# Benchmarking Results from Classification and Regression

#### Set Up

In [1]:
import pandas as pd
import numpy as np
import site
import os

In [2]:
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import TimeSeriesSplit
from sklearn.utils.class_weight import compute_class_weight

from sklearn.metrics import (
    precision_score, recall_score, f1_score, matthews_corrcoef,
    mean_squared_error, mean_absolute_error, r2_score, confusion_matrix
)

import torch
import torch.nn as nn
import torch.nn.functional as F

from torch.utils.data import Dataset, DataLoader
from torch.optim import Adam
from torch.optim.lr_scheduler import ReduceLROnPlateau
from contextlib import nullcontext

import random

from unicodedata import bidirectional

### Utility Classes and Functions

In [3]:
def set_global_seeds(seed: int = 42):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False

set_global_seeds(42)

# Datasets
class SequenceDataset(Dataset):
    def __init__(self, X, y):
        self.X = torch.tensor(X, dtype=torch.float32)
        self.y = torch.tensor(y, dtype=torch.float32)

    def __len__(self):
        return self.X.shape[0]

    def __getitem__(self, idx):
        return self.X[idx], self.y[idx]

class OrdinalSequenceDataset(Dataset):
    def __init__(self, X, T):
        self.X = torch.tensor(X, dtype=torch.float32)
        self.T = torch.tensor(T, dtype=torch.float32)

    def __len__(self):
        return self.X.shape[0]

    def __getitem__(self, idx):
        return self.X[idx], self.T[idx]

def make_cumulative_targets(y_int, K):
    y = y_int.reshape(-1, 1)
    ks = np.arange(K-1).reshape(1, -1)
    return (y > ks).astype(np.float32)

def decode_ordinal(probs, thr=0.5):
    return (probs >= thr).sum(axis=1)

# Models
class OrdinalHeadCORN(nn.Module):
    def __init__(self, in_dim, K):
        super().__init__()
        self.fc = nn.Linear(in_dim, K-1)

    def forward(self, h):
        return self.fc(h)


class OrdinalHeadCORAL(nn.Module):
    def __init__(self, in_dim, K):
        super().__init__()
        self.w = nn.Linear(in_dim, 1, bias=False)
        self._beta = nn.Parameter(torch.zeros(K-1))
        self.softplus = nn.Softplus()

    def forward(self, h):
        base = self.w(h)
        deltas = self.softplus(self._beta)
        b = torch.cumsum(deltas, dim=0)
        return base - b



class RNNHead(nn.Module):
    # Shared head:
    #   - RNN stack (LSTM/GRU, uni/bi)
    #   - BatchNorm + Dense(32, ReLU) + Dropout
    #   - Output layer (1 unit): linear (regression) or logits (classification)
    def __init__(self, input_size, rnn_type='LSTM', bidirectional=False, problem_type='classification',
                 n_classes=6, ordinal_head='coral', hidden1=128, hidden2=64, num_layers=1,
                 inter_rnn_drop=0.1, dropout=0.3, use_layernorm=False):
        super().__init__()
        self.problem_type = problem_type
        self.bidirectional = bidirectional
        self.rnn_type = rnn_type.upper()
        self.n_classes = n_classes
        self.ordinal_head = ordinal_head
        self.num_layers = int(num_layers)
        self.hidden1 = int(hidden1)
        self.hidden2 = int(hidden2)

        if self.num_layers not in (1, 2):
            raise ValueError("num_layers must be 1 or 2")

        rnn_cls = {'LSTM': nn.LSTM, 'GRU': nn.GRU}[('GRU' if 'GRU' in self.rnn_type else 'LSTM')]

        self.rnn1 = rnn_cls(
            input_size=input_size, hidden_size=self.hidden1, num_layers=1,
            batch_first=True, dropout=0.0, bidirectional=bidirectional
        )

        self.inter_rnn_drop = nn.Dropout(float(inter_rnn_drop))

        self.rnn2 = None
        if self.num_layers == 2:
            self.rnn2 = rnn_cls(
                input_size=self.hidden1*(2 if bidirectional else 1), hidden_size=self.hidden2, num_layers=1,
                batch_first=True, dropout=0.0, bidirectional=bidirectional
            )
            feat_dim = self.hidden2*(2 if bidirectional else 1)
        else:
            feat_dim = self.hidden1*(2 if bidirectional else 1)

        if use_layernorm:
            self.bn = nn.LayerNorm(feat_dim)
        else:
            self.bn = nn.BatchNorm1d(feat_dim)
        self.fc = nn.Linear(feat_dim, 32)
        self.drop = nn.Dropout(float(dropout))
        if self.problem_type == 'multiclass':
            head = self.ordinal_head.lower() if isinstance(self.ordinal_head, str) else 'coral'
            if head == 'corn':
                self.out = OrdinalHeadCORN(32, self.n_classes)
            else:
                self.out = OrdinalHeadCORAL(32, self.n_classes)
        else:
            self.out = nn.Linear(32, 1)

    def forward(self, x):
        # x: [B, T, F]
        out, _ = self.rnn1(x)
        if self.num_layers == 2:
            out = self.inter_rnn_drop(out)   # inter-layer dropout (sequence-wise)
            out, _ = self.rnn2(out)
        # take last timestep: [B, T, H] -> [B, H]
        out = out[:, -1, :]
        out = self.bn(out)
        out = F.relu(self.fc(out))
        out = self.drop(out)
        out = self.out(out)  # shape [B,1]
        return out  # regression: raw; classification: logits


def build_model(input_shape, model_type='LSTM', problem_type='regression', n_classes=6, ordinal_head='coral',
                hidden1=128, hidden2=64, num_layers=2, inter_rnn_drop=0.1, dropout=0.3, use_layernorm=False):
    seq_len, n_features = input_shape
    model_type = model_type.upper()
    kwargs = dict(
        problem_type=problem_type,
        n_classes=n_classes,
        ordinal_head=ordinal_head,
        hidden1=hidden1,
        hidden2=hidden2,
        num_layers=num_layers,
        inter_rnn_drop=inter_rnn_drop,
        dropout=dropout,
        use_layernorm=use_layernorm,
    )
    if model_type == 'LSTM':
        return RNNHead(n_features, rnn_type='LSTM', bidirectional=False, **kwargs)
    elif model_type == 'BILSTM':
        return RNNHead(n_features, rnn_type='LSTM', bidirectional=True, **kwargs)
    elif model_type == 'GRU':
        return RNNHead(n_features, rnn_type='GRU', bidirectional=False, **kwargs)
    elif model_type == 'BIGRU':
        return RNNHead(n_features, rnn_type='GRU', bidirectional=True, **kwargs)
    else:
        raise ValueError("Model type must be one of: ['LSTM','BiLSTM','GRU','BiGRU']")

# Early Stopping (PyTorch)
class EarlyStopper:
    def __init__(self, patience=15, min_delta=0.0, restore_best=True):
        self.patience = patience
        self.min_delta = min_delta
        self.restore_best = restore_best
        self.best_loss = float('inf')
        self.counter = 0
        self.best_state = None

    def step(self, val_loss, model):
        improved = (self.best_loss - val_loss) > self.min_delta
        if improved:
            self.best_loss = val_loss
            self.counter = 0
            if self.restore_best:
                # Deep copy state dict
                self.best_state = {k: v.detach().clone() for k, v in model.state_dict().items()}
        else:
            self.counter += 1
        return self.counter >= self.patience

    def restore(self, model):
        if self.restore_best and self.best_state is not None:
            model.load_state_dict(self.best_state)

In [4]:
def edge_labels_from_edges(edges, decimals=1):
    labels = []
    C = len(edges) - 1
    for i in range(C):
        lo, hi = edges[i], edges[i+1]
        if i == 0:
            labels.append(f"≤ {hi*100:.{decimals}f}%")
        elif i == C - 1:
            labels.append(f"> {lo*100:.{decimals}f}%")
        else:
            labels.append(f"({lo*100:.{decimals}f}%,{hi*100:.{decimals}f}%]")
    return labels

def pct_return(series, h):
    return series.shift(-h) / series - 1.0

def safe_quantile_edges(x, n_classes=6):
    qs = np.linspace(0, 1, n_classes + 1)
    edges = np.quantile(x, qs)
    for i in range(1, len(edges)):
        if edges[i] <= edges[i-1]:
            edges[i] = np.nextafter(edges[i-1], np.inf)
    return edges

def bucketize_with_edges(x, edges):
    inner = edges[1:-1]
    return np.digitize(x, inner, right=True).astype(int)

@torch.no_grad()
def collect_logits(model, loader, device):
    model.eval()
    chunks = []
    for xb, _ in loader:
        xb = xb.to(device)
        chunks.append(model(xb).detach().cpu())
    return torch.cat(chunks, dim=0)

def find_taus_per_threshold(Z_val, y_val_idx, grid=np.linspace(0, 1, 100)):
    if isinstance(Z_val, torch.Tensor):
        Z_val = Z_val.numpy()
    P_val = 1.0 / (1.0 + np.exp(-Z_val))
    P_rep = monotone_repair_numpy(P_val)
    K_1 = P_rep.shape[1]
    best_taus = np.full(K_1, 0.5, dtype=np.float32)
    for k in range(K_1):
        best_f1, best_tau = -1.0, 0.5
        for tau in grid:
            y_hat = decode_ordinal_with_taus(P_rep, taus_override={k: tau})
            f1 = f1_score(y_val_idx, y_hat, average='macro', zero_division=0)
            if f1 > best_f1:
                best_f1, best_tau = f1, tau
        best_taus[k] = best_tau
    return best_taus

def monotone_repair_numpy(P):
    P = np.asarray(P).copy()
    for k in range(P.shape[1] - 2, -1, -1):
        P[:, k] = np.maximum(P[:, k], P[:, k+1])
    return P

def decode_ordinal_with_taus(P_rep, taus=None, taus_override=None):
    N, K_1 = P_rep.shape
    if taus is None:
        taus = np.full(K_1, 0.5, dtype=np.float32)
    if taus_override:
        taus = taus.copy()
        for k, v in taus_override.items():
            taus[k] = v
    comp = (P_rep >= taus.reshape(1, -1)).astype(np.int32)
    return comp.sum(axis=1).astype(np.int64)

def ordinal_to_class_probs(P_rep):
    N, K_1 = P_rep.shape
    K = K_1 + 1
    Pc = np.empty((N, K), dtype=np.float32)
    Pc[:, 0] = 1.0 - P_rep[:, 0]
    for c in range(1, K - 1):
        Pc[:, c] = np.clip(P_rep[:, c-1] - P_rep[:, c], 0.0, 1.0)
    Pc[:, K - 1] = P_rep[:, K_1 - 1]
    s = Pc.sum(axis=1, keepdims=True)
    return Pc / np.maximum(s, 1e-8)


def best_threshold_from_val(y_true, y_scores, metric='f1', grid=None):
    """
    Sweep probability thresholds on validation scores to maximize a metric.
    metric can be 'f1', 'mcc', 'accuracy', or a callable(y_true,y_pred)->float.
    Returns (best_threshold, best_metric_value).
    """
    y_true = np.asarray(y_true).astype(int)
    y_scores = np.asarray(y_scores).astype(float)
    if grid is None:
        grid = np.linspace(0.05, 0.95, 181)
    metric_fn = None
    if callable(metric):
        metric_fn = metric
    else:
        name = str(metric).lower()
        if name == 'f1':
            metric_fn = lambda yt, yp: f1_score(yt, yp, zero_division=0)
        elif name == 'mcc':
            metric_fn = lambda yt, yp: matthews_corrcoef(yt, yp)
        elif name in ('acc', 'accuracy'):
            metric_fn = lambda yt, yp: (yt == yp).mean()
        else:
            raise ValueError(f"Unsupported metric '{metric}'")
    best_thr = 0.5
    best_val = -np.inf
    for thr in grid:
        preds = (y_scores >= thr).astype(int)
        val = metric_fn(y_true, preds)
        if val > best_val + 1e-12 or (abs(val - best_val) <= 1e-12 and thr < best_thr):
            best_val = float(val)
            best_thr = float(thr)
    return best_thr, best_val

## Stock Prediction Pipeline

In [5]:
class StockPredictionPipeline:
    def __init__(self, df, feature_columns, model_type='LSTM', sequence_length=24, problem_type='regression', horizon_steps=1, n_classes=6, ordinal_head='coral', fixed_bucket_edges=None,
                 hidden1=256, hidden2=64, num_layers=1, inter_rnn_drop=0.0, dropout=0.4,
                 batch_size=32, learning_rate=7e-3, weight_decay=2e-3, lr_patience=7, lr_factor=0.5,
                 early_stopping_patience=20, max_epochs=20, use_layernorm=False, huber_delta=1.0, early_stopping_min_delta=0.0):
        self.df = df.copy()
        self.feature_columns = feature_columns
        self.model_type = model_type
        self.sequence_length = sequence_length
        self.problem_type = problem_type
        self.horizon_steps = horizon_steps
        self.results = []
        self.loss_curves = []
        self.n_classes = n_classes
        self.ordinal_head = ordinal_head
        self.hidden1 = hidden1
        self.hidden2 = hidden2
        self.num_layers = num_layers
        self.inter_rnn_drop = inter_rnn_drop
        self.dropout = dropout
        self.batch_size = batch_size
        self.learning_rate = learning_rate
        self.weight_decay = weight_decay
        self.lr_patience = lr_patience
        self.lr_factor = lr_factor
        self.early_stopping_patience = early_stopping_patience
        self.max_epochs = max_epochs
        self.use_layernorm = use_layernorm
        self.huber_delta = huber_delta
        self.early_stopping_min_delta = early_stopping_min_delta
        self.fixed_bucket_edges = None
        if fixed_bucket_edges is not None:
            edges = np.asarray(fixed_bucket_edges, dtype=float)
            if edges.ndim != 1:
                raise ValueError("fixed_bucket_edges must be a 1D sequence of monotonically increasing numbers")
            if edges.size < 2:
                raise ValueError("fixed_bucket_edges must contain at least two values")
            if np.any(np.diff(edges) <= 0):
                raise ValueError("fixed_bucket_edges must be strictly increasing")
            self.n_classes = int(edges.size - 1)
            self.fixed_bucket_edges = edges

        # Validate
        self._validate_inputs()

        # Device & precision
        self.device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
        self.mixed_precision = torch.cuda.is_available()

        print(f"Pipeline initialized for a '{self.problem_type}' problem "
              f"with horizon {self.horizon_steps} steps. Device: {self.device}")

    def _validate_inputs(self):
        missing_cols = [col for col in self.feature_columns if col not in self.df.columns]
        if missing_cols:
            raise ValueError(f"Missing feature columns: {missing_cols}")

        if 'close' not in self.df.columns and 'close_price' not in self.df.columns:
            raise ValueError("No 'close' or 'close_price' column found in data")

        valid_models = ['LSTM', 'BiLSTM', 'GRU', 'BiGRU']
        if self.model_type not in valid_models:
            raise ValueError(f"Model type must be one of: {valid_models}")

        if self.problem_type not in ['regression', 'classification', 'multiclass']:
            raise ValueError("Problem type must be 'regression', 'classification', or 'multiclass'")

    def create_target_variable(self, company_data):
        company_data = company_data.copy()
        price_col = 'close' if 'close' in company_data.columns else 'close_price'
        if 'date' in company_data.columns:
            company_data = company_data.sort_values('date')
            
        h = self.horizon_steps

        company_data['target_regression'] = (
            np.log(company_data[price_col].shift(-h)) - np.log(company_data[price_col])
        )
        company_data['target_direction'] = (company_data['target_regression'] > 0).astype(int)
        company_data['ret_h'] = pct_return(company_data[price_col], h)
        if self.problem_type == 'multiclass':
            company_data = company_data.dropna(subset=['ret_h'])
        else:
            company_data = company_data.dropna()
        return company_data

    def create_sequences(self, features, *targets):
        X = []
        y_sequences = [[] for _ in targets]
        for i in range(self.sequence_length, len(features)):
            X.append(features[i-self.sequence_length:i])
            for j, target in enumerate(targets):
                y_sequences[j].append(target[i])
        return (np.array(X),) + tuple(np.array(y) for y in y_sequences)

    def _train_one_epoch(self, model, loader, optimizer, loss_fn, scaler):
        model.train()
        total_loss = 0.0
        for xb, yb in loader:
            xb = xb.to(self.device)
            yb = yb.to(self.device).view(-1, 1)

            optimizer.zero_grad(set_to_none=True)

            ctx = torch.amp.autocast('cuda') if self.mixed_precision else nullcontext()
            with ctx:
                logits = model(xb)
                loss = loss_fn(logits, yb)

            if self.mixed_precision:
                scaler.scale(loss).backward()
                scaler.unscale_(optimizer)
                torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0)
                scaler.step(optimizer)
                scaler.update()
            else:
                loss.backward()
                torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0)
                optimizer.step()

            total_loss += loss.item() * xb.size(0)

        return total_loss / len(loader.dataset)

    @torch.no_grad()
    def _eval_one_epoch(self, model, loader, loss_fn):
        model.eval()
        total_loss = 0.0
        for xb, yb in loader:
            xb = xb.to(self.device)
            yb = yb.to(self.device).view(-1, 1)
            logits = model(xb)
            loss = loss_fn(logits, yb)
            total_loss += loss.item() * xb.size(0)
        return total_loss / len(loader.dataset)

    def _train_one_epoch_multiclass(self, model, loader, optimizer, scaler, *, pos_weight=None):
        model.train()
        total = 0.0
        for xb, yb in loader:
            xb = xb.to(self.device)
            yb = yb.to(self.device)
            optimizer.zero_grad(set_to_none=True)
            ctx = torch.amp.autocast('cuda') if self.mixed_precision else nullcontext()
            with ctx:
                logits = model(xb)
                bces = []
                for k in range(logits.shape[1]):
                    w = None if pos_weight is None else pos_weight[k]
                    bce_k = F.binary_cross_entropy_with_logits(logits[:, k], yb[:, k], pos_weight=w)
                    bces.append(bce_k)
                loss = torch.stack(bces).mean()
            if self.mixed_precision:
                scaler.scale(loss).backward()
                scaler.unscale_(optimizer)
                torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
                scaler.step(optimizer)
                scaler.update()
            else:
                loss.backward()
                torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
                optimizer.step()
            total += float(loss.item()) * xb.size(0)
        return total / len(loader.dataset)

    @torch.no_grad()
    def _eval_one_epoch_multiclass(self, model, loader, pos_weight=None):
        model.eval()
        total = 0.0
        for xb, yb in loader:
            xb = xb.to(self.device)
            yb = yb.to(self.device)
            logits = model(xb)
            bces = []
            for k in range(logits.shape[1]):
                w = None if pos_weight is None else pos_weight[k]
                bce_k = F.binary_cross_entropy_with_logits(logits[:, k], yb[:, k], pos_weight=w)
                bces.append(bce_k)
            loss = torch.stack(bces).mean()
            total += float(loss.item()) * xb.size(0)
        return total / len(loader.dataset)

    @torch.no_grad()
    def _predict(self, model, loader):
        model.eval()
        outs = []
        for xb, _ in loader:
            xb = xb.to(self.device)
            logits = model(xb).squeeze(1).detach().cpu().numpy()
            outs.append(logits)
        return np.concatenate(outs, axis=0)

    def build_model(self, input_shape):
        model = build_model(
            input_shape,
            model_type=self.model_type,
            problem_type=self.problem_type,
            n_classes=self.n_classes,
            ordinal_head=self.ordinal_head,
            hidden1=self.hidden1,
            hidden2=self.hidden2,
            num_layers=self.num_layers,
            inter_rnn_drop=self.inter_rnn_drop,
            dropout=self.dropout,
            use_layernorm=self.use_layernorm
        )
        return model.to(self.device)

    def process_company(self, company_name, company_data, sector):
        print(f"\nProcessing {company_name} ({sector})...")
        try:
            company_data = self.create_target_variable(company_data)

            # Min samples requirement (same heuristic)
            min_samples = self.sequence_length + 75 + self.horizon_steps
            if len(company_data) < min_samples:
                print(f"Insufficient data for {company_name} ({len(company_data)} < {min_samples}). Skipping...")
                return None

            if company_data[self.feature_columns].isnull().any().any():
                print(f"Missing values in features for {company_name}. Skipping...")
                return None

            features = company_data[self.feature_columns].values
            target_reg = company_data['target_regression'].values
            target_dir = company_data['target_direction'].values

            # Create sequences
            X_raw, y_reg, y_dir = self.create_sequences(features, target_reg, target_dir)

            # TimeSeriesSplit
            n_splits = min(5, len(X_raw) // 50)
            if n_splits < 3:
                print(f"Insufficient data for proper time series validation for {company_name}. Skipping...")
                return None

            tscv = TimeSeriesSplit(n_splits=n_splits)
            splits = list(tscv.split(X_raw))
            train_idx, test_idx = splits[-1]

            # Train/Val split (last 20% of train for val)
            val_size = int(0.2 * len(train_idx))
            if val_size == 0:
                print(f'Insufficient data for validation split for {company_name}. Skipping...')
                return None
            final_train_idx = train_idx[:-val_size]
            val_idx = train_idx[-val_size:]
            
            if self.horizon_steps > 1:
                print("Adjusting for multi-step horizon...")
                gap = self.horizon_steps
                if len(final_train_idx) > gap:
                    final_train_idx = final_train_idx[:-gap]  # drop last h labels from train
                if len(val_idx) > gap:
                    val_idx = val_idx[gap:]  # drop last h labels from val
            if len(final_train_idx) == 0 or len(val_idx) == 0:
                print(f'Insufficient data after horizon adjustment for {company_name}. Skipping...')
                return None

            X_train_raw, X_val_raw, X_test_raw = X_raw[final_train_idx], X_raw[val_idx], X_raw[test_idx]
            
            F = X_raw.shape[-1]
            feat_scaler = StandardScaler()
            X_train = feat_scaler.fit_transform(X_train_raw.reshape(-1, F)).reshape(X_train_raw.shape)
            X_val   = feat_scaler.transform(X_val_raw.reshape(-1, F)).reshape(X_val_raw.shape)
            X_test  = feat_scaler.transform(X_test_raw.reshape(-1, F)).reshape(X_test_raw.shape)

            if self.problem_type == 'multiclass':
                if 'ret_h' not in company_data.columns:
                    raise RuntimeError("Expected 'ret_h' for ordinal targets but it was missing.")
                ret_full = company_data['ret_h'].values
                ret_seq_full = ret_full[self.sequence_length:]

                ret_train = ret_seq_full[final_train_idx]
                ret_val = ret_seq_full[val_idx]
                ret_test = ret_seq_full[test_idx]

                if self.fixed_bucket_edges is not None:
                    edges = self.fixed_bucket_edges
                    if int(edges.shape[0] - 1) != self.n_classes:
                        raise ValueError("fixed_bucket_edges length must match n_classes+1")
                else:
                    edges = safe_quantile_edges(ret_train, n_classes=self.n_classes)
                edges = np.asarray(edges, dtype=float)
                K = int(edges.shape[0] - 1)
                label_names = edge_labels_from_edges(edges, decimals=1)

                y_bucket = bucketize_with_edges(ret_seq_full, edges).astype(np.int64)
                y_train = y_bucket[final_train_idx]
                y_val = y_bucket[val_idx]
                y_test = y_bucket[test_idx]

                T_train = make_cumulative_targets(y_train.astype(np.int64), K)
                T_val = make_cumulative_targets(y_val.astype(np.int64), K)
                T_test = make_cumulative_targets(y_test.astype(np.int64), K)

                train_ds = OrdinalSequenceDataset(X_train, T_train)
                val_ds = OrdinalSequenceDataset(X_val, T_val)
                test_ds = OrdinalSequenceDataset(X_test, T_test)

                train_loader = DataLoader(train_ds, batch_size=self.batch_size, shuffle=False, drop_last=False, num_workers=0)
                val_loader = DataLoader(val_ds, batch_size=self.batch_size, shuffle=False, drop_last=False, num_workers=0)
                test_loader = DataLoader(test_ds, batch_size=self.batch_size, shuffle=False, drop_last=False, num_workers=0)

                model = self.build_model((self.sequence_length, len(self.feature_columns)))

                pos_rate = T_train.mean(axis=0)
                pos_weight = (1.0 - pos_rate) / np.clip(pos_rate, 1e-6, 1.0)
                pos_weight_tensor = torch.tensor(pos_weight, dtype=torch.float32).to(self.device)

                optimizer = Adam(model.parameters(), lr=self.learning_rate, eps=1e-7, weight_decay=self.weight_decay)
                scheduler = ReduceLROnPlateau(optimizer, mode='min', factor=self.lr_factor, patience=self.lr_patience, min_lr=1e-7)
                early_stopper = EarlyStopper(patience=self.early_stopping_patience, min_delta=self.early_stopping_min_delta, restore_best=True)
                scaler = torch.amp.GradScaler('cuda', enabled=self.mixed_precision)

                max_epochs = self.max_epochs
                best_val = float('inf')
                epochs_trained = 0
                company_loss_rows = []

                for epoch in range(1, max_epochs + 1):
                    train_loss = self._train_one_epoch_multiclass(model, train_loader, optimizer, scaler, pos_weight=pos_weight_tensor)
                    val_loss = self._eval_one_epoch_multiclass(model, val_loader, pos_weight=pos_weight_tensor)
                    scheduler.step(val_loss)
                    stop = early_stopper.step(val_loss, model)
                    epochs_trained = epoch

                    row = {
                        'company': company_name,
                        'sector': sector,
                        'model_type': self.model_type,
                        'problem_type': self.problem_type,
                        'sequence_length': self.sequence_length,
                        'horizon_steps': self.horizon_steps,
                        'epoch': epoch,
                        'train_loss': float(train_loss),
                        'val_loss': float(val_loss),
                        'train_samples': len(X_train),
                        'val_samples': len(X_val),
                        'test_samples': len(X_test),
                    }

                    company_loss_rows.append(row)
                    self.loss_curves.append(row)

                    if epoch % 10 == 0 or stop:
                        print(f"  Epoch {epoch:03d} - train {train_loss:.5f} | val {val_loss:.5f}")

                    if stop:
                        break

                early_stopper.restore(model)

                Z_val = collect_logits(model, val_loader, self.device)
                taus = find_taus_per_threshold(Z_val, y_val.astype(np.int64))
                P_cum_val = torch.sigmoid(Z_val).cpu().numpy()
                P_rep_val = monotone_repair_numpy(P_cum_val)
                P_class_val = ordinal_to_class_probs(P_rep_val)
                mid_cut = (K // 2)
                y_val_dir = (y_val >= mid_cut).astype(int)
                prob_val_up = P_class_val[:, mid_cut:].sum(axis=1)
                dir_thr, dir_thr_score = best_threshold_from_val(y_val_dir, prob_val_up, metric='mcc')

                Z_test = collect_logits(model, test_loader, self.device)
                P_cum = torch.sigmoid(Z_test).cpu().numpy()
                P_rep = monotone_repair_numpy(P_cum)
                P_class = ordinal_to_class_probs(P_rep)

                y_pred_labels = decode_ordinal_with_taus(P_rep, taus=taus)
                y_true_labels = y_test

                labels = list(range(K))
                cm_counts = confusion_matrix(y_true_labels, y_pred_labels, labels=labels)
                cm_norm = confusion_matrix(y_true_labels, y_pred_labels, labels=labels, normalize='true')

                micro_acc = (y_true_labels == y_pred_labels).mean()
                macro_f1 = f1_score(y_true_labels, y_pred_labels, average='macro', zero_division=0)

                ret_seq_train = ret_seq_full[final_train_idx].astype(np.float32)
                mu_c = np.array([
                    ret_seq_train[y_train == c].mean() if np.any(y_train == c) else 0.0
                    for c in range(K)
                ], dtype=np.float32)

                expected_ret = (P_class * mu_c[None, :]).sum(axis=1)
                expected_ret_mean = float(expected_ret.mean())

                prob_test_up = P_class[:, mid_cut:].sum(axis=1)
                y_true_dir = (y_true_labels >= mid_cut).astype(int)
                y_pred_dir = (prob_test_up >= dir_thr).astype(int)
                precision = precision_score(y_true_dir, y_pred_dir, zero_division=0)
                recall = recall_score(y_true_dir, y_pred_dir, zero_division=0)
                f1 = f1_score(y_true_dir, y_pred_dir, zero_division=0)
                mcc = matthews_corrcoef(y_true_dir, y_pred_dir)
                directional_accuracy = (y_true_dir == y_pred_dir).mean()

                result = {
                    'company': company_name,
                    'sector': sector,
                    'model_type': self.model_type,
                    'problem_type': self.problem_type,
                    'horizon_steps': self.horizon_steps,
                    'macro_f1': macro_f1,
                    'micro_accuracy': micro_acc,
                    'expected_return_mean': expected_ret_mean,
                    'mse': np.nan,
                    'mae': np.nan,
                    'r2': np.nan,
                    'mcc': mcc,
                    'f1': f1,
                    'precision': precision,
                    'recall': recall,
                    'directional_accuracy': directional_accuracy,
                'val_directional_accuracy': val_directional_accuracy if self.problem_type == 'classification' else np.nan,
                'val_mcc': val_mcc if self.problem_type == 'classification' else np.nan,
                'val_f1': val_f1 if self.problem_type == 'classification' else np.nan,
                'val_precision': val_precision if self.problem_type == 'classification' else np.nan,
                'val_recall': val_recall if self.problem_type == 'classification' else np.nan,
                    'n_samples': int(X_raw.shape[0]),
                    'train_samples': int(X_train.shape[0]),
                    'val_samples': int(X_val.shape[0]),
                    'test_samples': int(X_test.shape[0]),
                    'epochs_trained': epochs_trained
                }
                result['confusion_matrix'] = cm_counts.tolist()
                result['confusion_matrix_normalized'] = cm_norm.tolist()
                result['bucket_edges'] = edges.tolist()
                result['bucket_labels'] = label_names
                result['taus'] = taus.astype(float).tolist()
                result['direction_threshold'] = dir_thr
                result['direction_threshold_metric'] = dir_thr_score

                print(f"  Multiclass -> Micro Acc: {micro_acc:.4f}, Macro F1: {macro_f1:.4f}, Expected Return: {expected_ret_mean:.6f}")
                print(f"  Directional threshold -> τ={dir_thr:.3f} (val F1={dir_thr_score:.4f})")

                del model
                torch.cuda.empty_cache()
                return result

            if self.problem_type == 'regression':
                y_train, y_val, y_test = y_reg[final_train_idx], y_reg[val_idx], y_reg[test_idx]
                target_scaler = StandardScaler()
                y_train_scaled = target_scaler.fit_transform(y_train.reshape(-1, 1)).flatten()
                y_val_scaled   = target_scaler.transform(y_val.reshape(-1, 1)).flatten()
                train_target, val_target = y_train_scaled, y_val_scaled
            else:
                y_train, y_val, y_test = y_dir[final_train_idx], y_dir[val_idx], y_dir[test_idx]
                train_target, val_target = y_train, y_val
                target_scaler = None

            # class balance note
            if self.problem_type == 'classification':
                class_ratio = np.mean(y_train)
                if class_ratio < 0.1 or class_ratio > 0.9:
                    print(f"Severe class imbalance for {company_name} ({class_ratio:.3f}). Consider using class weights.")

            # datasets & loaders
            train_ds = SequenceDataset(X_train, train_target)
            val_ds   = SequenceDataset(X_val,   val_target)
            test_ds  = SequenceDataset(X_test,  y_test)

            train_bs = min(self.batch_size, len(train_ds))
            if train_bs < 2:
                print(f'Insufficient training samples for {company_name} (train size={len(train_ds)}). Skipping...')
                return None
            if len(train_ds) % train_bs == 1 and train_bs > 2:
                train_bs -= 1  # avoid batch size 1 for BatchNorm
            val_bs = min(self.batch_size, len(val_ds))
            test_bs = min(self.batch_size, len(test_ds))

            train_loader = DataLoader(train_ds, batch_size=train_bs, shuffle=False,  drop_last=False, num_workers=0)
            val_loader   = DataLoader(val_ds,   batch_size=val_bs,   shuffle=False, drop_last=False, num_workers=0)
            test_loader  = DataLoader(test_ds,  batch_size=test_bs,  shuffle=False, drop_last=False, num_workers=0)

            # build model
            model = self.build_model((self.sequence_length, len(self.feature_columns)))

            # loss functions
            if self.problem_type == 'regression':
                loss_fn = nn.HuberLoss(delta=self.huber_delta)
            else:
                # use BCEWithLogitsLoss for numerical stability (logits input)
                loss_fn = nn.BCEWithLogitsLoss()

            # optimizer & scheduler
            optimizer = Adam(model.parameters(), lr=self.learning_rate, eps=1e-7, weight_decay=self.weight_decay)
            scheduler = ReduceLROnPlateau(optimizer, mode='min', factor=self.lr_factor, patience=self.lr_patience, min_lr=1e-7)
            early_stopper = EarlyStopper(patience=self.early_stopping_patience, min_delta=self.early_stopping_min_delta, restore_best=True)
            scaler = torch.amp.GradScaler('cuda', enabled=self.mixed_precision)

            # training loop
            max_epochs = self.max_epochs
            best_val = float('inf')
            epochs_trained = 0
            company_loss_rows = []  

            for epoch in range(1, max_epochs + 1):
                train_loss = self._train_one_epoch(model, train_loader, optimizer, loss_fn, scaler)
                val_loss = self._eval_one_epoch(model, val_loader, loss_fn)
                scheduler.step(val_loss)
                stop = early_stopper.step(val_loss, model)
                epochs_trained = epoch

                
                row = {
                    'company': company_name,
                    'sector': sector,
                    'model_type': self.model_type,
                    'problem_type': self.problem_type,
                    'sequence_length': self.sequence_length,
                    'horizon_steps': self.horizon_steps,
                    'epoch': epoch,
                    'train_loss': float(train_loss),
                    'val_loss': float(val_loss),
                    'train_samples': len(X_train),
                    'val_samples': len(X_val),
                    'test_samples': len(X_test),
                }
                
                company_loss_rows.append(row)
                self.loss_curves.append(row)

                if epoch % 10 == 0 or stop:
                    print(f"  Epoch {epoch:03d} - train {train_loss:.5f} | val {val_loss:.5f}")

                if stop:
                    break

            # restore best model weights (like Keras restore_best_weights=True)
            early_stopper.restore(model)

            # summarize train/val loss for overfitting checks
            best_train_loss = np.nan
            best_val_loss = np.nan
            final_train_loss = np.nan
            final_val_loss = np.nan
            if company_loss_rows:
                best_val_loss = min(r['val_loss'] for r in company_loss_rows)
                best_train_loss = min(r['train_loss'] for r in company_loss_rows)
                final_train_loss = company_loss_rows[-1]['train_loss']
                final_val_loss = company_loss_rows[-1]['val_loss']

            # predictions
            y_pred_raw = self._predict(model, test_loader)  # raw/regression or logits

            if self.problem_type == 'regression':
                y_pred_unscaled = target_scaler.inverse_transform(y_pred_raw.reshape(-1,1)).flatten() if target_scaler is not None else y_pred_raw
                mse = mean_squared_error(y_test, y_pred_unscaled)
                mae = mean_absolute_error(y_test, y_pred_unscaled)
                r2  = r2_score(y_test, y_pred_unscaled)

                # directional metrics (derived)
                y_test_dir = (y_reg[test_idx] > 0).astype(int)
                y_pred_dir = (y_pred_unscaled > 0).astype(int)
            else:
                # logits -> probs via sigmoid -> learn best threshold on VAL
                val_logits = self._predict(model, val_loader)
                val_probs = 1.0 / (1.0 + np.exp(-val_logits))
                best_thr, best_thr_score = best_threshold_from_val(y_val, val_probs, metric='mcc')
                val_pred_dir = (val_probs >= best_thr).astype(int)
                val_precision = precision_score(y_val, val_pred_dir, zero_division=0)
                val_recall = recall_score(y_val, val_pred_dir, zero_division=0)
                val_f1 = f1_score(y_val, val_pred_dir, zero_division=0)
                val_mcc = matthews_corrcoef(y_val, val_pred_dir)
                val_directional_accuracy = (y_val == val_pred_dir).mean()
                probs = 1.0 / (1.0 + np.exp(-y_pred_raw))
                y_pred_dir = (probs >= best_thr).astype(int)
                y_test_dir = y_test
                mse = mae = r2 = np.nan

            precision = precision_score(y_test_dir, y_pred_dir, zero_division=0)
            recall    = recall_score(y_test_dir, y_pred_dir, zero_division=0)
            f1        = f1_score(y_test_dir, y_pred_dir, zero_division=0)
            mcc       = matthews_corrcoef(y_test_dir, y_pred_dir)
            directional_accuracy = np.mean(y_test_dir == y_pred_dir)

            result = {
                'company': company_name,
                'sector': sector,
                'model_type': self.model_type,
                'problem_type': self.problem_type,
                'horizon_steps': self.horizon_steps,
                'mse': mse,
                'mae': mae,
                'r2': r2,
                'mcc': mcc,
                'f1': f1,
                'precision': precision,
                'recall': recall,
                'directional_accuracy': directional_accuracy,
                'val_directional_accuracy': val_directional_accuracy if self.problem_type == 'classification' else np.nan,
                'val_mcc': val_mcc if self.problem_type == 'classification' else np.nan,
                'val_f1': val_f1 if self.problem_type == 'classification' else np.nan,
                'val_precision': val_precision if self.problem_type == 'classification' else np.nan,
                'val_recall': val_recall if self.problem_type == 'classification' else np.nan,
                'n_samples': int(X_raw.shape[0]),
                'train_samples': int(X_train.shape[0]),
                'val_samples': int(X_val.shape[0]),
                'test_samples': int(X_test.shape[0]),
                'epochs_trained': epochs_trained
            }
            if self.problem_type == 'classification':
                result['best_threshold'] = best_thr
                result['best_threshold_metric'] = best_thr_score

            if self.problem_type == 'regression':
                print(f"  Regression -> MSE: {mse:.6f}, MAE: {mae:.6f}, R²: {r2:.4f}")
            elif self.problem_type == 'classification':
                print(f"  Classification -> best τ={best_thr:.3f} (val F1={best_thr_score:.4f})")
            print(f"  Directional -> Accuracy: {directional_accuracy:.4f}, MCC: {mcc:.4f}, F1: {f1:.4f}")

            # explicit cleanup (PyTorch handles this, but keeps parity with Enrique2025)
            del model
            torch.cuda.empty_cache()

            return result

        except Exception as e:
            print(f"Error processing {company_name}: {str(e)}")
            torch.cuda.empty_cache()
            return None

    def run_pipeline(self):
        company_col = None
        for col_name in ['ticker', 'company', 'symbol']:
            if col_name in self.df.columns:
                company_col = col_name
                break
        if company_col is None:
            company_col = self.df.columns[0]
            print(f"Warning: Using '{company_col}' as company identifier column")

        companies = self.df[company_col].unique()
        print(f"Processing {len(companies)} companies with {self.model_type} model...")
        print(f"Problem type: {self.problem_type}")
        print(f"Sequence length: {self.sequence_length}")
        print(f"Features: {self.feature_columns}")

        successful_companies = 0
        for i, company in enumerate(companies, 1):
            print(f"\n[{i}/{len(companies)}] Processing {company}...")
            company_data = self.df[self.df[company_col] == company].copy()
            sector = company_data['sector'].iloc[0] if 'sector' in company_data.columns else 'Unknown'
            result = self.process_company(company, company_data, sector)
            if result:
                self.results.append(result)
                successful_companies += 1

        print(f"\n{'='*80}")
        print(f"Pipeline completed: {successful_companies}/{len(companies)} companies processed successfully")
        print(f"{'='*80}")

        if self.results:
            self.results_df = pd.DataFrame(self.results)
            return self.results_df
        else:
            print("No companies were processed successfully!")
            return pd.DataFrame()


    def analyze_results(self):
        if not hasattr(self, 'results_df') or self.results_df.empty:
            print("No results to analyze!")
            return None

        df = self.results_df
        analysis = {}

        print("" + "="*80)
        print("STOCK PREDICTION PIPELINE RESULTS")
        print("="*80)
        print(f"Model: {self.model_type} | Problem: {self.problem_type}")
        print(f"Companies analyzed: {len(df)}")
        print(f"Average samples per company: {df['n_samples'].mean():.0f}")

        print("" + "="*50)
        print("OVERALL PERFORMANCE")
        print("="*50)
        if self.problem_type == 'regression':
            print(f"Mean Squared Error:     {df['mse'].mean():.6f} (±{df['mse'].std():.6f})")
            print(f"Mean Absolute Error:    {df['mae'].mean():.6f} (±{df['mae'].std():.6f})")
            print(f"R² Score:              {df['r2'].mean():.4f} (±{df['r2'].std():.4f})")
        if self.problem_type == 'multiclass' and 'micro_accuracy' in df.columns:
            print(f"Micro Accuracy:         {df['micro_accuracy'].mean():.4f} (±{df['micro_accuracy'].std():.4f})")
            print(f"Macro F1 Score:         {df['macro_f1'].mean():.4f} (±{df['macro_f1'].std():.4f})")
            if 'expected_return_mean' in df.columns:
                print(f"Expected Return:        {df['expected_return_mean'].mean():.6f} (±{df['expected_return_mean'].std():.4f})")

        print(f"Directional Accuracy:   {df['directional_accuracy'].mean():.4f} (±{df['directional_accuracy'].std():.4f})")
        print(f"Matthews Correlation:   {df['mcc'].mean():.4f} (±{df['mcc'].std():.4f})")
        print(f"F1 Score:              {df['f1'].mean():.4f} (±{df['f1'].std():.4f})")
        print(f"Precision:             {df['precision'].mean():.4f} (±{df['precision'].std():.4f})")
        print(f"Recall:                {df['recall'].mean():.4f} (±{df['recall'].std():.4f})")

        if self.problem_type == 'multiclass' and 'expected_return_mean' in df.columns:
            print("" + "="*50)
            print("TOP 10 BY EXPECTED RETURN (mean)")
            print("="*50)
            top_er = df.nlargest(10, 'expected_return_mean')
            for _, row in top_er.iterrows():
                print(f"{row['company']:<20} | {row['sector']:<15} | E[r]_mean: {row['expected_return_mean']:.4e} | Macro-F1: {row['macro_f1']:.3f}")

        if 'sector' in df.columns and df['sector'].nunique() > 1:
            print("" + "="*50)
            print("PERFORMANCE BY SECTOR")
            print("="*50)
            sector_stats = df.groupby('sector').agg({
                'directional_accuracy': ['mean', 'std', 'count'],
                'mcc': ['mean', 'std'],
                'r2': 'mean' if self.problem_type == 'regression' else lambda x: np.nan,
                'mae': 'mean' if self.problem_type == 'regression' else lambda x: np.nan
            }).round(4)
            sector_stats.columns = ['_'.join(col).strip() if col[1] else col[0] for col in sector_stats.columns]
            sector_stats = sector_stats.sort_values('directional_accuracy_mean', ascending=False)
            for sector, row in sector_stats.iterrows():
                print(f"{sector:<20} | Acc: {row['directional_accuracy_mean']:.3f}±{row['directional_accuracy_std']:.3f} | "
                      f"MCC: {row['mcc_mean']:.3f} | Companies: {int(row['directional_accuracy_count'])}")

        print("" + "="*50)
        print("TOP 10 PERFORMERS (by Directional Accuracy)")
        print("="*50)
        top_performers = df.nlargest(10, 'directional_accuracy')
        for _, row in top_performers.iterrows():
            print(f"{row['company']:<20} | {row['sector']:<15} | "
                  f"Acc: {row['directional_accuracy']:.3f} | MCC: {row['mcc']:.3f}")

        return analysis

    def save_results(self, results, output_dir='results/benchmarking'):
        if results is not None and not results.empty:
            model_name = self.model_type

            if self.problem_type == 'regression':
                out_dir = os.path.join(output_dir, 'regression')
            elif self.problem_type == 'classification':
                out_dir = os.path.join(output_dir, 'classification')
            else:
                out_dir = os.path.join(output_dir, 'multiclass')

            os.makedirs(out_dir, exist_ok=True)

            output_path = os.path.join(out_dir, f"{model_name}.csv")

            results.to_csv(output_path, index=False)
            print(f"Results saved to {output_path}")
        else:
            print("No results to save.")
            
    def get_loss_curves_df(self):
        if not self.loss_curves:
            print("No loss curves logged yet.")
            return pd.DataFrame()
        return pd.DataFrame(self.loss_curves)

    def save_loss_curves(self, out_path='results/benchmarking/'):
        df = self.get_loss_curves_df()
        if df.empty:
            print("No loss curves to save.")
            return
        if self.problem_type == 'regression':
            out_path = os.path.join(out_path, 'regression', f"{self.model_type}_loss_curves.csv")
        elif self.problem_type == 'classification':
            out_path = os.path.join(out_path, 'classification', f"{self.model_type}_loss_curves.csv")
        else:
            out_path = os.path.join(out_path, 'multiclass', f"{self.model_type}_loss_curves.csv")
            
        os.makedirs(os.path.dirname(out_path), exist_ok=True)
        
        df.to_csv(out_path, index=False)
        print(f"Loss curves saved to {out_path}")

    def get_feature_importance_analysis(self):
        print("Feature importance analysis not implemented yet.")
        print("Consider implementing SHAP values or permutation importance for better insights.")
        return None

## Data Preparation

In [6]:
master_df = pd.read_parquet('../data/dataset/ta_nlp_sector.parquet')

In [7]:
master_df.columns

Index(['date', 'open', 'high', 'low', 'close', 'adj_close', 'volume', 'ticker',
       'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9',
       'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3',
       'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'ret_1d',
       'roll_ret_1d', 'roll_ret_5d', 'roll_ret_20d', 'text', 'sentiment',
       'emotion_anger', 'emotion_disgust', 'emotion_fear', 'emotion_joy',
       'emotion_neutral', 'emotion_sadness', 'emotion_surprize',
       'emotion_anger_pct', 'emotion_disgust_pct', 'emotion_fear_pct',
       'emotion_joy_pct', 'emotion_neutral_pct', 'emotion_sadness_pct',
       'emotion_surprize_pct', 'positive_emotion', 'negative_emotion',
       'uncertainty_emotion', 'positive_emotion_pct', 'negative_emotion_pct',
       'uncertainty_emotion_pct', 'stance_label', 'finbert_label',
       'stance_score', 'finbert_score', 'finbert_up', 'finbert_down',
       'finbert_neutral', 'sector', 'company_name', 'sector_open_mean',
       'sector_high_mean', 'sector_low_mean', 'sector_close_mean',
       'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d',
       'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector',
       'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector',
       'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector',
       'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower',
       'market_close', 'sector_rel_strength', 'sector_dispersion_1d'],
      dtype='object')

In [8]:
master_df

,date,open,high,low,close,adj_close,volume,ticker,ema_12,ema_26,...,macd_12_26_9_sector,macdh_12_26_9_sector,macds_12_26_9_sector,rsi_14_sector,sector_bb_upper,sector_bb_middle,sector_bb_lower,market_close,sector_rel_strength,sector_dispersion_1d
0,2012-09-04,95.108574,96.448570,94.928574,96.424286,87.121140,91973000.0,AAPL,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1464.800169,NaN,NaN
1,2012-09-05,96.510002,96.621429,95.657143,95.747147,86.509338,84093800.0,AAPL,NaN,NaN,...,NaN,NaN,NaN,0.000000,NaN,NaN,NaN,1481.232189,NaN,0.006548
2,2012-09-06,96.167145,96.898575,95.828575,96.610001,87.288956,97799100.0,AAPL,NaN,NaN,...,NaN,NaN,NaN,28.755774,NaN,NaN,NaN,1502.627054,NaN,0.006476
3,2012-09-07,96.864288,97.497147,96.538574,97.205711,87.827171,82416600.0,AAPL,NaN,NaN,...,NaN,NaN,NaN,28.562466,NaN,NaN,NaN,1506.971629,NaN,0.008604
4,2012-09-10,97.207146,97.612854,94.585716,94.677139,85.542564,121999500.0,AAPL,NaN,NaN,...,NaN,NaN,NaN,22.507443,NaN,NaN,NaN,1503.735325,NaN,0.012007
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
108587,2017-08-28,76.900002,76.940002,76.260002,76.470001,76.470001,8229700.0,XOM,77.187452,78.267858,...,-0.111192,0.016355,-0.127548,53.634155,63.049962,61.01430,58.978638,3101.328695,-0.007883,0.005228
108588,2017-08-29,76.209999,76.489998,76.080002,76.449997,76.449997,7060400.0,XOM,77.073998,78.133202,...,-0.067027,0.048417,-0.115443,54.205103,62.862103,60.94445,59.026797,3102.507723,-0.016661,0.002030
108589,2017-08-30,76.239998,76.449997,76.059998,76.099998,76.099998,8218000.0,XOM,76.924151,77.982594,...,-0.037643,0.062240,-0.099883,53.126723,62.639604,60.86875,59.097896,3128.753695,-0.017629,0.004873
108590,2017-08-31,76.269997,76.489998,76.050003,76.330002,76.330002,15641700.0,XOM,76.832744,77.860180,...,0.013408,0.090633,-0.077225,57.342960,62.525437,60.83190,59.138363,3141.201722,-0.008376,0.006185
108591,2017-09-01,76.370003,76.849998,76.320000,76.570000,76.570000,7340800.0,XOM,76.792322,77.764611,...,0.088512,0.132590,-0.044078,62.040301,62.426369,60.80760,59.188831,3136.813139,-0.001766,0.007085

In [9]:
columns_to_check = [
                    'sentiment',
                    
                    'emotion_anger', 'emotion_disgust', 'emotion_fear', 'emotion_joy',
                    'emotion_neutral', 'emotion_sadness', 'emotion_surprize',
                    'emotion_anger_pct', 'emotion_disgust_pct', 'emotion_fear_pct',
                    'emotion_joy_pct', 'emotion_neutral_pct', 'emotion_sadness_pct',
                    'emotion_surprize_pct', 
                    
                    'positive_emotion', 'negative_emotion','uncertainty_emotion', 
                    'positive_emotion_pct', 'negative_emotion_pct','uncertainty_emotion_pct', 
                    
                    'stance_label', 'stance_score', 
                    
                    'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down',
                    'finbert_neutral', 
                    
                    'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean',
                    'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d',
                    'sector_ret_20d', 'sector_range', 'sector_vol_20d', 
                    
                    'ema_12_sector','ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector',
                    'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector',
                    'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower',
                    'market_close', 'sector_rel_strength', 'sector_dispersion_1d'
                ]

print(f"Initial master_df shape: {master_df.shape}")

master_df = master_df.dropna(subset=columns_to_check)

print(f"After dropping NaNs in selected columns, master_df shape: {master_df.shape}")

master_df.reset_index(drop=True, inplace=True)

display(master_df)

Initial master_df shape: (108592, 80)
After dropping NaNs in selected columns, master_df shape: (104476, 80)

,date,open,high,low,close,adj_close,volume,ticker,ema_12,ema_26,...,macd_12_26_9_sector,macdh_12_26_9_sector,macds_12_26_9_sector,rsi_14_sector,sector_bb_upper,sector_bb_middle,sector_bb_lower,market_close,sector_rel_strength,sector_dispersion_1d
0,2012-11-14,77.928574,78.207146,76.597145,76.697144,69.613815,119292600.0,AAPL,80.708033,84.949698,...,-0.913108,-0.181794,-0.731314,27.619972,63.948320,61.465736,58.983152,1484.350654,-0.003089,0.006800
1,2012-11-15,76.790001,77.071426,74.660004,75.088570,68.153778,197477700.0,AAPL,79.843501,84.219244,...,-0.926239,-0.155940,-0.770299,32.479352,63.646173,61.261193,58.876213,1484.574993,0.002003,0.019838
2,2012-11-16,75.028572,75.714287,72.250000,75.382858,68.420891,316723400.0,AAPL,79.157248,83.564697,...,-0.892113,-0.097452,-0.794662,37.450172,63.236926,61.078872,58.920817,1497.780485,0.010276,0.010265
3,2012-11-19,77.244286,81.071426,77.125717,80.818573,73.354591,205829400.0,AAPL,79.412836,83.361280,...,-0.733193,0.049174,-0.782368,51.350390,63.001827,61.010079,59.018330,1506.128807,0.024682,0.018850
4,2012-11-20,81.701431,81.707146,79.225716,80.129997,72.729614,160688500.0,AAPL,79.523169,83.121926,...,-0.579416,0.162361,-0.741778,53.267164,62.959435,60.996029,59.032623,1508.629302,0.025531,0.007554
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
104471,2017-08-28,76.900002,76.940002,76.260002,76.470001,76.470001,8229700.0,XOM,77.187452,78.267858,...,-0.111192,0.016355,-0.127548,53.634155,63.049962,61.014300,58.978638,3101.328695,-0.007883,0.005228
104472,2017-08-29,76.209999,76.489998,76.080002,76.449997,76.449997,7060400.0,XOM,77.073998,78.133202,...,-0.067027,0.048417,-0.115443,54.205103,62.862103,60.944450,59.026797,3102.507723,-0.016661,0.002030
104473,2017-08-30,76.239998,76.449997,76.059998,76.099998,76.099998,8218000.0,XOM,76.924151,77.982594,...,-0.037643,0.062240,-0.099883,53.126723,62.639604,60.868750,59.097896,3128.753695,-0.017629,0.004873
104474,2017-08-31,76.269997,76.489998,76.050003,76.330002,76.330002,15641700.0,XOM,76.832744,77.860180,...,0.013408,0.090633,-0.077225,57.342960,62.525437,60.831900,59.138363,3141.201722,-0.008376,0.006185
104475,2017-09-01,76.370003,76.849998,76.320000,76.570000,76.570000,7340800.0,XOM,76.792322,77.764611,...,0.088512,0.132590,-0.044078,62.040301,62.426369,60.807600,59.188831,3136.813139,-0.001766,0.007085

In [10]:
print(master_df.columns)

Index(['date', 'open', 'high', 'low', 'close', 'adj_close', 'volume', 'ticker',
       'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9',
       'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3',
       'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'ret_1d',
       'roll_ret_1d', 'roll_ret_5d', 'roll_ret_20d', 'text', 'sentiment',
       'emotion_anger', 'emotion_disgust', 'emotion_fear', 'emotion_joy',
       'emotion_neutral', 'emotion_sadness', 'emotion_surprize',
       'emotion_anger_pct', 'emotion_disgust_pct', 'emotion_fear_pct',
       'emotion_joy_pct', 'emotion_neutral_pct', 'emotion_sadness_pct',
       'emotion_surprize_pct', 'positive_emotion', 'negative_emotion',
       'uncertainty_emotion', 'positive_emotion_pct', 'negative_emotion_pct',
       'uncertainty_emotion_pct', 'stance_label', 'finbert_label',
       'stance_score', 'finbert_score', 'finbert_up', 'finbert_down',
       'finbert_neutral', 'sector', 'company_name', 'sector_open_mean',
       'sector_high_mean', 'sector_low_mean', 'sector_close_mean',
       'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d',
       'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector',
       'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector',
       'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector',
       'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower',
       'market_close', 'sector_rel_strength', 'sector_dispersion_1d'],
      dtype='object')

In [11]:
feature_columns = [
    'open', 'high', 'low', 'close', 'volume',
    # 'roll_ret_1d', 'roll_ret_5d', 
    # 'roll_ret_20d',
    
    'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9',
    'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3',
    'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv',
]

new_indicator_columns = [
    # 'sentiment',
                    
    # 'emotion_anger', 'emotion_disgust', 'emotion_fear', 'emotion_joy',
    # 'emotion_neutral', 'emotion_sadness', 'emotion_surprize',
    # 'emotion_anger_pct', 'emotion_disgust_pct', 'emotion_fear_pct',
    # 'emotion_joy_pct', 'emotion_neutral_pct', 'emotion_sadness_pct',
    # 'emotion_surprize_pct', 
    
    # 'positive_emotion', 'negative_emotion','uncertainty_emotion', 
    # 'positive_emotion_pct', 'negative_emotion_pct','uncertainty_emotion_pct', 
    
    # 'stance_label', 'stance_score', 
    
    # 'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down',
    # 'finbert_neutral', 
    
    # 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean',
    # 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d',
    # 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 
    
    # 'ema_12_sector','ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector',
    # 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector',
    # 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower',
    # 'market_close', 'sector_rel_strength', 'sector_dispersion_1d'
]

# feature_columns.extend(new_indicator_columns)



sequence_length=12



all_pipelines = {}
all_results_dfs = {}
all_analyses = {}
fixed_bucket_edges = np.array([-0.08, -0.03, -0.01, 0.0, 0.01, 0.03, 0.08], dtype=float)
n_classes = len(fixed_bucket_edges) - 1
ordinal_head = 'corn'

In [12]:
print(master_df.shape)
master_df = master_df.dropna(subset=feature_columns).sort_values(['ticker','date'])
print(master_df.shape)

(104476, 80)
(104220, 80)

## Pipeline Execution

In [13]:
# print(f"\n{'='*25}\n  RUNNING PIPELINE FOR: GRU\n{'='*25}\n")

# pipeline_GRU = StockPredictionPipeline(
#     df=master_df,
#     feature_columns=feature_columns,
#     model_type='GRU',
#     sequence_length=sequence_length,
#     problem_type='classification',
#     horizon_steps=1,
#     n_classes=n_classes,
#     ordinal_head=ordinal_head,
#     fixed_bucket_edges=fixed_bucket_edges
# )

# results_GRU = pipeline_GRU.run_pipeline()

# loss_df = pipeline_GRU.get_loss_curves_df()

# pipeline_GRU.save_loss_curves('results/benchmarking/')

# if results_GRU is not None and not results_GRU.empty:
#     analysis_GRU = pipeline_GRU.analyze_results()
#     pipeline_GRU.save_results(results_GRU, output_dir='results/benchmarking/')
#     all_pipelines["GRU"] = pipeline_GRU
#     all_results_dfs["GRU"] = results_GRU
#     all_analyses["GRU"] = analysis_GRU

#     print("\nDisplaying first 5 rows of GRU results:")
#     display(results_GRU.head())
# else:
#     print(f"\n[FAILED] Pipeline for GRU did not produce any results.")

# del pipeline_GRU

In [14]:
sentinemt_columns = [
    'sentiment',
]

emotion_columns = [
    'emotion_anger', 'emotion_disgust', 'emotion_fear', 'emotion_joy',
    'emotion_neutral', 'emotion_sadness', 'emotion_surprize',
    'emotion_anger_pct', 'emotion_disgust_pct', 'emotion_fear_pct',
    'emotion_joy_pct', 'emotion_neutral_pct', 'emotion_sadness_pct',
    'emotion_surprize_pct',
]

unified_emotion_columns = [
    'positive_emotion', 'negative_emotion','uncertainty_emotion',
    'positive_emotion_pct', 'negative_emotion_pct','uncertainty_emotion_pct',
]

stance_columns = [
    'stance_label', 'stance_score',
]

finbert_columns = [
    'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down',
    'finbert_neutral',
]

sector_columns = ['sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean',
                  'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d',
                  'sector_ret_20d', 'sector_range', 'sector_vol_20d', 
                  
                  'ema_12_sector','ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector',
                  'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector',
                  'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower',
                  'market_close', 'sector_rel_strength', 'sector_dispersion_1d']

In [15]:
try:
    import optuna
except ImportError:
    import sys
    !{sys.executable} -m pip install optuna
    import optuna
    
from pathlib import Path
from datetime import datetime
    
# Define feature sets to test
feature_sets = {
    'base': feature_columns,
    'sentinment' : feature_columns + sentinemt_columns,
    'emotion' : feature_columns + emotion_columns,
    'unified_emotion': feature_columns + unified_emotion_columns,
    'finbert': feature_columns + finbert_columns,
    'all_nlp': feature_columns + sentinemt_columns + emotion_columns + unified_emotion_columns + stance_columns + finbert_columns,
    'sector': feature_columns + sector_columns,
    'sector_sentiment': feature_columns + sector_columns + sentinemt_columns,
    'sector_emotion': feature_columns + sector_columns + emotion_columns,
    'sector_unified_emotion': feature_columns + sector_columns + unified_emotion_columns,
    'sector_finbert': feature_columns + sector_columns + finbert_columns,
    'sector_all_nlp': feature_columns + sector_columns + sentinemt_columns + emotion_columns + unified_emotion_columns + stance_columns + finbert_columns,
}

def objective(trial):
    params = {
        'problem_type': 'classification',  # or 'classification'
        'feature_set': trial.suggest_categorical('feature_set', list(feature_sets.keys())),
        'model_type': trial.suggest_categorical('model_type', ['LSTM', 'BiLSTM', 'GRU', 'BiGRU']),
        'sequence_length': trial.suggest_int('sequence_length', 6, 36, step=6),
        'horizon_steps': trial.suggest_categorical('horizon_steps', [1]),
        'hidden1': trial.suggest_categorical('hidden1', [64, 128, 256]),
        'hidden2': trial.suggest_categorical('hidden2', [32, 64, 128]),
        'num_layers': trial.suggest_categorical('num_layers', [1, 2]),
        'inter_rnn_drop': trial.suggest_float('inter_rnn_drop', 0.0, 0.4, step=0.1),
        'dropout': trial.suggest_float('dropout', 0.0, 0.8, step=0.1),
        'batch_size': trial.suggest_categorical('batch_size', [16, 32, 64]),
        'learning_rate': trial.suggest_float('learning_rate', 1e-6, 1e-2, log=True),
        'weight_decay': trial.suggest_float('weight_decay', 1e-7, 1e-3, log=True),
        'lr_patience': trial.suggest_categorical('lr_patience', [5, 7, 10]),
        'lr_factor': trial.suggest_categorical('lr_factor', [0.4, 0.8]),
        'early_stopping_patience': trial.suggest_categorical('early_stopping_patience', [10, 15, 20]),
        'max_epochs': trial.suggest_categorical('max_epochs', [20, 30, 50]),
        'huber_delta': trial.suggest_float('huber_delta', 0.1, 2.0),
        'early_stopping_min_delta': trial.suggest_float('early_stopping_min_delta', 0.0, 0.01),
    }

    selected_features = feature_sets[params['feature_set']]
    missing_cols = [c for c in selected_features if c not in master_df.columns]
    if missing_cols:
        print(f"Missing columns for feature_set={params['feature_set']}: {missing_cols}")
        return -1.0

    pipeline = StockPredictionPipeline(
        df=master_df,
        feature_columns=selected_features,
        model_type=params['model_type'],
        sequence_length=params['sequence_length'],
        problem_type=params['problem_type'],
        horizon_steps=params['horizon_steps'],
        n_classes=n_classes,
        ordinal_head=ordinal_head,
        fixed_bucket_edges=fixed_bucket_edges,
        hidden1=params['hidden1'],
        hidden2=params['hidden2'],
        num_layers=params['num_layers'],
        inter_rnn_drop=params['inter_rnn_drop'],
        dropout=params['dropout'],
        batch_size=params['batch_size'],
        learning_rate=params['learning_rate'],
        weight_decay=params['weight_decay'],
        lr_patience=params['lr_patience'],
        lr_factor=params['lr_factor'],
        early_stopping_patience=params['early_stopping_patience'],
        max_epochs=params['max_epochs'],
        huber_delta=params['huber_delta'],
        early_stopping_min_delta=params['early_stopping_min_delta']
    )

    results_df = pipeline.run_pipeline()
    del pipeline
    torch.cuda.empty_cache()

    if results_df is None or results_df.empty:
        print('[DEBUG] results_df empty or None')
        return -1.0

    print('[DEBUG] results_df shape:', results_df.shape)
    print('[DEBUG] results_df columns:', results_df.columns.tolist())

    # Aggregate validation metrics
    val_f1 = results_df['val_f1'].mean() if 'val_f1' in results_df.columns else np.nan
    if not np.isfinite(val_f1) and 'best_threshold_metric' in results_df.columns:
        val_f1 = results_df['best_threshold_metric'].mean()
    val_mcc = results_df['val_mcc'].mean() if 'val_mcc' in results_df.columns else np.nan
    print('[DEBUG] val_mcc:', val_mcc)
    val_precision = results_df['val_precision'].mean() if 'val_precision' in results_df.columns else np.nan
    val_recall = results_df['val_recall'].mean() if 'val_recall' in results_df.columns else np.nan
    val_dir_acc = results_df['val_directional_accuracy'].mean() if 'val_directional_accuracy' in results_df.columns else np.nan

    trial.set_user_attr('val_f1', float(val_f1))
    trial.set_user_attr('val_mcc', float(val_mcc))
    trial.set_user_attr('val_precision', float(val_precision))
    trial.set_user_attr('val_recall', float(val_recall))
    trial.set_user_attr('val_directional_accuracy', float(val_dir_acc))

    # Primary metric: mean val MCC (classification) or mean MAE (regression)
    if params['problem_type'] == 'classification':
        score = val_mcc
        if not np.isfinite(score):
            return -1.0
        return float(score)
    else:
        # minimize MAE -> maximize negative MAE
        if 'mae' not in results_df.columns:
            return -1.0
        mae = results_df['mae'].mean()
        if not np.isfinite(mae):
            return -1.0
        return float(-mae)


N_TRIALS = 500

# Run study
study = optuna.create_study(direction='maximize')
study.optimize(objective, n_trials=N_TRIALS, timeout=60*60*12)  # 8 hours max
# Collect results
optuna_results = study.trials_dataframe()
# include user attrs
user_attrs = pd.DataFrame([t.user_attrs for t in study.trials])
optuna_results = pd.concat([optuna_results, user_attrs], axis=1)
optuna_results = optuna_results.sort_values('value', ascending=False)
optuna_results

timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
out_path = f'../results/benchmarking/classification/optuna_tuning_sector_1H.csv'
Path('../results/benchmarking/classification').mkdir(parents=True, exist_ok=True)
optuna_results.to_csv(out_path, index=False)
print(f'Saved Optuna results to {out_path}')

[I 2026-02-22 07:31:22,456] A new study created in memory with name: no-name-9b892cf7-3f5d-4311-bc20-970fcb044548

Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: classification
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d', 'emotion_anger', 'emotion_disgust', 'emotion_fear', 'emotion_joy', 'emotion_neutral', 'emotion_sadness', 'emotion_surprize', 'emotion_anger_pct', 'emotion_disgust_pct', 'emotion_fear_pct', 'emotion_joy_pct', 'emotion_neutral_pct', 'emotion_sadness_pct', 'emotion_surprize_pct']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.71766 | val 0.68910
  Epoch 011 - train 0.73091 | val 0.69013
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.70445 | val 0.68363
  Epoch 011 - train 0.72565 | val 0.68292
  Classification -> best τ=0.470 (val F1=0.0406)
  Directional -> Accuracy: 0.5000, MCC: -0.0635, F1: 0.6102

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.72415 | val 0.69953
  Epoch 011 - train 0.71401 | val 0.70337
  Classification -> best τ=0.525 (val F1=0.1303)
  Directional -> Accuracy: 0.4681, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.73789 | val 0.82854
  Epoch 011 - train 0.74866 | val 0.82910
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.70107 | val 0.67614
  Epoch 020 - train 0.70152 | val 0.67128
  Epoch 021 - train 0.70204 | val 0.67040
  Classification -> best τ=0.495 (val F1=0.3040)
  Directional -> Accuracy: 0.4902, MCC: 0.0000, F1: 0.4091

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.71929 | val 0.70100
  Epoch 011 - train 0.72086 | val 0.70290
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4894, MCC: 0.0000, F1: 0.6571

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.70950 | val 0.69176
  Epoch 011 - train 0.69836 | val 0.69194
  Classification -> best τ=0.455 (val F1=0.1667)
  Directional -> Accuracy: 0.4348, MCC: -0.0355, F1: 0.5185

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.69528 | val 0.70036
  Epoch 020 - train 0.69534 | val 0.64019
  Epoch 030 - train 0.71067 | val 0.63848
  Classification -> best τ=0.490 (val F1=0.3236)
  Directional -> Accuracy: 0.5909, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.70057 | val 0.67625
  Epoch 020 - train 0.75051 | val 0.67161
  Epoch 027 - train 0.70152 | val 0.67200
  Classification -> best τ=0.400 (val F1=0.2543)
  Directional -> Accuracy: 0.5306, MCC: 0.0724, F1: 0.5306

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.74797 | val 0.67298
  Epoch 017 - train 0.72508 | val 0.67209
  Classification -> best τ=0.505 (val F1=0.2809)
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.0000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.72986 | val 0.67760
  Epoch 020 - train 0.72653 | val 0.67413
  Epoch 021 - train 0.72702 | val 0.67495
  Classification -> best τ=0.390 (val F1=0.1721)
  Directional -> Accuracy: 0.4600, MCC: -0.0164, F1: 0.6197

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.69850 | val 0.68771
  Epoch 011 - train 0.71118 | val 0.68780
  Classification -> best τ=0.510 (val F1=0.2097)
  Directional -> Accuracy: 0.5690, MCC: 0.2265, F1: 0.6914

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.74237 | val 0.68727
  Epoch 020 - train 0.70363 | val 0.68134
  Epoch 023 - train 0.70986 | val 0.68346
  Classification -> best τ=0.530 (val F1=0.1960)
  Directional -> Accuracy: 0.4651, MCC: -0.2232, F1: 0.0800

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.69992 | val 0.69965
  Epoch 011 - train 0.68694 | val 0.70002
  Classification -> best τ=0.485 (val F1=0.0670)
  Directional -> Accuracy: 0.5082, MCC: 0.0141, F1: 0.5455

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.70710 | val 0.73477
  Epoch 011 - train 0.72274 | val 0.74512
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4615, MCC: 0.0000, F1: 0.6316

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.71661 | val 0.67684
  Epoch 019 - train 0.70293 | val 0.67742
  Classification -> best τ=0.490 (val F1=0.3767)
  Directional -> Accuracy: 0.6143, MCC: 0.2159, F1: 0.7033

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.72065 | val 0.69002
  Epoch 011 - train 0.71169 | val 0.69105
  Classification -> best τ=0.500 (val F1=0.2335)
  Directional -> Accuracy: 0.3898, MCC: 0.1013, F1: 0.0526

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.71084 | val 0.70750
  Epoch 011 - train 0.72676 | val 0.70698
  Classification -> best τ=0.490 (val F1=0.1116)
  Directional -> Accuracy: 0.3947, MCC: -0.0933, F1: 0.2069

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.68048 | val 0.72409
  Epoch 011 - train 0.68571 | val 0.72332
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5846, MCC: 0.0000, F1: 0.7379

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.71935 | val 0.73906
  Epoch 011 - train 0.71263 | val 0.73991
  Classification -> best τ=0.465 (val F1=0.0029)
  Directional -> Accuracy: 0.5467, MCC: 0.1250, F1: 0.5000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.73060 | val 0.71579
  Epoch 011 - train 0.73387 | val 0.72080
  Classification -> best τ=0.450 (val F1=0.0214)
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.72218 | val 0.73559
  Epoch 011 - train 0.73028 | val 0.73449
  Classification -> best τ=0.510 (val F1=0.1073)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.71738 | val 0.68994
  Epoch 016 - train 0.70328 | val 0.69269
  Classification -> best τ=0.580 (val F1=0.2629)
  Directional -> Accuracy: 0.3966, MCC: -0.1616, F1: 0.1026

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.71834 | val 0.70649
  Epoch 011 - train 0.73145 | val 0.70816
  Classification -> best τ=0.450 (val F1=0.0596)
  Directional -> Accuracy: 0.4091, MCC: -0.2086, F1: 0.5618

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.76265 | val 0.70460
  Epoch 011 - train 0.72860 | val 0.70562
  Classification -> best τ=0.515 (val F1=0.1348)
  Directional -> Accuracy: 0.4107, MCC: -0.1723, F1: 0.4211

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.71300 | val 0.69810
  Epoch 011 - train 0.66902 | val 0.69881
  Classification -> best τ=0.485 (val F1=0.1925)
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.0000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.69514 | val 0.68509
  Epoch 011 - train 0.68282 | val 0.68562
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.69233 | val 0.66722
  Epoch 020 - train 0.67892 | val 0.66364
  Epoch 025 - train 0.72709 | val 0.66276
  Classification -> best τ=0.545 (val F1=0.4018)
  Directional -> Accuracy: 0.4561, MCC: 0.1181, F1: 0.0606

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.68815 | val 0.69597
  Epoch 011 - train 0.70059 | val 0.69753
  Classification -> best τ=0.530 (val F1=0.0225)
  Directional -> Accuracy: 0.5366, MCC: 0.0587, F1: 0.5957

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.70094 | val 0.70576
  Epoch 011 - train 0.70930 | val 0.70846
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.70804 | val 0.66973
  Epoch 020 - train 0.73715 | val 0.65458
  Epoch 025 - train 0.70766 | val 0.65545
  Classification -> best τ=0.495 (val F1=0.1437)
  Directional -> Accuracy: 0.4186, MCC: -0.2849, F1: 0.5763

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.69972 | val 0.73706
  Epoch 011 - train 0.70930 | val 0.74043
  Classification -> best τ=0.525 (val F1=0.2872)
  Directional -> Accuracy: 0.5400, MCC: 0.0164, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.71420 | val 0.67363
  Epoch 018 - train 0.68453 | val 0.67309
  Classification -> best τ=0.415 (val F1=0.2492)
  Directional -> Accuracy: 0.5479, MCC: -0.0438, F1: 0.7027

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.68072 | val 0.69300
  Epoch 011 - train 0.69192 | val 0.69301
  Classification -> best τ=0.485 (val F1=0.1085)
  Directional -> Accuracy: 0.4737, MCC: -0.0529, F1: 0.5000

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.69326 | val 0.70209
  Epoch 011 - train 0.71989 | val 0.70233
  Classification -> best τ=0.515 (val F1=0.0541)
  Directional -> Accuracy: 0.3864, MCC: -0.2243, F1: 0.4000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.72150 | val 0.68331
  Epoch 017 - train 0.70030 | val 0.68324
  Classification -> best τ=0.530 (val F1=0.2234)
  Directional -> Accuracy: 0.4776, MCC: -0.1217, F1: 0.5977

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.71243 | val 0.69200
  Epoch 011 - train 0.70048 | val 0.69198
  Classification -> best τ=0.480 (val F1=0.1037)
  Directional -> Accuracy: 0.6047, MCC: 0.2082, F1: 0.6222

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.68607 | val 0.70969
  Epoch 011 - train 0.68718 | val 0.71083
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.71300 | val 0.70162
  Epoch 011 - train 0.72166 | val 0.71199
  Classification -> best τ=0.465 (val F1=0.2066)
  Directional -> Accuracy: 0.6383, MCC: 0.1622, F1: 0.7536

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.69044 | val 0.71314
  Epoch 011 - train 0.70955 | val 0.71431
  Classification -> best τ=0.535 (val F1=0.1864)
  Directional -> Accuracy: 0.3878, MCC: -0.0228, F1: 0.5161

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.74815 | val 0.69447
  Epoch 011 - train 0.72002 | val 0.69498
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.71199 | val 0.70674
  Epoch 011 - train 0.70664 | val 0.70665
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.70604 | val 0.68202
  Epoch 019 - train 0.70681 | val 0.70157
  Classification -> best τ=0.460 (val F1=0.2962)
  Directional -> Accuracy: 0.5319, MCC: 0.0687, F1: 0.6562

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.67770 | val 0.70187
  Epoch 020 - train 0.67629 | val 0.66804
  Epoch 028 - train 0.69573 | val 0.66635
  Classification -> best τ=0.465 (val F1=0.4416)
  Directional -> Accuracy: 0.5455, MCC: -0.1329, F1: 0.7059

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.75255 | val 0.68020
  Epoch 011 - train 0.70088 | val 0.68093
  Classification -> best τ=0.520 (val F1=0.2626)
  Directional -> Accuracy: 0.6327, MCC: 0.1539, F1: 0.3077

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.73456 | val 0.67191
  Epoch 017 - train 0.70174 | val 0.67448
  Classification -> best τ=0.555 (val F1=0.2405)
  Directional -> Accuracy: 0.5536, MCC: 0.0965, F1: 0.6988

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.70251 | val 0.70697
  Epoch 011 - train 0.72231 | val 0.70794
  Classification -> best τ=0.495 (val F1=0.1181)
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.70874 | val 0.73214
  Epoch 011 - train 0.72481 | val 0.73939
  Classification -> best τ=0.485 (val F1=0.1712)
  Directional -> Accuracy: 0.4815, MCC: -0.0385, F1: 0.5000

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.71481 | val 0.68781
  Epoch 015 - train 0.70930 | val 0.69181
  Classification -> best τ=0.465 (val F1=0.1979)
  Directional -> Accuracy: 0.4643, MCC: -0.1397, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...

[I 2026-02-22 07:32:00,041] Trial 0 finished with value: 0.14726800993483447 and parameters: {'feature_set': 'sector_emotion', 'model_type': 'LSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 64, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.7000000000000001, 'batch_size': 32, 'learning_rate': 9.974959911029263e-06, 'weight_decay': 5.189337916096731e-06, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 10, 'max_epochs': 50, 'huber_delta': 0.4460295325099286, 'early_stopping_min_delta': 0.006192808604397003}. Best is trial 0 with value: 0.14726800993483447.

  Epoch 010 - train 0.71908 | val 0.71014
  Epoch 011 - train 0.73109 | val 0.70945
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4754, MCC: 0.0000, F1: 0.6444

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.14726800993483447
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: classification
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'positive_emotion', 'negative_emotion', 'uncertainty_emotion', 'positive_emotion_pct', 'negative_emotion_pct', 'uncertainty_emotion_pct']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.68246 | val 0.70196
  Epoch 020 - train 0.65905 | val 0.71358
  Classification -> best τ=0.485 (val F1=0.0951)
  Directional -> Accuracy: 0.5455, MCC: 0.0000, F1: 0.0000

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.68681 | val 0.68736
  Epoch 020 - train 0.65742 | val 0.68603
  Classification -> best τ=0.450 (val F1=0.3081)
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.7222

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.71388 | val 0.70487
  Epoch 020 - train 0.70185 | val 0.70392
  Classification -> best τ=0.460 (val F1=0.2002)
  Directional -> Accuracy: 0.6170, MCC: 0.2764, F1: 0.5500

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.69396 | val 0.70880
  Epoch 020 - train 0.67834 | val 0.73722
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.67460 | val 0.67513
  Epoch 020 - train 0.65534 | val 0.66990
  Classification -> best τ=0.520 (val F1=0.5047)
  Directional -> Accuracy: 0.5098, MCC: -0.0242, F1: 0.6377

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.70238 | val 0.69368
  Epoch 020 - train 0.67450 | val 0.71930
  Classification -> best τ=0.500 (val F1=0.0778)
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.68449 | val 0.69004
  Epoch 020 - train 0.66577 | val 0.71117
  Classification -> best τ=0.460 (val F1=0.2567)
  Directional -> Accuracy: 0.4348, MCC: 0.0787, F1: 0.5806

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.68550 | val 0.67077
  Epoch 020 - train 0.66978 | val 0.67035
  Classification -> best τ=0.475 (val F1=0.0792)
  Directional -> Accuracy: 0.5909, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.71379 | val 0.69384
  Epoch 020 - train 0.69813 | val 0.69093
  Classification -> best τ=0.500 (val F1=0.1939)
  Directional -> Accuracy: 0.5102, MCC: 0.1103, F1: 0.6129

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.67846 | val 0.68642
  Epoch 020 - train 0.66485 | val 0.69738
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.68446 | val 0.71104
  Epoch 020 - train 0.68245 | val 0.77636
  Classification -> best τ=0.520 (val F1=0.1166)
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.6301

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.69358 | val 0.70884
  Epoch 020 - train 0.66436 | val 0.77719
  Classification -> best τ=0.485 (val F1=0.0298)
  Directional -> Accuracy: 0.3793, MCC: -0.2651, F1: 0.4857

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.66087 | val 0.69979
  Epoch 020 - train 0.66615 | val 0.77733
  Classification -> best τ=0.505 (val F1=0.1669)
  Directional -> Accuracy: 0.4651, MCC: 0.1373, F1: 0.6230

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.68672 | val 0.69876
  Epoch 020 - train 0.67611 | val 0.68148
  Classification -> best τ=0.485 (val F1=0.1829)
  Directional -> Accuracy: 0.5574, MCC: 0.1236, F1: 0.6494

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.69313 | val 0.69469
  Epoch 020 - train 0.66377 | val 0.70907
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4615, MCC: 0.0000, F1: 0.6316

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.69151 | val 0.67987
  Epoch 020 - train 0.66433 | val 0.68633
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5429, MCC: 0.0000, F1: 0.7037

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.70127 | val 0.71398
  Epoch 020 - train 0.69090 | val 0.79282
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.69157 | val 0.70798
  Epoch 020 - train 0.70950 | val 0.76189
  Classification -> best τ=0.490 (val F1=0.0823)
  Directional -> Accuracy: 0.3947, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.69961 | val 0.69451
  Epoch 020 - train 0.65754 | val 0.68787
  Classification -> best τ=0.555 (val F1=0.1446)
  Directional -> Accuracy: 0.4769, MCC: 0.1610, F1: 0.2273

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.67907 | val 0.67963
  Epoch 020 - train 0.66105 | val 0.67990
  Classification -> best τ=0.435 (val F1=0.2371)
  Directional -> Accuracy: 0.4800, MCC: -0.0573, F1: 0.5412

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.68662 | val 0.69317
  Epoch 020 - train 0.70761 | val 0.69559
  Classification -> best τ=0.500 (val F1=0.0764)
  Directional -> Accuracy: 0.4583, MCC: 0.1155, F1: 0.3158

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.68446 | val 0.69264
  Epoch 020 - train 0.67865 | val 0.69911
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.69153 | val 0.69111
  Epoch 020 - train 0.66212 | val 0.70450
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5690, MCC: 0.0000, F1: 0.7253

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.69225 | val 0.68695
  Epoch 020 - train 0.64475 | val 0.68212
  Classification -> best τ=0.480 (val F1=0.2364)
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.6392

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.67012 | val 0.68396
  Epoch 020 - train 0.65874 | val 0.66401
  Classification -> best τ=0.525 (val F1=0.2864)
  Directional -> Accuracy: 0.5536, MCC: 0.2064, F1: 0.4186

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.67103 | val 0.69681
  Epoch 020 - train 0.69037 | val 0.69745
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.69682 | val 0.68081
  Epoch 020 - train 0.66906 | val 0.68048
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.67600 | val 0.67959
  Epoch 020 - train 0.65898 | val 0.67227
  Classification -> best τ=0.445 (val F1=0.2668)
  Directional -> Accuracy: 0.4561, MCC: -0.1587, F1: 0.5753

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.69958 | val 0.69338
  Epoch 020 - train 0.71319 | val 0.69848
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.70515 | val 0.68620
  Epoch 020 - train 0.67059 | val 0.69065
  Classification -> best τ=0.430 (val F1=0.2112)
  Directional -> Accuracy: 0.4186, MCC: -0.1649, F1: 0.3902

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.66981 | val 0.71311
  Epoch 020 - train 0.71258 | val 0.70680
  Classification -> best τ=0.480 (val F1=0.0754)
  Directional -> Accuracy: 0.4651, MCC: -0.0334, F1: 0.2581

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.68337 | val 0.69601
  Epoch 020 - train 0.67562 | val 0.70388
  Classification -> best τ=0.510 (val F1=0.1462)
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.68553 | val 0.67678
  Epoch 020 - train 0.66056 | val 0.64722
  Classification -> best τ=0.425 (val F1=0.4179)
  Directional -> Accuracy: 0.5342, MCC: 0.1465, F1: 0.4333

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.70186 | val 0.69419
  Epoch 020 - train 0.69582 | val 0.69984
  Classification -> best τ=0.455 (val F1=0.2357)
  Directional -> Accuracy: 0.3947, MCC: -0.2582, F1: 0.1481

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.69705 | val 0.71771
  Epoch 020 - train 0.70596 | val 0.76312
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.68263 | val 0.69901
  Epoch 020 - train 0.68168 | val 0.70360
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5672, MCC: 0.0000, F1: 0.7238

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.68504 | val 0.68897
  Epoch 020 - train 0.67649 | val 0.68389
  Classification -> best τ=0.480 (val F1=0.1902)
  Directional -> Accuracy: 0.5581, MCC: 0.1239, F1: 0.5128

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.68362 | val 0.69669
  Epoch 020 - train 0.66701 | val 0.67589
  Classification -> best τ=0.450 (val F1=0.2369)
  Directional -> Accuracy: 0.5088, MCC: 0.0453, F1: 0.5882

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.68913 | val 0.70565
  Epoch 020 - train 0.67016 | val 0.70946
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.6170, MCC: 0.0000, F1: 0.7632

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.68219 | val 0.71316
  Epoch 020 - train 0.70428 | val 0.71293
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.66411 | val 0.69992
  Epoch 020 - train 0.67087 | val 0.71286
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.68976 | val 0.68365
  Epoch 020 - train 0.66151 | val 0.69500
  Classification -> best τ=0.580 (val F1=0.2568)
  Directional -> Accuracy: 0.5600, MCC: 0.1402, F1: 0.6374

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.67651 | val 0.69189
  Epoch 020 - train 0.66387 | val 0.68899
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.67256 | val 0.68388
  Epoch 020 - train 0.70044 | val 0.68633
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5682, MCC: 0.0000, F1: 0.7246

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.69905 | val 0.70738
  Epoch 020 - train 0.69841 | val 0.71679
  Classification -> best τ=0.480 (val F1=0.4264)
  Directional -> Accuracy: 0.6122, MCC: 0.0000, F1: 0.0000

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.70493 | val 0.69398
  Epoch 020 - train 0.69190 | val 0.71664
  Classification -> best τ=0.515 (val F1=0.0872)
  Directional -> Accuracy: 0.5357, MCC: 0.0534, F1: 0.6061

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.70194 | val 0.69196
  Epoch 020 - train 0.68755 | val 0.71008
  Classification -> best τ=0.485 (val F1=0.1635)
  Directional -> Accuracy: 0.4737, MCC: -0.0449, F1: 0.5000

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.69577 | val 0.69090
  Epoch 020 - train 0.71130 | val 0.71604
  Classification -> best τ=0.530 (val F1=0.1508)
  Directional -> Accuracy: 0.4815, MCC: -0.0198, F1: 0.3000

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.67807 | val 0.70701
  Epoch 020 - train 0.68576 | val 0.74670
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5179, MCC: 0.0000, F1: 0.6824

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.70794 | val 0.70387

[I 2026-02-22 07:32:35,227] Trial 1 finished with value: 0.12627030780494977 and parameters: {'feature_set': 'unified_emotion', 'model_type': 'LSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 32, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.7000000000000001, 'batch_size': 64, 'learning_rate': 0.0003806939867075793, 'weight_decay': 7.989072111016645e-07, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 20, 'huber_delta': 1.7936697290587247, 'early_stopping_min_delta': 0.006391436586336849}. Best is trial 0 with value: 0.14726800993483447.

  Epoch 020 - train 0.69371 | val 0.72730
  Classification -> best τ=0.530 (val F1=0.1734)
  Directional -> Accuracy: 0.4754, MCC: -0.0946, F1: 0.2381

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.12627030780494977
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: classification
Sequence length: 36
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d', 'sentiment', 'emotion_anger', 'emotion_disgust', 'emotion_fear', 'emotion_joy', 'emotion_neutral', 'emotion_sadness', 'emotion_surprize', 'emotion_anger_pct', 'emotion_disgust_pct', 'emotion_fear_pct', 'emotion_joy_pct', 'emotion_neutral_pct', 'emotion_sadness_pct', 'emotion_surprize_pct', 'positive_emotion', 'negative_emotion', 'uncertainty_emotion', 'positive_emotion_pct', 'negative_emotion_pct', 'uncertainty_emotion_pct', 'stance_label', 'stance_score', 'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down', 'finbert_neutral']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.27976 | val 0.97287
  Epoch 011 - train 0.23047 | val 1.15168
  Classification -> best τ=0.550 (val F1=0.1667)
  Directional -> Accuracy: 0.5676, MCC: 0.1302, F1: 0.5294

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 112). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.24011 | val 0.82795
  Epoch 011 - train 0.22348 | val 0.86672
  Classification -> best τ=0.480 (val F1=0.1373)
  Directional -> Accuracy: 0.6047, MCC: 0.0000, F1: 0.7536

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for AEP (109 < 112). Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 112). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.26546 | val 1.02222
  Epoch 011 - train 0.22379 | val 1.15307
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5227, MCC: 0.0000, F1: 0.6866

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.33199 | val 1.46326
  Epoch 011 - train 0.28070 | val 1.61586
  Classification -> best τ=0.465 (val F1=0.1061)
  Directional -> Accuracy: 0.4583, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.15617 | val 1.04850
  Epoch 014 - train 0.03676 | val 1.64268
  Classification -> best τ=0.510 (val F1=0.3380)
  Directional -> Accuracy: 0.5833, MCC: 0.2253, F1: 0.4444

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.26632 | val 0.81144
  Epoch 011 - train 0.23122 | val 0.92604
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.21801 | val 1.22577
  Epoch 011 - train 0.20500 | val 1.48982
  Classification -> best τ=0.490 (val F1=0.1287)
  Directional -> Accuracy: 0.5909, MCC: 0.0470, F1: 0.1290

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 112). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 112). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.25309 | val 0.69100
  Epoch 020 - train 0.02289 | val 1.65037
  Classification -> best τ=0.570 (val F1=0.3333)
  Directional -> Accuracy: 0.4872, MCC: -0.0428, F1: 0.4118

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.23512 | val 0.85780
  Epoch 011 - train 0.20140 | val 0.89951
  Classification -> best τ=0.510 (val F1=0.2966)
  Directional -> Accuracy: 0.5217, MCC: -0.0793, F1: 0.1538

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 112). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 112). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 112). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.23579 | val 0.85128
  Epoch 011 - train 0.14195 | val 0.99526
  Classification -> best τ=0.535 (val F1=0.0132)
  Directional -> Accuracy: 0.5672, MCC: 0.0212, F1: 0.2162

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.24058 | val 0.84924
  Epoch 011 - train 0.22624 | val 0.89715
  Classification -> best τ=0.540 (val F1=0.1871)
  Directional -> Accuracy: 0.5532, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.20847 | val 1.57643
  Epoch 011 - train 0.17819 | val 1.80319
  Classification -> best τ=0.495 (val F1=0.1555)
  Directional -> Accuracy: 0.5636, MCC: 0.2052, F1: 0.7073

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 112). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.25583 | val 1.05237
  Epoch 011 - train 0.22259 | val 1.19072
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4792, MCC: 0.0000, F1: 0.6479

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 112). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.28878 | val 0.93796
  Epoch 014 - train 0.11211 | val 1.50589
  Classification -> best τ=0.470 (val F1=0.3030)
  Directional -> Accuracy: 0.5517, MCC: 0.1527, F1: 0.3810

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.24881 | val 1.39792
  Epoch 011 - train 0.21568 | val 1.47572
  Classification -> best τ=0.505 (val F1=0.1373)
  Directional -> Accuracy: 0.6531, MCC: 0.2922, F1: 0.5854

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.40387 | val 1.33482
  Epoch 013 - train 0.24374 | val 1.54530
  Classification -> best τ=0.550 (val F1=0.2196)
  Directional -> Accuracy: 0.5373, MCC: 0.0716, F1: 0.5634

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 112). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.25443 | val 1.41780
  Epoch 011 - train 0.17523 | val 1.67569
  Classification -> best τ=0.510 (val F1=0.2320)
  Directional -> Accuracy: 0.4107, MCC: -0.0276, F1: 0.1951

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.30518 | val 0.87964
  Epoch 011 - train 0.26052 | val 0.99414
  Classification -> best τ=0.525 (val F1=0.0914)
  Directional -> Accuracy: 0.4110, MCC: -0.0882, F1: 0.2456

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.27880 | val 1.01406
  Epoch 011 - train 0.19829 | val 1.14268
  Classification -> best τ=0.490 (val F1=0.1386)
  Directional -> Accuracy: 0.4839, MCC: 0.1321, F1: 0.2727

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 112). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.27964 | val 1.01866
  Epoch 015 - train 0.10853 | val 1.67842
  Classification -> best τ=0.345 (val F1=0.2092)
  Directional -> Accuracy: 0.5556, MCC: 0.0791, F1: 0.6364

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.19048 | val 0.97374
  Epoch 011 - train 0.15502 | val 1.08500
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.6000, MCC: 0.0000, F1: 0.7500

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 112). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 112). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 112). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.24325 | val 0.83702
  Epoch 014 - train 0.08523 | val 1.67641
  Classification -> best τ=0.500 (val F1=0.2513)
  Directional -> Accuracy: 0.5397, MCC: 0.1014, F1: 0.2564

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.23224 | val 1.16281
  Epoch 011 - train 0.18850 | val 1.34213
  Classification -> best τ=0.490 (val F1=0.1978)
  Directional -> Accuracy: 0.6182, MCC: 0.2291, F1: 0.7529

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.27846 | val 1.59745
  Epoch 011 - train 0.21071 | val 1.80483
  Classification -> best τ=0.475 (val F1=0.0788)
  Directional -> Accuracy: 0.5079, MCC: 0.0452, F1: 0.5974

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.23329 | val 1.01155
  Epoch 015 - train 0.07536 | val 2.23844
  Classification -> best τ=0.430 (val F1=0.3604)
  Directional -> Accuracy: 0.5472, MCC: 0.1508, F1: 0.4545

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.28779 | val 0.66668
  Epoch 020 - train 0.02233 | val 1.21603
  Classification -> best τ=0.395 (val F1=0.3327)
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.19464 | val 0.80480
  Epoch 016 - train 0.02273 | val 1.80750
  Classification -> best τ=0.445 (val F1=0.2988)
  Directional -> Accuracy: 0.5625, MCC: 0.0555, F1: 0.6667

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.29037 | val 0.90923
  Epoch 011 - train 0.26633 | val 0.96800
  Classification -> best τ=0.495 (val F1=0.1139)
  Directional -> Accuracy: 0.5556, MCC: 0.0853, F1: 0.6571

[49/88] Processing MDT...

Processing MDT (Healthcare)...
Insufficient data for proper time series validation for MDT. Skipping...

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.27022 | val 1.27463
  Epoch 011 - train 0.24908 | val 1.47024
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.31710 | val 0.73316
  Epoch 012 - train 0.23024 | val 0.84441
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5500, MCC: 0.0000, F1: 0.7097

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.22614 | val 0.74834
  Epoch 017 - train 0.02627 | val 1.89613
  Classification -> best τ=0.395 (val F1=0.2277)
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.35850 | val 0.95313
  Epoch 011 - train 0.27129 | val 0.92212
  Classification -> best τ=0.445 (val F1=0.1592)
  Directional -> Accuracy: 0.5000, MCC: 0.0381, F1: 0.4444

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 112). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.22695 | val 0.91508
  Epoch 011 - train 0.18241 | val 1.03057
  Classification -> best τ=0.515 (val F1=0.2447)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for PCG (101 < 112). Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.26290 | val 0.88484
  Epoch 011 - train 0.22446 | val 0.96305
  Classification -> best τ=0.445 (val F1=0.3310)
  Directional -> Accuracy: 0.6562, MCC: 0.3150, F1: 0.6765

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.17652 | val 0.71399
  Epoch 016 - train 0.02931 | val 0.83149
  Classification -> best τ=0.480 (val F1=0.2898)
  Directional -> Accuracy: 0.5510, MCC: 0.1195, F1: 0.3125

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.22043 | val 1.29474
  Epoch 011 - train 0.19281 | val 1.45966
  Classification -> best τ=0.480 (val F1=0.0293)
  Directional -> Accuracy: 0.5185, MCC: 0.0046, F1: 0.3500

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.19218 | val 0.72293
  Epoch 013 - train 0.09669 | val 0.89370
  Classification -> best τ=0.495 (val F1=0.3046)
  Directional -> Accuracy: 0.4091, MCC: 0.1210, F1: 0.0714

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 112). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for PPL (108 < 112). Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 112). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 112). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 112). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.29597 | val 0.69927
  Epoch 011 - train 0.25588 | val 0.70545
  Classification -> best τ=0.480 (val F1=0.4719)
  Directional -> Accuracy: 0.3556, MCC: -0.0500, F1: 0.4727

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 112). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 112). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 112). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.30010 | val 1.61424
  Epoch 012 - train 0.15947 | val 2.22916
  Classification -> best τ=0.545 (val F1=0.2494)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0526

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 112). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 112). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 112). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 112). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.21912 | val 0.73914
  Epoch 019 - train 0.01792 | val 1.97983
  Classification -> best τ=0.635 (val F1=0.4641)
  Directional -> Accuracy: 0.6047, MCC: 0.2379, F1: 0.5143

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.26784 | val 0.72000
  Epoch 011 - train 0.22401 | val 0.73440
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5897, MCC: 0.0000, F1: 0.7419

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.33607 | val 0.69823
  Epoch 017 - train 0.09263 | val 0.84212
  Classification -> best τ=0.615 (val F1=0.2530)
  Directional -> Accuracy: 0.5333, MCC: -0.0286, F1: 0.3226

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.23082 | val 0.86001
  Epoch 011 - train 0.20842 | val 0.92430
  Classification -> best τ=0.550 (val F1=0.1354)
  Directional -> Accuracy: 0.5094, MCC: -0.1164, F1: 0.6667

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.23922 | val 0.95859
  Epoch 011 - train 0.20586 | val 1.06077
  Classification -> best τ=0.480 (val F1=0.1229)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.26217 | val 0.96096
  Epoch 013 - train 0.10947 | val 1.62809
  Classification -> best τ=0.485 (val F1=0.1690)
  Directional -> Accuracy: 0.5294, MCC: 0.0994, F1: 0.6471

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.28190 | val 0.95671
  Epoch 011 - train 0.23785 | val 0.97617
  Classification -> best τ=0.455 (val F1=0.0410)
  Directional -> Accuracy: 0.4906, MCC: -0.0113, F1: 0.3415

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.29547 | val 0.71786

[I 2026-02-22 07:33:43,746] Trial 2 finished with value: 0.1848752199990833 and parameters: {'feature_set': 'sector_all_nlp', 'model_type': 'BiLSTM', 'sequence_length': 36, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 32, 'num_layers': 2, 'inter_rnn_drop': 0.0, 'dropout': 0.5, 'batch_size': 64, 'learning_rate': 0.004141814111878786, 'weight_decay': 2.2080223759282217e-06, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 20, 'huber_delta': 0.9703563233341959, 'early_stopping_min_delta': 0.005258922006524895}. Best is trial 2 with value: 0.1848752199990833.

  Epoch 016 - train 0.06796 | val 1.58701
  Classification -> best τ=0.470 (val F1=0.3689)
  Directional -> Accuracy: 0.5000, MCC: 0.0600, F1: 0.6133

================================================================================
Pipeline completed: 47/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (47, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.1848752199990833
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: classification
Sequence length: 12
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sentiment', 'emotion_anger', 'emotion_disgust', 'emotion_fear', 'emotion_joy', 'emotion_neutral', 'emotion_sadness', 'emotion_surprize', 'emotion_anger_pct', 'emotion_disgust_pct', 'emotion_fear_pct', 'emotion_joy_pct', 'emotion_neutral_pct', 'emotion_sadness_pct', 'emotion_surprize_pct', 'positive_emotion', 'negative_emotion', 'uncertainty_emotion', 'positive_emotion_pct', 'negative_emotion_pct', 'uncertainty_emotion_pct', 'stance_label', 'stance_score', 'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down', 'finbert_neutral']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.62242 | val 1.09962
  Epoch 020 - train 0.48366 | val 1.39896
  Classification -> best τ=0.610 (val F1=0.1738)
  Directional -> Accuracy: 0.5000, MCC: -0.0861, F1: 0.2041

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 88). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.58504 | val 0.71496
  Epoch 020 - train 0.49455 | val 0.74471
  Classification -> best τ=0.415 (val F1=0.2805)
  Directional -> Accuracy: 0.5745, MCC: 0.1641, F1: 0.7222

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 88). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.63356 | val 0.65357
  Epoch 020 - train 0.47184 | val 0.87926
  Classification -> best τ=0.545 (val F1=0.4787)
  Directional -> Accuracy: 0.5625, MCC: 0.1290, F1: 0.5714

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.63654 | val 0.83860
  Epoch 020 - train 0.55022 | val 1.56093
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5395, MCC: 0.0000, F1: 0.7009

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.57945 | val 0.72813
  Epoch 020 - train 0.42777 | val 1.44640
  Classification -> best τ=0.570 (val F1=0.5378)
  Directional -> Accuracy: 0.6923, MCC: 0.4024, F1: 0.6800

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.54782 | val 0.80089
  Epoch 020 - train 0.44019 | val 1.77636
  Classification -> best τ=0.470 (val F1=0.2156)
  Directional -> Accuracy: 0.6327, MCC: 0.2671, F1: 0.6250

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.68153 | val 0.80806
  Epoch 020 - train 0.52419 | val 1.18403
  Classification -> best τ=0.510 (val F1=0.2488)
  Directional -> Accuracy: 0.5000, MCC: -0.0117, F1: 0.4262

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 88). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 88). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.57995 | val 1.28085
  Epoch 020 - train 0.52703 | val 0.84353
  Classification -> best τ=0.525 (val F1=0.3669)
  Directional -> Accuracy: 0.5556, MCC: -0.0481, F1: 0.0909

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.66140 | val 0.69826
  Epoch 020 - train 0.45806 | val 1.02139
  Classification -> best τ=0.565 (val F1=0.3792)
  Directional -> Accuracy: 0.5714, MCC: -0.1754, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 88). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 88). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.61796 | val 0.78113
  Epoch 020 - train 0.49169 | val 0.87030
  Classification -> best τ=0.430 (val F1=0.1694)
  Directional -> Accuracy: 0.4366, MCC: -0.0455, F1: 0.5745

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.54633 | val 0.68710
  Epoch 020 - train 0.46920 | val 1.04195
  Classification -> best τ=0.305 (val F1=0.1926)
  Directional -> Accuracy: 0.5882, MCC: 0.1697, F1: 0.4324

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.64834 | val 0.96467
  Epoch 020 - train 0.51262 | val 0.88390
  Classification -> best τ=0.500 (val F1=0.1479)
  Directional -> Accuracy: 0.5593, MCC: 0.1317, F1: 0.6579

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.61330 | val 0.95028
  Epoch 020 - train 0.48101 | val 0.92285
  Classification -> best τ=0.570 (val F1=0.1210)
  Directional -> Accuracy: 0.5455, MCC: 0.0000, F1: 0.0000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 88). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.61556 | val 0.66165
  Epoch 020 - train 0.56721 | val 0.72113
  Classification -> best τ=0.475 (val F1=0.3471)
  Directional -> Accuracy: 0.5484, MCC: 0.1022, F1: 0.6111

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.60164 | val 1.07014
  Epoch 020 - train 0.52426 | val 1.49067
  Classification -> best τ=0.615 (val F1=0.2193)
  Directional -> Accuracy: 0.5283, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.61521 | val 0.91490
  Epoch 020 - train 0.53133 | val 1.07583
  Classification -> best τ=0.495 (val F1=0.1883)
  Directional -> Accuracy: 0.5211, MCC: 0.0108, F1: 0.6222

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.61456 | val 0.98005
  Epoch 020 - train 0.51362 | val 1.46157
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.6167, MCC: 0.0000, F1: 0.7629

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.63690 | val 0.91349
  Epoch 020 - train 0.49202 | val 1.46577
  Classification -> best τ=0.545 (val F1=0.1571)
  Directional -> Accuracy: 0.3766, MCC: -0.1179, F1: 0.1111

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.63462 | val 0.69471
  Epoch 020 - train 0.53560 | val 0.78149
  Classification -> best τ=0.565 (val F1=0.3557)
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 88). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.60976 | val 0.83683
  Epoch 020 - train 0.49551 | val 1.10506
  Classification -> best τ=0.540 (val F1=0.1004)
  Directional -> Accuracy: 0.5000, MCC: 0.1387, F1: 0.1739

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.59541 | val 0.79805
  Epoch 020 - train 0.41506 | val 1.40125
  Classification -> best τ=0.490 (val F1=0.1317)
  Directional -> Accuracy: 0.4082, MCC: 0.0264, F1: 0.2162

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 88). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 88). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 88). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.60052 | val 0.74054
  Epoch 020 - train 0.50151 | val 0.80652
  Classification -> best τ=0.585 (val F1=0.2264)
  Directional -> Accuracy: 0.4925, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.60058 | val 0.77224
  Epoch 020 - train 0.51194 | val 1.71141
  Classification -> best τ=0.500 (val F1=0.2569)
  Directional -> Accuracy: 0.5254, MCC: 0.0938, F1: 0.5000

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.63179 | val 0.85528
  Epoch 020 - train 0.49009 | val 0.87727
  Classification -> best τ=0.485 (val F1=0.1921)
  Directional -> Accuracy: 0.4925, MCC: -0.0170, F1: 0.4688

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.61168 | val 0.71765
  Epoch 020 - train 0.52473 | val 0.83001
  Classification -> best τ=0.515 (val F1=0.4137)
  Directional -> Accuracy: 0.5789, MCC: 0.2579, F1: 0.4783

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.60512 | val 1.03769
  Epoch 020 - train 0.49061 | val 1.18103
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4167, MCC: 0.0000, F1: 0.5882

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.63325 | val 1.14642
  Epoch 020 - train 0.46102 | val 1.27213
  Classification -> best τ=0.460 (val F1=0.2661)
  Directional -> Accuracy: 0.5909, MCC: 0.0000, F1: 0.7429

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.61699 | val 0.88475
  Epoch 020 - train 0.49276 | val 1.08438
  Classification -> best τ=0.410 (val F1=0.2033)
  Directional -> Accuracy: 0.5172, MCC: 0.0909, F1: 0.4167

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.60325 | val 0.68069
  Epoch 020 - train 0.52211 | val 0.69436
  Classification -> best τ=0.355 (val F1=0.3901)
  Directional -> Accuracy: 0.5349, MCC: 0.0224, F1: 0.6774

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.61979 | val 0.84368
  Epoch 020 - train 0.52014 | val 1.04759
  Classification -> best τ=0.445 (val F1=0.1581)
  Directional -> Accuracy: 0.4889, MCC: -0.0629, F1: 0.6349

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.62545 | val 0.67588
  Epoch 020 - train 0.52611 | val 0.79293
  Classification -> best τ=0.580 (val F1=0.1361)
  Directional -> Accuracy: 0.4000, MCC: -0.1890, F1: 0.3077

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.63158 | val 0.71065
  Epoch 020 - train 0.52976 | val 0.78789
  Classification -> best τ=0.485 (val F1=0.1168)
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.64727 | val 0.69221
  Epoch 020 - train 0.50781 | val 1.03005
  Classification -> best τ=0.390 (val F1=0.3096)
  Directional -> Accuracy: 0.5270, MCC: 0.1525, F1: 0.4068

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 88). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.58325 | val 0.79235
  Epoch 020 - train 0.53290 | val 1.16451
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4872, MCC: 0.0000, F1: 0.6552

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.57827 | val 0.97204
  Epoch 020 - train 0.46840 | val 1.65288
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4667, MCC: 0.0000, F1: 0.6364

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.60781 | val 0.86642
  Epoch 020 - train 0.50721 | val 1.23140
  Classification -> best τ=0.450 (val F1=0.2688)
  Directional -> Accuracy: 0.5882, MCC: 0.2025, F1: 0.5882

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.59779 | val 0.72892
  Epoch 020 - train 0.49771 | val 0.83567
  Classification -> best τ=0.515 (val F1=0.2533)
  Directional -> Accuracy: 0.4545, MCC: -0.1021, F1: 0.2941

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.61675 | val 1.02270
  Epoch 020 - train 0.51503 | val 1.36174
  Classification -> best τ=0.560 (val F1=0.1571)
  Directional -> Accuracy: 0.4828, MCC: -0.0346, F1: 0.4643

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.60329 | val 1.68879
  Epoch 020 - train 0.39488 | val 3.30328
  Classification -> best τ=0.630 (val F1=0.1970)
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 88). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 88). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 88). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 88). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.59636 | val 0.73446
  Epoch 020 - train 0.49865 | val 0.96618
  Classification -> best τ=0.360 (val F1=0.2491)
  Directional -> Accuracy: 0.4500, MCC: -0.1048, F1: 0.3529

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 88). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.57050 | val 0.88051
  Epoch 020 - train 0.52978 | val 1.16120
  Classification -> best τ=0.510 (val F1=0.0510)
  Directional -> Accuracy: 0.5897, MCC: 0.1689, F1: 0.6364

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 88). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 88). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.61697 | val 1.01179
  Epoch 020 - train 0.51430 | val 1.59301
  Classification -> best τ=0.470 (val F1=0.1316)
  Directional -> Accuracy: 0.5132, MCC: 0.1155, F1: 0.6726

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 88). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 88). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 88). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.61326 | val 0.95483
  Epoch 020 - train 0.52721 | val 1.13980
  Classification -> best τ=0.500 (val F1=0.2544)
  Directional -> Accuracy: 0.6042, MCC: 0.2951, F1: 0.7077

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.59818 | val 0.77711
  Epoch 020 - train 0.48724 | val 0.78547
  Classification -> best τ=0.465 (val F1=0.3371)
  Directional -> Accuracy: 0.6444, MCC: 0.2683, F1: 0.7143

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.57996 | val 1.41902
  Epoch 020 - train 0.52513 | val 1.87792
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.3659, MCC: 0.0000, F1: 0.5357

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.60941 | val 1.25341
  Epoch 020 - train 0.51485 | val 1.09075
  Classification -> best τ=0.455 (val F1=0.2320)
  Directional -> Accuracy: 0.5263, MCC: 0.1672, F1: 0.3077

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.62570 | val 0.83561
  Epoch 020 - train 0.50885 | val 0.88474
  Classification -> best τ=0.515 (val F1=0.3793)
  Directional -> Accuracy: 0.5000, MCC: 0.0228, F1: 0.6027

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.65056 | val 0.70205
  Epoch 020 - train 0.58559 | val 0.79994
  Classification -> best τ=0.560 (val F1=0.1197)
  Directional -> Accuracy: 0.5455, MCC: 0.1101, F1: 0.4898

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.59837 | val 0.70545
  Epoch 020 - train 0.49681 | val 0.92234
  Classification -> best τ=0.490 (val F1=0.3588)
  Directional -> Accuracy: 0.5439, MCC: 0.1941, F1: 0.6905

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.62845 | val 0.72047

[I 2026-02-22 07:34:56,885] Trial 3 finished with value: 0.2155851829892739 and parameters: {'feature_set': 'all_nlp', 'model_type': 'GRU', 'sequence_length': 12, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 64, 'num_layers': 2, 'inter_rnn_drop': 0.1, 'dropout': 0.8, 'batch_size': 16, 'learning_rate': 0.0010235485681506112, 'weight_decay': 0.0005210309116003258, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 20, 'max_epochs': 20, 'huber_delta': 0.2999616715565892, 'early_stopping_min_delta': 0.0034393294908292293}. Best is trial 3 with value: 0.2155851829892739.

  Epoch 020 - train 0.50840 | val 0.70947
  Classification -> best τ=0.520 (val F1=0.3090)
  Directional -> Accuracy: 0.4355, MCC: -0.1422, F1: 0.3396

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2155851829892739
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down', 'finbert_neutral']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.63237 | val 0.91035
  Epoch 012 - train 0.59087 | val 0.97216
  Classification -> best τ=0.545 (val F1=0.1989)
  Directional -> Accuracy: 0.5455, MCC: 0.0000, F1: 0.0000

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.59402 | val 0.74168
  Epoch 011 - train 0.58735 | val 0.71385
  Classification -> best τ=0.440 (val F1=0.0805)
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.7222

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.64531 | val 0.73934
  Epoch 011 - train 0.59172 | val 0.74231
  Classification -> best τ=0.545 (val F1=0.3345)
  Directional -> Accuracy: 0.5106, MCC: 0.0603, F1: 0.3784

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.63547 | val 0.94515
  Epoch 011 - train 0.63127 | val 0.94348
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.55184 | val 1.46986
  Epoch 012 - train 0.54921 | val 1.62399
  Classification -> best τ=0.470 (val F1=0.4836)
  Directional -> Accuracy: 0.3529, MCC: -0.3499, F1: 0.4762

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.59466 | val 0.69417
  Epoch 020 - train 0.51372 | val 0.68372
  Epoch 027 - train 0.46535 | val 0.78669
  Classification -> best τ=0.435 (val F1=0.3394)
  Directional -> Accuracy: 0.5745, MCC: 0.1489, F1: 0.5000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.63395 | val 0.72475
  Epoch 011 - train 0.63611 | val 0.73973
  Classification -> best τ=0.455 (val F1=0.1334)
  Directional -> Accuracy: 0.4058, MCC: 0.0000, F1: 0.5773

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.53687 | val 1.16079
  Epoch 011 - train 0.54623 | val 1.15324
  Classification -> best τ=0.480 (val F1=0.2141)
  Directional -> Accuracy: 0.5909, MCC: 0.0872, F1: 0.3077

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.58243 | val 0.90311
  Epoch 011 - train 0.60356 | val 0.92035
  Classification -> best τ=0.570 (val F1=0.1978)
  Directional -> Accuracy: 0.5306, MCC: 0.0724, F1: 0.5306

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.58390 | val 0.73954
  Epoch 013 - train 0.55195 | val 0.75958
  Classification -> best τ=0.455 (val F1=0.1734)
  Directional -> Accuracy: 0.4429, MCC: 0.0407, F1: 0.5979

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.58592 | val 0.94032
  Epoch 011 - train 0.59572 | val 0.96018
  Classification -> best τ=0.460 (val F1=0.2125)
  Directional -> Accuracy: 0.5800, MCC: 0.1445, F1: 0.3226

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.60219 | val 1.32598
  Epoch 011 - train 0.58018 | val 1.34457
  Classification -> best τ=0.380 (val F1=0.1651)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.58506 | val 0.84916
  Epoch 011 - train 0.57344 | val 0.86289
  Classification -> best τ=0.435 (val F1=0.2454)
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.59921 | val 0.66186
  Epoch 015 - train 0.57317 | val 0.73982
  Classification -> best τ=0.325 (val F1=0.3232)
  Directional -> Accuracy: 0.5246, MCC: 0.0531, F1: 0.6506

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.60387 | val 0.74327
  Epoch 011 - train 0.57913 | val 0.71106
  Classification -> best τ=0.485 (val F1=0.2177)
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.58952 | val 0.87166
  Epoch 011 - train 0.59938 | val 0.82303
  Classification -> best τ=0.450 (val F1=0.2039)
  Directional -> Accuracy: 0.5571, MCC: 0.1312, F1: 0.7103

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.61231 | val 1.27256
  Epoch 011 - train 0.59421 | val 1.33602
  Classification -> best τ=0.585 (val F1=0.1789)
  Directional -> Accuracy: 0.4068, MCC: 0.1444, F1: 0.1026

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.61876 | val 0.97477
  Epoch 011 - train 0.61665 | val 0.96694
  Classification -> best τ=0.505 (val F1=0.1095)
  Directional -> Accuracy: 0.3947, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.60622 | val 0.66052
  Epoch 015 - train 0.56170 | val 0.86054
  Classification -> best τ=0.400 (val F1=0.3091)
  Directional -> Accuracy: 0.4923, MCC: 0.1307, F1: 0.3265

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.60390 | val 0.95463
  Epoch 011 - train 0.59005 | val 0.82658
  Classification -> best τ=0.570 (val F1=0.1861)
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.60527 | val 0.83298
  Epoch 011 - train 0.58294 | val 0.90234
  Classification -> best τ=0.450 (val F1=0.1399)
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.66411 | val 0.83201
  Epoch 011 - train 0.63840 | val 0.83102
  Classification -> best τ=0.480 (val F1=0.1288)
  Directional -> Accuracy: 0.5909, MCC: 0.1928, F1: 0.6494

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.63449 | val 0.76798
  Epoch 011 - train 0.59652 | val 0.77875
  Classification -> best τ=0.625 (val F1=0.2967)
  Directional -> Accuracy: 0.4828, MCC: 0.2033, F1: 0.1667

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.60248 | val 0.78508
  Epoch 011 - train 0.61539 | val 0.79720
  Classification -> best τ=0.480 (val F1=0.1936)
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.6392

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.58672 | val 0.66144
  Epoch 017 - train 0.53589 | val 0.65641
  Classification -> best τ=0.495 (val F1=0.3727)
  Directional -> Accuracy: 0.5893, MCC: 0.2696, F1: 0.4889

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.53299 | val 0.80290
  Epoch 011 - train 0.50272 | val 0.83689
  Classification -> best τ=0.525 (val F1=0.2774)
  Directional -> Accuracy: 0.3913, MCC: -0.2431, F1: 0.5625

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.60361 | val 0.68237
  Epoch 020 - train 0.51630 | val 0.70290
  Epoch 021 - train 0.49704 | val 0.70088
  Classification -> best τ=0.540 (val F1=0.1377)
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.56520 | val 0.97134
  Epoch 011 - train 0.56857 | val 1.04015
  Classification -> best τ=0.455 (val F1=0.1914)
  Directional -> Accuracy: 0.5614, MCC: 0.3307, F1: 0.3590

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.59014 | val 0.73815
  Epoch 011 - train 0.64988 | val 0.73938
  Classification -> best τ=0.585 (val F1=0.2833)
  Directional -> Accuracy: 0.4878, MCC: 0.0202, F1: 0.3226

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.58174 | val 1.81320
  Epoch 011 - train 0.55002 | val 2.03937
  Classification -> best τ=0.590 (val F1=0.2683)
  Directional -> Accuracy: 0.4884, MCC: -0.0353, F1: 0.3529

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.59347 | val 0.74341
  Epoch 011 - train 0.62060 | val 0.73651
  Classification -> best τ=0.510 (val F1=0.1667)
  Directional -> Accuracy: 0.4651, MCC: -0.0282, F1: 0.2069

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.57862 | val 1.06027
  Epoch 011 - train 0.57172 | val 1.12565
  Classification -> best τ=0.435 (val F1=0.0723)
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.59338 | val 0.62989
  Epoch 019 - train 0.51191 | val 0.68844
  Classification -> best τ=0.345 (val F1=0.4049)
  Directional -> Accuracy: 0.5616, MCC: 0.1446, F1: 0.5556

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.59181 | val 0.71331
  Epoch 011 - train 0.58849 | val 0.72011
  Classification -> best τ=0.470 (val F1=0.1325)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.57547 | val 0.93780
  Epoch 011 - train 0.57743 | val 0.95274
  Classification -> best τ=0.480 (val F1=0.2757)
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.58909 | val 1.04249
  Epoch 011 - train 0.60197 | val 1.03549
  Classification -> best τ=0.490 (val F1=0.3444)
  Directional -> Accuracy: 0.4627, MCC: 0.0044, F1: 0.3077

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.52537 | val 0.68619
  Epoch 020 - train 0.48123 | val 0.74103
  Epoch 023 - train 0.42234 | val 0.76161
  Classification -> best τ=0.760 (val F1=0.4404)
  Directional -> Accuracy: 0.4884, MCC: -0.0094, F1: 0.2143

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.54059 | val 0.89759
  Epoch 011 - train 0.55635 | val 0.91802
  Classification -> best τ=0.510 (val F1=0.1508)
  Directional -> Accuracy: 0.5263, MCC: 0.1409, F1: 0.6494

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.59010 | val 0.90394
  Epoch 011 - train 0.53843 | val 0.90049
  Classification -> best τ=0.580 (val F1=0.1978)
  Directional -> Accuracy: 0.4255, MCC: 0.0391, F1: 0.2286

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.58446 | val 0.70830
  Epoch 017 - train 0.49954 | val 0.71712
  Classification -> best τ=0.390 (val F1=0.3568)
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.55499 | val 1.01789
  Epoch 011 - train 0.55590 | val 1.07515
  Classification -> best τ=0.460 (val F1=0.2227)
  Directional -> Accuracy: 0.3947, MCC: -0.2270, F1: 0.4651

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.57993 | val 0.92684
  Epoch 013 - train 0.56640 | val 1.02921
  Classification -> best τ=0.390 (val F1=0.4061)
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.59258 | val 0.70963
  Epoch 011 - train 0.62843 | val 0.71390
  Classification -> best τ=0.495 (val F1=0.2382)
  Directional -> Accuracy: 0.4894, MCC: -0.0258, F1: 0.5385

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.56139 | val 0.70399
  Epoch 011 - train 0.56837 | val 0.70376
  Classification -> best τ=0.520 (val F1=0.1322)
  Directional -> Accuracy: 0.5455, MCC: 0.0856, F1: 0.5833

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.58879 | val 0.71415
  Epoch 011 - train 0.60455 | val 0.71244
  Classification -> best τ=0.490 (val F1=0.0945)
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.61749 | val 0.78403
  Epoch 011 - train 0.59467 | val 0.79977
  Classification -> best τ=0.515 (val F1=0.1548)
  Directional -> Accuracy: 0.4643, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.60264 | val 1.32234
  Epoch 011 - train 0.56617 | val 1.31979
  Classification -> best τ=0.580 (val F1=0.4045)
  Directional -> Accuracy: 0.4912, MCC: 0.0458, F1: 0.6329

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.59676 | val 1.03441
  Epoch 011 - train 0.60382 | val 1.06229
  Classification -> best τ=0.415 (val F1=0.2569)
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.60490 | val 0.94234
  Epoch 011 - train 0.57289 | val 0.99016
  Classification -> best τ=0.505 (val F1=0.1168)
  Directional -> Accuracy: 0.5179, MCC: 0.0000, F1: 0.6824

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.59327 | val 0.70553

[I 2026-02-22 07:36:28,550] Trial 4 finished with value: 0.2281230213287852 and parameters: {'feature_set': 'finbert', 'model_type': 'BiGRU', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 64, 'num_layers': 2, 'inter_rnn_drop': 0.4, 'dropout': 0.4, 'batch_size': 64, 'learning_rate': 0.0020142520376580323, 'weight_decay': 8.809702844053418e-07, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 0.3143075596977944, 'early_stopping_min_delta': 0.006053561215678717}. Best is trial 4 with value: 0.2281230213287852.

  Epoch 015 - train 0.55154 | val 0.82824
  Classification -> best τ=0.525 (val F1=0.2406)
  Directional -> Accuracy: 0.5246, MCC: 0.0163, F1: 0.1714

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2281230213287852
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 12
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d', 'sentiment']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.69907 | val 0.68872
  Epoch 020 - train 0.70408 | val 0.68584
  Epoch 030 - train 0.70310 | val 0.68571
  Epoch 037 - train 0.69909 | val 0.68570
  Classification -> best τ=0.560 (val F1=0.2950)
  Directional -> Accuracy: 0.5641, MCC: 0.0775, F1: 0.1905

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 88). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.69600 | val 0.68450
  Epoch 020 - train 0.70631 | val 0.68742
  Epoch 025 - train 0.69340 | val 0.68796
  Classification -> best τ=0.500 (val F1=0.1692)
  Directional -> Accuracy: 0.5745, MCC: 0.1641, F1: 0.7222

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 88). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.69627 | val 0.69175
  Epoch 020 - train 0.69549 | val 0.70018
  Epoch 024 - train 0.71329 | val 0.70020
  Classification -> best τ=0.475 (val F1=0.3590)
  Directional -> Accuracy: 0.5417, MCC: 0.0000, F1: 0.7027

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.71686 | val 0.71006
  Epoch 020 - train 0.69686 | val 0.71121
  Epoch 021 - train 0.69995 | val 0.71127
  Classification -> best τ=0.445 (val F1=0.1217)
  Directional -> Accuracy: 0.5395, MCC: 0.0232, F1: 0.6847

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.71858 | val 0.70393
  Epoch 020 - train 0.72811 | val 0.70335
  Epoch 021 - train 0.70233 | val 0.70324
  Classification -> best τ=0.465 (val F1=0.0077)
  Directional -> Accuracy: 0.3462, MCC: -0.3493, F1: 0.4516

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.75956 | val 0.70546
  Epoch 020 - train 0.74754 | val 0.72033
  Epoch 021 - train 0.71841 | val 0.72128
  Classification -> best τ=0.495 (val F1=0.0742)
  Directional -> Accuracy: 0.5102, MCC: 0.0000, F1: 0.6757

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.71000 | val 0.72477
  Epoch 020 - train 0.70441 | val 0.73893
  Epoch 021 - train 0.71760 | val 0.73894
  Classification -> best τ=0.505 (val F1=0.2791)
  Directional -> Accuracy: 0.5143, MCC: 0.0233, F1: 0.4516

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 88). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 88). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.69727 | val 0.69345
  Epoch 020 - train 0.69385 | val 0.67331
  Epoch 030 - train 0.72342 | val 0.65991
  Epoch 040 - train 0.70849 | val 0.65770
  Epoch 050 - train 0.70459 | val 0.65888
  Classification -> best τ=0.395 (val F1=0.1890)
  Directional -> Accuracy: 0.4889, MCC: 0.0675, F1: 0.5660

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.68915 | val 0.69020
  Epoch 020 - train 0.70195 | val 0.69082
  Epoch 021 - train 0.71664 | val 0.69089
  Classification -> best τ=0.530 (val F1=0.3303)
  Directional -> Accuracy: 0.6190, MCC: 0.2831, F1: 0.6000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 88). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 88). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.69440 | val 0.70767
  Epoch 020 - train 0.70786 | val 0.70912
  Epoch 021 - train 0.70489 | val 0.70911
  Classification -> best τ=0.490 (val F1=0.1429)
  Directional -> Accuracy: 0.4789, MCC: -0.0195, F1: 0.4932

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.70331 | val 0.68895
  Epoch 020 - train 0.72087 | val 0.68016
  Epoch 030 - train 0.71319 | val 0.67971
  Epoch 040 - train 0.70567 | val 0.67967
  Epoch 041 - train 0.71094 | val 0.67968
  Classification -> best τ=0.520 (val F1=0.2656)
  Directional -> Accuracy: 0.4314, MCC: -0.1775, F1: 0.2564

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.70220 | val 0.83508
  Epoch 020 - train 0.71672 | val 0.94776
  Epoch 021 - train 0.72393 | val 0.94906
  Classification -> best τ=0.425 (val F1=0.3016)
  Directional -> Accuracy: 0.4576, MCC: -0.1774, F1: 0.6190

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.70887 | val 0.70912
  Epoch 020 - train 0.69887 | val 0.72038
  Epoch 021 - train 0.69286 | val 0.72077
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 88). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.74100 | val 0.76944
  Epoch 020 - train 0.73487 | val 0.79954
  Epoch 021 - train 0.75168 | val 0.79969
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.71093 | val 0.72894
  Epoch 020 - train 0.70372 | val 0.76014
  Epoch 021 - train 0.71226 | val 0.76050
  Classification -> best τ=0.525 (val F1=0.2362)
  Directional -> Accuracy: 0.5472, MCC: 0.1468, F1: 0.0769

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.71539 | val 0.67939
  Epoch 020 - train 0.70797 | val 0.68091
  Epoch 025 - train 0.69558 | val 0.68074
  Classification -> best τ=0.555 (val F1=0.1545)
  Directional -> Accuracy: 0.4930, MCC: -0.0032, F1: 0.4706

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.70323 | val 0.69619
  Epoch 020 - train 0.71725 | val 0.69612
  Epoch 021 - train 0.70679 | val 0.69616
  Classification -> best τ=0.495 (val F1=0.1753)
  Directional -> Accuracy: 0.3833, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.67634 | val 0.68869
  Epoch 020 - train 0.69542 | val 0.68935
  Epoch 024 - train 0.69508 | val 0.68914
  Classification -> best τ=0.575 (val F1=0.2251)
  Directional -> Accuracy: 0.4026, MCC: -0.0409, F1: 0.1786

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.70294 | val 0.72680
  Epoch 020 - train 0.70394 | val 0.72934
  Epoch 021 - train 0.72002 | val 0.72924
  Classification -> best τ=0.495 (val F1=0.1833)
  Directional -> Accuracy: 0.4242, MCC: 0.1032, F1: 0.0500

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 88). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.70495 | val 0.69837
  Epoch 020 - train 0.69452 | val 0.69940
  Epoch 021 - train 0.70689 | val 0.69936
  Classification -> best τ=0.490 (val F1=0.2043)
  Directional -> Accuracy: 0.4605, MCC: -0.0130, F1: 0.0465

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.72356 | val 0.68608
  Epoch 020 - train 0.72162 | val 0.68973
  Epoch 029 - train 0.74561 | val 0.69006
  Classification -> best τ=0.465 (val F1=0.3513)
  Directional -> Accuracy: 0.4490, MCC: -0.1229, F1: 0.5263

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 88). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 88). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 88). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.70393 | val 0.69021
  Epoch 020 - train 0.69849 | val 0.69256
  Epoch 021 - train 0.69823 | val 0.69256
  Classification -> best τ=0.455 (val F1=0.2014)
  Directional -> Accuracy: 0.5075, MCC: 0.0112, F1: 0.5714

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.73392 | val 0.72423
  Epoch 020 - train 0.71899 | val 0.74407
  Epoch 021 - train 0.74666 | val 0.74411
  Classification -> best τ=0.470 (val F1=0.1336)
  Directional -> Accuracy: 0.5424, MCC: -0.1606, F1: 0.7033

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.70332 | val 0.68781
  Epoch 020 - train 0.69568 | val 0.68605
  Epoch 030 - train 0.69046 | val 0.68601
  Epoch 038 - train 0.68172 | val 0.68597
  Classification -> best τ=0.480 (val F1=0.1824)
  Directional -> Accuracy: 0.5075, MCC: 0.1677, F1: 0.6598

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.69261 | val 0.71109
  Epoch 020 - train 0.69732 | val 0.71726
  Epoch 021 - train 0.68070 | val 0.71725
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5614, MCC: 0.0000, F1: 0.7191

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.70030 | val 0.67583
  Epoch 020 - train 0.69413 | val 0.66645
  Epoch 030 - train 0.71226 | val 0.66290
  Epoch 040 - train 0.72549 | val 0.66236
  Epoch 047 - train 0.69958 | val 0.66235
  Classification -> best τ=0.570 (val F1=0.4291)
  Directional -> Accuracy: 0.4792, MCC: 0.0812, F1: 0.5763

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.68673 | val 0.69894
  Epoch 020 - train 0.68699 | val 0.70456
  Epoch 021 - train 0.68852 | val 0.70483
  Classification -> best τ=0.490 (val F1=0.0790)
  Directional -> Accuracy: 0.5227, MCC: 0.1336, F1: 0.4615

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.73137 | val 0.68005
  Epoch 020 - train 0.70457 | val 0.68133
  Epoch 028 - train 0.71199 | val 0.68143
  Classification -> best τ=0.505 (val F1=0.2970)
  Directional -> Accuracy: 0.4828, MCC: -0.0170, F1: 0.4643

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.70889 | val 0.68408
  Epoch 020 - train 0.68727 | val 0.67401
  Epoch 030 - train 0.70838 | val 0.66902
  Epoch 040 - train 0.69385 | val 0.66801
  Epoch 050 - train 0.68446 | val 0.66783
  Classification -> best τ=0.565 (val F1=0.6237)
  Directional -> Accuracy: 0.5349, MCC: 0.0716, F1: 0.5455

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.69558 | val 0.70732
  Epoch 020 - train 0.71529 | val 0.72092
  Epoch 021 - train 0.71119 | val 0.72138
  Classification -> best τ=0.530 (val F1=0.3436)
  Directional -> Accuracy: 0.5111, MCC: 0.0165, F1: 0.5769

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.72238 | val 0.67462
  Epoch 020 - train 0.72449 | val 0.67029
  Epoch 030 - train 0.71613 | val 0.66969
  Epoch 038 - train 0.71701 | val 0.66996
  Classification -> best τ=0.585 (val F1=0.1195)
  Directional -> Accuracy: 0.4444, MCC: -0.1129, F1: 0.4681

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.72988 | val 0.69505
  Epoch 020 - train 0.70836 | val 0.69868
  Epoch 021 - train 0.70520 | val 0.69869
  Classification -> best τ=0.485 (val F1=0.1199)
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.72776 | val 0.74348
  Epoch 020 - train 0.75150 | val 0.74393
  Epoch 021 - train 0.73304 | val 0.74378
  Classification -> best τ=0.500 (val F1=0.0176)
  Directional -> Accuracy: 0.5676, MCC: 0.0000, F1: 0.7241

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 88). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.68945 | val 0.70022
  Epoch 020 - train 0.71967 | val 0.71426
  Epoch 021 - train 0.67697 | val 0.71569
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4872, MCC: 0.0000, F1: 0.6552

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.71597 | val 0.69380
  Epoch 020 - train 0.68328 | val 0.69664
  Epoch 028 - train 0.70849 | val 0.69709
  Classification -> best τ=0.480 (val F1=0.2295)
  Directional -> Accuracy: 0.6444, MCC: 0.2971, F1: 0.5000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.72985 | val 0.68850
  Epoch 020 - train 0.71706 | val 0.69077
  Epoch 021 - train 0.73793 | val 0.69076
  Classification -> best τ=0.450 (val F1=0.2734)
  Directional -> Accuracy: 0.4265, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.71290 | val 0.69052
  Epoch 020 - train 0.70959 | val 0.69213
  Epoch 021 - train 0.69792 | val 0.69229
  Classification -> best τ=0.480 (val F1=0.1517)
  Directional -> Accuracy: 0.6364, MCC: 0.2928, F1: 0.5556

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.70585 | val 0.68035
  Epoch 020 - train 0.70018 | val 0.67824
  Epoch 030 - train 0.68716 | val 0.67800
  Epoch 032 - train 0.70155 | val 0.67794
  Classification -> best τ=0.430 (val F1=0.1955)
  Directional -> Accuracy: 0.4655, MCC: 0.0000, F1: 0.6353

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.70715 | val 0.71803
  Epoch 020 - train 0.71606 | val 0.73193
  Epoch 021 - train 0.72536 | val 0.73226
  Classification -> best τ=0.520 (val F1=0.2713)
  Directional -> Accuracy: 0.6042, MCC: 0.1089, F1: 0.7077

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 88). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 88). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 88). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 88). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.68474 | val 0.70461
  Epoch 020 - train 0.67681 | val 0.70644
  Epoch 021 - train 0.68503 | val 0.70619
  Classification -> best τ=0.505 (val F1=0.1391)
  Directional -> Accuracy: 0.3500, MCC: -0.0721, F1: 0.5000

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 88). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.68478 | val 0.71774
  Epoch 020 - train 0.72387 | val 0.73183
  Epoch 021 - train 0.68062 | val 0.73269
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.7000

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 88). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 88). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.71473 | val 0.74964
  Epoch 020 - train 0.71726 | val 0.75895
  Epoch 021 - train 0.70504 | val 0.75889
  Classification -> best τ=0.615 (val F1=0.1125)
  Directional -> Accuracy: 0.5658, MCC: 0.1354, F1: 0.5075

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 88). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 88). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 88). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.71266 | val 0.72498
  Epoch 020 - train 0.71169 | val 0.74372
  Epoch 021 - train 0.68487 | val 0.74409
  Classification -> best τ=0.540 (val F1=0.1733)
  Directional -> Accuracy: 0.5625, MCC: 0.1348, F1: 0.4615

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.69877 | val 0.70622
  Epoch 020 - train 0.70352 | val 0.69637
  Epoch 030 - train 0.76206 | val 0.69295
  Epoch 040 - train 0.72731 | val 0.69244
  Epoch 045 - train 0.70624 | val 0.69242
  Classification -> best τ=0.515 (val F1=0.1667)
  Directional -> Accuracy: 0.4000, MCC: -0.1754, F1: 0.1290

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.72050 | val 0.68048
  Epoch 020 - train 0.68997 | val 0.67392

[I 2026-02-22 07:37:21,013] Trial 5 finished with value: 0.1937771328292593 and parameters: {'feature_set': 'sector_sentiment', 'model_type': 'BiGRU', 'sequence_length': 12, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 128, 'num_layers': 1, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.6000000000000001, 'batch_size': 64, 'learning_rate': 1.9443977726961407e-06, 'weight_decay': 0.00013142318401055327, 'lr_patience': 5, 'lr_factor': 0.8, 'early_stopping_patience': 20, 'max_epochs': 50, 'huber_delta': 1.4316863035437946, 'early_stopping_min_delta': 0.0017212321297509936}. Best is trial 4 with value: 0.2281230213287852.

  Epoch 020 - train 0.69452 | val 0.72731
  Epoch 021 - train 0.71343 | val 0.72738
  Classification -> best τ=0.455 (val F1=0.1088)
  Directional -> Accuracy: 0.5484, MCC: 0.1370, F1: 0.6410

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.1937771328292593
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: classification
Sequence length: 36
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d', 'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down', 'finbert_neutral']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.70427 | val 0.70242
  Epoch 020 - train 0.70648 | val 0.70230
  Classification -> best τ=0.495 (val F1=0.0137)
  Directional -> Accuracy: 0.4189, MCC: -0.1370, F1: 0.4691

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 112). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.70037 | val 0.67454
  Epoch 020 - train 0.68982 | val 0.66605
  Classification -> best τ=0.485 (val F1=0.3565)
  Directional -> Accuracy: 0.5116, MCC: 0.0089, F1: 0.5714

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for AEP (109 < 112). Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 112). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.71592 | val 0.69056
  Epoch 020 - train 0.71546 | val 0.69553
  Classification -> best τ=0.530 (val F1=0.2951)
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.71643 | val 0.70850
  Epoch 020 - train 0.72442 | val 0.71243
  Classification -> best τ=0.545 (val F1=0.1782)
  Directional -> Accuracy: 0.5417, MCC: 0.0000, F1: 0.7027

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.69109 | val 0.67956
  Epoch 020 - train 0.69707 | val 0.67638
  Classification -> best τ=0.585 (val F1=0.2814)
  Directional -> Accuracy: 0.4375, MCC: -0.1184, F1: 0.3721

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.70689 | val 0.69601
  Epoch 020 - train 0.70118 | val 0.70094
  Classification -> best τ=0.480 (val F1=0.1667)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.71837 | val 0.69993
  Epoch 020 - train 0.72459 | val 0.70300
  Classification -> best τ=0.460 (val F1=0.1535)
  Directional -> Accuracy: 0.4697, MCC: -0.0561, F1: 0.4262

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 112). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 112). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.72553 | val 0.65833
  Epoch 020 - train 0.70835 | val 0.66091
  Classification -> best τ=0.485 (val F1=0.3612)
  Directional -> Accuracy: 0.6410, MCC: 0.2816, F1: 0.3636

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.70937 | val 0.74579
  Epoch 020 - train 0.72147 | val 0.76791
  Classification -> best τ=0.535 (val F1=0.1429)
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 112). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 112). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 112). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.70492 | val 0.79791
  Epoch 020 - train 0.70175 | val 0.81641
  Classification -> best τ=0.480 (val F1=0.1579)
  Directional -> Accuracy: 0.4776, MCC: 0.0487, F1: 0.5570

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.70055 | val 0.73787
  Epoch 020 - train 0.70923 | val 0.74743
  Classification -> best τ=0.575 (val F1=0.3420)
  Directional -> Accuracy: 0.5532, MCC: 0.0409, F1: 0.2222

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.71516 | val 0.77690
  Epoch 020 - train 0.68743 | val 0.79933
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5273, MCC: 0.0000, F1: 0.6905

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 112). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.70119 | val 0.67107
  Epoch 020 - train 0.69367 | val 0.66199
  Classification -> best τ=0.545 (val F1=0.4328)
  Directional -> Accuracy: 0.5208, MCC: 0.0000, F1: 0.0000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 112). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.71323 | val 0.68916
  Epoch 020 - train 0.70879 | val 0.69018
  Classification -> best τ=0.435 (val F1=0.1759)
  Directional -> Accuracy: 0.5000, MCC: -0.0698, F1: 0.6588

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.71315 | val 0.70324
  Epoch 020 - train 0.70613 | val 0.71248
  Classification -> best τ=0.540 (val F1=0.3203)
  Directional -> Accuracy: 0.4286, MCC: -0.1911, F1: 0.2632

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.71099 | val 0.70196
  Epoch 020 - train 0.69816 | val 0.70558
  Classification -> best τ=0.595 (val F1=0.0222)
  Directional -> Accuracy: 0.4776, MCC: 0.1142, F1: 0.0541

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 112). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.69253 | val 0.71748
  Epoch 020 - train 0.70054 | val 0.72572
  Classification -> best τ=0.590 (val F1=0.1313)
  Directional -> Accuracy: 0.3750, MCC: -0.1328, F1: 0.1026

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.70941 | val 0.72992
  Epoch 020 - train 0.70212 | val 0.73694
  Classification -> best τ=0.510 (val F1=0.1382)
  Directional -> Accuracy: 0.4110, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.69561 | val 0.69752
  Epoch 020 - train 0.70214 | val 0.69920
  Classification -> best τ=0.460 (val F1=0.1904)
  Directional -> Accuracy: 0.5161, MCC: 0.1681, F1: 0.3750

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 112). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.71675 | val 0.70614
  Epoch 020 - train 0.71149 | val 0.70747
  Classification -> best τ=0.555 (val F1=0.1367)
  Directional -> Accuracy: 0.4861, MCC: 0.0845, F1: 0.2449

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.70110 | val 0.69424
  Epoch 020 - train 0.71054 | val 0.69463
  Classification -> best τ=0.505 (val F1=0.1195)
  Directional -> Accuracy: 0.6000, MCC: 0.0000, F1: 0.7500

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 112). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 112). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 112). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.71632 | val 0.73078
  Epoch 020 - train 0.73596 | val 0.73715
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4921, MCC: 0.0000, F1: 0.6596

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.71927 | val 0.77332
  Epoch 020 - train 0.72725 | val 0.79360
  Classification -> best τ=0.435 (val F1=0.0684)
  Directional -> Accuracy: 0.4545, MCC: -0.0952, F1: 0.5000

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.71251 | val 0.72935
  Epoch 020 - train 0.71317 | val 0.73418
  Classification -> best τ=0.600 (val F1=0.1961)
  Directional -> Accuracy: 0.5238, MCC: 0.0000, F1: 0.0000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.69306 | val 0.70542
  Epoch 020 - train 0.68313 | val 0.70772
  Classification -> best τ=0.500 (val F1=0.0874)
  Directional -> Accuracy: 0.4717, MCC: -0.0447, F1: 0.4615

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.70429 | val 0.70479
  Epoch 020 - train 0.70034 | val 0.71390
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.71392 | val 0.69647
  Epoch 020 - train 0.70231 | val 0.70206
  Classification -> best τ=0.505 (val F1=0.1402)
  Directional -> Accuracy: 0.4375, MCC: 0.0115, F1: 0.1818

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.69511 | val 0.67447
  Epoch 020 - train 0.67760 | val 0.67184
  Classification -> best τ=0.400 (val F1=0.2649)
  Directional -> Accuracy: 0.5556, MCC: 0.1930, F1: 0.4000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
Insufficient data for proper time series validation for MDT. Skipping...

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.69062 | val 0.70498
  Epoch 020 - train 0.70840 | val 0.71791
  Classification -> best τ=0.525 (val F1=0.3708)
  Directional -> Accuracy: 0.4250, MCC: -0.1601, F1: 0.3030

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.71676 | val 0.65393
  Epoch 020 - train 0.70184 | val 0.65252
  Classification -> best τ=0.665 (val F1=0.2328)
  Directional -> Accuracy: 0.4000, MCC: -0.2536, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.69378 | val 0.68177
  Epoch 020 - train 0.70701 | val 0.67896
  Classification -> best τ=0.505 (val F1=0.3115)
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.69302 | val 0.70589
  Epoch 020 - train 0.70054 | val 0.70680
  Classification -> best τ=0.460 (val F1=0.0269)
  Directional -> Accuracy: 0.4857, MCC: -0.1025, F1: 0.6087

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 112). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.71283 | val 0.70077
  Epoch 020 - train 0.70770 | val 0.70065
  Classification -> best τ=0.520 (val F1=0.2392)
  Directional -> Accuracy: 0.4694, MCC: -0.0427, F1: 0.5357

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for PCG (101 < 112). Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.71249 | val 0.71228
  Epoch 020 - train 0.70030 | val 0.72229
  Classification -> best τ=0.525 (val F1=0.1651)
  Directional -> Accuracy: 0.4375, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.68451 | val 0.70623
  Epoch 020 - train 0.70514 | val 0.71671
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4898, MCC: 0.0000, F1: 0.6575

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.71954 | val 0.75045
  Epoch 020 - train 0.72399 | val 0.77575
  Classification -> best τ=0.555 (val F1=0.2648)
  Directional -> Accuracy: 0.5000, MCC: 0.0083, F1: 0.5091

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.70608 | val 0.69217
  Epoch 020 - train 0.68810 | val 0.71447
  Classification -> best τ=0.485 (val F1=0.2891)
  Directional -> Accuracy: 0.6136, MCC: 0.0509, F1: 0.7536

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 112). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for PPL (108 < 112). Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 112). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 112). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 112). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.70223 | val 0.68987
  Epoch 020 - train 0.70492 | val 0.68765
  Classification -> best τ=0.515 (val F1=0.4432)
  Directional -> Accuracy: 0.5333, MCC: 0.0316, F1: 0.4000

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 112). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 112). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 112). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.69838 | val 0.69345
  Epoch 020 - train 0.69324 | val 0.69216
  Classification -> best τ=0.500 (val F1=0.2229)
  Directional -> Accuracy: 0.5139, MCC: 0.0695, F1: 0.6667

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 112). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 112). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 112). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 112). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.70373 | val 0.70934
  Epoch 020 - train 0.69092 | val 0.73033
  Classification -> best τ=0.490 (val F1=0.2212)
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.0000

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.70785 | val 0.70213
  Epoch 020 - train 0.69883 | val 0.70882
  Classification -> best τ=0.520 (val F1=0.1511)
  Directional -> Accuracy: 0.4615, MCC: 0.1939, F1: 0.1600

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.69103 | val 0.69162
  Epoch 020 - train 0.69758 | val 0.69477
  Classification -> best τ=0.520 (val F1=0.1195)
  Directional -> Accuracy: 0.6667, MCC: 0.2768, F1: 0.2105

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.71802 | val 0.81153
  Epoch 020 - train 0.71327 | val 0.84173
  Classification -> best τ=0.385 (val F1=0.1712)
  Directional -> Accuracy: 0.5472, MCC: 0.0000, F1: 0.7073

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.69835 | val 0.74989
  Epoch 020 - train 0.68357 | val 0.77390
  Classification -> best τ=0.495 (val F1=0.0678)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.69616 | val 0.72234
  Epoch 020 - train 0.71113 | val 0.72750
  Classification -> best τ=0.450 (val F1=0.1352)
  Directional -> Accuracy: 0.4706, MCC: -0.1442, F1: 0.6400

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.69910 | val 0.77026
  Epoch 020 - train 0.69432 | val 0.79358
  Classification -> best τ=0.540 (val F1=0.2728)
  Directional -> Accuracy: 0.5283, MCC: 0.1413, F1: 0.6835

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.69651 | val 0.73366

[I 2026-02-22 07:38:13,972] Trial 6 finished with value: 0.1834217727776325 and parameters: {'feature_set': 'sector_finbert', 'model_type': 'GRU', 'sequence_length': 36, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 64, 'num_layers': 1, 'inter_rnn_drop': 0.1, 'dropout': 0.5, 'batch_size': 64, 'learning_rate': 3.230600378307401e-06, 'weight_decay': 1.6610714253634e-07, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 20, 'huber_delta': 0.32498730231090717, 'early_stopping_min_delta': 0.0022336632758730122}. Best is trial 4 with value: 0.2281230213287852.

  Epoch 020 - train 0.69933 | val 0.74217
  Classification -> best τ=0.500 (val F1=0.0423)
  Directional -> Accuracy: 0.4310, MCC: -0.1229, F1: 0.4923

================================================================================
Pipeline completed: 47/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (47, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.1834217727776325
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d', 'emotion_anger', 'emotion_disgust', 'emotion_fear', 'emotion_joy', 'emotion_neutral', 'emotion_sadness', 'emotion_surprize', 'emotion_anger_pct', 'emotion_disgust_pct', 'emotion_fear_pct', 'emotion_joy_pct', 'emotion_neutral_pct', 'emotion_sadness_pct', 'emotion_surprize_pct']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.61701 | val 0.68842
  Epoch 020 - train 0.53571 | val 0.71664
  Epoch 028 - train 0.49705 | val 0.79174
  Classification -> best τ=0.655 (val F1=0.2510)
  Directional -> Accuracy: 0.5658, MCC: 0.0795, F1: 0.1951

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.61697 | val 0.69557
  Epoch 020 - train 0.52114 | val 0.68520
  Epoch 030 - train 0.45605 | val 0.73616
  Classification -> best τ=0.455 (val F1=0.3022)
  Directional -> Accuracy: 0.5778, MCC: 0.0000, F1: 0.7324

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.64142 | val 0.69460
  Epoch 016 - train 0.60743 | val 0.71126
  Classification -> best τ=0.510 (val F1=0.2259)
  Directional -> Accuracy: 0.5652, MCC: 0.1461, F1: 0.6875

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.61673 | val 0.85309
  Epoch 016 - train 0.59849 | val 1.22123
  Classification -> best τ=0.520 (val F1=0.1722)
  Directional -> Accuracy: 0.5676, MCC: 0.1334, F1: 0.5897

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.59126 | val 0.68102
  Epoch 020 - train 0.52922 | val 0.76621
  Epoch 021 - train 0.51758 | val 0.77908
  Classification -> best τ=0.540 (val F1=0.2890)
  Directional -> Accuracy: 0.4800, MCC: 0.0000, F1: 0.0000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.63950 | val 0.69479
  Epoch 016 - train 0.60980 | val 0.69483
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4783, MCC: 0.0000, F1: 0.6471

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.64958 | val 0.68541
  Epoch 020 - train 0.57765 | val 0.76660
  Epoch 023 - train 0.55326 | val 0.84092
  Classification -> best τ=0.500 (val F1=0.2648)
  Directional -> Accuracy: 0.5147, MCC: 0.0552, F1: 0.4923

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.63432 | val 0.67183
  Epoch 020 - train 0.54445 | val 0.64311
  Epoch 030 - train 0.49723 | val 0.57695
  Classification -> best τ=0.440 (val F1=0.4176)
  Directional -> Accuracy: 0.4524, MCC: -0.0700, F1: 0.4651

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.63062 | val 0.69630
  Epoch 016 - train 0.58280 | val 0.71469
  Classification -> best τ=0.495 (val F1=0.1456)
  Directional -> Accuracy: 0.5625, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.60316 | val 0.70237
  Epoch 016 - train 0.57128 | val 0.72651
  Classification -> best τ=0.465 (val F1=0.0093)
  Directional -> Accuracy: 0.5072, MCC: 0.0077, F1: 0.4516

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.62215 | val 0.68540
  Epoch 016 - train 0.59113 | val 0.73092
  Classification -> best τ=0.455 (val F1=0.0385)
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.63027 | val 0.71496
  Epoch 016 - train 0.58970 | val 0.79760
  Classification -> best τ=0.490 (val F1=0.2157)
  Directional -> Accuracy: 0.5088, MCC: 0.0000, F1: 0.6744

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.59825 | val 0.69924
  Epoch 016 - train 0.58379 | val 0.74782
  Classification -> best τ=0.525 (val F1=0.1308)
  Directional -> Accuracy: 0.5476, MCC: 0.0000, F1: 0.0000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.61445 | val 0.65835
  Epoch 020 - train 0.55895 | val 0.66728
  Epoch 028 - train 0.51656 | val 0.72205
  Classification -> best τ=0.545 (val F1=0.4317)
  Directional -> Accuracy: 0.4667, MCC: -0.1857, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.59071 | val 0.69984
  Epoch 016 - train 0.58434 | val 0.75472
  Classification -> best τ=0.470 (val F1=0.0333)
  Directional -> Accuracy: 0.5490, MCC: 0.0199, F1: 0.0800

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.61322 | val 0.68956
  Epoch 016 - train 0.58119 | val 0.78728
  Classification -> best τ=0.510 (val F1=0.1741)
  Directional -> Accuracy: 0.5362, MCC: 0.0333, F1: 0.6596

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.63239 | val 0.71538
  Epoch 016 - train 0.57833 | val 0.80236
  Classification -> best τ=0.515 (val F1=0.2048)
  Directional -> Accuracy: 0.3276, MCC: -0.3106, F1: 0.3390

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.64898 | val 0.70657
  Epoch 016 - train 0.60371 | val 0.75705
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.6000, MCC: 0.0000, F1: 0.7500

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.62254 | val 0.68171
  Epoch 020 - train 0.55523 | val 0.71652
  Epoch 025 - train 0.53574 | val 0.75514
  Classification -> best τ=0.605 (val F1=0.2234)
  Directional -> Accuracy: 0.4219, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.61818 | val 0.67838
  Epoch 020 - train 0.55756 | val 0.70371
  Epoch 028 - train 0.50821 | val 0.83248
  Classification -> best τ=0.460 (val F1=0.2871)
  Directional -> Accuracy: 0.4595, MCC: 0.0249, F1: 0.1304

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.62053 | val 0.70016
  Epoch 016 - train 0.58713 | val 0.71358
  Classification -> best τ=0.450 (val F1=0.1572)
  Directional -> Accuracy: 0.5745, MCC: -0.0391, F1: 0.7143

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.63939 | val 0.67058
  Epoch 020 - train 0.58494 | val 0.70409
  Epoch 027 - train 0.52737 | val 0.76140
  Classification -> best τ=0.440 (val F1=0.3279)
  Directional -> Accuracy: 0.4615, MCC: -0.1809, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.61025 | val 0.65427
  Epoch 020 - train 0.54281 | val 0.74145
  Epoch 026 - train 0.50907 | val 0.87316
  Classification -> best τ=0.665 (val F1=0.3749)
  Directional -> Accuracy: 0.5263, MCC: 0.1434, F1: 0.4000

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.61059 | val 0.69112
  Epoch 016 - train 0.57478 | val 0.79502
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4769, MCC: 0.0000, F1: 0.6458

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.59918 | val 0.67521
  Epoch 020 - train 0.53595 | val 0.64730
  Epoch 030 - train 0.45588 | val 0.71766
  Classification -> best τ=0.410 (val F1=0.3750)
  Directional -> Accuracy: 0.5818, MCC: 0.2024, F1: 0.5306

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.59633 | val 0.69327
  Epoch 016 - train 0.58928 | val 0.69444
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.5938

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.61610 | val 0.68408
  Epoch 020 - train 0.55649 | val 0.67882
  Epoch 030 - train 0.49983 | val 0.70301
  Classification -> best τ=0.585 (val F1=0.2071)
  Directional -> Accuracy: 0.5000, MCC: 0.0782, F1: 0.4000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.61715 | val 0.69628
  Epoch 016 - train 0.58206 | val 0.74153
  Classification -> best τ=0.485 (val F1=0.1428)
  Directional -> Accuracy: 0.4464, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.63768 | val 0.69346
  Epoch 016 - train 0.61925 | val 0.69441
  Classification -> best τ=0.480 (val F1=0.4181)
  Directional -> Accuracy: 0.4500, MCC: -0.1370, F1: 0.5417

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.62785 | val 0.70600
  Epoch 016 - train 0.59922 | val 0.72203
  Classification -> best τ=0.530 (val F1=0.2065)
  Directional -> Accuracy: 0.5476, MCC: 0.0953, F1: 0.5366

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.61717 | val 0.72411
  Epoch 016 - train 0.59021 | val 0.76785
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5476, MCC: 0.0000, F1: 0.7077

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.62301 | val 0.68476
  Epoch 020 - train 0.52976 | val 0.72723
  Epoch 027 - train 0.48847 | val 0.86007
  Classification -> best τ=0.470 (val F1=0.3433)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.62196 | val 0.67266
  Epoch 020 - train 0.54940 | val 0.72423
  Epoch 024 - train 0.52435 | val 0.76762
  Classification -> best τ=0.420 (val F1=0.3252)
  Directional -> Accuracy: 0.5000, MCC: 0.0747, F1: 0.3571

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.61391 | val 0.70840
  Epoch 020 - train 0.54237 | val 0.70720
  Epoch 030 - train 0.47639 | val 0.76793
  Classification -> best τ=0.480 (val F1=0.2324)
  Directional -> Accuracy: 0.5581, MCC: 0.2093, F1: 0.6780

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.64576 | val 0.69723
  Epoch 016 - train 0.60205 | val 0.73069
  Classification -> best τ=0.540 (val F1=0.0794)
  Directional -> Accuracy: 0.4242, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.62196 | val 0.68906
  Epoch 020 - train 0.52642 | val 0.67842
  Epoch 030 - train 0.44066 | val 0.70718
  Classification -> best τ=0.595 (val F1=0.3828)
  Directional -> Accuracy: 0.6667, MCC: 0.3553, F1: 0.6316

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.58691 | val 0.68010
  Epoch 020 - train 0.52194 | val 0.94178
  Epoch 021 - train 0.50662 | val 0.97814
  Classification -> best τ=0.475 (val F1=0.1951)
  Directional -> Accuracy: 0.5179, MCC: 0.0780, F1: 0.5970

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.60824 | val 0.70585
  Epoch 016 - train 0.55869 | val 0.73195
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.6087, MCC: 0.0000, F1: 0.7568

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.60385 | val 0.69076
  Epoch 016 - train 0.57879 | val 0.68757
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.63170 | val 0.70586
  Epoch 016 - train 0.58659 | val 0.82721
  Classification -> best τ=0.470 (val F1=0.0131)
  Directional -> Accuracy: 0.4865, MCC: 0.0000, F1: 0.6545

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.62998 | val 0.68855
  Epoch 020 - train 0.58127 | val 0.69528
  Epoch 023 - train 0.55777 | val 0.70619
  Classification -> best τ=0.495 (val F1=0.2982)
  Directional -> Accuracy: 0.4667, MCC: -0.2109, F1: 0.6364

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.58360 | val 0.70840
  Epoch 016 - train 0.55863 | val 0.70721
  Classification -> best τ=0.540 (val F1=0.2010)
  Directional -> Accuracy: 0.5238, MCC: 0.1750, F1: 0.3750

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.63864 | val 0.70484
  Epoch 016 - train 0.62859 | val 0.70659
  Classification -> best τ=0.490 (val F1=0.2902)
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.0000

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.60690 | val 0.69290
  Epoch 020 - train 0.55124 | val 0.73815
  Epoch 027 - train 0.50846 | val 0.79496
  Classification -> best τ=0.565 (val F1=0.2085)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.62655 | val 0.69134
  Epoch 020 - train 0.53523 | val 0.79969
  Epoch 023 - train 0.50349 | val 0.87165
  Classification -> best τ=0.505 (val F1=0.3249)
  Directional -> Accuracy: 0.4821, MCC: -0.0309, F1: 0.5085

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.64492 | val 0.68111
  Epoch 016 - train 0.59865 | val 0.69784
  Classification -> best τ=0.550 (val F1=0.1122)
  Directional -> Accuracy: 0.5094, MCC: 0.0080, F1: 0.6389

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.62740 | val 0.71312
  Epoch 016 - train 0.57147 | val 0.85861
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5273, MCC: 0.0000, F1: 0.6905

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.63252 | val 0.68805

[I 2026-02-22 07:40:00,296] Trial 7 finished with value: 0.18819215126982194 and parameters: {'feature_set': 'sector_emotion', 'model_type': 'BiLSTM', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 64, 'num_layers': 2, 'inter_rnn_drop': 0.1, 'dropout': 0.5, 'batch_size': 64, 'learning_rate': 0.00039207330650769455, 'weight_decay': 1.5872658258890911e-07, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 15, 'max_epochs': 30, 'huber_delta': 0.24389306496976274, 'early_stopping_min_delta': 0.004335210261507253}. Best is trial 4 with value: 0.2281230213287852.

  Epoch 016 - train 0.59428 | val 0.70320
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4833, MCC: 0.0000, F1: 0.6517

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.18819215126982194
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: classification
Sequence length: 12
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d', 'sentiment', 'emotion_anger', 'emotion_disgust', 'emotion_fear', 'emotion_joy', 'emotion_neutral', 'emotion_sadness', 'emotion_surprize', 'emotion_anger_pct', 'emotion_disgust_pct', 'emotion_fear_pct', 'emotion_joy_pct', 'emotion_neutral_pct', 'emotion_sadness_pct', 'emotion_surprize_pct', 'positive_emotion', 'negative_emotion', 'uncertainty_emotion', 'positive_emotion_pct', 'negative_emotion_pct', 'uncertainty_emotion_pct', 'stance_label', 'stance_score', 'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down', 'finbert_neutral']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.67485 | val 0.74240
  Epoch 016 - train 0.67647 | val 0.74217
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4487, MCC: 0.0000, F1: 0.6195

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 88). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.69432 | val 0.69756
  Epoch 016 - train 0.67122 | val 0.69842
  Classification -> best τ=0.480 (val F1=0.0237)
  Directional -> Accuracy: 0.4894, MCC: 0.0654, F1: 0.2941

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 88). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.68045 | val 0.72791
  Epoch 016 - train 0.68701 | val 0.73158
  Classification -> best τ=0.530 (val F1=0.1940)
  Directional -> Accuracy: 0.4583, MCC: -0.0174, F1: 0.0714

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.69643 | val 0.74052
  Epoch 016 - train 0.68948 | val 0.74352
  Classification -> best τ=0.480 (val F1=0.1217)
  Directional -> Accuracy: 0.5395, MCC: 0.0000, F1: 0.7009

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.69940 | val 0.72291
  Epoch 016 - train 0.69049 | val 0.71832
  Classification -> best τ=0.445 (val F1=0.0111)
  Directional -> Accuracy: 0.4808, MCC: -0.1177, F1: 0.6197

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.65998 | val 0.70958
  Epoch 016 - train 0.66484 | val 0.72171
  Classification -> best τ=0.455 (val F1=0.1502)
  Directional -> Accuracy: 0.5102, MCC: 0.0000, F1: 0.6757

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.68328 | val 0.69882
  Epoch 016 - train 0.67895 | val 0.69851
  Classification -> best τ=0.505 (val F1=0.0941)
  Directional -> Accuracy: 0.5000, MCC: -0.0117, F1: 0.4262

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 88). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 88). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.69563 | val 0.72435
  Epoch 020 - train 0.66466 | val 0.71885
  Epoch 030 - train 0.67124 | val 0.72396
  Classification -> best τ=0.440 (val F1=0.1512)
  Directional -> Accuracy: 0.4222, MCC: -0.1842, F1: 0.3158

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.70470 | val 0.69384
  Epoch 020 - train 0.69263 | val 0.68886
  Epoch 027 - train 0.69787 | val 0.68891
  Classification -> best τ=0.445 (val F1=0.3093)
  Directional -> Accuracy: 0.5238, MCC: -0.0932, F1: 0.2308

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 88). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 88). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.70384 | val 0.78159
  Epoch 016 - train 0.70251 | val 0.78999
  Classification -> best τ=0.480 (val F1=0.3297)
  Directional -> Accuracy: 0.3803, MCC: -0.2430, F1: 0.5417

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.71266 | val 0.91093
  Epoch 016 - train 0.69493 | val 0.92078
  Classification -> best τ=0.540 (val F1=0.1557)
  Directional -> Accuracy: 0.4706, MCC: 0.0000, F1: 0.6400

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.68050 | val 0.69939
  Epoch 016 - train 0.67054 | val 0.69970
  Classification -> best τ=0.520 (val F1=0.2360)
  Directional -> Accuracy: 0.5254, MCC: 0.0518, F1: 0.5172

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.73483 | val 0.74531
  Epoch 016 - train 0.70623 | val 0.75667
  Classification -> best τ=0.470 (val F1=0.1715)
  Directional -> Accuracy: 0.5000, MCC: -0.0967, F1: 0.1538

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 88). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.68422 | val 0.64111
  Epoch 020 - train 0.67788 | val 0.63138
  Epoch 030 - train 0.65458 | val 0.62580
  Classification -> best τ=0.420 (val F1=0.3952)
  Directional -> Accuracy: 0.5484, MCC: 0.1050, F1: 0.4400

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.70311 | val 0.70547
  Epoch 016 - train 0.69472 | val 0.70580
  Classification -> best τ=0.465 (val F1=0.1085)
  Directional -> Accuracy: 0.5472, MCC: 0.0760, F1: 0.2941

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.68058 | val 0.70478
  Epoch 016 - train 0.66669 | val 0.70224
  Classification -> best τ=0.490 (val F1=0.1883)
  Directional -> Accuracy: 0.5634, MCC: 0.1072, F1: 0.6804

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.67996 | val 0.78788
  Epoch 016 - train 0.67875 | val 0.78985
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.6167, MCC: 0.0000, F1: 0.7629

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.68148 | val 0.71490
  Epoch 016 - train 0.67829 | val 0.71536
  Classification -> best τ=0.485 (val F1=0.1698)
  Directional -> Accuracy: 0.6104, MCC: 0.0000, F1: 0.7581

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.67962 | val 0.74671
  Epoch 016 - train 0.68441 | val 0.74282
  Classification -> best τ=0.575 (val F1=0.2859)
  Directional -> Accuracy: 0.4697, MCC: 0.0392, F1: 0.3636

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 88). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.70306 | val 0.71663
  Epoch 016 - train 0.69363 | val 0.71425
  Classification -> best τ=0.525 (val F1=0.0181)
  Directional -> Accuracy: 0.5658, MCC: 0.1779, F1: 0.7130

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.70094 | val 0.72327
  Epoch 016 - train 0.68986 | val 0.72309
  Classification -> best τ=0.435 (val F1=0.1535)
  Directional -> Accuracy: 0.5714, MCC: -0.1170, F1: 0.7200

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 88). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 88). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 88). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.67972 | val 0.70605
  Epoch 016 - train 0.67698 | val 0.70569
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5075, MCC: 0.0000, F1: 0.6733

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.68659 | val 0.68523
  Epoch 020 - train 0.67178 | val 0.68109
  Epoch 030 - train 0.67321 | val 0.67737
  Classification -> best τ=0.600 (val F1=0.3308)
  Directional -> Accuracy: 0.5424, MCC: 0.1228, F1: 0.5263

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.67803 | val 0.69646
  Epoch 018 - train 0.67157 | val 0.70110
  Classification -> best τ=0.505 (val F1=0.1890)
  Directional -> Accuracy: 0.5373, MCC: 0.0599, F1: 0.3404

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.69833 | val 0.68500
  Epoch 020 - train 0.68293 | val 0.67696
  Epoch 030 - train 0.67975 | val 0.66987
  Classification -> best τ=0.520 (val F1=0.2471)
  Directional -> Accuracy: 0.4737, MCC: 0.1044, F1: 0.1667

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.70398 | val 0.80181
  Epoch 016 - train 0.71376 | val 0.87809
  Classification -> best τ=0.435 (val F1=0.0700)
  Directional -> Accuracy: 0.4167, MCC: 0.0000, F1: 0.5882

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.67762 | val 0.69554
  Epoch 016 - train 0.67522 | val 0.69632
  Classification -> best τ=0.560 (val F1=0.1329)
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.0000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.70115 | val 0.69588
  Epoch 016 - train 0.68234 | val 0.69620
  Classification -> best τ=0.475 (val F1=0.2174)
  Directional -> Accuracy: 0.5345, MCC: 0.0357, F1: 0.6197

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.71578 | val 0.71351
  Epoch 016 - train 0.72428 | val 0.71700
  Classification -> best τ=0.450 (val F1=0.1486)
  Directional -> Accuracy: 0.4884, MCC: -0.0283, F1: 0.5217

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.65341 | val 0.69937
  Epoch 016 - train 0.66880 | val 0.70444
  Classification -> best τ=0.540 (val F1=0.3873)
  Directional -> Accuracy: 0.4222, MCC: -0.2733, F1: 0.0000

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.68776 | val 0.74173
  Epoch 016 - train 0.70055 | val 0.75941
  Classification -> best τ=0.505 (val F1=0.0993)
  Directional -> Accuracy: 0.5778, MCC: 0.1429, F1: 0.6780

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.69442 | val 0.71998
  Epoch 016 - train 0.68437 | val 0.72208
  Classification -> best τ=0.490 (val F1=0.1333)
  Directional -> Accuracy: 0.5490, MCC: 0.1136, F1: 0.5106

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.69042 | val 0.70456
  Epoch 016 - train 0.69504 | val 0.70297
  Classification -> best τ=0.490 (val F1=0.1455)
  Directional -> Accuracy: 0.5676, MCC: 0.0000, F1: 0.7241

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 88). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.68178 | val 0.68757
  Epoch 020 - train 0.67145 | val 0.69149
  Epoch 025 - train 0.68407 | val 0.69628
  Classification -> best τ=0.520 (val F1=0.2227)
  Directional -> Accuracy: 0.4872, MCC: -0.0669, F1: 0.1667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.67960 | val 0.68206
  Epoch 019 - train 0.66967 | val 0.68691
  Classification -> best τ=0.510 (val F1=0.2835)
  Directional -> Accuracy: 0.6000, MCC: 0.1964, F1: 0.5714

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.71887 | val 0.77258
  Epoch 016 - train 0.70338 | val 0.76048
  Classification -> best τ=0.565 (val F1=0.1272)
  Directional -> Accuracy: 0.5735, MCC: 0.0000, F1: 0.7290

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.69695 | val 0.70500
  Epoch 016 - train 0.69619 | val 0.70873
  Classification -> best τ=0.510 (val F1=0.1438)
  Directional -> Accuracy: 0.5682, MCC: 0.1864, F1: 0.3448

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.69039 | val 0.68661
  Epoch 020 - train 0.67132 | val 0.68711
  Classification -> best τ=0.475 (val F1=0.3196)
  Directional -> Accuracy: 0.5172, MCC: -0.1236, F1: 0.0000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.68263 | val 0.66847
  Epoch 019 - train 0.66184 | val 0.67429
  Classification -> best τ=0.475 (val F1=0.2816)
  Directional -> Accuracy: 0.4792, MCC: 0.1152, F1: 0.3902

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 88). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 88). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 88). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 88). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.68583 | val 0.68776
  Epoch 016 - train 0.67032 | val 0.69108
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.3500, MCC: 0.0000, F1: 0.5185

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 88). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.69148 | val 0.68380
  Epoch 016 - train 0.68947 | val 0.68994
  Classification -> best τ=0.430 (val F1=0.1762)
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.7000

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 88). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 88). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.68506 | val 0.68650
  Epoch 018 - train 0.67770 | val 0.68789
  Classification -> best τ=0.465 (val F1=0.2706)
  Directional -> Accuracy: 0.5132, MCC: 0.0676, F1: 0.0976

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 88). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 88). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 88). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.69968 | val 0.68294
  Epoch 020 - train 0.68984 | val 0.68089
  Epoch 030 - train 0.67165 | val 0.67672
  Classification -> best τ=0.475 (val F1=0.3731)
  Directional -> Accuracy: 0.4167, MCC: -0.1721, F1: 0.4815

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.67810 | val 0.73807
  Epoch 016 - train 0.68088 | val 0.76434
  Classification -> best τ=0.505 (val F1=0.2000)
  Directional -> Accuracy: 0.5111, MCC: -0.0337, F1: 0.6207

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.70204 | val 0.69872
  Epoch 016 - train 0.69096 | val 0.70361
  Classification -> best τ=0.510 (val F1=0.2890)
  Directional -> Accuracy: 0.3902, MCC: -0.3334, F1: 0.1379

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.70976 | val 0.73932
  Epoch 016 - train 0.68287 | val 0.74088
  Classification -> best τ=0.445 (val F1=0.1685)
  Directional -> Accuracy: 0.5439, MCC: 0.0000, F1: 0.7045

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.71331 | val 0.64760
  Epoch 020 - train 0.69335 | val 0.64653
  Epoch 023 - train 0.70357 | val 0.64652
  Classification -> best τ=0.515 (val F1=0.3079)
  Directional -> Accuracy: 0.5345, MCC: 0.0607, F1: 0.3077

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.69030 | val 0.72114
  Epoch 016 - train 0.68655 | val 0.72471
  Classification -> best τ=0.490 (val F1=0.0727)
  Directional -> Accuracy: 0.5273, MCC: 0.0817, F1: 0.4348

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.69259 | val 0.71668
  Epoch 016 - train 0.68126 | val 0.71366
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5088, MCC: 0.0000, F1: 0.6744

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.67341 | val 0.66601
  Epoch 020 - train 0.66699 | val 0.67070
  Epoch 022 - train 0.66459 | val 0.67088

[I 2026-02-22 07:40:43,454] Trial 8 finished with value: 0.17998845705143465 and parameters: {'feature_set': 'sector_all_nlp', 'model_type': 'LSTM', 'sequence_length': 12, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 64, 'num_layers': 1, 'inter_rnn_drop': 0.0, 'dropout': 0.30000000000000004, 'batch_size': 32, 'learning_rate': 1.5064408544781393e-05, 'weight_decay': 2.8178547816306024e-07, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 15, 'max_epochs': 30, 'huber_delta': 0.5323572649535109, 'early_stopping_min_delta': 0.0031211582014660966}. Best is trial 4 with value: 0.2281230213287852.

  Classification -> best τ=0.520 (val F1=0.3945)
  Directional -> Accuracy: 0.4677, MCC: -0.0559, F1: 0.5714

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.17998845705143465
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 36
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sentiment']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.71108 | val 0.68484
  Epoch 020 - train 0.68820 | val 0.70699
  Epoch 026 - train 0.68592 | val 0.71490
  Classification -> best τ=0.615 (val F1=0.2589)
  Directional -> Accuracy: 0.5541, MCC: 0.0000, F1: 0.0000

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 112). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.67760 | val 0.72483
  Epoch 020 - train 0.66870 | val 0.72882
  Epoch 021 - train 0.66366 | val 0.72910
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.6047, MCC: 0.0000, F1: 0.7536

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for AEP (109 < 112). Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 112). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.68815 | val 0.71213
  Epoch 020 - train 0.68022 | val 0.70140
  Epoch 021 - train 0.68338 | val 0.70109
  Classification -> best τ=0.490 (val F1=0.0950)
  Directional -> Accuracy: 0.5455, MCC: 0.1201, F1: 0.4444

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.69909 | val 0.87324
  Epoch 020 - train 0.69355 | val 0.89674
  Epoch 021 - train 0.69158 | val 0.90247
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5417, MCC: 0.0000, F1: 0.7027

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.69407 | val 0.66467
  Epoch 020 - train 0.66246 | val 0.64163
  Epoch 030 - train 0.64355 | val 0.63320
  Classification -> best τ=0.535 (val F1=0.4021)
  Directional -> Accuracy: 0.6667, MCC: 0.3969, F1: 0.5789

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.73198 | val 0.78024
  Epoch 020 - train 0.72157 | val 0.78075
  Epoch 021 - train 0.71452 | val 0.78041
  Classification -> best τ=0.560 (val F1=0.2976)
  Directional -> Accuracy: 0.5909, MCC: 0.2649, F1: 0.7000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.69978 | val 0.69131
  Epoch 020 - train 0.70077 | val 0.68648
  Epoch 030 - train 0.68846 | val 0.68648
  Classification -> best τ=0.445 (val F1=0.1375)
  Directional -> Accuracy: 0.4545, MCC: 0.0612, F1: 0.5714

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 112). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 112). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.70877 | val 0.77548
  Epoch 020 - train 0.70630 | val 0.91400
  Epoch 021 - train 0.68826 | val 0.92321
  Classification -> best τ=0.495 (val F1=0.1204)
  Directional -> Accuracy: 0.4359, MCC: 0.0000, F1: 0.6071

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.68584 | val 0.74476
  Epoch 020 - train 0.69011 | val 0.76295
  Epoch 021 - train 0.67825 | val 0.76325
  Classification -> best τ=0.550 (val F1=0.2163)
  Directional -> Accuracy: 0.4565, MCC: -0.0223, F1: 0.5455

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 112). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 112). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 112). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.69131 | val 0.69974
  Epoch 020 - train 0.66677 | val 0.69868
  Epoch 021 - train 0.67333 | val 0.69869
  Classification -> best τ=0.470 (val F1=0.1411)
  Directional -> Accuracy: 0.4627, MCC: -0.0146, F1: 0.5135

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.69197 | val 0.67775
  Epoch 020 - train 0.69109 | val 0.68934
  Epoch 029 - train 0.67919 | val 0.70984
  Classification -> best τ=0.435 (val F1=0.2057)
  Directional -> Accuracy: 0.5957, MCC: 0.1860, F1: 0.2400

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.70719 | val 0.71472
  Epoch 020 - train 0.68473 | val 0.71723
  Epoch 021 - train 0.68641 | val 0.71752
  Classification -> best τ=0.510 (val F1=0.0757)
  Directional -> Accuracy: 0.4727, MCC: 0.0000, F1: 0.0000

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 112). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.67527 | val 0.67156
  Epoch 020 - train 0.66120 | val 0.68162
  Epoch 028 - train 0.66390 | val 0.68816
  Classification -> best τ=0.555 (val F1=0.3217)
  Directional -> Accuracy: 0.4375, MCC: -0.1251, F1: 0.4255

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 112). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.72118 | val 0.66011
  Epoch 020 - train 0.68858 | val 0.65414
  Epoch 026 - train 0.69595 | val 0.65334
  Classification -> best τ=0.350 (val F1=0.3229)
  Directional -> Accuracy: 0.5172, MCC: 0.0000, F1: 0.6818

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.70722 | val 0.68445
  Epoch 020 - train 0.69749 | val 0.71891
  Epoch 030 - train 0.68523 | val 0.80940
  Classification -> best τ=0.525 (val F1=0.2100)
  Directional -> Accuracy: 0.4694, MCC: 0.1303, F1: 0.6286

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.69342 | val 0.67713
  Epoch 020 - train 0.68814 | val 0.65903
  Epoch 030 - train 0.67198 | val 0.66119
  Classification -> best τ=0.360 (val F1=0.2401)
  Directional -> Accuracy: 0.5373, MCC: 0.0000, F1: 0.6990

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 112). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.68291 | val 0.89012
  Epoch 020 - train 0.67190 | val 0.99100
  Epoch 021 - train 0.69015 | val 0.99965
  Classification -> best τ=0.555 (val F1=0.1874)
  Directional -> Accuracy: 0.3929, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.67036 | val 0.75123
  Epoch 020 - train 0.66140 | val 0.77774
  Epoch 021 - train 0.66095 | val 0.77985
  Classification -> best τ=0.505 (val F1=0.0813)
  Directional -> Accuracy: 0.4247, MCC: 0.0984, F1: 0.0455

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.67637 | val 0.69144
  Epoch 020 - train 0.65904 | val 0.70303
  Epoch 025 - train 0.65890 | val 0.70831
  Classification -> best τ=0.580 (val F1=0.2345)
  Directional -> Accuracy: 0.4194, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 112). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.67206 | val 0.70080
  Epoch 020 - train 0.66740 | val 0.72631
  Epoch 025 - train 0.67140 | val 0.72832
  Classification -> best τ=0.465 (val F1=0.2309)
  Directional -> Accuracy: 0.3333, MCC: -0.3185, F1: 0.2941

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.71023 | val 0.69308
  Epoch 020 - train 0.68504 | val 0.69122
  Epoch 021 - train 0.68143 | val 0.69139
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.6000, MCC: 0.0000, F1: 0.7500

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 112). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 112). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 112). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.69374 | val 0.73075
  Epoch 020 - train 0.67493 | val 0.74363
  Epoch 021 - train 0.69518 | val 0.74415
  Classification -> best τ=0.475 (val F1=0.2132)
  Directional -> Accuracy: 0.4921, MCC: 0.0000, F1: 0.6596

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.68242 | val 0.69982
  Epoch 020 - train 0.69319 | val 0.72248
  Epoch 024 - train 0.68165 | val 0.72877
  Classification -> best τ=0.525 (val F1=0.2725)
  Directional -> Accuracy: 0.5273, MCC: 0.2085, F1: 0.3810

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.70075 | val 0.79012
  Epoch 020 - train 0.67463 | val 0.86535
  Epoch 023 - train 0.65932 | val 0.87657
  Classification -> best τ=0.440 (val F1=0.2405)
  Directional -> Accuracy: 0.4921, MCC: 0.0107, F1: 0.5897

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.67677 | val 0.69282
  Epoch 020 - train 0.66474 | val 0.66601
  Epoch 030 - train 0.64937 | val 0.65663
  Classification -> best τ=0.510 (val F1=0.4297)
  Directional -> Accuracy: 0.5660, MCC: 0.1722, F1: 0.5106

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.68808 | val 0.71183
  Epoch 020 - train 0.66879 | val 0.71737
  Epoch 021 - train 0.66063 | val 0.71694
  Classification -> best τ=0.495 (val F1=0.1809)
  Directional -> Accuracy: 0.5476, MCC: 0.0000, F1: 0.2400

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.70828 | val 0.71046
  Epoch 020 - train 0.71547 | val 0.73603
  Epoch 023 - train 0.69878 | val 0.73125
  Classification -> best τ=0.555 (val F1=0.0482)
  Directional -> Accuracy: 0.4583, MCC: -0.1952, F1: 0.5938

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.68794 | val 0.67455
  Epoch 020 - train 0.67791 | val 0.66566
  Epoch 030 - train 0.67020 | val 0.66078
  Classification -> best τ=0.410 (val F1=0.4045)
  Directional -> Accuracy: 0.5000, MCC: 0.0919, F1: 0.2286

[49/88] Processing MDT...

Processing MDT (Healthcare)...
Insufficient data for proper time series validation for MDT. Skipping...

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.68089 | val 0.70503
  Epoch 020 - train 0.68346 | val 0.72186
  Epoch 021 - train 0.69009 | val 0.72276
  Classification -> best τ=0.505 (val F1=0.2928)
  Directional -> Accuracy: 0.5250, MCC: 0.1601, F1: 0.0952

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.68403 | val 0.72731
  Epoch 020 - train 0.68467 | val 0.73753
  Epoch 021 - train 0.71080 | val 0.73713
  Classification -> best τ=0.470 (val F1=0.2482)
  Directional -> Accuracy: 0.6000, MCC: 0.2536, F1: 0.7333

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.70073 | val 0.70238
  Epoch 020 - train 0.69771 | val 0.68105
  Epoch 030 - train 0.69749 | val 0.66661
  Classification -> best τ=0.475 (val F1=0.3415)
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.68692 | val 0.67842
  Epoch 020 - train 0.67633 | val 0.67016
  Epoch 030 - train 0.66676 | val 0.66522
  Classification -> best τ=0.440 (val F1=0.2983)
  Directional -> Accuracy: 0.5286, MCC: 0.1582, F1: 0.3774

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 112). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.69127 | val 0.69839
  Epoch 020 - train 0.68583 | val 0.71396
  Epoch 024 - train 0.67953 | val 0.71801
  Classification -> best τ=0.475 (val F1=0.2576)
  Directional -> Accuracy: 0.5306, MCC: 0.1293, F1: 0.6349

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for PCG (101 < 112). Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.66327 | val 0.71818
  Epoch 020 - train 0.67021 | val 0.72206
  Epoch 021 - train 0.65424 | val 0.72234
  Classification -> best τ=0.435 (val F1=0.2149)
  Directional -> Accuracy: 0.5938, MCC: 0.1412, F1: 0.7045

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.73116 | val 0.69480
  Epoch 020 - train 0.69051 | val 0.69224
  Epoch 030 - train 0.67124 | val 0.68723
  Classification -> best τ=0.530 (val F1=0.2469)
  Directional -> Accuracy: 0.6327, MCC: 0.3114, F1: 0.7000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.69936 | val 0.66766
  Epoch 020 - train 0.66927 | val 0.66158
  Epoch 030 - train 0.66512 | val 0.66247
  Classification -> best τ=0.425 (val F1=0.2700)
  Directional -> Accuracy: 0.4815, MCC: 0.1275, F1: 0.6410

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.69045 | val 0.72411
  Epoch 020 - train 0.68450 | val 0.74233
  Epoch 021 - train 0.68301 | val 0.74305
  Classification -> best τ=0.445 (val F1=0.0433)
  Directional -> Accuracy: 0.6136, MCC: 0.0000, F1: 0.7606

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 112). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for PPL (108 < 112). Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 112). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 112). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 112). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.71885 | val 0.68367
  Epoch 020 - train 0.68303 | val 0.67808
  Epoch 030 - train 0.71155 | val 0.67455
  Classification -> best τ=0.480 (val F1=0.3237)
  Directional -> Accuracy: 0.4000, MCC: 0.1890, F1: 0.5263

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 112). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 112). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 112). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.70278 | val 0.69917
  Epoch 020 - train 0.67950 | val 0.70448
  Epoch 021 - train 0.67030 | val 0.70572
  Classification -> best τ=0.505 (val F1=0.0525)
  Directional -> Accuracy: 0.4306, MCC: -0.1394, F1: 0.4533

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 112). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 112). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 112). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 112). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.72432 | val 0.72272
  Epoch 020 - train 0.69615 | val 0.77441
  Epoch 021 - train 0.71138 | val 0.77415
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.6769

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.69536 | val 0.70956
  Epoch 020 - train 0.67816 | val 0.71889
  Epoch 021 - train 0.67217 | val 0.71920
  Classification -> best τ=0.545 (val F1=0.3671)
  Directional -> Accuracy: 0.4872, MCC: 0.0594, F1: 0.4118

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.68806 | val 0.75911
  Epoch 020 - train 0.66502 | val 0.80976
  Epoch 021 - train 0.70239 | val 0.81180
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.3778, MCC: 0.0000, F1: 0.5484

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.71227 | val 0.72292
  Epoch 020 - train 0.72126 | val 0.74050
  Epoch 021 - train 0.70939 | val 0.74196
  Classification -> best τ=0.540 (val F1=0.1295)
  Directional -> Accuracy: 0.4151, MCC: -0.2177, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.70635 | val 0.71057
  Epoch 020 - train 0.67882 | val 0.76862
  Epoch 021 - train 0.68859 | val 0.77721
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.69477 | val 0.73741
  Epoch 020 - train 0.68872 | val 0.75004
  Epoch 021 - train 0.67138 | val 0.75138
  Classification -> best τ=0.470 (val F1=0.1690)
  Directional -> Accuracy: 0.5686, MCC: 0.1413, F1: 0.5926

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.68743 | val 0.90566
  Epoch 020 - train 0.68377 | val 0.97892
  Epoch 021 - train 0.67962 | val 0.98407
  Classification -> best τ=0.550 (val F1=0.1942)
  Directional -> Accuracy: 0.4717, MCC: -0.0607, F1: 0.5172

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.69569 | val 0.70358
  Epoch 020 - train 0.69041 | val 0.69052
  Epoch 021 - train 0.67885 | val 0.68941

[I 2026-02-22 07:44:04,755] Trial 9 finished with value: 0.19410746136693147 and parameters: {'feature_set': 'sentinment', 'model_type': 'BiGRU', 'sequence_length': 36, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 64, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.6000000000000001, 'batch_size': 32, 'learning_rate': 2.281757950340286e-05, 'weight_decay': 0.00011158967248289912, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 20, 'max_epochs': 30, 'huber_delta': 1.6594813920439477, 'early_stopping_min_delta': 0.0007578468962759721}. Best is trial 4 with value: 0.2281230213287852.

  Classification -> best τ=0.475 (val F1=0.1051)
  Directional -> Accuracy: 0.5345, MCC: 0.0427, F1: 0.3721

================================================================================
Pipeline completed: 47/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (47, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.19410746136693147
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down', 'finbert_neutral']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.60835 | val 0.78944
  Epoch 011 - train 0.59422 | val 0.82572
  Classification -> best τ=0.800 (val F1=0.2510)
  Directional -> Accuracy: 0.5395, MCC: -0.1039, F1: 0.0000

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.51136 | val 0.86876
  Epoch 012 - train 0.42725 | val 1.05978
  Classification -> best τ=0.620 (val F1=0.1323)
  Directional -> Accuracy: 0.6000, MCC: 0.1802, F1: 0.6538

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.54494 | val 0.98413
  Epoch 015 - train 0.46026 | val 1.15754
  Classification -> best τ=0.690 (val F1=0.3894)
  Directional -> Accuracy: 0.6304, MCC: 0.2611, F1: 0.6383

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.62638 | val 3.07177
  Epoch 013 - train 0.56458 | val 2.91642
  Classification -> best τ=0.495 (val F1=0.1269)
  Directional -> Accuracy: 0.5405, MCC: 0.0000, F1: 0.7018

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.56239 | val 0.74216
  Epoch 012 - train 0.44843 | val 2.10983
  Classification -> best τ=0.640 (val F1=0.4414)
  Directional -> Accuracy: 0.6800, MCC: 0.3677, F1: 0.6667

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.47208 | val 1.14199
  Epoch 011 - train 0.41997 | val 1.78832
  Classification -> best τ=0.390 (val F1=0.2739)
  Directional -> Accuracy: 0.4783, MCC: -0.0169, F1: 0.6129

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.55221 | val 0.94483
  Epoch 011 - train 0.53058 | val 1.08799
  Classification -> best τ=0.340 (val F1=0.2050)
  Directional -> Accuracy: 0.4412, MCC: 0.0771, F1: 0.5682

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.42422 | val 0.72570
  Epoch 019 - train 0.21494 | val 0.96036
  Classification -> best τ=0.195 (val F1=0.5399)
  Directional -> Accuracy: 0.5238, MCC: 0.0849, F1: 0.5455

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.45841 | val 2.10350
  Epoch 011 - train 0.47989 | val 2.40807
  Classification -> best τ=0.365 (val F1=0.1456)
  Directional -> Accuracy: 0.6250, MCC: 0.2208, F1: 0.5000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.54597 | val 0.69581
  Epoch 018 - train 0.35547 | val 1.54265
  Classification -> best τ=0.430 (val F1=0.2634)
  Directional -> Accuracy: 0.4783, MCC: -0.0324, F1: 0.4545

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.61829 | val 0.69516
  Epoch 011 - train 0.57237 | val 0.70998
  Classification -> best τ=0.365 (val F1=0.2169)
  Directional -> Accuracy: 0.5102, MCC: 0.0101, F1: 0.4545

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.59288 | val 0.96078
  Epoch 012 - train 0.51981 | val 0.87993
  Classification -> best τ=0.550 (val F1=0.3307)
  Directional -> Accuracy: 0.5439, MCC: 0.1091, F1: 0.4091

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.57772 | val 1.79286
  Epoch 013 - train 0.43991 | val 1.43019
  Classification -> best τ=0.675 (val F1=0.1754)
  Directional -> Accuracy: 0.5476, MCC: 0.0535, F1: 0.3448

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.64194 | val 1.32597
  Epoch 013 - train 0.61671 | val 0.66225
  Classification -> best τ=0.425 (val F1=0.1810)
  Directional -> Accuracy: 0.6000, MCC: 0.2942, F1: 0.3684

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.53921 | val 1.38850
  Epoch 012 - train 0.43216 | val 0.89621
  Classification -> best τ=0.510 (val F1=0.2571)
  Directional -> Accuracy: 0.5490, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.62493 | val 0.73632
  Epoch 014 - train 0.51417 | val 1.04637
  Classification -> best τ=0.390 (val F1=0.3035)
  Directional -> Accuracy: 0.6812, MCC: 0.4167, F1: 0.7660

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.64009 | val 1.27939
  Epoch 011 - train 0.58133 | val 1.69813
  Classification -> best τ=0.355 (val F1=0.1336)
  Directional -> Accuracy: 0.6207, MCC: 0.0000, F1: 0.7660

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.62862 | val 1.45033
  Epoch 012 - train 0.55621 | val 2.30956
  Classification -> best τ=0.680 (val F1=0.2500)
  Directional -> Accuracy: 0.4000, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.60541 | val 0.82747
  Epoch 013 - train 0.52330 | val 0.85816
  Classification -> best τ=0.415 (val F1=0.2166)
  Directional -> Accuracy: 0.4844, MCC: 0.0694, F1: 0.3529

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.60906 | val 0.78882
  Epoch 011 - train 0.60178 | val 1.17952
  Classification -> best τ=0.175 (val F1=0.1895)
  Directional -> Accuracy: 0.5541, MCC: 0.0000, F1: 0.7130

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.54662 | val 0.95460
  Epoch 011 - train 0.52921 | val 1.16580
  Classification -> best τ=0.545 (val F1=0.3458)
  Directional -> Accuracy: 0.5745, MCC: 0.0406, F1: 0.6875

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.58183 | val 1.05422
  Epoch 011 - train 0.57056 | val 1.25705
  Classification -> best τ=0.530 (val F1=0.1350)
  Directional -> Accuracy: 0.4923, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.65820 | val 0.78324
  Epoch 012 - train 0.61960 | val 0.81090
  Classification -> best τ=0.455 (val F1=0.2484)
  Directional -> Accuracy: 0.5614, MCC: 0.1750, F1: 0.5098

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.50837 | val 3.56507
  Epoch 012 - train 0.49907 | val 3.22747
  Classification -> best τ=0.555 (val F1=0.1122)
  Directional -> Accuracy: 0.4000, MCC: -0.2044, F1: 0.3607

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.57598 | val 1.28625
  Epoch 014 - train 0.42883 | val 2.02668
  Classification -> best τ=0.490 (val F1=0.4207)
  Directional -> Accuracy: 0.5455, MCC: 0.1077, F1: 0.5283

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.37977 | val 6.28733
  Epoch 012 - train 0.34672 | val 5.12547
  Classification -> best τ=0.745 (val F1=0.4328)
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.5938

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.56628 | val 0.79224
  Epoch 015 - train 0.47004 | val 0.84681
  Classification -> best τ=0.630 (val F1=0.0786)
  Directional -> Accuracy: 0.4286, MCC: -0.0323, F1: 0.0769

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.59646 | val 1.20500
  Epoch 012 - train 0.50316 | val 1.40548
  Classification -> best τ=0.450 (val F1=0.2382)
  Directional -> Accuracy: 0.4464, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.46898 | val 2.63235
  Epoch 012 - train 0.39168 | val 3.50557
  Classification -> best τ=0.545 (val F1=0.1457)
  Directional -> Accuracy: 0.5500, MCC: 0.0231, F1: 0.7000

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.41333 | val 0.73639
  Epoch 018 - train 0.23112 | val 1.18777
  Classification -> best τ=0.485 (val F1=0.4879)
  Directional -> Accuracy: 0.4048, MCC: -0.1992, F1: 0.5283

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.51716 | val 1.21622
  Epoch 015 - train 0.39014 | val 2.80271
  Classification -> best τ=0.745 (val F1=0.3067)
  Directional -> Accuracy: 0.4762, MCC: 0.1419, F1: 0.0833

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.43116 | val 1.10033
  Epoch 011 - train 0.39576 | val 0.88857
  Classification -> best τ=0.705 (val F1=0.1263)
  Directional -> Accuracy: 0.4898, MCC: 0.1358, F1: 0.0741

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.61672 | val 0.77674
  Epoch 011 - train 0.57782 | val 0.82718
  Classification -> best τ=0.490 (val F1=0.2267)
  Directional -> Accuracy: 0.4861, MCC: 0.1865, F1: 0.1395

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.52021 | val 1.36060
  Epoch 011 - train 0.46799 | val 1.49169
  Classification -> best τ=0.670 (val F1=0.3227)
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.50966 | val 1.19641
  Epoch 011 - train 0.49454 | val 1.25431
  Classification -> best τ=0.380 (val F1=0.3342)
  Directional -> Accuracy: 0.6212, MCC: 0.1919, F1: 0.7312

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.47551 | val 0.80740
  Epoch 017 - train 0.27851 | val 0.81239
  Classification -> best τ=0.240 (val F1=0.4100)
  Directional -> Accuracy: 0.5714, MCC: 0.1445, F1: 0.6786

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.55213 | val 0.74969
  Epoch 012 - train 0.45531 | val 0.82052
  Classification -> best τ=0.415 (val F1=0.2305)
  Directional -> Accuracy: 0.4464, MCC: -0.1100, F1: 0.4151

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.52186 | val 1.76755
  Epoch 019 - train 0.27040 | val 1.69950
  Classification -> best τ=0.480 (val F1=0.5001)
  Directional -> Accuracy: 0.6522, MCC: 0.2197, F1: 0.7576

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.44994 | val 1.02285
  Epoch 012 - train 0.34391 | val 1.12810
  Classification -> best τ=0.340 (val F1=0.3656)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.56550 | val 1.27660
  Epoch 011 - train 0.50974 | val 1.00124
  Classification -> best τ=0.265 (val F1=0.2700)
  Directional -> Accuracy: 0.4865, MCC: 0.0000, F1: 0.6545

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.48860 | val 0.72783
  Epoch 015 - train 0.40474 | val 1.04201
  Classification -> best τ=0.545 (val F1=0.4080)
  Directional -> Accuracy: 0.4667, MCC: -0.0653, F1: 0.4545

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.50030 | val 2.03366
  Epoch 011 - train 0.40410 | val 1.38760
  Classification -> best τ=0.595 (val F1=0.4523)
  Directional -> Accuracy: 0.4762, MCC: -0.0278, F1: 0.4762

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.44059 | val 1.29809
  Epoch 011 - train 0.42767 | val 1.31007
  Classification -> best τ=0.565 (val F1=0.1702)
  Directional -> Accuracy: 0.6042, MCC: -0.1130, F1: 0.0000

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.56193 | val 1.73827
  Epoch 011 - train 0.53620 | val 1.57452
  Classification -> best τ=0.400 (val F1=0.1154)
  Directional -> Accuracy: 0.4909, MCC: 0.1773, F1: 0.1250

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.49771 | val 3.01095
  Epoch 011 - train 0.46882 | val 3.18774
  Classification -> best τ=0.815 (val F1=0.1152)
  Directional -> Accuracy: 0.5179, MCC: 0.0226, F1: 0.3721

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.63633 | val 0.72537
  Epoch 011 - train 0.62304 | val 0.81109
  Classification -> best τ=0.695 (val F1=0.2407)
  Directional -> Accuracy: 0.6038, MCC: 0.2103, F1: 0.5882

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.51123 | val 2.19094
  Epoch 011 - train 0.48901 | val 2.39275
  Classification -> best τ=0.695 (val F1=0.1407)
  Directional -> Accuracy: 0.4909, MCC: -0.1249, F1: 0.6500

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.55977 | val 0.66439

[I 2026-02-22 07:48:47,736] Trial 10 finished with value: 0.2640135946461086 and parameters: {'feature_set': 'finbert', 'model_type': 'BiGRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.4, 'dropout': 0.0, 'batch_size': 16, 'learning_rate': 0.008483043580770245, 'weight_decay': 1.3857135358053015e-05, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 0.8278398983133108, 'early_stopping_min_delta': 0.00915688842009988}. Best is trial 10 with value: 0.2640135946461086.

  Epoch 016 - train 0.53232 | val 0.74841
  Classification -> best τ=0.575 (val F1=0.2691)
  Directional -> Accuracy: 0.5167, MCC: 0.0111, F1: 0.1714

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2640135946461086
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down', 'finbert_neutral']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.63303 | val 0.64397
  Epoch 020 - train 0.52626 | val 0.77269
  Classification -> best τ=0.630 (val F1=0.2919)
  Directional -> Accuracy: 0.5263, MCC: -0.0371, F1: 0.1818

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.61322 | val 0.70147
  Epoch 012 - train 0.45789 | val 0.69320
  Classification -> best τ=0.395 (val F1=0.2285)
  Directional -> Accuracy: 0.5556, MCC: -0.1289, F1: 0.7143

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.56502 | val 0.94288
  Epoch 019 - train 0.33890 | val 0.94224
  Classification -> best τ=0.660 (val F1=0.4178)
  Directional -> Accuracy: 0.4783, MCC: -0.0259, F1: 0.3333

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.61561 | val 1.54514
  Epoch 014 - train 0.47436 | val 2.77554
  Classification -> best τ=0.720 (val F1=0.1269)
  Directional -> Accuracy: 0.5405, MCC: 0.0000, F1: 0.7018

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.46443 | val 0.96722
  Epoch 011 - train 0.43458 | val 1.09445
  Classification -> best τ=0.480 (val F1=0.4602)
  Directional -> Accuracy: 0.6800, MCC: 0.3622, F1: 0.6800

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.44883 | val 0.93959
  Epoch 011 - train 0.42422 | val 0.94439
  Classification -> best τ=0.550 (val F1=0.2701)
  Directional -> Accuracy: 0.5652, MCC: 0.2227, F1: 0.1667

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.59717 | val 1.05843
  Epoch 015 - train 0.45935 | val 1.63156
  Classification -> best τ=0.745 (val F1=0.1230)
  Directional -> Accuracy: 0.5735, MCC: -0.0751, F1: 0.0645

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.32928 | val 4.62634
  Epoch 011 - train 0.27059 | val 5.64976
  Classification -> best τ=0.290 (val F1=0.2075)
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.41125 | val 2.61595
  Epoch 011 - train 0.36367 | val 2.76314
  Classification -> best τ=0.435 (val F1=0.0377)
  Directional -> Accuracy: 0.5000, MCC: 0.0053, F1: 0.4783

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.54301 | val 0.80938
  Epoch 014 - train 0.42858 | val 0.82557
  Classification -> best τ=0.485 (val F1=0.2293)
  Directional -> Accuracy: 0.5217, MCC: 0.1038, F1: 0.5600

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.59932 | val 0.71957
  Epoch 016 - train 0.49134 | val 0.68208
  Classification -> best τ=0.445 (val F1=0.2997)
  Directional -> Accuracy: 0.5918, MCC: 0.1804, F1: 0.2308

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.61520 | val 1.10798
  Epoch 013 - train 0.58231 | val 1.17710
  Classification -> best τ=0.615 (val F1=0.3426)
  Directional -> Accuracy: 0.6316, MCC: 0.2894, F1: 0.7042

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.50383 | val 1.19768
  Epoch 011 - train 0.51443 | val 1.22248
  Classification -> best τ=0.230 (val F1=0.2850)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.6230

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.65844 | val 0.65529
  Epoch 012 - train 0.58366 | val 0.72054
  Classification -> best τ=0.325 (val F1=0.3196)
  Directional -> Accuracy: 0.5667, MCC: 0.1361, F1: 0.6061

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.53003 | val 1.77141
  Epoch 011 - train 0.46981 | val 1.98751
  Classification -> best τ=0.470 (val F1=0.2571)
  Directional -> Accuracy: 0.5490, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.60210 | val 0.78808
  Epoch 011 - train 0.56533 | val 0.95354
  Classification -> best τ=0.575 (val F1=0.3024)
  Directional -> Accuracy: 0.5652, MCC: 0.1258, F1: 0.5946

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.62490 | val 0.99975
  Epoch 012 - train 0.56822 | val 0.99334
  Classification -> best τ=0.505 (val F1=0.1842)
  Directional -> Accuracy: 0.3966, MCC: 0.1035, F1: 0.0541

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.60730 | val 0.92548
  Epoch 012 - train 0.58220 | val 1.44210
  Classification -> best τ=0.380 (val F1=0.1769)
  Directional -> Accuracy: 0.6000, MCC: 0.0000, F1: 0.7500

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.64281 | val 1.38465
  Epoch 014 - train 0.47289 | val 1.23633
  Classification -> best τ=0.730 (val F1=0.2234)
  Directional -> Accuracy: 0.4219, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.54453 | val 1.41055
  Epoch 011 - train 0.52551 | val 1.15364
  Classification -> best τ=0.350 (val F1=0.2090)
  Directional -> Accuracy: 0.5541, MCC: 0.0000, F1: 0.7130

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.58456 | val 1.35159
  Epoch 012 - train 0.50259 | val 2.04060
  Classification -> best τ=0.490 (val F1=0.3262)
  Directional -> Accuracy: 0.5532, MCC: 0.0021, F1: 0.6667

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.60385 | val 2.63992
  Epoch 011 - train 0.57923 | val 2.84039
  Classification -> best τ=0.280 (val F1=0.2037)
  Directional -> Accuracy: 0.4462, MCC: -0.2077, F1: 0.6087

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.62181 | val 0.78031
  Epoch 011 - train 0.58355 | val 0.78997
  Classification -> best τ=0.670 (val F1=0.3191)
  Directional -> Accuracy: 0.4561, MCC: -0.0051, F1: 0.2439

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.59927 | val 0.92922
  Epoch 011 - train 0.64883 | val 0.75627
  Classification -> best τ=0.410 (val F1=0.1874)
  Directional -> Accuracy: 0.5231, MCC: 0.0484, F1: 0.5231

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.48970 | val 2.51530
  Epoch 011 - train 0.40273 | val 2.46059
  Classification -> best τ=0.290 (val F1=0.3436)
  Directional -> Accuracy: 0.5273, MCC: 0.0000, F1: 0.6486

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.44618 | val 6.61107
  Epoch 011 - train 0.44088 | val 6.74621
  Classification -> best τ=0.835 (val F1=0.1890)
  Directional -> Accuracy: 0.5778, MCC: 0.0000, F1: 0.0000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.57102 | val 2.32457
  Epoch 012 - train 0.48889 | val 2.07414
  Classification -> best τ=0.445 (val F1=0.1803)
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.7273

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.51316 | val 1.76652
  Epoch 012 - train 0.47022 | val 2.02534
  Classification -> best τ=0.260 (val F1=0.1986)
  Directional -> Accuracy: 0.5000, MCC: 0.0565, F1: 0.3913

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.47016 | val 1.02264
  Epoch 011 - train 0.44873 | val 1.28078
  Classification -> best τ=0.610 (val F1=0.1448)
  Directional -> Accuracy: 0.5750, MCC: 0.1297, F1: 0.6383

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.47797 | val 1.45059
  Epoch 012 - train 0.44254 | val 0.78025
  Classification -> best τ=0.645 (val F1=0.3501)
  Directional -> Accuracy: 0.5000, MCC: 0.0426, F1: 0.6182

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.61498 | val 0.92647
  Epoch 011 - train 0.58014 | val 1.10328
  Classification -> best τ=0.580 (val F1=0.1195)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.63271 | val 0.89625
  Epoch 011 - train 0.55520 | val 0.96389
  Classification -> best τ=0.325 (val F1=0.2686)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.61382 | val 0.66541
  Epoch 013 - train 0.56643 | val 0.65714
  Classification -> best τ=0.260 (val F1=0.3815)
  Directional -> Accuracy: 0.5417, MCC: 0.1155, F1: 0.5075

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.48011 | val 1.81074
  Epoch 011 - train 0.43149 | val 1.72231
  Classification -> best τ=0.600 (val F1=0.3227)
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.54495 | val 1.39723
  Epoch 015 - train 0.42852 | val 1.18837
  Classification -> best τ=0.905 (val F1=0.2249)
  Directional -> Accuracy: 0.4242, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.42592 | val 1.32171
  Epoch 014 - train 0.33879 | val 0.96971
  Classification -> best τ=0.470 (val F1=0.4099)
  Directional -> Accuracy: 0.6905, MCC: 0.3814, F1: 0.6977

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.55531 | val 1.63916
  Epoch 012 - train 0.48077 | val 1.39175
  Classification -> best τ=0.215 (val F1=0.2114)
  Directional -> Accuracy: 0.4464, MCC: -0.0891, F1: 0.5079

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.56329 | val 0.81948
  Epoch 011 - train 0.52101 | val 0.93057
  Classification -> best τ=0.550 (val F1=0.2659)
  Directional -> Accuracy: 0.4348, MCC: 0.0460, F1: 0.2353

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.42398 | val 1.18369
  Epoch 013 - train 0.29214 | val 0.91039
  Classification -> best τ=0.440 (val F1=0.3859)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.53767 | val 0.98432
  Epoch 012 - train 0.50112 | val 1.35720
  Classification -> best τ=0.380 (val F1=0.3006)
  Directional -> Accuracy: 0.5270, MCC: 0.2001, F1: 0.6729

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.59122 | val 0.66816
  Epoch 020 - train 0.56234 | val 0.84805
  Epoch 028 - train 0.26896 | val 1.26933
  Classification -> best τ=0.605 (val F1=0.4989)
  Directional -> Accuracy: 0.5333, MCC: 0.0764, F1: 0.4615

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.46160 | val 1.22334
  Epoch 012 - train 0.32047 | val 1.14813
  Classification -> best τ=0.500 (val F1=0.4082)
  Directional -> Accuracy: 0.5952, MCC: 0.1407, F1: 0.6909

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.46497 | val 1.81074
  Epoch 011 - train 0.49304 | val 1.31139
  Classification -> best τ=0.565 (val F1=0.0530)
  Directional -> Accuracy: 0.4583, MCC: 0.0000, F1: 0.4800

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.57626 | val 0.69165
  Epoch 011 - train 0.57921 | val 0.72885
  Classification -> best τ=0.535 (val F1=0.0684)
  Directional -> Accuracy: 0.4182, MCC: -0.3051, F1: 0.5789

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.59102 | val 2.34218
  Epoch 011 - train 0.54170 | val 2.61248
  Classification -> best τ=0.735 (val F1=0.1502)
  Directional -> Accuracy: 0.5179, MCC: 0.0000, F1: 0.0000

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.64166 | val 0.77133
  Epoch 013 - train 0.61650 | val 0.76232
  Classification -> best τ=0.480 (val F1=0.0341)
  Directional -> Accuracy: 0.5472, MCC: 0.1259, F1: 0.6757

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.54252 | val 2.21701
  Epoch 011 - train 0.47990 | val 2.37450
  Classification -> best τ=0.660 (val F1=0.2132)
  Directional -> Accuracy: 0.4727, MCC: -0.0892, F1: 0.5797

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.61009 | val 0.69828

[I 2026-02-22 07:53:32,486] Trial 11 finished with value: 0.2503130643674238 and parameters: {'feature_set': 'finbert', 'model_type': 'BiGRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.4, 'dropout': 0.0, 'batch_size': 16, 'learning_rate': 0.007864101567182506, 'weight_decay': 1.537638335011722e-05, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 0.9065944434547866, 'early_stopping_min_delta': 0.009634536606455251}. Best is trial 10 with value: 0.2640135946461086.

  Epoch 012 - train 0.56186 | val 0.73068
  Classification -> best τ=0.640 (val F1=0.2623)
  Directional -> Accuracy: 0.5000, MCC: -0.0689, F1: 0.0625

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2503130643674238
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down', 'finbert_neutral']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.64897 | val 0.74178
  Epoch 015 - train 0.56534 | val 0.87970
  Classification -> best τ=0.910 (val F1=0.2510)
  Directional -> Accuracy: 0.5395, MCC: -0.0120, F1: 0.1463

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.53731 | val 1.33356
  Epoch 016 - train 0.37551 | val 0.82683
  Classification -> best τ=0.575 (val F1=0.1764)
  Directional -> Accuracy: 0.5556, MCC: 0.3353, F1: 0.3750

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.49339 | val 0.78717
  Epoch 011 - train 0.49592 | val 0.75060
  Classification -> best τ=0.360 (val F1=0.3678)
  Directional -> Accuracy: 0.5435, MCC: 0.1557, F1: 0.6957

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.57842 | val 2.03145
  Epoch 015 - train 0.50228 | val 1.34922
  Classification -> best τ=0.320 (val F1=0.0788)
  Directional -> Accuracy: 0.5405, MCC: 0.0000, F1: 0.7018

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.47275 | val 0.90218
  Epoch 012 - train 0.40705 | val 1.53118
  Classification -> best τ=0.435 (val F1=0.4556)
  Directional -> Accuracy: 0.7000, MCC: 0.4543, F1: 0.6341

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.48687 | val 0.88670
  Epoch 011 - train 0.46051 | val 0.81839
  Classification -> best τ=0.505 (val F1=0.2030)
  Directional -> Accuracy: 0.5435, MCC: 0.0961, F1: 0.5714

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.56357 | val 1.16379
  Epoch 015 - train 0.44311 | val 1.44526
  Classification -> best τ=0.375 (val F1=0.2481)
  Directional -> Accuracy: 0.5147, MCC: 0.2180, F1: 0.6024

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.38473 | val 1.23849
  Epoch 012 - train 0.27065 | val 1.24130
  Classification -> best τ=0.345 (val F1=0.1795)
  Directional -> Accuracy: 0.4762, MCC: -0.0694, F1: 0.3889

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.48180 | val 1.70427
  Epoch 011 - train 0.44819 | val 2.07762
  Classification -> best τ=0.655 (val F1=0.2988)
  Directional -> Accuracy: 0.7083, MCC: 0.4006, F1: 0.6316

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.60071 | val 0.98787
  Epoch 011 - train 0.57606 | val 1.41007
  Classification -> best τ=0.435 (val F1=0.2293)
  Directional -> Accuracy: 0.4203, MCC: 0.0000, F1: 0.5918

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.59684 | val 0.68602
  Epoch 013 - train 0.56218 | val 0.71557
  Classification -> best τ=0.445 (val F1=0.1199)
  Directional -> Accuracy: 0.4082, MCC: -0.1635, F1: 0.5538

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.68482 | val 0.72983
  Epoch 012 - train 0.60028 | val 0.89179
  Classification -> best τ=0.655 (val F1=0.2579)
  Directional -> Accuracy: 0.5439, MCC: 0.0874, F1: 0.6176

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.52520 | val 1.04075
  Epoch 011 - train 0.46737 | val 1.08271
  Classification -> best τ=0.630 (val F1=0.2933)
  Directional -> Accuracy: 0.5952, MCC: 0.1736, F1: 0.5143

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.62273 | val 1.06395
  Epoch 011 - train 0.58904 | val 1.16260
  Classification -> best τ=0.380 (val F1=0.2965)
  Directional -> Accuracy: 0.5500, MCC: 0.1155, F1: 0.6400

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.57457 | val 0.72644
  Epoch 012 - train 0.52281 | val 0.77054
  Classification -> best τ=0.580 (val F1=0.2571)
  Directional -> Accuracy: 0.5490, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.60893 | val 0.74524
  Epoch 014 - train 0.47040 | val 1.40647
  Classification -> best τ=0.070 (val F1=0.3094)
  Directional -> Accuracy: 0.5362, MCC: 0.0000, F1: 0.6981

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.65406 | val 0.87832
  Epoch 011 - train 0.60930 | val 0.94291
  Classification -> best τ=0.410 (val F1=0.1878)
  Directional -> Accuracy: 0.5862, MCC: -0.1477, F1: 0.7391

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.59865 | val 1.07873
  Epoch 011 - train 0.58065 | val 1.34963
  Classification -> best τ=0.420 (val F1=0.1612)
  Directional -> Accuracy: 0.5867, MCC: 0.1062, F1: 0.6804

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.62346 | val 0.80056
  Epoch 016 - train 0.54026 | val 0.73453
  Classification -> best τ=0.455 (val F1=0.2946)
  Directional -> Accuracy: 0.5000, MCC: -0.0839, F1: 0.6190

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.55794 | val 0.90892
  Epoch 011 - train 0.54026 | val 1.08808
  Classification -> best τ=0.580 (val F1=0.2377)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.61375 | val 1.07671
  Epoch 017 - train 0.46333 | val 1.76818
  Classification -> best τ=0.490 (val F1=0.3262)
  Directional -> Accuracy: 0.5745, MCC: 0.0406, F1: 0.6875

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.59434 | val 1.27511
  Epoch 011 - train 0.57394 | val 1.22969
  Classification -> best τ=0.265 (val F1=0.1708)
  Directional -> Accuracy: 0.4000, MCC: -0.1994, F1: 0.3810

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.57250 | val 1.51029
  Epoch 011 - train 0.54923 | val 1.48674
  Classification -> best τ=0.635 (val F1=0.2963)
  Directional -> Accuracy: 0.4912, MCC: 0.0739, F1: 0.3256

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.59759 | val 0.78853
  Epoch 012 - train 0.56149 | val 0.77898
  Classification -> best τ=0.545 (val F1=0.2073)
  Directional -> Accuracy: 0.5538, MCC: 0.1327, F1: 0.6133

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.49007 | val 1.48831
  Epoch 011 - train 0.43358 | val 1.59620
  Classification -> best τ=0.645 (val F1=0.3974)
  Directional -> Accuracy: 0.4909, MCC: 0.0659, F1: 0.2632

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.37745 | val 6.13099
  Epoch 011 - train 0.32006 | val 6.25386
  Classification -> best τ=0.785 (val F1=0.0385)
  Directional -> Accuracy: 0.5778, MCC: 0.3149, F1: 0.6545

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.55428 | val 0.92608
  Epoch 016 - train 0.56446 | val 0.77115
  Classification -> best τ=0.505 (val F1=0.2107)
  Directional -> Accuracy: 0.5000, MCC: -0.1005, F1: 0.6316

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.53240 | val 1.42967
  Epoch 011 - train 0.51187 | val 1.46412
  Classification -> best τ=0.510 (val F1=0.2287)
  Directional -> Accuracy: 0.3750, MCC: -0.2303, F1: 0.3137

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.42707 | val 3.06333
  Epoch 011 - train 0.36786 | val 3.25390
  Classification -> best τ=0.675 (val F1=0.2774)
  Directional -> Accuracy: 0.5000, MCC: 0.0205, F1: 0.4737

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.55047 | val 1.23009
  Epoch 011 - train 0.53448 | val 0.96016
  Classification -> best τ=0.525 (val F1=0.2764)
  Directional -> Accuracy: 0.5000, MCC: 0.0196, F1: 0.5714

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.57964 | val 0.71238
  Epoch 020 - train 0.35536 | val 1.13204
  Epoch 021 - train 0.31815 | val 0.84221
  Classification -> best τ=0.515 (val F1=0.5622)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.48496 | val 1.04765
  Epoch 011 - train 0.46070 | val 1.04813
  Classification -> best τ=0.350 (val F1=0.2509)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.66123 | val 0.67335
  Epoch 020 - train 0.47702 | val 0.92541
  Classification -> best τ=0.760 (val F1=0.2637)
  Directional -> Accuracy: 0.4861, MCC: 0.1865, F1: 0.1395

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.53791 | val 1.26516
  Epoch 011 - train 0.47303 | val 1.42027
  Classification -> best τ=0.665 (val F1=0.2151)
  Directional -> Accuracy: 0.5814, MCC: 0.1623, F1: 0.5714

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.52995 | val 1.17013
  Epoch 011 - train 0.47769 | val 1.28149
  Classification -> best τ=0.715 (val F1=0.2329)
  Directional -> Accuracy: 0.5758, MCC: 0.0000, F1: 0.7308

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.40883 | val 0.68473
  Epoch 012 - train 0.24588 | val 0.78249
  Classification -> best τ=0.505 (val F1=0.3321)
  Directional -> Accuracy: 0.6190, MCC: 0.3091, F1: 0.5000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.51067 | val 1.35177
  Epoch 012 - train 0.42306 | val 1.13337
  Classification -> best τ=0.380 (val F1=0.1951)
  Directional -> Accuracy: 0.5179, MCC: 0.0384, F1: 0.5091

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.44289 | val 0.72079
  Epoch 011 - train 0.40650 | val 0.72749
  Classification -> best τ=0.380 (val F1=0.3985)
  Directional -> Accuracy: 0.6087, MCC: 0.0475, F1: 0.7500

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.51637 | val 1.10426
  Epoch 012 - train 0.45779 | val 1.21052
  Classification -> best τ=0.705 (val F1=0.3887)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.56540 | val 1.36374
  Epoch 020 - train 0.49180 | val 1.54216
  Epoch 025 - train 0.35252 | val 1.51843
  Classification -> best τ=0.615 (val F1=0.4569)
  Directional -> Accuracy: 0.5000, MCC: 0.0230, F1: 0.6186

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.54900 | val 0.73788
  Epoch 011 - train 0.49530 | val 0.73940
  Classification -> best τ=0.490 (val F1=0.3371)
  Directional -> Accuracy: 0.4444, MCC: -0.1110, F1: 0.3243

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.42341 | val 1.47971
  Epoch 011 - train 0.41348 | val 1.52316
  Classification -> best τ=0.445 (val F1=0.3015)
  Directional -> Accuracy: 0.5000, MCC: -0.1698, F1: 0.6557

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.45710 | val 1.39238
  Epoch 011 - train 0.40404 | val 1.26395
  Classification -> best τ=0.740 (val F1=0.4092)
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.0000

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.58362 | val 1.79637
  Epoch 014 - train 0.53823 | val 1.43546
  Classification -> best τ=0.480 (val F1=0.2833)
  Directional -> Accuracy: 0.3818, MCC: -0.3360, F1: 0.5278

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.48944 | val 3.21408
  Epoch 011 - train 0.49756 | val 3.11815
  Classification -> best τ=0.675 (val F1=0.3233)
  Directional -> Accuracy: 0.5357, MCC: 0.1073, F1: 0.6286

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.66044 | val 1.01978
  Epoch 012 - train 0.56757 | val 1.04626
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5094, MCC: 0.0000, F1: 0.6750

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.57036 | val 2.54255
  Epoch 011 - train 0.49877 | val 2.89341
  Classification -> best τ=0.770 (val F1=0.1383)
  Directional -> Accuracy: 0.5455, MCC: 0.0864, F1: 0.5763

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.64862 | val 0.68571

[I 2026-02-22 07:58:24,460] Trial 12 finished with value: 0.26451244235752075 and parameters: {'feature_set': 'finbert', 'model_type': 'BiGRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.4, 'dropout': 0.0, 'batch_size': 16, 'learning_rate': 0.005050920174004397, 'weight_decay': 3.402846981620689e-05, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 0.8834930812253997, 'early_stopping_min_delta': 0.009874350092912095}. Best is trial 12 with value: 0.26451244235752075.

  Epoch 011 - train 0.63476 | val 0.70254
  Classification -> best τ=0.450 (val F1=0.2744)
  Directional -> Accuracy: 0.5333, MCC: 0.1135, F1: 0.6410

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.26451244235752075
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 30
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down', 'finbert_neutral']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.63129 | val 0.73051
  Epoch 011 - train 0.57762 | val 0.73937
  Classification -> best τ=0.485 (val F1=0.1718)
  Directional -> Accuracy: 0.4933, MCC: -0.1411, F1: 0.0952

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 106). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.51831 | val 0.73825
  Epoch 018 - train 0.21625 | val 1.37106
  Classification -> best τ=0.475 (val F1=0.3103)
  Directional -> Accuracy: 0.4545, MCC: -0.0437, F1: 0.4286

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 106). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.43550 | val 1.11813
  Epoch 011 - train 0.35416 | val 1.64981
  Classification -> best τ=0.760 (val F1=0.3568)
  Directional -> Accuracy: 0.4889, MCC: 0.0714, F1: 0.1481

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.58944 | val 2.18018
  Epoch 011 - train 0.53873 | val 3.95779
  Classification -> best τ=0.425 (val F1=0.0315)
  Directional -> Accuracy: 0.4247, MCC: -0.1441, F1: 0.1600

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.47950 | val 0.81258
  Epoch 011 - train 0.41163 | val 0.83685
  Classification -> best τ=0.520 (val F1=0.4967)
  Directional -> Accuracy: 0.6122, MCC: 0.2582, F1: 0.5128

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.43947 | val 1.97885
  Epoch 012 - train 0.27907 | val 2.92069
  Classification -> best τ=0.515 (val F1=0.3188)
  Directional -> Accuracy: 0.6000, MCC: 0.1996, F1: 0.5500

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.57396 | val 1.03462
  Epoch 012 - train 0.45979 | val 1.36676
  Classification -> best τ=0.445 (val F1=0.1866)
  Directional -> Accuracy: 0.4328, MCC: 0.0445, F1: 0.5682

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 106). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 106). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.36613 | val 3.10890
  Epoch 012 - train 0.23921 | val 3.67679
  Classification -> best τ=0.305 (val F1=0.3637)
  Directional -> Accuracy: 0.4390, MCC: -0.0278, F1: 0.5965

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.41681 | val 2.68130
  Epoch 011 - train 0.39637 | val 3.44300
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4468, MCC: 0.0000, F1: 0.6176

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 106). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 106). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 106). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.50185 | val 0.82494
  Epoch 018 - train 0.42978 | val 0.72665
  Classification -> best τ=0.705 (val F1=0.2357)
  Directional -> Accuracy: 0.5441, MCC: 0.0640, F1: 0.4561

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.53054 | val 0.76185
  Epoch 012 - train 0.65893 | val 1.22122
  Classification -> best τ=0.445 (val F1=0.2994)
  Directional -> Accuracy: 0.5833, MCC: 0.2267, F1: 0.1667

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.51842 | val 1.04487
  Epoch 012 - train 0.48984 | val 1.52580
  Classification -> best τ=0.380 (val F1=0.2556)
  Directional -> Accuracy: 0.5179, MCC: 0.0000, F1: 0.6824

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 106). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.43480 | val 7.60470
  Epoch 011 - train 0.37637 | val 8.77394
  Classification -> best τ=0.330 (val F1=0.2112)
  Directional -> Accuracy: 0.4898, MCC: -0.0379, F1: 0.2857

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 106). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.58960 | val 0.85841
  Epoch 013 - train 0.41589 | val 0.72734
  Classification -> best τ=0.340 (val F1=0.1082)
  Directional -> Accuracy: 0.5593, MCC: 0.1231, F1: 0.6389

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.56156 | val 1.95339
  Epoch 012 - train 0.41801 | val 2.82737
  Classification -> best τ=0.535 (val F1=0.2938)
  Directional -> Accuracy: 0.5800, MCC: 0.1068, F1: 0.2759

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.62549 | val 0.94259
  Epoch 012 - train 0.58720 | val 0.99285
  Classification -> best τ=0.400 (val F1=0.2526)
  Directional -> Accuracy: 0.5147, MCC: -0.1152, F1: 0.6796

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 106). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.64899 | val 0.84838
  Epoch 012 - train 0.57005 | val 1.23275
  Classification -> best τ=0.720 (val F1=0.1890)
  Directional -> Accuracy: 0.3860, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.62831 | val 1.08083
  Epoch 013 - train 0.52401 | val 1.27500
  Classification -> best τ=0.510 (val F1=0.1079)
  Directional -> Accuracy: 0.4054, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.55570 | val 0.82923
  Epoch 011 - train 0.50911 | val 0.88538
  Classification -> best τ=0.270 (val F1=0.3339)
  Directional -> Accuracy: 0.5873, MCC: 0.1486, F1: 0.6486

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 106). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.57803 | val 0.79117
  Epoch 013 - train 0.42889 | val 1.02889
  Classification -> best τ=0.440 (val F1=0.2441)
  Directional -> Accuracy: 0.4521, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.54503 | val 1.54474
  Epoch 012 - train 0.47214 | val 1.92782
  Classification -> best τ=0.550 (val F1=0.2759)
  Directional -> Accuracy: 0.6087, MCC: 0.0475, F1: 0.7500

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 106). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 106). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 106). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.59787 | val 3.51996
  Epoch 011 - train 0.55697 | val 3.83045
  Classification -> best τ=0.450 (val F1=0.2149)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6098

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.51553 | val 3.13701
  Epoch 011 - train 0.44333 | val 3.24832
  Classification -> best τ=0.685 (val F1=0.2798)
  Directional -> Accuracy: 0.5893, MCC: 0.1857, F1: 0.6102

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.50322 | val 1.50007
  Epoch 011 - train 0.42433 | val 2.35980
  Classification -> best τ=0.600 (val F1=0.1912)
  Directional -> Accuracy: 0.5312, MCC: 0.0000, F1: 0.0000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.51629 | val 1.04792
  Epoch 013 - train 0.37603 | val 1.27399
  Classification -> best τ=0.505 (val F1=0.4079)
  Directional -> Accuracy: 0.5185, MCC: 0.0783, F1: 0.4091

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.32820 | val 0.88819
  Epoch 011 - train 0.19990 | val 1.23728
  Classification -> best τ=0.540 (val F1=0.3118)
  Directional -> Accuracy: 0.5349, MCC: 0.2465, F1: 0.6296

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.50951 | val 1.06107
  Epoch 012 - train 0.38091 | val 1.02717
  Classification -> best τ=0.575 (val F1=0.0967)
  Directional -> Accuracy: 0.5510, MCC: 0.0416, F1: 0.6452

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.55471 | val 1.10065
  Epoch 011 - train 0.53435 | val 1.24176
  Classification -> best τ=0.535 (val F1=0.1884)
  Directional -> Accuracy: 0.5273, MCC: 0.2557, F1: 0.2353

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.42274 | val 0.68876
  Epoch 012 - train 0.38151 | val 0.77049
  Classification -> best τ=0.540 (val F1=0.2227)
  Directional -> Accuracy: 0.5000, MCC: 0.1362, F1: 0.2400

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.38138 | val 0.89983
  Epoch 012 - train 0.35449 | val 2.62351
  Classification -> best τ=0.715 (val F1=0.2193)
  Directional -> Accuracy: 0.4878, MCC: -0.0290, F1: 0.4324

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.46378 | val 1.10590
  Epoch 011 - train 0.38108 | val 1.27182
  Classification -> best τ=0.670 (val F1=0.1336)
  Directional -> Accuracy: 0.4146, MCC: -0.1289, F1: 0.0769

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.43966 | val 1.33418
  Epoch 011 - train 0.35016 | val 1.33133
  Classification -> best τ=0.735 (val F1=0.2382)
  Directional -> Accuracy: 0.5208, MCC: 0.0087, F1: 0.6761

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.52713 | val 1.22579
  Epoch 011 - train 0.47869 | val 1.35617
  Classification -> best τ=0.655 (val F1=0.1623)
  Directional -> Accuracy: 0.4366, MCC: -0.0455, F1: 0.1667

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 106). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.60525 | val 1.33895
  Epoch 013 - train 0.41690 | val 1.41440
  Classification -> best τ=0.430 (val F1=0.2675)
  Directional -> Accuracy: 0.4762, MCC: -0.0302, F1: 0.5600

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for PCG (101 < 106). Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.57627 | val 1.06071
  Epoch 013 - train 0.43153 | val 1.43537
  Classification -> best τ=0.120 (val F1=0.3218)
  Directional -> Accuracy: 0.5538, MCC: 0.0786, F1: 0.6234

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.41576 | val 2.91687
  Epoch 013 - train 0.18011 | val 2.26670
  Classification -> best τ=0.345 (val F1=0.3780)
  Directional -> Accuracy: 0.6000, MCC: 0.2068, F1: 0.6923

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.63716 | val 0.92154
  Epoch 012 - train 0.47293 | val 1.02736
  Classification -> best τ=0.340 (val F1=0.3079)
  Directional -> Accuracy: 0.4909, MCC: -0.0199, F1: 0.4615

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.50355 | val 1.89433
  Epoch 011 - train 0.34821 | val 2.79237
  Classification -> best τ=0.395 (val F1=0.3250)
  Directional -> Accuracy: 0.4667, MCC: 0.0553, F1: 0.4000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 106). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 106). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 106). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 106). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.42408 | val 4.54977
  Epoch 011 - train 0.31752 | val 4.73001
  Classification -> best τ=0.645 (val F1=0.4256)
  Directional -> Accuracy: 0.3043, MCC: -0.2143, F1: 0.4667

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 106). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 106). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 106). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.61584 | val 2.61639
  Epoch 013 - train 0.49879 | val 2.08810
  Classification -> best τ=0.300 (val F1=0.2759)
  Directional -> Accuracy: 0.5068, MCC: 0.0505, F1: 0.6538

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 106). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 106). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 106). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 106). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.54134 | val 0.86883
  Epoch 012 - train 0.41568 | val 1.17087
  Classification -> best τ=0.460 (val F1=0.4330)
  Directional -> Accuracy: 0.5227, MCC: 0.1525, F1: 0.0870

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.41675 | val 1.05798
  Epoch 013 - train 0.32812 | val 1.52417
  Classification -> best τ=0.515 (val F1=0.4336)
  Directional -> Accuracy: 0.5610, MCC: 0.0649, F1: 0.6538

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.42207 | val 1.54324
  Epoch 011 - train 0.42087 | val 1.50361
  Classification -> best τ=0.645 (val F1=0.5489)
  Directional -> Accuracy: 0.6304, MCC: 0.0000, F1: 0.0000

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.59980 | val 0.92127
  Epoch 017 - train 0.44886 | val 0.77208
  Classification -> best τ=0.420 (val F1=0.2431)
  Directional -> Accuracy: 0.4815, MCC: -0.0791, F1: 0.5758

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.52312 | val 1.57109
  Epoch 011 - train 0.51728 | val 2.06252
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4909, MCC: 0.0000, F1: 0.6585

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.59438 | val 1.37404
  Epoch 011 - train 0.60193 | val 1.02995
  Classification -> best τ=0.405 (val F1=0.0392)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.41399 | val 2.13770
  Epoch 011 - train 0.36106 | val 2.10997
  Classification -> best τ=0.475 (val F1=0.1288)
  Directional -> Accuracy: 0.4259, MCC: -0.1555, F1: 0.4746

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.61539 | val 0.85672

[I 2026-02-22 08:03:36,418] Trial 13 finished with value: 0.25013430298399403 and parameters: {'feature_set': 'finbert', 'model_type': 'BiGRU', 'sequence_length': 30, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.0, 'batch_size': 16, 'learning_rate': 0.008319022896673613, 'weight_decay': 1.5561978332776603e-05, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 0.7225740453720286, 'early_stopping_min_delta': 0.00995672276008956}. Best is trial 12 with value: 0.26451244235752075.

  Epoch 011 - train 0.57799 | val 0.77537
  Classification -> best τ=0.395 (val F1=0.1680)
  Directional -> Accuracy: 0.6102, MCC: 0.2198, F1: 0.5965

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.25013430298399403
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 30
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.68197 | val 0.74921
  Epoch 011 - train 0.67310 | val 0.74418
  Classification -> best τ=0.490 (val F1=0.1787)
  Directional -> Accuracy: 0.5467, MCC: 0.0565, F1: 0.3704

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 106). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.64423 | val 0.78205
  Epoch 011 - train 0.66685 | val 0.78125
  Classification -> best τ=0.505 (val F1=0.0649)
  Directional -> Accuracy: 0.5227, MCC: 0.1601, F1: 0.4324

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 106). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.69501 | val 0.69251
  Epoch 013 - train 0.67414 | val 0.70249
  Classification -> best τ=0.525 (val F1=0.4053)
  Directional -> Accuracy: 0.4667, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.68149 | val 0.90846
  Epoch 011 - train 0.67887 | val 0.92103
  Classification -> best τ=0.505 (val F1=0.1176)
  Directional -> Accuracy: 0.5342, MCC: 0.0000, F1: 0.6964

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.62648 | val 0.67197
  Epoch 014 - train 0.62180 | val 0.69403
  Classification -> best τ=0.530 (val F1=0.3061)
  Directional -> Accuracy: 0.6327, MCC: 0.2770, F1: 0.5909

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.64620 | val 0.72268
  Epoch 011 - train 0.65875 | val 0.73115
  Classification -> best τ=0.540 (val F1=0.0839)
  Directional -> Accuracy: 0.5333, MCC: 0.0629, F1: 0.4324

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.69501 | val 0.76363
  Epoch 011 - train 0.67071 | val 0.76167
  Classification -> best τ=0.455 (val F1=0.3259)
  Directional -> Accuracy: 0.5373, MCC: 0.1794, F1: 0.5867

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 106). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 106). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.68041 | val 1.04118
  Epoch 011 - train 0.65822 | val 1.05621
  Classification -> best τ=0.465 (val F1=0.1204)
  Directional -> Accuracy: 0.4390, MCC: -0.0278, F1: 0.5965

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.67053 | val 0.68639
  Epoch 020 - train 0.66078 | val 0.67738
  Epoch 030 - train 0.63988 | val 0.66800
  Classification -> best τ=0.565 (val F1=0.2018)
  Directional -> Accuracy: 0.3830, MCC: -0.2541, F1: 0.2927

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 106). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 106). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 106). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.65733 | val 1.20989
  Epoch 011 - train 0.65358 | val 1.21798
  Classification -> best τ=0.455 (val F1=0.2623)
  Directional -> Accuracy: 0.4265, MCC: 0.0000, F1: 0.5979

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.66666 | val 1.07942
  Epoch 011 - train 0.65794 | val 1.07931
  Classification -> best τ=0.510 (val F1=0.2375)
  Directional -> Accuracy: 0.4583, MCC: 0.0000, F1: 0.6286

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.67465 | val 0.85075
  Epoch 011 - train 0.65691 | val 0.84717
  Classification -> best τ=0.525 (val F1=0.0174)
  Directional -> Accuracy: 0.5536, MCC: 0.2187, F1: 0.2857

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 106). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.62738 | val 1.73382
  Epoch 011 - train 0.59982 | val 1.80271
  Classification -> best τ=0.525 (val F1=0.2788)
  Directional -> Accuracy: 0.4490, MCC: -0.2105, F1: 0.6197

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 106). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.68133 | val 0.68811
  Epoch 014 - train 0.66812 | val 0.68871
  Classification -> best τ=0.465 (val F1=0.3312)
  Directional -> Accuracy: 0.5932, MCC: 0.1873, F1: 0.6364

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.67213 | val 1.20761
  Epoch 011 - train 0.66485 | val 1.19788
  Classification -> best τ=0.575 (val F1=0.2179)
  Directional -> Accuracy: 0.4800, MCC: 0.1809, F1: 0.6286

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.66309 | val 0.73275
  Epoch 011 - train 0.66522 | val 0.73511
  Classification -> best τ=0.400 (val F1=0.3005)
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 106). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.66658 | val 1.10627
  Epoch 011 - train 0.66150 | val 1.11202
  Classification -> best τ=0.580 (val F1=0.1429)
  Directional -> Accuracy: 0.3860, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.65490 | val 1.05828
  Epoch 011 - train 0.66568 | val 1.06310
  Classification -> best τ=0.515 (val F1=0.1265)
  Directional -> Accuracy: 0.4054, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.66289 | val 0.74596
  Epoch 011 - train 0.65937 | val 0.75136
  Classification -> best τ=0.530 (val F1=0.2756)
  Directional -> Accuracy: 0.4603, MCC: 0.0912, F1: 0.2273

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 106). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.65953 | val 0.78401
  Epoch 011 - train 0.64853 | val 0.79402
  Classification -> best τ=0.510 (val F1=0.0348)
  Directional -> Accuracy: 0.5479, MCC: 0.0000, F1: 0.7080

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.67686 | val 0.88169
  Epoch 011 - train 0.66083 | val 0.89419
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.6087, MCC: 0.0000, F1: 0.7568

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 106). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 106). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 106). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.67260 | val 0.98630
  Epoch 011 - train 0.67457 | val 1.00632
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.67186 | val 0.88602
  Epoch 011 - train 0.66630 | val 0.88665
  Classification -> best τ=0.515 (val F1=0.2719)
  Directional -> Accuracy: 0.5357, MCC: 0.1884, F1: 0.4091

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.63060 | val 1.37521
  Epoch 011 - train 0.62925 | val 1.34733
  Classification -> best τ=0.415 (val F1=0.1687)
  Directional -> Accuracy: 0.4688, MCC: 0.0000, F1: 0.6383

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.68177 | val 0.67822
  Epoch 012 - train 0.65259 | val 0.68274
  Classification -> best τ=0.540 (val F1=0.4005)
  Directional -> Accuracy: 0.5000, MCC: 0.0199, F1: 0.4490

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.67679 | val 0.71279
  Epoch 011 - train 0.64105 | val 0.71614
  Classification -> best τ=0.550 (val F1=0.3313)
  Directional -> Accuracy: 0.4186, MCC: 0.0000, F1: 0.5902

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.68094 | val 0.69853
  Epoch 011 - train 0.65253 | val 0.71249
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5918, MCC: 0.0000, F1: 0.7436

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.67399 | val 0.67810
  Epoch 014 - train 0.67261 | val 0.68996
  Classification -> best τ=0.370 (val F1=0.2995)
  Directional -> Accuracy: 0.5818, MCC: 0.2311, F1: 0.4889

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.67273 | val 0.73611
  Epoch 011 - train 0.65747 | val 0.73720
  Classification -> best τ=0.535 (val F1=0.1284)
  Directional -> Accuracy: 0.4737, MCC: 0.0033, F1: 0.3333

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.66070 | val 0.94408
  Epoch 011 - train 0.67205 | val 0.95936
  Classification -> best τ=0.540 (val F1=0.3150)
  Directional -> Accuracy: 0.4878, MCC: -0.0655, F1: 0.1600

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.66203 | val 0.81356
  Epoch 011 - train 0.66151 | val 0.81881
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5610, MCC: 0.0000, F1: 0.7188

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.64870 | val 0.71731
  Epoch 013 - train 0.62941 | val 0.73912
  Classification -> best τ=0.480 (val F1=0.2158)
  Directional -> Accuracy: 0.5208, MCC: 0.0000, F1: 0.6849

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.63149 | val 0.69787
  Epoch 013 - train 0.64822 | val 0.71169
  Classification -> best τ=0.435 (val F1=0.3566)
  Directional -> Accuracy: 0.5352, MCC: 0.1773, F1: 0.4000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 106). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.65465 | val 0.81011
  Epoch 011 - train 0.64091 | val 0.81049
  Classification -> best τ=0.505 (val F1=0.2401)
  Directional -> Accuracy: 0.5238, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for PCG (101 < 106). Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.63404 | val 0.87073
  Epoch 012 - train 0.62810 | val 0.87419
  Classification -> best τ=0.410 (val F1=0.3828)
  Directional -> Accuracy: 0.5231, MCC: 0.2313, F1: 0.3111

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.67581 | val 0.71406
  Epoch 011 - train 0.66413 | val 0.71425
  Classification -> best τ=0.545 (val F1=0.2582)
  Directional -> Accuracy: 0.4750, MCC: -0.0367, F1: 0.4000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.63267 | val 0.75232
  Epoch 011 - train 0.60755 | val 0.75409
  Classification -> best τ=0.525 (val F1=0.2140)
  Directional -> Accuracy: 0.4364, MCC: -0.1047, F1: 0.4918

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.63167 | val 1.17009
  Epoch 011 - train 0.63499 | val 1.20761
  Classification -> best τ=0.525 (val F1=0.2903)
  Directional -> Accuracy: 0.3778, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 106). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 106). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 106). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 106). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.64300 | val 0.65660
  Epoch 018 - train 0.62880 | val 0.67363
  Classification -> best τ=0.545 (val F1=0.4256)
  Directional -> Accuracy: 0.3261, MCC: 0.0000, F1: 0.4918

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 106). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 106). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 106). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.65131 | val 1.02030
  Epoch 011 - train 0.62977 | val 1.05483
  Classification -> best τ=0.465 (val F1=0.2675)
  Directional -> Accuracy: 0.4932, MCC: 0.0000, F1: 0.6606

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 106). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 106). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 106). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 106). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.65964 | val 0.72585
  Epoch 011 - train 0.66024 | val 0.72374
  Classification -> best τ=0.520 (val F1=0.1980)
  Directional -> Accuracy: 0.4091, MCC: -0.2041, F1: 0.2353

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.65323 | val 0.76331
  Epoch 011 - train 0.65747 | val 0.77012
  Classification -> best τ=0.540 (val F1=0.1512)
  Directional -> Accuracy: 0.5854, MCC: 0.0984, F1: 0.6909

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.64483 | val 0.89720
  Epoch 011 - train 0.65431 | val 0.90194
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.3696, MCC: 0.0000, F1: 0.5397

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.67475 | val 0.75518
  Epoch 011 - train 0.68169 | val 0.75647
  Classification -> best τ=0.540 (val F1=0.0935)
  Directional -> Accuracy: 0.5556, MCC: 0.2092, F1: 0.4286

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.64859 | val 1.22904
  Epoch 011 - train 0.64987 | val 1.23553
  Classification -> best τ=0.460 (val F1=0.2873)
  Directional -> Accuracy: 0.4545, MCC: -0.1183, F1: 0.2500

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.67382 | val 0.66218
  Epoch 015 - train 0.65596 | val 0.68520
  Classification -> best τ=0.560 (val F1=0.2394)
  Directional -> Accuracy: 0.5192, MCC: 0.1400, F1: 0.6753

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.65617 | val 0.76528
  Epoch 011 - train 0.65075 | val 0.75948
  Classification -> best τ=0.545 (val F1=0.1288)
  Directional -> Accuracy: 0.4815, MCC: -0.0262, F1: 0.3913

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.67224 | val 0.69363

[I 2026-02-22 08:08:41,617] Trial 14 finished with value: 0.20389044338204995 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 30, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.4, 'dropout': 0.2, 'batch_size': 16, 'learning_rate': 9.096546573731252e-05, 'weight_decay': 4.815406103827934e-05, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 1.2522544290980349, 'early_stopping_min_delta': 0.008113904290689934}. Best is trial 12 with value: 0.26451244235752075.

  Epoch 017 - train 0.65166 | val 0.69588
  Classification -> best τ=0.440 (val F1=0.0921)
  Directional -> Accuracy: 0.4576, MCC: -0.0687, F1: 0.5556

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.20389044338204995
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 6
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.56043 | val 1.64070
  Epoch 011 - train 0.50104 | val 1.83031
  Classification -> best τ=0.760 (val F1=0.2346)
  Directional -> Accuracy: 0.5570, MCC: 0.0000, F1: 0.0000

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 82). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.40899 | val 1.04823
  Epoch 011 - train 0.40312 | val 0.99932
  Classification -> best τ=0.570 (val F1=0.2364)
  Directional -> Accuracy: 0.4792, MCC: 0.1839, F1: 0.1379

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 82). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.44304 | val 1.68339
  Epoch 011 - train 0.43416 | val 2.00574
  Classification -> best τ=0.680 (val F1=0.2332)
  Directional -> Accuracy: 0.4898, MCC: 0.0696, F1: 0.1379

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.54046 | val 1.09062
  Epoch 011 - train 0.52366 | val 1.12718
  Classification -> best τ=0.300 (val F1=0.2670)
  Directional -> Accuracy: 0.5714, MCC: 0.1155, F1: 0.6598

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.44903 | val 1.58714
  Epoch 011 - train 0.45022 | val 1.68608
  Classification -> best τ=0.590 (val F1=0.4274)
  Directional -> Accuracy: 0.5472, MCC: 0.1500, F1: 0.4000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.43134 | val 0.80272
  Epoch 011 - train 0.42157 | val 0.95933
  Classification -> best τ=0.530 (val F1=0.2343)
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.51648 | val 1.31522
  Epoch 011 - train 0.49748 | val 1.50626
  Classification -> best τ=0.475 (val F1=0.2008)
  Directional -> Accuracy: 0.5211, MCC: 0.1549, F1: 0.5854

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 82). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 82). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.38575 | val 1.04015
  Epoch 015 - train 0.29236 | val 1.13097
  Classification -> best τ=0.425 (val F1=0.4750)
  Directional -> Accuracy: 0.5745, MCC: -0.0377, F1: 0.0909

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.45114 | val 1.11830
  Epoch 011 - train 0.42514 | val 0.87964
  Classification -> best τ=0.610 (val F1=0.3429)
  Directional -> Accuracy: 0.6279, MCC: 0.2567, F1: 0.5789

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 82). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 82). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.41457 | val 1.81984
  Epoch 011 - train 0.36382 | val 1.55827
  Classification -> best τ=0.260 (val F1=0.2120)
  Directional -> Accuracy: 0.4583, MCC: 0.1470, F1: 0.6139

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.43507 | val 1.00835
  Epoch 011 - train 0.41412 | val 0.96033
  Classification -> best τ=0.610 (val F1=0.1680)
  Directional -> Accuracy: 0.5769, MCC: 0.1350, F1: 0.4500

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.49942 | val 1.19567
  Epoch 011 - train 0.48791 | val 1.18031
  Classification -> best τ=0.545 (val F1=0.0335)
  Directional -> Accuracy: 0.6000, MCC: 0.2075, F1: 0.5385

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.40063 | val 0.88286
  Epoch 011 - train 0.33859 | val 0.93348
  Classification -> best τ=0.555 (val F1=0.2253)
  Directional -> Accuracy: 0.3778, MCC: -0.2373, F1: 0.4615

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 82). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.50191 | val 0.89050
  Epoch 012 - train 0.45049 | val 0.75486
  Classification -> best τ=0.610 (val F1=0.4300)
  Directional -> Accuracy: 0.5397, MCC: 0.0790, F1: 0.4314

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.43632 | val 2.08684
  Epoch 011 - train 0.45290 | val 2.22972
  Classification -> best τ=0.625 (val F1=0.1232)
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.47120 | val 1.33372
  Epoch 011 - train 0.45693 | val 1.37295
  Classification -> best τ=0.640 (val F1=0.2909)
  Directional -> Accuracy: 0.5139, MCC: 0.0279, F1: 0.5333

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.45187 | val 2.51707
  Epoch 011 - train 0.40378 | val 2.59545
  Classification -> best τ=0.475 (val F1=0.1411)
  Directional -> Accuracy: 0.6066, MCC: 0.0000, F1: 0.7551

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.51585 | val 1.37026
  Epoch 011 - train 0.47106 | val 1.40622
  Classification -> best τ=0.555 (val F1=0.1541)
  Directional -> Accuracy: 0.3974, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.48052 | val 0.72953
  Epoch 013 - train 0.44002 | val 0.82569
  Classification -> best τ=0.390 (val F1=0.2917)
  Directional -> Accuracy: 0.4925, MCC: 0.1096, F1: 0.3462

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 82). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.49155 | val 1.37716
  Epoch 012 - train 0.45175 | val 1.25448
  Classification -> best τ=0.435 (val F1=0.2913)
  Directional -> Accuracy: 0.4675, MCC: -0.0220, F1: 0.3279

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.47276 | val 1.45769
  Epoch 011 - train 0.38502 | val 1.35952
  Classification -> best τ=0.450 (val F1=0.2303)
  Directional -> Accuracy: 0.5400, MCC: -0.0071, F1: 0.6462

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 82). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 82). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 82). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.45727 | val 1.25499
  Epoch 011 - train 0.41496 | val 1.22397
  Classification -> best τ=0.530 (val F1=0.3057)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.49162 | val 1.47135
  Epoch 011 - train 0.45582 | val 1.48882
  Classification -> best τ=0.720 (val F1=0.2372)
  Directional -> Accuracy: 0.4000, MCC: -0.1540, F1: 0.0000

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.53469 | val 0.76452
  Epoch 011 - train 0.47136 | val 0.73783
  Classification -> best τ=0.460 (val F1=0.1757)
  Directional -> Accuracy: 0.5147, MCC: 0.0312, F1: 0.5217

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.47345 | val 0.97076
  Epoch 012 - train 0.39384 | val 0.95674
  Classification -> best τ=0.515 (val F1=0.5446)
  Directional -> Accuracy: 0.5517, MCC: 0.1685, F1: 0.4583

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.38540 | val 1.93731
  Epoch 013 - train 0.37522 | val 1.91407
  Classification -> best τ=0.505 (val F1=0.3862)
  Directional -> Accuracy: 0.3673, MCC: -0.2597, F1: 0.3404

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.49822 | val 0.76000
  Epoch 012 - train 0.47723 | val 0.69511
  Classification -> best τ=0.440 (val F1=0.2306)
  Directional -> Accuracy: 0.5111, MCC: 0.0181, F1: 0.5600

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.53347 | val 1.24439
  Epoch 011 - train 0.51722 | val 1.35423
  Classification -> best τ=0.340 (val F1=0.2312)
  Directional -> Accuracy: 0.5763, MCC: 0.2343, F1: 0.4898

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.42232 | val 3.92374
  Epoch 011 - train 0.41320 | val 4.01170
  Classification -> best τ=0.445 (val F1=0.2012)
  Directional -> Accuracy: 0.4773, MCC: -0.0455, F1: 0.4889

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.40472 | val 0.87210
  Epoch 011 - train 0.37773 | val 1.02124
  Classification -> best τ=0.480 (val F1=0.0910)
  Directional -> Accuracy: 0.5217, MCC: 0.0442, F1: 0.5600

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.51123 | val 1.37238
  Epoch 011 - train 0.46412 | val 1.39208
  Classification -> best τ=0.440 (val F1=0.0744)
  Directional -> Accuracy: 0.5435, MCC: 0.0000, F1: 0.7042

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.44288 | val 1.16860
  Epoch 012 - train 0.42174 | val 0.95726
  Classification -> best τ=0.355 (val F1=0.3201)
  Directional -> Accuracy: 0.5192, MCC: 0.0000, F1: 0.6835

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.44641 | val 1.17084
  Epoch 011 - train 0.44909 | val 1.04925
  Classification -> best τ=0.505 (val F1=0.3541)
  Directional -> Accuracy: 0.4267, MCC: -0.1311, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 82). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.44876 | val 0.81081
  Epoch 011 - train 0.43736 | val 0.74065
  Classification -> best τ=0.480 (val F1=0.5311)
  Directional -> Accuracy: 0.6098, MCC: 0.2605, F1: 0.6800

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.41460 | val 1.83690
  Epoch 011 - train 0.41546 | val 1.86776
  Classification -> best τ=0.425 (val F1=0.2421)
  Directional -> Accuracy: 0.4565, MCC: 0.0000, F1: 0.6269

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.48949 | val 0.98551
  Epoch 011 - train 0.45997 | val 0.94201
  Classification -> best τ=0.490 (val F1=0.3919)
  Directional -> Accuracy: 0.6232, MCC: 0.2730, F1: 0.6286

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.44986 | val 0.77049
  Epoch 011 - train 0.42585 | val 0.81875
  Classification -> best τ=0.445 (val F1=0.3241)
  Directional -> Accuracy: 0.5111, MCC: 0.0314, F1: 0.4211

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.52087 | val 1.29964
  Epoch 011 - train 0.50101 | val 1.31814
  Classification -> best τ=0.400 (val F1=0.2675)
  Directional -> Accuracy: 0.5424, MCC: 0.1781, F1: 0.6582

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.38802 | val 2.24777
  Epoch 011 - train 0.39285 | val 2.10549
  Classification -> best τ=0.400 (val F1=0.2032)
  Directional -> Accuracy: 0.6122, MCC: 0.0000, F1: 0.7595

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 82). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 82). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 82). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 82). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.44354 | val 1.02529
  Epoch 011 - train 0.42953 | val 1.08943
  Classification -> best τ=0.580 (val F1=0.3035)
  Directional -> Accuracy: 0.4524, MCC: 0.0364, F1: 0.4651

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 82). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.44875 | val 2.15899
  Epoch 011 - train 0.40073 | val 2.13895
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5122, MCC: 0.0000, F1: 0.6774

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 82). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 82). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.47371 | val 1.77149
  Epoch 011 - train 0.43680 | val 1.95754
  Classification -> best τ=0.425 (val F1=0.2250)
  Directional -> Accuracy: 0.5455, MCC: 0.1167, F1: 0.6667

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 82). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 82). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.50426 | val 1.55555
  Epoch 011 - train 0.48400 | val 1.48621
  Classification -> best τ=0.540 (val F1=0.1326)
  Directional -> Accuracy: 0.4082, MCC: -0.2299, F1: 0.5538

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.30149 | val 3.18644
  Epoch 011 - train 0.25808 | val 3.19790
  Classification -> best τ=0.585 (val F1=0.5804)
  Directional -> Accuracy: 0.7234, MCC: 0.4390, F1: 0.7937

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.42254 | val 0.99887
  Epoch 011 - train 0.41229 | val 0.86811
  Classification -> best τ=0.615 (val F1=0.0392)
  Directional -> Accuracy: 0.4286, MCC: 0.0259, F1: 0.5000

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.52070 | val 0.78785
  Epoch 011 - train 0.47837 | val 0.75508
  Classification -> best τ=0.515 (val F1=0.2652)
  Directional -> Accuracy: 0.5345, MCC: -0.1194, F1: 0.6966

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.43720 | val 2.03392
  Epoch 011 - train 0.40612 | val 2.13099
  Classification -> best τ=0.745 (val F1=0.3531)
  Directional -> Accuracy: 0.4915, MCC: 0.0000, F1: 0.6591

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.52681 | val 2.60560
  Epoch 011 - train 0.45750 | val 2.65081
  Classification -> best τ=0.410 (val F1=0.0321)
  Directional -> Accuracy: 0.6250, MCC: 0.3363, F1: 0.7407

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.41943 | val 2.70802
  Epoch 011 - train 0.40059 | val 2.24287
  Classification -> best τ=0.750 (val F1=0.1111)
  Directional -> Accuracy: 0.4655, MCC: -0.0860, F1: 0.0606

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.52585 | val 0.82232

[I 2026-02-22 08:10:40,495] Trial 15 finished with value: 0.25633100537301623 and parameters: {'feature_set': 'sector', 'model_type': 'BiGRU', 'sequence_length': 6, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.1, 'batch_size': 16, 'learning_rate': 0.001087321773083626, 'weight_decay': 4.8617623638182313e-05, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 1.2148619291507976, 'early_stopping_min_delta': 0.008047016447068008}. Best is trial 12 with value: 0.26451244235752075.

  Epoch 019 - train 0.38308 | val 0.97512
  Classification -> best τ=0.620 (val F1=0.4194)
  Directional -> Accuracy: 0.4762, MCC: -0.0374, F1: 0.5217

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.25633100537301623
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 30
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'emotion_anger', 'emotion_disgust', 'emotion_fear', 'emotion_joy', 'emotion_neutral', 'emotion_sadness', 'emotion_surprize', 'emotion_anger_pct', 'emotion_disgust_pct', 'emotion_fear_pct', 'emotion_joy_pct', 'emotion_neutral_pct', 'emotion_sadness_pct', 'emotion_surprize_pct']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.61675 | val 0.73145
  Epoch 011 - train 0.61913 | val 0.72765
  Classification -> best τ=0.435 (val F1=0.1314)
  Directional -> Accuracy: 0.4667, MCC: 0.1059, F1: 0.6296

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 106). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.58344 | val 0.94380
  Epoch 011 - train 0.59816 | val 0.95443
  Classification -> best τ=0.475 (val F1=0.2757)
  Directional -> Accuracy: 0.5909, MCC: 0.0000, F1: 0.7429

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 106). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.64372 | val 0.70387
  Epoch 013 - train 0.62470 | val 0.73066
  Classification -> best τ=0.495 (val F1=0.2970)
  Directional -> Accuracy: 0.4000, MCC: -0.1964, F1: 0.4000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.64730 | val 0.82185
  Epoch 011 - train 0.64300 | val 0.81661
  Classification -> best τ=0.475 (val F1=0.0893)
  Directional -> Accuracy: 0.5342, MCC: 0.0000, F1: 0.6964

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.55764 | val 0.64371
  Epoch 015 - train 0.53213 | val 0.68716
  Classification -> best τ=0.495 (val F1=0.4669)
  Directional -> Accuracy: 0.6122, MCC: 0.2250, F1: 0.6122

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.59363 | val 0.69605
  Epoch 014 - train 0.55227 | val 0.69925
  Classification -> best τ=0.525 (val F1=0.2260)
  Directional -> Accuracy: 0.5111, MCC: 0.0048, F1: 0.0833

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.63999 | val 0.84025
  Epoch 011 - train 0.62832 | val 0.83817
  Classification -> best τ=0.475 (val F1=0.2246)
  Directional -> Accuracy: 0.4179, MCC: 0.0307, F1: 0.5714

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 106). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 106). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.62334 | val 1.11902
  Epoch 011 - train 0.63191 | val 1.16323
  Classification -> best τ=0.505 (val F1=0.1491)
  Directional -> Accuracy: 0.5366, MCC: 0.0058, F1: 0.2963

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.63064 | val 0.67030
  Epoch 015 - train 0.58503 | val 0.67712
  Classification -> best τ=0.570 (val F1=0.2895)
  Directional -> Accuracy: 0.5745, MCC: 0.1049, F1: 0.2857

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 106). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 106). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 106). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.60196 | val 1.20703
  Epoch 011 - train 0.60266 | val 1.18591
  Classification -> best τ=0.420 (val F1=0.2261)
  Directional -> Accuracy: 0.4265, MCC: 0.0000, F1: 0.5979

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.61385 | val 0.97406
  Epoch 011 - train 0.61575 | val 0.97221
  Classification -> best τ=0.545 (val F1=0.2494)
  Directional -> Accuracy: 0.4583, MCC: 0.0000, F1: 0.6286

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.61815 | val 0.89616
  Epoch 011 - train 0.62922 | val 0.91507
  Classification -> best τ=0.535 (val F1=0.0625)
  Directional -> Accuracy: 0.4821, MCC: -0.0069, F1: 0.0645

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 106). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.59661 | val 1.55733
  Epoch 011 - train 0.58264 | val 1.58625
  Classification -> best τ=0.490 (val F1=0.1353)
  Directional -> Accuracy: 0.5102, MCC: 0.0090, F1: 0.2500

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 106). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.65219 | val 0.70409
  Epoch 020 - train 0.59101 | val 0.71651
  Epoch 021 - train 0.60188 | val 0.72023
  Classification -> best τ=0.550 (val F1=0.3087)
  Directional -> Accuracy: 0.5932, MCC: 0.1873, F1: 0.6364

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.63019 | val 0.96109
  Epoch 011 - train 0.65060 | val 0.97148
  Classification -> best τ=0.585 (val F1=0.2060)
  Directional -> Accuracy: 0.5800, MCC: 0.1612, F1: 0.0870

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.61765 | val 0.89454
  Epoch 011 - train 0.61829 | val 0.88194
  Classification -> best τ=0.490 (val F1=0.3111)
  Directional -> Accuracy: 0.5294, MCC: 0.0354, F1: 0.6279

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 106). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.61786 | val 1.06222
  Epoch 011 - train 0.62244 | val 1.06012
  Classification -> best τ=0.600 (val F1=0.1325)
  Directional -> Accuracy: 0.3860, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.62337 | val 1.09423
  Epoch 011 - train 0.61933 | val 1.10441
  Classification -> best τ=0.445 (val F1=0.1725)
  Directional -> Accuracy: 0.4730, MCC: 0.1388, F1: 0.2642

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.61123 | val 0.78166
  Epoch 011 - train 0.61028 | val 0.77521
  Classification -> best τ=0.545 (val F1=0.2009)
  Directional -> Accuracy: 0.4127, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 106). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.62358 | val 0.69495
  Epoch 011 - train 0.61792 | val 0.69535
  Classification -> best τ=0.475 (val F1=0.2100)
  Directional -> Accuracy: 0.4521, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.58733 | val 0.91007
  Epoch 011 - train 0.59222 | val 0.91081
  Classification -> best τ=0.450 (val F1=0.2227)
  Directional -> Accuracy: 0.4565, MCC: 0.0586, F1: 0.3243

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 106). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 106). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 106). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.61090 | val 0.91161
  Epoch 011 - train 0.61948 | val 0.92750
  Classification -> best τ=0.520 (val F1=0.1615)
  Directional -> Accuracy: 0.5156, MCC: 0.0388, F1: 0.3111

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.62821 | val 0.77508
  Epoch 011 - train 0.63105 | val 0.78570
  Classification -> best τ=0.490 (val F1=0.1925)
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.7273

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.57311 | val 1.17545
  Epoch 011 - train 0.58801 | val 1.16796
  Classification -> best τ=0.410 (val F1=0.1994)
  Directional -> Accuracy: 0.5469, MCC: 0.1396, F1: 0.6234

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.59011 | val 0.69262
  Epoch 013 - train 0.57683 | val 0.70397
  Classification -> best τ=0.495 (val F1=0.4299)
  Directional -> Accuracy: 0.4815, MCC: -0.0104, F1: 0.3913

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.57935 | val 0.79808
  Epoch 011 - train 0.58687 | val 0.80322
  Classification -> best τ=0.500 (val F1=0.1543)
  Directional -> Accuracy: 0.5116, MCC: -0.0454, F1: 0.3226

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.63661 | val 0.85490
  Epoch 011 - train 0.60727 | val 0.85530
  Classification -> best τ=0.495 (val F1=0.3284)
  Directional -> Accuracy: 0.5306, MCC: 0.0818, F1: 0.5490

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.62061 | val 0.89878
  Epoch 011 - train 0.61359 | val 0.90190
  Classification -> best τ=0.460 (val F1=0.1129)
  Directional -> Accuracy: 0.5273, MCC: 0.0078, F1: 0.6389

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.65186 | val 0.65606
  Epoch 020 - train 0.60626 | val 0.65900
  Epoch 023 - train 0.58253 | val 0.65870
  Classification -> best τ=0.555 (val F1=0.4808)
  Directional -> Accuracy: 0.5000, MCC: 0.0289, F1: 0.4571

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.62841 | val 1.06422
  Epoch 011 - train 0.61389 | val 1.07451
  Classification -> best τ=0.515 (val F1=0.3922)
  Directional -> Accuracy: 0.5366, MCC: 0.0837, F1: 0.2400

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.60921 | val 0.87028
  Epoch 011 - train 0.61406 | val 0.86898
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5610, MCC: 0.0000, F1: 0.7188

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.60680 | val 0.72944
  Epoch 013 - train 0.59417 | val 0.74510
  Classification -> best τ=0.540 (val F1=0.3333)
  Directional -> Accuracy: 0.5208, MCC: 0.0000, F1: 0.6849

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.58780 | val 0.73185
  Epoch 013 - train 0.56461 | val 0.76049
  Classification -> best τ=0.430 (val F1=0.2731)
  Directional -> Accuracy: 0.5070, MCC: 0.1231, F1: 0.3396

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 106). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.58163 | val 0.93594
  Epoch 011 - train 0.60021 | val 0.94514
  Classification -> best τ=0.575 (val F1=0.1894)
  Directional -> Accuracy: 0.5238, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for PCG (101 < 106). Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.61825 | val 0.81285
  Epoch 012 - train 0.59313 | val 0.81534
  Classification -> best τ=0.360 (val F1=0.3317)
  Directional -> Accuracy: 0.5538, MCC: 0.0479, F1: 0.6588

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.60097 | val 0.72244
  Epoch 013 - train 0.57017 | val 0.73586
  Classification -> best τ=0.525 (val F1=0.2520)
  Directional -> Accuracy: 0.5750, MCC: 0.1502, F1: 0.5854

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.57341 | val 0.75810
  Epoch 011 - train 0.56313 | val 0.75722
  Classification -> best τ=0.470 (val F1=0.2544)
  Directional -> Accuracy: 0.4000, MCC: -0.1797, F1: 0.5075

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.58478 | val 2.25322
  Epoch 011 - train 0.58017 | val 2.27860
  Classification -> best τ=0.525 (val F1=0.2626)
  Directional -> Accuracy: 0.3778, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 106). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 106). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 106). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 106). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.61148 | val 0.74075
  Epoch 011 - train 0.62047 | val 0.74193
  Classification -> best τ=0.545 (val F1=0.2923)
  Directional -> Accuracy: 0.3261, MCC: 0.0000, F1: 0.4918

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 106). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 106). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 106). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.60875 | val 0.93084
  Epoch 011 - train 0.60259 | val 0.95032
  Classification -> best τ=0.505 (val F1=0.1440)
  Directional -> Accuracy: 0.5342, MCC: 0.0672, F1: 0.4688

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 106). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 106). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 106). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 106). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.61274 | val 0.82435
  Epoch 011 - train 0.60118 | val 0.81745
  Classification -> best τ=0.575 (val F1=0.3064)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.61191 | val 0.69295
  Epoch 011 - train 0.57620 | val 0.69511
  Classification -> best τ=0.450 (val F1=0.1762)
  Directional -> Accuracy: 0.5854, MCC: 0.0000, F1: 0.7385

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.61394 | val 0.88040
  Epoch 011 - train 0.58357 | val 0.89254
  Classification -> best τ=0.535 (val F1=0.0608)
  Directional -> Accuracy: 0.3696, MCC: 0.0000, F1: 0.5397

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.62563 | val 0.93697
  Epoch 011 - train 0.63411 | val 0.95039
  Classification -> best τ=0.520 (val F1=0.1685)
  Directional -> Accuracy: 0.4259, MCC: -0.1412, F1: 0.4364

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.61922 | val 1.03397
  Epoch 011 - train 0.60631 | val 1.04049
  Classification -> best τ=0.500 (val F1=0.2712)
  Directional -> Accuracy: 0.5273, MCC: 0.1908, F1: 0.6750

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.62216 | val 0.69609
  Epoch 011 - train 0.61181 | val 0.70015
  Classification -> best τ=0.510 (val F1=0.1306)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.61856 | val 0.75672
  Epoch 012 - train 0.60558 | val 0.75004
  Classification -> best τ=0.450 (val F1=0.3459)
  Directional -> Accuracy: 0.5926, MCC: 0.1911, F1: 0.6765

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.64382 | val 0.68060

[I 2026-02-22 08:15:38,057] Trial 16 finished with value: 0.23005691496940717 and parameters: {'feature_set': 'emotion', 'model_type': 'BiGRU', 'sequence_length': 30, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.4, 'dropout': 0.2, 'batch_size': 16, 'learning_rate': 0.0001510508952769942, 'weight_decay': 5.510361795935465e-06, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 50, 'huber_delta': 0.7528071315406845, 'early_stopping_min_delta': 0.008271738950684834}. Best is trial 12 with value: 0.26451244235752075.

  Epoch 013 - train 0.63027 | val 0.68070
  Classification -> best τ=0.515 (val F1=0.2110)
  Directional -> Accuracy: 0.4237, MCC: -0.2110, F1: 0.1905

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.23005691496940717
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d', 'positive_emotion', 'negative_emotion', 'uncertainty_emotion', 'positive_emotion_pct', 'negative_emotion_pct', 'uncertainty_emotion_pct']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.51804 | val 0.93888
  Epoch 016 - train 0.44491 | val 1.19209
  Classification -> best τ=0.595 (val F1=0.2200)
  Directional -> Accuracy: 0.5921, MCC: 0.1542, F1: 0.4364

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.46723 | val 0.91591
  Epoch 016 - train 0.34449 | val 1.16718
  Classification -> best τ=0.410 (val F1=0.1186)
  Directional -> Accuracy: 0.5778, MCC: 0.0000, F1: 0.7324

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.54916 | val 1.44872
  Epoch 016 - train 0.40470 | val 1.97273
  Classification -> best τ=0.680 (val F1=0.3537)
  Directional -> Accuracy: 0.4565, MCC: -0.0996, F1: 0.0741

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.54805 | val 0.90221
  Epoch 016 - train 0.46533 | val 1.21844
  Classification -> best τ=0.365 (val F1=0.0732)
  Directional -> Accuracy: 0.5135, MCC: -0.0752, F1: 0.6667

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.46249 | val 0.95678
  Epoch 016 - train 0.37880 | val 0.70966
  Classification -> best τ=0.570 (val F1=0.3415)
  Directional -> Accuracy: 0.6400, MCC: 0.2821, F1: 0.6400

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.39622 | val 0.80378
  Epoch 016 - train 0.26322 | val 1.59198
  Classification -> best τ=0.555 (val F1=0.1808)
  Directional -> Accuracy: 0.4783, MCC: -0.2041, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.54720 | val 1.06926
  Epoch 016 - train 0.44312 | val 1.32809
  Classification -> best τ=0.575 (val F1=0.2727)
  Directional -> Accuracy: 0.5294, MCC: 0.0790, F1: 0.5000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.46941 | val 0.57325
  Epoch 020 - train 0.23994 | val 2.10813
  Epoch 026 - train 0.14598 | val 2.45486
  Classification -> best τ=0.730 (val F1=0.5247)
  Directional -> Accuracy: 0.5000, MCC: -0.0782, F1: 0.2759

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.47098 | val 1.95254
  Epoch 016 - train 0.39447 | val 2.75526
  Classification -> best τ=0.645 (val F1=0.2443)
  Directional -> Accuracy: 0.6042, MCC: 0.2100, F1: 0.5778

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.53499 | val 0.71908
  Epoch 020 - train 0.34221 | val 0.90416
  Epoch 022 - train 0.30691 | val 0.87483
  Classification -> best τ=0.570 (val F1=0.2359)
  Directional -> Accuracy: 0.5507, MCC: 0.0475, F1: 0.3922

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.51379 | val 0.83236
  Epoch 019 - train 0.31392 | val 0.99074
  Classification -> best τ=0.510 (val F1=0.3716)
  Directional -> Accuracy: 0.4898, MCC: 0.0370, F1: 0.5763

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.51989 | val 2.05613
  Epoch 016 - train 0.39281 | val 2.69297
  Classification -> best τ=0.445 (val F1=0.1576)
  Directional -> Accuracy: 0.5965, MCC: 0.3156, F1: 0.7160

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.47063 | val 3.38772
  Epoch 016 - train 0.37389 | val 3.57980
  Classification -> best τ=0.490 (val F1=0.2071)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.6230

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.52726 | val 1.00804
  Epoch 016 - train 0.47028 | val 1.30503
  Classification -> best τ=0.515 (val F1=0.3126)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.46046 | val 0.74860
  Epoch 016 - train 0.38336 | val 0.82348
  Classification -> best τ=0.600 (val F1=0.1843)
  Directional -> Accuracy: 0.5686, MCC: 0.1560, F1: 0.0833

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.56389 | val 1.10350
  Epoch 020 - train 0.38392 | val 1.28918
  Classification -> best τ=0.700 (val F1=0.2693)
  Directional -> Accuracy: 0.4638, MCC: -0.0333, F1: 0.2449

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.50989 | val 1.61725
  Epoch 016 - train 0.40372 | val 2.24991
  Classification -> best τ=0.650 (val F1=0.1065)
  Directional -> Accuracy: 0.3793, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.49802 | val 1.37557
  Epoch 016 - train 0.41208 | val 1.24255
  Classification -> best τ=0.550 (val F1=0.1909)
  Directional -> Accuracy: 0.4000, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.49347 | val 1.27559
  Epoch 019 - train 0.28629 | val 1.94553
  Classification -> best τ=0.320 (val F1=0.3202)
  Directional -> Accuracy: 0.5156, MCC: 0.0624, F1: 0.5079

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.51319 | val 1.23687
  Epoch 016 - train 0.43135 | val 1.36374
  Classification -> best τ=0.530 (val F1=0.2309)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.41927 | val 1.53789
  Epoch 016 - train 0.27195 | val 1.54554
  Classification -> best τ=0.435 (val F1=0.2247)
  Directional -> Accuracy: 0.6170, MCC: 0.0000, F1: 0.7632

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.54398 | val 0.88875
  Epoch 016 - train 0.45025 | val 0.76630
  Classification -> best τ=0.465 (val F1=0.2160)
  Directional -> Accuracy: 0.5692, MCC: 0.1471, F1: 0.6500

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.52502 | val 0.71634
  Epoch 017 - train 0.36806 | val 0.87215
  Classification -> best τ=0.550 (val F1=0.3881)
  Directional -> Accuracy: 0.5088, MCC: 0.0112, F1: 0.5484

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.48442 | val 1.46955
  Epoch 016 - train 0.42647 | val 2.46242
  Classification -> best τ=0.550 (val F1=0.0226)
  Directional -> Accuracy: 0.5231, MCC: 0.0197, F1: 0.2439

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.48037 | val 1.22013
  Epoch 017 - train 0.37059 | val 1.33481
  Classification -> best τ=0.550 (val F1=0.5635)
  Directional -> Accuracy: 0.5455, MCC: 0.1641, F1: 0.4186

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.39845 | val 3.32220
  Epoch 016 - train 0.34266 | val 3.51626
  Classification -> best τ=0.670 (val F1=0.2035)
  Directional -> Accuracy: 0.4222, MCC: -0.0340, F1: 0.5806

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.54383 | val 0.93842
  Epoch 020 - train 0.39531 | val 0.91466
  Epoch 021 - train 0.36242 | val 0.99728
  Classification -> best τ=0.695 (val F1=0.3347)
  Directional -> Accuracy: 0.4286, MCC: -0.0468, F1: 0.1429

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.48895 | val 0.82504
  Epoch 016 - train 0.42020 | val 0.95005
  Classification -> best τ=0.455 (val F1=0.3217)
  Directional -> Accuracy: 0.4464, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.46104 | val 1.16924
  Epoch 016 - train 0.38786 | val 0.93230
  Classification -> best τ=0.525 (val F1=0.2774)
  Directional -> Accuracy: 0.4500, MCC: -0.0821, F1: 0.4211

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.45864 | val 1.67977
  Epoch 016 - train 0.35469 | val 1.97258
  Classification -> best τ=0.530 (val F1=0.0323)
  Directional -> Accuracy: 0.5476, MCC: 0.0953, F1: 0.5366

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.48187 | val 1.25501
  Epoch 017 - train 0.37951 | val 1.90969
  Classification -> best τ=0.350 (val F1=0.0769)
  Directional -> Accuracy: 0.5476, MCC: 0.0000, F1: 0.7077

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.48391 | val 0.78125
  Epoch 020 - train 0.22699 | val 1.25696
  Classification -> best τ=0.315 (val F1=0.3142)
  Directional -> Accuracy: 0.5306, MCC: 0.0509, F1: 0.5818

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.48518 | val 0.84460
  Epoch 016 - train 0.38541 | val 1.03971
  Classification -> best τ=0.485 (val F1=0.2727)
  Directional -> Accuracy: 0.4306, MCC: -0.1327, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.48566 | val 0.86631
  Epoch 016 - train 0.40619 | val 1.04441
  Classification -> best τ=0.405 (val F1=0.2324)
  Directional -> Accuracy: 0.4651, MCC: -0.0746, F1: 0.4103

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.53617 | val 1.35580
  Epoch 016 - train 0.45317 | val 1.45563
  Classification -> best τ=0.365 (val F1=0.3525)
  Directional -> Accuracy: 0.5000, MCC: 0.1168, F1: 0.3529

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.45144 | val 3.14765
  Epoch 016 - train 0.36179 | val 3.86779
  Classification -> best τ=0.420 (val F1=0.2409)
  Directional -> Accuracy: 0.6190, MCC: 0.2364, F1: 0.6364

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.44150 | val 1.30958
  Epoch 016 - train 0.32388 | val 1.67382
  Classification -> best τ=0.360 (val F1=0.3405)
  Directional -> Accuracy: 0.4821, MCC: 0.0030, F1: 0.5797

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.38278 | val 1.34515
  Epoch 016 - train 0.27460 | val 1.38350
  Classification -> best τ=0.520 (val F1=0.3105)
  Directional -> Accuracy: 0.4783, MCC: 0.0040, F1: 0.4783

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.49985 | val 0.89985
  Epoch 016 - train 0.43182 | val 0.91080
  Classification -> best τ=0.495 (val F1=0.4201)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.47688 | val 1.27389
  Epoch 016 - train 0.36475 | val 1.65262
  Classification -> best τ=0.595 (val F1=0.2620)
  Directional -> Accuracy: 0.5000, MCC: -0.0151, F1: 0.3273

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.53349 | val 0.98602
  Epoch 016 - train 0.41761 | val 1.41138
  Classification -> best τ=0.520 (val F1=0.0622)
  Directional -> Accuracy: 0.5111, MCC: 0.0000, F1: 0.6765

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.43776 | val 1.30709
  Epoch 016 - train 0.31103 | val 1.38834
  Classification -> best τ=0.585 (val F1=0.2010)
  Directional -> Accuracy: 0.5476, MCC: 0.1105, F1: 0.5581

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.43807 | val 0.94742
  Epoch 018 - train 0.31578 | val 1.66956
  Classification -> best τ=0.425 (val F1=0.2605)
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.5455

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.50801 | val 1.14680
  Epoch 016 - train 0.46403 | val 1.23272
  Classification -> best τ=0.450 (val F1=0.0465)
  Directional -> Accuracy: 0.5091, MCC: -0.1150, F1: 0.6667

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.43020 | val 2.12542
  Epoch 016 - train 0.35755 | val 2.52914
  Classification -> best τ=0.605 (val F1=0.3455)
  Directional -> Accuracy: 0.4821, MCC: -0.0226, F1: 0.5672

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.51405 | val 0.80330
  Epoch 017 - train 0.42411 | val 1.19114
  Classification -> best τ=0.295 (val F1=0.2309)
  Directional -> Accuracy: 0.5094, MCC: 0.0000, F1: 0.6750

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.41024 | val 3.81097
  Epoch 017 - train 0.30663 | val 4.26908
  Classification -> best τ=0.735 (val F1=0.1884)
  Directional -> Accuracy: 0.5273, MCC: 0.0000, F1: 0.6905

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.51342 | val 0.85249

[I 2026-02-22 08:18:53,326] Trial 17 finished with value: 0.25017365700574073 and parameters: {'feature_set': 'sector_unified_emotion', 'model_type': 'GRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.1, 'batch_size': 16, 'learning_rate': 0.0025147028321731947, 'weight_decay': 0.0009740270783481967, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 15, 'max_epochs': 30, 'huber_delta': 0.7160109633544909, 'early_stopping_min_delta': 0.008942016953593163}. Best is trial 12 with value: 0.26451244235752075.

  Epoch 017 - train 0.39318 | val 1.09315
  Classification -> best τ=0.455 (val F1=0.3495)
  Directional -> Accuracy: 0.5167, MCC: 0.0062, F1: 0.0645

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.25017365700574073
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down', 'finbert_neutral']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.50340 | val 1.48022
  Epoch 011 - train 0.40054 | val 1.16351
  Classification -> best τ=0.590 (val F1=0.2919)
  Directional -> Accuracy: 0.5132, MCC: -0.1036, F1: 0.0976

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.45895 | val 1.59468
  Epoch 011 - train 0.33393 | val 2.31809
  Classification -> best τ=0.535 (val F1=0.1764)
  Directional -> Accuracy: 0.5111, MCC: 0.0260, F1: 0.5417

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.31253 | val 1.13787
  Epoch 011 - train 0.23301 | val 1.50315
  Classification -> best τ=0.445 (val F1=0.2871)
  Directional -> Accuracy: 0.5000, MCC: -0.0266, F1: 0.6102

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.42854 | val 3.75498
  Epoch 011 - train 0.30262 | val 6.75294
  Classification -> best τ=0.280 (val F1=0.1269)
  Directional -> Accuracy: 0.5405, MCC: 0.0000, F1: 0.7018

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.42079 | val 1.89319
  Epoch 013 - train 0.18823 | val 1.88752
  Classification -> best τ=0.770 (val F1=0.4611)
  Directional -> Accuracy: 0.6800, MCC: 0.4208, F1: 0.6000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.18431 | val 2.41789
  Epoch 011 - train 0.13875 | val 3.20866
  Classification -> best τ=0.555 (val F1=0.0635)
  Directional -> Accuracy: 0.5217, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.45016 | val 2.30219
  Epoch 011 - train 0.27222 | val 3.08229
  Classification -> best τ=0.140 (val F1=0.2101)
  Directional -> Accuracy: 0.3971, MCC: 0.0000, F1: 0.5684

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.08999 | val 9.84293
  Epoch 012 - train 0.00466 | val 10.20102
  Classification -> best τ=0.445 (val F1=0.2453)
  Directional -> Accuracy: 0.5238, MCC: 0.2161, F1: 0.6296

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.19917 | val 2.42806
  Epoch 011 - train 0.13795 | val 2.82646
  Classification -> best τ=0.365 (val F1=0.1402)
  Directional -> Accuracy: 0.4583, MCC: 0.1286, F1: 0.6176

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.41563 | val 2.22663
  Epoch 014 - train 0.19669 | val 3.05299
  Classification -> best τ=0.395 (val F1=0.2849)
  Directional -> Accuracy: 0.5362, MCC: 0.1287, F1: 0.5676

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.33614 | val 1.34383
  Epoch 011 - train 0.23096 | val 2.15530
  Classification -> best τ=0.460 (val F1=0.2204)
  Directional -> Accuracy: 0.5918, MCC: 0.1563, F1: 0.3333

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.46859 | val 1.67554
  Epoch 011 - train 0.42033 | val 3.16351
  Classification -> best τ=0.550 (val F1=0.2554)
  Directional -> Accuracy: 0.6316, MCC: 0.2693, F1: 0.6038

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.37563 | val 4.33625
  Epoch 013 - train 0.19961 | val 3.07214
  Classification -> best τ=0.685 (val F1=0.2083)
  Directional -> Accuracy: 0.4286, MCC: -0.1647, F1: 0.3333

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.52430 | val 1.18234
  Epoch 012 - train 0.47287 | val 0.88896
  Classification -> best τ=0.490 (val F1=0.2186)
  Directional -> Accuracy: 0.5667, MCC: 0.1361, F1: 0.6061

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.52274 | val 1.03663
  Epoch 011 - train 0.31873 | val 2.42353
  Classification -> best τ=0.465 (val F1=0.1347)
  Directional -> Accuracy: 0.4118, MCC: -0.1753, F1: 0.5714

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.49530 | val 1.53250
  Epoch 012 - train 0.30768 | val 1.83420
  Classification -> best τ=0.690 (val F1=0.3262)
  Directional -> Accuracy: 0.5217, MCC: 0.0490, F1: 0.5217

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.38660 | val 3.64941
  Epoch 011 - train 0.27644 | val 4.71750
  Classification -> best τ=0.310 (val F1=0.1336)
  Directional -> Accuracy: 0.5862, MCC: -0.0036, F1: 0.7209

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.36156 | val 5.08809
  Epoch 011 - train 0.30275 | val 6.92384
  Classification -> best τ=0.315 (val F1=0.2004)
  Directional -> Accuracy: 0.4000, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.44257 | val 2.24318
  Epoch 012 - train 0.33461 | val 2.65036
  Classification -> best τ=0.495 (val F1=0.3846)
  Directional -> Accuracy: 0.4844, MCC: 0.1315, F1: 0.2667

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.43599 | val 1.67901
  Epoch 011 - train 0.21989 | val 2.31119
  Classification -> best τ=0.435 (val F1=0.2204)
  Directional -> Accuracy: 0.5541, MCC: 0.0000, F1: 0.7130

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.53724 | val 1.35470
  Epoch 013 - train 0.48266 | val 1.08296
  Classification -> best τ=0.520 (val F1=0.2899)
  Directional -> Accuracy: 0.2766, MCC: -0.3935, F1: 0.1905

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.50388 | val 1.80447
  Epoch 011 - train 0.34590 | val 1.98655
  Classification -> best τ=0.510 (val F1=0.1542)
  Directional -> Accuracy: 0.3692, MCC: -0.2945, F1: 0.1633

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.41673 | val 1.17607
  Epoch 011 - train 0.27782 | val 1.13158
  Classification -> best τ=0.605 (val F1=0.3374)
  Directional -> Accuracy: 0.5088, MCC: 0.0572, F1: 0.4615

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.52936 | val 1.48773
  Epoch 011 - train 0.41155 | val 1.56331
  Classification -> best τ=0.450 (val F1=0.1874)
  Directional -> Accuracy: 0.5692, MCC: 0.1779, F1: 0.6410

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.48935 | val 2.03001
  Epoch 011 - train 0.28623 | val 2.21028
  Classification -> best τ=0.460 (val F1=0.4947)
  Directional -> Accuracy: 0.4727, MCC: 0.0199, F1: 0.2162

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.31313 | val 3.67824
  Epoch 012 - train 0.16632 | val 4.85115
  Classification -> best τ=0.600 (val F1=0.2241)
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.5938

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.34606 | val 3.35587
  Epoch 011 - train 0.34373 | val 3.14637
  Classification -> best τ=0.545 (val F1=0.0446)
  Directional -> Accuracy: 0.5238, MCC: 0.0694, F1: 0.5238

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.44787 | val 2.35432
  Epoch 012 - train 0.28195 | val 2.28009
  Classification -> best τ=0.195 (val F1=0.1718)
  Directional -> Accuracy: 0.4643, MCC: -0.0757, F1: 0.5000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.45111 | val 1.48746
  Epoch 012 - train 0.15336 | val 3.05947
  Classification -> best τ=0.610 (val F1=0.3427)
  Directional -> Accuracy: 0.6000, MCC: 0.1755, F1: 0.6800

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.39295 | val 1.26590
  Epoch 016 - train 0.12381 | val 1.31690
  Classification -> best τ=0.395 (val F1=0.3823)
  Directional -> Accuracy: 0.4762, MCC: -0.0608, F1: 0.3889

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.33858 | val 3.39994
  Epoch 011 - train 0.24002 | val 4.80390
  Classification -> best τ=0.565 (val F1=0.1329)
  Directional -> Accuracy: 0.4286, MCC: -0.1718, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.44789 | val 1.18361
  Epoch 011 - train 0.27085 | val 1.55966
  Classification -> best τ=0.620 (val F1=0.4023)
  Directional -> Accuracy: 0.4694, MCC: -0.0127, F1: 0.0714

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.49463 | val 1.62794
  Epoch 012 - train 0.35641 | val 0.92223
  Classification -> best τ=0.420 (val F1=0.2660)
  Directional -> Accuracy: 0.5556, MCC: 0.1803, F1: 0.4667

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.31660 | val 4.88466
  Epoch 011 - train 0.15679 | val 4.42190
  Classification -> best τ=0.505 (val F1=0.2324)
  Directional -> Accuracy: 0.5581, MCC: 0.2676, F1: 0.6885

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.40017 | val 0.94131
  Epoch 012 - train 0.23357 | val 1.31968
  Classification -> best τ=0.470 (val F1=0.3280)
  Directional -> Accuracy: 0.5303, MCC: 0.0907, F1: 0.5231

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.24756 | val 1.16931
  Epoch 014 - train 0.08392 | val 1.95286
  Classification -> best τ=0.415 (val F1=0.3985)
  Directional -> Accuracy: 0.4762, MCC: -0.0413, F1: 0.4500

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.41274 | val 1.23822
  Epoch 011 - train 0.32676 | val 0.98819
  Classification -> best τ=0.465 (val F1=0.2096)
  Directional -> Accuracy: 0.4464, MCC: -0.0852, F1: 0.5974

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.31203 | val 1.79346
  Epoch 012 - train 0.14702 | val 3.12353
  Classification -> best τ=0.360 (val F1=0.2118)
  Directional -> Accuracy: 0.6087, MCC: 0.0000, F1: 0.7568

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.36997 | val 2.45810
  Epoch 014 - train 0.06485 | val 2.47403
  Classification -> best τ=0.245 (val F1=0.5119)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.47134 | val 1.95454
  Epoch 011 - train 0.38489 | val 3.03045
  Classification -> best τ=0.600 (val F1=0.2620)
  Directional -> Accuracy: 0.5676, MCC: 0.1662, F1: 0.6444

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.39127 | val 1.56087
  Epoch 012 - train 0.15786 | val 2.12424
  Classification -> best τ=0.705 (val F1=0.2712)
  Directional -> Accuracy: 0.4667, MCC: -0.0709, F1: 0.2000

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.19023 | val 2.45389
  Epoch 011 - train 0.10390 | val 2.03416
  Classification -> best τ=0.570 (val F1=0.3118)
  Directional -> Accuracy: 0.4286, MCC: -0.0913, F1: 0.3333

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.23820 | val 2.65436
  Epoch 011 - train 0.12517 | val 2.22953
  Classification -> best τ=0.640 (val F1=0.5081)
  Directional -> Accuracy: 0.3958, MCC: 0.0222, F1: 0.5397

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.39511 | val 2.17415
  Epoch 011 - train 0.24088 | val 2.62513
  Classification -> best τ=0.565 (val F1=0.0644)
  Directional -> Accuracy: 0.3273, MCC: -0.3614, F1: 0.3934

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.25616 | val 3.74165
  Epoch 011 - train 0.17077 | val 4.28899
  Classification -> best τ=0.465 (val F1=0.1796)
  Directional -> Accuracy: 0.5179, MCC: 0.0000, F1: 0.0000

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.44297 | val 1.47616
  Epoch 012 - train 0.24591 | val 1.39786
  Classification -> best τ=0.490 (val F1=0.2719)
  Directional -> Accuracy: 0.6226, MCC: 0.2468, F1: 0.6154

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.46321 | val 3.77307
  Epoch 011 - train 0.30352 | val 7.05957
  Classification -> best τ=0.690 (val F1=0.0684)
  Directional -> Accuracy: 0.5273, MCC: 0.0258, F1: 0.6486

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.46903 | val 1.30632
  Epoch 012 - train 0.27227 | val 3.41933
  Classification -> best τ=0.460 (val F1=0.3056)
  Directional -> Accuracy: 0.5167, MCC: 0.0111, F1: 0.1714

[I 2026-02-22 08:22:17,067] Trial 18 finished with value: 0.2532371550085096 and parameters: {'feature_set': 'finbert', 'model_type': 'BiLSTM', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 1, 'inter_rnn_drop': 0.4, 'dropout': 0.0, 'batch_size': 16, 'learning_rate': 0.008997067003620652, 'weight_decay': 3.412742580534918e-05, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 1.086743005817563, 'early_stopping_min_delta': 0.007050944772069609}. Best is trial 12 with value: 0.26451244235752075.

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2532371550085096
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 30
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down', 'finbert_neutral']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.60025 | val 0.82532
  Epoch 011 - train 0.59135 | val 0.84311
  Classification -> best τ=0.620 (val F1=0.2705)
  Directional -> Accuracy: 0.5067, MCC: -0.1080, F1: 0.0976

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 106). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.54831 | val 0.78323
  Epoch 011 - train 0.54917 | val 0.80216
  Classification -> best τ=0.480 (val F1=0.1430)
  Directional -> Accuracy: 0.6136, MCC: 0.1833, F1: 0.7536

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 106). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.59984 | val 0.63518
  Epoch 019 - train 0.53019 | val 0.69882
  Classification -> best τ=0.650 (val F1=0.3961)
  Directional -> Accuracy: 0.3778, MCC: -0.2357, F1: 0.3000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.62184 | val 1.24402
  Epoch 011 - train 0.63222 | val 1.32246
  Classification -> best τ=0.500 (val F1=0.0288)
  Directional -> Accuracy: 0.5342, MCC: 0.0000, F1: 0.6964

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.53534 | val 0.74011
  Epoch 012 - train 0.51208 | val 0.73381
  Classification -> best τ=0.550 (val F1=0.3061)
  Directional -> Accuracy: 0.5918, MCC: 0.2539, F1: 0.4118

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.53403 | val 0.70682
  Epoch 011 - train 0.52704 | val 0.68424
  Classification -> best τ=0.535 (val F1=0.2379)
  Directional -> Accuracy: 0.5333, MCC: 0.0667, F1: 0.3226

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.61044 | val 0.91255
  Epoch 011 - train 0.59225 | val 0.94743
  Classification -> best τ=0.460 (val F1=0.1510)
  Directional -> Accuracy: 0.5075, MCC: 0.0422, F1: 0.4923

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 106). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 106). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.54376 | val 2.55056
  Epoch 011 - train 0.52293 | val 2.55124
  Classification -> best τ=0.520 (val F1=0.1491)
  Directional -> Accuracy: 0.5854, MCC: 0.1635, F1: 0.5405

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.61141 | val 0.75295
  Epoch 011 - train 0.60032 | val 0.76417
  Classification -> best τ=0.460 (val F1=0.1974)
  Directional -> Accuracy: 0.4468, MCC: 0.0000, F1: 0.6176

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 106). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 106). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 106). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.53926 | val 1.19569
  Epoch 011 - train 0.52561 | val 1.28955
  Classification -> best τ=0.430 (val F1=0.1846)
  Directional -> Accuracy: 0.4265, MCC: 0.0000, F1: 0.5979

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.59038 | val 1.08946
  Epoch 011 - train 0.57592 | val 1.14719
  Classification -> best τ=0.580 (val F1=0.0913)
  Directional -> Accuracy: 0.5833, MCC: 0.1496, F1: 0.3333

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.56439 | val 1.05724
  Epoch 011 - train 0.57693 | val 1.06082
  Classification -> best τ=0.455 (val F1=0.0965)
  Directional -> Accuracy: 0.5536, MCC: 0.1995, F1: 0.6988

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 106). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.56721 | val 2.07310
  Epoch 011 - train 0.56053 | val 2.21150
  Classification -> best τ=0.310 (val F1=0.1945)
  Directional -> Accuracy: 0.4898, MCC: 0.0000, F1: 0.6575

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 106). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.63349 | val 0.69972
  Epoch 018 - train 0.54626 | val 0.81244
  Classification -> best τ=0.465 (val F1=0.2768)
  Directional -> Accuracy: 0.5593, MCC: 0.1267, F1: 0.6486

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.56489 | val 1.01710
  Epoch 011 - train 0.56562 | val 0.99571
  Classification -> best τ=0.605 (val F1=0.1516)
  Directional -> Accuracy: 0.6000, MCC: 0.1842, F1: 0.2308

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.59178 | val 1.12006
  Epoch 011 - train 0.59240 | val 1.12762
  Classification -> best τ=0.350 (val F1=0.2526)
  Directional -> Accuracy: 0.5441, MCC: 0.1296, F1: 0.6990

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 106). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.59794 | val 1.23774
  Epoch 011 - train 0.58886 | val 1.25970
  Classification -> best τ=0.680 (val F1=0.2335)
  Directional -> Accuracy: 0.3860, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.56331 | val 1.14330
  Epoch 011 - train 0.55679 | val 1.21342
  Classification -> best τ=0.300 (val F1=0.1547)
  Directional -> Accuracy: 0.5676, MCC: 0.0451, F1: 0.6800

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.56945 | val 0.72063
  Epoch 011 - train 0.58175 | val 0.71572
  Classification -> best τ=0.565 (val F1=0.1853)
  Directional -> Accuracy: 0.4603, MCC: 0.1268, F1: 0.1905

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 106). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.59161 | val 0.71698
  Epoch 011 - train 0.56766 | val 0.71903
  Classification -> best τ=0.525 (val F1=0.1892)
  Directional -> Accuracy: 0.4932, MCC: 0.1088, F1: 0.2128

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.57515 | val 1.12777
  Epoch 011 - train 0.54811 | val 1.17661
  Classification -> best τ=0.495 (val F1=0.2159)
  Directional -> Accuracy: 0.5000, MCC: 0.1075, F1: 0.4390

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 106). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 106). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 106). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.58936 | val 1.60506
  Epoch 011 - train 0.57133 | val 1.63533
  Classification -> best τ=0.605 (val F1=0.1914)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.59235 | val 1.09245
  Epoch 011 - train 0.57106 | val 1.12735
  Classification -> best τ=0.505 (val F1=0.1879)
  Directional -> Accuracy: 0.6071, MCC: 0.2274, F1: 0.6207

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.56434 | val 1.22648
  Epoch 011 - train 0.55923 | val 1.30568
  Classification -> best τ=0.375 (val F1=0.1932)
  Directional -> Accuracy: 0.5156, MCC: 0.0333, F1: 0.5079

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.55618 | val 0.70503
  Epoch 013 - train 0.52069 | val 0.70748
  Classification -> best τ=0.525 (val F1=0.4542)
  Directional -> Accuracy: 0.4815, MCC: 0.0266, F1: 0.2222

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.54937 | val 0.77288
  Epoch 011 - train 0.56690 | val 0.79128
  Classification -> best τ=0.470 (val F1=0.1355)
  Directional -> Accuracy: 0.4884, MCC: 0.0889, F1: 0.5769

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.62700 | val 0.77681
  Epoch 011 - train 0.61083 | val 0.78437
  Classification -> best τ=0.530 (val F1=0.1982)
  Directional -> Accuracy: 0.4286, MCC: -0.1061, F1: 0.4167

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.60921 | val 0.87879
  Epoch 011 - train 0.59672 | val 0.88203
  Classification -> best τ=0.495 (val F1=0.2111)
  Directional -> Accuracy: 0.5636, MCC: 0.1047, F1: 0.6364

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.57950 | val 0.74430
  Epoch 015 - train 0.53804 | val 0.70873
  Classification -> best τ=0.410 (val F1=0.3708)
  Directional -> Accuracy: 0.6579, MCC: 0.3361, F1: 0.7547

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.58604 | val 1.71574
  Epoch 011 - train 0.56193 | val 1.77078
  Classification -> best τ=0.560 (val F1=0.3508)
  Directional -> Accuracy: 0.5122, MCC: 0.0000, F1: 0.0000

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.62335 | val 0.87646
  Epoch 011 - train 0.60940 | val 0.88888
  Classification -> best τ=0.530 (val F1=0.2339)
  Directional -> Accuracy: 0.5610, MCC: 0.0000, F1: 0.7188

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.54115 | val 0.90214
  Epoch 011 - train 0.50913 | val 0.89970
  Classification -> best τ=0.510 (val F1=0.3014)
  Directional -> Accuracy: 0.5208, MCC: 0.0000, F1: 0.6849

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.56167 | val 0.86153
  Epoch 012 - train 0.54011 | val 0.88464
  Classification -> best τ=0.320 (val F1=0.3210)
  Directional -> Accuracy: 0.5352, MCC: 0.1612, F1: 0.4211

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 106). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.54807 | val 0.83246
  Epoch 011 - train 0.57011 | val 0.83470
  Classification -> best τ=0.520 (val F1=0.2712)
  Directional -> Accuracy: 0.5238, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for PCG (101 < 106). Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.56509 | val 0.94743
  Epoch 011 - train 0.54833 | val 0.96644
  Classification -> best τ=0.385 (val F1=0.4004)
  Directional -> Accuracy: 0.6154, MCC: 0.2268, F1: 0.6479

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.55386 | val 0.65327
  Epoch 016 - train 0.46699 | val 0.70088
  Classification -> best τ=0.535 (val F1=0.4384)
  Directional -> Accuracy: 0.5750, MCC: 0.2023, F1: 0.4516

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.54018 | val 0.76503
  Epoch 011 - train 0.54810 | val 0.76795
  Classification -> best τ=0.445 (val F1=0.2089)
  Directional -> Accuracy: 0.5091, MCC: 0.1617, F1: 0.6400

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.52129 | val 1.46742
  Epoch 011 - train 0.50259 | val 1.55442
  Classification -> best τ=0.520 (val F1=0.2626)
  Directional -> Accuracy: 0.6222, MCC: 0.0000, F1: 0.7671

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 106). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 106). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 106). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 106). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.54691 | val 0.68152
  Epoch 019 - train 0.45160 | val 0.74688
  Classification -> best τ=0.680 (val F1=0.4242)
  Directional -> Accuracy: 0.3261, MCC: 0.0000, F1: 0.4918

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 106). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 106). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 106). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.55817 | val 1.13533
  Epoch 011 - train 0.56828 | val 1.15421
  Classification -> best τ=0.475 (val F1=0.2058)
  Directional -> Accuracy: 0.5068, MCC: 0.0505, F1: 0.6538

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 106). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 106). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 106). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 106). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.58999 | val 0.78324
  Epoch 011 - train 0.59839 | val 0.78086
  Classification -> best τ=0.515 (val F1=0.3536)
  Directional -> Accuracy: 0.4545, MCC: -0.1179, F1: 0.2000

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.57036 | val 0.79626
  Epoch 011 - train 0.57541 | val 0.79937
  Classification -> best τ=0.505 (val F1=0.2014)
  Directional -> Accuracy: 0.4390, MCC: -0.1280, F1: 0.4889

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.56072 | val 0.92068
  Epoch 011 - train 0.54664 | val 0.91336
  Classification -> best τ=0.630 (val F1=0.0422)
  Directional -> Accuracy: 0.3696, MCC: 0.0000, F1: 0.5397

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.59055 | val 1.33485
  Epoch 011 - train 0.59761 | val 1.37963
  Classification -> best τ=0.480 (val F1=0.1445)
  Directional -> Accuracy: 0.5741, MCC: 0.1109, F1: 0.6667

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.58328 | val 1.57133
  Epoch 011 - train 0.56441 | val 1.70369
  Classification -> best τ=0.580 (val F1=0.2873)
  Directional -> Accuracy: 0.4909, MCC: 0.0000, F1: 0.6585

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.58733 | val 0.71291
  Epoch 011 - train 0.55541 | val 0.71326
  Classification -> best τ=0.555 (val F1=0.2376)
  Directional -> Accuracy: 0.5962, MCC: 0.1936, F1: 0.5714

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.54562 | val 0.76672
  Epoch 011 - train 0.57396 | val 0.78477
  Classification -> best τ=0.510 (val F1=0.2078)
  Directional -> Accuracy: 0.5370, MCC: 0.1425, F1: 0.6914

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.59061 | val 0.77830

[I 2026-02-22 08:26:21,762] Trial 19 finished with value: 0.2310333584525666 and parameters: {'feature_set': 'finbert', 'model_type': 'BiGRU', 'sequence_length': 30, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.2, 'batch_size': 16, 'learning_rate': 0.0006205175473588517, 'weight_decay': 0.00014938271286543537, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 50, 'huber_delta': 1.5240097819366896, 'early_stopping_min_delta': 0.007319991857626832}. Best is trial 12 with value: 0.26451244235752075.

  Epoch 011 - train 0.57348 | val 0.86626
  Classification -> best τ=0.460 (val F1=0.1479)
  Directional -> Accuracy: 0.5254, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2310333584525666
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'emotion_anger', 'emotion_disgust', 'emotion_fear', 'emotion_joy', 'emotion_neutral', 'emotion_sadness', 'emotion_surprize', 'emotion_anger_pct', 'emotion_disgust_pct', 'emotion_fear_pct', 'emotion_joy_pct', 'emotion_neutral_pct', 'emotion_sadness_pct', 'emotion_surprize_pct']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.64191 | val 0.72588
  Epoch 016 - train 0.63342 | val 0.74429
  Classification -> best τ=0.495 (val F1=0.2135)
  Directional -> Accuracy: 0.5195, MCC: -0.0327, F1: 0.2128

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.60830 | val 0.85970
  Epoch 016 - train 0.59059 | val 0.91954
  Classification -> best τ=0.475 (val F1=0.2495)
  Directional -> Accuracy: 0.6087, MCC: 0.1962, F1: 0.7353

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.64721 | val 0.67687
  Epoch 020 - train 0.60700 | val 0.68272
  Epoch 026 - train 0.60286 | val 0.68161
  Classification -> best τ=0.590 (val F1=0.3671)
  Directional -> Accuracy: 0.5957, MCC: 0.2793, F1: 0.4571

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.64310 | val 0.84434
  Epoch 016 - train 0.63493 | val 0.89761
  Classification -> best τ=0.435 (val F1=0.0066)
  Directional -> Accuracy: 0.6133, MCC: 0.2076, F1: 0.6882

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.61448 | val 0.64904
  Epoch 019 - train 0.56784 | val 0.68147
  Classification -> best τ=0.540 (val F1=0.4098)
  Directional -> Accuracy: 0.6078, MCC: 0.3034, F1: 0.4737

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.59289 | val 0.91461
  Epoch 016 - train 0.58468 | val 0.98906
  Classification -> best τ=0.510 (val F1=0.0529)
  Directional -> Accuracy: 0.4894, MCC: -0.0183, F1: 0.5200

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.63012 | val 0.86616
  Epoch 016 - train 0.62874 | val 0.87981
  Classification -> best τ=0.475 (val F1=0.1840)
  Directional -> Accuracy: 0.4058, MCC: 0.0000, F1: 0.5773

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.60646 | val 0.99715
  Epoch 016 - train 0.59783 | val 1.10378
  Classification -> best τ=0.465 (val F1=0.1752)
  Directional -> Accuracy: 0.4545, MCC: 0.0100, F1: 0.5385

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.62985 | val 0.71056
  Epoch 019 - train 0.61295 | val 0.71151
  Classification -> best τ=0.560 (val F1=0.3459)
  Directional -> Accuracy: 0.5306, MCC: -0.1303, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.62934 | val 0.74026
  Epoch 016 - train 0.62122 | val 0.75670
  Classification -> best τ=0.515 (val F1=0.2220)
  Directional -> Accuracy: 0.4286, MCC: -0.0355, F1: 0.5833

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.62211 | val 1.15789
  Epoch 016 - train 0.61979 | val 1.22090
  Classification -> best τ=0.600 (val F1=0.0417)
  Directional -> Accuracy: 0.4600, MCC: -0.1605, F1: 0.1818

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.63676 | val 0.97507
  Epoch 016 - train 0.62392 | val 1.07578
  Classification -> best τ=0.520 (val F1=0.0325)
  Directional -> Accuracy: 0.6379, MCC: 0.2843, F1: 0.5882

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.60111 | val 1.13766
  Epoch 016 - train 0.60194 | val 1.21680
  Classification -> best τ=0.475 (val F1=0.1710)
  Directional -> Accuracy: 0.3721, MCC: -0.3078, F1: 0.5424

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.63742 | val 0.68179
  Epoch 016 - train 0.62420 | val 0.67933
  Classification -> best τ=0.455 (val F1=0.3268)
  Directional -> Accuracy: 0.5902, MCC: 0.1848, F1: 0.5614

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.62961 | val 0.81136
  Epoch 016 - train 0.60888 | val 0.80625
  Classification -> best τ=0.465 (val F1=0.1164)
  Directional -> Accuracy: 0.5577, MCC: 0.1018, F1: 0.1481

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.60306 | val 0.74857
  Epoch 016 - train 0.60754 | val 0.77120
  Classification -> best τ=0.455 (val F1=0.2172)
  Directional -> Accuracy: 0.5429, MCC: 0.0000, F1: 0.7037

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.61378 | val 1.23168
  Epoch 016 - train 0.61842 | val 1.32935
  Classification -> best τ=0.565 (val F1=0.1809)
  Directional -> Accuracy: 0.3898, MCC: 0.0189, F1: 0.1000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.65043 | val 0.70339
  Epoch 016 - train 0.63650 | val 0.70739
  Classification -> best τ=0.520 (val F1=0.0570)
  Directional -> Accuracy: 0.3947, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.60919 | val 0.96750
  Epoch 016 - train 0.59772 | val 1.02028
  Classification -> best τ=0.495 (val F1=0.2818)
  Directional -> Accuracy: 0.4615, MCC: 0.1854, F1: 0.1463

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.63785 | val 0.75870
  Epoch 016 - train 0.61440 | val 0.74628
  Classification -> best τ=0.515 (val F1=0.1486)
  Directional -> Accuracy: 0.4667, MCC: -0.0938, F1: 0.5455

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.62338 | val 0.74017
  Epoch 016 - train 0.60713 | val 0.74431
  Classification -> best τ=0.440 (val F1=0.1945)
  Directional -> Accuracy: 0.5208, MCC: 0.1237, F1: 0.5106

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.64744 | val 0.76428
  Epoch 016 - train 0.62307 | val 0.78893
  Classification -> best τ=0.520 (val F1=0.0284)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.64760 | val 0.75880
  Epoch 018 - train 0.63514 | val 0.78335
  Classification -> best τ=0.645 (val F1=0.3947)
  Directional -> Accuracy: 0.5172, MCC: 0.1165, F1: 0.4167

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.61575 | val 0.90926
  Epoch 016 - train 0.60193 | val 0.97778
  Classification -> best τ=0.445 (val F1=0.3348)
  Directional -> Accuracy: 0.4848, MCC: 0.0081, F1: 0.5952

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.63093 | val 0.65808
  Epoch 020 - train 0.59502 | val 0.67843
  Classification -> best τ=0.555 (val F1=0.3320)
  Directional -> Accuracy: 0.5000, MCC: 0.1552, F1: 0.2222

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.61694 | val 0.72519
  Epoch 016 - train 0.60551 | val 0.73172
  Classification -> best τ=0.505 (val F1=0.3464)
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.64095 | val 0.98085
  Epoch 016 - train 0.62069 | val 1.01640
  Classification -> best τ=0.490 (val F1=0.3212)
  Directional -> Accuracy: 0.4186, MCC: -0.2040, F1: 0.5098

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.63370 | val 0.82534
  Epoch 016 - train 0.61957 | val 0.86277
  Classification -> best τ=0.490 (val F1=0.0825)
  Directional -> Accuracy: 0.5789, MCC: 0.3571, F1: 0.4000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.65884 | val 0.74112
  Epoch 016 - train 0.62089 | val 0.75696
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.63016 | val 0.96670
  Epoch 016 - train 0.64420 | val 1.02178
  Classification -> best τ=0.505 (val F1=0.1574)
  Directional -> Accuracy: 0.4884, MCC: -0.0128, F1: 0.5926

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.64969 | val 0.71436
  Epoch 016 - train 0.64065 | val 0.72418
  Classification -> best τ=0.530 (val F1=0.2533)
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.60756 | val 0.83623
  Epoch 016 - train 0.60319 | val 0.86786
  Classification -> best τ=0.460 (val F1=0.0770)
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.61550 | val 0.61099
  Epoch 020 - train 0.58265 | val 0.61228
  Epoch 023 - train 0.56726 | val 0.61162
  Classification -> best τ=0.365 (val F1=0.4013)
  Directional -> Accuracy: 0.5068, MCC: 0.1076, F1: 0.3571

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.64594 | val 0.74981
  Epoch 016 - train 0.59872 | val 0.76303
  Classification -> best τ=0.475 (val F1=0.4082)
  Directional -> Accuracy: 0.5526, MCC: 0.1443, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.60844 | val 1.01629
  Epoch 016 - train 0.61396 | val 1.02152
  Classification -> best τ=0.540 (val F1=0.1283)
  Directional -> Accuracy: 0.5227, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.61974 | val 0.68432
  Epoch 017 - train 0.61242 | val 0.68710
  Classification -> best τ=0.415 (val F1=0.3687)
  Directional -> Accuracy: 0.5224, MCC: 0.1217, F1: 0.4286

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.58257 | val 0.73620
  Epoch 016 - train 0.57895 | val 0.76553
  Classification -> best τ=0.490 (val F1=0.2986)
  Directional -> Accuracy: 0.5349, MCC: 0.0716, F1: 0.5238

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.58876 | val 0.81606
  Epoch 016 - train 0.59430 | val 0.82388
  Classification -> best τ=0.510 (val F1=0.1738)
  Directional -> Accuracy: 0.5614, MCC: 0.1124, F1: 0.4681

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.63096 | val 0.87986
  Epoch 016 - train 0.60458 | val 0.93538
  Classification -> best τ=0.575 (val F1=0.2676)
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.66173 | val 0.71885
  Epoch 016 - train 0.64869 | val 0.71151
  Classification -> best τ=0.530 (val F1=0.1477)
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.62579 | val 0.81878
  Epoch 016 - train 0.61107 | val 0.87183
  Classification -> best τ=0.475 (val F1=0.0134)
  Directional -> Accuracy: 0.4474, MCC: -0.1116, F1: 0.4878

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.60417 | val 0.98171
  Epoch 016 - train 0.58640 | val 1.01408
  Classification -> best τ=0.525 (val F1=0.1964)
  Directional -> Accuracy: 0.5067, MCC: 0.1147, F1: 0.6667

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.62220 | val 0.68883
  Epoch 019 - train 0.61264 | val 0.71890
  Classification -> best τ=0.475 (val F1=0.4538)
  Directional -> Accuracy: 0.5106, MCC: 0.0111, F1: 0.6230

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.60790 | val 0.83151
  Epoch 016 - train 0.59660 | val 0.87300
  Classification -> best τ=0.480 (val F1=0.3967)
  Directional -> Accuracy: 0.4318, MCC: 0.0000, F1: 0.0000

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.65643 | val 0.80213
  Epoch 016 - train 0.64480 | val 0.81846
  Classification -> best τ=0.480 (val F1=0.1443)
  Directional -> Accuracy: 0.6122, MCC: 0.0861, F1: 0.2400

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.62511 | val 0.66231
  Epoch 020 - train 0.59900 | val 0.68222
  Epoch 021 - train 0.60504 | val 0.68469
  Classification -> best τ=0.540 (val F1=0.2194)
  Directional -> Accuracy: 0.5536, MCC: 0.0812, F1: 0.6835

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.61539 | val 0.87861
  Epoch 016 - train 0.61090 | val 0.88994
  Classification -> best τ=0.520 (val F1=0.3429)
  Directional -> Accuracy: 0.5088, MCC: 0.0590, F1: 0.6111

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.64954 | val 0.75248
  Epoch 016 - train 0.64745 | val 0.75931
  Classification -> best τ=0.520 (val F1=0.2365)
  Directional -> Accuracy: 0.5000, MCC: -0.0225, F1: 0.6087

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.62297 | val 0.70217
  Epoch 020 - train 0.59330 | val 0.68923
  Epoch 027 - train 0.59026 | val 0.69709
  Classification -> best τ=0.330 (val F1=0.2712)
  Directional -> Accuracy: 0.5000, MCC: -0.1301, F1: 0.6667

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.63995 | val 0.72733

[I 2026-02-22 08:31:37,871] Trial 20 finished with value: 0.2188227182010606 and parameters: {'feature_set': 'emotion', 'model_type': 'BiGRU', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.4, 'dropout': 0.1, 'batch_size': 16, 'learning_rate': 0.00011183188252158728, 'weight_decay': 2.754775024910627e-06, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 15, 'max_epochs': 30, 'huber_delta': 1.930311228884205, 'early_stopping_min_delta': 0.009345705068026861}. Best is trial 12 with value: 0.26451244235752075.

  Epoch 016 - train 0.63320 | val 0.73149
  Classification -> best τ=0.505 (val F1=0.1498)
  Directional -> Accuracy: 0.5246, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2188227182010606
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 6
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.51487 | val 1.86466
  Epoch 011 - train 0.52299 | val 1.54871
  Classification -> best τ=0.835 (val F1=0.1903)
  Directional -> Accuracy: 0.5570, MCC: 0.0000, F1: 0.0000

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 82). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.41252 | val 1.24415
  Epoch 011 - train 0.37764 | val 1.16135
  Classification -> best τ=0.550 (val F1=0.1654)
  Directional -> Accuracy: 0.6250, MCC: 0.3485, F1: 0.5500

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 82). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.44727 | val 2.20810
  Epoch 011 - train 0.44167 | val 2.28598
  Classification -> best τ=0.495 (val F1=0.2274)
  Directional -> Accuracy: 0.4694, MCC: -0.0554, F1: 0.4583

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.54442 | val 0.69759
  Epoch 020 - train 0.30595 | val 1.43554
  Classification -> best τ=0.650 (val F1=0.2888)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.42886 | val 1.79972
  Epoch 011 - train 0.39728 | val 1.89319
  Classification -> best τ=0.535 (val F1=0.4237)
  Directional -> Accuracy: 0.5849, MCC: 0.2097, F1: 0.5000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.40190 | val 1.43788
  Epoch 011 - train 0.41599 | val 1.67070
  Classification -> best τ=0.515 (val F1=0.2343)
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.48215 | val 1.61362
  Epoch 011 - train 0.45922 | val 1.65797
  Classification -> best τ=0.415 (val F1=0.1963)
  Directional -> Accuracy: 0.5070, MCC: 0.1493, F1: 0.5882

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 82). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 82). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.37994 | val 0.75419
  Epoch 015 - train 0.25895 | val 1.09649
  Classification -> best τ=0.400 (val F1=0.4750)
  Directional -> Accuracy: 0.5957, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.44114 | val 1.29221
  Epoch 011 - train 0.43518 | val 1.03220
  Classification -> best τ=0.545 (val F1=0.2203)
  Directional -> Accuracy: 0.6512, MCC: 0.2950, F1: 0.5946

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 82). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 82). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.42863 | val 1.30781
  Epoch 011 - train 0.38295 | val 1.43101
  Classification -> best τ=0.385 (val F1=0.1696)
  Directional -> Accuracy: 0.4444, MCC: 0.1032, F1: 0.6078

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.45855 | val 0.87647
  Epoch 012 - train 0.37456 | val 0.92757
  Classification -> best τ=0.520 (val F1=0.1784)
  Directional -> Accuracy: 0.5577, MCC: 0.1255, F1: 0.5660

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.56033 | val 1.11851
  Epoch 011 - train 0.52007 | val 1.33375
  Classification -> best τ=0.495 (val F1=0.1231)
  Directional -> Accuracy: 0.6500, MCC: 0.3085, F1: 0.6866

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.40564 | val 1.01076
  Epoch 011 - train 0.37990 | val 1.17027
  Classification -> best τ=0.515 (val F1=0.1868)
  Directional -> Accuracy: 0.4667, MCC: -0.0653, F1: 0.4545

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 82). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.45681 | val 1.04745
  Epoch 011 - train 0.42092 | val 1.01764
  Classification -> best τ=0.520 (val F1=0.3510)
  Directional -> Accuracy: 0.5238, MCC: 0.0458, F1: 0.4828

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.47796 | val 2.74302
  Epoch 011 - train 0.40573 | val 3.59951
  Classification -> best τ=0.665 (val F1=0.2291)
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.51928 | val 1.35631
  Epoch 011 - train 0.47093 | val 1.30257
  Classification -> best τ=0.665 (val F1=0.2578)
  Directional -> Accuracy: 0.5417, MCC: 0.0791, F1: 0.5714

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.43270 | val 2.05810
  Epoch 011 - train 0.40720 | val 2.39337
  Classification -> best τ=0.420 (val F1=0.1341)
  Directional -> Accuracy: 0.6066, MCC: 0.1757, F1: 0.6757

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.49439 | val 1.15298
  Epoch 011 - train 0.46804 | val 1.30398
  Classification -> best τ=0.320 (val F1=0.2052)
  Directional -> Accuracy: 0.6026, MCC: 0.0000, F1: 0.7520

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.46272 | val 0.98664
  Epoch 011 - train 0.45297 | val 0.92990
  Classification -> best τ=0.555 (val F1=0.1654)
  Directional -> Accuracy: 0.4627, MCC: 0.1255, F1: 0.1818

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 82). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.46335 | val 1.06839
  Epoch 011 - train 0.45029 | val 1.10520
  Classification -> best τ=0.445 (val F1=0.2424)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.39660 | val 1.12032
  Epoch 011 - train 0.38622 | val 1.18288
  Classification -> best τ=0.480 (val F1=0.2415)
  Directional -> Accuracy: 0.3800, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 82). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 82). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 82). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.45314 | val 1.33944
  Epoch 011 - train 0.43518 | val 1.33791
  Classification -> best τ=0.505 (val F1=0.2081)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.49025 | val 1.35895
  Epoch 011 - train 0.47794 | val 1.32596
  Classification -> best τ=0.660 (val F1=0.2763)
  Directional -> Accuracy: 0.5333, MCC: 0.1757, F1: 0.4400

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.50622 | val 0.71247
  Epoch 011 - train 0.45499 | val 0.72552
  Classification -> best τ=0.445 (val F1=0.1654)
  Directional -> Accuracy: 0.5735, MCC: 0.1683, F1: 0.6329

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.48620 | val 1.59619
  Epoch 012 - train 0.38640 | val 1.58333
  Classification -> best τ=0.580 (val F1=0.4633)
  Directional -> Accuracy: 0.5517, MCC: 0.1844, F1: 0.4348

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.39349 | val 1.99069
  Epoch 011 - train 0.38629 | val 2.07770
  Classification -> best τ=0.550 (val F1=0.2106)
  Directional -> Accuracy: 0.4286, MCC: -0.1667, F1: 0.3333

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.47071 | val 0.73664
  Epoch 011 - train 0.48378 | val 0.76824
  Classification -> best τ=0.510 (val F1=0.1410)
  Directional -> Accuracy: 0.4222, MCC: 0.1231, F1: 0.0714

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.50384 | val 1.43412
  Epoch 011 - train 0.46314 | val 1.42834
  Classification -> best τ=0.355 (val F1=0.2312)
  Directional -> Accuracy: 0.5932, MCC: 0.1532, F1: 0.7209

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.41532 | val 2.73910
  Epoch 011 - train 0.39041 | val 2.61613
  Classification -> best τ=0.410 (val F1=0.3185)
  Directional -> Accuracy: 0.5000, MCC: 0.0021, F1: 0.5000

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.42632 | val 1.17043
  Epoch 012 - train 0.39077 | val 0.96103
  Classification -> best τ=0.510 (val F1=0.2498)
  Directional -> Accuracy: 0.5870, MCC: 0.1754, F1: 0.5581

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.48222 | val 1.46576
  Epoch 011 - train 0.49472 | val 1.52190
  Classification -> best τ=0.500 (val F1=0.1370)
  Directional -> Accuracy: 0.5652, MCC: 0.1006, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.42302 | val 1.14938
  Epoch 011 - train 0.42509 | val 1.02048
  Classification -> best τ=0.605 (val F1=0.2262)
  Directional -> Accuracy: 0.4615, MCC: -0.0963, F1: 0.5484

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.47249 | val 1.18037
  Epoch 011 - train 0.43554 | val 1.32316
  Classification -> best τ=0.455 (val F1=0.2843)
  Directional -> Accuracy: 0.4933, MCC: 0.1323, F1: 0.2400

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 82). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.41306 | val 0.81352
  Epoch 016 - train 0.32055 | val 1.27595
  Classification -> best τ=0.655 (val F1=0.3477)
  Directional -> Accuracy: 0.6098, MCC: 0.2605, F1: 0.6800

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.40680 | val 1.85615
  Epoch 011 - train 0.36687 | val 1.56162
  Classification -> best τ=0.555 (val F1=0.1646)
  Directional -> Accuracy: 0.5217, MCC: 0.0063, F1: 0.3529

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.47362 | val 0.86949
  Epoch 011 - train 0.43302 | val 0.86816
  Classification -> best τ=0.460 (val F1=0.3063)
  Directional -> Accuracy: 0.6087, MCC: 0.2179, F1: 0.6400

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.41330 | val 0.97581
  Epoch 011 - train 0.40222 | val 0.97820
  Classification -> best τ=0.435 (val F1=0.4328)
  Directional -> Accuracy: 0.4444, MCC: -0.1129, F1: 0.4681

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.50921 | val 1.29300
  Epoch 011 - train 0.46906 | val 1.40946
  Classification -> best τ=0.470 (val F1=0.1830)
  Directional -> Accuracy: 0.5085, MCC: 0.0400, F1: 0.5797

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.39653 | val 1.64265
  Epoch 011 - train 0.39157 | val 1.80632
  Classification -> best τ=0.430 (val F1=0.2032)
  Directional -> Accuracy: 0.6122, MCC: 0.0000, F1: 0.7595

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 82). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 82). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 82). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 82). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.45891 | val 0.85616
  Epoch 012 - train 0.41645 | val 0.84135
  Classification -> best τ=0.485 (val F1=0.3420)
  Directional -> Accuracy: 0.3571, MCC: 0.1104, F1: 0.5091

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 82). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.38568 | val 1.85426
  Epoch 011 - train 0.34897 | val 2.01713
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5122, MCC: 0.0000, F1: 0.6774

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 82). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 82). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.47466 | val 1.55736
  Epoch 011 - train 0.45835 | val 1.82386
  Classification -> best τ=0.245 (val F1=0.2601)
  Directional -> Accuracy: 0.5065, MCC: 0.0000, F1: 0.6724

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 82). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 82). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.47851 | val 2.15075
  Epoch 011 - train 0.44254 | val 2.13146
  Classification -> best τ=0.545 (val F1=0.0060)
  Directional -> Accuracy: 0.5714, MCC: 0.1782, F1: 0.6557

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.28392 | val 3.87123
  Epoch 011 - train 0.24227 | val 4.14007
  Classification -> best τ=0.590 (val F1=0.4196)
  Directional -> Accuracy: 0.5106, MCC: 0.0444, F1: 0.5106

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.42797 | val 0.89729
  Epoch 011 - train 0.39420 | val 0.95463
  Classification -> best τ=0.525 (val F1=0.1782)
  Directional -> Accuracy: 0.4286, MCC: 0.2067, F1: 0.5556

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.53322 | val 0.86926
  Epoch 011 - train 0.52059 | val 0.90861
  Classification -> best τ=0.650 (val F1=0.1704)
  Directional -> Accuracy: 0.4483, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.37249 | val 1.59241
  Epoch 011 - train 0.36261 | val 1.67237
  Classification -> best τ=0.690 (val F1=0.2818)
  Directional -> Accuracy: 0.4915, MCC: -0.0046, F1: 0.6429

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.49695 | val 1.70192
  Epoch 011 - train 0.48277 | val 1.78453
  Classification -> best τ=0.385 (val F1=0.2143)
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.40362 | val 2.73700
  Epoch 011 - train 0.37231 | val 2.39133
  Classification -> best τ=0.780 (val F1=0.0473)
  Directional -> Accuracy: 0.4655, MCC: -0.1738, F1: 0.6265

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.54238 | val 1.42173

[I 2026-02-22 08:33:34,666] Trial 21 finished with value: 0.2331582623129341 and parameters: {'feature_set': 'sector', 'model_type': 'BiGRU', 'sequence_length': 6, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.1, 'batch_size': 16, 'learning_rate': 0.001229307323567454, 'weight_decay': 4.0106430265702656e-05, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 1.2040963286364441, 'early_stopping_min_delta': 0.008469271783379702}. Best is trial 12 with value: 0.26451244235752075.

  Epoch 016 - train 0.39799 | val 0.99670
  Classification -> best τ=0.495 (val F1=0.2829)
  Directional -> Accuracy: 0.6349, MCC: 0.2672, F1: 0.5660

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2331582623129341
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 6
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.61274 | val 0.78828
  Epoch 012 - train 0.54692 | val 0.93675
  Classification -> best τ=0.580 (val F1=0.2727)
  Directional -> Accuracy: 0.6076, MCC: 0.1867, F1: 0.3673

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 82). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.39866 | val 0.87963
  Epoch 011 - train 0.39767 | val 0.98453
  Classification -> best τ=0.515 (val F1=0.1654)
  Directional -> Accuracy: 0.4375, MCC: 0.0000, F1: 0.0000

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 82). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.48205 | val 2.06257
  Epoch 011 - train 0.41976 | val 2.25164
  Classification -> best τ=0.810 (val F1=0.2722)
  Directional -> Accuracy: 0.4898, MCC: 0.0469, F1: 0.1935

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.57358 | val 0.74862
  Epoch 013 - train 0.54149 | val 0.70775
  Classification -> best τ=0.460 (val F1=0.2598)
  Directional -> Accuracy: 0.5455, MCC: 0.0000, F1: 0.7059

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.45751 | val 1.30509
  Epoch 012 - train 0.31648 | val 1.80133
  Classification -> best τ=0.550 (val F1=0.4557)
  Directional -> Accuracy: 0.6604, MCC: 0.3584, F1: 0.6087

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.43966 | val 0.79519
  Epoch 013 - train 0.31953 | val 0.95988
  Classification -> best τ=0.700 (val F1=0.2032)
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.51663 | val 1.20469
  Epoch 011 - train 0.48733 | val 1.25442
  Classification -> best τ=0.845 (val F1=0.2085)
  Directional -> Accuracy: 0.5915, MCC: 0.0000, F1: 0.0000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 82). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 82). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.29104 | val 1.51079
  Epoch 013 - train 0.23152 | val 1.03160
  Classification -> best τ=0.330 (val F1=0.4000)
  Directional -> Accuracy: 0.5319, MCC: -0.1010, F1: 0.1538

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.56406 | val 1.22775
  Epoch 011 - train 0.50410 | val 0.88106
  Classification -> best τ=0.555 (val F1=0.2950)
  Directional -> Accuracy: 0.4186, MCC: -0.0300, F1: 0.5283

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 82). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 82). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.46139 | val 1.14267
  Epoch 014 - train 0.31722 | val 1.33146
  Classification -> best τ=0.825 (val F1=0.1791)
  Directional -> Accuracy: 0.5278, MCC: 0.0370, F1: 0.4516

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.49595 | val 0.83335
  Epoch 014 - train 0.31952 | val 1.00575
  Classification -> best τ=0.590 (val F1=0.3161)
  Directional -> Accuracy: 0.6731, MCC: 0.3471, F1: 0.5641

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.62148 | val 1.05793
  Epoch 013 - train 0.53148 | val 1.06678
  Classification -> best τ=0.670 (val F1=0.1822)
  Directional -> Accuracy: 0.6000, MCC: 0.2018, F1: 0.6250

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.37309 | val 1.03316
  Epoch 011 - train 0.30799 | val 1.14527
  Classification -> best τ=0.655 (val F1=0.1231)
  Directional -> Accuracy: 0.5556, MCC: 0.0945, F1: 0.4444

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 82). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.54068 | val 0.68810
  Epoch 011 - train 0.49479 | val 0.76147
  Classification -> best τ=0.230 (val F1=0.4286)
  Directional -> Accuracy: 0.4921, MCC: -0.0311, F1: 0.2727

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.52703 | val 1.05268
  Epoch 011 - train 0.45428 | val 0.93555
  Classification -> best τ=0.590 (val F1=0.2869)
  Directional -> Accuracy: 0.5185, MCC: 0.0447, F1: 0.5517

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.52915 | val 0.95826
  Epoch 016 - train 0.36774 | val 1.60395
  Classification -> best τ=0.930 (val F1=0.3077)
  Directional -> Accuracy: 0.5278, MCC: 0.1176, F1: 0.3929

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.45599 | val 1.85543
  Epoch 011 - train 0.42110 | val 1.97474
  Classification -> best τ=0.440 (val F1=0.1411)
  Directional -> Accuracy: 0.6066, MCC: 0.0000, F1: 0.7551

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.53125 | val 0.98142
  Epoch 012 - train 0.41483 | val 1.14784
  Classification -> best τ=0.720 (val F1=0.2486)
  Directional -> Accuracy: 0.3974, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.54682 | val 1.19033
  Epoch 011 - train 0.51545 | val 1.07144
  Classification -> best τ=0.420 (val F1=0.4146)
  Directional -> Accuracy: 0.5522, MCC: 0.1084, F1: 0.5833

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 82). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.44767 | val 0.93258
  Epoch 011 - train 0.38736 | val 0.96161
  Classification -> best τ=0.455 (val F1=0.2433)
  Directional -> Accuracy: 0.5325, MCC: -0.0074, F1: 0.6727

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.37138 | val 1.16276
  Epoch 011 - train 0.36341 | val 1.31234
  Classification -> best τ=0.395 (val F1=0.2850)
  Directional -> Accuracy: 0.6200, MCC: 0.0000, F1: 0.7654

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 82). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 82). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 82). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.48271 | val 1.24042
  Epoch 011 - train 0.41345 | val 1.43771
  Classification -> best τ=0.310 (val F1=0.2500)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.48732 | val 1.31148
  Epoch 012 - train 0.40848 | val 1.33368
  Classification -> best τ=0.575 (val F1=0.2464)
  Directional -> Accuracy: 0.5500, MCC: 0.0796, F1: 0.6087

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.55500 | val 0.77283
  Epoch 013 - train 0.48020 | val 0.74439
  Classification -> best τ=0.625 (val F1=0.1846)
  Directional -> Accuracy: 0.5147, MCC: 0.0000, F1: 0.0000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.45858 | val 1.30561
  Epoch 011 - train 0.34755 | val 1.20102
  Classification -> best τ=0.460 (val F1=0.5592)
  Directional -> Accuracy: 0.5690, MCC: 0.1741, F1: 0.5283

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.38095 | val 1.53802
  Epoch 011 - train 0.36003 | val 1.53707
  Classification -> best τ=0.585 (val F1=0.2915)
  Directional -> Accuracy: 0.4286, MCC: -0.2173, F1: 0.2222

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.46926 | val 0.83822
  Epoch 011 - train 0.43958 | val 0.76644
  Classification -> best τ=0.565 (val F1=0.0714)
  Directional -> Accuracy: 0.4222, MCC: 0.1231, F1: 0.0714

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.47628 | val 1.49907
  Epoch 011 - train 0.40494 | val 1.76909
  Classification -> best τ=0.335 (val F1=0.2775)
  Directional -> Accuracy: 0.4407, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.28969 | val 2.23654
  Epoch 011 - train 0.25316 | val 1.94494
  Classification -> best τ=0.470 (val F1=0.2365)
  Directional -> Accuracy: 0.4773, MCC: -0.1145, F1: 0.6230

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.40594 | val 0.77954
  Epoch 011 - train 0.39404 | val 0.91262
  Classification -> best τ=0.530 (val F1=0.3582)
  Directional -> Accuracy: 0.6304, MCC: 0.2673, F1: 0.6667

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.48445 | val 1.11865
  Epoch 011 - train 0.44206 | val 1.06649
  Classification -> best τ=0.450 (val F1=0.0744)
  Directional -> Accuracy: 0.5652, MCC: 0.0977, F1: 0.6875

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.43363 | val 0.94169
  Epoch 011 - train 0.37766 | val 1.07372
  Classification -> best τ=0.475 (val F1=0.2689)
  Directional -> Accuracy: 0.5192, MCC: 0.0000, F1: 0.6835

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.48746 | val 1.31708
  Epoch 011 - train 0.42920 | val 1.51271
  Classification -> best τ=0.410 (val F1=0.3337)
  Directional -> Accuracy: 0.5200, MCC: 0.1896, F1: 0.3077

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 82). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.41254 | val 1.02012
  Epoch 011 - train 0.36481 | val 1.10068
  Classification -> best τ=0.530 (val F1=0.4730)
  Directional -> Accuracy: 0.5610, MCC: 0.1407, F1: 0.6250

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.37665 | val 1.82941
  Epoch 011 - train 0.33453 | val 1.77658
  Classification -> best τ=0.655 (val F1=0.2930)
  Directional -> Accuracy: 0.5435, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.56409 | val 1.08011
  Epoch 015 - train 0.34287 | val 1.21028
  Classification -> best τ=0.195 (val F1=0.2307)
  Directional -> Accuracy: 0.4928, MCC: 0.0780, F1: 0.3860

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.38708 | val 1.55292
  Epoch 012 - train 0.36464 | val 1.29756
  Classification -> best τ=0.350 (val F1=0.3636)
  Directional -> Accuracy: 0.4444, MCC: -0.1160, F1: 0.4898

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.56015 | val 1.37588
  Epoch 011 - train 0.52215 | val 1.37656
  Classification -> best τ=0.435 (val F1=0.2118)
  Directional -> Accuracy: 0.5763, MCC: 0.1787, F1: 0.6269

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.43020 | val 0.99182
  Epoch 011 - train 0.37291 | val 1.08147
  Classification -> best τ=0.390 (val F1=0.3278)
  Directional -> Accuracy: 0.6122, MCC: 0.0000, F1: 0.7595

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 82). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 82). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 82). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 82). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.44357 | val 1.04525
  Epoch 011 - train 0.38632 | val 1.03631
  Classification -> best τ=0.445 (val F1=0.3420)
  Directional -> Accuracy: 0.3333, MCC: 0.0000, F1: 0.5000

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 82). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.40707 | val 1.72609
  Epoch 012 - train 0.20829 | val 2.05892
  Classification -> best τ=0.550 (val F1=0.3564)
  Directional -> Accuracy: 0.5610, MCC: 0.1334, F1: 0.5000

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 82). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 82). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.52132 | val 1.10568
  Epoch 013 - train 0.35167 | val 1.57358
  Classification -> best τ=0.365 (val F1=0.3625)
  Directional -> Accuracy: 0.5325, MCC: 0.1654, F1: 0.6842

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 82). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 82). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.53648 | val 1.61592
  Epoch 012 - train 0.36572 | val 2.10695
  Classification -> best τ=0.685 (val F1=0.3934)
  Directional -> Accuracy: 0.5714, MCC: 0.2119, F1: 0.6769

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.22945 | val 4.64360
  Epoch 011 - train 0.15886 | val 4.61311
  Classification -> best τ=0.590 (val F1=0.5308)
  Directional -> Accuracy: 0.5532, MCC: 0.1315, F1: 0.5532

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.30647 | val 1.30886
  Epoch 011 - train 0.22701 | val 1.30136
  Classification -> best τ=0.465 (val F1=0.5666)
  Directional -> Accuracy: 0.4286, MCC: 0.2067, F1: 0.5556

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.57290 | val 1.02800
  Epoch 011 - train 0.49924 | val 1.23205
  Classification -> best τ=0.760 (val F1=0.1962)
  Directional -> Accuracy: 0.4483, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.34822 | val 1.27658
  Epoch 011 - train 0.25984 | val 1.44432
  Classification -> best τ=0.355 (val F1=0.2470)
  Directional -> Accuracy: 0.4915, MCC: 0.0000, F1: 0.6591

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.51987 | val 1.56620
  Epoch 011 - train 0.42505 | val 1.91265
  Classification -> best τ=0.120 (val F1=0.1502)
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.38518 | val 2.34409
  Epoch 011 - train 0.32107 | val 3.10132
  Classification -> best τ=0.765 (val F1=0.0263)
  Directional -> Accuracy: 0.4828, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.54121 | val 0.68209

[I 2026-02-22 08:35:36,143] Trial 22 finished with value: 0.2833350641483003 and parameters: {'feature_set': 'sector', 'model_type': 'BiGRU', 'sequence_length': 6, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.0, 'batch_size': 16, 'learning_rate': 0.003520721651454354, 'weight_decay': 1.5581758539869743e-05, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 1.3319993602978772, 'early_stopping_min_delta': 0.007874187352334677}. Best is trial 22 with value: 0.2833350641483003.

  Epoch 014 - train 0.53540 | val 1.00773
  Classification -> best τ=0.490 (val F1=0.2543)
  Directional -> Accuracy: 0.5714, MCC: 0.1352, F1: 0.4906

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2833350641483003
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.60231 | val 0.81670
  Epoch 011 - train 0.58465 | val 0.97711
  Classification -> best τ=0.805 (val F1=0.2510)
  Directional -> Accuracy: 0.5526, MCC: 0.0000, F1: 0.0000

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.52694 | val 0.91853
  Epoch 011 - train 0.44838 | val 0.78825
  Classification -> best τ=0.465 (val F1=0.1941)
  Directional -> Accuracy: 0.6222, MCC: 0.1967, F1: 0.7119

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.53206 | val 1.51942
  Epoch 011 - train 0.49482 | val 1.82879
  Classification -> best τ=0.735 (val F1=0.3114)
  Directional -> Accuracy: 0.5217, MCC: 0.1124, F1: 0.2667

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.57954 | val 1.13624
  Epoch 016 - train 0.46727 | val 1.00820
  Classification -> best τ=0.290 (val F1=0.1808)
  Directional -> Accuracy: 0.5405, MCC: 0.0000, F1: 0.7018

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.51242 | val 0.76119
  Epoch 016 - train 0.34413 | val 1.03423
  Classification -> best τ=0.590 (val F1=0.5217)
  Directional -> Accuracy: 0.6200, MCC: 0.2795, F1: 0.5366

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.48714 | val 0.92558
  Epoch 011 - train 0.39964 | val 0.91953
  Classification -> best τ=0.510 (val F1=0.2090)
  Directional -> Accuracy: 0.5217, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.62852 | val 1.12379
  Epoch 011 - train 0.53552 | val 1.10624
  Classification -> best τ=0.570 (val F1=0.2536)
  Directional -> Accuracy: 0.5147, MCC: 0.0425, F1: 0.4762

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.47842 | val 0.97703
  Epoch 013 - train 0.39613 | val 1.11121
  Classification -> best τ=0.210 (val F1=0.1147)
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.47777 | val 1.90224
  Epoch 011 - train 0.45479 | val 1.73432
  Classification -> best τ=0.540 (val F1=0.3433)
  Directional -> Accuracy: 0.5625, MCC: 0.1065, F1: 0.4878

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.54566 | val 1.09872
  Epoch 012 - train 0.47420 | val 1.19987
  Classification -> best τ=0.295 (val F1=0.2434)
  Directional -> Accuracy: 0.4783, MCC: 0.0054, F1: 0.5135

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.57349 | val 0.66273
  Epoch 016 - train 0.47499 | val 0.70865
  Classification -> best τ=0.430 (val F1=0.4037)
  Directional -> Accuracy: 0.5510, MCC: 0.0453, F1: 0.2667

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.52930 | val 2.04174
  Epoch 011 - train 0.52805 | val 2.46174
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5088, MCC: 0.0000, F1: 0.6744

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.46144 | val 2.52626
  Epoch 011 - train 0.36784 | val 2.64231
  Classification -> best τ=0.525 (val F1=0.1225)
  Directional -> Accuracy: 0.5476, MCC: 0.0677, F1: 0.4242

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.54194 | val 0.96536
  Epoch 011 - train 0.47538 | val 0.92019
  Classification -> best τ=0.430 (val F1=0.1774)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.57657 | val 0.73427
  Epoch 016 - train 0.42055 | val 0.76577
  Classification -> best τ=0.435 (val F1=0.2157)
  Directional -> Accuracy: 0.5490, MCC: 0.2988, F1: 0.6667

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.55921 | val 2.14087
  Epoch 012 - train 0.51921 | val 2.16523
  Classification -> best τ=0.310 (val F1=0.3486)
  Directional -> Accuracy: 0.5362, MCC: 0.0180, F1: 0.6863

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.58602 | val 1.59948
  Epoch 011 - train 0.52922 | val 1.66730
  Classification -> best τ=0.315 (val F1=0.0660)
  Directional -> Accuracy: 0.6207, MCC: 0.0000, F1: 0.7660

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.52189 | val 1.05324
  Epoch 013 - train 0.43177 | val 1.12242
  Classification -> best τ=0.345 (val F1=0.2262)
  Directional -> Accuracy: 0.4000, MCC: -0.0705, F1: 0.1509

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.58584 | val 1.21116
  Epoch 011 - train 0.51532 | val 1.11771
  Classification -> best τ=0.295 (val F1=0.3057)
  Directional -> Accuracy: 0.5781, MCC: 0.1225, F1: 0.6494

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.50445 | val 1.11559
  Epoch 011 - train 0.50448 | val 1.32459
  Classification -> best τ=0.420 (val F1=0.2881)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.53387 | val 1.22649
  Epoch 012 - train 0.42637 | val 1.29522
  Classification -> best τ=0.665 (val F1=0.1978)
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.55874 | val 1.02762
  Epoch 011 - train 0.50368 | val 1.19266
  Classification -> best τ=0.415 (val F1=0.1650)
  Directional -> Accuracy: 0.5077, MCC: 0.0000, F1: 0.6735

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.58797 | val 0.84724
  Epoch 013 - train 0.53484 | val 1.17856
  Classification -> best τ=0.745 (val F1=0.4108)
  Directional -> Accuracy: 0.4912, MCC: 0.0250, F1: 0.4314

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.56449 | val 0.76721
  Epoch 011 - train 0.53601 | val 0.87294
  Classification -> best τ=0.450 (val F1=0.2298)
  Directional -> Accuracy: 0.5077, MCC: 0.0917, F1: 0.6444

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.50167 | val 1.25247
  Epoch 011 - train 0.50303 | val 1.29392
  Classification -> best τ=0.435 (val F1=0.4723)
  Directional -> Accuracy: 0.4545, MCC: -0.0177, F1: 0.0625

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.43904 | val 4.73573
  Epoch 011 - train 0.41534 | val 4.42784
  Classification -> best τ=0.645 (val F1=0.1310)
  Directional -> Accuracy: 0.3556, MCC: -0.2466, F1: 0.4528

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.53889 | val 1.02708
  Epoch 011 - train 0.50960 | val 1.20631
  Classification -> best τ=0.395 (val F1=0.1340)
  Directional -> Accuracy: 0.5238, MCC: 0.0694, F1: 0.5238

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.48563 | val 1.84872
  Epoch 011 - train 0.46058 | val 1.67591
  Classification -> best τ=0.265 (val F1=0.2543)
  Directional -> Accuracy: 0.4464, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.48780 | val 0.90069
  Epoch 011 - train 0.50435 | val 0.92027
  Classification -> best τ=0.640 (val F1=0.1918)
  Directional -> Accuracy: 0.4250, MCC: -0.1234, F1: 0.3429

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.55351 | val 0.80500
  Epoch 016 - train 0.40145 | val 1.08553
  Classification -> best τ=0.465 (val F1=0.4035)
  Directional -> Accuracy: 0.4286, MCC: -0.1514, F1: 0.3684

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.47681 | val 1.01366
  Epoch 012 - train 0.45579 | val 1.17993
  Classification -> best τ=0.370 (val F1=0.2357)
  Directional -> Accuracy: 0.5476, MCC: 0.0000, F1: 0.7077

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.50910 | val 1.05136
  Epoch 011 - train 0.45380 | val 0.99175
  Classification -> best τ=0.385 (val F1=0.3242)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.56707 | val 1.02476
  Epoch 011 - train 0.54364 | val 0.85375
  Classification -> best τ=0.515 (val F1=0.3008)
  Directional -> Accuracy: 0.4444, MCC: 0.0000, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.43318 | val 1.20458
  Epoch 011 - train 0.39476 | val 1.44940
  Classification -> best τ=0.410 (val F1=0.3078)
  Directional -> Accuracy: 0.5116, MCC: 0.0162, F1: 0.4000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.52481 | val 1.15379
  Epoch 011 - train 0.49385 | val 1.27164
  Classification -> best τ=0.435 (val F1=0.2858)
  Directional -> Accuracy: 0.5758, MCC: 0.0000, F1: 0.7308

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.45663 | val 1.08536
  Epoch 011 - train 0.40676 | val 1.16848
  Classification -> best τ=0.445 (val F1=0.1715)
  Directional -> Accuracy: 0.6905, MCC: 0.3877, F1: 0.6829

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.51483 | val 1.11842
  Epoch 011 - train 0.52385 | val 1.35582
  Classification -> best τ=0.475 (val F1=0.2327)
  Directional -> Accuracy: 0.5000, MCC: 0.0157, F1: 0.5333

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.44730 | val 1.54443
  Epoch 011 - train 0.38770 | val 1.52791
  Classification -> best τ=0.585 (val F1=0.2659)
  Directional -> Accuracy: 0.4783, MCC: -0.0742, F1: 0.5556

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.55014 | val 0.81342
  Epoch 011 - train 0.50691 | val 0.80108
  Classification -> best τ=0.590 (val F1=0.4011)
  Directional -> Accuracy: 0.3750, MCC: 0.1080, F1: 0.5312

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.56558 | val 1.61399
  Epoch 012 - train 0.49689 | val 1.66639
  Classification -> best τ=0.395 (val F1=0.3584)
  Directional -> Accuracy: 0.4595, MCC: -0.1053, F1: 0.2857

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.51857 | val 0.79496
  Epoch 012 - train 0.49632 | val 0.68968
  Classification -> best τ=0.470 (val F1=0.4080)
  Directional -> Accuracy: 0.6000, MCC: 0.1996, F1: 0.6400

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.38975 | val 3.41586
  Epoch 011 - train 0.31329 | val 3.36877
  Classification -> best τ=0.620 (val F1=0.4971)
  Directional -> Accuracy: 0.6190, MCC: 0.1978, F1: 0.7037

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.42695 | val 0.92797
  Epoch 015 - train 0.35133 | val 1.16396
  Classification -> best τ=0.500 (val F1=0.3752)
  Directional -> Accuracy: 0.3958, MCC: 0.1130, F1: 0.5538

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.60797 | val 1.39856
  Epoch 012 - train 0.59150 | val 1.68647
  Classification -> best τ=0.585 (val F1=0.2374)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.44465 | val 3.93102
  Epoch 011 - train 0.39116 | val 3.85748
  Classification -> best τ=0.710 (val F1=0.2143)
  Directional -> Accuracy: 0.5357, MCC: 0.0662, F1: 0.4800

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.60521 | val 1.04200
  Epoch 012 - train 0.57911 | val 0.92139
  Classification -> best τ=0.455 (val F1=0.1787)
  Directional -> Accuracy: 0.5660, MCC: 0.1375, F1: 0.6462

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.51838 | val 1.89505
  Epoch 011 - train 0.45814 | val 2.20587
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5273, MCC: 0.0000, F1: 0.6905

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.58958 | val 0.74538

[I 2026-02-22 08:39:39,150] Trial 23 finished with value: 0.2580170035644324 and parameters: {'feature_set': 'sector', 'model_type': 'BiGRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.4, 'dropout': 0.0, 'batch_size': 16, 'learning_rate': 0.0031978229210442902, 'weight_decay': 9.040663999783525e-06, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 0.8849901157430133, 'early_stopping_min_delta': 0.009900458939274473}. Best is trial 22 with value: 0.2833350641483003.

  Epoch 011 - train 0.54934 | val 0.73625
  Classification -> best τ=0.530 (val F1=0.2231)
  Directional -> Accuracy: 0.5500, MCC: 0.1130, F1: 0.5970

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2580170035644324
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 12
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sentiment', 'emotion_anger', 'emotion_disgust', 'emotion_fear', 'emotion_joy', 'emotion_neutral', 'emotion_sadness', 'emotion_surprize', 'emotion_anger_pct', 'emotion_disgust_pct', 'emotion_fear_pct', 'emotion_joy_pct', 'emotion_neutral_pct', 'emotion_sadness_pct', 'emotion_surprize_pct', 'positive_emotion', 'negative_emotion', 'uncertainty_emotion', 'positive_emotion_pct', 'negative_emotion_pct', 'uncertainty_emotion_pct', 'stance_label', 'stance_score', 'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down', 'finbert_neutral']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.35792 | val 0.90800
  Epoch 011 - train 0.27055 | val 1.07356
  Classification -> best τ=0.510 (val F1=0.0690)
  Directional -> Accuracy: 0.4359, MCC: -0.2117, F1: 0.1852

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 88). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.22186 | val 1.40286
  Epoch 011 - train 0.14272 | val 2.00811
  Classification -> best τ=0.555 (val F1=0.2346)
  Directional -> Accuracy: 0.6809, MCC: 0.3661, F1: 0.6939

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 88). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.33802 | val 1.53457
  Epoch 011 - train 0.19475 | val 1.52728
  Classification -> best τ=0.565 (val F1=0.2586)
  Directional -> Accuracy: 0.5000, MCC: 0.0216, F1: 0.4545

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.42620 | val 1.57384
  Epoch 011 - train 0.33446 | val 1.28070
  Classification -> best τ=0.460 (val F1=0.1095)
  Directional -> Accuracy: 0.4605, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.22887 | val 1.41864
  Epoch 012 - train 0.04885 | val 1.42241
  Classification -> best τ=0.505 (val F1=0.3913)
  Directional -> Accuracy: 0.5577, MCC: 0.1782, F1: 0.4390

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.18252 | val 3.24482
  Epoch 011 - train 0.12286 | val 3.63686
  Classification -> best τ=0.675 (val F1=0.1956)
  Directional -> Accuracy: 0.4898, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.25538 | val 2.36956
  Epoch 011 - train 0.15019 | val 2.42392
  Classification -> best τ=0.800 (val F1=0.1212)
  Directional -> Accuracy: 0.5714, MCC: -0.1400, F1: 0.0000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 88). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 88). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.15740 | val 2.27827
  Epoch 012 - train 0.07611 | val 2.35419
  Classification -> best τ=0.640 (val F1=0.2988)
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.5938

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.22719 | val 1.18860
  Epoch 013 - train 0.06318 | val 1.67816
  Classification -> best τ=0.260 (val F1=0.3920)
  Directional -> Accuracy: 0.5238, MCC: 0.2557, F1: 0.6000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 88). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 88). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.22973 | val 1.75134
  Epoch 011 - train 0.15403 | val 1.85785
  Classification -> best τ=0.395 (val F1=0.1909)
  Directional -> Accuracy: 0.4930, MCC: 0.0462, F1: 0.5610

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.28392 | val 2.87771
  Epoch 012 - train 0.08918 | val 2.61882
  Classification -> best τ=0.440 (val F1=0.1551)
  Directional -> Accuracy: 0.5686, MCC: 0.1245, F1: 0.4500

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.37297 | val 0.80214
  Epoch 011 - train 0.26887 | val 0.87976
  Classification -> best τ=0.530 (val F1=0.2750)
  Directional -> Accuracy: 0.5763, MCC: 0.1955, F1: 0.4186

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.19925 | val 2.73798
  Epoch 011 - train 0.08969 | val 2.95775
  Classification -> best τ=0.470 (val F1=0.3737)
  Directional -> Accuracy: 0.5455, MCC: 0.0690, F1: 0.4444

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 88). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.34368 | val 0.95712
  Epoch 011 - train 0.22569 | val 1.14188
  Classification -> best τ=0.355 (val F1=0.3471)
  Directional -> Accuracy: 0.5323, MCC: 0.0645, F1: 0.5397

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.32469 | val 1.32757
  Epoch 011 - train 0.18459 | val 1.18007
  Classification -> best τ=0.395 (val F1=0.1229)
  Directional -> Accuracy: 0.4528, MCC: -0.1468, F1: 0.6234

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.41379 | val 0.96247
  Epoch 011 - train 0.24648 | val 1.10758
  Classification -> best τ=0.695 (val F1=0.3827)
  Directional -> Accuracy: 0.6056, MCC: 0.2045, F1: 0.6410

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.45837 | val 2.28387
  Epoch 011 - train 0.24217 | val 2.42561
  Classification -> best τ=0.590 (val F1=0.0781)
  Directional -> Accuracy: 0.4000, MCC: -0.0338, F1: 0.1818

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.39917 | val 1.79486
  Epoch 011 - train 0.27373 | val 1.89827
  Classification -> best τ=0.575 (val F1=0.0425)
  Directional -> Accuracy: 0.3896, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.35005 | val 1.74520
  Epoch 011 - train 0.24686 | val 3.09391
  Classification -> best τ=0.545 (val F1=0.1964)
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 88). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.45113 | val 1.38125
  Epoch 012 - train 0.24303 | val 1.61217
  Classification -> best τ=0.685 (val F1=0.2332)
  Directional -> Accuracy: 0.4605, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.21639 | val 1.06075
  Epoch 011 - train 0.11695 | val 1.34822
  Classification -> best τ=0.585 (val F1=0.0271)
  Directional -> Accuracy: 0.5918, MCC: -0.1572, F1: 0.7436

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 88). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 88). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 88). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.33076 | val 1.40839
  Epoch 011 - train 0.21997 | val 1.72702
  Classification -> best τ=0.300 (val F1=0.0959)
  Directional -> Accuracy: 0.5821, MCC: 0.1961, F1: 0.6818

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.33661 | val 3.11675
  Epoch 011 - train 0.17820 | val 3.71244
  Classification -> best τ=0.665 (val F1=0.1955)
  Directional -> Accuracy: 0.4068, MCC: -0.1179, F1: 0.2222

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.38681 | val 1.95392
  Epoch 013 - train 0.17849 | val 2.32113
  Classification -> best τ=0.555 (val F1=0.2331)
  Directional -> Accuracy: 0.5224, MCC: 0.0313, F1: 0.4074

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.26724 | val 2.09026
  Epoch 011 - train 0.16705 | val 2.13291
  Classification -> best τ=0.720 (val F1=0.1593)
  Directional -> Accuracy: 0.5263, MCC: 0.1635, F1: 0.3721

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.03864 | val 2.53839
  Epoch 011 - train 0.02713 | val 2.53949
  Classification -> best τ=0.385 (val F1=0.2249)
  Directional -> Accuracy: 0.4167, MCC: 0.0000, F1: 0.5882

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.18376 | val 2.30536
  Epoch 011 - train 0.06186 | val 3.27775
  Classification -> best τ=0.385 (val F1=0.3221)
  Directional -> Accuracy: 0.5227, MCC: -0.0534, F1: 0.6441

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.25691 | val 2.00669
  Epoch 012 - train 0.08999 | val 2.25930
  Classification -> best τ=0.380 (val F1=0.2211)
  Directional -> Accuracy: 0.5000, MCC: 0.0688, F1: 0.3556

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.12826 | val 1.36849
  Epoch 014 - train 0.02562 | val 1.84112
  Classification -> best τ=0.625 (val F1=0.5733)
  Directional -> Accuracy: 0.3721, MCC: -0.2468, F1: 0.3077

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.21835 | val 1.58446
  Epoch 011 - train 0.09284 | val 1.62759
  Classification -> best τ=0.830 (val F1=0.1348)
  Directional -> Accuracy: 0.4889, MCC: 0.0000, F1: 0.0000

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.17683 | val 1.27870
  Epoch 011 - train 0.10095 | val 1.24790
  Classification -> best τ=0.435 (val F1=0.2390)
  Directional -> Accuracy: 0.5333, MCC: 0.0000, F1: 0.6957

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.17719 | val 1.95741
  Epoch 011 - train 0.10852 | val 2.09252
  Classification -> best τ=0.505 (val F1=0.1682)
  Directional -> Accuracy: 0.5098, MCC: 0.0094, F1: 0.5614

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.33550 | val 1.37049
  Epoch 011 - train 0.22576 | val 1.50897
  Classification -> best τ=0.410 (val F1=0.3204)
  Directional -> Accuracy: 0.5811, MCC: 0.1498, F1: 0.6265

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 88). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.13125 | val 1.08104
  Epoch 014 - train 0.03295 | val 1.49730
  Classification -> best τ=0.445 (val F1=0.4808)
  Directional -> Accuracy: 0.5128, MCC: 0.0669, F1: 0.6415

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.19308 | val 2.81556
  Epoch 011 - train 0.06836 | val 3.21890
  Classification -> best τ=0.660 (val F1=0.1612)
  Directional -> Accuracy: 0.5333, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.21885 | val 2.41481
  Epoch 011 - train 0.15238 | val 2.59218
  Classification -> best τ=0.100 (val F1=0.3219)
  Directional -> Accuracy: 0.5882, MCC: 0.2258, F1: 0.5625

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.19667 | val 2.04591
  Epoch 011 - train 0.11208 | val 1.75631
  Classification -> best τ=0.710 (val F1=0.3151)
  Directional -> Accuracy: 0.5227, MCC: 0.0902, F1: 0.1600

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.34386 | val 1.38306
  Epoch 012 - train 0.15451 | val 1.71052
  Classification -> best τ=0.670 (val F1=0.2827)
  Directional -> Accuracy: 0.4655, MCC: -0.0668, F1: 0.4561

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.41110 | val 3.03900
  Epoch 012 - train 0.08428 | val 3.95450
  Classification -> best τ=0.830 (val F1=0.1970)
  Directional -> Accuracy: 0.3958, MCC: 0.1130, F1: 0.0645

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 88). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 88). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 88). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 88). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.26491 | val 2.11142
  Epoch 013 - train 0.02710 | val 2.70857
  Classification -> best τ=0.575 (val F1=0.5266)
  Directional -> Accuracy: 0.6000, MCC: 0.0605, F1: 0.3333

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 88). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.14077 | val 1.74591
  Epoch 011 - train 0.09010 | val 1.98893
  Classification -> best τ=0.595 (val F1=0.0510)
  Directional -> Accuracy: 0.4872, MCC: 0.1502, F1: 0.0909

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 88). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 88). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.29634 | val 3.05531
  Epoch 012 - train 0.14691 | val 4.17735
  Classification -> best τ=0.365 (val F1=0.1711)
  Directional -> Accuracy: 0.5263, MCC: 0.1644, F1: 0.6786

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 88). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 88). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 88). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.24495 | val 2.32130
  Epoch 012 - train 0.08578 | val 2.58008
  Classification -> best τ=0.440 (val F1=0.2544)
  Directional -> Accuracy: 0.4583, MCC: -0.1118, F1: 0.1875

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.05402 | val 2.47455
  Epoch 011 - train 0.03592 | val 2.55689
  Classification -> best τ=0.590 (val F1=0.4339)
  Directional -> Accuracy: 0.4667, MCC: 0.0137, F1: 0.2500

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.17586 | val 2.48791
  Epoch 011 - train 0.07330 | val 2.53927
  Classification -> best τ=0.330 (val F1=0.0727)
  Directional -> Accuracy: 0.3659, MCC: 0.0000, F1: 0.5357

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.49626 | val 0.76618
  Epoch 012 - train 0.19426 | val 1.27657
  Classification -> best τ=0.560 (val F1=0.3101)
  Directional -> Accuracy: 0.4035, MCC: -0.1830, F1: 0.1500

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.21915 | val 4.82277
  Epoch 011 - train 0.11974 | val 3.64974
  Classification -> best τ=0.815 (val F1=0.3167)
  Directional -> Accuracy: 0.5000, MCC: 0.0048, F1: 0.5246

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.22583 | val 1.17523
  Epoch 011 - train 0.15326 | val 1.29803
  Classification -> best τ=0.430 (val F1=0.1307)
  Directional -> Accuracy: 0.5273, MCC: 0.0381, F1: 0.6061

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.26838 | val 1.57235
  Epoch 012 - train 0.14056 | val 2.52542
  Classification -> best τ=0.515 (val F1=0.2202)
  Directional -> Accuracy: 0.5614, MCC: 0.1520, F1: 0.6753

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.38170 | val 0.78311

[I 2026-02-22 08:42:09,743] Trial 24 finished with value: 0.23934989547005872 and parameters: {'feature_set': 'all_nlp', 'model_type': 'BiGRU', 'sequence_length': 12, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.30000000000000004, 'batch_size': 16, 'learning_rate': 0.004388156351656418, 'weight_decay': 2.0586636298095508e-05, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 1.35955462413841, 'early_stopping_min_delta': 0.007255044108798119}. Best is trial 22 with value: 0.2833350641483003.

  Epoch 014 - train 0.15103 | val 2.24788
  Classification -> best τ=0.575 (val F1=0.3383)
  Directional -> Accuracy: 0.4194, MCC: -0.1927, F1: 0.2500

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.23934989547005872
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 6
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d', 'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down', 'finbert_neutral']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.48109 | val 0.92606
  Epoch 014 - train 0.39072 | val 1.26168
  Classification -> best τ=0.555 (val F1=0.2727)
  Directional -> Accuracy: 0.5949, MCC: 0.1746, F1: 0.5294

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 82). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.41663 | val 1.09484
  Epoch 012 - train 0.32918 | val 1.44666
  Classification -> best τ=0.670 (val F1=0.2364)
  Directional -> Accuracy: 0.5208, MCC: 0.1039, F1: 0.4390

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 82). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.48750 | val 1.85865
  Epoch 011 - train 0.42411 | val 2.17483
  Classification -> best τ=0.620 (val F1=0.3408)
  Directional -> Accuracy: 0.4694, MCC: -0.0229, F1: 0.1875

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.49898 | val 0.78083
  Epoch 011 - train 0.44051 | val 0.88611
  Classification -> best τ=0.620 (val F1=0.2465)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.38738 | val 1.22149
  Epoch 018 - train 0.14982 | val 1.04002
  Classification -> best τ=0.495 (val F1=0.4386)
  Directional -> Accuracy: 0.6604, MCC: 0.3281, F1: 0.6538

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.40087 | val 0.84041
  Epoch 012 - train 0.31094 | val 1.03840
  Classification -> best τ=0.575 (val F1=0.3383)
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.48417 | val 0.99927
  Epoch 011 - train 0.41493 | val 1.26157
  Classification -> best τ=0.595 (val F1=0.1930)
  Directional -> Accuracy: 0.6056, MCC: 0.1438, F1: 0.0667

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 82). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 82). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.35638 | val 1.86503
  Epoch 011 - train 0.31388 | val 2.43722
  Classification -> best τ=0.720 (val F1=0.4385)
  Directional -> Accuracy: 0.5957, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.42947 | val 2.80105
  Epoch 011 - train 0.35732 | val 3.06098
  Classification -> best τ=0.350 (val F1=0.1439)
  Directional -> Accuracy: 0.3953, MCC: 0.0000, F1: 0.5667

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 82). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 82). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.49670 | val 1.13458
  Epoch 011 - train 0.44803 | val 1.05261
  Classification -> best τ=0.385 (val F1=0.1838)
  Directional -> Accuracy: 0.4167, MCC: -0.0994, F1: 0.5800

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.50066 | val 1.19209
  Epoch 011 - train 0.39233 | val 1.27843
  Classification -> best τ=0.540 (val F1=0.2140)
  Directional -> Accuracy: 0.6346, MCC: 0.2673, F1: 0.4865

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.57678 | val 0.74254
  Epoch 012 - train 0.52066 | val 0.82220
  Classification -> best τ=0.545 (val F1=0.2974)
  Directional -> Accuracy: 0.5167, MCC: 0.0603, F1: 0.6588

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.34824 | val 1.46090
  Epoch 011 - train 0.29945 | val 1.34862
  Classification -> best τ=0.390 (val F1=0.1502)
  Directional -> Accuracy: 0.4667, MCC: 0.0000, F1: 0.6364

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 82). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.48283 | val 0.90090
  Epoch 014 - train 0.36444 | val 0.88013
  Classification -> best τ=0.330 (val F1=0.5157)
  Directional -> Accuracy: 0.5397, MCC: 0.0790, F1: 0.4314

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.44291 | val 0.67966
  Epoch 018 - train 0.20793 | val 0.95450
  Classification -> best τ=0.650 (val F1=0.2833)
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.44823 | val 1.42527
  Epoch 011 - train 0.40268 | val 1.85664
  Classification -> best τ=0.685 (val F1=0.4162)
  Directional -> Accuracy: 0.5417, MCC: 0.0791, F1: 0.5714

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.49281 | val 1.28911
  Epoch 012 - train 0.38536 | val 1.41465
  Classification -> best τ=0.615 (val F1=0.2441)
  Directional -> Accuracy: 0.4098, MCC: -0.2365, F1: 0.5135

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.59774 | val 1.21518
  Epoch 012 - train 0.46199 | val 1.21272
  Classification -> best τ=0.710 (val F1=0.1541)
  Directional -> Accuracy: 0.3974, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.47481 | val 1.33377
  Epoch 012 - train 0.40770 | val 1.41583
  Classification -> best τ=0.645 (val F1=0.2988)
  Directional -> Accuracy: 0.4179, MCC: -0.0777, F1: 0.2353

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 82). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.42449 | val 0.91791
  Epoch 011 - train 0.35480 | val 0.96362
  Classification -> best τ=0.390 (val F1=0.2079)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.43890 | val 1.14003
  Epoch 011 - train 0.36639 | val 1.31770
  Classification -> best τ=0.480 (val F1=0.2303)
  Directional -> Accuracy: 0.6200, MCC: 0.0000, F1: 0.7654

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 82). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 82). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 82). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.51030 | val 0.85488
  Epoch 012 - train 0.41874 | val 1.03228
  Classification -> best τ=0.505 (val F1=0.2462)
  Directional -> Accuracy: 0.5147, MCC: 0.0563, F1: 0.1538

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.49563 | val 2.41370
  Epoch 012 - train 0.32561 | val 2.65983
  Classification -> best τ=0.530 (val F1=0.2888)
  Directional -> Accuracy: 0.6000, MCC: 0.1869, F1: 0.6471

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.48017 | val 1.20651
  Epoch 011 - train 0.50550 | val 1.26519
  Classification -> best τ=0.425 (val F1=0.1667)
  Directional -> Accuracy: 0.5441, MCC: 0.0979, F1: 0.5867

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.37676 | val 1.33412
  Epoch 011 - train 0.32150 | val 1.21177
  Classification -> best τ=0.425 (val F1=0.3913)
  Directional -> Accuracy: 0.5517, MCC: 0.1238, F1: 0.5357

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.28107 | val 3.36246
  Epoch 011 - train 0.24710 | val 3.01531
  Classification -> best τ=0.630 (val F1=0.1009)
  Directional -> Accuracy: 0.3878, MCC: -0.2239, F1: 0.3478

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.54484 | val 1.08896
  Epoch 012 - train 0.38901 | val 0.87855
  Classification -> best τ=0.520 (val F1=0.0898)
  Directional -> Accuracy: 0.6000, MCC: 0.1372, F1: 0.6897

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.43029 | val 0.90222
  Epoch 011 - train 0.39455 | val 0.98590
  Classification -> best τ=0.180 (val F1=0.2312)
  Directional -> Accuracy: 0.5254, MCC: -0.1663, F1: 0.6889

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.31463 | val 1.06662
  Epoch 012 - train 0.28585 | val 1.49519
  Classification -> best τ=0.505 (val F1=0.1956)
  Directional -> Accuracy: 0.4773, MCC: -0.0498, F1: 0.5106

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.43106 | val 1.25349
  Epoch 012 - train 0.33632 | val 1.33836
  Classification -> best τ=0.510 (val F1=0.1836)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.4889

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.42123 | val 1.22184
  Epoch 012 - train 0.36179 | val 1.57429
  Classification -> best τ=0.560 (val F1=0.1471)
  Directional -> Accuracy: 0.5000, MCC: -0.0371, F1: 0.5965

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.34353 | val 1.12363
  Epoch 012 - train 0.29718 | val 1.46487
  Classification -> best τ=0.375 (val F1=0.2935)
  Directional -> Accuracy: 0.4808, MCC: -0.1925, F1: 0.6494

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.68459 | val 0.76114
  Epoch 013 - train 0.40892 | val 0.79463
  Classification -> best τ=0.305 (val F1=0.3565)
  Directional -> Accuracy: 0.5600, MCC: 0.0000, F1: 0.7179

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 82). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.34566 | val 1.20886
  Epoch 011 - train 0.37361 | val 1.30224
  Classification -> best τ=0.545 (val F1=0.3518)
  Directional -> Accuracy: 0.5122, MCC: 0.1543, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.33262 | val 0.98499
  Epoch 011 - train 0.30598 | val 1.02032
  Classification -> best τ=0.330 (val F1=0.2421)
  Directional -> Accuracy: 0.4565, MCC: 0.0000, F1: 0.6269

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.48220 | val 0.83518
  Epoch 011 - train 0.42137 | val 0.85525
  Classification -> best τ=0.315 (val F1=0.2717)
  Directional -> Accuracy: 0.5797, MCC: 0.2824, F1: 0.4912

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.59399 | val 1.02828
  Epoch 016 - train 0.21618 | val 1.35979
  Classification -> best τ=0.245 (val F1=0.3859)
  Directional -> Accuracy: 0.5556, MCC: 0.1094, F1: 0.6154

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.48530 | val 1.74019
  Epoch 011 - train 0.42218 | val 1.78494
  Classification -> best τ=0.500 (val F1=0.1667)
  Directional -> Accuracy: 0.5424, MCC: 0.1137, F1: 0.6087

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.45285 | val 0.79447
  Epoch 013 - train 0.25455 | val 1.48024
  Classification -> best τ=0.385 (val F1=0.3515)
  Directional -> Accuracy: 0.5918, MCC: -0.0285, F1: 0.7368

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 82). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 82). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 82). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 82). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.40553 | val 1.30054
  Epoch 011 - train 0.39807 | val 1.11856
  Classification -> best τ=0.395 (val F1=0.2503)
  Directional -> Accuracy: 0.3333, MCC: 0.0000, F1: 0.5000

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 82). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.37109 | val 1.62286
  Epoch 012 - train 0.30762 | val 1.58836
  Classification -> best τ=0.650 (val F1=0.2467)
  Directional -> Accuracy: 0.5366, MCC: 0.2210, F1: 0.1739

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 82). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 82). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.44989 | val 1.98041
  Epoch 012 - train 0.36909 | val 1.77637
  Classification -> best τ=0.560 (val F1=0.1191)
  Directional -> Accuracy: 0.5714, MCC: 0.1909, F1: 0.6857

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 82). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 82). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.42467 | val 2.08567
  Epoch 011 - train 0.39330 | val 2.47820
  Classification -> best τ=0.650 (val F1=0.2296)
  Directional -> Accuracy: 0.5510, MCC: 0.1954, F1: 0.6765

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.26669 | val 2.86048
  Epoch 011 - train 0.26352 | val 3.08737
  Classification -> best τ=0.425 (val F1=0.1850)
  Directional -> Accuracy: 0.4255, MCC: -0.1413, F1: 0.4490

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.39965 | val 1.20541
  Epoch 011 - train 0.34488 | val 1.32390
  Classification -> best τ=0.500 (val F1=0.5666)
  Directional -> Accuracy: 0.5952, MCC: 0.1848, F1: 0.5143

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.52902 | val 0.75836
  Epoch 014 - train 0.45717 | val 0.95755
  Classification -> best τ=0.650 (val F1=0.2581)
  Directional -> Accuracy: 0.5000, MCC: 0.2105, F1: 0.1714

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.38623 | val 1.27212
  Epoch 011 - train 0.31921 | val 1.38624
  Classification -> best τ=0.485 (val F1=0.3112)
  Directional -> Accuracy: 0.5085, MCC: 0.0000, F1: 0.0000

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.56095 | val 1.07622
  Epoch 011 - train 0.49122 | val 1.05539
  Classification -> best τ=0.345 (val F1=0.1054)
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.47871 | val 1.47722
  Epoch 011 - train 0.37969 | val 1.51408
  Classification -> best τ=0.450 (val F1=0.1153)
  Directional -> Accuracy: 0.5172, MCC: 0.0000, F1: 0.6818

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.54718 | val 0.84271

[I 2026-02-22 08:43:17,965] Trial 25 finished with value: 0.2594950965752363 and parameters: {'feature_set': 'sector_finbert', 'model_type': 'BiGRU', 'sequence_length': 6, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.4, 'dropout': 0.0, 'batch_size': 32, 'learning_rate': 0.005273981739073453, 'weight_decay': 6.903411056954983e-06, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 1.0880598210314512, 'early_stopping_min_delta': 0.008621775412600525}. Best is trial 22 with value: 0.2833350641483003.

  Epoch 018 - train 0.32833 | val 0.69521
  Classification -> best τ=0.490 (val F1=0.2821)
  Directional -> Accuracy: 0.4444, MCC: -0.1348, F1: 0.3137

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2594950965752363
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: classification
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'positive_emotion', 'negative_emotion', 'uncertainty_emotion', 'positive_emotion_pct', 'negative_emotion_pct', 'uncertainty_emotion_pct']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.46425 | val 1.50818
  Epoch 011 - train 0.39605 | val 2.05875
  Classification -> best τ=0.560 (val F1=0.2851)
  Directional -> Accuracy: 0.5714, MCC: 0.1389, F1: 0.1538

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.32668 | val 3.36634
  Epoch 011 - train 0.29097 | val 1.84353
  Classification -> best τ=0.570 (val F1=0.1168)
  Directional -> Accuracy: 0.6522, MCC: 0.2852, F1: 0.7037

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.29095 | val 1.01102
  Epoch 012 - train 0.16917 | val 0.82664
  Classification -> best τ=0.490 (val F1=0.4623)
  Directional -> Accuracy: 0.5957, MCC: 0.1864, F1: 0.6885

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.42976 | val 3.94320
  Epoch 011 - train 0.35861 | val 4.46612
  Classification -> best τ=0.455 (val F1=0.1868)
  Directional -> Accuracy: 0.5600, MCC: 0.1145, F1: 0.5926

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.31234 | val 2.72798
  Epoch 011 - train 0.16642 | val 3.11900
  Classification -> best τ=0.480 (val F1=0.4850)
  Directional -> Accuracy: 0.6863, MCC: 0.3686, F1: 0.7143

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.22769 | val 4.12683
  Epoch 011 - train 0.19449 | val 3.30876
  Classification -> best τ=0.545 (val F1=0.3873)
  Directional -> Accuracy: 0.6170, MCC: 0.3078, F1: 0.4000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.31523 | val 1.46156
  Epoch 011 - train 0.24653 | val 1.80082
  Classification -> best τ=0.365 (val F1=0.1667)
  Directional -> Accuracy: 0.4058, MCC: 0.0000, F1: 0.5773

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.13174 | val 2.38060
  Epoch 011 - train 0.10101 | val 3.37945
  Classification -> best τ=0.480 (val F1=0.1752)
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.5806

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.27018 | val 1.32962
  Epoch 011 - train 0.18216 | val 2.02688
  Classification -> best τ=0.530 (val F1=0.2265)
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.36854 | val 0.84565
  Epoch 011 - train 0.25541 | val 0.95649
  Classification -> best τ=0.445 (val F1=0.1869)
  Directional -> Accuracy: 0.4143, MCC: -0.1018, F1: 0.5773

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.26474 | val 2.32151
  Epoch 011 - train 0.21331 | val 2.41584
  Classification -> best τ=0.610 (val F1=0.1750)
  Directional -> Accuracy: 0.5800, MCC: 0.1445, F1: 0.3226

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.42842 | val 3.05901
  Epoch 011 - train 0.34478 | val 2.67759
  Classification -> best τ=0.285 (val F1=0.1982)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.24955 | val 2.94074
  Epoch 011 - train 0.18820 | val 3.17232
  Classification -> best τ=0.370 (val F1=0.2719)
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.39691 | val 1.41305
  Epoch 012 - train 0.33355 | val 1.30420
  Classification -> best τ=0.440 (val F1=0.3225)
  Directional -> Accuracy: 0.5902, MCC: 0.2087, F1: 0.6835

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.29949 | val 1.89251
  Epoch 011 - train 0.19760 | val 1.82086
  Classification -> best τ=0.450 (val F1=0.1449)
  Directional -> Accuracy: 0.5769, MCC: 0.1670, F1: 0.2143

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.40799 | val 1.77661
  Epoch 011 - train 0.32757 | val 2.04210
  Classification -> best τ=0.555 (val F1=0.4029)
  Directional -> Accuracy: 0.5714, MCC: 0.1200, F1: 0.6512

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.25129 | val 2.92809
  Epoch 011 - train 0.23586 | val 4.00978
  Classification -> best τ=0.605 (val F1=0.1336)
  Directional -> Accuracy: 0.3729, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.36007 | val 1.67908
  Epoch 011 - train 0.26867 | val 1.93762
  Classification -> best τ=0.550 (val F1=0.1199)
  Directional -> Accuracy: 0.3947, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.27092 | val 2.70825
  Epoch 011 - train 0.28213 | val 3.47758
  Classification -> best τ=0.690 (val F1=0.1348)
  Directional -> Accuracy: 0.4154, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.37110 | val 1.79816
  Epoch 011 - train 0.26919 | val 1.44263
  Classification -> best τ=0.435 (val F1=0.2434)
  Directional -> Accuracy: 0.5600, MCC: 0.1277, F1: 0.7130

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.24888 | val 1.12460
  Epoch 011 - train 0.15610 | val 1.23686
  Classification -> best τ=0.500 (val F1=0.2174)
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.40643 | val 1.62631
  Epoch 011 - train 0.31914 | val 1.79238
  Classification -> best τ=0.510 (val F1=0.2075)
  Directional -> Accuracy: 0.4697, MCC: -0.0928, F1: 0.6154

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.26110 | val 1.97632
  Epoch 011 - train 0.15141 | val 1.80325
  Classification -> best τ=0.490 (val F1=0.2817)
  Directional -> Accuracy: 0.5690, MCC: 0.0000, F1: 0.7253

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.35098 | val 1.36407
  Epoch 011 - train 0.26821 | val 1.14693
  Classification -> best τ=0.405 (val F1=0.1920)
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.6392

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.33529 | val 1.14987
  Epoch 012 - train 0.24718 | val 2.01152
  Classification -> best τ=0.580 (val F1=0.2379)
  Directional -> Accuracy: 0.4464, MCC: 0.0000, F1: 0.0000

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.12158 | val 1.65990
  Epoch 014 - train 0.04002 | val 2.26978
  Classification -> best τ=0.400 (val F1=0.4124)
  Directional -> Accuracy: 0.6087, MCC: 0.2431, F1: 0.1818

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.30712 | val 1.07552
  Epoch 014 - train 0.15537 | val 0.94405
  Classification -> best τ=0.510 (val F1=0.3895)
  Directional -> Accuracy: 0.3953, MCC: -0.1599, F1: 0.3158

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.34294 | val 1.55957
  Epoch 011 - train 0.23527 | val 1.96446
  Classification -> best τ=0.475 (val F1=0.1011)
  Directional -> Accuracy: 0.4211, MCC: -0.1512, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.23703 | val 1.32426
  Epoch 011 - train 0.30293 | val 1.13537
  Classification -> best τ=0.480 (val F1=0.3974)
  Directional -> Accuracy: 0.5854, MCC: 0.1688, F1: 0.7018

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.14776 | val 3.06261
  Epoch 011 - train 0.10658 | val 2.75043
  Classification -> best τ=0.600 (val F1=0.3337)
  Directional -> Accuracy: 0.4884, MCC: -0.0397, F1: 0.3125

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.17698 | val 1.09234
  Epoch 011 - train 0.16531 | val 1.31436
  Classification -> best τ=0.460 (val F1=0.0985)
  Directional -> Accuracy: 0.5349, MCC: 0.0282, F1: 0.6667

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.26080 | val 1.69269
  Epoch 011 - train 0.18968 | val 1.93535
  Classification -> best τ=0.475 (val F1=0.4255)
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.41480 | val 0.99344
  Epoch 012 - train 0.28889 | val 1.17508
  Classification -> best τ=0.280 (val F1=0.3602)
  Directional -> Accuracy: 0.5342, MCC: 0.1465, F1: 0.4333

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.10260 | val 2.70009
  Epoch 011 - train 0.08614 | val 3.08821
  Classification -> best τ=0.490 (val F1=0.1085)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.14744 | val 1.35333
  Epoch 011 - train 0.09736 | val 2.55891
  Classification -> best τ=0.510 (val F1=0.2358)
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.35382 | val 0.91956
  Epoch 015 - train 0.15319 | val 1.25149
  Classification -> best τ=0.335 (val F1=0.4396)
  Directional -> Accuracy: 0.4179, MCC: -0.1357, F1: 0.3810

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.18736 | val 1.94166
  Epoch 011 - train 0.11611 | val 2.09483
  Classification -> best τ=0.550 (val F1=0.2888)
  Directional -> Accuracy: 0.6512, MCC: 0.3392, F1: 0.5714

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.33600 | val 2.14045
  Epoch 011 - train 0.26464 | val 2.66724
  Classification -> best τ=0.355 (val F1=0.2816)
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.17879 | val 2.93450
  Epoch 011 - train 0.13235 | val 2.92701
  Classification -> best τ=0.505 (val F1=0.2718)
  Directional -> Accuracy: 0.6170, MCC: 0.0000, F1: 0.7632

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.14513 | val 1.83114
  Epoch 013 - train 0.03153 | val 2.43595
  Classification -> best τ=0.545 (val F1=0.2417)
  Directional -> Accuracy: 0.4082, MCC: -0.1013, F1: 0.4314

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.14065 | val 5.31765
  Epoch 011 - train 0.09258 | val 5.87898
  Classification -> best τ=0.495 (val F1=0.0134)
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.0000

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.42931 | val 1.64486
  Epoch 011 - train 0.35337 | val 2.40000
  Classification -> best τ=0.435 (val F1=0.2338)
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.21299 | val 2.16384
  Epoch 012 - train 0.15321 | val 2.05282
  Classification -> best τ=0.445 (val F1=0.3069)
  Directional -> Accuracy: 0.4255, MCC: -0.2169, F1: 0.5714

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.10730 | val 2.94435
  Epoch 011 - train 0.06688 | val 3.03070
  Classification -> best τ=0.535 (val F1=0.2100)
  Directional -> Accuracy: 0.6136, MCC: 0.1841, F1: 0.7119

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.14518 | val 4.76020
  Epoch 011 - train 0.10537 | val 3.93373
  Classification -> best τ=0.450 (val F1=0.0945)
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.25324 | val 1.39254
  Epoch 011 - train 0.24156 | val 2.50368
  Classification -> best τ=0.450 (val F1=0.2392)
  Directional -> Accuracy: 0.6250, MCC: 0.2751, F1: 0.7273

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.25670 | val 1.35985
  Epoch 011 - train 0.15958 | val 1.68554
  Classification -> best τ=0.595 (val F1=0.4250)
  Directional -> Accuracy: 0.5088, MCC: 0.0398, F1: 0.5758

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.36259 | val 1.26617
  Epoch 011 - train 0.30920 | val 1.14126
  Classification -> best τ=0.565 (val F1=0.1626)
  Directional -> Accuracy: 0.6296, MCC: 0.2610, F1: 0.6296

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.23086 | val 0.95000
  Epoch 011 - train 0.25623 | val 0.98867
  Classification -> best τ=0.540 (val F1=0.2222)
  Directional -> Accuracy: 0.4643, MCC: -0.0791, F1: 0.5161

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.43771 | val 1.57596

[I 2026-02-22 08:44:38,121] Trial 26 finished with value: 0.25002387782214464 and parameters: {'feature_set': 'unified_emotion', 'model_type': 'LSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.1, 'batch_size': 16, 'learning_rate': 0.00252828822599507, 'weight_decay': 9.117020956655212e-05, 'lr_patience': 7, 'lr_factor': 0.8, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 0.11445339306128088, 'early_stopping_min_delta': 0.009102916721259329}. Best is trial 22 with value: 0.2833350641483003.

  Epoch 015 - train 0.24180 | val 0.80472
  Classification -> best τ=0.495 (val F1=0.2451)
  Directional -> Accuracy: 0.4590, MCC: -0.0797, F1: 0.4590

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.25002387782214464
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: classification
Sequence length: 30
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d', 'sentiment']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.63443 | val 0.87781
  Epoch 011 - train 0.62610 | val 0.87974
  Classification -> best τ=0.540 (val F1=0.1771)
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.0000

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 106). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.62717 | val 0.80565
  Epoch 011 - train 0.61941 | val 0.81340
  Classification -> best τ=0.490 (val F1=0.2503)
  Directional -> Accuracy: 0.4773, MCC: 0.1091, F1: 0.3030

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 106). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.66201 | val 0.84427
  Epoch 011 - train 0.63264 | val 0.85281
  Classification -> best τ=0.540 (val F1=0.2319)
  Directional -> Accuracy: 0.4889, MCC: 0.1410, F1: 0.0800

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.65990 | val 0.97692
  Epoch 011 - train 0.64873 | val 1.00514
  Classification -> best τ=0.405 (val F1=0.1896)
  Directional -> Accuracy: 0.5342, MCC: 0.0115, F1: 0.6909

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.57690 | val 0.65968
  Epoch 020 - train 0.53082 | val 0.69370
  Epoch 021 - train 0.52968 | val 0.69499
  Classification -> best τ=0.635 (val F1=0.3405)
  Directional -> Accuracy: 0.5714, MCC: 0.2119, F1: 0.3636

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.60966 | val 0.73345
  Epoch 011 - train 0.59870 | val 0.74532
  Classification -> best τ=0.505 (val F1=0.1787)
  Directional -> Accuracy: 0.4889, MCC: 0.0000, F1: 0.6567

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.64985 | val 1.11538
  Epoch 011 - train 0.65344 | val 1.15810
  Classification -> best τ=0.405 (val F1=0.1690)
  Directional -> Accuracy: 0.4030, MCC: 0.0000, F1: 0.5745

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 106). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 106). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.63826 | val 0.78305
  Epoch 011 - train 0.63499 | val 0.76930
  Classification -> best τ=0.520 (val F1=0.2646)
  Directional -> Accuracy: 0.5610, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.64149 | val 0.68837
  Epoch 015 - train 0.58314 | val 0.68198
  Classification -> best τ=0.340 (val F1=0.2453)
  Directional -> Accuracy: 0.4468, MCC: 0.0000, F1: 0.6176

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 106). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 106). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 106). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.62751 | val 1.16956
  Epoch 011 - train 0.62770 | val 1.21619
  Classification -> best τ=0.485 (val F1=0.2768)
  Directional -> Accuracy: 0.4265, MCC: -0.0825, F1: 0.5185

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.62195 | val 0.90651
  Epoch 011 - train 0.61542 | val 0.91191
  Classification -> best τ=0.565 (val F1=0.1650)
  Directional -> Accuracy: 0.5208, MCC: 0.1036, F1: 0.6102

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.64116 | val 0.93458
  Epoch 011 - train 0.64684 | val 0.95379
  Classification -> best τ=0.475 (val F1=0.2067)
  Directional -> Accuracy: 0.5179, MCC: 0.0000, F1: 0.6824

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 106). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.57695 | val 1.41044
  Epoch 011 - train 0.57944 | val 1.41549
  Classification -> best τ=0.535 (val F1=0.5001)
  Directional -> Accuracy: 0.4490, MCC: -0.1264, F1: 0.2703

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 106). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.65824 | val 0.64867
  Epoch 018 - train 0.62276 | val 0.74616
  Classification -> best τ=0.630 (val F1=0.3343)
  Directional -> Accuracy: 0.4915, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.63331 | val 1.17159
  Epoch 011 - train 0.62583 | val 1.18701
  Classification -> best τ=0.490 (val F1=0.0580)
  Directional -> Accuracy: 0.5600, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.64184 | val 0.72509
  Epoch 011 - train 0.64307 | val 0.72738
  Classification -> best τ=0.400 (val F1=0.3279)
  Directional -> Accuracy: 0.5147, MCC: -0.0141, F1: 0.6452

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 106). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.63476 | val 0.82023
  Epoch 011 - train 0.63870 | val 0.83331
  Classification -> best τ=0.515 (val F1=0.1890)
  Directional -> Accuracy: 0.5088, MCC: -0.1175, F1: 0.6410

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.63244 | val 1.08828
  Epoch 011 - train 0.63767 | val 1.11121
  Classification -> best τ=0.495 (val F1=0.2065)
  Directional -> Accuracy: 0.5811, MCC: 0.1357, F1: 0.6437

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.63465 | val 0.74179
  Epoch 011 - train 0.64169 | val 0.74556
  Classification -> best τ=0.485 (val F1=0.1280)
  Directional -> Accuracy: 0.5079, MCC: 0.1877, F1: 0.3404

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 106). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.63640 | val 0.93235
  Epoch 011 - train 0.63945 | val 0.94526
  Classification -> best τ=0.495 (val F1=0.1501)
  Directional -> Accuracy: 0.5205, MCC: 0.1097, F1: 0.3860

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.63869 | val 0.75333
  Epoch 011 - train 0.63729 | val 0.76397
  Classification -> best τ=0.445 (val F1=0.1860)
  Directional -> Accuracy: 0.6087, MCC: 0.0000, F1: 0.7568

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 106). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 106). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 106). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.63355 | val 0.83448
  Epoch 011 - train 0.64663 | val 0.84505
  Classification -> best τ=0.495 (val F1=0.1855)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.64451 | val 0.89185
  Epoch 011 - train 0.62898 | val 0.91092
  Classification -> best τ=0.495 (val F1=0.1620)
  Directional -> Accuracy: 0.6071, MCC: 0.1667, F1: 0.7027

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.61165 | val 1.66049
  Epoch 011 - train 0.61347 | val 1.70704
  Classification -> best τ=0.615 (val F1=0.1932)
  Directional -> Accuracy: 0.5625, MCC: 0.1276, F1: 0.2222

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.58154 | val 0.76047
  Epoch 013 - train 0.59627 | val 0.79937
  Classification -> best τ=0.470 (val F1=0.4448)
  Directional -> Accuracy: 0.5741, MCC: 0.2103, F1: 0.4651

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.59381 | val 0.78124
  Epoch 011 - train 0.59148 | val 0.79591
  Classification -> best τ=0.495 (val F1=0.4148)
  Directional -> Accuracy: 0.5581, MCC: -0.0473, F1: 0.0952

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.62978 | val 0.70822
  Epoch 011 - train 0.63877 | val 0.70876
  Classification -> best τ=0.515 (val F1=0.1269)
  Directional -> Accuracy: 0.5918, MCC: 0.0557, F1: 0.7297

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.62628 | val 0.71025
  Epoch 013 - train 0.62144 | val 0.72473
  Classification -> best τ=0.525 (val F1=0.3398)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.64473 | val 0.69168
  Epoch 011 - train 0.64716 | val 0.68766
  Classification -> best τ=0.520 (val F1=0.1510)
  Directional -> Accuracy: 0.5263, MCC: -0.0371, F1: 0.6667

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.66699 | val 0.89559
  Epoch 011 - train 0.66197 | val 0.90731
  Classification -> best τ=0.440 (val F1=0.1425)
  Directional -> Accuracy: 0.5610, MCC: 0.2146, F1: 0.6786

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.63603 | val 0.84114
  Epoch 011 - train 0.61553 | val 0.84532
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5610, MCC: 0.0000, F1: 0.7188

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.61340 | val 0.72994
  Epoch 013 - train 0.59791 | val 0.76101
  Classification -> best τ=0.455 (val F1=0.3672)
  Directional -> Accuracy: 0.6042, MCC: 0.2680, F1: 0.7164

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.62285 | val 1.40239
  Epoch 011 - train 0.63584 | val 1.40985
  Classification -> best τ=0.455 (val F1=0.2428)
  Directional -> Accuracy: 0.5493, MCC: 0.2029, F1: 0.4286

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 106). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.61323 | val 0.70817
  Epoch 011 - train 0.61133 | val 0.71146
  Classification -> best τ=0.465 (val F1=0.3412)
  Directional -> Accuracy: 0.5714, MCC: 0.2530, F1: 0.6786

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for PCG (101 < 106). Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.60682 | val 0.91157
  Epoch 011 - train 0.63280 | val 0.91990
  Classification -> best τ=0.425 (val F1=0.3828)
  Directional -> Accuracy: 0.5231, MCC: 0.2313, F1: 0.3111

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.61352 | val 0.68959
  Epoch 011 - train 0.59621 | val 0.69242
  Classification -> best τ=0.525 (val F1=0.2268)
  Directional -> Accuracy: 0.4000, MCC: -0.2101, F1: 0.4545

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.59875 | val 0.82954
  Epoch 011 - train 0.58088 | val 0.83338
  Classification -> best τ=0.490 (val F1=0.2458)
  Directional -> Accuracy: 0.5636, MCC: 0.1587, F1: 0.6000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.58264 | val 1.13522
  Epoch 011 - train 0.61963 | val 1.11855
  Classification -> best τ=0.545 (val F1=0.2913)
  Directional -> Accuracy: 0.5111, MCC: -0.0165, F1: 0.5926

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 106). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 106). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 106). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 106). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.62821 | val 0.69162
  Epoch 015 - train 0.59073 | val 0.78290
  Classification -> best τ=0.555 (val F1=0.4326)
  Directional -> Accuracy: 0.3261, MCC: 0.0000, F1: 0.4918

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 106). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 106). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 106). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.58966 | val 0.79337
  Epoch 011 - train 0.60535 | val 0.81477
  Classification -> best τ=0.495 (val F1=0.1785)
  Directional -> Accuracy: 0.4658, MCC: -0.0855, F1: 0.2909

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 106). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 106). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 106). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 106). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.63919 | val 0.68038
  Epoch 014 - train 0.62501 | val 0.68404
  Classification -> best τ=0.390 (val F1=0.4801)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.62334 | val 0.72223
  Epoch 011 - train 0.62480 | val 0.72377
  Classification -> best τ=0.480 (val F1=0.3568)
  Directional -> Accuracy: 0.4146, MCC: 0.0000, F1: 0.0000

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.62687 | val 0.79671
  Epoch 011 - train 0.61545 | val 0.80367
  Classification -> best τ=0.460 (val F1=0.1978)
  Directional -> Accuracy: 0.3696, MCC: 0.0000, F1: 0.5397

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.65109 | val 0.78759
  Epoch 011 - train 0.64362 | val 0.79488
  Classification -> best τ=0.480 (val F1=0.1115)
  Directional -> Accuracy: 0.7222, MCC: 0.5029, F1: 0.6939

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.62868 | val 1.07360
  Epoch 011 - train 0.61163 | val 1.10485
  Classification -> best τ=0.530 (val F1=0.2537)
  Directional -> Accuracy: 0.4545, MCC: -0.0917, F1: 0.5455

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.62973 | val 0.78996
  Epoch 011 - train 0.63987 | val 0.79133
  Classification -> best τ=0.455 (val F1=0.2037)
  Directional -> Accuracy: 0.4808, MCC: -0.0652, F1: 0.6301

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.62989 | val 0.71507
  Epoch 011 - train 0.63201 | val 0.70652
  Classification -> best τ=0.455 (val F1=0.0533)
  Directional -> Accuracy: 0.5370, MCC: 0.1425, F1: 0.6914

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.64139 | val 0.83601

[I 2026-02-22 08:47:06,829] Trial 27 finished with value: 0.2354486367626328 and parameters: {'feature_set': 'sector_sentiment', 'model_type': 'GRU', 'sequence_length': 30, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.30000000000000004, 'batch_size': 16, 'learning_rate': 0.0002124396370069558, 'weight_decay': 0.0002645087543677278, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 0.5240963326216522, 'early_stopping_min_delta': 0.00782802581698095}. Best is trial 22 with value: 0.2833350641483003.

  Epoch 011 - train 0.63004 | val 0.83783
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4746, MCC: 0.0000, F1: 0.6437

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2354486367626328
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.65687 | val 0.84741
  Epoch 016 - train 0.65267 | val 0.85683
  Classification -> best τ=0.480 (val F1=0.2039)
  Directional -> Accuracy: 0.5526, MCC: 0.0000, F1: 0.0000

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.67428 | val 0.72182
  Epoch 016 - train 0.68140 | val 0.75021
  Classification -> best τ=0.465 (val F1=0.1844)
  Directional -> Accuracy: 0.4889, MCC: 0.0318, F1: 0.4390

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.67787 | val 0.64776
  Epoch 020 - train 0.68701 | val 0.66780
  Classification -> best τ=0.510 (val F1=0.3835)
  Directional -> Accuracy: 0.5217, MCC: 0.2041, F1: 0.1538

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.68941 | val 1.48905
  Epoch 016 - train 0.67733 | val 1.46539
  Classification -> best τ=0.465 (val F1=0.2920)
  Directional -> Accuracy: 0.5541, MCC: 0.1130, F1: 0.5600

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.65999 | val 0.63516
  Epoch 020 - train 0.65436 | val 0.65649
  Classification -> best τ=0.550 (val F1=0.4139)
  Directional -> Accuracy: 0.6600, MCC: 0.3398, F1: 0.6222

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.68762 | val 0.72971
  Epoch 016 - train 0.67874 | val 0.74079
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4783, MCC: 0.0000, F1: 0.6471

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.66952 | val 0.75464
  Epoch 018 - train 0.66869 | val 0.77785
  Classification -> best τ=0.475 (val F1=0.2236)
  Directional -> Accuracy: 0.5441, MCC: 0.1157, F1: 0.5231

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.66902 | val 0.79530
  Epoch 016 - train 0.67003 | val 0.89193
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.66812 | val 0.75419
  Epoch 016 - train 0.66361 | val 0.79023
  Classification -> best τ=0.465 (val F1=0.1435)
  Directional -> Accuracy: 0.4375, MCC: -0.0263, F1: 0.5970

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.65593 | val 0.98582
  Epoch 016 - train 0.66064 | val 0.98768
  Classification -> best τ=0.435 (val F1=0.2287)
  Directional -> Accuracy: 0.4203, MCC: 0.0000, F1: 0.5918

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.68335 | val 0.74135
  Epoch 016 - train 0.65526 | val 0.74901
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4490, MCC: 0.0000, F1: 0.6197

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.68770 | val 0.76610
  Epoch 016 - train 0.70049 | val 0.77777
  Classification -> best τ=0.515 (val F1=0.1313)
  Directional -> Accuracy: 0.5614, MCC: 0.1520, F1: 0.6753

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.65046 | val 1.07120
  Epoch 016 - train 0.62799 | val 1.10348
  Classification -> best τ=0.450 (val F1=0.0548)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.6230

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.69530 | val 0.68483
  Epoch 020 - train 0.67599 | val 0.65762
  Classification -> best τ=0.450 (val F1=0.2839)
  Directional -> Accuracy: 0.4833, MCC: -0.1302, F1: 0.6517

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.64890 | val 0.86551
  Epoch 016 - train 0.65536 | val 0.85528
  Classification -> best τ=0.495 (val F1=0.0730)
  Directional -> Accuracy: 0.5490, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.65500 | val 0.73964
  Epoch 018 - train 0.66010 | val 0.75266
  Classification -> best τ=0.405 (val F1=0.2795)
  Directional -> Accuracy: 0.5797, MCC: 0.2293, F1: 0.7184

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.68293 | val 0.99801
  Epoch 016 - train 0.66876 | val 1.11712
  Classification -> best τ=0.485 (val F1=0.1065)
  Directional -> Accuracy: 0.3793, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.67531 | val 0.84593
  Epoch 016 - train 0.67145 | val 0.88459
  Classification -> best τ=0.495 (val F1=0.0805)
  Directional -> Accuracy: 0.5867, MCC: 0.1341, F1: 0.6593

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.67251 | val 0.71005
  Epoch 016 - train 0.64845 | val 0.71888
  Classification -> best τ=0.505 (val F1=0.1578)
  Directional -> Accuracy: 0.4844, MCC: 0.1062, F1: 0.2979

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.63241 | val 0.96434
  Epoch 018 - train 0.64364 | val 1.03673
  Classification -> best τ=0.385 (val F1=0.2699)
  Directional -> Accuracy: 0.5676, MCC: 0.2713, F1: 0.4074

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.68074 | val 0.71251
  Epoch 016 - train 0.66698 | val 0.71860
  Classification -> best τ=0.475 (val F1=0.1250)
  Directional -> Accuracy: 0.4043, MCC: -0.0121, F1: 0.1765

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.69460 | val 0.69377
  Epoch 019 - train 0.67767 | val 0.69950
  Classification -> best τ=0.505 (val F1=0.1879)
  Directional -> Accuracy: 0.4615, MCC: -0.1809, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.68329 | val 0.71180
  Epoch 019 - train 0.68828 | val 0.72836
  Classification -> best τ=0.475 (val F1=0.1803)
  Directional -> Accuracy: 0.5263, MCC: 0.0509, F1: 0.5574

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.67545 | val 0.72981
  Epoch 016 - train 0.66453 | val 0.75250
  Classification -> best τ=0.525 (val F1=0.1575)
  Directional -> Accuracy: 0.4769, MCC: -0.1024, F1: 0.1905

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.67107 | val 0.65331
  Epoch 020 - train 0.64854 | val 0.68512
  Classification -> best τ=0.505 (val F1=0.5197)
  Directional -> Accuracy: 0.5455, MCC: 0.1641, F1: 0.4186

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.65831 | val 0.70893
  Epoch 016 - train 0.66705 | val 0.72345
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.5938

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.66951 | val 0.74664
  Epoch 016 - train 0.67136 | val 0.75504
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.7273

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.65116 | val 0.66774
  Epoch 020 - train 0.65060 | val 0.67835
  Classification -> best τ=0.465 (val F1=0.2718)
  Directional -> Accuracy: 0.5357, MCC: 0.2812, F1: 0.2778

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.67941 | val 0.72804
  Epoch 016 - train 0.65670 | val 0.74697
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5500, MCC: 0.0000, F1: 0.7097

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.69124 | val 0.67987
  Epoch 020 - train 0.65936 | val 0.68649
  Classification -> best τ=0.600 (val F1=0.3501)
  Directional -> Accuracy: 0.5000, MCC: -0.0196, F1: 0.3636

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.69680 | val 0.74350
  Epoch 016 - train 0.68586 | val 0.79357
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5476, MCC: 0.0000, F1: 0.7077

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.69517 | val 0.65290
  Epoch 020 - train 0.66557 | val 0.66402
  Classification -> best τ=0.425 (val F1=0.3886)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.68148 | val 0.71002
  Epoch 016 - train 0.67474 | val 0.70818
  Classification -> best τ=0.515 (val F1=0.0756)
  Directional -> Accuracy: 0.4444, MCC: -0.1250, F1: 0.5000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.66456 | val 0.88480
  Epoch 016 - train 0.66431 | val 0.93326
  Classification -> best τ=0.535 (val F1=0.2804)
  Directional -> Accuracy: 0.5814, MCC: 0.1746, F1: 0.6250

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.67235 | val 0.69174
  Epoch 019 - train 0.66911 | val 0.70332
  Classification -> best τ=0.435 (val F1=0.3280)
  Directional -> Accuracy: 0.5909, MCC: 0.1666, F1: 0.6400

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.69224 | val 0.68548
  Epoch 020 - train 0.65499 | val 0.68408
  Classification -> best τ=0.485 (val F1=0.3001)
  Directional -> Accuracy: 0.5714, MCC: 0.2530, F1: 0.3571

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.65169 | val 0.73738
  Epoch 016 - train 0.63340 | val 0.74252
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4643, MCC: 0.0000, F1: 0.6341

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.67195 | val 0.83016
  Epoch 016 - train 0.64970 | val 0.81493
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.6087, MCC: 0.0000, F1: 0.7568

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.68106 | val 0.65470
  Epoch 020 - train 0.64125 | val 0.63654
  Classification -> best τ=0.565 (val F1=0.3800)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.66232 | val 0.74649
  Epoch 016 - train 0.65475 | val 0.76758
  Classification -> best τ=0.485 (val F1=0.0474)
  Directional -> Accuracy: 0.5135, MCC: 0.1622, F1: 0.6667

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.72435 | val 0.68509
  Epoch 016 - train 0.70724 | val 0.68568
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5111, MCC: 0.0000, F1: 0.6765

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.66361 | val 0.70356
  Epoch 016 - train 0.67182 | val 0.71233
  Classification -> best τ=0.505 (val F1=0.3118)
  Directional -> Accuracy: 0.5952, MCC: 0.2676, F1: 0.5405

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.66099 | val 0.77675
  Epoch 016 - train 0.67242 | val 0.81564
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.5455

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.69301 | val 0.73870
  Epoch 016 - train 0.68262 | val 0.75183
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5455, MCC: 0.0000, F1: 0.7059

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.66303 | val 1.06163
  Epoch 016 - train 0.64136 | val 1.15689
  Classification -> best τ=0.490 (val F1=0.3729)
  Directional -> Accuracy: 0.5357, MCC: 0.0994, F1: 0.6176

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.69064 | val 0.70938
  Epoch 016 - train 0.67502 | val 0.71206
  Classification -> best τ=0.530 (val F1=0.1646)
  Directional -> Accuracy: 0.5094, MCC: 0.0000, F1: 0.6750

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.64749 | val 1.30537
  Epoch 016 - train 0.64611 | val 1.45836
  Classification -> best τ=0.460 (val F1=0.0489)
  Directional -> Accuracy: 0.6364, MCC: 0.3324, F1: 0.7368

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.66800 | val 0.74777

[I 2026-02-22 08:53:41,730] Trial 28 finished with value: 0.16749994807425073 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.4, 'dropout': 0.2, 'batch_size': 16, 'learning_rate': 3.8986069338500215e-05, 'weight_decay': 2.7797482632170747e-06, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 15, 'max_epochs': 20, 'huber_delta': 0.7751486052649329, 'early_stopping_min_delta': 0.005201503407926736}. Best is trial 22 with value: 0.2833350641483003.

  Epoch 016 - train 0.65848 | val 0.75170
  Classification -> best τ=0.500 (val F1=0.0388)
  Directional -> Accuracy: 0.4833, MCC: -0.0357, F1: 0.4561

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.16749994807425073
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: classification
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sentiment']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.61585 | val 1.02368
  Epoch 014 - train 0.57731 | val 1.40101
  Classification -> best τ=0.475 (val F1=0.1514)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.56003 | val 0.66824
  Epoch 017 - train 0.49945 | val 1.13296
  Classification -> best τ=0.430 (val F1=0.3893)
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.7222

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.61290 | val 0.68446
  Epoch 019 - train 0.54725 | val 0.86468
  Classification -> best τ=0.540 (val F1=0.2376)
  Directional -> Accuracy: 0.5106, MCC: 0.0146, F1: 0.5490

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.63375 | val 1.25361
  Epoch 011 - train 0.63178 | val 1.40854
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.53429 | val 1.09941
  Epoch 011 - train 0.52340 | val 1.42858
  Classification -> best τ=0.505 (val F1=0.2571)
  Directional -> Accuracy: 0.5294, MCC: 0.0435, F1: 0.6000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.54813 | val 0.71883
  Epoch 011 - train 0.54213 | val 0.76490
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4894, MCC: 0.0000, F1: 0.6571

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.61492 | val 0.96599
  Epoch 011 - train 0.60657 | val 0.93160
  Classification -> best τ=0.465 (val F1=0.1001)
  Directional -> Accuracy: 0.5072, MCC: -0.0104, F1: 0.4138

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.55535 | val 1.16689
  Epoch 011 - train 0.53787 | val 1.20718
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.5806

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.58434 | val 0.69842
  Epoch 011 - train 0.57612 | val 0.75005
  Classification -> best τ=0.465 (val F1=0.2949)
  Directional -> Accuracy: 0.6735, MCC: 0.3783, F1: 0.4667

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.56741 | val 0.79850
  Epoch 011 - train 0.54716 | val 0.78557
  Classification -> best τ=0.460 (val F1=0.1187)
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.59508 | val 0.95515
  Epoch 011 - train 0.60387 | val 1.07779
  Classification -> best τ=0.535 (val F1=0.0505)
  Directional -> Accuracy: 0.5600, MCC: 0.1272, F1: 0.5600

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.59035 | val 1.60978
  Epoch 011 - train 0.56292 | val 1.51947
  Classification -> best τ=0.510 (val F1=0.0917)
  Directional -> Accuracy: 0.5690, MCC: 0.2265, F1: 0.6914

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.51660 | val 0.76923
  Epoch 020 - train 0.46867 | val 0.81335
  Epoch 030 - train 0.41188 | val 0.81973
  Epoch 035 - train 0.38615 | val 0.82812
  Classification -> best τ=0.755 (val F1=0.4020)
  Directional -> Accuracy: 0.6977, MCC: 0.3841, F1: 0.6486

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.61520 | val 0.67921
  Epoch 016 - train 0.56538 | val 0.70351
  Classification -> best τ=0.460 (val F1=0.2012)
  Directional -> Accuracy: 0.5574, MCC: 0.1199, F1: 0.6400

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.53306 | val 0.70696
  Epoch 011 - train 0.54061 | val 0.68973
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4615, MCC: 0.0000, F1: 0.6316

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.54817 | val 0.96684
  Epoch 015 - train 0.54704 | val 1.02121
  Classification -> best τ=0.350 (val F1=0.2516)
  Directional -> Accuracy: 0.6000, MCC: 0.2683, F1: 0.7308

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.61504 | val 1.06413
  Epoch 011 - train 0.61180 | val 1.25122
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.63466 | val 1.30901
  Epoch 011 - train 0.62265 | val 1.52628
  Classification -> best τ=0.470 (val F1=0.0028)
  Directional -> Accuracy: 0.3947, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.58584 | val 0.85737
  Epoch 011 - train 0.57922 | val 1.04607
  Classification -> best τ=0.525 (val F1=0.1294)
  Directional -> Accuracy: 0.5077, MCC: 0.1597, F1: 0.3600

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.56161 | val 0.83546
  Epoch 015 - train 0.51722 | val 1.07796
  Classification -> best τ=0.410 (val F1=0.2599)
  Directional -> Accuracy: 0.6400, MCC: 0.2912, F1: 0.6400

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.59287 | val 1.32273
  Epoch 011 - train 0.57817 | val 1.38195
  Classification -> best τ=0.490 (val F1=0.0735)
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.62190 | val 1.01315
  Epoch 011 - train 0.61983 | val 0.85911
  Classification -> best τ=0.510 (val F1=0.0365)
  Directional -> Accuracy: 0.5909, MCC: 0.1928, F1: 0.5091

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.59526 | val 1.12914
  Epoch 011 - train 0.57588 | val 1.35232
  Classification -> best τ=0.505 (val F1=0.2253)
  Directional -> Accuracy: 0.5000, MCC: 0.1462, F1: 0.2927

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.57705 | val 0.84709
  Epoch 011 - train 0.56516 | val 0.89160
  Classification -> best τ=0.515 (val F1=0.1427)
  Directional -> Accuracy: 0.5000, MCC: -0.0055, F1: 0.4590

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.58627 | val 0.64093
  Epoch 019 - train 0.49540 | val 0.77103
  Classification -> best τ=0.445 (val F1=0.3824)
  Directional -> Accuracy: 0.5536, MCC: 0.1158, F1: 0.5614

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.54417 | val 0.77511
  Epoch 011 - train 0.52982 | val 0.79720
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.58458 | val 0.68566
  Epoch 020 - train 0.47350 | val 0.86471
  Epoch 027 - train 0.44726 | val 0.73259
  Classification -> best τ=0.500 (val F1=0.2603)
  Directional -> Accuracy: 0.5116, MCC: -0.0889, F1: 0.6441

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.57938 | val 1.04091
  Epoch 011 - train 0.58385 | val 1.08082
  Classification -> best τ=0.520 (val F1=0.0898)
  Directional -> Accuracy: 0.5965, MCC: 0.1651, F1: 0.6667

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.58515 | val 0.67687
  Epoch 020 - train 0.54829 | val 0.80674
  Epoch 021 - train 0.50011 | val 0.81595
  Classification -> best τ=0.630 (val F1=0.3548)
  Directional -> Accuracy: 0.4634, MCC: -0.0528, F1: 0.3889

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.59037 | val 0.86375
  Epoch 011 - train 0.60130 | val 0.90533
  Classification -> best τ=0.470 (val F1=0.1869)
  Directional -> Accuracy: 0.4884, MCC: -0.0528, F1: 0.2143

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.59977 | val 0.85612
  Epoch 011 - train 0.58298 | val 0.93632
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.58813 | val 0.86656
  Epoch 013 - train 0.54595 | val 1.13837
  Classification -> best τ=0.520 (val F1=0.0634)
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.59518 | val 0.69257
  Epoch 015 - train 0.57134 | val 0.76463
  Classification -> best τ=0.415 (val F1=0.3602)
  Directional -> Accuracy: 0.5753, MCC: 0.1768, F1: 0.5634

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.56691 | val 0.72535
  Epoch 011 - train 0.57793 | val 0.73578
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.60596 | val 0.84831
  Epoch 011 - train 0.60152 | val 0.92654
  Classification -> best τ=0.460 (val F1=0.1676)
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.57557 | val 0.84145
  Epoch 011 - train 0.56839 | val 0.79798
  Classification -> best τ=0.500 (val F1=0.3266)
  Directional -> Accuracy: 0.5970, MCC: 0.1543, F1: 0.6824

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.57006 | val 0.70804
  Epoch 011 - train 0.57610 | val 0.71073
  Classification -> best τ=0.500 (val F1=0.0429)
  Directional -> Accuracy: 0.5581, MCC: 0.1198, F1: 0.5366

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.56191 | val 0.76446
  Epoch 015 - train 0.53739 | val 0.96690
  Classification -> best τ=0.435 (val F1=0.3404)
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.54102 | val 1.13562
  Epoch 011 - train 0.54596 | val 1.21861
  Classification -> best τ=0.475 (val F1=0.2057)
  Directional -> Accuracy: 0.6170, MCC: 0.0000, F1: 0.7632

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.58350 | val 0.66957
  Epoch 020 - train 0.47411 | val 0.80933
  Epoch 025 - train 0.45703 | val 0.88855
  Classification -> best τ=0.155 (val F1=0.3568)
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.53157 | val 0.76786
  Epoch 011 - train 0.53342 | val 0.79662
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.57585 | val 0.81534
  Epoch 011 - train 0.55538 | val 1.01345
  Classification -> best τ=0.500 (val F1=0.2568)
  Directional -> Accuracy: 0.5467, MCC: 0.1305, F1: 0.6531

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.61030 | val 0.71672
  Epoch 011 - train 0.61332 | val 0.71916
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.53845 | val 0.74357
  Epoch 011 - train 0.53521 | val 0.76944
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5682, MCC: 0.0000, F1: 0.7246

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.55007 | val 0.75349
  Epoch 011 - train 0.55469 | val 0.77255
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.62012 | val 0.91593
  Epoch 016 - train 0.58706 | val 1.18595
  Classification -> best τ=0.565 (val F1=0.1979)
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.56252 | val 1.24496
  Epoch 011 - train 0.58131 | val 1.30487
  Classification -> best τ=0.540 (val F1=0.2362)
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.0000

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.58511 | val 1.57939
  Epoch 011 - train 0.58235 | val 1.55134
  Classification -> best τ=0.510 (val F1=0.1465)
  Directional -> Accuracy: 0.5926, MCC: 0.2085, F1: 0.6944

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.57742 | val 0.78025
  Epoch 011 - train 0.59474 | val 0.79796
  Classification -> best τ=0.495 (val F1=0.0838)
  Directional -> Accuracy: 0.5179, MCC: 0.0000, F1: 0.6824

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.58270 | val 0.69879

[I 2026-02-22 08:54:35,432] Trial 29 finished with value: 0.15477419668070588 and parameters: {'feature_set': 'sentinment', 'model_type': 'LSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.0, 'batch_size': 32, 'learning_rate': 0.001515725758306111, 'weight_decay': 2.1843865958551364e-05, 'lr_patience': 5, 'lr_factor': 0.8, 'early_stopping_patience': 10, 'max_epochs': 50, 'huber_delta': 1.5767929213587077, 'early_stopping_min_delta': 0.006425867379777291}. Best is trial 22 with value: 0.2833350641483003.

  Epoch 018 - train 0.56180 | val 0.85068
  Classification -> best τ=0.645 (val F1=0.2639)
  Directional -> Accuracy: 0.5246, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.15477419668070588
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 12
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d', 'positive_emotion', 'negative_emotion', 'uncertainty_emotion', 'positive_emotion_pct', 'negative_emotion_pct', 'uncertainty_emotion_pct']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.53546 | val 1.00158
  Epoch 011 - train 0.52052 | val 1.14476
  Classification -> best τ=0.455 (val F1=0.2593)
  Directional -> Accuracy: 0.5513, MCC: 0.1058, F1: 0.5333

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 88). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.53792 | val 0.98118
  Epoch 011 - train 0.50864 | val 0.96374
  Classification -> best τ=0.535 (val F1=0.1941)
  Directional -> Accuracy: 0.4681, MCC: -0.0273, F1: 0.3902

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 88). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.56727 | val 0.91524
  Epoch 011 - train 0.54567 | val 0.96876
  Classification -> best τ=0.515 (val F1=0.3012)
  Directional -> Accuracy: 0.4792, MCC: -0.1205, F1: 0.6154

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.55341 | val 0.86802
  Epoch 011 - train 0.53213 | val 0.96016
  Classification -> best τ=0.415 (val F1=0.1733)
  Directional -> Accuracy: 0.5395, MCC: 0.0000, F1: 0.7009

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.49075 | val 0.72043
  Epoch 012 - train 0.44538 | val 0.81245
  Classification -> best τ=0.525 (val F1=0.3213)
  Directional -> Accuracy: 0.6346, MCC: 0.3020, F1: 0.5957

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.53751 | val 0.84400
  Epoch 011 - train 0.50293 | val 0.87194
  Classification -> best τ=0.530 (val F1=0.4364)
  Directional -> Accuracy: 0.5102, MCC: 0.1414, F1: 0.0769

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.57394 | val 0.96970
  Epoch 011 - train 0.54737 | val 0.93968
  Classification -> best τ=0.510 (val F1=0.1798)
  Directional -> Accuracy: 0.6000, MCC: 0.1569, F1: 0.4815

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 88). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 88). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.56917 | val 1.10989
  Epoch 011 - train 0.56441 | val 0.99661
  Classification -> best τ=0.540 (val F1=0.1890)
  Directional -> Accuracy: 0.5111, MCC: 0.0260, F1: 0.4762

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.53409 | val 0.69984
  Epoch 013 - train 0.50393 | val 0.72375
  Classification -> best τ=0.605 (val F1=0.4315)
  Directional -> Accuracy: 0.6190, MCC: 0.2571, F1: 0.5789

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 88). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 88). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.52016 | val 1.24016
  Epoch 011 - train 0.50783 | val 1.35997
  Classification -> best τ=0.460 (val F1=0.1725)
  Directional -> Accuracy: 0.4507, MCC: -0.0060, F1: 0.5806

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.52784 | val 0.82264
  Epoch 011 - train 0.51813 | val 0.85480
  Classification -> best τ=0.595 (val F1=0.0462)
  Directional -> Accuracy: 0.4510, MCC: -0.1073, F1: 0.3913

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.53672 | val 0.85308
  Epoch 011 - train 0.51847 | val 0.86898
  Classification -> best τ=0.525 (val F1=0.2300)
  Directional -> Accuracy: 0.4237, MCC: -0.1546, F1: 0.4516

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.50469 | val 1.13726
  Epoch 011 - train 0.48181 | val 1.24623
  Classification -> best τ=0.505 (val F1=0.3985)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 88). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.58517 | val 0.60376
  Epoch 014 - train 0.51999 | val 0.66804
  Classification -> best τ=0.465 (val F1=0.4257)
  Directional -> Accuracy: 0.4839, MCC: -0.1280, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.53956 | val 0.74615
  Epoch 011 - train 0.51313 | val 0.76362
  Classification -> best τ=0.560 (val F1=0.2193)
  Directional -> Accuracy: 0.5283, MCC: 0.0112, F1: 0.0741

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.54453 | val 0.77585
  Epoch 011 - train 0.53263 | val 0.80376
  Classification -> best τ=0.455 (val F1=0.2103)
  Directional -> Accuracy: 0.4930, MCC: -0.1004, F1: 0.6400

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.54354 | val 1.09574
  Epoch 011 - train 0.54551 | val 1.07851
  Classification -> best τ=0.590 (val F1=0.1050)
  Directional -> Accuracy: 0.3833, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.54675 | val 1.05109
  Epoch 011 - train 0.51586 | val 1.10691
  Classification -> best τ=0.405 (val F1=0.2058)
  Directional -> Accuracy: 0.5325, MCC: 0.2326, F1: 0.4375

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.53787 | val 0.68322
  Epoch 011 - train 0.52164 | val 0.69929
  Classification -> best τ=0.480 (val F1=0.3431)
  Directional -> Accuracy: 0.5455, MCC: -0.0413, F1: 0.6809

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 88). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.54410 | val 1.08880
  Epoch 011 - train 0.53180 | val 1.06857
  Classification -> best τ=0.520 (val F1=0.1581)
  Directional -> Accuracy: 0.4342, MCC: -0.1369, F1: 0.0444

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.50366 | val 0.80352
  Epoch 011 - train 0.47025 | val 0.85077
  Classification -> best τ=0.490 (val F1=0.2003)
  Directional -> Accuracy: 0.5102, MCC: 0.0156, F1: 0.5714

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 88). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 88). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 88). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.52874 | val 0.79193
  Epoch 013 - train 0.46599 | val 0.91599
  Classification -> best τ=0.535 (val F1=0.2502)
  Directional -> Accuracy: 0.5672, MCC: 0.1949, F1: 0.3556

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.54290 | val 1.04947
  Epoch 011 - train 0.53202 | val 1.11594
  Classification -> best τ=0.485 (val F1=0.2298)
  Directional -> Accuracy: 0.5424, MCC: 0.1360, F1: 0.5091

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.54453 | val 1.09724
  Epoch 011 - train 0.54059 | val 1.17878
  Classification -> best τ=0.400 (val F1=0.2556)
  Directional -> Accuracy: 0.4776, MCC: -0.0209, F1: 0.5977

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.50911 | val 0.66329
  Epoch 014 - train 0.44063 | val 0.84472
  Classification -> best τ=0.590 (val F1=0.5244)
  Directional -> Accuracy: 0.5263, MCC: 0.1434, F1: 0.4000

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.53847 | val 1.06652
  Epoch 011 - train 0.49814 | val 1.08292
  Classification -> best τ=0.535 (val F1=0.1588)
  Directional -> Accuracy: 0.5833, MCC: 0.0000, F1: 0.0000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.51846 | val 1.62035
  Epoch 011 - train 0.52111 | val 1.69976
  Classification -> best τ=0.445 (val F1=0.0649)
  Directional -> Accuracy: 0.5909, MCC: 0.1132, F1: 0.6897

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.52553 | val 0.99089
  Epoch 011 - train 0.50872 | val 1.03695
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5517, MCC: 0.0000, F1: 0.7111

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.54605 | val 0.65838
  Epoch 020 - train 0.40019 | val 0.78712
  Classification -> best τ=0.505 (val F1=0.3929)
  Directional -> Accuracy: 0.5116, MCC: 0.0089, F1: 0.5714

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.55161 | val 0.76811
  Epoch 011 - train 0.53997 | val 0.79751
  Classification -> best τ=0.475 (val F1=0.0271)
  Directional -> Accuracy: 0.6222, MCC: 0.2541, F1: 0.5854

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.58614 | val 0.88121
  Epoch 011 - train 0.56743 | val 0.90462
  Classification -> best τ=0.500 (val F1=0.0993)
  Directional -> Accuracy: 0.4444, MCC: -0.1786, F1: 0.5763

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.52787 | val 0.80365
  Epoch 011 - train 0.48736 | val 0.87493
  Classification -> best τ=0.535 (val F1=0.1747)
  Directional -> Accuracy: 0.5294, MCC: 0.1007, F1: 0.4000

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.53530 | val 0.94956
  Epoch 011 - train 0.52270 | val 0.93024
  Classification -> best τ=0.485 (val F1=0.2058)
  Directional -> Accuracy: 0.4459, MCC: 0.0411, F1: 0.0889

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 88). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.55473 | val 0.73563
  Epoch 011 - train 0.55184 | val 0.75618
  Classification -> best τ=0.520 (val F1=0.2955)
  Directional -> Accuracy: 0.4872, MCC: 0.0000, F1: 0.6552

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.54293 | val 1.11721
  Epoch 011 - train 0.53459 | val 1.09614
  Classification -> best τ=0.545 (val F1=0.1071)
  Directional -> Accuracy: 0.5333, MCC: 0.0403, F1: 0.3636

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.52875 | val 1.48004
  Epoch 011 - train 0.53800 | val 1.49641
  Classification -> best τ=0.440 (val F1=0.2704)
  Directional -> Accuracy: 0.5882, MCC: 0.2025, F1: 0.5882

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.52922 | val 0.76920
  Epoch 011 - train 0.51006 | val 0.75329
  Classification -> best τ=0.500 (val F1=0.1765)
  Directional -> Accuracy: 0.5455, MCC: 0.1581, F1: 0.2308

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.51148 | val 1.24877
  Epoch 011 - train 0.51119 | val 1.38362
  Classification -> best τ=0.545 (val F1=0.1118)
  Directional -> Accuracy: 0.5517, MCC: 0.1701, F1: 0.6389

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.49273 | val 1.27239
  Epoch 011 - train 0.45935 | val 1.34080
  Classification -> best τ=0.510 (val F1=0.2799)
  Directional -> Accuracy: 0.6458, MCC: 0.1556, F1: 0.7733

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 88). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 88). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 88). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 88). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.54185 | val 0.68562
  Epoch 017 - train 0.43156 | val 0.73142
  Classification -> best τ=0.480 (val F1=0.3333)
  Directional -> Accuracy: 0.5500, MCC: -0.2446, F1: 0.0000

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 88). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.56176 | val 0.83066
  Epoch 011 - train 0.55735 | val 0.85881
  Classification -> best τ=0.505 (val F1=0.1762)
  Directional -> Accuracy: 0.5897, MCC: 0.1629, F1: 0.6667

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 88). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 88). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.52395 | val 1.46355
  Epoch 011 - train 0.49419 | val 1.67437
  Classification -> best τ=0.490 (val F1=0.1940)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 88). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 88). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 88). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.55845 | val 0.68343
  Epoch 018 - train 0.42141 | val 1.02938
  Classification -> best τ=0.560 (val F1=0.3616)
  Directional -> Accuracy: 0.6042, MCC: 0.2344, F1: 0.4865

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.54211 | val 1.00106
  Epoch 011 - train 0.51323 | val 1.01038
  Classification -> best τ=0.525 (val F1=0.1000)
  Directional -> Accuracy: 0.4222, MCC: -0.1685, F1: 0.0000

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.53402 | val 1.18793
  Epoch 011 - train 0.50631 | val 1.19888
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.3659, MCC: 0.0000, F1: 0.5357

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.58459 | val 0.88667
  Epoch 011 - train 0.57262 | val 0.89860
  Classification -> best τ=0.545 (val F1=0.2583)
  Directional -> Accuracy: 0.5263, MCC: 0.1018, F1: 0.4255

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.51007 | val 0.81435
  Epoch 012 - train 0.46665 | val 0.87919
  Classification -> best τ=0.625 (val F1=0.3832)
  Directional -> Accuracy: 0.5172, MCC: 0.0000, F1: 0.0000

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.58976 | val 0.78124
  Epoch 011 - train 0.58692 | val 0.79440
  Classification -> best τ=0.555 (val F1=0.1272)
  Directional -> Accuracy: 0.4182, MCC: -0.1590, F1: 0.2381

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.52825 | val 0.81075
  Epoch 011 - train 0.50991 | val 0.87642
  Classification -> best τ=0.470 (val F1=0.1512)
  Directional -> Accuracy: 0.4912, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.56164 | val 0.68666

[I 2026-02-22 08:55:37,405] Trial 30 finished with value: 0.2243471797261553 and parameters: {'feature_set': 'sector_unified_emotion', 'model_type': 'BiGRU', 'sequence_length': 12, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 32, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.1, 'batch_size': 16, 'learning_rate': 0.0007129874840297398, 'weight_decay': 9.9689954817831e-06, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 50, 'huber_delta': 0.5950285583335209, 'early_stopping_min_delta': 0.009172901885927665}. Best is trial 22 with value: 0.2833350641483003.

  Epoch 018 - train 0.40713 | val 0.91701
  Classification -> best τ=0.400 (val F1=0.3068)
  Directional -> Accuracy: 0.5645, MCC: 0.1315, F1: 0.5714

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2243471797261553
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 6
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d', 'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down', 'finbert_neutral']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.57077 | val 0.82291
  Epoch 012 - train 0.47056 | val 1.01417
  Classification -> best τ=0.730 (val F1=0.2727)
  Directional -> Accuracy: 0.5570, MCC: 0.0000, F1: 0.0000

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 82). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.43416 | val 1.33420
  Epoch 013 - train 0.31086 | val 1.39039
  Classification -> best τ=0.820 (val F1=0.2928)
  Directional -> Accuracy: 0.5000, MCC: 0.0053, F1: 0.5200

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 82). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.47381 | val 1.85832
  Epoch 011 - train 0.45952 | val 1.79589
  Classification -> best τ=0.535 (val F1=0.3077)
  Directional -> Accuracy: 0.4898, MCC: 0.0334, F1: 0.2424

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.54144 | val 0.97168
  Epoch 011 - train 0.51389 | val 0.72028
  Classification -> best τ=0.595 (val F1=0.2218)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.34509 | val 0.98282
  Epoch 012 - train 0.31146 | val 1.16385
  Classification -> best τ=0.560 (val F1=0.5017)
  Directional -> Accuracy: 0.6038, MCC: 0.2445, F1: 0.5333

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.42859 | val 0.94547
  Epoch 012 - train 0.30788 | val 0.84082
  Classification -> best τ=0.615 (val F1=0.2521)
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.43326 | val 1.11660
  Epoch 011 - train 0.39314 | val 1.25045
  Classification -> best τ=0.530 (val F1=0.2344)
  Directional -> Accuracy: 0.5352, MCC: 0.0009, F1: 0.3529

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 82). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 82). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.28610 | val 1.39259
  Epoch 011 - train 0.27370 | val 1.32892
  Classification -> best τ=0.550 (val F1=0.3469)
  Directional -> Accuracy: 0.3830, MCC: -0.1396, F1: 0.5397

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.39029 | val 1.11785
  Epoch 011 - train 0.30750 | val 1.32823
  Classification -> best τ=0.510 (val F1=0.1725)
  Directional -> Accuracy: 0.6047, MCC: 0.1178, F1: 0.3704

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 82). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 82). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.59505 | val 0.76282
  Epoch 012 - train 0.45605 | val 0.87048
  Classification -> best τ=0.480 (val F1=0.1838)
  Directional -> Accuracy: 0.5000, MCC: 0.0278, F1: 0.5135

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.43552 | val 1.28429
  Epoch 012 - train 0.36345 | val 1.02680
  Classification -> best τ=0.480 (val F1=0.1814)
  Directional -> Accuracy: 0.5577, MCC: 0.1128, F1: 0.5306

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.54900 | val 0.94272
  Epoch 012 - train 0.48482 | val 0.99719
  Classification -> best τ=0.485 (val F1=0.2247)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.37754 | val 1.74894
  Epoch 011 - train 0.34612 | val 1.67689
  Classification -> best τ=0.405 (val F1=0.1455)
  Directional -> Accuracy: 0.4667, MCC: 0.0000, F1: 0.6364

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 82). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.55523 | val 0.83618
  Epoch 015 - train 0.36191 | val 1.03100
  Classification -> best τ=0.265 (val F1=0.5000)
  Directional -> Accuracy: 0.4921, MCC: -0.0196, F1: 0.4286

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.41717 | val 0.80015
  Epoch 011 - train 0.30618 | val 0.82067
  Classification -> best τ=0.500 (val F1=0.2833)
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.46761 | val 1.31727
  Epoch 011 - train 0.37271 | val 1.60091
  Classification -> best τ=0.645 (val F1=0.3396)
  Directional -> Accuracy: 0.5694, MCC: 0.1866, F1: 0.4918

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.47903 | val 1.09206
  Epoch 012 - train 0.39181 | val 1.19077
  Classification -> best τ=0.545 (val F1=0.2073)
  Directional -> Accuracy: 0.3607, MCC: -0.2444, F1: 0.3607

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.50000 | val 1.15803
  Epoch 011 - train 0.42610 | val 1.08718
  Classification -> best τ=0.600 (val F1=0.2209)
  Directional -> Accuracy: 0.3974, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.47062 | val 0.81284
  Epoch 012 - train 0.36622 | val 0.84224
  Classification -> best τ=0.355 (val F1=0.3146)
  Directional -> Accuracy: 0.5522, MCC: 0.0986, F1: 0.5946

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 82). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.51499 | val 0.83208
  Epoch 012 - train 0.35744 | val 0.91270
  Classification -> best τ=0.455 (val F1=0.2095)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.41718 | val 1.02106
  Epoch 012 - train 0.33269 | val 1.40684
  Classification -> best τ=0.410 (val F1=0.4552)
  Directional -> Accuracy: 0.4400, MCC: 0.0784, F1: 0.2632

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 82). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 82). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 82). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.46138 | val 1.08905
  Epoch 011 - train 0.40991 | val 1.20115
  Classification -> best τ=0.270 (val F1=0.2817)
  Directional -> Accuracy: 0.5147, MCC: 0.0434, F1: 0.6452

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.41700 | val 1.74509
  Epoch 011 - train 0.38114 | val 2.17554
  Classification -> best τ=0.855 (val F1=0.2763)
  Directional -> Accuracy: 0.5500, MCC: 0.2039, F1: 0.4706

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.50188 | val 0.98164
  Epoch 011 - train 0.42987 | val 0.92624
  Classification -> best τ=0.530 (val F1=0.0867)
  Directional -> Accuracy: 0.5294, MCC: 0.0517, F1: 0.3043

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.41953 | val 0.96674
  Epoch 011 - train 0.36003 | val 1.03365
  Classification -> best τ=0.580 (val F1=0.3638)
  Directional -> Accuracy: 0.4483, MCC: 0.0000, F1: 0.0000

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.28093 | val 1.51981
  Epoch 018 - train 0.09770 | val 3.36172
  Classification -> best τ=0.840 (val F1=0.4257)
  Directional -> Accuracy: 0.5714, MCC: 0.1005, F1: 0.4324

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.43402 | val 0.75871
  Epoch 012 - train 0.39197 | val 0.77489
  Classification -> best τ=0.490 (val F1=0.1476)
  Directional -> Accuracy: 0.5111, MCC: 0.0181, F1: 0.5600

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.39425 | val 1.18889
  Epoch 011 - train 0.37617 | val 1.15891
  Classification -> best τ=0.455 (val F1=0.3233)
  Directional -> Accuracy: 0.4407, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.40026 | val 1.37797
  Epoch 011 - train 0.29566 | val 1.34997
  Classification -> best τ=0.505 (val F1=0.1677)
  Directional -> Accuracy: 0.4318, MCC: -0.1329, F1: 0.4186

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.31329 | val 1.43370
  Epoch 014 - train 0.18492 | val 2.14172
  Classification -> best τ=0.475 (val F1=0.2815)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.5490

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.46970 | val 2.00195
  Epoch 012 - train 0.36607 | val 1.85615
  Classification -> best τ=0.565 (val F1=0.1500)
  Directional -> Accuracy: 0.5435, MCC: 0.0186, F1: 0.6957

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.36996 | val 1.28504
  Epoch 012 - train 0.24920 | val 1.31256
  Classification -> best τ=0.355 (val F1=0.2656)
  Directional -> Accuracy: 0.4808, MCC: -0.1333, F1: 0.6400

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.47253 | val 1.07594
  Epoch 013 - train 0.30032 | val 1.31779
  Classification -> best τ=0.620 (val F1=0.3037)
  Directional -> Accuracy: 0.5467, MCC: 0.1701, F1: 0.4516

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 82). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.42965 | val 1.04540
  Epoch 013 - train 0.29224 | val 1.09742
  Classification -> best τ=0.570 (val F1=0.3477)
  Directional -> Accuracy: 0.5366, MCC: 0.1111, F1: 0.6415

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.34942 | val 1.29949
  Epoch 011 - train 0.30864 | val 1.23014
  Classification -> best τ=0.455 (val F1=0.2828)
  Directional -> Accuracy: 0.4565, MCC: 0.0000, F1: 0.6269

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.47427 | val 1.09359
  Epoch 011 - train 0.40151 | val 1.36993
  Classification -> best τ=0.410 (val F1=0.1973)
  Directional -> Accuracy: 0.4493, MCC: 0.0544, F1: 0.1739

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.30928 | val 1.32499
  Epoch 013 - train 0.23814 | val 1.33289
  Classification -> best τ=0.325 (val F1=0.4176)
  Directional -> Accuracy: 0.6000, MCC: 0.2429, F1: 0.7000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.47892 | val 1.63264
  Epoch 012 - train 0.36046 | val 1.74769
  Classification -> best τ=0.415 (val F1=0.1985)
  Directional -> Accuracy: 0.4915, MCC: 0.0051, F1: 0.5714

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.35160 | val 0.82288
  Epoch 011 - train 0.30481 | val 0.89731
  Classification -> best τ=0.455 (val F1=0.2449)
  Directional -> Accuracy: 0.3469, MCC: -0.2592, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 82). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 82). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 82). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 82). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.40178 | val 1.44193
  Epoch 011 - train 0.36097 | val 1.15781
  Classification -> best τ=0.530 (val F1=0.3420)
  Directional -> Accuracy: 0.3333, MCC: 0.0000, F1: 0.5000

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 82). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.39854 | val 1.57084
  Epoch 011 - train 0.32644 | val 1.71542
  Classification -> best τ=0.575 (val F1=0.3780)
  Directional -> Accuracy: 0.5366, MCC: 0.2210, F1: 0.1739

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 82). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 82). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.52800 | val 1.26738
  Epoch 012 - train 0.39200 | val 1.35014
  Classification -> best τ=0.405 (val F1=0.1643)
  Directional -> Accuracy: 0.5065, MCC: 0.0000, F1: 0.6724

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 82). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 82). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.40855 | val 2.58417
  Epoch 011 - train 0.44466 | val 2.51798
  Classification -> best τ=0.565 (val F1=0.4121)
  Directional -> Accuracy: 0.5102, MCC: 0.1414, F1: 0.6667

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.29343 | val 3.84052
  Epoch 011 - train 0.25310 | val 3.77693
  Classification -> best τ=0.485 (val F1=0.2191)
  Directional -> Accuracy: 0.6596, MCC: 0.2856, F1: 0.7419

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.33971 | val 1.97314
  Epoch 011 - train 0.32740 | val 1.91317
  Classification -> best τ=0.535 (val F1=0.2193)
  Directional -> Accuracy: 0.5238, MCC: 0.3333, F1: 0.6000

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.49095 | val 0.84696
  Epoch 011 - train 0.43003 | val 0.90650
  Classification -> best τ=0.540 (val F1=0.1942)
  Directional -> Accuracy: 0.7069, MCC: 0.4056, F1: 0.7385

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.35222 | val 1.42647
  Epoch 011 - train 0.30281 | val 1.48323
  Classification -> best τ=0.520 (val F1=0.3604)
  Directional -> Accuracy: 0.4746, MCC: -0.0923, F1: 0.1622

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.56655 | val 1.12228
  Epoch 012 - train 0.47359 | val 1.21666
  Classification -> best τ=0.635 (val F1=0.0788)
  Directional -> Accuracy: 0.4643, MCC: -0.0248, F1: 0.1667

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.45871 | val 1.40382
  Epoch 011 - train 0.41463 | val 1.71820
  Classification -> best τ=0.485 (val F1=0.1462)
  Directional -> Accuracy: 0.5172, MCC: 0.0000, F1: 0.6818

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.54917 | val 0.70165
  Epoch 011 - train 0.52044 | val 0.86808

[I 2026-02-22 08:56:43,572] Trial 31 finished with value: 0.2687702702778568 and parameters: {'feature_set': 'sector_finbert', 'model_type': 'BiGRU', 'sequence_length': 6, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.4, 'dropout': 0.0, 'batch_size': 32, 'learning_rate': 0.004498657827390639, 'weight_decay': 6.14267051133262e-06, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 1.057696314551763, 'early_stopping_min_delta': 0.00877794073510545}. Best is trial 22 with value: 0.2833350641483003.

  Classification -> best τ=0.520 (val F1=0.2936)
  Directional -> Accuracy: 0.4921, MCC: -0.0317, F1: 0.3846

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2687702702778568
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 6
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d', 'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down', 'finbert_neutral']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.60950 | val 0.84350
  Epoch 012 - train 0.48069 | val 0.99653
  Classification -> best τ=0.620 (val F1=0.2346)
  Directional -> Accuracy: 0.5443, MCC: 0.0093, F1: 0.2174

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 82). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.46574 | val 0.82943
  Epoch 012 - train 0.41584 | val 0.88549
  Classification -> best τ=0.540 (val F1=0.2928)
  Directional -> Accuracy: 0.5625, MCC: 0.1065, F1: 0.6182

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 82). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.46974 | val 1.31627
  Epoch 013 - train 0.44305 | val 1.47635
  Classification -> best τ=0.450 (val F1=0.2539)
  Directional -> Accuracy: 0.5102, MCC: 0.0517, F1: 0.4000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.60628 | val 0.78746
  Epoch 012 - train 0.46471 | val 0.99665
  Classification -> best τ=0.385 (val F1=0.1162)
  Directional -> Accuracy: 0.5455, MCC: 0.0000, F1: 0.7059

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.41206 | val 1.27049
  Epoch 013 - train 0.44230 | val 0.77280
  Classification -> best τ=0.475 (val F1=0.4461)
  Directional -> Accuracy: 0.6415, MCC: 0.3254, F1: 0.5778

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.48320 | val 0.78347
  Epoch 012 - train 0.37167 | val 0.95515
  Classification -> best τ=0.605 (val F1=0.3341)
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.50119 | val 0.92035
  Epoch 013 - train 0.38474 | val 0.83807
  Classification -> best τ=0.495 (val F1=0.2817)
  Directional -> Accuracy: 0.5915, MCC: 0.0664, F1: 0.2162

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 82). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 82). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.38565 | val 1.47911
  Epoch 017 - train 0.17158 | val 1.82209
  Classification -> best τ=0.685 (val F1=0.3043)
  Directional -> Accuracy: 0.5319, MCC: 0.0952, F1: 0.5217

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.43708 | val 1.41856
  Epoch 012 - train 0.36556 | val 1.77195
  Classification -> best τ=0.385 (val F1=0.2082)
  Directional -> Accuracy: 0.5116, MCC: 0.0490, F1: 0.4878

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 82). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 82). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.52767 | val 0.84196
  Epoch 012 - train 0.39233 | val 1.12762
  Classification -> best τ=0.665 (val F1=0.1918)
  Directional -> Accuracy: 0.5694, MCC: 0.0930, F1: 0.4151

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.50871 | val 0.91641
  Epoch 013 - train 0.38965 | val 0.86994
  Classification -> best τ=0.525 (val F1=0.3963)
  Directional -> Accuracy: 0.5962, MCC: 0.2000, F1: 0.3226

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.56287 | val 0.81561
  Epoch 011 - train 0.54297 | val 0.76323
  Classification -> best τ=0.415 (val F1=0.1439)
  Directional -> Accuracy: 0.4833, MCC: -0.1302, F1: 0.6517

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.45942 | val 2.46380
  Epoch 011 - train 0.35805 | val 3.92153
  Classification -> best τ=0.565 (val F1=0.0956)
  Directional -> Accuracy: 0.4667, MCC: 0.0000, F1: 0.6364

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 82). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.44512 | val 1.07394
  Epoch 012 - train 0.48475 | val 0.89071
  Classification -> best τ=0.385 (val F1=0.4157)
  Directional -> Accuracy: 0.5238, MCC: 0.0454, F1: 0.3750

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.46745 | val 0.78148
  Epoch 011 - train 0.39369 | val 0.73920
  Classification -> best τ=0.515 (val F1=0.2833)
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.51335 | val 1.30194
  Epoch 011 - train 0.44806 | val 1.67892
  Classification -> best τ=0.545 (val F1=0.4871)
  Directional -> Accuracy: 0.6528, MCC: 0.3228, F1: 0.7423

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.56880 | val 0.90572
  Epoch 012 - train 0.49489 | val 1.21820
  Classification -> best τ=0.645 (val F1=0.2046)
  Directional -> Accuracy: 0.3934, MCC: -0.1079, F1: 0.2449

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.58263 | val 1.15184
  Epoch 012 - train 0.44559 | val 1.37476
  Classification -> best τ=0.525 (val F1=0.1900)
  Directional -> Accuracy: 0.3974, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.52951 | val 1.71622
  Epoch 012 - train 0.36159 | val 1.57003
  Classification -> best τ=0.325 (val F1=0.2670)
  Directional -> Accuracy: 0.4925, MCC: -0.1039, F1: 0.6136

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 82). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.52703 | val 0.85983
  Epoch 012 - train 0.39890 | val 0.96453
  Classification -> best τ=0.520 (val F1=0.2236)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.47092 | val 1.58145
  Epoch 011 - train 0.46217 | val 1.68476
  Classification -> best τ=0.400 (val F1=0.2303)
  Directional -> Accuracy: 0.6200, MCC: 0.0000, F1: 0.7654

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 82). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 82). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 82). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.54524 | val 1.11534
  Epoch 012 - train 0.47288 | val 0.87359
  Classification -> best τ=0.350 (val F1=0.2500)
  Directional -> Accuracy: 0.5882, MCC: 0.1886, F1: 0.5000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.45785 | val 2.15169
  Epoch 012 - train 0.32017 | val 2.28925
  Classification -> best τ=0.325 (val F1=0.3601)
  Directional -> Accuracy: 0.6667, MCC: 0.3247, F1: 0.7727

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.55984 | val 1.48240
  Epoch 011 - train 0.42242 | val 1.62927
  Classification -> best τ=0.455 (val F1=0.1818)
  Directional -> Accuracy: 0.5588, MCC: 0.1265, F1: 0.5946

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.48474 | val 0.78445
  Epoch 011 - train 0.41058 | val 0.90749
  Classification -> best τ=0.315 (val F1=0.3458)
  Directional -> Accuracy: 0.5690, MCC: 0.1545, F1: 0.5614

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.33402 | val 1.29143
  Epoch 014 - train 0.19552 | val 1.31850
  Classification -> best τ=0.625 (val F1=0.1624)
  Directional -> Accuracy: 0.4286, MCC: -0.2173, F1: 0.2222

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.41487 | val 0.76380
  Epoch 011 - train 0.38267 | val 0.84353
  Classification -> best τ=0.545 (val F1=0.1427)
  Directional -> Accuracy: 0.5778, MCC: 0.0633, F1: 0.6885

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.43475 | val 1.07343
  Epoch 011 - train 0.38758 | val 1.29770
  Classification -> best τ=0.315 (val F1=0.2942)
  Directional -> Accuracy: 0.4746, MCC: 0.1036, F1: 0.1622

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.36163 | val 0.99388
  Epoch 012 - train 0.23462 | val 1.08865
  Classification -> best τ=0.640 (val F1=0.2345)
  Directional -> Accuracy: 0.5000, MCC: 0.0424, F1: 0.2667

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.42450 | val 0.81307
  Epoch 012 - train 0.40175 | val 0.92447
  Classification -> best τ=0.480 (val F1=0.3577)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.5490

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.41645 | val 1.10056
  Epoch 011 - train 0.42840 | val 1.42167
  Classification -> best τ=0.560 (val F1=0.2429)
  Directional -> Accuracy: 0.5435, MCC: 0.0338, F1: 0.6769

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.35700 | val 1.27184
  Epoch 011 - train 0.32935 | val 1.16543
  Classification -> best τ=0.410 (val F1=0.3025)
  Directional -> Accuracy: 0.5192, MCC: 0.0000, F1: 0.6835

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.44783 | val 0.79419
  Epoch 012 - train 0.44336 | val 0.78778
  Classification -> best τ=0.400 (val F1=0.3252)
  Directional -> Accuracy: 0.4400, MCC: -0.0287, F1: 0.0870

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 82). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.35808 | val 0.74344
  Epoch 011 - train 0.40032 | val 0.76404
  Classification -> best τ=0.570 (val F1=0.4109)
  Directional -> Accuracy: 0.4878, MCC: 0.0000, F1: 0.6557

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.28697 | val 1.08658
  Epoch 011 - train 0.23151 | val 1.19152
  Classification -> best τ=0.300 (val F1=0.1954)
  Directional -> Accuracy: 0.4565, MCC: 0.0000, F1: 0.6269

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.47836 | val 0.93819
  Epoch 011 - train 0.38959 | val 1.21715
  Classification -> best τ=0.435 (val F1=0.2466)
  Directional -> Accuracy: 0.6377, MCC: 0.2766, F1: 0.6667

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.33999 | val 1.35420
  Epoch 011 - train 0.29054 | val 1.45060
  Classification -> best τ=0.385 (val F1=0.3934)
  Directional -> Accuracy: 0.6667, MCC: 0.3380, F1: 0.6512

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.47436 | val 1.62814
  Epoch 012 - train 0.39216 | val 1.55613
  Classification -> best τ=0.550 (val F1=0.1531)
  Directional -> Accuracy: 0.5254, MCC: 0.0137, F1: 0.1250

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.31605 | val 0.78646
  Epoch 011 - train 0.27870 | val 0.80066
  Classification -> best τ=0.265 (val F1=0.3249)
  Directional -> Accuracy: 0.6327, MCC: 0.1462, F1: 0.7632

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 82). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 82). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 82). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 82). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.36345 | val 1.38569
  Epoch 011 - train 0.33221 | val 1.31613
  Classification -> best τ=0.485 (val F1=0.2954)
  Directional -> Accuracy: 0.3333, MCC: 0.0000, F1: 0.5000

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 82). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.35859 | val 0.88053
  Epoch 011 - train 0.34808 | val 0.96163
  Classification -> best τ=0.570 (val F1=0.2467)
  Directional -> Accuracy: 0.4878, MCC: -0.0101, F1: 0.2222

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 82). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 82). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.57442 | val 1.93352
  Epoch 013 - train 0.39176 | val 1.35126
  Classification -> best τ=0.605 (val F1=0.2040)
  Directional -> Accuracy: 0.4935, MCC: 0.0000, F1: 0.0000

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 82). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 82). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.48706 | val 3.17677
  Epoch 011 - train 0.42170 | val 3.16641
  Classification -> best τ=0.550 (val F1=0.2850)
  Directional -> Accuracy: 0.5510, MCC: 0.2502, F1: 0.6857

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.23491 | val 3.17289
  Epoch 011 - train 0.20804 | val 3.47234
  Classification -> best τ=0.610 (val F1=0.3043)
  Directional -> Accuracy: 0.4255, MCC: 0.0000, F1: 0.0000

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.37223 | val 0.88666
  Epoch 011 - train 0.34307 | val 0.94958
  Classification -> best τ=0.400 (val F1=0.4122)
  Directional -> Accuracy: 0.4048, MCC: 0.0203, F1: 0.5098

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.49476 | val 0.72433
  Epoch 014 - train 0.44227 | val 0.75560
  Classification -> best τ=0.655 (val F1=0.2581)
  Directional -> Accuracy: 0.5172, MCC: 0.2453, F1: 0.2222

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.50740 | val 1.88600
  Epoch 013 - train 0.27945 | val 2.04877
  Classification -> best τ=0.500 (val F1=0.4001)
  Directional -> Accuracy: 0.5254, MCC: 0.0499, F1: 0.3333

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.52320 | val 0.73744
  Epoch 013 - train 0.49206 | val 0.78278
  Classification -> best τ=0.510 (val F1=0.0823)
  Directional -> Accuracy: 0.6071, MCC: 0.2042, F1: 0.6562

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.48926 | val 1.14421
  Epoch 013 - train 0.27045 | val 1.55786
  Classification -> best τ=0.460 (val F1=0.2809)
  Directional -> Accuracy: 0.4828, MCC: -0.0065, F1: 0.0625

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.54818 | val 0.68132

[I 2026-02-22 08:57:52,330] Trial 32 finished with value: 0.27088874124625684 and parameters: {'feature_set': 'sector_finbert', 'model_type': 'BiGRU', 'sequence_length': 6, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.4, 'dropout': 0.0, 'batch_size': 32, 'learning_rate': 0.009871179946449248, 'weight_decay': 4.703472603939752e-06, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 1.0249516858736882, 'early_stopping_min_delta': 0.008932558665522722}. Best is trial 22 with value: 0.2833350641483003.

  Epoch 016 - train 0.40883 | val 0.81016
  Classification -> best τ=0.620 (val F1=0.2500)
  Directional -> Accuracy: 0.5238, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.27088874124625684
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 6
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d', 'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down', 'finbert_neutral']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.49333 | val 1.13468
  Epoch 016 - train 0.38210 | val 1.36676
  Classification -> best τ=0.900 (val F1=0.2727)
  Directional -> Accuracy: 0.5696, MCC: 0.1054, F1: 0.4333

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 82). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.35273 | val 1.00451
  Epoch 012 - train 0.29281 | val 1.19724
  Classification -> best τ=0.620 (val F1=0.1899)
  Directional -> Accuracy: 0.5833, MCC: 0.1534, F1: 0.6296

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 82). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.49905 | val 2.39188
  Epoch 011 - train 0.45393 | val 2.50038
  Classification -> best τ=0.625 (val F1=0.3612)
  Directional -> Accuracy: 0.4694, MCC: -0.0229, F1: 0.1875

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.48818 | val 0.78547
  Epoch 011 - train 0.45069 | val 0.78500
  Classification -> best τ=0.450 (val F1=0.0636)
  Directional -> Accuracy: 0.5325, MCC: -0.1047, F1: 0.6949

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.38418 | val 1.26352
  Epoch 013 - train 0.26144 | val 0.93155
  Classification -> best τ=0.595 (val F1=0.5017)
  Directional -> Accuracy: 0.6038, MCC: 0.2445, F1: 0.5333

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.40966 | val 0.67034
  Epoch 020 - train 0.15354 | val 1.36028
  Classification -> best τ=0.410 (val F1=0.3290)
  Directional -> Accuracy: 0.4390, MCC: -0.1025, F1: 0.5106

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.47458 | val 1.33760
  Epoch 011 - train 0.38645 | val 1.66886
  Classification -> best τ=0.570 (val F1=0.2100)
  Directional -> Accuracy: 0.5915, MCC: 0.0317, F1: 0.0645

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 82). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 82). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.35699 | val 1.37752
  Epoch 011 - train 0.28079 | val 1.46670
  Classification -> best τ=0.560 (val F1=0.3064)
  Directional -> Accuracy: 0.4894, MCC: 0.1852, F1: 0.6000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.41518 | val 1.84804
  Epoch 011 - train 0.33565 | val 1.95070
  Classification -> best τ=0.440 (val F1=0.1533)
  Directional -> Accuracy: 0.5349, MCC: -0.0989, F1: 0.1667

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 82). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 82). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.52138 | val 0.92273
  Epoch 011 - train 0.47157 | val 1.07084
  Classification -> best τ=0.560 (val F1=0.1918)
  Directional -> Accuracy: 0.5000, MCC: -0.0117, F1: 0.4375

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.49845 | val 1.16836
  Epoch 013 - train 0.30288 | val 1.58689
  Classification -> best τ=0.685 (val F1=0.2430)
  Directional -> Accuracy: 0.6154, MCC: 0.2694, F1: 0.3333

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.55664 | val 0.87095
  Epoch 012 - train 0.47475 | val 0.84308
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.38757 | val 1.24766
  Epoch 015 - train 0.22998 | val 1.13296
  Classification -> best τ=0.795 (val F1=0.1761)
  Directional -> Accuracy: 0.4889, MCC: -0.1048, F1: 0.1481

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 82). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.54152 | val 0.64165
  Epoch 011 - train 0.48271 | val 0.67226
  Classification -> best τ=0.290 (val F1=0.4709)
  Directional -> Accuracy: 0.4444, MCC: -0.2112, F1: 0.0541

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.42082 | val 0.76207
  Epoch 013 - train 0.34942 | val 1.05202
  Classification -> best τ=0.570 (val F1=0.2833)
  Directional -> Accuracy: 0.5000, MCC: -0.0115, F1: 0.4000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.49406 | val 1.32526
  Epoch 012 - train 0.39020 | val 1.24704
  Classification -> best τ=0.580 (val F1=0.3574)
  Directional -> Accuracy: 0.5278, MCC: 0.1080, F1: 0.4138

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.54288 | val 0.99539
  Epoch 011 - train 0.48487 | val 1.07115
  Classification -> best τ=0.400 (val F1=0.0426)
  Directional -> Accuracy: 0.5410, MCC: 0.0383, F1: 0.6216

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.48764 | val 0.94812
  Epoch 011 - train 0.40987 | val 1.09344
  Classification -> best τ=0.425 (val F1=0.1916)
  Directional -> Accuracy: 0.3974, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.48112 | val 1.16603
  Epoch 012 - train 0.38002 | val 1.15072
  Classification -> best τ=0.585 (val F1=0.2326)
  Directional -> Accuracy: 0.4179, MCC: -0.1325, F1: 0.4000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 82). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.43668 | val 1.08174
  Epoch 011 - train 0.39234 | val 1.12771
  Classification -> best τ=0.425 (val F1=0.3245)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.42187 | val 1.26484
  Epoch 012 - train 0.35483 | val 1.40089
  Classification -> best τ=0.540 (val F1=0.3094)
  Directional -> Accuracy: 0.3600, MCC: -0.1591, F1: 0.1579

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 82). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 82). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 82). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.46690 | val 0.89805
  Epoch 011 - train 0.49422 | val 1.00928
  Classification -> best τ=0.240 (val F1=0.2500)
  Directional -> Accuracy: 0.5882, MCC: 0.1765, F1: 0.5882

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.52697 | val 2.84032
  Epoch 011 - train 0.39437 | val 2.92697
  Classification -> best τ=0.455 (val F1=0.2859)
  Directional -> Accuracy: 0.6167, MCC: 0.1912, F1: 0.6933

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.49329 | val 1.44006
  Epoch 011 - train 0.40780 | val 1.25740
  Classification -> best τ=0.475 (val F1=0.1152)
  Directional -> Accuracy: 0.5882, MCC: 0.2667, F1: 0.6889

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.47669 | val 0.98018
  Epoch 011 - train 0.39739 | val 1.04426
  Classification -> best τ=0.470 (val F1=0.4873)
  Directional -> Accuracy: 0.5862, MCC: 0.2300, F1: 0.5200

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.27647 | val 1.31951
  Epoch 014 - train 0.23676 | val 2.20985
  Classification -> best τ=0.765 (val F1=0.2915)
  Directional -> Accuracy: 0.5102, MCC: -0.0121, F1: 0.4000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.49672 | val 0.73803
  Epoch 011 - train 0.47825 | val 0.77665
  Classification -> best τ=0.615 (val F1=0.0714)
  Directional -> Accuracy: 0.4667, MCC: 0.1443, F1: 0.2500

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.46525 | val 1.07765
  Epoch 011 - train 0.38001 | val 1.11723
  Classification -> best τ=0.330 (val F1=0.2356)
  Directional -> Accuracy: 0.4407, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.43489 | val 1.29919
  Epoch 011 - train 0.35904 | val 1.40119
  Classification -> best τ=0.570 (val F1=0.1685)
  Directional -> Accuracy: 0.6591, MCC: 0.3182, F1: 0.7059

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.39790 | val 1.22095
  Epoch 011 - train 0.34642 | val 1.50384
  Classification -> best τ=0.495 (val F1=0.1071)
  Directional -> Accuracy: 0.4565, MCC: -0.0877, F1: 0.4898

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.46776 | val 1.35189
  Epoch 011 - train 0.40816 | val 1.35415
  Classification -> best τ=0.535 (val F1=0.1465)
  Directional -> Accuracy: 0.5435, MCC: 0.0186, F1: 0.6957

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.41381 | val 0.97961
  Epoch 012 - train 0.35201 | val 0.89501
  Classification -> best τ=0.415 (val F1=0.2540)
  Directional -> Accuracy: 0.4423, MCC: -0.1278, F1: 0.5085

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.54014 | val 0.73566
  Epoch 013 - train 0.38626 | val 0.90789
  Classification -> best τ=0.480 (val F1=0.2477)
  Directional -> Accuracy: 0.5733, MCC: 0.1053, F1: 0.6667

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 82). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.46230 | val 1.26757
  Epoch 011 - train 0.41548 | val 1.91364
  Classification -> best τ=0.600 (val F1=0.1448)
  Directional -> Accuracy: 0.5366, MCC: 0.1111, F1: 0.6415

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.38399 | val 1.44846
  Epoch 011 - train 0.29639 | val 1.49790
  Classification -> best τ=0.405 (val F1=0.1954)
  Directional -> Accuracy: 0.5217, MCC: 0.2421, F1: 0.6562

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.48643 | val 1.05083
  Epoch 011 - train 0.41053 | val 1.10861
  Classification -> best τ=0.300 (val F1=0.2361)
  Directional -> Accuracy: 0.6232, MCC: 0.1904, F1: 0.7292

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.40278 | val 1.45718
  Epoch 012 - train 0.30194 | val 1.30750
  Classification -> best τ=0.410 (val F1=0.3857)
  Directional -> Accuracy: 0.6444, MCC: 0.2960, F1: 0.6190

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.47336 | val 1.00501
  Epoch 012 - train 0.39239 | val 1.25905
  Classification -> best τ=0.495 (val F1=0.1680)
  Directional -> Accuracy: 0.4746, MCC: -0.0518, F1: 0.4561

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.35141 | val 1.54551
  Epoch 011 - train 0.33054 | val 1.77597
  Classification -> best τ=0.370 (val F1=0.2373)
  Directional -> Accuracy: 0.5102, MCC: 0.1951, F1: 0.4000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 82). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 82). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 82). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 82). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.43126 | val 0.98217
  Epoch 011 - train 0.38680 | val 1.16216
  Classification -> best τ=0.515 (val F1=0.2503)
  Directional -> Accuracy: 0.3333, MCC: 0.0000, F1: 0.5000

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 82). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.39833 | val 2.01198
  Epoch 014 - train 0.21233 | val 2.26002
  Classification -> best τ=0.565 (val F1=0.2403)
  Directional -> Accuracy: 0.5122, MCC: 0.0655, F1: 0.2308

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 82). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 82). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.55644 | val 1.32393
  Epoch 012 - train 0.39547 | val 1.46021
  Classification -> best τ=0.350 (val F1=0.2601)
  Directional -> Accuracy: 0.5065, MCC: 0.0000, F1: 0.6724

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 82). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 82). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.47214 | val 2.80521
  Epoch 013 - train 0.34432 | val 1.97880
  Classification -> best τ=0.710 (val F1=0.1664)
  Directional -> Accuracy: 0.4898, MCC: -0.0799, F1: 0.0741

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.32209 | val 2.59488
  Epoch 011 - train 0.23478 | val 2.73623
  Classification -> best τ=0.540 (val F1=0.1180)
  Directional -> Accuracy: 0.4255, MCC: 0.0000, F1: 0.0000

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.38796 | val 1.39868
  Epoch 011 - train 0.34641 | val 1.41367
  Classification -> best τ=0.505 (val F1=0.3962)
  Directional -> Accuracy: 0.5952, MCC: 0.3614, F1: 0.6222

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.45675 | val 0.77782
  Epoch 011 - train 0.42869 | val 0.79047
  Classification -> best τ=0.690 (val F1=0.1962)
  Directional -> Accuracy: 0.4483, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.43959 | val 1.79089
  Epoch 011 - train 0.41090 | val 1.31324
  Classification -> best τ=0.680 (val F1=0.3874)
  Directional -> Accuracy: 0.4746, MCC: -0.0532, F1: 0.4364

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.56529 | val 1.96586
  Epoch 012 - train 0.48839 | val 1.78141
  Classification -> best τ=0.495 (val F1=0.0996)
  Directional -> Accuracy: 0.6250, MCC: 0.2417, F1: 0.6667

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.39317 | val 1.93650
  Epoch 011 - train 0.35437 | val 2.13772
  Classification -> best τ=0.350 (val F1=0.0192)
  Directional -> Accuracy: 0.5172, MCC: 0.0000, F1: 0.6818

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.51872 | val 0.69543

[I 2026-02-22 08:59:00,267] Trial 33 finished with value: 0.23245462438178813 and parameters: {'feature_set': 'sector_finbert', 'model_type': 'BiGRU', 'sequence_length': 6, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.4, 'dropout': 0.1, 'batch_size': 32, 'learning_rate': 0.004700660149473197, 'weight_decay': 4.316096660594492e-06, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 0.9944384004292642, 'early_stopping_min_delta': 0.007659304470422904}. Best is trial 22 with value: 0.2833350641483003.

  Epoch 016 - train 0.39219 | val 0.69158
  Classification -> best τ=0.600 (val F1=0.2500)
  Directional -> Accuracy: 0.5397, MCC: 0.1332, F1: 0.0645

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.23245462438178813
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 6
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d', 'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down', 'finbert_neutral']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.50673 | val 0.93223
  Epoch 011 - train 0.48122 | val 1.12719
  Classification -> best τ=0.850 (val F1=0.1903)
  Directional -> Accuracy: 0.5823, MCC: 0.1230, F1: 0.2326

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 82). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.43735 | val 0.89734
  Epoch 012 - train 0.32996 | val 1.07534
  Classification -> best τ=0.715 (val F1=0.2928)
  Directional -> Accuracy: 0.4375, MCC: -0.0891, F1: 0.3721

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 82). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.43552 | val 1.75559
  Epoch 011 - train 0.38043 | val 1.99221
  Classification -> best τ=0.435 (val F1=0.3612)
  Directional -> Accuracy: 0.4898, MCC: 0.0334, F1: 0.2424

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.51886 | val 0.68381
  Epoch 020 - train 0.23875 | val 1.07171
  Classification -> best τ=0.605 (val F1=0.2383)
  Directional -> Accuracy: 0.4805, MCC: 0.0708, F1: 0.1667

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.37115 | val 1.12197
  Epoch 012 - train 0.27016 | val 1.06184
  Classification -> best τ=0.520 (val F1=0.4874)
  Directional -> Accuracy: 0.6038, MCC: 0.2335, F1: 0.5532

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.41290 | val 0.93019
  Epoch 012 - train 0.36695 | val 1.13546
  Classification -> best τ=0.530 (val F1=0.2521)
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.46985 | val 1.08078
  Epoch 011 - train 0.41621 | val 1.27141
  Classification -> best τ=0.575 (val F1=0.1690)
  Directional -> Accuracy: 0.5634, MCC: 0.0917, F1: 0.4561

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 82). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 82). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.27389 | val 1.31119
  Epoch 011 - train 0.31768 | val 1.35820
  Classification -> best τ=0.635 (val F1=0.3043)
  Directional -> Accuracy: 0.6170, MCC: 0.1790, F1: 0.1000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.39085 | val 1.52450
  Epoch 011 - train 0.33061 | val 1.57565
  Classification -> best τ=0.425 (val F1=0.1586)
  Directional -> Accuracy: 0.4884, MCC: -0.0288, F1: 0.4211

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 82). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 82). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.45541 | val 0.93793
  Epoch 011 - train 0.40636 | val 1.04544
  Classification -> best τ=0.350 (val F1=0.1838)
  Directional -> Accuracy: 0.4028, MCC: -0.1944, F1: 0.5743

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.57936 | val 1.22496
  Epoch 012 - train 0.35069 | val 1.28425
  Classification -> best τ=0.550 (val F1=0.2430)
  Directional -> Accuracy: 0.5192, MCC: -0.0157, F1: 0.2424

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.52983 | val 0.86532
  Epoch 012 - train 0.47774 | val 0.94410
  Classification -> best τ=0.540 (val F1=0.1374)
  Directional -> Accuracy: 0.4500, MCC: -0.2294, F1: 0.0000

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.35939 | val 1.24433
  Epoch 011 - train 0.32843 | val 1.40063
  Classification -> best τ=0.515 (val F1=0.2182)
  Directional -> Accuracy: 0.4667, MCC: 0.0000, F1: 0.6364

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 82). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.54746 | val 0.72873
  Epoch 011 - train 0.42644 | val 0.79021
  Classification -> best τ=0.410 (val F1=0.4588)
  Directional -> Accuracy: 0.4603, MCC: -0.2201, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.40458 | val 0.71606
  Epoch 019 - train 0.20485 | val 1.08629
  Classification -> best τ=0.810 (val F1=0.2833)
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.51820 | val 1.15378
  Epoch 011 - train 0.46271 | val 1.06521
  Classification -> best τ=0.790 (val F1=0.2854)
  Directional -> Accuracy: 0.5278, MCC: 0.2078, F1: 0.2609

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.49886 | val 1.00086
  Epoch 011 - train 0.43702 | val 0.97033
  Classification -> best τ=0.350 (val F1=0.1411)
  Directional -> Accuracy: 0.6066, MCC: 0.0000, F1: 0.7551

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.48397 | val 1.24207
  Epoch 011 - train 0.43948 | val 1.27662
  Classification -> best τ=0.435 (val F1=0.1200)
  Directional -> Accuracy: 0.6026, MCC: 0.0000, F1: 0.7520

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.53931 | val 0.88556
  Epoch 014 - train 0.37662 | val 0.77901
  Classification -> best τ=0.400 (val F1=0.2986)
  Directional -> Accuracy: 0.4925, MCC: -0.0027, F1: 0.5143

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 82). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.49831 | val 0.86910
  Epoch 011 - train 0.38728 | val 0.99574
  Classification -> best τ=0.530 (val F1=0.2236)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.38054 | val 1.05431
  Epoch 011 - train 0.33259 | val 1.26958
  Classification -> best τ=0.510 (val F1=0.2850)
  Directional -> Accuracy: 0.6200, MCC: 0.0000, F1: 0.7654

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 82). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 82). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 82). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.51621 | val 0.87474
  Epoch 013 - train 0.36279 | val 0.94648
  Classification -> best τ=0.400 (val F1=0.2074)
  Directional -> Accuracy: 0.5588, MCC: 0.1176, F1: 0.5588

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.42042 | val 2.62439
  Epoch 011 - train 0.39118 | val 3.00332
  Classification -> best τ=0.525 (val F1=0.3326)
  Directional -> Accuracy: 0.6333, MCC: 0.2548, F1: 0.6765

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.41480 | val 1.16361
  Epoch 011 - train 0.44910 | val 1.62621
  Classification -> best τ=0.545 (val F1=0.0354)
  Directional -> Accuracy: 0.5294, MCC: 0.0549, F1: 0.2381

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.40341 | val 1.09128
  Epoch 015 - train 0.25712 | val 0.93991
  Classification -> best τ=0.495 (val F1=0.5159)
  Directional -> Accuracy: 0.6034, MCC: 0.2463, F1: 0.5660

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.24953 | val 1.04409
  Epoch 014 - train 0.13517 | val 2.93874
  Classification -> best τ=0.530 (val F1=0.3363)
  Directional -> Accuracy: 0.4694, MCC: -0.0244, F1: 0.5000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.47620 | val 0.85246
  Epoch 011 - train 0.39508 | val 0.89613
  Classification -> best τ=0.595 (val F1=0.0945)
  Directional -> Accuracy: 0.5778, MCC: 0.0801, F1: 0.6780

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.43657 | val 1.05560
  Epoch 011 - train 0.40133 | val 1.12255
  Classification -> best τ=0.335 (val F1=0.3139)
  Directional -> Accuracy: 0.4746, MCC: -0.0215, F1: 0.4364

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.41171 | val 1.38786
  Epoch 011 - train 0.30389 | val 0.91064
  Classification -> best τ=0.630 (val F1=0.1626)
  Directional -> Accuracy: 0.5682, MCC: 0.3022, F1: 0.2963

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.35803 | val 0.88109
  Epoch 015 - train 0.19624 | val 1.41260
  Classification -> best τ=0.450 (val F1=0.2998)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.5106

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.44731 | val 2.01668
  Epoch 011 - train 0.36862 | val 1.78050
  Classification -> best τ=0.470 (val F1=0.0744)
  Directional -> Accuracy: 0.5652, MCC: 0.1114, F1: 0.7059

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.37098 | val 1.35691
  Epoch 012 - train 0.30649 | val 1.39035
  Classification -> best τ=0.370 (val F1=0.2742)
  Directional -> Accuracy: 0.5192, MCC: 0.0000, F1: 0.6835

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.49550 | val 0.82084
  Epoch 011 - train 0.46048 | val 1.24467
  Classification -> best τ=0.440 (val F1=0.1958)
  Directional -> Accuracy: 0.5200, MCC: 0.1489, F1: 0.3571

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 82). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.39231 | val 0.78762
  Epoch 011 - train 0.36094 | val 0.86920
  Classification -> best τ=0.520 (val F1=0.5136)
  Directional -> Accuracy: 0.4878, MCC: 0.0000, F1: 0.6557

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.42368 | val 1.22860
  Epoch 011 - train 0.27576 | val 1.24851
  Classification -> best τ=0.440 (val F1=0.2421)
  Directional -> Accuracy: 0.5870, MCC: 0.3550, F1: 0.6885

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.51188 | val 1.01288
  Epoch 011 - train 0.43871 | val 1.01614
  Classification -> best τ=0.605 (val F1=0.3095)
  Directional -> Accuracy: 0.4203, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.31093 | val 1.50433
  Epoch 012 - train 0.27988 | val 1.25287
  Classification -> best τ=0.540 (val F1=0.4489)
  Directional -> Accuracy: 0.5778, MCC: 0.1771, F1: 0.4865

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.49921 | val 1.25535
  Epoch 012 - train 0.40945 | val 1.01614
  Classification -> best τ=0.495 (val F1=0.1667)
  Directional -> Accuracy: 0.4746, MCC: -0.0422, F1: 0.5079

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.43100 | val 0.74891
  Epoch 011 - train 0.35821 | val 0.93799
  Classification -> best τ=0.345 (val F1=0.3249)
  Directional -> Accuracy: 0.6122, MCC: 0.0000, F1: 0.7595

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 82). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 82). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 82). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 82). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.44333 | val 1.04413
  Epoch 011 - train 0.35090 | val 1.03333
  Classification -> best τ=0.490 (val F1=0.2992)
  Directional -> Accuracy: 0.3333, MCC: 0.0000, F1: 0.5000

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 82). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.34205 | val 1.80176
  Epoch 014 - train 0.16160 | val 2.09506
  Classification -> best τ=0.615 (val F1=0.2467)
  Directional -> Accuracy: 0.6098, MCC: 0.2818, F1: 0.4667

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 82). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 82). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.51679 | val 1.78553
  Epoch 012 - train 0.36865 | val 1.62040
  Classification -> best τ=0.270 (val F1=0.1658)
  Directional -> Accuracy: 0.5065, MCC: 0.0000, F1: 0.6724

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 82). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 82). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.40152 | val 1.74150
  Epoch 013 - train 0.32536 | val 3.09509
  Classification -> best τ=0.660 (val F1=0.2671)
  Directional -> Accuracy: 0.6531, MCC: 0.3232, F1: 0.6909

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.34416 | val 2.23319
  Epoch 011 - train 0.20024 | val 2.55434
  Classification -> best τ=0.625 (val F1=0.2921)
  Directional -> Accuracy: 0.4255, MCC: 0.0000, F1: 0.0000

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.38920 | val 1.45700
  Epoch 011 - train 0.25902 | val 1.52846
  Classification -> best τ=0.550 (val F1=0.3070)
  Directional -> Accuracy: 0.6429, MCC: 0.2582, F1: 0.5455

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.48621 | val 0.74159
  Epoch 011 - train 0.45806 | val 0.74449
  Classification -> best τ=0.645 (val F1=0.1962)
  Directional -> Accuracy: 0.4483, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.38285 | val 1.36394
  Epoch 011 - train 0.31953 | val 1.65005
  Classification -> best τ=0.530 (val F1=0.3769)
  Directional -> Accuracy: 0.4746, MCC: -0.0595, F1: 0.3673

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.56617 | val 0.95463
  Epoch 016 - train 0.37120 | val 1.37871
  Classification -> best τ=0.520 (val F1=0.1211)
  Directional -> Accuracy: 0.5714, MCC: 0.1432, F1: 0.5862

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.40832 | val 1.57352
  Epoch 011 - train 0.35075 | val 1.91964
  Classification -> best τ=0.560 (val F1=0.0263)
  Directional -> Accuracy: 0.4828, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.49272 | val 0.72786

[I 2026-02-22 09:00:09,351] Trial 34 finished with value: 0.2545794155578264 and parameters: {'feature_set': 'sector_finbert', 'model_type': 'BiGRU', 'sequence_length': 6, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.4, 'dropout': 0.0, 'batch_size': 32, 'learning_rate': 0.0048067936328440265, 'weight_decay': 1.1136993906373725e-06, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 20, 'huber_delta': 1.0759521089278032, 'early_stopping_min_delta': 0.006672241057953826}. Best is trial 22 with value: 0.2833350641483003.

  Epoch 017 - train 0.35020 | val 0.76551
  Classification -> best τ=0.640 (val F1=0.2500)
  Directional -> Accuracy: 0.4921, MCC: -0.0280, F1: 0.4074

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2545794155578264
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: classification
Sequence length: 6
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d', 'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down', 'finbert_neutral']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.64844 | val 0.87236
  Epoch 011 - train 0.62820 | val 0.93343
  Classification -> best τ=0.460 (val F1=0.1779)
  Directional -> Accuracy: 0.5063, MCC: -0.0281, F1: 0.3607

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 82). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.66088 | val 0.72623
  Epoch 011 - train 0.64712 | val 0.72709
  Classification -> best τ=0.540 (val F1=0.0258)
  Directional -> Accuracy: 0.5833, MCC: 0.1187, F1: 0.6875

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 82). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.66808 | val 0.71587
  Epoch 011 - train 0.66746 | val 0.71348
  Classification -> best τ=0.465 (val F1=0.3817)
  Directional -> Accuracy: 0.6735, MCC: 0.3987, F1: 0.7576

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.69058 | val 0.74602
  Epoch 011 - train 0.67407 | val 0.74009
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5455, MCC: 0.0000, F1: 0.7059

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.64388 | val 0.66138
  Epoch 016 - train 0.59747 | val 0.67210
  Classification -> best τ=0.550 (val F1=0.4804)
  Directional -> Accuracy: 0.6038, MCC: 0.2445, F1: 0.5333

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.64102 | val 0.94061
  Epoch 011 - train 0.62270 | val 0.99372
  Classification -> best τ=0.495 (val F1=0.2415)
  Directional -> Accuracy: 0.4146, MCC: -0.2437, F1: 0.5862

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.65958 | val 0.73526
  Epoch 011 - train 0.66142 | val 0.75476
  Classification -> best τ=0.500 (val F1=0.1434)
  Directional -> Accuracy: 0.4930, MCC: 0.0486, F1: 0.5263

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 82). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 82). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.67550 | val 0.75057
  Epoch 011 - train 0.67554 | val 0.75665
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4043, MCC: 0.0000, F1: 0.5758

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.67105 | val 0.71362
  Epoch 015 - train 0.69729 | val 0.71010
  Classification -> best τ=0.490 (val F1=0.4466)
  Directional -> Accuracy: 0.6279, MCC: 0.1908, F1: 0.1111

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 82). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 82). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.63711 | val 0.79764
  Epoch 011 - train 0.62518 | val 0.79205
  Classification -> best τ=0.470 (val F1=0.2663)
  Directional -> Accuracy: 0.4444, MCC: 0.0409, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.62338 | val 0.71850
  Epoch 011 - train 0.65682 | val 0.77410
  Classification -> best τ=0.465 (val F1=0.0836)
  Directional -> Accuracy: 0.5577, MCC: 0.0872, F1: 0.3429

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.67114 | val 0.73180
  Epoch 011 - train 0.67878 | val 0.74140
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.63069 | val 0.75675
  Epoch 011 - train 0.59839 | val 0.76566
  Classification -> best τ=0.525 (val F1=0.0364)
  Directional -> Accuracy: 0.5333, MCC: 0.0000, F1: 0.0000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 82). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.65035 | val 0.58800
  Epoch 020 - train 0.58189 | val 0.61267
  Classification -> best τ=0.495 (val F1=0.4382)
  Directional -> Accuracy: 0.4762, MCC: -0.1782, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.66331 | val 0.79398
  Epoch 011 - train 0.62633 | val 0.81347
  Classification -> best τ=0.455 (val F1=0.1154)
  Directional -> Accuracy: 0.4815, MCC: -0.0105, F1: 0.6316

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.63648 | val 0.73460
  Epoch 011 - train 0.62813 | val 0.74650
  Classification -> best τ=0.515 (val F1=0.1781)
  Directional -> Accuracy: 0.5139, MCC: 0.1122, F1: 0.3137

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.67525 | val 0.69166
  Epoch 018 - train 0.60894 | val 0.88209
  Classification -> best τ=0.575 (val F1=0.3112)
  Directional -> Accuracy: 0.4426, MCC: 0.0794, F1: 0.2273

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.69065 | val 0.75851
  Epoch 011 - train 0.67385 | val 0.75726
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.6026, MCC: 0.0000, F1: 0.7520

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.68056 | val 0.68199
  Epoch 018 - train 0.62909 | val 0.73613
  Classification -> best τ=0.540 (val F1=0.2740)
  Directional -> Accuracy: 0.4627, MCC: 0.1255, F1: 0.1818

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 82). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.63097 | val 0.68692
  Epoch 016 - train 0.60548 | val 0.75079
  Classification -> best τ=0.500 (val F1=0.1904)
  Directional -> Accuracy: 0.4805, MCC: 0.1491, F1: 0.0909

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.63956 | val 0.74235
  Epoch 011 - train 0.65419 | val 0.74780
  Classification -> best τ=0.515 (val F1=0.1041)
  Directional -> Accuracy: 0.5200, MCC: 0.2595, F1: 0.4000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 82). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 82). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 82). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.69220 | val 0.70728
  Epoch 019 - train 0.62344 | val 0.73414
  Classification -> best τ=0.580 (val F1=0.3086)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.64504 | val 0.77201
  Epoch 011 - train 0.66143 | val 0.77908
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5833, MCC: 0.0000, F1: 0.7368

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.63381 | val 1.01261
  Epoch 011 - train 0.61916 | val 1.06375
  Classification -> best τ=0.515 (val F1=0.0661)
  Directional -> Accuracy: 0.5147, MCC: 0.0331, F1: 0.5352

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.64489 | val 0.73456
  Epoch 011 - train 0.66475 | val 0.72208
  Classification -> best τ=0.480 (val F1=0.2909)
  Directional -> Accuracy: 0.5000, MCC: 0.0991, F1: 0.2927

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.61376 | val 0.67908
  Epoch 020 - train 0.52688 | val 0.67289
  Epoch 022 - train 0.52491 | val 0.68407
  Classification -> best τ=0.565 (val F1=0.3854)
  Directional -> Accuracy: 0.4898, MCC: 0.0248, F1: 0.5283

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.67276 | val 0.69801
  Epoch 011 - train 0.65927 | val 0.69845
  Classification -> best τ=0.530 (val F1=0.0144)
  Directional -> Accuracy: 0.5333, MCC: -0.0200, F1: 0.6441

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.63418 | val 0.74124
  Epoch 014 - train 0.65414 | val 0.77120
  Classification -> best τ=0.475 (val F1=0.2084)
  Directional -> Accuracy: 0.4407, MCC: -0.1136, F1: 0.4590

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.68389 | val 0.68748
  Epoch 011 - train 0.67623 | val 0.69164
  Classification -> best τ=0.530 (val F1=0.1866)
  Directional -> Accuracy: 0.5227, MCC: 0.0000, F1: 0.6866

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.62702 | val 0.68032
  Epoch 018 - train 0.59880 | val 0.74733
  Classification -> best τ=0.510 (val F1=0.2815)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.4103

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.65176 | val 0.72605
  Epoch 011 - train 0.70054 | val 0.74142
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5435, MCC: 0.0000, F1: 0.7042

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.67255 | val 0.67699
  Epoch 020 - train 0.58444 | val 0.70867
  Epoch 023 - train 0.58598 | val 0.72831
  Classification -> best τ=0.460 (val F1=0.2955)
  Directional -> Accuracy: 0.5192, MCC: 0.0000, F1: 0.6835

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.61318 | val 0.71049
  Epoch 016 - train 0.61977 | val 0.70079
  Classification -> best τ=0.470 (val F1=0.4301)
  Directional -> Accuracy: 0.5467, MCC: 0.1701, F1: 0.4516

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 82). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.66461 | val 0.69718
  Epoch 011 - train 0.60184 | val 0.69725
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4878, MCC: 0.0000, F1: 0.6557

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.62865 | val 0.83453
  Epoch 011 - train 0.61910 | val 0.84832
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4565, MCC: 0.0000, F1: 0.6269

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.66315 | val 0.66680
  Epoch 019 - train 0.62330 | val 0.70518
  Classification -> best τ=0.340 (val F1=0.3138)
  Directional -> Accuracy: 0.5362, MCC: 0.0758, F1: 0.5676

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.65600 | val 0.68705
  Epoch 020 - train 0.59817 | val 0.68019
  Epoch 030 - train 0.55422 | val 0.74191
  Classification -> best τ=0.445 (val F1=0.3981)
  Directional -> Accuracy: 0.4889, MCC: 0.0000, F1: 0.0000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.59234 | val 0.88058
  Epoch 011 - train 0.61505 | val 0.88032
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4746, MCC: 0.0000, F1: 0.6437

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.62771 | val 0.79053
  Epoch 011 - train 0.65757 | val 0.79379
  Classification -> best τ=0.485 (val F1=0.1936)
  Directional -> Accuracy: 0.6122, MCC: 0.0000, F1: 0.7595

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 82). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 82). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 82). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 82). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.65370 | val 0.67887
  Epoch 020 - train 0.56716 | val 0.69655
  Epoch 022 - train 0.58969 | val 0.69782
  Classification -> best τ=0.550 (val F1=0.4327)
  Directional -> Accuracy: 0.5952, MCC: 0.0000, F1: 0.2609

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 82). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.63667 | val 0.72135
  Epoch 011 - train 0.70349 | val 0.72472
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5122, MCC: 0.0000, F1: 0.6774

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 82). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 82). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.66175 | val 0.84040
  Epoch 011 - train 0.65480 | val 0.90332
  Classification -> best τ=0.515 (val F1=0.0424)
  Directional -> Accuracy: 0.4935, MCC: -0.0212, F1: 0.5895

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 82). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 82). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.66413 | val 0.72486
  Epoch 011 - train 0.67286 | val 0.76036
  Classification -> best τ=0.485 (val F1=0.4430)
  Directional -> Accuracy: 0.5714, MCC: 0.1782, F1: 0.6557

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.63429 | val 0.78553
  Epoch 011 - train 0.59647 | val 0.80482
  Classification -> best τ=0.515 (val F1=0.1316)
  Directional -> Accuracy: 0.4255, MCC: 0.0000, F1: 0.0000

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.65781 | val 0.77964
  Epoch 011 - train 0.64787 | val 0.79480
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.3571, MCC: 0.0000, F1: 0.5263

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.64990 | val 0.68781
  Epoch 020 - train 0.60790 | val 0.81396
  Epoch 021 - train 0.64469 | val 0.79958
  Classification -> best τ=0.675 (val F1=0.1962)
  Directional -> Accuracy: 0.4483, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.64726 | val 0.84775
  Epoch 014 - train 0.63152 | val 0.94501
  Classification -> best τ=0.475 (val F1=0.3033)
  Directional -> Accuracy: 0.4576, MCC: -0.0865, F1: 0.4286

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.65610 | val 0.81827
  Epoch 011 - train 0.65730 | val 0.80211
  Classification -> best τ=0.535 (val F1=0.0541)
  Directional -> Accuracy: 0.5893, MCC: 0.1690, F1: 0.6349

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.63957 | val 0.93649
  Epoch 011 - train 0.62940 | val 0.92703
  Classification -> best τ=0.555 (val F1=0.1339)
  Directional -> Accuracy: 0.5345, MCC: 0.1371, F1: 0.6897

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.67305 | val 0.72563
  Epoch 020 - train 0.65071 | val 0.67021

[I 2026-02-22 09:00:29,848] Trial 35 finished with value: 0.18834557846975927 and parameters: {'feature_set': 'sector_finbert', 'model_type': 'LSTM', 'sequence_length': 6, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 32, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.8, 'batch_size': 32, 'learning_rate': 0.0020321206937131122, 'weight_decay': 1.9406755128252274e-06, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 1.3585008355403274, 'early_stopping_min_delta': 0.00578579130491705}. Best is trial 22 with value: 0.2833350641483003.

  Epoch 030 - train 0.61013 | val 0.65657
  Classification -> best τ=0.505 (val F1=0.4122)
  Directional -> Accuracy: 0.5556, MCC: 0.1091, F1: 0.5333

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.18834557846975927
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 12
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d', 'emotion_anger', 'emotion_disgust', 'emotion_fear', 'emotion_joy', 'emotion_neutral', 'emotion_sadness', 'emotion_surprize', 'emotion_anger_pct', 'emotion_disgust_pct', 'emotion_fear_pct', 'emotion_joy_pct', 'emotion_neutral_pct', 'emotion_sadness_pct', 'emotion_surprize_pct']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.54484 | val 0.81308
  Epoch 020 - train 0.51482 | val 1.00026
  Epoch 021 - train 0.50812 | val 0.99974
  Classification -> best τ=0.515 (val F1=0.1749)
  Directional -> Accuracy: 0.5000, MCC: 0.0303, F1: 0.5412

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 88). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.50890 | val 0.79652
  Epoch 020 - train 0.44367 | val 0.84303
  Epoch 021 - train 0.44730 | val 0.84502
  Classification -> best τ=0.575 (val F1=0.2346)
  Directional -> Accuracy: 0.4468, MCC: -0.0697, F1: 0.3500

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 88). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.57971 | val 1.01606
  Epoch 020 - train 0.53338 | val 1.15650
  Epoch 021 - train 0.49680 | val 1.15542
  Classification -> best τ=0.450 (val F1=0.1535)
  Directional -> Accuracy: 0.5417, MCC: 0.0000, F1: 0.7027

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.57730 | val 1.07680
  Epoch 020 - train 0.55931 | val 1.02247
  Epoch 021 - train 0.54717 | val 1.02839
  Classification -> best τ=0.445 (val F1=0.1610)
  Directional -> Accuracy: 0.5263, MCC: 0.0389, F1: 0.5814

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.47719 | val 0.74984
  Epoch 020 - train 0.43261 | val 0.88321
  Epoch 023 - train 0.39534 | val 0.91650
  Classification -> best τ=0.540 (val F1=0.3765)
  Directional -> Accuracy: 0.6154, MCC: 0.2682, F1: 0.5652

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.50053 | val 1.17122
  Epoch 020 - train 0.44574 | val 1.47511
  Epoch 021 - train 0.45784 | val 1.48821
  Classification -> best τ=0.455 (val F1=0.2152)
  Directional -> Accuracy: 0.4898, MCC: -0.0500, F1: 0.6269

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.58048 | val 0.87631
  Epoch 020 - train 0.55254 | val 1.00143
  Epoch 021 - train 0.55970 | val 1.00727
  Classification -> best τ=0.465 (val F1=0.2054)
  Directional -> Accuracy: 0.4571, MCC: 0.0833, F1: 0.5682

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 88). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 88). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.55577 | val 1.19789
  Epoch 020 - train 0.49332 | val 1.37364
  Epoch 021 - train 0.49317 | val 1.38252
  Classification -> best τ=0.565 (val F1=0.3669)
  Directional -> Accuracy: 0.4000, MCC: -0.1500, F1: 0.4706

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.51288 | val 0.70321
  Epoch 020 - train 0.42623 | val 0.81670
  Epoch 026 - train 0.42689 | val 0.83950
  Classification -> best τ=0.700 (val F1=0.4079)
  Directional -> Accuracy: 0.6190, MCC: 0.1189, F1: 0.3333

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 88). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 88). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.51256 | val 0.94854
  Epoch 020 - train 0.47368 | val 1.01873
  Epoch 021 - train 0.47711 | val 1.00966
  Classification -> best τ=0.435 (val F1=0.2394)
  Directional -> Accuracy: 0.4789, MCC: 0.0793, F1: 0.6022

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.53597 | val 1.07724
  Epoch 020 - train 0.48024 | val 1.22193
  Epoch 021 - train 0.49321 | val 1.23557
  Classification -> best τ=0.500 (val F1=0.1555)
  Directional -> Accuracy: 0.4510, MCC: -0.0855, F1: 0.6000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.57047 | val 0.95832
  Epoch 020 - train 0.52807 | val 1.06932
  Epoch 021 - train 0.52143 | val 1.06666
  Classification -> best τ=0.505 (val F1=0.1370)
  Directional -> Accuracy: 0.6102, MCC: 0.2485, F1: 0.6933

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.55265 | val 1.09056
  Epoch 020 - train 0.48680 | val 1.17237
  Epoch 021 - train 0.49517 | val 1.16320
  Classification -> best τ=0.470 (val F1=0.3409)
  Directional -> Accuracy: 0.5000, MCC: 0.0466, F1: 0.5769

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 88). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.52904 | val 0.66006
  Epoch 020 - train 0.46612 | val 0.64084
  Epoch 023 - train 0.48809 | val 0.64214
  Classification -> best τ=0.475 (val F1=0.4257)
  Directional -> Accuracy: 0.4839, MCC: -0.1280, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.55377 | val 1.52399
  Epoch 020 - train 0.51239 | val 1.60501
  Epoch 021 - train 0.48808 | val 1.60999
  Classification -> best τ=0.550 (val F1=0.1675)
  Directional -> Accuracy: 0.5660, MCC: 0.2096, F1: 0.1481

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.53564 | val 0.90311
  Epoch 020 - train 0.48199 | val 1.01477
  Epoch 021 - train 0.46736 | val 1.01384
  Classification -> best τ=0.420 (val F1=0.2527)
  Directional -> Accuracy: 0.5634, MCC: 0.1827, F1: 0.7103

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.55020 | val 1.35044
  Epoch 020 - train 0.52245 | val 1.53250
  Epoch 021 - train 0.49738 | val 1.54047
  Classification -> best τ=0.500 (val F1=0.1184)
  Directional -> Accuracy: 0.3833, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.54039 | val 1.08068
  Epoch 020 - train 0.51986 | val 1.23514
  Epoch 021 - train 0.52507 | val 1.24333
  Classification -> best τ=0.515 (val F1=0.1936)
  Directional -> Accuracy: 0.3636, MCC: -0.1948, F1: 0.2687

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.51824 | val 0.76082
  Epoch 020 - train 0.46714 | val 0.77623
  Epoch 022 - train 0.47234 | val 0.77011
  Classification -> best τ=0.525 (val F1=0.3326)
  Directional -> Accuracy: 0.4697, MCC: 0.0938, F1: 0.2857

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 88). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.53958 | val 0.73192
  Epoch 020 - train 0.49056 | val 0.99648
  Epoch 023 - train 0.49309 | val 1.02424
  Classification -> best τ=0.400 (val F1=0.2661)
  Directional -> Accuracy: 0.5263, MCC: 0.0009, F1: 0.6538

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.45880 | val 0.75662
  Epoch 020 - train 0.38462 | val 1.13671
  Epoch 023 - train 0.34788 | val 1.25784
  Classification -> best τ=0.540 (val F1=0.2266)
  Directional -> Accuracy: 0.3673, MCC: -0.1215, F1: 0.2051

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 88). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 88). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 88). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.54711 | val 0.84287
  Epoch 020 - train 0.49266 | val 0.99195
  Epoch 022 - train 0.46941 | val 0.99702
  Classification -> best τ=0.450 (val F1=0.3166)
  Directional -> Accuracy: 0.5522, MCC: 0.1116, F1: 0.6429

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.53070 | val 0.82887
  Epoch 020 - train 0.49422 | val 0.82627
  Epoch 021 - train 0.51481 | val 0.83031
  Classification -> best τ=0.520 (val F1=0.2095)
  Directional -> Accuracy: 0.5254, MCC: 0.0817, F1: 0.5172

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.52909 | val 0.98696
  Epoch 020 - train 0.51819 | val 1.14973
  Epoch 021 - train 0.48468 | val 1.14852
  Classification -> best τ=0.450 (val F1=0.2525)
  Directional -> Accuracy: 0.5224, MCC: 0.1312, F1: 0.6522

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.51794 | val 0.80472
  Epoch 020 - train 0.45583 | val 0.85213
  Epoch 023 - train 0.43630 | val 0.87499
  Classification -> best τ=0.525 (val F1=0.4027)
  Directional -> Accuracy: 0.5789, MCC: 0.2579, F1: 0.4783

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.58326 | val 1.32432
  Epoch 020 - train 0.52066 | val 1.82758
  Epoch 021 - train 0.51100 | val 1.83999
  Classification -> best τ=0.435 (val F1=0.1744)
  Directional -> Accuracy: 0.5417, MCC: 0.0989, F1: 0.5217

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.53538 | val 0.94031
  Epoch 020 - train 0.47715 | val 1.05027
  Epoch 021 - train 0.50403 | val 1.05413
  Classification -> best τ=0.500 (val F1=0.1902)
  Directional -> Accuracy: 0.6136, MCC: 0.1942, F1: 0.6792

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.54101 | val 0.87905
  Epoch 020 - train 0.50763 | val 0.92667
  Epoch 021 - train 0.50370 | val 0.92709
  Classification -> best τ=0.440 (val F1=0.1323)
  Directional -> Accuracy: 0.4310, MCC: -0.1469, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.56599 | val 0.71572
  Epoch 020 - train 0.53917 | val 0.72826
  Epoch 021 - train 0.54148 | val 0.72958
  Classification -> best τ=0.475 (val F1=0.2381)
  Directional -> Accuracy: 0.6279, MCC: 0.2731, F1: 0.7241

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.58280 | val 0.97649
  Epoch 020 - train 0.51145 | val 1.24481
  Epoch 021 - train 0.51427 | val 1.25100
  Classification -> best τ=0.475 (val F1=0.2562)
  Directional -> Accuracy: 0.6222, MCC: 0.2621, F1: 0.5641

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.57175 | val 0.89569
  Epoch 020 - train 0.52536 | val 0.93897
  Epoch 021 - train 0.51767 | val 0.93716
  Classification -> best τ=0.460 (val F1=0.2132)
  Directional -> Accuracy: 0.5111, MCC: -0.1410, F1: 0.6765

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.52026 | val 0.70956
  Epoch 020 - train 0.40926 | val 0.76746
  Epoch 023 - train 0.41369 | val 0.78396
  Classification -> best τ=0.720 (val F1=0.2335)
  Directional -> Accuracy: 0.4902, MCC: 0.0466, F1: 0.1875

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.57835 | val 1.19053
  Epoch 020 - train 0.51309 | val 1.29525
  Epoch 021 - train 0.50179 | val 1.30704
  Classification -> best τ=0.485 (val F1=0.2080)
  Directional -> Accuracy: 0.4324, MCC: 0.0000, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 88). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.58299 | val 0.72606
  Epoch 020 - train 0.51287 | val 0.73395
  Epoch 021 - train 0.52454 | val 0.73440
  Classification -> best τ=0.415 (val F1=0.2041)
  Directional -> Accuracy: 0.4872, MCC: 0.0000, F1: 0.6552

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.51230 | val 1.00522
  Epoch 020 - train 0.49896 | val 1.04458
  Epoch 021 - train 0.48637 | val 1.04355
  Classification -> best τ=0.405 (val F1=0.2017)
  Directional -> Accuracy: 0.4667, MCC: 0.0000, F1: 0.6364

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.56107 | val 0.74868
  Epoch 020 - train 0.49534 | val 0.80464
  Epoch 023 - train 0.49393 | val 0.80978
  Classification -> best τ=0.325 (val F1=0.3801)
  Directional -> Accuracy: 0.6176, MCC: 0.3022, F1: 0.5806

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.47059 | val 0.66530
  Epoch 020 - train 0.33449 | val 0.73001
  Epoch 028 - train 0.31875 | val 0.76016
  Classification -> best τ=0.600 (val F1=0.3438)
  Directional -> Accuracy: 0.5909, MCC: 0.1849, F1: 0.5500

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.50445 | val 0.97403
  Epoch 020 - train 0.47872 | val 1.13647
  Epoch 021 - train 0.46452 | val 1.14987
  Classification -> best τ=0.450 (val F1=0.1687)
  Directional -> Accuracy: 0.5000, MCC: 0.0121, F1: 0.5246

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.53683 | val 1.18172
  Epoch 020 - train 0.48179 | val 1.29327
  Epoch 021 - train 0.48569 | val 1.29332
  Classification -> best τ=0.515 (val F1=0.2799)
  Directional -> Accuracy: 0.6250, MCC: 0.0538, F1: 0.7632

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 88). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 88). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 88). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 88). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.54911 | val 0.92574
  Epoch 020 - train 0.49059 | val 1.05136
  Epoch 021 - train 0.50466 | val 1.06440
  Classification -> best τ=0.475 (val F1=0.0277)
  Directional -> Accuracy: 0.4250, MCC: -0.0176, F1: 0.4651

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 88). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.56126 | val 0.77937
  Epoch 020 - train 0.51898 | val 0.93836
  Epoch 021 - train 0.52108 | val 0.94709
  Classification -> best τ=0.525 (val F1=0.2548)
  Directional -> Accuracy: 0.5897, MCC: 0.1821, F1: 0.6000

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 88). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 88). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.51312 | val 1.50570
  Epoch 020 - train 0.46309 | val 1.82577
  Epoch 021 - train 0.47337 | val 1.83977
  Classification -> best τ=0.425 (val F1=0.2439)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 88). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 88). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 88). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.56584 | val 0.70586
  Epoch 020 - train 0.50833 | val 0.76258
  Epoch 021 - train 0.51111 | val 0.76320
  Classification -> best τ=0.445 (val F1=0.0500)
  Directional -> Accuracy: 0.5417, MCC: 0.1026, F1: 0.6452

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.51200 | val 0.81172
  Epoch 020 - train 0.44842 | val 0.85855
  Epoch 021 - train 0.47090 | val 0.86511
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5556, MCC: 0.0000, F1: 0.7143

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.52729 | val 0.94262
  Epoch 020 - train 0.49215 | val 0.99567
  Epoch 021 - train 0.48259 | val 0.99828
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.3659, MCC: 0.0000, F1: 0.5357

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.57352 | val 1.01248
  Epoch 020 - train 0.51783 | val 1.10187
  Epoch 021 - train 0.50616 | val 1.09857

[I 2026-02-22 09:03:27,241] Trial 36 finished with value: 0.22950176614051696 and parameters: {'feature_set': 'sector_emotion', 'model_type': 'BiGRU', 'sequence_length': 12, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.4, 'dropout': 0.2, 'batch_size': 32, 'learning_rate': 0.0005134873323766584, 'weight_decay': 4.5282173627177947e-07, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 30, 'huber_delta': 1.1701460595084194, 'early_stopping_min_delta': 0.008774818588504107}. Best is trial 22 with value: 0.2833350641483003.

  Classification -> best τ=0.525 (val F1=0.3165)
  Directional -> Accuracy: 0.5806, MCC: 0.1653, F1: 0.5938

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.22950176614051696
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: classification
Sequence length: 12
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d', 'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down', 'finbert_neutral']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.54261 | val 1.32051
  Epoch 013 - train 0.52511 | val 1.12331
  Classification -> best τ=0.740 (val F1=0.1997)
  Directional -> Accuracy: 0.5513, MCC: 0.0240, F1: 0.1026

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 88). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.50337 | val 0.70516
  Epoch 015 - train 0.37053 | val 0.86333
  Classification -> best τ=0.435 (val F1=0.3934)
  Directional -> Accuracy: 0.6170, MCC: 0.2108, F1: 0.7097

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 88). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.54606 | val 1.08114
  Epoch 011 - train 0.49298 | val 1.21545
  Classification -> best τ=0.490 (val F1=0.1800)
  Directional -> Accuracy: 0.5417, MCC: 0.0000, F1: 0.7027

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.59745 | val 1.15186
  Epoch 011 - train 0.57034 | val 1.11926
  Classification -> best τ=0.450 (val F1=0.1095)
  Directional -> Accuracy: 0.5526, MCC: 0.1792, F1: 0.4138

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.45911 | val 0.89042
  Epoch 014 - train 0.39493 | val 1.18768
  Classification -> best τ=0.525 (val F1=0.4747)
  Directional -> Accuracy: 0.6154, MCC: 0.2682, F1: 0.5652

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.48346 | val 1.24925
  Epoch 011 - train 0.54054 | val 1.22562
  Classification -> best τ=0.550 (val F1=0.4148)
  Directional -> Accuracy: 0.4694, MCC: -0.0637, F1: 0.5000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.56171 | val 1.39441
  Epoch 011 - train 0.55218 | val 1.47019
  Classification -> best τ=0.500 (val F1=0.1267)
  Directional -> Accuracy: 0.4714, MCC: 0.0544, F1: 0.5432

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 88). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 88). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.53443 | val 0.73346
  Epoch 011 - train 0.51903 | val 0.81160
  Classification -> best τ=0.520 (val F1=0.1517)
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.5938

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.50689 | val 1.35643
  Epoch 011 - train 0.52079 | val 1.58627
  Classification -> best τ=0.570 (val F1=0.3364)
  Directional -> Accuracy: 0.3810, MCC: 0.0000, F1: 0.5517

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 88). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 88). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.47945 | val 1.49039
  Epoch 011 - train 0.44081 | val 1.35045
  Classification -> best τ=0.370 (val F1=0.2614)
  Directional -> Accuracy: 0.4366, MCC: 0.0000, F1: 0.6078

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.52308 | val 1.25445
  Epoch 011 - train 0.50620 | val 1.31849
  Classification -> best τ=0.570 (val F1=0.2323)
  Directional -> Accuracy: 0.5686, MCC: 0.1633, F1: 0.2143

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.54867 | val 1.17848
  Epoch 011 - train 0.51667 | val 1.17991
  Classification -> best τ=0.515 (val F1=0.0894)
  Directional -> Accuracy: 0.5763, MCC: 0.1533, F1: 0.6269

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.49566 | val 1.27034
  Epoch 011 - train 0.47378 | val 1.26328
  Classification -> best τ=0.450 (val F1=0.1653)
  Directional -> Accuracy: 0.4091, MCC: -0.1693, F1: 0.5517

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 88). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.52999 | val 0.78074
  Epoch 013 - train 0.50785 | val 0.60838
  Classification -> best τ=0.385 (val F1=0.4381)
  Directional -> Accuracy: 0.5161, MCC: 0.0377, F1: 0.3478

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.52120 | val 1.16961
  Epoch 011 - train 0.49455 | val 0.85453
  Classification -> best τ=0.615 (val F1=0.1750)
  Directional -> Accuracy: 0.5660, MCC: 0.2096, F1: 0.1481

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.51765 | val 1.14858
  Epoch 011 - train 0.50839 | val 1.23305
  Classification -> best τ=0.570 (val F1=0.2731)
  Directional -> Accuracy: 0.5493, MCC: 0.0906, F1: 0.5897

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.53613 | val 1.43384
  Epoch 011 - train 0.55315 | val 1.32714
  Classification -> best τ=0.420 (val F1=0.1457)
  Directional -> Accuracy: 0.6167, MCC: 0.0000, F1: 0.7629

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.57374 | val 1.59253
  Epoch 011 - train 0.52393 | val 1.50336
  Classification -> best τ=0.475 (val F1=0.1698)
  Directional -> Accuracy: 0.6104, MCC: 0.0000, F1: 0.7581

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.55811 | val 0.66654
  Epoch 014 - train 0.51188 | val 0.71512
  Classification -> best τ=0.415 (val F1=0.2985)
  Directional -> Accuracy: 0.5909, MCC: 0.0000, F1: 0.7429

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 88). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.53694 | val 0.75849
  Epoch 013 - train 0.47227 | val 0.87455
  Classification -> best τ=0.345 (val F1=0.3188)
  Directional -> Accuracy: 0.5526, MCC: 0.1577, F1: 0.4516

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.51437 | val 0.85302
  Epoch 011 - train 0.49603 | val 0.90609
  Classification -> best τ=0.515 (val F1=0.2233)
  Directional -> Accuracy: 0.4490, MCC: 0.1555, F1: 0.2703

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 88). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 88). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 88). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.55307 | val 0.75968
  Epoch 011 - train 0.53673 | val 0.71554
  Classification -> best τ=0.485 (val F1=0.2409)
  Directional -> Accuracy: 0.6269, MCC: 0.2602, F1: 0.6753

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.56833 | val 1.37933
  Epoch 011 - train 0.55101 | val 1.44847
  Classification -> best τ=0.540 (val F1=0.2555)
  Directional -> Accuracy: 0.5763, MCC: 0.1680, F1: 0.5902

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.51141 | val 1.37671
  Epoch 011 - train 0.51273 | val 1.17613
  Classification -> best τ=0.415 (val F1=0.1921)
  Directional -> Accuracy: 0.5522, MCC: 0.1249, F1: 0.6053

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.50348 | val 0.91099
  Epoch 012 - train 0.46348 | val 0.94954
  Classification -> best τ=0.540 (val F1=0.4027)
  Directional -> Accuracy: 0.5439, MCC: 0.1587, F1: 0.4583

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.48151 | val 1.38230
  Epoch 011 - train 0.46108 | val 1.71799
  Classification -> best τ=0.470 (val F1=0.0486)
  Directional -> Accuracy: 0.5208, MCC: -0.0396, F1: 0.3030

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.51903 | val 1.10278
  Epoch 011 - train 0.53648 | val 0.97095
  Classification -> best τ=0.495 (val F1=0.1116)
  Directional -> Accuracy: 0.5455, MCC: 0.1282, F1: 0.5455

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.51295 | val 0.90257
  Epoch 011 - train 0.51196 | val 0.98730
  Classification -> best τ=0.475 (val F1=0.2435)
  Directional -> Accuracy: 0.4483, MCC: -0.0283, F1: 0.1111

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.55169 | val 0.88807
  Epoch 011 - train 0.51386 | val 1.21331
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.52519 | val 1.24681
  Epoch 011 - train 0.52514 | val 1.19460
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5111, MCC: 0.0000, F1: 0.6765

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.55859 | val 0.99555
  Epoch 011 - train 0.53100 | val 1.06821
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5333, MCC: 0.0000, F1: 0.6957

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.50016 | val 0.95869
  Epoch 011 - train 0.47613 | val 0.99378
  Classification -> best τ=0.500 (val F1=0.1648)
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.53032 | val 0.97611
  Epoch 011 - train 0.51209 | val 1.10015
  Classification -> best τ=0.390 (val F1=0.2593)
  Directional -> Accuracy: 0.5405, MCC: 0.1627, F1: 0.4516

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 88). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.52039 | val 0.71195
  Epoch 011 - train 0.49666 | val 0.74316
  Classification -> best τ=0.475 (val F1=0.3125)
  Directional -> Accuracy: 0.5897, MCC: 0.3295, F1: 0.7037

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.48962 | val 1.10878
  Epoch 011 - train 0.49047 | val 1.16057
  Classification -> best τ=0.485 (val F1=0.0714)
  Directional -> Accuracy: 0.4667, MCC: 0.0000, F1: 0.6364

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.51710 | val 1.07236
  Epoch 011 - train 0.50781 | val 1.02644
  Classification -> best τ=0.360 (val F1=0.3342)
  Directional -> Accuracy: 0.5000, MCC: 0.0508, F1: 0.4516

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.51074 | val 0.81634
  Epoch 011 - train 0.46776 | val 0.81898
  Classification -> best τ=0.510 (val F1=0.3137)
  Directional -> Accuracy: 0.3636, MCC: -0.2774, F1: 0.4167

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.49345 | val 2.29333
  Epoch 011 - train 0.50090 | val 2.33445
  Classification -> best τ=0.495 (val F1=0.2044)
  Directional -> Accuracy: 0.5000, MCC: 0.0121, F1: 0.5246

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.45372 | val 1.52396
  Epoch 011 - train 0.42880 | val 1.60303
  Classification -> best τ=0.490 (val F1=0.3001)
  Directional -> Accuracy: 0.4792, MCC: -0.2176, F1: 0.6269

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 88). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 88). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 88). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 88). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.51175 | val 1.56719
  Epoch 011 - train 0.50419 | val 1.44748
  Classification -> best τ=0.535 (val F1=0.2000)
  Directional -> Accuracy: 0.4000, MCC: -0.1791, F1: 0.3333

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 88). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.51956 | val 0.98449
  Epoch 011 - train 0.52497 | val 1.05129
  Classification -> best τ=0.515 (val F1=0.2467)
  Directional -> Accuracy: 0.5128, MCC: 0.0600, F1: 0.4242

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 88). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 88). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.51960 | val 1.54260
  Epoch 011 - train 0.51183 | val 1.71031
  Classification -> best τ=0.435 (val F1=0.2073)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 88). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 88). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 88). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.53378 | val 1.10189
  Epoch 011 - train 0.51648 | val 1.23319
  Classification -> best τ=0.455 (val F1=0.1560)
  Directional -> Accuracy: 0.5208, MCC: 0.1459, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.47277 | val 1.17353
  Epoch 011 - train 0.47639 | val 1.08293
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5556, MCC: 0.0000, F1: 0.7143

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.50005 | val 1.18336
  Epoch 011 - train 0.50163 | val 1.17136
  Classification -> best τ=0.470 (val F1=0.0476)
  Directional -> Accuracy: 0.3659, MCC: 0.0000, F1: 0.5357

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.56497 | val 1.12311
  Epoch 011 - train 0.54630 | val 1.11457
  Classification -> best τ=0.495 (val F1=0.1978)
  Directional -> Accuracy: 0.6140, MCC: 0.2114, F1: 0.6857

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.53862 | val 1.17687
  Epoch 012 - train 0.50922 | val 1.03082
  Classification -> best τ=0.535 (val F1=0.4622)
  Directional -> Accuracy: 0.5690, MCC: 0.1484, F1: 0.6032

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.57278 | val 1.95402
  Epoch 011 - train 0.55671 | val 2.07045
  Classification -> best τ=0.460 (val F1=0.2617)
  Directional -> Accuracy: 0.6182, MCC: 0.3340, F1: 0.7342

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.50114 | val 1.00149
  Epoch 011 - train 0.50309 | val 1.49376
  Classification -> best τ=0.540 (val F1=0.2225)
  Directional -> Accuracy: 0.5088, MCC: 0.0000, F1: 0.6744

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...

[I 2026-02-22 09:04:08,538] Trial 37 finished with value: 0.2191068846522429 and parameters: {'feature_set': 'sector_finbert', 'model_type': 'GRU', 'sequence_length': 12, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.1, 'batch_size': 32, 'learning_rate': 0.0016574059832585569, 'weight_decay': 1.448729719398663e-06, 'lr_patience': 7, 'lr_factor': 0.8, 'early_stopping_patience': 10, 'max_epochs': 20, 'huber_delta': 0.9228731236783586, 'early_stopping_min_delta': 0.009920767107167725}. Best is trial 22 with value: 0.2833350641483003.

  Epoch 010 - train 0.53960 | val 1.15088
  Epoch 011 - train 0.52478 | val 1.02370
  Classification -> best τ=0.505 (val F1=0.3206)
  Directional -> Accuracy: 0.4516, MCC: -0.1034, F1: 0.3929

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2191068846522429
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: classification
Sequence length: 6
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.56495 | val 0.93717
  Epoch 020 - train 0.49257 | val 1.17395
  Epoch 024 - train 0.48583 | val 1.19030
  Classification -> best τ=0.600 (val F1=0.2346)
  Directional -> Accuracy: 0.5696, MCC: 0.1015, F1: 0.4138

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 82). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.47656 | val 0.81687
  Epoch 020 - train 0.44519 | val 0.87264
  Epoch 021 - train 0.42276 | val 0.87545
  Classification -> best τ=0.555 (val F1=0.1654)
  Directional -> Accuracy: 0.5417, MCC: 0.2085, F1: 0.3889

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 82). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.56262 | val 1.03680
  Epoch 020 - train 0.52528 | val 1.24348
  Epoch 021 - train 0.52411 | val 1.24982
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.56987 | val 0.70772
  Epoch 020 - train 0.54742 | val 0.71092
  Epoch 021 - train 0.53263 | val 0.70854
  Classification -> best τ=0.470 (val F1=0.1286)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.51045 | val 0.66046
  Epoch 020 - train 0.43979 | val 0.80464
  Epoch 027 - train 0.41931 | val 0.88080
  Classification -> best τ=0.615 (val F1=0.3984)
  Directional -> Accuracy: 0.6604, MCC: 0.3584, F1: 0.6087

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.53212 | val 0.78792
  Epoch 020 - train 0.50192 | val 1.00893
  Epoch 021 - train 0.49747 | val 1.02296
  Classification -> best τ=0.545 (val F1=0.0083)
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.58576 | val 0.81495
  Epoch 020 - train 0.52952 | val 0.89977
  Epoch 021 - train 0.52362 | val 0.90846
  Classification -> best τ=0.475 (val F1=0.2782)
  Directional -> Accuracy: 0.5070, MCC: 0.0990, F1: 0.5570

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 82). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 82). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.54355 | val 0.79647
  Epoch 020 - train 0.50841 | val 1.08823
  Epoch 021 - train 0.50704 | val 1.10018
  Classification -> best τ=0.505 (val F1=0.1387)
  Directional -> Accuracy: 0.6170, MCC: 0.1376, F1: 0.2500

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.55902 | val 0.78386
  Epoch 020 - train 0.49053 | val 0.94431
  Epoch 021 - train 0.49912 | val 0.95952
  Classification -> best τ=0.525 (val F1=0.2950)
  Directional -> Accuracy: 0.3953, MCC: 0.0000, F1: 0.5667

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 82). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 82). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.54106 | val 0.78093
  Epoch 020 - train 0.48851 | val 0.85100
  Epoch 021 - train 0.46596 | val 0.85352
  Classification -> best τ=0.495 (val F1=0.1290)
  Directional -> Accuracy: 0.4306, MCC: 0.0000, F1: 0.6019

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.54548 | val 0.73222
  Epoch 020 - train 0.46645 | val 0.79840
  Epoch 021 - train 0.45889 | val 0.81233
  Classification -> best τ=0.535 (val F1=0.2780)
  Directional -> Accuracy: 0.6154, MCC: 0.2334, F1: 0.4118

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.56397 | val 0.91892
  Epoch 020 - train 0.52457 | val 1.03835
  Epoch 021 - train 0.52989 | val 1.04658
  Classification -> best τ=0.475 (val F1=0.1748)
  Directional -> Accuracy: 0.5167, MCC: 0.1302, F1: 0.6742

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.53179 | val 0.73573
  Epoch 020 - train 0.49482 | val 0.77308
  Epoch 021 - train 0.48188 | val 0.77508
  Classification -> best τ=0.485 (val F1=0.0638)
  Directional -> Accuracy: 0.4889, MCC: 0.0714, F1: 0.6349

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 82). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.55854 | val 0.77688
  Epoch 020 - train 0.49279 | val 0.89542
  Epoch 025 - train 0.47822 | val 0.90206
  Classification -> best τ=0.430 (val F1=0.4160)
  Directional -> Accuracy: 0.4603, MCC: -0.1459, F1: 0.1053

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.53607 | val 2.16649
  Epoch 020 - train 0.49169 | val 2.92573
  Epoch 021 - train 0.47025 | val 2.95772
  Classification -> best τ=0.500 (val F1=0.1881)
  Directional -> Accuracy: 0.5370, MCC: 0.1193, F1: 0.6377

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.53287 | val 0.76617
  Epoch 020 - train 0.45737 | val 0.87339
  Epoch 024 - train 0.45673 | val 0.87648
  Classification -> best τ=0.325 (val F1=0.2789)
  Directional -> Accuracy: 0.5694, MCC: 0.1838, F1: 0.7156

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.58755 | val 1.00792
  Epoch 020 - train 0.53269 | val 1.26876
  Epoch 021 - train 0.52792 | val 1.28056
  Classification -> best τ=0.540 (val F1=0.1657)
  Directional -> Accuracy: 0.3934, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.55712 | val 1.32859
  Epoch 020 - train 0.51885 | val 1.40519
  Epoch 021 - train 0.50564 | val 1.40000
  Classification -> best τ=0.495 (val F1=0.1455)
  Directional -> Accuracy: 0.4744, MCC: 0.1547, F1: 0.2807

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.57210 | val 0.66294
  Epoch 020 - train 0.47372 | val 0.68470
  Epoch 030 - train 0.42220 | val 0.74200
  Classification -> best τ=0.280 (val F1=0.2357)
  Directional -> Accuracy: 0.4776, MCC: 0.0633, F1: 0.3396

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 82). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.54585 | val 0.71580
  Epoch 020 - train 0.46691 | val 0.73834
  Epoch 025 - train 0.44410 | val 0.74912
  Classification -> best τ=0.395 (val F1=0.3239)
  Directional -> Accuracy: 0.4935, MCC: 0.1072, F1: 0.2041

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.51796 | val 0.76987
  Epoch 020 - train 0.45907 | val 0.85318
  Epoch 021 - train 0.48177 | val 0.85860
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.6200, MCC: 0.0000, F1: 0.7654

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 82). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 82). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 82). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.55063 | val 0.79973
  Epoch 020 - train 0.49929 | val 0.88886
  Epoch 021 - train 0.48992 | val 0.89280
  Classification -> best τ=0.495 (val F1=0.1741)
  Directional -> Accuracy: 0.4853, MCC: -0.0374, F1: 0.2553

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.56890 | val 0.79157
  Epoch 020 - train 0.49378 | val 0.99176
  Epoch 021 - train 0.50877 | val 1.00582
  Classification -> best τ=0.515 (val F1=0.2650)
  Directional -> Accuracy: 0.5000, MCC: 0.0532, F1: 0.4643

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.52751 | val 1.08223
  Epoch 020 - train 0.45402 | val 1.14869
  Epoch 021 - train 0.46310 | val 1.18273
  Classification -> best τ=0.490 (val F1=0.1757)
  Directional -> Accuracy: 0.4853, MCC: -0.0074, F1: 0.6392

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.53601 | val 0.69941
  Epoch 020 - train 0.43839 | val 0.82254
  Epoch 026 - train 0.43666 | val 0.84334
  Classification -> best τ=0.485 (val F1=0.4723)
  Directional -> Accuracy: 0.5862, MCC: 0.2461, F1: 0.5000

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.54561 | val 0.75172
  Epoch 020 - train 0.53502 | val 0.96664
  Epoch 021 - train 0.54303 | val 0.97944
  Classification -> best τ=0.460 (val F1=0.2787)
  Directional -> Accuracy: 0.6122, MCC: 0.1753, F1: 0.3448

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.55455 | val 0.71261
  Epoch 020 - train 0.50210 | val 0.74151
  Epoch 021 - train 0.47931 | val 0.74445
  Classification -> best τ=0.490 (val F1=0.0223)
  Directional -> Accuracy: 0.4222, MCC: -0.0801, F1: 0.3500

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.54071 | val 0.86357
  Epoch 020 - train 0.48640 | val 0.93078
  Epoch 021 - train 0.50124 | val 0.93868
  Classification -> best τ=0.445 (val F1=0.1606)
  Directional -> Accuracy: 0.4576, MCC: -0.1002, F1: 0.5152

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.53209 | val 0.71216
  Epoch 020 - train 0.50813 | val 0.81529
  Epoch 021 - train 0.48476 | val 0.81946
  Classification -> best τ=0.515 (val F1=0.1975)
  Directional -> Accuracy: 0.5909, MCC: 0.1923, F1: 0.6897

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.55484 | val 0.71932
  Epoch 020 - train 0.50954 | val 0.74706
  Epoch 021 - train 0.52950 | val 0.74876
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.58301 | val 0.72866
  Epoch 020 - train 0.55171 | val 0.83154
  Epoch 021 - train 0.55470 | val 0.83045
  Classification -> best τ=0.525 (val F1=0.1227)
  Directional -> Accuracy: 0.4130, MCC: -0.1552, F1: 0.1818

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.52413 | val 0.73124
  Epoch 020 - train 0.43087 | val 0.78803
  Epoch 025 - train 0.40614 | val 0.80423
  Classification -> best τ=0.495 (val F1=0.2689)
  Directional -> Accuracy: 0.6346, MCC: 0.3365, F1: 0.7324

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.53763 | val 0.92710
  Epoch 020 - train 0.46909 | val 1.20636
  Epoch 023 - train 0.45993 | val 1.22650
  Classification -> best τ=0.460 (val F1=0.2477)
  Directional -> Accuracy: 0.5333, MCC: 0.1458, F1: 0.4262

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 82). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.56456 | val 0.68945
  Epoch 020 - train 0.49765 | val 0.85532
  Epoch 028 - train 0.48039 | val 0.98644
  Classification -> best τ=0.490 (val F1=0.2618)
  Directional -> Accuracy: 0.4878, MCC: -0.0055, F1: 0.6441

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.55105 | val 0.91574
  Epoch 020 - train 0.51265 | val 1.15554
  Epoch 021 - train 0.51682 | val 1.15876
  Classification -> best τ=0.490 (val F1=0.0338)
  Directional -> Accuracy: 0.4348, MCC: -0.1073, F1: 0.5000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.56460 | val 0.72904
  Epoch 020 - train 0.51614 | val 0.74793
  Epoch 026 - train 0.50176 | val 0.75483
  Classification -> best τ=0.300 (val F1=0.3271)
  Directional -> Accuracy: 0.5507, MCC: 0.1661, F1: 0.5079

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.53991 | val 0.68477
  Epoch 020 - train 0.46826 | val 0.72297
  Epoch 028 - train 0.42632 | val 0.71384
  Classification -> best τ=0.420 (val F1=0.2651)
  Directional -> Accuracy: 0.5778, MCC: 0.2020, F1: 0.4242

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.52494 | val 0.96751
  Epoch 020 - train 0.45901 | val 1.05903
  Epoch 021 - train 0.45878 | val 1.06812
  Classification -> best τ=0.535 (val F1=0.2184)
  Directional -> Accuracy: 0.5254, MCC: 0.0000, F1: 0.0000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.52847 | val 0.79879
  Epoch 020 - train 0.46836 | val 0.86901
  Epoch 021 - train 0.46535 | val 0.87289
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.6122, MCC: 0.0000, F1: 0.7595

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 82). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 82). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 82). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 82). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.52400 | val 0.71068
  Epoch 020 - train 0.42043 | val 0.82533
  Epoch 021 - train 0.43033 | val 0.83466
  Classification -> best τ=0.535 (val F1=0.1917)
  Directional -> Accuracy: 0.6190, MCC: -0.0574, F1: 0.1111

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 82). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.57063 | val 0.72409
  Epoch 020 - train 0.55635 | val 0.80647
  Epoch 021 - train 0.55267 | val 0.81976
  Classification -> best τ=0.510 (val F1=0.0173)
  Directional -> Accuracy: 0.4634, MCC: -0.0692, F1: 0.3889

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 82). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 82). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.53422 | val 0.97769
  Epoch 020 - train 0.49202 | val 1.18796
  Epoch 021 - train 0.48586 | val 1.19939
  Classification -> best τ=0.490 (val F1=0.1162)
  Directional -> Accuracy: 0.4935, MCC: 0.0000, F1: 0.0000

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 82). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 82). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.57974 | val 0.94473
  Epoch 020 - train 0.53460 | val 1.81856
  Epoch 021 - train 0.52391 | val 1.83407
  Classification -> best τ=0.465 (val F1=0.0109)
  Directional -> Accuracy: 0.6939, MCC: 0.4389, F1: 0.7458

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.54556 | val 0.80041
  Epoch 020 - train 0.48584 | val 1.07996
  Epoch 021 - train 0.47975 | val 1.09117
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5745, MCC: 0.0000, F1: 0.7297

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.53384 | val 0.90525
  Epoch 020 - train 0.48237 | val 1.04674
  Epoch 021 - train 0.51298 | val 1.04836
  Classification -> best τ=0.475 (val F1=0.1677)
  Directional -> Accuracy: 0.4048, MCC: 0.1667, F1: 0.5455

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.57213 | val 0.75318
  Epoch 020 - train 0.53619 | val 0.81837
  Epoch 021 - train 0.54288 | val 0.82368
  Classification -> best τ=0.530 (val F1=0.1962)
  Directional -> Accuracy: 0.4483, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.52996 | val 0.83465

[I 2026-02-22 09:05:41,922] Trial 38 finished with value: 0.18852214541482365 and parameters: {'feature_set': 'sector', 'model_type': 'BiLSTM', 'sequence_length': 6, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 1, 'inter_rnn_drop': 0.4, 'dropout': 0.4, 'batch_size': 32, 'learning_rate': 0.00026008372242762666, 'weight_decay': 3.747772716723909e-06, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 30, 'huber_delta': 1.3199212504892017, 'early_stopping_min_delta': 0.007627231248056503}. Best is trial 22 with value: 0.2833350641483003.

  Epoch 026 - train 0.47722 | val 0.92169
  Classification -> best τ=0.565 (val F1=0.3305)
  Directional -> Accuracy: 0.5397, MCC: 0.0853, F1: 0.1212

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.18852214541482365
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 12
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'positive_emotion', 'negative_emotion', 'uncertainty_emotion', 'positive_emotion_pct', 'negative_emotion_pct', 'uncertainty_emotion_pct']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.57024 | val 0.79719
  Epoch 013 - train 0.54959 | val 0.74887
  Classification -> best τ=0.570 (val F1=0.1403)
  Directional -> Accuracy: 0.5513, MCC: 0.0000, F1: 0.0000

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 88). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.54209 | val 0.69374
  Epoch 011 - train 0.49425 | val 0.71450
  Classification -> best τ=0.460 (val F1=0.1793)
  Directional -> Accuracy: 0.5532, MCC: 0.0000, F1: 0.7123

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 88). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.60594 | val 0.83774
  Epoch 011 - train 0.59418 | val 0.89436
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5417, MCC: 0.0000, F1: 0.7027

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.60677 | val 0.71381
  Epoch 011 - train 0.60475 | val 0.75965
  Classification -> best τ=0.500 (val F1=0.0392)
  Directional -> Accuracy: 0.4605, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.55423 | val 0.72665
  Epoch 015 - train 0.46208 | val 0.92134
  Classification -> best τ=0.595 (val F1=0.3036)
  Directional -> Accuracy: 0.7308, MCC: 0.4940, F1: 0.7083

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.50173 | val 1.10145
  Epoch 011 - train 0.49305 | val 1.14589
  Classification -> best τ=0.490 (val F1=0.2371)
  Directional -> Accuracy: 0.4898, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.60647 | val 0.70198
  Epoch 019 - train 0.46437 | val 0.79797
  Classification -> best τ=0.545 (val F1=0.3248)
  Directional -> Accuracy: 0.5000, MCC: -0.0117, F1: 0.4262

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 88). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 88). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.49664 | val 1.44324
  Epoch 011 - train 0.48652 | val 1.61760
  Classification -> best τ=0.545 (val F1=0.2390)
  Directional -> Accuracy: 0.5556, MCC: 0.1469, F1: 0.5652

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.53432 | val 0.78228
  Epoch 011 - train 0.54391 | val 0.82147
  Classification -> best τ=0.535 (val F1=0.1409)
  Directional -> Accuracy: 0.6429, MCC: 0.1991, F1: 0.1176

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 88). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 88). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.53764 | val 0.89277
  Epoch 013 - train 0.51534 | val 0.73427
  Classification -> best τ=0.445 (val F1=0.1473)
  Directional -> Accuracy: 0.4366, MCC: -0.0689, F1: 0.5349

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.57111 | val 0.86852
  Epoch 012 - train 0.49799 | val 0.77948
  Classification -> best τ=0.480 (val F1=0.2248)
  Directional -> Accuracy: 0.4706, MCC: -0.0513, F1: 0.4906

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.57212 | val 1.19377
  Epoch 011 - train 0.57937 | val 1.33720
  Classification -> best τ=0.535 (val F1=0.1741)
  Directional -> Accuracy: 0.5763, MCC: 0.1848, F1: 0.4444

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.50728 | val 0.74481
  Epoch 020 - train 0.39689 | val 1.53987
  Epoch 023 - train 0.32286 | val 0.95766
  Classification -> best τ=0.790 (val F1=0.3153)
  Directional -> Accuracy: 0.5000, MCC: -0.0259, F1: 0.3889

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 88). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.54121 | val 1.47822
  Epoch 014 - train 0.51643 | val 1.53578
  Classification -> best τ=0.500 (val F1=0.2889)
  Directional -> Accuracy: 0.5645, MCC: 0.1925, F1: 0.6824

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.50859 | val 0.86155
  Epoch 011 - train 0.46876 | val 0.95874
  Classification -> best τ=0.510 (val F1=0.0086)
  Directional -> Accuracy: 0.4906, MCC: -0.1871, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.54842 | val 0.98313
  Epoch 011 - train 0.54476 | val 0.97332
  Classification -> best τ=0.565 (val F1=0.2699)
  Directional -> Accuracy: 0.5352, MCC: 0.1168, F1: 0.4211

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.53594 | val 0.89151
  Epoch 011 - train 0.52971 | val 1.04622
  Classification -> best τ=0.555 (val F1=0.1753)
  Directional -> Accuracy: 0.3833, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.57551 | val 1.64848
  Epoch 011 - train 0.53993 | val 1.80062
  Classification -> best τ=0.430 (val F1=0.0858)
  Directional -> Accuracy: 0.5455, MCC: 0.0385, F1: 0.6316

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.51925 | val 1.10910
  Epoch 011 - train 0.51603 | val 1.25390
  Classification -> best τ=0.490 (val F1=0.2264)
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 88). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.55376 | val 0.73336
  Epoch 015 - train 0.52438 | val 0.74428
  Classification -> best τ=0.510 (val F1=0.3236)
  Directional -> Accuracy: 0.4605, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.54607 | val 0.80375
  Epoch 011 - train 0.54328 | val 0.83993
  Classification -> best τ=0.530 (val F1=0.1293)
  Directional -> Accuracy: 0.5102, MCC: 0.2521, F1: 0.4000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 88). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 88). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 88). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.57153 | val 1.01329
  Epoch 011 - train 0.55261 | val 1.12217
  Classification -> best τ=0.510 (val F1=0.2070)
  Directional -> Accuracy: 0.6269, MCC: 0.2602, F1: 0.6753

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.52307 | val 0.71998
  Epoch 011 - train 0.50582 | val 0.70668
  Classification -> best τ=0.540 (val F1=0.2559)
  Directional -> Accuracy: 0.6102, MCC: 0.2494, F1: 0.6102

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.56847 | val 0.73236
  Epoch 011 - train 0.57089 | val 0.88253
  Classification -> best τ=0.515 (val F1=0.1890)
  Directional -> Accuracy: 0.5821, MCC: 0.1764, F1: 0.6111

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.53154 | val 0.80548
  Epoch 015 - train 0.45271 | val 1.08780
  Classification -> best τ=0.490 (val F1=0.4409)
  Directional -> Accuracy: 0.4737, MCC: -0.0255, F1: 0.4444

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.48349 | val 0.77032
  Epoch 011 - train 0.50869 | val 0.76997
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4167, MCC: 0.0000, F1: 0.5882

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.52383 | val 0.68193
  Epoch 020 - train 0.34610 | val 0.74139
  Epoch 024 - train 0.26299 | val 1.20535
  Classification -> best τ=0.620 (val F1=0.4442)
  Directional -> Accuracy: 0.5455, MCC: 0.0760, F1: 0.6000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.53706 | val 1.10370
  Epoch 011 - train 0.52739 | val 1.25203
  Classification -> best τ=0.440 (val F1=0.0995)
  Directional -> Accuracy: 0.5690, MCC: 0.1637, F1: 0.5455

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.49480 | val 0.73274
  Epoch 014 - train 0.48349 | val 1.57713
  Classification -> best τ=0.535 (val F1=0.3077)
  Directional -> Accuracy: 0.5814, MCC: 0.1533, F1: 0.6897

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.57205 | val 1.29845
  Epoch 011 - train 0.55723 | val 1.32241
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5111, MCC: 0.0000, F1: 0.6765

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.59281 | val 0.76031
  Epoch 011 - train 0.57525 | val 0.76605
  Classification -> best τ=0.500 (val F1=0.1250)
  Directional -> Accuracy: 0.5111, MCC: 0.0513, F1: 0.4211

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.54177 | val 0.73872
  Epoch 014 - train 0.48557 | val 0.79216
  Classification -> best τ=0.475 (val F1=0.2787)
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.53614 | val 1.21678
  Epoch 014 - train 0.49045 | val 1.46588
  Classification -> best τ=0.500 (val F1=0.3677)
  Directional -> Accuracy: 0.5541, MCC: 0.1420, F1: 0.5352

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 88). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.50111 | val 0.84566
  Epoch 011 - train 0.48334 | val 0.90171
  Classification -> best τ=0.475 (val F1=0.1724)
  Directional -> Accuracy: 0.5128, MCC: 0.0669, F1: 0.6415

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.53196 | val 0.82805
  Epoch 011 - train 0.53848 | val 0.81920
  Classification -> best τ=0.520 (val F1=0.0262)
  Directional -> Accuracy: 0.4667, MCC: 0.0000, F1: 0.6364

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.56913 | val 0.77125
  Epoch 011 - train 0.55290 | val 0.79325
  Classification -> best τ=0.455 (val F1=0.2847)
  Directional -> Accuracy: 0.4853, MCC: 0.1303, F1: 0.2553

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.50451 | val 0.68764
  Epoch 019 - train 0.38500 | val 0.82710
  Classification -> best τ=0.495 (val F1=0.3820)
  Directional -> Accuracy: 0.6818, MCC: 0.3698, F1: 0.6500

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.54440 | val 0.82002
  Epoch 011 - train 0.54123 | val 0.83664
  Classification -> best τ=0.450 (val F1=0.1687)
  Directional -> Accuracy: 0.4655, MCC: -0.0316, F1: 0.5867

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.47788 | val 0.87893
  Epoch 011 - train 0.48420 | val 0.87519
  Classification -> best τ=0.475 (val F1=0.2233)
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 88). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 88). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 88). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 88). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.58844 | val 0.79873
  Epoch 011 - train 0.54861 | val 0.76901
  Classification -> best τ=0.490 (val F1=0.2582)
  Directional -> Accuracy: 0.3500, MCC: 0.0000, F1: 0.5185

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 88). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.54360 | val 0.76816
  Epoch 011 - train 0.52586 | val 0.78688
  Classification -> best τ=0.415 (val F1=0.2548)
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.7000

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 88). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 88). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.55974 | val 1.20321
  Epoch 012 - train 0.49668 | val 1.36405
  Classification -> best τ=0.445 (val F1=0.2725)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 88). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 88). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 88). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.54155 | val 0.72573
  Epoch 011 - train 0.54622 | val 0.73570
  Classification -> best τ=0.520 (val F1=0.3086)
  Directional -> Accuracy: 0.6042, MCC: 0.2344, F1: 0.6780

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.51427 | val 0.91698
  Epoch 011 - train 0.52551 | val 0.98540
  Classification -> best τ=0.505 (val F1=0.2774)
  Directional -> Accuracy: 0.4444, MCC: 0.0000, F1: 0.0000

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.56890 | val 0.89513
  Epoch 011 - train 0.53579 | val 0.88892
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.3659, MCC: 0.0000, F1: 0.5357

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.57109 | val 1.19335
  Epoch 011 - train 0.55084 | val 1.31084
  Classification -> best τ=0.420 (val F1=0.1464)
  Directional -> Accuracy: 0.4912, MCC: 0.0846, F1: 0.2162

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.57610 | val 1.24172
  Epoch 011 - train 0.54957 | val 1.36382
  Classification -> best τ=0.565 (val F1=0.4144)
  Directional -> Accuracy: 0.4828, MCC: 0.0000, F1: 0.6512

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.57900 | val 0.91896
  Epoch 013 - train 0.50598 | val 1.06726
  Classification -> best τ=0.490 (val F1=0.2782)
  Directional -> Accuracy: 0.5091, MCC: -0.0338, F1: 0.6494

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.50159 | val 0.88155
  Epoch 012 - train 0.48814 | val 1.05085
  Classification -> best τ=0.565 (val F1=0.1724)
  Directional -> Accuracy: 0.5088, MCC: 0.1313, F1: 0.0667

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...

[I 2026-02-22 09:06:17,078] Trial 39 finished with value: 0.209196833474758 and parameters: {'feature_set': 'unified_emotion', 'model_type': 'BiGRU', 'sequence_length': 12, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 64, 'num_layers': 2, 'inter_rnn_drop': 0.4, 'dropout': 0.0, 'batch_size': 64, 'learning_rate': 0.003158082847961767, 'weight_decay': 6.312200959609294e-07, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 1.4707890080592136, 'early_stopping_min_delta': 0.005659084322414064}. Best is trial 22 with value: 0.2833350641483003.

  Epoch 010 - train 0.55216 | val 0.83098
  Epoch 011 - train 0.54036 | val 0.82634
  Classification -> best τ=0.540 (val F1=0.1305)
  Directional -> Accuracy: 0.4194, MCC: -0.1590, F1: 0.4375

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.209196833474758
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 6
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d', 'sentiment', 'emotion_anger', 'emotion_disgust', 'emotion_fear', 'emotion_joy', 'emotion_neutral', 'emotion_sadness', 'emotion_surprize', 'emotion_anger_pct', 'emotion_disgust_pct', 'emotion_fear_pct', 'emotion_joy_pct', 'emotion_neutral_pct', 'emotion_sadness_pct', 'emotion_surprize_pct', 'positive_emotion', 'negative_emotion', 'uncertainty_emotion', 'positive_emotion_pct', 'negative_emotion_pct', 'uncertainty_emotion_pct', 'stance_label', 'stance_score', 'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down', 'finbert_neutral']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.41418 | val 1.03900
  Epoch 020 - train 0.16093 | val 2.06323
  Classification -> best τ=0.460 (val F1=0.2352)
  Directional -> Accuracy: 0.4557, MCC: 0.1010, F1: 0.6195

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 82). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.38625 | val 0.76017
  Epoch 020 - train 0.16720 | val 1.04471
  Classification -> best τ=0.470 (val F1=0.2277)
  Directional -> Accuracy: 0.5625, MCC: 0.0000, F1: 0.7200

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 82). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.44165 | val 1.00685
  Epoch 020 - train 0.17413 | val 2.08552
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.44214 | val 0.98031
  Epoch 020 - train 0.21166 | val 2.00467
  Classification -> best τ=0.490 (val F1=0.1654)
  Directional -> Accuracy: 0.5455, MCC: 0.0000, F1: 0.7059

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.36522 | val 0.72796
  Epoch 020 - train 0.12042 | val 1.34549
  Classification -> best τ=0.475 (val F1=0.4489)
  Directional -> Accuracy: 0.6604, MCC: 0.3224, F1: 0.6667

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.47178 | val 0.72991
  Epoch 020 - train 0.20351 | val 1.08184
  Classification -> best τ=0.500 (val F1=0.0605)
  Directional -> Accuracy: 0.5366, MCC: 0.0872, F1: 0.5581

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.40693 | val 0.81589
  Epoch 020 - train 0.14697 | val 1.03004
  Classification -> best τ=0.515 (val F1=0.1690)
  Directional -> Accuracy: 0.5634, MCC: 0.0427, F1: 0.3404

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 82). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 82). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.47232 | val 1.04824
  Epoch 020 - train 0.27932 | val 1.34616
  Classification -> best τ=0.535 (val F1=0.1754)
  Directional -> Accuracy: 0.4043, MCC: 0.0000, F1: 0.5758

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.44727 | val 0.97155
  Epoch 020 - train 0.18193 | val 1.16152
  Classification -> best τ=0.510 (val F1=0.1533)
  Directional -> Accuracy: 0.3721, MCC: -0.1588, F1: 0.4906

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 82). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 82). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.36814 | val 0.73155
  Epoch 020 - train 0.11739 | val 1.46446
  Classification -> best τ=0.480 (val F1=0.2466)
  Directional -> Accuracy: 0.4444, MCC: -0.1083, F1: 0.4118

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.38184 | val 0.91112
  Epoch 020 - train 0.14684 | val 1.51363
  Classification -> best τ=0.535 (val F1=0.1701)
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.42361 | val 0.87009
  Epoch 020 - train 0.16691 | val 2.22916
  Classification -> best τ=0.340 (val F1=0.2053)
  Directional -> Accuracy: 0.5167, MCC: 0.1302, F1: 0.6742

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.39129 | val 1.12733
  Epoch 020 - train 0.15672 | val 1.45593
  Classification -> best τ=0.460 (val F1=0.0454)
  Directional -> Accuracy: 0.4667, MCC: 0.0000, F1: 0.6364

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 82). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.44185 | val 0.72077
  Epoch 020 - train 0.21108 | val 0.84901
  Classification -> best τ=0.550 (val F1=0.3682)
  Directional -> Accuracy: 0.5079, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.38591 | val 1.33736
  Epoch 020 - train 0.16235 | val 2.35472
  Classification -> best τ=0.530 (val F1=0.1738)
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.40313 | val 0.80899
  Epoch 020 - train 0.17315 | val 1.34515
  Classification -> best τ=0.420 (val F1=0.1944)
  Directional -> Accuracy: 0.5694, MCC: 0.1838, F1: 0.7156

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.38779 | val 1.33512
  Epoch 020 - train 0.15275 | val 3.09675
  Classification -> best τ=0.570 (val F1=0.1162)
  Directional -> Accuracy: 0.3934, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.41767 | val 0.90520
  Epoch 020 - train 0.17839 | val 1.36769
  Classification -> best τ=0.415 (val F1=0.1708)
  Directional -> Accuracy: 0.5897, MCC: -0.0926, F1: 0.7419

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.40917 | val 0.71969
  Epoch 020 - train 0.15677 | val 1.13881
  Classification -> best τ=0.530 (val F1=0.2279)
  Directional -> Accuracy: 0.4179, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 82). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.41335 | val 0.77233
  Epoch 020 - train 0.19868 | val 1.97460
  Classification -> best τ=0.365 (val F1=0.2254)
  Directional -> Accuracy: 0.4805, MCC: -0.0829, F1: 0.5833

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.35073 | val 0.74954
  Epoch 020 - train 0.11504 | val 1.27764
  Classification -> best τ=0.560 (val F1=0.2955)
  Directional -> Accuracy: 0.3800, MCC: -0.0913, F1: 0.1622

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 82). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 82). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 82). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.42680 | val 0.78242
  Epoch 020 - train 0.20166 | val 1.19420
  Classification -> best τ=0.455 (val F1=0.2500)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.43085 | val 1.33023
  Epoch 020 - train 0.18113 | val 3.04352
  Classification -> best τ=0.545 (val F1=0.1834)
  Directional -> Accuracy: 0.5500, MCC: 0.2873, F1: 0.4000

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.37186 | val 1.16900
  Epoch 020 - train 0.13969 | val 1.07890
  Classification -> best τ=0.430 (val F1=0.2160)
  Directional -> Accuracy: 0.5294, MCC: 0.0849, F1: 0.6190

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.42391 | val 0.72366
  Epoch 020 - train 0.19019 | val 1.56964
  Classification -> best τ=0.575 (val F1=0.3621)
  Directional -> Accuracy: 0.5690, MCC: 0.2157, F1: 0.4681

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.37281 | val 0.69123
  Epoch 020 - train 0.15035 | val 0.72827
  Classification -> best τ=0.655 (val F1=0.3430)
  Directional -> Accuracy: 0.4490, MCC: -0.1319, F1: 0.3415

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.36048 | val 0.74213
  Epoch 020 - train 0.14306 | val 1.16634
  Classification -> best τ=0.520 (val F1=0.2357)
  Directional -> Accuracy: 0.6000, MCC: 0.1372, F1: 0.6897

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.40556 | val 1.12139
  Epoch 020 - train 0.19709 | val 1.70669
  Classification -> best τ=0.500 (val F1=0.0416)
  Directional -> Accuracy: 0.4407, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.47153 | val 0.69506
  Epoch 020 - train 0.25262 | val 0.74464
  Classification -> best τ=0.520 (val F1=0.4973)
  Directional -> Accuracy: 0.4773, MCC: -0.0415, F1: 0.4651

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.38651 | val 1.03910
  Epoch 020 - train 0.16307 | val 2.45493
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.47968 | val 0.75473
  Epoch 020 - train 0.25396 | val 1.23941
  Classification -> best τ=0.475 (val F1=0.2059)
  Directional -> Accuracy: 0.5000, MCC: -0.0475, F1: 0.6102

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.35506 | val 0.82345
  Epoch 020 - train 0.13267 | val 1.12163
  Classification -> best τ=0.430 (val F1=0.3513)
  Directional -> Accuracy: 0.5192, MCC: 0.0000, F1: 0.6835

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.40777 | val 0.81640
  Epoch 020 - train 0.15867 | val 1.28374
  Classification -> best τ=0.665 (val F1=0.2513)
  Directional -> Accuracy: 0.4400, MCC: 0.0000, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 82). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.46549 | val 0.67316
  Epoch 020 - train 0.21632 | val 0.82916
  Classification -> best τ=0.590 (val F1=0.4139)
  Directional -> Accuracy: 0.5122, MCC: 0.1543, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.37646 | val 0.93069
  Epoch 020 - train 0.11889 | val 1.51578
  Classification -> best τ=0.485 (val F1=0.1954)
  Directional -> Accuracy: 0.4565, MCC: 0.0000, F1: 0.6269

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.42099 | val 0.90519
  Epoch 020 - train 0.19035 | val 1.00295
  Classification -> best τ=0.450 (val F1=0.2171)
  Directional -> Accuracy: 0.4348, MCC: 0.1033, F1: 0.0488

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.39436 | val 0.67050
  Epoch 020 - train 0.15054 | val 0.97906
  Classification -> best τ=0.295 (val F1=0.4609)
  Directional -> Accuracy: 0.6889, MCC: 0.3802, F1: 0.6818

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.34910 | val 0.99388
  Epoch 020 - train 0.11987 | val 1.16300
  Classification -> best τ=0.485 (val F1=0.1985)
  Directional -> Accuracy: 0.4746, MCC: -0.0365, F1: 0.5373

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.36916 | val 0.90407
  Epoch 020 - train 0.13286 | val 1.51557
  Classification -> best τ=0.570 (val F1=0.1814)
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 82). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 82). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 82). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 82). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.43143 | val 0.76765
  Epoch 020 - train 0.16278 | val 1.10358
  Classification -> best τ=0.460 (val F1=0.1517)
  Directional -> Accuracy: 0.5238, MCC: -0.1581, F1: 0.1667

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 82). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.48220 | val 0.81095
  Epoch 020 - train 0.29008 | val 1.09230
  Classification -> best τ=0.520 (val F1=0.1762)
  Directional -> Accuracy: 0.5122, MCC: 0.0055, F1: 0.6667

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 82). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 82). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.40530 | val 1.52838
  Epoch 020 - train 0.14044 | val 2.96684
  Classification -> best τ=0.525 (val F1=0.2082)
  Directional -> Accuracy: 0.4935, MCC: -0.0050, F1: 0.2041

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 82). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 82). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.46508 | val 1.05337
  Epoch 020 - train 0.24802 | val 1.90029
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4898, MCC: 0.0000, F1: 0.6575

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.42450 | val 1.13390
  Epoch 020 - train 0.24068 | val 1.83589
  Classification -> best τ=0.565 (val F1=0.3043)
  Directional -> Accuracy: 0.4468, MCC: -0.0324, F1: 0.3158

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.41004 | val 0.92444
  Epoch 020 - train 0.20578 | val 1.48709
  Classification -> best τ=0.620 (val F1=0.1425)
  Directional -> Accuracy: 0.5952, MCC: 0.2777, F1: 0.5854

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.40036 | val 0.68152
  Epoch 020 - train 0.12993 | val 1.33678
  Classification -> best τ=0.395 (val F1=0.3167)
  Directional -> Accuracy: 0.4655, MCC: -0.0929, F1: 0.5373

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.37889 | val 1.00198
  Epoch 020 - train 0.13244 | val 1.52373
  Classification -> best τ=0.500 (val F1=0.3570)
  Directional -> Accuracy: 0.5424, MCC: 0.1342, F1: 0.6582

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.44831 | val 0.76759
  Epoch 020 - train 0.19592 | val 1.04807
  Classification -> best τ=0.495 (val F1=0.1057)
  Directional -> Accuracy: 0.5536, MCC: 0.0812, F1: 0.6835

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.41841 | val 1.07496
  Epoch 020 - train 0.15673 | val 1.55903
  Classification -> best τ=0.540 (val F1=0.3035)
  Directional -> Accuracy: 0.5172, MCC: 0.0000, F1: 0.6818

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.42826 | val 0.65430

[I 2026-02-22 09:07:13,915] Trial 40 finished with value: 0.22221421151876433 and parameters: {'feature_set': 'sector_all_nlp', 'model_type': 'BiGRU', 'sequence_length': 6, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 32, 'num_layers': 2, 'inter_rnn_drop': 0.0, 'dropout': 0.4, 'batch_size': 32, 'learning_rate': 0.0008064310164231415, 'weight_decay': 2.752950889195691e-05, 'lr_patience': 7, 'lr_factor': 0.8, 'early_stopping_patience': 20, 'max_epochs': 20, 'huber_delta': 1.0275102451546563, 'early_stopping_min_delta': 0.004285884428633968}. Best is trial 22 with value: 0.2833350641483003.

  Epoch 020 - train 0.19821 | val 0.65734
  Classification -> best τ=0.670 (val F1=0.3651)
  Directional -> Accuracy: 0.5238, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.22221421151876433
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down', 'finbert_neutral']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.62925 | val 0.92980
  Epoch 011 - train 0.60375 | val 1.05754
  Classification -> best τ=0.435 (val F1=0.1989)
  Directional -> Accuracy: 0.5325, MCC: 0.0398, F1: 0.4194

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.52247 | val 1.08180
  Epoch 012 - train 0.42621 | val 1.34389
  Classification -> best τ=0.415 (val F1=0.1812)
  Directional -> Accuracy: 0.6522, MCC: 0.2779, F1: 0.7333

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.57024 | val 0.74995
  Epoch 014 - train 0.42570 | val 0.90998
  Classification -> best τ=0.580 (val F1=0.3844)
  Directional -> Accuracy: 0.4681, MCC: -0.0195, F1: 0.1379

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.61412 | val 2.28760
  Epoch 014 - train 0.51917 | val 2.22011
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.47772 | val 2.52738
  Epoch 011 - train 0.44129 | val 2.67599
  Classification -> best τ=0.460 (val F1=0.4836)
  Directional -> Accuracy: 0.6863, MCC: 0.3808, F1: 0.6800

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.57426 | val 0.82965
  Epoch 011 - train 0.55354 | val 0.97670
  Classification -> best τ=0.525 (val F1=0.3430)
  Directional -> Accuracy: 0.4894, MCC: -0.0045, F1: 0.6471

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.52268 | val 0.86928
  Epoch 011 - train 0.53336 | val 0.91629
  Classification -> best τ=0.490 (val F1=0.2198)
  Directional -> Accuracy: 0.5217, MCC: 0.0819, F1: 0.5217

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.43268 | val 4.06280
  Epoch 011 - train 0.42413 | val 3.03229
  Classification -> best τ=0.435 (val F1=0.1214)
  Directional -> Accuracy: 0.4318, MCC: 0.1269, F1: 0.5902

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.47179 | val 1.10212
  Epoch 013 - train 0.44676 | val 1.27380
  Classification -> best τ=0.520 (val F1=0.2788)
  Directional -> Accuracy: 0.5306, MCC: -0.1303, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.50585 | val 1.10953
  Epoch 011 - train 0.48938 | val 0.87878
  Classification -> best τ=0.375 (val F1=0.0831)
  Directional -> Accuracy: 0.5571, MCC: 0.0630, F1: 0.3922

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.49180 | val 1.01053
  Epoch 014 - train 0.36168 | val 1.19092
  Classification -> best τ=0.680 (val F1=0.1750)
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.59074 | val 1.04866
  Epoch 012 - train 0.50367 | val 1.21542
  Classification -> best τ=0.275 (val F1=0.1806)
  Directional -> Accuracy: 0.5517, MCC: 0.1136, F1: 0.6286

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.46105 | val 1.11801
  Epoch 014 - train 0.26347 | val 1.94310
  Classification -> best τ=0.375 (val F1=0.0584)
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.53898 | val 0.81392
  Epoch 015 - train 0.44822 | val 0.85979
  Classification -> best τ=0.680 (val F1=0.3318)
  Directional -> Accuracy: 0.5410, MCC: 0.0952, F1: 0.4400

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.58951 | val 0.68731
  Epoch 018 - train 0.40746 | val 0.76686
  Classification -> best τ=0.490 (val F1=0.2693)
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.61891 | val 0.72809
  Epoch 018 - train 0.36988 | val 1.29104
  Classification -> best τ=0.210 (val F1=0.3770)
  Directional -> Accuracy: 0.6571, MCC: 0.3131, F1: 0.7333

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.65808 | val 0.80011
  Epoch 013 - train 0.55910 | val 0.92789
  Classification -> best τ=0.655 (val F1=0.1857)
  Directional -> Accuracy: 0.3729, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.59952 | val 0.95937
  Epoch 012 - train 0.57561 | val 1.46118
  Classification -> best τ=0.475 (val F1=0.1734)
  Directional -> Accuracy: 0.6184, MCC: 0.1430, F1: 0.7603

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.58373 | val 0.77327
  Epoch 015 - train 0.48422 | val 0.83381
  Classification -> best τ=0.475 (val F1=0.2858)
  Directional -> Accuracy: 0.5077, MCC: 0.1030, F1: 0.4286

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.49585 | val 1.11375
  Epoch 011 - train 0.42142 | val 1.25063
  Classification -> best τ=0.625 (val F1=0.2242)
  Directional -> Accuracy: 0.4400, MCC: -0.1193, F1: 0.4615

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.54964 | val 0.96604
  Epoch 012 - train 0.50071 | val 0.75598
  Classification -> best τ=0.470 (val F1=0.2174)
  Directional -> Accuracy: 0.7083, MCC: 0.3892, F1: 0.8108

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.58608 | val 1.05480
  Epoch 011 - train 0.55706 | val 0.95897
  Classification -> best τ=0.425 (val F1=0.2565)
  Directional -> Accuracy: 0.5455, MCC: 0.1476, F1: 0.6739

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.61416 | val 0.83939
  Epoch 013 - train 0.52536 | val 1.64736
  Classification -> best τ=0.415 (val F1=0.2817)
  Directional -> Accuracy: 0.5345, MCC: 0.1323, F1: 0.4706

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.59637 | val 1.02050
  Epoch 011 - train 0.56444 | val 1.42339
  Classification -> best τ=0.525 (val F1=0.1878)
  Directional -> Accuracy: 0.5909, MCC: 0.2304, F1: 0.2703

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.52475 | val 0.84491
  Epoch 016 - train 0.38581 | val 0.84733
  Classification -> best τ=0.605 (val F1=0.3951)
  Directional -> Accuracy: 0.5000, MCC: 0.0996, F1: 0.3000

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.31776 | val 1.67896
  Epoch 011 - train 0.30632 | val 1.68635
  Classification -> best τ=0.540 (val F1=0.2774)
  Directional -> Accuracy: 0.5000, MCC: 0.2317, F1: 0.6349

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.61198 | val 0.72514
  Epoch 019 - train 0.50913 | val 1.01818
  Classification -> best τ=0.625 (val F1=0.2717)
  Directional -> Accuracy: 0.4186, MCC: 0.0000, F1: 0.0000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.57797 | val 1.22034
  Epoch 012 - train 0.48852 | val 1.43467
  Classification -> best τ=0.400 (val F1=0.1644)
  Directional -> Accuracy: 0.5789, MCC: 0.1312, F1: 0.6471

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.49782 | val 1.19624
  Epoch 012 - train 0.38698 | val 1.44806
  Classification -> best τ=0.550 (val F1=0.3203)
  Directional -> Accuracy: 0.5610, MCC: 0.1701, F1: 0.7097

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.46579 | val 2.86503
  Epoch 012 - train 0.47144 | val 3.48516
  Classification -> best τ=0.810 (val F1=0.2683)
  Directional -> Accuracy: 0.5116, MCC: 0.0162, F1: 0.4000

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.66172 | val 0.68824
  Epoch 011 - train 0.58542 | val 0.91714
  Classification -> best τ=0.545 (val F1=0.2533)
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.49026 | val 1.29283
  Epoch 011 - train 0.42139 | val 1.42585
  Classification -> best τ=0.465 (val F1=0.3304)
  Directional -> Accuracy: 0.3800, MCC: -0.2288, F1: 0.2439

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.59224 | val 0.75133
  Epoch 014 - train 0.51513 | val 0.84249
  Classification -> best τ=0.385 (val F1=0.3434)
  Directional -> Accuracy: 0.5342, MCC: 0.1602, F1: 0.4138

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.44662 | val 0.84617
  Epoch 012 - train 0.40432 | val 0.95031
  Classification -> best τ=0.455 (val F1=0.3162)
  Directional -> Accuracy: 0.5263, MCC: 0.1644, F1: 0.6786

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.51297 | val 1.02900
  Epoch 011 - train 0.45464 | val 1.11945
  Classification -> best τ=0.425 (val F1=0.2757)
  Directional -> Accuracy: 0.5455, MCC: 0.1988, F1: 0.6667

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.45979 | val 1.10061
  Epoch 011 - train 0.45246 | val 1.25381
  Classification -> best τ=0.710 (val F1=0.1187)
  Directional -> Accuracy: 0.4328, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.57237 | val 0.65976
  Epoch 016 - train 0.32430 | val 1.95903
  Classification -> best τ=0.545 (val F1=0.4714)
  Directional -> Accuracy: 0.6047, MCC: 0.2379, F1: 0.5143

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.46376 | val 0.81901
  Epoch 012 - train 0.35361 | val 1.25380
  Classification -> best τ=0.410 (val F1=0.2343)
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.50687 | val 1.48890
  Epoch 011 - train 0.43493 | val 1.55915
  Classification -> best τ=0.455 (val F1=0.2718)
  Directional -> Accuracy: 0.6170, MCC: 0.0000, F1: 0.7632

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.45021 | val 2.08182
  Epoch 012 - train 0.32856 | val 2.11645
  Classification -> best τ=0.525 (val F1=0.3300)
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.32327 | val 2.01681
  Epoch 011 - train 0.34179 | val 2.12446
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.59085 | val 0.82933
  Epoch 012 - train 0.52908 | val 1.07293
  Classification -> best τ=0.535 (val F1=0.2892)
  Directional -> Accuracy: 0.5200, MCC: 0.0378, F1: 0.4000

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.51266 | val 0.73029
  Epoch 011 - train 0.51109 | val 0.72466
  Classification -> best τ=0.425 (val F1=0.3471)
  Directional -> Accuracy: 0.5745, MCC: 0.2144, F1: 0.6970

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.41811 | val 2.14254
  Epoch 011 - train 0.33694 | val 2.46130
  Classification -> best τ=0.460 (val F1=0.3103)
  Directional -> Accuracy: 0.5909, MCC: 0.1749, F1: 0.7353

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.50633 | val 1.34457
  Epoch 012 - train 0.42766 | val 1.53600
  Classification -> best τ=0.595 (val F1=0.1543)
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.55395 | val 0.93111
  Epoch 012 - train 0.49353 | val 1.52699
  Classification -> best τ=0.580 (val F1=0.2465)
  Directional -> Accuracy: 0.4464, MCC: -0.2915, F1: 0.6173

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.59779 | val 0.77708
  Epoch 011 - train 0.54608 | val 0.93376
  Classification -> best τ=0.400 (val F1=0.1685)
  Directional -> Accuracy: 0.4737, MCC: -0.0101, F1: 0.6341

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.59863 | val 1.55884
  Epoch 011 - train 0.59515 | val 1.72303
  Classification -> best τ=0.325 (val F1=0.2024)
  Directional -> Accuracy: 0.5556, MCC: 0.2035, F1: 0.7000

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.55002 | val 1.39426
  Epoch 014 - train 0.49032 | val 1.00913
  Classification -> best τ=0.405 (val F1=0.1667)
  Directional -> Accuracy: 0.5179, MCC: 0.0000, F1: 0.6824

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.60385 | val 0.68255

[I 2026-02-22 09:09:36,640] Trial 41 finished with value: 0.24700049927633563 and parameters: {'feature_set': 'finbert', 'model_type': 'BiGRU', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.4, 'dropout': 0.0, 'batch_size': 32, 'learning_rate': 0.006193537297609399, 'weight_decay': 1.3036503684735334e-05, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 0.789699011003198, 'early_stopping_min_delta': 0.009421806666631494}. Best is trial 22 with value: 0.2833350641483003.

  Epoch 014 - train 0.46930 | val 0.70417
  Classification -> best τ=0.410 (val F1=0.3240)
  Directional -> Accuracy: 0.5738, MCC: 0.1430, F1: 0.5357

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.24700049927633563
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down', 'finbert_neutral']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.59179 | val 0.73738
  Epoch 017 - train 0.54165 | val 0.88719
  Classification -> best τ=0.630 (val F1=0.2453)
  Directional -> Accuracy: 0.4935, MCC: -0.2137, F1: 0.0000

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.53627 | val 1.22089
  Epoch 012 - train 0.53525 | val 1.20639
  Classification -> best τ=0.395 (val F1=0.1433)
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.7222

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.51809 | val 0.83908
  Epoch 012 - train 0.46432 | val 1.01909
  Classification -> best τ=0.665 (val F1=0.3477)
  Directional -> Accuracy: 0.4681, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.64598 | val 1.07146
  Epoch 018 - train 0.54884 | val 1.37653
  Classification -> best τ=0.275 (val F1=0.1210)
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.46228 | val 1.11282
  Epoch 011 - train 0.39693 | val 1.73980
  Classification -> best τ=0.640 (val F1=0.4051)
  Directional -> Accuracy: 0.5098, MCC: 0.1004, F1: 0.2424

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.56612 | val 0.81424
  Epoch 013 - train 0.43630 | val 1.08988
  Classification -> best τ=0.470 (val F1=0.3892)
  Directional -> Accuracy: 0.6170, MCC: 0.2375, F1: 0.5500

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.54195 | val 1.04263
  Epoch 012 - train 0.52940 | val 1.14194
  Classification -> best τ=0.315 (val F1=0.1334)
  Directional -> Accuracy: 0.4058, MCC: -0.0592, F1: 0.5495

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.52429 | val 2.87858
  Epoch 012 - train 0.39210 | val 2.32648
  Classification -> best τ=0.530 (val F1=0.3295)
  Directional -> Accuracy: 0.5909, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.55571 | val 0.98177
  Epoch 013 - train 0.40974 | val 1.15031
  Classification -> best τ=0.430 (val F1=0.2881)
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.53943 | val 1.02511
  Epoch 011 - train 0.47468 | val 0.99473
  Classification -> best τ=0.530 (val F1=0.1998)
  Directional -> Accuracy: 0.6143, MCC: 0.2082, F1: 0.2286

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.49510 | val 1.55111
  Epoch 011 - train 0.48307 | val 1.56340
  Classification -> best τ=0.325 (val F1=0.0754)
  Directional -> Accuracy: 0.4400, MCC: -0.0902, F1: 0.5758

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.56858 | val 1.06938
  Epoch 011 - train 0.52048 | val 1.05371
  Classification -> best τ=0.435 (val F1=0.1469)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.40699 | val 0.88908
  Epoch 011 - train 0.37114 | val 1.07931
  Classification -> best τ=0.315 (val F1=0.2004)
  Directional -> Accuracy: 0.4651, MCC: 0.1373, F1: 0.6230

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.60189 | val 0.68804
  Epoch 013 - train 0.53973 | val 0.64231
  Classification -> best τ=0.315 (val F1=0.3268)
  Directional -> Accuracy: 0.5574, MCC: 0.1154, F1: 0.6197

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.59404 | val 1.13355
  Epoch 013 - train 0.54033 | val 0.76611
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4615, MCC: 0.0000, F1: 0.6316

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.58080 | val 0.77978
  Epoch 018 - train 0.45981 | val 0.99326
  Classification -> best τ=0.710 (val F1=0.2734)
  Directional -> Accuracy: 0.5000, MCC: 0.0256, F1: 0.4444

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.58335 | val 1.04348
  Epoch 012 - train 0.51945 | val 1.03063
  Classification -> best τ=0.525 (val F1=0.1302)
  Directional -> Accuracy: 0.3729, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.61729 | val 0.90207
  Epoch 013 - train 0.54993 | val 0.86185
  Classification -> best τ=0.365 (val F1=0.2396)
  Directional -> Accuracy: 0.5526, MCC: 0.1192, F1: 0.5854

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.50520 | val 0.68939
  Epoch 011 - train 0.45941 | val 0.69258
  Classification -> best τ=0.550 (val F1=0.2249)
  Directional -> Accuracy: 0.4154, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.63973 | val 1.25455
  Epoch 013 - train 0.49215 | val 0.99562
  Classification -> best τ=0.530 (val F1=0.2371)
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.63745 | val 0.79182
  Epoch 018 - train 0.41724 | val 0.81929
  Classification -> best τ=0.585 (val F1=0.3030)
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.60878 | val 1.50058
  Epoch 014 - train 0.51467 | val 2.29902
  Classification -> best τ=0.535 (val F1=0.2390)
  Directional -> Accuracy: 0.5606, MCC: 0.1414, F1: 0.6506

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.64710 | val 0.77226
  Epoch 012 - train 0.59573 | val 1.03127
  Classification -> best τ=0.525 (val F1=0.3158)
  Directional -> Accuracy: 0.5172, MCC: 0.0882, F1: 0.4615

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.60445 | val 1.35106
  Epoch 012 - train 0.52810 | val 1.34605
  Classification -> best τ=0.400 (val F1=0.2655)
  Directional -> Accuracy: 0.4697, MCC: -0.0107, F1: 0.6316

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.54346 | val 1.11859
  Epoch 012 - train 0.45329 | val 1.75119
  Classification -> best τ=0.710 (val F1=0.4376)
  Directional -> Accuracy: 0.4643, MCC: 0.1211, F1: 0.0625

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.46409 | val 1.35439
  Epoch 015 - train 0.29803 | val 1.70429
  Classification -> best τ=0.300 (val F1=0.1741)
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.53988 | val 0.84369
  Epoch 013 - train 0.47654 | val 0.96696
  Classification -> best τ=0.635 (val F1=0.1874)
  Directional -> Accuracy: 0.4651, MCC: 0.0696, F1: 0.2581

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.59862 | val 0.94604
  Epoch 012 - train 0.50314 | val 1.26035
  Classification -> best τ=0.660 (val F1=0.1940)
  Directional -> Accuracy: 0.4386, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.52733 | val 1.83140
  Epoch 016 - train 0.42502 | val 1.36528
  Classification -> best τ=0.470 (val F1=0.3974)
  Directional -> Accuracy: 0.6098, MCC: 0.2516, F1: 0.7241

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.55327 | val 2.40144
  Epoch 012 - train 0.43069 | val 3.04073
  Classification -> best τ=0.675 (val F1=0.2683)
  Directional -> Accuracy: 0.5349, MCC: 0.0693, F1: 0.5238

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.56675 | val 0.72109
  Epoch 015 - train 0.42658 | val 1.10715
  Classification -> best τ=0.445 (val F1=0.2533)
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.45124 | val 1.80088
  Epoch 012 - train 0.38265 | val 1.51183
  Classification -> best τ=0.270 (val F1=0.1760)
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.64220 | val 0.86850
  Epoch 016 - train 0.57781 | val 1.43590
  Classification -> best τ=0.235 (val F1=0.3809)
  Directional -> Accuracy: 0.5753, MCC: 0.1768, F1: 0.5634

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.49536 | val 0.96035
  Epoch 011 - train 0.44675 | val 0.98142
  Classification -> best τ=0.415 (val F1=0.3162)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.2963

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.53180 | val 0.77875
  Epoch 012 - train 0.42902 | val 0.78479
  Classification -> best τ=0.760 (val F1=0.3103)
  Directional -> Accuracy: 0.5227, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.59215 | val 1.20582
  Epoch 013 - train 0.48429 | val 1.23298
  Classification -> best τ=0.255 (val F1=0.3687)
  Directional -> Accuracy: 0.5075, MCC: 0.1239, F1: 0.3529

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.54616 | val 2.14661
  Epoch 013 - train 0.40357 | val 1.41549
  Classification -> best τ=0.570 (val F1=0.3780)
  Directional -> Accuracy: 0.6047, MCC: 0.2191, F1: 0.5641

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.53531 | val 1.30906
  Epoch 011 - train 0.50193 | val 1.51143
  Classification -> best τ=0.265 (val F1=0.1851)
  Directional -> Accuracy: 0.5088, MCC: 0.0304, F1: 0.5484

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.57328 | val 0.71854
  Epoch 014 - train 0.35308 | val 1.42724
  Classification -> best τ=0.420 (val F1=0.2606)
  Directional -> Accuracy: 0.6170, MCC: 0.0508, F1: 0.7568

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.48753 | val 0.86415
  Epoch 011 - train 0.45443 | val 1.00516
  Classification -> best τ=0.495 (val F1=0.1477)
  Directional -> Accuracy: 0.3878, MCC: -0.0759, F1: 0.4828

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.38917 | val 1.98404
  Epoch 011 - train 0.41213 | val 1.93626
  Classification -> best τ=0.580 (val F1=0.0134)
  Directional -> Accuracy: 0.5526, MCC: 0.2777, F1: 0.2609

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.61018 | val 0.78186
  Epoch 012 - train 0.58059 | val 1.29546
  Classification -> best τ=0.670 (val F1=0.2833)
  Directional -> Accuracy: 0.4800, MCC: -0.0944, F1: 0.0930

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.52323 | val 0.70242
  Epoch 011 - train 0.49078 | val 0.69074
  Classification -> best τ=0.460 (val F1=0.1808)
  Directional -> Accuracy: 0.5106, MCC: 0.0437, F1: 0.3030

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.45590 | val 1.75045
  Epoch 011 - train 0.42528 | val 2.24793
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5682, MCC: 0.0000, F1: 0.7246

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.50590 | val 1.56990
  Epoch 012 - train 0.38695 | val 0.78513
  Classification -> best τ=0.575 (val F1=0.1890)
  Directional -> Accuracy: 0.4490, MCC: 0.0266, F1: 0.5263

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.58221 | val 0.73078
  Epoch 012 - train 0.54580 | val 1.22423
  Classification -> best τ=0.575 (val F1=0.0829)
  Directional -> Accuracy: 0.4643, MCC: -0.0138, F1: 0.0625

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.55984 | val 1.19785
  Epoch 011 - train 0.52524 | val 1.24349
  Classification -> best τ=0.430 (val F1=0.2554)
  Directional -> Accuracy: 0.5088, MCC: 0.0964, F1: 0.6410

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.57557 | val 1.35506
  Epoch 011 - train 0.53656 | val 1.74154
  Classification -> best τ=0.610 (val F1=0.1626)
  Directional -> Accuracy: 0.5926, MCC: 0.1816, F1: 0.6333

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.53081 | val 1.97218
  Epoch 011 - train 0.49715 | val 1.70253
  Classification -> best τ=0.540 (val F1=0.0442)
  Directional -> Accuracy: 0.5357, MCC: 0.1397, F1: 0.6905

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.61340 | val 0.77279
  Epoch 020 - train 0.48338 | val 1.12668

[I 2026-02-22 09:12:07,977] Trial 42 finished with value: 0.23173174751201198 and parameters: {'feature_set': 'finbert', 'model_type': 'BiGRU', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.4, 'dropout': 0.0, 'batch_size': 32, 'learning_rate': 0.00944139389969994, 'weight_decay': 6.706215612243847e-05, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 0.6359416198525538, 'early_stopping_min_delta': 0.008610917681645226}. Best is trial 22 with value: 0.2833350641483003.

  Epoch 023 - train 0.47862 | val 0.70179
  Classification -> best τ=0.330 (val F1=0.3586)
  Directional -> Accuracy: 0.4426, MCC: -0.1112, F1: 0.4516

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.23173174751201198
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sentiment', 'emotion_anger', 'emotion_disgust', 'emotion_fear', 'emotion_joy', 'emotion_neutral', 'emotion_sadness', 'emotion_surprize', 'emotion_anger_pct', 'emotion_disgust_pct', 'emotion_fear_pct', 'emotion_joy_pct', 'emotion_neutral_pct', 'emotion_sadness_pct', 'emotion_surprize_pct', 'positive_emotion', 'negative_emotion', 'uncertainty_emotion', 'positive_emotion_pct', 'negative_emotion_pct', 'uncertainty_emotion_pct', 'stance_label', 'stance_score', 'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down', 'finbert_neutral']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.44490 | val 0.91400
  Epoch 015 - train 0.27075 | val 1.89463
  Classification -> best τ=0.615 (val F1=0.2627)
  Directional -> Accuracy: 0.5526, MCC: 0.0503, F1: 0.2917

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.31763 | val 1.34970
  Epoch 012 - train 0.25987 | val 1.32363
  Classification -> best τ=0.405 (val F1=0.0340)
  Directional -> Accuracy: 0.6000, MCC: 0.1591, F1: 0.6786

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.29915 | val 1.51716
  Epoch 013 - train 0.15513 | val 1.72398
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5217, MCC: 0.0000, F1: 0.6857

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.45409 | val 1.47434
  Epoch 013 - train 0.24454 | val 1.03078
  Classification -> best τ=0.235 (val F1=0.2771)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.5195

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.27213 | val 1.29854
  Epoch 012 - train 0.19603 | val 1.45298
  Classification -> best τ=0.490 (val F1=0.3641)
  Directional -> Accuracy: 0.7000, MCC: 0.4003, F1: 0.7059

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.24456 | val 1.04799
  Epoch 011 - train 0.25020 | val 1.17858
  Classification -> best τ=0.555 (val F1=0.0194)
  Directional -> Accuracy: 0.4783, MCC: 0.0000, F1: 0.6471

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.39351 | val 1.59854
  Epoch 012 - train 0.31369 | val 1.54575
  Classification -> best τ=0.445 (val F1=0.2878)
  Directional -> Accuracy: 0.4412, MCC: 0.0509, F1: 0.5581

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.23938 | val 1.78960
  Epoch 012 - train 0.12789 | val 2.15771
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.24657 | val 1.76526
  Epoch 012 - train 0.12529 | val 1.77321
  Classification -> best τ=0.410 (val F1=0.2443)
  Directional -> Accuracy: 0.5833, MCC: 0.2810, F1: 0.6552

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.42823 | val 0.79629
  Epoch 016 - train 0.08847 | val 1.21777
  Classification -> best τ=0.225 (val F1=0.3318)
  Directional -> Accuracy: 0.3768, MCC: -0.1933, F1: 0.5169

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.33130 | val 1.78514
  Epoch 011 - train 0.28061 | val 1.88877
  Classification -> best τ=0.510 (val F1=0.0653)
  Directional -> Accuracy: 0.4082, MCC: -0.1687, F1: 0.4314

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.39144 | val 2.87647
  Epoch 012 - train 0.20198 | val 3.39862
  Classification -> best τ=0.535 (val F1=0.1512)
  Directional -> Accuracy: 0.4737, MCC: -0.0939, F1: 0.6154

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.27125 | val 1.40139
  Epoch 011 - train 0.21329 | val 1.84341
  Classification -> best τ=0.550 (val F1=0.2176)
  Directional -> Accuracy: 0.5476, MCC: 0.0000, F1: 0.0000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.25679 | val 1.29439
  Epoch 011 - train 0.17469 | val 1.26878
  Classification -> best τ=0.340 (val F1=0.3843)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.4828

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.34771 | val 1.45363
  Epoch 012 - train 0.22354 | val 1.32440
  Classification -> best τ=0.550 (val F1=0.0921)
  Directional -> Accuracy: 0.5490, MCC: 0.0199, F1: 0.0800

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.35691 | val 1.51253
  Epoch 012 - train 0.25384 | val 1.59539
  Classification -> best τ=0.230 (val F1=0.3094)
  Directional -> Accuracy: 0.5652, MCC: 0.1858, F1: 0.7115

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.36678 | val 1.34209
  Epoch 011 - train 0.24473 | val 1.42280
  Classification -> best τ=0.520 (val F1=0.1291)
  Directional -> Accuracy: 0.5862, MCC: 0.3993, F1: 0.5000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.38411 | val 2.40778
  Epoch 013 - train 0.24933 | val 2.05353
  Classification -> best τ=0.345 (val F1=0.2537)
  Directional -> Accuracy: 0.6133, MCC: 0.1123, F1: 0.7434

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.46031 | val 0.94910
  Epoch 012 - train 0.35399 | val 1.08770
  Classification -> best τ=0.585 (val F1=0.2453)
  Directional -> Accuracy: 0.4219, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.47616 | val 1.22661
  Epoch 014 - train 0.29979 | val 0.96032
  Classification -> best τ=0.535 (val F1=0.2926)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.25242 | val 1.49216
  Epoch 011 - train 0.21663 | val 1.73867
  Classification -> best τ=0.520 (val F1=0.0872)
  Directional -> Accuracy: 0.5106, MCC: -0.1254, F1: 0.6462

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.36077 | val 1.97835
  Epoch 011 - train 0.30073 | val 1.98449
  Classification -> best τ=0.430 (val F1=0.1952)
  Directional -> Accuracy: 0.4154, MCC: -0.1841, F1: 0.5000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.36334 | val 1.61541
  Epoch 012 - train 0.36276 | val 1.35953
  Classification -> best τ=0.515 (val F1=0.4032)
  Directional -> Accuracy: 0.5965, MCC: 0.1560, F1: 0.6849

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.48004 | val 1.02697
  Epoch 011 - train 0.52625 | val 0.75776
  Classification -> best τ=0.350 (val F1=0.0345)
  Directional -> Accuracy: 0.5077, MCC: 0.0049, F1: 0.4286

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.45649 | val 1.01888
  Epoch 015 - train 0.25070 | val 1.47783
  Classification -> best τ=0.610 (val F1=0.3446)
  Directional -> Accuracy: 0.5273, MCC: 0.1286, F1: 0.3810

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.05343 | val 1.45973
  Epoch 014 - train 0.04402 | val 2.86887
  Classification -> best τ=0.635 (val F1=0.4009)
  Directional -> Accuracy: 0.5111, MCC: -0.0165, F1: 0.3889

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.11715 | val 1.97908
  Epoch 013 - train 0.05520 | val 2.90765
  Classification -> best τ=0.605 (val F1=0.2527)
  Directional -> Accuracy: 0.5714, MCC: 0.1132, F1: 0.6400

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.34692 | val 2.21117
  Epoch 013 - train 0.22240 | val 2.80578
  Classification -> best τ=0.265 (val F1=0.1718)
  Directional -> Accuracy: 0.4821, MCC: -0.0604, F1: 0.5538

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.21680 | val 2.85566
  Epoch 012 - train 0.10804 | val 3.21873
  Classification -> best τ=0.500 (val F1=0.3296)
  Directional -> Accuracy: 0.6000, MCC: 0.1830, F1: 0.7143

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.20900 | val 2.09820
  Epoch 012 - train 0.11903 | val 2.20213
  Classification -> best τ=0.660 (val F1=0.3001)
  Directional -> Accuracy: 0.5476, MCC: 0.1137, F1: 0.5957

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.39422 | val 1.83647
  Epoch 012 - train 0.21849 | val 1.36792
  Classification -> best τ=0.525 (val F1=0.1707)
  Directional -> Accuracy: 0.4524, MCC: -0.1972, F1: 0.5965

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.12526 | val 2.01022
  Epoch 012 - train 0.05566 | val 2.21185
  Classification -> best τ=0.280 (val F1=0.3136)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.36089 | val 1.38154
  Epoch 013 - train 0.25248 | val 1.32391
  Classification -> best τ=0.465 (val F1=0.3287)
  Directional -> Accuracy: 0.5000, MCC: 0.1685, F1: 0.2174

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.27600 | val 2.40282
  Epoch 011 - train 0.16024 | val 2.16190
  Classification -> best τ=0.600 (val F1=0.3227)
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.42716 | val 1.13440
  Epoch 012 - train 0.23938 | val 1.39913
  Classification -> best τ=0.425 (val F1=0.1779)
  Directional -> Accuracy: 0.6061, MCC: 0.2193, F1: 0.6286

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.08921 | val 2.24161
  Epoch 013 - train 0.01197 | val 3.26113
  Classification -> best τ=0.375 (val F1=0.3589)
  Directional -> Accuracy: 0.5238, MCC: 0.0500, F1: 0.5238

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.34853 | val 0.84759
  Epoch 014 - train 0.22480 | val 0.95290
  Classification -> best τ=0.580 (val F1=0.3690)
  Directional -> Accuracy: 0.5714, MCC: 0.1281, F1: 0.4783

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.20990 | val 2.28640
  Epoch 012 - train 0.07660 | val 2.96359
  Classification -> best τ=0.440 (val F1=0.1859)
  Directional -> Accuracy: 0.3913, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.11206 | val 1.54975
  Epoch 011 - train 0.09524 | val 1.72607
  Classification -> best τ=0.515 (val F1=0.2513)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.49939 | val 1.13017
  Epoch 011 - train 0.40344 | val 1.61595
  Classification -> best τ=0.550 (val F1=0.1947)
  Directional -> Accuracy: 0.5000, MCC: -0.0151, F1: 0.3273

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.39155 | val 1.07197
  Epoch 013 - train 0.19833 | val 1.02958
  Classification -> best τ=0.445 (val F1=0.3287)
  Directional -> Accuracy: 0.4889, MCC: -0.0165, F1: 0.4103

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.21619 | val 1.23889
  Epoch 011 - train 0.15088 | val 1.32304
  Classification -> best τ=0.410 (val F1=0.1961)
  Directional -> Accuracy: 0.5476, MCC: 0.0829, F1: 0.5957

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.10721 | val 1.80074
  Epoch 011 - train 0.08929 | val 1.92237
  Classification -> best τ=0.585 (val F1=0.6590)
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.0000

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.29152 | val 1.17500
  Epoch 011 - train 0.21504 | val 1.36869
  Classification -> best τ=0.650 (val F1=0.1647)
  Directional -> Accuracy: 0.4727, MCC: 0.0346, F1: 0.1714

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.23829 | val 2.71377
  Epoch 011 - train 0.17921 | val 2.55665
  Classification -> best τ=0.385 (val F1=0.1124)
  Directional -> Accuracy: 0.5536, MCC: 0.1176, F1: 0.5902

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.30908 | val 1.65106
  Epoch 012 - train 0.17094 | val 1.66118
  Classification -> best τ=0.500 (val F1=0.1813)
  Directional -> Accuracy: 0.5472, MCC: 0.1056, F1: 0.6571

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.29779 | val 1.26222
  Epoch 013 - train 0.19097 | val 0.87553
  Classification -> best τ=0.510 (val F1=0.2368)
  Directional -> Accuracy: 0.5636, MCC: 0.1170, F1: 0.6250

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.41556 | val 0.74912

[I 2026-02-22 09:14:29,630] Trial 43 finished with value: 0.23478698301600284 and parameters: {'feature_set': 'all_nlp', 'model_type': 'BiGRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.4, 'dropout': 0.0, 'batch_size': 64, 'learning_rate': 0.009897932391788265, 'weight_decay': 7.500968661699272e-06, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 0.8726051722331332, 'early_stopping_min_delta': 0.009151544517232626}. Best is trial 22 with value: 0.2833350641483003.

  Epoch 016 - train 0.20911 | val 0.95420
  Classification -> best τ=0.490 (val F1=0.2354)
  Directional -> Accuracy: 0.4333, MCC: -0.1452, F1: 0.3462

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.23478698301600284
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 6
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d', 'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down', 'finbert_neutral']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.32191 | val 1.37670
  Epoch 011 - train 0.25065 | val 1.71883
  Classification -> best τ=0.430 (val F1=0.1660)
  Directional -> Accuracy: 0.5823, MCC: 0.1949, F1: 0.6024

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 82). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.25826 | val 1.11259
  Epoch 012 - train 0.18240 | val 1.28391
  Classification -> best τ=0.575 (val F1=0.2364)
  Directional -> Accuracy: 0.5208, MCC: 0.0420, F1: 0.5490

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 82). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.28075 | val 1.66404
  Epoch 011 - train 0.27604 | val 1.81055
  Classification -> best τ=0.560 (val F1=0.1319)
  Directional -> Accuracy: 0.4694, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.46516 | val 1.00675
  Epoch 014 - train 0.28270 | val 1.07203
  Classification -> best τ=0.435 (val F1=0.2040)
  Directional -> Accuracy: 0.5065, MCC: -0.1072, F1: 0.6607

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.30501 | val 0.86757
  Epoch 015 - train 0.17095 | val 1.34307
  Classification -> best τ=0.520 (val F1=0.4736)
  Directional -> Accuracy: 0.6415, MCC: 0.2935, F1: 0.6275

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.29566 | val 1.45852
  Epoch 011 - train 0.27998 | val 1.56939
  Classification -> best τ=0.590 (val F1=0.2032)
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.41155 | val 1.06491
  Epoch 012 - train 0.26756 | val 1.30641
  Classification -> best τ=0.430 (val F1=0.2412)
  Directional -> Accuracy: 0.4648, MCC: 0.0893, F1: 0.5778

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 82). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 82). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.25405 | val 1.09336
  Epoch 012 - train 0.23622 | val 1.35968
  Classification -> best τ=0.575 (val F1=0.2921)
  Directional -> Accuracy: 0.5532, MCC: -0.0959, F1: 0.0870

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.33485 | val 0.87775
  Epoch 011 - train 0.30361 | val 1.09371
  Classification -> best τ=0.480 (val F1=0.1439)
  Directional -> Accuracy: 0.4419, MCC: -0.0472, F1: 0.4783

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 82). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 82). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.35723 | val 1.28719
  Epoch 011 - train 0.29384 | val 1.30706
  Classification -> best τ=0.310 (val F1=0.1838)
  Directional -> Accuracy: 0.4306, MCC: 0.0000, F1: 0.6019

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.27758 | val 1.11630
  Epoch 011 - train 0.23481 | val 1.25941
  Classification -> best τ=0.565 (val F1=0.1701)
  Directional -> Accuracy: 0.5962, MCC: 0.2214, F1: 0.2759

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.25940 | val 1.76154
  Epoch 011 - train 0.23956 | val 1.85076
  Classification -> best τ=0.470 (val F1=0.2121)
  Directional -> Accuracy: 0.5333, MCC: 0.1336, F1: 0.6744

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.26790 | val 1.13468
  Epoch 011 - train 0.25746 | val 1.38742
  Classification -> best τ=0.645 (val F1=0.1231)
  Directional -> Accuracy: 0.4667, MCC: -0.0782, F1: 0.4000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 82). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.37956 | val 0.70728
  Epoch 014 - train 0.21975 | val 0.94758
  Classification -> best τ=0.485 (val F1=0.4811)
  Directional -> Accuracy: 0.5397, MCC: 0.0849, F1: 0.3556

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.30708 | val 0.91919
  Epoch 011 - train 0.25369 | val 1.49482
  Classification -> best τ=0.405 (val F1=0.1154)
  Directional -> Accuracy: 0.4259, MCC: -0.1657, F1: 0.5634

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.36305 | val 1.61720
  Epoch 011 - train 0.28998 | val 1.44362
  Classification -> best τ=0.450 (val F1=0.3137)
  Directional -> Accuracy: 0.6389, MCC: 0.2683, F1: 0.7111

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.36749 | val 1.59651
  Epoch 011 - train 0.30868 | val 1.69680
  Classification -> best τ=0.480 (val F1=0.0974)
  Directional -> Accuracy: 0.6066, MCC: 0.0000, F1: 0.7551

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.33382 | val 1.33420
  Epoch 011 - train 0.31966 | val 1.71342
  Classification -> best τ=0.530 (val F1=0.1204)
  Directional -> Accuracy: 0.4487, MCC: -0.1574, F1: 0.5474

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.40150 | val 0.98601
  Epoch 014 - train 0.25175 | val 1.10601
  Classification -> best τ=0.430 (val F1=0.2357)
  Directional -> Accuracy: 0.4328, MCC: -0.0434, F1: 0.2692

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 82). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.38284 | val 0.89134
  Epoch 011 - train 0.35078 | val 1.14041
  Classification -> best τ=0.500 (val F1=0.2424)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.31616 | val 0.82134
  Epoch 011 - train 0.26925 | val 0.99710
  Classification -> best τ=0.640 (val F1=0.1809)
  Directional -> Accuracy: 0.3800, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 82). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 82). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 82). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.38021 | val 0.90939
  Epoch 013 - train 0.24945 | val 1.09813
  Classification -> best τ=0.460 (val F1=0.2796)
  Directional -> Accuracy: 0.5882, MCC: 0.1768, F1: 0.5758

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.29155 | val 2.08804
  Epoch 011 - train 0.24232 | val 2.36615
  Classification -> best τ=0.510 (val F1=0.2358)
  Directional -> Accuracy: 0.5833, MCC: 0.1478, F1: 0.6377

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.29781 | val 2.61293
  Epoch 011 - train 0.25609 | val 3.17111
  Classification -> best τ=0.625 (val F1=0.1846)
  Directional -> Accuracy: 0.5147, MCC: 0.0000, F1: 0.0000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.31180 | val 0.78513
  Epoch 014 - train 0.18465 | val 0.98616
  Classification -> best τ=0.515 (val F1=0.3757)
  Directional -> Accuracy: 0.5345, MCC: 0.1519, F1: 0.4000

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.23847 | val 0.72768
  Epoch 020 - train 0.04907 | val 1.44025
  Epoch 022 - train 0.04327 | val 1.85806
  Classification -> best τ=0.340 (val F1=0.4036)
  Directional -> Accuracy: 0.5510, MCC: 0.1319, F1: 0.5600

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.35356 | val 0.77195
  Epoch 011 - train 0.33855 | val 0.77954
  Classification -> best τ=0.485 (val F1=0.0449)
  Directional -> Accuracy: 0.5556, MCC: 0.0569, F1: 0.6429

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.37085 | val 0.82859
  Epoch 011 - train 0.33990 | val 0.85207
  Classification -> best τ=0.435 (val F1=0.2526)
  Directional -> Accuracy: 0.4407, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.30403 | val 0.90492
  Epoch 011 - train 0.26429 | val 0.90701
  Classification -> best τ=0.490 (val F1=0.1975)
  Directional -> Accuracy: 0.5909, MCC: 0.2064, F1: 0.7000

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.30213 | val 1.24757
  Epoch 011 - train 0.24787 | val 1.10405
  Classification -> best τ=0.545 (val F1=0.2456)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.3429

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.34393 | val 0.98736
  Epoch 011 - train 0.31922 | val 1.00383
  Classification -> best τ=0.555 (val F1=0.1500)
  Directional -> Accuracy: 0.5435, MCC: 0.0000, F1: 0.7042

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.28225 | val 1.57799
  Epoch 012 - train 0.17901 | val 2.00004
  Classification -> best τ=0.485 (val F1=0.2384)
  Directional -> Accuracy: 0.5192, MCC: 0.0577, F1: 0.4186

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.37178 | val 0.80591
  Epoch 015 - train 0.15321 | val 1.06529
  Classification -> best τ=0.330 (val F1=0.3565)
  Directional -> Accuracy: 0.5600, MCC: 0.0000, F1: 0.7179

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 82). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.27082 | val 1.08639
  Epoch 011 - train 0.25046 | val 1.12286
  Classification -> best τ=0.560 (val F1=0.3287)
  Directional -> Accuracy: 0.5122, MCC: 0.0868, F1: 0.6552

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.26653 | val 1.09772
  Epoch 011 - train 0.26149 | val 1.14774
  Classification -> best τ=0.420 (val F1=0.1954)
  Directional -> Accuracy: 0.4565, MCC: 0.0000, F1: 0.6269

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.43568 | val 1.29801
  Epoch 013 - train 0.31904 | val 1.17174
  Classification -> best τ=0.560 (val F1=0.1941)
  Directional -> Accuracy: 0.4348, MCC: 0.1033, F1: 0.0488

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.27552 | val 0.70081
  Epoch 017 - train 0.10311 | val 1.04922
  Classification -> best τ=0.700 (val F1=0.4728)
  Directional -> Accuracy: 0.5111, MCC: 0.0518, F1: 0.2667

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.24059 | val 1.69194
  Epoch 011 - train 0.19800 | val 1.91772
  Classification -> best τ=0.430 (val F1=0.1378)
  Directional -> Accuracy: 0.5085, MCC: 0.0952, F1: 0.6420

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.29061 | val 1.16001
  Epoch 011 - train 0.26659 | val 1.20318
  Classification -> best τ=0.510 (val F1=0.2736)
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 82). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 82). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 82). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 82). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.31398 | val 1.00869
  Epoch 011 - train 0.30141 | val 1.05174
  Classification -> best τ=0.510 (val F1=0.2954)
  Directional -> Accuracy: 0.3333, MCC: 0.0000, F1: 0.5000

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 82). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.25383 | val 0.79734
  Epoch 011 - train 0.25995 | val 0.85280
  Classification -> best τ=0.515 (val F1=0.2467)
  Directional -> Accuracy: 0.6829, MCC: 0.3667, F1: 0.6829

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 82). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 82). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.36406 | val 1.64806
  Epoch 011 - train 0.31667 | val 1.85915
  Classification -> best τ=0.380 (val F1=0.2218)
  Directional -> Accuracy: 0.5065, MCC: 0.0000, F1: 0.6724

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 82). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 82). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.21892 | val 2.05944
  Epoch 011 - train 0.19664 | val 2.33790
  Classification -> best τ=0.595 (val F1=0.1037)
  Directional -> Accuracy: 0.4898, MCC: -0.1414, F1: 0.0000

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.25081 | val 1.21970
  Epoch 011 - train 0.23478 | val 1.26527
  Classification -> best τ=0.555 (val F1=0.2510)
  Directional -> Accuracy: 0.5745, MCC: 0.1828, F1: 0.5652

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.30576 | val 1.43594
  Epoch 011 - train 0.25428 | val 1.38066
  Classification -> best τ=0.480 (val F1=0.0551)
  Directional -> Accuracy: 0.3571, MCC: 0.0000, F1: 0.5263

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.32247 | val 1.35189
  Epoch 011 - train 0.29240 | val 1.49792
  Classification -> best τ=0.410 (val F1=0.2249)
  Directional -> Accuracy: 0.6724, MCC: 0.3598, F1: 0.7595

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.33535 | val 1.52115
  Epoch 013 - train 0.17983 | val 2.20593
  Classification -> best τ=0.625 (val F1=0.3679)
  Directional -> Accuracy: 0.4746, MCC: -0.0659, F1: 0.3111

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.36656 | val 2.35719
  Epoch 011 - train 0.26056 | val 1.88153
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.32971 | val 1.45578
  Epoch 011 - train 0.29141 | val 2.01207
  Classification -> best τ=0.555 (val F1=0.1111)
  Directional -> Accuracy: 0.4828, MCC: -0.0065, F1: 0.0625

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.38336 | val 0.99791

[I 2026-02-22 09:15:08,878] Trial 44 finished with value: 0.22612260170246168 and parameters: {'feature_set': 'sector_finbert', 'model_type': 'BiGRU', 'sequence_length': 6, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 1, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.1, 'batch_size': 64, 'learning_rate': 0.003451924710174912, 'weight_decay': 1.1406648961651718e-05, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 1.1454111298724587, 'early_stopping_min_delta': 0.009556772925176376}. Best is trial 22 with value: 0.2833350641483003.

  Epoch 017 - train 0.14441 | val 1.41047
  Classification -> best τ=0.485 (val F1=0.2929)
  Directional -> Accuracy: 0.5556, MCC: 0.1136, F1: 0.2632

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.22612260170246168
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 12
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down', 'finbert_neutral']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.70330 | val 0.74038
  Epoch 016 - train 0.70396 | val 0.74331
  Classification -> best τ=0.500 (val F1=0.2425)
  Directional -> Accuracy: 0.5897, MCC: 0.1583, F1: 0.2727

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 88). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.72242 | val 0.73219
  Epoch 016 - train 0.69518 | val 0.73381
  Classification -> best τ=0.445 (val F1=0.1325)
  Directional -> Accuracy: 0.5106, MCC: -0.1207, F1: 0.6667

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 88). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.69563 | val 0.67360
  Epoch 018 - train 0.70686 | val 0.67158
  Classification -> best τ=0.500 (val F1=0.3012)
  Directional -> Accuracy: 0.6042, MCC: 0.2212, F1: 0.5957

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.69898 | val 0.82984
  Epoch 016 - train 0.72052 | val 0.81334
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5395, MCC: 0.0000, F1: 0.7009

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.71646 | val 0.72850
  Epoch 016 - train 0.72769 | val 0.72290
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.7000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.71843 | val 0.73778
  Epoch 016 - train 0.72544 | val 0.73522
  Classification -> best τ=0.490 (val F1=0.1502)
  Directional -> Accuracy: 0.4286, MCC: -0.2119, F1: 0.5758

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.70261 | val 0.76399
  Epoch 016 - train 0.69994 | val 0.76640
  Classification -> best τ=0.545 (val F1=0.0979)
  Directional -> Accuracy: 0.5429, MCC: -0.0133, F1: 0.3043

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 88). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 88). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.68976 | val 0.69451
  Epoch 020 - train 0.66908 | val 0.70575
  Epoch 021 - train 0.70195 | val 0.70721
  Classification -> best τ=0.455 (val F1=0.1129)
  Directional -> Accuracy: 0.4444, MCC: 0.0481, F1: 0.5902

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.70190 | val 0.72637
  Epoch 016 - train 0.70544 | val 0.73216
  Classification -> best τ=0.535 (val F1=0.3364)
  Directional -> Accuracy: 0.3810, MCC: 0.0000, F1: 0.5517

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 88). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 88). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.70847 | val 0.69500
  Epoch 016 - train 0.70911 | val 0.69299
  Classification -> best τ=0.530 (val F1=0.0813)
  Directional -> Accuracy: 0.6197, MCC: 0.2114, F1: 0.5091

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.70300 | val 0.75010
  Epoch 016 - train 0.71238 | val 0.75672
  Classification -> best τ=0.480 (val F1=0.1555)
  Directional -> Accuracy: 0.4118, MCC: -0.1667, F1: 0.4828

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.73580 | val 0.70446
  Epoch 016 - train 0.69202 | val 0.70420
  Classification -> best τ=0.500 (val F1=0.2811)
  Directional -> Accuracy: 0.3559, MCC: -0.3455, F1: 0.0952

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.71376 | val 0.96572
  Epoch 016 - train 0.71816 | val 0.95418
  Classification -> best τ=0.505 (val F1=0.2175)
  Directional -> Accuracy: 0.6136, MCC: 0.2160, F1: 0.4138

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 88). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.69708 | val 0.63154
  Epoch 020 - train 0.67570 | val 0.62548
  Epoch 030 - train 0.68906 | val 0.62008
  Classification -> best τ=0.355 (val F1=0.3848)
  Directional -> Accuracy: 0.5806, MCC: 0.1981, F1: 0.4091

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.70476 | val 0.83320
  Epoch 016 - train 0.70618 | val 0.84558
  Classification -> best τ=0.535 (val F1=0.1571)
  Directional -> Accuracy: 0.4528, MCC: -0.1468, F1: 0.6234

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.72100 | val 0.72551
  Epoch 016 - train 0.69094 | val 0.72071
  Classification -> best τ=0.435 (val F1=0.1620)
  Directional -> Accuracy: 0.5493, MCC: 0.0746, F1: 0.6923

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.72532 | val 0.84178
  Epoch 016 - train 0.72932 | val 0.84244
  Classification -> best τ=0.430 (val F1=0.1567)
  Directional -> Accuracy: 0.6000, MCC: 0.2138, F1: 0.6364

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.69436 | val 0.69564
  Epoch 016 - train 0.71183 | val 0.69527
  Classification -> best τ=0.510 (val F1=0.1193)
  Directional -> Accuracy: 0.6104, MCC: 0.0000, F1: 0.7581

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.69739 | val 0.73036
  Epoch 016 - train 0.71434 | val 0.72799
  Classification -> best τ=0.530 (val F1=0.1374)
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 88). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.70906 | val 0.70073
  Epoch 020 - train 0.69845 | val 0.68443
  Epoch 030 - train 0.70651 | val 0.68226
  Classification -> best τ=0.360 (val F1=0.2236)
  Directional -> Accuracy: 0.5395, MCC: 0.0000, F1: 0.7009

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.74239 | val 0.71953
  Epoch 016 - train 0.74687 | val 0.72073
  Classification -> best τ=0.455 (val F1=0.1091)
  Directional -> Accuracy: 0.5918, MCC: 0.1633, F1: 0.6552

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 88). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 88). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 88). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.71759 | val 0.72211
  Epoch 016 - train 0.70775 | val 0.71872
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5075, MCC: 0.0000, F1: 0.6733

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.74156 | val 0.71277
  Epoch 016 - train 0.71190 | val 0.71079
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5763, MCC: 0.0000, F1: 0.7312

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.69442 | val 0.82928
  Epoch 016 - train 0.71113 | val 0.84605
  Classification -> best τ=0.495 (val F1=0.2333)
  Directional -> Accuracy: 0.5821, MCC: 0.1764, F1: 0.6111

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.69356 | val 0.70547
  Epoch 016 - train 0.72647 | val 0.70042
  Classification -> best τ=0.535 (val F1=0.0799)
  Directional -> Accuracy: 0.4912, MCC: -0.0572, F1: 0.5797

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.67288 | val 0.69321
  Epoch 020 - train 0.69297 | val 0.70568
  Epoch 021 - train 0.74079 | val 0.70450
  Classification -> best τ=0.510 (val F1=0.2239)
  Directional -> Accuracy: 0.4167, MCC: -0.0352, F1: 0.5758

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.70534 | val 0.73285
  Epoch 016 - train 0.71773 | val 0.72085
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5909, MCC: 0.0000, F1: 0.7429

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.67408 | val 0.65792
  Epoch 020 - train 0.70127 | val 0.66175
  Epoch 021 - train 0.71904 | val 0.66181
  Classification -> best τ=0.430 (val F1=0.3959)
  Directional -> Accuracy: 0.4655, MCC: 0.1194, F1: 0.0606

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.71628 | val 0.75145
  Epoch 016 - train 0.72347 | val 0.76726
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.68849 | val 0.70016
  Epoch 016 - train 0.69578 | val 0.70138
  Classification -> best τ=0.505 (val F1=0.1512)
  Directional -> Accuracy: 0.4889, MCC: -0.0832, F1: 0.6462

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.71766 | val 0.66996
  Epoch 016 - train 0.71165 | val 0.67033
  Classification -> best τ=0.530 (val F1=0.2390)
  Directional -> Accuracy: 0.5333, MCC: 0.0000, F1: 0.6957

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.72041 | val 0.69349
  Epoch 016 - train 0.69428 | val 0.69168
  Classification -> best τ=0.520 (val F1=0.1283)
  Directional -> Accuracy: 0.4706, MCC: 0.0000, F1: 0.0000

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.70783 | val 0.68232
  Epoch 020 - train 0.68261 | val 0.67794
  Epoch 030 - train 0.67501 | val 0.67579
  Classification -> best τ=0.535 (val F1=0.3928)
  Directional -> Accuracy: 0.5811, MCC: 0.2326, F1: 0.5231

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 88). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.73794 | val 0.72437
  Epoch 016 - train 0.72244 | val 0.73593
  Classification -> best τ=0.465 (val F1=0.2227)
  Directional -> Accuracy: 0.4872, MCC: -0.0237, F1: 0.5000

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.72611 | val 0.69934
  Epoch 016 - train 0.69576 | val 0.70063
  Classification -> best τ=0.495 (val F1=0.1607)
  Directional -> Accuracy: 0.5333, MCC: 0.0209, F1: 0.1600

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.69725 | val 0.67317
  Epoch 020 - train 0.68867 | val 0.66653
  Epoch 030 - train 0.70193 | val 0.66488
  Classification -> best τ=0.420 (val F1=0.2989)
  Directional -> Accuracy: 0.5000, MCC: 0.1613, F1: 0.2917

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.71708 | val 0.69272
  Epoch 016 - train 0.71509 | val 0.69223
  Classification -> best τ=0.540 (val F1=0.0809)
  Directional -> Accuracy: 0.4773, MCC: -0.0902, F1: 0.6349

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.72103 | val 0.69357
  Epoch 016 - train 0.70677 | val 0.69194
  Classification -> best τ=0.490 (val F1=0.0934)
  Directional -> Accuracy: 0.5345, MCC: 0.0235, F1: 0.1818

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.71423 | val 0.95621
  Epoch 016 - train 0.70868 | val 0.98248
  Classification -> best τ=0.550 (val F1=0.1912)
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 88). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 88). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 88). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 88). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.72942 | val 0.70715
  Epoch 016 - train 0.73489 | val 0.70615
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.3500, MCC: 0.0000, F1: 0.5185

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 88). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.72122 | val 0.71498
  Epoch 016 - train 0.72076 | val 0.71666
  Classification -> best τ=0.505 (val F1=0.2548)
  Directional -> Accuracy: 0.5128, MCC: -0.0088, F1: 0.6122

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 88). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 88). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.68452 | val 0.70235
  Epoch 016 - train 0.71488 | val 0.70150
  Classification -> best τ=0.545 (val F1=0.1601)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 88). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 88). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 88). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.74102 | val 0.71372
  Epoch 016 - train 0.70531 | val 0.71484
  Classification -> best τ=0.510 (val F1=0.2485)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.74380 | val 0.69355
  Epoch 016 - train 0.72307 | val 0.69406
  Classification -> best τ=0.465 (val F1=0.4183)
  Directional -> Accuracy: 0.5111, MCC: -0.0215, F1: 0.6071

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.71748 | val 0.80356
  Epoch 016 - train 0.68502 | val 0.82794
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.3659, MCC: 0.0000, F1: 0.5357

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.72960 | val 0.69494
  Epoch 016 - train 0.69967 | val 0.70019
  Classification -> best τ=0.525 (val F1=0.1298)
  Directional -> Accuracy: 0.5439, MCC: 0.1474, F1: 0.4348

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.69649 | val 0.68203
  Epoch 018 - train 0.69966 | val 0.68227
  Classification -> best τ=0.550 (val F1=0.2409)
  Directional -> Accuracy: 0.5172, MCC: 0.0000, F1: 0.0000

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.69966 | val 0.69859
  Epoch 016 - train 0.71576 | val 0.69701
  Classification -> best τ=0.505 (val F1=0.1197)
  Directional -> Accuracy: 0.5455, MCC: 0.1041, F1: 0.5098

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.69935 | val 0.74900
  Epoch 016 - train 0.69256 | val 0.73692
  Classification -> best τ=0.530 (val F1=0.2000)
  Directional -> Accuracy: 0.5614, MCC: 0.1217, F1: 0.6032

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.73021 | val 0.80233

[I 2026-02-22 09:18:39,991] Trial 45 finished with value: 0.1690359902581218 and parameters: {'feature_set': 'finbert', 'model_type': 'BiGRU', 'sequence_length': 12, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 64, 'num_layers': 2, 'inter_rnn_drop': 0.1, 'dropout': 0.7000000000000001, 'batch_size': 16, 'learning_rate': 5.33893738952391e-06, 'weight_decay': 2.145816577761698e-05, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 15, 'max_epochs': 30, 'huber_delta': 0.4199147749055143, 'early_stopping_min_delta': 0.006808504762301289}. Best is trial 22 with value: 0.2833350641483003.

  Epoch 016 - train 0.72431 | val 0.79232
  Classification -> best τ=0.570 (val F1=0.2285)
  Directional -> Accuracy: 0.5161, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.1690359902581218
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d', 'sentiment']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.57160 | val 0.95542
  Epoch 014 - train 0.50747 | val 0.95409
  Classification -> best τ=0.805 (val F1=0.2510)
  Directional -> Accuracy: 0.5526, MCC: 0.0000, F1: 0.0000

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.49716 | val 0.74262
  Epoch 011 - train 0.45484 | val 0.70237
  Classification -> best τ=0.380 (val F1=0.1289)
  Directional -> Accuracy: 0.5778, MCC: 0.0000, F1: 0.7324

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.46833 | val 2.52074
  Epoch 012 - train 0.41909 | val 3.07244
  Classification -> best τ=0.755 (val F1=0.2727)
  Directional -> Accuracy: 0.5000, MCC: 0.1427, F1: 0.0800

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.57204 | val 0.72871
  Epoch 012 - train 0.53907 | val 0.77545
  Classification -> best τ=0.415 (val F1=0.2230)
  Directional -> Accuracy: 0.5405, MCC: 0.0000, F1: 0.7018

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.50000 | val 0.78785
  Epoch 015 - train 0.40664 | val 0.71527
  Classification -> best τ=0.480 (val F1=0.5167)
  Directional -> Accuracy: 0.6800, MCC: 0.4208, F1: 0.6000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.46519 | val 0.73451
  Epoch 015 - train 0.39388 | val 1.34810
  Classification -> best τ=0.435 (val F1=0.1808)
  Directional -> Accuracy: 0.4783, MCC: 0.0000, F1: 0.6471

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.56901 | val 1.44196
  Epoch 012 - train 0.55325 | val 1.41265
  Classification -> best τ=0.570 (val F1=0.1463)
  Directional -> Accuracy: 0.4706, MCC: -0.0921, F1: 0.3571

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.43617 | val 0.79464
  Epoch 016 - train 0.34414 | val 0.85283
  Classification -> best τ=0.160 (val F1=0.4215)
  Directional -> Accuracy: 0.4524, MCC: 0.1353, F1: 0.6102

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.49133 | val 1.54249
  Epoch 012 - train 0.46883 | val 1.58468
  Classification -> best τ=0.525 (val F1=0.3431)
  Directional -> Accuracy: 0.6250, MCC: 0.2492, F1: 0.3077

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.51087 | val 1.12967
  Epoch 011 - train 0.48677 | val 1.22011
  Classification -> best τ=0.685 (val F1=0.1607)
  Directional -> Accuracy: 0.5507, MCC: 0.0291, F1: 0.3404

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.52160 | val 1.77509
  Epoch 011 - train 0.48587 | val 1.43857
  Classification -> best τ=0.545 (val F1=0.2173)
  Directional -> Accuracy: 0.6122, MCC: 0.2278, F1: 0.5957

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.56956 | val 1.53939
  Epoch 011 - train 0.53893 | val 1.54457
  Classification -> best τ=0.355 (val F1=0.1724)
  Directional -> Accuracy: 0.5088, MCC: 0.0000, F1: 0.6744

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.43602 | val 1.58409
  Epoch 013 - train 0.44911 | val 1.24223
  Classification -> best τ=0.535 (val F1=0.1705)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.6230

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.51367 | val 0.71585
  Epoch 011 - train 0.49773 | val 0.80144
  Classification -> best τ=0.415 (val F1=0.3126)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.53217 | val 0.81412
  Epoch 011 - train 0.50925 | val 0.76348
  Classification -> best τ=0.430 (val F1=0.2971)
  Directional -> Accuracy: 0.5294, MCC: 0.1160, F1: 0.6000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.50502 | val 1.40274
  Epoch 012 - train 0.44766 | val 1.37588
  Classification -> best τ=0.455 (val F1=0.2795)
  Directional -> Accuracy: 0.6232, MCC: 0.2986, F1: 0.7347

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.54898 | val 1.45534
  Epoch 011 - train 0.47448 | val 1.47785
  Classification -> best τ=0.385 (val F1=0.1905)
  Directional -> Accuracy: 0.6207, MCC: 0.0000, F1: 0.7660

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.54694 | val 1.14277
  Epoch 011 - train 0.49260 | val 1.38870
  Classification -> best τ=0.615 (val F1=0.1909)
  Directional -> Accuracy: 0.4000, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.55352 | val 1.09309
  Epoch 011 - train 0.54058 | val 1.04333
  Classification -> best τ=0.365 (val F1=0.2843)
  Directional -> Accuracy: 0.5469, MCC: 0.0286, F1: 0.6506

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.49955 | val 0.82749
  Epoch 012 - train 0.45023 | val 0.92653
  Classification -> best τ=0.500 (val F1=0.2377)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.43349 | val 1.16568
  Epoch 011 - train 0.41686 | val 1.28548
  Classification -> best τ=0.545 (val F1=0.1250)
  Directional -> Accuracy: 0.5532, MCC: 0.1469, F1: 0.5714

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.55889 | val 1.67768
  Epoch 012 - train 0.48399 | val 1.73208
  Classification -> best τ=0.500 (val F1=0.2245)
  Directional -> Accuracy: 0.4923, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.51376 | val 0.78946
  Epoch 015 - train 0.42101 | val 0.92227
  Classification -> best τ=0.720 (val F1=0.4362)
  Directional -> Accuracy: 0.5614, MCC: 0.1304, F1: 0.5763

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.53336 | val 0.75207
  Epoch 012 - train 0.45970 | val 0.80885
  Classification -> best τ=0.390 (val F1=0.3078)
  Directional -> Accuracy: 0.5231, MCC: 0.0624, F1: 0.5753

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.49199 | val 0.93336
  Epoch 012 - train 0.43835 | val 1.23554
  Classification -> best τ=0.365 (val F1=0.4973)
  Directional -> Accuracy: 0.5818, MCC: 0.1733, F1: 0.5818

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.47152 | val 1.98870
  Epoch 011 - train 0.41464 | val 2.22779
  Classification -> best τ=0.500 (val F1=0.4947)
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.5938

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.54122 | val 0.70642
  Epoch 012 - train 0.56260 | val 0.78141
  Classification -> best τ=0.700 (val F1=0.2402)
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.0000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.54234 | val 0.79568
  Epoch 013 - train 0.47749 | val 0.96933
  Classification -> best τ=0.550 (val F1=0.2305)
  Directional -> Accuracy: 0.4464, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.47212 | val 2.93538
  Epoch 011 - train 0.44869 | val 2.68449
  Classification -> best τ=0.445 (val F1=0.3477)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.5238

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.53491 | val 1.39127
  Epoch 011 - train 0.48699 | val 0.87607
  Classification -> best τ=0.525 (val F1=0.3501)
  Directional -> Accuracy: 0.5714, MCC: 0.1779, F1: 0.2500

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.52231 | val 0.76528
  Epoch 013 - train 0.53096 | val 0.68128
  Classification -> best τ=0.665 (val F1=0.2697)
  Directional -> Accuracy: 0.4286, MCC: -0.1533, F1: 0.4783

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.44136 | val 1.29544
  Epoch 011 - train 0.46305 | val 1.29283
  Classification -> best τ=0.640 (val F1=0.2969)
  Directional -> Accuracy: 0.4694, MCC: 0.0000, F1: 0.0000

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.57211 | val 1.08199
  Epoch 011 - train 0.50122 | val 1.14035
  Classification -> best τ=0.420 (val F1=0.2458)
  Directional -> Accuracy: 0.4444, MCC: 0.0000, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.49430 | val 1.16664
  Epoch 011 - train 0.45814 | val 1.22264
  Classification -> best τ=0.395 (val F1=0.2040)
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.60588 | val 1.38284
  Epoch 012 - train 0.54029 | val 1.19848
  Classification -> best τ=0.335 (val F1=0.3787)
  Directional -> Accuracy: 0.6212, MCC: 0.2284, F1: 0.6667

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.40885 | val 2.16977
  Epoch 011 - train 0.42945 | val 2.48805
  Classification -> best τ=0.455 (val F1=0.1745)
  Directional -> Accuracy: 0.6667, MCC: 0.3319, F1: 0.7083

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.46748 | val 1.15339
  Epoch 011 - train 0.46949 | val 1.28552
  Classification -> best τ=0.485 (val F1=0.2755)
  Directional -> Accuracy: 0.5000, MCC: 0.0103, F1: 0.5172

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.49449 | val 1.86108
  Epoch 011 - train 0.43223 | val 1.88409
  Classification -> best τ=0.535 (val F1=0.3451)
  Directional -> Accuracy: 0.6087, MCC: 0.0863, F1: 0.7353

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.56036 | val 0.65672
  Epoch 019 - train 0.39448 | val 0.67991
  Classification -> best τ=0.340 (val F1=0.3970)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.48818 | val 1.47405
  Epoch 011 - train 0.42756 | val 1.59848
  Classification -> best τ=0.335 (val F1=0.2944)
  Directional -> Accuracy: 0.4865, MCC: 0.0000, F1: 0.6545

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.52434 | val 0.77453
  Epoch 011 - train 0.50285 | val 1.01591
  Classification -> best τ=0.430 (val F1=0.2586)
  Directional -> Accuracy: 0.5111, MCC: 0.0000, F1: 0.6765

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.42242 | val 1.21701
  Epoch 012 - train 0.35047 | val 1.42301
  Classification -> best τ=0.670 (val F1=0.3612)
  Directional -> Accuracy: 0.4286, MCC: -0.0913, F1: 0.3333

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.47831 | val 0.77523
  Epoch 012 - train 0.38349 | val 0.79723
  Classification -> best τ=0.470 (val F1=0.3410)
  Directional -> Accuracy: 0.5417, MCC: 0.2914, F1: 0.6071

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.58616 | val 0.93227
  Epoch 011 - train 0.56661 | val 0.87560
  Classification -> best τ=0.590 (val F1=0.3238)
  Directional -> Accuracy: 0.4545, MCC: -0.0256, F1: 0.1176

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.52064 | val 1.48459
  Epoch 011 - train 0.45581 | val 1.45582
  Classification -> best τ=0.530 (val F1=0.1566)
  Directional -> Accuracy: 0.5000, MCC: 0.0227, F1: 0.6000

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.54404 | val 1.29840
  Epoch 012 - train 0.51333 | val 1.39086
  Classification -> best τ=0.640 (val F1=0.2064)
  Directional -> Accuracy: 0.6038, MCC: 0.2080, F1: 0.6038

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.53222 | val 0.83940
  Epoch 013 - train 0.45580 | val 1.08200
  Classification -> best τ=0.420 (val F1=0.2257)
  Directional -> Accuracy: 0.4000, MCC: -0.2291, F1: 0.1081

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.59283 | val 0.71652

[I 2026-02-22 09:20:50,340] Trial 46 finished with value: 0.2775459296298333 and parameters: {'feature_set': 'sector_sentiment', 'model_type': 'BiGRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.4, 'dropout': 0.0, 'batch_size': 32, 'learning_rate': 0.005384084276131887, 'weight_decay': 5.066765210649944e-06, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 0.9790393368041543, 'early_stopping_min_delta': 0.008358005226334817}. Best is trial 22 with value: 0.2833350641483003.

  Epoch 016 - train 0.43725 | val 1.36921
  Classification -> best τ=0.410 (val F1=0.3158)
  Directional -> Accuracy: 0.5500, MCC: 0.2112, F1: 0.6747

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2775459296298333
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: classification
Sequence length: 6
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d', 'emotion_anger', 'emotion_disgust', 'emotion_fear', 'emotion_joy', 'emotion_neutral', 'emotion_sadness', 'emotion_surprize', 'emotion_anger_pct', 'emotion_disgust_pct', 'emotion_fear_pct', 'emotion_joy_pct', 'emotion_neutral_pct', 'emotion_sadness_pct', 'emotion_surprize_pct']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.69540 | val 0.69161
  Epoch 011 - train 0.71296 | val 0.69108
  Classification -> best τ=0.490 (val F1=0.1365)
  Directional -> Accuracy: 0.4557, MCC: 0.0225, F1: 0.6055

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 82). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.72814 | val 0.70308
  Epoch 011 - train 0.73451 | val 0.70498
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5625, MCC: 0.0000, F1: 0.7200

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 82). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.70242 | val 0.73067
  Epoch 011 - train 0.69982 | val 0.73825
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.69054 | val 0.68024
  Epoch 016 - train 0.69736 | val 0.67966
  Classification -> best τ=0.510 (val F1=0.2035)
  Directional -> Accuracy: 0.4545, MCC: -0.0430, F1: 0.2500

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.70586 | val 0.69011
  Epoch 011 - train 0.70515 | val 0.69028
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5283, MCC: 0.0000, F1: 0.6914

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.70112 | val 0.69432
  Epoch 011 - train 0.70325 | val 0.69539
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4634, MCC: 0.0000, F1: 0.6333

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.70548 | val 0.69800
  Epoch 011 - train 0.70038 | val 0.69839
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4085, MCC: 0.0000, F1: 0.5800

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 82). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 82). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.69041 | val 0.73756
  Epoch 011 - train 0.69016 | val 0.74251
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4043, MCC: 0.0000, F1: 0.5758

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.70431 | val 0.69572
  Epoch 011 - train 0.70402 | val 0.69662
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.3953, MCC: 0.0000, F1: 0.5667

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 82). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 82). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.69375 | val 0.69855
  Epoch 011 - train 0.69108 | val 0.69896
  Classification -> best τ=0.470 (val F1=0.0104)
  Directional -> Accuracy: 0.5278, MCC: 0.0217, F1: 0.4138

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.70288 | val 0.69578
  Epoch 011 - train 0.70845 | val 0.70020
  Classification -> best τ=0.465 (val F1=0.0075)
  Directional -> Accuracy: 0.4615, MCC: -0.0714, F1: 0.4615

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.70446 | val 0.70158
  Epoch 011 - train 0.70500 | val 0.70328
  Classification -> best τ=0.520 (val F1=0.1227)
  Directional -> Accuracy: 0.5333, MCC: 0.0754, F1: 0.3913

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.69830 | val 0.69102
  Epoch 011 - train 0.69732 | val 0.69371
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4667, MCC: 0.0000, F1: 0.6364

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 82). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.69388 | val 0.75290
  Epoch 011 - train 0.69901 | val 0.75725
  Classification -> best τ=0.510 (val F1=0.0857)
  Directional -> Accuracy: 0.4921, MCC: 0.0000, F1: 0.6596

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.70216 | val 0.70656
  Epoch 011 - train 0.70495 | val 0.70454
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4815, MCC: 0.0000, F1: 0.6500

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.70885 | val 0.72899
  Epoch 011 - train 0.71176 | val 0.72960
  Classification -> best τ=0.455 (val F1=0.1755)
  Directional -> Accuracy: 0.5694, MCC: 0.1261, F1: 0.7048

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.71154 | val 0.72513
  Epoch 011 - train 0.71844 | val 0.72746
  Classification -> best τ=0.465 (val F1=0.0426)
  Directional -> Accuracy: 0.3934, MCC: -0.2448, F1: 0.4789

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.69775 | val 0.71059
  Epoch 011 - train 0.69322 | val 0.71106
  Classification -> best τ=0.460 (val F1=0.1200)
  Directional -> Accuracy: 0.6026, MCC: 0.0000, F1: 0.7520

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.69622 | val 0.70125
  Epoch 011 - train 0.69265 | val 0.70166
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5821, MCC: 0.0000, F1: 0.7358

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 82). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.68655 | val 0.68974
  Epoch 011 - train 0.69857 | val 0.69011
  Classification -> best τ=0.480 (val F1=0.1112)
  Directional -> Accuracy: 0.4675, MCC: 0.0074, F1: 0.1961

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.71589 | val 0.71888
  Epoch 011 - train 0.71343 | val 0.72459
  Classification -> best τ=0.510 (val F1=0.1842)
  Directional -> Accuracy: 0.6200, MCC: 0.0000, F1: 0.7654

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 82). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 82). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 82). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.69742 | val 0.69952
  Epoch 011 - train 0.69515 | val 0.69900
  Classification -> best τ=0.510 (val F1=0.1741)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.70442 | val 0.72322
  Epoch 011 - train 0.70531 | val 0.72299
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5833, MCC: 0.0000, F1: 0.7368

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.68742 | val 0.68823
  Epoch 017 - train 0.69279 | val 0.68785
  Classification -> best τ=0.545 (val F1=0.2279)
  Directional -> Accuracy: 0.5147, MCC: 0.0000, F1: 0.0000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.68721 | val 0.71414
  Epoch 011 - train 0.69761 | val 0.71692
  Classification -> best τ=0.515 (val F1=0.0787)
  Directional -> Accuracy: 0.5000, MCC: 0.0823, F1: 0.3256

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.66596 | val 0.69341
  Epoch 011 - train 0.66195 | val 0.69466
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.69461 | val 0.69743
  Epoch 011 - train 0.70098 | val 0.70038
  Classification -> best τ=0.530 (val F1=0.1607)
  Directional -> Accuracy: 0.5556, MCC: -0.0237, F1: 0.6875

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.70193 | val 0.69088
  Epoch 011 - train 0.69553 | val 0.69162
  Classification -> best τ=0.475 (val F1=0.0423)
  Directional -> Accuracy: 0.5085, MCC: -0.0600, F1: 0.6329

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.69064 | val 0.68975
  Epoch 011 - train 0.68716 | val 0.68977
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5227, MCC: 0.0000, F1: 0.6866

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.68999 | val 0.70388
  Epoch 011 - train 0.70560 | val 0.70653
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.69351 | val 0.67879
  Epoch 011 - train 0.69419 | val 0.67784
  Classification -> best τ=0.520 (val F1=0.0095)
  Directional -> Accuracy: 0.3913, MCC: -0.2025, F1: 0.3333

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.69956 | val 0.68389
  Epoch 011 - train 0.70786 | val 0.68363
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5192, MCC: 0.0000, F1: 0.6835

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.69675 | val 0.67100
  Epoch 018 - train 0.70117 | val 0.67091
  Classification -> best τ=0.515 (val F1=0.2337)
  Directional -> Accuracy: 0.4400, MCC: 0.0000, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 82). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.70182 | val 0.68777
  Epoch 011 - train 0.70302 | val 0.68734
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4878, MCC: 0.0000, F1: 0.6557

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.70422 | val 0.69136
  Epoch 011 - train 0.69665 | val 0.69314
  Classification -> best τ=0.470 (val F1=0.1818)
  Directional -> Accuracy: 0.5435, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.69001 | val 0.70444
  Epoch 011 - train 0.69583 | val 0.70436
  Classification -> best τ=0.495 (val F1=0.0750)
  Directional -> Accuracy: 0.4493, MCC: -0.1099, F1: 0.5000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.69952 | val 0.70305
  Epoch 011 - train 0.70694 | val 0.70473
  Classification -> best τ=0.535 (val F1=0.1319)
  Directional -> Accuracy: 0.5111, MCC: 0.0349, F1: 0.3889

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.69113 | val 0.68994
  Epoch 011 - train 0.68782 | val 0.69071
  Classification -> best τ=0.465 (val F1=0.1463)
  Directional -> Accuracy: 0.5932, MCC: 0.2029, F1: 0.6250

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.70689 | val 0.73221
  Epoch 011 - train 0.70178 | val 0.73441
  Classification -> best τ=0.530 (val F1=0.1312)
  Directional -> Accuracy: 0.4490, MCC: 0.0530, F1: 0.3077

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 82). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 82). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 82). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 82). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.71209 | val 0.68340
  Epoch 011 - train 0.70713 | val 0.68323
  Classification -> best τ=0.460 (val F1=0.1517)
  Directional -> Accuracy: 0.3333, MCC: 0.0000, F1: 0.5000

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 82). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.70889 | val 0.70947
  Epoch 011 - train 0.70451 | val 0.71105
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5122, MCC: 0.0000, F1: 0.6774

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 82). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 82). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.69640 | val 0.70293
  Epoch 011 - train 0.69440 | val 0.70337
  Classification -> best τ=0.470 (val F1=0.1132)
  Directional -> Accuracy: 0.5195, MCC: 0.1162, F1: 0.6783

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 82). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 82). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.70835 | val 0.70929
  Epoch 011 - train 0.70031 | val 0.71167
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4898, MCC: 0.0000, F1: 0.6575

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.68292 | val 0.73235
  Epoch 011 - train 0.69101 | val 0.73371
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5745, MCC: 0.0000, F1: 0.7297

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.69147 | val 0.69869
  Epoch 011 - train 0.70394 | val 0.70061
  Classification -> best τ=0.495 (val F1=0.2706)
  Directional -> Accuracy: 0.5714, MCC: 0.0081, F1: 0.3077

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.68771 | val 0.69559
  Epoch 011 - train 0.69609 | val 0.69712
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5517, MCC: 0.0000, F1: 0.7111

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.70037 | val 0.77793
  Epoch 011 - train 0.69091 | val 0.78261
  Classification -> best τ=0.545 (val F1=0.2489)
  Directional -> Accuracy: 0.4915, MCC: 0.0000, F1: 0.6591

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.68657 | val 0.69197
  Epoch 011 - train 0.68007 | val 0.69207
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.71339 | val 0.72024
  Epoch 011 - train 0.71233 | val 0.72199
  Classification -> best τ=0.495 (val F1=0.1522)
  Directional -> Accuracy: 0.4828, MCC: -0.0065, F1: 0.0625

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...

[I 2026-02-22 09:21:50,867] Trial 47 finished with value: 0.07544325467233118 and parameters: {'feature_set': 'sector_emotion', 'model_type': 'BiLSTM', 'sequence_length': 6, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.4, 'dropout': 0.1, 'batch_size': 32, 'learning_rate': 1.1958749399065598e-06, 'weight_decay': 4.145095090431755e-06, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 0.963873439881506, 'early_stopping_min_delta': 0.008349463735183065}. Best is trial 22 with value: 0.2833350641483003.

  Epoch 010 - train 0.70462 | val 0.71478
  Epoch 011 - train 0.69801 | val 0.71310
  Classification -> best τ=0.510 (val F1=0.0426)
  Directional -> Accuracy: 0.5556, MCC: 0.1899, F1: 0.1250

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.07544325467233118
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d', 'sentiment']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.57231 | val 0.88004
  Epoch 011 - train 0.59079 | val 0.73007
  Classification -> best τ=0.425 (val F1=0.1635)
  Directional -> Accuracy: 0.6053, MCC: 0.2017, F1: 0.5588

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.45078 | val 0.92744
  Epoch 011 - train 0.41740 | val 0.84528
  Classification -> best τ=0.505 (val F1=0.2523)
  Directional -> Accuracy: 0.6444, MCC: 0.2960, F1: 0.6667

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.49600 | val 2.42689
  Epoch 011 - train 0.45908 | val 2.96016
  Classification -> best τ=0.725 (val F1=0.3114)
  Directional -> Accuracy: 0.4565, MCC: -0.0996, F1: 0.0741

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.57393 | val 0.90951
  Epoch 011 - train 0.60323 | val 0.89275
  Classification -> best τ=0.410 (val F1=0.1947)
  Directional -> Accuracy: 0.4595, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.50659 | val 0.78447
  Epoch 016 - train 0.36950 | val 0.83196
  Classification -> best τ=0.415 (val F1=0.4751)
  Directional -> Accuracy: 0.5400, MCC: 0.0746, F1: 0.5818

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.43120 | val 1.03222
  Epoch 011 - train 0.39539 | val 1.13411
  Classification -> best τ=0.570 (val F1=0.3776)
  Directional -> Accuracy: 0.5652, MCC: 0.1234, F1: 0.4444

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.58395 | val 1.23701
  Epoch 011 - train 0.54160 | val 1.24864
  Classification -> best τ=0.430 (val F1=0.2789)
  Directional -> Accuracy: 0.5294, MCC: 0.1704, F1: 0.5789

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.50582 | val 0.63644
  Epoch 017 - train 0.36052 | val 1.17908
  Classification -> best τ=0.320 (val F1=0.3855)
  Directional -> Accuracy: 0.5238, MCC: 0.1021, F1: 0.5652

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.55048 | val 1.63534
  Epoch 013 - train 0.47706 | val 1.41917
  Classification -> best τ=0.270 (val F1=0.2497)
  Directional -> Accuracy: 0.4375, MCC: 0.0000, F1: 0.6087

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.53783 | val 0.82429
  Epoch 011 - train 0.58117 | val 1.20693
  Classification -> best τ=0.285 (val F1=0.2361)
  Directional -> Accuracy: 0.4203, MCC: 0.0000, F1: 0.5918

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.49084 | val 1.24152
  Epoch 011 - train 0.47623 | val 1.17427
  Classification -> best τ=0.635 (val F1=0.3590)
  Directional -> Accuracy: 0.5918, MCC: 0.1804, F1: 0.2308

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.50084 | val 2.07149
  Epoch 012 - train 0.47398 | val 2.72396
  Classification -> best τ=0.335 (val F1=0.1512)
  Directional -> Accuracy: 0.5614, MCC: 0.1520, F1: 0.6753

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.49895 | val 1.68606
  Epoch 011 - train 0.49257 | val 1.20864
  Classification -> best τ=0.545 (val F1=0.1225)
  Directional -> Accuracy: 0.4524, MCC: -0.1972, F1: 0.1481

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.55841 | val 0.73502
  Epoch 011 - train 0.51637 | val 0.71943
  Classification -> best τ=0.445 (val F1=0.3387)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.47176 | val 0.93704
  Epoch 011 - train 0.44840 | val 1.15683
  Classification -> best τ=0.490 (val F1=0.0730)
  Directional -> Accuracy: 0.5294, MCC: 0.0497, F1: 0.4783

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.54090 | val 0.93140
  Epoch 011 - train 0.55098 | val 1.07829
  Classification -> best τ=0.445 (val F1=0.1240)
  Directional -> Accuracy: 0.5217, MCC: -0.0237, F1: 0.6667

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.54049 | val 1.32709
  Epoch 011 - train 0.47977 | val 1.58574
  Classification -> best τ=0.700 (val F1=0.2651)
  Directional -> Accuracy: 0.4310, MCC: 0.1826, F1: 0.1538

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.51061 | val 0.85631
  Epoch 011 - train 0.47448 | val 1.08295
  Classification -> best τ=0.575 (val F1=0.2220)
  Directional -> Accuracy: 0.4000, MCC: -0.0338, F1: 0.0426

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.51301 | val 1.32273
  Epoch 011 - train 0.50798 | val 0.87770
  Classification -> best τ=0.405 (val F1=0.2158)
  Directional -> Accuracy: 0.5312, MCC: 0.1556, F1: 0.4444

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.53196 | val 0.89583
  Epoch 012 - train 0.49310 | val 1.45976
  Classification -> best τ=0.535 (val F1=0.2246)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.47053 | val 1.09321
  Epoch 011 - train 0.42674 | val 1.26763
  Classification -> best τ=0.575 (val F1=0.2427)
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.57815 | val 0.72260
  Epoch 011 - train 0.50898 | val 0.73789
  Classification -> best τ=0.505 (val F1=0.2656)
  Directional -> Accuracy: 0.4923, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.58217 | val 0.79798
  Epoch 020 - train 0.31656 | val 0.75993
  Epoch 021 - train 0.28592 | val 0.80700
  Classification -> best τ=0.630 (val F1=0.4472)
  Directional -> Accuracy: 0.5789, MCC: 0.1512, F1: 0.7273

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.58294 | val 0.75649
  Epoch 012 - train 0.52686 | val 0.88214
  Classification -> best τ=0.540 (val F1=0.1565)
  Directional -> Accuracy: 0.4769, MCC: -0.0669, F1: 0.3462

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.47783 | val 0.96808
  Epoch 012 - train 0.41898 | val 1.22885
  Classification -> best τ=0.550 (val F1=0.4907)
  Directional -> Accuracy: 0.5455, MCC: 0.1641, F1: 0.4186

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.47950 | val 1.28746
  Epoch 011 - train 0.46519 | val 2.00242
  Classification -> best τ=0.560 (val F1=0.1310)
  Directional -> Accuracy: 0.4000, MCC: -0.1764, F1: 0.5714

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.52209 | val 0.78409
  Epoch 011 - train 0.50139 | val 0.69438
  Classification -> best τ=0.575 (val F1=0.0700)
  Directional -> Accuracy: 0.5476, MCC: 0.0446, F1: 0.6415

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.53466 | val 0.74610
  Epoch 018 - train 0.30504 | val 1.27732
  Classification -> best τ=0.275 (val F1=0.3408)
  Directional -> Accuracy: 0.4821, MCC: 0.0587, F1: 0.2564

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.42588 | val 3.11371
  Epoch 011 - train 0.40287 | val 3.50308
  Classification -> best τ=0.390 (val F1=0.3296)
  Directional -> Accuracy: 0.5500, MCC: 0.0503, F1: 0.6667

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.52358 | val 0.95609
  Epoch 013 - train 0.44845 | val 1.30457
  Classification -> best τ=0.655 (val F1=0.3501)
  Directional -> Accuracy: 0.5238, MCC: 0.0413, F1: 0.4737

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.56313 | val 0.64709
  Epoch 018 - train 0.29158 | val 0.94370
  Classification -> best τ=0.615 (val F1=0.3385)
  Directional -> Accuracy: 0.5476, MCC: 0.0535, F1: 0.6545

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.48171 | val 1.34905
  Epoch 011 - train 0.46448 | val 1.25461
  Classification -> best τ=0.505 (val F1=0.2609)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.54892 | val 0.86847
  Epoch 011 - train 0.55349 | val 0.85661
  Classification -> best τ=0.470 (val F1=0.2269)
  Directional -> Accuracy: 0.4444, MCC: 0.0000, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.48312 | val 0.98873
  Epoch 011 - train 0.44007 | val 1.08418
  Classification -> best τ=0.390 (val F1=0.2717)
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.56074 | val 1.56826
  Epoch 011 - train 0.52648 | val 1.49814
  Classification -> best τ=0.300 (val F1=0.3068)
  Directional -> Accuracy: 0.5758, MCC: 0.0000, F1: 0.7308

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.49063 | val 1.67112
  Epoch 012 - train 0.44251 | val 1.79028
  Classification -> best τ=0.505 (val F1=0.2228)
  Directional -> Accuracy: 0.6667, MCC: 0.3708, F1: 0.6111

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.49348 | val 0.86676
  Epoch 011 - train 0.44747 | val 0.99306
  Classification -> best τ=0.455 (val F1=0.2327)
  Directional -> Accuracy: 0.5000, MCC: 0.0051, F1: 0.5000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.39922 | val 1.25857
  Epoch 011 - train 0.38642 | val 1.96307
  Classification -> best τ=0.530 (val F1=0.4335)
  Directional -> Accuracy: 0.6087, MCC: 0.0000, F1: 0.7568

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.52071 | val 0.76910
  Epoch 011 - train 0.47922 | val 0.72813
  Classification -> best τ=0.540 (val F1=0.2955)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.52242 | val 1.38449
  Epoch 011 - train 0.47384 | val 1.36418
  Classification -> best τ=0.275 (val F1=0.2456)
  Directional -> Accuracy: 0.4865, MCC: 0.0000, F1: 0.6545

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.52562 | val 1.78134
  Epoch 012 - train 0.45272 | val 2.44055
  Classification -> best τ=0.455 (val F1=0.2582)
  Directional -> Accuracy: 0.5333, MCC: 0.1541, F1: 0.6866

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.45737 | val 1.83786
  Epoch 012 - train 0.37442 | val 1.63120
  Classification -> best τ=0.595 (val F1=0.3612)
  Directional -> Accuracy: 0.4762, MCC: 0.0323, F1: 0.3529

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.50211 | val 0.57355
  Epoch 019 - train 0.17512 | val 1.41148
  Classification -> best τ=0.615 (val F1=0.5671)
  Directional -> Accuracy: 0.4583, MCC: -0.0861, F1: 0.3810

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.55756 | val 0.85806
  Epoch 011 - train 0.52429 | val 0.99231
  Classification -> best τ=0.555 (val F1=0.1811)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.47060 | val 0.93877
  Epoch 012 - train 0.40999 | val 0.97557
  Classification -> best τ=0.550 (val F1=0.3633)
  Directional -> Accuracy: 0.5000, MCC: -0.0121, F1: 0.3913

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.54582 | val 1.04552
  Epoch 012 - train 0.50523 | val 1.46858
  Classification -> best τ=0.555 (val F1=0.2064)
  Directional -> Accuracy: 0.6038, MCC: 0.2068, F1: 0.6182

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.52081 | val 0.81355
  Epoch 011 - train 0.47196 | val 0.76563
  Classification -> best τ=0.490 (val F1=0.2292)
  Directional -> Accuracy: 0.4727, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.57883 | val 1.15703
  Epoch 011 - train 0.54578 | val 1.43255

[I 2026-02-22 09:22:51,293] Trial 48 finished with value: 0.27091026712504457 and parameters: {'feature_set': 'sector_sentiment', 'model_type': 'GRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 64, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.0, 'batch_size': 32, 'learning_rate': 0.006453706105051784, 'weight_decay': 6.400700565856998e-06, 'lr_patience': 5, 'lr_factor': 0.8, 'early_stopping_patience': 10, 'max_epochs': 50, 'huber_delta': 1.309501976144414, 'early_stopping_min_delta': 0.007911124064524247}. Best is trial 22 with value: 0.2833350641483003.

  Classification -> best τ=0.425 (val F1=0.1570)
  Directional -> Accuracy: 0.5167, MCC: 0.0408, F1: 0.5538

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.27091026712504457
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: classification
Sequence length: 30
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d', 'sentiment']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.44496 | val 2.04594
  Epoch 020 - train 0.14234 | val 3.57458
  Epoch 023 - train 0.05285 | val 3.73882
  Classification -> best τ=0.520 (val F1=0.1171)
  Directional -> Accuracy: 0.5600, MCC: 0.0854, F1: 0.3774

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 106). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.25934 | val 1.11657
  Epoch 020 - train 0.02027 | val 1.43260
  Epoch 029 - train 0.00424 | val 1.77000
  Classification -> best τ=0.285 (val F1=0.3148)
  Directional -> Accuracy: 0.6364, MCC: 0.2193, F1: 0.7576

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 106). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.25759 | val 2.38319
  Epoch 020 - train 0.03103 | val 4.94891
  Epoch 021 - train 0.03163 | val 4.89225
  Classification -> best τ=0.565 (val F1=0.2132)
  Directional -> Accuracy: 0.4667, MCC: -0.0144, F1: 0.0769

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.48388 | val 2.68510
  Epoch 020 - train 0.16387 | val 5.20016
  Epoch 022 - train 0.09092 | val 5.85154
  Classification -> best τ=0.525 (val F1=0.1524)
  Directional -> Accuracy: 0.4932, MCC: 0.1567, F1: 0.0976

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.37058 | val 0.91072
  Epoch 020 - train 0.06367 | val 1.98866
  Epoch 021 - train 0.04752 | val 1.82259
  Classification -> best τ=0.600 (val F1=0.3423)
  Directional -> Accuracy: 0.4694, MCC: -0.0624, F1: 0.2353

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.31425 | val 1.32646
  Epoch 020 - train 0.03325 | val 1.39913
  Epoch 023 - train 0.01235 | val 1.52021
  Classification -> best τ=0.500 (val F1=0.4176)
  Directional -> Accuracy: 0.5111, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.35562 | val 2.09161
  Epoch 020 - train 0.03777 | val 3.72087
  Epoch 022 - train 0.01580 | val 4.16257
  Classification -> best τ=0.340 (val F1=0.2611)
  Directional -> Accuracy: 0.4776, MCC: 0.1811, F1: 0.5977

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 106). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 106). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.31806 | val 1.38246
  Epoch 020 - train 0.02357 | val 2.63296
  Epoch 023 - train 0.00856 | val 2.15713
  Classification -> best τ=0.585 (val F1=0.3612)
  Directional -> Accuracy: 0.4390, MCC: -0.0278, F1: 0.5965

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.34653 | val 0.75507
  Epoch 020 - train 0.09038 | val 1.34020
  Epoch 026 - train 0.00971 | val 1.61245
  Classification -> best τ=0.645 (val F1=0.5024)
  Directional -> Accuracy: 0.5745, MCC: 0.1641, F1: 0.0909

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 106). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 106). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 106). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.34421 | val 2.44041
  Epoch 020 - train 0.04508 | val 5.15662
  Epoch 021 - train 0.03199 | val 5.45906
  Classification -> best τ=0.325 (val F1=0.1296)
  Directional -> Accuracy: 0.4265, MCC: 0.0000, F1: 0.5979

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.37838 | val 1.66416
  Epoch 020 - train 0.05378 | val 4.02289
  Epoch 021 - train 0.05227 | val 3.83430
  Classification -> best τ=0.515 (val F1=0.2711)
  Directional -> Accuracy: 0.5625, MCC: 0.1221, F1: 0.5333

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.34259 | val 1.28904
  Epoch 020 - train 0.06860 | val 3.04261
  Epoch 021 - train 0.06031 | val 3.09924
  Classification -> best τ=0.455 (val F1=0.1281)
  Directional -> Accuracy: 0.6250, MCC: 0.2966, F1: 0.7200

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 106). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.30750 | val 2.65184
  Epoch 020 - train 0.02146 | val 6.74217
  Epoch 021 - train 0.01483 | val 7.13234
  Classification -> best τ=0.555 (val F1=0.1639)
  Directional -> Accuracy: 0.4490, MCC: -0.1485, F1: 0.1818

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 106). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.37625 | val 0.73917
  Epoch 020 - train 0.03861 | val 1.26932
  Epoch 023 - train 0.01143 | val 1.30392
  Classification -> best τ=0.720 (val F1=0.3841)
  Directional -> Accuracy: 0.4915, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.33217 | val 0.78606
  Epoch 020 - train 0.06475 | val 1.34476
  Epoch 022 - train 0.03716 | val 1.39638
  Classification -> best τ=0.555 (val F1=0.2550)
  Directional -> Accuracy: 0.5600, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.44028 | val 1.29569
  Epoch 020 - train 0.16345 | val 2.84724
  Epoch 021 - train 0.10502 | val 3.09675
  Classification -> best τ=0.395 (val F1=0.1982)
  Directional -> Accuracy: 0.5147, MCC: -0.0398, F1: 0.6667

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 106). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.40466 | val 2.03024
  Epoch 020 - train 0.10612 | val 4.26670
  Epoch 021 - train 0.06556 | val 4.47212
  Classification -> best τ=0.625 (val F1=0.0614)
  Directional -> Accuracy: 0.5088, MCC: 0.2051, F1: 0.3913

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.34468 | val 2.11108
  Epoch 020 - train 0.06519 | val 4.22254
  Epoch 021 - train 0.05204 | val 4.94787
  Classification -> best τ=0.380 (val F1=0.2228)
  Directional -> Accuracy: 0.5270, MCC: -0.1129, F1: 0.6729

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.40261 | val 2.23822
  Epoch 020 - train 0.03731 | val 5.19039
  Epoch 021 - train 0.03749 | val 5.48005
  Classification -> best τ=0.445 (val F1=0.1752)
  Directional -> Accuracy: 0.5556, MCC: 0.2191, F1: 0.4815

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 106). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.47684 | val 0.99841
  Epoch 020 - train 0.15198 | val 1.26267
  Epoch 024 - train 0.05911 | val 1.64999
  Classification -> best τ=0.560 (val F1=0.3912)
  Directional -> Accuracy: 0.5342, MCC: 0.2305, F1: 0.2917

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.25673 | val 2.15539
  Epoch 020 - train 0.02513 | val 3.75506
  Epoch 021 - train 0.01984 | val 4.15564
  Classification -> best τ=0.435 (val F1=0.2041)
  Directional -> Accuracy: 0.4565, MCC: 0.2118, F1: 0.1935

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 106). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 106). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 106). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.37287 | val 1.19105
  Epoch 020 - train 0.04554 | val 2.67396
  Epoch 021 - train 0.03799 | val 2.86581
  Classification -> best τ=0.375 (val F1=0.1986)
  Directional -> Accuracy: 0.5469, MCC: 0.1747, F1: 0.2162

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.32814 | val 3.11823
  Epoch 020 - train 0.05920 | val 6.70783
  Epoch 021 - train 0.03647 | val 6.92726
  Classification -> best τ=0.635 (val F1=0.3495)
  Directional -> Accuracy: 0.5536, MCC: 0.0933, F1: 0.6032

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.42508 | val 1.22554
  Epoch 020 - train 0.10267 | val 4.00884
  Epoch 021 - train 0.06163 | val 3.48871
  Classification -> best τ=0.525 (val F1=0.1341)
  Directional -> Accuracy: 0.5938, MCC: 0.1808, F1: 0.4348

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.34758 | val 1.97381
  Epoch 020 - train 0.03999 | val 4.47662
  Epoch 021 - train 0.02892 | val 4.64332
  Classification -> best τ=0.545 (val F1=0.4328)
  Directional -> Accuracy: 0.5185, MCC: 0.1163, F1: 0.3158

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.33279 | val 1.37290
  Epoch 020 - train 0.08948 | val 2.44411
  Epoch 021 - train 0.08674 | val 2.63267
  Classification -> best τ=0.455 (val F1=0.2160)
  Directional -> Accuracy: 0.4186, MCC: 0.0000, F1: 0.5902

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.33686 | val 0.74660
  Epoch 020 - train 0.05453 | val 2.00836
  Epoch 021 - train 0.05313 | val 1.75581
  Classification -> best τ=0.575 (val F1=0.2044)
  Directional -> Accuracy: 0.4082, MCC: 0.0000, F1: 0.0000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.44320 | val 1.37081
  Epoch 020 - train 0.06661 | val 3.57456
  Epoch 023 - train 0.04213 | val 4.02811
  Classification -> best τ=0.530 (val F1=0.2291)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.22169 | val 0.89394
  Epoch 020 - train 0.06559 | val 2.17824
  Epoch 024 - train 0.04327 | val 2.62178
  Classification -> best τ=0.445 (val F1=0.2550)
  Directional -> Accuracy: 0.5263, MCC: -0.0180, F1: 0.6538

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.34983 | val 0.98640
  Epoch 020 - train 0.07444 | val 1.85188
  Epoch 024 - train 0.02477 | val 1.66908
  Classification -> best τ=0.590 (val F1=0.3402)
  Directional -> Accuracy: 0.4634, MCC: -0.0738, F1: 0.4500

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.22145 | val 1.75015
  Epoch 020 - train 0.01621 | val 2.76918
  Epoch 021 - train 0.01506 | val 2.91495
  Classification -> best τ=0.550 (val F1=0.1336)
  Directional -> Accuracy: 0.4390, MCC: -0.1803, F1: 0.5490

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.33551 | val 1.24750
  Epoch 020 - train 0.02790 | val 3.22213
  Epoch 021 - train 0.02292 | val 3.30710
  Classification -> best τ=0.595 (val F1=0.2382)
  Directional -> Accuracy: 0.4792, MCC: 0.0000, F1: 0.0000

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.45021 | val 1.60027
  Epoch 020 - train 0.12402 | val 3.21329
  Epoch 021 - train 0.07141 | val 2.83933
  Classification -> best τ=0.220 (val F1=0.2277)
  Directional -> Accuracy: 0.5493, MCC: 0.1049, F1: 0.5676

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 106). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.38269 | val 0.84570
  Epoch 020 - train 0.02636 | val 2.07020
  Epoch 024 - train 0.00832 | val 2.66009
  Classification -> best τ=0.205 (val F1=0.2675)
  Directional -> Accuracy: 0.4048, MCC: -0.2132, F1: 0.2857

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for PCG (101 < 106). Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.44718 | val 1.23760
  Epoch 020 - train 0.12981 | val 1.61095
  Epoch 021 - train 0.12071 | val 1.83424
  Classification -> best τ=0.245 (val F1=0.3577)
  Directional -> Accuracy: 0.5846, MCC: 0.2029, F1: 0.5714

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.22084 | val 1.30450
  Epoch 020 - train 0.01697 | val 2.46127
  Epoch 021 - train 0.01995 | val 2.39436
  Classification -> best τ=0.450 (val F1=0.3475)
  Directional -> Accuracy: 0.6750, MCC: 0.3472, F1: 0.6977

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.30506 | val 2.63304
  Epoch 020 - train 0.03637 | val 5.89622
  Epoch 021 - train 0.02193 | val 5.80455
  Classification -> best τ=0.435 (val F1=0.2544)
  Directional -> Accuracy: 0.5818, MCC: 0.2311, F1: 0.6462

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.30158 | val 2.08717
  Epoch 020 - train 0.04554 | val 2.76691
  Epoch 022 - train 0.03154 | val 3.34239
  Classification -> best τ=0.575 (val F1=0.3031)
  Directional -> Accuracy: 0.4667, MCC: 0.0553, F1: 0.4000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 106). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 106). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 106). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 106). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.38024 | val 0.74664
  Epoch 020 - train 0.07507 | val 1.31196
  Epoch 027 - train 0.02034 | val 1.85907
  Classification -> best τ=0.585 (val F1=0.4548)
  Directional -> Accuracy: 0.3261, MCC: 0.0000, F1: 0.4918

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 106). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 106). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 106). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.33434 | val 2.49804
  Epoch 020 - train 0.12160 | val 5.07090
  Epoch 021 - train 0.07168 | val 5.14579
  Classification -> best τ=0.335 (val F1=0.1656)
  Directional -> Accuracy: 0.4932, MCC: 0.0000, F1: 0.6606

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 106). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 106). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 106). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 106). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.29875 | val 1.03054
  Epoch 020 - train 0.02259 | val 2.90638
  Epoch 021 - train 0.01540 | val 2.92339
  Classification -> best τ=0.500 (val F1=0.4714)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.34121 | val 1.14014
  Epoch 020 - train 0.06616 | val 1.73764
  Epoch 022 - train 0.04990 | val 1.78164
  Classification -> best τ=0.585 (val F1=0.3568)
  Directional -> Accuracy: 0.5122, MCC: 0.0840, F1: 0.4737

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.33145 | val 0.86980
  Epoch 020 - train 0.03636 | val 1.45373
  Epoch 021 - train 0.02037 | val 1.44817
  Classification -> best τ=0.415 (val F1=0.0608)
  Directional -> Accuracy: 0.3696, MCC: 0.0000, F1: 0.5397

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.38553 | val 2.47386
  Epoch 020 - train 0.06672 | val 7.99015
  Epoch 021 - train 0.05536 | val 8.45515
  Classification -> best τ=0.500 (val F1=0.2011)
  Directional -> Accuracy: 0.4444, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.29251 | val 4.06434
  Epoch 020 - train 0.01434 | val 9.31811
  Epoch 021 - train 0.00938 | val 9.47914
  Classification -> best τ=0.710 (val F1=0.4152)
  Directional -> Accuracy: 0.5455, MCC: 0.1273, F1: 0.6479

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.41539 | val 0.77910
  Epoch 020 - train 0.04996 | val 1.15877
  Epoch 022 - train 0.02897 | val 1.55858
  Classification -> best τ=0.555 (val F1=0.2345)
  Directional -> Accuracy: 0.5962, MCC: 0.1960, F1: 0.6316

[87/88] Processing WMT...


[I 2026-02-22 09:24:07,552] Trial 49 finished with value: 0.2670831585700942 and parameters: {'feature_set': 'sector_sentiment', 'model_type': 'GRU', 'sequence_length': 30, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 64, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.2, 'batch_size': 32, 'learning_rate': 0.006195149697780072, 'weight_decay': 5.753548604522471e-06, 'lr_patience': 5, 'lr_factor': 0.8, 'early_stopping_patience': 20, 'max_epochs': 50, 'huber_delta': 1.766510887134789, 'early_stopping_min_delta': 0.007461742968753907}. Best is trial 22 with value: 0.2833350641483003.

  Classification -> best τ=0.460 (val F1=0.3870)
  Directional -> Accuracy: 0.5085, MCC: 0.0586, F1: 0.6133

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2670831585700942
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: classification
Sequence length: 36
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d', 'sentiment']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.51791 | val 1.01528
  Epoch 011 - train 0.51177 | val 0.85031
  Classification -> best τ=0.485 (val F1=0.1829)
  Directional -> Accuracy: 0.5946, MCC: 0.2033, F1: 0.5946

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 112). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.49563 | val 1.52609
  Epoch 011 - train 0.46160 | val 1.39885
  Classification -> best τ=0.430 (val F1=0.2582)
  Directional -> Accuracy: 0.6047, MCC: 0.0000, F1: 0.7536

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for AEP (109 < 112). Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 112). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.47561 | val 1.77149
  Epoch 011 - train 0.46573 | val 2.22482
  Classification -> best τ=0.570 (val F1=0.2890)
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.55664 | val 0.90207
  Epoch 011 - train 0.53506 | val 0.77004
  Classification -> best τ=0.415 (val F1=0.2712)
  Directional -> Accuracy: 0.5417, MCC: 0.0141, F1: 0.6972

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.42014 | val 1.09395
  Epoch 011 - train 0.38714 | val 1.15332
  Classification -> best τ=0.485 (val F1=0.3724)
  Directional -> Accuracy: 0.6458, MCC: 0.3612, F1: 0.5405

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.43448 | val 0.90632
  Epoch 011 - train 0.39952 | val 0.94102
  Classification -> best τ=0.540 (val F1=0.2738)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.3125

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.53536 | val 0.71551
  Epoch 011 - train 0.52895 | val 1.29391
  Classification -> best τ=0.485 (val F1=0.2513)
  Directional -> Accuracy: 0.5909, MCC: 0.2154, F1: 0.5846

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 112). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 112). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.50204 | val 1.07257
  Epoch 011 - train 0.47746 | val 1.28683
  Classification -> best τ=0.500 (val F1=0.0727)
  Directional -> Accuracy: 0.4359, MCC: 0.0000, F1: 0.6071

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.49996 | val 1.21981
  Epoch 011 - train 0.50127 | val 1.45827
  Classification -> best τ=0.540 (val F1=0.2729)
  Directional -> Accuracy: 0.4130, MCC: -0.1700, F1: 0.5846

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 112). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 112). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 112). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.52079 | val 0.87292
  Epoch 011 - train 0.46606 | val 0.89172
  Classification -> best τ=0.460 (val F1=0.2037)
  Directional -> Accuracy: 0.4328, MCC: -0.0711, F1: 0.5000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.46724 | val 1.08254
  Epoch 011 - train 0.43454 | val 1.30743
  Classification -> best τ=0.490 (val F1=0.1469)
  Directional -> Accuracy: 0.5532, MCC: 0.0626, F1: 0.3636

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.47810 | val 1.84966
  Epoch 011 - train 0.43790 | val 1.84364
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5273, MCC: 0.0000, F1: 0.6905

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 112). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.43579 | val 1.45951
  Epoch 011 - train 0.42581 | val 1.54380
  Classification -> best τ=0.480 (val F1=0.2020)
  Directional -> Accuracy: 0.4167, MCC: -0.1631, F1: 0.5000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 112). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.52748 | val 0.98684
  Epoch 013 - train 0.47614 | val 1.48413
  Classification -> best τ=0.305 (val F1=0.2791)
  Directional -> Accuracy: 0.5517, MCC: 0.1202, F1: 0.4800

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.52486 | val 0.74190
  Epoch 012 - train 0.53402 | val 1.05925
  Classification -> best τ=0.555 (val F1=0.1487)
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.51595 | val 1.07095
  Epoch 011 - train 0.48850 | val 1.29250
  Classification -> best τ=0.445 (val F1=0.2287)
  Directional -> Accuracy: 0.5970, MCC: 0.2331, F1: 0.7216

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 112). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.53939 | val 2.31475
  Epoch 011 - train 0.52513 | val 2.73779
  Classification -> best τ=0.410 (val F1=0.1941)
  Directional -> Accuracy: 0.5714, MCC: 0.0255, F1: 0.6923

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.50416 | val 1.04005
  Epoch 011 - train 0.48824 | val 1.02250
  Classification -> best τ=0.500 (val F1=0.1829)
  Directional -> Accuracy: 0.4110, MCC: -0.0542, F1: 0.1224

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.49452 | val 0.97280
  Epoch 011 - train 0.45547 | val 1.08521
  Classification -> best τ=0.410 (val F1=0.2483)
  Directional -> Accuracy: 0.5484, MCC: 0.1521, F1: 0.5172

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 112). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.48619 | val 0.91776
  Epoch 012 - train 0.43312 | val 0.88608
  Classification -> best τ=0.305 (val F1=0.2443)
  Directional -> Accuracy: 0.5556, MCC: 0.0000, F1: 0.7143

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.44010 | val 1.29802
  Epoch 011 - train 0.45095 | val 1.58962
  Classification -> best τ=0.555 (val F1=0.1929)
  Directional -> Accuracy: 0.4444, MCC: 0.0534, F1: 0.2424

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 112). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 112). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 112). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.50774 | val 0.72735
  Epoch 016 - train 0.31811 | val 0.84478
  Classification -> best τ=0.440 (val F1=0.3269)
  Directional -> Accuracy: 0.5397, MCC: 0.0790, F1: 0.4314

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.48681 | val 2.23372
  Epoch 011 - train 0.48192 | val 2.57618
  Classification -> best τ=0.660 (val F1=0.2659)
  Directional -> Accuracy: 0.4545, MCC: 0.0955, F1: 0.1667

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.49881 | val 1.49952
  Epoch 011 - train 0.49335 | val 1.93639
  Classification -> best τ=0.435 (val F1=0.1217)
  Directional -> Accuracy: 0.5238, MCC: 0.1037, F1: 0.6341

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.49329 | val 0.89213
  Epoch 014 - train 0.38847 | val 1.32243
  Classification -> best τ=0.515 (val F1=0.4354)
  Directional -> Accuracy: 0.5660, MCC: 0.2449, F1: 0.4103

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.50465 | val 1.03918
  Epoch 011 - train 0.49621 | val 1.22922
  Classification -> best τ=0.490 (val F1=0.3327)
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.51833 | val 0.90812
  Epoch 011 - train 0.50170 | val 0.93351
  Classification -> best τ=0.470 (val F1=0.1086)
  Directional -> Accuracy: 0.5208, MCC: 0.0213, F1: 0.5818

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.48241 | val 0.94037
  Epoch 013 - train 0.46252 | val 1.09414
  Classification -> best τ=0.360 (val F1=0.2345)
  Directional -> Accuracy: 0.5000, MCC: 0.1821, F1: 0.1290

[49/88] Processing MDT...

Processing MDT (Healthcare)...
Insufficient data for proper time series validation for MDT. Skipping...

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.47412 | val 1.96949
  Epoch 011 - train 0.47385 | val 1.54369
  Classification -> best τ=0.530 (val F1=0.0667)
  Directional -> Accuracy: 0.5500, MCC: 0.1005, F1: 0.5263

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.52298 | val 0.96175
  Epoch 011 - train 0.49976 | val 0.85040
  Classification -> best τ=0.510 (val F1=0.0303)
  Directional -> Accuracy: 0.5500, MCC: 0.0000, F1: 0.7097

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.49177 | val 0.76131
  Epoch 013 - train 0.40202 | val 0.81206
  Classification -> best τ=0.475 (val F1=0.3415)
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.50509 | val 0.82671
  Epoch 011 - train 0.48286 | val 0.93098
  Classification -> best τ=0.440 (val F1=0.2879)
  Directional -> Accuracy: 0.5714, MCC: 0.0919, F1: 0.6875

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 112). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.51109 | val 1.13968
  Epoch 011 - train 0.49037 | val 1.06629
  Classification -> best τ=0.475 (val F1=0.2576)
  Directional -> Accuracy: 0.4694, MCC: 0.0000, F1: 0.6389

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for PCG (101 < 112). Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.50314 | val 1.16118
  Epoch 011 - train 0.48025 | val 1.42392
  Classification -> best τ=0.335 (val F1=0.3587)
  Directional -> Accuracy: 0.5938, MCC: 0.1489, F1: 0.6829

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.43224 | val 1.20970
  Epoch 013 - train 0.36933 | val 1.29394
  Classification -> best τ=0.460 (val F1=0.4419)
  Directional -> Accuracy: 0.5918, MCC: 0.1853, F1: 0.6000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.47746 | val 1.30893
  Epoch 011 - train 0.44113 | val 1.46203
  Classification -> best τ=0.520 (val F1=0.2648)
  Directional -> Accuracy: 0.4815, MCC: 0.1275, F1: 0.6410

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.46865 | val 1.86448
  Epoch 011 - train 0.40466 | val 1.86101
  Classification -> best τ=0.525 (val F1=0.1922)
  Directional -> Accuracy: 0.3864, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 112). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for PPL (108 < 112). Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 112). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 112). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 112). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.51901 | val 0.81020
  Epoch 011 - train 0.52005 | val 0.77785
  Classification -> best τ=0.480 (val F1=0.3237)
  Directional -> Accuracy: 0.6222, MCC: 0.0411, F1: 0.2609

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 112). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 112). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 112). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.45388 | val 1.52199
  Epoch 011 - train 0.42988 | val 1.74366
  Classification -> best τ=0.440 (val F1=0.2657)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 112). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 112). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 112). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 112). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.48460 | val 0.75270
  Epoch 016 - train 0.41236 | val 0.98641
  Classification -> best τ=0.620 (val F1=0.3954)
  Directional -> Accuracy: 0.6047, MCC: 0.2379, F1: 0.5143

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.49008 | val 0.82707
  Epoch 011 - train 0.46908 | val 0.84834
  Classification -> best τ=0.505 (val F1=0.2267)
  Directional -> Accuracy: 0.6154, MCC: 0.1843, F1: 0.6939

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.49325 | val 1.01661
  Epoch 011 - train 0.47825 | val 0.98550
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.3778, MCC: 0.0000, F1: 0.5484

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.52358 | val 0.89668
  Epoch 011 - train 0.52900 | val 0.88812
  Classification -> best τ=0.550 (val F1=0.2127)
  Directional -> Accuracy: 0.4528, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.46874 | val 2.71131
  Epoch 011 - train 0.43926 | val 2.77153
  Classification -> best τ=0.560 (val F1=0.2750)
  Directional -> Accuracy: 0.5185, MCC: 0.0639, F1: 0.6579

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.54478 | val 1.01688
  Epoch 011 - train 0.52008 | val 1.08417
  Classification -> best τ=0.510 (val F1=0.2758)
  Directional -> Accuracy: 0.5686, MCC: 0.1369, F1: 0.5600

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.51649 | val 1.82478
  Epoch 011 - train 0.50247 | val 1.22993
  Classification -> best τ=0.545 (val F1=0.3546)
  Directional -> Accuracy: 0.5094, MCC: 0.0113, F1: 0.6061

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.53165 | val 1.58368
  Epoch 011 - train 0.50331 | val 1.25109

[I 2026-02-22 09:25:24,625] Trial 50 finished with value: 0.23379258593204671 and parameters: {'feature_set': 'sector_sentiment', 'model_type': 'GRU', 'sequence_length': 36, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 64, 'num_layers': 2, 'inter_rnn_drop': 0.1, 'dropout': 0.0, 'batch_size': 32, 'learning_rate': 0.0021935033099888027, 'weight_decay': 1.7700313453310945e-06, 'lr_patience': 5, 'lr_factor': 0.8, 'early_stopping_patience': 10, 'max_epochs': 50, 'huber_delta': 1.2675967714122798, 'early_stopping_min_delta': 0.007995069873841703}. Best is trial 22 with value: 0.2833350641483003.

  Classification -> best τ=0.415 (val F1=0.0755)
  Directional -> Accuracy: 0.3966, MCC: -0.2005, F1: 0.5070

================================================================================
Pipeline completed: 47/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (47, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.23379258593204671
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: classification
Sequence length: 30
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d', 'sentiment']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.48123 | val 0.92831
  Epoch 020 - train 0.16580 | val 1.34431
  Epoch 024 - train 0.06895 | val 1.89895
  Classification -> best τ=0.520 (val F1=0.2989)
  Directional -> Accuracy: 0.5733, MCC: 0.1312, F1: 0.5000

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 106). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.29118 | val 1.13715
  Epoch 020 - train 0.06461 | val 1.26835
  Epoch 021 - train 0.04025 | val 1.29588
  Classification -> best τ=0.465 (val F1=0.1329)
  Directional -> Accuracy: 0.5909, MCC: 0.0000, F1: 0.7429

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 106). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.32893 | val 2.91652
  Epoch 020 - train 0.04354 | val 5.86692
  Epoch 022 - train 0.05040 | val 6.40201
  Classification -> best τ=0.595 (val F1=0.3026)
  Directional -> Accuracy: 0.4889, MCC: 0.1410, F1: 0.0800

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.50095 | val 1.37890
  Epoch 020 - train 0.17189 | val 4.70031
  Epoch 022 - train 0.13756 | val 4.13634
  Classification -> best τ=0.380 (val F1=0.1565)
  Directional -> Accuracy: 0.4795, MCC: -0.0206, F1: 0.4062

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.33109 | val 1.26083
  Epoch 020 - train 0.03559 | val 2.00038
  Epoch 022 - train 0.02759 | val 2.50010
  Classification -> best τ=0.550 (val F1=0.3837)
  Directional -> Accuracy: 0.6327, MCC: 0.2965, F1: 0.5500

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.33566 | val 2.26095
  Epoch 020 - train 0.10351 | val 4.12825
  Epoch 021 - train 0.06526 | val 3.99100
  Classification -> best τ=0.605 (val F1=0.2294)
  Directional -> Accuracy: 0.5111, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.49803 | val 1.26373
  Epoch 020 - train 0.07011 | val 3.05101
  Epoch 022 - train 0.07289 | val 3.51253
  Classification -> best τ=0.540 (val F1=0.1793)
  Directional -> Accuracy: 0.5373, MCC: 0.0442, F1: 0.4364

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 106). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 106). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.35588 | val 0.77657
  Epoch 020 - train 0.05434 | val 1.84217
  Epoch 025 - train 0.01320 | val 2.17173
  Classification -> best τ=0.585 (val F1=0.2041)
  Directional -> Accuracy: 0.4878, MCC: 0.2003, F1: 0.6316

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.45932 | val 0.91676
  Epoch 020 - train 0.09134 | val 2.04723
  Epoch 024 - train 0.03449 | val 1.81979
  Classification -> best τ=0.525 (val F1=0.3687)
  Directional -> Accuracy: 0.6383, MCC: 0.2648, F1: 0.4516

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 106). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 106). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 106). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.38963 | val 2.33540
  Epoch 020 - train 0.09650 | val 5.54391
  Epoch 021 - train 0.06122 | val 5.60447
  Classification -> best τ=0.410 (val F1=0.1361)
  Directional -> Accuracy: 0.3971, MCC: -0.1466, F1: 0.5393

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.41129 | val 1.69702
  Epoch 020 - train 0.10434 | val 2.20115
  Epoch 022 - train 0.05233 | val 2.92697
  Classification -> best τ=0.610 (val F1=0.2944)
  Directional -> Accuracy: 0.5833, MCC: 0.1459, F1: 0.3750

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.36055 | val 1.37055
  Epoch 020 - train 0.09421 | val 3.09355
  Epoch 021 - train 0.08754 | val 2.79318
  Classification -> best τ=0.435 (val F1=0.2067)
  Directional -> Accuracy: 0.6071, MCC: 0.2313, F1: 0.6944

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 106). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.38536 | val 2.40257
  Epoch 020 - train 0.09800 | val 6.49677
  Epoch 022 - train 0.04263 | val 6.69413
  Classification -> best τ=0.485 (val F1=0.1655)
  Directional -> Accuracy: 0.4694, MCC: -0.0661, F1: 0.4091

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 106). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.38962 | val 0.87605
  Epoch 020 - train 0.05079 | val 1.82135
  Epoch 021 - train 0.03674 | val 1.78098
  Classification -> best τ=0.560 (val F1=0.3628)
  Directional -> Accuracy: 0.4915, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.40597 | val 1.04431
  Epoch 020 - train 0.09575 | val 2.36135
  Epoch 022 - train 0.06967 | val 2.56071
  Classification -> best τ=0.530 (val F1=0.2550)
  Directional -> Accuracy: 0.5600, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.50851 | val 0.87858
  Epoch 020 - train 0.16781 | val 2.80588
  Epoch 022 - train 0.10293 | val 2.73131
  Classification -> best τ=0.540 (val F1=0.2819)
  Directional -> Accuracy: 0.5588, MCC: 0.1117, F1: 0.5946

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 106). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.43188 | val 2.33803
  Epoch 020 - train 0.15822 | val 3.63716
  Epoch 021 - train 0.10498 | val 4.07007
  Classification -> best τ=0.500 (val F1=0.2335)
  Directional -> Accuracy: 0.6140, MCC: 0.0000, F1: 0.7609

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.34898 | val 2.29197
  Epoch 020 - train 0.11136 | val 4.55337
  Epoch 021 - train 0.09687 | val 5.70045
  Classification -> best τ=0.615 (val F1=0.1895)
  Directional -> Accuracy: 0.4054, MCC: -0.1173, F1: 0.3125

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.45283 | val 1.11792
  Epoch 020 - train 0.10519 | val 3.04084
  Epoch 021 - train 0.07230 | val 3.22387
  Classification -> best τ=0.545 (val F1=0.1372)
  Directional -> Accuracy: 0.4762, MCC: 0.0994, F1: 0.2979

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 106). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.41485 | val 0.87800
  Epoch 020 - train 0.20757 | val 1.60683
  Epoch 021 - train 0.16204 | val 1.66566
  Classification -> best τ=0.460 (val F1=0.2785)
  Directional -> Accuracy: 0.4521, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.33280 | val 3.28233
  Epoch 020 - train 0.02175 | val 4.65874
  Epoch 021 - train 0.02437 | val 4.54556
  Classification -> best τ=0.455 (val F1=0.2041)
  Directional -> Accuracy: 0.3913, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 106). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 106). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 106). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.35494 | val 1.24789
  Epoch 020 - train 0.05726 | val 2.57123
  Epoch 021 - train 0.05062 | val 2.70314
  Classification -> best τ=0.425 (val F1=0.1195)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0588

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.41036 | val 2.43046
  Epoch 020 - train 0.07201 | val 4.22004
  Epoch 021 - train 0.04949 | val 4.78891
  Classification -> best τ=0.840 (val F1=0.3131)
  Directional -> Accuracy: 0.5536, MCC: 0.2807, F1: 0.3902

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.39965 | val 1.81554
  Epoch 020 - train 0.12234 | val 3.01356
  Epoch 021 - train 0.09644 | val 3.28168
  Classification -> best τ=0.600 (val F1=0.1341)
  Directional -> Accuracy: 0.5938, MCC: 0.1846, F1: 0.4091

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.36256 | val 1.73091
  Epoch 020 - train 0.07877 | val 4.00467
  Epoch 021 - train 0.07665 | val 3.71523
  Classification -> best τ=0.620 (val F1=0.3669)
  Directional -> Accuracy: 0.5000, MCC: 0.0736, F1: 0.2703

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.37282 | val 1.54870
  Epoch 020 - train 0.09561 | val 2.29892
  Epoch 021 - train 0.09911 | val 2.75935
  Classification -> best τ=0.560 (val F1=0.2254)
  Directional -> Accuracy: 0.4186, MCC: -0.1027, F1: 0.4898

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.33251 | val 0.79910
  Epoch 020 - train 0.07970 | val 1.06318
  Epoch 021 - train 0.05794 | val 1.22045
  Classification -> best τ=0.555 (val F1=0.0878)
  Directional -> Accuracy: 0.4694, MCC: 0.1428, F1: 0.2353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.44188 | val 1.12564
  Epoch 020 - train 0.15469 | val 2.10565
  Epoch 023 - train 0.08349 | val 2.45770
  Classification -> best τ=0.430 (val F1=0.2557)
  Directional -> Accuracy: 0.4727, MCC: 0.1242, F1: 0.0645

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.27583 | val 0.79428
  Epoch 020 - train 0.10378 | val 0.84133
  Epoch 021 - train 0.08994 | val 0.87303
  Classification -> best τ=0.510 (val F1=0.1288)
  Directional -> Accuracy: 0.5263, MCC: 0.0769, F1: 0.5000

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.39656 | val 1.73007
  Epoch 020 - train 0.09160 | val 3.07934
  Epoch 021 - train 0.07051 | val 3.23938
  Classification -> best τ=0.525 (val F1=0.1863)
  Directional -> Accuracy: 0.5366, MCC: 0.0853, F1: 0.5957

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.31722 | val 1.89568
  Epoch 020 - train 0.05160 | val 3.84605
  Epoch 021 - train 0.04298 | val 3.93490
  Classification -> best τ=0.660 (val F1=0.0297)
  Directional -> Accuracy: 0.3659, MCC: -0.2620, F1: 0.3810

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.34097 | val 1.21906
  Epoch 020 - train 0.03588 | val 3.31708
  Epoch 021 - train 0.02895 | val 3.28585
  Classification -> best τ=0.630 (val F1=0.2382)
  Directional -> Accuracy: 0.5000, MCC: 0.1399, F1: 0.0769

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.42589 | val 1.35298
  Epoch 020 - train 0.10215 | val 2.70600
  Epoch 021 - train 0.07982 | val 3.03179
  Classification -> best τ=0.210 (val F1=0.2565)
  Directional -> Accuracy: 0.4930, MCC: -0.0160, F1: 0.5263

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 106). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.54343 | val 1.00580
  Epoch 020 - train 0.07484 | val 2.21690
  Epoch 025 - train 0.01010 | val 2.37613
  Classification -> best τ=0.250 (val F1=0.2287)
  Directional -> Accuracy: 0.5000, MCC: 0.0258, F1: 0.5882

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for PCG (101 < 106). Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.46174 | val 0.97885
  Epoch 020 - train 0.16572 | val 1.50139
  Epoch 022 - train 0.11424 | val 1.79479
  Classification -> best τ=0.420 (val F1=0.3029)
  Directional -> Accuracy: 0.4769, MCC: 0.1914, F1: 0.1500

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.28605 | val 1.23584
  Epoch 020 - train 0.01711 | val 2.05093
  Epoch 021 - train 0.01558 | val 2.09235
  Classification -> best τ=0.455 (val F1=0.2887)
  Directional -> Accuracy: 0.6250, MCC: 0.2453, F1: 0.6667

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.32960 | val 1.83150
  Epoch 020 - train 0.04281 | val 4.15770
  Epoch 021 - train 0.02375 | val 4.08893
  Classification -> best τ=0.375 (val F1=0.2494)
  Directional -> Accuracy: 0.4727, MCC: -0.0215, F1: 0.5397

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.31414 | val 2.96275
  Epoch 020 - train 0.09645 | val 5.08552
  Epoch 021 - train 0.07854 | val 5.47625
  Classification -> best τ=0.570 (val F1=0.3714)
  Directional -> Accuracy: 0.6222, MCC: 0.0000, F1: 0.7671

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 106). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 106). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 106). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 106). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.44532 | val 0.82875
  Epoch 020 - train 0.11318 | val 1.70114
  Epoch 027 - train 0.01605 | val 1.80502
  Classification -> best τ=0.555 (val F1=0.4548)
  Directional -> Accuracy: 0.3261, MCC: 0.0000, F1: 0.4918

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 106). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 106). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 106). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.39837 | val 2.89891
  Epoch 020 - train 0.12254 | val 5.76092
  Epoch 022 - train 0.08396 | val 5.89745
  Classification -> best τ=0.235 (val F1=0.2157)
  Directional -> Accuracy: 0.4932, MCC: 0.0000, F1: 0.6606

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 106). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 106). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 106). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 106). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.30715 | val 0.81143
  Epoch 020 - train 0.05062 | val 2.22968
  Epoch 023 - train 0.01630 | val 2.35430
  Classification -> best τ=0.525 (val F1=0.4152)
  Directional -> Accuracy: 0.6818, MCC: 0.3780, F1: 0.7200

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.37231 | val 0.91903
  Epoch 020 - train 0.13285 | val 1.19125
  Epoch 021 - train 0.11451 | val 1.26629
  Classification -> best τ=0.605 (val F1=0.2467)
  Directional -> Accuracy: 0.4634, MCC: 0.0683, F1: 0.2667

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.31457 | val 0.79145
  Epoch 020 - train 0.05919 | val 1.11153
  Epoch 022 - train 0.04584 | val 1.54233
  Classification -> best τ=0.520 (val F1=0.4306)
  Directional -> Accuracy: 0.3696, MCC: 0.0000, F1: 0.5397

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.39292 | val 2.60713
  Epoch 020 - train 0.09838 | val 6.72244
  Epoch 022 - train 0.04770 | val 7.71394
  Classification -> best τ=0.605 (val F1=0.2011)
  Directional -> Accuracy: 0.4444, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.34675 | val 3.59206
  Epoch 020 - train 0.01988 | val 7.89698
  Epoch 021 - train 0.01158 | val 8.32024
  Classification -> best τ=0.585 (val F1=0.4021)
  Directional -> Accuracy: 0.5636, MCC: 0.1564, F1: 0.6471

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.44977 | val 1.31689
  Epoch 020 - train 0.06774 | val 2.12745
  Epoch 023 - train 0.07990 | val 2.54104
  Classification -> best τ=0.630 (val F1=0.2685)
  Directional -> Accuracy: 0.5962, MCC: 0.1925, F1: 0.5882

[87/88] Processing WMT...


[I 2026-02-22 09:26:48,676] Trial 51 finished with value: 0.24911863766603334 and parameters: {'feature_set': 'sector_sentiment', 'model_type': 'GRU', 'sequence_length': 30, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 64, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.30000000000000004, 'batch_size': 32, 'learning_rate': 0.00637011836918718, 'weight_decay': 6.161915307931161e-06, 'lr_patience': 5, 'lr_factor': 0.8, 'early_stopping_patience': 20, 'max_epochs': 50, 'huber_delta': 1.7513966231937053, 'early_stopping_min_delta': 0.007553615753347742}. Best is trial 22 with value: 0.2833350641483003.

  Classification -> best τ=0.355 (val F1=0.3428)
  Directional -> Accuracy: 0.5085, MCC: 0.0352, F1: 0.5672

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.24911863766603334
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: classification
Sequence length: 36
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d', 'sentiment']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.47871 | val 0.90544
  Epoch 020 - train 0.08498 | val 2.16973
  Epoch 021 - train 0.05098 | val 2.22162
  Classification -> best τ=0.490 (val F1=0.2444)
  Directional -> Accuracy: 0.5000, MCC: 0.0651, F1: 0.5843

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 112). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.33793 | val 1.81701
  Epoch 020 - train 0.06914 | val 2.09286
  Epoch 021 - train 0.06069 | val 2.21482
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.6047, MCC: 0.0000, F1: 0.7536

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for AEP (109 < 112). Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 112). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.31140 | val 2.17111
  Epoch 020 - train 0.03565 | val 5.45145
  Epoch 021 - train 0.04084 | val 5.86640
  Classification -> best τ=0.560 (val F1=0.3327)
  Directional -> Accuracy: 0.5000, MCC: 0.0424, F1: 0.2667

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.46866 | val 1.76990
  Epoch 020 - train 0.15782 | val 1.35673
  Epoch 025 - train 0.05404 | val 2.08966
  Classification -> best τ=0.415 (val F1=0.2569)
  Directional -> Accuracy: 0.4722, MCC: -0.0086, F1: 0.2963

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.33416 | val 1.23430
  Epoch 020 - train 0.05050 | val 2.05939
  Epoch 023 - train 0.02048 | val 2.13216
  Classification -> best τ=0.620 (val F1=0.3496)
  Directional -> Accuracy: 0.5000, MCC: 0.0754, F1: 0.1429

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.27863 | val 1.58280
  Epoch 020 - train 0.06514 | val 3.97187
  Epoch 021 - train 0.05277 | val 4.67835
  Classification -> best τ=0.375 (val F1=0.1993)
  Directional -> Accuracy: 0.5227, MCC: 0.0459, F1: 0.4878

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.40355 | val 0.73462
  Epoch 020 - train 0.05591 | val 1.35380
  Epoch 021 - train 0.04193 | val 1.63436
  Classification -> best τ=0.545 (val F1=0.2264)
  Directional -> Accuracy: 0.5758, MCC: 0.0835, F1: 0.3913

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 112). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 112). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.23633 | val 2.91584
  Epoch 020 - train 0.01846 | val 5.46046
  Epoch 021 - train 0.01537 | val 5.74305
  Classification -> best τ=0.680 (val F1=0.2582)
  Directional -> Accuracy: 0.4872, MCC: 0.0624, F1: 0.5833

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.32134 | val 1.06206
  Epoch 020 - train 0.06340 | val 2.11701
  Epoch 021 - train 0.04703 | val 2.02021
  Classification -> best τ=0.550 (val F1=0.3586)
  Directional -> Accuracy: 0.6739, MCC: 0.3610, F1: 0.4444

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 112). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 112). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 112). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.43357 | val 0.75191
  Epoch 020 - train 0.10504 | val 0.83039
  Epoch 030 - train 0.01007 | val 1.75329
  Epoch 032 - train 0.00671 | val 1.95786
  Classification -> best τ=0.800 (val F1=0.2824)
  Directional -> Accuracy: 0.4478, MCC: -0.1409, F1: 0.3273

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.37742 | val 1.04386
  Epoch 020 - train 0.04854 | val 3.21698
  Epoch 022 - train 0.03919 | val 2.99344
  Classification -> best τ=0.515 (val F1=0.3559)
  Directional -> Accuracy: 0.5106, MCC: 0.1713, F1: 0.6349

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.33639 | val 1.32673
  Epoch 020 - train 0.04539 | val 3.20502
  Epoch 021 - train 0.04037 | val 3.06808
  Classification -> best τ=0.460 (val F1=0.1386)
  Directional -> Accuracy: 0.5273, MCC: 0.0000, F1: 0.6905

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 112). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.31038 | val 1.71975
  Epoch 020 - train 0.03812 | val 5.95350
  Epoch 021 - train 0.03843 | val 5.93805
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4792, MCC: 0.0000, F1: 0.6479

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 112). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.41404 | val 1.45357
  Epoch 020 - train 0.05349 | val 3.16911
  Epoch 021 - train 0.03634 | val 3.40868
  Classification -> best τ=0.450 (val F1=0.2574)
  Directional -> Accuracy: 0.5517, MCC: 0.1527, F1: 0.3810

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.34218 | val 4.47576
  Epoch 020 - train 0.06988 | val 9.48365
  Epoch 021 - train 0.08634 | val 9.24111
  Classification -> best τ=0.490 (val F1=0.2612)
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.48454 | val 2.15215
  Epoch 020 - train 0.10490 | val 2.77092
  Epoch 021 - train 0.06719 | val 3.07018
  Classification -> best τ=0.650 (val F1=0.2073)
  Directional -> Accuracy: 0.4627, MCC: -0.0131, F1: 0.0526

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 112). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.38800 | val 4.23618
  Epoch 020 - train 0.05423 | val 9.27529
  Epoch 021 - train 0.04201 | val 9.38549
  Classification -> best τ=0.715 (val F1=0.1874)
  Directional -> Accuracy: 0.3929, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.43060 | val 1.32758
  Epoch 020 - train 0.08473 | val 2.45289
  Epoch 021 - train 0.04536 | val 2.83093
  Classification -> best τ=0.490 (val F1=0.2178)
  Directional -> Accuracy: 0.4110, MCC: -0.0304, F1: 0.0444

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.41559 | val 1.96727
  Epoch 020 - train 0.11520 | val 5.01258
  Epoch 021 - train 0.07182 | val 5.37509
  Classification -> best τ=0.545 (val F1=0.2345)
  Directional -> Accuracy: 0.4516, MCC: 0.0571, F1: 0.1905

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 112). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.45651 | val 1.15962
  Epoch 020 - train 0.15087 | val 1.75905
  Epoch 022 - train 0.10265 | val 1.75613
  Classification -> best τ=0.530 (val F1=0.3671)
  Directional -> Accuracy: 0.4444, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.29422 | val 2.01950
  Epoch 020 - train 0.03871 | val 3.75228
  Epoch 022 - train 0.01884 | val 4.98909
  Classification -> best τ=0.530 (val F1=0.2794)
  Directional -> Accuracy: 0.4000, MCC: -0.0638, F1: 0.1290

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 112). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 112). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 112). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.33512 | val 1.08532
  Epoch 020 - train 0.03415 | val 2.21055
  Epoch 021 - train 0.01847 | val 2.35873
  Classification -> best τ=0.430 (val F1=0.2345)
  Directional -> Accuracy: 0.5079, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.32312 | val 2.33934
  Epoch 020 - train 0.01383 | val 3.49987
  Epoch 021 - train 0.01268 | val 3.79287
  Classification -> best τ=0.540 (val F1=0.2446)
  Directional -> Accuracy: 0.6182, MCC: 0.1730, F1: 0.7342

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.35435 | val 2.26182
  Epoch 020 - train 0.04171 | val 4.36540
  Epoch 021 - train 0.03240 | val 5.15647
  Classification -> best τ=0.335 (val F1=0.2405)
  Directional -> Accuracy: 0.4762, MCC: 0.0000, F1: 0.6452

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.37915 | val 1.53942
  Epoch 020 - train 0.05782 | val 2.22600
  Epoch 022 - train 0.03947 | val 2.06933
  Classification -> best τ=0.560 (val F1=0.4023)
  Directional -> Accuracy: 0.5094, MCC: 0.1639, F1: 0.2353

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.35459 | val 1.22558
  Epoch 020 - train 0.07392 | val 2.01212
  Epoch 021 - train 0.05407 | val 2.15000
  Classification -> best τ=0.465 (val F1=0.0679)
  Directional -> Accuracy: 0.4048, MCC: -0.1340, F1: 0.5098

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.30652 | val 2.41401
  Epoch 020 - train 0.04471 | val 2.16264
  Epoch 021 - train 0.03764 | val 2.62327
  Classification -> best τ=0.505 (val F1=0.2133)
  Directional -> Accuracy: 0.5625, MCC: 0.1841, F1: 0.5333

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.50694 | val 1.65815
  Epoch 020 - train 0.07421 | val 2.38890
  Epoch 021 - train 0.05767 | val 2.61617
  Classification -> best τ=0.485 (val F1=0.2925)
  Directional -> Accuracy: 0.4630, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
Insufficient data for proper time series validation for MDT. Skipping...

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.41629 | val 1.45081
  Epoch 020 - train 0.03162 | val 1.62253
  Epoch 021 - train 0.02900 | val 1.94374
  Classification -> best τ=0.500 (val F1=0.2277)
  Directional -> Accuracy: 0.4750, MCC: -0.0501, F1: 0.4878

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.24168 | val 1.19087
  Epoch 020 - train 0.01072 | val 2.24050
  Epoch 021 - train 0.01322 | val 2.43848
  Classification -> best τ=0.585 (val F1=0.1300)
  Directional -> Accuracy: 0.5750, MCC: 0.1677, F1: 0.5641

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.43215 | val 0.84733
  Epoch 020 - train 0.02408 | val 1.80496
  Epoch 023 - train 0.00984 | val 1.99581
  Classification -> best τ=0.455 (val F1=0.3130)
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.41055 | val 0.92098
  Epoch 020 - train 0.05855 | val 1.58737
  Epoch 021 - train 0.04411 | val 1.67582
  Classification -> best τ=0.435 (val F1=0.2615)
  Directional -> Accuracy: 0.5143, MCC: 0.1300, F1: 0.3462

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 112). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.34956 | val 1.48002
  Epoch 020 - train 0.01800 | val 4.20284
  Epoch 021 - train 0.01706 | val 4.06586
  Classification -> best τ=0.425 (val F1=0.3015)
  Directional -> Accuracy: 0.4694, MCC: 0.0000, F1: 0.6389

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for PCG (101 < 112). Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.43177 | val 1.34789
  Epoch 020 - train 0.06257 | val 3.67500
  Epoch 021 - train 0.05087 | val 3.64814
  Classification -> best τ=0.360 (val F1=0.3021)
  Directional -> Accuracy: 0.6094, MCC: 0.2515, F1: 0.7423

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.18792 | val 1.12086
  Epoch 020 - train 0.02702 | val 2.22127
  Epoch 021 - train 0.02033 | val 2.35467
  Classification -> best τ=0.385 (val F1=0.4419)
  Directional -> Accuracy: 0.6122, MCC: 0.2322, F1: 0.6415

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.40206 | val 1.61211
  Epoch 020 - train 0.07361 | val 4.22669
  Epoch 021 - train 0.04681 | val 4.60760
  Classification -> best τ=0.520 (val F1=0.2225)
  Directional -> Accuracy: 0.5741, MCC: 0.2103, F1: 0.6462

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.32072 | val 2.05273
  Epoch 020 - train 0.04642 | val 3.62582
  Epoch 021 - train 0.04186 | val 3.81656
  Classification -> best τ=0.420 (val F1=0.2841)
  Directional -> Accuracy: 0.5682, MCC: 0.0592, F1: 0.6667

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 112). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for PPL (108 < 112). Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 112). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 112). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 112). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.34236 | val 1.34269
  Epoch 020 - train 0.03389 | val 3.68708
  Epoch 025 - train 0.04063 | val 3.42341
  Classification -> best τ=0.370 (val F1=0.3464)
  Directional -> Accuracy: 0.3111, MCC: -0.2132, F1: 0.4746

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 112). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 112). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 112). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.39025 | val 2.32454
  Epoch 020 - train 0.14451 | val 4.69817
  Epoch 021 - train 0.08490 | val 4.47207
  Classification -> best τ=0.270 (val F1=0.2299)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 112). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 112). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 112). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 112). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.32349 | val 1.40515
  Epoch 020 - train 0.02682 | val 3.75133
  Epoch 021 - train 0.01576 | val 3.91248
  Classification -> best τ=0.565 (val F1=0.1981)
  Directional -> Accuracy: 0.5814, MCC: 0.1930, F1: 0.4706

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.34775 | val 1.01951
  Epoch 020 - train 0.03513 | val 1.50645
  Epoch 021 - train 0.03809 | val 1.57352
  Classification -> best τ=0.500 (val F1=0.1457)
  Directional -> Accuracy: 0.4359, MCC: 0.0080, F1: 0.2143

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.31255 | val 1.12869
  Epoch 020 - train 0.06772 | val 1.92722
  Epoch 021 - train 0.04751 | val 1.92449
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.3778, MCC: 0.0000, F1: 0.5484

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.38097 | val 1.51149
  Epoch 020 - train 0.06028 | val 2.32584
  Epoch 021 - train 0.07106 | val 2.34790
  Classification -> best τ=0.540 (val F1=0.2070)
  Directional -> Accuracy: 0.5094, MCC: 0.0244, F1: 0.5185

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.28143 | val 2.65166
  Epoch 020 - train 0.00709 | val 8.58045
  Epoch 021 - train 0.00560 | val 8.82060
  Classification -> best τ=0.575 (val F1=0.2681)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6494

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.37982 | val 2.03722
  Epoch 020 - train 0.04163 | val 6.55729
  Epoch 022 - train 0.03233 | val 7.63058
  Classification -> best τ=0.485 (val F1=0.1824)
  Directional -> Accuracy: 0.5882, MCC: 0.2281, F1: 0.6769

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.35529 | val 1.74347
  Epoch 020 - train 0.01799 | val 4.70540
  Epoch 021 - train 0.01739 | val 4.88368

[I 2026-02-22 09:28:21,668] Trial 52 finished with value: 0.23855950419671237 and parameters: {'feature_set': 'sector_sentiment', 'model_type': 'GRU', 'sequence_length': 36, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 64, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.2, 'batch_size': 32, 'learning_rate': 0.006278168973606209, 'weight_decay': 3.36713030883481e-06, 'lr_patience': 5, 'lr_factor': 0.8, 'early_stopping_patience': 20, 'max_epochs': 50, 'huber_delta': 1.9008283040755716, 'early_stopping_min_delta': 0.008229372522126048}. Best is trial 22 with value: 0.2833350641483003.

  Classification -> best τ=0.465 (val F1=0.2986)
  Directional -> Accuracy: 0.5345, MCC: 0.1515, F1: 0.6400

================================================================================
Pipeline completed: 47/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (47, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.23855950419671237
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: classification
Sequence length: 30
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d', 'sentiment']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.40863 | val 0.86556
  Epoch 020 - train 0.13571 | val 1.43597
  Epoch 021 - train 0.13135 | val 1.71803
  Classification -> best τ=0.460 (val F1=0.1939)
  Directional -> Accuracy: 0.5600, MCC: 0.1491, F1: 0.5926

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 106). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.28521 | val 0.86005
  Epoch 020 - train 0.06121 | val 2.25653
  Epoch 021 - train 0.05075 | val 2.02681
  Classification -> best τ=0.495 (val F1=0.0649)
  Directional -> Accuracy: 0.7273, MCC: 0.4312, F1: 0.8000

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 106). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.28015 | val 2.07050
  Epoch 020 - train 0.05617 | val 2.96090
  Epoch 021 - train 0.03979 | val 3.02953
  Classification -> best τ=0.645 (val F1=0.3086)
  Directional -> Accuracy: 0.4667, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.45869 | val 2.61728
  Epoch 020 - train 0.20191 | val 4.30967
  Epoch 022 - train 0.10604 | val 3.81633
  Classification -> best τ=0.375 (val F1=0.2651)
  Directional -> Accuracy: 0.5479, MCC: 0.0971, F1: 0.5600

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.32599 | val 1.16223
  Epoch 020 - train 0.01783 | val 2.42491
  Epoch 024 - train 0.00990 | val 2.85350
  Classification -> best τ=0.685 (val F1=0.1940)
  Directional -> Accuracy: 0.5306, MCC: 0.1169, F1: 0.2581

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.30803 | val 2.76635
  Epoch 020 - train 0.07626 | val 4.92131
  Epoch 021 - train 0.07056 | val 5.22603
  Classification -> best τ=0.565 (val F1=0.2294)
  Directional -> Accuracy: 0.5111, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.40781 | val 1.69265
  Epoch 020 - train 0.05673 | val 3.96675
  Epoch 021 - train 0.04275 | val 4.22308
  Classification -> best τ=0.500 (val F1=0.1793)
  Directional -> Accuracy: 0.5224, MCC: 0.0192, F1: 0.4286

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 106). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 106). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.29063 | val 2.75992
  Epoch 020 - train 0.03271 | val 3.51575
  Epoch 022 - train 0.01674 | val 4.05144
  Classification -> best τ=0.560 (val F1=0.3612)
  Directional -> Accuracy: 0.4878, MCC: 0.0025, F1: 0.5116

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.33859 | val 1.57225
  Epoch 020 - train 0.11021 | val 2.67457
  Epoch 022 - train 0.06196 | val 2.89769
  Classification -> best τ=0.530 (val F1=0.3904)
  Directional -> Accuracy: 0.4255, MCC: -0.1641, F1: 0.5970

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 106). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 106). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 106). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.36963 | val 3.31480
  Epoch 020 - train 0.06749 | val 7.57988
  Epoch 021 - train 0.07331 | val 7.55632
  Classification -> best τ=0.415 (val F1=0.2300)
  Directional -> Accuracy: 0.4265, MCC: 0.0000, F1: 0.5979

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.31395 | val 2.25665
  Epoch 020 - train 0.07413 | val 2.54679
  Epoch 022 - train 0.04249 | val 3.51895
  Classification -> best τ=0.645 (val F1=0.2994)
  Directional -> Accuracy: 0.6250, MCC: 0.2845, F1: 0.3571

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.34871 | val 2.53422
  Epoch 020 - train 0.10549 | val 3.89190
  Epoch 021 - train 0.06535 | val 3.77310
  Classification -> best τ=0.680 (val F1=0.0174)
  Directional -> Accuracy: 0.5357, MCC: 0.1768, F1: 0.2353

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 106). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.27466 | val 2.98240
  Epoch 020 - train 0.04363 | val 8.09173
  Epoch 021 - train 0.04271 | val 7.89563
  Classification -> best τ=0.385 (val F1=0.2788)
  Directional -> Accuracy: 0.6122, MCC: 0.2470, F1: 0.6667

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 106). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.32278 | val 1.04094
  Epoch 020 - train 0.02339 | val 1.49789
  Epoch 022 - train 0.01228 | val 1.60952
  Classification -> best τ=0.540 (val F1=0.4093)
  Directional -> Accuracy: 0.4915, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.32967 | val 1.11959
  Epoch 020 - train 0.06714 | val 1.77870
  Epoch 021 - train 0.05640 | val 1.69070
  Classification -> best τ=0.595 (val F1=0.2550)
  Directional -> Accuracy: 0.5600, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.48081 | val 0.98911
  Epoch 020 - train 0.09266 | val 2.27544
  Epoch 023 - train 0.04336 | val 2.35834
  Classification -> best τ=0.395 (val F1=0.2526)
  Directional -> Accuracy: 0.5735, MCC: 0.1654, F1: 0.7010

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 106). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.38407 | val 1.69175
  Epoch 020 - train 0.10350 | val 2.23150
  Epoch 021 - train 0.08855 | val 2.25236
  Classification -> best τ=0.700 (val F1=0.2335)
  Directional -> Accuracy: 0.3860, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.32808 | val 1.91332
  Epoch 020 - train 0.07126 | val 4.06027
  Epoch 021 - train 0.05456 | val 4.50342
  Classification -> best τ=0.545 (val F1=0.1895)
  Directional -> Accuracy: 0.4054, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.37265 | val 2.63047
  Epoch 020 - train 0.05227 | val 4.73951
  Epoch 021 - train 0.03428 | val 4.67072
  Classification -> best τ=0.410 (val F1=0.2149)
  Directional -> Accuracy: 0.5238, MCC: 0.1658, F1: 0.4231

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 106). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.41672 | val 0.94539
  Epoch 020 - train 0.12605 | val 2.18749
  Epoch 022 - train 0.06997 | val 2.32618
  Classification -> best τ=0.560 (val F1=0.2985)
  Directional -> Accuracy: 0.4521, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.27988 | val 1.73247
  Epoch 020 - train 0.03220 | val 4.57647
  Epoch 021 - train 0.02546 | val 4.71742
  Classification -> best τ=0.465 (val F1=0.2496)
  Directional -> Accuracy: 0.5000, MCC: -0.0393, F1: 0.5818

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 106). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 106). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 106). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.29625 | val 1.69119
  Epoch 020 - train 0.03460 | val 3.26006
  Epoch 021 - train 0.02956 | val 3.43975
  Classification -> best τ=0.430 (val F1=0.1264)
  Directional -> Accuracy: 0.5469, MCC: 0.1747, F1: 0.2162

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.31802 | val 2.35088
  Epoch 020 - train 0.07148 | val 4.37424
  Epoch 021 - train 0.03959 | val 4.25940
  Classification -> best τ=0.710 (val F1=0.3062)
  Directional -> Accuracy: 0.5179, MCC: 0.1009, F1: 0.4490

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.38240 | val 1.23076
  Epoch 020 - train 0.10440 | val 1.77583
  Epoch 021 - train 0.06463 | val 1.98523
  Classification -> best τ=0.335 (val F1=0.1687)
  Directional -> Accuracy: 0.4688, MCC: 0.0000, F1: 0.6383

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.33039 | val 3.21049
  Epoch 020 - train 0.06653 | val 6.72597
  Epoch 021 - train 0.04469 | val 6.83507
  Classification -> best τ=0.560 (val F1=0.4005)
  Directional -> Accuracy: 0.4630, MCC: -0.0263, F1: 0.1714

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.31202 | val 1.46940
  Epoch 020 - train 0.07793 | val 2.15299
  Epoch 021 - train 0.06162 | val 2.27210
  Classification -> best τ=0.620 (val F1=0.1852)
  Directional -> Accuracy: 0.3721, MCC: -0.3533, F1: 0.1290

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.33322 | val 1.09322
  Epoch 020 - train 0.06837 | val 3.53976
  Epoch 022 - train 0.04835 | val 3.46630
  Classification -> best τ=0.520 (val F1=0.1426)
  Directional -> Accuracy: 0.4286, MCC: 0.1199, F1: 0.0667

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.38732 | val 1.22343
  Epoch 020 - train 0.11984 | val 1.98474
  Epoch 021 - train 0.09267 | val 2.09878
  Classification -> best τ=0.445 (val F1=0.2036)
  Directional -> Accuracy: 0.5455, MCC: 0.2064, F1: 0.3590

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.30195 | val 0.81991
  Epoch 020 - train 0.10934 | val 1.26755
  Epoch 021 - train 0.09006 | val 1.20160
  Classification -> best τ=0.510 (val F1=0.3708)
  Directional -> Accuracy: 0.6053, MCC: 0.2088, F1: 0.7273

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.33643 | val 1.19804
  Epoch 020 - train 0.07270 | val 1.61025
  Epoch 021 - train 0.05416 | val 1.63831
  Classification -> best τ=0.520 (val F1=0.2706)
  Directional -> Accuracy: 0.5366, MCC: 0.0716, F1: 0.5128

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.32219 | val 1.57741
  Epoch 020 - train 0.03160 | val 3.25469
  Epoch 022 - train 0.02024 | val 3.24706
  Classification -> best τ=0.675 (val F1=0.0877)
  Directional -> Accuracy: 0.3902, MCC: -0.1871, F1: 0.2857

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.33358 | val 1.39572
  Epoch 020 - train 0.05170 | val 2.94257
  Epoch 021 - train 0.03997 | val 2.99852
  Classification -> best τ=0.695 (val F1=0.2382)
  Directional -> Accuracy: 0.5000, MCC: 0.1399, F1: 0.0769

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.37360 | val 1.24709
  Epoch 020 - train 0.06823 | val 3.19557
  Epoch 021 - train 0.05956 | val 3.06308
  Classification -> best τ=0.505 (val F1=0.2254)
  Directional -> Accuracy: 0.4366, MCC: 0.0000, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 106). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.31707 | val 1.24490
  Epoch 020 - train 0.05266 | val 2.59715
  Epoch 021 - train 0.03330 | val 2.59411
  Classification -> best τ=0.435 (val F1=0.2287)
  Directional -> Accuracy: 0.5476, MCC: 0.0830, F1: 0.3448

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for PCG (101 < 106). Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.41731 | val 1.08604
  Epoch 020 - train 0.16125 | val 1.97641
  Epoch 021 - train 0.11270 | val 2.10396
  Classification -> best τ=0.350 (val F1=0.3234)
  Directional -> Accuracy: 0.5846, MCC: 0.3339, F1: 0.4490

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.24523 | val 1.20398
  Epoch 020 - train 0.04729 | val 2.00170
  Epoch 021 - train 0.03939 | val 2.01658
  Classification -> best τ=0.420 (val F1=0.2582)
  Directional -> Accuracy: 0.5750, MCC: 0.1502, F1: 0.6792

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.33473 | val 1.58701
  Epoch 020 - train 0.04362 | val 2.28280
  Epoch 021 - train 0.03393 | val 2.42877
  Classification -> best τ=0.430 (val F1=0.2494)
  Directional -> Accuracy: 0.5273, MCC: 0.0920, F1: 0.5806

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.28293 | val 3.10835
  Epoch 020 - train 0.05621 | val 4.37723
  Epoch 021 - train 0.03812 | val 5.11005
  Classification -> best τ=0.660 (val F1=0.2903)
  Directional -> Accuracy: 0.3778, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 106). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 106). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 106). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 106). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.39378 | val 0.83011
  Epoch 020 - train 0.08664 | val 1.86391
  Epoch 026 - train 0.02778 | val 2.11525
  Classification -> best τ=0.750 (val F1=0.3721)
  Directional -> Accuracy: 0.3478, MCC: 0.1037, F1: 0.5000

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 106). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 106). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 106). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.36076 | val 2.67668
  Epoch 020 - train 0.09989 | val 5.58730
  Epoch 021 - train 0.08972 | val 5.68384
  Classification -> best τ=0.360 (val F1=0.2464)
  Directional -> Accuracy: 0.4932, MCC: 0.0000, F1: 0.6606

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 106). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 106). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 106). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 106). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.28648 | val 1.02180
  Epoch 020 - train 0.02757 | val 2.78681
  Epoch 025 - train 0.01251 | val 2.78749
  Classification -> best τ=0.540 (val F1=0.4086)
  Directional -> Accuracy: 0.5227, MCC: 0.0716, F1: 0.6557

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.38342 | val 0.86721
  Epoch 020 - train 0.09672 | val 1.14656
  Epoch 021 - train 0.06728 | val 1.22044
  Classification -> best τ=0.525 (val F1=0.0707)
  Directional -> Accuracy: 0.5122, MCC: 0.0462, F1: 0.5238

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.32258 | val 0.72022
  Epoch 020 - train 0.08767 | val 1.01402
  Epoch 021 - train 0.06775 | val 0.97296
  Classification -> best τ=0.495 (val F1=0.2928)
  Directional -> Accuracy: 0.3696, MCC: 0.0000, F1: 0.5397

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.38586 | val 2.52128
  Epoch 020 - train 0.11543 | val 6.62942
  Epoch 021 - train 0.09720 | val 7.27718
  Classification -> best τ=0.540 (val F1=0.1626)
  Directional -> Accuracy: 0.4444, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.28521 | val 3.94926
  Epoch 020 - train 0.01870 | val 6.92378
  Epoch 021 - train 0.01718 | val 7.06862
  Classification -> best τ=0.610 (val F1=0.4021)
  Directional -> Accuracy: 0.5091, MCC: 0.1336, F1: 0.6667

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.33472 | val 1.07783
  Epoch 020 - train 0.05324 | val 3.08626
  Epoch 022 - train 0.03329 | val 2.96713
  Classification -> best τ=0.585 (val F1=0.2729)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0714

[87/88] Processing WMT...

Processing WMT (Services)...

[I 2026-02-22 09:29:42,934] Trial 53 finished with value: 0.24444360844977778 and parameters: {'feature_set': 'sector_sentiment', 'model_type': 'GRU', 'sequence_length': 30, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 64, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.1, 'batch_size': 32, 'learning_rate': 0.0035248517030470727, 'weight_decay': 5.84266669654151e-06, 'lr_patience': 5, 'lr_factor': 0.8, 'early_stopping_patience': 20, 'max_epochs': 50, 'huber_delta': 1.667962928146258, 'early_stopping_min_delta': 0.007008659225920545}. Best is trial 22 with value: 0.2833350641483003.

  Epoch 020 - train 0.10542 | val 2.35285
  Epoch 021 - train 0.08973 | val 2.21712
  Classification -> best τ=0.415 (val F1=0.1479)
  Directional -> Accuracy: 0.4915, MCC: -0.0269, F1: 0.4231

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.24444360844977778
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d', 'sentiment']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.42389 | val 0.96794
  Epoch 020 - train 0.06862 | val 1.92360
  Epoch 022 - train 0.02774 | val 3.04664
  Classification -> best τ=0.560 (val F1=0.2510)
  Directional -> Accuracy: 0.5526, MCC: 0.0000, F1: 0.0000

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.24160 | val 0.98903
  Epoch 020 - train 0.01776 | val 1.45710
  Epoch 021 - train 0.01230 | val 1.55599
  Classification -> best τ=0.495 (val F1=0.2523)
  Directional -> Accuracy: 0.6000, MCC: 0.1419, F1: 0.7000

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.25849 | val 4.23660
  Epoch 020 - train 0.02343 | val 5.87600
  Epoch 022 - train 0.01547 | val 6.17465
  Classification -> best τ=0.690 (val F1=0.2861)
  Directional -> Accuracy: 0.4783, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.42033 | val 1.03156
  Epoch 020 - train 0.07385 | val 2.38264
  Epoch 021 - train 0.04334 | val 2.38598
  Classification -> best τ=0.450 (val F1=0.1269)
  Directional -> Accuracy: 0.5405, MCC: 0.0000, F1: 0.7018

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.23919 | val 1.67509
  Epoch 020 - train 0.00400 | val 2.15230
  Epoch 022 - train 0.00282 | val 2.22484
  Classification -> best τ=0.610 (val F1=0.3724)
  Directional -> Accuracy: 0.5000, MCC: 0.1373, F1: 0.0741

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.24766 | val 2.39416
  Epoch 020 - train 0.01328 | val 4.31205
  Epoch 021 - train 0.00837 | val 4.30827
  Classification -> best τ=0.600 (val F1=0.2739)
  Directional -> Accuracy: 0.5217, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.39469 | val 1.31818
  Epoch 020 - train 0.03100 | val 3.32175
  Epoch 022 - train 0.01170 | val 3.41958
  Classification -> best τ=0.305 (val F1=0.1981)
  Directional -> Accuracy: 0.3971, MCC: 0.0000, F1: 0.5684

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.26202 | val 0.89877
  Epoch 020 - train 0.01611 | val 1.54593
  Epoch 021 - train 0.01192 | val 1.68055
  Classification -> best τ=0.290 (val F1=0.1657)
  Directional -> Accuracy: 0.5000, MCC: -0.1698, F1: 0.0870

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.29389 | val 1.49474
  Epoch 020 - train 0.02201 | val 4.03634
  Epoch 023 - train 0.00565 | val 4.60787
  Classification -> best τ=0.490 (val F1=0.3959)
  Directional -> Accuracy: 0.5625, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.35712 | val 2.74862
  Epoch 020 - train 0.02653 | val 4.02990
  Epoch 021 - train 0.01424 | val 4.36703
  Classification -> best τ=0.275 (val F1=0.3590)
  Directional -> Accuracy: 0.4783, MCC: 0.2112, F1: 0.6170

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.35064 | val 1.99595
  Epoch 020 - train 0.00987 | val 3.39754
  Epoch 021 - train 0.00764 | val 3.47022
  Classification -> best τ=0.470 (val F1=0.2661)
  Directional -> Accuracy: 0.5306, MCC: 0.0921, F1: 0.5660

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.32385 | val 2.91396
  Epoch 020 - train 0.04083 | val 3.71846
  Epoch 021 - train 0.02680 | val 4.17897
  Classification -> best τ=0.410 (val F1=0.1707)
  Directional -> Accuracy: 0.5789, MCC: 0.1570, F1: 0.6000

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.26186 | val 2.89822
  Epoch 020 - train 0.01019 | val 6.49158
  Epoch 021 - train 0.00997 | val 6.75275
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.6230

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.34927 | val 1.02382
  Epoch 020 - train 0.00540 | val 1.78261
  Epoch 023 - train 0.00263 | val 1.87576
  Classification -> best τ=0.505 (val F1=0.4109)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.26904 | val 0.94351
  Epoch 020 - train 0.01024 | val 1.83058
  Epoch 022 - train 0.00578 | val 1.85200
  Classification -> best τ=0.575 (val F1=0.2078)
  Directional -> Accuracy: 0.5490, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.30761 | val 2.82319
  Epoch 020 - train 0.01268 | val 4.10290
  Epoch 022 - train 0.00582 | val 4.22185
  Classification -> best τ=0.250 (val F1=0.1512)
  Directional -> Accuracy: 0.5507, MCC: 0.1304, F1: 0.7048

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.37808 | val 2.22870
  Epoch 020 - train 0.03798 | val 5.30456
  Epoch 021 - train 0.02691 | val 5.71743
  Classification -> best τ=0.505 (val F1=0.1529)
  Directional -> Accuracy: 0.5517, MCC: -0.0258, F1: 0.6750

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.31686 | val 1.29681
  Epoch 020 - train 0.03923 | val 2.89948
  Epoch 022 - train 0.01862 | val 2.95498
  Classification -> best τ=0.675 (val F1=0.1909)
  Directional -> Accuracy: 0.4000, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.38255 | val 1.99258
  Epoch 020 - train 0.02731 | val 3.14238
  Epoch 021 - train 0.01981 | val 3.41198
  Classification -> best τ=0.365 (val F1=0.2166)
  Directional -> Accuracy: 0.5469, MCC: 0.1825, F1: 0.4727

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.39152 | val 0.87841
  Epoch 020 - train 0.08430 | val 1.92271
  Epoch 023 - train 0.04940 | val 2.37075
  Classification -> best τ=0.405 (val F1=0.3185)
  Directional -> Accuracy: 0.3649, MCC: -0.2595, F1: 0.3562

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.23441 | val 1.61067
  Epoch 020 - train 0.00864 | val 4.74771
  Epoch 021 - train 0.00679 | val 4.87713
  Classification -> best τ=0.495 (val F1=0.1340)
  Directional -> Accuracy: 0.4255, MCC: -0.0406, F1: 0.3415

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.34193 | val 1.28921
  Epoch 020 - train 0.01615 | val 2.79169
  Epoch 022 - train 0.01125 | val 2.89881
  Classification -> best τ=0.365 (val F1=0.2141)
  Directional -> Accuracy: 0.5846, MCC: 0.1898, F1: 0.4906

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.37025 | val 1.00936
  Epoch 020 - train 0.01037 | val 1.72450
  Epoch 024 - train 0.00323 | val 1.84041
  Classification -> best τ=0.820 (val F1=0.3833)
  Directional -> Accuracy: 0.4561, MCC: -0.0051, F1: 0.2439

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.37921 | val 1.09392
  Epoch 020 - train 0.05369 | val 1.77316
  Epoch 022 - train 0.01976 | val 1.93030
  Classification -> best τ=0.420 (val F1=0.3391)
  Directional -> Accuracy: 0.5077, MCC: 0.0220, F1: 0.5294

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.25757 | val 0.95495
  Epoch 020 - train 0.01071 | val 2.60727
  Epoch 022 - train 0.00544 | val 2.63990
  Classification -> best τ=0.590 (val F1=0.5278)
  Directional -> Accuracy: 0.5455, MCC: 0.1826, F1: 0.3902

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.24593 | val 2.70069
  Epoch 020 - train 0.00836 | val 4.44121
  Epoch 021 - train 0.00588 | val 4.41927
  Classification -> best τ=0.610 (val F1=0.2035)
  Directional -> Accuracy: 0.4000, MCC: -0.1297, F1: 0.5263

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.25052 | val 1.87969
  Epoch 020 - train 0.00444 | val 4.23569
  Epoch 021 - train 0.00345 | val 4.34937
  Classification -> best τ=0.565 (val F1=0.1105)
  Directional -> Accuracy: 0.5000, MCC: -0.0138, F1: 0.5532

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.46756 | val 0.94471
  Epoch 020 - train 0.07599 | val 2.02189
  Epoch 022 - train 0.04180 | val 2.18853
  Classification -> best τ=0.290 (val F1=0.1706)
  Directional -> Accuracy: 0.5714, MCC: 0.1399, F1: 0.6000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.27323 | val 5.03518
  Epoch 020 - train 0.06120 | val 9.55616
  Epoch 021 - train 0.04863 | val 9.66200
  Classification -> best τ=0.305 (val F1=0.4965)
  Directional -> Accuracy: 0.4750, MCC: -0.1069, F1: 0.5882

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.28944 | val 0.81573
  Epoch 020 - train 0.01029 | val 1.57612
  Epoch 023 - train 0.00426 | val 1.61280
  Classification -> best τ=0.585 (val F1=0.3501)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.4878

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.21328 | val 1.14399
  Epoch 020 - train 0.00239 | val 2.22607
  Epoch 022 - train 0.00177 | val 2.27636
  Classification -> best τ=0.425 (val F1=0.3039)
  Directional -> Accuracy: 0.5476, MCC: 0.0000, F1: 0.7077

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.22770 | val 2.62349
  Epoch 020 - train 0.01257 | val 5.31427
  Epoch 021 - train 0.00973 | val 5.52530
  Classification -> best τ=0.520 (val F1=0.2884)
  Directional -> Accuracy: 0.4694, MCC: -0.1021, F1: 0.5806

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.47409 | val 1.47512
  Epoch 020 - train 0.04199 | val 3.10191
  Epoch 022 - train 0.01840 | val 3.49269
  Classification -> best τ=0.395 (val F1=0.3530)
  Directional -> Accuracy: 0.4861, MCC: 0.1865, F1: 0.1395

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.25385 | val 2.23011
  Epoch 020 - train 0.00534 | val 2.02102
  Epoch 021 - train 0.00408 | val 2.08790
  Classification -> best τ=0.415 (val F1=0.2717)
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.48581 | val 1.33000
  Epoch 020 - train 0.12466 | val 2.18439
  Epoch 021 - train 0.08261 | val 2.55778
  Classification -> best τ=0.510 (val F1=0.3298)
  Directional -> Accuracy: 0.5909, MCC: 0.1443, F1: 0.6667

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.16157 | val 2.49367
  Epoch 020 - train 0.00388 | val 5.69278
  Epoch 021 - train 0.00321 | val 5.65849
  Classification -> best τ=0.440 (val F1=0.2464)
  Directional -> Accuracy: 0.6190, MCC: 0.2919, F1: 0.7241

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.21290 | val 2.16302
  Epoch 020 - train 0.00781 | val 4.78898
  Epoch 021 - train 0.00607 | val 4.90478
  Classification -> best τ=0.380 (val F1=0.2725)
  Directional -> Accuracy: 0.4821, MCC: -0.0234, F1: 0.5085

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.18711 | val 2.71059
  Epoch 020 - train 0.00392 | val 5.46061
  Epoch 022 - train 0.00273 | val 5.74762
  Classification -> best τ=0.615 (val F1=0.2659)
  Directional -> Accuracy: 0.4130, MCC: -0.0726, F1: 0.3077

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.30163 | val 0.79332
  Epoch 020 - train 0.01787 | val 1.48552
  Epoch 021 - train 0.01193 | val 1.57596
  Classification -> best τ=0.555 (val F1=0.4011)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.37630 | val 2.00378
  Epoch 020 - train 0.01983 | val 4.50196
  Epoch 021 - train 0.01003 | val 4.63780
  Classification -> best τ=0.375 (val F1=0.3548)
  Directional -> Accuracy: 0.5135, MCC: 0.0107, F1: 0.2174

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.23363 | val 2.56992
  Epoch 020 - train 0.00856 | val 5.25863
  Epoch 023 - train 0.00395 | val 5.53318
  Classification -> best τ=0.500 (val F1=0.2668)
  Directional -> Accuracy: 0.5556, MCC: 0.2205, F1: 0.6970

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.19876 | val 1.83419
  Epoch 020 - train 0.00680 | val 2.85904
  Epoch 022 - train 0.00453 | val 2.97067
  Classification -> best τ=0.660 (val F1=0.3612)
  Directional -> Accuracy: 0.4524, MCC: 0.1353, F1: 0.0800

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.17096 | val 1.34057
  Epoch 020 - train 0.00392 | val 2.35604
  Epoch 021 - train 0.00327 | val 2.40042
  Classification -> best τ=0.560 (val F1=0.1371)
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.5455

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.32167 | val 1.01687
  Epoch 020 - train 0.00744 | val 1.79192
  Epoch 022 - train 0.00404 | val 1.92098
  Classification -> best τ=0.650 (val F1=0.1647)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.28675 | val 2.80352
  Epoch 020 - train 0.00612 | val 5.19643
  Epoch 022 - train 0.00434 | val 5.28658
  Classification -> best τ=0.625 (val F1=0.3116)
  Directional -> Accuracy: 0.5179, MCC: 0.0766, F1: 0.6301

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.34317 | val 1.66856
  Epoch 020 - train 0.01841 | val 3.42981
  Epoch 022 - train 0.00598 | val 3.60568
  Classification -> best τ=0.700 (val F1=0.2064)

[I 2026-02-22 09:30:52,662] Trial 54 finished with value: 0.26343680399268377 and parameters: {'feature_set': 'sector_sentiment', 'model_type': 'GRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 64, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.0, 'batch_size': 32, 'learning_rate': 0.006770527588631217, 'weight_decay': 9.009865598263227e-06, 'lr_patience': 5, 'lr_factor': 0.8, 'early_stopping_patience': 20, 'max_epochs': 50, 'huber_delta': 1.821981428909056, 'early_stopping_min_delta': 0.00040404897397685463}. Best is trial 22 with value: 0.2833350641483003.

  Classification -> best τ=0.550 (val F1=0.2920)
  Directional -> Accuracy: 0.5333, MCC: 0.0848, F1: 0.6000

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.26343680399268377
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: classification
Sequence length: 30
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d', 'sentiment']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.42191 | val 2.29825
  Epoch 020 - train 0.22175 | val 3.61593
  Epoch 021 - train 0.20409 | val 3.58454
  Classification -> best τ=0.575 (val F1=0.1818)
  Directional -> Accuracy: 0.5600, MCC: 0.1277, F1: 0.0571

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 106). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.35404 | val 1.02920
  Epoch 020 - train 0.18167 | val 1.23743
  Epoch 021 - train 0.16600 | val 1.27515
  Classification -> best τ=0.470 (val F1=0.2818)
  Directional -> Accuracy: 0.6591, MCC: 0.3251, F1: 0.7761

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 106). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.38250 | val 1.12052
  Epoch 020 - train 0.17152 | val 1.96126
  Epoch 021 - train 0.15275 | val 2.01730
  Classification -> best τ=0.530 (val F1=0.3086)
  Directional -> Accuracy: 0.4667, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.43721 | val 2.68210
  Epoch 020 - train 0.25041 | val 4.56382
  Epoch 021 - train 0.22520 | val 5.53196
  Classification -> best τ=0.360 (val F1=0.2651)
  Directional -> Accuracy: 0.5205, MCC: 0.0810, F1: 0.4068

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.40352 | val 1.75674
  Epoch 020 - train 0.20104 | val 3.20128
  Epoch 021 - train 0.18116 | val 3.16054
  Classification -> best τ=0.570 (val F1=0.3489)
  Directional -> Accuracy: 0.5102, MCC: 0.0500, F1: 0.2500

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.40013 | val 1.08638
  Epoch 020 - train 0.21471 | val 1.67150
  Epoch 021 - train 0.20572 | val 1.79207
  Classification -> best τ=0.585 (val F1=0.2294)
  Directional -> Accuracy: 0.5111, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.45034 | val 1.29185
  Epoch 020 - train 0.20235 | val 1.89897
  Epoch 021 - train 0.19212 | val 1.87355
  Classification -> best τ=0.415 (val F1=0.2081)
  Directional -> Accuracy: 0.4925, MCC: 0.0705, F1: 0.5405

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 106). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 106). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.41391 | val 1.43547
  Epoch 020 - train 0.22648 | val 2.72564
  Epoch 022 - train 0.19668 | val 2.72850
  Classification -> best τ=0.590 (val F1=0.5222)
  Directional -> Accuracy: 0.4634, MCC: -0.0767, F1: 0.4211

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.40177 | val 0.98726
  Epoch 020 - train 0.19709 | val 1.16421
  Epoch 025 - train 0.13516 | val 1.71442
  Classification -> best τ=0.635 (val F1=0.4891)
  Directional -> Accuracy: 0.6383, MCC: 0.2974, F1: 0.3704

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 106). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 106). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 106). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.38802 | val 2.00063
  Epoch 020 - train 0.17057 | val 3.22431
  Epoch 021 - train 0.15129 | val 3.20553
  Classification -> best τ=0.405 (val F1=0.1531)
  Directional -> Accuracy: 0.4265, MCC: 0.0000, F1: 0.5979

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.40938 | val 1.18910
  Epoch 020 - train 0.22819 | val 1.54540
  Epoch 021 - train 0.19885 | val 1.50058
  Classification -> best τ=0.615 (val F1=0.3892)
  Directional -> Accuracy: 0.5833, MCC: 0.1459, F1: 0.3750

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.37655 | val 1.65161
  Epoch 020 - train 0.20030 | val 2.05623
  Epoch 021 - train 0.17660 | val 2.08369
  Classification -> best τ=0.580 (val F1=0.2215)
  Directional -> Accuracy: 0.5536, MCC: 0.2676, F1: 0.2424

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 106). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.40529 | val 2.37767
  Epoch 020 - train 0.19442 | val 3.51467
  Epoch 021 - train 0.17736 | val 3.45905
  Classification -> best τ=0.485 (val F1=0.2112)
  Directional -> Accuracy: 0.5102, MCC: 0.0000, F1: 0.0000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 106). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.41147 | val 1.06605
  Epoch 020 - train 0.17118 | val 1.29706
  Epoch 021 - train 0.15466 | val 1.51930
  Classification -> best τ=0.495 (val F1=0.2510)
  Directional -> Accuracy: 0.5593, MCC: 0.1731, F1: 0.3500

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.39526 | val 0.88126
  Epoch 020 - train 0.18486 | val 1.49086
  Epoch 022 - train 0.14901 | val 1.65916
  Classification -> best τ=0.575 (val F1=0.1516)
  Directional -> Accuracy: 0.5600, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.42284 | val 0.76153
  Epoch 020 - train 0.21312 | val 1.21753
  Epoch 022 - train 0.17401 | val 1.31187
  Classification -> best τ=0.385 (val F1=0.3005)
  Directional -> Accuracy: 0.5588, MCC: 0.1846, F1: 0.7059

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 106). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.46975 | val 1.56538
  Epoch 020 - train 0.23509 | val 2.50237
  Epoch 021 - train 0.21355 | val 2.72738
  Classification -> best τ=0.565 (val F1=0.2000)
  Directional -> Accuracy: 0.3860, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.40886 | val 2.10134
  Epoch 020 - train 0.20303 | val 3.10187
  Epoch 021 - train 0.17272 | val 2.90092
  Classification -> best τ=0.385 (val F1=0.1839)
  Directional -> Accuracy: 0.5946, MCC: 0.0000, F1: 0.7458

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.42884 | val 1.98107
  Epoch 020 - train 0.22503 | val 2.38072
  Epoch 021 - train 0.20141 | val 2.49830
  Classification -> best τ=0.565 (val F1=0.2288)
  Directional -> Accuracy: 0.4444, MCC: 0.0860, F1: 0.1463

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 106). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.42331 | val 1.35997
  Epoch 020 - train 0.26511 | val 1.57701
  Epoch 022 - train 0.22838 | val 1.44447
  Classification -> best τ=0.515 (val F1=0.3105)
  Directional -> Accuracy: 0.4658, MCC: 0.1070, F1: 0.0488

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.36463 | val 0.78726
  Epoch 020 - train 0.11288 | val 1.50646
  Epoch 023 - train 0.07867 | val 1.78546
  Classification -> best τ=0.520 (val F1=0.2955)
  Directional -> Accuracy: 0.3913, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 106). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 106). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 106). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.40501 | val 1.31532
  Epoch 020 - train 0.16721 | val 2.06041
  Epoch 021 - train 0.14874 | val 2.19208
  Classification -> best τ=0.380 (val F1=0.2122)
  Directional -> Accuracy: 0.5781, MCC: 0.1769, F1: 0.4490

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.41439 | val 2.55375
  Epoch 020 - train 0.18521 | val 4.60219
  Epoch 021 - train 0.16273 | val 4.99163
  Classification -> best τ=0.650 (val F1=0.3062)
  Directional -> Accuracy: 0.5179, MCC: 0.1343, F1: 0.4000

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.39782 | val 1.15636
  Epoch 020 - train 0.19606 | val 1.23959
  Epoch 021 - train 0.18305 | val 1.51043
  Classification -> best τ=0.365 (val F1=0.3186)
  Directional -> Accuracy: 0.5156, MCC: 0.0960, F1: 0.6265

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.38733 | val 1.44049
  Epoch 020 - train 0.18560 | val 3.19000
  Epoch 022 - train 0.15920 | val 3.40718
  Classification -> best τ=0.525 (val F1=0.3669)
  Directional -> Accuracy: 0.5000, MCC: 0.0736, F1: 0.2703

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.43236 | val 0.88336
  Epoch 020 - train 0.26557 | val 1.43013
  Epoch 021 - train 0.24965 | val 1.44001
  Classification -> best τ=0.525 (val F1=0.1157)
  Directional -> Accuracy: 0.5116, MCC: -0.0112, F1: 0.4000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.44896 | val 0.97622
  Epoch 020 - train 0.26410 | val 1.31677
  Epoch 021 - train 0.24466 | val 1.18946
  Classification -> best τ=0.505 (val F1=0.1133)
  Directional -> Accuracy: 0.4082, MCC: 0.0000, F1: 0.0000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.43750 | val 1.06331
  Epoch 020 - train 0.23367 | val 1.84660
  Epoch 022 - train 0.20012 | val 2.03231
  Classification -> best τ=0.380 (val F1=0.2374)
  Directional -> Accuracy: 0.5818, MCC: 0.1596, F1: 0.6102

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.39512 | val 0.74975
  Epoch 020 - train 0.21825 | val 0.96494
  Epoch 021 - train 0.20585 | val 0.98190
  Classification -> best τ=0.480 (val F1=0.3708)
  Directional -> Accuracy: 0.5000, MCC: -0.0752, F1: 0.6275

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.45277 | val 0.82260
  Epoch 020 - train 0.24724 | val 1.03945
  Epoch 021 - train 0.23165 | val 1.03285
  Classification -> best τ=0.480 (val F1=0.2706)
  Directional -> Accuracy: 0.5122, MCC: 0.0238, F1: 0.5000

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.40500 | val 1.20264
  Epoch 020 - train 0.18693 | val 2.03380
  Epoch 021 - train 0.17216 | val 2.04897
  Classification -> best τ=0.525 (val F1=0.2076)
  Directional -> Accuracy: 0.5122, MCC: -0.0635, F1: 0.6429

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.43230 | val 0.98623
  Epoch 020 - train 0.20475 | val 1.88580
  Epoch 021 - train 0.17950 | val 1.88397
  Classification -> best τ=0.475 (val F1=0.3333)
  Directional -> Accuracy: 0.5208, MCC: 0.0000, F1: 0.6849

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.40146 | val 1.84104
  Epoch 020 - train 0.20491 | val 3.05512
  Epoch 021 - train 0.18559 | val 2.87396
  Classification -> best τ=0.435 (val F1=0.2614)
  Directional -> Accuracy: 0.4648, MCC: 0.1499, F1: 0.0952

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 106). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.40111 | val 0.88449
  Epoch 020 - train 0.16538 | val 1.35926
  Epoch 021 - train 0.14955 | val 1.67515
  Classification -> best τ=0.540 (val F1=0.3363)
  Directional -> Accuracy: 0.5238, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for PCG (101 < 106). Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.44196 | val 0.90642
  Epoch 020 - train 0.25107 | val 1.17434
  Epoch 021 - train 0.22678 | val 1.10202
  Classification -> best τ=0.425 (val F1=0.4004)
  Directional -> Accuracy: 0.6308, MCC: 0.2541, F1: 0.6667

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.37387 | val 0.83967
  Epoch 020 - train 0.15214 | val 1.05338
  Epoch 024 - train 0.09786 | val 1.18167
  Classification -> best τ=0.425 (val F1=0.2697)
  Directional -> Accuracy: 0.7000, MCC: 0.4088, F1: 0.7500

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.37149 | val 1.31438
  Epoch 020 - train 0.18125 | val 1.82910
  Epoch 021 - train 0.16249 | val 1.87391
  Classification -> best τ=0.465 (val F1=0.2089)
  Directional -> Accuracy: 0.4909, MCC: -0.0133, F1: 0.4815

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.34855 | val 3.05330
  Epoch 020 - train 0.16148 | val 4.72744
  Epoch 021 - train 0.14912 | val 5.12497
  Classification -> best τ=0.520 (val F1=0.2320)
  Directional -> Accuracy: 0.6222, MCC: 0.0544, F1: 0.7606

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 106). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 106). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 106). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 106). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.41641 | val 0.68548
  Epoch 020 - train 0.22678 | val 0.97357
  Epoch 027 - train 0.14357 | val 1.24049
  Classification -> best τ=0.705 (val F1=0.4385)
  Directional -> Accuracy: 0.3913, MCC: 0.1837, F1: 0.5172

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 106). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 106). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 106). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.39486 | val 1.62458
  Epoch 020 - train 0.20915 | val 3.04026
  Epoch 021 - train 0.18946 | val 3.13860
  Classification -> best τ=0.455 (val F1=0.2875)
  Directional -> Accuracy: 0.4658, MCC: -0.0767, F1: 0.3607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 106). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 106). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 106). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 106). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.39846 | val 0.75992
  Epoch 020 - train 0.14076 | val 0.86403
  Epoch 029 - train 0.04540 | val 1.15104
  Classification -> best τ=0.605 (val F1=0.3720)
  Directional -> Accuracy: 0.6136, MCC: 0.3107, F1: 0.7119

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.48423 | val 0.81670
  Epoch 020 - train 0.30685 | val 1.00765
  Epoch 021 - train 0.29058 | val 1.03831
  Classification -> best τ=0.540 (val F1=0.0989)
  Directional -> Accuracy: 0.3902, MCC: -0.1608, F1: 0.2857

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.42855 | val 0.94539
  Epoch 020 - train 0.24426 | val 1.55688
  Epoch 021 - train 0.22939 | val 1.75905
  Classification -> best τ=0.445 (val F1=0.0608)
  Directional -> Accuracy: 0.3696, MCC: 0.0000, F1: 0.5397

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.42758 | val 1.52078
  Epoch 020 - train 0.22962 | val 3.26005
  Epoch 021 - train 0.21625 | val 3.16515
  Classification -> best τ=0.440 (val F1=0.1783)
  Directional -> Accuracy: 0.5741, MCC: 0.3000, F1: 0.4103

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.41242 | val 2.80235
  Epoch 020 - train 0.17895 | val 4.46447
  Epoch 021 - train 0.15873 | val 4.80908
  Classification -> best τ=0.575 (val F1=0.4152)
  Directional -> Accuracy: 0.4182, MCC: -0.1972, F1: 0.5556

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.43524 | val 1.09937
  Epoch 020 - train 0.18219 | val 1.19452
  Epoch 024 - train 0.11124 | val 1.33901
  Classification -> best τ=0.550 (val F1=0.2423)
  Directional -> Accuracy: 0.5962, MCC: 0.2122, F1: 0.6667

[87/88] Processing WMT...


[I 2026-02-22 09:32:15,136] Trial 55 finished with value: 0.26527158042692495 and parameters: {'feature_set': 'sector_sentiment', 'model_type': 'GRU', 'sequence_length': 30, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 64, 'num_layers': 1, 'inter_rnn_drop': 0.1, 'dropout': 0.0, 'batch_size': 32, 'learning_rate': 0.0013437680858542275, 'weight_decay': 2.7206666452497397e-06, 'lr_patience': 5, 'lr_factor': 0.8, 'early_stopping_patience': 20, 'max_epochs': 50, 'huber_delta': 1.4207178549319608, 'early_stopping_min_delta': 0.004671337495484392}. Best is trial 22 with value: 0.2833350641483003.

  Classification -> best τ=0.465 (val F1=0.2110)
  Directional -> Accuracy: 0.5254, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.26527158042692495
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d', 'sentiment']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.59522 | val 0.79046
  Epoch 016 - train 0.48890 | val 1.12130
  Classification -> best τ=0.460 (val F1=0.1635)
  Directional -> Accuracy: 0.5921, MCC: 0.1649, F1: 0.5079

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.45698 | val 1.37352
  Epoch 016 - train 0.32902 | val 1.69331
  Classification -> best τ=0.465 (val F1=0.1857)
  Directional -> Accuracy: 0.5556, MCC: -0.0159, F1: 0.6970

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.51337 | val 1.75921
  Epoch 016 - train 0.41702 | val 2.39647
  Classification -> best τ=0.570 (val F1=0.1314)
  Directional -> Accuracy: 0.4783, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.60295 | val 0.84152
  Epoch 018 - train 0.47737 | val 1.00933
  Classification -> best τ=0.335 (val F1=0.1808)
  Directional -> Accuracy: 0.5405, MCC: 0.0000, F1: 0.7018

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.51243 | val 0.64664
  Epoch 020 - train 0.30344 | val 1.11037
  Epoch 024 - train 0.18260 | val 1.70228
  Classification -> best τ=0.520 (val F1=0.4947)
  Directional -> Accuracy: 0.6400, MCC: 0.3036, F1: 0.5909

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.50092 | val 0.91045
  Epoch 016 - train 0.36570 | val 1.94145
  Classification -> best τ=0.520 (val F1=0.0882)
  Directional -> Accuracy: 0.5435, MCC: 0.0763, F1: 0.3226

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.55600 | val 1.29618
  Epoch 016 - train 0.47083 | val 1.56711
  Classification -> best τ=0.440 (val F1=0.2587)
  Directional -> Accuracy: 0.5294, MCC: 0.1909, F1: 0.5897

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.53125 | val 0.57181
  Epoch 020 - train 0.37509 | val 0.83077
  Epoch 025 - train 0.26543 | val 1.10586
  Classification -> best τ=0.410 (val F1=0.3974)
  Directional -> Accuracy: 0.5000, MCC: 0.0782, F1: 0.5714

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.52971 | val 1.49499
  Epoch 016 - train 0.43694 | val 1.63147
  Classification -> best τ=0.520 (val F1=0.1928)
  Directional -> Accuracy: 0.5625, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.50619 | val 1.21777
  Epoch 016 - train 0.45787 | val 1.67580
  Classification -> best τ=0.330 (val F1=0.2634)
  Directional -> Accuracy: 0.4203, MCC: 0.0000, F1: 0.5918

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.51267 | val 2.05228
  Epoch 016 - train 0.44871 | val 1.78879
  Classification -> best τ=0.590 (val F1=0.2484)
  Directional -> Accuracy: 0.6122, MCC: 0.2379, F1: 0.2963

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.54433 | val 1.38641
  Epoch 016 - train 0.44665 | val 1.26802
  Classification -> best τ=0.450 (val F1=0.0340)
  Directional -> Accuracy: 0.6316, MCC: 0.3198, F1: 0.7200

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.47924 | val 2.46272
  Epoch 016 - train 0.41080 | val 2.59166
  Classification -> best τ=0.400 (val F1=0.2850)
  Directional -> Accuracy: 0.4048, MCC: -0.1940, F1: 0.5614

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.56907 | val 0.69081
  Epoch 020 - train 0.41659 | val 1.01006
  Classification -> best τ=0.480 (val F1=0.4109)
  Directional -> Accuracy: 0.4833, MCC: -0.1302, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.47818 | val 0.76686
  Epoch 020 - train 0.31781 | val 0.71991
  Epoch 030 - train 0.17511 | val 1.17574
  Classification -> best τ=0.580 (val F1=0.3516)
  Directional -> Accuracy: 0.3725, MCC: -0.2806, F1: 0.5294

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.51385 | val 1.12597
  Epoch 016 - train 0.46399 | val 1.29935
  Classification -> best τ=0.425 (val F1=0.3094)
  Directional -> Accuracy: 0.5507, MCC: 0.0867, F1: 0.6990

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.54945 | val 1.83699
  Epoch 016 - train 0.46115 | val 2.78620
  Classification -> best τ=0.645 (val F1=0.1842)
  Directional -> Accuracy: 0.3793, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.57031 | val 0.96430
  Epoch 016 - train 0.41592 | val 1.69818
  Classification -> best τ=0.530 (val F1=0.1087)
  Directional -> Accuracy: 0.4000, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.55927 | val 0.69630
  Epoch 020 - train 0.37564 | val 0.89239
  Epoch 022 - train 0.36473 | val 0.97027
  Classification -> best τ=0.230 (val F1=0.2803)
  Directional -> Accuracy: 0.4844, MCC: 0.1062, F1: 0.2979

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.53049 | val 0.96857
  Epoch 016 - train 0.44649 | val 0.85979
  Classification -> best τ=0.510 (val F1=0.3153)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.52962 | val 1.43841
  Epoch 016 - train 0.37020 | val 2.66752
  Classification -> best τ=0.475 (val F1=0.2164)
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.56197 | val 0.77164
  Epoch 020 - train 0.30542 | val 1.62328
  Classification -> best τ=0.530 (val F1=0.3236)
  Directional -> Accuracy: 0.4923, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.61306 | val 0.68447
  Epoch 020 - train 0.41799 | val 0.96534
  Epoch 022 - train 0.36540 | val 1.08805
  Classification -> best τ=0.535 (val F1=0.4373)
  Directional -> Accuracy: 0.5088, MCC: -0.0353, F1: 0.6111

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.55635 | val 0.78926
  Epoch 016 - train 0.48524 | val 0.81502
  Classification -> best τ=0.485 (val F1=0.2177)
  Directional -> Accuracy: 0.4923, MCC: -0.0402, F1: 0.3265

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.51371 | val 0.87844
  Epoch 019 - train 0.32730 | val 1.37929
  Classification -> best τ=0.600 (val F1=0.4560)
  Directional -> Accuracy: 0.5273, MCC: 0.1143, F1: 0.4091

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.49352 | val 1.35953
  Epoch 016 - train 0.42349 | val 1.64242
  Classification -> best τ=0.640 (val F1=0.1956)
  Directional -> Accuracy: 0.5778, MCC: 0.0000, F1: 0.0000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.53240 | val 0.82693
  Epoch 017 - train 0.51943 | val 1.18065
  Classification -> best τ=0.560 (val F1=0.0534)
  Directional -> Accuracy: 0.4762, MCC: 0.1936, F1: 0.1538

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.52615 | val 0.78474
  Epoch 016 - train 0.46712 | val 0.92316
  Classification -> best τ=0.465 (val F1=0.2622)
  Directional -> Accuracy: 0.4464, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.49909 | val 1.45270
  Epoch 019 - train 0.37847 | val 4.15391
  Classification -> best τ=0.405 (val F1=0.2957)
  Directional -> Accuracy: 0.6000, MCC: 0.1759, F1: 0.7037

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.53478 | val 0.81944
  Epoch 018 - train 0.46831 | val 1.06846
  Classification -> best τ=0.610 (val F1=0.3501)
  Directional -> Accuracy: 0.4762, MCC: -0.0674, F1: 0.3529

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.55930 | val 1.02902
  Epoch 016 - train 0.47681 | val 1.47450
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5476, MCC: 0.0000, F1: 0.7077

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.49418 | val 1.37525
  Epoch 016 - train 0.40612 | val 1.68001
  Classification -> best τ=0.510 (val F1=0.2716)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.57038 | val 0.72339
  Epoch 016 - train 0.48566 | val 0.96541
  Classification -> best τ=0.395 (val F1=0.3366)
  Directional -> Accuracy: 0.5417, MCC: 0.0870, F1: 0.5600

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.53028 | val 1.20657
  Epoch 016 - train 0.44391 | val 1.26708
  Classification -> best τ=0.455 (val F1=0.2717)
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.54787 | val 1.02543
  Epoch 016 - train 0.46976 | val 1.44494
  Classification -> best τ=0.350 (val F1=0.3254)
  Directional -> Accuracy: 0.5000, MCC: 0.1961, F1: 0.2667

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.56326 | val 1.92104
  Epoch 016 - train 0.39862 | val 2.71342
  Classification -> best τ=0.495 (val F1=0.1715)
  Directional -> Accuracy: 0.6429, MCC: 0.2860, F1: 0.6512

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.45801 | val 1.24890
  Epoch 016 - train 0.41764 | val 1.61445
  Classification -> best τ=0.455 (val F1=0.2382)
  Directional -> Accuracy: 0.4643, MCC: -0.0620, F1: 0.4828

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.43495 | val 1.28885
  Epoch 016 - train 0.36928 | val 1.42197
  Classification -> best τ=0.565 (val F1=0.3679)
  Directional -> Accuracy: 0.6087, MCC: 0.1786, F1: 0.6786

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.52992 | val 0.68331
  Epoch 020 - train 0.39464 | val 0.92987
  Epoch 027 - train 0.26996 | val 1.39675
  Classification -> best τ=0.595 (val F1=0.4306)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.49755 | val 1.10539
  Epoch 016 - train 0.36751 | val 1.53179
  Classification -> best τ=0.260 (val F1=0.2456)
  Directional -> Accuracy: 0.4865, MCC: 0.0000, F1: 0.6545

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.56588 | val 1.03567
  Epoch 018 - train 0.44058 | val 1.41152
  Classification -> best τ=0.475 (val F1=0.1976)
  Directional -> Accuracy: 0.4889, MCC: -0.1474, F1: 0.6567

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.51979 | val 1.00150
  Epoch 016 - train 0.46366 | val 1.30853
  Classification -> best τ=0.540 (val F1=0.2500)
  Directional -> Accuracy: 0.5000, MCC: 0.0782, F1: 0.4000

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.50711 | val 0.67622
  Epoch 020 - train 0.36695 | val 0.89322
  Epoch 025 - train 0.26643 | val 1.07899
  Classification -> best τ=0.655 (val F1=0.2464)
  Directional -> Accuracy: 0.6042, MCC: 0.2046, F1: 0.5366

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.56464 | val 0.81998
  Epoch 018 - train 0.45595 | val 1.00120
  Classification -> best τ=0.540 (val F1=0.1811)
  Directional -> Accuracy: 0.5455, MCC: 0.1491, F1: 0.4444

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.52227 | val 1.60420
  Epoch 016 - train 0.40151 | val 2.02965
  Classification -> best τ=0.515 (val F1=0.2385)
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.6506

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.53316 | val 0.96190
  Epoch 016 - train 0.46792 | val 1.07658
  Classification -> best τ=0.525 (val F1=0.1126)
  Directional -> Accuracy: 0.5849, MCC: 0.1768, F1: 0.6562

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.54276 | val 1.07820
  Epoch 016 - train 0.42628 | val 1.54417
  Classification -> best τ=0.525 (val F1=0.2426)
  Directional -> Accuracy: 0.5273, MCC: 0.0598, F1: 0.5185

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.55454 | val 1.03535

[I 2026-02-22 09:33:39,245] Trial 56 finished with value: 0.25430807359031865 and parameters: {'feature_set': 'sector_sentiment', 'model_type': 'GRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 64, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.1, 'batch_size': 32, 'learning_rate': 0.002747513186779312, 'weight_decay': 1.5242251506068726e-05, 'lr_patience': 5, 'lr_factor': 0.8, 'early_stopping_patience': 15, 'max_epochs': 50, 'huber_delta': 1.1175405952461532, 'early_stopping_min_delta': 0.006024042667066941}. Best is trial 22 with value: 0.2833350641483003.

  Epoch 019 - train 0.40746 | val 0.75701
  Classification -> best τ=0.515 (val F1=0.3862)
  Directional -> Accuracy: 0.4833, MCC: -0.0438, F1: 0.3922

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.25430807359031865
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: classification
Sequence length: 30
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.42698 | val 0.71314
  Epoch 012 - train 0.34571 | val 0.91505
  Classification -> best τ=0.400 (val F1=0.2236)
  Directional -> Accuracy: 0.5733, MCC: 0.1661, F1: 0.5897

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 106). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.25944 | val 1.15647
  Epoch 011 - train 0.22347 | val 1.20070
  Classification -> best τ=0.565 (val F1=0.1749)
  Directional -> Accuracy: 0.6818, MCC: 0.3320, F1: 0.7407

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 106). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.27975 | val 2.36352
  Epoch 011 - train 0.23363 | val 2.57021
  Classification -> best τ=0.585 (val F1=0.2294)
  Directional -> Accuracy: 0.5333, MCC: 0.1890, F1: 0.2759

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.43248 | val 1.84377
  Epoch 011 - train 0.42094 | val 2.43351
  Classification -> best τ=0.405 (val F1=0.2157)
  Directional -> Accuracy: 0.4658, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.32635 | val 1.32666
  Epoch 014 - train 0.17168 | val 1.45947
  Classification -> best τ=0.540 (val F1=0.4473)
  Directional -> Accuracy: 0.6327, MCC: 0.2770, F1: 0.5909

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.28268 | val 1.38310
  Epoch 011 - train 0.24878 | val 1.72624
  Classification -> best τ=0.645 (val F1=0.2294)
  Directional -> Accuracy: 0.5111, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.40262 | val 1.38490
  Epoch 011 - train 0.33691 | val 1.59351
  Classification -> best τ=0.465 (val F1=0.3225)
  Directional -> Accuracy: 0.5075, MCC: 0.1723, F1: 0.5926

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 106). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 106). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.27675 | val 1.41278
  Epoch 013 - train 0.12892 | val 1.45300
  Classification -> best τ=0.675 (val F1=0.3612)
  Directional -> Accuracy: 0.4878, MCC: -0.0097, F1: 0.4878

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.32105 | val 1.04803
  Epoch 014 - train 0.18685 | val 1.36202
  Classification -> best τ=0.540 (val F1=0.3835)
  Directional -> Accuracy: 0.5532, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 106). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 106). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 106). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.38536 | val 3.01257
  Epoch 011 - train 0.33245 | val 3.87753
  Classification -> best τ=0.350 (val F1=0.1654)
  Directional -> Accuracy: 0.4265, MCC: 0.0000, F1: 0.5979

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.34294 | val 2.67363
  Epoch 014 - train 0.17599 | val 2.33864
  Classification -> best τ=0.735 (val F1=0.4619)
  Directional -> Accuracy: 0.6250, MCC: 0.2618, F1: 0.4000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.39280 | val 2.35212
  Epoch 011 - train 0.44064 | val 2.46557
  Classification -> best τ=0.495 (val F1=0.0199)
  Directional -> Accuracy: 0.5357, MCC: 0.1397, F1: 0.6905

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 106). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.27494 | val 2.55149
  Epoch 011 - train 0.29383 | val 2.09294
  Classification -> best τ=0.445 (val F1=0.2112)
  Directional -> Accuracy: 0.5306, MCC: 0.0601, F1: 0.5106

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 106). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.37028 | val 1.02725
  Epoch 013 - train 0.22496 | val 1.81057
  Classification -> best τ=0.215 (val F1=0.3952)
  Directional -> Accuracy: 0.5254, MCC: 0.0506, F1: 0.5333

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.37691 | val 1.77228
  Epoch 012 - train 0.28791 | val 1.72928
  Classification -> best τ=0.550 (val F1=0.2550)
  Directional -> Accuracy: 0.5600, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.41212 | val 1.65711
  Epoch 011 - train 0.37018 | val 1.77991
  Classification -> best τ=0.435 (val F1=0.2283)
  Directional -> Accuracy: 0.5294, MCC: 0.0103, F1: 0.6863

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 106). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.42202 | val 1.63410
  Epoch 011 - train 0.40440 | val 1.71830
  Classification -> best τ=0.610 (val F1=0.1612)
  Directional -> Accuracy: 0.4211, MCC: 0.0371, F1: 0.1951

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.38444 | val 1.90221
  Epoch 011 - train 0.36028 | val 2.83045
  Classification -> best τ=0.605 (val F1=0.1895)
  Directional -> Accuracy: 0.4189, MCC: -0.0296, F1: 0.1887

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.41526 | val 1.57818
  Epoch 011 - train 0.36837 | val 1.77248
  Classification -> best τ=0.355 (val F1=0.1741)
  Directional -> Accuracy: 0.5238, MCC: 0.0745, F1: 0.5312

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 106). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.46840 | val 0.97530
  Epoch 013 - train 0.35046 | val 1.31241
  Classification -> best τ=0.570 (val F1=0.3461)
  Directional -> Accuracy: 0.4521, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.30116 | val 2.07479
  Epoch 011 - train 0.26226 | val 1.73319
  Classification -> best τ=0.470 (val F1=0.4450)
  Directional -> Accuracy: 0.4348, MCC: 0.1709, F1: 0.1333

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 106). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 106). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 106). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.27393 | val 1.68030
  Epoch 011 - train 0.25348 | val 1.85836
  Classification -> best τ=0.525 (val F1=0.1372)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.32809 | val 3.28917
  Epoch 011 - train 0.27911 | val 3.30952
  Classification -> best τ=0.700 (val F1=0.3062)
  Directional -> Accuracy: 0.5179, MCC: 0.0745, F1: 0.4906

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.40260 | val 0.84305
  Epoch 011 - train 0.39020 | val 1.35783
  Classification -> best τ=0.375 (val F1=0.1941)
  Directional -> Accuracy: 0.4688, MCC: 0.0000, F1: 0.6383

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.29600 | val 1.60223
  Epoch 011 - train 0.26082 | val 1.89491
  Classification -> best τ=0.520 (val F1=0.3646)
  Directional -> Accuracy: 0.5000, MCC: 0.0736, F1: 0.2703

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.30352 | val 1.40893
  Epoch 011 - train 0.26949 | val 1.56725
  Classification -> best τ=0.605 (val F1=0.1409)
  Directional -> Accuracy: 0.4651, MCC: 0.1874, F1: 0.6102

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.30748 | val 2.40746
  Epoch 012 - train 0.24270 | val 3.49766
  Classification -> best τ=0.490 (val F1=0.2645)
  Directional -> Accuracy: 0.6327, MCC: 0.2101, F1: 0.7188

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.41136 | val 1.10738
  Epoch 011 - train 0.36378 | val 1.26232
  Classification -> best τ=0.540 (val F1=0.3730)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.24635 | val 0.79639
  Epoch 013 - train 0.14988 | val 0.90791
  Classification -> best τ=0.525 (val F1=0.3706)
  Directional -> Accuracy: 0.5526, MCC: 0.0633, F1: 0.6531

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.29321 | val 1.15835
  Epoch 011 - train 0.25489 | val 1.16268
  Classification -> best τ=0.540 (val F1=0.3150)
  Directional -> Accuracy: 0.5610, MCC: 0.1199, F1: 0.5263

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.23454 | val 1.71519
  Epoch 011 - train 0.18865 | val 1.61581
  Classification -> best τ=0.520 (val F1=0.1053)
  Directional -> Accuracy: 0.4878, MCC: -0.2486, F1: 0.6557

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.36681 | val 1.36749
  Epoch 011 - train 0.31654 | val 1.29541
  Classification -> best τ=0.425 (val F1=0.2582)
  Directional -> Accuracy: 0.5208, MCC: 0.0000, F1: 0.6849

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.41442 | val 1.47128
  Epoch 011 - train 0.37403 | val 2.28149
  Classification -> best τ=0.375 (val F1=0.3022)
  Directional -> Accuracy: 0.5211, MCC: 0.1508, F1: 0.3704

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 106). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.28710 | val 1.07096
  Epoch 012 - train 0.21691 | val 1.54020
  Classification -> best τ=0.420 (val F1=0.3367)
  Directional -> Accuracy: 0.5476, MCC: 0.0830, F1: 0.3448

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for PCG (101 < 106). Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.42440 | val 1.20619
  Epoch 011 - train 0.40191 | val 1.49052
  Classification -> best τ=0.335 (val F1=0.3317)
  Directional -> Accuracy: 0.5846, MCC: 0.1646, F1: 0.6197

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.25421 | val 1.27329
  Epoch 011 - train 0.23260 | val 1.42234
  Classification -> best τ=0.505 (val F1=0.2582)
  Directional -> Accuracy: 0.6750, MCC: 0.3831, F1: 0.6286

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.33590 | val 2.62019
  Epoch 011 - train 0.28918 | val 3.21805
  Classification -> best τ=0.445 (val F1=0.2436)
  Directional -> Accuracy: 0.5273, MCC: 0.0828, F1: 0.5667

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.23511 | val 2.56821
  Epoch 011 - train 0.20767 | val 2.15671
  Classification -> best τ=0.520 (val F1=0.2913)
  Directional -> Accuracy: 0.5333, MCC: 0.0410, F1: 0.6038

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 106). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 106). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 106). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 106). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.37022 | val 0.66706
  Epoch 015 - train 0.17776 | val 0.77063
  Classification -> best τ=0.655 (val F1=0.4548)
  Directional -> Accuracy: 0.3478, MCC: 0.1037, F1: 0.5000

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 106). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 106). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 106). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.33800 | val 2.13677
  Epoch 011 - train 0.30487 | val 2.51050
  Classification -> best τ=0.290 (val F1=0.2282)
  Directional -> Accuracy: 0.4932, MCC: 0.0000, F1: 0.6606

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 106). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 106). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 106). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 106). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.28163 | val 0.94831
  Epoch 016 - train 0.05420 | val 1.82486
  Classification -> best τ=0.500 (val F1=0.4152)
  Directional -> Accuracy: 0.5455, MCC: 0.2182, F1: 0.6875

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.34629 | val 0.77121
  Epoch 011 - train 0.29619 | val 0.75631
  Classification -> best τ=0.540 (val F1=0.1908)
  Directional -> Accuracy: 0.4878, MCC: 0.0875, F1: 0.3636

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.32367 | val 0.92472
  Epoch 012 - train 0.23504 | val 1.11894
  Classification -> best τ=0.660 (val F1=0.2231)
  Directional -> Accuracy: 0.3913, MCC: 0.1141, F1: 0.5484

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.39880 | val 2.33528
  Epoch 011 - train 0.34096 | val 3.47263
  Classification -> best τ=0.585 (val F1=0.2011)
  Directional -> Accuracy: 0.4444, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.29171 | val 2.51096
  Epoch 011 - train 0.24880 | val 2.28575
  Classification -> best τ=0.585 (val F1=0.4032)
  Directional -> Accuracy: 0.4909, MCC: 0.0000, F1: 0.6585

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.36195 | val 0.91762
  Epoch 012 - train 0.31366 | val 1.17061
  Classification -> best τ=0.585 (val F1=0.2648)
  Directional -> Accuracy: 0.6154, MCC: 0.2315, F1: 0.6000

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.35161 | val 0.81916
  Epoch 013 - train 0.21558 | val 0.94014
  Classification -> best τ=0.430 (val F1=0.2569)
  Directional -> Accuracy: 0.5185, MCC: 0.0073, F1: 0.6750

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...

[I 2026-02-22 09:34:32,987] Trial 57 finished with value: 0.2741560299226151 and parameters: {'feature_set': 'sector', 'model_type': 'GRU', 'sequence_length': 30, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 64, 'num_layers': 1, 'inter_rnn_drop': 0.1, 'dropout': 0.0, 'batch_size': 32, 'learning_rate': 0.0041945770025588434, 'weight_decay': 1.3480905053073912e-06, 'lr_patience': 5, 'lr_factor': 0.8, 'early_stopping_patience': 10, 'max_epochs': 50, 'huber_delta': 1.5355459299187035, 'early_stopping_min_delta': 0.002233036440986435}. Best is trial 22 with value: 0.2833350641483003.

  Epoch 010 - train 0.46317 | val 1.33351
  Epoch 011 - train 0.38945 | val 1.05519
  Classification -> best τ=0.485 (val F1=0.2881)
  Directional -> Accuracy: 0.4576, MCC: -0.0840, F1: 0.4483

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2741560299226151
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: classification
Sequence length: 36
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.50919 | val 0.87748
  Epoch 011 - train 0.49539 | val 0.87308
  Classification -> best τ=0.550 (val F1=0.1092)
  Directional -> Accuracy: 0.6081, MCC: 0.1897, F1: 0.4727

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 112). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.49172 | val 1.00851
  Epoch 011 - train 0.47486 | val 1.07900
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.6047, MCC: 0.0000, F1: 0.7536

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for AEP (109 < 112). Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 112). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.48627 | val 1.10111
  Epoch 013 - train 0.41150 | val 1.92041
  Classification -> best τ=0.540 (val F1=0.3150)
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.53212 | val 0.84886
  Epoch 011 - train 0.52479 | val 0.77536
  Classification -> best τ=0.515 (val F1=0.0198)
  Directional -> Accuracy: 0.5139, MCC: -0.1014, F1: 0.6729

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.44905 | val 0.74981
  Epoch 018 - train 0.30657 | val 1.01504
  Classification -> best τ=0.555 (val F1=0.4382)
  Directional -> Accuracy: 0.6042, MCC: 0.2867, F1: 0.4571

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.51206 | val 0.73323
  Epoch 011 - train 0.49591 | val 0.74668
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.53665 | val 0.87145
  Epoch 015 - train 0.45882 | val 0.81956
  Classification -> best τ=0.435 (val F1=0.3670)
  Directional -> Accuracy: 0.5000, MCC: 0.1302, F1: 0.5823

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 112). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 112). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.50591 | val 0.84152
  Epoch 011 - train 0.49456 | val 0.89579
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4359, MCC: 0.0000, F1: 0.6071

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.50064 | val 0.84517
  Epoch 011 - train 0.48330 | val 0.91150
  Classification -> best τ=0.495 (val F1=0.2726)
  Directional -> Accuracy: 0.6087, MCC: 0.2038, F1: 0.5500

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 112). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 112). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 112). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.49868 | val 1.10698
  Epoch 015 - train 0.38076 | val 1.71121
  Classification -> best τ=0.550 (val F1=0.3100)
  Directional -> Accuracy: 0.5075, MCC: 0.0027, F1: 0.4407

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.46496 | val 0.77726
  Epoch 018 - train 0.34244 | val 1.36534
  Classification -> best τ=0.595 (val F1=0.3390)
  Directional -> Accuracy: 0.5957, MCC: 0.2346, F1: 0.1739

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.49434 | val 1.42375
  Epoch 011 - train 0.48507 | val 1.72622
  Classification -> best τ=0.460 (val F1=0.1386)
  Directional -> Accuracy: 0.5636, MCC: 0.2052, F1: 0.7073

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 112). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.43808 | val 0.94661
  Epoch 011 - train 0.42661 | val 1.07948
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4792, MCC: 0.0000, F1: 0.6479

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 112). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.53829 | val 0.80494
  Epoch 015 - train 0.47388 | val 1.54488
  Classification -> best τ=0.405 (val F1=0.3013)
  Directional -> Accuracy: 0.5690, MCC: 0.1597, F1: 0.4898

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.46674 | val 0.79651
  Epoch 011 - train 0.45655 | val 0.82410
  Classification -> best τ=0.495 (val F1=0.1555)
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.51446 | val 1.02349
  Epoch 014 - train 0.45249 | val 1.25107
  Classification -> best τ=0.530 (val F1=0.2630)
  Directional -> Accuracy: 0.5075, MCC: 0.0525, F1: 0.4000

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 112). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.52897 | val 3.40134
  Epoch 011 - train 0.50799 | val 3.82994
  Classification -> best τ=0.485 (val F1=0.0715)
  Directional -> Accuracy: 0.4107, MCC: 0.0290, F1: 0.1081

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.53800 | val 0.89265
  Epoch 011 - train 0.52973 | val 0.85926
  Classification -> best τ=0.480 (val F1=0.1829)
  Directional -> Accuracy: 0.4110, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.51300 | val 0.68648
  Epoch 015 - train 0.45327 | val 0.88106
  Classification -> best τ=0.245 (val F1=0.2483)
  Directional -> Accuracy: 0.5161, MCC: 0.0487, F1: 0.5312

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 112). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.49764 | val 0.97919
  Epoch 014 - train 0.44995 | val 1.07773
  Classification -> best τ=0.415 (val F1=0.2737)
  Directional -> Accuracy: 0.5694, MCC: 0.2524, F1: 0.4364

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.47611 | val 0.94260
  Epoch 014 - train 0.38686 | val 1.64970
  Classification -> best τ=0.580 (val F1=0.1929)
  Directional -> Accuracy: 0.4222, MCC: -0.0250, F1: 0.2353

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 112). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 112). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 112). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.52859 | val 0.79305
  Epoch 015 - train 0.43968 | val 1.02583
  Classification -> best τ=0.480 (val F1=0.1706)
  Directional -> Accuracy: 0.5079, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.51531 | val 1.70433
  Epoch 011 - train 0.49824 | val 2.00947
  Classification -> best τ=0.500 (val F1=0.1183)
  Directional -> Accuracy: 0.5455, MCC: 0.2396, F1: 0.4186

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.51334 | val 1.27199
  Epoch 012 - train 0.48205 | val 1.38435
  Classification -> best τ=0.475 (val F1=0.1567)
  Directional -> Accuracy: 0.5238, MCC: 0.1348, F1: 0.6512

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.48796 | val 0.72923
  Epoch 017 - train 0.37142 | val 1.08146
  Classification -> best τ=0.320 (val F1=0.3604)
  Directional -> Accuracy: 0.5849, MCC: 0.1847, F1: 0.5769

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.50306 | val 0.77141
  Epoch 011 - train 0.49208 | val 0.83446
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.51236 | val 0.76800
  Epoch 011 - train 0.49910 | val 0.82255
  Classification -> best τ=0.480 (val F1=0.0956)
  Directional -> Accuracy: 0.4583, MCC: -0.1704, F1: 0.5806

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.53019 | val 0.74646
  Epoch 019 - train 0.39581 | val 0.81000
  Classification -> best τ=0.540 (val F1=0.2552)
  Directional -> Accuracy: 0.4630, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
Insufficient data for proper time series validation for MDT. Skipping...

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.48862 | val 0.96172
  Epoch 011 - train 0.47314 | val 1.04505
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.52806 | val 0.72700
  Epoch 011 - train 0.51492 | val 0.75009
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5500, MCC: 0.0000, F1: 0.7097

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.49971 | val 0.68975
  Epoch 019 - train 0.32603 | val 1.23120
  Classification -> best τ=0.410 (val F1=0.3545)
  Directional -> Accuracy: 0.6170, MCC: 0.3078, F1: 0.7188

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.51079 | val 0.90229
  Epoch 015 - train 0.44579 | val 0.94069
  Classification -> best τ=0.390 (val F1=0.4111)
  Directional -> Accuracy: 0.5429, MCC: 0.1852, F1: 0.4074

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 112). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.51106 | val 0.69388
  Epoch 017 - train 0.38069 | val 1.06683
  Classification -> best τ=0.460 (val F1=0.3419)
  Directional -> Accuracy: 0.5510, MCC: 0.0832, F1: 0.3889

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for PCG (101 < 112). Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.51145 | val 1.17127
  Epoch 011 - train 0.49095 | val 1.20986
  Classification -> best τ=0.465 (val F1=0.3397)
  Directional -> Accuracy: 0.5781, MCC: 0.1463, F1: 0.6197

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.46077 | val 0.70782
  Epoch 011 - train 0.44881 | val 0.71847
  Classification -> best τ=0.495 (val F1=0.3498)
  Directional -> Accuracy: 0.6327, MCC: 0.2754, F1: 0.5500

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.49358 | val 1.14040
  Epoch 012 - train 0.47423 | val 1.33605
  Classification -> best τ=0.480 (val F1=0.1924)
  Directional -> Accuracy: 0.5741, MCC: 0.1738, F1: 0.6102

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.43448 | val 1.15097
  Epoch 012 - train 0.40904 | val 1.45489
  Classification -> best τ=0.490 (val F1=0.2867)
  Directional -> Accuracy: 0.5000, MCC: -0.0321, F1: 0.5769

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 112). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for PPL (108 < 112). Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 112). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 112). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 112). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.50239 | val 0.70309
  Epoch 016 - train 0.43357 | val 0.74894
  Classification -> best τ=0.525 (val F1=0.3458)
  Directional -> Accuracy: 0.5333, MCC: 0.0316, F1: 0.4000

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 112). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 112). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 112). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.47902 | val 1.56491
  Epoch 011 - train 0.46800 | val 1.52632
  Classification -> best τ=0.475 (val F1=0.1154)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 112). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 112). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 112). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 112). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.47168 | val 0.72061
  Epoch 011 - train 0.45956 | val 0.74092
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.6769

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.51665 | val 0.69429
  Epoch 019 - train 0.41714 | val 0.74090
  Classification -> best τ=0.530 (val F1=0.2414)
  Directional -> Accuracy: 0.5641, MCC: 0.1658, F1: 0.5641

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.47837 | val 0.78223
  Epoch 011 - train 0.46321 | val 0.80317
  Classification -> best τ=0.520 (val F1=0.0598)
  Directional -> Accuracy: 0.3778, MCC: 0.0000, F1: 0.5484

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.53697 | val 0.80926
  Epoch 016 - train 0.45264 | val 1.04947
  Classification -> best τ=0.575 (val F1=0.2034)
  Directional -> Accuracy: 0.5472, MCC: 0.2429, F1: 0.3333

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.48079 | val 1.94466
  Epoch 011 - train 0.47424 | val 2.01222
  Classification -> best τ=0.470 (val F1=0.2000)
  Directional -> Accuracy: 0.5185, MCC: 0.1374, F1: 0.6750

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.53071 | val 1.24915
  Epoch 012 - train 0.50239 | val 1.52107
  Classification -> best τ=0.455 (val F1=0.2777)
  Directional -> Accuracy: 0.5490, MCC: 0.2451, F1: 0.6849

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.51964 | val 1.78176
  Epoch 011 - train 0.50415 | val 1.87763
  Classification -> best τ=0.495 (val F1=0.1133)
  Directional -> Accuracy: 0.5094, MCC: 0.0000, F1: 0.6750

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.52028 | val 0.72872

[I 2026-02-22 09:36:00,411] Trial 58 finished with value: 0.19674646947059526 and parameters: {'feature_set': 'sector', 'model_type': 'LSTM', 'sequence_length': 36, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 64, 'num_layers': 2, 'inter_rnn_drop': 0.0, 'dropout': 0.0, 'batch_size': 32, 'learning_rate': 0.0009226761249256702, 'weight_decay': 9.935291380872208e-07, 'lr_patience': 5, 'lr_factor': 0.8, 'early_stopping_patience': 10, 'max_epochs': 50, 'huber_delta': 1.582502648197323, 'early_stopping_min_delta': 0.0012887430901833874}. Best is trial 22 with value: 0.2833350641483003.

  Epoch 016 - train 0.44939 | val 0.96919
  Classification -> best τ=0.630 (val F1=0.2591)
  Directional -> Accuracy: 0.5345, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 47/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (47, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.19674646947059526
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: classification
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.59114 | val 1.09740
  Epoch 014 - train 0.49040 | val 0.72294
  Classification -> best τ=0.290 (val F1=0.2163)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.32434 | val 1.22879
  Epoch 011 - train 0.30025 | val 1.33085
  Classification -> best τ=0.410 (val F1=0.2014)
  Directional -> Accuracy: 0.5870, MCC: 0.1700, F1: 0.7324

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.44166 | val 2.32755
  Epoch 012 - train 0.41402 | val 2.25995
  Classification -> best τ=0.535 (val F1=0.3307)
  Directional -> Accuracy: 0.5957, MCC: 0.1937, F1: 0.6984

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.51125 | val 1.96359
  Epoch 011 - train 0.53834 | val 2.37699
  Classification -> best τ=0.350 (val F1=0.0556)
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.43460 | val 1.05214
  Epoch 011 - train 0.42488 | val 1.49100
  Classification -> best τ=0.545 (val F1=0.3808)
  Directional -> Accuracy: 0.5490, MCC: 0.1136, F1: 0.5106

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.46648 | val 1.48801
  Epoch 013 - train 0.37088 | val 1.22901
  Classification -> best τ=0.575 (val F1=0.4062)
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.49802 | val 0.81336
  Epoch 011 - train 0.47167 | val 1.20631
  Classification -> best τ=0.505 (val F1=0.2130)
  Directional -> Accuracy: 0.5652, MCC: 0.1087, F1: 0.4828

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.42504 | val 2.70285
  Epoch 015 - train 0.30446 | val 3.22115
  Classification -> best τ=0.435 (val F1=0.0792)
  Directional -> Accuracy: 0.5909, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.45377 | val 0.97674
  Epoch 012 - train 0.43435 | val 1.07187
  Classification -> best τ=0.510 (val F1=0.1505)
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.45026 | val 1.39388
  Epoch 011 - train 0.45184 | val 1.54749
  Classification -> best τ=0.500 (val F1=0.1137)
  Directional -> Accuracy: 0.4571, MCC: -0.1083, F1: 0.3667

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.48429 | val 1.78642
  Epoch 011 - train 0.43199 | val 1.99313
  Classification -> best τ=0.615 (val F1=0.2151)
  Directional -> Accuracy: 0.5000, MCC: 0.0032, F1: 0.4898

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.46979 | val 2.37686
  Epoch 011 - train 0.44281 | val 2.78701
  Classification -> best τ=0.390 (val F1=0.2943)
  Directional -> Accuracy: 0.5172, MCC: 0.0614, F1: 0.6585

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.44904 | val 1.50922
  Epoch 011 - train 0.39054 | val 1.65041
  Classification -> best τ=0.485 (val F1=0.2778)
  Directional -> Accuracy: 0.3721, MCC: -0.2383, F1: 0.4000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.54344 | val 0.70666
  Epoch 012 - train 0.50279 | val 0.63914
  Classification -> best τ=0.485 (val F1=0.4124)
  Directional -> Accuracy: 0.4918, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.46309 | val 0.72558
  Epoch 011 - train 0.42781 | val 0.87715
  Classification -> best τ=0.425 (val F1=0.0588)
  Directional -> Accuracy: 0.6346, MCC: 0.2902, F1: 0.4242

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.49279 | val 1.21416
  Epoch 011 - train 0.45739 | val 1.09723
  Classification -> best τ=0.595 (val F1=0.2179)
  Directional -> Accuracy: 0.5571, MCC: 0.0976, F1: 0.6173

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.50103 | val 1.46163
  Epoch 011 - train 0.46857 | val 1.97823
  Classification -> best τ=0.560 (val F1=0.2294)
  Directional -> Accuracy: 0.3729, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.53946 | val 1.39976
  Epoch 011 - train 0.47046 | val 1.06027
  Classification -> best τ=0.655 (val F1=0.1354)
  Directional -> Accuracy: 0.4211, MCC: -0.1852, F1: 0.5000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.57454 | val 0.83467
  Epoch 014 - train 0.45694 | val 1.13711
  Classification -> best τ=0.235 (val F1=0.3603)
  Directional -> Accuracy: 0.5385, MCC: 0.1728, F1: 0.4643

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.48412 | val 1.07250
  Epoch 012 - train 0.52195 | val 0.89433
  Classification -> best τ=0.380 (val F1=0.2924)
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.43212 | val 1.22280
  Epoch 016 - train 0.28700 | val 1.13623
  Classification -> best τ=0.355 (val F1=0.2949)
  Directional -> Accuracy: 0.4792, MCC: 0.0110, F1: 0.4898

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.53096 | val 1.09326
  Epoch 011 - train 0.48381 | val 1.09413
  Classification -> best τ=0.450 (val F1=0.2411)
  Directional -> Accuracy: 0.5455, MCC: 0.1476, F1: 0.2500

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.54400 | val 2.02401
  Epoch 012 - train 0.45723 | val 1.73547
  Classification -> best τ=0.550 (val F1=0.3286)
  Directional -> Accuracy: 0.5345, MCC: 0.0555, F1: 0.5846

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.49887 | val 0.97935
  Epoch 011 - train 0.47845 | val 0.91517
  Classification -> best τ=0.395 (val F1=0.1664)
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.6392

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.48754 | val 0.76944
  Epoch 014 - train 0.38463 | val 0.97133
  Classification -> best τ=0.615 (val F1=0.3404)
  Directional -> Accuracy: 0.6071, MCC: 0.2504, F1: 0.5769

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.41671 | val 0.78113
  Epoch 011 - train 0.43562 | val 0.81360
  Classification -> best τ=0.395 (val F1=0.2774)
  Directional -> Accuracy: 0.4783, MCC: -0.0269, F1: 0.4783

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.46392 | val 0.84262
  Epoch 013 - train 0.44500 | val 1.57787
  Classification -> best τ=0.610 (val F1=0.1309)
  Directional -> Accuracy: 0.4186, MCC: 0.0000, F1: 0.0000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.46234 | val 1.08703
  Epoch 012 - train 0.45663 | val 0.96315
  Classification -> best τ=0.345 (val F1=0.2789)
  Directional -> Accuracy: 0.4561, MCC: -0.1758, F1: 0.5867

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.43012 | val 0.99386
  Epoch 012 - train 0.36094 | val 1.43749
  Classification -> best τ=0.545 (val F1=0.2833)
  Directional -> Accuracy: 0.4634, MCC: -0.0528, F1: 0.3889

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.39394 | val 2.00038
  Epoch 011 - train 0.35785 | val 2.29829
  Classification -> best τ=0.555 (val F1=0.2683)
  Directional -> Accuracy: 0.4884, MCC: -0.0288, F1: 0.4211

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.46161 | val 2.40392
  Epoch 011 - train 0.42599 | val 1.57944
  Classification -> best τ=0.570 (val F1=0.1161)
  Directional -> Accuracy: 0.5581, MCC: 0.1822, F1: 0.4242

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.43436 | val 1.38427
  Epoch 011 - train 0.41799 | val 1.47132
  Classification -> best τ=0.530 (val F1=0.2325)
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.51907 | val 1.04415
  Epoch 011 - train 0.47322 | val 0.99440
  Classification -> best τ=0.485 (val F1=0.2725)
  Directional -> Accuracy: 0.4384, MCC: 0.0000, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.44435 | val 1.03861
  Epoch 011 - train 0.41061 | val 1.61164
  Classification -> best τ=0.420 (val F1=0.3974)
  Directional -> Accuracy: 0.5526, MCC: 0.1195, F1: 0.6383

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.52051 | val 0.88726
  Epoch 011 - train 0.46438 | val 1.38459
  Classification -> best τ=0.440 (val F1=0.2757)
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.48588 | val 0.95018
  Epoch 017 - train 0.36815 | val 1.30865
  Classification -> best τ=0.615 (val F1=0.3542)
  Directional -> Accuracy: 0.4627, MCC: 0.1532, F1: 0.1000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.41054 | val 0.95889
  Epoch 011 - train 0.36787 | val 0.89655
  Classification -> best τ=0.530 (val F1=0.2819)
  Directional -> Accuracy: 0.6512, MCC: 0.3030, F1: 0.6512

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.45805 | val 1.86727
  Epoch 011 - train 0.45230 | val 1.80227
  Classification -> best τ=0.320 (val F1=0.1920)
  Directional -> Accuracy: 0.5439, MCC: 0.1452, F1: 0.6389

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.35567 | val 1.10284
  Epoch 011 - train 0.31698 | val 1.20731
  Classification -> best τ=0.490 (val F1=0.2718)
  Directional -> Accuracy: 0.6170, MCC: 0.0000, F1: 0.7632

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.45850 | val 0.93517
  Epoch 012 - train 0.38361 | val 0.86828
  Classification -> best τ=0.565 (val F1=0.4141)
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.40223 | val 1.94089
  Epoch 011 - train 0.36499 | val 2.27808
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.43960 | val 1.84046
  Epoch 011 - train 0.50132 | val 2.17149
  Classification -> best τ=0.320 (val F1=0.2470)
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.36809 | val 0.98537
  Epoch 011 - train 0.31567 | val 2.26778
  Classification -> best τ=0.505 (val F1=0.2030)
  Directional -> Accuracy: 0.5106, MCC: 0.0081, F1: 0.6462

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.41194 | val 2.15819
  Epoch 011 - train 0.35819 | val 2.47906
  Classification -> best τ=0.560 (val F1=0.4655)
  Directional -> Accuracy: 0.5000, MCC: 0.0462, F1: 0.4500

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.38585 | val 2.25360
  Epoch 011 - train 0.35885 | val 1.70561
  Classification -> best τ=0.395 (val F1=0.2626)
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.49299 | val 0.77271
  Epoch 011 - train 0.44323 | val 0.84421
  Classification -> best τ=0.550 (val F1=0.2077)
  Directional -> Accuracy: 0.5893, MCC: 0.2397, F1: 0.4889

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.44683 | val 1.27674
  Epoch 012 - train 0.39218 | val 1.57014
  Classification -> best τ=0.590 (val F1=0.2777)
  Directional -> Accuracy: 0.4737, MCC: -0.1217, F1: 0.1667

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.49655 | val 2.21162
  Epoch 011 - train 0.47681 | val 2.46417
  Classification -> best τ=0.420 (val F1=0.2665)
  Directional -> Accuracy: 0.5556, MCC: 0.1520, F1: 0.6923

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.47880 | val 1.17783
  Epoch 011 - train 0.47302 | val 1.72376
  Classification -> best τ=0.465 (val F1=0.1446)
  Directional -> Accuracy: 0.5179, MCC: 0.0000, F1: 0.6824

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...

[I 2026-02-22 09:36:46,940] Trial 59 finished with value: 0.24973174017350833 and parameters: {'feature_set': 'sector', 'model_type': 'GRU', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 64, 'num_layers': 2, 'inter_rnn_drop': 0.0, 'dropout': 0.0, 'batch_size': 32, 'learning_rate': 0.003968509399086791, 'weight_decay': 6.306365757156223e-07, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 10, 'max_epochs': 50, 'huber_delta': 1.2819977751734197, 'early_stopping_min_delta': 0.0030108030739149274}. Best is trial 22 with value: 0.2833350641483003.

  Epoch 010 - train 0.44584 | val 0.82155
  Epoch 011 - train 0.41041 | val 1.17904
  Classification -> best τ=0.565 (val F1=0.3526)
  Directional -> Accuracy: 0.6066, MCC: 0.2079, F1: 0.5556

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.24973174017350833
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 6
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.64881 | val 0.69534
  Epoch 014 - train 0.64083 | val 0.70488
  Classification -> best τ=0.540 (val F1=0.1407)
  Directional -> Accuracy: 0.5316, MCC: -0.0330, F1: 0.1778

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 82). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.64843 | val 0.72002
  Epoch 011 - train 0.64375 | val 0.72344
  Classification -> best τ=0.520 (val F1=0.0258)
  Directional -> Accuracy: 0.3958, MCC: -0.1680, F1: 0.2162

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 82). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.65676 | val 0.73109
  Epoch 011 - train 0.63990 | val 0.74478
  Classification -> best τ=0.555 (val F1=0.1191)
  Directional -> Accuracy: 0.4694, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.66164 | val 0.78111
  Epoch 011 - train 0.65247 | val 0.77770
  Classification -> best τ=0.535 (val F1=0.1612)
  Directional -> Accuracy: 0.4805, MCC: 0.0962, F1: 0.1304

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.63933 | val 0.64301
  Epoch 020 - train 0.61422 | val 0.63185
  Classification -> best τ=0.415 (val F1=0.4337)
  Directional -> Accuracy: 0.6792, MCC: 0.3629, F1: 0.6792

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.64670 | val 0.71312
  Epoch 014 - train 0.62698 | val 0.72275
  Classification -> best τ=0.505 (val F1=0.1718)
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.67827 | val 0.67812
  Epoch 015 - train 0.66457 | val 0.69065
  Classification -> best τ=0.485 (val F1=0.3333)
  Directional -> Accuracy: 0.5070, MCC: 0.0990, F1: 0.5570

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 82). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 82). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.63210 | val 0.78021
  Epoch 011 - train 0.63610 | val 0.80412
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4043, MCC: 0.0000, F1: 0.5758

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.66039 | val 0.74933
  Epoch 011 - train 0.66358 | val 0.75665
  Classification -> best τ=0.540 (val F1=0.2731)
  Directional -> Accuracy: 0.6512, MCC: 0.2323, F1: 0.2857

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 82). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 82). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.64329 | val 0.76706
  Epoch 011 - train 0.64550 | val 0.77037
  Classification -> best τ=0.520 (val F1=0.1838)
  Directional -> Accuracy: 0.4306, MCC: -0.0423, F1: 0.5773

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.66144 | val 0.77619
  Epoch 011 - train 0.65797 | val 0.77990
  Classification -> best τ=0.550 (val F1=0.3006)
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.65962 | val 0.76785
  Epoch 011 - train 0.66081 | val 0.77154
  Classification -> best τ=0.495 (val F1=0.1421)
  Directional -> Accuracy: 0.6167, MCC: 0.2446, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.61787 | val 0.81167
  Epoch 011 - train 0.61819 | val 0.81580
  Classification -> best τ=0.520 (val F1=0.0364)
  Directional -> Accuracy: 0.4889, MCC: -0.0364, F1: 0.4103

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 82). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.64790 | val 0.65331
  Epoch 016 - train 0.63016 | val 0.65541
  Classification -> best τ=0.455 (val F1=0.3402)
  Directional -> Accuracy: 0.5238, MCC: 0.0454, F1: 0.3750

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.65239 | val 0.81244
  Epoch 011 - train 0.64307 | val 0.82733
  Classification -> best τ=0.510 (val F1=0.1605)
  Directional -> Accuracy: 0.5370, MCC: 0.0663, F1: 0.2857

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.64465 | val 0.70921
  Epoch 011 - train 0.64670 | val 0.71005
  Classification -> best τ=0.515 (val F1=0.0992)
  Directional -> Accuracy: 0.6528, MCC: 0.3058, F1: 0.7312

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.64097 | val 0.80269
  Epoch 011 - train 0.64566 | val 0.81308
  Classification -> best τ=0.540 (val F1=0.0979)
  Directional -> Accuracy: 0.3934, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.65653 | val 0.75847
  Epoch 011 - train 0.65454 | val 0.76144
  Classification -> best τ=0.485 (val F1=0.1900)
  Directional -> Accuracy: 0.3974, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.65213 | val 0.67659
  Epoch 020 - train 0.63138 | val 0.67580
  Classification -> best τ=0.385 (val F1=0.2933)
  Directional -> Accuracy: 0.5373, MCC: 0.1907, F1: 0.4364

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 82). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.64442 | val 0.66647
  Epoch 018 - train 0.62891 | val 0.67221
  Classification -> best τ=0.420 (val F1=0.2747)
  Directional -> Accuracy: 0.4545, MCC: -0.0265, F1: 0.1250

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.65454 | val 0.68422
  Epoch 011 - train 0.64975 | val 0.68306
  Classification -> best τ=0.555 (val F1=0.0528)
  Directional -> Accuracy: 0.3800, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 82). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 82). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 82). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.67134 | val 0.68606
  Epoch 020 - train 0.65290 | val 0.68723
  Classification -> best τ=0.315 (val F1=0.1741)
  Directional -> Accuracy: 0.5147, MCC: 0.0716, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.66261 | val 0.70087
  Epoch 015 - train 0.64699 | val 0.71711
  Classification -> best τ=0.475 (val F1=0.3031)
  Directional -> Accuracy: 0.6000, MCC: 0.1121, F1: 0.7333

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.65094 | val 0.94739
  Epoch 011 - train 0.64761 | val 0.97009
  Classification -> best τ=0.485 (val F1=0.1846)
  Directional -> Accuracy: 0.5147, MCC: 0.0000, F1: 0.0000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.64343 | val 0.64786
  Epoch 020 - train 0.62399 | val 0.64343
  Classification -> best τ=0.485 (val F1=0.4987)
  Directional -> Accuracy: 0.5862, MCC: 0.2163, F1: 0.5385

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.64948 | val 0.72384
  Epoch 011 - train 0.65045 | val 0.72838
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.64398 | val 0.71181
  Epoch 011 - train 0.64133 | val 0.71229
  Classification -> best τ=0.510 (val F1=0.0403)
  Directional -> Accuracy: 0.6222, MCC: 0.1588, F1: 0.7302

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.63321 | val 0.73782
  Epoch 011 - train 0.64108 | val 0.74481
  Classification -> best τ=0.450 (val F1=0.2045)
  Directional -> Accuracy: 0.4576, MCC: 0.1166, F1: 0.0588

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.67279 | val 0.68564
  Epoch 020 - train 0.65793 | val 0.67739
  Classification -> best τ=0.605 (val F1=0.2345)
  Directional -> Accuracy: 0.4773, MCC: -0.0247, F1: 0.3030

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.66930 | val 0.72077
  Epoch 011 - train 0.66058 | val 0.72439
  Classification -> best τ=0.500 (val F1=0.0065)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0800

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.65961 | val 0.72783
  Epoch 011 - train 0.67236 | val 0.73433
  Classification -> best τ=0.485 (val F1=0.1995)
  Directional -> Accuracy: 0.4783, MCC: -0.0289, F1: 0.4545

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.63925 | val 0.69648
  Epoch 020 - train 0.60338 | val 0.68460
  Classification -> best τ=0.465 (val F1=0.2935)
  Directional -> Accuracy: 0.5577, MCC: 0.1344, F1: 0.6849

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.65415 | val 0.67521
  Epoch 020 - train 0.63070 | val 0.67328
  Classification -> best τ=0.475 (val F1=0.2843)
  Directional -> Accuracy: 0.4400, MCC: -0.0200, F1: 0.0455

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 82). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.65603 | val 0.69580
  Epoch 011 - train 0.65569 | val 0.69895
  Classification -> best τ=0.520 (val F1=0.1459)
  Directional -> Accuracy: 0.4878, MCC: -0.0290, F1: 0.4324

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.63744 | val 0.74759
  Epoch 011 - train 0.62871 | val 0.75728
  Classification -> best τ=0.500 (val F1=0.0981)
  Directional -> Accuracy: 0.5217, MCC: 0.0063, F1: 0.3529

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.64133 | val 0.65762
  Epoch 017 - train 0.63035 | val 0.66054
  Classification -> best τ=0.310 (val F1=0.3376)
  Directional -> Accuracy: 0.6377, MCC: 0.2968, F1: 0.6479

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.65004 | val 0.67245
  Epoch 020 - train 0.61482 | val 0.66949
  Classification -> best τ=0.435 (val F1=0.4176)
  Directional -> Accuracy: 0.5556, MCC: 0.1093, F1: 0.5833

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.63627 | val 0.77028
  Epoch 011 - train 0.63539 | val 0.77140
  Classification -> best τ=0.560 (val F1=0.1361)
  Directional -> Accuracy: 0.5424, MCC: 0.0840, F1: 0.5263

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.64755 | val 0.79875
  Epoch 011 - train 0.65172 | val 0.81454
  Classification -> best τ=0.455 (val F1=0.2973)
  Directional -> Accuracy: 0.6122, MCC: 0.1457, F1: 0.7077

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 82). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 82). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 82). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 82). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.64674 | val 0.69035
  Epoch 011 - train 0.63099 | val 0.69208
  Classification -> best τ=0.490 (val F1=0.3708)
  Directional -> Accuracy: 0.4762, MCC: 0.0714, F1: 0.4762

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 82). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.65612 | val 0.69647
  Epoch 011 - train 0.65867 | val 0.69786
  Classification -> best τ=0.500 (val F1=0.1762)
  Directional -> Accuracy: 0.4390, MCC: -0.1834, F1: 0.5818

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 82). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 82). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.64571 | val 0.73252
  Epoch 011 - train 0.64854 | val 0.73549
  Classification -> best τ=0.520 (val F1=0.2040)
  Directional -> Accuracy: 0.5455, MCC: 0.0982, F1: 0.4776

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 82). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 82). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.66769 | val 0.67161
  Epoch 020 - train 0.64775 | val 0.69497
  Classification -> best τ=0.490 (val F1=0.4354)
  Directional -> Accuracy: 0.5510, MCC: 0.1000, F1: 0.5000

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.64527 | val 0.71131
  Epoch 011 - train 0.65402 | val 0.71974
  Classification -> best τ=0.480 (val F1=0.4000)
  Directional -> Accuracy: 0.5319, MCC: -0.0105, F1: 0.6452

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.66092 | val 0.76611
  Epoch 011 - train 0.63959 | val 0.77983
  Classification -> best τ=0.535 (val F1=0.0551)
  Directional -> Accuracy: 0.3571, MCC: 0.0000, F1: 0.5263

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.66806 | val 0.70117
  Epoch 011 - train 0.65462 | val 0.69985
  Classification -> best τ=0.535 (val F1=0.1055)
  Directional -> Accuracy: 0.4483, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.64756 | val 0.73678
  Epoch 011 - train 0.64517 | val 0.74189
  Classification -> best τ=0.475 (val F1=0.3475)
  Directional -> Accuracy: 0.5254, MCC: 0.0496, F1: 0.5000

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.66313 | val 0.75120
  Epoch 011 - train 0.65763 | val 0.76076
  Classification -> best τ=0.480 (val F1=0.1869)
  Directional -> Accuracy: 0.5536, MCC: 0.1222, F1: 0.5283

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.64105 | val 0.94840
  Epoch 011 - train 0.65052 | val 0.96719
  Classification -> best τ=0.550 (val F1=0.1433)
  Directional -> Accuracy: 0.5172, MCC: 0.0000, F1: 0.6818

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...

[I 2026-02-22 09:37:43,703] Trial 60 finished with value: 0.2080157623389346 and parameters: {'feature_set': 'sector', 'model_type': 'BiGRU', 'sequence_length': 6, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.1, 'dropout': 0.1, 'batch_size': 32, 'learning_rate': 5.1417830767241545e-05, 'weight_decay': 1.1412815828722468e-07, 'lr_patience': 5, 'lr_factor': 0.8, 'early_stopping_patience': 10, 'max_epochs': 20, 'huber_delta': 1.3749564972337782, 'early_stopping_min_delta': 0.0038592241059765544}. Best is trial 22 with value: 0.2833350641483003.

  Epoch 010 - train 0.66241 | val 0.73821
  Epoch 011 - train 0.66621 | val 0.74485
  Classification -> best τ=0.480 (val F1=0.2902)
  Directional -> Accuracy: 0.4762, MCC: 0.0000, F1: 0.6452

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2080157623389346
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: classification
Sequence length: 30
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sentiment']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.51295 | val 1.07458
  Epoch 011 - train 0.48026 | val 0.88526
  Classification -> best τ=0.600 (val F1=0.2085)
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.0000

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 106). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.42496 | val 1.71606
  Epoch 011 - train 0.36262 | val 1.12595
  Classification -> best τ=0.435 (val F1=0.1161)
  Directional -> Accuracy: 0.5682, MCC: -0.1269, F1: 0.7246

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 106). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.35854 | val 1.28964
  Epoch 011 - train 0.31016 | val 1.68543
  Classification -> best τ=0.495 (val F1=0.1644)
  Directional -> Accuracy: 0.4222, MCC: -0.2031, F1: 0.5357

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.56027 | val 0.88915
  Epoch 012 - train 0.47361 | val 1.23987
  Classification -> best τ=0.360 (val F1=0.1219)
  Directional -> Accuracy: 0.5205, MCC: 0.0206, F1: 0.5977

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.35561 | val 1.33029
  Epoch 015 - train 0.16358 | val 2.58232
  Classification -> best τ=0.595 (val F1=0.4080)
  Directional -> Accuracy: 0.5510, MCC: 0.1013, F1: 0.6207

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.33732 | val 3.90601
  Epoch 011 - train 0.31412 | val 3.62959
  Classification -> best τ=0.410 (val F1=0.2294)
  Directional -> Accuracy: 0.5778, MCC: 0.1678, F1: 0.4242

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.51723 | val 0.94925
  Epoch 012 - train 0.44484 | val 1.22690
  Classification -> best τ=0.545 (val F1=0.2847)
  Directional -> Accuracy: 0.5821, MCC: 0.0907, F1: 0.3913

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 106). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 106). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.26225 | val 3.32092
  Epoch 011 - train 0.22531 | val 3.88761
  Classification -> best τ=0.600 (val F1=0.0727)
  Directional -> Accuracy: 0.5610, MCC: 0.0885, F1: 0.4375

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.45291 | val 0.82050
  Epoch 014 - train 0.33183 | val 0.89916
  Classification -> best τ=0.525 (val F1=0.3773)
  Directional -> Accuracy: 0.5319, MCC: -0.0325, F1: 0.1538

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 106). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 106). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 106). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.46510 | val 0.85703
  Epoch 012 - train 0.38582 | val 1.04137
  Classification -> best τ=0.440 (val F1=0.1846)
  Directional -> Accuracy: 0.4265, MCC: 0.0000, F1: 0.5979

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.46752 | val 1.50258
  Epoch 011 - train 0.43619 | val 1.73281
  Classification -> best τ=0.500 (val F1=0.1816)
  Directional -> Accuracy: 0.4583, MCC: 0.0000, F1: 0.6286

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.41337 | val 1.18146
  Epoch 012 - train 0.40979 | val 1.29824
  Classification -> best τ=0.395 (val F1=0.1448)
  Directional -> Accuracy: 0.5179, MCC: 0.0069, F1: 0.6747

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 106). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.37776 | val 4.54967
  Epoch 011 - train 0.34355 | val 5.06275
  Classification -> best τ=0.440 (val F1=0.2094)
  Directional -> Accuracy: 0.4898, MCC: -0.0256, F1: 0.4186

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 106). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.37516 | val 2.21292
  Epoch 011 - train 0.33308 | val 1.48053
  Classification -> best τ=0.455 (val F1=0.2976)
  Directional -> Accuracy: 0.5424, MCC: 0.0884, F1: 0.5091

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.48041 | val 1.60746
  Epoch 011 - train 0.40001 | val 1.27571
  Classification -> best τ=0.415 (val F1=0.2550)
  Directional -> Accuracy: 0.5600, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.46432 | val 1.10794
  Epoch 011 - train 0.52877 | val 1.44209
  Classification -> best τ=0.565 (val F1=0.1620)
  Directional -> Accuracy: 0.5147, MCC: 0.1255, F1: 0.2326

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 106). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.51862 | val 3.02996
  Epoch 011 - train 0.46197 | val 2.93544
  Classification -> best τ=0.580 (val F1=0.1890)
  Directional -> Accuracy: 0.5439, MCC: -0.2178, F1: 0.7045

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.52561 | val 1.26615
  Epoch 018 - train 0.35616 | val 1.32922
  Classification -> best τ=0.660 (val F1=0.2699)
  Directional -> Accuracy: 0.4189, MCC: 0.0966, F1: 0.0444

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.48277 | val 1.01490
  Epoch 011 - train 0.43390 | val 1.38161
  Classification -> best τ=0.515 (val F1=0.1300)
  Directional -> Accuracy: 0.4127, MCC: -0.0575, F1: 0.1395

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 106). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.66064 | val 0.87714
  Epoch 013 - train 0.43976 | val 1.20710
  Classification -> best τ=0.555 (val F1=0.3060)
  Directional -> Accuracy: 0.4521, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.29051 | val 1.13630
  Epoch 011 - train 0.26826 | val 1.37286
  Classification -> best τ=0.490 (val F1=0.1921)
  Directional -> Accuracy: 0.3913, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 106). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 106). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 106). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.46463 | val 1.66562
  Epoch 011 - train 0.43956 | val 2.19461
  Classification -> best τ=0.620 (val F1=0.0081)
  Directional -> Accuracy: 0.4844, MCC: -0.0388, F1: 0.2667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.46987 | val 2.20212
  Epoch 011 - train 0.43628 | val 2.72844
  Classification -> best τ=0.705 (val F1=0.2798)
  Directional -> Accuracy: 0.5536, MCC: 0.1362, F1: 0.5455

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.54816 | val 0.80005
  Epoch 015 - train 0.42110 | val 1.19134
  Classification -> best τ=0.315 (val F1=0.2531)
  Directional -> Accuracy: 0.4688, MCC: 0.0000, F1: 0.6383

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.38308 | val 0.68324
  Epoch 014 - train 0.29343 | val 1.12469
  Classification -> best τ=0.630 (val F1=0.3954)
  Directional -> Accuracy: 0.4630, MCC: 0.0000, F1: 0.0000

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.38611 | val 1.50190
  Epoch 011 - train 0.36284 | val 1.36960
  Classification -> best τ=0.575 (val F1=0.3240)
  Directional -> Accuracy: 0.4419, MCC: 0.1309, F1: 0.6000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.32477 | val 2.41732
  Epoch 011 - train 0.26458 | val 3.25714
  Classification -> best τ=0.450 (val F1=0.1845)
  Directional -> Accuracy: 0.5918, MCC: 0.0698, F1: 0.7222

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.43584 | val 1.32356
  Epoch 011 - train 0.38977 | val 1.40552
  Classification -> best τ=0.435 (val F1=0.2452)
  Directional -> Accuracy: 0.5273, MCC: 0.2023, F1: 0.2778

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.32886 | val 0.97469
  Epoch 013 - train 0.27508 | val 1.31117
  Classification -> best τ=0.570 (val F1=0.2955)
  Directional -> Accuracy: 0.5526, MCC: 0.0458, F1: 0.6792

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.36852 | val 1.37434
  Epoch 011 - train 0.35739 | val 2.07357
  Classification -> best τ=0.520 (val F1=0.2550)
  Directional -> Accuracy: 0.4878, MCC: 0.0000, F1: 0.6557

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.36312 | val 2.16418
  Epoch 012 - train 0.27229 | val 3.34624
  Classification -> best τ=0.590 (val F1=0.1336)
  Directional -> Accuracy: 0.5610, MCC: 0.0000, F1: 0.7188

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.52840 | val 0.80521
  Epoch 012 - train 0.44167 | val 0.87245
  Classification -> best τ=0.830 (val F1=0.2382)
  Directional -> Accuracy: 0.5417, MCC: 0.0893, F1: 0.5217

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.56949 | val 1.12020
  Epoch 011 - train 0.51248 | val 1.07944
  Classification -> best τ=0.325 (val F1=0.2961)
  Directional -> Accuracy: 0.5775, MCC: 0.1781, F1: 0.5714

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 106). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.38765 | val 1.05859
  Epoch 012 - train 0.25939 | val 1.36079
  Classification -> best τ=0.630 (val F1=0.4647)
  Directional -> Accuracy: 0.5238, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for PCG (101 < 106). Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.53121 | val 1.20359
  Epoch 011 - train 0.45219 | val 1.44305
  Classification -> best τ=0.420 (val F1=0.4254)
  Directional -> Accuracy: 0.5692, MCC: 0.1142, F1: 0.6316

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.34100 | val 1.19705
  Epoch 011 - train 0.30399 | val 1.38930
  Classification -> best τ=0.505 (val F1=0.2697)
  Directional -> Accuracy: 0.7250, MCC: 0.4579, F1: 0.7179

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.45215 | val 1.65532
  Epoch 011 - train 0.37527 | val 1.86966
  Classification -> best τ=0.390 (val F1=0.1918)
  Directional -> Accuracy: 0.4727, MCC: -0.0531, F1: 0.4528

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.30936 | val 2.37963
  Epoch 011 - train 0.26783 | val 3.62489
  Classification -> best τ=0.560 (val F1=0.2730)
  Directional -> Accuracy: 0.6000, MCC: 0.0162, F1: 0.7353

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 106). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 106). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 106). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 106). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.46582 | val 0.93613
  Epoch 015 - train 0.31580 | val 1.60021
  Classification -> best τ=0.550 (val F1=0.4326)
  Directional -> Accuracy: 0.3261, MCC: 0.0000, F1: 0.4918

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 106). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 106). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 106). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.50184 | val 2.03926
  Epoch 012 - train 0.55061 | val 3.52387
  Classification -> best τ=0.345 (val F1=0.2060)
  Directional -> Accuracy: 0.4932, MCC: 0.0000, F1: 0.6606

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 106). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 106). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 106). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 106). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.42165 | val 1.03081
  Epoch 012 - train 0.35709 | val 1.05351
  Classification -> best τ=0.495 (val F1=0.3536)
  Directional -> Accuracy: 0.5682, MCC: 0.1376, F1: 0.5957

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.42072 | val 0.77393
  Epoch 011 - train 0.39885 | val 0.96399
  Classification -> best τ=0.465 (val F1=0.1762)
  Directional -> Accuracy: 0.5854, MCC: 0.0000, F1: 0.7385

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.31062 | val 1.34973
  Epoch 012 - train 0.23242 | val 2.18431
  Classification -> best τ=0.460 (val F1=0.0608)
  Directional -> Accuracy: 0.3696, MCC: 0.0000, F1: 0.5397

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.44996 | val 1.85633
  Epoch 011 - train 0.41886 | val 2.07894
  Classification -> best τ=0.380 (val F1=0.2410)
  Directional -> Accuracy: 0.4259, MCC: -0.1491, F1: 0.4561

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.50420 | val 1.34697
  Epoch 012 - train 0.44247 | val 1.99357
  Classification -> best τ=0.390 (val F1=0.2464)
  Directional -> Accuracy: 0.4909, MCC: 0.0000, F1: 0.6585

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.49758 | val 0.76750
  Epoch 020 - train 0.10438 | val 1.08411
  Epoch 021 - train 0.06586 | val 1.23501
  Classification -> best τ=0.475 (val F1=0.3008)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.56596 | val 1.72479
  Epoch 014 - train 0.33538 | val 0.99149
  Classification -> best τ=0.505 (val F1=0.1807)
  Directional -> Accuracy: 0.5185, MCC: 0.0447, F1: 0.4800

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.47757 | val 1.76554
  Epoch 012 - train 0.44288 | val 1.85280

[I 2026-02-22 09:38:31,907] Trial 61 finished with value: 0.2366173471277546 and parameters: {'feature_set': 'sentinment', 'model_type': 'GRU', 'sequence_length': 30, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 64, 'num_layers': 1, 'inter_rnn_drop': 0.1, 'dropout': 0.0, 'batch_size': 32, 'learning_rate': 0.007214281798075159, 'weight_decay': 5.130110115747039e-06, 'lr_patience': 5, 'lr_factor': 0.8, 'early_stopping_patience': 10, 'max_epochs': 50, 'huber_delta': 1.6743464578236997, 'early_stopping_min_delta': 0.0028624585672509823}. Best is trial 22 with value: 0.2833350641483003.

  Classification -> best τ=0.325 (val F1=0.1215)
  Directional -> Accuracy: 0.4068, MCC: -0.1944, F1: 0.5333

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2366173471277546
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: classification
Sequence length: 30
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'emotion_anger', 'emotion_disgust', 'emotion_fear', 'emotion_joy', 'emotion_neutral', 'emotion_sadness', 'emotion_surprize', 'emotion_anger_pct', 'emotion_disgust_pct', 'emotion_fear_pct', 'emotion_joy_pct', 'emotion_neutral_pct', 'emotion_sadness_pct', 'emotion_surprize_pct']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.44776 | val 0.72845
  Epoch 011 - train 0.42826 | val 0.74152
  Classification -> best τ=0.560 (val F1=0.1352)
  Directional -> Accuracy: 0.5867, MCC: 0.1473, F1: 0.3673

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 106). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.34531 | val 1.48900
  Epoch 011 - train 0.29203 | val 1.85578
  Classification -> best τ=0.345 (val F1=0.2358)
  Directional -> Accuracy: 0.5909, MCC: 0.0000, F1: 0.7429

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 106). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.35893 | val 1.07890
  Epoch 011 - train 0.26351 | val 1.35269
  Classification -> best τ=0.460 (val F1=0.2414)
  Directional -> Accuracy: 0.6444, MCC: 0.2883, F1: 0.7143

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.54310 | val 2.28237
  Epoch 011 - train 0.51758 | val 3.45298
  Classification -> best τ=0.305 (val F1=0.1593)
  Directional -> Accuracy: 0.5205, MCC: -0.0039, F1: 0.6465

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.30640 | val 1.98321
  Epoch 012 - train 0.25522 | val 2.46773
  Classification -> best τ=0.430 (val F1=0.3748)
  Directional -> Accuracy: 0.6327, MCC: 0.3114, F1: 0.5263

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.36173 | val 0.75464
  Epoch 011 - train 0.39411 | val 0.89797
  Classification -> best τ=0.525 (val F1=0.3241)
  Directional -> Accuracy: 0.5333, MCC: 0.0786, F1: 0.2222

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.47193 | val 0.96290
  Epoch 011 - train 0.38189 | val 1.23517
  Classification -> best τ=0.520 (val F1=0.2014)
  Directional -> Accuracy: 0.5522, MCC: 0.0352, F1: 0.3750

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 106). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 106). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.43084 | val 1.54434
  Epoch 014 - train 0.19514 | val 1.66284
  Classification -> best τ=0.520 (val F1=0.6880)
  Directional -> Accuracy: 0.5366, MCC: 0.0423, F1: 0.4242

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.34193 | val 1.03287
  Epoch 015 - train 0.13985 | val 1.97328
  Classification -> best τ=0.410 (val F1=0.3687)
  Directional -> Accuracy: 0.6596, MCC: 0.3028, F1: 0.5556

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 106). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 106). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 106). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.41515 | val 1.20280
  Epoch 011 - train 0.32633 | val 1.20744
  Classification -> best τ=0.430 (val F1=0.1846)
  Directional -> Accuracy: 0.3971, MCC: -0.2019, F1: 0.5684

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.29002 | val 1.33611
  Epoch 012 - train 0.20384 | val 1.81365
  Classification -> best τ=0.530 (val F1=0.1585)
  Directional -> Accuracy: 0.4583, MCC: -0.0836, F1: 0.4348

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.37540 | val 1.17404
  Epoch 012 - train 0.32072 | val 1.86488
  Classification -> best τ=0.655 (val F1=0.1353)
  Directional -> Accuracy: 0.4643, MCC: -0.1397, F1: 0.0000

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 106). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.28459 | val 4.54506
  Epoch 012 - train 0.15554 | val 5.93587
  Classification -> best τ=0.315 (val F1=0.2788)
  Directional -> Accuracy: 0.4898, MCC: 0.0000, F1: 0.6575

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 106). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.43002 | val 0.97027
  Epoch 013 - train 0.27169 | val 1.11076
  Classification -> best τ=0.405 (val F1=0.3536)
  Directional -> Accuracy: 0.5424, MCC: 0.1057, F1: 0.6667

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.33367 | val 0.86534
  Epoch 012 - train 0.27041 | val 1.25783
  Classification -> best τ=0.455 (val F1=0.0605)
  Directional -> Accuracy: 0.6000, MCC: 0.2303, F1: 0.1667

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.33709 | val 2.32036
  Epoch 011 - train 0.29966 | val 1.81253
  Classification -> best τ=0.455 (val F1=0.3671)
  Directional -> Accuracy: 0.5588, MCC: 0.1399, F1: 0.7000

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 106). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.36679 | val 4.50749
  Epoch 011 - train 0.33359 | val 4.76592
  Classification -> best τ=0.375 (val F1=0.1890)
  Directional -> Accuracy: 0.5439, MCC: -0.0558, F1: 0.6750

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.38172 | val 2.15997
  Epoch 011 - train 0.38974 | val 1.30484
  Classification -> best τ=0.555 (val F1=0.1849)
  Directional -> Accuracy: 0.4054, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.34323 | val 1.70739
  Epoch 011 - train 0.23328 | val 2.28556
  Classification -> best τ=0.490 (val F1=0.1280)
  Directional -> Accuracy: 0.5238, MCC: 0.2157, F1: 0.3750

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 106). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.43108 | val 1.19299
  Epoch 011 - train 0.42187 | val 1.14531
  Classification -> best τ=0.520 (val F1=0.1841)
  Directional -> Accuracy: 0.4521, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.18021 | val 1.47142
  Epoch 011 - train 0.20453 | val 1.81246
  Classification -> best τ=0.480 (val F1=0.1557)
  Directional -> Accuracy: 0.6087, MCC: 0.0000, F1: 0.7568

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 106). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 106). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 106). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.46512 | val 1.18585
  Epoch 011 - train 0.45306 | val 1.30062
  Classification -> best τ=0.585 (val F1=0.1300)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.1111

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.44554 | val 1.48222
  Epoch 011 - train 0.38518 | val 2.40017
  Classification -> best τ=0.660 (val F1=0.2798)
  Directional -> Accuracy: 0.5357, MCC: 0.0620, F1: 0.5806

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.48219 | val 0.78939
  Epoch 014 - train 0.28539 | val 0.84989
  Classification -> best τ=0.435 (val F1=0.1629)
  Directional -> Accuracy: 0.4531, MCC: -0.1341, F1: 0.6237

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.37856 | val 1.16311
  Epoch 012 - train 0.28440 | val 1.42120
  Classification -> best τ=0.520 (val F1=0.3886)
  Directional -> Accuracy: 0.4259, MCC: -0.1628, F1: 0.0606

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.24509 | val 1.29653
  Epoch 011 - train 0.25082 | val 1.52726
  Classification -> best τ=0.585 (val F1=0.1409)
  Directional -> Accuracy: 0.5349, MCC: 0.1480, F1: 0.5833

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.32623 | val 1.93885
  Epoch 011 - train 0.26493 | val 2.66077
  Classification -> best τ=0.530 (val F1=0.2645)
  Directional -> Accuracy: 0.5918, MCC: 0.0000, F1: 0.7436

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.39475 | val 1.33003
  Epoch 011 - train 0.39785 | val 1.56265
  Classification -> best τ=0.425 (val F1=0.2408)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.26971 | val 1.30780
  Epoch 011 - train 0.24734 | val 1.87290
  Classification -> best τ=0.575 (val F1=0.5505)
  Directional -> Accuracy: 0.4211, MCC: -0.1212, F1: 0.2667

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.42087 | val 1.77529
  Epoch 011 - train 0.37222 | val 1.70468
  Classification -> best τ=0.770 (val F1=0.2193)
  Directional -> Accuracy: 0.5122, MCC: 0.0000, F1: 0.0000

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.33369 | val 1.72937
  Epoch 012 - train 0.30601 | val 1.94283
  Classification -> best τ=0.525 (val F1=0.2339)
  Directional -> Accuracy: 0.5610, MCC: 0.0000, F1: 0.7188

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.33960 | val 1.31455
  Epoch 012 - train 0.22645 | val 1.59864
  Classification -> best τ=0.455 (val F1=0.3392)
  Directional -> Accuracy: 0.5208, MCC: 0.0000, F1: 0.6849

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.50397 | val 0.89992
  Epoch 015 - train 0.28819 | val 1.66446
  Classification -> best τ=0.240 (val F1=0.3449)
  Directional -> Accuracy: 0.5634, MCC: 0.1631, F1: 0.5373

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 106). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.35331 | val 1.58022
  Epoch 012 - train 0.23388 | val 1.47704
  Classification -> best τ=0.520 (val F1=0.2386)
  Directional -> Accuracy: 0.5000, MCC: -0.0092, F1: 0.4324

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for PCG (101 < 106). Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.49496 | val 0.99173
  Epoch 011 - train 0.42620 | val 1.01884
  Classification -> best τ=0.260 (val F1=0.2756)
  Directional -> Accuracy: 0.5385, MCC: 0.1359, F1: 0.4828

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.23466 | val 1.31984
  Epoch 011 - train 0.17640 | val 1.35330
  Classification -> best τ=0.505 (val F1=0.4454)
  Directional -> Accuracy: 0.6250, MCC: 0.2781, F1: 0.5714

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.39414 | val 1.83775
  Epoch 011 - train 0.29770 | val 1.71019
  Classification -> best τ=0.365 (val F1=0.2494)
  Directional -> Accuracy: 0.5091, MCC: 0.0671, F1: 0.5846

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.24902 | val 4.23546
  Epoch 012 - train 0.14304 | val 5.17592
  Classification -> best τ=0.640 (val F1=0.2110)
  Directional -> Accuracy: 0.3778, MCC: -0.0787, F1: 0.1250

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 106). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 106). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 106). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 106). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.26973 | val 1.23039
  Epoch 011 - train 0.21735 | val 1.33561
  Classification -> best τ=0.515 (val F1=0.4242)
  Directional -> Accuracy: 0.3261, MCC: 0.0000, F1: 0.4918

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 106). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 106). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 106). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.51689 | val 1.55297
  Epoch 012 - train 0.42029 | val 1.63518
  Classification -> best τ=0.385 (val F1=0.1802)
  Directional -> Accuracy: 0.4932, MCC: 0.0000, F1: 0.6606

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 106). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 106). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 106). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 106). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.33803 | val 0.87424
  Epoch 012 - train 0.30165 | val 1.19999
  Classification -> best τ=0.470 (val F1=0.3536)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.41123 | val 1.01497
  Epoch 011 - train 0.37043 | val 1.04989
  Classification -> best τ=0.470 (val F1=0.0436)
  Directional -> Accuracy: 0.5122, MCC: 0.0840, F1: 0.4737

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.33231 | val 1.14341
  Epoch 013 - train 0.21621 | val 1.63361
  Classification -> best τ=0.720 (val F1=0.2231)
  Directional -> Accuracy: 0.3478, MCC: -0.1947, F1: 0.5161

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.34461 | val 1.37756
  Epoch 012 - train 0.32372 | val 1.60783
  Classification -> best τ=0.530 (val F1=0.2012)
  Directional -> Accuracy: 0.4630, MCC: 0.1229, F1: 0.0645

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.44636 | val 1.80535
  Epoch 011 - train 0.36016 | val 2.62896
  Classification -> best τ=0.505 (val F1=0.2464)
  Directional -> Accuracy: 0.4909, MCC: 0.0000, F1: 0.6585

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.34052 | val 1.07604
  Epoch 012 - train 0.27702 | val 1.38998
  Classification -> best τ=0.590 (val F1=0.1304)
  Directional -> Accuracy: 0.4615, MCC: -0.0778, F1: 0.5000

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.49593 | val 1.26416
  Epoch 020 - train 0.11834 | val 1.11237
  Epoch 024 - train 0.07664 | val 1.72795
  Classification -> best τ=0.365 (val F1=0.4018)
  Directional -> Accuracy: 0.5185, MCC: 0.0131, F1: 0.6579

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.50949 | val 0.82396

[I 2026-02-22 09:39:16,772] Trial 62 finished with value: 0.2586583828848346 and parameters: {'feature_set': 'emotion', 'model_type': 'GRU', 'sequence_length': 30, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 64, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.6000000000000001, 'batch_size': 32, 'learning_rate': 0.009874029735186252, 'weight_decay': 2.387877318872904e-06, 'lr_patience': 5, 'lr_factor': 0.8, 'early_stopping_patience': 10, 'max_epochs': 50, 'huber_delta': 1.9979298867674666, 'early_stopping_min_delta': 0.007321816441262916}. Best is trial 22 with value: 0.2833350641483003.

  Epoch 020 - train 0.07633 | val 1.00586
  Epoch 021 - train 0.06998 | val 1.17015
  Classification -> best τ=0.585 (val F1=0.3870)
  Directional -> Accuracy: 0.4407, MCC: -0.1082, F1: 0.5075

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2586583828848346
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d', 'sentiment', 'emotion_anger', 'emotion_disgust', 'emotion_fear', 'emotion_joy', 'emotion_neutral', 'emotion_sadness', 'emotion_surprize', 'emotion_anger_pct', 'emotion_disgust_pct', 'emotion_fear_pct', 'emotion_joy_pct', 'emotion_neutral_pct', 'emotion_sadness_pct', 'emotion_surprize_pct', 'positive_emotion', 'negative_emotion', 'uncertainty_emotion', 'positive_emotion_pct', 'negative_emotion_pct', 'uncertainty_emotion_pct', 'stance_label', 'stance_score', 'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down', 'finbert_neutral']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.26863 | val 1.96996
  Epoch 012 - train 0.19162 | val 2.21991
  Classification -> best τ=0.560 (val F1=0.2919)
  Directional -> Accuracy: 0.5395, MCC: 0.0192, F1: 0.2857

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.23070 | val 2.42449
  Epoch 011 - train 0.19932 | val 3.62463
  Classification -> best τ=0.270 (val F1=0.1591)
  Directional -> Accuracy: 0.5778, MCC: 0.0000, F1: 0.7324

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.19411 | val 2.50073
  Epoch 011 - train 0.14108 | val 2.86270
  Classification -> best τ=0.590 (val F1=0.1333)
  Directional -> Accuracy: 0.4783, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.27200 | val 2.79876
  Epoch 011 - train 0.22752 | val 3.28713
  Classification -> best τ=0.305 (val F1=0.1537)
  Directional -> Accuracy: 0.5000, MCC: -0.0693, F1: 0.6337

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.17468 | val 1.72059
  Epoch 012 - train 0.06276 | val 1.60477
  Classification -> best τ=0.465 (val F1=0.4493)
  Directional -> Accuracy: 0.6800, MCC: 0.3870, F1: 0.6364

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.18788 | val 1.82160
  Epoch 011 - train 0.14264 | val 2.28116
  Classification -> best τ=0.585 (val F1=0.2739)
  Directional -> Accuracy: 0.5217, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.21042 | val 1.87570
  Epoch 011 - train 0.15059 | val 2.12898
  Classification -> best τ=0.435 (val F1=0.2176)
  Directional -> Accuracy: 0.4853, MCC: 0.1159, F1: 0.5679

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.18390 | val 1.34496
  Epoch 013 - train 0.14036 | val 2.18251
  Classification -> best τ=0.285 (val F1=0.2075)
  Directional -> Accuracy: 0.4524, MCC: 0.1353, F1: 0.6102

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.18196 | val 1.75983
  Epoch 012 - train 0.13190 | val 1.56683
  Classification -> best τ=0.520 (val F1=0.2243)
  Directional -> Accuracy: 0.4583, MCC: 0.0542, F1: 0.6061

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.21774 | val 2.87564
  Epoch 011 - train 0.18110 | val 3.12868
  Classification -> best τ=0.240 (val F1=0.2535)
  Directional -> Accuracy: 0.4203, MCC: 0.0000, F1: 0.5918

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.16122 | val 1.82026
  Epoch 011 - train 0.12532 | val 2.72579
  Classification -> best τ=0.630 (val F1=0.2484)
  Directional -> Accuracy: 0.5918, MCC: 0.2285, F1: 0.1667

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.25365 | val 3.34205
  Epoch 011 - train 0.14822 | val 3.85342
  Classification -> best τ=0.390 (val F1=0.1944)
  Directional -> Accuracy: 0.5614, MCC: 0.2399, F1: 0.6988

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.18248 | val 3.42764
  Epoch 011 - train 0.15061 | val 3.44356
  Classification -> best τ=0.485 (val F1=0.1754)
  Directional -> Accuracy: 0.5000, MCC: -0.0046, F1: 0.4615

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.20852 | val 1.84146
  Epoch 011 - train 0.18195 | val 1.81859
  Classification -> best τ=0.495 (val F1=0.3320)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.15965 | val 1.89131
  Epoch 011 - train 0.13751 | val 2.28580
  Classification -> best τ=0.565 (val F1=0.1455)
  Directional -> Accuracy: 0.5490, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.25796 | val 1.49509
  Epoch 011 - train 0.22954 | val 2.08595
  Classification -> best τ=0.515 (val F1=0.2998)
  Directional -> Accuracy: 0.6377, MCC: 0.2951, F1: 0.7312

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.19014 | val 2.95967
  Epoch 011 - train 0.14579 | val 3.55866
  Classification -> best τ=0.680 (val F1=0.1510)
  Directional -> Accuracy: 0.4483, MCC: 0.2128, F1: 0.2000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.26244 | val 1.28369
  Epoch 011 - train 0.19331 | val 1.42712
  Classification -> best τ=0.555 (val F1=0.1548)
  Directional -> Accuracy: 0.3867, MCC: -0.1111, F1: 0.0417

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.14330 | val 2.14217
  Epoch 011 - train 0.10311 | val 2.65469
  Classification -> best τ=0.555 (val F1=0.2535)
  Directional -> Accuracy: 0.4844, MCC: 0.1315, F1: 0.2667

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.27142 | val 0.97672
  Epoch 012 - train 0.15865 | val 1.14989
  Classification -> best τ=0.455 (val F1=0.3183)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.15572 | val 1.84514
  Epoch 011 - train 0.11772 | val 1.64491
  Classification -> best τ=0.460 (val F1=0.2247)
  Directional -> Accuracy: 0.4894, MCC: -0.1303, F1: 0.6129

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.16211 | val 1.95706
  Epoch 011 - train 0.11639 | val 2.09891
  Classification -> best τ=0.515 (val F1=0.2376)
  Directional -> Accuracy: 0.4923, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.18066 | val 1.08234
  Epoch 011 - train 0.15065 | val 1.23820
  Classification -> best τ=0.690 (val F1=0.3749)
  Directional -> Accuracy: 0.5614, MCC: 0.1400, F1: 0.5614

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.28947 | val 0.98409
  Epoch 011 - train 0.23606 | val 1.07147
  Classification -> best τ=0.515 (val F1=0.2177)
  Directional -> Accuracy: 0.6769, MCC: 0.3536, F1: 0.6667

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.17781 | val 1.33118
  Epoch 012 - train 0.09813 | val 1.70090
  Classification -> best τ=0.440 (val F1=0.3233)
  Directional -> Accuracy: 0.5455, MCC: 0.1365, F1: 0.4681

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.20006 | val 2.54217
  Epoch 011 - train 0.14895 | val 3.06290
  Classification -> best τ=0.515 (val F1=0.2241)
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.5938

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.14190 | val 1.33244
  Epoch 011 - train 0.10415 | val 1.70608
  Classification -> best τ=0.530 (val F1=0.2161)
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.0000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.23501 | val 1.43635
  Epoch 011 - train 0.21799 | val 1.58394
  Classification -> best τ=0.335 (val F1=0.1126)
  Directional -> Accuracy: 0.4821, MCC: -0.0437, F1: 0.5246

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.22483 | val 4.66583
  Epoch 011 - train 0.18953 | val 5.60012
  Classification -> best τ=0.345 (val F1=0.4345)
  Directional -> Accuracy: 0.5750, MCC: 0.1124, F1: 0.6909

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.21073 | val 2.47437
  Epoch 011 - train 0.16261 | val 2.87108
  Classification -> best τ=0.595 (val F1=0.3501)
  Directional -> Accuracy: 0.4762, MCC: -0.0754, F1: 0.3125

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.23819 | val 1.54678
  Epoch 011 - train 0.18128 | val 1.84259
  Classification -> best τ=0.500 (val F1=0.1286)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.16707 | val 1.64343
  Epoch 011 - train 0.12318 | val 1.74618
  Classification -> best τ=0.430 (val F1=0.2161)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.20146 | val 1.71719
  Epoch 011 - train 0.13367 | val 2.00822
  Classification -> best τ=0.465 (val F1=0.2370)
  Directional -> Accuracy: 0.4583, MCC: 0.1061, F1: 0.0488

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.18159 | val 1.55507
  Epoch 011 - train 0.13091 | val 1.88421
  Classification -> best τ=0.435 (val F1=0.2324)
  Directional -> Accuracy: 0.5116, MCC: 0.0849, F1: 0.6557

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.27239 | val 1.65045
  Epoch 011 - train 0.20362 | val 1.75754
  Classification -> best τ=0.350 (val F1=0.3814)
  Directional -> Accuracy: 0.5000, MCC: 0.1168, F1: 0.3529

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.10798 | val 2.43803
  Epoch 011 - train 0.08877 | val 2.58429
  Classification -> best τ=0.460 (val F1=0.3321)
  Directional -> Accuracy: 0.6190, MCC: 0.2337, F1: 0.6667

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.17556 | val 1.14876
  Epoch 011 - train 0.13829 | val 1.26725
  Classification -> best τ=0.395 (val F1=0.2755)
  Directional -> Accuracy: 0.4821, MCC: -0.0333, F1: 0.4727

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.13891 | val 2.01492
  Epoch 011 - train 0.11328 | val 2.20254
  Classification -> best τ=0.495 (val F1=0.3146)
  Directional -> Accuracy: 0.6087, MCC: 0.0000, F1: 0.7568

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.20402 | val 0.89542
  Epoch 015 - train 0.06835 | val 1.33982
  Classification -> best τ=0.530 (val F1=0.4688)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.23106 | val 2.66084
  Epoch 011 - train 0.15451 | val 3.01440
  Classification -> best τ=0.215 (val F1=0.2319)
  Directional -> Accuracy: 0.4865, MCC: 0.0000, F1: 0.6545

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.19151 | val 1.46059
  Epoch 011 - train 0.13993 | val 1.83385
  Classification -> best τ=0.365 (val F1=0.2169)
  Directional -> Accuracy: 0.5111, MCC: 0.0000, F1: 0.6765

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.25482 | val 1.05582
  Epoch 011 - train 0.24597 | val 1.11442
  Classification -> best τ=0.485 (val F1=0.2408)
  Directional -> Accuracy: 0.5952, MCC: 0.1487, F1: 0.6792

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.25902 | val 0.88906
  Epoch 011 - train 0.18911 | val 1.05012
  Classification -> best τ=0.425 (val F1=0.2605)
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.5455

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.19347 | val 2.17182
  Epoch 011 - train 0.13816 | val 2.34504
  Classification -> best τ=0.485 (val F1=0.1884)
  Directional -> Accuracy: 0.4727, MCC: -0.0404, F1: 0.4528

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.18439 | val 2.24884
  Epoch 011 - train 0.12328 | val 2.65175
  Classification -> best τ=0.610 (val F1=0.4452)
  Directional -> Accuracy: 0.5893, MCC: 0.3343, F1: 0.7013

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.17070 | val 2.20612
  Epoch 012 - train 0.09243 | val 2.71735
  Classification -> best τ=0.395 (val F1=0.1942)
  Directional -> Accuracy: 0.5094, MCC: 0.0000, F1: 0.6750

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.26758 | val 1.98177
  Epoch 011 - train 0.19482 | val 2.01984
  Classification -> best τ=0.680 (val F1=0.2833)
  Directional -> Accuracy: 0.4727, MCC: -0.0319, F1: 0.3256

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.26744 | val 1.04378

[I 2026-02-22 09:39:56,861] Trial 63 finished with value: 0.25666824148753625 and parameters: {'feature_set': 'sector_all_nlp', 'model_type': 'GRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 64, 'num_layers': 1, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.5, 'batch_size': 32, 'learning_rate': 0.004611837753386228, 'weight_decay': 1.2612557146633015e-06, 'lr_patience': 5, 'lr_factor': 0.8, 'early_stopping_patience': 10, 'max_epochs': 50, 'huber_delta': 1.4914151564111537, 'early_stopping_min_delta': 0.007999221906917233}. Best is trial 22 with value: 0.2833350641483003.

  Epoch 015 - train 0.09897 | val 0.99681
  Classification -> best τ=0.560 (val F1=0.3195)
  Directional -> Accuracy: 0.5333, MCC: 0.0656, F1: 0.5172

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.25666824148753625
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: classification
Sequence length: 30
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.54490 | val 0.79198
  Epoch 014 - train 0.48236 | val 0.76688
  Classification -> best τ=0.440 (val F1=0.2895)
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.6239

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 106). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.48869 | val 1.43679
  Epoch 011 - train 0.46422 | val 1.88227
  Classification -> best τ=0.425 (val F1=0.0721)
  Directional -> Accuracy: 0.5909, MCC: 0.0000, F1: 0.7429

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 106). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.52196 | val 1.31539
  Epoch 011 - train 0.49722 | val 1.53228
  Classification -> best τ=0.535 (val F1=0.3026)
  Directional -> Accuracy: 0.4667, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.57619 | val 1.57622
  Epoch 011 - train 0.55594 | val 2.75907
  Classification -> best τ=0.465 (val F1=0.0021)
  Directional -> Accuracy: 0.5342, MCC: 0.0000, F1: 0.6964

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.46456 | val 1.09105
  Epoch 014 - train 0.39359 | val 1.69723
  Classification -> best τ=0.570 (val F1=0.4307)
  Directional -> Accuracy: 0.5918, MCC: 0.1831, F1: 0.6296

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.44796 | val 1.15897
  Epoch 011 - train 0.43674 | val 1.24132
  Classification -> best τ=0.500 (val F1=0.2294)
  Directional -> Accuracy: 0.5333, MCC: 0.0709, F1: 0.2759

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.58010 | val 0.83402
  Epoch 014 - train 0.53586 | val 0.95116
  Classification -> best τ=0.630 (val F1=0.2575)
  Directional -> Accuracy: 0.5970, MCC: 0.1199, F1: 0.4000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 106). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 106). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.48012 | val 2.45048
  Epoch 011 - train 0.44974 | val 2.90484
  Classification -> best τ=0.600 (val F1=0.3637)
  Directional -> Accuracy: 0.6098, MCC: 0.1921, F1: 0.5000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.49255 | val 1.20686
  Epoch 011 - train 0.45468 | val 1.48899
  Classification -> best τ=0.465 (val F1=0.2152)
  Directional -> Accuracy: 0.7234, MCC: 0.4383, F1: 0.6829

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 106). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 106). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 106). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.52399 | val 0.82394
  Epoch 011 - train 0.47742 | val 1.05111
  Classification -> best τ=0.500 (val F1=0.0699)
  Directional -> Accuracy: 0.5294, MCC: 0.0120, F1: 0.3846

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.50671 | val 3.36294
  Epoch 011 - train 0.47977 | val 2.71048
  Classification -> best τ=0.560 (val F1=0.2604)
  Directional -> Accuracy: 0.5417, MCC: 0.1303, F1: 0.6071

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.47712 | val 1.32146
  Epoch 011 - train 0.50238 | val 1.23628
  Classification -> best τ=0.390 (val F1=0.1448)
  Directional -> Accuracy: 0.5179, MCC: 0.0000, F1: 0.6824

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 106). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.45480 | val 2.57855
  Epoch 011 - train 0.43710 | val 3.45631
  Classification -> best τ=0.370 (val F1=0.1843)
  Directional -> Accuracy: 0.4694, MCC: -0.1473, F1: 0.6389

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 106). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.52888 | val 1.59232
  Epoch 011 - train 0.50119 | val 1.77781
  Classification -> best τ=0.485 (val F1=0.2763)
  Directional -> Accuracy: 0.5254, MCC: 0.0480, F1: 0.6000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.50848 | val 0.94065
  Epoch 011 - train 0.50415 | val 1.66106
  Classification -> best τ=0.565 (val F1=0.2060)
  Directional -> Accuracy: 0.5600, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.54248 | val 0.95858
  Epoch 011 - train 0.52044 | val 0.88999
  Classification -> best τ=0.470 (val F1=0.2526)
  Directional -> Accuracy: 0.5441, MCC: 0.1296, F1: 0.6990

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 106). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.54029 | val 1.54339
  Epoch 011 - train 0.53370 | val 1.82079
  Classification -> best τ=0.660 (val F1=0.0476)
  Directional -> Accuracy: 0.3860, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.51459 | val 0.96345
  Epoch 011 - train 0.50042 | val 1.08513
  Classification -> best τ=0.425 (val F1=0.2014)
  Directional -> Accuracy: 0.4865, MCC: 0.1988, F1: 0.2692

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.52865 | val 2.27029
  Epoch 012 - train 0.50318 | val 2.47934
  Classification -> best τ=0.505 (val F1=0.2664)
  Directional -> Accuracy: 0.4127, MCC: -0.0321, F1: 0.0513

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 106). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.53193 | val 1.15592
  Epoch 014 - train 0.43623 | val 1.01099
  Classification -> best τ=0.540 (val F1=0.2454)
  Directional -> Accuracy: 0.4658, MCC: -0.0021, F1: 0.2353

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.46038 | val 1.64303
  Epoch 011 - train 0.45657 | val 1.48851
  Classification -> best τ=0.440 (val F1=0.2159)
  Directional -> Accuracy: 0.4565, MCC: -0.0891, F1: 0.5098

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 106). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 106). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 106). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.53738 | val 1.29831
  Epoch 011 - train 0.53109 | val 1.30664
  Classification -> best τ=0.465 (val F1=0.1741)
  Directional -> Accuracy: 0.4844, MCC: -0.0369, F1: 0.5926

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.51848 | val 1.69053
  Epoch 011 - train 0.51605 | val 1.32620
  Classification -> best τ=0.740 (val F1=0.3062)
  Directional -> Accuracy: 0.5357, MCC: 0.1884, F1: 0.4091

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.52528 | val 0.90830
  Epoch 017 - train 0.40616 | val 1.23276
  Classification -> best τ=0.360 (val F1=0.2670)
  Directional -> Accuracy: 0.4688, MCC: 0.0000, F1: 0.6383

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.49788 | val 0.94193
  Epoch 015 - train 0.42268 | val 0.90609
  Classification -> best τ=0.490 (val F1=0.4640)
  Directional -> Accuracy: 0.4630, MCC: -0.0146, F1: 0.0645

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.47762 | val 0.89290
  Epoch 011 - train 0.45123 | val 0.95865
  Classification -> best τ=0.545 (val F1=0.0833)
  Directional -> Accuracy: 0.3953, MCC: -0.1508, F1: 0.4800

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.49277 | val 2.24884
  Epoch 011 - train 0.47379 | val 2.77925
  Classification -> best τ=0.490 (val F1=0.1326)
  Directional -> Accuracy: 0.5102, MCC: 0.0170, F1: 0.5556

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.54980 | val 1.28979
  Epoch 011 - train 0.49850 | val 1.28012
  Classification -> best τ=0.430 (val F1=0.3498)
  Directional -> Accuracy: 0.5273, MCC: 0.2023, F1: 0.2778

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.48514 | val 1.00034
  Epoch 011 - train 0.48079 | val 1.17714
  Classification -> best τ=0.500 (val F1=0.4441)
  Directional -> Accuracy: 0.5789, MCC: 0.1291, F1: 0.7143

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.46241 | val 0.79903
  Epoch 011 - train 0.43142 | val 0.91926
  Classification -> best τ=0.580 (val F1=0.3150)
  Directional -> Accuracy: 0.4878, MCC: -0.0655, F1: 0.1600

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.48462 | val 1.41188
  Epoch 011 - train 0.47626 | val 1.57064
  Classification -> best τ=0.535 (val F1=0.0134)
  Directional -> Accuracy: 0.5610, MCC: 0.0000, F1: 0.7188

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.53608 | val 0.87506
  Epoch 011 - train 0.50187 | val 0.84577
  Classification -> best τ=0.575 (val F1=0.2530)
  Directional -> Accuracy: 0.5000, MCC: 0.0053, F1: 0.4783

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.51383 | val 1.45260
  Epoch 012 - train 0.47537 | val 1.69576
  Classification -> best τ=0.475 (val F1=0.3077)
  Directional -> Accuracy: 0.5493, MCC: 0.1488, F1: 0.5000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 106). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.46858 | val 0.68180
  Epoch 017 - train 0.36319 | val 0.92900
  Classification -> best τ=0.510 (val F1=0.3977)
  Directional -> Accuracy: 0.5476, MCC: 0.1003, F1: 0.5581

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for PCG (101 < 106). Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.53418 | val 1.08490
  Epoch 011 - train 0.51780 | val 1.07450
  Classification -> best τ=0.425 (val F1=0.3218)
  Directional -> Accuracy: 0.5846, MCC: 0.1494, F1: 0.6400

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.45515 | val 1.03122
  Epoch 013 - train 0.40187 | val 1.26926
  Classification -> best τ=0.430 (val F1=0.2697)
  Directional -> Accuracy: 0.6750, MCC: 0.3831, F1: 0.6286

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.51264 | val 0.80323
  Epoch 011 - train 0.52218 | val 0.96182
  Classification -> best τ=0.415 (val F1=0.2494)
  Directional -> Accuracy: 0.5273, MCC: 0.0828, F1: 0.5667

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.41903 | val 3.56692
  Epoch 011 - train 0.41433 | val 3.81306
  Classification -> best τ=0.620 (val F1=0.2626)
  Directional -> Accuracy: 0.5111, MCC: 0.1000, F1: 0.5000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 106). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 106). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 106). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 106). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.48712 | val 0.63618
  Epoch 017 - train 0.40926 | val 0.80789
  Classification -> best τ=0.590 (val F1=0.4326)
  Directional -> Accuracy: 0.3261, MCC: 0.0000, F1: 0.4918

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 106). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 106). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 106). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.53295 | val 1.66351
  Epoch 011 - train 0.50301 | val 1.71330
  Classification -> best τ=0.490 (val F1=0.2709)
  Directional -> Accuracy: 0.4932, MCC: 0.0000, F1: 0.6606

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 106). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 106). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 106). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 106). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.53947 | val 1.32653
  Epoch 011 - train 0.49611 | val 1.46381
  Classification -> best τ=0.465 (val F1=0.1980)
  Directional -> Accuracy: 0.5455, MCC: 0.0913, F1: 0.5652

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.51777 | val 0.66758
  Epoch 020 - train 0.37598 | val 0.75777
  Epoch 023 - train 0.36432 | val 0.78789
  Classification -> best τ=0.495 (val F1=0.3928)
  Directional -> Accuracy: 0.4878, MCC: -0.1645, F1: 0.6316

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.49008 | val 0.77732
  Epoch 011 - train 0.47110 | val 0.82352
  Classification -> best τ=0.550 (val F1=0.0422)
  Directional -> Accuracy: 0.3696, MCC: 0.0000, F1: 0.5397

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.55242 | val 1.91613
  Epoch 011 - train 0.54835 | val 2.18229
  Classification -> best τ=0.470 (val F1=0.2457)
  Directional -> Accuracy: 0.5000, MCC: 0.2169, F1: 0.1818

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.51949 | val 1.70454
  Epoch 012 - train 0.49495 | val 2.12293
  Classification -> best τ=0.470 (val F1=0.2464)
  Directional -> Accuracy: 0.4909, MCC: 0.0000, F1: 0.6585

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.53429 | val 0.91570
  Epoch 014 - train 0.45600 | val 1.00577
  Classification -> best τ=0.620 (val F1=0.2685)
  Directional -> Accuracy: 0.5769, MCC: 0.1667, F1: 0.6452

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.52688 | val 0.97008
  Epoch 012 - train 0.49388 | val 1.07011
  Classification -> best τ=0.460 (val F1=0.1732)
  Directional -> Accuracy: 0.5370, MCC: 0.1425, F1: 0.6914

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...

[I 2026-02-22 09:40:49,419] Trial 64 finished with value: 0.2397475911576508 and parameters: {'feature_set': 'base', 'model_type': 'GRU', 'sequence_length': 30, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 64, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.1, 'batch_size': 32, 'learning_rate': 0.00212655555153405, 'weight_decay': 7.280612809729271e-06, 'lr_patience': 5, 'lr_factor': 0.8, 'early_stopping_patience': 10, 'max_epochs': 50, 'huber_delta': 1.2005562030873351, 'early_stopping_min_delta': 0.002230243775898772}. Best is trial 22 with value: 0.2833350641483003.

  Epoch 010 - train 0.50696 | val 2.18908
  Epoch 011 - train 0.49270 | val 1.75217
  Classification -> best τ=0.455 (val F1=0.0921)
  Directional -> Accuracy: 0.3729, MCC: -0.2503, F1: 0.3934

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2397475911576508
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d', 'positive_emotion', 'negative_emotion', 'uncertainty_emotion', 'positive_emotion_pct', 'negative_emotion_pct', 'uncertainty_emotion_pct']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.40584 | val 0.76133
  Epoch 013 - train 0.28422 | val 0.82717
  Classification -> best τ=0.530 (val F1=0.2919)
  Directional -> Accuracy: 0.5921, MCC: 0.1728, F1: 0.5373

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.28114 | val 1.06120
  Epoch 011 - train 0.23549 | val 1.14215
  Classification -> best τ=0.395 (val F1=0.2285)
  Directional -> Accuracy: 0.5778, MCC: 0.0000, F1: 0.7324

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.33787 | val 1.95615
  Epoch 011 - train 0.28544 | val 2.15201
  Classification -> best τ=0.480 (val F1=0.0653)
  Directional -> Accuracy: 0.5000, MCC: 0.0266, F1: 0.3429

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.46407 | val 1.91765
  Epoch 011 - train 0.43249 | val 2.37218
  Classification -> best τ=0.415 (val F1=0.1257)
  Directional -> Accuracy: 0.5405, MCC: 0.0000, F1: 0.7018

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.36507 | val 0.82931
  Epoch 014 - train 0.17350 | val 1.37507
  Classification -> best τ=0.515 (val F1=0.3688)
  Directional -> Accuracy: 0.6200, MCC: 0.2795, F1: 0.5366

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.31684 | val 0.80596
  Epoch 015 - train 0.21591 | val 1.23567
  Classification -> best τ=0.425 (val F1=0.3855)
  Directional -> Accuracy: 0.5217, MCC: 0.0349, F1: 0.4500

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.39952 | val 1.16176
  Epoch 011 - train 0.36306 | val 1.31828
  Classification -> best τ=0.425 (val F1=0.3071)
  Directional -> Accuracy: 0.5147, MCC: 0.1463, F1: 0.5714

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.39255 | val 0.47834
  Epoch 020 - train 0.10420 | val 0.81229
  Epoch 021 - train 0.08847 | val 0.91822
  Classification -> best τ=0.455 (val F1=0.5614)
  Directional -> Accuracy: 0.4524, MCC: 0.0534, F1: 0.5965

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.40743 | val 1.27571
  Epoch 011 - train 0.32490 | val 1.54320
  Classification -> best τ=0.515 (val F1=0.2779)
  Directional -> Accuracy: 0.4167, MCC: -0.1654, F1: 0.5882

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.32519 | val 0.83071
  Epoch 016 - train 0.07788 | val 1.69534
  Classification -> best τ=0.455 (val F1=0.3870)
  Directional -> Accuracy: 0.4638, MCC: 0.0217, F1: 0.5542

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.32413 | val 1.51979
  Epoch 011 - train 0.29450 | val 1.36388
  Classification -> best τ=0.560 (val F1=0.2543)
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.30559 | val 1.88331
  Epoch 011 - train 0.29029 | val 2.60231
  Classification -> best τ=0.515 (val F1=0.0996)
  Directional -> Accuracy: 0.6491, MCC: 0.2993, F1: 0.6774

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.40156 | val 1.39305
  Epoch 011 - train 0.36385 | val 1.56243
  Classification -> best τ=0.370 (val F1=0.2018)
  Directional -> Accuracy: 0.5714, MCC: 0.2150, F1: 0.6400

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.40071 | val 0.81905
  Epoch 017 - train 0.12292 | val 1.85985
  Classification -> best τ=0.545 (val F1=0.3584)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.1667

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.40295 | val 1.02010
  Epoch 012 - train 0.29194 | val 1.14422
  Classification -> best τ=0.470 (val F1=0.2078)
  Directional -> Accuracy: 0.5490, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.44125 | val 1.28013
  Epoch 011 - train 0.40453 | val 1.34436
  Classification -> best τ=0.385 (val F1=0.1823)
  Directional -> Accuracy: 0.5362, MCC: 0.0000, F1: 0.6981

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.38435 | val 1.29054
  Epoch 011 - train 0.33220 | val 1.49506
  Classification -> best τ=0.635 (val F1=0.1842)
  Directional -> Accuracy: 0.3966, MCC: 0.1035, F1: 0.0541

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.47262 | val 1.15382
  Epoch 011 - train 0.38419 | val 1.68895
  Classification -> best τ=0.620 (val F1=0.1548)
  Directional -> Accuracy: 0.4133, MCC: -0.1535, F1: 0.4359

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.37890 | val 1.47431
  Epoch 011 - train 0.30924 | val 1.51150
  Classification -> best τ=0.380 (val F1=0.2843)
  Directional -> Accuracy: 0.5781, MCC: 0.0760, F1: 0.6966

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.47993 | val 0.81151
  Epoch 016 - train 0.28861 | val 1.14990
  Classification -> best τ=0.330 (val F1=0.3030)
  Directional -> Accuracy: 0.5270, MCC: 0.1734, F1: 0.3396

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.29211 | val 1.96733
  Epoch 011 - train 0.28291 | val 2.15644
  Classification -> best τ=0.475 (val F1=0.3237)
  Directional -> Accuracy: 0.4894, MCC: 0.0037, F1: 0.5200

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.41972 | val 1.27933
  Epoch 012 - train 0.33201 | val 1.48169
  Classification -> best τ=0.575 (val F1=0.1925)
  Directional -> Accuracy: 0.4923, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.36934 | val 0.87144
  Epoch 013 - train 0.22003 | val 1.18375
  Classification -> best τ=0.475 (val F1=0.4892)
  Directional -> Accuracy: 0.5614, MCC: 0.0424, F1: 0.6988

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.42803 | val 0.86133
  Epoch 011 - train 0.38385 | val 1.12619
  Classification -> best τ=0.525 (val F1=0.2451)
  Directional -> Accuracy: 0.5231, MCC: 0.0548, F1: 0.5507

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.30222 | val 1.58750
  Epoch 012 - train 0.28184 | val 2.07956
  Classification -> best τ=0.420 (val F1=0.4399)
  Directional -> Accuracy: 0.5091, MCC: 0.0671, F1: 0.4000

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.25879 | val 1.12768
  Epoch 011 - train 0.19708 | val 1.14782
  Classification -> best τ=0.580 (val F1=0.0284)
  Directional -> Accuracy: 0.3778, MCC: -0.2030, F1: 0.4400

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.35166 | val 0.91989
  Epoch 011 - train 0.28630 | val 0.95884
  Classification -> best τ=0.515 (val F1=0.1803)
  Directional -> Accuracy: 0.6190, MCC: 0.1925, F1: 0.7241

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.40430 | val 1.46049
  Epoch 011 - train 0.34783 | val 1.42558
  Classification -> best τ=0.540 (val F1=0.2305)
  Directional -> Accuracy: 0.4464, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.28064 | val 0.90220
  Epoch 011 - train 0.25624 | val 1.19564
  Classification -> best τ=0.435 (val F1=0.3671)
  Directional -> Accuracy: 0.5750, MCC: 0.1124, F1: 0.6909

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.42263 | val 0.87483
  Epoch 012 - train 0.36471 | val 1.13395
  Classification -> best τ=0.610 (val F1=0.4110)
  Directional -> Accuracy: 0.4762, MCC: -0.0754, F1: 0.3125

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.32905 | val 1.39005
  Epoch 012 - train 0.25612 | val 1.32527
  Classification -> best τ=0.470 (val F1=0.1846)
  Directional -> Accuracy: 0.6190, MCC: 0.2981, F1: 0.5556

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.32439 | val 1.32952
  Epoch 013 - train 0.22579 | val 1.68889
  Classification -> best τ=0.395 (val F1=0.3987)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.41716 | val 0.99935
  Epoch 013 - train 0.27901 | val 1.29892
  Classification -> best τ=0.490 (val F1=0.2762)
  Directional -> Accuracy: 0.4444, MCC: 0.0000, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.31108 | val 0.97156
  Epoch 011 - train 0.26641 | val 1.01033
  Classification -> best τ=0.570 (val F1=0.2151)
  Directional -> Accuracy: 0.5814, MCC: 0.1993, F1: 0.3571

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.47867 | val 1.19548
  Epoch 011 - train 0.44920 | val 1.37345
  Classification -> best τ=0.415 (val F1=0.3525)
  Directional -> Accuracy: 0.5758, MCC: 0.0569, F1: 0.7083

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.25039 | val 0.94152
  Epoch 011 - train 0.20898 | val 1.05207
  Classification -> best τ=0.395 (val F1=0.2067)
  Directional -> Accuracy: 0.7381, MCC: 0.4767, F1: 0.7442

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.30848 | val 1.34392
  Epoch 011 - train 0.27949 | val 1.29139
  Classification -> best τ=0.485 (val F1=0.1508)
  Directional -> Accuracy: 0.6250, MCC: 0.2420, F1: 0.5116

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.28594 | val 1.05571
  Epoch 011 - train 0.22410 | val 1.14457
  Classification -> best τ=0.485 (val F1=0.3105)
  Directional -> Accuracy: 0.6087, MCC: 0.0000, F1: 0.7568

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.39919 | val 0.76125
  Epoch 019 - train 0.08201 | val 1.30974
  Classification -> best τ=0.560 (val F1=0.4011)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.44659 | val 1.09558
  Epoch 012 - train 0.34493 | val 1.47494
  Classification -> best τ=0.360 (val F1=0.2611)
  Directional -> Accuracy: 0.4865, MCC: 0.0000, F1: 0.6545

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.38121 | val 1.04368
  Epoch 013 - train 0.18728 | val 1.62345
  Classification -> best τ=0.520 (val F1=0.2000)
  Directional -> Accuracy: 0.4667, MCC: -0.1059, F1: 0.6000

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.33800 | val 0.79846
  Epoch 011 - train 0.27636 | val 0.83208
  Classification -> best τ=0.510 (val F1=0.2722)
  Directional -> Accuracy: 0.5952, MCC: 0.1803, F1: 0.7385

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.38440 | val 0.60417
  Epoch 019 - train 0.09726 | val 0.74716
  Classification -> best τ=0.565 (val F1=0.5249)
  Directional -> Accuracy: 0.4375, MCC: 0.1233, F1: 0.5574

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.35847 | val 1.39974
  Epoch 011 - train 0.31622 | val 1.55018
  Classification -> best τ=0.525 (val F1=0.2036)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.32112 | val 1.79165
  Epoch 013 - train 0.16510 | val 2.92019
  Classification -> best τ=0.620 (val F1=0.3446)
  Directional -> Accuracy: 0.4643, MCC: -0.1173, F1: 0.2105

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.38073 | val 1.46537
  Epoch 012 - train 0.29947 | val 1.59857
  Classification -> best τ=0.380 (val F1=0.1646)
  Directional -> Accuracy: 0.5094, MCC: 0.0000, F1: 0.6750

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.37648 | val 1.98867
  Epoch 011 - train 0.32267 | val 1.32036
  Classification -> best τ=0.625 (val F1=0.2291)
  Directional -> Accuracy: 0.4727, MCC: -0.0446, F1: 0.4314

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.46406 | val 0.67557

[I 2026-02-22 09:41:18,897] Trial 65 finished with value: 0.2737366189805482 and parameters: {'feature_set': 'sector_unified_emotion', 'model_type': 'GRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 64, 'num_layers': 1, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.2, 'batch_size': 64, 'learning_rate': 0.005531495924547653, 'weight_decay': 3.709435579075357e-07, 'lr_patience': 5, 'lr_factor': 0.8, 'early_stopping_patience': 10, 'max_epochs': 50, 'huber_delta': 1.5501521940853242, 'early_stopping_min_delta': 0.008817703822358977}. Best is trial 22 with value: 0.2833350641483003.

  Epoch 017 - train 0.14566 | val 1.03877
  Classification -> best τ=0.685 (val F1=0.3056)
  Directional -> Accuracy: 0.5333, MCC: 0.1346, F1: 0.0667

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2737366189805482
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d', 'positive_emotion', 'negative_emotion', 'uncertainty_emotion', 'positive_emotion_pct', 'negative_emotion_pct', 'uncertainty_emotion_pct']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.29794 | val 0.90537
  Epoch 014 - train 0.17380 | val 1.21623
  Classification -> best τ=0.550 (val F1=0.2919)
  Directional -> Accuracy: 0.5921, MCC: 0.1561, F1: 0.4561

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.24645 | val 0.77326
  Epoch 011 - train 0.20929 | val 0.82573
  Classification -> best τ=0.510 (val F1=0.2523)
  Directional -> Accuracy: 0.6000, MCC: 0.1591, F1: 0.6786

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.18942 | val 1.25069
  Epoch 011 - train 0.16509 | val 1.46921
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5217, MCC: 0.0000, F1: 0.6857

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.33599 | val 1.85987
  Epoch 011 - train 0.31346 | val 2.07297
  Classification -> best τ=0.500 (val F1=0.1951)
  Directional -> Accuracy: 0.4730, MCC: -0.0168, F1: 0.3390

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.25023 | val 0.74650
  Epoch 015 - train 0.08265 | val 1.09895
  Classification -> best τ=0.565 (val F1=0.3280)
  Directional -> Accuracy: 0.5800, MCC: 0.2417, F1: 0.4000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.27018 | val 0.96977
  Epoch 011 - train 0.23428 | val 1.15264
  Classification -> best τ=0.475 (val F1=0.2739)
  Directional -> Accuracy: 0.5217, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.28618 | val 1.24102
  Epoch 011 - train 0.25466 | val 1.52304
  Classification -> best τ=0.510 (val F1=0.2176)
  Directional -> Accuracy: 0.5000, MCC: 0.1418, F1: 0.5750

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.22775 | val 0.57503
  Epoch 020 - train 0.02529 | val 0.59446
  Epoch 024 - train 0.00809 | val 0.61701
  Classification -> best τ=0.525 (val F1=0.4839)
  Directional -> Accuracy: 0.4286, MCC: -0.0913, F1: 0.5000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.22579 | val 0.95780
  Epoch 011 - train 0.21222 | val 0.90581
  Classification -> best τ=0.525 (val F1=0.2233)
  Directional -> Accuracy: 0.5000, MCC: 0.1264, F1: 0.6129

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.21175 | val 1.05689
  Epoch 014 - train 0.09619 | val 1.38452
  Classification -> best τ=0.525 (val F1=0.2460)
  Directional -> Accuracy: 0.3768, MCC: -0.2267, F1: 0.3768

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.22853 | val 0.96806
  Epoch 011 - train 0.20417 | val 1.01830
  Classification -> best τ=0.545 (val F1=0.2101)
  Directional -> Accuracy: 0.6122, MCC: 0.2829, F1: 0.2400

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.20089 | val 1.42526
  Epoch 011 - train 0.17073 | val 1.37815
  Classification -> best τ=0.520 (val F1=0.1706)
  Directional -> Accuracy: 0.6491, MCC: 0.2979, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.24979 | val 1.10503
  Epoch 011 - train 0.22538 | val 1.20564
  Classification -> best τ=0.445 (val F1=0.0523)
  Directional -> Accuracy: 0.4524, MCC: -0.0391, F1: 0.5818

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.30454 | val 0.75594
  Epoch 016 - train 0.08774 | val 1.58492
  Classification -> best τ=0.515 (val F1=0.4640)
  Directional -> Accuracy: 0.4833, MCC: -0.0765, F1: 0.0606

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.24789 | val 1.06467
  Epoch 011 - train 0.22067 | val 1.02394
  Classification -> best τ=0.535 (val F1=0.1556)
  Directional -> Accuracy: 0.5490, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.28789 | val 1.25390
  Epoch 011 - train 0.25434 | val 1.25911
  Classification -> best τ=0.495 (val F1=0.2557)
  Directional -> Accuracy: 0.5797, MCC: 0.1502, F1: 0.6234

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.24256 | val 1.20170
  Epoch 011 - train 0.21440 | val 1.28417
  Classification -> best τ=0.540 (val F1=0.1342)
  Directional -> Accuracy: 0.4655, MCC: 0.0793, F1: 0.3673

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.32474 | val 1.41059
  Epoch 011 - train 0.30039 | val 1.61296
  Classification -> best τ=0.525 (val F1=0.1548)
  Directional -> Accuracy: 0.4000, MCC: -0.0602, F1: 0.1176

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.35339 | val 1.32804
  Epoch 013 - train 0.19925 | val 1.64678
  Classification -> best τ=0.365 (val F1=0.2803)
  Directional -> Accuracy: 0.6094, MCC: 0.1811, F1: 0.6835

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.36196 | val 0.92841
  Epoch 014 - train 0.22387 | val 1.16710
  Classification -> best τ=0.390 (val F1=0.3431)
  Directional -> Accuracy: 0.4865, MCC: 0.1332, F1: 0.1739

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.18225 | val 0.86657
  Epoch 011 - train 0.16481 | val 0.90966
  Classification -> best τ=0.510 (val F1=0.2861)
  Directional -> Accuracy: 0.4043, MCC: 0.0267, F1: 0.1250

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.25200 | val 1.52572
  Epoch 011 - train 0.21906 | val 1.68352
  Classification -> best τ=0.485 (val F1=0.2445)
  Directional -> Accuracy: 0.4923, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.28855 | val 0.89919
  Epoch 015 - train 0.10126 | val 1.32747
  Classification -> best τ=0.855 (val F1=0.3254)
  Directional -> Accuracy: 0.4737, MCC: 0.1044, F1: 0.1667

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.29657 | val 1.03914
  Epoch 011 - train 0.24726 | val 1.10698
  Classification -> best τ=0.490 (val F1=0.2120)
  Directional -> Accuracy: 0.4615, MCC: -0.1309, F1: 0.6316

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.23520 | val 0.99508
  Epoch 014 - train 0.10354 | val 1.61188
  Classification -> best τ=0.375 (val F1=0.3436)
  Directional -> Accuracy: 0.5273, MCC: 0.0669, F1: 0.5185

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.13002 | val 0.91220
  Epoch 011 - train 0.11578 | val 0.96798
  Classification -> best τ=0.575 (val F1=0.1890)
  Directional -> Accuracy: 0.4444, MCC: -0.3353, F1: 0.0000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.23182 | val 0.78375
  Epoch 011 - train 0.19089 | val 0.84397
  Classification -> best τ=0.505 (val F1=0.2402)
  Directional -> Accuracy: 0.3810, MCC: -0.2107, F1: 0.0714

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.27575 | val 1.33849
  Epoch 011 - train 0.25524 | val 1.43964
  Classification -> best τ=0.445 (val F1=0.1986)
  Directional -> Accuracy: 0.5536, MCC: 0.1704, F1: 0.4681

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.19337 | val 0.73605
  Epoch 011 - train 0.16129 | val 0.73498
  Classification -> best τ=0.425 (val F1=0.3278)
  Directional -> Accuracy: 0.6000, MCC: 0.2010, F1: 0.7241

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.28500 | val 1.07397
  Epoch 011 - train 0.22413 | val 0.82775
  Classification -> best τ=0.500 (val F1=0.2764)
  Directional -> Accuracy: 0.5238, MCC: 0.0674, F1: 0.5833

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.22900 | val 1.15624
  Epoch 011 - train 0.19783 | val 1.26750
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5476, MCC: 0.0000, F1: 0.7077

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.22653 | val 1.54220
  Epoch 011 - train 0.25157 | val 1.69699
  Classification -> best τ=0.465 (val F1=0.2837)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.36162 | val 0.98451
  Epoch 013 - train 0.23288 | val 1.19211
  Classification -> best τ=0.465 (val F1=0.3066)
  Directional -> Accuracy: 0.5000, MCC: 0.0863, F1: 0.3333

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.22334 | val 1.12707
  Epoch 011 - train 0.17353 | val 1.31577
  Classification -> best τ=0.450 (val F1=0.2324)
  Directional -> Accuracy: 0.6047, MCC: 0.2502, F1: 0.4138

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.43945 | val 0.81660
  Epoch 011 - train 0.37803 | val 0.85493
  Classification -> best τ=0.455 (val F1=0.3254)
  Directional -> Accuracy: 0.5455, MCC: 0.0152, F1: 0.6591

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.20886 | val 0.72681
  Epoch 011 - train 0.14781 | val 0.74414
  Classification -> best τ=0.430 (val F1=0.1715)
  Directional -> Accuracy: 0.7857, MCC: 0.5701, F1: 0.8000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.21542 | val 1.46728
  Epoch 011 - train 0.19562 | val 1.66461
  Classification -> best τ=0.445 (val F1=0.2149)
  Directional -> Accuracy: 0.4643, MCC: -0.0493, F1: 0.5312

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.21967 | val 0.86764
  Epoch 011 - train 0.18501 | val 0.89420
  Classification -> best τ=0.515 (val F1=0.2800)
  Directional -> Accuracy: 0.5652, MCC: -0.0153, F1: 0.6970

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.26782 | val 0.64835
  Epoch 020 - train 0.03870 | val 1.16359
  Classification -> best τ=0.760 (val F1=0.5075)
  Directional -> Accuracy: 0.3333, MCC: -0.1970, F1: 0.5000

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.27637 | val 1.54135
  Epoch 011 - train 0.24665 | val 1.80185
  Classification -> best τ=0.490 (val F1=0.2709)
  Directional -> Accuracy: 0.4865, MCC: 0.0000, F1: 0.6545

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.19668 | val 0.72306
  Epoch 016 - train 0.05341 | val 1.14084
  Classification -> best τ=0.500 (val F1=0.3185)
  Directional -> Accuracy: 0.5111, MCC: 0.0048, F1: 0.6667

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.19461 | val 0.66404
  Epoch 020 - train 0.01755 | val 0.70287
  Epoch 022 - train 0.01207 | val 0.73113
  Classification -> best τ=0.255 (val F1=0.3563)
  Directional -> Accuracy: 0.5952, MCC: 0.1273, F1: 0.7213

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.27612 | val 0.67571
  Epoch 020 - train 0.03140 | val 0.91097
  Epoch 023 - train 0.01404 | val 1.07027
  Classification -> best τ=0.545 (val F1=0.3410)
  Directional -> Accuracy: 0.5208, MCC: 0.1237, F1: 0.5306

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.24511 | val 1.08042
  Epoch 011 - train 0.19031 | val 1.20197
  Classification -> best τ=0.545 (val F1=0.2036)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.23008 | val 1.17895
  Epoch 011 - train 0.19891 | val 1.22101
  Classification -> best τ=0.515 (val F1=0.3189)
  Directional -> Accuracy: 0.5536, MCC: 0.1995, F1: 0.1379

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.25604 | val 1.16193
  Epoch 011 - train 0.20636 | val 1.25465
  Classification -> best τ=0.480 (val F1=0.0343)
  Directional -> Accuracy: 0.6038, MCC: 0.2109, F1: 0.6557

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.25655 | val 1.29548
  Epoch 011 - train 0.22799 | val 1.28277
  Classification -> best τ=0.575 (val F1=0.1210)
  Directional -> Accuracy: 0.4545, MCC: -0.0806, F1: 0.1176

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.33598 | val 0.65664

[I 2026-02-22 09:42:19,548] Trial 66 finished with value: 0.24915686876278573 and parameters: {'feature_set': 'sector_unified_emotion', 'model_type': 'BiLSTM', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 128, 'num_layers': 1, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.0, 'batch_size': 64, 'learning_rate': 0.0030067617776412285, 'weight_decay': 3.126134264463739e-07, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 1.5629869540834331, 'early_stopping_min_delta': 0.008793546856373327}. Best is trial 22 with value: 0.2833350641483003.

  Epoch 018 - train 0.09089 | val 1.17795
  Classification -> best τ=0.290 (val F1=0.2966)
  Directional -> Accuracy: 0.4833, MCC: -0.0201, F1: 0.5753

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.24915686876278573
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d', 'positive_emotion', 'negative_emotion', 'uncertainty_emotion', 'positive_emotion_pct', 'negative_emotion_pct', 'uncertainty_emotion_pct']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.56293 | val 0.71396
  Epoch 014 - train 0.51065 | val 0.76370
  Classification -> best τ=0.520 (val F1=0.2125)
  Directional -> Accuracy: 0.5658, MCC: 0.1351, F1: 0.5479

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.54399 | val 0.71814
  Epoch 016 - train 0.43902 | val 0.83172
  Classification -> best τ=0.400 (val F1=0.2769)
  Directional -> Accuracy: 0.5778, MCC: 0.0000, F1: 0.7324

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.61306 | val 0.75027
  Epoch 011 - train 0.59675 | val 0.76562
  Classification -> best τ=0.515 (val F1=0.3251)
  Directional -> Accuracy: 0.4783, MCC: -0.0733, F1: 0.5862

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.56152 | val 1.14283
  Epoch 011 - train 0.57730 | val 1.12882
  Classification -> best τ=0.445 (val F1=0.2246)
  Directional -> Accuracy: 0.5135, MCC: -0.0231, F1: 0.6327

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.56678 | val 0.66249
  Epoch 019 - train 0.45388 | val 0.84157
  Classification -> best τ=0.565 (val F1=0.3181)
  Directional -> Accuracy: 0.5800, MCC: 0.2044, F1: 0.4615

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.56670 | val 0.70187
  Epoch 011 - train 0.55399 | val 0.71356
  Classification -> best τ=0.515 (val F1=0.1829)
  Directional -> Accuracy: 0.5217, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.61086 | val 0.77373
  Epoch 011 - train 0.58865 | val 0.79807
  Classification -> best τ=0.455 (val F1=0.3042)
  Directional -> Accuracy: 0.5588, MCC: 0.1021, F1: 0.4828

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.58633 | val 0.61540
  Epoch 020 - train 0.41831 | val 0.50143
  Epoch 030 - train 0.28908 | val 0.61671
  Classification -> best τ=0.490 (val F1=0.6556)
  Directional -> Accuracy: 0.4286, MCC: -0.0589, F1: 0.5556

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.58858 | val 0.76981
  Epoch 011 - train 0.57999 | val 0.79713
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4375, MCC: 0.0000, F1: 0.6087

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.55374 | val 0.72707
  Epoch 011 - train 0.55913 | val 0.72886
  Classification -> best τ=0.530 (val F1=0.2355)
  Directional -> Accuracy: 0.4783, MCC: 0.0054, F1: 0.5135

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.57822 | val 0.90162
  Epoch 011 - train 0.57969 | val 0.91687
  Classification -> best τ=0.520 (val F1=0.0946)
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.58487 | val 0.83172
  Epoch 011 - train 0.58745 | val 0.84207
  Classification -> best τ=0.485 (val F1=0.1009)
  Directional -> Accuracy: 0.5088, MCC: 0.0000, F1: 0.6744

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.52944 | val 0.81300
  Epoch 011 - train 0.53246 | val 0.84064
  Classification -> best τ=0.480 (val F1=0.3536)
  Directional -> Accuracy: 0.4048, MCC: -0.1664, F1: 0.4898

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.57758 | val 0.62150
  Epoch 020 - train 0.45924 | val 0.71359
  Classification -> best τ=0.675 (val F1=0.3642)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.56477 | val 0.76224
  Epoch 011 - train 0.57287 | val 0.77909
  Classification -> best τ=0.525 (val F1=0.1613)
  Directional -> Accuracy: 0.5490, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.56544 | val 0.86788
  Epoch 011 - train 0.55957 | val 0.87575
  Classification -> best τ=0.430 (val F1=0.2341)
  Directional -> Accuracy: 0.5942, MCC: 0.2667, F1: 0.7255

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.58966 | val 0.81025
  Epoch 011 - train 0.55817 | val 0.83220
  Classification -> best τ=0.530 (val F1=0.2882)
  Directional -> Accuracy: 0.4310, MCC: 0.1135, F1: 0.1951

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.59689 | val 1.14720
  Epoch 011 - train 0.59171 | val 1.14012
  Classification -> best τ=0.425 (val F1=0.2071)
  Directional -> Accuracy: 0.6000, MCC: 0.0338, F1: 0.7458

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.58097 | val 0.66173
  Epoch 018 - train 0.47359 | val 0.76865
  Classification -> best τ=0.255 (val F1=0.3140)
  Directional -> Accuracy: 0.5938, MCC: 0.1949, F1: 0.6176

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.56643 | val 0.68148
  Epoch 018 - train 0.47577 | val 0.92603
  Classification -> best τ=0.345 (val F1=0.3377)
  Directional -> Accuracy: 0.5676, MCC: 0.2029, F1: 0.4839

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.55720 | val 0.80014
  Epoch 011 - train 0.55845 | val 0.81298
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.6170, MCC: 0.0000, F1: 0.7632

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.59670 | val 0.80942
  Epoch 011 - train 0.59227 | val 0.82640
  Classification -> best τ=0.515 (val F1=0.1925)
  Directional -> Accuracy: 0.4923, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.59952 | val 0.69920
  Epoch 012 - train 0.57389 | val 0.69322
  Classification -> best τ=0.570 (val F1=0.3833)
  Directional -> Accuracy: 0.5439, MCC: 0.1313, F1: 0.5000

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.60013 | val 0.69877
  Epoch 011 - train 0.58601 | val 0.70494
  Classification -> best τ=0.485 (val F1=0.2290)
  Directional -> Accuracy: 0.4923, MCC: -0.0251, F1: 0.4211

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.53868 | val 0.65415
  Epoch 018 - train 0.42996 | val 0.85574
  Classification -> best τ=0.420 (val F1=0.4068)
  Directional -> Accuracy: 0.5636, MCC: 0.1587, F1: 0.5200

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.57724 | val 0.71181
  Epoch 011 - train 0.58450 | val 0.71351
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.5938

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.57769 | val 0.68802
  Epoch 013 - train 0.56171 | val 0.72584
  Classification -> best τ=0.520 (val F1=0.3596)
  Directional -> Accuracy: 0.4524, MCC: -0.2178, F1: 0.5965

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.54923 | val 0.85792
  Epoch 011 - train 0.53480 | val 0.87475
  Classification -> best τ=0.440 (val F1=0.1467)
  Directional -> Accuracy: 0.5179, MCC: 0.1373, F1: 0.3415

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.59579 | val 0.73815
  Epoch 011 - train 0.57378 | val 0.74779
  Classification -> best τ=0.475 (val F1=0.3287)
  Directional -> Accuracy: 0.5500, MCC: 0.0503, F1: 0.6667

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.62109 | val 0.75474
  Epoch 011 - train 0.62126 | val 0.76589
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4762, MCC: 0.0000, F1: 0.6452

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.58398 | val 0.92077
  Epoch 011 - train 0.59765 | val 0.94688
  Classification -> best τ=0.515 (val F1=0.1846)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.57357 | val 0.81538
  Epoch 011 - train 0.55960 | val 0.89114
  Classification -> best τ=0.515 (val F1=0.3639)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.56741 | val 0.68214
  Epoch 014 - train 0.52459 | val 0.72789
  Classification -> best τ=0.370 (val F1=0.3477)
  Directional -> Accuracy: 0.4861, MCC: 0.0205, F1: 0.3934

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.58239 | val 0.70923
  Epoch 011 - train 0.55784 | val 0.71595
  Classification -> best τ=0.435 (val F1=0.1874)
  Directional -> Accuracy: 0.4651, MCC: -0.0660, F1: 0.5490

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.59639 | val 0.75115
  Epoch 011 - train 0.60476 | val 0.75760
  Classification -> best τ=0.430 (val F1=0.3603)
  Directional -> Accuracy: 0.6061, MCC: 0.1545, F1: 0.7111

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.57987 | val 0.68443
  Epoch 015 - train 0.50219 | val 0.79269
  Classification -> best τ=0.445 (val F1=0.2858)
  Directional -> Accuracy: 0.7619, MCC: 0.5227, F1: 0.7727

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.54264 | val 0.99623
  Epoch 013 - train 0.48913 | val 1.20506
  Classification -> best τ=0.520 (val F1=0.1886)
  Directional -> Accuracy: 0.4286, MCC: -0.1344, F1: 0.4483

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.53149 | val 0.79878
  Epoch 011 - train 0.49952 | val 0.81129
  Classification -> best τ=0.500 (val F1=0.3105)
  Directional -> Accuracy: 0.5217, MCC: 0.1179, F1: 0.5000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.57483 | val 0.70026
  Epoch 011 - train 0.58590 | val 0.70135
  Classification -> best τ=0.500 (val F1=0.2513)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.53411 | val 1.04180
  Epoch 011 - train 0.50942 | val 1.11795
  Classification -> best τ=0.525 (val F1=0.2148)
  Directional -> Accuracy: 0.4865, MCC: -0.0211, F1: 0.5366

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.58915 | val 0.72337
  Epoch 011 - train 0.58929 | val 0.72055
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5111, MCC: 0.0000, F1: 0.6765

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.56899 | val 0.69591
  Epoch 011 - train 0.53469 | val 0.70123
  Classification -> best τ=0.470 (val F1=0.2408)
  Directional -> Accuracy: 0.5952, MCC: 0.2071, F1: 0.6047

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.58289 | val 0.69141
  Epoch 019 - train 0.50137 | val 0.71226
  Classification -> best τ=0.430 (val F1=0.5514)
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.5455

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.58816 | val 0.73647
  Epoch 013 - train 0.55736 | val 0.79030
  Classification -> best τ=0.510 (val F1=0.2111)
  Directional -> Accuracy: 0.5091, MCC: 0.1295, F1: 0.2703

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.52565 | val 0.69054
  Epoch 017 - train 0.44182 | val 0.82377
  Classification -> best τ=0.620 (val F1=0.3491)
  Directional -> Accuracy: 0.4643, MCC: -0.1303, F1: 0.1667

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.57899 | val 0.78281
  Epoch 011 - train 0.56697 | val 0.79872
  Classification -> best τ=0.440 (val F1=0.1810)
  Directional -> Accuracy: 0.5094, MCC: 0.0000, F1: 0.6750

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.56268 | val 0.91542
  Epoch 011 - train 0.54602 | val 0.91378
  Classification -> best τ=0.495 (val F1=0.1186)
  Directional -> Accuracy: 0.5091, MCC: -0.0338, F1: 0.6494

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.57328 | val 0.65179

[I 2026-02-22 09:43:12,682] Trial 67 finished with value: 0.24868583853651915 and parameters: {'feature_set': 'sector_unified_emotion', 'model_type': 'BiGRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 32, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.0, 'batch_size': 64, 'learning_rate': 0.0015391434182906172, 'weight_decay': 1.926572006572815e-07, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 1.4342559009583788, 'early_stopping_min_delta': 0.008486343929928926}. Best is trial 22 with value: 0.2833350641483003.

  Epoch 020 - train 0.44233 | val 0.66427
  Classification -> best τ=0.480 (val F1=0.3525)
  Directional -> Accuracy: 0.5833, MCC: 0.1638, F1: 0.5098

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.24868583853651915
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d', 'positive_emotion', 'negative_emotion', 'uncertainty_emotion', 'positive_emotion_pct', 'negative_emotion_pct', 'uncertainty_emotion_pct']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.56453 | val 0.72324
  Epoch 016 - train 0.53482 | val 1.11709
  Classification -> best τ=0.445 (val F1=0.2510)
  Directional -> Accuracy: 0.5132, MCC: 0.0293, F1: 0.4932

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.53403 | val 0.70955
  Epoch 011 - train 0.49861 | val 0.71129
  Classification -> best τ=0.480 (val F1=0.2428)
  Directional -> Accuracy: 0.5778, MCC: 0.0000, F1: 0.7324

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.59488 | val 0.84316
  Epoch 011 - train 0.58247 | val 0.95988
  Classification -> best τ=0.520 (val F1=0.2275)
  Directional -> Accuracy: 0.4130, MCC: -0.1691, F1: 0.3721

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.62047 | val 0.86348
  Epoch 011 - train 0.60376 | val 0.99611
  Classification -> best τ=0.490 (val F1=0.1414)
  Directional -> Accuracy: 0.5405, MCC: 0.0000, F1: 0.7018

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.51706 | val 0.63872
  Epoch 020 - train 0.40727 | val 0.75160
  Classification -> best τ=0.680 (val F1=0.3933)
  Directional -> Accuracy: 0.6200, MCC: 0.3170, F1: 0.4865

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.54929 | val 1.04774
  Epoch 011 - train 0.56954 | val 1.38589
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4783, MCC: 0.0000, F1: 0.6471

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.59375 | val 0.85701
  Epoch 015 - train 0.52981 | val 0.95336
  Classification -> best τ=0.440 (val F1=0.3336)
  Directional -> Accuracy: 0.5000, MCC: 0.1418, F1: 0.5750

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.53035 | val 0.83163
  Epoch 012 - train 0.51432 | val 1.15871
  Classification -> best τ=0.490 (val F1=0.1639)
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.55458 | val 0.95051
  Epoch 011 - train 0.57920 | val 0.97206
  Classification -> best τ=0.515 (val F1=0.2443)
  Directional -> Accuracy: 0.4375, MCC: 0.0000, F1: 0.6087

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.55631 | val 0.78163
  Epoch 011 - train 0.55668 | val 0.79968
  Classification -> best τ=0.475 (val F1=0.2679)
  Directional -> Accuracy: 0.4203, MCC: 0.0000, F1: 0.5918

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.52211 | val 1.04164
  Epoch 011 - train 0.50811 | val 1.01548
  Classification -> best τ=0.550 (val F1=0.1301)
  Directional -> Accuracy: 0.5510, MCC: 0.0453, F1: 0.2667

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.57185 | val 0.86443
  Epoch 011 - train 0.59356 | val 0.92756
  Classification -> best τ=0.480 (val F1=0.1512)
  Directional -> Accuracy: 0.5088, MCC: 0.0000, F1: 0.6744

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.53474 | val 0.89175
  Epoch 011 - train 0.53946 | val 0.97034
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.6230

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.57487 | val 0.74478
  Epoch 012 - train 0.56142 | val 0.84502
  Classification -> best τ=0.500 (val F1=0.3378)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.54405 | val 0.72316
  Epoch 017 - train 0.47995 | val 0.82210
  Classification -> best τ=0.510 (val F1=0.3469)
  Directional -> Accuracy: 0.5490, MCC: 0.0287, F1: 0.1481

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.56399 | val 0.95313
  Epoch 012 - train 0.56190 | val 0.90682
  Classification -> best τ=0.450 (val F1=0.1512)
  Directional -> Accuracy: 0.5362, MCC: 0.0000, F1: 0.6981

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.60412 | val 0.90049
  Epoch 011 - train 0.57342 | val 0.88907
  Classification -> best τ=0.540 (val F1=0.2651)
  Directional -> Accuracy: 0.3276, MCC: -0.3241, F1: 0.3607

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.59208 | val 0.91164
  Epoch 011 - train 0.59779 | val 0.86918
  Classification -> best τ=0.495 (val F1=0.0714)
  Directional -> Accuracy: 0.6000, MCC: 0.0000, F1: 0.7500

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.60377 | val 0.71106
  Epoch 011 - train 0.60241 | val 0.72250
  Classification -> best τ=0.495 (val F1=0.2752)
  Directional -> Accuracy: 0.5781, MCC: 0.0913, F1: 0.6824

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.56570 | val 0.74360
  Epoch 014 - train 0.51529 | val 0.82066
  Classification -> best τ=0.480 (val F1=0.2882)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.58423 | val 0.70934
  Epoch 011 - train 0.54841 | val 0.72074
  Classification -> best τ=0.475 (val F1=0.1413)
  Directional -> Accuracy: 0.5745, MCC: -0.0074, F1: 0.7059

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.62625 | val 0.71623
  Epoch 016 - train 0.56087 | val 0.78590
  Classification -> best τ=0.505 (val F1=0.3190)
  Directional -> Accuracy: 0.5231, MCC: 0.1014, F1: 0.2051

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.55724 | val 0.61686
  Epoch 020 - train 0.41707 | val 0.68898
  Classification -> best τ=0.740 (val F1=0.3833)
  Directional -> Accuracy: 0.5614, MCC: 0.2071, F1: 0.4681

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.56692 | val 0.78540
  Epoch 011 - train 0.57132 | val 0.76171
  Classification -> best τ=0.470 (val F1=0.0462)
  Directional -> Accuracy: 0.5846, MCC: 0.1851, F1: 0.6197

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.52960 | val 0.75178
  Epoch 015 - train 0.45809 | val 1.04695
  Classification -> best τ=0.500 (val F1=0.3091)
  Directional -> Accuracy: 0.6545, MCC: 0.3416, F1: 0.6275

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.50963 | val 0.71067
  Epoch 011 - train 0.51903 | val 0.71155
  Classification -> best τ=0.510 (val F1=0.1251)
  Directional -> Accuracy: 0.5111, MCC: 0.0885, F1: 0.5600

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.58075 | val 0.68631
  Epoch 011 - train 0.58388 | val 0.68168
  Classification -> best τ=0.515 (val F1=0.1936)
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.0000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.54198 | val 0.91374
  Epoch 011 - train 0.53951 | val 1.01895
  Classification -> best τ=0.490 (val F1=0.1718)
  Directional -> Accuracy: 0.5357, MCC: 0.1974, F1: 0.3500

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.56601 | val 0.72414
  Epoch 011 - train 0.52363 | val 0.70239
  Classification -> best τ=0.480 (val F1=0.1448)
  Directional -> Accuracy: 0.6000, MCC: 0.2010, F1: 0.7241

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.58650 | val 1.23820
  Epoch 011 - train 0.55863 | val 1.23389
  Classification -> best τ=0.500 (val F1=0.2221)
  Directional -> Accuracy: 0.5238, MCC: 0.0413, F1: 0.4737

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.60156 | val 1.04175
  Epoch 011 - train 0.58648 | val 1.15393
  Classification -> best τ=0.515 (val F1=0.1286)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.56149 | val 0.80532
  Epoch 016 - train 0.43041 | val 1.34584
  Classification -> best τ=0.450 (val F1=0.3242)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.57387 | val 0.84176
  Epoch 011 - train 0.57174 | val 0.79604
  Classification -> best τ=0.485 (val F1=0.2774)
  Directional -> Accuracy: 0.5278, MCC: 0.1291, F1: 0.4138

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.53550 | val 0.76550
  Epoch 011 - train 0.52202 | val 0.78631
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.62206 | val 0.74270
  Epoch 011 - train 0.60160 | val 0.72596
  Classification -> best τ=0.490 (val F1=0.2088)
  Directional -> Accuracy: 0.6061, MCC: 0.1678, F1: 0.6905

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.52423 | val 1.10740
  Epoch 011 - train 0.51747 | val 1.51224
  Classification -> best τ=0.465 (val F1=0.2132)
  Directional -> Accuracy: 0.6905, MCC: 0.3977, F1: 0.6667

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.52731 | val 1.07960
  Epoch 011 - train 0.51732 | val 1.33508
  Classification -> best τ=0.520 (val F1=0.2755)
  Directional -> Accuracy: 0.4821, MCC: -0.0283, F1: 0.4912

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.50238 | val 0.75782
  Epoch 011 - train 0.44433 | val 0.74971
  Classification -> best τ=0.480 (val F1=0.3105)
  Directional -> Accuracy: 0.5217, MCC: 0.1431, F1: 0.4762

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.57645 | val 0.67136
  Epoch 020 - train 0.47249 | val 0.63691
  Epoch 030 - train 0.33845 | val 0.63644
  Epoch 031 - train 0.30354 | val 0.62213
  Classification -> best τ=0.550 (val F1=0.4625)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.52708 | val 0.90560
  Epoch 011 - train 0.50365 | val 0.97368
  Classification -> best τ=0.485 (val F1=0.1348)
  Directional -> Accuracy: 0.5135, MCC: 0.0310, F1: 0.5385

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.63138 | val 0.70850
  Epoch 014 - train 0.56848 | val 0.71679
  Classification -> best τ=0.515 (val F1=0.2668)
  Directional -> Accuracy: 0.4667, MCC: -0.0629, F1: 0.3684

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.51790 | val 0.64542
  Epoch 020 - train 0.35895 | val 0.88411
  Epoch 022 - train 0.32824 | val 0.92745
  Classification -> best τ=0.240 (val F1=0.4082)
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.7273

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.57128 | val 0.68662
  Epoch 020 - train 0.45149 | val 0.78422
  Epoch 023 - train 0.34611 | val 0.65960
  Classification -> best τ=0.520 (val F1=0.5557)
  Directional -> Accuracy: 0.4167, MCC: 0.1615, F1: 0.5625

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.58712 | val 0.72625
  Epoch 011 - train 0.57046 | val 0.80867
  Classification -> best τ=0.530 (val F1=0.1474)
  Directional -> Accuracy: 0.4727, MCC: 0.1242, F1: 0.0645

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.51660 | val 0.70423
  Epoch 013 - train 0.46348 | val 0.77217
  Classification -> best τ=0.485 (val F1=0.2696)
  Directional -> Accuracy: 0.5000, MCC: 0.0121, F1: 0.5625

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.59086 | val 0.67723
  Epoch 017 - train 0.52358 | val 1.03350
  Classification -> best τ=0.455 (val F1=0.2668)
  Directional -> Accuracy: 0.5472, MCC: 0.1483, F1: 0.6842

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.53322 | val 0.89687
  Epoch 011 - train 0.52891 | val 0.89931
  Classification -> best τ=0.490 (val F1=0.2291)
  Directional -> Accuracy: 0.4727, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.57454 | val 0.65835

[I 2026-02-22 09:44:17,179] Trial 68 finished with value: 0.23405694067258084 and parameters: {'feature_set': 'sector_unified_emotion', 'model_type': 'LSTM', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.4, 'dropout': 0.1, 'batch_size': 64, 'learning_rate': 0.004144567908178734, 'weight_decay': 3.461126595215561e-07, 'lr_patience': 5, 'lr_factor': 0.8, 'early_stopping_patience': 10, 'max_epochs': 50, 'huber_delta': 0.9819956698072563, 'early_stopping_min_delta': 0.00903784284143543}. Best is trial 22 with value: 0.2833350641483003.

  Epoch 019 - train 0.45666 | val 0.69683
  Classification -> best τ=0.420 (val F1=0.4160)
  Directional -> Accuracy: 0.6000, MCC: 0.1978, F1: 0.5714

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.23405694067258084
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d', 'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down', 'finbert_neutral']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.55451 | val 0.79481
  Epoch 011 - train 0.54918 | val 0.88271
  Classification -> best τ=0.460 (val F1=0.0676)
  Directional -> Accuracy: 0.6364, MCC: 0.2865, F1: 0.6410

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.45319 | val 0.70221
  Epoch 013 - train 0.37189 | val 0.74825
  Classification -> best τ=0.475 (val F1=0.2573)
  Directional -> Accuracy: 0.6087, MCC: 0.1757, F1: 0.7097

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.49853 | val 1.21985
  Epoch 011 - train 0.49164 | val 1.21631
  Classification -> best τ=0.530 (val F1=0.2616)
  Directional -> Accuracy: 0.5106, MCC: 0.1033, F1: 0.2581

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.53941 | val 1.35219
  Epoch 011 - train 0.51493 | val 1.51835
  Classification -> best τ=0.495 (val F1=0.1210)
  Directional -> Accuracy: 0.5600, MCC: 0.2300, F1: 0.4000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.44491 | val 1.79660
  Epoch 012 - train 0.41172 | val 2.16305
  Classification -> best τ=0.510 (val F1=0.4737)
  Directional -> Accuracy: 0.6275, MCC: 0.2745, F1: 0.5957

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.51560 | val 0.67423
  Epoch 018 - train 0.36493 | val 1.10618
  Classification -> best τ=0.425 (val F1=0.3430)
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.51993 | val 1.00733
  Epoch 011 - train 0.47720 | val 1.08802
  Classification -> best τ=0.615 (val F1=0.1765)
  Directional -> Accuracy: 0.5942, MCC: 0.0000, F1: 0.0000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.46254 | val 2.00792
  Epoch 011 - train 0.43844 | val 2.25756
  Classification -> best τ=0.545 (val F1=0.2180)
  Directional -> Accuracy: 0.5909, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.51010 | val 1.03882
  Epoch 012 - train 0.45596 | val 1.32736
  Classification -> best τ=0.465 (val F1=0.1723)
  Directional -> Accuracy: 0.5918, MCC: 0.1633, F1: 0.5000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.48626 | val 1.12855
  Epoch 012 - train 0.43178 | val 1.18198
  Classification -> best τ=0.730 (val F1=0.1137)
  Directional -> Accuracy: 0.5571, MCC: 0.0556, F1: 0.3673

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.49412 | val 1.50167
  Epoch 012 - train 0.45277 | val 1.76967
  Classification -> best τ=0.595 (val F1=0.4676)
  Directional -> Accuracy: 0.5600, MCC: 0.1048, F1: 0.1538

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.44580 | val 1.51610
  Epoch 011 - train 0.48441 | val 1.56797
  Classification -> best τ=0.440 (val F1=0.1635)
  Directional -> Accuracy: 0.5862, MCC: 0.2381, F1: 0.6923

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.42901 | val 1.69956
  Epoch 011 - train 0.41346 | val 1.78970
  Classification -> best τ=0.480 (val F1=0.1960)
  Directional -> Accuracy: 0.4884, MCC: -0.0261, F1: 0.4500

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.49491 | val 0.73020
  Epoch 014 - train 0.48967 | val 0.86732
  Classification -> best τ=0.595 (val F1=0.3400)
  Directional -> Accuracy: 0.4918, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.51710 | val 0.82192
  Epoch 011 - train 0.50538 | val 0.82872
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4615, MCC: 0.0000, F1: 0.6316

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.50768 | val 1.49564
  Epoch 012 - train 0.43988 | val 1.38854
  Classification -> best τ=0.575 (val F1=0.2264)
  Directional -> Accuracy: 0.5429, MCC: 0.0885, F1: 0.5556

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.55687 | val 1.99654
  Epoch 011 - train 0.51027 | val 2.01933
  Classification -> best τ=0.550 (val F1=0.1302)
  Directional -> Accuracy: 0.3898, MCC: -0.0628, F1: 0.2174

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.56281 | val 1.42475
  Epoch 011 - train 0.52760 | val 1.38451
  Classification -> best τ=0.470 (val F1=0.2137)
  Directional -> Accuracy: 0.6053, MCC: 0.0000, F1: 0.7541

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.52437 | val 0.83961
  Epoch 012 - train 0.44557 | val 0.84279
  Classification -> best τ=0.305 (val F1=0.3280)
  Directional -> Accuracy: 0.5846, MCC: 0.1590, F1: 0.6301

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.51560 | val 0.76206
  Epoch 012 - train 0.45747 | val 0.76677
  Classification -> best τ=0.430 (val F1=0.2385)
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.52165 | val 0.79110
  Epoch 011 - train 0.49294 | val 0.80678
  Classification -> best τ=0.440 (val F1=0.2425)
  Directional -> Accuracy: 0.6042, MCC: 0.0176, F1: 0.7397

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.56038 | val 0.84983
  Epoch 011 - train 0.56433 | val 0.79414
  Classification -> best τ=0.390 (val F1=0.2694)
  Directional -> Accuracy: 0.5758, MCC: 0.1590, F1: 0.5000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.53036 | val 1.15720
  Epoch 012 - train 0.49349 | val 1.29887
  Classification -> best τ=0.515 (val F1=0.2530)
  Directional -> Accuracy: 0.6034, MCC: 0.2171, F1: 0.7416

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.54655 | val 0.86152
  Epoch 012 - train 0.59213 | val 0.97657
  Classification -> best τ=0.465 (val F1=0.2209)
  Directional -> Accuracy: 0.5000, MCC: 0.0260, F1: 0.5714

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.46112 | val 1.07251
  Epoch 014 - train 0.40962 | val 1.05634
  Classification -> best τ=0.400 (val F1=0.3482)
  Directional -> Accuracy: 0.5536, MCC: 0.1704, F1: 0.4681

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.42914 | val 0.85936
  Epoch 011 - train 0.41160 | val 0.85884
  Classification -> best τ=0.495 (val F1=0.2774)
  Directional -> Accuracy: 0.4130, MCC: -0.1164, F1: 0.5574

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.51634 | val 0.72964
  Epoch 011 - train 0.49099 | val 0.74230
  Classification -> best τ=0.495 (val F1=0.2588)
  Directional -> Accuracy: 0.5349, MCC: 0.1076, F1: 0.5238

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.42735 | val 1.16867
  Epoch 011 - train 0.47486 | val 1.18299
  Classification -> best τ=0.465 (val F1=0.0972)
  Directional -> Accuracy: 0.4561, MCC: -0.1963, F1: 0.5974

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.41883 | val 0.82475
  Epoch 011 - train 0.46728 | val 0.81567
  Classification -> best τ=0.480 (val F1=0.2821)
  Directional -> Accuracy: 0.4634, MCC: -0.1383, F1: 0.5926

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.49847 | val 2.69626
  Epoch 011 - train 0.48684 | val 2.52912
  Classification -> best τ=0.560 (val F1=0.2683)
  Directional -> Accuracy: 0.4884, MCC: -0.0353, F1: 0.3529

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.54855 | val 0.70103
  Epoch 011 - train 0.55336 | val 0.71758
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.40542 | val 0.96094
  Epoch 011 - train 0.47533 | val 1.18451
  Classification -> best τ=0.435 (val F1=0.2806)
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.54276 | val 0.94901
  Epoch 012 - train 0.46199 | val 0.94932
  Classification -> best τ=0.395 (val F1=0.2933)
  Directional -> Accuracy: 0.5068, MCC: 0.1939, F1: 0.2500

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.48506 | val 0.77876
  Epoch 012 - train 0.47776 | val 0.83787
  Classification -> best τ=0.465 (val F1=0.3162)
  Directional -> Accuracy: 0.4737, MCC: -0.1644, F1: 0.6429

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.48883 | val 1.21124
  Epoch 011 - train 0.43724 | val 1.28854
  Classification -> best τ=0.430 (val F1=0.1902)
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.53058 | val 1.18944
  Epoch 011 - train 0.49708 | val 1.21358
  Classification -> best τ=0.435 (val F1=0.2908)
  Directional -> Accuracy: 0.6119, MCC: 0.2322, F1: 0.6286

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.46131 | val 0.67385
  Epoch 018 - train 0.31198 | val 1.05546
  Classification -> best τ=0.800 (val F1=0.3943)
  Directional -> Accuracy: 0.6279, MCC: 0.2817, F1: 0.5556

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.42730 | val 1.32223
  Epoch 011 - train 0.40913 | val 1.61261
  Classification -> best τ=0.445 (val F1=0.2235)
  Directional -> Accuracy: 0.4561, MCC: -0.0792, F1: 0.4918

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.45404 | val 0.89376
  Epoch 011 - train 0.44686 | val 0.89515
  Classification -> best τ=0.380 (val F1=0.3014)
  Directional -> Accuracy: 0.5957, MCC: 0.0121, F1: 0.7324

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.48289 | val 0.80746
  Epoch 015 - train 0.40990 | val 0.90598
  Classification -> best τ=0.565 (val F1=0.3482)
  Directional -> Accuracy: 0.3469, MCC: -0.1894, F1: 0.5152

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.45675 | val 1.70319
  Epoch 011 - train 0.38591 | val 1.86756
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.47373 | val 1.34141
  Epoch 011 - train 0.46969 | val 1.53886
  Classification -> best τ=0.410 (val F1=0.2995)
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.51690 | val 0.69576
  Epoch 011 - train 0.49930 | val 0.69305
  Classification -> best τ=0.495 (val F1=0.0484)
  Directional -> Accuracy: 0.4681, MCC: -0.0764, F1: 0.1379

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.44431 | val 1.09821
  Epoch 011 - train 0.41825 | val 1.12172
  Classification -> best τ=0.475 (val F1=0.2425)
  Directional -> Accuracy: 0.5909, MCC: 0.1900, F1: 0.6087

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.51695 | val 0.88589
  Epoch 020 - train 0.29900 | val 1.67514
  Epoch 022 - train 0.30623 | val 1.40999
  Classification -> best τ=0.370 (val F1=0.3731)
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.54276 | val 0.77674
  Epoch 011 - train 0.54523 | val 0.77181
  Classification -> best τ=0.540 (val F1=0.2180)
  Directional -> Accuracy: 0.5893, MCC: 0.2134, F1: 0.5306

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.47369 | val 1.20198
  Epoch 013 - train 0.38839 | val 1.45972
  Classification -> best τ=0.490 (val F1=0.4250)
  Directional -> Accuracy: 0.4912, MCC: -0.0349, F1: 0.3830

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.54830 | val 1.33301
  Epoch 012 - train 0.51689 | val 1.44331
  Classification -> best τ=0.410 (val F1=0.2410)
  Directional -> Accuracy: 0.5556, MCC: 0.2035, F1: 0.7000

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.46880 | val 1.22984
  Epoch 011 - train 0.45519 | val 1.23150
  Classification -> best τ=0.420 (val F1=0.2060)
  Directional -> Accuracy: 0.5179, MCC: 0.0000, F1: 0.6824

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.56110 | val 0.69242

[I 2026-02-22 09:45:19,815] Trial 69 finished with value: 0.2396377706666854 and parameters: {'feature_set': 'sector_finbert', 'model_type': 'BiGRU', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 64, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.30000000000000004, 'batch_size': 64, 'learning_rate': 0.0049181089176010976, 'weight_decay': 7.022836773054387e-07, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 1.044168796127321, 'early_stopping_min_delta': 0.009615282111415331}. Best is trial 22 with value: 0.2833350641483003.

  Epoch 013 - train 0.43167 | val 0.79033
  Classification -> best τ=0.575 (val F1=0.2639)
  Directional -> Accuracy: 0.5246, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2396377706666854
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: classification
Sequence length: 6
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.50333 | val 1.14156
  Epoch 011 - train 0.43405 | val 1.63943
  Classification -> best τ=0.490 (val F1=0.2262)
  Directional -> Accuracy: 0.5823, MCC: 0.1561, F1: 0.5352

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 82). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.41035 | val 1.01938
  Epoch 011 - train 0.35700 | val 1.10393
  Classification -> best τ=0.435 (val F1=0.1286)
  Directional -> Accuracy: 0.5625, MCC: 0.0000, F1: 0.7200

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 82). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.41648 | val 1.30069
  Epoch 011 - train 0.39339 | val 1.51778
  Classification -> best τ=0.530 (val F1=0.2332)
  Directional -> Accuracy: 0.4898, MCC: 0.0334, F1: 0.2424

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.47746 | val 0.88150
  Epoch 011 - train 0.46571 | val 0.87308
  Classification -> best τ=0.570 (val F1=0.1132)
  Directional -> Accuracy: 0.5065, MCC: 0.1046, F1: 0.2963

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.39765 | val 0.76654
  Epoch 015 - train 0.29908 | val 1.01520
  Classification -> best τ=0.615 (val F1=0.3050)
  Directional -> Accuracy: 0.5660, MCC: 0.2040, F1: 0.4103

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.42859 | val 1.03467
  Epoch 012 - train 0.39105 | val 1.35214
  Classification -> best τ=0.510 (val F1=0.2032)
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.49085 | val 0.73111
  Epoch 017 - train 0.28894 | val 0.83439
  Classification -> best τ=0.750 (val F1=0.2425)
  Directional -> Accuracy: 0.5915, MCC: 0.0317, F1: 0.0645

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 82). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 82). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.41325 | val 0.87167
  Epoch 011 - train 0.38867 | val 0.95722
  Classification -> best τ=0.530 (val F1=0.1850)
  Directional -> Accuracy: 0.4043, MCC: 0.0000, F1: 0.5758

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.49009 | val 0.73316
  Epoch 011 - train 0.45673 | val 0.76617
  Classification -> best τ=0.520 (val F1=0.3087)
  Directional -> Accuracy: 0.5814, MCC: 0.1068, F1: 0.4375

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 82). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 82). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.41687 | val 1.49511
  Epoch 011 - train 0.40697 | val 2.59695
  Classification -> best τ=0.360 (val F1=0.2992)
  Directional -> Accuracy: 0.4306, MCC: 0.0000, F1: 0.6019

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.38218 | val 1.04051
  Epoch 012 - train 0.33394 | val 1.57387
  Classification -> best τ=0.445 (val F1=0.2140)
  Directional -> Accuracy: 0.5769, MCC: 0.1682, F1: 0.5926

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.48974 | val 1.72807
  Epoch 011 - train 0.40457 | val 1.72191
  Classification -> best τ=0.470 (val F1=0.0711)
  Directional -> Accuracy: 0.5833, MCC: 0.2154, F1: 0.6835

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.40434 | val 0.87791
  Epoch 013 - train 0.34600 | val 1.07634
  Classification -> best τ=0.565 (val F1=0.1443)
  Directional -> Accuracy: 0.5333, MCC: 0.0598, F1: 0.4878

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 82). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.49773 | val 0.64584
  Epoch 017 - train 0.28343 | val 0.82083
  Classification -> best τ=0.355 (val F1=0.3264)
  Directional -> Accuracy: 0.5079, MCC: 0.0284, F1: 0.6076

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.42220 | val 1.28661
  Epoch 011 - train 0.39822 | val 2.61463
  Classification -> best τ=0.530 (val F1=0.2107)
  Directional -> Accuracy: 0.5000, MCC: 0.0028, F1: 0.5091

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.44053 | val 0.97567
  Epoch 012 - train 0.37381 | val 1.15052
  Classification -> best τ=0.395 (val F1=0.2038)
  Directional -> Accuracy: 0.5833, MCC: 0.1873, F1: 0.7170

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.44244 | val 1.24797
  Epoch 011 - train 0.44247 | val 1.38652
  Classification -> best τ=0.575 (val F1=0.1189)
  Directional -> Accuracy: 0.3934, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.44173 | val 1.56908
  Epoch 011 - train 0.41298 | val 1.53193
  Classification -> best τ=0.530 (val F1=0.1900)
  Directional -> Accuracy: 0.3974, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.49507 | val 0.80248
  Epoch 013 - train 0.38080 | val 0.96319
  Classification -> best τ=0.425 (val F1=0.2300)
  Directional -> Accuracy: 0.4776, MCC: 0.1598, F1: 0.2222

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 82). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.47184 | val 1.02350
  Epoch 013 - train 0.40641 | val 0.99624
  Classification -> best τ=0.410 (val F1=0.2764)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.40980 | val 0.95350
  Epoch 011 - train 0.35437 | val 1.09267
  Classification -> best τ=0.485 (val F1=0.2557)
  Directional -> Accuracy: 0.5600, MCC: 0.2428, F1: 0.5217

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 82). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 82). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 82). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.43863 | val 0.98325
  Epoch 011 - train 0.41283 | val 1.03061
  Classification -> best τ=0.510 (val F1=0.3237)
  Directional -> Accuracy: 0.5294, MCC: 0.0830, F1: 0.2727

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.44572 | val 1.16920
  Epoch 011 - train 0.45212 | val 1.01740
  Classification -> best τ=0.540 (val F1=0.2550)
  Directional -> Accuracy: 0.5000, MCC: 0.0406, F1: 0.4828

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.41251 | val 1.16797
  Epoch 011 - train 0.38029 | val 1.36231
  Classification -> best τ=0.455 (val F1=0.1859)
  Directional -> Accuracy: 0.5147, MCC: 0.0352, F1: 0.5479

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.40483 | val 0.96128
  Epoch 013 - train 0.31456 | val 1.05988
  Classification -> best τ=0.535 (val F1=0.4533)
  Directional -> Accuracy: 0.5345, MCC: 0.1519, F1: 0.4000

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.41419 | val 0.67299
  Epoch 020 - train 0.21483 | val 0.90796
  Classification -> best τ=0.355 (val F1=0.3812)
  Directional -> Accuracy: 0.5510, MCC: 0.1184, F1: 0.5417

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.44302 | val 0.88300
  Epoch 011 - train 0.41438 | val 0.94189
  Classification -> best τ=0.480 (val F1=0.2857)
  Directional -> Accuracy: 0.5778, MCC: -0.0364, F1: 0.7246

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.47493 | val 0.88728
  Epoch 011 - train 0.45130 | val 0.95010
  Classification -> best τ=0.360 (val F1=0.2312)
  Directional -> Accuracy: 0.5763, MCC: 0.2174, F1: 0.5098

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.42940 | val 0.76301
  Epoch 014 - train 0.33097 | val 0.92852
  Classification -> best τ=0.520 (val F1=0.2932)
  Directional -> Accuracy: 0.4091, MCC: -0.2064, F1: 0.1333

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.46687 | val 0.93544
  Epoch 011 - train 0.44973 | val 1.12562
  Classification -> best τ=0.535 (val F1=0.1712)
  Directional -> Accuracy: 0.5217, MCC: 0.0548, F1: 0.3125

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.42481 | val 0.88640
  Epoch 011 - train 0.41090 | val 1.03827
  Classification -> best τ=0.475 (val F1=0.3248)
  Directional -> Accuracy: 0.5435, MCC: 0.0000, F1: 0.7042

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.41403 | val 1.03524
  Epoch 012 - train 0.37521 | val 1.24467
  Classification -> best τ=0.485 (val F1=0.2384)
  Directional -> Accuracy: 0.5192, MCC: 0.0077, F1: 0.6753

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.43085 | val 0.78165
  Epoch 013 - train 0.35829 | val 1.09488
  Classification -> best τ=0.400 (val F1=0.3761)
  Directional -> Accuracy: 0.5600, MCC: 0.0000, F1: 0.7179

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 82). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.43923 | val 0.99183
  Epoch 011 - train 0.41179 | val 1.12820
  Classification -> best τ=0.550 (val F1=0.1918)
  Directional -> Accuracy: 0.5610, MCC: 0.1195, F1: 0.5000

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.45988 | val 0.76416
  Epoch 011 - train 0.43701 | val 0.83365
  Classification -> best τ=0.480 (val F1=0.2421)
  Directional -> Accuracy: 0.4565, MCC: 0.0000, F1: 0.6269

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.54168 | val 1.02284
  Epoch 011 - train 0.49405 | val 0.88105
  Classification -> best τ=0.470 (val F1=0.3296)
  Directional -> Accuracy: 0.4493, MCC: 0.0856, F1: 0.1364

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.43973 | val 0.78761
  Epoch 011 - train 0.42560 | val 0.72881
  Classification -> best τ=0.480 (val F1=0.3148)
  Directional -> Accuracy: 0.6667, MCC: 0.3380, F1: 0.6512

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.43269 | val 1.39101
  Epoch 011 - train 0.40613 | val 1.57820
  Classification -> best τ=0.500 (val F1=0.1506)
  Directional -> Accuracy: 0.4576, MCC: -0.0755, F1: 0.5000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.43454 | val 0.83276
  Epoch 011 - train 0.39895 | val 0.90705
  Classification -> best τ=0.530 (val F1=0.3278)
  Directional -> Accuracy: 0.5918, MCC: 0.0552, F1: 0.7143

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 82). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 82). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 82). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 82). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.44408 | val 0.87192
  Epoch 011 - train 0.42352 | val 0.96627
  Classification -> best τ=0.515 (val F1=0.2714)
  Directional -> Accuracy: 0.3810, MCC: 0.1581, F1: 0.5185

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 82). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.44351 | val 0.83493
  Epoch 012 - train 0.39534 | val 0.92617
  Classification -> best τ=0.480 (val F1=0.3780)
  Directional -> Accuracy: 0.5122, MCC: 0.0000, F1: 0.6774

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 82). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 82). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.43965 | val 1.60972
  Epoch 011 - train 0.39597 | val 1.51662
  Classification -> best τ=0.485 (val F1=0.1156)
  Directional -> Accuracy: 0.5065, MCC: 0.0000, F1: 0.6724

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 82). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 82). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.39217 | val 1.49629
  Epoch 011 - train 0.36347 | val 2.01166
  Classification -> best τ=0.540 (val F1=0.1664)
  Directional -> Accuracy: 0.5102, MCC: 0.0000, F1: 0.0000

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.40097 | val 1.24330
  Epoch 011 - train 0.37298 | val 1.39319
  Classification -> best τ=0.555 (val F1=0.0913)
  Directional -> Accuracy: 0.5745, MCC: 0.0682, F1: 0.6970

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.43237 | val 1.39575
  Epoch 011 - train 0.40852 | val 1.40839
  Classification -> best τ=0.620 (val F1=0.1425)
  Directional -> Accuracy: 0.5714, MCC: 0.3892, F1: 0.6250

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.46054 | val 1.16970
  Epoch 011 - train 0.44407 | val 1.28453
  Classification -> best τ=0.455 (val F1=0.1931)
  Directional -> Accuracy: 0.6207, MCC: 0.2332, F1: 0.6562

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.41939 | val 1.10370
  Epoch 011 - train 0.37731 | val 1.45984
  Classification -> best τ=0.500 (val F1=0.4001)
  Directional -> Accuracy: 0.5763, MCC: 0.1955, F1: 0.6667

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.46669 | val 1.08538
  Epoch 011 - train 0.46566 | val 1.33453
  Classification -> best τ=0.435 (val F1=0.1534)
  Directional -> Accuracy: 0.5714, MCC: 0.2067, F1: 0.7143

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.40898 | val 1.38329
  Epoch 011 - train 0.39340 | val 1.62712
  Classification -> best τ=0.575 (val F1=0.1522)
  Directional -> Accuracy: 0.5345, MCC: 0.1738, F1: 0.2286

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...

[I 2026-02-22 09:45:33,256] Trial 70 finished with value: 0.23479863608089135 and parameters: {'feature_set': 'sector', 'model_type': 'GRU', 'sequence_length': 6, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 128, 'num_layers': 1, 'inter_rnn_drop': 0.4, 'dropout': 0.0, 'batch_size': 64, 'learning_rate': 0.00259116099593644, 'weight_decay': 3.276379602234735e-06, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 1.6248401962653485, 'early_stopping_min_delta': 0.007862681180318616}. Best is trial 22 with value: 0.2833350641483003.

  Epoch 010 - train 0.46135 | val 1.07387
  Epoch 011 - train 0.40540 | val 1.62061
  Classification -> best τ=0.500 (val F1=0.1136)
  Directional -> Accuracy: 0.4762, MCC: 0.0000, F1: 0.6452

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.23479863608089135
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: classification
Sequence length: 30
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d', 'sentiment']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.52194 | val 1.09067
  Epoch 014 - train 0.28085 | val 1.72358
  Classification -> best τ=0.305 (val F1=0.2281)
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.6239

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 106). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.26753 | val 0.94660
  Epoch 011 - train 0.21296 | val 1.25461
  Classification -> best τ=0.610 (val F1=0.2503)
  Directional -> Accuracy: 0.5682, MCC: 0.2669, F1: 0.4865

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 106). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.22798 | val 4.03763
  Epoch 011 - train 0.19156 | val 4.75269
  Classification -> best τ=0.725 (val F1=0.2132)
  Directional -> Accuracy: 0.4889, MCC: 0.1410, F1: 0.0800

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.45507 | val 1.63140
  Epoch 012 - train 0.40936 | val 1.75646
  Classification -> best τ=0.510 (val F1=0.1848)
  Directional -> Accuracy: 0.5342, MCC: 0.0000, F1: 0.6964

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.37454 | val 1.16723
  Epoch 019 - train 0.07199 | val 1.22943
  Classification -> best τ=0.720 (val F1=0.4405)
  Directional -> Accuracy: 0.5102, MCC: 0.0799, F1: 0.1429

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.28595 | val 2.70785
  Epoch 013 - train 0.17607 | val 2.54964
  Classification -> best τ=0.475 (val F1=0.3859)
  Directional -> Accuracy: 0.5111, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.50887 | val 0.91376
  Epoch 012 - train 0.34378 | val 1.11777
  Classification -> best τ=0.440 (val F1=0.2321)
  Directional -> Accuracy: 0.4328, MCC: 0.0025, F1: 0.5476

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 106). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 106). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.31122 | val 1.25969
  Epoch 013 - train 0.29351 | val 1.34833
  Classification -> best τ=0.530 (val F1=0.2041)
  Directional -> Accuracy: 0.4390, MCC: -0.0278, F1: 0.5965

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.38197 | val 1.01836
  Epoch 014 - train 0.19456 | val 1.31161
  Classification -> best τ=0.450 (val F1=0.4301)
  Directional -> Accuracy: 0.4894, MCC: 0.0037, F1: 0.5200

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 106). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 106). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 106). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.42137 | val 1.16888
  Epoch 012 - train 0.27146 | val 1.31335
  Classification -> best τ=0.620 (val F1=0.0591)
  Directional -> Accuracy: 0.5294, MCC: 0.0120, F1: 0.3846

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.34855 | val 1.77786
  Epoch 012 - train 0.25705 | val 2.17423
  Classification -> best τ=0.715 (val F1=0.2896)
  Directional -> Accuracy: 0.6042, MCC: 0.2807, F1: 0.2400

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.34775 | val 1.82178
  Epoch 011 - train 0.30516 | val 1.53665
  Classification -> best τ=0.710 (val F1=0.1255)
  Directional -> Accuracy: 0.5357, MCC: 0.1486, F1: 0.2778

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 106). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.26625 | val 2.87312
  Epoch 011 - train 0.25268 | val 4.67322
  Classification -> best τ=0.605 (val F1=0.0080)
  Directional -> Accuracy: 0.4082, MCC: -0.1936, F1: 0.5085

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 106). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.35166 | val 0.97050
  Epoch 013 - train 0.20752 | val 0.93157
  Classification -> best τ=0.460 (val F1=0.3738)
  Directional -> Accuracy: 0.4915, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.31261 | val 3.34981
  Epoch 011 - train 0.31482 | val 2.94934
  Classification -> best τ=0.570 (val F1=0.2060)
  Directional -> Accuracy: 0.5600, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.43851 | val 1.12817
  Epoch 011 - train 0.39100 | val 1.30197
  Classification -> best τ=0.560 (val F1=0.2539)
  Directional -> Accuracy: 0.4853, MCC: -0.0277, F1: 0.4928

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 106). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.41216 | val 1.08463
  Epoch 011 - train 0.43436 | val 1.45232
  Classification -> best τ=0.660 (val F1=0.0614)
  Directional -> Accuracy: 0.3860, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.35703 | val 2.75561
  Epoch 011 - train 0.34707 | val 1.97957
  Classification -> best τ=0.500 (val F1=0.1537)
  Directional -> Accuracy: 0.3919, MCC: -0.1417, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.43376 | val 1.56426
  Epoch 011 - train 0.36368 | val 1.98433
  Classification -> best τ=0.495 (val F1=0.2288)
  Directional -> Accuracy: 0.4286, MCC: 0.0076, F1: 0.1429

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 106). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.39820 | val 1.22859
  Epoch 011 - train 0.34779 | val 1.52468
  Classification -> best τ=0.525 (val F1=0.1985)
  Directional -> Accuracy: 0.4658, MCC: 0.1070, F1: 0.0488

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.22924 | val 1.48878
  Epoch 011 - train 0.20455 | val 1.63650
  Classification -> best τ=0.420 (val F1=0.3223)
  Directional -> Accuracy: 0.5435, MCC: 0.2832, F1: 0.4324

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 106). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 106). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 106). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.30587 | val 1.56778
  Epoch 011 - train 0.23764 | val 1.87071
  Classification -> best τ=0.335 (val F1=0.2822)
  Directional -> Accuracy: 0.5781, MCC: 0.1942, F1: 0.4000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.39274 | val 2.21550
  Epoch 012 - train 0.31936 | val 2.41755
  Classification -> best τ=0.620 (val F1=0.2981)
  Directional -> Accuracy: 0.5893, MCC: 0.1572, F1: 0.6462

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.45186 | val 0.92775
  Epoch 012 - train 0.37361 | val 0.97108
  Classification -> best τ=0.445 (val F1=0.1846)
  Directional -> Accuracy: 0.5625, MCC: 0.1941, F1: 0.6500

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.37015 | val 1.69534
  Epoch 013 - train 0.17730 | val 2.45931
  Classification -> best τ=0.565 (val F1=0.5237)
  Directional -> Accuracy: 0.5000, MCC: 0.0736, F1: 0.2703

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.31756 | val 1.30198
  Epoch 011 - train 0.29606 | val 1.41395
  Classification -> best τ=0.570 (val F1=0.1852)
  Directional -> Accuracy: 0.4419, MCC: -0.0427, F1: 0.5200

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.29810 | val 1.89376
  Epoch 011 - train 0.29029 | val 1.55990
  Classification -> best τ=0.505 (val F1=0.2045)
  Directional -> Accuracy: 0.4694, MCC: 0.1428, F1: 0.2353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.39373 | val 1.19150
  Epoch 011 - train 0.32402 | val 1.42779
  Classification -> best τ=0.610 (val F1=0.2291)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.28990 | val 0.77662
  Epoch 012 - train 0.17816 | val 0.91399
  Classification -> best τ=0.415 (val F1=0.2097)
  Directional -> Accuracy: 0.5526, MCC: 0.0363, F1: 0.6909

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.39474 | val 0.85672
  Epoch 014 - train 0.14763 | val 1.30951
  Classification -> best τ=0.535 (val F1=0.2781)
  Directional -> Accuracy: 0.5122, MCC: 0.0238, F1: 0.5000

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.23598 | val 1.50122
  Epoch 011 - train 0.19927 | val 2.07591
  Classification -> best τ=0.580 (val F1=0.2339)
  Directional -> Accuracy: 0.5854, MCC: 0.1289, F1: 0.7213

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.30506 | val 1.72811
  Epoch 011 - train 0.25391 | val 2.14223
  Classification -> best τ=0.380 (val F1=0.3014)
  Directional -> Accuracy: 0.5208, MCC: 0.0000, F1: 0.6849

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.41240 | val 2.29029
  Epoch 011 - train 0.39070 | val 2.76670
  Classification -> best τ=0.335 (val F1=0.2673)
  Directional -> Accuracy: 0.5211, MCC: 0.1932, F1: 0.3200

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 106). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.35692 | val 0.94944
  Epoch 011 - train 0.24608 | val 1.57659
  Classification -> best τ=0.565 (val F1=0.3363)
  Directional -> Accuracy: 0.5238, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for PCG (101 < 106). Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.39897 | val 1.53838
  Epoch 011 - train 0.34321 | val 1.45804
  Classification -> best τ=0.340 (val F1=0.3218)
  Directional -> Accuracy: 0.5692, MCC: 0.0596, F1: 0.6957

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.25023 | val 1.24646
  Epoch 013 - train 0.14650 | val 2.25612
  Classification -> best τ=0.380 (val F1=0.2582)
  Directional -> Accuracy: 0.7250, MCC: 0.4506, F1: 0.7317

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.33418 | val 1.79952
  Epoch 011 - train 0.30121 | val 2.77076
  Classification -> best τ=0.405 (val F1=0.2436)
  Directional -> Accuracy: 0.5636, MCC: 0.1587, F1: 0.6000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.28712 | val 1.66576
  Epoch 012 - train 0.21068 | val 1.78357
  Classification -> best τ=0.530 (val F1=0.3283)
  Directional -> Accuracy: 0.6000, MCC: 0.1691, F1: 0.6667

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 106). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 106). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 106). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 106). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.35655 | val 0.77312
  Epoch 011 - train 0.34816 | val 0.85194
  Classification -> best τ=0.590 (val F1=0.4326)
  Directional -> Accuracy: 0.3261, MCC: 0.0000, F1: 0.4918

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 106). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 106). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 106). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.36982 | val 2.65057
  Epoch 011 - train 0.37788 | val 2.60849
  Classification -> best τ=0.285 (val F1=0.2104)
  Directional -> Accuracy: 0.4932, MCC: 0.0000, F1: 0.6606

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 106). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 106). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 106). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 106). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.34555 | val 0.72116
  Epoch 015 - train 0.12813 | val 0.92062
  Classification -> best τ=0.450 (val F1=0.4148)
  Directional -> Accuracy: 0.6364, MCC: 0.2835, F1: 0.6800

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.38572 | val 0.83610
  Epoch 012 - train 0.25109 | val 1.00120
  Classification -> best τ=0.560 (val F1=0.2467)
  Directional -> Accuracy: 0.4390, MCC: -0.0802, F1: 0.4103

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.29779 | val 0.95459
  Epoch 011 - train 0.22880 | val 1.21578
  Classification -> best τ=0.600 (val F1=0.0422)
  Directional -> Accuracy: 0.3696, MCC: 0.0000, F1: 0.5397

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.42466 | val 2.84387
  Epoch 011 - train 0.32199 | val 3.54782
  Classification -> best τ=0.625 (val F1=0.2011)
  Directional -> Accuracy: 0.4444, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.36768 | val 2.10586
  Epoch 011 - train 0.32776 | val 2.98382
  Classification -> best τ=0.695 (val F1=0.3308)
  Directional -> Accuracy: 0.5273, MCC: 0.1103, F1: 0.6579

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.42112 | val 0.76527
  Epoch 011 - train 0.36924 | val 0.77559
  Classification -> best τ=0.520 (val F1=0.2685)
  Directional -> Accuracy: 0.5769, MCC: 0.1581, F1: 0.6207

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.31873 | val 1.14983
  Epoch 012 - train 0.21624 | val 1.20992
  Classification -> best τ=0.430 (val F1=0.3006)
  Directional -> Accuracy: 0.5000, MCC: -0.0719, F1: 0.6582

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.44457 | val 1.96158
  Epoch 012 - train 0.29412 | val 1.76623

[I 2026-02-22 09:46:18,061] Trial 71 finished with value: 0.2568737786279096 and parameters: {'feature_set': 'sector_sentiment', 'model_type': 'GRU', 'sequence_length': 30, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 64, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.2, 'batch_size': 32, 'learning_rate': 0.007267102688967816, 'weight_decay': 8.946602716370514e-06, 'lr_patience': 5, 'lr_factor': 0.8, 'early_stopping_patience': 10, 'max_epochs': 50, 'huber_delta': 1.7482746252197656, 'early_stopping_min_delta': 0.008811223661671698}. Best is trial 22 with value: 0.2833350641483003.

  Classification -> best τ=0.445 (val F1=0.3465)
  Directional -> Accuracy: 0.4407, MCC: -0.1333, F1: 0.3529

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2568737786279096
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'positive_emotion', 'negative_emotion', 'uncertainty_emotion', 'positive_emotion_pct', 'negative_emotion_pct', 'uncertainty_emotion_pct']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.41155 | val 0.77698
  Epoch 016 - train 0.16528 | val 1.06216
  Classification -> best τ=0.455 (val F1=0.2082)
  Directional -> Accuracy: 0.5000, MCC: 0.0862, F1: 0.6042

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.28603 | val 1.89870
  Epoch 017 - train 0.07003 | val 4.82641
  Classification -> best τ=0.480 (val F1=0.0492)
  Directional -> Accuracy: 0.6000, MCC: 0.1419, F1: 0.7000

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.34075 | val 1.30804
  Epoch 017 - train 0.03318 | val 1.98101
  Classification -> best τ=0.550 (val F1=0.2779)
  Directional -> Accuracy: 0.4348, MCC: -0.1234, F1: 0.3158

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.40410 | val 2.81187
  Epoch 016 - train 0.17642 | val 4.63502
  Classification -> best τ=0.430 (val F1=0.1079)
  Directional -> Accuracy: 0.4595, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.29460 | val 1.03894
  Epoch 017 - train 0.03568 | val 1.63393
  Classification -> best τ=0.525 (val F1=0.4611)
  Directional -> Accuracy: 0.6600, MCC: 0.3870, F1: 0.5641

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.24260 | val 1.22767
  Epoch 016 - train 0.07637 | val 2.40506
  Classification -> best τ=0.495 (val F1=0.2593)
  Directional -> Accuracy: 0.4783, MCC: 0.0000, F1: 0.6471

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.35896 | val 1.30448
  Epoch 017 - train 0.07660 | val 2.00507
  Classification -> best τ=0.515 (val F1=0.2587)
  Directional -> Accuracy: 0.5000, MCC: 0.1215, F1: 0.5641

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.20787 | val 2.49181
  Epoch 016 - train 0.03033 | val 3.80760
  Classification -> best τ=0.465 (val F1=0.1657)
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.17017 | val 2.34557
  Epoch 016 - train 0.04298 | val 4.40487
  Classification -> best τ=0.595 (val F1=0.2443)
  Directional -> Accuracy: 0.5625, MCC: 0.2456, F1: 0.6441

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.30614 | val 2.02463
  Epoch 020 - train 0.01881 | val 2.43608
  Classification -> best τ=0.445 (val F1=0.4308)
  Directional -> Accuracy: 0.4783, MCC: -0.0139, F1: 0.4857

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.35490 | val 1.00395
  Epoch 017 - train 0.06307 | val 1.77693
  Classification -> best τ=0.465 (val F1=0.2484)
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.32442 | val 3.48598
  Epoch 016 - train 0.06131 | val 6.23542
  Classification -> best τ=0.425 (val F1=0.1944)
  Directional -> Accuracy: 0.5088, MCC: 0.0150, F1: 0.5484

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.27329 | val 3.31628
  Epoch 017 - train 0.05617 | val 7.45894
  Classification -> best τ=0.390 (val F1=0.2636)
  Directional -> Accuracy: 0.5000, MCC: 0.2032, F1: 0.6441

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.27642 | val 1.49509
  Epoch 016 - train 0.04521 | val 2.50332
  Classification -> best τ=0.475 (val F1=0.3138)
  Directional -> Accuracy: 0.5500, MCC: 0.1558, F1: 0.6747

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.24839 | val 2.96162
  Epoch 016 - train 0.03647 | val 2.45260
  Classification -> best τ=0.460 (val F1=0.2078)
  Directional -> Accuracy: 0.5490, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.40851 | val 1.79475
  Epoch 017 - train 0.11096 | val 2.55794
  Classification -> best τ=0.475 (val F1=0.3949)
  Directional -> Accuracy: 0.6087, MCC: 0.2071, F1: 0.6582

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.39166 | val 4.29206
  Epoch 016 - train 0.12316 | val 6.47741
  Classification -> best τ=0.330 (val F1=0.1336)
  Directional -> Accuracy: 0.6207, MCC: 0.0000, F1: 0.7660

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.34832 | val 1.68061
  Epoch 016 - train 0.20310 | val 1.88709
  Classification -> best τ=0.435 (val F1=0.0780)
  Directional -> Accuracy: 0.5733, MCC: 0.0279, F1: 0.6981

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.26339 | val 3.22707
  Epoch 016 - train 0.05176 | val 3.15657
  Classification -> best τ=0.485 (val F1=0.1910)
  Directional -> Accuracy: 0.4688, MCC: 0.0725, F1: 0.2609

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.37308 | val 1.06774
  Epoch 016 - train 0.13228 | val 1.97455
  Classification -> best τ=0.470 (val F1=0.2309)
  Directional -> Accuracy: 0.4595, MCC: 0.1050, F1: 0.0476

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.21474 | val 1.20993
  Epoch 017 - train 0.04778 | val 2.45587
  Classification -> best τ=0.495 (val F1=0.2784)
  Directional -> Accuracy: 0.5957, MCC: -0.0267, F1: 0.7397

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.37229 | val 1.05903
  Epoch 016 - train 0.13318 | val 1.92005
  Classification -> best τ=0.390 (val F1=0.1157)
  Directional -> Accuracy: 0.5077, MCC: 0.0000, F1: 0.6735

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.26930 | val 1.53729
  Epoch 016 - train 0.05576 | val 2.89000
  Classification -> best τ=0.645 (val F1=0.2528)
  Directional -> Accuracy: 0.5263, MCC: 0.1888, F1: 0.3415

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.46652 | val 1.39355
  Epoch 017 - train 0.18545 | val 1.06146
  Classification -> best τ=0.645 (val F1=0.2055)
  Directional -> Accuracy: 0.5231, MCC: 0.0669, F1: 0.5867

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.34786 | val 1.24750
  Epoch 016 - train 0.12365 | val 2.20980
  Classification -> best τ=0.510 (val F1=0.2970)
  Directional -> Accuracy: 0.5636, MCC: 0.2410, F1: 0.4000

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.19573 | val 2.30873
  Epoch 016 - train 0.02893 | val 3.45034
  Classification -> best τ=0.625 (val F1=0.1890)
  Directional -> Accuracy: 0.3778, MCC: -0.2204, F1: 0.3913

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.25463 | val 2.27879
  Epoch 016 - train 0.05606 | val 4.23210
  Classification -> best τ=0.515 (val F1=0.2222)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.5333

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.32304 | val 1.83567
  Epoch 016 - train 0.05987 | val 2.99367
  Classification -> best τ=0.400 (val F1=0.2149)
  Directional -> Accuracy: 0.5357, MCC: 0.2308, F1: 0.3158

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.20425 | val 6.83330
  Epoch 016 - train 0.07323 | val 8.96831
  Classification -> best τ=0.395 (val F1=0.4139)
  Directional -> Accuracy: 0.6000, MCC: 0.2010, F1: 0.7241

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.18023 | val 1.58788
  Epoch 016 - train 0.06309 | val 2.04749
  Classification -> best τ=0.615 (val F1=0.3001)
  Directional -> Accuracy: 0.5000, MCC: -0.0426, F1: 0.2222

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.25172 | val 1.89286
  Epoch 017 - train 0.03212 | val 3.51550
  Classification -> best τ=0.395 (val F1=0.2357)
  Directional -> Accuracy: 0.5476, MCC: 0.0000, F1: 0.7077

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.28973 | val 1.03841
  Epoch 018 - train 0.02790 | val 1.89354
  Classification -> best τ=0.335 (val F1=0.3541)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.38350 | val 2.45668
  Epoch 017 - train 0.07003 | val 2.22177
  Classification -> best τ=0.385 (val F1=0.3380)
  Directional -> Accuracy: 0.5694, MCC: 0.1646, F1: 0.5507

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.24060 | val 1.65786
  Epoch 016 - train 0.03504 | val 3.04145
  Classification -> best τ=0.460 (val F1=0.2717)
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.41481 | val 1.44709
  Epoch 020 - train 0.03439 | val 2.24313
  Epoch 021 - train 0.02106 | val 2.38469
  Classification -> best τ=0.385 (val F1=0.4647)
  Directional -> Accuracy: 0.5000, MCC: -0.0487, F1: 0.5926

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.18706 | val 1.39212
  Epoch 016 - train 0.01552 | val 2.32207
  Classification -> best τ=0.495 (val F1=0.3260)
  Directional -> Accuracy: 0.4524, MCC: -0.1058, F1: 0.0800

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.28242 | val 1.97771
  Epoch 016 - train 0.06702 | val 3.63418
  Classification -> best τ=0.470 (val F1=0.1593)
  Directional -> Accuracy: 0.5179, MCC: 0.0234, F1: 0.4490

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.14674 | val 4.34167
  Epoch 016 - train 0.02661 | val 5.75932
  Classification -> best τ=0.530 (val F1=0.3985)
  Directional -> Accuracy: 0.6087, MCC: 0.0000, F1: 0.7568

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.28484 | val 1.02974
  Epoch 019 - train 0.01579 | val 2.10743
  Classification -> best τ=0.485 (val F1=0.4011)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.35041 | val 1.67968
  Epoch 017 - train 0.09759 | val 2.61685
  Classification -> best τ=0.665 (val F1=0.2518)
  Directional -> Accuracy: 0.5135, MCC: 0.0515, F1: 0.6170

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.26637 | val 1.51603
  Epoch 017 - train 0.03509 | val 4.12732
  Classification -> best τ=0.430 (val F1=0.3592)
  Directional -> Accuracy: 0.5333, MCC: 0.0667, F1: 0.6441

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.21751 | val 1.42534
  Epoch 016 - train 0.04219 | val 2.34160
  Classification -> best τ=0.500 (val F1=0.1667)
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.7273

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.21758 | val 1.07564
  Epoch 020 - train 0.01851 | val 1.75365
  Classification -> best τ=0.615 (val F1=0.2681)
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.5455

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.25839 | val 1.42560
  Epoch 016 - train 0.03470 | val 2.57420
  Classification -> best τ=0.650 (val F1=0.2036)
  Directional -> Accuracy: 0.4727, MCC: 0.0585, F1: 0.1212

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.28652 | val 1.74804
  Epoch 016 - train 0.07600 | val 2.96887
  Classification -> best τ=0.550 (val F1=0.3846)
  Directional -> Accuracy: 0.5536, MCC: 0.1225, F1: 0.6032

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.23509 | val 1.74841
  Epoch 016 - train 0.07072 | val 1.94141
  Classification -> best τ=0.475 (val F1=0.2508)
  Directional -> Accuracy: 0.5472, MCC: 0.1259, F1: 0.6757

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.35920 | val 1.69599
  Epoch 016 - train 0.07946 | val 2.44022
  Classification -> best τ=0.665 (val F1=0.1605)
  Directional -> Accuracy: 0.4727, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.32824 | val 0.96230

[I 2026-02-22 09:47:11,218] Trial 72 finished with value: 0.2607506495993346 and parameters: {'feature_set': 'unified_emotion', 'model_type': 'GRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 64, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.1, 'batch_size': 32, 'learning_rate': 0.005615085598215182, 'weight_decay': 1.7483821265560873e-05, 'lr_patience': 5, 'lr_factor': 0.8, 'early_stopping_patience': 15, 'max_epochs': 50, 'huber_delta': 1.5196395919111092, 'early_stopping_min_delta': 0.008373462599591503}. Best is trial 22 with value: 0.2833350641483003.

  Epoch 019 - train 0.03894 | val 1.15559
  Classification -> best τ=0.565 (val F1=0.3128)
  Directional -> Accuracy: 0.5333, MCC: 0.0704, F1: 0.1765

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2607506495993346
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: classification
Sequence length: 30
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d', 'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down', 'finbert_neutral']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.37856 | val 1.21779
  Epoch 011 - train 0.29678 | val 1.32272
  Classification -> best τ=0.465 (val F1=0.0804)
  Directional -> Accuracy: 0.6267, MCC: 0.2509, F1: 0.6000

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 106). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.21186 | val 1.20867
  Epoch 011 - train 0.18784 | val 1.66030
  Classification -> best τ=0.520 (val F1=0.2503)
  Directional -> Accuracy: 0.5000, MCC: -0.0169, F1: 0.5600

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 106). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.16525 | val 2.75129
  Epoch 011 - train 0.11529 | val 4.34286
  Classification -> best τ=0.570 (val F1=0.2294)
  Directional -> Accuracy: 0.4889, MCC: 0.0714, F1: 0.1481

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.42851 | val 2.02623
  Epoch 011 - train 0.36412 | val 2.49473
  Classification -> best τ=0.420 (val F1=0.2576)
  Directional -> Accuracy: 0.4658, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.25818 | val 0.81717
  Epoch 012 - train 0.12597 | val 1.11739
  Classification -> best τ=0.570 (val F1=0.3933)
  Directional -> Accuracy: 0.4898, MCC: -0.0076, F1: 0.1935

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.14335 | val 4.75122
  Epoch 011 - train 0.10771 | val 5.01335
  Classification -> best τ=0.595 (val F1=0.2294)
  Directional -> Accuracy: 0.5111, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.34329 | val 1.37197
  Epoch 012 - train 0.19686 | val 1.89556
  Classification -> best τ=0.405 (val F1=0.1868)
  Directional -> Accuracy: 0.4478, MCC: 0.0033, F1: 0.5316

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 106). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 106). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.24875 | val 1.09564
  Epoch 014 - train 0.07998 | val 1.30391
  Classification -> best τ=0.450 (val F1=0.0529)
  Directional -> Accuracy: 0.4390, MCC: -0.0605, F1: 0.5490

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.18359 | val 1.65838
  Epoch 013 - train 0.05555 | val 2.31576
  Classification -> best τ=0.505 (val F1=0.2895)
  Directional -> Accuracy: 0.5106, MCC: -0.1895, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 106). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 106). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 106). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.28290 | val 1.86718
  Epoch 011 - train 0.21145 | val 2.95394
  Classification -> best τ=0.360 (val F1=0.1255)
  Directional -> Accuracy: 0.4853, MCC: 0.0456, F1: 0.5570

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.29434 | val 2.16766
  Epoch 012 - train 0.19937 | val 2.00195
  Classification -> best τ=0.845 (val F1=0.3333)
  Directional -> Accuracy: 0.5417, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.29149 | val 2.90410
  Epoch 011 - train 0.29220 | val 2.21078
  Classification -> best τ=0.485 (val F1=0.0274)
  Directional -> Accuracy: 0.6429, MCC: 0.2956, F1: 0.7059

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 106). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.21711 | val 3.27695
  Epoch 011 - train 0.13291 | val 3.59326
  Classification -> best τ=0.445 (val F1=0.2112)
  Directional -> Accuracy: 0.5102, MCC: 0.0061, F1: 0.1429

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 106). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.28488 | val 0.92563
  Epoch 011 - train 0.25276 | val 0.84012
  Classification -> best τ=0.450 (val F1=0.3428)
  Directional -> Accuracy: 0.5593, MCC: 0.1422, F1: 0.4348

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.20787 | val 1.34116
  Epoch 011 - train 0.20275 | val 1.67848
  Classification -> best τ=0.525 (val F1=0.2060)
  Directional -> Accuracy: 0.5600, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.30991 | val 1.68982
  Epoch 011 - train 0.35194 | val 1.90184
  Classification -> best τ=0.540 (val F1=0.3346)
  Directional -> Accuracy: 0.6324, MCC: 0.2800, F1: 0.7191

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 106). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.31030 | val 2.32354
  Epoch 011 - train 0.25137 | val 2.43934
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.6140, MCC: 0.0000, F1: 0.7609

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.31317 | val 2.56731
  Epoch 011 - train 0.25919 | val 3.29606
  Classification -> best τ=0.540 (val F1=0.1895)
  Directional -> Accuracy: 0.4054, MCC: -0.1253, F1: 0.3333

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.35296 | val 1.63144
  Epoch 011 - train 0.28270 | val 1.83233
  Classification -> best τ=0.400 (val F1=0.1741)
  Directional -> Accuracy: 0.5238, MCC: 0.0868, F1: 0.5161

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 106). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.40573 | val 0.96213
  Epoch 011 - train 0.32245 | val 0.97816
  Classification -> best τ=0.530 (val F1=0.3105)
  Directional -> Accuracy: 0.4521, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.20950 | val 1.74390
  Epoch 011 - train 0.14852 | val 2.15512
  Classification -> best τ=0.460 (val F1=0.0961)
  Directional -> Accuracy: 0.3913, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 106). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 106). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 106). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.26649 | val 1.69810
  Epoch 011 - train 0.19887 | val 2.34727
  Classification -> best τ=0.450 (val F1=0.2582)
  Directional -> Accuracy: 0.5625, MCC: 0.1443, F1: 0.4167

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.39805 | val 2.83670
  Epoch 011 - train 0.33405 | val 2.20833
  Classification -> best τ=0.835 (val F1=0.3131)
  Directional -> Accuracy: 0.5179, MCC: 0.2182, F1: 0.3077

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.31552 | val 1.29672
  Epoch 011 - train 0.24833 | val 2.72743
  Classification -> best τ=0.435 (val F1=0.1912)
  Directional -> Accuracy: 0.6250, MCC: 0.2425, F1: 0.5556

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.29432 | val 2.37357
  Epoch 014 - train 0.07011 | val 3.18193
  Classification -> best τ=0.785 (val F1=0.3078)
  Directional -> Accuracy: 0.4630, MCC: 0.0000, F1: 0.0000

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.19269 | val 2.57901
  Epoch 012 - train 0.15104 | val 2.06266
  Classification -> best τ=0.485 (val F1=0.2160)
  Directional -> Accuracy: 0.4186, MCC: 0.0000, F1: 0.5902

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.21256 | val 1.29931
  Epoch 011 - train 0.16274 | val 1.49449
  Classification -> best τ=0.640 (val F1=0.2044)
  Directional -> Accuracy: 0.4286, MCC: 0.1199, F1: 0.0667

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.30245 | val 1.57470
  Epoch 011 - train 0.25034 | val 1.69472
  Classification -> best τ=0.630 (val F1=0.2291)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.22680 | val 1.51111
  Epoch 012 - train 0.15530 | val 2.57788
  Classification -> best τ=0.600 (val F1=0.4441)
  Directional -> Accuracy: 0.5789, MCC: 0.1259, F1: 0.6667

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.21145 | val 1.56883
  Epoch 012 - train 0.14678 | val 1.29644
  Classification -> best τ=0.555 (val F1=0.2025)
  Directional -> Accuracy: 0.5122, MCC: 0.0263, F1: 0.5238

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.12384 | val 2.91630
  Epoch 011 - train 0.07502 | val 3.07716
  Classification -> best τ=0.635 (val F1=0.1336)
  Directional -> Accuracy: 0.5610, MCC: 0.0000, F1: 0.7188

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.26676 | val 1.49784
  Epoch 011 - train 0.22137 | val 1.66224
  Classification -> best τ=0.470 (val F1=0.2739)
  Directional -> Accuracy: 0.5208, MCC: 0.0000, F1: 0.6849

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.30724 | val 1.43958
  Epoch 012 - train 0.26016 | val 2.10676
  Classification -> best τ=0.300 (val F1=0.2748)
  Directional -> Accuracy: 0.5634, MCC: 0.0000, F1: 0.7207

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 106). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.24100 | val 1.26960
  Epoch 011 - train 0.21504 | val 1.51769
  Classification -> best τ=0.430 (val F1=0.3367)
  Directional -> Accuracy: 0.6190, MCC: 0.2919, F1: 0.3846

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for PCG (101 < 106). Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.37494 | val 1.80940
  Epoch 012 - train 0.30313 | val 2.15945
  Classification -> best τ=0.345 (val F1=0.2936)
  Directional -> Accuracy: 0.5538, MCC: 0.1024, F1: 0.5915

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.16573 | val 1.61068
  Epoch 011 - train 0.15545 | val 1.80997
  Classification -> best τ=0.525 (val F1=0.4384)
  Directional -> Accuracy: 0.6000, MCC: 0.2197, F1: 0.5556

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.28660 | val 3.12145
  Epoch 011 - train 0.29216 | val 3.34400
  Classification -> best τ=0.375 (val F1=0.2895)
  Directional -> Accuracy: 0.5636, MCC: 0.1587, F1: 0.6000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.21533 | val 2.24909
  Epoch 011 - train 0.17684 | val 2.35381
  Classification -> best τ=0.540 (val F1=0.4547)
  Directional -> Accuracy: 0.5778, MCC: 0.0245, F1: 0.6984

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 106). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 106). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 106). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 106). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.30761 | val 1.13305
  Epoch 013 - train 0.25603 | val 0.90880
  Classification -> best τ=0.585 (val F1=0.5017)
  Directional -> Accuracy: 0.3696, MCC: -0.0479, F1: 0.4528

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 106). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 106). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 106). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.34526 | val 2.57431
  Epoch 011 - train 0.30165 | val 3.08962
  Classification -> best τ=0.600 (val F1=0.1664)
  Directional -> Accuracy: 0.5068, MCC: 0.0067, F1: 0.2800

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 106). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 106). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 106). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 106). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.20042 | val 1.85953
  Epoch 015 - train 0.02802 | val 2.61156
  Classification -> best τ=0.535 (val F1=0.4330)
  Directional -> Accuracy: 0.6591, MCC: 0.3185, F1: 0.6512

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.32153 | val 1.10409
  Epoch 012 - train 0.19896 | val 1.47899
  Classification -> best τ=0.435 (val F1=0.2000)
  Directional -> Accuracy: 0.5366, MCC: 0.0872, F1: 0.5581

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.22518 | val 0.90830
  Epoch 012 - train 0.13837 | val 1.20298
  Classification -> best τ=0.540 (val F1=0.2392)
  Directional -> Accuracy: 0.3696, MCC: 0.0000, F1: 0.5397

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.37179 | val 1.27832
  Epoch 011 - train 0.28241 | val 1.92458
  Classification -> best τ=0.490 (val F1=0.2697)
  Directional -> Accuracy: 0.4444, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.29670 | val 2.05228
  Epoch 012 - train 0.16635 | val 2.40157
  Classification -> best τ=0.540 (val F1=0.3760)
  Directional -> Accuracy: 0.5273, MCC: 0.0594, F1: 0.5667

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.37810 | val 1.19824
  Epoch 013 - train 0.17121 | val 1.74675
  Classification -> best τ=0.630 (val F1=0.2376)
  Directional -> Accuracy: 0.5385, MCC: 0.0772, F1: 0.5556

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.33374 | val 1.13106
  Epoch 011 - train 0.23304 | val 0.85614
  Classification -> best τ=0.360 (val F1=0.1890)
  Directional -> Accuracy: 0.4815, MCC: -0.0240, F1: 0.3636

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.38768 | val 1.12743

[I 2026-02-22 09:47:54,781] Trial 73 finished with value: 0.251266037931033 and parameters: {'feature_set': 'sector_finbert', 'model_type': 'GRU', 'sequence_length': 30, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 64, 'num_layers': 1, 'inter_rnn_drop': 0.1, 'dropout': 0.2, 'batch_size': 32, 'learning_rate': 0.007895692764618418, 'weight_decay': 4.914390135394873e-06, 'lr_patience': 5, 'lr_factor': 0.8, 'early_stopping_patience': 10, 'max_epochs': 50, 'huber_delta': 1.8278589394966724, 'early_stopping_min_delta': 0.007436895547157813}. Best is trial 22 with value: 0.2833350641483003.

  Epoch 013 - train 0.19141 | val 1.44454
  Classification -> best τ=0.430 (val F1=0.2658)
  Directional -> Accuracy: 0.4746, MCC: 0.0000, F1: 0.6437

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.251266037931033
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sentiment', 'emotion_anger', 'emotion_disgust', 'emotion_fear', 'emotion_joy', 'emotion_neutral', 'emotion_sadness', 'emotion_surprize', 'emotion_anger_pct', 'emotion_disgust_pct', 'emotion_fear_pct', 'emotion_joy_pct', 'emotion_neutral_pct', 'emotion_sadness_pct', 'emotion_surprize_pct', 'positive_emotion', 'negative_emotion', 'uncertainty_emotion', 'positive_emotion_pct', 'negative_emotion_pct', 'uncertainty_emotion_pct', 'stance_label', 'stance_score', 'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down', 'finbert_neutral']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.08364 | val 2.37607
  Epoch 020 - train 0.00270 | val 3.76519
  Epoch 021 - train 0.00244 | val 3.81784
  Classification -> best τ=0.610 (val F1=0.2039)
  Directional -> Accuracy: 0.5395, MCC: -0.0022, F1: 0.1860

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.08430 | val 2.91067
  Epoch 020 - train 0.00374 | val 4.43246
  Epoch 021 - train 0.00338 | val 4.48766
  Classification -> best τ=0.310 (val F1=0.1844)
  Directional -> Accuracy: 0.5778, MCC: 0.0000, F1: 0.7324

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.06420 | val 1.22485
  Epoch 020 - train 0.00196 | val 1.33931
  Epoch 023 - train 0.00152 | val 1.37594
  Classification -> best τ=0.625 (val F1=0.3882)
  Directional -> Accuracy: 0.4783, MCC: -0.0134, F1: 0.1429

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.14195 | val 2.83026
  Epoch 020 - train 0.00305 | val 5.49550
  Epoch 021 - train 0.00271 | val 5.61441
  Classification -> best τ=0.360 (val F1=0.1895)
  Directional -> Accuracy: 0.4595, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.03876 | val 1.12629
  Epoch 020 - train 0.00194 | val 1.56070
  Epoch 023 - train 0.00154 | val 1.60117
  Classification -> best τ=0.565 (val F1=0.4139)
  Directional -> Accuracy: 0.6200, MCC: 0.2498, F1: 0.5957

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.09427 | val 0.92019
  Epoch 020 - train 0.00478 | val 1.47209
  Epoch 021 - train 0.00421 | val 1.49162
  Classification -> best τ=0.570 (val F1=0.2058)
  Directional -> Accuracy: 0.5217, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.07678 | val 1.77539
  Epoch 020 - train 0.00293 | val 2.40183
  Epoch 021 - train 0.00263 | val 2.42772
  Classification -> best τ=0.520 (val F1=0.2664)
  Directional -> Accuracy: 0.5588, MCC: 0.1141, F1: 0.5000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.04193 | val 2.73803
  Epoch 020 - train 0.00259 | val 4.04711
  Epoch 021 - train 0.00239 | val 4.06939
  Classification -> best τ=0.465 (val F1=0.3158)
  Directional -> Accuracy: 0.5476, MCC: 0.0962, F1: 0.5128

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.04228 | val 1.83679
  Epoch 020 - train 0.00201 | val 2.51080
  Epoch 021 - train 0.00185 | val 2.52955
  Classification -> best τ=0.580 (val F1=0.2822)
  Directional -> Accuracy: 0.5625, MCC: 0.0563, F1: 0.2759

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.06953 | val 1.52161
  Epoch 020 - train 0.00242 | val 2.75230
  Epoch 021 - train 0.00219 | val 2.77584
  Classification -> best τ=0.365 (val F1=0.3007)
  Directional -> Accuracy: 0.3768, MCC: -0.2504, F1: 0.5474

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.05594 | val 2.44656
  Epoch 020 - train 0.00262 | val 3.44329
  Epoch 022 - train 0.00217 | val 3.50498
  Classification -> best τ=0.570 (val F1=0.2484)
  Directional -> Accuracy: 0.6327, MCC: 0.3303, F1: 0.3077

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.09396 | val 3.52141
  Epoch 020 - train 0.00662 | val 5.14636
  Epoch 021 - train 0.00615 | val 5.18330
  Classification -> best τ=0.490 (val F1=0.1963)
  Directional -> Accuracy: 0.5088, MCC: 0.0323, F1: 0.3333

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.04576 | val 2.64431
  Epoch 020 - train 0.00205 | val 3.47386
  Epoch 021 - train 0.00183 | val 3.48852
  Classification -> best τ=0.370 (val F1=0.1754)
  Directional -> Accuracy: 0.4286, MCC: -0.1090, F1: 0.5714

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.05125 | val 2.43347
  Epoch 020 - train 0.00218 | val 3.25415
  Epoch 021 - train 0.00201 | val 3.29039
  Classification -> best τ=0.475 (val F1=0.3141)
  Directional -> Accuracy: 0.5333, MCC: 0.0673, F1: 0.5625

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.08468 | val 1.88683
  Epoch 020 - train 0.00378 | val 3.08530
  Epoch 022 - train 0.00297 | val 3.17015
  Classification -> best τ=0.555 (val F1=0.1455)
  Directional -> Accuracy: 0.5490, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.12021 | val 1.64076
  Epoch 020 - train 0.00980 | val 2.24303
  Epoch 021 - train 0.00529 | val 2.06683
  Classification -> best τ=0.480 (val F1=0.2659)
  Directional -> Accuracy: 0.5652, MCC: 0.1858, F1: 0.7115

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.06928 | val 4.23753
  Epoch 020 - train 0.00234 | val 5.61562
  Epoch 021 - train 0.00210 | val 5.68342
  Classification -> best τ=0.665 (val F1=0.0319)
  Directional -> Accuracy: 0.3966, MCC: 0.0221, F1: 0.1026

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.09503 | val 2.60565
  Epoch 020 - train 0.00309 | val 3.74765
  Epoch 021 - train 0.00278 | val 3.80471
  Classification -> best τ=0.510 (val F1=0.2500)
  Directional -> Accuracy: 0.4000, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.03347 | val 2.29524
  Epoch 020 - train 0.00167 | val 3.25444
  Epoch 021 - train 0.00152 | val 3.28519
  Classification -> best τ=0.285 (val F1=0.2166)
  Directional -> Accuracy: 0.5625, MCC: 0.0855, F1: 0.6410

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.10293 | val 1.33641
  Epoch 020 - train 0.00291 | val 1.68940
  Epoch 021 - train 0.00256 | val 1.70980
  Classification -> best τ=0.475 (val F1=0.2169)
  Directional -> Accuracy: 0.5541, MCC: 0.2070, F1: 0.4211

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.05242 | val 1.57456
  Epoch 020 - train 0.00293 | val 2.50847
  Epoch 021 - train 0.00263 | val 2.53410
  Classification -> best τ=0.470 (val F1=0.3159)
  Directional -> Accuracy: 0.4894, MCC: -0.0805, F1: 0.5862

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.06759 | val 2.04351
  Epoch 020 - train 0.00299 | val 2.83008
  Epoch 021 - train 0.00272 | val 2.86004
  Classification -> best τ=0.355 (val F1=0.1514)
  Directional -> Accuracy: 0.5385, MCC: 0.1320, F1: 0.6809

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.09603 | val 1.47200
  Epoch 020 - train 0.00428 | val 2.08267
  Epoch 021 - train 0.00386 | val 2.10417
  Classification -> best τ=0.470 (val F1=0.3217)
  Directional -> Accuracy: 0.5088, MCC: -0.1153, F1: 0.6585

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.10941 | val 1.58821
  Epoch 020 - train 0.00301 | val 1.98385
  Epoch 021 - train 0.00273 | val 2.00830
  Classification -> best τ=0.525 (val F1=0.1393)
  Directional -> Accuracy: 0.5538, MCC: 0.1046, F1: 0.5246

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.07661 | val 1.60957
  Epoch 020 - train 0.00256 | val 2.43101
  Epoch 021 - train 0.00231 | val 2.45572
  Classification -> best τ=0.525 (val F1=0.2747)
  Directional -> Accuracy: 0.5636, MCC: 0.2170, F1: 0.4286

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.07097 | val 1.98826
  Epoch 020 - train 0.00361 | val 3.24848
  Epoch 021 - train 0.00321 | val 3.29031
  Classification -> best τ=0.480 (val F1=0.2035)
  Directional -> Accuracy: 0.4444, MCC: 0.1289, F1: 0.6032

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.02033 | val 1.73920
  Epoch 020 - train 0.00176 | val 2.34921
  Epoch 021 - train 0.00163 | val 2.36471
  Classification -> best τ=0.500 (val F1=0.2582)
  Directional -> Accuracy: 0.4762, MCC: 0.0000, F1: 0.4211

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.06378 | val 1.76405
  Epoch 020 - train 0.00305 | val 2.50818
  Epoch 021 - train 0.00277 | val 2.53384
  Classification -> best τ=0.525 (val F1=0.0804)
  Directional -> Accuracy: 0.4286, MCC: -0.1502, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.06693 | val 2.45528
  Epoch 020 - train 0.00306 | val 4.15879
  Epoch 021 - train 0.00276 | val 4.20492
  Classification -> best τ=0.475 (val F1=0.0707)
  Directional -> Accuracy: 0.6250, MCC: 0.2307, F1: 0.6939

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.05468 | val 3.02010
  Epoch 020 - train 0.00228 | val 3.33916
  Epoch 021 - train 0.00209 | val 3.35310
  Classification -> best τ=0.660 (val F1=0.3501)
  Directional -> Accuracy: 0.5476, MCC: 0.1638, F1: 0.0952

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.07351 | val 1.22782
  Epoch 020 - train 0.00292 | val 2.01602
  Epoch 021 - train 0.00265 | val 2.03703
  Classification -> best τ=0.555 (val F1=0.1846)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.04807 | val 1.64985
  Epoch 020 - train 0.00191 | val 2.32026
  Epoch 023 - train 0.00145 | val 2.38172
  Classification -> best τ=0.395 (val F1=0.3005)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.09842 | val 1.04297
  Epoch 020 - train 0.00266 | val 1.64083
  Epoch 021 - train 0.00237 | val 1.66170
  Classification -> best τ=0.385 (val F1=0.3815)
  Directional -> Accuracy: 0.5556, MCC: 0.1402, F1: 0.5294

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.03941 | val 2.99521
  Epoch 020 - train 0.00199 | val 3.99468
  Epoch 021 - train 0.00180 | val 4.02526
  Classification -> best τ=0.340 (val F1=0.1874)
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.13170 | val 1.36004
  Epoch 020 - train 0.00391 | val 2.24074
  Epoch 021 - train 0.00347 | val 2.26998
  Classification -> best τ=0.335 (val F1=0.3342)
  Directional -> Accuracy: 0.5455, MCC: 0.0152, F1: 0.6591

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.02989 | val 1.42888
  Epoch 020 - train 0.00204 | val 2.25979
  Epoch 022 - train 0.00169 | val 2.30466
  Classification -> best τ=0.425 (val F1=0.5203)
  Directional -> Accuracy: 0.6905, MCC: 0.3977, F1: 0.6667

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.05605 | val 1.77986
  Epoch 020 - train 0.00223 | val 2.27314
  Epoch 021 - train 0.00201 | val 2.29292
  Classification -> best τ=0.485 (val F1=0.2450)
  Directional -> Accuracy: 0.5000, MCC: 0.0103, F1: 0.5172

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.04594 | val 3.45311
  Epoch 020 - train 0.00232 | val 5.15948
  Epoch 022 - train 0.00197 | val 5.23984
  Classification -> best τ=0.605 (val F1=0.2975)
  Directional -> Accuracy: 0.3696, MCC: -0.1771, F1: 0.2564

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.05436 | val 1.33904
  Epoch 020 - train 0.00262 | val 1.97507
  Epoch 021 - train 0.00229 | val 2.00761
  Classification -> best τ=0.545 (val F1=0.1623)
  Directional -> Accuracy: 0.4167, MCC: 0.1099, F1: 0.5333

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.11740 | val 2.86620
  Epoch 020 - train 0.00317 | val 4.50891
  Epoch 021 - train 0.00282 | val 4.56167
  Classification -> best τ=0.370 (val F1=0.1602)
  Directional -> Accuracy: 0.4865, MCC: 0.0000, F1: 0.6545

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.04898 | val 2.12450
  Epoch 020 - train 0.00188 | val 3.75861
  Epoch 021 - train 0.00170 | val 3.79037
  Classification -> best τ=0.480 (val F1=0.1942)
  Directional -> Accuracy: 0.5111, MCC: 0.0260, F1: 0.4762

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.08279 | val 1.31503
  Epoch 020 - train 0.00397 | val 2.08558
  Epoch 021 - train 0.00357 | val 2.11308
  Classification -> best τ=0.455 (val F1=0.1667)
  Directional -> Accuracy: 0.5952, MCC: 0.1273, F1: 0.7213

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.10634 | val 1.47992
  Epoch 020 - train 0.00329 | val 2.16679
  Epoch 022 - train 0.00253 | val 2.22075
  Classification -> best τ=0.660 (val F1=0.1371)
  Directional -> Accuracy: 0.3542, MCC: -0.1883, F1: 0.5231

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.05680 | val 1.70504
  Epoch 020 - train 0.00237 | val 2.69574
  Epoch 021 - train 0.00218 | val 2.72220
  Classification -> best τ=0.555 (val F1=0.2452)
  Directional -> Accuracy: 0.4364, MCC: -0.1491, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.04806 | val 1.76152
  Epoch 020 - train 0.00238 | val 2.89955
  Epoch 021 - train 0.00217 | val 2.93092
  Classification -> best τ=0.585 (val F1=0.3318)
  Directional -> Accuracy: 0.5893, MCC: 0.2147, F1: 0.6567

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.06682 | val 2.09931
  Epoch 020 - train 0.00226 | val 2.77474
  Epoch 021 - train 0.00208 | val 2.80527

[I 2026-02-22 09:48:59,274] Trial 74 finished with value: 0.23396224888808667 and parameters: {'feature_set': 'all_nlp', 'model_type': 'GRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 64, 'num_layers': 1, 'inter_rnn_drop': 0.4, 'dropout': 0.0, 'batch_size': 32, 'learning_rate': 0.0036765494177113884, 'weight_decay': 1.6555368606921112e-06, 'lr_patience': 5, 'lr_factor': 0.8, 'early_stopping_patience': 20, 'max_epochs': 50, 'huber_delta': 1.3077565893743137, 'early_stopping_min_delta': 0.008158428438688445}. Best is trial 22 with value: 0.2833350641483003.

  Classification -> best τ=0.595 (val F1=0.1489)
  Directional -> Accuracy: 0.5333, MCC: 0.0842, F1: 0.1250

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.23396224888808667
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 12
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.47272 | val 1.89461
  Epoch 012 - train 0.40713 | val 2.13209
  Classification -> best τ=0.710 (val F1=0.2463)
  Directional -> Accuracy: 0.5769, MCC: 0.1196, F1: 0.4000

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 88). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.29416 | val 2.06397
  Epoch 011 - train 0.25452 | val 1.58828
  Classification -> best τ=0.520 (val F1=0.1641)
  Directional -> Accuracy: 0.5532, MCC: 0.1093, F1: 0.5714

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 88). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.35462 | val 1.97244
  Epoch 011 - train 0.37004 | val 1.62670
  Classification -> best τ=0.565 (val F1=0.1358)
  Directional -> Accuracy: 0.4583, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.47177 | val 1.54324
  Epoch 012 - train 0.43753 | val 2.67545
  Classification -> best τ=0.340 (val F1=0.3086)
  Directional -> Accuracy: 0.5263, MCC: 0.0152, F1: 0.6327

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.37130 | val 1.17142
  Epoch 013 - train 0.24826 | val 1.42858
  Classification -> best τ=0.550 (val F1=0.3445)
  Directional -> Accuracy: 0.6538, MCC: 0.3243, F1: 0.6400

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.33314 | val 1.54336
  Epoch 012 - train 0.29020 | val 1.06020
  Classification -> best τ=0.585 (val F1=0.2778)
  Directional -> Accuracy: 0.4898, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.44907 | val 1.83272
  Epoch 011 - train 0.35932 | val 1.40179
  Classification -> best τ=0.510 (val F1=0.0728)
  Directional -> Accuracy: 0.5143, MCC: 0.0350, F1: 0.4688

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 88). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 88). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.23117 | val 2.43001
  Epoch 011 - train 0.19558 | val 1.85412
  Classification -> best τ=0.625 (val F1=0.3280)
  Directional -> Accuracy: 0.5333, MCC: 0.0931, F1: 0.5333

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.35611 | val 1.25204
  Epoch 011 - train 0.28716 | val 1.96056
  Classification -> best τ=0.545 (val F1=0.3303)
  Directional -> Accuracy: 0.4048, MCC: 0.0272, F1: 0.5455

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 88). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 88). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.38039 | val 2.96451
  Epoch 011 - train 0.33362 | val 2.74071
  Classification -> best τ=0.365 (val F1=0.1283)
  Directional -> Accuracy: 0.4366, MCC: 0.0000, F1: 0.6078

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.33053 | val 1.38404
  Epoch 011 - train 0.29375 | val 2.59496
  Classification -> best τ=0.645 (val F1=0.2622)
  Directional -> Accuracy: 0.6078, MCC: 0.2654, F1: 0.3333

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.37153 | val 1.69975
  Epoch 011 - train 0.36694 | val 1.46405
  Classification -> best τ=0.445 (val F1=0.1931)
  Directional -> Accuracy: 0.5085, MCC: 0.0000, F1: 0.6742

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.27756 | val 2.79415
  Epoch 011 - train 0.22780 | val 3.61846
  Classification -> best τ=0.515 (val F1=0.2146)
  Directional -> Accuracy: 0.5455, MCC: 0.0000, F1: 0.0000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 88). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.34410 | val 1.23097
  Epoch 012 - train 0.30541 | val 1.35635
  Classification -> best τ=0.325 (val F1=0.3520)
  Directional -> Accuracy: 0.5323, MCC: 0.0711, F1: 0.4082

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.35317 | val 6.09315
  Epoch 011 - train 0.31769 | val 5.45863
  Classification -> best τ=0.705 (val F1=0.2358)
  Directional -> Accuracy: 0.5472, MCC: 0.1468, F1: 0.0769

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.37229 | val 1.00122
  Epoch 011 - train 0.35402 | val 1.26857
  Classification -> best τ=0.485 (val F1=0.2229)
  Directional -> Accuracy: 0.5775, MCC: 0.1654, F1: 0.7059

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.42558 | val 2.06230
  Epoch 011 - train 0.35705 | val 2.55867
  Classification -> best τ=0.600 (val F1=0.1753)
  Directional -> Accuracy: 0.3833, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.41956 | val 3.33357
  Epoch 011 - train 0.38460 | val 3.04755
  Classification -> best τ=0.360 (val F1=0.1193)
  Directional -> Accuracy: 0.6104, MCC: 0.0000, F1: 0.7581

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.44390 | val 1.62072
  Epoch 012 - train 0.36595 | val 1.97587
  Classification -> best τ=0.355 (val F1=0.2999)
  Directional -> Accuracy: 0.6061, MCC: 0.1852, F1: 0.6667

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 88). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.42782 | val 1.82781
  Epoch 012 - train 0.40383 | val 1.47164
  Classification -> best τ=0.520 (val F1=0.2318)
  Directional -> Accuracy: 0.5000, MCC: 0.1117, F1: 0.2083

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.29083 | val 1.66098
  Epoch 011 - train 0.27619 | val 2.15507
  Classification -> best τ=0.440 (val F1=0.3170)
  Directional -> Accuracy: 0.4694, MCC: 0.2569, F1: 0.2778

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 88). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 88). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 88). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.40352 | val 1.60643
  Epoch 011 - train 0.36340 | val 1.27674
  Classification -> best τ=0.620 (val F1=0.2264)
  Directional -> Accuracy: 0.4925, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.41483 | val 1.19035
  Epoch 013 - train 0.34798 | val 1.44728
  Classification -> best τ=0.790 (val F1=0.3607)
  Directional -> Accuracy: 0.4068, MCC: -0.1531, F1: 0.0000

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.38457 | val 1.56375
  Epoch 011 - train 0.36951 | val 1.70602
  Classification -> best τ=0.380 (val F1=0.2518)
  Directional -> Accuracy: 0.4776, MCC: 0.0000, F1: 0.6465

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.36336 | val 1.25803
  Epoch 012 - train 0.26240 | val 1.35291
  Classification -> best τ=0.470 (val F1=0.4805)
  Directional -> Accuracy: 0.6140, MCC: 0.2416, F1: 0.6207

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.28132 | val 2.96764
  Epoch 011 - train 0.30297 | val 3.41894
  Classification -> best τ=0.475 (val F1=0.2287)
  Directional -> Accuracy: 0.4583, MCC: -0.2646, F1: 0.0714

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.35395 | val 2.11832
  Epoch 011 - train 0.31825 | val 1.95180
  Classification -> best τ=0.485 (val F1=0.1394)
  Directional -> Accuracy: 0.5909, MCC: 0.0000, F1: 0.7429

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.39920 | val 1.25532
  Epoch 011 - train 0.36209 | val 1.32492
  Classification -> best τ=0.545 (val F1=0.1753)
  Directional -> Accuracy: 0.4655, MCC: 0.0540, F1: 0.1143

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.27388 | val 1.76725
  Epoch 016 - train 0.14109 | val 1.99669
  Classification -> best τ=0.545 (val F1=0.3344)
  Directional -> Accuracy: 0.4419, MCC: -0.1001, F1: 0.3684

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.32800 | val 0.90092
  Epoch 011 - train 0.29574 | val 1.12241
  Classification -> best τ=0.465 (val F1=0.2697)
  Directional -> Accuracy: 0.4889, MCC: -0.0518, F1: 0.6230

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.34713 | val 2.15312
  Epoch 011 - train 0.28754 | val 2.27222
  Classification -> best τ=0.450 (val F1=0.2132)
  Directional -> Accuracy: 0.5333, MCC: 0.0000, F1: 0.6957

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.36479 | val 0.86374
  Epoch 011 - train 0.25952 | val 0.76259
  Classification -> best τ=0.425 (val F1=0.2793)
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.39947 | val 2.68805
  Epoch 011 - train 0.36361 | val 2.22713
  Classification -> best τ=0.510 (val F1=0.2748)
  Directional -> Accuracy: 0.4324, MCC: 0.0000, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 88). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.28173 | val 0.74439
  Epoch 011 - train 0.26448 | val 0.77726
  Classification -> best τ=0.465 (val F1=0.3223)
  Directional -> Accuracy: 0.5385, MCC: 0.0792, F1: 0.5500

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.33413 | val 1.45664
  Epoch 011 - train 0.29592 | val 1.62074
  Classification -> best τ=0.500 (val F1=0.0238)
  Directional -> Accuracy: 0.4667, MCC: -0.0714, F1: 0.4286

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.40907 | val 1.12098
  Epoch 011 - train 0.40611 | val 1.33954
  Classification -> best τ=0.410 (val F1=0.3463)
  Directional -> Accuracy: 0.4559, MCC: 0.0892, F1: 0.1395

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.27009 | val 1.03060
  Epoch 014 - train 0.12058 | val 1.27172
  Classification -> best τ=0.475 (val F1=0.3430)
  Directional -> Accuracy: 0.5682, MCC: 0.1575, F1: 0.6545

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.34050 | val 3.23538
  Epoch 011 - train 0.30052 | val 4.42847
  Classification -> best τ=0.465 (val F1=0.1687)
  Directional -> Accuracy: 0.4655, MCC: -0.0502, F1: 0.5231

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.27151 | val 1.29006
  Epoch 011 - train 0.24025 | val 1.54704
  Classification -> best τ=0.500 (val F1=0.2441)
  Directional -> Accuracy: 0.6458, MCC: 0.1883, F1: 0.7792

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 88). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 88). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 88). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 88). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.32733 | val 1.30402
  Epoch 011 - train 0.31056 | val 1.47242
  Classification -> best τ=0.480 (val F1=0.0667)
  Directional -> Accuracy: 0.3500, MCC: -0.1321, F1: 0.4583

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 88). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.34462 | val 1.25751
  Epoch 011 - train 0.30285 | val 1.50235
  Classification -> best τ=0.520 (val F1=0.3780)
  Directional -> Accuracy: 0.4872, MCC: 0.0088, F1: 0.3750

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 88). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 88). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.37942 | val 3.30744
  Epoch 011 - train 0.35636 | val 3.23305
  Classification -> best τ=0.390 (val F1=0.2905)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.5957

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 88). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 88). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 88). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.29995 | val 1.61867
  Epoch 011 - train 0.25347 | val 1.97318
  Classification -> best τ=0.470 (val F1=0.3693)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.27559 | val 1.52765
  Epoch 011 - train 0.23888 | val 1.74577
  Classification -> best τ=0.540 (val F1=0.4000)
  Directional -> Accuracy: 0.5111, MCC: 0.1371, F1: 0.3125

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.27930 | val 1.26272
  Epoch 011 - train 0.21995 | val 1.23749
  Classification -> best τ=0.465 (val F1=0.2037)
  Directional -> Accuracy: 0.3659, MCC: 0.0000, F1: 0.5357

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.38883 | val 2.37963
  Epoch 011 - train 0.31985 | val 2.39727
  Classification -> best τ=0.325 (val F1=0.2405)
  Directional -> Accuracy: 0.5965, MCC: 0.2574, F1: 0.7294

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.29219 | val 2.79741
  Epoch 012 - train 0.23045 | val 3.22617
  Classification -> best τ=0.555 (val F1=0.4216)
  Directional -> Accuracy: 0.4655, MCC: -0.0778, F1: 0.3922

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.41381 | val 4.02732
  Epoch 012 - train 0.33133 | val 3.57065
  Classification -> best τ=0.370 (val F1=0.1709)
  Directional -> Accuracy: 0.6545, MCC: 0.4033, F1: 0.7532

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.31543 | val 1.51906
  Epoch 012 - train 0.25340 | val 1.67965
  Classification -> best τ=0.500 (val F1=0.1635)
  Directional -> Accuracy: 0.5088, MCC: 0.0000, F1: 0.6744

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.40655 | val 1.26913

[I 2026-02-22 09:50:05,154] Trial 75 finished with value: 0.25327061082983976 and parameters: {'feature_set': 'sector', 'model_type': 'BiGRU', 'sequence_length': 12, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 1, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.1, 'batch_size': 32, 'learning_rate': 0.0019424838377257124, 'weight_decay': 4.754039621492428e-07, 'lr_patience': 7, 'lr_factor': 0.8, 'early_stopping_patience': 10, 'max_epochs': 50, 'huber_delta': 1.7185866075978484, 'early_stopping_min_delta': 0.006473357431217271}. Best is trial 22 with value: 0.2833350641483003.

  Epoch 013 - train 0.26053 | val 1.17913
  Classification -> best τ=0.540 (val F1=0.3165)
  Directional -> Accuracy: 0.5161, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.25327061082983976
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: classification
Sequence length: 6
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d', 'sentiment']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.54086 | val 0.76972
  Epoch 011 - train 0.51877 | val 0.78291
  Classification -> best τ=0.475 (val F1=0.1447)
  Directional -> Accuracy: 0.5696, MCC: 0.1387, F1: 0.5405

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 82). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.49881 | val 0.80895
  Epoch 011 - train 0.47476 | val 0.82625
  Classification -> best τ=0.460 (val F1=0.2667)
  Directional -> Accuracy: 0.5625, MCC: 0.0000, F1: 0.7200

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 82). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.50738 | val 1.04969
  Epoch 011 - train 0.51390 | val 1.13665
  Classification -> best τ=0.505 (val F1=0.4414)
  Directional -> Accuracy: 0.5102, MCC: 0.0018, F1: 0.5862

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.53564 | val 0.79155
  Epoch 017 - train 0.46071 | val 1.09323
  Classification -> best τ=0.450 (val F1=0.1976)
  Directional -> Accuracy: 0.5455, MCC: 0.0000, F1: 0.7059

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.48069 | val 0.94037
  Epoch 011 - train 0.43896 | val 0.91834
  Classification -> best τ=0.500 (val F1=0.3984)
  Directional -> Accuracy: 0.5660, MCC: 0.2040, F1: 0.4103

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.47939 | val 1.04328
  Epoch 011 - train 0.47538 | val 1.15168
  Classification -> best τ=0.475 (val F1=0.1795)
  Directional -> Accuracy: 0.5122, MCC: 0.0050, F1: 0.4118

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.58426 | val 0.68586
  Epoch 018 - train 0.44310 | val 0.99961
  Classification -> best τ=0.420 (val F1=0.3338)
  Directional -> Accuracy: 0.4507, MCC: -0.0038, F1: 0.5301

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 82). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 82). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.51773 | val 1.00079
  Epoch 011 - train 0.51908 | val 1.16518
  Classification -> best τ=0.520 (val F1=0.1316)
  Directional -> Accuracy: 0.4894, MCC: -0.0989, F1: 0.2941

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.54650 | val 0.87551
  Epoch 011 - train 0.53698 | val 0.94667
  Classification -> best τ=0.525 (val F1=0.1829)
  Directional -> Accuracy: 0.6047, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 82). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 82). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.51248 | val 0.77320
  Epoch 012 - train 0.47723 | val 0.81085
  Classification -> best τ=0.465 (val F1=0.1448)
  Directional -> Accuracy: 0.5278, MCC: 0.0850, F1: 0.5405

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.53339 | val 1.02782
  Epoch 011 - train 0.49938 | val 0.98840
  Classification -> best τ=0.505 (val F1=0.1189)
  Directional -> Accuracy: 0.5769, MCC: 0.1350, F1: 0.4500

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.51934 | val 1.01477
  Epoch 011 - train 0.48774 | val 1.02361
  Classification -> best τ=0.530 (val F1=0.1116)
  Directional -> Accuracy: 0.6167, MCC: 0.2400, F1: 0.5660

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.47618 | val 0.94524
  Epoch 012 - train 0.47458 | val 1.13817
  Classification -> best τ=0.530 (val F1=0.2253)
  Directional -> Accuracy: 0.5111, MCC: 0.0061, F1: 0.4211

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 82). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.52876 | val 0.60537
  Epoch 017 - train 0.40865 | val 0.73575
  Classification -> best τ=0.660 (val F1=0.3441)
  Directional -> Accuracy: 0.5079, MCC: 0.0052, F1: 0.1622

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.56092 | val 0.73494
  Epoch 018 - train 0.38557 | val 0.87823
  Classification -> best τ=0.575 (val F1=0.3730)
  Directional -> Accuracy: 0.5185, MCC: 0.0307, F1: 0.4583

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.48757 | val 1.27593
  Epoch 011 - train 0.48159 | val 1.24792
  Classification -> best τ=0.480 (val F1=0.2453)
  Directional -> Accuracy: 0.5833, MCC: 0.2267, F1: 0.7222

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.51108 | val 1.35031
  Epoch 011 - train 0.52857 | val 1.51010
  Classification -> best τ=0.585 (val F1=0.1559)
  Directional -> Accuracy: 0.3934, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.57478 | val 0.96979
  Epoch 011 - train 0.54169 | val 1.05656
  Classification -> best τ=0.590 (val F1=0.1083)
  Directional -> Accuracy: 0.3974, MCC: -0.0804, F1: 0.1754

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.56921 | val 0.83278
  Epoch 013 - train 0.47640 | val 0.88823
  Classification -> best τ=0.435 (val F1=0.3114)
  Directional -> Accuracy: 0.5373, MCC: 0.0634, F1: 0.5867

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 82). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.51525 | val 0.75803
  Epoch 013 - train 0.45293 | val 0.82358
  Classification -> best τ=0.385 (val F1=0.2662)
  Directional -> Accuracy: 0.5195, MCC: 0.1491, F1: 0.3019

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.51860 | val 0.76332
  Epoch 011 - train 0.51124 | val 0.75396
  Classification -> best τ=0.455 (val F1=0.1074)
  Directional -> Accuracy: 0.6200, MCC: 0.0000, F1: 0.7654

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 82). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 82). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 82). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.50172 | val 0.81523
  Epoch 014 - train 0.43872 | val 0.77073
  Classification -> best τ=0.385 (val F1=0.3057)
  Directional -> Accuracy: 0.6029, MCC: 0.2377, F1: 0.6824

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.51221 | val 1.38039
  Epoch 011 - train 0.49068 | val 1.41566
  Classification -> best τ=0.590 (val F1=0.2763)
  Directional -> Accuracy: 0.4333, MCC: 0.1100, F1: 0.0556

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.48552 | val 1.09895
  Epoch 011 - train 0.49373 | val 1.16163
  Classification -> best τ=0.460 (val F1=0.0589)
  Directional -> Accuracy: 0.5294, MCC: 0.0580, F1: 0.5152

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.49826 | val 1.00757
  Epoch 014 - train 0.41262 | val 1.22161
  Classification -> best τ=0.505 (val F1=0.4187)
  Directional -> Accuracy: 0.5345, MCC: 0.1519, F1: 0.4000

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.48351 | val 0.73552
  Epoch 015 - train 0.39148 | val 0.97153
  Classification -> best τ=0.470 (val F1=0.4718)
  Directional -> Accuracy: 0.4898, MCC: 0.0121, F1: 0.5098

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.54710 | val 0.71036
  Epoch 011 - train 0.53930 | val 0.72104
  Classification -> best τ=0.515 (val F1=0.0449)
  Directional -> Accuracy: 0.4222, MCC: 0.0364, F1: 0.1333

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.51901 | val 0.79745
  Epoch 011 - train 0.52057 | val 0.84458
  Classification -> best τ=0.455 (val F1=0.3145)
  Directional -> Accuracy: 0.4407, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.48440 | val 0.69524
  Epoch 011 - train 0.47276 | val 0.70494
  Classification -> best τ=0.535 (val F1=0.1626)
  Directional -> Accuracy: 0.3864, MCC: -0.2265, F1: 0.2703

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.53074 | val 1.05295
  Epoch 011 - train 0.54860 | val 1.18544
  Classification -> best τ=0.480 (val F1=0.0765)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.5818

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.57119 | val 0.85374
  Epoch 011 - train 0.56988 | val 0.93001
  Classification -> best τ=0.550 (val F1=0.1084)
  Directional -> Accuracy: 0.5217, MCC: -0.1366, F1: 0.6857

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.52360 | val 0.88522
  Epoch 013 - train 0.50252 | val 0.97559
  Classification -> best τ=0.445 (val F1=0.2608)
  Directional -> Accuracy: 0.5192, MCC: 0.0000, F1: 0.6835

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.56017 | val 0.72116
  Epoch 014 - train 0.44003 | val 0.84510
  Classification -> best τ=0.415 (val F1=0.3758)
  Directional -> Accuracy: 0.5333, MCC: 0.1340, F1: 0.4444

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 82). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.52490 | val 0.84605
  Epoch 011 - train 0.51622 | val 0.85095
  Classification -> best τ=0.510 (val F1=0.2618)
  Directional -> Accuracy: 0.5122, MCC: 0.0868, F1: 0.6552

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.50468 | val 0.94161
  Epoch 011 - train 0.49385 | val 0.98361
  Classification -> best τ=0.440 (val F1=0.1954)
  Directional -> Accuracy: 0.4130, MCC: -0.2326, F1: 0.5846

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.61519 | val 0.76712
  Epoch 011 - train 0.57571 | val 0.77040
  Classification -> best τ=0.495 (val F1=0.1612)
  Directional -> Accuracy: 0.5652, MCC: 0.1163, F1: 0.6154

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.52662 | val 0.80407
  Epoch 011 - train 0.53053 | val 0.80893
  Classification -> best τ=0.515 (val F1=0.1967)
  Directional -> Accuracy: 0.5333, MCC: 0.0653, F1: 0.5532

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.51355 | val 1.14567
  Epoch 011 - train 0.49717 | val 1.20894
  Classification -> best τ=0.525 (val F1=0.1713)
  Directional -> Accuracy: 0.4746, MCC: 0.0000, F1: 0.6437

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.52213 | val 0.90451
  Epoch 011 - train 0.53233 | val 1.04481
  Classification -> best τ=0.460 (val F1=0.2373)
  Directional -> Accuracy: 0.5102, MCC: 0.0069, F1: 0.5714

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 82). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 82). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 82). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 82). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.49869 | val 0.85302
  Epoch 014 - train 0.42230 | val 0.95314
  Classification -> best τ=0.435 (val F1=0.2503)
  Directional -> Accuracy: 0.4524, MCC: 0.2599, F1: 0.5490

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 82). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.49908 | val 0.89394
  Epoch 011 - train 0.45551 | val 0.96001
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5122, MCC: 0.0000, F1: 0.6774

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 82). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 82). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.45020 | val 1.85979
  Epoch 011 - train 0.43193 | val 2.06095
  Classification -> best τ=0.480 (val F1=0.1140)
  Directional -> Accuracy: 0.5065, MCC: 0.0000, F1: 0.6724

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 82). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 82). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.56739 | val 0.94832
  Epoch 011 - train 0.54530 | val 1.02935
  Classification -> best τ=0.605 (val F1=0.0866)
  Directional -> Accuracy: 0.5102, MCC: 0.0061, F1: 0.1429

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.46369 | val 1.32838
  Epoch 011 - train 0.44481 | val 1.44152
  Classification -> best τ=0.495 (val F1=0.2282)
  Directional -> Accuracy: 0.5957, MCC: 0.1280, F1: 0.7077

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.51458 | val 1.16842
  Epoch 011 - train 0.49094 | val 1.15039
  Classification -> best τ=0.655 (val F1=0.1425)
  Directional -> Accuracy: 0.4762, MCC: 0.2740, F1: 0.5769

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.56755 | val 0.76881
  Epoch 012 - train 0.53725 | val 0.80949
  Classification -> best τ=0.505 (val F1=0.1853)
  Directional -> Accuracy: 0.5517, MCC: 0.2036, F1: 0.4091

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.49156 | val 1.21719
  Epoch 011 - train 0.48217 | val 1.21752
  Classification -> best τ=0.525 (val F1=0.3033)
  Directional -> Accuracy: 0.5254, MCC: 0.0506, F1: 0.5172

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.54272 | val 0.96857
  Epoch 011 - train 0.54923 | val 1.06443
  Classification -> best τ=0.465 (val F1=0.0967)
  Directional -> Accuracy: 0.5714, MCC: 0.2067, F1: 0.7143

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.46274 | val 1.27463
  Epoch 011 - train 0.43586 | val 1.28470
  Classification -> best τ=0.505 (val F1=0.1015)
  Directional -> Accuracy: 0.5172, MCC: 0.0000, F1: 0.6818

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...

[I 2026-02-22 09:50:19,915] Trial 76 finished with value: 0.21362365762103575 and parameters: {'feature_set': 'sector_sentiment', 'model_type': 'GRU', 'sequence_length': 6, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 64, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.0, 'batch_size': 64, 'learning_rate': 0.005366469626409033, 'weight_decay': 1.238282321027892e-05, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 20, 'huber_delta': 1.2234769928188218, 'early_stopping_min_delta': 0.009264270883953887}. Best is trial 22 with value: 0.2833350641483003.

  Epoch 010 - train 0.54965 | val 1.08254
  Epoch 011 - train 0.49815 | val 1.07799
  Classification -> best τ=0.480 (val F1=0.2850)
  Directional -> Accuracy: 0.5397, MCC: 0.0728, F1: 0.1714

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.21362365762103575
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 30
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d', 'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down', 'finbert_neutral']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.61022 | val 0.69457
  Epoch 019 - train 0.53177 | val 0.82554
  Classification -> best τ=0.655 (val F1=0.2989)
  Directional -> Accuracy: 0.5600, MCC: 0.1059, F1: 0.4923

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 106). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.53953 | val 0.86449
  Epoch 011 - train 0.54203 | val 0.89013
  Classification -> best τ=0.395 (val F1=0.2178)
  Directional -> Accuracy: 0.5909, MCC: 0.0000, F1: 0.7429

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 106). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.58120 | val 0.95261
  Epoch 011 - train 0.59171 | val 1.02262
  Classification -> best τ=0.545 (val F1=0.0877)
  Directional -> Accuracy: 0.6667, MCC: 0.3571, F1: 0.7458

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.59293 | val 1.11910
  Epoch 011 - train 0.55583 | val 1.14418
  Classification -> best τ=0.425 (val F1=0.1524)
  Directional -> Accuracy: 0.4795, MCC: 0.1100, F1: 0.0500

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.50828 | val 0.64053
  Epoch 018 - train 0.42305 | val 1.06828
  Classification -> best τ=0.630 (val F1=0.5315)
  Directional -> Accuracy: 0.5510, MCC: 0.1485, F1: 0.3529

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.60226 | val 0.68395
  Epoch 020 - train 0.45737 | val 0.75728
  Classification -> best τ=0.590 (val F1=0.3344)
  Directional -> Accuracy: 0.5111, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.58114 | val 0.94162
  Epoch 011 - train 0.58154 | val 0.97374
  Classification -> best τ=0.400 (val F1=0.3236)
  Directional -> Accuracy: 0.5075, MCC: 0.0546, F1: 0.5075

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 106). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 106). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.55742 | val 0.73518
  Epoch 017 - train 0.48331 | val 0.65278
  Classification -> best τ=0.430 (val F1=0.2646)
  Directional -> Accuracy: 0.4390, MCC: 0.0000, F1: 0.6102

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.57379 | val 0.71869
  Epoch 011 - train 0.57726 | val 0.71996
  Classification -> best τ=0.465 (val F1=0.2453)
  Directional -> Accuracy: 0.4468, MCC: 0.0000, F1: 0.6176

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 106). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 106). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 106). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.51295 | val 1.42215
  Epoch 011 - train 0.49762 | val 1.52783
  Classification -> best τ=0.495 (val F1=0.1463)
  Directional -> Accuracy: 0.4853, MCC: 0.0243, F1: 0.5333

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.59783 | val 0.82531
  Epoch 011 - train 0.56176 | val 0.82791
  Classification -> best τ=0.575 (val F1=0.2205)
  Directional -> Accuracy: 0.6042, MCC: 0.2338, F1: 0.2963

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.58747 | val 1.10557
  Epoch 011 - train 0.56768 | val 1.12599
  Classification -> best τ=0.485 (val F1=0.0199)
  Directional -> Accuracy: 0.5536, MCC: 0.1995, F1: 0.6988

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 106). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.52780 | val 1.26319
  Epoch 011 - train 0.53196 | val 1.35514
  Classification -> best τ=0.455 (val F1=0.3777)
  Directional -> Accuracy: 0.4490, MCC: -0.1667, F1: 0.1290

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 106). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.58608 | val 0.64814
  Epoch 013 - train 0.53327 | val 0.83486
  Classification -> best τ=0.535 (val F1=0.3841)
  Directional -> Accuracy: 0.4915, MCC: -0.0032, F1: 0.0625

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.55592 | val 0.77007
  Epoch 011 - train 0.54577 | val 0.79361
  Classification -> best τ=0.645 (val F1=0.0883)
  Directional -> Accuracy: 0.5600, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.56836 | val 0.88272
  Epoch 013 - train 0.52582 | val 0.85770
  Classification -> best τ=0.500 (val F1=0.2539)
  Directional -> Accuracy: 0.5588, MCC: 0.1092, F1: 0.6053

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 106). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.59984 | val 0.94053
  Epoch 011 - train 0.56237 | val 0.94635
  Classification -> best τ=0.525 (val F1=0.2722)
  Directional -> Accuracy: 0.3860, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.60240 | val 0.97137
  Epoch 011 - train 0.55603 | val 1.08461
  Classification -> best τ=0.525 (val F1=0.1566)
  Directional -> Accuracy: 0.4730, MCC: 0.1728, F1: 0.2353

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.58805 | val 0.67630
  Epoch 020 - train 0.42769 | val 0.99240
  Epoch 021 - train 0.42472 | val 0.90534
  Classification -> best τ=0.525 (val F1=0.3494)
  Directional -> Accuracy: 0.4921, MCC: 0.1579, F1: 0.3043

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 106). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.56939 | val 0.69641
  Epoch 014 - train 0.51893 | val 0.76830
  Classification -> best τ=0.295 (val F1=0.2569)
  Directional -> Accuracy: 0.4384, MCC: -0.1583, F1: 0.5287

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.57708 | val 0.70885
  Epoch 014 - train 0.47414 | val 0.77842
  Classification -> best τ=0.500 (val F1=0.2340)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.5490

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 106). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 106). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 106). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.57827 | val 0.77655
  Epoch 011 - train 0.55871 | val 0.78157
  Classification -> best τ=0.450 (val F1=0.2562)
  Directional -> Accuracy: 0.5156, MCC: 0.0501, F1: 0.2051

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.58205 | val 1.12958
  Epoch 011 - train 0.57464 | val 1.14622
  Classification -> best τ=0.645 (val F1=0.3062)
  Directional -> Accuracy: 0.5714, MCC: 0.1667, F1: 0.5714

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.55908 | val 0.76954
  Epoch 011 - train 0.55213 | val 0.79299
  Classification -> best τ=0.445 (val F1=0.1604)
  Directional -> Accuracy: 0.5625, MCC: 0.1341, F1: 0.5758

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.57680 | val 0.77395
  Epoch 011 - train 0.56354 | val 0.79636
  Classification -> best τ=0.510 (val F1=0.3408)
  Directional -> Accuracy: 0.5185, MCC: 0.1163, F1: 0.3158

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.53172 | val 0.72652
  Epoch 011 - train 0.53122 | val 0.72801
  Classification -> best τ=0.500 (val F1=0.0401)
  Directional -> Accuracy: 0.4186, MCC: 0.0000, F1: 0.5902

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.55909 | val 0.69115
  Epoch 017 - train 0.53882 | val 0.84543
  Classification -> best τ=0.420 (val F1=0.1845)
  Directional -> Accuracy: 0.5714, MCC: 0.0170, F1: 0.7042

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.58301 | val 0.80357
  Epoch 012 - train 0.54315 | val 0.90857
  Classification -> best τ=0.495 (val F1=0.3303)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.53612 | val 0.74392
  Epoch 011 - train 0.50457 | val 0.76191
  Classification -> best τ=0.505 (val F1=0.2227)
  Directional -> Accuracy: 0.5000, MCC: 0.0752, F1: 0.3448

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.55321 | val 0.87392
  Epoch 011 - train 0.55286 | val 0.84685
  Classification -> best τ=0.575 (val F1=0.2706)
  Directional -> Accuracy: 0.4878, MCC: -0.0403, F1: 0.3226

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.59026 | val 0.75987
  Epoch 011 - train 0.58091 | val 0.78907
  Classification -> best τ=0.525 (val F1=0.2143)
  Directional -> Accuracy: 0.3171, MCC: -0.3717, F1: 0.3636

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.54898 | val 0.85301
  Epoch 011 - train 0.55188 | val 0.86763
  Classification -> best τ=0.455 (val F1=0.2961)
  Directional -> Accuracy: 0.5208, MCC: 0.0000, F1: 0.6849

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.54753 | val 1.13128
  Epoch 011 - train 0.54991 | val 1.16673
  Classification -> best τ=0.490 (val F1=0.2253)
  Directional -> Accuracy: 0.4366, MCC: 0.0000, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 106). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.57012 | val 0.82096
  Epoch 011 - train 0.55326 | val 0.82417
  Classification -> best τ=0.490 (val F1=0.3031)
  Directional -> Accuracy: 0.4762, MCC: -0.0754, F1: 0.3125

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for PCG (101 < 106). Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.57020 | val 0.94563
  Epoch 011 - train 0.56280 | val 0.98001
  Classification -> best τ=0.385 (val F1=0.3218)
  Directional -> Accuracy: 0.6154, MCC: 0.2063, F1: 0.6753

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.54832 | val 0.70453
  Epoch 014 - train 0.47730 | val 0.71767
  Classification -> best τ=0.465 (val F1=0.2582)
  Directional -> Accuracy: 0.7000, MCC: 0.4127, F1: 0.6842

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.52907 | val 0.78670
  Epoch 011 - train 0.52555 | val 0.81954
  Classification -> best τ=0.325 (val F1=0.1903)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.52978 | val 1.17712
  Epoch 011 - train 0.51509 | val 1.25206
  Classification -> best τ=0.540 (val F1=0.2903)
  Directional -> Accuracy: 0.3778, MCC: -0.0787, F1: 0.1250

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 106). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 106). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 106). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 106). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.59046 | val 0.67638
  Epoch 020 - train 0.47439 | val 0.62580
  Epoch 029 - train 0.43172 | val 0.69276
  Classification -> best τ=0.770 (val F1=0.4385)
  Directional -> Accuracy: 0.3261, MCC: 0.0000, F1: 0.4918

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 106). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 106). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 106). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.53637 | val 1.19094
  Epoch 011 - train 0.51352 | val 1.22981
  Classification -> best τ=0.435 (val F1=0.2619)
  Directional -> Accuracy: 0.5890, MCC: 0.1849, F1: 0.6250

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 106). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 106). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 106). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 106). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.60154 | val 0.65923
  Epoch 018 - train 0.50407 | val 0.87227
  Classification -> best τ=0.535 (val F1=0.5330)
  Directional -> Accuracy: 0.6136, MCC: 0.2624, F1: 0.6909

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.55987 | val 0.76377
  Epoch 011 - train 0.55920 | val 0.77457
  Classification -> best τ=0.460 (val F1=0.1429)
  Directional -> Accuracy: 0.6098, MCC: 0.1830, F1: 0.6800

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.53401 | val 0.79791
  Epoch 011 - train 0.53068 | val 0.81058
  Classification -> best τ=0.430 (val F1=0.0608)
  Directional -> Accuracy: 0.3696, MCC: 0.0000, F1: 0.5397

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.60016 | val 0.75296
  Epoch 011 - train 0.58520 | val 0.74723
  Classification -> best τ=0.460 (val F1=0.1506)
  Directional -> Accuracy: 0.6852, MCC: 0.4249, F1: 0.6531

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.55234 | val 1.27105
  Epoch 011 - train 0.55532 | val 1.37270
  Classification -> best τ=0.575 (val F1=0.3093)
  Directional -> Accuracy: 0.5455, MCC: 0.0980, F1: 0.5902

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.60305 | val 0.67609
  Epoch 016 - train 0.53639 | val 0.81010
  Classification -> best τ=0.535 (val F1=0.2780)
  Directional -> Accuracy: 0.5577, MCC: 0.1525, F1: 0.6667

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.56129 | val 0.70506
  Epoch 012 - train 0.54391 | val 0.72735
  Classification -> best τ=0.385 (val F1=0.1626)
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.59637 | val 0.65717

[I 2026-02-22 09:53:15,580] Trial 77 finished with value: 0.2506483015449971 and parameters: {'feature_set': 'sector_finbert', 'model_type': 'BiGRU', 'sequence_length': 30, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 2, 'inter_rnn_drop': 0.4, 'dropout': 0.30000000000000004, 'batch_size': 32, 'learning_rate': 0.001131903948559414, 'weight_decay': 2.9045359749642498e-05, 'lr_patience': 7, 'lr_factor': 0.8, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 1.4027366757544815, 'early_stopping_min_delta': 0.007066093771561828}. Best is trial 22 with value: 0.2833350641483003.

  Epoch 020 - train 0.49480 | val 1.12523
  Classification -> best τ=0.475 (val F1=0.2661)
  Directional -> Accuracy: 0.4746, MCC: -0.0284, F1: 0.5753

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2506483015449971
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 6
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d', 'positive_emotion', 'negative_emotion', 'uncertainty_emotion', 'positive_emotion_pct', 'negative_emotion_pct', 'uncertainty_emotion_pct']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.42062 | val 0.77417
  Epoch 013 - train 0.31810 | val 1.25330
  Classification -> best τ=0.580 (val F1=0.2416)
  Directional -> Accuracy: 0.5949, MCC: 0.1704, F1: 0.5152

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 82). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.31363 | val 1.04860
  Epoch 012 - train 0.18992 | val 1.51002
  Classification -> best τ=0.500 (val F1=0.2364)
  Directional -> Accuracy: 0.6042, MCC: 0.1843, F1: 0.6667

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 82). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.38828 | val 2.09099
  Epoch 011 - train 0.27393 | val 2.16223
  Classification -> best τ=0.620 (val F1=0.2934)
  Directional -> Accuracy: 0.4694, MCC: -0.0183, F1: 0.1333

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.52846 | val 0.83994
  Epoch 012 - train 0.39420 | val 0.80600
  Classification -> best τ=0.580 (val F1=0.1494)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.36899 | val 1.15311
  Epoch 012 - train 0.25231 | val 1.35525
  Classification -> best τ=0.450 (val F1=0.4804)
  Directional -> Accuracy: 0.5849, MCC: 0.1988, F1: 0.5217

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.25451 | val 0.83516
  Epoch 011 - train 0.30148 | val 1.12687
  Classification -> best τ=0.460 (val F1=0.2460)
  Directional -> Accuracy: 0.4878, MCC: -0.0050, F1: 0.5333

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.46486 | val 1.47245
  Epoch 011 - train 0.35740 | val 1.80945
  Classification -> best τ=0.460 (val F1=0.2702)
  Directional -> Accuracy: 0.5211, MCC: 0.0727, F1: 0.5143

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 82). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 82). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.20024 | val 0.81188
  Epoch 011 - train 0.20449 | val 0.88835
  Classification -> best τ=0.640 (val F1=0.2921)
  Directional -> Accuracy: 0.5957, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.29678 | val 1.92657
  Epoch 011 - train 0.19176 | val 2.60695
  Classification -> best τ=0.410 (val F1=0.1934)
  Directional -> Accuracy: 0.5581, MCC: 0.0472, F1: 0.3871

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 82). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 82). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.48712 | val 1.14349
  Epoch 012 - train 0.41310 | val 1.17163
  Classification -> best τ=0.760 (val F1=0.1348)
  Directional -> Accuracy: 0.5556, MCC: 0.0294, F1: 0.2727

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.37037 | val 1.36390
  Epoch 012 - train 0.20274 | val 1.57640
  Classification -> best τ=0.300 (val F1=0.2037)
  Directional -> Accuracy: 0.4615, MCC: 0.0000, F1: 0.6316

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.58423 | val 0.77975
  Epoch 012 - train 0.33104 | val 0.95734
  Classification -> best τ=0.435 (val F1=0.2247)
  Directional -> Accuracy: 0.5333, MCC: 0.1857, F1: 0.6818

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.38924 | val 1.08616
  Epoch 014 - train 0.17448 | val 0.90057
  Classification -> best τ=0.685 (val F1=0.2550)
  Directional -> Accuracy: 0.4889, MCC: -0.0364, F1: 0.4103

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 82). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.59532 | val 0.66724
  Epoch 012 - train 0.39686 | val 0.73486
  Classification -> best τ=0.480 (val F1=0.3883)
  Directional -> Accuracy: 0.5397, MCC: 0.0898, F1: 0.6027

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.40303 | val 0.89369
  Epoch 011 - train 0.32681 | val 1.36968
  Classification -> best τ=0.595 (val F1=0.1683)
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.54932 | val 1.53077
  Epoch 011 - train 0.39102 | val 1.27599
  Classification -> best τ=0.740 (val F1=0.3259)
  Directional -> Accuracy: 0.5278, MCC: 0.0629, F1: 0.5278

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.37628 | val 1.42943
  Epoch 012 - train 0.21485 | val 1.70514
  Classification -> best τ=0.545 (val F1=0.0974)
  Directional -> Accuracy: 0.6066, MCC: 0.0000, F1: 0.7551

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.50800 | val 1.36240
  Epoch 011 - train 0.36403 | val 1.33360
  Classification -> best τ=0.545 (val F1=0.1642)
  Directional -> Accuracy: 0.5128, MCC: -0.1304, F1: 0.6545

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.41321 | val 1.63821
  Epoch 011 - train 0.32204 | val 1.79092
  Classification -> best τ=0.485 (val F1=0.3085)
  Directional -> Accuracy: 0.5522, MCC: 0.1409, F1: 0.5455

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 82). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.44010 | val 0.89488
  Epoch 011 - train 0.32978 | val 1.08613
  Classification -> best τ=0.590 (val F1=0.1789)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.35149 | val 0.94912
  Epoch 014 - train 0.09769 | val 1.89789
  Classification -> best τ=0.620 (val F1=0.3273)
  Directional -> Accuracy: 0.3800, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 82). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 82). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 82). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.52234 | val 1.57319
  Epoch 011 - train 0.51228 | val 1.55643
  Classification -> best τ=0.440 (val F1=0.2182)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.40266 | val 1.47251
  Epoch 011 - train 0.29275 | val 1.81272
  Classification -> best τ=0.480 (val F1=0.2859)
  Directional -> Accuracy: 0.6333, MCC: 0.2130, F1: 0.7442

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.35646 | val 1.01456
  Epoch 011 - train 0.28659 | val 1.54883
  Classification -> best τ=0.515 (val F1=0.1296)
  Directional -> Accuracy: 0.5294, MCC: 0.0780, F1: 0.1111

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.50455 | val 1.16047
  Epoch 012 - train 0.24184 | val 1.53104
  Classification -> best τ=0.540 (val F1=0.4633)
  Directional -> Accuracy: 0.5345, MCC: 0.1365, F1: 0.4255

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.42809 | val 3.62179
  Epoch 012 - train 0.11851 | val 0.97555
  Classification -> best τ=0.475 (val F1=0.3056)
  Directional -> Accuracy: 0.4490, MCC: -0.0511, F1: 0.5091

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.28091 | val 0.95248
  Epoch 012 - train 0.15059 | val 1.05413
  Classification -> best τ=0.500 (val F1=0.3359)
  Directional -> Accuracy: 0.5556, MCC: 0.0392, F1: 0.6552

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.42198 | val 1.40478
  Epoch 011 - train 0.30175 | val 1.46066
  Classification -> best τ=0.460 (val F1=0.2184)
  Directional -> Accuracy: 0.4407, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.31250 | val 1.52314
  Epoch 018 - train 0.05684 | val 1.37395
  Classification -> best τ=0.540 (val F1=0.4798)
  Directional -> Accuracy: 0.5227, MCC: 0.0965, F1: 0.3226

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.32859 | val 1.44086
  Epoch 012 - train 0.18099 | val 1.34816
  Classification -> best τ=0.395 (val F1=0.2485)
  Directional -> Accuracy: 0.5435, MCC: 0.1054, F1: 0.6441

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.32880 | val 1.93804
  Epoch 012 - train 0.29690 | val 2.09576
  Classification -> best τ=0.555 (val F1=0.2157)
  Directional -> Accuracy: 0.4348, MCC: -0.1875, F1: 0.5517

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.27470 | val 1.31014
  Epoch 011 - train 0.21024 | val 1.33104
  Classification -> best τ=0.455 (val F1=0.2955)
  Directional -> Accuracy: 0.5192, MCC: 0.0000, F1: 0.6835

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.44239 | val 0.82628
  Epoch 013 - train 0.38638 | val 0.87629
  Classification -> best τ=0.395 (val F1=0.2955)
  Directional -> Accuracy: 0.4533, MCC: -0.0121, F1: 0.2264

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 82). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.23157 | val 1.68632
  Epoch 012 - train 0.17422 | val 2.41377
  Classification -> best τ=0.500 (val F1=0.0989)
  Directional -> Accuracy: 0.4878, MCC: -0.0195, F1: 0.5333

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.28429 | val 1.42824
  Epoch 011 - train 0.20305 | val 1.63565
  Classification -> best τ=0.315 (val F1=0.1280)
  Directional -> Accuracy: 0.5000, MCC: 0.0115, F1: 0.5106

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.49478 | val 0.92425
  Epoch 013 - train 0.27209 | val 0.94620
  Classification -> best τ=0.450 (val F1=0.2029)
  Directional -> Accuracy: 0.4493, MCC: 0.1471, F1: 0.0952

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.20785 | val 1.43567
  Epoch 013 - train 0.10649 | val 1.83414
  Classification -> best τ=0.495 (val F1=0.4328)
  Directional -> Accuracy: 0.5333, MCC: 0.0653, F1: 0.5532

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.45393 | val 1.27940
  Epoch 012 - train 0.32045 | val 1.76144
  Classification -> best τ=0.525 (val F1=0.1611)
  Directional -> Accuracy: 0.4576, MCC: -0.1011, F1: 0.3600

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.16854 | val 1.14726
  Epoch 011 - train 0.10664 | val 1.25197
  Classification -> best τ=0.455 (val F1=0.4265)
  Directional -> Accuracy: 0.5918, MCC: 0.0910, F1: 0.6970

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 82). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 82). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 82). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 82). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.26146 | val 1.21412
  Epoch 011 - train 0.20399 | val 1.21734
  Classification -> best τ=0.425 (val F1=0.2503)
  Directional -> Accuracy: 0.3333, MCC: 0.0000, F1: 0.5000

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 82). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.31514 | val 3.36919
  Epoch 011 - train 0.13685 | val 3.61920
  Classification -> best τ=0.550 (val F1=0.4183)
  Directional -> Accuracy: 0.4390, MCC: -0.1241, F1: 0.4651

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 82). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 82). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.41189 | val 1.68462
  Epoch 012 - train 0.29334 | val 2.50779
  Classification -> best τ=0.395 (val F1=0.2383)
  Directional -> Accuracy: 0.5065, MCC: 0.0000, F1: 0.6724

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 82). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 82). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.35436 | val 3.44811
  Epoch 012 - train 0.21158 | val 2.63005
  Classification -> best τ=0.685 (val F1=0.1789)
  Directional -> Accuracy: 0.4490, MCC: -0.1485, F1: 0.1818

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.17899 | val 2.97121
  Epoch 011 - train 0.13190 | val 2.93692
  Classification -> best τ=0.425 (val F1=0.1754)
  Directional -> Accuracy: 0.5745, MCC: 0.1187, F1: 0.6429

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.21567 | val 0.87041
  Epoch 011 - train 0.19333 | val 1.02092
  Classification -> best τ=0.640 (val F1=0.4385)
  Directional -> Accuracy: 0.6429, MCC: 0.0000, F1: 0.0000

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.45581 | val 0.86425
  Epoch 011 - train 0.37360 | val 0.95531
  Classification -> best τ=0.615 (val F1=0.2287)
  Directional -> Accuracy: 0.4483, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.21405 | val 1.21928
  Epoch 011 - train 0.27330 | val 2.28771
  Classification -> best τ=0.460 (val F1=0.3505)
  Directional -> Accuracy: 0.5254, MCC: 0.1336, F1: 0.0667

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.43817 | val 0.85212
  Epoch 011 - train 0.34283 | val 0.95905
  Classification -> best τ=0.335 (val F1=0.2143)
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.46451 | val 1.53654
  Epoch 013 - train 0.15989 | val 2.80756
  Classification -> best τ=0.435 (val F1=0.2076)
  Directional -> Accuracy: 0.5172, MCC: 0.0065, F1: 0.6744

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.46257 | val 0.96905
  Epoch 011 - train 0.39050 | val 0.86078

[I 2026-02-22 09:54:09,994] Trial 78 finished with value: 0.26228915720946255 and parameters: {'feature_set': 'sector_unified_emotion', 'model_type': 'BiGRU', 'sequence_length': 6, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.1, 'dropout': 0.2, 'batch_size': 32, 'learning_rate': 0.008096412358526569, 'weight_decay': 2.1523684524134883e-06, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 50, 'huber_delta': 0.8470121101930089, 'early_stopping_min_delta': 0.007798468594064002}. Best is trial 22 with value: 0.2833350641483003.

  Classification -> best τ=0.490 (val F1=0.2911)
  Directional -> Accuracy: 0.5238, MCC: 0.0400, F1: 0.4643

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.26228915720946255
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: classification
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'emotion_anger', 'emotion_disgust', 'emotion_fear', 'emotion_joy', 'emotion_neutral', 'emotion_sadness', 'emotion_surprize', 'emotion_anger_pct', 'emotion_disgust_pct', 'emotion_fear_pct', 'emotion_joy_pct', 'emotion_neutral_pct', 'emotion_sadness_pct', 'emotion_surprize_pct']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.68434 | val 0.70193
  Epoch 020 - train 0.67203 | val 0.70143
  Epoch 021 - train 0.68422 | val 0.70142
  Classification -> best τ=0.455 (val F1=0.1653)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.65268 | val 0.70855
  Epoch 020 - train 0.64974 | val 0.71185
  Epoch 021 - train 0.64703 | val 0.71205
  Classification -> best τ=0.535 (val F1=0.1700)
  Directional -> Accuracy: 0.5000, MCC: -0.0232, F1: 0.5660

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.69965 | val 0.68036
  Epoch 020 - train 0.66968 | val 0.67500
  Epoch 030 - train 0.65582 | val 0.67057
  Classification -> best τ=0.510 (val F1=0.3938)
  Directional -> Accuracy: 0.4681, MCC: -0.0712, F1: 0.5098

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.68274 | val 0.70684
  Epoch 020 - train 0.66833 | val 0.71244
  Epoch 021 - train 0.67040 | val 0.71251
  Classification -> best τ=0.485 (val F1=0.1210)
  Directional -> Accuracy: 0.5333, MCC: 0.0134, F1: 0.6535

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.67706 | val 0.68036
  Epoch 020 - train 0.64846 | val 0.66606
  Epoch 030 - train 0.63270 | val 0.66268
  Classification -> best τ=0.420 (val F1=0.4138)
  Directional -> Accuracy: 0.7059, MCC: 0.4087, F1: 0.7273

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.67925 | val 1.01833
  Epoch 020 - train 0.67803 | val 1.07432
  Epoch 021 - train 0.67698 | val 1.07526
  Classification -> best τ=0.495 (val F1=0.2182)
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.67826 | val 0.68812
  Epoch 020 - train 0.67698 | val 0.69181
  Epoch 023 - train 0.67599 | val 0.69225
  Classification -> best τ=0.565 (val F1=0.2533)
  Directional -> Accuracy: 0.5942, MCC: 0.0592, F1: 0.1765

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.70827 | val 0.67674
  Epoch 020 - train 0.69925 | val 0.68529
  Epoch 021 - train 0.70238 | val 0.68554
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.5806

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.68210 | val 0.66905
  Epoch 020 - train 0.65903 | val 0.66617
  Epoch 029 - train 0.65338 | val 0.66360
  Classification -> best τ=0.505 (val F1=0.2881)
  Directional -> Accuracy: 0.5102, MCC: -0.0869, F1: 0.1429

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.68021 | val 0.68125
  Epoch 020 - train 0.65203 | val 0.67442
  Epoch 030 - train 0.64565 | val 0.67598
  Classification -> best τ=0.595 (val F1=0.3096)
  Directional -> Accuracy: 0.6143, MCC: 0.1925, F1: 0.2703

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.65663 | val 0.72436
  Epoch 020 - train 0.66639 | val 0.73509
  Epoch 021 - train 0.67066 | val 0.73566
  Classification -> best τ=0.540 (val F1=0.1675)
  Directional -> Accuracy: 0.6600, MCC: 0.3270, F1: 0.5143

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.68355 | val 0.70504
  Epoch 020 - train 0.66874 | val 0.70415
  Epoch 021 - train 0.67845 | val 0.70413
  Classification -> best τ=0.515 (val F1=0.2427)
  Directional -> Accuracy: 0.4828, MCC: -0.1325, F1: 0.6512

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.68451 | val 0.70548
  Epoch 020 - train 0.66407 | val 0.70699
  Epoch 021 - train 0.66347 | val 0.70706
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.69126 | val 0.76041
  Epoch 020 - train 0.69290 | val 0.76012
  Epoch 021 - train 0.68501 | val 0.76012
  Classification -> best τ=0.485 (val F1=0.2086)
  Directional -> Accuracy: 0.4918, MCC: -0.0394, F1: 0.6265

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.69262 | val 0.74271
  Epoch 020 - train 0.68841 | val 0.74412
  Epoch 021 - train 0.67830 | val 0.74412
  Classification -> best τ=0.530 (val F1=0.1802)
  Directional -> Accuracy: 0.4231, MCC: -0.2160, F1: 0.5946

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.67620 | val 0.68909
  Epoch 020 - train 0.66299 | val 0.68579
  Epoch 021 - train 0.65312 | val 0.68560
  Classification -> best τ=0.545 (val F1=0.1012)
  Directional -> Accuracy: 0.4571, MCC: 0.0000, F1: 0.0000

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.65854 | val 0.85330
  Epoch 020 - train 0.65862 | val 0.85670
  Epoch 021 - train 0.65849 | val 0.85682
  Classification -> best τ=0.550 (val F1=0.1414)
  Directional -> Accuracy: 0.5085, MCC: -0.1036, F1: 0.6329

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.67405 | val 0.72824
  Epoch 020 - train 0.66723 | val 0.72873
  Epoch 021 - train 0.67368 | val 0.72868
  Classification -> best τ=0.555 (val F1=0.0429)
  Directional -> Accuracy: 0.5263, MCC: -0.0029, F1: 0.6170

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.67446 | val 0.69687
  Epoch 020 - train 0.66524 | val 0.69737
  Epoch 021 - train 0.67491 | val 0.69753
  Classification -> best τ=0.470 (val F1=0.2249)
  Directional -> Accuracy: 0.4462, MCC: -0.1818, F1: 0.5610

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.67490 | val 0.70703
  Epoch 020 - train 0.66913 | val 0.69871
  Epoch 021 - train 0.66332 | val 0.69850
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.68131 | val 0.72626
  Epoch 020 - train 0.66397 | val 0.72553
  Epoch 021 - train 0.65947 | val 0.72550
  Classification -> best τ=0.485 (val F1=0.2000)
  Directional -> Accuracy: 0.3958, MCC: 0.1130, F1: 0.0645

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.68869 | val 0.68160
  Epoch 020 - train 0.66728 | val 0.68313
  Epoch 026 - train 0.66794 | val 0.68333
  Classification -> best τ=0.425 (val F1=0.3130)
  Directional -> Accuracy: 0.5152, MCC: 0.0573, F1: 0.6596

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.68794 | val 0.70790
  Epoch 020 - train 0.68470 | val 0.70363
  Epoch 021 - train 0.68538 | val 0.70350
  Classification -> best τ=0.505 (val F1=0.1371)
  Directional -> Accuracy: 0.5690, MCC: 0.0000, F1: 0.7253

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.69441 | val 0.75317
  Epoch 020 - train 0.68947 | val 0.75782
  Epoch 021 - train 0.68676 | val 0.75812
  Classification -> best τ=0.430 (val F1=0.1664)
  Directional -> Accuracy: 0.4545, MCC: -0.0861, F1: 0.6170

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.67242 | val 0.66075
  Epoch 020 - train 0.65581 | val 0.65914
  Epoch 025 - train 0.65779 | val 0.66021
  Classification -> best τ=0.495 (val F1=0.4352)
  Directional -> Accuracy: 0.5536, MCC: 0.1003, F1: 0.5902

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.69453 | val 0.73833
  Epoch 020 - train 0.67988 | val 0.74499
  Epoch 021 - train 0.68282 | val 0.74502
  Classification -> best τ=0.460 (val F1=0.0825)
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.0000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.68450 | val 0.72950
  Epoch 020 - train 0.68246 | val 0.72954
  Epoch 021 - train 0.67902 | val 0.72968
  Classification -> best τ=0.455 (val F1=0.1140)
  Directional -> Accuracy: 0.5581, MCC: 0.1656, F1: 0.5366

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.68172 | val 0.69436
  Epoch 020 - train 0.66554 | val 0.69506
  Epoch 021 - train 0.67373 | val 0.69511
  Classification -> best τ=0.495 (val F1=0.1893)
  Directional -> Accuracy: 0.4211, MCC: -0.1083, F1: 0.0571

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.70132 | val 0.73455
  Epoch 020 - train 0.71334 | val 0.73301
  Epoch 021 - train 0.70319 | val 0.73293
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.69366 | val 0.71310
  Epoch 020 - train 0.68140 | val 0.71947
  Epoch 021 - train 0.67985 | val 0.71960
  Classification -> best τ=0.475 (val F1=0.1574)
  Directional -> Accuracy: 0.4884, MCC: -0.0074, F1: 0.6333

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.67277 | val 0.73645
  Epoch 020 - train 0.66923 | val 0.73893
  Epoch 021 - train 0.67916 | val 0.73902
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.69121 | val 0.72719
  Epoch 020 - train 0.67695 | val 0.72410
  Epoch 021 - train 0.67821 | val 0.72403
  Classification -> best τ=0.520 (val F1=0.0209)
  Directional -> Accuracy: 0.5600, MCC: 0.0936, F1: 0.6944

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.66899 | val 0.66586
  Epoch 020 - train 0.66363 | val 0.65021
  Epoch 030 - train 0.63639 | val 0.64083
  Classification -> best τ=0.430 (val F1=0.4214)
  Directional -> Accuracy: 0.5205, MCC: 0.1344, F1: 0.3860

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.66627 | val 0.70857
  Epoch 020 - train 0.66006 | val 0.72990
  Epoch 021 - train 0.65175 | val 0.73012
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.66628 | val 0.68116
  Epoch 020 - train 0.64462 | val 0.70385
  Epoch 024 - train 0.65971 | val 0.70743
  Classification -> best τ=0.495 (val F1=0.3366)
  Directional -> Accuracy: 0.4545, MCC: -0.0932, F1: 0.4286

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.67874 | val 0.70960
  Epoch 020 - train 0.68194 | val 0.70687
  Epoch 021 - train 0.68149 | val 0.70682
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5672, MCC: 0.0000, F1: 0.7238

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.69305 | val 0.68602
  Epoch 020 - train 0.66604 | val 0.68254
  Epoch 028 - train 0.63651 | val 0.68260
  Classification -> best τ=0.445 (val F1=0.2251)
  Directional -> Accuracy: 0.5581, MCC: 0.1198, F1: 0.5366

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.65921 | val 0.70626
  Epoch 020 - train 0.64108 | val 0.70973
  Epoch 021 - train 0.65613 | val 0.70987
  Classification -> best τ=0.480 (val F1=0.2207)
  Directional -> Accuracy: 0.5088, MCC: 0.1809, F1: 0.6585

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.68096 | val 0.70333
  Epoch 020 - train 0.67567 | val 0.71273
  Epoch 021 - train 0.65915 | val 0.71316
  Classification -> best τ=0.500 (val F1=0.1871)
  Directional -> Accuracy: 0.3404, MCC: -0.2303, F1: 0.0606

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.68355 | val 0.71793
  Epoch 020 - train 0.68705 | val 0.71890
  Epoch 021 - train 0.67795 | val 0.71889
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.67016 | val 0.70983
  Epoch 020 - train 0.68333 | val 0.72065
  Epoch 021 - train 0.66075 | val 0.72072
  Classification -> best τ=0.520 (val F1=0.2496)
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.0000

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.65151 | val 0.68833
  Epoch 020 - train 0.64323 | val 0.69325
  Epoch 021 - train 0.64894 | val 0.69343
  Classification -> best τ=0.550 (val F1=0.1961)
  Directional -> Accuracy: 0.5200, MCC: 0.0432, F1: 0.2500

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.69200 | val 0.70998
  Epoch 020 - train 0.68232 | val 0.70630
  Epoch 021 - train 0.67064 | val 0.70621
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.69193 | val 0.68933
  Epoch 020 - train 0.68438 | val 0.69482
  Epoch 021 - train 0.67657 | val 0.69486
  Classification -> best τ=0.465 (val F1=0.1455)
  Directional -> Accuracy: 0.5227, MCC: -0.1161, F1: 0.6769

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.67244 | val 0.74168
  Epoch 020 - train 0.68528 | val 0.75099
  Epoch 021 - train 0.67060 | val 0.75113
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.69199 | val 0.75171
  Epoch 020 - train 0.67307 | val 0.74637
  Epoch 021 - train 0.66540 | val 0.74620
  Classification -> best τ=0.480 (val F1=0.2505)
  Directional -> Accuracy: 0.5179, MCC: 0.0185, F1: 0.5846

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.68502 | val 0.67587
  Epoch 020 - train 0.67210 | val 0.68469
  Epoch 024 - train 0.67119 | val 0.68613
  Classification -> best τ=0.535 (val F1=0.3160)
  Directional -> Accuracy: 0.5439, MCC: 0.0928, F1: 0.5517

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.69141 | val 0.96908
  Epoch 020 - train 0.68178 | val 0.96308

[I 2026-02-22 09:59:17,430] Trial 79 finished with value: 0.17501431778711488 and parameters: {'feature_set': 'emotion', 'model_type': 'BiLSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 1, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.4, 'batch_size': 16, 'learning_rate': 1.0332911126276728e-05, 'weight_decay': 4.4487318757626625e-06, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 30, 'huber_delta': 1.1363468174521851, 'early_stopping_min_delta': 0.008624437763385933}. Best is trial 22 with value: 0.2833350641483003.

  Epoch 021 - train 0.67909 | val 0.73600
  Classification -> best τ=0.490 (val F1=0.2406)
  Directional -> Accuracy: 0.4918, MCC: -0.0314, F1: 0.3922

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.17501431778711488
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sentiment']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.62605 | val 0.71370
  Epoch 011 - train 0.61609 | val 0.85054
  Classification -> best τ=0.505 (val F1=0.2036)
  Directional -> Accuracy: 0.5263, MCC: -0.0671, F1: 0.1000

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.57000 | val 0.93432
  Epoch 011 - train 0.56918 | val 0.97697
  Classification -> best τ=0.360 (val F1=0.1085)
  Directional -> Accuracy: 0.5778, MCC: 0.0000, F1: 0.7324

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.64343 | val 0.65956
  Epoch 018 - train 0.54346 | val 0.78482
  Classification -> best τ=0.595 (val F1=0.3673)
  Directional -> Accuracy: 0.4565, MCC: -0.0996, F1: 0.0741

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.62279 | val 1.40080
  Epoch 011 - train 0.62124 | val 1.55488
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5405, MCC: 0.0000, F1: 0.7018

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.57344 | val 0.62677
  Epoch 014 - train 0.53811 | val 0.67508
  Classification -> best τ=0.575 (val F1=0.4414)
  Directional -> Accuracy: 0.6600, MCC: 0.3398, F1: 0.6222

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.57148 | val 0.87280
  Epoch 011 - train 0.55389 | val 0.97219
  Classification -> best τ=0.545 (val F1=0.1294)
  Directional -> Accuracy: 0.5217, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.62047 | val 0.82953
  Epoch 011 - train 0.59717 | val 0.92342
  Classification -> best τ=0.515 (val F1=0.2727)
  Directional -> Accuracy: 0.5294, MCC: 0.1201, F1: 0.5429

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.56232 | val 1.40653
  Epoch 011 - train 0.57832 | val 1.31939
  Classification -> best τ=0.495 (val F1=0.1147)
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.58051 | val 0.83062
  Epoch 011 - train 0.58399 | val 1.04705
  Classification -> best τ=0.540 (val F1=0.1975)
  Directional -> Accuracy: 0.5625, MCC: 0.0380, F1: 0.1600

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.60928 | val 0.81494
  Epoch 012 - train 0.58581 | val 0.81040
  Classification -> best τ=0.490 (val F1=0.1607)
  Directional -> Accuracy: 0.5362, MCC: 0.0010, F1: 0.3333

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.64673 | val 0.68282
  Epoch 020 - train 0.55291 | val 0.66324
  Epoch 021 - train 0.54541 | val 0.69443
  Classification -> best τ=0.510 (val F1=0.4498)
  Directional -> Accuracy: 0.6122, MCC: 0.2379, F1: 0.2963

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.61127 | val 1.11869
  Epoch 012 - train 0.60486 | val 1.07220
  Classification -> best τ=0.400 (val F1=0.1512)
  Directional -> Accuracy: 0.6140, MCC: 0.2302, F1: 0.6562

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.55328 | val 1.89429
  Epoch 011 - train 0.56396 | val 2.04791
  Classification -> best τ=0.460 (val F1=0.1754)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.6230

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.63244 | val 0.77124
  Epoch 014 - train 0.58090 | val 1.21766
  Classification -> best τ=0.410 (val F1=0.2902)
  Directional -> Accuracy: 0.5333, MCC: 0.1857, F1: 0.6818

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.50492 | val 0.86025
  Epoch 011 - train 0.53011 | val 0.98356
  Classification -> best τ=0.545 (val F1=0.1455)
  Directional -> Accuracy: 0.5490, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.57803 | val 0.81025
  Epoch 011 - train 0.54484 | val 0.83297
  Classification -> best τ=0.490 (val F1=0.2795)
  Directional -> Accuracy: 0.5797, MCC: 0.1688, F1: 0.7071

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.63194 | val 1.05761
  Epoch 011 - train 0.62488 | val 0.88051
  Classification -> best τ=0.650 (val F1=0.1731)
  Directional -> Accuracy: 0.3793, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.64132 | val 0.78403
  Epoch 011 - train 0.62434 | val 0.78584
  Classification -> best τ=0.585 (val F1=0.1087)
  Directional -> Accuracy: 0.4000, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.60741 | val 0.97913
  Epoch 011 - train 0.61241 | val 1.05486
  Classification -> best τ=0.475 (val F1=0.1790)
  Directional -> Accuracy: 0.5000, MCC: 0.1376, F1: 0.3333

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.58049 | val 0.80228
  Epoch 011 - train 0.57949 | val 0.81062
  Classification -> best τ=0.495 (val F1=0.2597)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.62468 | val 0.91699
  Epoch 011 - train 0.60849 | val 0.91059
  Classification -> best τ=0.525 (val F1=0.1506)
  Directional -> Accuracy: 0.5319, MCC: -0.0346, F1: 0.6452

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.64523 | val 1.07235
  Epoch 011 - train 0.60996 | val 1.21435
  Classification -> best τ=0.575 (val F1=0.2315)
  Directional -> Accuracy: 0.4923, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.57950 | val 1.16943
  Epoch 011 - train 0.57138 | val 1.18242
  Classification -> best τ=0.550 (val F1=0.2666)
  Directional -> Accuracy: 0.5088, MCC: 0.1095, F1: 0.3636

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.58630 | val 0.73123
  Epoch 011 - train 0.58791 | val 0.79864
  Classification -> best τ=0.510 (val F1=0.1565)
  Directional -> Accuracy: 0.5385, MCC: 0.0971, F1: 0.5946

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.60356 | val 0.82135
  Epoch 013 - train 0.55427 | val 0.84854
  Classification -> best τ=0.610 (val F1=0.4603)
  Directional -> Accuracy: 0.5455, MCC: 0.1826, F1: 0.3902

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.53695 | val 1.17389
  Epoch 011 - train 0.57233 | val 1.37762
  Classification -> best τ=0.535 (val F1=0.1099)
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.5938

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.61997 | val 0.96014
  Epoch 011 - train 0.60441 | val 0.93215
  Classification -> best τ=0.525 (val F1=0.1132)
  Directional -> Accuracy: 0.5238, MCC: -0.0525, F1: 0.6552

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.61714 | val 0.80783
  Epoch 012 - train 0.60151 | val 0.83358
  Classification -> best τ=0.485 (val F1=0.2976)
  Directional -> Accuracy: 0.4464, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.58211 | val 1.63184
  Epoch 011 - train 0.58010 | val 1.88512
  Classification -> best τ=0.555 (val F1=0.1870)
  Directional -> Accuracy: 0.4750, MCC: -0.0356, F1: 0.4615

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.58109 | val 0.65425
  Epoch 020 - train 0.50557 | val 0.64719
  Epoch 025 - train 0.42761 | val 0.64790
  Classification -> best τ=0.540 (val F1=0.4846)
  Directional -> Accuracy: 0.5238, MCC: 0.0550, F1: 0.5455

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.60684 | val 1.42781
  Epoch 011 - train 0.60138 | val 1.39988
  Classification -> best τ=0.440 (val F1=0.0409)
  Directional -> Accuracy: 0.5476, MCC: 0.0310, F1: 0.6885

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.57046 | val 0.79324
  Epoch 011 - train 0.56045 | val 0.83296
  Classification -> best τ=0.480 (val F1=0.1903)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.61582 | val 0.68479
  Epoch 012 - train 0.60364 | val 0.70457
  Classification -> best τ=0.470 (val F1=0.3369)
  Directional -> Accuracy: 0.5278, MCC: 0.1291, F1: 0.4138

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.58806 | val 1.40817
  Epoch 011 - train 0.58747 | val 1.51510
  Classification -> best τ=0.450 (val F1=0.3078)
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.58795 | val 0.89379
  Epoch 011 - train 0.59100 | val 0.92604
  Classification -> best τ=0.415 (val F1=0.3855)
  Directional -> Accuracy: 0.6212, MCC: 0.2145, F1: 0.6835

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.54943 | val 1.03794
  Epoch 011 - train 0.50376 | val 1.01567
  Classification -> best τ=0.460 (val F1=0.2768)
  Directional -> Accuracy: 0.5952, MCC: 0.2656, F1: 0.4516

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.54048 | val 1.00035
  Epoch 011 - train 0.56064 | val 1.09500
  Classification -> best τ=0.485 (val F1=0.2382)
  Directional -> Accuracy: 0.4643, MCC: -0.0667, F1: 0.4643

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.52412 | val 1.46199
  Epoch 011 - train 0.53993 | val 1.24784
  Classification -> best τ=0.500 (val F1=0.2800)
  Directional -> Accuracy: 0.6087, MCC: 0.0000, F1: 0.7568

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.54760 | val 0.73444
  Epoch 014 - train 0.56184 | val 0.72611
  Classification -> best τ=0.580 (val F1=0.3800)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.59676 | val 0.98958
  Epoch 011 - train 0.56851 | val 1.10496
  Classification -> best τ=0.485 (val F1=0.1940)
  Directional -> Accuracy: 0.4865, MCC: 0.0000, F1: 0.6545

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.61142 | val 0.93098
  Epoch 013 - train 0.56293 | val 1.50633
  Classification -> best τ=0.455 (val F1=0.3953)
  Directional -> Accuracy: 0.5778, MCC: 0.2222, F1: 0.3871

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.57868 | val 0.72942
  Epoch 011 - train 0.55892 | val 0.71717
  Classification -> best τ=0.515 (val F1=0.3612)
  Directional -> Accuracy: 0.3810, MCC: -0.2582, F1: 0.0000

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.58097 | val 0.62028
  Epoch 020 - train 0.46308 | val 0.48791
  Epoch 030 - train 0.28608 | val 0.79946
  Classification -> best τ=0.220 (val F1=0.7040)
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.5455

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.63701 | val 0.80065
  Epoch 014 - train 0.62579 | val 0.84614
  Classification -> best τ=0.600 (val F1=0.1784)
  Directional -> Accuracy: 0.5273, MCC: 0.2557, F1: 0.2353

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.57366 | val 1.22698
  Epoch 011 - train 0.55342 | val 1.35355
  Classification -> best τ=0.610 (val F1=0.3246)
  Directional -> Accuracy: 0.5893, MCC: 0.2270, F1: 0.6667

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.59028 | val 0.82970
  Epoch 011 - train 0.60034 | val 0.79802
  Classification -> best τ=0.500 (val F1=0.2064)
  Directional -> Accuracy: 0.5849, MCC: 0.1691, F1: 0.6207

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.58285 | val 1.40566
  Epoch 011 - train 0.54200 | val 1.46868
  Classification -> best τ=0.615 (val F1=0.2111)
  Directional -> Accuracy: 0.5273, MCC: 0.0000, F1: 0.6905

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.58351 | val 0.79509

[I 2026-02-22 10:00:12,194] Trial 80 finished with value: 0.2470074819885306 and parameters: {'feature_set': 'sentinment', 'model_type': 'GRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 64, 'num_layers': 2, 'inter_rnn_drop': 0.4, 'dropout': 0.0, 'batch_size': 32, 'learning_rate': 0.0028921698576980393, 'weight_decay': 9.096588966215325e-07, 'lr_patience': 7, 'lr_factor': 0.8, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 1.3446656989639338, 'early_stopping_min_delta': 0.009654971804915586}. Best is trial 22 with value: 0.2833350641483003.

  Epoch 013 - train 0.54065 | val 0.80354
  Classification -> best τ=0.405 (val F1=0.1794)
  Directional -> Accuracy: 0.5000, MCC: 0.0327, F1: 0.6250

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2470074819885306
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: classification
Sequence length: 30
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d', 'sentiment']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.34169 | val 1.26126
  Epoch 020 - train 0.04318 | val 4.72766
  Epoch 021 - train 0.02808 | val 4.93199
  Classification -> best τ=0.380 (val F1=0.2231)
  Directional -> Accuracy: 0.5867, MCC: 0.2045, F1: 0.6173

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 106). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.21812 | val 1.59157
  Epoch 020 - train 0.03633 | val 1.40724
  Epoch 021 - train 0.01577 | val 1.44001
  Classification -> best τ=0.470 (val F1=0.2503)
  Directional -> Accuracy: 0.6136, MCC: 0.1417, F1: 0.7463

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 106). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.22669 | val 3.93105
  Epoch 020 - train 0.00580 | val 6.15079
  Epoch 021 - train 0.00407 | val 6.19609
  Classification -> best τ=0.635 (val F1=0.2095)
  Directional -> Accuracy: 0.4667, MCC: -0.0144, F1: 0.0769

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.42695 | val 2.05488
  Epoch 020 - train 0.08267 | val 4.90554
  Epoch 021 - train 0.06599 | val 5.58193
  Classification -> best τ=0.415 (val F1=0.1617)
  Directional -> Accuracy: 0.4932, MCC: -0.0670, F1: 0.6186

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.33177 | val 0.85936
  Epoch 020 - train 0.01259 | val 1.54988
  Epoch 026 - train 0.00274 | val 1.88680
  Classification -> best τ=0.460 (val F1=0.3774)
  Directional -> Accuracy: 0.6531, MCC: 0.3486, F1: 0.5641

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.26619 | val 1.18944
  Epoch 020 - train 0.01272 | val 1.82371
  Epoch 021 - train 0.00943 | val 1.87316
  Classification -> best τ=0.585 (val F1=0.2294)
  Directional -> Accuracy: 0.5111, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.32164 | val 1.90058
  Epoch 020 - train 0.02034 | val 3.74864
  Epoch 022 - train 0.01130 | val 3.97885
  Classification -> best τ=0.585 (val F1=0.1793)
  Directional -> Accuracy: 0.5970, MCC: 0.0000, F1: 0.0000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 106). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 106). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.24295 | val 2.26304
  Epoch 020 - train 0.01873 | val 3.01271
  Epoch 022 - train 0.00847 | val 3.13568
  Classification -> best τ=0.580 (val F1=0.3637)
  Directional -> Accuracy: 0.4634, MCC: -0.1032, F1: 0.3529

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.30409 | val 1.46970
  Epoch 020 - train 0.02301 | val 1.66231
  Epoch 021 - train 0.01583 | val 1.68750
  Classification -> best τ=0.475 (val F1=0.2895)
  Directional -> Accuracy: 0.6383, MCC: 0.2648, F1: 0.4516

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 106). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 106). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 106). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.41734 | val 1.34130
  Epoch 020 - train 0.02304 | val 4.24880
  Epoch 021 - train 0.01413 | val 4.54090
  Classification -> best τ=0.335 (val F1=0.1654)
  Directional -> Accuracy: 0.4265, MCC: 0.0000, F1: 0.5979

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.29921 | val 1.30990
  Epoch 020 - train 0.01739 | val 3.13589
  Epoch 022 - train 0.00986 | val 2.80000
  Classification -> best τ=0.675 (val F1=0.3478)
  Directional -> Accuracy: 0.6042, MCC: 0.2807, F1: 0.2400

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.33125 | val 1.85870
  Epoch 020 - train 0.03244 | val 3.09372
  Epoch 021 - train 0.02195 | val 3.19465
  Classification -> best τ=0.490 (val F1=0.1316)
  Directional -> Accuracy: 0.6607, MCC: 0.3250, F1: 0.7077

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 106). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.21667 | val 2.88972
  Epoch 020 - train 0.00817 | val 6.09002
  Epoch 021 - train 0.00652 | val 6.15351
  Classification -> best τ=0.530 (val F1=0.0451)
  Directional -> Accuracy: 0.5306, MCC: 0.0743, F1: 0.2069

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 106). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.34736 | val 1.10237
  Epoch 020 - train 0.00591 | val 1.94566
  Epoch 023 - train 0.00324 | val 1.99923
  Classification -> best τ=0.610 (val F1=0.3841)
  Directional -> Accuracy: 0.4746, MCC: -0.0811, F1: 0.0606

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.27704 | val 0.70269
  Epoch 020 - train 0.02602 | val 1.01807
  Epoch 021 - train 0.01654 | val 0.99692
  Classification -> best τ=0.485 (val F1=0.2506)
  Directional -> Accuracy: 0.5600, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.36407 | val 1.28354
  Epoch 020 - train 0.02623 | val 2.28043
  Epoch 023 - train 0.00735 | val 2.51779
  Classification -> best τ=0.325 (val F1=0.3322)
  Directional -> Accuracy: 0.6176, MCC: 0.2411, F1: 0.7045

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 106). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.39684 | val 1.72678
  Epoch 020 - train 0.04141 | val 2.30071
  Epoch 021 - train 0.02412 | val 2.34020
  Classification -> best τ=0.650 (val F1=0.2739)
  Directional -> Accuracy: 0.3684, MCC: -0.1602, F1: 0.2174

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.30344 | val 1.64213
  Epoch 020 - train 0.02162 | val 4.52380
  Epoch 021 - train 0.01159 | val 4.76629
  Classification -> best τ=0.625 (val F1=0.1895)
  Directional -> Accuracy: 0.4189, MCC: 0.0302, F1: 0.0851

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.38714 | val 1.47603
  Epoch 020 - train 0.03201 | val 4.54729
  Epoch 021 - train 0.01746 | val 4.60409
  Classification -> best τ=0.360 (val F1=0.2503)
  Directional -> Accuracy: 0.5873, MCC: 0.1122, F1: 0.6829

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 106). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.42150 | val 0.91868
  Epoch 020 - train 0.06183 | val 1.56677
  Epoch 021 - train 0.05058 | val 1.64354
  Classification -> best τ=0.475 (val F1=0.3305)
  Directional -> Accuracy: 0.4384, MCC: -0.0781, F1: 0.1277

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.21510 | val 2.11040
  Epoch 020 - train 0.01152 | val 3.69804
  Epoch 021 - train 0.01065 | val 3.76648
  Classification -> best τ=0.425 (val F1=0.2759)
  Directional -> Accuracy: 0.6087, MCC: 0.0000, F1: 0.7568

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 106). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 106). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 106). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.25882 | val 1.62145
  Epoch 020 - train 0.00912 | val 2.83503
  Epoch 021 - train 0.00686 | val 2.85358
  Classification -> best τ=0.435 (val F1=0.1651)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.29496 | val 2.65650
  Epoch 020 - train 0.01001 | val 4.35375
  Epoch 021 - train 0.00798 | val 4.42224
  Classification -> best τ=0.595 (val F1=0.3267)
  Directional -> Accuracy: 0.5714, MCC: 0.1344, F1: 0.6129

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.41702 | val 1.27558
  Epoch 020 - train 0.03825 | val 3.76991
  Epoch 021 - train 0.02433 | val 3.99946
  Classification -> best τ=0.520 (val F1=0.1341)
  Directional -> Accuracy: 0.5469, MCC: 0.0700, F1: 0.2927

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.28259 | val 3.21678
  Epoch 020 - train 0.01562 | val 5.59178
  Epoch 021 - train 0.01185 | val 5.72987
  Classification -> best τ=0.580 (val F1=0.3494)
  Directional -> Accuracy: 0.4630, MCC: 0.0000, F1: 0.0000

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.26030 | val 1.42166
  Epoch 020 - train 0.01043 | val 2.42272
  Epoch 021 - train 0.00751 | val 2.46511
  Classification -> best τ=0.595 (val F1=0.1871)
  Directional -> Accuracy: 0.4186, MCC: -0.1146, F1: 0.4681

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.26706 | val 4.23331
  Epoch 020 - train 0.01605 | val 9.42247
  Epoch 022 - train 0.00913 | val 10.01791
  Classification -> best τ=0.480 (val F1=0.2972)
  Directional -> Accuracy: 0.4898, MCC: 0.2476, F1: 0.2424

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.44751 | val 0.86333
  Epoch 020 - train 0.04445 | val 2.18261
  Epoch 024 - train 0.01974 | val 2.58822
  Classification -> best τ=0.345 (val F1=0.2694)
  Directional -> Accuracy: 0.4909, MCC: 0.1773, F1: 0.1250

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.22008 | val 0.89672
  Epoch 020 - train 0.08127 | val 1.57172
  Epoch 023 - train 0.05455 | val 1.95468
  Classification -> best τ=0.570 (val F1=0.2097)
  Directional -> Accuracy: 0.5789, MCC: 0.1212, F1: 0.6800

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.31744 | val 1.09808
  Epoch 020 - train 0.01470 | val 2.07967
  Epoch 021 - train 0.01344 | val 2.11243
  Classification -> best τ=0.550 (val F1=0.3150)
  Directional -> Accuracy: 0.5122, MCC: 0.0176, F1: 0.4118

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.14759 | val 1.78263
  Epoch 020 - train 0.00436 | val 3.04915
  Epoch 021 - train 0.00377 | val 3.09073
  Classification -> best τ=0.705 (val F1=0.1336)
  Directional -> Accuracy: 0.3902, MCC: -0.1921, F1: 0.3243

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.28902 | val 1.51127
  Epoch 020 - train 0.01475 | val 2.81308
  Epoch 021 - train 0.01055 | val 2.85667
  Classification -> best τ=0.370 (val F1=0.1786)
  Directional -> Accuracy: 0.5208, MCC: 0.0000, F1: 0.6849

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.33330 | val 2.22366
  Epoch 020 - train 0.01358 | val 4.28819
  Epoch 021 - train 0.00914 | val 4.42676
  Classification -> best τ=0.450 (val F1=0.2954)
  Directional -> Accuracy: 0.4366, MCC: 0.0000, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 106). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.31658 | val 1.08030
  Epoch 020 - train 0.01609 | val 2.32341
  Epoch 022 - train 0.00915 | val 2.41584
  Classification -> best τ=0.615 (val F1=0.3363)
  Directional -> Accuracy: 0.5238, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for PCG (101 < 106). Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.42982 | val 0.99586
  Epoch 020 - train 0.07950 | val 1.57129
  Epoch 021 - train 0.05420 | val 1.60394
  Classification -> best τ=0.380 (val F1=0.3234)
  Directional -> Accuracy: 0.5846, MCC: 0.1134, F1: 0.6897

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.15524 | val 1.59887
  Epoch 020 - train 0.00427 | val 2.21604
  Epoch 021 - train 0.00363 | val 2.26510
  Classification -> best τ=0.535 (val F1=0.3216)
  Directional -> Accuracy: 0.6000, MCC: 0.2495, F1: 0.5000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.25590 | val 1.91113
  Epoch 020 - train 0.00809 | val 3.43217
  Epoch 021 - train 0.00605 | val 3.53639
  Classification -> best τ=0.415 (val F1=0.2544)
  Directional -> Accuracy: 0.5455, MCC: 0.1365, F1: 0.6032

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.26072 | val 2.47623
  Epoch 020 - train 0.01296 | val 3.88588
  Epoch 022 - train 0.00824 | val 4.10420
  Classification -> best τ=0.590 (val F1=0.2435)
  Directional -> Accuracy: 0.4889, MCC: 0.0921, F1: 0.4390

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 106). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 106). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 106). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 106). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.31267 | val 0.78794
  Epoch 020 - train 0.02420 | val 1.50976
  Epoch 024 - train 0.00691 | val 1.78282
  Classification -> best τ=0.620 (val F1=0.4256)
  Directional -> Accuracy: 0.3261, MCC: 0.0000, F1: 0.4918

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 106). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 106). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 106). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.34324 | val 2.56574
  Epoch 020 - train 0.06016 | val 5.19813
  Epoch 021 - train 0.03554 | val 5.56272
  Classification -> best τ=0.215 (val F1=0.2032)
  Directional -> Accuracy: 0.4932, MCC: 0.0000, F1: 0.6606

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 106). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 106). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 106). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 106). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.24108 | val 0.80750
  Epoch 020 - train 0.00716 | val 1.83056
  Epoch 026 - train 0.00203 | val 2.05141
  Classification -> best τ=0.550 (val F1=0.3720)
  Directional -> Accuracy: 0.5455, MCC: 0.1325, F1: 0.6667

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.23731 | val 0.94972
  Epoch 020 - train 0.01293 | val 1.72816
  Epoch 021 - train 0.00865 | val 1.77512
  Classification -> best τ=0.585 (val F1=0.1195)
  Directional -> Accuracy: 0.5854, MCC: 0.2059, F1: 0.5854

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.24395 | val 0.94346
  Epoch 020 - train 0.01703 | val 1.57685
  Epoch 021 - train 0.01409 | val 1.62247
  Classification -> best τ=0.705 (val F1=0.1548)
  Directional -> Accuracy: 0.3696, MCC: 0.0000, F1: 0.5397

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.36234 | val 2.79368
  Epoch 020 - train 0.03256 | val 6.86690
  Epoch 022 - train 0.01302 | val 7.22197
  Classification -> best τ=0.480 (val F1=0.2163)
  Directional -> Accuracy: 0.5741, MCC: 0.3000, F1: 0.4103

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.24845 | val 3.04159
  Epoch 020 - train 0.00433 | val 7.13606
  Epoch 021 - train 0.00356 | val 7.29684
  Classification -> best τ=0.555 (val F1=0.4399)
  Directional -> Accuracy: 0.4909, MCC: 0.0000, F1: 0.6585

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.32214 | val 1.12059
  Epoch 020 - train 0.01036 | val 1.76786
  Epoch 023 - train 0.00534 | val 1.90617
  Classification -> best τ=0.615 (val F1=0.2648)
  Directional -> Accuracy: 0.5962, MCC: 0.1960, F1: 0.6316


[I 2026-02-22 10:01:28,812] Trial 81 finished with value: 0.25334812971971643 and parameters: {'feature_set': 'sector_sentiment', 'model_type': 'GRU', 'sequence_length': 30, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 64, 'num_layers': 1, 'inter_rnn_drop': 0.1, 'dropout': 0.0, 'batch_size': 32, 'learning_rate': 0.005693929794653679, 'weight_decay': 2.8081127772991855e-06, 'lr_patience': 5, 'lr_factor': 0.8, 'early_stopping_patience': 20, 'max_epochs': 50, 'huber_delta': 0.9405332072086585, 'early_stopping_min_delta': 0.004982337467907028}. Best is trial 22 with value: 0.2833350641483003.

  Classification -> best τ=0.360 (val F1=0.2694)
  Directional -> Accuracy: 0.4576, MCC: -0.0915, F1: 0.4074

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.25334812971971643
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: classification
Sequence length: 30
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d', 'sentiment']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.43232 | val 1.21543
  Epoch 020 - train 0.22100 | val 1.85092
  Epoch 021 - train 0.19995 | val 2.07285
  Classification -> best τ=0.470 (val F1=0.2362)
  Directional -> Accuracy: 0.5867, MCC: 0.2463, F1: 0.6517

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 106). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.34360 | val 1.28811
  Epoch 020 - train 0.15920 | val 1.44064
  Epoch 021 - train 0.13464 | val 1.44813
  Classification -> best τ=0.430 (val F1=0.2042)
  Directional -> Accuracy: 0.5909, MCC: 0.0000, F1: 0.7429

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 106). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.37109 | val 1.45214
  Epoch 020 - train 0.16253 | val 2.17237
  Epoch 021 - train 0.14287 | val 2.36624
  Classification -> best τ=0.495 (val F1=0.3091)
  Directional -> Accuracy: 0.4889, MCC: 0.0223, F1: 0.3030

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.43529 | val 2.82441
  Epoch 020 - train 0.23752 | val 3.16372
  Epoch 021 - train 0.21277 | val 4.09775
  Classification -> best τ=0.375 (val F1=0.2100)
  Directional -> Accuracy: 0.5205, MCC: -0.0357, F1: 0.6729

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.40204 | val 1.17690
  Epoch 020 - train 0.17607 | val 2.24374
  Epoch 023 - train 0.12340 | val 2.15304
  Classification -> best τ=0.595 (val F1=0.3799)
  Directional -> Accuracy: 0.5510, MCC: 0.1264, F1: 0.4211

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.36534 | val 1.55108
  Epoch 020 - train 0.16039 | val 1.79714
  Epoch 021 - train 0.14413 | val 2.03024
  Classification -> best τ=0.445 (val F1=0.1787)
  Directional -> Accuracy: 0.4444, MCC: -0.1094, F1: 0.5098

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.43337 | val 1.23520
  Epoch 020 - train 0.19505 | val 2.23994
  Epoch 021 - train 0.16813 | val 1.93937
  Classification -> best τ=0.480 (val F1=0.1869)
  Directional -> Accuracy: 0.5373, MCC: 0.1036, F1: 0.5231

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 106). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 106). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.35204 | val 1.17132
  Epoch 020 - train 0.13908 | val 1.99460
  Epoch 023 - train 0.09759 | val 2.31255
  Classification -> best τ=0.555 (val F1=0.1741)
  Directional -> Accuracy: 0.4146, MCC: -0.1299, F1: 0.5000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.40622 | val 0.82938
  Epoch 020 - train 0.19513 | val 1.64735
  Epoch 026 - train 0.12202 | val 2.21470
  Classification -> best τ=0.560 (val F1=0.4394)
  Directional -> Accuracy: 0.6170, MCC: 0.2427, F1: 0.6087

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 106). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 106). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 106). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.37368 | val 1.93685
  Epoch 020 - train 0.15802 | val 3.04185
  Epoch 021 - train 0.13964 | val 3.39109
  Classification -> best τ=0.440 (val F1=0.2123)
  Directional -> Accuracy: 0.5000, MCC: 0.2429, F1: 0.6304

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.40804 | val 1.44211
  Epoch 020 - train 0.19820 | val 2.62634
  Epoch 021 - train 0.17947 | val 2.58136
  Classification -> best τ=0.515 (val F1=0.3037)
  Directional -> Accuracy: 0.5417, MCC: 0.1183, F1: 0.5926

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.40914 | val 2.81659
  Epoch 020 - train 0.16885 | val 3.52848
  Epoch 021 - train 0.13663 | val 3.93435
  Classification -> best τ=0.530 (val F1=0.0667)
  Directional -> Accuracy: 0.5893, MCC: 0.2874, F1: 0.7160

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 106). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.38005 | val 2.59411
  Epoch 020 - train 0.15658 | val 4.70972
  Epoch 021 - train 0.13783 | val 4.83411
  Classification -> best τ=0.360 (val F1=0.2788)
  Directional -> Accuracy: 0.5510, MCC: 0.1485, F1: 0.6562

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 106). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.43376 | val 0.88434
  Epoch 020 - train 0.17037 | val 1.47862
  Epoch 024 - train 0.10904 | val 1.43723
  Classification -> best τ=0.495 (val F1=0.3713)
  Directional -> Accuracy: 0.4915, MCC: -0.0057, F1: 0.1667

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.41947 | val 1.21303
  Epoch 020 - train 0.20300 | val 1.55477
  Epoch 022 - train 0.15907 | val 1.70743
  Classification -> best τ=0.620 (val F1=0.2550)
  Directional -> Accuracy: 0.5600, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.46938 | val 0.92836
  Epoch 020 - train 0.21209 | val 1.51691
  Epoch 021 - train 0.19591 | val 1.51234
  Classification -> best τ=0.455 (val F1=0.3005)
  Directional -> Accuracy: 0.5441, MCC: 0.0730, F1: 0.6869

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 106). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.42857 | val 1.87498
  Epoch 020 - train 0.20498 | val 2.73534
  Epoch 021 - train 0.19562 | val 2.65436
  Classification -> best τ=0.575 (val F1=0.2000)
  Directional -> Accuracy: 0.4035, MCC: 0.1059, F1: 0.0556

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.37695 | val 2.18866
  Epoch 020 - train 0.15220 | val 3.81632
  Epoch 021 - train 0.13844 | val 3.90328
  Classification -> best τ=0.445 (val F1=0.2204)
  Directional -> Accuracy: 0.4054, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.40149 | val 1.56225
  Epoch 020 - train 0.19305 | val 2.84624
  Epoch 021 - train 0.17754 | val 3.05421
  Classification -> best τ=0.555 (val F1=0.1853)
  Directional -> Accuracy: 0.4286, MCC: 0.0076, F1: 0.1429

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 106). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.42413 | val 1.28932
  Epoch 020 - train 0.25672 | val 1.74638
  Epoch 021 - train 0.24509 | val 2.37198
  Classification -> best τ=0.535 (val F1=0.3060)
  Directional -> Accuracy: 0.4658, MCC: 0.0494, F1: 0.0930

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.33533 | val 0.93454
  Epoch 020 - train 0.10016 | val 2.57726
  Epoch 021 - train 0.08949 | val 2.16065
  Classification -> best τ=0.495 (val F1=0.3644)
  Directional -> Accuracy: 0.3913, MCC: -0.0475, F1: 0.0667

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 106). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 106). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 106). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.35763 | val 1.12210
  Epoch 020 - train 0.12710 | val 1.83891
  Epoch 021 - train 0.10484 | val 2.09267
  Classification -> best τ=0.405 (val F1=0.2395)
  Directional -> Accuracy: 0.5469, MCC: 0.0949, F1: 0.5085

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.40026 | val 2.35902
  Epoch 020 - train 0.16337 | val 4.41974
  Epoch 021 - train 0.14664 | val 4.16747
  Classification -> best τ=0.525 (val F1=0.3571)
  Directional -> Accuracy: 0.5714, MCC: 0.0833, F1: 0.6757

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.41434 | val 1.59190
  Epoch 020 - train 0.19639 | val 2.26826
  Epoch 021 - train 0.18209 | val 2.10059
  Classification -> best τ=0.360 (val F1=0.1604)
  Directional -> Accuracy: 0.5312, MCC: 0.1304, F1: 0.6341

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.35848 | val 2.47309
  Epoch 020 - train 0.16705 | val 4.76027
  Epoch 022 - train 0.13314 | val 5.04343
  Classification -> best τ=0.590 (val F1=0.4553)
  Directional -> Accuracy: 0.4630, MCC: 0.0000, F1: 0.0000

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.43247 | val 0.90261
  Epoch 020 - train 0.25352 | val 1.61805
  Epoch 021 - train 0.23573 | val 1.81302
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4186, MCC: 0.0000, F1: 0.5902

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.40656 | val 1.08883
  Epoch 020 - train 0.18763 | val 2.30736
  Epoch 021 - train 0.17669 | val 2.63810
  Classification -> best τ=0.485 (val F1=0.1943)
  Directional -> Accuracy: 0.4898, MCC: 0.0470, F1: 0.4444

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.46423 | val 1.00057
  Epoch 020 - train 0.22579 | val 1.99445
  Epoch 022 - train 0.18792 | val 2.22907
  Classification -> best τ=0.495 (val F1=0.2224)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.39614 | val 0.75753
  Epoch 020 - train 0.20724 | val 0.92568
  Epoch 021 - train 0.19504 | val 0.93333
  Classification -> best τ=0.515 (val F1=0.2550)
  Directional -> Accuracy: 0.6053, MCC: 0.1910, F1: 0.7170

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.41758 | val 1.03290
  Epoch 020 - train 0.20088 | val 1.41819
  Epoch 021 - train 0.18454 | val 1.22902
  Classification -> best τ=0.525 (val F1=0.2706)
  Directional -> Accuracy: 0.5122, MCC: 0.0195, F1: 0.4444

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.40386 | val 1.10479
  Epoch 020 - train 0.16328 | val 2.24602
  Epoch 021 - train 0.14836 | val 2.31371
  Classification -> best τ=0.455 (val F1=0.2339)
  Directional -> Accuracy: 0.5366, MCC: -0.0096, F1: 0.6667

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.41041 | val 1.35925
  Epoch 020 - train 0.14880 | val 1.85586
  Epoch 022 - train 0.11633 | val 2.13749
  Classification -> best τ=0.695 (val F1=0.2949)
  Directional -> Accuracy: 0.4792, MCC: -0.0650, F1: 0.5763

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.39938 | val 1.88884
  Epoch 020 - train 0.19653 | val 2.84976
  Epoch 021 - train 0.17444 | val 3.17396
  Classification -> best τ=0.370 (val F1=0.2573)
  Directional -> Accuracy: 0.5070, MCC: 0.1231, F1: 0.3396

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 106). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.40476 | val 0.78918
  Epoch 020 - train 0.17267 | val 1.23342
  Epoch 021 - train 0.15909 | val 1.33560
  Classification -> best τ=0.445 (val F1=0.2675)
  Directional -> Accuracy: 0.4762, MCC: -0.0754, F1: 0.3125

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for PCG (101 < 106). Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.44499 | val 0.91659
  Epoch 020 - train 0.23365 | val 1.08237
  Epoch 021 - train 0.20941 | val 1.13835
  Classification -> best τ=0.375 (val F1=0.3504)
  Directional -> Accuracy: 0.5538, MCC: 0.2848, F1: 0.3830

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.36548 | val 1.18421
  Epoch 020 - train 0.15323 | val 1.46133
  Epoch 021 - train 0.14022 | val 1.47953
  Classification -> best τ=0.455 (val F1=0.3290)
  Directional -> Accuracy: 0.7000, MCC: 0.4127, F1: 0.6842

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.41086 | val 1.56071
  Epoch 020 - train 0.19414 | val 2.78902
  Epoch 021 - train 0.18259 | val 2.96008
  Classification -> best τ=0.480 (val F1=0.2089)
  Directional -> Accuracy: 0.5091, MCC: 0.0671, F1: 0.5846

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.33880 | val 3.47585
  Epoch 020 - train 0.15853 | val 5.03728
  Epoch 021 - train 0.14226 | val 4.98701
  Classification -> best τ=0.560 (val F1=0.2626)
  Directional -> Accuracy: 0.4889, MCC: 0.1232, F1: 0.4103

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 106). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 106). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 106). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 106). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.42880 | val 0.63254
  Epoch 020 - train 0.21268 | val 0.86087
  Epoch 028 - train 0.10275 | val 1.14691
  Classification -> best τ=0.700 (val F1=0.4385)
  Directional -> Accuracy: 0.3913, MCC: -0.0449, F1: 0.4400

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 106). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 106). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 106). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.40761 | val 1.82085
  Epoch 020 - train 0.19727 | val 3.38329
  Epoch 021 - train 0.17615 | val 3.52130
  Classification -> best τ=0.485 (val F1=0.2561)
  Directional -> Accuracy: 0.4932, MCC: 0.0000, F1: 0.6606

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 106). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 106). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 106). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 106). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.40301 | val 0.91826
  Epoch 020 - train 0.11881 | val 0.94578
  Epoch 029 - train 0.03456 | val 1.19640
  Classification -> best τ=0.570 (val F1=0.3064)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6562

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.45305 | val 0.78805
  Epoch 020 - train 0.25392 | val 0.78133
  Epoch 021 - train 0.24043 | val 0.78979
  Classification -> best τ=0.530 (val F1=0.0989)
  Directional -> Accuracy: 0.4878, MCC: 0.0049, F1: 0.4878

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.42551 | val 0.84976
  Epoch 020 - train 0.23653 | val 1.14122
  Epoch 021 - train 0.22596 | val 1.08048
  Classification -> best τ=0.470 (val F1=0.0608)
  Directional -> Accuracy: 0.3696, MCC: 0.0000, F1: 0.5397

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.41792 | val 1.93748
  Epoch 020 - train 0.20413 | val 3.93870
  Epoch 021 - train 0.18565 | val 3.85204
  Classification -> best τ=0.440 (val F1=0.1683)
  Directional -> Accuracy: 0.6296, MCC: 0.2652, F1: 0.6429

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.35711 | val 3.79227
  Epoch 020 - train 0.13720 | val 5.82408
  Epoch 021 - train 0.11932 | val 6.19806
  Classification -> best τ=0.570 (val F1=0.2617)
  Directional -> Accuracy: 0.4909, MCC: 0.0000, F1: 0.6585

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.49157 | val 0.71784
  Epoch 020 - train 0.16779 | val 1.27325
  Epoch 024 - train 0.10233 | val 1.42352
  Classification -> best τ=0.515 (val F1=0.3230)
  Directional -> Accuracy: 0.5769, MCC: 0.1581, F1: 0.6207

[87/88] Processing WMT...


[I 2026-02-22 10:02:44,744] Trial 82 finished with value: 0.2500239313152528 and parameters: {'feature_set': 'sector_sentiment', 'model_type': 'GRU', 'sequence_length': 30, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 64, 'num_layers': 1, 'inter_rnn_drop': 0.1, 'dropout': 0.0, 'batch_size': 32, 'learning_rate': 0.0014485621952367263, 'weight_decay': 7.151632619742026e-06, 'lr_patience': 5, 'lr_factor': 0.8, 'early_stopping_patience': 20, 'max_epochs': 50, 'huber_delta': 1.4634192360248488, 'early_stopping_min_delta': 0.004739451606866465}. Best is trial 22 with value: 0.2833350641483003.

  Epoch 020 - train 0.21611 | val 2.43024
  Epoch 021 - train 0.19406 | val 2.37005
  Classification -> best τ=0.470 (val F1=0.1479)
  Directional -> Accuracy: 0.4068, MCC: -0.1812, F1: 0.4928

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2500239313152528
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: classification
Sequence length: 30
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d', 'sentiment']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.46435 | val 0.87369
  Epoch 020 - train 0.09542 | val 1.95249
  Epoch 022 - train 0.05898 | val 1.98993
  Classification -> best τ=0.640 (val F1=0.2989)
  Directional -> Accuracy: 0.5600, MCC: 0.1019, F1: 0.4762

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 106). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.26801 | val 0.96541
  Epoch 020 - train 0.03229 | val 1.63667
  Epoch 021 - train 0.02651 | val 1.64257
  Classification -> best τ=0.550 (val F1=0.2503)
  Directional -> Accuracy: 0.5455, MCC: 0.1282, F1: 0.5455

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 106). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.24097 | val 2.64491
  Epoch 020 - train 0.01529 | val 4.28039
  Epoch 021 - train 0.01041 | val 4.32968
  Classification -> best τ=0.615 (val F1=0.2641)
  Directional -> Accuracy: 0.4667, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.38123 | val 1.69226
  Epoch 020 - train 0.06037 | val 3.43344
  Epoch 021 - train 0.04868 | val 4.09908
  Classification -> best τ=0.445 (val F1=0.1892)
  Directional -> Accuracy: 0.5342, MCC: 0.1350, F1: 0.3704

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.31400 | val 0.77103
  Epoch 020 - train 0.01039 | val 1.35482
  Epoch 024 - train 0.00489 | val 1.44173
  Classification -> best τ=0.605 (val F1=0.4805)
  Directional -> Accuracy: 0.5918, MCC: 0.2539, F1: 0.4118

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.23748 | val 1.69989
  Epoch 020 - train 0.03204 | val 1.86395
  Epoch 022 - train 0.01868 | val 1.95751
  Classification -> best τ=0.515 (val F1=0.2294)
  Directional -> Accuracy: 0.5111, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.35903 | val 1.98254
  Epoch 020 - train 0.03471 | val 3.25309
  Epoch 021 - train 0.02132 | val 3.39121
  Classification -> best τ=0.445 (val F1=0.1186)
  Directional -> Accuracy: 0.4030, MCC: 0.0000, F1: 0.5745

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 106). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 106). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.23004 | val 1.27277
  Epoch 020 - train 0.01056 | val 2.07028
  Epoch 024 - train 0.00466 | val 2.29581
  Classification -> best τ=0.520 (val F1=0.2041)
  Directional -> Accuracy: 0.5122, MCC: 0.1129, F1: 0.6000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.30565 | val 1.75066
  Epoch 020 - train 0.05094 | val 3.35565
  Epoch 024 - train 0.02053 | val 3.78969
  Classification -> best τ=0.660 (val F1=0.4444)
  Directional -> Accuracy: 0.6383, MCC: 0.3394, F1: 0.3200

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 106). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 106). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 106). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.33150 | val 3.18906
  Epoch 020 - train 0.04269 | val 5.93714
  Epoch 021 - train 0.02728 | val 6.45470
  Classification -> best τ=0.335 (val F1=0.1222)
  Directional -> Accuracy: 0.4265, MCC: 0.0000, F1: 0.5979

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.30807 | val 1.93072
  Epoch 020 - train 0.03791 | val 3.75751
  Epoch 021 - train 0.02990 | val 3.87052
  Classification -> best τ=0.670 (val F1=0.2277)
  Directional -> Accuracy: 0.5833, MCC: 0.1496, F1: 0.3333

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.29726 | val 2.64274
  Epoch 020 - train 0.04034 | val 4.41976
  Epoch 021 - train 0.03121 | val 4.55532
  Classification -> best τ=0.685 (val F1=0.1255)
  Directional -> Accuracy: 0.5357, MCC: 0.1486, F1: 0.2778

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 106). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.28025 | val 3.01859
  Epoch 020 - train 0.02138 | val 6.57344
  Epoch 021 - train 0.01708 | val 6.61214
  Classification -> best τ=0.325 (val F1=0.1945)
  Directional -> Accuracy: 0.4898, MCC: 0.0000, F1: 0.6575

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 106). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.33182 | val 0.71727
  Epoch 020 - train 0.01957 | val 1.24172
  Epoch 022 - train 0.01147 | val 1.27900
  Classification -> best τ=0.510 (val F1=0.4093)
  Directional -> Accuracy: 0.4915, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.31141 | val 1.07497
  Epoch 020 - train 0.04460 | val 1.92855
  Epoch 022 - train 0.02645 | val 1.75188
  Classification -> best τ=0.545 (val F1=0.2550)
  Directional -> Accuracy: 0.5600, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.40935 | val 1.09106
  Epoch 020 - train 0.08685 | val 2.18725
  Epoch 023 - train 0.03964 | val 2.62430
  Classification -> best τ=0.705 (val F1=0.2583)
  Directional -> Accuracy: 0.5588, MCC: 0.2251, F1: 0.3478

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 106). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.36733 | val 2.27070
  Epoch 020 - train 0.05202 | val 3.73993
  Epoch 021 - train 0.03405 | val 3.81244
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.6140, MCC: 0.0000, F1: 0.7609

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.32700 | val 1.76361
  Epoch 020 - train 0.03383 | val 3.83463
  Epoch 021 - train 0.02496 | val 4.12432
  Classification -> best τ=0.590 (val F1=0.1895)
  Directional -> Accuracy: 0.4054, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.34888 | val 1.75872
  Epoch 020 - train 0.02848 | val 3.51348
  Epoch 022 - train 0.01672 | val 3.77740
  Classification -> best τ=0.295 (val F1=0.2503)
  Directional -> Accuracy: 0.5397, MCC: 0.2424, F1: 0.4082

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 106). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.36424 | val 1.35640
  Epoch 020 - train 0.08408 | val 2.14357
  Epoch 021 - train 0.05913 | val 1.84558
  Classification -> best τ=0.495 (val F1=0.3304)
  Directional -> Accuracy: 0.4658, MCC: 0.0494, F1: 0.0930

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.19375 | val 1.91380
  Epoch 020 - train 0.01521 | val 2.85309
  Epoch 021 - train 0.01298 | val 3.02055
  Classification -> best τ=0.430 (val F1=0.2759)
  Directional -> Accuracy: 0.5000, MCC: 0.0826, F1: 0.4651

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 106). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 106). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 106). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.27031 | val 1.57538
  Epoch 020 - train 0.01883 | val 2.77358
  Epoch 021 - train 0.01177 | val 2.83596
  Classification -> best τ=0.560 (val F1=0.1372)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.30506 | val 3.91878
  Epoch 020 - train 0.03553 | val 5.76003
  Epoch 021 - train 0.03790 | val 6.15108
  Classification -> best τ=0.700 (val F1=0.3062)
  Directional -> Accuracy: 0.5536, MCC: 0.1362, F1: 0.5455

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.35545 | val 1.50719
  Epoch 020 - train 0.05771 | val 3.55244
  Epoch 021 - train 0.04086 | val 3.70734
  Classification -> best τ=0.365 (val F1=0.1341)
  Directional -> Accuracy: 0.5781, MCC: 0.1745, F1: 0.6087

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.25196 | val 2.42073
  Epoch 020 - train 0.03765 | val 4.31873
  Epoch 021 - train 0.03386 | val 4.24863
  Classification -> best τ=0.590 (val F1=0.3669)
  Directional -> Accuracy: 0.5000, MCC: 0.0736, F1: 0.2703

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.31112 | val 1.55329
  Epoch 020 - train 0.06384 | val 2.90120
  Epoch 021 - train 0.05139 | val 3.00568
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4186, MCC: 0.0000, F1: 0.5902

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.30166 | val 1.57944
  Epoch 020 - train 0.04179 | val 5.16037
  Epoch 022 - train 0.02547 | val 4.81379
  Classification -> best τ=0.500 (val F1=0.1845)
  Directional -> Accuracy: 0.5918, MCC: 0.1987, F1: 0.6154

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.38966 | val 0.98199
  Epoch 020 - train 0.05180 | val 1.66200
  Epoch 021 - train 0.03556 | val 1.72398
  Classification -> best τ=0.420 (val F1=0.3586)
  Directional -> Accuracy: 0.4727, MCC: 0.1242, F1: 0.0645

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.23783 | val 0.77870
  Epoch 020 - train 0.05908 | val 1.40236
  Epoch 025 - train 0.02472 | val 2.12415
  Classification -> best τ=0.470 (val F1=0.2955)
  Directional -> Accuracy: 0.5526, MCC: 0.0458, F1: 0.6792

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.24871 | val 1.57514
  Epoch 020 - train 0.02466 | val 2.62047
  Epoch 021 - train 0.02043 | val 2.74872
  Classification -> best τ=0.605 (val F1=0.3150)
  Directional -> Accuracy: 0.4634, MCC: -0.1111, F1: 0.2143

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.23348 | val 2.29652
  Epoch 020 - train 0.01442 | val 4.62196
  Epoch 021 - train 0.01189 | val 4.68606
  Classification -> best τ=0.610 (val F1=0.1053)
  Directional -> Accuracy: 0.5366, MCC: -0.0096, F1: 0.6667

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.31045 | val 1.40197
  Epoch 020 - train 0.02646 | val 2.76462
  Epoch 022 - train 0.01893 | val 2.88242
  Classification -> best τ=0.305 (val F1=0.2710)
  Directional -> Accuracy: 0.5208, MCC: 0.0000, F1: 0.6849

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.35627 | val 1.68589
  Epoch 020 - train 0.03072 | val 4.19505
  Epoch 021 - train 0.02136 | val 4.37903
  Classification -> best τ=0.400 (val F1=0.2319)
  Directional -> Accuracy: 0.5070, MCC: 0.1231, F1: 0.3396

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 106). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.30529 | val 1.01843
  Epoch 020 - train 0.01643 | val 3.18675
  Epoch 021 - train 0.01315 | val 3.32316
  Classification -> best τ=0.485 (val F1=0.3367)
  Directional -> Accuracy: 0.5476, MCC: 0.0830, F1: 0.3448

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for PCG (101 < 106). Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.35139 | val 1.25895
  Epoch 020 - train 0.05358 | val 1.95878
  Epoch 021 - train 0.03582 | val 1.99602
  Classification -> best τ=0.410 (val F1=0.3218)
  Directional -> Accuracy: 0.5538, MCC: 0.0557, F1: 0.6506

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.23503 | val 1.14962
  Epoch 020 - train 0.01337 | val 1.97052
  Epoch 021 - train 0.01060 | val 1.98041
  Classification -> best τ=0.400 (val F1=0.3780)
  Directional -> Accuracy: 0.7000, MCC: 0.3985, F1: 0.7143

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.30715 | val 1.74933
  Epoch 020 - train 0.02362 | val 3.97365
  Epoch 021 - train 0.01763 | val 4.13789
  Classification -> best τ=0.430 (val F1=0.2494)
  Directional -> Accuracy: 0.4727, MCC: -0.0404, F1: 0.4912

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.24794 | val 3.05489
  Epoch 020 - train 0.02800 | val 4.40568
  Epoch 022 - train 0.01967 | val 4.62243
  Classification -> best τ=0.530 (val F1=0.3714)
  Directional -> Accuracy: 0.5556, MCC: 0.1202, F1: 0.6000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 106). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 106). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 106). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 106). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.34439 | val 0.80686
  Epoch 020 - train 0.07277 | val 1.46579
  Epoch 026 - train 0.01453 | val 1.63384
  Classification -> best τ=0.655 (val F1=0.4385)
  Directional -> Accuracy: 0.4783, MCC: 0.0184, F1: 0.4286

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 106). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 106). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 106). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.33339 | val 2.03840
  Epoch 020 - train 0.06734 | val 4.98220
  Epoch 021 - train 0.04482 | val 5.21727
  Classification -> best τ=0.340 (val F1=0.2464)
  Directional -> Accuracy: 0.4932, MCC: 0.0000, F1: 0.6606

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 106). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 106). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 106). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 106). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.25401 | val 1.20895
  Epoch 020 - train 0.01427 | val 2.39812
  Epoch 022 - train 0.00860 | val 2.52887
  Classification -> best τ=0.555 (val F1=0.3720)
  Directional -> Accuracy: 0.5455, MCC: 0.0925, F1: 0.5000

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.36154 | val 0.83781
  Epoch 020 - train 0.06539 | val 1.33694
  Epoch 021 - train 0.05452 | val 1.38097
  Classification -> best τ=0.575 (val F1=0.1917)
  Directional -> Accuracy: 0.5854, MCC: 0.1386, F1: 0.6531

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.25884 | val 0.99727
  Epoch 020 - train 0.03171 | val 2.04215
  Epoch 021 - train 0.02521 | val 2.07660
  Classification -> best τ=0.535 (val F1=0.0422)
  Directional -> Accuracy: 0.3696, MCC: 0.0000, F1: 0.5397

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.33547 | val 2.68505
  Epoch 020 - train 0.03916 | val 5.89148
  Epoch 021 - train 0.02968 | val 6.03976
  Classification -> best τ=0.585 (val F1=0.2011)
  Directional -> Accuracy: 0.4444, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.24777 | val 3.82361
  Epoch 020 - train 0.01346 | val 6.80306
  Epoch 021 - train 0.01085 | val 6.97077
  Classification -> best τ=0.540 (val F1=0.3630)
  Directional -> Accuracy: 0.4909, MCC: 0.0000, F1: 0.6585

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.28639 | val 0.87105
  Epoch 020 - train 0.01909 | val 1.51538
  Epoch 023 - train 0.00937 | val 1.64813
  Classification -> best τ=0.595 (val F1=0.3517)

[I 2026-02-22 10:03:59,732] Trial 83 finished with value: 0.25576840895459957 and parameters: {'feature_set': 'sector_sentiment', 'model_type': 'GRU', 'sequence_length': 30, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 64, 'num_layers': 1, 'inter_rnn_drop': 0.1, 'dropout': 0.0, 'batch_size': 32, 'learning_rate': 0.0037652888366900552, 'weight_decay': 3.4286861811824353e-06, 'lr_patience': 5, 'lr_factor': 0.8, 'early_stopping_patience': 20, 'max_epochs': 50, 'huber_delta': 1.418454904120845, 'early_stopping_min_delta': 0.003551018825274189}. Best is trial 22 with value: 0.2833350641483003.

  Classification -> best τ=0.395 (val F1=0.3019)
  Directional -> Accuracy: 0.4915, MCC: 0.0655, F1: 0.6429

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.25576840895459957
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: classification
Sequence length: 36
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d', 'emotion_anger', 'emotion_disgust', 'emotion_fear', 'emotion_joy', 'emotion_neutral', 'emotion_sadness', 'emotion_surprize', 'emotion_anger_pct', 'emotion_disgust_pct', 'emotion_fear_pct', 'emotion_joy_pct', 'emotion_neutral_pct', 'emotion_sadness_pct', 'emotion_surprize_pct']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.16157 | val 2.90145
  Epoch 020 - train 0.00295 | val 2.77779
  Epoch 021 - train 0.00244 | val 2.80507
  Classification -> best τ=0.505 (val F1=0.1974)
  Directional -> Accuracy: 0.6081, MCC: 0.2047, F1: 0.5538

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 112). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.08835 | val 2.31835
  Epoch 020 - train 0.00182 | val 4.42381
  Epoch 021 - train 0.00157 | val 4.47841
  Classification -> best τ=0.680 (val F1=0.1734)
  Directional -> Accuracy: 0.4651, MCC: 0.0989, F1: 0.3030

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for AEP (109 < 112). Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 112). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.04612 | val 4.75691
  Epoch 020 - train 0.00083 | val 6.21132
  Epoch 021 - train 0.00077 | val 6.23740
  Classification -> best τ=0.695 (val F1=0.2703)
  Directional -> Accuracy: 0.4545, MCC: -0.1596, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.39237 | val 0.83404
  Epoch 020 - train 0.04739 | val 2.44804
  Epoch 023 - train 0.01085 | val 3.22711
  Classification -> best τ=0.470 (val F1=0.2265)
  Directional -> Accuracy: 0.5556, MCC: 0.0777, F1: 0.6981

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.06191 | val 1.67504
  Epoch 020 - train 0.00083 | val 2.78751
  Epoch 021 - train 0.00077 | val 2.81336
  Classification -> best τ=0.455 (val F1=0.4266)
  Directional -> Accuracy: 0.6458, MCC: 0.3244, F1: 0.5854

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.09163 | val 1.47914
  Epoch 020 - train 0.00097 | val 2.36124
  Epoch 022 - train 0.00078 | val 2.41542
  Classification -> best τ=0.420 (val F1=0.2350)
  Directional -> Accuracy: 0.5227, MCC: 0.0621, F1: 0.2759

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.20986 | val 1.05521
  Epoch 020 - train 0.00160 | val 2.08909
  Epoch 023 - train 0.00112 | val 2.13558
  Classification -> best τ=0.400 (val F1=0.2649)
  Directional -> Accuracy: 0.5455, MCC: 0.1282, F1: 0.5455

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 112). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 112). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.05227 | val 2.78361
  Epoch 020 - train 0.00094 | val 6.58749
  Epoch 022 - train 0.00062 | val 6.62883
  Classification -> best τ=0.630 (val F1=0.1925)
  Directional -> Accuracy: 0.4103, MCC: -0.1322, F1: 0.5106

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.01917 | val 1.45916
  Epoch 020 - train 0.00053 | val 1.75538
  Epoch 022 - train 0.00047 | val 1.77232
  Classification -> best τ=0.545 (val F1=0.3564)
  Directional -> Accuracy: 0.6087, MCC: 0.2431, F1: 0.1818

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 112). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 112). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 112). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.14611 | val 1.24037
  Epoch 020 - train 0.00162 | val 2.12190
  Epoch 022 - train 0.00121 | val 2.14856
  Classification -> best τ=0.340 (val F1=0.1948)
  Directional -> Accuracy: 0.4478, MCC: 0.0538, F1: 0.5843

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.09596 | val 2.42326
  Epoch 020 - train 0.00160 | val 3.71155
  Epoch 022 - train 0.00115 | val 3.82748
  Classification -> best τ=0.595 (val F1=0.0645)
  Directional -> Accuracy: 0.4043, MCC: -0.1608, F1: 0.5000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.06971 | val 2.58545
  Epoch 020 - train 0.00126 | val 3.51795
  Epoch 022 - train 0.00087 | val 3.58592
  Classification -> best τ=0.745 (val F1=0.2359)
  Directional -> Accuracy: 0.4727, MCC: -0.0106, F1: 0.0645

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 112). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.04681 | val 3.47300
  Epoch 020 - train 0.00094 | val 4.97565
  Epoch 022 - train 0.00078 | val 5.05971
  Classification -> best τ=0.555 (val F1=0.1328)
  Directional -> Accuracy: 0.3750, MCC: -0.2489, F1: 0.4444

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 112). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.23641 | val 1.01913
  Epoch 020 - train 0.00151 | val 1.47957
  Epoch 022 - train 0.00120 | val 1.50355
  Classification -> best τ=0.595 (val F1=0.3100)
  Directional -> Accuracy: 0.4828, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.21955 | val 2.71062
  Epoch 020 - train 0.00191 | val 4.58530
  Epoch 023 - train 0.00125 | val 4.64844
  Classification -> best τ=0.550 (val F1=0.2359)
  Directional -> Accuracy: 0.5510, MCC: 0.0212, F1: 0.0833

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.20457 | val 1.47340
  Epoch 020 - train 0.00293 | val 2.42813
  Epoch 021 - train 0.00244 | val 2.46257
  Classification -> best τ=0.470 (val F1=0.2203)
  Directional -> Accuracy: 0.5373, MCC: 0.0000, F1: 0.6990

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 112). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.15986 | val 2.73540
  Epoch 020 - train 0.00242 | val 5.36384
  Epoch 021 - train 0.00206 | val 5.43932
  Classification -> best τ=0.495 (val F1=0.1204)
  Directional -> Accuracy: 0.6071, MCC: 0.0000, F1: 0.7556

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.16461 | val 2.24855
  Epoch 020 - train 0.00336 | val 3.19422
  Epoch 021 - train 0.00254 | val 3.26897
  Classification -> best τ=0.625 (val F1=0.1041)
  Directional -> Accuracy: 0.4110, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.16767 | val 2.41673
  Epoch 020 - train 0.00168 | val 3.53970
  Epoch 021 - train 0.00140 | val 3.58491
  Classification -> best τ=0.460 (val F1=0.1738)
  Directional -> Accuracy: 0.5000, MCC: 0.1166, F1: 0.3673

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 112). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.35282 | val 0.92540
  Epoch 020 - train 0.05207 | val 1.54884
  Epoch 023 - train 0.01984 | val 1.76194
  Classification -> best τ=0.430 (val F1=0.2309)
  Directional -> Accuracy: 0.4583, MCC: 0.1061, F1: 0.0488

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.04299 | val 2.82352
  Epoch 020 - train 0.00088 | val 4.30621
  Epoch 021 - train 0.00081 | val 4.33348
  Classification -> best τ=0.635 (val F1=0.2794)
  Directional -> Accuracy: 0.4889, MCC: 0.0588, F1: 0.4390

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 112). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 112). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 112). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.12445 | val 1.98663
  Epoch 020 - train 0.00127 | val 2.83780
  Epoch 022 - train 0.00105 | val 2.88766
  Classification -> best τ=0.420 (val F1=0.2483)
  Directional -> Accuracy: 0.4921, MCC: -0.0041, F1: 0.6444

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.09792 | val 1.88174
  Epoch 020 - train 0.00129 | val 3.35390
  Epoch 021 - train 0.00114 | val 3.37370
  Classification -> best τ=0.535 (val F1=0.2368)
  Directional -> Accuracy: 0.5455, MCC: 0.0952, F1: 0.5763

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.14185 | val 2.05883
  Epoch 020 - train 0.00184 | val 3.76970
  Epoch 021 - train 0.00157 | val 3.83705
  Classification -> best τ=0.435 (val F1=0.1672)
  Directional -> Accuracy: 0.4762, MCC: 0.0000, F1: 0.6452

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.14654 | val 2.52283
  Epoch 020 - train 0.00125 | val 3.52406
  Epoch 022 - train 0.00101 | val 3.58613
  Classification -> best τ=0.510 (val F1=0.3053)
  Directional -> Accuracy: 0.5472, MCC: 0.2095, F1: 0.3684

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.01407 | val 2.17741
  Epoch 020 - train 0.00054 | val 3.01243
  Epoch 021 - train 0.00050 | val 3.03113
  Classification -> best τ=0.570 (val F1=0.0144)
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.03906 | val 1.18263
  Epoch 020 - train 0.00041 | val 1.68747
  Epoch 026 - train 0.00025 | val 1.76100
  Classification -> best τ=0.600 (val F1=0.3199)
  Directional -> Accuracy: 0.4792, MCC: 0.0228, F1: 0.4186

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.15503 | val 2.21499
  Epoch 020 - train 0.00219 | val 3.56332
  Epoch 021 - train 0.00170 | val 3.60137
  Classification -> best τ=0.515 (val F1=0.1288)
  Directional -> Accuracy: 0.4630, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
Insufficient data for proper time series validation for MDT. Skipping...

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.10657 | val 2.92159
  Epoch 020 - train 0.00165 | val 4.08381
  Epoch 022 - train 0.00125 | val 4.18348
  Classification -> best τ=0.800 (val F1=0.3133)
  Directional -> Accuracy: 0.4750, MCC: -0.0658, F1: 0.2222

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.04841 | val 2.11622
  Epoch 020 - train 0.00089 | val 3.00683
  Epoch 022 - train 0.00075 | val 3.02601
  Classification -> best τ=0.545 (val F1=0.2482)
  Directional -> Accuracy: 0.4750, MCC: -0.1521, F1: 0.6182

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.10143 | val 2.86308
  Epoch 020 - train 0.00146 | val 4.46400
  Epoch 021 - train 0.00124 | val 4.53413
  Classification -> best τ=0.550 (val F1=0.3419)
  Directional -> Accuracy: 0.5319, MCC: 0.2064, F1: 0.1538

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.23386 | val 1.72150
  Epoch 020 - train 0.00233 | val 2.87897
  Epoch 022 - train 0.00159 | val 2.97021
  Classification -> best τ=0.430 (val F1=0.1955)
  Directional -> Accuracy: 0.5571, MCC: 0.0000, F1: 0.7156

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 112). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.09436 | val 2.65105
  Epoch 020 - train 0.00068 | val 3.79221
  Epoch 023 - train 0.00048 | val 3.85955
  Classification -> best τ=0.565 (val F1=0.3898)
  Directional -> Accuracy: 0.6327, MCC: 0.2586, F1: 0.5714

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for PCG (101 < 112). Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.35927 | val 2.87922
  Epoch 020 - train 0.00558 | val 2.84917
  Epoch 021 - train 0.00423 | val 2.95897
  Classification -> best τ=0.240 (val F1=0.3587)
  Directional -> Accuracy: 0.6406, MCC: 0.2797, F1: 0.6667

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.01827 | val 2.23940
  Epoch 020 - train 0.00055 | val 3.33457
  Epoch 022 - train 0.00042 | val 3.34116
  Classification -> best τ=0.390 (val F1=0.3286)
  Directional -> Accuracy: 0.6122, MCC: 0.2293, F1: 0.5366

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.11797 | val 3.16333
  Epoch 020 - train 0.00127 | val 3.82601
  Epoch 021 - train 0.00111 | val 3.86324
  Classification -> best τ=0.760 (val F1=0.2277)
  Directional -> Accuracy: 0.5556, MCC: 0.0991, F1: 0.1429

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.05221 | val 2.43902
  Epoch 020 - train 0.00092 | val 3.38490
  Epoch 021 - train 0.00084 | val 3.40789
  Classification -> best τ=0.450 (val F1=0.2023)
  Directional -> Accuracy: 0.3864, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 112). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for PPL (108 < 112). Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 112). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 112). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 112). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.07983 | val 1.10751
  Epoch 020 - train 0.00106 | val 1.30900
  Epoch 023 - train 0.00069 | val 1.33016
  Classification -> best τ=0.485 (val F1=0.2365)
  Directional -> Accuracy: 0.5778, MCC: -0.1387, F1: 0.0952

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 112). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 112). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 112). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.18960 | val 2.93101
  Epoch 020 - train 0.00362 | val 5.25135
  Epoch 022 - train 0.00230 | val 5.33896
  Classification -> best τ=0.225 (val F1=0.1155)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 112). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 112). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 112). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 112). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.07359 | val 1.80066
  Epoch 020 - train 0.00072 | val 2.27654
  Epoch 021 - train 0.00066 | val 2.28340
  Classification -> best τ=0.635 (val F1=0.3177)
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.0000

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.04447 | val 1.39525
  Epoch 020 - train 0.00079 | val 1.84846
  Epoch 021 - train 0.00069 | val 1.87280
  Classification -> best τ=0.505 (val F1=0.1608)
  Directional -> Accuracy: 0.5128, MCC: 0.1655, F1: 0.3871

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.05813 | val 1.41425
  Epoch 020 - train 0.00076 | val 2.33950
  Epoch 021 - train 0.00069 | val 2.35899
  Classification -> best τ=0.450 (val F1=0.2193)
  Directional -> Accuracy: 0.3778, MCC: 0.0000, F1: 0.5484

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.07755 | val 1.88716
  Epoch 020 - train 0.00086 | val 2.22757
  Epoch 022 - train 0.00068 | val 2.27082
  Classification -> best τ=0.790 (val F1=0.2315)
  Directional -> Accuracy: 0.4528, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.06525 | val 3.61436
  Epoch 020 - train 0.00057 | val 5.56517
  Epoch 021 - train 0.00053 | val 5.60255
  Classification -> best τ=0.515 (val F1=0.3305)
  Directional -> Accuracy: 0.5185, MCC: 0.0371, F1: 0.5000

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.11125 | val 2.19669
  Epoch 020 - train 0.00118 | val 4.18664
  Epoch 022 - train 0.00099 | val 4.25762
  Classification -> best τ=0.325 (val F1=0.1690)

[I 2026-02-22 10:05:41,240] Trial 84 finished with value: 0.23857586172554854 and parameters: {'feature_set': 'sector_emotion', 'model_type': 'GRU', 'sequence_length': 36, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 64, 'num_layers': 1, 'inter_rnn_drop': 0.0, 'dropout': 0.0, 'batch_size': 32, 'learning_rate': 0.009968975487285538, 'weight_decay': 1.0448666083621714e-05, 'lr_patience': 5, 'lr_factor': 0.8, 'early_stopping_patience': 20, 'max_epochs': 50, 'huber_delta': 1.5717224695531544, 'early_stopping_min_delta': 0.0011916274098350426}. Best is trial 22 with value: 0.2833350641483003.

  Epoch 027 - train 0.00101 | val 2.68596
  Classification -> best τ=0.735 (val F1=0.4810)
  Directional -> Accuracy: 0.5172, MCC: -0.1236, F1: 0.0000

================================================================================
Pipeline completed: 47/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (47, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.23857586172554854
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 30
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d', 'sentiment']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.35995 | val 1.22958
  Epoch 020 - train 0.17178 | val 2.86499
  Epoch 021 - train 0.13691 | val 3.03705
  Classification -> best τ=0.595 (val F1=0.2571)
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.0000

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 106). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.23645 | val 0.95691
  Epoch 020 - train 0.06300 | val 0.99578
  Epoch 021 - train 0.05891 | val 1.07125
  Classification -> best τ=0.525 (val F1=0.1749)
  Directional -> Accuracy: 0.6818, MCC: 0.3208, F1: 0.7586

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 106). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.25835 | val 1.89172
  Epoch 020 - train 0.07540 | val 2.97018
  Epoch 021 - train 0.06357 | val 3.25918
  Classification -> best τ=0.560 (val F1=0.3086)
  Directional -> Accuracy: 0.4667, MCC: -0.0144, F1: 0.0769

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.44726 | val 1.72746
  Epoch 020 - train 0.21951 | val 4.94406
  Epoch 021 - train 0.19979 | val 3.28224
  Classification -> best τ=0.380 (val F1=0.2293)
  Directional -> Accuracy: 0.5479, MCC: 0.0690, F1: 0.6857

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.33641 | val 1.15106
  Epoch 020 - train 0.07576 | val 2.58923
  Epoch 022 - train 0.04320 | val 2.50804
  Classification -> best τ=0.505 (val F1=0.4014)
  Directional -> Accuracy: 0.6122, MCC: 0.2385, F1: 0.5581

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.28349 | val 2.58113
  Epoch 020 - train 0.10408 | val 4.95106
  Epoch 021 - train 0.09488 | val 4.68441
  Classification -> best τ=0.560 (val F1=0.2294)
  Directional -> Accuracy: 0.5111, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.32630 | val 1.73730
  Epoch 020 - train 0.10643 | val 3.30364
  Epoch 022 - train 0.07883 | val 4.09066
  Classification -> best τ=0.380 (val F1=0.3225)
  Directional -> Accuracy: 0.4925, MCC: 0.0861, F1: 0.5526

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 106). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 106). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.28498 | val 0.71022
  Epoch 020 - train 0.05062 | val 1.49880
  Epoch 026 - train 0.02601 | val 1.82971
  Classification -> best τ=0.680 (val F1=0.3612)
  Directional -> Accuracy: 0.4634, MCC: -0.0423, F1: 0.5000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.28412 | val 0.87265
  Epoch 020 - train 0.10021 | val 1.11317
  Epoch 024 - train 0.07369 | val 2.25317
  Classification -> best τ=0.465 (val F1=0.6442)
  Directional -> Accuracy: 0.6170, MCC: 0.2253, F1: 0.5714

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 106). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 106). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 106). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.33113 | val 2.52898
  Epoch 020 - train 0.11734 | val 5.64077
  Epoch 021 - train 0.09247 | val 6.41369
  Classification -> best τ=0.370 (val F1=0.2593)
  Directional -> Accuracy: 0.4412, MCC: 0.1053, F1: 0.6042

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.34438 | val 0.88853
  Epoch 020 - train 0.11040 | val 2.70210
  Epoch 022 - train 0.08220 | val 2.28504
  Classification -> best τ=0.625 (val F1=0.3464)
  Directional -> Accuracy: 0.6042, MCC: 0.2807, F1: 0.2400

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.32955 | val 2.70359
  Epoch 020 - train 0.11802 | val 3.98946
  Epoch 021 - train 0.10194 | val 4.04613
  Classification -> best τ=0.530 (val F1=0.0413)
  Directional -> Accuracy: 0.6250, MCC: 0.3210, F1: 0.7273

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 106). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.23922 | val 2.25963
  Epoch 020 - train 0.05936 | val 4.58745
  Epoch 022 - train 0.05835 | val 5.47520
  Classification -> best τ=0.385 (val F1=0.2788)
  Directional -> Accuracy: 0.4898, MCC: 0.0000, F1: 0.6575

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 106). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.33877 | val 1.19438
  Epoch 020 - train 0.11142 | val 2.00807
  Epoch 023 - train 0.07676 | val 2.07317
  Classification -> best τ=0.670 (val F1=0.4093)
  Directional -> Accuracy: 0.4915, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.30211 | val 0.92998
  Epoch 020 - train 0.11327 | val 2.97587
  Epoch 021 - train 0.11088 | val 1.54971
  Classification -> best τ=0.530 (val F1=0.2550)
  Directional -> Accuracy: 0.5600, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.37990 | val 0.98111
  Epoch 020 - train 0.16781 | val 2.03055
  Epoch 023 - train 0.11368 | val 2.27951
  Classification -> best τ=0.440 (val F1=0.3299)
  Directional -> Accuracy: 0.5735, MCC: 0.1355, F1: 0.6420

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 106). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.34450 | val 1.96136
  Epoch 020 - train 0.15594 | val 3.25373
  Epoch 021 - train 0.10846 | val 3.33136
  Classification -> best τ=0.540 (val F1=0.1890)
  Directional -> Accuracy: 0.6140, MCC: 0.0000, F1: 0.7609

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.37397 | val 2.26233
  Epoch 020 - train 0.12124 | val 4.46045
  Epoch 022 - train 0.09015 | val 4.32322
  Classification -> best τ=0.405 (val F1=0.2357)
  Directional -> Accuracy: 0.5676, MCC: 0.0553, F1: 0.6735

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.34606 | val 1.66093
  Epoch 020 - train 0.13102 | val 2.86948
  Epoch 022 - train 0.11077 | val 2.97676
  Classification -> best τ=0.370 (val F1=0.2822)
  Directional -> Accuracy: 0.5079, MCC: 0.1603, F1: 0.3673

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 106). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.39987 | val 1.63596
  Epoch 020 - train 0.17434 | val 1.26631
  Epoch 024 - train 0.11721 | val 2.11763
  Classification -> best τ=0.195 (val F1=0.3187)
  Directional -> Accuracy: 0.6027, MCC: 0.2106, F1: 0.6133

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.22349 | val 1.93411
  Epoch 020 - train 0.04706 | val 3.14969
  Epoch 021 - train 0.04263 | val 3.09764
  Classification -> best τ=0.410 (val F1=0.3223)
  Directional -> Accuracy: 0.4130, MCC: 0.0314, F1: 0.1290

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 106). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 106). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 106). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.32595 | val 1.48017
  Epoch 020 - train 0.06874 | val 2.03413
  Epoch 021 - train 0.06221 | val 2.45686
  Classification -> best τ=0.525 (val F1=0.1372)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.32651 | val 2.44643
  Epoch 020 - train 0.11545 | val 4.86444
  Epoch 021 - train 0.07643 | val 4.51217
  Classification -> best τ=0.620 (val F1=0.2474)
  Directional -> Accuracy: 0.5536, MCC: 0.1032, F1: 0.5902

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.37290 | val 1.42126
  Epoch 020 - train 0.16997 | val 2.01636
  Epoch 021 - train 0.14095 | val 2.75126
  Classification -> best τ=0.530 (val F1=0.1341)
  Directional -> Accuracy: 0.5312, MCC: 0.0000, F1: 0.0000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.26100 | val 2.42376
  Epoch 020 - train 0.08878 | val 5.01858
  Epoch 021 - train 0.07099 | val 5.14833
  Classification -> best τ=0.545 (val F1=0.4772)
  Directional -> Accuracy: 0.4630, MCC: -0.0263, F1: 0.1714

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.30962 | val 1.05482
  Epoch 020 - train 0.08834 | val 1.96445
  Epoch 021 - train 0.08955 | val 2.09787
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4186, MCC: 0.0000, F1: 0.5902

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.26019 | val 2.04133
  Epoch 020 - train 0.09649 | val 6.79135
  Epoch 021 - train 0.10738 | val 6.97152
  Classification -> best τ=0.500 (val F1=0.1385)
  Directional -> Accuracy: 0.6122, MCC: 0.1692, F1: 0.6984

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.39794 | val 1.22821
  Epoch 020 - train 0.15110 | val 2.33496
  Epoch 021 - train 0.11201 | val 2.51444
  Classification -> best τ=0.480 (val F1=0.2681)
  Directional -> Accuracy: 0.5091, MCC: 0.2193, F1: 0.1818

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.23053 | val 0.70706
  Epoch 020 - train 0.06544 | val 1.12098
  Epoch 027 - train 0.02585 | val 1.25708
  Classification -> best τ=0.465 (val F1=0.3130)
  Directional -> Accuracy: 0.5000, MCC: -0.0752, F1: 0.6275

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.29851 | val 1.12840
  Epoch 020 - train 0.08552 | val 1.67237
  Epoch 021 - train 0.08457 | val 1.96208
  Classification -> best τ=0.560 (val F1=0.2706)
  Directional -> Accuracy: 0.5366, MCC: 0.0701, F1: 0.4865

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.22792 | val 1.59193
  Epoch 020 - train 0.04429 | val 2.99490
  Epoch 021 - train 0.04292 | val 3.04663
  Classification -> best τ=0.605 (val F1=0.1437)
  Directional -> Accuracy: 0.2927, MCC: -0.4149, F1: 0.3256

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.31163 | val 1.82881
  Epoch 020 - train 0.11623 | val 2.73719
  Epoch 021 - train 0.08976 | val 2.67182
  Classification -> best τ=0.625 (val F1=0.2382)
  Directional -> Accuracy: 0.5208, MCC: 0.0722, F1: 0.3784

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.36689 | val 2.37789
  Epoch 020 - train 0.12137 | val 4.27786
  Epoch 021 - train 0.12178 | val 3.86887
  Classification -> best τ=0.455 (val F1=0.2254)
  Directional -> Accuracy: 0.4366, MCC: 0.0000, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 106). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.26886 | val 1.06103
  Epoch 020 - train 0.07052 | val 1.85478
  Epoch 021 - train 0.08260 | val 2.20760
  Classification -> best τ=0.325 (val F1=0.2287)
  Directional -> Accuracy: 0.5000, MCC: -0.0196, F1: 0.3636

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for PCG (101 < 106). Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.37735 | val 0.97088
  Epoch 020 - train 0.11726 | val 1.37629
  Epoch 023 - train 0.08172 | val 1.70066
  Classification -> best τ=0.325 (val F1=0.3750)
  Directional -> Accuracy: 0.5692, MCC: 0.0799, F1: 0.6744

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.16794 | val 1.15480
  Epoch 020 - train 0.04867 | val 2.62742
  Epoch 021 - train 0.03132 | val 2.90270
  Classification -> best τ=0.440 (val F1=0.3203)
  Directional -> Accuracy: 0.7500, MCC: 0.5041, F1: 0.7826

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.29185 | val 2.12131
  Epoch 020 - train 0.08563 | val 3.30813
  Epoch 021 - train 0.07025 | val 3.80185
  Classification -> best τ=0.425 (val F1=0.2544)
  Directional -> Accuracy: 0.5455, MCC: 0.1641, F1: 0.6269

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.24986 | val 4.19941
  Epoch 020 - train 0.09138 | val 5.07543
  Epoch 021 - train 0.06769 | val 4.73458
  Classification -> best τ=0.620 (val F1=0.2256)
  Directional -> Accuracy: 0.3556, MCC: -0.1935, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 106). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 106). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 106). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 106). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.32858 | val 0.64404
  Epoch 020 - train 0.11602 | val 1.35888
  Epoch 027 - train 0.04696 | val 1.68466
  Classification -> best τ=0.730 (val F1=0.4385)
  Directional -> Accuracy: 0.3696, MCC: -0.0060, F1: 0.4727

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 106). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 106). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 106). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.35610 | val 1.71023
  Epoch 020 - train 0.11815 | val 3.39933
  Epoch 021 - train 0.08309 | val 3.69050
  Classification -> best τ=0.475 (val F1=0.3456)
  Directional -> Accuracy: 0.4795, MCC: -0.0470, F1: 0.3871

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 106). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 106). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 106). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 106). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.27365 | val 0.76021
  Epoch 020 - train 0.03864 | val 2.11803
  Epoch 025 - train 0.03136 | val 2.39762
  Classification -> best τ=0.515 (val F1=0.4152)
  Directional -> Accuracy: 0.5682, MCC: 0.2148, F1: 0.6885

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.28508 | val 0.89327
  Epoch 020 - train 0.09709 | val 1.35631
  Epoch 021 - train 0.07773 | val 1.37173
  Classification -> best τ=0.500 (val F1=0.1690)
  Directional -> Accuracy: 0.5122, MCC: 0.0644, F1: 0.5000

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.23829 | val 0.81690
  Epoch 020 - train 0.06844 | val 1.28439
  Epoch 022 - train 0.04617 | val 1.35404
  Classification -> best τ=0.585 (val F1=0.0422)
  Directional -> Accuracy: 0.3696, MCC: 0.0000, F1: 0.5397

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.35722 | val 3.79831
  Epoch 020 - train 0.11897 | val 7.32476
  Epoch 021 - train 0.09289 | val 7.35760
  Classification -> best τ=0.525 (val F1=0.2397)
  Directional -> Accuracy: 0.4444, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.29949 | val 2.56599
  Epoch 020 - train 0.08580 | val 5.18101
  Epoch 021 - train 0.06639 | val 6.26735
  Classification -> best τ=0.480 (val F1=0.2464)
  Directional -> Accuracy: 0.4909, MCC: 0.0000, F1: 0.6585

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.28163 | val 1.13748
  Epoch 020 - train 0.10863 | val 1.87113
  Epoch 024 - train 0.05490 | val 2.38211
  Classification -> best τ=0.630 (val F1=0.2685)
  Directional -> Accuracy: 0.6154, MCC: 0.2308, F1: 0.6154


[I 2026-02-22 10:09:23,610] Trial 85 finished with value: 0.263950427340679 and parameters: {'feature_set': 'sector_sentiment', 'model_type': 'BiGRU', 'sequence_length': 30, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 64, 'num_layers': 1, 'inter_rnn_drop': 0.1, 'dropout': 0.1, 'batch_size': 32, 'learning_rate': 0.0018251905828293084, 'weight_decay': 2.1205532628094248e-07, 'lr_patience': 5, 'lr_factor': 0.8, 'early_stopping_patience': 20, 'max_epochs': 50, 'huber_delta': 1.6363519114753227, 'early_stopping_min_delta': 0.008875444365027355}. Best is trial 22 with value: 0.2833350641483003.

  Epoch 021 - train 0.10946 | val 2.17263
  Classification -> best τ=0.455 (val F1=0.1450)
  Directional -> Accuracy: 0.5085, MCC: -0.0012, F1: 0.3830

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.263950427340679
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.59664 | val 1.12649
  Epoch 011 - train 0.58551 | val 1.54295
  Classification -> best τ=0.565 (val F1=0.2036)
  Directional -> Accuracy: 0.5526, MCC: 0.0000, F1: 0.0000

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.59605 | val 0.78002
  Epoch 012 - train 0.47538 | val 0.73429
  Classification -> best τ=0.495 (val F1=0.1058)
  Directional -> Accuracy: 0.5778, MCC: 0.0000, F1: 0.7324

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.61702 | val 1.00464
  Epoch 011 - train 0.54771 | val 1.05573
  Classification -> best τ=0.550 (val F1=0.2764)
  Directional -> Accuracy: 0.4565, MCC: -0.0996, F1: 0.0741

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.65097 | val 0.72091
  Epoch 011 - train 0.61829 | val 0.73356
  Classification -> best τ=0.425 (val F1=0.1394)
  Directional -> Accuracy: 0.5405, MCC: 0.0000, F1: 0.7018

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.54895 | val 0.63935
  Epoch 020 - train 0.33745 | val 1.00292
  Classification -> best τ=0.510 (val F1=0.5167)
  Directional -> Accuracy: 0.6600, MCC: 0.3398, F1: 0.6222

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.52233 | val 0.78693
  Epoch 012 - train 0.44657 | val 0.71362
  Classification -> best τ=0.530 (val F1=0.2030)
  Directional -> Accuracy: 0.4783, MCC: -0.0288, F1: 0.5556

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.60214 | val 0.99602
  Epoch 011 - train 0.55493 | val 1.04029
  Classification -> best τ=0.430 (val F1=0.3636)
  Directional -> Accuracy: 0.4265, MCC: 0.0405, F1: 0.5618

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.54447 | val 0.95231
  Epoch 012 - train 0.45882 | val 2.12651
  Classification -> best τ=0.575 (val F1=0.3689)
  Directional -> Accuracy: 0.5000, MCC: 0.0430, F1: 0.5333

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.61189 | val 1.36655
  Epoch 012 - train 0.51154 | val 1.39837
  Classification -> best τ=0.600 (val F1=0.1928)
  Directional -> Accuracy: 0.5417, MCC: 0.0893, F1: 0.5217

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.54705 | val 0.88558
  Epoch 011 - train 0.54741 | val 0.89199
  Classification -> best τ=0.740 (val F1=0.1607)
  Directional -> Accuracy: 0.5652, MCC: 0.0583, F1: 0.3478

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.64039 | val 0.69222
  Epoch 018 - train 0.55414 | val 0.95840
  Classification -> best τ=0.490 (val F1=0.3729)
  Directional -> Accuracy: 0.5714, MCC: 0.1005, F1: 0.2759

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.65720 | val 0.72634
  Epoch 013 - train 0.60127 | val 0.74162
  Classification -> best τ=0.470 (val F1=0.2777)
  Directional -> Accuracy: 0.5088, MCC: 0.0000, F1: 0.6744

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.50480 | val 1.45834
  Epoch 011 - train 0.46441 | val 1.99633
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.6230

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.62603 | val 0.71147
  Epoch 012 - train 0.63750 | val 0.78744
  Classification -> best τ=0.470 (val F1=0.3768)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.60550 | val 0.78861
  Epoch 015 - train 0.46669 | val 0.93193
  Classification -> best τ=0.500 (val F1=0.2678)
  Directional -> Accuracy: 0.5294, MCC: 0.2086, F1: 0.6471

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.59888 | val 1.07307
  Epoch 011 - train 0.56771 | val 1.14529
  Classification -> best τ=0.530 (val F1=0.1195)
  Directional -> Accuracy: 0.5797, MCC: 0.1910, F1: 0.5246

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.61952 | val 1.68129
  Epoch 011 - train 0.55619 | val 1.71890
  Classification -> best τ=0.445 (val F1=0.1905)
  Directional -> Accuracy: 0.6207, MCC: 0.0000, F1: 0.7660

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.61252 | val 0.94886
  Epoch 012 - train 0.55643 | val 0.83950
  Classification -> best τ=0.560 (val F1=0.1087)
  Directional -> Accuracy: 0.4000, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.59666 | val 0.82005
  Epoch 012 - train 0.53444 | val 0.86660
  Classification -> best τ=0.485 (val F1=0.3948)
  Directional -> Accuracy: 0.5000, MCC: -0.0049, F1: 0.5429

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.54152 | val 0.89728
  Epoch 011 - train 0.51097 | val 0.87948
  Classification -> best τ=0.515 (val F1=0.2030)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.54654 | val 2.22730
  Epoch 011 - train 0.49883 | val 1.95392
  Classification -> best τ=0.550 (val F1=0.1340)
  Directional -> Accuracy: 0.5106, MCC: 0.0805, F1: 0.5106

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.64250 | val 0.95090
  Epoch 018 - train 0.53243 | val 1.60118
  Classification -> best τ=0.455 (val F1=0.2612)
  Directional -> Accuracy: 0.4923, MCC: -0.0049, F1: 0.1538

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.62102 | val 0.71125
  Epoch 013 - train 0.57881 | val 0.67423
  Classification -> best τ=0.505 (val F1=0.3820)
  Directional -> Accuracy: 0.5965, MCC: 0.1518, F1: 0.7160

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.60645 | val 0.75273
  Epoch 011 - train 0.57128 | val 0.83577
  Classification -> best τ=0.505 (val F1=0.1565)
  Directional -> Accuracy: 0.5231, MCC: 0.0147, F1: 0.1622

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.59105 | val 1.24404
  Epoch 012 - train 0.52950 | val 0.91487
  Classification -> best τ=0.510 (val F1=0.3974)
  Directional -> Accuracy: 0.5818, MCC: 0.1913, F1: 0.5490

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.47975 | val 4.81531
  Epoch 011 - train 0.46227 | val 4.54229
  Classification -> best τ=0.570 (val F1=0.3669)
  Directional -> Accuracy: 0.4000, MCC: -0.1764, F1: 0.5714

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.55876 | val 1.32822
  Epoch 013 - train 0.56634 | val 0.89614
  Classification -> best τ=0.545 (val F1=0.1803)
  Directional -> Accuracy: 0.5714, MCC: 0.1250, F1: 0.6250

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.59745 | val 1.04291
  Epoch 011 - train 0.54924 | val 1.08684
  Classification -> best τ=0.380 (val F1=0.2305)
  Directional -> Accuracy: 0.4464, MCC: -0.2311, F1: 0.5974

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.47589 | val 0.75966
  Epoch 011 - train 0.45631 | val 0.83931
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5500, MCC: 0.0000, F1: 0.7097

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.55286 | val 0.74834
  Epoch 018 - train 0.45885 | val 0.86581
  Classification -> best τ=0.525 (val F1=0.3979)
  Directional -> Accuracy: 0.4286, MCC: -0.1685, F1: 0.2941

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.59717 | val 0.89371
  Epoch 011 - train 0.51637 | val 1.09041
  Classification -> best τ=0.490 (val F1=0.0769)
  Directional -> Accuracy: 0.5952, MCC: 0.1758, F1: 0.7119

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.55307 | val 0.80184
  Epoch 016 - train 0.30746 | val 0.98634
  Classification -> best τ=0.485 (val F1=0.3272)
  Directional -> Accuracy: 0.4898, MCC: -0.0517, F1: 0.5902

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.60017 | val 0.85907
  Epoch 011 - train 0.57233 | val 0.79394
  Classification -> best τ=0.475 (val F1=0.2365)
  Directional -> Accuracy: 0.5139, MCC: 0.1992, F1: 0.2553

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.48447 | val 1.03420
  Epoch 011 - train 0.46782 | val 1.16477
  Classification -> best τ=0.475 (val F1=0.2717)
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.56986 | val 0.95287
  Epoch 017 - train 0.49937 | val 0.97689
  Classification -> best τ=0.270 (val F1=0.3855)
  Directional -> Accuracy: 0.5909, MCC: 0.1026, F1: 0.7216

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.54060 | val 0.98621
  Epoch 011 - train 0.53120 | val 0.96400
  Classification -> best τ=0.455 (val F1=0.1745)
  Directional -> Accuracy: 0.7143, MCC: 0.4301, F1: 0.7500

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.57473 | val 1.21451
  Epoch 011 - train 0.53153 | val 1.09206
  Classification -> best τ=0.540 (val F1=0.2327)
  Directional -> Accuracy: 0.5714, MCC: 0.1281, F1: 0.4783

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.45688 | val 1.05429
  Epoch 011 - train 0.38885 | val 1.08515
  Classification -> best τ=0.440 (val F1=0.0314)
  Directional -> Accuracy: 0.6087, MCC: 0.0000, F1: 0.7568

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.50303 | val 0.79163
  Epoch 015 - train 0.46053 | val 0.80754
  Classification -> best τ=0.760 (val F1=0.4306)
  Directional -> Accuracy: 0.5208, MCC: 0.2263, F1: 0.5660

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.55532 | val 1.46116
  Epoch 011 - train 0.49778 | val 1.76294
  Classification -> best τ=0.465 (val F1=0.3965)
  Directional -> Accuracy: 0.4595, MCC: -0.1107, F1: 0.2593

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.62516 | val 0.77045
  Epoch 015 - train 0.54191 | val 0.97336
  Classification -> best τ=0.410 (val F1=0.1942)
  Directional -> Accuracy: 0.5111, MCC: 0.0103, F1: 0.6333

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.40015 | val 1.32278
  Epoch 011 - train 0.35159 | val 1.37562
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.7273

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.47384 | val 2.46569
  Epoch 012 - train 0.40565 | val 3.20224
  Classification -> best τ=0.580 (val F1=0.1371)
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.5455

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.64302 | val 0.71124
  Epoch 014 - train 0.58390 | val 0.76453
  Classification -> best τ=0.575 (val F1=0.2085)
  Directional -> Accuracy: 0.6364, MCC: 0.2586, F1: 0.7059

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.55215 | val 2.07983
  Epoch 011 - train 0.47184 | val 2.01980
  Classification -> best τ=0.485 (val F1=0.2491)
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.6506

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.64831 | val 0.70334
  Epoch 011 - train 0.61189 | val 0.79883
  Classification -> best τ=0.575 (val F1=0.2407)
  Directional -> Accuracy: 0.4906, MCC: -0.0054, F1: 0.1290

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.53188 | val 2.53683
  Epoch 012 - train 0.47000 | val 2.93570
  Classification -> best τ=0.480 (val F1=0.2291)
  Directional -> Accuracy: 0.4727, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.65171 | val 0.78315
  Epoch 020 - train 0.53034 | val 0.88828

[I 2026-02-22 10:11:12,978] Trial 86 finished with value: 0.23994856559809133 and parameters: {'feature_set': 'sector', 'model_type': 'LSTM', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.0, 'batch_size': 16, 'learning_rate': 0.004394711190037831, 'weight_decay': 2.445925115359905e-06, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 1.4899187119745558, 'early_stopping_min_delta': 0.0020378902886180124}. Best is trial 22 with value: 0.2833350641483003.

  Epoch 026 - train 0.34948 | val 1.10711
  Classification -> best τ=0.400 (val F1=0.3458)
  Directional -> Accuracy: 0.5000, MCC: -0.0229, F1: 0.2857

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.23994856559809133
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: classification
Sequence length: 6
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.55612 | val 1.11124
  Epoch 016 - train 0.41637 | val 1.89607
  Classification -> best τ=0.630 (val F1=0.2727)
  Directional -> Accuracy: 0.5823, MCC: 0.1212, F1: 0.3529

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 82). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.48363 | val 0.81495
  Epoch 017 - train 0.25217 | val 1.05229
  Classification -> best τ=0.635 (val F1=0.1654)
  Directional -> Accuracy: 0.6042, MCC: 0.1732, F1: 0.6885

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 82). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.48434 | val 1.42215
  Epoch 016 - train 0.33656 | val 1.54115
  Classification -> best τ=0.475 (val F1=0.3077)
  Directional -> Accuracy: 0.4694, MCC: -0.0229, F1: 0.1875

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.63295 | val 0.85638
  Epoch 020 - train 0.40901 | val 0.92743
  Epoch 027 - train 0.28920 | val 0.78318
  Classification -> best τ=0.540 (val F1=0.1913)
  Directional -> Accuracy: 0.5714, MCC: 0.1299, F1: 0.6207

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.48534 | val 1.13161
  Epoch 020 - train 0.21960 | val 0.76273
  Epoch 027 - train 0.07710 | val 0.87330
  Classification -> best τ=0.330 (val F1=0.3780)
  Directional -> Accuracy: 0.6226, MCC: 0.2519, F1: 0.7059

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.40446 | val 1.10486
  Epoch 016 - train 0.20382 | val 1.87829
  Classification -> best τ=0.480 (val F1=0.1940)
  Directional -> Accuracy: 0.4634, MCC: -0.0872, F1: 0.3889

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.54478 | val 0.97265
  Epoch 016 - train 0.44622 | val 1.30550
  Classification -> best τ=0.505 (val F1=0.0603)
  Directional -> Accuracy: 0.4507, MCC: -0.0155, F1: 0.5185

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 82). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 82). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.37890 | val 1.45574
  Epoch 016 - train 0.16147 | val 2.86331
  Classification -> best τ=0.670 (val F1=0.2921)
  Directional -> Accuracy: 0.5745, MCC: -0.0030, F1: 0.1667

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.45525 | val 0.95265
  Epoch 017 - train 0.27359 | val 1.42038
  Classification -> best τ=0.525 (val F1=0.3726)
  Directional -> Accuracy: 0.6047, MCC: 0.1178, F1: 0.3704

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 82). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 82). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.47075 | val 0.72555
  Epoch 016 - train 0.32306 | val 0.83074
  Classification -> best τ=0.420 (val F1=0.1838)
  Directional -> Accuracy: 0.3889, MCC: -0.1863, F1: 0.4500

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.49111 | val 1.26536
  Epoch 016 - train 0.31586 | val 1.38148
  Classification -> best τ=0.510 (val F1=0.1701)
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.63361 | val 1.13972
  Epoch 018 - train 0.41199 | val 1.34741
  Classification -> best τ=0.370 (val F1=0.3506)
  Directional -> Accuracy: 0.5333, MCC: 0.1336, F1: 0.6744

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.42316 | val 0.72780
  Epoch 016 - train 0.28648 | val 0.83308
  Classification -> best τ=0.590 (val F1=0.1455)
  Directional -> Accuracy: 0.5556, MCC: 0.1475, F1: 0.6154

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 82). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.48258 | val 0.79287
  Epoch 016 - train 0.38542 | val 0.83282
  Classification -> best τ=0.485 (val F1=0.4287)
  Directional -> Accuracy: 0.5873, MCC: 0.1744, F1: 0.5806

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.50844 | val 2.51339
  Epoch 016 - train 0.42720 | val 3.73523
  Classification -> best τ=0.490 (val F1=0.3472)
  Directional -> Accuracy: 0.5370, MCC: 0.0845, F1: 0.5763

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.46443 | val 0.96773
  Epoch 017 - train 0.30578 | val 0.89449
  Classification -> best τ=0.580 (val F1=0.3484)
  Directional -> Accuracy: 0.5000, MCC: 0.0448, F1: 0.3793

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.50524 | val 2.26570
  Epoch 017 - train 0.30339 | val 3.51773
  Classification -> best τ=0.395 (val F1=0.0426)
  Directional -> Accuracy: 0.6230, MCC: 0.1603, F1: 0.7629

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.52293 | val 1.42935
  Epoch 016 - train 0.34965 | val 1.62867
  Classification -> best τ=0.485 (val F1=0.1177)
  Directional -> Accuracy: 0.3846, MCC: -0.1403, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.60439 | val 0.68486
  Epoch 019 - train 0.30104 | val 1.16550
  Classification -> best τ=0.280 (val F1=0.3682)
  Directional -> Accuracy: 0.5075, MCC: 0.1378, F1: 0.3774

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 82). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.49668 | val 1.08755
  Epoch 018 - train 0.28303 | val 1.62534
  Classification -> best τ=0.620 (val F1=0.2946)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.40099 | val 0.86111
  Epoch 016 - train 0.26664 | val 1.00391
  Classification -> best τ=0.495 (val F1=0.2726)
  Directional -> Accuracy: 0.5400, MCC: -0.0294, F1: 0.6567

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 82). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 82). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 82). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.54558 | val 0.90961
  Epoch 017 - train 0.36379 | val 1.75050
  Classification -> best τ=0.540 (val F1=0.2962)
  Directional -> Accuracy: 0.4559, MCC: -0.0883, F1: 0.4638

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.52079 | val 1.15077
  Epoch 018 - train 0.30138 | val 1.22257
  Classification -> best τ=0.615 (val F1=0.2668)
  Directional -> Accuracy: 0.4333, MCC: -0.0586, F1: 0.3200

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.47682 | val 0.78996
  Epoch 017 - train 0.34520 | val 0.84856
  Classification -> best τ=0.480 (val F1=0.1296)
  Directional -> Accuracy: 0.4706, MCC: -0.0597, F1: 0.4545

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.50963 | val 1.03870
  Epoch 018 - train 0.24113 | val 1.93186
  Classification -> best τ=0.690 (val F1=0.3640)
  Directional -> Accuracy: 0.4483, MCC: 0.0000, F1: 0.0000

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.36165 | val 1.42069
  Epoch 016 - train 0.17822 | val 1.86211
  Classification -> best τ=0.515 (val F1=0.2124)
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.52384 | val 0.85749
  Epoch 017 - train 0.30898 | val 1.40331
  Classification -> best τ=0.510 (val F1=0.1022)
  Directional -> Accuracy: 0.5111, MCC: 0.0181, F1: 0.5600

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.44582 | val 1.31410
  Epoch 016 - train 0.33756 | val 1.67982
  Classification -> best τ=0.425 (val F1=0.3431)
  Directional -> Accuracy: 0.4576, MCC: -0.0134, F1: 0.2727

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.34757 | val 1.28834
  Epoch 020 - train 0.15771 | val 1.91308
  Classification -> best τ=0.675 (val F1=0.3458)
  Directional -> Accuracy: 0.4545, MCC: -0.0788, F1: 0.2941

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.46194 | val 0.84367
  Epoch 016 - train 0.26711 | val 1.21883
  Classification -> best τ=0.580 (val F1=0.2479)
  Directional -> Accuracy: 0.3478, MCC: -0.3568, F1: 0.1176

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.42403 | val 1.56997
  Epoch 017 - train 0.18224 | val 2.44318
  Classification -> best τ=0.520 (val F1=0.2265)
  Directional -> Accuracy: 0.5435, MCC: 0.0000, F1: 0.7042

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.50547 | val 0.75874
  Epoch 016 - train 0.26215 | val 1.36034
  Classification -> best τ=0.490 (val F1=0.4081)
  Directional -> Accuracy: 0.4615, MCC: -0.1455, F1: 0.0000

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.51864 | val 0.67727
  Epoch 016 - train 0.37743 | val 0.87439
  Classification -> best τ=0.335 (val F1=0.3516)
  Directional -> Accuracy: 0.5600, MCC: 0.1364, F1: 0.5600

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 82). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.37124 | val 1.14072
  Epoch 017 - train 0.15394 | val 1.82782
  Classification -> best τ=0.535 (val F1=0.2365)
  Directional -> Accuracy: 0.5122, MCC: 0.0195, F1: 0.4444

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.49152 | val 1.37576
  Epoch 017 - train 0.24985 | val 2.50575
  Classification -> best τ=0.550 (val F1=0.3407)
  Directional -> Accuracy: 0.4783, MCC: -0.1453, F1: 0.1429

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.53117 | val 0.85925
  Epoch 016 - train 0.36484 | val 1.01782
  Classification -> best τ=0.425 (val F1=0.3582)
  Directional -> Accuracy: 0.6377, MCC: 0.2275, F1: 0.7368

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.40905 | val 0.99343
  Epoch 016 - train 0.27208 | val 1.30536
  Classification -> best τ=0.485 (val F1=0.2782)
  Directional -> Accuracy: 0.5778, MCC: 0.1633, F1: 0.5366

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.57544 | val 2.17015
  Epoch 019 - train 0.27728 | val 1.46206
  Classification -> best τ=0.480 (val F1=0.1713)
  Directional -> Accuracy: 0.5085, MCC: 0.0232, F1: 0.5246

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.46008 | val 1.14967
  Epoch 016 - train 0.27538 | val 1.90023
  Classification -> best τ=0.345 (val F1=0.0039)
  Directional -> Accuracy: 0.3878, MCC: -0.0861, F1: 0.1667

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 82). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 82). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 82). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 82). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.45382 | val 1.44634
  Epoch 016 - train 0.33101 | val 2.35071
  Classification -> best τ=0.475 (val F1=0.3647)
  Directional -> Accuracy: 0.3333, MCC: 0.0000, F1: 0.5000

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 82). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.35299 | val 1.07635
  Epoch 017 - train 0.15920 | val 1.30900
  Classification -> best τ=0.350 (val F1=0.3780)
  Directional -> Accuracy: 0.4878, MCC: -0.0403, F1: 0.5882

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 82). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 82). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.60179 | val 1.11938
  Epoch 019 - train 0.34312 | val 2.59323
  Classification -> best τ=0.360 (val F1=0.3306)
  Directional -> Accuracy: 0.5065, MCC: 0.0000, F1: 0.6724

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 82). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 82). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.42377 | val 3.85216
  Epoch 016 - train 0.23538 | val 6.91379
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4898, MCC: 0.0000, F1: 0.6575

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.37909 | val 2.26279
  Epoch 016 - train 0.26040 | val 2.50618
  Classification -> best τ=0.590 (val F1=0.3244)
  Directional -> Accuracy: 0.4894, MCC: 0.1183, F1: 0.2941

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.42979 | val 1.15593
  Epoch 016 - train 0.27593 | val 1.33671
  Classification -> best τ=0.480 (val F1=0.4805)
  Directional -> Accuracy: 0.6667, MCC: 0.2000, F1: 0.3636

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.51105 | val 1.05263
  Epoch 018 - train 0.26211 | val 2.39304
  Classification -> best τ=0.545 (val F1=0.2581)
  Directional -> Accuracy: 0.4828, MCC: 0.1703, F1: 0.1176

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.44597 | val 2.35328
  Epoch 016 - train 0.30407 | val 3.04041
  Classification -> best τ=0.590 (val F1=0.2997)
  Directional -> Accuracy: 0.4915, MCC: 0.0000, F1: 0.6591

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.49969 | val 0.85514
  Epoch 016 - train 0.34220 | val 0.89260
  Classification -> best τ=0.495 (val F1=0.0541)
  Directional -> Accuracy: 0.5536, MCC: 0.1049, F1: 0.5763

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.49635 | val 0.88771
  Epoch 017 - train 0.34677 | val 0.96133
  Classification -> best τ=0.540 (val F1=0.1522)
  Directional -> Accuracy: 0.4310, MCC: -0.1577, F1: 0.1538

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.61569 | val 0.68670

[I 2026-02-22 10:11:47,854] Trial 87 finished with value: 0.25664630022504575 and parameters: {'feature_set': 'base', 'model_type': 'GRU', 'sequence_length': 6, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 1, 'inter_rnn_drop': 0.4, 'dropout': 0.1, 'batch_size': 32, 'learning_rate': 0.00726858884121929, 'weight_decay': 5.714801043393042e-06, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 15, 'max_epochs': 50, 'huber_delta': 1.0301154157565546, 'early_stopping_min_delta': 0.008111145339689823}. Best is trial 22 with value: 0.2833350641483003.

  Epoch 019 - train 0.32663 | val 0.94108
  Classification -> best τ=0.440 (val F1=0.2031)
  Directional -> Accuracy: 0.4603, MCC: -0.0711, F1: 0.5000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.25664630022504575
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d', 'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down', 'finbert_neutral']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.50314 | val 0.91044
  Epoch 020 - train 0.30212 | val 1.42987
  Epoch 024 - train 0.24908 | val 1.52648
  Classification -> best τ=0.580 (val F1=0.2510)
  Directional -> Accuracy: 0.5658, MCC: 0.1023, F1: 0.4407

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.42980 | val 0.78041
  Epoch 020 - train 0.24178 | val 1.12771
  Epoch 023 - train 0.18633 | val 1.55772
  Classification -> best τ=0.450 (val F1=0.2227)
  Directional -> Accuracy: 0.5778, MCC: 0.0000, F1: 0.7324

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.46079 | val 0.84208
  Epoch 020 - train 0.19759 | val 2.05760
  Epoch 021 - train 0.25355 | val 1.98776
  Classification -> best τ=0.505 (val F1=0.2861)
  Directional -> Accuracy: 0.4783, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.50014 | val 0.96396
  Epoch 020 - train 0.28604 | val 1.10733
  Epoch 021 - train 0.27549 | val 1.19799
  Classification -> best τ=0.485 (val F1=0.2027)
  Directional -> Accuracy: 0.5811, MCC: 0.1782, F1: 0.5634

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.44747 | val 0.88717
  Epoch 020 - train 0.26731 | val 1.19178
  Epoch 025 - train 0.19467 | val 1.47166
  Classification -> best τ=0.495 (val F1=0.4787)
  Directional -> Accuracy: 0.6200, MCC: 0.2795, F1: 0.5366

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.45082 | val 0.75102
  Epoch 020 - train 0.28544 | val 1.32465
  Epoch 021 - train 0.24042 | val 1.18606
  Classification -> best τ=0.520 (val F1=0.3644)
  Directional -> Accuracy: 0.5652, MCC: 0.2227, F1: 0.1667

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.46019 | val 1.68358
  Epoch 020 - train 0.23443 | val 2.80427
  Epoch 021 - train 0.23617 | val 2.95964
  Classification -> best τ=0.440 (val F1=0.2050)
  Directional -> Accuracy: 0.4853, MCC: 0.1391, F1: 0.5783

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.44299 | val 0.82552
  Epoch 020 - train 0.21435 | val 1.62028
  Epoch 029 - train 0.12395 | val 1.47883
  Classification -> best τ=0.630 (val F1=0.5247)
  Directional -> Accuracy: 0.4524, MCC: -0.0313, F1: 0.5306

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.45442 | val 0.96302
  Epoch 020 - train 0.24921 | val 2.02175
  Epoch 021 - train 0.22082 | val 1.99918
  Classification -> best τ=0.490 (val F1=0.2285)
  Directional -> Accuracy: 0.5625, MCC: 0.0263, F1: 0.0870

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.41322 | val 0.87539
  Epoch 020 - train 0.21892 | val 0.99201
  Epoch 023 - train 0.18067 | val 1.34168
  Classification -> best τ=0.480 (val F1=0.3247)
  Directional -> Accuracy: 0.4638, MCC: -0.0573, F1: 0.4478

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.50549 | val 0.87623
  Epoch 020 - train 0.27688 | val 1.25501
  Epoch 021 - train 0.29471 | val 1.32800
  Classification -> best τ=0.530 (val F1=0.2593)
  Directional -> Accuracy: 0.5918, MCC: 0.1804, F1: 0.2308

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.46781 | val 1.20438
  Epoch 020 - train 0.27713 | val 2.92886
  Epoch 021 - train 0.24201 | val 3.74299
  Classification -> best τ=0.465 (val F1=0.1304)
  Directional -> Accuracy: 0.6667, MCC: 0.3408, F1: 0.7077

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.43694 | val 1.02326
  Epoch 020 - train 0.23449 | val 2.47103
  Epoch 021 - train 0.23109 | val 2.45257
  Classification -> best τ=0.455 (val F1=0.2850)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.6230

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.48528 | val 0.73102
  Epoch 020 - train 0.27329 | val 1.83922
  Epoch 023 - train 0.23161 | val 1.91441
  Classification -> best τ=0.500 (val F1=0.3864)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.49487 | val 1.18208
  Epoch 020 - train 0.24648 | val 2.11737
  Epoch 023 - train 0.17982 | val 2.67069
  Classification -> best τ=0.520 (val F1=0.3118)
  Directional -> Accuracy: 0.5098, MCC: -0.1178, F1: 0.0741

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.50168 | val 1.26022
  Epoch 020 - train 0.27887 | val 2.02969
  Epoch 021 - train 0.30212 | val 1.85189
  Classification -> best τ=0.450 (val F1=0.2659)
  Directional -> Accuracy: 0.5362, MCC: 0.0180, F1: 0.6863

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.50357 | val 0.96717
  Epoch 020 - train 0.32873 | val 2.13229
  Epoch 021 - train 0.30642 | val 1.94635
  Classification -> best τ=0.555 (val F1=0.2276)
  Directional -> Accuracy: 0.3793, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.44540 | val 0.94465
  Epoch 020 - train 0.23007 | val 1.88653
  Epoch 021 - train 0.24651 | val 2.27759
  Classification -> best τ=0.515 (val F1=0.1909)
  Directional -> Accuracy: 0.4000, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.48180 | val 0.86523
  Epoch 020 - train 0.27701 | val 1.10577
  Epoch 023 - train 0.26237 | val 1.07478
  Classification -> best τ=0.520 (val F1=0.3180)
  Directional -> Accuracy: 0.4531, MCC: 0.0577, F1: 0.1860

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.48882 | val 0.88533
  Epoch 020 - train 0.29530 | val 0.92440
  Epoch 023 - train 0.23631 | val 0.98311
  Classification -> best τ=0.530 (val F1=0.3222)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.45479 | val 0.74023
  Epoch 020 - train 0.18688 | val 1.24993
  Epoch 030 - train 0.07890 | val 1.56113
  Classification -> best τ=0.430 (val F1=0.4873)
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.47503 | val 1.10533
  Epoch 020 - train 0.24738 | val 1.78772
  Epoch 021 - train 0.23649 | val 1.92874
  Classification -> best τ=0.465 (val F1=0.1952)
  Directional -> Accuracy: 0.4923, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.51617 | val 1.00247
  Epoch 020 - train 0.28194 | val 1.50988
  Epoch 021 - train 0.26040 | val 1.60104
  Classification -> best τ=0.575 (val F1=0.2644)
  Directional -> Accuracy: 0.5789, MCC: 0.1706, F1: 0.5862

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.50909 | val 0.87754
  Epoch 020 - train 0.25195 | val 1.42973
  Epoch 021 - train 0.25505 | val 1.49588
  Classification -> best τ=0.545 (val F1=0.1565)
  Directional -> Accuracy: 0.5231, MCC: 0.0548, F1: 0.5507

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.43343 | val 0.83389
  Epoch 020 - train 0.24740 | val 1.84140
  Epoch 025 - train 0.20191 | val 2.18249
  Classification -> best τ=0.530 (val F1=0.4199)
  Directional -> Accuracy: 0.5636, MCC: 0.2170, F1: 0.4286

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.40012 | val 0.68461
  Epoch 020 - train 0.25392 | val 1.36623
  Epoch 028 - train 0.14566 | val 2.03190
  Classification -> best τ=0.450 (val F1=0.4947)
  Directional -> Accuracy: 0.4000, MCC: -0.1764, F1: 0.5714

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.49810 | val 0.70108
  Epoch 020 - train 0.30956 | val 1.12178
  Epoch 021 - train 0.26828 | val 1.02198
  Classification -> best τ=0.520 (val F1=0.1803)
  Directional -> Accuracy: 0.4048, MCC: -0.1925, F1: 0.4444

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.46327 | val 0.98964
  Epoch 020 - train 0.27308 | val 1.52628
  Epoch 021 - train 0.30395 | val 1.56033
  Classification -> best τ=0.490 (val F1=0.1387)
  Directional -> Accuracy: 0.4821, MCC: 0.1728, F1: 0.1212

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.45084 | val 0.78926
  Epoch 020 - train 0.29916 | val 1.48586
  Epoch 021 - train 0.27186 | val 1.66233
  Classification -> best τ=0.480 (val F1=0.0216)
  Directional -> Accuracy: 0.5000, MCC: -0.0439, F1: 0.6000

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.48520 | val 0.95190
  Epoch 020 - train 0.33394 | val 1.52867
  Epoch 021 - train 0.28433 | val 1.36058
  Classification -> best τ=0.540 (val F1=0.2814)
  Directional -> Accuracy: 0.4286, MCC: -0.2530, F1: 0.0769

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.50981 | val 1.01004
  Epoch 020 - train 0.31337 | val 1.95018
  Epoch 021 - train 0.27028 | val 1.77328
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5476, MCC: 0.0000, F1: 0.7077

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.43694 | val 1.08609
  Epoch 020 - train 0.21971 | val 1.68829
  Epoch 023 - train 0.19135 | val 1.93273
  Classification -> best τ=0.445 (val F1=0.3541)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.46756 | val 0.62625
  Epoch 020 - train 0.25968 | val 1.12505
  Epoch 028 - train 0.12195 | val 1.41645
  Classification -> best τ=0.450 (val F1=0.4730)
  Directional -> Accuracy: 0.5278, MCC: 0.2273, F1: 0.2917

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.44509 | val 0.83569
  Epoch 020 - train 0.21515 | val 1.41303
  Epoch 021 - train 0.20566 | val 1.74368
  Classification -> best τ=0.445 (val F1=0.2717)
  Directional -> Accuracy: 0.5349, MCC: 0.1084, F1: 0.6429

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.47506 | val 1.25074
  Epoch 020 - train 0.34662 | val 1.84552
  Epoch 021 - train 0.32814 | val 1.89220
  Classification -> best τ=0.395 (val F1=0.3068)
  Directional -> Accuracy: 0.5758, MCC: 0.0569, F1: 0.7083

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.43332 | val 0.73483
  Epoch 020 - train 0.20170 | val 1.10603
  Epoch 025 - train 0.15286 | val 1.38346
  Classification -> best τ=0.575 (val F1=0.3260)
  Directional -> Accuracy: 0.5952, MCC: 0.2656, F1: 0.4516

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.42649 | val 1.80984
  Epoch 020 - train 0.24268 | val 2.81500
  Epoch 021 - train 0.19690 | val 3.45454
  Classification -> best τ=0.500 (val F1=0.1607)
  Directional -> Accuracy: 0.5357, MCC: 0.1240, F1: 0.6176

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.42816 | val 0.81888
  Epoch 020 - train 0.22121 | val 1.42342
  Epoch 023 - train 0.17693 | val 1.12502
  Classification -> best τ=0.445 (val F1=0.2474)
  Directional -> Accuracy: 0.6087, MCC: 0.0000, F1: 0.7568

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.45642 | val 0.63157
  Epoch 020 - train 0.30114 | val 0.72294
  Epoch 030 - train 0.16614 | val 0.85757
  Classification -> best τ=0.300 (val F1=0.4556)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.47066 | val 1.29052
  Epoch 020 - train 0.26025 | val 2.62265
  Epoch 021 - train 0.26737 | val 2.63343
  Classification -> best τ=0.475 (val F1=0.3691)
  Directional -> Accuracy: 0.5541, MCC: 0.1070, F1: 0.4211

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.42864 | val 0.82772
  Epoch 020 - train 0.21357 | val 1.36943
  Epoch 025 - train 0.13783 | val 1.49115
  Classification -> best τ=0.475 (val F1=0.3873)
  Directional -> Accuracy: 0.5556, MCC: 0.1266, F1: 0.6667

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.44904 | val 0.71847
  Epoch 020 - train 0.23785 | val 0.96007
  Epoch 027 - train 0.10802 | val 1.25068
  Classification -> best τ=0.360 (val F1=0.2408)
  Directional -> Accuracy: 0.5476, MCC: 0.0000, F1: 0.6780

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.49048 | val 0.69979
  Epoch 020 - train 0.27613 | val 0.85948
  Epoch 030 - train 0.13091 | val 1.62671
  Classification -> best τ=0.455 (val F1=0.2689)
  Directional -> Accuracy: 0.3958, MCC: 0.1130, F1: 0.5538

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.50397 | val 0.91108
  Epoch 020 - train 0.34738 | val 1.32553
  Epoch 021 - train 0.35027 | val 1.44941
  Classification -> best τ=0.470 (val F1=0.1884)
  Directional -> Accuracy: 0.5455, MCC: 0.0177, F1: 0.6988

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.41706 | val 1.71441
  Epoch 020 - train 0.19024 | val 2.00704
  Epoch 021 - train 0.19462 | val 1.92363
  Classification -> best τ=0.500 (val F1=0.2914)
  Directional -> Accuracy: 0.5000, MCC: -0.0013, F1: 0.4815

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.49259 | val 1.10637
  Epoch 020 - train 0.28452 | val 1.91067
  Epoch 021 - train 0.27407 | val 2.14190

[I 2026-02-22 10:13:27,560] Trial 88 finished with value: 0.2770445837898889 and parameters: {'feature_set': 'sector_finbert', 'model_type': 'BiGRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 64, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.0, 'batch_size': 64, 'learning_rate': 0.0025806514974135125, 'weight_decay': 4.18162120074925e-06, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 20, 'max_epochs': 30, 'huber_delta': 1.2458108084814443, 'early_stopping_min_delta': 0.008563570173593582}. Best is trial 22 with value: 0.2833350641483003.

  Classification -> best τ=0.455 (val F1=0.1489)
  Directional -> Accuracy: 0.4667, MCC: -0.0733, F1: 0.4074

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2770445837898889
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d', 'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down', 'finbert_neutral']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.47992 | val 0.93889
  Epoch 011 - train 0.47120 | val 1.05636
  Classification -> best τ=0.455 (val F1=0.1396)
  Directional -> Accuracy: 0.5395, MCC: 0.1417, F1: 0.6067

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.40742 | val 0.70161
  Epoch 014 - train 0.29865 | val 0.82932
  Classification -> best τ=0.440 (val F1=0.2440)
  Directional -> Accuracy: 0.6000, MCC: 0.1273, F1: 0.7273

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.44485 | val 0.93444
  Epoch 011 - train 0.44046 | val 0.97545
  Classification -> best τ=0.535 (val F1=0.1979)
  Directional -> Accuracy: 0.5000, MCC: 0.0266, F1: 0.3429

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.47939 | val 0.74270
  Epoch 011 - train 0.45315 | val 0.87760
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5405, MCC: 0.0000, F1: 0.7018

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.41473 | val 0.81486
  Epoch 016 - train 0.31007 | val 1.14351
  Classification -> best τ=0.395 (val F1=0.3215)
  Directional -> Accuracy: 0.6800, MCC: 0.3677, F1: 0.6667

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.42056 | val 0.74526
  Epoch 011 - train 0.38287 | val 0.99383
  Classification -> best τ=0.495 (val F1=0.1808)
  Directional -> Accuracy: 0.5652, MCC: 0.1461, F1: 0.2857

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.45507 | val 1.26808
  Epoch 011 - train 0.42622 | val 1.69114
  Classification -> best τ=0.470 (val F1=0.1965)
  Directional -> Accuracy: 0.5147, MCC: 0.1667, F1: 0.5823

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.33618 | val 1.08097
  Epoch 013 - train 0.28099 | val 1.07161
  Classification -> best τ=0.520 (val F1=0.3689)
  Directional -> Accuracy: 0.5000, MCC: 0.0280, F1: 0.5116

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.42132 | val 0.89352
  Epoch 014 - train 0.35753 | val 1.40362
  Classification -> best τ=0.500 (val F1=0.2354)
  Directional -> Accuracy: 0.5625, MCC: 0.2182, F1: 0.6316

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.41958 | val 0.90614
  Epoch 012 - train 0.42092 | val 0.81068
  Classification -> best τ=0.460 (val F1=0.2679)
  Directional -> Accuracy: 0.4493, MCC: 0.0544, F1: 0.5870

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.43927 | val 1.03164
  Epoch 011 - train 0.42424 | val 1.28129
  Classification -> best τ=0.540 (val F1=0.2877)
  Directional -> Accuracy: 0.5918, MCC: 0.1635, F1: 0.2857

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.44850 | val 1.37674
  Epoch 011 - train 0.40477 | val 1.51834
  Classification -> best τ=0.470 (val F1=0.1528)
  Directional -> Accuracy: 0.6316, MCC: 0.2894, F1: 0.7042

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.41198 | val 1.03015
  Epoch 011 - train 0.40106 | val 1.21404
  Classification -> best τ=0.505 (val F1=0.0875)
  Directional -> Accuracy: 0.4762, MCC: -0.0912, F1: 0.3125

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.47575 | val 0.85148
  Epoch 011 - train 0.45642 | val 0.94391
  Classification -> best τ=0.510 (val F1=0.3864)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.48655 | val 0.74486
  Epoch 016 - train 0.35087 | val 1.68027
  Classification -> best τ=0.625 (val F1=0.2571)
  Directional -> Accuracy: 0.5490, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.45850 | val 1.36649
  Epoch 012 - train 0.40121 | val 1.62873
  Classification -> best τ=0.345 (val F1=0.2341)
  Directional -> Accuracy: 0.5797, MCC: 0.1688, F1: 0.7071

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.50709 | val 1.37498
  Epoch 011 - train 0.48150 | val 1.47566
  Classification -> best τ=0.575 (val F1=0.2276)
  Directional -> Accuracy: 0.4138, MCC: 0.1477, F1: 0.1053

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.42873 | val 1.20603
  Epoch 011 - train 0.39314 | val 1.58746
  Classification -> best τ=0.480 (val F1=0.0425)
  Directional -> Accuracy: 0.4533, MCC: -0.1453, F1: 0.5495

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.50563 | val 0.86701
  Epoch 013 - train 0.42045 | val 1.08395
  Classification -> best τ=0.390 (val F1=0.2803)
  Directional -> Accuracy: 0.5625, MCC: 0.1420, F1: 0.5758

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.45946 | val 0.86201
  Epoch 012 - train 0.43769 | val 0.93093
  Classification -> best τ=0.490 (val F1=0.3153)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.40832 | val 0.90783
  Epoch 011 - train 0.38724 | val 0.94224
  Classification -> best τ=0.460 (val F1=0.2064)
  Directional -> Accuracy: 0.5106, MCC: -0.0037, F1: 0.5818

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.44128 | val 0.98820
  Epoch 011 - train 0.40527 | val 1.23406
  Classification -> best τ=0.420 (val F1=0.2673)
  Directional -> Accuracy: 0.5846, MCC: 0.1709, F1: 0.5714

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.46628 | val 0.70621
  Epoch 018 - train 0.28774 | val 1.22863
  Classification -> best τ=0.930 (val F1=0.3833)
  Directional -> Accuracy: 0.5088, MCC: 0.0937, F1: 0.3913

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.48754 | val 1.07236
  Epoch 011 - train 0.46649 | val 1.05893
  Classification -> best τ=0.480 (val F1=0.0568)
  Directional -> Accuracy: 0.4923, MCC: 0.0075, F1: 0.5823

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.41371 | val 0.87601
  Epoch 013 - train 0.38790 | val 1.20406
  Classification -> best τ=0.425 (val F1=0.4051)
  Directional -> Accuracy: 0.5818, MCC: 0.1817, F1: 0.5660

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.39734 | val 0.69467
  Epoch 017 - train 0.21562 | val 0.90480
  Classification -> best τ=0.510 (val F1=0.3764)
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.5938

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.47147 | val 0.71476
  Epoch 011 - train 0.45307 | val 0.75827
  Classification -> best τ=0.540 (val F1=0.1353)
  Directional -> Accuracy: 0.4286, MCC: -0.0913, F1: 0.3333

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.46090 | val 0.88207
  Epoch 011 - train 0.40943 | val 0.95739
  Classification -> best τ=0.460 (val F1=0.2868)
  Directional -> Accuracy: 0.4643, MCC: 0.1211, F1: 0.0625

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.41936 | val 1.31117
  Epoch 011 - train 0.38435 | val 1.75483
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5500, MCC: 0.0000, F1: 0.7097

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.42293 | val 0.91828
  Epoch 011 - train 0.43016 | val 1.15445
  Classification -> best τ=0.605 (val F1=0.3501)
  Directional -> Accuracy: 0.5000, MCC: -0.0426, F1: 0.2222

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.47802 | val 1.24007
  Epoch 012 - train 0.40513 | val 1.69616
  Classification -> best τ=0.525 (val F1=0.1286)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.43836 | val 1.04201
  Epoch 011 - train 0.39153 | val 1.18083
  Classification -> best τ=0.475 (val F1=0.1903)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.49249 | val 0.72323
  Epoch 016 - train 0.32472 | val 1.25400
  Classification -> best τ=0.495 (val F1=0.3347)
  Directional -> Accuracy: 0.4444, MCC: 0.0000, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.39970 | val 0.92367
  Epoch 011 - train 0.37295 | val 0.97130
  Classification -> best τ=0.485 (val F1=0.3078)
  Directional -> Accuracy: 0.5814, MCC: 0.1835, F1: 0.4000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.47507 | val 1.46785
  Epoch 011 - train 0.49319 | val 1.20375
  Classification -> best τ=0.495 (val F1=0.2067)
  Directional -> Accuracy: 0.5606, MCC: -0.0140, F1: 0.7071

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.39719 | val 0.83438
  Epoch 011 - train 0.35867 | val 0.89900
  Classification -> best τ=0.485 (val F1=0.1715)
  Directional -> Accuracy: 0.5952, MCC: 0.2132, F1: 0.7018

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.37008 | val 1.32579
  Epoch 011 - train 0.36199 | val 1.46044
  Classification -> best τ=0.495 (val F1=0.2450)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.4815

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.36253 | val 0.70592
  Epoch 014 - train 0.29745 | val 0.89947
  Classification -> best τ=0.560 (val F1=0.3372)
  Directional -> Accuracy: 0.3696, MCC: -0.1490, F1: 0.0645

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.47604 | val 0.62947
  Epoch 020 - train 0.28972 | val 0.60812
  Epoch 026 - train 0.17388 | val 0.90715
  Classification -> best τ=0.345 (val F1=0.4556)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.46524 | val 1.29165
  Epoch 011 - train 0.43645 | val 1.62705
  Classification -> best τ=0.475 (val F1=0.2633)
  Directional -> Accuracy: 0.4459, MCC: -0.1279, F1: 0.3051

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.42825 | val 0.71353
  Epoch 011 - train 0.38515 | val 0.72220
  Classification -> best τ=0.500 (val F1=0.2668)
  Directional -> Accuracy: 0.4889, MCC: -0.0832, F1: 0.6462

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.43336 | val 0.75541
  Epoch 011 - train 0.40249 | val 0.76444
  Classification -> best τ=0.510 (val F1=0.2381)
  Directional -> Accuracy: 0.4524, MCC: -0.0574, F1: 0.4103

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.42476 | val 0.66312
  Epoch 020 - train 0.28232 | val 0.98491
  Epoch 021 - train 0.19502 | val 1.07179
  Classification -> best τ=0.780 (val F1=0.3311)
  Directional -> Accuracy: 0.5417, MCC: 0.0861, F1: 0.4762

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.47271 | val 0.75319
  Epoch 011 - train 0.44909 | val 0.74650
  Classification -> best τ=0.525 (val F1=0.1997)
  Directional -> Accuracy: 0.5455, MCC: 0.1826, F1: 0.3902

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.38506 | val 1.04524
  Epoch 011 - train 0.37396 | val 1.69849
  Classification -> best τ=0.510 (val F1=0.1949)
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.6506

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.46135 | val 0.88687
  Epoch 011 - train 0.44568 | val 0.96811
  Classification -> best τ=0.500 (val F1=0.2807)
  Directional -> Accuracy: 0.5472, MCC: 0.1056, F1: 0.6571

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.41965 | val 1.10393
  Epoch 011 - train 0.42039 | val 1.23579
  Classification -> best τ=0.600 (val F1=0.1166)
  Directional -> Accuracy: 0.4727, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.48641 | val 1.08583
  Epoch 011 - train 0.46256 | val 1.13427

[I 2026-02-22 10:14:44,527] Trial 89 finished with value: 0.23560130805239798 and parameters: {'feature_set': 'sector_finbert', 'model_type': 'BiGRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.0, 'batch_size': 64, 'learning_rate': 0.0022636254604583143, 'weight_decay': 8.432068226087221e-06, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 1.237035402890473, 'early_stopping_min_delta': 0.008547496623894587}. Best is trial 22 with value: 0.2833350641483003.

  Classification -> best τ=0.525 (val F1=0.1489)
  Directional -> Accuracy: 0.5167, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.23560130805239798
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d', 'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down', 'finbert_neutral']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.55532 | val 0.79202
  Epoch 016 - train 0.46043 | val 0.96579
  Classification -> best τ=0.650 (val F1=0.2510)
  Directional -> Accuracy: 0.5789, MCC: 0.1195, F1: 0.2727

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.50184 | val 0.81110
  Epoch 011 - train 0.48509 | val 0.86684
  Classification -> best τ=0.400 (val F1=0.1289)
  Directional -> Accuracy: 0.5778, MCC: 0.0000, F1: 0.7324

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.54428 | val 1.08369
  Epoch 011 - train 0.51188 | val 1.16774
  Classification -> best τ=0.520 (val F1=0.0135)
  Directional -> Accuracy: 0.5435, MCC: 0.0784, F1: 0.6038

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.58898 | val 0.69832
  Epoch 011 - train 0.56013 | val 0.78010
  Classification -> best τ=0.510 (val F1=0.1414)
  Directional -> Accuracy: 0.5000, MCC: -0.0044, F1: 0.5316

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.55527 | val 0.72410
  Epoch 014 - train 0.47679 | val 0.91880
  Classification -> best τ=0.565 (val F1=0.4602)
  Directional -> Accuracy: 0.6000, MCC: 0.2587, F1: 0.4737

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.51128 | val 0.73622
  Epoch 011 - train 0.50802 | val 0.98790
  Classification -> best τ=0.485 (val F1=0.2937)
  Directional -> Accuracy: 0.4783, MCC: -0.0596, F1: 0.3684

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.54728 | val 1.66556
  Epoch 011 - train 0.55879 | val 1.74132
  Classification -> best τ=0.490 (val F1=0.2536)
  Directional -> Accuracy: 0.5147, MCC: 0.1115, F1: 0.5479

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.53757 | val 0.55377
  Epoch 020 - train 0.28385 | val 0.76407
  Epoch 021 - train 0.32781 | val 0.71955
  Classification -> best τ=0.270 (val F1=0.3158)
  Directional -> Accuracy: 0.4524, MCC: 0.1353, F1: 0.6102

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.51860 | val 1.18297
  Epoch 011 - train 0.47965 | val 1.27469
  Classification -> best τ=0.485 (val F1=0.2231)
  Directional -> Accuracy: 0.4375, MCC: 0.0000, F1: 0.6087

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.49891 | val 0.68744
  Epoch 018 - train 0.39048 | val 0.92681
  Classification -> best τ=0.605 (val F1=0.2880)
  Directional -> Accuracy: 0.4638, MCC: -0.0573, F1: 0.4478

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.57107 | val 0.90804
  Epoch 011 - train 0.55999 | val 0.79795
  Classification -> best τ=0.545 (val F1=0.3961)
  Directional -> Accuracy: 0.5918, MCC: 0.1804, F1: 0.2308

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.56563 | val 0.90190
  Epoch 011 - train 0.54819 | val 1.04946
  Classification -> best τ=0.455 (val F1=0.0572)
  Directional -> Accuracy: 0.5439, MCC: 0.1204, F1: 0.6750

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.51936 | val 1.18906
  Epoch 011 - train 0.49354 | val 1.17162
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.6230

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.54315 | val 0.87201
  Epoch 011 - train 0.51855 | val 0.87107
  Classification -> best τ=0.485 (val F1=0.3378)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.50882 | val 0.90627
  Epoch 012 - train 0.51408 | val 0.73499
  Classification -> best τ=0.490 (val F1=0.2571)
  Directional -> Accuracy: 0.5490, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.52542 | val 1.17596
  Epoch 011 - train 0.53318 | val 1.25298
  Classification -> best τ=0.545 (val F1=0.1614)
  Directional -> Accuracy: 0.5072, MCC: 0.0765, F1: 0.3200

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.54688 | val 0.98773
  Epoch 011 - train 0.53378 | val 1.06311
  Classification -> best τ=0.575 (val F1=0.1913)
  Directional -> Accuracy: 0.3793, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.52782 | val 1.14038
  Epoch 011 - train 0.51610 | val 1.42179
  Classification -> best τ=0.545 (val F1=0.1087)
  Directional -> Accuracy: 0.4000, MCC: -0.0602, F1: 0.1176

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.50712 | val 1.26122
  Epoch 012 - train 0.50453 | val 0.98800
  Classification -> best τ=0.375 (val F1=0.3140)
  Directional -> Accuracy: 0.5000, MCC: 0.0579, F1: 0.4483

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.53616 | val 0.78348
  Epoch 013 - train 0.47096 | val 0.85889
  Classification -> best τ=0.430 (val F1=0.2899)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.52123 | val 0.86090
  Epoch 011 - train 0.53007 | val 1.05519
  Classification -> best τ=0.565 (val F1=0.1383)
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.60112 | val 0.86198
  Epoch 011 - train 0.55913 | val 0.92034
  Classification -> best τ=0.505 (val F1=0.1994)
  Directional -> Accuracy: 0.4923, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.56244 | val 0.82515
  Epoch 017 - train 0.39577 | val 1.57782
  Classification -> best τ=0.845 (val F1=0.3144)
  Directional -> Accuracy: 0.5088, MCC: 0.0801, F1: 0.4167

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.56617 | val 0.83150
  Epoch 011 - train 0.54138 | val 0.84055
  Classification -> best τ=0.460 (val F1=0.1122)
  Directional -> Accuracy: 0.4769, MCC: 0.0000, F1: 0.6458

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.49704 | val 0.90480
  Epoch 013 - train 0.43027 | val 1.09383
  Classification -> best τ=0.355 (val F1=0.4051)
  Directional -> Accuracy: 0.5455, MCC: 0.0690, F1: 0.6154

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.48531 | val 0.81065
  Epoch 013 - train 0.40195 | val 0.72687
  Classification -> best τ=0.500 (val F1=0.3039)
  Directional -> Accuracy: 0.4444, MCC: 0.1289, F1: 0.6032

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.55755 | val 0.69448
  Epoch 012 - train 0.54108 | val 0.73529
  Classification -> best τ=0.545 (val F1=0.1936)
  Directional -> Accuracy: 0.4048, MCC: -0.1803, F1: 0.0000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.51340 | val 0.96187
  Epoch 011 - train 0.48163 | val 0.99021
  Classification -> best τ=0.435 (val F1=0.2386)
  Directional -> Accuracy: 0.4464, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.52962 | val 1.24194
  Epoch 012 - train 0.41948 | val 1.98467
  Classification -> best τ=0.485 (val F1=0.1608)
  Directional -> Accuracy: 0.4750, MCC: -0.1069, F1: 0.5882

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.57404 | val 0.83369
  Epoch 011 - train 0.52517 | val 0.85993
  Classification -> best τ=0.565 (val F1=0.3501)
  Directional -> Accuracy: 0.4286, MCC: -0.1409, F1: 0.4286

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.54049 | val 1.21614
  Epoch 011 - train 0.55331 | val 1.15981
  Classification -> best τ=0.445 (val F1=0.0521)
  Directional -> Accuracy: 0.5952, MCC: 0.1658, F1: 0.6909

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.51641 | val 1.12732
  Epoch 011 - train 0.51624 | val 1.18225
  Classification -> best τ=0.460 (val F1=0.2716)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.54895 | val 0.82914
  Epoch 011 - train 0.52896 | val 1.05977
  Classification -> best τ=0.495 (val F1=0.2663)
  Directional -> Accuracy: 0.4583, MCC: 0.0466, F1: 0.0930

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.53416 | val 1.00177
  Epoch 011 - train 0.51703 | val 1.02761
  Classification -> best τ=0.500 (val F1=0.2603)
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.54282 | val 1.17804
  Epoch 011 - train 0.52894 | val 1.12111
  Classification -> best τ=0.465 (val F1=0.2358)
  Directional -> Accuracy: 0.5909, MCC: 0.1376, F1: 0.6747

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.48195 | val 1.05085
  Epoch 011 - train 0.44507 | val 0.99078
  Classification -> best τ=0.425 (val F1=0.2658)
  Directional -> Accuracy: 0.7381, MCC: 0.4835, F1: 0.7317

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.44733 | val 1.27110
  Epoch 011 - train 0.40262 | val 1.46668
  Classification -> best τ=0.420 (val F1=0.2841)
  Directional -> Accuracy: 0.5893, MCC: 0.2253, F1: 0.6462

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.51445 | val 0.74492
  Epoch 011 - train 0.51508 | val 0.83697
  Classification -> best τ=0.485 (val F1=0.3397)
  Directional -> Accuracy: 0.5652, MCC: -0.0894, F1: 0.7143

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.55517 | val 0.61526
  Epoch 020 - train 0.38727 | val 0.61326
  Epoch 023 - train 0.29230 | val 0.61740
  Classification -> best τ=0.645 (val F1=0.5075)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.51144 | val 1.39187
  Epoch 011 - train 0.50035 | val 1.50345
  Classification -> best τ=0.450 (val F1=0.1836)
  Directional -> Accuracy: 0.4865, MCC: 0.0000, F1: 0.6545

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.55959 | val 0.65192
  Epoch 020 - train 0.30056 | val 0.98597
  Classification -> best τ=0.530 (val F1=0.4080)
  Directional -> Accuracy: 0.6667, MCC: 0.3382, F1: 0.7059

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.46946 | val 0.79993
  Epoch 012 - train 0.42296 | val 0.82021
  Classification -> best τ=0.465 (val F1=0.2303)
  Directional -> Accuracy: 0.5000, MCC: 0.0138, F1: 0.5116

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.58516 | val 0.71730
  Epoch 020 - train 0.35788 | val 0.95266
  Epoch 022 - train 0.32504 | val 1.24312
  Classification -> best τ=0.455 (val F1=0.5249)
  Directional -> Accuracy: 0.4375, MCC: 0.1233, F1: 0.5574

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.54310 | val 0.87897
  Epoch 011 - train 0.56557 | val 0.98151
  Classification -> best τ=0.490 (val F1=0.2833)
  Directional -> Accuracy: 0.5455, MCC: 0.0000, F1: 0.7059

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.48541 | val 1.13796
  Epoch 011 - train 0.52647 | val 0.92412
  Classification -> best τ=0.485 (val F1=0.3988)
  Directional -> Accuracy: 0.5714, MCC: 0.1801, F1: 0.6471

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.57804 | val 0.79513
  Epoch 013 - train 0.52749 | val 1.06840
  Classification -> best τ=0.495 (val F1=0.1691)
  Directional -> Accuracy: 0.6038, MCC: 0.2301, F1: 0.6866

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.50761 | val 1.61663
  Epoch 011 - train 0.48881 | val 2.70412
  Classification -> best τ=0.635 (val F1=0.1166)
  Directional -> Accuracy: 0.4182, MCC: -0.1718, F1: 0.1579

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.55548 | val 0.68151

[I 2026-02-22 10:15:33,575] Trial 90 finished with value: 0.25097766724203746 and parameters: {'feature_set': 'sector_finbert', 'model_type': 'BiGRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 32, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.5, 'batch_size': 64, 'learning_rate': 0.005975133716972518, 'weight_decay': 4.247271710257053e-06, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 1.179622275693386, 'early_stopping_min_delta': 0.0076884952263983}. Best is trial 22 with value: 0.2833350641483003.

  Epoch 020 - train 0.42157 | val 0.77636
  Epoch 021 - train 0.39540 | val 0.80949
  Classification -> best τ=0.635 (val F1=0.3496)
  Directional -> Accuracy: 0.5500, MCC: 0.0946, F1: 0.4255

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.25097766724203746
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d', 'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down', 'finbert_neutral']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.45805 | val 0.91707
  Epoch 020 - train 0.26802 | val 1.37038
  Epoch 024 - train 0.16931 | val 1.60896
  Classification -> best τ=0.575 (val F1=0.2510)
  Directional -> Accuracy: 0.6316, MCC: 0.2549, F1: 0.5882

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.37689 | val 0.71720
  Epoch 020 - train 0.17815 | val 1.54694
  Epoch 021 - train 0.15454 | val 1.89158
  Classification -> best τ=0.415 (val F1=0.1924)
  Directional -> Accuracy: 0.5778, MCC: 0.0000, F1: 0.7324

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.44188 | val 1.48281
  Epoch 020 - train 0.23820 | val 3.32948
  Epoch 022 - train 0.20706 | val 3.48907
  Classification -> best τ=0.535 (val F1=0.2727)
  Directional -> Accuracy: 0.4783, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.47795 | val 0.96777
  Epoch 020 - train 0.28694 | val 1.45734
  Epoch 022 - train 0.23817 | val 0.94500
  Classification -> best τ=0.455 (val F1=0.0520)
  Directional -> Accuracy: 0.4324, MCC: -0.1808, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.42761 | val 0.78294
  Epoch 020 - train 0.23849 | val 1.47470
  Epoch 025 - train 0.15143 | val 1.75748
  Classification -> best τ=0.505 (val F1=0.4139)
  Directional -> Accuracy: 0.6200, MCC: 0.2957, F1: 0.5128

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.41942 | val 0.80146
  Epoch 020 - train 0.23344 | val 2.39792
  Epoch 021 - train 0.21303 | val 2.98785
  Classification -> best τ=0.520 (val F1=0.4070)
  Directional -> Accuracy: 0.5217, MCC: 0.0229, F1: 0.3125

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.43795 | val 1.43742
  Epoch 020 - train 0.19915 | val 2.85980
  Epoch 021 - train 0.17448 | val 3.10996
  Classification -> best τ=0.495 (val F1=0.3110)
  Directional -> Accuracy: 0.5147, MCC: 0.1667, F1: 0.5823

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.38008 | val 0.52309
  Epoch 020 - train 0.16011 | val 0.84379
  Epoch 030 - train 0.03439 | val 1.21950
  Classification -> best τ=0.290 (val F1=0.4215)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.5660

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.40689 | val 1.04258
  Epoch 020 - train 0.18777 | val 1.51400
  Epoch 023 - train 0.17652 | val 2.25711
  Classification -> best τ=0.610 (val F1=0.1928)
  Directional -> Accuracy: 0.6042, MCC: 0.1690, F1: 0.3448

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.45782 | val 0.89470
  Epoch 020 - train 0.19240 | val 1.30240
  Epoch 021 - train 0.21292 | val 1.45883
  Classification -> best τ=0.470 (val F1=0.1973)
  Directional -> Accuracy: 0.5362, MCC: 0.1896, F1: 0.6098

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.47059 | val 1.03950
  Epoch 020 - train 0.24247 | val 2.71647
  Epoch 021 - train 0.23915 | val 2.76237
  Classification -> best τ=0.565 (val F1=0.3590)
  Directional -> Accuracy: 0.6122, MCC: 0.2379, F1: 0.2963

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.41450 | val 2.16292
  Epoch 020 - train 0.19900 | val 3.27494
  Epoch 021 - train 0.24416 | val 3.32069
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5088, MCC: 0.0000, F1: 0.6744

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.37156 | val 1.08427
  Epoch 020 - train 0.19172 | val 3.06323
  Epoch 021 - train 0.20361 | val 3.01900
  Classification -> best τ=0.475 (val F1=0.1658)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.6230

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.44518 | val 1.22315
  Epoch 020 - train 0.24018 | val 2.05304
  Epoch 022 - train 0.20648 | val 1.99908
  Classification -> best τ=0.485 (val F1=0.4109)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.48149 | val 1.85325
  Epoch 020 - train 0.21837 | val 2.56139
  Epoch 022 - train 0.19027 | val 3.09013
  Classification -> best τ=0.530 (val F1=0.1455)
  Directional -> Accuracy: 0.5490, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.47486 | val 1.39758
  Epoch 020 - train 0.27980 | val 1.96298
  Epoch 022 - train 0.27518 | val 2.28621
  Classification -> best τ=0.510 (val F1=0.1850)
  Directional -> Accuracy: 0.5217, MCC: 0.0750, F1: 0.4407

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.48193 | val 1.06535
  Epoch 020 - train 0.24866 | val 2.40830
  Epoch 021 - train 0.23645 | val 2.57000
  Classification -> best τ=0.545 (val F1=0.1842)
  Directional -> Accuracy: 0.3966, MCC: 0.1035, F1: 0.0541

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.45440 | val 1.50073
  Epoch 020 - train 0.19643 | val 2.45161
  Epoch 021 - train 0.21027 | val 2.38353
  Classification -> best τ=0.490 (val F1=0.0818)
  Directional -> Accuracy: 0.4933, MCC: -0.2402, F1: 0.6545

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.43965 | val 1.06117
  Epoch 020 - train 0.25332 | val 1.25548
  Epoch 023 - train 0.20868 | val 1.67559
  Classification -> best τ=0.255 (val F1=0.3057)
  Directional -> Accuracy: 0.5781, MCC: 0.0000, F1: 0.7327

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.49304 | val 0.74343
  Epoch 020 - train 0.27801 | val 1.15947
  Epoch 023 - train 0.33323 | val 1.52029
  Classification -> best τ=0.490 (val F1=0.2903)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.41059 | val 1.31186
  Epoch 020 - train 0.16030 | val 1.84035
  Epoch 021 - train 0.20398 | val 1.78291
  Classification -> best τ=0.485 (val F1=0.3285)
  Directional -> Accuracy: 0.4681, MCC: 0.0346, F1: 0.4186

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.41447 | val 1.14126
  Epoch 020 - train 0.20108 | val 2.04883
  Epoch 024 - train 0.16765 | val 2.19209
  Classification -> best τ=0.525 (val F1=0.3150)
  Directional -> Accuracy: 0.4923, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.52357 | val 0.88839
  Epoch 020 - train 0.21369 | val 1.39405
  Epoch 024 - train 0.16166 | val 1.96962
  Classification -> best τ=0.770 (val F1=0.3833)
  Directional -> Accuracy: 0.4211, MCC: -0.1512, F1: 0.0000

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.51060 | val 1.22455
  Epoch 020 - train 0.25156 | val 1.50108
  Epoch 021 - train 0.19302 | val 1.69731
  Classification -> best τ=0.455 (val F1=0.1599)
  Directional -> Accuracy: 0.4769, MCC: 0.0000, F1: 0.6458

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.42201 | val 1.02218
  Epoch 020 - train 0.23725 | val 2.03715
  Epoch 024 - train 0.19306 | val 2.62511
  Classification -> best τ=0.395 (val F1=0.4051)
  Directional -> Accuracy: 0.5636, MCC: 0.1587, F1: 0.5200

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.39117 | val 0.70651
  Epoch 020 - train 0.20310 | val 0.92593
  Epoch 028 - train 0.11367 | val 2.12181
  Classification -> best τ=0.470 (val F1=0.4947)
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.5938

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.47365 | val 0.71244
  Epoch 020 - train 0.26055 | val 1.20278
  Epoch 024 - train 0.18405 | val 1.38604
  Classification -> best τ=0.595 (val F1=0.1353)
  Directional -> Accuracy: 0.4524, MCC: 0.1353, F1: 0.0800

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.42268 | val 1.02481
  Epoch 020 - train 0.26037 | val 1.74618
  Epoch 022 - train 0.21937 | val 1.87489
  Classification -> best τ=0.525 (val F1=0.2850)
  Directional -> Accuracy: 0.4464, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.44459 | val 0.96378
  Epoch 020 - train 0.25205 | val 2.82231
  Epoch 021 - train 0.23991 | val 2.75197
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5500, MCC: 0.0000, F1: 0.7097

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.45089 | val 0.67205
  Epoch 020 - train 0.24995 | val 1.10534
  Epoch 030 - train 0.10326 | val 1.15728
  Classification -> best τ=0.650 (val F1=0.4677)
  Directional -> Accuracy: 0.4286, MCC: -0.1455, F1: 0.4000

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.47852 | val 1.14242
  Epoch 020 - train 0.24466 | val 1.54438
  Epoch 021 - train 0.25264 | val 1.73782
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5476, MCC: 0.0000, F1: 0.7077

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.41335 | val 1.35823
  Epoch 020 - train 0.22544 | val 2.34206
  Epoch 021 - train 0.19866 | val 2.51196
  Classification -> best τ=0.495 (val F1=0.1981)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.43332 | val 1.04906
  Epoch 020 - train 0.18390 | val 2.04212
  Epoch 023 - train 0.12716 | val 1.87842
  Classification -> best τ=0.395 (val F1=0.2932)
  Directional -> Accuracy: 0.5139, MCC: 0.1147, F1: 0.3636

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.42905 | val 0.98385
  Epoch 020 - train 0.17479 | val 1.84506
  Epoch 021 - train 0.17274 | val 1.92087
  Classification -> best τ=0.480 (val F1=0.3078)
  Directional -> Accuracy: 0.5349, MCC: 0.0664, F1: 0.4737

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.50782 | val 1.49656
  Epoch 020 - train 0.29714 | val 2.03068
  Epoch 021 - train 0.33109 | val 2.05035
  Classification -> best τ=0.435 (val F1=0.2778)
  Directional -> Accuracy: 0.5606, MCC: 0.0162, F1: 0.6947

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.44515 | val 0.82532
  Epoch 020 - train 0.20773 | val 1.54559
  Epoch 022 - train 0.20481 | val 1.75005
  Classification -> best τ=0.460 (val F1=0.2858)
  Directional -> Accuracy: 0.6667, MCC: 0.3441, F1: 0.6500

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.40051 | val 1.58213
  Epoch 020 - train 0.16138 | val 3.08124
  Epoch 021 - train 0.14578 | val 3.74437
  Classification -> best τ=0.435 (val F1=0.1690)
  Directional -> Accuracy: 0.4464, MCC: -0.1100, F1: 0.4151

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.39574 | val 0.92424
  Epoch 020 - train 0.15647 | val 1.53778
  Epoch 023 - train 0.11341 | val 1.70183
  Classification -> best τ=0.400 (val F1=0.2474)
  Directional -> Accuracy: 0.6087, MCC: 0.0000, F1: 0.7568

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.44328 | val 0.65090
  Epoch 020 - train 0.24686 | val 0.72276
  Epoch 030 - train 0.13168 | val 1.23404
  Classification -> best τ=0.340 (val F1=0.4973)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.44114 | val 1.26152
  Epoch 020 - train 0.24239 | val 2.50939
  Epoch 022 - train 0.19604 | val 2.83206
  Classification -> best τ=0.420 (val F1=0.3304)
  Directional -> Accuracy: 0.4865, MCC: 0.0000, F1: 0.6545

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.41696 | val 0.72348
  Epoch 020 - train 0.16809 | val 1.38774
  Epoch 026 - train 0.12099 | val 2.18078
  Classification -> best τ=0.545 (val F1=0.2874)
  Directional -> Accuracy: 0.5333, MCC: 0.0644, F1: 0.6316

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.41558 | val 0.73720
  Epoch 020 - train 0.18011 | val 1.05706
  Epoch 021 - train 0.15828 | val 0.95490
  Classification -> best τ=0.485 (val F1=0.1667)
  Directional -> Accuracy: 0.5714, MCC: 0.1376, F1: 0.6087

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.40500 | val 0.70031
  Epoch 020 - train 0.24437 | val 1.11108
  Epoch 024 - train 0.17818 | val 1.58705
  Classification -> best τ=0.445 (val F1=0.5131)
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.5455

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.48911 | val 0.91181
  Epoch 020 - train 0.32900 | val 1.43259
  Epoch 021 - train 0.28740 | val 1.32740
  Classification -> best τ=0.525 (val F1=0.2184)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.39329 | val 1.74012
  Epoch 020 - train 0.18448 | val 1.95760
  Epoch 021 - train 0.17049 | val 2.37694
  Classification -> best τ=0.515 (val F1=0.4282)
  Directional -> Accuracy: 0.5357, MCC: 0.0680, F1: 0.5000

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.43374 | val 1.54290
  Epoch 020 - train 0.22169 | val 2.49299

[I 2026-02-22 10:17:16,157] Trial 91 finished with value: 0.2651519415082863 and parameters: {'feature_set': 'sector_finbert', 'model_type': 'BiGRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 64, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.0, 'batch_size': 64, 'learning_rate': 0.003286836838613019, 'weight_decay': 1.4076128731362138e-06, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 20, 'max_epochs': 30, 'huber_delta': 1.280081997807797, 'early_stopping_min_delta': 0.002651919656333512}. Best is trial 22 with value: 0.2833350641483003.

  Epoch 023 - train 0.21753 | val 1.93081
  Classification -> best τ=0.520 (val F1=0.2691)
  Directional -> Accuracy: 0.5167, MCC: 0.0184, F1: 0.3256

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2651519415082863
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 30
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d', 'sentiment', 'emotion_anger', 'emotion_disgust', 'emotion_fear', 'emotion_joy', 'emotion_neutral', 'emotion_sadness', 'emotion_surprize', 'emotion_anger_pct', 'emotion_disgust_pct', 'emotion_fear_pct', 'emotion_joy_pct', 'emotion_neutral_pct', 'emotion_sadness_pct', 'emotion_surprize_pct', 'positive_emotion', 'negative_emotion', 'uncertainty_emotion', 'positive_emotion_pct', 'negative_emotion_pct', 'uncertainty_emotion_pct', 'stance_label', 'stance_score', 'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down', 'finbert_neutral']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.44684 | val 0.92571
  Epoch 020 - train 0.22650 | val 1.88827
  Epoch 021 - train 0.21427 | val 1.83512
  Classification -> best τ=0.540 (val F1=0.1811)
  Directional -> Accuracy: 0.5200, MCC: 0.0365, F1: 0.4857

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 106). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.39532 | val 0.90396
  Epoch 020 - train 0.20088 | val 1.44135
  Epoch 021 - train 0.19046 | val 1.51622
  Classification -> best τ=0.415 (val F1=0.1730)
  Directional -> Accuracy: 0.5909, MCC: 0.0000, F1: 0.7429

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 106). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.45817 | val 0.81201
  Epoch 020 - train 0.23768 | val 1.29962
  Epoch 021 - train 0.19774 | val 1.36160
  Classification -> best τ=0.470 (val F1=0.0877)
  Directional -> Accuracy: 0.5778, MCC: 0.2211, F1: 0.4571

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.44191 | val 1.27338
  Epoch 020 - train 0.24345 | val 2.44045
  Epoch 021 - train 0.22627 | val 2.46426
  Classification -> best τ=0.515 (val F1=0.1070)
  Directional -> Accuracy: 0.4795, MCC: -0.0206, F1: 0.4062

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.44082 | val 0.69950
  Epoch 020 - train 0.18976 | val 1.02890
  Epoch 023 - train 0.13118 | val 1.20826
  Classification -> best τ=0.530 (val F1=0.3100)
  Directional -> Accuracy: 0.4898, MCC: -0.0061, F1: 0.1379

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.43863 | val 0.72280
  Epoch 020 - train 0.20268 | val 1.40022
  Epoch 027 - train 0.13799 | val 2.05200
  Classification -> best τ=0.415 (val F1=0.3188)
  Directional -> Accuracy: 0.5333, MCC: 0.0653, F1: 0.5116

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.47760 | val 1.02912
  Epoch 020 - train 0.18204 | val 2.09071
  Epoch 021 - train 0.19943 | val 2.33594
  Classification -> best τ=0.475 (val F1=0.1152)
  Directional -> Accuracy: 0.5075, MCC: 0.1294, F1: 0.5714

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 106). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 106). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.42601 | val 0.67819
  Epoch 020 - train 0.22347 | val 1.19427
  Epoch 027 - train 0.11739 | val 1.59501
  Classification -> best τ=0.565 (val F1=0.3612)
  Directional -> Accuracy: 0.4634, MCC: -0.1032, F1: 0.3529

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.45497 | val 0.70292
  Epoch 020 - train 0.18743 | val 0.95079
  Epoch 027 - train 0.09615 | val 1.08024
  Classification -> best τ=0.485 (val F1=0.2962)
  Directional -> Accuracy: 0.5745, MCC: 0.2932, F1: 0.6667

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 106). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 106). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 106). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.39592 | val 0.83860
  Epoch 020 - train 0.18068 | val 1.04950
  Epoch 025 - train 0.10746 | val 1.85359
  Classification -> best τ=0.375 (val F1=0.1846)
  Directional -> Accuracy: 0.4412, MCC: 0.0405, F1: 0.5957

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.45544 | val 0.94512
  Epoch 020 - train 0.20665 | val 1.49776
  Epoch 021 - train 0.22112 | val 1.55095
  Classification -> best τ=0.510 (val F1=0.1920)
  Directional -> Accuracy: 0.5625, MCC: 0.1586, F1: 0.0870

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.44034 | val 1.09198
  Epoch 020 - train 0.21536 | val 2.47743
  Epoch 021 - train 0.18263 | val 2.94951
  Classification -> best τ=0.525 (val F1=0.1448)
  Directional -> Accuracy: 0.5714, MCC: 0.1526, F1: 0.6757

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 106). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.43623 | val 1.46469
  Epoch 020 - train 0.22087 | val 3.63770
  Epoch 021 - train 0.19890 | val 3.67143
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4898, MCC: 0.0000, F1: 0.6575

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 106). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.43825 | val 0.78814
  Epoch 020 - train 0.24654 | val 1.37570
  Epoch 024 - train 0.17619 | val 1.48971
  Classification -> best τ=0.430 (val F1=0.3738)
  Directional -> Accuracy: 0.4746, MCC: -0.1336, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.47320 | val 0.82277
  Epoch 020 - train 0.26553 | val 1.38467
  Epoch 021 - train 0.23196 | val 1.50132
  Classification -> best τ=0.505 (val F1=0.2975)
  Directional -> Accuracy: 0.5600, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.47095 | val 0.92403
  Epoch 020 - train 0.26499 | val 1.32650
  Epoch 021 - train 0.25477 | val 1.37867
  Classification -> best τ=0.505 (val F1=0.3005)
  Directional -> Accuracy: 0.5000, MCC: -0.0587, F1: 0.6383

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 106). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.46068 | val 1.30806
  Epoch 020 - train 0.18373 | val 2.65545
  Epoch 021 - train 0.18420 | val 2.76177
  Classification -> best τ=0.555 (val F1=0.0851)
  Directional -> Accuracy: 0.4035, MCC: 0.0255, F1: 0.1053

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.43109 | val 1.09436
  Epoch 020 - train 0.24597 | val 1.60287
  Epoch 021 - train 0.21459 | val 1.55655
  Classification -> best τ=0.530 (val F1=0.1895)
  Directional -> Accuracy: 0.4054, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.45964 | val 0.66780
  Epoch 020 - train 0.22567 | val 1.03483
  Epoch 029 - train 0.07480 | val 1.57229
  Classification -> best τ=0.240 (val F1=0.3117)
  Directional -> Accuracy: 0.5714, MCC: 0.1788, F1: 0.5714

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 106). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.45741 | val 0.84939
  Epoch 020 - train 0.23571 | val 1.56854
  Epoch 023 - train 0.19306 | val 1.48768
  Classification -> best τ=0.480 (val F1=0.2725)
  Directional -> Accuracy: 0.4521, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.41832 | val 0.77700
  Epoch 020 - train 0.16134 | val 2.13278
  Epoch 021 - train 0.14750 | val 2.56524
  Classification -> best τ=0.475 (val F1=0.2249)
  Directional -> Accuracy: 0.6087, MCC: 0.0000, F1: 0.7568

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 106). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 106). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 106). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.42466 | val 1.07703
  Epoch 020 - train 0.21459 | val 1.41973
  Epoch 021 - train 0.19966 | val 1.65975
  Classification -> best τ=0.435 (val F1=0.2173)
  Directional -> Accuracy: 0.5156, MCC: 0.0739, F1: 0.1143

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.46743 | val 0.68559
  Epoch 020 - train 0.19734 | val 1.29428
  Epoch 024 - train 0.12810 | val 1.47930
  Classification -> best τ=0.490 (val F1=0.3727)
  Directional -> Accuracy: 0.6250, MCC: 0.2105, F1: 0.7342

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.46251 | val 0.86837
  Epoch 020 - train 0.24125 | val 1.19141
  Epoch 021 - train 0.21230 | val 1.27723
  Classification -> best τ=0.490 (val F1=0.1183)
  Directional -> Accuracy: 0.5469, MCC: 0.1306, F1: 0.6133

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.46048 | val 0.80270
  Epoch 020 - train 0.20748 | val 1.93171
  Epoch 023 - train 0.18580 | val 2.22650
  Classification -> best τ=0.500 (val F1=0.3164)
  Directional -> Accuracy: 0.5370, MCC: 0.1558, F1: 0.3590

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.41711 | val 0.68749
  Epoch 020 - train 0.19443 | val 0.96583
  Epoch 021 - train 0.16898 | val 1.09257
  Classification -> best τ=0.515 (val F1=0.2160)
  Directional -> Accuracy: 0.4186, MCC: 0.0000, F1: 0.5902

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.45580 | val 0.74819
  Epoch 020 - train 0.21206 | val 1.84991
  Epoch 021 - train 0.17732 | val 2.12237
  Classification -> best τ=0.530 (val F1=0.2645)
  Directional -> Accuracy: 0.5714, MCC: -0.0389, F1: 0.7200

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.46393 | val 0.88196
  Epoch 020 - train 0.21959 | val 1.78970
  Epoch 021 - train 0.21979 | val 1.95827
  Classification -> best τ=0.440 (val F1=0.2132)
  Directional -> Accuracy: 0.4909, MCC: -0.0133, F1: 0.5000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.43861 | val 0.77272
  Epoch 020 - train 0.24219 | val 1.14123
  Epoch 021 - train 0.21697 | val 1.24419
  Classification -> best τ=0.530 (val F1=0.1288)
  Directional -> Accuracy: 0.5000, MCC: -0.0752, F1: 0.6275

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.48248 | val 0.92509
  Epoch 020 - train 0.29599 | val 1.42682
  Epoch 021 - train 0.27121 | val 1.46746
  Classification -> best τ=0.520 (val F1=0.3150)
  Directional -> Accuracy: 0.4878, MCC: -0.0403, F1: 0.3226

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.50764 | val 0.78670
  Epoch 020 - train 0.30016 | val 1.12947
  Epoch 021 - train 0.27459 | val 1.16390
  Classification -> best τ=0.535 (val F1=0.0134)
  Directional -> Accuracy: 0.6098, MCC: 0.2560, F1: 0.7419

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.42059 | val 0.93920
  Epoch 020 - train 0.19686 | val 1.89420
  Epoch 021 - train 0.17823 | val 1.92597
  Classification -> best τ=0.535 (val F1=0.2739)
  Directional -> Accuracy: 0.6250, MCC: 0.3555, F1: 0.7353

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.41391 | val 0.90477
  Epoch 020 - train 0.19058 | val 1.37907
  Epoch 025 - train 0.11263 | val 1.60570
  Classification -> best τ=0.435 (val F1=0.3323)
  Directional -> Accuracy: 0.5211, MCC: 0.0888, F1: 0.4688

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 106). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.42770 | val 0.84279
  Epoch 020 - train 0.18226 | val 1.67108
  Epoch 021 - train 0.18568 | val 1.77728
  Classification -> best τ=0.470 (val F1=0.1844)
  Directional -> Accuracy: 0.4762, MCC: -0.0337, F1: 0.5417

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for PCG (101 < 106). Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.45869 | val 0.99443
  Epoch 020 - train 0.24295 | val 1.43972
  Epoch 021 - train 0.21969 | val 1.45570
  Classification -> best τ=0.415 (val F1=0.3488)
  Directional -> Accuracy: 0.5231, MCC: -0.0466, F1: 0.6517

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.41064 | val 0.65276
  Epoch 020 - train 0.15745 | val 0.87693
  Epoch 027 - train 0.08674 | val 0.99674
  Classification -> best τ=0.400 (val F1=0.3873)
  Directional -> Accuracy: 0.5250, MCC: 0.0409, F1: 0.5778

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.40291 | val 0.87853
  Epoch 020 - train 0.15836 | val 1.82907
  Epoch 021 - train 0.15924 | val 1.94498
  Classification -> best τ=0.475 (val F1=0.2048)
  Directional -> Accuracy: 0.5636, MCC: 0.1827, F1: 0.6250

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.43258 | val 0.88949
  Epoch 020 - train 0.20073 | val 1.79007
  Epoch 021 - train 0.18535 | val 1.80726
  Classification -> best τ=0.535 (val F1=0.2241)
  Directional -> Accuracy: 0.4222, MCC: 0.0027, F1: 0.2778

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 106). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 106). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 106). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 106). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.43098 | val 0.70148
  Epoch 020 - train 0.18590 | val 0.91724
  Epoch 021 - train 0.16365 | val 0.98956
  Classification -> best τ=0.480 (val F1=0.3116)
  Directional -> Accuracy: 0.3261, MCC: 0.0000, F1: 0.4918

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 106). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 106). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 106). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.40951 | val 1.30530
  Epoch 020 - train 0.16991 | val 3.13844
  Epoch 021 - train 0.15862 | val 3.27343
  Classification -> best τ=0.510 (val F1=0.0763)
  Directional -> Accuracy: 0.4110, MCC: -0.1927, F1: 0.5169

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 106). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 106). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 106). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 106). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.43582 | val 0.74197
  Epoch 020 - train 0.23151 | val 1.01806
  Epoch 021 - train 0.19975 | val 1.06365
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.44870 | val 0.70616
  Epoch 020 - train 0.20637 | val 0.88450
  Epoch 026 - train 0.12999 | val 1.12176
  Classification -> best τ=0.485 (val F1=0.0989)
  Directional -> Accuracy: 0.5366, MCC: 0.0371, F1: 0.6122

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.47004 | val 0.66087
  Epoch 020 - train 0.23307 | val 0.72378
  Epoch 030 - train 0.09567 | val 0.98275
  Classification -> best τ=0.675 (val F1=0.3284)
  Directional -> Accuracy: 0.6304, MCC: 0.3700, F1: 0.6383

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.41621 | val 0.85353
  Epoch 020 - train 0.22098 | val 1.23759
  Epoch 021 - train 0.21332 | val 1.29292
  Classification -> best τ=0.450 (val F1=0.3853)
  Directional -> Accuracy: 0.5370, MCC: -0.0286, F1: 0.6835

[85/88] Processing VZ...

Processing VZ (Technology)...

[I 2026-02-22 10:19:16,323] Trial 92 finished with value: 0.2280095053769042 and parameters: {'feature_set': 'sector_all_nlp', 'model_type': 'BiGRU', 'sequence_length': 30, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 64, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.0, 'batch_size': 64, 'learning_rate': 0.0012841949897662713, 'weight_decay': 3.5227967203929694e-06, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 20, 'max_epochs': 30, 'huber_delta': 1.0733262000390922, 'early_stopping_min_delta': 0.00897326116975163}. Best is trial 22 with value: 0.2833350641483003.

  Epoch 026 - train 0.11563 | val 1.41113
  Classification -> best τ=0.415 (val F1=0.3384)
  Directional -> Accuracy: 0.5593, MCC: 0.2437, F1: 0.6750

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2280095053769042
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d', 'sentiment']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.47760 | val 1.00957
  Epoch 020 - train 0.27106 | val 1.65071
  Epoch 022 - train 0.23217 | val 1.80173
  Classification -> best τ=0.640 (val F1=0.2036)
  Directional -> Accuracy: 0.5658, MCC: 0.1283, F1: 0.0571

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.32315 | val 0.97362
  Epoch 020 - train 0.15280 | val 2.10972
  Epoch 021 - train 0.13116 | val 2.14232
  Classification -> best τ=0.500 (val F1=0.1764)
  Directional -> Accuracy: 0.6000, MCC: 0.1924, F1: 0.6400

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.33464 | val 2.60592
  Epoch 020 - train 0.16999 | val 3.22094
  Epoch 021 - train 0.15641 | val 4.01258
  Classification -> best τ=0.615 (val F1=0.2311)
  Directional -> Accuracy: 0.4783, MCC: -0.0093, F1: 0.0769

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.47653 | val 1.09962
  Epoch 020 - train 0.22525 | val 1.46681
  Epoch 021 - train 0.23495 | val 1.96834
  Classification -> best τ=0.380 (val F1=0.1462)
  Directional -> Accuracy: 0.5135, MCC: -0.1537, F1: 0.6786

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.35281 | val 0.79381
  Epoch 020 - train 0.13847 | val 1.64586
  Epoch 021 - train 0.11222 | val 1.61336
  Classification -> best τ=0.495 (val F1=0.3440)
  Directional -> Accuracy: 0.6200, MCC: 0.2498, F1: 0.5957

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.34539 | val 1.38820
  Epoch 020 - train 0.19738 | val 1.91414
  Epoch 021 - train 0.15992 | val 2.26991
  Classification -> best τ=0.495 (val F1=0.2937)
  Directional -> Accuracy: 0.5652, MCC: 0.1250, F1: 0.4118

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.44097 | val 1.61832
  Epoch 020 - train 0.14662 | val 1.57627
  Epoch 021 - train 0.13354 | val 2.01997
  Classification -> best τ=0.450 (val F1=0.1907)
  Directional -> Accuracy: 0.4559, MCC: 0.0824, F1: 0.5647

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.34804 | val 0.92964
  Epoch 020 - train 0.08803 | val 4.26075
  Epoch 027 - train 0.07101 | val 2.26813
  Classification -> best τ=0.485 (val F1=0.3590)
  Directional -> Accuracy: 0.5000, MCC: 0.0782, F1: 0.5714

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.41949 | val 1.68193
  Epoch 020 - train 0.20988 | val 2.34342
  Epoch 023 - train 0.17921 | val 2.14403
  Classification -> best τ=0.550 (val F1=0.3431)
  Directional -> Accuracy: 0.4792, MCC: -0.0527, F1: 0.4186

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.37130 | val 1.46769
  Epoch 020 - train 0.16578 | val 1.61630
  Epoch 021 - train 0.12715 | val 1.24502
  Classification -> best τ=0.350 (val F1=0.2465)
  Directional -> Accuracy: 0.4203, MCC: 0.0000, F1: 0.5918

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.38701 | val 1.46532
  Epoch 020 - train 0.11448 | val 1.76676
  Epoch 021 - train 0.10822 | val 1.94879
  Classification -> best τ=0.600 (val F1=0.3075)
  Directional -> Accuracy: 0.5918, MCC: 0.1804, F1: 0.2308

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.40543 | val 2.05374
  Epoch 020 - train 0.16263 | val 3.02887
  Epoch 021 - train 0.17387 | val 3.64491
  Classification -> best τ=0.470 (val F1=0.0887)
  Directional -> Accuracy: 0.5965, MCC: 0.1923, F1: 0.6230

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.35185 | val 1.75509
  Epoch 020 - train 0.10561 | val 3.26308
  Epoch 021 - train 0.06742 | val 3.50506
  Classification -> best τ=0.510 (val F1=0.1225)
  Directional -> Accuracy: 0.5476, MCC: 0.0000, F1: 0.0000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.30065 | val 0.97011
  Epoch 020 - train 0.11462 | val 1.35893
  Epoch 021 - train 0.09813 | val 1.35374
  Classification -> best τ=0.470 (val F1=0.4543)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.38824 | val 0.69058
  Epoch 020 - train 0.17882 | val 1.16265
  Epoch 023 - train 0.11569 | val 1.65576
  Classification -> best τ=0.530 (val F1=0.2571)
  Directional -> Accuracy: 0.5490, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.39997 | val 1.41699
  Epoch 020 - train 0.23560 | val 2.18970
  Epoch 021 - train 0.20653 | val 1.88219
  Classification -> best τ=0.465 (val F1=0.2155)
  Directional -> Accuracy: 0.5507, MCC: 0.0713, F1: 0.6804

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.44628 | val 1.15724
  Epoch 020 - train 0.19027 | val 3.29084
  Epoch 021 - train 0.16358 | val 3.49254
  Classification -> best τ=0.530 (val F1=0.1499)
  Directional -> Accuracy: 0.3966, MCC: -0.0911, F1: 0.2857

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.42292 | val 2.23571
  Epoch 020 - train 0.15012 | val 4.13162
  Epoch 021 - train 0.15208 | val 4.95063
  Classification -> best τ=0.565 (val F1=0.1087)
  Directional -> Accuracy: 0.4000, MCC: -0.0705, F1: 0.1509

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.47389 | val 0.90437
  Epoch 020 - train 0.21513 | val 1.76100
  Epoch 021 - train 0.19870 | val 2.12583
  Classification -> best τ=0.370 (val F1=0.2166)
  Directional -> Accuracy: 0.5625, MCC: 0.0502, F1: 0.6744

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.41325 | val 0.77655
  Epoch 020 - train 0.21875 | val 1.36323
  Epoch 022 - train 0.19803 | val 1.79640
  Classification -> best τ=0.470 (val F1=0.2937)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.28309 | val 1.90055
  Epoch 020 - train 0.07263 | val 3.81614
  Epoch 021 - train 0.08372 | val 4.06043
  Classification -> best τ=0.510 (val F1=0.1737)
  Directional -> Accuracy: 0.4043, MCC: 0.0267, F1: 0.1250

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.39124 | val 1.81477
  Epoch 020 - train 0.15244 | val 2.63055
  Epoch 021 - train 0.11914 | val 3.02561
  Classification -> best τ=0.545 (val F1=0.1960)
  Directional -> Accuracy: 0.4923, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.46107 | val 1.02847
  Epoch 020 - train 0.14873 | val 2.13008
  Epoch 023 - train 0.13528 | val 2.00514
  Classification -> best τ=0.500 (val F1=0.3032)
  Directional -> Accuracy: 0.5263, MCC: 0.0255, F1: 0.5970

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.43283 | val 0.91814
  Epoch 020 - train 0.18367 | val 1.80123
  Epoch 021 - train 0.17428 | val 2.17871
  Classification -> best τ=0.480 (val F1=0.1985)
  Directional -> Accuracy: 0.5231, MCC: 0.0455, F1: 0.5079

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.34002 | val 1.52295
  Epoch 020 - train 0.11618 | val 2.35738
  Epoch 022 - train 0.09757 | val 1.96059
  Classification -> best τ=0.505 (val F1=0.4688)
  Directional -> Accuracy: 0.5455, MCC: 0.1491, F1: 0.4444

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.37145 | val 0.83605
  Epoch 020 - train 0.15096 | val 1.52869
  Epoch 021 - train 0.15310 | val 1.53491
  Classification -> best τ=0.550 (val F1=0.0198)
  Directional -> Accuracy: 0.5778, MCC: 0.0000, F1: 0.0000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.43587 | val 0.77412
  Epoch 020 - train 0.19484 | val 1.12333
  Epoch 021 - train 0.16162 | val 1.17775
  Classification -> best τ=0.480 (val F1=0.0550)
  Directional -> Accuracy: 0.5476, MCC: 0.1260, F1: 0.5366

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.46691 | val 0.92975
  Epoch 020 - train 0.22081 | val 1.89420
  Epoch 022 - train 0.19921 | val 1.91484
  Classification -> best τ=0.510 (val F1=0.2478)
  Directional -> Accuracy: 0.4464, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.31774 | val 3.69663
  Epoch 020 - train 0.15540 | val 3.70004
  Epoch 021 - train 0.12100 | val 2.80239
  Classification -> best τ=0.475 (val F1=0.2509)
  Directional -> Accuracy: 0.5750, MCC: 0.1124, F1: 0.6909

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.40020 | val 1.12447
  Epoch 020 - train 0.16056 | val 2.28247
  Epoch 021 - train 0.16820 | val 1.99259
  Classification -> best τ=0.470 (val F1=0.3532)
  Directional -> Accuracy: 0.4762, MCC: -0.0155, F1: 0.6207

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.38489 | val 1.33602
  Epoch 020 - train 0.13744 | val 1.89011
  Epoch 021 - train 0.11014 | val 1.81125
  Classification -> best τ=0.560 (val F1=0.1286)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.43095 | val 1.41251
  Epoch 020 - train 0.11636 | val 3.41508
  Epoch 021 - train 0.12502 | val 3.83698
  Classification -> best τ=0.520 (val F1=0.2611)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.42412 | val 1.34527
  Epoch 020 - train 0.20525 | val 2.49521
  Epoch 021 - train 0.17954 | val 2.83761
  Classification -> best τ=0.530 (val F1=0.2267)
  Directional -> Accuracy: 0.4444, MCC: 0.0000, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.38189 | val 1.66071
  Epoch 020 - train 0.13980 | val 1.97116
  Epoch 021 - train 0.15612 | val 1.96963
  Classification -> best τ=0.425 (val F1=0.2324)
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.45521 | val 0.86394
  Epoch 020 - train 0.27066 | val 1.49172
  Epoch 021 - train 0.19175 | val 1.45834
  Classification -> best τ=0.390 (val F1=0.3525)
  Directional -> Accuracy: 0.6061, MCC: 0.2406, F1: 0.6061

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.31174 | val 1.98243
  Epoch 020 - train 0.08698 | val 2.61976
  Epoch 021 - train 0.12411 | val 2.41219
  Classification -> best τ=0.445 (val F1=0.2464)
  Directional -> Accuracy: 0.5952, MCC: 0.2383, F1: 0.7119

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.39303 | val 1.42417
  Epoch 020 - train 0.14993 | val 3.02407
  Epoch 021 - train 0.13160 | val 2.85803
  Classification -> best τ=0.405 (val F1=0.2871)
  Directional -> Accuracy: 0.5000, MCC: 0.0340, F1: 0.5758

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.33426 | val 1.76754
  Epoch 020 - train 0.09828 | val 2.90233
  Epoch 021 - train 0.10519 | val 2.76764
  Classification -> best τ=0.525 (val F1=0.4627)
  Directional -> Accuracy: 0.4348, MCC: -0.0094, F1: 0.3158

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.42306 | val 0.67456
  Epoch 020 - train 0.18445 | val 1.43321
  Epoch 028 - train 0.06201 | val 2.96345
  Classification -> best τ=0.235 (val F1=0.3751)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.33713 | val 1.65954
  Epoch 020 - train 0.14748 | val 2.56827
  Epoch 021 - train 0.13625 | val 2.71518
  Classification -> best τ=0.440 (val F1=0.2709)
  Directional -> Accuracy: 0.4595, MCC: -0.0836, F1: 0.4286

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.35975 | val 1.00838
  Epoch 020 - train 0.12250 | val 1.31502
  Epoch 021 - train 0.10960 | val 1.35169
  Classification -> best τ=0.475 (val F1=0.2169)
  Directional -> Accuracy: 0.5111, MCC: 0.0000, F1: 0.6765

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.33342 | val 1.18894
  Epoch 020 - train 0.09649 | val 2.01207
  Epoch 021 - train 0.09221 | val 1.95884
  Classification -> best τ=0.520 (val F1=0.2381)
  Directional -> Accuracy: 0.7143, MCC: 0.4082, F1: 0.7692

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.35383 | val 1.04533
  Epoch 020 - train 0.12573 | val 2.68043
  Epoch 021 - train 0.10830 | val 2.42608
  Classification -> best τ=0.540 (val F1=0.1974)
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.5455

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.43537 | val 0.79619
  Epoch 020 - train 0.25096 | val 1.29151
  Epoch 021 - train 0.22754 | val 1.33780
  Classification -> best τ=0.555 (val F1=0.1647)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.35948 | val 2.44420
  Epoch 020 - train 0.12921 | val 2.11183
  Epoch 021 - train 0.12465 | val 1.89308
  Classification -> best τ=0.560 (val F1=0.3988)
  Directional -> Accuracy: 0.5357, MCC: 0.0728, F1: 0.5357

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.48237 | val 1.18132
  Epoch 020 - train 0.18560 | val 2.07577
  Epoch 021 - train 0.19195 | val 2.03311
  Classification -> best τ=0.495 (val F1=0.1289)

[I 2026-02-22 10:21:21,810] Trial 93 finished with value: 0.24305452022824672 and parameters: {'feature_set': 'sector_sentiment', 'model_type': 'BiGRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 64, 'num_layers': 2, 'inter_rnn_drop': 0.1, 'dropout': 0.0, 'batch_size': 32, 'learning_rate': 0.0025919664370593555, 'weight_decay': 6.131149819781173e-06, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 20, 'max_epochs': 30, 'huber_delta': 1.3205361269320963, 'early_stopping_min_delta': 0.009428171220966584}. Best is trial 22 with value: 0.2833350641483003.

  Epoch 024 - train 0.12405 | val 2.66120
  Classification -> best τ=0.435 (val F1=0.3363)
  Directional -> Accuracy: 0.5167, MCC: 0.0850, F1: 0.6420

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.24305452022824672
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: classification
Sequence length: 36
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d', 'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down', 'finbert_neutral']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.59987 | val 1.17122
  Epoch 020 - train 0.46005 | val 1.56513
  Classification -> best τ=0.580 (val F1=0.2018)
  Directional -> Accuracy: 0.5541, MCC: 0.0000, F1: 0.0000

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 112). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.50034 | val 0.93245
  Epoch 020 - train 0.34912 | val 1.25152
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.6047, MCC: 0.0000, F1: 0.7536

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for AEP (109 < 112). Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 112). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.50781 | val 0.97747
  Epoch 020 - train 0.26425 | val 2.28172
  Classification -> best τ=0.520 (val F1=0.1935)
  Directional -> Accuracy: 0.5000, MCC: 0.0780, F1: 0.1538

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.57672 | val 1.38990
  Epoch 020 - train 0.43257 | val 2.06355
  Classification -> best τ=0.415 (val F1=0.1988)
  Directional -> Accuracy: 0.4583, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.48086 | val 1.00900
  Epoch 020 - train 0.32236 | val 1.40206
  Classification -> best τ=0.515 (val F1=0.3724)
  Directional -> Accuracy: 0.6458, MCC: 0.3402, F1: 0.5641

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.53056 | val 0.98909
  Epoch 020 - train 0.36092 | val 1.72152
  Classification -> best τ=0.420 (val F1=0.2640)
  Directional -> Accuracy: 0.4773, MCC: -0.0459, F1: 0.5106

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.59064 | val 0.84337
  Epoch 020 - train 0.44691 | val 1.26786
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.5806

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 112). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 112). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.51233 | val 1.18862
  Epoch 020 - train 0.36712 | val 1.03063
  Classification -> best τ=0.525 (val F1=0.3637)
  Directional -> Accuracy: 0.4872, MCC: -0.0027, F1: 0.5000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.55522 | val 1.55658
  Epoch 020 - train 0.39946 | val 1.76858
  Classification -> best τ=0.575 (val F1=0.2390)
  Directional -> Accuracy: 0.5652, MCC: 0.0510, F1: 0.2308

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 112). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 112). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 112). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.56502 | val 0.75345
  Epoch 020 - train 0.37461 | val 1.16882
  Classification -> best τ=0.505 (val F1=0.3020)
  Directional -> Accuracy: 0.4627, MCC: -0.0442, F1: 0.4706

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.51685 | val 1.03953
  Epoch 020 - train 0.35782 | val 1.13217
  Classification -> best τ=0.520 (val F1=0.2956)
  Directional -> Accuracy: 0.6383, MCC: 0.2762, F1: 0.4138

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.55093 | val 1.01073
  Epoch 020 - train 0.35064 | val 2.16925
  Classification -> best τ=0.485 (val F1=0.1451)
  Directional -> Accuracy: 0.5273, MCC: 0.0000, F1: 0.6905

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 112). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.50597 | val 1.97695
  Epoch 020 - train 0.39201 | val 3.12838
  Classification -> best τ=0.475 (val F1=0.2036)
  Directional -> Accuracy: 0.4792, MCC: 0.0000, F1: 0.6479

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 112). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.55551 | val 0.75514
  Epoch 020 - train 0.44829 | val 1.08447
  Classification -> best τ=0.545 (val F1=0.3613)
  Directional -> Accuracy: 0.4828, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.56888 | val 0.77836
  Epoch 020 - train 0.43901 | val 0.71059
  Classification -> best τ=0.480 (val F1=0.1594)
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.56612 | val 1.04201
  Epoch 020 - train 0.42006 | val 1.53391
  Classification -> best τ=0.500 (val F1=0.2068)
  Directional -> Accuracy: 0.5672, MCC: 0.1210, F1: 0.6234

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 112). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.56465 | val 1.28224
  Epoch 020 - train 0.41891 | val 2.03381
  Classification -> best τ=0.670 (val F1=0.2699)
  Directional -> Accuracy: 0.3571, MCC: -0.1941, F1: 0.1429

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.58197 | val 0.79911
  Epoch 020 - train 0.35704 | val 1.36673
  Classification -> best τ=0.535 (val F1=0.1512)
  Directional -> Accuracy: 0.5479, MCC: -0.1163, F1: 0.7027

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.55560 | val 0.71242
  Epoch 020 - train 0.35962 | val 0.84574
  Classification -> best τ=0.530 (val F1=0.3116)
  Directional -> Accuracy: 0.5000, MCC: 0.1646, F1: 0.3111

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 112). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.55452 | val 0.84023
  Epoch 020 - train 0.37306 | val 1.21492
  Classification -> best τ=0.475 (val F1=0.2750)
  Directional -> Accuracy: 0.4444, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.54647 | val 0.82594
  Epoch 020 - train 0.30689 | val 1.33069
  Classification -> best τ=0.480 (val F1=0.1754)
  Directional -> Accuracy: 0.5333, MCC: -0.1001, F1: 0.6769

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 112). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 112). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 112). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.58398 | val 0.84711
  Epoch 020 - train 0.36661 | val 0.81844
  Classification -> best τ=0.475 (val F1=0.2244)
  Directional -> Accuracy: 0.5873, MCC: 0.1952, F1: 0.4348

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.56521 | val 1.46866
  Epoch 020 - train 0.37600 | val 3.55220
  Classification -> best τ=0.550 (val F1=0.2738)
  Directional -> Accuracy: 0.5636, MCC: 0.0924, F1: 0.6364

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.58761 | val 1.63608
  Epoch 020 - train 0.39907 | val 2.08465
  Classification -> best τ=0.350 (val F1=0.1173)
  Directional -> Accuracy: 0.4762, MCC: 0.0000, F1: 0.6452

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.51262 | val 0.68967
  Epoch 020 - train 0.32828 | val 1.30787
  Classification -> best τ=0.430 (val F1=0.4397)
  Directional -> Accuracy: 0.5660, MCC: 0.2449, F1: 0.4103

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.52503 | val 1.07343
  Epoch 020 - train 0.38574 | val 1.58856
  Classification -> best τ=0.455 (val F1=0.3327)
  Directional -> Accuracy: 0.3810, MCC: -0.1964, F1: 0.5185

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.56658 | val 0.69678
  Epoch 020 - train 0.47142 | val 0.88021
  Classification -> best τ=0.590 (val F1=0.2010)
  Directional -> Accuracy: 0.4167, MCC: 0.0000, F1: 0.0000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.56062 | val 0.81174
  Epoch 020 - train 0.33117 | val 1.69609
  Classification -> best τ=0.465 (val F1=0.1421)
  Directional -> Accuracy: 0.4630, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
Insufficient data for proper time series validation for MDT. Skipping...

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.57360 | val 1.22150
  Epoch 020 - train 0.48575 | val 1.61656
  Classification -> best τ=0.545 (val F1=0.1391)
  Directional -> Accuracy: 0.4500, MCC: -0.1250, F1: 0.2143

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.56591 | val 1.06098
  Epoch 020 - train 0.44206 | val 1.34364
  Classification -> best τ=0.575 (val F1=0.1300)
  Directional -> Accuracy: 0.4750, MCC: 0.0668, F1: 0.1600

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.49330 | val 0.99330
  Epoch 020 - train 0.23542 | val 2.13545
  Classification -> best τ=0.445 (val F1=0.1986)
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.54748 | val 0.70102
  Epoch 020 - train 0.37233 | val 1.02548
  Classification -> best τ=0.290 (val F1=0.3361)
  Directional -> Accuracy: 0.5571, MCC: 0.1118, F1: 0.5867

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 112). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.54252 | val 0.76594
  Epoch 020 - train 0.36409 | val 0.86398
  Classification -> best τ=0.455 (val F1=0.2576)
  Directional -> Accuracy: 0.4490, MCC: -0.1091, F1: 0.4000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for PCG (101 < 112). Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.55393 | val 1.14250
  Epoch 020 - train 0.36891 | val 1.85263
  Classification -> best τ=0.375 (val F1=0.2718)
  Directional -> Accuracy: 0.5625, MCC: 0.0000, F1: 0.7200

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.46136 | val 0.79558
  Epoch 020 - train 0.30237 | val 0.94975
  Classification -> best τ=0.465 (val F1=0.4419)
  Directional -> Accuracy: 0.6531, MCC: 0.3064, F1: 0.6222

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.50830 | val 1.17897
  Epoch 020 - train 0.36790 | val 2.14959
  Classification -> best τ=0.495 (val F1=0.1854)
  Directional -> Accuracy: 0.5000, MCC: 0.0736, F1: 0.6197

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.46295 | val 1.30553
  Epoch 020 - train 0.28326 | val 2.01749
  Classification -> best τ=0.485 (val F1=0.3451)
  Directional -> Accuracy: 0.4773, MCC: 0.0962, F1: 0.3784

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 112). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for PPL (108 < 112). Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 112). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 112). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 112). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.59716 | val 0.61421
  Epoch 020 - train 0.48671 | val 0.77606
  Classification -> best τ=0.545 (val F1=0.4633)
  Directional -> Accuracy: 0.4667, MCC: -0.0629, F1: 0.3684

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 112). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 112). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 112). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.51747 | val 1.39654
  Epoch 020 - train 0.35970 | val 1.66018
  Classification -> best τ=0.410 (val F1=0.2028)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 112). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 112). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 112). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 112). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.56049 | val 0.67145
  Epoch 020 - train 0.43863 | val 0.74570
  Classification -> best τ=0.620 (val F1=0.3569)
  Directional -> Accuracy: 0.6744, MCC: 0.3519, F1: 0.7083

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.53779 | val 1.04500
  Epoch 020 - train 0.46871 | val 1.35163
  Classification -> best τ=0.540 (val F1=0.2414)
  Directional -> Accuracy: 0.5128, MCC: 0.1655, F1: 0.3871

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.50505 | val 0.94603
  Epoch 020 - train 0.36905 | val 1.28184
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.3778, MCC: 0.0000, F1: 0.5484

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.55513 | val 0.79255
  Epoch 020 - train 0.48436 | val 1.22551
  Classification -> best τ=0.525 (val F1=0.3024)
  Directional -> Accuracy: 0.5849, MCC: 0.1535, F1: 0.7105

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.58608 | val 1.11959
  Epoch 020 - train 0.37306 | val 1.64880
  Classification -> best τ=0.560 (val F1=0.2444)
  Directional -> Accuracy: 0.4815, MCC: -0.0388, F1: 0.3913

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.56257 | val 0.75082
  Epoch 020 - train 0.47868 | val 0.83043
  Classification -> best τ=0.630 (val F1=0.2758)
  Directional -> Accuracy: 0.5294, MCC: 0.0557, F1: 0.4545

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.60972 | val 1.07057
  Epoch 020 - train 0.38207 | val 1.90975
  Classification -> best τ=0.455 (val F1=0.1999)
  Directional -> Accuracy: 0.5094, MCC: 0.0000, F1: 0.6750

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.57263 | val 0.76373

[I 2026-02-22 10:22:44,945] Trial 94 finished with value: 0.24065106325233027 and parameters: {'feature_set': 'sector_finbert', 'model_type': 'GRU', 'sequence_length': 36, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 64, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.1, 'batch_size': 64, 'learning_rate': 0.004373343624774362, 'weight_decay': 2.8008063065594273e-06, 'lr_patience': 7, 'lr_factor': 0.8, 'early_stopping_patience': 20, 'max_epochs': 20, 'huber_delta': 1.375532053490269, 'early_stopping_min_delta': 0.008313061424042104}. Best is trial 22 with value: 0.2833350641483003.

  Epoch 020 - train 0.42324 | val 0.97295
  Classification -> best τ=0.560 (val F1=0.2969)
  Directional -> Accuracy: 0.5000, MCC: 0.0347, F1: 0.5797

================================================================================
Pipeline completed: 47/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (47, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.24065106325233027
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 30
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d', 'sentiment']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.62758 | val 0.78345
  Epoch 020 - train 0.58408 | val 0.80350
  Epoch 021 - train 0.57778 | val 0.80204
  Classification -> best τ=0.560 (val F1=0.2520)
  Directional -> Accuracy: 0.4933, MCC: -0.1411, F1: 0.0952

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 106). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.60568 | val 0.74334
  Epoch 020 - train 0.53713 | val 0.85766
  Epoch 021 - train 0.52712 | val 0.86058
  Classification -> best τ=0.455 (val F1=0.2015)
  Directional -> Accuracy: 0.6136, MCC: 0.1833, F1: 0.7536

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 106). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.63164 | val 0.80097
  Epoch 020 - train 0.58493 | val 0.92201
  Epoch 021 - train 0.56731 | val 0.91512
  Classification -> best τ=0.510 (val F1=0.3162)
  Directional -> Accuracy: 0.6444, MCC: 0.3118, F1: 0.7333

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.62092 | val 1.09020
  Epoch 020 - train 0.58249 | val 1.51511
  Epoch 021 - train 0.57076 | val 1.51085
  Classification -> best τ=0.450 (val F1=0.1167)
  Directional -> Accuracy: 0.5342, MCC: 0.0573, F1: 0.5854

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.56849 | val 0.73122
  Epoch 020 - train 0.52635 | val 0.78098
  Epoch 030 - train 0.49017 | val 0.88549
  Epoch 034 - train 0.46866 | val 0.90253
  Classification -> best τ=0.650 (val F1=0.3842)
  Directional -> Accuracy: 0.5510, MCC: 0.1264, F1: 0.4211

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.59541 | val 0.71483
  Epoch 020 - train 0.53279 | val 0.73799
  Epoch 021 - train 0.51722 | val 0.73681
  Classification -> best τ=0.440 (val F1=0.2727)
  Directional -> Accuracy: 0.4222, MCC: -0.1572, F1: 0.5000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.64904 | val 0.73529
  Epoch 020 - train 0.60613 | val 0.95826
  Epoch 021 - train 0.59731 | val 0.96786
  Classification -> best τ=0.460 (val F1=0.2938)
  Directional -> Accuracy: 0.5075, MCC: 0.0182, F1: 0.4590

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 106). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 106). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.61838 | val 0.76829
  Epoch 020 - train 0.55204 | val 0.74609
  Epoch 021 - train 0.56695 | val 0.75909
  Classification -> best τ=0.515 (val F1=0.3612)
  Directional -> Accuracy: 0.5854, MCC: 0.1289, F1: 0.1905

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.61187 | val 0.67156
  Epoch 020 - train 0.55095 | val 0.86507
  Epoch 030 - train 0.50433 | val 1.06958
  Epoch 031 - train 0.49149 | val 1.08933
  Classification -> best τ=0.655 (val F1=0.4216)
  Directional -> Accuracy: 0.5532, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 106). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 106). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 106). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.60483 | val 0.95731
  Epoch 020 - train 0.55241 | val 1.18959
  Epoch 021 - train 0.54637 | val 1.21817
  Classification -> best τ=0.600 (val F1=0.1152)
  Directional -> Accuracy: 0.5735, MCC: 0.0372, F1: 0.1212

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.62823 | val 0.89490
  Epoch 020 - train 0.59061 | val 0.93369
  Epoch 021 - train 0.59732 | val 0.95597
  Classification -> best τ=0.530 (val F1=0.2907)
  Directional -> Accuracy: 0.4792, MCC: -0.0039, F1: 0.5614

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.62991 | val 0.93701
  Epoch 020 - train 0.58531 | val 1.11716
  Epoch 021 - train 0.57416 | val 1.13926
  Classification -> best τ=0.450 (val F1=0.0965)
  Directional -> Accuracy: 0.5179, MCC: 0.0000, F1: 0.6824

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 106). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.57336 | val 1.15730
  Epoch 020 - train 0.52598 | val 1.40777
  Epoch 021 - train 0.52933 | val 1.43246
  Classification -> best τ=0.475 (val F1=0.0424)
  Directional -> Accuracy: 0.4898, MCC: -0.0042, F1: 0.6479

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 106). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.62444 | val 0.63853
  Epoch 020 - train 0.58134 | val 0.70271
  Epoch 023 - train 0.57341 | val 0.70927
  Classification -> best τ=0.505 (val F1=0.3738)
  Directional -> Accuracy: 0.4915, MCC: -0.0032, F1: 0.0625

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.61836 | val 0.78038
  Epoch 020 - train 0.55810 | val 0.87324
  Epoch 021 - train 0.55987 | val 0.88256
  Classification -> best τ=0.525 (val F1=0.2043)
  Directional -> Accuracy: 0.6000, MCC: 0.1842, F1: 0.2308

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.61164 | val 0.71112
  Epoch 020 - train 0.56197 | val 0.84675
  Epoch 021 - train 0.54624 | val 0.87139
  Classification -> best τ=0.475 (val F1=0.2526)
  Directional -> Accuracy: 0.5588, MCC: 0.1399, F1: 0.7000

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 106). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.62886 | val 0.81979
  Epoch 020 - train 0.59182 | val 1.02599
  Epoch 021 - train 0.58920 | val 1.03235
  Classification -> best τ=0.460 (val F1=0.2335)
  Directional -> Accuracy: 0.5789, MCC: -0.0767, F1: 0.7273

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.61352 | val 0.95233
  Epoch 020 - train 0.55590 | val 1.22104
  Epoch 021 - train 0.55338 | val 1.27021
  Classification -> best τ=0.400 (val F1=0.2903)
  Directional -> Accuracy: 0.5135, MCC: 0.2139, F1: 0.3571

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.60727 | val 0.80595
  Epoch 020 - train 0.55787 | val 0.86283
  Epoch 023 - train 0.54894 | val 0.86218
  Classification -> best τ=0.415 (val F1=0.2822)
  Directional -> Accuracy: 0.5079, MCC: 0.1877, F1: 0.3404

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 106). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.60682 | val 0.67157
  Epoch 020 - train 0.54922 | val 0.71788
  Epoch 029 - train 0.51780 | val 0.78404
  Classification -> best τ=0.580 (val F1=0.2785)
  Directional -> Accuracy: 0.4521, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.61616 | val 0.73009
  Epoch 020 - train 0.53677 | val 0.77059
  Epoch 021 - train 0.55191 | val 0.77148
  Classification -> best τ=0.540 (val F1=0.4045)
  Directional -> Accuracy: 0.5652, MCC: 0.0691, F1: 0.6552

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 106). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 106). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 106). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.62000 | val 0.75107
  Epoch 020 - train 0.57125 | val 0.86899
  Epoch 021 - train 0.56285 | val 0.87450
  Classification -> best τ=0.510 (val F1=0.0323)
  Directional -> Accuracy: 0.4375, MCC: -0.1512, F1: 0.5610

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.62270 | val 0.89360
  Epoch 020 - train 0.58321 | val 1.06006
  Epoch 021 - train 0.56384 | val 1.06699
  Classification -> best τ=0.650 (val F1=0.3464)
  Directional -> Accuracy: 0.5000, MCC: 0.1833, F1: 0.2632

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.62556 | val 0.80439
  Epoch 020 - train 0.56955 | val 0.87684
  Epoch 021 - train 0.56943 | val 0.88836
  Classification -> best τ=0.450 (val F1=0.1547)
  Directional -> Accuracy: 0.4688, MCC: 0.0000, F1: 0.6383

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.60532 | val 0.70228
  Epoch 020 - train 0.55365 | val 0.80628
  Epoch 024 - train 0.53079 | val 0.83652
  Classification -> best τ=0.505 (val F1=0.4641)
  Directional -> Accuracy: 0.5000, MCC: 0.0736, F1: 0.2703

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.60102 | val 0.75475
  Epoch 020 - train 0.54607 | val 0.79143
  Epoch 021 - train 0.55019 | val 0.79251
  Classification -> best τ=0.455 (val F1=0.3901)
  Directional -> Accuracy: 0.4419, MCC: -0.0713, F1: 0.4783

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.61278 | val 0.71013
  Epoch 020 - train 0.57678 | val 0.74925
  Epoch 021 - train 0.57527 | val 0.75167
  Classification -> best τ=0.465 (val F1=0.2816)
  Directional -> Accuracy: 0.5306, MCC: -0.0110, F1: 0.6349

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.61131 | val 0.68159
  Epoch 020 - train 0.56632 | val 0.75007
  Epoch 023 - train 0.56122 | val 0.77519
  Classification -> best τ=0.475 (val F1=0.3303)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.61850 | val 0.73212
  Epoch 020 - train 0.55702 | val 0.76667
  Epoch 021 - train 0.53548 | val 0.76540
  Classification -> best τ=0.505 (val F1=0.1724)
  Directional -> Accuracy: 0.4474, MCC: -0.1558, F1: 0.5532

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.63704 | val 0.77003
  Epoch 020 - train 0.59150 | val 0.86659
  Epoch 021 - train 0.59193 | val 0.87710
  Classification -> best τ=0.495 (val F1=0.1782)
  Directional -> Accuracy: 0.5610, MCC: 0.1214, F1: 0.5500

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.63202 | val 0.84664
  Epoch 020 - train 0.58561 | val 0.91139
  Epoch 021 - train 0.57436 | val 0.92414
  Classification -> best τ=0.455 (val F1=0.0720)
  Directional -> Accuracy: 0.5610, MCC: 0.0000, F1: 0.7188

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.59023 | val 0.71113
  Epoch 020 - train 0.54785 | val 0.79868
  Epoch 022 - train 0.53899 | val 0.80273
  Classification -> best τ=0.485 (val F1=0.2811)
  Directional -> Accuracy: 0.5833, MCC: 0.2190, F1: 0.7059

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.60690 | val 0.79731
  Epoch 020 - train 0.57019 | val 1.05412
  Epoch 022 - train 0.54543 | val 1.09969
  Classification -> best τ=0.320 (val F1=0.2831)
  Directional -> Accuracy: 0.5211, MCC: 0.1214, F1: 0.4138

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 106). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.60918 | val 0.70377
  Epoch 020 - train 0.54868 | val 0.70626
  Epoch 021 - train 0.54980 | val 0.71516
  Classification -> best τ=0.475 (val F1=0.3068)
  Directional -> Accuracy: 0.4286, MCC: -0.1409, F1: 0.4286

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for PCG (101 < 106). Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.60591 | val 0.75356
  Epoch 020 - train 0.56132 | val 0.82489
  Epoch 022 - train 0.56539 | val 0.84426
  Classification -> best τ=0.370 (val F1=0.3488)
  Directional -> Accuracy: 0.6154, MCC: 0.2192, F1: 0.6575

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.58980 | val 0.71814
  Epoch 020 - train 0.53974 | val 0.78462
  Epoch 023 - train 0.53018 | val 0.80783
  Classification -> best τ=0.445 (val F1=0.2582)
  Directional -> Accuracy: 0.5500, MCC: 0.0869, F1: 0.6538

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.58833 | val 0.80585
  Epoch 020 - train 0.54891 | val 0.87506
  Epoch 021 - train 0.54697 | val 0.88158
  Classification -> best τ=0.485 (val F1=0.1868)
  Directional -> Accuracy: 0.5273, MCC: 0.0828, F1: 0.5667

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.57988 | val 0.96340
  Epoch 020 - train 0.52176 | val 1.28592
  Epoch 021 - train 0.51419 | val 1.30932
  Classification -> best τ=0.510 (val F1=0.2626)
  Directional -> Accuracy: 0.5333, MCC: 0.0410, F1: 0.6038

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 106). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 106). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 106). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 106). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.60628 | val 0.69284
  Epoch 020 - train 0.57427 | val 0.71454
  Epoch 021 - train 0.57152 | val 0.71750
  Classification -> best τ=0.525 (val F1=0.4256)
  Directional -> Accuracy: 0.3261, MCC: 0.0000, F1: 0.4918

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 106). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 106). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 106). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.59158 | val 0.96510
  Epoch 020 - train 0.51522 | val 1.25778
  Epoch 021 - train 0.51244 | val 1.30709
  Classification -> best τ=0.465 (val F1=0.2279)
  Directional -> Accuracy: 0.5068, MCC: 0.0000, F1: 0.0000

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 106). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 106). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 106). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 106). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.63645 | val 0.67091
  Epoch 020 - train 0.58731 | val 0.67715
  Epoch 026 - train 0.56916 | val 0.71051
  Classification -> best τ=0.470 (val F1=0.3536)
  Directional -> Accuracy: 0.5455, MCC: 0.1085, F1: 0.6429

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.58856 | val 0.74623
  Epoch 020 - train 0.55048 | val 0.76946
  Epoch 021 - train 0.55440 | val 0.76393
  Classification -> best τ=0.530 (val F1=0.3568)
  Directional -> Accuracy: 0.4146, MCC: 0.0000, F1: 0.0000

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.59544 | val 0.86893
  Epoch 020 - train 0.56792 | val 0.90875
  Epoch 021 - train 0.54596 | val 0.90826
  Classification -> best τ=0.565 (val F1=0.1548)
  Directional -> Accuracy: 0.5000, MCC: 0.2325, F1: 0.5818

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.63297 | val 0.68766
  Epoch 020 - train 0.60045 | val 0.73620
  Epoch 024 - train 0.57968 | val 0.75290
  Classification -> best τ=0.545 (val F1=0.2374)
  Directional -> Accuracy: 0.4444, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.59545 | val 1.03451
  Epoch 020 - train 0.54629 | val 1.29981
  Epoch 021 - train 0.53947 | val 1.31162
  Classification -> best τ=0.555 (val F1=0.3142)
  Directional -> Accuracy: 0.5273, MCC: 0.0619, F1: 0.5806

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.62483 | val 0.66458
  Epoch 020 - train 0.56530 | val 0.68806
  Epoch 029 - train 0.51306 | val 0.71903

[I 2026-02-22 10:28:06,160] Trial 95 finished with value: 0.26174246705258625 and parameters: {'feature_set': 'sector_sentiment', 'model_type': 'BiGRU', 'sequence_length': 30, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 64, 'num_layers': 2, 'inter_rnn_drop': 0.4, 'dropout': 0.0, 'batch_size': 32, 'learning_rate': 0.00032927401623411334, 'weight_decay': 5.079797836382274e-06, 'lr_patience': 5, 'lr_factor': 0.8, 'early_stopping_patience': 20, 'max_epochs': 50, 'huber_delta': 1.5326253470481455, 'early_stopping_min_delta': 0.0056248895396488075}. Best is trial 22 with value: 0.2833350641483003.

  Epoch 022 - train 0.57292 | val 0.75683
  Classification -> best τ=0.500 (val F1=0.1680)
  Directional -> Accuracy: 0.4576, MCC: -0.0960, F1: 0.3846

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.26174246705258625
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.43618 | val 1.09183
  Epoch 011 - train 0.36134 | val 1.42194
  Classification -> best τ=0.605 (val F1=0.2851)
  Directional -> Accuracy: 0.5584, MCC: 0.0742, F1: 0.1905

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.29969 | val 1.51698
  Epoch 011 - train 0.18510 | val 1.38990
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.7222

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.39660 | val 2.37387
  Epoch 011 - train 0.25406 | val 2.27143
  Classification -> best τ=0.645 (val F1=0.1342)
  Directional -> Accuracy: 0.4681, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.45298 | val 0.93801
  Epoch 011 - train 0.41097 | val 1.68167
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.35362 | val 4.24974
  Epoch 011 - train 0.20746 | val 4.04352
  Classification -> best τ=0.375 (val F1=0.3579)
  Directional -> Accuracy: 0.6667, MCC: 0.3287, F1: 0.7018

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.20385 | val 7.19236
  Epoch 011 - train 0.09199 | val 6.20930
  Classification -> best τ=0.730 (val F1=0.4062)
  Directional -> Accuracy: 0.4894, MCC: -0.1443, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.41395 | val 4.28829
  Epoch 011 - train 0.36351 | val 4.31984
  Classification -> best τ=0.095 (val F1=0.2269)
  Directional -> Accuracy: 0.4348, MCC: -0.0468, F1: 0.5063

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.08559 | val 2.08017
  Epoch 011 - train 0.05859 | val 2.71664
  Classification -> best τ=0.385 (val F1=0.1214)
  Directional -> Accuracy: 0.4773, MCC: -0.1601, F1: 0.2069

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.30357 | val 2.21640
  Epoch 011 - train 0.27846 | val 2.67162
  Classification -> best τ=0.420 (val F1=0.3475)
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.40699 | val 1.04196
  Epoch 011 - train 0.39914 | val 1.35813
  Classification -> best τ=0.435 (val F1=0.1816)
  Directional -> Accuracy: 0.4286, MCC: -0.0248, F1: 0.5918

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.37863 | val 3.82931
  Epoch 011 - train 0.30491 | val 3.54578
  Classification -> best τ=0.895 (val F1=0.1750)
  Directional -> Accuracy: 0.6000, MCC: 0.2274, F1: 0.2857

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.39691 | val 3.44762
  Epoch 011 - train 0.41270 | val 3.56863
  Classification -> best τ=0.260 (val F1=0.2172)
  Directional -> Accuracy: 0.5172, MCC: 0.0529, F1: 0.6500

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.25364 | val 4.17358
  Epoch 012 - train 0.18648 | val 5.23310
  Classification -> best τ=0.165 (val F1=0.2869)
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.32253 | val 1.24459
  Epoch 011 - train 0.24460 | val 1.70706
  Classification -> best τ=0.240 (val F1=0.3963)
  Directional -> Accuracy: 0.5082, MCC: 0.0350, F1: 0.2857

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.43234 | val 1.96342
  Epoch 012 - train 0.28432 | val 2.33240
  Classification -> best τ=0.570 (val F1=0.2693)
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.38730 | val 2.94043
  Epoch 011 - train 0.37724 | val 1.97201
  Classification -> best τ=0.340 (val F1=0.1569)
  Directional -> Accuracy: 0.5000, MCC: -0.1147, F1: 0.6535

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.32860 | val 5.10912
  Epoch 011 - train 0.27248 | val 4.41231
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.34812 | val 1.99286
  Epoch 012 - train 0.37082 | val 1.44045
  Classification -> best τ=0.135 (val F1=0.2137)
  Directional -> Accuracy: 0.6316, MCC: 0.2036, F1: 0.7667

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.45365 | val 1.99601
  Epoch 011 - train 0.35278 | val 2.02907
  Classification -> best τ=0.540 (val F1=0.2899)
  Directional -> Accuracy: 0.4154, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.46383 | val 1.75105
  Epoch 012 - train 0.28179 | val 2.05869
  Classification -> best τ=0.270 (val F1=0.2749)
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.36288 | val 0.93559
  Epoch 011 - train 0.16534 | val 1.39206
  Classification -> best τ=0.570 (val F1=0.2600)
  Directional -> Accuracy: 0.6042, MCC: 0.0457, F1: 0.7324

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.35798 | val 2.30998
  Epoch 011 - train 0.26422 | val 1.93687
  Classification -> best τ=0.325 (val F1=0.2054)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.51041 | val 2.61093
  Epoch 011 - train 0.32356 | val 3.83897
  Classification -> best τ=0.785 (val F1=0.3282)
  Directional -> Accuracy: 0.5517, MCC: 0.1248, F1: 0.5517

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.47467 | val 1.05049
  Epoch 011 - train 0.37101 | val 3.13724
  Classification -> best τ=0.470 (val F1=0.1950)
  Directional -> Accuracy: 0.5455, MCC: 0.1482, F1: 0.6341

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.31128 | val 1.73400
  Epoch 011 - train 0.23463 | val 1.47175
  Classification -> best τ=0.365 (val F1=0.3299)
  Directional -> Accuracy: 0.5893, MCC: 0.2075, F1: 0.5660

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.34078 | val 1.52675
  Epoch 011 - train 0.27792 | val 1.60199
  Classification -> best τ=0.380 (val F1=0.2774)
  Directional -> Accuracy: 0.3913, MCC: -0.2385, F1: 0.3000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.29084 | val 2.29854
  Epoch 011 - train 0.27323 | val 2.20119
  Classification -> best τ=0.655 (val F1=0.1309)
  Directional -> Accuracy: 0.5116, MCC: 0.1323, F1: 0.4000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.41009 | val 1.30510
  Epoch 012 - train 0.30213 | val 1.48012
  Classification -> best τ=0.405 (val F1=0.2024)
  Directional -> Accuracy: 0.4386, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.22786 | val 2.17751
  Epoch 012 - train 0.09184 | val 3.00498
  Classification -> best τ=0.505 (val F1=0.2802)
  Directional -> Accuracy: 0.5610, MCC: 0.1021, F1: 0.6897

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.23148 | val 2.90078
  Epoch 011 - train 0.26744 | val 3.09394
  Classification -> best τ=0.670 (val F1=0.1869)
  Directional -> Accuracy: 0.4884, MCC: -0.0318, F1: 0.3889

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.16322 | val 2.05460
  Epoch 011 - train 0.13199 | val 2.76635
  Classification -> best τ=0.430 (val F1=0.2533)
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.24921 | val 3.48111
  Epoch 011 - train 0.30327 | val 5.13128
  Classification -> best τ=0.725 (val F1=0.2320)
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.0000

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.39447 | val 3.06952
  Epoch 011 - train 0.35955 | val 3.33631
  Classification -> best τ=0.480 (val F1=0.2340)
  Directional -> Accuracy: 0.4384, MCC: 0.0000, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.17255 | val 3.75969
  Epoch 011 - train 0.10304 | val 3.74094
  Classification -> best τ=0.515 (val F1=0.4714)
  Directional -> Accuracy: 0.5263, MCC: 0.0619, F1: 0.6250

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.29011 | val 3.08068
  Epoch 011 - train 0.23659 | val 3.78490
  Classification -> best τ=0.400 (val F1=0.0586)
  Directional -> Accuracy: 0.5227, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.46631 | val 1.59982
  Epoch 012 - train 0.32537 | val 1.97639
  Classification -> best τ=0.585 (val F1=0.3243)
  Directional -> Accuracy: 0.4627, MCC: 0.1532, F1: 0.1000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.26280 | val 1.87965
  Epoch 012 - train 0.10826 | val 1.58500
  Classification -> best τ=0.320 (val F1=0.2933)
  Directional -> Accuracy: 0.7209, MCC: 0.4416, F1: 0.7273

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.30437 | val 4.68999
  Epoch 011 - train 0.24551 | val 4.79600
  Classification -> best τ=0.105 (val F1=0.1771)
  Directional -> Accuracy: 0.5789, MCC: 0.2313, F1: 0.6667

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.25169 | val 1.43121
  Epoch 016 - train 0.04104 | val 1.89198
  Classification -> best τ=0.105 (val F1=0.3834)
  Directional -> Accuracy: 0.6170, MCC: 0.0000, F1: 0.7632

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.24561 | val 2.16855
  Epoch 013 - train 0.10257 | val 3.98238
  Classification -> best τ=0.405 (val F1=0.3025)
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.26346 | val 3.95960
  Epoch 012 - train 0.11299 | val 4.65944
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.39602 | val 4.94434
  Epoch 011 - train 0.34491 | val 3.80623
  Classification -> best τ=0.195 (val F1=0.2995)
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.31762 | val 0.71240
  Epoch 015 - train 0.09353 | val 0.75443
  Classification -> best τ=0.465 (val F1=0.5404)
  Directional -> Accuracy: 0.6170, MCC: 0.2631, F1: 0.7000

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.13612 | val 3.43086
  Epoch 011 - train 0.10540 | val 2.67848
  Classification -> best τ=0.625 (val F1=0.5880)
  Directional -> Accuracy: 0.5909, MCC: 0.1394, F1: 0.6786

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.21914 | val 5.88908
  Epoch 011 - train 0.12792 | val 6.19653
  Classification -> best τ=0.375 (val F1=0.4714)
  Directional -> Accuracy: 0.3469, MCC: -0.2592, F1: 0.5152

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.35514 | val 2.11361
  Epoch 011 - train 0.29958 | val 1.82840
  Classification -> best τ=0.645 (val F1=0.2639)
  Directional -> Accuracy: 0.5179, MCC: -0.1255, F1: 0.6824

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.25389 | val 3.38611
  Epoch 011 - train 0.16914 | val 1.95522
  Classification -> best τ=0.655 (val F1=0.2671)
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.45598 | val 2.42319
  Epoch 012 - train 0.35853 | val 1.56061
  Classification -> best τ=0.605 (val F1=0.2078)
  Directional -> Accuracy: 0.4444, MCC: -0.1065, F1: 0.2857

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.38276 | val 2.44578
  Epoch 012 - train 0.23358 | val 2.75971
  Classification -> best τ=0.480 (val F1=0.2539)
  Directional -> Accuracy: 0.4821, MCC: -0.0069, F1: 0.0645

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.39231 | val 1.03492

[I 2026-02-22 10:29:24,337] Trial 96 finished with value: 0.2541161319933796 and parameters: {'feature_set': 'sector', 'model_type': 'BiGRU', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 64, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.1, 'batch_size': 16, 'learning_rate': 0.008091055206507823, 'weight_decay': 1.263377628968578e-05, 'lr_patience': 7, 'lr_factor': 0.8, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 1.4490973910327203, 'early_stopping_min_delta': 0.004346850333630308}. Best is trial 22 with value: 0.2833350641483003.

  Epoch 012 - train 0.29674 | val 0.88884
  Classification -> best τ=0.540 (val F1=0.3467)
  Directional -> Accuracy: 0.5246, MCC: 0.0218, F1: 0.2564

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2541161319933796
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: classification
Sequence length: 6
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'positive_emotion', 'negative_emotion', 'uncertainty_emotion', 'positive_emotion_pct', 'negative_emotion_pct', 'uncertainty_emotion_pct']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.46054 | val 0.97712
  Epoch 020 - train 0.06906 | val 1.78284
  Epoch 022 - train 0.04341 | val 2.02100
  Classification -> best τ=0.765 (val F1=0.2346)
  Directional -> Accuracy: 0.5570, MCC: 0.0000, F1: 0.0000

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 82). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.39128 | val 0.86455
  Epoch 020 - train 0.10690 | val 1.58126
  Epoch 021 - train 0.10475 | val 1.60727
  Classification -> best τ=0.520 (val F1=0.0476)
  Directional -> Accuracy: 0.6250, MCC: 0.2186, F1: 0.7188

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 82). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.38072 | val 1.34515
  Epoch 020 - train 0.05582 | val 2.72726
  Epoch 022 - train 0.04425 | val 2.86506
  Classification -> best τ=0.365 (val F1=0.3612)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.52948 | val 0.71825
  Epoch 020 - train 0.12351 | val 0.87115
  Epoch 026 - train 0.05830 | val 0.95337
  Classification -> best τ=0.500 (val F1=0.1163)
  Directional -> Accuracy: 0.5455, MCC: 0.0000, F1: 0.7059

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.24242 | val 1.06081
  Epoch 020 - train 0.02984 | val 1.49206
  Epoch 021 - train 0.02885 | val 1.54106
  Classification -> best τ=0.625 (val F1=0.3984)
  Directional -> Accuracy: 0.4528, MCC: -0.1468, F1: 0.0000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.32532 | val 0.90133
  Epoch 020 - train 0.09870 | val 1.08150
  Epoch 021 - train 0.09893 | val 1.10007
  Classification -> best τ=0.555 (val F1=0.3052)
  Directional -> Accuracy: 0.6098, MCC: 0.3023, F1: 0.2727

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.49383 | val 0.93772
  Epoch 020 - train 0.20125 | val 2.03218
  Epoch 021 - train 0.18058 | val 2.08801
  Classification -> best τ=0.570 (val F1=0.2807)
  Directional -> Accuracy: 0.5634, MCC: 0.0917, F1: 0.4561

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 82). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 82). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.36113 | val 1.62765
  Epoch 020 - train 0.11051 | val 3.21797
  Epoch 021 - train 0.09811 | val 3.20186
  Classification -> best τ=0.555 (val F1=0.1754)
  Directional -> Accuracy: 0.4043, MCC: 0.0000, F1: 0.5758

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.33331 | val 2.07117
  Epoch 020 - train 0.07589 | val 2.70568
  Epoch 023 - train 0.05466 | val 2.49678
  Classification -> best τ=0.470 (val F1=0.3603)
  Directional -> Accuracy: 0.5581, MCC: 0.0852, F1: 0.4571

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 82). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 82). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.43269 | val 0.91120
  Epoch 020 - train 0.08640 | val 2.05573
  Epoch 023 - train 0.06315 | val 2.27498
  Classification -> best τ=0.585 (val F1=0.2231)
  Directional -> Accuracy: 0.5278, MCC: 0.0370, F1: 0.4516

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.34674 | val 1.19733
  Epoch 020 - train 0.01104 | val 2.75403
  Epoch 024 - train 0.00756 | val 2.83492
  Classification -> best τ=0.560 (val F1=0.2430)
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.35288 | val 1.55977
  Epoch 020 - train 0.04955 | val 2.86354
  Epoch 021 - train 0.03929 | val 2.82405
  Classification -> best τ=0.440 (val F1=0.2121)
  Directional -> Accuracy: 0.6000, MCC: 0.2182, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.38853 | val 1.00766
  Epoch 020 - train 0.02804 | val 1.20845
  Epoch 026 - train 0.01420 | val 1.39962
  Classification -> best τ=0.590 (val F1=0.2887)
  Directional -> Accuracy: 0.4667, MCC: 0.0000, F1: 0.6364

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 82). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.53365 | val 0.72017
  Epoch 020 - train 0.13749 | val 1.00214
  Epoch 021 - train 0.11676 | val 1.05808
  Classification -> best τ=0.440 (val F1=0.3371)
  Directional -> Accuracy: 0.5238, MCC: 0.0484, F1: 0.5312

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.39753 | val 1.04402
  Epoch 020 - train 0.13070 | val 1.80433
  Epoch 021 - train 0.12272 | val 1.94866
  Classification -> best τ=0.510 (val F1=0.3225)
  Directional -> Accuracy: 0.5370, MCC: 0.1425, F1: 0.0741

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.46434 | val 1.13233
  Epoch 020 - train 0.20202 | val 1.67036
  Epoch 021 - train 0.19165 | val 1.74878
  Classification -> best τ=0.395 (val F1=0.2789)
  Directional -> Accuracy: 0.6111, MCC: 0.2423, F1: 0.7255

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.39228 | val 1.83438
  Epoch 020 - train 0.12633 | val 2.78894
  Epoch 021 - train 0.10834 | val 2.82418
  Classification -> best τ=0.600 (val F1=0.2688)
  Directional -> Accuracy: 0.4918, MCC: 0.0621, F1: 0.4561

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.45517 | val 0.79082
  Epoch 020 - train 0.13070 | val 1.59115
  Epoch 021 - train 0.11962 | val 1.67283
  Classification -> best τ=0.620 (val F1=0.2627)
  Directional -> Accuracy: 0.3974, MCC: -0.0340, F1: 0.0408

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.55685 | val 0.87051
  Epoch 020 - train 0.07449 | val 1.31498
  Epoch 024 - train 0.04874 | val 1.38887
  Classification -> best τ=0.375 (val F1=0.3194)
  Directional -> Accuracy: 0.4925, MCC: 0.1096, F1: 0.3462

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 82). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.36589 | val 1.05592
  Epoch 020 - train 0.10502 | val 1.45156
  Epoch 021 - train 0.10047 | val 1.48841
  Classification -> best τ=0.535 (val F1=0.2358)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.29838 | val 0.97397
  Epoch 020 - train 0.02193 | val 1.99356
  Epoch 022 - train 0.01743 | val 2.06335
  Classification -> best τ=0.540 (val F1=0.2926)
  Directional -> Accuracy: 0.5600, MCC: 0.1042, F1: 0.6207

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 82). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 82). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 82). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.42254 | val 0.92340
  Epoch 020 - train 0.07772 | val 1.86596
  Epoch 021 - train 0.06672 | val 1.88008
  Classification -> best τ=0.570 (val F1=0.2390)
  Directional -> Accuracy: 0.4559, MCC: -0.0983, F1: 0.3019

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.39008 | val 1.29131
  Epoch 020 - train 0.10202 | val 2.63992
  Epoch 021 - train 0.09789 | val 2.64294
  Classification -> best τ=0.645 (val F1=0.2668)
  Directional -> Accuracy: 0.5167, MCC: 0.1465, F1: 0.4082

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.39914 | val 0.77991
  Epoch 020 - train 0.09664 | val 1.12129
  Epoch 021 - train 0.08453 | val 1.11078
  Classification -> best τ=0.475 (val F1=0.0277)
  Directional -> Accuracy: 0.4853, MCC: -0.0190, F1: 0.5679

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.45976 | val 1.08723
  Epoch 020 - train 0.10335 | val 2.39019
  Epoch 023 - train 0.07662 | val 2.47255
  Classification -> best τ=0.660 (val F1=0.4101)
  Directional -> Accuracy: 0.5172, MCC: 0.1180, F1: 0.3636

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.23050 | val 0.77757
  Epoch 020 - train 0.03867 | val 1.68844
  Epoch 023 - train 0.02621 | val 1.58911
  Classification -> best τ=0.450 (val F1=0.3812)
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.36972 | val 0.77868
  Epoch 020 - train 0.09694 | val 1.96014
  Epoch 022 - train 0.07978 | val 2.20156
  Classification -> best τ=0.495 (val F1=0.1022)
  Directional -> Accuracy: 0.6222, MCC: 0.2204, F1: 0.6792

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.38539 | val 1.35209
  Epoch 020 - train 0.11085 | val 2.77608
  Epoch 021 - train 0.10193 | val 2.78994
  Classification -> best τ=0.620 (val F1=0.1531)
  Directional -> Accuracy: 0.4407, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.40251 | val 2.17346
  Epoch 020 - train 0.02293 | val 0.93527
  Epoch 030 - train 0.00620 | val 1.24305
  Epoch 032 - train 0.00547 | val 1.25337
  Classification -> best τ=0.370 (val F1=0.3411)
  Directional -> Accuracy: 0.4545, MCC: -0.1314, F1: 0.5714

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.28168 | val 1.39417
  Epoch 020 - train 0.05021 | val 2.58464
  Epoch 022 - train 0.04078 | val 2.63857
  Classification -> best τ=0.550 (val F1=0.2479)
  Directional -> Accuracy: 0.5217, MCC: 0.0483, F1: 0.6071

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.35154 | val 1.37994
  Epoch 020 - train 0.09173 | val 2.74539
  Epoch 021 - train 0.08084 | val 2.77699
  Classification -> best τ=0.490 (val F1=0.2227)
  Directional -> Accuracy: 0.5435, MCC: 0.0000, F1: 0.7042

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.38791 | val 0.91507
  Epoch 020 - train 0.03256 | val 2.02838
  Epoch 023 - train 0.02058 | val 2.11149
  Classification -> best τ=0.525 (val F1=0.2879)
  Directional -> Accuracy: 0.5192, MCC: 0.0385, F1: 0.5283

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.49561 | val 0.71531
  Epoch 020 - train 0.14431 | val 0.98595
  Epoch 021 - train 0.13122 | val 1.06670
  Classification -> best τ=0.360 (val F1=0.3761)
  Directional -> Accuracy: 0.5467, MCC: 0.0684, F1: 0.6136

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 82). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.35788 | val 1.73162
  Epoch 020 - train 0.09228 | val 2.67330
  Epoch 021 - train 0.08479 | val 2.63832
  Classification -> best τ=0.520 (val F1=0.1918)
  Directional -> Accuracy: 0.5122, MCC: 0.0358, F1: 0.5833

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.38156 | val 0.93510
  Epoch 020 - train 0.05605 | val 1.35217
  Epoch 021 - train 0.05167 | val 1.41842
  Classification -> best τ=0.485 (val F1=0.3883)
  Directional -> Accuracy: 0.5217, MCC: 0.1453, F1: 0.6333

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.40694 | val 0.84736
  Epoch 020 - train 0.05474 | val 2.08112
  Epoch 021 - train 0.04466 | val 2.12962
  Classification -> best τ=0.385 (val F1=0.3136)
  Directional -> Accuracy: 0.5507, MCC: 0.0192, F1: 0.6667

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.30180 | val 1.21999
  Epoch 020 - train 0.03935 | val 1.89456
  Epoch 024 - train 0.02590 | val 1.99462
  Classification -> best τ=0.375 (val F1=0.4122)
  Directional -> Accuracy: 0.6222, MCC: 0.2882, F1: 0.5143

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.44865 | val 0.90725
  Epoch 020 - train 0.06447 | val 1.71749
  Epoch 023 - train 0.03995 | val 1.94213
  Classification -> best τ=0.325 (val F1=0.1768)
  Directional -> Accuracy: 0.5254, MCC: 0.0594, F1: 0.5484

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.34127 | val 1.66737
  Epoch 020 - train 0.05861 | val 2.89541
  Epoch 021 - train 0.05229 | val 2.93572
  Classification -> best τ=0.345 (val F1=0.1612)
  Directional -> Accuracy: 0.5306, MCC: 0.0395, F1: 0.5965

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 82). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 82). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 82). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 82). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.32438 | val 1.02054
  Epoch 020 - train 0.06472 | val 1.53490
  Epoch 021 - train 0.05646 | val 1.56480
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.3333, MCC: 0.0000, F1: 0.5000

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 82). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.35937 | val 1.42677
  Epoch 020 - train 0.09328 | val 2.29730
  Epoch 021 - train 0.08827 | val 2.29785
  Classification -> best τ=0.425 (val F1=0.3780)
  Directional -> Accuracy: 0.4878, MCC: -0.1543, F1: 0.6557

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 82). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 82). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.47453 | val 1.57288
  Epoch 020 - train 0.17499 | val 2.71956
  Epoch 022 - train 0.14198 | val 2.74414
  Classification -> best τ=0.550 (val F1=0.1488)
  Directional -> Accuracy: 0.5325, MCC: 0.0772, F1: 0.6538

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 82). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 82). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.37037 | val 1.49860
  Epoch 020 - train 0.14286 | val 2.34493
  Epoch 021 - train 0.12276 | val 2.37130
  Classification -> best τ=0.545 (val F1=0.2953)
  Directional -> Accuracy: 0.5918, MCC: 0.1936, F1: 0.4737

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.31998 | val 3.21108
  Epoch 020 - train 0.06514 | val 4.69285
  Epoch 021 - train 0.06859 | val 4.68057
  Classification -> best τ=0.680 (val F1=0.4196)
  Directional -> Accuracy: 0.4043, MCC: -0.1713, F1: 0.0000

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.35140 | val 0.79360
  Epoch 020 - train 0.12035 | val 1.11205
  Epoch 021 - train 0.11816 | val 1.10692
  Classification -> best τ=0.695 (val F1=0.1425)
  Directional -> Accuracy: 0.3571, MCC: 0.0000, F1: 0.5263

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.46262 | val 0.82892
  Epoch 020 - train 0.06709 | val 2.21835
  Epoch 021 - train 0.05899 | val 2.37157
  Classification -> best τ=0.470 (val F1=0.2517)
  Directional -> Accuracy: 0.6034, MCC: 0.2949, F1: 0.5106

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.41612 | val 2.76463
  Epoch 020 - train 0.12733 | val 4.59354
  Epoch 021 - train 0.11027 | val 4.73589
  Classification -> best τ=0.435 (val F1=0.2470)
  Directional -> Accuracy: 0.4915, MCC: 0.0000, F1: 0.6591

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.44455 | val 0.82718
  Epoch 020 - train 0.17353 | val 0.85730

[I 2026-02-22 10:30:44,201] Trial 97 finished with value: 0.25354442664633686 and parameters: {'feature_set': 'unified_emotion', 'model_type': 'GRU', 'sequence_length': 6, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.1, 'dropout': 0.0, 'batch_size': 32, 'learning_rate': 0.005149351025367001, 'weight_decay': 1.9569561654150264e-06, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 50, 'huber_delta': 1.0966673130122215, 'early_stopping_min_delta': 0.009218513513198943}. Best is trial 22 with value: 0.2833350641483003.

  Epoch 029 - train 0.02532 | val 2.05214
  Classification -> best τ=0.505 (val F1=0.2821)
  Directional -> Accuracy: 0.4603, MCC: -0.0935, F1: 0.3704

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.25354442664633686
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d', 'positive_emotion', 'negative_emotion', 'uncertainty_emotion', 'positive_emotion_pct', 'negative_emotion_pct', 'uncertainty_emotion_pct']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.26367 | val 0.82660
  Epoch 013 - train 0.17033 | val 1.16983
  Classification -> best τ=0.525 (val F1=0.2919)
  Directional -> Accuracy: 0.5658, MCC: 0.1148, F1: 0.4923

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.21268 | val 0.82961
  Epoch 011 - train 0.18870 | val 0.89128
  Classification -> best τ=0.495 (val F1=0.2523)
  Directional -> Accuracy: 0.6000, MCC: 0.2213, F1: 0.6087

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.18951 | val 1.61985
  Epoch 011 - train 0.14195 | val 1.90913
  Classification -> best τ=0.500 (val F1=0.1978)
  Directional -> Accuracy: 0.4783, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.34989 | val 1.71548
  Epoch 011 - train 0.31213 | val 2.14489
  Classification -> best τ=0.440 (val F1=0.1593)
  Directional -> Accuracy: 0.4730, MCC: -0.0587, F1: 0.5063

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.18361 | val 0.81541
  Epoch 014 - train 0.08501 | val 1.37336
  Classification -> best τ=0.530 (val F1=0.3641)
  Directional -> Accuracy: 0.5800, MCC: 0.2417, F1: 0.4000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.25802 | val 1.02062
  Epoch 011 - train 0.20065 | val 1.09210
  Classification -> best τ=0.520 (val F1=0.2937)
  Directional -> Accuracy: 0.4348, MCC: -0.1326, F1: 0.4091

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.29160 | val 1.58505
  Epoch 011 - train 0.22726 | val 1.58240
  Classification -> best τ=0.500 (val F1=0.1963)
  Directional -> Accuracy: 0.4853, MCC: 0.0621, F1: 0.5333

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.20075 | val 0.62069
  Epoch 020 - train 0.01663 | val 0.58343
  Epoch 027 - train 0.00221 | val 0.68945
  Classification -> best τ=0.555 (val F1=0.5212)
  Directional -> Accuracy: 0.5000, MCC: 0.0430, F1: 0.5333

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.21127 | val 1.07520
  Epoch 012 - train 0.14782 | val 1.21364
  Classification -> best τ=0.520 (val F1=0.1837)
  Directional -> Accuracy: 0.5625, MCC: 0.2456, F1: 0.6441

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.20785 | val 1.05769
  Epoch 012 - train 0.13765 | val 1.34109
  Classification -> best τ=0.485 (val F1=0.3582)
  Directional -> Accuracy: 0.4493, MCC: 0.0169, F1: 0.5682

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.19083 | val 1.20089
  Epoch 011 - train 0.15422 | val 1.21953
  Classification -> best τ=0.530 (val F1=0.2495)
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.24565 | val 1.54365
  Epoch 011 - train 0.22756 | val 1.76596
  Classification -> best τ=0.490 (val F1=0.1613)
  Directional -> Accuracy: 0.6140, MCC: 0.2849, F1: 0.7105

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.24216 | val 1.02724
  Epoch 011 - train 0.20245 | val 1.07997
  Classification -> best τ=0.465 (val F1=0.1991)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.6230

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.24170 | val 0.74000
  Epoch 016 - train 0.08223 | val 2.04875
  Classification -> best τ=0.560 (val F1=0.3748)
  Directional -> Accuracy: 0.4833, MCC: -0.0765, F1: 0.0606

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.29250 | val 2.14275
  Epoch 013 - train 0.14564 | val 3.61241
  Classification -> best τ=0.450 (val F1=0.2147)
  Directional -> Accuracy: 0.5882, MCC: 0.1793, F1: 0.5714

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.31036 | val 1.16089
  Epoch 012 - train 0.22150 | val 1.54508
  Classification -> best τ=0.475 (val F1=0.3223)
  Directional -> Accuracy: 0.5797, MCC: 0.1455, F1: 0.6420

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.25647 | val 1.12866
  Epoch 011 - train 0.18568 | val 1.36218
  Classification -> best τ=0.540 (val F1=0.1599)
  Directional -> Accuracy: 0.4310, MCC: 0.1135, F1: 0.1951

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.31303 | val 1.21428
  Epoch 011 - train 0.27059 | val 1.45588
  Classification -> best τ=0.550 (val F1=0.1087)
  Directional -> Accuracy: 0.3467, MCC: -0.2376, F1: 0.1404

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.27005 | val 1.09472
  Epoch 013 - train 0.14316 | val 1.62688
  Classification -> best τ=0.410 (val F1=0.2914)
  Directional -> Accuracy: 0.5625, MCC: 0.0185, F1: 0.6957

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.34058 | val 0.79600
  Epoch 014 - train 0.21819 | val 1.00011
  Classification -> best τ=0.455 (val F1=0.3362)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.18217 | val 1.02298
  Epoch 011 - train 0.16925 | val 1.25938
  Classification -> best τ=0.475 (val F1=0.2427)
  Directional -> Accuracy: 0.3830, MCC: -0.2072, F1: 0.4082

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.25137 | val 1.81100
  Epoch 011 - train 0.22729 | val 1.93880
  Classification -> best τ=0.515 (val F1=0.1925)
  Directional -> Accuracy: 0.4923, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.25283 | val 0.89690
  Epoch 013 - train 0.15020 | val 1.34625
  Classification -> best τ=0.485 (val F1=0.3604)
  Directional -> Accuracy: 0.6316, MCC: 0.2349, F1: 0.7200

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.27016 | val 1.41769
  Epoch 011 - train 0.22430 | val 1.48105
  Classification -> best τ=0.465 (val F1=0.1599)
  Directional -> Accuracy: 0.4615, MCC: -0.0836, F1: 0.6237

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.22524 | val 1.12545
  Epoch 014 - train 0.08262 | val 1.98373
  Classification -> best τ=0.510 (val F1=0.3823)
  Directional -> Accuracy: 0.5273, MCC: 0.1286, F1: 0.3810

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.12917 | val 0.88835
  Epoch 011 - train 0.10496 | val 1.00361
  Classification -> best τ=0.525 (val F1=0.0777)
  Directional -> Accuracy: 0.5778, MCC: 0.0000, F1: 0.0000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.24128 | val 0.82171
  Epoch 011 - train 0.19405 | val 0.98928
  Classification -> best τ=0.505 (val F1=0.1750)
  Directional -> Accuracy: 0.3810, MCC: -0.2582, F1: 0.0000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.26569 | val 1.17894
  Epoch 011 - train 0.24836 | val 1.22487
  Classification -> best τ=0.515 (val F1=0.0951)
  Directional -> Accuracy: 0.4821, MCC: 0.1096, F1: 0.1714

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.17807 | val 0.86565
  Epoch 013 - train 0.09212 | val 0.96334
  Classification -> best τ=0.455 (val F1=0.4181)
  Directional -> Accuracy: 0.5500, MCC: 0.0503, F1: 0.6667

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.23216 | val 0.93839
  Epoch 011 - train 0.20725 | val 0.94026
  Classification -> best τ=0.600 (val F1=0.2814)
  Directional -> Accuracy: 0.5238, MCC: 0.0107, F1: 0.0909

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.18641 | val 1.26587
  Epoch 011 - train 0.16798 | val 1.39647
  Classification -> best τ=0.505 (val F1=0.1286)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.21435 | val 1.34814
  Epoch 013 - train 0.10491 | val 2.08105
  Classification -> best τ=0.425 (val F1=0.3714)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.37014 | val 0.79413
  Epoch 011 - train 0.29978 | val 0.89965
  Classification -> best τ=0.385 (val F1=0.2231)
  Directional -> Accuracy: 0.4861, MCC: 0.0133, F1: 0.4127

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.17799 | val 0.96166
  Epoch 011 - train 0.13734 | val 1.07480
  Classification -> best τ=0.510 (val F1=0.3417)
  Directional -> Accuracy: 0.6047, MCC: 0.2502, F1: 0.4138

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.36708 | val 0.99273
  Epoch 011 - train 0.32474 | val 1.25990
  Classification -> best τ=0.480 (val F1=0.3787)
  Directional -> Accuracy: 0.5303, MCC: 0.1551, F1: 0.4364

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.18761 | val 0.80373
  Epoch 011 - train 0.15654 | val 0.77893
  Classification -> best τ=0.460 (val F1=0.2193)
  Directional -> Accuracy: 0.6667, MCC: 0.3553, F1: 0.6316

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.18451 | val 1.42576
  Epoch 011 - train 0.15297 | val 1.72278
  Classification -> best τ=0.475 (val F1=0.2530)
  Directional -> Accuracy: 0.5179, MCC: 0.0333, F1: 0.4906

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.16807 | val 0.88454
  Epoch 014 - train 0.07805 | val 1.41341
  Classification -> best τ=0.650 (val F1=0.3294)
  Directional -> Accuracy: 0.3913, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.22573 | val 0.66042
  Epoch 020 - train 0.01441 | val 1.23897
  Classification -> best τ=0.665 (val F1=0.3887)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.29904 | val 1.98784
  Epoch 011 - train 0.24017 | val 2.01375
  Classification -> best τ=0.490 (val F1=0.2266)
  Directional -> Accuracy: 0.5135, MCC: 0.0094, F1: 0.1818

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.27526 | val 0.76099
  Epoch 016 - train 0.05009 | val 1.27665
  Classification -> best τ=0.475 (val F1=0.4632)
  Directional -> Accuracy: 0.4667, MCC: -0.1221, F1: 0.6129

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.18260 | val 0.71555
  Epoch 011 - train 0.14428 | val 0.71820
  Classification -> best τ=0.520 (val F1=0.1667)
  Directional -> Accuracy: 0.4286, MCC: -0.0913, F1: 0.3333

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.22777 | val 0.65809
  Epoch 020 - train 0.00868 | val 1.10587
  Epoch 022 - train 0.00495 | val 1.26465
  Classification -> best τ=0.545 (val F1=0.4371)
  Directional -> Accuracy: 0.4792, MCC: 0.1981, F1: 0.5763

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.19517 | val 1.18570
  Epoch 011 - train 0.16151 | val 1.41319
  Classification -> best τ=0.555 (val F1=0.2036)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.17876 | val 0.84796
  Epoch 017 - train 0.02250 | val 1.65817
  Classification -> best τ=0.385 (val F1=0.3401)
  Directional -> Accuracy: 0.5179, MCC: 0.0875, F1: 0.6400

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.19634 | val 1.03555
  Epoch 011 - train 0.14926 | val 1.21775
  Classification -> best τ=0.500 (val F1=0.2127)
  Directional -> Accuracy: 0.5283, MCC: 0.1413, F1: 0.6835

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.25164 | val 1.05595
  Epoch 011 - train 0.19717 | val 1.29642
  Classification -> best τ=0.550 (val F1=0.1884)
  Directional -> Accuracy: 0.5091, MCC: -0.0125, F1: 0.6197

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.33298 | val 0.77498

[I 2026-02-22 10:31:44,816] Trial 98 finished with value: 0.267729824610307 and parameters: {'feature_set': 'sector_unified_emotion', 'model_type': 'BiLSTM', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 64, 'num_layers': 1, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.0, 'batch_size': 64, 'learning_rate': 0.0034438871000278394, 'weight_decay': 7.663431780654599e-06, 'lr_patience': 7, 'lr_factor': 0.8, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 1.2566021817269206, 'early_stopping_min_delta': 0.008669732176421575}. Best is trial 22 with value: 0.2833350641483003.

  Epoch 016 - train 0.11991 | val 1.00820
  Classification -> best τ=0.490 (val F1=0.3575)
  Directional -> Accuracy: 0.5333, MCC: 0.0704, F1: 0.5484

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.267729824610307
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d', 'positive_emotion', 'negative_emotion', 'uncertainty_emotion', 'positive_emotion_pct', 'negative_emotion_pct', 'uncertainty_emotion_pct']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.47995 | val 0.72536
  Epoch 013 - train 0.41070 | val 1.01634
  Classification -> best τ=0.525 (val F1=0.2919)
  Directional -> Accuracy: 0.5789, MCC: 0.1288, F1: 0.4483

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.39810 | val 0.89951
  Epoch 014 - train 0.27830 | val 1.18435
  Classification -> best τ=0.475 (val F1=0.1764)
  Directional -> Accuracy: 0.6889, MCC: 0.4024, F1: 0.6957

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.43848 | val 1.16641
  Epoch 011 - train 0.43314 | val 1.29623
  Classification -> best τ=0.515 (val F1=0.1383)
  Directional -> Accuracy: 0.4783, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.51196 | val 1.50779
  Epoch 011 - train 0.49119 | val 1.66896
  Classification -> best τ=0.415 (val F1=0.1235)
  Directional -> Accuracy: 0.5270, MCC: -0.0200, F1: 0.6729

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.46982 | val 0.75854
  Epoch 014 - train 0.31350 | val 0.88309
  Classification -> best τ=0.515 (val F1=0.3968)
  Directional -> Accuracy: 0.5800, MCC: 0.2203, F1: 0.4324

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.42549 | val 0.70782
  Epoch 011 - train 0.32833 | val 0.78205
  Classification -> best τ=0.540 (val F1=0.1808)
  Directional -> Accuracy: 0.4783, MCC: -0.0382, F1: 0.5000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.46267 | val 0.95719
  Epoch 011 - train 0.46301 | val 1.00564
  Classification -> best τ=0.500 (val F1=0.3336)
  Directional -> Accuracy: 0.4853, MCC: 0.0621, F1: 0.5333

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.37564 | val 0.54526
  Epoch 020 - train 0.17212 | val 0.52505
  Epoch 023 - train 0.13861 | val 0.91884
  Classification -> best τ=0.545 (val F1=0.5247)
  Directional -> Accuracy: 0.4762, MCC: -0.1452, F1: 0.2143

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.43731 | val 1.02757
  Epoch 011 - train 0.38063 | val 1.18914
  Classification -> best τ=0.550 (val F1=0.1608)
  Directional -> Accuracy: 0.5833, MCC: 0.1534, F1: 0.5238

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.45364 | val 0.85703
  Epoch 011 - train 0.43288 | val 0.88054
  Classification -> best τ=0.515 (val F1=0.2260)
  Directional -> Accuracy: 0.4203, MCC: 0.0000, F1: 0.5918

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.40303 | val 0.91937
  Epoch 011 - train 0.34899 | val 0.82982
  Classification -> best τ=0.490 (val F1=0.1199)
  Directional -> Accuracy: 0.4490, MCC: 0.0000, F1: 0.6197

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.47340 | val 0.97177
  Epoch 011 - train 0.41160 | val 1.24239
  Classification -> best τ=0.470 (val F1=0.1009)
  Directional -> Accuracy: 0.5088, MCC: 0.0000, F1: 0.6744

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.38257 | val 0.95417
  Epoch 011 - train 0.37061 | val 0.95526
  Classification -> best τ=0.465 (val F1=0.1991)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.6230

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.45601 | val 0.87630
  Epoch 017 - train 0.26652 | val 1.64414
  Classification -> best τ=0.480 (val F1=0.3362)
  Directional -> Accuracy: 0.4667, MCC: -0.1336, F1: 0.0588

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.48744 | val 1.00350
  Epoch 011 - train 0.42070 | val 1.13962
  Classification -> best τ=0.485 (val F1=0.1556)
  Directional -> Accuracy: 0.5686, MCC: 0.1560, F1: 0.0833

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.49131 | val 1.16817
  Epoch 012 - train 0.40707 | val 0.98697
  Classification -> best τ=0.550 (val F1=0.2693)
  Directional -> Accuracy: 0.5507, MCC: 0.0822, F1: 0.6265

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.43568 | val 1.04196
  Epoch 011 - train 0.39445 | val 1.11102
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.6207, MCC: 0.0000, F1: 0.7660

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.52916 | val 1.14501
  Epoch 011 - train 0.47972 | val 1.17710
  Classification -> best τ=0.465 (val F1=0.1348)
  Directional -> Accuracy: 0.6000, MCC: 0.0000, F1: 0.7500

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.51759 | val 0.77520
  Epoch 012 - train 0.46075 | val 0.88770
  Classification -> best τ=0.455 (val F1=0.2843)
  Directional -> Accuracy: 0.5156, MCC: 0.1279, F1: 0.4151

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.48524 | val 0.85010
  Epoch 016 - train 0.29735 | val 1.01282
  Classification -> best τ=0.260 (val F1=0.2866)
  Directional -> Accuracy: 0.4054, MCC: -0.1611, F1: 0.3125

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.42260 | val 0.86554
  Epoch 011 - train 0.35816 | val 0.96653
  Classification -> best τ=0.520 (val F1=0.3114)
  Directional -> Accuracy: 0.3404, MCC: -0.2232, F1: 0.1143

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.54308 | val 1.02444
  Epoch 011 - train 0.40371 | val 0.97220
  Classification -> best τ=0.445 (val F1=0.1886)
  Directional -> Accuracy: 0.5846, MCC: 0.1795, F1: 0.5263

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.52481 | val 0.75254
  Epoch 013 - train 0.39128 | val 0.83534
  Classification -> best τ=0.500 (val F1=0.3944)
  Directional -> Accuracy: 0.5965, MCC: 0.1576, F1: 0.7229

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.44519 | val 0.72194
  Epoch 011 - train 0.45118 | val 0.71801
  Classification -> best τ=0.495 (val F1=0.0417)
  Directional -> Accuracy: 0.5385, MCC: 0.0971, F1: 0.5946

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.44949 | val 0.98886
  Epoch 014 - train 0.30115 | val 1.12413
  Classification -> best τ=0.540 (val F1=0.3860)
  Directional -> Accuracy: 0.5273, MCC: 0.1143, F1: 0.4091

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.29422 | val 1.00603
  Epoch 011 - train 0.21975 | val 1.11148
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.5938

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.47230 | val 0.68738
  Epoch 011 - train 0.44020 | val 0.68374
  Classification -> best τ=0.545 (val F1=0.2402)
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.0000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.42237 | val 0.94609
  Epoch 012 - train 0.37024 | val 1.13349
  Classification -> best τ=0.510 (val F1=0.1615)
  Directional -> Accuracy: 0.4464, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.35391 | val 0.80292
  Epoch 018 - train 0.20477 | val 0.86932
  Classification -> best τ=0.520 (val F1=0.3671)
  Directional -> Accuracy: 0.5750, MCC: 0.1124, F1: 0.6909

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.43365 | val 0.75863
  Epoch 012 - train 0.36267 | val 1.30132
  Classification -> best τ=0.585 (val F1=0.3501)
  Directional -> Accuracy: 0.4762, MCC: -0.0754, F1: 0.3125

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.44318 | val 1.02682
  Epoch 011 - train 0.47319 | val 1.11007
  Classification -> best τ=0.440 (val F1=0.2357)
  Directional -> Accuracy: 0.5476, MCC: 0.0000, F1: 0.7077

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.40601 | val 1.46878
  Epoch 013 - train 0.29946 | val 1.81504
  Classification -> best τ=0.470 (val F1=0.3502)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.46913 | val 1.19242
  Epoch 011 - train 0.45385 | val 1.05707
  Classification -> best τ=0.465 (val F1=0.1774)
  Directional -> Accuracy: 0.4444, MCC: 0.0000, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.34983 | val 1.24790
  Epoch 011 - train 0.34370 | val 1.27178
  Classification -> best τ=0.450 (val F1=0.1874)
  Directional -> Accuracy: 0.5116, MCC: 0.1508, F1: 0.6667

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.51709 | val 0.94805
  Epoch 011 - train 0.49244 | val 1.01583
  Classification -> best τ=0.470 (val F1=0.1632)
  Directional -> Accuracy: 0.5758, MCC: 0.0000, F1: 0.7308

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.40906 | val 1.14432
  Epoch 011 - train 0.37942 | val 1.48249
  Classification -> best τ=0.510 (val F1=0.2658)
  Directional -> Accuracy: 0.6190, MCC: 0.2571, F1: 0.5789

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.38251 | val 1.34066
  Epoch 011 - train 0.36192 | val 1.45085
  Classification -> best τ=0.495 (val F1=0.1781)
  Directional -> Accuracy: 0.4821, MCC: -0.0185, F1: 0.5246

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.30995 | val 0.73063
  Epoch 015 - train 0.22629 | val 1.37527
  Classification -> best τ=0.510 (val F1=0.2852)
  Directional -> Accuracy: 0.3913, MCC: -0.0687, F1: 0.1250

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.51185 | val 0.63990
  Epoch 020 - train 0.20529 | val 0.81851
  Classification -> best τ=0.485 (val F1=0.4242)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.48467 | val 1.27753
  Epoch 011 - train 0.41107 | val 1.39648
  Classification -> best τ=0.550 (val F1=0.2327)
  Directional -> Accuracy: 0.4730, MCC: -0.1027, F1: 0.1702

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.47355 | val 0.68166
  Epoch 015 - train 0.31787 | val 0.91207
  Classification -> best τ=0.515 (val F1=0.3371)
  Directional -> Accuracy: 0.5556, MCC: 0.1202, F1: 0.5000

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.24514 | val 0.69306
  Epoch 015 - train 0.12478 | val 0.94988
  Classification -> best τ=0.355 (val F1=0.3563)
  Directional -> Accuracy: 0.5714, MCC: 0.0323, F1: 0.7188

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.34327 | val 0.65443
  Epoch 020 - train 0.11862 | val 1.08354
  Epoch 021 - train 0.09993 | val 1.12345
  Classification -> best τ=0.455 (val F1=0.3752)
  Directional -> Accuracy: 0.5000, MCC: 0.2928, F1: 0.6000

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.46640 | val 0.94821
  Epoch 011 - train 0.43757 | val 1.03717
  Classification -> best τ=0.590 (val F1=0.2036)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.36298 | val 1.39317
  Epoch 013 - train 0.23093 | val 1.41468
  Classification -> best τ=0.480 (val F1=0.4367)
  Directional -> Accuracy: 0.5000, MCC: 0.0330, F1: 0.6216

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.45232 | val 0.95029
  Epoch 011 - train 0.37814 | val 1.05596
  Classification -> best τ=0.490 (val F1=0.2064)
  Directional -> Accuracy: 0.6226, MCC: 0.2483, F1: 0.6667

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.34986 | val 1.47174
  Epoch 011 - train 0.33804 | val 1.67439
  Classification -> best τ=0.465 (val F1=0.0684)
  Directional -> Accuracy: 0.4909, MCC: -0.0014, F1: 0.4167

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.54278 | val 0.66108

[I 2026-02-22 10:33:23,097] Trial 99 finished with value: 0.2429288064321631 and parameters: {'feature_set': 'sector_unified_emotion', 'model_type': 'BiLSTM', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 64, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.0, 'batch_size': 64, 'learning_rate': 0.006351900892550602, 'weight_decay': 1.6145354219629637e-05, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 1.1451082833208583, 'early_stopping_min_delta': 0.008668587161118001}. Best is trial 22 with value: 0.2833350641483003.

  Epoch 020 - train 0.25683 | val 0.74198
  Classification -> best τ=0.455 (val F1=0.2966)
  Directional -> Accuracy: 0.5333, MCC: 0.0963, F1: 0.6216

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2429288064321631
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d', 'positive_emotion', 'negative_emotion', 'uncertainty_emotion', 'positive_emotion_pct', 'negative_emotion_pct', 'uncertainty_emotion_pct']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.51824 | val 0.82542
  Epoch 015 - train 0.46342 | val 0.78211
  Classification -> best τ=0.500 (val F1=0.2510)
  Directional -> Accuracy: 0.5921, MCC: 0.1586, F1: 0.4746

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.39422 | val 0.73507
  Epoch 011 - train 0.37964 | val 0.74881
  Classification -> best τ=0.485 (val F1=0.1186)
  Directional -> Accuracy: 0.6000, MCC: 0.1764, F1: 0.7429

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.44824 | val 1.33896
  Epoch 011 - train 0.37187 | val 1.62520
  Classification -> best τ=0.490 (val F1=0.2037)
  Directional -> Accuracy: 0.5435, MCC: 0.1286, F1: 0.4000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.52642 | val 1.81309
  Epoch 011 - train 0.48950 | val 1.42575
  Classification -> best τ=0.465 (val F1=0.1602)
  Directional -> Accuracy: 0.4730, MCC: 0.0520, F1: 0.0930

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.44447 | val 0.66951
  Epoch 016 - train 0.29473 | val 0.75881
  Classification -> best τ=0.560 (val F1=0.4947)
  Directional -> Accuracy: 0.6000, MCC: 0.2425, F1: 0.5000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.40492 | val 0.73876
  Epoch 011 - train 0.40232 | val 0.84547
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4783, MCC: 0.0000, F1: 0.6471

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.48587 | val 1.29342
  Epoch 011 - train 0.43932 | val 1.38472
  Classification -> best τ=0.490 (val F1=0.2481)
  Directional -> Accuracy: 0.5294, MCC: 0.0921, F1: 0.5152

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.37190 | val 0.60956
  Epoch 020 - train 0.20152 | val 1.29439
  Epoch 022 - train 0.14974 | val 1.56192
  Classification -> best τ=0.600 (val F1=0.5247)
  Directional -> Accuracy: 0.5238, MCC: 0.0694, F1: 0.5238

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.42566 | val 0.87070
  Epoch 013 - train 0.32459 | val 1.28999
  Classification -> best τ=0.480 (val F1=0.1743)
  Directional -> Accuracy: 0.4375, MCC: 0.0000, F1: 0.6087

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.49530 | val 0.78925
  Epoch 011 - train 0.45901 | val 0.94871
  Classification -> best τ=0.490 (val F1=0.3141)
  Directional -> Accuracy: 0.4203, MCC: 0.0000, F1: 0.5918

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.48538 | val 0.87074
  Epoch 011 - train 0.48411 | val 0.87302
  Classification -> best τ=0.530 (val F1=0.3075)
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.48303 | val 1.50190
  Epoch 011 - train 0.47074 | val 1.83999
  Classification -> best τ=0.440 (val F1=0.1083)
  Directional -> Accuracy: 0.5088, MCC: 0.0000, F1: 0.6744

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.44911 | val 1.00553
  Epoch 013 - train 0.35873 | val 0.98299
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.6230

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.45854 | val 0.72721
  Epoch 015 - train 0.32986 | val 1.18135
  Classification -> best τ=0.545 (val F1=0.4317)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.49385 | val 1.05415
  Epoch 011 - train 0.44490 | val 1.11312
  Classification -> best τ=0.485 (val F1=0.1595)
  Directional -> Accuracy: 0.4118, MCC: -0.1515, F1: 0.4828

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.47345 | val 1.00597
  Epoch 012 - train 0.43073 | val 1.18516
  Classification -> best τ=0.560 (val F1=0.3217)
  Directional -> Accuracy: 0.5362, MCC: 0.0637, F1: 0.5789

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.50961 | val 0.83929
  Epoch 011 - train 0.44906 | val 0.92887
  Classification -> best τ=0.545 (val F1=0.0046)
  Directional -> Accuracy: 0.5517, MCC: -0.0746, F1: 0.6905

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.58678 | val 0.89452
  Epoch 011 - train 0.52618 | val 1.06158
  Classification -> best τ=0.470 (val F1=0.0681)
  Directional -> Accuracy: 0.4267, MCC: -0.1013, F1: 0.4110

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.51099 | val 0.75251
  Epoch 013 - train 0.41125 | val 0.95166
  Classification -> best τ=0.400 (val F1=0.2428)
  Directional -> Accuracy: 0.5469, MCC: -0.0051, F1: 0.6742

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.46130 | val 0.74934
  Epoch 011 - train 0.45759 | val 0.85279
  Classification -> best τ=0.485 (val F1=0.2246)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.36426 | val 0.84484
  Epoch 011 - train 0.32964 | val 0.89194
  Classification -> best τ=0.550 (val F1=0.1978)
  Directional -> Accuracy: 0.4043, MCC: -0.0615, F1: 0.2632

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.47960 | val 0.97147
  Epoch 011 - train 0.45971 | val 0.96726
  Classification -> best τ=0.455 (val F1=0.1592)
  Directional -> Accuracy: 0.4769, MCC: -0.1269, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.44944 | val 0.76716
  Epoch 013 - train 0.43376 | val 1.04405
  Classification -> best τ=0.475 (val F1=0.3566)
  Directional -> Accuracy: 0.5789, MCC: 0.1083, F1: 0.7209

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.55024 | val 0.70708
  Epoch 012 - train 0.45917 | val 0.74087
  Classification -> best τ=0.470 (val F1=0.1974)
  Directional -> Accuracy: 0.5231, MCC: 0.1153, F1: 0.6437

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.41647 | val 0.89292
  Epoch 014 - train 0.33754 | val 1.23174
  Classification -> best τ=0.395 (val F1=0.3750)
  Directional -> Accuracy: 0.6000, MCC: 0.2476, F1: 0.5417

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.30337 | val 0.79407
  Epoch 011 - train 0.30018 | val 0.78621
  Classification -> best τ=0.525 (val F1=0.2035)
  Directional -> Accuracy: 0.4444, MCC: -0.0225, F1: 0.5455

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.49130 | val 0.68408
  Epoch 011 - train 0.48753 | val 0.68241
  Classification -> best τ=0.560 (val F1=0.2402)
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.0000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.44956 | val 0.93110
  Epoch 012 - train 0.39476 | val 1.25226
  Classification -> best τ=0.480 (val F1=0.2816)
  Directional -> Accuracy: 0.4464, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.39010 | val 0.68417
  Epoch 020 - train 0.15874 | val 1.88334
  Epoch 021 - train 0.16840 | val 2.61031
  Classification -> best τ=0.290 (val F1=0.4109)
  Directional -> Accuracy: 0.5500, MCC: 0.0335, F1: 0.6897

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.44502 | val 0.84037
  Epoch 011 - train 0.36704 | val 1.03834
  Classification -> best τ=0.520 (val F1=0.3450)
  Directional -> Accuracy: 0.4762, MCC: -0.1469, F1: 0.0833

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.45049 | val 1.05842
  Epoch 011 - train 0.38719 | val 1.18372
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5476, MCC: 0.0000, F1: 0.7077

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.39945 | val 1.32768
  Epoch 013 - train 0.30763 | val 2.06896
  Classification -> best τ=0.475 (val F1=0.2611)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.54850 | val 1.03181
  Epoch 011 - train 0.52634 | val 0.99352
  Classification -> best τ=0.485 (val F1=0.2458)
  Directional -> Accuracy: 0.4444, MCC: 0.0000, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.39254 | val 1.17750
  Epoch 011 - train 0.37837 | val 1.25762
  Classification -> best τ=0.450 (val F1=0.2717)
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.53856 | val 0.94369
  Epoch 011 - train 0.52625 | val 0.89653
  Classification -> best τ=0.505 (val F1=0.2464)
  Directional -> Accuracy: 0.5758, MCC: 0.0000, F1: 0.7308

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.44115 | val 1.05368
  Epoch 011 - train 0.39611 | val 1.14801
  Classification -> best τ=0.525 (val F1=0.2658)
  Directional -> Accuracy: 0.6429, MCC: 0.3006, F1: 0.6154

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.44352 | val 1.18127
  Epoch 011 - train 0.42489 | val 1.24145
  Classification -> best τ=0.485 (val F1=0.2530)
  Directional -> Accuracy: 0.4643, MCC: -0.0716, F1: 0.4444

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.32695 | val 0.72509
  Epoch 015 - train 0.20133 | val 1.10373
  Classification -> best τ=0.500 (val F1=0.2698)
  Directional -> Accuracy: 0.3696, MCC: -0.1660, F1: 0.2162

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.50333 | val 0.65856
  Epoch 019 - train 0.29614 | val 0.76906
  Classification -> best τ=0.565 (val F1=0.4710)
  Directional -> Accuracy: 0.3333, MCC: -0.1970, F1: 0.5000

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.47092 | val 1.13210
  Epoch 011 - train 0.39527 | val 1.24147
  Classification -> best τ=0.465 (val F1=0.2965)
  Directional -> Accuracy: 0.4595, MCC: -0.1107, F1: 0.2593

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.48631 | val 0.75600
  Epoch 011 - train 0.46344 | val 0.77738
  Classification -> best τ=0.495 (val F1=0.1803)
  Directional -> Accuracy: 0.4889, MCC: -0.1474, F1: 0.6567

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.32999 | val 0.70407
  Epoch 014 - train 0.22931 | val 0.87899
  Classification -> best τ=0.515 (val F1=0.3059)
  Directional -> Accuracy: 0.4524, MCC: -0.0574, F1: 0.4103

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.43111 | val 0.60101
  Epoch 020 - train 0.14749 | val 1.10780
  Classification -> best τ=0.470 (val F1=0.4682)
  Directional -> Accuracy: 0.3958, MCC: 0.1130, F1: 0.5538

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.49289 | val 0.88189
  Epoch 014 - train 0.42340 | val 1.19123
  Classification -> best τ=0.620 (val F1=0.2036)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.38428 | val 0.73077
  Epoch 015 - train 0.23100 | val 1.37063
  Classification -> best τ=0.400 (val F1=0.3536)
  Directional -> Accuracy: 0.5714, MCC: 0.1801, F1: 0.6471

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.47470 | val 0.99610
  Epoch 015 - train 0.33319 | val 1.89711
  Classification -> best τ=0.465 (val F1=0.2298)
  Directional -> Accuracy: 0.5283, MCC: 0.0863, F1: 0.6753

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.47003 | val 1.31123
  Epoch 011 - train 0.40402 | val 1.15852
  Classification -> best τ=0.495 (val F1=0.1200)
  Directional -> Accuracy: 0.5273, MCC: 0.0000, F1: 0.6905

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.55646 | val 0.70965

[I 2026-02-22 10:36:23,797] Trial 100 finished with value: 0.2473695025957324 and parameters: {'feature_set': 'sector_unified_emotion', 'model_type': 'BiLSTM', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.1, 'batch_size': 64, 'learning_rate': 0.00360767762201097, 'weight_decay': 1.059125045051482e-05, 'lr_patience': 7, 'lr_factor': 0.8, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 0.9852183520701355, 'early_stopping_min_delta': 0.007895731888174856}. Best is trial 22 with value: 0.2833350641483003.

  Epoch 017 - train 0.36965 | val 1.00035
  Classification -> best τ=0.640 (val F1=0.3056)
  Directional -> Accuracy: 0.5167, MCC: 0.0236, F1: 0.4082

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2473695025957324
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d', 'positive_emotion', 'negative_emotion', 'uncertainty_emotion', 'positive_emotion_pct', 'negative_emotion_pct', 'uncertainty_emotion_pct']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.28443 | val 0.89850
  Epoch 015 - train 0.14429 | val 2.00980
  Classification -> best τ=0.630 (val F1=0.2919)
  Directional -> Accuracy: 0.6053, MCC: 0.1845, F1: 0.4000

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.21471 | val 0.81189
  Epoch 011 - train 0.19133 | val 0.85145
  Classification -> best τ=0.475 (val F1=0.1722)
  Directional -> Accuracy: 0.5778, MCC: 0.0000, F1: 0.7324

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.17904 | val 1.51519
  Epoch 011 - train 0.15235 | val 1.86346
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5217, MCC: 0.0000, F1: 0.6857

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.35136 | val 2.24322
  Epoch 011 - train 0.32014 | val 2.17995
  Classification -> best τ=0.425 (val F1=0.1422)
  Directional -> Accuracy: 0.5270, MCC: 0.0542, F1: 0.5455

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.25425 | val 0.85128
  Epoch 014 - train 0.10526 | val 1.33398
  Classification -> best τ=0.545 (val F1=0.4259)
  Directional -> Accuracy: 0.5600, MCC: 0.1801, F1: 0.3889

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.23649 | val 0.95916
  Epoch 011 - train 0.19667 | val 0.93548
  Classification -> best τ=0.535 (val F1=0.2208)
  Directional -> Accuracy: 0.5217, MCC: 0.0288, F1: 0.3889

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.30840 | val 1.23779
  Epoch 011 - train 0.27283 | val 1.58814
  Classification -> best τ=0.455 (val F1=0.2466)
  Directional -> Accuracy: 0.5441, MCC: 0.1940, F1: 0.5867

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.24054 | val 0.58729
  Epoch 020 - train 0.02140 | val 0.56394
  Epoch 026 - train 0.00364 | val 0.64083
  Classification -> best τ=0.400 (val F1=0.4839)
  Directional -> Accuracy: 0.4524, MCC: 0.0212, F1: 0.5818

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.24091 | val 1.12616
  Epoch 013 - train 0.14171 | val 1.33619
  Classification -> best τ=0.510 (val F1=0.1975)
  Directional -> Accuracy: 0.6250, MCC: 0.3228, F1: 0.6667

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.22991 | val 0.99918
  Epoch 012 - train 0.17841 | val 1.13648
  Classification -> best τ=0.435 (val F1=0.2079)
  Directional -> Accuracy: 0.4203, MCC: -0.0279, F1: 0.5833

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.27251 | val 0.91650
  Epoch 011 - train 0.20709 | val 0.98639
  Classification -> best τ=0.555 (val F1=0.1593)
  Directional -> Accuracy: 0.5714, MCC: 0.1118, F1: 0.1600

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.27751 | val 1.30947
  Epoch 011 - train 0.18857 | val 1.59911
  Classification -> best τ=0.470 (val F1=0.1771)
  Directional -> Accuracy: 0.6316, MCC: 0.3198, F1: 0.7200

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.27586 | val 0.83861
  Epoch 011 - train 0.22823 | val 0.87666
  Classification -> best τ=0.490 (val F1=0.2545)
  Directional -> Accuracy: 0.4762, MCC: -0.1062, F1: 0.2667

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.26748 | val 0.91011
  Epoch 011 - train 0.22281 | val 0.99983
  Classification -> best τ=0.485 (val F1=0.2845)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.22236 | val 1.04476
  Epoch 011 - train 0.19046 | val 1.32084
  Classification -> best τ=0.515 (val F1=0.2571)
  Directional -> Accuracy: 0.5490, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.32829 | val 1.06310
  Epoch 011 - train 0.28493 | val 1.33367
  Classification -> best τ=0.525 (val F1=0.1561)
  Directional -> Accuracy: 0.5652, MCC: 0.1644, F1: 0.5000

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.24140 | val 1.25216
  Epoch 011 - train 0.20893 | val 1.40240
  Classification -> best τ=0.545 (val F1=0.1342)
  Directional -> Accuracy: 0.3276, MCC: -0.2558, F1: 0.0930

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.31093 | val 1.84883
  Epoch 011 - train 0.26636 | val 2.50525
  Classification -> best τ=0.510 (val F1=0.1548)
  Directional -> Accuracy: 0.4000, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.22787 | val 1.06546
  Epoch 013 - train 0.15593 | val 1.62117
  Classification -> best τ=0.550 (val F1=0.2600)
  Directional -> Accuracy: 0.4375, MCC: 0.1076, F1: 0.0526

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.36100 | val 0.85991
  Epoch 011 - train 0.31469 | val 1.15909
  Classification -> best τ=0.485 (val F1=0.2701)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.17548 | val 0.92429
  Epoch 011 - train 0.14954 | val 0.98460
  Classification -> best τ=0.490 (val F1=0.1830)
  Directional -> Accuracy: 0.4043, MCC: -0.1537, F1: 0.4167

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.26855 | val 1.38234
  Epoch 011 - train 0.23274 | val 1.62236
  Classification -> best τ=0.440 (val F1=0.2281)
  Directional -> Accuracy: 0.5538, MCC: 0.1417, F1: 0.3830

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.31841 | val 1.13518
  Epoch 013 - train 0.16491 | val 1.50901
  Classification -> best τ=0.580 (val F1=0.3175)
  Directional -> Accuracy: 0.4912, MCC: 0.0465, F1: 0.3830

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.27786 | val 1.18033
  Epoch 011 - train 0.24663 | val 1.94101
  Classification -> best τ=0.550 (val F1=0.1393)
  Directional -> Accuracy: 0.5385, MCC: 0.1309, F1: 0.0625

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.32224 | val 1.11906
  Epoch 014 - train 0.13213 | val 1.67322
  Classification -> best τ=0.480 (val F1=0.4075)
  Directional -> Accuracy: 0.5818, MCC: 0.2155, F1: 0.5106

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.16414 | val 0.74663
  Epoch 011 - train 0.13919 | val 0.83775
  Classification -> best τ=0.465 (val F1=0.2097)
  Directional -> Accuracy: 0.5556, MCC: 0.1650, F1: 0.5833

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.22085 | val 0.97329
  Epoch 011 - train 0.19234 | val 0.98912
  Classification -> best τ=0.595 (val F1=0.3184)
  Directional -> Accuracy: 0.4048, MCC: -0.1803, F1: 0.0000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.28981 | val 1.25876
  Epoch 011 - train 0.27983 | val 1.30588
  Classification -> best τ=0.450 (val F1=0.1607)
  Directional -> Accuracy: 0.5357, MCC: 0.1020, F1: 0.5000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.20088 | val 0.68781
  Epoch 017 - train 0.05024 | val 0.83271
  Classification -> best τ=0.410 (val F1=0.4099)
  Directional -> Accuracy: 0.5500, MCC: 0.0503, F1: 0.6667

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.22275 | val 0.79275
  Epoch 011 - train 0.17719 | val 0.91443
  Classification -> best τ=0.550 (val F1=0.3059)
  Directional -> Accuracy: 0.5000, MCC: -0.0561, F1: 0.1600

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.21203 | val 1.13840
  Epoch 011 - train 0.17311 | val 1.49405
  Classification -> best τ=0.430 (val F1=0.0128)
  Directional -> Accuracy: 0.6190, MCC: 0.2311, F1: 0.6522

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.22291 | val 1.26187
  Epoch 013 - train 0.11634 | val 2.06833
  Classification -> best τ=0.465 (val F1=0.3196)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.34003 | val 1.48111
  Epoch 011 - train 0.29524 | val 1.35331
  Classification -> best τ=0.425 (val F1=0.2231)
  Directional -> Accuracy: 0.4861, MCC: 0.0133, F1: 0.4127

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.23468 | val 1.25940
  Epoch 011 - train 0.17245 | val 1.51836
  Classification -> best τ=0.460 (val F1=0.2324)
  Directional -> Accuracy: 0.5581, MCC: 0.1229, F1: 0.3871

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.35400 | val 0.97009
  Epoch 011 - train 0.31187 | val 1.02064
  Classification -> best τ=0.495 (val F1=0.2972)
  Directional -> Accuracy: 0.5455, MCC: 0.0045, F1: 0.6667

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.19141 | val 0.74617
  Epoch 011 - train 0.16410 | val 0.79584
  Classification -> best τ=0.480 (val F1=0.2409)
  Directional -> Accuracy: 0.7381, MCC: 0.4767, F1: 0.7442

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.25059 | val 1.80701
  Epoch 011 - train 0.19577 | val 1.58481
  Classification -> best τ=0.470 (val F1=0.1677)
  Directional -> Accuracy: 0.4464, MCC: -0.0962, F1: 0.4746

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.19383 | val 0.78527
  Epoch 011 - train 0.14409 | val 0.87371
  Classification -> best τ=0.500 (val F1=0.3105)
  Directional -> Accuracy: 0.5435, MCC: -0.1369, F1: 0.6957

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.31378 | val 0.64275
  Epoch 019 - train 0.07022 | val 0.90756
  Classification -> best τ=0.565 (val F1=0.3887)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.27606 | val 1.61165
  Epoch 011 - train 0.22964 | val 1.82086
  Classification -> best τ=0.515 (val F1=0.2205)
  Directional -> Accuracy: 0.5000, MCC: 0.1139, F1: 0.6606

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.24400 | val 0.82145
  Epoch 011 - train 0.15781 | val 0.85576
  Classification -> best τ=0.495 (val F1=0.2169)
  Directional -> Accuracy: 0.5111, MCC: 0.0000, F1: 0.6765

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.23136 | val 0.67865
  Epoch 020 - train 0.01066 | val 0.73548
  Epoch 023 - train 0.00410 | val 0.80765
  Classification -> best τ=0.360 (val F1=0.4423)
  Directional -> Accuracy: 0.5952, MCC: 0.1273, F1: 0.7213

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.23340 | val 0.61975
  Epoch 020 - train 0.01475 | val 0.85353
  Classification -> best τ=0.610 (val F1=0.3895)
  Directional -> Accuracy: 0.6667, MCC: 0.4564, F1: 0.6800

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.23862 | val 1.13756
  Epoch 011 - train 0.19791 | val 1.31638
  Classification -> best τ=0.520 (val F1=0.2036)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.21540 | val 0.97817
  Epoch 013 - train 0.09390 | val 1.51802
  Classification -> best τ=0.495 (val F1=0.3585)
  Directional -> Accuracy: 0.5893, MCC: 0.2147, F1: 0.6567

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.22090 | val 1.09859
  Epoch 011 - train 0.16966 | val 1.34048
  Classification -> best τ=0.520 (val F1=0.1801)
  Directional -> Accuracy: 0.4528, MCC: -0.0930, F1: 0.4314

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.27710 | val 1.45865
  Epoch 011 - train 0.22466 | val 1.69005
  Classification -> best τ=0.595 (val F1=0.1210)
  Directional -> Accuracy: 0.4727, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.26213 | val 0.72755

[I 2026-02-22 10:37:22,507] Trial 101 finished with value: 0.24522954047533332 and parameters: {'feature_set': 'sector_unified_emotion', 'model_type': 'BiLSTM', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 64, 'num_layers': 1, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.0, 'batch_size': 64, 'learning_rate': 0.0030440859528261715, 'weight_decay': 7.37089545066612e-06, 'lr_patience': 7, 'lr_factor': 0.8, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 1.4081137678878999, 'early_stopping_min_delta': 0.00901286891454611}. Best is trial 22 with value: 0.2833350641483003.

  Epoch 015 - train 0.14427 | val 1.11904
  Classification -> best τ=0.515 (val F1=0.2691)
  Directional -> Accuracy: 0.5500, MCC: 0.1920, F1: 0.1290

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.24522954047533332
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sentiment', 'emotion_anger', 'emotion_disgust', 'emotion_fear', 'emotion_joy', 'emotion_neutral', 'emotion_sadness', 'emotion_surprize', 'emotion_anger_pct', 'emotion_disgust_pct', 'emotion_fear_pct', 'emotion_joy_pct', 'emotion_neutral_pct', 'emotion_sadness_pct', 'emotion_surprize_pct', 'positive_emotion', 'negative_emotion', 'uncertainty_emotion', 'positive_emotion_pct', 'negative_emotion_pct', 'uncertainty_emotion_pct', 'stance_label', 'stance_score', 'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down', 'finbert_neutral']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.09656 | val 1.40521
  Epoch 013 - train 0.03009 | val 2.50261
  Classification -> best τ=0.625 (val F1=0.1430)
  Directional -> Accuracy: 0.5658, MCC: 0.1283, F1: 0.0571

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.07014 | val 1.29277
  Epoch 011 - train 0.03927 | val 1.58879
  Classification -> best τ=0.480 (val F1=0.1289)
  Directional -> Accuracy: 0.5778, MCC: 0.0000, F1: 0.7324

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.05753 | val 1.08402
  Epoch 016 - train 0.00240 | val 2.04113
  Classification -> best τ=0.390 (val F1=0.4059)
  Directional -> Accuracy: 0.5870, MCC: 0.1860, F1: 0.6885

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.13962 | val 1.41668
  Epoch 013 - train 0.05176 | val 1.65234
  Classification -> best τ=0.445 (val F1=0.2881)
  Directional -> Accuracy: 0.5000, MCC: 0.0044, F1: 0.5067

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.04306 | val 1.24454
  Epoch 015 - train 0.00325 | val 2.25669
  Classification -> best τ=0.710 (val F1=0.2934)
  Directional -> Accuracy: 0.5000, MCC: 0.0534, F1: 0.1935

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.12103 | val 0.93399
  Epoch 016 - train 0.00726 | val 1.49165
  Classification -> best τ=0.475 (val F1=0.4159)
  Directional -> Accuracy: 0.6087, MCC: 0.2936, F1: 0.6897

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.07758 | val 1.52112
  Epoch 013 - train 0.01683 | val 2.38442
  Classification -> best τ=0.420 (val F1=0.2944)
  Directional -> Accuracy: 0.3971, MCC: -0.0526, F1: 0.5495

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.05847 | val 1.42356
  Epoch 011 - train 0.03531 | val 1.62117
  Classification -> best τ=0.500 (val F1=0.1795)
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.03303 | val 1.16202
  Epoch 011 - train 0.02141 | val 1.30083
  Classification -> best τ=0.515 (val F1=0.2166)
  Directional -> Accuracy: 0.6875, MCC: 0.3578, F1: 0.6154

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.06752 | val 1.54287
  Epoch 011 - train 0.04243 | val 1.82910
  Classification -> best τ=0.455 (val F1=0.2968)
  Directional -> Accuracy: 0.3623, MCC: -0.2582, F1: 0.5217

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.02965 | val 2.04385
  Epoch 011 - train 0.01642 | val 2.35317
  Classification -> best τ=0.540 (val F1=0.1738)
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.05749 | val 2.44055
  Epoch 011 - train 0.03541 | val 2.60165
  Classification -> best τ=0.515 (val F1=0.2083)
  Directional -> Accuracy: 0.5088, MCC: 0.0566, F1: 0.1765

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.06549 | val 2.04864
  Epoch 011 - train 0.04538 | val 2.73922
  Classification -> best τ=0.455 (val F1=0.2850)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.6230

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.07437 | val 1.71626
  Epoch 011 - train 0.04225 | val 1.50053
  Classification -> best τ=0.505 (val F1=0.2365)
  Directional -> Accuracy: 0.5333, MCC: 0.0668, F1: 0.5484

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.12384 | val 2.32998
  Epoch 011 - train 0.04841 | val 2.63870
  Classification -> best τ=0.495 (val F1=0.1091)
  Directional -> Accuracy: 0.5882, MCC: 0.1753, F1: 0.2222

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.13987 | val 1.67389
  Epoch 012 - train 0.10868 | val 1.91806
  Classification -> best τ=0.625 (val F1=0.2474)
  Directional -> Accuracy: 0.5217, MCC: 0.1839, F1: 0.2326

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.04542 | val 1.94273
  Epoch 011 - train 0.02950 | val 2.30411
  Classification -> best τ=0.595 (val F1=0.1291)
  Directional -> Accuracy: 0.3793, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.08461 | val 4.37821
  Epoch 011 - train 0.05027 | val 4.93306
  Classification -> best τ=0.480 (val F1=0.2004)
  Directional -> Accuracy: 0.4133, MCC: 0.0949, F1: 0.0435

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.12060 | val 1.71978
  Epoch 011 - train 0.07072 | val 1.85825
  Classification -> best τ=0.420 (val F1=0.2166)
  Directional -> Accuracy: 0.5781, MCC: 0.0760, F1: 0.6966

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.17280 | val 1.22114
  Epoch 013 - train 0.05257 | val 1.73884
  Classification -> best τ=0.475 (val F1=0.2515)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.06386 | val 1.22707
  Epoch 011 - train 0.04257 | val 1.45341
  Classification -> best τ=0.470 (val F1=0.1522)
  Directional -> Accuracy: 0.5957, MCC: 0.0121, F1: 0.7324

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.12747 | val 1.43894
  Epoch 011 - train 0.08149 | val 1.77631
  Classification -> best τ=0.460 (val F1=0.1157)
  Directional -> Accuracy: 0.5077, MCC: 0.0000, F1: 0.6735

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.10656 | val 1.74218
  Epoch 013 - train 0.02723 | val 2.03115
  Classification -> best τ=0.605 (val F1=0.3749)
  Directional -> Accuracy: 0.4912, MCC: 0.0465, F1: 0.3830

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.19983 | val 1.66666
  Epoch 012 - train 0.05778 | val 1.83727
  Classification -> best τ=0.430 (val F1=0.1974)
  Directional -> Accuracy: 0.4769, MCC: 0.0000, F1: 0.6458

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.07723 | val 1.05580
  Epoch 014 - train 0.00938 | val 1.47842
  Classification -> best τ=0.495 (val F1=0.3226)
  Directional -> Accuracy: 0.5091, MCC: 0.0133, F1: 0.5424

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.02809 | val 0.93537
  Epoch 011 - train 0.01890 | val 1.04108
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.5938

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.03452 | val 1.22763
  Epoch 011 - train 0.01643 | val 1.36806
  Classification -> best τ=0.520 (val F1=0.2240)
  Directional -> Accuracy: 0.5238, MCC: 0.0142, F1: 0.6000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.05821 | val 1.56220
  Epoch 011 - train 0.04209 | val 1.75324
  Classification -> best τ=0.480 (val F1=0.1089)
  Directional -> Accuracy: 0.4464, MCC: -0.0207, F1: 0.0606

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.03919 | val 1.15881
  Epoch 011 - train 0.02520 | val 1.32583
  Classification -> best τ=0.480 (val F1=0.3427)
  Directional -> Accuracy: 0.4500, MCC: -0.1005, F1: 0.4762

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.03161 | val 1.61198
  Epoch 011 - train 0.02180 | val 1.84742
  Classification -> best τ=0.550 (val F1=0.3501)
  Directional -> Accuracy: 0.5238, MCC: 0.0000, F1: 0.0000

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.07976 | val 1.14701
  Epoch 011 - train 0.05509 | val 1.29796
  Classification -> best τ=0.460 (val F1=0.2357)
  Directional -> Accuracy: 0.5476, MCC: 0.0751, F1: 0.6122

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.04953 | val 1.17616
  Epoch 011 - train 0.02677 | val 1.43687
  Classification -> best τ=0.570 (val F1=0.2969)
  Directional -> Accuracy: 0.4286, MCC: -0.1376, F1: 0.4167

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.11818 | val 1.11151
  Epoch 013 - train 0.03152 | val 1.61331
  Classification -> best τ=0.380 (val F1=0.3252)
  Directional -> Accuracy: 0.5556, MCC: 0.1402, F1: 0.5294

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.04229 | val 1.40400
  Epoch 011 - train 0.02906 | val 1.60022
  Classification -> best τ=0.480 (val F1=0.1874)
  Directional -> Accuracy: 0.5116, MCC: 0.1508, F1: 0.6667

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.14498 | val 1.38304
  Epoch 011 - train 0.09670 | val 1.56537
  Classification -> best τ=0.440 (val F1=0.2409)
  Directional -> Accuracy: 0.4697, MCC: -0.0805, F1: 0.5333

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.01891 | val 1.08447
  Epoch 011 - train 0.01020 | val 1.26033
  Classification -> best τ=0.515 (val F1=0.2618)
  Directional -> Accuracy: 0.5476, MCC: 0.1706, F1: 0.3448

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.06970 | val 3.40752
  Epoch 011 - train 0.04578 | val 3.66817
  Classification -> best τ=0.465 (val F1=0.1995)
  Directional -> Accuracy: 0.4821, MCC: -0.0283, F1: 0.4912

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.07202 | val 1.45890
  Epoch 011 - train 0.04973 | val 1.69176
  Classification -> best τ=0.555 (val F1=0.3859)
  Directional -> Accuracy: 0.3913, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.02834 | val 0.94348
  Epoch 011 - train 0.01696 | val 1.03870
  Classification -> best τ=0.500 (val F1=0.1900)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.11644 | val 1.78774
  Epoch 011 - train 0.07491 | val 2.16092
  Classification -> best τ=0.545 (val F1=0.1787)
  Directional -> Accuracy: 0.5135, MCC: 0.0347, F1: 0.5610

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.08284 | val 0.86167
  Epoch 014 - train 0.01275 | val 1.50133
  Classification -> best τ=0.555 (val F1=0.3500)
  Directional -> Accuracy: 0.5556, MCC: 0.1556, F1: 0.3750

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.05809 | val 0.73762
  Epoch 015 - train 0.00480 | val 1.10597
  Classification -> best τ=0.420 (val F1=0.3563)
  Directional -> Accuracy: 0.5714, MCC: 0.0323, F1: 0.7188

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.05607 | val 0.74519
  Epoch 012 - train 0.02262 | val 0.87888
  Classification -> best τ=0.505 (val F1=0.3705)
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.5455

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.06780 | val 1.62535
  Epoch 011 - train 0.03551 | val 2.01498
  Classification -> best τ=0.465 (val F1=0.1605)
  Directional -> Accuracy: 0.5455, MCC: 0.0000, F1: 0.7059

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.05037 | val 3.12141
  Epoch 011 - train 0.02210 | val 3.54241
  Classification -> best τ=0.625 (val F1=0.2696)
  Directional -> Accuracy: 0.5179, MCC: 0.1289, F1: 0.6582

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.06066 | val 1.57154
  Epoch 011 - train 0.03705 | val 1.78732
  Classification -> best τ=0.535 (val F1=0.1409)
  Directional -> Accuracy: 0.5660, MCC: 0.1373, F1: 0.5306

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.07970 | val 1.52609
  Epoch 012 - train 0.02626 | val 1.55559
  Classification -> best τ=0.615 (val F1=0.1210)
  Directional -> Accuracy: 0.4909, MCC: -0.0297, F1: 0.5484

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.09834 | val 0.98970

[I 2026-02-22 10:38:19,561] Trial 102 finished with value: 0.23671249112703183 and parameters: {'feature_set': 'all_nlp', 'model_type': 'BiLSTM', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 64, 'num_layers': 1, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.0, 'batch_size': 64, 'learning_rate': 0.0042904255664175245, 'weight_decay': 3.8076944540672608e-06, 'lr_patience': 7, 'lr_factor': 0.8, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 1.27075027697838, 'early_stopping_min_delta': 0.00848252384982375}. Best is trial 22 with value: 0.2833350641483003.

  Epoch 014 - train 0.01340 | val 1.77741
  Classification -> best τ=0.440 (val F1=0.1825)
  Directional -> Accuracy: 0.4667, MCC: -0.0620, F1: 0.5000

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.23671249112703183
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 30
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d', 'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down', 'finbert_neutral']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.40589 | val 1.23150
  Epoch 011 - train 0.33409 | val 1.28241
  Classification -> best τ=0.580 (val F1=0.2989)
  Directional -> Accuracy: 0.5600, MCC: 0.0875, F1: 0.1081

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 106). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.31696 | val 0.79285
  Epoch 011 - train 0.28891 | val 0.81387
  Classification -> best τ=0.435 (val F1=0.0621)
  Directional -> Accuracy: 0.5909, MCC: 0.0000, F1: 0.7429

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 106). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.32053 | val 1.27991
  Epoch 011 - train 0.28653 | val 1.38207
  Classification -> best τ=0.510 (val F1=0.3780)
  Directional -> Accuracy: 0.4667, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.40063 | val 1.57656
  Epoch 011 - train 0.36652 | val 2.04711
  Classification -> best τ=0.365 (val F1=0.2279)
  Directional -> Accuracy: 0.5068, MCC: 0.0166, F1: 0.5135

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.34848 | val 0.74434
  Epoch 014 - train 0.20899 | val 1.13766
  Classification -> best τ=0.465 (val F1=0.4014)
  Directional -> Accuracy: 0.5918, MCC: 0.2189, F1: 0.4737

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.30942 | val 0.91735
  Epoch 011 - train 0.28195 | val 0.92751
  Classification -> best τ=0.475 (val F1=0.3788)
  Directional -> Accuracy: 0.5333, MCC: 0.0632, F1: 0.4000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.37035 | val 1.30907
  Epoch 011 - train 0.32179 | val 1.55017
  Classification -> best τ=0.505 (val F1=0.2040)
  Directional -> Accuracy: 0.4776, MCC: 0.0443, F1: 0.5333

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 106). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 106). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.29674 | val 0.76804
  Epoch 011 - train 0.27428 | val 0.94951
  Classification -> best τ=0.510 (val F1=0.1741)
  Directional -> Accuracy: 0.4878, MCC: -0.0337, F1: 0.4324

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.30706 | val 0.76524
  Epoch 011 - train 0.29026 | val 0.99134
  Classification -> best τ=0.555 (val F1=0.2895)
  Directional -> Accuracy: 0.6383, MCC: 0.2648, F1: 0.4516

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 106). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 106). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 106). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.33667 | val 1.26879
  Epoch 011 - train 0.31114 | val 1.07364
  Classification -> best τ=0.385 (val F1=0.1846)
  Directional -> Accuracy: 0.4265, MCC: 0.0000, F1: 0.5979

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.34297 | val 1.17522
  Epoch 011 - train 0.27486 | val 0.92471
  Classification -> best τ=0.515 (val F1=0.3550)
  Directional -> Accuracy: 0.5833, MCC: 0.2267, F1: 0.1667

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.36113 | val 1.32770
  Epoch 011 - train 0.29758 | val 1.46850
  Classification -> best τ=0.610 (val F1=0.0271)
  Directional -> Accuracy: 0.5714, MCC: 0.2566, F1: 0.3333

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 106). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.32958 | val 2.36119
  Epoch 011 - train 0.30760 | val 2.87492
  Classification -> best τ=0.410 (val F1=0.2788)
  Directional -> Accuracy: 0.5102, MCC: 0.1414, F1: 0.6667

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 106). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.35893 | val 0.79956
  Epoch 014 - train 0.23136 | val 1.09512
  Classification -> best τ=0.450 (val F1=0.4093)
  Directional -> Accuracy: 0.4746, MCC: -0.1336, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.33602 | val 0.96647
  Epoch 011 - train 0.30733 | val 1.11713
  Classification -> best τ=0.565 (val F1=0.2060)
  Directional -> Accuracy: 0.5600, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.42346 | val 1.22781
  Epoch 011 - train 0.35231 | val 1.36285
  Classification -> best τ=0.475 (val F1=0.2661)
  Directional -> Accuracy: 0.5735, MCC: 0.1491, F1: 0.5797

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 106). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.35881 | val 1.13421
  Epoch 011 - train 0.34041 | val 1.28902
  Classification -> best τ=0.620 (val F1=0.2335)
  Directional -> Accuracy: 0.3860, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.36647 | val 1.60473
  Epoch 011 - train 0.32020 | val 1.95171
  Classification -> best τ=0.525 (val F1=0.1895)
  Directional -> Accuracy: 0.3919, MCC: -0.1314, F1: 0.2373

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.37967 | val 0.75616
  Epoch 015 - train 0.22389 | val 1.13348
  Classification -> best τ=0.655 (val F1=0.3318)
  Directional -> Accuracy: 0.4127, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 106). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.40105 | val 0.73015
  Epoch 012 - train 0.33672 | val 0.85338
  Classification -> best τ=0.475 (val F1=0.2467)
  Directional -> Accuracy: 0.4521, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.32280 | val 1.39667
  Epoch 011 - train 0.27919 | val 1.39040
  Classification -> best τ=0.490 (val F1=0.2326)
  Directional -> Accuracy: 0.4565, MCC: 0.2118, F1: 0.1935

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 106). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 106). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 106). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.33748 | val 0.86862
  Epoch 011 - train 0.30778 | val 1.18885
  Classification -> best τ=0.480 (val F1=0.1887)
  Directional -> Accuracy: 0.5312, MCC: 0.1072, F1: 0.2105

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.35911 | val 0.98787
  Epoch 011 - train 0.37434 | val 0.92444
  Classification -> best τ=0.500 (val F1=0.4082)
  Directional -> Accuracy: 0.6607, MCC: 0.3616, F1: 0.7711

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.34235 | val 1.37203
  Epoch 011 - train 0.32357 | val 1.20105
  Classification -> best τ=0.490 (val F1=0.1994)
  Directional -> Accuracy: 0.5312, MCC: 0.0808, F1: 0.5714

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.33798 | val 0.83320
  Epoch 015 - train 0.20180 | val 1.45014
  Classification -> best τ=0.490 (val F1=0.3953)
  Directional -> Accuracy: 0.5185, MCC: 0.1163, F1: 0.3158

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.28653 | val 0.79120
  Epoch 011 - train 0.26117 | val 0.82554
  Classification -> best τ=0.585 (val F1=0.1852)
  Directional -> Accuracy: 0.4884, MCC: -0.0511, F1: 0.3889

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.36044 | val 0.94346
  Epoch 011 - train 0.33588 | val 1.14551
  Classification -> best τ=0.530 (val F1=0.1845)
  Directional -> Accuracy: 0.6327, MCC: 0.2074, F1: 0.7568

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.36014 | val 1.11037
  Epoch 011 - train 0.36036 | val 1.12334
  Classification -> best τ=0.470 (val F1=0.2309)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.31617 | val 0.81405
  Epoch 011 - train 0.29591 | val 0.91126
  Classification -> best τ=0.485 (val F1=0.2041)
  Directional -> Accuracy: 0.5789, MCC: 0.1827, F1: 0.7241

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.33363 | val 0.88604
  Epoch 011 - train 0.29856 | val 0.85286
  Classification -> best τ=0.540 (val F1=0.1782)
  Directional -> Accuracy: 0.4634, MCC: -0.0767, F1: 0.4211

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.36577 | val 0.98162
  Epoch 012 - train 0.30485 | val 1.16876
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5610, MCC: 0.0000, F1: 0.7188

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.33182 | val 1.21829
  Epoch 011 - train 0.28956 | val 1.24061
  Classification -> best τ=0.500 (val F1=0.2843)
  Directional -> Accuracy: 0.5208, MCC: 0.0000, F1: 0.6849

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.41013 | val 1.24225
  Epoch 012 - train 0.27642 | val 2.22430
  Classification -> best τ=0.465 (val F1=0.3238)
  Directional -> Accuracy: 0.4930, MCC: 0.0561, F1: 0.3793

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 106). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.31176 | val 1.33418
  Epoch 011 - train 0.28217 | val 1.30258
  Classification -> best τ=0.480 (val F1=0.1844)
  Directional -> Accuracy: 0.5238, MCC: 0.2132, F1: 0.6667

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for PCG (101 < 106). Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.39543 | val 1.55504
  Epoch 011 - train 0.37269 | val 1.72476
  Classification -> best τ=0.415 (val F1=0.3234)
  Directional -> Accuracy: 0.6769, MCC: 0.3442, F1: 0.7123

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.26486 | val 0.66178
  Epoch 016 - train 0.11411 | val 1.18315
  Classification -> best τ=0.495 (val F1=0.4384)
  Directional -> Accuracy: 0.6250, MCC: 0.2657, F1: 0.5946

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.28815 | val 1.33020
  Epoch 011 - train 0.28854 | val 1.79262
  Classification -> best τ=0.425 (val F1=0.2040)
  Directional -> Accuracy: 0.4909, MCC: 0.1773, F1: 0.6410

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.33738 | val 1.18049
  Epoch 011 - train 0.31225 | val 1.27514
  Classification -> best τ=0.500 (val F1=0.2913)
  Directional -> Accuracy: 0.4444, MCC: 0.0815, F1: 0.2857

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 106). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 106). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 106). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 106). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.34876 | val 0.61057
  Epoch 020 - train 0.11641 | val 0.82016
  Classification -> best τ=0.410 (val F1=0.5795)
  Directional -> Accuracy: 0.3261, MCC: 0.0000, F1: 0.4918

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 106). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 106). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 106). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.36949 | val 1.90799
  Epoch 011 - train 0.32431 | val 2.21816
  Classification -> best τ=0.430 (val F1=0.2729)
  Directional -> Accuracy: 0.4932, MCC: 0.0000, F1: 0.6606

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 106). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 106). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 106). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 106). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.30312 | val 0.81115
  Epoch 011 - train 0.25943 | val 0.85156
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.33334 | val 0.74277
  Epoch 011 - train 0.30534 | val 0.74598
  Classification -> best τ=0.535 (val F1=0.0639)
  Directional -> Accuracy: 0.5366, MCC: 0.0535, F1: 0.5957

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.33616 | val 0.72276
  Epoch 016 - train 0.16062 | val 1.14419
  Classification -> best τ=0.640 (val F1=0.2231)
  Directional -> Accuracy: 0.5217, MCC: 0.3244, F1: 0.6071

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.36019 | val 1.32287
  Epoch 011 - train 0.32805 | val 1.59495
  Classification -> best τ=0.455 (val F1=0.2495)
  Directional -> Accuracy: 0.5741, MCC: 0.3000, F1: 0.4103

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.31273 | val 1.16032
  Epoch 011 - train 0.26845 | val 1.22326
  Classification -> best τ=0.515 (val F1=0.3483)
  Directional -> Accuracy: 0.5091, MCC: 0.0575, F1: 0.6494

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.34361 | val 1.13432
  Epoch 012 - train 0.28994 | val 1.34886
  Classification -> best τ=0.575 (val F1=0.1646)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.38033 | val 1.31600
  Epoch 011 - train 0.35161 | val 1.27525
  Classification -> best τ=0.510 (val F1=0.3324)
  Directional -> Accuracy: 0.4074, MCC: -0.1981, F1: 0.2000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.41156 | val 0.90914

[I 2026-02-22 10:39:16,352] Trial 103 finished with value: 0.25515673873058237 and parameters: {'feature_set': 'sector_finbert', 'model_type': 'BiGRU', 'sequence_length': 30, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 64, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.0, 'batch_size': 64, 'learning_rate': 0.002374930200477183, 'weight_decay': 5.931856732249301e-06, 'lr_patience': 7, 'lr_factor': 0.8, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 1.1927293104895775, 'early_stopping_min_delta': 0.008196186771935707}. Best is trial 22 with value: 0.2833350641483003.

  Epoch 016 - train 0.22781 | val 1.09592
  Classification -> best τ=0.580 (val F1=0.4133)
  Directional -> Accuracy: 0.5254, MCC: 0.0484, F1: 0.5000

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.25515673873058237
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d', 'positive_emotion', 'negative_emotion', 'uncertainty_emotion', 'positive_emotion_pct', 'negative_emotion_pct', 'uncertainty_emotion_pct']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.41315 | val 0.77946
  Epoch 013 - train 0.40426 | val 1.03739
  Classification -> best τ=0.540 (val F1=0.2919)
  Directional -> Accuracy: 0.5921, MCC: 0.1649, F1: 0.5079

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.12242 | val 1.53351
  Epoch 011 - train 0.10605 | val 1.66871
  Classification -> best τ=0.570 (val F1=0.2523)
  Directional -> Accuracy: 0.4889, MCC: 0.0165, F1: 0.4651

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.13336 | val 4.07245
  Epoch 011 - train 0.09652 | val 5.36577
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5217, MCC: 0.0000, F1: 0.6857

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.36846 | val 2.38470
  Epoch 012 - train 0.29385 | val 2.67656
  Classification -> best τ=0.465 (val F1=0.1895)
  Directional -> Accuracy: 0.4730, MCC: 0.1079, F1: 0.0488

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.16737 | val 1.62302
  Epoch 012 - train 0.05805 | val 2.18298
  Classification -> best τ=0.440 (val F1=0.5298)
  Directional -> Accuracy: 0.6600, MCC: 0.3516, F1: 0.6047

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.10004 | val 1.08961
  Epoch 011 - train 0.07360 | val 1.19668
  Classification -> best τ=0.625 (val F1=0.1537)
  Directional -> Accuracy: 0.5217, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.35498 | val 1.69254
  Epoch 012 - train 0.23566 | val 2.46605
  Classification -> best τ=0.420 (val F1=0.3336)
  Directional -> Accuracy: 0.5588, MCC: 0.2172, F1: 0.5946

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.14409 | val 0.63739
  Epoch 017 - train 0.01384 | val 1.06113
  Classification -> best τ=0.175 (val F1=0.3524)
  Directional -> Accuracy: 0.5000, MCC: 0.0430, F1: 0.5333

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.13675 | val 2.34330
  Epoch 012 - train 0.07450 | val 2.80852
  Classification -> best τ=0.430 (val F1=0.2243)
  Directional -> Accuracy: 0.5417, MCC: 0.2085, F1: 0.6333

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.24925 | val 2.29880
  Epoch 011 - train 0.18762 | val 2.16079
  Classification -> best τ=0.285 (val F1=0.2877)
  Directional -> Accuracy: 0.4783, MCC: 0.0808, F1: 0.5814

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.14926 | val 1.23710
  Epoch 011 - train 0.08758 | val 1.60056
  Classification -> best τ=0.520 (val F1=0.2521)
  Directional -> Accuracy: 0.5714, MCC: 0.1376, F1: 0.5333

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.18500 | val 3.01788
  Epoch 011 - train 0.16107 | val 2.79697
  Classification -> best τ=0.480 (val F1=0.1313)
  Directional -> Accuracy: 0.5965, MCC: 0.1923, F1: 0.6230

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.18836 | val 3.00733
  Epoch 011 - train 0.12835 | val 3.44115
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.6230

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.25421 | val 1.20244
  Epoch 012 - train 0.12737 | val 1.20542
  Classification -> best τ=0.395 (val F1=0.4244)
  Directional -> Accuracy: 0.5833, MCC: 0.1675, F1: 0.5614

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.13494 | val 1.35341
  Epoch 012 - train 0.08902 | val 1.47508
  Classification -> best τ=0.580 (val F1=0.2078)
  Directional -> Accuracy: 0.5490, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.35402 | val 1.57758
  Epoch 012 - train 0.18475 | val 2.95734
  Classification -> best τ=0.650 (val F1=0.3307)
  Directional -> Accuracy: 0.5507, MCC: 0.1234, F1: 0.5079

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.22390 | val 2.33642
  Epoch 011 - train 0.20727 | val 2.63101
  Classification -> best τ=0.375 (val F1=0.1336)
  Directional -> Accuracy: 0.5690, MCC: 0.0252, F1: 0.6835

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.25667 | val 1.27183
  Epoch 011 - train 0.20178 | val 1.67091
  Classification -> best τ=0.525 (val F1=0.1548)
  Directional -> Accuracy: 0.4000, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.19873 | val 2.43384
  Epoch 011 - train 0.16547 | val 2.76183
  Classification -> best τ=0.365 (val F1=0.2843)
  Directional -> Accuracy: 0.5469, MCC: 0.1825, F1: 0.4727

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.30223 | val 1.20318
  Epoch 011 - train 0.30696 | val 1.28471
  Classification -> best τ=0.550 (val F1=0.2565)
  Directional -> Accuracy: 0.4595, MCC: 0.1050, F1: 0.0476

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.17528 | val 2.33322
  Epoch 011 - train 0.12787 | val 2.72724
  Classification -> best τ=0.555 (val F1=0.1978)
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.25946 | val 1.65124
  Epoch 011 - train 0.20271 | val 2.15962
  Classification -> best τ=0.490 (val F1=0.2766)
  Directional -> Accuracy: 0.4923, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.17410 | val 1.09468
  Epoch 013 - train 0.07294 | val 1.43265
  Classification -> best τ=0.815 (val F1=0.3550)
  Directional -> Accuracy: 0.5088, MCC: 0.1095, F1: 0.3636

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.25567 | val 1.33792
  Epoch 012 - train 0.15912 | val 1.22022
  Classification -> best τ=0.450 (val F1=0.1874)
  Directional -> Accuracy: 0.5538, MCC: 0.1071, F1: 0.5397

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.18292 | val 1.82256
  Epoch 012 - train 0.08253 | val 2.15817
  Classification -> best τ=0.485 (val F1=0.3563)
  Directional -> Accuracy: 0.5091, MCC: 0.0671, F1: 0.4000

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.07663 | val 1.89199
  Epoch 011 - train 0.04726 | val 1.93019
  Classification -> best τ=0.520 (val F1=0.2035)
  Directional -> Accuracy: 0.4889, MCC: 0.2285, F1: 0.6230

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.16798 | val 2.16125
  Epoch 011 - train 0.10413 | val 2.63124
  Classification -> best τ=0.555 (val F1=0.1578)
  Directional -> Accuracy: 0.5238, MCC: 0.0849, F1: 0.5000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.22893 | val 1.14362
  Epoch 012 - train 0.11114 | val 1.59373
  Classification -> best τ=0.365 (val F1=0.1860)
  Directional -> Accuracy: 0.4821, MCC: 0.0114, F1: 0.3830

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.14345 | val 4.72906
  Epoch 011 - train 0.11085 | val 4.95920
  Classification -> best τ=0.335 (val F1=0.3518)
  Directional -> Accuracy: 0.5750, MCC: 0.1140, F1: 0.7018

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.16174 | val 1.94809
  Epoch 011 - train 0.16068 | val 2.23206
  Classification -> best τ=0.560 (val F1=0.4110)
  Directional -> Accuracy: 0.4286, MCC: -0.1809, F1: 0.2500

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.11642 | val 1.29235
  Epoch 011 - train 0.03808 | val 1.67274
  Classification -> best τ=0.445 (val F1=0.2328)
  Directional -> Accuracy: 0.5476, MCC: 0.0000, F1: 0.7077

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.18895 | val 1.80304
  Epoch 012 - train 0.09592 | val 2.15020
  Classification -> best τ=0.430 (val F1=0.3541)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.30082 | val 1.59616
  Epoch 011 - train 0.23421 | val 1.82754
  Classification -> best τ=0.370 (val F1=0.2431)
  Directional -> Accuracy: 0.4444, MCC: 0.0000, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.12595 | val 1.45113
  Epoch 011 - train 0.07453 | val 1.47794
  Classification -> best τ=0.445 (val F1=0.3742)
  Directional -> Accuracy: 0.5116, MCC: 0.0094, F1: 0.2222

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.39584 | val 1.08348
  Epoch 011 - train 0.35773 | val 1.01051
  Classification -> best τ=0.480 (val F1=0.2899)
  Directional -> Accuracy: 0.4545, MCC: 0.1517, F1: 0.1000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.04695 | val 2.26325
  Epoch 011 - train 0.02690 | val 2.53423
  Classification -> best τ=0.415 (val F1=0.2464)
  Directional -> Accuracy: 0.6667, MCC: 0.3371, F1: 0.7200

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.23271 | val 1.83959
  Epoch 011 - train 0.21049 | val 2.39600
  Classification -> best τ=0.400 (val F1=0.2450)
  Directional -> Accuracy: 0.5357, MCC: 0.0716, F1: 0.5185

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.09878 | val 2.66779
  Epoch 011 - train 0.09009 | val 3.29684
  Classification -> best τ=0.625 (val F1=0.2659)
  Directional -> Accuracy: 0.4565, MCC: 0.0318, F1: 0.3590

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.12684 | val 0.87307
  Epoch 014 - train 0.01500 | val 1.33274
  Classification -> best τ=0.405 (val F1=0.4556)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.25455 | val 2.71422
  Epoch 011 - train 0.19211 | val 3.04072
  Classification -> best τ=0.405 (val F1=0.2704)
  Directional -> Accuracy: 0.5135, MCC: 0.0176, F1: 0.3793

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.18840 | val 1.26184
  Epoch 012 - train 0.07362 | val 2.38144
  Classification -> best τ=0.415 (val F1=0.3287)
  Directional -> Accuracy: 0.6222, MCC: 0.2515, F1: 0.6792

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.12764 | val 1.69323
  Epoch 012 - train 0.04298 | val 2.01159
  Classification -> best τ=0.680 (val F1=0.2500)
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.0000

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.10374 | val 1.41447
  Epoch 015 - train 0.01176 | val 1.60205
  Classification -> best τ=0.610 (val F1=0.1270)
  Directional -> Accuracy: 0.6250, MCC: 0.4024, F1: 0.6538

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.14986 | val 1.78631
  Epoch 011 - train 0.08729 | val 2.37647
  Classification -> best τ=0.655 (val F1=0.2036)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.17129 | val 3.07563
  Epoch 012 - train 0.06274 | val 3.11783
  Classification -> best τ=0.550 (val F1=0.3585)
  Directional -> Accuracy: 0.5536, MCC: 0.1284, F1: 0.6154

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.15842 | val 2.05791
  Epoch 012 - train 0.07751 | val 2.31044
  Classification -> best τ=0.360 (val F1=0.2351)
  Directional -> Accuracy: 0.5094, MCC: 0.0000, F1: 0.6750

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.19761 | val 2.66359
  Epoch 011 - train 0.13439 | val 1.41827
  Classification -> best τ=0.525 (val F1=0.2833)
  Directional -> Accuracy: 0.4727, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.24851 | val 1.08302

[I 2026-02-22 10:39:52,170] Trial 104 finished with value: 0.26299199017670744 and parameters: {'feature_set': 'sector_unified_emotion', 'model_type': 'GRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 64, 'num_layers': 1, 'inter_rnn_drop': 0.4, 'dropout': 0.0, 'batch_size': 32, 'learning_rate': 0.006821175699881373, 'weight_decay': 1.8939261636159057e-05, 'lr_patience': 5, 'lr_factor': 0.8, 'early_stopping_patience': 10, 'max_epochs': 50, 'huber_delta': 1.3296858018370046, 'early_stopping_min_delta': 0.00973073044994688}. Best is trial 22 with value: 0.2833350641483003.

  Epoch 018 - train 0.02137 | val 1.06908
  Classification -> best τ=0.605 (val F1=0.3862)
  Directional -> Accuracy: 0.5667, MCC: 0.1541, F1: 0.3158

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.26299199017670744
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: classification
Sequence length: 6
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d', 'sentiment']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.39417 | val 1.25760
  Epoch 017 - train 0.23894 | val 1.80174
  Classification -> best τ=0.565 (val F1=0.2346)
  Directional -> Accuracy: 0.6076, MCC: 0.1849, F1: 0.4561

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 82). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.26011 | val 1.16984
  Epoch 016 - train 0.10390 | val 2.10635
  Classification -> best τ=0.580 (val F1=0.1654)
  Directional -> Accuracy: 0.5208, MCC: 0.2063, F1: 0.3030

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 82). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.30522 | val 2.61812
  Epoch 016 - train 0.18228 | val 3.84770
  Classification -> best τ=0.455 (val F1=0.2271)
  Directional -> Accuracy: 0.4898, MCC: -0.1311, F1: 0.6479

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.38614 | val 1.26046
  Epoch 016 - train 0.24925 | val 1.26691
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5455, MCC: 0.0000, F1: 0.7059

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.32040 | val 0.94771
  Epoch 020 - train 0.06947 | val 2.20240
  Classification -> best τ=0.540 (val F1=0.4064)
  Directional -> Accuracy: 0.6792, MCC: 0.3791, F1: 0.6531

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.29671 | val 1.70762
  Epoch 016 - train 0.16511 | val 3.24503
  Classification -> best τ=0.545 (val F1=0.2521)
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.35600 | val 2.30999
  Epoch 016 - train 0.17855 | val 3.41829
  Classification -> best τ=0.490 (val F1=0.2732)
  Directional -> Accuracy: 0.5634, MCC: 0.0725, F1: 0.4151

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 82). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 82). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.27015 | val 1.07366
  Epoch 016 - train 0.13280 | val 1.92456
  Classification -> best τ=0.520 (val F1=0.0231)
  Directional -> Accuracy: 0.4043, MCC: -0.1679, F1: 0.3913

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.33044 | val 1.84981
  Epoch 016 - train 0.16204 | val 1.37375
  Classification -> best τ=0.540 (val F1=0.3890)
  Directional -> Accuracy: 0.4884, MCC: 0.2590, F1: 0.6071

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 82). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 82). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.33738 | val 1.21920
  Epoch 016 - train 0.20213 | val 1.61405
  Classification -> best τ=0.505 (val F1=0.0948)
  Directional -> Accuracy: 0.5139, MCC: -0.0032, F1: 0.4068

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.28940 | val 1.05381
  Epoch 016 - train 0.14809 | val 1.67085
  Classification -> best τ=0.590 (val F1=0.1701)
  Directional -> Accuracy: 0.6154, MCC: 0.2694, F1: 0.3333

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.35928 | val 1.61441
  Epoch 016 - train 0.18549 | val 2.69359
  Classification -> best τ=0.485 (val F1=0.1529)
  Directional -> Accuracy: 0.6667, MCC: 0.3769, F1: 0.7297

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.29044 | val 1.44456
  Epoch 016 - train 0.12488 | val 2.73021
  Classification -> best τ=0.515 (val F1=0.1231)
  Directional -> Accuracy: 0.5333, MCC: 0.0000, F1: 0.0000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 82). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.37304 | val 1.33866
  Epoch 018 - train 0.14841 | val 2.66684
  Classification -> best τ=0.520 (val F1=0.3929)
  Directional -> Accuracy: 0.5079, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.31697 | val 3.23407
  Epoch 016 - train 0.19663 | val 7.26712
  Classification -> best τ=0.530 (val F1=0.2306)
  Directional -> Accuracy: 0.6111, MCC: 0.2224, F1: 0.6038

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.33469 | val 1.23618
  Epoch 016 - train 0.21723 | val 1.58048
  Classification -> best τ=0.505 (val F1=0.2697)
  Directional -> Accuracy: 0.5556, MCC: 0.0971, F1: 0.6098

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.34128 | val 2.28539
  Epoch 016 - train 0.17727 | val 2.78655
  Classification -> best τ=0.535 (val F1=0.1559)
  Directional -> Accuracy: 0.3934, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.35760 | val 1.56860
  Epoch 016 - train 0.19876 | val 2.00157
  Classification -> best τ=0.495 (val F1=0.1900)
  Directional -> Accuracy: 0.3974, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.34541 | val 0.84479
  Epoch 019 - train 0.18649 | val 1.17038
  Classification -> best τ=0.530 (val F1=0.2901)
  Directional -> Accuracy: 0.4627, MCC: 0.0915, F1: 0.2174

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 82). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.35539 | val 1.40466
  Epoch 018 - train 0.14922 | val 1.62101
  Classification -> best τ=0.540 (val F1=0.3456)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.21719 | val 1.05570
  Epoch 016 - train 0.09218 | val 1.36279
  Classification -> best τ=0.495 (val F1=0.0829)
  Directional -> Accuracy: 0.5600, MCC: 0.1042, F1: 0.6207

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 82). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 82). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 82). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.34705 | val 1.00739
  Epoch 016 - train 0.19095 | val 1.41222
  Classification -> best τ=0.480 (val F1=0.1222)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.31192 | val 3.36347
  Epoch 016 - train 0.16528 | val 5.20610
  Classification -> best τ=0.535 (val F1=0.2335)
  Directional -> Accuracy: 0.5333, MCC: 0.1757, F1: 0.4400

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.29982 | val 1.32911
  Epoch 016 - train 0.14725 | val 2.02612
  Classification -> best τ=0.480 (val F1=0.2740)
  Directional -> Accuracy: 0.5000, MCC: -0.0009, F1: 0.4848

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.28679 | val 1.07027
  Epoch 018 - train 0.12009 | val 1.61692
  Classification -> best τ=0.495 (val F1=0.5264)
  Directional -> Accuracy: 0.6034, MCC: 0.2598, F1: 0.5490

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.28648 | val 1.20101
  Epoch 016 - train 0.17487 | val 2.46262
  Classification -> best τ=0.490 (val F1=0.3021)
  Directional -> Accuracy: 0.5306, MCC: 0.1978, F1: 0.6230

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.25908 | val 0.94149
  Epoch 016 - train 0.14523 | val 1.08546
  Classification -> best τ=0.465 (val F1=0.2004)
  Directional -> Accuracy: 0.4667, MCC: -0.0367, F1: 0.4783

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.36432 | val 1.00047
  Epoch 016 - train 0.19470 | val 1.83030
  Classification -> best τ=0.455 (val F1=0.2076)
  Directional -> Accuracy: 0.4576, MCC: 0.0500, F1: 0.1111

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.25841 | val 0.86272
  Epoch 016 - train 0.14488 | val 1.71710
  Classification -> best τ=0.525 (val F1=0.1066)
  Directional -> Accuracy: 0.5682, MCC: 0.1329, F1: 0.5957

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.26849 | val 1.17478
  Epoch 016 - train 0.15088 | val 1.67851
  Classification -> best τ=0.510 (val F1=0.0684)
  Directional -> Accuracy: 0.5652, MCC: 0.1325, F1: 0.6000

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.33576 | val 1.19711
  Epoch 016 - train 0.17832 | val 2.53609
  Classification -> best τ=0.475 (val F1=0.0673)
  Directional -> Accuracy: 0.5435, MCC: 0.0000, F1: 0.7042

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.24519 | val 1.64032
  Epoch 018 - train 0.07379 | val 1.83959
  Classification -> best τ=0.425 (val F1=0.2981)
  Directional -> Accuracy: 0.5192, MCC: 0.0000, F1: 0.6835

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.32369 | val 1.22430
  Epoch 017 - train 0.16319 | val 1.97991
  Classification -> best τ=0.480 (val F1=0.2843)
  Directional -> Accuracy: 0.5200, MCC: 0.2193, F1: 0.2800

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 82). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.26796 | val 0.91915
  Epoch 016 - train 0.13202 | val 2.50652
  Classification -> best τ=0.545 (val F1=0.3427)
  Directional -> Accuracy: 0.4390, MCC: -0.1280, F1: 0.3784

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.30057 | val 2.22803
  Epoch 016 - train 0.11407 | val 3.98025
  Classification -> best τ=0.590 (val F1=0.1627)
  Directional -> Accuracy: 0.5652, MCC: 0.1627, F1: 0.0909

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.36878 | val 0.88108
  Epoch 016 - train 0.21074 | val 1.16517
  Classification -> best τ=0.435 (val F1=0.2959)
  Directional -> Accuracy: 0.5217, MCC: 0.2426, F1: 0.3265

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.24274 | val 0.86768
  Epoch 020 - train 0.04422 | val 1.71324
  Classification -> best τ=0.615 (val F1=0.3188)
  Directional -> Accuracy: 0.4889, MCC: 0.0000, F1: 0.0000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.30730 | val 1.84968
  Epoch 016 - train 0.14598 | val 2.64046
  Classification -> best τ=0.570 (val F1=0.1531)
  Directional -> Accuracy: 0.5254, MCC: 0.0000, F1: 0.0000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.26328 | val 1.29189
  Epoch 017 - train 0.11412 | val 1.39281
  Classification -> best τ=0.505 (val F1=0.2991)
  Directional -> Accuracy: 0.6122, MCC: 0.0000, F1: 0.7595

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 82). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 82). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 82). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 82). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.26620 | val 0.99764
  Epoch 016 - train 0.14305 | val 1.50618
  Classification -> best τ=0.520 (val F1=0.2959)
  Directional -> Accuracy: 0.5714, MCC: -0.0857, F1: 0.1818

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 82). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.32478 | val 1.32662
  Epoch 016 - train 0.18279 | val 3.10121
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5122, MCC: 0.0000, F1: 0.6774

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 82). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 82). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.30917 | val 2.70320
  Epoch 016 - train 0.18247 | val 4.17181
  Classification -> best τ=0.445 (val F1=0.2123)
  Directional -> Accuracy: 0.5065, MCC: 0.0000, F1: 0.6724

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 82). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 82). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.31477 | val 2.11716
  Epoch 016 - train 0.18119 | val 4.46171
  Classification -> best τ=0.490 (val F1=0.1024)
  Directional -> Accuracy: 0.4694, MCC: -0.0904, F1: 0.6286

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.26753 | val 1.46314
  Epoch 016 - train 0.13759 | val 2.82847
  Classification -> best τ=0.480 (val F1=0.1754)
  Directional -> Accuracy: 0.6809, MCC: 0.4009, F1: 0.7826

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.29812 | val 0.96367
  Epoch 016 - train 0.13105 | val 1.79944
  Classification -> best τ=0.505 (val F1=0.0551)
  Directional -> Accuracy: 0.3571, MCC: 0.0000, F1: 0.5263

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.29552 | val 1.17603
  Epoch 016 - train 0.14101 | val 1.72765
  Classification -> best τ=0.535 (val F1=0.1962)
  Directional -> Accuracy: 0.4483, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.25578 | val 1.70429
  Epoch 016 - train 0.14870 | val 2.84970
  Classification -> best τ=0.530 (val F1=0.3743)
  Directional -> Accuracy: 0.5254, MCC: 0.0923, F1: 0.6500

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.33996 | val 1.34689
  Epoch 016 - train 0.18731 | val 2.28567
  Classification -> best τ=0.445 (val F1=0.0207)
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.31584 | val 2.48055
  Epoch 016 - train 0.12155 | val 2.93403
  Classification -> best τ=0.630 (val F1=0.1522)
  Directional -> Accuracy: 0.5345, MCC: 0.0778, F1: 0.4906

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.42792 | val 0.99478

[I 2026-02-22 10:40:34,877] Trial 105 finished with value: 0.21142950242411115 and parameters: {'feature_set': 'sector_sentiment', 'model_type': 'BiLSTM', 'sequence_length': 6, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 64, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.1, 'batch_size': 32, 'learning_rate': 0.0017231892001938363, 'weight_decay': 8.290018870699076e-06, 'lr_patience': 7, 'lr_factor': 0.8, 'early_stopping_patience': 15, 'max_epochs': 30, 'huber_delta': 1.8877947378633413, 'early_stopping_min_delta': 0.007509506803191496}. Best is trial 22 with value: 0.2833350641483003.

  Epoch 016 - train 0.24827 | val 1.32895
  Classification -> best τ=0.530 (val F1=0.2543)
  Directional -> Accuracy: 0.5397, MCC: 0.0674, F1: 0.2162

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.21142950242411115
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: classification
Sequence length: 12
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.47222 | val 1.43067
  Epoch 011 - train 0.44569 | val 2.14229
  Classification -> best τ=0.660 (val F1=0.2463)
  Directional -> Accuracy: 0.5769, MCC: 0.1219, F1: 0.4211

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 88). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.26290 | val 1.53686
  Epoch 011 - train 0.42069 | val 1.84640
  Classification -> best τ=0.535 (val F1=0.2346)
  Directional -> Accuracy: 0.4681, MCC: 0.0596, F1: 0.1379

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 88). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.35333 | val 3.25912
  Epoch 011 - train 0.44223 | val 3.44855
  Classification -> best τ=0.685 (val F1=0.1940)
  Directional -> Accuracy: 0.4583, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.40624 | val 2.14892
  Epoch 011 - train 0.39945 | val 1.23598
  Classification -> best τ=0.550 (val F1=0.1923)
  Directional -> Accuracy: 0.4605, MCC: -0.0130, F1: 0.0465

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.29948 | val 1.35334
  Epoch 011 - train 0.24446 | val 1.51251
  Classification -> best τ=0.540 (val F1=0.3867)
  Directional -> Accuracy: 0.6154, MCC: 0.2829, F1: 0.5455

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.22550 | val 3.76780
  Epoch 011 - train 0.23783 | val 2.17525
  Classification -> best τ=0.665 (val F1=0.3475)
  Directional -> Accuracy: 0.4898, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.37570 | val 1.37956
  Epoch 011 - train 0.31773 | val 1.91743
  Classification -> best τ=0.500 (val F1=0.1267)
  Directional -> Accuracy: 0.4571, MCC: -0.0362, F1: 0.4722

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 88). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 88). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.13075 | val 1.41874
  Epoch 011 - train 0.09050 | val 1.84489
  Classification -> best τ=0.550 (val F1=0.2255)
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.5938

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.32507 | val 0.76257
  Epoch 017 - train 0.12459 | val 1.25984
  Classification -> best τ=0.535 (val F1=0.5701)
  Directional -> Accuracy: 0.4048, MCC: 0.1225, F1: 0.5614

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 88). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 88). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.40644 | val 1.56879
  Epoch 011 - train 0.31544 | val 3.06404
  Classification -> best τ=0.310 (val F1=0.1407)
  Directional -> Accuracy: 0.4648, MCC: 0.1499, F1: 0.6200

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.35948 | val 1.01374
  Epoch 013 - train 0.47097 | val 0.85994
  Classification -> best τ=0.625 (val F1=0.3244)
  Directional -> Accuracy: 0.5686, MCC: 0.1633, F1: 0.2143

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.55077 | val 1.17722
  Epoch 011 - train 0.53014 | val 0.97357
  Classification -> best τ=0.435 (val F1=0.1748)
  Directional -> Accuracy: 0.5593, MCC: 0.1635, F1: 0.6829

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.23145 | val 1.61970
  Epoch 011 - train 0.14632 | val 2.62699
  Classification -> best τ=0.585 (val F1=0.1210)
  Directional -> Accuracy: 0.4773, MCC: -0.0415, F1: 0.4651

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 88). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.46510 | val 0.76256
  Epoch 013 - train 0.24406 | val 1.56605
  Classification -> best τ=0.130 (val F1=0.4402)
  Directional -> Accuracy: 0.5323, MCC: 0.0690, F1: 0.4314

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.48228 | val 1.61036
  Epoch 011 - train 0.40916 | val 1.16540
  Classification -> best τ=0.570 (val F1=0.2286)
  Directional -> Accuracy: 0.4906, MCC: -0.0073, F1: 0.5263

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.50741 | val 1.54603
  Epoch 011 - train 0.43863 | val 1.52483
  Classification -> best τ=0.415 (val F1=0.2527)
  Directional -> Accuracy: 0.5634, MCC: 0.1397, F1: 0.7048

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.39679 | val 1.48242
  Epoch 011 - train 0.41928 | val 1.73301
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.6167, MCC: 0.0000, F1: 0.7629

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.42755 | val 1.90172
  Epoch 011 - train 0.34299 | val 2.33770
  Classification -> best τ=0.500 (val F1=0.1936)
  Directional -> Accuracy: 0.3896, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.38836 | val 2.93951
  Epoch 011 - train 0.33456 | val 4.53893
  Classification -> best τ=0.390 (val F1=0.2409)
  Directional -> Accuracy: 0.5758, MCC: 0.1656, F1: 0.6000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 88). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.45451 | val 1.37191
  Epoch 011 - train 0.34981 | val 1.86887
  Classification -> best τ=0.500 (val F1=0.2211)
  Directional -> Accuracy: 0.4211, MCC: -0.1375, F1: 0.2903

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.38131 | val 1.43282
  Epoch 011 - train 0.27936 | val 1.49225
  Classification -> best τ=0.590 (val F1=0.1940)
  Directional -> Accuracy: 0.5306, MCC: 0.2008, F1: 0.4889

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 88). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 88). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 88). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.25827 | val 2.88912
  Epoch 011 - train 0.22540 | val 2.20641
  Classification -> best τ=0.445 (val F1=0.1719)
  Directional -> Accuracy: 0.4925, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.38246 | val 1.51523
  Epoch 011 - train 0.39507 | val 1.73124
  Classification -> best τ=0.720 (val F1=0.2992)
  Directional -> Accuracy: 0.5254, MCC: 0.1776, F1: 0.3913

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.34392 | val 1.18221
  Epoch 011 - train 0.40286 | val 1.19565
  Classification -> best τ=0.550 (val F1=0.2432)
  Directional -> Accuracy: 0.3582, MCC: -0.2803, F1: 0.3944

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.38333 | val 1.16977
  Epoch 012 - train 0.29068 | val 1.67935
  Classification -> best τ=0.625 (val F1=0.5336)
  Directional -> Accuracy: 0.4211, MCC: -0.1512, F1: 0.0000

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.29166 | val 2.55102
  Epoch 011 - train 0.18185 | val 2.52729
  Classification -> best τ=0.530 (val F1=0.1588)
  Directional -> Accuracy: 0.4583, MCC: -0.1952, F1: 0.1875

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.28898 | val 1.23568
  Epoch 011 - train 0.26557 | val 1.14856
  Classification -> best τ=0.545 (val F1=0.1902)
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.0000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.35425 | val 1.08429
  Epoch 011 - train 0.32598 | val 1.10689
  Classification -> best τ=0.510 (val F1=0.1485)
  Directional -> Accuracy: 0.4655, MCC: -0.0929, F1: 0.5373

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.18031 | val 1.25312
  Epoch 016 - train 0.01917 | val 1.15689
  Classification -> best τ=0.735 (val F1=0.3948)
  Directional -> Accuracy: 0.5116, MCC: 0.0864, F1: 0.3226

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.22057 | val 1.16105
  Epoch 012 - train 0.18138 | val 1.17538
  Classification -> best τ=0.410 (val F1=0.2169)
  Directional -> Accuracy: 0.5333, MCC: 0.0632, F1: 0.6182

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.23307 | val 2.98806
  Epoch 011 - train 0.24077 | val 2.99084
  Classification -> best τ=0.465 (val F1=0.1581)
  Directional -> Accuracy: 0.5333, MCC: 0.0357, F1: 0.6441

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.31346 | val 1.33774
  Epoch 013 - train 0.24284 | val 1.25552
  Classification -> best τ=0.740 (val F1=0.2889)
  Directional -> Accuracy: 0.4314, MCC: -0.1334, F1: 0.1714

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.40838 | val 1.11438
  Epoch 011 - train 0.39168 | val 1.58997
  Classification -> best τ=0.520 (val F1=0.2739)
  Directional -> Accuracy: 0.4324, MCC: 0.0000, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 88). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.16093 | val 1.42941
  Epoch 011 - train 0.18094 | val 2.18317
  Classification -> best τ=0.485 (val F1=0.2145)
  Directional -> Accuracy: 0.5385, MCC: 0.1140, F1: 0.6400

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.26331 | val 2.59277
  Epoch 011 - train 0.17170 | val 2.00499
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4667, MCC: 0.0000, F1: 0.6364

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.45509 | val 2.33774
  Epoch 011 - train 0.38802 | val 1.93740
  Classification -> best τ=0.490 (val F1=0.2347)
  Directional -> Accuracy: 0.4265, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.19155 | val 1.37760
  Epoch 012 - train 0.10053 | val 1.51840
  Classification -> best τ=0.430 (val F1=0.2001)
  Directional -> Accuracy: 0.6364, MCC: 0.3254, F1: 0.7143

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.38870 | val 1.66901
  Epoch 011 - train 0.38423 | val 1.64775
  Classification -> best τ=0.510 (val F1=0.2001)
  Directional -> Accuracy: 0.5345, MCC: 0.0668, F1: 0.5091

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.26730 | val 2.54182
  Epoch 011 - train 0.23614 | val 3.54786
  Classification -> best τ=0.575 (val F1=0.4038)
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 88). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 88). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 88). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 88). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.29704 | val 1.00369
  Epoch 011 - train 0.31869 | val 0.98367
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.3500, MCC: 0.0000, F1: 0.5185

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 88). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.12208 | val 1.94011
  Epoch 011 - train 0.06110 | val 2.00255
  Classification -> best τ=0.475 (val F1=0.0510)
  Directional -> Accuracy: 0.6667, MCC: 0.3325, F1: 0.6829

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 88). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 88). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.37702 | val 3.61734
  Epoch 011 - train 0.35676 | val 3.24286
  Classification -> best τ=0.125 (val F1=0.3270)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 88). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 88). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 88). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.20817 | val 1.20345
  Epoch 014 - train 0.18592 | val 1.01709
  Classification -> best τ=0.595 (val F1=0.3649)
  Directional -> Accuracy: 0.5625, MCC: 0.2582, F1: 0.6957

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.08804 | val 0.91736
  Epoch 015 - train 0.00965 | val 1.38258
  Classification -> best τ=0.760 (val F1=0.5669)
  Directional -> Accuracy: 0.5111, MCC: 0.0632, F1: 0.4500

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.30422 | val 1.03632
  Epoch 011 - train 0.25544 | val 1.32714
  Classification -> best τ=0.515 (val F1=0.0325)
  Directional -> Accuracy: 0.3659, MCC: 0.0000, F1: 0.5357

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.47925 | val 2.07406
  Epoch 011 - train 0.30844 | val 2.20300
  Classification -> best τ=0.525 (val F1=0.2458)
  Directional -> Accuracy: 0.4561, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.38008 | val 2.15544
  Epoch 011 - train 0.24806 | val 2.38755
  Classification -> best τ=0.605 (val F1=0.4216)
  Directional -> Accuracy: 0.4828, MCC: 0.0000, F1: 0.6512

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.39144 | val 1.06936
  Epoch 012 - train 0.37149 | val 1.46523
  Classification -> best τ=0.590 (val F1=0.1449)
  Directional -> Accuracy: 0.5455, MCC: 0.1631, F1: 0.3590

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.28416 | val 1.78991
  Epoch 012 - train 0.29998 | val 3.18620
  Classification -> best τ=0.420 (val F1=0.1963)
  Directional -> Accuracy: 0.5439, MCC: 0.1941, F1: 0.6905

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...

[I 2026-02-22 10:41:08,135] Trial 106 finished with value: 0.23835907352651162 and parameters: {'feature_set': 'sector', 'model_type': 'LSTM', 'sequence_length': 12, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 64, 'num_layers': 1, 'inter_rnn_drop': 0.4, 'dropout': 0.0, 'batch_size': 16, 'learning_rate': 0.005217568451736953, 'weight_decay': 2.936244193855846e-06, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 50, 'huber_delta': 1.6044319410372923, 'early_stopping_min_delta': 0.007144121133444973}. Best is trial 22 with value: 0.2833350641483003.

  Epoch 010 - train 0.42785 | val 0.82119
  Epoch 011 - train 0.39007 | val 0.83332
  Classification -> best τ=0.465 (val F1=0.1801)
  Directional -> Accuracy: 0.5323, MCC: 0.0668, F1: 0.5397

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.23835907352651162
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d', 'emotion_anger', 'emotion_disgust', 'emotion_fear', 'emotion_joy', 'emotion_neutral', 'emotion_sadness', 'emotion_surprize', 'emotion_anger_pct', 'emotion_disgust_pct', 'emotion_fear_pct', 'emotion_joy_pct', 'emotion_neutral_pct', 'emotion_sadness_pct', 'emotion_surprize_pct']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.41218 | val 1.65541
  Epoch 012 - train 0.39661 | val 1.44321
  Classification -> best τ=0.505 (val F1=0.2082)
  Directional -> Accuracy: 0.5658, MCC: 0.0795, F1: 0.1951

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.32760 | val 1.17808
  Epoch 012 - train 0.23905 | val 1.94427
  Classification -> best τ=0.365 (val F1=0.2025)
  Directional -> Accuracy: 0.6222, MCC: 0.2523, F1: 0.7536

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.32637 | val 3.41259
  Epoch 011 - train 0.25312 | val 3.85005
  Classification -> best τ=0.705 (val F1=0.1854)
  Directional -> Accuracy: 0.4783, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.45832 | val 1.14091
  Epoch 012 - train 0.45395 | val 1.01924
  Classification -> best τ=0.580 (val F1=0.2403)
  Directional -> Accuracy: 0.5405, MCC: 0.0393, F1: 0.6600

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.31790 | val 1.21512
  Epoch 014 - train 0.13762 | val 1.67021
  Classification -> best τ=0.590 (val F1=0.2934)
  Directional -> Accuracy: 0.6400, MCC: 0.3524, F1: 0.5263

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.34951 | val 0.85886
  Epoch 015 - train 0.19704 | val 1.15403
  Classification -> best τ=0.530 (val F1=0.4453)
  Directional -> Accuracy: 0.5000, MCC: -0.0210, F1: 0.3429

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.45633 | val 2.45326
  Epoch 012 - train 0.35554 | val 2.32630
  Classification -> best τ=0.390 (val F1=0.1703)
  Directional -> Accuracy: 0.3971, MCC: -0.0654, F1: 0.5393

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.26113 | val 1.06800
  Epoch 011 - train 0.33195 | val 0.85717
  Classification -> best τ=0.395 (val F1=0.3632)
  Directional -> Accuracy: 0.5238, MCC: -0.1171, F1: 0.0909

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.36004 | val 2.56593
  Epoch 015 - train 0.20172 | val 1.88418
  Classification -> best τ=0.400 (val F1=0.3652)
  Directional -> Accuracy: 0.4583, MCC: 0.0542, F1: 0.6061

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.35981 | val 1.42126
  Epoch 012 - train 0.30728 | val 2.49676
  Classification -> best τ=0.460 (val F1=0.1667)
  Directional -> Accuracy: 0.5072, MCC: -0.0112, F1: 0.4138

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.30285 | val 1.58838
  Epoch 011 - train 0.28336 | val 1.63334
  Classification -> best τ=0.440 (val F1=0.2397)
  Directional -> Accuracy: 0.5510, MCC: 0.0649, F1: 0.3889

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.41623 | val 2.36228
  Epoch 012 - train 0.30324 | val 3.52178
  Classification -> best τ=0.275 (val F1=0.1512)
  Directional -> Accuracy: 0.4737, MCC: -0.1874, F1: 0.6429

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.25896 | val 6.25884
  Epoch 011 - train 0.20479 | val 6.96289
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.6230

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.34502 | val 0.74490
  Epoch 013 - train 0.22623 | val 0.95792
  Classification -> best τ=0.580 (val F1=0.3642)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.30786 | val 1.12585
  Epoch 011 - train 0.32755 | val 1.29727
  Classification -> best τ=0.485 (val F1=0.1613)
  Directional -> Accuracy: 0.5490, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.34272 | val 1.67109
  Epoch 012 - train 0.50891 | val 1.16457
  Classification -> best τ=0.735 (val F1=0.2474)
  Directional -> Accuracy: 0.4928, MCC: 0.1607, F1: 0.1026

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.33026 | val 1.56693
  Epoch 011 - train 0.33665 | val 2.30716
  Classification -> best τ=0.650 (val F1=0.1842)
  Directional -> Accuracy: 0.3793, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.44906 | val 0.99227
  Epoch 012 - train 0.38597 | val 1.21889
  Classification -> best τ=0.360 (val F1=0.2182)
  Directional -> Accuracy: 0.6000, MCC: 0.0000, F1: 0.7500

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.34328 | val 1.38435
  Epoch 011 - train 0.36948 | val 2.05698
  Classification -> best τ=0.540 (val F1=0.2467)
  Directional -> Accuracy: 0.5312, MCC: 0.1954, F1: 0.4000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.47958 | val 0.98188
  Epoch 013 - train 0.45396 | val 1.16442
  Classification -> best τ=0.525 (val F1=0.2989)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.26186 | val 2.05844
  Epoch 011 - train 0.25160 | val 2.25986
  Classification -> best τ=0.620 (val F1=0.1854)
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.37352 | val 1.39354
  Epoch 011 - train 0.29775 | val 1.46418
  Classification -> best τ=0.540 (val F1=0.1350)
  Directional -> Accuracy: 0.4923, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.34584 | val 0.72326
  Epoch 016 - train 0.17678 | val 1.69297
  Classification -> best τ=0.480 (val F1=0.4715)
  Directional -> Accuracy: 0.5263, MCC: 0.0596, F1: 0.5424

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.38374 | val 1.11475
  Epoch 012 - train 0.40351 | val 0.97705
  Classification -> best τ=0.385 (val F1=0.1122)
  Directional -> Accuracy: 0.4615, MCC: -0.0836, F1: 0.6237

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.34189 | val 1.07157
  Epoch 013 - train 0.30205 | val 1.36336
  Classification -> best τ=0.360 (val F1=0.4688)
  Directional -> Accuracy: 0.5818, MCC: 0.1913, F1: 0.5490

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.21355 | val 1.95393
  Epoch 011 - train 0.13574 | val 1.65719
  Classification -> best τ=0.465 (val F1=0.2318)
  Directional -> Accuracy: 0.4444, MCC: 0.0159, F1: 0.5763

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.36942 | val 1.50903
  Epoch 012 - train 0.29074 | val 1.28617
  Classification -> best τ=0.490 (val F1=0.1936)
  Directional -> Accuracy: 0.4524, MCC: 0.0212, F1: 0.2069

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.36637 | val 1.46665
  Epoch 012 - train 0.28284 | val 2.07778
  Classification -> best τ=0.340 (val F1=0.2999)
  Directional -> Accuracy: 0.4821, MCC: 0.1096, F1: 0.1714

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.23111 | val 3.22240
  Epoch 012 - train 0.29907 | val 3.87710
  Classification -> best τ=0.560 (val F1=0.2957)
  Directional -> Accuracy: 0.6250, MCC: 0.2307, F1: 0.7059

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.26713 | val 2.62421
  Epoch 012 - train 0.13193 | val 3.68417
  Classification -> best τ=0.590 (val F1=0.2271)
  Directional -> Accuracy: 0.5238, MCC: 0.0155, F1: 0.1667

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.36124 | val 1.87675
  Epoch 011 - train 0.38755 | val 1.46491
  Classification -> best τ=0.550 (val F1=0.2697)
  Directional -> Accuracy: 0.3333, MCC: -0.3455, F1: 0.3913

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.36047 | val 1.83412
  Epoch 011 - train 0.27995 | val 1.85715
  Classification -> best τ=0.525 (val F1=0.3179)
  Directional -> Accuracy: 0.5102, MCC: -0.0696, F1: 0.6667

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.47700 | val 0.86535
  Epoch 011 - train 0.38156 | val 0.84764
  Classification -> best τ=0.510 (val F1=0.3347)
  Directional -> Accuracy: 0.4306, MCC: -0.1327, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.32279 | val 1.57889
  Epoch 011 - train 0.29978 | val 1.51295
  Classification -> best τ=0.470 (val F1=0.2804)
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.41834 | val 1.37111
  Epoch 012 - train 0.36836 | val 1.87625
  Classification -> best τ=0.320 (val F1=0.3280)
  Directional -> Accuracy: 0.5758, MCC: 0.0648, F1: 0.7021

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.27471 | val 3.21102
  Epoch 013 - train 0.21289 | val 3.74444
  Classification -> best τ=0.505 (val F1=0.2858)
  Directional -> Accuracy: 0.6429, MCC: 0.2821, F1: 0.6809

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.35450 | val 1.46243
  Epoch 011 - train 0.33000 | val 1.92366
  Classification -> best τ=0.525 (val F1=0.3172)
  Directional -> Accuracy: 0.5714, MCC: 0.1309, F1: 0.5000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.35438 | val 2.19008
  Epoch 011 - train 0.17893 | val 2.39796
  Classification -> best τ=0.520 (val F1=0.4603)
  Directional -> Accuracy: 0.5652, MCC: -0.0894, F1: 0.7143

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.33152 | val 1.02119
  Epoch 011 - train 0.25341 | val 1.19353
  Classification -> best τ=0.510 (val F1=0.2533)
  Directional -> Accuracy: 0.5417, MCC: -0.0294, F1: 0.3125

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.34900 | val 2.18976
  Epoch 011 - train 0.37991 | val 2.14234
  Classification -> best τ=0.385 (val F1=0.4056)
  Directional -> Accuracy: 0.4595, MCC: -0.0836, F1: 0.4286

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.35065 | val 1.03306
  Epoch 014 - train 0.21285 | val 2.34385
  Classification -> best τ=0.470 (val F1=0.2562)
  Directional -> Accuracy: 0.4444, MCC: -0.1202, F1: 0.5098

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.21429 | val 1.17767
  Epoch 017 - train 0.04765 | val 2.49157
  Classification -> best τ=0.795 (val F1=0.3612)
  Directional -> Accuracy: 0.4048, MCC: -0.1334, F1: 0.0741

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.16661 | val 1.75311
  Epoch 011 - train 0.14205 | val 2.77811
  Classification -> best τ=0.520 (val F1=0.4216)
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.5455

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.45049 | val 1.17523
  Epoch 012 - train 0.39804 | val 1.18514
  Classification -> best τ=0.665 (val F1=0.2085)
  Directional -> Accuracy: 0.4727, MCC: 0.1242, F1: 0.0645

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.31664 | val 2.56053
  Epoch 011 - train 0.29509 | val 4.48628
  Classification -> best τ=0.450 (val F1=0.2939)
  Directional -> Accuracy: 0.4643, MCC: -0.0620, F1: 0.5588

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.31833 | val 1.25387
  Epoch 012 - train 0.21755 | val 1.59840
  Classification -> best τ=0.495 (val F1=0.1236)
  Directional -> Accuracy: 0.5472, MCC: 0.1134, F1: 0.6667

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.34437 | val 1.49055
  Epoch 012 - train 0.21946 | val 1.72639
  Classification -> best τ=0.500 (val F1=0.3143)
  Directional -> Accuracy: 0.3636, MCC: -0.2934, F1: 0.1463

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.42483 | val 0.72816

[I 2026-02-22 10:42:53,174] Trial 107 finished with value: 0.26827971815479534 and parameters: {'feature_set': 'sector_emotion', 'model_type': 'BiGRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.1, 'batch_size': 32, 'learning_rate': 0.008922427506173558, 'weight_decay': 4.450075969070634e-06, 'lr_patience': 5, 'lr_factor': 0.8, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 1.244616400424918, 'early_stopping_min_delta': 0.00679671015528293}. Best is trial 22 with value: 0.2833350641483003.

  Epoch 014 - train 0.24852 | val 0.94614
  Classification -> best τ=0.520 (val F1=0.2719)
  Directional -> Accuracy: 0.6333, MCC: 0.2650, F1: 0.5926

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.26827971815479534
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d', 'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down', 'finbert_neutral']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.55022 | val 0.84521
  Epoch 014 - train 0.51904 | val 0.84618
  Classification -> best τ=0.430 (val F1=0.2919)
  Directional -> Accuracy: 0.5789, MCC: 0.1439, F1: 0.5152

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.43014 | val 0.83311
  Epoch 012 - train 0.41361 | val 0.86072
  Classification -> best τ=0.455 (val F1=0.1273)
  Directional -> Accuracy: 0.6222, MCC: 0.2204, F1: 0.6792

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.49838 | val 1.21814
  Epoch 011 - train 0.46044 | val 1.34448
  Classification -> best τ=0.545 (val F1=0.3114)
  Directional -> Accuracy: 0.4565, MCC: -0.0996, F1: 0.0741

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.55554 | val 0.82589
  Epoch 012 - train 0.47891 | val 0.92266
  Classification -> best τ=0.430 (val F1=0.0882)
  Directional -> Accuracy: 0.4459, MCC: -0.0839, F1: 0.3492

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.42351 | val 0.80470
  Epoch 017 - train 0.35419 | val 1.18439
  Classification -> best τ=0.625 (val F1=0.4556)
  Directional -> Accuracy: 0.6000, MCC: 0.2425, F1: 0.5000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.49528 | val 0.74684
  Epoch 015 - train 0.36416 | val 0.85981
  Classification -> best τ=0.450 (val F1=0.2030)
  Directional -> Accuracy: 0.4783, MCC: -0.0543, F1: 0.4000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.47395 | val 2.28469
  Epoch 012 - train 0.40648 | val 2.15945
  Classification -> best τ=0.425 (val F1=0.2242)
  Directional -> Accuracy: 0.5000, MCC: 0.1418, F1: 0.5750

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.42479 | val 0.61642
  Epoch 019 - train 0.16870 | val 0.82781
  Classification -> best τ=0.505 (val F1=0.3632)
  Directional -> Accuracy: 0.4762, MCC: -0.0142, F1: 0.5000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.50954 | val 0.86002
  Epoch 012 - train 0.44539 | val 0.92381
  Classification -> best τ=0.465 (val F1=0.2285)
  Directional -> Accuracy: 0.5625, MCC: 0.0380, F1: 0.1600

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.48133 | val 0.74993
  Epoch 012 - train 0.42837 | val 0.79780
  Classification -> best τ=0.505 (val F1=0.2178)
  Directional -> Accuracy: 0.4928, MCC: 0.0112, F1: 0.4928

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.47824 | val 1.42396
  Epoch 012 - train 0.45821 | val 1.58106
  Classification -> best τ=0.500 (val F1=0.2030)
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.54810 | val 1.27916
  Epoch 012 - train 0.46236 | val 1.38687
  Classification -> best τ=0.510 (val F1=0.0571)
  Directional -> Accuracy: 0.5789, MCC: 0.1629, F1: 0.6471

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.46155 | val 1.42108
  Epoch 013 - train 0.37023 | val 1.19458
  Classification -> best τ=0.540 (val F1=0.0875)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.6230

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.50720 | val 0.92654
  Epoch 011 - train 0.53537 | val 0.98704
  Classification -> best τ=0.430 (val F1=0.3026)
  Directional -> Accuracy: 0.5667, MCC: 0.1455, F1: 0.6389

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.47017 | val 1.20435
  Epoch 013 - train 0.39260 | val 1.39821
  Classification -> best τ=0.455 (val F1=0.2971)
  Directional -> Accuracy: 0.4314, MCC: -0.0987, F1: 0.5797

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.49682 | val 1.47370
  Epoch 013 - train 0.44949 | val 1.67851
  Classification -> best τ=0.520 (val F1=0.2997)
  Directional -> Accuracy: 0.5652, MCC: 0.1258, F1: 0.5946

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.52323 | val 0.98340
  Epoch 013 - train 0.43753 | val 1.37876
  Classification -> best τ=0.675 (val F1=0.2285)
  Directional -> Accuracy: 0.4310, MCC: 0.1826, F1: 0.1538

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.48829 | val 1.54128
  Epoch 012 - train 0.44796 | val 1.72388
  Classification -> best τ=0.620 (val F1=0.0164)
  Directional -> Accuracy: 0.4000, MCC: -0.2432, F1: 0.4944

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.52825 | val 0.95981
  Epoch 011 - train 0.50927 | val 1.08053
  Classification -> best τ=0.500 (val F1=0.3484)
  Directional -> Accuracy: 0.5312, MCC: -0.0123, F1: 0.6429

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.54274 | val 0.87710
  Epoch 012 - train 0.45719 | val 0.87190
  Classification -> best τ=0.500 (val F1=0.3301)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.52329 | val 1.02792
  Epoch 013 - train 0.45105 | val 1.22863
  Classification -> best τ=0.445 (val F1=0.2784)
  Directional -> Accuracy: 0.6170, MCC: 0.0000, F1: 0.7632

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.58973 | val 1.17518
  Epoch 013 - train 0.39667 | val 1.09590
  Classification -> best τ=0.495 (val F1=0.3503)
  Directional -> Accuracy: 0.4769, MCC: -0.1269, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.53613 | val 0.84713
  Epoch 017 - train 0.35169 | val 1.41476
  Classification -> best τ=0.885 (val F1=0.3833)
  Directional -> Accuracy: 0.4912, MCC: 0.0465, F1: 0.3830

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.54724 | val 0.74590
  Epoch 012 - train 0.44440 | val 0.71138
  Classification -> best τ=0.435 (val F1=0.1348)
  Directional -> Accuracy: 0.5538, MCC: 0.1134, F1: 0.5672

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.42136 | val 1.09217
  Epoch 015 - train 0.34399 | val 1.46109
  Classification -> best τ=0.465 (val F1=0.3823)
  Directional -> Accuracy: 0.6000, MCC: 0.2476, F1: 0.5417

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.37840 | val 0.78983
  Epoch 011 - train 0.40096 | val 0.73628
  Classification -> best τ=0.500 (val F1=0.3464)
  Directional -> Accuracy: 0.5111, MCC: 0.0885, F1: 0.5600

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.52527 | val 0.71639
  Epoch 017 - train 0.42743 | val 0.77137
  Classification -> best τ=0.620 (val F1=0.1353)
  Directional -> Accuracy: 0.5952, MCC: 0.2970, F1: 0.5143

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.45955 | val 0.95033
  Epoch 011 - train 0.44186 | val 0.98535
  Classification -> best τ=0.495 (val F1=0.3689)
  Directional -> Accuracy: 0.4464, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.46631 | val 1.33262
  Epoch 013 - train 0.46144 | val 0.96740
  Classification -> best τ=0.475 (val F1=0.2403)
  Directional -> Accuracy: 0.5500, MCC: 0.0231, F1: 0.7000

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.58228 | val 0.65599
  Epoch 020 - train 0.28531 | val 1.79528
  Classification -> best τ=0.665 (val F1=0.4846)
  Directional -> Accuracy: 0.4286, MCC: -0.1455, F1: 0.4000

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.45472 | val 1.14132
  Epoch 014 - train 0.44620 | val 1.43349
  Classification -> best τ=0.390 (val F1=0.2357)
  Directional -> Accuracy: 0.5714, MCC: 0.1083, F1: 0.6786

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.45798 | val 1.08271
  Epoch 011 - train 0.45705 | val 1.19201
  Classification -> best τ=0.475 (val F1=0.2498)
  Directional -> Accuracy: 0.5510, MCC: 0.0944, F1: 0.5926

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.52567 | val 0.74205
  Epoch 016 - train 0.29795 | val 1.47966
  Classification -> best τ=0.400 (val F1=0.3553)
  Directional -> Accuracy: 0.4167, MCC: -0.1465, F1: 0.3824

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.44100 | val 1.22472
  Epoch 013 - train 0.34270 | val 1.54059
  Classification -> best τ=0.540 (val F1=0.3243)
  Directional -> Accuracy: 0.5814, MCC: 0.1993, F1: 0.3571

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.55875 | val 1.06015
  Epoch 012 - train 0.50180 | val 1.43577
  Classification -> best τ=0.475 (val F1=0.1898)
  Directional -> Accuracy: 0.5606, MCC: 0.0799, F1: 0.6420

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.42307 | val 1.10623
  Epoch 015 - train 0.31570 | val 1.43145
  Classification -> best τ=0.490 (val F1=0.3287)
  Directional -> Accuracy: 0.7381, MCC: 0.4949, F1: 0.7179

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.45198 | val 1.07289
  Epoch 013 - train 0.36811 | val 1.50986
  Classification -> best τ=0.515 (val F1=0.2541)
  Directional -> Accuracy: 0.4821, MCC: -0.0333, F1: 0.4727

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.41513 | val 0.77204
  Epoch 015 - train 0.30574 | val 1.19103
  Classification -> best τ=0.270 (val F1=0.2118)
  Directional -> Accuracy: 0.6087, MCC: 0.0000, F1: 0.7568

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.50261 | val 0.80699
  Epoch 011 - train 0.51168 | val 0.79956
  Classification -> best τ=0.625 (val F1=0.3378)
  Directional -> Accuracy: 0.4375, MCC: 0.1482, F1: 0.5424

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.46611 | val 2.17514
  Epoch 011 - train 0.42157 | val 2.30948
  Classification -> best τ=0.420 (val F1=0.3785)
  Directional -> Accuracy: 0.4459, MCC: -0.1388, F1: 0.2545

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.55234 | val 0.84190
  Epoch 016 - train 0.42631 | val 0.76764
  Classification -> best τ=0.570 (val F1=0.3873)
  Directional -> Accuracy: 0.6000, MCC: 0.2119, F1: 0.5500

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.41452 | val 0.77745
  Epoch 013 - train 0.37641 | val 0.87834
  Classification -> best τ=0.315 (val F1=0.3015)
  Directional -> Accuracy: 0.6190, MCC: 0.2582, F1: 0.7500

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.47202 | val 0.64433
  Epoch 020 - train 0.30223 | val 0.92047
  Classification -> best τ=0.610 (val F1=0.4176)
  Directional -> Accuracy: 0.5000, MCC: 0.2928, F1: 0.6000

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.51464 | val 0.78932
  Epoch 012 - train 0.46925 | val 0.86843
  Classification -> best τ=0.535 (val F1=0.2224)
  Directional -> Accuracy: 0.5455, MCC: 0.0377, F1: 0.6753

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.42222 | val 1.53107
  Epoch 014 - train 0.28466 | val 1.48636
  Classification -> best τ=0.520 (val F1=0.4185)
  Directional -> Accuracy: 0.4643, MCC: -0.1303, F1: 0.1667

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.56568 | val 1.16064
  Epoch 015 - train 0.46503 | val 1.49963
  Classification -> best τ=0.430 (val F1=0.2317)
  Directional -> Accuracy: 0.6038, MCC: 0.2301, F1: 0.6866

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.51557 | val 1.05524
  Epoch 011 - train 0.47794 | val 1.00971
  Classification -> best τ=0.535 (val F1=0.1647)
  Directional -> Accuracy: 0.5273, MCC: 0.0000, F1: 0.6905

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.55055 | val 0.73099

[I 2026-02-22 10:44:14,813] Trial 108 finished with value: 0.27462075762741206 and parameters: {'feature_set': 'sector_finbert', 'model_type': 'BiGRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.2, 'batch_size': 64, 'learning_rate': 0.009008489582645943, 'weight_decay': 4.656826521161628e-06, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 1.238198004659935, 'early_stopping_min_delta': 3.0174672711148938e-05}. Best is trial 22 with value: 0.2833350641483003.

  Epoch 016 - train 0.42259 | val 0.74026
  Classification -> best τ=0.495 (val F1=0.3862)
  Directional -> Accuracy: 0.5833, MCC: 0.1668, F1: 0.5763

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.27462075762741206
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d', 'emotion_anger', 'emotion_disgust', 'emotion_fear', 'emotion_joy', 'emotion_neutral', 'emotion_sadness', 'emotion_surprize', 'emotion_anger_pct', 'emotion_disgust_pct', 'emotion_fear_pct', 'emotion_joy_pct', 'emotion_neutral_pct', 'emotion_sadness_pct', 'emotion_surprize_pct']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.50607 | val 0.72136
  Epoch 011 - train 0.45499 | val 0.74288
  Classification -> best τ=0.515 (val F1=0.1430)
  Directional -> Accuracy: 0.5263, MCC: 0.0474, F1: 0.4857

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.33993 | val 1.01093
  Epoch 013 - train 0.21744 | val 1.22765
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5778, MCC: 0.0000, F1: 0.7324

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.38205 | val 1.66899
  Epoch 013 - train 0.25919 | val 2.48442
  Classification -> best τ=0.535 (val F1=0.1978)
  Directional -> Accuracy: 0.4783, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.46146 | val 0.89518
  Epoch 013 - train 0.38607 | val 1.33529
  Classification -> best τ=0.420 (val F1=0.2463)
  Directional -> Accuracy: 0.4595, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.29547 | val 1.73226
  Epoch 013 - train 0.27316 | val 1.66487
  Classification -> best τ=0.495 (val F1=0.3612)
  Directional -> Accuracy: 0.6400, MCC: 0.3036, F1: 0.5909

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.37849 | val 1.25766
  Epoch 011 - train 0.37106 | val 0.83504
  Classification -> best τ=0.510 (val F1=0.2699)
  Directional -> Accuracy: 0.5217, MCC: 0.0349, F1: 0.4500

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.41969 | val 1.35744
  Epoch 014 - train 0.26569 | val 1.84247
  Classification -> best τ=0.510 (val F1=0.3209)
  Directional -> Accuracy: 0.5441, MCC: 0.0779, F1: 0.4746

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.29803 | val 0.89954
  Epoch 012 - train 0.27705 | val 0.90936
  Classification -> best τ=0.330 (val F1=0.3158)
  Directional -> Accuracy: 0.5000, MCC: 0.0280, F1: 0.5116

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.37988 | val 1.01821
  Epoch 012 - train 0.33841 | val 1.60914
  Classification -> best τ=0.465 (val F1=0.4119)
  Directional -> Accuracy: 0.5208, MCC: -0.1839, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.47033 | val 0.87935
  Epoch 012 - train 0.36743 | val 0.79230
  Classification -> best τ=0.510 (val F1=0.2293)
  Directional -> Accuracy: 0.3913, MCC: -0.1583, F1: 0.4878

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.42546 | val 1.54261
  Epoch 011 - train 0.31963 | val 1.62898
  Classification -> best τ=0.535 (val F1=0.2285)
  Directional -> Accuracy: 0.6122, MCC: 0.2010, F1: 0.4571

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.37862 | val 2.33434
  Epoch 012 - train 0.28415 | val 2.61300
  Classification -> best τ=0.560 (val F1=0.0424)
  Directional -> Accuracy: 0.4912, MCC: -0.0744, F1: 0.6506

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.35297 | val 2.41823
  Epoch 013 - train 0.25970 | val 3.02328
  Classification -> best τ=0.605 (val F1=0.1225)
  Directional -> Accuracy: 0.5238, MCC: -0.1419, F1: 0.0000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.43624 | val 0.99283
  Epoch 015 - train 0.26574 | val 1.28393
  Classification -> best τ=0.450 (val F1=0.3721)
  Directional -> Accuracy: 0.4500, MCC: -0.2294, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.35781 | val 1.26208
  Epoch 013 - train 0.26786 | val 1.29926
  Classification -> best τ=0.470 (val F1=0.0527)
  Directional -> Accuracy: 0.5098, MCC: 0.0921, F1: 0.6032

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.40202 | val 2.09167
  Epoch 012 - train 0.33065 | val 1.77730
  Classification -> best τ=0.540 (val F1=0.2907)
  Directional -> Accuracy: 0.5797, MCC: 0.1438, F1: 0.6506

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.39619 | val 1.37798
  Epoch 011 - train 0.35839 | val 1.35760
  Classification -> best τ=0.450 (val F1=0.2354)
  Directional -> Accuracy: 0.6034, MCC: 0.0131, F1: 0.7416

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.45477 | val 1.87495
  Epoch 012 - train 0.41986 | val 1.54994
  Classification -> best τ=0.610 (val F1=0.1909)
  Directional -> Accuracy: 0.4000, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.48622 | val 1.01768
  Epoch 012 - train 0.35605 | val 1.22552
  Classification -> best τ=0.425 (val F1=0.2843)
  Directional -> Accuracy: 0.5781, MCC: 0.0913, F1: 0.6824

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.51627 | val 0.95946
  Epoch 014 - train 0.33571 | val 0.94393
  Classification -> best τ=0.500 (val F1=0.1839)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.32187 | val 1.52989
  Epoch 011 - train 0.32902 | val 1.81923
  Classification -> best τ=0.550 (val F1=0.3114)
  Directional -> Accuracy: 0.4043, MCC: -0.0999, F1: 0.3333

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.52143 | val 1.05835
  Epoch 012 - train 0.37794 | val 1.17219
  Classification -> best τ=0.560 (val F1=0.2215)
  Directional -> Accuracy: 0.4923, MCC: -0.0081, F1: 0.2979

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.41993 | val 0.78271
  Epoch 016 - train 0.21896 | val 1.09882
  Classification -> best τ=0.490 (val F1=0.3938)
  Directional -> Accuracy: 0.6140, MCC: 0.2258, F1: 0.7381

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.41197 | val 1.09221
  Epoch 015 - train 0.30391 | val 1.15585
  Classification -> best τ=0.320 (val F1=0.1599)
  Directional -> Accuracy: 0.4769, MCC: 0.0000, F1: 0.6458

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.40608 | val 1.08283
  Epoch 014 - train 0.26769 | val 1.53640
  Classification -> best τ=0.495 (val F1=0.3860)
  Directional -> Accuracy: 0.5636, MCC: 0.2170, F1: 0.4286

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.26518 | val 1.05747
  Epoch 011 - train 0.20914 | val 1.09993
  Classification -> best τ=0.465 (val F1=0.1131)
  Directional -> Accuracy: 0.5333, MCC: 0.0503, F1: 0.4615

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.36132 | val 0.78366
  Epoch 014 - train 0.13759 | val 1.47048
  Classification -> best τ=0.625 (val F1=0.3350)
  Directional -> Accuracy: 0.4524, MCC: -0.0574, F1: 0.4103

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.47472 | val 1.28365
  Epoch 012 - train 0.34834 | val 1.32517
  Classification -> best τ=0.465 (val F1=0.2868)
  Directional -> Accuracy: 0.4464, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.36534 | val 0.98871
  Epoch 015 - train 0.22577 | val 1.55365
  Classification -> best τ=0.525 (val F1=0.3239)
  Directional -> Accuracy: 0.5000, MCC: -0.0985, F1: 0.6429

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.31016 | val 2.37371
  Epoch 012 - train 0.27875 | val 1.97984
  Classification -> best τ=0.550 (val F1=0.2801)
  Directional -> Accuracy: 0.5476, MCC: 0.1137, F1: 0.5957

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.37010 | val 1.87201
  Epoch 011 - train 0.36839 | val 1.76907
  Classification -> best τ=0.535 (val F1=0.0246)
  Directional -> Accuracy: 0.3810, MCC: -0.2202, F1: 0.2353

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.33947 | val 1.64910
  Epoch 013 - train 0.21856 | val 2.34857
  Classification -> best τ=0.325 (val F1=0.3833)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.47557 | val 1.02082
  Epoch 014 - train 0.31872 | val 0.84111
  Classification -> best τ=0.420 (val F1=0.2618)
  Directional -> Accuracy: 0.4444, MCC: -0.0395, F1: 0.1667

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.38389 | val 1.17005
  Epoch 011 - train 0.34915 | val 1.21905
  Classification -> best τ=0.515 (val F1=0.2078)
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.48707 | val 1.72900
  Epoch 011 - train 0.43376 | val 1.72100
  Classification -> best τ=0.530 (val F1=0.2618)
  Directional -> Accuracy: 0.5606, MCC: 0.1915, F1: 0.5085

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.32092 | val 2.11561
  Epoch 014 - train 0.19858 | val 2.67394
  Classification -> best τ=0.520 (val F1=0.3589)
  Directional -> Accuracy: 0.5476, MCC: 0.0953, F1: 0.5581

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.34399 | val 2.09955
  Epoch 012 - train 0.30317 | val 2.00684
  Classification -> best τ=0.380 (val F1=0.1718)
  Directional -> Accuracy: 0.4643, MCC: -0.0493, F1: 0.5312

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.30369 | val 0.93468
  Epoch 013 - train 0.19924 | val 1.11965
  Classification -> best τ=0.400 (val F1=0.3146)
  Directional -> Accuracy: 0.6087, MCC: 0.0475, F1: 0.7500

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.31187 | val 0.72218
  Epoch 018 - train 0.12468 | val 1.49800
  Classification -> best τ=0.645 (val F1=0.3887)
  Directional -> Accuracy: 0.3125, MCC: -0.2816, F1: 0.4762

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.42364 | val 1.45700
  Epoch 011 - train 0.38015 | val 1.50099
  Classification -> best τ=0.385 (val F1=0.2112)
  Directional -> Accuracy: 0.4595, MCC: -0.0765, F1: 0.5238

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.47796 | val 0.90243
  Epoch 013 - train 0.32207 | val 1.06141
  Classification -> best τ=0.490 (val F1=0.2712)
  Directional -> Accuracy: 0.4889, MCC: 0.0000, F1: 0.0000

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.20435 | val 0.79931
  Epoch 015 - train 0.10222 | val 1.17305
  Classification -> best τ=0.430 (val F1=0.3595)
  Directional -> Accuracy: 0.6190, MCC: 0.1978, F1: 0.7037

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.28509 | val 0.78091
  Epoch 013 - train 0.13312 | val 0.82964
  Classification -> best τ=0.475 (val F1=0.4682)
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.5455

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.43691 | val 0.92499
  Epoch 012 - train 0.35224 | val 1.15295
  Classification -> best τ=0.545 (val F1=0.2036)
  Directional -> Accuracy: 0.4727, MCC: 0.1242, F1: 0.0645

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.38308 | val 1.24355
  Epoch 013 - train 0.18970 | val 1.59805
  Classification -> best τ=0.410 (val F1=0.3111)
  Directional -> Accuracy: 0.5357, MCC: 0.0633, F1: 0.4348

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.36832 | val 1.18872
  Epoch 011 - train 0.34207 | val 1.41853
  Classification -> best τ=0.545 (val F1=0.1901)
  Directional -> Accuracy: 0.5660, MCC: 0.1343, F1: 0.6349

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.41151 | val 1.06433
  Epoch 016 - train 0.21400 | val 1.41666
  Classification -> best τ=0.380 (val F1=0.2036)
  Directional -> Accuracy: 0.5273, MCC: 0.0000, F1: 0.6905

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.44295 | val 0.74583
  Epoch 011 - train 0.39960 | val 0.76134

[I 2026-02-22 10:45:34,781] Trial 109 finished with value: 0.2534434189366726 and parameters: {'feature_set': 'sector_emotion', 'model_type': 'BiGRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.1, 'batch_size': 64, 'learning_rate': 0.008477135222801264, 'weight_decay': 4.840150900243673e-06, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 1.2214139886675608, 'early_stopping_min_delta': 0.0003787031150914483}. Best is trial 22 with value: 0.2833350641483003.

  Classification -> best τ=0.410 (val F1=0.2623)
  Directional -> Accuracy: 0.5333, MCC: 0.1346, F1: 0.0667

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2534434189366726
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d', 'emotion_anger', 'emotion_disgust', 'emotion_fear', 'emotion_joy', 'emotion_neutral', 'emotion_sadness', 'emotion_surprize', 'emotion_anger_pct', 'emotion_disgust_pct', 'emotion_fear_pct', 'emotion_joy_pct', 'emotion_neutral_pct', 'emotion_sadness_pct', 'emotion_surprize_pct']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.46542 | val 0.67094
  Epoch 016 - train 0.29111 | val 1.12464
  Classification -> best τ=0.675 (val F1=0.2919)
  Directional -> Accuracy: 0.5921, MCC: 0.1649, F1: 0.5079

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.36159 | val 0.93482
  Epoch 011 - train 0.33110 | val 1.09067
  Classification -> best τ=0.435 (val F1=0.2227)
  Directional -> Accuracy: 0.5111, MCC: 0.0260, F1: 0.5417

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.39024 | val 1.48433
  Epoch 013 - train 0.28918 | val 2.13406
  Classification -> best τ=0.555 (val F1=0.1978)
  Directional -> Accuracy: 0.5217, MCC: 0.0826, F1: 0.3529

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.43727 | val 0.90225
  Epoch 012 - train 0.37074 | val 0.98023
  Classification -> best τ=0.560 (val F1=0.1265)
  Directional -> Accuracy: 0.4865, MCC: -0.2204, F1: 0.6545

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.39289 | val 1.17991
  Epoch 013 - train 0.28998 | val 1.19680
  Classification -> best τ=0.625 (val F1=0.2890)
  Directional -> Accuracy: 0.5800, MCC: 0.2203, F1: 0.4324

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.30033 | val 1.13231
  Epoch 013 - train 0.29461 | val 1.16586
  Classification -> best τ=0.470 (val F1=0.2593)
  Directional -> Accuracy: 0.5217, MCC: 0.0543, F1: 0.5600

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.47779 | val 1.27973
  Epoch 011 - train 0.40833 | val 1.01976
  Classification -> best τ=0.470 (val F1=0.2067)
  Directional -> Accuracy: 0.4853, MCC: 0.0333, F1: 0.5070

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.34314 | val 0.50186
  Epoch 020 - train 0.05931 | val 2.13211
  Epoch 021 - train 0.07513 | val 2.76614
  Classification -> best τ=0.215 (val F1=0.5541)
  Directional -> Accuracy: 0.5238, MCC: -0.0152, F1: 0.3333

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.35971 | val 1.00410
  Epoch 016 - train 0.18374 | val 1.94908
  Classification -> best τ=0.765 (val F1=0.4748)
  Directional -> Accuracy: 0.6042, MCC: 0.1917, F1: 0.5366

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.43159 | val 0.94179
  Epoch 011 - train 0.38235 | val 0.95851
  Classification -> best τ=0.435 (val F1=0.2691)
  Directional -> Accuracy: 0.4058, MCC: -0.1064, F1: 0.5684

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.43109 | val 1.08665
  Epoch 012 - train 0.34986 | val 1.25276
  Classification -> best τ=0.485 (val F1=0.2484)
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.42975 | val 2.21424
  Epoch 012 - train 0.34398 | val 2.59819
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5088, MCC: 0.0000, F1: 0.6744

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.37045 | val 1.21731
  Epoch 012 - train 0.32807 | val 1.37918
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.6230

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.42082 | val 0.93193
  Epoch 013 - train 0.36216 | val 1.13239
  Classification -> best τ=0.445 (val F1=0.3642)
  Directional -> Accuracy: 0.5167, MCC: 0.0519, F1: 0.2162

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.42644 | val 1.06669
  Epoch 014 - train 0.32040 | val 1.40563
  Classification -> best τ=0.550 (val F1=0.1455)
  Directional -> Accuracy: 0.5490, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.46494 | val 1.16998
  Epoch 013 - train 0.36667 | val 1.62198
  Classification -> best τ=0.575 (val F1=0.2921)
  Directional -> Accuracy: 0.5652, MCC: 0.1141, F1: 0.6341

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.38741 | val 1.26591
  Epoch 011 - train 0.33816 | val 1.38394
  Classification -> best τ=0.320 (val F1=0.1336)
  Directional -> Accuracy: 0.6034, MCC: 0.0575, F1: 0.7294

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.47834 | val 1.21858
  Epoch 011 - train 0.43812 | val 1.37083
  Classification -> best τ=0.360 (val F1=0.1348)
  Directional -> Accuracy: 0.6000, MCC: 0.0000, F1: 0.7500

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.40643 | val 1.17750
  Epoch 014 - train 0.31127 | val 1.41788
  Classification -> best τ=0.295 (val F1=0.2493)
  Directional -> Accuracy: 0.5000, MCC: -0.0464, F1: 0.5897

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.45886 | val 0.80762
  Epoch 011 - train 0.42656 | val 0.85627
  Classification -> best τ=0.375 (val F1=0.2482)
  Directional -> Accuracy: 0.5270, MCC: -0.0365, F1: 0.6667

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.29137 | val 1.05888
  Epoch 011 - train 0.34073 | val 1.10716
  Classification -> best τ=0.430 (val F1=0.2259)
  Directional -> Accuracy: 0.6383, MCC: 0.1871, F1: 0.7733

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.50220 | val 1.31353
  Epoch 013 - train 0.32091 | val 1.72713
  Classification -> best τ=0.530 (val F1=0.3118)
  Directional -> Accuracy: 0.4923, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.37625 | val 1.43841
  Epoch 013 - train 0.28413 | val 1.34937
  Classification -> best τ=0.605 (val F1=0.4010)
  Directional -> Accuracy: 0.6140, MCC: 0.2236, F1: 0.6452

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.55492 | val 0.82905
  Epoch 011 - train 0.49930 | val 0.72692
  Classification -> best τ=0.420 (val F1=0.2111)
  Directional -> Accuracy: 0.4615, MCC: -0.0711, F1: 0.6154

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.41553 | val 1.34081
  Epoch 014 - train 0.26896 | val 1.72320
  Classification -> best τ=0.480 (val F1=0.3823)
  Directional -> Accuracy: 0.5273, MCC: 0.1143, F1: 0.4091

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.21442 | val 1.15155
  Epoch 015 - train 0.08973 | val 1.85383
  Classification -> best τ=0.620 (val F1=0.2786)
  Directional -> Accuracy: 0.5111, MCC: 0.2029, F1: 0.6207

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.44144 | val 0.85977
  Epoch 015 - train 0.25298 | val 1.16691
  Classification -> best τ=0.630 (val F1=0.4201)
  Directional -> Accuracy: 0.5714, MCC: 0.1021, F1: 0.6538

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.45182 | val 1.15742
  Epoch 012 - train 0.37858 | val 1.41940
  Classification -> best τ=0.410 (val F1=0.1607)
  Directional -> Accuracy: 0.4821, MCC: 0.0435, F1: 0.2927

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.38625 | val 1.36844
  Epoch 013 - train 0.36250 | val 1.21080
  Classification -> best τ=0.550 (val F1=0.4099)
  Directional -> Accuracy: 0.5750, MCC: 0.1124, F1: 0.6909

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.36674 | val 1.09085
  Epoch 012 - train 0.34318 | val 1.30818
  Classification -> best τ=0.535 (val F1=0.3501)
  Directional -> Accuracy: 0.5238, MCC: 0.0455, F1: 0.5000

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.42294 | val 1.96771
  Epoch 012 - train 0.31161 | val 1.47774
  Classification -> best τ=0.330 (val F1=0.2357)
  Directional -> Accuracy: 0.5714, MCC: 0.1718, F1: 0.7188

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.34005 | val 1.55564
  Epoch 013 - train 0.23441 | val 2.26040
  Classification -> best τ=0.390 (val F1=0.4255)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.54219 | val 0.80643
  Epoch 012 - train 0.39301 | val 1.13983
  Classification -> best τ=0.370 (val F1=0.2406)
  Directional -> Accuracy: 0.5556, MCC: 0.0000, F1: 0.7143

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.40075 | val 1.33109
  Epoch 011 - train 0.35050 | val 1.51878
  Classification -> best τ=0.440 (val F1=0.2717)
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.52326 | val 1.11119
  Epoch 011 - train 0.46862 | val 1.07594
  Classification -> best τ=0.405 (val F1=0.2117)
  Directional -> Accuracy: 0.5758, MCC: 0.0000, F1: 0.7308

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.31687 | val 1.81940
  Epoch 013 - train 0.24527 | val 2.05049
  Classification -> best τ=0.495 (val F1=0.3001)
  Directional -> Accuracy: 0.5952, MCC: 0.2035, F1: 0.5641

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.42428 | val 1.96608
  Epoch 012 - train 0.32104 | val 2.19018
  Classification -> best τ=0.470 (val F1=0.2244)
  Directional -> Accuracy: 0.5000, MCC: -0.0051, F1: 0.4615

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.28730 | val 1.06220
  Epoch 012 - train 0.20243 | val 1.14839
  Classification -> best τ=0.540 (val F1=0.2698)
  Directional -> Accuracy: 0.5000, MCC: 0.0393, F1: 0.5106

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.37003 | val 0.73137
  Epoch 018 - train 0.13075 | val 1.64520
  Classification -> best τ=0.725 (val F1=0.4306)
  Directional -> Accuracy: 0.3125, MCC: -0.2495, F1: 0.4590

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.42657 | val 1.53320
  Epoch 011 - train 0.37842 | val 1.67610
  Classification -> best τ=0.430 (val F1=0.2102)
  Directional -> Accuracy: 0.4730, MCC: -0.0638, F1: 0.3810

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.48625 | val 1.08290
  Epoch 013 - train 0.35242 | val 1.24049
  Classification -> best τ=0.570 (val F1=0.3953)
  Directional -> Accuracy: 0.5556, MCC: 0.1266, F1: 0.6667

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.24502 | val 1.06334
  Epoch 013 - train 0.25367 | val 1.23658
  Classification -> best τ=0.245 (val F1=0.3563)
  Directional -> Accuracy: 0.6190, MCC: 0.1925, F1: 0.7241

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.22068 | val 0.74239
  Epoch 014 - train 0.13566 | val 0.84545
  Classification -> best τ=0.515 (val F1=0.5249)
  Directional -> Accuracy: 0.5833, MCC: 0.1721, F1: 0.5238

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.41934 | val 1.25728
  Epoch 013 - train 0.35658 | val 1.46330
  Classification -> best τ=0.730 (val F1=0.2036)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.33575 | val 1.22012
  Epoch 012 - train 0.31460 | val 1.53074
  Classification -> best τ=0.545 (val F1=0.3088)
  Directional -> Accuracy: 0.5357, MCC: 0.0739, F1: 0.1875

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.42297 | val 1.32102
  Epoch 011 - train 0.35184 | val 1.38317
  Classification -> best τ=0.635 (val F1=0.2064)
  Directional -> Accuracy: 0.5849, MCC: 0.1739, F1: 0.5600

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.39183 | val 1.48290
  Epoch 011 - train 0.34641 | val 1.57698
  Classification -> best τ=0.480 (val F1=0.1033)
  Directional -> Accuracy: 0.4909, MCC: -0.0297, F1: 0.5484

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.47432 | val 0.79654

[I 2026-02-22 10:46:54,100] Trial 110 finished with value: 0.27248666484805484 and parameters: {'feature_set': 'sector_emotion', 'model_type': 'BiGRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.2, 'batch_size': 64, 'learning_rate': 0.008988859406574519, 'weight_decay': 1.4305607186127452e-05, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 0.9057467608620545, 'early_stopping_min_delta': 4.172165631638599e-05}. Best is trial 22 with value: 0.2833350641483003.

  Epoch 017 - train 0.27118 | val 1.31760
  Classification -> best τ=0.210 (val F1=0.3008)
  Directional -> Accuracy: 0.4833, MCC: 0.0000, F1: 0.6517

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.27248666484805484
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d', 'emotion_anger', 'emotion_disgust', 'emotion_fear', 'emotion_joy', 'emotion_neutral', 'emotion_sadness', 'emotion_surprize', 'emotion_anger_pct', 'emotion_disgust_pct', 'emotion_fear_pct', 'emotion_joy_pct', 'emotion_neutral_pct', 'emotion_sadness_pct', 'emotion_surprize_pct']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.47121 | val 0.92851
  Epoch 014 - train 0.37053 | val 1.04160
  Classification -> best τ=0.465 (val F1=0.3286)
  Directional -> Accuracy: 0.6184, MCC: 0.2238, F1: 0.3830

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.40267 | val 1.01692
  Epoch 012 - train 0.35250 | val 0.97353
  Classification -> best τ=0.485 (val F1=0.1764)
  Directional -> Accuracy: 0.5111, MCC: 0.1323, F1: 0.3889

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.44512 | val 1.58603
  Epoch 012 - train 0.36917 | val 1.93207
  Classification -> best τ=0.580 (val F1=0.2330)
  Directional -> Accuracy: 0.5652, MCC: 0.2227, F1: 0.7059

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.48494 | val 1.33367
  Epoch 012 - train 0.43840 | val 1.34224
  Classification -> best τ=0.510 (val F1=0.3161)
  Directional -> Accuracy: 0.5811, MCC: 0.1839, F1: 0.7156

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.38619 | val 0.94122
  Epoch 011 - train 0.30013 | val 1.00899
  Classification -> best τ=0.410 (val F1=0.4787)
  Directional -> Accuracy: 0.6600, MCC: 0.3516, F1: 0.6047

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.40260 | val 0.78074
  Epoch 015 - train 0.31072 | val 1.05544
  Classification -> best τ=0.555 (val F1=0.2739)
  Directional -> Accuracy: 0.4783, MCC: -0.0826, F1: 0.2500

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.48528 | val 1.49123
  Epoch 011 - train 0.38843 | val 1.44179
  Classification -> best τ=0.455 (val F1=0.2236)
  Directional -> Accuracy: 0.4853, MCC: 0.0333, F1: 0.5070

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.35434 | val 0.61860
  Epoch 012 - train 0.27729 | val 1.21707
  Classification -> best τ=0.380 (val F1=0.4176)
  Directional -> Accuracy: 0.4048, MCC: -0.1273, F1: 0.5455

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.35351 | val 1.14781
  Epoch 012 - train 0.29848 | val 1.18528
  Classification -> best τ=0.405 (val F1=0.2285)
  Directional -> Accuracy: 0.5625, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.42390 | val 0.84364
  Epoch 013 - train 0.33297 | val 1.07701
  Classification -> best τ=0.455 (val F1=0.2144)
  Directional -> Accuracy: 0.3913, MCC: -0.1583, F1: 0.4878

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.34155 | val 1.93258
  Epoch 011 - train 0.36910 | val 1.98696
  Classification -> best τ=0.585 (val F1=0.1738)
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.42135 | val 2.06168
  Epoch 012 - train 0.37306 | val 2.07353
  Classification -> best τ=0.630 (val F1=0.1181)
  Directional -> Accuracy: 0.4912, MCC: 0.0000, F1: 0.0000

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.45470 | val 1.28279
  Epoch 011 - train 0.32923 | val 1.19455
  Classification -> best τ=0.450 (val F1=0.1356)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.6230

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.41653 | val 0.72561
  Epoch 012 - train 0.32495 | val 0.85426
  Classification -> best τ=0.445 (val F1=0.3378)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.41434 | val 1.20454
  Epoch 013 - train 0.31847 | val 1.80995
  Classification -> best τ=0.360 (val F1=0.1347)
  Directional -> Accuracy: 0.4902, MCC: -0.0216, F1: 0.4583

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.43148 | val 1.37559
  Epoch 013 - train 0.29988 | val 1.49271
  Classification -> best τ=0.675 (val F1=0.2694)
  Directional -> Accuracy: 0.5797, MCC: 0.1910, F1: 0.5246

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.38240 | val 1.23452
  Epoch 012 - train 0.33171 | val 1.43490
  Classification -> best τ=0.565 (val F1=0.1731)
  Directional -> Accuracy: 0.3448, MCC: -0.2012, F1: 0.0952

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.55456 | val 1.36665
  Epoch 012 - train 0.43359 | val 0.90788
  Classification -> best τ=0.620 (val F1=0.1833)
  Directional -> Accuracy: 0.4000, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.47486 | val 1.43380
  Epoch 011 - train 0.38812 | val 1.18052
  Classification -> best τ=0.465 (val F1=0.2843)
  Directional -> Accuracy: 0.5781, MCC: 0.0408, F1: 0.7216

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.52734 | val 0.71398
  Epoch 014 - train 0.33165 | val 0.84168
  Classification -> best τ=0.390 (val F1=0.2957)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.36956 | val 0.95309
  Epoch 013 - train 0.26650 | val 1.50722
  Classification -> best τ=0.505 (val F1=0.3237)
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.40590 | val 1.82329
  Epoch 011 - train 0.36628 | val 1.48292
  Classification -> best τ=0.485 (val F1=0.1925)
  Directional -> Accuracy: 0.4923, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.49306 | val 0.75923
  Epoch 015 - train 0.24028 | val 1.01766
  Classification -> best τ=0.490 (val F1=0.3248)
  Directional -> Accuracy: 0.5789, MCC: 0.1083, F1: 0.7209

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.49616 | val 0.80615
  Epoch 012 - train 0.42245 | val 0.88497
  Classification -> best τ=0.400 (val F1=0.1778)
  Directional -> Accuracy: 0.5692, MCC: 0.1464, F1: 0.5882

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.40300 | val 1.20432
  Epoch 014 - train 0.26443 | val 1.63206
  Classification -> best τ=0.525 (val F1=0.4180)
  Directional -> Accuracy: 0.5455, MCC: 0.1641, F1: 0.4186

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.27581 | val 0.65327
  Epoch 020 - train 0.02217 | val 2.69431
  Classification -> best τ=0.745 (val F1=0.4629)
  Directional -> Accuracy: 0.4667, MCC: -0.1273, F1: 0.2941

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.44682 | val 0.75091
  Epoch 015 - train 0.31469 | val 1.02523
  Classification -> best τ=0.610 (val F1=0.4404)
  Directional -> Accuracy: 0.5476, MCC: 0.1105, F1: 0.5581

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.42713 | val 1.39730
  Epoch 012 - train 0.36295 | val 1.62876
  Classification -> best τ=0.330 (val F1=0.1677)
  Directional -> Accuracy: 0.5536, MCC: 0.0000, F1: 0.7126

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.40340 | val 1.18361
  Epoch 012 - train 0.34080 | val 1.55756
  Classification -> best τ=0.610 (val F1=0.3380)
  Directional -> Accuracy: 0.5000, MCC: -0.0205, F1: 0.5652

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.43302 | val 1.77615
  Epoch 012 - train 0.46625 | val 1.65825
  Classification -> best τ=0.545 (val F1=0.3501)
  Directional -> Accuracy: 0.5000, MCC: 0.0092, F1: 0.5333

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.39072 | val 1.57861
  Epoch 014 - train 0.29800 | val 2.16603
  Classification -> best τ=0.740 (val F1=0.1846)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.36023 | val 2.17563
  Epoch 013 - train 0.27289 | val 2.73182
  Classification -> best τ=0.255 (val F1=0.3142)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.49660 | val 0.83538
  Epoch 013 - train 0.34600 | val 0.93125
  Classification -> best τ=0.450 (val F1=0.4114)
  Directional -> Accuracy: 0.4861, MCC: 0.0691, F1: 0.2745

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.35327 | val 1.23561
  Epoch 011 - train 0.33262 | val 1.46944
  Classification -> best τ=0.480 (val F1=0.2057)
  Directional -> Accuracy: 0.4419, MCC: -0.1140, F1: 0.4783

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.53777 | val 1.28668
  Epoch 012 - train 0.47138 | val 0.96370
  Classification -> best τ=0.580 (val F1=0.2249)
  Directional -> Accuracy: 0.4242, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.32849 | val 2.07354
  Epoch 013 - train 0.25474 | val 2.02096
  Classification -> best τ=0.570 (val F1=0.1822)
  Directional -> Accuracy: 0.5000, MCC: 0.0793, F1: 0.1600

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.39908 | val 1.28971
  Epoch 012 - train 0.31324 | val 1.47971
  Classification -> best τ=0.385 (val F1=0.2256)
  Directional -> Accuracy: 0.5000, MCC: -0.0051, F1: 0.4615

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.32176 | val 1.63262
  Epoch 011 - train 0.27419 | val 1.65712
  Classification -> best τ=0.495 (val F1=0.3690)
  Directional -> Accuracy: 0.4565, MCC: 0.2118, F1: 0.1935

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.32469 | val 0.64990
  Epoch 018 - train 0.10136 | val 0.95100
  Classification -> best τ=0.515 (val F1=0.4710)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.57948 | val 1.74785
  Epoch 012 - train 0.38996 | val 1.53983
  Classification -> best τ=0.450 (val F1=0.2269)
  Directional -> Accuracy: 0.4865, MCC: 0.0000, F1: 0.6545

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.42904 | val 0.82062
  Epoch 014 - train 0.25506 | val 1.48420
  Classification -> best τ=0.505 (val F1=0.3371)
  Directional -> Accuracy: 0.5111, MCC: 0.0285, F1: 0.4500

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.26299 | val 1.08749
  Epoch 013 - train 0.14444 | val 1.50722
  Classification -> best τ=0.455 (val F1=0.3333)
  Directional -> Accuracy: 0.4286, MCC: -0.0700, F1: 0.2500

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.34084 | val 0.90137
  Epoch 011 - train 0.27613 | val 0.71013
  Classification -> best τ=0.500 (val F1=0.4371)
  Directional -> Accuracy: 0.3958, MCC: 0.1130, F1: 0.5538

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.41413 | val 1.41047
  Epoch 011 - train 0.40773 | val 1.47449
  Classification -> best τ=0.550 (val F1=0.2036)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.39961 | val 1.06117
  Epoch 013 - train 0.22193 | val 1.22513
  Classification -> best τ=0.385 (val F1=0.2952)
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.6506

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.45094 | val 1.05440
  Epoch 012 - train 0.31139 | val 1.64656
  Classification -> best τ=0.505 (val F1=0.2351)
  Directional -> Accuracy: 0.4151, MCC: -0.1776, F1: 0.4746

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.42931 | val 1.25969
  Epoch 014 - train 0.35782 | val 1.13948
  Classification -> best τ=0.510 (val F1=0.2020)
  Directional -> Accuracy: 0.4545, MCC: -0.0933, F1: 0.0625

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.38167 | val 0.79600

[I 2026-02-22 10:48:12,775] Trial 111 finished with value: 0.2784007195567964 and parameters: {'feature_set': 'sector_emotion', 'model_type': 'BiGRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.2, 'batch_size': 64, 'learning_rate': 0.008755278937477799, 'weight_decay': 2.5956761109309075e-05, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 0.7983641174726287, 'early_stopping_min_delta': 0.0006950046540263033}. Best is trial 22 with value: 0.2833350641483003.

  Epoch 016 - train 0.28651 | val 1.15683
  Classification -> best τ=0.365 (val F1=0.3117)
  Directional -> Accuracy: 0.4667, MCC: -0.0679, F1: 0.4483

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2784007195567964
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d', 'emotion_anger', 'emotion_disgust', 'emotion_fear', 'emotion_joy', 'emotion_neutral', 'emotion_sadness', 'emotion_surprize', 'emotion_anger_pct', 'emotion_disgust_pct', 'emotion_fear_pct', 'emotion_joy_pct', 'emotion_neutral_pct', 'emotion_sadness_pct', 'emotion_surprize_pct']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.45703 | val 0.82983
  Epoch 011 - train 0.44642 | val 0.97787
  Classification -> best τ=0.585 (val F1=0.1430)
  Directional -> Accuracy: 0.5395, MCC: 0.0059, F1: 0.2222

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.37992 | val 0.89261
  Epoch 012 - train 0.34847 | val 0.88823
  Classification -> best τ=0.485 (val F1=0.0732)
  Directional -> Accuracy: 0.6222, MCC: 0.2030, F1: 0.7018

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.35451 | val 2.11758
  Epoch 012 - train 0.31611 | val 2.72227
  Classification -> best τ=0.520 (val F1=0.1978)
  Directional -> Accuracy: 0.4783, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.46891 | val 1.02369
  Epoch 013 - train 0.37731 | val 1.32799
  Classification -> best τ=0.490 (val F1=0.2712)
  Directional -> Accuracy: 0.5135, MCC: 0.0992, F1: 0.3333

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.33688 | val 1.11555
  Epoch 011 - train 0.35325 | val 1.11911
  Classification -> best τ=0.520 (val F1=0.4556)
  Directional -> Accuracy: 0.6400, MCC: 0.3524, F1: 0.5263

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.40762 | val 1.75918
  Epoch 013 - train 0.36220 | val 0.76403
  Classification -> best τ=0.545 (val F1=0.3210)
  Directional -> Accuracy: 0.5000, MCC: -0.0547, F1: 0.1481

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.45796 | val 1.67265
  Epoch 011 - train 0.44113 | val 2.14766
  Classification -> best τ=0.400 (val F1=0.3383)
  Directional -> Accuracy: 0.5294, MCC: 0.1704, F1: 0.5789

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.31818 | val 0.72904
  Epoch 017 - train 0.20139 | val 1.58954
  Classification -> best τ=0.345 (val F1=0.2566)
  Directional -> Accuracy: 0.4048, MCC: -0.1334, F1: 0.5614

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.38112 | val 1.51845
  Epoch 015 - train 0.22060 | val 2.40890
  Classification -> best τ=0.620 (val F1=0.3441)
  Directional -> Accuracy: 0.6042, MCC: 0.1680, F1: 0.3871

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.44499 | val 0.78737
  Epoch 012 - train 0.40168 | val 0.86344
  Classification -> best τ=0.450 (val F1=0.2079)
  Directional -> Accuracy: 0.4348, MCC: -0.0667, F1: 0.5063

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.41904 | val 0.92716
  Epoch 011 - train 0.37755 | val 1.08271
  Classification -> best τ=0.485 (val F1=0.2397)
  Directional -> Accuracy: 0.5510, MCC: 0.1289, F1: 0.5769

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.43154 | val 1.20828
  Epoch 013 - train 0.30026 | val 2.11762
  Classification -> best τ=0.490 (val F1=0.1944)
  Directional -> Accuracy: 0.6316, MCC: 0.2894, F1: 0.7042

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.38847 | val 1.43634
  Epoch 013 - train 0.25163 | val 1.52394
  Classification -> best τ=0.610 (val F1=0.2176)
  Directional -> Accuracy: 0.5000, MCC: -0.0588, F1: 0.2759

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.43716 | val 0.77128
  Epoch 011 - train 0.42512 | val 0.78698
  Classification -> best τ=0.410 (val F1=0.3844)
  Directional -> Accuracy: 0.5167, MCC: 0.0405, F1: 0.3256

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.38315 | val 1.42486
  Epoch 012 - train 0.30787 | val 1.65024
  Classification -> best τ=0.495 (val F1=0.1347)
  Directional -> Accuracy: 0.5294, MCC: 0.1742, F1: 0.6364

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.49138 | val 1.23650
  Epoch 014 - train 0.30340 | val 1.45788
  Classification -> best τ=0.625 (val F1=0.3151)
  Directional -> Accuracy: 0.5652, MCC: 0.1297, F1: 0.5833

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.46270 | val 0.88479
  Epoch 011 - train 0.37250 | val 0.93610
  Classification -> best τ=0.395 (val F1=0.1336)
  Directional -> Accuracy: 0.5517, MCC: -0.1066, F1: 0.6977

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.52910 | val 0.90038
  Epoch 011 - train 0.45036 | val 1.08626
  Classification -> best τ=0.610 (val F1=0.1909)
  Directional -> Accuracy: 0.4000, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.44265 | val 1.46629
  Epoch 011 - train 0.36762 | val 1.77620
  Classification -> best τ=0.395 (val F1=0.2843)
  Directional -> Accuracy: 0.4688, MCC: -0.1954, F1: 0.6136

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.50687 | val 0.92666
  Epoch 014 - train 0.39031 | val 1.08461
  Classification -> best τ=0.390 (val F1=0.2625)
  Directional -> Accuracy: 0.5676, MCC: 0.1107, F1: 0.6364

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.39186 | val 1.32191
  Epoch 012 - train 0.31690 | val 1.33331
  Classification -> best τ=0.400 (val F1=0.2247)
  Directional -> Accuracy: 0.4468, MCC: -0.0446, F1: 0.4348

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.55023 | val 0.96812
  Epoch 013 - train 0.32261 | val 1.08304
  Classification -> best τ=0.600 (val F1=0.2376)
  Directional -> Accuracy: 0.4923, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.49810 | val 0.91021
  Epoch 016 - train 0.21782 | val 1.64764
  Classification -> best τ=0.815 (val F1=0.3749)
  Directional -> Accuracy: 0.4737, MCC: 0.0014, F1: 0.3750

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.46652 | val 0.84769
  Epoch 015 - train 0.26320 | val 1.03689
  Classification -> best τ=0.380 (val F1=0.1478)
  Directional -> Accuracy: 0.5846, MCC: 0.2464, F1: 0.6747

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.39254 | val 2.13926
  Epoch 013 - train 0.26684 | val 2.69474
  Classification -> best τ=0.475 (val F1=0.4582)
  Directional -> Accuracy: 0.5636, MCC: 0.1827, F1: 0.4783

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.25630 | val 0.74935
  Epoch 018 - train 0.05016 | val 3.02776
  Classification -> best τ=0.740 (val F1=0.5701)
  Directional -> Accuracy: 0.5333, MCC: 0.2428, F1: 0.6316

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.43682 | val 0.70342
  Epoch 018 - train 0.16177 | val 0.86714
  Classification -> best τ=0.570 (val F1=0.3717)
  Directional -> Accuracy: 0.5476, MCC: 0.1434, F1: 0.5128

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.42930 | val 1.52667
  Epoch 013 - train 0.29368 | val 1.69540
  Classification -> best τ=0.365 (val F1=0.1383)
  Directional -> Accuracy: 0.4643, MCC: -0.1728, F1: 0.6053

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.33535 | val 0.72324
  Epoch 016 - train 0.14820 | val 1.21610
  Classification -> best τ=0.620 (val F1=0.3477)
  Directional -> Accuracy: 0.4750, MCC: -0.0161, F1: 0.4000

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.38072 | val 1.24036
  Epoch 012 - train 0.35278 | val 1.94701
  Classification -> best τ=0.480 (val F1=0.3501)
  Directional -> Accuracy: 0.5000, MCC: -0.0092, F1: 0.4324

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.34733 | val 1.12552
  Epoch 013 - train 0.28061 | val 1.84565
  Classification -> best τ=0.500 (val F1=0.2357)
  Directional -> Accuracy: 0.4524, MCC: -0.1711, F1: 0.5818

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.33603 | val 1.76962
  Epoch 013 - train 0.28129 | val 2.52684
  Classification -> best τ=0.380 (val F1=0.3529)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.54699 | val 0.78508
  Epoch 015 - train 0.28126 | val 1.16740
  Classification -> best τ=0.390 (val F1=0.3369)
  Directional -> Accuracy: 0.5139, MCC: 0.1147, F1: 0.3636

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.39134 | val 0.95786
  Epoch 011 - train 0.37711 | val 1.00333
  Classification -> best τ=0.445 (val F1=0.2717)
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.54707 | val 0.79652
  Epoch 012 - train 0.45132 | val 0.94603
  Classification -> best τ=0.610 (val F1=0.2249)
  Directional -> Accuracy: 0.4242, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.28685 | val 0.84563
  Epoch 014 - train 0.15759 | val 1.23781
  Classification -> best τ=0.455 (val F1=0.2721)
  Directional -> Accuracy: 0.7143, MCC: 0.4273, F1: 0.7273

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.33890 | val 1.91109
  Epoch 012 - train 0.31107 | val 1.68785
  Classification -> best τ=0.420 (val F1=0.3155)
  Directional -> Accuracy: 0.4286, MCC: -0.1344, F1: 0.4483

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.34008 | val 0.90237
  Epoch 011 - train 0.30579 | val 0.93113
  Classification -> best τ=0.415 (val F1=0.1195)
  Directional -> Accuracy: 0.6087, MCC: 0.1022, F1: 0.7273

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.47157 | val 0.63841
  Epoch 018 - train 0.13981 | val 1.08236
  Classification -> best τ=0.315 (val F1=0.4011)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.48688 | val 1.46469
  Epoch 012 - train 0.38900 | val 1.37081
  Classification -> best τ=0.310 (val F1=0.2766)
  Directional -> Accuracy: 0.4865, MCC: 0.0000, F1: 0.6545

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.34386 | val 0.86902
  Epoch 011 - train 0.35994 | val 0.96546
  Classification -> best τ=0.520 (val F1=0.5000)
  Directional -> Accuracy: 0.6000, MCC: 0.3194, F1: 0.7188

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.29700 | val 0.92645
  Epoch 013 - train 0.17919 | val 1.30224
  Classification -> best τ=0.400 (val F1=0.3333)
  Directional -> Accuracy: 0.6190, MCC: 0.2123, F1: 0.6800

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.31063 | val 0.76764
  Epoch 019 - train 0.15900 | val 0.99427
  Classification -> best τ=0.495 (val F1=0.4371)
  Directional -> Accuracy: 0.5417, MCC: 0.2914, F1: 0.6071

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.44658 | val 1.54931
  Epoch 012 - train 0.41269 | val 1.48815
  Classification -> best τ=0.615 (val F1=0.1682)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.32269 | val 1.51175
  Epoch 012 - train 0.24502 | val 1.68866
  Classification -> best τ=0.415 (val F1=0.3497)
  Directional -> Accuracy: 0.5179, MCC: 0.0146, F1: 0.2286

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.44482 | val 0.96096
  Epoch 011 - train 0.39720 | val 0.96722
  Classification -> best τ=0.525 (val F1=0.2788)
  Directional -> Accuracy: 0.6038, MCC: 0.2109, F1: 0.6557

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.39420 | val 1.81160
  Epoch 012 - train 0.38778 | val 0.95283
  Classification -> best τ=0.545 (val F1=0.2291)
  Directional -> Accuracy: 0.4364, MCC: -0.2052, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.44520 | val 1.32839
  Epoch 011 - train 0.39297 | val 1.26613

[I 2026-02-22 10:49:32,663] Trial 112 finished with value: 0.2833506688525635 and parameters: {'feature_set': 'sector_emotion', 'model_type': 'BiGRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.2, 'batch_size': 64, 'learning_rate': 0.009874069956732666, 'weight_decay': 6.214688581192553e-05, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 0.8123821597288361, 'early_stopping_min_delta': 0.000200176745543631}. Best is trial 112 with value: 0.2833506688525635.

  Classification -> best τ=0.425 (val F1=0.3108)
  Directional -> Accuracy: 0.5167, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2833506688525635
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d', 'emotion_anger', 'emotion_disgust', 'emotion_fear', 'emotion_joy', 'emotion_neutral', 'emotion_sadness', 'emotion_surprize', 'emotion_anger_pct', 'emotion_disgust_pct', 'emotion_fear_pct', 'emotion_joy_pct', 'emotion_neutral_pct', 'emotion_sadness_pct', 'emotion_surprize_pct']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.43033 | val 0.79938
  Epoch 016 - train 0.27625 | val 0.78911
  Classification -> best τ=0.425 (val F1=0.3286)
  Directional -> Accuracy: 0.6053, MCC: 0.1910, F1: 0.3478

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.43984 | val 1.03233
  Epoch 013 - train 0.30266 | val 1.11626
  Classification -> best τ=0.375 (val F1=0.1844)
  Directional -> Accuracy: 0.4444, MCC: -0.1022, F1: 0.4681

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.35823 | val 2.48044
  Epoch 013 - train 0.27675 | val 3.56922
  Classification -> best τ=0.620 (val F1=0.2727)
  Directional -> Accuracy: 0.5435, MCC: 0.1633, F1: 0.3226

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.50825 | val 1.25232
  Epoch 012 - train 0.44823 | val 1.04905
  Classification -> best τ=0.515 (val F1=0.1745)
  Directional -> Accuracy: 0.4865, MCC: -0.0537, F1: 0.5682

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.36629 | val 1.23955
  Epoch 011 - train 0.27481 | val 1.30942
  Classification -> best τ=0.485 (val F1=0.2716)
  Directional -> Accuracy: 0.5200, MCC: 0.0917, F1: 0.2941

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.37379 | val 0.64881
  Epoch 019 - train 0.15243 | val 1.96159
  Classification -> best τ=0.635 (val F1=0.5229)
  Directional -> Accuracy: 0.5217, MCC: 0.0093, F1: 0.0833

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.40215 | val 1.85329
  Epoch 012 - train 0.31953 | val 1.42993
  Classification -> best τ=0.465 (val F1=0.2772)
  Directional -> Accuracy: 0.5000, MCC: 0.0578, F1: 0.5143

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.28390 | val 0.85772
  Epoch 015 - train 0.18829 | val 1.86337
  Classification -> best τ=0.365 (val F1=0.6184)
  Directional -> Accuracy: 0.4524, MCC: 0.0212, F1: 0.5818

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.42886 | val 1.53524
  Epoch 012 - train 0.38408 | val 1.43714
  Classification -> best τ=0.435 (val F1=0.3433)
  Directional -> Accuracy: 0.6250, MCC: 0.2186, F1: 0.4375

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.41885 | val 1.15837
  Epoch 013 - train 0.31768 | val 1.26481
  Classification -> best τ=0.585 (val F1=0.1554)
  Directional -> Accuracy: 0.4203, MCC: -0.1256, F1: 0.4444

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.41538 | val 1.60264
  Epoch 012 - train 0.31617 | val 1.76345
  Classification -> best τ=0.420 (val F1=0.3590)
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.41695 | val 1.89067
  Epoch 012 - train 0.36172 | val 2.38263
  Classification -> best τ=0.560 (val F1=0.1500)
  Directional -> Accuracy: 0.5263, MCC: 0.0827, F1: 0.6747

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.40187 | val 2.50379
  Epoch 013 - train 0.27150 | val 2.81967
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.6230

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.44105 | val 0.61229
  Epoch 016 - train 0.27814 | val 0.74870
  Classification -> best τ=0.465 (val F1=0.3774)
  Directional -> Accuracy: 0.5167, MCC: 0.0519, F1: 0.2162

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.43933 | val 1.03480
  Epoch 013 - train 0.34306 | val 1.82012
  Classification -> best τ=0.590 (val F1=0.1455)
  Directional -> Accuracy: 0.5490, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.49879 | val 1.13523
  Epoch 012 - train 0.42232 | val 1.27668
  Classification -> best τ=0.305 (val F1=0.1512)
  Directional -> Accuracy: 0.5217, MCC: -0.0357, F1: 0.6733

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.52587 | val 1.39645
  Epoch 011 - train 0.37247 | val 1.29576
  Classification -> best τ=0.245 (val F1=0.1905)
  Directional -> Accuracy: 0.6034, MCC: 0.0131, F1: 0.7416

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.48493 | val 0.98345
  Epoch 014 - train 0.34946 | val 1.46399
  Classification -> best τ=0.490 (val F1=0.1071)
  Directional -> Accuracy: 0.3867, MCC: -0.1424, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.36121 | val 1.44275
  Epoch 013 - train 0.24252 | val 1.86813
  Classification -> best τ=0.520 (val F1=0.2846)
  Directional -> Accuracy: 0.4844, MCC: 0.1315, F1: 0.2667

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.50915 | val 0.88229
  Epoch 014 - train 0.41270 | val 1.05928
  Classification -> best τ=0.545 (val F1=0.2593)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.33680 | val 1.47406
  Epoch 012 - train 0.28204 | val 1.47918
  Classification -> best τ=0.490 (val F1=0.4040)
  Directional -> Accuracy: 0.4255, MCC: -0.1381, F1: 0.4706

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.43133 | val 1.08504
  Epoch 012 - train 0.32461 | val 1.34312
  Classification -> best τ=0.420 (val F1=0.2541)
  Directional -> Accuracy: 0.5692, MCC: 0.1742, F1: 0.4167

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.49840 | val 0.91720
  Epoch 012 - train 0.36876 | val 1.00400
  Classification -> best τ=0.675 (val F1=0.3175)
  Directional -> Accuracy: 0.5439, MCC: 0.0820, F1: 0.5806

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.43082 | val 0.71880
  Epoch 012 - train 0.43208 | val 0.77194
  Classification -> best τ=0.375 (val F1=0.2111)
  Directional -> Accuracy: 0.5077, MCC: 0.0359, F1: 0.5789

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.40612 | val 1.09341
  Epoch 014 - train 0.22804 | val 1.96818
  Classification -> best τ=0.250 (val F1=0.3750)
  Directional -> Accuracy: 0.5273, MCC: 0.0669, F1: 0.5185

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.20425 | val 1.16568
  Epoch 011 - train 0.24842 | val 1.41290
  Classification -> best τ=0.425 (val F1=0.1310)
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.5938

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.40860 | val 0.75119
  Epoch 014 - train 0.29037 | val 1.21903
  Classification -> best τ=0.620 (val F1=0.3536)
  Directional -> Accuracy: 0.5000, MCC: 0.1005, F1: 0.3636

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.44236 | val 1.18840
  Epoch 012 - train 0.37791 | val 1.22385
  Classification -> best τ=0.385 (val F1=0.1802)
  Directional -> Accuracy: 0.4464, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.35215 | val 1.23412
  Epoch 012 - train 0.38145 | val 1.27273
  Classification -> best τ=0.490 (val F1=0.2414)
  Directional -> Accuracy: 0.5750, MCC: 0.1240, F1: 0.7119

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.45573 | val 2.27938
  Epoch 012 - train 0.29330 | val 1.47128
  Classification -> best τ=0.530 (val F1=0.3001)
  Directional -> Accuracy: 0.5476, MCC: 0.0953, F1: 0.5366

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.41943 | val 1.45137
  Epoch 012 - train 0.40618 | val 1.34607
  Classification -> best τ=0.445 (val F1=0.1286)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.37610 | val 1.75429
  Epoch 011 - train 0.34254 | val 1.94088
  Classification -> best τ=0.455 (val F1=0.2918)
  Directional -> Accuracy: 0.5102, MCC: 0.0517, F1: 0.4000

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.54452 | val 0.66135
  Epoch 020 - train 0.21474 | val 2.00779
  Epoch 022 - train 0.10506 | val 1.84410
  Classification -> best τ=0.560 (val F1=0.3228)
  Directional -> Accuracy: 0.5139, MCC: 0.1992, F1: 0.2553

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.31103 | val 1.58534
  Epoch 011 - train 0.35460 | val 1.52858
  Classification -> best τ=0.510 (val F1=0.2804)
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.48427 | val 1.11826
  Epoch 013 - train 0.37126 | val 1.61875
  Classification -> best τ=0.320 (val F1=0.3342)
  Directional -> Accuracy: 0.6061, MCC: 0.2529, F1: 0.5938

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.24442 | val 1.59169
  Epoch 014 - train 0.18354 | val 1.59512
  Classification -> best τ=0.595 (val F1=0.3287)
  Directional -> Accuracy: 0.5952, MCC: 0.1907, F1: 0.6047

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.41647 | val 1.31590
  Epoch 012 - train 0.33092 | val 1.30993
  Classification -> best τ=0.340 (val F1=0.2114)
  Directional -> Accuracy: 0.4464, MCC: -0.1003, F1: 0.4561

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.31020 | val 1.12526
  Epoch 013 - train 0.21951 | val 1.66204
  Classification -> best τ=0.565 (val F1=0.3334)
  Directional -> Accuracy: 0.4130, MCC: -0.0062, F1: 0.1818

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.38674 | val 0.80016
  Epoch 012 - train 0.32178 | val 0.82784
  Classification -> best τ=0.525 (val F1=0.0896)
  Directional -> Accuracy: 0.5833, MCC: 0.0388, F1: 0.3333

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.50445 | val 1.77346
  Epoch 011 - train 0.40064 | val 1.55374
  Classification -> best τ=0.385 (val F1=0.2998)
  Directional -> Accuracy: 0.4730, MCC: -0.0664, F1: 0.3607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.40258 | val 0.83610
  Epoch 011 - train 0.42168 | val 0.80331
  Classification -> best τ=0.450 (val F1=0.2169)
  Directional -> Accuracy: 0.5111, MCC: 0.0000, F1: 0.6765

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.34708 | val 1.12874
  Epoch 013 - train 0.20163 | val 1.29919
  Classification -> best τ=0.525 (val F1=0.3333)
  Directional -> Accuracy: 0.4762, MCC: -0.0278, F1: 0.4762

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.30199 | val 0.73526
  Epoch 011 - train 0.29223 | val 0.77745
  Classification -> best τ=0.535 (val F1=0.5249)
  Directional -> Accuracy: 0.6042, MCC: 0.0176, F1: 0.1739

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.45322 | val 1.00800
  Epoch 011 - train 0.41763 | val 1.12783
  Classification -> best τ=0.590 (val F1=0.2036)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.33683 | val 1.34726
  Epoch 014 - train 0.21045 | val 1.73697
  Classification -> best τ=0.495 (val F1=0.2280)
  Directional -> Accuracy: 0.4821, MCC: -0.0069, F1: 0.6420

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.37360 | val 1.50691
  Epoch 012 - train 0.29722 | val 2.09652
  Classification -> best τ=0.475 (val F1=0.2127)
  Directional -> Accuracy: 0.6038, MCC: 0.2423, F1: 0.6957

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.37935 | val 2.74758
  Epoch 012 - train 0.29851 | val 1.80804
  Classification -> best τ=0.515 (val F1=0.2368)
  Directional -> Accuracy: 0.5273, MCC: 0.2274, F1: 0.1875

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.43318 | val 1.68174
  Epoch 011 - train 0.39359 | val 2.04109

[I 2026-02-22 10:50:53,642] Trial 113 finished with value: 0.2662685670341154 and parameters: {'feature_set': 'sector_emotion', 'model_type': 'BiGRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.2, 'batch_size': 64, 'learning_rate': 0.00994876988828708, 'weight_decay': 4.641399823746603e-05, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 0.7157793321814647, 'early_stopping_min_delta': 0.0001698187885182045}. Best is trial 112 with value: 0.2833506688525635.

  Classification -> best τ=0.475 (val F1=0.2623)
  Directional -> Accuracy: 0.5167, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2662685670341154
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d', 'emotion_anger', 'emotion_disgust', 'emotion_fear', 'emotion_joy', 'emotion_neutral', 'emotion_sadness', 'emotion_surprize', 'emotion_anger_pct', 'emotion_disgust_pct', 'emotion_fear_pct', 'emotion_joy_pct', 'emotion_neutral_pct', 'emotion_sadness_pct', 'emotion_surprize_pct']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.51151 | val 1.01619
  Epoch 014 - train 0.35108 | val 1.79262
  Classification -> best τ=0.550 (val F1=0.1989)
  Directional -> Accuracy: 0.5974, MCC: 0.1755, F1: 0.4918

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.37371 | val 0.81121
  Epoch 013 - train 0.28983 | val 0.99948
  Classification -> best τ=0.405 (val F1=0.1154)
  Directional -> Accuracy: 0.6739, MCC: 0.3412, F1: 0.7619

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.41190 | val 1.54577
  Epoch 012 - train 0.29253 | val 1.85065
  Classification -> best τ=0.670 (val F1=0.1342)
  Directional -> Accuracy: 0.4681, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.49508 | val 1.31354
  Epoch 011 - train 0.46340 | val 1.59036
  Classification -> best τ=0.365 (val F1=0.1210)
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.35515 | val 2.72320
  Epoch 012 - train 0.30088 | val 2.42065
  Classification -> best τ=0.385 (val F1=0.3725)
  Directional -> Accuracy: 0.5490, MCC: 0.1073, F1: 0.5306

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.39188 | val 0.71534
  Epoch 020 - train 0.16456 | val 1.13462
  Epoch 023 - train 0.13864 | val 1.10954
  Classification -> best τ=0.420 (val F1=0.4330)
  Directional -> Accuracy: 0.5106, MCC: 0.0168, F1: 0.4390

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.49446 | val 1.15893
  Epoch 011 - train 0.43047 | val 1.14033
  Classification -> best τ=0.510 (val F1=0.2897)
  Directional -> Accuracy: 0.5507, MCC: 0.1061, F1: 0.5079

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.36568 | val 0.67142
  Epoch 015 - train 0.28255 | val 1.42563
  Classification -> best τ=0.400 (val F1=0.4756)
  Directional -> Accuracy: 0.4318, MCC: -0.0365, F1: 0.5283

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.49061 | val 1.48435
  Epoch 012 - train 0.40658 | val 1.55839
  Classification -> best τ=0.515 (val F1=0.3461)
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.45449 | val 0.82709
  Epoch 012 - train 0.36625 | val 1.00314
  Classification -> best τ=0.680 (val F1=0.1092)
  Directional -> Accuracy: 0.5571, MCC: 0.0556, F1: 0.3673

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.44243 | val 2.87425
  Epoch 012 - train 0.38102 | val 2.95351
  Classification -> best τ=0.480 (val F1=0.2588)
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.43234 | val 1.76380
  Epoch 012 - train 0.40107 | val 2.23033
  Classification -> best τ=0.525 (val F1=0.1703)
  Directional -> Accuracy: 0.5172, MCC: 0.0476, F1: 0.2632

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.37156 | val 1.40657
  Epoch 011 - train 0.32962 | val 1.25930
  Classification -> best τ=0.465 (val F1=0.2004)
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.44358 | val 0.76355
  Epoch 016 - train 0.29020 | val 1.02235
  Classification -> best τ=0.425 (val F1=0.3400)
  Directional -> Accuracy: 0.4918, MCC: -0.0043, F1: 0.1143

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.46930 | val 0.91894
  Epoch 011 - train 0.41319 | val 0.94289
  Classification -> best τ=0.420 (val F1=0.2449)
  Directional -> Accuracy: 0.5192, MCC: 0.1711, F1: 0.6479

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.52000 | val 1.08817
  Epoch 012 - train 0.41321 | val 1.28036
  Classification -> best τ=0.685 (val F1=0.2979)
  Directional -> Accuracy: 0.5429, MCC: 0.1721, F1: 0.3846

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.41541 | val 1.90014
  Epoch 011 - train 0.39718 | val 2.14233
  Classification -> best τ=0.395 (val F1=0.2294)
  Directional -> Accuracy: 0.6271, MCC: 0.1328, F1: 0.7381

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.48059 | val 0.86793
  Epoch 012 - train 0.43889 | val 1.03790
  Classification -> best τ=0.450 (val F1=0.1217)
  Directional -> Accuracy: 0.6053, MCC: 0.0000, F1: 0.7541

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.42635 | val 1.76091
  Epoch 012 - train 0.39241 | val 1.88335
  Classification -> best τ=0.570 (val F1=0.2480)
  Directional -> Accuracy: 0.4154, MCC: -0.0643, F1: 0.1739

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.49038 | val 0.78895
  Epoch 013 - train 0.40665 | val 0.86599
  Classification -> best τ=0.535 (val F1=0.3269)
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.40884 | val 0.91787
  Epoch 011 - train 0.36168 | val 1.01928
  Classification -> best τ=0.505 (val F1=0.2522)
  Directional -> Accuracy: 0.3958, MCC: -0.0689, F1: 0.2564

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.45416 | val 0.85394
  Epoch 011 - train 0.38934 | val 0.94253
  Classification -> best τ=0.315 (val F1=0.2284)
  Directional -> Accuracy: 0.4848, MCC: -0.0492, F1: 0.1500

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.45847 | val 1.01251
  Epoch 013 - train 0.38041 | val 0.97462
  Classification -> best τ=0.690 (val F1=0.3496)
  Directional -> Accuracy: 0.5517, MCC: 0.1248, F1: 0.5517

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.46971 | val 0.81401
  Epoch 011 - train 0.42515 | val 0.78260
  Classification -> best τ=0.550 (val F1=0.1318)
  Directional -> Accuracy: 0.5909, MCC: 0.1950, F1: 0.3415

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.44234 | val 1.11294
  Epoch 015 - train 0.29236 | val 1.99646
  Classification -> best τ=0.155 (val F1=0.3780)
  Directional -> Accuracy: 0.5536, MCC: 0.0207, F1: 0.7059

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.28949 | val 1.09356
  Epoch 011 - train 0.26935 | val 1.21463
  Classification -> best τ=0.555 (val F1=0.1925)
  Directional -> Accuracy: 0.5652, MCC: 0.0870, F1: 0.4118

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.40098 | val 0.83259
  Epoch 014 - train 0.24947 | val 0.77201
  Classification -> best τ=0.500 (val F1=0.3652)
  Directional -> Accuracy: 0.5814, MCC: 0.2254, F1: 0.5500

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.45663 | val 1.15531
  Epoch 014 - train 0.33491 | val 1.67789
  Classification -> best τ=0.345 (val F1=0.1370)
  Directional -> Accuracy: 0.4561, MCC: -0.0657, F1: 0.4364

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.41474 | val 0.86745
  Epoch 017 - train 0.29127 | val 1.05356
  Classification -> best τ=0.475 (val F1=0.3677)
  Directional -> Accuracy: 0.4390, MCC: -0.1678, F1: 0.5490

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.33864 | val 3.17544
  Epoch 012 - train 0.33523 | val 3.37018
  Classification -> best τ=0.545 (val F1=0.1869)
  Directional -> Accuracy: 0.5349, MCC: 0.0675, F1: 0.5000

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.41439 | val 0.65704
  Epoch 011 - train 0.46502 | val 0.66541
  Classification -> best τ=0.690 (val F1=0.2764)
  Directional -> Accuracy: 0.4186, MCC: -0.1539, F1: 0.3902

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.37189 | val 1.56311
  Epoch 011 - train 0.35829 | val 1.62273
  Classification -> best τ=0.395 (val F1=0.2461)
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.44717 | val 0.75472
  Epoch 012 - train 0.37351 | val 0.76564
  Classification -> best τ=0.375 (val F1=0.3721)
  Directional -> Accuracy: 0.5890, MCC: 0.1306, F1: 0.7000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.33849 | val 0.83824
  Epoch 011 - train 0.28172 | val 0.88677
  Classification -> best τ=0.480 (val F1=0.2182)
  Directional -> Accuracy: 0.5789, MCC: 0.1588, F1: 0.5556

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.41338 | val 0.86023
  Epoch 011 - train 0.39680 | val 0.89706
  Classification -> best τ=0.410 (val F1=0.1902)
  Directional -> Accuracy: 0.5000, MCC: 0.0780, F1: 0.6452

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.48396 | val 1.15366
  Epoch 011 - train 0.42664 | val 1.22227
  Classification -> best τ=0.440 (val F1=0.3521)
  Directional -> Accuracy: 0.5970, MCC: 0.1428, F1: 0.7216

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.33533 | val 1.07518
  Epoch 014 - train 0.28503 | val 1.20719
  Classification -> best τ=0.560 (val F1=0.2740)
  Directional -> Accuracy: 0.5814, MCC: 0.2074, F1: 0.4375

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.40590 | val 1.88605
  Epoch 011 - train 0.36523 | val 2.28640
  Classification -> best τ=0.600 (val F1=0.2236)
  Directional -> Accuracy: 0.5614, MCC: 0.1326, F1: 0.2424

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.32438 | val 0.82337
  Epoch 014 - train 0.19676 | val 0.98387
  Classification -> best τ=0.510 (val F1=0.3057)
  Directional -> Accuracy: 0.4043, MCC: -0.0392, F1: 0.2222

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.37019 | val 0.66939
  Epoch 020 - train 0.18046 | val 1.66643
  Classification -> best τ=0.415 (val F1=0.3533)
  Directional -> Accuracy: 0.3469, MCC: -0.1894, F1: 0.5152

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.41122 | val 1.15594
  Epoch 011 - train 0.38364 | val 1.25271
  Classification -> best τ=0.465 (val F1=0.2227)
  Directional -> Accuracy: 0.5789, MCC: 0.1611, F1: 0.5789

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.43954 | val 1.66763
  Epoch 011 - train 0.40286 | val 1.69533
  Classification -> best τ=0.480 (val F1=0.3332)
  Directional -> Accuracy: 0.4533, MCC: -0.0980, F1: 0.3881

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.48413 | val 0.88778
  Epoch 014 - train 0.38455 | val 1.14125
  Classification -> best τ=0.465 (val F1=0.2309)
  Directional -> Accuracy: 0.5532, MCC: 0.1069, F1: 0.5532

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.28959 | val 1.09675
  Epoch 011 - train 0.23438 | val 1.20017
  Classification -> best τ=0.480 (val F1=0.2628)
  Directional -> Accuracy: 0.5455, MCC: -0.1329, F1: 0.7059

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.30108 | val 0.79885
  Epoch 012 - train 0.26204 | val 0.83755
  Classification -> best τ=0.520 (val F1=0.1890)
  Directional -> Accuracy: 0.4286, MCC: 0.0843, F1: 0.5625

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.50629 | val 0.94114
  Epoch 012 - train 0.41983 | val 1.04703
  Classification -> best τ=0.685 (val F1=0.1914)
  Directional -> Accuracy: 0.4643, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.39378 | val 0.98664
  Epoch 015 - train 0.20326 | val 1.44265
  Classification -> best τ=0.445 (val F1=0.2671)
  Directional -> Accuracy: 0.4912, MCC: 0.0663, F1: 0.6420

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.45469 | val 1.15552
  Epoch 012 - train 0.36315 | val 1.61565
  Classification -> best τ=0.460 (val F1=0.1972)
  Directional -> Accuracy: 0.5370, MCC: 0.0899, F1: 0.6835

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.42108 | val 1.22560
  Epoch 014 - train 0.31622 | val 1.25938
  Classification -> best τ=0.375 (val F1=0.2402)
  Directional -> Accuracy: 0.5179, MCC: 0.0000, F1: 0.6824

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.48038 | val 0.71531

[I 2026-02-22 10:51:58,401] Trial 114 finished with value: 0.2566659402164573 and parameters: {'feature_set': 'sector_emotion', 'model_type': 'BiGRU', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.30000000000000004, 'batch_size': 64, 'learning_rate': 0.007817294845461273, 'weight_decay': 8.058588251125552e-05, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 0.8157325289769144, 'early_stopping_min_delta': 9.456976528217572e-05}. Best is trial 112 with value: 0.2833506688525635.

  Epoch 018 - train 0.23163 | val 1.47729
  Classification -> best τ=0.640 (val F1=0.2639)
  Directional -> Accuracy: 0.5246, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2566659402164573
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d', 'emotion_anger', 'emotion_disgust', 'emotion_fear', 'emotion_joy', 'emotion_neutral', 'emotion_sadness', 'emotion_surprize', 'emotion_anger_pct', 'emotion_disgust_pct', 'emotion_fear_pct', 'emotion_joy_pct', 'emotion_neutral_pct', 'emotion_sadness_pct', 'emotion_surprize_pct']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.52751 | val 0.86947
  Epoch 015 - train 0.38962 | val 1.16159
  Classification -> best τ=0.575 (val F1=0.2627)
  Directional -> Accuracy: 0.5395, MCC: 0.0509, F1: 0.4262

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.40670 | val 0.86205
  Epoch 011 - train 0.41090 | val 0.87510
  Classification -> best τ=0.470 (val F1=0.2030)
  Directional -> Accuracy: 0.4889, MCC: 0.1591, F1: 0.2581

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.34480 | val 1.68088
  Epoch 011 - train 0.36661 | val 1.91846
  Classification -> best τ=0.555 (val F1=0.2309)
  Directional -> Accuracy: 0.6304, MCC: 0.2583, F1: 0.6531

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.50252 | val 1.08617
  Epoch 012 - train 0.46056 | val 1.77136
  Classification -> best τ=0.335 (val F1=0.1156)
  Directional -> Accuracy: 0.4865, MCC: -0.2204, F1: 0.6545

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.29401 | val 1.21135
  Epoch 011 - train 0.29233 | val 1.27069
  Classification -> best τ=0.550 (val F1=0.3612)
  Directional -> Accuracy: 0.6000, MCC: 0.2587, F1: 0.4737

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.38424 | val 0.66510
  Epoch 016 - train 0.19913 | val 0.97837
  Classification -> best τ=0.380 (val F1=0.4772)
  Directional -> Accuracy: 0.5217, MCC: 0.0496, F1: 0.5417

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.45374 | val 1.48188
  Epoch 011 - train 0.44189 | val 1.42771
  Classification -> best τ=0.410 (val F1=0.2557)
  Directional -> Accuracy: 0.5147, MCC: 0.1667, F1: 0.5823

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.27742 | val 1.04866
  Epoch 016 - train 0.25914 | val 1.05610
  Classification -> best τ=0.515 (val F1=0.3632)
  Directional -> Accuracy: 0.5000, MCC: -0.0138, F1: 0.4324

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.39201 | val 1.21520
  Epoch 013 - train 0.32523 | val 1.78397
  Classification -> best τ=0.465 (val F1=0.2955)
  Directional -> Accuracy: 0.5625, MCC: 0.2456, F1: 0.6441

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.40684 | val 0.91870
  Epoch 011 - train 0.39416 | val 0.98945
  Classification -> best τ=0.495 (val F1=0.2071)
  Directional -> Accuracy: 0.4058, MCC: -0.1061, F1: 0.5393

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.40092 | val 1.12989
  Epoch 012 - train 0.29288 | val 1.41850
  Classification -> best τ=0.485 (val F1=0.2495)
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.41649 | val 1.57771
  Epoch 011 - train 0.38615 | val 1.53388
  Classification -> best τ=0.435 (val F1=0.1083)
  Directional -> Accuracy: 0.5088, MCC: 0.0000, F1: 0.6744

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.37874 | val 1.19185
  Epoch 013 - train 0.29455 | val 1.53498
  Classification -> best τ=0.570 (val F1=0.1225)
  Directional -> Accuracy: 0.5714, MCC: 0.1718, F1: 0.1000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.44594 | val 0.87841
  Epoch 015 - train 0.30103 | val 1.00703
  Classification -> best τ=0.510 (val F1=0.3864)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.41955 | val 0.89946
  Epoch 013 - train 0.36648 | val 1.50434
  Classification -> best τ=0.565 (val F1=0.2571)
  Directional -> Accuracy: 0.5490, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.39504 | val 1.22211
  Epoch 013 - train 0.30770 | val 1.45894
  Classification -> best τ=0.635 (val F1=0.1989)
  Directional -> Accuracy: 0.4783, MCC: 0.0081, F1: 0.2500

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.44134 | val 0.85754
  Epoch 012 - train 0.36846 | val 1.04388
  Classification -> best τ=0.630 (val F1=0.2942)
  Directional -> Accuracy: 0.3793, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.46851 | val 1.77420
  Epoch 011 - train 0.45213 | val 1.76394
  Classification -> best τ=0.490 (val F1=0.2220)
  Directional -> Accuracy: 0.4000, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.47176 | val 1.20629
  Epoch 011 - train 0.38712 | val 1.31273
  Classification -> best τ=0.435 (val F1=0.3202)
  Directional -> Accuracy: 0.5781, MCC: 0.0408, F1: 0.7216

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.51189 | val 0.91188
  Epoch 012 - train 0.44037 | val 1.05376
  Classification -> best τ=0.490 (val F1=0.2651)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.38944 | val 1.29293
  Epoch 011 - train 0.33743 | val 1.31703
  Classification -> best τ=0.665 (val F1=0.1978)
  Directional -> Accuracy: 0.3830, MCC: -0.1090, F1: 0.2162

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.43412 | val 1.27617
  Epoch 012 - train 0.37523 | val 1.33740
  Classification -> best τ=0.560 (val F1=0.1925)
  Directional -> Accuracy: 0.4923, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.42563 | val 0.84374
  Epoch 015 - train 0.26387 | val 1.05789
  Classification -> best τ=0.495 (val F1=0.4074)
  Directional -> Accuracy: 0.5789, MCC: 0.1141, F1: 0.6757

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.46263 | val 0.88473
  Epoch 012 - train 0.39535 | val 1.25939
  Classification -> best τ=0.505 (val F1=0.1874)
  Directional -> Accuracy: 0.4923, MCC: -0.0220, F1: 0.4407

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.38891 | val 1.54197
  Epoch 014 - train 0.24493 | val 1.77461
  Classification -> best τ=0.555 (val F1=0.4543)
  Directional -> Accuracy: 0.5636, MCC: 0.2170, F1: 0.4286

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.28231 | val 0.95818
  Epoch 011 - train 0.25288 | val 0.92654
  Classification -> best τ=0.560 (val F1=0.1048)
  Directional -> Accuracy: 0.4222, MCC: -0.2769, F1: 0.1333

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.45242 | val 0.69162
  Epoch 015 - train 0.32541 | val 0.81586
  Classification -> best τ=0.610 (val F1=0.3712)
  Directional -> Accuracy: 0.5238, MCC: 0.1021, F1: 0.4737

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.39078 | val 1.30489
  Epoch 013 - train 0.32830 | val 1.48823
  Classification -> best τ=0.465 (val F1=0.2371)
  Directional -> Accuracy: 0.5179, MCC: 0.0359, F1: 0.5424

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.36758 | val 1.37162
  Epoch 013 - train 0.31933 | val 1.31744
  Classification -> best τ=0.465 (val F1=0.4099)
  Directional -> Accuracy: 0.5500, MCC: 0.0422, F1: 0.6786

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.40376 | val 1.71923
  Epoch 012 - train 0.33418 | val 1.99574
  Classification -> best τ=0.550 (val F1=0.3501)
  Directional -> Accuracy: 0.5000, MCC: 0.0046, F1: 0.5116

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.45184 | val 2.22565
  Epoch 011 - train 0.36261 | val 2.40819
  Classification -> best τ=0.520 (val F1=0.2697)
  Directional -> Accuracy: 0.4524, MCC: -0.1105, F1: 0.5106

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.37889 | val 1.89067
  Epoch 011 - train 0.39007 | val 2.04763
  Classification -> best τ=0.435 (val F1=0.2150)
  Directional -> Accuracy: 0.5918, MCC: 0.2233, F1: 0.7143

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.56041 | val 0.79799
  Epoch 012 - train 0.43394 | val 0.95932
  Classification -> best τ=0.465 (val F1=0.1442)
  Directional -> Accuracy: 0.5556, MCC: 0.0000, F1: 0.7143

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.34795 | val 1.51078
  Epoch 012 - train 0.29002 | val 1.51294
  Classification -> best τ=0.440 (val F1=0.4228)
  Directional -> Accuracy: 0.5349, MCC: 0.0691, F1: 0.3333

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.54891 | val 1.09313
  Epoch 013 - train 0.43257 | val 1.09197
  Classification -> best τ=0.330 (val F1=0.3254)
  Directional -> Accuracy: 0.6818, MCC: 0.3357, F1: 0.7586

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.29664 | val 1.70312
  Epoch 013 - train 0.26892 | val 2.34166
  Classification -> best τ=0.520 (val F1=0.3287)
  Directional -> Accuracy: 0.7143, MCC: 0.4318, F1: 0.7143

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.39238 | val 1.08023
  Epoch 011 - train 0.36978 | val 1.24496
  Classification -> best τ=0.535 (val F1=0.2478)
  Directional -> Accuracy: 0.5893, MCC: 0.1664, F1: 0.5106

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.35379 | val 0.91987
  Epoch 013 - train 0.22738 | val 1.69859
  Classification -> best τ=0.510 (val F1=0.3024)
  Directional -> Accuracy: 0.3913, MCC: -0.1022, F1: 0.2222

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.36888 | val 0.65824
  Epoch 019 - train 0.13985 | val 1.25714
  Classification -> best τ=0.590 (val F1=0.3887)
  Directional -> Accuracy: 0.3333, MCC: -0.1970, F1: 0.5000

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.41511 | val 1.36005
  Epoch 011 - train 0.37938 | val 1.69671
  Classification -> best τ=0.440 (val F1=0.2218)
  Directional -> Accuracy: 0.5811, MCC: 0.1661, F1: 0.5974

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.46457 | val 1.17557
  Epoch 012 - train 0.38652 | val 1.15361
  Classification -> best τ=0.390 (val F1=0.1512)
  Directional -> Accuracy: 0.5111, MCC: 0.0000, F1: 0.6765

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.28628 | val 0.89379
  Epoch 014 - train 0.14982 | val 1.07010
  Classification -> best τ=0.320 (val F1=0.3015)
  Directional -> Accuracy: 0.6190, MCC: 0.1978, F1: 0.7037

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.30953 | val 0.70829
  Epoch 016 - train 0.12572 | val 1.15800
  Classification -> best τ=0.585 (val F1=0.4371)
  Directional -> Accuracy: 0.5833, MCC: 0.1943, F1: 0.5455

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.45325 | val 0.82550
  Epoch 012 - train 0.39848 | val 0.88701
  Classification -> best τ=0.600 (val F1=0.2036)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.41431 | val 1.18018
  Epoch 012 - train 0.29496 | val 1.69318
  Classification -> best τ=0.605 (val F1=0.3570)
  Directional -> Accuracy: 0.5536, MCC: 0.1012, F1: 0.4681

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.42095 | val 1.24521
  Epoch 012 - train 0.38954 | val 1.75775
  Classification -> best τ=0.540 (val F1=0.1942)
  Directional -> Accuracy: 0.4906, MCC: -0.0275, F1: 0.5714

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.40542 | val 1.40680
  Epoch 011 - train 0.34444 | val 1.36903
  Classification -> best τ=0.550 (val F1=0.1605)
  Directional -> Accuracy: 0.4727, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.47176 | val 1.33010

[I 2026-02-22 10:53:17,091] Trial 115 finished with value: 0.27172617128857224 and parameters: {'feature_set': 'sector_emotion', 'model_type': 'BiGRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.2, 'batch_size': 64, 'learning_rate': 0.0068675083540210855, 'weight_decay': 0.00015038651458631244, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 0.9012616622748628, 'early_stopping_min_delta': 0.0006807847948594153}. Best is trial 112 with value: 0.2833506688525635.

  Epoch 012 - train 0.41581 | val 1.55881
  Classification -> best τ=0.440 (val F1=0.2623)
  Directional -> Accuracy: 0.4833, MCC: -0.0131, F1: 0.6173

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.27172617128857224
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d', 'emotion_anger', 'emotion_disgust', 'emotion_fear', 'emotion_joy', 'emotion_neutral', 'emotion_sadness', 'emotion_surprize', 'emotion_anger_pct', 'emotion_disgust_pct', 'emotion_fear_pct', 'emotion_joy_pct', 'emotion_neutral_pct', 'emotion_sadness_pct', 'emotion_surprize_pct']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.48890 | val 0.96938
  Epoch 014 - train 0.37266 | val 0.93709
  Classification -> best τ=0.560 (val F1=0.2510)
  Directional -> Accuracy: 0.6184, MCC: 0.2168, F1: 0.5246

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.35378 | val 1.06431
  Epoch 011 - train 0.34006 | val 1.23091
  Classification -> best τ=0.445 (val F1=0.1764)
  Directional -> Accuracy: 0.6000, MCC: 0.1297, F1: 0.7188

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.36952 | val 2.02577
  Epoch 013 - train 0.29827 | val 2.92539
  Classification -> best τ=0.605 (val F1=0.2164)
  Directional -> Accuracy: 0.4565, MCC: -0.1557, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.45455 | val 0.80573
  Epoch 012 - train 0.41068 | val 1.81066
  Classification -> best τ=0.465 (val F1=0.2042)
  Directional -> Accuracy: 0.4459, MCC: -0.2118, F1: 0.5941

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.34685 | val 1.57426
  Epoch 013 - train 0.28803 | val 1.44130
  Classification -> best τ=0.595 (val F1=0.2567)
  Directional -> Accuracy: 0.6000, MCC: 0.2587, F1: 0.4737

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.40835 | val 0.77683
  Epoch 011 - train 0.39686 | val 0.88038
  Classification -> best τ=0.530 (val F1=0.1684)
  Directional -> Accuracy: 0.5652, MCC: 0.1232, F1: 0.4737

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.45375 | val 1.11774
  Epoch 014 - train 0.31135 | val 1.83339
  Classification -> best τ=0.410 (val F1=0.3622)
  Directional -> Accuracy: 0.5000, MCC: 0.1034, F1: 0.5526

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.32905 | val 1.35832
  Epoch 017 - train 0.24030 | val 2.45342
  Classification -> best τ=0.480 (val F1=0.5614)
  Directional -> Accuracy: 0.3571, MCC: -0.2582, F1: 0.4906

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.36968 | val 1.25085
  Epoch 015 - train 0.18309 | val 1.36532
  Classification -> best τ=0.650 (val F1=0.3433)
  Directional -> Accuracy: 0.5833, MCC: 0.1372, F1: 0.4737

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.41349 | val 0.94419
  Epoch 012 - train 0.37082 | val 0.86108
  Classification -> best τ=0.505 (val F1=0.2693)
  Directional -> Accuracy: 0.4493, MCC: -0.0475, F1: 0.5000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.45114 | val 1.65659
  Epoch 012 - train 0.36318 | val 2.15208
  Classification -> best τ=0.505 (val F1=0.1182)
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.44131 | val 1.62672
  Epoch 012 - train 0.36235 | val 2.13612
  Classification -> best τ=0.680 (val F1=0.0500)
  Directional -> Accuracy: 0.5088, MCC: 0.0744, F1: 0.1250

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.39843 | val 1.27560
  Epoch 011 - train 0.30987 | val 1.34421
  Classification -> best τ=0.500 (val F1=0.2176)
  Directional -> Accuracy: 0.4286, MCC: -0.1718, F1: 0.6000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.44958 | val 0.76249
  Epoch 016 - train 0.28579 | val 1.23752
  Classification -> best τ=0.455 (val F1=0.3268)
  Directional -> Accuracy: 0.5500, MCC: 0.1110, F1: 0.4255

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.40899 | val 1.16592
  Epoch 011 - train 0.37767 | val 1.10646
  Classification -> best τ=0.590 (val F1=0.2078)
  Directional -> Accuracy: 0.5490, MCC: 0.0728, F1: 0.4390

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.47197 | val 1.75860
  Epoch 013 - train 0.35308 | val 1.89436
  Classification -> best τ=0.585 (val F1=0.2904)
  Directional -> Accuracy: 0.5797, MCC: 0.1834, F1: 0.5397

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.39838 | val 1.37240
  Epoch 011 - train 0.35289 | val 1.46112
  Classification -> best τ=0.520 (val F1=0.2046)
  Directional -> Accuracy: 0.4310, MCC: -0.2692, F1: 0.5714

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.47584 | val 1.14224
  Epoch 011 - train 0.41004 | val 1.34795
  Classification -> best τ=0.520 (val F1=0.2220)
  Directional -> Accuracy: 0.4000, MCC: -0.1147, F1: 0.2857

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.54871 | val 1.46058
  Epoch 015 - train 0.29676 | val 1.47019
  Classification -> best τ=0.570 (val F1=0.3601)
  Directional -> Accuracy: 0.4375, MCC: -0.0593, F1: 0.3333

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.48347 | val 0.75734
  Epoch 015 - train 0.38819 | val 0.86232
  Classification -> best τ=0.360 (val F1=0.2699)
  Directional -> Accuracy: 0.4324, MCC: -0.1359, F1: 0.4615

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.37194 | val 1.15671
  Epoch 011 - train 0.31781 | val 1.30499
  Classification -> best τ=0.595 (val F1=0.1978)
  Directional -> Accuracy: 0.4255, MCC: 0.0074, F1: 0.2703

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.40225 | val 1.35378
  Epoch 013 - train 0.24857 | val 1.57776
  Classification -> best τ=0.395 (val F1=0.2673)
  Directional -> Accuracy: 0.6308, MCC: 0.2855, F1: 0.5556

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.48335 | val 0.99558
  Epoch 014 - train 0.31868 | val 1.17859
  Classification -> best τ=0.490 (val F1=0.4055)
  Directional -> Accuracy: 0.5614, MCC: 0.0424, F1: 0.6988

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.47801 | val 0.90664
  Epoch 012 - train 0.39365 | val 0.84872
  Classification -> best τ=0.420 (val F1=0.2826)
  Directional -> Accuracy: 0.5077, MCC: 0.0190, F1: 0.5152

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.41871 | val 1.29969
  Epoch 012 - train 0.30942 | val 1.67279
  Classification -> best τ=0.505 (val F1=0.3512)
  Directional -> Accuracy: 0.5455, MCC: 0.1491, F1: 0.4444

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.22694 | val 1.29347
  Epoch 012 - train 0.17095 | val 1.12590
  Classification -> best τ=0.590 (val F1=0.0524)
  Directional -> Accuracy: 0.4222, MCC: -0.2021, F1: 0.2778

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.41313 | val 0.73873
  Epoch 014 - train 0.30050 | val 0.87714
  Classification -> best τ=0.575 (val F1=0.4404)
  Directional -> Accuracy: 0.5000, MCC: 0.0782, F1: 0.4000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.36778 | val 1.21188
  Epoch 012 - train 0.36037 | val 1.61345
  Classification -> best τ=0.380 (val F1=0.1997)
  Directional -> Accuracy: 0.5000, MCC: -0.2137, F1: 0.6667

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.39494 | val 0.78048
  Epoch 012 - train 0.36861 | val 0.87710
  Classification -> best τ=0.550 (val F1=0.2267)
  Directional -> Accuracy: 0.5250, MCC: -0.1448, F1: 0.6885

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.38504 | val 1.74588
  Epoch 012 - train 0.31064 | val 2.54267
  Classification -> best τ=0.600 (val F1=0.3001)
  Directional -> Accuracy: 0.4762, MCC: -0.0550, F1: 0.4211

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.40470 | val 1.47981
  Epoch 011 - train 0.40413 | val 1.53425
  Classification -> best τ=0.355 (val F1=0.1124)
  Directional -> Accuracy: 0.5476, MCC: 0.0000, F1: 0.7077

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.40652 | val 2.24013
  Epoch 014 - train 0.26963 | val 2.30174
  Classification -> best τ=0.700 (val F1=0.3574)
  Directional -> Accuracy: 0.4082, MCC: -0.1747, F1: 0.3556

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.53593 | val 1.23885
  Epoch 012 - train 0.42735 | val 1.22602
  Classification -> best τ=0.580 (val F1=0.1838)
  Directional -> Accuracy: 0.4444, MCC: 0.0000, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.43444 | val 1.39825
  Epoch 012 - train 0.36893 | val 1.45351
  Classification -> best τ=0.390 (val F1=0.1734)
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.61800 | val 1.28917
  Epoch 011 - train 0.52119 | val 1.00728
  Classification -> best τ=0.530 (val F1=0.2169)
  Directional -> Accuracy: 0.5000, MCC: 0.0283, F1: 0.4923

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.32878 | val 1.33349
  Epoch 014 - train 0.25237 | val 1.66076
  Classification -> best τ=0.545 (val F1=0.3260)
  Directional -> Accuracy: 0.6905, MCC: 0.3977, F1: 0.6667

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.44109 | val 1.22552
  Epoch 011 - train 0.37956 | val 1.38540
  Classification -> best τ=0.480 (val F1=0.2382)
  Directional -> Accuracy: 0.5714, MCC: 0.1708, F1: 0.6129

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.29775 | val 0.99057
  Epoch 013 - train 0.21659 | val 1.27949
  Classification -> best τ=0.540 (val F1=0.3294)
  Directional -> Accuracy: 0.3913, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.36444 | val 0.68380
  Epoch 019 - train 0.10340 | val 1.53457
  Classification -> best τ=0.260 (val F1=0.3284)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.47506 | val 1.63316
  Epoch 011 - train 0.39108 | val 1.60563
  Classification -> best τ=0.345 (val F1=0.2397)
  Directional -> Accuracy: 0.4865, MCC: 0.0000, F1: 0.6545

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.47965 | val 0.72196
  Epoch 017 - train 0.26430 | val 0.96023
  Classification -> best τ=0.340 (val F1=0.2169)
  Directional -> Accuracy: 0.4889, MCC: -0.1474, F1: 0.6567

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.25731 | val 0.91160
  Epoch 013 - train 0.21890 | val 1.05668
  Classification -> best τ=0.510 (val F1=0.3151)
  Directional -> Accuracy: 0.4048, MCC: -0.1487, F1: 0.3243

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.35504 | val 0.61115
  Epoch 020 - train 0.08379 | val 0.70420
  Epoch 025 - train 0.09868 | val 1.12467
  Classification -> best τ=0.740 (val F1=0.5263)
  Directional -> Accuracy: 0.5625, MCC: 0.1870, F1: 0.5532

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.41028 | val 1.25845
  Epoch 014 - train 0.28385 | val 1.88505
  Classification -> best τ=0.680 (val F1=0.2114)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.33506 | val 1.24528
  Epoch 014 - train 0.22183 | val 1.84438
  Classification -> best τ=0.350 (val F1=0.3236)
  Directional -> Accuracy: 0.5179, MCC: 0.1032, F1: 0.6494

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.42493 | val 1.24497
  Epoch 012 - train 0.32256 | val 1.32663
  Classification -> best τ=0.480 (val F1=0.2521)
  Directional -> Accuracy: 0.5472, MCC: 0.1259, F1: 0.6757

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.40410 | val 1.03664
  Epoch 013 - train 0.33447 | val 1.27791
  Classification -> best τ=0.425 (val F1=0.2114)
  Directional -> Accuracy: 0.5273, MCC: 0.0000, F1: 0.6905

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.50317 | val 0.71261

[I 2026-02-22 10:54:37,432] Trial 116 finished with value: 0.2630144204572137 and parameters: {'feature_set': 'sector_emotion', 'model_type': 'BiGRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.2, 'batch_size': 64, 'learning_rate': 0.006957079373905818, 'weight_decay': 0.0002107882985977529, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 0.6699351857105252, 'early_stopping_min_delta': 0.0007200093200018722}. Best is trial 112 with value: 0.2833506688525635.

  Epoch 015 - train 0.32655 | val 0.70796
  Classification -> best τ=0.555 (val F1=0.2623)
  Directional -> Accuracy: 0.5000, MCC: -0.0689, F1: 0.0625

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2630144204572137
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d', 'emotion_anger', 'emotion_disgust', 'emotion_fear', 'emotion_joy', 'emotion_neutral', 'emotion_sadness', 'emotion_surprize', 'emotion_anger_pct', 'emotion_disgust_pct', 'emotion_fear_pct', 'emotion_joy_pct', 'emotion_neutral_pct', 'emotion_sadness_pct', 'emotion_surprize_pct']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.45511 | val 0.77436
  Epoch 014 - train 0.40289 | val 0.99212
  Classification -> best τ=0.540 (val F1=0.2200)
  Directional -> Accuracy: 0.5395, MCC: -0.0022, F1: 0.1860

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.40218 | val 0.97583
  Epoch 011 - train 0.34348 | val 0.93151
  Classification -> best τ=0.430 (val F1=0.2285)
  Directional -> Accuracy: 0.5778, MCC: 0.0000, F1: 0.7324

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.40048 | val 1.69402
  Epoch 011 - train 0.38819 | val 1.92471
  Classification -> best τ=0.610 (val F1=0.1383)
  Directional -> Accuracy: 0.4783, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.51787 | val 1.22384
  Epoch 012 - train 0.42289 | val 1.56222
  Classification -> best τ=0.400 (val F1=0.2228)
  Directional -> Accuracy: 0.5000, MCC: -0.1895, F1: 0.6667

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.40319 | val 1.10697
  Epoch 013 - train 0.30795 | val 1.42619
  Classification -> best τ=0.515 (val F1=0.3984)
  Directional -> Accuracy: 0.6000, MCC: 0.2202, F1: 0.5455

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.36675 | val 0.70780
  Epoch 011 - train 0.35914 | val 0.75538
  Classification -> best τ=0.500 (val F1=0.1808)
  Directional -> Accuracy: 0.5000, MCC: -0.0038, F1: 0.4651

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.43479 | val 1.84144
  Epoch 011 - train 0.42747 | val 1.79792
  Classification -> best τ=0.420 (val F1=0.2242)
  Directional -> Accuracy: 0.5294, MCC: 0.1704, F1: 0.5789

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.38802 | val 0.67087
  Epoch 013 - train 0.33303 | val 1.41474
  Classification -> best τ=0.365 (val F1=0.4453)
  Directional -> Accuracy: 0.4524, MCC: -0.0574, F1: 0.4889

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.39795 | val 1.47503
  Epoch 012 - train 0.35614 | val 1.61223
  Classification -> best τ=0.560 (val F1=0.2771)
  Directional -> Accuracy: 0.5625, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.42838 | val 1.27046
  Epoch 013 - train 0.29522 | val 1.30173
  Classification -> best τ=0.415 (val F1=0.1858)
  Directional -> Accuracy: 0.4058, MCC: -0.1029, F1: 0.5495

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.42196 | val 1.70753
  Epoch 012 - train 0.36680 | val 1.43063
  Classification -> best τ=0.510 (val F1=0.2484)
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.38885 | val 2.02960
  Epoch 011 - train 0.42665 | val 2.07421
  Classification -> best τ=0.525 (val F1=0.1313)
  Directional -> Accuracy: 0.5965, MCC: 0.1933, F1: 0.5965

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.36536 | val 1.31524
  Epoch 011 - train 0.36732 | val 1.51882
  Classification -> best τ=0.560 (val F1=0.0059)
  Directional -> Accuracy: 0.2619, MCC: -0.4691, F1: 0.3111

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.45045 | val 0.68853
  Epoch 012 - train 0.40571 | val 0.71463
  Classification -> best τ=0.480 (val F1=0.3864)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.44951 | val 0.94956
  Epoch 013 - train 0.36173 | val 1.14819
  Classification -> best τ=0.525 (val F1=0.1493)
  Directional -> Accuracy: 0.5882, MCC: 0.1508, F1: 0.3226

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.44074 | val 1.41419
  Epoch 012 - train 0.44916 | val 1.75157
  Classification -> best τ=0.305 (val F1=0.2659)
  Directional -> Accuracy: 0.5217, MCC: -0.1128, F1: 0.6857

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.46484 | val 0.94744
  Epoch 011 - train 0.40897 | val 1.02247
  Classification -> best τ=0.540 (val F1=0.2651)
  Directional -> Accuracy: 0.3793, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.49198 | val 1.20103
  Epoch 012 - train 0.39408 | val 1.66518
  Classification -> best τ=0.600 (val F1=0.1548)
  Directional -> Accuracy: 0.4267, MCC: -0.0915, F1: 0.3944

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.45503 | val 0.83073
  Epoch 013 - train 0.36590 | val 1.15450
  Classification -> best τ=0.585 (val F1=0.2868)
  Directional -> Accuracy: 0.4688, MCC: 0.0966, F1: 0.2273

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.44657 | val 0.98527
  Epoch 012 - train 0.40597 | val 1.08815
  Classification -> best τ=0.525 (val F1=0.2230)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.35403 | val 0.90393
  Epoch 014 - train 0.25927 | val 1.06722
  Classification -> best τ=0.490 (val F1=0.3512)
  Directional -> Accuracy: 0.3617, MCC: -0.1524, F1: 0.0625

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.46628 | val 0.97602
  Epoch 011 - train 0.43806 | val 0.99751
  Classification -> best τ=0.495 (val F1=0.1925)
  Directional -> Accuracy: 0.4769, MCC: -0.0767, F1: 0.0556

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.41731 | val 0.86246
  Epoch 015 - train 0.26212 | val 1.10813
  Classification -> best τ=0.330 (val F1=0.3944)
  Directional -> Accuracy: 0.5614, MCC: 0.0000, F1: 0.7191

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.42409 | val 0.83028
  Epoch 012 - train 0.40727 | val 0.95681
  Classification -> best τ=0.465 (val F1=0.1243)
  Directional -> Accuracy: 0.5231, MCC: 0.0844, F1: 0.6173

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.37774 | val 1.27155
  Epoch 013 - train 0.26715 | val 1.77990
  Classification -> best τ=0.400 (val F1=0.3887)
  Directional -> Accuracy: 0.6000, MCC: 0.2346, F1: 0.5600

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.22731 | val 0.98896
  Epoch 011 - train 0.18074 | val 0.99873
  Classification -> best τ=0.525 (val F1=0.1981)
  Directional -> Accuracy: 0.4222, MCC: -0.1540, F1: 0.3810

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.37337 | val 0.83555
  Epoch 015 - train 0.19383 | val 1.21861
  Classification -> best τ=0.605 (val F1=0.3536)
  Directional -> Accuracy: 0.4048, MCC: -0.1334, F1: 0.0741

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.45320 | val 1.17559
  Epoch 012 - train 0.39605 | val 1.19129
  Classification -> best τ=0.455 (val F1=0.0132)
  Directional -> Accuracy: 0.5536, MCC: 0.0000, F1: 0.7126

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.37287 | val 1.88157
  Epoch 012 - train 0.33803 | val 1.90462
  Classification -> best τ=0.475 (val F1=0.3380)
  Directional -> Accuracy: 0.5250, MCC: 0.0356, F1: 0.5778

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.34033 | val 1.29939
  Epoch 012 - train 0.29878 | val 1.67986
  Classification -> best τ=0.580 (val F1=0.2814)
  Directional -> Accuracy: 0.5000, MCC: -0.0092, F1: 0.4324

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.45162 | val 1.97535
  Epoch 012 - train 0.37175 | val 2.12663
  Classification -> best τ=0.490 (val F1=0.1286)
  Directional -> Accuracy: 0.3333, MCC: -0.4045, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.37558 | val 1.30842
  Epoch 011 - train 0.37944 | val 1.41100
  Classification -> best τ=0.510 (val F1=0.2969)
  Directional -> Accuracy: 0.4286, MCC: -0.1701, F1: 0.5172

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.49494 | val 0.77362
  Epoch 012 - train 0.39865 | val 0.86931
  Classification -> best τ=0.505 (val F1=0.1693)
  Directional -> Accuracy: 0.5278, MCC: -0.0949, F1: 0.6852

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.40210 | val 1.21540
  Epoch 011 - train 0.38447 | val 1.40983
  Classification -> best τ=0.575 (val F1=0.3227)
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.48690 | val 1.07162
  Epoch 011 - train 0.46941 | val 1.07357
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5758, MCC: 0.0000, F1: 0.7308

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.30376 | val 1.26792
  Epoch 011 - train 0.23473 | val 1.45834
  Classification -> best τ=0.530 (val F1=0.3420)
  Directional -> Accuracy: 0.6429, MCC: 0.3127, F1: 0.5946

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.35973 | val 2.01106
  Epoch 011 - train 0.34320 | val 2.36984
  Classification -> best τ=0.460 (val F1=0.2026)
  Directional -> Accuracy: 0.5536, MCC: 0.2124, F1: 0.6575

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.30873 | val 0.77122
  Epoch 016 - train 0.17068 | val 1.19007
  Classification -> best τ=0.485 (val F1=0.3218)
  Directional -> Accuracy: 0.4783, MCC: -0.0952, F1: 0.5714

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.39953 | val 0.74344
  Epoch 012 - train 0.32143 | val 0.76247
  Classification -> best τ=0.485 (val F1=0.3090)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.41310 | val 2.07900
  Epoch 012 - train 0.33933 | val 2.62977
  Classification -> best τ=0.520 (val F1=0.2600)
  Directional -> Accuracy: 0.4865, MCC: 0.0000, F1: 0.6545

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.44116 | val 0.91740
  Epoch 011 - train 0.39300 | val 1.01379
  Classification -> best τ=0.445 (val F1=0.3287)
  Directional -> Accuracy: 0.4889, MCC: -0.0518, F1: 0.6230

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.36153 | val 0.79996
  Epoch 012 - train 0.25559 | val 0.77851
  Classification -> best τ=0.475 (val F1=0.3563)
  Directional -> Accuracy: 0.5952, MCC: 0.1340, F1: 0.7018

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.38899 | val 0.70824
  Epoch 017 - train 0.13605 | val 1.05306
  Classification -> best τ=0.535 (val F1=0.3410)
  Directional -> Accuracy: 0.4167, MCC: 0.0778, F1: 0.5484

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.47206 | val 1.09095
  Epoch 013 - train 0.38891 | val 1.16142
  Classification -> best τ=0.720 (val F1=0.2036)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.36303 | val 1.59099
  Epoch 012 - train 0.29511 | val 1.22193
  Classification -> best τ=0.465 (val F1=0.2952)
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.6506

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.44382 | val 1.06121
  Epoch 011 - train 0.37717 | val 1.13259
  Classification -> best τ=0.510 (val F1=0.2305)
  Directional -> Accuracy: 0.5472, MCC: 0.0969, F1: 0.6364

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.38717 | val 1.10254
  Epoch 011 - train 0.37289 | val 1.17059
  Classification -> best τ=0.480 (val F1=0.2681)
  Directional -> Accuracy: 0.5273, MCC: 0.0000, F1: 0.6905

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.45508 | val 0.67377

[I 2026-02-22 10:55:54,839] Trial 117 finished with value: 0.2497092529329116 and parameters: {'feature_set': 'sector_emotion', 'model_type': 'BiGRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.2, 'batch_size': 64, 'learning_rate': 0.0056879403916319975, 'weight_decay': 0.00016570347777704984, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 0.857620340551404, 'early_stopping_min_delta': 0.001050861922050185}. Best is trial 112 with value: 0.2833506688525635.

  Epoch 020 - train 0.21476 | val 1.46205
  Classification -> best τ=0.400 (val F1=0.3363)
  Directional -> Accuracy: 0.5333, MCC: 0.0704, F1: 0.1765

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2497092529329116
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d', 'emotion_anger', 'emotion_disgust', 'emotion_fear', 'emotion_joy', 'emotion_neutral', 'emotion_sadness', 'emotion_surprize', 'emotion_anger_pct', 'emotion_disgust_pct', 'emotion_fear_pct', 'emotion_joy_pct', 'emotion_neutral_pct', 'emotion_sadness_pct', 'emotion_surprize_pct']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.47378 | val 0.66566
  Epoch 015 - train 0.38279 | val 1.26193
  Classification -> best τ=0.495 (val F1=0.2036)
  Directional -> Accuracy: 0.5658, MCC: 0.0886, F1: 0.3529

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.41488 | val 0.82572
  Epoch 012 - train 0.31107 | val 0.89390
  Classification -> best τ=0.470 (val F1=0.2523)
  Directional -> Accuracy: 0.5556, MCC: 0.1308, F1: 0.5652

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.40810 | val 1.56670
  Epoch 012 - train 0.32367 | val 1.97836
  Classification -> best τ=0.430 (val F1=0.2309)
  Directional -> Accuracy: 0.6087, MCC: 0.2159, F1: 0.6250

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.51277 | val 2.47459
  Epoch 012 - train 0.42205 | val 1.88799
  Classification -> best τ=0.530 (val F1=0.1079)
  Directional -> Accuracy: 0.4459, MCC: -0.1042, F1: 0.4533

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.37495 | val 1.10875
  Epoch 013 - train 0.25009 | val 1.31977
  Classification -> best τ=0.555 (val F1=0.2934)
  Directional -> Accuracy: 0.6200, MCC: 0.3170, F1: 0.4865

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.45455 | val 0.81876
  Epoch 015 - train 0.31085 | val 1.12537
  Classification -> best τ=0.465 (val F1=0.2593)
  Directional -> Accuracy: 0.4565, MCC: -0.0790, F1: 0.5902

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.44301 | val 1.42168
  Epoch 012 - train 0.37258 | val 1.97853
  Classification -> best τ=0.495 (val F1=0.2766)
  Directional -> Accuracy: 0.5000, MCC: 0.0313, F1: 0.4848

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.38325 | val 0.79609
  Epoch 013 - train 0.27545 | val 0.94189
  Classification -> best τ=0.360 (val F1=0.6571)
  Directional -> Accuracy: 0.5714, MCC: 0.0323, F1: 0.1000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.43954 | val 1.15560
  Epoch 012 - train 0.35021 | val 1.18518
  Classification -> best τ=0.465 (val F1=0.1411)
  Directional -> Accuracy: 0.5625, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.41398 | val 0.87183
  Epoch 012 - train 0.39686 | val 0.85618
  Classification -> best τ=0.545 (val F1=0.1983)
  Directional -> Accuracy: 0.5507, MCC: 0.0385, F1: 0.3673

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.41322 | val 1.03243
  Epoch 011 - train 0.37146 | val 1.09747
  Classification -> best τ=0.535 (val F1=0.1593)
  Directional -> Accuracy: 0.5918, MCC: 0.1804, F1: 0.2308

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.49856 | val 1.74699
  Epoch 012 - train 0.43140 | val 1.73189
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5088, MCC: 0.0000, F1: 0.6744

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.44668 | val 1.86685
  Epoch 011 - train 0.35196 | val 1.76963
  Classification -> best τ=0.460 (val F1=0.1878)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.6230

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.38972 | val 0.89981
  Epoch 014 - train 0.30884 | val 0.96202
  Classification -> best τ=0.620 (val F1=0.3126)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.41186 | val 0.98568
  Epoch 011 - train 0.39093 | val 1.03681
  Classification -> best τ=0.375 (val F1=0.1925)
  Directional -> Accuracy: 0.4706, MCC: 0.0338, F1: 0.6087

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.54143 | val 0.95822
  Epoch 014 - train 0.33587 | val 1.11998
  Classification -> best τ=0.205 (val F1=0.3094)
  Directional -> Accuracy: 0.5797, MCC: 0.2293, F1: 0.7184

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.44196 | val 1.02249
  Epoch 011 - train 0.42134 | val 1.05246
  Classification -> best τ=0.590 (val F1=0.1842)
  Directional -> Accuracy: 0.4483, MCC: -0.2749, F1: 0.6000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.52282 | val 1.13614
  Epoch 011 - train 0.48122 | val 1.34756
  Classification -> best τ=0.455 (val F1=0.1769)
  Directional -> Accuracy: 0.6000, MCC: 0.0000, F1: 0.7500

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.52068 | val 1.39946
  Epoch 011 - train 0.40570 | val 1.11637
  Classification -> best τ=0.380 (val F1=0.3140)
  Directional -> Accuracy: 0.6094, MCC: 0.1555, F1: 0.7312

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.51924 | val 0.82619
  Epoch 013 - train 0.42293 | val 0.96740
  Classification -> best τ=0.480 (val F1=0.2597)
  Directional -> Accuracy: 0.4595, MCC: 0.1050, F1: 0.0476

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.42092 | val 1.17247
  Epoch 011 - train 0.38523 | val 1.25131
  Classification -> best τ=0.620 (val F1=0.2727)
  Directional -> Accuracy: 0.4043, MCC: -0.0615, F1: 0.2632

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.51731 | val 0.93353
  Epoch 012 - train 0.37552 | val 1.05674
  Classification -> best τ=0.565 (val F1=0.3148)
  Directional -> Accuracy: 0.5231, MCC: 0.0720, F1: 0.3111

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.45811 | val 0.86747
  Epoch 016 - train 0.25757 | val 1.00815
  Classification -> best τ=0.625 (val F1=0.4845)
  Directional -> Accuracy: 0.6140, MCC: 0.2045, F1: 0.6765

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.46413 | val 0.85672
  Epoch 015 - train 0.29236 | val 0.80664
  Classification -> best τ=0.515 (val F1=0.1415)
  Directional -> Accuracy: 0.5231, MCC: 0.0515, F1: 0.5373

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.38055 | val 1.24700
  Epoch 014 - train 0.31072 | val 1.67399
  Classification -> best τ=0.325 (val F1=0.4068)
  Directional -> Accuracy: 0.6000, MCC: 0.2476, F1: 0.5417

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.29943 | val 0.98256
  Epoch 011 - train 0.23318 | val 1.04339
  Classification -> best τ=0.515 (val F1=0.3039)
  Directional -> Accuracy: 0.4444, MCC: -0.0055, F1: 0.5614

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.43989 | val 0.82063
  Epoch 013 - train 0.32851 | val 1.03749
  Classification -> best τ=0.630 (val F1=0.3873)
  Directional -> Accuracy: 0.4762, MCC: 0.0786, F1: 0.2667

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.45342 | val 1.32508
  Epoch 012 - train 0.36610 | val 1.42324
  Classification -> best τ=0.405 (val F1=0.1387)
  Directional -> Accuracy: 0.5179, MCC: 0.0909, F1: 0.4255

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.38191 | val 0.88185
  Epoch 012 - train 0.33755 | val 1.30406
  Classification -> best τ=0.510 (val F1=0.2957)
  Directional -> Accuracy: 0.6000, MCC: 0.1759, F1: 0.7037

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.43824 | val 1.32616
  Epoch 012 - train 0.38089 | val 1.66405
  Classification -> best τ=0.555 (val F1=0.4110)
  Directional -> Accuracy: 0.5238, MCC: 0.0413, F1: 0.4737

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.56952 | val 1.14287
  Epoch 011 - train 0.48009 | val 1.30005
  Classification -> best τ=0.475 (val F1=0.2646)
  Directional -> Accuracy: 0.5714, MCC: 0.1435, F1: 0.5909

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.40947 | val 1.67507
  Epoch 011 - train 0.38279 | val 1.88074
  Classification -> best τ=0.415 (val F1=0.3432)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.46680 | val 0.83867
  Epoch 016 - train 0.28219 | val 0.87002
  Classification -> best τ=0.625 (val F1=0.3560)
  Directional -> Accuracy: 0.4444, MCC: 0.0000, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.42713 | val 1.18083
  Epoch 011 - train 0.36387 | val 1.26075
  Classification -> best τ=0.380 (val F1=0.2324)
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.52710 | val 1.17563
  Epoch 011 - train 0.46031 | val 1.09072
  Classification -> best τ=0.510 (val F1=0.0794)
  Directional -> Accuracy: 0.5606, MCC: -0.1065, F1: 0.7184

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.29036 | val 1.22735
  Epoch 014 - train 0.15229 | val 2.16604
  Classification -> best τ=0.540 (val F1=0.1822)
  Directional -> Accuracy: 0.6190, MCC: 0.2571, F1: 0.5789

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.42231 | val 1.22559
  Epoch 011 - train 0.36932 | val 1.59178
  Classification -> best τ=0.390 (val F1=0.2450)
  Directional -> Accuracy: 0.5893, MCC: 0.2397, F1: 0.6567

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.40195 | val 0.91662
  Epoch 011 - train 0.35947 | val 1.00120
  Classification -> best τ=0.535 (val F1=0.3508)
  Directional -> Accuracy: 0.6087, MCC: 0.0863, F1: 0.7353

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.38228 | val 0.81809
  Epoch 015 - train 0.23423 | val 0.94824
  Classification -> best τ=0.640 (val F1=0.4011)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.45103 | val 1.51801
  Epoch 012 - train 0.36707 | val 1.73622
  Classification -> best τ=0.505 (val F1=0.2810)
  Directional -> Accuracy: 0.4865, MCC: 0.0000, F1: 0.6545

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.43488 | val 0.78222
  Epoch 015 - train 0.26694 | val 1.01106
  Classification -> best τ=0.530 (val F1=0.2712)
  Directional -> Accuracy: 0.5111, MCC: 0.0629, F1: 0.2143

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.32945 | val 0.81498
  Epoch 013 - train 0.18773 | val 0.96288
  Classification -> best τ=0.350 (val F1=0.3563)
  Directional -> Accuracy: 0.5238, MCC: -0.1171, F1: 0.6774

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.35573 | val 0.68546
  Epoch 020 - train 0.08646 | val 1.17341
  Epoch 021 - train 0.07908 | val 1.29290
  Classification -> best τ=0.505 (val F1=0.3410)
  Directional -> Accuracy: 0.3958, MCC: 0.0222, F1: 0.5397

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.48289 | val 1.31610
  Epoch 013 - train 0.39885 | val 1.52997
  Classification -> best τ=0.680 (val F1=0.2374)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.35720 | val 1.58977
  Epoch 011 - train 0.33929 | val 1.85089
  Classification -> best τ=0.475 (val F1=0.3526)
  Directional -> Accuracy: 0.5000, MCC: -0.0013, F1: 0.4815

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.40428 | val 1.44289
  Epoch 011 - train 0.34552 | val 1.65334
  Classification -> best τ=0.460 (val F1=0.1942)
  Directional -> Accuracy: 0.5283, MCC: 0.0631, F1: 0.6575

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.41789 | val 0.90748
  Epoch 020 - train 0.17304 | val 1.05228
  Epoch 021 - train 0.16551 | val 1.57180
  Classification -> best τ=0.275 (val F1=0.4110)
  Directional -> Accuracy: 0.5091, MCC: -0.0074, F1: 0.6087

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.48200 | val 0.71127

[I 2026-02-22 10:57:13,914] Trial 118 finished with value: 0.27156771330323554 and parameters: {'feature_set': 'sector_emotion', 'model_type': 'BiGRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.30000000000000004, 'batch_size': 64, 'learning_rate': 0.008620957996216658, 'weight_decay': 5.797913452050153e-05, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 0.9185689397905625, 'early_stopping_min_delta': 0.0007431684186662835}. Best is trial 112 with value: 0.2833506688525635.

  Epoch 015 - train 0.36926 | val 1.08081
  Classification -> best τ=0.520 (val F1=0.2623)
  Directional -> Accuracy: 0.5333, MCC: 0.0842, F1: 0.1250

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.27156771330323554
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d', 'emotion_anger', 'emotion_disgust', 'emotion_fear', 'emotion_joy', 'emotion_neutral', 'emotion_sadness', 'emotion_surprize', 'emotion_anger_pct', 'emotion_disgust_pct', 'emotion_fear_pct', 'emotion_joy_pct', 'emotion_neutral_pct', 'emotion_sadness_pct', 'emotion_surprize_pct']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.49922 | val 0.75479
  Epoch 016 - train 0.43237 | val 0.80116
  Classification -> best τ=0.545 (val F1=0.2036)
  Directional -> Accuracy: 0.5921, MCC: 0.1615, F1: 0.4918

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.44937 | val 0.98428
  Epoch 012 - train 0.34601 | val 0.94357
  Classification -> best τ=0.470 (val F1=0.1844)
  Directional -> Accuracy: 0.6444, MCC: 0.2538, F1: 0.7500

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.47808 | val 1.30166
  Epoch 011 - train 0.42863 | val 1.40552
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5217, MCC: 0.0000, F1: 0.6857

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.53097 | val 0.91386
  Epoch 012 - train 0.46873 | val 1.01271
  Classification -> best τ=0.390 (val F1=0.2241)
  Directional -> Accuracy: 0.4865, MCC: -0.0076, F1: 0.4412

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.49692 | val 1.08338
  Epoch 013 - train 0.31011 | val 1.15588
  Classification -> best τ=0.580 (val F1=0.2567)
  Directional -> Accuracy: 0.6000, MCC: 0.2802, F1: 0.4444

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.44395 | val 0.81687
  Epoch 011 - train 0.46380 | val 0.80618
  Classification -> best τ=0.520 (val F1=0.2241)
  Directional -> Accuracy: 0.4565, MCC: -0.0836, F1: 0.4681

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.47076 | val 1.27265
  Epoch 011 - train 0.41846 | val 1.21688
  Classification -> best τ=0.415 (val F1=0.2002)
  Directional -> Accuracy: 0.4265, MCC: 0.0165, F1: 0.5517

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.38733 | val 1.00432
  Epoch 012 - train 0.34168 | val 1.01497
  Classification -> best τ=0.295 (val F1=0.2753)
  Directional -> Accuracy: 0.4048, MCC: -0.1291, F1: 0.5283

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.40094 | val 0.77052
  Epoch 016 - train 0.24890 | val 1.24705
  Classification -> best τ=0.505 (val F1=0.4602)
  Directional -> Accuracy: 0.6250, MCC: 0.2208, F1: 0.5000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.40399 | val 0.86379
  Epoch 014 - train 0.34556 | val 0.95850
  Classification -> best τ=0.510 (val F1=0.3245)
  Directional -> Accuracy: 0.3768, MCC: -0.2197, F1: 0.3944

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.41850 | val 1.75230
  Epoch 012 - train 0.38046 | val 2.15767
  Classification -> best τ=0.455 (val F1=0.0360)
  Directional -> Accuracy: 0.5714, MCC: 0.1599, F1: 0.0870

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.46101 | val 2.26884
  Epoch 011 - train 0.42332 | val 2.30136
  Classification -> best τ=0.450 (val F1=0.1620)
  Directional -> Accuracy: 0.6842, MCC: 0.3806, F1: 0.7273

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.44571 | val 1.93247
  Epoch 013 - train 0.31541 | val 2.86160
  Classification -> best τ=0.525 (val F1=0.1387)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.6230

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.45134 | val 0.71491
  Epoch 012 - train 0.39412 | val 0.75108
  Classification -> best τ=0.445 (val F1=0.3864)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.47631 | val 1.10664
  Epoch 011 - train 0.46854 | val 1.16008
  Classification -> best τ=0.425 (val F1=0.1556)
  Directional -> Accuracy: 0.4706, MCC: -0.0572, F1: 0.4490

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.51101 | val 1.36935
  Epoch 012 - train 0.42126 | val 1.21061
  Classification -> best τ=0.630 (val F1=0.3679)
  Directional -> Accuracy: 0.5507, MCC: 0.1300, F1: 0.4918

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.46531 | val 1.12319
  Epoch 013 - train 0.36988 | val 1.32605
  Classification -> best τ=0.605 (val F1=0.2276)
  Directional -> Accuracy: 0.3966, MCC: 0.1035, F1: 0.0541

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.49389 | val 1.11505
  Epoch 011 - train 0.45460 | val 1.10596
  Classification -> best τ=0.520 (val F1=0.1007)
  Directional -> Accuracy: 0.4800, MCC: -0.1455, F1: 0.6061

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.43419 | val 0.95406
  Epoch 011 - train 0.39530 | val 0.84705
  Classification -> best τ=0.470 (val F1=0.2103)
  Directional -> Accuracy: 0.5312, MCC: 0.1003, F1: 0.5161

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.47875 | val 0.84408
  Epoch 016 - train 0.42899 | val 1.04453
  Classification -> best τ=0.450 (val F1=0.2382)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.38396 | val 0.99983
  Epoch 011 - train 0.37248 | val 1.11277
  Classification -> best τ=0.555 (val F1=0.2861)
  Directional -> Accuracy: 0.4043, MCC: -0.0392, F1: 0.2222

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.48865 | val 1.18676
  Epoch 012 - train 0.40045 | val 1.02766
  Classification -> best τ=0.540 (val F1=0.2381)
  Directional -> Accuracy: 0.4923, MCC: -0.0027, F1: 0.0571

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.43065 | val 0.91123
  Epoch 013 - train 0.43473 | val 1.10715
  Classification -> best τ=0.510 (val F1=0.3248)
  Directional -> Accuracy: 0.6316, MCC: 0.2536, F1: 0.7407

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.49256 | val 0.75259
  Epoch 011 - train 0.44422 | val 0.76237
  Classification -> best τ=0.535 (val F1=0.1565)
  Directional -> Accuracy: 0.5385, MCC: 0.0777, F1: 0.5312

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.43927 | val 1.36817
  Epoch 014 - train 0.31529 | val 1.58323
  Classification -> best τ=0.385 (val F1=0.3563)
  Directional -> Accuracy: 0.5455, MCC: 0.1491, F1: 0.4444

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.24602 | val 1.19635
  Epoch 011 - train 0.26045 | val 1.12518
  Classification -> best τ=0.395 (val F1=0.0105)
  Directional -> Accuracy: 0.4889, MCC: 0.0675, F1: 0.5660

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.42324 | val 0.68680
  Epoch 015 - train 0.33625 | val 0.85539
  Classification -> best τ=0.575 (val F1=0.4201)
  Directional -> Accuracy: 0.5238, MCC: 0.0849, F1: 0.5000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.44136 | val 1.12645
  Epoch 012 - train 0.39252 | val 1.26354
  Classification -> best τ=0.455 (val F1=0.2450)
  Directional -> Accuracy: 0.4286, MCC: -0.1502, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.40440 | val 0.84108
  Epoch 015 - train 0.24856 | val 1.07308
  Classification -> best τ=0.555 (val F1=0.3427)
  Directional -> Accuracy: 0.5500, MCC: 0.0503, F1: 0.6667

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.43594 | val 1.87913
  Epoch 012 - train 0.32128 | val 1.51441
  Classification -> best τ=0.535 (val F1=0.1959)
  Directional -> Accuracy: 0.5476, MCC: 0.1137, F1: 0.5957

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.44736 | val 1.00574
  Epoch 011 - train 0.39121 | val 1.03008
  Classification -> best τ=0.540 (val F1=0.1286)
  Directional -> Accuracy: 0.4762, MCC: 0.0387, F1: 0.2143

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.46542 | val 1.43440
  Epoch 012 - train 0.34971 | val 1.84645
  Classification -> best τ=0.290 (val F1=0.2884)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.58343 | val 0.70994
  Epoch 016 - train 0.32046 | val 0.91665
  Classification -> best τ=0.230 (val F1=0.3131)
  Directional -> Accuracy: 0.5694, MCC: 0.0855, F1: 0.7103

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.40605 | val 0.85210
  Epoch 013 - train 0.31228 | val 1.22468
  Classification -> best τ=0.655 (val F1=0.2603)
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.56371 | val 1.03930
  Epoch 011 - train 0.46895 | val 0.94005
  Classification -> best τ=0.385 (val F1=0.2518)
  Directional -> Accuracy: 0.5909, MCC: 0.1070, F1: 0.7327

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.32503 | val 1.17805
  Epoch 015 - train 0.21672 | val 2.05487
  Classification -> best τ=0.660 (val F1=0.3865)
  Directional -> Accuracy: 0.5714, MCC: 0.1589, F1: 0.5263

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.37509 | val 1.18550
  Epoch 011 - train 0.35333 | val 1.33172
  Classification -> best τ=0.455 (val F1=0.2110)
  Directional -> Accuracy: 0.6071, MCC: 0.2717, F1: 0.6667

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.36197 | val 1.19662
  Epoch 013 - train 0.25762 | val 1.60211
  Classification -> best τ=0.455 (val F1=0.3054)
  Directional -> Accuracy: 0.3478, MCC: -0.2185, F1: 0.1176

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.43528 | val 0.73472
  Epoch 016 - train 0.21924 | val 0.77063
  Classification -> best τ=0.670 (val F1=0.4710)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.49675 | val 1.45500
  Epoch 013 - train 0.42330 | val 1.67645
  Classification -> best τ=0.570 (val F1=0.2163)
  Directional -> Accuracy: 0.4865, MCC: 0.0000, F1: 0.6545

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.49417 | val 0.79798
  Epoch 016 - train 0.30825 | val 1.03973
  Classification -> best τ=0.615 (val F1=0.2174)
  Directional -> Accuracy: 0.4889, MCC: -0.0087, F1: 0.2069

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.35997 | val 0.78975
  Epoch 011 - train 0.27748 | val 0.84306
  Classification -> best τ=0.515 (val F1=0.3059)
  Directional -> Accuracy: 0.5476, MCC: 0.1434, F1: 0.5128

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.29534 | val 0.66382
  Epoch 017 - train 0.16684 | val 0.81497
  Classification -> best τ=0.605 (val F1=0.4092)
  Directional -> Accuracy: 0.6042, MCC: 0.2750, F1: 0.5957

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.46901 | val 0.90477
  Epoch 013 - train 0.36562 | val 1.13837
  Classification -> best τ=0.580 (val F1=0.2114)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.41871 | val 0.90414
  Epoch 013 - train 0.26735 | val 1.18337
  Classification -> best τ=0.545 (val F1=0.4605)
  Directional -> Accuracy: 0.5536, MCC: 0.1049, F1: 0.5283

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.42024 | val 1.17178
  Epoch 011 - train 0.44756 | val 1.23805
  Classification -> best τ=0.560 (val F1=0.2064)
  Directional -> Accuracy: 0.6038, MCC: 0.2103, F1: 0.5882

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.44765 | val 1.01912
  Epoch 011 - train 0.43884 | val 0.95756
  Classification -> best τ=0.485 (val F1=0.2085)
  Directional -> Accuracy: 0.5455, MCC: 0.1437, F1: 0.6988

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.47984 | val 0.71229
  Epoch 011 - train 0.43566 | val 0.72936

[I 2026-02-22 10:58:32,658] Trial 119 finished with value: 0.25236083909726637 and parameters: {'feature_set': 'sector_emotion', 'model_type': 'BiGRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.30000000000000004, 'batch_size': 64, 'learning_rate': 0.008318235393532334, 'weight_decay': 0.0004957600850272781, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 0.7814710600449234, 'early_stopping_min_delta': 0.0007291821818486995}. Best is trial 112 with value: 0.2833506688525635.

  Classification -> best τ=0.470 (val F1=0.3092)
  Directional -> Accuracy: 0.5500, MCC: 0.0946, F1: 0.4255

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.25236083909726637
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d', 'emotion_anger', 'emotion_disgust', 'emotion_fear', 'emotion_joy', 'emotion_neutral', 'emotion_sadness', 'emotion_surprize', 'emotion_anger_pct', 'emotion_disgust_pct', 'emotion_fear_pct', 'emotion_joy_pct', 'emotion_neutral_pct', 'emotion_sadness_pct', 'emotion_surprize_pct']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.54148 | val 0.70069
  Epoch 017 - train 0.35102 | val 1.10091
  Classification -> best τ=0.560 (val F1=0.3286)
  Directional -> Accuracy: 0.5263, MCC: 0.0367, F1: 0.4545

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.40508 | val 0.93834
  Epoch 011 - train 0.31055 | val 0.99317
  Classification -> best τ=0.465 (val F1=0.1273)
  Directional -> Accuracy: 0.6000, MCC: 0.1273, F1: 0.7273

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.37590 | val 2.03601
  Epoch 012 - train 0.30265 | val 2.42466
  Classification -> best τ=0.600 (val F1=0.1383)
  Directional -> Accuracy: 0.4783, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.40576 | val 1.18206
  Epoch 011 - train 0.41335 | val 1.22353
  Classification -> best τ=0.470 (val F1=0.1776)
  Directional -> Accuracy: 0.5000, MCC: -0.0333, F1: 0.5934

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.35172 | val 0.94033
  Epoch 011 - train 0.27620 | val 1.05719
  Classification -> best τ=0.545 (val F1=0.4556)
  Directional -> Accuracy: 0.5400, MCC: 0.1868, F1: 0.2581

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.36311 | val 0.74399
  Epoch 016 - train 0.23761 | val 1.05267
  Classification -> best τ=0.395 (val F1=0.3301)
  Directional -> Accuracy: 0.5652, MCC: 0.1326, F1: 0.5652

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.41344 | val 1.92274
  Epoch 012 - train 0.36979 | val 1.59493
  Classification -> best τ=0.510 (val F1=0.1882)
  Directional -> Accuracy: 0.5294, MCC: 0.0417, F1: 0.4483

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.33823 | val 0.48508
  Epoch 020 - train 0.14688 | val 1.56240
  Classification -> best τ=0.610 (val F1=0.5247)
  Directional -> Accuracy: 0.4762, MCC: -0.0694, F1: 0.3889

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.41147 | val 1.06655
  Epoch 013 - train 0.28436 | val 1.68823
  Classification -> best τ=0.455 (val F1=0.2443)
  Directional -> Accuracy: 0.6458, MCC: 0.2845, F1: 0.6047

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.43158 | val 0.98485
  Epoch 013 - train 0.31836 | val 1.29700
  Classification -> best τ=0.520 (val F1=0.2620)
  Directional -> Accuracy: 0.4783, MCC: 0.0378, F1: 0.5500

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.42932 | val 1.43698
  Epoch 012 - train 0.38370 | val 1.65324
  Classification -> best τ=0.440 (val F1=0.1692)
  Directional -> Accuracy: 0.6327, MCC: 0.2465, F1: 0.5000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.41681 | val 2.26419
  Epoch 012 - train 0.34537 | val 2.57828
  Classification -> best τ=0.490 (val F1=0.0236)
  Directional -> Accuracy: 0.4912, MCC: -0.0744, F1: 0.6506

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.35140 | val 2.40506
  Epoch 011 - train 0.34294 | val 2.23501
  Classification -> best τ=0.490 (val F1=0.1225)
  Directional -> Accuracy: 0.4524, MCC: -0.0829, F1: 0.4651

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.43763 | val 0.63383
  Epoch 015 - train 0.29161 | val 1.12157
  Classification -> best τ=0.675 (val F1=0.3864)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.46298 | val 1.09305
  Epoch 013 - train 0.36066 | val 1.14508
  Classification -> best τ=0.585 (val F1=0.2078)
  Directional -> Accuracy: 0.5490, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.42482 | val 1.02914
  Epoch 011 - train 0.43221 | val 1.14420
  Classification -> best τ=0.430 (val F1=0.3486)
  Directional -> Accuracy: 0.4928, MCC: -0.1478, F1: 0.6535

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.41900 | val 1.69093
  Epoch 011 - train 0.38133 | val 1.79330
  Classification -> best τ=0.480 (val F1=0.0032)
  Directional -> Accuracy: 0.6207, MCC: 0.0000, F1: 0.7660

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.48327 | val 1.32804
  Epoch 011 - train 0.43603 | val 1.47294
  Classification -> best τ=0.515 (val F1=0.1909)
  Directional -> Accuracy: 0.4000, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.40079 | val 1.04739
  Epoch 011 - train 0.35907 | val 0.97267
  Classification -> best τ=0.460 (val F1=0.2752)
  Directional -> Accuracy: 0.5781, MCC: 0.0000, F1: 0.7327

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.49074 | val 0.88035
  Epoch 012 - train 0.42639 | val 0.94601
  Classification -> best τ=0.510 (val F1=0.2230)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.35707 | val 1.20188
  Epoch 013 - train 0.24203 | val 1.46486
  Classification -> best τ=0.525 (val F1=0.3639)
  Directional -> Accuracy: 0.4894, MCC: -0.0373, F1: 0.5556

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.41653 | val 1.33271
  Epoch 013 - train 0.30380 | val 1.54678
  Classification -> best τ=0.545 (val F1=0.2376)
  Directional -> Accuracy: 0.4923, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.38539 | val 0.90364
  Epoch 012 - train 0.33667 | val 1.01742
  Classification -> best τ=0.720 (val F1=0.3175)
  Directional -> Accuracy: 0.5614, MCC: 0.1400, F1: 0.5614

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.40526 | val 0.93716
  Epoch 012 - train 0.42337 | val 1.04167
  Classification -> best τ=0.400 (val F1=0.1695)
  Directional -> Accuracy: 0.5538, MCC: 0.1269, F1: 0.6027

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.43897 | val 1.63106
  Epoch 012 - train 0.33057 | val 1.63566
  Classification -> best τ=0.440 (val F1=0.4002)
  Directional -> Accuracy: 0.5455, MCC: 0.1491, F1: 0.4444

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.24307 | val 0.96345
  Epoch 011 - train 0.25365 | val 0.98336
  Classification -> best τ=0.475 (val F1=0.2035)
  Directional -> Accuracy: 0.5111, MCC: 0.1085, F1: 0.5769

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.42592 | val 0.78139
  Epoch 014 - train 0.25598 | val 0.94139
  Classification -> best τ=0.550 (val F1=0.2976)
  Directional -> Accuracy: 0.4524, MCC: -0.0446, F1: 0.3784

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.41654 | val 1.89439
  Epoch 012 - train 0.34481 | val 1.73833
  Classification -> best τ=0.585 (val F1=0.1615)
  Directional -> Accuracy: 0.4464, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.35976 | val 0.76858
  Epoch 012 - train 0.34122 | val 0.88602
  Classification -> best τ=0.470 (val F1=0.4345)
  Directional -> Accuracy: 0.5750, MCC: 0.1240, F1: 0.7119

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.35022 | val 1.15349
  Epoch 012 - train 0.30644 | val 1.46050
  Classification -> best τ=0.570 (val F1=0.2271)
  Directional -> Accuracy: 0.5476, MCC: 0.0953, F1: 0.5366

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.40865 | val 0.99228
  Epoch 012 - train 0.37483 | val 1.23077
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5476, MCC: 0.0000, F1: 0.7077

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.41840 | val 1.84240
  Epoch 014 - train 0.24040 | val 2.60501
  Classification -> best τ=0.265 (val F1=0.2918)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.43690 | val 0.94194
  Epoch 012 - train 0.40243 | val 1.16587
  Classification -> best τ=0.355 (val F1=0.3131)
  Directional -> Accuracy: 0.5556, MCC: 0.0000, F1: 0.7143

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.39560 | val 1.34215
  Epoch 012 - train 0.35137 | val 1.16355
  Classification -> best τ=0.405 (val F1=0.3417)
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.52108 | val 1.12263
  Epoch 012 - train 0.43569 | val 1.07591
  Classification -> best τ=0.605 (val F1=0.1446)
  Directional -> Accuracy: 0.4242, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.35520 | val 1.36525
  Epoch 014 - train 0.27788 | val 2.12542
  Classification -> best τ=0.515 (val F1=0.3347)
  Directional -> Accuracy: 0.6667, MCC: 0.3303, F1: 0.6957

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.39986 | val 2.23845
  Epoch 012 - train 0.34883 | val 2.42377
  Classification -> best τ=0.625 (val F1=0.2305)
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.0000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.34958 | val 1.06551
  Epoch 012 - train 0.28764 | val 1.20582
  Classification -> best τ=0.640 (val F1=0.2659)
  Directional -> Accuracy: 0.4130, MCC: -0.0062, F1: 0.1818

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.42406 | val 0.61235
  Epoch 020 - train 0.07409 | val 1.23238
  Classification -> best τ=0.440 (val F1=0.5424)
  Directional -> Accuracy: 0.3333, MCC: -0.1970, F1: 0.5000

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.41963 | val 1.50552
  Epoch 011 - train 0.37391 | val 1.47426
  Classification -> best τ=0.390 (val F1=0.2479)
  Directional -> Accuracy: 0.4865, MCC: 0.0000, F1: 0.6545

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.49025 | val 0.92173
  Epoch 014 - train 0.28522 | val 1.03686
  Classification -> best τ=0.500 (val F1=0.2712)
  Directional -> Accuracy: 0.5111, MCC: 0.0349, F1: 0.3889

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.25264 | val 0.63614
  Epoch 020 - train 0.08285 | val 1.25666
  Classification -> best τ=0.395 (val F1=0.3948)
  Directional -> Accuracy: 0.5714, MCC: 0.1132, F1: 0.6400

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.30859 | val 0.61221
  Epoch 020 - train 0.05600 | val 1.39044
  Classification -> best τ=0.725 (val F1=0.3311)
  Directional -> Accuracy: 0.6458, MCC: 0.2711, F1: 0.5641

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.39890 | val 1.07944
  Epoch 014 - train 0.22273 | val 1.56223
  Classification -> best τ=0.405 (val F1=0.2291)
  Directional -> Accuracy: 0.4727, MCC: -0.2557, F1: 0.6420

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.38278 | val 0.97787
  Epoch 014 - train 0.26599 | val 1.16590
  Classification -> best τ=0.440 (val F1=0.3809)
  Directional -> Accuracy: 0.5000, MCC: 0.0709, F1: 0.6500

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.37508 | val 1.45308
  Epoch 012 - train 0.31383 | val 1.78809
  Classification -> best τ=0.515 (val F1=0.1810)
  Directional -> Accuracy: 0.6226, MCC: 0.2985, F1: 0.7143

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.41982 | val 1.31950
  Epoch 011 - train 0.37686 | val 1.50157
  Classification -> best τ=0.545 (val F1=0.2859)
  Directional -> Accuracy: 0.4909, MCC: 0.0029, F1: 0.3913

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.50521 | val 1.37458

[I 2026-02-22 10:59:53,767] Trial 120 finished with value: 0.2611043460308055 and parameters: {'feature_set': 'sector_emotion', 'model_type': 'BiGRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.2, 'batch_size': 64, 'learning_rate': 0.006761879654131052, 'weight_decay': 6.851780231827187e-05, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 0.9234623550486653, 'early_stopping_min_delta': 0.00040270181285085183}. Best is trial 112 with value: 0.2833506688525635.

  Epoch 012 - train 0.40804 | val 1.19543
  Classification -> best τ=0.470 (val F1=0.2060)
  Directional -> Accuracy: 0.5167, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2611043460308055
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d', 'emotion_anger', 'emotion_disgust', 'emotion_fear', 'emotion_joy', 'emotion_neutral', 'emotion_sadness', 'emotion_surprize', 'emotion_anger_pct', 'emotion_disgust_pct', 'emotion_fear_pct', 'emotion_joy_pct', 'emotion_neutral_pct', 'emotion_sadness_pct', 'emotion_surprize_pct']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.45989 | val 0.74617
  Epoch 016 - train 0.34433 | val 0.76149
  Classification -> best τ=0.365 (val F1=0.2061)
  Directional -> Accuracy: 0.4868, MCC: -0.0293, F1: 0.4507

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.40347 | val 0.98607
  Epoch 011 - train 0.30857 | val 1.04913
  Classification -> best τ=0.460 (val F1=0.2670)
  Directional -> Accuracy: 0.5778, MCC: 0.0000, F1: 0.7324

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.44107 | val 1.64255
  Epoch 012 - train 0.36694 | val 1.98901
  Classification -> best τ=0.620 (val F1=0.1333)
  Directional -> Accuracy: 0.4783, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.52597 | val 1.50509
  Epoch 012 - train 0.44143 | val 1.77739
  Classification -> best τ=0.460 (val F1=0.1694)
  Directional -> Accuracy: 0.4865, MCC: -0.1463, F1: 0.6415

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.39289 | val 1.05800
  Epoch 014 - train 0.26063 | val 1.69134
  Classification -> best τ=0.530 (val F1=0.3280)
  Directional -> Accuracy: 0.5600, MCC: 0.1801, F1: 0.3889

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.42414 | val 0.88063
  Epoch 016 - train 0.23105 | val 0.91005
  Classification -> best τ=0.575 (val F1=0.3069)
  Directional -> Accuracy: 0.5000, MCC: -0.0118, F1: 0.4103

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.46943 | val 1.56234
  Epoch 014 - train 0.32983 | val 1.90671
  Classification -> best τ=0.470 (val F1=0.3209)
  Directional -> Accuracy: 0.5588, MCC: 0.1671, F1: 0.5588

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.41452 | val 0.66075
  Epoch 013 - train 0.30168 | val 0.76853
  Classification -> best τ=0.315 (val F1=0.3689)
  Directional -> Accuracy: 0.5476, MCC: 0.0313, F1: 0.3448

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.34087 | val 1.26153
  Epoch 012 - train 0.32322 | val 1.50917
  Classification -> best τ=0.415 (val F1=0.2154)
  Directional -> Accuracy: 0.5625, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.45831 | val 0.88615
  Epoch 011 - train 0.41246 | val 0.92508
  Classification -> best τ=0.505 (val F1=0.3492)
  Directional -> Accuracy: 0.5072, MCC: 0.1376, F1: 0.5952

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.46228 | val 1.22704
  Epoch 012 - train 0.30481 | val 1.49161
  Classification -> best τ=0.520 (val F1=0.1738)
  Directional -> Accuracy: 0.5714, MCC: 0.1599, F1: 0.0870

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.42132 | val 2.20272
  Epoch 012 - train 0.32810 | val 2.77567
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5088, MCC: 0.0000, F1: 0.6744

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.38502 | val 1.27658
  Epoch 012 - train 0.32587 | val 1.87197
  Classification -> best τ=0.455 (val F1=0.2850)
  Directional -> Accuracy: 0.5238, MCC: 0.0302, F1: 0.4444

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.49973 | val 0.81926
  Epoch 012 - train 0.40460 | val 0.97494
  Classification -> best τ=0.415 (val F1=0.3289)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.47477 | val 1.15366
  Epoch 011 - train 0.40954 | val 1.25015
  Classification -> best τ=0.485 (val F1=0.3365)
  Directional -> Accuracy: 0.4118, MCC: -0.1753, F1: 0.5714

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.51381 | val 0.96681
  Epoch 012 - train 0.43673 | val 1.30468
  Classification -> best τ=0.455 (val F1=0.2974)
  Directional -> Accuracy: 0.4783, MCC: -0.1552, F1: 0.6327

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.42867 | val 1.50223
  Epoch 011 - train 0.35468 | val 1.51252
  Classification -> best τ=0.545 (val F1=0.0354)
  Directional -> Accuracy: 0.3793, MCC: -0.1270, F1: 0.2500

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.48405 | val 1.18359
  Epoch 014 - train 0.37690 | val 1.39773
  Classification -> best τ=0.455 (val F1=0.0658)
  Directional -> Accuracy: 0.6000, MCC: 0.0000, F1: 0.7500

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.43031 | val 1.14844
  Epoch 012 - train 0.35178 | val 1.13424
  Classification -> best τ=0.565 (val F1=0.2315)
  Directional -> Accuracy: 0.4219, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.57438 | val 0.95351
  Epoch 012 - train 0.46838 | val 0.79284
  Classification -> best τ=0.530 (val F1=0.2377)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.43049 | val 1.37326
  Epoch 013 - train 0.29590 | val 1.33541
  Classification -> best τ=0.475 (val F1=0.1424)
  Directional -> Accuracy: 0.6170, MCC: 0.0921, F1: 0.7429

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.44688 | val 0.92031
  Epoch 012 - train 0.33513 | val 0.99640
  Classification -> best τ=0.460 (val F1=0.3279)
  Directional -> Accuracy: 0.5385, MCC: 0.1275, F1: 0.2857

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.45130 | val 0.89765
  Epoch 014 - train 0.33208 | val 1.20088
  Classification -> best τ=0.530 (val F1=0.4055)
  Directional -> Accuracy: 0.6140, MCC: 0.2258, F1: 0.7381

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.47444 | val 0.76355
  Epoch 012 - train 0.41932 | val 0.85610
  Classification -> best τ=0.460 (val F1=0.1415)
  Directional -> Accuracy: 0.5846, MCC: 0.1798, F1: 0.6087

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.44544 | val 1.24361
  Epoch 014 - train 0.26124 | val 1.74298
  Classification -> best τ=0.200 (val F1=0.4051)
  Directional -> Accuracy: 0.5636, MCC: 0.1587, F1: 0.5200

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.23141 | val 1.58601
  Epoch 013 - train 0.11282 | val 2.57479
  Classification -> best τ=0.430 (val F1=0.2035)
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.5938

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.45852 | val 0.67143
  Epoch 020 - train 0.15067 | val 1.04269
  Classification -> best τ=0.555 (val F1=0.2810)
  Directional -> Accuracy: 0.5000, MCC: 0.0782, F1: 0.4000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.41504 | val 1.92686
  Epoch 012 - train 0.36251 | val 1.82225
  Classification -> best τ=0.485 (val F1=0.1778)
  Directional -> Accuracy: 0.4643, MCC: -0.0535, F1: 0.4444

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.42509 | val 1.02776
  Epoch 012 - train 0.36519 | val 1.20643
  Classification -> best τ=0.520 (val F1=0.2267)
  Directional -> Accuracy: 0.5500, MCC: 0.0000, F1: 0.7097

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.50293 | val 1.11463
  Epoch 012 - train 0.42442 | val 0.91028
  Classification -> best τ=0.510 (val F1=0.4673)
  Directional -> Accuracy: 0.5000, MCC: 0.0046, F1: 0.5116

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.38691 | val 1.65545
  Epoch 011 - train 0.39666 | val 1.93671
  Classification -> best τ=0.380 (val F1=0.2697)
  Directional -> Accuracy: 0.5714, MCC: 0.1435, F1: 0.5909

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.32214 | val 1.58793
  Epoch 012 - train 0.28746 | val 2.04851
  Classification -> best τ=0.550 (val F1=0.3302)
  Directional -> Accuracy: 0.5306, MCC: 0.0183, F1: 0.6761

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.47627 | val 0.89521
  Epoch 013 - train 0.40795 | val 0.88614
  Classification -> best τ=0.405 (val F1=0.3145)
  Directional -> Accuracy: 0.5556, MCC: 0.0000, F1: 0.7143

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.39861 | val 1.33627
  Epoch 012 - train 0.37760 | val 1.61501
  Classification -> best τ=0.455 (val F1=0.2588)
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.47986 | val 1.40555
  Epoch 011 - train 0.44189 | val 1.34002
  Classification -> best τ=0.535 (val F1=0.2618)
  Directional -> Accuracy: 0.5152, MCC: 0.0353, F1: 0.5429

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.28528 | val 1.33366
  Epoch 013 - train 0.22780 | val 1.57120
  Classification -> best τ=0.405 (val F1=0.3068)
  Directional -> Accuracy: 0.5476, MCC: 0.0853, F1: 0.6667

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.40315 | val 2.00612
  Epoch 012 - train 0.32419 | val 2.10631
  Classification -> best τ=0.420 (val F1=0.2450)
  Directional -> Accuracy: 0.5179, MCC: 0.0384, F1: 0.5091

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.32288 | val 0.95495
  Epoch 012 - train 0.25710 | val 1.07226
  Classification -> best τ=0.455 (val F1=0.3146)
  Directional -> Accuracy: 0.6087, MCC: 0.0000, F1: 0.7568

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.50077 | val 0.66986
  Epoch 018 - train 0.17187 | val 1.39032
  Classification -> best τ=0.520 (val F1=0.4011)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.43210 | val 1.62332
  Epoch 011 - train 0.41712 | val 1.71381
  Classification -> best τ=0.500 (val F1=0.2485)
  Directional -> Accuracy: 0.5135, MCC: 0.0000, F1: 0.0000

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.47305 | val 0.88675
  Epoch 014 - train 0.30416 | val 0.96480
  Classification -> best τ=0.555 (val F1=0.2712)
  Directional -> Accuracy: 0.4889, MCC: -0.0069, F1: 0.1481

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.36116 | val 0.84952
  Epoch 013 - train 0.25821 | val 0.94638
  Classification -> best τ=0.405 (val F1=0.5230)
  Directional -> Accuracy: 0.5952, MCC: 0.1273, F1: 0.7213

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.44887 | val 0.67574
  Epoch 020 - train 0.10462 | val 1.58055
  Epoch 021 - train 0.03797 | val 1.39081
  Classification -> best τ=0.495 (val F1=0.4682)
  Directional -> Accuracy: 0.5000, MCC: 0.1491, F1: 0.5556

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.44363 | val 1.13650
  Epoch 013 - train 0.43882 | val 1.44945
  Classification -> best τ=0.740 (val F1=0.2036)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.39498 | val 1.09100
  Epoch 013 - train 0.29282 | val 1.55310
  Classification -> best τ=0.405 (val F1=0.3164)
  Directional -> Accuracy: 0.4821, MCC: -0.0479, F1: 0.3830

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.36520 | val 1.74469
  Epoch 011 - train 0.37285 | val 1.65508
  Classification -> best τ=0.550 (val F1=0.2305)
  Directional -> Accuracy: 0.5660, MCC: 0.1343, F1: 0.6349

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.49547 | val 1.36088
  Epoch 012 - train 0.28871 | val 1.70769
  Classification -> best τ=0.555 (val F1=0.2291)
  Directional -> Accuracy: 0.4182, MCC: -0.1639, F1: 0.2000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.51613 | val 1.03074
  Epoch 011 - train 0.42947 | val 0.96949

[I 2026-02-22 11:01:15,869] Trial 121 finished with value: 0.26883110082896683 and parameters: {'feature_set': 'sector_emotion', 'model_type': 'BiGRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.30000000000000004, 'batch_size': 64, 'learning_rate': 0.00984386873504883, 'weight_decay': 0.00011029215107758989, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 0.8938838992820077, 'early_stopping_min_delta': 6.840419943649098e-06}. Best is trial 112 with value: 0.2833506688525635.

  Classification -> best τ=0.495 (val F1=0.2749)
  Directional -> Accuracy: 0.5333, MCC: 0.0842, F1: 0.1250

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.26883110082896683
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d', 'emotion_anger', 'emotion_disgust', 'emotion_fear', 'emotion_joy', 'emotion_neutral', 'emotion_sadness', 'emotion_surprize', 'emotion_anger_pct', 'emotion_disgust_pct', 'emotion_fear_pct', 'emotion_joy_pct', 'emotion_neutral_pct', 'emotion_sadness_pct', 'emotion_surprize_pct']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.47202 | val 0.74391
  Epoch 016 - train 0.31103 | val 0.87873
  Classification -> best τ=0.585 (val F1=0.2919)
  Directional -> Accuracy: 0.4605, MCC: -0.1075, F1: 0.3492

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.36944 | val 0.92510
  Epoch 011 - train 0.33293 | val 1.11205
  Classification -> best τ=0.385 (val F1=0.1289)
  Directional -> Accuracy: 0.5778, MCC: 0.0000, F1: 0.7324

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.37837 | val 1.33961
  Epoch 011 - train 0.34285 | val 1.60739
  Classification -> best τ=0.580 (val F1=0.1383)
  Directional -> Accuracy: 0.4783, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.45551 | val 0.81145
  Epoch 011 - train 0.43859 | val 1.33546
  Classification -> best τ=0.435 (val F1=0.1585)
  Directional -> Accuracy: 0.5135, MCC: 0.0163, F1: 0.5610

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.37276 | val 1.16148
  Epoch 012 - train 0.32874 | val 1.28566
  Classification -> best τ=0.585 (val F1=0.2567)
  Directional -> Accuracy: 0.5600, MCC: 0.2316, F1: 0.3125

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.38872 | val 0.70411
  Epoch 012 - train 0.30988 | val 0.80230
  Classification -> best τ=0.445 (val F1=0.1808)
  Directional -> Accuracy: 0.4565, MCC: -0.0756, F1: 0.5455

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.44336 | val 1.29038
  Epoch 011 - train 0.36952 | val 1.50330
  Classification -> best τ=0.570 (val F1=0.2163)
  Directional -> Accuracy: 0.5294, MCC: 0.0172, F1: 0.4074

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.35204 | val 0.77587
  Epoch 017 - train 0.18967 | val 1.69242
  Classification -> best τ=0.325 (val F1=0.4839)
  Directional -> Accuracy: 0.4048, MCC: -0.1334, F1: 0.5614

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.43467 | val 0.82999
  Epoch 014 - train 0.30377 | val 1.47665
  Classification -> best τ=0.495 (val F1=0.3047)
  Directional -> Accuracy: 0.6250, MCC: 0.2308, F1: 0.5500

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.47267 | val 0.95664
  Epoch 013 - train 0.34983 | val 0.86837
  Classification -> best τ=0.515 (val F1=0.2480)
  Directional -> Accuracy: 0.4348, MCC: -0.0749, F1: 0.4935

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.44801 | val 1.09237
  Epoch 015 - train 0.25711 | val 1.11857
  Classification -> best τ=0.475 (val F1=0.3007)
  Directional -> Accuracy: 0.6327, MCC: 0.2556, F1: 0.4375

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.42897 | val 2.61247
  Epoch 011 - train 0.35270 | val 2.73883
  Classification -> best τ=0.450 (val F1=0.0377)
  Directional -> Accuracy: 0.5614, MCC: 0.1217, F1: 0.6032

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.36802 | val 1.28844
  Epoch 013 - train 0.29127 | val 1.67548
  Classification -> best τ=0.535 (val F1=0.0512)
  Directional -> Accuracy: 0.4762, MCC: -0.1062, F1: 0.2667

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.41529 | val 0.85390
  Epoch 016 - train 0.26403 | val 1.08108
  Classification -> best τ=0.600 (val F1=0.3768)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.44903 | val 1.02065
  Epoch 011 - train 0.39746 | val 0.93209
  Classification -> best τ=0.510 (val F1=0.1706)
  Directional -> Accuracy: 0.5294, MCC: 0.0424, F1: 0.4545

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.43594 | val 1.73276
  Epoch 013 - train 0.34167 | val 1.48995
  Classification -> best τ=0.475 (val F1=0.3024)
  Directional -> Accuracy: 0.5507, MCC: 0.0850, F1: 0.6173

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.42084 | val 1.27226
  Epoch 011 - train 0.42947 | val 1.41768
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.6207, MCC: 0.0000, F1: 0.7660

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.48357 | val 1.24510
  Epoch 011 - train 0.45034 | val 1.29109
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.6000, MCC: 0.0000, F1: 0.7500

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.42194 | val 1.10821
  Epoch 013 - train 0.31922 | val 1.45977
  Classification -> best τ=0.390 (val F1=0.3421)
  Directional -> Accuracy: 0.5156, MCC: 0.0735, F1: 0.4918

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.47603 | val 0.76035
  Epoch 014 - train 0.38439 | val 1.01245
  Classification -> best τ=0.410 (val F1=0.3006)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.38793 | val 1.02490
  Epoch 011 - train 0.34949 | val 1.15947
  Classification -> best τ=0.520 (val F1=0.2941)
  Directional -> Accuracy: 0.4681, MCC: 0.0598, F1: 0.3902

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.40490 | val 1.41660
  Epoch 012 - train 0.37541 | val 1.44643
  Classification -> best τ=0.535 (val F1=0.2378)
  Directional -> Accuracy: 0.4923, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.48247 | val 0.91481
  Epoch 014 - train 0.30807 | val 1.09929
  Classification -> best τ=0.595 (val F1=0.4177)
  Directional -> Accuracy: 0.5439, MCC: 0.0820, F1: 0.5806

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.45107 | val 0.79185
  Epoch 012 - train 0.41779 | val 0.79302
  Classification -> best τ=0.485 (val F1=0.2524)
  Directional -> Accuracy: 0.5385, MCC: 0.0923, F1: 0.5833

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.38664 | val 1.56983
  Epoch 013 - train 0.33633 | val 2.10925
  Classification -> best τ=0.440 (val F1=0.3686)
  Directional -> Accuracy: 0.5091, MCC: 0.0671, F1: 0.4000

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.26588 | val 0.94610
  Epoch 011 - train 0.23839 | val 0.95218
  Classification -> best τ=0.485 (val F1=0.0105)
  Directional -> Accuracy: 0.4222, MCC: -0.0618, F1: 0.5517

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.40085 | val 0.74159
  Epoch 011 - train 0.36443 | val 0.77283
  Classification -> best τ=0.560 (val F1=0.2402)
  Directional -> Accuracy: 0.5000, MCC: 0.0430, F1: 0.4615

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.42740 | val 0.96473
  Epoch 012 - train 0.40355 | val 1.19166
  Classification -> best τ=0.410 (val F1=0.0906)
  Directional -> Accuracy: 0.5714, MCC: 0.1054, F1: 0.7143

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.39396 | val 0.85528
  Epoch 016 - train 0.24445 | val 0.91054
  Classification -> best τ=0.405 (val F1=0.4966)
  Directional -> Accuracy: 0.5500, MCC: 0.0503, F1: 0.6667

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.35744 | val 1.49564
  Epoch 011 - train 0.36183 | val 1.57334
  Classification -> best τ=0.615 (val F1=0.3501)
  Directional -> Accuracy: 0.5000, MCC: -0.1489, F1: 0.0000

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.43599 | val 1.51168
  Epoch 012 - train 0.41355 | val 1.67914
  Classification -> best τ=0.630 (val F1=0.1846)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.38168 | val 1.21957
  Epoch 011 - train 0.36099 | val 1.35790
  Classification -> best τ=0.550 (val F1=0.2969)
  Directional -> Accuracy: 0.4490, MCC: -0.1535, F1: 0.0000

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.46932 | val 1.73751
  Epoch 012 - train 0.40903 | val 1.00671
  Classification -> best τ=0.395 (val F1=0.2231)
  Directional -> Accuracy: 0.5556, MCC: 0.0000, F1: 0.7143

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.44089 | val 0.94547
  Epoch 011 - train 0.43356 | val 0.98076
  Classification -> best τ=0.425 (val F1=0.1874)
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.49316 | val 1.10746
  Epoch 011 - train 0.49786 | val 1.14716
  Classification -> best τ=0.445 (val F1=0.1194)
  Directional -> Accuracy: 0.5758, MCC: 0.0000, F1: 0.7308

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.31492 | val 1.30676
  Epoch 011 - train 0.30262 | val 1.27129
  Classification -> best τ=0.460 (val F1=0.2409)
  Directional -> Accuracy: 0.6429, MCC: 0.2843, F1: 0.6939

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.34720 | val 1.81774
  Epoch 011 - train 0.36176 | val 2.01027
  Classification -> best τ=0.490 (val F1=0.3147)
  Directional -> Accuracy: 0.5357, MCC: 0.0620, F1: 0.4800

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.35812 | val 0.94374
  Epoch 014 - train 0.22352 | val 1.41783
  Classification -> best τ=0.525 (val F1=0.3352)
  Directional -> Accuracy: 0.3913, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.39720 | val 0.65831
  Epoch 019 - train 0.19690 | val 1.23595
  Classification -> best τ=0.430 (val F1=0.4011)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.38496 | val 1.44946
  Epoch 011 - train 0.36598 | val 1.50486
  Classification -> best τ=0.430 (val F1=0.2892)
  Directional -> Accuracy: 0.4865, MCC: 0.0000, F1: 0.6545

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.45286 | val 0.78898
  Epoch 014 - train 0.29626 | val 1.00716
  Classification -> best τ=0.400 (val F1=0.2697)
  Directional -> Accuracy: 0.5111, MCC: 0.0000, F1: 0.6765

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.23527 | val 0.79978
  Epoch 013 - train 0.20303 | val 0.92809
  Classification -> best τ=0.465 (val F1=0.1961)
  Directional -> Accuracy: 0.4286, MCC: -0.1132, F1: 0.4000

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.36082 | val 0.76479
  Epoch 015 - train 0.20622 | val 0.96308
  Classification -> best τ=0.420 (val F1=0.4682)
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.5455

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.41109 | val 1.22999
  Epoch 012 - train 0.39090 | val 1.17670
  Classification -> best τ=0.610 (val F1=0.2085)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.42986 | val 1.48668
  Epoch 013 - train 0.29490 | val 1.15688
  Classification -> best τ=0.465 (val F1=0.2514)
  Directional -> Accuracy: 0.4643, MCC: -0.0646, F1: 0.5161

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.47608 | val 1.32650
  Epoch 012 - train 0.39789 | val 1.24080
  Classification -> best τ=0.455 (val F1=0.1847)
  Directional -> Accuracy: 0.5660, MCC: 0.1998, F1: 0.6933

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.35862 | val 1.38075
  Epoch 011 - train 0.34602 | val 1.54922
  Classification -> best τ=0.455 (val F1=0.2415)
  Directional -> Accuracy: 0.5455, MCC: 0.1437, F1: 0.6988

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.47697 | val 0.68372

[I 2026-02-22 11:02:37,940] Trial 122 finished with value: 0.24539906724492488 and parameters: {'feature_set': 'sector_emotion', 'model_type': 'BiGRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.2, 'batch_size': 64, 'learning_rate': 0.004929104699819502, 'weight_decay': 3.461329658512406e-05, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 0.8260679665891769, 'early_stopping_min_delta': 0.0014440677420009388}. Best is trial 112 with value: 0.2833506688525635.

  Epoch 019 - train 0.27294 | val 0.88201
  Classification -> best τ=0.290 (val F1=0.3177)
  Directional -> Accuracy: 0.4667, MCC: -0.0963, F1: 0.2727

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.24539906724492488
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d', 'emotion_anger', 'emotion_disgust', 'emotion_fear', 'emotion_joy', 'emotion_neutral', 'emotion_sadness', 'emotion_surprize', 'emotion_anger_pct', 'emotion_disgust_pct', 'emotion_fear_pct', 'emotion_joy_pct', 'emotion_neutral_pct', 'emotion_sadness_pct', 'emotion_surprize_pct']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.43952 | val 0.90314
  Epoch 013 - train 0.35238 | val 1.01025
  Classification -> best τ=0.475 (val F1=0.2919)
  Directional -> Accuracy: 0.5789, MCC: 0.1485, F1: 0.5294

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.35845 | val 1.05137
  Epoch 012 - train 0.29190 | val 1.10641
  Classification -> best τ=0.500 (val F1=0.2523)
  Directional -> Accuracy: 0.5333, MCC: 0.0931, F1: 0.5333

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.42174 | val 1.80056
  Epoch 013 - train 0.33161 | val 2.64907
  Classification -> best τ=0.600 (val F1=0.1854)
  Directional -> Accuracy: 0.4130, MCC: -0.2759, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.45901 | val 1.21177
  Epoch 012 - train 0.41109 | val 1.87228
  Classification -> best τ=0.405 (val F1=0.3161)
  Directional -> Accuracy: 0.4865, MCC: -0.2204, F1: 0.6545

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.42253 | val 1.32621
  Epoch 012 - train 0.27251 | val 1.63561
  Classification -> best τ=0.585 (val F1=0.2722)
  Directional -> Accuracy: 0.4400, MCC: -0.2125, F1: 0.0000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.38997 | val 0.87593
  Epoch 020 - train 0.20032 | val 0.89634
  Epoch 022 - train 0.13762 | val 0.91110
  Classification -> best τ=0.225 (val F1=0.3776)
  Directional -> Accuracy: 0.5217, MCC: 0.0658, F1: 0.5926

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.40856 | val 2.29516
  Epoch 012 - train 0.34458 | val 2.41297
  Classification -> best τ=0.485 (val F1=0.2170)
  Directional -> Accuracy: 0.4853, MCC: 0.1159, F1: 0.5679

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.25631 | val 0.88843
  Epoch 014 - train 0.22526 | val 1.60462
  Classification -> best τ=0.440 (val F1=0.3632)
  Directional -> Accuracy: 0.4762, MCC: -0.0694, F1: 0.3889

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.33186 | val 1.46445
  Epoch 012 - train 0.27973 | val 1.42998
  Classification -> best τ=0.470 (val F1=0.4025)
  Directional -> Accuracy: 0.5625, MCC: 0.0808, F1: 0.4000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.43544 | val 1.09989
  Epoch 012 - train 0.36843 | val 1.02650
  Classification -> best τ=0.440 (val F1=0.2287)
  Directional -> Accuracy: 0.4783, MCC: 0.0054, F1: 0.5135

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.37029 | val 1.44212
  Epoch 012 - train 0.33820 | val 1.25688
  Classification -> best τ=0.525 (val F1=0.1356)
  Directional -> Accuracy: 0.6122, MCC: 0.2379, F1: 0.2963

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.44584 | val 1.77931
  Epoch 013 - train 0.32527 | val 2.16065
  Classification -> best τ=0.420 (val F1=0.2157)
  Directional -> Accuracy: 0.5088, MCC: 0.0000, F1: 0.6744

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.40670 | val 1.95659
  Epoch 014 - train 0.30456 | val 2.35685
  Classification -> best τ=0.565 (val F1=0.1754)
  Directional -> Accuracy: 0.4524, MCC: -0.0912, F1: 0.4390

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.43358 | val 0.79137
  Epoch 013 - train 0.31166 | val 1.06176
  Classification -> best τ=0.635 (val F1=0.3864)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.47816 | val 0.89888
  Epoch 011 - train 0.42841 | val 0.93427
  Classification -> best τ=0.535 (val F1=0.3390)
  Directional -> Accuracy: 0.4902, MCC: -0.0139, F1: 0.4800

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.40828 | val 1.18907
  Epoch 012 - train 0.32748 | val 1.54875
  Classification -> best τ=0.645 (val F1=0.3105)
  Directional -> Accuracy: 0.5652, MCC: 0.1829, F1: 0.4643

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.44034 | val 1.73233
  Epoch 011 - train 0.39004 | val 1.73282
  Classification -> best τ=0.625 (val F1=0.1291)
  Directional -> Accuracy: 0.3966, MCC: 0.1035, F1: 0.0541

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.50954 | val 1.08414
  Epoch 012 - train 0.43058 | val 1.42401
  Classification -> best τ=0.575 (val F1=0.2082)
  Directional -> Accuracy: 0.4000, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.42434 | val 1.20261
  Epoch 013 - train 0.32493 | val 1.52648
  Classification -> best τ=0.320 (val F1=0.2914)
  Directional -> Accuracy: 0.5000, MCC: -0.0149, F1: 0.5556

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.48157 | val 0.93408
  Epoch 011 - train 0.43570 | val 0.92009
  Classification -> best τ=0.415 (val F1=0.2027)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.31804 | val 1.20102
  Epoch 011 - train 0.33495 | val 1.46173
  Classification -> best τ=0.575 (val F1=0.2861)
  Directional -> Accuracy: 0.4255, MCC: -0.0182, F1: 0.3077

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.45802 | val 1.20363
  Epoch 012 - train 0.34831 | val 1.25217
  Classification -> best τ=0.420 (val F1=0.2381)
  Directional -> Accuracy: 0.4923, MCC: -0.0027, F1: 0.0571

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.44204 | val 0.73383
  Epoch 014 - train 0.25339 | val 0.99839
  Classification -> best τ=0.660 (val F1=0.3749)
  Directional -> Accuracy: 0.4737, MCC: 0.0014, F1: 0.3750

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.50193 | val 0.79094
  Epoch 015 - train 0.29940 | val 1.03212
  Classification -> best τ=0.405 (val F1=0.1174)
  Directional -> Accuracy: 0.5692, MCC: 0.1307, F1: 0.4615

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.40845 | val 1.14664
  Epoch 012 - train 0.30818 | val 1.38061
  Classification -> best τ=0.435 (val F1=0.4688)
  Directional -> Accuracy: 0.6000, MCC: 0.2476, F1: 0.5417

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.23595 | val 1.31666
  Epoch 011 - train 0.17415 | val 1.36142
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.5938

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.43607 | val 0.74378
  Epoch 015 - train 0.24948 | val 0.75713
  Classification -> best τ=0.620 (val F1=0.3536)
  Directional -> Accuracy: 0.4048, MCC: -0.1291, F1: 0.1935

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.39292 | val 1.26025
  Epoch 012 - train 0.35659 | val 1.61613
  Classification -> best τ=0.530 (val F1=0.1913)
  Directional -> Accuracy: 0.4464, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.32518 | val 1.07860
  Epoch 012 - train 0.32001 | val 1.36918
  Classification -> best τ=0.560 (val F1=0.3278)
  Directional -> Accuracy: 0.5500, MCC: 0.0231, F1: 0.7000

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.43586 | val 1.40980
  Epoch 012 - train 0.32236 | val 1.79891
  Classification -> best τ=0.545 (val F1=0.2814)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.4878

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.36591 | val 1.47335
  Epoch 011 - train 0.37673 | val 1.56627
  Classification -> best τ=0.415 (val F1=0.0769)
  Directional -> Accuracy: 0.5476, MCC: 0.0000, F1: 0.7077

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.40080 | val 1.61059
  Epoch 011 - train 0.37296 | val 1.77727
  Classification -> best τ=0.485 (val F1=0.2399)
  Directional -> Accuracy: 0.5510, MCC: 0.2266, F1: 0.3125

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.44482 | val 0.81730
  Epoch 011 - train 0.39590 | val 0.94800
  Classification -> best τ=0.420 (val F1=0.3526)
  Directional -> Accuracy: 0.4583, MCC: 0.0244, F1: 0.1333

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.37768 | val 1.12083
  Epoch 011 - train 0.32541 | val 1.26117
  Classification -> best τ=0.455 (val F1=0.2814)
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.50815 | val 1.14348
  Epoch 011 - train 0.42359 | val 1.09179
  Classification -> best τ=0.490 (val F1=0.2249)
  Directional -> Accuracy: 0.5303, MCC: -0.1873, F1: 0.6931

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.27704 | val 1.37038
  Epoch 014 - train 0.11145 | val 1.84837
  Classification -> best τ=0.455 (val F1=0.3865)
  Directional -> Accuracy: 0.6667, MCC: 0.3364, F1: 0.6667

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.38393 | val 1.77886
  Epoch 012 - train 0.28959 | val 2.07125
  Classification -> best τ=0.475 (val F1=0.2382)
  Directional -> Accuracy: 0.5714, MCC: 0.1260, F1: 0.4545

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.34003 | val 0.92092
  Epoch 012 - train 0.25459 | val 1.01317
  Classification -> best τ=0.475 (val F1=0.4130)
  Directional -> Accuracy: 0.3913, MCC: -0.1022, F1: 0.2222

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.34510 | val 0.67629
  Epoch 016 - train 0.21217 | val 0.98165
  Classification -> best τ=0.440 (val F1=0.3476)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.44841 | val 1.54812
  Epoch 011 - train 0.40878 | val 1.48120
  Classification -> best τ=0.425 (val F1=0.2829)
  Directional -> Accuracy: 0.4459, MCC: -0.1279, F1: 0.3051

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.41723 | val 0.81005
  Epoch 011 - train 0.41966 | val 0.81510
  Classification -> best τ=0.475 (val F1=0.1941)
  Directional -> Accuracy: 0.6000, MCC: 0.2145, F1: 0.6786

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.35538 | val 0.94151
  Epoch 013 - train 0.16275 | val 1.16249
  Classification -> best τ=0.545 (val F1=0.3151)
  Directional -> Accuracy: 0.6905, MCC: 0.3586, F1: 0.7451

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.27679 | val 0.69375
  Epoch 018 - train 0.15265 | val 0.88928
  Classification -> best τ=0.475 (val F1=0.4682)
  Directional -> Accuracy: 0.5000, MCC: 0.2928, F1: 0.6000

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.41790 | val 1.69304
  Epoch 012 - train 0.40745 | val 1.66657
  Classification -> best τ=0.635 (val F1=0.2452)
  Directional -> Accuracy: 0.4727, MCC: 0.1242, F1: 0.0645

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.43995 | val 1.49193
  Epoch 013 - train 0.23456 | val 1.10904
  Classification -> best τ=0.425 (val F1=0.3570)
  Directional -> Accuracy: 0.5179, MCC: 0.0069, F1: 0.0690

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.45280 | val 0.99520
  Epoch 013 - train 0.25662 | val 1.17116
  Classification -> best τ=0.475 (val F1=0.1646)
  Directional -> Accuracy: 0.5283, MCC: 0.1413, F1: 0.6835

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.44505 | val 1.12815
  Epoch 012 - train 0.36896 | val 1.21524
  Classification -> best τ=0.470 (val F1=0.1884)
  Directional -> Accuracy: 0.4727, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.42957 | val 1.14498

[I 2026-02-22 11:03:56,621] Trial 123 finished with value: 0.2713032367582769 and parameters: {'feature_set': 'sector_emotion', 'model_type': 'BiGRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.2, 'batch_size': 64, 'learning_rate': 0.00807946869523841, 'weight_decay': 2.7631008851575323e-05, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 0.7348915158552543, 'early_stopping_min_delta': 0.0009640505259682491}. Best is trial 112 with value: 0.2833506688525635.

  Epoch 015 - train 0.34331 | val 1.09963
  Classification -> best τ=0.505 (val F1=0.3056)
  Directional -> Accuracy: 0.5667, MCC: 0.1911, F1: 0.2353

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2713032367582769
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d', 'emotion_anger', 'emotion_disgust', 'emotion_fear', 'emotion_joy', 'emotion_neutral', 'emotion_sadness', 'emotion_surprize', 'emotion_anger_pct', 'emotion_disgust_pct', 'emotion_fear_pct', 'emotion_joy_pct', 'emotion_neutral_pct', 'emotion_sadness_pct', 'emotion_surprize_pct']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.49925 | val 0.83755
  Epoch 015 - train 0.35353 | val 0.96644
  Classification -> best τ=0.535 (val F1=0.3286)
  Directional -> Accuracy: 0.5658, MCC: 0.1194, F1: 0.5075

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.35533 | val 0.80832
  Epoch 012 - train 0.32119 | val 0.89379
  Classification -> best τ=0.480 (val F1=0.2523)
  Directional -> Accuracy: 0.6667, MCC: 0.3002, F1: 0.7368

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.43177 | val 1.43008
  Epoch 011 - train 0.34322 | val 1.54172
  Classification -> best τ=0.460 (val F1=0.1854)
  Directional -> Accuracy: 0.5217, MCC: 0.0496, F1: 0.5000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.47563 | val 1.13313
  Epoch 012 - train 0.44367 | val 1.63043
  Classification -> best τ=0.460 (val F1=0.1725)
  Directional -> Accuracy: 0.5135, MCC: -0.1537, F1: 0.6786

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.34143 | val 1.10804
  Epoch 014 - train 0.31565 | val 1.26198
  Classification -> best τ=0.625 (val F1=0.2726)
  Directional -> Accuracy: 0.5600, MCC: 0.1650, F1: 0.4211

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.39504 | val 0.84672
  Epoch 014 - train 0.25407 | val 1.37860
  Classification -> best τ=0.540 (val F1=0.3210)
  Directional -> Accuracy: 0.4565, MCC: -0.1431, F1: 0.1935

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.46807 | val 1.94942
  Epoch 012 - train 0.39241 | val 1.98205
  Classification -> best τ=0.400 (val F1=0.2242)
  Directional -> Accuracy: 0.5000, MCC: 0.1034, F1: 0.5526

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.37365 | val 0.68175
  Epoch 018 - train 0.25301 | val 1.46820
  Classification -> best τ=0.305 (val F1=0.3094)
  Directional -> Accuracy: 0.4286, MCC: -0.0323, F1: 0.5862

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.39944 | val 0.88118
  Epoch 013 - train 0.31051 | val 1.51476
  Classification -> best τ=0.475 (val F1=0.3198)
  Directional -> Accuracy: 0.6667, MCC: 0.3228, F1: 0.6190

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.39930 | val 0.89444
  Epoch 012 - train 0.34605 | val 0.94418
  Classification -> best τ=0.455 (val F1=0.2667)
  Directional -> Accuracy: 0.4058, MCC: -0.1424, F1: 0.5773

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.43522 | val 1.29571
  Epoch 011 - train 0.41392 | val 1.46863
  Classification -> best τ=0.545 (val F1=0.1976)
  Directional -> Accuracy: 0.5918, MCC: 0.1804, F1: 0.2308

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.41821 | val 1.90143
  Epoch 011 - train 0.38290 | val 1.97696
  Classification -> best τ=0.390 (val F1=0.1083)
  Directional -> Accuracy: 0.5088, MCC: 0.0000, F1: 0.6744

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.42289 | val 1.50936
  Epoch 012 - train 0.33594 | val 1.43997
  Classification -> best τ=0.415 (val F1=0.0219)
  Directional -> Accuracy: 0.5000, MCC: 0.0454, F1: 0.5714

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.45709 | val 0.79165
  Epoch 015 - train 0.29376 | val 1.21360
  Classification -> best τ=0.485 (val F1=0.4317)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.43492 | val 0.96841
  Epoch 011 - train 0.40410 | val 1.32289
  Classification -> best τ=0.440 (val F1=0.1128)
  Directional -> Accuracy: 0.5490, MCC: 0.0728, F1: 0.4390

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.43639 | val 0.86601
  Epoch 011 - train 0.40656 | val 0.91435
  Classification -> best τ=0.455 (val F1=0.2224)
  Directional -> Accuracy: 0.5797, MCC: 0.1424, F1: 0.6667

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.42215 | val 1.70205
  Epoch 011 - train 0.34096 | val 1.69284
  Classification -> best τ=0.445 (val F1=0.0032)
  Directional -> Accuracy: 0.6207, MCC: 0.0000, F1: 0.7660

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.48731 | val 0.91134
  Epoch 011 - train 0.49587 | val 0.95811
  Classification -> best τ=0.560 (val F1=0.0635)
  Directional -> Accuracy: 0.4000, MCC: -0.0801, F1: 0.1818

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.40611 | val 1.54649
  Epoch 014 - train 0.27322 | val 1.30167
  Classification -> best τ=0.455 (val F1=0.3660)
  Directional -> Accuracy: 0.4062, MCC: -0.1050, F1: 0.0952

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.49580 | val 0.78532
  Epoch 012 - train 0.41515 | val 0.87256
  Classification -> best τ=0.395 (val F1=0.2816)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.34033 | val 1.23186
  Epoch 011 - train 0.31302 | val 1.45672
  Classification -> best τ=0.520 (val F1=0.1978)
  Directional -> Accuracy: 0.4468, MCC: -0.1043, F1: 0.5000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.48806 | val 0.95696
  Epoch 013 - train 0.30532 | val 1.04641
  Classification -> best τ=0.415 (val F1=0.1296)
  Directional -> Accuracy: 0.6000, MCC: 0.2197, F1: 0.5185

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.40567 | val 0.79442
  Epoch 015 - train 0.25029 | val 1.03873
  Classification -> best τ=0.505 (val F1=0.4239)
  Directional -> Accuracy: 0.5789, MCC: 0.1021, F1: 0.7000

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.47200 | val 0.89399
  Epoch 012 - train 0.40125 | val 0.92933
  Classification -> best τ=0.455 (val F1=0.1348)
  Directional -> Accuracy: 0.5231, MCC: 0.0428, F1: 0.4918

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.40189 | val 1.44866
  Epoch 013 - train 0.32232 | val 1.75494
  Classification -> best τ=0.490 (val F1=0.3472)
  Directional -> Accuracy: 0.5455, MCC: 0.1641, F1: 0.4186

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.20493 | val 0.99242
  Epoch 011 - train 0.22558 | val 1.05755
  Classification -> best τ=0.540 (val F1=0.2726)
  Directional -> Accuracy: 0.6000, MCC: 0.1764, F1: 0.1000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.35114 | val 0.76780
  Epoch 015 - train 0.21531 | val 1.16531
  Classification -> best τ=0.605 (val F1=0.3568)
  Directional -> Accuracy: 0.5238, MCC: 0.0142, F1: 0.6000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.38497 | val 1.29929
  Epoch 011 - train 0.42298 | val 1.36598
  Classification -> best τ=0.570 (val F1=0.1615)
  Directional -> Accuracy: 0.4464, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.34984 | val 0.95728
  Epoch 013 - train 0.25719 | val 1.14215
  Classification -> best τ=0.515 (val F1=0.2957)
  Directional -> Accuracy: 0.5750, MCC: 0.1143, F1: 0.6792

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.37589 | val 2.53645
  Epoch 011 - train 0.35428 | val 2.72298
  Classification -> best τ=0.650 (val F1=0.1959)
  Directional -> Accuracy: 0.5238, MCC: 0.0000, F1: 0.0000

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.42250 | val 1.19233
  Epoch 011 - train 0.34616 | val 1.36102
  Classification -> best τ=0.460 (val F1=0.1286)
  Directional -> Accuracy: 0.4286, MCC: -0.1070, F1: 0.2000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.49363 | val 1.39360
  Epoch 013 - train 0.35663 | val 1.89408
  Classification -> best τ=0.640 (val F1=0.3093)
  Directional -> Accuracy: 0.5306, MCC: 0.0771, F1: 0.4889

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.52708 | val 0.79536
  Epoch 014 - train 0.34125 | val 0.90778
  Classification -> best τ=0.410 (val F1=0.3610)
  Directional -> Accuracy: 0.5278, MCC: 0.0688, F1: 0.5278

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.38263 | val 0.98287
  Epoch 012 - train 0.31884 | val 1.16805
  Classification -> best τ=0.410 (val F1=0.3207)
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.49914 | val 1.54297
  Epoch 011 - train 0.45057 | val 1.49499
  Classification -> best τ=0.590 (val F1=0.1822)
  Directional -> Accuracy: 0.5303, MCC: -0.0266, F1: 0.6517

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.22399 | val 1.30995
  Epoch 014 - train 0.22200 | val 1.97342
  Classification -> best τ=0.605 (val F1=0.3828)
  Directional -> Accuracy: 0.5000, MCC: 0.0332, F1: 0.3226

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.42201 | val 1.85523
  Epoch 011 - train 0.36595 | val 2.20406
  Classification -> best τ=0.435 (val F1=0.2450)
  Directional -> Accuracy: 0.6071, MCC: 0.2717, F1: 0.6667

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.37611 | val 1.09816
  Epoch 014 - train 0.18581 | val 1.58555
  Classification -> best τ=0.485 (val F1=0.3024)
  Directional -> Accuracy: 0.4130, MCC: 0.0314, F1: 0.1290

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.34502 | val 0.69524
  Epoch 018 - train 0.14221 | val 1.09585
  Classification -> best τ=0.570 (val F1=0.4011)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.43225 | val 1.47669
  Epoch 012 - train 0.36096 | val 1.82610
  Classification -> best τ=0.515 (val F1=0.3293)
  Directional -> Accuracy: 0.4865, MCC: -0.0515, F1: 0.2692

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.45242 | val 0.76136
  Epoch 014 - train 0.33763 | val 1.15863
  Classification -> best τ=0.550 (val F1=0.3371)
  Directional -> Accuracy: 0.6000, MCC: 0.1996, F1: 0.6087

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.30620 | val 0.74038
  Epoch 013 - train 0.22172 | val 0.88346
  Classification -> best τ=0.485 (val F1=0.3333)
  Directional -> Accuracy: 0.5238, MCC: 0.1217, F1: 0.4444

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.31547 | val 0.84029
  Epoch 018 - train 0.05252 | val 1.05283
  Classification -> best τ=0.465 (val F1=0.3622)
  Directional -> Accuracy: 0.5208, MCC: 0.1509, F1: 0.5490

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.42904 | val 0.80683
  Epoch 015 - train 0.34914 | val 1.13687
  Classification -> best τ=0.520 (val F1=0.2448)
  Directional -> Accuracy: 0.3455, MCC: -0.3735, F1: 0.4706

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.37263 | val 1.94624
  Epoch 012 - train 0.26714 | val 1.38458
  Classification -> best τ=0.580 (val F1=0.3428)
  Directional -> Accuracy: 0.5536, MCC: 0.1072, F1: 0.5455

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.41913 | val 1.26196
  Epoch 012 - train 0.34415 | val 1.51539
  Classification -> best τ=0.520 (val F1=0.1796)
  Directional -> Accuracy: 0.6038, MCC: 0.2103, F1: 0.5882

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.38940 | val 0.81734
  Epoch 012 - train 0.31295 | val 0.79351
  Classification -> best τ=0.520 (val F1=0.3398)
  Directional -> Accuracy: 0.5273, MCC: 0.0982, F1: 0.3810

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.46164 | val 0.68035

[I 2026-02-22 11:05:16,565] Trial 124 finished with value: 0.25726012367200923 and parameters: {'feature_set': 'sector_emotion', 'model_type': 'BiGRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.2, 'batch_size': 64, 'learning_rate': 0.0059918278950468855, 'weight_decay': 5.311636805650797e-05, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 0.732874448611555, 'early_stopping_min_delta': 0.0009344923631834427}. Best is trial 112 with value: 0.2833506688525635.

  Epoch 015 - train 0.30127 | val 0.84808
  Classification -> best τ=0.515 (val F1=0.2691)
  Directional -> Accuracy: 0.5500, MCC: 0.0946, F1: 0.4706

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.25726012367200923
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d', 'emotion_anger', 'emotion_disgust', 'emotion_fear', 'emotion_joy', 'emotion_neutral', 'emotion_sadness', 'emotion_surprize', 'emotion_anger_pct', 'emotion_disgust_pct', 'emotion_fear_pct', 'emotion_joy_pct', 'emotion_neutral_pct', 'emotion_sadness_pct', 'emotion_surprize_pct']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.47563 | val 0.79510
  Epoch 012 - train 0.46068 | val 0.76326
  Classification -> best τ=0.625 (val F1=0.2036)
  Directional -> Accuracy: 0.5526, MCC: 0.0249, F1: 0.1053

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.35971 | val 0.88464
  Epoch 011 - train 0.31242 | val 0.95585
  Classification -> best τ=0.470 (val F1=0.0340)
  Directional -> Accuracy: 0.6000, MCC: 0.1323, F1: 0.7353

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.36864 | val 1.96565
  Epoch 012 - train 0.29874 | val 2.24246
  Classification -> best τ=0.650 (val F1=0.1383)
  Directional -> Accuracy: 0.4783, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.51202 | val 1.33822
  Epoch 012 - train 0.43737 | val 1.52559
  Classification -> best τ=0.560 (val F1=0.2329)
  Directional -> Accuracy: 0.4324, MCC: -0.2208, F1: 0.5714

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.32196 | val 1.17094
  Epoch 011 - train 0.32065 | val 1.28952
  Classification -> best τ=0.570 (val F1=0.4139)
  Directional -> Accuracy: 0.5800, MCC: 0.2044, F1: 0.4615

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.41487 | val 1.17334
  Epoch 013 - train 0.25280 | val 1.10926
  Classification -> best τ=0.455 (val F1=0.2701)
  Directional -> Accuracy: 0.4565, MCC: -0.0767, F1: 0.5283

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.42099 | val 1.97194
  Epoch 011 - train 0.38096 | val 1.89688
  Classification -> best τ=0.430 (val F1=0.2789)
  Directional -> Accuracy: 0.5147, MCC: 0.1115, F1: 0.5479

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.31456 | val 0.62426
  Epoch 015 - train 0.25766 | val 1.43578
  Classification -> best τ=0.295 (val F1=0.4215)
  Directional -> Accuracy: 0.4524, MCC: -0.0700, F1: 0.4651

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.31827 | val 1.46613
  Epoch 015 - train 0.24089 | val 1.83951
  Classification -> best τ=0.575 (val F1=0.3523)
  Directional -> Accuracy: 0.6042, MCC: 0.2673, F1: 0.6415

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.40534 | val 1.08225
  Epoch 014 - train 0.33750 | val 1.01621
  Classification -> best τ=0.395 (val F1=0.3006)
  Directional -> Accuracy: 0.4058, MCC: -0.1061, F1: 0.5393

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.40861 | val 1.54134
  Epoch 012 - train 0.32914 | val 2.12417
  Classification -> best τ=0.500 (val F1=0.1199)
  Directional -> Accuracy: 0.5510, MCC: 0.0212, F1: 0.0833

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.44556 | val 2.01216
  Epoch 011 - train 0.42214 | val 2.11773
  Classification -> best τ=0.395 (val F1=0.1512)
  Directional -> Accuracy: 0.5088, MCC: 0.0000, F1: 0.6744

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.38351 | val 2.02407
  Epoch 013 - train 0.29731 | val 2.83356
  Classification -> best τ=0.580 (val F1=0.1991)
  Directional -> Accuracy: 0.4524, MCC: -0.1105, F1: 0.3784

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.45987 | val 0.65900
  Epoch 015 - train 0.28663 | val 1.05252
  Classification -> best τ=0.555 (val F1=0.3864)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.40766 | val 1.07157
  Epoch 013 - train 0.33720 | val 1.30728
  Classification -> best τ=0.575 (val F1=0.1455)
  Directional -> Accuracy: 0.5490, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.42638 | val 1.72316
  Epoch 012 - train 0.34899 | val 1.88353
  Classification -> best τ=0.215 (val F1=0.2659)
  Directional -> Accuracy: 0.4783, MCC: -0.1352, F1: 0.6250

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.40525 | val 1.29859
  Epoch 011 - train 0.36899 | val 1.45168
  Classification -> best τ=0.455 (val F1=0.2391)
  Directional -> Accuracy: 0.6034, MCC: -0.1035, F1: 0.7527

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.47461 | val 1.06729
  Epoch 014 - train 0.37163 | val 1.55342
  Classification -> best τ=0.360 (val F1=0.1243)
  Directional -> Accuracy: 0.6000, MCC: 0.0000, F1: 0.7500

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.45033 | val 1.17985
  Epoch 011 - train 0.43073 | val 1.37129
  Classification -> best τ=0.390 (val F1=0.3622)
  Directional -> Accuracy: 0.5781, MCC: 0.1395, F1: 0.6301

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.50264 | val 1.02124
  Epoch 016 - train 0.33151 | val 1.07100
  Classification -> best τ=0.400 (val F1=0.2912)
  Directional -> Accuracy: 0.4324, MCC: -0.1305, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.33701 | val 1.11645
  Epoch 011 - train 0.33450 | val 1.28462
  Classification -> best τ=0.565 (val F1=0.1333)
  Directional -> Accuracy: 0.3830, MCC: -0.0921, F1: 0.1714

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.49236 | val 1.36909
  Epoch 012 - train 0.37554 | val 1.47869
  Classification -> best τ=0.495 (val F1=0.2381)
  Directional -> Accuracy: 0.4923, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.43872 | val 1.06167
  Epoch 014 - train 0.29164 | val 1.18486
  Classification -> best τ=0.455 (val F1=0.3457)
  Directional -> Accuracy: 0.5965, MCC: 0.1518, F1: 0.7160

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.47961 | val 1.40512
  Epoch 011 - train 0.42980 | val 1.30441
  Classification -> best τ=0.435 (val F1=0.1122)
  Directional -> Accuracy: 0.4462, MCC: -0.1866, F1: 0.6170

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.36557 | val 1.41238
  Epoch 013 - train 0.27794 | val 1.98478
  Classification -> best τ=0.440 (val F1=0.3643)
  Directional -> Accuracy: 0.5818, MCC: 0.2024, F1: 0.5306

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.22325 | val 1.02501
  Epoch 011 - train 0.25991 | val 1.13525
  Classification -> best τ=0.455 (val F1=0.2035)
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.5938

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.41166 | val 0.71771
  Epoch 014 - train 0.23685 | val 0.93740
  Classification -> best τ=0.595 (val F1=0.3536)
  Directional -> Accuracy: 0.4286, MCC: -0.0468, F1: 0.1429

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.45891 | val 1.97364
  Epoch 012 - train 0.36948 | val 1.94118
  Classification -> best τ=0.405 (val F1=0.1607)
  Directional -> Accuracy: 0.5536, MCC: 0.0000, F1: 0.7126

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.43538 | val 0.79308
  Epoch 017 - train 0.20600 | val 1.43222
  Classification -> best τ=0.375 (val F1=0.3296)
  Directional -> Accuracy: 0.6000, MCC: 0.2010, F1: 0.7241

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.36251 | val 1.46294
  Epoch 012 - train 0.32534 | val 1.14323
  Classification -> best τ=0.555 (val F1=0.3001)
  Directional -> Accuracy: 0.4762, MCC: -0.0608, F1: 0.3889

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.39255 | val 1.59340
  Epoch 011 - train 0.37363 | val 1.62481
  Classification -> best τ=0.405 (val F1=0.0409)
  Directional -> Accuracy: 0.5238, MCC: -0.1419, F1: 0.6875

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.38298 | val 1.18875
  Epoch 013 - train 0.28801 | val 2.02005
  Classification -> best τ=0.275 (val F1=0.3232)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.51714 | val 0.75331
  Epoch 016 - train 0.28039 | val 1.12663
  Classification -> best τ=0.465 (val F1=0.2992)
  Directional -> Accuracy: 0.4444, MCC: -0.0189, F1: 0.0476

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.37376 | val 1.10229
  Epoch 012 - train 0.32186 | val 1.30524
  Classification -> best τ=0.380 (val F1=0.2057)
  Directional -> Accuracy: 0.5349, MCC: 0.0658, F1: 0.4444

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.47545 | val 0.93928
  Epoch 011 - train 0.46508 | val 1.02044
  Classification -> best τ=0.465 (val F1=0.2464)
  Directional -> Accuracy: 0.6061, MCC: 0.1551, F1: 0.7347

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.32588 | val 1.68955
  Epoch 013 - train 0.20666 | val 2.33868
  Classification -> best τ=0.495 (val F1=0.2858)
  Directional -> Accuracy: 0.4524, MCC: -0.0835, F1: 0.3429

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.39885 | val 1.64440
  Epoch 011 - train 0.36284 | val 1.89936
  Classification -> best τ=0.430 (val F1=0.2110)
  Directional -> Accuracy: 0.5357, MCC: 0.1132, F1: 0.6061

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.31142 | val 1.17932
  Epoch 013 - train 0.21885 | val 1.36743
  Classification -> best τ=0.550 (val F1=0.3383)
  Directional -> Accuracy: 0.3913, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.35114 | val 0.75291
  Epoch 016 - train 0.18873 | val 1.06067
  Classification -> best τ=0.465 (val F1=0.4556)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.47232 | val 2.11857
  Epoch 011 - train 0.47887 | val 2.00570
  Classification -> best τ=0.395 (val F1=0.2700)
  Directional -> Accuracy: 0.4730, MCC: -0.0638, F1: 0.3810

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.51275 | val 0.80243
  Epoch 011 - train 0.47910 | val 0.85734
  Classification -> best τ=0.505 (val F1=0.1512)
  Directional -> Accuracy: 0.5111, MCC: 0.0000, F1: 0.6765

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.25362 | val 0.75813
  Epoch 016 - train 0.15433 | val 1.25034
  Classification -> best τ=0.485 (val F1=0.4277)
  Directional -> Accuracy: 0.5476, MCC: 0.0829, F1: 0.5957

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.29825 | val 0.73267
  Epoch 018 - train 0.13796 | val 1.06228
  Classification -> best τ=0.400 (val F1=0.4682)
  Directional -> Accuracy: 0.6250, MCC: 0.3333, F1: 0.6250

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.44682 | val 1.06905
  Epoch 012 - train 0.40171 | val 1.14034
  Classification -> best τ=0.645 (val F1=0.2036)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.38318 | val 1.08252
  Epoch 014 - train 0.23453 | val 1.20669
  Classification -> best τ=0.600 (val F1=0.3487)
  Directional -> Accuracy: 0.5179, MCC: 0.0099, F1: 0.1290

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.38967 | val 1.28737
  Epoch 011 - train 0.37288 | val 1.41398
  Classification -> best τ=0.565 (val F1=0.1479)
  Directional -> Accuracy: 0.5660, MCC: 0.1308, F1: 0.5965

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.43445 | val 0.72009
  Epoch 011 - train 0.38962 | val 0.90757
  Classification -> best τ=0.490 (val F1=0.2085)
  Directional -> Accuracy: 0.4909, MCC: 0.0074, F1: 0.3636

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.45175 | val 1.00530

[I 2026-02-22 11:06:35,673] Trial 125 finished with value: 0.25724092185267283 and parameters: {'feature_set': 'sector_emotion', 'model_type': 'BiGRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.2, 'batch_size': 64, 'learning_rate': 0.007723942516036227, 'weight_decay': 2.6042548339448052e-05, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 0.6324736534305524, 'early_stopping_min_delta': 0.0005693448166356796}. Best is trial 112 with value: 0.2833506688525635.

  Epoch 016 - train 0.32607 | val 0.83234
  Classification -> best τ=0.325 (val F1=0.2441)
  Directional -> Accuracy: 0.6000, MCC: 0.2658, F1: 0.6842

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.25724092185267283
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d', 'emotion_anger', 'emotion_disgust', 'emotion_fear', 'emotion_joy', 'emotion_neutral', 'emotion_sadness', 'emotion_surprize', 'emotion_anger_pct', 'emotion_disgust_pct', 'emotion_fear_pct', 'emotion_joy_pct', 'emotion_neutral_pct', 'emotion_sadness_pct', 'emotion_surprize_pct']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.50841 | val 0.75083
  Epoch 016 - train 0.40591 | val 0.79860
  Classification -> best τ=0.575 (val F1=0.3286)
  Directional -> Accuracy: 0.5789, MCC: 0.1534, F1: 0.5429

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.39461 | val 0.83844
  Epoch 011 - train 0.34173 | val 0.85564
  Classification -> best τ=0.450 (val F1=0.2025)
  Directional -> Accuracy: 0.5778, MCC: 0.0000, F1: 0.7324

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.39872 | val 1.44216
  Epoch 011 - train 0.41651 | val 1.54069
  Classification -> best τ=0.555 (val F1=0.1383)
  Directional -> Accuracy: 0.4565, MCC: -0.0996, F1: 0.0741

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.54097 | val 2.57034
  Epoch 012 - train 0.46814 | val 1.64352
  Classification -> best τ=0.450 (val F1=0.1725)
  Directional -> Accuracy: 0.5135, MCC: -0.0231, F1: 0.6327

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.39002 | val 1.00967
  Epoch 013 - train 0.34200 | val 1.18756
  Classification -> best τ=0.520 (val F1=0.4342)
  Directional -> Accuracy: 0.6400, MCC: 0.2942, F1: 0.6087

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.41252 | val 1.07297
  Epoch 011 - train 0.34352 | val 0.97173
  Classification -> best τ=0.495 (val F1=0.2204)
  Directional -> Accuracy: 0.5000, MCC: -0.1427, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.48740 | val 0.93713
  Epoch 012 - train 0.45037 | val 1.08885
  Classification -> best τ=0.485 (val F1=0.2766)
  Directional -> Accuracy: 0.5000, MCC: 0.0578, F1: 0.5143

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.39845 | val 1.12300
  Epoch 017 - train 0.26833 | val 1.89073
  Classification -> best τ=0.595 (val F1=0.5247)
  Directional -> Accuracy: 0.4286, MCC: -0.1021, F1: 0.4783

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.34208 | val 1.06937
  Epoch 013 - train 0.30056 | val 1.48271
  Classification -> best τ=0.510 (val F1=0.2584)
  Directional -> Accuracy: 0.6667, MCC: 0.3310, F1: 0.6364

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.41841 | val 0.75749
  Epoch 012 - train 0.40163 | val 0.78252
  Classification -> best τ=0.430 (val F1=0.1858)
  Directional -> Accuracy: 0.4203, MCC: 0.0000, F1: 0.5918

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.40699 | val 1.06570
  Epoch 012 - train 0.32212 | val 1.28903
  Classification -> best τ=0.545 (val F1=0.1965)
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.43048 | val 2.37539
  Epoch 011 - train 0.41376 | val 2.38320
  Classification -> best τ=0.435 (val F1=0.2157)
  Directional -> Accuracy: 0.5088, MCC: 0.0000, F1: 0.6744

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.47767 | val 1.50625
  Epoch 011 - train 0.40869 | val 1.76555
  Classification -> best τ=0.520 (val F1=0.0875)
  Directional -> Accuracy: 0.5714, MCC: 0.1083, F1: 0.3571

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.52703 | val 0.76806
  Epoch 016 - train 0.35625 | val 1.07244
  Classification -> best τ=0.575 (val F1=0.3864)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.46912 | val 1.14325
  Epoch 013 - train 0.36987 | val 1.62341
  Classification -> best τ=0.630 (val F1=0.2078)
  Directional -> Accuracy: 0.5490, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.47710 | val 1.19290
  Epoch 012 - train 0.40016 | val 1.21557
  Classification -> best τ=0.315 (val F1=0.2659)
  Directional -> Accuracy: 0.5362, MCC: 0.0224, F1: 0.6800

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.44366 | val 0.96243
  Epoch 011 - train 0.42172 | val 0.99003
  Classification -> best τ=0.570 (val F1=0.1774)
  Directional -> Accuracy: 0.3793, MCC: -0.0845, F1: 0.1429

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.47860 | val 1.18165
  Epoch 011 - train 0.47199 | val 1.24475
  Classification -> best τ=0.580 (val F1=0.0245)
  Directional -> Accuracy: 0.4267, MCC: -0.1755, F1: 0.5057

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.49515 | val 0.91767
  Epoch 015 - train 0.33613 | val 1.00012
  Classification -> best τ=0.275 (val F1=0.3421)
  Directional -> Accuracy: 0.4688, MCC: -0.0891, F1: 0.5405

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.50651 | val 0.83013
  Epoch 013 - train 0.41663 | val 0.84877
  Classification -> best τ=0.400 (val F1=0.3669)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.35069 | val 0.92975
  Epoch 011 - train 0.39008 | val 0.96301
  Classification -> best τ=0.440 (val F1=0.1039)
  Directional -> Accuracy: 0.6170, MCC: 0.0000, F1: 0.7632

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.45443 | val 0.88206
  Epoch 015 - train 0.27596 | val 1.48574
  Classification -> best τ=0.430 (val F1=0.3229)
  Directional -> Accuracy: 0.5538, MCC: 0.1341, F1: 0.4082

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.40135 | val 0.75471
  Epoch 014 - train 0.37200 | val 0.94081
  Classification -> best τ=0.495 (val F1=0.4032)
  Directional -> Accuracy: 0.6316, MCC: 0.2729, F1: 0.7470

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.47094 | val 1.02333
  Epoch 012 - train 0.41436 | val 1.30553
  Classification -> best τ=0.485 (val F1=0.2298)
  Directional -> Accuracy: 0.4923, MCC: 0.0632, F1: 0.6452

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.39379 | val 1.17619
  Epoch 014 - train 0.33819 | val 1.57183
  Classification -> best τ=0.360 (val F1=0.4903)
  Directional -> Accuracy: 0.6182, MCC: 0.2193, F1: 0.6866

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.37183 | val 0.81196
  Epoch 012 - train 0.33165 | val 0.78418
  Classification -> best τ=0.505 (val F1=0.4328)
  Directional -> Accuracy: 0.4222, MCC: -0.0618, F1: 0.5517

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.41252 | val 0.69565
  Epoch 017 - train 0.28363 | val 1.00768
  Classification -> best τ=0.505 (val F1=0.3568)
  Directional -> Accuracy: 0.6190, MCC: 0.1964, F1: 0.7333

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.47947 | val 1.18867
  Epoch 011 - train 0.43240 | val 1.21907
  Classification -> best τ=0.525 (val F1=0.1238)
  Directional -> Accuracy: 0.4464, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.43087 | val 0.82039
  Epoch 013 - train 0.34367 | val 0.81447
  Classification -> best τ=0.455 (val F1=0.3671)
  Directional -> Accuracy: 0.6000, MCC: 0.1759, F1: 0.7037

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.45302 | val 1.62172
  Epoch 012 - train 0.40575 | val 2.10854
  Classification -> best τ=0.625 (val F1=0.1959)
  Directional -> Accuracy: 0.5238, MCC: 0.0000, F1: 0.0000

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.45123 | val 1.01733
  Epoch 011 - train 0.38437 | val 1.32920
  Classification -> best τ=0.485 (val F1=0.0128)
  Directional -> Accuracy: 0.4524, MCC: -0.0214, F1: 0.0800

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.40738 | val 1.57134
  Epoch 013 - train 0.33678 | val 1.72969
  Classification -> best τ=0.485 (val F1=0.4404)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.49343 | val 0.83463
  Epoch 013 - train 0.39687 | val 1.05517
  Classification -> best τ=0.460 (val F1=0.3263)
  Directional -> Accuracy: 0.4444, MCC: 0.0000, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.42790 | val 1.02403
  Epoch 012 - train 0.40843 | val 1.06312
  Classification -> best τ=0.450 (val F1=0.3078)
  Directional -> Accuracy: 0.5814, MCC: 0.1993, F1: 0.3571

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.52077 | val 0.79904
  Epoch 015 - train 0.41754 | val 1.10279
  Classification -> best τ=0.370 (val F1=0.3525)
  Directional -> Accuracy: 0.5000, MCC: -0.0998, F1: 0.6292

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.28443 | val 1.14903
  Epoch 012 - train 0.25781 | val 1.44841
  Classification -> best τ=0.460 (val F1=0.2839)
  Directional -> Accuracy: 0.5714, MCC: 0.1376, F1: 0.6087

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.39261 | val 1.74934
  Epoch 011 - train 0.38130 | val 1.83945
  Classification -> best τ=0.530 (val F1=0.2724)
  Directional -> Accuracy: 0.4821, MCC: -0.0437, F1: 0.4314

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.39950 | val 0.83638
  Epoch 015 - train 0.27533 | val 1.21135
  Classification -> best τ=0.505 (val F1=0.3438)
  Directional -> Accuracy: 0.4348, MCC: -0.0094, F1: 0.3158

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.47620 | val 0.71182
  Epoch 017 - train 0.27887 | val 0.82574
  Classification -> best τ=0.530 (val F1=0.4011)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.41531 | val 1.70099
  Epoch 011 - train 0.42352 | val 1.84180
  Classification -> best τ=0.445 (val F1=0.2674)
  Directional -> Accuracy: 0.5000, MCC: 0.1139, F1: 0.6606

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.48022 | val 0.77762
  Epoch 011 - train 0.42551 | val 0.73901
  Classification -> best τ=0.465 (val F1=0.3371)
  Directional -> Accuracy: 0.5333, MCC: 0.1493, F1: 0.2222

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.29456 | val 0.77546
  Epoch 012 - train 0.32466 | val 0.89501
  Classification -> best τ=0.555 (val F1=0.2041)
  Directional -> Accuracy: 0.4286, MCC: -0.0323, F1: 0.0769

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.43656 | val 0.65726
  Epoch 020 - train 0.19865 | val 0.73037
  Epoch 021 - train 0.09679 | val 0.81463
  Classification -> best τ=0.670 (val F1=0.3311)
  Directional -> Accuracy: 0.5208, MCC: 0.0990, F1: 0.5106

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.50695 | val 1.13936
  Epoch 014 - train 0.40431 | val 1.30995
  Classification -> best τ=0.585 (val F1=0.2132)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.34633 | val 1.44954
  Epoch 011 - train 0.33006 | val 1.77072
  Classification -> best τ=0.480 (val F1=0.1949)
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.6506

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.47452 | val 0.86682
  Epoch 012 - train 0.42920 | val 0.91600
  Classification -> best τ=0.480 (val F1=0.1847)
  Directional -> Accuracy: 0.6415, MCC: 0.2960, F1: 0.6984

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.42618 | val 1.21362
  Epoch 011 - train 0.38717 | val 1.42928
  Classification -> best τ=0.495 (val F1=0.2036)
  Directional -> Accuracy: 0.5273, MCC: 0.0000, F1: 0.6905

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.47776 | val 0.74818

[I 2026-02-22 11:07:56,050] Trial 126 finished with value: 0.27508785918997236 and parameters: {'feature_set': 'sector_emotion', 'model_type': 'BiGRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.30000000000000004, 'batch_size': 64, 'learning_rate': 0.004218155852809594, 'weight_decay': 2.3609069565526225e-05, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 0.9448488871047747, 'early_stopping_min_delta': 0.0002704522314752921}. Best is trial 112 with value: 0.2833506688525635.

  Epoch 019 - train 0.24783 | val 0.78311
  Classification -> best τ=0.555 (val F1=0.4877)
  Directional -> Accuracy: 0.5167, MCC: 0.0062, F1: 0.0645

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.27508785918997236
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d', 'emotion_anger', 'emotion_disgust', 'emotion_fear', 'emotion_joy', 'emotion_neutral', 'emotion_sadness', 'emotion_surprize', 'emotion_anger_pct', 'emotion_disgust_pct', 'emotion_fear_pct', 'emotion_joy_pct', 'emotion_neutral_pct', 'emotion_sadness_pct', 'emotion_surprize_pct']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.49372 | val 0.88238
  Epoch 012 - train 0.45660 | val 1.17491
  Classification -> best τ=0.455 (val F1=0.2034)
  Directional -> Accuracy: 0.6053, MCC: 0.2064, F1: 0.5714

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.38071 | val 1.11278
  Epoch 011 - train 0.32105 | val 0.92257
  Classification -> best τ=0.465 (val F1=0.1591)
  Directional -> Accuracy: 0.5778, MCC: 0.0000, F1: 0.7324

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.41822 | val 1.28049
  Epoch 011 - train 0.39751 | val 1.43474
  Classification -> best τ=0.560 (val F1=0.1383)
  Directional -> Accuracy: 0.5217, MCC: 0.1124, F1: 0.2667

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.52916 | val 1.58073
  Epoch 011 - train 0.48286 | val 1.35729
  Classification -> best τ=0.505 (val F1=0.2739)
  Directional -> Accuracy: 0.4595, MCC: -0.0393, F1: 0.2593

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.39411 | val 1.25993
  Epoch 011 - train 0.33988 | val 1.29027
  Classification -> best τ=0.485 (val F1=0.4493)
  Directional -> Accuracy: 0.6400, MCC: 0.3036, F1: 0.5909

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.45797 | val 0.73242
  Epoch 013 - train 0.34672 | val 0.98776
  Classification -> best τ=0.525 (val F1=0.2470)
  Directional -> Accuracy: 0.5652, MCC: 0.1284, F1: 0.3750

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.49252 | val 1.22956
  Epoch 012 - train 0.44424 | val 1.73542
  Classification -> best τ=0.455 (val F1=0.2766)
  Directional -> Accuracy: 0.4706, MCC: 0.0364, F1: 0.5263

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.42132 | val 0.90987
  Epoch 017 - train 0.20383 | val 2.53683
  Classification -> best τ=0.450 (val F1=0.5247)
  Directional -> Accuracy: 0.4286, MCC: -0.0913, F1: 0.5000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.44380 | val 0.92430
  Epoch 013 - train 0.36397 | val 1.47841
  Classification -> best τ=0.545 (val F1=0.2154)
  Directional -> Accuracy: 0.5625, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.46195 | val 0.82855
  Epoch 014 - train 0.39188 | val 0.94225
  Classification -> best τ=0.375 (val F1=0.2293)
  Directional -> Accuracy: 0.4203, MCC: -0.0279, F1: 0.5833

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.43552 | val 1.12297
  Epoch 011 - train 0.44607 | val 1.18706
  Classification -> best τ=0.520 (val F1=0.1593)
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.40187 | val 2.04438
  Epoch 011 - train 0.42926 | val 2.18731
  Classification -> best τ=0.475 (val F1=0.1055)
  Directional -> Accuracy: 0.6140, MCC: 0.3491, F1: 0.7250

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.37251 | val 1.10717
  Epoch 011 - train 0.37306 | val 1.26956
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.6230

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.48688 | val 0.73252
  Epoch 012 - train 0.38588 | val 0.77664
  Classification -> best τ=0.440 (val F1=0.4651)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.46341 | val 0.86071
  Epoch 015 - train 0.36156 | val 1.00841
  Classification -> best τ=0.505 (val F1=0.2280)
  Directional -> Accuracy: 0.4510, MCC: -0.0287, F1: 0.6000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.49974 | val 1.20771
  Epoch 012 - train 0.43474 | val 1.29359
  Classification -> best τ=0.345 (val F1=0.2659)
  Directional -> Accuracy: 0.5507, MCC: 0.0867, F1: 0.6990

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.44363 | val 1.32789
  Epoch 011 - train 0.41438 | val 1.35708
  Classification -> best τ=0.620 (val F1=0.1510)
  Directional -> Accuracy: 0.3621, MCC: -0.1467, F1: 0.1395

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.52148 | val 1.28543
  Epoch 011 - train 0.48175 | val 1.45146
  Classification -> best τ=0.575 (val F1=0.1087)
  Directional -> Accuracy: 0.4000, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.48174 | val 0.75324
  Epoch 015 - train 0.35169 | val 0.99032
  Classification -> best τ=0.365 (val F1=0.3513)
  Directional -> Accuracy: 0.5156, MCC: -0.0187, F1: 0.6076

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.47118 | val 0.88986
  Epoch 012 - train 0.45468 | val 0.87494
  Classification -> best τ=0.380 (val F1=0.2642)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.37366 | val 1.02886
  Epoch 013 - train 0.30988 | val 1.48427
  Classification -> best τ=0.375 (val F1=0.2784)
  Directional -> Accuracy: 0.6170, MCC: 0.0000, F1: 0.7632

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.47878 | val 1.24554
  Epoch 012 - train 0.41200 | val 1.14050
  Classification -> best τ=0.540 (val F1=0.1960)
  Directional -> Accuracy: 0.4923, MCC: -0.0039, F1: 0.1081

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.48747 | val 0.72120
  Epoch 017 - train 0.28248 | val 0.91217
  Classification -> best τ=0.550 (val F1=0.4455)
  Directional -> Accuracy: 0.5614, MCC: 0.0571, F1: 0.6835

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.49025 | val 0.79407
  Epoch 012 - train 0.42234 | val 0.92630
  Classification -> best τ=0.405 (val F1=0.1599)
  Directional -> Accuracy: 0.4769, MCC: -0.0147, F1: 0.6222

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.43597 | val 1.16038
  Epoch 014 - train 0.30134 | val 1.63388
  Classification -> best τ=0.475 (val F1=0.3749)
  Directional -> Accuracy: 0.5455, MCC: 0.1491, F1: 0.4444

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.32822 | val 0.78815
  Epoch 011 - train 0.29978 | val 0.77697
  Classification -> best τ=0.510 (val F1=0.0198)
  Directional -> Accuracy: 0.4444, MCC: -0.0763, F1: 0.4681

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.43505 | val 0.67820
  Epoch 014 - train 0.38146 | val 0.76741
  Classification -> best τ=0.500 (val F1=0.3728)
  Directional -> Accuracy: 0.5476, MCC: -0.0212, F1: 0.6885

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.44902 | val 1.09667
  Epoch 012 - train 0.40952 | val 1.26724
  Classification -> best τ=0.455 (val F1=0.1083)
  Directional -> Accuracy: 0.5000, MCC: -0.2137, F1: 0.6667

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.39210 | val 0.71264
  Epoch 017 - train 0.22567 | val 1.00248
  Classification -> best τ=0.445 (val F1=0.4382)
  Directional -> Accuracy: 0.5250, MCC: -0.0380, F1: 0.6667

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.47301 | val 1.47041
  Epoch 012 - train 0.37503 | val 1.31892
  Classification -> best τ=0.615 (val F1=0.3501)
  Directional -> Accuracy: 0.5000, MCC: -0.0561, F1: 0.1600

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.40317 | val 1.82228
  Epoch 012 - train 0.40912 | val 2.37740
  Classification -> best τ=0.590 (val F1=0.1286)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.43859 | val 1.41305
  Epoch 014 - train 0.30963 | val 2.25571
  Classification -> best τ=0.645 (val F1=0.2837)
  Directional -> Accuracy: 0.4490, MCC: -0.1422, F1: 0.5574

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.47328 | val 1.01550
  Epoch 012 - train 0.41563 | val 0.97663
  Classification -> best τ=0.405 (val F1=0.3801)
  Directional -> Accuracy: 0.5139, MCC: 0.0916, F1: 0.4068

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.40853 | val 0.97568
  Epoch 011 - train 0.39437 | val 0.98623
  Classification -> best τ=0.580 (val F1=0.2603)
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.54390 | val 1.11772
  Epoch 011 - train 0.52337 | val 1.12743
  Classification -> best τ=0.485 (val F1=0.2778)
  Directional -> Accuracy: 0.5758, MCC: 0.0000, F1: 0.7308

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.34664 | val 1.06086
  Epoch 014 - train 0.22450 | val 1.27226
  Classification -> best τ=0.440 (val F1=0.3758)
  Directional -> Accuracy: 0.5714, MCC: 0.1386, F1: 0.6667

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.40981 | val 1.68259
  Epoch 011 - train 0.42021 | val 1.56958
  Classification -> best τ=0.470 (val F1=0.1832)
  Directional -> Accuracy: 0.5179, MCC: 0.0185, F1: 0.4255

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.33829 | val 0.78734
  Epoch 013 - train 0.29447 | val 0.84895
  Classification -> best τ=0.520 (val F1=0.3352)
  Directional -> Accuracy: 0.3696, MCC: -0.1493, F1: 0.1212

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.42636 | val 0.70718
  Epoch 017 - train 0.24329 | val 0.94524
  Classification -> best τ=0.420 (val F1=0.3656)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.45672 | val 1.34482
  Epoch 011 - train 0.43556 | val 1.26435
  Classification -> best τ=0.445 (val F1=0.3031)
  Directional -> Accuracy: 0.4865, MCC: 0.0000, F1: 0.6545

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.47520 | val 0.93942
  Epoch 012 - train 0.41099 | val 0.90451
  Classification -> best τ=0.485 (val F1=0.2582)
  Directional -> Accuracy: 0.5778, MCC: 0.1935, F1: 0.6885

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.33608 | val 0.75017
  Epoch 014 - train 0.24872 | val 0.76028
  Classification -> best τ=0.495 (val F1=0.2632)
  Directional -> Accuracy: 0.5952, MCC: 0.2240, F1: 0.5854

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.44517 | val 0.65464
  Epoch 020 - train 0.16601 | val 1.13398
  Epoch 023 - train 0.12019 | val 0.99977
  Classification -> best τ=0.680 (val F1=0.3737)
  Directional -> Accuracy: 0.6042, MCC: 0.2750, F1: 0.5957

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.40957 | val 0.97737
  Epoch 013 - train 0.34416 | val 1.25340
  Classification -> best τ=0.570 (val F1=0.1784)
  Directional -> Accuracy: 0.4727, MCC: 0.1242, F1: 0.0645

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.38827 | val 1.27645
  Epoch 011 - train 0.34696 | val 1.19713
  Classification -> best τ=0.465 (val F1=0.3536)
  Directional -> Accuracy: 0.5000, MCC: 0.0187, F1: 0.5882

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.42263 | val 1.01382
  Epoch 012 - train 0.37365 | val 1.11571
  Classification -> best τ=0.495 (val F1=0.1968)
  Directional -> Accuracy: 0.6226, MCC: 0.2457, F1: 0.6552

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.45342 | val 1.02719
  Epoch 011 - train 0.40563 | val 0.97942
  Classification -> best τ=0.510 (val F1=0.2036)
  Directional -> Accuracy: 0.5273, MCC: 0.0000, F1: 0.6905

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.50162 | val 0.68104
  Epoch 020 - train 0.27816 | val 0.89829
  Epoch 021 - train 0.25597 | val 0.90255
  Classification -> best τ=0.695 (val F1=0.3496)
  Directional -> Accuracy: 0.5000, MCC: -0.0689, F1: 0.0625

[I 2026-02-22 11:09:16,296] Trial 127 finished with value: 0.263132944954373 and parameters: {'feature_set': 'sector_emotion', 'model_type': 'BiGRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.30000000000000004, 'batch_size': 64, 'learning_rate': 0.004611943035113241, 'weight_decay': 2.5638857075197754e-05, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 0.8876213907075845, 'early_stopping_min_delta': 0.0015771629258721491}. Best is trial 112 with value: 0.2833506688525635.

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.263132944954373
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d', 'emotion_anger', 'emotion_disgust', 'emotion_fear', 'emotion_joy', 'emotion_neutral', 'emotion_sadness', 'emotion_surprize', 'emotion_anger_pct', 'emotion_disgust_pct', 'emotion_fear_pct', 'emotion_joy_pct', 'emotion_neutral_pct', 'emotion_sadness_pct', 'emotion_surprize_pct']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.65486 | val 0.69124
  Epoch 017 - train 0.63071 | val 0.70377
  Classification -> best τ=0.430 (val F1=0.1341)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.65225 | val 0.68866
  Epoch 017 - train 0.63493 | val 0.72007
  Classification -> best τ=0.435 (val F1=0.1462)
  Directional -> Accuracy: 0.6087, MCC: 0.2431, F1: 0.7429

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.66792 | val 0.70498
  Epoch 011 - train 0.67760 | val 0.70654
  Classification -> best τ=0.490 (val F1=0.1586)
  Directional -> Accuracy: 0.5532, MCC: 0.1572, F1: 0.7042

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.65944 | val 0.78128
  Epoch 011 - train 0.65910 | val 0.79861
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.65703 | val 0.67776
  Epoch 020 - train 0.60914 | val 0.69033
  Epoch 022 - train 0.62520 | val 0.69080
  Classification -> best τ=0.460 (val F1=0.4858)
  Directional -> Accuracy: 0.6078, MCC: 0.2637, F1: 0.5238

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.65394 | val 0.69030
  Epoch 019 - train 0.61323 | val 0.70145
  Classification -> best τ=0.485 (val F1=0.2901)
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.66120 | val 0.68543
  Epoch 019 - train 0.64548 | val 0.69143
  Classification -> best τ=0.460 (val F1=0.2607)
  Directional -> Accuracy: 0.5362, MCC: 0.1985, F1: 0.6000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.66603 | val 0.74081
  Epoch 011 - train 0.65420 | val 0.74219
  Classification -> best τ=0.540 (val F1=0.1729)
  Directional -> Accuracy: 0.4091, MCC: -0.1688, F1: 0.3810

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.66088 | val 0.70184
  Epoch 020 - train 0.65100 | val 0.69244
  Epoch 030 - train 0.60905 | val 0.68780
  Classification -> best τ=0.410 (val F1=0.3301)
  Directional -> Accuracy: 0.6327, MCC: 0.3325, F1: 0.6786

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.64234 | val 0.71749
  Epoch 014 - train 0.63075 | val 0.72968
  Classification -> best τ=0.465 (val F1=0.2576)
  Directional -> Accuracy: 0.4429, MCC: 0.0407, F1: 0.5979

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.64503 | val 0.71005
  Epoch 018 - train 0.62192 | val 0.76461
  Classification -> best τ=0.590 (val F1=0.2500)
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.65137 | val 0.74836
  Epoch 011 - train 0.65392 | val 0.76010
  Classification -> best τ=0.490 (val F1=0.2453)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.2564

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.64150 | val 0.69453
  Epoch 011 - train 0.63295 | val 0.69776
  Classification -> best τ=0.555 (val F1=0.1700)
  Directional -> Accuracy: 0.5116, MCC: -0.0880, F1: 0.1600

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.64456 | val 0.62857
  Epoch 020 - train 0.61487 | val 0.63178
  Epoch 023 - train 0.61442 | val 0.63308
  Classification -> best τ=0.390 (val F1=0.3523)
  Directional -> Accuracy: 0.5246, MCC: 0.0744, F1: 0.3256

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.66102 | val 0.75278
  Epoch 011 - train 0.65150 | val 0.75763
  Classification -> best τ=0.525 (val F1=0.1762)
  Directional -> Accuracy: 0.5962, MCC: 0.2673, F1: 0.6667

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.65683 | val 0.69305
  Epoch 015 - train 0.63710 | val 0.70373
  Classification -> best τ=0.445 (val F1=0.2516)
  Directional -> Accuracy: 0.5429, MCC: 0.0000, F1: 0.7037

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.65316 | val 0.72675
  Epoch 011 - train 0.65880 | val 0.73606
  Classification -> best τ=0.520 (val F1=0.2366)
  Directional -> Accuracy: 0.4407, MCC: 0.0182, F1: 0.3529

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.65351 | val 0.72039
  Epoch 012 - train 0.65281 | val 0.73195
  Classification -> best τ=0.540 (val F1=0.1923)
  Directional -> Accuracy: 0.3947, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.65678 | val 0.67799
  Epoch 020 - train 0.62383 | val 0.67831
  Epoch 023 - train 0.61835 | val 0.68081
  Classification -> best τ=0.320 (val F1=0.2464)
  Directional -> Accuracy: 0.5692, MCC: 0.2237, F1: 0.5172

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.64830 | val 0.66312
  Epoch 020 - train 0.61561 | val 0.66660
  Epoch 021 - train 0.62207 | val 0.66895
  Classification -> best τ=0.350 (val F1=0.3236)
  Directional -> Accuracy: 0.4667, MCC: 0.1059, F1: 0.0476

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.66579 | val 0.72692
  Epoch 011 - train 0.66726 | val 0.73151
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.65506 | val 0.68731
  Epoch 017 - train 0.64234 | val 0.69863
  Classification -> best τ=0.465 (val F1=0.2550)
  Directional -> Accuracy: 0.4848, MCC: -0.0727, F1: 0.0556

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.66919 | val 0.65604
  Epoch 020 - train 0.65531 | val 0.66380
  Epoch 022 - train 0.63641 | val 0.66582
  Classification -> best τ=0.765 (val F1=0.2967)
  Directional -> Accuracy: 0.4655, MCC: 0.0453, F1: 0.2439

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.63486 | val 0.68186
  Epoch 018 - train 0.60655 | val 0.68353
  Classification -> best τ=0.500 (val F1=0.2453)
  Directional -> Accuracy: 0.4697, MCC: -0.0400, F1: 0.5455

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.65287 | val 0.65716
  Epoch 020 - train 0.63382 | val 0.67052
  Classification -> best τ=0.455 (val F1=0.3394)
  Directional -> Accuracy: 0.5357, MCC: 0.0926, F1: 0.5185

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.63585 | val 0.70148
  Epoch 011 - train 0.63144 | val 0.70242
  Classification -> best τ=0.545 (val F1=0.1925)
  Directional -> Accuracy: 0.3261, MCC: -0.3407, F1: 0.3111

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.65413 | val 0.69559
  Epoch 011 - train 0.65084 | val 0.69705
  Classification -> best τ=0.540 (val F1=0.0473)
  Directional -> Accuracy: 0.4651, MCC: 0.1874, F1: 0.1481

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.64202 | val 0.69047
  Epoch 020 - train 0.59172 | val 0.70445
  Epoch 022 - train 0.59636 | val 0.70950
  Classification -> best τ=0.495 (val F1=0.2519)
  Directional -> Accuracy: 0.4386, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.65466 | val 0.69899
  Epoch 011 - train 0.66291 | val 0.69972
  Classification -> best τ=0.525 (val F1=0.0118)
  Directional -> Accuracy: 0.5854, MCC: 0.2437, F1: 0.7213

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.65052 | val 0.71085
  Epoch 011 - train 0.66434 | val 0.71294
  Classification -> best τ=0.540 (val F1=0.3004)
  Directional -> Accuracy: 0.5349, MCC: 0.0675, F1: 0.5000

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.67462 | val 0.69412
  Epoch 011 - train 0.66154 | val 0.69848
  Classification -> best τ=0.535 (val F1=0.1759)
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.65073 | val 0.69726
  Epoch 016 - train 0.62599 | val 0.72638
  Classification -> best τ=0.500 (val F1=0.2198)
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.65423 | val 0.63905
  Epoch 020 - train 0.62720 | val 0.63120
  Epoch 024 - train 0.61573 | val 0.63091
  Classification -> best τ=0.370 (val F1=0.4630)
  Directional -> Accuracy: 0.5479, MCC: 0.2717, F1: 0.3529

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.67160 | val 0.70012
  Epoch 011 - train 0.65695 | val 0.70085
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.65936 | val 0.69239
  Epoch 014 - train 0.63630 | val 0.70163
  Classification -> best τ=0.475 (val F1=0.2757)
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.65394 | val 0.69876
  Epoch 015 - train 0.64338 | val 0.71252
  Classification -> best τ=0.385 (val F1=0.3166)
  Directional -> Accuracy: 0.5373, MCC: 0.2001, F1: 0.3922

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.63820 | val 0.68805
  Epoch 020 - train 0.61734 | val 0.68263
  Epoch 030 - train 0.56269 | val 0.67686
  Classification -> best τ=0.500 (val F1=0.4167)
  Directional -> Accuracy: 0.5349, MCC: 0.0675, F1: 0.5652

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.63319 | val 0.71504
  Epoch 013 - train 0.63178 | val 0.74294
  Classification -> best τ=0.465 (val F1=0.1140)
  Directional -> Accuracy: 0.4912, MCC: 0.0040, F1: 0.5672

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.65534 | val 0.71984
  Epoch 011 - train 0.64826 | val 0.72311
  Classification -> best τ=0.540 (val F1=0.0999)
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.65445 | val 0.69455
  Epoch 011 - train 0.64943 | val 0.69439
  Classification -> best τ=0.510 (val F1=0.2957)
  Directional -> Accuracy: 0.3878, MCC: 0.1100, F1: 0.5455

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.64608 | val 0.70087
  Epoch 011 - train 0.63981 | val 0.70256
  Classification -> best τ=0.485 (val F1=0.4792)
  Directional -> Accuracy: 0.4474, MCC: -0.1733, F1: 0.0000

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.65172 | val 0.72455
  Epoch 013 - train 0.65218 | val 0.74035
  Classification -> best τ=0.440 (val F1=0.2821)
  Directional -> Accuracy: 0.6000, MCC: 0.2074, F1: 0.5161

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.66619 | val 0.67712
  Epoch 020 - train 0.64433 | val 0.67906
  Epoch 026 - train 0.61303 | val 0.68365
  Classification -> best τ=0.360 (val F1=0.3210)
  Directional -> Accuracy: 0.4894, MCC: -0.1443, F1: 0.6571

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.62816 | val 0.75584
  Epoch 011 - train 0.63927 | val 0.75724
  Classification -> best τ=0.550 (val F1=0.1455)
  Directional -> Accuracy: 0.5682, MCC: 0.0000, F1: 0.7246

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.66620 | val 0.77679
  Epoch 011 - train 0.65130 | val 0.78317
  Classification -> best τ=0.445 (val F1=0.4427)
  Directional -> Accuracy: 0.3469, MCC: -0.2151, F1: 0.4667

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.66648 | val 0.67807
  Epoch 020 - train 0.63259 | val 0.68793
  Classification -> best τ=0.510 (val F1=0.2256)
  Directional -> Accuracy: 0.6071, MCC: 0.2067, F1: 0.6452

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.66572 | val 0.69585
  Epoch 014 - train 0.63993 | val 0.72368
  Classification -> best τ=0.490 (val F1=0.3147)
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.67276 | val 0.68245
  Epoch 014 - train 0.65789 | val 0.69325
  Classification -> best τ=0.540 (val F1=0.2495)
  Directional -> Accuracy: 0.5185, MCC: 0.0262, F1: 0.5938

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.66262 | val 0.71818
  Epoch 011 - train 0.65850 | val 0.72005
  Classification -> best τ=0.530 (val F1=0.1825)
  Directional -> Accuracy: 0.5536, MCC: 0.1167, F1: 0.6753

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.65785 | val 0.72545
  Epoch 011 - train 0.66061 | val 0.72977

[I 2026-02-22 11:10:33,711] Trial 128 finished with value: 0.23670252699030805 and parameters: {'feature_set': 'sector_emotion', 'model_type': 'BiGRU', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.2, 'batch_size': 64, 'learning_rate': 0.00013585335951245598, 'weight_decay': 3.58021934015675e-05, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 0.9309642348051536, 'early_stopping_min_delta': 0.00025911099501746426}. Best is trial 112 with value: 0.2833506688525635.

  Classification -> best τ=0.530 (val F1=0.1942)
  Directional -> Accuracy: 0.5082, MCC: 0.0239, F1: 0.5312

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.23670252699030805
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d', 'emotion_anger', 'emotion_disgust', 'emotion_fear', 'emotion_joy', 'emotion_neutral', 'emotion_sadness', 'emotion_surprize', 'emotion_anger_pct', 'emotion_disgust_pct', 'emotion_fear_pct', 'emotion_joy_pct', 'emotion_neutral_pct', 'emotion_sadness_pct', 'emotion_surprize_pct']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.49393 | val 0.75718
  Epoch 014 - train 0.38441 | val 1.02923
  Classification -> best τ=0.530 (val F1=0.2510)
  Directional -> Accuracy: 0.6053, MCC: 0.1858, F1: 0.4828

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.33830 | val 0.97427
  Epoch 011 - train 0.37396 | val 1.07227
  Classification -> best τ=0.480 (val F1=0.3120)
  Directional -> Accuracy: 0.4000, MCC: -0.1323, F1: 0.0690

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.38373 | val 1.90873
  Epoch 012 - train 0.31516 | val 2.41134
  Classification -> best τ=0.740 (val F1=0.1383)
  Directional -> Accuracy: 0.4783, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.50958 | val 1.29138
  Epoch 013 - train 0.41566 | val 1.81623
  Classification -> best τ=0.490 (val F1=0.2558)
  Directional -> Accuracy: 0.4324, MCC: -0.1224, F1: 0.4000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.42074 | val 1.17456
  Epoch 013 - train 0.32349 | val 1.27364
  Classification -> best τ=0.570 (val F1=0.2934)
  Directional -> Accuracy: 0.6000, MCC: 0.2587, F1: 0.4737

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.43896 | val 0.69844
  Epoch 011 - train 0.42938 | val 0.79255
  Classification -> best τ=0.505 (val F1=0.2593)
  Directional -> Accuracy: 0.4783, MCC: 0.0000, F1: 0.6471

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.44256 | val 1.22165
  Epoch 011 - train 0.41686 | val 1.73254
  Classification -> best τ=0.470 (val F1=0.1720)
  Directional -> Accuracy: 0.5588, MCC: 0.1021, F1: 0.4828

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.40937 | val 0.76622
  Epoch 012 - train 0.32402 | val 0.83171
  Classification -> best τ=0.300 (val F1=0.1657)
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.48097 | val 1.08718
  Epoch 012 - train 0.39507 | val 1.11537
  Classification -> best τ=0.485 (val F1=0.3433)
  Directional -> Accuracy: 0.5833, MCC: 0.1117, F1: 0.2308

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.50565 | val 0.94994
  Epoch 013 - train 0.36402 | val 1.07502
  Classification -> best τ=0.455 (val F1=0.1879)
  Directional -> Accuracy: 0.4928, MCC: 0.0310, F1: 0.5205

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.42645 | val 1.04329
  Epoch 012 - train 0.35307 | val 1.31179
  Classification -> best τ=0.475 (val F1=0.0323)
  Directional -> Accuracy: 0.4898, MCC: -0.0545, F1: 0.3590

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.43739 | val 1.56023
  Epoch 012 - train 0.37148 | val 1.93682
  Classification -> best τ=0.670 (val F1=0.1181)
  Directional -> Accuracy: 0.4912, MCC: 0.0000, F1: 0.0000

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.40614 | val 1.82778
  Epoch 013 - train 0.34459 | val 2.28665
  Classification -> best τ=0.490 (val F1=0.2850)
  Directional -> Accuracy: 0.4524, MCC: -0.1105, F1: 0.3784

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.44964 | val 0.84585
  Epoch 013 - train 0.37422 | val 1.00527
  Classification -> best τ=0.570 (val F1=0.2845)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.42797 | val 1.22359
  Epoch 015 - train 0.29792 | val 1.77274
  Classification -> best τ=0.470 (val F1=0.0527)
  Directional -> Accuracy: 0.4510, MCC: 0.0000, F1: 0.6216

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.44463 | val 1.50546
  Epoch 012 - train 0.38019 | val 1.83072
  Classification -> best τ=0.630 (val F1=0.2921)
  Directional -> Accuracy: 0.5362, MCC: 0.0565, F1: 0.6000

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.40743 | val 1.07162
  Epoch 011 - train 0.40328 | val 1.06354
  Classification -> best τ=0.545 (val F1=0.0462)
  Directional -> Accuracy: 0.3621, MCC: -0.1557, F1: 0.1778

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.47736 | val 1.02295
  Epoch 012 - train 0.43463 | val 1.10696
  Classification -> best τ=0.465 (val F1=0.1243)
  Directional -> Accuracy: 0.6000, MCC: 0.0000, F1: 0.7500

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.49192 | val 1.02178
  Epoch 014 - train 0.33948 | val 1.03683
  Classification -> best τ=0.370 (val F1=0.3385)
  Directional -> Accuracy: 0.5938, MCC: 0.1949, F1: 0.6176

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.49022 | val 0.94365
  Epoch 011 - train 0.42092 | val 1.05399
  Classification -> best τ=0.465 (val F1=0.2382)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.39686 | val 1.18076
  Epoch 011 - train 0.39597 | val 1.12921
  Classification -> best τ=0.450 (val F1=0.2247)
  Directional -> Accuracy: 0.6170, MCC: 0.0000, F1: 0.7632

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.47896 | val 0.99653
  Epoch 012 - train 0.39701 | val 1.16482
  Classification -> best τ=0.510 (val F1=0.2245)
  Directional -> Accuracy: 0.5692, MCC: 0.1742, F1: 0.4167

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.48755 | val 0.75380
  Epoch 014 - train 0.35232 | val 0.90263
  Classification -> best τ=0.630 (val F1=0.3749)
  Directional -> Accuracy: 0.5614, MCC: 0.1216, F1: 0.5902

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.47857 | val 0.70197
  Epoch 020 - train 0.22892 | val 0.84686
  Epoch 021 - train 0.23234 | val 0.84206
  Classification -> best τ=0.435 (val F1=0.3164)
  Directional -> Accuracy: 0.4923, MCC: -0.0077, F1: 0.5217

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.41363 | val 1.10532
  Epoch 013 - train 0.35246 | val 2.01225
  Classification -> best τ=0.400 (val F1=0.4001)
  Directional -> Accuracy: 0.5818, MCC: 0.2155, F1: 0.5106

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.25569 | val 0.88282
  Epoch 011 - train 0.21972 | val 0.97338
  Classification -> best τ=0.500 (val F1=0.3006)
  Directional -> Accuracy: 0.5333, MCC: -0.0240, F1: 0.2759

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.44959 | val 0.70775
  Epoch 011 - train 0.40254 | val 0.72192
  Classification -> best τ=0.595 (val F1=0.3350)
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.0000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.44141 | val 1.36136
  Epoch 012 - train 0.36864 | val 1.75951
  Classification -> best τ=0.420 (val F1=0.1572)
  Directional -> Accuracy: 0.4286, MCC: -0.1502, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.45141 | val 0.76563
  Epoch 012 - train 0.36248 | val 0.84440
  Classification -> best τ=0.565 (val F1=0.0989)
  Directional -> Accuracy: 0.5750, MCC: 0.1124, F1: 0.6909

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.43260 | val 1.40177
  Epoch 012 - train 0.32160 | val 1.29839
  Classification -> best τ=0.635 (val F1=0.3656)
  Directional -> Accuracy: 0.4762, MCC: -0.0674, F1: 0.3529

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.49460 | val 1.42480
  Epoch 011 - train 0.35933 | val 1.44027
  Classification -> best τ=0.435 (val F1=0.0435)
  Directional -> Accuracy: 0.5952, MCC: 0.2460, F1: 0.7302

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.40716 | val 1.98080
  Epoch 013 - train 0.32931 | val 2.19578
  Classification -> best τ=0.415 (val F1=0.3196)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.51942 | val 0.70463
  Epoch 012 - train 0.43721 | val 0.71099
  Classification -> best τ=0.560 (val F1=0.2267)
  Directional -> Accuracy: 0.4444, MCC: 0.0000, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.38100 | val 0.92199
  Epoch 015 - train 0.30405 | val 1.73640
  Classification -> best τ=0.350 (val F1=0.2324)
  Directional -> Accuracy: 0.5116, MCC: 0.0261, F1: 0.5333

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.50530 | val 1.02028
  Epoch 012 - train 0.42867 | val 1.19742
  Classification -> best τ=0.585 (val F1=0.2618)
  Directional -> Accuracy: 0.4242, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.29007 | val 2.07719
  Epoch 013 - train 0.22211 | val 2.27998
  Classification -> best τ=0.570 (val F1=0.3828)
  Directional -> Accuracy: 0.6429, MCC: 0.3127, F1: 0.5946

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.44654 | val 1.27640
  Epoch 013 - train 0.32958 | val 1.92333
  Classification -> best τ=0.620 (val F1=0.3751)
  Directional -> Accuracy: 0.5714, MCC: 0.1316, F1: 0.2941

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.31465 | val 1.20868
  Epoch 013 - train 0.25194 | val 1.30779
  Classification -> best τ=0.525 (val F1=0.3690)
  Directional -> Accuracy: 0.3913, MCC: -0.0863, F1: 0.1765

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.40723 | val 0.67625
  Epoch 016 - train 0.23835 | val 0.86171
  Classification -> best τ=0.420 (val F1=0.4242)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.54730 | val 1.12634
  Epoch 012 - train 0.44717 | val 1.26721
  Classification -> best τ=0.475 (val F1=0.2013)
  Directional -> Accuracy: 0.4865, MCC: 0.0000, F1: 0.6545

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.43020 | val 0.78809
  Epoch 012 - train 0.35356 | val 0.86700
  Classification -> best τ=0.440 (val F1=0.2169)
  Directional -> Accuracy: 0.4889, MCC: -0.1474, F1: 0.6567

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.31050 | val 0.79279
  Epoch 013 - train 0.20196 | val 0.95007
  Classification -> best τ=0.390 (val F1=0.3563)
  Directional -> Accuracy: 0.5714, MCC: 0.0589, F1: 0.7000

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.37426 | val 0.65562
  Epoch 018 - train 0.14243 | val 1.31588
  Classification -> best τ=0.520 (val F1=0.4682)
  Directional -> Accuracy: 0.5417, MCC: 0.2485, F1: 0.5926

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.45942 | val 0.97109
  Epoch 014 - train 0.37378 | val 1.81906
  Classification -> best τ=0.790 (val F1=0.2036)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.37080 | val 1.17871
  Epoch 014 - train 0.25269 | val 1.67238
  Classification -> best τ=0.390 (val F1=0.3104)
  Directional -> Accuracy: 0.5000, MCC: 0.0709, F1: 0.6500

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.42219 | val 1.07329
  Epoch 011 - train 0.40826 | val 1.09697
  Classification -> best τ=0.495 (val F1=0.1942)
  Directional -> Accuracy: 0.5283, MCC: 0.1413, F1: 0.6835

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.45298 | val 0.90917
  Epoch 014 - train 0.28557 | val 0.84971
  Classification -> best τ=0.405 (val F1=0.2374)
  Directional -> Accuracy: 0.5273, MCC: 0.0000, F1: 0.6905

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.49352 | val 1.05414
  Epoch 011 - train 0.44121 | val 1.36695

[I 2026-02-22 11:11:53,886] Trial 129 finished with value: 0.2515504002969193 and parameters: {'feature_set': 'sector_emotion', 'model_type': 'BiGRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.30000000000000004, 'batch_size': 64, 'learning_rate': 0.008014856436007719, 'weight_decay': 2.2433741009028965e-05, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 0.9596523096150307, 'early_stopping_min_delta': 0.0008697102940830555}. Best is trial 112 with value: 0.2833506688525635.

  Classification -> best τ=0.505 (val F1=0.2623)
  Directional -> Accuracy: 0.5167, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2515504002969193
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d', 'emotion_anger', 'emotion_disgust', 'emotion_fear', 'emotion_joy', 'emotion_neutral', 'emotion_sadness', 'emotion_surprize', 'emotion_anger_pct', 'emotion_disgust_pct', 'emotion_fear_pct', 'emotion_joy_pct', 'emotion_neutral_pct', 'emotion_sadness_pct', 'emotion_surprize_pct']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.68714 | val 0.68454
  Epoch 020 - train 0.67113 | val 0.68280
  Epoch 028 - train 0.65830 | val 0.68422
  Classification -> best τ=0.590 (val F1=0.2510)
  Directional -> Accuracy: 0.5526, MCC: 0.0000, F1: 0.0000

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.67421 | val 0.68595
  Epoch 020 - train 0.65685 | val 0.67396
  Epoch 028 - train 0.65802 | val 0.67775
  Classification -> best τ=0.425 (val F1=0.3181)
  Directional -> Accuracy: 0.5778, MCC: 0.0000, F1: 0.7324

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.69705 | val 0.69483
  Epoch 011 - train 0.69704 | val 0.69508
  Classification -> best τ=0.500 (val F1=0.1529)
  Directional -> Accuracy: 0.4565, MCC: -0.0836, F1: 0.4444

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.69185 | val 0.76289
  Epoch 011 - train 0.68446 | val 0.76715
  Classification -> best τ=0.470 (val F1=0.2230)
  Directional -> Accuracy: 0.5405, MCC: 0.0000, F1: 0.7018

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.68486 | val 0.68141
  Epoch 020 - train 0.67021 | val 0.67843
  Epoch 030 - train 0.67660 | val 0.67668
  Classification -> best τ=0.645 (val F1=0.3751)
  Directional -> Accuracy: 0.5600, MCC: 0.1650, F1: 0.4211

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.65210 | val 0.69772
  Epoch 011 - train 0.65819 | val 0.69769
  Classification -> best τ=0.475 (val F1=0.1808)
  Directional -> Accuracy: 0.5435, MCC: 0.0851, F1: 0.2222

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.68783 | val 0.69013
  Epoch 020 - train 0.67706 | val 0.68801
  Epoch 027 - train 0.66979 | val 0.68876
  Classification -> best τ=0.455 (val F1=0.1599)
  Directional -> Accuracy: 0.5882, MCC: 0.2822, F1: 0.6216

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.68129 | val 0.70919
  Epoch 020 - train 0.65338 | val 0.69223
  Epoch 030 - train 0.67940 | val 0.69645
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.70831 | val 0.69423
  Epoch 011 - train 0.68070 | val 0.69485
  Classification -> best τ=0.510 (val F1=0.1928)
  Directional -> Accuracy: 0.5625, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.67850 | val 0.69048
  Epoch 020 - train 0.66897 | val 0.69108
  Epoch 022 - train 0.66842 | val 0.69211
  Classification -> best τ=0.445 (val F1=0.3257)
  Directional -> Accuracy: 0.4203, MCC: -0.0279, F1: 0.5833

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.67869 | val 0.68474
  Epoch 019 - train 0.66728 | val 0.69474
  Classification -> best τ=0.495 (val F1=0.3075)
  Directional -> Accuracy: 0.6122, MCC: 0.2379, F1: 0.2963

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.68603 | val 0.70567
  Epoch 011 - train 0.69191 | val 0.70630
  Classification -> best τ=0.460 (val F1=0.2157)
  Directional -> Accuracy: 0.4912, MCC: -0.1313, F1: 0.6588

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.68497 | val 0.67372
  Epoch 019 - train 0.67527 | val 0.68220
  Classification -> best τ=0.525 (val F1=0.2438)
  Directional -> Accuracy: 0.3810, MCC: -0.2248, F1: 0.5000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.67011 | val 0.63593
  Epoch 020 - train 0.66030 | val 0.62314
  Epoch 028 - train 0.64634 | val 0.62426
  Classification -> best τ=0.440 (val F1=0.3774)
  Directional -> Accuracy: 0.4500, MCC: -0.2294, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.67429 | val 0.69572
  Epoch 011 - train 0.68495 | val 0.69693
  Classification -> best τ=0.485 (val F1=0.2556)
  Directional -> Accuracy: 0.5882, MCC: 0.1598, F1: 0.5116

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.68619 | val 0.68498
  Epoch 020 - train 0.66063 | val 0.69279
  Epoch 022 - train 0.66616 | val 0.69379
  Classification -> best τ=0.435 (val F1=0.3067)
  Directional -> Accuracy: 0.5507, MCC: 0.0764, F1: 0.6931

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.67380 | val 0.70796
  Epoch 011 - train 0.66315 | val 0.71117
  Classification -> best τ=0.490 (val F1=0.0832)
  Directional -> Accuracy: 0.6207, MCC: 0.0000, F1: 0.7660

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.68947 | val 0.68959
  Epoch 019 - train 0.67349 | val 0.69367
  Classification -> best τ=0.535 (val F1=0.2166)
  Directional -> Accuracy: 0.5200, MCC: -0.1940, F1: 0.6786

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.67359 | val 0.67706
  Epoch 020 - train 0.67027 | val 0.66932
  Epoch 030 - train 0.68474 | val 0.66903
  Classification -> best τ=0.355 (val F1=0.2843)
  Directional -> Accuracy: 0.5000, MCC: 0.1167, F1: 0.3600

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.68016 | val 0.68885
  Epoch 020 - train 0.65981 | val 0.68255
  Epoch 030 - train 0.65716 | val 0.67992
  Classification -> best τ=0.365 (val F1=0.2204)
  Directional -> Accuracy: 0.5135, MCC: -0.0692, F1: 0.6538

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.68063 | val 0.69566
  Epoch 011 - train 0.68303 | val 0.69611
  Classification -> best τ=0.525 (val F1=0.0712)
  Directional -> Accuracy: 0.5745, MCC: 0.2577, F1: 0.5455

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.68650 | val 0.69558
  Epoch 011 - train 0.67826 | val 0.69483
  Classification -> best τ=0.490 (val F1=0.1087)
  Directional -> Accuracy: 0.5538, MCC: 0.1080, F1: 0.5538

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.68588 | val 0.71166
  Epoch 011 - train 0.68997 | val 0.71473
  Classification -> best τ=0.525 (val F1=0.1809)
  Directional -> Accuracy: 0.4386, MCC: 0.0000, F1: 0.0000

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.69878 | val 0.68635
  Epoch 017 - train 0.68686 | val 0.68602
  Classification -> best τ=0.470 (val F1=0.1348)
  Directional -> Accuracy: 0.6308, MCC: 0.2577, F1: 0.5862

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.69087 | val 0.69624
  Epoch 020 - train 0.67054 | val 0.69158
  Epoch 030 - train 0.66599 | val 0.68782
  Classification -> best τ=0.705 (val F1=0.4504)
  Directional -> Accuracy: 0.5273, MCC: 0.1463, F1: 0.3500

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.72551 | val 0.70641
  Epoch 011 - train 0.71865 | val 0.70721
  Classification -> best τ=0.440 (val F1=0.2035)
  Directional -> Accuracy: 0.5556, MCC: 0.1469, F1: 0.5652

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.69903 | val 0.67924
  Epoch 020 - train 0.66987 | val 0.67605
  Epoch 027 - train 0.64539 | val 0.67778
  Classification -> best τ=0.570 (val F1=0.3746)
  Directional -> Accuracy: 0.4286, MCC: -0.0913, F1: 0.3333

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.70900 | val 0.67594
  Epoch 020 - train 0.68460 | val 0.66682
  Epoch 030 - train 0.65772 | val 0.66272
  Classification -> best τ=0.515 (val F1=0.4362)
  Directional -> Accuracy: 0.4464, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.70243 | val 0.70323
  Epoch 011 - train 0.71350 | val 0.70403
  Classification -> best τ=0.470 (val F1=0.0836)
  Directional -> Accuracy: 0.5000, MCC: -0.0205, F1: 0.5652

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.70678 | val 0.68716
  Epoch 020 - train 0.69692 | val 0.67785
  Epoch 030 - train 0.67329 | val 0.67378
  Classification -> best τ=0.465 (val F1=0.3979)
  Directional -> Accuracy: 0.4762, MCC: 0.0000, F1: 0.6452

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.67834 | val 0.69060
  Epoch 020 - train 0.69013 | val 0.69148
  Epoch 021 - train 0.68219 | val 0.69154
  Classification -> best τ=0.510 (val F1=0.3417)
  Directional -> Accuracy: 0.5000, MCC: 0.1319, F1: 0.2222

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.70520 | val 0.68038
  Epoch 020 - train 0.68753 | val 0.67830
  Epoch 030 - train 0.66014 | val 0.67762
  Classification -> best τ=0.430 (val F1=0.2609)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.68626 | val 0.68661
  Epoch 020 - train 0.67685 | val 0.67182
  Epoch 030 - train 0.67218 | val 0.66711
  Classification -> best τ=0.480 (val F1=0.3266)
  Directional -> Accuracy: 0.4444, MCC: 0.0000, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.68223 | val 0.72340
  Epoch 011 - train 0.67935 | val 0.72725
  Classification -> best τ=0.495 (val F1=0.1309)
  Directional -> Accuracy: 0.4884, MCC: -0.0074, F1: 0.6333

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.68372 | val 0.70330
  Epoch 011 - train 0.67826 | val 0.70393
  Classification -> best τ=0.480 (val F1=0.0859)
  Directional -> Accuracy: 0.5303, MCC: 0.0431, F1: 0.5867

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.66939 | val 0.69455
  Epoch 020 - train 0.68257 | val 0.68818
  Epoch 030 - train 0.65085 | val 0.68246
  Classification -> best τ=0.520 (val F1=0.3985)
  Directional -> Accuracy: 0.7381, MCC: 0.4767, F1: 0.7442

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.68304 | val 0.70982
  Epoch 011 - train 0.67330 | val 0.71331
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4643, MCC: 0.0000, F1: 0.6341

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.71480 | val 0.69773
  Epoch 014 - train 0.68716 | val 0.70355
  Classification -> best τ=0.520 (val F1=0.2659)
  Directional -> Accuracy: 0.3696, MCC: -0.1859, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.69927 | val 0.70696
  Epoch 011 - train 0.68229 | val 0.70681
  Classification -> best τ=0.525 (val F1=0.4201)
  Directional -> Accuracy: 0.6458, MCC: 0.1957, F1: 0.4516

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.68195 | val 0.67869
  Epoch 020 - train 0.67195 | val 0.68082
  Epoch 021 - train 0.67389 | val 0.68076
  Classification -> best τ=0.470 (val F1=0.2977)
  Directional -> Accuracy: 0.5135, MCC: 0.0444, F1: 0.6000

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.69563 | val 0.70824
  Epoch 011 - train 0.67301 | val 0.70767
  Classification -> best τ=0.555 (val F1=0.1890)
  Directional -> Accuracy: 0.4667, MCC: -0.0950, F1: 0.0769

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.69723 | val 0.68102
  Epoch 020 - train 0.67459 | val 0.67591
  Epoch 030 - train 0.67186 | val 0.67282
  Classification -> best τ=0.410 (val F1=0.3015)
  Directional -> Accuracy: 0.5952, MCC: 0.1340, F1: 0.7018

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.67974 | val 0.72227
  Epoch 011 - train 0.67340 | val 0.72582
  Classification -> best τ=0.515 (val F1=0.1371)
  Directional -> Accuracy: 0.4167, MCC: 0.0000, F1: 0.5172

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.70822 | val 0.73942
  Epoch 011 - train 0.70489 | val 0.74319
  Classification -> best τ=0.450 (val F1=0.0489)
  Directional -> Accuracy: 0.4545, MCC: -0.0482, F1: 0.2857

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.69714 | val 0.68602
  Epoch 020 - train 0.67433 | val 0.68334
  Epoch 030 - train 0.66913 | val 0.68104
  Classification -> best τ=0.385 (val F1=0.1949)
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.6506

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.68311 | val 0.69406
  Epoch 011 - train 0.67197 | val 0.69466
  Classification -> best τ=0.495 (val F1=0.1508)
  Directional -> Accuracy: 0.5094, MCC: 0.0091, F1: 0.6286

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.68626 | val 0.68896
  Epoch 011 - train 0.68166 | val 0.69004
  Classification -> best τ=0.465 (val F1=0.1605)
  Directional -> Accuracy: 0.4727, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.67312 | val 0.69469

[I 2026-02-22 11:13:52,683] Trial 130 finished with value: 0.22900029696230884 and parameters: {'feature_set': 'sector_emotion', 'model_type': 'BiGRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.4, 'batch_size': 64, 'learning_rate': 3.937985692589319e-05, 'weight_decay': 6.069754155665587e-05, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 0.6946355287396817, 'early_stopping_min_delta': 0.0005713176173157955}. Best is trial 112 with value: 0.2833506688525635.

  Epoch 015 - train 0.67944 | val 0.70780
  Classification -> best τ=0.480 (val F1=0.1489)
  Directional -> Accuracy: 0.5000, MCC: -0.0689, F1: 0.0625

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.22900029696230884
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d', 'emotion_anger', 'emotion_disgust', 'emotion_fear', 'emotion_joy', 'emotion_neutral', 'emotion_sadness', 'emotion_surprize', 'emotion_anger_pct', 'emotion_disgust_pct', 'emotion_fear_pct', 'emotion_joy_pct', 'emotion_neutral_pct', 'emotion_sadness_pct', 'emotion_surprize_pct']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.45560 | val 0.78700
  Epoch 013 - train 0.40685 | val 0.80554
  Classification -> best τ=0.460 (val F1=0.2039)
  Directional -> Accuracy: 0.5395, MCC: 0.1006, F1: 0.5570

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.42711 | val 0.82706
  Epoch 012 - train 0.32326 | val 1.10137
  Classification -> best τ=0.500 (val F1=0.2523)
  Directional -> Accuracy: 0.5778, MCC: 0.0950, F1: 0.6780

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.48977 | val 1.28537
  Epoch 011 - train 0.42263 | val 1.49803
  Classification -> best τ=0.470 (val F1=0.1572)
  Directional -> Accuracy: 0.5217, MCC: 0.0000, F1: 0.6857

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.49338 | val 1.08918
  Epoch 013 - train 0.41802 | val 1.21795
  Classification -> best τ=0.440 (val F1=0.1805)
  Directional -> Accuracy: 0.4730, MCC: -0.1771, F1: 0.6286

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.38281 | val 1.10580
  Epoch 013 - train 0.32357 | val 1.26812
  Classification -> best τ=0.490 (val F1=0.3559)
  Directional -> Accuracy: 0.6400, MCC: 0.2942, F1: 0.6087

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.39047 | val 0.73707
  Epoch 019 - train 0.17244 | val 1.21455
  Classification -> best τ=0.650 (val F1=0.4056)
  Directional -> Accuracy: 0.5217, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.41564 | val 1.62372
  Epoch 011 - train 0.42975 | val 1.88501
  Classification -> best τ=0.445 (val F1=0.2557)
  Directional -> Accuracy: 0.4412, MCC: 0.0771, F1: 0.5682

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.37566 | val 0.73749
  Epoch 014 - train 0.29556 | val 1.41710
  Classification -> best τ=0.500 (val F1=0.4176)
  Directional -> Accuracy: 0.4286, MCC: -0.0700, F1: 0.5385

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.32726 | val 0.91367
  Epoch 017 - train 0.25002 | val 1.40376
  Classification -> best τ=0.385 (val F1=0.3500)
  Directional -> Accuracy: 0.5000, MCC: 0.1009, F1: 0.6000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.43961 | val 0.87602
  Epoch 012 - train 0.41297 | val 0.85817
  Classification -> best τ=0.450 (val F1=0.2465)
  Directional -> Accuracy: 0.3913, MCC: -0.1657, F1: 0.5532

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.41211 | val 1.18695
  Epoch 011 - train 0.40209 | val 1.27055
  Classification -> best τ=0.545 (val F1=0.1692)
  Directional -> Accuracy: 0.5306, MCC: 0.0317, F1: 0.4103

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.42773 | val 2.52834
  Epoch 011 - train 0.38757 | val 2.44814
  Classification -> best τ=0.495 (val F1=0.1378)
  Directional -> Accuracy: 0.6491, MCC: 0.3534, F1: 0.7297

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.37875 | val 1.70722
  Epoch 011 - train 0.42093 | val 1.95103
  Classification -> best τ=0.440 (val F1=0.1754)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.6230

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.44346 | val 0.68422
  Epoch 018 - train 0.28728 | val 0.99762
  Classification -> best τ=0.570 (val F1=0.3864)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.40689 | val 0.87836
  Epoch 011 - train 0.35388 | val 0.89940
  Classification -> best τ=0.510 (val F1=0.2078)
  Directional -> Accuracy: 0.5490, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.48249 | val 1.10351
  Epoch 013 - train 0.38735 | val 1.28129
  Classification -> best τ=0.290 (val F1=0.2659)
  Directional -> Accuracy: 0.5652, MCC: 0.1171, F1: 0.6939

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.44751 | val 1.56293
  Epoch 011 - train 0.41618 | val 1.57058
  Classification -> best τ=0.540 (val F1=0.0354)
  Directional -> Accuracy: 0.4310, MCC: -0.0600, F1: 0.4000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.48092 | val 1.35119
  Epoch 011 - train 0.42957 | val 1.46816
  Classification -> best τ=0.590 (val F1=0.0047)
  Directional -> Accuracy: 0.4267, MCC: -0.1879, F1: 0.5169

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.42309 | val 0.92335
  Epoch 016 - train 0.30148 | val 1.08509
  Classification -> best τ=0.195 (val F1=0.3421)
  Directional -> Accuracy: 0.5000, MCC: -0.0579, F1: 0.6000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.47424 | val 1.00726
  Epoch 012 - train 0.42405 | val 0.86267
  Classification -> best τ=0.425 (val F1=0.2337)
  Directional -> Accuracy: 0.5270, MCC: 0.0697, F1: 0.5205

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.34093 | val 1.06200
  Epoch 011 - train 0.34694 | val 1.09352
  Classification -> best τ=0.475 (val F1=0.1424)
  Directional -> Accuracy: 0.5532, MCC: 0.0446, F1: 0.6441

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.45289 | val 1.16032
  Epoch 013 - train 0.30410 | val 1.41131
  Classification -> best τ=0.480 (val F1=0.2040)
  Directional -> Accuracy: 0.5231, MCC: 0.1755, F1: 0.1143

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.43266 | val 1.05206
  Epoch 013 - train 0.36810 | val 1.20029
  Classification -> best τ=0.535 (val F1=0.3913)
  Directional -> Accuracy: 0.6140, MCC: 0.1966, F1: 0.6944

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.46017 | val 0.84340
  Epoch 012 - train 0.39486 | val 0.90503
  Classification -> best τ=0.540 (val F1=0.1565)
  Directional -> Accuracy: 0.5385, MCC: 0.0750, F1: 0.5161

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.40889 | val 1.06193
  Epoch 014 - train 0.26249 | val 1.51013
  Classification -> best τ=0.520 (val F1=0.3512)
  Directional -> Accuracy: 0.5455, MCC: 0.1826, F1: 0.3902

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.28497 | val 0.84449
  Epoch 011 - train 0.24617 | val 0.89471
  Classification -> best τ=0.530 (val F1=0.2035)
  Directional -> Accuracy: 0.4444, MCC: 0.1289, F1: 0.6032

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.41372 | val 0.78793
  Epoch 017 - train 0.20262 | val 1.19939
  Classification -> best τ=0.515 (val F1=0.3194)
  Directional -> Accuracy: 0.5238, MCC: 0.0000, F1: 0.6154

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.43891 | val 1.32245
  Epoch 012 - train 0.37444 | val 1.56502
  Classification -> best τ=0.355 (val F1=0.1607)
  Directional -> Accuracy: 0.5536, MCC: 0.0000, F1: 0.7126

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.37012 | val 0.80440
  Epoch 013 - train 0.34239 | val 0.89885
  Classification -> best τ=0.435 (val F1=0.4114)
  Directional -> Accuracy: 0.4750, MCC: -0.0259, F1: 0.4324

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.44530 | val 1.40109
  Epoch 011 - train 0.42977 | val 1.45469
  Classification -> best τ=0.560 (val F1=0.3501)
  Directional -> Accuracy: 0.5238, MCC: 0.0337, F1: 0.4118

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.43363 | val 0.82887
  Epoch 012 - train 0.41372 | val 0.86342
  Classification -> best τ=0.525 (val F1=0.1286)
  Directional -> Accuracy: 0.4048, MCC: -0.2460, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.40501 | val 1.72397
  Epoch 013 - train 0.30893 | val 2.35819
  Classification -> best τ=0.370 (val F1=0.3541)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.49689 | val 0.84080
  Epoch 013 - train 0.36403 | val 0.98100
  Classification -> best τ=0.420 (val F1=0.3117)
  Directional -> Accuracy: 0.4444, MCC: -0.0189, F1: 0.0476

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.44378 | val 1.02724
  Epoch 011 - train 0.37820 | val 1.03280
  Classification -> best τ=0.445 (val F1=0.2324)
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.51671 | val 0.86162
  Epoch 011 - train 0.50342 | val 0.84732
  Classification -> best τ=0.395 (val F1=0.2117)
  Directional -> Accuracy: 0.5758, MCC: 0.0000, F1: 0.7308

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.37126 | val 1.05154
  Epoch 012 - train 0.26623 | val 1.36652
  Classification -> best τ=0.495 (val F1=0.3260)
  Directional -> Accuracy: 0.6190, MCC: 0.2571, F1: 0.5789

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.36792 | val 1.29358
  Epoch 011 - train 0.37739 | val 1.58919
  Classification -> best τ=0.450 (val F1=0.2530)
  Directional -> Accuracy: 0.5179, MCC: 0.0998, F1: 0.6197

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.32983 | val 0.85948
  Epoch 014 - train 0.26932 | val 1.06162
  Classification -> best τ=0.465 (val F1=0.2852)
  Directional -> Accuracy: 0.4565, MCC: 0.0086, F1: 0.3902

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.36057 | val 0.74942
  Epoch 017 - train 0.24211 | val 1.01121
  Classification -> best τ=0.560 (val F1=0.4011)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.44920 | val 1.78167
  Epoch 012 - train 0.37512 | val 1.58155
  Classification -> best τ=0.540 (val F1=0.3128)
  Directional -> Accuracy: 0.5135, MCC: 0.0187, F1: 0.4000

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.41923 | val 0.75133
  Epoch 011 - train 0.39867 | val 0.76452
  Classification -> best τ=0.485 (val F1=0.2982)
  Directional -> Accuracy: 0.5556, MCC: 0.2205, F1: 0.6970

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.34960 | val 0.78825
  Epoch 014 - train 0.21875 | val 0.96075
  Classification -> best τ=0.555 (val F1=0.3059)
  Directional -> Accuracy: 0.4524, MCC: -0.0313, F1: 0.3429

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.42183 | val 0.65619
  Epoch 020 - train 0.12002 | val 0.92498
  Epoch 022 - train 0.09908 | val 0.93521
  Classification -> best τ=0.675 (val F1=0.4092)
  Directional -> Accuracy: 0.5417, MCC: 0.1080, F1: 0.5000

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.46551 | val 1.06355
  Epoch 011 - train 0.44067 | val 1.11461
  Classification -> best τ=0.595 (val F1=0.1647)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.40447 | val 0.97105
  Epoch 014 - train 0.28489 | val 1.27864
  Classification -> best τ=0.360 (val F1=0.2952)
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.6506

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.37354 | val 0.96499
  Epoch 011 - train 0.34973 | val 1.16771
  Classification -> best τ=0.530 (val F1=0.2482)
  Directional -> Accuracy: 0.5094, MCC: 0.0135, F1: 0.5806

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.43274 | val 1.46615
  Epoch 011 - train 0.44090 | val 1.31542
  Classification -> best τ=0.660 (val F1=0.2291)
  Directional -> Accuracy: 0.4727, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.49357 | val 0.93802

[I 2026-02-22 11:15:12,631] Trial 131 finished with value: 0.262307706070303 and parameters: {'feature_set': 'sector_emotion', 'model_type': 'BiGRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.2, 'batch_size': 64, 'learning_rate': 0.004006161593934843, 'weight_decay': 4.279688378657287e-05, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 0.7714718746742866, 'early_stopping_min_delta': 0.00189229333812809}. Best is trial 112 with value: 0.2833506688525635.

  Epoch 012 - train 0.39970 | val 1.01335
  Classification -> best τ=0.475 (val F1=0.3496)
  Directional -> Accuracy: 0.5500, MCC: 0.0955, F1: 0.4000

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.262307706070303
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d', 'emotion_anger', 'emotion_disgust', 'emotion_fear', 'emotion_joy', 'emotion_neutral', 'emotion_sadness', 'emotion_surprize', 'emotion_anger_pct', 'emotion_disgust_pct', 'emotion_fear_pct', 'emotion_joy_pct', 'emotion_neutral_pct', 'emotion_sadness_pct', 'emotion_surprize_pct']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.42187 | val 0.79869
  Epoch 014 - train 0.34595 | val 1.17296
  Classification -> best τ=0.435 (val F1=0.2771)
  Directional -> Accuracy: 0.5789, MCC: 0.1709, F1: 0.5789

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.40604 | val 0.96924
  Epoch 013 - train 0.26316 | val 1.11674
  Classification -> best τ=0.445 (val F1=0.2523)
  Directional -> Accuracy: 0.6000, MCC: 0.2060, F1: 0.6250

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.43875 | val 1.36993
  Epoch 011 - train 0.38138 | val 1.48936
  Classification -> best τ=0.540 (val F1=0.1978)
  Directional -> Accuracy: 0.4565, MCC: -0.0996, F1: 0.0741

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.51513 | val 0.81807
  Epoch 016 - train 0.32265 | val 2.51428
  Classification -> best τ=0.370 (val F1=0.3151)
  Directional -> Accuracy: 0.5000, MCC: 0.0228, F1: 0.4478

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.44852 | val 1.03250
  Epoch 011 - train 0.33693 | val 1.10040
  Classification -> best τ=0.565 (val F1=0.4139)
  Directional -> Accuracy: 0.6000, MCC: 0.2300, F1: 0.5238

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.43756 | val 1.02805
  Epoch 011 - train 0.40110 | val 0.88251
  Classification -> best τ=0.535 (val F1=0.1808)
  Directional -> Accuracy: 0.5217, MCC: 0.0455, F1: 0.5217

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.46262 | val 1.23994
  Epoch 012 - train 0.35059 | val 1.40447
  Classification -> best τ=0.585 (val F1=0.1753)
  Directional -> Accuracy: 0.6029, MCC: 0.0000, F1: 0.0000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.32615 | val 1.12602
  Epoch 018 - train 0.18635 | val 1.56819
  Classification -> best τ=0.375 (val F1=0.4971)
  Directional -> Accuracy: 0.4762, MCC: 0.1171, F1: 0.6071

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.37056 | val 1.18885
  Epoch 013 - train 0.26482 | val 1.51139
  Classification -> best τ=0.490 (val F1=0.2822)
  Directional -> Accuracy: 0.7083, MCC: 0.4006, F1: 0.6316

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.41423 | val 0.88385
  Epoch 012 - train 0.31333 | val 0.91126
  Classification -> best τ=0.540 (val F1=0.2535)
  Directional -> Accuracy: 0.4203, MCC: -0.0815, F1: 0.5238

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.40661 | val 0.99624
  Epoch 011 - train 0.33570 | val 1.02496
  Classification -> best τ=0.600 (val F1=0.2484)
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.37455 | val 3.13687
  Epoch 011 - train 0.37281 | val 3.02020
  Classification -> best τ=0.530 (val F1=0.0728)
  Directional -> Accuracy: 0.5088, MCC: 0.1313, F1: 0.0667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.40307 | val 1.38630
  Epoch 011 - train 0.40209 | val 1.49025
  Classification -> best τ=0.435 (val F1=0.2850)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.6230

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.44509 | val 0.86868
  Epoch 011 - train 0.43309 | val 0.90171
  Classification -> best τ=0.500 (val F1=0.3768)
  Directional -> Accuracy: 0.4667, MCC: -0.1857, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.39929 | val 1.06660
  Epoch 011 - train 0.41071 | val 1.07210
  Classification -> best τ=0.395 (val F1=0.0730)
  Directional -> Accuracy: 0.4510, MCC: -0.0546, F1: 0.5484

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.43050 | val 1.14342
  Epoch 012 - train 0.38245 | val 1.19006
  Classification -> best τ=0.270 (val F1=0.2659)
  Directional -> Accuracy: 0.5217, MCC: -0.1128, F1: 0.6857

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.41327 | val 1.15968
  Epoch 011 - train 0.38163 | val 1.23389
  Classification -> best τ=0.495 (val F1=0.0499)
  Directional -> Accuracy: 0.5517, MCC: 0.0981, F1: 0.6061

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.44381 | val 1.15565
  Epoch 011 - train 0.42687 | val 1.19243
  Classification -> best τ=0.460 (val F1=0.1243)
  Directional -> Accuracy: 0.5733, MCC: -0.0727, F1: 0.7241

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.42676 | val 0.98572
  Epoch 013 - train 0.28449 | val 1.05654
  Classification -> best τ=0.420 (val F1=0.2626)
  Directional -> Accuracy: 0.5156, MCC: -0.0299, F1: 0.6173

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.50982 | val 0.81424
  Epoch 013 - train 0.43567 | val 0.86100
  Classification -> best τ=0.385 (val F1=0.3397)
  Directional -> Accuracy: 0.4189, MCC: -0.1225, F1: 0.1569

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.32715 | val 1.15614
  Epoch 013 - train 0.23846 | val 1.15584
  Classification -> best τ=0.510 (val F1=0.3835)
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.42808 | val 0.94177
  Epoch 011 - train 0.41615 | val 0.96868
  Classification -> best τ=0.465 (val F1=0.1960)
  Directional -> Accuracy: 0.4923, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.40317 | val 0.83590
  Epoch 014 - train 0.32971 | val 0.95290
  Classification -> best τ=0.685 (val F1=0.3749)
  Directional -> Accuracy: 0.4561, MCC: 0.0076, F1: 0.2051

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.44481 | val 0.90863
  Epoch 012 - train 0.40720 | val 0.87723
  Classification -> best τ=0.460 (val F1=0.1429)
  Directional -> Accuracy: 0.4769, MCC: 0.0000, F1: 0.6458

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.41494 | val 1.15304
  Epoch 014 - train 0.20457 | val 1.19278
  Classification -> best τ=0.405 (val F1=0.4051)
  Directional -> Accuracy: 0.6000, MCC: 0.2476, F1: 0.5417

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.21329 | val 1.24218
  Epoch 011 - train 0.20038 | val 1.14908
  Classification -> best τ=0.560 (val F1=0.1890)
  Directional -> Accuracy: 0.5778, MCC: 0.0000, F1: 0.0000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.37517 | val 0.66728
  Epoch 019 - train 0.15774 | val 1.07269
  Classification -> best τ=0.535 (val F1=0.3443)
  Directional -> Accuracy: 0.6190, MCC: 0.2639, F1: 0.6190

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.39288 | val 1.67922
  Epoch 012 - train 0.35163 | val 1.70394
  Classification -> best τ=0.400 (val F1=0.1805)
  Directional -> Accuracy: 0.4643, MCC: -0.2308, F1: 0.6250

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.32524 | val 0.79704
  Epoch 012 - train 0.25432 | val 0.89631
  Classification -> best τ=0.525 (val F1=0.2660)
  Directional -> Accuracy: 0.5750, MCC: 0.1297, F1: 0.6383

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.41581 | val 1.54973
  Epoch 012 - train 0.35502 | val 1.59104
  Classification -> best τ=0.570 (val F1=0.3001)
  Directional -> Accuracy: 0.5238, MCC: 0.0413, F1: 0.4737

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.44163 | val 1.13599
  Epoch 012 - train 0.36614 | val 1.83968
  Classification -> best τ=0.570 (val F1=0.0128)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.43647 | val 1.54027
  Epoch 014 - train 0.29657 | val 1.97830
  Classification -> best τ=0.715 (val F1=0.3465)
  Directional -> Accuracy: 0.4898, MCC: 0.1358, F1: 0.0741

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.44529 | val 1.17596
  Epoch 014 - train 0.31808 | val 1.48880
  Classification -> best τ=0.415 (val F1=0.2509)
  Directional -> Accuracy: 0.5556, MCC: 0.2784, F1: 0.3600

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.36584 | val 0.90980
  Epoch 011 - train 0.38215 | val 0.92944
  Classification -> best τ=0.405 (val F1=0.2324)
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.53533 | val 1.11333
  Epoch 011 - train 0.51052 | val 1.18297
  Classification -> best τ=0.545 (val F1=0.1805)
  Directional -> Accuracy: 0.6515, MCC: 0.2730, F1: 0.7160

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.32237 | val 1.02157
  Epoch 012 - train 0.22841 | val 1.31986
  Classification -> best τ=0.455 (val F1=0.3218)
  Directional -> Accuracy: 0.5000, MCC: -0.0142, F1: 0.5714

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.40775 | val 2.00429
  Epoch 011 - train 0.37916 | val 2.31430
  Classification -> best τ=0.415 (val F1=0.2677)
  Directional -> Accuracy: 0.5000, MCC: 0.0910, F1: 0.6316

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.32159 | val 0.92393
  Epoch 011 - train 0.27704 | val 0.97569
  Classification -> best τ=0.525 (val F1=0.2562)
  Directional -> Accuracy: 0.4348, MCC: -0.0094, F1: 0.3158

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.38502 | val 0.79933
  Epoch 017 - train 0.17201 | val 1.13544
  Classification -> best τ=0.465 (val F1=0.3090)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.45530 | val 1.24704
  Epoch 012 - train 0.33577 | val 1.36772
  Classification -> best τ=0.420 (val F1=0.2479)
  Directional -> Accuracy: 0.4865, MCC: 0.0000, F1: 0.6545

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.39575 | val 0.69043
  Epoch 011 - train 0.43066 | val 0.71956
  Classification -> best τ=0.460 (val F1=0.4490)
  Directional -> Accuracy: 0.5556, MCC: 0.1089, F1: 0.6000

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.29362 | val 0.73571
  Epoch 015 - train 0.19909 | val 0.94993
  Classification -> best τ=0.415 (val F1=0.2942)
  Directional -> Accuracy: 0.6190, MCC: 0.2123, F1: 0.6800

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.34490 | val 0.65857
  Epoch 018 - train 0.13273 | val 1.11986
  Classification -> best τ=0.505 (val F1=0.3458)
  Directional -> Accuracy: 0.4792, MCC: 0.2641, F1: 0.5902

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.42514 | val 1.00714
  Epoch 011 - train 0.39016 | val 1.00035
  Classification -> best τ=0.625 (val F1=0.1647)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.36811 | val 0.93413
  Epoch 014 - train 0.25682 | val 1.33270
  Classification -> best τ=0.485 (val F1=0.4444)
  Directional -> Accuracy: 0.4643, MCC: -0.0620, F1: 0.5588

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.42562 | val 1.30516
  Epoch 013 - train 0.29639 | val 1.60420
  Classification -> best τ=0.360 (val F1=0.1646)
  Directional -> Accuracy: 0.5094, MCC: 0.0000, F1: 0.6750

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.36466 | val 1.93863
  Epoch 011 - train 0.40126 | val 2.10219
  Classification -> best τ=0.505 (val F1=0.1186)
  Directional -> Accuracy: 0.4727, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.46633 | val 0.69678

[I 2026-02-22 11:16:30,523] Trial 132 finished with value: 0.2599486740753436 and parameters: {'feature_set': 'sector_emotion', 'model_type': 'BiGRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.2, 'batch_size': 64, 'learning_rate': 0.0057145018354132155, 'weight_decay': 1.3917611308444151e-05, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 1.0066981895890466, 'early_stopping_min_delta': 0.000492461565816702}. Best is trial 112 with value: 0.2833506688525635.

  Epoch 016 - train 0.22492 | val 1.05855
  Classification -> best τ=0.560 (val F1=0.3448)
  Directional -> Accuracy: 0.5167, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2599486740753436
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'emotion_anger', 'emotion_disgust', 'emotion_fear', 'emotion_joy', 'emotion_neutral', 'emotion_sadness', 'emotion_surprize', 'emotion_anger_pct', 'emotion_disgust_pct', 'emotion_fear_pct', 'emotion_joy_pct', 'emotion_neutral_pct', 'emotion_sadness_pct', 'emotion_surprize_pct']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.52220 | val 0.80807
  Epoch 013 - train 0.48596 | val 0.86507
  Classification -> best τ=0.670 (val F1=0.2036)
  Directional -> Accuracy: 0.5658, MCC: 0.1283, F1: 0.0571

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.45839 | val 0.80478
  Epoch 014 - train 0.29659 | val 0.87772
  Classification -> best τ=0.550 (val F1=0.1764)
  Directional -> Accuracy: 0.6889, MCC: 0.3500, F1: 0.7500

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.51119 | val 0.85535
  Epoch 013 - train 0.39096 | val 0.92781
  Classification -> best τ=0.445 (val F1=0.3894)
  Directional -> Accuracy: 0.5870, MCC: 0.2143, F1: 0.4865

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.53146 | val 1.33887
  Epoch 015 - train 0.42739 | val 1.97187
  Classification -> best τ=0.370 (val F1=0.3164)
  Directional -> Accuracy: 0.5000, MCC: 0.0180, F1: 0.4638

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.40600 | val 1.04053
  Epoch 013 - train 0.37339 | val 1.31623
  Classification -> best τ=0.575 (val F1=0.2726)
  Directional -> Accuracy: 0.7200, MCC: 0.4391, F1: 0.7308

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.51003 | val 0.64841
  Epoch 020 - train 0.17350 | val 0.94173
  Classification -> best τ=0.620 (val F1=0.4147)
  Directional -> Accuracy: 0.5217, MCC: 0.1124, F1: 0.6452

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.46352 | val 1.25085
  Epoch 012 - train 0.40660 | val 1.33268
  Classification -> best τ=0.475 (val F1=0.3662)
  Directional -> Accuracy: 0.3971, MCC: -0.1071, F1: 0.4938

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.39570 | val 2.08631
  Epoch 014 - train 0.27499 | val 1.90410
  Classification -> best τ=0.425 (val F1=0.2810)
  Directional -> Accuracy: 0.4048, MCC: -0.1803, F1: 0.5763

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.40878 | val 0.84329
  Epoch 015 - train 0.31455 | val 1.25670
  Classification -> best τ=0.625 (val F1=0.2764)
  Directional -> Accuracy: 0.5625, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.48608 | val 0.94945
  Epoch 012 - train 0.45161 | val 0.98682
  Classification -> best τ=0.585 (val F1=0.1950)
  Directional -> Accuracy: 0.4783, MCC: -0.0707, F1: 0.3793

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.51790 | val 1.18661
  Epoch 012 - train 0.45438 | val 1.40431
  Classification -> best τ=0.480 (val F1=0.2074)
  Directional -> Accuracy: 0.5510, MCC: 0.0212, F1: 0.0833

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.44653 | val 2.15195
  Epoch 012 - train 0.38460 | val 2.09370
  Classification -> best τ=0.555 (val F1=0.2083)
  Directional -> Accuracy: 0.4912, MCC: 0.0000, F1: 0.0000

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.42022 | val 1.38046
  Epoch 012 - train 0.33327 | val 1.52410
  Classification -> best τ=0.395 (val F1=0.3073)
  Directional -> Accuracy: 0.4762, MCC: 0.0663, F1: 0.6207

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.46599 | val 1.26196
  Epoch 011 - train 0.40512 | val 1.31131
  Classification -> best τ=0.525 (val F1=0.3387)
  Directional -> Accuracy: 0.5333, MCC: 0.0668, F1: 0.5484

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.45693 | val 0.96145
  Epoch 014 - train 0.34613 | val 1.40696
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4510, MCC: 0.0000, F1: 0.6216

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.50229 | val 1.09189
  Epoch 012 - train 0.48736 | val 1.27583
  Classification -> best τ=0.330 (val F1=0.2659)
  Directional -> Accuracy: 0.5362, MCC: 0.0000, F1: 0.6981

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.47025 | val 1.39180
  Epoch 011 - train 0.47813 | val 1.49479
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.6207, MCC: 0.0000, F1: 0.7660

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.49094 | val 1.94228
  Epoch 011 - train 0.47908 | val 1.98156
  Classification -> best τ=0.555 (val F1=0.2079)
  Directional -> Accuracy: 0.4000, MCC: -0.0338, F1: 0.0426

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.55112 | val 0.99005
  Epoch 011 - train 0.46170 | val 0.95065
  Classification -> best τ=0.530 (val F1=0.3708)
  Directional -> Accuracy: 0.5625, MCC: 0.1782, F1: 0.5333

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.53314 | val 0.82800
  Epoch 012 - train 0.50085 | val 0.84571
  Classification -> best τ=0.500 (val F1=0.2597)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.37796 | val 0.92392
  Epoch 012 - train 0.36615 | val 1.23607
  Classification -> best τ=0.500 (val F1=0.1522)
  Directional -> Accuracy: 0.5745, MCC: -0.0834, F1: 0.7222

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.48974 | val 0.90997
  Epoch 011 - train 0.50693 | val 0.96780
  Classification -> best τ=0.460 (val F1=0.0397)
  Directional -> Accuracy: 0.5538, MCC: 0.1079, F1: 0.6133

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.46108 | val 1.12620
  Epoch 012 - train 0.37724 | val 1.04628
  Classification -> best τ=0.630 (val F1=0.3881)
  Directional -> Accuracy: 0.5088, MCC: 0.0572, F1: 0.4615

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.49143 | val 0.73780
  Epoch 014 - train 0.35775 | val 0.83692
  Classification -> best τ=0.450 (val F1=0.2255)
  Directional -> Accuracy: 0.5846, MCC: 0.2464, F1: 0.6747

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.45017 | val 1.11352
  Epoch 014 - train 0.35563 | val 1.47674
  Classification -> best τ=0.580 (val F1=0.3860)
  Directional -> Accuracy: 0.5636, MCC: 0.2170, F1: 0.4286

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.40037 | val 0.94542
  Epoch 013 - train 0.31090 | val 1.21779
  Classification -> best τ=0.560 (val F1=0.2726)
  Directional -> Accuracy: 0.5778, MCC: 0.1683, F1: 0.5581

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.46238 | val 0.77415
  Epoch 014 - train 0.29638 | val 0.98905
  Classification -> best τ=0.570 (val F1=0.2661)
  Directional -> Accuracy: 0.5476, MCC: 0.0574, F1: 0.6275

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.45173 | val 1.53552
  Epoch 011 - train 0.40194 | val 1.53429
  Classification -> best τ=0.480 (val F1=0.0363)
  Directional -> Accuracy: 0.4643, MCC: -0.2812, F1: 0.6341

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.37041 | val 1.04956
  Epoch 015 - train 0.31402 | val 2.31002
  Classification -> best τ=0.470 (val F1=0.4139)
  Directional -> Accuracy: 0.5500, MCC: 0.0422, F1: 0.6786

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.44060 | val 1.13553
  Epoch 012 - train 0.37594 | val 1.56071
  Classification -> best τ=0.585 (val F1=0.3001)
  Directional -> Accuracy: 0.5000, MCC: 0.0092, F1: 0.5333

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.47467 | val 1.24458
  Epoch 011 - train 0.48763 | val 1.25049
  Classification -> best τ=0.475 (val F1=0.1846)
  Directional -> Accuracy: 0.4762, MCC: 0.1419, F1: 0.0833

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.42986 | val 1.24583
  Epoch 014 - train 0.28851 | val 1.64228
  Classification -> best τ=0.420 (val F1=0.4694)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.47643 | val 1.07722
  Epoch 011 - train 0.46804 | val 1.03932
  Classification -> best τ=0.410 (val F1=0.3215)
  Directional -> Accuracy: 0.5694, MCC: 0.1496, F1: 0.5753

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.47201 | val 1.17217
  Epoch 011 - train 0.43839 | val 1.23136
  Classification -> best τ=0.410 (val F1=0.3078)
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.51376 | val 0.92820
  Epoch 013 - train 0.44190 | val 1.00208
  Classification -> best τ=0.415 (val F1=0.2778)
  Directional -> Accuracy: 0.5303, MCC: -0.0731, F1: 0.6737

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.30962 | val 1.28626
  Epoch 012 - train 0.30839 | val 1.42068
  Classification -> best τ=0.455 (val F1=0.3346)
  Directional -> Accuracy: 0.6667, MCC: 0.3708, F1: 0.6111

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.46888 | val 1.47129
  Epoch 011 - train 0.47396 | val 1.51434
  Classification -> best τ=0.525 (val F1=0.1802)
  Directional -> Accuracy: 0.5714, MCC: 0.1487, F1: 0.5714

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.37968 | val 0.92160
  Epoch 012 - train 0.33660 | val 1.26146
  Classification -> best τ=0.470 (val F1=0.0894)
  Directional -> Accuracy: 0.5000, MCC: 0.0393, F1: 0.5106

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.29394 | val 0.70498
  Epoch 017 - train 0.14727 | val 1.18057
  Classification -> best τ=0.420 (val F1=0.5119)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.53118 | val 1.14032
  Epoch 013 - train 0.45391 | val 1.05458
  Classification -> best τ=0.335 (val F1=0.3052)
  Directional -> Accuracy: 0.4865, MCC: 0.0000, F1: 0.6545

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.52208 | val 0.69260
  Epoch 018 - train 0.28686 | val 1.21483
  Classification -> best τ=0.310 (val F1=0.2169)
  Directional -> Accuracy: 0.5111, MCC: 0.0000, F1: 0.6765

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.45330 | val 0.68283
  Epoch 017 - train 0.20702 | val 1.37950
  Classification -> best τ=0.420 (val F1=0.4588)
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.7273

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.40317 | val 0.70946
  Epoch 020 - train 0.11473 | val 1.39559
  Classification -> best τ=0.500 (val F1=0.3672)
  Directional -> Accuracy: 0.3958, MCC: -0.0457, F1: 0.5085

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.47818 | val 1.00070
  Epoch 012 - train 0.41738 | val 1.04251
  Classification -> best τ=0.545 (val F1=0.2114)
  Directional -> Accuracy: 0.3091, MCC: -0.3750, F1: 0.2083

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.46481 | val 1.66631
  Epoch 012 - train 0.41062 | val 1.67223
  Classification -> best τ=0.545 (val F1=0.2385)
  Directional -> Accuracy: 0.5179, MCC: 0.1857, F1: 0.6667

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.47464 | val 1.16384
  Epoch 012 - train 0.37520 | val 1.25647
  Classification -> best τ=0.505 (val F1=0.2762)
  Directional -> Accuracy: 0.5094, MCC: 0.0000, F1: 0.6750

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.46281 | val 0.98744
  Epoch 011 - train 0.43671 | val 1.25496
  Classification -> best τ=0.510 (val F1=0.2374)
  Directional -> Accuracy: 0.5273, MCC: 0.0000, F1: 0.6905

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.47581 | val 0.71972

[I 2026-02-22 11:17:50,276] Trial 133 finished with value: 0.2643887081957934 and parameters: {'feature_set': 'emotion', 'model_type': 'BiGRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.30000000000000004, 'batch_size': 64, 'learning_rate': 0.006570848382180737, 'weight_decay': 0.00011071201515747617, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 20, 'huber_delta': 0.8046901887524857, 'early_stopping_min_delta': 0.0002484224063132604}. Best is trial 112 with value: 0.2833506688525635.

  Epoch 014 - train 0.39532 | val 0.78180
  Classification -> best τ=0.425 (val F1=0.1638)
  Directional -> Accuracy: 0.5333, MCC: 0.1135, F1: 0.6410

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2643887081957934
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.60868 | val 0.72732
  Epoch 013 - train 0.59960 | val 0.77771
  Classification -> best τ=0.445 (val F1=0.2510)
  Directional -> Accuracy: 0.5526, MCC: 0.0000, F1: 0.0000

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.62159 | val 0.75352
  Epoch 017 - train 0.53522 | val 0.80550
  Classification -> best τ=0.435 (val F1=0.0732)
  Directional -> Accuracy: 0.6222, MCC: 0.2073, F1: 0.7463

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.68250 | val 0.65766
  Epoch 020 - train 0.57096 | val 0.72927
  Classification -> best τ=0.470 (val F1=0.3251)
  Directional -> Accuracy: 0.5000, MCC: -0.1427, F1: 0.6667

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.65699 | val 0.86709
  Epoch 012 - train 0.65284 | val 0.90620
  Classification -> best τ=0.560 (val F1=0.0966)
  Directional -> Accuracy: 0.5000, MCC: -0.0228, F1: 0.5747

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.60895 | val 0.72756
  Epoch 014 - train 0.61573 | val 0.69970
  Classification -> best τ=0.535 (val F1=0.4753)
  Directional -> Accuracy: 0.7200, MCC: 0.4576, F1: 0.6957

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.62809 | val 1.02580
  Epoch 013 - train 0.56713 | val 0.77767
  Classification -> best τ=0.565 (val F1=0.2739)
  Directional -> Accuracy: 0.3913, MCC: -0.2179, F1: 0.4815

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.64691 | val 0.72924
  Epoch 016 - train 0.62922 | val 0.76653
  Classification -> best τ=0.300 (val F1=0.2352)
  Directional -> Accuracy: 0.4559, MCC: 0.1097, F1: 0.5747

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.58712 | val 1.13723
  Epoch 015 - train 0.56817 | val 1.04340
  Classification -> best τ=0.385 (val F1=0.1657)
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.59952 | val 0.96143
  Epoch 015 - train 0.55941 | val 1.13143
  Classification -> best τ=0.565 (val F1=0.2764)
  Directional -> Accuracy: 0.6250, MCC: 0.2492, F1: 0.3077

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.64084 | val 0.69925
  Epoch 014 - train 0.60914 | val 0.72319
  Classification -> best τ=0.545 (val F1=0.1767)
  Directional -> Accuracy: 0.5652, MCC: 0.0994, F1: 0.4643

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.67495 | val 0.73806
  Epoch 012 - train 0.65678 | val 0.72634
  Classification -> best τ=0.395 (val F1=0.1199)
  Directional -> Accuracy: 0.4694, MCC: 0.1303, F1: 0.6286

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.63123 | val 0.87580
  Epoch 015 - train 0.59842 | val 1.08077
  Classification -> best τ=0.580 (val F1=0.3032)
  Directional -> Accuracy: 0.6842, MCC: 0.3704, F1: 0.7097

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.58569 | val 1.05429
  Epoch 013 - train 0.54238 | val 0.84649
  Classification -> best τ=0.520 (val F1=0.2018)
  Directional -> Accuracy: 0.5476, MCC: 0.1513, F1: 0.6122

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.65341 | val 0.71709
  Epoch 011 - train 0.63185 | val 0.70846
  Classification -> best τ=0.445 (val F1=0.4019)
  Directional -> Accuracy: 0.5333, MCC: 0.0667, F1: 0.5333

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.62158 | val 0.72969
  Epoch 020 - train 0.52529 | val 0.79230
  Epoch 022 - train 0.48532 | val 0.79126
  Classification -> best τ=0.450 (val F1=0.2296)
  Directional -> Accuracy: 0.6471, MCC: 0.2786, F1: 0.5500

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.58837 | val 0.99399
  Epoch 014 - train 0.58946 | val 1.04664
  Classification -> best τ=0.680 (val F1=0.2722)
  Directional -> Accuracy: 0.5362, MCC: 0.1508, F1: 0.3600

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.62280 | val 1.02156
  Epoch 013 - train 0.64338 | val 0.97306
  Classification -> best τ=0.585 (val F1=0.1291)
  Directional -> Accuracy: 0.4483, MCC: 0.2128, F1: 0.2000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.65432 | val 0.80039
  Epoch 011 - train 0.64888 | val 0.83367
  Classification -> best τ=0.475 (val F1=0.1480)
  Directional -> Accuracy: 0.6000, MCC: 0.0000, F1: 0.7500

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.64683 | val 0.70834
  Epoch 017 - train 0.62958 | val 0.82814
  Classification -> best τ=0.445 (val F1=0.2752)
  Directional -> Accuracy: 0.4688, MCC: 0.0725, F1: 0.2609

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.61868 | val 0.77491
  Epoch 012 - train 0.61668 | val 0.80716
  Classification -> best τ=0.550 (val F1=0.2871)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.65261 | val 0.69509
  Epoch 020 - train 0.60133 | val 0.67462
  Epoch 030 - train 0.48220 | val 0.70694
  Classification -> best τ=0.400 (val F1=0.3458)
  Directional -> Accuracy: 0.4894, MCC: 0.0958, F1: 0.4286

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.66252 | val 0.77734
  Epoch 013 - train 0.62361 | val 0.79144
  Classification -> best τ=0.445 (val F1=0.1296)
  Directional -> Accuracy: 0.5077, MCC: 0.0000, F1: 0.6735

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.62775 | val 0.82913
  Epoch 015 - train 0.56468 | val 0.83073
  Classification -> best τ=0.685 (val F1=0.2644)
  Directional -> Accuracy: 0.4912, MCC: 0.0154, F1: 0.4528

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.65221 | val 0.76130
  Epoch 017 - train 0.59854 | val 0.80324
  Classification -> best τ=0.530 (val F1=0.1565)
  Directional -> Accuracy: 0.5385, MCC: 0.0711, F1: 0.1667

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.61064 | val 0.85719
  Epoch 014 - train 0.56593 | val 1.13407
  Classification -> best τ=0.520 (val F1=0.5155)
  Directional -> Accuracy: 0.5273, MCC: 0.1463, F1: 0.3500

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.60785 | val 0.79634
  Epoch 011 - train 0.59429 | val 0.83258
  Classification -> best τ=0.475 (val F1=0.0447)
  Directional -> Accuracy: 0.5111, MCC: -0.1591, F1: 0.0833

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.62427 | val 0.68811
  Epoch 020 - train 0.57465 | val 0.73587
  Epoch 027 - train 0.54726 | val 0.74628
  Classification -> best τ=0.690 (val F1=0.1936)
  Directional -> Accuracy: 0.4048, MCC: -0.1803, F1: 0.0000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.60040 | val 0.83096
  Epoch 012 - train 0.60502 | val 0.89846
  Classification -> best τ=0.355 (val F1=0.2058)
  Directional -> Accuracy: 0.5893, MCC: 0.2499, F1: 0.5106

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.67420 | val 0.69069
  Epoch 012 - train 0.64348 | val 0.68891
  Classification -> best τ=0.590 (val F1=0.4114)
  Directional -> Accuracy: 0.5250, MCC: 0.1069, F1: 0.4242

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.64062 | val 0.97190
  Epoch 012 - train 0.63487 | val 1.14502
  Classification -> best τ=0.595 (val F1=0.3501)
  Directional -> Accuracy: 0.5238, MCC: 0.0500, F1: 0.5238

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.65328 | val 1.09506
  Epoch 011 - train 0.62158 | val 1.13709
  Classification -> best τ=0.460 (val F1=0.2042)
  Directional -> Accuracy: 0.5476, MCC: 0.0000, F1: 0.7077

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.64423 | val 0.68527
  Epoch 018 - train 0.59410 | val 0.92616
  Classification -> best τ=0.320 (val F1=0.3957)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.64404 | val 0.66086
  Epoch 015 - train 0.62902 | val 0.68337
  Classification -> best τ=0.415 (val F1=0.3117)
  Directional -> Accuracy: 0.5278, MCC: 0.1419, F1: 0.3929

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.64142 | val 0.85495
  Epoch 011 - train 0.63516 | val 0.84214
  Classification -> best τ=0.515 (val F1=0.0444)
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.62676 | val 0.93829
  Epoch 012 - train 0.62327 | val 0.96672
  Classification -> best τ=0.550 (val F1=0.2179)
  Directional -> Accuracy: 0.4242, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.59683 | val 0.76281
  Epoch 014 - train 0.56802 | val 0.85185
  Classification -> best τ=0.515 (val F1=0.2618)
  Directional -> Accuracy: 0.6429, MCC: 0.3290, F1: 0.5714

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.56455 | val 0.81190
  Epoch 013 - train 0.55365 | val 0.75323
  Classification -> best τ=0.490 (val F1=0.2717)
  Directional -> Accuracy: 0.5179, MCC: 0.0234, F1: 0.4490

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.58022 | val 0.75505
  Epoch 011 - train 0.58803 | val 0.78731
  Classification -> best τ=0.465 (val F1=0.2118)
  Directional -> Accuracy: 0.5870, MCC: 0.0062, F1: 0.7246

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.63081 | val 0.77466
  Epoch 016 - train 0.57699 | val 0.70607
  Classification -> best τ=0.530 (val F1=0.3800)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.61264 | val 0.78602
  Epoch 011 - train 0.58271 | val 0.85598
  Classification -> best τ=0.445 (val F1=0.2732)
  Directional -> Accuracy: 0.4865, MCC: 0.0000, F1: 0.6545

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.62751 | val 0.79133
  Epoch 012 - train 0.66129 | val 0.82773
  Classification -> best τ=0.510 (val F1=0.2000)
  Directional -> Accuracy: 0.5111, MCC: 0.0000, F1: 0.6765

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.58831 | val 0.77158
  Epoch 012 - train 0.59396 | val 0.76387
  Classification -> best τ=0.540 (val F1=0.5230)
  Directional -> Accuracy: 0.5238, MCC: 0.0142, F1: 0.6000

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.59721 | val 0.63161
  Epoch 020 - train 0.49322 | val 0.67318
  Epoch 021 - train 0.47584 | val 0.64577
  Classification -> best τ=0.495 (val F1=0.4682)
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.5455

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.63454 | val 0.72527
  Epoch 011 - train 0.64848 | val 0.73361
  Classification -> best τ=0.505 (val F1=0.2833)
  Directional -> Accuracy: 0.5273, MCC: -0.0585, F1: 0.6829

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.57329 | val 1.71740
  Epoch 012 - train 0.55713 | val 2.19686
  Classification -> best τ=0.610 (val F1=0.3246)
  Directional -> Accuracy: 0.5179, MCC: 0.0875, F1: 0.6400

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.61113 | val 0.85125
  Epoch 011 - train 0.62727 | val 0.87458
  Classification -> best τ=0.610 (val F1=0.2064)
  Directional -> Accuracy: 0.6038, MCC: 0.2103, F1: 0.5882

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.60781 | val 0.76972
  Epoch 011 - train 0.60487 | val 0.74219
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5273, MCC: 0.0000, F1: 0.6905

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.62511 | val 0.67831
  Epoch 020 - train 0.57335 | val 0.71518
  Epoch 021 - train 0.54966 | val 0.69210

[I 2026-02-22 11:19:18,389] Trial 134 finished with value: 0.2538706041389838 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.4, 'batch_size': 64, 'learning_rate': 0.009871104604871925, 'weight_decay': 3.099917258639424e-05, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 0.8692589761637575, 'early_stopping_min_delta': 0.0010123655228086357}. Best is trial 112 with value: 0.2833506688525635.

  Classification -> best τ=0.335 (val F1=0.2732)
  Directional -> Accuracy: 0.4833, MCC: 0.0000, F1: 0.6517

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2538706041389838
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.62614 | val 0.74901
  Epoch 015 - train 0.53447 | val 1.42515
  Classification -> best τ=0.575 (val F1=0.2510)
  Directional -> Accuracy: 0.6053, MCC: 0.1858, F1: 0.4828

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.53617 | val 0.71796
  Epoch 014 - train 0.46019 | val 0.79015
  Classification -> best τ=0.535 (val F1=0.1764)
  Directional -> Accuracy: 0.5111, MCC: 0.0402, F1: 0.5217

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.57179 | val 0.99183
  Epoch 012 - train 0.54910 | val 1.12753
  Classification -> best τ=0.595 (val F1=0.1978)
  Directional -> Accuracy: 0.4783, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.59816 | val 0.79154
  Epoch 012 - train 0.57364 | val 1.03267
  Classification -> best τ=0.425 (val F1=0.1085)
  Directional -> Accuracy: 0.5270, MCC: 0.0852, F1: 0.4615

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.51235 | val 0.66872
  Epoch 016 - train 0.38405 | val 0.93364
  Classification -> best τ=0.535 (val F1=0.3751)
  Directional -> Accuracy: 0.6000, MCC: 0.2300, F1: 0.5238

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.54576 | val 0.68625
  Epoch 020 - train 0.42593 | val 0.79082
  Classification -> best τ=0.585 (val F1=0.2739)
  Directional -> Accuracy: 0.5217, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.59291 | val 1.21299
  Epoch 013 - train 0.58456 | val 1.29611
  Classification -> best τ=0.420 (val F1=0.2519)
  Directional -> Accuracy: 0.5000, MCC: 0.0443, F1: 0.5000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.50080 | val 0.58218
  Epoch 020 - train 0.33373 | val 0.73253
  Epoch 025 - train 0.30828 | val 0.86078
  Classification -> best τ=0.480 (val F1=0.3632)
  Directional -> Accuracy: 0.4762, MCC: 0.0525, F1: 0.5769

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.56100 | val 0.94763
  Epoch 017 - train 0.46013 | val 1.56807
  Classification -> best τ=0.605 (val F1=0.4022)
  Directional -> Accuracy: 0.5625, MCC: 0.0380, F1: 0.1600

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.55036 | val 0.73211
  Epoch 015 - train 0.46552 | val 0.71039
  Classification -> best τ=0.580 (val F1=0.2178)
  Directional -> Accuracy: 0.5072, MCC: -0.0017, F1: 0.4333

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.58891 | val 0.82591
  Epoch 012 - train 0.54624 | val 0.82384
  Classification -> best τ=0.470 (val F1=0.3075)
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.56416 | val 0.97734
  Epoch 012 - train 0.54263 | val 0.97664
  Classification -> best τ=0.465 (val F1=0.1576)
  Directional -> Accuracy: 0.4737, MCC: -0.1326, F1: 0.6341

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.53754 | val 1.63390
  Epoch 011 - train 0.51113 | val 1.59609
  Classification -> best τ=0.555 (val F1=0.1328)
  Directional -> Accuracy: 0.4048, MCC: -0.1758, F1: 0.5455

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.53481 | val 0.77188
  Epoch 014 - train 0.53153 | val 0.82978
  Classification -> best τ=0.520 (val F1=0.3378)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.54825 | val 0.88161
  Epoch 017 - train 0.45678 | val 1.01218
  Classification -> best τ=0.715 (val F1=0.2571)
  Directional -> Accuracy: 0.5490, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.53055 | val 1.06279
  Epoch 012 - train 0.50426 | val 1.16632
  Classification -> best τ=0.555 (val F1=0.1953)
  Directional -> Accuracy: 0.5652, MCC: 0.1223, F1: 0.6053

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.57052 | val 0.91272
  Epoch 011 - train 0.58056 | val 0.94799
  Classification -> best τ=0.475 (val F1=0.0866)
  Directional -> Accuracy: 0.6207, MCC: 0.0000, F1: 0.7660

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.60129 | val 1.01502
  Epoch 011 - train 0.56776 | val 1.02165
  Classification -> best τ=0.440 (val F1=0.1653)
  Directional -> Accuracy: 0.5200, MCC: -0.1118, F1: 0.6604

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.62214 | val 0.96934
  Epoch 013 - train 0.55186 | val 1.02167
  Classification -> best τ=0.555 (val F1=0.3238)
  Directional -> Accuracy: 0.4844, MCC: 0.0694, F1: 0.3529

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.59376 | val 0.68476
  Epoch 016 - train 0.47715 | val 0.80430
  Classification -> best τ=0.610 (val F1=0.3164)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.55313 | val 0.78366
  Epoch 012 - train 0.50140 | val 0.77825
  Classification -> best τ=0.520 (val F1=0.1448)
  Directional -> Accuracy: 0.6170, MCC: 0.2072, F1: 0.6786

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.57779 | val 0.88494
  Epoch 014 - train 0.49506 | val 1.06057
  Classification -> best τ=0.470 (val F1=0.2794)
  Directional -> Accuracy: 0.4923, MCC: -0.0039, F1: 0.1081

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.55095 | val 0.85782
  Epoch 012 - train 0.54823 | val 0.80823
  Classification -> best τ=0.655 (val F1=0.2644)
  Directional -> Accuracy: 0.5439, MCC: 0.1093, F1: 0.5357

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.59291 | val 0.74319
  Epoch 012 - train 0.56571 | val 0.73198
  Classification -> best τ=0.525 (val F1=0.1348)
  Directional -> Accuracy: 0.5538, MCC: 0.1575, F1: 0.6420

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.50449 | val 0.92437
  Epoch 013 - train 0.49954 | val 1.05977
  Classification -> best τ=0.515 (val F1=0.4199)
  Directional -> Accuracy: 0.5455, MCC: 0.1826, F1: 0.3902

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.51874 | val 1.08138
  Epoch 012 - train 0.53779 | val 1.27366
  Classification -> best τ=0.560 (val F1=0.2756)
  Directional -> Accuracy: 0.4444, MCC: -0.0636, F1: 0.4898

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.57284 | val 0.69551
  Epoch 011 - train 0.54624 | val 0.70423
  Classification -> best τ=0.555 (val F1=0.2178)
  Directional -> Accuracy: 0.4286, MCC: -0.0323, F1: 0.0769

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.55447 | val 0.78398
  Epoch 015 - train 0.47055 | val 0.89159
  Classification -> best τ=0.590 (val F1=0.2478)
  Directional -> Accuracy: 0.4464, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.52961 | val 0.85382
  Epoch 014 - train 0.43915 | val 0.92961
  Classification -> best τ=0.505 (val F1=0.3278)
  Directional -> Accuracy: 0.5500, MCC: 0.0231, F1: 0.7000

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.50316 | val 1.01603
  Epoch 012 - train 0.50614 | val 0.91593
  Classification -> best τ=0.525 (val F1=0.3501)
  Directional -> Accuracy: 0.5476, MCC: 0.0912, F1: 0.5128

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.55331 | val 1.48997
  Epoch 013 - train 0.47765 | val 1.55211
  Classification -> best τ=0.405 (val F1=0.1425)
  Directional -> Accuracy: 0.5238, MCC: -0.1419, F1: 0.6875

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.55550 | val 0.98372
  Epoch 011 - train 0.51127 | val 1.00563
  Classification -> best τ=0.450 (val F1=0.3541)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.58153 | val 1.14727
  Epoch 013 - train 0.53920 | val 0.90528
  Classification -> best τ=0.420 (val F1=0.2370)
  Directional -> Accuracy: 0.4444, MCC: 0.0000, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.50475 | val 0.90037
  Epoch 011 - train 0.49403 | val 0.93676
  Classification -> best τ=0.505 (val F1=0.1874)
  Directional -> Accuracy: 0.4884, MCC: -0.0261, F1: 0.4500

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.54802 | val 1.29110
  Epoch 011 - train 0.52424 | val 1.28741
  Classification -> best τ=0.500 (val F1=0.2464)
  Directional -> Accuracy: 0.5758, MCC: 0.0000, F1: 0.7308

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.49726 | val 1.57451
  Epoch 012 - train 0.43514 | val 1.63197
  Classification -> best τ=0.490 (val F1=0.3001)
  Directional -> Accuracy: 0.6667, MCC: 0.3371, F1: 0.7200

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.50394 | val 1.11505
  Epoch 011 - train 0.50853 | val 1.30941
  Classification -> best τ=0.505 (val F1=0.2203)
  Directional -> Accuracy: 0.5179, MCC: 0.0437, F1: 0.5263

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.44164 | val 0.81511
  Epoch 013 - train 0.46147 | val 0.99664
  Classification -> best τ=0.615 (val F1=0.2268)
  Directional -> Accuracy: 0.3913, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.59834 | val 0.65174
  Epoch 020 - train 0.51596 | val 0.62974
  Epoch 030 - train 0.47990 | val 0.70562
  Classification -> best τ=0.535 (val F1=0.4710)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.51962 | val 1.19261
  Epoch 012 - train 0.49407 | val 1.20250
  Classification -> best τ=0.440 (val F1=0.2169)
  Directional -> Accuracy: 0.4865, MCC: 0.0000, F1: 0.6545

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.60792 | val 0.70889
  Epoch 011 - train 0.58066 | val 0.70784
  Classification -> best τ=0.490 (val F1=0.4914)
  Directional -> Accuracy: 0.5111, MCC: 0.0000, F1: 0.6765

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.49794 | val 0.78747
  Epoch 014 - train 0.41324 | val 0.99576
  Classification -> best τ=0.605 (val F1=0.3118)
  Directional -> Accuracy: 0.4524, MCC: -0.0168, F1: 0.3030

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.54443 | val 0.65207
  Epoch 020 - train 0.37450 | val 0.79926
  Epoch 021 - train 0.36940 | val 0.86483
  Classification -> best τ=0.460 (val F1=0.3672)
  Directional -> Accuracy: 0.6042, MCC: 0.4223, F1: 0.6545

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.59567 | val 0.75667
  Epoch 011 - train 0.58188 | val 0.75455
  Classification -> best τ=0.560 (val F1=0.2036)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.48341 | val 1.65829
  Epoch 013 - train 0.45115 | val 1.76444
  Classification -> best τ=0.570 (val F1=0.3487)
  Directional -> Accuracy: 0.5357, MCC: 0.1397, F1: 0.0714

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.59166 | val 0.90570
  Epoch 012 - train 0.54816 | val 0.85774
  Classification -> best τ=0.420 (val F1=0.2298)
  Directional -> Accuracy: 0.5472, MCC: 0.2018, F1: 0.6923

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.55374 | val 1.06050
  Epoch 011 - train 0.53416 | val 1.02411
  Classification -> best τ=0.525 (val F1=0.1209)
  Directional -> Accuracy: 0.5273, MCC: 0.0000, F1: 0.6905

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.54066 | val 0.66664

[I 2026-02-22 11:20:41,340] Trial 135 finished with value: 0.2607279003486552 and parameters: {'feature_set': 'sector', 'model_type': 'BiGRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.2, 'batch_size': 64, 'learning_rate': 0.005175487464060927, 'weight_decay': 2.1855157981343627e-05, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 0.9187049345375843, 'early_stopping_min_delta': 0.0013279213449019132}. Best is trial 112 with value: 0.2833506688525635.

  Epoch 019 - train 0.48195 | val 0.78374
  Classification -> best τ=0.465 (val F1=0.2787)
  Directional -> Accuracy: 0.6500, MCC: 0.3074, F1: 0.6667

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2607279003486552
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d', 'emotion_anger', 'emotion_disgust', 'emotion_fear', 'emotion_joy', 'emotion_neutral', 'emotion_sadness', 'emotion_surprize', 'emotion_anger_pct', 'emotion_disgust_pct', 'emotion_fear_pct', 'emotion_joy_pct', 'emotion_neutral_pct', 'emotion_sadness_pct', 'emotion_surprize_pct']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.44981 | val 0.76300
  Epoch 015 - train 0.40577 | val 0.85460
  Classification -> best τ=0.570 (val F1=0.2919)
  Directional -> Accuracy: 0.5658, MCC: 0.1062, F1: 0.4590

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.34680 | val 0.89835
  Epoch 013 - train 0.32195 | val 1.14795
  Classification -> best τ=0.500 (val F1=0.1764)
  Directional -> Accuracy: 0.6000, MCC: 0.2829, F1: 0.5500

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.38667 | val 1.49990
  Epoch 011 - train 0.39126 | val 1.73470
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5217, MCC: 0.0000, F1: 0.6857

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.51652 | val 1.00118
  Epoch 014 - train 0.42440 | val 1.38162
  Classification -> best τ=0.390 (val F1=0.4538)
  Directional -> Accuracy: 0.5135, MCC: 0.0249, F1: 0.5385

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.42685 | val 0.98336
  Epoch 014 - train 0.28027 | val 1.24693
  Classification -> best τ=0.660 (val F1=0.3077)
  Directional -> Accuracy: 0.5200, MCC: 0.1358, F1: 0.2000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.39070 | val 1.01781
  Epoch 011 - train 0.41090 | val 1.01304
  Classification -> best τ=0.490 (val F1=0.1808)
  Directional -> Accuracy: 0.5217, MCC: 0.0543, F1: 0.5600

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.51579 | val 1.12372
  Epoch 011 - train 0.49205 | val 1.03168
  Classification -> best τ=0.440 (val F1=0.1963)
  Directional -> Accuracy: 0.4853, MCC: 0.1391, F1: 0.5783

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.41572 | val 0.86534
  Epoch 017 - train 0.19795 | val 1.41898
  Classification -> best τ=0.455 (val F1=0.4176)
  Directional -> Accuracy: 0.4762, MCC: -0.0142, F1: 0.5000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.39640 | val 0.91028
  Epoch 012 - train 0.31866 | val 1.15198
  Classification -> best τ=0.500 (val F1=0.1715)
  Directional -> Accuracy: 0.6458, MCC: 0.2940, F1: 0.6222

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.44649 | val 0.87212
  Epoch 012 - train 0.41004 | val 0.90506
  Classification -> best τ=0.480 (val F1=0.1858)
  Directional -> Accuracy: 0.3913, MCC: -0.1502, F1: 0.5333

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.42757 | val 0.98787
  Epoch 012 - train 0.38181 | val 1.18308
  Classification -> best τ=0.560 (val F1=0.1738)
  Directional -> Accuracy: 0.5918, MCC: 0.2285, F1: 0.1667

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.42449 | val 1.63895
  Epoch 011 - train 0.42855 | val 1.85920
  Classification -> best τ=0.465 (val F1=0.1651)
  Directional -> Accuracy: 0.6667, MCC: 0.3859, F1: 0.7397

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.38939 | val 1.17425
  Epoch 011 - train 0.35687 | val 1.53955
  Classification -> best τ=0.430 (val F1=0.0548)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.6230

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.43972 | val 0.95529
  Epoch 012 - train 0.37685 | val 0.98457
  Classification -> best τ=0.430 (val F1=0.3768)
  Directional -> Accuracy: 0.4500, MCC: -0.2294, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.41865 | val 0.85783
  Epoch 014 - train 0.32708 | val 1.20434
  Classification -> best τ=0.440 (val F1=0.1901)
  Directional -> Accuracy: 0.6667, MCC: 0.3676, F1: 0.4516

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.47041 | val 1.11028
  Epoch 011 - train 0.44015 | val 1.15982
  Classification -> best τ=0.480 (val F1=0.1203)
  Directional -> Accuracy: 0.5362, MCC: 0.0180, F1: 0.6863

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.46113 | val 1.23308
  Epoch 011 - train 0.42255 | val 1.31178
  Classification -> best τ=0.585 (val F1=0.1065)
  Directional -> Accuracy: 0.3621, MCC: -0.1657, F1: 0.2128

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.50438 | val 1.30184
  Epoch 011 - train 0.45775 | val 1.26117
  Classification -> best τ=0.585 (val F1=0.1087)
  Directional -> Accuracy: 0.4000, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.47957 | val 0.81596
  Epoch 011 - train 0.41921 | val 0.90071
  Classification -> best τ=0.465 (val F1=0.2352)
  Directional -> Accuracy: 0.6250, MCC: 0.1979, F1: 0.7333

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.49132 | val 1.01422
  Epoch 012 - train 0.41278 | val 1.09375
  Classification -> best τ=0.445 (val F1=0.2760)
  Directional -> Accuracy: 0.5135, MCC: 0.1971, F1: 0.2500

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.37864 | val 1.09821
  Epoch 011 - train 0.31381 | val 1.09147
  Classification -> best τ=0.510 (val F1=0.2861)
  Directional -> Accuracy: 0.4255, MCC: -0.0182, F1: 0.3077

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.45121 | val 1.34966
  Epoch 011 - train 0.37433 | val 1.36738
  Classification -> best τ=0.315 (val F1=0.2237)
  Directional -> Accuracy: 0.6000, MCC: 0.2029, F1: 0.5806

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.39125 | val 1.03444
  Epoch 013 - train 0.31986 | val 1.14611
  Classification -> best τ=0.670 (val F1=0.3749)
  Directional -> Accuracy: 0.4386, MCC: -0.0500, F1: 0.2000

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.44660 | val 0.85010
  Epoch 012 - train 0.40351 | val 0.81474
  Classification -> best τ=0.510 (val F1=0.2073)
  Directional -> Accuracy: 0.4923, MCC: 0.0042, F1: 0.5714

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.38233 | val 1.13256
  Epoch 013 - train 0.33781 | val 1.54199
  Classification -> best τ=0.395 (val F1=0.4001)
  Directional -> Accuracy: 0.5818, MCC: 0.2024, F1: 0.5306

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.32453 | val 0.72411
  Epoch 019 - train 0.08301 | val 1.21549
  Classification -> best τ=0.480 (val F1=0.3764)
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.5938

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.39917 | val 0.81581
  Epoch 012 - train 0.36423 | val 0.89391
  Classification -> best τ=0.540 (val F1=0.3596)
  Directional -> Accuracy: 0.5000, MCC: -0.0280, F1: 0.5714

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.48168 | val 1.16054
  Epoch 012 - train 0.42082 | val 1.22635
  Classification -> best τ=0.400 (val F1=0.1151)
  Directional -> Accuracy: 0.5536, MCC: 0.0207, F1: 0.7059

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.43247 | val 0.74175
  Epoch 016 - train 0.32216 | val 1.57013
  Classification -> best τ=0.525 (val F1=0.3477)
  Directional -> Accuracy: 0.5750, MCC: 0.1297, F1: 0.6383

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.45220 | val 1.34017
  Epoch 011 - train 0.39721 | val 1.38928
  Classification -> best τ=0.540 (val F1=0.2221)
  Directional -> Accuracy: 0.4524, MCC: -0.1228, F1: 0.3030

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.41651 | val 1.73136
  Epoch 012 - train 0.34358 | val 1.92484
  Classification -> best τ=0.560 (val F1=0.0128)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.42492 | val 0.98742
  Epoch 014 - train 0.29576 | val 1.42606
  Classification -> best τ=0.305 (val F1=0.3142)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.49939 | val 0.90644
  Epoch 012 - train 0.44465 | val 0.84821
  Classification -> best τ=0.440 (val F1=0.2513)
  Directional -> Accuracy: 0.5556, MCC: 0.0000, F1: 0.7143

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.40457 | val 1.11329
  Epoch 013 - train 0.35890 | val 1.23484
  Classification -> best τ=0.445 (val F1=0.2717)
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.50152 | val 0.96692
  Epoch 011 - train 0.47697 | val 1.02556
  Classification -> best τ=0.500 (val F1=0.1970)
  Directional -> Accuracy: 0.5455, MCC: -0.0072, F1: 0.6739

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.33048 | val 0.89809
  Epoch 014 - train 0.20051 | val 1.42010
  Classification -> best τ=0.450 (val F1=0.3941)
  Directional -> Accuracy: 0.6429, MCC: 0.2821, F1: 0.6809

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.38868 | val 1.72385
  Epoch 011 - train 0.35944 | val 2.13040
  Classification -> best τ=0.525 (val F1=0.2327)
  Directional -> Accuracy: 0.4821, MCC: -0.0283, F1: 0.4912

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.35713 | val 0.93612
  Epoch 014 - train 0.26004 | val 1.08101
  Classification -> best τ=0.630 (val F1=0.2924)
  Directional -> Accuracy: 0.3913, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.40782 | val 0.71302
  Epoch 018 - train 0.16437 | val 1.19485
  Classification -> best τ=0.465 (val F1=0.3859)
  Directional -> Accuracy: 0.3333, MCC: -0.1687, F1: 0.4839

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.41316 | val 1.37890
  Epoch 011 - train 0.39187 | val 1.56050
  Classification -> best τ=0.415 (val F1=0.2044)
  Directional -> Accuracy: 0.4865, MCC: 0.0000, F1: 0.6545

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.44832 | val 0.83500
  Epoch 011 - train 0.44070 | val 0.87552
  Classification -> best τ=0.465 (val F1=0.1569)
  Directional -> Accuracy: 0.4222, MCC: -0.1540, F1: 0.3810

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.35218 | val 0.72360
  Epoch 015 - train 0.21609 | val 0.82414
  Classification -> best τ=0.535 (val F1=0.3333)
  Directional -> Accuracy: 0.4286, MCC: -0.0913, F1: 0.3333

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.36648 | val 0.66927
  Epoch 019 - train 0.15769 | val 1.00687
  Classification -> best τ=0.730 (val F1=0.4092)
  Directional -> Accuracy: 0.5833, MCC: 0.1943, F1: 0.5455

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.46285 | val 0.94133
  Epoch 011 - train 0.44772 | val 0.94516
  Classification -> best τ=0.470 (val F1=0.1763)
  Directional -> Accuracy: 0.5273, MCC: -0.1242, F1: 0.6905

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.35943 | val 1.20362
  Epoch 013 - train 0.29257 | val 1.09248
  Classification -> best τ=0.415 (val F1=0.2939)
  Directional -> Accuracy: 0.5893, MCC: 0.2147, F1: 0.6567

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.40187 | val 0.89778
  Epoch 016 - train 0.24493 | val 1.48974
  Classification -> best τ=0.595 (val F1=0.2434)
  Directional -> Accuracy: 0.5472, MCC: 0.0946, F1: 0.6250

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.39691 | val 1.06634
  Epoch 011 - train 0.42828 | val 1.13717
  Classification -> best τ=0.555 (val F1=0.2291)
  Directional -> Accuracy: 0.4909, MCC: 0.0671, F1: 0.1250

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.48414 | val 0.88155

[I 2026-02-22 11:22:00,328] Trial 136 finished with value: 0.24861414370362037 and parameters: {'feature_set': 'sector_emotion', 'model_type': 'BiGRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.2, 'batch_size': 64, 'learning_rate': 0.0039975922613752594, 'weight_decay': 0.00034658570690327154, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 0.5213999538118674, 'early_stopping_min_delta': 0.0007053508716758565}. Best is trial 112 with value: 0.2833506688525635.

  Epoch 019 - train 0.25280 | val 0.93036
  Classification -> best τ=0.365 (val F1=0.4330)
  Directional -> Accuracy: 0.5333, MCC: 0.0842, F1: 0.1250

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.24861414370362037
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d', 'sentiment', 'emotion_anger', 'emotion_disgust', 'emotion_fear', 'emotion_joy', 'emotion_neutral', 'emotion_sadness', 'emotion_surprize', 'emotion_anger_pct', 'emotion_disgust_pct', 'emotion_fear_pct', 'emotion_joy_pct', 'emotion_neutral_pct', 'emotion_sadness_pct', 'emotion_surprize_pct', 'positive_emotion', 'negative_emotion', 'uncertainty_emotion', 'positive_emotion_pct', 'negative_emotion_pct', 'uncertainty_emotion_pct', 'stance_label', 'stance_score', 'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down', 'finbert_neutral']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.66690 | val 0.67563
  Epoch 020 - train 0.65639 | val 0.67929
  Classification -> best τ=0.450 (val F1=0.1988)
  Directional -> Accuracy: 0.5844, MCC: 0.2309, F1: 0.6444

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.65840 | val 0.67884
  Epoch 020 - train 0.61476 | val 0.68754
  Epoch 022 - train 0.61564 | val 0.69327
  Classification -> best τ=0.465 (val F1=0.2820)
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.7222

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.68299 | val 0.70322
  Epoch 011 - train 0.67790 | val 0.70469
  Classification -> best τ=0.490 (val F1=0.1838)
  Directional -> Accuracy: 0.5745, MCC: 0.1381, F1: 0.6296

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.66965 | val 0.79876
  Epoch 011 - train 0.67331 | val 0.81311
  Classification -> best τ=0.480 (val F1=0.1453)
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.66532 | val 0.66834
  Epoch 020 - train 0.64234 | val 0.66191
  Epoch 030 - train 0.60768 | val 0.66679
  Classification -> best τ=0.550 (val F1=0.2826)
  Directional -> Accuracy: 0.5490, MCC: 0.1398, F1: 0.4390

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.70249 | val 0.70065
  Epoch 011 - train 0.69301 | val 0.70105
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4894, MCC: 0.0000, F1: 0.6571

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.67045 | val 0.68745
  Epoch 017 - train 0.66430 | val 0.69277
  Classification -> best τ=0.450 (val F1=0.2100)
  Directional -> Accuracy: 0.4493, MCC: 0.1762, F1: 0.5957

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.70416 | val 0.66381
  Epoch 016 - train 0.68638 | val 0.66739
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.5806

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.67935 | val 0.70680
  Epoch 011 - train 0.68011 | val 0.70736
  Classification -> best τ=0.525 (val F1=0.2891)
  Directional -> Accuracy: 0.5306, MCC: 0.0637, F1: 0.5106

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.65647 | val 0.68778
  Epoch 019 - train 0.62894 | val 0.69540
  Classification -> best τ=0.490 (val F1=0.2847)
  Directional -> Accuracy: 0.4714, MCC: 0.0424, F1: 0.5747

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.68337 | val 0.74233
  Epoch 011 - train 0.70165 | val 0.74908
  Classification -> best τ=0.540 (val F1=0.0754)
  Directional -> Accuracy: 0.5200, MCC: 0.0695, F1: 0.5714

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.67712 | val 0.69792
  Epoch 011 - train 0.66209 | val 0.70052
  Classification -> best τ=0.530 (val F1=0.0457)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0645

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.66626 | val 0.71756
  Epoch 011 - train 0.66443 | val 0.72372
  Classification -> best τ=0.510 (val F1=0.3451)
  Directional -> Accuracy: 0.5814, MCC: 0.1513, F1: 0.5263

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.64971 | val 0.62707
  Epoch 020 - train 0.62101 | val 0.63144
  Epoch 023 - train 0.61863 | val 0.63478
  Classification -> best τ=0.560 (val F1=0.3656)
  Directional -> Accuracy: 0.4918, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.67380 | val 0.72396
  Epoch 011 - train 0.68713 | val 0.72688
  Classification -> best τ=0.555 (val F1=0.2184)
  Directional -> Accuracy: 0.4423, MCC: -0.0872, F1: 0.5538

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.66879 | val 0.71417
  Epoch 014 - train 0.66577 | val 0.72810
  Classification -> best τ=0.475 (val F1=0.0772)
  Directional -> Accuracy: 0.5857, MCC: 0.1597, F1: 0.6329

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.67421 | val 0.71813
  Epoch 011 - train 0.65962 | val 0.72577
  Classification -> best τ=0.525 (val F1=0.2335)
  Directional -> Accuracy: 0.4407, MCC: 0.2080, F1: 0.1951

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.66090 | val 0.70952
  Epoch 011 - train 0.66701 | val 0.71460
  Classification -> best τ=0.575 (val F1=0.0392)
  Directional -> Accuracy: 0.4737, MCC: -0.0087, F1: 0.4737

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.66298 | val 0.67835
  Epoch 020 - train 0.65287 | val 0.67890
  Epoch 021 - train 0.64950 | val 0.68007
  Classification -> best τ=0.400 (val F1=0.2778)
  Directional -> Accuracy: 0.4923, MCC: 0.0483, F1: 0.4407

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.66687 | val 0.67509
  Epoch 020 - train 0.65791 | val 0.66718
  Epoch 030 - train 0.63029 | val 0.66150
  Classification -> best τ=0.410 (val F1=0.2982)
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.67384 | val 0.69480
  Epoch 014 - train 0.67376 | val 0.69975
  Classification -> best τ=0.480 (val F1=0.1521)
  Directional -> Accuracy: 0.6458, MCC: 0.2711, F1: 0.7018

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.69188 | val 0.68931
  Epoch 016 - train 0.66675 | val 0.69447
  Classification -> best τ=0.480 (val F1=0.2648)
  Directional -> Accuracy: 0.5303, MCC: 0.1768, F1: 0.1143

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.67117 | val 0.68535
  Epoch 020 - train 0.65558 | val 0.68827
  Epoch 022 - train 0.65858 | val 0.68988
  Classification -> best τ=0.630 (val F1=0.2914)
  Directional -> Accuracy: 0.5517, MCC: 0.2174, F1: 0.4348

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.65972 | val 0.68643
  Epoch 020 - train 0.65100 | val 0.68485
  Epoch 030 - train 0.62182 | val 0.68310
  Classification -> best τ=0.420 (val F1=0.2617)
  Directional -> Accuracy: 0.5455, MCC: 0.1765, F1: 0.6512

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.67100 | val 0.68413
  Epoch 020 - train 0.65000 | val 0.67355
  Epoch 030 - train 0.63265 | val 0.67153
  Classification -> best τ=0.455 (val F1=0.2823)
  Directional -> Accuracy: 0.5179, MCC: 0.0797, F1: 0.4490

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.66933 | val 0.69826
  Epoch 011 - train 0.66896 | val 0.69885
  Classification -> best τ=0.500 (val F1=0.0825)
  Directional -> Accuracy: 0.4348, MCC: -0.1154, F1: 0.4348

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.66338 | val 0.68711
  Epoch 020 - train 0.63419 | val 0.69189
  Epoch 022 - train 0.64049 | val 0.69294
  Classification -> best τ=0.540 (val F1=0.2057)
  Directional -> Accuracy: 0.4884, MCC: 0.2324, F1: 0.2143

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.65828 | val 0.71578
  Epoch 011 - train 0.65859 | val 0.71810
  Classification -> best τ=0.535 (val F1=0.0375)
  Directional -> Accuracy: 0.4912, MCC: 0.2083, F1: 0.1714

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.69472 | val 0.69900
  Epoch 020 - train 0.67122 | val 0.69717
  Epoch 028 - train 0.64827 | val 0.69747
  Classification -> best τ=0.465 (val F1=0.3069)
  Directional -> Accuracy: 0.4878, MCC: -0.1080, F1: 0.6316

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.68297 | val 0.69494
  Epoch 013 - train 0.68127 | val 0.69946
  Classification -> best τ=0.495 (val F1=0.1869)
  Directional -> Accuracy: 0.5116, MCC: 0.0074, F1: 0.1600

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.68141 | val 0.69256
  Epoch 011 - train 0.66931 | val 0.69395
  Classification -> best τ=0.495 (val F1=0.2324)
  Directional -> Accuracy: 0.5116, MCC: -0.0213, F1: 0.6316

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.66731 | val 0.70417
  Epoch 011 - train 0.66451 | val 0.70599
  Classification -> best τ=0.520 (val F1=0.0122)
  Directional -> Accuracy: 0.4600, MCC: -0.0237, F1: 0.1290

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.66095 | val 0.66381
  Epoch 020 - train 0.63673 | val 0.65782
  Epoch 025 - train 0.64465 | val 0.65738
  Classification -> best τ=0.350 (val F1=0.3721)
  Directional -> Accuracy: 0.5479, MCC: 0.1207, F1: 0.5352

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.67194 | val 0.69305
  Epoch 020 - train 0.65053 | val 0.69341
  Epoch 026 - train 0.65941 | val 0.69364
  Classification -> best τ=0.435 (val F1=0.3162)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.66435 | val 0.72254
  Epoch 011 - train 0.65274 | val 0.72730
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.66881 | val 0.70228
  Epoch 014 - train 0.64918 | val 0.71370
  Classification -> best τ=0.400 (val F1=0.3166)
  Directional -> Accuracy: 0.5522, MCC: 0.1116, F1: 0.5714

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.67060 | val 0.69544
  Epoch 020 - train 0.65239 | val 0.68681
  Epoch 030 - train 0.61836 | val 0.68245
  Classification -> best τ=0.595 (val F1=0.4260)
  Directional -> Accuracy: 0.6744, MCC: 0.3575, F1: 0.6500

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.66051 | val 0.70940
  Epoch 011 - train 0.64988 | val 0.71199
  Classification -> best τ=0.515 (val F1=0.0377)
  Directional -> Accuracy: 0.4912, MCC: 0.1268, F1: 0.6506

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.65807 | val 0.68276
  Epoch 013 - train 0.63839 | val 0.69184
  Classification -> best τ=0.445 (val F1=0.1661)
  Directional -> Accuracy: 0.6170, MCC: 0.0000, F1: 0.7632

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.69402 | val 0.68849
  Epoch 011 - train 0.66800 | val 0.68923
  Classification -> best τ=0.485 (val F1=0.2417)
  Directional -> Accuracy: 0.5918, MCC: 0.0583, F1: 0.3333

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.65350 | val 0.71858
  Epoch 011 - train 0.65583 | val 0.72167
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.66235 | val 0.68089
  Epoch 020 - train 0.64042 | val 0.69120
  Classification -> best τ=0.415 (val F1=0.2125)
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.67757 | val 0.70281
  Epoch 011 - train 0.67147 | val 0.70366
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.66316 | val 0.68917
  Epoch 020 - train 0.64389 | val 0.68457
  Epoch 030 - train 0.61777 | val 0.68837
  Classification -> best τ=0.600 (val F1=0.2749)
  Directional -> Accuracy: 0.4318, MCC: -0.0300, F1: 0.0741

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.66276 | val 0.71494
  Epoch 011 - train 0.66340 | val 0.71887
  Classification -> best τ=0.500 (val F1=0.1313)
  Directional -> Accuracy: 0.4286, MCC: 0.0116, F1: 0.5333

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.68956 | val 0.67498
  Epoch 020 - train 0.66012 | val 0.67514
  Epoch 026 - train 0.65519 | val 0.67721
  Classification -> best τ=0.620 (val F1=0.2519)
  Directional -> Accuracy: 0.4821, MCC: 0.1255, F1: 0.0645

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.67628 | val 0.66691
  Epoch 020 - train 0.66923 | val 0.65792
  Epoch 029 - train 0.63399 | val 0.66597
  Classification -> best τ=0.470 (val F1=0.4387)
  Directional -> Accuracy: 0.4912, MCC: 0.0000, F1: 0.5538

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.66865 | val 0.69755
  Epoch 018 - train 0.66838 | val 0.71256
  Classification -> best τ=0.490 (val F1=0.1783)
  Directional -> Accuracy: 0.5741, MCC: 0.1657, F1: 0.6849

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.67558 | val 0.73319
  Epoch 011 - train 0.66276 | val 0.73785
  Classification -> best τ=0.515 (val F1=0.1091)
  Directional -> Accuracy: 0.5179, MCC: 0.0519, F1: 0.4255

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.67026 | val 0.67929

[I 2026-02-22 11:23:28,188] Trial 137 finished with value: 0.20009348424183163 and parameters: {'feature_set': 'sector_all_nlp', 'model_type': 'BiGRU', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.30000000000000004, 'batch_size': 64, 'learning_rate': 8.142353450890878e-05, 'weight_decay': 1.775055680427586e-05, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 0.7401430792759907, 'early_stopping_min_delta': 3.19506539659003e-05}. Best is trial 112 with value: 0.2833506688525635.

  Epoch 018 - train 0.66190 | val 0.69385
  Classification -> best τ=0.475 (val F1=0.3632)
  Directional -> Accuracy: 0.3934, MCC: -0.3139, F1: 0.5647

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.20009348424183163
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sentiment']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.70088 | val 0.69870
  Epoch 020 - train 0.68764 | val 0.69736
  Epoch 026 - train 0.68599 | val 0.69649
  Classification -> best τ=0.440 (val F1=0.0933)
  Directional -> Accuracy: 0.4474, MCC: 0.0000, F1: 0.6182

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.71583 | val 0.69345
  Epoch 020 - train 0.72833 | val 0.69084
  Epoch 024 - train 0.71973 | val 0.69078
  Classification -> best τ=0.440 (val F1=0.1857)
  Directional -> Accuracy: 0.5556, MCC: 0.0763, F1: 0.6296

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.70243 | val 0.69717
  Epoch 011 - train 0.69239 | val 0.69745
  Classification -> best τ=0.545 (val F1=0.1039)
  Directional -> Accuracy: 0.4565, MCC: -0.2529, F1: 0.6269

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.71678 | val 0.70540
  Epoch 011 - train 0.71500 | val 0.70679
  Classification -> best τ=0.550 (val F1=0.1269)
  Directional -> Accuracy: 0.5405, MCC: 0.0000, F1: 0.7018

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.70394 | val 0.69760
  Epoch 011 - train 0.70252 | val 0.69885
  Classification -> best τ=0.525 (val F1=0.1884)
  Directional -> Accuracy: 0.5600, MCC: 0.2009, F1: 0.3529

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.69201 | val 0.69747
  Epoch 011 - train 0.70323 | val 0.69801
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4783, MCC: 0.0000, F1: 0.6471

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.69622 | val 0.71545
  Epoch 011 - train 0.70293 | val 0.71742
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.3971, MCC: 0.0000, F1: 0.5684

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.71210 | val 0.68984
  Epoch 017 - train 0.69652 | val 0.69227
  Classification -> best τ=0.520 (val F1=0.3421)
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.68935 | val 0.69894
  Epoch 011 - train 0.68333 | val 0.69914
  Classification -> best τ=0.505 (val F1=0.1715)
  Directional -> Accuracy: 0.5833, MCC: 0.2810, F1: 0.6552

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.70282 | val 0.72550
  Epoch 011 - train 0.71009 | val 0.72901
  Classification -> best τ=0.515 (val F1=0.0022)
  Directional -> Accuracy: 0.5797, MCC: 0.0000, F1: 0.0000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.71283 | val 0.68826
  Epoch 017 - train 0.70383 | val 0.68989
  Classification -> best τ=0.520 (val F1=0.1738)
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.69925 | val 0.69918
  Epoch 011 - train 0.69617 | val 0.70073
  Classification -> best τ=0.525 (val F1=0.1044)
  Directional -> Accuracy: 0.4561, MCC: -0.1422, F1: 0.0606

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.68874 | val 0.67349
  Epoch 018 - train 0.69973 | val 0.67455
  Classification -> best τ=0.600 (val F1=0.2176)
  Directional -> Accuracy: 0.5476, MCC: 0.0000, F1: 0.0000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.68653 | val 0.67630
  Epoch 020 - train 0.69218 | val 0.67637
  Epoch 022 - train 0.68894 | val 0.67581
  Classification -> best τ=0.415 (val F1=0.1683)
  Directional -> Accuracy: 0.5167, MCC: 0.0519, F1: 0.6506

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.70489 | val 0.70429
  Epoch 011 - train 0.70792 | val 0.70580
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4510, MCC: 0.0000, F1: 0.6216

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.69696 | val 0.70088
  Epoch 011 - train 0.70975 | val 0.70160
  Classification -> best τ=0.480 (val F1=0.1203)
  Directional -> Accuracy: 0.5362, MCC: 0.0000, F1: 0.6981

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.69027 | val 0.74959
  Epoch 011 - train 0.68141 | val 0.75796
  Classification -> best τ=0.440 (val F1=0.0140)
  Directional -> Accuracy: 0.6897, MCC: 0.3056, F1: 0.7907

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.71158 | val 0.72262
  Epoch 011 - train 0.71062 | val 0.72500
  Classification -> best τ=0.470 (val F1=0.1006)
  Directional -> Accuracy: 0.6000, MCC: 0.1147, F1: 0.7059

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.72264 | val 0.71479
  Epoch 011 - train 0.70723 | val 0.71472
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5781, MCC: 0.0000, F1: 0.7327

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.69440 | val 0.67857
  Epoch 016 - train 0.69920 | val 0.68056
  Classification -> best τ=0.510 (val F1=0.2639)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.69933 | val 0.69577
  Epoch 011 - train 0.71538 | val 0.69642
  Classification -> best τ=0.525 (val F1=0.0135)
  Directional -> Accuracy: 0.6170, MCC: 0.0000, F1: 0.7632

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.70211 | val 0.70662
  Epoch 011 - train 0.69808 | val 0.70698
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5077, MCC: 0.0000, F1: 0.6735

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.70830 | val 0.70307
  Epoch 011 - train 0.70148 | val 0.70282
  Classification -> best τ=0.490 (val F1=0.1409)
  Directional -> Accuracy: 0.6140, MCC: 0.2667, F1: 0.7442

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.70877 | val 0.71148
  Epoch 011 - train 0.70879 | val 0.70999
  Classification -> best τ=0.535 (val F1=0.1985)
  Directional -> Accuracy: 0.5231, MCC: 0.0000, F1: 0.0000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.70372 | val 0.68975
  Epoch 020 - train 0.70273 | val 0.68804
  Epoch 027 - train 0.69942 | val 0.68710
  Classification -> best τ=0.500 (val F1=0.2399)
  Directional -> Accuracy: 0.4545, MCC: -0.2064, F1: 0.6053

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.67918 | val 0.69844
  Epoch 011 - train 0.66555 | val 0.69973
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.5938

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.73384 | val 0.77465
  Epoch 011 - train 0.73893 | val 0.78235
  Classification -> best τ=0.425 (val F1=0.2582)
  Directional -> Accuracy: 0.5952, MCC: 0.1803, F1: 0.7385

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.69709 | val 0.67585
  Epoch 020 - train 0.69016 | val 0.67337
  Epoch 025 - train 0.70065 | val 0.67307
  Classification -> best τ=0.460 (val F1=0.2622)
  Directional -> Accuracy: 0.5714, MCC: 0.1476, F1: 0.5862

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.69110 | val 0.69933
  Epoch 011 - train 0.68755 | val 0.69926
  Classification -> best τ=0.470 (val F1=0.1943)
  Directional -> Accuracy: 0.4250, MCC: -0.1985, F1: 0.5306

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.71178 | val 0.69415
  Epoch 011 - train 0.69431 | val 0.69461
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4762, MCC: 0.0000, F1: 0.6452

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.70129 | val 0.66612
  Epoch 020 - train 0.70706 | val 0.66525
  Epoch 026 - train 0.70425 | val 0.66436
  Classification -> best τ=0.630 (val F1=0.1286)
  Directional -> Accuracy: 0.4048, MCC: -0.1664, F1: 0.2857

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.69931 | val 0.69795
  Epoch 011 - train 0.69609 | val 0.69931
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.69277 | val 0.67847
  Epoch 020 - train 0.69771 | val 0.67651
  Epoch 028 - train 0.70491 | val 0.67604
  Classification -> best τ=0.425 (val F1=0.3823)
  Directional -> Accuracy: 0.6111, MCC: 0.2651, F1: 0.5758

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.71020 | val 0.70643
  Epoch 013 - train 0.69024 | val 0.71342
  Classification -> best τ=0.545 (val F1=0.2587)
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.71159 | val 0.69701
  Epoch 011 - train 0.71036 | val 0.69774
  Classification -> best τ=0.480 (val F1=0.2674)
  Directional -> Accuracy: 0.5000, MCC: -0.0487, F1: 0.5926

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.67367 | val 0.69663
  Epoch 011 - train 0.69254 | val 0.69692
  Classification -> best τ=0.465 (val F1=0.0077)
  Directional -> Accuracy: 0.5000, MCC: 0.0793, F1: 0.1600

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.70224 | val 0.69035
  Epoch 011 - train 0.70578 | val 0.69084
  Classification -> best τ=0.470 (val F1=0.0545)
  Directional -> Accuracy: 0.4643, MCC: 0.0000, F1: 0.6341

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.71751 | val 0.70015
  Epoch 011 - train 0.70129 | val 0.70117
  Classification -> best τ=0.510 (val F1=0.2832)
  Directional -> Accuracy: 0.5652, MCC: 0.0094, F1: 0.6875

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.72491 | val 0.73767
  Epoch 011 - train 0.71131 | val 0.73939
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.69811 | val 0.69765
  Epoch 011 - train 0.70693 | val 0.69851
  Classification -> best τ=0.500 (val F1=0.1828)
  Directional -> Accuracy: 0.3919, MCC: -0.2529, F1: 0.2105

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.74524 | val 0.70306
  Epoch 011 - train 0.72830 | val 0.70406
  Classification -> best τ=0.490 (val F1=0.1383)
  Directional -> Accuracy: 0.4000, MCC: -0.3194, F1: 0.0000

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.70782 | val 0.70081
  Epoch 011 - train 0.68942 | val 0.70084
  Classification -> best τ=0.505 (val F1=0.0658)
  Directional -> Accuracy: 0.4524, MCC: -0.1105, F1: 0.5106

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.69625 | val 0.68087
  Epoch 011 - train 0.69131 | val 0.68044
  Classification -> best τ=0.520 (val F1=0.1202)
  Directional -> Accuracy: 0.3958, MCC: -0.0457, F1: 0.5085

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.68522 | val 0.72672
  Epoch 011 - train 0.70494 | val 0.72807
  Classification -> best τ=0.465 (val F1=0.1784)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.68629 | val 0.68345
  Epoch 020 - train 0.69314 | val 0.68213
  Epoch 023 - train 0.68343 | val 0.68211
  Classification -> best τ=0.485 (val F1=0.2514)
  Directional -> Accuracy: 0.5536, MCC: 0.1555, F1: 0.6479

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.72973 | val 0.70717
  Epoch 011 - train 0.72457 | val 0.70780
  Classification -> best τ=0.440 (val F1=0.1251)
  Directional -> Accuracy: 0.5094, MCC: 0.0000, F1: 0.6750

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.69640 | val 0.72306
  Epoch 011 - train 0.70274 | val 0.72621
  Classification -> best τ=0.505 (val F1=0.1780)
  Directional -> Accuracy: 0.5455, MCC: 0.1437, F1: 0.6988

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...

[I 2026-02-22 11:24:22,066] Trial 138 finished with value: 0.13452531878025076 and parameters: {'feature_set': 'sentinment', 'model_type': 'BiGRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 32, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.2, 'batch_size': 64, 'learning_rate': 3.867228584843088e-06, 'weight_decay': 8.798336120584209e-05, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 0.9760425301067117, 'early_stopping_min_delta': 0.0011788371882122074}. Best is trial 112 with value: 0.2833506688525635.

  Epoch 010 - train 0.69389 | val 0.69336
  Epoch 011 - train 0.69965 | val 0.69396
  Classification -> best τ=0.475 (val F1=0.1504)
  Directional -> Accuracy: 0.5833, MCC: 0.2093, F1: 0.3243

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.13452531878025076
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d', 'emotion_anger', 'emotion_disgust', 'emotion_fear', 'emotion_joy', 'emotion_neutral', 'emotion_sadness', 'emotion_surprize', 'emotion_anger_pct', 'emotion_disgust_pct', 'emotion_fear_pct', 'emotion_joy_pct', 'emotion_neutral_pct', 'emotion_sadness_pct', 'emotion_surprize_pct']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.46036 | val 0.92821
  Epoch 018 - train 0.27681 | val 1.12238
  Classification -> best τ=0.485 (val F1=0.2200)
  Directional -> Accuracy: 0.5789, MCC: 0.1534, F1: 0.5429

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.32836 | val 0.91110
  Epoch 018 - train 0.21511 | val 1.44331
  Classification -> best τ=0.350 (val F1=0.1289)
  Directional -> Accuracy: 0.5778, MCC: 0.0000, F1: 0.7324

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.34209 | val 1.53400
  Epoch 017 - train 0.24841 | val 2.80965
  Classification -> best τ=0.570 (val F1=0.1854)
  Directional -> Accuracy: 0.4783, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.55417 | val 0.78093
  Epoch 017 - train 0.34435 | val 1.85048
  Classification -> best τ=0.535 (val F1=0.2027)
  Directional -> Accuracy: 0.4459, MCC: -0.1593, F1: 0.5591

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.31093 | val 1.31138
  Epoch 018 - train 0.19873 | val 1.79958
  Classification -> best τ=0.420 (val F1=0.3984)
  Directional -> Accuracy: 0.6600, MCC: 0.3309, F1: 0.6383

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.34135 | val 0.98699
  Epoch 020 - train 0.19986 | val 0.92056
  Epoch 026 - train 0.10000 | val 1.75957
  Classification -> best τ=0.535 (val F1=0.4299)
  Directional -> Accuracy: 0.4783, MCC: -0.2041, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.46586 | val 1.57010
  Epoch 016 - train 0.22892 | val 2.47251
  Classification -> best τ=0.475 (val F1=0.2220)
  Directional -> Accuracy: 0.5588, MCC: 0.1671, F1: 0.5588

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.32129 | val 0.51648
  Epoch 020 - train 0.16658 | val 1.98538
  Epoch 023 - train 0.12742 | val 1.43631
  Classification -> best τ=0.305 (val F1=0.6571)
  Directional -> Accuracy: 0.3810, MCC: -0.2041, F1: 0.4348

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.37052 | val 1.13353
  Epoch 020 - train 0.12106 | val 2.59485
  Epoch 021 - train 0.11733 | val 2.32412
  Classification -> best τ=0.530 (val F1=0.3523)
  Directional -> Accuracy: 0.4792, MCC: 0.0115, F1: 0.5455

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.37640 | val 0.85482
  Epoch 016 - train 0.26635 | val 0.97096
  Classification -> best τ=0.480 (val F1=0.1304)
  Directional -> Accuracy: 0.4203, MCC: 0.0000, F1: 0.5918

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.37258 | val 1.55653
  Epoch 017 - train 0.20716 | val 2.04543
  Classification -> best τ=0.495 (val F1=0.1738)
  Directional -> Accuracy: 0.5918, MCC: 0.2285, F1: 0.1667

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.42320 | val 1.16912
  Epoch 017 - train 0.26036 | val 2.92145
  Classification -> best τ=0.685 (val F1=0.1181)
  Directional -> Accuracy: 0.4912, MCC: 0.0000, F1: 0.0000

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.35291 | val 1.83078
  Epoch 016 - train 0.22423 | val 2.33122
  Classification -> best τ=0.415 (val F1=0.1733)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.6230

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.39690 | val 0.94491
  Epoch 017 - train 0.25481 | val 1.29043
  Classification -> best τ=0.445 (val F1=0.3774)
  Directional -> Accuracy: 0.4833, MCC: -0.1302, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.37731 | val 1.01474
  Epoch 018 - train 0.19900 | val 1.46520
  Classification -> best τ=0.520 (val F1=0.2320)
  Directional -> Accuracy: 0.5294, MCC: 0.1160, F1: 0.6000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.43743 | val 1.23888
  Epoch 017 - train 0.20645 | val 2.10635
  Classification -> best τ=0.380 (val F1=0.2795)
  Directional -> Accuracy: 0.5217, MCC: -0.0081, F1: 0.6526

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.39442 | val 0.85035
  Epoch 016 - train 0.29675 | val 1.09563
  Classification -> best τ=0.525 (val F1=0.2581)
  Directional -> Accuracy: 0.4138, MCC: 0.0725, F1: 0.1500

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.46080 | val 1.28269
  Epoch 016 - train 0.29439 | val 1.37583
  Classification -> best τ=0.515 (val F1=0.1548)
  Directional -> Accuracy: 0.4133, MCC: 0.0278, F1: 0.0833

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.45808 | val 1.56486
  Epoch 017 - train 0.20739 | val 2.17854
  Classification -> best τ=0.365 (val F1=0.2843)
  Directional -> Accuracy: 0.5625, MCC: 0.1420, F1: 0.5758

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.49942 | val 0.87932
  Epoch 019 - train 0.26951 | val 1.15324
  Classification -> best τ=0.410 (val F1=0.4047)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.34795 | val 2.13912
  Epoch 017 - train 0.22294 | val 2.51469
  Classification -> best τ=0.450 (val F1=0.1810)
  Directional -> Accuracy: 0.5745, MCC: -0.0834, F1: 0.7222

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.46097 | val 1.52240
  Epoch 017 - train 0.27332 | val 1.87075
  Classification -> best τ=0.535 (val F1=0.2830)
  Directional -> Accuracy: 0.4923, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.46899 | val 0.76063
  Epoch 020 - train 0.17591 | val 1.47739
  Epoch 022 - train 0.12752 | val 1.64912
  Classification -> best τ=0.570 (val F1=0.3191)
  Directional -> Accuracy: 0.6491, MCC: 0.2739, F1: 0.7222

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.49092 | val 0.85788
  Epoch 017 - train 0.28706 | val 1.27642
  Classification -> best τ=0.475 (val F1=0.1985)
  Directional -> Accuracy: 0.5538, MCC: 0.1006, F1: 0.4912

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.41532 | val 1.55680
  Epoch 019 - train 0.16822 | val 3.11075
  Classification -> best τ=0.520 (val F1=0.4260)
  Directional -> Accuracy: 0.5091, MCC: 0.0671, F1: 0.4000

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.25388 | val 1.12324
  Epoch 016 - train 0.12189 | val 2.10591
  Classification -> best τ=0.445 (val F1=0.2035)
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.5938

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.43702 | val 0.69126
  Epoch 018 - train 0.24049 | val 1.02475
  Classification -> best τ=0.610 (val F1=0.3184)
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.0000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.40156 | val 1.28493
  Epoch 017 - train 0.27221 | val 1.72913
  Classification -> best τ=0.365 (val F1=0.1986)
  Directional -> Accuracy: 0.5179, MCC: 0.0696, F1: 0.4706

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.38315 | val 0.70546
  Epoch 020 - train 0.15581 | val 2.18123
  Classification -> best τ=0.420 (val F1=0.3296)
  Directional -> Accuracy: 0.5750, MCC: 0.1240, F1: 0.7119

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.38507 | val 1.87229
  Epoch 017 - train 0.17670 | val 3.50592
  Classification -> best τ=0.505 (val F1=0.3656)
  Directional -> Accuracy: 0.5476, MCC: 0.1137, F1: 0.5957

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.41354 | val 1.45046
  Epoch 018 - train 0.24606 | val 1.97015
  Classification -> best τ=0.535 (val F1=0.1286)
  Directional -> Accuracy: 0.5000, MCC: 0.0235, F1: 0.4615

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.34007 | val 1.78452
  Epoch 017 - train 0.22395 | val 2.60565
  Classification -> best τ=0.615 (val F1=0.3465)
  Directional -> Accuracy: 0.5510, MCC: 0.2266, F1: 0.3125

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.49032 | val 0.80702
  Epoch 020 - train 0.18061 | val 1.32170
  Classification -> best τ=0.605 (val F1=0.2618)
  Directional -> Accuracy: 0.4444, MCC: 0.0000, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.37197 | val 1.12833
  Epoch 016 - train 0.22793 | val 1.80445
  Classification -> best τ=0.460 (val F1=0.2465)
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.52874 | val 0.96390
  Epoch 016 - train 0.37353 | val 1.25882
  Classification -> best τ=0.505 (val F1=0.1490)
  Directional -> Accuracy: 0.4848, MCC: -0.0168, F1: 0.5000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.27378 | val 1.99143
  Epoch 018 - train 0.08899 | val 2.43175
  Classification -> best τ=0.440 (val F1=0.2658)
  Directional -> Accuracy: 0.4524, MCC: -0.1228, F1: 0.5490

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.36648 | val 1.44437
  Epoch 016 - train 0.25642 | val 2.74797
  Classification -> best τ=0.500 (val F1=0.2327)
  Directional -> Accuracy: 0.5893, MCC: 0.1949, F1: 0.6102

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.28839 | val 0.87177
  Epoch 019 - train 0.07813 | val 1.59668
  Classification -> best τ=0.475 (val F1=0.3225)
  Directional -> Accuracy: 0.4130, MCC: -0.0726, F1: 0.3077

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.41440 | val 0.69558
  Epoch 020 - train 0.10642 | val 1.11655
  Epoch 023 - train 0.10795 | val 1.29051
  Classification -> best τ=0.620 (val F1=0.3448)
  Directional -> Accuracy: 0.3542, MCC: -0.0919, F1: 0.4918

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.44085 | val 1.85833
  Epoch 017 - train 0.23027 | val 2.47377
  Classification -> best τ=0.400 (val F1=0.2456)
  Directional -> Accuracy: 0.4865, MCC: 0.0000, F1: 0.6545

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.38280 | val 0.89210
  Epoch 016 - train 0.28594 | val 1.09024
  Classification -> best τ=0.505 (val F1=0.3371)
  Directional -> Accuracy: 0.4667, MCC: -0.0632, F1: 0.4000

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.26482 | val 0.78593
  Epoch 018 - train 0.14448 | val 1.03931
  Classification -> best τ=0.345 (val F1=0.2408)
  Directional -> Accuracy: 0.5952, MCC: 0.1291, F1: 0.7119

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.32636 | val 0.60511
  Epoch 020 - train 0.10711 | val 1.05090
  Epoch 026 - train 0.06311 | val 1.21400
  Classification -> best τ=0.495 (val F1=0.4682)
  Directional -> Accuracy: 0.5000, MCC: 0.0436, F1: 0.4783

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.46892 | val 1.22253
  Epoch 017 - train 0.30911 | val 1.75066
  Classification -> best τ=0.430 (val F1=0.2448)
  Directional -> Accuracy: 0.5455, MCC: 0.0000, F1: 0.7059

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.40105 | val 1.09715
  Epoch 017 - train 0.16821 | val 1.99850
  Classification -> best τ=0.510 (val F1=0.3164)
  Directional -> Accuracy: 0.5179, MCC: 0.0333, F1: 0.4906

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.39025 | val 1.16119
  Epoch 018 - train 0.15375 | val 2.20072
  Classification -> best τ=0.700 (val F1=0.2064)
  Directional -> Accuracy: 0.5660, MCC: 0.1373, F1: 0.5306

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.35579 | val 1.39898
  Epoch 016 - train 0.22751 | val 1.75128
  Classification -> best τ=0.595 (val F1=0.1605)
  Directional -> Accuracy: 0.4727, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.45690 | val 0.77243
  Epoch 020 - train 0.15674 | val 1.35594

[I 2026-02-22 11:26:10,454] Trial 139 finished with value: 0.27156661033846835 and parameters: {'feature_set': 'sector_emotion', 'model_type': 'BiGRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.2, 'batch_size': 64, 'learning_rate': 0.0073743494744839145, 'weight_decay': 4.034853697522404e-05, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 15, 'max_epochs': 30, 'huber_delta': 0.8396475479569467, 'early_stopping_min_delta': 0.00029770570074271976}. Best is trial 112 with value: 0.2833506688525635.

  Epoch 023 - train 0.13857 | val 1.80486
  Classification -> best τ=0.660 (val F1=0.3108)
  Directional -> Accuracy: 0.5167, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.27156661033846835
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d', 'emotion_anger', 'emotion_disgust', 'emotion_fear', 'emotion_joy', 'emotion_neutral', 'emotion_sadness', 'emotion_surprize', 'emotion_anger_pct', 'emotion_disgust_pct', 'emotion_fear_pct', 'emotion_joy_pct', 'emotion_neutral_pct', 'emotion_sadness_pct', 'emotion_surprize_pct']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.49958 | val 0.82845
  Epoch 016 - train 0.28332 | val 0.94513
  Classification -> best τ=0.435 (val F1=0.0809)
  Directional -> Accuracy: 0.4474, MCC: -0.0458, F1: 0.5714

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.36370 | val 1.04418
  Epoch 017 - train 0.17757 | val 1.31157
  Classification -> best τ=0.505 (val F1=0.2073)
  Directional -> Accuracy: 0.5111, MCC: 0.0120, F1: 0.5600

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.37079 | val 1.79407
  Epoch 016 - train 0.17429 | val 2.99892
  Classification -> best τ=0.425 (val F1=0.2295)
  Directional -> Accuracy: 0.5217, MCC: 0.0000, F1: 0.6857

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.50243 | val 1.01750
  Epoch 017 - train 0.31451 | val 1.90800
  Classification -> best τ=0.515 (val F1=0.1627)
  Directional -> Accuracy: 0.4730, MCC: -0.0634, F1: 0.5185

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.31785 | val 1.10119
  Epoch 018 - train 0.14234 | val 1.84653
  Classification -> best τ=0.535 (val F1=0.2934)
  Directional -> Accuracy: 0.5600, MCC: 0.2009, F1: 0.3529

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.34961 | val 0.89888
  Epoch 020 - train 0.13190 | val 1.17447
  Epoch 021 - train 0.13680 | val 1.15816
  Classification -> best τ=0.330 (val F1=0.3301)
  Directional -> Accuracy: 0.4783, MCC: -0.0455, F1: 0.4545

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.45508 | val 1.77686
  Epoch 016 - train 0.30829 | val 2.14427
  Classification -> best τ=0.495 (val F1=0.3071)
  Directional -> Accuracy: 0.5735, MCC: 0.1629, F1: 0.5397

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.30288 | val 0.69699
  Epoch 020 - train 0.13856 | val 1.28694
  Epoch 024 - train 0.14276 | val 1.77943
  Classification -> best τ=0.255 (val F1=0.3590)
  Directional -> Accuracy: 0.4048, MCC: -0.1680, F1: 0.4186

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.33181 | val 1.43245
  Epoch 020 - train 0.12413 | val 2.35937
  Classification -> best τ=0.405 (val F1=0.4017)
  Directional -> Accuracy: 0.6250, MCC: 0.2574, F1: 0.6087

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.46578 | val 0.98376
  Epoch 017 - train 0.24478 | val 1.62643
  Classification -> best τ=0.465 (val F1=0.2293)
  Directional -> Accuracy: 0.4493, MCC: 0.0544, F1: 0.5870

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.49263 | val 1.59453
  Epoch 017 - train 0.27458 | val 2.63102
  Classification -> best τ=0.470 (val F1=0.2543)
  Directional -> Accuracy: 0.5714, MCC: 0.1599, F1: 0.0870

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.43462 | val 1.93154
  Epoch 017 - train 0.22655 | val 2.82410
  Classification -> best τ=0.485 (val F1=0.0424)
  Directional -> Accuracy: 0.5614, MCC: 0.2399, F1: 0.6988

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.30607 | val 1.55095
  Epoch 016 - train 0.23227 | val 2.20810
  Classification -> best τ=0.490 (val F1=0.1658)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.6230

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.42885 | val 0.90942
  Epoch 017 - train 0.23038 | val 1.44549
  Classification -> best τ=0.525 (val F1=0.4317)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.40210 | val 1.34281
  Epoch 017 - train 0.24213 | val 2.65765
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4510, MCC: 0.0000, F1: 0.6216

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.38347 | val 1.30951
  Epoch 017 - train 0.24679 | val 2.02324
  Classification -> best τ=0.470 (val F1=0.2161)
  Directional -> Accuracy: 0.5652, MCC: 0.1121, F1: 0.6429

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.42772 | val 1.38393
  Epoch 017 - train 0.26287 | val 2.16342
  Classification -> best τ=0.650 (val F1=0.2276)
  Directional -> Accuracy: 0.3276, MCC: -0.2988, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.44997 | val 1.07194
  Epoch 016 - train 0.33153 | val 1.47527
  Classification -> best τ=0.575 (val F1=0.2220)
  Directional -> Accuracy: 0.4000, MCC: -0.0485, F1: 0.0816

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.40616 | val 0.71049
  Epoch 020 - train 0.16021 | val 1.17264
  Classification -> best τ=0.280 (val F1=0.3893)
  Directional -> Accuracy: 0.5156, MCC: 0.0518, F1: 0.5231

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.53065 | val 0.79452
  Epoch 017 - train 0.30865 | val 1.19433
  Classification -> best τ=0.465 (val F1=0.2700)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.39291 | val 1.47976
  Epoch 016 - train 0.25334 | val 2.29755
  Classification -> best τ=0.565 (val F1=0.1978)
  Directional -> Accuracy: 0.4468, MCC: 0.0220, F1: 0.3500

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.42776 | val 1.37902
  Epoch 017 - train 0.26707 | val 1.74553
  Classification -> best τ=0.575 (val F1=0.2766)
  Directional -> Accuracy: 0.4923, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.43832 | val 0.79897
  Epoch 020 - train 0.16918 | val 1.28401
  Epoch 022 - train 0.13364 | val 1.34462
  Classification -> best τ=0.410 (val F1=0.4704)
  Directional -> Accuracy: 0.6140, MCC: 0.2667, F1: 0.7442

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.44447 | val 0.85444
  Epoch 017 - train 0.25834 | val 0.97680
  Classification -> best τ=0.485 (val F1=0.2774)
  Directional -> Accuracy: 0.5385, MCC: 0.0880, F1: 0.5714

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.37174 | val 1.31040
  Epoch 019 - train 0.15497 | val 2.29292
  Classification -> best τ=0.440 (val F1=0.4207)
  Directional -> Accuracy: 0.5455, MCC: 0.1365, F1: 0.4681

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.27497 | val 0.71490
  Epoch 016 - train 0.14884 | val 1.24174
  Classification -> best τ=0.545 (val F1=0.2582)
  Directional -> Accuracy: 0.4444, MCC: -0.0225, F1: 0.5455

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.41892 | val 0.70109
  Epoch 020 - train 0.16177 | val 0.86228
  Classification -> best τ=0.590 (val F1=0.3717)
  Directional -> Accuracy: 0.5238, MCC: 0.1217, F1: 0.4444

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.39741 | val 1.31452
  Epoch 016 - train 0.28450 | val 1.78196
  Classification -> best τ=0.480 (val F1=0.2096)
  Directional -> Accuracy: 0.5000, MCC: -0.0823, F1: 0.6316

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.33034 | val 0.87324
  Epoch 020 - train 0.13778 | val 2.95578
  Classification -> best τ=0.525 (val F1=0.2957)
  Directional -> Accuracy: 0.4500, MCC: -0.1231, F1: 0.5217

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.38368 | val 1.34076
  Epoch 016 - train 0.28682 | val 2.49810
  Classification -> best τ=0.595 (val F1=0.2814)
  Directional -> Accuracy: 0.5714, MCC: 0.1779, F1: 0.2500

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.37504 | val 1.32838
  Epoch 016 - train 0.33520 | val 1.69217
  Classification -> best τ=0.490 (val F1=0.2298)
  Directional -> Accuracy: 0.4762, MCC: 0.0083, F1: 0.3125

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.39312 | val 2.30564
  Epoch 016 - train 0.27741 | val 3.83941
  Classification -> best τ=0.485 (val F1=0.2498)
  Directional -> Accuracy: 0.5102, MCC: -0.0469, F1: 0.6571

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.50662 | val 0.81592
  Epoch 019 - train 0.23166 | val 1.96108
  Classification -> best τ=0.330 (val F1=0.3252)
  Directional -> Accuracy: 0.5833, MCC: 0.1422, F1: 0.6512

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.33784 | val 1.10225
  Epoch 016 - train 0.23721 | val 1.45817
  Classification -> best τ=0.495 (val F1=0.4057)
  Directional -> Accuracy: 0.5349, MCC: 0.0733, F1: 0.2857

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.49838 | val 1.33224
  Epoch 016 - train 0.35126 | val 1.64322
  Classification -> best τ=0.465 (val F1=0.1715)
  Directional -> Accuracy: 0.5758, MCC: 0.0000, F1: 0.7308

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.35556 | val 1.34887
  Epoch 019 - train 0.06994 | val 2.41336
  Classification -> best τ=0.540 (val F1=0.3287)
  Directional -> Accuracy: 0.7143, MCC: 0.4404, F1: 0.7000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.40142 | val 1.61205
  Epoch 016 - train 0.20286 | val 2.45583
  Classification -> best τ=0.430 (val F1=0.2450)
  Directional -> Accuracy: 0.5714, MCC: 0.1708, F1: 0.6129

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.30803 | val 1.20104
  Epoch 018 - train 0.12490 | val 1.67223
  Classification -> best τ=0.400 (val F1=0.2157)
  Directional -> Accuracy: 0.5652, MCC: 0.0873, F1: 0.6429

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.39803 | val 0.68042
  Epoch 020 - train 0.08923 | val 1.46005
  Epoch 027 - train 0.06173 | val 1.98439
  Classification -> best τ=0.690 (val F1=0.3887)
  Directional -> Accuracy: 0.3542, MCC: -0.0636, F1: 0.5079

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.42174 | val 1.62908
  Epoch 016 - train 0.23007 | val 3.05305
  Classification -> best τ=0.465 (val F1=0.3293)
  Directional -> Accuracy: 0.4595, MCC: -0.1107, F1: 0.2593

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.40297 | val 0.78938
  Epoch 018 - train 0.23189 | val 1.39691
  Classification -> best τ=0.525 (val F1=0.3500)
  Directional -> Accuracy: 0.5111, MCC: 0.0314, F1: 0.4211

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.30275 | val 0.81146
  Epoch 018 - train 0.15923 | val 1.28718
  Classification -> best τ=0.535 (val F1=0.3151)
  Directional -> Accuracy: 0.4286, MCC: -0.1021, F1: 0.3684

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.28613 | val 0.62081
  Epoch 020 - train 0.09449 | val 1.23436
  Epoch 023 - train 0.05184 | val 1.07836
  Classification -> best τ=0.620 (val F1=0.4092)
  Directional -> Accuracy: 0.5625, MCC: 0.2137, F1: 0.5714

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.43028 | val 1.72920
  Epoch 017 - train 0.24913 | val 2.31784
  Classification -> best τ=0.650 (val F1=0.2374)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.30977 | val 1.25933
  Epoch 017 - train 0.14365 | val 1.92320
  Classification -> best τ=0.440 (val F1=0.2793)
  Directional -> Accuracy: 0.4464, MCC: -0.1700, F1: 0.1622

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.41261 | val 1.40840
  Epoch 017 - train 0.23778 | val 2.60319
  Classification -> best τ=0.545 (val F1=0.2486)
  Directional -> Accuracy: 0.5660, MCC: 0.1312, F1: 0.5818

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.41776 | val 1.52994
  Epoch 016 - train 0.26953 | val 2.24650
  Classification -> best τ=0.405 (val F1=0.2036)
  Directional -> Accuracy: 0.5273, MCC: 0.0000, F1: 0.6905

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.48815 | val 1.03718

[I 2026-02-22 11:27:58,851] Trial 140 finished with value: 0.2700222959525224 and parameters: {'feature_set': 'sector_emotion', 'model_type': 'BiGRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.2, 'batch_size': 64, 'learning_rate': 0.007299998679138638, 'weight_decay': 3.7762124508828285e-05, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 15, 'max_epochs': 30, 'huber_delta': 0.8363010178944338, 'early_stopping_min_delta': 0.0003395498957276833}. Best is trial 112 with value: 0.2833506688525635.

  Epoch 019 - train 0.27876 | val 1.98321
  Classification -> best τ=0.600 (val F1=0.1489)
  Directional -> Accuracy: 0.5333, MCC: 0.0842, F1: 0.1250

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2700222959525224
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d', 'emotion_anger', 'emotion_disgust', 'emotion_fear', 'emotion_joy', 'emotion_neutral', 'emotion_sadness', 'emotion_surprize', 'emotion_anger_pct', 'emotion_disgust_pct', 'emotion_fear_pct', 'emotion_joy_pct', 'emotion_neutral_pct', 'emotion_sadness_pct', 'emotion_surprize_pct']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.49855 | val 0.91252
  Epoch 019 - train 0.29072 | val 1.20873
  Classification -> best τ=0.640 (val F1=0.2036)
  Directional -> Accuracy: 0.6053, MCC: 0.1835, F1: 0.4231

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.33711 | val 0.85903
  Epoch 016 - train 0.26010 | val 1.07466
  Classification -> best τ=0.405 (val F1=0.1289)
  Directional -> Accuracy: 0.5556, MCC: 0.0372, F1: 0.6667

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.40788 | val 1.46507
  Epoch 016 - train 0.27794 | val 2.78475
  Classification -> best τ=0.515 (val F1=0.0019)
  Directional -> Accuracy: 0.4348, MCC: -0.1326, F1: 0.4583

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.47958 | val 1.97049
  Epoch 017 - train 0.28912 | val 2.77552
  Classification -> best τ=0.505 (val F1=0.1895)
  Directional -> Accuracy: 0.5270, MCC: 0.1771, F1: 0.2857

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.36366 | val 1.17434
  Epoch 016 - train 0.23682 | val 1.30560
  Classification -> best τ=0.485 (val F1=0.3280)
  Directional -> Accuracy: 0.6000, MCC: 0.2425, F1: 0.5000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.40648 | val 0.83466
  Epoch 019 - train 0.22050 | val 1.55589
  Classification -> best τ=0.575 (val F1=0.2739)
  Directional -> Accuracy: 0.5217, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.45489 | val 1.69003
  Epoch 017 - train 0.22970 | val 2.57454
  Classification -> best τ=0.430 (val F1=0.1651)
  Directional -> Accuracy: 0.5147, MCC: 0.1667, F1: 0.5823

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.31396 | val 1.00088
  Epoch 017 - train 0.20286 | val 2.87500
  Classification -> best τ=0.335 (val F1=0.3524)
  Directional -> Accuracy: 0.4762, MCC: 0.0786, F1: 0.5926

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.40561 | val 0.86033
  Epoch 020 - train 0.13278 | val 2.22327
  Epoch 021 - train 0.17162 | val 2.25997
  Classification -> best τ=0.655 (val F1=0.3433)
  Directional -> Accuracy: 0.5833, MCC: 0.1534, F1: 0.5238

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.43057 | val 0.86025
  Epoch 018 - train 0.19621 | val 1.38306
  Classification -> best τ=0.515 (val F1=0.1304)
  Directional -> Accuracy: 0.4348, MCC: -0.0495, F1: 0.5301

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.41060 | val 2.03550
  Epoch 017 - train 0.24883 | val 2.46708
  Classification -> best τ=0.530 (val F1=0.1155)
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.40376 | val 2.21468
  Epoch 017 - train 0.23814 | val 3.66624
  Classification -> best τ=0.530 (val F1=0.2434)
  Directional -> Accuracy: 0.5088, MCC: 0.0048, F1: 0.6585

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.37865 | val 1.06235
  Epoch 018 - train 0.22329 | val 1.77347
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.6230

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.43610 | val 1.01955
  Epoch 017 - train 0.25577 | val 1.30262
  Classification -> best τ=0.500 (val F1=0.3126)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.41582 | val 1.35954
  Epoch 017 - train 0.24255 | val 1.88597
  Classification -> best τ=0.550 (val F1=0.1556)
  Directional -> Accuracy: 0.5490, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.47155 | val 1.39256
  Epoch 016 - train 0.23740 | val 2.24357
  Classification -> best τ=0.385 (val F1=0.1240)
  Directional -> Accuracy: 0.5362, MCC: 0.0000, F1: 0.6981

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.44086 | val 0.90814
  Epoch 016 - train 0.20040 | val 1.20767
  Classification -> best τ=0.520 (val F1=0.0506)
  Directional -> Accuracy: 0.3793, MCC: -0.0995, F1: 0.1818

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.46521 | val 1.02478
  Epoch 016 - train 0.30160 | val 1.80649
  Classification -> best τ=0.430 (val F1=0.2004)
  Directional -> Accuracy: 0.4667, MCC: -0.0875, F1: 0.5349

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.43978 | val 1.41317
  Epoch 017 - train 0.20963 | val 1.53678
  Classification -> best τ=0.555 (val F1=0.2932)
  Directional -> Accuracy: 0.4219, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.48324 | val 0.88108
  Epoch 016 - train 0.29965 | val 1.22603
  Classification -> best τ=0.475 (val F1=0.2030)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.36891 | val 1.50399
  Epoch 016 - train 0.24627 | val 1.90259
  Classification -> best τ=0.600 (val F1=0.2449)
  Directional -> Accuracy: 0.3617, MCC: -0.1540, F1: 0.1176

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.47707 | val 1.32450
  Epoch 017 - train 0.24766 | val 1.27238
  Classification -> best τ=0.440 (val F1=0.1688)
  Directional -> Accuracy: 0.5385, MCC: 0.1275, F1: 0.2857

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.37090 | val 1.16100
  Epoch 020 - train 0.13768 | val 1.22628
  Classification -> best τ=0.380 (val F1=0.4564)
  Directional -> Accuracy: 0.5614, MCC: 0.0000, F1: 0.7191

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.50518 | val 0.82830
  Epoch 016 - train 0.29953 | val 0.96179
  Classification -> best τ=0.505 (val F1=0.1974)
  Directional -> Accuracy: 0.4769, MCC: 0.0000, F1: 0.6458

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.42269 | val 1.35427
  Epoch 019 - train 0.19879 | val 3.31690
  Classification -> best τ=0.510 (val F1=0.4260)
  Directional -> Accuracy: 0.5455, MCC: 0.1641, F1: 0.4186

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.28024 | val 1.65628
  Epoch 018 - train 0.06204 | val 2.72668
  Classification -> best τ=0.560 (val F1=0.3315)
  Directional -> Accuracy: 0.4667, MCC: -0.0230, F1: 0.5000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.39952 | val 0.77745
  Epoch 018 - train 0.19427 | val 1.58558
  Classification -> best τ=0.530 (val F1=0.1132)
  Directional -> Accuracy: 0.5714, MCC: 0.1021, F1: 0.6538

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.43907 | val 1.41126
  Epoch 016 - train 0.26370 | val 2.22731
  Classification -> best τ=0.510 (val F1=0.1832)
  Directional -> Accuracy: 0.4464, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.37057 | val 1.11430
  Epoch 017 - train 0.22215 | val 2.10101
  Classification -> best τ=0.485 (val F1=0.4382)
  Directional -> Accuracy: 0.5500, MCC: 0.0580, F1: 0.6538

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.45327 | val 1.71289
  Epoch 017 - train 0.25415 | val 2.40061
  Classification -> best τ=0.515 (val F1=0.3501)
  Directional -> Accuracy: 0.5238, MCC: 0.0413, F1: 0.4737

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.42337 | val 1.49812
  Epoch 017 - train 0.25448 | val 2.28403
  Classification -> best τ=0.585 (val F1=0.1286)
  Directional -> Accuracy: 0.4524, MCC: -0.0214, F1: 0.0800

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.39165 | val 2.37464
  Epoch 019 - train 0.21639 | val 2.83509
  Classification -> best τ=0.640 (val F1=0.3574)
  Directional -> Accuracy: 0.4898, MCC: -0.0704, F1: 0.6154

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.51595 | val 0.98208
  Epoch 017 - train 0.29197 | val 1.19902
  Classification -> best τ=0.420 (val F1=0.3366)
  Directional -> Accuracy: 0.5556, MCC: 0.0000, F1: 0.7143

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.38261 | val 1.38600
  Epoch 019 - train 0.18211 | val 2.52240
  Classification -> best τ=0.375 (val F1=0.3742)
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.49481 | val 0.94376
  Epoch 017 - train 0.29125 | val 1.62654
  Classification -> best τ=0.645 (val F1=0.2618)
  Directional -> Accuracy: 0.4242, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.35626 | val 1.49434
  Epoch 019 - train 0.11194 | val 2.20367
  Classification -> best τ=0.480 (val F1=0.3287)
  Directional -> Accuracy: 0.6667, MCC: 0.3318, F1: 0.6818

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.37984 | val 2.22875
  Epoch 016 - train 0.23878 | val 2.68370
  Classification -> best τ=0.570 (val F1=0.2850)
  Directional -> Accuracy: 0.6607, MCC: 0.3263, F1: 0.5366

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.33613 | val 1.09196
  Epoch 018 - train 0.12864 | val 1.85223
  Classification -> best τ=0.350 (val F1=0.1709)
  Directional -> Accuracy: 0.6087, MCC: 0.0000, F1: 0.7568

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.39871 | val 0.65280
  Epoch 020 - train 0.10584 | val 1.10296
  Epoch 022 - train 0.07927 | val 1.19327
  Classification -> best τ=0.655 (val F1=0.4306)
  Directional -> Accuracy: 0.3333, MCC: -0.1970, F1: 0.5000

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.45800 | val 1.80886
  Epoch 016 - train 0.28884 | val 2.92093
  Classification -> best τ=0.350 (val F1=0.2542)
  Directional -> Accuracy: 0.4324, MCC: -0.1326, F1: 0.4878

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.44824 | val 0.78854
  Epoch 016 - train 0.30810 | val 1.31557
  Classification -> best τ=0.440 (val F1=0.4490)
  Directional -> Accuracy: 0.6222, MCC: 0.2466, F1: 0.6667

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.27202 | val 0.86772
  Epoch 016 - train 0.12233 | val 1.22236
  Classification -> best τ=0.525 (val F1=0.3151)
  Directional -> Accuracy: 0.5000, MCC: 0.1291, F1: 0.3226

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.35336 | val 0.68739
  Epoch 019 - train 0.08332 | val 1.03550
  Classification -> best τ=0.640 (val F1=0.5261)
  Directional -> Accuracy: 0.6250, MCC: 0.3333, F1: 0.6250

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.40700 | val 1.00310
  Epoch 016 - train 0.27243 | val 1.48622
  Classification -> best τ=0.580 (val F1=0.2036)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.33329 | val 1.24530
  Epoch 017 - train 0.15639 | val 2.49804
  Classification -> best τ=0.495 (val F1=0.3428)
  Directional -> Accuracy: 0.5357, MCC: 0.0646, F1: 0.4583

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.39878 | val 1.84616
  Epoch 017 - train 0.14985 | val 2.90942
  Classification -> best τ=0.595 (val F1=0.1770)
  Directional -> Accuracy: 0.4906, MCC: -0.0080, F1: 0.2286

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.44111 | val 1.03056
  Epoch 018 - train 0.22895 | val 2.03693
  Classification -> best τ=0.390 (val F1=0.2967)
  Directional -> Accuracy: 0.5091, MCC: -0.1289, F1: 0.6747

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.52036 | val 0.82238

[I 2026-02-22 11:29:48,027] Trial 141 finished with value: 0.2556038401665231 and parameters: {'feature_set': 'sector_emotion', 'model_type': 'BiGRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.2, 'batch_size': 64, 'learning_rate': 0.008430530813281012, 'weight_decay': 5.189333372085968e-05, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 15, 'max_epochs': 30, 'huber_delta': 0.7637538540190765, 'early_stopping_min_delta': 0.0006215099487367412}. Best is trial 112 with value: 0.2833506688525635.

  Epoch 017 - train 0.22930 | val 1.14227
  Classification -> best τ=0.480 (val F1=0.3056)
  Directional -> Accuracy: 0.5833, MCC: 0.1727, F1: 0.6032

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2556038401665231
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d', 'emotion_anger', 'emotion_disgust', 'emotion_fear', 'emotion_joy', 'emotion_neutral', 'emotion_sadness', 'emotion_surprize', 'emotion_anger_pct', 'emotion_disgust_pct', 'emotion_fear_pct', 'emotion_joy_pct', 'emotion_neutral_pct', 'emotion_sadness_pct', 'emotion_surprize_pct']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.44676 | val 0.87222
  Epoch 018 - train 0.29771 | val 1.35497
  Classification -> best τ=0.520 (val F1=0.2919)
  Directional -> Accuracy: 0.5395, MCC: 0.0660, F1: 0.4776

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.34308 | val 0.83654
  Epoch 016 - train 0.25265 | val 1.37322
  Classification -> best τ=0.405 (val F1=0.1323)
  Directional -> Accuracy: 0.5778, MCC: 0.0000, F1: 0.7324

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.38827 | val 1.53713
  Epoch 016 - train 0.26066 | val 2.67670
  Classification -> best τ=0.535 (val F1=0.1978)
  Directional -> Accuracy: 0.4783, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.48003 | val 1.36839
  Epoch 017 - train 0.34443 | val 1.79748
  Classification -> best τ=0.525 (val F1=0.2419)
  Directional -> Accuracy: 0.4865, MCC: -0.0163, F1: 0.4722

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.40134 | val 1.01065
  Epoch 018 - train 0.21711 | val 1.33799
  Classification -> best τ=0.525 (val F1=0.2976)
  Directional -> Accuracy: 0.5800, MCC: 0.2044, F1: 0.4615

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.41076 | val 0.66679
  Epoch 020 - train 0.14182 | val 1.20273
  Epoch 024 - train 0.11793 | val 1.36652
  Classification -> best τ=0.355 (val F1=0.4379)
  Directional -> Accuracy: 0.5217, MCC: 0.0318, F1: 0.4211

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.42660 | val 1.47092
  Epoch 017 - train 0.26730 | val 1.98092
  Classification -> best τ=0.405 (val F1=0.3104)
  Directional -> Accuracy: 0.4853, MCC: 0.0621, F1: 0.5333

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.35221 | val 1.06920
  Epoch 020 - train 0.17629 | val 2.50377
  Epoch 021 - train 0.11215 | val 2.50531
  Classification -> best τ=0.395 (val F1=0.2753)
  Directional -> Accuracy: 0.4048, MCC: -0.1334, F1: 0.5614

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.36359 | val 1.25771
  Epoch 017 - train 0.25592 | val 1.91190
  Classification -> best τ=0.525 (val F1=0.2927)
  Directional -> Accuracy: 0.6042, MCC: 0.1732, F1: 0.4571

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.43734 | val 0.85161
  Epoch 017 - train 0.25098 | val 1.24131
  Classification -> best τ=0.415 (val F1=0.2293)
  Directional -> Accuracy: 0.4058, MCC: -0.1061, F1: 0.5393

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.40620 | val 1.71043
  Epoch 017 - train 0.24296 | val 2.92235
  Classification -> best τ=0.530 (val F1=0.2543)
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.40845 | val 1.88337
  Epoch 017 - train 0.27736 | val 3.72762
  Classification -> best τ=0.625 (val F1=0.0919)
  Directional -> Accuracy: 0.4912, MCC: 0.0000, F1: 0.0000

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.32835 | val 1.64262
  Epoch 016 - train 0.23744 | val 1.50222
  Classification -> best τ=0.460 (val F1=0.0981)
  Directional -> Accuracy: 0.4286, MCC: -0.1718, F1: 0.6000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.44451 | val 0.91160
  Epoch 016 - train 0.28425 | val 1.35344
  Classification -> best τ=0.480 (val F1=0.4109)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.45906 | val 0.96003
  Epoch 016 - train 0.25492 | val 1.48794
  Classification -> best τ=0.460 (val F1=0.0356)
  Directional -> Accuracy: 0.5686, MCC: 0.1560, F1: 0.0833

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.43125 | val 1.26627
  Epoch 018 - train 0.27235 | val 1.82245
  Classification -> best τ=0.735 (val F1=0.2895)
  Directional -> Accuracy: 0.5362, MCC: 0.1508, F1: 0.3600

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.45848 | val 0.89561
  Epoch 019 - train 0.21523 | val 1.59876
  Classification -> best τ=0.635 (val F1=0.2651)
  Directional -> Accuracy: 0.3276, MCC: -0.2558, F1: 0.0930

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.48365 | val 0.99851
  Epoch 016 - train 0.33812 | val 1.50411
  Classification -> best τ=0.500 (val F1=0.2015)
  Directional -> Accuracy: 0.4133, MCC: -0.0462, F1: 0.2143

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.47744 | val 1.13232
  Epoch 018 - train 0.30121 | val 1.33317
  Classification -> best τ=0.640 (val F1=0.2600)
  Directional -> Accuracy: 0.4219, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.45891 | val 0.79918
  Epoch 018 - train 0.30206 | val 1.11863
  Classification -> best τ=0.445 (val F1=0.3164)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.35568 | val 0.94858
  Epoch 019 - train 0.16326 | val 1.18690
  Classification -> best τ=0.505 (val F1=0.3678)
  Directional -> Accuracy: 0.3830, MCC: -0.1090, F1: 0.2162

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.38283 | val 0.95379
  Epoch 016 - train 0.24429 | val 1.27955
  Classification -> best τ=0.480 (val F1=0.2753)
  Directional -> Accuracy: 0.4923, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.43940 | val 0.80865
  Epoch 019 - train 0.19047 | val 1.56741
  Classification -> best τ=0.675 (val F1=0.3749)
  Directional -> Accuracy: 0.5439, MCC: 0.1441, F1: 0.4800

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.46362 | val 0.91008
  Epoch 017 - train 0.30364 | val 0.98541
  Classification -> best τ=0.425 (val F1=0.2111)
  Directional -> Accuracy: 0.5385, MCC: 0.1510, F1: 0.6512

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.35616 | val 1.23960
  Epoch 019 - train 0.18099 | val 2.06033
  Classification -> best τ=0.380 (val F1=0.3686)
  Directional -> Accuracy: 0.5636, MCC: 0.1587, F1: 0.5200

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.28682 | val 0.93219
  Epoch 016 - train 0.22072 | val 1.08437
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.5938

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.43454 | val 0.71323
  Epoch 016 - train 0.27899 | val 0.84097
  Classification -> best τ=0.575 (val F1=0.2123)
  Directional -> Accuracy: 0.5000, MCC: 0.1291, F1: 0.3226

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.39477 | val 1.36443
  Epoch 016 - train 0.27885 | val 1.86241
  Classification -> best τ=0.515 (val F1=0.1615)
  Directional -> Accuracy: 0.4464, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.33501 | val 0.78802
  Epoch 016 - train 0.19549 | val 1.26960
  Classification -> best τ=0.480 (val F1=0.2957)
  Directional -> Accuracy: 0.5000, MCC: -0.0580, F1: 0.6154

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.41330 | val 1.46027
  Epoch 016 - train 0.24152 | val 2.18406
  Classification -> best τ=0.540 (val F1=0.3689)
  Directional -> Accuracy: 0.4524, MCC: -0.1064, F1: 0.3784

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.44665 | val 1.89484
  Epoch 017 - train 0.22234 | val 2.21755
  Classification -> best τ=0.440 (val F1=0.0806)
  Directional -> Accuracy: 0.5476, MCC: 0.0214, F1: 0.6984

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.38839 | val 1.38113
  Epoch 019 - train 0.22070 | val 2.68174
  Classification -> best τ=0.505 (val F1=0.2645)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.44197 | val 0.86451
  Epoch 017 - train 0.31032 | val 0.98354
  Classification -> best τ=0.490 (val F1=0.3008)
  Directional -> Accuracy: 0.5000, MCC: 0.0323, F1: 0.4545

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.37481 | val 1.10846
  Epoch 016 - train 0.24313 | val 1.29329
  Classification -> best τ=0.460 (val F1=0.3078)
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.49716 | val 1.11685
  Epoch 016 - train 0.36733 | val 1.55091
  Classification -> best τ=0.495 (val F1=0.2358)
  Directional -> Accuracy: 0.6061, MCC: 0.1678, F1: 0.6905

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.26945 | val 1.42663
  Epoch 016 - train 0.16548 | val 2.28952
  Classification -> best τ=0.560 (val F1=0.3260)
  Directional -> Accuracy: 0.4762, MCC: -0.0155, F1: 0.1538

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.36283 | val 2.01703
  Epoch 016 - train 0.23187 | val 3.23468
  Classification -> best τ=0.550 (val F1=0.2850)
  Directional -> Accuracy: 0.5714, MCC: 0.1316, F1: 0.2941

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.31645 | val 0.98964
  Epoch 017 - train 0.20615 | val 1.37412
  Classification -> best τ=0.610 (val F1=0.2924)
  Directional -> Accuracy: 0.3913, MCC: -0.0687, F1: 0.1250

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.38603 | val 0.65695
  Epoch 020 - train 0.12610 | val 1.06317
  Epoch 026 - train 0.05495 | val 1.35093
  Classification -> best τ=0.340 (val F1=0.3476)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.39779 | val 2.07948
  Epoch 016 - train 0.24284 | val 2.78171
  Classification -> best τ=0.490 (val F1=0.1967)
  Directional -> Accuracy: 0.4865, MCC: -0.0293, F1: 0.4571

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.42432 | val 0.84480
  Epoch 019 - train 0.22593 | val 1.45743
  Classification -> best τ=0.355 (val F1=0.2697)
  Directional -> Accuracy: 0.4889, MCC: -0.1474, F1: 0.6567

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.29366 | val 0.92586
  Epoch 018 - train 0.11800 | val 1.31304
  Classification -> best τ=0.535 (val F1=0.3151)
  Directional -> Accuracy: 0.5476, MCC: 0.1434, F1: 0.5128

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.35169 | val 0.60387
  Epoch 020 - train 0.09939 | val 1.00149
  Epoch 022 - train 0.09301 | val 1.00986
  Classification -> best τ=0.440 (val F1=0.4682)
  Directional -> Accuracy: 0.4375, MCC: 0.2000, F1: 0.5714

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.43561 | val 1.15394
  Epoch 016 - train 0.32470 | val 1.57611
  Classification -> best τ=0.570 (val F1=0.2036)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.40094 | val 1.69767
  Epoch 016 - train 0.27427 | val 1.93735
  Classification -> best τ=0.515 (val F1=0.2669)
  Directional -> Accuracy: 0.5714, MCC: 0.2466, F1: 0.2000

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.40928 | val 1.20438
  Epoch 017 - train 0.22121 | val 2.13426
  Classification -> best τ=0.520 (val F1=0.2668)
  Directional -> Accuracy: 0.5283, MCC: 0.0607, F1: 0.4898

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.42057 | val 0.86251
  Epoch 016 - train 0.29162 | val 1.50633
  Classification -> best τ=0.430 (val F1=0.2681)
  Directional -> Accuracy: 0.5273, MCC: 0.0000, F1: 0.6905

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.48371 | val 0.64079
  Epoch 020 - train 0.18641 | val 0.90462

[I 2026-02-22 11:31:37,081] Trial 142 finished with value: 0.2638678053102817 and parameters: {'feature_set': 'sector_emotion', 'model_type': 'BiGRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.2, 'batch_size': 64, 'learning_rate': 0.006176326836655641, 'weight_decay': 2.488078993794681e-05, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 15, 'max_epochs': 30, 'huber_delta': 0.8816260728950187, 'early_stopping_min_delta': 0.0008753084501834297}. Best is trial 112 with value: 0.2833506688525635.

  Epoch 024 - train 0.14103 | val 1.02811
  Classification -> best τ=0.560 (val F1=0.4036)
  Directional -> Accuracy: 0.5667, MCC: 0.1348, F1: 0.4091

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2638678053102817
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down', 'finbert_neutral']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.56725 | val 1.23612
  Epoch 018 - train 0.50682 | val 1.69301
  Classification -> best τ=0.395 (val F1=0.1637)
  Directional -> Accuracy: 0.4474, MCC: 0.0000, F1: 0.6182

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.52868 | val 0.69424
  Epoch 020 - train 0.37324 | val 0.88807
  Epoch 024 - train 0.33672 | val 0.94287
  Classification -> best τ=0.375 (val F1=0.2388)
  Directional -> Accuracy: 0.5778, MCC: 0.0000, F1: 0.7324

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.55964 | val 0.75403
  Epoch 020 - train 0.37962 | val 0.98427
  Epoch 021 - train 0.35913 | val 1.03687
  Classification -> best τ=0.530 (val F1=0.2764)
  Directional -> Accuracy: 0.5000, MCC: 0.0421, F1: 0.2581

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.62182 | val 0.75082
  Epoch 017 - train 0.49314 | val 0.96627
  Classification -> best τ=0.460 (val F1=0.1547)
  Directional -> Accuracy: 0.5405, MCC: 0.0000, F1: 0.7018

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.51754 | val 0.81344
  Epoch 020 - train 0.40409 | val 0.98334
  Classification -> best τ=0.570 (val F1=0.4782)
  Directional -> Accuracy: 0.6800, MCC: 0.3870, F1: 0.6364

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.50424 | val 0.85730
  Epoch 020 - train 0.39800 | val 0.86053
  Epoch 021 - train 0.39863 | val 0.92455
  Classification -> best τ=0.460 (val F1=0.3776)
  Directional -> Accuracy: 0.5217, MCC: 0.1124, F1: 0.6452

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.55769 | val 0.80790
  Epoch 016 - train 0.48487 | val 0.97253
  Classification -> best τ=0.445 (val F1=0.2272)
  Directional -> Accuracy: 0.4853, MCC: 0.1672, F1: 0.5882

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.43142 | val 1.67823
  Epoch 016 - train 0.38479 | val 1.06874
  Classification -> best τ=0.465 (val F1=0.2075)
  Directional -> Accuracy: 0.5238, MCC: -0.1171, F1: 0.0909

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.51046 | val 0.87368
  Epoch 017 - train 0.42039 | val 1.45532
  Classification -> best τ=0.515 (val F1=0.2443)
  Directional -> Accuracy: 0.6667, MCC: 0.3185, F1: 0.5000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.57392 | val 0.90960
  Epoch 017 - train 0.44670 | val 1.08840
  Classification -> best τ=0.530 (val F1=0.2691)
  Directional -> Accuracy: 0.4493, MCC: -0.0192, F1: 0.5366

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.52334 | val 0.96237
  Epoch 018 - train 0.36436 | val 0.96571
  Classification -> best τ=0.450 (val F1=0.1713)
  Directional -> Accuracy: 0.4694, MCC: 0.1303, F1: 0.6286

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.54036 | val 0.93712
  Epoch 017 - train 0.40789 | val 1.70860
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5088, MCC: 0.0000, F1: 0.6744

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.50138 | val 1.07211
  Epoch 018 - train 0.36071 | val 2.40083
  Classification -> best τ=0.410 (val F1=0.3686)
  Directional -> Accuracy: 0.5000, MCC: 0.1319, F1: 0.6316

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.56515 | val 0.87605
  Epoch 020 - train 0.43692 | val 1.36175
  Classification -> best τ=0.355 (val F1=0.3083)
  Directional -> Accuracy: 0.5167, MCC: 0.1302, F1: 0.6742

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.52431 | val 0.72151
  Epoch 020 - train 0.39475 | val 1.16158
  Epoch 023 - train 0.33652 | val 1.29522
  Classification -> best τ=0.590 (val F1=0.3498)
  Directional -> Accuracy: 0.5882, MCC: 0.1489, F1: 0.4324

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.56194 | val 0.99119
  Epoch 020 - train 0.39420 | val 1.15378
  Classification -> best τ=0.485 (val F1=0.2907)
  Directional -> Accuracy: 0.5797, MCC: 0.1834, F1: 0.5397

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.57007 | val 1.29826
  Epoch 016 - train 0.48083 | val 1.66194
  Classification -> best τ=0.505 (val F1=0.1905)
  Directional -> Accuracy: 0.6379, MCC: 0.1397, F1: 0.7640

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.59481 | val 1.14106
  Epoch 016 - train 0.52666 | val 1.80201
  Classification -> best τ=0.505 (val F1=0.1071)
  Directional -> Accuracy: 0.3867, MCC: -0.1424, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.58102 | val 0.94290
  Epoch 020 - train 0.46877 | val 1.20314
  Epoch 021 - train 0.43879 | val 1.15741
  Classification -> best τ=0.295 (val F1=0.2493)
  Directional -> Accuracy: 0.4688, MCC: 0.0537, F1: 0.2917

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.55213 | val 0.75350
  Epoch 019 - train 0.40960 | val 1.06334
  Classification -> best τ=0.445 (val F1=0.1999)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.55024 | val 0.73433
  Epoch 018 - train 0.45163 | val 1.15585
  Classification -> best τ=0.530 (val F1=0.3251)
  Directional -> Accuracy: 0.6170, MCC: 0.0000, F1: 0.7632

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.55178 | val 1.08182
  Epoch 017 - train 0.48988 | val 1.01833
  Classification -> best τ=0.470 (val F1=0.2037)
  Directional -> Accuracy: 0.5231, MCC: 0.1269, F1: 0.6804

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.55900 | val 1.01587
  Epoch 017 - train 0.46807 | val 0.97305
  Classification -> best τ=0.680 (val F1=0.3833)
  Directional -> Accuracy: 0.5263, MCC: 0.1268, F1: 0.4255

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.59703 | val 0.81412
  Epoch 017 - train 0.48165 | val 0.75609
  Classification -> best τ=0.560 (val F1=0.1565)
  Directional -> Accuracy: 0.5692, MCC: 0.1464, F1: 0.5882

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.47844 | val 0.97229
  Epoch 017 - train 0.35054 | val 1.30586
  Classification -> best τ=0.495 (val F1=0.3020)
  Directional -> Accuracy: 0.4545, MCC: -0.0319, F1: 0.1667

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.47725 | val 0.95259
  Epoch 016 - train 0.40492 | val 1.52876
  Classification -> best τ=0.535 (val F1=0.1932)
  Directional -> Accuracy: 0.5556, MCC: -0.1289, F1: 0.0000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.56677 | val 0.73987
  Epoch 019 - train 0.43051 | val 0.80954
  Classification -> best τ=0.560 (val F1=0.0694)
  Directional -> Accuracy: 0.5714, MCC: 0.1250, F1: 0.6250

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.53715 | val 1.21930
  Epoch 017 - train 0.43786 | val 1.52528
  Classification -> best τ=0.460 (val F1=0.2203)
  Directional -> Accuracy: 0.5179, MCC: 0.2491, F1: 0.2286

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.55557 | val 0.82473
  Epoch 017 - train 0.45383 | val 0.83570
  Classification -> best τ=0.515 (val F1=0.0383)
  Directional -> Accuracy: 0.5500, MCC: 0.1005, F1: 0.5714

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.55166 | val 1.43122
  Epoch 017 - train 0.48923 | val 0.81581
  Classification -> best τ=0.570 (val F1=0.3501)
  Directional -> Accuracy: 0.5238, MCC: 0.0455, F1: 0.5000

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.55295 | val 1.03543
  Epoch 018 - train 0.48844 | val 1.44751
  Classification -> best τ=0.420 (val F1=0.0769)
  Directional -> Accuracy: 0.5476, MCC: 0.0000, F1: 0.7077

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.56180 | val 0.79541
  Epoch 017 - train 0.41355 | val 0.89448
  Classification -> best τ=0.600 (val F1=0.2399)
  Directional -> Accuracy: 0.5306, MCC: 0.0127, F1: 0.6849

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.53377 | val 1.06063
  Epoch 018 - train 0.41203 | val 1.27086
  Classification -> best τ=0.415 (val F1=0.2736)
  Directional -> Accuracy: 0.5556, MCC: 0.1402, F1: 0.5294

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.51655 | val 0.94282
  Epoch 016 - train 0.38027 | val 1.25957
  Classification -> best τ=0.425 (val F1=0.1874)
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.55437 | val 1.02434
  Epoch 016 - train 0.46696 | val 1.43259
  Classification -> best τ=0.435 (val F1=0.2117)
  Directional -> Accuracy: 0.5758, MCC: 0.0000, F1: 0.7308

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.43927 | val 0.68592
  Epoch 020 - train 0.30068 | val 1.07696
  Epoch 023 - train 0.27392 | val 1.10125
  Classification -> best τ=0.300 (val F1=0.3603)
  Directional -> Accuracy: 0.6429, MCC: 0.2821, F1: 0.6809

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.45776 | val 1.92303
  Epoch 016 - train 0.39103 | val 1.87126
  Classification -> best τ=0.480 (val F1=0.1951)
  Directional -> Accuracy: 0.5179, MCC: 0.0185, F1: 0.4255

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.47902 | val 1.13426
  Epoch 016 - train 0.38418 | val 1.53600
  Classification -> best τ=0.440 (val F1=0.2474)
  Directional -> Accuracy: 0.4565, MCC: -0.1776, F1: 0.5763

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.46793 | val 0.67219
  Epoch 020 - train 0.36010 | val 0.78253
  Epoch 022 - train 0.33636 | val 0.93782
  Classification -> best τ=0.430 (val F1=0.4011)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.54857 | val 1.05726
  Epoch 018 - train 0.41884 | val 1.47327
  Classification -> best τ=0.465 (val F1=0.3006)
  Directional -> Accuracy: 0.5000, MCC: 0.1139, F1: 0.6606

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.52656 | val 0.66217
  Epoch 020 - train 0.35068 | val 0.89054
  Epoch 025 - train 0.29196 | val 0.93527
  Classification -> best τ=0.475 (val F1=0.3981)
  Directional -> Accuracy: 0.4889, MCC: -0.1474, F1: 0.6567

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.52370 | val 0.62764
  Epoch 020 - train 0.38186 | val 0.62126
  Epoch 030 - train 0.26982 | val 1.22697
  Classification -> best τ=0.190 (val F1=0.4588)
  Directional -> Accuracy: 0.5000, MCC: -0.1698, F1: 0.6557

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.50812 | val 0.70873
  Epoch 020 - train 0.41537 | val 0.96648
  Epoch 022 - train 0.36252 | val 1.15122
  Classification -> best τ=0.690 (val F1=0.4092)
  Directional -> Accuracy: 0.3750, MCC: -0.0976, F1: 0.5000

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.55708 | val 0.79583
  Epoch 016 - train 0.50427 | val 0.84255
  Classification -> best τ=0.535 (val F1=0.1605)
  Directional -> Accuracy: 0.4909, MCC: -0.1617, F1: 0.6500

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.52249 | val 2.49543
  Epoch 016 - train 0.45277 | val 3.42932
  Classification -> best τ=0.465 (val F1=0.2491)
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.6506

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.53024 | val 0.83750
  Epoch 017 - train 0.48318 | val 1.14127
  Classification -> best τ=0.480 (val F1=0.2203)
  Directional -> Accuracy: 0.5660, MCC: 0.1493, F1: 0.6667

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.54635 | val 0.89891
  Epoch 016 - train 0.49654 | val 0.99525
  Classification -> best τ=0.490 (val F1=0.0924)
  Directional -> Accuracy: 0.5273, MCC: 0.0000, F1: 0.6905

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.57782 | val 1.18730
  Epoch 020 - train 0.44614 | val 1.45121

[I 2026-02-22 11:33:32,314] Trial 143 finished with value: 0.24604237224480738 and parameters: {'feature_set': 'finbert', 'model_type': 'BiGRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.2, 'batch_size': 64, 'learning_rate': 0.005243299420088731, 'weight_decay': 1.514507938295823e-05, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 15, 'max_epochs': 30, 'huber_delta': 0.9490377212050395, 'early_stopping_min_delta': 0.00021657848242945244}. Best is trial 112 with value: 0.2833506688525635.

  Epoch 023 - train 0.40664 | val 1.90088
  Classification -> best τ=0.550 (val F1=0.2124)
  Directional -> Accuracy: 0.5833, MCC: 0.1823, F1: 0.6269

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.24604237224480738
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.58441 | val 0.80632
  Epoch 016 - train 0.53076 | val 0.77183
  Classification -> best τ=0.450 (val F1=0.2919)
  Directional -> Accuracy: 0.6053, MCC: 0.2313, F1: 0.6154

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.51964 | val 0.69007
  Epoch 014 - train 0.47268 | val 0.72605
  Classification -> best τ=0.535 (val F1=0.2523)
  Directional -> Accuracy: 0.6000, MCC: 0.1419, F1: 0.7000

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.56126 | val 0.79634
  Epoch 011 - train 0.57961 | val 0.84895
  Classification -> best τ=0.470 (val F1=0.1864)
  Directional -> Accuracy: 0.4348, MCC: -0.1241, F1: 0.3810

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.59066 | val 1.02144
  Epoch 011 - train 0.59199 | val 0.94725
  Classification -> best τ=0.445 (val F1=0.1414)
  Directional -> Accuracy: 0.5405, MCC: 0.0000, F1: 0.7018

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.53986 | val 0.72219
  Epoch 016 - train 0.48721 | val 0.65028
  Classification -> best τ=0.485 (val F1=0.4342)
  Directional -> Accuracy: 0.6800, MCC: 0.3759, F1: 0.6522

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.56920 | val 0.77923
  Epoch 015 - train 0.49553 | val 0.96291
  Classification -> best τ=0.555 (val F1=0.2739)
  Directional -> Accuracy: 0.5652, MCC: 0.1348, F1: 0.3333

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.62420 | val 1.07850
  Epoch 012 - train 0.59180 | val 1.03412
  Classification -> best τ=0.455 (val F1=0.2605)
  Directional -> Accuracy: 0.4559, MCC: 0.1465, F1: 0.5843

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.51676 | val 0.60706
  Epoch 020 - train 0.44588 | val 0.85526
  Epoch 023 - train 0.44263 | val 0.69517
  Classification -> best τ=0.600 (val F1=0.5247)
  Directional -> Accuracy: 0.5000, MCC: 0.0280, F1: 0.5116

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.57415 | val 1.03875
  Epoch 014 - train 0.53397 | val 1.57052
  Classification -> best τ=0.540 (val F1=0.3433)
  Directional -> Accuracy: 0.5625, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.54178 | val 0.82758
  Epoch 014 - train 0.51937 | val 0.92070
  Classification -> best τ=0.590 (val F1=0.1983)
  Directional -> Accuracy: 0.5362, MCC: -0.0099, F1: 0.3043

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.58243 | val 0.87792
  Epoch 014 - train 0.55838 | val 1.19008
  Classification -> best τ=0.660 (val F1=0.3075)
  Directional -> Accuracy: 0.5306, MCC: -0.1303, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.61116 | val 1.06881
  Epoch 012 - train 0.56909 | val 1.14258
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5088, MCC: 0.0000, F1: 0.6744

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.51951 | val 1.06498
  Epoch 011 - train 0.50482 | val 1.17555
  Classification -> best τ=0.465 (val F1=0.0875)
  Directional -> Accuracy: 0.5000, MCC: -0.0454, F1: 0.3226

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.57190 | val 0.76814
  Epoch 018 - train 0.48515 | val 0.99472
  Classification -> best τ=0.510 (val F1=0.3387)
  Directional -> Accuracy: 0.4833, MCC: -0.0765, F1: 0.0606

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.57969 | val 0.77576
  Epoch 014 - train 0.52073 | val 0.84550
  Classification -> best τ=0.510 (val F1=0.2571)
  Directional -> Accuracy: 0.5490, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.53332 | val 0.88728
  Epoch 012 - train 0.53196 | val 0.96874
  Classification -> best τ=0.490 (val F1=0.3589)
  Directional -> Accuracy: 0.6087, MCC: 0.2301, F1: 0.7158

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.59959 | val 1.15667
  Epoch 011 - train 0.58667 | val 1.22731
  Classification -> best τ=0.450 (val F1=0.1179)
  Directional -> Accuracy: 0.5690, MCC: -0.0406, F1: 0.7059

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.57700 | val 0.90085
  Epoch 012 - train 0.54887 | val 1.02796
  Classification -> best τ=0.415 (val F1=0.1612)
  Directional -> Accuracy: 0.5333, MCC: -0.0863, F1: 0.6729

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.57086 | val 0.85427
  Epoch 012 - train 0.55638 | val 0.95085
  Classification -> best τ=0.435 (val F1=0.3140)
  Directional -> Accuracy: 0.6094, MCC: 0.1602, F1: 0.7126

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.57555 | val 0.76252
  Epoch 015 - train 0.53535 | val 0.82514
  Classification -> best τ=0.460 (val F1=0.3062)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.56492 | val 0.86494
  Epoch 011 - train 0.53008 | val 0.94361
  Classification -> best τ=0.460 (val F1=0.2784)
  Directional -> Accuracy: 0.6170, MCC: 0.0000, F1: 0.7632

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.57140 | val 0.71672
  Epoch 017 - train 0.48653 | val 0.95989
  Classification -> best τ=0.430 (val F1=0.2607)
  Directional -> Accuracy: 0.5385, MCC: 0.0959, F1: 0.4000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.60400 | val 0.74797
  Epoch 013 - train 0.55867 | val 0.74874
  Classification -> best τ=0.765 (val F1=0.2942)
  Directional -> Accuracy: 0.4211, MCC: -0.1512, F1: 0.0000

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.56062 | val 0.82735
  Epoch 012 - train 0.57325 | val 0.90031
  Classification -> best τ=0.470 (val F1=0.0893)
  Directional -> Accuracy: 0.5385, MCC: 0.0880, F1: 0.5714

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.47313 | val 0.90907
  Epoch 015 - train 0.46292 | val 1.17286
  Classification -> best τ=0.570 (val F1=0.4120)
  Directional -> Accuracy: 0.5455, MCC: 0.1826, F1: 0.3902

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.60050 | val 0.72431
  Epoch 017 - train 0.47172 | val 0.72981
  Classification -> best τ=0.455 (val F1=0.3669)
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.5938

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.60751 | val 0.67761
  Epoch 020 - train 0.54307 | val 0.73752
  Epoch 024 - train 0.49342 | val 0.68340
  Classification -> best τ=0.645 (val F1=0.2582)
  Directional -> Accuracy: 0.5952, MCC: 0.2970, F1: 0.5143

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.58243 | val 0.69980
  Epoch 014 - train 0.51145 | val 0.83956
  Classification -> best τ=0.540 (val F1=0.2305)
  Directional -> Accuracy: 0.4464, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.53849 | val 0.91216
  Epoch 015 - train 0.51352 | val 1.02002
  Classification -> best τ=0.445 (val F1=0.4109)
  Directional -> Accuracy: 0.5500, MCC: 0.0231, F1: 0.7000

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.55636 | val 0.77740
  Epoch 011 - train 0.60766 | val 0.84754
  Classification -> best τ=0.525 (val F1=0.2814)
  Directional -> Accuracy: 0.5000, MCC: -0.0142, F1: 0.4000

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.57870 | val 1.01721
  Epoch 011 - train 0.60690 | val 1.21994
  Classification -> best τ=0.470 (val F1=0.1286)
  Directional -> Accuracy: 0.4286, MCC: -0.1070, F1: 0.2000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.52685 | val 0.84358
  Epoch 016 - train 0.47912 | val 1.17197
  Classification -> best τ=0.360 (val F1=0.3714)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.54928 | val 0.85609
  Epoch 011 - train 0.54652 | val 0.90710
  Classification -> best τ=0.410 (val F1=0.2231)
  Directional -> Accuracy: 0.5000, MCC: -0.0125, F1: 0.5500

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.55577 | val 0.84676
  Epoch 011 - train 0.56187 | val 0.86902
  Classification -> best τ=0.475 (val F1=0.3555)
  Directional -> Accuracy: 0.6279, MCC: 0.2708, F1: 0.6667

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.57906 | val 0.95247
  Epoch 011 - train 0.55272 | val 0.98967
  Classification -> best τ=0.465 (val F1=0.3254)
  Directional -> Accuracy: 0.6667, MCC: 0.3246, F1: 0.7027

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.52550 | val 0.80217
  Epoch 011 - train 0.50875 | val 0.84243
  Classification -> best τ=0.470 (val F1=0.2658)
  Directional -> Accuracy: 0.5952, MCC: 0.1850, F1: 0.6383

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.54522 | val 1.31575
  Epoch 012 - train 0.53446 | val 1.26204
  Classification -> best τ=0.545 (val F1=0.2327)
  Directional -> Accuracy: 0.5179, MCC: 0.0333, F1: 0.4906

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.52236 | val 0.69866
  Epoch 012 - train 0.51299 | val 0.69594
  Classification -> best τ=0.500 (val F1=0.2441)
  Directional -> Accuracy: 0.4130, MCC: -0.0062, F1: 0.1818

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.53680 | val 0.64739
  Epoch 020 - train 0.50340 | val 0.66254
  Epoch 027 - train 0.48908 | val 0.61836
  Classification -> best τ=0.320 (val F1=0.4242)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.51957 | val 1.25904
  Epoch 011 - train 0.54689 | val 1.30566
  Classification -> best τ=0.510 (val F1=0.2709)
  Directional -> Accuracy: 0.4730, MCC: -0.0549, F1: 0.6214

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.60626 | val 0.70402
  Epoch 011 - train 0.60697 | val 0.70624
  Classification -> best τ=0.485 (val F1=0.3953)
  Directional -> Accuracy: 0.5333, MCC: 0.1541, F1: 0.6866

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.53052 | val 0.73398
  Epoch 014 - train 0.46064 | val 0.78749
  Classification -> best τ=0.565 (val F1=0.3151)
  Directional -> Accuracy: 0.4286, MCC: -0.0589, F1: 0.2000

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.54354 | val 0.64558
  Epoch 018 - train 0.50019 | val 0.72210
  Classification -> best τ=0.645 (val F1=0.5261)
  Directional -> Accuracy: 0.5417, MCC: 0.1080, F1: 0.5000

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.62100 | val 0.75264
  Epoch 014 - train 0.54022 | val 0.86344
  Classification -> best τ=0.685 (val F1=0.1647)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.48705 | val 0.99312
  Epoch 011 - train 0.52344 | val 1.09565
  Classification -> best τ=0.435 (val F1=0.3249)
  Directional -> Accuracy: 0.5179, MCC: 0.0479, F1: 0.5714

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.58160 | val 1.21978
  Epoch 013 - train 0.55937 | val 1.12808
  Classification -> best τ=0.415 (val F1=0.1824)
  Directional -> Accuracy: 0.5660, MCC: 0.2496, F1: 0.7013

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.56829 | val 1.02454
  Epoch 011 - train 0.56193 | val 1.00920
  Classification -> best τ=0.545 (val F1=0.0684)
  Directional -> Accuracy: 0.4182, MCC: -0.1596, F1: 0.4074

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.58419 | val 0.70183

[I 2026-02-22 11:34:56,837] Trial 144 finished with value: 0.27443471475524456 and parameters: {'feature_set': 'sector', 'model_type': 'BiGRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.30000000000000004, 'batch_size': 64, 'learning_rate': 0.00303101228410679, 'weight_decay': 3.015006529675992e-05, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 1.0424204816204412, 'early_stopping_min_delta': 0.0004062901370442983}. Best is trial 112 with value: 0.2833506688525635.

  Epoch 016 - train 0.51289 | val 0.71094
  Classification -> best τ=0.440 (val F1=0.3158)
  Directional -> Accuracy: 0.6000, MCC: 0.1991, F1: 0.5862

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.27443471475524456
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.58786 | val 0.72734
  Epoch 020 - train 0.50589 | val 0.96999
  Classification -> best τ=0.540 (val F1=0.2510)
  Directional -> Accuracy: 0.6053, MCC: 0.1938, F1: 0.5312

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.53503 | val 0.78505
  Epoch 018 - train 0.44256 | val 0.91099
  Classification -> best τ=0.535 (val F1=0.2523)
  Directional -> Accuracy: 0.6889, MCC: 0.3485, F1: 0.7586

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.57152 | val 0.98812
  Epoch 017 - train 0.52978 | val 1.42949
  Classification -> best τ=0.555 (val F1=0.1854)
  Directional -> Accuracy: 0.4783, MCC: -0.0093, F1: 0.0769

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.59477 | val 0.93543
  Epoch 020 - train 0.51900 | val 0.85906
  Classification -> best τ=0.390 (val F1=0.2230)
  Directional -> Accuracy: 0.5405, MCC: 0.0000, F1: 0.7018

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.55259 | val 0.65004
  Epoch 020 - train 0.44109 | val 0.73908
  Epoch 023 - train 0.38635 | val 0.77178
  Classification -> best τ=0.560 (val F1=0.4414)
  Directional -> Accuracy: 0.6200, MCC: 0.2795, F1: 0.5366

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.53423 | val 0.70545
  Epoch 020 - train 0.46898 | val 0.74538
  Epoch 028 - train 0.48452 | val 0.80274
  Classification -> best τ=0.290 (val F1=0.3776)
  Directional -> Accuracy: 0.5652, MCC: 0.1241, F1: 0.5000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.62503 | val 1.21663
  Epoch 016 - train 0.60153 | val 1.49729
  Classification -> best τ=0.430 (val F1=0.2831)
  Directional -> Accuracy: 0.4706, MCC: 0.1396, F1: 0.5814

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.53877 | val 0.68981
  Epoch 020 - train 0.45508 | val 0.71689
  Epoch 026 - train 0.40224 | val 1.17175
  Classification -> best τ=0.640 (val F1=0.3689)
  Directional -> Accuracy: 0.5000, MCC: 0.0138, F1: 0.4878

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.55384 | val 0.90999
  Epoch 019 - train 0.52003 | val 1.92907
  Classification -> best τ=0.495 (val F1=0.3441)
  Directional -> Accuracy: 0.5625, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.56101 | val 0.69754
  Epoch 020 - train 0.43286 | val 0.72124
  Epoch 025 - train 0.40042 | val 0.71881
  Classification -> best τ=0.500 (val F1=0.2150)
  Directional -> Accuracy: 0.4638, MCC: -0.0664, F1: 0.4308

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.59060 | val 0.88538
  Epoch 017 - train 0.54737 | val 1.16825
  Classification -> best τ=0.550 (val F1=0.3075)
  Directional -> Accuracy: 0.5510, MCC: 0.0212, F1: 0.0833

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.55222 | val 1.08622
  Epoch 017 - train 0.52767 | val 1.57867
  Classification -> best τ=0.605 (val F1=0.1181)
  Directional -> Accuracy: 0.5614, MCC: 0.1764, F1: 0.3590

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.54487 | val 0.90900
  Epoch 016 - train 0.49638 | val 1.16483
  Classification -> best τ=0.440 (val F1=0.1991)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.6230

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.59056 | val 0.71215
  Epoch 020 - train 0.51102 | val 0.77466
  Classification -> best τ=0.525 (val F1=0.3864)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.52629 | val 0.68637
  Epoch 020 - train 0.45168 | val 0.79281
  Epoch 021 - train 0.43999 | val 0.78723
  Classification -> best τ=0.525 (val F1=0.2571)
  Directional -> Accuracy: 0.5294, MCC: -0.0591, F1: 0.0769

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.57158 | val 0.90966
  Epoch 017 - train 0.53173 | val 0.97581
  Classification -> best τ=0.430 (val F1=0.2795)
  Directional -> Accuracy: 0.5507, MCC: 0.0713, F1: 0.6804

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.60754 | val 0.88424
  Epoch 016 - train 0.56357 | val 1.14594
  Classification -> best τ=0.570 (val F1=0.1842)
  Directional -> Accuracy: 0.3793, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.59668 | val 0.97219
  Epoch 016 - train 0.55785 | val 0.95209
  Classification -> best τ=0.565 (val F1=0.2220)
  Directional -> Accuracy: 0.4133, MCC: -0.0970, F1: 0.3333

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.57949 | val 0.92617
  Epoch 019 - train 0.49196 | val 1.20095
  Classification -> best τ=0.310 (val F1=0.2472)
  Directional -> Accuracy: 0.5781, MCC: 0.0760, F1: 0.6966

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.57848 | val 0.77692
  Epoch 018 - train 0.51133 | val 1.02117
  Classification -> best τ=0.475 (val F1=0.2056)
  Directional -> Accuracy: 0.4189, MCC: -0.1858, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.56287 | val 0.74395
  Epoch 016 - train 0.53383 | val 1.11551
  Classification -> best τ=0.455 (val F1=0.1039)
  Directional -> Accuracy: 0.6170, MCC: 0.0000, F1: 0.7632

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.57980 | val 0.83791
  Epoch 016 - train 0.51152 | val 1.00635
  Classification -> best τ=0.450 (val F1=0.1543)
  Directional -> Accuracy: 0.5846, MCC: 0.1968, F1: 0.4706

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.58965 | val 0.67935
  Epoch 020 - train 0.50158 | val 0.92752
  Classification -> best τ=0.780 (val F1=0.3144)
  Directional -> Accuracy: 0.4912, MCC: 0.0250, F1: 0.4314

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.60389 | val 0.72732
  Epoch 018 - train 0.48821 | val 0.87433
  Classification -> best τ=0.465 (val F1=0.0478)
  Directional -> Accuracy: 0.4923, MCC: 0.0632, F1: 0.6452

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.54237 | val 0.95178
  Epoch 020 - train 0.43155 | val 1.35420
  Classification -> best τ=0.395 (val F1=0.4344)
  Directional -> Accuracy: 0.5818, MCC: 0.1913, F1: 0.5490

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.57551 | val 0.77008
  Epoch 016 - train 0.49520 | val 0.90360
  Classification -> best τ=0.495 (val F1=0.1310)
  Directional -> Accuracy: 0.3556, MCC: -0.2466, F1: 0.4528

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.58564 | val 0.70476
  Epoch 020 - train 0.52767 | val 0.73106
  Epoch 028 - train 0.45438 | val 0.71555
  Classification -> best τ=0.650 (val F1=0.2970)
  Directional -> Accuracy: 0.5238, MCC: 0.1750, F1: 0.3750

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.60237 | val 0.78420
  Epoch 017 - train 0.50937 | val 0.99296
  Classification -> best τ=0.485 (val F1=0.1518)
  Directional -> Accuracy: 0.5357, MCC: 0.2308, F1: 0.3158

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.56438 | val 0.68510
  Epoch 020 - train 0.47151 | val 1.31043
  Epoch 024 - train 0.44576 | val 0.90543
  Classification -> best τ=0.580 (val F1=0.2774)
  Directional -> Accuracy: 0.4500, MCC: -0.0821, F1: 0.4211

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.59999 | val 0.73821
  Epoch 016 - train 0.52196 | val 0.76099
  Classification -> best τ=0.500 (val F1=0.0070)
  Directional -> Accuracy: 0.4762, MCC: -0.0674, F1: 0.3529

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.56764 | val 1.24482
  Epoch 016 - train 0.54841 | val 1.47154
  Classification -> best τ=0.455 (val F1=0.0409)
  Directional -> Accuracy: 0.5476, MCC: 0.0000, F1: 0.7077

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.54295 | val 0.94386
  Epoch 018 - train 0.49470 | val 1.33798
  Classification -> best τ=0.615 (val F1=0.3465)
  Directional -> Accuracy: 0.5102, MCC: 0.0217, F1: 0.5200

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.60353 | val 0.85230
  Epoch 016 - train 0.52583 | val 0.87766
  Classification -> best τ=0.410 (val F1=0.2774)
  Directional -> Accuracy: 0.5417, MCC: 0.1682, F1: 0.4211

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.55361 | val 0.84667
  Epoch 016 - train 0.50466 | val 1.03377
  Classification -> best τ=0.520 (val F1=0.3227)
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.56068 | val 1.05772
  Epoch 016 - train 0.54283 | val 1.06956
  Classification -> best τ=0.455 (val F1=0.3603)
  Directional -> Accuracy: 0.6212, MCC: 0.1915, F1: 0.7253

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.48454 | val 0.74257
  Epoch 017 - train 0.45604 | val 0.99615
  Classification -> best τ=0.500 (val F1=0.2839)
  Directional -> Accuracy: 0.6667, MCC: 0.3708, F1: 0.6111

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.51883 | val 1.06804
  Epoch 016 - train 0.49773 | val 1.65102
  Classification -> best τ=0.455 (val F1=0.2110)
  Directional -> Accuracy: 0.5000, MCC: 0.0051, F1: 0.5000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.47951 | val 0.79721
  Epoch 020 - train 0.40396 | val 1.09482
  Classification -> best τ=0.575 (val F1=0.2441)
  Directional -> Accuracy: 0.4130, MCC: -0.0062, F1: 0.1818

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.58945 | val 0.65058
  Epoch 020 - train 0.49345 | val 0.59201
  Epoch 030 - train 0.42232 | val 0.64928
  Classification -> best τ=0.275 (val F1=0.4973)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.58855 | val 1.19193
  Epoch 017 - train 0.49196 | val 1.53773
  Classification -> best τ=0.460 (val F1=0.3134)
  Directional -> Accuracy: 0.4865, MCC: 0.0000, F1: 0.6545

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.61284 | val 0.73204
  Epoch 016 - train 0.56310 | val 0.73441
  Classification -> best τ=0.420 (val F1=0.5000)
  Directional -> Accuracy: 0.5333, MCC: 0.2109, F1: 0.1600

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.53069 | val 0.72898
  Epoch 016 - train 0.49074 | val 0.79851
  Classification -> best τ=0.490 (val F1=0.0891)
  Directional -> Accuracy: 0.3810, MCC: -0.2107, F1: 0.0714

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.57400 | val 0.65906
  Epoch 020 - train 0.47293 | val 0.69547
  Epoch 030 - train 0.32695 | val 0.81832
  Classification -> best τ=0.725 (val F1=0.4478)
  Directional -> Accuracy: 0.5417, MCC: 0.2485, F1: 0.5926

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.56939 | val 0.76926
  Epoch 020 - train 0.56008 | val 0.82053
  Classification -> best τ=0.655 (val F1=0.1647)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.55390 | val 1.16443
  Epoch 016 - train 0.50265 | val 1.74272
  Classification -> best τ=0.500 (val F1=0.3067)
  Directional -> Accuracy: 0.5357, MCC: 0.0633, F1: 0.4348

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.56055 | val 0.92651
  Epoch 016 - train 0.55523 | val 1.09249
  Classification -> best τ=0.505 (val F1=0.1573)
  Directional -> Accuracy: 0.5660, MCC: 0.1493, F1: 0.6667

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.56322 | val 1.07447
  Epoch 016 - train 0.52473 | val 1.34932
  Classification -> best τ=0.570 (val F1=0.1186)
  Directional -> Accuracy: 0.4000, MCC: -0.2291, F1: 0.1081

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.56958 | val 0.66263
  Epoch 020 - train 0.46978 | val 0.80342

[I 2026-02-22 11:36:50,245] Trial 145 finished with value: 0.25613996685918866 and parameters: {'feature_set': 'sector', 'model_type': 'BiGRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.30000000000000004, 'batch_size': 64, 'learning_rate': 0.0028047717292773652, 'weight_decay': 2.9052022358604757e-05, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 15, 'max_epochs': 30, 'huber_delta': 1.0206203125880327, 'early_stopping_min_delta': 1.4616999479996444e-06}. Best is trial 112 with value: 0.2833506688525635.

  Epoch 025 - train 0.41832 | val 0.88044
  Classification -> best τ=0.495 (val F1=0.3455)
  Directional -> Accuracy: 0.6500, MCC: 0.2995, F1: 0.6038

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.25613996685918866
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.58817 | val 0.83728
  Epoch 015 - train 0.55967 | val 0.93788
  Classification -> best τ=0.460 (val F1=0.2510)
  Directional -> Accuracy: 0.5789, MCC: 0.1709, F1: 0.5789

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.46719 | val 0.76629
  Epoch 013 - train 0.48113 | val 1.08822
  Classification -> best τ=0.420 (val F1=0.3860)
  Directional -> Accuracy: 0.5778, MCC: 0.0000, F1: 0.7324

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.55489 | val 1.10611
  Epoch 012 - train 0.59704 | val 1.24478
  Classification -> best τ=0.565 (val F1=0.2861)
  Directional -> Accuracy: 0.4783, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.56974 | val 0.69293
  Epoch 019 - train 0.51320 | val 0.79012
  Classification -> best τ=0.375 (val F1=0.2593)
  Directional -> Accuracy: 0.5270, MCC: -0.0112, F1: 0.6667

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.55288 | val 0.69099
  Epoch 018 - train 0.49614 | val 0.73951
  Classification -> best τ=0.555 (val F1=0.2934)
  Directional -> Accuracy: 0.6200, MCC: 0.2795, F1: 0.5366

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.51248 | val 0.68083
  Epoch 020 - train 0.45599 | val 0.89456
  Classification -> best τ=0.505 (val F1=0.3525)
  Directional -> Accuracy: 0.5870, MCC: 0.2002, F1: 0.3448

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.59168 | val 1.16702
  Epoch 011 - train 0.57881 | val 1.29754
  Classification -> best τ=0.510 (val F1=0.2449)
  Directional -> Accuracy: 0.5294, MCC: 0.0417, F1: 0.4483

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.51928 | val 0.73986
  Epoch 011 - train 0.59640 | val 0.74344
  Classification -> best τ=0.435 (val F1=0.3094)
  Directional -> Accuracy: 0.5714, MCC: 0.0468, F1: 0.1818

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.53370 | val 1.00464
  Epoch 014 - train 0.53155 | val 1.37131
  Classification -> best τ=0.550 (val F1=0.3433)
  Directional -> Accuracy: 0.6042, MCC: 0.1732, F1: 0.4571

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.59670 | val 0.70651
  Epoch 018 - train 0.46910 | val 0.79972
  Classification -> best τ=0.525 (val F1=0.3007)
  Directional -> Accuracy: 0.4348, MCC: -0.0912, F1: 0.4658

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.58006 | val 0.77369
  Epoch 013 - train 0.56224 | val 0.85442
  Classification -> best τ=0.505 (val F1=0.4498)
  Directional -> Accuracy: 0.5918, MCC: 0.1804, F1: 0.2308

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.59043 | val 1.02877
  Epoch 011 - train 0.56825 | val 0.97566
  Classification -> best τ=0.520 (val F1=0.1000)
  Directional -> Accuracy: 0.6491, MCC: 0.3361, F1: 0.7222

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.54368 | val 0.85312
  Epoch 011 - train 0.48019 | val 0.87106
  Classification -> best τ=0.575 (val F1=0.0875)
  Directional -> Accuracy: 0.5952, MCC: 0.1940, F1: 0.2609

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.57875 | val 0.74058
  Epoch 015 - train 0.56118 | val 0.94002
  Classification -> best τ=0.565 (val F1=0.3378)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.55506 | val 0.86472
  Epoch 016 - train 0.51462 | val 0.94037
  Classification -> best τ=0.570 (val F1=0.2720)
  Directional -> Accuracy: 0.5490, MCC: 0.0199, F1: 0.0800

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.57324 | val 0.86192
  Epoch 013 - train 0.53900 | val 0.94896
  Classification -> best τ=0.370 (val F1=0.2341)
  Directional -> Accuracy: 0.5217, MCC: -0.0150, F1: 0.6598

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.60465 | val 1.17833
  Epoch 011 - train 0.58378 | val 1.20409
  Classification -> best τ=0.575 (val F1=0.2276)
  Directional -> Accuracy: 0.3966, MCC: 0.0221, F1: 0.1026

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.60442 | val 0.86251
  Epoch 011 - train 0.55390 | val 0.89214
  Classification -> best τ=0.580 (val F1=0.1087)
  Directional -> Accuracy: 0.3867, MCC: -0.1294, F1: 0.2069

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.56650 | val 0.73281
  Epoch 014 - train 0.51441 | val 0.81222
  Classification -> best τ=0.370 (val F1=0.3624)
  Directional -> Accuracy: 0.5781, MCC: 0.0837, F1: 0.6897

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.54922 | val 0.77907
  Epoch 016 - train 0.52277 | val 0.83285
  Classification -> best τ=0.370 (val F1=0.3303)
  Directional -> Accuracy: 0.4595, MCC: 0.1050, F1: 0.0476

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.50707 | val 0.84955
  Epoch 011 - train 0.54976 | val 0.85161
  Classification -> best τ=0.500 (val F1=0.2295)
  Directional -> Accuracy: 0.6170, MCC: 0.0000, F1: 0.7632

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.55821 | val 0.87859
  Epoch 014 - train 0.51075 | val 0.83873
  Classification -> best τ=0.515 (val F1=0.2509)
  Directional -> Accuracy: 0.5077, MCC: 0.0699, F1: 0.1111

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.58241 | val 0.72769
  Epoch 013 - train 0.57914 | val 0.73139
  Classification -> best τ=0.495 (val F1=0.3566)
  Directional -> Accuracy: 0.5614, MCC: 0.0236, F1: 0.7126

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.58786 | val 0.72643
  Epoch 012 - train 0.59459 | val 0.73487
  Classification -> best τ=0.520 (val F1=0.1415)
  Directional -> Accuracy: 0.5538, MCC: 0.1051, F1: 0.2927

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.50437 | val 0.98321
  Epoch 015 - train 0.42456 | val 1.42913
  Classification -> best τ=0.430 (val F1=0.4306)
  Directional -> Accuracy: 0.5818, MCC: 0.1913, F1: 0.5490

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.51255 | val 0.79228
  Epoch 011 - train 0.54124 | val 0.78391
  Classification -> best τ=0.500 (val F1=0.2726)
  Directional -> Accuracy: 0.5778, MCC: 0.0340, F1: 0.0952

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.58894 | val 0.72298
  Epoch 015 - train 0.53721 | val 0.71931
  Classification -> best τ=0.565 (val F1=0.2810)
  Directional -> Accuracy: 0.5952, MCC: 0.2240, F1: 0.5854

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.55957 | val 0.79246
  Epoch 013 - train 0.56412 | val 0.83779
  Classification -> best τ=0.435 (val F1=0.0545)
  Directional -> Accuracy: 0.5536, MCC: 0.0000, F1: 0.7126

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.53787 | val 0.73121
  Epoch 014 - train 0.59648 | val 0.83762
  Classification -> best τ=0.470 (val F1=0.4099)
  Directional -> Accuracy: 0.5750, MCC: 0.1140, F1: 0.7018

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.60426 | val 0.86634
  Epoch 011 - train 0.51514 | val 0.79302
  Classification -> best τ=0.535 (val F1=0.3501)
  Directional -> Accuracy: 0.4762, MCC: -0.0754, F1: 0.3125

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.59059 | val 1.01937
  Epoch 012 - train 0.55109 | val 0.99326
  Classification -> best τ=0.400 (val F1=0.2357)
  Directional -> Accuracy: 0.5476, MCC: 0.0000, F1: 0.7077

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.50968 | val 0.94560
  Epoch 013 - train 0.57654 | val 0.96442
  Classification -> best τ=0.445 (val F1=0.3242)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.58344 | val 0.89070
  Epoch 011 - train 0.56373 | val 0.97490
  Classification -> best τ=0.535 (val F1=0.2637)
  Directional -> Accuracy: 0.4444, MCC: 0.0000, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.55507 | val 0.78683
  Epoch 011 - train 0.53954 | val 0.80140
  Classification -> best τ=0.545 (val F1=0.2603)
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.58703 | val 0.90025
  Epoch 011 - train 0.56130 | val 0.97303
  Classification -> best τ=0.525 (val F1=0.1715)
  Directional -> Accuracy: 0.5909, MCC: 0.1445, F1: 0.7379

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.51091 | val 1.28669
  Epoch 012 - train 0.52834 | val 1.35787
  Classification -> best τ=0.440 (val F1=0.2439)
  Directional -> Accuracy: 0.6905, MCC: 0.3838, F1: 0.7347

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.51808 | val 1.17241
  Epoch 011 - train 0.53375 | val 1.33615
  Classification -> best τ=0.465 (val F1=0.2110)
  Directional -> Accuracy: 0.4286, MCC: -0.1309, F1: 0.4667

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.51049 | val 0.80855
  Epoch 011 - train 0.47638 | val 0.78835
  Classification -> best τ=0.535 (val F1=0.4277)
  Directional -> Accuracy: 0.4130, MCC: -0.0537, F1: 0.2703

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.58427 | val 0.70986
  Epoch 020 - train 0.46571 | val 0.62694
  Epoch 030 - train 0.41785 | val 0.61468
  Classification -> best τ=0.250 (val F1=0.4201)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.53877 | val 1.32030
  Epoch 012 - train 0.49811 | val 1.30294
  Classification -> best τ=0.435 (val F1=0.2769)
  Directional -> Accuracy: 0.4865, MCC: 0.0000, F1: 0.6545

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.57457 | val 0.69487
  Epoch 018 - train 0.54420 | val 0.83154
  Classification -> best τ=0.480 (val F1=0.4080)
  Directional -> Accuracy: 0.5778, MCC: 0.1877, F1: 0.4571

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.49321 | val 0.77749
  Epoch 011 - train 0.48352 | val 0.78894
  Classification -> best τ=0.530 (val F1=0.1667)
  Directional -> Accuracy: 0.4286, MCC: -0.0468, F1: 0.1429

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.55865 | val 0.74251
  Epoch 020 - train 0.45157 | val 0.84750
  Epoch 024 - train 0.42441 | val 0.90510
  Classification -> best τ=0.665 (val F1=0.1730)
  Directional -> Accuracy: 0.5833, MCC: 0.2739, F1: 0.6000

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.59324 | val 0.77331
  Epoch 012 - train 0.57209 | val 0.79961
  Classification -> best τ=0.595 (val F1=0.1647)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.47922 | val 1.28272
  Epoch 011 - train 0.49322 | val 1.42433
  Classification -> best τ=0.530 (val F1=0.2195)
  Directional -> Accuracy: 0.5179, MCC: 0.0519, F1: 0.5846

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.62910 | val 0.80230
  Epoch 016 - train 0.56908 | val 0.80008
  Classification -> best τ=0.350 (val F1=0.2369)
  Directional -> Accuracy: 0.5094, MCC: 0.0000, F1: 0.6750

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.54240 | val 0.81740
  Epoch 011 - train 0.56009 | val 0.84030
  Classification -> best τ=0.520 (val F1=0.1459)
  Directional -> Accuracy: 0.5273, MCC: 0.0000, F1: 0.6905

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.58496 | val 0.66557

[I 2026-02-22 11:38:14,648] Trial 146 finished with value: 0.27199430400042096 and parameters: {'feature_set': 'sector', 'model_type': 'BiGRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.30000000000000004, 'batch_size': 64, 'learning_rate': 0.0033169854066852724, 'weight_decay': 5.842931591811605e-05, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 1.0572496975709986, 'early_stopping_min_delta': 0.0004462777129483656}. Best is trial 112 with value: 0.2833506688525635.

  Epoch 018 - train 0.52085 | val 0.80523
  Classification -> best τ=0.440 (val F1=0.3923)
  Directional -> Accuracy: 0.5833, MCC: 0.1710, F1: 0.4444

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.27199430400042096
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.59200 | val 0.77657
  Epoch 017 - train 0.56121 | val 0.82025
  Classification -> best τ=0.665 (val F1=0.2919)
  Directional -> Accuracy: 0.6053, MCC: 0.2017, F1: 0.5588

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.55622 | val 0.75606
  Epoch 014 - train 0.47823 | val 0.94900
  Classification -> best τ=0.480 (val F1=0.2829)
  Directional -> Accuracy: 0.6222, MCC: 0.1941, F1: 0.7385

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.60620 | val 0.80538
  Epoch 013 - train 0.57314 | val 0.94927
  Classification -> best τ=0.565 (val F1=0.2861)
  Directional -> Accuracy: 0.4783, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.57769 | val 0.88931
  Epoch 012 - train 0.60008 | val 0.72541
  Classification -> best τ=0.485 (val F1=0.1422)
  Directional -> Accuracy: 0.5135, MCC: -0.1537, F1: 0.6786

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.56589 | val 0.66557
  Epoch 020 - train 0.43712 | val 0.78421
  Epoch 022 - train 0.38234 | val 0.84844
  Classification -> best τ=0.620 (val F1=0.2742)
  Directional -> Accuracy: 0.6400, MCC: 0.3158, F1: 0.5714

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.56953 | val 0.81383
  Epoch 011 - train 0.56830 | val 0.79517
  Classification -> best τ=0.520 (val F1=0.0595)
  Directional -> Accuracy: 0.5217, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.62068 | val 1.30914
  Epoch 011 - train 0.62526 | val 1.20496
  Classification -> best τ=0.485 (val F1=0.1892)
  Directional -> Accuracy: 0.5147, MCC: 0.1667, F1: 0.5823

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.55084 | val 0.69813
  Epoch 018 - train 0.42344 | val 0.95409
  Classification -> best τ=0.315 (val F1=0.2566)
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.57590 | val 0.93069
  Epoch 015 - train 0.51858 | val 1.64894
  Classification -> best τ=0.430 (val F1=0.2779)
  Directional -> Accuracy: 0.5208, MCC: 0.0639, F1: 0.5306

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.56402 | val 0.76396
  Epoch 013 - train 0.53130 | val 0.80089
  Classification -> best τ=0.465 (val F1=0.1829)
  Directional -> Accuracy: 0.5072, MCC: 0.0562, F1: 0.5278

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.61398 | val 0.88948
  Epoch 011 - train 0.60528 | val 0.89191
  Classification -> best τ=0.545 (val F1=0.2534)
  Directional -> Accuracy: 0.5918, MCC: 0.1804, F1: 0.2308

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.62072 | val 0.92870
  Epoch 012 - train 0.59880 | val 0.97436
  Classification -> best τ=0.505 (val F1=0.0591)
  Directional -> Accuracy: 0.6491, MCC: 0.3140, F1: 0.6000

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.52829 | val 0.86161
  Epoch 011 - train 0.53672 | val 0.85265
  Classification -> best τ=0.495 (val F1=0.1370)
  Directional -> Accuracy: 0.4524, MCC: -0.1353, F1: 0.3030

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.58484 | val 0.98140
  Epoch 014 - train 0.54744 | val 0.93815
  Classification -> best τ=0.545 (val F1=0.3378)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.58182 | val 0.67955
  Epoch 019 - train 0.49339 | val 0.81043
  Classification -> best τ=0.560 (val F1=0.3000)
  Directional -> Accuracy: 0.4510, MCC: -0.0728, F1: 0.5000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.59235 | val 0.88156
  Epoch 012 - train 0.59039 | val 0.95462
  Classification -> best τ=0.375 (val F1=0.1823)
  Directional -> Accuracy: 0.5217, MCC: -0.0237, F1: 0.6667

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.60365 | val 0.89108
  Epoch 011 - train 0.60705 | val 0.91801
  Classification -> best τ=0.485 (val F1=0.1905)
  Directional -> Accuracy: 0.4655, MCC: -0.0711, F1: 0.5231

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.59558 | val 0.93133
  Epoch 011 - train 0.59678 | val 0.95476
  Classification -> best τ=0.550 (val F1=0.1310)
  Directional -> Accuracy: 0.4000, MCC: -0.1961, F1: 0.4444

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.59731 | val 1.18372
  Epoch 013 - train 0.55089 | val 1.29982
  Classification -> best τ=0.305 (val F1=0.3140)
  Directional -> Accuracy: 0.5781, MCC: 0.0000, F1: 0.7327

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.60750 | val 0.76128
  Epoch 015 - train 0.54899 | val 0.99788
  Classification -> best τ=0.480 (val F1=0.2651)
  Directional -> Accuracy: 0.4054, MCC: -0.1563, F1: 0.2414

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.53513 | val 0.77473
  Epoch 011 - train 0.53152 | val 0.79646
  Classification -> best τ=0.565 (val F1=0.1978)
  Directional -> Accuracy: 0.4255, MCC: 0.1661, F1: 0.1290

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.60980 | val 0.82484
  Epoch 011 - train 0.62424 | val 0.82933
  Classification -> best τ=0.500 (val F1=0.2216)
  Directional -> Accuracy: 0.4923, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.59625 | val 0.70766
  Epoch 020 - train 0.56870 | val 0.94217
  Epoch 023 - train 0.49322 | val 1.00760
  Classification -> best τ=0.370 (val F1=0.4564)
  Directional -> Accuracy: 0.5263, MCC: 0.0080, F1: 0.6197

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.59074 | val 0.71617
  Epoch 011 - train 0.56471 | val 0.72223
  Classification -> best τ=0.465 (val F1=0.1254)
  Directional -> Accuracy: 0.4769, MCC: 0.0000, F1: 0.6458

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.55338 | val 0.86251
  Epoch 015 - train 0.48097 | val 1.22332
  Classification -> best τ=0.500 (val F1=0.4550)
  Directional -> Accuracy: 0.5818, MCC: 0.1913, F1: 0.5490

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.55009 | val 0.75618
  Epoch 013 - train 0.51650 | val 0.75585
  Classification -> best τ=0.530 (val F1=0.4328)
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.5938

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.61106 | val 0.74652
  Epoch 012 - train 0.55866 | val 0.75523
  Classification -> best τ=0.600 (val F1=0.1936)
  Directional -> Accuracy: 0.5000, MCC: 0.1005, F1: 0.3636

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.57511 | val 0.73494
  Epoch 013 - train 0.55221 | val 0.76940
  Classification -> best τ=0.480 (val F1=0.2816)
  Directional -> Accuracy: 0.4464, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.59366 | val 0.80802
  Epoch 014 - train 0.52656 | val 0.77937
  Classification -> best τ=0.490 (val F1=0.3477)
  Directional -> Accuracy: 0.5000, MCC: -0.0205, F1: 0.5652

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.60188 | val 0.88833
  Epoch 011 - train 0.62818 | val 0.92077
  Classification -> best τ=0.490 (val F1=0.2814)
  Directional -> Accuracy: 0.4762, MCC: -0.0674, F1: 0.3529

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.57930 | val 1.16739
  Epoch 012 - train 0.54089 | val 1.31593
  Classification -> best τ=0.420 (val F1=0.2357)
  Directional -> Accuracy: 0.5476, MCC: 0.0000, F1: 0.7077

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.52880 | val 0.90032
  Epoch 013 - train 0.52469 | val 1.10176
  Classification -> best τ=0.465 (val F1=0.3461)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.59136 | val 0.85943
  Epoch 014 - train 0.54896 | val 1.08591
  Classification -> best τ=0.360 (val F1=0.3593)
  Directional -> Accuracy: 0.5556, MCC: 0.1323, F1: 0.5429

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.58801 | val 1.10061
  Epoch 011 - train 0.56290 | val 1.17528
  Classification -> best τ=0.535 (val F1=0.0112)
  Directional -> Accuracy: 0.5349, MCC: 0.0670, F1: 0.3750

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.58632 | val 0.80055
  Epoch 011 - train 0.59135 | val 0.84211
  Classification -> best τ=0.455 (val F1=0.3001)
  Directional -> Accuracy: 0.5758, MCC: 0.0569, F1: 0.7083

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.52406 | val 0.96324
  Epoch 012 - train 0.48774 | val 1.03447
  Classification -> best τ=0.515 (val F1=0.1970)
  Directional -> Accuracy: 0.6190, MCC: 0.2571, F1: 0.5789

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.51928 | val 0.94066
  Epoch 011 - train 0.50912 | val 0.99860
  Classification -> best τ=0.465 (val F1=0.2110)
  Directional -> Accuracy: 0.5179, MCC: 0.0998, F1: 0.6197

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.53526 | val 0.80810
  Epoch 011 - train 0.51922 | val 0.82708
  Classification -> best τ=0.495 (val F1=0.3749)
  Directional -> Accuracy: 0.4348, MCC: 0.0460, F1: 0.2353

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.55006 | val 0.61821
  Epoch 020 - train 0.52419 | val 0.59792
  Epoch 030 - train 0.48363 | val 0.59683
  Classification -> best τ=0.320 (val F1=0.4556)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.58068 | val 1.71954
  Epoch 012 - train 0.50844 | val 1.59382
  Classification -> best τ=0.420 (val F1=0.3395)
  Directional -> Accuracy: 0.4865, MCC: 0.0000, F1: 0.6545

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.57684 | val 0.70565
  Epoch 019 - train 0.52576 | val 0.77523
  Classification -> best τ=0.330 (val F1=0.1512)
  Directional -> Accuracy: 0.5111, MCC: 0.0000, F1: 0.6765

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.54355 | val 0.76649
  Epoch 011 - train 0.52839 | val 0.78046
  Classification -> best τ=0.500 (val F1=0.2381)
  Directional -> Accuracy: 0.4524, MCC: -0.0446, F1: 0.3784

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.58060 | val 0.69181
  Epoch 020 - train 0.45652 | val 0.58652
  Epoch 030 - train 0.36378 | val 0.95557
  Classification -> best τ=0.595 (val F1=0.4542)
  Directional -> Accuracy: 0.4167, MCC: 0.0778, F1: 0.5484

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.58836 | val 0.71159
  Epoch 017 - train 0.54661 | val 0.84670
  Classification -> best τ=0.570 (val F1=0.1811)
  Directional -> Accuracy: 0.5455, MCC: 0.2064, F1: 0.3590

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.54631 | val 1.47544
  Epoch 011 - train 0.58411 | val 1.46665
  Classification -> best τ=0.485 (val F1=0.3006)
  Directional -> Accuracy: 0.5179, MCC: 0.0357, F1: 0.5091

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.62489 | val 0.83946
  Epoch 012 - train 0.61535 | val 0.89071
  Classification -> best τ=0.540 (val F1=0.3023)
  Directional -> Accuracy: 0.5660, MCC: 0.1310, F1: 0.6102

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.58990 | val 1.11007
  Epoch 011 - train 0.59808 | val 1.07386
  Classification -> best τ=0.510 (val F1=0.2257)
  Directional -> Accuracy: 0.4727, MCC: -0.0598, F1: 0.5085

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.62712 | val 0.65722
  Epoch 020 - train 0.52901 | val 0.68911

[I 2026-02-22 11:39:41,703] Trial 147 finished with value: 0.2590867827939621 and parameters: {'feature_set': 'sector', 'model_type': 'BiGRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.4, 'batch_size': 64, 'learning_rate': 0.003399022784017942, 'weight_decay': 6.906652974709799e-05, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 1.069345112418614, 'early_stopping_min_delta': 0.0004429534421253679}. Best is trial 112 with value: 0.2833506688525635.

  Epoch 025 - train 0.49052 | val 0.85509
  Classification -> best τ=0.505 (val F1=0.3455)
  Directional -> Accuracy: 0.6333, MCC: 0.2648, F1: 0.6071

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2590867827939621
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.58435 | val 0.73270
  Epoch 016 - train 0.55652 | val 0.78167
  Classification -> best τ=0.580 (val F1=0.2627)
  Directional -> Accuracy: 0.6184, MCC: 0.2225, F1: 0.5538

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.49556 | val 0.81177
  Epoch 013 - train 0.46785 | val 0.83398
  Classification -> best τ=0.490 (val F1=0.2523)
  Directional -> Accuracy: 0.4889, MCC: 0.0165, F1: 0.4651

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.61287 | val 0.86587
  Epoch 012 - train 0.55571 | val 0.94201
  Classification -> best τ=0.590 (val F1=0.2793)
  Directional -> Accuracy: 0.4565, MCC: -0.0996, F1: 0.0741

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.56396 | val 0.85445
  Epoch 011 - train 0.57213 | val 0.81684
  Classification -> best τ=0.425 (val F1=0.1725)
  Directional -> Accuracy: 0.6081, MCC: 0.2011, F1: 0.6813

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.53177 | val 0.66089
  Epoch 016 - train 0.47372 | val 0.72809
  Classification -> best τ=0.510 (val F1=0.5167)
  Directional -> Accuracy: 0.6400, MCC: 0.3158, F1: 0.5714

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.57015 | val 0.85225
  Epoch 012 - train 0.52972 | val 0.80483
  Classification -> best τ=0.500 (val F1=0.1808)
  Directional -> Accuracy: 0.4783, MCC: 0.0000, F1: 0.6471

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.63288 | val 0.82937
  Epoch 011 - train 0.60895 | val 0.87435
  Classification -> best τ=0.495 (val F1=0.1347)
  Directional -> Accuracy: 0.5441, MCC: 0.0418, F1: 0.4151

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.54804 | val 1.04375
  Epoch 020 - train 0.29561 | val 1.58200
  Epoch 022 - train 0.38106 | val 1.78688
  Classification -> best τ=0.540 (val F1=0.4215)
  Directional -> Accuracy: 0.5000, MCC: 0.0595, F1: 0.5532

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.56439 | val 0.79908
  Epoch 017 - train 0.50245 | val 1.61728
  Classification -> best τ=0.505 (val F1=0.3962)
  Directional -> Accuracy: 0.5833, MCC: 0.1534, F1: 0.5238

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.53573 | val 0.73592
  Epoch 015 - train 0.46643 | val 0.75673
  Classification -> best τ=0.540 (val F1=0.3268)
  Directional -> Accuracy: 0.4348, MCC: -0.1345, F1: 0.3810

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.58658 | val 0.75663
  Epoch 013 - train 0.54076 | val 0.86312
  Classification -> best τ=0.490 (val F1=0.1687)
  Directional -> Accuracy: 0.5102, MCC: 0.0268, F1: 0.5000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.57815 | val 1.08774
  Epoch 011 - train 0.58407 | val 1.11012
  Classification -> best τ=0.445 (val F1=0.0025)
  Directional -> Accuracy: 0.6316, MCC: 0.2799, F1: 0.6957

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.48862 | val 1.02121
  Epoch 011 - train 0.49865 | val 1.03819
  Classification -> best τ=0.515 (val F1=0.0512)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.6230

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.60489 | val 0.66394
  Epoch 020 - train 0.48555 | val 0.99018
  Epoch 021 - train 0.46458 | val 0.96645
  Classification -> best τ=0.500 (val F1=0.4623)
  Directional -> Accuracy: 0.4667, MCC: -0.1111, F1: 0.1111

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.55768 | val 0.76506
  Epoch 012 - train 0.51461 | val 0.81869
  Classification -> best τ=0.465 (val F1=0.2298)
  Directional -> Accuracy: 0.5882, MCC: 0.1753, F1: 0.2222

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.55742 | val 1.00176
  Epoch 012 - train 0.51947 | val 1.05946
  Classification -> best τ=0.390 (val F1=0.2795)
  Directional -> Accuracy: 0.5507, MCC: 0.0713, F1: 0.6804

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.58013 | val 0.90650
  Epoch 011 - train 0.59927 | val 0.95482
  Classification -> best τ=0.510 (val F1=0.1905)
  Directional -> Accuracy: 0.5517, MCC: 0.1518, F1: 0.5667

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.59713 | val 1.10463
  Epoch 011 - train 0.58834 | val 1.11433
  Classification -> best τ=0.495 (val F1=0.0714)
  Directional -> Accuracy: 0.6000, MCC: 0.0000, F1: 0.7500

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.59320 | val 1.19451
  Epoch 011 - train 0.57432 | val 1.14082
  Classification -> best τ=0.415 (val F1=0.3689)
  Directional -> Accuracy: 0.5781, MCC: 0.0000, F1: 0.7327

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.56936 | val 0.92837
  Epoch 012 - train 0.54514 | val 0.97598
  Classification -> best τ=0.460 (val F1=0.1735)
  Directional -> Accuracy: 0.4324, MCC: -0.0821, F1: 0.1600

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.57566 | val 0.95606
  Epoch 011 - train 0.52293 | val 1.13408
  Classification -> best τ=0.550 (val F1=0.2861)
  Directional -> Accuracy: 0.4255, MCC: -0.0182, F1: 0.3077

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.59377 | val 0.77634
  Epoch 016 - train 0.48885 | val 0.96705
  Classification -> best τ=0.460 (val F1=0.2830)
  Directional -> Accuracy: 0.5077, MCC: 0.0699, F1: 0.1111

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.59734 | val 0.71629
  Epoch 013 - train 0.57815 | val 0.80338
  Classification -> best τ=0.750 (val F1=0.3144)
  Directional -> Accuracy: 0.4211, MCC: -0.1009, F1: 0.1081

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.53827 | val 0.76362
  Epoch 012 - train 0.53703 | val 0.76682
  Classification -> best τ=0.445 (val F1=0.1772)
  Directional -> Accuracy: 0.5077, MCC: 0.0764, F1: 0.6364

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.51937 | val 0.96715
  Epoch 015 - train 0.47140 | val 1.49197
  Classification -> best τ=0.425 (val F1=0.4723)
  Directional -> Accuracy: 0.6000, MCC: 0.2476, F1: 0.5417

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.60447 | val 0.69505
  Epoch 012 - train 0.56318 | val 0.77772
  Classification -> best τ=0.515 (val F1=0.4328)
  Directional -> Accuracy: 0.5111, MCC: 0.2670, F1: 0.6333

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.56400 | val 0.68812
  Epoch 020 - train 0.50180 | val 0.73401
  Epoch 024 - train 0.46922 | val 0.70906
  Classification -> best τ=0.595 (val F1=0.3712)
  Directional -> Accuracy: 0.6429, MCC: 0.2887, F1: 0.6667

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.58397 | val 0.98010
  Epoch 013 - train 0.54163 | val 1.17006
  Classification -> best τ=0.430 (val F1=0.1997)
  Directional -> Accuracy: 0.5893, MCC: 0.2939, F1: 0.4651

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.52077 | val 1.09183
  Epoch 011 - train 0.52120 | val 0.92196
  Classification -> best τ=0.485 (val F1=0.0836)
  Directional -> Accuracy: 0.6250, MCC: 0.3148, F1: 0.7458

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.57569 | val 1.01868
  Epoch 013 - train 0.53307 | val 1.23311
  Classification -> best τ=0.560 (val F1=0.3656)
  Directional -> Accuracy: 0.5000, MCC: 0.0092, F1: 0.5333

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.56460 | val 0.97650
  Epoch 011 - train 0.57176 | val 1.05004
  Classification -> best τ=0.460 (val F1=0.1286)
  Directional -> Accuracy: 0.4286, MCC: -0.1090, F1: 0.1429

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.52746 | val 0.82030
  Epoch 013 - train 0.50994 | val 1.00313
  Classification -> best τ=0.425 (val F1=0.3502)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.54118 | val 0.84488
  Epoch 013 - train 0.51436 | val 0.86517
  Classification -> best τ=0.505 (val F1=0.3278)
  Directional -> Accuracy: 0.4444, MCC: 0.0000, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.53525 | val 0.76660
  Epoch 011 - train 0.54878 | val 0.80224
  Classification -> best τ=0.555 (val F1=0.3227)
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.59472 | val 0.95056
  Epoch 011 - train 0.59731 | val 0.95963
  Classification -> best τ=0.460 (val F1=0.2117)
  Directional -> Accuracy: 0.5758, MCC: 0.0000, F1: 0.7308

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.49135 | val 1.83149
  Epoch 012 - train 0.49626 | val 1.70064
  Classification -> best τ=0.490 (val F1=0.2439)
  Directional -> Accuracy: 0.6905, MCC: 0.3814, F1: 0.6977

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.51300 | val 1.31811
  Epoch 011 - train 0.52648 | val 1.33742
  Classification -> best τ=0.465 (val F1=0.2677)
  Directional -> Accuracy: 0.5714, MCC: 0.1807, F1: 0.6250

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.47706 | val 0.74258
  Epoch 016 - train 0.40201 | val 0.79502
  Classification -> best τ=0.605 (val F1=0.2185)
  Directional -> Accuracy: 0.3913, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.52745 | val 0.61603
  Epoch 020 - train 0.49244 | val 0.65126
  Epoch 030 - train 0.44202 | val 0.79361
  Classification -> best τ=0.295 (val F1=0.4556)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.55602 | val 1.17117
  Epoch 012 - train 0.50953 | val 1.18412
  Classification -> best τ=0.435 (val F1=0.2998)
  Directional -> Accuracy: 0.4865, MCC: 0.0000, F1: 0.6545

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.59981 | val 0.72547
  Epoch 011 - train 0.62545 | val 0.73945
  Classification -> best τ=0.535 (val F1=0.4348)
  Directional -> Accuracy: 0.5556, MCC: 0.1425, F1: 0.4118

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.50629 | val 0.65029
  Epoch 019 - train 0.36532 | val 0.93971
  Classification -> best τ=0.625 (val F1=0.4523)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.2581

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.56160 | val 0.62116
  Epoch 017 - train 0.42826 | val 0.61708
  Classification -> best τ=0.590 (val F1=0.5261)
  Directional -> Accuracy: 0.4167, MCC: 0.0325, F1: 0.5333

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.57660 | val 0.82651
  Epoch 013 - train 0.56420 | val 0.85355
  Classification -> best τ=0.490 (val F1=0.2291)
  Directional -> Accuracy: 0.5636, MCC: 0.1023, F1: 0.7073

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.53064 | val 1.09918
  Epoch 011 - train 0.51422 | val 1.24195
  Classification -> best τ=0.460 (val F1=0.3249)
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.6506

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.57743 | val 0.84623
  Epoch 012 - train 0.59463 | val 0.86698
  Classification -> best τ=0.405 (val F1=0.2309)
  Directional -> Accuracy: 0.5094, MCC: 0.0000, F1: 0.6750

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.55958 | val 1.18977
  Epoch 012 - train 0.52797 | val 1.24040
  Classification -> best τ=0.670 (val F1=0.1210)
  Directional -> Accuracy: 0.4727, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.58736 | val 0.75173

[I 2026-02-22 11:41:05,664] Trial 148 finished with value: 0.27880464342892103 and parameters: {'feature_set': 'sector', 'model_type': 'BiGRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.30000000000000004, 'batch_size': 64, 'learning_rate': 0.004063429958763796, 'weight_decay': 5.0251815963927885e-05, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 1.116695785463312, 'early_stopping_min_delta': 0.00024119265800737923}. Best is trial 112 with value: 0.2833506688525635.

  Epoch 019 - train 0.49443 | val 0.81714
  Classification -> best τ=0.525 (val F1=0.3093)
  Directional -> Accuracy: 0.6167, MCC: 0.2402, F1: 0.5106

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.27880464342892103
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.59177 | val 0.93458
  Epoch 011 - train 0.57111 | val 0.99920
  Classification -> best τ=0.510 (val F1=0.1718)
  Directional -> Accuracy: 0.5526, MCC: 0.1468, F1: 0.5952

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.42613 | val 1.61326
  Epoch 011 - train 0.46383 | val 1.66278
  Classification -> best τ=0.400 (val F1=0.2590)
  Directional -> Accuracy: 0.5778, MCC: 0.0000, F1: 0.7324

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.52507 | val 1.59854
  Epoch 011 - train 0.53792 | val 1.68126
  Classification -> best τ=0.665 (val F1=0.2559)
  Directional -> Accuracy: 0.4783, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.60302 | val 0.77680
  Epoch 019 - train 0.43937 | val 0.73066
  Classification -> best τ=0.795 (val F1=0.1079)
  Directional -> Accuracy: 0.4865, MCC: 0.0752, F1: 0.1739

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.50926 | val 0.75156
  Epoch 012 - train 0.43693 | val 0.79998
  Classification -> best τ=0.640 (val F1=0.4556)
  Directional -> Accuracy: 0.6000, MCC: 0.2300, F1: 0.5238

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.49664 | val 0.79772
  Epoch 015 - train 0.35882 | val 0.66449
  Classification -> best τ=0.490 (val F1=0.4885)
  Directional -> Accuracy: 0.5217, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.57959 | val 1.41589
  Epoch 011 - train 0.56477 | val 1.34634
  Classification -> best τ=0.380 (val F1=0.2473)
  Directional -> Accuracy: 0.4853, MCC: 0.0781, F1: 0.5455

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.45095 | val 4.02278
  Epoch 011 - train 0.53057 | val 2.87560
  Classification -> best τ=0.535 (val F1=0.3059)
  Directional -> Accuracy: 0.5238, MCC: -0.1936, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.54401 | val 1.76799
  Epoch 011 - train 0.49724 | val 1.40618
  Classification -> best τ=0.550 (val F1=0.3431)
  Directional -> Accuracy: 0.5833, MCC: 0.1449, F1: 0.5000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.48267 | val 1.58640
  Epoch 011 - train 0.47808 | val 1.41577
  Classification -> best τ=0.345 (val F1=0.2651)
  Directional -> Accuracy: 0.4203, MCC: 0.0000, F1: 0.5918

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.55000 | val 1.30836
  Epoch 016 - train 0.52011 | val 1.12297
  Classification -> best τ=0.540 (val F1=0.2670)
  Directional -> Accuracy: 0.5714, MCC: 0.1044, F1: 0.3636

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.62100 | val 1.57290
  Epoch 011 - train 0.53972 | val 1.53308
  Classification -> best τ=0.490 (val F1=0.1198)
  Directional -> Accuracy: 0.5965, MCC: 0.1923, F1: 0.6230

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.45073 | val 2.42552
  Epoch 011 - train 0.41863 | val 2.66378
  Classification -> best τ=0.360 (val F1=0.0548)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.6230

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.57084 | val 0.85851
  Epoch 012 - train 0.48464 | val 0.81912
  Classification -> best τ=0.400 (val F1=0.3477)
  Directional -> Accuracy: 0.5333, MCC: 0.0727, F1: 0.4167

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.53630 | val 0.73246
  Epoch 013 - train 0.46205 | val 0.82149
  Classification -> best τ=0.610 (val F1=0.3390)
  Directional -> Accuracy: 0.5294, MCC: -0.0061, F1: 0.2500

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.58054 | val 1.15467
  Epoch 011 - train 0.50577 | val 1.16931
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5362, MCC: 0.0000, F1: 0.6981

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.54519 | val 1.25298
  Epoch 011 - train 0.52154 | val 1.35374
  Classification -> best τ=0.460 (val F1=0.0057)
  Directional -> Accuracy: 0.5345, MCC: 0.1252, F1: 0.5424

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.53504 | val 1.12508
  Epoch 011 - train 0.51511 | val 1.13051
  Classification -> best τ=0.365 (val F1=0.2004)
  Directional -> Accuracy: 0.5867, MCC: 0.0000, F1: 0.7304

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.54668 | val 0.76754
  Epoch 015 - train 0.42389 | val 0.70605
  Classification -> best τ=0.240 (val F1=0.3421)
  Directional -> Accuracy: 0.5781, MCC: 0.1486, F1: 0.6197

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.50941 | val 1.78775
  Epoch 011 - train 0.48109 | val 1.99384
  Classification -> best τ=0.530 (val F1=0.2403)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.49468 | val 1.83575
  Epoch 011 - train 0.45596 | val 2.25093
  Classification -> best τ=0.465 (val F1=0.1033)
  Directional -> Accuracy: 0.3830, MCC: -0.1251, F1: 0.2564

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.56995 | val 0.95373
  Epoch 012 - train 0.48473 | val 0.94620
  Classification -> best τ=0.415 (val F1=0.2037)
  Directional -> Accuracy: 0.5077, MCC: 0.0000, F1: 0.6735

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.52482 | val 1.20146
  Epoch 011 - train 0.50656 | val 1.30517
  Classification -> best τ=0.455 (val F1=0.3938)
  Directional -> Accuracy: 0.5965, MCC: 0.1518, F1: 0.7160

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.59330 | val 0.88707
  Epoch 011 - train 0.55620 | val 0.93867
  Classification -> best τ=0.470 (val F1=0.1874)
  Directional -> Accuracy: 0.5846, MCC: 0.1632, F1: 0.4906

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.50852 | val 2.01287
  Epoch 012 - train 0.45757 | val 1.88276
  Classification -> best τ=0.635 (val F1=0.5312)
  Directional -> Accuracy: 0.5273, MCC: 0.1463, F1: 0.3500

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.48941 | val 2.95043
  Epoch 011 - train 0.51566 | val 2.54846
  Classification -> best τ=0.600 (val F1=0.2241)
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.5938

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.54188 | val 1.11198
  Epoch 011 - train 0.58592 | val 1.04768
  Classification -> best τ=0.465 (val F1=0.1964)
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.7273

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.52235 | val 0.81026
  Epoch 011 - train 0.48825 | val 0.84742
  Classification -> best τ=0.345 (val F1=0.2011)
  Directional -> Accuracy: 0.4821, MCC: 0.1728, F1: 0.1212

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.46769 | val 0.98621
  Epoch 015 - train 0.35946 | val 1.22470
  Classification -> best τ=0.630 (val F1=0.3671)
  Directional -> Accuracy: 0.5250, MCC: 0.0453, F1: 0.5581

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.49249 | val 1.16157
  Epoch 011 - train 0.49462 | val 1.43479
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4762, MCC: 0.0000, F1: 0.6452

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.56930 | val 1.41552
  Epoch 011 - train 0.54839 | val 1.41181
  Classification -> best τ=0.575 (val F1=0.1846)
  Directional -> Accuracy: 0.4762, MCC: 0.1419, F1: 0.0833

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.49735 | val 1.04815
  Epoch 011 - train 0.46022 | val 1.05185
  Classification -> best τ=0.420 (val F1=0.2509)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.52398 | val 1.04138
  Epoch 011 - train 0.54786 | val 1.11284
  Classification -> best τ=0.510 (val F1=0.3239)
  Directional -> Accuracy: 0.4861, MCC: 0.0845, F1: 0.2449

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.52935 | val 1.05659
  Epoch 011 - train 0.47990 | val 1.14771
  Classification -> best τ=0.500 (val F1=0.1874)
  Directional -> Accuracy: 0.4651, MCC: -0.1579, F1: 0.6349

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.58118 | val 1.12954
  Epoch 011 - train 0.52358 | val 1.24086
  Classification -> best τ=0.375 (val F1=0.2778)
  Directional -> Accuracy: 0.5758, MCC: 0.0000, F1: 0.7308

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.45668 | val 3.20467
  Epoch 011 - train 0.45887 | val 3.29425
  Classification -> best τ=0.420 (val F1=0.3001)
  Directional -> Accuracy: 0.6190, MCC: 0.2659, F1: 0.7143

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.50520 | val 1.06419
  Epoch 011 - train 0.46537 | val 1.13471
  Classification -> best τ=0.425 (val F1=0.3039)
  Directional -> Accuracy: 0.5714, MCC: 0.1807, F1: 0.6250

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.45730 | val 1.20439
  Epoch 011 - train 0.42022 | val 1.32720
  Classification -> best τ=0.615 (val F1=0.2254)
  Directional -> Accuracy: 0.3696, MCC: -0.1859, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.50645 | val 1.87383
  Epoch 014 - train 0.48643 | val 1.50779
  Classification -> best τ=0.875 (val F1=0.4306)
  Directional -> Accuracy: 0.3958, MCC: -0.0195, F1: 0.4912

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.48102 | val 1.64007
  Epoch 011 - train 0.44806 | val 1.75625
  Classification -> best τ=0.280 (val F1=0.3577)
  Directional -> Accuracy: 0.4865, MCC: 0.0000, F1: 0.6545

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.55291 | val 0.83704
  Epoch 013 - train 0.50505 | val 1.17153
  Classification -> best τ=0.555 (val F1=0.2712)
  Directional -> Accuracy: 0.5111, MCC: 0.0000, F1: 0.6765

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.37396 | val 1.56942
  Epoch 012 - train 0.36286 | val 1.52907
  Classification -> best τ=0.605 (val F1=0.4971)
  Directional -> Accuracy: 0.6190, MCC: 0.2222, F1: 0.6667

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.50449 | val 0.84809
  Epoch 014 - train 0.39378 | val 0.77183
  Classification -> best τ=0.665 (val F1=0.2902)
  Directional -> Accuracy: 0.5625, MCC: 0.3200, F1: 0.6182

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.66341 | val 1.09005
  Epoch 011 - train 0.58618 | val 1.06047
  Classification -> best τ=0.495 (val F1=0.2036)
  Directional -> Accuracy: 0.4545, MCC: -0.0256, F1: 0.1176

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.46984 | val 2.19956
  Epoch 011 - train 0.43762 | val 2.04696
  Classification -> best τ=0.665 (val F1=0.2793)
  Directional -> Accuracy: 0.5893, MCC: 0.2918, F1: 0.6933

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.58137 | val 0.93137
  Epoch 011 - train 0.54381 | val 0.92504
  Classification -> best τ=0.525 (val F1=0.2155)
  Directional -> Accuracy: 0.5660, MCC: 0.1343, F1: 0.6349

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.49041 | val 3.65855
  Epoch 011 - train 0.49650 | val 3.70935
  Classification -> best τ=0.865 (val F1=0.0580)
  Directional -> Accuracy: 0.4545, MCC: -0.0933, F1: 0.0625

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.58841 | val 0.72116

[I 2026-02-22 11:43:30,033] Trial 149 finished with value: 0.2554981093564321 and parameters: {'feature_set': 'sector', 'model_type': 'BiGRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.30000000000000004, 'batch_size': 16, 'learning_rate': 0.0026510390051863427, 'weight_decay': 5.340663553973368e-05, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 1.1292197939286883, 'early_stopping_min_delta': 0.00047807879842623}. Best is trial 112 with value: 0.2833506688525635.

  Epoch 016 - train 0.44708 | val 0.88485
  Classification -> best τ=0.430 (val F1=0.3817)
  Directional -> Accuracy: 0.6500, MCC: 0.3066, F1: 0.5714

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2554981093564321
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.60170 | val 0.77013
  Epoch 016 - train 0.54314 | val 0.75531
  Classification -> best τ=0.600 (val F1=0.1989)
  Directional -> Accuracy: 0.6104, MCC: 0.2143, F1: 0.5714

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.51551 | val 0.85487
  Epoch 011 - train 0.49569 | val 0.86749
  Classification -> best τ=0.430 (val F1=0.2707)
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.7222

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.56806 | val 1.07704
  Epoch 012 - train 0.57139 | val 1.23459
  Classification -> best τ=0.455 (val F1=0.1931)
  Directional -> Accuracy: 0.5319, MCC: 0.0333, F1: 0.6452

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.60041 | val 0.87817
  Epoch 011 - train 0.58384 | val 0.98427
  Classification -> best τ=0.515 (val F1=0.0901)
  Directional -> Accuracy: 0.4667, MCC: -0.0561, F1: 0.4595

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.51400 | val 1.82688
  Epoch 012 - train 0.53729 | val 1.55081
  Classification -> best τ=0.430 (val F1=0.3622)
  Directional -> Accuracy: 0.5294, MCC: 0.0254, F1: 0.6571

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.56708 | val 0.67923
  Epoch 019 - train 0.43525 | val 0.78110
  Classification -> best τ=0.495 (val F1=0.3397)
  Directional -> Accuracy: 0.5106, MCC: 0.0065, F1: 0.1481

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.60949 | val 0.96443
  Epoch 012 - train 0.59011 | val 0.98685
  Classification -> best τ=0.500 (val F1=0.1994)
  Directional -> Accuracy: 0.5217, MCC: 0.1376, F1: 0.5714

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.50775 | val 1.38780
  Epoch 011 - train 0.47119 | val 1.67013
  Classification -> best τ=0.500 (val F1=0.0792)
  Directional -> Accuracy: 0.4091, MCC: -0.3019, F1: 0.1333

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.58661 | val 0.87766
  Epoch 013 - train 0.57355 | val 1.06040
  Classification -> best τ=0.470 (val F1=0.2129)
  Directional -> Accuracy: 0.6531, MCC: 0.2907, F1: 0.5405

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.55710 | val 0.81530
  Epoch 012 - train 0.52510 | val 0.81325
  Classification -> best τ=0.460 (val F1=0.1552)
  Directional -> Accuracy: 0.4571, MCC: 0.0589, F1: 0.5957

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.57784 | val 1.09146
  Epoch 011 - train 0.57612 | val 1.14281
  Classification -> best τ=0.530 (val F1=0.1400)
  Directional -> Accuracy: 0.5600, MCC: 0.0933, F1: 0.3889

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.62595 | val 0.99369
  Epoch 011 - train 0.56270 | val 1.04391
  Classification -> best τ=0.485 (val F1=0.1005)
  Directional -> Accuracy: 0.5862, MCC: 0.1894, F1: 0.6571

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.51642 | val 0.89460
  Epoch 011 - train 0.50976 | val 0.95215
  Classification -> best τ=0.520 (val F1=0.2778)
  Directional -> Accuracy: 0.3721, MCC: -0.2296, F1: 0.4706

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.55153 | val 0.69072
  Epoch 014 - train 0.54055 | val 0.70196
  Classification -> best τ=0.480 (val F1=0.3886)
  Directional -> Accuracy: 0.4918, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.56861 | val 0.99636
  Epoch 011 - train 0.57942 | val 0.98434
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4615, MCC: 0.0000, F1: 0.6316

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.59692 | val 1.01821
  Epoch 012 - train 0.53282 | val 1.05797
  Classification -> best τ=0.375 (val F1=0.2927)
  Directional -> Accuracy: 0.6000, MCC: 0.2312, F1: 0.7255

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.61496 | val 1.27880
  Epoch 011 - train 0.58588 | val 1.28767
  Classification -> best τ=0.510 (val F1=0.0788)
  Directional -> Accuracy: 0.5593, MCC: 0.0577, F1: 0.6486

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.61230 | val 0.95260
  Epoch 011 - train 0.59108 | val 0.93017
  Classification -> best τ=0.430 (val F1=0.1304)
  Directional -> Accuracy: 0.5132, MCC: -0.1792, F1: 0.6667

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.57625 | val 0.70185
  Epoch 016 - train 0.51025 | val 1.09081
  Classification -> best τ=0.335 (val F1=0.2941)
  Directional -> Accuracy: 0.5538, MCC: 0.1285, F1: 0.5672

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.57860 | val 0.99723
  Epoch 012 - train 0.55158 | val 0.72094
  Classification -> best τ=0.510 (val F1=0.2119)
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.55842 | val 0.77326
  Epoch 011 - train 0.56301 | val 0.76227
  Classification -> best τ=0.485 (val F1=0.1419)
  Directional -> Accuracy: 0.6250, MCC: 0.0976, F1: 0.7500

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.58948 | val 0.77743
  Epoch 011 - train 0.57637 | val 0.81427
  Classification -> best τ=0.355 (val F1=0.2390)
  Directional -> Accuracy: 0.5909, MCC: 0.1890, F1: 0.5263

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.59972 | val 1.18986
  Epoch 012 - train 0.53159 | val 1.21182
  Classification -> best τ=0.730 (val F1=0.2629)
  Directional -> Accuracy: 0.4310, MCC: 0.0000, F1: 0.0000

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.59945 | val 0.74005
  Epoch 012 - train 0.57481 | val 0.82247
  Classification -> best τ=0.505 (val F1=0.2086)
  Directional -> Accuracy: 0.5455, MCC: 0.1038, F1: 0.5714

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.55490 | val 0.81651
  Epoch 015 - train 0.46378 | val 1.07247
  Classification -> best τ=0.495 (val F1=0.3608)
  Directional -> Accuracy: 0.5536, MCC: 0.2064, F1: 0.4186

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.54879 | val 0.82100
  Epoch 011 - train 0.50769 | val 0.80484
  Classification -> best τ=0.505 (val F1=0.1925)
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.54273 | val 0.66938
  Epoch 020 - train 0.53139 | val 0.87832
  Classification -> best τ=0.600 (val F1=0.2439)
  Directional -> Accuracy: 0.5814, MCC: 0.2814, F1: 0.5000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.58656 | val 0.87716
  Epoch 014 - train 0.54236 | val 1.00987
  Classification -> best τ=0.415 (val F1=0.2260)
  Directional -> Accuracy: 0.5789, MCC: 0.2579, F1: 0.4783

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.57576 | val 0.74411
  Epoch 017 - train 0.51310 | val 1.01086
  Classification -> best τ=0.620 (val F1=0.3548)
  Directional -> Accuracy: 0.4146, MCC: -0.1635, F1: 0.4000

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.55273 | val 1.80044
  Epoch 012 - train 0.54820 | val 1.99346
  Classification -> best τ=0.535 (val F1=0.2683)
  Directional -> Accuracy: 0.5116, MCC: 0.0197, F1: 0.4615

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.56243 | val 0.98012
  Epoch 015 - train 0.51320 | val 1.36220
  Classification -> best τ=0.470 (val F1=0.2324)
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.52766 | val 1.04348
  Epoch 011 - train 0.51167 | val 1.08282
  Classification -> best τ=0.410 (val F1=0.2324)
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.59096 | val 1.16990
  Epoch 011 - train 0.56878 | val 1.18542
  Classification -> best τ=0.520 (val F1=0.2343)
  Directional -> Accuracy: 0.4384, MCC: 0.0000, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.51903 | val 0.80717
  Epoch 011 - train 0.55503 | val 0.84167
  Classification -> best τ=0.515 (val F1=0.2041)
  Directional -> Accuracy: 0.5789, MCC: 0.1741, F1: 0.6522

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.54997 | val 0.92950
  Epoch 011 - train 0.53436 | val 0.98656
  Classification -> best τ=0.410 (val F1=0.2757)
  Directional -> Accuracy: 0.5455, MCC: 0.0788, F1: 0.3750

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.59285 | val 1.17829
  Epoch 011 - train 0.56735 | val 1.15688
  Classification -> best τ=0.445 (val F1=0.3180)
  Directional -> Accuracy: 0.5821, MCC: 0.1241, F1: 0.6667

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.49137 | val 0.75824
  Epoch 012 - train 0.50120 | val 0.74336
  Classification -> best τ=0.580 (val F1=0.1846)
  Directional -> Accuracy: 0.6977, MCC: 0.4222, F1: 0.6486

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.51187 | val 1.29245
  Epoch 011 - train 0.51931 | val 1.49491
  Classification -> best τ=0.435 (val F1=0.3530)
  Directional -> Accuracy: 0.5439, MCC: 0.1235, F1: 0.6176

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.48969 | val 0.73721
  Epoch 011 - train 0.49688 | val 0.73138
  Classification -> best τ=0.440 (val F1=0.3296)
  Directional -> Accuracy: 0.6170, MCC: 0.0000, F1: 0.7632

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.57071 | val 0.64885
  Epoch 020 - train 0.42479 | val 0.69622
  Epoch 021 - train 0.39447 | val 0.69590
  Classification -> best τ=0.475 (val F1=0.4795)
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.44995 | val 1.10863
  Epoch 011 - train 0.46794 | val 1.15595
  Classification -> best τ=0.490 (val F1=0.2227)
  Directional -> Accuracy: 0.4737, MCC: -0.0690, F1: 0.5455

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.56147 | val 1.31752
  Epoch 013 - train 0.54394 | val 1.45615
  Classification -> best τ=0.505 (val F1=0.3073)
  Directional -> Accuracy: 0.4800, MCC: -0.1178, F1: 0.6486

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.59764 | val 0.69797
  Epoch 011 - train 0.58420 | val 0.70538
  Classification -> best τ=0.480 (val F1=0.4379)
  Directional -> Accuracy: 0.4894, MCC: -0.0111, F1: 0.2941

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.45230 | val 0.82993
  Epoch 011 - train 0.51379 | val 0.92924
  Classification -> best τ=0.500 (val F1=0.2749)
  Directional -> Accuracy: 0.4318, MCC: 0.0000, F1: 0.0000

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.51427 | val 0.75723
  Epoch 013 - train 0.51956 | val 0.82041
  Classification -> best τ=0.465 (val F1=0.4458)
  Directional -> Accuracy: 0.3469, MCC: -0.2592, F1: 0.5152

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.59783 | val 1.02927
  Epoch 012 - train 0.58395 | val 1.14277
  Classification -> best τ=0.510 (val F1=0.1563)
  Directional -> Accuracy: 0.6250, MCC: 0.2417, F1: 0.6667

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.52343 | val 0.84582
  Epoch 014 - train 0.48029 | val 1.01283
  Classification -> best τ=0.495 (val F1=0.4217)
  Directional -> Accuracy: 0.4737, MCC: -0.0301, F1: 0.5714

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.59198 | val 1.39652
  Epoch 011 - train 0.56869 | val 1.42113
  Classification -> best τ=0.500 (val F1=0.1626)
  Directional -> Accuracy: 0.5926, MCC: 0.1841, F1: 0.6071

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.56876 | val 1.10693
  Epoch 011 - train 0.57589 | val 1.21010
  Classification -> best τ=0.470 (val F1=0.2182)
  Directional -> Accuracy: 0.5179, MCC: 0.0000, F1: 0.6824

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.57752 | val 0.64838

[I 2026-02-22 11:44:31,481] Trial 150 finished with value: 0.24646803289883812 and parameters: {'feature_set': 'sector', 'model_type': 'BiGRU', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.30000000000000004, 'batch_size': 64, 'learning_rate': 0.004324130771027333, 'weight_decay': 0.0001605126498665773, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 1.0922613556285246, 'early_stopping_min_delta': 0.0007599367766221307}. Best is trial 112 with value: 0.2833506688525635.

  Epoch 019 - train 0.51640 | val 0.82415
  Classification -> best τ=0.460 (val F1=0.3174)
  Directional -> Accuracy: 0.5410, MCC: 0.2042, F1: 0.6667

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.24646803289883812
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.54878 | val 0.74920
  Epoch 015 - train 0.53401 | val 0.92591
  Classification -> best τ=0.480 (val F1=0.2627)
  Directional -> Accuracy: 0.6184, MCC: 0.2355, F1: 0.5915

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.51344 | val 0.72426
  Epoch 011 - train 0.53788 | val 0.74575
  Classification -> best τ=0.475 (val F1=0.1764)
  Directional -> Accuracy: 0.6222, MCC: 0.2110, F1: 0.6909

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.58882 | val 0.97495
  Epoch 012 - train 0.52083 | val 1.10296
  Classification -> best τ=0.550 (val F1=0.2449)
  Directional -> Accuracy: 0.4783, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.61544 | val 0.74995
  Epoch 011 - train 0.59706 | val 0.78812
  Classification -> best τ=0.455 (val F1=0.1839)
  Directional -> Accuracy: 0.5541, MCC: 0.0868, F1: 0.6292

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.54045 | val 0.65259
  Epoch 019 - train 0.42323 | val 0.77194
  Classification -> best τ=0.640 (val F1=0.3641)
  Directional -> Accuracy: 0.6000, MCC: 0.2202, F1: 0.5455

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.50070 | val 0.74039
  Epoch 015 - train 0.48993 | val 0.71071
  Classification -> best τ=0.435 (val F1=0.3222)
  Directional -> Accuracy: 0.5870, MCC: 0.1741, F1: 0.5778

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.60445 | val 1.19257
  Epoch 011 - train 0.59813 | val 1.34334
  Classification -> best τ=0.470 (val F1=0.2492)
  Directional -> Accuracy: 0.4706, MCC: 0.0888, F1: 0.5610

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.50045 | val 0.58642
  Epoch 020 - train 0.43402 | val 0.75373
  Epoch 025 - train 0.37061 | val 0.67018
  Classification -> best τ=0.625 (val F1=0.3689)
  Directional -> Accuracy: 0.5238, MCC: 0.1021, F1: 0.5652

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.57539 | val 0.82022
  Epoch 014 - train 0.51601 | val 0.94506
  Classification -> best τ=0.410 (val F1=0.2678)
  Directional -> Accuracy: 0.4583, MCC: 0.0542, F1: 0.6061

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.54230 | val 0.73305
  Epoch 013 - train 0.52219 | val 1.00453
  Classification -> best τ=0.500 (val F1=0.1745)
  Directional -> Accuracy: 0.4783, MCC: -0.0139, F1: 0.4857

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.61259 | val 0.86821
  Epoch 012 - train 0.55619 | val 0.88782
  Classification -> best τ=0.505 (val F1=0.3729)
  Directional -> Accuracy: 0.5306, MCC: -0.1303, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.56843 | val 0.94042
  Epoch 011 - train 0.57240 | val 0.91530
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5088, MCC: 0.0000, F1: 0.6744

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.53543 | val 1.17978
  Epoch 014 - train 0.47833 | val 1.07548
  Classification -> best τ=0.530 (val F1=0.1225)
  Directional -> Accuracy: 0.4524, MCC: -0.1513, F1: 0.2581

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.56099 | val 0.69839
  Epoch 014 - train 0.52557 | val 0.74616
  Classification -> best τ=0.555 (val F1=0.2845)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.54977 | val 0.87335
  Epoch 012 - train 0.51961 | val 0.78506
  Classification -> best τ=0.590 (val F1=0.2078)
  Directional -> Accuracy: 0.5490, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.56450 | val 0.86390
  Epoch 012 - train 0.54178 | val 0.84653
  Classification -> best τ=0.525 (val F1=0.3024)
  Directional -> Accuracy: 0.5797, MCC: 0.1767, F1: 0.5538

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.59634 | val 0.90613
  Epoch 011 - train 0.58603 | val 0.92219
  Classification -> best τ=0.570 (val F1=0.1342)
  Directional -> Accuracy: 0.3793, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.56806 | val 0.91925
  Epoch 011 - train 0.55863 | val 0.89218
  Classification -> best τ=0.445 (val F1=0.1348)
  Directional -> Accuracy: 0.6000, MCC: 0.0000, F1: 0.7500

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.56490 | val 1.13133
  Epoch 014 - train 0.54211 | val 0.86413
  Classification -> best τ=0.310 (val F1=0.3057)
  Directional -> Accuracy: 0.5625, MCC: -0.0129, F1: 0.7083

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.56521 | val 0.92261
  Epoch 014 - train 0.53216 | val 0.90636
  Classification -> best τ=0.375 (val F1=0.2437)
  Directional -> Accuracy: 0.4865, MCC: -0.0738, F1: 0.5870

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.54798 | val 0.89879
  Epoch 011 - train 0.52593 | val 0.91508
  Classification -> best τ=0.495 (val F1=0.1424)
  Directional -> Accuracy: 0.6170, MCC: 0.0000, F1: 0.7632

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.59053 | val 0.78213
  Epoch 016 - train 0.49443 | val 1.06413
  Classification -> best τ=0.460 (val F1=0.3624)
  Directional -> Accuracy: 0.5077, MCC: 0.0533, F1: 0.1579

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.59505 | val 0.77042
  Epoch 014 - train 0.54193 | val 0.80631
  Classification -> best τ=0.530 (val F1=0.3667)
  Directional -> Accuracy: 0.5614, MCC: 0.0981, F1: 0.6269

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.57262 | val 0.76879
  Epoch 014 - train 0.52267 | val 0.94148
  Classification -> best τ=0.470 (val F1=0.1313)
  Directional -> Accuracy: 0.4923, MCC: 0.0075, F1: 0.5823

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.51047 | val 0.84510
  Epoch 015 - train 0.44229 | val 1.19952
  Classification -> best τ=0.525 (val F1=0.5707)
  Directional -> Accuracy: 0.6000, MCC: 0.2476, F1: 0.5417

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.54920 | val 0.68538
  Epoch 019 - train 0.46550 | val 0.98623
  Classification -> best τ=0.480 (val F1=0.3764)
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.5938

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.58258 | val 0.71992
  Epoch 011 - train 0.56574 | val 0.71816
  Classification -> best τ=0.600 (val F1=0.1936)
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.0000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.55736 | val 0.77432
  Epoch 011 - train 0.54920 | val 0.79076
  Classification -> best τ=0.450 (val F1=0.2871)
  Directional -> Accuracy: 0.4821, MCC: 0.1728, F1: 0.1212

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.57820 | val 0.88644
  Epoch 011 - train 0.58739 | val 0.86911
  Classification -> best τ=0.450 (val F1=0.2509)
  Directional -> Accuracy: 0.6000, MCC: 0.2010, F1: 0.7241

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.55032 | val 0.83456
  Epoch 011 - train 0.55654 | val 0.92509
  Classification -> best τ=0.510 (val F1=0.3244)
  Directional -> Accuracy: 0.4762, MCC: -0.0374, F1: 0.5217

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.62407 | val 1.34118
  Epoch 011 - train 0.51856 | val 1.32675
  Classification -> best τ=0.485 (val F1=0.1286)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.53767 | val 0.95477
  Epoch 013 - train 0.50843 | val 1.01351
  Classification -> best τ=0.420 (val F1=0.3242)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.58344 | val 0.85509
  Epoch 013 - train 0.56794 | val 0.95322
  Classification -> best τ=0.415 (val F1=0.3534)
  Directional -> Accuracy: 0.5139, MCC: 0.1292, F1: 0.3396

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.57558 | val 0.77742
  Epoch 011 - train 0.57662 | val 0.78636
  Classification -> best τ=0.470 (val F1=0.2324)
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.57755 | val 1.00953
  Epoch 011 - train 0.58208 | val 1.10333
  Classification -> best τ=0.480 (val F1=0.2409)
  Directional -> Accuracy: 0.5909, MCC: 0.1026, F1: 0.7216

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.49217 | val 0.78295
  Epoch 012 - train 0.47902 | val 0.84885
  Classification -> best τ=0.550 (val F1=0.2665)
  Directional -> Accuracy: 0.6667, MCC: 0.3708, F1: 0.6111

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.53081 | val 0.99263
  Epoch 011 - train 0.52639 | val 1.20764
  Classification -> best τ=0.465 (val F1=0.2450)
  Directional -> Accuracy: 0.5179, MCC: 0.0384, F1: 0.5091

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.49956 | val 0.87053
  Epoch 015 - train 0.45461 | val 1.04721
  Classification -> best τ=0.640 (val F1=0.3294)
  Directional -> Accuracy: 0.3478, MCC: -0.2659, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.57088 | val 0.74074
  Epoch 020 - train 0.52498 | val 0.73975
  Epoch 024 - train 0.49885 | val 0.72827
  Classification -> best τ=0.555 (val F1=0.4011)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.55969 | val 1.39832
  Epoch 012 - train 0.54442 | val 1.28317
  Classification -> best τ=0.385 (val F1=0.3322)
  Directional -> Accuracy: 0.4865, MCC: 0.0000, F1: 0.6545

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.57041 | val 0.75586
  Epoch 011 - train 0.58818 | val 0.76025
  Classification -> best τ=0.495 (val F1=0.0259)
  Directional -> Accuracy: 0.4889, MCC: -0.0048, F1: 0.0800

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.56590 | val 0.69345
  Epoch 014 - train 0.47094 | val 0.77167
  Classification -> best τ=0.435 (val F1=0.3563)
  Directional -> Accuracy: 0.5000, MCC: 0.0138, F1: 0.5116

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.51736 | val 0.62850
  Epoch 020 - train 0.42607 | val 0.72780
  Epoch 024 - train 0.37386 | val 0.80082
  Classification -> best τ=0.695 (val F1=0.6080)
  Directional -> Accuracy: 0.3958, MCC: 0.0222, F1: 0.5397

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.58991 | val 0.73667
  Epoch 012 - train 0.58320 | val 0.80824
  Classification -> best τ=0.585 (val F1=0.1474)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.54788 | val 1.28584
  Epoch 014 - train 0.49185 | val 1.33339
  Classification -> best τ=0.620 (val F1=0.3088)
  Directional -> Accuracy: 0.5179, MCC: 0.0000, F1: 0.0000

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.56811 | val 0.85859
  Epoch 012 - train 0.56741 | val 1.00921
  Classification -> best τ=0.525 (val F1=0.2719)
  Directional -> Accuracy: 0.6226, MCC: 0.2468, F1: 0.6154

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.54065 | val 0.84983
  Epoch 011 - train 0.55532 | val 0.98448
  Classification -> best τ=0.530 (val F1=0.2681)
  Directional -> Accuracy: 0.5273, MCC: 0.0000, F1: 0.6905

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.58548 | val 0.76162

[I 2026-02-22 11:45:54,889] Trial 151 finished with value: 0.2675850781783419 and parameters: {'feature_set': 'sector', 'model_type': 'BiGRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.30000000000000004, 'batch_size': 64, 'learning_rate': 0.003208120711452425, 'weight_decay': 7.628520427851677e-05, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 1.053386924483529, 'early_stopping_min_delta': 0.00018871935268635485}. Best is trial 112 with value: 0.2833506688525635.

  Epoch 017 - train 0.55903 | val 0.80937
  Classification -> best τ=0.535 (val F1=0.2749)
  Directional -> Accuracy: 0.5000, MCC: -0.1259, F1: 0.0000

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2675850781783419
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.57362 | val 0.76703
  Epoch 014 - train 0.56064 | val 0.97546
  Classification -> best τ=0.575 (val F1=0.2510)
  Directional -> Accuracy: 0.5658, MCC: 0.0857, F1: 0.3265

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.53148 | val 0.68920
  Epoch 017 - train 0.46038 | val 0.78597
  Classification -> best τ=0.395 (val F1=0.3022)
  Directional -> Accuracy: 0.5778, MCC: 0.0000, F1: 0.7324

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.56802 | val 0.90166
  Epoch 011 - train 0.56052 | val 0.93601
  Classification -> best τ=0.510 (val F1=0.0845)
  Directional -> Accuracy: 0.3913, MCC: -0.2753, F1: 0.0667

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.59571 | val 0.88345
  Epoch 011 - train 0.58218 | val 0.90722
  Classification -> best τ=0.440 (val F1=0.0335)
  Directional -> Accuracy: 0.5676, MCC: 0.1808, F1: 0.7143

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.57140 | val 0.64269
  Epoch 020 - train 0.45120 | val 0.70469
  Epoch 024 - train 0.37456 | val 0.75593
  Classification -> best τ=0.800 (val F1=0.4028)
  Directional -> Accuracy: 0.5400, MCC: 0.2427, F1: 0.2069

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.55983 | val 0.67271
  Epoch 020 - train 0.46832 | val 0.84292
  Epoch 024 - train 0.42928 | val 0.91500
  Classification -> best τ=0.565 (val F1=0.4390)
  Directional -> Accuracy: 0.5217, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.60763 | val 1.34259
  Epoch 011 - train 0.61555 | val 1.33824
  Classification -> best τ=0.470 (val F1=0.3051)
  Directional -> Accuracy: 0.5147, MCC: 0.1667, F1: 0.5823

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.55485 | val 0.66969
  Epoch 011 - train 0.55699 | val 0.66854
  Classification -> best τ=0.465 (val F1=0.2657)
  Directional -> Accuracy: 0.4762, MCC: -0.2161, F1: 0.0833

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.58708 | val 0.73858
  Epoch 014 - train 0.52414 | val 1.04837
  Classification -> best τ=0.525 (val F1=0.2764)
  Directional -> Accuracy: 0.5833, MCC: 0.1240, F1: 0.4118

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.58514 | val 0.76484
  Epoch 020 - train 0.43041 | val 0.89183
  Epoch 024 - train 0.43383 | val 0.80988
  Classification -> best τ=0.400 (val F1=0.3268)
  Directional -> Accuracy: 0.4928, MCC: 0.0209, F1: 0.5070

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.58463 | val 0.94681
  Epoch 011 - train 0.60621 | val 1.01731
  Classification -> best τ=0.475 (val F1=0.2661)
  Directional -> Accuracy: 0.5918, MCC: 0.1635, F1: 0.2857

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.58075 | val 0.93064
  Epoch 011 - train 0.60273 | val 0.96422
  Classification -> best τ=0.525 (val F1=0.0820)
  Directional -> Accuracy: 0.5965, MCC: 0.3156, F1: 0.7160

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.56956 | val 0.75678
  Epoch 011 - train 0.52784 | val 0.78971
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.6230

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.60595 | val 0.69840
  Epoch 014 - train 0.56403 | val 0.69146
  Classification -> best τ=0.475 (val F1=0.3289)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.58724 | val 0.76245
  Epoch 016 - train 0.50445 | val 0.80638
  Classification -> best τ=0.425 (val F1=0.2069)
  Directional -> Accuracy: 0.6471, MCC: 0.3580, F1: 0.6897

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.55272 | val 0.97473
  Epoch 011 - train 0.53165 | val 1.03349
  Classification -> best τ=0.475 (val F1=0.2795)
  Directional -> Accuracy: 0.5652, MCC: 0.1171, F1: 0.6939

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.59771 | val 1.03555
  Epoch 011 - train 0.59153 | val 1.12393
  Classification -> best τ=0.475 (val F1=0.1336)
  Directional -> Accuracy: 0.6207, MCC: 0.0000, F1: 0.7660

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.59517 | val 0.88400
  Epoch 011 - train 0.58127 | val 0.90123
  Classification -> best τ=0.500 (val F1=0.1909)
  Directional -> Accuracy: 0.4133, MCC: -0.0780, F1: 0.2903

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.61534 | val 0.94592
  Epoch 012 - train 0.56183 | val 1.13103
  Classification -> best τ=0.425 (val F1=0.2616)
  Directional -> Accuracy: 0.5781, MCC: 0.0913, F1: 0.6824

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.59368 | val 0.94131
  Epoch 013 - train 0.54891 | val 1.08365
  Classification -> best τ=0.390 (val F1=0.2912)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.56760 | val 0.78297
  Epoch 012 - train 0.57941 | val 0.87066
  Classification -> best τ=0.505 (val F1=0.2281)
  Directional -> Accuracy: 0.5106, MCC: -0.0037, F1: 0.5818

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.60086 | val 0.78647
  Epoch 012 - train 0.58292 | val 0.82161
  Classification -> best τ=0.375 (val F1=0.2673)
  Directional -> Accuracy: 0.6000, MCC: 0.2359, F1: 0.4800

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.59550 | val 0.68732
  Epoch 016 - train 0.54414 | val 0.79586
  Classification -> best τ=0.805 (val F1=0.3254)
  Directional -> Accuracy: 0.4386, MCC: -0.0236, F1: 0.0588

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.58020 | val 0.74091
  Epoch 014 - train 0.55608 | val 0.73833
  Classification -> best τ=0.520 (val F1=0.2177)
  Directional -> Accuracy: 0.5077, MCC: 0.0402, F1: 0.5897

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.51518 | val 0.91114
  Epoch 016 - train 0.47193 | val 1.25635
  Classification -> best τ=0.465 (val F1=0.4209)
  Directional -> Accuracy: 0.6000, MCC: 0.2476, F1: 0.5417

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.53470 | val 0.73620
  Epoch 011 - train 0.54371 | val 0.75527
  Classification -> best τ=0.580 (val F1=0.1932)
  Directional -> Accuracy: 0.5778, MCC: 0.0000, F1: 0.0000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.59566 | val 0.68472
  Epoch 020 - train 0.50489 | val 0.66588
  Epoch 030 - train 0.48485 | val 0.70008
  Classification -> best τ=0.450 (val F1=0.3685)
  Directional -> Accuracy: 0.5000, MCC: -0.0595, F1: 0.6038

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.56688 | val 0.85026
  Epoch 012 - train 0.56035 | val 0.93944
  Classification -> best τ=0.450 (val F1=0.1677)
  Directional -> Accuracy: 0.5536, MCC: 0.0000, F1: 0.7126

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.58770 | val 0.81428
  Epoch 012 - train 0.53868 | val 0.82513
  Classification -> best τ=0.505 (val F1=0.0483)
  Directional -> Accuracy: 0.5500, MCC: 0.0000, F1: 0.7097

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.57096 | val 0.79082
  Epoch 011 - train 0.58732 | val 0.79085
  Classification -> best τ=0.500 (val F1=0.3501)
  Directional -> Accuracy: 0.4762, MCC: -0.0674, F1: 0.3529

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.58392 | val 1.01517
  Epoch 012 - train 0.53407 | val 1.07188
  Classification -> best τ=0.430 (val F1=0.1124)
  Directional -> Accuracy: 0.5476, MCC: 0.0000, F1: 0.7077

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.59622 | val 0.76387
  Epoch 016 - train 0.49830 | val 1.05401
  Classification -> best τ=0.415 (val F1=0.4687)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.57989 | val 0.84007
  Epoch 011 - train 0.55195 | val 0.87114
  Classification -> best τ=0.455 (val F1=0.2382)
  Directional -> Accuracy: 0.4444, MCC: 0.0000, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.55780 | val 0.83142
  Epoch 011 - train 0.58751 | val 0.86171
  Classification -> best τ=0.480 (val F1=0.3533)
  Directional -> Accuracy: 0.6047, MCC: 0.2502, F1: 0.4138

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.57536 | val 0.86558
  Epoch 011 - train 0.57785 | val 0.88173
  Classification -> best τ=0.480 (val F1=0.4292)
  Directional -> Accuracy: 0.5909, MCC: 0.1026, F1: 0.7216

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.51525 | val 0.91392
  Epoch 012 - train 0.47543 | val 0.92798
  Classification -> best τ=0.470 (val F1=0.2292)
  Directional -> Accuracy: 0.7381, MCC: 0.4767, F1: 0.7442

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.53501 | val 0.96480
  Epoch 012 - train 0.54097 | val 1.12892
  Classification -> best τ=0.485 (val F1=0.1690)
  Directional -> Accuracy: 0.4464, MCC: -0.0962, F1: 0.4746

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.51251 | val 0.78206
  Epoch 012 - train 0.47740 | val 0.87397
  Classification -> best τ=0.470 (val F1=0.3105)
  Directional -> Accuracy: 0.5652, MCC: 0.0505, F1: 0.6667

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.54980 | val 0.68401
  Epoch 020 - train 0.50347 | val 0.59488
  Epoch 030 - train 0.41381 | val 0.64188
  Classification -> best τ=0.210 (val F1=0.4469)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.53756 | val 1.17450
  Epoch 013 - train 0.51992 | val 1.33469
  Classification -> best τ=0.400 (val F1=0.3163)
  Directional -> Accuracy: 0.4865, MCC: 0.0000, F1: 0.6545

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.61514 | val 0.71041
  Epoch 017 - train 0.54592 | val 0.73018
  Classification -> best τ=0.475 (val F1=0.5164)
  Directional -> Accuracy: 0.5111, MCC: 0.0000, F1: 0.6765

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.57057 | val 0.69472
  Epoch 015 - train 0.48312 | val 0.72642
  Classification -> best τ=0.585 (val F1=0.3612)
  Directional -> Accuracy: 0.4762, MCC: 0.0786, F1: 0.2667

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.57486 | val 0.68605
  Epoch 020 - train 0.43120 | val 0.66071
  Epoch 030 - train 0.41982 | val 0.61986
  Classification -> best τ=0.455 (val F1=0.3410)
  Directional -> Accuracy: 0.3958, MCC: 0.0222, F1: 0.5397

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.62511 | val 0.73762
  Epoch 013 - train 0.58934 | val 0.75952
  Classification -> best τ=0.560 (val F1=0.1647)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.51905 | val 0.87600
  Epoch 011 - train 0.51345 | val 0.83552
  Classification -> best τ=0.555 (val F1=0.2493)
  Directional -> Accuracy: 0.5179, MCC: 0.0000, F1: 0.0000

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.57862 | val 0.83514
  Epoch 015 - train 0.55921 | val 0.92198
  Classification -> best τ=0.410 (val F1=0.2309)
  Directional -> Accuracy: 0.5472, MCC: 0.2018, F1: 0.6923

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.56316 | val 1.13214
  Epoch 011 - train 0.56919 | val 1.17426
  Classification -> best τ=0.540 (val F1=0.1129)
  Directional -> Accuracy: 0.4909, MCC: -0.0452, F1: 0.5882

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.59744 | val 0.66576
  Epoch 020 - train 0.52167 | val 0.67396

[I 2026-02-22 11:47:20,132] Trial 152 finished with value: 0.2630535283574657 and parameters: {'feature_set': 'sector', 'model_type': 'BiGRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.30000000000000004, 'batch_size': 64, 'learning_rate': 0.002173493655746316, 'weight_decay': 3.873563012767779e-05, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 1.0047832581818237, 'early_stopping_min_delta': 0.00025247307792647795}. Best is trial 112 with value: 0.2833506688525635.

  Epoch 022 - train 0.50013 | val 0.70931
  Classification -> best τ=0.405 (val F1=0.2615)
  Directional -> Accuracy: 0.5667, MCC: 0.1348, F1: 0.4091

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2630535283574657
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.58760 | val 0.95555
  Epoch 015 - train 0.54491 | val 1.04934
  Classification -> best τ=0.545 (val F1=0.2200)
  Directional -> Accuracy: 0.6053, MCC: 0.2176, F1: 0.5946

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.51150 | val 0.77245
  Epoch 013 - train 0.50469 | val 0.83670
  Classification -> best τ=0.430 (val F1=0.1289)
  Directional -> Accuracy: 0.5778, MCC: 0.0000, F1: 0.7324

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.57948 | val 1.28316
  Epoch 012 - train 0.50252 | val 1.49985
  Classification -> best τ=0.550 (val F1=0.2727)
  Directional -> Accuracy: 0.4783, MCC: -0.0200, F1: 0.2500

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.60783 | val 0.70085
  Epoch 020 - train 0.52601 | val 0.71387
  Epoch 023 - train 0.50359 | val 0.75300
  Classification -> best τ=0.480 (val F1=0.3504)
  Directional -> Accuracy: 0.4189, MCC: -0.1425, F1: 0.3175

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.57961 | val 0.65752
  Epoch 014 - train 0.52705 | val 0.69365
  Classification -> best τ=0.570 (val F1=0.5298)
  Directional -> Accuracy: 0.6000, MCC: 0.2425, F1: 0.5000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.53164 | val 0.82403
  Epoch 011 - train 0.53767 | val 0.89906
  Classification -> best τ=0.540 (val F1=0.3069)
  Directional -> Accuracy: 0.5217, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.61901 | val 1.08379
  Epoch 013 - train 0.63649 | val 1.01775
  Classification -> best τ=0.460 (val F1=0.3041)
  Directional -> Accuracy: 0.5294, MCC: 0.1704, F1: 0.5789

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.56707 | val 0.56714
  Epoch 020 - train 0.38378 | val 0.63355
  Epoch 026 - train 0.42817 | val 0.74369
  Classification -> best τ=0.080 (val F1=0.3504)
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.55111 | val 0.64826
  Epoch 020 - train 0.47016 | val 1.76927
  Classification -> best τ=0.580 (val F1=0.3959)
  Directional -> Accuracy: 0.5417, MCC: 0.0067, F1: 0.2667

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.57259 | val 0.84480
  Epoch 017 - train 0.49678 | val 0.93623
  Classification -> best τ=0.565 (val F1=0.3044)
  Directional -> Accuracy: 0.4928, MCC: -0.0265, F1: 0.4262

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.57910 | val 0.88191
  Epoch 012 - train 0.59639 | val 0.96508
  Classification -> best τ=0.525 (val F1=0.3075)
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.60677 | val 0.89799
  Epoch 011 - train 0.60501 | val 0.92368
  Classification -> best τ=0.460 (val F1=0.2157)
  Directional -> Accuracy: 0.5088, MCC: 0.0000, F1: 0.6744

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.49898 | val 0.91521
  Epoch 013 - train 0.49735 | val 1.11671
  Classification -> best τ=0.445 (val F1=0.1754)
  Directional -> Accuracy: 0.5238, MCC: 0.1062, F1: 0.6000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.55490 | val 0.73971
  Epoch 016 - train 0.55302 | val 0.84486
  Classification -> best τ=0.370 (val F1=0.3455)
  Directional -> Accuracy: 0.4833, MCC: -0.1302, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.57567 | val 0.78421
  Epoch 012 - train 0.56823 | val 0.91864
  Classification -> best τ=0.500 (val F1=0.3737)
  Directional -> Accuracy: 0.5490, MCC: 0.0858, F1: 0.4889

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.56467 | val 0.99223
  Epoch 012 - train 0.55451 | val 1.08860
  Classification -> best τ=0.350 (val F1=0.2341)
  Directional -> Accuracy: 0.5362, MCC: 0.0224, F1: 0.6800

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.59324 | val 0.99513
  Epoch 013 - train 0.55501 | val 1.00992
  Classification -> best τ=0.595 (val F1=0.2276)
  Directional -> Accuracy: 0.3793, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.58315 | val 0.82216
  Epoch 011 - train 0.59366 | val 0.80492
  Classification -> best τ=0.535 (val F1=0.1548)
  Directional -> Accuracy: 0.4000, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.61109 | val 1.01670
  Epoch 012 - train 0.57286 | val 1.05377
  Classification -> best τ=0.400 (val F1=0.3689)
  Directional -> Accuracy: 0.5469, MCC: 0.0384, F1: 0.6420

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.60215 | val 0.92998
  Epoch 011 - train 0.55699 | val 0.92850
  Classification -> best τ=0.415 (val F1=0.3397)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.62195 | val 0.97556
  Epoch 011 - train 0.54834 | val 1.01166
  Classification -> best τ=0.495 (val F1=0.2449)
  Directional -> Accuracy: 0.5106, MCC: 0.1303, F1: 0.4651

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.59122 | val 0.79103
  Epoch 013 - train 0.55043 | val 0.83507
  Classification -> best τ=0.525 (val F1=0.2216)
  Directional -> Accuracy: 0.4923, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.58803 | val 0.74520
  Epoch 012 - train 0.63009 | val 0.80519
  Classification -> best τ=0.475 (val F1=0.3566)
  Directional -> Accuracy: 0.5789, MCC: 0.1083, F1: 0.7209

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.60421 | val 0.89307
  Epoch 012 - train 0.58190 | val 0.78846
  Classification -> best τ=0.505 (val F1=0.2073)
  Directional -> Accuracy: 0.5538, MCC: 0.2044, F1: 0.6667

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.47973 | val 0.84144
  Epoch 016 - train 0.47674 | val 1.12326
  Classification -> best τ=0.365 (val F1=0.4380)
  Directional -> Accuracy: 0.5818, MCC: 0.2024, F1: 0.5306

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.55239 | val 0.71952
  Epoch 013 - train 0.53076 | val 0.90956
  Classification -> best τ=0.520 (val F1=0.2935)
  Directional -> Accuracy: 0.4444, MCC: 0.0481, F1: 0.5902

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.57177 | val 0.70697
  Epoch 014 - train 0.54916 | val 0.75630
  Classification -> best τ=0.595 (val F1=0.1353)
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.0000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.55161 | val 0.99954
  Epoch 012 - train 0.55568 | val 1.02747
  Classification -> best τ=0.400 (val F1=0.1986)
  Directional -> Accuracy: 0.5536, MCC: 0.0000, F1: 0.7126

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.57867 | val 0.68157
  Epoch 020 - train 0.42225 | val 0.76614
  Classification -> best τ=0.485 (val F1=0.2509)
  Directional -> Accuracy: 0.6250, MCC: 0.2659, F1: 0.7368

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.64595 | val 0.85714
  Epoch 016 - train 0.52933 | val 0.92096
  Classification -> best τ=0.635 (val F1=0.3501)
  Directional -> Accuracy: 0.5000, MCC: -0.0092, F1: 0.4324

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.62771 | val 1.16729
  Epoch 011 - train 0.57271 | val 1.13883
  Classification -> best τ=0.530 (val F1=0.1286)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.58664 | val 0.93393
  Epoch 013 - train 0.53249 | val 1.18009
  Classification -> best τ=0.390 (val F1=0.2884)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.59269 | val 0.84331
  Epoch 014 - train 0.54550 | val 0.81133
  Classification -> best τ=0.510 (val F1=0.2524)
  Directional -> Accuracy: 0.4444, MCC: 0.0000, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.56953 | val 0.87865
  Epoch 011 - train 0.56525 | val 0.93177
  Classification -> best τ=0.440 (val F1=0.2324)
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.59642 | val 0.89358
  Epoch 011 - train 0.56661 | val 0.90838
  Classification -> best τ=0.420 (val F1=0.2972)
  Directional -> Accuracy: 0.5606, MCC: 0.0466, F1: 0.6742

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.49930 | val 0.74468
  Epoch 012 - train 0.50586 | val 1.01602
  Classification -> best τ=0.455 (val F1=0.2193)
  Directional -> Accuracy: 0.7143, MCC: 0.4318, F1: 0.7143

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.51831 | val 1.20733
  Epoch 011 - train 0.52247 | val 1.25945
  Classification -> best τ=0.430 (val F1=0.2677)
  Directional -> Accuracy: 0.4464, MCC: -0.0962, F1: 0.4746

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.52992 | val 0.73865
  Epoch 011 - train 0.51204 | val 0.74358
  Classification -> best τ=0.500 (val F1=0.4763)
  Directional -> Accuracy: 0.4783, MCC: 0.0463, F1: 0.4286

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.61107 | val 0.69480
  Epoch 013 - train 0.57293 | val 0.71471
  Classification -> best τ=0.530 (val F1=0.4011)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.52371 | val 1.26604
  Epoch 012 - train 0.52425 | val 1.25385
  Classification -> best τ=0.470 (val F1=0.3523)
  Directional -> Accuracy: 0.4595, MCC: -0.0855, F1: 0.4118

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.59406 | val 0.69873
  Epoch 019 - train 0.51006 | val 0.79686
  Classification -> best τ=0.560 (val F1=0.3500)
  Directional -> Accuracy: 0.5333, MCC: 0.0871, F1: 0.4000

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.53436 | val 0.73684
  Epoch 016 - train 0.42555 | val 0.93080
  Classification -> best τ=0.635 (val F1=0.3118)
  Directional -> Accuracy: 0.4762, MCC: 0.0525, F1: 0.3125

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.53947 | val 0.66106
  Epoch 020 - train 0.46029 | val 0.61684
  Epoch 027 - train 0.38758 | val 0.79173
  Classification -> best τ=0.510 (val F1=0.4542)
  Directional -> Accuracy: 0.4583, MCC: 0.1627, F1: 0.5667

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.60973 | val 0.86565
  Epoch 012 - train 0.59167 | val 0.91656
  Classification -> best τ=0.470 (val F1=0.2833)
  Directional -> Accuracy: 0.5455, MCC: 0.0000, F1: 0.7059

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.50486 | val 0.84408
  Epoch 013 - train 0.50307 | val 1.00239
  Classification -> best τ=0.555 (val F1=0.3246)
  Directional -> Accuracy: 0.5536, MCC: 0.1135, F1: 0.5763

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.59419 | val 0.92637
  Epoch 011 - train 0.60483 | val 0.99006
  Classification -> best τ=0.470 (val F1=0.2790)
  Directional -> Accuracy: 0.5849, MCC: 0.1768, F1: 0.6562

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.56294 | val 1.19379
  Epoch 011 - train 0.56078 | val 1.17094
  Classification -> best τ=0.565 (val F1=0.1186)
  Directional -> Accuracy: 0.4727, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.58042 | val 0.91799

[I 2026-02-22 11:48:42,184] Trial 153 finished with value: 0.29003479699554807 and parameters: {'feature_set': 'sector', 'model_type': 'BiGRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.4, 'batch_size': 64, 'learning_rate': 0.003961245114478727, 'weight_decay': 4.312298095735805e-05, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 1.1663874717952307, 'early_stopping_min_delta': 0.000580325055808252}. Best is trial 153 with value: 0.29003479699554807.

  Epoch 017 - train 0.51315 | val 0.73253
  Classification -> best τ=0.520 (val F1=0.2810)
  Directional -> Accuracy: 0.6167, MCC: 0.2550, F1: 0.4651

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.29003479699554807
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.61287 | val 0.69463
  Epoch 013 - train 0.56082 | val 0.79439
  Classification -> best τ=0.495 (val F1=0.2919)
  Directional -> Accuracy: 0.6053, MCC: 0.1975, F1: 0.5455

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.56579 | val 0.68936
  Epoch 011 - train 0.53693 | val 0.69986
  Classification -> best τ=0.490 (val F1=0.0618)
  Directional -> Accuracy: 0.6444, MCC: 0.2466, F1: 0.7333

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.57169 | val 0.90888
  Epoch 012 - train 0.54018 | val 1.00703
  Classification -> best τ=0.555 (val F1=0.1978)
  Directional -> Accuracy: 0.4783, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.60226 | val 0.73028
  Epoch 011 - train 0.59244 | val 0.75850
  Classification -> best τ=0.460 (val F1=0.2025)
  Directional -> Accuracy: 0.3919, MCC: -0.2271, F1: 0.4444

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.53740 | val 0.66010
  Epoch 018 - train 0.48374 | val 0.70370
  Classification -> best τ=0.580 (val F1=0.3751)
  Directional -> Accuracy: 0.6000, MCC: 0.2802, F1: 0.4444

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.51939 | val 0.79170
  Epoch 011 - train 0.54317 | val 0.78601
  Classification -> best τ=0.505 (val F1=0.2204)
  Directional -> Accuracy: 0.5217, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.61859 | val 1.27437
  Epoch 013 - train 0.62434 | val 1.34775
  Classification -> best τ=0.470 (val F1=0.2255)
  Directional -> Accuracy: 0.5147, MCC: 0.1280, F1: 0.5600

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.59574 | val 0.56816
  Epoch 020 - train 0.42322 | val 0.75170
  Epoch 021 - train 0.44723 | val 0.77766
  Classification -> best τ=0.500 (val F1=0.5247)
  Directional -> Accuracy: 0.5000, MCC: 0.0595, F1: 0.5532

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.56977 | val 1.76478
  Epoch 013 - train 0.58232 | val 2.13686
  Classification -> best τ=0.525 (val F1=0.2443)
  Directional -> Accuracy: 0.7083, MCC: 0.4371, F1: 0.5333

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.55369 | val 0.80943
  Epoch 012 - train 0.55186 | val 0.80884
  Classification -> best τ=0.430 (val F1=0.2671)
  Directional -> Accuracy: 0.4348, MCC: 0.0115, F1: 0.5806

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.63665 | val 0.79745
  Epoch 014 - train 0.57252 | val 0.92477
  Classification -> best τ=0.505 (val F1=0.3493)
  Directional -> Accuracy: 0.5918, MCC: 0.1804, F1: 0.2308

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.59696 | val 1.07800
  Epoch 012 - train 0.62186 | val 0.99279
  Classification -> best τ=0.580 (val F1=0.1181)
  Directional -> Accuracy: 0.5439, MCC: 0.2316, F1: 0.1875

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.54178 | val 0.78351
  Epoch 011 - train 0.52279 | val 0.75990
  Classification -> best τ=0.420 (val F1=0.1632)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.6230

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.58263 | val 0.67961
  Epoch 015 - train 0.53471 | val 0.74977
  Classification -> best τ=0.435 (val F1=0.3012)
  Directional -> Accuracy: 0.5333, MCC: 0.0894, F1: 0.3000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.56099 | val 0.69521
  Epoch 020 - train 0.46041 | val 0.87986
  Classification -> best τ=0.635 (val F1=0.1556)
  Directional -> Accuracy: 0.5490, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.58472 | val 0.89981
  Epoch 012 - train 0.53935 | val 0.85712
  Classification -> best τ=0.565 (val F1=0.2466)
  Directional -> Accuracy: 0.5507, MCC: 0.0987, F1: 0.5753

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.59863 | val 0.86973
  Epoch 011 - train 0.59738 | val 0.88129
  Classification -> best τ=0.560 (val F1=0.1303)
  Directional -> Accuracy: 0.3793, MCC: -0.2759, F1: 0.4706

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.59782 | val 1.06005
  Epoch 011 - train 0.58999 | val 1.06479
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.6000, MCC: 0.0000, F1: 0.7500

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.59674 | val 0.92770
  Epoch 013 - train 0.55066 | val 0.93048
  Classification -> best τ=0.375 (val F1=0.3140)
  Directional -> Accuracy: 0.6562, MCC: 0.2759, F1: 0.7317

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.58927 | val 0.82833
  Epoch 012 - train 0.57578 | val 0.79550
  Classification -> best τ=0.415 (val F1=0.3194)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.60432 | val 0.77802
  Epoch 012 - train 0.54080 | val 0.75209
  Classification -> best τ=0.455 (val F1=0.1723)
  Directional -> Accuracy: 0.6170, MCC: 0.0000, F1: 0.7632

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.64239 | val 0.71212
  Epoch 015 - train 0.55689 | val 0.84774
  Classification -> best τ=0.440 (val F1=0.3247)
  Directional -> Accuracy: 0.5846, MCC: 0.1898, F1: 0.4906

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.59917 | val 0.69123
  Epoch 016 - train 0.56061 | val 0.76977
  Classification -> best τ=0.470 (val F1=0.3800)
  Directional -> Accuracy: 0.5789, MCC: 0.1450, F1: 0.6250

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.58098 | val 0.73790
  Epoch 011 - train 0.58631 | val 0.74366
  Classification -> best τ=0.540 (val F1=0.1874)
  Directional -> Accuracy: 0.5231, MCC: 0.0776, F1: 0.6076

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.53192 | val 0.83573
  Epoch 016 - train 0.45959 | val 1.30992
  Classification -> best τ=0.465 (val F1=0.4068)
  Directional -> Accuracy: 0.5273, MCC: 0.1286, F1: 0.3810

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.53052 | val 0.79031
  Epoch 011 - train 0.51237 | val 0.81309
  Classification -> best τ=0.550 (val F1=0.2726)
  Directional -> Accuracy: 0.5111, MCC: -0.1591, F1: 0.0833

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.57911 | val 0.78161
  Epoch 014 - train 0.55159 | val 0.74727
  Classification -> best τ=0.570 (val F1=0.2161)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.2581

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.58299 | val 0.75368
  Epoch 012 - train 0.60044 | val 0.79135
  Classification -> best τ=0.395 (val F1=0.1607)
  Directional -> Accuracy: 0.5357, MCC: -0.0017, F1: 0.6667

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.61131 | val 1.03004
  Epoch 013 - train 0.52895 | val 0.86253
  Classification -> best τ=0.450 (val F1=0.3278)
  Directional -> Accuracy: 0.5750, MCC: 0.1770, F1: 0.7213

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.62731 | val 0.94754
  Epoch 012 - train 0.60209 | val 0.93969
  Classification -> best τ=0.550 (val F1=0.3501)
  Directional -> Accuracy: 0.4762, MCC: -0.0413, F1: 0.5000

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.56881 | val 1.34627
  Epoch 011 - train 0.56348 | val 1.28178
  Classification -> best τ=0.535 (val F1=0.1286)
  Directional -> Accuracy: 0.5000, MCC: 0.1319, F1: 0.2222

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.49970 | val 0.94320
  Epoch 014 - train 0.48584 | val 1.06971
  Classification -> best τ=0.685 (val F1=0.2969)
  Directional -> Accuracy: 0.6122, MCC: 0.3100, F1: 0.4865

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.61063 | val 0.78399
  Epoch 014 - train 0.52850 | val 0.89887
  Classification -> best τ=0.415 (val F1=0.3263)
  Directional -> Accuracy: 0.4583, MCC: 0.0466, F1: 0.0930

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.57070 | val 0.87623
  Epoch 011 - train 0.55561 | val 0.89186
  Classification -> best τ=0.520 (val F1=0.2603)
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.57816 | val 0.96488
  Epoch 013 - train 0.56429 | val 0.98538
  Classification -> best τ=0.345 (val F1=0.3855)
  Directional -> Accuracy: 0.5758, MCC: 0.1011, F1: 0.6667

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.51059 | val 0.85259
  Epoch 011 - train 0.50550 | val 0.90609
  Classification -> best τ=0.475 (val F1=0.2409)
  Directional -> Accuracy: 0.7381, MCC: 0.4767, F1: 0.7442

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.55322 | val 1.14114
  Epoch 011 - train 0.53432 | val 1.11653
  Classification -> best τ=0.505 (val F1=0.2450)
  Directional -> Accuracy: 0.4643, MCC: -0.0576, F1: 0.5000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.54120 | val 0.79595
  Epoch 011 - train 0.49553 | val 0.79401
  Classification -> best τ=0.490 (val F1=0.3105)
  Directional -> Accuracy: 0.5000, MCC: 0.0393, F1: 0.5106

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.49528 | val 0.65566
  Epoch 020 - train 0.56048 | val 0.61079
  Epoch 030 - train 0.45644 | val 0.65197
  Classification -> best τ=0.285 (val F1=0.4855)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.53327 | val 1.07768
  Epoch 011 - train 0.51750 | val 1.16124
  Classification -> best τ=0.535 (val F1=0.2518)
  Directional -> Accuracy: 0.5405, MCC: 0.1260, F1: 0.1500

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.67336 | val 0.70806
  Epoch 016 - train 0.57785 | val 0.92394
  Classification -> best τ=0.470 (val F1=0.1976)
  Directional -> Accuracy: 0.4667, MCC: -0.1059, F1: 0.6000

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.52869 | val 0.74497
  Epoch 015 - train 0.49854 | val 0.87715
  Classification -> best τ=0.590 (val F1=0.3151)
  Directional -> Accuracy: 0.4762, MCC: 0.0323, F1: 0.3529

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.52860 | val 0.65339
  Epoch 020 - train 0.43681 | val 0.65657
  Epoch 022 - train 0.36693 | val 0.66257
  Classification -> best τ=0.465 (val F1=0.4682)
  Directional -> Accuracy: 0.4583, MCC: 0.1627, F1: 0.5667

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.62419 | val 0.74096
  Epoch 017 - train 0.54962 | val 0.93699
  Classification -> best τ=0.465 (val F1=0.3303)
  Directional -> Accuracy: 0.5455, MCC: 0.0000, F1: 0.7059

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.53841 | val 0.98423
  Epoch 014 - train 0.48629 | val 0.97687
  Classification -> best τ=0.465 (val F1=0.3236)
  Directional -> Accuracy: 0.5714, MCC: 0.1443, F1: 0.5714

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.61055 | val 1.10795
  Epoch 012 - train 0.61589 | val 1.15166
  Classification -> best τ=0.575 (val F1=0.2064)
  Directional -> Accuracy: 0.5660, MCC: 0.1459, F1: 0.4889

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.57415 | val 0.92458
  Epoch 014 - train 0.52913 | val 1.02182
  Classification -> best τ=0.410 (val F1=0.1801)
  Directional -> Accuracy: 0.5455, MCC: 0.1254, F1: 0.4444

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.62057 | val 0.69329

[I 2026-02-22 11:50:04,278] Trial 154 finished with value: 0.26647257075066066 and parameters: {'feature_set': 'sector', 'model_type': 'BiGRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.4, 'batch_size': 64, 'learning_rate': 0.003835689238213485, 'weight_decay': 9.884601902212212e-05, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 1.037413859075798, 'early_stopping_min_delta': 0.0005916935218131235}. Best is trial 153 with value: 0.29003479699554807.

  Epoch 018 - train 0.50923 | val 0.81175
  Classification -> best τ=0.455 (val F1=0.3309)
  Directional -> Accuracy: 0.5500, MCC: 0.1223, F1: 0.2286

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.26647257075066066
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.57721 | val 0.76953
  Epoch 017 - train 0.53812 | val 0.79064
  Classification -> best τ=0.630 (val F1=0.2919)
  Directional -> Accuracy: 0.5526, MCC: 0.0633, F1: 0.3704

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.50565 | val 0.80070
  Epoch 015 - train 0.44915 | val 0.79403
  Classification -> best τ=0.545 (val F1=0.1764)
  Directional -> Accuracy: 0.6000, MCC: 0.1419, F1: 0.7000

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.53126 | val 1.43886
  Epoch 011 - train 0.50787 | val 1.57112
  Classification -> best τ=0.540 (val F1=0.1383)
  Directional -> Accuracy: 0.4348, MCC: -0.1679, F1: 0.0714

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.62661 | val 0.72312
  Epoch 018 - train 0.53516 | val 0.69354
  Classification -> best τ=0.390 (val F1=0.3161)
  Directional -> Accuracy: 0.5270, MCC: 0.0073, F1: 0.6465

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.53699 | val 0.66478
  Epoch 015 - train 0.47845 | val 0.63012
  Classification -> best τ=0.510 (val F1=0.4947)
  Directional -> Accuracy: 0.6600, MCC: 0.3398, F1: 0.6222

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.56612 | val 1.03608
  Epoch 013 - train 0.47485 | val 1.06852
  Classification -> best τ=0.480 (val F1=0.1808)
  Directional -> Accuracy: 0.5652, MCC: 0.1461, F1: 0.2857

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.61466 | val 1.62049
  Epoch 011 - train 0.58640 | val 1.65269
  Classification -> best τ=0.530 (val F1=0.1276)
  Directional -> Accuracy: 0.5588, MCC: 0.0903, F1: 0.4643

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.51124 | val 0.70179
  Epoch 020 - train 0.36557 | val 0.65352
  Epoch 026 - train 0.32592 | val 0.63051
  Classification -> best τ=0.585 (val F1=0.5247)
  Directional -> Accuracy: 0.4762, MCC: 0.0323, F1: 0.5600

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.54813 | val 1.02282
  Epoch 012 - train 0.56229 | val 1.20477
  Classification -> best τ=0.560 (val F1=0.2764)
  Directional -> Accuracy: 0.6042, MCC: 0.1732, F1: 0.4571

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.53910 | val 0.74535
  Epoch 012 - train 0.55855 | val 0.77763
  Classification -> best τ=0.525 (val F1=0.3041)
  Directional -> Accuracy: 0.4638, MCC: -0.0392, F1: 0.4789

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.60269 | val 0.90402
  Epoch 012 - train 0.58065 | val 0.89426
  Classification -> best τ=0.520 (val F1=0.2687)
  Directional -> Accuracy: 0.5510, MCC: 0.0212, F1: 0.0833

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.58161 | val 0.97323
  Epoch 012 - train 0.53644 | val 1.13490
  Classification -> best τ=0.495 (val F1=0.0500)
  Directional -> Accuracy: 0.4561, MCC: -0.0929, F1: 0.5079

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.52752 | val 0.82341
  Epoch 011 - train 0.52244 | val 0.82096
  Classification -> best τ=0.570 (val F1=0.0400)
  Directional -> Accuracy: 0.4524, MCC: -0.1105, F1: 0.3784

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.59233 | val 0.73094
  Epoch 012 - train 0.56970 | val 0.76773
  Classification -> best τ=0.405 (val F1=0.3721)
  Directional -> Accuracy: 0.4833, MCC: -0.0431, F1: 0.2439

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.57604 | val 0.75716
  Epoch 020 - train 0.47223 | val 1.05768
  Epoch 023 - train 0.42241 | val 1.24528
  Classification -> best τ=0.690 (val F1=0.2971)
  Directional -> Accuracy: 0.6078, MCC: 0.2007, F1: 0.3750

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.55500 | val 0.90287
  Epoch 012 - train 0.53119 | val 0.98106
  Classification -> best τ=0.580 (val F1=0.3151)
  Directional -> Accuracy: 0.5652, MCC: 0.1223, F1: 0.6053

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.58712 | val 0.90479
  Epoch 011 - train 0.56886 | val 0.91386
  Classification -> best τ=0.505 (val F1=0.1394)
  Directional -> Accuracy: 0.6379, MCC: 0.1694, F1: 0.7742

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.54985 | val 0.91470
  Epoch 011 - train 0.55851 | val 0.95263
  Classification -> best τ=0.590 (val F1=0.1548)
  Directional -> Accuracy: 0.4000, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.54650 | val 1.06684
  Epoch 013 - train 0.55075 | val 1.03580
  Classification -> best τ=0.405 (val F1=0.3426)
  Directional -> Accuracy: 0.5000, MCC: -0.1376, F1: 0.6444

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.59441 | val 0.91483
  Epoch 012 - train 0.54019 | val 0.96844
  Classification -> best τ=0.475 (val F1=0.2056)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.53985 | val 0.76288
  Epoch 011 - train 0.52767 | val 0.77456
  Classification -> best τ=0.460 (val F1=0.1572)
  Directional -> Accuracy: 0.6170, MCC: 0.0000, F1: 0.7632

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.58652 | val 0.82708
  Epoch 015 - train 0.52987 | val 0.84155
  Classification -> best τ=0.585 (val F1=0.3236)
  Directional -> Accuracy: 0.4923, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.59713 | val 0.70583
  Epoch 015 - train 0.51618 | val 0.86783
  Classification -> best τ=0.430 (val F1=0.3601)
  Directional -> Accuracy: 0.5439, MCC: 0.0579, F1: 0.6176

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.54140 | val 0.82836
  Epoch 012 - train 0.53349 | val 0.82697
  Classification -> best τ=0.535 (val F1=0.1348)
  Directional -> Accuracy: 0.5077, MCC: 0.0574, F1: 0.6190

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.52601 | val 0.89898
  Epoch 015 - train 0.42836 | val 1.04943
  Classification -> best τ=0.315 (val F1=0.4001)
  Directional -> Accuracy: 0.5818, MCC: 0.2024, F1: 0.5306

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.56451 | val 0.92448
  Epoch 011 - train 0.52619 | val 1.07451
  Classification -> best τ=0.515 (val F1=0.2035)
  Directional -> Accuracy: 0.4222, MCC: -0.0618, F1: 0.5517

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.57720 | val 0.72827
  Epoch 011 - train 0.60376 | val 0.72057
  Classification -> best τ=0.605 (val F1=0.1936)
  Directional -> Accuracy: 0.4286, MCC: -0.0913, F1: 0.3333

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.56599 | val 0.78306
  Epoch 015 - train 0.47207 | val 0.83511
  Classification -> best τ=0.355 (val F1=0.2058)
  Directional -> Accuracy: 0.5893, MCC: 0.1466, F1: 0.7089

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.54413 | val 0.71924
  Epoch 018 - train 0.50078 | val 0.86550
  Classification -> best τ=0.520 (val F1=0.5105)
  Directional -> Accuracy: 0.5500, MCC: 0.0503, F1: 0.6667

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.55384 | val 0.78156
  Epoch 011 - train 0.57244 | val 0.76801
  Classification -> best τ=0.565 (val F1=0.3501)
  Directional -> Accuracy: 0.5000, MCC: -0.0196, F1: 0.3636

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.55123 | val 1.19082
  Epoch 012 - train 0.59372 | val 1.59699
  Classification -> best τ=0.440 (val F1=0.2357)
  Directional -> Accuracy: 0.5476, MCC: 0.0000, F1: 0.7077

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.55694 | val 0.94942
  Epoch 013 - train 0.49336 | val 0.98545
  Classification -> best τ=0.445 (val F1=0.3461)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.56763 | val 1.08011
  Epoch 012 - train 0.53275 | val 1.12295
  Classification -> best τ=0.445 (val F1=0.3583)
  Directional -> Accuracy: 0.5278, MCC: 0.0828, F1: 0.5000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.59762 | val 0.84392
  Epoch 012 - train 0.52456 | val 0.85887
  Classification -> best τ=0.610 (val F1=0.3746)
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.56700 | val 0.98695
  Epoch 011 - train 0.56463 | val 1.03440
  Classification -> best τ=0.500 (val F1=0.1372)
  Directional -> Accuracy: 0.5758, MCC: 0.0000, F1: 0.7308

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.47344 | val 1.38520
  Epoch 012 - train 0.46694 | val 1.45858
  Classification -> best τ=0.495 (val F1=0.2618)
  Directional -> Accuracy: 0.6667, MCC: 0.3441, F1: 0.6500

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.50099 | val 1.37321
  Epoch 011 - train 0.49229 | val 1.39551
  Classification -> best τ=0.480 (val F1=0.2382)
  Directional -> Accuracy: 0.5000, MCC: -0.0103, F1: 0.4400

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.48614 | val 0.73874
  Epoch 014 - train 0.43787 | val 0.83234
  Classification -> best τ=0.370 (val F1=0.2504)
  Directional -> Accuracy: 0.6087, MCC: 0.0000, F1: 0.7568

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.53697 | val 0.67789
  Epoch 020 - train 0.48717 | val 0.62842
  Epoch 026 - train 0.42521 | val 0.64331
  Classification -> best τ=0.560 (val F1=0.3887)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.58606 | val 1.08025
  Epoch 014 - train 0.43590 | val 1.25933
  Classification -> best τ=0.450 (val F1=0.3031)
  Directional -> Accuracy: 0.4865, MCC: -0.0107, F1: 0.6200

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.58631 | val 0.69112
  Epoch 016 - train 0.54858 | val 0.76749
  Classification -> best τ=0.525 (val F1=0.3371)
  Directional -> Accuracy: 0.5333, MCC: 0.1221, F1: 0.2759

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.47340 | val 0.88983
  Epoch 014 - train 0.46780 | val 1.07588
  Classification -> best τ=0.610 (val F1=0.4082)
  Directional -> Accuracy: 0.4048, MCC: -0.1273, F1: 0.1379

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.51251 | val 0.60943
  Epoch 020 - train 0.43805 | val 0.66346
  Epoch 024 - train 0.32681 | val 0.67496
  Classification -> best τ=0.550 (val F1=0.4216)
  Directional -> Accuracy: 0.4583, MCC: 0.1155, F1: 0.5517

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.60633 | val 0.82749
  Epoch 014 - train 0.57107 | val 0.98304
  Classification -> best τ=0.565 (val F1=0.1682)
  Directional -> Accuracy: 0.6364, MCC: 0.3435, F1: 0.5652

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.50664 | val 1.50131
  Epoch 013 - train 0.46135 | val 1.42891
  Classification -> best τ=0.500 (val F1=0.2804)
  Directional -> Accuracy: 0.5000, MCC: 0.0405, F1: 0.6316

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.59454 | val 0.85097
  Epoch 012 - train 0.60187 | val 0.88464
  Classification -> best τ=0.580 (val F1=0.1668)
  Directional -> Accuracy: 0.5660, MCC: 0.1410, F1: 0.5106

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.56154 | val 0.92021
  Epoch 013 - train 0.55208 | val 1.15456
  Classification -> best τ=0.550 (val F1=0.1210)
  Directional -> Accuracy: 0.4727, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.61323 | val 0.69262

[I 2026-02-22 11:51:28,500] Trial 155 finished with value: 0.26907789273860955 and parameters: {'feature_set': 'sector', 'model_type': 'BiGRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.30000000000000004, 'batch_size': 64, 'learning_rate': 0.004760384757922322, 'weight_decay': 6.009208900282757e-05, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 1.1623329904164534, 'early_stopping_min_delta': 0.0008041169648110399}. Best is trial 153 with value: 0.29003479699554807.

  Epoch 019 - train 0.47476 | val 0.66813
  Classification -> best τ=0.745 (val F1=0.2623)
  Directional -> Accuracy: 0.5167, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.26907789273860955
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.59721 | val 0.77576
  Epoch 015 - train 0.58667 | val 0.90255
  Classification -> best τ=0.445 (val F1=0.1671)
  Directional -> Accuracy: 0.6316, MCC: 0.2646, F1: 0.6111

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.57983 | val 0.69803
  Epoch 018 - train 0.51176 | val 0.75282
  Classification -> best τ=0.470 (val F1=0.2523)
  Directional -> Accuracy: 0.6222, MCC: 0.1941, F1: 0.7385

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.62563 | val 0.69183
  Epoch 016 - train 0.56216 | val 0.85282
  Classification -> best τ=0.545 (val F1=0.2941)
  Directional -> Accuracy: 0.4783, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.62774 | val 0.76028
  Epoch 011 - train 0.64022 | val 0.72883
  Classification -> best τ=0.485 (val F1=0.2352)
  Directional -> Accuracy: 0.4730, MCC: 0.0200, F1: 0.1702

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.58006 | val 0.64062
  Epoch 020 - train 0.52383 | val 0.74201
  Epoch 022 - train 0.52818 | val 0.64123
  Classification -> best τ=0.580 (val F1=0.5250)
  Directional -> Accuracy: 0.6200, MCC: 0.3170, F1: 0.4865

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.58594 | val 0.68738
  Epoch 019 - train 0.53124 | val 0.78863
  Classification -> best τ=0.505 (val F1=0.3838)
  Directional -> Accuracy: 0.5217, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.65097 | val 0.76764
  Epoch 013 - train 0.62255 | val 1.02235
  Classification -> best τ=0.470 (val F1=0.2255)
  Directional -> Accuracy: 0.4706, MCC: 0.0693, F1: 0.5500

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.58236 | val 0.84142
  Epoch 011 - train 0.55303 | val 0.76012
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.63823 | val 0.82376
  Epoch 015 - train 0.58100 | val 0.88292
  Classification -> best τ=0.475 (val F1=0.2094)
  Directional -> Accuracy: 0.6458, MCC: 0.3194, F1: 0.6531

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.60869 | val 0.79875
  Epoch 013 - train 0.55051 | val 0.78313
  Classification -> best τ=0.520 (val F1=0.1502)
  Directional -> Accuracy: 0.4928, MCC: 0.0415, F1: 0.5333

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.61096 | val 0.67911
  Epoch 019 - train 0.57057 | val 0.73430
  Classification -> best τ=0.445 (val F1=0.3241)
  Directional -> Accuracy: 0.4898, MCC: 0.0370, F1: 0.5763

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.62752 | val 0.73635
  Epoch 011 - train 0.64733 | val 0.74837
  Classification -> best τ=0.475 (val F1=0.1095)
  Directional -> Accuracy: 0.6491, MCC: 0.3027, F1: 0.6296

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.51922 | val 0.69529
  Epoch 011 - train 0.54757 | val 0.70344
  Classification -> best τ=0.490 (val F1=0.2466)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.6230

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.61071 | val 0.71778
  Epoch 013 - train 0.59360 | val 0.73805
  Classification -> best τ=0.525 (val F1=0.3378)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.59807 | val 0.69815
  Epoch 020 - train 0.52108 | val 0.68121
  Epoch 029 - train 0.47197 | val 0.77106
  Classification -> best τ=0.490 (val F1=0.3219)
  Directional -> Accuracy: 0.4510, MCC: 0.0000, F1: 0.6216

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.56591 | val 0.76300
  Epoch 013 - train 0.56284 | val 0.95064
  Classification -> best τ=0.445 (val F1=0.2795)
  Directional -> Accuracy: 0.6087, MCC: 0.3006, F1: 0.7327

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.64336 | val 0.71910
  Epoch 011 - train 0.63469 | val 0.72229
  Classification -> best τ=0.535 (val F1=0.0557)
  Directional -> Accuracy: 0.4138, MCC: 0.0725, F1: 0.1500

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.65251 | val 0.74753
  Epoch 012 - train 0.63315 | val 0.80963
  Classification -> best τ=0.500 (val F1=0.1750)
  Directional -> Accuracy: 0.5733, MCC: -0.0727, F1: 0.7241

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.59940 | val 0.67942
  Epoch 018 - train 0.57463 | val 0.75204
  Classification -> best τ=0.455 (val F1=0.3343)
  Directional -> Accuracy: 0.5000, MCC: -0.0049, F1: 0.5429

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.60114 | val 0.71067
  Epoch 018 - train 0.58054 | val 0.87333
  Classification -> best τ=0.440 (val F1=0.2329)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.61911 | val 0.70924
  Epoch 014 - train 0.63580 | val 0.71499
  Classification -> best τ=0.480 (val F1=0.1314)
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.66528 | val 0.68939
  Epoch 018 - train 0.59766 | val 0.82771
  Classification -> best τ=0.500 (val F1=0.2508)
  Directional -> Accuracy: 0.5077, MCC: 0.0699, F1: 0.1111

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.63010 | val 0.67116
  Epoch 020 - train 0.58415 | val 0.85550
  Epoch 023 - train 0.56255 | val 0.91538
  Classification -> best τ=0.545 (val F1=0.3191)
  Directional -> Accuracy: 0.5614, MCC: 0.1133, F1: 0.6032

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.63717 | val 0.72669
  Epoch 011 - train 0.59386 | val 0.76054
  Classification -> best τ=0.495 (val F1=0.1122)
  Directional -> Accuracy: 0.5077, MCC: 0.0451, F1: 0.6000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.61086 | val 0.68812
  Epoch 017 - train 0.54904 | val 1.02107
  Classification -> best τ=0.505 (val F1=0.4001)
  Directional -> Accuracy: 0.5818, MCC: 0.1913, F1: 0.5490

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.62052 | val 0.69754
  Epoch 013 - train 0.56532 | val 0.69708
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.5938

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.61139 | val 0.69097
  Epoch 017 - train 0.57909 | val 0.70162
  Classification -> best τ=0.545 (val F1=0.1273)
  Directional -> Accuracy: 0.5000, MCC: 0.0280, F1: 0.4878

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.59686 | val 0.69067
  Epoch 017 - train 0.55963 | val 0.82607
  Classification -> best τ=0.440 (val F1=0.1677)
  Directional -> Accuracy: 0.5893, MCC: 0.1796, F1: 0.6102

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.59874 | val 0.68658
  Epoch 020 - train 0.49587 | val 0.77117
  Epoch 022 - train 0.50543 | val 0.83071
  Classification -> best τ=0.460 (val F1=0.3518)
  Directional -> Accuracy: 0.6250, MCC: 0.3148, F1: 0.7458

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.63222 | val 0.72068
  Epoch 011 - train 0.59312 | val 0.75684
  Classification -> best τ=0.470 (val F1=0.2764)
  Directional -> Accuracy: 0.4524, MCC: -0.1064, F1: 0.3784

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.61722 | val 0.71575
  Epoch 011 - train 0.60521 | val 0.73346
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5476, MCC: 0.0000, F1: 0.7077

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.58218 | val 0.75729
  Epoch 014 - train 0.59327 | val 0.90003
  Classification -> best τ=0.475 (val F1=0.3987)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.62559 | val 0.77969
  Epoch 016 - train 0.57982 | val 0.87543
  Classification -> best τ=0.515 (val F1=0.3067)
  Directional -> Accuracy: 0.4444, MCC: 0.0000, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.60153 | val 0.71957
  Epoch 011 - train 0.61060 | val 0.73100
  Classification -> best τ=0.490 (val F1=0.2603)
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.61333 | val 0.77970
  Epoch 013 - train 0.58520 | val 0.80868
  Classification -> best τ=0.445 (val F1=0.3603)
  Directional -> Accuracy: 0.5758, MCC: 0.0389, F1: 0.7200

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.54496 | val 0.73077
  Epoch 015 - train 0.54808 | val 1.10705
  Classification -> best τ=0.445 (val F1=0.3068)
  Directional -> Accuracy: 0.5952, MCC: 0.1910, F1: 0.6792

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.59122 | val 0.82835
  Epoch 011 - train 0.53295 | val 0.88484
  Classification -> best τ=0.480 (val F1=0.2450)
  Directional -> Accuracy: 0.5179, MCC: 0.0437, F1: 0.5263

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.58134 | val 0.68450
  Epoch 011 - train 0.55916 | val 0.69197
  Classification -> best τ=0.470 (val F1=0.4627)
  Directional -> Accuracy: 0.5652, MCC: 0.0309, F1: 0.6774

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.61026 | val 0.66809
  Epoch 020 - train 0.54870 | val 0.66301
  Epoch 030 - train 0.48311 | val 0.73037
  Classification -> best τ=0.640 (val F1=0.3887)
  Directional -> Accuracy: 0.5208, MCC: 0.0692, F1: 0.4651

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.57298 | val 0.88315
  Epoch 015 - train 0.52190 | val 0.94206
  Classification -> best τ=0.455 (val F1=0.2732)
  Directional -> Accuracy: 0.4865, MCC: 0.0000, F1: 0.6545

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.64152 | val 0.68723
  Epoch 020 - train 0.57262 | val 0.68206
  Epoch 026 - train 0.51214 | val 0.70654
  Classification -> best τ=0.445 (val F1=0.4397)
  Directional -> Accuracy: 0.5111, MCC: 0.0000, F1: 0.6765

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.55228 | val 0.66738
  Epoch 020 - train 0.54478 | val 0.63259
  Epoch 028 - train 0.51169 | val 0.98741
  Classification -> best τ=0.250 (val F1=0.3563)
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.7273

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.60366 | val 0.66272
  Epoch 020 - train 0.57663 | val 0.64958
  Epoch 030 - train 0.47063 | val 0.67448
  Classification -> best τ=0.700 (val F1=0.3154)
  Directional -> Accuracy: 0.5000, MCC: 0.1854, F1: 0.5714

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.63874 | val 0.71361
  Epoch 012 - train 0.60489 | val 0.71926
  Classification -> best τ=0.470 (val F1=0.2448)
  Directional -> Accuracy: 0.5091, MCC: -0.0305, F1: 0.6197

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.55331 | val 0.70883
  Epoch 020 - train 0.46601 | val 0.97738
  Epoch 022 - train 0.45311 | val 1.09365
  Classification -> best τ=0.320 (val F1=0.4089)
  Directional -> Accuracy: 0.5179, MCC: 0.0875, F1: 0.6400

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.61104 | val 0.69127
  Epoch 013 - train 0.58556 | val 0.72143
  Classification -> best τ=0.500 (val F1=0.2741)
  Directional -> Accuracy: 0.5660, MCC: 0.1998, F1: 0.6933

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.60555 | val 0.80250
  Epoch 011 - train 0.60740 | val 0.81230
  Classification -> best τ=0.485 (val F1=0.0723)
  Directional -> Accuracy: 0.5273, MCC: 0.0000, F1: 0.6905

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...

[I 2026-02-22 11:52:27,579] Trial 156 finished with value: 0.25455251481610414 and parameters: {'feature_set': 'sector', 'model_type': 'LSTM', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.4, 'batch_size': 64, 'learning_rate': 0.0030042262633624057, 'weight_decay': 4.693601459443608e-05, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 1.1347195870425015, 'early_stopping_min_delta': 0.0012033184092561664}. Best is trial 153 with value: 0.29003479699554807.

  Epoch 010 - train 0.62217 | val 0.72095
  Epoch 011 - train 0.59791 | val 0.74905
  Classification -> best τ=0.525 (val F1=0.1080)
  Directional -> Accuracy: 0.4667, MCC: -0.0580, F1: 0.5556

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.25455251481610414
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.63238 | val 0.77091
  Epoch 013 - train 0.59999 | val 0.73148
  Classification -> best τ=0.430 (val F1=0.1671)
  Directional -> Accuracy: 0.5789, MCC: 0.1777, F1: 0.5897

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.57537 | val 0.68987
  Epoch 014 - train 0.56018 | val 0.72559
  Classification -> best τ=0.520 (val F1=0.2523)
  Directional -> Accuracy: 0.6667, MCC: 0.3123, F1: 0.7170

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.60187 | val 0.94517
  Epoch 012 - train 0.63527 | val 1.04796
  Classification -> best τ=0.545 (val F1=0.2449)
  Directional -> Accuracy: 0.4783, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.60757 | val 0.81880
  Epoch 013 - train 0.58791 | val 0.89147
  Classification -> best τ=0.480 (val F1=0.2329)
  Directional -> Accuracy: 0.5405, MCC: 0.0000, F1: 0.7018

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.58093 | val 0.68025
  Epoch 018 - train 0.53148 | val 0.75754
  Classification -> best τ=0.560 (val F1=0.4048)
  Directional -> Accuracy: 0.6200, MCC: 0.2795, F1: 0.5366

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.55924 | val 0.71815
  Epoch 011 - train 0.55628 | val 0.73020
  Classification -> best τ=0.570 (val F1=0.1877)
  Directional -> Accuracy: 0.5435, MCC: 0.0851, F1: 0.2222

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.65007 | val 1.06488
  Epoch 013 - train 0.62136 | val 1.07887
  Classification -> best τ=0.460 (val F1=0.2492)
  Directional -> Accuracy: 0.5147, MCC: 0.0683, F1: 0.5075

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.63130 | val 0.64152
  Epoch 017 - train 0.52532 | val 0.99183
  Classification -> best τ=0.390 (val F1=0.3632)
  Directional -> Accuracy: 0.4762, MCC: -0.0278, F1: 0.4762

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.57414 | val 0.90504
  Epoch 017 - train 0.56821 | val 1.54329
  Classification -> best τ=0.355 (val F1=0.3616)
  Directional -> Accuracy: 0.6458, MCC: 0.3055, F1: 0.6383

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.58911 | val 0.72062
  Epoch 013 - train 0.56029 | val 0.71765
  Classification -> best τ=0.460 (val F1=0.1256)
  Directional -> Accuracy: 0.4928, MCC: 0.0415, F1: 0.5333

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.65047 | val 0.80353
  Epoch 013 - train 0.58079 | val 0.71386
  Classification -> best τ=0.525 (val F1=0.1422)
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.59716 | val 0.89904
  Epoch 012 - train 0.61898 | val 1.01245
  Classification -> best τ=0.515 (val F1=0.2819)
  Directional -> Accuracy: 0.6842, MCC: 0.3743, F1: 0.7188

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.54648 | val 1.07358
  Epoch 011 - train 0.54327 | val 1.09233
  Classification -> best τ=0.425 (val F1=0.1754)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.6230

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.62537 | val 0.65798
  Epoch 013 - train 0.60099 | val 0.65888
  Classification -> best τ=0.525 (val F1=0.4109)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.60690 | val 0.71654
  Epoch 013 - train 0.55371 | val 0.72315
  Classification -> best τ=0.475 (val F1=0.0679)
  Directional -> Accuracy: 0.5490, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.62020 | val 0.88520
  Epoch 013 - train 0.54467 | val 0.86756
  Classification -> best τ=0.515 (val F1=0.2799)
  Directional -> Accuracy: 0.5797, MCC: 0.1502, F1: 0.6234

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.61600 | val 0.81316
  Epoch 011 - train 0.56802 | val 0.84543
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.6207, MCC: 0.0000, F1: 0.7660

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.59919 | val 0.82350
  Epoch 011 - train 0.60933 | val 0.84208
  Classification -> best τ=0.570 (val F1=0.1909)
  Directional -> Accuracy: 0.4133, MCC: 0.0949, F1: 0.0435

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.59093 | val 0.86986
  Epoch 013 - train 0.57769 | val 0.87451
  Classification -> best τ=0.345 (val F1=0.3140)
  Directional -> Accuracy: 0.5938, MCC: 0.1140, F1: 0.7111

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.57730 | val 0.78739
  Epoch 012 - train 0.58954 | val 0.86768
  Classification -> best τ=0.425 (val F1=0.2572)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.61127 | val 0.85753
  Epoch 014 - train 0.55037 | val 1.07269
  Classification -> best τ=0.410 (val F1=0.2247)
  Directional -> Accuracy: 0.6170, MCC: 0.0508, F1: 0.7568

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.63422 | val 0.71661
  Epoch 011 - train 0.63176 | val 0.71909
  Classification -> best τ=0.435 (val F1=0.2952)
  Directional -> Accuracy: 0.5846, MCC: 0.1709, F1: 0.5714

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.59769 | val 0.72487
  Epoch 015 - train 0.57697 | val 0.91114
  Classification -> best τ=0.780 (val F1=0.3550)
  Directional -> Accuracy: 0.4035, MCC: -0.2157, F1: 0.0000

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.58406 | val 0.77403
  Epoch 014 - train 0.58123 | val 0.82318
  Classification -> best τ=0.450 (val F1=0.0902)
  Directional -> Accuracy: 0.5231, MCC: 0.0776, F1: 0.6076

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.52455 | val 0.77306
  Epoch 018 - train 0.41522 | val 1.42932
  Classification -> best τ=0.460 (val F1=0.5376)
  Directional -> Accuracy: 0.6000, MCC: 0.2236, F1: 0.5769

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.55969 | val 0.73602
  Epoch 011 - train 0.54623 | val 0.74026
  Classification -> best τ=0.560 (val F1=0.1383)
  Directional -> Accuracy: 0.3556, MCC: -0.3530, F1: 0.1714

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.62886 | val 0.75226
  Epoch 011 - train 0.58665 | val 0.75653
  Classification -> best τ=0.550 (val F1=0.1353)
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.0000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.58303 | val 0.82717
  Epoch 012 - train 0.56961 | val 0.88032
  Classification -> best τ=0.460 (val F1=0.1218)
  Directional -> Accuracy: 0.5179, MCC: -0.1728, F1: 0.6824

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.59186 | val 0.67945
  Epoch 020 - train 0.51007 | val 1.43235
  Classification -> best τ=0.370 (val F1=0.4109)
  Directional -> Accuracy: 0.5500, MCC: 0.0231, F1: 0.7000

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.64427 | val 0.77096
  Epoch 013 - train 0.60220 | val 0.75546
  Classification -> best τ=0.575 (val F1=0.2814)
  Directional -> Accuracy: 0.5000, MCC: -0.0258, F1: 0.3226

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.56818 | val 0.89227
  Epoch 012 - train 0.57151 | val 1.06236
  Classification -> best τ=0.390 (val F1=0.2357)
  Directional -> Accuracy: 0.5476, MCC: 0.0000, F1: 0.7077

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.58732 | val 0.93325
  Epoch 016 - train 0.51839 | val 1.36694
  Classification -> best τ=0.340 (val F1=0.3242)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.60604 | val 0.83455
  Epoch 011 - train 0.61250 | val 0.84667
  Classification -> best τ=0.405 (val F1=0.2774)
  Directional -> Accuracy: 0.5139, MCC: 0.1147, F1: 0.3636

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.63995 | val 0.79630
  Epoch 011 - train 0.61135 | val 0.81293
  Classification -> best τ=0.535 (val F1=0.2603)
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.59940 | val 0.99904
  Epoch 011 - train 0.60346 | val 1.04422
  Classification -> best τ=0.465 (val F1=0.3280)
  Directional -> Accuracy: 0.6061, MCC: 0.1582, F1: 0.7045

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.54229 | val 1.03249
  Epoch 011 - train 0.50306 | val 1.11987
  Classification -> best τ=0.490 (val F1=0.3218)
  Directional -> Accuracy: 0.6905, MCC: 0.3877, F1: 0.6829

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.59776 | val 1.18154
  Epoch 011 - train 0.57684 | val 1.17188
  Classification -> best τ=0.530 (val F1=0.2305)
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.0000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.53767 | val 0.70849
  Epoch 014 - train 0.50019 | val 0.80277
  Classification -> best τ=0.360 (val F1=0.2118)
  Directional -> Accuracy: 0.6304, MCC: 0.1493, F1: 0.7536

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.61930 | val 0.65976
  Epoch 020 - train 0.53664 | val 0.65396
  Classification -> best τ=0.580 (val F1=0.3887)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.55210 | val 1.26596
  Epoch 012 - train 0.54090 | val 1.35172
  Classification -> best τ=0.430 (val F1=0.2600)
  Directional -> Accuracy: 0.4865, MCC: 0.0000, F1: 0.6545

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.65024 | val 0.66831
  Epoch 019 - train 0.53725 | val 0.75269
  Classification -> best τ=0.495 (val F1=0.4348)
  Directional -> Accuracy: 0.5556, MCC: 0.1188, F1: 0.6552

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.55544 | val 0.72131
  Epoch 016 - train 0.49094 | val 0.79242
  Classification -> best τ=0.545 (val F1=0.3151)
  Directional -> Accuracy: 0.4762, MCC: -0.0142, F1: 0.4500

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.62012 | val 0.64213
  Epoch 019 - train 0.50550 | val 0.73240
  Classification -> best τ=0.575 (val F1=0.4385)
  Directional -> Accuracy: 0.5000, MCC: 0.2928, F1: 0.6000

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.61150 | val 0.71992
  Epoch 013 - train 0.62784 | val 0.76244
  Classification -> best τ=0.700 (val F1=0.2036)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.59782 | val 1.01247
  Epoch 012 - train 0.49553 | val 0.92029
  Classification -> best τ=0.470 (val F1=0.4352)
  Directional -> Accuracy: 0.5000, MCC: -0.0039, F1: 0.4615

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.63435 | val 1.13296
  Epoch 011 - train 0.60802 | val 1.08998
  Classification -> best τ=0.565 (val F1=0.2064)
  Directional -> Accuracy: 0.5472, MCC: 0.1138, F1: 0.4286

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.61913 | val 1.21512
  Epoch 011 - train 0.59984 | val 1.28070
  Classification -> best τ=0.525 (val F1=0.2681)
  Directional -> Accuracy: 0.5273, MCC: 0.0000, F1: 0.6905

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.59662 | val 0.71944

[I 2026-02-22 11:53:47,134] Trial 157 finished with value: 0.26488875220664543 and parameters: {'feature_set': 'sector', 'model_type': 'BiGRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.5, 'batch_size': 64, 'learning_rate': 0.0038114371816028894, 'weight_decay': 1.2739455226235837e-07, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 20, 'huber_delta': 1.1864744274566934, 'early_stopping_min_delta': 0.0004895153740292846}. Best is trial 153 with value: 0.29003479699554807.

  Epoch 017 - train 0.55840 | val 0.95752
  Classification -> best τ=0.510 (val F1=0.2749)
  Directional -> Accuracy: 0.6167, MCC: 0.2668, F1: 0.4390

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.26488875220664543
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.61645 | val 1.61535
  Epoch 013 - train 0.57459 | val 1.15994
  Classification -> best τ=0.840 (val F1=0.2510)
  Directional -> Accuracy: 0.5526, MCC: 0.0000, F1: 0.0000

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.52342 | val 0.82247
  Epoch 011 - train 0.48196 | val 0.88218
  Classification -> best τ=0.510 (val F1=0.1764)
  Directional -> Accuracy: 0.6000, MCC: 0.1691, F1: 0.6667

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.56395 | val 1.44564
  Epoch 011 - train 0.52304 | val 1.61240
  Classification -> best τ=0.530 (val F1=0.2727)
  Directional -> Accuracy: 0.4783, MCC: -0.0134, F1: 0.1429

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.57730 | val 1.39314
  Epoch 020 - train 0.40856 | val 0.98961
  Epoch 025 - train 0.33652 | val 0.88571
  Classification -> best τ=0.240 (val F1=0.2230)
  Directional -> Accuracy: 0.5405, MCC: 0.0000, F1: 0.7018

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.51597 | val 1.57970
  Epoch 012 - train 0.41043 | val 1.78979
  Classification -> best τ=0.515 (val F1=0.5298)
  Directional -> Accuracy: 0.6800, MCC: 0.3677, F1: 0.6667

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.43452 | val 0.75613
  Epoch 012 - train 0.38650 | val 0.83230
  Classification -> best τ=0.530 (val F1=0.3433)
  Directional -> Accuracy: 0.5217, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.55336 | val 1.36058
  Epoch 011 - train 0.55937 | val 1.39275
  Classification -> best τ=0.420 (val F1=0.2797)
  Directional -> Accuracy: 0.4706, MCC: 0.0888, F1: 0.5610

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.52599 | val 1.37557
  Epoch 014 - train 0.41682 | val 2.22416
  Classification -> best τ=0.295 (val F1=0.3504)
  Directional -> Accuracy: 0.4762, MCC: -0.0550, F1: 0.4211

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.47115 | val 3.30890
  Epoch 011 - train 0.50026 | val 2.90015
  Classification -> best τ=0.595 (val F1=0.2764)
  Directional -> Accuracy: 0.6042, MCC: 0.1782, F1: 0.4865

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.51589 | val 1.54201
  Epoch 011 - train 0.50333 | val 1.52357
  Classification -> best τ=0.465 (val F1=0.1668)
  Directional -> Accuracy: 0.5362, MCC: 0.0953, F1: 0.5294

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.56714 | val 0.66046
  Epoch 020 - train 0.32831 | val 0.77476
  Classification -> best τ=0.535 (val F1=0.3493)
  Directional -> Accuracy: 0.5510, MCC: 0.0453, F1: 0.2667

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.58198 | val 1.30163
  Epoch 012 - train 0.51648 | val 2.27339
  Classification -> best τ=0.505 (val F1=0.2083)
  Directional -> Accuracy: 0.5439, MCC: 0.0929, F1: 0.5000

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.45866 | val 1.75336
  Epoch 011 - train 0.44732 | val 1.59606
  Classification -> best τ=0.510 (val F1=0.1225)
  Directional -> Accuracy: 0.5476, MCC: 0.0829, F1: 0.4865

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.57019 | val 0.66896
  Epoch 012 - train 0.55207 | val 0.83952
  Classification -> best τ=0.715 (val F1=0.3642)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.54857 | val 0.75039
  Epoch 011 - train 0.51179 | val 0.73359
  Classification -> best τ=0.605 (val F1=0.1455)
  Directional -> Accuracy: 0.5490, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.57823 | val 1.47841
  Epoch 011 - train 0.54877 | val 1.41592
  Classification -> best τ=0.665 (val F1=0.0972)
  Directional -> Accuracy: 0.4638, MCC: 0.0000, F1: 0.0000

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.61438 | val 1.05484
  Epoch 011 - train 0.51269 | val 0.92982
  Classification -> best τ=0.540 (val F1=0.1521)
  Directional -> Accuracy: 0.4483, MCC: 0.0258, F1: 0.3600

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.54282 | val 1.07859
  Epoch 014 - train 0.44706 | val 1.79436
  Classification -> best τ=0.550 (val F1=0.2758)
  Directional -> Accuracy: 0.4000, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.57287 | val 1.36474
  Epoch 011 - train 0.52820 | val 1.44091
  Classification -> best τ=0.625 (val F1=0.1931)
  Directional -> Accuracy: 0.4844, MCC: 0.1062, F1: 0.2979

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.50826 | val 1.63133
  Epoch 011 - train 0.48676 | val 2.15041
  Classification -> best τ=0.495 (val F1=0.4618)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.51443 | val 0.76300
  Epoch 011 - train 0.44143 | val 0.82842
  Classification -> best τ=0.455 (val F1=0.1572)
  Directional -> Accuracy: 0.5745, MCC: -0.0074, F1: 0.7059

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.50064 | val 1.24053
  Epoch 011 - train 0.47397 | val 1.53332
  Classification -> best τ=0.385 (val F1=0.1224)
  Directional -> Accuracy: 0.6154, MCC: 0.2387, F1: 0.5763

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.56348 | val 0.91724
  Epoch 018 - train 0.45760 | val 0.84970
  Classification -> best τ=0.485 (val F1=0.4893)
  Directional -> Accuracy: 0.6316, MCC: 0.2729, F1: 0.7470

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.56398 | val 0.99545
  Epoch 011 - train 0.52738 | val 1.03137
  Classification -> best τ=0.410 (val F1=0.1393)
  Directional -> Accuracy: 0.4923, MCC: 0.0445, F1: 0.6374

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.47811 | val 1.80769
  Epoch 012 - train 0.45890 | val 1.96628
  Classification -> best τ=0.370 (val F1=0.5188)
  Directional -> Accuracy: 0.5818, MCC: 0.1913, F1: 0.5490

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.48832 | val 5.28390
  Epoch 011 - train 0.45957 | val 5.22817
  Classification -> best τ=0.705 (val F1=0.2935)
  Directional -> Accuracy: 0.3333, MCC: -0.3664, F1: 0.2105

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.56681 | val 0.78279
  Epoch 011 - train 0.51473 | val 0.99209
  Classification -> best τ=0.565 (val F1=0.1407)
  Directional -> Accuracy: 0.4762, MCC: -0.0550, F1: 0.5217

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.50723 | val 1.38478
  Epoch 011 - train 0.46438 | val 1.68765
  Classification -> best τ=0.255 (val F1=0.3653)
  Directional -> Accuracy: 0.5000, MCC: 0.2137, F1: 0.1765

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.54927 | val 1.65797
  Epoch 012 - train 0.46122 | val 1.45327
  Classification -> best τ=0.465 (val F1=0.5577)
  Directional -> Accuracy: 0.5750, MCC: 0.1240, F1: 0.7119

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.58420 | val 0.81642
  Epoch 019 - train 0.36398 | val 0.98048
  Classification -> best τ=0.610 (val F1=0.3490)
  Directional -> Accuracy: 0.5238, MCC: 0.0413, F1: 0.4737

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.51914 | val 2.09361
  Epoch 013 - train 0.46004 | val 1.62350
  Classification -> best τ=0.755 (val F1=0.1286)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.47743 | val 0.95379
  Epoch 012 - train 0.39648 | val 1.17618
  Classification -> best τ=0.260 (val F1=0.3502)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.54777 | val 0.96573
  Epoch 011 - train 0.48666 | val 1.20520
  Classification -> best τ=0.450 (val F1=0.2978)
  Directional -> Accuracy: 0.5000, MCC: 0.2169, F1: 0.1818

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.51170 | val 1.99501
  Epoch 011 - train 0.52090 | val 1.73597
  Classification -> best τ=0.370 (val F1=0.2717)
  Directional -> Accuracy: 0.4651, MCC: -0.0977, F1: 0.6230

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.55903 | val 1.06470
  Epoch 013 - train 0.49651 | val 1.49954
  Classification -> best τ=0.515 (val F1=0.3001)
  Directional -> Accuracy: 0.5000, MCC: 0.1961, F1: 0.2667

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.49281 | val 4.51441
  Epoch 011 - train 0.38806 | val 4.48970
  Classification -> best τ=0.330 (val F1=0.1715)
  Directional -> Accuracy: 0.7143, MCC: 0.4273, F1: 0.7273

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.52721 | val 1.06232
  Epoch 011 - train 0.48653 | val 1.26143
  Classification -> best τ=0.525 (val F1=0.2755)
  Directional -> Accuracy: 0.5179, MCC: 0.0437, F1: 0.5263

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.44984 | val 1.20179
  Epoch 011 - train 0.40549 | val 1.18671
  Classification -> best τ=0.515 (val F1=0.3563)
  Directional -> Accuracy: 0.5870, MCC: 0.1074, F1: 0.6780

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.58143 | val 0.64402
  Epoch 020 - train 0.33552 | val 1.10133
  Classification -> best τ=0.580 (val F1=0.5708)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.54707 | val 2.28513
  Epoch 011 - train 0.48046 | val 2.40413
  Classification -> best τ=0.555 (val F1=0.2891)
  Directional -> Accuracy: 0.5270, MCC: 0.0611, F1: 0.1463

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.60639 | val 0.76833
  Epoch 014 - train 0.48494 | val 1.42391
  Classification -> best τ=0.445 (val F1=0.3873)
  Directional -> Accuracy: 0.5778, MCC: 0.2733, F1: 0.7077

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.34813 | val 2.12730
  Epoch 012 - train 0.23944 | val 3.29916
  Classification -> best τ=0.585 (val F1=0.4576)
  Directional -> Accuracy: 0.6190, MCC: 0.2041, F1: 0.6923

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.48647 | val 0.73219
  Epoch 013 - train 0.41893 | val 1.20355
  Classification -> best τ=0.605 (val F1=0.3300)
  Directional -> Accuracy: 0.5417, MCC: 0.2914, F1: 0.6071

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.64583 | val 0.92348
  Epoch 011 - train 0.61234 | val 0.96839
  Classification -> best τ=0.520 (val F1=0.2452)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.43424 | val 2.13046
  Epoch 011 - train 0.38465 | val 2.46684
  Classification -> best τ=0.620 (val F1=0.3294)
  Directional -> Accuracy: 0.5179, MCC: 0.1289, F1: 0.6582

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.62947 | val 1.10498
  Epoch 011 - train 0.59179 | val 1.21844
  Classification -> best τ=0.470 (val F1=0.2133)
  Directional -> Accuracy: 0.5849, MCC: 0.1768, F1: 0.6562

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.46004 | val 4.94321
  Epoch 012 - train 0.48029 | val 3.56216
  Classification -> best τ=0.785 (val F1=0.2859)
  Directional -> Accuracy: 0.4727, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.59765 | val 0.81534

[I 2026-02-22 11:56:18,227] Trial 158 finished with value: 0.290102987282063 and parameters: {'feature_set': 'sector', 'model_type': 'BiGRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.30000000000000004, 'batch_size': 16, 'learning_rate': 0.005718238423327583, 'weight_decay': 2.0174685127417825e-05, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 1.1036266607142817, 'early_stopping_min_delta': 7.291920632628978e-06}. Best is trial 158 with value: 0.290102987282063.

  Epoch 015 - train 0.53018 | val 0.72086
  Classification -> best τ=0.445 (val F1=0.2920)
  Directional -> Accuracy: 0.5167, MCC: 0.0089, F1: 0.1212

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.290102987282063
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.61712 | val 0.81497
  Epoch 011 - train 0.64365 | val 0.82056
  Classification -> best τ=0.620 (val F1=0.2510)
  Directional -> Accuracy: 0.6053, MCC: 0.1868, F1: 0.3750

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.57251 | val 1.24862
  Epoch 011 - train 0.48918 | val 1.39479
  Classification -> best τ=0.325 (val F1=0.2103)
  Directional -> Accuracy: 0.5778, MCC: 0.0000, F1: 0.7324

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.59900 | val 1.66324
  Epoch 011 - train 0.55345 | val 1.68150
  Classification -> best τ=0.315 (val F1=0.4104)
  Directional -> Accuracy: 0.5217, MCC: 0.0000, F1: 0.6857

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.60953 | val 1.31043
  Epoch 011 - train 0.55628 | val 1.27643
  Classification -> best τ=0.425 (val F1=0.1585)
  Directional -> Accuracy: 0.3919, MCC: -0.2030, F1: 0.2373

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.64647 | val 0.64349
  Epoch 019 - train 0.42100 | val 1.23078
  Classification -> best τ=0.360 (val F1=0.5217)
  Directional -> Accuracy: 0.6600, MCC: 0.3309, F1: 0.6383

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.53397 | val 0.77114
  Epoch 017 - train 0.40150 | val 0.78952
  Classification -> best τ=0.590 (val F1=0.3624)
  Directional -> Accuracy: 0.5217, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.58533 | val 1.46364
  Epoch 011 - train 0.65312 | val 1.14149
  Classification -> best τ=0.420 (val F1=0.3353)
  Directional -> Accuracy: 0.5294, MCC: 0.1355, F1: 0.5556

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.55171 | val 0.55342
  Epoch 019 - train 0.51000 | val 1.40859
  Classification -> best τ=0.185 (val F1=0.3094)
  Directional -> Accuracy: 0.4286, MCC: -0.0700, F1: 0.5385

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.59032 | val 2.18231
  Epoch 011 - train 0.56703 | val 2.73021
  Classification -> best τ=0.630 (val F1=0.2927)
  Directional -> Accuracy: 0.6042, MCC: 0.1697, F1: 0.4242

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.62100 | val 0.66896
  Epoch 020 - train 0.41053 | val 1.17892
  Classification -> best τ=0.470 (val F1=0.3404)
  Directional -> Accuracy: 0.4638, MCC: -0.0953, F1: 0.3729

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.64183 | val 0.83275
  Epoch 018 - train 0.55657 | val 1.70781
  Classification -> best τ=0.475 (val F1=0.4059)
  Directional -> Accuracy: 0.5714, MCC: 0.1005, F1: 0.2759

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.59011 | val 1.46877
  Epoch 011 - train 0.60099 | val 1.62212
  Classification -> best τ=0.590 (val F1=0.2083)
  Directional -> Accuracy: 0.5263, MCC: 0.1874, F1: 0.1290

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.54355 | val 2.93293
  Epoch 011 - train 0.49961 | val 3.45107
  Classification -> best τ=0.385 (val F1=0.1225)
  Directional -> Accuracy: 0.4762, MCC: -0.0302, F1: 0.5000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.60047 | val 0.84172
  Epoch 013 - train 0.57248 | val 0.89267
  Classification -> best τ=0.270 (val F1=0.3407)
  Directional -> Accuracy: 0.4500, MCC: -0.2294, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.62463 | val 1.00734
  Epoch 015 - train 0.52666 | val 0.82769
  Classification -> best τ=0.545 (val F1=0.2078)
  Directional -> Accuracy: 0.5294, MCC: -0.0338, F1: 0.1429

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.55729 | val 1.75331
  Epoch 011 - train 0.57252 | val 1.39692
  Classification -> best τ=0.780 (val F1=0.1385)
  Directional -> Accuracy: 0.4638, MCC: 0.0000, F1: 0.0000

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.60108 | val 1.41228
  Epoch 011 - train 0.58528 | val 1.44155
  Classification -> best τ=0.325 (val F1=0.1336)
  Directional -> Accuracy: 0.5862, MCC: 0.1864, F1: 0.6250

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.60661 | val 1.02388
  Epoch 011 - train 0.56125 | val 1.10707
  Classification -> best τ=0.340 (val F1=0.2166)
  Directional -> Accuracy: 0.5600, MCC: 0.0884, F1: 0.6292

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.60808 | val 0.88905
  Epoch 017 - train 0.50487 | val 1.01332
  Classification -> best τ=0.305 (val F1=0.3933)
  Directional -> Accuracy: 0.5156, MCC: 0.0416, F1: 0.5373

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.53257 | val 1.42325
  Epoch 011 - train 0.50627 | val 1.37520
  Classification -> best τ=0.455 (val F1=0.2617)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.60225 | val 1.51776
  Epoch 015 - train 0.47737 | val 1.36049
  Classification -> best τ=0.550 (val F1=0.2861)
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.62587 | val 0.82976
  Epoch 015 - train 0.52561 | val 0.98423
  Classification -> best τ=0.575 (val F1=0.2895)
  Directional -> Accuracy: 0.4923, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.60199 | val 0.62091
  Epoch 018 - train 0.55225 | val 0.68764
  Classification -> best τ=0.555 (val F1=0.5089)
  Directional -> Accuracy: 0.5965, MCC: 0.1771, F1: 0.6462

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.62476 | val 0.79020
  Epoch 015 - train 0.55858 | val 1.13394
  Classification -> best τ=0.560 (val F1=0.2484)
  Directional -> Accuracy: 0.5385, MCC: 0.1091, F1: 0.6154

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.59416 | val 1.72763
  Epoch 012 - train 0.50698 | val 0.91937
  Classification -> best τ=0.445 (val F1=0.5376)
  Directional -> Accuracy: 0.5818, MCC: 0.1913, F1: 0.5490

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.56205 | val 1.50488
  Epoch 011 - train 0.55649 | val 1.45224
  Classification -> best τ=0.605 (val F1=0.4594)
  Directional -> Accuracy: 0.4000, MCC: -0.2590, F1: 0.2286

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.65042 | val 0.77950
  Epoch 019 - train 0.49067 | val 0.75874
  Classification -> best τ=0.605 (val F1=0.2976)
  Directional -> Accuracy: 0.5000, MCC: 0.0782, F1: 0.4000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.53794 | val 1.40071
  Epoch 013 - train 0.55734 | val 1.19511
  Classification -> best τ=0.595 (val F1=0.3967)
  Directional -> Accuracy: 0.4464, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.59841 | val 0.71531
  Epoch 017 - train 0.48634 | val 0.70023
  Classification -> best τ=0.525 (val F1=0.3287)
  Directional -> Accuracy: 0.5750, MCC: 0.1182, F1: 0.6667

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.62955 | val 1.00220
  Epoch 012 - train 0.57649 | val 1.48304
  Classification -> best τ=0.400 (val F1=0.3135)
  Directional -> Accuracy: 0.5238, MCC: 0.0754, F1: 0.6000

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.53626 | val 0.97219
  Epoch 012 - train 0.59101 | val 1.01111
  Classification -> best τ=0.675 (val F1=0.2697)
  Directional -> Accuracy: 0.5952, MCC: 0.3711, F1: 0.4138

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.59974 | val 1.17106
  Epoch 011 - train 0.54342 | val 1.28234
  Classification -> best τ=0.565 (val F1=0.1494)
  Directional -> Accuracy: 0.4286, MCC: -0.1293, F1: 0.3000

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.62933 | val 1.26200
  Epoch 011 - train 0.54349 | val 1.29575
  Classification -> best τ=0.455 (val F1=0.2968)
  Directional -> Accuracy: 0.4444, MCC: 0.0000, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.66320 | val 1.44563
  Epoch 011 - train 0.54143 | val 1.29883
  Classification -> best τ=0.455 (val F1=0.2717)
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.58489 | val 1.16388
  Epoch 011 - train 0.62732 | val 1.34953
  Classification -> best τ=0.420 (val F1=0.2292)
  Directional -> Accuracy: 0.6212, MCC: 0.2550, F1: 0.6377

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.56048 | val 0.95196
  Epoch 011 - train 0.46246 | val 0.97498
  Classification -> best τ=0.495 (val F1=0.2409)
  Directional -> Accuracy: 0.5952, MCC: 0.1850, F1: 0.6383

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.55993 | val 0.94034
  Epoch 011 - train 0.56025 | val 1.04728
  Classification -> best τ=0.455 (val F1=0.2382)
  Directional -> Accuracy: 0.5714, MCC: 0.1807, F1: 0.6250

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.49808 | val 1.25650
  Epoch 011 - train 0.46000 | val 1.20699
  Classification -> best τ=0.395 (val F1=0.1709)
  Directional -> Accuracy: 0.5870, MCC: -0.1195, F1: 0.7397

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.55052 | val 0.68128
  Epoch 020 - train 0.52276 | val 0.63992
  Epoch 021 - train 0.54062 | val 0.65684
  Classification -> best τ=0.405 (val F1=0.4011)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.56234 | val 2.20965
  Epoch 011 - train 0.52577 | val 2.21657
  Classification -> best τ=0.275 (val F1=0.2982)
  Directional -> Accuracy: 0.4595, MCC: -0.0855, F1: 0.4118

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.60067 | val 0.83423
  Epoch 013 - train 0.67876 | val 1.02093
  Classification -> best τ=0.395 (val F1=0.3857)
  Directional -> Accuracy: 0.5111, MCC: 0.0000, F1: 0.6765

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.51088 | val 2.41687
  Epoch 012 - train 0.44199 | val 2.71036
  Classification -> best τ=0.540 (val F1=0.3015)
  Directional -> Accuracy: 0.6190, MCC: 0.2041, F1: 0.6923

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.56711 | val 0.62064
  Epoch 016 - train 0.45401 | val 0.82107
  Classification -> best τ=0.685 (val F1=0.5689)
  Directional -> Accuracy: 0.4583, MCC: 0.2335, F1: 0.5806

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.67274 | val 0.91566
  Epoch 014 - train 0.61279 | val 1.77118
  Classification -> best τ=0.630 (val F1=0.1647)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.52503 | val 1.68273
  Epoch 011 - train 0.55014 | val 2.04836
  Classification -> best τ=0.770 (val F1=0.2720)
  Directional -> Accuracy: 0.4464, MCC: -0.1019, F1: 0.4918

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.69934 | val 1.35287
  Epoch 011 - train 0.60566 | val 1.35284
  Classification -> best τ=0.490 (val F1=0.3392)
  Directional -> Accuracy: 0.5094, MCC: 0.0000, F1: 0.6750

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.56730 | val 1.97333
  Epoch 011 - train 0.53584 | val 2.08458
  Classification -> best τ=0.645 (val F1=0.1154)
  Directional -> Accuracy: 0.5273, MCC: 0.0000, F1: 0.6905

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.62231 | val 0.66756

[I 2026-02-22 11:58:56,159] Trial 159 finished with value: 0.297766251520741 and parameters: {'feature_set': 'sector', 'model_type': 'BiGRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.6000000000000001, 'batch_size': 16, 'learning_rate': 0.004911987457423672, 'weight_decay': 2.0403224706511107e-05, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 1.1087356625990796, 'early_stopping_min_delta': 3.4691004242167785e-05}. Best is trial 159 with value: 0.297766251520741.

  Epoch 016 - train 0.54898 | val 0.73665
  Classification -> best τ=0.515 (val F1=0.2920)
  Directional -> Accuracy: 0.5333, MCC: 0.0842, F1: 0.1250

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.297766251520741
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.61740 | val 0.82087
  Epoch 011 - train 0.61250 | val 0.91040
  Classification -> best τ=0.655 (val F1=0.2510)
  Directional -> Accuracy: 0.5658, MCC: 0.0815, F1: 0.1538

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.58026 | val 1.26007
  Epoch 011 - train 0.51536 | val 1.29256
  Classification -> best τ=0.475 (val F1=0.1478)
  Directional -> Accuracy: 0.5778, MCC: 0.0340, F1: 0.7246

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.60286 | val 0.97564
  Epoch 011 - train 0.59804 | val 1.02544
  Classification -> best τ=0.620 (val F1=0.2398)
  Directional -> Accuracy: 0.4783, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.64252 | val 0.81175
  Epoch 011 - train 0.62905 | val 0.83079
  Classification -> best τ=0.390 (val F1=0.1839)
  Directional -> Accuracy: 0.5405, MCC: 0.0000, F1: 0.7018

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.51989 | val 1.20583
  Epoch 012 - train 0.54991 | val 1.13433
  Classification -> best τ=0.655 (val F1=0.4851)
  Directional -> Accuracy: 0.6200, MCC: 0.2670, F1: 0.5581

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.56220 | val 0.71574
  Epoch 012 - train 0.53342 | val 0.76640
  Classification -> best τ=0.520 (val F1=0.2871)
  Directional -> Accuracy: 0.5217, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.64952 | val 1.19781
  Epoch 011 - train 0.62495 | val 1.36631
  Classification -> best τ=0.465 (val F1=0.3069)
  Directional -> Accuracy: 0.5000, MCC: 0.0443, F1: 0.5000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.56914 | val 1.07297
  Epoch 011 - train 0.55855 | val 1.24817
  Classification -> best τ=0.580 (val F1=0.1228)
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.62342 | val 1.15781
  Epoch 011 - train 0.59856 | val 1.16232
  Classification -> best τ=0.540 (val F1=0.2584)
  Directional -> Accuracy: 0.6042, MCC: 0.1843, F1: 0.5128

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.58450 | val 1.00950
  Epoch 011 - train 0.58282 | val 0.96212
  Classification -> best τ=0.320 (val F1=0.2071)
  Directional -> Accuracy: 0.4638, MCC: 0.0916, F1: 0.5934

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.60302 | val 0.83838
  Epoch 011 - train 0.57338 | val 0.90634
  Classification -> best τ=0.575 (val F1=0.2687)
  Directional -> Accuracy: 0.5918, MCC: 0.1804, F1: 0.2308

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.62806 | val 0.96936
  Epoch 011 - train 0.60959 | val 0.99394
  Classification -> best τ=0.620 (val F1=0.2083)
  Directional -> Accuracy: 0.5263, MCC: 0.1326, F1: 0.1818

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.52637 | val 1.82932
  Epoch 011 - train 0.53458 | val 2.00476
  Classification -> best τ=0.415 (val F1=0.1658)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.6230

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.60519 | val 0.58463
  Epoch 020 - train 0.53657 | val 0.65075
  Classification -> best τ=0.560 (val F1=0.4746)
  Directional -> Accuracy: 0.5167, MCC: 0.0431, F1: 0.2927

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.60736 | val 0.98333
  Epoch 018 - train 0.54530 | val 0.96500
  Classification -> best τ=0.440 (val F1=0.2157)
  Directional -> Accuracy: 0.5490, MCC: 0.1684, F1: 0.6230

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.62124 | val 0.94291
  Epoch 012 - train 0.57929 | val 0.83148
  Classification -> best τ=0.345 (val F1=0.2224)
  Directional -> Accuracy: 0.5072, MCC: -0.0526, F1: 0.6458

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.60069 | val 1.31458
  Epoch 012 - train 0.58134 | val 1.31923
  Classification -> best τ=0.500 (val F1=0.2743)
  Directional -> Accuracy: 0.4310, MCC: -0.2193, F1: 0.5479

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.56977 | val 1.08546
  Epoch 011 - train 0.56255 | val 1.11638
  Classification -> best τ=0.540 (val F1=0.1909)
  Directional -> Accuracy: 0.4000, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.61990 | val 0.75148
  Epoch 013 - train 0.57509 | val 0.79071
  Classification -> best τ=0.290 (val F1=0.2843)
  Directional -> Accuracy: 0.5000, MCC: 0.1376, F1: 0.3333

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.57045 | val 1.52454
  Epoch 011 - train 0.53603 | val 1.48930
  Classification -> best τ=0.495 (val F1=0.2588)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.55002 | val 1.14580
  Epoch 012 - train 0.57846 | val 1.20209
  Classification -> best τ=0.470 (val F1=0.3237)
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.63860 | val 0.77049
  Epoch 011 - train 0.58555 | val 0.76433
  Classification -> best τ=0.490 (val F1=0.1968)
  Directional -> Accuracy: 0.5846, MCC: 0.1703, F1: 0.6301

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.61319 | val 0.66627
  Epoch 016 - train 0.57749 | val 0.73072
  Classification -> best τ=0.675 (val F1=0.4639)
  Directional -> Accuracy: 0.5088, MCC: 0.1095, F1: 0.3636

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.63586 | val 0.83084
  Epoch 011 - train 0.61352 | val 0.87151
  Classification -> best τ=0.400 (val F1=0.1793)
  Directional -> Accuracy: 0.4769, MCC: 0.0000, F1: 0.6458

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.58267 | val 1.06545
  Epoch 012 - train 0.51503 | val 1.20747
  Classification -> best τ=0.640 (val F1=0.4603)
  Directional -> Accuracy: 0.5273, MCC: 0.1463, F1: 0.3500

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.57202 | val 1.68947
  Epoch 011 - train 0.55752 | val 1.84073
  Classification -> best τ=0.555 (val F1=0.2726)
  Directional -> Accuracy: 0.5333, MCC: 0.0503, F1: 0.4615

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.62189 | val 0.88075
  Epoch 011 - train 0.61317 | val 0.92565
  Classification -> best τ=0.440 (val F1=0.1353)
  Directional -> Accuracy: 0.5714, MCC: 0.1514, F1: 0.5909

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.56947 | val 1.07631
  Epoch 011 - train 0.54279 | val 1.13871
  Classification -> best τ=0.350 (val F1=0.1607)
  Directional -> Accuracy: 0.5357, MCC: 0.0926, F1: 0.5185

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.58485 | val 0.79201
  Epoch 013 - train 0.52654 | val 0.82938
  Classification -> best τ=0.540 (val F1=0.4109)
  Directional -> Accuracy: 0.6000, MCC: 0.2010, F1: 0.7241

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.61572 | val 0.83882
  Epoch 014 - train 0.55485 | val 0.85792
  Classification -> best τ=0.680 (val F1=0.2814)
  Directional -> Accuracy: 0.5000, MCC: -0.0196, F1: 0.3636

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.63448 | val 1.10554
  Epoch 011 - train 0.61244 | val 1.19353
  Classification -> best τ=0.580 (val F1=0.1286)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.54190 | val 1.01998
  Epoch 012 - train 0.51138 | val 0.98351
  Classification -> best τ=0.390 (val F1=0.3232)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.57389 | val 1.00761
  Epoch 013 - train 0.55520 | val 0.93052
  Classification -> best τ=0.340 (val F1=0.2888)
  Directional -> Accuracy: 0.5556, MCC: 0.0000, F1: 0.7143

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.57314 | val 0.81872
  Epoch 011 - train 0.58036 | val 0.85592
  Classification -> best τ=0.475 (val F1=0.1874)
  Directional -> Accuracy: 0.4884, MCC: -0.0261, F1: 0.4500

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.62926 | val 0.89845
  Epoch 011 - train 0.60151 | val 0.94470
  Classification -> best τ=0.395 (val F1=0.3254)
  Directional -> Accuracy: 0.5909, MCC: 0.3480, F1: 0.4706

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.56846 | val 2.03349
  Epoch 012 - train 0.52397 | val 2.03907
  Classification -> best τ=0.510 (val F1=0.2439)
  Directional -> Accuracy: 0.5476, MCC: 0.0830, F1: 0.6545

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.54591 | val 0.84736
  Epoch 012 - train 0.52225 | val 0.93230
  Classification -> best τ=0.325 (val F1=0.1677)
  Directional -> Accuracy: 0.4643, MCC: -0.0534, F1: 0.5161

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.50704 | val 0.86433
  Epoch 011 - train 0.49656 | val 0.83988
  Classification -> best τ=0.475 (val F1=0.1709)
  Directional -> Accuracy: 0.6087, MCC: 0.0000, F1: 0.7568

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.59500 | val 0.78139
  Epoch 011 - train 0.60116 | val 0.78521
  Classification -> best τ=0.560 (val F1=0.4011)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.53586 | val 1.35563
  Epoch 011 - train 0.55115 | val 1.45985
  Classification -> best τ=0.355 (val F1=0.2611)
  Directional -> Accuracy: 0.4865, MCC: 0.0000, F1: 0.6545

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.60134 | val 0.86439
  Epoch 011 - train 0.61502 | val 0.89103
  Classification -> best τ=0.505 (val F1=0.4158)
  Directional -> Accuracy: 0.5111, MCC: 0.0000, F1: 0.6765

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.52028 | val 1.03620
  Epoch 011 - train 0.52947 | val 1.04894
  Classification -> best τ=0.515 (val F1=0.0602)
  Directional -> Accuracy: 0.4524, MCC: -0.0446, F1: 0.3784

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.55027 | val 0.70673
  Epoch 011 - train 0.54093 | val 0.68181
  Classification -> best τ=0.530 (val F1=0.1702)
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.5455

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.65269 | val 0.97633
  Epoch 013 - train 0.63590 | val 1.03793
  Classification -> best τ=0.640 (val F1=0.2036)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.51260 | val 1.72477
  Epoch 011 - train 0.53039 | val 1.85621
  Classification -> best τ=0.565 (val F1=0.3633)
  Directional -> Accuracy: 0.5893, MCC: 0.2633, F1: 0.6849

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.65831 | val 1.02494
  Epoch 011 - train 0.64208 | val 0.92847
  Classification -> best τ=0.480 (val F1=0.1289)
  Directional -> Accuracy: 0.5094, MCC: 0.0113, F1: 0.6061

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.57019 | val 3.03160
  Epoch 011 - train 0.53739 | val 3.71588
  Classification -> best τ=0.655 (val F1=0.1246)
  Directional -> Accuracy: 0.5273, MCC: 0.0000, F1: 0.6905

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.63454 | val 1.47132
  Epoch 011 - train 0.61661 | val 1.29920

[I 2026-02-22 12:00:38,280] Trial 160 finished with value: 0.25326422030808643 and parameters: {'feature_set': 'sector', 'model_type': 'BiGRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 32, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.6000000000000001, 'batch_size': 16, 'learning_rate': 0.00239482134356938, 'weight_decay': 1.8015099295834568e-05, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 1.1086504337150271, 'early_stopping_min_delta': 3.263704009917381e-05}. Best is trial 159 with value: 0.297766251520741.

  Classification -> best τ=0.565 (val F1=0.2534)
  Directional -> Accuracy: 0.5167, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.25326422030808643
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.64167 | val 0.75334
  Epoch 012 - train 0.61223 | val 0.91765
  Classification -> best τ=0.655 (val F1=0.2510)
  Directional -> Accuracy: 0.5526, MCC: 0.0363, F1: 0.1905

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.59135 | val 1.16284
  Epoch 011 - train 0.59247 | val 1.08290
  Classification -> best τ=0.440 (val F1=0.1722)
  Directional -> Accuracy: 0.5778, MCC: 0.0000, F1: 0.7324

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.61334 | val 1.11320
  Epoch 011 - train 0.61090 | val 1.10985
  Classification -> best τ=0.610 (val F1=0.2861)
  Directional -> Accuracy: 0.4783, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.61039 | val 0.74437
  Epoch 019 - train 0.54265 | val 0.96479
  Classification -> best τ=0.325 (val F1=0.2230)
  Directional -> Accuracy: 0.5405, MCC: 0.0000, F1: 0.7018

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.57940 | val 0.76927
  Epoch 013 - train 0.47245 | val 0.70184
  Classification -> best τ=0.550 (val F1=0.4851)
  Directional -> Accuracy: 0.5800, MCC: 0.2044, F1: 0.4615

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.51165 | val 1.17098
  Epoch 011 - train 0.54724 | val 1.08290
  Classification -> best τ=0.580 (val F1=0.2463)
  Directional -> Accuracy: 0.5217, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.64771 | val 1.33793
  Epoch 011 - train 0.61137 | val 1.34916
  Classification -> best τ=0.545 (val F1=0.3514)
  Directional -> Accuracy: 0.5294, MCC: 0.1521, F1: 0.5676

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.62827 | val 1.08787
  Epoch 014 - train 0.68375 | val 1.29525
  Classification -> best τ=0.320 (val F1=0.3632)
  Directional -> Accuracy: 0.4048, MCC: -0.2676, F1: 0.1935

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.59920 | val 1.15169
  Epoch 011 - train 0.59635 | val 1.46902
  Classification -> best τ=0.595 (val F1=0.2443)
  Directional -> Accuracy: 0.5625, MCC: 0.2182, F1: 0.6316

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.63120 | val 0.86212
  Epoch 019 - train 0.54384 | val 0.88909
  Classification -> best τ=0.490 (val F1=0.1876)
  Directional -> Accuracy: 0.4928, MCC: 0.0112, F1: 0.4928

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.66437 | val 0.92722
  Epoch 013 - train 0.58709 | val 0.85423
  Classification -> best τ=0.670 (val F1=0.3072)
  Directional -> Accuracy: 0.5918, MCC: 0.1804, F1: 0.2308

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.67253 | val 0.82619
  Epoch 012 - train 0.65544 | val 0.96132
  Classification -> best τ=0.335 (val F1=0.2960)
  Directional -> Accuracy: 0.5088, MCC: 0.0000, F1: 0.6744

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.55554 | val 2.92688
  Epoch 011 - train 0.52378 | val 2.90304
  Classification -> best τ=0.440 (val F1=0.1370)
  Directional -> Accuracy: 0.4762, MCC: -0.0673, F1: 0.3889

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.65167 | val 0.61595
  Epoch 020 - train 0.53839 | val 0.62427
  Epoch 022 - train 0.56927 | val 0.69007
  Classification -> best τ=0.600 (val F1=0.3864)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.60053 | val 0.76320
  Epoch 011 - train 0.60622 | val 0.77453
  Classification -> best τ=0.575 (val F1=0.2571)
  Directional -> Accuracy: 0.5490, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.62193 | val 0.82846
  Epoch 011 - train 0.60756 | val 0.86803
  Classification -> best τ=0.340 (val F1=0.2795)
  Directional -> Accuracy: 0.5652, MCC: 0.1858, F1: 0.7115

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.63502 | val 0.94536
  Epoch 011 - train 0.60523 | val 0.94379
  Classification -> best τ=0.430 (val F1=0.1336)
  Directional -> Accuracy: 0.5517, MCC: -0.1066, F1: 0.6977

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.59753 | val 0.93934
  Epoch 011 - train 0.59731 | val 1.02286
  Classification -> best τ=0.405 (val F1=0.1750)
  Directional -> Accuracy: 0.5867, MCC: 0.3077, F1: 0.5231

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.61669 | val 0.87670
  Epoch 011 - train 0.60720 | val 0.90134
  Classification -> best τ=0.500 (val F1=0.2940)
  Directional -> Accuracy: 0.5000, MCC: 0.0992, F1: 0.3846

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.54374 | val 1.12587
  Epoch 011 - train 0.54287 | val 1.19231
  Classification -> best τ=0.485 (val F1=0.2470)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.56053 | val 1.36234
  Epoch 011 - train 0.65299 | val 1.63870
  Classification -> best τ=0.385 (val F1=0.2416)
  Directional -> Accuracy: 0.4043, MCC: 0.0267, F1: 0.1250

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.69214 | val 0.73025
  Epoch 011 - train 0.65102 | val 0.78891
  Classification -> best τ=0.510 (val F1=0.1664)
  Directional -> Accuracy: 0.4923, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.66754 | val 0.63760
  Epoch 020 - train 0.62625 | val 0.71337
  Epoch 025 - train 0.55630 | val 0.72754
  Classification -> best τ=0.460 (val F1=0.4360)
  Directional -> Accuracy: 0.6316, MCC: 0.2825, F1: 0.6316

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.65354 | val 0.70487
  Epoch 012 - train 0.61715 | val 0.69493
  Classification -> best τ=0.445 (val F1=0.2712)
  Directional -> Accuracy: 0.4462, MCC: -0.1134, F1: 0.4000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.56663 | val 1.22784
  Epoch 012 - train 0.55260 | val 1.54736
  Classification -> best τ=0.370 (val F1=0.4688)
  Directional -> Accuracy: 0.5273, MCC: 0.0920, F1: 0.4583

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.55666 | val 4.48517
  Epoch 011 - train 0.53984 | val 4.37341
  Classification -> best τ=0.590 (val F1=0.1956)
  Directional -> Accuracy: 0.4222, MCC: -0.2021, F1: 0.2778

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.66488 | val 0.78362
  Epoch 011 - train 0.63059 | val 0.80243
  Classification -> best τ=0.550 (val F1=0.1936)
  Directional -> Accuracy: 0.3333, MCC: -0.3339, F1: 0.0667

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.64338 | val 1.30818
  Epoch 011 - train 0.56838 | val 1.34373
  Classification -> best τ=0.230 (val F1=0.2315)
  Directional -> Accuracy: 0.5714, MCC: 0.0985, F1: 0.6842

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.69269 | val 0.71949
  Epoch 011 - train 0.58072 | val 0.71588
  Classification -> best τ=0.625 (val F1=0.1748)
  Directional -> Accuracy: 0.5250, MCC: 0.0453, F1: 0.5581

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.63998 | val 1.30136
  Epoch 011 - train 0.62179 | val 1.42769
  Classification -> best τ=0.500 (val F1=0.3612)
  Directional -> Accuracy: 0.5000, MCC: 0.0196, F1: 0.5714

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.64820 | val 0.89748
  Epoch 011 - train 0.64948 | val 0.96581
  Classification -> best τ=0.685 (val F1=0.1286)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.55398 | val 0.85645
  Epoch 011 - train 0.55160 | val 0.89066
  Classification -> best τ=0.455 (val F1=0.2812)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.63627 | val 0.81292
  Epoch 011 - train 0.63581 | val 0.78649
  Classification -> best τ=0.420 (val F1=0.3066)
  Directional -> Accuracy: 0.4861, MCC: 0.1865, F1: 0.1395

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.57650 | val 0.83190
  Epoch 011 - train 0.54917 | val 0.88053
  Classification -> best τ=0.480 (val F1=0.2465)
  Directional -> Accuracy: 0.4884, MCC: -0.0452, F1: 0.2667

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.60883 | val 1.36605
  Epoch 011 - train 0.57940 | val 1.71072
  Classification -> best τ=0.680 (val F1=0.2951)
  Directional -> Accuracy: 0.4545, MCC: 0.1517, F1: 0.1000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.56781 | val 1.25904
  Epoch 011 - train 0.48698 | val 1.66431
  Classification -> best τ=0.485 (val F1=0.2067)
  Directional -> Accuracy: 0.5952, MCC: 0.2035, F1: 0.5641

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.56045 | val 1.26147
  Epoch 011 - train 0.54260 | val 1.17327
  Classification -> best τ=0.495 (val F1=0.2755)
  Directional -> Accuracy: 0.6250, MCC: 0.3031, F1: 0.6769

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.57176 | val 1.30654
  Epoch 011 - train 0.54849 | val 1.20424
  Classification -> best τ=0.620 (val F1=0.2659)
  Directional -> Accuracy: 0.4565, MCC: -0.0511, F1: 0.4681

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.62438 | val 0.73736
  Epoch 011 - train 0.59688 | val 0.70071
  Classification -> best τ=0.465 (val F1=0.2928)
  Directional -> Accuracy: 0.5625, MCC: -0.1482, F1: 0.0870

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.60527 | val 1.56893
  Epoch 011 - train 0.55012 | val 1.80671
  Classification -> best τ=0.515 (val F1=0.2547)
  Directional -> Accuracy: 0.4459, MCC: -0.1279, F1: 0.3051

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.70245 | val 0.66639
  Epoch 018 - train 0.58566 | val 0.75963
  Classification -> best τ=0.465 (val F1=0.4375)
  Directional -> Accuracy: 0.5111, MCC: 0.0000, F1: 0.6765

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.49866 | val 2.30058
  Epoch 011 - train 0.45240 | val 2.32641
  Classification -> best τ=0.570 (val F1=0.2500)
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.0000

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.60113 | val 0.58940
  Epoch 020 - train 0.44821 | val 0.61763
  Epoch 021 - train 0.44400 | val 0.57937
  Classification -> best τ=0.540 (val F1=0.6058)
  Directional -> Accuracy: 0.5625, MCC: 0.2784, F1: 0.6038

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.59364 | val 1.34401
  Epoch 011 - train 0.64327 | val 1.59250
  Classification -> best τ=0.630 (val F1=0.3238)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.53152 | val 2.65594
  Epoch 011 - train 0.56841 | val 2.50440
  Classification -> best τ=0.700 (val F1=0.2386)
  Directional -> Accuracy: 0.5000, MCC: 0.1301, F1: 0.6585

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.70262 | val 0.74513
  Epoch 020 - train 0.62243 | val 1.37455
  Epoch 024 - train 0.53734 | val 0.99755
  Classification -> best τ=0.320 (val F1=0.2866)
  Directional -> Accuracy: 0.5849, MCC: 0.2912, F1: 0.7105

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.59575 | val 3.46593
  Epoch 011 - train 0.57338 | val 3.57120
  Classification -> best τ=0.835 (val F1=0.1154)
  Directional -> Accuracy: 0.5273, MCC: 0.0000, F1: 0.6905

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.67316 | val 0.74862

[I 2026-02-22 12:03:14,921] Trial 161 finished with value: 0.2736965789156975 and parameters: {'feature_set': 'sector', 'model_type': 'BiGRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.7000000000000001, 'batch_size': 16, 'learning_rate': 0.004776492041567914, 'weight_decay': 1.97883682338365e-05, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 1.1055900217721921, 'early_stopping_min_delta': 3.577555273902982e-06}. Best is trial 159 with value: 0.297766251520741.

  Epoch 018 - train 0.59271 | val 0.72021
  Classification -> best τ=0.650 (val F1=0.2623)
  Directional -> Accuracy: 0.5167, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2736965789156975
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.61643 | val 0.95028
  Epoch 011 - train 0.58207 | val 1.08033
  Classification -> best τ=0.490 (val F1=0.2036)
  Directional -> Accuracy: 0.5395, MCC: 0.0358, F1: 0.3636

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.51352 | val 0.96296
  Epoch 011 - train 0.48178 | val 1.10218
  Classification -> best τ=0.445 (val F1=0.1844)
  Directional -> Accuracy: 0.5778, MCC: 0.0000, F1: 0.7324

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.56033 | val 2.37617
  Epoch 011 - train 0.46860 | val 2.31472
  Classification -> best τ=0.590 (val F1=0.2311)
  Directional -> Accuracy: 0.4783, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.60213 | val 0.71784
  Epoch 020 - train 0.51727 | val 0.99441
  Epoch 022 - train 0.45625 | val 0.71550
  Classification -> best τ=0.455 (val F1=0.2920)
  Directional -> Accuracy: 0.5135, MCC: -0.0231, F1: 0.6327

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.50719 | val 1.23861
  Epoch 012 - train 0.44316 | val 1.54690
  Classification -> best τ=0.585 (val F1=0.4493)
  Directional -> Accuracy: 0.5800, MCC: 0.1825, F1: 0.5116

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.49823 | val 0.91035
  Epoch 015 - train 0.39192 | val 1.06836
  Classification -> best τ=0.705 (val F1=0.3963)
  Directional -> Accuracy: 0.5217, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.59116 | val 0.92964
  Epoch 011 - train 0.57346 | val 0.95361
  Classification -> best τ=0.430 (val F1=0.3010)
  Directional -> Accuracy: 0.5294, MCC: 0.1521, F1: 0.5676

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.41953 | val 0.83496
  Epoch 019 - train 0.33457 | val 0.75441
  Classification -> best τ=0.140 (val F1=0.3094)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.5660

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.54320 | val 1.45419
  Epoch 011 - train 0.52978 | val 1.74237
  Classification -> best τ=0.630 (val F1=0.1928)
  Directional -> Accuracy: 0.5833, MCC: 0.1187, F1: 0.3750

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.61006 | val 0.94539
  Epoch 013 - train 0.52337 | val 0.98262
  Classification -> best τ=0.585 (val F1=0.1200)
  Directional -> Accuracy: 0.4783, MCC: -0.0511, F1: 0.4194

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.57320 | val 0.88327
  Epoch 011 - train 0.55111 | val 0.87722
  Classification -> best τ=0.545 (val F1=0.3020)
  Directional -> Accuracy: 0.6122, MCC: 0.2379, F1: 0.2963

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.56064 | val 1.38562
  Epoch 011 - train 0.53623 | val 1.66296
  Classification -> best τ=0.435 (val F1=0.2157)
  Directional -> Accuracy: 0.5088, MCC: 0.0000, F1: 0.6744

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.48827 | val 1.67814
  Epoch 011 - train 0.46713 | val 2.02731
  Classification -> best τ=0.490 (val F1=0.1754)
  Directional -> Accuracy: 0.4524, MCC: -0.1711, F1: 0.2069

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.59179 | val 0.65816
  Epoch 012 - train 0.53084 | val 0.66348
  Classification -> best τ=0.420 (val F1=0.3281)
  Directional -> Accuracy: 0.5167, MCC: 0.0467, F1: 0.2564

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.52918 | val 0.72933
  Epoch 017 - train 0.44952 | val 0.85988
  Classification -> best τ=0.645 (val F1=0.0921)
  Directional -> Accuracy: 0.6078, MCC: 0.1954, F1: 0.4118

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.58046 | val 0.99950
  Epoch 011 - train 0.54250 | val 1.03989
  Classification -> best τ=0.405 (val F1=0.2795)
  Directional -> Accuracy: 0.5507, MCC: 0.0867, F1: 0.6990

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.59545 | val 1.11268
  Epoch 011 - train 0.55577 | val 1.23527
  Classification -> best τ=0.450 (val F1=0.1336)
  Directional -> Accuracy: 0.6379, MCC: 0.1467, F1: 0.7586

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.56243 | val 1.09368
  Epoch 011 - train 0.50390 | val 1.07539
  Classification -> best τ=0.560 (val F1=0.2500)
  Directional -> Accuracy: 0.4000, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.51842 | val 0.94380
  Epoch 012 - train 0.49217 | val 1.07653
  Classification -> best τ=0.625 (val F1=0.1771)
  Directional -> Accuracy: 0.4375, MCC: 0.1076, F1: 0.0526

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.55604 | val 0.98928
  Epoch 011 - train 0.49060 | val 0.99474
  Classification -> best τ=0.465 (val F1=0.2312)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.52655 | val 0.88664
  Epoch 011 - train 0.51754 | val 0.80160
  Classification -> best τ=0.475 (val F1=0.2247)
  Directional -> Accuracy: 0.6170, MCC: 0.0000, F1: 0.7632

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.53608 | val 0.83474
  Epoch 011 - train 0.55205 | val 0.92304
  Classification -> best τ=0.535 (val F1=0.1761)
  Directional -> Accuracy: 0.4154, MCC: -0.1709, F1: 0.4412

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.60643 | val 0.71748
  Epoch 017 - train 0.47654 | val 0.82378
  Classification -> best τ=0.765 (val F1=0.3749)
  Directional -> Accuracy: 0.4737, MCC: 0.0518, F1: 0.2500

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.59231 | val 1.62324
  Epoch 013 - train 0.54370 | val 1.25744
  Classification -> best τ=0.395 (val F1=0.2774)
  Directional -> Accuracy: 0.5385, MCC: 0.0923, F1: 0.5833

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.53414 | val 1.18551
  Epoch 012 - train 0.48794 | val 1.13465
  Classification -> best τ=0.290 (val F1=0.5197)
  Directional -> Accuracy: 0.5818, MCC: 0.1733, F1: 0.5818

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.45525 | val 2.38081
  Epoch 011 - train 0.50743 | val 2.60187
  Classification -> best τ=0.520 (val F1=0.2935)
  Directional -> Accuracy: 0.4444, MCC: 0.0159, F1: 0.5763

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.53941 | val 0.85192
  Epoch 011 - train 0.51527 | val 0.88943
  Classification -> best τ=0.475 (val F1=0.2582)
  Directional -> Accuracy: 0.5952, MCC: 0.1925, F1: 0.6222

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.52519 | val 1.08180
  Epoch 011 - train 0.51103 | val 1.09919
  Classification -> best τ=0.405 (val F1=0.2386)
  Directional -> Accuracy: 0.4464, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.50075 | val 1.42774
  Epoch 013 - train 0.46529 | val 1.10656
  Classification -> best τ=0.545 (val F1=0.4109)
  Directional -> Accuracy: 0.5750, MCC: 0.1240, F1: 0.7119

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.56986 | val 0.80387
  Epoch 012 - train 0.52886 | val 1.51584
  Classification -> best τ=0.480 (val F1=0.4846)
  Directional -> Accuracy: 0.4524, MCC: -0.1137, F1: 0.3429

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.54484 | val 1.28672
  Epoch 011 - train 0.60018 | val 1.25376
  Classification -> best τ=0.490 (val F1=0.1286)
  Directional -> Accuracy: 0.5714, MCC: 0.2781, F1: 0.4000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.53631 | val 0.75518
  Epoch 012 - train 0.42027 | val 1.02591
  Classification -> best τ=0.640 (val F1=0.3465)
  Directional -> Accuracy: 0.5102, MCC: 0.0323, F1: 0.4783

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.55624 | val 1.48059
  Epoch 013 - train 0.48922 | val 1.13971
  Classification -> best τ=0.305 (val F1=0.3346)
  Directional -> Accuracy: 0.5694, MCC: 0.1327, F1: 0.7207

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.49395 | val 1.54129
  Epoch 011 - train 0.43401 | val 1.66989
  Classification -> best τ=0.345 (val F1=0.2324)
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.53194 | val 1.19090
  Epoch 011 - train 0.56147 | val 1.08384
  Classification -> best τ=0.400 (val F1=0.2464)
  Directional -> Accuracy: 0.5758, MCC: 0.0000, F1: 0.7308

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.48086 | val 2.42533
  Epoch 011 - train 0.41709 | val 3.04288
  Classification -> best τ=0.455 (val F1=0.2228)
  Directional -> Accuracy: 0.6429, MCC: 0.3127, F1: 0.5946

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.51342 | val 1.02353
  Epoch 011 - train 0.55451 | val 0.98356
  Classification -> best τ=0.455 (val F1=0.2110)
  Directional -> Accuracy: 0.6429, MCC: 0.3090, F1: 0.6667

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.49769 | val 1.08299
  Epoch 011 - train 0.46778 | val 1.07493
  Classification -> best τ=0.470 (val F1=0.2157)
  Directional -> Accuracy: 0.5870, MCC: -0.1195, F1: 0.7397

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.54094 | val 0.81749
  Epoch 013 - train 0.54083 | val 0.99793
  Classification -> best τ=0.480 (val F1=0.4011)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.57208 | val 2.05253
  Epoch 012 - train 0.51267 | val 2.14524
  Classification -> best τ=0.455 (val F1=0.2367)
  Directional -> Accuracy: 0.5000, MCC: 0.0029, F1: 0.5195

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.57966 | val 0.72471
  Epoch 016 - train 0.49593 | val 0.93308
  Classification -> best τ=0.590 (val F1=0.4080)
  Directional -> Accuracy: 0.5333, MCC: 0.0786, F1: 0.6667

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.48278 | val 2.85762
  Epoch 012 - train 0.42193 | val 2.69800
  Classification -> best τ=0.550 (val F1=0.2677)
  Directional -> Accuracy: 0.5476, MCC: 0.0700, F1: 0.6122

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.46291 | val 0.85713
  Epoch 012 - train 0.37779 | val 0.92666
  Classification -> best τ=0.495 (val F1=0.4371)
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.5455

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.58039 | val 2.26847
  Epoch 011 - train 0.64280 | val 2.01329
  Classification -> best τ=0.560 (val F1=0.2754)
  Directional -> Accuracy: 0.4182, MCC: -0.1415, F1: 0.3333

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.47641 | val 1.93451
  Epoch 011 - train 0.42431 | val 2.20761
  Classification -> best τ=0.435 (val F1=0.2137)
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.6506

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.65828 | val 1.02818
  Epoch 011 - train 0.61412 | val 0.92913
  Classification -> best τ=0.450 (val F1=0.2155)
  Directional -> Accuracy: 0.5660, MCC: 0.1343, F1: 0.6349

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.58012 | val 3.60655
  Epoch 011 - train 0.50523 | val 2.92739
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5273, MCC: 0.0000, F1: 0.6905

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.60942 | val 1.19897

[I 2026-02-22 12:05:41,608] Trial 162 finished with value: 0.2652568852937867 and parameters: {'feature_set': 'sector', 'model_type': 'BiGRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.4, 'batch_size': 16, 'learning_rate': 0.004692429288790708, 'weight_decay': 2.015583800580585e-05, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 1.1634988535059214, 'early_stopping_min_delta': 0.00012938050544772123}. Best is trial 159 with value: 0.297766251520741.

  Epoch 011 - train 0.53705 | val 1.03472
  Classification -> best τ=0.485 (val F1=0.2160)
  Directional -> Accuracy: 0.5333, MCC: 0.0679, F1: 0.5333

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2652568852937867
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.62533 | val 0.79351
  Epoch 011 - train 0.63434 | val 0.80795
  Classification -> best τ=0.485 (val F1=0.2125)
  Directional -> Accuracy: 0.5658, MCC: 0.1793, F1: 0.6118

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.59326 | val 1.00058
  Epoch 011 - train 0.60388 | val 1.13396
  Classification -> best τ=0.435 (val F1=0.1857)
  Directional -> Accuracy: 0.5778, MCC: 0.0000, F1: 0.7324

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.68594 | val 0.75694
  Epoch 013 - train 0.63188 | val 0.81509
  Classification -> best τ=0.595 (val F1=0.3114)
  Directional -> Accuracy: 0.4783, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.69951 | val 0.79572
  Epoch 020 - train 0.60082 | val 0.80768
  Epoch 021 - train 0.61788 | val 0.80266
  Classification -> best τ=0.495 (val F1=0.1537)
  Directional -> Accuracy: 0.4595, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.57996 | val 0.90956
  Epoch 011 - train 0.62049 | val 0.95991
  Classification -> best τ=0.585 (val F1=0.3612)
  Directional -> Accuracy: 0.5800, MCC: 0.1922, F1: 0.4878

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.58750 | val 0.79409
  Epoch 016 - train 0.60600 | val 0.72435
  Classification -> best τ=0.625 (val F1=0.3994)
  Directional -> Accuracy: 0.5217, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.66093 | val 0.88629
  Epoch 019 - train 0.60738 | val 1.03776
  Classification -> best τ=0.555 (val F1=0.3977)
  Directional -> Accuracy: 0.4706, MCC: 0.0888, F1: 0.5610

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.63858 | val 0.86278
  Epoch 020 - train 0.62871 | val 1.25854
  Epoch 022 - train 0.51472 | val 0.84195
  Classification -> best τ=0.340 (val F1=0.2168)
  Directional -> Accuracy: 0.5000, MCC: 0.0430, F1: 0.5333

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.64482 | val 1.59971
  Epoch 011 - train 0.62272 | val 1.67633
  Classification -> best τ=0.600 (val F1=0.4197)
  Directional -> Accuracy: 0.5625, MCC: 0.0263, F1: 0.0870

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.63977 | val 0.79401
  Epoch 014 - train 0.62738 | val 1.05934
  Classification -> best τ=0.560 (val F1=0.2162)
  Directional -> Accuracy: 0.5217, MCC: 0.0044, F1: 0.4000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.66149 | val 0.67363
  Epoch 020 - train 0.58711 | val 0.83385
  Classification -> best τ=0.575 (val F1=0.3075)
  Directional -> Accuracy: 0.5918, MCC: 0.1804, F1: 0.2308

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.66224 | val 1.15039
  Epoch 011 - train 0.64905 | val 1.27520
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5088, MCC: 0.0000, F1: 0.6744

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.60789 | val 1.70844
  Epoch 011 - train 0.57697 | val 1.63084
  Classification -> best τ=0.260 (val F1=0.1878)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.6230

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.69896 | val 0.64342
  Epoch 015 - train 0.59998 | val 0.84179
  Classification -> best τ=0.295 (val F1=0.3859)
  Directional -> Accuracy: 0.5667, MCC: 0.1361, F1: 0.5185

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.64624 | val 1.32272
  Epoch 011 - train 0.67480 | val 1.16321
  Classification -> best τ=0.630 (val F1=0.0921)
  Directional -> Accuracy: 0.5490, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.67112 | val 0.83833
  Epoch 011 - train 0.61222 | val 0.92551
  Classification -> best τ=0.415 (val F1=0.1741)
  Directional -> Accuracy: 0.5507, MCC: 0.0867, F1: 0.6990

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.68177 | val 1.01712
  Epoch 012 - train 0.64242 | val 0.97410
  Classification -> best τ=0.585 (val F1=0.1342)
  Directional -> Accuracy: 0.3793, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.66110 | val 1.04437
  Epoch 011 - train 0.64155 | val 1.14437
  Classification -> best τ=0.340 (val F1=0.2171)
  Directional -> Accuracy: 0.4933, MCC: 0.0849, F1: 0.4242

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.62669 | val 0.68151
  Epoch 015 - train 0.59011 | val 0.77894
  Classification -> best τ=0.585 (val F1=0.2641)
  Directional -> Accuracy: 0.4688, MCC: 0.0966, F1: 0.2273

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.64270 | val 1.17309
  Epoch 011 - train 0.56043 | val 1.40272
  Classification -> best τ=0.445 (val F1=0.3460)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.65254 | val 0.95792
  Epoch 013 - train 0.58279 | val 1.43163
  Classification -> best τ=0.430 (val F1=0.3458)
  Directional -> Accuracy: 0.4043, MCC: 0.1162, F1: 0.0667

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.67587 | val 0.77695
  Epoch 011 - train 0.65937 | val 0.76033
  Classification -> best τ=0.445 (val F1=0.2952)
  Directional -> Accuracy: 0.5077, MCC: 0.0000, F1: 0.6735

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.65459 | val 0.71303
  Epoch 020 - train 0.65213 | val 0.66209
  Epoch 021 - train 0.62554 | val 0.63791
  Classification -> best τ=0.390 (val F1=0.4704)
  Directional -> Accuracy: 0.5789, MCC: 0.1009, F1: 0.7143

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.66479 | val 0.82332
  Epoch 018 - train 0.58485 | val 1.22783
  Classification -> best τ=0.530 (val F1=0.1415)
  Directional -> Accuracy: 0.4923, MCC: -0.0764, F1: 0.1538

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.61383 | val 0.70925
  Epoch 013 - train 0.58202 | val 0.85288
  Classification -> best τ=0.305 (val F1=0.4688)
  Directional -> Accuracy: 0.5818, MCC: 0.1449, F1: 0.6462

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.62812 | val 1.68764
  Epoch 011 - train 0.63070 | val 1.82142
  Classification -> best τ=0.575 (val F1=0.1890)
  Directional -> Accuracy: 0.5778, MCC: 0.0000, F1: 0.0000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.68597 | val 0.87765
  Epoch 011 - train 0.62719 | val 0.87279
  Classification -> best τ=0.465 (val F1=0.1514)
  Directional -> Accuracy: 0.5952, MCC: 0.1578, F1: 0.6667

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.64074 | val 1.11478
  Epoch 011 - train 0.62798 | val 1.21876
  Classification -> best τ=0.490 (val F1=0.2976)
  Directional -> Accuracy: 0.4464, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.60734 | val 1.12567
  Epoch 013 - train 0.65878 | val 1.15629
  Classification -> best τ=0.535 (val F1=0.3518)
  Directional -> Accuracy: 0.5000, MCC: -0.1340, F1: 0.6552

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.69497 | val 0.68184
  Epoch 019 - train 0.60426 | val 1.41165
  Classification -> best τ=0.445 (val F1=0.4146)
  Directional -> Accuracy: 0.5238, MCC: 0.0413, F1: 0.4737

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.64019 | val 1.07515
  Epoch 011 - train 0.70666 | val 1.09446
  Classification -> best τ=0.425 (val F1=0.0769)
  Directional -> Accuracy: 0.5476, MCC: 0.0391, F1: 0.6780

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.65636 | val 0.82515
  Epoch 011 - train 0.60998 | val 0.79724
  Classification -> best τ=0.445 (val F1=0.3850)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.60897 | val 0.86172
  Epoch 013 - train 0.61608 | val 0.96259
  Classification -> best τ=0.420 (val F1=0.2524)
  Directional -> Accuracy: 0.4444, MCC: 0.0000, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.59798 | val 1.44661
  Epoch 011 - train 0.57887 | val 1.56786
  Classification -> best τ=0.545 (val F1=0.1027)
  Directional -> Accuracy: 0.4651, MCC: -0.0783, F1: 0.3784

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.66804 | val 0.93559
  Epoch 011 - train 0.62815 | val 1.08995
  Classification -> best τ=0.320 (val F1=0.3342)
  Directional -> Accuracy: 0.6515, MCC: 0.2777, F1: 0.7089

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.55653 | val 1.42620
  Epoch 011 - train 0.62126 | val 1.98882
  Classification -> best τ=0.465 (val F1=0.0495)
  Directional -> Accuracy: 0.5238, MCC: 0.0413, F1: 0.5652

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.60443 | val 1.38689
  Epoch 011 - train 0.57137 | val 1.56351
  Classification -> best τ=0.565 (val F1=0.2850)
  Directional -> Accuracy: 0.6071, MCC: 0.2204, F1: 0.3889

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.69302 | val 1.50392
  Epoch 013 - train 0.57709 | val 1.27704
  Classification -> best τ=0.260 (val F1=0.1195)
  Directional -> Accuracy: 0.6087, MCC: 0.0000, F1: 0.7568

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.64093 | val 0.74357
  Epoch 015 - train 0.67636 | val 1.10378
  Classification -> best τ=0.780 (val F1=0.4710)
  Directional -> Accuracy: 0.3958, MCC: -0.0195, F1: 0.4912

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.57753 | val 1.13473
  Epoch 011 - train 0.62003 | val 1.17738
  Classification -> best τ=0.355 (val F1=0.2485)
  Directional -> Accuracy: 0.4865, MCC: -0.0347, F1: 0.4062

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.68692 | val 0.69895
  Epoch 020 - train 0.64048 | val 0.74445
  Epoch 023 - train 0.61249 | val 0.69896
  Classification -> best τ=0.530 (val F1=0.3776)
  Directional -> Accuracy: 0.4889, MCC: -0.0134, F1: 0.3429

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.56524 | val 1.16645
  Epoch 011 - train 0.60993 | val 1.19551
  Classification -> best τ=0.515 (val F1=0.4277)
  Directional -> Accuracy: 0.5714, MCC: 0.1132, F1: 0.6400

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.66262 | val 0.80852
  Epoch 016 - train 0.59676 | val 1.07931
  Classification -> best τ=0.675 (val F1=0.4371)
  Directional -> Accuracy: 0.5417, MCC: 0.1309, F1: 0.5217

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.68223 | val 0.82897
  Epoch 012 - train 0.62238 | val 0.87733
  Classification -> best τ=0.745 (val F1=0.2036)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.61997 | val 2.19512
  Epoch 011 - train 0.50414 | val 2.47521
  Classification -> best τ=0.680 (val F1=0.3233)
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.6506

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.66735 | val 0.82486
  Epoch 011 - train 0.68253 | val 0.78607
  Classification -> best τ=0.470 (val F1=0.1801)
  Directional -> Accuracy: 0.6038, MCC: 0.2109, F1: 0.6557

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.60530 | val 4.07434
  Epoch 011 - train 0.61295 | val 4.18135
  Classification -> best τ=0.770 (val F1=0.1210)
  Directional -> Accuracy: 0.4727, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.65605 | val 0.65891

[I 2026-02-22 12:08:22,855] Trial 163 finished with value: 0.26712570777622274 and parameters: {'feature_set': 'sector', 'model_type': 'BiGRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.8, 'batch_size': 16, 'learning_rate': 0.003279326228423952, 'weight_decay': 1.1666914962528463e-05, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 1.1031767579858065, 'early_stopping_min_delta': 0.00034816270270194167}. Best is trial 159 with value: 0.297766251520741.

  Epoch 017 - train 0.63603 | val 0.73247
  Classification -> best τ=0.335 (val F1=0.3178)
  Directional -> Accuracy: 0.5167, MCC: 0.0746, F1: 0.6329

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.26712570777622274
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.54711 | val 1.35697
  Epoch 011 - train 0.48692 | val 1.71734
  Classification -> best τ=0.465 (val F1=0.2364)
  Directional -> Accuracy: 0.5000, MCC: 0.0569, F1: 0.5778

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.43727 | val 0.93161
  Epoch 011 - train 0.36560 | val 0.94579
  Classification -> best τ=0.715 (val F1=0.0492)
  Directional -> Accuracy: 0.6000, MCC: 0.1924, F1: 0.6400

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.51624 | val 2.24468
  Epoch 011 - train 0.41177 | val 2.26518
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5217, MCC: 0.0000, F1: 0.6857

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.64377 | val 1.05396
  Epoch 012 - train 0.51052 | val 1.09638
  Classification -> best τ=0.430 (val F1=0.2042)
  Directional -> Accuracy: 0.5270, MCC: 0.0457, F1: 0.5679

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.48412 | val 0.81172
  Epoch 013 - train 0.31302 | val 1.20210
  Classification -> best τ=0.655 (val F1=0.4556)
  Directional -> Accuracy: 0.6000, MCC: 0.2425, F1: 0.5000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.53074 | val 0.84129
  Epoch 015 - train 0.29177 | val 1.79788
  Classification -> best τ=0.610 (val F1=0.3624)
  Directional -> Accuracy: 0.5217, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.65074 | val 1.71519
  Epoch 012 - train 0.48244 | val 2.33421
  Classification -> best τ=0.540 (val F1=0.2140)
  Directional -> Accuracy: 0.5588, MCC: 0.1671, F1: 0.5588

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.42092 | val 0.57332
  Epoch 016 - train 0.27951 | val 1.89131
  Classification -> best τ=0.330 (val F1=0.3059)
  Directional -> Accuracy: 0.5238, MCC: 0.0413, F1: 0.4737

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.49480 | val 2.48163
  Epoch 011 - train 0.43943 | val 3.00386
  Classification -> best τ=0.455 (val F1=0.2497)
  Directional -> Accuracy: 0.4375, MCC: 0.0000, F1: 0.6087

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.62070 | val 0.73016
  Epoch 012 - train 0.38701 | val 0.80808
  Classification -> best τ=0.510 (val F1=0.1668)
  Directional -> Accuracy: 0.4928, MCC: 0.0209, F1: 0.5070

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.55063 | val 0.97484
  Epoch 011 - train 0.47952 | val 0.82819
  Classification -> best τ=0.580 (val F1=0.2672)
  Directional -> Accuracy: 0.5918, MCC: 0.1913, F1: 0.5833

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.61443 | val 1.06100
  Epoch 012 - train 0.48150 | val 1.31092
  Classification -> best τ=0.400 (val F1=0.2391)
  Directional -> Accuracy: 0.5789, MCC: 0.1731, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.44711 | val 1.29719
  Epoch 011 - train 0.42881 | val 1.27990
  Classification -> best τ=0.330 (val F1=0.0096)
  Directional -> Accuracy: 0.4762, MCC: -0.0389, F1: 0.4762

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.60165 | val 0.86079
  Epoch 013 - train 0.44024 | val 1.06440
  Classification -> best τ=0.375 (val F1=0.3833)
  Directional -> Accuracy: 0.5333, MCC: 0.0754, F1: 0.3913

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.57150 | val 2.02937
  Epoch 012 - train 0.41884 | val 1.00202
  Classification -> best τ=0.600 (val F1=0.2571)
  Directional -> Accuracy: 0.5490, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.55285 | val 1.76753
  Epoch 011 - train 0.50456 | val 1.63614
  Classification -> best τ=0.445 (val F1=0.2345)
  Directional -> Accuracy: 0.3768, MCC: -0.2424, F1: 0.3768

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.51507 | val 1.90084
  Epoch 013 - train 0.45760 | val 2.41998
  Classification -> best τ=0.530 (val F1=0.3060)
  Directional -> Accuracy: 0.3793, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.47192 | val 1.80683
  Epoch 011 - train 0.42566 | val 2.09290
  Classification -> best τ=0.300 (val F1=0.2004)
  Directional -> Accuracy: 0.5200, MCC: 0.1455, F1: 0.4545

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.59363 | val 0.90173
  Epoch 012 - train 0.43217 | val 0.99389
  Classification -> best τ=0.255 (val F1=0.3140)
  Directional -> Accuracy: 0.5312, MCC: 0.0294, F1: 0.6053

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.51466 | val 1.40349
  Epoch 011 - train 0.39837 | val 1.47623
  Classification -> best τ=0.375 (val F1=0.2312)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.46093 | val 2.01909
  Epoch 011 - train 0.42602 | val 2.35062
  Classification -> best τ=0.510 (val F1=0.2779)
  Directional -> Accuracy: 0.4468, MCC: 0.0220, F1: 0.3500

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.53122 | val 1.68463
  Epoch 011 - train 0.45429 | val 1.85313
  Classification -> best τ=0.575 (val F1=0.1521)
  Directional -> Accuracy: 0.5077, MCC: 0.0699, F1: 0.1111

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.56128 | val 1.12952
  Epoch 011 - train 0.49658 | val 1.22810
  Classification -> best τ=0.535 (val F1=0.3727)
  Directional -> Accuracy: 0.5789, MCC: 0.1706, F1: 0.5862

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.54759 | val 1.35349
  Epoch 011 - train 0.47843 | val 1.07494
  Classification -> best τ=0.455 (val F1=0.1079)
  Directional -> Accuracy: 0.5077, MCC: 0.0049, F1: 0.4286

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.50603 | val 0.98531
  Epoch 011 - train 0.47030 | val 0.98827
  Classification -> best τ=0.485 (val F1=0.6005)
  Directional -> Accuracy: 0.5818, MCC: 0.1660, F1: 0.5965

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.50329 | val 3.45147
  Epoch 011 - train 0.48070 | val 3.80519
  Classification -> best τ=0.605 (val F1=0.0447)
  Directional -> Accuracy: 0.4444, MCC: -0.2103, F1: 0.1935

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.46957 | val 1.09748
  Epoch 011 - train 0.44729 | val 1.02425
  Classification -> best τ=0.500 (val F1=0.2582)
  Directional -> Accuracy: 0.5238, MCC: -0.1936, F1: 0.6875

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.52081 | val 2.08261
  Epoch 011 - train 0.43614 | val 1.64439
  Classification -> best τ=0.470 (val F1=0.4296)
  Directional -> Accuracy: 0.4643, MCC: 0.1211, F1: 0.0625

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.52921 | val 0.77317
  Epoch 015 - train 0.28041 | val 1.09321
  Classification -> best τ=0.590 (val F1=0.4063)
  Directional -> Accuracy: 0.5500, MCC: 0.1111, F1: 0.5500

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.50440 | val 1.35477
  Epoch 014 - train 0.48362 | val 1.37155
  Classification -> best τ=0.400 (val F1=0.3689)
  Directional -> Accuracy: 0.4762, MCC: -0.0337, F1: 0.5417

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.75466 | val 1.38822
  Epoch 012 - train 0.43118 | val 1.63787
  Classification -> best τ=0.410 (val F1=0.2357)
  Directional -> Accuracy: 0.5714, MCC: 0.1194, F1: 0.7097

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.45607 | val 1.18813
  Epoch 012 - train 0.36812 | val 1.51947
  Classification -> best τ=0.385 (val F1=0.2837)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.53832 | val 1.32174
  Epoch 012 - train 0.40151 | val 1.65302
  Classification -> best τ=0.250 (val F1=0.2978)
  Directional -> Accuracy: 0.5556, MCC: 0.0000, F1: 0.7143

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.47616 | val 2.31798
  Epoch 011 - train 0.41200 | val 2.05053
  Classification -> best τ=0.585 (val F1=0.2603)
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.60511 | val 1.10368
  Epoch 011 - train 0.51667 | val 1.49945
  Classification -> best τ=0.300 (val F1=0.2518)
  Directional -> Accuracy: 0.4848, MCC: 0.0438, F1: 0.3929

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.33584 | val 3.30960
  Epoch 011 - train 0.27782 | val 3.77751
  Classification -> best τ=0.440 (val F1=0.1822)
  Directional -> Accuracy: 0.6429, MCC: 0.3290, F1: 0.5714

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.47236 | val 1.83312
  Epoch 011 - train 0.43477 | val 1.80657
  Classification -> best τ=0.520 (val F1=0.2755)
  Directional -> Accuracy: 0.5893, MCC: 0.2134, F1: 0.6349

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.44248 | val 1.55836
  Epoch 011 - train 0.38885 | val 1.72723
  Classification -> best τ=0.735 (val F1=0.2659)
  Directional -> Accuracy: 0.3913, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.52720 | val 1.31165
  Epoch 015 - train 0.38349 | val 0.82956
  Classification -> best τ=0.475 (val F1=0.4011)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.52033 | val 1.54073
  Epoch 011 - train 0.42417 | val 1.94691
  Classification -> best τ=0.130 (val F1=0.2397)
  Directional -> Accuracy: 0.4865, MCC: 0.0000, F1: 0.6545

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.45104 | val 1.41545
  Epoch 012 - train 0.39190 | val 0.91545
  Classification -> best τ=0.315 (val F1=0.2375)
  Directional -> Accuracy: 0.5111, MCC: 0.0000, F1: 0.6765

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.37586 | val 2.76891
  Epoch 011 - train 0.37616 | val 3.23299
  Classification -> best τ=0.570 (val F1=0.3015)
  Directional -> Accuracy: 0.6905, MCC: 0.3873, F1: 0.7797

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.55185 | val 0.65066
  Epoch 020 - train 0.27413 | val 0.60355
  Epoch 028 - train 0.05094 | val 0.92850
  Classification -> best τ=0.785 (val F1=0.6110)
  Directional -> Accuracy: 0.4583, MCC: 0.1627, F1: 0.5667

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.59826 | val 1.29304
  Epoch 013 - train 0.52513 | val 3.30281
  Classification -> best τ=0.625 (val F1=0.1647)
  Directional -> Accuracy: 0.5091, MCC: 0.2193, F1: 0.1818

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.39486 | val 2.76310
  Epoch 011 - train 0.31761 | val 3.01252
  Classification -> best τ=0.605 (val F1=0.2143)
  Directional -> Accuracy: 0.4821, MCC: -0.0565, F1: 0.3256

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.54451 | val 2.00023
  Epoch 012 - train 0.49441 | val 1.58015
  Classification -> best τ=0.455 (val F1=0.1824)
  Directional -> Accuracy: 0.5094, MCC: 0.0000, F1: 0.6750

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.46265 | val 5.53284
  Epoch 011 - train 0.39901 | val 5.92715
  Classification -> best τ=0.860 (val F1=0.0924)
  Directional -> Accuracy: 0.5455, MCC: 0.0832, F1: 0.5902

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.62988 | val 1.12184

[I 2026-02-22 12:10:44,403] Trial 164 finished with value: 0.26030407987541215 and parameters: {'feature_set': 'sector', 'model_type': 'BiGRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.0, 'dropout': 0.7000000000000001, 'batch_size': 16, 'learning_rate': 0.00558174588898177, 'weight_decay': 3.206217932335246e-05, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 1.2056846270331094, 'early_stopping_min_delta': 7.469310371925946e-05}. Best is trial 159 with value: 0.297766251520741.

  Epoch 013 - train 0.48009 | val 0.83924
  Classification -> best τ=0.355 (val F1=0.2915)
  Directional -> Accuracy: 0.5667, MCC: 0.2916, F1: 0.6905

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.26030407987541215
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.62525 | val 1.00778
  Epoch 013 - train 0.56134 | val 1.04735
  Classification -> best τ=0.455 (val F1=0.2919)
  Directional -> Accuracy: 0.5526, MCC: 0.0633, F1: 0.3704

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.53520 | val 1.09194
  Epoch 012 - train 0.52421 | val 1.29609
  Classification -> best τ=0.535 (val F1=0.1323)
  Directional -> Accuracy: 0.6222, MCC: 0.1909, F1: 0.7302

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.54422 | val 1.39635
  Epoch 011 - train 0.58049 | val 1.45790
  Classification -> best τ=0.350 (val F1=0.4104)
  Directional -> Accuracy: 0.5217, MCC: 0.0134, F1: 0.6667

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.59467 | val 0.98310
  Epoch 011 - train 0.58108 | val 0.85391
  Classification -> best τ=0.265 (val F1=0.2771)
  Directional -> Accuracy: 0.5405, MCC: 0.0000, F1: 0.7018

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.57222 | val 1.34081
  Epoch 017 - train 0.39559 | val 2.79958
  Classification -> best τ=0.510 (val F1=0.5217)
  Directional -> Accuracy: 0.6400, MCC: 0.2821, F1: 0.6400

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.54193 | val 0.91810
  Epoch 016 - train 0.43277 | val 0.75400
  Classification -> best τ=0.625 (val F1=0.3194)
  Directional -> Accuracy: 0.5217, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.60237 | val 1.37841
  Epoch 011 - train 0.60256 | val 1.21882
  Classification -> best τ=0.555 (val F1=0.2827)
  Directional -> Accuracy: 0.4853, MCC: -0.0053, F1: 0.4615

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.53201 | val 0.55058
  Epoch 020 - train 0.36282 | val 3.44590
  Epoch 021 - train 0.28164 | val 2.62301
  Classification -> best τ=0.585 (val F1=0.3689)
  Directional -> Accuracy: 0.5000, MCC: 0.0280, F1: 0.5116

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.58265 | val 1.92191
  Epoch 011 - train 0.58034 | val 1.92749
  Classification -> best τ=0.585 (val F1=0.2443)
  Directional -> Accuracy: 0.6042, MCC: 0.1782, F1: 0.4865

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.59188 | val 0.75802
  Epoch 012 - train 0.53442 | val 0.91424
  Classification -> best τ=0.440 (val F1=0.2117)
  Directional -> Accuracy: 0.4928, MCC: 0.0209, F1: 0.5070

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.57385 | val 0.72820
  Epoch 012 - train 0.57873 | val 0.70103
  Classification -> best τ=0.510 (val F1=0.2765)
  Directional -> Accuracy: 0.5102, MCC: 0.0268, F1: 0.5000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.58826 | val 1.27846
  Epoch 011 - train 0.54276 | val 1.32627
  Classification -> best τ=0.380 (val F1=0.1512)
  Directional -> Accuracy: 0.5088, MCC: 0.0000, F1: 0.6744

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.50525 | val 2.16231
  Epoch 011 - train 0.49190 | val 2.31100
  Classification -> best τ=0.460 (val F1=0.1387)
  Directional -> Accuracy: 0.4524, MCC: -0.0751, F1: 0.4889

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.59550 | val 0.75732
  Epoch 011 - train 0.57344 | val 0.70620
  Classification -> best τ=0.435 (val F1=0.3320)
  Directional -> Accuracy: 0.5333, MCC: 0.0981, F1: 0.2632

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.60659 | val 0.84508
  Epoch 012 - train 0.55788 | val 0.80590
  Classification -> best τ=0.695 (val F1=0.2078)
  Directional -> Accuracy: 0.5490, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.61728 | val 1.08784
  Epoch 012 - train 0.51578 | val 1.59212
  Classification -> best τ=0.340 (val F1=0.1512)
  Directional -> Accuracy: 0.5507, MCC: 0.0764, F1: 0.6931

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.60580 | val 1.05779
  Epoch 012 - train 0.51148 | val 1.03291
  Classification -> best τ=0.660 (val F1=0.1842)
  Directional -> Accuracy: 0.3793, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.58983 | val 1.05950
  Epoch 011 - train 0.52752 | val 1.04515
  Classification -> best τ=0.320 (val F1=0.2004)
  Directional -> Accuracy: 0.5467, MCC: 0.0233, F1: 0.6458

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.61940 | val 0.78995
  Epoch 011 - train 0.58369 | val 0.69348
  Classification -> best τ=0.480 (val F1=0.2231)
  Directional -> Accuracy: 0.4844, MCC: 0.1315, F1: 0.2667

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.54484 | val 1.22031
  Epoch 011 - train 0.51595 | val 1.21710
  Classification -> best τ=0.600 (val F1=0.3183)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.58904 | val 1.39550
  Epoch 011 - train 0.52256 | val 1.59735
  Classification -> best τ=0.595 (val F1=0.1383)
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.55969 | val 1.24873
  Epoch 011 - train 0.60136 | val 1.27731
  Classification -> best τ=0.440 (val F1=0.2425)
  Directional -> Accuracy: 0.5692, MCC: 0.1742, F1: 0.4167

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.59201 | val 0.74029
  Epoch 016 - train 0.52247 | val 0.95672
  Classification -> best τ=0.660 (val F1=0.5161)
  Directional -> Accuracy: 0.5263, MCC: 0.0887, F1: 0.4906

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.61126 | val 0.70065
  Epoch 011 - train 0.58321 | val 0.74660
  Classification -> best τ=0.380 (val F1=0.1599)
  Directional -> Accuracy: 0.4769, MCC: 0.0000, F1: 0.6458

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.55051 | val 1.24089
  Epoch 014 - train 0.48622 | val 0.98811
  Classification -> best τ=0.640 (val F1=0.5294)
  Directional -> Accuracy: 0.5455, MCC: 0.0864, F1: 0.5763

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.44137 | val 2.08307
  Epoch 011 - train 0.58838 | val 1.97719
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.5938

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.60681 | val 0.80384
  Epoch 015 - train 0.54388 | val 0.87606
  Classification -> best τ=0.575 (val F1=0.1936)
  Directional -> Accuracy: 0.4524, MCC: 0.1353, F1: 0.0800

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.57780 | val 1.21375
  Epoch 011 - train 0.54152 | val 1.09930
  Classification -> best τ=0.335 (val F1=0.2244)
  Directional -> Accuracy: 0.4464, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.52029 | val 0.64745
  Epoch 020 - train 0.32861 | val 0.74145
  Classification -> best τ=0.455 (val F1=0.4966)
  Directional -> Accuracy: 0.5500, MCC: 0.0422, F1: 0.6786

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.58058 | val 1.06293
  Epoch 013 - train 0.50426 | val 1.58567
  Classification -> best τ=0.520 (val F1=0.5731)
  Directional -> Accuracy: 0.4762, MCC: -0.0413, F1: 0.5000

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.56648 | val 1.30070
  Epoch 011 - train 0.56536 | val 1.49111
  Classification -> best τ=0.475 (val F1=0.0155)
  Directional -> Accuracy: 0.6190, MCC: 0.2311, F1: 0.6522

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.55273 | val 0.95804
  Epoch 011 - train 0.51159 | val 1.03922
  Classification -> best τ=0.425 (val F1=0.2599)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.57958 | val 1.36749
  Epoch 014 - train 0.53697 | val 1.09506
  Classification -> best τ=0.715 (val F1=0.2970)
  Directional -> Accuracy: 0.4444, MCC: 0.0000, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.53666 | val 1.04369
  Epoch 011 - train 0.53326 | val 1.08299
  Classification -> best τ=0.545 (val F1=0.2814)
  Directional -> Accuracy: 0.5116, MCC: 0.0197, F1: 0.4615

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.59380 | val 1.05982
  Epoch 014 - train 0.52745 | val 1.66360
  Classification -> best τ=0.400 (val F1=0.3551)
  Directional -> Accuracy: 0.4848, MCC: 0.2180, F1: 0.1905

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.47733 | val 3.51578
  Epoch 011 - train 0.49048 | val 3.57881
  Classification -> best τ=0.405 (val F1=0.2464)
  Directional -> Accuracy: 0.6429, MCC: 0.2897, F1: 0.7059

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.51280 | val 1.41023
  Epoch 011 - train 0.51247 | val 1.12332
  Classification -> best τ=0.505 (val F1=0.2327)
  Directional -> Accuracy: 0.6250, MCC: 0.2774, F1: 0.6557

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.53499 | val 1.06337
  Epoch 012 - train 0.41974 | val 1.02199
  Classification -> best τ=0.480 (val F1=0.3352)
  Directional -> Accuracy: 0.5870, MCC: -0.1195, F1: 0.7397

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.60588 | val 0.95090
  Epoch 013 - train 0.56499 | val 0.93652
  Classification -> best τ=0.435 (val F1=0.4011)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.54248 | val 1.52428
  Epoch 011 - train 0.48836 | val 1.85144
  Classification -> best τ=0.235 (val F1=0.3163)
  Directional -> Accuracy: 0.4865, MCC: 0.0000, F1: 0.6545

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.61885 | val 0.74266
  Epoch 019 - train 0.43456 | val 1.10309
  Classification -> best τ=0.710 (val F1=0.4490)
  Directional -> Accuracy: 0.5333, MCC: 0.1541, F1: 0.6866

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.45733 | val 1.98517
  Epoch 011 - train 0.47617 | val 2.15498
  Classification -> best τ=0.580 (val F1=0.3612)
  Directional -> Accuracy: 0.4048, MCC: -0.1803, F1: 0.0000

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.51492 | val 0.72249
  Epoch 020 - train 0.38644 | val 0.82549
  Epoch 022 - train 0.37589 | val 1.14852
  Classification -> best τ=0.600 (val F1=0.5557)
  Directional -> Accuracy: 0.6042, MCC: 0.1462, F1: 0.4571

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.65582 | val 1.52833
  Epoch 011 - train 0.62679 | val 1.61762
  Classification -> best τ=0.530 (val F1=0.2036)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.53534 | val 2.25666
  Epoch 011 - train 0.45525 | val 1.97238
  Classification -> best τ=0.620 (val F1=0.3432)
  Directional -> Accuracy: 0.5536, MCC: 0.1135, F1: 0.5763

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.64317 | val 0.79480
  Epoch 013 - train 0.62127 | val 1.25082
  Classification -> best τ=0.810 (val F1=0.2064)
  Directional -> Accuracy: 0.6226, MCC: 0.2468, F1: 0.6154

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.62099 | val 1.59186
  Epoch 012 - train 0.54277 | val 1.75654
  Classification -> best τ=0.785 (val F1=0.2292)
  Directional -> Accuracy: 0.4909, MCC: 0.0074, F1: 0.3636

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.58100 | val 0.94805

[I 2026-02-22 12:13:16,835] Trial 165 finished with value: 0.2847675162419489 and parameters: {'feature_set': 'sector', 'model_type': 'BiGRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.5, 'batch_size': 16, 'learning_rate': 0.004194626967997112, 'weight_decay': 1.4570129978982328e-05, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 1.0507701857658958, 'early_stopping_min_delta': 0.0002091854214893296}. Best is trial 159 with value: 0.297766251520741.

  Epoch 015 - train 0.54168 | val 0.79067
  Classification -> best τ=0.655 (val F1=0.2623)
  Directional -> Accuracy: 0.5167, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2847675162419489
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.60678 | val 1.01546
  Epoch 011 - train 0.59550 | val 0.96036
  Classification -> best τ=0.440 (val F1=0.2034)
  Directional -> Accuracy: 0.5658, MCC: 0.1351, F1: 0.5479

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.50849 | val 1.34058
  Epoch 011 - train 0.50674 | val 1.47800
  Classification -> best τ=0.665 (val F1=0.1273)
  Directional -> Accuracy: 0.6000, MCC: 0.1691, F1: 0.6667

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.59079 | val 1.98622
  Epoch 011 - train 0.59247 | val 1.94506
  Classification -> best τ=0.670 (val F1=0.2727)
  Directional -> Accuracy: 0.4565, MCC: -0.0996, F1: 0.0741

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.58741 | val 0.77278
  Epoch 016 - train 0.56088 | val 1.26176
  Classification -> best τ=0.310 (val F1=0.2920)
  Directional -> Accuracy: 0.5405, MCC: 0.0000, F1: 0.7018

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.54812 | val 1.71495
  Epoch 012 - train 0.46930 | val 1.30383
  Classification -> best τ=0.590 (val F1=0.4602)
  Directional -> Accuracy: 0.6200, MCC: 0.2670, F1: 0.5581

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.63461 | val 1.71789
  Epoch 012 - train 0.51238 | val 1.26430
  Classification -> best τ=0.580 (val F1=0.2585)
  Directional -> Accuracy: 0.5217, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.60007 | val 1.25670
  Epoch 011 - train 0.62211 | val 1.37902
  Classification -> best τ=0.405 (val F1=0.3331)
  Directional -> Accuracy: 0.5441, MCC: 0.1591, F1: 0.5634

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.67387 | val 3.49340
  Epoch 013 - train 0.52714 | val 1.92941
  Classification -> best τ=0.485 (val F1=0.2810)
  Directional -> Accuracy: 0.4762, MCC: -0.0550, F1: 0.4211

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.56768 | val 3.12293
  Epoch 011 - train 0.55682 | val 3.31712
  Classification -> best τ=0.515 (val F1=0.3441)
  Directional -> Accuracy: 0.6250, MCC: 0.2250, F1: 0.5263

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.59416 | val 0.75935
  Epoch 019 - train 0.44886 | val 0.99032
  Classification -> best τ=0.565 (val F1=0.2294)
  Directional -> Accuracy: 0.4638, MCC: -0.0758, F1: 0.4127

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.63041 | val 0.93781
  Epoch 013 - train 0.54164 | val 1.15590
  Classification -> best τ=0.610 (val F1=0.3075)
  Directional -> Accuracy: 0.6122, MCC: 0.2379, F1: 0.2963

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.60163 | val 1.16789
  Epoch 011 - train 0.60316 | val 1.25060
  Classification -> best τ=0.525 (val F1=0.2162)
  Directional -> Accuracy: 0.5965, MCC: 0.2309, F1: 0.6933

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.47417 | val 2.33659
  Epoch 011 - train 0.47428 | val 2.99916
  Classification -> best τ=0.345 (val F1=0.2636)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.6230

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.62155 | val 0.67104
  Epoch 020 - train 0.55518 | val 0.67043
  Epoch 025 - train 0.46161 | val 0.79670
  Classification -> best τ=0.125 (val F1=0.3282)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.5312

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.63122 | val 0.75277
  Epoch 019 - train 0.47365 | val 0.86454
  Classification -> best τ=0.585 (val F1=0.2078)
  Directional -> Accuracy: 0.5490, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.57767 | val 1.16183
  Epoch 011 - train 0.56053 | val 1.13187
  Classification -> best τ=0.425 (val F1=0.2341)
  Directional -> Accuracy: 0.5362, MCC: 0.0600, F1: 0.5897

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.59046 | val 1.01629
  Epoch 011 - train 0.60369 | val 1.17139
  Classification -> best τ=0.435 (val F1=0.1336)
  Directional -> Accuracy: 0.6207, MCC: 0.0000, F1: 0.7660

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.58958 | val 0.94388
  Epoch 011 - train 0.55332 | val 0.98878
  Classification -> best τ=0.640 (val F1=0.1909)
  Directional -> Accuracy: 0.4000, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.60990 | val 1.02547
  Epoch 017 - train 0.44714 | val 1.59629
  Classification -> best τ=0.540 (val F1=0.2641)
  Directional -> Accuracy: 0.5156, MCC: 0.1672, F1: 0.3673

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.55823 | val 1.49277
  Epoch 012 - train 0.51597 | val 1.37973
  Classification -> best τ=0.215 (val F1=0.2572)
  Directional -> Accuracy: 0.4459, MCC: -0.1317, F1: 0.5176

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.51721 | val 1.11460
  Epoch 011 - train 0.55069 | val 1.46681
  Classification -> best τ=0.435 (val F1=0.1572)
  Directional -> Accuracy: 0.6596, MCC: 0.2676, F1: 0.7838

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.57786 | val 0.75790
  Epoch 011 - train 0.57236 | val 0.83433
  Classification -> best τ=0.550 (val F1=0.2543)
  Directional -> Accuracy: 0.4923, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.64694 | val 0.70031
  Epoch 017 - train 0.58711 | val 0.66247
  Classification -> best τ=0.550 (val F1=0.6141)
  Directional -> Accuracy: 0.5789, MCC: 0.1528, F1: 0.6129

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.60897 | val 0.80903
  Epoch 014 - train 0.58602 | val 1.52313
  Classification -> best τ=0.570 (val F1=0.1778)
  Directional -> Accuracy: 0.4769, MCC: -0.0924, F1: 0.2273

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.60145 | val 0.76771
  Epoch 013 - train 0.55322 | val 0.96472
  Classification -> best τ=0.395 (val F1=0.5472)
  Directional -> Accuracy: 0.5273, MCC: 0.0745, F1: 0.5000

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.46271 | val 4.18571
  Epoch 011 - train 0.47981 | val 4.90135
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.5938

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.61162 | val 0.86134
  Epoch 011 - train 0.55266 | val 0.92648
  Classification -> best τ=0.370 (val F1=0.2582)
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.7273

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.65499 | val 0.95116
  Epoch 011 - train 0.52596 | val 0.96209
  Classification -> best τ=0.320 (val F1=0.2386)
  Directional -> Accuracy: 0.4464, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.54734 | val 0.79059
  Epoch 011 - train 0.56549 | val 0.74368
  Classification -> best τ=0.565 (val F1=0.1457)
  Directional -> Accuracy: 0.6250, MCC: 0.2335, F1: 0.6809

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.55999 | val 0.65534
  Epoch 020 - train 0.47349 | val 0.89518
  Epoch 022 - train 0.45221 | val 0.77252
  Classification -> best τ=0.285 (val F1=0.4113)
  Directional -> Accuracy: 0.4524, MCC: -0.0912, F1: 0.4651

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.64527 | val 1.46020
  Epoch 011 - train 0.65305 | val 1.82534
  Classification -> best τ=0.485 (val F1=0.0190)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.56483 | val 0.89229
  Epoch 012 - train 0.53407 | val 1.02375
  Classification -> best τ=0.415 (val F1=0.3242)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.58993 | val 1.05583
  Epoch 012 - train 0.56733 | val 1.16104
  Classification -> best τ=0.250 (val F1=0.3593)
  Directional -> Accuracy: 0.5556, MCC: 0.0000, F1: 0.7143

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.56645 | val 1.17595
  Epoch 011 - train 0.54562 | val 1.18335
  Classification -> best τ=0.480 (val F1=0.1095)
  Directional -> Accuracy: 0.4651, MCC: -0.0660, F1: 0.5490

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.60447 | val 1.06898
  Epoch 011 - train 0.60002 | val 1.14922
  Classification -> best τ=0.205 (val F1=0.2778)
  Directional -> Accuracy: 0.5758, MCC: 0.0000, F1: 0.7308

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.61743 | val 2.47179
  Epoch 011 - train 0.55267 | val 2.06280
  Classification -> best τ=0.405 (val F1=0.2439)
  Directional -> Accuracy: 0.5238, MCC: 0.0107, F1: 0.6774

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.58831 | val 1.01597
  Epoch 011 - train 0.49708 | val 1.01237
  Classification -> best τ=0.460 (val F1=0.2530)
  Directional -> Accuracy: 0.5536, MCC: 0.1222, F1: 0.5763

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.52549 | val 1.10282
  Epoch 012 - train 0.44082 | val 1.00168
  Classification -> best τ=0.485 (val F1=0.3146)
  Directional -> Accuracy: 0.5870, MCC: 0.0062, F1: 0.7246

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.66444 | val 0.67034
  Epoch 020 - train 0.48952 | val 0.84360
  Epoch 028 - train 0.39084 | val 1.18583
  Classification -> best τ=0.170 (val F1=0.4201)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.55329 | val 1.69415
  Epoch 011 - train 0.50682 | val 2.04206
  Classification -> best τ=0.335 (val F1=0.2766)
  Directional -> Accuracy: 0.4865, MCC: 0.0000, F1: 0.6545

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.64218 | val 0.69698
  Epoch 014 - train 0.55055 | val 0.68617
  Classification -> best τ=0.455 (val F1=0.4490)
  Directional -> Accuracy: 0.6222, MCC: 0.2882, F1: 0.5143

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.50423 | val 1.80602
  Epoch 012 - train 0.39537 | val 2.21347
  Classification -> best τ=0.585 (val F1=0.5000)
  Directional -> Accuracy: 0.6429, MCC: 0.2501, F1: 0.7273

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.58662 | val 0.71436
  Epoch 020 - train 0.40038 | val 1.51893
  Epoch 023 - train 0.33197 | val 1.76056
  Classification -> best τ=0.555 (val F1=0.3410)
  Directional -> Accuracy: 0.3958, MCC: 0.1130, F1: 0.5538

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.62854 | val 1.45245
  Epoch 011 - train 0.61293 | val 1.51530
  Classification -> best τ=0.465 (val F1=0.2036)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.54410 | val 2.50794
  Epoch 011 - train 0.50422 | val 2.77640
  Classification -> best τ=0.735 (val F1=0.3111)
  Directional -> Accuracy: 0.5000, MCC: 0.0013, F1: 0.5000

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.64542 | val 0.69335
  Epoch 013 - train 0.60909 | val 0.71774
  Classification -> best τ=0.635 (val F1=0.2064)
  Directional -> Accuracy: 0.6038, MCC: 0.2069, F1: 0.6316

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.51928 | val 2.79720
  Epoch 011 - train 0.53764 | val 2.94417
  Classification -> best τ=0.650 (val F1=0.1372)
  Directional -> Accuracy: 0.5455, MCC: 0.0733, F1: 0.6479

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.59024 | val 0.82925

[I 2026-02-22 12:15:57,416] Trial 166 finished with value: 0.271584874957766 and parameters: {'feature_set': 'sector', 'model_type': 'BiGRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.6000000000000001, 'batch_size': 16, 'learning_rate': 0.00395821671943675, 'weight_decay': 1.4446228222785048e-05, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 1.1168043589924204, 'early_stopping_min_delta': 0.0002977604823064495}. Best is trial 159 with value: 0.297766251520741.

  Epoch 017 - train 0.50402 | val 0.78700
  Classification -> best τ=0.515 (val F1=0.2810)
  Directional -> Accuracy: 0.5500, MCC: 0.1112, F1: 0.2703

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.271584874957766
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.63000 | val 0.88416
  Epoch 015 - train 0.64839 | val 1.07903
  Classification -> best τ=0.845 (val F1=0.2919)
  Directional -> Accuracy: 0.5263, MCC: -0.1479, F1: 0.0000

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.56634 | val 0.98713
  Epoch 012 - train 0.54922 | val 0.98018
  Classification -> best τ=0.400 (val F1=0.1844)
  Directional -> Accuracy: 0.6222, MCC: 0.2523, F1: 0.7536

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.59330 | val 1.32447
  Epoch 011 - train 0.60316 | val 1.41985
  Classification -> best τ=0.595 (val F1=0.2727)
  Directional -> Accuracy: 0.4565, MCC: -0.0996, F1: 0.0741

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.64618 | val 1.52246
  Epoch 014 - train 0.56015 | val 1.73765
  Classification -> best τ=0.395 (val F1=0.2962)
  Directional -> Accuracy: 0.5270, MCC: 0.0375, F1: 0.5882

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.53247 | val 1.17469
  Epoch 012 - train 0.63015 | val 1.03621
  Classification -> best τ=0.590 (val F1=0.3945)
  Directional -> Accuracy: 0.7000, MCC: 0.3991, F1: 0.7273

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.59269 | val 0.69322
  Epoch 018 - train 0.41853 | val 1.58049
  Classification -> best τ=0.525 (val F1=0.3669)
  Directional -> Accuracy: 0.5217, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.64587 | val 1.20424
  Epoch 011 - train 0.63551 | val 1.31757
  Classification -> best τ=0.375 (val F1=0.3287)
  Directional -> Accuracy: 0.5147, MCC: 0.1115, F1: 0.5479

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.53360 | val 0.80629
  Epoch 018 - train 0.38490 | val 0.81612
  Classification -> best τ=0.510 (val F1=0.3632)
  Directional -> Accuracy: 0.5000, MCC: -0.1291, F1: 0.1600

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.62836 | val 1.58402
  Epoch 011 - train 0.60206 | val 1.64483
  Classification -> best τ=0.660 (val F1=0.1837)
  Directional -> Accuracy: 0.6250, MCC: 0.2308, F1: 0.5500

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.62817 | val 1.53163
  Epoch 011 - train 0.57290 | val 1.15546
  Classification -> best τ=0.375 (val F1=0.2679)
  Directional -> Accuracy: 0.4928, MCC: 0.0780, F1: 0.5679

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.61439 | val 0.84368
  Epoch 015 - train 0.59389 | val 0.91957
  Classification -> best τ=0.525 (val F1=0.2534)
  Directional -> Accuracy: 0.5918, MCC: 0.1538, F1: 0.4118

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.66044 | val 1.23239
  Epoch 012 - train 0.52680 | val 1.95318
  Classification -> best τ=0.755 (val F1=0.1181)
  Directional -> Accuracy: 0.5263, MCC: 0.0842, F1: 0.3077

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.55498 | val 1.55174
  Epoch 011 - train 0.49023 | val 2.05108
  Classification -> best τ=0.345 (val F1=0.2466)
  Directional -> Accuracy: 0.4762, MCC: 0.1419, F1: 0.6333

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.64878 | val 0.67041
  Epoch 015 - train 0.55888 | val 0.78142
  Classification -> best τ=0.235 (val F1=0.4343)
  Directional -> Accuracy: 0.5667, MCC: 0.1508, F1: 0.4348

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.64291 | val 0.83544
  Epoch 015 - train 0.59773 | val 0.94039
  Classification -> best τ=0.585 (val F1=0.2571)
  Directional -> Accuracy: 0.5490, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.61833 | val 1.71883
  Epoch 011 - train 0.58166 | val 2.03999
  Classification -> best τ=0.705 (val F1=0.1709)
  Directional -> Accuracy: 0.4638, MCC: 0.0000, F1: 0.0000

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.62317 | val 1.09152
  Epoch 011 - train 0.58212 | val 1.16408
  Classification -> best τ=0.405 (val F1=0.1486)
  Directional -> Accuracy: 0.5690, MCC: 0.2994, F1: 0.5098

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.60697 | val 0.88135
  Epoch 011 - train 0.57413 | val 0.87329
  Classification -> best τ=0.645 (val F1=0.2220)
  Directional -> Accuracy: 0.4000, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.61888 | val 0.94907
  Epoch 016 - train 0.61152 | val 0.95505
  Classification -> best τ=0.290 (val F1=0.3140)
  Directional -> Accuracy: 0.4844, MCC: 0.1062, F1: 0.2979

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.57945 | val 1.71647
  Epoch 011 - train 0.54014 | val 1.40736
  Classification -> best τ=0.510 (val F1=0.3439)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.59280 | val 1.23278
  Epoch 011 - train 0.56205 | val 1.46440
  Classification -> best τ=0.455 (val F1=0.3251)
  Directional -> Accuracy: 0.5106, MCC: 0.0373, F1: 0.5490

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.67842 | val 0.78762
  Epoch 014 - train 0.54703 | val 1.28924
  Classification -> best τ=0.695 (val F1=0.0905)
  Directional -> Accuracy: 0.5077, MCC: 0.0699, F1: 0.1111

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.66447 | val 0.73375
  Epoch 020 - train 0.55969 | val 2.20853
  Epoch 021 - train 0.50551 | val 1.99327
  Classification -> best τ=0.780 (val F1=0.4037)
  Directional -> Accuracy: 0.6316, MCC: 0.2553, F1: 0.6667

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.73446 | val 0.77395
  Epoch 011 - train 0.67827 | val 1.15399
  Classification -> best τ=0.425 (val F1=0.1568)
  Directional -> Accuracy: 0.4615, MCC: -0.0616, F1: 0.5783

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.56768 | val 0.91887
  Epoch 011 - train 0.54172 | val 1.63308
  Classification -> best τ=0.505 (val F1=0.5278)
  Directional -> Accuracy: 0.5273, MCC: 0.1463, F1: 0.3500

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.57080 | val 3.50367
  Epoch 011 - train 0.54787 | val 4.07380
  Classification -> best τ=0.695 (val F1=0.0524)
  Directional -> Accuracy: 0.5778, MCC: 0.0340, F1: 0.0952

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.64357 | val 0.75142
  Epoch 011 - train 0.59842 | val 1.01756
  Classification -> best τ=0.460 (val F1=0.2527)
  Directional -> Accuracy: 0.5952, MCC: 0.1680, F1: 0.6531

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.57505 | val 1.73738
  Epoch 011 - train 0.57512 | val 1.33199
  Classification -> best τ=0.420 (val F1=0.3181)
  Directional -> Accuracy: 0.4464, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.59131 | val 1.06932
  Epoch 011 - train 0.60914 | val 1.34042
  Classification -> best τ=0.575 (val F1=0.4109)
  Directional -> Accuracy: 0.6000, MCC: 0.1830, F1: 0.7143

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.61801 | val 0.69251
  Epoch 016 - train 0.52339 | val 0.80361
  Classification -> best τ=0.625 (val F1=0.4673)
  Directional -> Accuracy: 0.4762, MCC: -0.0674, F1: 0.3529

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.69163 | val 1.02310
  Epoch 020 - train 0.59473 | val 1.57920
  Epoch 021 - train 0.49597 | val 1.51991
  Classification -> best τ=0.365 (val F1=0.1986)
  Directional -> Accuracy: 0.5714, MCC: 0.1090, F1: 0.7000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.50318 | val 1.18783
  Epoch 011 - train 0.50951 | val 1.33218
  Classification -> best τ=0.450 (val F1=0.2521)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.61515 | val 0.73900
  Epoch 016 - train 0.53726 | val 1.06128
  Classification -> best τ=0.530 (val F1=0.2292)
  Directional -> Accuracy: 0.4583, MCC: 0.1061, F1: 0.0488

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.57999 | val 0.84019
  Epoch 011 - train 0.51756 | val 0.85426
  Classification -> best τ=0.440 (val F1=0.1309)
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.60550 | val 1.59918
  Epoch 011 - train 0.61395 | val 1.13986
  Classification -> best τ=0.380 (val F1=0.3551)
  Directional -> Accuracy: 0.5455, MCC: -0.0582, F1: 0.6939

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.51198 | val 1.67111
  Epoch 011 - train 0.42030 | val 2.29140
  Classification -> best τ=0.490 (val F1=0.3287)
  Directional -> Accuracy: 0.5000, MCC: 0.0561, F1: 0.2222

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.55308 | val 1.79161
  Epoch 011 - train 0.60868 | val 1.15467
  Classification -> best τ=0.400 (val F1=0.2868)
  Directional -> Accuracy: 0.5000, MCC: 0.0601, F1: 0.6111

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.54110 | val 1.24279
  Epoch 011 - train 0.50884 | val 1.29309
  Classification -> best τ=0.460 (val F1=0.2268)
  Directional -> Accuracy: 0.3913, MCC: -0.1022, F1: 0.2222

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.63253 | val 0.85646
  Epoch 014 - train 0.61310 | val 0.80166
  Classification -> best τ=0.215 (val F1=0.4201)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.56080 | val 1.89075
  Epoch 011 - train 0.57882 | val 1.95755
  Classification -> best τ=0.315 (val F1=0.2998)
  Directional -> Accuracy: 0.5270, MCC: 0.2001, F1: 0.6729

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.64751 | val 0.72553
  Epoch 012 - train 0.56361 | val 0.75749
  Classification -> best τ=0.450 (val F1=0.3190)
  Directional -> Accuracy: 0.4889, MCC: -0.1474, F1: 0.6567

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.51736 | val 1.48931
  Epoch 011 - train 0.51460 | val 1.99977
  Classification -> best τ=0.515 (val F1=0.2677)
  Directional -> Accuracy: 0.6429, MCC: 0.2513, F1: 0.7368

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.51086 | val 0.61219
  Epoch 020 - train 0.33962 | val 0.50414
  Epoch 030 - train 0.27207 | val 0.58345
  Classification -> best τ=0.340 (val F1=0.6290)
  Directional -> Accuracy: 0.4375, MCC: 0.2000, F1: 0.5714

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.64277 | val 0.90575
  Epoch 011 - train 0.64919 | val 1.25415
  Classification -> best τ=0.565 (val F1=0.2036)
  Directional -> Accuracy: 0.4545, MCC: -0.0177, F1: 0.0625

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.53424 | val 2.02121
  Epoch 011 - train 0.55895 | val 2.02376
  Classification -> best τ=0.760 (val F1=0.3818)
  Directional -> Accuracy: 0.6250, MCC: 0.2815, F1: 0.6769

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.70576 | val 0.71912
  Epoch 017 - train 0.68561 | val 1.05305
  Classification -> best τ=0.490 (val F1=0.2415)
  Directional -> Accuracy: 0.5849, MCC: 0.2020, F1: 0.6857

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.58779 | val 2.75199
  Epoch 012 - train 0.53585 | val 4.22572
  Classification -> best τ=0.685 (val F1=0.2283)
  Directional -> Accuracy: 0.5273, MCC: 0.0000, F1: 0.6905

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.64291 | val 0.69822

[I 2026-02-22 12:18:35,592] Trial 167 finished with value: 0.28595352119441836 and parameters: {'feature_set': 'sector', 'model_type': 'BiGRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.6000000000000001, 'batch_size': 16, 'learning_rate': 0.005273472598984194, 'weight_decay': 2.141487137686953e-05, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 1.008475839960821, 'early_stopping_min_delta': 2.6547208818104872e-05}. Best is trial 159 with value: 0.297766251520741.

  Epoch 015 - train 0.62151 | val 1.07636
  Classification -> best τ=0.615 (val F1=0.2623)
  Directional -> Accuracy: 0.5167, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.28595352119441836
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.64651 | val 0.95836
  Epoch 012 - train 0.65693 | val 1.06791
  Classification -> best τ=0.725 (val F1=0.2510)
  Directional -> Accuracy: 0.6184, MCC: 0.2435, F1: 0.3256

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.48274 | val 1.11234
  Epoch 011 - train 0.49462 | val 1.30045
  Classification -> best τ=0.590 (val F1=0.0492)
  Directional -> Accuracy: 0.6000, MCC: 0.1350, F1: 0.7097

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.56567 | val 2.98225
  Epoch 013 - train 0.60846 | val 1.70183
  Classification -> best τ=0.655 (val F1=0.3482)
  Directional -> Accuracy: 0.4565, MCC: -0.0996, F1: 0.0741

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.60239 | val 0.99644
  Epoch 013 - train 0.56769 | val 0.76287
  Classification -> best τ=0.550 (val F1=0.1844)
  Directional -> Accuracy: 0.4865, MCC: 0.0590, F1: 0.2083

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.57510 | val 1.01609
  Epoch 011 - train 0.56301 | val 0.89006
  Classification -> best τ=0.575 (val F1=0.3612)
  Directional -> Accuracy: 0.6600, MCC: 0.3398, F1: 0.6222

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.50489 | val 1.09249
  Epoch 012 - train 0.51221 | val 0.76507
  Classification -> best τ=0.560 (val F1=0.4538)
  Directional -> Accuracy: 0.4783, MCC: 0.0000, F1: 0.6471

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.62070 | val 1.09834
  Epoch 011 - train 0.57256 | val 0.82638
  Classification -> best τ=0.570 (val F1=0.2536)
  Directional -> Accuracy: 0.5294, MCC: 0.1201, F1: 0.5429

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.59603 | val 0.66765
  Epoch 017 - train 0.43395 | val 1.14541
  Classification -> best τ=0.360 (val F1=0.3632)
  Directional -> Accuracy: 0.4762, MCC: -0.0694, F1: 0.3889

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.56406 | val 1.93604
  Epoch 012 - train 0.56036 | val 2.20006
  Classification -> best τ=0.625 (val F1=0.2443)
  Directional -> Accuracy: 0.4375, MCC: 0.0000, F1: 0.6087

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.58395 | val 0.71582
  Epoch 013 - train 0.56075 | val 0.99077
  Classification -> best τ=0.830 (val F1=0.1607)
  Directional -> Accuracy: 0.4928, MCC: -0.0562, F1: 0.3636

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.59609 | val 0.68520
  Epoch 013 - train 0.61117 | val 0.67018
  Classification -> best τ=0.410 (val F1=0.3957)
  Directional -> Accuracy: 0.5918, MCC: 0.1538, F1: 0.4118

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.63675 | val 1.74164
  Epoch 011 - train 0.64541 | val 1.13028
  Classification -> best τ=0.435 (val F1=0.1512)
  Directional -> Accuracy: 0.5088, MCC: 0.0000, F1: 0.6744

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.50825 | val 4.39477
  Epoch 011 - train 0.54491 | val 4.07647
  Classification -> best τ=0.385 (val F1=0.0875)
  Directional -> Accuracy: 0.4762, MCC: -0.0214, F1: 0.5217

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.63072 | val 0.73547
  Epoch 012 - train 0.57727 | val 0.86768
  Classification -> best τ=0.555 (val F1=0.3864)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.57064 | val 0.80857
  Epoch 017 - train 0.52863 | val 0.76372
  Classification -> best τ=0.375 (val F1=0.2787)
  Directional -> Accuracy: 0.6078, MCC: 0.2081, F1: 0.5652

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.61196 | val 1.54456
  Epoch 012 - train 0.54126 | val 1.36064
  Classification -> best τ=0.905 (val F1=0.1385)
  Directional -> Accuracy: 0.4638, MCC: 0.0000, F1: 0.0000

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.60836 | val 1.12134
  Epoch 011 - train 0.60516 | val 1.20251
  Classification -> best τ=0.485 (val F1=0.0161)
  Directional -> Accuracy: 0.5517, MCC: 0.0981, F1: 0.6061

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.61745 | val 0.85705
  Epoch 011 - train 0.59189 | val 0.89382
  Classification -> best τ=0.485 (val F1=0.2262)
  Directional -> Accuracy: 0.5200, MCC: 0.2301, F1: 0.3793

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.55458 | val 1.11278
  Epoch 012 - train 0.59208 | val 1.14185
  Classification -> best τ=0.305 (val F1=0.3948)
  Directional -> Accuracy: 0.5625, MCC: -0.0129, F1: 0.7083

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.56215 | val 1.15562
  Epoch 011 - train 0.55993 | val 1.26564
  Classification -> best τ=0.645 (val F1=0.2230)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.55417 | val 0.82254
  Epoch 014 - train 0.46485 | val 1.09347
  Classification -> best τ=0.640 (val F1=0.1978)
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.58110 | val 1.08160
  Epoch 011 - train 0.54438 | val 1.47980
  Classification -> best τ=0.470 (val F1=0.3279)
  Directional -> Accuracy: 0.5231, MCC: 0.0720, F1: 0.3111

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.61527 | val 0.71286
  Epoch 011 - train 0.60399 | val 0.72103
  Classification -> best τ=0.625 (val F1=0.4037)
  Directional -> Accuracy: 0.5263, MCC: 0.1268, F1: 0.4255

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.63967 | val 1.12212
  Epoch 012 - train 0.57803 | val 1.25120
  Classification -> best τ=0.650 (val F1=0.1565)
  Directional -> Accuracy: 0.5077, MCC: -0.0261, F1: 0.2000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.53092 | val 1.30554
  Epoch 012 - train 0.56025 | val 1.62251
  Classification -> best τ=0.440 (val F1=0.5472)
  Directional -> Accuracy: 0.5455, MCC: 0.1641, F1: 0.4186

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.56926 | val 2.25102
  Epoch 011 - train 0.48587 | val 2.31766
  Classification -> best τ=0.600 (val F1=0.1890)
  Directional -> Accuracy: 0.5111, MCC: -0.1186, F1: 0.1538

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.57537 | val 0.95861
  Epoch 011 - train 0.58616 | val 1.15023
  Classification -> best τ=0.545 (val F1=0.1353)
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.0000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.56391 | val 1.25110
  Epoch 011 - train 0.57443 | val 1.08864
  Classification -> best τ=0.390 (val F1=0.2622)
  Directional -> Accuracy: 0.4464, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.59704 | val 1.08179
  Epoch 011 - train 0.61125 | val 0.99632
  Classification -> best τ=0.600 (val F1=0.1580)
  Directional -> Accuracy: 0.5500, MCC: 0.0580, F1: 0.6538

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.56531 | val 1.13106
  Epoch 013 - train 0.62351 | val 1.07336
  Classification -> best τ=0.595 (val F1=0.3501)
  Directional -> Accuracy: 0.5476, MCC: 0.0912, F1: 0.5128

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.62569 | val 1.34196
  Epoch 011 - train 0.56079 | val 0.99748
  Classification -> best τ=0.455 (val F1=0.0521)
  Directional -> Accuracy: 0.5238, MCC: 0.0389, F1: 0.5652

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.54423 | val 1.04198
  Epoch 011 - train 0.56832 | val 1.13251
  Classification -> best τ=0.495 (val F1=0.2978)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.57856 | val 1.26213
  Epoch 011 - train 0.56596 | val 1.37303
  Classification -> best τ=0.505 (val F1=0.1838)
  Directional -> Accuracy: 0.4444, MCC: 0.0000, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.53911 | val 1.28697
  Epoch 011 - train 0.51241 | val 1.70328
  Classification -> best τ=0.385 (val F1=0.1874)
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.59185 | val 0.83518
  Epoch 011 - train 0.58879 | val 1.12903
  Classification -> best τ=0.330 (val F1=0.3814)
  Directional -> Accuracy: 0.5909, MCC: 0.1313, F1: 0.6824

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.51828 | val 3.21778
  Epoch 011 - train 0.47211 | val 3.19931
  Classification -> best τ=0.580 (val F1=0.2618)
  Directional -> Accuracy: 0.5714, MCC: 0.2197, F1: 0.4000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.55702 | val 1.74470
  Epoch 012 - train 0.52333 | val 2.78393
  Classification -> best τ=0.590 (val F1=0.2305)
  Directional -> Accuracy: 0.5714, MCC: 0.2067, F1: 0.1429

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.50600 | val 1.00310
  Epoch 011 - train 0.53263 | val 1.35384
  Classification -> best τ=0.620 (val F1=0.2659)
  Directional -> Accuracy: 0.3696, MCC: -0.1490, F1: 0.0645

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.51833 | val 0.86577
  Epoch 013 - train 0.58406 | val 1.02948
  Classification -> best τ=0.490 (val F1=0.4011)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.56888 | val 1.99427
  Epoch 011 - train 0.55812 | val 1.89212
  Classification -> best τ=0.450 (val F1=0.2001)
  Directional -> Accuracy: 0.5000, MCC: -0.1139, F1: 0.0000

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.59209 | val 0.67510
  Epoch 019 - train 0.46692 | val 0.73842
  Classification -> best τ=0.610 (val F1=0.4080)
  Directional -> Accuracy: 0.6000, MCC: 0.2200, F1: 0.5263

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.49234 | val 2.32934
  Epoch 011 - train 0.44393 | val 2.15081
  Classification -> best τ=0.515 (val F1=0.3015)
  Directional -> Accuracy: 0.5952, MCC: 0.1803, F1: 0.7385

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.52510 | val 0.75305
  Epoch 012 - train 0.45559 | val 1.34595
  Classification -> best τ=0.425 (val F1=0.3458)
  Directional -> Accuracy: 0.4375, MCC: 0.2000, F1: 0.5714

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.60138 | val 2.02686
  Epoch 011 - train 0.65303 | val 2.36456
  Classification -> best τ=0.485 (val F1=0.2036)
  Directional -> Accuracy: 0.4545, MCC: -0.0177, F1: 0.0625

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.54525 | val 2.01147
  Epoch 011 - train 0.48457 | val 2.81600
  Classification -> best τ=0.805 (val F1=0.4039)
  Directional -> Accuracy: 0.5714, MCC: 0.1801, F1: 0.6471

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.61674 | val 1.04135
  Epoch 012 - train 0.62287 | val 0.70645
  Classification -> best τ=0.425 (val F1=0.1901)
  Directional -> Accuracy: 0.6415, MCC: 0.3354, F1: 0.7246

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.53274 | val 5.31037
  Epoch 011 - train 0.53370 | val 5.02146
  Classification -> best τ=0.820 (val F1=0.0094)
  Directional -> Accuracy: 0.5455, MCC: 0.1437, F1: 0.6988

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.61699 | val 1.23135

[I 2026-02-22 12:21:01,216] Trial 168 finished with value: 0.2561340651230926 and parameters: {'feature_set': 'sector', 'model_type': 'BiGRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.5, 'batch_size': 16, 'learning_rate': 0.005069492680226714, 'weight_decay': 2.2965397426784812e-05, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 1.080282429537096, 'early_stopping_min_delta': 0.00027820816986122855}. Best is trial 159 with value: 0.297766251520741.

  Epoch 017 - train 0.56925 | val 0.95399
  Classification -> best τ=0.480 (val F1=0.2749)
  Directional -> Accuracy: 0.5500, MCC: 0.1920, F1: 0.1290

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2561340651230926
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.65132 | val 0.90500
  Epoch 011 - train 0.65429 | val 1.36029
  Classification -> best τ=0.745 (val F1=0.2036)
  Directional -> Accuracy: 0.5526, MCC: 0.0000, F1: 0.0000

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.57889 | val 1.20244
  Epoch 011 - train 0.60274 | val 1.54457
  Classification -> best τ=0.465 (val F1=0.1857)
  Directional -> Accuracy: 0.5778, MCC: 0.0000, F1: 0.7324

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.64771 | val 1.02311
  Epoch 011 - train 0.63151 | val 0.98967
  Classification -> best τ=0.560 (val F1=0.3114)
  Directional -> Accuracy: 0.4783, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.60539 | val 1.63504
  Epoch 011 - train 0.60689 | val 1.35004
  Classification -> best τ=0.360 (val F1=0.1079)
  Directional -> Accuracy: 0.4459, MCC: -0.1269, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.57719 | val 1.39846
  Epoch 012 - train 0.54476 | val 1.02031
  Classification -> best τ=0.575 (val F1=0.4787)
  Directional -> Accuracy: 0.6200, MCC: 0.2573, F1: 0.5778

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.56877 | val 0.87613
  Epoch 013 - train 0.54977 | val 0.80620
  Classification -> best τ=0.620 (val F1=0.3994)
  Directional -> Accuracy: 0.5217, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.64768 | val 0.84947
  Epoch 011 - train 0.62921 | val 0.92459
  Classification -> best τ=0.375 (val F1=0.2013)
  Directional -> Accuracy: 0.3971, MCC: 0.0000, F1: 0.5684

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.65483 | val 0.54152
  Epoch 020 - train 0.50920 | val 1.35447
  Classification -> best τ=0.480 (val F1=0.5247)
  Directional -> Accuracy: 0.4762, MCC: -0.0550, F1: 0.4211

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.58132 | val 1.13055
  Epoch 011 - train 0.56915 | val 1.28534
  Classification -> best τ=0.585 (val F1=0.2443)
  Directional -> Accuracy: 0.6250, MCC: 0.2308, F1: 0.5500

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.62220 | val 1.04257
  Epoch 011 - train 0.63080 | val 0.94014
  Classification -> best τ=0.405 (val F1=0.0765)
  Directional -> Accuracy: 0.4928, MCC: 0.1099, F1: 0.5882

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.63220 | val 0.86816
  Epoch 020 - train 0.53078 | val 1.76549
  Epoch 023 - train 0.53495 | val 1.06398
  Classification -> best τ=0.490 (val F1=0.2661)
  Directional -> Accuracy: 0.5306, MCC: 0.0637, F1: 0.5106

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.67484 | val 1.21910
  Epoch 011 - train 0.62562 | val 1.09565
  Classification -> best τ=0.455 (val F1=0.1990)
  Directional -> Accuracy: 0.5088, MCC: 0.0048, F1: 0.6585

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.56965 | val 2.97991
  Epoch 011 - train 0.55820 | val 3.30977
  Classification -> best τ=0.375 (val F1=0.3172)
  Directional -> Accuracy: 0.5714, MCC: 0.2781, F1: 0.6667

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.64862 | val 0.62049
  Epoch 017 - train 0.58847 | val 0.60885
  Classification -> best τ=0.665 (val F1=0.4109)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.65102 | val 0.73994
  Epoch 011 - train 0.61573 | val 0.77275
  Classification -> best τ=0.545 (val F1=0.2078)
  Directional -> Accuracy: 0.5294, MCC: 0.0424, F1: 0.4545

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.63025 | val 1.39643
  Epoch 011 - train 0.60046 | val 1.29040
  Classification -> best τ=0.620 (val F1=0.2097)
  Directional -> Accuracy: 0.5507, MCC: 0.0987, F1: 0.5753

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.59422 | val 1.64592
  Epoch 011 - train 0.61650 | val 1.57761
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.6207, MCC: 0.0000, F1: 0.7660

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.63087 | val 0.95367
  Epoch 011 - train 0.59390 | val 1.13330
  Classification -> best τ=0.575 (val F1=0.1909)
  Directional -> Accuracy: 0.3867, MCC: -0.1123, F1: 0.1154

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.62910 | val 0.77591
  Epoch 015 - train 0.54550 | val 1.05583
  Classification -> best τ=0.170 (val F1=0.2843)
  Directional -> Accuracy: 0.5781, MCC: 0.0000, F1: 0.7327

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.56487 | val 1.41110
  Epoch 011 - train 0.55061 | val 1.60310
  Classification -> best τ=0.280 (val F1=0.2333)
  Directional -> Accuracy: 0.4730, MCC: 0.1495, F1: 0.0930

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.61697 | val 0.95500
  Epoch 011 - train 0.61164 | val 0.98960
  Classification -> best τ=0.515 (val F1=0.3673)
  Directional -> Accuracy: 0.3617, MCC: -0.1524, F1: 0.0625

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.66986 | val 0.75240
  Epoch 011 - train 0.60707 | val 0.80385
  Classification -> best τ=0.455 (val F1=0.2037)
  Directional -> Accuracy: 0.5077, MCC: 0.0000, F1: 0.6735

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.68542 | val 0.66602
  Epoch 015 - train 0.62422 | val 0.76256
  Classification -> best τ=0.630 (val F1=0.4639)
  Directional -> Accuracy: 0.5088, MCC: 0.0286, F1: 0.5172

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.64488 | val 0.71446
  Epoch 011 - train 0.64375 | val 0.81901
  Classification -> best τ=0.465 (val F1=0.1974)
  Directional -> Accuracy: 0.4769, MCC: 0.0000, F1: 0.6458

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.59889 | val 1.32750
  Epoch 012 - train 0.59201 | val 1.34957
  Classification -> best τ=0.505 (val F1=0.4994)
  Directional -> Accuracy: 0.5818, MCC: 0.1817, F1: 0.5660

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.60356 | val 3.52447
  Epoch 011 - train 0.58407 | val 3.89680
  Classification -> best τ=0.545 (val F1=0.1310)
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.5938

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.65677 | val 1.05703
  Epoch 011 - train 0.61110 | val 1.31274
  Classification -> best τ=0.430 (val F1=0.1376)
  Directional -> Accuracy: 0.4762, MCC: -0.0694, F1: 0.5417

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.58530 | val 0.88609
  Epoch 011 - train 0.59300 | val 0.92106
  Classification -> best τ=0.345 (val F1=0.2315)
  Directional -> Accuracy: 0.5714, MCC: 0.2385, F1: 0.4545

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.56627 | val 0.74642
  Epoch 012 - train 0.66644 | val 0.82834
  Classification -> best τ=0.510 (val F1=0.2414)
  Directional -> Accuracy: 0.6000, MCC: 0.2010, F1: 0.7241

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.63211 | val 0.63958
  Epoch 020 - train 0.55717 | val 0.77716
  Classification -> best τ=0.705 (val F1=0.3501)
  Directional -> Accuracy: 0.5476, MCC: 0.0912, F1: 0.5128

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.64338 | val 1.35169
  Epoch 011 - train 0.70018 | val 1.66788
  Classification -> best τ=0.455 (val F1=0.0769)
  Directional -> Accuracy: 0.5476, MCC: 0.0000, F1: 0.7077

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.52704 | val 1.20050
  Epoch 011 - train 0.59010 | val 1.29501
  Classification -> best τ=0.590 (val F1=0.2969)
  Directional -> Accuracy: 0.3878, MCC: -0.2340, F1: 0.1667

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.63179 | val 0.79016
  Epoch 014 - train 0.59197 | val 0.94443
  Classification -> best τ=0.660 (val F1=0.2414)
  Directional -> Accuracy: 0.5139, MCC: 0.1292, F1: 0.3396

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.56628 | val 1.12901
  Epoch 011 - train 0.54573 | val 1.04261
  Classification -> best τ=0.535 (val F1=0.2603)
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.62940 | val 1.05105
  Epoch 012 - train 0.59967 | val 1.65409
  Classification -> best τ=0.345 (val F1=0.2518)
  Directional -> Accuracy: 0.5909, MCC: 0.1018, F1: 0.7273

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.61633 | val 2.80560
  Epoch 011 - train 0.56333 | val 2.73570
  Classification -> best τ=0.465 (val F1=0.3068)
  Directional -> Accuracy: 0.5952, MCC: 0.1992, F1: 0.6909

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.56794 | val 1.19729
  Epoch 011 - train 0.56996 | val 1.52221
  Classification -> best τ=0.460 (val F1=0.1362)
  Directional -> Accuracy: 0.4821, MCC: -0.0333, F1: 0.4727

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.54820 | val 1.09841
  Epoch 011 - train 0.55346 | val 0.90379
  Classification -> best τ=0.590 (val F1=0.3294)
  Directional -> Accuracy: 0.3696, MCC: -0.1490, F1: 0.0645

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.59298 | val 0.88652
  Epoch 014 - train 0.67561 | val 0.96373
  Classification -> best τ=0.780 (val F1=0.4306)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.55911 | val 1.85804
  Epoch 011 - train 0.63071 | val 1.28489
  Classification -> best τ=0.525 (val F1=0.3146)
  Directional -> Accuracy: 0.4459, MCC: -0.1329, F1: 0.2807

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.67594 | val 0.83216
  Epoch 017 - train 0.56732 | val 0.81728
  Classification -> best τ=0.545 (val F1=0.1890)
  Directional -> Accuracy: 0.5333, MCC: 0.1541, F1: 0.6866

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.61586 | val 1.10061
  Epoch 011 - train 0.56139 | val 1.25456
  Classification -> best τ=0.520 (val F1=0.4001)
  Directional -> Accuracy: 0.6190, MCC: 0.2222, F1: 0.6667

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.58447 | val 1.02630
  Epoch 020 - train 0.50562 | val 0.67345
  Epoch 029 - train 0.51532 | val 0.87864
  Classification -> best τ=0.370 (val F1=0.5689)
  Directional -> Accuracy: 0.6667, MCC: 0.3443, F1: 0.6190

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.66260 | val 1.53999
  Epoch 011 - train 0.66682 | val 1.45694
  Classification -> best τ=0.615 (val F1=0.2036)
  Directional -> Accuracy: 0.4545, MCC: -0.0177, F1: 0.0625

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.61582 | val 1.99184
  Epoch 011 - train 0.50999 | val 2.18438
  Classification -> best τ=0.535 (val F1=0.3104)
  Directional -> Accuracy: 0.5000, MCC: 0.0013, F1: 0.5000

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.64857 | val 0.80499
  Epoch 018 - train 0.57921 | val 0.94627
  Classification -> best τ=0.355 (val F1=0.2351)
  Directional -> Accuracy: 0.5849, MCC: 0.2912, F1: 0.7105

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.58481 | val 2.69031
  Epoch 011 - train 0.56888 | val 2.62566
  Classification -> best τ=0.535 (val F1=0.1372)
  Directional -> Accuracy: 0.5818, MCC: 0.1639, F1: 0.6849

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.64638 | val 0.66677
  Epoch 020 - train 0.55667 | val 1.25989

[I 2026-02-22 12:23:36,419] Trial 169 finished with value: 0.26972337757840187 and parameters: {'feature_set': 'sector', 'model_type': 'BiGRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.7000000000000001, 'batch_size': 16, 'learning_rate': 0.0027783715512773918, 'weight_decay': 1.9285854807059665e-05, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 1.0035489155648156, 'early_stopping_min_delta': 0.000577550153970621}. Best is trial 159 with value: 0.297766251520741.

  Epoch 021 - train 0.54918 | val 0.84129
  Classification -> best τ=0.515 (val F1=0.3812)
  Directional -> Accuracy: 0.5667, MCC: 0.1680, F1: 0.2778

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.26972337757840187
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.61140 | val 0.81391
  Epoch 019 - train 0.55986 | val 1.24527
  Classification -> best τ=0.520 (val F1=0.3286)
  Directional -> Accuracy: 0.6053, MCC: 0.2017, F1: 0.5588

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.60941 | val 0.81616
  Epoch 011 - train 0.54178 | val 0.87385
  Classification -> best τ=0.580 (val F1=0.1273)
  Directional -> Accuracy: 0.6000, MCC: 0.1500, F1: 0.6897

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.52034 | val 1.57905
  Epoch 011 - train 0.52029 | val 1.59523
  Classification -> best τ=0.675 (val F1=0.2311)
  Directional -> Accuracy: 0.4565, MCC: -0.0996, F1: 0.0741

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.63381 | val 1.02516
  Epoch 016 - train 0.60369 | val 0.69746
  Classification -> best τ=0.520 (val F1=0.2980)
  Directional -> Accuracy: 0.4730, MCC: 0.1079, F1: 0.0488

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.56563 | val 0.78826
  Epoch 013 - train 0.49704 | val 1.20765
  Classification -> best τ=0.570 (val F1=0.6019)
  Directional -> Accuracy: 0.6200, MCC: 0.2670, F1: 0.5581

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.58833 | val 0.89065
  Epoch 012 - train 0.48025 | val 0.92455
  Classification -> best τ=0.650 (val F1=0.2899)
  Directional -> Accuracy: 0.5217, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.63719 | val 0.91326
  Epoch 011 - train 0.59899 | val 1.07339
  Classification -> best τ=0.405 (val F1=0.2870)
  Directional -> Accuracy: 0.5588, MCC: 0.1393, F1: 0.5312

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.55696 | val 0.63897
  Epoch 017 - train 0.44036 | val 0.66192
  Classification -> best τ=0.765 (val F1=0.5247)
  Directional -> Accuracy: 0.5000, MCC: 0.0138, F1: 0.4878

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.57404 | val 2.13391
  Epoch 011 - train 0.58676 | val 1.74099
  Classification -> best τ=0.580 (val F1=0.2784)
  Directional -> Accuracy: 0.6458, MCC: 0.2845, F1: 0.6047

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.62609 | val 1.25350
  Epoch 012 - train 0.49874 | val 1.94514
  Classification -> best τ=0.905 (val F1=0.1607)
  Directional -> Accuracy: 0.5652, MCC: 0.0583, F1: 0.3478

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.61765 | val 0.65638
  Epoch 020 - train 0.48592 | val 0.61920
  Epoch 030 - train 0.35283 | val 0.93320
  Classification -> best τ=0.525 (val F1=0.4323)
  Directional -> Accuracy: 0.5306, MCC: -0.0043, F1: 0.2581

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.56533 | val 2.69613
  Epoch 011 - train 0.54623 | val 2.69400
  Classification -> best τ=0.615 (val F1=0.1685)
  Directional -> Accuracy: 0.4912, MCC: 0.0000, F1: 0.0000

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.48246 | val 3.28202
  Epoch 011 - train 0.56286 | val 2.60740
  Classification -> best τ=0.370 (val F1=0.1754)
  Directional -> Accuracy: 0.4286, MCC: -0.1647, F1: 0.3333

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.62391 | val 0.70509
  Epoch 018 - train 0.55980 | val 1.33255
  Classification -> best τ=0.685 (val F1=0.4109)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.56178 | val 0.75102
  Epoch 020 - train 0.46748 | val 0.90290
  Epoch 025 - train 0.39885 | val 1.17905
  Classification -> best τ=0.465 (val F1=0.2370)
  Directional -> Accuracy: 0.3529, MCC: -0.3256, F1: 0.5075

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.56919 | val 1.46840
  Epoch 011 - train 0.54407 | val 1.48438
  Classification -> best τ=0.680 (val F1=0.1385)
  Directional -> Accuracy: 0.4638, MCC: 0.0000, F1: 0.0000

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.56246 | val 1.00170
  Epoch 013 - train 0.50308 | val 1.10033
  Classification -> best τ=0.355 (val F1=0.1336)
  Directional -> Accuracy: 0.4828, MCC: 0.1361, F1: 0.3750

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.61426 | val 1.33137
  Epoch 011 - train 0.53873 | val 1.64690
  Classification -> best τ=0.250 (val F1=0.1958)
  Directional -> Accuracy: 0.6000, MCC: 0.1859, F1: 0.6512

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.59107 | val 1.10556
  Epoch 011 - train 0.54786 | val 1.22558
  Classification -> best τ=0.425 (val F1=0.2166)
  Directional -> Accuracy: 0.5625, MCC: 0.1420, F1: 0.5758

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.51555 | val 1.33764
  Epoch 011 - train 0.54387 | val 1.52173
  Classification -> best τ=0.555 (val F1=0.2870)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.59215 | val 0.88170
  Epoch 011 - train 0.51042 | val 1.16815
  Classification -> best τ=0.705 (val F1=0.2861)
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.60299 | val 1.79152
  Epoch 011 - train 0.61508 | val 1.14011
  Classification -> best τ=0.625 (val F1=0.2040)
  Directional -> Accuracy: 0.5231, MCC: 0.1014, F1: 0.2051

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.61352 | val 1.20733
  Epoch 011 - train 0.57082 | val 1.60212
  Classification -> best τ=0.465 (val F1=0.3032)
  Directional -> Accuracy: 0.5789, MCC: 0.1613, F1: 0.6000

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.58829 | val 0.79614
  Epoch 014 - train 0.50867 | val 1.10151
  Classification -> best τ=0.675 (val F1=0.1874)
  Directional -> Accuracy: 0.5385, MCC: 0.1309, F1: 0.0625

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.53911 | val 0.82686
  Epoch 013 - train 0.48282 | val 1.21999
  Classification -> best τ=0.390 (val F1=0.5463)
  Directional -> Accuracy: 0.5636, MCC: 0.2170, F1: 0.4286

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.53372 | val 2.75232
  Epoch 011 - train 0.54865 | val 3.15274
  Classification -> best τ=0.585 (val F1=0.2570)
  Directional -> Accuracy: 0.4667, MCC: -0.0230, F1: 0.5000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.60207 | val 0.74451
  Epoch 011 - train 0.55830 | val 1.05865
  Classification -> best τ=0.540 (val F1=0.1407)
  Directional -> Accuracy: 0.5238, MCC: 0.0550, F1: 0.5455

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.57659 | val 1.49279
  Epoch 011 - train 0.59761 | val 1.73791
  Classification -> best τ=0.185 (val F1=0.2315)
  Directional -> Accuracy: 0.5000, MCC: 0.0278, F1: 0.4615

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.55785 | val 1.27157
  Epoch 012 - train 0.50991 | val 0.70833
  Classification -> best τ=0.540 (val F1=0.4109)
  Directional -> Accuracy: 0.5750, MCC: 0.1240, F1: 0.7119

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.58042 | val 1.13490
  Epoch 016 - train 0.52185 | val 0.97574
  Classification -> best τ=0.385 (val F1=0.3823)
  Directional -> Accuracy: 0.4524, MCC: -0.0853, F1: 0.5106

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.55995 | val 0.90647
  Epoch 011 - train 0.50267 | val 1.11945
  Classification -> best τ=0.525 (val F1=0.1286)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.50331 | val 1.03755
  Epoch 011 - train 0.45103 | val 1.28388
  Classification -> best τ=0.610 (val F1=0.2969)
  Directional -> Accuracy: 0.5714, MCC: 0.1477, F1: 0.6957

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.58121 | val 0.96648
  Epoch 011 - train 0.61780 | val 0.85025
  Classification -> best τ=0.440 (val F1=0.3838)
  Directional -> Accuracy: 0.5278, MCC: 0.1291, F1: 0.4138

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.55778 | val 1.09992
  Epoch 011 - train 0.52867 | val 1.04506
  Classification -> best τ=0.375 (val F1=0.2717)
  Directional -> Accuracy: 0.5349, MCC: 0.2158, F1: 0.6774

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.58864 | val 1.15828
  Epoch 011 - train 0.59366 | val 1.24469
  Classification -> best τ=0.485 (val F1=0.4343)
  Directional -> Accuracy: 0.4545, MCC: 0.1517, F1: 0.1000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.49437 | val 3.67777
  Epoch 012 - train 0.54470 | val 2.48297
  Classification -> best τ=0.385 (val F1=0.2858)
  Directional -> Accuracy: 0.7143, MCC: 0.4318, F1: 0.7143

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.54723 | val 1.64948
  Epoch 011 - train 0.53750 | val 2.04580
  Classification -> best τ=0.355 (val F1=0.2114)
  Directional -> Accuracy: 0.5536, MCC: 0.1899, F1: 0.6479

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.46095 | val 1.00801
  Epoch 011 - train 0.52780 | val 0.84780
  Classification -> best τ=0.390 (val F1=0.1709)
  Directional -> Accuracy: 0.6087, MCC: 0.0000, F1: 0.7568

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.51484 | val 1.00181
  Epoch 016 - train 0.48207 | val 1.19512
  Classification -> best τ=0.270 (val F1=0.4011)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.56330 | val 1.97118
  Epoch 012 - train 0.52851 | val 2.03266
  Classification -> best τ=0.230 (val F1=0.3395)
  Directional -> Accuracy: 0.4459, MCC: -0.1117, F1: 0.4058

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.63255 | val 0.69346
  Epoch 013 - train 0.63056 | val 0.77672
  Classification -> best τ=0.525 (val F1=0.3500)
  Directional -> Accuracy: 0.4444, MCC: -0.1202, F1: 0.5098

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.43143 | val 1.64584
  Epoch 011 - train 0.38221 | val 2.41461
  Classification -> best τ=0.530 (val F1=0.4901)
  Directional -> Accuracy: 0.5952, MCC: 0.1334, F1: 0.7302

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.54284 | val 0.52208
  Epoch 020 - train 0.42999 | val 0.86979
  Classification -> best τ=0.380 (val F1=0.4682)
  Directional -> Accuracy: 0.5417, MCC: 0.1826, F1: 0.5600

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.63379 | val 0.92544
  Epoch 011 - train 0.63614 | val 1.06561
  Classification -> best τ=0.505 (val F1=0.2036)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.51560 | val 2.91905
  Epoch 011 - train 0.48989 | val 2.23174
  Classification -> best τ=0.490 (val F1=0.1949)
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.6506

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.63312 | val 0.80044
  Epoch 014 - train 0.58535 | val 1.17796
  Classification -> best τ=0.335 (val F1=0.2351)
  Directional -> Accuracy: 0.5283, MCC: 0.1413, F1: 0.6835

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.54509 | val 2.47851
  Epoch 011 - train 0.49880 | val 3.85842
  Classification -> best τ=0.695 (val F1=0.0322)
  Directional -> Accuracy: 0.4727, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.61562 | val 0.84048

[I 2026-02-22 12:26:15,524] Trial 170 finished with value: 0.2864820414715683 and parameters: {'feature_set': 'sector', 'model_type': 'BiGRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.5, 'batch_size': 16, 'learning_rate': 0.004284536497879828, 'weight_decay': 1.0012426177810585e-05, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 1.1831502752185388, 'early_stopping_min_delta': 4.196664520619073e-05}. Best is trial 159 with value: 0.297766251520741.

  Epoch 018 - train 0.53388 | val 1.41829
  Classification -> best τ=0.345 (val F1=0.3805)
  Directional -> Accuracy: 0.5000, MCC: -0.1259, F1: 0.0000

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2864820414715683
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.62913 | val 0.97728
  Epoch 011 - train 0.60802 | val 1.14269
  Classification -> best τ=0.620 (val F1=0.2082)
  Directional -> Accuracy: 0.6053, MCC: 0.1835, F1: 0.4231

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.56917 | val 1.31792
  Epoch 012 - train 0.52802 | val 0.91498
  Classification -> best τ=0.395 (val F1=0.1273)
  Directional -> Accuracy: 0.5778, MCC: 0.0000, F1: 0.7324

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.57884 | val 1.62886
  Epoch 011 - train 0.57871 | val 1.12033
  Classification -> best τ=0.670 (val F1=0.2727)
  Directional -> Accuracy: 0.4783, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.59194 | val 0.84051
  Epoch 020 - train 0.54258 | val 0.94433
  Epoch 030 - train 0.46064 | val 1.65074
  Classification -> best τ=0.335 (val F1=0.2920)
  Directional -> Accuracy: 0.5405, MCC: 0.0000, F1: 0.7018

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.53067 | val 0.82233
  Epoch 011 - train 0.52081 | val 0.92631
  Classification -> best τ=0.550 (val F1=0.3984)
  Directional -> Accuracy: 0.6600, MCC: 0.3309, F1: 0.6383

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.47402 | val 0.75691
  Epoch 011 - train 0.46776 | val 1.72717
  Classification -> best τ=0.470 (val F1=0.1808)
  Directional -> Accuracy: 0.4565, MCC: -0.0996, F1: 0.6154

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.58246 | val 1.08014
  Epoch 011 - train 0.60606 | val 1.09711
  Classification -> best τ=0.535 (val F1=0.2587)
  Directional -> Accuracy: 0.4853, MCC: 0.1672, F1: 0.5882

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.54400 | val 0.90131
  Epoch 011 - train 0.51819 | val 1.33463
  Classification -> best τ=0.500 (val F1=0.1639)
  Directional -> Accuracy: 0.5714, MCC: 0.0807, F1: 0.3571

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.55373 | val 1.36986
  Epoch 011 - train 0.61864 | val 1.75796
  Classification -> best τ=0.565 (val F1=0.2584)
  Directional -> Accuracy: 0.5417, MCC: 0.0788, F1: 0.5000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.53582 | val 0.95403
  Epoch 013 - train 0.56556 | val 1.16973
  Classification -> best τ=0.460 (val F1=0.3379)
  Directional -> Accuracy: 0.5072, MCC: 0.0265, F1: 0.4848

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.62475 | val 0.93303
  Epoch 011 - train 0.60761 | val 0.94709
  Classification -> best τ=0.630 (val F1=0.2484)
  Directional -> Accuracy: 0.5918, MCC: 0.1804, F1: 0.2308

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.64310 | val 1.10854
  Epoch 011 - train 0.57653 | val 1.22481
  Classification -> best τ=0.525 (val F1=0.1313)
  Directional -> Accuracy: 0.6491, MCC: 0.3234, F1: 0.7143

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.56294 | val 3.20528
  Epoch 011 - train 0.48990 | val 2.70578
  Classification -> best τ=0.420 (val F1=0.1991)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.6230

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.61466 | val 0.95293
  Epoch 013 - train 0.61270 | val 0.81463
  Classification -> best τ=0.510 (val F1=0.4109)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.56015 | val 0.91676
  Epoch 019 - train 0.49331 | val 0.88463
  Classification -> best τ=0.455 (val F1=0.2956)
  Directional -> Accuracy: 0.4510, MCC: 0.0000, F1: 0.6216

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.56803 | val 1.01446
  Epoch 011 - train 0.58498 | val 1.54782
  Classification -> best τ=0.470 (val F1=0.2795)
  Directional -> Accuracy: 0.5507, MCC: 0.0722, F1: 0.6667

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.59198 | val 1.23584
  Epoch 011 - train 0.54143 | val 1.19941
  Classification -> best τ=0.505 (val F1=0.0660)
  Directional -> Accuracy: 0.6207, MCC: 0.2090, F1: 0.6857

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.58174 | val 1.27040
  Epoch 012 - train 0.57328 | val 1.38130
  Classification -> best τ=0.585 (val F1=0.1909)
  Directional -> Accuracy: 0.4000, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.52995 | val 0.77580
  Epoch 012 - train 0.57933 | val 0.80075
  Classification -> best τ=0.465 (val F1=0.2359)
  Directional -> Accuracy: 0.4844, MCC: -0.0624, F1: 0.5600

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.54000 | val 1.38154
  Epoch 011 - train 0.56109 | val 0.96577
  Classification -> best τ=0.455 (val F1=0.3153)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.49122 | val 1.01858
  Epoch 011 - train 0.57445 | val 1.79190
  Classification -> best τ=0.535 (val F1=0.0705)
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.59645 | val 1.00981
  Epoch 011 - train 0.61469 | val 1.05061
  Classification -> best τ=0.370 (val F1=0.2019)
  Directional -> Accuracy: 0.6000, MCC: 0.2092, F1: 0.5517

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.65585 | val 0.82231
  Epoch 011 - train 0.58539 | val 0.85270
  Classification -> best τ=0.540 (val F1=0.3370)
  Directional -> Accuracy: 0.4912, MCC: 0.0250, F1: 0.4314

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.61465 | val 0.89675
  Epoch 011 - train 0.60645 | val 1.34563
  Classification -> best τ=0.490 (val F1=0.1348)
  Directional -> Accuracy: 0.5692, MCC: 0.1561, F1: 0.6111

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.56991 | val 1.69382
  Epoch 013 - train 0.51916 | val 1.14988
  Classification -> best τ=0.415 (val F1=0.5604)
  Directional -> Accuracy: 0.6182, MCC: 0.3130, F1: 0.5333

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.57105 | val 3.20437
  Epoch 011 - train 0.47219 | val 3.56383
  Classification -> best τ=0.595 (val F1=0.2035)
  Directional -> Accuracy: 0.3778, MCC: -0.2110, F1: 0.4167

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.61363 | val 1.16508
  Epoch 011 - train 0.60700 | val 1.13210
  Classification -> best τ=0.500 (val F1=0.1340)
  Directional -> Accuracy: 0.5476, MCC: 0.1260, F1: 0.5366

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.59364 | val 1.43461
  Epoch 011 - train 0.53759 | val 1.26343
  Classification -> best τ=0.470 (val F1=0.3147)
  Directional -> Accuracy: 0.4464, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.56061 | val 0.69792
  Epoch 020 - train 0.42933 | val 0.97297
  Epoch 022 - train 0.29458 | val 0.89532
  Classification -> best τ=0.495 (val F1=0.3239)
  Directional -> Accuracy: 0.5750, MCC: 0.1140, F1: 0.7018

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.60713 | val 1.23760
  Epoch 013 - train 0.47745 | val 1.52679
  Classification -> best τ=0.460 (val F1=0.3630)
  Directional -> Accuracy: 0.5238, MCC: 0.0754, F1: 0.6000

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.68244 | val 0.96680
  Epoch 011 - train 0.57008 | val 0.92362
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5476, MCC: 0.0000, F1: 0.7077

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.57591 | val 1.43887
  Epoch 011 - train 0.54290 | val 1.02603
  Classification -> best τ=0.380 (val F1=0.2932)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.60309 | val 1.08250
  Epoch 011 - train 0.55080 | val 0.74174
  Classification -> best τ=0.535 (val F1=0.3244)
  Directional -> Accuracy: 0.4583, MCC: 0.0466, F1: 0.0930

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.53593 | val 1.01176
  Epoch 011 - train 0.55223 | val 1.43876
  Classification -> best τ=0.555 (val F1=0.0427)
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.58449 | val 1.62588
  Epoch 011 - train 0.66794 | val 1.07670
  Classification -> best τ=0.395 (val F1=0.3327)
  Directional -> Accuracy: 0.4394, MCC: 0.1065, F1: 0.0513

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.46503 | val 3.64167
  Epoch 011 - train 0.63857 | val 3.89753
  Classification -> best τ=0.470 (val F1=0.3589)
  Directional -> Accuracy: 0.6190, MCC: 0.2697, F1: 0.5556

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.53131 | val 1.29792
  Epoch 011 - train 0.53666 | val 1.57437
  Classification -> best τ=0.470 (val F1=0.2622)
  Directional -> Accuracy: 0.5714, MCC: 0.1708, F1: 0.6129

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.57164 | val 1.59160
  Epoch 011 - train 0.53074 | val 1.69719
  Classification -> best τ=0.690 (val F1=0.2254)
  Directional -> Accuracy: 0.3913, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.59387 | val 0.68688
  Epoch 020 - train 0.50662 | val 0.81359
  Epoch 028 - train 0.34728 | val 1.23728
  Classification -> best τ=0.205 (val F1=0.5119)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.55791 | val 1.81514
  Epoch 011 - train 0.57917 | val 1.76564
  Classification -> best τ=0.435 (val F1=0.1940)
  Directional -> Accuracy: 0.4459, MCC: -0.1329, F1: 0.2807

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.60634 | val 0.70992
  Epoch 017 - train 0.56387 | val 0.98207
  Classification -> best τ=0.515 (val F1=0.3287)
  Directional -> Accuracy: 0.5556, MCC: 0.1266, F1: 0.6667

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.49342 | val 1.49434
  Epoch 012 - train 0.38809 | val 1.55360
  Classification -> best τ=0.465 (val F1=0.1667)
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.7273

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.50525 | val 1.18781
  Epoch 014 - train 0.50648 | val 2.37160
  Classification -> best τ=0.610 (val F1=0.5557)
  Directional -> Accuracy: 0.6458, MCC: 0.3630, F1: 0.6383

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.65849 | val 1.07075
  Epoch 011 - train 0.63268 | val 1.08865
  Classification -> best τ=0.570 (val F1=0.2036)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.50403 | val 3.42564
  Epoch 011 - train 0.52073 | val 1.93474
  Classification -> best τ=0.715 (val F1=0.3067)
  Directional -> Accuracy: 0.5714, MCC: 0.2072, F1: 0.6667

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.61684 | val 0.90428
  Epoch 017 - train 0.56063 | val 1.15732
  Classification -> best τ=0.545 (val F1=0.2407)
  Directional -> Accuracy: 0.5660, MCC: 0.1493, F1: 0.6667

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.58858 | val 2.73033
  Epoch 012 - train 0.54073 | val 1.75865
  Classification -> best τ=0.705 (val F1=0.2735)
  Directional -> Accuracy: 0.4545, MCC: -0.0743, F1: 0.3182

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.61508 | val 0.67060

[I 2026-02-22 12:28:51,420] Trial 171 finished with value: 0.26001787179550134 and parameters: {'feature_set': 'sector', 'model_type': 'BiGRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.5, 'batch_size': 16, 'learning_rate': 0.004328205579834787, 'weight_decay': 1.6552029066648895e-05, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 1.1619327551278458, 'early_stopping_min_delta': 0.0001638223852055692}. Best is trial 159 with value: 0.297766251520741.

  Epoch 020 - train 0.54747 | val 0.84270
  Classification -> best τ=0.605 (val F1=0.3448)
  Directional -> Accuracy: 0.5333, MCC: 0.0607, F1: 0.2632

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.26001787179550134
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.64054 | val 0.77827
  Epoch 011 - train 0.61172 | val 1.11617
  Classification -> best τ=0.560 (val F1=0.2510)
  Directional -> Accuracy: 0.5395, MCC: -0.1039, F1: 0.0000

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.62154 | val 0.77668
  Epoch 011 - train 0.55924 | val 0.79795
  Classification -> best τ=0.610 (val F1=0.1323)
  Directional -> Accuracy: 0.6000, MCC: 0.1924, F1: 0.6400

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.60118 | val 1.97111
  Epoch 011 - train 0.62405 | val 1.34640
  Classification -> best τ=0.765 (val F1=0.2398)
  Directional -> Accuracy: 0.4783, MCC: -0.0134, F1: 0.1429

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.62141 | val 0.89808
  Epoch 018 - train 0.56349 | val 1.71774
  Classification -> best τ=0.310 (val F1=0.2402)
  Directional -> Accuracy: 0.4730, MCC: 0.0520, F1: 0.0930

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.56930 | val 1.32046
  Epoch 014 - train 0.51859 | val 0.91218
  Classification -> best τ=0.695 (val F1=0.4947)
  Directional -> Accuracy: 0.6400, MCC: 0.3158, F1: 0.5714

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.56862 | val 0.82394
  Epoch 014 - train 0.48852 | val 0.86069
  Classification -> best τ=0.535 (val F1=0.4575)
  Directional -> Accuracy: 0.5652, MCC: 0.1679, F1: 0.2308

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.64657 | val 1.41565
  Epoch 011 - train 0.64379 | val 0.97121
  Classification -> best τ=0.395 (val F1=0.2727)
  Directional -> Accuracy: 0.4853, MCC: 0.1672, F1: 0.5882

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.55555 | val 0.62961
  Epoch 020 - train 0.40428 | val 0.71853
  Epoch 021 - train 0.40116 | val 0.91816
  Classification -> best τ=0.510 (val F1=0.3632)
  Directional -> Accuracy: 0.5000, MCC: -0.0138, F1: 0.4324

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.59281 | val 1.91326
  Epoch 011 - train 0.56084 | val 2.01959
  Classification -> best τ=0.650 (val F1=0.3433)
  Directional -> Accuracy: 0.5625, MCC: 0.0380, F1: 0.1600

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.63409 | val 0.69475
  Epoch 020 - train 0.53845 | val 0.82686
  Classification -> best τ=0.495 (val F1=0.2524)
  Directional -> Accuracy: 0.5072, MCC: 0.0170, F1: 0.4688

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.64371 | val 1.15977
  Epoch 011 - train 0.60571 | val 1.26627
  Classification -> best τ=0.575 (val F1=0.2765)
  Directional -> Accuracy: 0.6122, MCC: 0.2379, F1: 0.2963

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.61230 | val 0.93345
  Epoch 012 - train 0.56051 | val 1.60982
  Classification -> best τ=0.435 (val F1=0.2157)
  Directional -> Accuracy: 0.5088, MCC: 0.0000, F1: 0.6744

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.56777 | val 2.55937
  Epoch 011 - train 0.46391 | val 2.04571
  Classification -> best τ=0.500 (val F1=0.1754)
  Directional -> Accuracy: 0.4524, MCC: -0.1220, F1: 0.3429

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.63207 | val 0.68971
  Epoch 016 - train 0.51670 | val 0.84807
  Classification -> best τ=0.375 (val F1=0.4160)
  Directional -> Accuracy: 0.5333, MCC: 0.0707, F1: 0.4400

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.61510 | val 0.81398
  Epoch 012 - train 0.56625 | val 0.76193
  Classification -> best τ=0.535 (val F1=0.2571)
  Directional -> Accuracy: 0.5490, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.62519 | val 1.02306
  Epoch 011 - train 0.60074 | val 0.99874
  Classification -> best τ=0.515 (val F1=0.2341)
  Directional -> Accuracy: 0.5507, MCC: 0.0713, F1: 0.6737

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.62733 | val 1.93331
  Epoch 012 - train 0.56513 | val 2.44467
  Classification -> best τ=0.580 (val F1=0.1842)
  Directional -> Accuracy: 0.3793, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.62779 | val 0.80129
  Epoch 017 - train 0.53004 | val 0.86573
  Classification -> best τ=0.515 (val F1=0.1909)
  Directional -> Accuracy: 0.4000, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.58276 | val 0.92919
  Epoch 011 - train 0.58317 | val 1.16054
  Classification -> best τ=0.745 (val F1=0.1809)
  Directional -> Accuracy: 0.4219, MCC: -0.0284, F1: 0.0513

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.58135 | val 1.26246
  Epoch 011 - train 0.56670 | val 1.12585
  Classification -> best τ=0.630 (val F1=0.2771)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.61975 | val 1.35497
  Epoch 012 - train 0.53770 | val 1.50650
  Classification -> best τ=0.565 (val F1=0.1978)
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.59826 | val 0.85870
  Epoch 012 - train 0.64770 | val 0.98670
  Classification -> best τ=0.805 (val F1=0.2376)
  Directional -> Accuracy: 0.4923, MCC: -0.0027, F1: 0.0571

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.64784 | val 0.70485
  Epoch 019 - train 0.55000 | val 0.80614
  Classification -> best τ=0.490 (val F1=0.4370)
  Directional -> Accuracy: 0.5789, MCC: 0.1450, F1: 0.6250

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.64992 | val 0.88734
  Epoch 011 - train 0.63058 | val 0.84964
  Classification -> best τ=0.615 (val F1=0.2451)
  Directional -> Accuracy: 0.5538, MCC: 0.1866, F1: 0.1212

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.53246 | val 0.81535
  Epoch 011 - train 0.59471 | val 0.95573
  Classification -> best τ=0.495 (val F1=0.5048)
  Directional -> Accuracy: 0.6000, MCC: 0.2142, F1: 0.5926

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.62505 | val 2.85883
  Epoch 012 - train 0.52199 | val 3.42309
  Classification -> best τ=0.650 (val F1=0.1890)
  Directional -> Accuracy: 0.6222, MCC: 0.1941, F1: 0.3200

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.58781 | val 1.06504
  Epoch 011 - train 0.62561 | val 1.26240
  Classification -> best τ=0.415 (val F1=0.1936)
  Directional -> Accuracy: 0.6190, MCC: 0.2041, F1: 0.6923

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.58863 | val 1.26647
  Epoch 011 - train 0.56760 | val 1.27283
  Classification -> best τ=0.280 (val F1=0.2315)
  Directional -> Accuracy: 0.5357, MCC: 0.1242, F1: 0.4583

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.57244 | val 0.86317
  Epoch 012 - train 0.55841 | val 0.81080
  Classification -> best τ=0.515 (val F1=0.0989)
  Directional -> Accuracy: 0.5750, MCC: 0.1143, F1: 0.6792

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.66279 | val 0.88080
  Epoch 012 - train 0.63849 | val 0.68305
  Classification -> best τ=0.520 (val F1=0.3501)
  Directional -> Accuracy: 0.4762, MCC: -0.0674, F1: 0.3529

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.70427 | val 0.66371
  Epoch 020 - train 0.49128 | val 0.95460
  Classification -> best τ=0.485 (val F1=0.2357)
  Directional -> Accuracy: 0.5476, MCC: 0.0000, F1: 0.7077

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.59246 | val 1.15333
  Epoch 011 - train 0.58280 | val 0.80474
  Classification -> best τ=0.495 (val F1=0.3432)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.63102 | val 1.08745
  Epoch 012 - train 0.56779 | val 1.17090
  Classification -> best τ=0.300 (val F1=0.2593)
  Directional -> Accuracy: 0.5556, MCC: 0.0000, F1: 0.7143

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.52570 | val 1.44229
  Epoch 011 - train 0.55176 | val 1.19757
  Classification -> best τ=0.710 (val F1=0.0140)
  Directional -> Accuracy: 0.5349, MCC: 0.0660, F1: 0.4118

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.62070 | val 0.67251
  Epoch 020 - train 0.60512 | val 1.31846
  Classification -> best τ=0.145 (val F1=0.3342)
  Directional -> Accuracy: 0.5909, MCC: 0.1070, F1: 0.7327

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.57767 | val 2.46748
  Epoch 011 - train 0.50509 | val 3.14890
  Classification -> best τ=0.435 (val F1=0.2228)
  Directional -> Accuracy: 0.6429, MCC: 0.3127, F1: 0.5946

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.57321 | val 1.25504
  Epoch 011 - train 0.55146 | val 1.53578
  Classification -> best τ=0.550 (val F1=0.2382)
  Directional -> Accuracy: 0.5714, MCC: 0.1623, F1: 0.6000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.52704 | val 1.17217
  Epoch 011 - train 0.48093 | val 0.83411
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.6087, MCC: 0.0000, F1: 0.7568

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.54426 | val 0.83026
  Epoch 015 - train 0.50599 | val 0.98883
  Classification -> best τ=0.550 (val F1=0.4011)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.60477 | val 1.86003
  Epoch 012 - train 0.57536 | val 1.58722
  Classification -> best τ=0.425 (val F1=0.2869)
  Directional -> Accuracy: 0.4865, MCC: 0.0000, F1: 0.6545

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.63393 | val 0.71416
  Epoch 020 - train 0.49092 | val 1.55275
  Epoch 023 - train 0.49257 | val 1.27445
  Classification -> best τ=0.535 (val F1=0.3190)
  Directional -> Accuracy: 0.5333, MCC: 0.0950, F1: 0.6769

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.50920 | val 2.74969
  Epoch 012 - train 0.60471 | val 3.45826
  Classification -> best τ=0.595 (val F1=0.4277)
  Directional -> Accuracy: 0.5714, MCC: 0.1250, F1: 0.6250

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.55416 | val 1.31951
  Epoch 013 - train 0.48501 | val 0.76206
  Classification -> best τ=0.555 (val F1=0.4795)
  Directional -> Accuracy: 0.3958, MCC: 0.0222, F1: 0.5397

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.65527 | val 1.24611
  Epoch 012 - train 0.67442 | val 1.23443
  Classification -> best τ=0.690 (val F1=0.2132)
  Directional -> Accuracy: 0.4727, MCC: 0.1242, F1: 0.0645

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.53567 | val 2.58721
  Epoch 011 - train 0.53384 | val 1.99662
  Classification -> best τ=0.420 (val F1=0.3104)
  Directional -> Accuracy: 0.5179, MCC: 0.0333, F1: 0.4906

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.66202 | val 0.71054
  Epoch 020 - train 0.60316 | val 0.73776
  Epoch 021 - train 0.53526 | val 1.08170
  Classification -> best τ=0.585 (val F1=0.3242)
  Directional -> Accuracy: 0.6038, MCC: 0.2069, F1: 0.6316

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.54893 | val 5.03521
  Epoch 013 - train 0.53316 | val 2.53451
  Classification -> best τ=0.480 (val F1=0.2728)
  Directional -> Accuracy: 0.4727, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.59574 | val 0.79276

[I 2026-02-22 12:31:35,225] Trial 172 finished with value: 0.27442597497248616 and parameters: {'feature_set': 'sector', 'model_type': 'BiGRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.6000000000000001, 'batch_size': 16, 'learning_rate': 0.005668363714920424, 'weight_decay': 1.02735437464066e-05, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 1.2390298970773586, 'early_stopping_min_delta': 5.333895021002657e-05}. Best is trial 159 with value: 0.297766251520741.

  Epoch 013 - train 0.60192 | val 0.76792
  Classification -> best τ=0.535 (val F1=0.3496)
  Directional -> Accuracy: 0.5833, MCC: 0.2335, F1: 0.2857

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.27442597497248616
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.63454 | val 0.81962
  Epoch 011 - train 0.65415 | val 0.99865
  Classification -> best τ=0.815 (val F1=0.1713)
  Directional -> Accuracy: 0.5921, MCC: 0.1882, F1: 0.2051

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.58201 | val 0.94964
  Epoch 011 - train 0.55549 | val 1.06238
  Classification -> best τ=0.390 (val F1=0.1289)
  Directional -> Accuracy: 0.5778, MCC: 0.0000, F1: 0.7324

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.60746 | val 1.53712
  Epoch 011 - train 0.57486 | val 1.79377
  Classification -> best τ=0.595 (val F1=0.2941)
  Directional -> Accuracy: 0.4783, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.62172 | val 0.76406
  Epoch 011 - train 0.65736 | val 0.98658
  Classification -> best τ=0.455 (val F1=0.1537)
  Directional -> Accuracy: 0.4595, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.59572 | val 1.91562
  Epoch 012 - train 0.54801 | val 1.73883
  Classification -> best τ=0.655 (val F1=0.4083)
  Directional -> Accuracy: 0.6000, MCC: 0.2425, F1: 0.5000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.55294 | val 0.68169
  Epoch 013 - train 0.51843 | val 0.79329
  Classification -> best τ=0.595 (val F1=0.2585)
  Directional -> Accuracy: 0.5217, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.60526 | val 1.46928
  Epoch 012 - train 0.63219 | val 0.90721
  Classification -> best τ=0.365 (val F1=0.2739)
  Directional -> Accuracy: 0.3824, MCC: -0.1405, F1: 0.4878

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.60431 | val 2.26009
  Epoch 011 - train 0.65117 | val 1.55509
  Classification -> best τ=0.530 (val F1=0.1228)
  Directional -> Accuracy: 0.4286, MCC: -0.0323, F1: 0.5862

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.60842 | val 1.82600
  Epoch 014 - train 0.54598 | val 2.76972
  Classification -> best τ=0.675 (val F1=0.4197)
  Directional -> Accuracy: 0.5833, MCC: 0.1193, F1: 0.1667

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.59595 | val 1.39161
  Epoch 011 - train 0.59356 | val 1.03444
  Classification -> best τ=0.450 (val F1=0.2524)
  Directional -> Accuracy: 0.5072, MCC: 0.0670, F1: 0.5405

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.60977 | val 0.77025
  Epoch 012 - train 0.64304 | val 0.68120
  Classification -> best τ=0.385 (val F1=0.3146)
  Directional -> Accuracy: 0.5714, MCC: 0.1016, F1: 0.3226

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.60557 | val 1.20961
  Epoch 013 - train 0.56128 | val 1.23322
  Classification -> best τ=0.370 (val F1=0.1512)
  Directional -> Accuracy: 0.5088, MCC: 0.0033, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.51292 | val 2.76495
  Epoch 011 - train 0.56654 | val 2.19328
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.6230

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.62292 | val 0.80942
  Epoch 020 - train 0.57873 | val 0.78593
  Epoch 026 - train 0.50431 | val 0.87781
  Classification -> best τ=0.325 (val F1=0.4213)
  Directional -> Accuracy: 0.5333, MCC: 0.0754, F1: 0.3913

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.58268 | val 0.71442
  Epoch 020 - train 0.55687 | val 0.76450
  Epoch 027 - train 0.47565 | val 0.77823
  Classification -> best τ=0.375 (val F1=0.3139)
  Directional -> Accuracy: 0.5490, MCC: 0.0487, F1: 0.3030

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.60487 | val 1.01096
  Epoch 011 - train 0.58050 | val 1.39902
  Classification -> best τ=0.340 (val F1=0.2795)
  Directional -> Accuracy: 0.5362, MCC: 0.0263, F1: 0.6735

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.62549 | val 0.76173
  Epoch 011 - train 0.57190 | val 0.83266
  Classification -> best τ=0.535 (val F1=0.2027)
  Directional -> Accuracy: 0.4483, MCC: 0.2128, F1: 0.2000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.59983 | val 0.82053
  Epoch 012 - train 0.56943 | val 0.98181
  Classification -> best τ=0.625 (val F1=0.2758)
  Directional -> Accuracy: 0.4000, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.58820 | val 1.20131
  Epoch 014 - train 0.55773 | val 0.91080
  Classification -> best τ=0.155 (val F1=0.3689)
  Directional -> Accuracy: 0.5938, MCC: 0.1850, F1: 0.6286

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.56514 | val 1.23726
  Epoch 011 - train 0.58319 | val 1.47170
  Classification -> best τ=0.385 (val F1=0.2382)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.61499 | val 1.01744
  Epoch 019 - train 0.48284 | val 1.47094
  Classification -> best τ=0.470 (val F1=0.4877)
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.57610 | val 0.80815
  Epoch 011 - train 0.56204 | val 0.91649
  Classification -> best τ=0.585 (val F1=0.1482)
  Directional -> Accuracy: 0.4923, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.63354 | val 0.70906
  Epoch 020 - train 0.54996 | val 0.75270
  Epoch 024 - train 0.49681 | val 0.85448
  Classification -> best τ=0.820 (val F1=0.4108)
  Directional -> Accuracy: 0.5088, MCC: 0.0286, F1: 0.5172

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.65733 | val 0.74490
  Epoch 014 - train 0.58409 | val 0.83743
  Classification -> best τ=0.500 (val F1=0.1415)
  Directional -> Accuracy: 0.5231, MCC: 0.0000, F1: 0.0000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.61739 | val 0.85083
  Epoch 012 - train 0.58490 | val 1.47912
  Classification -> best τ=0.705 (val F1=0.3953)
  Directional -> Accuracy: 0.5273, MCC: 0.1463, F1: 0.3500

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.61063 | val 3.70105
  Epoch 011 - train 0.54576 | val 4.16753
  Classification -> best τ=0.650 (val F1=0.1890)
  Directional -> Accuracy: 0.5333, MCC: -0.0706, F1: 0.1600

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.60806 | val 1.28634
  Epoch 017 - train 0.62643 | val 0.76432
  Classification -> best τ=0.560 (val F1=0.2161)
  Directional -> Accuracy: 0.5952, MCC: 0.1925, F1: 0.6222

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.55583 | val 1.04332
  Epoch 012 - train 0.56369 | val 1.15596
  Classification -> best τ=0.415 (val F1=0.1508)
  Directional -> Accuracy: 0.4464, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.54662 | val 0.70439
  Epoch 020 - train 0.47825 | val 0.72949
  Epoch 021 - train 0.45286 | val 0.75323
  Classification -> best τ=0.545 (val F1=0.2509)
  Directional -> Accuracy: 0.5500, MCC: 0.0580, F1: 0.6538

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.66961 | val 0.91664
  Epoch 013 - train 0.58058 | val 1.18686
  Classification -> best τ=0.520 (val F1=0.3398)
  Directional -> Accuracy: 0.4762, MCC: -0.0674, F1: 0.3529

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.65678 | val 1.62460
  Epoch 011 - train 0.66461 | val 1.51171
  Classification -> best τ=0.575 (val F1=0.0128)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.57271 | val 0.98316
  Epoch 012 - train 0.55244 | val 1.04038
  Classification -> best τ=0.330 (val F1=0.2932)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.60939 | val 0.86716
  Epoch 016 - train 0.55101 | val 0.99523
  Classification -> best τ=0.510 (val F1=0.3323)
  Directional -> Accuracy: 0.5556, MCC: 0.0000, F1: 0.7143

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.61784 | val 0.79551
  Epoch 011 - train 0.52757 | val 0.83415
  Classification -> best τ=0.440 (val F1=0.1874)
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.61341 | val 1.30301
  Epoch 011 - train 0.63838 | val 1.08699
  Classification -> best τ=0.230 (val F1=0.3787)
  Directional -> Accuracy: 0.5455, MCC: 0.1165, F1: 0.5455

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.53545 | val 1.51500
  Epoch 011 - train 0.42962 | val 2.20969
  Classification -> best τ=0.430 (val F1=0.2409)
  Directional -> Accuracy: 0.6667, MCC: 0.3364, F1: 0.6667

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.60855 | val 1.18049
  Epoch 011 - train 0.54822 | val 1.23668
  Classification -> best τ=0.480 (val F1=0.1951)
  Directional -> Accuracy: 0.4821, MCC: -0.0333, F1: 0.4727

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.58752 | val 1.01294
  Epoch 011 - train 0.49861 | val 1.21905
  Classification -> best τ=0.475 (val F1=0.2800)
  Directional -> Accuracy: 0.6087, MCC: 0.0000, F1: 0.7568

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.56100 | val 0.84678
  Epoch 015 - train 0.59682 | val 0.93461
  Classification -> best τ=0.840 (val F1=0.4710)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.57618 | val 1.84157
  Epoch 011 - train 0.57937 | val 2.35947
  Classification -> best τ=0.315 (val F1=0.3263)
  Directional -> Accuracy: 0.4459, MCC: -0.1329, F1: 0.2807

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.63360 | val 0.72035
  Epoch 011 - train 0.62725 | val 0.79216
  Classification -> best τ=0.470 (val F1=0.4080)
  Directional -> Accuracy: 0.5111, MCC: 0.0000, F1: 0.6765

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.49059 | val 2.42299
  Epoch 011 - train 0.48888 | val 2.20946
  Classification -> best τ=0.550 (val F1=0.5000)
  Directional -> Accuracy: 0.5952, MCC: 0.1803, F1: 0.7385

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.61831 | val 0.54266
  Epoch 020 - train 0.45487 | val 1.57604
  Classification -> best τ=0.545 (val F1=0.6290)
  Directional -> Accuracy: 0.5000, MCC: 0.1491, F1: 0.5556

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.67848 | val 0.85463
  Epoch 012 - train 0.63016 | val 1.96417
  Classification -> best τ=0.490 (val F1=0.1210)
  Directional -> Accuracy: 0.4364, MCC: -0.2410, F1: 0.5867

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.52758 | val 2.21664
  Epoch 011 - train 0.53011 | val 1.70682
  Classification -> best τ=0.420 (val F1=0.2137)
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.6506

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.68521 | val 0.81098
  Epoch 020 - train 0.57140 | val 0.82590
  Epoch 028 - train 0.50696 | val 0.76352
  Classification -> best τ=0.335 (val F1=0.2521)
  Directional -> Accuracy: 0.5849, MCC: 0.2020, F1: 0.6857

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.56892 | val 2.85453
  Epoch 011 - train 0.59712 | val 4.20849
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5273, MCC: 0.0000, F1: 0.6905

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.63440 | val 0.76754

[I 2026-02-22 12:34:21,909] Trial 173 finished with value: 0.2702273089815695 and parameters: {'feature_set': 'sector', 'model_type': 'BiGRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.6000000000000001, 'batch_size': 16, 'learning_rate': 0.006065956311903508, 'weight_decay': 9.560223968600446e-06, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 1.2846505682736395, 'early_stopping_min_delta': 0.00045451211652669694}. Best is trial 159 with value: 0.297766251520741.

  Epoch 013 - train 0.61728 | val 1.30505
  Classification -> best τ=0.540 (val F1=0.3496)
  Directional -> Accuracy: 0.4000, MCC: -0.2282, F1: 0.2500

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2702273089815695
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.63005 | val 0.95280
  Epoch 011 - train 0.61525 | val 0.94058
  Classification -> best τ=0.580 (val F1=0.2203)
  Directional -> Accuracy: 0.5658, MCC: 0.1148, F1: 0.4923

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.58104 | val 0.95620
  Epoch 011 - train 0.56114 | val 1.00711
  Classification -> best τ=0.490 (val F1=0.0950)
  Directional -> Accuracy: 0.5778, MCC: 0.0000, F1: 0.7324

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.62234 | val 0.81276
  Epoch 012 - train 0.63755 | val 0.84743
  Classification -> best τ=0.540 (val F1=0.2275)
  Directional -> Accuracy: 0.7609, MCC: 0.5226, F1: 0.7843

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.63683 | val 1.04899
  Epoch 011 - train 0.61211 | val 1.09394
  Classification -> best τ=0.430 (val F1=0.1269)
  Directional -> Accuracy: 0.5405, MCC: 0.0000, F1: 0.7018

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.62006 | val 0.80594
  Epoch 013 - train 0.58152 | val 0.93103
  Classification -> best τ=0.570 (val F1=0.4139)
  Directional -> Accuracy: 0.6000, MCC: 0.2300, F1: 0.5238

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.59693 | val 1.06869
  Epoch 012 - train 0.58351 | val 1.14562
  Classification -> best τ=0.565 (val F1=0.2463)
  Directional -> Accuracy: 0.5217, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.65340 | val 1.06982
  Epoch 011 - train 0.63810 | val 1.13568
  Classification -> best τ=0.445 (val F1=0.3074)
  Directional -> Accuracy: 0.5147, MCC: 0.2180, F1: 0.6024

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.59949 | val 0.86596
  Epoch 011 - train 0.57984 | val 0.91514
  Classification -> best τ=0.520 (val F1=0.1657)
  Directional -> Accuracy: 0.4524, MCC: -0.0446, F1: 0.5106

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.62504 | val 1.18765
  Epoch 011 - train 0.60593 | val 1.28364
  Classification -> best τ=0.540 (val F1=0.2771)
  Directional -> Accuracy: 0.6250, MCC: 0.2219, F1: 0.4000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.60412 | val 1.29290
  Epoch 011 - train 0.60644 | val 1.38660
  Classification -> best τ=0.465 (val F1=0.1922)
  Directional -> Accuracy: 0.4783, MCC: -0.0044, F1: 0.5000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.64379 | val 0.79149
  Epoch 011 - train 0.61162 | val 0.80029
  Classification -> best τ=0.565 (val F1=0.2021)
  Directional -> Accuracy: 0.5306, MCC: 0.0152, F1: 0.3429

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.66104 | val 0.79616
  Epoch 011 - train 0.64861 | val 0.85063
  Classification -> best τ=0.465 (val F1=0.2258)
  Directional -> Accuracy: 0.5439, MCC: 0.0891, F1: 0.6286

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.57348 | val 1.65323
  Epoch 011 - train 0.56795 | val 1.72115
  Classification -> best τ=0.430 (val F1=0.2636)
  Directional -> Accuracy: 0.5952, MCC: 0.2205, F1: 0.6222

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.63344 | val 0.68152
  Epoch 013 - train 0.61566 | val 0.70445
  Classification -> best τ=0.530 (val F1=0.2531)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.60411 | val 0.91149
  Epoch 011 - train 0.61995 | val 0.83608
  Classification -> best τ=0.560 (val F1=0.1347)
  Directional -> Accuracy: 0.5098, MCC: 0.0062, F1: 0.4444

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.59918 | val 0.82960
  Epoch 012 - train 0.61958 | val 0.85149
  Classification -> best τ=0.340 (val F1=0.2795)
  Directional -> Accuracy: 0.5507, MCC: 0.1304, F1: 0.7048

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.64196 | val 1.13551
  Epoch 011 - train 0.60592 | val 1.31519
  Classification -> best τ=0.585 (val F1=0.1510)
  Directional -> Accuracy: 0.3793, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.60587 | val 0.99145
  Epoch 011 - train 0.62381 | val 1.12086
  Classification -> best τ=0.455 (val F1=0.1348)
  Directional -> Accuracy: 0.6000, MCC: 0.0000, F1: 0.7500

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.63337 | val 0.75857
  Epoch 011 - train 0.62829 | val 0.78083
  Classification -> best τ=0.445 (val F1=0.2522)
  Directional -> Accuracy: 0.5781, MCC: 0.0408, F1: 0.7216

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.58783 | val 1.15850
  Epoch 011 - train 0.60285 | val 1.17601
  Classification -> best τ=0.460 (val F1=0.3161)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.64920 | val 0.77111
  Epoch 013 - train 0.57530 | val 0.86210
  Classification -> best τ=0.395 (val F1=0.2784)
  Directional -> Accuracy: 0.6170, MCC: 0.0000, F1: 0.7632

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.64341 | val 0.81900
  Epoch 012 - train 0.63223 | val 0.80800
  Classification -> best τ=0.585 (val F1=0.2168)
  Directional -> Accuracy: 0.4923, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.67904 | val 0.65059
  Epoch 019 - train 0.61581 | val 0.73642
  Classification -> best τ=0.575 (val F1=0.4735)
  Directional -> Accuracy: 0.5614, MCC: 0.1750, F1: 0.5098

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.67204 | val 1.15859
  Epoch 011 - train 0.62420 | val 1.41683
  Classification -> best τ=0.460 (val F1=0.2111)
  Directional -> Accuracy: 0.4769, MCC: 0.0000, F1: 0.6458

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.59264 | val 0.89382
  Epoch 012 - train 0.59939 | val 0.96515
  Classification -> best τ=0.525 (val F1=0.4051)
  Directional -> Accuracy: 0.5636, MCC: 0.1827, F1: 0.4783

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.61605 | val 1.08483
  Epoch 013 - train 0.58111 | val 1.19163
  Classification -> best τ=0.495 (val F1=0.4328)
  Directional -> Accuracy: 0.6000, MCC: 0.2590, F1: 0.6250

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.64057 | val 1.14045
  Epoch 011 - train 0.65396 | val 1.21110
  Classification -> best τ=0.425 (val F1=0.2161)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.2581

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.61524 | val 0.80720
  Epoch 012 - train 0.59593 | val 0.85596
  Classification -> best τ=0.450 (val F1=0.2305)
  Directional -> Accuracy: 0.4464, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.60009 | val 0.68270
  Epoch 020 - train 0.50683 | val 0.70954
  Epoch 027 - train 0.49225 | val 1.08470
  Classification -> best τ=0.455 (val F1=0.4139)
  Directional -> Accuracy: 0.6000, MCC: 0.2010, F1: 0.7241

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.59622 | val 0.80634
  Epoch 012 - train 0.65365 | val 0.88340
  Classification -> best τ=0.515 (val F1=0.3501)
  Directional -> Accuracy: 0.5000, MCC: -0.0142, F1: 0.4000

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.64900 | val 1.06025
  Epoch 011 - train 0.67293 | val 1.09977
  Classification -> best τ=0.490 (val F1=0.1846)
  Directional -> Accuracy: 0.5238, MCC: 0.0123, F1: 0.6154

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.60655 | val 0.72852
  Epoch 014 - train 0.63830 | val 0.84738
  Classification -> best τ=0.450 (val F1=0.2716)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.64946 | val 0.85213
  Epoch 011 - train 0.64376 | val 0.83637
  Classification -> best τ=0.510 (val F1=0.1290)
  Directional -> Accuracy: 0.4444, MCC: 0.0000, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.63020 | val 0.84445
  Epoch 011 - train 0.58224 | val 0.84245
  Classification -> best τ=0.485 (val F1=0.2603)
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.61972 | val 0.71462
  Epoch 019 - train 0.54429 | val 0.79592
  Classification -> best τ=0.275 (val F1=0.4339)
  Directional -> Accuracy: 0.6364, MCC: 0.2911, F1: 0.6471

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.61252 | val 1.06996
  Epoch 012 - train 0.59995 | val 1.19882
  Classification -> best τ=0.475 (val F1=0.2228)
  Directional -> Accuracy: 0.5714, MCC: 0.1589, F1: 0.5263

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.56738 | val 0.85152
  Epoch 013 - train 0.54620 | val 1.02836
  Classification -> best τ=0.530 (val F1=0.1951)
  Directional -> Accuracy: 0.5179, MCC: 0.0494, F1: 0.5424

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.58975 | val 0.87595
  Epoch 011 - train 0.56708 | val 0.94147
  Classification -> best τ=0.440 (val F1=0.2118)
  Directional -> Accuracy: 0.6087, MCC: 0.0000, F1: 0.7568

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.60263 | val 0.65427
  Epoch 020 - train 0.54439 | val 0.70980
  Epoch 023 - train 0.51186 | val 0.64132
  Classification -> best τ=0.815 (val F1=0.4306)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.60531 | val 1.13896
  Epoch 011 - train 0.57346 | val 1.19318
  Classification -> best τ=0.435 (val F1=0.3509)
  Directional -> Accuracy: 0.5135, MCC: 0.0107, F1: 0.2174

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.63971 | val 0.72096
  Epoch 011 - train 0.60063 | val 0.73541
  Classification -> best τ=0.510 (val F1=0.0905)
  Directional -> Accuracy: 0.4222, MCC: -0.2020, F1: 0.5517

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.60270 | val 0.90628
  Epoch 011 - train 0.64007 | val 0.92005
  Classification -> best τ=0.480 (val F1=0.1667)
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.7273

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.59603 | val 0.76186
  Epoch 011 - train 0.59520 | val 0.74029
  Classification -> best τ=0.480 (val F1=0.1371)
  Directional -> Accuracy: 0.3750, MCC: -0.0778, F1: 0.5161

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.64272 | val 0.84183
  Epoch 012 - train 0.65208 | val 0.87180
  Classification -> best τ=0.610 (val F1=0.1647)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.59614 | val 1.87526
  Epoch 011 - train 0.57975 | val 2.04765
  Classification -> best τ=0.610 (val F1=0.2914)
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.6506

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.67656 | val 0.75761
  Epoch 011 - train 0.67097 | val 0.79486
  Classification -> best τ=0.480 (val F1=0.1691)
  Directional -> Accuracy: 0.4340, MCC: -0.1343, F1: 0.3182

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.60536 | val 2.89706
  Epoch 011 - train 0.56800 | val 2.73774
  Classification -> best τ=0.505 (val F1=0.2859)
  Directional -> Accuracy: 0.5636, MCC: 0.2052, F1: 0.7073

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.63557 | val 0.73295

[I 2026-02-22 12:36:47,171] Trial 174 finished with value: 0.24722628223009613 and parameters: {'feature_set': 'sector', 'model_type': 'BiGRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.6000000000000001, 'batch_size': 16, 'learning_rate': 0.0005528071187076557, 'weight_decay': 4.357383168301536e-07, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 1.2342686058488148, 'early_stopping_min_delta': 0.00028972847255180525}. Best is trial 159 with value: 0.297766251520741.

  Epoch 011 - train 0.63755 | val 0.78566
  Classification -> best τ=0.515 (val F1=0.1572)
  Directional -> Accuracy: 0.5167, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.24722628223009613
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'positive_emotion', 'negative_emotion', 'uncertainty_emotion', 'positive_emotion_pct', 'negative_emotion_pct', 'uncertainty_emotion_pct']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.63352 | val 0.77377
  Epoch 016 - train 0.57629 | val 0.77693
  Classification -> best τ=0.510 (val F1=0.3286)
  Directional -> Accuracy: 0.5526, MCC: 0.0855, F1: 0.4688

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.53728 | val 1.28186
  Epoch 011 - train 0.50158 | val 1.66416
  Classification -> best τ=0.365 (val F1=0.0706)
  Directional -> Accuracy: 0.5778, MCC: 0.0000, F1: 0.7324

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.60456 | val 0.84154
  Epoch 012 - train 0.53682 | val 0.96045
  Classification -> best τ=0.705 (val F1=0.3894)
  Directional -> Accuracy: 0.4783, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.61874 | val 1.56360
  Epoch 011 - train 0.64030 | val 1.13037
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5405, MCC: 0.0000, F1: 0.7018

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.54564 | val 0.69074
  Epoch 012 - train 0.67033 | val 1.26970
  Classification -> best τ=0.635 (val F1=0.4611)
  Directional -> Accuracy: 0.6000, MCC: 0.2802, F1: 0.4444

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.49761 | val 0.93161
  Epoch 011 - train 0.58318 | val 1.20192
  Classification -> best τ=0.570 (val F1=0.1463)
  Directional -> Accuracy: 0.5217, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.58859 | val 1.03352
  Epoch 011 - train 0.58115 | val 1.36571
  Classification -> best τ=0.535 (val F1=0.2870)
  Directional -> Accuracy: 0.5294, MCC: 0.0539, F1: 0.4667

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.57038 | val 1.07856
  Epoch 011 - train 0.62710 | val 1.61527
  Classification -> best τ=0.505 (val F1=0.1147)
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.55512 | val 1.11381
  Epoch 011 - train 0.59998 | val 1.22874
  Classification -> best τ=0.595 (val F1=0.2784)
  Directional -> Accuracy: 0.5625, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.56896 | val 0.84613
  Epoch 011 - train 0.52217 | val 1.44036
  Classification -> best τ=0.285 (val F1=0.3079)
  Directional -> Accuracy: 0.4203, MCC: -0.0279, F1: 0.5833

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.60194 | val 1.24913
  Epoch 012 - train 0.56006 | val 1.36437
  Classification -> best τ=0.515 (val F1=0.2484)
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.59683 | val 1.70557
  Epoch 011 - train 0.59480 | val 1.64456
  Classification -> best τ=0.470 (val F1=0.0688)
  Directional -> Accuracy: 0.6316, MCC: 0.2626, F1: 0.6441

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.53309 | val 1.52207
  Epoch 011 - train 0.55573 | val 1.74621
  Classification -> best τ=0.350 (val F1=0.1991)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.6230

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.65287 | val 0.61813
  Epoch 020 - train 0.52408 | val 0.80191
  Classification -> best τ=0.310 (val F1=0.4301)
  Directional -> Accuracy: 0.5500, MCC: 0.2294, F1: 0.6897

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.56103 | val 0.87529
  Epoch 011 - train 0.54529 | val 0.71705
  Classification -> best τ=0.530 (val F1=0.1925)
  Directional -> Accuracy: 0.5490, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.61789 | val 0.87329
  Epoch 011 - train 0.64028 | val 1.06168
  Classification -> best τ=0.500 (val F1=0.1869)
  Directional -> Accuracy: 0.4783, MCC: -0.0490, F1: 0.5135

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.59978 | val 2.94925
  Epoch 011 - train 0.60104 | val 3.19618
  Classification -> best τ=0.505 (val F1=0.0811)
  Directional -> Accuracy: 0.6034, MCC: -0.1035, F1: 0.7527

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.62407 | val 1.37754
  Epoch 011 - train 0.60174 | val 1.29259
  Classification -> best τ=0.525 (val F1=0.1909)
  Directional -> Accuracy: 0.4000, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.59436 | val 0.73180
  Epoch 011 - train 0.57495 | val 0.93214
  Classification -> best τ=0.490 (val F1=0.1578)
  Directional -> Accuracy: 0.5000, MCC: 0.0839, F1: 0.4074

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.58575 | val 0.68643
  Epoch 020 - train 0.49983 | val 1.05304
  Classification -> best τ=0.575 (val F1=0.2403)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.54167 | val 1.29845
  Epoch 011 - train 0.47815 | val 1.02202
  Classification -> best τ=0.485 (val F1=0.2247)
  Directional -> Accuracy: 0.6170, MCC: 0.0000, F1: 0.7632

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.66416 | val 1.02931
  Epoch 011 - train 0.62588 | val 1.04200
  Classification -> best τ=0.570 (val F1=0.3164)
  Directional -> Accuracy: 0.4769, MCC: -0.0480, F1: 0.2273

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.58864 | val 0.73796
  Epoch 011 - train 0.55548 | val 0.72876
  Classification -> best τ=0.525 (val F1=0.2380)
  Directional -> Accuracy: 0.5789, MCC: 0.2830, F1: 0.4545

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.58075 | val 0.99500
  Epoch 012 - train 0.58332 | val 0.79862
  Classification -> best τ=0.590 (val F1=0.2484)
  Directional -> Accuracy: 0.5385, MCC: 0.0923, F1: 0.5833

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.65267 | val 1.07340
  Epoch 012 - train 0.55105 | val 1.45076
  Classification -> best τ=0.605 (val F1=0.3507)
  Directional -> Accuracy: 0.5455, MCC: 0.1641, F1: 0.4186

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.48393 | val 2.44277
  Epoch 011 - train 0.49659 | val 2.30288
  Classification -> best τ=0.460 (val F1=0.2035)
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.5938

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.54683 | val 0.77845
  Epoch 012 - train 0.58957 | val 0.80772
  Classification -> best τ=0.535 (val F1=0.3586)
  Directional -> Accuracy: 0.5714, MCC: 0.0913, F1: 0.6667

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.58034 | val 1.38855
  Epoch 011 - train 0.61396 | val 1.10601
  Classification -> best τ=0.500 (val F1=0.1265)
  Directional -> Accuracy: 0.4286, MCC: -0.1054, F1: 0.0588

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.52835 | val 1.22691
  Epoch 011 - train 0.46455 | val 1.69468
  Classification -> best τ=0.500 (val F1=0.0989)
  Directional -> Accuracy: 0.6000, MCC: 0.1755, F1: 0.6800

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.51016 | val 0.86625
  Epoch 016 - train 0.36593 | val 0.85623
  Classification -> best τ=0.845 (val F1=0.3501)
  Directional -> Accuracy: 0.5000, MCC: -0.0258, F1: 0.3226

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.59259 | val 2.75518
  Epoch 011 - train 0.57524 | val 1.98983
  Classification -> best τ=0.420 (val F1=0.0409)
  Directional -> Accuracy: 0.3810, MCC: -0.2981, F1: 0.5000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.54071 | val 0.97031
  Epoch 011 - train 0.49895 | val 1.15420
  Classification -> best τ=0.500 (val F1=0.2716)
  Directional -> Accuracy: 0.4898, MCC: -0.0704, F1: 0.6154

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.59338 | val 1.39030
  Epoch 015 - train 0.53328 | val 2.31519
  Classification -> best τ=0.325 (val F1=0.3131)
  Directional -> Accuracy: 0.5278, MCC: 0.1079, F1: 0.4516

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.61464 | val 2.83439
  Epoch 011 - train 0.51264 | val 2.18514
  Classification -> best τ=0.410 (val F1=0.3417)
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.57833 | val 1.26071
  Epoch 011 - train 0.56267 | val 1.12072
  Classification -> best τ=0.380 (val F1=0.3603)
  Directional -> Accuracy: 0.5758, MCC: 0.0795, F1: 0.6889

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.51075 | val 1.57277
  Epoch 012 - train 0.54804 | val 1.97509
  Classification -> best τ=0.415 (val F1=0.3001)
  Directional -> Accuracy: 0.6905, MCC: 0.4321, F1: 0.6286

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.54780 | val 1.51908
  Epoch 011 - train 0.62011 | val 0.97696
  Classification -> best τ=0.580 (val F1=0.2850)
  Directional -> Accuracy: 0.5893, MCC: 0.1646, F1: 0.4390

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.44087 | val 1.51198
  Epoch 011 - train 0.50529 | val 1.17584
  Classification -> best τ=0.500 (val F1=0.2474)
  Directional -> Accuracy: 0.6087, MCC: 0.0475, F1: 0.7500

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.50310 | val 1.39362
  Epoch 012 - train 0.46858 | val 1.28212
  Classification -> best τ=0.620 (val F1=0.4710)
  Directional -> Accuracy: 0.3750, MCC: 0.0112, F1: 0.5161

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.61045 | val 0.99785
  Epoch 011 - train 0.54842 | val 1.17319
  Classification -> best τ=0.460 (val F1=0.3321)
  Directional -> Accuracy: 0.4865, MCC: 0.0000, F1: 0.6545

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.58721 | val 0.96727
  Epoch 012 - train 0.50289 | val 1.20243
  Classification -> best τ=0.455 (val F1=0.3371)
  Directional -> Accuracy: 0.4889, MCC: -0.0217, F1: 0.4889

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.49368 | val 1.14804
  Epoch 011 - train 0.36993 | val 1.28739
  Classification -> best τ=0.565 (val F1=0.2500)
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.0000

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.46705 | val 0.87635
  Epoch 011 - train 0.41373 | val 0.77152
  Classification -> best τ=0.440 (val F1=0.2605)
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.5455

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.65921 | val 1.26499
  Epoch 011 - train 0.61032 | val 0.77576
  Classification -> best τ=0.420 (val F1=0.1166)
  Directional -> Accuracy: 0.4727, MCC: -0.1695, F1: 0.6234

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.54003 | val 1.44765
  Epoch 011 - train 0.54319 | val 2.08807
  Classification -> best τ=0.470 (val F1=0.2137)
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.6506

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.66424 | val 0.93189
  Epoch 011 - train 0.58949 | val 0.96182
  Classification -> best τ=0.400 (val F1=0.2762)
  Directional -> Accuracy: 0.5094, MCC: 0.0000, F1: 0.6750

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.56804 | val 2.65084
  Epoch 011 - train 0.49819 | val 2.15427
  Classification -> best τ=0.840 (val F1=0.2291)
  Directional -> Accuracy: 0.4727, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.61965 | val 0.81971

[I 2026-02-22 12:39:10,965] Trial 175 finished with value: 0.245469400143396 and parameters: {'feature_set': 'unified_emotion', 'model_type': 'BiGRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.6000000000000001, 'batch_size': 16, 'learning_rate': 0.0040086646243568174, 'weight_decay': 1.1493968591108115e-05, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 1.2122971846308184, 'early_stopping_min_delta': 0.0025928741587143496}. Best is trial 159 with value: 0.297766251520741.

  Epoch 019 - train 0.41091 | val 0.90203
  Classification -> best τ=0.290 (val F1=0.2405)
  Directional -> Accuracy: 0.5167, MCC: 0.1248, F1: 0.6588

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.245469400143396
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sentiment', 'emotion_anger', 'emotion_disgust', 'emotion_fear', 'emotion_joy', 'emotion_neutral', 'emotion_sadness', 'emotion_surprize', 'emotion_anger_pct', 'emotion_disgust_pct', 'emotion_fear_pct', 'emotion_joy_pct', 'emotion_neutral_pct', 'emotion_sadness_pct', 'emotion_surprize_pct', 'positive_emotion', 'negative_emotion', 'uncertainty_emotion', 'positive_emotion_pct', 'negative_emotion_pct', 'uncertainty_emotion_pct', 'stance_label', 'stance_score', 'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down', 'finbert_neutral']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.52162 | val 1.05935
  Epoch 011 - train 0.51284 | val 0.98232
  Classification -> best τ=0.435 (val F1=0.2143)
  Directional -> Accuracy: 0.4605, MCC: 0.0022, F1: 0.5941

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.35720 | val 2.41221
  Epoch 011 - train 0.47213 | val 2.11675
  Classification -> best τ=0.550 (val F1=0.2590)
  Directional -> Accuracy: 0.6222, MCC: 0.1967, F1: 0.7119

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.51664 | val 1.37374
  Epoch 012 - train 0.30133 | val 1.51572
  Classification -> best τ=0.400 (val F1=0.3732)
  Directional -> Accuracy: 0.4565, MCC: -0.1090, F1: 0.5455

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.54644 | val 1.95069
  Epoch 011 - train 0.43225 | val 5.51519
  Classification -> best τ=0.365 (val F1=0.2067)
  Directional -> Accuracy: 0.4730, MCC: 0.0520, F1: 0.0930

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.28069 | val 1.81485
  Epoch 011 - train 0.30675 | val 3.12617
  Classification -> best τ=0.475 (val F1=0.3440)
  Directional -> Accuracy: 0.5800, MCC: 0.1748, F1: 0.5333

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.29250 | val 1.33447
  Epoch 011 - train 0.28185 | val 1.25476
  Classification -> best τ=0.495 (val F1=0.3222)
  Directional -> Accuracy: 0.4783, MCC: -0.0134, F1: 0.6250

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.46971 | val 1.59724
  Epoch 011 - train 0.34677 | val 2.10478
  Classification -> best τ=0.595 (val F1=0.1863)
  Directional -> Accuracy: 0.6324, MCC: 0.1714, F1: 0.2424

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.28510 | val 3.78215
  Epoch 011 - train 0.26438 | val 4.70848
  Classification -> best τ=0.570 (val F1=0.4215)
  Directional -> Accuracy: 0.4286, MCC: -0.2282, F1: 0.2000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.36021 | val 3.04800
  Epoch 011 - train 0.32025 | val 2.39427
  Classification -> best τ=0.640 (val F1=0.2838)
  Directional -> Accuracy: 0.6250, MCC: 0.3018, F1: 0.6538

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.35366 | val 1.25756
  Epoch 012 - train 0.39482 | val 1.13260
  Classification -> best τ=0.475 (val F1=0.4403)
  Directional -> Accuracy: 0.5217, MCC: 0.0707, F1: 0.5217

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.42105 | val 1.68278
  Epoch 011 - train 0.36245 | val 1.87304
  Classification -> best τ=0.640 (val F1=0.2074)
  Directional -> Accuracy: 0.6122, MCC: 0.2027, F1: 0.4242

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.47029 | val 0.92240
  Epoch 011 - train 0.41264 | val 1.81881
  Classification -> best τ=0.590 (val F1=0.1685)
  Directional -> Accuracy: 0.5088, MCC: 0.1313, F1: 0.0667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.41983 | val 2.02309
  Epoch 011 - train 0.24131 | val 3.86238
  Classification -> best τ=0.335 (val F1=0.1991)
  Directional -> Accuracy: 0.4524, MCC: -0.0214, F1: 0.6102

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.44629 | val 1.56453
  Epoch 013 - train 0.40188 | val 1.33614
  Classification -> best τ=0.375 (val F1=0.2516)
  Directional -> Accuracy: 0.4833, MCC: -0.0519, F1: 0.6265

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.46830 | val 1.31257
  Epoch 011 - train 0.39632 | val 1.46335
  Classification -> best τ=0.460 (val F1=0.2008)
  Directional -> Accuracy: 0.4118, MCC: -0.1479, F1: 0.5312

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.42678 | val 1.93915
  Epoch 015 - train 0.44938 | val 1.03711
  Classification -> best τ=0.450 (val F1=0.3335)
  Directional -> Accuracy: 0.5942, MCC: 0.1745, F1: 0.6744

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.47307 | val 1.51720
  Epoch 011 - train 0.44571 | val 2.01179
  Classification -> best τ=0.530 (val F1=0.1521)
  Directional -> Accuracy: 0.3621, MCC: -0.3432, F1: 0.4789

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.47977 | val 1.11156
  Epoch 012 - train 0.48413 | val 1.79246
  Classification -> best τ=0.515 (val F1=0.1769)
  Directional -> Accuracy: 0.6000, MCC: 0.0000, F1: 0.7500

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.36028 | val 1.44133
  Epoch 012 - train 0.41854 | val 2.06906
  Classification -> best τ=0.610 (val F1=0.1578)
  Directional -> Accuracy: 0.4219, MCC: -0.0284, F1: 0.0513

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.46518 | val 0.83913
  Epoch 015 - train 0.30981 | val 1.68725
  Classification -> best τ=0.280 (val F1=0.1947)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.43390 | val 1.32642
  Epoch 011 - train 0.41434 | val 1.23162
  Classification -> best τ=0.470 (val F1=0.2416)
  Directional -> Accuracy: 0.5957, MCC: 0.0814, F1: 0.7077

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.43403 | val 1.46403
  Epoch 012 - train 0.44223 | val 1.69681
  Classification -> best τ=0.495 (val F1=0.2794)
  Directional -> Accuracy: 0.5538, MCC: 0.1231, F1: 0.4528

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.45824 | val 1.72218
  Epoch 016 - train 0.26517 | val 2.17553
  Classification -> best τ=0.595 (val F1=0.3457)
  Directional -> Accuracy: 0.4737, MCC: 0.0359, F1: 0.2857

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.38022 | val 0.85719
  Epoch 011 - train 0.52907 | val 0.84042
  Classification -> best τ=0.560 (val F1=0.1393)
  Directional -> Accuracy: 0.5231, MCC: 0.0000, F1: 0.0000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.41720 | val 1.65340
  Epoch 011 - train 0.39184 | val 1.75989
  Classification -> best τ=0.475 (val F1=0.3470)
  Directional -> Accuracy: 0.4909, MCC: 0.0069, F1: 0.4400

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.30700 | val 5.66451
  Epoch 011 - train 0.17520 | val 5.44623
  Classification -> best τ=0.480 (val F1=0.0105)
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.5938

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.26551 | val 1.65582
  Epoch 011 - train 0.23811 | val 2.32057
  Classification -> best τ=0.515 (val F1=0.2759)
  Directional -> Accuracy: 0.5476, MCC: -0.0212, F1: 0.6885

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.41445 | val 1.70679
  Epoch 011 - train 0.41589 | val 2.16856
  Classification -> best τ=0.370 (val F1=0.2315)
  Directional -> Accuracy: 0.5536, MCC: 0.1340, F1: 0.5283

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.23302 | val 4.18734
  Epoch 011 - train 0.31318 | val 4.40541
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5500, MCC: 0.0000, F1: 0.7097

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.28796 | val 2.86841
  Epoch 011 - train 0.24159 | val 4.24018
  Classification -> best τ=0.845 (val F1=0.1959)
  Directional -> Accuracy: 0.5238, MCC: 0.0000, F1: 0.0000

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.31332 | val 1.10941
  Epoch 011 - train 0.32606 | val 1.05493
  Classification -> best τ=0.490 (val F1=0.1161)
  Directional -> Accuracy: 0.4524, MCC: -0.0310, F1: 0.1481

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.41676 | val 1.77460
  Epoch 012 - train 0.29737 | val 2.40627
  Classification -> best τ=0.315 (val F1=0.2932)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.40112 | val 1.14587
  Epoch 013 - train 0.41010 | val 0.89867
  Classification -> best τ=0.515 (val F1=0.3548)
  Directional -> Accuracy: 0.5000, MCC: 0.0747, F1: 0.3571

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.28411 | val 2.62241
  Epoch 011 - train 0.30831 | val 2.27143
  Classification -> best τ=0.355 (val F1=0.1309)
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.46748 | val 2.07710
  Epoch 011 - train 0.44572 | val 1.86354
  Classification -> best τ=0.415 (val F1=0.2858)
  Directional -> Accuracy: 0.4848, MCC: 0.2180, F1: 0.1905

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.19793 | val 1.58275
  Epoch 012 - train 0.22074 | val 2.61459
  Classification -> best τ=0.505 (val F1=0.3941)
  Directional -> Accuracy: 0.5476, MCC: 0.1706, F1: 0.3448

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.36032 | val 2.29789
  Epoch 011 - train 0.42285 | val 2.44426
  Classification -> best τ=0.465 (val F1=0.2450)
  Directional -> Accuracy: 0.4643, MCC: -0.0493, F1: 0.5312

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.33574 | val 0.91759
  Epoch 013 - train 0.20110 | val 1.28037
  Classification -> best τ=0.465 (val F1=0.4454)
  Directional -> Accuracy: 0.4130, MCC: -0.0903, F1: 0.3415

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.32994 | val 1.23719
  Epoch 012 - train 0.11604 | val 2.16875
  Classification -> best τ=0.535 (val F1=0.4688)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.48819 | val 2.61202
  Epoch 011 - train 0.50041 | val 2.20686
  Classification -> best τ=0.220 (val F1=0.2112)
  Directional -> Accuracy: 0.4865, MCC: 0.0000, F1: 0.6545

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.39466 | val 1.40754
  Epoch 011 - train 0.43332 | val 1.80198
  Classification -> best τ=0.475 (val F1=0.2169)
  Directional -> Accuracy: 0.5111, MCC: 0.0000, F1: 0.6765

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.33957 | val 1.67487
  Epoch 011 - train 0.29882 | val 2.10388
  Classification -> best τ=0.550 (val F1=0.0602)
  Directional -> Accuracy: 0.5000, MCC: 0.1291, F1: 0.3226

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.16190 | val 0.81489
  Epoch 011 - train 0.28771 | val 1.12794
  Classification -> best τ=0.380 (val F1=0.2300)
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.5455

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.46916 | val 1.95945
  Epoch 011 - train 0.44084 | val 1.20065
  Classification -> best τ=0.480 (val F1=0.2121)
  Directional -> Accuracy: 0.3455, MCC: -0.2971, F1: 0.2500

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.34162 | val 4.04411
  Epoch 011 - train 0.23140 | val 3.53395
  Classification -> best τ=0.645 (val F1=0.3088)
  Directional -> Accuracy: 0.4643, MCC: -0.1486, F1: 0.1176

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.44129 | val 1.43437
  Epoch 011 - train 0.39212 | val 1.40724
  Classification -> best τ=0.570 (val F1=0.1409)
  Directional -> Accuracy: 0.5660, MCC: 0.1520, F1: 0.4651

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.51498 | val 4.56627
  Epoch 011 - train 0.45511 | val 2.73093
  Classification -> best τ=0.650 (val F1=0.2859)
  Directional -> Accuracy: 0.5818, MCC: 0.1718, F1: 0.6933

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.47594 | val 0.79033

[I 2026-02-22 12:41:34,723] Trial 176 finished with value: 0.2469318376104539 and parameters: {'feature_set': 'all_nlp', 'model_type': 'BiGRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.6000000000000001, 'batch_size': 16, 'learning_rate': 0.005605105077100054, 'weight_decay': 9.687685224315235e-06, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 1.1716716199585195, 'early_stopping_min_delta': 0.00021663030913724276}. Best is trial 159 with value: 0.297766251520741.

  Epoch 017 - train 0.44407 | val 0.95143
  Classification -> best τ=0.590 (val F1=0.2920)
  Directional -> Accuracy: 0.5333, MCC: 0.0589, F1: 0.3000

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2469318376104539
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.64251 | val 0.70907
  Epoch 011 - train 0.65386 | val 0.82248
  Classification -> best τ=0.570 (val F1=0.2036)
  Directional -> Accuracy: 0.5658, MCC: 0.0795, F1: 0.1951

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.55676 | val 0.70847
  Epoch 020 - train 0.53711 | val 0.92563
  Epoch 022 - train 0.45859 | val 1.03481
  Classification -> best τ=0.370 (val F1=0.3463)
  Directional -> Accuracy: 0.5556, MCC: -0.1289, F1: 0.7143

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.67437 | val 0.73954
  Epoch 013 - train 0.63810 | val 0.81266
  Classification -> best τ=0.520 (val F1=0.3005)
  Directional -> Accuracy: 0.4130, MCC: -0.1686, F1: 0.3415

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.63808 | val 1.33718
  Epoch 011 - train 0.65829 | val 1.76686
  Classification -> best τ=0.470 (val F1=0.2470)
  Directional -> Accuracy: 0.5811, MCC: 0.1414, F1: 0.6667

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.60974 | val 0.61807
  Epoch 020 - train 0.42468 | val 0.90214
  Classification -> best τ=0.655 (val F1=0.4930)
  Directional -> Accuracy: 0.6600, MCC: 0.3398, F1: 0.6222

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.59457 | val 0.69233
  Epoch 020 - train 0.50077 | val 0.67395
  Epoch 030 - train 0.32913 | val 0.68500
  Classification -> best τ=0.465 (val F1=0.4039)
  Directional -> Accuracy: 0.3913, MCC: -0.2423, F1: 0.2632

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.66269 | val 0.70815
  Epoch 019 - train 0.60772 | val 0.77286
  Classification -> best τ=0.535 (val F1=0.3010)
  Directional -> Accuracy: 0.4559, MCC: -0.1027, F1: 0.3729

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.61040 | val 1.15277
  Epoch 011 - train 0.56332 | val 1.37557
  Classification -> best τ=0.510 (val F1=0.0679)
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.61971 | val 1.78809
  Epoch 011 - train 0.65663 | val 2.00375
  Classification -> best τ=0.550 (val F1=0.2443)
  Directional -> Accuracy: 0.5417, MCC: 0.1005, F1: 0.5417

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.64652 | val 0.72922
  Epoch 011 - train 0.64676 | val 0.87081
  Classification -> best τ=0.490 (val F1=0.2620)
  Directional -> Accuracy: 0.4783, MCC: 0.0155, F1: 0.5263

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.68095 | val 0.67460
  Epoch 016 - train 0.61986 | val 0.70460
  Classification -> best τ=0.560 (val F1=0.3075)
  Directional -> Accuracy: 0.5918, MCC: 0.1804, F1: 0.2308

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.65745 | val 1.26621
  Epoch 011 - train 0.66051 | val 1.68899
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5088, MCC: 0.0000, F1: 0.6744

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.54834 | val 1.83011
  Epoch 011 - train 0.54171 | val 1.39153
  Classification -> best τ=0.475 (val F1=0.2466)
  Directional -> Accuracy: 0.5000, MCC: 0.0976, F1: 0.6182

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.63039 | val 0.66053
  Epoch 013 - train 0.61830 | val 0.65592
  Classification -> best τ=0.450 (val F1=0.4160)
  Directional -> Accuracy: 0.5333, MCC: 0.0754, F1: 0.3913

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.61154 | val 0.70936
  Epoch 020 - train 0.55956 | val 0.74508
  Epoch 022 - train 0.54965 | val 0.85334
  Classification -> best τ=0.485 (val F1=0.2078)
  Directional -> Accuracy: 0.5098, MCC: -0.1831, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.62770 | val 0.83915
  Epoch 011 - train 0.56348 | val 0.92612
  Classification -> best τ=0.465 (val F1=0.1741)
  Directional -> Accuracy: 0.5362, MCC: 0.0000, F1: 0.6981

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.61793 | val 0.92387
  Epoch 013 - train 0.62571 | val 0.78161
  Classification -> best τ=0.520 (val F1=0.1857)
  Directional -> Accuracy: 0.4310, MCC: 0.1135, F1: 0.1951

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.64264 | val 0.93711
  Epoch 012 - train 0.64898 | val 0.85488
  Classification -> best τ=0.445 (val F1=0.1925)
  Directional -> Accuracy: 0.6000, MCC: 0.0000, F1: 0.7500

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.61934 | val 0.72031
  Epoch 015 - train 0.61390 | val 0.71828
  Classification -> best τ=0.550 (val F1=0.3075)
  Directional -> Accuracy: 0.5156, MCC: 0.0316, F1: 0.5507

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.58276 | val 0.72857
  Epoch 011 - train 0.60947 | val 0.85336
  Classification -> best τ=0.500 (val F1=0.2312)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.62504 | val 0.92220
  Epoch 011 - train 0.57947 | val 0.93456
  Classification -> best τ=0.535 (val F1=0.0712)
  Directional -> Accuracy: 0.5319, MCC: 0.0918, F1: 0.5600

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.66905 | val 0.74107
  Epoch 011 - train 0.63130 | val 0.78897
  Classification -> best τ=0.475 (val F1=0.0886)
  Directional -> Accuracy: 0.5077, MCC: 0.0000, F1: 0.6735

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.64409 | val 0.68808
  Epoch 018 - train 0.62581 | val 0.71957
  Classification -> best τ=0.540 (val F1=0.3294)
  Directional -> Accuracy: 0.5614, MCC: 0.1216, F1: 0.5902

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.65276 | val 0.69441
  Epoch 016 - train 0.64728 | val 0.81163
  Classification -> best τ=0.485 (val F1=0.1772)
  Directional -> Accuracy: 0.5385, MCC: 0.1166, F1: 0.6250

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.60385 | val 0.93854
  Epoch 013 - train 0.57602 | val 1.01812
  Classification -> best τ=0.430 (val F1=0.3360)
  Directional -> Accuracy: 0.5455, MCC: 0.0000, F1: 0.7059

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.57242 | val 2.10157
  Epoch 012 - train 0.55367 | val 3.65079
  Classification -> best τ=0.510 (val F1=0.2935)
  Directional -> Accuracy: 0.4222, MCC: -0.0492, F1: 0.5667

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.64039 | val 0.70545
  Epoch 011 - train 0.60614 | val 0.70425
  Classification -> best τ=0.515 (val F1=0.0550)
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.7273

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.60777 | val 0.91517
  Epoch 012 - train 0.63793 | val 0.72633
  Classification -> best τ=0.510 (val F1=0.2850)
  Directional -> Accuracy: 0.4464, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.53751 | val 0.74887
  Epoch 011 - train 0.49974 | val 0.72486
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5500, MCC: 0.0000, F1: 0.7097

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.66618 | val 0.99956
  Epoch 015 - train 0.55827 | val 0.73677
  Classification -> best τ=0.525 (val F1=0.4316)
  Directional -> Accuracy: 0.5476, MCC: 0.0835, F1: 0.4242

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.65267 | val 0.89876
  Epoch 011 - train 0.64625 | val 0.82171
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5476, MCC: 0.0000, F1: 0.7077

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.61217 | val 0.69456
  Epoch 013 - train 0.59022 | val 0.83628
  Classification -> best τ=0.515 (val F1=0.3302)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.61978 | val 0.72810
  Epoch 018 - train 0.55987 | val 0.82937
  Classification -> best τ=0.475 (val F1=0.3927)
  Directional -> Accuracy: 0.4444, MCC: -0.0598, F1: 0.2857

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.62015 | val 1.32605
  Epoch 011 - train 0.59108 | val 1.11266
  Classification -> best τ=0.485 (val F1=0.2814)
  Directional -> Accuracy: 0.5349, MCC: 0.1249, F1: 0.6552

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.66352 | val 1.08576
  Epoch 011 - train 0.64370 | val 1.14665
  Classification -> best τ=0.445 (val F1=0.3855)
  Directional -> Accuracy: 0.6061, MCC: 0.2015, F1: 0.6486

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.60070 | val 1.78465
  Epoch 013 - train 0.56220 | val 1.61687
  Classification -> best τ=0.440 (val F1=0.2464)
  Directional -> Accuracy: 0.5714, MCC: 0.1386, F1: 0.6667

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.55613 | val 1.06450
  Epoch 012 - train 0.56016 | val 1.62681
  Classification -> best τ=0.440 (val F1=0.1886)
  Directional -> Accuracy: 0.5179, MCC: 0.0333, F1: 0.4906

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.53619 | val 0.99838
  Epoch 011 - train 0.53929 | val 1.07840
  Classification -> best τ=0.465 (val F1=0.2118)
  Directional -> Accuracy: 0.5435, MCC: 0.0124, F1: 0.6441

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.61345 | val 0.63486
  Epoch 020 - train 0.51715 | val 1.03635
  Classification -> best τ=0.425 (val F1=0.4011)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.55953 | val 1.54306
  Epoch 012 - train 0.58509 | val 1.23060
  Classification -> best τ=0.310 (val F1=0.2479)
  Directional -> Accuracy: 0.4865, MCC: 0.0000, F1: 0.6545

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.64235 | val 0.70411
  Epoch 011 - train 0.62459 | val 0.69342
  Classification -> best τ=0.470 (val F1=0.1348)
  Directional -> Accuracy: 0.5556, MCC: 0.1129, F1: 0.5455

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.56362 | val 1.35303
  Epoch 011 - train 0.51258 | val 1.37781
  Classification -> best τ=0.520 (val F1=0.1667)
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.7273

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.58800 | val 0.76801
  Epoch 012 - train 0.56371 | val 0.74825
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.5455

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.67830 | val 0.77197
  Epoch 014 - train 0.63693 | val 0.78007
  Classification -> best τ=0.465 (val F1=0.1884)
  Directional -> Accuracy: 0.4182, MCC: -0.3051, F1: 0.5789

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.63483 | val 0.95820
  Epoch 011 - train 0.59739 | val 1.19060
  Classification -> best τ=0.565 (val F1=0.3052)
  Directional -> Accuracy: 0.6607, MCC: 0.3301, F1: 0.6780

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.66659 | val 0.72369
  Epoch 020 - train 0.60346 | val 0.69203
  Epoch 022 - train 0.57490 | val 0.67029
  Classification -> best τ=0.485 (val F1=0.2769)
  Directional -> Accuracy: 0.5660, MCC: 0.2496, F1: 0.7013

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.62437 | val 1.76608
  Epoch 011 - train 0.55643 | val 2.21083
  Classification -> best τ=0.520 (val F1=0.1997)
  Directional -> Accuracy: 0.4182, MCC: -0.1718, F1: 0.1579

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.64449 | val 0.66776

[I 2026-02-22 12:43:07,101] Trial 177 finished with value: 0.23940933312829948 and parameters: {'feature_set': 'sector', 'model_type': 'LSTM', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.5, 'batch_size': 16, 'learning_rate': 0.003525711078126494, 'weight_decay': 1.3070230685771104e-05, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 1.2484518104783997, 'early_stopping_min_delta': 2.5890835139728353e-06}. Best is trial 159 with value: 0.297766251520741.

  Epoch 020 - train 0.51996 | val 0.70696
  Classification -> best τ=0.400 (val F1=0.3281)
  Directional -> Accuracy: 0.6667, MCC: 0.3510, F1: 0.6970

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.23940933312829948
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.62023 | val 1.10432
  Epoch 012 - train 0.63279 | val 1.10151
  Classification -> best τ=0.795 (val F1=0.2510)
  Directional -> Accuracy: 0.5526, MCC: 0.0000, F1: 0.0000

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.54675 | val 1.18594
  Epoch 011 - train 0.54016 | val 1.23469
  Classification -> best τ=0.490 (val F1=0.1093)
  Directional -> Accuracy: 0.6222, MCC: 0.1941, F1: 0.7385

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.64198 | val 0.89069
  Epoch 011 - train 0.60277 | val 0.90592
  Classification -> best τ=0.600 (val F1=0.2625)
  Directional -> Accuracy: 0.4565, MCC: -0.0996, F1: 0.0741

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.62166 | val 1.01424
  Epoch 011 - train 0.60832 | val 0.96082
  Classification -> best τ=0.275 (val F1=0.1716)
  Directional -> Accuracy: 0.5135, MCC: -0.0752, F1: 0.6667

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.49616 | val 1.63850
  Epoch 012 - train 0.52290 | val 0.99393
  Classification -> best τ=0.650 (val F1=0.4930)
  Directional -> Accuracy: 0.4800, MCC: -0.0148, F1: 0.1875

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.53575 | val 0.75005
  Epoch 012 - train 0.58050 | val 0.84192
  Classification -> best τ=0.555 (val F1=0.2871)
  Directional -> Accuracy: 0.5217, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.59766 | val 0.92529
  Epoch 018 - train 0.54510 | val 1.67355
  Classification -> best τ=0.270 (val F1=0.2101)
  Directional -> Accuracy: 0.3676, MCC: -0.1722, F1: 0.4941

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.58285 | val 0.81787
  Epoch 014 - train 0.44175 | val 0.76972
  Classification -> best τ=0.345 (val F1=0.2168)
  Directional -> Accuracy: 0.4762, MCC: 0.0152, F1: 0.5417

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.55955 | val 3.43082
  Epoch 011 - train 0.57939 | val 2.17737
  Classification -> best τ=0.675 (val F1=0.2443)
  Directional -> Accuracy: 0.6250, MCC: 0.2305, F1: 0.3571

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.57022 | val 1.02033
  Epoch 011 - train 0.54691 | val 1.33686
  Classification -> best τ=0.600 (val F1=0.1607)
  Directional -> Accuracy: 0.4783, MCC: -0.0811, F1: 0.3571

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.62568 | val 0.84422
  Epoch 020 - train 0.53632 | val 0.64572
  Epoch 029 - train 0.37010 | val 1.86368
  Classification -> best τ=0.515 (val F1=0.3729)
  Directional -> Accuracy: 0.5918, MCC: 0.1537, F1: 0.3750

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.60094 | val 1.22263
  Epoch 012 - train 0.57103 | val 1.16081
  Classification -> best τ=0.395 (val F1=0.2157)
  Directional -> Accuracy: 0.5088, MCC: 0.0000, F1: 0.6744

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.49515 | val 3.75887
  Epoch 011 - train 0.48303 | val 1.69550
  Classification -> best τ=0.415 (val F1=0.1132)
  Directional -> Accuracy: 0.5476, MCC: 0.1003, F1: 0.5366

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.62833 | val 0.63488
  Epoch 011 - train 0.58911 | val 0.63672
  Classification -> best τ=0.415 (val F1=0.4276)
  Directional -> Accuracy: 0.5167, MCC: 0.0405, F1: 0.3256

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.59625 | val 0.88332
  Epoch 011 - train 0.56089 | val 0.76466
  Classification -> best τ=0.535 (val F1=0.2078)
  Directional -> Accuracy: 0.5490, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.57046 | val 1.95568
  Epoch 011 - train 0.56913 | val 1.48906
  Classification -> best τ=0.555 (val F1=0.1963)
  Directional -> Accuracy: 0.4638, MCC: -0.0432, F1: 0.3273

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.57224 | val 1.03559
  Epoch 013 - train 0.55377 | val 1.04640
  Classification -> best τ=0.650 (val F1=0.2569)
  Directional -> Accuracy: 0.3793, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.61084 | val 0.85766
  Epoch 012 - train 0.52408 | val 1.19093
  Classification -> best τ=0.235 (val F1=0.2004)
  Directional -> Accuracy: 0.6000, MCC: 0.0000, F1: 0.7500

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.58037 | val 1.18135
  Epoch 011 - train 0.56398 | val 1.51276
  Classification -> best τ=0.495 (val F1=0.2770)
  Directional -> Accuracy: 0.4844, MCC: 0.1062, F1: 0.2979

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.56778 | val 1.18888
  Epoch 011 - train 0.52360 | val 1.17614
  Classification -> best τ=0.340 (val F1=0.2642)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.49058 | val 0.87643
  Epoch 013 - train 0.50265 | val 1.44087
  Classification -> best τ=0.375 (val F1=0.2784)
  Directional -> Accuracy: 0.4255, MCC: 0.0834, F1: 0.1818

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.58875 | val 1.56998
  Epoch 011 - train 0.58629 | val 1.32696
  Classification -> best τ=0.535 (val F1=0.0835)
  Directional -> Accuracy: 0.4923, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.62122 | val 0.65560
  Epoch 020 - train 0.48237 | val 0.97162
  Epoch 023 - train 0.48689 | val 1.39816
  Classification -> best τ=0.315 (val F1=0.4893)
  Directional -> Accuracy: 0.5088, MCC: -0.0063, F1: 0.5758

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.60985 | val 0.83457
  Epoch 016 - train 0.59434 | val 0.84043
  Classification -> best τ=0.580 (val F1=0.1985)
  Directional -> Accuracy: 0.5077, MCC: -0.0445, F1: 0.1111

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.58202 | val 1.09460
  Epoch 012 - train 0.49858 | val 1.53621
  Classification -> best τ=0.465 (val F1=0.5656)
  Directional -> Accuracy: 0.5636, MCC: 0.1144, F1: 0.6129

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.43867 | val 2.82807
  Epoch 011 - train 0.50889 | val 3.81844
  Classification -> best τ=0.610 (val F1=0.2241)
  Directional -> Accuracy: 0.4667, MCC: 0.0068, F1: 0.5385

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.62791 | val 0.82740
  Epoch 011 - train 0.56458 | val 0.80679
  Classification -> best τ=0.480 (val F1=0.1978)
  Directional -> Accuracy: 0.5952, MCC: 0.1273, F1: 0.7213

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.53108 | val 2.33789
  Epoch 011 - train 0.51056 | val 2.07051
  Classification -> best τ=0.320 (val F1=0.1781)
  Directional -> Accuracy: 0.4464, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.56078 | val 1.42409
  Epoch 011 - train 0.41591 | val 1.03565
  Classification -> best τ=0.635 (val F1=0.1580)
  Directional -> Accuracy: 0.5500, MCC: 0.0503, F1: 0.6667

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.57020 | val 2.97119
  Epoch 011 - train 0.60996 | val 3.19298
  Classification -> best τ=0.480 (val F1=0.4110)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.4878

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.59921 | val 0.96447
  Epoch 011 - train 0.60244 | val 1.11270
  Classification -> best τ=0.375 (val F1=0.2357)
  Directional -> Accuracy: 0.5952, MCC: 0.1758, F1: 0.7119

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.53138 | val 0.96366
  Epoch 011 - train 0.49709 | val 1.04032
  Classification -> best τ=0.400 (val F1=0.3639)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.56044 | val 1.07796
  Epoch 013 - train 0.58211 | val 0.99349
  Classification -> best τ=0.445 (val F1=0.3260)
  Directional -> Accuracy: 0.4583, MCC: 0.0466, F1: 0.0930

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.55884 | val 1.15852
  Epoch 013 - train 0.51249 | val 1.03619
  Classification -> best τ=0.245 (val F1=0.2717)
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.62166 | val 1.32396
  Epoch 011 - train 0.57000 | val 1.20063
  Classification -> best τ=0.620 (val F1=0.2818)
  Directional -> Accuracy: 0.5606, MCC: 0.1322, F1: 0.5797

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.52148 | val 2.40085
  Epoch 011 - train 0.57328 | val 3.08314
  Classification -> best τ=0.310 (val F1=0.3218)
  Directional -> Accuracy: 0.6190, MCC: 0.2364, F1: 0.6364

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.56395 | val 1.18758
  Epoch 011 - train 0.57057 | val 1.11838
  Classification -> best τ=0.610 (val F1=0.2268)
  Directional -> Accuracy: 0.6429, MCC: 0.2831, F1: 0.5238

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.47460 | val 1.16456
  Epoch 011 - train 0.54931 | val 1.11712
  Classification -> best τ=0.540 (val F1=0.2659)
  Directional -> Accuracy: 0.5652, MCC: -0.0153, F1: 0.6970

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.60940 | val 0.72818
  Epoch 011 - train 0.61069 | val 0.67128
  Classification -> best τ=0.475 (val F1=0.4011)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.59939 | val 0.99437
  Epoch 011 - train 0.56124 | val 1.95159
  Classification -> best τ=0.485 (val F1=0.4011)
  Directional -> Accuracy: 0.5135, MCC: 0.0119, F1: 0.2500

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.64402 | val 0.71391
  Epoch 020 - train 0.54757 | val 1.40523
  Epoch 021 - train 0.48429 | val 1.29124
  Classification -> best τ=0.485 (val F1=0.4490)
  Directional -> Accuracy: 0.4889, MCC: -0.0103, F1: 0.2581

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.37545 | val 1.54936
  Epoch 013 - train 0.38404 | val 2.60295
  Classification -> best τ=0.570 (val F1=0.3595)
  Directional -> Accuracy: 0.5714, MCC: 0.1250, F1: 0.6250

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.58352 | val 0.82835
  Epoch 012 - train 0.51322 | val 1.50827
  Classification -> best τ=0.565 (val F1=0.1306)
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.5455

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.65103 | val 0.98518
  Epoch 018 - train 0.57070 | val 0.95240
  Classification -> best τ=0.900 (val F1=0.2036)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.48952 | val 3.28279
  Epoch 011 - train 0.51647 | val 2.92929
  Classification -> best τ=0.600 (val F1=0.3951)
  Directional -> Accuracy: 0.4464, MCC: -0.1019, F1: 0.4918

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.64440 | val 0.97385
  Epoch 013 - train 0.60233 | val 1.21107
  Classification -> best τ=0.275 (val F1=0.1824)
  Directional -> Accuracy: 0.5660, MCC: 0.1746, F1: 0.6849

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.55941 | val 3.67203
  Epoch 011 - train 0.51442 | val 3.12683
  Classification -> best τ=0.810 (val F1=0.0782)
  Directional -> Accuracy: 0.5455, MCC: 0.1475, F1: 0.3902

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.63400 | val 0.81682

[I 2026-02-22 12:45:37,943] Trial 178 finished with value: 0.2670391840339599 and parameters: {'feature_set': 'sector', 'model_type': 'BiGRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.5, 'batch_size': 16, 'learning_rate': 0.0063308884117263126, 'weight_decay': 3.0626965920961015e-05, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 1.5285334749787935, 'early_stopping_min_delta': 0.0033510691556209136}. Best is trial 159 with value: 0.297766251520741.

  Epoch 011 - train 0.54468 | val 0.95173
  Classification -> best τ=0.410 (val F1=0.2006)
  Directional -> Accuracy: 0.4833, MCC: -0.0381, F1: 0.4364

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2670391840339599
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d', 'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down', 'finbert_neutral']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.57448 | val 1.08782
  Epoch 011 - train 0.54544 | val 1.51661
  Classification -> best τ=0.510 (val F1=0.1671)
  Directional -> Accuracy: 0.5395, MCC: 0.1075, F1: 0.5679

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.54695 | val 1.76689
  Epoch 011 - train 0.53902 | val 1.51520
  Classification -> best τ=0.475 (val F1=0.1297)
  Directional -> Accuracy: 0.6222, MCC: 0.2523, F1: 0.7536

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.56331 | val 1.40660
  Epoch 011 - train 0.51428 | val 1.08516
  Classification -> best τ=0.560 (val F1=0.2727)
  Directional -> Accuracy: 0.4565, MCC: -0.0996, F1: 0.0741

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.58689 | val 0.83746
  Epoch 011 - train 0.55299 | val 0.98048
  Classification -> best τ=0.290 (val F1=0.2157)
  Directional -> Accuracy: 0.4730, MCC: -0.0073, F1: 0.2909

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.53246 | val 0.96698
  Epoch 012 - train 0.49943 | val 1.56829
  Classification -> best τ=0.680 (val F1=0.4414)
  Directional -> Accuracy: 0.6200, MCC: 0.2957, F1: 0.5128

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.51872 | val 0.96430
  Epoch 011 - train 0.49713 | val 1.18900
  Classification -> best τ=0.515 (val F1=0.3301)
  Directional -> Accuracy: 0.5870, MCC: 0.2759, F1: 0.2400

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.54600 | val 1.93325
  Epoch 011 - train 0.57717 | val 1.26941
  Classification -> best τ=0.575 (val F1=0.1671)
  Directional -> Accuracy: 0.5294, MCC: 0.0417, F1: 0.4483

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.43944 | val 0.72097
  Epoch 011 - train 0.41514 | val 1.22021
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.53584 | val 1.59528
  Epoch 011 - train 0.51336 | val 1.68703
  Classification -> best τ=0.490 (val F1=0.1608)
  Directional -> Accuracy: 0.6042, MCC: 0.1782, F1: 0.4865

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.57478 | val 0.93610
  Epoch 017 - train 0.44027 | val 0.83986
  Classification -> best τ=0.380 (val F1=0.2376)
  Directional -> Accuracy: 0.5217, MCC: 0.0921, F1: 0.5479

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.53270 | val 0.98625
  Epoch 013 - train 0.47328 | val 1.92433
  Classification -> best τ=0.615 (val F1=0.3005)
  Directional -> Accuracy: 0.6327, MCC: 0.2673, F1: 0.4000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.56689 | val 2.19937
  Epoch 011 - train 0.57651 | val 2.23952
  Classification -> best τ=0.410 (val F1=0.2157)
  Directional -> Accuracy: 0.6316, MCC: 0.3023, F1: 0.7123

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.56757 | val 2.54031
  Epoch 011 - train 0.47886 | val 2.16462
  Classification -> best τ=0.335 (val F1=0.3190)
  Directional -> Accuracy: 0.4762, MCC: 0.0387, F1: 0.6071

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.55726 | val 0.83746
  Epoch 011 - train 0.58920 | val 0.64205
  Classification -> best τ=0.485 (val F1=0.3864)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.48416 | val 2.28989
  Epoch 011 - train 0.55152 | val 1.06334
  Classification -> best τ=0.600 (val F1=0.3737)
  Directional -> Accuracy: 0.4706, MCC: -0.0424, F1: 0.4906

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.57916 | val 1.10070
  Epoch 011 - train 0.52030 | val 1.11136
  Classification -> best τ=0.390 (val F1=0.1823)
  Directional -> Accuracy: 0.5362, MCC: 0.0224, F1: 0.6800

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.57050 | val 1.49289
  Epoch 011 - train 0.56973 | val 1.70640
  Classification -> best τ=0.295 (val F1=0.1394)
  Directional -> Accuracy: 0.6034, MCC: 0.1653, F1: 0.6761

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.55181 | val 1.10935
  Epoch 013 - train 0.59532 | val 1.35544
  Classification -> best τ=0.290 (val F1=0.1958)
  Directional -> Accuracy: 0.4800, MCC: -0.1021, F1: 0.5806

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.59675 | val 1.02512
  Epoch 012 - train 0.46814 | val 1.06421
  Classification -> best τ=0.355 (val F1=0.2803)
  Directional -> Accuracy: 0.5625, MCC: 0.0048, F1: 0.7021

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.51296 | val 1.26202
  Epoch 011 - train 0.54627 | val 1.64160
  Classification -> best τ=0.540 (val F1=0.2309)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.54942 | val 2.82208
  Epoch 011 - train 0.52003 | val 2.47060
  Classification -> best τ=0.550 (val F1=0.1383)
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.58176 | val 1.14934
  Epoch 011 - train 0.56142 | val 1.10946
  Classification -> best τ=0.335 (val F1=0.2037)
  Directional -> Accuracy: 0.5385, MCC: 0.0760, F1: 0.6053

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.56264 | val 0.58684
  Epoch 020 - train 0.39615 | val 1.50955
  Classification -> best τ=0.480 (val F1=0.4704)
  Directional -> Accuracy: 0.5439, MCC: -0.1181, F1: 0.7045

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.59036 | val 0.87908
  Epoch 011 - train 0.56762 | val 0.85503
  Classification -> best τ=0.505 (val F1=0.1348)
  Directional -> Accuracy: 0.4769, MCC: -0.0548, F1: 0.4138

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.60873 | val 0.93190
  Epoch 020 - train 0.41587 | val 1.55957
  Classification -> best τ=0.300 (val F1=0.4629)
  Directional -> Accuracy: 0.5636, MCC: 0.1406, F1: 0.5556

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.46391 | val 4.42081
  Epoch 011 - train 0.38667 | val 4.07910
  Classification -> best τ=0.565 (val F1=0.2035)
  Directional -> Accuracy: 0.4667, MCC: -0.0931, F1: 0.3684

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.58005 | val 1.20703
  Epoch 011 - train 0.52405 | val 1.15745
  Classification -> best τ=0.570 (val F1=0.1925)
  Directional -> Accuracy: 0.5476, MCC: 0.1635, F1: 0.4865

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.53260 | val 2.93461
  Epoch 011 - train 0.49746 | val 1.96884
  Classification -> best τ=0.515 (val F1=0.2305)
  Directional -> Accuracy: 0.4464, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.56489 | val 0.96948
  Epoch 011 - train 0.59367 | val 0.93567
  Classification -> best τ=0.570 (val F1=0.3477)
  Directional -> Accuracy: 0.4500, MCC: 0.0000, F1: 0.0000

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.51349 | val 2.42772
  Epoch 012 - train 0.58655 | val 1.74418
  Classification -> best τ=0.555 (val F1=0.3656)
  Directional -> Accuracy: 0.4524, MCC: -0.1137, F1: 0.3429

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.60356 | val 0.68839
  Epoch 020 - train 0.40806 | val 0.97462
  Classification -> best τ=0.625 (val F1=0.3054)
  Directional -> Accuracy: 0.6190, MCC: 0.4065, F1: 0.4667

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.48192 | val 1.50694
  Epoch 011 - train 0.51386 | val 1.70470
  Classification -> best τ=0.600 (val F1=0.2399)
  Directional -> Accuracy: 0.4898, MCC: 0.0036, F1: 0.3902

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.52830 | val 1.30504
  Epoch 013 - train 0.52964 | val 0.96009
  Classification -> best τ=0.570 (val F1=0.2970)
  Directional -> Accuracy: 0.4444, MCC: 0.0000, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.51813 | val 1.38157
  Epoch 012 - train 0.48759 | val 1.21089
  Classification -> best τ=0.420 (val F1=0.2717)
  Directional -> Accuracy: 0.5116, MCC: 0.0849, F1: 0.6557

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.58148 | val 1.69215
  Epoch 011 - train 0.59355 | val 1.17696
  Classification -> best τ=0.515 (val F1=0.3298)
  Directional -> Accuracy: 0.4545, MCC: 0.0895, F1: 0.1429

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.41995 | val 2.92265
  Epoch 012 - train 0.36970 | val 2.37302
  Classification -> best τ=0.495 (val F1=0.4011)
  Directional -> Accuracy: 0.5952, MCC: 0.2132, F1: 0.5405

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.55057 | val 1.07035
  Epoch 011 - train 0.53803 | val 1.56320
  Classification -> best τ=0.445 (val F1=0.2382)
  Directional -> Accuracy: 0.5893, MCC: 0.2034, F1: 0.6230

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.45969 | val 1.07597
  Epoch 012 - train 0.43514 | val 1.06430
  Classification -> best τ=0.680 (val F1=0.2185)
  Directional -> Accuracy: 0.4130, MCC: -0.0062, F1: 0.1818

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.43001 | val 0.77317
  Epoch 013 - train 0.47532 | val 0.65884
  Classification -> best τ=0.365 (val F1=0.4011)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.55446 | val 2.15769
  Epoch 011 - train 0.57614 | val 1.53720
  Classification -> best τ=0.470 (val F1=0.2397)
  Directional -> Accuracy: 0.4865, MCC: 0.0000, F1: 0.6545

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.64263 | val 0.73900
  Epoch 014 - train 0.51293 | val 2.11322
  Classification -> best τ=0.425 (val F1=0.3953)
  Directional -> Accuracy: 0.5333, MCC: 0.1541, F1: 0.6866

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.44058 | val 3.23659
  Epoch 011 - train 0.41107 | val 3.06004
  Classification -> best τ=0.510 (val F1=0.2632)
  Directional -> Accuracy: 0.5952, MCC: 0.1334, F1: 0.7302

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.56977 | val 0.64042
  Epoch 020 - train 0.28908 | val 1.18338
  Classification -> best τ=0.615 (val F1=0.3672)
  Directional -> Accuracy: 0.5208, MCC: 0.2619, F1: 0.5965

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.60614 | val 1.15031
  Epoch 011 - train 0.60643 | val 1.66123
  Classification -> best τ=0.600 (val F1=0.2184)
  Directional -> Accuracy: 0.4364, MCC: -0.0938, F1: 0.2791

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.51327 | val 3.82998
  Epoch 011 - train 0.47512 | val 4.02539
  Classification -> best τ=0.540 (val F1=0.4355)
  Directional -> Accuracy: 0.5357, MCC: 0.1173, F1: 0.6389

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.60861 | val 0.85903
  Epoch 012 - train 0.63777 | val 1.02489
  Classification -> best τ=0.395 (val F1=0.2486)
  Directional -> Accuracy: 0.5660, MCC: 0.1998, F1: 0.6933

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.57694 | val 2.98258
  Epoch 011 - train 0.52754 | val 2.90043
  Classification -> best τ=0.705 (val F1=0.1682)
  Directional -> Accuracy: 0.5636, MCC: 0.2052, F1: 0.7073

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.59789 | val 0.71453

[I 2026-02-22 12:48:04,331] Trial 179 finished with value: 0.26931492607125146 and parameters: {'feature_set': 'sector_finbert', 'model_type': 'BiGRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.6000000000000001, 'batch_size': 16, 'learning_rate': 0.004522122684103564, 'weight_decay': 2.3383289206717107e-05, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 20, 'huber_delta': 1.0425091518502994, 'early_stopping_min_delta': 0.000527037721935638}. Best is trial 159 with value: 0.297766251520741.

  Epoch 020 - train 0.49370 | val 0.84495
  Classification -> best τ=0.450 (val F1=0.3923)
  Directional -> Accuracy: 0.5167, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.26931492607125146
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.64321 | val 0.85561
  Epoch 011 - train 0.60879 | val 0.87729
  Classification -> best τ=0.825 (val F1=0.2036)
  Directional -> Accuracy: 0.5526, MCC: 0.0000, F1: 0.0000

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.52392 | val 1.86018
  Epoch 011 - train 0.51205 | val 1.39987
  Classification -> best τ=0.425 (val F1=0.2826)
  Directional -> Accuracy: 0.5778, MCC: 0.0000, F1: 0.7324

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.56202 | val 1.72039
  Epoch 011 - train 0.57375 | val 1.66753
  Classification -> best τ=0.570 (val F1=0.2941)
  Directional -> Accuracy: 0.4783, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.61462 | val 0.82739
  Epoch 011 - train 0.59535 | val 0.98293
  Classification -> best τ=0.295 (val F1=0.2030)
  Directional -> Accuracy: 0.5135, MCC: -0.0472, F1: 0.6538

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.55451 | val 0.83527
  Epoch 012 - train 0.53812 | val 1.37840
  Classification -> best τ=0.655 (val F1=0.3919)
  Directional -> Accuracy: 0.6200, MCC: 0.2670, F1: 0.5581

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.55491 | val 0.81185
  Epoch 011 - train 0.52483 | val 0.79979
  Classification -> best τ=0.570 (val F1=0.0985)
  Directional -> Accuracy: 0.5217, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.61899 | val 1.46720
  Epoch 011 - train 0.60123 | val 1.25941
  Classification -> best τ=0.475 (val F1=0.2272)
  Directional -> Accuracy: 0.4265, MCC: 0.1413, F1: 0.5806

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.61295 | val 2.64711
  Epoch 014 - train 0.62305 | val 4.42175
  Classification -> best τ=0.605 (val F1=0.3632)
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.60124 | val 1.54874
  Epoch 011 - train 0.61548 | val 1.89710
  Classification -> best τ=0.610 (val F1=0.2443)
  Directional -> Accuracy: 0.5833, MCC: 0.1734, F1: 0.5652

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.58016 | val 0.95574
  Epoch 011 - train 0.56135 | val 0.87063
  Classification -> best τ=0.380 (val F1=0.2504)
  Directional -> Accuracy: 0.4203, MCC: 0.0000, F1: 0.5918

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.59038 | val 0.89659
  Epoch 011 - train 0.55102 | val 0.93192
  Classification -> best τ=0.535 (val F1=0.2765)
  Directional -> Accuracy: 0.5510, MCC: 0.0584, F1: 0.3529

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.58237 | val 1.40472
  Epoch 011 - train 0.60201 | val 1.75137
  Classification -> best τ=0.505 (val F1=0.0681)
  Directional -> Accuracy: 0.6316, MCC: 0.2680, F1: 0.6769

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.57506 | val 3.23938
  Epoch 011 - train 0.56639 | val 3.12609
  Classification -> best τ=0.365 (val F1=0.2466)
  Directional -> Accuracy: 0.5476, MCC: 0.1513, F1: 0.6122

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.64171 | val 0.67005
  Epoch 019 - train 0.53034 | val 0.84878
  Classification -> best τ=0.140 (val F1=0.3859)
  Directional -> Accuracy: 0.5167, MCC: 0.0334, F1: 0.5246

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.57847 | val 0.95364
  Epoch 011 - train 0.57657 | val 0.86979
  Classification -> best τ=0.520 (val F1=0.3390)
  Directional -> Accuracy: 0.5490, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.55748 | val 1.24957
  Epoch 011 - train 0.59037 | val 1.23834
  Classification -> best τ=0.450 (val F1=0.3094)
  Directional -> Accuracy: 0.5652, MCC: 0.1424, F1: 0.7059

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.57511 | val 1.16002
  Epoch 011 - train 0.60142 | val 1.30465
  Classification -> best τ=0.415 (val F1=0.1905)
  Directional -> Accuracy: 0.5000, MCC: -0.0172, F1: 0.5672

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.58325 | val 1.19800
  Epoch 011 - train 0.58112 | val 1.39626
  Classification -> best τ=0.545 (val F1=0.1909)
  Directional -> Accuracy: 0.4000, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.58849 | val 0.77742
  Epoch 011 - train 0.65460 | val 0.99465
  Classification -> best τ=0.405 (val F1=0.2843)
  Directional -> Accuracy: 0.5469, MCC: 0.1156, F1: 0.5538

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.56471 | val 1.21023
  Epoch 011 - train 0.56529 | val 0.97869
  Classification -> best τ=0.515 (val F1=0.2881)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.54329 | val 1.53028
  Epoch 011 - train 0.55952 | val 1.75650
  Classification -> best τ=0.490 (val F1=0.0850)
  Directional -> Accuracy: 0.4043, MCC: 0.0267, F1: 0.1250

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.66107 | val 0.91270
  Epoch 011 - train 0.59864 | val 0.94944
  Classification -> best τ=0.465 (val F1=0.2037)
  Directional -> Accuracy: 0.5077, MCC: 0.0000, F1: 0.6735

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.64018 | val 0.69815
  Epoch 015 - train 0.56522 | val 0.89726
  Classification -> best τ=0.760 (val F1=0.3452)
  Directional -> Accuracy: 0.4912, MCC: 0.1153, F1: 0.2564

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.60358 | val 0.94932
  Epoch 011 - train 0.62110 | val 1.31707
  Classification -> best τ=0.515 (val F1=0.1985)
  Directional -> Accuracy: 0.5231, MCC: 0.0000, F1: 0.0000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.60508 | val 1.08972
  Epoch 012 - train 0.58136 | val 1.37496
  Classification -> best τ=0.525 (val F1=0.4914)
  Directional -> Accuracy: 0.5818, MCC: 0.2024, F1: 0.5306

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.52366 | val 3.15783
  Epoch 011 - train 0.57344 | val 3.35008
  Classification -> best τ=0.490 (val F1=0.2035)
  Directional -> Accuracy: 0.4000, MCC: -0.1273, F1: 0.5424

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.61614 | val 1.71514
  Epoch 011 - train 0.59502 | val 1.66527
  Classification -> best τ=0.460 (val F1=0.1936)
  Directional -> Accuracy: 0.5000, MCC: 0.0430, F1: 0.4615

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.53582 | val 1.35712
  Epoch 011 - train 0.55241 | val 1.56769
  Classification -> best τ=0.440 (val F1=0.2829)
  Directional -> Accuracy: 0.4464, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.55874 | val 0.73687
  Epoch 011 - train 0.60200 | val 0.72347
  Classification -> best τ=0.535 (val F1=0.2774)
  Directional -> Accuracy: 0.5000, MCC: 0.0754, F1: 0.3333

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.56184 | val 0.91629
  Epoch 016 - train 0.55290 | val 1.44614
  Classification -> best τ=0.355 (val F1=0.2962)
  Directional -> Accuracy: 0.4762, MCC: -0.0500, F1: 0.4500

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.66086 | val 1.64273
  Epoch 011 - train 0.53930 | val 1.32967
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5476, MCC: 0.0000, F1: 0.7077

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.54526 | val 1.31332
  Epoch 012 - train 0.57004 | val 0.99540
  Classification -> best τ=0.370 (val F1=0.2932)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.59268 | val 1.38840
  Epoch 012 - train 0.54750 | val 1.13438
  Classification -> best τ=0.645 (val F1=0.2267)
  Directional -> Accuracy: 0.4444, MCC: 0.0000, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.57999 | val 0.94581
  Epoch 011 - train 0.56317 | val 0.89821
  Classification -> best τ=0.450 (val F1=0.2324)
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.64432 | val 1.05950
  Epoch 011 - train 0.56868 | val 1.32472
  Classification -> best τ=0.455 (val F1=0.4538)
  Directional -> Accuracy: 0.5606, MCC: 0.2461, F1: 0.4528

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.54157 | val 2.09915
  Epoch 011 - train 0.45789 | val 2.08158
  Classification -> best τ=0.475 (val F1=0.2464)
  Directional -> Accuracy: 0.5238, MCC: 0.0000, F1: 0.6875

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.56280 | val 1.34976
  Epoch 012 - train 0.54541 | val 1.72469
  Classification -> best τ=0.535 (val F1=0.2450)
  Directional -> Accuracy: 0.5179, MCC: 0.0333, F1: 0.4906

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.57343 | val 1.40595
  Epoch 011 - train 0.51548 | val 1.36502
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.6087, MCC: 0.0000, F1: 0.7568

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.55728 | val 0.63612
  Epoch 020 - train 0.48144 | val 0.97620
  Epoch 021 - train 0.47244 | val 0.87680
  Classification -> best τ=0.270 (val F1=0.5119)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.56686 | val 1.13957
  Epoch 011 - train 0.58575 | val 1.30646
  Classification -> best τ=0.395 (val F1=0.2479)
  Directional -> Accuracy: 0.4865, MCC: 0.0000, F1: 0.6545

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.66501 | val 0.78126
  Epoch 011 - train 0.64683 | val 0.75603
  Classification -> best τ=0.500 (val F1=0.2000)
  Directional -> Accuracy: 0.5778, MCC: 0.1613, F1: 0.6545

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.56698 | val 1.74813
  Epoch 011 - train 0.49389 | val 1.44134
  Classification -> best τ=0.500 (val F1=0.2677)
  Directional -> Accuracy: 0.4048, MCC: -0.1407, F1: 0.2857

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.55283 | val 0.80046
  Epoch 011 - train 0.50884 | val 0.97662
  Classification -> best τ=0.475 (val F1=0.1667)
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.5455

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.62884 | val 1.79474
  Epoch 011 - train 0.63827 | val 1.80691
  Classification -> best τ=0.400 (val F1=0.2291)
  Directional -> Accuracy: 0.5455, MCC: 0.0000, F1: 0.7059

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.56001 | val 1.69038
  Epoch 011 - train 0.50100 | val 2.53203
  Classification -> best τ=0.680 (val F1=0.2649)
  Directional -> Accuracy: 0.5357, MCC: 0.0830, F1: 0.5806

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.63119 | val 1.01790
  Epoch 012 - train 0.60175 | val 0.86028
  Classification -> best τ=0.385 (val F1=0.3033)
  Directional -> Accuracy: 0.5472, MCC: 0.2018, F1: 0.6923

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.56862 | val 2.48400
  Epoch 011 - train 0.55616 | val 3.83956
  Classification -> best τ=0.770 (val F1=0.1290)
  Directional -> Accuracy: 0.5091, MCC: 0.0593, F1: 0.3415

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.61800 | val 0.65307

[I 2026-02-22 12:50:32,422] Trial 180 finished with value: 0.251651377724219 and parameters: {'feature_set': 'sector', 'model_type': 'BiGRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.6000000000000001, 'batch_size': 16, 'learning_rate': 0.0023519859394626427, 'weight_decay': 1.1263075922548188e-06, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 1.1398686419012498, 'early_stopping_min_delta': 0.00039218816212307106}. Best is trial 159 with value: 0.297766251520741.

  Epoch 020 - train 0.47438 | val 0.82434
  Classification -> best τ=0.510 (val F1=0.3458)
  Directional -> Accuracy: 0.6500, MCC: 0.3002, F1: 0.6441

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.251651377724219
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.60091 | val 0.96382
  Epoch 012 - train 0.61780 | val 1.24678
  Classification -> best τ=0.520 (val F1=0.1635)
  Directional -> Accuracy: 0.5921, MCC: 0.1586, F1: 0.4746

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.51307 | val 1.49862
  Epoch 012 - train 0.53631 | val 1.53449
  Classification -> best τ=0.600 (val F1=0.2523)
  Directional -> Accuracy: 0.6000, MCC: 0.1419, F1: 0.7000

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.65707 | val 0.99224
  Epoch 011 - train 0.63110 | val 1.03646
  Classification -> best τ=0.730 (val F1=0.2727)
  Directional -> Accuracy: 0.4565, MCC: -0.0996, F1: 0.0741

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.58962 | val 1.28903
  Epoch 020 - train 0.50244 | val 0.98906
  Epoch 030 - train 0.50838 | val 0.78434
  Classification -> best τ=0.415 (val F1=0.2593)
  Directional -> Accuracy: 0.4730, MCC: -0.1276, F1: 0.6061

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.51494 | val 1.80435
  Epoch 011 - train 0.48119 | val 2.09376
  Classification -> best τ=0.530 (val F1=0.4048)
  Directional -> Accuracy: 0.6600, MCC: 0.3245, F1: 0.6531

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.53686 | val 0.70090
  Epoch 020 - train 0.41177 | val 0.96984
  Epoch 024 - train 0.42865 | val 1.69727
  Classification -> best τ=0.410 (val F1=0.3548)
  Directional -> Accuracy: 0.5000, MCC: -0.1427, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.58576 | val 1.32996
  Epoch 011 - train 0.57293 | val 0.89097
  Classification -> best τ=0.525 (val F1=0.3514)
  Directional -> Accuracy: 0.5294, MCC: 0.0921, F1: 0.5152

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.50253 | val 0.59781
  Epoch 020 - train 0.46828 | val 2.28956
  Epoch 023 - train 0.37611 | val 1.19232
  Classification -> best τ=0.130 (val F1=0.3855)
  Directional -> Accuracy: 0.4524, MCC: 0.0534, F1: 0.5965

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.60829 | val 1.89100
  Epoch 013 - train 0.52127 | val 1.71902
  Classification -> best τ=0.675 (val F1=0.2988)
  Directional -> Accuracy: 0.6875, MCC: 0.3620, F1: 0.6341

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.59324 | val 0.67945
  Epoch 020 - train 0.51128 | val 0.78951
  Classification -> best τ=0.530 (val F1=0.2460)
  Directional -> Accuracy: 0.4493, MCC: -0.1099, F1: 0.3871

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.61071 | val 0.92003
  Epoch 011 - train 0.58181 | val 1.37381
  Classification -> best τ=0.485 (val F1=0.2173)
  Directional -> Accuracy: 0.5306, MCC: 0.0554, F1: 0.4889

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.61055 | val 1.12572
  Epoch 014 - train 0.50313 | val 1.90774
  Classification -> best τ=0.375 (val F1=0.2258)
  Directional -> Accuracy: 0.5088, MCC: 0.0000, F1: 0.6744

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.60427 | val 2.55697
  Epoch 011 - train 0.49318 | val 1.79952
  Classification -> best τ=0.730 (val F1=0.1754)
  Directional -> Accuracy: 0.4762, MCC: -0.0784, F1: 0.3529

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.62133 | val 0.70864
  Epoch 015 - train 0.57499 | val 0.73907
  Classification -> best τ=0.470 (val F1=0.4317)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.57860 | val 1.34914
  Epoch 018 - train 0.47963 | val 2.30160
  Classification -> best τ=0.470 (val F1=0.1765)
  Directional -> Accuracy: 0.5490, MCC: 0.0606, F1: 0.3784

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.57747 | val 0.99710
  Epoch 011 - train 0.60674 | val 1.01272
  Classification -> best τ=0.400 (val F1=0.2795)
  Directional -> Accuracy: 0.5652, MCC: 0.1171, F1: 0.6939

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.59684 | val 2.11301
  Epoch 011 - train 0.58572 | val 1.21312
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.6207, MCC: 0.0000, F1: 0.7660

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.58472 | val 0.87639
  Epoch 011 - train 0.52867 | val 1.12977
  Classification -> best τ=0.480 (val F1=0.2220)
  Directional -> Accuracy: 0.4000, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.56776 | val 2.10006
  Epoch 011 - train 0.60142 | val 1.60403
  Classification -> best τ=0.380 (val F1=0.3689)
  Directional -> Accuracy: 0.5156, MCC: 0.1459, F1: 0.3922

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.57281 | val 1.02291
  Epoch 011 - train 0.53110 | val 1.23693
  Classification -> best τ=0.535 (val F1=0.3271)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.53974 | val 1.43717
  Epoch 011 - train 0.49934 | val 1.43036
  Classification -> best τ=0.595 (val F1=0.2449)
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.59597 | val 1.54886
  Epoch 012 - train 0.54921 | val 1.61839
  Classification -> best τ=0.670 (val F1=0.2753)
  Directional -> Accuracy: 0.4923, MCC: -0.0027, F1: 0.0571

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.64595 | val 0.74512
  Epoch 020 - train 0.50453 | val 1.02203
  Epoch 022 - train 0.58015 | val 1.04510
  Classification -> best τ=0.630 (val F1=0.4409)
  Directional -> Accuracy: 0.5439, MCC: 0.0737, F1: 0.5938

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.59592 | val 0.73849
  Epoch 012 - train 0.60182 | val 1.42942
  Classification -> best τ=0.440 (val F1=0.0277)
  Directional -> Accuracy: 0.6000, MCC: 0.2009, F1: 0.5938

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.58301 | val 1.15909
  Epoch 013 - train 0.52851 | val 1.31316
  Classification -> best τ=0.320 (val F1=0.5048)
  Directional -> Accuracy: 0.6000, MCC: 0.2476, F1: 0.5417

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.44769 | val 2.80647
  Epoch 011 - train 0.56126 | val 2.94896
  Classification -> best τ=0.610 (val F1=0.2935)
  Directional -> Accuracy: 0.5111, MCC: 0.1621, F1: 0.6071

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.57301 | val 1.10584
  Epoch 015 - train 0.54478 | val 0.75507
  Classification -> best τ=0.510 (val F1=0.2976)
  Directional -> Accuracy: 0.5952, MCC: 0.1795, F1: 0.6383

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.59834 | val 1.26881
  Epoch 011 - train 0.52918 | val 1.59859
  Classification -> best τ=0.210 (val F1=0.1986)
  Directional -> Accuracy: 0.5714, MCC: 0.2023, F1: 0.5000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.55430 | val 0.72093
  Epoch 011 - train 0.50494 | val 0.76713
  Classification -> best τ=0.595 (val F1=0.1183)
  Directional -> Accuracy: 0.5750, MCC: 0.1372, F1: 0.6222

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.59634 | val 0.91384
  Epoch 020 - train 0.48665 | val 1.79896
  Epoch 023 - train 0.47340 | val 1.93127
  Classification -> best τ=0.660 (val F1=0.3501)
  Directional -> Accuracy: 0.4762, MCC: -0.0853, F1: 0.2667

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.56157 | val 0.89039
  Epoch 012 - train 0.56830 | val 1.19756
  Classification -> best τ=0.370 (val F1=0.0769)
  Directional -> Accuracy: 0.5476, MCC: 0.0000, F1: 0.7077

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.53589 | val 1.11870
  Epoch 012 - train 0.47923 | val 1.29408
  Classification -> best τ=0.420 (val F1=0.3802)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.54270 | val 1.30897
  Epoch 011 - train 0.62705 | val 0.97538
  Classification -> best τ=0.320 (val F1=0.3427)
  Directional -> Accuracy: 0.4444, MCC: -0.0395, F1: 0.1667

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.56581 | val 1.49064
  Epoch 011 - train 0.55369 | val 1.32386
  Classification -> best τ=0.590 (val F1=0.3227)
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.59030 | val 2.14345
  Epoch 011 - train 0.58624 | val 1.80395
  Classification -> best τ=0.595 (val F1=0.0866)
  Directional -> Accuracy: 0.5303, MCC: -0.1873, F1: 0.6931

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.53633 | val 1.84967
  Epoch 011 - train 0.52801 | val 2.16994
  Classification -> best τ=0.405 (val F1=0.2464)
  Directional -> Accuracy: 0.5476, MCC: 0.0826, F1: 0.6415

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.58617 | val 1.00678
  Epoch 011 - train 0.54996 | val 0.95305
  Classification -> best τ=0.540 (val F1=0.2327)
  Directional -> Accuracy: 0.5179, MCC: 0.0333, F1: 0.4906

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.53328 | val 1.01736
  Epoch 011 - train 0.49789 | val 0.83222
  Classification -> best τ=0.320 (val F1=0.2118)
  Directional -> Accuracy: 0.6087, MCC: 0.0000, F1: 0.7568

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.46550 | val 0.73336
  Epoch 015 - train 0.45036 | val 1.19725
  Classification -> best τ=0.370 (val F1=0.5119)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.58399 | val 1.83714
  Epoch 011 - train 0.56576 | val 1.99231
  Classification -> best τ=0.175 (val F1=0.2397)
  Directional -> Accuracy: 0.4865, MCC: 0.0000, F1: 0.6545

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.59661 | val 0.72205
  Epoch 017 - train 0.50731 | val 0.94393
  Classification -> best τ=0.550 (val F1=0.4080)
  Directional -> Accuracy: 0.6000, MCC: 0.2070, F1: 0.6667

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.45665 | val 3.19991
  Epoch 011 - train 0.49756 | val 3.07463
  Classification -> best τ=0.610 (val F1=0.4082)
  Directional -> Accuracy: 0.5714, MCC: 0.2582, F1: 0.4706

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.54761 | val 0.75017
  Epoch 014 - train 0.52645 | val 0.65655
  Classification -> best τ=0.560 (val F1=0.3638)
  Directional -> Accuracy: 0.5000, MCC: 0.2928, F1: 0.6000

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.64791 | val 1.31029
  Epoch 011 - train 0.61662 | val 1.37135
  Classification -> best τ=0.530 (val F1=0.2036)
  Directional -> Accuracy: 0.4727, MCC: 0.1242, F1: 0.0645

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.54704 | val 2.07958
  Epoch 011 - train 0.57442 | val 1.65185
  Classification -> best τ=0.310 (val F1=0.2812)
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.6506

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.65395 | val 0.96969
  Epoch 012 - train 0.54588 | val 1.18542
  Classification -> best τ=0.545 (val F1=0.1168)
  Directional -> Accuracy: 0.5283, MCC: 0.0800, F1: 0.3590

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.53343 | val 2.57009
  Epoch 011 - train 0.48579 | val 2.75831
  Classification -> best τ=0.855 (val F1=0.0580)
  Directional -> Accuracy: 0.4909, MCC: 0.1289, F1: 0.0667

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.56607 | val 0.88603

[I 2026-02-22 12:53:11,504] Trial 181 finished with value: 0.27096645314922707 and parameters: {'feature_set': 'sector', 'model_type': 'BiGRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.5, 'batch_size': 16, 'learning_rate': 0.005251987643999094, 'weight_decay': 1.9018434139633666e-05, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 1.0893926784255406, 'early_stopping_min_delta': 8.674970697272052e-06}. Best is trial 159 with value: 0.297766251520741.

  Epoch 017 - train 0.55605 | val 0.67149
  Classification -> best τ=0.580 (val F1=0.3496)
  Directional -> Accuracy: 0.5333, MCC: 0.0842, F1: 0.1250

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.27096645314922707
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.61506 | val 0.91172
  Epoch 011 - train 0.60519 | val 0.96431
  Classification -> best τ=0.640 (val F1=0.2510)
  Directional -> Accuracy: 0.5526, MCC: 0.0000, F1: 0.0000

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.51579 | val 1.15193
  Epoch 012 - train 0.52297 | val 1.55483
  Classification -> best τ=0.500 (val F1=0.0492)
  Directional -> Accuracy: 0.6667, MCC: 0.3050, F1: 0.7273

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.56378 | val 1.06781
  Epoch 011 - train 0.53543 | val 2.25556
  Classification -> best τ=0.615 (val F1=0.2559)
  Directional -> Accuracy: 0.4783, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.58796 | val 0.80243
  Epoch 020 - train 0.50894 | val 1.17856
  Epoch 030 - train 0.42922 | val 1.44139
  Classification -> best τ=0.310 (val F1=0.2903)
  Directional -> Accuracy: 0.5405, MCC: 0.0000, F1: 0.7018

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.53376 | val 1.03706
  Epoch 012 - train 0.49056 | val 1.43462
  Classification -> best τ=0.540 (val F1=0.5079)
  Directional -> Accuracy: 0.5600, MCC: 0.1368, F1: 0.5000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.56451 | val 0.71092
  Epoch 015 - train 0.45557 | val 0.88360
  Classification -> best τ=0.480 (val F1=0.3994)
  Directional -> Accuracy: 0.5217, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.58872 | val 1.06059
  Epoch 014 - train 0.55227 | val 1.46464
  Classification -> best τ=0.400 (val F1=0.3149)
  Directional -> Accuracy: 0.4853, MCC: 0.0781, F1: 0.5455

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.56006 | val 0.65113
  Epoch 020 - train 0.28930 | val 2.45053
  Classification -> best τ=0.220 (val F1=0.2075)
  Directional -> Accuracy: 0.3810, MCC: -0.2582, F1: 0.5517

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.56761 | val 1.43926
  Epoch 011 - train 0.47933 | val 1.80494
  Classification -> best τ=0.640 (val F1=0.3441)
  Directional -> Accuracy: 0.6875, MCC: 0.3687, F1: 0.6512

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.57703 | val 0.76558
  Epoch 020 - train 0.47101 | val 1.18787
  Classification -> best τ=0.470 (val F1=0.2734)
  Directional -> Accuracy: 0.4493, MCC: -0.1099, F1: 0.3871

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.57884 | val 1.08776
  Epoch 018 - train 0.49535 | val 0.73484
  Classification -> best τ=0.725 (val F1=0.4059)
  Directional -> Accuracy: 0.5918, MCC: 0.1804, F1: 0.2308

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.59899 | val 1.40945
  Epoch 011 - train 0.59526 | val 1.61132
  Classification -> best τ=0.350 (val F1=0.3132)
  Directional -> Accuracy: 0.5088, MCC: 0.0000, F1: 0.6744

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.49557 | val 1.20364
  Epoch 011 - train 0.49753 | val 1.18686
  Classification -> best τ=0.450 (val F1=0.1370)
  Directional -> Accuracy: 0.5000, MCC: -0.0454, F1: 0.3226

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.60419 | val 0.87951
  Epoch 011 - train 0.60966 | val 0.68799
  Classification -> best τ=0.500 (val F1=0.3289)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.60115 | val 0.96632
  Epoch 014 - train 0.54987 | val 0.97972
  Classification -> best τ=0.610 (val F1=0.2571)
  Directional -> Accuracy: 0.5490, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.61310 | val 1.20807
  Epoch 011 - train 0.61205 | val 1.12406
  Classification -> best τ=0.770 (val F1=0.1385)
  Directional -> Accuracy: 0.4638, MCC: 0.0000, F1: 0.0000

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.55334 | val 1.44820
  Epoch 011 - train 0.61366 | val 1.41617
  Classification -> best τ=0.725 (val F1=0.0354)
  Directional -> Accuracy: 0.4138, MCC: -0.0573, F1: 0.3200

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.59858 | val 0.97371
  Epoch 011 - train 0.57587 | val 0.86960
  Classification -> best τ=0.475 (val F1=0.1909)
  Directional -> Accuracy: 0.4000, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.55097 | val 0.71102
  Epoch 012 - train 0.49879 | val 0.88745
  Classification -> best τ=0.460 (val F1=0.2846)
  Directional -> Accuracy: 0.4844, MCC: 0.1062, F1: 0.2979

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.55851 | val 1.57780
  Epoch 011 - train 0.54952 | val 1.84611
  Classification -> best τ=0.180 (val F1=0.2204)
  Directional -> Accuracy: 0.5541, MCC: 0.0000, F1: 0.7130

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.55615 | val 0.90182
  Epoch 013 - train 0.43257 | val 0.92530
  Classification -> best τ=0.365 (val F1=0.2784)
  Directional -> Accuracy: 0.6596, MCC: 0.2676, F1: 0.7838

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.60472 | val 0.98413
  Epoch 013 - train 0.59879 | val 1.10248
  Classification -> best τ=0.455 (val F1=0.2529)
  Directional -> Accuracy: 0.6000, MCC: 0.2103, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.60594 | val 0.76043
  Epoch 014 - train 0.56014 | val 1.02772
  Classification -> best τ=0.430 (val F1=0.3913)
  Directional -> Accuracy: 0.6316, MCC: 0.2487, F1: 0.6769

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.59478 | val 0.73691
  Epoch 019 - train 0.49130 | val 0.71521
  Classification -> best τ=0.450 (val F1=0.2826)
  Directional -> Accuracy: 0.5077, MCC: 0.0251, F1: 0.5429

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.57603 | val 1.15764
  Epoch 011 - train 0.49239 | val 1.42622
  Classification -> best τ=0.440 (val F1=0.4075)
  Directional -> Accuracy: 0.5091, MCC: 0.0781, F1: 0.3721

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.44581 | val 3.38325
  Epoch 011 - train 0.40531 | val 2.98884
  Classification -> best τ=0.725 (val F1=0.1890)
  Directional -> Accuracy: 0.5556, MCC: -0.1289, F1: 0.0000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.62402 | val 0.82687
  Epoch 011 - train 0.66414 | val 0.81135
  Classification -> best τ=0.525 (val F1=0.1803)
  Directional -> Accuracy: 0.5952, MCC: 0.1487, F1: 0.6792

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.55488 | val 1.50759
  Epoch 011 - train 0.51611 | val 1.41478
  Classification -> best τ=0.410 (val F1=0.3280)
  Directional -> Accuracy: 0.4464, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.49341 | val 1.03203
  Epoch 013 - train 0.46167 | val 1.51658
  Classification -> best τ=0.565 (val F1=0.3518)
  Directional -> Accuracy: 0.5750, MCC: 0.1140, F1: 0.7018

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.63098 | val 1.01780
  Epoch 011 - train 0.56877 | val 0.90018
  Classification -> best τ=0.515 (val F1=0.3501)
  Directional -> Accuracy: 0.5000, MCC: -0.0092, F1: 0.4324

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.54290 | val 1.12519
  Epoch 011 - train 0.52112 | val 1.15986
  Classification -> best τ=0.590 (val F1=0.1286)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.52683 | val 0.84585
  Epoch 011 - train 0.48326 | val 1.44578
  Classification -> best τ=0.640 (val F1=0.3917)
  Directional -> Accuracy: 0.4694, MCC: 0.0000, F1: 0.0000

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.56251 | val 1.05070
  Epoch 011 - train 0.60804 | val 1.21889
  Classification -> best τ=0.485 (val F1=0.3534)
  Directional -> Accuracy: 0.5139, MCC: 0.1992, F1: 0.2553

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.51384 | val 1.49264
  Epoch 011 - train 0.52973 | val 1.42242
  Classification -> best τ=0.380 (val F1=0.2717)
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.56670 | val 1.42113
  Epoch 011 - train 0.56725 | val 1.68767
  Classification -> best τ=0.465 (val F1=0.1203)
  Directional -> Accuracy: 0.5758, MCC: 0.0000, F1: 0.7308

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.49638 | val 3.52431
  Epoch 011 - train 0.37993 | val 4.52405
  Classification -> best τ=0.430 (val F1=0.2464)
  Directional -> Accuracy: 0.5714, MCC: 0.1357, F1: 0.6538

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.55766 | val 1.13405
  Epoch 011 - train 0.52932 | val 1.12646
  Classification -> best τ=0.455 (val F1=0.2110)
  Directional -> Accuracy: 0.5714, MCC: 0.2244, F1: 0.6571

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.50026 | val 1.35580
  Epoch 011 - train 0.51461 | val 1.38342
  Classification -> best τ=0.490 (val F1=0.2118)
  Directional -> Accuracy: 0.5652, MCC: -0.1709, F1: 0.7222

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.54614 | val 0.72168
  Epoch 014 - train 0.51434 | val 0.84679
  Classification -> best τ=0.520 (val F1=0.4011)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.56677 | val 1.57708
  Epoch 011 - train 0.56734 | val 1.60185
  Classification -> best τ=0.375 (val F1=0.2112)
  Directional -> Accuracy: 0.4865, MCC: 0.0000, F1: 0.6545

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.57967 | val 0.69372
  Epoch 011 - train 0.50178 | val 0.68639
  Classification -> best τ=0.450 (val F1=0.4842)
  Directional -> Accuracy: 0.5111, MCC: 0.0000, F1: 0.6765

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.43478 | val 2.32518
  Epoch 011 - train 0.37842 | val 3.10983
  Classification -> best τ=0.500 (val F1=0.3015)
  Directional -> Accuracy: 0.5952, MCC: 0.1803, F1: 0.7385

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.57141 | val 1.60409
  Epoch 020 - train 0.30635 | val 0.95672
  Epoch 022 - train 0.40367 | val 2.19119
  Classification -> best τ=0.915 (val F1=0.4478)
  Directional -> Accuracy: 0.5000, MCC: 0.2928, F1: 0.6000

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.60836 | val 1.40694
  Epoch 011 - train 0.61459 | val 1.14106
  Classification -> best τ=0.460 (val F1=0.2036)
  Directional -> Accuracy: 0.4727, MCC: 0.0199, F1: 0.2162

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.47883 | val 2.37150
  Epoch 011 - train 0.48371 | val 2.20290
  Classification -> best τ=0.715 (val F1=0.1694)
  Directional -> Accuracy: 0.5179, MCC: 0.0000, F1: 0.0000

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.63814 | val 0.84124
  Epoch 011 - train 0.62854 | val 1.19202
  Classification -> best τ=0.415 (val F1=0.2351)
  Directional -> Accuracy: 0.5094, MCC: 0.0000, F1: 0.6750

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.54141 | val 3.61606
  Epoch 011 - train 0.52812 | val 6.48702
  Classification -> best τ=0.875 (val F1=0.0465)
  Directional -> Accuracy: 0.5091, MCC: 0.0297, F1: 0.4706

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.60649 | val 0.71767

[I 2026-02-22 12:55:51,761] Trial 182 finished with value: 0.2700187180805785 and parameters: {'feature_set': 'sector', 'model_type': 'BiGRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.4, 'batch_size': 16, 'learning_rate': 0.004856047875956738, 'weight_decay': 2.199540498990518e-05, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 1.3051132652132624, 'early_stopping_min_delta': 0.0001733466584959931}. Best is trial 159 with value: 0.297766251520741.

  Epoch 014 - train 0.57759 | val 0.83658
  Classification -> best τ=0.450 (val F1=0.3083)
  Directional -> Accuracy: 0.5500, MCC: 0.0953, F1: 0.4906

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2700187180805785
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.63197 | val 1.19083
  Epoch 011 - train 0.64610 | val 0.70566
  Classification -> best τ=0.590 (val F1=0.2510)
  Directional -> Accuracy: 0.5789, MCC: 0.1212, F1: 0.3846

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.61154 | val 0.94354
  Epoch 011 - train 0.58569 | val 0.98648
  Classification -> best τ=0.525 (val F1=0.1273)
  Directional -> Accuracy: 0.6000, MCC: 0.1297, F1: 0.7188

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.62801 | val 1.29433
  Epoch 013 - train 0.60355 | val 1.29900
  Classification -> best τ=0.440 (val F1=0.2779)
  Directional -> Accuracy: 0.5217, MCC: 0.0948, F1: 0.3125

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.60306 | val 1.09958
  Epoch 015 - train 0.62338 | val 1.05057
  Classification -> best τ=0.325 (val F1=0.1745)
  Directional -> Accuracy: 0.5405, MCC: 0.0000, F1: 0.7018

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.60705 | val 0.65145
  Epoch 013 - train 0.53052 | val 0.70187
  Classification -> best τ=0.580 (val F1=0.4611)
  Directional -> Accuracy: 0.6800, MCC: 0.3677, F1: 0.6667

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.58824 | val 0.67353
  Epoch 019 - train 0.44484 | val 0.74831
  Classification -> best τ=0.690 (val F1=0.3525)
  Directional -> Accuracy: 0.5217, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.70695 | val 0.89067
  Epoch 011 - train 0.64690 | val 0.80356
  Classification -> best τ=0.490 (val F1=0.2648)
  Directional -> Accuracy: 0.5147, MCC: 0.1280, F1: 0.5600

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.60467 | val 2.06655
  Epoch 020 - train 0.43191 | val 3.62550
  Epoch 022 - train 0.44634 | val 1.12864
  Classification -> best τ=0.685 (val F1=0.3632)
  Directional -> Accuracy: 0.5000, MCC: -0.0280, F1: 0.4000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.62400 | val 1.24542
  Epoch 012 - train 0.66870 | val 1.72631
  Classification -> best τ=0.540 (val F1=0.2784)
  Directional -> Accuracy: 0.6458, MCC: 0.2711, F1: 0.5641

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.63959 | val 0.94948
  Epoch 011 - train 0.63029 | val 0.93474
  Classification -> best τ=0.340 (val F1=0.2778)
  Directional -> Accuracy: 0.5217, MCC: 0.1305, F1: 0.5823

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.62541 | val 0.93049
  Epoch 012 - train 0.62533 | val 0.89452
  Classification -> best τ=0.500 (val F1=0.3007)
  Directional -> Accuracy: 0.5714, MCC: 0.1005, F1: 0.2759

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.61866 | val 1.38476
  Epoch 011 - train 0.62991 | val 2.04775
  Classification -> best τ=0.445 (val F1=0.1843)
  Directional -> Accuracy: 0.5263, MCC: 0.1360, F1: 0.6824

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.55625 | val 1.82099
  Epoch 011 - train 0.49355 | val 2.35346
  Classification -> best τ=0.385 (val F1=0.3922)
  Directional -> Accuracy: 0.5476, MCC: 0.1513, F1: 0.6122

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.67024 | val 0.61927
  Epoch 012 - train 0.62348 | val 0.81770
  Classification -> best τ=0.420 (val F1=0.3864)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.60156 | val 0.80265
  Epoch 013 - train 0.60205 | val 0.78013
  Classification -> best τ=0.575 (val F1=0.1455)
  Directional -> Accuracy: 0.5490, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.66234 | val 0.84810
  Epoch 011 - train 0.60925 | val 0.91848
  Classification -> best τ=0.655 (val F1=0.1385)
  Directional -> Accuracy: 0.4638, MCC: 0.0000, F1: 0.0000

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.60203 | val 1.50273
  Epoch 011 - train 0.62914 | val 1.42533
  Classification -> best τ=0.470 (val F1=0.0811)
  Directional -> Accuracy: 0.6552, MCC: 0.2025, F1: 0.7674

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.57976 | val 0.87522
  Epoch 011 - train 0.63021 | val 0.88222
  Classification -> best τ=0.370 (val F1=0.1682)
  Directional -> Accuracy: 0.4000, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.59526 | val 0.72273
  Epoch 011 - train 0.59640 | val 0.76023
  Classification -> best τ=0.370 (val F1=0.2843)
  Directional -> Accuracy: 0.5938, MCC: 0.1850, F1: 0.6286

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.56013 | val 1.23427
  Epoch 011 - train 0.63185 | val 1.13645
  Classification -> best τ=0.505 (val F1=0.3153)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.57184 | val 0.76676
  Epoch 011 - train 0.57699 | val 0.98784
  Classification -> best τ=0.490 (val F1=0.0872)
  Directional -> Accuracy: 0.5745, MCC: -0.0834, F1: 0.7222

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.62522 | val 0.80608
  Epoch 011 - train 0.59132 | val 0.86959
  Classification -> best τ=0.495 (val F1=0.2141)
  Directional -> Accuracy: 0.5077, MCC: 0.0000, F1: 0.6735

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.67657 | val 0.90173
  Epoch 017 - train 0.60788 | val 0.89417
  Classification -> best τ=0.580 (val F1=0.4376)
  Directional -> Accuracy: 0.5263, MCC: 0.0887, F1: 0.4906

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.63589 | val 0.80846
  Epoch 012 - train 0.61832 | val 0.76375
  Classification -> best τ=0.595 (val F1=0.1415)
  Directional -> Accuracy: 0.5538, MCC: 0.1051, F1: 0.2927

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.61215 | val 0.89872
  Epoch 012 - train 0.61275 | val 1.05503
  Classification -> best τ=0.470 (val F1=0.4903)
  Directional -> Accuracy: 0.5273, MCC: 0.1143, F1: 0.4091

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.60652 | val 3.07853
  Epoch 011 - train 0.62039 | val 3.46430
  Classification -> best τ=0.565 (val F1=0.2935)
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.5938

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.62677 | val 0.71763
  Epoch 011 - train 0.63071 | val 0.80670
  Classification -> best τ=0.425 (val F1=0.2582)
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.7273

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.62964 | val 1.05060
  Epoch 011 - train 0.62112 | val 1.37789
  Classification -> best τ=0.245 (val F1=0.1986)
  Directional -> Accuracy: 0.5536, MCC: 0.0000, F1: 0.7126

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.64201 | val 0.75120
  Epoch 011 - train 0.57489 | val 0.85819
  Classification -> best τ=0.530 (val F1=0.2403)
  Directional -> Accuracy: 0.6000, MCC: 0.2010, F1: 0.7241

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.61448 | val 0.92107
  Epoch 015 - train 0.58817 | val 3.00265
  Classification -> best τ=0.330 (val F1=0.4113)
  Directional -> Accuracy: 0.4286, MCC: -0.1376, F1: 0.4545

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.69237 | val 1.00416
  Epoch 011 - train 0.62167 | val 0.96223
  Classification -> best τ=0.450 (val F1=0.3158)
  Directional -> Accuracy: 0.4524, MCC: -0.1972, F1: 0.5965

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.53448 | val 1.09155
  Epoch 011 - train 0.57793 | val 1.18755
  Classification -> best τ=0.460 (val F1=0.3987)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.63279 | val 0.67312
  Epoch 019 - train 0.52501 | val 1.48293
  Classification -> best τ=0.635 (val F1=0.3278)
  Directional -> Accuracy: 0.4861, MCC: 0.1865, F1: 0.1395

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.57949 | val 1.47242
  Epoch 011 - train 0.60118 | val 1.43596
  Classification -> best τ=0.655 (val F1=0.1146)
  Directional -> Accuracy: 0.5116, MCC: 0.0179, F1: 0.4324

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.59840 | val 1.23774
  Epoch 011 - train 0.62393 | val 1.10457
  Classification -> best τ=0.475 (val F1=0.3298)
  Directional -> Accuracy: 0.4545, MCC: 0.1517, F1: 0.1000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.61224 | val 1.42837
  Epoch 011 - train 0.54862 | val 1.34972
  Classification -> best τ=0.490 (val F1=0.2858)
  Directional -> Accuracy: 0.6190, MCC: 0.2571, F1: 0.5789

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.56548 | val 1.10360
  Epoch 011 - train 0.61909 | val 1.23687
  Classification -> best τ=0.550 (val F1=0.2850)
  Directional -> Accuracy: 0.5714, MCC: 0.1316, F1: 0.2941

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.52374 | val 1.38688
  Epoch 012 - train 0.57732 | val 1.26425
  Classification -> best τ=0.515 (val F1=0.2832)
  Directional -> Accuracy: 0.6087, MCC: 0.0687, F1: 0.7429

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.59817 | val 0.73412
  Epoch 015 - train 0.62832 | val 0.85841
  Classification -> best τ=0.480 (val F1=0.4011)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.55648 | val 1.49796
  Epoch 011 - train 0.56045 | val 1.71883
  Classification -> best τ=0.340 (val F1=0.2479)
  Directional -> Accuracy: 0.5270, MCC: 0.2001, F1: 0.6729

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.58749 | val 0.70103
  Epoch 020 - train 0.54713 | val 0.79553
  Epoch 022 - train 0.61431 | val 0.97595
  Classification -> best τ=0.405 (val F1=0.4632)
  Directional -> Accuracy: 0.5333, MCC: 0.0786, F1: 0.6667

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.58217 | val 1.51777
  Epoch 011 - train 0.56261 | val 2.12362
  Classification -> best τ=0.600 (val F1=0.2408)
  Directional -> Accuracy: 0.5238, MCC: 0.0000, F1: 0.6154

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.60988 | val 0.64724
  Epoch 020 - train 0.50517 | val 0.50685
  Epoch 030 - train 0.41410 | val 1.01593
  Classification -> best τ=0.390 (val F1=0.7162)
  Directional -> Accuracy: 0.3958, MCC: 0.1130, F1: 0.5538

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.64988 | val 1.33367
  Epoch 011 - train 0.66503 | val 1.29815
  Classification -> best τ=0.585 (val F1=0.2036)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.59584 | val 2.56347
  Epoch 011 - train 0.54488 | val 1.96947
  Classification -> best τ=0.625 (val F1=0.2774)
  Directional -> Accuracy: 0.4107, MCC: -0.1929, F1: 0.5352

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.64827 | val 0.86339
  Epoch 011 - train 0.66319 | val 0.88030
  Classification -> best τ=0.465 (val F1=0.1824)
  Directional -> Accuracy: 0.6226, MCC: 0.2808, F1: 0.7059

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.63493 | val 2.48286
  Epoch 011 - train 0.59411 | val 2.88648
  Classification -> best τ=0.775 (val F1=0.0817)
  Directional -> Accuracy: 0.5273, MCC: 0.0481, F1: 0.5667

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.64647 | val 0.70241

[I 2026-02-22 12:58:19,952] Trial 183 finished with value: 0.28052652536519046 and parameters: {'feature_set': 'sector', 'model_type': 'BiGRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.7000000000000001, 'batch_size': 16, 'learning_rate': 0.0037885730516488705, 'weight_decay': 1.6145073188433757e-05, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 1.2012867245542251, 'early_stopping_min_delta': 2.893645374111592e-05}. Best is trial 159 with value: 0.297766251520741.

  Epoch 017 - train 0.60862 | val 0.80361
  Classification -> best τ=0.400 (val F1=0.3128)
  Directional -> Accuracy: 0.5167, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.28052652536519046
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.67624 | val 0.88498
  Epoch 016 - train 0.66726 | val 0.97040
  Classification -> best τ=0.625 (val F1=0.2919)
  Directional -> Accuracy: 0.5395, MCC: -0.1039, F1: 0.0000

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.62543 | val 0.94838
  Epoch 011 - train 0.60541 | val 0.84247
  Classification -> best τ=0.490 (val F1=0.1160)
  Directional -> Accuracy: 0.5778, MCC: 0.0000, F1: 0.7324

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.66980 | val 0.95763
  Epoch 011 - train 0.68908 | val 0.94398
  Classification -> best τ=0.550 (val F1=0.2727)
  Directional -> Accuracy: 0.4783, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.65161 | val 1.13006
  Epoch 020 - train 0.61307 | val 0.89607
  Epoch 021 - train 0.57284 | val 0.91255
  Classification -> best τ=0.335 (val F1=0.2920)
  Directional -> Accuracy: 0.5405, MCC: 0.0000, F1: 0.7018

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.64477 | val 0.93558
  Epoch 015 - train 0.58066 | val 0.78671
  Classification -> best τ=0.735 (val F1=0.4414)
  Directional -> Accuracy: 0.6000, MCC: 0.2202, F1: 0.5455

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.69502 | val 0.73636
  Epoch 012 - train 0.65498 | val 0.75740
  Classification -> best τ=0.550 (val F1=0.2720)
  Directional -> Accuracy: 0.5217, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.67131 | val 0.77070
  Epoch 015 - train 0.61673 | val 0.97527
  Classification -> best τ=0.565 (val F1=0.2727)
  Directional -> Accuracy: 0.5147, MCC: 0.1667, F1: 0.5823

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.70849 | val 1.11419
  Epoch 011 - train 0.63195 | val 1.02987
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.71539 | val 1.69669
  Epoch 012 - train 0.59186 | val 1.75283
  Classification -> best τ=0.475 (val F1=0.2925)
  Directional -> Accuracy: 0.4375, MCC: 0.0000, F1: 0.6087

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.67110 | val 1.13962
  Epoch 011 - train 0.64351 | val 1.27701
  Classification -> best τ=0.290 (val F1=0.2620)
  Directional -> Accuracy: 0.4203, MCC: 0.0000, F1: 0.5918

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.69805 | val 0.71399
  Epoch 016 - train 0.69080 | val 1.08473
  Classification -> best τ=0.710 (val F1=0.3590)
  Directional -> Accuracy: 0.6122, MCC: 0.2379, F1: 0.2963

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.70684 | val 1.05561
  Epoch 011 - train 0.68602 | val 0.97502
  Classification -> best τ=0.490 (val F1=0.1528)
  Directional -> Accuracy: 0.6140, MCC: 0.3102, F1: 0.7179

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.56919 | val 1.73501
  Epoch 011 - train 0.57875 | val 1.97229
  Classification -> best τ=0.480 (val F1=0.1991)
  Directional -> Accuracy: 0.4762, MCC: -0.0026, F1: 0.5600

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.66800 | val 0.67081
  Epoch 020 - train 0.62787 | val 0.61579
  Epoch 028 - train 0.54892 | val 0.68192
  Classification -> best τ=0.455 (val F1=0.4543)
  Directional -> Accuracy: 0.4667, MCC: -0.1857, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.66229 | val 0.83684
  Epoch 011 - train 0.63462 | val 1.23586
  Classification -> best τ=0.430 (val F1=0.2084)
  Directional -> Accuracy: 0.6275, MCC: 0.3219, F1: 0.2963

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.67177 | val 1.00886
  Epoch 011 - train 0.61323 | val 0.99697
  Classification -> best τ=0.415 (val F1=0.1823)
  Directional -> Accuracy: 0.5217, MCC: -0.0237, F1: 0.6667

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.68019 | val 1.23406
  Epoch 011 - train 0.67737 | val 0.87393
  Classification -> best τ=0.500 (val F1=0.1521)
  Directional -> Accuracy: 0.4655, MCC: 0.1387, F1: 0.3111

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.65999 | val 0.89473
  Epoch 011 - train 0.61846 | val 0.93093
  Classification -> best τ=0.480 (val F1=0.2247)
  Directional -> Accuracy: 0.4667, MCC: 0.1340, F1: 0.2593

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.63369 | val 0.84142
  Epoch 012 - train 0.64620 | val 0.83311
  Classification -> best τ=0.775 (val F1=0.2234)
  Directional -> Accuracy: 0.4219, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.59501 | val 1.52749
  Epoch 011 - train 0.59966 | val 1.30368
  Classification -> best τ=0.535 (val F1=0.2597)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.67035 | val 0.71112
  Epoch 014 - train 0.65665 | val 1.09851
  Classification -> best τ=0.615 (val F1=0.2398)
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.69376 | val 0.95637
  Epoch 011 - train 0.65578 | val 0.92357
  Classification -> best τ=0.455 (val F1=0.2818)
  Directional -> Accuracy: 0.5077, MCC: 0.0000, F1: 0.6735

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.68784 | val 0.64087
  Epoch 020 - train 0.61708 | val 0.59408
  Epoch 030 - train 0.56359 | val 1.20316
  Classification -> best τ=0.415 (val F1=0.4239)
  Directional -> Accuracy: 0.5439, MCC: -0.1181, F1: 0.7045

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.70693 | val 0.89556
  Epoch 011 - train 0.64986 | val 1.13740
  Classification -> best τ=0.430 (val F1=0.1348)
  Directional -> Accuracy: 0.5077, MCC: 0.0133, F1: 0.4839

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.65760 | val 0.88517
  Epoch 015 - train 0.59879 | val 0.95107
  Classification -> best τ=0.605 (val F1=0.5294)
  Directional -> Accuracy: 0.6000, MCC: 0.2476, F1: 0.5417

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.61183 | val 1.25160
  Epoch 011 - train 0.67941 | val 1.01418
  Classification -> best τ=0.510 (val F1=0.1890)
  Directional -> Accuracy: 0.5778, MCC: 0.0000, F1: 0.0000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.64340 | val 1.09031
  Epoch 015 - train 0.64609 | val 0.74191
  Classification -> best τ=0.575 (val F1=0.2402)
  Directional -> Accuracy: 0.4762, MCC: 0.0786, F1: 0.2667

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.63457 | val 0.84878
  Epoch 012 - train 0.61333 | val 1.17060
  Classification -> best τ=0.230 (val F1=0.2315)
  Directional -> Accuracy: 0.5536, MCC: 0.1340, F1: 0.5283

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.65223 | val 0.97897
  Epoch 014 - train 0.62157 | val 0.89567
  Classification -> best τ=0.435 (val F1=0.3278)
  Directional -> Accuracy: 0.5750, MCC: 0.1240, F1: 0.7119

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.69400 | val 1.34900
  Epoch 011 - train 0.65938 | val 1.31988
  Classification -> best τ=0.555 (val F1=0.3501)
  Directional -> Accuracy: 0.5238, MCC: 0.0413, F1: 0.4737

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.72400 | val 1.04451
  Epoch 011 - train 0.70574 | val 0.92289
  Classification -> best τ=0.585 (val F1=0.1286)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.59697 | val 0.81275
  Epoch 011 - train 0.63359 | val 0.90905
  Classification -> best τ=0.530 (val F1=0.2388)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.65438 | val 0.88365
  Epoch 016 - train 0.59944 | val 1.01383
  Classification -> best τ=0.175 (val F1=0.2774)
  Directional -> Accuracy: 0.5556, MCC: 0.0000, F1: 0.7143

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.62882 | val 1.61562
  Epoch 011 - train 0.61137 | val 1.42484
  Classification -> best τ=0.475 (val F1=0.2324)
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.62450 | val 1.03953
  Epoch 011 - train 0.64053 | val 0.99843
  Classification -> best τ=0.375 (val F1=0.3490)
  Directional -> Accuracy: 0.6061, MCC: 0.2406, F1: 0.6061

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.67053 | val 1.81992
  Epoch 012 - train 0.57322 | val 2.61775
  Classification -> best τ=0.440 (val F1=0.2858)
  Directional -> Accuracy: 0.6190, MCC: 0.2364, F1: 0.6364

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.59001 | val 1.22942
  Epoch 011 - train 0.69089 | val 1.28520
  Classification -> best τ=0.445 (val F1=0.2530)
  Directional -> Accuracy: 0.4286, MCC: -0.1247, F1: 0.5429

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.66613 | val 0.85165
  Epoch 011 - train 0.60751 | val 0.99437
  Classification -> best τ=0.510 (val F1=0.2474)
  Directional -> Accuracy: 0.6087, MCC: 0.0000, F1: 0.7568

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.65400 | val 0.77044
  Epoch 020 - train 0.56644 | val 0.67143
  Epoch 022 - train 0.59590 | val 0.84431
  Classification -> best τ=0.230 (val F1=0.4973)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.58114 | val 1.16045
  Epoch 011 - train 0.58696 | val 1.32788
  Classification -> best τ=0.355 (val F1=0.3052)
  Directional -> Accuracy: 0.5270, MCC: 0.2001, F1: 0.6729

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.64709 | val 0.66017
  Epoch 020 - train 0.61533 | val 0.69015
  Epoch 021 - train 0.66124 | val 0.72961
  Classification -> best τ=0.405 (val F1=0.4989)
  Directional -> Accuracy: 0.5111, MCC: 0.0000, F1: 0.6765

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.62953 | val 0.77921
  Epoch 011 - train 0.65248 | val 0.81786
  Classification -> best τ=0.540 (val F1=0.4082)
  Directional -> Accuracy: 0.5476, MCC: -0.0212, F1: 0.6885

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.69748 | val 0.76833
  Epoch 018 - train 0.54979 | val 0.71332
  Classification -> best τ=0.680 (val F1=0.3154)
  Directional -> Accuracy: 0.5208, MCC: 0.3201, F1: 0.6102

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.68948 | val 1.11303
  Epoch 011 - train 0.65593 | val 1.22150
  Classification -> best τ=0.460 (val F1=0.1884)
  Directional -> Accuracy: 0.5818, MCC: 0.1491, F1: 0.7089

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.63068 | val 2.27558
  Epoch 011 - train 0.62667 | val 2.22058
  Classification -> best τ=0.580 (val F1=0.2696)
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.6506

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.67817 | val 0.74706
  Epoch 013 - train 0.67317 | val 0.81634
  Classification -> best τ=0.420 (val F1=0.2521)
  Directional -> Accuracy: 0.5660, MCC: 0.2496, F1: 0.7013

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.65321 | val 1.75345
  Epoch 011 - train 0.59212 | val 1.64629
  Classification -> best τ=0.665 (val F1=0.1186)
  Directional -> Accuracy: 0.5091, MCC: 0.0452, F1: 0.4000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.64832 | val 0.73015

[I 2026-02-22 13:01:06,378] Trial 184 finished with value: 0.272219966522761 and parameters: {'feature_set': 'sector', 'model_type': 'BiGRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.8, 'batch_size': 16, 'learning_rate': 0.003091802203322695, 'weight_decay': 1.568522703847628e-05, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 1.223845134808306, 'early_stopping_min_delta': 0.0006508840831123076}. Best is trial 159 with value: 0.297766251520741.

  Epoch 015 - train 0.65919 | val 0.78161
  Classification -> best τ=0.360 (val F1=0.3234)
  Directional -> Accuracy: 0.5167, MCC: 0.0149, F1: 0.2564

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.272219966522761
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'emotion_anger', 'emotion_disgust', 'emotion_fear', 'emotion_joy', 'emotion_neutral', 'emotion_sadness', 'emotion_surprize', 'emotion_anger_pct', 'emotion_disgust_pct', 'emotion_fear_pct', 'emotion_joy_pct', 'emotion_neutral_pct', 'emotion_sadness_pct', 'emotion_surprize_pct']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.57352 | val 0.81933
  Epoch 013 - train 0.52912 | val 0.93919
  Classification -> best τ=0.615 (val F1=0.2799)
  Directional -> Accuracy: 0.5789, MCC: 0.1357, F1: 0.4839

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.51072 | val 1.82864
  Epoch 011 - train 0.48082 | val 1.49617
  Classification -> best τ=0.535 (val F1=0.0492)
  Directional -> Accuracy: 0.6000, MCC: 0.1591, F1: 0.6786

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.61722 | val 1.65250
  Epoch 015 - train 0.47069 | val 1.38134
  Classification -> best τ=0.580 (val F1=0.4245)
  Directional -> Accuracy: 0.3913, MCC: -0.3223, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.57339 | val 1.65164
  Epoch 011 - train 0.55246 | val 1.96370
  Classification -> best τ=0.335 (val F1=0.2701)
  Directional -> Accuracy: 0.5405, MCC: 0.0000, F1: 0.7018

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.44214 | val 1.01544
  Epoch 013 - train 0.41507 | val 1.40254
  Classification -> best τ=0.635 (val F1=0.3440)
  Directional -> Accuracy: 0.6200, MCC: 0.2670, F1: 0.5581

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.40635 | val 1.94423
  Epoch 011 - train 0.39210 | val 2.70766
  Classification -> best τ=0.585 (val F1=0.2204)
  Directional -> Accuracy: 0.5435, MCC: 0.1557, F1: 0.0870

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.54909 | val 1.09705
  Epoch 011 - train 0.55909 | val 1.19955
  Classification -> best τ=0.540 (val F1=0.2727)
  Directional -> Accuracy: 0.5735, MCC: 0.0925, F1: 0.4314

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.49846 | val 4.25278
  Epoch 011 - train 0.40827 | val 3.45283
  Classification -> best τ=0.525 (val F1=0.3689)
  Directional -> Accuracy: 0.6429, MCC: 0.2759, F1: 0.3478

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.50425 | val 1.30139
  Epoch 011 - train 0.43603 | val 1.72678
  Classification -> best τ=0.610 (val F1=0.2927)
  Directional -> Accuracy: 0.5625, MCC: 0.1782, F1: 0.6038

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.53952 | val 1.32034
  Epoch 011 - train 0.52071 | val 0.80630
  Classification -> best τ=0.350 (val F1=0.2535)
  Directional -> Accuracy: 0.3913, MCC: -0.2029, F1: 0.5625

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.49933 | val 1.39226
  Epoch 011 - train 0.53146 | val 1.54864
  Classification -> best τ=0.560 (val F1=0.2484)
  Directional -> Accuracy: 0.5510, MCC: 0.0212, F1: 0.0833

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.46378 | val 1.72781
  Epoch 011 - train 0.54580 | val 2.45863
  Classification -> best τ=0.540 (val F1=0.1536)
  Directional -> Accuracy: 0.5789, MCC: 0.1803, F1: 0.4783

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.45739 | val 1.60364
  Epoch 011 - train 0.46492 | val 1.64050
  Classification -> best τ=0.255 (val F1=0.3133)
  Directional -> Accuracy: 0.4524, MCC: -0.0214, F1: 0.6102

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.56481 | val 0.77897
  Epoch 013 - train 0.52193 | val 0.94632
  Classification -> best τ=0.400 (val F1=0.3477)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.5161

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.52492 | val 0.96906
  Epoch 011 - train 0.47426 | val 0.76973
  Classification -> best τ=0.590 (val F1=0.1455)
  Directional -> Accuracy: 0.5490, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.54854 | val 0.87500
  Epoch 011 - train 0.50415 | val 0.92040
  Classification -> best τ=0.450 (val F1=0.2155)
  Directional -> Accuracy: 0.5652, MCC: 0.1171, F1: 0.6939

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.57150 | val 2.77845
  Epoch 011 - train 0.50547 | val 2.00372
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.6207, MCC: 0.0000, F1: 0.7660

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.61862 | val 0.83418
  Epoch 011 - train 0.59271 | val 0.87572
  Classification -> best τ=0.375 (val F1=0.1905)
  Directional -> Accuracy: 0.6000, MCC: 0.1315, F1: 0.6939

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.45621 | val 1.03393
  Epoch 012 - train 0.39435 | val 1.20855
  Classification -> best τ=0.540 (val F1=0.1495)
  Directional -> Accuracy: 0.4375, MCC: 0.0398, F1: 0.1000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.55813 | val 0.95743
  Epoch 011 - train 0.54479 | val 0.79016
  Classification -> best τ=0.590 (val F1=0.2902)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.49401 | val 1.06485
  Epoch 011 - train 0.46635 | val 1.15360
  Classification -> best τ=0.515 (val F1=0.2871)
  Directional -> Accuracy: 0.5532, MCC: -0.0497, F1: 0.6866

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.57047 | val 0.84684
  Epoch 011 - train 0.59741 | val 0.90324
  Classification -> best τ=0.575 (val F1=0.3107)
  Directional -> Accuracy: 0.5077, MCC: 0.0699, F1: 0.1111

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.46336 | val 1.00756
  Epoch 014 - train 0.45323 | val 0.78905
  Classification -> best τ=0.390 (val F1=0.4259)
  Directional -> Accuracy: 0.4912, MCC: -0.1880, F1: 0.6506

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.51008 | val 0.88753
  Epoch 012 - train 0.48637 | val 2.33610
  Classification -> best τ=0.550 (val F1=0.1978)
  Directional -> Accuracy: 0.5385, MCC: 0.1981, F1: 0.6667

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.48996 | val 2.25948
  Epoch 011 - train 0.56532 | val 1.97682
  Classification -> best τ=0.590 (val F1=0.2538)
  Directional -> Accuracy: 0.4364, MCC: -0.0924, F1: 0.1143

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.38801 | val 3.95877
  Epoch 011 - train 0.37810 | val 4.09269
  Classification -> best τ=0.550 (val F1=0.0105)
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.5938

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.50654 | val 0.87734
  Epoch 011 - train 0.41650 | val 0.80046
  Classification -> best τ=0.470 (val F1=0.3184)
  Directional -> Accuracy: 0.5238, MCC: 0.1217, F1: 0.4444

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.49895 | val 1.70466
  Epoch 011 - train 0.55748 | val 2.06292
  Classification -> best τ=0.495 (val F1=0.2096)
  Directional -> Accuracy: 0.4464, MCC: -0.0207, F1: 0.0606

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.41732 | val 1.58822
  Epoch 011 - train 0.37556 | val 2.03037
  Classification -> best τ=0.505 (val F1=0.2223)
  Directional -> Accuracy: 0.6000, MCC: 0.1846, F1: 0.6522

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.48384 | val 2.19558
  Epoch 012 - train 0.38205 | val 2.88261
  Classification -> best τ=0.645 (val F1=0.2271)
  Directional -> Accuracy: 0.5714, MCC: 0.1386, F1: 0.4000

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.44706 | val 2.17249
  Epoch 011 - train 0.44375 | val 3.14929
  Classification -> best τ=0.530 (val F1=0.1195)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.47486 | val 1.08496
  Epoch 011 - train 0.46923 | val 1.39292
  Classification -> best τ=0.600 (val F1=0.2399)
  Directional -> Accuracy: 0.4490, MCC: -0.1535, F1: 0.0000

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.56649 | val 0.83844
  Epoch 011 - train 0.54676 | val 1.01882
  Classification -> best τ=0.570 (val F1=0.2968)
  Directional -> Accuracy: 0.4306, MCC: -0.1327, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.49121 | val 2.58442
  Epoch 011 - train 0.44981 | val 3.90053
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.56659 | val 1.17480
  Epoch 011 - train 0.53280 | val 1.36316
  Classification -> best τ=0.380 (val F1=0.2972)
  Directional -> Accuracy: 0.6212, MCC: 0.2778, F1: 0.6154

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.39847 | val 1.46414
  Epoch 012 - train 0.28006 | val 1.49540
  Classification -> best τ=0.400 (val F1=0.3218)
  Directional -> Accuracy: 0.5714, MCC: 0.1589, F1: 0.5263

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.55382 | val 0.87352
  Epoch 011 - train 0.51776 | val 0.97988
  Classification -> best τ=0.445 (val F1=0.2804)
  Directional -> Accuracy: 0.5357, MCC: 0.0961, F1: 0.5806

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.43534 | val 1.22777
  Epoch 011 - train 0.39011 | val 1.72914
  Classification -> best τ=0.430 (val F1=0.2800)
  Directional -> Accuracy: 0.6087, MCC: 0.0000, F1: 0.7568

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.47653 | val 1.14371
  Epoch 012 - train 0.32846 | val 0.92853
  Classification -> best τ=0.490 (val F1=0.4011)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.55950 | val 1.96582
  Epoch 012 - train 0.46458 | val 2.17442
  Classification -> best τ=0.440 (val F1=0.2884)
  Directional -> Accuracy: 0.5000, MCC: 0.0375, F1: 0.6408

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.52282 | val 1.18176
  Epoch 013 - train 0.51892 | val 1.24882
  Classification -> best τ=0.455 (val F1=0.2562)
  Directional -> Accuracy: 0.4444, MCC: -0.2043, F1: 0.6032

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.39502 | val 1.98843
  Epoch 012 - train 0.31436 | val 2.00863
  Classification -> best τ=0.490 (val F1=0.3563)
  Directional -> Accuracy: 0.6429, MCC: 0.2759, F1: 0.7541

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.39785 | val 1.04547
  Epoch 011 - train 0.45481 | val 1.84667
  Classification -> best τ=0.640 (val F1=0.1371)
  Directional -> Accuracy: 0.5417, MCC: 0.0222, F1: 0.3889

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.60065 | val 1.22696
  Epoch 012 - train 0.48468 | val 1.06541
  Classification -> best τ=0.595 (val F1=0.2771)
  Directional -> Accuracy: 0.4727, MCC: 0.0090, F1: 0.2564

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.53226 | val 1.77460
  Epoch 011 - train 0.43932 | val 2.56708
  Classification -> best τ=0.320 (val F1=0.0292)
  Directional -> Accuracy: 0.5179, MCC: 0.0875, F1: 0.6400

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.56120 | val 0.93528
  Epoch 011 - train 0.46833 | val 0.93881
  Classification -> best τ=0.425 (val F1=0.2351)
  Directional -> Accuracy: 0.5094, MCC: 0.0000, F1: 0.6750

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.56347 | val 3.79914
  Epoch 011 - train 0.44959 | val 4.84435
  Classification -> best τ=0.800 (val F1=0.2111)
  Directional -> Accuracy: 0.5273, MCC: 0.0106, F1: 0.6829

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.57229 | val 0.77862

[I 2026-02-22 13:03:24,352] Trial 185 finished with value: 0.24302218520622157 and parameters: {'feature_set': 'emotion', 'model_type': 'BiGRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.6000000000000001, 'batch_size': 16, 'learning_rate': 0.003923018675174084, 'weight_decay': 1.2408549118064139e-05, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 1.1949689656920288, 'early_stopping_min_delta': 0.0003600457595700998}. Best is trial 159 with value: 0.297766251520741.

  Epoch 017 - train 0.52366 | val 0.94623
  Classification -> best τ=0.585 (val F1=0.3448)
  Directional -> Accuracy: 0.5167, MCC: 0.0089, F1: 0.1212

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.24302218520622157
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.64487 | val 0.84554
  Epoch 011 - train 0.65439 | val 0.71048
  Classification -> best τ=0.440 (val F1=0.1635)
  Directional -> Accuracy: 0.6053, MCC: 0.1858, F1: 0.4828

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.54950 | val 0.95100
  Epoch 011 - train 0.51590 | val 1.10489
  Classification -> best τ=0.420 (val F1=0.1842)
  Directional -> Accuracy: 0.5778, MCC: 0.0000, F1: 0.7324

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.64084 | val 1.12996
  Epoch 011 - train 0.63601 | val 1.71077
  Classification -> best τ=0.375 (val F1=0.3135)
  Directional -> Accuracy: 0.6087, MCC: 0.2496, F1: 0.7097

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.62637 | val 1.47803
  Epoch 019 - train 0.54734 | val 1.61394
  Classification -> best τ=0.450 (val F1=0.1537)
  Directional -> Accuracy: 0.4595, MCC: -0.0882, F1: 0.5000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.60981 | val 1.75332
  Epoch 012 - train 0.52088 | val 2.64364
  Classification -> best τ=0.590 (val F1=0.4602)
  Directional -> Accuracy: 0.4800, MCC: -0.0175, F1: 0.2353

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.53321 | val 0.69864
  Epoch 020 - train 0.43762 | val 0.87571
  Epoch 026 - train 0.35030 | val 1.19457
  Classification -> best τ=0.415 (val F1=0.4575)
  Directional -> Accuracy: 0.5217, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.63158 | val 1.52581
  Epoch 011 - train 0.64757 | val 1.75956
  Classification -> best τ=0.335 (val F1=0.3051)
  Directional -> Accuracy: 0.3971, MCC: 0.0000, F1: 0.5684

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.57049 | val 0.62064
  Epoch 020 - train 0.48321 | val 0.73752
  Epoch 022 - train 0.51736 | val 0.57626
  Classification -> best τ=0.515 (val F1=0.5247)
  Directional -> Accuracy: 0.5238, MCC: 0.0694, F1: 0.5238

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.64592 | val 1.67305
  Epoch 011 - train 0.64676 | val 1.20741
  Classification -> best τ=0.495 (val F1=0.1875)
  Directional -> Accuracy: 0.6875, MCC: 0.3687, F1: 0.6512

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.62770 | val 0.75652
  Epoch 020 - train 0.58067 | val 0.82929
  Epoch 028 - train 0.51413 | val 1.75064
  Classification -> best τ=0.585 (val F1=0.3141)
  Directional -> Accuracy: 0.5072, MCC: 0.1047, F1: 0.5750

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.66028 | val 0.81831
  Epoch 015 - train 0.59822 | val 1.00103
  Classification -> best τ=0.505 (val F1=0.3939)
  Directional -> Accuracy: 0.6531, MCC: 0.3136, F1: 0.4516

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.68346 | val 1.19538
  Epoch 013 - train 0.60823 | val 1.19605
  Classification -> best τ=0.395 (val F1=0.2157)
  Directional -> Accuracy: 0.5088, MCC: 0.0000, F1: 0.6744

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.52135 | val 1.13069
  Epoch 011 - train 0.58915 | val 1.77629
  Classification -> best τ=0.470 (val F1=0.2466)
  Directional -> Accuracy: 0.3571, MCC: -0.2901, F1: 0.4906

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.63861 | val 0.86694
  Epoch 011 - train 0.66964 | val 0.71180
  Classification -> best τ=0.355 (val F1=0.2926)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.61981 | val 0.68741
  Epoch 020 - train 0.60413 | val 0.76625
  Classification -> best τ=0.640 (val F1=0.2571)
  Directional -> Accuracy: 0.5490, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.66762 | val 1.03806
  Epoch 016 - train 0.62346 | val 1.57228
  Classification -> best τ=0.220 (val F1=0.2795)
  Directional -> Accuracy: 0.5797, MCC: 0.2293, F1: 0.7184

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.63343 | val 0.82831
  Epoch 011 - train 0.59940 | val 0.85210
  Classification -> best τ=0.435 (val F1=0.2743)
  Directional -> Accuracy: 0.6724, MCC: 0.2773, F1: 0.7532

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.63046 | val 0.75776
  Epoch 020 - train 0.64693 | val 0.75636
  Epoch 021 - train 0.58014 | val 0.78401
  Classification -> best τ=0.530 (val F1=0.2220)
  Directional -> Accuracy: 0.4000, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.61323 | val 0.80376
  Epoch 011 - train 0.59915 | val 0.94292
  Classification -> best τ=0.430 (val F1=0.3689)
  Directional -> Accuracy: 0.5781, MCC: 0.0509, F1: 0.7158

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.62061 | val 1.64721
  Epoch 011 - train 0.60414 | val 1.77398
  Classification -> best τ=0.740 (val F1=0.2303)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.61168 | val 1.65046
  Epoch 015 - train 0.55482 | val 0.98551
  Classification -> best τ=0.565 (val F1=0.2793)
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.65874 | val 1.18957
  Epoch 011 - train 0.64000 | val 1.39300
  Classification -> best τ=0.490 (val F1=0.3343)
  Directional -> Accuracy: 0.5385, MCC: 0.1688, F1: 0.2105

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.65739 | val 0.66403
  Epoch 020 - train 0.67439 | val 0.67563
  Epoch 021 - train 0.58591 | val 0.66712
  Classification -> best τ=0.430 (val F1=0.4409)
  Directional -> Accuracy: 0.6491, MCC: 0.2777, F1: 0.7059

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.62143 | val 1.06627
  Epoch 011 - train 0.64288 | val 0.77882
  Classification -> best τ=0.470 (val F1=0.1536)
  Directional -> Accuracy: 0.4462, MCC: -0.1006, F1: 0.4857

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.62665 | val 1.01603
  Epoch 011 - train 0.62629 | val 1.13266
  Classification -> best τ=0.490 (val F1=0.2725)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.62240 | val 1.96063
  Epoch 011 - train 0.53861 | val 1.91256
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.5938

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.63323 | val 0.74550
  Epoch 012 - train 0.66267 | val 0.78200
  Classification -> best τ=0.625 (val F1=0.2582)
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.0000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.63938 | val 1.37817
  Epoch 011 - train 0.61575 | val 0.91378
  Classification -> best τ=0.405 (val F1=0.2724)
  Directional -> Accuracy: 0.5000, MCC: 0.0278, F1: 0.4615

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.56860 | val 0.89860
  Epoch 011 - train 0.66364 | val 0.91102
  Classification -> best τ=0.545 (val F1=0.0989)
  Directional -> Accuracy: 0.5750, MCC: 0.1124, F1: 0.6909

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.61499 | val 0.82560
  Epoch 014 - train 0.64129 | val 0.73456
  Classification -> best τ=0.760 (val F1=0.3501)
  Directional -> Accuracy: 0.4524, MCC: -0.1494, F1: 0.2069

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.63154 | val 0.86160
  Epoch 011 - train 0.64115 | val 0.87891
  Classification -> best τ=0.415 (val F1=0.2147)
  Directional -> Accuracy: 0.4286, MCC: -0.2150, F1: 0.5556

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.56177 | val 1.26262
  Epoch 011 - train 0.65046 | val 1.36159
  Classification -> best τ=0.550 (val F1=0.3179)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.64010 | val 0.72700
  Epoch 015 - train 0.60372 | val 1.10226
  Classification -> best τ=0.540 (val F1=0.2637)
  Directional -> Accuracy: 0.4722, MCC: 0.1512, F1: 0.0952

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.59450 | val 1.20462
  Epoch 011 - train 0.59522 | val 1.44600
  Classification -> best τ=0.405 (val F1=0.1874)
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.66679 | val 1.22472
  Epoch 011 - train 0.64800 | val 1.69386
  Classification -> best τ=0.480 (val F1=0.3068)
  Directional -> Accuracy: 0.5758, MCC: 0.0000, F1: 0.7308

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.58413 | val 1.21953
  Epoch 013 - train 0.55554 | val 2.93254
  Classification -> best τ=0.495 (val F1=0.2721)
  Directional -> Accuracy: 0.7143, MCC: 0.4404, F1: 0.7000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.57624 | val 0.88590
  Epoch 011 - train 0.61288 | val 1.26711
  Classification -> best τ=0.495 (val F1=0.2450)
  Directional -> Accuracy: 0.5179, MCC: 0.0437, F1: 0.5263

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.58979 | val 1.22584
  Epoch 017 - train 0.59571 | val 1.20387
  Classification -> best τ=0.050 (val F1=0.2118)
  Directional -> Accuracy: 0.6087, MCC: 0.0000, F1: 0.7568

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.57273 | val 0.64188
  Epoch 020 - train 0.60121 | val 0.76837
  Epoch 021 - train 0.47558 | val 0.93709
  Classification -> best τ=0.490 (val F1=0.4688)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.61787 | val 1.40505
  Epoch 011 - train 0.56034 | val 1.83006
  Classification -> best τ=0.270 (val F1=0.2944)
  Directional -> Accuracy: 0.4865, MCC: 0.0000, F1: 0.6545

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.66931 | val 0.83782
  Epoch 011 - train 0.64261 | val 0.92428
  Classification -> best τ=0.520 (val F1=0.4375)
  Directional -> Accuracy: 0.5556, MCC: 0.1266, F1: 0.6667

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.58494 | val 1.97780
  Epoch 011 - train 0.48911 | val 1.85180
  Classification -> best τ=0.545 (val F1=0.3015)
  Directional -> Accuracy: 0.5714, MCC: 0.0468, F1: 0.7097

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.58477 | val 0.75258
  Epoch 013 - train 0.53830 | val 0.89534
  Classification -> best τ=0.555 (val F1=0.1371)
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.5455

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.68535 | val 0.95506
  Epoch 015 - train 0.61857 | val 1.56265
  Classification -> best τ=0.520 (val F1=0.2036)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.63298 | val 2.26975
  Epoch 011 - train 0.61385 | val 2.01947
  Classification -> best τ=0.665 (val F1=0.3111)
  Directional -> Accuracy: 0.4643, MCC: -0.1073, F1: 0.2500

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.68603 | val 0.75082
  Epoch 014 - train 0.67498 | val 0.96777
  Classification -> best τ=0.755 (val F1=0.1668)
  Directional -> Accuracy: 0.4906, MCC: 0.0000, F1: 0.0000

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.63651 | val 2.91107
  Epoch 012 - train 0.64900 | val 2.35299
  Classification -> best τ=0.735 (val F1=0.1881)
  Directional -> Accuracy: 0.5273, MCC: 0.0000, F1: 0.6905

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.69816 | val 0.70476

[I 2026-02-22 13:06:08,192] Trial 186 finished with value: 0.2728320862524969 and parameters: {'feature_set': 'sector', 'model_type': 'BiGRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.7000000000000001, 'batch_size': 16, 'learning_rate': 0.006635700604723566, 'weight_decay': 7.716484569128008e-07, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 0.9790884424389805, 'early_stopping_min_delta': 0.00014343616988366726}. Best is trial 159 with value: 0.297766251520741.

  Epoch 014 - train 0.63417 | val 0.69750
  Classification -> best τ=0.590 (val F1=0.2623)
  Directional -> Accuracy: 0.5167, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2728320862524969
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sentiment']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.61176 | val 0.90494
  Epoch 014 - train 0.59961 | val 1.01115
  Classification -> best τ=0.420 (val F1=0.2771)
  Directional -> Accuracy: 0.6184, MCC: 0.2709, F1: 0.6420

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.60108 | val 0.74463
  Epoch 011 - train 0.61609 | val 0.75153
  Classification -> best τ=0.380 (val F1=0.0900)
  Directional -> Accuracy: 0.5778, MCC: 0.0000, F1: 0.7324

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.63515 | val 0.73080
  Epoch 011 - train 0.63987 | val 0.68960
  Classification -> best τ=0.435 (val F1=0.3458)
  Directional -> Accuracy: 0.6304, MCC: 0.3213, F1: 0.7302

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.64504 | val 0.80038
  Epoch 012 - train 0.63755 | val 1.07560
  Classification -> best τ=0.365 (val F1=0.1908)
  Directional -> Accuracy: 0.5405, MCC: 0.0000, F1: 0.7018

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.59995 | val 0.78151
  Epoch 012 - train 0.53760 | val 1.07827
  Classification -> best τ=0.595 (val F1=0.4751)
  Directional -> Accuracy: 0.6400, MCC: 0.2871, F1: 0.6250

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.49807 | val 1.37476
  Epoch 011 - train 0.54463 | val 1.05283
  Classification -> best τ=0.535 (val F1=0.1537)
  Directional -> Accuracy: 0.5217, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.63796 | val 0.87190
  Epoch 011 - train 0.64172 | val 1.09359
  Classification -> best τ=0.395 (val F1=0.2481)
  Directional -> Accuracy: 0.4706, MCC: 0.1396, F1: 0.5814

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.51768 | val 3.44477
  Epoch 012 - train 0.54227 | val 1.73322
  Classification -> best τ=0.630 (val F1=0.3632)
  Directional -> Accuracy: 0.5714, MCC: 0.0700, F1: 0.3077

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.61242 | val 1.06757
  Epoch 011 - train 0.67950 | val 1.18926
  Classification -> best τ=0.585 (val F1=0.4197)
  Directional -> Accuracy: 0.5625, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.64153 | val 1.13311
  Epoch 012 - train 0.60535 | val 1.34902
  Classification -> best τ=0.330 (val F1=0.2293)
  Directional -> Accuracy: 0.4348, MCC: 0.1033, F1: 0.5979

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.65695 | val 0.88098
  Epoch 014 - train 0.63033 | val 1.41290
  Classification -> best τ=0.310 (val F1=0.2799)
  Directional -> Accuracy: 0.5918, MCC: 0.1563, F1: 0.3333

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.64181 | val 0.90645
  Epoch 012 - train 0.62965 | val 1.17973
  Classification -> best τ=0.420 (val F1=0.2157)
  Directional -> Accuracy: 0.5965, MCC: 0.2186, F1: 0.6849

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.56568 | val 0.91917
  Epoch 011 - train 0.54716 | val 1.34752
  Classification -> best τ=0.360 (val F1=0.2522)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.6230

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.67584 | val 0.76389
  Epoch 011 - train 0.65861 | val 0.83758
  Classification -> best τ=0.435 (val F1=0.3118)
  Directional -> Accuracy: 0.5833, MCC: 0.1714, F1: 0.6269

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.58088 | val 0.80910
  Epoch 020 - train 0.48409 | val 1.02647
  Epoch 021 - train 0.46342 | val 0.82074
  Classification -> best τ=0.760 (val F1=0.1455)
  Directional -> Accuracy: 0.5490, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.67022 | val 0.75763
  Epoch 020 - train 0.53716 | val 0.80300
  Epoch 022 - train 0.54510 | val 1.37372
  Classification -> best τ=0.780 (val F1=0.3361)
  Directional -> Accuracy: 0.4638, MCC: 0.0000, F1: 0.0000

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.61961 | val 2.57100
  Epoch 011 - train 0.61669 | val 2.40906
  Classification -> best τ=0.620 (val F1=0.0923)
  Directional -> Accuracy: 0.4483, MCC: 0.2128, F1: 0.2000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.66444 | val 0.92786
  Epoch 011 - train 0.60156 | val 1.03070
  Classification -> best τ=0.240 (val F1=0.1410)
  Directional -> Accuracy: 0.5733, MCC: 0.0615, F1: 0.6800

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.60226 | val 0.92914
  Epoch 012 - train 0.60439 | val 1.24622
  Classification -> best τ=0.530 (val F1=0.3662)
  Directional -> Accuracy: 0.4688, MCC: 0.0725, F1: 0.2609

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.57053 | val 0.96793
  Epoch 011 - train 0.53660 | val 1.32772
  Classification -> best τ=0.600 (val F1=0.2651)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.62153 | val 1.04496
  Epoch 011 - train 0.60720 | val 1.15553
  Classification -> best τ=0.560 (val F1=0.1572)
  Directional -> Accuracy: 0.6170, MCC: 0.0000, F1: 0.7632

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.64065 | val 1.18327
  Epoch 012 - train 0.61906 | val 1.91085
  Classification -> best τ=0.595 (val F1=0.1960)
  Directional -> Accuracy: 0.4769, MCC: -0.0767, F1: 0.0556

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.66307 | val 1.46611
  Epoch 012 - train 0.68357 | val 1.30675
  Classification -> best τ=0.620 (val F1=0.3175)
  Directional -> Accuracy: 0.4035, MCC: -0.2157, F1: 0.0000

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.59922 | val 1.58212
  Epoch 011 - train 0.58679 | val 2.26066
  Classification -> best τ=0.445 (val F1=0.1565)
  Directional -> Accuracy: 0.5692, MCC: 0.1509, F1: 0.6000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.59183 | val 1.52858
  Epoch 011 - train 0.56677 | val 1.76016
  Classification -> best τ=0.435 (val F1=0.1336)
  Directional -> Accuracy: 0.5455, MCC: 0.0000, F1: 0.7059

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.48752 | val 2.02251
  Epoch 011 - train 0.52051 | val 1.66066
  Classification -> best τ=0.545 (val F1=0.2035)
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.5938

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.59255 | val 0.77598
  Epoch 011 - train 0.62201 | val 0.89553
  Classification -> best τ=0.525 (val F1=0.0589)
  Directional -> Accuracy: 0.5000, MCC: -0.0430, F1: 0.5882

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.55191 | val 1.80237
  Epoch 011 - train 0.54718 | val 2.55191
  Classification -> best τ=0.435 (val F1=0.2829)
  Directional -> Accuracy: 0.5357, MCC: 0.2308, F1: 0.3158

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.64711 | val 1.33014
  Epoch 011 - train 0.59018 | val 1.31153
  Classification -> best τ=0.555 (val F1=0.2403)
  Directional -> Accuracy: 0.5500, MCC: 0.0737, F1: 0.6250

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.66444 | val 0.64721
  Epoch 020 - train 0.53812 | val 0.58650
  Epoch 026 - train 0.41405 | val 0.57350
  Classification -> best τ=0.595 (val F1=0.5210)
  Directional -> Accuracy: 0.5000, MCC: 0.0092, F1: 0.5333

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.60198 | val 0.92040
  Epoch 012 - train 0.63032 | val 1.17012
  Classification -> best τ=0.375 (val F1=0.2357)
  Directional -> Accuracy: 0.4762, MCC: -0.1864, F1: 0.6333

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.54450 | val 0.98417
  Epoch 011 - train 0.57210 | val 1.05521
  Classification -> best τ=0.490 (val F1=0.3465)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.64205 | val 0.74200
  Epoch 012 - train 0.62165 | val 0.83199
  Classification -> best τ=0.660 (val F1=0.3129)
  Directional -> Accuracy: 0.4444, MCC: 0.0000, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.61348 | val 2.26893
  Epoch 012 - train 0.56038 | val 1.76122
  Classification -> best τ=0.630 (val F1=0.2603)
  Directional -> Accuracy: 0.5116, MCC: 0.0094, F1: 0.2222

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.63906 | val 1.17163
  Epoch 012 - train 0.57038 | val 1.02046
  Classification -> best τ=0.675 (val F1=0.3287)
  Directional -> Accuracy: 0.6212, MCC: 0.2550, F1: 0.6377

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.61998 | val 1.14740
  Epoch 014 - train 0.48713 | val 0.84865
  Classification -> best τ=0.470 (val F1=0.4073)
  Directional -> Accuracy: 0.5952, MCC: 0.2259, F1: 0.5143

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.56949 | val 0.85105
  Epoch 011 - train 0.56625 | val 0.89169
  Classification -> best τ=0.450 (val F1=0.1886)
  Directional -> Accuracy: 0.5893, MCC: 0.1878, F1: 0.5965

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.51895 | val 1.01480
  Epoch 011 - train 0.53515 | val 1.04847
  Classification -> best τ=0.535 (val F1=0.3024)
  Directional -> Accuracy: 0.3913, MCC: -0.1022, F1: 0.2222

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.57223 | val 0.86209
  Epoch 012 - train 0.64652 | val 0.88576
  Classification -> best τ=0.425 (val F1=0.3476)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.59034 | val 1.77312
  Epoch 011 - train 0.62305 | val 1.82336
  Classification -> best τ=0.195 (val F1=0.2766)
  Directional -> Accuracy: 0.4865, MCC: 0.0000, F1: 0.6545

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.63412 | val 1.76238
  Epoch 015 - train 0.61596 | val 0.85757
  Classification -> best τ=0.525 (val F1=0.3500)
  Directional -> Accuracy: 0.5556, MCC: 0.1395, F1: 0.6774

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.59546 | val 1.57876
  Epoch 011 - train 0.50256 | val 1.57542
  Classification -> best τ=0.585 (val F1=0.3612)
  Directional -> Accuracy: 0.4286, MCC: -0.0323, F1: 0.0769

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.52442 | val 1.72269
  Epoch 012 - train 0.48429 | val 1.72888
  Classification -> best τ=0.545 (val F1=0.2605)
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.5455

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.68341 | val 1.60772
  Epoch 011 - train 0.65753 | val 1.49101
  Classification -> best τ=0.550 (val F1=0.0955)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.58038 | val 2.32190
  Epoch 011 - train 0.55031 | val 2.10966
  Classification -> best τ=0.795 (val F1=0.2143)
  Directional -> Accuracy: 0.4821, MCC: -0.0766, F1: 0.2162

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.65510 | val 0.78758
  Epoch 011 - train 0.60369 | val 1.03910
  Classification -> best τ=0.360 (val F1=0.1211)
  Directional -> Accuracy: 0.5094, MCC: 0.0000, F1: 0.6750

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.60785 | val 3.00680
  Epoch 011 - train 0.60711 | val 2.93700
  Classification -> best τ=0.750 (val F1=0.0489)
  Directional -> Accuracy: 0.5273, MCC: 0.0000, F1: 0.6905

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.62424 | val 0.69144

[I 2026-02-22 13:08:33,981] Trial 187 finished with value: 0.2544946263565811 and parameters: {'feature_set': 'sentinment', 'model_type': 'BiGRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.5, 'batch_size': 16, 'learning_rate': 0.0036472493518311393, 'weight_decay': 2.625019774985564e-07, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 1.3541037281187913, 'early_stopping_min_delta': 0.0003915690066282584}. Best is trial 159 with value: 0.297766251520741.

  Epoch 016 - train 0.60521 | val 0.81909
  Classification -> best τ=0.355 (val F1=0.2915)
  Directional -> Accuracy: 0.5500, MCC: 0.1831, F1: 0.6667

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2544946263565811
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.64418 | val 0.66645
  Epoch 016 - train 0.63720 | val 0.70897
  Classification -> best τ=0.615 (val F1=0.2919)
  Directional -> Accuracy: 0.5263, MCC: -0.0499, F1: 0.1429

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.62593 | val 1.01470
  Epoch 011 - train 0.64737 | val 1.03374
  Classification -> best τ=0.455 (val F1=0.1469)
  Directional -> Accuracy: 0.5778, MCC: 0.0000, F1: 0.7324

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.65406 | val 0.66560
  Epoch 014 - train 0.65225 | val 0.68679
  Classification -> best τ=0.410 (val F1=0.4104)
  Directional -> Accuracy: 0.5217, MCC: 0.0093, F1: 0.6765

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.67787 | val 1.00827
  Epoch 011 - train 0.66413 | val 1.13452
  Classification -> best τ=0.405 (val F1=0.1106)
  Directional -> Accuracy: 0.5405, MCC: 0.0000, F1: 0.7018

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.62040 | val 0.85818
  Epoch 012 - train 0.60360 | val 0.77862
  Classification -> best τ=0.590 (val F1=0.4753)
  Directional -> Accuracy: 0.6400, MCC: 0.2942, F1: 0.6087

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.60547 | val 0.94626
  Epoch 011 - train 0.61559 | val 1.04736
  Classification -> best τ=0.570 (val F1=0.1684)
  Directional -> Accuracy: 0.5217, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.67251 | val 0.83558
  Epoch 011 - train 0.67226 | val 0.81922
  Classification -> best τ=0.500 (val F1=0.2140)
  Directional -> Accuracy: 0.5735, MCC: 0.1763, F1: 0.5538

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.65880 | val 1.43593
  Epoch 011 - train 0.62995 | val 1.42756
  Classification -> best τ=0.535 (val F1=0.2566)
  Directional -> Accuracy: 0.5952, MCC: 0.1340, F1: 0.3704

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.66310 | val 0.92273
  Epoch 011 - train 0.65011 | val 0.97498
  Classification -> best τ=0.485 (val F1=0.3096)
  Directional -> Accuracy: 0.5000, MCC: 0.0268, F1: 0.5200

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.63135 | val 0.78302
  Epoch 011 - train 0.65891 | val 0.84772
  Classification -> best τ=0.400 (val F1=0.2208)
  Directional -> Accuracy: 0.4203, MCC: 0.0000, F1: 0.5918

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.67897 | val 0.68358
  Epoch 020 - train 0.63380 | val 1.07578
  Classification -> best τ=0.625 (val F1=0.3590)
  Directional -> Accuracy: 0.5918, MCC: 0.1804, F1: 0.2308

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.68094 | val 0.76760
  Epoch 011 - train 0.65613 | val 0.80083
  Classification -> best τ=0.515 (val F1=0.0728)
  Directional -> Accuracy: 0.5439, MCC: 0.1806, F1: 0.2353

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.60844 | val 1.10382
  Epoch 011 - train 0.65831 | val 1.09141
  Classification -> best τ=0.325 (val F1=0.2438)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.6230

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.66759 | val 0.64085
  Epoch 013 - train 0.67396 | val 0.67182
  Classification -> best τ=0.450 (val F1=0.3320)
  Directional -> Accuracy: 0.5500, MCC: 0.1075, F1: 0.6197

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.62638 | val 0.89585
  Epoch 011 - train 0.63898 | val 0.88924
  Classification -> best τ=0.590 (val F1=0.2298)
  Directional -> Accuracy: 0.5490, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.64149 | val 0.82803
  Epoch 011 - train 0.65105 | val 0.95841
  Classification -> best τ=0.415 (val F1=0.2795)
  Directional -> Accuracy: 0.5797, MCC: 0.1688, F1: 0.7071

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.64447 | val 1.06487
  Epoch 011 - train 0.65246 | val 1.08045
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.6207, MCC: 0.0000, F1: 0.7660

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.64217 | val 1.00159
  Epoch 011 - train 0.67529 | val 1.03977
  Classification -> best τ=0.400 (val F1=0.1605)
  Directional -> Accuracy: 0.6000, MCC: 0.1761, F1: 0.6591

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.65399 | val 0.87925
  Epoch 011 - train 0.65746 | val 0.91600
  Classification -> best τ=0.390 (val F1=0.2166)
  Directional -> Accuracy: 0.5156, MCC: 0.1459, F1: 0.3922

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.62125 | val 1.10044
  Epoch 011 - train 0.62013 | val 1.06329
  Classification -> best τ=0.555 (val F1=0.2881)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.66995 | val 0.75382
  Epoch 011 - train 0.67526 | val 0.75706
  Classification -> best τ=0.490 (val F1=0.1455)
  Directional -> Accuracy: 0.4468, MCC: -0.1705, F1: 0.5517

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.68598 | val 0.79573
  Epoch 011 - train 0.66943 | val 0.84286
  Classification -> best τ=0.525 (val F1=0.1157)
  Directional -> Accuracy: 0.4769, MCC: -0.0564, F1: 0.5641

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.69501 | val 0.75847
  Epoch 011 - train 0.66250 | val 0.76664
  Classification -> best τ=0.530 (val F1=0.2236)
  Directional -> Accuracy: 0.5263, MCC: 0.0255, F1: 0.5970

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.64493 | val 1.24749
  Epoch 011 - train 0.68174 | val 1.06076
  Classification -> best τ=0.460 (val F1=0.2073)
  Directional -> Accuracy: 0.5538, MCC: 0.1694, F1: 0.6506

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.64287 | val 0.86353
  Epoch 013 - train 0.61752 | val 0.96412
  Classification -> best τ=0.550 (val F1=0.4075)
  Directional -> Accuracy: 0.5091, MCC: 0.1077, F1: 0.3077

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.62241 | val 1.17352
  Epoch 011 - train 0.63193 | val 1.20021
  Classification -> best τ=0.515 (val F1=0.2035)
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.5938

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.66821 | val 0.82451
  Epoch 011 - train 0.69892 | val 0.83087
  Classification -> best τ=0.450 (val F1=0.1936)
  Directional -> Accuracy: 0.5000, MCC: -0.0280, F1: 0.5714

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.65465 | val 1.02230
  Epoch 011 - train 0.60670 | val 1.03253
  Classification -> best τ=0.455 (val F1=0.2435)
  Directional -> Accuracy: 0.5179, MCC: 0.2491, F1: 0.2286

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.69018 | val 0.72553
  Epoch 011 - train 0.64767 | val 0.72388
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5500, MCC: 0.0000, F1: 0.7097

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.68574 | val 0.81783
  Epoch 012 - train 0.64685 | val 0.91580
  Classification -> best τ=0.525 (val F1=0.3501)
  Directional -> Accuracy: 0.5238, MCC: 0.0500, F1: 0.5238

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.67428 | val 0.97877
  Epoch 011 - train 0.65150 | val 0.98658
  Classification -> best τ=0.530 (val F1=0.2697)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.62254 | val 0.76145
  Epoch 011 - train 0.60300 | val 0.77212
  Classification -> best τ=0.515 (val F1=0.1813)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.66664 | val 0.68384
  Epoch 018 - train 0.65628 | val 0.81104
  Classification -> best τ=0.410 (val F1=0.3366)
  Directional -> Accuracy: 0.5139, MCC: 0.0916, F1: 0.4068

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.65487 | val 1.22069
  Epoch 011 - train 0.65357 | val 1.25426
  Classification -> best τ=0.515 (val F1=0.3385)
  Directional -> Accuracy: 0.5814, MCC: 0.2074, F1: 0.6667

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.65889 | val 0.81405
  Epoch 011 - train 0.65684 | val 0.79441
  Classification -> best τ=0.430 (val F1=0.3855)
  Directional -> Accuracy: 0.5455, MCC: 0.1390, F1: 0.5161

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.63466 | val 0.70885
  Epoch 020 - train 0.56857 | val 0.70818
  Epoch 024 - train 0.50282 | val 0.77021
  Classification -> best τ=0.415 (val F1=0.3001)
  Directional -> Accuracy: 0.6429, MCC: 0.3127, F1: 0.5946

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.65649 | val 1.00548
  Epoch 011 - train 0.61503 | val 1.22233
  Classification -> best τ=0.475 (val F1=0.1718)
  Directional -> Accuracy: 0.4464, MCC: -0.1003, F1: 0.4561

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.64009 | val 1.25482
  Epoch 011 - train 0.61380 | val 1.16584
  Classification -> best τ=0.475 (val F1=0.2474)
  Directional -> Accuracy: 0.6087, MCC: 0.0000, F1: 0.7568

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.67436 | val 0.63632
  Epoch 020 - train 0.58595 | val 0.77032
  Classification -> best τ=0.480 (val F1=0.3800)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.64272 | val 1.19396
  Epoch 011 - train 0.63629 | val 1.23798
  Classification -> best τ=0.500 (val F1=0.2485)
  Directional -> Accuracy: 0.4865, MCC: -0.0094, F1: 0.6275

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.65761 | val 0.71338
  Epoch 013 - train 0.66747 | val 0.74257
  Classification -> best τ=0.515 (val F1=0.2125)
  Directional -> Accuracy: 0.5111, MCC: 0.0000, F1: 0.6765

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.63660 | val 0.84302
  Epoch 011 - train 0.67039 | val 0.86530
  Classification -> best τ=0.470 (val F1=0.1147)
  Directional -> Accuracy: 0.5714, MCC: 0.1376, F1: 0.6087

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.63759 | val 0.88724
  Epoch 014 - train 0.63339 | val 0.71566
  Classification -> best τ=0.485 (val F1=0.2605)
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.5455

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.66842 | val 0.85462
  Epoch 011 - train 0.68500 | val 0.85261
  Classification -> best τ=0.515 (val F1=0.0602)
  Directional -> Accuracy: 0.4364, MCC: -0.1491, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.63625 | val 1.81779
  Epoch 011 - train 0.62085 | val 1.83810
  Classification -> best τ=0.575 (val F1=0.4444)
  Directional -> Accuracy: 0.5357, MCC: 0.0680, F1: 0.5000

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.69505 | val 0.84977
  Epoch 011 - train 0.64430 | val 0.88251
  Classification -> best τ=0.435 (val F1=0.1967)
  Directional -> Accuracy: 0.5094, MCC: 0.0000, F1: 0.6750

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.61909 | val 1.86163
  Epoch 011 - train 0.56200 | val 1.92210
  Classification -> best τ=0.515 (val F1=0.2085)
  Directional -> Accuracy: 0.5273, MCC: 0.0000, F1: 0.6905

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.63343 | val 0.96640
  Epoch 011 - train 0.64689 | val 0.90452

[I 2026-02-22 13:10:16,269] Trial 188 finished with value: 0.23950555419692662 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 32, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.7000000000000001, 'batch_size': 16, 'learning_rate': 0.0017550435365913629, 'weight_decay': 2.613138735406745e-05, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 1.152905586341534, 'early_stopping_min_delta': 0.0008407981501426087}. Best is trial 159 with value: 0.297766251520741.

  Classification -> best τ=0.545 (val F1=0.2623)
  Directional -> Accuracy: 0.5167, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.23950555419692662
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d', 'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down', 'finbert_neutral']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.60496 | val 0.91523
  Epoch 011 - train 0.59361 | val 1.11896
  Classification -> best τ=0.550 (val F1=0.2200)
  Directional -> Accuracy: 0.6447, MCC: 0.2852, F1: 0.4490

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.57233 | val 1.12585
  Epoch 011 - train 0.53946 | val 1.18261
  Classification -> best τ=0.410 (val F1=0.2285)
  Directional -> Accuracy: 0.6000, MCC: 0.1297, F1: 0.7188

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.62625 | val 1.47582
  Epoch 011 - train 0.55531 | val 1.37434
  Classification -> best τ=0.445 (val F1=0.2871)
  Directional -> Accuracy: 0.5435, MCC: 0.0870, F1: 0.5532

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.56949 | val 0.90645
  Epoch 013 - train 0.53010 | val 0.97064
  Classification -> best τ=0.325 (val F1=0.1808)
  Directional -> Accuracy: 0.5405, MCC: 0.0000, F1: 0.7018

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.53586 | val 1.52993
  Epoch 011 - train 0.49274 | val 1.48457
  Classification -> best τ=0.545 (val F1=0.4414)
  Directional -> Accuracy: 0.6600, MCC: 0.3398, F1: 0.6222

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.51207 | val 0.81277
  Epoch 013 - train 0.40773 | val 1.70175
  Classification -> best τ=0.575 (val F1=0.4047)
  Directional -> Accuracy: 0.5217, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.57642 | val 1.18759
  Epoch 011 - train 0.54280 | val 1.24475
  Classification -> best τ=0.390 (val F1=0.1703)
  Directional -> Accuracy: 0.4118, MCC: 0.0991, F1: 0.5745

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.49552 | val 1.39424
  Epoch 017 - train 0.39002 | val 1.82028
  Classification -> best τ=0.490 (val F1=0.3689)
  Directional -> Accuracy: 0.5000, MCC: 0.0138, F1: 0.4878

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.52662 | val 2.62311
  Epoch 011 - train 0.47666 | val 2.40872
  Classification -> best τ=0.625 (val F1=0.2927)
  Directional -> Accuracy: 0.5208, MCC: 0.1039, F1: 0.5818

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.52375 | val 0.92576
  Epoch 011 - train 0.54521 | val 1.18553
  Classification -> best τ=0.650 (val F1=0.1478)
  Directional -> Accuracy: 0.5507, MCC: 0.0291, F1: 0.3404

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.52315 | val 0.74052
  Epoch 011 - train 0.53031 | val 0.71044
  Classification -> best τ=0.575 (val F1=0.3729)
  Directional -> Accuracy: 0.5918, MCC: 0.1804, F1: 0.2308

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.57636 | val 1.80747
  Epoch 011 - train 0.59251 | val 1.36815
  Classification -> best τ=0.420 (val F1=0.2739)
  Directional -> Accuracy: 0.5088, MCC: 0.0000, F1: 0.6744

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.41944 | val 3.72978
  Epoch 011 - train 0.41273 | val 3.45004
  Classification -> best τ=0.415 (val F1=0.2522)
  Directional -> Accuracy: 0.5000, MCC: 0.0235, F1: 0.5333

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.58197 | val 0.88986
  Epoch 011 - train 0.63559 | val 0.88052
  Classification -> best τ=0.400 (val F1=0.1961)
  Directional -> Accuracy: 0.5167, MCC: 0.0343, F1: 0.4528

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.51946 | val 1.28993
  Epoch 014 - train 0.47246 | val 1.81345
  Classification -> best τ=0.695 (val F1=0.2078)
  Directional -> Accuracy: 0.5882, MCC: 0.1753, F1: 0.2222

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.56800 | val 0.97071
  Epoch 011 - train 0.57548 | val 1.84174
  Classification -> best τ=0.550 (val F1=0.2112)
  Directional -> Accuracy: 0.5362, MCC: 0.1271, F1: 0.4074

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.58450 | val 1.51129
  Epoch 011 - train 0.52852 | val 1.37700
  Classification -> best τ=0.515 (val F1=0.1291)
  Directional -> Accuracy: 0.3793, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.54932 | val 0.80183
  Epoch 011 - train 0.50551 | val 1.27866
  Classification -> best τ=0.575 (val F1=0.1909)
  Directional -> Accuracy: 0.4000, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.54833 | val 0.78563
  Epoch 012 - train 0.57140 | val 0.76166
  Classification -> best τ=0.335 (val F1=0.3140)
  Directional -> Accuracy: 0.5625, MCC: 0.1532, F1: 0.5625

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.52606 | val 1.12085
  Epoch 011 - train 0.51153 | val 1.30699
  Classification -> best τ=0.510 (val F1=0.3183)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.58210 | val 1.24190
  Epoch 012 - train 0.51483 | val 1.22237
  Classification -> best τ=0.485 (val F1=0.3020)
  Directional -> Accuracy: 0.5106, MCC: 0.0805, F1: 0.5106

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.53414 | val 0.80701
  Epoch 013 - train 0.54761 | val 0.92010
  Classification -> best τ=0.495 (val F1=0.2842)
  Directional -> Accuracy: 0.3692, MCC: -0.2648, F1: 0.4058

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.61684 | val 0.70760
  Epoch 015 - train 0.52512 | val 0.93176
  Classification -> best τ=0.405 (val F1=0.3938)
  Directional -> Accuracy: 0.5088, MCC: 0.0025, F1: 0.5625

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.56234 | val 1.45707
  Epoch 011 - train 0.57657 | val 2.15027
  Classification -> best τ=0.575 (val F1=0.1565)
  Directional -> Accuracy: 0.5231, MCC: 0.0220, F1: 0.2791

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.52802 | val 1.04610
  Epoch 012 - train 0.46139 | val 1.82891
  Classification -> best τ=0.620 (val F1=0.5312)
  Directional -> Accuracy: 0.5273, MCC: 0.1463, F1: 0.3500

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.46670 | val 2.58866
  Epoch 011 - train 0.45868 | val 2.22248
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.5938

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.59932 | val 0.67438
  Epoch 020 - train 0.44875 | val 0.92063
  Classification -> best τ=0.615 (val F1=0.4201)
  Directional -> Accuracy: 0.4286, MCC: -0.0700, F1: 0.2500

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.55248 | val 1.17202
  Epoch 012 - train 0.55066 | val 1.26086
  Classification -> best τ=0.245 (val F1=0.2315)
  Directional -> Accuracy: 0.5179, MCC: 0.2491, F1: 0.2286

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.57031 | val 1.60375
  Epoch 011 - train 0.48895 | val 1.43287
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5500, MCC: 0.0000, F1: 0.7097

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.52138 | val 1.65236
  Epoch 012 - train 0.52821 | val 0.81879
  Classification -> best τ=0.510 (val F1=0.4110)
  Directional -> Accuracy: 0.5238, MCC: 0.0608, F1: 0.5652

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.57449 | val 1.14891
  Epoch 011 - train 0.58533 | val 1.49960
  Classification -> best τ=0.500 (val F1=0.1286)
  Directional -> Accuracy: 0.4286, MCC: -0.1194, F1: 0.0769

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.46926 | val 1.42928
  Epoch 012 - train 0.47015 | val 1.17640
  Classification -> best τ=0.415 (val F1=0.2611)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.57727 | val 1.12408
  Epoch 011 - train 0.55376 | val 1.41202
  Classification -> best τ=0.530 (val F1=0.2204)
  Directional -> Accuracy: 0.4444, MCC: 0.0000, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.50983 | val 0.97741
  Epoch 011 - train 0.53088 | val 1.39473
  Classification -> best τ=0.435 (val F1=0.1874)
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.58052 | val 1.30816
  Epoch 011 - train 0.59478 | val 1.11493
  Classification -> best τ=0.390 (val F1=0.1632)
  Directional -> Accuracy: 0.5758, MCC: 0.0000, F1: 0.7308

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.43232 | val 2.05910
  Epoch 012 - train 0.45873 | val 3.50372
  Classification -> best τ=0.410 (val F1=0.3001)
  Directional -> Accuracy: 0.6905, MCC: 0.3838, F1: 0.7347

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.50742 | val 0.93157
  Epoch 012 - train 0.51896 | val 1.32440
  Classification -> best τ=0.390 (val F1=0.2725)
  Directional -> Accuracy: 0.5179, MCC: 0.0333, F1: 0.4906

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.48876 | val 1.07693
  Epoch 015 - train 0.39605 | val 1.35165
  Classification -> best τ=0.500 (val F1=0.2185)
  Directional -> Accuracy: 0.3913, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.57702 | val 0.96097
  Epoch 020 - train 0.35796 | val 0.77538
  Epoch 022 - train 0.35521 | val 1.10966
  Classification -> best τ=0.580 (val F1=0.4710)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.55226 | val 1.83182
  Epoch 011 - train 0.49772 | val 1.69076
  Classification -> best τ=0.350 (val F1=0.2464)
  Directional -> Accuracy: 0.4595, MCC: -0.1260, F1: 0.6226

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.53903 | val 0.80275
  Epoch 013 - train 0.54410 | val 0.91766
  Classification -> best τ=0.485 (val F1=0.1941)
  Directional -> Accuracy: 0.5333, MCC: 0.1541, F1: 0.6866

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.50615 | val 1.53752
  Epoch 014 - train 0.36424 | val 1.83341
  Classification -> best τ=0.560 (val F1=0.5601)
  Directional -> Accuracy: 0.5952, MCC: 0.1487, F1: 0.6792

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.51441 | val 1.14296
  Epoch 020 - train 0.51485 | val 0.99945
  Epoch 022 - train 0.38875 | val 0.97079
  Classification -> best τ=0.485 (val F1=0.4606)
  Directional -> Accuracy: 0.5000, MCC: -0.0436, F1: 0.3684

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.62477 | val 1.17057
  Epoch 011 - train 0.60566 | val 1.22314
  Classification -> best τ=0.455 (val F1=0.2036)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.49100 | val 2.15058
  Epoch 011 - train 0.48332 | val 2.43490
  Classification -> best τ=0.560 (val F1=0.2952)
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.6506

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.55179 | val 0.86613
  Epoch 013 - train 0.58522 | val 1.16970
  Classification -> best τ=0.425 (val F1=0.2866)
  Directional -> Accuracy: 0.5094, MCC: 0.0000, F1: 0.6750

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.53361 | val 4.30438
  Epoch 011 - train 0.53435 | val 6.01662
  Classification -> best τ=0.745 (val F1=0.1763)
  Directional -> Accuracy: 0.5091, MCC: 0.0517, F1: 0.3721

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.56792 | val 1.08365

[I 2026-02-22 13:12:43,835] Trial 189 finished with value: 0.26936805208324593 and parameters: {'feature_set': 'sector_finbert', 'model_type': 'BiGRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.6000000000000001, 'batch_size': 16, 'learning_rate': 0.002716550373073309, 'weight_decay': 1.0040001553632686e-05, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 1.278040101392734, 'early_stopping_min_delta': 0.00023057196615879655}. Best is trial 159 with value: 0.297766251520741.

  Epoch 017 - train 0.45023 | val 1.06093
  Classification -> best τ=0.655 (val F1=0.3448)
  Directional -> Accuracy: 0.5167, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.26936805208324593
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.61514 | val 1.11810
  Epoch 011 - train 0.57629 | val 1.19565
  Classification -> best τ=0.540 (val F1=0.2510)
  Directional -> Accuracy: 0.5921, MCC: 0.1561, F1: 0.4561

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.57988 | val 0.90088
  Epoch 015 - train 0.47681 | val 0.92520
  Classification -> best τ=0.795 (val F1=0.2523)
  Directional -> Accuracy: 0.6000, MCC: 0.2829, F1: 0.5500

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.48775 | val 1.39775
  Epoch 011 - train 0.50555 | val 1.74311
  Classification -> best τ=0.755 (val F1=0.2449)
  Directional -> Accuracy: 0.4783, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.58828 | val 0.97629
  Epoch 020 - train 0.47957 | val 0.70527
  Epoch 029 - train 0.42896 | val 0.75926
  Classification -> best τ=0.360 (val F1=0.2230)
  Directional -> Accuracy: 0.5405, MCC: 0.0000, F1: 0.7018

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.55075 | val 0.99803
  Epoch 012 - train 0.46768 | val 1.23364
  Classification -> best τ=0.565 (val F1=0.5298)
  Directional -> Accuracy: 0.6200, MCC: 0.2670, F1: 0.5581

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.50093 | val 1.01906
  Epoch 012 - train 0.51036 | val 1.37071
  Classification -> best τ=0.640 (val F1=0.3069)
  Directional -> Accuracy: 0.5217, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.59432 | val 0.89615
  Epoch 011 - train 0.53585 | val 1.08162
  Classification -> best τ=0.520 (val F1=0.1489)
  Directional -> Accuracy: 0.5882, MCC: 0.1081, F1: 0.4167

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.51098 | val 0.62443
  Epoch 019 - train 0.36167 | val 0.90047
  Classification -> best τ=0.340 (val F1=0.3632)
  Directional -> Accuracy: 0.5476, MCC: 0.0574, F1: 0.4242

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.52961 | val 1.61274
  Epoch 011 - train 0.58896 | val 2.19541
  Classification -> best τ=0.615 (val F1=0.1608)
  Directional -> Accuracy: 0.6458, MCC: 0.2940, F1: 0.6222

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.56860 | val 0.82259
  Epoch 014 - train 0.50148 | val 0.87585
  Classification -> best τ=0.520 (val F1=0.1967)
  Directional -> Accuracy: 0.5072, MCC: 0.0170, F1: 0.4688

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.62723 | val 0.83744
  Epoch 015 - train 0.49623 | val 1.46103
  Classification -> best τ=0.475 (val F1=0.3241)
  Directional -> Accuracy: 0.5714, MCC: 0.1044, F1: 0.3636

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.59901 | val 1.95445
  Epoch 011 - train 0.53939 | val 1.74846
  Classification -> best τ=0.425 (val F1=0.0596)
  Directional -> Accuracy: 0.5088, MCC: 0.0033, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.47267 | val 1.96120
  Epoch 011 - train 0.50524 | val 1.91902
  Classification -> best τ=0.485 (val F1=0.1754)
  Directional -> Accuracy: 0.5476, MCC: 0.0000, F1: 0.0000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.60889 | val 0.88172
  Epoch 015 - train 0.47105 | val 0.88226
  Classification -> best τ=0.395 (val F1=0.3282)
  Directional -> Accuracy: 0.4833, MCC: -0.0603, F1: 0.1143

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.59598 | val 0.82311
  Epoch 016 - train 0.41865 | val 0.85031
  Classification -> best τ=0.475 (val F1=0.3000)
  Directional -> Accuracy: 0.4510, MCC: -0.0858, F1: 0.4615

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.56399 | val 1.40463
  Epoch 011 - train 0.55352 | val 1.12579
  Classification -> best τ=0.730 (val F1=0.1989)
  Directional -> Accuracy: 0.5072, MCC: 0.1200, F1: 0.2273

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.59947 | val 1.40253
  Epoch 011 - train 0.55222 | val 1.40290
  Classification -> best τ=0.435 (val F1=0.2048)
  Directional -> Accuracy: 0.6207, MCC: 0.1270, F1: 0.7317

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.59349 | val 1.04493
  Epoch 012 - train 0.52211 | val 0.90332
  Classification -> best τ=0.555 (val F1=0.2220)
  Directional -> Accuracy: 0.4000, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.54788 | val 1.04221
  Epoch 011 - train 0.49995 | val 0.99307
  Classification -> best τ=0.475 (val F1=0.3144)
  Directional -> Accuracy: 0.5312, MCC: 0.1954, F1: 0.4000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.54890 | val 1.16824
  Epoch 011 - train 0.49579 | val 1.47589
  Classification -> best τ=0.510 (val F1=0.2382)
  Directional -> Accuracy: 0.3919, MCC: -0.1954, F1: 0.1509

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.52932 | val 1.51152
  Epoch 013 - train 0.43657 | val 1.29281
  Classification -> best τ=0.565 (val F1=0.2449)
  Directional -> Accuracy: 0.3830, MCC: -0.0921, F1: 0.1714

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.53547 | val 1.70418
  Epoch 013 - train 0.53302 | val 1.45393
  Classification -> best τ=0.485 (val F1=0.2509)
  Directional -> Accuracy: 0.4923, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.62177 | val 0.66414
  Epoch 011 - train 0.62974 | val 0.65387
  Classification -> best τ=0.455 (val F1=0.4382)
  Directional -> Accuracy: 0.5614, MCC: 0.0000, F1: 0.7191

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.60946 | val 0.94819
  Epoch 017 - train 0.49608 | val 0.74591
  Classification -> best τ=0.505 (val F1=0.2055)
  Directional -> Accuracy: 0.4615, MCC: -0.1166, F1: 0.2553

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.51387 | val 1.20100
  Epoch 011 - train 0.48884 | val 1.21158
  Classification -> best τ=0.430 (val F1=0.4183)
  Directional -> Accuracy: 0.5636, MCC: 0.1491, F1: 0.5385

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.48915 | val 2.28132
  Epoch 012 - train 0.47939 | val 3.89024
  Classification -> best τ=0.660 (val F1=0.2935)
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.5938

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.58175 | val 0.72400
  Epoch 018 - train 0.41188 | val 0.75115
  Classification -> best τ=0.625 (val F1=0.2402)
  Directional -> Accuracy: 0.5714, MCC: 0.1667, F1: 0.5714

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.52132 | val 1.58414
  Epoch 011 - train 0.51525 | val 1.74288
  Classification -> best τ=0.355 (val F1=0.2870)
  Directional -> Accuracy: 0.5000, MCC: 0.2137, F1: 0.1765

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.50570 | val 1.54025
  Epoch 011 - train 0.47787 | val 1.33871
  Classification -> best τ=0.650 (val F1=0.1943)
  Directional -> Accuracy: 0.5250, MCC: 0.0056, F1: 0.6275

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.63223 | val 0.66862
  Epoch 016 - train 0.44135 | val 0.97226
  Classification -> best τ=0.465 (val F1=0.5027)
  Directional -> Accuracy: 0.4762, MCC: -0.0455, F1: 0.4762

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.53885 | val 0.88841
  Epoch 011 - train 0.50130 | val 0.96497
  Classification -> best τ=0.545 (val F1=0.1286)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.55622 | val 1.04123
  Epoch 011 - train 0.47427 | val 0.98652
  Classification -> best τ=0.540 (val F1=0.3465)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.58147 | val 0.64181
  Epoch 020 - train 0.42620 | val 0.92638
  Classification -> best τ=0.440 (val F1=0.3239)
  Directional -> Accuracy: 0.5417, MCC: 0.1835, F1: 0.4000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.51126 | val 1.22503
  Epoch 011 - train 0.47749 | val 1.20149
  Classification -> best τ=0.395 (val F1=0.2717)
  Directional -> Accuracy: 0.6279, MCC: 0.3176, F1: 0.7037

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.58892 | val 1.54462
  Epoch 011 - train 0.52962 | val 1.23002
  Classification -> best τ=0.470 (val F1=0.2406)
  Directional -> Accuracy: 0.4242, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.53433 | val 1.91942
  Epoch 012 - train 0.42611 | val 2.21434
  Classification -> best τ=0.320 (val F1=0.2464)
  Directional -> Accuracy: 0.5238, MCC: 0.0267, F1: 0.6296

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.61736 | val 0.97189
  Epoch 012 - train 0.50595 | val 1.04857
  Classification -> best τ=0.535 (val F1=0.2717)
  Directional -> Accuracy: 0.6071, MCC: 0.2204, F1: 0.3889

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.48870 | val 0.91361
  Epoch 012 - train 0.45696 | val 1.15814
  Classification -> best τ=0.605 (val F1=0.3294)
  Directional -> Accuracy: 0.5217, MCC: 0.0156, F1: 0.5926

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.50108 | val 0.71719
  Epoch 014 - train 0.46846 | val 0.78158
  Classification -> best τ=0.295 (val F1=0.4556)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.50178 | val 2.37437
  Epoch 011 - train 0.45058 | val 2.84983
  Classification -> best τ=0.525 (val F1=0.2784)
  Directional -> Accuracy: 0.5000, MCC: -0.0466, F1: 0.0976

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.61322 | val 1.34280
  Epoch 015 - train 0.46914 | val 1.05150
  Classification -> best τ=0.530 (val F1=0.4080)
  Directional -> Accuracy: 0.6667, MCC: 0.3340, F1: 0.6667

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.38936 | val 2.16512
  Epoch 012 - train 0.27474 | val 2.40149
  Classification -> best τ=0.640 (val F1=0.3612)
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.0000

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.53577 | val 0.67970
  Epoch 020 - train 0.37355 | val 0.84837
  Epoch 026 - train 0.18658 | val 1.16139
  Classification -> best τ=0.700 (val F1=0.6590)
  Directional -> Accuracy: 0.5625, MCC: -0.0128, F1: 0.2759

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.61740 | val 1.36058
  Epoch 011 - train 0.57297 | val 1.36043
  Classification -> best τ=0.580 (val F1=0.1784)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.45355 | val 1.74823
  Epoch 011 - train 0.42324 | val 1.54575
  Classification -> best τ=0.580 (val F1=0.1502)
  Directional -> Accuracy: 0.5179, MCC: 0.0000, F1: 0.0000

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.65924 | val 0.84525
  Epoch 011 - train 0.60722 | val 0.75299
  Classification -> best τ=0.570 (val F1=0.2064)
  Directional -> Accuracy: 0.6226, MCC: 0.2457, F1: 0.6552

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.51643 | val 3.72918
  Epoch 011 - train 0.51780 | val 3.67224
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5273, MCC: 0.0000, F1: 0.6905

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.61238 | val 0.90675

[I 2026-02-22 13:15:21,310] Trial 190 finished with value: 0.27577201719038924 and parameters: {'feature_set': 'sector', 'model_type': 'BiGRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.4, 'batch_size': 16, 'learning_rate': 0.006049347321223612, 'weight_decay': 3.404323942378868e-05, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 1.0537002063982432, 'early_stopping_min_delta': 0.0005684559028152218}. Best is trial 159 with value: 0.297766251520741.

  Epoch 014 - train 0.52028 | val 1.03335
  Classification -> best τ=0.535 (val F1=0.2623)
  Directional -> Accuracy: 0.5167, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.27577201719038924
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.58975 | val 0.80825
  Epoch 011 - train 0.56095 | val 0.80019
  Classification -> best τ=0.645 (val F1=0.2510)
  Directional -> Accuracy: 0.5658, MCC: 0.0795, F1: 0.1951

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.55527 | val 1.00128
  Epoch 011 - train 0.50584 | val 1.04307
  Classification -> best τ=0.450 (val F1=0.2949)
  Directional -> Accuracy: 0.5778, MCC: 0.0000, F1: 0.7324

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.57911 | val 1.87881
  Epoch 011 - train 0.51717 | val 2.35096
  Classification -> best τ=0.685 (val F1=0.2727)
  Directional -> Accuracy: 0.5435, MCC: 0.1633, F1: 0.3226

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.56531 | val 1.34181
  Epoch 015 - train 0.52474 | val 1.06565
  Classification -> best τ=0.260 (val F1=0.1808)
  Directional -> Accuracy: 0.5405, MCC: 0.0000, F1: 0.7018

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.51195 | val 1.15742
  Epoch 011 - train 0.47786 | val 1.14218
  Classification -> best τ=0.620 (val F1=0.4493)
  Directional -> Accuracy: 0.5800, MCC: 0.1922, F1: 0.4878

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.52340 | val 0.72706
  Epoch 014 - train 0.37530 | val 1.14779
  Classification -> best τ=0.600 (val F1=0.3210)
  Directional -> Accuracy: 0.5217, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.57236 | val 1.10743
  Epoch 011 - train 0.53490 | val 1.22939
  Classification -> best τ=0.595 (val F1=0.2727)
  Directional -> Accuracy: 0.5294, MCC: 0.0921, F1: 0.5152

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.47500 | val 0.78586
  Epoch 011 - train 0.48507 | val 0.68593
  Classification -> best τ=0.375 (val F1=0.1147)
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.57342 | val 2.02620
  Epoch 011 - train 0.50675 | val 2.25875
  Classification -> best τ=0.635 (val F1=0.2822)
  Directional -> Accuracy: 0.5625, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.54617 | val 0.94662
  Epoch 011 - train 0.54244 | val 1.01101
  Classification -> best τ=0.340 (val F1=0.1858)
  Directional -> Accuracy: 0.4203, MCC: 0.0000, F1: 0.5918

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.61124 | val 0.88704
  Epoch 017 - train 0.53333 | val 0.79738
  Classification -> best τ=0.530 (val F1=0.3075)
  Directional -> Accuracy: 0.5918, MCC: 0.1635, F1: 0.2857

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.58090 | val 1.34480
  Epoch 011 - train 0.52153 | val 1.52313
  Classification -> best τ=0.590 (val F1=0.1181)
  Directional -> Accuracy: 0.5965, MCC: 0.2346, F1: 0.4651

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.48827 | val 2.94330
  Epoch 011 - train 0.46402 | val 3.01355
  Classification -> best τ=0.570 (val F1=0.1225)
  Directional -> Accuracy: 0.3333, MCC: -0.4045, F1: 0.5000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.58955 | val 0.60107
  Epoch 020 - train 0.42728 | val 0.70276
  Classification -> best τ=0.630 (val F1=0.4746)
  Directional -> Accuracy: 0.5333, MCC: 0.0833, F1: 0.3333

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.61094 | val 0.73891
  Epoch 011 - train 0.52599 | val 0.98719
  Classification -> best τ=0.600 (val F1=0.2571)
  Directional -> Accuracy: 0.5098, MCC: -0.1831, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.62536 | val 1.36042
  Epoch 011 - train 0.56058 | val 1.38739
  Classification -> best τ=0.420 (val F1=0.1823)
  Directional -> Accuracy: 0.5362, MCC: 0.0367, F1: 0.6522

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.60115 | val 1.51616
  Epoch 011 - train 0.56823 | val 1.50761
  Classification -> best τ=0.440 (val F1=0.2135)
  Directional -> Accuracy: 0.6379, MCC: 0.3217, F1: 0.6557

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.56146 | val 0.78301
  Epoch 012 - train 0.51124 | val 0.92895
  Classification -> best τ=0.615 (val F1=0.2758)
  Directional -> Accuracy: 0.4000, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.55546 | val 0.78702
  Epoch 017 - train 0.45916 | val 1.22014
  Classification -> best τ=0.230 (val F1=0.2843)
  Directional -> Accuracy: 0.5156, MCC: 0.0624, F1: 0.5079

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.48066 | val 1.87214
  Epoch 011 - train 0.53072 | val 1.74182
  Classification -> best τ=0.540 (val F1=0.2588)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.59257 | val 1.12426
  Epoch 011 - train 0.49259 | val 1.11859
  Classification -> best τ=0.415 (val F1=0.2416)
  Directional -> Accuracy: 0.6170, MCC: 0.0000, F1: 0.7632

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.60263 | val 0.90750
  Epoch 016 - train 0.50334 | val 1.49073
  Classification -> best τ=0.305 (val F1=0.3216)
  Directional -> Accuracy: 0.5077, MCC: 0.0000, F1: 0.6735

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.60012 | val 0.75911
  Epoch 016 - train 0.51897 | val 1.10216
  Classification -> best τ=0.415 (val F1=0.5155)
  Directional -> Accuracy: 0.5614, MCC: 0.0000, F1: 0.7191

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.59376 | val 0.71787
  Epoch 012 - train 0.55562 | val 0.86123
  Classification -> best τ=0.510 (val F1=0.1778)
  Directional -> Accuracy: 0.4923, MCC: -0.0285, F1: 0.4000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.54915 | val 0.80380
  Epoch 015 - train 0.49723 | val 1.20909
  Classification -> best τ=0.400 (val F1=0.4994)
  Directional -> Accuracy: 0.5091, MCC: 0.1077, F1: 0.3077

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.48999 | val 2.87288
  Epoch 012 - train 0.49906 | val 2.56285
  Classification -> best τ=0.685 (val F1=0.1585)
  Directional -> Accuracy: 0.5778, MCC: 0.1170, F1: 0.4571

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.59327 | val 0.70705
  Epoch 012 - train 0.56753 | val 0.72786
  Classification -> best τ=0.625 (val F1=0.2402)
  Directional -> Accuracy: 0.5952, MCC: 0.2970, F1: 0.5143

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.52303 | val 1.95102
  Epoch 011 - train 0.48303 | val 1.84723
  Classification -> best τ=0.220 (val F1=0.1126)
  Directional -> Accuracy: 0.5536, MCC: 0.1566, F1: 0.4898

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.46647 | val 0.77530
  Epoch 012 - train 0.45306 | val 0.92729
  Classification -> best τ=0.560 (val F1=0.2414)
  Directional -> Accuracy: 0.4250, MCC: -0.2467, F1: 0.5660

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.55760 | val 0.73382
  Epoch 012 - train 0.53086 | val 0.91483
  Classification -> best τ=0.475 (val F1=0.3501)
  Directional -> Accuracy: 0.5238, MCC: 0.0413, F1: 0.4737

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.52620 | val 1.60074
  Epoch 012 - train 0.54824 | val 1.33265
  Classification -> best τ=0.640 (val F1=0.1286)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.50697 | val 1.03851
  Epoch 011 - train 0.45609 | val 1.15294
  Classification -> best τ=0.440 (val F1=0.3541)
  Directional -> Accuracy: 0.5102, MCC: -0.0696, F1: 0.6667

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.56054 | val 1.24668
  Epoch 011 - train 0.51977 | val 1.24209
  Classification -> best τ=0.360 (val F1=0.2831)
  Directional -> Accuracy: 0.4444, MCC: 0.0000, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.60025 | val 1.09359
  Epoch 011 - train 0.46694 | val 1.16631
  Classification -> best τ=0.435 (val F1=0.3078)
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.56112 | val 1.95870
  Epoch 011 - train 0.53951 | val 1.37303
  Classification -> best τ=0.555 (val F1=0.2329)
  Directional -> Accuracy: 0.6667, MCC: 0.3526, F1: 0.6765

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.55925 | val 2.89044
  Epoch 012 - train 0.40486 | val 2.77395
  Classification -> best τ=0.425 (val F1=0.3260)
  Directional -> Accuracy: 0.6429, MCC: 0.3511, F1: 0.5455

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.50089 | val 0.91561
  Epoch 011 - train 0.50371 | val 1.06107
  Classification -> best τ=0.480 (val F1=0.2530)
  Directional -> Accuracy: 0.5179, MCC: 0.0437, F1: 0.5263

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.44385 | val 1.32641
  Epoch 011 - train 0.43677 | val 1.30134
  Classification -> best τ=0.340 (val F1=0.1709)
  Directional -> Accuracy: 0.6087, MCC: 0.0000, F1: 0.7568

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.51413 | val 1.12357
  Epoch 016 - train 0.43247 | val 1.09602
  Classification -> best τ=0.375 (val F1=0.4011)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.58710 | val 1.61842
  Epoch 011 - train 0.49361 | val 1.65616
  Classification -> best τ=0.495 (val F1=0.2891)
  Directional -> Accuracy: 0.5270, MCC: 0.0741, F1: 0.1026

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.63366 | val 0.85083
  Epoch 014 - train 0.53117 | val 0.80170
  Classification -> best τ=0.475 (val F1=0.3953)
  Directional -> Accuracy: 0.4889, MCC: -0.0134, F1: 0.3429

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.40086 | val 2.78452
  Epoch 011 - train 0.41406 | val 2.83089
  Classification -> best τ=0.585 (val F1=0.3851)
  Directional -> Accuracy: 0.6429, MCC: 0.2527, F1: 0.7170

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.48851 | val 0.74321
  Epoch 019 - train 0.30052 | val 1.12314
  Classification -> best τ=0.440 (val F1=0.5514)
  Directional -> Accuracy: 0.5000, MCC: 0.2928, F1: 0.6000

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.68539 | val 1.41781
  Epoch 012 - train 0.58034 | val 1.54008
  Classification -> best τ=0.360 (val F1=0.0322)
  Directional -> Accuracy: 0.4364, MCC: -0.3194, F1: 0.6076

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.41827 | val 1.62005
  Epoch 011 - train 0.42005 | val 1.93298
  Classification -> best τ=0.570 (val F1=0.0696)
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.6506

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.63545 | val 0.83196
  Epoch 014 - train 0.52016 | val 0.78006
  Classification -> best τ=0.525 (val F1=0.2457)
  Directional -> Accuracy: 0.5660, MCC: 0.1310, F1: 0.6102

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.53531 | val 3.66233
  Epoch 012 - train 0.49129 | val 3.59284
  Classification -> best τ=0.650 (val F1=0.2132)
  Directional -> Accuracy: 0.5273, MCC: 0.0000, F1: 0.6905

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.57883 | val 0.65934

[I 2026-02-22 13:17:52,704] Trial 191 finished with value: 0.2700729163425259 and parameters: {'feature_set': 'sector', 'model_type': 'BiGRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.4, 'batch_size': 16, 'learning_rate': 0.005852782026367825, 'weight_decay': 3.487172438394372e-05, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 1.0424510434733019, 'early_stopping_min_delta': 0.0005505875996954841}. Best is trial 159 with value: 0.297766251520741.

  Epoch 020 - train 0.46234 | val 1.12319
  Classification -> best τ=0.430 (val F1=0.3461)
  Directional -> Accuracy: 0.5167, MCC: 0.0089, F1: 0.1212

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2700729163425259
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.62695 | val 0.93987
  Epoch 011 - train 0.63682 | val 0.98435
  Classification -> best τ=0.590 (val F1=0.2919)
  Directional -> Accuracy: 0.5526, MCC: 0.0000, F1: 0.0000

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.56679 | val 0.91188
  Epoch 011 - train 0.53001 | val 0.93057
  Classification -> best τ=0.430 (val F1=0.2285)
  Directional -> Accuracy: 0.5333, MCC: -0.1089, F1: 0.6866

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.56430 | val 2.59241
  Epoch 011 - train 0.51581 | val 2.46091
  Classification -> best τ=0.820 (val F1=0.2727)
  Directional -> Accuracy: 0.5000, MCC: 0.0547, F1: 0.2069

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.60038 | val 0.72670
  Epoch 020 - train 0.57184 | val 1.06352
  Epoch 023 - train 0.48804 | val 0.93803
  Classification -> best τ=0.545 (val F1=0.1895)
  Directional -> Accuracy: 0.4595, MCC: -0.0136, F1: 0.0476

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.54827 | val 0.97782
  Epoch 011 - train 0.47014 | val 1.22467
  Classification -> best τ=0.550 (val F1=0.3529)
  Directional -> Accuracy: 0.7000, MCC: 0.4003, F1: 0.7059

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.50345 | val 0.78055
  Epoch 015 - train 0.42335 | val 1.13054
  Classification -> best τ=0.590 (val F1=0.5108)
  Directional -> Accuracy: 0.5217, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.59627 | val 1.91095
  Epoch 013 - train 0.57195 | val 1.45973
  Classification -> best τ=0.295 (val F1=0.1235)
  Directional -> Accuracy: 0.6176, MCC: 0.2014, F1: 0.5185

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.56219 | val 0.86161
  Epoch 011 - train 0.47896 | val 1.18538
  Classification -> best τ=0.355 (val F1=0.1847)
  Directional -> Accuracy: 0.4048, MCC: -0.1334, F1: 0.5614

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.58819 | val 1.93986
  Epoch 014 - train 0.51860 | val 1.76286
  Classification -> best τ=0.335 (val F1=0.2678)
  Directional -> Accuracy: 0.4583, MCC: 0.0542, F1: 0.6061

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.59793 | val 0.87455
  Epoch 011 - train 0.55760 | val 0.87359
  Classification -> best τ=0.480 (val F1=0.1801)
  Directional -> Accuracy: 0.5217, MCC: 0.0511, F1: 0.4923

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.62623 | val 0.66727
  Epoch 020 - train 0.38621 | val 0.84426
  Classification -> best τ=0.385 (val F1=0.3390)
  Directional -> Accuracy: 0.5714, MCC: 0.1005, F1: 0.2759

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.55945 | val 1.38171
  Epoch 013 - train 0.49289 | val 1.68591
  Classification -> best τ=0.415 (val F1=0.1758)
  Directional -> Accuracy: 0.5965, MCC: 0.1953, F1: 0.5818

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.51827 | val 2.62713
  Epoch 011 - train 0.45543 | val 2.88501
  Classification -> best τ=0.490 (val F1=0.1308)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.6230

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.60081 | val 0.76488
  Epoch 017 - train 0.43743 | val 0.68168
  Classification -> best τ=0.215 (val F1=0.3391)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.2500

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.55546 | val 0.75152
  Epoch 011 - train 0.54193 | val 0.74063
  Classification -> best τ=0.580 (val F1=0.2078)
  Directional -> Accuracy: 0.5490, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.57450 | val 1.18579
  Epoch 011 - train 0.55061 | val 1.49016
  Classification -> best τ=0.445 (val F1=0.2795)
  Directional -> Accuracy: 0.5217, MCC: -0.1128, F1: 0.6857

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.64346 | val 1.95611
  Epoch 012 - train 0.54989 | val 1.50826
  Classification -> best τ=0.310 (val F1=0.3095)
  Directional -> Accuracy: 0.4828, MCC: 0.1361, F1: 0.3750

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.59292 | val 0.91617
  Epoch 015 - train 0.50497 | val 0.95501
  Classification -> best τ=0.545 (val F1=0.1909)
  Directional -> Accuracy: 0.3867, MCC: -0.1424, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.56923 | val 0.88119
  Epoch 015 - train 0.47256 | val 1.13008
  Classification -> best τ=0.515 (val F1=0.3202)
  Directional -> Accuracy: 0.5938, MCC: 0.1850, F1: 0.6286

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.52633 | val 1.17754
  Epoch 011 - train 0.51091 | val 1.39988
  Classification -> best τ=0.275 (val F1=0.2796)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.52945 | val 0.78240
  Epoch 014 - train 0.43220 | val 1.38733
  Classification -> best τ=0.570 (val F1=0.3835)
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.57988 | val 0.96670
  Epoch 013 - train 0.51336 | val 1.19561
  Classification -> best τ=0.490 (val F1=0.2520)
  Directional -> Accuracy: 0.5692, MCC: 0.1742, F1: 0.4167

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.65878 | val 0.66154
  Epoch 020 - train 0.50377 | val 0.96595
  Epoch 021 - train 0.40731 | val 1.11010
  Classification -> best τ=0.515 (val F1=0.4597)
  Directional -> Accuracy: 0.5088, MCC: 0.0199, F1: 0.5333

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.55668 | val 1.76972
  Epoch 011 - train 0.51759 | val 2.06343
  Classification -> best τ=0.615 (val F1=0.2305)
  Directional -> Accuracy: 0.4462, MCC: -0.1269, F1: 0.3333

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.58853 | val 0.88440
  Epoch 013 - train 0.45493 | val 1.24516
  Classification -> best τ=0.560 (val F1=0.5294)
  Directional -> Accuracy: 0.5455, MCC: 0.0930, F1: 0.5614

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.52945 | val 2.85257
  Epoch 011 - train 0.48817 | val 2.64686
  Classification -> best τ=0.685 (val F1=0.1890)
  Directional -> Accuracy: 0.4222, MCC: -0.1842, F1: 0.3158

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.56539 | val 0.73975
  Epoch 012 - train 0.59429 | val 0.81400
  Classification -> best τ=0.535 (val F1=0.1250)
  Directional -> Accuracy: 0.5476, MCC: 0.0000, F1: 0.6780

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.53418 | val 0.94073
  Epoch 011 - train 0.48231 | val 1.31577
  Classification -> best τ=0.325 (val F1=0.2541)
  Directional -> Accuracy: 0.4464, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.57902 | val 1.06092
  Epoch 011 - train 0.53384 | val 1.01612
  Classification -> best τ=0.495 (val F1=0.2686)
  Directional -> Accuracy: 0.6000, MCC: 0.1741, F1: 0.6923

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.63397 | val 2.12680
  Epoch 013 - train 0.51135 | val 1.85396
  Classification -> best τ=0.415 (val F1=0.4266)
  Directional -> Accuracy: 0.5238, MCC: 0.0302, F1: 0.3750

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.57826 | val 1.38418
  Epoch 011 - train 0.58228 | val 1.25789
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5476, MCC: 0.0000, F1: 0.7077

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.52875 | val 0.95721
  Epoch 012 - train 0.38920 | val 1.25369
  Classification -> best τ=0.235 (val F1=0.3833)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.60042 | val 0.95040
  Epoch 017 - train 0.44873 | val 1.03085
  Classification -> best τ=0.710 (val F1=0.3278)
  Directional -> Accuracy: 0.4583, MCC: 0.1061, F1: 0.0488

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.53647 | val 0.95870
  Epoch 011 - train 0.51660 | val 0.98503
  Classification -> best τ=0.620 (val F1=0.3774)
  Directional -> Accuracy: 0.4884, MCC: -0.0318, F1: 0.3889

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.56449 | val 1.86157
  Epoch 011 - train 0.51740 | val 1.50544
  Classification -> best τ=0.500 (val F1=0.3099)
  Directional -> Accuracy: 0.5303, MCC: 0.0060, F1: 0.6265

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.53821 | val 0.83895
  Epoch 011 - train 0.42825 | val 1.01027
  Classification -> best τ=0.440 (val F1=0.2464)
  Directional -> Accuracy: 0.5714, MCC: 0.1386, F1: 0.6667

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.50556 | val 0.97539
  Epoch 011 - train 0.47142 | val 1.03276
  Classification -> best τ=0.340 (val F1=0.2530)
  Directional -> Accuracy: 0.5357, MCC: 0.1240, F1: 0.6176

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.54143 | val 0.98821
  Epoch 012 - train 0.42228 | val 0.96950
  Classification -> best τ=0.450 (val F1=0.2815)
  Directional -> Accuracy: 0.4783, MCC: 0.0244, F1: 0.4545

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.54871 | val 0.97354
  Epoch 012 - train 0.48548 | val 0.88004
  Classification -> best τ=0.575 (val F1=0.4011)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.56175 | val 1.39220
  Epoch 011 - train 0.49522 | val 1.82964
  Classification -> best τ=0.320 (val F1=0.2829)
  Directional -> Accuracy: 0.4865, MCC: 0.0000, F1: 0.6545

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.58861 | val 0.77014
  Epoch 012 - train 0.58816 | val 0.75899
  Classification -> best τ=0.440 (val F1=0.4490)
  Directional -> Accuracy: 0.5333, MCC: 0.1541, F1: 0.6866

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.36897 | val 1.91315
  Epoch 011 - train 0.33369 | val 2.06370
  Classification -> best τ=0.515 (val F1=0.3015)
  Directional -> Accuracy: 0.5952, MCC: 0.1334, F1: 0.7302

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.49786 | val 1.72725
  Epoch 017 - train 0.35580 | val 1.43178
  Classification -> best τ=0.700 (val F1=0.4371)
  Directional -> Accuracy: 0.3958, MCC: 0.1130, F1: 0.5538

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.70804 | val 0.97410
  Epoch 012 - train 0.64286 | val 1.49282
  Classification -> best τ=0.685 (val F1=0.2036)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.50640 | val 1.93761
  Epoch 011 - train 0.44776 | val 2.16791
  Classification -> best τ=0.625 (val F1=0.4352)
  Directional -> Accuracy: 0.5357, MCC: 0.0728, F1: 0.5357

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.60969 | val 0.80766
  Epoch 015 - train 0.59111 | val 0.76555
  Classification -> best τ=0.425 (val F1=0.2521)
  Directional -> Accuracy: 0.5849, MCC: 0.2912, F1: 0.7105

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.50234 | val 4.17961
  Epoch 011 - train 0.49929 | val 4.40791
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5273, MCC: 0.0000, F1: 0.6905

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.60653 | val 1.04698

[I 2026-02-22 13:20:29,755] Trial 192 finished with value: 0.281215765430148 and parameters: {'feature_set': 'sector', 'model_type': 'BiGRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.4, 'batch_size': 16, 'learning_rate': 0.006960636931413245, 'weight_decay': 4.398929266084827e-05, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 1.0712930659160709, 'early_stopping_min_delta': 0.0010285423944840684}. Best is trial 159 with value: 0.297766251520741.

  Epoch 015 - train 0.56413 | val 0.98244
  Classification -> best τ=0.255 (val F1=0.2637)
  Directional -> Accuracy: 0.4833, MCC: -0.0062, F1: 0.6437

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.281215765430148
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.62332 | val 1.60082
  Epoch 011 - train 0.59667 | val 1.56485
  Classification -> best τ=0.675 (val F1=0.2919)
  Directional -> Accuracy: 0.5395, MCC: -0.1039, F1: 0.0000

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.54321 | val 0.89676
  Epoch 012 - train 0.50083 | val 0.84947
  Classification -> best τ=0.335 (val F1=0.2670)
  Directional -> Accuracy: 0.5556, MCC: 0.0225, F1: 0.6774

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.58102 | val 1.75600
  Epoch 011 - train 0.55488 | val 1.78236
  Classification -> best τ=0.525 (val F1=0.2449)
  Directional -> Accuracy: 0.4783, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.57902 | val 1.00978
  Epoch 011 - train 0.56954 | val 1.68740
  Classification -> best τ=0.420 (val F1=0.2204)
  Directional -> Accuracy: 0.4865, MCC: 0.1005, F1: 0.1364

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.52045 | val 1.25424
  Epoch 012 - train 0.45674 | val 2.29376
  Classification -> best τ=0.645 (val F1=0.4028)
  Directional -> Accuracy: 0.6800, MCC: 0.3870, F1: 0.6364

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.52891 | val 0.72217
  Epoch 020 - train 0.34285 | val 1.05650
  Epoch 022 - train 0.42114 | val 0.88921
  Classification -> best τ=0.565 (val F1=0.3994)
  Directional -> Accuracy: 0.5000, MCC: -0.0334, F1: 0.2581

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.58075 | val 1.13342
  Epoch 011 - train 0.60247 | val 1.15583
  Classification -> best τ=0.580 (val F1=0.3354)
  Directional -> Accuracy: 0.5882, MCC: 0.0378, F1: 0.2222

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.60377 | val 1.51534
  Epoch 020 - train 0.35802 | val 0.67658
  Epoch 027 - train 0.26541 | val 1.51408
  Classification -> best τ=0.345 (val F1=0.3421)
  Directional -> Accuracy: 0.4762, MCC: -0.0142, F1: 0.5000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.55524 | val 2.40307
  Epoch 011 - train 0.53977 | val 2.24083
  Classification -> best τ=0.600 (val F1=0.2764)
  Directional -> Accuracy: 0.6458, MCC: 0.2714, F1: 0.4516

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.59267 | val 1.05876
  Epoch 014 - train 0.52085 | val 0.80417
  Classification -> best τ=0.385 (val F1=0.1885)
  Directional -> Accuracy: 0.4493, MCC: -0.0085, F1: 0.5476

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.60193 | val 1.14644
  Epoch 012 - train 0.57022 | val 0.90483
  Classification -> best τ=0.445 (val F1=0.2670)
  Directional -> Accuracy: 0.5714, MCC: 0.1237, F1: 0.4878

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.63785 | val 1.56003
  Epoch 014 - train 0.51789 | val 1.60359
  Classification -> best τ=0.380 (val F1=0.2349)
  Directional -> Accuracy: 0.5263, MCC: 0.1360, F1: 0.6824

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.51460 | val 1.71654
  Epoch 011 - train 0.46728 | val 1.51384
  Classification -> best τ=0.530 (val F1=0.0465)
  Directional -> Accuracy: 0.4286, MCC: -0.1718, F1: 0.6000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.60989 | val 0.70730
  Epoch 014 - train 0.46611 | val 0.86153
  Classification -> best τ=0.505 (val F1=0.4109)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.57313 | val 1.26900
  Epoch 011 - train 0.51583 | val 1.16064
  Classification -> best τ=0.530 (val F1=0.0921)
  Directional -> Accuracy: 0.5490, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.61187 | val 1.83918
  Epoch 014 - train 0.53555 | val 2.13440
  Classification -> best τ=0.610 (val F1=0.1561)
  Directional -> Accuracy: 0.5797, MCC: 0.1910, F1: 0.5246

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.56513 | val 1.14661
  Epoch 012 - train 0.54224 | val 1.05773
  Classification -> best τ=0.480 (val F1=0.2135)
  Directional -> Accuracy: 0.4483, MCC: 0.2128, F1: 0.2000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.56119 | val 0.78504
  Epoch 011 - train 0.53733 | val 0.85583
  Classification -> best τ=0.685 (val F1=0.1909)
  Directional -> Accuracy: 0.4000, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.58750 | val 0.77699
  Epoch 012 - train 0.51194 | val 0.89846
  Classification -> best τ=0.530 (val F1=0.3763)
  Directional -> Accuracy: 0.4844, MCC: 0.1062, F1: 0.2979

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.57415 | val 1.17195
  Epoch 011 - train 0.49804 | val 1.85110
  Classification -> best τ=0.545 (val F1=0.2470)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.54280 | val 1.24787
  Epoch 013 - train 0.42466 | val 0.91183
  Classification -> best τ=0.385 (val F1=0.1723)
  Directional -> Accuracy: 0.6383, MCC: 0.1871, F1: 0.7733

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.62222 | val 1.30422
  Epoch 011 - train 0.54587 | val 1.28532
  Classification -> best τ=0.245 (val F1=0.2701)
  Directional -> Accuracy: 0.4923, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.59302 | val 0.70244
  Epoch 017 - train 0.52368 | val 0.79173
  Classification -> best τ=0.395 (val F1=0.4370)
  Directional -> Accuracy: 0.5965, MCC: 0.2157, F1: 0.7356

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.57892 | val 0.75093
  Epoch 011 - train 0.54339 | val 0.75196
  Classification -> best τ=0.500 (val F1=0.1686)
  Directional -> Accuracy: 0.4769, MCC: -0.0353, F1: 0.5278

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.59767 | val 1.07053
  Epoch 013 - train 0.50001 | val 1.34410
  Classification -> best τ=0.335 (val F1=0.5197)
  Directional -> Accuracy: 0.5636, MCC: 0.1093, F1: 0.6250

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.52607 | val 1.83948
  Epoch 011 - train 0.43944 | val 2.19188
  Classification -> best τ=0.645 (val F1=0.1890)
  Directional -> Accuracy: 0.4889, MCC: 0.0020, F1: 0.4889

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.63074 | val 0.69569
  Epoch 011 - train 0.55937 | val 0.69870
  Classification -> best τ=0.470 (val F1=0.2107)
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.7273

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.55072 | val 1.35103
  Epoch 011 - train 0.51840 | val 1.39020
  Classification -> best τ=0.295 (val F1=0.2315)
  Directional -> Accuracy: 0.5536, MCC: 0.2640, F1: 0.3590

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.52034 | val 0.70623
  Epoch 020 - train 0.30322 | val 0.78945
  Epoch 022 - train 0.33934 | val 0.76946
  Classification -> best τ=0.625 (val F1=0.5854)
  Directional -> Accuracy: 0.5750, MCC: 0.1140, F1: 0.7018

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.56458 | val 0.65862
  Epoch 018 - train 0.43113 | val 0.97173
  Classification -> best τ=0.425 (val F1=0.4035)
  Directional -> Accuracy: 0.5000, MCC: 0.0196, F1: 0.5714

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.50636 | val 1.43707
  Epoch 011 - train 0.51904 | val 1.26758
  Classification -> best τ=0.580 (val F1=0.1286)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.51162 | val 0.98793
  Epoch 012 - train 0.48709 | val 0.94623
  Classification -> best τ=0.390 (val F1=0.4397)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.59387 | val 0.76755
  Epoch 015 - train 0.55219 | val 0.78503
  Classification -> best τ=0.475 (val F1=0.2970)
  Directional -> Accuracy: 0.4444, MCC: 0.0000, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.50830 | val 1.12302
  Epoch 011 - train 0.45378 | val 1.43700
  Classification -> best τ=0.295 (val F1=0.2717)
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.54125 | val 0.96424
  Epoch 011 - train 0.52076 | val 1.13977
  Classification -> best τ=0.505 (val F1=0.1867)
  Directional -> Accuracy: 0.4394, MCC: -0.0799, F1: 0.3934

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.44759 | val 2.11583
  Epoch 011 - train 0.48494 | val 2.42649
  Classification -> best τ=0.440 (val F1=0.2618)
  Directional -> Accuracy: 0.6667, MCC: 0.3920, F1: 0.5882

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.56864 | val 1.12811
  Epoch 012 - train 0.48065 | val 1.93585
  Classification -> best τ=0.480 (val F1=0.2530)
  Directional -> Accuracy: 0.6071, MCC: 0.2148, F1: 0.5926

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.47168 | val 0.85849
  Epoch 011 - train 0.39762 | val 0.86864
  Classification -> best τ=0.465 (val F1=0.3985)
  Directional -> Accuracy: 0.5870, MCC: 0.0537, F1: 0.7077

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.54854 | val 0.82841
  Epoch 016 - train 0.43443 | val 1.00543
  Classification -> best τ=0.420 (val F1=0.4011)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.55197 | val 1.84998
  Epoch 011 - train 0.46562 | val 2.25678
  Classification -> best τ=0.490 (val F1=0.2709)
  Directional -> Accuracy: 0.4865, MCC: -0.0560, F1: 0.2400

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.57527 | val 1.04472
  Epoch 011 - train 0.51970 | val 1.31342
  Classification -> best τ=0.425 (val F1=0.1976)
  Directional -> Accuracy: 0.5333, MCC: 0.0871, F1: 0.4000

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.46008 | val 3.02990
  Epoch 012 - train 0.35848 | val 2.37305
  Classification -> best τ=0.690 (val F1=0.5230)
  Directional -> Accuracy: 0.5952, MCC: 0.1340, F1: 0.7018

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.53860 | val 1.23814
  Epoch 015 - train 0.40544 | val 0.68817
  Classification -> best τ=0.725 (val F1=0.5557)
  Directional -> Accuracy: 0.6875, MCC: 0.3333, F1: 0.2857

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.60999 | val 1.57045
  Epoch 013 - train 0.57673 | val 1.44358
  Classification -> best τ=0.470 (val F1=0.1763)
  Directional -> Accuracy: 0.3818, MCC: -0.2945, F1: 0.5000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.45436 | val 2.46102
  Epoch 011 - train 0.49684 | val 2.17256
  Classification -> best τ=0.440 (val F1=0.3536)
  Directional -> Accuracy: 0.5179, MCC: 0.0333, F1: 0.4906

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.65295 | val 0.99107
  Epoch 018 - train 0.51590 | val 0.81280
  Classification -> best τ=0.590 (val F1=0.1895)
  Directional -> Accuracy: 0.5849, MCC: 0.1827, F1: 0.5217

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.51710 | val 2.80784
  Epoch 011 - train 0.49574 | val 2.75973
  Classification -> best τ=0.720 (val F1=0.0580)
  Directional -> Accuracy: 0.4727, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.63866 | val 1.33587

[I 2026-02-22 13:23:08,254] Trial 193 finished with value: 0.2850392598358383 and parameters: {'feature_set': 'sector', 'model_type': 'BiGRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.4, 'batch_size': 16, 'learning_rate': 0.0071932263754671995, 'weight_decay': 3.273995921748808e-05, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 1.0726823164568764, 'early_stopping_min_delta': 0.0010678535481887445}. Best is trial 159 with value: 0.297766251520741.

  Epoch 016 - train 0.54298 | val 0.86993
  Classification -> best τ=0.385 (val F1=0.3274)
  Directional -> Accuracy: 0.5500, MCC: 0.1025, F1: 0.5574

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2850392598358383
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.66422 | val 1.32037
  Epoch 012 - train 0.61853 | val 0.95672
  Classification -> best τ=0.530 (val F1=0.2409)
  Directional -> Accuracy: 0.5658, MCC: 0.1296, F1: 0.5352

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.57011 | val 1.09594
  Epoch 011 - train 0.49521 | val 1.24593
  Classification -> best τ=0.715 (val F1=0.2523)
  Directional -> Accuracy: 0.5111, MCC: 0.2029, F1: 0.3125

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.53843 | val 1.87737
  Epoch 011 - train 0.42766 | val 2.03738
  Classification -> best τ=0.875 (val F1=0.1978)
  Directional -> Accuracy: 0.4783, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.63426 | val 0.96667
  Epoch 011 - train 0.54012 | val 1.27477
  Classification -> best τ=0.380 (val F1=0.2593)
  Directional -> Accuracy: 0.5405, MCC: 0.0000, F1: 0.7018

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.54491 | val 1.53266
  Epoch 013 - train 0.45719 | val 1.57637
  Classification -> best τ=0.635 (val F1=0.3968)
  Directional -> Accuracy: 0.6200, MCC: 0.2957, F1: 0.5128

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.52984 | val 0.91575
  Epoch 012 - train 0.47789 | val 0.71175
  Classification -> best τ=0.525 (val F1=0.3624)
  Directional -> Accuracy: 0.5217, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.60697 | val 1.09521
  Epoch 011 - train 0.56739 | val 1.16179
  Classification -> best τ=0.320 (val F1=0.3071)
  Directional -> Accuracy: 0.5000, MCC: 0.1418, F1: 0.5750

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.50633 | val 0.70171
  Epoch 020 - train 0.43855 | val 1.35292
  Epoch 024 - train 0.22498 | val 1.11773
  Classification -> best τ=0.460 (val F1=0.5247)
  Directional -> Accuracy: 0.5000, MCC: 0.0138, F1: 0.4878

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.59966 | val 1.93357
  Epoch 011 - train 0.53714 | val 1.58135
  Classification -> best τ=0.655 (val F1=0.2443)
  Directional -> Accuracy: 0.5833, MCC: 0.1449, F1: 0.5000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.61549 | val 0.71501
  Epoch 020 - train 0.56305 | val 0.77672
  Epoch 026 - train 0.35230 | val 0.99652
  Classification -> best τ=0.525 (val F1=0.3379)
  Directional -> Accuracy: 0.5362, MCC: 0.1557, F1: 0.5897

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.59622 | val 0.97417
  Epoch 017 - train 0.49066 | val 1.40196
  Classification -> best τ=0.610 (val F1=0.2498)
  Directional -> Accuracy: 0.5510, MCC: 0.0453, F1: 0.2667

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.53726 | val 1.68209
  Epoch 011 - train 0.56388 | val 1.53901
  Classification -> best τ=0.570 (val F1=0.1809)
  Directional -> Accuracy: 0.6316, MCC: 0.3023, F1: 0.7123

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.46657 | val 2.30989
  Epoch 011 - train 0.47673 | val 2.70561
  Classification -> best τ=0.365 (val F1=0.0096)
  Directional -> Accuracy: 0.4524, MCC: -0.0605, F1: 0.5306

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.58977 | val 0.60737
  Epoch 020 - train 0.43776 | val 1.50124
  Classification -> best τ=0.490 (val F1=0.3642)
  Directional -> Accuracy: 0.4667, MCC: -0.1857, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.57289 | val 0.88160
  Epoch 019 - train 0.47591 | val 1.25317
  Classification -> best τ=0.655 (val F1=0.2571)
  Directional -> Accuracy: 0.5490, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.60619 | val 1.15242
  Epoch 012 - train 0.54718 | val 1.26897
  Classification -> best τ=0.755 (val F1=0.2224)
  Directional -> Accuracy: 0.5072, MCC: 0.1478, F1: 0.1905

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.57801 | val 1.49875
  Epoch 011 - train 0.52285 | val 1.27138
  Classification -> best τ=0.480 (val F1=0.2540)
  Directional -> Accuracy: 0.3448, MCC: -0.2417, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.57975 | val 1.71389
  Epoch 012 - train 0.54438 | val 1.32416
  Classification -> best τ=0.515 (val F1=0.1548)
  Directional -> Accuracy: 0.4000, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.55507 | val 1.08558
  Epoch 011 - train 0.51352 | val 1.29957
  Classification -> best τ=0.330 (val F1=0.2620)
  Directional -> Accuracy: 0.5469, MCC: 0.0757, F1: 0.6027

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.59138 | val 0.93748
  Epoch 011 - train 0.50850 | val 1.14063
  Classification -> best τ=0.160 (val F1=0.2204)
  Directional -> Accuracy: 0.5541, MCC: 0.0000, F1: 0.7130

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.57213 | val 0.69116
  Epoch 014 - train 0.44261 | val 0.80258
  Classification -> best τ=0.450 (val F1=0.2247)
  Directional -> Accuracy: 0.5957, MCC: -0.1162, F1: 0.7467

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.61037 | val 0.96222
  Epoch 012 - train 0.55279 | val 0.93833
  Classification -> best τ=0.520 (val F1=0.2245)
  Directional -> Accuracy: 0.5231, MCC: 0.1014, F1: 0.2051

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.59749 | val 0.68451
  Epoch 020 - train 0.53349 | val 0.70686
  Epoch 023 - train 0.44419 | val 0.95522
  Classification -> best τ=0.625 (val F1=0.4074)
  Directional -> Accuracy: 0.6316, MCC: 0.2630, F1: 0.6557

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.61156 | val 0.70550
  Epoch 011 - train 0.53612 | val 0.73571
  Classification -> best τ=0.495 (val F1=0.1348)
  Directional -> Accuracy: 0.4923, MCC: -0.0402, F1: 0.3265

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.60033 | val 1.04361
  Epoch 017 - train 0.46921 | val 1.04890
  Classification -> best τ=0.455 (val F1=0.4180)
  Directional -> Accuracy: 0.5636, MCC: 0.1006, F1: 0.6471

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.41647 | val 1.95925
  Epoch 011 - train 0.43001 | val 2.23593
  Classification -> best τ=0.640 (val F1=0.2035)
  Directional -> Accuracy: 0.4444, MCC: -0.0372, F1: 0.5283

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.60066 | val 1.01635
  Epoch 019 - train 0.39982 | val 0.94450
  Classification -> best τ=0.740 (val F1=0.2810)
  Directional -> Accuracy: 0.4762, MCC: 0.0525, F1: 0.3125

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.60665 | val 0.99970
  Epoch 011 - train 0.53908 | val 1.02752
  Classification -> best τ=0.310 (val F1=0.2841)
  Directional -> Accuracy: 0.4107, MCC: -0.1694, F1: 0.0571

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.51917 | val 1.19502
  Epoch 012 - train 0.45919 | val 1.19163
  Classification -> best τ=0.500 (val F1=0.2267)
  Directional -> Accuracy: 0.6250, MCC: 0.3148, F1: 0.7458

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.59959 | val 0.92554
  Epoch 014 - train 0.47682 | val 1.55261
  Classification -> best τ=0.475 (val F1=0.3501)
  Directional -> Accuracy: 0.5000, MCC: 0.0046, F1: 0.5116

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.67871 | val 0.80166
  Epoch 011 - train 0.57693 | val 0.79538
  Classification -> best τ=0.495 (val F1=0.2544)
  Directional -> Accuracy: 0.5476, MCC: 0.0000, F1: 0.7077

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.57028 | val 0.91444
  Epoch 013 - train 0.43473 | val 1.35679
  Classification -> best τ=0.515 (val F1=0.2849)
  Directional -> Accuracy: 0.5306, MCC: 0.0349, F1: 0.6349

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.54615 | val 0.81688
  Epoch 014 - train 0.47738 | val 0.94686
  Classification -> best τ=0.420 (val F1=0.3815)
  Directional -> Accuracy: 0.5139, MCC: 0.1292, F1: 0.3396

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.58687 | val 1.20671
  Epoch 011 - train 0.53765 | val 1.24668
  Classification -> best τ=0.210 (val F1=0.2717)
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.59895 | val 1.38443
  Epoch 011 - train 0.54444 | val 1.74866
  Classification -> best τ=0.745 (val F1=0.1822)
  Directional -> Accuracy: 0.5303, MCC: 0.0060, F1: 0.6265

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.55608 | val 4.34452
  Epoch 011 - train 0.44787 | val 4.03115
  Classification -> best τ=0.540 (val F1=0.2618)
  Directional -> Accuracy: 0.6190, MCC: 0.2864, F1: 0.5294

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.55363 | val 0.91933
  Epoch 011 - train 0.50667 | val 1.07899
  Classification -> best τ=0.520 (val F1=0.2110)
  Directional -> Accuracy: 0.5000, MCC: -0.0051, F1: 0.4615

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.48390 | val 0.89321
  Epoch 011 - train 0.47877 | val 0.89726
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.6087, MCC: 0.0000, F1: 0.7568

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.56852 | val 0.80304
  Epoch 015 - train 0.49626 | val 0.71264
  Classification -> best τ=0.535 (val F1=0.4011)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.53120 | val 2.28953
  Epoch 011 - train 0.56153 | val 2.35071
  Classification -> best τ=0.475 (val F1=0.1388)
  Directional -> Accuracy: 0.4865, MCC: -0.0131, F1: 0.6042

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.60308 | val 0.94986
  Epoch 013 - train 0.54833 | val 0.76417
  Classification -> best τ=0.380 (val F1=0.2169)
  Directional -> Accuracy: 0.5111, MCC: 0.0000, F1: 0.6765

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.39712 | val 1.62645
  Epoch 011 - train 0.39753 | val 2.29109
  Classification -> best τ=0.560 (val F1=0.2381)
  Directional -> Accuracy: 0.5952, MCC: 0.1334, F1: 0.7302

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.52893 | val 0.89339
  Epoch 013 - train 0.43463 | val 0.92548
  Classification -> best τ=0.640 (val F1=0.3672)
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.5455

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.63952 | val 1.18817
  Epoch 011 - train 0.61656 | val 1.28506
  Classification -> best τ=0.640 (val F1=0.2036)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.48529 | val 2.25245
  Epoch 011 - train 0.43734 | val 2.33578
  Classification -> best τ=0.645 (val F1=0.3189)
  Directional -> Accuracy: 0.5714, MCC: 0.1384, F1: 0.5000

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.64291 | val 0.70938
  Epoch 020 - train 0.48786 | val 1.14408
  Epoch 021 - train 0.52405 | val 1.10731
  Classification -> best τ=0.320 (val F1=0.2351)
  Directional -> Accuracy: 0.6038, MCC: 0.2151, F1: 0.6667

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.53455 | val 2.76512
  Epoch 011 - train 0.51246 | val 3.56876
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5273, MCC: 0.0000, F1: 0.6905

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.58667 | val 1.78992

[I 2026-02-22 13:25:48,505] Trial 194 finished with value: 0.25691034224948733 and parameters: {'feature_set': 'sector', 'model_type': 'BiGRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.4, 'batch_size': 16, 'learning_rate': 0.007213539388259929, 'weight_decay': 4.252620702739543e-05, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 1.0739291415640784, 'early_stopping_min_delta': 0.0008773795218109735}. Best is trial 159 with value: 0.297766251520741.

  Epoch 013 - train 0.56817 | val 2.19003
  Classification -> best τ=0.420 (val F1=0.3108)
  Directional -> Accuracy: 0.5167, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.25691034224948733
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.59521 | val 1.11294
  Epoch 016 - train 0.56598 | val 0.96497
  Classification -> best τ=0.795 (val F1=0.2510)
  Directional -> Accuracy: 0.5526, MCC: 0.0000, F1: 0.0000

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.53843 | val 0.71205
  Epoch 020 - train 0.44154 | val 0.95203
  Classification -> best τ=0.305 (val F1=0.1844)
  Directional -> Accuracy: 0.5778, MCC: 0.0000, F1: 0.7324

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.52241 | val 1.78037
  Epoch 011 - train 0.51391 | val 1.85585
  Classification -> best τ=0.765 (val F1=0.1978)
  Directional -> Accuracy: 0.4783, MCC: -0.0134, F1: 0.1429

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.61980 | val 1.01948
  Epoch 020 - train 0.52120 | val 0.96817
  Epoch 026 - train 0.44971 | val 0.88191
  Classification -> best τ=0.430 (val F1=0.1839)
  Directional -> Accuracy: 0.5405, MCC: 0.0000, F1: 0.7018

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.56523 | val 1.21697
  Epoch 011 - train 0.50401 | val 1.29086
  Classification -> best τ=0.710 (val F1=0.3529)
  Directional -> Accuracy: 0.5800, MCC: 0.1922, F1: 0.4878

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.53054 | val 1.42008
  Epoch 013 - train 0.41683 | val 1.24518
  Classification -> best τ=0.640 (val F1=0.2739)
  Directional -> Accuracy: 0.3696, MCC: -0.3110, F1: 0.1714

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.62491 | val 0.79579
  Epoch 012 - train 0.55091 | val 0.99135
  Classification -> best τ=0.335 (val F1=0.2665)
  Directional -> Accuracy: 0.4265, MCC: -0.0025, F1: 0.5412

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.61132 | val 1.50873
  Epoch 018 - train 0.44006 | val 0.85741
  Classification -> best τ=0.550 (val F1=0.3632)
  Directional -> Accuracy: 0.5000, MCC: -0.0138, F1: 0.4324

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.52031 | val 3.15217
  Epoch 013 - train 0.50890 | val 4.54996
  Classification -> best τ=0.665 (val F1=0.2764)
  Directional -> Accuracy: 0.5625, MCC: 0.0646, F1: 0.3226

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.62578 | val 1.15625
  Epoch 013 - train 0.52326 | val 1.14990
  Classification -> best τ=0.495 (val F1=0.2772)
  Directional -> Accuracy: 0.5217, MCC: 0.0707, F1: 0.5217

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.60971 | val 0.73152
  Epoch 019 - train 0.47230 | val 0.98090
  Classification -> best τ=0.555 (val F1=0.2593)
  Directional -> Accuracy: 0.5510, MCC: 0.0519, F1: 0.3125

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.61743 | val 1.24215
  Epoch 011 - train 0.57643 | val 1.50346
  Classification -> best τ=0.430 (val F1=0.1512)
  Directional -> Accuracy: 0.5088, MCC: 0.0000, F1: 0.6744

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.45535 | val 2.14781
  Epoch 011 - train 0.48678 | val 2.18790
  Classification -> best τ=0.550 (val F1=0.1754)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.6230

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.59998 | val 0.63433
  Epoch 012 - train 0.56658 | val 0.71003
  Classification -> best τ=0.635 (val F1=0.3642)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.55248 | val 1.20235
  Epoch 011 - train 0.54195 | val 1.30296
  Classification -> best τ=0.565 (val F1=0.2571)
  Directional -> Accuracy: 0.5490, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.55242 | val 1.43629
  Epoch 011 - train 0.51876 | val 1.76620
  Classification -> best τ=0.665 (val F1=0.0972)
  Directional -> Accuracy: 0.4638, MCC: 0.0000, F1: 0.0000

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.58282 | val 0.90363
  Epoch 019 - train 0.43810 | val 0.86515
  Classification -> best τ=0.355 (val F1=0.3154)
  Directional -> Accuracy: 0.3793, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.56146 | val 1.09934
  Epoch 019 - train 0.40359 | val 1.07726
  Classification -> best τ=0.570 (val F1=0.2424)
  Directional -> Accuracy: 0.4133, MCC: -0.0680, F1: 0.2667

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.59864 | val 1.05084
  Epoch 012 - train 0.52063 | val 1.04106
  Classification -> best τ=0.285 (val F1=0.2803)
  Directional -> Accuracy: 0.4375, MCC: -0.2740, F1: 0.5909

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.54444 | val 1.13498
  Epoch 011 - train 0.50047 | val 1.10868
  Classification -> best τ=0.455 (val F1=0.3433)
  Directional -> Accuracy: 0.4865, MCC: 0.1844, F1: 0.1364

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.48406 | val 1.83217
  Epoch 011 - train 0.52622 | val 1.88914
  Classification -> best τ=0.445 (val F1=0.2247)
  Directional -> Accuracy: 0.5957, MCC: 0.1919, F1: 0.6415

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.58282 | val 1.37021
  Epoch 011 - train 0.52215 | val 1.56207
  Classification -> best τ=0.225 (val F1=0.2281)
  Directional -> Accuracy: 0.4615, MCC: -0.0866, F1: 0.2222

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.60323 | val 0.65079
  Epoch 013 - train 0.57743 | val 0.63535
  Classification -> best τ=0.425 (val F1=0.3800)
  Directional -> Accuracy: 0.6316, MCC: 0.2347, F1: 0.7123

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.61282 | val 1.23010
  Epoch 015 - train 0.49333 | val 2.08973
  Classification -> best τ=0.560 (val F1=0.1348)
  Directional -> Accuracy: 0.4769, MCC: -0.0584, F1: 0.3929

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.60216 | val 0.80005
  Epoch 012 - train 0.50554 | val 1.17035
  Classification -> best τ=0.170 (val F1=0.4051)
  Directional -> Accuracy: 0.6000, MCC: 0.2061, F1: 0.6071

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.51659 | val 3.86630
  Epoch 011 - train 0.44592 | val 3.64730
  Classification -> best τ=0.740 (val F1=0.2726)
  Directional -> Accuracy: 0.5111, MCC: -0.0675, F1: 0.2667

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.62844 | val 0.72560
  Epoch 011 - train 0.58563 | val 0.71328
  Classification -> best τ=0.505 (val F1=0.2041)
  Directional -> Accuracy: 0.5000, MCC: -0.0430, F1: 0.5882

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.52116 | val 0.97416
  Epoch 011 - train 0.46245 | val 1.14909
  Classification -> best τ=0.505 (val F1=0.1354)
  Directional -> Accuracy: 0.4464, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.52934 | val 1.26557
  Epoch 011 - train 0.52329 | val 1.27876
  Classification -> best τ=0.565 (val F1=0.1943)
  Directional -> Accuracy: 0.5500, MCC: 0.0503, F1: 0.6667

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.64074 | val 2.00745
  Epoch 012 - train 0.52276 | val 2.22276
  Classification -> best τ=0.630 (val F1=0.2801)
  Directional -> Accuracy: 0.4762, MCC: -0.0754, F1: 0.3125

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.58390 | val 1.40393
  Epoch 011 - train 0.51935 | val 1.65507
  Classification -> best τ=0.620 (val F1=0.1286)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.54730 | val 0.93456
  Epoch 011 - train 0.47578 | val 1.02062
  Classification -> best τ=0.490 (val F1=0.4023)
  Directional -> Accuracy: 0.5102, MCC: 0.0517, F1: 0.4000

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.59413 | val 1.02277
  Epoch 014 - train 0.48001 | val 1.07034
  Classification -> best τ=0.405 (val F1=0.2975)
  Directional -> Accuracy: 0.4583, MCC: 0.0466, F1: 0.0930

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.52373 | val 1.43057
  Epoch 011 - train 0.45354 | val 1.45003
  Classification -> best τ=0.360 (val F1=0.1309)
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.59176 | val 1.88159
  Epoch 011 - train 0.55689 | val 2.31682
  Classification -> best τ=0.510 (val F1=0.1756)
  Directional -> Accuracy: 0.5758, MCC: 0.0000, F1: 0.7308

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.50106 | val 1.72844
  Epoch 011 - train 0.49661 | val 1.88474
  Classification -> best τ=0.505 (val F1=0.3260)
  Directional -> Accuracy: 0.5952, MCC: 0.2656, F1: 0.4516

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.54785 | val 0.97720
  Epoch 011 - train 0.47393 | val 1.15489
  Classification -> best τ=0.510 (val F1=0.2327)
  Directional -> Accuracy: 0.5714, MCC: 0.1623, F1: 0.6000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.51862 | val 1.22637
  Epoch 011 - train 0.50777 | val 1.02596
  Classification -> best τ=0.720 (val F1=0.2659)
  Directional -> Accuracy: 0.3913, MCC: -0.0687, F1: 0.1250

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.58204 | val 0.82645
  Epoch 017 - train 0.44733 | val 0.99716
  Classification -> best τ=0.380 (val F1=0.3378)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.54465 | val 1.37302
  Epoch 011 - train 0.48518 | val 1.96560
  Classification -> best τ=0.360 (val F1=0.2490)
  Directional -> Accuracy: 0.4595, MCC: -0.1107, F1: 0.2593

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.62849 | val 0.77302
  Epoch 017 - train 0.52122 | val 1.92273
  Classification -> best τ=0.385 (val F1=0.4438)
  Directional -> Accuracy: 0.5333, MCC: 0.0950, F1: 0.6769

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.45078 | val 3.68216
  Epoch 012 - train 0.34768 | val 3.28579
  Classification -> best τ=0.550 (val F1=0.5601)
  Directional -> Accuracy: 0.6667, MCC: 0.3043, F1: 0.7407

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.44070 | val 0.91916
  Epoch 015 - train 0.44242 | val 1.33264
  Classification -> best τ=0.675 (val F1=0.4606)
  Directional -> Accuracy: 0.4792, MCC: 0.2641, F1: 0.5902

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.61727 | val 1.08068
  Epoch 011 - train 0.61467 | val 1.38295
  Classification -> best τ=0.510 (val F1=0.2132)
  Directional -> Accuracy: 0.4364, MCC: -0.0897, F1: 0.2051

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.49879 | val 2.57302
  Epoch 011 - train 0.43959 | val 2.96248
  Classification -> best τ=0.565 (val F1=0.2314)
  Directional -> Accuracy: 0.5000, MCC: -0.0515, F1: 0.1250

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.63117 | val 0.74637
  Epoch 014 - train 0.56718 | val 1.10236
  Classification -> best τ=0.445 (val F1=0.2351)
  Directional -> Accuracy: 0.5094, MCC: 0.0000, F1: 0.6750

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.47830 | val 2.89571
  Epoch 011 - train 0.50925 | val 2.71721
  Classification -> best τ=0.665 (val F1=0.2291)
  Directional -> Accuracy: 0.4727, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.59885 | val 0.83590

[I 2026-02-22 13:28:25,322] Trial 195 finished with value: 0.2657067233885702 and parameters: {'feature_set': 'sector', 'model_type': 'BiGRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.4, 'batch_size': 16, 'learning_rate': 0.007564427740554314, 'weight_decay': 3.211272084502127e-05, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 1.0150412435328073, 'early_stopping_min_delta': 0.0006964629089174448}. Best is trial 159 with value: 0.297766251520741.

  Epoch 013 - train 0.52007 | val 0.82042
  Classification -> best τ=0.625 (val F1=0.2623)
  Directional -> Accuracy: 0.5167, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2657067233885702
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.68832 | val 0.71068
  Epoch 012 - train 0.59874 | val 0.93259
  Classification -> best τ=0.930 (val F1=0.2510)
  Directional -> Accuracy: 0.5526, MCC: 0.0000, F1: 0.0000

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.53809 | val 1.02763
  Epoch 011 - train 0.45487 | val 0.92684
  Classification -> best τ=0.445 (val F1=0.2523)
  Directional -> Accuracy: 0.6667, MCC: 0.3487, F1: 0.6809

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.56900 | val 1.95712
  Epoch 011 - train 0.61029 | val 2.50986
  Classification -> best τ=0.435 (val F1=0.2784)
  Directional -> Accuracy: 0.4130, MCC: -0.2143, F1: 0.5263

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.63833 | val 0.82571
  Epoch 011 - train 0.58712 | val 1.06477
  Classification -> best τ=0.415 (val F1=0.2065)
  Directional -> Accuracy: 0.4189, MCC: -0.1425, F1: 0.3175

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.48723 | val 0.99405
  Epoch 011 - train 0.49305 | val 1.08466
  Classification -> best τ=0.690 (val F1=0.4556)
  Directional -> Accuracy: 0.6000, MCC: 0.2202, F1: 0.5455

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.51904 | val 0.67889
  Epoch 016 - train 0.44401 | val 0.83012
  Classification -> best τ=0.520 (val F1=0.3994)
  Directional -> Accuracy: 0.5217, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.61280 | val 1.07564
  Epoch 011 - train 0.62842 | val 1.14900
  Classification -> best τ=0.765 (val F1=0.1753)
  Directional -> Accuracy: 0.5735, MCC: -0.0405, F1: 0.1212

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.57213 | val 0.76333
  Epoch 015 - train 0.35238 | val 0.80876
  Classification -> best τ=0.170 (val F1=0.3504)
  Directional -> Accuracy: 0.4524, MCC: 0.1353, F1: 0.6102

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.61550 | val 1.86554
  Epoch 011 - train 0.60074 | val 1.86246
  Classification -> best τ=0.745 (val F1=0.2764)
  Directional -> Accuracy: 0.5208, MCC: -0.0242, F1: 0.3030

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.60397 | val 1.41648
  Epoch 012 - train 0.51708 | val 1.14517
  Classification -> best τ=0.630 (val F1=0.1128)
  Directional -> Accuracy: 0.5507, MCC: 0.0385, F1: 0.3673

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.60439 | val 0.77915
  Epoch 011 - train 0.59189 | val 0.69411
  Classification -> best τ=0.630 (val F1=0.2484)
  Directional -> Accuracy: 0.5918, MCC: 0.1804, F1: 0.2308

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.62866 | val 0.92207
  Epoch 011 - train 0.58423 | val 1.02651
  Classification -> best τ=0.495 (val F1=0.1441)
  Directional -> Accuracy: 0.5263, MCC: 0.0675, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.49614 | val 2.32420
  Epoch 013 - train 0.42862 | val 2.09889
  Classification -> best τ=0.445 (val F1=0.1370)
  Directional -> Accuracy: 0.5000, MCC: -0.0138, F1: 0.4324

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.63023 | val 0.84397
  Epoch 012 - train 0.58873 | val 0.89622
  Classification -> best τ=0.420 (val F1=0.3477)
  Directional -> Accuracy: 0.4500, MCC: -0.1558, F1: 0.1081

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.59664 | val 0.86044
  Epoch 011 - train 0.62293 | val 0.98782
  Classification -> best τ=0.550 (val F1=0.1843)
  Directional -> Accuracy: 0.4706, MCC: -0.0279, F1: 0.5263

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.57424 | val 1.23937
  Epoch 011 - train 0.54773 | val 1.19557
  Classification -> best τ=0.730 (val F1=0.1709)
  Directional -> Accuracy: 0.5797, MCC: 0.2524, F1: 0.4314

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.58304 | val 0.80224
  Epoch 013 - train 0.53366 | val 0.88818
  Classification -> best τ=0.235 (val F1=0.3455)
  Directional -> Accuracy: 0.4138, MCC: 0.0322, F1: 0.1905

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.58552 | val 1.03232
  Epoch 013 - train 0.55413 | val 1.24394
  Classification -> best τ=0.570 (val F1=0.2367)
  Directional -> Accuracy: 0.4267, MCC: 0.1351, F1: 0.0851

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.66494 | val 1.03264
  Epoch 014 - train 0.52431 | val 1.61708
  Classification -> best τ=0.365 (val F1=0.3513)
  Directional -> Accuracy: 0.4844, MCC: -0.0020, F1: 0.4762

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.56360 | val 1.37413
  Epoch 011 - train 0.52341 | val 1.53291
  Classification -> best τ=0.470 (val F1=0.1838)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.59733 | val 1.38865
  Epoch 013 - train 0.44233 | val 1.03727
  Classification -> best τ=0.600 (val F1=0.2309)
  Directional -> Accuracy: 0.4468, MCC: 0.0837, F1: 0.2778

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.59603 | val 0.81232
  Epoch 012 - train 0.57611 | val 0.90320
  Classification -> best τ=0.525 (val F1=0.2830)
  Directional -> Accuracy: 0.4923, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.63450 | val 0.60686
  Epoch 018 - train 0.51827 | val 0.75466
  Classification -> best τ=0.425 (val F1=0.5089)
  Directional -> Accuracy: 0.5614, MCC: 0.1620, F1: 0.5283

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.64021 | val 0.75208
  Epoch 012 - train 0.53758 | val 0.73612
  Classification -> best τ=0.390 (val F1=0.1348)
  Directional -> Accuracy: 0.4923, MCC: -0.0220, F1: 0.4407

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.53398 | val 1.41069
  Epoch 012 - train 0.52652 | val 0.87653
  Classification -> best τ=0.425 (val F1=0.6369)
  Directional -> Accuracy: 0.5455, MCC: 0.1826, F1: 0.3902

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.52447 | val 4.11079
  Epoch 012 - train 0.38623 | val 4.94628
  Classification -> best τ=0.845 (val F1=0.2726)
  Directional -> Accuracy: 0.6222, MCC: 0.2110, F1: 0.5143

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.62163 | val 0.76177
  Epoch 013 - train 0.52535 | val 0.70205
  Classification -> best τ=0.545 (val F1=0.2582)
  Directional -> Accuracy: 0.5476, MCC: 0.2582, F1: 0.3871

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.56060 | val 1.11726
  Epoch 011 - train 0.51176 | val 1.26956
  Classification -> best τ=0.455 (val F1=0.3265)
  Directional -> Accuracy: 0.4464, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.58095 | val 0.88380
  Epoch 013 - train 0.46816 | val 0.86638
  Classification -> best τ=0.450 (val F1=0.3278)
  Directional -> Accuracy: 0.5750, MCC: 0.1770, F1: 0.7213

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.60981 | val 2.00133
  Epoch 016 - train 0.50564 | val 0.94041
  Classification -> best τ=0.470 (val F1=0.3979)
  Directional -> Accuracy: 0.5000, MCC: -0.0142, F1: 0.4000

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.69313 | val 0.79770
  Epoch 012 - train 0.58220 | val 0.79773
  Classification -> best τ=0.425 (val F1=0.2357)
  Directional -> Accuracy: 0.5476, MCC: 0.0000, F1: 0.7077

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.52970 | val 0.90772
  Epoch 011 - train 0.47514 | val 0.86245
  Classification -> best τ=0.310 (val F1=0.3714)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.59352 | val 1.07661
  Epoch 011 - train 0.54767 | val 0.99863
  Classification -> best τ=0.415 (val F1=0.3008)
  Directional -> Accuracy: 0.4444, MCC: 0.0000, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.52393 | val 1.09527
  Epoch 011 - train 0.45011 | val 1.25844
  Classification -> best τ=0.625 (val F1=0.0528)
  Directional -> Accuracy: 0.5814, MCC: 0.1835, F1: 0.4000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.59159 | val 1.82770
  Epoch 011 - train 0.55820 | val 2.11617
  Classification -> best τ=0.645 (val F1=0.2726)
  Directional -> Accuracy: 0.5606, MCC: -0.1065, F1: 0.7184

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.42193 | val 1.74316
  Epoch 013 - train 0.37312 | val 2.13105
  Classification -> best τ=0.525 (val F1=0.3589)
  Directional -> Accuracy: 0.5714, MCC: 0.1972, F1: 0.4375

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.61240 | val 0.88592
  Epoch 012 - train 0.47916 | val 0.99674
  Classification -> best τ=0.530 (val F1=0.1572)
  Directional -> Accuracy: 0.5536, MCC: 0.0965, F1: 0.1379

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.49240 | val 1.14254
  Epoch 011 - train 0.44169 | val 1.14008
  Classification -> best τ=0.615 (val F1=0.2659)
  Directional -> Accuracy: 0.3913, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.47844 | val 0.92568
  Epoch 019 - train 0.42446 | val 0.76220
  Classification -> best τ=0.595 (val F1=0.4011)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.53433 | val 2.27374
  Epoch 011 - train 0.52784 | val 2.20155
  Classification -> best τ=0.145 (val F1=0.2169)
  Directional -> Accuracy: 0.4865, MCC: 0.0000, F1: 0.6545

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.57153 | val 0.65933
  Epoch 020 - train 0.35584 | val 1.04391
  Classification -> best τ=0.645 (val F1=0.5000)
  Directional -> Accuracy: 0.5556, MCC: 0.1425, F1: 0.4118

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.42711 | val 4.15953
  Epoch 012 - train 0.35999 | val 3.72906
  Classification -> best τ=0.485 (val F1=0.5092)
  Directional -> Accuracy: 0.6429, MCC: 0.2527, F1: 0.7170

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.51839 | val 1.71423
  Epoch 011 - train 0.38663 | val 1.97940
  Classification -> best τ=0.575 (val F1=0.4795)
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.0000

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.63200 | val 1.56971
  Epoch 012 - train 0.64042 | val 1.78960
  Classification -> best τ=0.345 (val F1=0.2228)
  Directional -> Accuracy: 0.4727, MCC: -0.1463, F1: 0.6133

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.46810 | val 2.23136
  Epoch 011 - train 0.48529 | val 1.95862
  Classification -> best τ=0.485 (val F1=0.3249)
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.6506

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.65506 | val 1.02282
  Epoch 015 - train 0.58208 | val 0.98069
  Classification -> best τ=0.780 (val F1=0.2064)
  Directional -> Accuracy: 0.6226, MCC: 0.2468, F1: 0.6154

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.58067 | val 1.05511
  Epoch 016 - train 0.47034 | val 2.90123
  Classification -> best τ=0.910 (val F1=0.2291)
  Directional -> Accuracy: 0.4727, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.67466 | val 0.86914

[I 2026-02-22 13:30:55,447] Trial 196 finished with value: 0.28717929908768774 and parameters: {'feature_set': 'sector', 'model_type': 'BiGRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.4, 'batch_size': 16, 'learning_rate': 0.009852344459020237, 'weight_decay': 4.2319311487857195e-05, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 0.9699075250137105, 'early_stopping_min_delta': 0.0010435147774642635}. Best is trial 159 with value: 0.297766251520741.

  Epoch 018 - train 0.53657 | val 1.79391
  Classification -> best τ=0.390 (val F1=0.1942)
  Directional -> Accuracy: 0.5167, MCC: 0.0218, F1: 0.3830

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.28717929908768774
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.61887 | val 0.89131
  Epoch 012 - train 0.60994 | val 1.53192
  Classification -> best τ=0.555 (val F1=0.2510)
  Directional -> Accuracy: 0.5789, MCC: 0.1259, F1: 0.4286

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.62196 | val 0.93522
  Epoch 012 - train 0.54000 | val 1.36185
  Classification -> best τ=0.470 (val F1=0.1844)
  Directional -> Accuracy: 0.6000, MCC: 0.1323, F1: 0.7353

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.64443 | val 1.51562
  Epoch 012 - train 0.53667 | val 1.72632
  Classification -> best τ=0.590 (val F1=0.3171)
  Directional -> Accuracy: 0.4783, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.62831 | val 1.25907
  Epoch 013 - train 0.57030 | val 0.96337
  Classification -> best τ=0.465 (val F1=0.1745)
  Directional -> Accuracy: 0.5135, MCC: 0.2204, F1: 0.1818

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.54825 | val 2.93285
  Epoch 011 - train 0.46118 | val 3.45250
  Classification -> best τ=0.490 (val F1=0.4291)
  Directional -> Accuracy: 0.6000, MCC: 0.2300, F1: 0.5238

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.54197 | val 0.85539
  Epoch 011 - train 0.52666 | val 0.90134
  Classification -> best τ=0.610 (val F1=0.2699)
  Directional -> Accuracy: 0.5435, MCC: 0.1557, F1: 0.0870

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.62956 | val 1.03461
  Epoch 012 - train 0.57481 | val 1.01159
  Classification -> best τ=0.445 (val F1=0.2931)
  Directional -> Accuracy: 0.5294, MCC: 0.1909, F1: 0.5897

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.48828 | val 0.75340
  Epoch 011 - train 0.49298 | val 0.68023
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.56757 | val 2.40040
  Epoch 011 - train 0.51224 | val 3.34675
  Classification -> best τ=0.645 (val F1=0.2764)
  Directional -> Accuracy: 0.4792, MCC: -0.0316, F1: 0.4681

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.61396 | val 0.86278
  Epoch 012 - train 0.53270 | val 0.82249
  Classification -> best τ=0.750 (val F1=0.1200)
  Directional -> Accuracy: 0.5362, MCC: 0.0301, F1: 0.4074

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.66403 | val 0.71117
  Epoch 013 - train 0.53584 | val 1.11632
  Classification -> best τ=0.375 (val F1=0.3231)
  Directional -> Accuracy: 0.5918, MCC: 0.1804, F1: 0.2308

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.63801 | val 0.83342
  Epoch 012 - train 0.56462 | val 1.18040
  Classification -> best τ=0.595 (val F1=0.1560)
  Directional -> Accuracy: 0.5088, MCC: 0.0172, F1: 0.5172

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.50658 | val 0.92991
  Epoch 011 - train 0.47800 | val 0.72991
  Classification -> best τ=0.565 (val F1=0.3536)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.6230

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.63836 | val 0.64872
  Epoch 020 - train 0.47147 | val 0.79677
  Classification -> best τ=0.600 (val F1=0.2531)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.64695 | val 0.82407
  Epoch 017 - train 0.46510 | val 1.91796
  Classification -> best τ=0.580 (val F1=0.3000)
  Directional -> Accuracy: 0.4706, MCC: -0.2086, F1: 0.0690

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.63675 | val 0.92840
  Epoch 011 - train 0.56784 | val 0.99930
  Classification -> best τ=0.745 (val F1=0.2738)
  Directional -> Accuracy: 0.5507, MCC: 0.1458, F1: 0.4561

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.60590 | val 2.52900
  Epoch 011 - train 0.58885 | val 2.33516
  Classification -> best τ=0.315 (val F1=0.1905)
  Directional -> Accuracy: 0.6207, MCC: 0.0000, F1: 0.7660

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.62243 | val 0.69514
  Epoch 014 - train 0.56911 | val 0.84030
  Classification -> best τ=0.560 (val F1=0.1909)
  Directional -> Accuracy: 0.4000, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.63039 | val 1.67534
  Epoch 014 - train 0.49854 | val 2.06384
  Classification -> best τ=0.360 (val F1=0.3421)
  Directional -> Accuracy: 0.5000, MCC: 0.0149, F1: 0.5152

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.55565 | val 1.20773
  Epoch 012 - train 0.49697 | val 1.52167
  Classification -> best τ=0.440 (val F1=0.2096)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.53696 | val 1.07960
  Epoch 016 - train 0.47722 | val 0.94059
  Classification -> best τ=0.655 (val F1=0.2559)
  Directional -> Accuracy: 0.3830, MCC: -0.1090, F1: 0.2162

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.57115 | val 1.20087
  Epoch 011 - train 0.52012 | val 1.08820
  Classification -> best τ=0.495 (val F1=0.2843)
  Directional -> Accuracy: 0.5538, MCC: 0.2077, F1: 0.2564

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.60197 | val 1.12107
  Epoch 019 - train 0.52208 | val 2.42925
  Classification -> best τ=0.555 (val F1=0.3667)
  Directional -> Accuracy: 0.6491, MCC: 0.2819, F1: 0.6970

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.60444 | val 0.80015
  Epoch 012 - train 0.58325 | val 0.74565
  Classification -> best τ=0.490 (val F1=0.1985)
  Directional -> Accuracy: 0.5231, MCC: 0.0000, F1: 0.0000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.57028 | val 0.83536
  Epoch 018 - train 0.46603 | val 1.29550
  Classification -> best τ=0.255 (val F1=0.5463)
  Directional -> Accuracy: 0.5455, MCC: 0.0690, F1: 0.6154

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.52573 | val 2.40310
  Epoch 012 - train 0.47663 | val 1.55959
  Classification -> best τ=0.625 (val F1=0.3764)
  Directional -> Accuracy: 0.5556, MCC: 0.1469, F1: 0.5652

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.57736 | val 1.41696
  Epoch 012 - train 0.56447 | val 0.97992
  Classification -> best τ=0.535 (val F1=0.2161)
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.0000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.60023 | val 0.91991
  Epoch 011 - train 0.51173 | val 0.94593
  Classification -> best τ=0.495 (val F1=0.2622)
  Directional -> Accuracy: 0.4464, MCC: -0.0207, F1: 0.0606

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.53170 | val 0.71552
  Epoch 017 - train 0.43483 | val 0.77877
  Classification -> best τ=0.435 (val F1=0.3518)
  Directional -> Accuracy: 0.5500, MCC: 0.0335, F1: 0.6897

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.63274 | val 0.87688
  Epoch 018 - train 0.52235 | val 1.80615
  Classification -> best τ=0.705 (val F1=0.4673)
  Directional -> Accuracy: 0.5000, MCC: 0.0046, F1: 0.5116

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.56686 | val 1.97514
  Epoch 014 - train 0.55016 | val 2.17024
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5476, MCC: 0.0000, F1: 0.7077

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.58908 | val 0.78148
  Epoch 012 - train 0.46852 | val 0.79167
  Classification -> best τ=0.300 (val F1=0.3196)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.61743 | val 0.72957
  Epoch 020 - train 0.53642 | val 1.28479
  Epoch 022 - train 0.49328 | val 1.49001
  Classification -> best τ=0.255 (val F1=0.3801)
  Directional -> Accuracy: 0.5000, MCC: 0.0747, F1: 0.3571

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.57529 | val 1.35235
  Epoch 015 - train 0.47932 | val 1.43435
  Classification -> best τ=0.390 (val F1=0.1874)
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.57919 | val 1.68220
  Epoch 011 - train 0.59155 | val 1.91749
  Classification -> best τ=0.660 (val F1=0.1348)
  Directional -> Accuracy: 0.4242, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.54281 | val 1.30130
  Epoch 012 - train 0.43651 | val 1.65024
  Classification -> best τ=0.575 (val F1=0.2665)
  Directional -> Accuracy: 0.6190, MCC: 0.2864, F1: 0.5294

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.57042 | val 0.93115
  Epoch 012 - train 0.50956 | val 1.16401
  Classification -> best τ=0.310 (val F1=0.2530)
  Directional -> Accuracy: 0.4643, MCC: -0.0716, F1: 0.4444

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.47864 | val 1.15221
  Epoch 011 - train 0.42872 | val 1.17441
  Classification -> best τ=0.475 (val F1=0.3367)
  Directional -> Accuracy: 0.6087, MCC: 0.0687, F1: 0.7429

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.72732 | val 0.95683
  Epoch 011 - train 0.58858 | val 0.79467
  Classification -> best τ=0.545 (val F1=0.4011)
  Directional -> Accuracy: 0.5625, MCC: 0.2464, F1: 0.5714

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.55706 | val 2.21312
  Epoch 011 - train 0.49713 | val 2.66978
  Classification -> best τ=0.545 (val F1=0.2700)
  Directional -> Accuracy: 0.5270, MCC: 0.0741, F1: 0.1026

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.58626 | val 0.70278
  Epoch 014 - train 0.50202 | val 1.60802
  Classification -> best τ=0.495 (val F1=0.3287)
  Directional -> Accuracy: 0.5111, MCC: 0.0199, F1: 0.5417

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.45925 | val 1.53093
  Epoch 012 - train 0.33924 | val 1.73806
  Classification -> best τ=0.580 (val F1=0.4588)
  Directional -> Accuracy: 0.6429, MCC: 0.2527, F1: 0.7170

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.55176 | val 0.67091
  Epoch 020 - train 0.35232 | val 2.64157
  Epoch 022 - train 0.27605 | val 2.21818
  Classification -> best τ=0.850 (val F1=0.6110)
  Directional -> Accuracy: 0.6250, MCC: 0.3055, F1: 0.6087

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.67891 | val 1.03185
  Epoch 015 - train 0.58925 | val 1.11580
  Classification -> best τ=0.680 (val F1=0.2036)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.53659 | val 1.10551
  Epoch 011 - train 0.45342 | val 1.27280
  Classification -> best τ=0.220 (val F1=0.2491)
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.6506

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.61629 | val 0.79669
  Epoch 014 - train 0.62923 | val 0.68610
  Classification -> best τ=0.670 (val F1=0.2719)
  Directional -> Accuracy: 0.6226, MCC: 0.2450, F1: 0.6296

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.54026 | val 1.44689
  Epoch 013 - train 0.51524 | val 2.34648
  Classification -> best τ=0.460 (val F1=0.1874)
  Directional -> Accuracy: 0.4727, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.63167 | val 1.23414

[I 2026-02-22 13:33:34,633] Trial 197 finished with value: 0.2779919032780766 and parameters: {'feature_set': 'sector', 'model_type': 'BiGRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.4, 'batch_size': 16, 'learning_rate': 0.00993520602284528, 'weight_decay': 4.778207480595577e-05, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 0.9656921841427191, 'early_stopping_min_delta': 0.0015151946849839683}. Best is trial 159 with value: 0.297766251520741.

  Epoch 012 - train 0.61585 | val 1.17986
  Classification -> best τ=0.355 (val F1=0.2501)
  Directional -> Accuracy: 0.5333, MCC: 0.0733, F1: 0.5625

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2779919032780766
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.68580 | val 0.67744
  Epoch 013 - train 0.70638 | val 0.67956
  Classification -> best τ=0.360 (val F1=0.1903)
  Directional -> Accuracy: 0.5132, MCC: 0.1951, F1: 0.6408

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.67370 | val 0.71039
  Epoch 011 - train 0.68063 | val 0.71048
  Classification -> best τ=0.515 (val F1=0.3119)
  Directional -> Accuracy: 0.3333, MCC: -0.3002, F1: 0.2500

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.71661 | val 0.73185
  Epoch 011 - train 0.71946 | val 0.72922
  Classification -> best τ=0.470 (val F1=0.1978)
  Directional -> Accuracy: 0.4348, MCC: -0.1234, F1: 0.3158

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.69136 | val 0.70782
  Epoch 011 - train 0.69912 | val 0.71000
  Classification -> best τ=0.535 (val F1=0.1269)
  Directional -> Accuracy: 0.5405, MCC: 0.0000, F1: 0.7018

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.68689 | val 0.66941
  Epoch 020 - train 0.65805 | val 0.65461
  Epoch 030 - train 0.63970 | val 0.64115
  Classification -> best τ=0.530 (val F1=0.5298)
  Directional -> Accuracy: 0.6400, MCC: 0.3036, F1: 0.5909

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.72128 | val 0.69622
  Epoch 014 - train 0.69074 | val 0.69734
  Classification -> best τ=0.510 (val F1=0.0726)
  Directional -> Accuracy: 0.5000, MCC: 0.1427, F1: 0.6567

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.69775 | val 0.72591
  Epoch 011 - train 0.69748 | val 0.72991
  Classification -> best τ=0.480 (val F1=0.0648)
  Directional -> Accuracy: 0.4412, MCC: -0.0669, F1: 0.4571

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.69260 | val 0.70142
  Epoch 011 - train 0.69801 | val 0.71052
  Classification -> best τ=0.480 (val F1=0.1873)
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.69374 | val 0.70251
  Epoch 011 - train 0.67138 | val 0.70606
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4375, MCC: 0.0000, F1: 0.6087

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.69583 | val 0.73153
  Epoch 011 - train 0.67866 | val 0.73209
  Classification -> best τ=0.460 (val F1=0.1668)
  Directional -> Accuracy: 0.5072, MCC: -0.0780, F1: 0.2609

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.65843 | val 0.70070
  Epoch 011 - train 0.67629 | val 0.70417
  Classification -> best τ=0.480 (val F1=0.2285)
  Directional -> Accuracy: 0.5510, MCC: 0.0926, F1: 0.5000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.69866 | val 0.70813
  Epoch 013 - train 0.69453 | val 0.70963
  Classification -> best τ=0.495 (val F1=0.2353)
  Directional -> Accuracy: 0.6491, MCC: 0.2993, F1: 0.6774

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.67018 | val 0.73346
  Epoch 011 - train 0.67213 | val 0.73533
  Classification -> best τ=0.520 (val F1=0.2123)
  Directional -> Accuracy: 0.5000, MCC: 0.0046, F1: 0.4878

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.69003 | val 0.69519
  Epoch 011 - train 0.68164 | val 0.70017
  Classification -> best τ=0.490 (val F1=0.1230)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0625

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.69846 | val 0.72342
  Epoch 011 - train 0.69732 | val 0.72454
  Classification -> best τ=0.485 (val F1=0.0211)
  Directional -> Accuracy: 0.5490, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.69419 | val 0.69135
  Epoch 012 - train 0.68906 | val 0.69275
  Classification -> best τ=0.525 (val F1=0.2155)
  Directional -> Accuracy: 0.4783, MCC: -0.0978, F1: 0.6000

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.69056 | val 0.78591
  Epoch 011 - train 0.69483 | val 0.78807
  Classification -> best τ=0.560 (val F1=0.1842)
  Directional -> Accuracy: 0.3793, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.68958 | val 0.68762
  Epoch 020 - train 0.68012 | val 0.68427
  Epoch 024 - train 0.66010 | val 0.68783
  Classification -> best τ=0.465 (val F1=0.2537)
  Directional -> Accuracy: 0.5733, MCC: -0.1351, F1: 0.7288

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.67677 | val 0.67134
  Epoch 020 - train 0.66520 | val 0.67447
  Classification -> best τ=0.340 (val F1=0.2843)
  Directional -> Accuracy: 0.5312, MCC: 0.1003, F1: 0.5161

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.67493 | val 0.67177
  Epoch 017 - train 0.65226 | val 0.68070
  Classification -> best τ=0.390 (val F1=0.2980)
  Directional -> Accuracy: 0.6757, MCC: 0.3403, F1: 0.7143

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.68738 | val 0.69755
  Epoch 011 - train 0.69541 | val 0.69721
  Classification -> best τ=0.530 (val F1=0.1854)
  Directional -> Accuracy: 0.6170, MCC: 0.4355, F1: 0.5500

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.71605 | val 0.69601
  Epoch 011 - train 0.69811 | val 0.69512
  Classification -> best τ=0.510 (val F1=0.1925)
  Directional -> Accuracy: 0.4923, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.66806 | val 0.67449
  Epoch 020 - train 0.68470 | val 0.67697
  Epoch 027 - train 0.68106 | val 0.67704
  Classification -> best τ=0.495 (val F1=0.2996)
  Directional -> Accuracy: 0.5614, MCC: 0.0981, F1: 0.6269

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.70104 | val 0.67976
  Epoch 013 - train 0.67401 | val 0.68281
  Classification -> best τ=0.405 (val F1=0.2906)
  Directional -> Accuracy: 0.4615, MCC: -0.0619, F1: 0.5679

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.68311 | val 0.68158
  Epoch 020 - train 0.67954 | val 0.66942
  Epoch 030 - train 0.65743 | val 0.66183
  Classification -> best τ=0.560 (val F1=0.4524)
  Directional -> Accuracy: 0.5273, MCC: 0.1143, F1: 0.4091

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.69181 | val 0.67333
  Epoch 017 - train 0.69403 | val 0.67645
  Classification -> best τ=0.460 (val F1=0.2935)
  Directional -> Accuracy: 0.4889, MCC: 0.2285, F1: 0.6230

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.67981 | val 0.68464
  Epoch 013 - train 0.69783 | val 0.68622
  Classification -> best τ=0.595 (val F1=0.1936)
  Directional -> Accuracy: 0.5000, MCC: 0.1698, F1: 0.2759

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.67582 | val 0.68857
  Epoch 020 - train 0.66526 | val 0.67159
  Epoch 030 - train 0.65942 | val 0.67224
  Classification -> best τ=0.265 (val F1=0.2315)
  Directional -> Accuracy: 0.5893, MCC: 0.2696, F1: 0.4889

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.68155 | val 0.69999
  Epoch 013 - train 0.68206 | val 0.70394
  Classification -> best τ=0.520 (val F1=0.2774)
  Directional -> Accuracy: 0.4750, MCC: 0.0060, F1: 0.3226

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.69988 | val 0.68736
  Epoch 018 - train 0.69176 | val 0.68797
  Classification -> best τ=0.515 (val F1=0.3612)
  Directional -> Accuracy: 0.4762, MCC: -0.0754, F1: 0.3125

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.68214 | val 0.75614
  Epoch 011 - train 0.70155 | val 0.75833
  Classification -> best τ=0.450 (val F1=0.2357)
  Directional -> Accuracy: 0.4524, MCC: -0.0310, F1: 0.1481

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.68974 | val 0.67084
  Epoch 020 - train 0.65966 | val 0.67372
  Epoch 026 - train 0.66460 | val 0.67128
  Classification -> best τ=0.420 (val F1=0.3714)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.69879 | val 0.69734
  Epoch 015 - train 0.68886 | val 0.69589
  Classification -> best τ=0.580 (val F1=0.2714)
  Directional -> Accuracy: 0.5417, MCC: 0.2244, F1: 0.3529

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.70387 | val 0.68849
  Epoch 013 - train 0.69932 | val 0.68888
  Classification -> best τ=0.470 (val F1=0.1508)
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.66847 | val 0.69449
  Epoch 011 - train 0.67565 | val 0.69441
  Classification -> best τ=0.485 (val F1=0.0606)
  Directional -> Accuracy: 0.5606, MCC: 0.1647, F1: 0.5397

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.69059 | val 0.72740
  Epoch 011 - train 0.70041 | val 0.72825
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5238, MCC: 0.0000, F1: 0.6875

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.69399 | val 0.70391
  Epoch 015 - train 0.69215 | val 0.70444
  Classification -> best τ=0.530 (val F1=0.1615)
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.0000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.70272 | val 0.79365
  Epoch 011 - train 0.67551 | val 0.79277
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.6087, MCC: 0.0000, F1: 0.7568

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.69539 | val 0.69019
  Epoch 011 - train 0.71094 | val 0.68985
  Classification -> best τ=0.485 (val F1=0.1548)
  Directional -> Accuracy: 0.5000, MCC: -0.0930, F1: 0.2941

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.67494 | val 0.69459
  Epoch 013 - train 0.68173 | val 0.69609
  Classification -> best τ=0.445 (val F1=0.3548)
  Directional -> Accuracy: 0.4865, MCC: -0.0367, F1: 0.3871

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.69010 | val 0.68127
  Epoch 020 - train 0.69850 | val 0.68061
  Epoch 030 - train 0.66599 | val 0.67465
  Classification -> best τ=0.525 (val F1=0.5292)
  Directional -> Accuracy: 0.6222, MCC: 0.2713, F1: 0.7018

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.67846 | val 0.70961
  Epoch 011 - train 0.70132 | val 0.70984
  Classification -> best τ=0.520 (val F1=0.3118)
  Directional -> Accuracy: 0.5952, MCC: 0.1795, F1: 0.6383

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.70989 | val 0.84050
  Epoch 011 - train 0.68579 | val 0.82563
  Classification -> best τ=0.540 (val F1=0.1371)
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.5455

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.69993 | val 0.72802
  Epoch 011 - train 0.69519 | val 0.72682
  Classification -> best τ=0.455 (val F1=0.2735)
  Directional -> Accuracy: 0.6364, MCC: 0.2667, F1: 0.6667

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.69272 | val 0.67360
  Epoch 020 - train 0.67355 | val 0.68333
  Epoch 022 - train 0.67327 | val 0.68668
  Classification -> best τ=0.510 (val F1=0.3729)
  Directional -> Accuracy: 0.4464, MCC: -0.1284, F1: 0.3111

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.70560 | val 0.67436
  Epoch 014 - train 0.68699 | val 0.67518
  Classification -> best τ=0.490 (val F1=0.2351)
  Directional -> Accuracy: 0.5094, MCC: 0.0000, F1: 0.6750

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.68765 | val 0.72650
  Epoch 011 - train 0.70078 | val 0.72682
  Classification -> best τ=0.505 (val F1=0.1647)
  Directional -> Accuracy: 0.5636, MCC: 0.1258, F1: 0.6842

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.70510 | val 0.67378

[I 2026-02-22 13:36:34,413] Trial 198 finished with value: 0.22522337133614823 and parameters: {'feature_set': 'sector', 'model_type': 'BiGRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.4, 'batch_size': 16, 'learning_rate': 2.2080716700632027e-05, 'weight_decay': 4.9099542559765614e-05, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 1.1332522298038337, 'early_stopping_min_delta': 0.0016392141057270672}. Best is trial 159 with value: 0.297766251520741.

  Epoch 016 - train 0.69962 | val 0.67364
  Classification -> best τ=0.420 (val F1=0.3436)
  Directional -> Accuracy: 0.5000, MCC: -0.0105, F1: 0.4000

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.22522337133614823
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.65250 | val 0.90541
  Epoch 012 - train 0.62532 | val 1.00228
  Classification -> best τ=0.455 (val F1=0.1635)
  Directional -> Accuracy: 0.5921, MCC: 0.1649, F1: 0.5079

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.56356 | val 0.81855
  Epoch 012 - train 0.52522 | val 1.05537
  Classification -> best τ=0.430 (val F1=0.3123)
  Directional -> Accuracy: 0.6444, MCC: 0.2475, F1: 0.7419

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.58165 | val 1.45950
  Epoch 012 - train 0.51777 | val 1.27294
  Classification -> best τ=0.325 (val F1=0.1572)
  Directional -> Accuracy: 0.5217, MCC: 0.0000, F1: 0.6857

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.64823 | val 0.74455
  Epoch 020 - train 0.55552 | val 0.79424
  Epoch 026 - train 0.53063 | val 1.02617
  Classification -> best τ=0.385 (val F1=0.2920)
  Directional -> Accuracy: 0.5405, MCC: 0.0000, F1: 0.7018

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.50597 | val 2.66981
  Epoch 011 - train 0.48008 | val 2.82785
  Classification -> best τ=0.635 (val F1=0.3331)
  Directional -> Accuracy: 0.6400, MCC: 0.3158, F1: 0.5714

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.55033 | val 0.75603
  Epoch 014 - train 0.40518 | val 0.75484
  Classification -> best τ=0.690 (val F1=0.3644)
  Directional -> Accuracy: 0.5217, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.63737 | val 1.58817
  Epoch 015 - train 0.55544 | val 1.93580
  Classification -> best τ=0.385 (val F1=0.2766)
  Directional -> Accuracy: 0.5294, MCC: -0.0220, F1: 0.3333

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.56186 | val 1.17748
  Epoch 017 - train 0.35948 | val 0.87829
  Classification -> best τ=0.395 (val F1=0.3632)
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.60125 | val 2.72221
  Epoch 012 - train 0.49934 | val 2.58901
  Classification -> best τ=0.440 (val F1=0.1465)
  Directional -> Accuracy: 0.5833, MCC: 0.1449, F1: 0.5000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.62396 | val 0.85599
  Epoch 020 - train 0.49525 | val 0.73269
  Epoch 028 - train 0.42409 | val 0.70657
  Classification -> best τ=0.525 (val F1=0.2307)
  Directional -> Accuracy: 0.5362, MCC: 0.0111, F1: 0.3600

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.64043 | val 1.27329
  Epoch 011 - train 0.56739 | val 1.59374
  Classification -> best τ=0.400 (val F1=0.1483)
  Directional -> Accuracy: 0.5306, MCC: 0.1036, F1: 0.5818

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.63382 | val 0.83842
  Epoch 013 - train 0.54808 | val 0.81570
  Classification -> best τ=0.555 (val F1=0.2819)
  Directional -> Accuracy: 0.5263, MCC: 0.1360, F1: 0.6824

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.48081 | val 1.30583
  Epoch 011 - train 0.43681 | val 1.53948
  Classification -> best τ=0.625 (val F1=0.1370)
  Directional -> Accuracy: 0.5714, MCC: 0.1158, F1: 0.4375

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.61300 | val 0.64848
  Epoch 018 - train 0.56559 | val 1.07107
  Classification -> best τ=0.310 (val F1=0.3994)
  Directional -> Accuracy: 0.5167, MCC: 0.0335, F1: 0.4912

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.63254 | val 0.83997
  Epoch 013 - train 0.54634 | val 0.70404
  Classification -> best τ=0.495 (val F1=0.2326)
  Directional -> Accuracy: 0.4902, MCC: 0.0863, F1: 0.6176

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.60273 | val 0.97820
  Epoch 011 - train 0.57580 | val 1.12439
  Classification -> best τ=0.495 (val F1=0.2998)
  Directional -> Accuracy: 0.5507, MCC: 0.0722, F1: 0.6667

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.61370 | val 0.87993
  Epoch 012 - train 0.55938 | val 0.84899
  Classification -> best τ=0.655 (val F1=0.0757)
  Directional -> Accuracy: 0.4310, MCC: 0.1826, F1: 0.1538

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.61813 | val 0.99903
  Epoch 020 - train 0.53583 | val 1.44176
  Epoch 027 - train 0.39833 | val 1.44449
  Classification -> best τ=0.205 (val F1=0.2182)
  Directional -> Accuracy: 0.6000, MCC: 0.0000, F1: 0.7500

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.59733 | val 0.83788
  Epoch 011 - train 0.54477 | val 0.95543
  Classification -> best τ=0.275 (val F1=0.2843)
  Directional -> Accuracy: 0.5781, MCC: 0.0000, F1: 0.7327

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.51718 | val 1.81376
  Epoch 011 - train 0.50246 | val 1.77745
  Classification -> best τ=0.535 (val F1=0.2593)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.58209 | val 1.32890
  Epoch 012 - train 0.56312 | val 0.91285
  Classification -> best τ=0.670 (val F1=0.3237)
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.63602 | val 1.25316
  Epoch 013 - train 0.56913 | val 1.49290
  Classification -> best τ=0.585 (val F1=0.3780)
  Directional -> Accuracy: 0.5077, MCC: 0.1231, F1: 0.0588

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.65216 | val 0.65593
  Epoch 015 - train 0.62212 | val 0.69761
  Classification -> best τ=0.445 (val F1=0.4370)
  Directional -> Accuracy: 0.5965, MCC: 0.2225, F1: 0.5818

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.66650 | val 0.71635
  Epoch 015 - train 0.62974 | val 0.75457
  Classification -> best τ=0.555 (val F1=0.1985)
  Directional -> Accuracy: 0.5385, MCC: 0.1309, F1: 0.0625

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.56398 | val 0.93430
  Epoch 014 - train 0.44828 | val 1.15206
  Classification -> best τ=0.520 (val F1=0.4560)
  Directional -> Accuracy: 0.5091, MCC: 0.0199, F1: 0.5263

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.50096 | val 1.86619
  Epoch 011 - train 0.48636 | val 1.75448
  Classification -> best τ=0.795 (val F1=0.2935)
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.5938

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.60051 | val 0.77224
  Epoch 014 - train 0.53908 | val 0.79092
  Classification -> best τ=0.585 (val F1=0.1936)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.2581

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.56168 | val 1.61583
  Epoch 011 - train 0.50500 | val 1.62421
  Classification -> best τ=0.280 (val F1=0.3430)
  Directional -> Accuracy: 0.4464, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.51132 | val 0.72035
  Epoch 020 - train 0.37912 | val 0.73058
  Epoch 021 - train 0.30820 | val 0.74688
  Classification -> best τ=0.375 (val F1=0.2267)
  Directional -> Accuracy: 0.5750, MCC: 0.1770, F1: 0.7213

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.61380 | val 0.62700
  Epoch 020 - train 0.51765 | val 0.97943
  Classification -> best τ=0.530 (val F1=0.4673)
  Directional -> Accuracy: 0.4524, MCC: -0.1137, F1: 0.3429

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.58336 | val 1.07041
  Epoch 011 - train 0.59604 | val 1.16133
  Classification -> best τ=0.550 (val F1=0.2697)
  Directional -> Accuracy: 0.4762, MCC: -0.1062, F1: 0.5926

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.56537 | val 0.91334
  Epoch 013 - train 0.48333 | val 1.37203
  Classification -> best τ=0.340 (val F1=0.3502)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.58898 | val 0.75785
  Epoch 020 - train 0.55883 | val 0.74770
  Epoch 021 - train 0.49324 | val 0.81090
  Classification -> best τ=0.280 (val F1=0.2774)
  Directional -> Accuracy: 0.5556, MCC: 0.0000, F1: 0.7143

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.47526 | val 1.17827
  Epoch 011 - train 0.45942 | val 1.37520
  Classification -> best τ=0.655 (val F1=0.2603)
  Directional -> Accuracy: 0.5581, MCC: 0.2261, F1: 0.1739

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.60005 | val 1.56263
  Epoch 011 - train 0.58479 | val 2.04509
  Classification -> best τ=0.525 (val F1=0.1203)
  Directional -> Accuracy: 0.5758, MCC: 0.0000, F1: 0.7308

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.54119 | val 2.63249
  Epoch 012 - train 0.41673 | val 2.39733
  Classification -> best τ=0.780 (val F1=0.3260)
  Directional -> Accuracy: 0.5000, MCC: 0.1489, F1: 0.0870

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.54193 | val 1.21028
  Epoch 012 - train 0.50883 | val 1.00341
  Classification -> best τ=0.605 (val F1=0.2850)
  Directional -> Accuracy: 0.5179, MCC: -0.0625, F1: 0.0690

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.44702 | val 1.87857
  Epoch 011 - train 0.43992 | val 1.85451
  Classification -> best τ=0.465 (val F1=0.3679)
  Directional -> Accuracy: 0.6087, MCC: 0.0000, F1: 0.7568

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.49399 | val 0.73446
  Epoch 017 - train 0.48534 | val 0.89307
  Classification -> best τ=0.225 (val F1=0.3751)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.57672 | val 1.66495
  Epoch 011 - train 0.51457 | val 1.77974
  Classification -> best τ=0.140 (val F1=0.3053)
  Directional -> Accuracy: 0.4865, MCC: 0.0000, F1: 0.6545

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.67914 | val 1.83634
  Epoch 012 - train 0.57184 | val 1.35049
  Classification -> best τ=0.455 (val F1=0.4080)
  Directional -> Accuracy: 0.5778, MCC: 0.1778, F1: 0.6780

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.41036 | val 2.39447
  Epoch 011 - train 0.30157 | val 2.92174
  Classification -> best τ=0.685 (val F1=0.3612)
  Directional -> Accuracy: 0.5000, MCC: 0.0138, F1: 0.5116

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.54030 | val 1.03709
  Epoch 016 - train 0.40688 | val 1.10407
  Classification -> best τ=0.645 (val F1=0.5421)
  Directional -> Accuracy: 0.4583, MCC: 0.0795, F1: 0.5357

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.62708 | val 1.10835
  Epoch 011 - train 0.56454 | val 1.00553
  Classification -> best τ=0.700 (val F1=0.1784)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.50865 | val 2.54790
  Epoch 011 - train 0.43708 | val 3.31639
  Classification -> best τ=0.400 (val F1=0.3536)
  Directional -> Accuracy: 0.4643, MCC: -0.0662, F1: 0.5000

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.64851 | val 0.91604
  Epoch 012 - train 0.61359 | val 0.89890
  Classification -> best τ=0.620 (val F1=0.2908)
  Directional -> Accuracy: 0.5094, MCC: 0.0037, F1: 0.6667

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.55588 | val 1.67889
  Epoch 011 - train 0.48699 | val 1.81170
  Classification -> best τ=0.655 (val F1=0.0094)
  Directional -> Accuracy: 0.4727, MCC: -0.0153, F1: 0.1212

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.61420 | val 0.95213

[I 2026-02-22 13:39:21,354] Trial 199 finished with value: 0.28217705489302203 and parameters: {'feature_set': 'sector', 'model_type': 'BiGRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.4, 'batch_size': 16, 'learning_rate': 0.009463712626887853, 'weight_decay': 4.4635882134798566e-05, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 0.9639878080095485, 'early_stopping_min_delta': 0.001155813759810968}. Best is trial 159 with value: 0.297766251520741.

  Epoch 011 - train 0.58462 | val 1.02270
  Classification -> best τ=0.525 (val F1=0.1708)
  Directional -> Accuracy: 0.5167, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.28217705489302203
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.63273 | val 1.32458
  Epoch 012 - train 0.62840 | val 1.29415
  Classification -> best τ=0.875 (val F1=0.2510)
  Directional -> Accuracy: 0.5526, MCC: 0.0174, F1: 0.0556

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.57018 | val 0.87232
  Epoch 012 - train 0.52071 | val 0.84177
  Classification -> best τ=0.675 (val F1=0.2523)
  Directional -> Accuracy: 0.4667, MCC: 0.0240, F1: 0.3333

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.60528 | val 1.17997
  Epoch 011 - train 0.56031 | val 1.24916
  Classification -> best τ=0.655 (val F1=0.3114)
  Directional -> Accuracy: 0.4565, MCC: -0.0996, F1: 0.0741

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.63337 | val 2.00730
  Epoch 017 - train 0.57728 | val 1.87172
  Classification -> best τ=0.525 (val F1=0.1079)
  Directional -> Accuracy: 0.5405, MCC: 0.2058, F1: 0.3200

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.54371 | val 3.29260
  Epoch 011 - train 0.48134 | val 2.77614
  Classification -> best τ=0.525 (val F1=0.4745)
  Directional -> Accuracy: 0.6000, MCC: 0.2202, F1: 0.5455

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.49071 | val 1.15934
  Epoch 018 - train 0.41087 | val 1.33955
  Classification -> best τ=0.595 (val F1=0.4070)
  Directional -> Accuracy: 0.5217, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.60701 | val 1.16963
  Epoch 011 - train 0.58516 | val 1.17917
  Classification -> best τ=0.405 (val F1=0.3331)
  Directional -> Accuracy: 0.5000, MCC: 0.0719, F1: 0.5278

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.63556 | val 0.58570
  Epoch 011 - train 0.41351 | val 0.62390
  Classification -> best τ=0.315 (val F1=0.2168)
  Directional -> Accuracy: 0.5238, MCC: -0.1936, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.61615 | val 1.76147
  Epoch 011 - train 0.60012 | val 1.53123
  Classification -> best τ=0.690 (val F1=0.1975)
  Directional -> Accuracy: 0.6042, MCC: 0.1746, F1: 0.2963

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.59002 | val 1.02424
  Epoch 011 - train 0.55175 | val 1.05178
  Classification -> best τ=0.505 (val F1=0.1607)
  Directional -> Accuracy: 0.4638, MCC: -0.0573, F1: 0.4478

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.58486 | val 1.02488
  Epoch 019 - train 0.47493 | val 2.40688
  Classification -> best τ=0.425 (val F1=0.2661)
  Directional -> Accuracy: 0.6122, MCC: 0.2010, F1: 0.4571

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.53622 | val 1.76175
  Epoch 012 - train 0.57924 | val 1.37240
  Classification -> best τ=0.485 (val F1=0.1706)
  Directional -> Accuracy: 0.5088, MCC: 0.0000, F1: 0.6744

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.47178 | val 0.87788
  Epoch 016 - train 0.40765 | val 0.80058
  Classification -> best τ=0.650 (val F1=0.2473)
  Directional -> Accuracy: 0.5238, MCC: -0.1419, F1: 0.0000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.62321 | val 0.69054
  Epoch 011 - train 0.62782 | val 0.66941
  Classification -> best τ=0.325 (val F1=0.2845)
  Directional -> Accuracy: 0.5333, MCC: 0.1336, F1: 0.1765

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.60816 | val 0.73523
  Epoch 012 - train 0.52337 | val 0.76914
  Classification -> best τ=0.455 (val F1=0.3516)
  Directional -> Accuracy: 0.4118, MCC: -0.1515, F1: 0.4828

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.58500 | val 1.96582
  Epoch 011 - train 0.52176 | val 2.16784
  Classification -> best τ=0.500 (val F1=0.3207)
  Directional -> Accuracy: 0.5507, MCC: 0.0764, F1: 0.6931

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.62234 | val 0.70740
  Epoch 012 - train 0.56881 | val 0.72409
  Classification -> best τ=0.470 (val F1=0.3095)
  Directional -> Accuracy: 0.4310, MCC: 0.1135, F1: 0.1951

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.60557 | val 1.19969
  Epoch 012 - train 0.56705 | val 1.32685
  Classification -> best τ=0.500 (val F1=0.1909)
  Directional -> Accuracy: 0.4000, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.60458 | val 1.44589
  Epoch 011 - train 0.53352 | val 1.63784
  Classification -> best τ=0.410 (val F1=0.3561)
  Directional -> Accuracy: 0.5781, MCC: 0.0408, F1: 0.7216

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.51355 | val 1.46709
  Epoch 011 - train 0.50055 | val 1.36137
  Classification -> best τ=0.420 (val F1=0.2920)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.58472 | val 1.54340
  Epoch 011 - train 0.50940 | val 2.02545
  Classification -> best τ=0.600 (val F1=0.2861)
  Directional -> Accuracy: 0.3617, MCC: -0.1871, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.61299 | val 1.02082
  Epoch 011 - train 0.60157 | val 1.08456
  Classification -> best τ=0.360 (val F1=0.2160)
  Directional -> Accuracy: 0.5077, MCC: 0.0000, F1: 0.6735

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.64101 | val 1.03786
  Epoch 020 - train 0.52412 | val 0.91180
  Epoch 021 - train 0.50785 | val 1.04678
  Classification -> best τ=0.380 (val F1=0.4748)
  Directional -> Accuracy: 0.6140, MCC: 0.2162, F1: 0.6562

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.60456 | val 0.67937
  Epoch 020 - train 0.50182 | val 1.06394
  Classification -> best τ=0.395 (val F1=0.3473)
  Directional -> Accuracy: 0.4923, MCC: -0.0133, F1: 0.4923

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.54559 | val 1.33947
  Epoch 012 - train 0.50963 | val 1.31201
  Classification -> best τ=0.395 (val F1=0.4629)
  Directional -> Accuracy: 0.5455, MCC: 0.1077, F1: 0.5283

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.49719 | val 1.87047
  Epoch 011 - train 0.50170 | val 1.74007
  Classification -> best τ=0.615 (val F1=0.0105)
  Directional -> Accuracy: 0.3778, MCC: -0.2440, F1: 0.3333

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.63593 | val 0.71128
  Epoch 012 - train 0.57861 | val 0.72844
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.7273

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.54520 | val 1.16952
  Epoch 011 - train 0.47407 | val 1.44870
  Classification -> best τ=0.385 (val F1=0.3214)
  Directional -> Accuracy: 0.4643, MCC: 0.1211, F1: 0.0625

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.50214 | val 1.35765
  Epoch 011 - train 0.51887 | val 1.30760
  Classification -> best τ=0.690 (val F1=0.0707)
  Directional -> Accuracy: 0.6000, MCC: 0.1759, F1: 0.7037

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.55138 | val 1.49042
  Epoch 011 - train 0.51221 | val 1.39981
  Classification -> best τ=0.560 (val F1=0.3501)
  Directional -> Accuracy: 0.5000, MCC: -0.0332, F1: 0.2759

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.56259 | val 2.41793
  Epoch 012 - train 0.54545 | val 1.53829
  Classification -> best τ=0.400 (val F1=0.2042)
  Directional -> Accuracy: 0.4048, MCC: -0.2572, F1: 0.5283

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.50100 | val 1.23949
  Epoch 013 - train 0.40993 | val 1.01451
  Classification -> best τ=0.485 (val F1=0.3323)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.62721 | val 0.85569
  Epoch 012 - train 0.56347 | val 0.76482
  Classification -> best τ=0.520 (val F1=0.3694)
  Directional -> Accuracy: 0.4861, MCC: 0.0282, F1: 0.3729

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.57797 | val 0.89953
  Epoch 012 - train 0.50229 | val 1.20637
  Classification -> best τ=0.260 (val F1=0.1874)
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.64719 | val 1.12694
  Epoch 017 - train 0.51579 | val 1.50103
  Classification -> best τ=0.715 (val F1=0.2983)
  Directional -> Accuracy: 0.4545, MCC: 0.1517, F1: 0.1000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.49966 | val 1.73254
  Epoch 011 - train 0.50281 | val 1.72407
  Classification -> best τ=0.515 (val F1=0.2618)
  Directional -> Accuracy: 0.6190, MCC: 0.3091, F1: 0.5000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.54452 | val 1.31798
  Epoch 012 - train 0.49882 | val 1.18026
  Classification -> best τ=0.360 (val F1=0.2841)
  Directional -> Accuracy: 0.5357, MCC: 0.0961, F1: 0.5806

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.50806 | val 1.53989
  Epoch 016 - train 0.41535 | val 1.02661
  Classification -> best τ=0.355 (val F1=0.3107)
  Directional -> Accuracy: 0.5217, MCC: 0.0156, F1: 0.5926

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.59519 | val 1.50861
  Epoch 011 - train 0.56789 | val 1.54144
  Classification -> best τ=0.585 (val F1=0.4011)
  Directional -> Accuracy: 0.4583, MCC: 0.0592, F1: 0.5000

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.62593 | val 1.63651
  Epoch 011 - train 0.51275 | val 1.94097
  Classification -> best τ=0.615 (val F1=0.2327)
  Directional -> Accuracy: 0.5000, MCC: -0.1139, F1: 0.0000

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.65600 | val 0.73642
  Epoch 017 - train 0.44616 | val 1.40234
  Classification -> best τ=0.450 (val F1=0.2874)
  Directional -> Accuracy: 0.4667, MCC: -0.0709, F1: 0.2000

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.42614 | val 3.01966
  Epoch 011 - train 0.27511 | val 2.81292
  Classification -> best τ=0.500 (val F1=0.2408)
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.7273

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.57902 | val 0.66341
  Epoch 013 - train 0.47657 | val 0.63079
  Classification -> best τ=0.690 (val F1=0.3299)
  Directional -> Accuracy: 0.4792, MCC: 0.1152, F1: 0.5455

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.63023 | val 1.38855
  Epoch 016 - train 0.56588 | val 0.77657
  Classification -> best τ=0.675 (val F1=0.2036)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.51133 | val 2.67917
  Epoch 011 - train 0.45969 | val 2.59203
  Classification -> best τ=0.475 (val F1=0.3432)
  Directional -> Accuracy: 0.4821, MCC: -0.0444, F1: 0.4082

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.58662 | val 0.77821
  Epoch 020 - train 0.51559 | val 0.69887
  Epoch 029 - train 0.41172 | val 1.72032
  Classification -> best τ=0.725 (val F1=0.2728)
  Directional -> Accuracy: 0.5849, MCC: 0.1691, F1: 0.6207

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.59241 | val 3.83530
  Epoch 011 - train 0.48777 | val 3.07512
  Classification -> best τ=0.730 (val F1=0.1154)
  Directional -> Accuracy: 0.5273, MCC: 0.0000, F1: 0.6905

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.59349 | val 1.07735

[I 2026-02-22 13:42:23,442] Trial 200 finished with value: 0.2703915178185537 and parameters: {'feature_set': 'sector', 'model_type': 'BiGRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.4, 'batch_size': 16, 'learning_rate': 0.009566982585823117, 'weight_decay': 3.883716987560377e-05, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 0.9489906132382961, 'early_stopping_min_delta': 0.0010799864998286377}. Best is trial 159 with value: 0.297766251520741.

  Epoch 011 - train 0.57256 | val 1.30710
  Classification -> best τ=0.470 (val F1=0.2623)
  Directional -> Accuracy: 0.5167, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2703915178185537
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.64881 | val 0.86861
  Epoch 011 - train 0.64064 | val 0.73337
  Classification -> best τ=0.580 (val F1=0.2919)
  Directional -> Accuracy: 0.5526, MCC: 0.0000, F1: 0.0000

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.55570 | val 0.84340
  Epoch 011 - train 0.56357 | val 0.88474
  Classification -> best τ=0.555 (val F1=0.1764)
  Directional -> Accuracy: 0.5778, MCC: 0.1540, F1: 0.6122

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.59167 | val 1.13342
  Epoch 012 - train 0.54906 | val 1.70979
  Classification -> best τ=0.775 (val F1=0.2941)
  Directional -> Accuracy: 0.4565, MCC: -0.0996, F1: 0.0741

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.56227 | val 1.13285
  Epoch 011 - train 0.57566 | val 1.18982
  Classification -> best τ=0.570 (val F1=0.2332)
  Directional -> Accuracy: 0.5135, MCC: 0.1463, F1: 0.2500

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.56687 | val 0.76212
  Epoch 014 - train 0.46640 | val 0.78140
  Classification -> best τ=0.455 (val F1=0.5169)
  Directional -> Accuracy: 0.5800, MCC: 0.1825, F1: 0.5116

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.55896 | val 0.67888
  Epoch 020 - train 0.36390 | val 1.16197
  Classification -> best τ=0.485 (val F1=0.4047)
  Directional -> Accuracy: 0.5217, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.57623 | val 0.99149
  Epoch 011 - train 0.55350 | val 1.19078
  Classification -> best τ=0.525 (val F1=0.2176)
  Directional -> Accuracy: 0.5588, MCC: 0.0903, F1: 0.4643

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.49432 | val 0.45058
  Epoch 020 - train 0.35447 | val 1.49012
  Classification -> best τ=0.245 (val F1=0.4453)
  Directional -> Accuracy: 0.5714, MCC: 0.1840, F1: 0.5909

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.58196 | val 1.37200
  Epoch 011 - train 0.51021 | val 1.36100
  Classification -> best τ=0.625 (val F1=0.2443)
  Directional -> Accuracy: 0.7083, MCC: 0.4371, F1: 0.5333

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.56596 | val 0.71261
  Epoch 011 - train 0.57511 | val 0.73828
  Classification -> best τ=0.455 (val F1=0.2060)
  Directional -> Accuracy: 0.5217, MCC: 0.0607, F1: 0.5075

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.62309 | val 0.74805
  Epoch 013 - train 0.54695 | val 1.00141
  Classification -> best τ=0.445 (val F1=0.3590)
  Directional -> Accuracy: 0.6122, MCC: 0.2379, F1: 0.2963

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.60959 | val 0.86615
  Epoch 011 - train 0.61204 | val 0.96371
  Classification -> best τ=0.405 (val F1=0.2667)
  Directional -> Accuracy: 0.5614, MCC: 0.1669, F1: 0.6835

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.45018 | val 0.93856
  Epoch 020 - train 0.38474 | val 1.36213
  Epoch 022 - train 0.34624 | val 1.03462
  Classification -> best τ=0.545 (val F1=0.1733)
  Directional -> Accuracy: 0.5238, MCC: -0.0387, F1: 0.1667

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.59047 | val 0.99567
  Epoch 013 - train 0.55073 | val 0.81903
  Classification -> best τ=0.345 (val F1=0.3455)
  Directional -> Accuracy: 0.5333, MCC: 0.0754, F1: 0.6216

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.62857 | val 0.73525
  Epoch 012 - train 0.55887 | val 0.75107
  Classification -> best τ=0.535 (val F1=0.3139)
  Directional -> Accuracy: 0.4510, MCC: -0.0666, F1: 0.5172

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.58212 | val 1.11330
  Epoch 011 - train 0.53915 | val 1.25002
  Classification -> best τ=0.880 (val F1=0.1385)
  Directional -> Accuracy: 0.4638, MCC: 0.0000, F1: 0.0000

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.55805 | val 1.53750
  Epoch 017 - train 0.46730 | val 1.37980
  Classification -> best τ=0.610 (val F1=0.1898)
  Directional -> Accuracy: 0.3793, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.54881 | val 1.01183
  Epoch 011 - train 0.52691 | val 1.05696
  Classification -> best τ=0.375 (val F1=0.1657)
  Directional -> Accuracy: 0.4933, MCC: 0.1846, F1: 0.3214

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.61601 | val 1.19198
  Epoch 012 - train 0.52149 | val 1.21198
  Classification -> best τ=0.430 (val F1=0.3346)
  Directional -> Accuracy: 0.4844, MCC: -0.0624, F1: 0.5600

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.56886 | val 1.39387
  Epoch 011 - train 0.48156 | val 2.30248
  Classification -> best τ=0.530 (val F1=0.2565)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.59334 | val 1.01134
  Epoch 012 - train 0.48615 | val 1.77677
  Classification -> best τ=0.525 (val F1=0.1723)
  Directional -> Accuracy: 0.6170, MCC: 0.0000, F1: 0.7632

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.57984 | val 1.33514
  Epoch 012 - train 0.53227 | val 1.32000
  Classification -> best τ=0.665 (val F1=0.2757)
  Directional -> Accuracy: 0.4923, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.64605 | val 0.60706
  Epoch 020 - train 0.46473 | val 1.02483
  Classification -> best τ=0.505 (val F1=0.4137)
  Directional -> Accuracy: 0.5439, MCC: 0.1198, F1: 0.5185

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.64575 | val 0.84140
  Epoch 012 - train 0.58850 | val 0.97345
  Classification -> best τ=0.475 (val F1=0.2366)
  Directional -> Accuracy: 0.4769, MCC: -0.1024, F1: 0.1905

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.53090 | val 0.75275
  Epoch 011 - train 0.50649 | val 0.89797
  Classification -> best τ=0.485 (val F1=0.5707)
  Directional -> Accuracy: 0.5818, MCC: 0.1913, F1: 0.5490

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.43548 | val 6.47431
  Epoch 011 - train 0.39688 | val 7.53735
  Classification -> best τ=0.760 (val F1=0.4328)
  Directional -> Accuracy: 0.5111, MCC: 0.2670, F1: 0.6333

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.61110 | val 0.75108
  Epoch 014 - train 0.54654 | val 0.77923
  Classification -> best τ=0.500 (val F1=0.2222)
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.7273

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.61526 | val 1.66523
  Epoch 012 - train 0.46929 | val 2.32384
  Classification -> best τ=0.680 (val F1=0.3322)
  Directional -> Accuracy: 0.4464, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.53907 | val 1.19677
  Epoch 011 - train 0.47507 | val 0.83667
  Classification -> best τ=0.560 (val F1=0.1943)
  Directional -> Accuracy: 0.5500, MCC: 0.0503, F1: 0.6667

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.59413 | val 0.82537
  Epoch 016 - train 0.53781 | val 0.70443
  Classification -> best τ=0.465 (val F1=0.4110)
  Directional -> Accuracy: 0.4762, MCC: -0.0500, F1: 0.4500

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.55764 | val 1.57388
  Epoch 011 - train 0.58934 | val 1.48208
  Classification -> best τ=0.730 (val F1=0.1286)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.54757 | val 0.87208
  Epoch 011 - train 0.47410 | val 0.89268
  Classification -> best τ=0.425 (val F1=0.3069)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.61796 | val 0.68221
  Epoch 020 - train 0.48004 | val 0.82492
  Classification -> best τ=0.795 (val F1=0.2267)
  Directional -> Accuracy: 0.4444, MCC: 0.0000, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.54331 | val 1.47874
  Epoch 011 - train 0.48874 | val 1.60398
  Classification -> best τ=0.590 (val F1=0.0364)
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.59338 | val 0.96228
  Epoch 011 - train 0.57593 | val 1.42166
  Classification -> best τ=0.460 (val F1=0.0244)
  Directional -> Accuracy: 0.5758, MCC: 0.0000, F1: 0.7308

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.44352 | val 2.94566
  Epoch 011 - train 0.49082 | val 2.86620
  Classification -> best τ=0.490 (val F1=0.2292)
  Directional -> Accuracy: 0.7143, MCC: 0.4404, F1: 0.7000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.61387 | val 0.79929
  Epoch 020 - train 0.49201 | val 0.77469
  Epoch 023 - train 0.32678 | val 1.20103
  Classification -> best τ=0.440 (val F1=0.2114)
  Directional -> Accuracy: 0.5536, MCC: 0.0805, F1: 0.3243

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.51320 | val 1.20172
  Epoch 011 - train 0.48031 | val 1.20294
  Classification -> best τ=0.445 (val F1=0.3367)
  Directional -> Accuracy: 0.6087, MCC: 0.0000, F1: 0.7568

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.57115 | val 0.77396
  Epoch 011 - train 0.55223 | val 0.74277
  Classification -> best τ=0.595 (val F1=0.5075)
  Directional -> Accuracy: 0.5208, MCC: 0.0436, F1: 0.4390

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.56120 | val 1.94101
  Epoch 011 - train 0.52639 | val 2.23496
  Classification -> best τ=0.650 (val F1=0.2222)
  Directional -> Accuracy: 0.5135, MCC: 0.0045, F1: 0.0526

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.58709 | val 0.68803
  Epoch 013 - train 0.61771 | val 0.80310
  Classification -> best τ=0.555 (val F1=0.4632)
  Directional -> Accuracy: 0.5333, MCC: 0.0667, F1: 0.6441

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.36822 | val 2.25070
  Epoch 012 - train 0.33070 | val 2.76887
  Classification -> best τ=0.660 (val F1=0.3612)
  Directional -> Accuracy: 0.3571, MCC: -0.2759, F1: 0.0690

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.56381 | val 1.47485
  Epoch 011 - train 0.49934 | val 1.47742
  Classification -> best τ=0.495 (val F1=0.4216)
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.5455

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.65902 | val 2.63756
  Epoch 011 - train 0.61598 | val 2.38643
  Classification -> best τ=0.340 (val F1=0.1605)
  Directional -> Accuracy: 0.5455, MCC: 0.0000, F1: 0.7059

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.51857 | val 2.04470
  Epoch 011 - train 0.50149 | val 2.25960
  Classification -> best τ=0.605 (val F1=0.3988)
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.6506

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.63270 | val 0.86998
  Epoch 012 - train 0.59245 | val 0.73742
  Classification -> best τ=0.795 (val F1=0.2064)
  Directional -> Accuracy: 0.6038, MCC: 0.2103, F1: 0.5882

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.61468 | val 1.13430
  Epoch 012 - train 0.46933 | val 1.73064
  Classification -> best τ=0.725 (val F1=0.1655)
  Directional -> Accuracy: 0.5273, MCC: 0.0000, F1: 0.6905

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.61219 | val 0.72710

[I 2026-02-22 13:44:58,658] Trial 201 finished with value: 0.2831700600620542 and parameters: {'feature_set': 'sector', 'model_type': 'BiGRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.4, 'batch_size': 16, 'learning_rate': 0.008605569447168162, 'weight_decay': 3.791223859583912e-05, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 0.9535203871691237, 'early_stopping_min_delta': 0.0014632644931900619}. Best is trial 159 with value: 0.297766251520741.

  Epoch 011 - train 0.59221 | val 0.79221
  Classification -> best τ=0.495 (val F1=0.3496)
  Directional -> Accuracy: 0.5833, MCC: 0.1761, F1: 0.4186

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2831700600620542
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.64374 | val 1.05663
  Epoch 013 - train 0.61151 | val 1.37570
  Classification -> best τ=0.735 (val F1=0.2510)
  Directional -> Accuracy: 0.5395, MCC: -0.1039, F1: 0.0000

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.62587 | val 0.84944
  Epoch 012 - train 0.49928 | val 1.26678
  Classification -> best τ=0.610 (val F1=0.1764)
  Directional -> Accuracy: 0.6667, MCC: 0.3219, F1: 0.7059

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.60366 | val 1.37614
  Epoch 011 - train 0.55756 | val 1.57289
  Classification -> best τ=0.650 (val F1=0.3114)
  Directional -> Accuracy: 0.5217, MCC: 0.0948, F1: 0.3125

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.61112 | val 0.80165
  Epoch 015 - train 0.51914 | val 0.76695
  Classification -> best τ=0.540 (val F1=0.2739)
  Directional -> Accuracy: 0.5000, MCC: 0.1895, F1: 0.1395

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.51032 | val 1.84015
  Epoch 011 - train 0.52415 | val 1.91860
  Classification -> best τ=0.700 (val F1=0.4745)
  Directional -> Accuracy: 0.6000, MCC: 0.2300, F1: 0.5238

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.61369 | val 0.68314
  Epoch 020 - train 0.31845 | val 0.75232
  Epoch 028 - train 0.15211 | val 1.06995
  Classification -> best τ=0.710 (val F1=0.4390)
  Directional -> Accuracy: 0.5217, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.59964 | val 1.11898
  Epoch 016 - train 0.57604 | val 1.27961
  Classification -> best τ=0.240 (val F1=0.3280)
  Directional -> Accuracy: 0.5147, MCC: -0.0200, F1: 0.3774

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.54407 | val 0.80991
  Epoch 016 - train 0.27374 | val 1.52549
  Classification -> best τ=0.170 (val F1=0.2810)
  Directional -> Accuracy: 0.4286, MCC: -0.0323, F1: 0.5862

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.57453 | val 1.29723
  Epoch 011 - train 0.52072 | val 1.37945
  Classification -> best τ=0.430 (val F1=0.1715)
  Directional -> Accuracy: 0.6042, MCC: 0.1843, F1: 0.5128

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.57118 | val 0.86585
  Epoch 011 - train 0.52206 | val 0.90256
  Classification -> best τ=0.405 (val F1=0.2260)
  Directional -> Accuracy: 0.5362, MCC: 0.0953, F1: 0.5294

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.61348 | val 1.01361
  Epoch 020 - train 0.54770 | val 0.85504
  Epoch 022 - train 0.47946 | val 0.72194
  Classification -> best τ=0.560 (val F1=0.3231)
  Directional -> Accuracy: 0.6122, MCC: 0.2178, F1: 0.3448

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.60116 | val 1.15464
  Epoch 011 - train 0.56404 | val 1.44585
  Classification -> best τ=0.450 (val F1=0.1400)
  Directional -> Accuracy: 0.5088, MCC: 0.0000, F1: 0.6744

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.56317 | val 0.81551
  Epoch 016 - train 0.43521 | val 1.39362
  Classification -> best τ=0.830 (val F1=0.1225)
  Directional -> Accuracy: 0.3810, MCC: -0.2311, F1: 0.3810

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.62212 | val 0.77156
  Epoch 012 - train 0.55808 | val 0.78469
  Classification -> best τ=0.425 (val F1=0.3916)
  Directional -> Accuracy: 0.4833, MCC: -0.0467, F1: 0.2051

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.59702 | val 0.72122
  Epoch 012 - train 0.49053 | val 0.77154
  Classification -> best τ=0.530 (val F1=0.2571)
  Directional -> Accuracy: 0.5490, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.61071 | val 1.31465
  Epoch 011 - train 0.57304 | val 1.57366
  Classification -> best τ=0.610 (val F1=0.2604)
  Directional -> Accuracy: 0.5362, MCC: 0.0263, F1: 0.6735

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.59051 | val 1.07241
  Epoch 013 - train 0.54015 | val 1.07887
  Classification -> best τ=0.385 (val F1=0.3916)
  Directional -> Accuracy: 0.3793, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.61161 | val 1.04925
  Epoch 014 - train 0.51876 | val 0.86405
  Classification -> best τ=0.425 (val F1=0.1909)
  Directional -> Accuracy: 0.3600, MCC: -0.2080, F1: 0.2258

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.60976 | val 1.45531
  Epoch 012 - train 0.53669 | val 1.40418
  Classification -> best τ=0.275 (val F1=0.2843)
  Directional -> Accuracy: 0.5938, MCC: 0.1140, F1: 0.7111

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.54826 | val 1.12909
  Epoch 011 - train 0.50609 | val 1.07120
  Classification -> best τ=0.470 (val F1=0.2597)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.53512 | val 1.01694
  Epoch 014 - train 0.47505 | val 1.77763
  Classification -> best τ=0.500 (val F1=0.2514)
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.61378 | val 1.07577
  Epoch 012 - train 0.56170 | val 1.36302
  Classification -> best τ=0.305 (val F1=0.3000)
  Directional -> Accuracy: 0.4923, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.65207 | val 0.70777
  Epoch 013 - train 0.54400 | val 0.86784
  Classification -> best τ=0.465 (val F1=0.3382)
  Directional -> Accuracy: 0.5965, MCC: 0.1771, F1: 0.6462

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.63253 | val 0.73859
  Epoch 020 - train 0.52626 | val 0.75084
  Epoch 021 - train 0.48635 | val 0.75248
  Classification -> best τ=0.305 (val F1=0.1122)
  Directional -> Accuracy: 0.4462, MCC: -0.1111, F1: 0.5909

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.50958 | val 1.16639
  Epoch 011 - train 0.52086 | val 1.35695
  Classification -> best τ=0.450 (val F1=0.4399)
  Directional -> Accuracy: 0.5636, MCC: 0.2170, F1: 0.4286

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.42521 | val 4.21036
  Epoch 011 - train 0.43839 | val 4.03254
  Classification -> best τ=0.800 (val F1=0.0105)
  Directional -> Accuracy: 0.3778, MCC: -0.2030, F1: 0.4400

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.61044 | val 0.75061
  Epoch 018 - train 0.46045 | val 0.70095
  Classification -> best τ=0.565 (val F1=0.2582)
  Directional -> Accuracy: 0.6429, MCC: 0.2501, F1: 0.7273

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.56608 | val 1.38459
  Epoch 011 - train 0.50405 | val 1.93317
  Classification -> best τ=0.240 (val F1=0.2614)
  Directional -> Accuracy: 0.5536, MCC: 0.2064, F1: 0.4186

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.54043 | val 0.79842
  Epoch 011 - train 0.45995 | val 0.82597
  Classification -> best τ=0.605 (val F1=0.3296)
  Directional -> Accuracy: 0.5750, MCC: 0.1234, F1: 0.6531

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.64618 | val 0.92905
  Epoch 017 - train 0.50170 | val 2.25323
  Classification -> best τ=0.595 (val F1=0.4110)
  Directional -> Accuracy: 0.5000, MCC: -0.0046, F1: 0.4615

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.57800 | val 0.91461
  Epoch 013 - train 0.52733 | val 1.18613
  Classification -> best τ=0.645 (val F1=0.1846)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.50272 | val 1.13449
  Epoch 013 - train 0.45553 | val 1.22519
  Classification -> best τ=0.375 (val F1=0.3802)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.59674 | val 0.70616
  Epoch 012 - train 0.53411 | val 0.81152
  Classification -> best τ=0.480 (val F1=0.4063)
  Directional -> Accuracy: 0.6111, MCC: 0.2177, F1: 0.6410

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.50156 | val 1.17066
  Epoch 011 - train 0.46873 | val 1.28823
  Classification -> best τ=0.365 (val F1=0.2717)
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.57470 | val 1.14750
  Epoch 011 - train 0.59363 | val 1.36937
  Classification -> best τ=0.540 (val F1=0.2941)
  Directional -> Accuracy: 0.5909, MCC: 0.1097, F1: 0.7097

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.51648 | val 1.65533
  Epoch 013 - train 0.43912 | val 2.35020
  Classification -> best τ=0.460 (val F1=0.3218)
  Directional -> Accuracy: 0.7143, MCC: 0.4266, F1: 0.7391

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.51804 | val 0.76016
  Epoch 020 - train 0.36396 | val 1.86622
  Classification -> best τ=0.605 (val F1=0.2622)
  Directional -> Accuracy: 0.6071, MCC: 0.2026, F1: 0.5000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.47530 | val 1.49818
  Epoch 011 - train 0.40336 | val 2.48023
  Classification -> best τ=0.160 (val F1=0.1195)
  Directional -> Accuracy: 0.6087, MCC: 0.0000, F1: 0.7568

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.53837 | val 0.67619
  Epoch 014 - train 0.48680 | val 0.69790
  Classification -> best τ=0.435 (val F1=0.4011)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.54843 | val 1.68932
  Epoch 011 - train 0.53690 | val 1.79569
  Classification -> best τ=0.490 (val F1=0.4030)
  Directional -> Accuracy: 0.4865, MCC: -0.0615, F1: 0.2083

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.60555 | val 1.38332
  Epoch 012 - train 0.53006 | val 0.81961
  Classification -> best τ=0.555 (val F1=0.3780)
  Directional -> Accuracy: 0.5111, MCC: 0.0000, F1: 0.6765

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.34149 | val 1.96259
  Epoch 011 - train 0.34357 | val 2.32942
  Classification -> best τ=0.650 (val F1=0.4971)
  Directional -> Accuracy: 0.5714, MCC: 0.0468, F1: 0.7097

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.53424 | val 0.54618
  Epoch 020 - train 0.33181 | val 1.10098
  Classification -> best τ=0.595 (val F1=0.5514)
  Directional -> Accuracy: 0.5833, MCC: 0.3974, F1: 0.6429

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.67125 | val 0.91759
  Epoch 012 - train 0.61186 | val 1.02311
  Classification -> best τ=0.630 (val F1=0.2036)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.53684 | val 1.52872
  Epoch 011 - train 0.51035 | val 1.56339
  Classification -> best τ=0.525 (val F1=0.4367)
  Directional -> Accuracy: 0.5179, MCC: 0.1289, F1: 0.6582

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.64207 | val 0.74921
  Epoch 015 - train 0.56653 | val 0.90038
  Classification -> best τ=0.540 (val F1=0.2921)
  Directional -> Accuracy: 0.5849, MCC: 0.1825, F1: 0.6667

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.57270 | val 2.65228
  Epoch 011 - train 0.52852 | val 2.70845
  Classification -> best τ=0.860 (val F1=0.0322)
  Directional -> Accuracy: 0.4727, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.65526 | val 1.68343

[I 2026-02-22 13:47:40,167] Trial 202 finished with value: 0.2912683927761212 and parameters: {'feature_set': 'sector', 'model_type': 'BiGRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.4, 'batch_size': 16, 'learning_rate': 0.00986857280325721, 'weight_decay': 3.978577836571723e-05, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 0.9728136140262031, 'early_stopping_min_delta': 0.0014480681019447123}. Best is trial 159 with value: 0.297766251520741.

  Epoch 011 - train 0.62144 | val 1.76089
  Classification -> best τ=0.420 (val F1=0.2789)
  Directional -> Accuracy: 0.5333, MCC: 0.0580, F1: 0.3913

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2912683927761212
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.66112 | val 0.65981
  Epoch 020 - train 0.51862 | val 0.91213
  Classification -> best τ=0.715 (val F1=0.2919)
  Directional -> Accuracy: 0.5526, MCC: 0.0000, F1: 0.0000

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.59755 | val 0.81124
  Epoch 014 - train 0.42598 | val 1.25860
  Classification -> best τ=0.700 (val F1=0.2073)
  Directional -> Accuracy: 0.5333, MCC: 0.0782, F1: 0.5532

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.60868 | val 1.15540
  Epoch 011 - train 0.53411 | val 1.17485
  Classification -> best τ=0.445 (val F1=0.2700)
  Directional -> Accuracy: 0.5652, MCC: 0.1234, F1: 0.6429

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.60875 | val 0.69546
  Epoch 011 - train 0.55718 | val 0.74037
  Classification -> best τ=0.595 (val F1=0.2208)
  Directional -> Accuracy: 0.5541, MCC: 0.0931, F1: 0.6118

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.49469 | val 1.46599
  Epoch 011 - train 0.52712 | val 1.82246
  Classification -> best τ=0.600 (val F1=0.4291)
  Directional -> Accuracy: 0.6200, MCC: 0.2670, F1: 0.5581

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.53412 | val 0.85273
  Epoch 020 - train 0.37426 | val 0.66284
  Epoch 028 - train 0.28737 | val 1.84384
  Classification -> best τ=0.585 (val F1=0.5858)
  Directional -> Accuracy: 0.5217, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.62707 | val 1.31150
  Epoch 014 - train 0.55604 | val 0.91801
  Classification -> best τ=0.510 (val F1=0.3966)
  Directional -> Accuracy: 0.5294, MCC: 0.0790, F1: 0.5000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.49370 | val 0.55570
  Epoch 016 - train 0.43445 | val 0.65399
  Classification -> best τ=0.410 (val F1=0.3689)
  Directional -> Accuracy: 0.5238, MCC: 0.0694, F1: 0.5238

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.55443 | val 2.32494
  Epoch 013 - train 0.48259 | val 1.95303
  Classification -> best τ=0.370 (val F1=0.3385)
  Directional -> Accuracy: 0.3958, MCC: -0.1690, F1: 0.5246

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.57366 | val 0.72023
  Epoch 011 - train 0.54275 | val 0.83119
  Classification -> best τ=0.465 (val F1=0.2620)
  Directional -> Accuracy: 0.4928, MCC: 0.1099, F1: 0.5882

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.63518 | val 0.78297
  Epoch 015 - train 0.55048 | val 1.02755
  Classification -> best τ=0.560 (val F1=0.1653)
  Directional -> Accuracy: 0.5306, MCC: 0.0474, F1: 0.4651

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.59347 | val 1.44382
  Epoch 012 - train 0.56291 | val 1.10191
  Classification -> best τ=0.660 (val F1=0.1963)
  Directional -> Accuracy: 0.5614, MCC: 0.1248, F1: 0.5455

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.55222 | val 1.65899
  Epoch 011 - train 0.41299 | val 2.25431
  Classification -> best τ=0.430 (val F1=0.0548)
  Directional -> Accuracy: 0.5000, MCC: 0.0976, F1: 0.6182

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.60298 | val 0.83836
  Epoch 012 - train 0.57313 | val 0.77022
  Classification -> best τ=0.420 (val F1=0.4109)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.60333 | val 0.76087
  Epoch 012 - train 0.54772 | val 0.76608
  Classification -> best τ=0.495 (val F1=0.2571)
  Directional -> Accuracy: 0.6078, MCC: 0.2025, F1: 0.5455

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.58548 | val 1.56494
  Epoch 011 - train 0.54847 | val 2.04885
  Classification -> best τ=0.505 (val F1=0.0140)
  Directional -> Accuracy: 0.4638, MCC: -0.0432, F1: 0.3273

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.62619 | val 0.86022
  Epoch 013 - train 0.58007 | val 0.97871
  Classification -> best τ=0.635 (val F1=0.2226)
  Directional -> Accuracy: 0.3793, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.58354 | val 1.00411
  Epoch 017 - train 0.51874 | val 1.53160
  Classification -> best τ=0.475 (val F1=0.1909)
  Directional -> Accuracy: 0.4133, MCC: 0.0949, F1: 0.0435

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.60415 | val 1.00765
  Epoch 014 - train 0.50591 | val 1.27566
  Classification -> best τ=0.305 (val F1=0.2914)
  Directional -> Accuracy: 0.5156, MCC: 0.0020, F1: 0.5867

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.50879 | val 1.67095
  Epoch 011 - train 0.47812 | val 1.73579
  Classification -> best τ=0.465 (val F1=0.2357)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.61503 | val 0.81794
  Epoch 016 - train 0.45981 | val 1.00519
  Classification -> best τ=0.545 (val F1=0.4554)
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.62282 | val 1.03270
  Epoch 012 - train 0.58773 | val 1.06050
  Classification -> best τ=0.545 (val F1=0.2709)
  Directional -> Accuracy: 0.6154, MCC: 0.2914, F1: 0.4681

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.59616 | val 0.65390
  Epoch 016 - train 0.53929 | val 1.03874
  Classification -> best τ=0.515 (val F1=0.4332)
  Directional -> Accuracy: 0.5614, MCC: 0.0773, F1: 0.6575

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.63261 | val 0.73653
  Epoch 013 - train 0.54617 | val 0.74921
  Classification -> best τ=0.635 (val F1=0.1393)
  Directional -> Accuracy: 0.5231, MCC: 0.0000, F1: 0.0000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.59785 | val 1.24668
  Epoch 013 - train 0.51102 | val 1.24235
  Classification -> best τ=0.445 (val F1=0.4306)
  Directional -> Accuracy: 0.5455, MCC: 0.0803, F1: 0.5902

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.53663 | val 3.67137
  Epoch 011 - train 0.46330 | val 4.09242
  Classification -> best τ=0.845 (val F1=0.2097)
  Directional -> Accuracy: 0.4889, MCC: -0.0120, F1: 0.4651

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.61127 | val 0.69220
  Epoch 020 - train 0.47255 | val 0.76817
  Classification -> best τ=0.500 (val F1=0.3184)
  Directional -> Accuracy: 0.5238, MCC: 0.1021, F1: 0.4737

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.57283 | val 1.21481
  Epoch 011 - train 0.53483 | val 1.32250
  Classification -> best τ=0.195 (val F1=0.3475)
  Directional -> Accuracy: 0.4821, MCC: 0.1728, F1: 0.1212

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.54391 | val 0.78637
  Epoch 016 - train 0.42548 | val 0.79310
  Classification -> best τ=0.430 (val F1=0.2509)
  Directional -> Accuracy: 0.5250, MCC: -0.0060, F1: 0.6415

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.57577 | val 1.84882
  Epoch 012 - train 0.51429 | val 2.50626
  Classification -> best τ=0.530 (val F1=0.3501)
  Directional -> Accuracy: 0.5000, MCC: -0.0092, F1: 0.4324

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.55465 | val 1.09281
  Epoch 011 - train 0.55541 | val 1.30656
  Classification -> best τ=0.420 (val F1=0.1591)
  Directional -> Accuracy: 0.3810, MCC: -0.2202, F1: 0.2353

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.50437 | val 0.86157
  Epoch 011 - train 0.46405 | val 0.89363
  Classification -> best τ=0.320 (val F1=0.3541)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.58715 | val 0.72733
  Epoch 012 - train 0.65252 | val 0.93604
  Classification -> best τ=0.170 (val F1=0.3366)
  Directional -> Accuracy: 0.5556, MCC: 0.0000, F1: 0.7143

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.56037 | val 1.01025
  Epoch 011 - train 0.49913 | val 1.34107
  Classification -> best τ=0.285 (val F1=0.2057)
  Directional -> Accuracy: 0.5116, MCC: 0.0641, F1: 0.6441

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.61149 | val 1.21724
  Epoch 011 - train 0.57774 | val 1.39213
  Classification -> best τ=0.410 (val F1=0.1898)
  Directional -> Accuracy: 0.5758, MCC: 0.0000, F1: 0.7308

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.48862 | val 1.08904
  Epoch 012 - train 0.41841 | val 1.84988
  Classification -> best τ=0.435 (val F1=0.3420)
  Directional -> Accuracy: 0.5000, MCC: 0.0142, F1: 0.4324

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.55987 | val 0.75566
  Epoch 012 - train 0.51192 | val 0.94947
  Classification -> best τ=0.610 (val F1=0.2850)
  Directional -> Accuracy: 0.5536, MCC: 0.1448, F1: 0.0741

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.56249 | val 1.56695
  Epoch 011 - train 0.47962 | val 1.37636
  Classification -> best τ=0.465 (val F1=0.3611)
  Directional -> Accuracy: 0.6087, MCC: 0.0000, F1: 0.7568

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.56994 | val 0.75889
  Epoch 011 - train 0.53159 | val 0.74907
  Classification -> best τ=0.550 (val F1=0.4306)
  Directional -> Accuracy: 0.5417, MCC: 0.0494, F1: 0.4211

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.57458 | val 2.04272
  Epoch 011 - train 0.51810 | val 1.79947
  Classification -> best τ=0.300 (val F1=0.2542)
  Directional -> Accuracy: 0.5135, MCC: 0.0515, F1: 0.6170

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.57719 | val 1.66854
  Epoch 016 - train 0.48534 | val 1.40718
  Classification -> best τ=0.570 (val F1=0.1890)
  Directional -> Accuracy: 0.5556, MCC: 0.2614, F1: 0.2308

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.48861 | val 1.59772
  Epoch 011 - train 0.52810 | val 1.92586
  Classification -> best τ=0.405 (val F1=0.1667)
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.7273

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.55994 | val 0.74282
  Epoch 015 - train 0.31775 | val 1.00889
  Classification -> best τ=0.495 (val F1=0.5689)
  Directional -> Accuracy: 0.3958, MCC: 0.0222, F1: 0.5397

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.64622 | val 1.65194
  Epoch 015 - train 0.59743 | val 1.62410
  Classification -> best τ=0.520 (val F1=0.2036)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.47095 | val 2.82969
  Epoch 011 - train 0.47528 | val 4.02712
  Classification -> best τ=0.610 (val F1=0.2669)
  Directional -> Accuracy: 0.5000, MCC: -0.0013, F1: 0.4815

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.69002 | val 0.85098
  Epoch 011 - train 0.62303 | val 0.92677
  Classification -> best τ=0.380 (val F1=0.2521)
  Directional -> Accuracy: 0.5283, MCC: 0.0707, F1: 0.6667

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.60662 | val 0.80985
  Epoch 014 - train 0.50130 | val 2.20346
  Classification -> best τ=0.755 (val F1=0.3225)
  Directional -> Accuracy: 0.4545, MCC: -0.1437, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.65055 | val 0.77261

[I 2026-02-22 13:50:20,566] Trial 203 finished with value: 0.2867919664730421 and parameters: {'feature_set': 'sector', 'model_type': 'BiGRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.4, 'batch_size': 16, 'learning_rate': 0.009873917835702949, 'weight_decay': 4.806564118370676e-05, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 0.976989561997104, 'early_stopping_min_delta': 0.001300958011279719}. Best is trial 159 with value: 0.297766251520741.

  Epoch 018 - train 0.50211 | val 1.09156
  Classification -> best τ=0.730 (val F1=0.2623)
  Directional -> Accuracy: 0.5167, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2867919664730421
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.60105 | val 1.11949
  Epoch 011 - train 0.60246 | val 0.97782
  Classification -> best τ=0.725 (val F1=0.2919)
  Directional -> Accuracy: 0.5526, MCC: 0.0000, F1: 0.0000

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.62686 | val 0.88280
  Epoch 014 - train 0.42035 | val 1.19620
  Classification -> best τ=0.755 (val F1=0.2073)
  Directional -> Accuracy: 0.6444, MCC: 0.2713, F1: 0.6923

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.61931 | val 1.25118
  Epoch 011 - train 0.58570 | val 1.35705
  Classification -> best τ=0.795 (val F1=0.2727)
  Directional -> Accuracy: 0.4783, MCC: -0.0134, F1: 0.1429

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.55842 | val 0.75333
  Epoch 011 - train 0.58765 | val 0.74634
  Classification -> best τ=0.560 (val F1=0.1895)
  Directional -> Accuracy: 0.4595, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.53180 | val 2.21275
  Epoch 013 - train 0.52009 | val 1.49006
  Classification -> best τ=0.605 (val F1=0.4947)
  Directional -> Accuracy: 0.6000, MCC: 0.2300, F1: 0.5238

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.57653 | val 1.09664
  Epoch 013 - train 0.37275 | val 1.29534
  Classification -> best τ=0.635 (val F1=0.3624)
  Directional -> Accuracy: 0.5217, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.63760 | val 0.87045
  Epoch 012 - train 0.54871 | val 1.03676
  Classification -> best τ=0.260 (val F1=0.2096)
  Directional -> Accuracy: 0.4706, MCC: 0.2286, F1: 0.6000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.50922 | val 0.94860
  Epoch 017 - train 0.50058 | val 0.94247
  Classification -> best τ=0.465 (val F1=0.3632)
  Directional -> Accuracy: 0.5000, MCC: 0.0138, F1: 0.4878

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.59187 | val 1.08174
  Epoch 011 - train 0.58121 | val 0.90995
  Classification -> best τ=0.495 (val F1=0.0255)
  Directional -> Accuracy: 0.4375, MCC: 0.0000, F1: 0.6087

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.52995 | val 0.85192
  Epoch 011 - train 0.55814 | val 0.85469
  Classification -> best τ=0.305 (val F1=0.3285)
  Directional -> Accuracy: 0.4203, MCC: 0.0000, F1: 0.5918

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.60856 | val 0.83309
  Epoch 011 - train 0.57178 | val 0.98621
  Classification -> best τ=0.580 (val F1=0.2484)
  Directional -> Accuracy: 0.5510, MCC: 0.0649, F1: 0.3889

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.70392 | val 0.80127
  Epoch 012 - train 0.57565 | val 1.08591
  Classification -> best τ=0.365 (val F1=0.2667)
  Directional -> Accuracy: 0.5088, MCC: 0.0000, F1: 0.6744

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.56008 | val 1.54337
  Epoch 015 - train 0.43764 | val 1.72851
  Classification -> best τ=0.775 (val F1=0.1225)
  Directional -> Accuracy: 0.5238, MCC: -0.1419, F1: 0.0000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.59539 | val 1.20480
  Epoch 013 - train 0.52109 | val 1.06017
  Classification -> best τ=0.315 (val F1=0.1523)
  Directional -> Accuracy: 0.5167, MCC: 0.0335, F1: 0.5397

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.63688 | val 0.71841
  Epoch 011 - train 0.58683 | val 0.71792
  Classification -> best τ=0.445 (val F1=0.2707)
  Directional -> Accuracy: 0.5490, MCC: 0.0791, F1: 0.4651

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.60812 | val 1.40054
  Epoch 011 - train 0.56438 | val 1.40098
  Classification -> best τ=0.505 (val F1=0.4077)
  Directional -> Accuracy: 0.5362, MCC: 0.0299, F1: 0.6667

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.57717 | val 1.07501
  Epoch 012 - train 0.56927 | val 1.31114
  Classification -> best τ=0.515 (val F1=0.0112)
  Directional -> Accuracy: 0.6724, MCC: 0.2563, F1: 0.7711

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.64641 | val 0.78375
  Epoch 017 - train 0.56796 | val 0.91437
  Classification -> best τ=0.615 (val F1=0.1773)
  Directional -> Accuracy: 0.4000, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.58827 | val 1.37444
  Epoch 012 - train 0.53861 | val 1.16404
  Classification -> best τ=0.320 (val F1=0.3229)
  Directional -> Accuracy: 0.5781, MCC: 0.0000, F1: 0.7327

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.53647 | val 1.26464
  Epoch 011 - train 0.53964 | val 1.56118
  Classification -> best τ=0.640 (val F1=0.2771)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.48135 | val 1.46086
  Epoch 011 - train 0.53045 | val 1.40395
  Classification -> best τ=0.660 (val F1=0.3237)
  Directional -> Accuracy: 0.3830, MCC: -0.0508, F1: 0.0645

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.63678 | val 0.93502
  Epoch 012 - train 0.56098 | val 0.95480
  Classification -> best τ=0.445 (val F1=0.2371)
  Directional -> Accuracy: 0.5231, MCC: 0.0442, F1: 0.6173

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.62690 | val 0.86944
  Epoch 016 - train 0.62143 | val 0.65947
  Classification -> best τ=0.525 (val F1=0.3656)
  Directional -> Accuracy: 0.5439, MCC: 0.0996, F1: 0.5517

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.64847 | val 0.75012
  Epoch 019 - train 0.51905 | val 1.10135
  Classification -> best τ=0.400 (val F1=0.2484)
  Directional -> Accuracy: 0.5385, MCC: 0.0836, F1: 0.1176

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.54025 | val 0.94774
  Epoch 015 - train 0.45028 | val 1.17678
  Classification -> best τ=0.515 (val F1=0.4927)
  Directional -> Accuracy: 0.5091, MCC: 0.0133, F1: 0.5424

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.50610 | val 2.89304
  Epoch 011 - train 0.50374 | val 3.50871
  Classification -> best τ=0.700 (val F1=0.0105)
  Directional -> Accuracy: 0.4444, MCC: 0.0481, F1: 0.5902

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.62546 | val 0.91617
  Epoch 015 - train 0.52965 | val 1.16003
  Classification -> best τ=0.560 (val F1=0.3536)
  Directional -> Accuracy: 0.5952, MCC: 0.2439, F1: 0.5641

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.53658 | val 1.63826
  Epoch 011 - train 0.50619 | val 1.81986
  Classification -> best τ=0.340 (val F1=0.2382)
  Directional -> Accuracy: 0.4464, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.52581 | val 0.89238
  Epoch 012 - train 0.41358 | val 0.87128
  Classification -> best τ=0.595 (val F1=0.2686)
  Directional -> Accuracy: 0.6000, MCC: 0.1830, F1: 0.7143

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.59948 | val 2.11412
  Epoch 013 - train 0.54655 | val 1.91763
  Classification -> best τ=0.410 (val F1=0.4110)
  Directional -> Accuracy: 0.5000, MCC: 0.0332, F1: 0.6038

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.59759 | val 1.09960
  Epoch 013 - train 0.54817 | val 1.86589
  Classification -> best τ=0.230 (val F1=0.2357)
  Directional -> Accuracy: 0.5000, MCC: -0.1319, F1: 0.6557

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.55531 | val 1.01025
  Epoch 011 - train 0.51842 | val 0.95609
  Classification -> best τ=0.355 (val F1=0.2918)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.61523 | val 0.79802
  Epoch 013 - train 0.52966 | val 0.73342
  Classification -> best τ=0.255 (val F1=0.4063)
  Directional -> Accuracy: 0.5278, MCC: 0.0828, F1: 0.5000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.52511 | val 1.78232
  Epoch 011 - train 0.51512 | val 2.25613
  Classification -> best τ=0.340 (val F1=0.1874)
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.58161 | val 1.27465
  Epoch 011 - train 0.55322 | val 1.31878
  Classification -> best τ=0.435 (val F1=0.1715)
  Directional -> Accuracy: 0.5758, MCC: 0.0000, F1: 0.7308

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.44971 | val 2.42356
  Epoch 012 - train 0.45463 | val 2.57655
  Classification -> best τ=0.525 (val F1=0.3001)
  Directional -> Accuracy: 0.5952, MCC: 0.2259, F1: 0.5143

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.55892 | val 1.17298
  Epoch 012 - train 0.49256 | val 1.36574
  Classification -> best τ=0.685 (val F1=0.2742)
  Directional -> Accuracy: 0.5536, MCC: 0.0818, F1: 0.3590

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.46369 | val 1.52334
  Epoch 011 - train 0.44312 | val 1.85369
  Classification -> best τ=0.540 (val F1=0.3916)
  Directional -> Accuracy: 0.6087, MCC: 0.0475, F1: 0.7500

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.60834 | val 0.87794
  Epoch 013 - train 0.48885 | val 0.76721
  Classification -> best τ=0.575 (val F1=0.4011)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.54749 | val 2.36275
  Epoch 011 - train 0.53756 | val 2.59300
  Classification -> best τ=0.545 (val F1=0.2362)
  Directional -> Accuracy: 0.4459, MCC: -0.1388, F1: 0.2545

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.64073 | val 1.24518
  Epoch 013 - train 0.53504 | val 2.30267
  Classification -> best τ=0.500 (val F1=0.4632)
  Directional -> Accuracy: 0.6000, MCC: 0.2429, F1: 0.7000

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.39945 | val 2.63339
  Epoch 011 - train 0.38681 | val 3.27750
  Classification -> best τ=0.555 (val F1=0.1021)
  Directional -> Accuracy: 0.6190, MCC: 0.2123, F1: 0.6800

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.48691 | val 0.82860
  Epoch 020 - train 0.43158 | val 1.14585
  Epoch 021 - train 0.38636 | val 1.18743
  Classification -> best τ=0.280 (val F1=0.4682)
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.5455

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.64941 | val 0.86585
  Epoch 014 - train 0.64667 | val 1.33384
  Classification -> best τ=0.590 (val F1=0.2036)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.50955 | val 2.53003
  Epoch 011 - train 0.45006 | val 3.44523
  Classification -> best τ=0.755 (val F1=0.1502)
  Directional -> Accuracy: 0.5179, MCC: 0.0000, F1: 0.0000

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.66346 | val 1.15688
  Epoch 013 - train 0.59938 | val 0.75103
  Classification -> best τ=0.475 (val F1=0.3392)
  Directional -> Accuracy: 0.5283, MCC: 0.0707, F1: 0.6667

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.49991 | val 2.66165
  Epoch 011 - train 0.49884 | val 3.06115
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5273, MCC: 0.0000, F1: 0.6905

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.62672 | val 0.80663
  Epoch 020 - train 0.57538 | val 0.78297

[I 2026-02-22 13:53:19,952] Trial 204 finished with value: 0.2692905975017514 and parameters: {'feature_set': 'sector', 'model_type': 'BiGRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.4, 'batch_size': 16, 'learning_rate': 0.009749952624586172, 'weight_decay': 4.288370613964998e-05, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 0.9837316635743982, 'early_stopping_min_delta': 0.0013511462633852128}. Best is trial 159 with value: 0.297766251520741.

  Epoch 021 - train 0.54527 | val 1.00874
  Classification -> best τ=0.300 (val F1=0.3523)
  Directional -> Accuracy: 0.5833, MCC: 0.1761, F1: 0.4186

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2692905975017514
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.62682 | val 0.74297
  Epoch 016 - train 0.55084 | val 1.94678
  Classification -> best τ=0.835 (val F1=0.2510)
  Directional -> Accuracy: 0.5526, MCC: 0.0000, F1: 0.0000

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.57275 | val 1.15641
  Epoch 011 - train 0.48222 | val 0.93513
  Classification -> best τ=0.515 (val F1=0.2523)
  Directional -> Accuracy: 0.6000, MCC: 0.1500, F1: 0.6897

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.56701 | val 1.92651
  Epoch 011 - train 0.56564 | val 1.89957
  Classification -> best τ=0.795 (val F1=0.3537)
  Directional -> Accuracy: 0.4783, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.59117 | val 1.16896
  Epoch 017 - train 0.53118 | val 1.04969
  Classification -> best τ=0.250 (val F1=0.2230)
  Directional -> Accuracy: 0.5405, MCC: 0.0000, F1: 0.7018

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.54748 | val 1.45041
  Epoch 011 - train 0.50211 | val 1.28283
  Classification -> best τ=0.570 (val F1=0.4745)
  Directional -> Accuracy: 0.6200, MCC: 0.2795, F1: 0.5366

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.52226 | val 0.76573
  Epoch 020 - train 0.33404 | val 0.94653
  Epoch 021 - train 0.38825 | val 0.75959
  Classification -> best τ=0.600 (val F1=0.3963)
  Directional -> Accuracy: 0.5217, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.59399 | val 1.08561
  Epoch 011 - train 0.56724 | val 1.35980
  Classification -> best τ=0.645 (val F1=0.2836)
  Directional -> Accuracy: 0.5294, MCC: -0.0888, F1: 0.2000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.45873 | val 0.68430
  Epoch 015 - train 0.40202 | val 0.88309
  Classification -> best τ=0.215 (val F1=0.3059)
  Directional -> Accuracy: 0.4524, MCC: 0.0534, F1: 0.5965

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.59274 | val 0.92111
  Epoch 011 - train 0.53611 | val 1.40971
  Classification -> best τ=0.470 (val F1=0.2822)
  Directional -> Accuracy: 0.5833, MCC: 0.1116, F1: 0.2857

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.57637 | val 0.89285
  Epoch 011 - train 0.53008 | val 0.99193
  Classification -> best τ=0.570 (val F1=0.3131)
  Directional -> Accuracy: 0.5217, MCC: 0.0607, F1: 0.5075

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.64649 | val 0.65843
  Epoch 013 - train 0.71901 | val 0.73461
  Classification -> best τ=0.410 (val F1=0.2877)
  Directional -> Accuracy: 0.4490, MCC: -0.0383, F1: 0.5846

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.57461 | val 0.89302
  Epoch 011 - train 0.53195 | val 1.17559
  Classification -> best τ=0.450 (val F1=0.2162)
  Directional -> Accuracy: 0.5263, MCC: 0.1360, F1: 0.6824

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.61220 | val 1.14176
  Epoch 013 - train 0.42424 | val 1.87069
  Classification -> best τ=0.585 (val F1=0.1328)
  Directional -> Accuracy: 0.5476, MCC: 0.0000, F1: 0.0000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.60280 | val 0.66384
  Epoch 013 - train 0.55058 | val 0.66271
  Classification -> best τ=0.370 (val F1=0.4691)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.60055 | val 0.69499
  Epoch 014 - train 0.51388 | val 0.79790
  Classification -> best τ=0.590 (val F1=0.2571)
  Directional -> Accuracy: 0.5490, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.56380 | val 1.19721
  Epoch 011 - train 0.54330 | val 1.28718
  Classification -> best τ=0.810 (val F1=0.3679)
  Directional -> Accuracy: 0.5072, MCC: 0.0765, F1: 0.3200

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.61725 | val 1.36596
  Epoch 012 - train 0.52231 | val 1.53130
  Classification -> best τ=0.455 (val F1=0.2321)
  Directional -> Accuracy: 0.5345, MCC: 0.0371, F1: 0.6087

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.65645 | val 0.73199
  Epoch 015 - train 0.51714 | val 0.75128
  Classification -> best τ=0.475 (val F1=0.2082)
  Directional -> Accuracy: 0.4000, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.58760 | val 1.18830
  Epoch 012 - train 0.56191 | val 1.08145
  Classification -> best τ=0.545 (val F1=0.3267)
  Directional -> Accuracy: 0.4844, MCC: 0.1062, F1: 0.2979

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.50974 | val 1.17375
  Epoch 011 - train 0.49044 | val 1.33328
  Classification -> best τ=0.355 (val F1=0.2337)
  Directional -> Accuracy: 0.5270, MCC: -0.0365, F1: 0.6667

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.50768 | val 1.28169
  Epoch 011 - train 0.47651 | val 1.73917
  Classification -> best τ=0.515 (val F1=0.1830)
  Directional -> Accuracy: 0.5745, MCC: -0.0834, F1: 0.7222

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.60325 | val 0.87765
  Epoch 012 - train 0.54567 | val 1.46252
  Classification -> best τ=0.510 (val F1=0.3356)
  Directional -> Accuracy: 0.5538, MCC: 0.1513, F1: 0.3556

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.61706 | val 0.94250
  Epoch 018 - train 0.48795 | val 1.19761
  Classification -> best τ=0.760 (val F1=0.4319)
  Directional -> Accuracy: 0.5439, MCC: 0.0737, F1: 0.5938

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.65553 | val 0.69166
  Epoch 020 - train 0.54492 | val 1.09729
  Epoch 022 - train 0.50013 | val 1.18431
  Classification -> best τ=0.645 (val F1=0.1985)
  Directional -> Accuracy: 0.5231, MCC: 0.0000, F1: 0.0000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.58622 | val 1.16587
  Epoch 012 - train 0.47936 | val 1.41979
  Classification -> best τ=0.230 (val F1=0.3887)
  Directional -> Accuracy: 0.5455, MCC: 0.0000, F1: 0.7059

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.49637 | val 3.12719
  Epoch 011 - train 0.44275 | val 3.90278
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.5938

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.55928 | val 0.72695
  Epoch 015 - train 0.49871 | val 1.03947
  Classification -> best τ=0.505 (val F1=0.1132)
  Directional -> Accuracy: 0.6190, MCC: 0.2123, F1: 0.6800

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.54289 | val 1.44720
  Epoch 011 - train 0.48440 | val 1.59672
  Classification -> best τ=0.490 (val F1=0.3558)
  Directional -> Accuracy: 0.4643, MCC: 0.1211, F1: 0.0625

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.52573 | val 2.23805
  Epoch 012 - train 0.46395 | val 2.41802
  Classification -> best τ=0.585 (val F1=0.2618)
  Directional -> Accuracy: 0.5750, MCC: 0.1240, F1: 0.7119

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.61321 | val 1.44149
  Epoch 020 - train 0.47890 | val 0.81916
  Epoch 022 - train 0.34055 | val 0.69328
  Classification -> best τ=0.520 (val F1=0.3656)
  Directional -> Accuracy: 0.4762, MCC: -0.0674, F1: 0.3529

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.60941 | val 0.73714
  Epoch 019 - train 0.41040 | val 1.02740
  Classification -> best τ=0.625 (val F1=0.2428)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.52519 | val 0.78580
  Epoch 011 - train 0.45860 | val 0.77226
  Classification -> best τ=0.495 (val F1=0.3574)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.64595 | val 0.75337
  Epoch 012 - train 0.56997 | val 1.15336
  Classification -> best τ=0.420 (val F1=0.4139)
  Directional -> Accuracy: 0.5278, MCC: 0.1419, F1: 0.3929

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.54760 | val 1.56538
  Epoch 011 - train 0.53176 | val 1.34559
  Classification -> best τ=0.330 (val F1=0.1874)
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.59071 | val 1.90126
  Epoch 013 - train 0.57852 | val 1.32976
  Classification -> best τ=0.380 (val F1=0.4438)
  Directional -> Accuracy: 0.4242, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.44789 | val 2.65847
  Epoch 014 - train 0.40687 | val 2.34468
  Classification -> best τ=0.635 (val F1=0.2228)
  Directional -> Accuracy: 0.6667, MCC: 0.3441, F1: 0.6500

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.62735 | val 0.87496
  Epoch 012 - train 0.50191 | val 1.14604
  Classification -> best τ=0.540 (val F1=0.2327)
  Directional -> Accuracy: 0.5536, MCC: 0.1049, F1: 0.5283

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.45556 | val 1.12638
  Epoch 011 - train 0.42110 | val 1.22933
  Classification -> best τ=0.515 (val F1=0.3916)
  Directional -> Accuracy: 0.5435, MCC: 0.0700, F1: 0.6038

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.52503 | val 0.74274
  Epoch 020 - train 0.46629 | val 1.87081
  Epoch 025 - train 0.32763 | val 1.46407
  Classification -> best τ=0.495 (val F1=0.3800)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.56147 | val 1.19985
  Epoch 012 - train 0.50937 | val 2.13786
  Classification -> best τ=0.745 (val F1=0.2082)
  Directional -> Accuracy: 0.4730, MCC: -0.1027, F1: 0.1702

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.58043 | val 0.75055
  Epoch 016 - train 0.46450 | val 1.48196
  Classification -> best τ=0.445 (val F1=0.4438)
  Directional -> Accuracy: 0.5556, MCC: 0.1094, F1: 0.6154

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.39963 | val 2.26939
  Epoch 011 - train 0.38947 | val 2.37407
  Classification -> best τ=0.530 (val F1=0.2408)
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.7273

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.54397 | val 0.78131
  Epoch 020 - train 0.37182 | val 0.83314
  Epoch 025 - train 0.23854 | val 1.25280
  Classification -> best τ=0.695 (val F1=0.4622)
  Directional -> Accuracy: 0.3750, MCC: -0.0976, F1: 0.5000

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.62881 | val 1.41569
  Epoch 012 - train 0.60963 | val 1.25364
  Classification -> best τ=0.490 (val F1=0.2132)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.52366 | val 2.56987
  Epoch 011 - train 0.45722 | val 3.32427
  Classification -> best τ=0.515 (val F1=0.3111)
  Directional -> Accuracy: 0.4286, MCC: -0.2466, F1: 0.6000

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.64274 | val 0.70271
  Epoch 013 - train 0.55425 | val 0.98155
  Classification -> best τ=0.505 (val F1=0.1901)
  Directional -> Accuracy: 0.6415, MCC: 0.3051, F1: 0.7077

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.57697 | val 2.57433
  Epoch 012 - train 0.46879 | val 3.37123
  Classification -> best τ=0.605 (val F1=0.1997)
  Directional -> Accuracy: 0.4182, MCC: -0.1718, F1: 0.1579

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.61290 | val 1.35559

[I 2026-02-22 13:56:14,447] Trial 205 finished with value: 0.29140413592819264 and parameters: {'feature_set': 'sector', 'model_type': 'BiGRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.4, 'batch_size': 16, 'learning_rate': 0.008134202575793817, 'weight_decay': 4.9547284396903304e-05, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 0.9685815119357148, 'early_stopping_min_delta': 0.0017993703041175356}. Best is trial 159 with value: 0.297766251520741.

  Epoch 016 - train 0.51921 | val 0.86980
  Classification -> best τ=0.580 (val F1=0.3448)
  Directional -> Accuracy: 0.5167, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.29140413592819264
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.64234 | val 0.94208
  Epoch 012 - train 0.58805 | val 1.17859
  Classification -> best τ=0.635 (val F1=0.2510)
  Directional -> Accuracy: 0.5395, MCC: -0.1039, F1: 0.0000

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.56773 | val 1.02696
  Epoch 011 - train 0.50061 | val 0.93207
  Classification -> best τ=0.490 (val F1=0.2523)
  Directional -> Accuracy: 0.6000, MCC: 0.3120, F1: 0.5263

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.65295 | val 2.66154
  Epoch 011 - train 0.54379 | val 2.83637
  Classification -> best τ=0.800 (val F1=0.3171)
  Directional -> Accuracy: 0.4783, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.59471 | val 1.16736
  Epoch 012 - train 0.56618 | val 2.01105
  Classification -> best τ=0.460 (val F1=0.1269)
  Directional -> Accuracy: 0.5405, MCC: 0.0000, F1: 0.7018

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.54788 | val 1.66716
  Epoch 011 - train 0.50837 | val 1.54959
  Classification -> best τ=0.555 (val F1=0.4611)
  Directional -> Accuracy: 0.6000, MCC: 0.2202, F1: 0.5455

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.57336 | val 0.77661
  Epoch 020 - train 0.35365 | val 0.73248
  Epoch 027 - train 0.24179 | val 0.96004
  Classification -> best τ=0.525 (val F1=0.4633)
  Directional -> Accuracy: 0.5217, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.63796 | val 1.04673
  Epoch 012 - train 0.55209 | val 1.19321
  Classification -> best τ=0.385 (val F1=0.2220)
  Directional -> Accuracy: 0.5147, MCC: 0.1463, F1: 0.5714

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.51930 | val 0.68811
  Epoch 018 - train 0.35173 | val 1.19819
  Classification -> best τ=0.385 (val F1=0.3632)
  Directional -> Accuracy: 0.5476, MCC: -0.0212, F1: 0.1739

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.54496 | val 0.89648
  Epoch 013 - train 0.51145 | val 1.91989
  Classification -> best τ=0.650 (val F1=0.1928)
  Directional -> Accuracy: 0.5417, MCC: -0.1286, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.57571 | val 0.85556
  Epoch 011 - train 0.56575 | val 0.94335
  Classification -> best τ=0.505 (val F1=0.2301)
  Directional -> Accuracy: 0.4783, MCC: -0.0139, F1: 0.4857

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.63351 | val 1.07113
  Epoch 011 - train 0.55034 | val 1.00183
  Classification -> best τ=0.490 (val F1=0.2521)
  Directional -> Accuracy: 0.5714, MCC: 0.1303, F1: 0.5116

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.56294 | val 0.92609
  Epoch 011 - train 0.58700 | val 0.96648
  Classification -> best τ=0.505 (val F1=0.3132)
  Directional -> Accuracy: 0.5614, MCC: 0.2399, F1: 0.6988

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.51550 | val 1.14993
  Epoch 011 - train 0.45790 | val 1.15073
  Classification -> best τ=0.435 (val F1=0.0548)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.6230

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.63195 | val 0.87546
  Epoch 011 - train 0.59771 | val 0.84341
  Classification -> best τ=0.455 (val F1=0.3026)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.54845 | val 1.35264
  Epoch 011 - train 0.56579 | val 1.12733
  Classification -> best τ=0.535 (val F1=0.1556)
  Directional -> Accuracy: 0.5490, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.59236 | val 1.77892
  Epoch 011 - train 0.56786 | val 1.69753
  Classification -> best τ=0.295 (val F1=0.3094)
  Directional -> Accuracy: 0.5507, MCC: 0.0764, F1: 0.6931

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.60544 | val 1.16771
  Epoch 014 - train 0.56949 | val 1.01959
  Classification -> best τ=0.600 (val F1=0.2581)
  Directional -> Accuracy: 0.3793, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.61336 | val 1.04352
  Epoch 011 - train 0.58477 | val 0.93551
  Classification -> best τ=0.330 (val F1=0.1938)
  Directional -> Accuracy: 0.4133, MCC: 0.0949, F1: 0.0435

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.60691 | val 1.76756
  Epoch 013 - train 0.54504 | val 1.27619
  Classification -> best τ=0.325 (val F1=0.3142)
  Directional -> Accuracy: 0.5781, MCC: 0.0000, F1: 0.7327

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.57944 | val 1.17227
  Epoch 014 - train 0.45702 | val 1.89527
  Classification -> best τ=0.500 (val F1=0.2902)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.56563 | val 1.11423
  Epoch 016 - train 0.46655 | val 1.23205
  Classification -> best τ=0.485 (val F1=0.2793)
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.60185 | val 1.68643
  Epoch 011 - train 0.52436 | val 2.21155
  Classification -> best τ=0.375 (val F1=0.0650)
  Directional -> Accuracy: 0.5077, MCC: 0.0000, F1: 0.6735

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.65382 | val 0.92237
  Epoch 011 - train 0.57840 | val 0.79269
  Classification -> best τ=0.415 (val F1=0.3616)
  Directional -> Accuracy: 0.6316, MCC: 0.3108, F1: 0.7529

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.63883 | val 0.96339
  Epoch 012 - train 0.57734 | val 0.94400
  Classification -> best τ=0.565 (val F1=0.1778)
  Directional -> Accuracy: 0.5231, MCC: 0.0173, F1: 0.2051

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.58383 | val 0.95067
  Epoch 012 - train 0.48948 | val 1.32480
  Classification -> best τ=0.385 (val F1=0.4688)
  Directional -> Accuracy: 0.5636, MCC: 0.1006, F1: 0.6471

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.51606 | val 2.47512
  Epoch 012 - train 0.42276 | val 2.93536
  Classification -> best τ=0.550 (val F1=0.0385)
  Directional -> Accuracy: 0.5556, MCC: -0.1289, F1: 0.0000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.56376 | val 0.75093
  Epoch 011 - train 0.55911 | val 0.76376
  Classification -> best τ=0.500 (val F1=0.1803)
  Directional -> Accuracy: 0.5000, MCC: -0.0430, F1: 0.5882

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.58313 | val 0.77563
  Epoch 012 - train 0.51926 | val 1.28656
  Classification -> best τ=0.410 (val F1=0.2742)
  Directional -> Accuracy: 0.4464, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.52784 | val 0.70678
  Epoch 012 - train 0.56296 | val 1.01586
  Classification -> best τ=0.535 (val F1=0.2618)
  Directional -> Accuracy: 0.6250, MCC: 0.3148, F1: 0.7458

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.59239 | val 1.16711
  Epoch 019 - train 0.45136 | val 1.30722
  Classification -> best τ=0.535 (val F1=0.4673)
  Directional -> Accuracy: 0.4762, MCC: -0.0674, F1: 0.3529

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.64664 | val 0.79976
  Epoch 012 - train 0.58418 | val 0.77433
  Classification -> best τ=0.600 (val F1=0.1149)
  Directional -> Accuracy: 0.6905, MCC: 0.3706, F1: 0.7347

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.51297 | val 1.05630
  Epoch 011 - train 0.49766 | val 1.16949
  Classification -> best τ=0.235 (val F1=0.2932)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.59936 | val 0.68847
  Epoch 012 - train 0.56560 | val 0.76763
  Classification -> best τ=0.310 (val F1=0.3366)
  Directional -> Accuracy: 0.5556, MCC: 0.0000, F1: 0.7143

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.61691 | val 1.05810
  Epoch 013 - train 0.40068 | val 1.20909
  Classification -> best τ=0.155 (val F1=0.2717)
  Directional -> Accuracy: 0.5581, MCC: 0.1239, F1: 0.5957

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.61341 | val 1.46419
  Epoch 013 - train 0.54548 | val 1.67461
  Classification -> best τ=0.380 (val F1=0.3017)
  Directional -> Accuracy: 0.4242, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.51293 | val 1.03500
  Epoch 013 - train 0.43724 | val 1.87240
  Classification -> best τ=0.480 (val F1=0.2858)
  Directional -> Accuracy: 0.5476, MCC: 0.1494, F1: 0.3871

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.55309 | val 2.76219
  Epoch 012 - train 0.50520 | val 1.88230
  Classification -> best τ=0.645 (val F1=0.2244)
  Directional -> Accuracy: 0.5000, MCC: 0.0214, F1: 0.5484

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.58594 | val 1.53737
  Epoch 011 - train 0.51687 | val 1.36432
  Classification -> best τ=0.655 (val F1=0.2815)
  Directional -> Accuracy: 0.4348, MCC: -0.0505, F1: 0.3810

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.52886 | val 0.77191
  Epoch 011 - train 0.57131 | val 0.73173
  Classification -> best τ=0.620 (val F1=0.4011)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.59869 | val 2.32293
  Epoch 011 - train 0.52674 | val 2.54084
  Classification -> best τ=0.315 (val F1=0.2944)
  Directional -> Accuracy: 0.4865, MCC: 0.0000, F1: 0.6545

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.57351 | val 0.89583
  Epoch 013 - train 0.54946 | val 1.34056
  Classification -> best τ=0.535 (val F1=0.4490)
  Directional -> Accuracy: 0.5556, MCC: 0.2043, F1: 0.2857

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.42461 | val 2.08145
  Epoch 012 - train 0.25929 | val 2.89404
  Classification -> best τ=0.550 (val F1=0.3948)
  Directional -> Accuracy: 0.5714, MCC: 0.1132, F1: 0.6400

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.46876 | val 0.60377
  Epoch 011 - train 0.51979 | val 0.80517
  Classification -> best τ=0.550 (val F1=0.5081)
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.0000

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.61951 | val 1.17856
  Epoch 012 - train 0.58304 | val 1.37652
  Classification -> best τ=0.495 (val F1=0.1154)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.52579 | val 1.70780
  Epoch 011 - train 0.43388 | val 2.65042
  Classification -> best τ=0.760 (val F1=0.2649)
  Directional -> Accuracy: 0.5179, MCC: 0.0000, F1: 0.0000

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.63672 | val 0.98520
  Epoch 011 - train 0.58762 | val 0.91142
  Classification -> best τ=0.500 (val F1=0.2910)
  Directional -> Accuracy: 0.5472, MCC: 0.0932, F1: 0.6129

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.55951 | val 1.26120
  Epoch 011 - train 0.51026 | val 1.92282
  Classification -> best τ=0.630 (val F1=0.0580)
  Directional -> Accuracy: 0.5273, MCC: 0.0381, F1: 0.6061

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.66012 | val 0.67703

[I 2026-02-22 13:58:52,612] Trial 206 finished with value: 0.27244073446477995 and parameters: {'feature_set': 'sector', 'model_type': 'BiGRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.4, 'batch_size': 16, 'learning_rate': 0.009943716371597, 'weight_decay': 6.643218499632391e-05, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 0.9813577248924785, 'early_stopping_min_delta': 0.001825498873803087}. Best is trial 159 with value: 0.297766251520741.

  Epoch 014 - train 0.56385 | val 0.98648
  Classification -> best τ=0.440 (val F1=0.2920)
  Directional -> Accuracy: 0.5167, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.27244073446477995
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.64759 | val 0.98771
  Epoch 011 - train 0.59758 | val 1.04596
  Classification -> best τ=0.610 (val F1=0.2510)
  Directional -> Accuracy: 0.5526, MCC: 0.0174, F1: 0.0556

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.48450 | val 0.93518
  Epoch 011 - train 0.44102 | val 1.18877
  Classification -> best τ=0.600 (val F1=0.2523)
  Directional -> Accuracy: 0.5556, MCC: 0.1308, F1: 0.5652

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.62848 | val 0.92240
  Epoch 011 - train 0.57518 | val 0.94639
  Classification -> best τ=0.690 (val F1=0.3482)
  Directional -> Accuracy: 0.4783, MCC: -0.0134, F1: 0.1429

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.63879 | val 1.55302
  Epoch 011 - train 0.55783 | val 1.79944
  Classification -> best τ=0.425 (val F1=0.2025)
  Directional -> Accuracy: 0.4865, MCC: -0.0537, F1: 0.5682

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.54384 | val 2.34823
  Epoch 013 - train 0.48050 | val 1.80731
  Classification -> best τ=0.585 (val F1=0.4947)
  Directional -> Accuracy: 0.6200, MCC: 0.2670, F1: 0.5581

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.57032 | val 0.60663
  Epoch 020 - train 0.34486 | val 0.74186
  Classification -> best τ=0.480 (val F1=0.5642)
  Directional -> Accuracy: 0.5217, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.60447 | val 0.86240
  Epoch 012 - train 0.53637 | val 1.61390
  Classification -> best τ=0.510 (val F1=0.2176)
  Directional -> Accuracy: 0.5294, MCC: 0.0046, F1: 0.3846

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.48217 | val 0.69299
  Epoch 012 - train 0.46817 | val 1.01654
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.55200 | val 1.46554
  Epoch 011 - train 0.55700 | val 2.08445
  Classification -> best τ=0.555 (val F1=0.1517)
  Directional -> Accuracy: 0.3958, MCC: -0.2100, F1: 0.3556

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.59501 | val 0.99769
  Epoch 011 - train 0.53259 | val 0.88131
  Classification -> best τ=0.325 (val F1=0.1427)
  Directional -> Accuracy: 0.4203, MCC: 0.0000, F1: 0.5918

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.65141 | val 0.85684
  Epoch 014 - train 0.55005 | val 1.30521
  Classification -> best τ=0.465 (val F1=0.4059)
  Directional -> Accuracy: 0.6122, MCC: 0.2379, F1: 0.2963

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.60612 | val 1.21333
  Epoch 014 - train 0.46576 | val 1.41829
  Classification -> best τ=0.555 (val F1=0.2819)
  Directional -> Accuracy: 0.5088, MCC: 0.0000, F1: 0.6744

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.52402 | val 3.04905
  Epoch 011 - train 0.45810 | val 3.01940
  Classification -> best τ=0.555 (val F1=0.1225)
  Directional -> Accuracy: 0.4286, MCC: -0.1114, F1: 0.5200

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.60880 | val 0.73309
  Epoch 013 - train 0.55574 | val 1.17859
  Classification -> best τ=0.260 (val F1=0.4160)
  Directional -> Accuracy: 0.5833, MCC: 0.1714, F1: 0.5283

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.57552 | val 0.70246
  Epoch 012 - train 0.52083 | val 0.77130
  Classification -> best τ=0.545 (val F1=0.3000)
  Directional -> Accuracy: 0.5098, MCC: 0.1663, F1: 0.6377

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.65006 | val 1.28881
  Epoch 012 - train 0.53833 | val 1.78317
  Classification -> best τ=0.840 (val F1=0.2337)
  Directional -> Accuracy: 0.5362, MCC: 0.0676, F1: 0.5676

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.62098 | val 1.18609
  Epoch 012 - train 0.55740 | val 1.17654
  Classification -> best τ=0.285 (val F1=0.1336)
  Directional -> Accuracy: 0.6207, MCC: 0.0000, F1: 0.7660

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.61009 | val 0.85956
  Epoch 013 - train 0.53662 | val 1.07441
  Classification -> best τ=0.480 (val F1=0.2220)
  Directional -> Accuracy: 0.4000, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.59915 | val 1.17511
  Epoch 012 - train 0.52071 | val 1.03624
  Classification -> best τ=0.790 (val F1=0.2234)
  Directional -> Accuracy: 0.4219, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.52486 | val 1.26382
  Epoch 011 - train 0.50338 | val 1.23861
  Classification -> best τ=0.420 (val F1=0.2419)
  Directional -> Accuracy: 0.3243, MCC: -0.3366, F1: 0.2647

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.50646 | val 1.30558
  Epoch 011 - train 0.48600 | val 1.59589
  Classification -> best τ=0.420 (val F1=0.1723)
  Directional -> Accuracy: 0.6170, MCC: 0.0000, F1: 0.7632

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.61260 | val 1.01965
  Epoch 011 - train 0.56833 | val 1.30963
  Classification -> best τ=0.325 (val F1=0.2794)
  Directional -> Accuracy: 0.4923, MCC: -0.0171, F1: 0.5217

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.61675 | val 0.66413
  Epoch 011 - train 0.57625 | val 0.69498
  Classification -> best τ=0.455 (val F1=0.3720)
  Directional -> Accuracy: 0.5789, MCC: 0.1002, F1: 0.7073

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.63638 | val 0.90142
  Epoch 012 - train 0.56597 | val 0.98747
  Classification -> best τ=0.490 (val F1=0.1985)
  Directional -> Accuracy: 0.6000, MCC: 0.2086, F1: 0.6176

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.57162 | val 0.84022
  Epoch 011 - train 0.52040 | val 0.94188
  Classification -> best τ=0.345 (val F1=0.4629)
  Directional -> Accuracy: 0.5818, MCC: 0.1366, F1: 0.6849

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.46951 | val 3.20210
  Epoch 012 - train 0.40202 | val 3.52768
  Classification -> best τ=0.695 (val F1=0.2035)
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.5938

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.55108 | val 0.81210
  Epoch 011 - train 0.53688 | val 0.77300
  Classification -> best τ=0.535 (val F1=0.1936)
  Directional -> Accuracy: 0.6190, MCC: 0.2340, F1: 0.6522

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.54575 | val 1.48428
  Epoch 012 - train 0.56288 | val 1.27418
  Classification -> best τ=0.320 (val F1=0.2999)
  Directional -> Accuracy: 0.5179, MCC: 0.2491, F1: 0.2286

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.51310 | val 0.93564
  Epoch 011 - train 0.55344 | val 0.91513
  Classification -> best τ=0.675 (val F1=0.1943)
  Directional -> Accuracy: 0.5000, MCC: 0.0101, F1: 0.5000

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.60437 | val 2.26962
  Epoch 013 - train 0.56315 | val 1.20185
  Classification -> best τ=0.545 (val F1=0.3501)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.4878

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.59896 | val 0.80410
  Epoch 016 - train 0.46926 | val 1.18136
  Classification -> best τ=0.355 (val F1=0.2357)
  Directional -> Accuracy: 0.5952, MCC: 0.1758, F1: 0.7119

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.50319 | val 0.98714
  Epoch 011 - train 0.46177 | val 1.23008
  Classification -> best τ=0.515 (val F1=0.3433)
  Directional -> Accuracy: 0.5102, MCC: -0.1358, F1: 0.6757

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.60514 | val 0.73685
  Epoch 015 - train 0.49989 | val 0.83787
  Classification -> best τ=0.405 (val F1=0.2831)
  Directional -> Accuracy: 0.5000, MCC: 0.0863, F1: 0.3333

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.55155 | val 0.95662
  Epoch 011 - train 0.45145 | val 0.96155
  Classification -> best τ=0.435 (val F1=0.2717)
  Directional -> Accuracy: 0.5349, MCC: 0.0973, F1: 0.6296

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.57775 | val 0.96043
  Epoch 015 - train 0.57314 | val 1.49195
  Classification -> best τ=0.150 (val F1=0.3551)
  Directional -> Accuracy: 0.4545, MCC: 0.1517, F1: 0.1000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.56063 | val 0.90484
  Epoch 012 - train 0.44820 | val 1.06100
  Classification -> best τ=0.435 (val F1=0.4011)
  Directional -> Accuracy: 0.6667, MCC: 0.3553, F1: 0.6316

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.56485 | val 0.78641
  Epoch 017 - train 0.44977 | val 1.23411
  Classification -> best τ=0.450 (val F1=0.2530)
  Directional -> Accuracy: 0.5357, MCC: 0.0534, F1: 0.4348

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.50975 | val 1.23405
  Epoch 011 - train 0.47258 | val 1.07642
  Classification -> best τ=0.540 (val F1=0.2659)
  Directional -> Accuracy: 0.5217, MCC: -0.0244, F1: 0.6207

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.53701 | val 0.60667
  Epoch 020 - train 0.47878 | val 0.84625
  Classification -> best τ=0.280 (val F1=0.4644)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.54190 | val 1.87131
  Epoch 012 - train 0.49483 | val 2.24350
  Classification -> best τ=0.255 (val F1=0.2869)
  Directional -> Accuracy: 0.4865, MCC: 0.0000, F1: 0.6545

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.61327 | val 0.74613
  Epoch 020 - train 0.31191 | val 0.76192
  Epoch 023 - train 0.32155 | val 0.90931
  Classification -> best τ=0.530 (val F1=0.4490)
  Directional -> Accuracy: 0.5111, MCC: 0.0285, F1: 0.4500

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.45252 | val 2.27785
  Epoch 011 - train 0.37224 | val 2.73166
  Classification -> best τ=0.550 (val F1=0.0364)
  Directional -> Accuracy: 0.5238, MCC: 0.0550, F1: 0.5455

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.62378 | val 0.90092
  Epoch 013 - train 0.44886 | val 0.83735
  Classification -> best τ=0.460 (val F1=0.7785)
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.5455

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.65495 | val 2.22390
  Epoch 012 - train 0.62334 | val 1.71687
  Classification -> best τ=0.585 (val F1=0.0087)
  Directional -> Accuracy: 0.3636, MCC: -0.2596, F1: 0.3137

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.45622 | val 2.33873
  Epoch 011 - train 0.46404 | val 2.42983
  Classification -> best τ=0.250 (val F1=0.2308)
  Directional -> Accuracy: 0.5000, MCC: -0.0013, F1: 0.4815

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.63693 | val 0.68076
  Epoch 017 - train 0.58681 | val 0.89434
  Classification -> best τ=0.545 (val F1=0.1824)
  Directional -> Accuracy: 0.5472, MCC: 0.1004, F1: 0.6471

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.55759 | val 4.16296
  Epoch 017 - train 0.38938 | val 3.50246
  Classification -> best τ=0.900 (val F1=0.2257)
  Directional -> Accuracy: 0.4364, MCC: -0.2052, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.59441 | val 0.95808

[I 2026-02-22 14:01:28,631] Trial 207 finished with value: 0.27734913367064534 and parameters: {'feature_set': 'sector', 'model_type': 'BiGRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.4, 'batch_size': 16, 'learning_rate': 0.00819546907774853, 'weight_decay': 4.784211258671401e-05, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 0.9499296768605605, 'early_stopping_min_delta': 0.0014538491664359118}. Best is trial 159 with value: 0.297766251520741.

  Epoch 015 - train 0.53702 | val 1.58537
  Classification -> best τ=0.400 (val F1=0.3083)
  Directional -> Accuracy: 0.5667, MCC: 0.2372, F1: 0.1875

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.27734913367064534
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.62903 | val 1.01040
  Epoch 011 - train 0.60227 | val 1.06831
  Classification -> best τ=0.685 (val F1=0.2510)
  Directional -> Accuracy: 0.5526, MCC: 0.0174, F1: 0.0556

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.54020 | val 1.14962
  Epoch 012 - train 0.46534 | val 1.18576
  Classification -> best τ=0.370 (val F1=0.2471)
  Directional -> Accuracy: 0.5778, MCC: 0.0732, F1: 0.6984

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.60721 | val 1.36341
  Epoch 012 - train 0.51486 | val 1.69738
  Classification -> best τ=0.485 (val F1=0.2725)
  Directional -> Accuracy: 0.5217, MCC: 0.0596, F1: 0.4500

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.64043 | val 1.15759
  Epoch 014 - train 0.53054 | val 0.99397
  Classification -> best τ=0.540 (val F1=0.1808)
  Directional -> Accuracy: 0.5405, MCC: 0.0000, F1: 0.7018

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.52950 | val 2.93315
  Epoch 011 - train 0.47894 | val 2.90488
  Classification -> best τ=0.555 (val F1=0.3945)
  Directional -> Accuracy: 0.6600, MCC: 0.3245, F1: 0.6531

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.55190 | val 0.83296
  Epoch 012 - train 0.47208 | val 0.82450
  Classification -> best τ=0.540 (val F1=0.2303)
  Directional -> Accuracy: 0.5217, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.58473 | val 1.11160
  Epoch 011 - train 0.56970 | val 1.41637
  Classification -> best τ=0.695 (val F1=0.2043)
  Directional -> Accuracy: 0.5882, MCC: 0.0017, F1: 0.1250

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.51900 | val 0.79189
  Epoch 017 - train 0.41462 | val 0.82314
  Classification -> best τ=0.410 (val F1=0.3632)
  Directional -> Accuracy: 0.5000, MCC: 0.0138, F1: 0.4878

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.58084 | val 1.86011
  Epoch 012 - train 0.50996 | val 1.93719
  Classification -> best τ=0.425 (val F1=0.2925)
  Directional -> Accuracy: 0.4375, MCC: 0.0000, F1: 0.6087

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.52592 | val 1.15133
  Epoch 011 - train 0.50384 | val 1.33048
  Classification -> best τ=0.530 (val F1=0.3492)
  Directional -> Accuracy: 0.5217, MCC: 0.0811, F1: 0.5352

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.64108 | val 0.69704
  Epoch 014 - train 0.48481 | val 0.75021
  Classification -> best τ=0.570 (val F1=0.4059)
  Directional -> Accuracy: 0.5918, MCC: 0.1804, F1: 0.2308

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.63797 | val 1.26937
  Epoch 012 - train 0.49425 | val 2.34832
  Classification -> best τ=0.380 (val F1=0.2434)
  Directional -> Accuracy: 0.5088, MCC: 0.0000, F1: 0.6744

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.47433 | val 2.64530
  Epoch 011 - train 0.45446 | val 2.81960
  Classification -> best τ=0.425 (val F1=0.0795)
  Directional -> Accuracy: 0.5952, MCC: 0.1664, F1: 0.4516

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.60254 | val 0.73471
  Epoch 012 - train 0.58574 | val 0.69653
  Classification -> best τ=0.480 (val F1=0.3916)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.60991 | val 0.83440
  Epoch 011 - train 0.53503 | val 0.96900
  Classification -> best τ=0.495 (val F1=0.2078)
  Directional -> Accuracy: 0.5490, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.58089 | val 1.31424
  Epoch 011 - train 0.55169 | val 1.34038
  Classification -> best τ=0.575 (val F1=0.3104)
  Directional -> Accuracy: 0.5072, MCC: 0.0874, F1: 0.2917

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.60598 | val 1.21637
  Epoch 017 - train 0.47822 | val 1.20853
  Classification -> best τ=0.535 (val F1=0.1973)
  Directional -> Accuracy: 0.4138, MCC: 0.1477, F1: 0.1053

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.59574 | val 0.89064
  Epoch 011 - train 0.54378 | val 1.14952
  Classification -> best τ=0.530 (val F1=0.2004)
  Directional -> Accuracy: 0.4000, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.59359 | val 0.82974
  Epoch 018 - train 0.44261 | val 1.06141
  Classification -> best τ=0.485 (val F1=0.3662)
  Directional -> Accuracy: 0.5469, MCC: 0.1156, F1: 0.5538

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.53179 | val 1.36499
  Epoch 011 - train 0.51363 | val 1.69997
  Classification -> best τ=0.560 (val F1=0.2700)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.53899 | val 2.33262
  Epoch 012 - train 0.45881 | val 2.18759
  Classification -> best τ=0.410 (val F1=0.2247)
  Directional -> Accuracy: 0.6170, MCC: 0.0000, F1: 0.7632

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.61140 | val 1.16424
  Epoch 011 - train 0.55219 | val 1.30367
  Classification -> best τ=0.355 (val F1=0.1382)
  Directional -> Accuracy: 0.5231, MCC: 0.0480, F1: 0.6437

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.60398 | val 0.58385
  Epoch 020 - train 0.48980 | val 0.89142
  Classification -> best τ=0.420 (val F1=0.4938)
  Directional -> Accuracy: 0.5789, MCC: 0.1706, F1: 0.5862

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.59658 | val 0.71939
  Epoch 012 - train 0.51346 | val 0.72447
  Classification -> best τ=0.480 (val F1=0.1568)
  Directional -> Accuracy: 0.5385, MCC: 0.0842, F1: 0.5588

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.63818 | val 1.08771
  Epoch 012 - train 0.47330 | val 0.87088
  Classification -> best τ=0.290 (val F1=0.4607)
  Directional -> Accuracy: 0.5273, MCC: 0.1286, F1: 0.3810

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.53626 | val 3.14564
  Epoch 011 - train 0.52876 | val 3.06233
  Classification -> best τ=0.625 (val F1=0.1890)
  Directional -> Accuracy: 0.6222, MCC: 0.2314, F1: 0.5641

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.63865 | val 0.83833
  Epoch 012 - train 0.54741 | val 0.69786
  Classification -> best τ=0.580 (val F1=0.1936)
  Directional -> Accuracy: 0.5476, MCC: 0.0446, F1: 0.6415

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.58335 | val 0.98960
  Epoch 012 - train 0.43600 | val 1.73834
  Classification -> best τ=0.455 (val F1=0.2622)
  Directional -> Accuracy: 0.4464, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.52251 | val 0.74979
  Epoch 011 - train 0.50783 | val 0.75178
  Classification -> best τ=0.435 (val F1=0.0252)
  Directional -> Accuracy: 0.6000, MCC: 0.2536, F1: 0.7333

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.62079 | val 0.66154
  Epoch 020 - train 0.39111 | val 1.09639
  Classification -> best τ=0.505 (val F1=0.3823)
  Directional -> Accuracy: 0.4762, MCC: -0.0500, F1: 0.4500

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.66299 | val 0.90656
  Epoch 015 - train 0.44484 | val 1.14768
  Classification -> best τ=0.335 (val F1=0.2357)
  Directional -> Accuracy: 0.5714, MCC: 0.1718, F1: 0.7188

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.50551 | val 1.13983
  Epoch 011 - train 0.44945 | val 1.19356
  Classification -> best τ=0.690 (val F1=0.2969)
  Directional -> Accuracy: 0.4694, MCC: 0.0000, F1: 0.0000

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.57619 | val 1.60615
  Epoch 013 - train 0.54177 | val 1.64491
  Classification -> best τ=0.330 (val F1=0.3534)
  Directional -> Accuracy: 0.5278, MCC: 0.2273, F1: 0.2917

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.48410 | val 1.35179
  Epoch 011 - train 0.51498 | val 1.41949
  Classification -> best τ=0.260 (val F1=0.2324)
  Directional -> Accuracy: 0.4884, MCC: -0.0261, F1: 0.4500

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.57590 | val 1.79945
  Epoch 011 - train 0.53397 | val 2.26739
  Classification -> best τ=0.480 (val F1=0.2605)
  Directional -> Accuracy: 0.5152, MCC: -0.0867, F1: 0.6522

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.52339 | val 4.98123
  Epoch 011 - train 0.46793 | val 4.53507
  Classification -> best τ=0.485 (val F1=0.2618)
  Directional -> Accuracy: 0.5952, MCC: 0.2656, F1: 0.4516

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.59018 | val 0.85726
  Epoch 017 - train 0.40849 | val 0.90259
  Classification -> best τ=0.635 (val F1=0.2742)
  Directional -> Accuracy: 0.6071, MCC: 0.2119, F1: 0.4211

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.52758 | val 0.95987
  Epoch 011 - train 0.49559 | val 1.06449
  Classification -> best τ=0.430 (val F1=0.3397)
  Directional -> Accuracy: 0.5870, MCC: -0.0314, F1: 0.7324

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.52690 | val 0.91708
  Epoch 011 - train 0.52249 | val 0.93743
  Classification -> best τ=0.430 (val F1=0.3656)
  Directional -> Accuracy: 0.4792, MCC: 0.1257, F1: 0.5283

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.62146 | val 1.44628
  Epoch 011 - train 0.48956 | val 1.92807
  Classification -> best τ=0.335 (val F1=0.2998)
  Directional -> Accuracy: 0.5000, MCC: 0.0044, F1: 0.5316

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.56511 | val 0.89310
  Epoch 016 - train 0.58885 | val 1.34446
  Classification -> best τ=0.490 (val F1=0.5000)
  Directional -> Accuracy: 0.5111, MCC: 0.0199, F1: 0.5417

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.37900 | val 2.65657
  Epoch 011 - train 0.37615 | val 3.05645
  Classification -> best τ=0.415 (val F1=0.1667)
  Directional -> Accuracy: 0.4762, MCC: -0.2161, F1: 0.6333

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.50868 | val 0.92576
  Epoch 015 - train 0.35945 | val 2.83550
  Classification -> best τ=0.530 (val F1=0.3458)
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.5455

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.63479 | val 0.90870
  Epoch 013 - train 0.61854 | val 0.96132
  Classification -> best τ=0.725 (val F1=0.1757)
  Directional -> Accuracy: 0.4727, MCC: 0.1242, F1: 0.0645

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.54031 | val 2.83561
  Epoch 011 - train 0.43303 | val 3.23332
  Classification -> best τ=0.440 (val F1=0.3930)
  Directional -> Accuracy: 0.5000, MCC: -0.0013, F1: 0.4815

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.65841 | val 0.69806
  Epoch 015 - train 0.58949 | val 0.87682
  Classification -> best τ=0.715 (val F1=0.2719)
  Directional -> Accuracy: 0.5849, MCC: 0.1688, F1: 0.6071

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.58966 | val 4.01465
  Epoch 012 - train 0.50861 | val 3.74689
  Classification -> best τ=0.705 (val F1=0.1682)
  Directional -> Accuracy: 0.5273, MCC: 0.0153, F1: 0.6750

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.61396 | val 0.71955

[I 2026-02-22 14:04:11,550] Trial 208 finished with value: 0.2751437731653629 and parameters: {'feature_set': 'sector', 'model_type': 'BiGRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.4, 'batch_size': 16, 'learning_rate': 0.0076776459802107575, 'weight_decay': 5.145391045098657e-05, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 0.9944617288098365, 'early_stopping_min_delta': 0.0014993365412545136}. Best is trial 159 with value: 0.297766251520741.

  Epoch 012 - train 0.57771 | val 0.95486
  Classification -> best τ=0.630 (val F1=0.2810)
  Directional -> Accuracy: 0.6333, MCC: 0.3009, F1: 0.4762

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2751437731653629
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.64482 | val 1.00272
  Epoch 011 - train 0.58211 | val 1.05353
  Classification -> best τ=0.620 (val F1=0.2510)
  Directional -> Accuracy: 0.5526, MCC: 0.0000, F1: 0.0000

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.65320 | val 0.99833
  Epoch 013 - train 0.49617 | val 1.10954
  Classification -> best τ=0.380 (val F1=0.1844)
  Directional -> Accuracy: 0.6000, MCC: 0.1500, F1: 0.6897

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.57314 | val 1.95401
  Epoch 011 - train 0.54338 | val 2.28686
  Classification -> best τ=0.670 (val F1=0.3313)
  Directional -> Accuracy: 0.4565, MCC: -0.0996, F1: 0.0741

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.60833 | val 0.94279
  Epoch 020 - train 0.45523 | val 0.88753
  Epoch 024 - train 0.40724 | val 0.74463
  Classification -> best τ=0.280 (val F1=0.2593)
  Directional -> Accuracy: 0.5405, MCC: 0.0000, F1: 0.7018

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.50211 | val 2.66496
  Epoch 011 - train 0.45404 | val 3.02263
  Classification -> best τ=0.330 (val F1=0.4602)
  Directional -> Accuracy: 0.7000, MCC: 0.4048, F1: 0.6939

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.48490 | val 1.06405
  Epoch 011 - train 0.45466 | val 1.18033
  Classification -> best τ=0.595 (val F1=0.2585)
  Directional -> Accuracy: 0.5217, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.65603 | val 1.06714
  Epoch 012 - train 0.57605 | val 0.87001
  Classification -> best τ=0.410 (val F1=0.2766)
  Directional -> Accuracy: 0.4412, MCC: -0.0669, F1: 0.4571

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.52943 | val 1.01244
  Epoch 018 - train 0.35283 | val 0.88909
  Classification -> best τ=0.115 (val F1=0.2810)
  Directional -> Accuracy: 0.4762, MCC: 0.0525, F1: 0.5769

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.58120 | val 1.47045
  Epoch 012 - train 0.51692 | val 2.60620
  Classification -> best τ=0.630 (val F1=0.3959)
  Directional -> Accuracy: 0.6042, MCC: 0.1680, F1: 0.3871

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.59714 | val 0.96309
  Epoch 015 - train 0.47588 | val 1.09493
  Classification -> best τ=0.810 (val F1=0.1552)
  Directional -> Accuracy: 0.5652, MCC: 0.1078, F1: 0.4828

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.56129 | val 0.95843
  Epoch 011 - train 0.58878 | val 1.12996
  Classification -> best τ=0.545 (val F1=0.1976)
  Directional -> Accuracy: 0.4286, MCC: -0.1599, F1: 0.6000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.55224 | val 1.77513
  Epoch 012 - train 0.54910 | val 1.73266
  Classification -> best τ=0.465 (val F1=0.2487)
  Directional -> Accuracy: 0.5088, MCC: 0.0000, F1: 0.6744

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.50569 | val 3.24521
  Epoch 011 - train 0.42095 | val 3.75571
  Classification -> best τ=0.640 (val F1=0.1225)
  Directional -> Accuracy: 0.4048, MCC: -0.1940, F1: 0.5614

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.62318 | val 0.79373
  Epoch 012 - train 0.58720 | val 0.82601
  Classification -> best τ=0.535 (val F1=0.3642)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.60443 | val 0.78004
  Epoch 011 - train 0.55700 | val 0.81884
  Classification -> best τ=0.465 (val F1=0.3592)
  Directional -> Accuracy: 0.6471, MCC: 0.2786, F1: 0.5500

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.55781 | val 1.02912
  Epoch 011 - train 0.51566 | val 1.35524
  Classification -> best τ=0.390 (val F1=0.3094)
  Directional -> Accuracy: 0.5507, MCC: 0.1304, F1: 0.7048

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.62667 | val 0.91445
  Epoch 012 - train 0.53814 | val 1.15246
  Classification -> best τ=0.335 (val F1=0.2683)
  Directional -> Accuracy: 0.6207, MCC: 0.0000, F1: 0.7660

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.62019 | val 0.75095
  Epoch 019 - train 0.48308 | val 0.86912
  Classification -> best τ=0.595 (val F1=0.2220)
  Directional -> Accuracy: 0.4000, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.58120 | val 1.11838
  Epoch 012 - train 0.53432 | val 1.21407
  Classification -> best τ=0.415 (val F1=0.3421)
  Directional -> Accuracy: 0.4844, MCC: -0.1459, F1: 0.6207

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.55970 | val 1.11664
  Epoch 011 - train 0.48575 | val 1.30386
  Classification -> best τ=0.455 (val F1=0.3161)
  Directional -> Accuracy: 0.4730, MCC: 0.1495, F1: 0.0930

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.52608 | val 1.29485
  Epoch 011 - train 0.54167 | val 1.29118
  Classification -> best τ=0.580 (val F1=0.3020)
  Directional -> Accuracy: 0.4894, MCC: 0.1254, F1: 0.4000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.60495 | val 1.43730
  Epoch 012 - train 0.53203 | val 1.05524
  Classification -> best τ=0.605 (val F1=0.2757)
  Directional -> Accuracy: 0.4923, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.64989 | val 0.67874
  Epoch 017 - train 0.51442 | val 0.85893
  Classification -> best τ=0.760 (val F1=0.3833)
  Directional -> Accuracy: 0.5965, MCC: 0.1771, F1: 0.6462

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.60940 | val 0.76903
  Epoch 011 - train 0.56232 | val 0.72502
  Classification -> best τ=0.690 (val F1=0.1874)
  Directional -> Accuracy: 0.5077, MCC: -0.0632, F1: 0.0588

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.58833 | val 0.82232
  Epoch 013 - train 0.46736 | val 1.05734
  Classification -> best τ=0.385 (val F1=0.4688)
  Directional -> Accuracy: 0.4909, MCC: 0.0305, F1: 0.3636

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.53505 | val 2.06765
  Epoch 011 - train 0.44848 | val 1.84018
  Classification -> best τ=0.770 (val F1=0.1823)
  Directional -> Accuracy: 0.5111, MCC: -0.0318, F1: 0.3529

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.55178 | val 1.04652
  Epoch 012 - train 0.56768 | val 0.87858
  Classification -> best τ=0.550 (val F1=0.1353)
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.0000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.50730 | val 1.40380
  Epoch 011 - train 0.52808 | val 1.33795
  Classification -> best τ=0.445 (val F1=0.2850)
  Directional -> Accuracy: 0.4464, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.53740 | val 1.24364
  Epoch 012 - train 0.47428 | val 1.24500
  Classification -> best τ=0.470 (val F1=0.4139)
  Directional -> Accuracy: 0.5750, MCC: 0.1140, F1: 0.7018

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.57989 | val 2.34965
  Epoch 011 - train 0.56843 | val 2.69493
  Classification -> best τ=0.585 (val F1=0.1959)
  Directional -> Accuracy: 0.4762, MCC: -0.2132, F1: 0.0000

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.66611 | val 1.06144
  Epoch 013 - train 0.60833 | val 1.29508
  Classification -> best τ=0.385 (val F1=0.2357)
  Directional -> Accuracy: 0.5476, MCC: 0.0000, F1: 0.7077

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.49469 | val 1.36417
  Epoch 013 - train 0.43328 | val 1.14437
  Classification -> best τ=0.420 (val F1=0.2837)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.53569 | val 0.84741
  Epoch 013 - train 0.52862 | val 1.04489
  Classification -> best τ=0.330 (val F1=0.4719)
  Directional -> Accuracy: 0.5556, MCC: 0.0000, F1: 0.7143

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.50996 | val 1.04673
  Epoch 011 - train 0.47178 | val 1.07840
  Classification -> best τ=0.495 (val F1=0.0852)
  Directional -> Accuracy: 0.4884, MCC: -0.0179, F1: 0.5417

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.60750 | val 1.06759
  Epoch 011 - train 0.54642 | val 1.18787
  Classification -> best τ=0.585 (val F1=0.2566)
  Directional -> Accuracy: 0.4242, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.44480 | val 2.00843
  Epoch 011 - train 0.41716 | val 2.54844
  Classification -> best τ=0.505 (val F1=0.2665)
  Directional -> Accuracy: 0.6190, MCC: 0.2864, F1: 0.5294

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.57143 | val 0.76442
  Epoch 012 - train 0.48018 | val 0.88581
  Classification -> best τ=0.450 (val F1=0.2305)
  Directional -> Accuracy: 0.6071, MCC: 0.2204, F1: 0.3889

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.51094 | val 0.80196
  Epoch 011 - train 0.44802 | val 0.87546
  Classification -> best τ=0.570 (val F1=0.3294)
  Directional -> Accuracy: 0.4348, MCC: -0.0505, F1: 0.3810

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.59358 | val 0.73543
  Epoch 012 - train 0.49919 | val 0.66257
  Classification -> best τ=0.570 (val F1=0.4011)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.54160 | val 2.03366
  Epoch 011 - train 0.51949 | val 2.50587
  Classification -> best τ=0.105 (val F1=0.2112)
  Directional -> Accuracy: 0.4595, MCC: -0.0836, F1: 0.4286

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.59262 | val 0.74686
  Epoch 011 - train 0.58488 | val 0.82753
  Classification -> best τ=0.505 (val F1=0.2169)
  Directional -> Accuracy: 0.5111, MCC: 0.0000, F1: 0.6765

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.35107 | val 2.30199
  Epoch 012 - train 0.34621 | val 2.18449
  Classification -> best τ=0.395 (val F1=0.4423)
  Directional -> Accuracy: 0.6429, MCC: 0.2527, F1: 0.7170

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.51353 | val 0.64039
  Epoch 020 - train 0.33906 | val 0.68593
  Epoch 023 - train 0.35385 | val 0.69844
  Classification -> best τ=0.610 (val F1=0.6110)
  Directional -> Accuracy: 0.5208, MCC: 0.3201, F1: 0.6102

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.66175 | val 0.91930
  Epoch 013 - train 0.61959 | val 2.23430
  Classification -> best τ=0.550 (val F1=0.2036)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.46517 | val 2.20032
  Epoch 011 - train 0.44585 | val 2.43568
  Classification -> best τ=0.435 (val F1=0.1949)
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.6506

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.62443 | val 0.84224
  Epoch 012 - train 0.62732 | val 0.79802
  Classification -> best τ=0.780 (val F1=0.1668)
  Directional -> Accuracy: 0.5283, MCC: 0.1124, F1: 0.2424

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.63651 | val 2.11151
  Epoch 012 - train 0.49206 | val 1.92332
  Classification -> best τ=0.575 (val F1=0.1757)
  Directional -> Accuracy: 0.5273, MCC: 0.0000, F1: 0.6905

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.63908 | val 0.82226

[I 2026-02-22 14:06:46,127] Trial 209 finished with value: 0.28157462091555013 and parameters: {'feature_set': 'sector', 'model_type': 'BiGRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.4, 'batch_size': 16, 'learning_rate': 0.008379133696518846, 'weight_decay': 7.726524599719652e-05, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 1.0048310101307987, 'early_stopping_min_delta': 0.0011252350306711683}. Best is trial 159 with value: 0.297766251520741.

  Epoch 016 - train 0.55298 | val 1.10871
  Classification -> best τ=0.290 (val F1=0.2992)
  Directional -> Accuracy: 0.5500, MCC: 0.1044, F1: 0.3077

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.28157462091555013
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.60445 | val 1.11936
  Epoch 011 - train 0.58905 | val 1.08421
  Classification -> best τ=0.725 (val F1=0.2510)
  Directional -> Accuracy: 0.5789, MCC: 0.1291, F1: 0.2000

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.59207 | val 1.08711
  Epoch 011 - train 0.49023 | val 1.19290
  Classification -> best τ=0.520 (val F1=0.2405)
  Directional -> Accuracy: 0.5778, MCC: 0.0000, F1: 0.7324

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.62761 | val 2.12666
  Epoch 012 - train 0.52749 | val 2.38007
  Classification -> best τ=0.685 (val F1=0.2398)
  Directional -> Accuracy: 0.4783, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.62616 | val 0.86345
  Epoch 019 - train 0.52396 | val 1.35630
  Classification -> best τ=0.520 (val F1=0.1895)
  Directional -> Accuracy: 0.4865, MCC: -0.1463, F1: 0.6415

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.52298 | val 1.13849
  Epoch 011 - train 0.51107 | val 1.33900
  Classification -> best τ=0.575 (val F1=0.4083)
  Directional -> Accuracy: 0.6000, MCC: 0.2425, F1: 0.5000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.55105 | val 0.71173
  Epoch 020 - train 0.36297 | val 1.20386
  Epoch 021 - train 0.30170 | val 1.50441
  Classification -> best τ=0.495 (val F1=0.4559)
  Directional -> Accuracy: 0.5217, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.58751 | val 1.77643
  Epoch 014 - train 0.55387 | val 1.03711
  Classification -> best τ=0.465 (val F1=0.2536)
  Directional -> Accuracy: 0.6324, MCC: 0.1815, F1: 0.3902

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.56462 | val 0.71296
  Epoch 017 - train 0.42148 | val 0.98096
  Classification -> best τ=0.390 (val F1=0.3632)
  Directional -> Accuracy: 0.3810, MCC: -0.3347, F1: 0.1333

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.53126 | val 1.81429
  Epoch 013 - train 0.55904 | val 1.37774
  Classification -> best τ=0.195 (val F1=0.2497)
  Directional -> Accuracy: 0.4375, MCC: 0.0000, F1: 0.6087

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.63434 | val 0.87122
  Epoch 011 - train 0.56685 | val 0.86296
  Classification -> best τ=0.615 (val F1=0.2739)
  Directional -> Accuracy: 0.4928, MCC: -0.0459, F1: 0.3860

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.57368 | val 0.73001
  Epoch 011 - train 0.52294 | val 0.72233
  Classification -> best τ=0.620 (val F1=0.2484)
  Directional -> Accuracy: 0.5918, MCC: 0.1804, F1: 0.2308

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.63254 | val 2.32263
  Epoch 011 - train 0.59687 | val 2.19151
  Classification -> best τ=0.510 (val F1=0.2162)
  Directional -> Accuracy: 0.6491, MCC: 0.3361, F1: 0.7222

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.52763 | val 2.04965
  Epoch 012 - train 0.49880 | val 1.61937
  Classification -> best τ=0.370 (val F1=0.1754)
  Directional -> Accuracy: 0.4048, MCC: -0.1940, F1: 0.5614

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.61609 | val 0.64544
  Epoch 014 - train 0.50671 | val 0.81910
  Classification -> best τ=0.415 (val F1=0.3768)
  Directional -> Accuracy: 0.5167, MCC: 0.1302, F1: 0.0645

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.60050 | val 0.70787
  Epoch 016 - train 0.52246 | val 0.77029
  Classification -> best τ=0.585 (val F1=0.3000)
  Directional -> Accuracy: 0.5490, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.60717 | val 1.66746
  Epoch 012 - train 0.55125 | val 1.19800
  Classification -> best τ=0.780 (val F1=0.2616)
  Directional -> Accuracy: 0.5217, MCC: 0.0490, F1: 0.5217

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.66375 | val 0.83910
  Epoch 012 - train 0.55274 | val 1.22517
  Classification -> best τ=0.410 (val F1=0.1862)
  Directional -> Accuracy: 0.4483, MCC: 0.1066, F1: 0.2727

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.58070 | val 1.31749
  Epoch 011 - train 0.55851 | val 1.70015
  Classification -> best τ=0.470 (val F1=0.1909)
  Directional -> Accuracy: 0.4000, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.61925 | val 0.92968
  Epoch 012 - train 0.52683 | val 1.03997
  Classification -> best τ=0.455 (val F1=0.2433)
  Directional -> Accuracy: 0.5000, MCC: 0.0250, F1: 0.5000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.53359 | val 1.01277
  Epoch 011 - train 0.55053 | val 1.09550
  Classification -> best τ=0.350 (val F1=0.2771)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.50117 | val 1.76823
  Epoch 013 - train 0.42116 | val 1.65625
  Classification -> best τ=0.340 (val F1=0.2784)
  Directional -> Accuracy: 0.4681, MCC: 0.1702, F1: 0.2857

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.59135 | val 1.17602
  Epoch 012 - train 0.53320 | val 1.31266
  Classification -> best τ=0.520 (val F1=0.3161)
  Directional -> Accuracy: 0.4923, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.62888 | val 0.70813
  Epoch 019 - train 0.51550 | val 0.85778
  Classification -> best τ=0.585 (val F1=0.4532)
  Directional -> Accuracy: 0.5088, MCC: 0.0471, F1: 0.4815

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.62002 | val 0.78860
  Epoch 015 - train 0.52795 | val 1.14121
  Classification -> best τ=0.765 (val F1=0.1985)
  Directional -> Accuracy: 0.5231, MCC: 0.0000, F1: 0.0000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.54128 | val 0.85003
  Epoch 013 - train 0.46899 | val 1.54752
  Classification -> best τ=0.530 (val F1=0.4994)
  Directional -> Accuracy: 0.5636, MCC: 0.1406, F1: 0.5556

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.49182 | val 2.51688
  Epoch 011 - train 0.47577 | val 2.58248
  Classification -> best τ=0.680 (val F1=0.2035)
  Directional -> Accuracy: 0.6000, MCC: 0.3487, F1: 0.6667

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.54523 | val 0.74372
  Epoch 015 - train 0.48527 | val 0.76577
  Classification -> best τ=0.555 (val F1=0.0829)
  Directional -> Accuracy: 0.5476, MCC: 0.0574, F1: 0.6275

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.59946 | val 1.28700
  Epoch 012 - train 0.52734 | val 1.97867
  Classification -> best τ=0.340 (val F1=0.3873)
  Directional -> Accuracy: 0.4464, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.45111 | val 0.71742
  Epoch 011 - train 0.44575 | val 0.75329
  Classification -> best τ=0.565 (val F1=0.2267)
  Directional -> Accuracy: 0.5250, MCC: 0.0259, F1: 0.5957

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.57979 | val 0.74701
  Epoch 020 - train 0.42549 | val 1.10187
  Epoch 024 - train 0.34832 | val 1.29601
  Classification -> best τ=0.520 (val F1=0.5210)
  Directional -> Accuracy: 0.4524, MCC: -0.1003, F1: 0.4103

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.57595 | val 1.60786
  Epoch 013 - train 0.48031 | val 0.93995
  Classification -> best τ=0.385 (val F1=0.2357)
  Directional -> Accuracy: 0.5476, MCC: 0.0000, F1: 0.7077

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.57054 | val 0.97118
  Epoch 012 - train 0.44335 | val 1.44171
  Classification -> best τ=0.625 (val F1=0.4339)
  Directional -> Accuracy: 0.3673, MCC: -0.2931, F1: 0.1143

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.59684 | val 0.77877
  Epoch 017 - train 0.47748 | val 1.03271
  Classification -> best τ=0.400 (val F1=0.4286)
  Directional -> Accuracy: 0.5417, MCC: 0.1004, F1: 0.5352

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.54838 | val 1.03091
  Epoch 011 - train 0.47232 | val 1.18439
  Classification -> best τ=0.405 (val F1=0.3078)
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.60079 | val 2.18987
  Epoch 011 - train 0.53519 | val 2.47365
  Classification -> best τ=0.625 (val F1=0.2618)
  Directional -> Accuracy: 0.4242, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.47068 | val 2.17703
  Epoch 011 - train 0.44069 | val 3.60962
  Classification -> best τ=0.565 (val F1=0.3001)
  Directional -> Accuracy: 0.6429, MCC: 0.2860, F1: 0.6512

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.55101 | val 0.97836
  Epoch 012 - train 0.50984 | val 0.98899
  Classification -> best τ=0.555 (val F1=0.2530)
  Directional -> Accuracy: 0.5357, MCC: 0.0769, F1: 0.5357

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.49049 | val 1.09098
  Epoch 011 - train 0.45436 | val 1.54413
  Classification -> best τ=0.435 (val F1=0.1298)
  Directional -> Accuracy: 0.6304, MCC: 0.1493, F1: 0.7536

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.56604 | val 1.61850
  Epoch 017 - train 0.46873 | val 0.99544
  Classification -> best τ=0.395 (val F1=0.4011)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.52684 | val 1.78240
  Epoch 011 - train 0.52777 | val 1.87548
  Classification -> best τ=0.785 (val F1=0.3146)
  Directional -> Accuracy: 0.5135, MCC: 0.0000, F1: 0.0000

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.56274 | val 1.41205
  Epoch 017 - train 0.49773 | val 2.49513
  Classification -> best τ=0.445 (val F1=0.5493)
  Directional -> Accuracy: 0.4667, MCC: -0.0644, F1: 0.2941

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.48279 | val 2.83708
  Epoch 012 - train 0.41339 | val 3.15875
  Classification -> best τ=0.445 (val F1=0.4082)
  Directional -> Accuracy: 0.6429, MCC: 0.2527, F1: 0.7170

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.57614 | val 0.69479
  Epoch 014 - train 0.39126 | val 0.78216
  Classification -> best τ=0.540 (val F1=0.6290)
  Directional -> Accuracy: 0.4167, MCC: 0.0778, F1: 0.5484

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.68634 | val 0.93623
  Epoch 012 - train 0.63737 | val 0.85817
  Classification -> best τ=0.640 (val F1=0.1647)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.48937 | val 1.51519
  Epoch 011 - train 0.45358 | val 1.84563
  Classification -> best τ=0.355 (val F1=0.2998)
  Directional -> Accuracy: 0.5357, MCC: 0.0728, F1: 0.5357

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.63684 | val 0.89175
  Epoch 016 - train 0.51982 | val 0.83028
  Classification -> best τ=0.675 (val F1=0.1668)
  Directional -> Accuracy: 0.5660, MCC: 0.1410, F1: 0.5106

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.56069 | val 3.36301
  Epoch 012 - train 0.46853 | val 4.38054
  Classification -> best τ=0.580 (val F1=0.1399)
  Directional -> Accuracy: 0.5091, MCC: -0.0671, F1: 0.6667

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.67073 | val 0.67519

[I 2026-02-22 14:09:32,776] Trial 210 finished with value: 0.2969770662810303 and parameters: {'feature_set': 'sector', 'model_type': 'BiGRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.4, 'batch_size': 16, 'learning_rate': 0.008389629839916977, 'weight_decay': 7.580279579077769e-05, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 1.0243303782492967, 'early_stopping_min_delta': 0.0017226469214105815}. Best is trial 159 with value: 0.297766251520741.

  Epoch 017 - train 0.56296 | val 0.68025
  Classification -> best τ=0.620 (val F1=0.2623)
  Directional -> Accuracy: 0.5167, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2969770662810303
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.63892 | val 0.94231
  Epoch 014 - train 0.58442 | val 1.09369
  Classification -> best τ=0.830 (val F1=0.2919)
  Directional -> Accuracy: 0.5526, MCC: 0.0000, F1: 0.0000

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.52678 | val 0.89656
  Epoch 011 - train 0.47501 | val 0.96338
  Classification -> best τ=0.485 (val F1=0.1941)
  Directional -> Accuracy: 0.6222, MCC: 0.2110, F1: 0.6909

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.64785 | val 1.26870
  Epoch 014 - train 0.49472 | val 1.38069
  Classification -> best τ=0.675 (val F1=0.2311)
  Directional -> Accuracy: 0.4783, MCC: -0.0093, F1: 0.0769

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.62486 | val 1.45792
  Epoch 017 - train 0.57398 | val 0.80079
  Classification -> best τ=0.380 (val F1=0.2585)
  Directional -> Accuracy: 0.4730, MCC: 0.0520, F1: 0.0930

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.54340 | val 0.98433
  Epoch 011 - train 0.52115 | val 1.32500
  Classification -> best τ=0.665 (val F1=0.4556)
  Directional -> Accuracy: 0.6400, MCC: 0.3158, F1: 0.5714

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.53315 | val 0.78373
  Epoch 015 - train 0.39053 | val 1.13717
  Classification -> best τ=0.670 (val F1=0.2208)
  Directional -> Accuracy: 0.5217, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.60739 | val 1.03613
  Epoch 014 - train 0.52696 | val 1.00629
  Classification -> best τ=0.545 (val F1=0.3353)
  Directional -> Accuracy: 0.5882, MCC: 0.1742, F1: 0.5333

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.50853 | val 0.56244
  Epoch 017 - train 0.46434 | val 1.31294
  Classification -> best τ=0.600 (val F1=0.3632)
  Directional -> Accuracy: 0.5476, MCC: 0.0574, F1: 0.4242

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.54334 | val 1.01559
  Epoch 011 - train 0.59423 | val 0.81433
  Classification -> best τ=0.620 (val F1=0.2285)
  Directional -> Accuracy: 0.6042, MCC: 0.1899, F1: 0.2400

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.59335 | val 0.74972
  Epoch 012 - train 0.53404 | val 0.78041
  Classification -> best τ=0.360 (val F1=0.1745)
  Directional -> Accuracy: 0.4638, MCC: 0.0500, F1: 0.5747

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.56405 | val 0.76623
  Epoch 011 - train 0.57749 | val 0.77802
  Classification -> best τ=0.445 (val F1=0.2765)
  Directional -> Accuracy: 0.5714, MCC: 0.1179, F1: 0.4615

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.60129 | val 1.35104
  Epoch 011 - train 0.58242 | val 1.33532
  Classification -> best τ=0.330 (val F1=0.1512)
  Directional -> Accuracy: 0.5088, MCC: 0.0000, F1: 0.6744

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.49237 | val 1.03835
  Epoch 011 - train 0.46431 | val 0.99860
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.6230

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.58073 | val 0.78842
  Epoch 018 - train 0.48645 | val 1.34234
  Classification -> best τ=0.515 (val F1=0.2516)
  Directional -> Accuracy: 0.5500, MCC: 0.1155, F1: 0.4000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.63993 | val 0.73272
  Epoch 020 - train 0.46295 | val 0.75662
  Classification -> best τ=0.785 (val F1=0.2571)
  Directional -> Accuracy: 0.5490, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.61623 | val 1.11635
  Epoch 011 - train 0.55961 | val 1.10210
  Classification -> best τ=0.560 (val F1=0.2212)
  Directional -> Accuracy: 0.5362, MCC: 0.0497, F1: 0.6190

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.59691 | val 0.97901
  Epoch 012 - train 0.53729 | val 1.01338
  Classification -> best τ=0.590 (val F1=0.2184)
  Directional -> Accuracy: 0.3793, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.64715 | val 0.82291
  Epoch 011 - train 0.57172 | val 0.86758
  Classification -> best τ=0.525 (val F1=0.1909)
  Directional -> Accuracy: 0.4000, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.61505 | val 1.61421
  Epoch 012 - train 0.53285 | val 1.62686
  Classification -> best τ=0.255 (val F1=0.2843)
  Directional -> Accuracy: 0.5781, MCC: 0.0000, F1: 0.7327

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.57898 | val 1.35556
  Epoch 011 - train 0.50014 | val 1.53131
  Classification -> best τ=0.310 (val F1=0.0321)
  Directional -> Accuracy: 0.5541, MCC: 0.0000, F1: 0.7130

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.60944 | val 0.96595
  Epoch 014 - train 0.44048 | val 1.95222
  Classification -> best τ=0.400 (val F1=0.2559)
  Directional -> Accuracy: 0.4468, MCC: -0.1043, F1: 0.5000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.62627 | val 1.18156
  Epoch 012 - train 0.53946 | val 2.28936
  Classification -> best τ=0.450 (val F1=0.2874)
  Directional -> Accuracy: 0.5846, MCC: 0.1968, F1: 0.4706

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.60907 | val 0.79999
  Epoch 017 - train 0.54106 | val 0.92313
  Classification -> best τ=0.485 (val F1=0.4370)
  Directional -> Accuracy: 0.6842, MCC: 0.3540, F1: 0.7273

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.61478 | val 0.85086
  Epoch 011 - train 0.57415 | val 0.90825
  Classification -> best τ=0.455 (val F1=0.1978)
  Directional -> Accuracy: 0.5385, MCC: 0.1091, F1: 0.6154

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.57249 | val 1.02180
  Epoch 012 - train 0.52205 | val 1.20604
  Classification -> best τ=0.255 (val F1=0.4524)
  Directional -> Accuracy: 0.5273, MCC: 0.0279, F1: 0.6061

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.53699 | val 2.17735
  Epoch 011 - train 0.45625 | val 1.82223
  Classification -> best τ=0.725 (val F1=0.2097)
  Directional -> Accuracy: 0.4222, MCC: -0.1842, F1: 0.3158

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.59880 | val 0.99559
  Epoch 016 - train 0.53742 | val 0.71135
  Classification -> best τ=0.525 (val F1=0.3873)
  Directional -> Accuracy: 0.5714, MCC: 0.1840, F1: 0.5500

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.54918 | val 2.04874
  Epoch 011 - train 0.52113 | val 2.09573
  Classification -> best τ=0.455 (val F1=0.2976)
  Directional -> Accuracy: 0.4464, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.51944 | val 0.91228
  Epoch 011 - train 0.47863 | val 0.91592
  Classification -> best τ=0.505 (val F1=0.2618)
  Directional -> Accuracy: 0.6000, MCC: 0.2536, F1: 0.7333

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.59492 | val 1.95173
  Epoch 012 - train 0.56184 | val 1.74178
  Classification -> best τ=0.490 (val F1=0.3501)
  Directional -> Accuracy: 0.5476, MCC: 0.1137, F1: 0.5957

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.62634 | val 0.65682
  Epoch 020 - train 0.42370 | val 1.01152
  Classification -> best τ=0.430 (val F1=0.2357)
  Directional -> Accuracy: 0.5714, MCC: 0.1718, F1: 0.7188

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.44792 | val 0.94422
  Epoch 011 - train 0.42363 | val 1.09015
  Classification -> best τ=0.440 (val F1=0.2837)
  Directional -> Accuracy: 0.4694, MCC: 0.0000, F1: 0.0000

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.63080 | val 0.76540
  Epoch 012 - train 0.54259 | val 0.93467
  Classification -> best τ=0.650 (val F1=0.3278)
  Directional -> Accuracy: 0.4444, MCC: 0.0000, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.52024 | val 0.91486
  Epoch 011 - train 0.48960 | val 0.84271
  Classification -> best τ=0.535 (val F1=0.2151)
  Directional -> Accuracy: 0.6047, MCC: 0.3278, F1: 0.3200

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.55446 | val 0.94415
  Epoch 011 - train 0.51392 | val 1.52360
  Classification -> best τ=0.570 (val F1=0.2249)
  Directional -> Accuracy: 0.4242, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.51080 | val 1.41957
  Epoch 012 - train 0.37763 | val 1.64149
  Classification -> best τ=0.390 (val F1=0.2067)
  Directional -> Accuracy: 0.6667, MCC: 0.3318, F1: 0.6818

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.60194 | val 0.76279
  Epoch 012 - train 0.54477 | val 0.77930
  Classification -> best τ=0.540 (val F1=0.1951)
  Directional -> Accuracy: 0.5536, MCC: 0.0891, F1: 0.4444

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.46833 | val 0.81518
  Epoch 011 - train 0.46253 | val 0.90218
  Classification -> best τ=0.530 (val F1=0.3677)
  Directional -> Accuracy: 0.5870, MCC: 0.0062, F1: 0.7246

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.57857 | val 0.65092
  Epoch 014 - train 0.58675 | val 0.65145
  Classification -> best τ=0.450 (val F1=0.4011)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.54420 | val 2.03805
  Epoch 011 - train 0.50017 | val 2.13380
  Classification -> best τ=0.140 (val F1=0.3052)
  Directional -> Accuracy: 0.4865, MCC: 0.0000, F1: 0.6545

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.55566 | val 0.94350
  Epoch 018 - train 0.56086 | val 1.33582
  Classification -> best τ=0.465 (val F1=0.4632)
  Directional -> Accuracy: 0.5778, MCC: 0.1692, F1: 0.5128

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.51871 | val 2.34111
  Epoch 012 - train 0.25731 | val 2.22665
  Classification -> best τ=0.650 (val F1=0.4971)
  Directional -> Accuracy: 0.4524, MCC: -0.0700, F1: 0.4390

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.50008 | val 0.87657
  Epoch 012 - train 0.46596 | val 0.76999
  Classification -> best τ=0.710 (val F1=0.1371)
  Directional -> Accuracy: 0.4792, MCC: 0.1516, F1: 0.5614

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.63179 | val 1.09417
  Epoch 012 - train 0.61938 | val 1.18437
  Classification -> best τ=0.525 (val F1=0.2681)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.46613 | val 1.57059
  Epoch 011 - train 0.44567 | val 2.19271
  Classification -> best τ=0.650 (val F1=0.3246)
  Directional -> Accuracy: 0.5536, MCC: 0.1100, F1: 0.5614

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.59088 | val 0.70030
  Epoch 014 - train 0.57553 | val 0.86893
  Classification -> best τ=0.500 (val F1=0.3033)
  Directional -> Accuracy: 0.5283, MCC: 0.1413, F1: 0.6835

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.54424 | val 1.95216
  Epoch 011 - train 0.47468 | val 2.56057
  Classification -> best τ=0.785 (val F1=0.0580)
  Directional -> Accuracy: 0.4364, MCC: -0.1359, F1: 0.1143

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.59592 | val 1.01205

[I 2026-02-22 14:12:14,179] Trial 211 finished with value: 0.2677209924026113 and parameters: {'feature_set': 'sector', 'model_type': 'BiGRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.4, 'batch_size': 16, 'learning_rate': 0.00865326637915971, 'weight_decay': 5.957458111399907e-05, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 1.0185873214290926, 'early_stopping_min_delta': 0.0017661444733177714}. Best is trial 159 with value: 0.297766251520741.

  Epoch 011 - train 0.58807 | val 0.93423
  Classification -> best τ=0.535 (val F1=0.2623)
  Directional -> Accuracy: 0.5000, MCC: -0.0689, F1: 0.0625

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2677209924026113
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.58847 | val 1.23170
  Epoch 013 - train 0.59860 | val 1.36386
  Classification -> best τ=0.330 (val F1=0.2262)
  Directional -> Accuracy: 0.5789, MCC: 0.1935, F1: 0.6098

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.56155 | val 0.82960
  Epoch 013 - train 0.50427 | val 1.16965
  Classification -> best τ=0.725 (val F1=0.1323)
  Directional -> Accuracy: 0.6000, MCC: 0.1924, F1: 0.6400

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.68503 | val 1.26511
  Epoch 012 - train 0.58943 | val 1.17533
  Classification -> best τ=0.540 (val F1=0.2727)
  Directional -> Accuracy: 0.4783, MCC: -0.0134, F1: 0.1429

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.60172 | val 0.90258
  Epoch 011 - train 0.61040 | val 0.83842
  Classification -> best τ=0.480 (val F1=0.0073)
  Directional -> Accuracy: 0.5405, MCC: 0.0000, F1: 0.7018

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.51210 | val 1.02909
  Epoch 011 - train 0.48787 | val 1.10840
  Classification -> best τ=0.680 (val F1=0.4259)
  Directional -> Accuracy: 0.6000, MCC: 0.2425, F1: 0.5000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.54897 | val 1.05252
  Epoch 017 - train 0.43395 | val 0.79629
  Classification -> best τ=0.745 (val F1=0.3210)
  Directional -> Accuracy: 0.5217, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.60173 | val 1.72394
  Epoch 011 - train 0.59066 | val 1.95169
  Classification -> best τ=0.665 (val F1=0.1753)
  Directional -> Accuracy: 0.5735, MCC: 0.0328, F1: 0.2927

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.54799 | val 0.64881
  Epoch 016 - train 0.41124 | val 0.93561
  Classification -> best τ=0.190 (val F1=0.3094)
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.53720 | val 1.45191
  Epoch 011 - train 0.43855 | val 2.64009
  Classification -> best τ=0.630 (val F1=0.1928)
  Directional -> Accuracy: 0.6458, MCC: 0.2656, F1: 0.5143

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.60867 | val 0.90224
  Epoch 012 - train 0.55386 | val 0.77385
  Classification -> best τ=0.470 (val F1=0.3006)
  Directional -> Accuracy: 0.4058, MCC: -0.1264, F1: 0.4938

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.62356 | val 1.00996
  Epoch 016 - train 0.52001 | val 3.04570
  Classification -> best τ=0.600 (val F1=0.3075)
  Directional -> Accuracy: 0.5918, MCC: 0.1804, F1: 0.2308

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.58191 | val 0.87695
  Epoch 011 - train 0.52698 | val 1.34810
  Classification -> best τ=0.745 (val F1=0.0241)
  Directional -> Accuracy: 0.4561, MCC: -0.1422, F1: 0.0606

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.57671 | val 0.88835
  Epoch 013 - train 0.50784 | val 1.33884
  Classification -> best τ=0.765 (val F1=0.2942)
  Directional -> Accuracy: 0.5476, MCC: 0.0000, F1: 0.0000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.61839 | val 0.62581
  Epoch 020 - train 0.44867 | val 0.69860
  Classification -> best τ=0.340 (val F1=0.3601)
  Directional -> Accuracy: 0.5333, MCC: 0.0707, F1: 0.4400

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.65032 | val 0.93189
  Epoch 015 - train 0.52931 | val 0.92277
  Classification -> best τ=0.680 (val F1=0.2571)
  Directional -> Accuracy: 0.5490, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.58069 | val 1.20862
  Epoch 011 - train 0.53647 | val 1.19244
  Classification -> best τ=0.455 (val F1=0.1890)
  Directional -> Accuracy: 0.4928, MCC: -0.0359, F1: 0.5679

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.64598 | val 0.82149
  Epoch 013 - train 0.54330 | val 0.83558
  Classification -> best τ=0.420 (val F1=0.3233)
  Directional -> Accuracy: 0.3793, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.59045 | val 1.14419
  Epoch 011 - train 0.55214 | val 1.41494
  Classification -> best τ=0.610 (val F1=0.1909)
  Directional -> Accuracy: 0.4000, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.56013 | val 1.91238
  Epoch 011 - train 0.51498 | val 2.22904
  Classification -> best τ=0.455 (val F1=0.3622)
  Directional -> Accuracy: 0.5469, MCC: 0.1050, F1: 0.5672

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.61809 | val 2.07461
  Epoch 011 - train 0.53589 | val 1.92804
  Classification -> best τ=0.285 (val F1=0.1537)
  Directional -> Accuracy: 0.5541, MCC: 0.0000, F1: 0.7130

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.55491 | val 1.23422
  Epoch 011 - train 0.50371 | val 0.91495
  Classification -> best τ=0.570 (val F1=0.2449)
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.53700 | val 1.30637
  Epoch 011 - train 0.54083 | val 1.54121
  Classification -> best τ=0.255 (val F1=0.2673)
  Directional -> Accuracy: 0.5077, MCC: 0.0000, F1: 0.6735

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.61783 | val 0.80392
  Epoch 013 - train 0.55853 | val 1.18839
  Classification -> best τ=0.830 (val F1=0.4376)
  Directional -> Accuracy: 0.4561, MCC: 0.0241, F1: 0.1622

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.63448 | val 0.88073
  Epoch 017 - train 0.53653 | val 0.72644
  Classification -> best τ=0.395 (val F1=0.3411)
  Directional -> Accuracy: 0.4923, MCC: 0.0112, F1: 0.5926

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.54653 | val 0.85852
  Epoch 012 - train 0.49154 | val 0.90131
  Classification -> best τ=0.500 (val F1=0.4674)
  Directional -> Accuracy: 0.4909, MCC: 0.0402, F1: 0.3333

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.60984 | val 3.69890
  Epoch 011 - train 0.42135 | val 4.49980
  Classification -> best τ=0.780 (val F1=0.0447)
  Directional -> Accuracy: 0.4000, MCC: -0.2060, F1: 0.3415

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.63770 | val 0.80919
  Epoch 012 - train 0.56403 | val 0.81128
  Classification -> best τ=0.540 (val F1=0.3184)
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.0000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.57692 | val 0.94534
  Epoch 011 - train 0.52225 | val 1.14097
  Classification -> best τ=0.460 (val F1=0.2916)
  Directional -> Accuracy: 0.5357, MCC: 0.2308, F1: 0.3158

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.61104 | val 0.75426
  Epoch 013 - train 0.45922 | val 0.72110
  Classification -> best τ=0.510 (val F1=0.2414)
  Directional -> Accuracy: 0.6250, MCC: 0.3148, F1: 0.7458

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.55737 | val 2.56720
  Epoch 014 - train 0.49237 | val 2.96527
  Classification -> best τ=0.565 (val F1=0.3501)
  Directional -> Accuracy: 0.5476, MCC: 0.0953, F1: 0.5366

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.61781 | val 0.76081
  Epoch 014 - train 0.40171 | val 1.15441
  Classification -> best τ=0.520 (val F1=0.2328)
  Directional -> Accuracy: 0.3810, MCC: -0.2392, F1: 0.4091

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.45419 | val 0.91895
  Epoch 011 - train 0.45177 | val 1.10273
  Classification -> best τ=0.395 (val F1=0.2837)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.63627 | val 0.69109
  Epoch 019 - train 0.43317 | val 0.87398
  Classification -> best τ=0.565 (val F1=0.3842)
  Directional -> Accuracy: 0.5139, MCC: 0.1467, F1: 0.3137

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.56416 | val 1.22548
  Epoch 011 - train 0.51867 | val 1.27802
  Classification -> best τ=0.770 (val F1=0.1818)
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.57565 | val 1.52458
  Epoch 011 - train 0.60842 | val 1.44608
  Classification -> best τ=0.540 (val F1=0.4416)
  Directional -> Accuracy: 0.5303, MCC: -0.1873, F1: 0.6931

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.50962 | val 1.30843
  Epoch 014 - train 0.48745 | val 2.42518
  Classification -> best τ=0.310 (val F1=0.3218)
  Directional -> Accuracy: 0.6190, MCC: 0.2412, F1: 0.6923

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.54504 | val 0.71577
  Epoch 020 - train 0.34769 | val 0.84723
  Epoch 021 - train 0.34603 | val 0.96953
  Classification -> best τ=0.435 (val F1=0.1684)
  Directional -> Accuracy: 0.4821, MCC: -0.0555, F1: 0.3830

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.53363 | val 1.19194
  Epoch 011 - train 0.43497 | val 1.04357
  Classification -> best τ=0.395 (val F1=0.1241)
  Directional -> Accuracy: 0.5870, MCC: 0.0324, F1: 0.7164

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.59356 | val 1.41149
  Epoch 015 - train 0.48710 | val 0.94151
  Classification -> best τ=0.625 (val F1=0.4011)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.55107 | val 1.63857
  Epoch 011 - train 0.49649 | val 1.77865
  Classification -> best τ=0.775 (val F1=0.2327)
  Directional -> Accuracy: 0.4730, MCC: -0.1027, F1: 0.1702

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.60324 | val 0.75834
  Epoch 014 - train 0.47802 | val 0.82836
  Classification -> best τ=0.525 (val F1=0.4080)
  Directional -> Accuracy: 0.5333, MCC: 0.1221, F1: 0.2759

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.48845 | val 2.62785
  Epoch 012 - train 0.33346 | val 2.86795
  Classification -> best τ=0.610 (val F1=0.4082)
  Directional -> Accuracy: 0.4762, MCC: -0.0278, F1: 0.4762

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.51705 | val 0.73463
  Epoch 011 - train 0.51334 | val 0.73625
  Classification -> best τ=0.600 (val F1=0.6590)
  Directional -> Accuracy: 0.6667, MCC: 0.2692, F1: 0.2000

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.70354 | val 1.21933
  Epoch 011 - train 0.61944 | val 1.25716
  Classification -> best τ=0.520 (val F1=0.2036)
  Directional -> Accuracy: 0.4000, MCC: -0.2631, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.47424 | val 2.44064
  Epoch 011 - train 0.45074 | val 2.69288
  Classification -> best τ=0.535 (val F1=0.1552)
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.6506

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.72965 | val 0.73905
  Epoch 017 - train 0.58086 | val 0.90162
  Classification -> best τ=0.385 (val F1=0.2866)
  Directional -> Accuracy: 0.6226, MCC: 0.2483, F1: 0.6667

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.54118 | val 3.19694
  Epoch 011 - train 0.50913 | val 3.56677
  Classification -> best τ=0.790 (val F1=0.1884)
  Directional -> Accuracy: 0.4545, MCC: -0.1437, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.62499 | val 0.71197

[I 2026-02-22 14:15:01,981] Trial 212 finished with value: 0.2736304895003834 and parameters: {'feature_set': 'sector', 'model_type': 'BiGRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.4, 'batch_size': 16, 'learning_rate': 0.009833284085666295, 'weight_decay': 8.035488660868566e-05, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 0.9597429788615017, 'early_stopping_min_delta': 0.0012075240409730205}. Best is trial 159 with value: 0.297766251520741.

  Epoch 014 - train 0.55143 | val 1.87360
  Classification -> best τ=0.315 (val F1=0.2231)
  Directional -> Accuracy: 0.6333, MCC: 0.2888, F1: 0.5000

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2736304895003834
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.63669 | val 1.19620
  Epoch 012 - train 0.61833 | val 1.25583
  Classification -> best τ=0.580 (val F1=0.2510)
  Directional -> Accuracy: 0.5395, MCC: -0.1039, F1: 0.0000

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.48889 | val 1.11204
  Epoch 013 - train 0.51936 | val 1.04400
  Classification -> best τ=0.890 (val F1=0.2523)
  Directional -> Accuracy: 0.5333, MCC: 0.0782, F1: 0.5532

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.59576 | val 1.54615
  Epoch 011 - train 0.57582 | val 1.88465
  Classification -> best τ=0.785 (val F1=0.2941)
  Directional -> Accuracy: 0.5217, MCC: 0.1124, F1: 0.2667

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.64026 | val 0.73773
  Epoch 011 - train 0.56895 | val 0.92958
  Classification -> best τ=0.525 (val F1=0.1235)
  Directional -> Accuracy: 0.5405, MCC: 0.0322, F1: 0.6731

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.55330 | val 1.36342
  Epoch 011 - train 0.50847 | val 1.48804
  Classification -> best τ=0.495 (val F1=0.3984)
  Directional -> Accuracy: 0.6200, MCC: 0.2573, F1: 0.5778

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.56295 | val 1.18125
  Epoch 011 - train 0.48403 | val 0.90651
  Classification -> best τ=0.490 (val F1=0.1808)
  Directional -> Accuracy: 0.5870, MCC: 0.1695, F1: 0.4865

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.57497 | val 0.86422
  Epoch 013 - train 0.55589 | val 0.95218
  Classification -> best τ=0.780 (val F1=0.1753)
  Directional -> Accuracy: 0.5735, MCC: 0.0813, F1: 0.4082

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.51951 | val 0.67489
  Epoch 011 - train 0.47469 | val 0.69791
  Classification -> best τ=0.310 (val F1=0.4215)
  Directional -> Accuracy: 0.4048, MCC: -0.1578, F1: 0.4444

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.56568 | val 2.90311
  Epoch 013 - train 0.47608 | val 2.43110
  Classification -> best τ=0.500 (val F1=0.3047)
  Directional -> Accuracy: 0.6042, MCC: 0.1746, F1: 0.2963

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.58663 | val 0.74853
  Epoch 020 - train 0.49200 | val 0.87963
  Epoch 024 - train 0.40484 | val 0.87196
  Classification -> best τ=0.600 (val F1=0.2162)
  Directional -> Accuracy: 0.4783, MCC: -0.0921, F1: 0.3333

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.59225 | val 0.82217
  Epoch 018 - train 0.46654 | val 0.93221
  Classification -> best τ=0.430 (val F1=0.2661)
  Directional -> Accuracy: 0.5918, MCC: 0.1537, F1: 0.3750

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.57991 | val 1.62417
  Epoch 011 - train 0.54514 | val 1.97749
  Classification -> best τ=0.325 (val F1=0.0236)
  Directional -> Accuracy: 0.5439, MCC: 0.1204, F1: 0.6750

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.53688 | val 1.10775
  Epoch 011 - train 0.45145 | val 1.90783
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.6230

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.59949 | val 0.79287
  Epoch 011 - train 0.57750 | val 0.76229
  Classification -> best τ=0.405 (val F1=0.2845)
  Directional -> Accuracy: 0.5667, MCC: 0.1333, F1: 0.5667

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.60209 | val 0.79034
  Epoch 011 - train 0.52931 | val 0.73174
  Classification -> best τ=0.510 (val F1=0.2571)
  Directional -> Accuracy: 0.5490, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.58526 | val 1.01261
  Epoch 011 - train 0.52954 | val 0.88822
  Classification -> best τ=0.525 (val F1=0.1835)
  Directional -> Accuracy: 0.4783, MCC: -0.0324, F1: 0.4545

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.57085 | val 0.81843
  Epoch 011 - train 0.60553 | val 0.91530
  Classification -> best τ=0.515 (val F1=0.2743)
  Directional -> Accuracy: 0.3793, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.63558 | val 1.27591
  Epoch 012 - train 0.51437 | val 1.34272
  Classification -> best τ=0.370 (val F1=0.1243)
  Directional -> Accuracy: 0.5733, MCC: -0.0727, F1: 0.7241

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.61484 | val 1.27684
  Epoch 014 - train 0.51816 | val 1.12269
  Classification -> best τ=0.475 (val F1=0.2624)
  Directional -> Accuracy: 0.4375, MCC: 0.0398, F1: 0.1000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.52039 | val 1.65431
  Epoch 011 - train 0.50909 | val 1.84073
  Classification -> best τ=0.510 (val F1=0.2096)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.57334 | val 1.53880
  Epoch 013 - train 0.46337 | val 1.14196
  Classification -> best τ=0.540 (val F1=0.3140)
  Directional -> Accuracy: 0.4468, MCC: -0.1043, F1: 0.5000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.62402 | val 1.48242
  Epoch 012 - train 0.57809 | val 1.40436
  Classification -> best τ=0.585 (val F1=0.2815)
  Directional -> Accuracy: 0.5231, MCC: 0.1269, F1: 0.6804

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.61623 | val 0.62630
  Epoch 017 - train 0.52754 | val 0.74395
  Classification -> best τ=0.650 (val F1=0.6078)
  Directional -> Accuracy: 0.5439, MCC: 0.0157, F1: 0.6667

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.58459 | val 1.56972
  Epoch 013 - train 0.58438 | val 1.54668
  Classification -> best τ=0.545 (val F1=0.1874)
  Directional -> Accuracy: 0.5846, MCC: 0.1798, F1: 0.6087

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.55268 | val 0.92121
  Epoch 012 - train 0.43909 | val 1.29577
  Classification -> best τ=0.480 (val F1=0.4947)
  Directional -> Accuracy: 0.5273, MCC: 0.1463, F1: 0.3500

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.46595 | val 3.67830
  Epoch 012 - train 0.41810 | val 3.71584
  Classification -> best τ=0.690 (val F1=0.2570)
  Directional -> Accuracy: 0.5333, MCC: 0.2428, F1: 0.6316

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.59550 | val 0.74989
  Epoch 020 - train 0.46635 | val 0.74727
  Epoch 029 - train 0.35612 | val 1.25268
  Classification -> best τ=0.560 (val F1=0.3062)
  Directional -> Accuracy: 0.6429, MCC: 0.2661, F1: 0.6939

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.55008 | val 1.26015
  Epoch 011 - train 0.55446 | val 1.40779
  Classification -> best τ=0.260 (val F1=0.3143)
  Directional -> Accuracy: 0.4643, MCC: 0.1211, F1: 0.0625

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.56307 | val 1.60326
  Epoch 017 - train 0.46520 | val 1.08318
  Classification -> best τ=0.475 (val F1=0.2509)
  Directional -> Accuracy: 0.5500, MCC: 0.1111, F1: 0.5500

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.56766 | val 0.69649
  Epoch 019 - train 0.38673 | val 1.37700
  Classification -> best τ=0.745 (val F1=0.3501)
  Directional -> Accuracy: 0.5238, MCC: 0.0267, F1: 0.3333

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.57658 | val 0.81608
  Epoch 018 - train 0.43773 | val 1.13061
  Classification -> best τ=0.850 (val F1=0.1846)
  Directional -> Accuracy: 0.5714, MCC: 0.2415, F1: 0.4375

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.59359 | val 1.08379
  Epoch 012 - train 0.42276 | val 1.15362
  Classification -> best τ=0.610 (val F1=0.2399)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.58864 | val 1.07728
  Epoch 013 - train 0.51655 | val 0.92174
  Classification -> best τ=0.425 (val F1=0.3076)
  Directional -> Accuracy: 0.5694, MCC: 0.0888, F1: 0.6869

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.50308 | val 1.18200
  Epoch 011 - train 0.44264 | val 1.26572
  Classification -> best τ=0.580 (val F1=0.2603)
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.58783 | val 1.00796
  Epoch 011 - train 0.59248 | val 1.08655
  Classification -> best τ=0.610 (val F1=0.2249)
  Directional -> Accuracy: 0.4697, MCC: 0.1299, F1: 0.1860

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.48257 | val 1.11330
  Epoch 011 - train 0.44090 | val 1.32886
  Classification -> best τ=0.490 (val F1=0.2228)
  Directional -> Accuracy: 0.6429, MCC: 0.3290, F1: 0.5714

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.56207 | val 0.96765
  Epoch 011 - train 0.49472 | val 1.35170
  Classification -> best τ=0.450 (val F1=0.1884)
  Directional -> Accuracy: 0.5179, MCC: 0.0555, F1: 0.5574

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.51089 | val 1.17582
  Epoch 011 - train 0.44779 | val 1.19845
  Classification -> best τ=0.540 (val F1=0.2734)
  Directional -> Accuracy: 0.5870, MCC: 0.0062, F1: 0.7246

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.54894 | val 0.92071
  Epoch 011 - train 0.49729 | val 0.91023
  Classification -> best τ=0.505 (val F1=0.3887)
  Directional -> Accuracy: 0.4792, MCC: -0.0182, F1: 0.4186

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.48873 | val 1.58129
  Epoch 011 - train 0.50613 | val 1.86349
  Classification -> best τ=0.655 (val F1=0.2327)
  Directional -> Accuracy: 0.4865, MCC: -0.1131, F1: 0.0500

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.57457 | val 0.85389
  Epoch 013 - train 0.50537 | val 1.04719
  Classification -> best τ=0.555 (val F1=0.3873)
  Directional -> Accuracy: 0.4444, MCC: -0.1188, F1: 0.2424

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.37793 | val 1.64710
  Epoch 011 - train 0.30502 | val 1.45379
  Classification -> best τ=0.625 (val F1=0.5345)
  Directional -> Accuracy: 0.5714, MCC: 0.0468, F1: 0.7097

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.52532 | val 0.78429
  Epoch 020 - train 0.38804 | val 0.58911
  Epoch 029 - train 0.21950 | val 0.64634
  Classification -> best τ=0.595 (val F1=0.6947)
  Directional -> Accuracy: 0.5625, MCC: 0.3200, F1: 0.6182

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.67259 | val 0.74879
  Epoch 013 - train 0.59567 | val 1.48369
  Classification -> best τ=0.655 (val F1=0.2452)
  Directional -> Accuracy: 0.4727, MCC: 0.0585, F1: 0.1212

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.45792 | val 2.57589
  Epoch 011 - train 0.42207 | val 2.94342
  Classification -> best τ=0.775 (val F1=0.2649)
  Directional -> Accuracy: 0.5000, MCC: -0.0187, F1: 0.3333

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.65772 | val 0.93034
  Epoch 013 - train 0.56391 | val 1.10906
  Classification -> best τ=0.595 (val F1=0.1168)
  Directional -> Accuracy: 0.6038, MCC: 0.2068, F1: 0.6182

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.50898 | val 3.44608
  Epoch 011 - train 0.49807 | val 3.53302
  Classification -> best τ=0.595 (val F1=0.0361)
  Directional -> Accuracy: 0.5273, MCC: 0.0000, F1: 0.6905

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.60975 | val 0.81980

[I 2026-02-22 14:17:46,308] Trial 213 finished with value: 0.2690412954565083 and parameters: {'feature_set': 'sector', 'model_type': 'BiGRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.4, 'batch_size': 16, 'learning_rate': 0.007433518136497391, 'weight_decay': 6.884997879997121e-05, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 1.0187257865330122, 'early_stopping_min_delta': 0.0019395662803261904}. Best is trial 159 with value: 0.297766251520741.

  Epoch 012 - train 0.59650 | val 0.76846
  Classification -> best τ=0.485 (val F1=0.2439)
  Directional -> Accuracy: 0.5167, MCC: 0.0408, F1: 0.5538

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2690412954565083
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.65233 | val 1.19531
  Epoch 011 - train 0.60386 | val 1.04558
  Classification -> best τ=0.770 (val F1=0.2919)
  Directional -> Accuracy: 0.5658, MCC: 0.1283, F1: 0.0571

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.55729 | val 1.23330
  Epoch 012 - train 0.50180 | val 1.44599
  Classification -> best τ=0.565 (val F1=0.1941)
  Directional -> Accuracy: 0.6667, MCC: 0.2984, F1: 0.7458

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.59638 | val 1.61448
  Epoch 011 - train 0.50278 | val 1.68059
  Classification -> best τ=0.680 (val F1=0.3114)
  Directional -> Accuracy: 0.5217, MCC: 0.0948, F1: 0.3125

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.59994 | val 0.85945
  Epoch 017 - train 0.48747 | val 1.08485
  Classification -> best τ=0.505 (val F1=0.3506)
  Directional -> Accuracy: 0.5405, MCC: 0.0000, F1: 0.7018

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.56971 | val 0.94096
  Epoch 012 - train 0.47903 | val 1.03620
  Classification -> best τ=0.495 (val F1=0.4851)
  Directional -> Accuracy: 0.6000, MCC: 0.2300, F1: 0.5238

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.53167 | val 0.67750
  Epoch 020 - train 0.31201 | val 0.95670
  Classification -> best τ=0.720 (val F1=0.3525)
  Directional -> Accuracy: 0.5217, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.60502 | val 0.85507
  Epoch 015 - train 0.54708 | val 0.97578
  Classification -> best τ=0.780 (val F1=0.3409)
  Directional -> Accuracy: 0.6029, MCC: 0.0000, F1: 0.0000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.53126 | val 2.54103
  Epoch 011 - train 0.51527 | val 2.22624
  Classification -> best τ=0.460 (val F1=0.2657)
  Directional -> Accuracy: 0.4524, MCC: -0.1105, F1: 0.3784

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.60899 | val 1.42122
  Epoch 013 - train 0.49362 | val 1.61752
  Classification -> best τ=0.440 (val F1=0.3385)
  Directional -> Accuracy: 0.5625, MCC: 0.0976, F1: 0.4615

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.61696 | val 0.72116
  Epoch 011 - train 0.54651 | val 0.76265
  Classification -> best τ=0.540 (val F1=0.2725)
  Directional -> Accuracy: 0.4348, MCC: -0.0749, F1: 0.4935

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.58500 | val 0.95189
  Epoch 011 - train 0.54862 | val 0.99713
  Classification -> best τ=0.610 (val F1=0.4059)
  Directional -> Accuracy: 0.6122, MCC: 0.2379, F1: 0.2963

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.60670 | val 0.95527
  Epoch 011 - train 0.59868 | val 1.04612
  Classification -> best τ=0.475 (val F1=0.1613)
  Directional -> Accuracy: 0.6140, MCC: 0.2282, F1: 0.6452

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.48217 | val 0.97670
  Epoch 015 - train 0.38526 | val 1.36562
  Classification -> best τ=0.360 (val F1=0.2466)
  Directional -> Accuracy: 0.4762, MCC: -0.0302, F1: 0.5000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.63421 | val 0.74308
  Epoch 016 - train 0.51085 | val 0.75832
  Classification -> best τ=0.390 (val F1=0.4193)
  Directional -> Accuracy: 0.4833, MCC: -0.0603, F1: 0.1143

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.58527 | val 0.70390
  Epoch 014 - train 0.55365 | val 0.87826
  Classification -> best τ=0.520 (val F1=0.2008)
  Directional -> Accuracy: 0.6078, MCC: 0.2148, F1: 0.5833

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.58372 | val 1.99620
  Epoch 011 - train 0.59259 | val 1.72401
  Classification -> best τ=0.280 (val F1=0.3094)
  Directional -> Accuracy: 0.5362, MCC: 0.0367, F1: 0.6522

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.57818 | val 1.09820
  Epoch 015 - train 0.51731 | val 1.46995
  Classification -> best τ=0.425 (val F1=0.2877)
  Directional -> Accuracy: 0.3448, MCC: -0.2233, F1: 0.2400

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.60213 | val 1.14119
  Epoch 012 - train 0.53548 | val 1.32983
  Classification -> best τ=0.565 (val F1=0.2220)
  Directional -> Accuracy: 0.4000, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.62049 | val 0.79903
  Epoch 013 - train 0.52033 | val 0.96269
  Classification -> best τ=0.415 (val F1=0.2616)
  Directional -> Accuracy: 0.4688, MCC: -0.0584, F1: 0.5000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.48337 | val 1.33063
  Epoch 011 - train 0.53593 | val 1.26438
  Classification -> best τ=0.565 (val F1=0.2357)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.58282 | val 1.17260
  Epoch 012 - train 0.46368 | val 1.57597
  Classification -> best τ=0.195 (val F1=0.2784)
  Directional -> Accuracy: 0.5319, MCC: 0.2287, F1: 0.4500

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.59268 | val 1.77978
  Epoch 011 - train 0.55982 | val 1.61491
  Classification -> best τ=0.495 (val F1=0.2221)
  Directional -> Accuracy: 0.5077, MCC: 0.0000, F1: 0.6735

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.60131 | val 0.63433
  Epoch 019 - train 0.43272 | val 0.85747
  Classification -> best τ=0.515 (val F1=0.4032)
  Directional -> Accuracy: 0.6842, MCC: 0.3510, F1: 0.7353

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.64795 | val 0.82859
  Epoch 015 - train 0.51578 | val 0.96642
  Classification -> best τ=0.420 (val F1=0.2073)
  Directional -> Accuracy: 0.4923, MCC: 0.0075, F1: 0.5823

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.58500 | val 0.90030
  Epoch 014 - train 0.48170 | val 1.41322
  Classification -> best τ=0.485 (val F1=0.5299)
  Directional -> Accuracy: 0.4545, MCC: -0.0533, F1: 0.3182

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.50360 | val 1.94239
  Epoch 011 - train 0.42468 | val 2.23760
  Classification -> best τ=0.695 (val F1=0.4009)
  Directional -> Accuracy: 0.4222, MCC: -0.0732, F1: 0.5357

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.59843 | val 0.83599
  Epoch 015 - train 0.51087 | val 0.78404
  Classification -> best τ=0.590 (val F1=0.2810)
  Directional -> Accuracy: 0.5238, MCC: 0.1217, F1: 0.4444

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.57745 | val 0.94744
  Epoch 011 - train 0.48963 | val 1.14522
  Classification -> best τ=0.375 (val F1=0.3430)
  Directional -> Accuracy: 0.4464, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.46605 | val 0.79715
  Epoch 012 - train 0.47101 | val 1.01402
  Classification -> best τ=0.530 (val F1=0.2686)
  Directional -> Accuracy: 0.5500, MCC: 0.0422, F1: 0.6786

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.55914 | val 1.29659
  Epoch 011 - train 0.52863 | val 1.74102
  Classification -> best τ=0.615 (val F1=0.3501)
  Directional -> Accuracy: 0.4762, MCC: -0.0550, F1: 0.4211

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.55325 | val 0.95619
  Epoch 012 - train 0.46932 | val 0.95202
  Classification -> best τ=0.355 (val F1=0.3039)
  Directional -> Accuracy: 0.5000, MCC: -0.1319, F1: 0.6557

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.57339 | val 0.77861
  Epoch 011 - train 0.49419 | val 0.99689
  Classification -> best τ=0.545 (val F1=0.3718)
  Directional -> Accuracy: 0.4490, MCC: -0.1155, F1: 0.5091

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.62441 | val 0.71429
  Epoch 012 - train 0.52148 | val 0.77400
  Classification -> best τ=0.430 (val F1=0.3495)
  Directional -> Accuracy: 0.5139, MCC: 0.1147, F1: 0.3636

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.53463 | val 1.17581
  Epoch 011 - train 0.47883 | val 1.49051
  Classification -> best τ=0.400 (val F1=0.1539)
  Directional -> Accuracy: 0.4651, MCC: -0.0831, F1: 0.3429

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.55668 | val 1.42850
  Epoch 011 - train 0.58186 | val 1.48418
  Classification -> best τ=0.385 (val F1=0.1203)
  Directional -> Accuracy: 0.5758, MCC: 0.0000, F1: 0.7308

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.46913 | val 2.31417
  Epoch 011 - train 0.39913 | val 2.53571
  Classification -> best τ=0.605 (val F1=0.2618)
  Directional -> Accuracy: 0.5952, MCC: 0.2656, F1: 0.4516

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.58044 | val 1.74329
  Epoch 012 - train 0.48261 | val 1.49215
  Classification -> best τ=0.560 (val F1=0.2478)
  Directional -> Accuracy: 0.5893, MCC: 0.1776, F1: 0.3429

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.49374 | val 1.32118
  Epoch 011 - train 0.41888 | val 1.42496
  Classification -> best τ=0.580 (val F1=0.3294)
  Directional -> Accuracy: 0.5217, MCC: -0.0040, F1: 0.6071

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.52427 | val 0.83398
  Epoch 014 - train 0.54431 | val 0.84203
  Classification -> best τ=0.240 (val F1=0.4201)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.55064 | val 1.55600
  Epoch 011 - train 0.49865 | val 2.34175
  Classification -> best τ=0.550 (val F1=0.2001)
  Directional -> Accuracy: 0.5135, MCC: 0.0045, F1: 0.0526

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.58651 | val 0.71780
  Epoch 012 - train 0.56086 | val 0.72936
  Classification -> best τ=0.465 (val F1=0.3873)
  Directional -> Accuracy: 0.5111, MCC: 0.0000, F1: 0.6765

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.49421 | val 3.22413
  Epoch 012 - train 0.37573 | val 2.73694
  Classification -> best τ=0.510 (val F1=0.3948)
  Directional -> Accuracy: 0.5476, MCC: 0.0962, F1: 0.5778

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.49092 | val 0.91682
  Epoch 015 - train 0.40289 | val 0.78231
  Classification -> best τ=0.490 (val F1=0.4682)
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.5455

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.63597 | val 1.33557
  Epoch 012 - train 0.62865 | val 1.41504
  Classification -> best τ=0.545 (val F1=0.1647)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.40922 | val 1.84134
  Epoch 011 - train 0.50450 | val 1.83180
  Classification -> best τ=0.640 (val F1=0.3164)
  Directional -> Accuracy: 0.5179, MCC: 0.0357, F1: 0.5091

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.64740 | val 0.75573
  Epoch 015 - train 0.55417 | val 0.73042
  Classification -> best τ=0.545 (val F1=0.3242)
  Directional -> Accuracy: 0.5472, MCC: 0.1483, F1: 0.6842

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.52480 | val 2.88481
  Epoch 011 - train 0.50414 | val 3.14814
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5273, MCC: 0.0000, F1: 0.6905

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.64559 | val 0.79412

[I 2026-02-22 14:20:33,662] Trial 214 finished with value: 0.2991200218486954 and parameters: {'feature_set': 'sector', 'model_type': 'BiGRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.4, 'batch_size': 16, 'learning_rate': 0.007906454662673626, 'weight_decay': 4.312524321224732e-05, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 1.0723941332915894, 'early_stopping_min_delta': 0.0015526383943650396}. Best is trial 214 with value: 0.2991200218486954.

  Epoch 016 - train 0.48471 | val 1.11826
  Classification -> best τ=0.595 (val F1=0.3056)
  Directional -> Accuracy: 0.5167, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2991200218486954
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.61634 | val 1.02704
  Epoch 011 - train 0.59801 | val 1.11021
  Classification -> best τ=0.620 (val F1=0.2919)
  Directional -> Accuracy: 0.5395, MCC: -0.1039, F1: 0.0000

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.54336 | val 1.04828
  Epoch 011 - train 0.55260 | val 1.10878
  Classification -> best τ=0.670 (val F1=0.1941)
  Directional -> Accuracy: 0.6444, MCC: 0.2466, F1: 0.7333

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.53905 | val 1.89732
  Epoch 011 - train 0.59550 | val 1.63076
  Classification -> best τ=0.755 (val F1=0.3114)
  Directional -> Accuracy: 0.5435, MCC: 0.1633, F1: 0.3226

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.63375 | val 1.09120
  Epoch 020 - train 0.48649 | val 1.26306
  Epoch 022 - train 0.46754 | val 0.69379
  Classification -> best τ=0.340 (val F1=0.2593)
  Directional -> Accuracy: 0.5405, MCC: 0.0000, F1: 0.7018

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.51871 | val 1.89473
  Epoch 011 - train 0.48486 | val 2.67552
  Classification -> best τ=0.455 (val F1=0.3641)
  Directional -> Accuracy: 0.6600, MCC: 0.3398, F1: 0.6222

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.55562 | val 0.76672
  Epoch 011 - train 0.48791 | val 0.77926
  Classification -> best τ=0.615 (val F1=0.2739)
  Directional -> Accuracy: 0.5217, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.62090 | val 0.73298
  Epoch 020 - train 0.48542 | val 1.27496
  Classification -> best τ=0.190 (val F1=0.3531)
  Directional -> Accuracy: 0.4706, MCC: 0.0521, F1: 0.5385

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.57713 | val 0.59738
  Epoch 014 - train 0.47949 | val 0.85518
  Classification -> best τ=0.270 (val F1=0.2810)
  Directional -> Accuracy: 0.4524, MCC: -0.0168, F1: 0.5490

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.56888 | val 1.51529
  Epoch 011 - train 0.55041 | val 1.70392
  Classification -> best τ=0.655 (val F1=0.2764)
  Directional -> Accuracy: 0.5417, MCC: 0.0067, F1: 0.2667

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.58916 | val 0.79287
  Epoch 012 - train 0.54167 | val 0.81418
  Classification -> best τ=0.690 (val F1=0.1607)
  Directional -> Accuracy: 0.5217, MCC: -0.0054, F1: 0.3774

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.60023 | val 0.68318
  Epoch 020 - train 0.50344 | val 0.77603
  Epoch 026 - train 0.44370 | val 0.87895
  Classification -> best τ=0.470 (val F1=0.4059)
  Directional -> Accuracy: 0.6122, MCC: 0.2379, F1: 0.2963

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.55904 | val 1.10267
  Epoch 011 - train 0.54539 | val 1.45756
  Classification -> best τ=0.510 (val F1=0.1843)
  Directional -> Accuracy: 0.6316, MCC: 0.3198, F1: 0.7200

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.50319 | val 1.08628
  Epoch 011 - train 0.49823 | val 1.24016
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.6230

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.59578 | val 0.68693
  Epoch 013 - train 0.54002 | val 0.78192
  Classification -> best τ=0.215 (val F1=0.3083)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6429

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.56868 | val 1.37742
  Epoch 011 - train 0.50421 | val 1.36088
  Classification -> best τ=0.580 (val F1=0.3469)
  Directional -> Accuracy: 0.5490, MCC: 0.1177, F1: 0.5660

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.57791 | val 1.38396
  Epoch 011 - train 0.52093 | val 1.71346
  Classification -> best τ=0.385 (val F1=0.2659)
  Directional -> Accuracy: 0.5507, MCC: 0.0764, F1: 0.6931

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.66505 | val 1.07704
  Epoch 011 - train 0.58281 | val 1.07624
  Classification -> best τ=0.370 (val F1=0.1533)
  Directional -> Accuracy: 0.6552, MCC: 0.3682, F1: 0.6667

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.58173 | val 1.08957
  Epoch 013 - train 0.48409 | val 1.39959
  Classification -> best τ=0.480 (val F1=0.1548)
  Directional -> Accuracy: 0.4000, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.59979 | val 0.91522
  Epoch 012 - train 0.53033 | val 1.21461
  Classification -> best τ=0.200 (val F1=0.2428)
  Directional -> Accuracy: 0.5625, MCC: -0.1076, F1: 0.7200

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.54212 | val 1.23322
  Epoch 011 - train 0.47917 | val 1.26004
  Classification -> best τ=0.445 (val F1=0.2403)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.51102 | val 1.40652
  Epoch 012 - train 0.47219 | val 1.56592
  Classification -> best τ=0.435 (val F1=0.3308)
  Directional -> Accuracy: 0.4894, MCC: 0.2066, F1: 0.3333

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.56277 | val 1.39855
  Epoch 012 - train 0.58142 | val 1.18432
  Classification -> best τ=0.535 (val F1=0.2874)
  Directional -> Accuracy: 0.5846, MCC: 0.2055, F1: 0.4490

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.63711 | val 0.68258
  Epoch 013 - train 0.54940 | val 0.69534
  Classification -> best τ=0.620 (val F1=0.3833)
  Directional -> Accuracy: 0.5088, MCC: 0.0937, F1: 0.3913

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.60035 | val 0.98146
  Epoch 013 - train 0.52408 | val 2.44119
  Classification -> best τ=0.390 (val F1=0.2298)
  Directional -> Accuracy: 0.5077, MCC: 0.0451, F1: 0.6000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.55413 | val 1.18141
  Epoch 011 - train 0.50556 | val 1.17471
  Classification -> best τ=0.560 (val F1=0.4947)
  Directional -> Accuracy: 0.5636, MCC: 0.2170, F1: 0.4286

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.46188 | val 3.68375
  Epoch 011 - train 0.52233 | val 3.81442
  Classification -> best τ=0.760 (val F1=0.1890)
  Directional -> Accuracy: 0.5556, MCC: -0.1289, F1: 0.0000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.58489 | val 1.41184
  Epoch 011 - train 0.56616 | val 1.42149
  Classification -> best τ=0.525 (val F1=0.1021)
  Directional -> Accuracy: 0.5238, MCC: 0.0694, F1: 0.5238

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.56513 | val 1.17767
  Epoch 011 - train 0.47373 | val 1.48664
  Classification -> best τ=0.610 (val F1=0.2850)
  Directional -> Accuracy: 0.4464, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.54238 | val 1.59626
  Epoch 011 - train 0.59025 | val 1.58152
  Classification -> best τ=0.615 (val F1=0.4114)
  Directional -> Accuracy: 0.4750, MCC: 0.0668, F1: 0.1600

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.62369 | val 1.13372
  Epoch 015 - train 0.54831 | val 1.44956
  Classification -> best τ=0.505 (val F1=0.1413)
  Directional -> Accuracy: 0.5476, MCC: 0.0912, F1: 0.5128

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.60322 | val 0.97932
  Epoch 012 - train 0.52639 | val 1.06563
  Classification -> best τ=0.490 (val F1=0.2879)
  Directional -> Accuracy: 0.6190, MCC: 0.3238, F1: 0.5294

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.50218 | val 1.27739
  Epoch 012 - train 0.44167 | val 1.11488
  Classification -> best τ=0.600 (val F1=0.3465)
  Directional -> Accuracy: 0.5102, MCC: -0.0469, F1: 0.6571

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.62203 | val 0.72686
  Epoch 018 - train 0.47283 | val 1.08713
  Classification -> best τ=0.335 (val F1=0.3548)
  Directional -> Accuracy: 0.5833, MCC: 0.1291, F1: 0.6809

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.56587 | val 0.93906
  Epoch 011 - train 0.47641 | val 0.96498
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.58187 | val 1.63611
  Epoch 011 - train 0.56324 | val 2.10802
  Classification -> best τ=0.450 (val F1=0.1259)
  Directional -> Accuracy: 0.5758, MCC: 0.0000, F1: 0.7308

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.56727 | val 0.89795
  Epoch 012 - train 0.41858 | val 1.14545
  Classification -> best τ=0.520 (val F1=0.2839)
  Directional -> Accuracy: 0.4762, MCC: -0.0155, F1: 0.1538

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.55613 | val 0.76533
  Epoch 011 - train 0.54474 | val 0.86599
  Classification -> best τ=0.495 (val F1=0.2816)
  Directional -> Accuracy: 0.5536, MCC: 0.0862, F1: 0.4186

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.46061 | val 0.97180
  Epoch 011 - train 0.37528 | val 1.04363
  Classification -> best τ=0.310 (val F1=0.2118)
  Directional -> Accuracy: 0.6087, MCC: 0.0000, F1: 0.7568

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.48009 | val 0.83843
  Epoch 012 - train 0.51339 | val 0.76332
  Classification -> best τ=0.550 (val F1=0.4011)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.54047 | val 1.24671
  Epoch 011 - train 0.52436 | val 1.37570
  Classification -> best τ=0.615 (val F1=0.1622)
  Directional -> Accuracy: 0.4595, MCC: -0.1647, F1: 0.0909

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.61030 | val 0.68419
  Epoch 015 - train 0.51136 | val 0.78581
  Classification -> best τ=0.485 (val F1=0.3287)
  Directional -> Accuracy: 0.6000, MCC: 0.2020, F1: 0.5909

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.45901 | val 2.99292
  Epoch 011 - train 0.41395 | val 3.26614
  Classification -> best τ=0.615 (val F1=0.2500)
  Directional -> Accuracy: 0.4762, MCC: -0.0278, F1: 0.4762

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.49277 | val 1.27556
  Epoch 012 - train 0.47145 | val 1.30089
  Classification -> best τ=0.630 (val F1=0.2450)
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.5455

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.60625 | val 1.73507
  Epoch 011 - train 0.58060 | val 2.00317
  Classification -> best τ=0.465 (val F1=0.2036)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.51030 | val 1.67357
  Epoch 011 - train 0.40138 | val 2.21865
  Classification -> best τ=0.515 (val F1=0.1995)
  Directional -> Accuracy: 0.5357, MCC: 0.0625, F1: 0.4091

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.62183 | val 0.96488
  Epoch 013 - train 0.56677 | val 0.83495
  Classification -> best τ=0.545 (val F1=0.2769)
  Directional -> Accuracy: 0.6038, MCC: 0.2109, F1: 0.6557

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.55592 | val 2.74851
  Epoch 011 - train 0.49799 | val 2.91097
  Classification -> best τ=0.685 (val F1=0.0413)
  Directional -> Accuracy: 0.5273, MCC: 0.0000, F1: 0.6905

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.57779 | val 0.71526

[I 2026-02-22 14:23:10,833] Trial 215 finished with value: 0.25449412797592236 and parameters: {'feature_set': 'sector', 'model_type': 'BiGRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.4, 'batch_size': 16, 'learning_rate': 0.00717203944455281, 'weight_decay': 8.907953556676397e-05, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 1.0857144814073394, 'early_stopping_min_delta': 0.002062370959051467}. Best is trial 214 with value: 0.2991200218486954.

  Epoch 012 - train 0.58414 | val 0.67398
  Classification -> best τ=0.495 (val F1=0.2920)
  Directional -> Accuracy: 0.5167, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.25449412797592236
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.63685 | val 1.03460
  Epoch 019 - train 0.55459 | val 1.33710
  Classification -> best τ=0.930 (val F1=0.2510)
  Directional -> Accuracy: 0.5526, MCC: 0.0000, F1: 0.0000

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.58070 | val 1.31181
  Epoch 012 - train 0.48644 | val 1.07239
  Classification -> best τ=0.630 (val F1=0.1941)
  Directional -> Accuracy: 0.6444, MCC: 0.2538, F1: 0.7500

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.53347 | val 2.27982
  Epoch 011 - train 0.47716 | val 2.17705
  Classification -> best τ=0.690 (val F1=0.2311)
  Directional -> Accuracy: 0.4783, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.61919 | val 0.73584
  Epoch 018 - train 0.47049 | val 1.25576
  Classification -> best τ=0.310 (val F1=0.2920)
  Directional -> Accuracy: 0.5405, MCC: 0.0194, F1: 0.6909

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.54395 | val 1.34809
  Epoch 011 - train 0.49451 | val 1.34436
  Classification -> best τ=0.565 (val F1=0.3945)
  Directional -> Accuracy: 0.7000, MCC: 0.4003, F1: 0.7059

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.54582 | val 0.70256
  Epoch 020 - train 0.52398 | val 0.95251
  Epoch 021 - train 0.35247 | val 0.81010
  Classification -> best τ=0.385 (val F1=0.4575)
  Directional -> Accuracy: 0.5217, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.62290 | val 1.05102
  Epoch 012 - train 0.57371 | val 0.77980
  Classification -> best τ=0.550 (val F1=0.2140)
  Directional -> Accuracy: 0.5147, MCC: 0.0177, F1: 0.4407

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.55815 | val 0.80970
  Epoch 017 - train 0.40646 | val 1.00913
  Classification -> best τ=0.165 (val F1=0.2677)
  Directional -> Accuracy: 0.4286, MCC: -0.0913, F1: 0.5000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.52024 | val 2.81467
  Epoch 011 - train 0.55993 | val 2.91874
  Classification -> best τ=0.695 (val F1=0.2764)
  Directional -> Accuracy: 0.6042, MCC: 0.1680, F1: 0.3871

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.56020 | val 0.81426
  Epoch 017 - train 0.44986 | val 1.11334
  Classification -> best τ=0.520 (val F1=0.3041)
  Directional -> Accuracy: 0.4783, MCC: -0.0044, F1: 0.5000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.64728 | val 0.72891
  Epoch 014 - train 0.55480 | val 1.24692
  Classification -> best τ=0.540 (val F1=0.3493)
  Directional -> Accuracy: 0.5918, MCC: 0.1804, F1: 0.2308

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.60391 | val 1.04682
  Epoch 014 - train 0.55083 | val 1.53022
  Classification -> best τ=0.400 (val F1=0.2667)
  Directional -> Accuracy: 0.5439, MCC: 0.1204, F1: 0.6750

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.47992 | val 1.95647
  Epoch 011 - train 0.45676 | val 1.81533
  Classification -> best τ=0.600 (val F1=0.2193)
  Directional -> Accuracy: 0.4286, MCC: -0.1718, F1: 0.6000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.59997 | val 0.68596
  Epoch 012 - train 0.53787 | val 0.65970
  Classification -> best τ=0.305 (val F1=0.2965)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.4643

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.57174 | val 0.77235
  Epoch 011 - train 0.48664 | val 0.79744
  Classification -> best τ=0.520 (val F1=0.2571)
  Directional -> Accuracy: 0.5490, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.58216 | val 1.09672
  Epoch 011 - train 0.53502 | val 1.66967
  Classification -> best τ=0.625 (val F1=0.3105)
  Directional -> Accuracy: 0.5072, MCC: 0.1200, F1: 0.2273

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.57100 | val 1.05093
  Epoch 012 - train 0.55213 | val 1.12920
  Classification -> best τ=0.580 (val F1=0.1697)
  Directional -> Accuracy: 0.3793, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.62721 | val 1.08672
  Epoch 014 - train 0.50277 | val 1.01448
  Classification -> best τ=0.500 (val F1=0.2477)
  Directional -> Accuracy: 0.4800, MCC: 0.0615, F1: 0.4000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.57054 | val 1.09596
  Epoch 012 - train 0.50813 | val 0.97825
  Classification -> best τ=0.290 (val F1=0.2843)
  Directional -> Accuracy: 0.4844, MCC: -0.1279, F1: 0.6118

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.54814 | val 1.03764
  Epoch 011 - train 0.52798 | val 1.12507
  Classification -> best τ=0.165 (val F1=0.2482)
  Directional -> Accuracy: 0.5541, MCC: 0.0000, F1: 0.7130

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.57380 | val 0.96813
  Epoch 014 - train 0.47843 | val 0.99041
  Classification -> best τ=0.535 (val F1=0.1906)
  Directional -> Accuracy: 0.5745, MCC: -0.0834, F1: 0.7222

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.54370 | val 1.75502
  Epoch 012 - train 0.55016 | val 1.75773
  Classification -> best τ=0.485 (val F1=0.3236)
  Directional -> Accuracy: 0.6000, MCC: 0.2010, F1: 0.6389

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.64852 | val 0.64145
  Epoch 020 - train 0.51421 | val 0.95512
  Epoch 022 - train 0.46060 | val 0.96707
  Classification -> best τ=0.445 (val F1=0.4634)
  Directional -> Accuracy: 0.5614, MCC: 0.0981, F1: 0.6269

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.60867 | val 0.83283
  Epoch 014 - train 0.49783 | val 0.84910
  Classification -> best τ=0.450 (val F1=0.1778)
  Directional -> Accuracy: 0.5077, MCC: 0.0402, F1: 0.5897

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.57094 | val 0.73088
  Epoch 016 - train 0.45695 | val 1.20805
  Classification -> best τ=0.370 (val F1=0.5197)
  Directional -> Accuracy: 0.5455, MCC: 0.0745, F1: 0.6032

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.38584 | val 3.09230
  Epoch 011 - train 0.45550 | val 3.01106
  Classification -> best τ=0.590 (val F1=0.2035)
  Directional -> Accuracy: 0.4444, MCC: 0.0481, F1: 0.5902

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.59025 | val 0.76381
  Epoch 019 - train 0.42742 | val 0.78200
  Classification -> best τ=0.620 (val F1=0.3873)
  Directional -> Accuracy: 0.5000, MCC: 0.0782, F1: 0.4000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.52184 | val 1.39397
  Epoch 013 - train 0.48848 | val 1.51443
  Classification -> best τ=0.145 (val F1=0.2870)
  Directional -> Accuracy: 0.4643, MCC: 0.1211, F1: 0.0625

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.58106 | val 0.79944
  Epoch 015 - train 0.40871 | val 1.19791
  Classification -> best τ=0.390 (val F1=0.3278)
  Directional -> Accuracy: 0.5750, MCC: 0.1240, F1: 0.7119

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.61303 | val 0.68797
  Epoch 012 - train 0.53255 | val 0.68547
  Classification -> best τ=0.405 (val F1=0.3501)
  Directional -> Accuracy: 0.5000, MCC: 0.0046, F1: 0.5116

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.56002 | val 0.94370
  Epoch 015 - train 0.55436 | val 0.90290
  Classification -> best τ=0.315 (val F1=0.2357)
  Directional -> Accuracy: 0.6667, MCC: 0.3349, F1: 0.6818

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.47715 | val 0.86758
  Epoch 011 - train 0.48086 | val 0.92330
  Classification -> best τ=0.495 (val F1=0.2328)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.60943 | val 0.76335
  Epoch 015 - train 0.49876 | val 0.90289
  Classification -> best τ=0.455 (val F1=0.3287)
  Directional -> Accuracy: 0.4861, MCC: 0.0205, F1: 0.3934

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.54620 | val 1.73258
  Epoch 012 - train 0.47117 | val 1.38664
  Classification -> best τ=0.470 (val F1=0.0197)
  Directional -> Accuracy: 0.4651, MCC: -0.0664, F1: 0.5106

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.57909 | val 0.82209
  Epoch 018 - train 0.47385 | val 1.43012
  Classification -> best τ=0.405 (val F1=0.3855)
  Directional -> Accuracy: 0.5758, MCC: 0.0648, F1: 0.7021

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.60789 | val 1.28385
  Epoch 014 - train 0.57085 | val 1.08475
  Classification -> best τ=0.580 (val F1=0.3260)
  Directional -> Accuracy: 0.5000, MCC: 0.0561, F1: 0.2222

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.57730 | val 0.85929
  Epoch 011 - train 0.51096 | val 1.06694
  Classification -> best τ=0.610 (val F1=0.2382)
  Directional -> Accuracy: 0.5357, MCC: 0.0576, F1: 0.4583

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.46027 | val 1.34201
  Epoch 012 - train 0.44947 | val 1.37053
  Classification -> best τ=0.620 (val F1=0.3225)
  Directional -> Accuracy: 0.4130, MCC: -0.0324, F1: 0.2286

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.57045 | val 0.91313
  Epoch 019 - train 0.43860 | val 1.02475
  Classification -> best τ=0.690 (val F1=0.4710)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.56711 | val 2.20531
  Epoch 011 - train 0.46042 | val 2.80884
  Classification -> best τ=0.300 (val F1=0.3244)
  Directional -> Accuracy: 0.4865, MCC: -0.0515, F1: 0.2692

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.63147 | val 0.76656
  Epoch 014 - train 0.48842 | val 1.41063
  Classification -> best τ=0.465 (val F1=0.3371)
  Directional -> Accuracy: 0.4889, MCC: 0.0000, F1: 0.0000

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.39601 | val 1.55102
  Epoch 012 - train 0.31150 | val 1.92713
  Classification -> best τ=0.785 (val F1=0.2500)
  Directional -> Accuracy: 0.4524, MCC: 0.0212, F1: 0.2069

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.63701 | val 0.58384
  Epoch 020 - train 0.52461 | val 0.87700
  Epoch 027 - train 0.22308 | val 1.28302
  Classification -> best τ=0.480 (val F1=0.6290)
  Directional -> Accuracy: 0.5208, MCC: 0.2176, F1: 0.5818

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.67238 | val 1.23767
  Epoch 012 - train 0.62822 | val 1.61069
  Classification -> best τ=0.655 (val F1=0.2036)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.48786 | val 1.98167
  Epoch 011 - train 0.44185 | val 1.89439
  Classification -> best τ=0.640 (val F1=0.4275)
  Directional -> Accuracy: 0.4821, MCC: -0.0684, F1: 0.2564

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.63470 | val 0.71287
  Epoch 014 - train 0.60488 | val 0.83478
  Classification -> best τ=0.500 (val F1=0.1813)
  Directional -> Accuracy: 0.5849, MCC: 0.1688, F1: 0.6071

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.61704 | val 1.78071
  Epoch 012 - train 0.51439 | val 3.34609
  Classification -> best τ=0.715 (val F1=0.2283)
  Directional -> Accuracy: 0.5455, MCC: 0.0988, F1: 0.5283

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.61890 | val 0.96657

[I 2026-02-22 14:26:06,244] Trial 216 finished with value: 0.29694479872387985 and parameters: {'feature_set': 'sector', 'model_type': 'BiGRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.4, 'batch_size': 16, 'learning_rate': 0.008335523339304492, 'weight_decay': 3.7802173830999205e-05, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 1.0652897974459539, 'early_stopping_min_delta': 0.001102123347518915}. Best is trial 214 with value: 0.2991200218486954.

  Epoch 012 - train 0.58064 | val 0.92478
  Classification -> best τ=0.400 (val F1=0.3495)
  Directional -> Accuracy: 0.5667, MCC: 0.1451, F1: 0.3500

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.29694479872387985
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.62863 | val 1.42860
  Epoch 013 - train 0.59190 | val 2.39728
  Classification -> best τ=0.770 (val F1=0.2510)
  Directional -> Accuracy: 0.5526, MCC: 0.0000, F1: 0.0000

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.50804 | val 1.42871
  Epoch 011 - train 0.51302 | val 1.65934
  Classification -> best τ=0.725 (val F1=0.2523)
  Directional -> Accuracy: 0.6000, MCC: 0.1802, F1: 0.6538

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.55613 | val 1.69466
  Epoch 011 - train 0.52392 | val 1.82980
  Classification -> best τ=0.685 (val F1=0.3005)
  Directional -> Accuracy: 0.5217, MCC: 0.2041, F1: 0.1538

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.58438 | val 1.11572
  Epoch 011 - train 0.54886 | val 1.22571
  Classification -> best τ=0.490 (val F1=0.1269)
  Directional -> Accuracy: 0.5405, MCC: 0.0000, F1: 0.7018

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.50999 | val 1.20721
  Epoch 012 - train 0.47839 | val 1.41112
  Classification -> best τ=0.710 (val F1=0.3933)
  Directional -> Accuracy: 0.5000, MCC: 0.1373, F1: 0.0741

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.53065 | val 0.73352
  Epoch 012 - train 0.44660 | val 0.83881
  Classification -> best τ=0.640 (val F1=0.2739)
  Directional -> Accuracy: 0.5217, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.56831 | val 0.78209
  Epoch 011 - train 0.58762 | val 0.84596
  Classification -> best τ=0.435 (val F1=0.2301)
  Directional -> Accuracy: 0.3971, MCC: -0.0974, F1: 0.5060

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.51839 | val 1.06087
  Epoch 017 - train 0.42297 | val 0.94603
  Classification -> best τ=0.425 (val F1=0.3632)
  Directional -> Accuracy: 0.5000, MCC: 0.0138, F1: 0.4878

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.52264 | val 2.50462
  Epoch 013 - train 0.45898 | val 2.43933
  Classification -> best τ=0.700 (val F1=0.2822)
  Directional -> Accuracy: 0.6667, MCC: 0.3310, F1: 0.6364

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.55208 | val 0.97331
  Epoch 011 - train 0.49339 | val 0.90503
  Classification -> best τ=0.370 (val F1=0.2293)
  Directional -> Accuracy: 0.4348, MCC: -0.0403, F1: 0.5412

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.61429 | val 1.11070
  Epoch 013 - train 0.59185 | val 1.00200
  Classification -> best τ=0.475 (val F1=0.2484)
  Directional -> Accuracy: 0.5306, MCC: 0.0236, F1: 0.3784

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.56194 | val 1.17137
  Epoch 012 - train 0.51271 | val 1.32588
  Classification -> best τ=0.540 (val F1=0.2630)
  Directional -> Accuracy: 0.5614, MCC: 0.1520, F1: 0.6753

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.53418 | val 1.43553
  Epoch 011 - train 0.41831 | val 2.00236
  Classification -> best τ=0.505 (val F1=0.1225)
  Directional -> Accuracy: 0.4286, MCC: -0.1783, F1: 0.2941

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.62435 | val 0.63168
  Epoch 020 - train 0.53407 | val 0.72120
  Epoch 023 - train 0.44461 | val 0.87767
  Classification -> best τ=0.380 (val F1=0.3833)
  Directional -> Accuracy: 0.5167, MCC: 0.0405, F1: 0.3256

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.62726 | val 0.88005
  Epoch 013 - train 0.51955 | val 0.90972
  Classification -> best τ=0.545 (val F1=0.2571)
  Directional -> Accuracy: 0.5686, MCC: 0.0996, F1: 0.3529

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.61291 | val 1.15347
  Epoch 011 - train 0.53798 | val 1.42955
  Classification -> best τ=0.510 (val F1=0.1423)
  Directional -> Accuracy: 0.4783, MCC: -0.0690, F1: 0.5610

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.56664 | val 1.07089
  Epoch 011 - train 0.56166 | val 0.99887
  Classification -> best τ=0.465 (val F1=0.0866)
  Directional -> Accuracy: 0.4655, MCC: -0.0711, F1: 0.5231

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.62032 | val 0.76210
  Epoch 012 - train 0.54272 | val 0.88740
  Classification -> best τ=0.665 (val F1=0.2220)
  Directional -> Accuracy: 0.4000, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.56426 | val 0.95054
  Epoch 011 - train 0.55401 | val 0.96706
  Classification -> best τ=0.525 (val F1=0.2668)
  Directional -> Accuracy: 0.5000, MCC: 0.1376, F1: 0.3333

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.52460 | val 1.40329
  Epoch 011 - train 0.49236 | val 1.68611
  Classification -> best τ=0.420 (val F1=0.2403)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.60519 | val 1.29269
  Epoch 014 - train 0.42876 | val 0.76179
  Classification -> best τ=0.480 (val F1=0.2295)
  Directional -> Accuracy: 0.6170, MCC: 0.0508, F1: 0.7568

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.60475 | val 1.62308
  Epoch 011 - train 0.56489 | val 1.67387
  Classification -> best τ=0.515 (val F1=0.1925)
  Directional -> Accuracy: 0.4923, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.63662 | val 1.32655
  Epoch 015 - train 0.52950 | val 1.27245
  Classification -> best τ=0.770 (val F1=0.3144)
  Directional -> Accuracy: 0.4912, MCC: 0.0739, F1: 0.3256

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.56848 | val 0.86280
  Epoch 011 - train 0.62640 | val 0.97998
  Classification -> best τ=0.665 (val F1=0.1985)
  Directional -> Accuracy: 0.5231, MCC: 0.0000, F1: 0.0000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.60962 | val 0.96838
  Epoch 012 - train 0.52729 | val 0.94747
  Classification -> best τ=0.390 (val F1=0.4199)
  Directional -> Accuracy: 0.5273, MCC: 0.0920, F1: 0.4583

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.42612 | val 2.45314
  Epoch 011 - train 0.48539 | val 3.38439
  Classification -> best τ=0.670 (val F1=0.1981)
  Directional -> Accuracy: 0.6444, MCC: 0.3119, F1: 0.6364

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.62863 | val 0.76968
  Epoch 012 - train 0.56530 | val 0.84290
  Classification -> best τ=0.560 (val F1=0.1936)
  Directional -> Accuracy: 0.4524, MCC: 0.1353, F1: 0.0800

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.54954 | val 1.71443
  Epoch 011 - train 0.48345 | val 1.88687
  Classification -> best τ=0.415 (val F1=0.3181)
  Directional -> Accuracy: 0.4464, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.59642 | val 0.91027
  Epoch 011 - train 0.54640 | val 1.07227
  Classification -> best τ=0.600 (val F1=0.4109)
  Directional -> Accuracy: 0.5750, MCC: 0.1240, F1: 0.7119

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.58874 | val 1.30767
  Epoch 012 - train 0.51535 | val 1.48576
  Classification -> best τ=0.510 (val F1=0.3501)
  Directional -> Accuracy: 0.4762, MCC: -0.0608, F1: 0.3889

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.61782 | val 1.97443
  Epoch 014 - train 0.49947 | val 1.54702
  Classification -> best τ=0.390 (val F1=0.2357)
  Directional -> Accuracy: 0.5714, MCC: 0.1718, F1: 0.7188

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.49174 | val 1.02737
  Epoch 011 - train 0.47210 | val 1.16972
  Classification -> best τ=0.365 (val F1=0.2932)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.64407 | val 0.69251
  Epoch 017 - train 0.44412 | val 1.05081
  Classification -> best τ=0.700 (val F1=0.3278)
  Directional -> Accuracy: 0.4583, MCC: 0.1061, F1: 0.0488

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.50491 | val 1.55486
  Epoch 011 - train 0.44270 | val 1.63730
  Classification -> best τ=0.405 (val F1=0.1874)
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.58180 | val 1.59141
  Epoch 011 - train 0.52545 | val 1.80076
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5758, MCC: 0.0000, F1: 0.7308

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.51790 | val 1.30375
  Epoch 011 - train 0.42958 | val 1.32295
  Classification -> best τ=0.500 (val F1=0.2409)
  Directional -> Accuracy: 0.6667, MCC: 0.3441, F1: 0.6500

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.56226 | val 0.83477
  Epoch 012 - train 0.45325 | val 1.06923
  Classification -> best τ=0.510 (val F1=0.2382)
  Directional -> Accuracy: 0.5536, MCC: 0.0891, F1: 0.4444

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.50234 | val 1.10528
  Epoch 011 - train 0.48001 | val 1.25928
  Classification -> best τ=0.545 (val F1=0.3367)
  Directional -> Accuracy: 0.5652, MCC: 0.0094, F1: 0.6875

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.66040 | val 0.92642
  Epoch 011 - train 0.55231 | val 0.80668
  Classification -> best τ=0.675 (val F1=0.4710)
  Directional -> Accuracy: 0.5000, MCC: 0.0650, F1: 0.4783

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.55493 | val 2.44844
  Epoch 011 - train 0.49420 | val 2.80661
  Classification -> best τ=0.685 (val F1=0.2620)
  Directional -> Accuracy: 0.4865, MCC: -0.0910, F1: 0.0952

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.56500 | val 0.92438
  Epoch 014 - train 0.53691 | val 1.15882
  Classification -> best τ=0.575 (val F1=0.5164)
  Directional -> Accuracy: 0.5333, MCC: 0.1059, F1: 0.3226

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.35503 | val 2.59131
  Epoch 012 - train 0.30153 | val 3.17393
  Classification -> best τ=0.545 (val F1=0.4588)
  Directional -> Accuracy: 0.6429, MCC: 0.2527, F1: 0.7170

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.54576 | val 1.01971
  Epoch 012 - train 0.39077 | val 1.09884
  Classification -> best τ=0.550 (val F1=0.3410)
  Directional -> Accuracy: 0.3542, MCC: -0.1883, F1: 0.5231

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.62459 | val 1.07223
  Epoch 012 - train 0.59806 | val 1.80173
  Classification -> best τ=0.605 (val F1=0.2036)
  Directional -> Accuracy: 0.4727, MCC: 0.1242, F1: 0.0645

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.49771 | val 2.51161
  Epoch 011 - train 0.40342 | val 2.93730
  Classification -> best τ=0.750 (val F1=0.3073)
  Directional -> Accuracy: 0.5000, MCC: -0.0013, F1: 0.4815

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.61841 | val 0.75008
  Epoch 011 - train 0.57197 | val 0.79270
  Classification -> best τ=0.605 (val F1=0.2064)
  Directional -> Accuracy: 0.5849, MCC: 0.1695, F1: 0.5926

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.52602 | val 3.58218
  Epoch 011 - train 0.51235 | val 3.37043
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5273, MCC: 0.0000, F1: 0.6905

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.59583 | val 0.93457

[I 2026-02-22 14:28:36,115] Trial 217 finished with value: 0.26356205755636813 and parameters: {'feature_set': 'sector', 'model_type': 'BiGRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.4, 'batch_size': 16, 'learning_rate': 0.006976042087237408, 'weight_decay': 3.997898822117188e-05, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 1.0673087522504903, 'early_stopping_min_delta': 0.0013197434490413071}. Best is trial 214 with value: 0.2991200218486954.

  Epoch 013 - train 0.56797 | val 0.82380
  Classification -> best τ=0.370 (val F1=0.2637)
  Directional -> Accuracy: 0.6333, MCC: 0.2800, F1: 0.5217

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.26356205755636813
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.68031 | val 1.24261
  Epoch 012 - train 0.60554 | val 1.56086
  Classification -> best τ=0.670 (val F1=0.2510)
  Directional -> Accuracy: 0.6447, MCC: 0.3068, F1: 0.4000

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.58453 | val 1.02140
  Epoch 011 - train 0.50625 | val 0.92719
  Classification -> best τ=0.410 (val F1=0.1591)
  Directional -> Accuracy: 0.5778, MCC: 0.0000, F1: 0.7324

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.56596 | val 1.05792
  Epoch 013 - train 0.58581 | val 2.33336
  Classification -> best τ=0.705 (val F1=0.1978)
  Directional -> Accuracy: 0.5000, MCC: 0.1427, F1: 0.0800

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.59028 | val 0.92694
  Epoch 011 - train 0.53289 | val 0.97984
  Classification -> best τ=0.640 (val F1=0.1593)
  Directional -> Accuracy: 0.5000, MCC: 0.1401, F1: 0.1778

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.54255 | val 1.34465
  Epoch 011 - train 0.51580 | val 1.34411
  Classification -> best τ=0.580 (val F1=0.4602)
  Directional -> Accuracy: 0.6800, MCC: 0.3677, F1: 0.6667

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.49786 | val 0.85358
  Epoch 012 - train 0.45766 | val 0.69501
  Classification -> best τ=0.535 (val F1=0.3963)
  Directional -> Accuracy: 0.5217, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.58572 | val 1.93236
  Epoch 012 - train 0.57610 | val 1.54472
  Classification -> best τ=0.470 (val F1=0.2878)
  Directional -> Accuracy: 0.5441, MCC: 0.0659, F1: 0.4561

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.51853 | val 0.65778
  Epoch 018 - train 0.34322 | val 0.89852
  Classification -> best τ=0.235 (val F1=0.3524)
  Directional -> Accuracy: 0.5238, MCC: 0.1217, F1: 0.5833

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.57003 | val 1.22419
  Epoch 011 - train 0.49801 | val 1.47163
  Classification -> best τ=0.685 (val F1=0.2764)
  Directional -> Accuracy: 0.5625, MCC: 0.0263, F1: 0.0870

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.54355 | val 0.83238
  Epoch 016 - train 0.46511 | val 0.95782
  Classification -> best τ=0.865 (val F1=0.1983)
  Directional -> Accuracy: 0.5072, MCC: -0.0017, F1: 0.4333

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.59365 | val 0.70591
  Epoch 016 - train 0.46923 | val 0.87089
  Classification -> best τ=0.435 (val F1=0.3961)
  Directional -> Accuracy: 0.5918, MCC: 0.1804, F1: 0.2308

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.57048 | val 1.33175
  Epoch 012 - train 0.50464 | val 2.00469
  Classification -> best τ=0.440 (val F1=0.2225)
  Directional -> Accuracy: 0.5088, MCC: 0.0033, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.47953 | val 1.30330
  Epoch 011 - train 0.40104 | val 1.14737
  Classification -> best τ=0.560 (val F1=0.2176)
  Directional -> Accuracy: 0.3810, MCC: -0.2353, F1: 0.5185

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.62850 | val 0.69141
  Epoch 012 - train 0.54304 | val 0.76386
  Classification -> best τ=0.240 (val F1=0.3558)
  Directional -> Accuracy: 0.4667, MCC: -0.1857, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.58658 | val 0.90156
  Epoch 015 - train 0.52115 | val 0.99488
  Classification -> best τ=0.690 (val F1=0.1455)
  Directional -> Accuracy: 0.5490, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.62486 | val 0.87102
  Epoch 012 - train 0.54404 | val 0.91898
  Classification -> best τ=0.555 (val F1=0.2799)
  Directional -> Accuracy: 0.5942, MCC: 0.1751, F1: 0.6585

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.60795 | val 0.85080
  Epoch 012 - train 0.54932 | val 0.94908
  Classification -> best τ=0.215 (val F1=0.2300)
  Directional -> Accuracy: 0.5517, MCC: -0.1066, F1: 0.6977

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.57813 | val 1.09710
  Epoch 011 - train 0.54181 | val 1.24421
  Classification -> best τ=0.425 (val F1=0.1890)
  Directional -> Accuracy: 0.4933, MCC: 0.2620, F1: 0.2692

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.63730 | val 0.99961
  Epoch 017 - train 0.50275 | val 0.94260
  Classification -> best τ=0.225 (val F1=0.2752)
  Directional -> Accuracy: 0.5781, MCC: 0.0913, F1: 0.6824

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.54473 | val 0.98797
  Epoch 011 - train 0.48413 | val 1.23587
  Classification -> best τ=0.550 (val F1=0.3008)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.52791 | val 1.01858
  Epoch 011 - train 0.53173 | val 1.01393
  Classification -> best τ=0.495 (val F1=0.1737)
  Directional -> Accuracy: 0.4894, MCC: 0.0465, F1: 0.4783

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.55956 | val 1.06065
  Epoch 011 - train 0.53938 | val 1.27690
  Classification -> best τ=0.535 (val F1=0.2183)
  Directional -> Accuracy: 0.4923, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.60816 | val 0.88370
  Epoch 013 - train 0.55124 | val 0.79254
  Classification -> best τ=0.535 (val F1=0.2981)
  Directional -> Accuracy: 0.4912, MCC: 0.1153, F1: 0.2564

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.61247 | val 0.75199
  Epoch 016 - train 0.51150 | val 0.85658
  Classification -> best τ=0.430 (val F1=0.2029)
  Directional -> Accuracy: 0.5077, MCC: -0.0042, F1: 0.3600

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.49271 | val 1.21815
  Epoch 011 - train 0.64604 | val 1.17405
  Classification -> best τ=0.540 (val F1=0.5009)
  Directional -> Accuracy: 0.5636, MCC: 0.1587, F1: 0.5200

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.48116 | val 2.93979
  Epoch 011 - train 0.49667 | val 2.97723
  Classification -> best τ=0.660 (val F1=0.1890)
  Directional -> Accuracy: 0.4222, MCC: -0.1540, F1: 0.3810

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.56447 | val 0.76263
  Epoch 012 - train 0.52242 | val 0.81787
  Classification -> best τ=0.465 (val F1=0.1803)
  Directional -> Accuracy: 0.5000, MCC: -0.0280, F1: 0.5714

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.50599 | val 1.25066
  Epoch 011 - train 0.48281 | val 1.46942
  Classification -> best τ=0.405 (val F1=0.2256)
  Directional -> Accuracy: 0.4464, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.62763 | val 1.42380
  Epoch 011 - train 0.46575 | val 1.15111
  Classification -> best τ=0.515 (val F1=0.2618)
  Directional -> Accuracy: 0.5500, MCC: 0.0000, F1: 0.7097

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.51612 | val 0.89038
  Epoch 013 - train 0.49512 | val 1.56017
  Classification -> best τ=0.345 (val F1=0.4146)
  Directional -> Accuracy: 0.4524, MCC: -0.0879, F1: 0.4889

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.58336 | val 1.99722
  Epoch 012 - train 0.58270 | val 1.32954
  Classification -> best τ=0.295 (val F1=0.1124)
  Directional -> Accuracy: 0.5476, MCC: 0.0000, F1: 0.7077

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.48405 | val 1.03640
  Epoch 011 - train 0.43790 | val 1.08689
  Classification -> best τ=0.325 (val F1=0.3433)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.59712 | val 0.77309
  Epoch 015 - train 0.50157 | val 0.87470
  Classification -> best τ=0.525 (val F1=0.3568)
  Directional -> Accuracy: 0.4444, MCC: 0.0000, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.57274 | val 0.77787
  Epoch 011 - train 0.49708 | val 0.83338
  Classification -> best τ=0.570 (val F1=0.3385)
  Directional -> Accuracy: 0.6279, MCC: 0.2686, F1: 0.5294

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.59522 | val 1.58609
  Epoch 012 - train 0.52808 | val 1.57802
  Classification -> best τ=0.195 (val F1=0.3603)
  Directional -> Accuracy: 0.5758, MCC: 0.0000, F1: 0.7308

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.48580 | val 3.01892
  Epoch 012 - train 0.44482 | val 2.77244
  Classification -> best τ=0.455 (val F1=0.2132)
  Directional -> Accuracy: 0.6190, MCC: 0.2659, F1: 0.7143

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.58644 | val 0.94386
  Epoch 012 - train 0.47189 | val 1.26801
  Classification -> best τ=0.575 (val F1=0.2976)
  Directional -> Accuracy: 0.5000, MCC: -0.0731, F1: 0.1765

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.59421 | val 1.14473
  Epoch 011 - train 0.44966 | val 1.04940
  Classification -> best τ=0.735 (val F1=0.2659)
  Directional -> Accuracy: 0.4348, MCC: -0.1055, F1: 0.4583

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.55925 | val 0.70070
  Epoch 019 - train 0.44724 | val 1.19644
  Classification -> best τ=0.410 (val F1=0.4556)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.57737 | val 1.30164
  Epoch 011 - train 0.51301 | val 1.51821
  Classification -> best τ=0.110 (val F1=0.2112)
  Directional -> Accuracy: 0.4865, MCC: 0.0000, F1: 0.6545

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.60202 | val 1.00988
  Epoch 016 - train 0.53896 | val 1.28184
  Classification -> best τ=0.410 (val F1=0.4632)
  Directional -> Accuracy: 0.6000, MCC: 0.2429, F1: 0.7000

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.46778 | val 2.12618
  Epoch 011 - train 0.45279 | val 1.97160
  Classification -> best τ=0.550 (val F1=0.0364)
  Directional -> Accuracy: 0.5714, MCC: 0.0913, F1: 0.6667

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.60429 | val 1.67923
  Epoch 013 - train 0.40668 | val 1.43928
  Classification -> best τ=0.720 (val F1=0.3737)
  Directional -> Accuracy: 0.6667, MCC: 0.2692, F1: 0.2000

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.63928 | val 1.98861
  Epoch 011 - train 0.59993 | val 2.38407
  Classification -> best τ=0.430 (val F1=0.1605)
  Directional -> Accuracy: 0.5273, MCC: -0.0585, F1: 0.6829

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.49924 | val 2.29599
  Epoch 011 - train 0.42647 | val 2.11563
  Classification -> best τ=0.730 (val F1=0.1694)
  Directional -> Accuracy: 0.5357, MCC: 0.0626, F1: 0.3158

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.65649 | val 0.90127
  Epoch 011 - train 0.55647 | val 1.00385
  Classification -> best τ=0.700 (val F1=0.2155)
  Directional -> Accuracy: 0.6226, MCC: 0.2468, F1: 0.6154

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.51445 | val 2.29893
  Epoch 011 - train 0.53622 | val 2.49129
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5273, MCC: 0.0000, F1: 0.6905

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.60775 | val 0.81189

[I 2026-02-22 14:31:16,207] Trial 218 finished with value: 0.2645607738918905 and parameters: {'feature_set': 'sector', 'model_type': 'BiGRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.4, 'batch_size': 16, 'learning_rate': 0.007324405822338902, 'weight_decay': 4.289864855230319e-05, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 1.046123723031704, 'early_stopping_min_delta': 0.0010822749509641731}. Best is trial 214 with value: 0.2991200218486954.

  Epoch 013 - train 0.56001 | val 0.86333
  Classification -> best τ=0.470 (val F1=0.3093)
  Directional -> Accuracy: 0.5500, MCC: 0.1112, F1: 0.2703

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2645607738918905
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.64692 | val 0.87666
  Epoch 011 - train 0.59593 | val 0.85544
  Classification -> best τ=0.750 (val F1=0.2036)
  Directional -> Accuracy: 0.5526, MCC: 0.0174, F1: 0.0556

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.53548 | val 1.22322
  Epoch 012 - train 0.48406 | val 1.49573
  Classification -> best τ=0.815 (val F1=0.2523)
  Directional -> Accuracy: 0.5778, MCC: 0.1683, F1: 0.5957

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.56092 | val 1.98239
  Epoch 012 - train 0.51149 | val 2.45951
  Classification -> best τ=0.410 (val F1=0.2295)
  Directional -> Accuracy: 0.4130, MCC: -0.2528, F1: 0.5574

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.59343 | val 1.28249
  Epoch 011 - train 0.58492 | val 1.10378
  Classification -> best τ=0.505 (val F1=0.1808)
  Directional -> Accuracy: 0.5270, MCC: -0.0520, F1: 0.6847

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.53924 | val 1.21607
  Epoch 012 - train 0.51396 | val 0.99681
  Classification -> best τ=0.485 (val F1=0.5655)
  Directional -> Accuracy: 0.6400, MCC: 0.3036, F1: 0.5909

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.52579 | val 1.42704
  Epoch 015 - train 0.47280 | val 1.09979
  Classification -> best τ=0.605 (val F1=0.4299)
  Directional -> Accuracy: 0.5217, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.61638 | val 0.95381
  Epoch 012 - train 0.54941 | val 1.08010
  Classification -> best τ=0.515 (val F1=0.2361)
  Directional -> Accuracy: 0.5294, MCC: 0.0790, F1: 0.5000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.66581 | val 0.81347
  Epoch 014 - train 0.41350 | val 0.67246
  Classification -> best τ=0.325 (val F1=0.5247)
  Directional -> Accuracy: 0.5714, MCC: 0.0323, F1: 0.1000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.55052 | val 1.79787
  Epoch 012 - train 0.49691 | val 1.99745
  Classification -> best τ=0.220 (val F1=0.1402)
  Directional -> Accuracy: 0.4375, MCC: 0.0000, F1: 0.6087

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.60486 | val 0.88913
  Epoch 011 - train 0.56181 | val 0.84912
  Classification -> best τ=0.425 (val F1=0.2362)
  Directional -> Accuracy: 0.5362, MCC: 0.0758, F1: 0.5000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.55249 | val 0.84229
  Epoch 013 - train 0.53557 | val 1.12357
  Classification -> best τ=0.540 (val F1=0.3007)
  Directional -> Accuracy: 0.5918, MCC: 0.1635, F1: 0.2857

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.63514 | val 1.00797
  Epoch 012 - train 0.57735 | val 1.10745
  Classification -> best τ=0.470 (val F1=0.2236)
  Directional -> Accuracy: 0.5439, MCC: 0.1941, F1: 0.6905

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.43186 | val 1.63705
  Epoch 011 - train 0.46652 | val 1.59757
  Classification -> best τ=0.560 (val F1=0.1840)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.6230

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.65099 | val 0.93659
  Epoch 014 - train 0.51198 | val 0.97063
  Classification -> best τ=0.205 (val F1=0.2667)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.60882 | val 0.80919
  Epoch 011 - train 0.56239 | val 0.99814
  Classification -> best τ=0.600 (val F1=0.1556)
  Directional -> Accuracy: 0.5490, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.59622 | val 1.30227
  Epoch 012 - train 0.53031 | val 1.75093
  Classification -> best τ=0.735 (val F1=0.3383)
  Directional -> Accuracy: 0.5362, MCC: 0.0565, F1: 0.6000

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.57662 | val 1.04287
  Epoch 012 - train 0.53865 | val 0.89132
  Classification -> best τ=0.485 (val F1=0.1205)
  Directional -> Accuracy: 0.4138, MCC: 0.0322, F1: 0.1905

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.65301 | val 0.76665
  Epoch 012 - train 0.51824 | val 1.02767
  Classification -> best τ=0.595 (val F1=0.1909)
  Directional -> Accuracy: 0.3867, MCC: -0.1430, F1: 0.2581

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.61075 | val 0.77788
  Epoch 015 - train 0.53005 | val 1.49108
  Classification -> best τ=0.435 (val F1=0.3760)
  Directional -> Accuracy: 0.5000, MCC: 0.0149, F1: 0.5152

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.59379 | val 1.19880
  Epoch 011 - train 0.47894 | val 1.18346
  Classification -> best τ=0.460 (val F1=0.2593)
  Directional -> Accuracy: 0.5000, MCC: 0.2145, F1: 0.1778

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.58463 | val 1.15745
  Epoch 012 - train 0.50378 | val 1.02949
  Classification -> best τ=0.555 (val F1=0.3894)
  Directional -> Accuracy: 0.4043, MCC: -0.0121, F1: 0.1765

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.60683 | val 1.36103
  Epoch 011 - train 0.55770 | val 1.78806
  Classification -> best τ=0.310 (val F1=0.1650)
  Directional -> Accuracy: 0.5077, MCC: 0.0000, F1: 0.6735

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.62550 | val 0.81587
  Epoch 011 - train 0.58454 | val 0.81183
  Classification -> best τ=0.555 (val F1=0.3045)
  Directional -> Accuracy: 0.5789, MCC: 0.1613, F1: 0.6000

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.64609 | val 1.68768
  Epoch 012 - train 0.57556 | val 1.32964
  Classification -> best τ=0.440 (val F1=0.1010)
  Directional -> Accuracy: 0.4462, MCC: -0.1400, F1: 0.6087

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.53440 | val 0.95175
  Epoch 011 - train 0.47191 | val 1.02446
  Classification -> best τ=0.475 (val F1=0.5155)
  Directional -> Accuracy: 0.5818, MCC: 0.1733, F1: 0.5818

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.54871 | val 3.18469
  Epoch 012 - train 0.45928 | val 2.25345
  Classification -> best τ=0.680 (val F1=0.0385)
  Directional -> Accuracy: 0.6444, MCC: 0.2704, F1: 0.3333

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.60824 | val 0.72077
  Epoch 020 - train 0.41714 | val 0.82046
  Classification -> best τ=0.485 (val F1=0.1936)
  Directional -> Accuracy: 0.6190, MCC: 0.3712, F1: 0.5294

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.56945 | val 1.18106
  Epoch 011 - train 0.51293 | val 1.30231
  Classification -> best τ=0.395 (val F1=0.0535)
  Directional -> Accuracy: 0.4821, MCC: 0.1728, F1: 0.1212

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.55677 | val 2.18863
  Epoch 012 - train 0.48497 | val 1.82762
  Classification -> best τ=0.540 (val F1=0.0707)
  Directional -> Accuracy: 0.6000, MCC: 0.2010, F1: 0.7241

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.63959 | val 0.75179
  Epoch 015 - train 0.52029 | val 1.70737
  Classification -> best τ=0.645 (val F1=0.4673)
  Directional -> Accuracy: 0.4762, MCC: -0.0674, F1: 0.3529

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.57635 | val 1.23355
  Epoch 012 - train 0.54543 | val 1.11762
  Classification -> best τ=0.435 (val F1=0.0769)
  Directional -> Accuracy: 0.5476, MCC: 0.0000, F1: 0.7077

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.55319 | val 0.95873
  Epoch 011 - train 0.46197 | val 0.97914
  Classification -> best τ=0.350 (val F1=0.2918)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.59359 | val 1.03299
  Epoch 016 - train 0.50606 | val 0.71280
  Classification -> best τ=0.320 (val F1=0.4246)
  Directional -> Accuracy: 0.5556, MCC: 0.0000, F1: 0.7143

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.50320 | val 1.19217
  Epoch 011 - train 0.51733 | val 1.33844
  Classification -> best τ=0.210 (val F1=0.2324)
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.58809 | val 1.93410
  Epoch 012 - train 0.52027 | val 2.23991
  Classification -> best τ=0.275 (val F1=0.2193)
  Directional -> Accuracy: 0.5909, MCC: 0.1443, F1: 0.6667

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.46404 | val 1.64958
  Epoch 015 - train 0.39281 | val 2.66405
  Classification -> best τ=0.515 (val F1=0.3001)
  Directional -> Accuracy: 0.6667, MCC: 0.3441, F1: 0.6500

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.55050 | val 0.75694
  Epoch 019 - train 0.37767 | val 1.11373
  Classification -> best τ=0.605 (val F1=0.2530)
  Directional -> Accuracy: 0.5714, MCC: 0.1260, F1: 0.4545

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.53472 | val 0.90298
  Epoch 011 - train 0.46124 | val 0.86308
  Classification -> best τ=0.755 (val F1=0.2659)
  Directional -> Accuracy: 0.3913, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.49898 | val 0.71310
  Epoch 018 - train 0.49174 | val 1.66070
  Classification -> best τ=0.415 (val F1=0.3859)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.57124 | val 1.40151
  Epoch 011 - train 0.51222 | val 1.73848
  Classification -> best τ=0.605 (val F1=0.3031)
  Directional -> Accuracy: 0.4595, MCC: -0.1172, F1: 0.2308

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.55450 | val 0.71847
  Epoch 014 - train 0.50831 | val 0.68342
  Classification -> best τ=0.350 (val F1=0.4977)
  Directional -> Accuracy: 0.5111, MCC: 0.0000, F1: 0.6765

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.39985 | val 2.55226
  Epoch 011 - train 0.33990 | val 2.41301
  Classification -> best τ=0.535 (val F1=0.1667)
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.7273

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.53224 | val 0.77096
  Epoch 019 - train 0.27559 | val 1.28529
  Classification -> best τ=0.495 (val F1=0.5261)
  Directional -> Accuracy: 0.4375, MCC: 0.2000, F1: 0.5714

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.65367 | val 0.93217
  Epoch 014 - train 0.56345 | val 1.65339
  Classification -> best τ=0.490 (val F1=0.2036)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.50463 | val 2.19433
  Epoch 011 - train 0.44075 | val 2.53370
  Classification -> best τ=0.665 (val F1=0.3067)
  Directional -> Accuracy: 0.5000, MCC: -0.0013, F1: 0.4815

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.62851 | val 0.71204
  Epoch 017 - train 0.57805 | val 0.82937
  Classification -> best τ=0.475 (val F1=0.2801)
  Directional -> Accuracy: 0.6226, MCC: 0.2483, F1: 0.6667

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.54279 | val 2.53876
  Epoch 011 - train 0.48310 | val 3.04494
  Classification -> best τ=0.730 (val F1=0.0117)
  Directional -> Accuracy: 0.4182, MCC: -0.2874, F1: 0.5789

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.62243 | val 0.84886

[I 2026-02-22 14:33:59,562] Trial 219 finished with value: 0.26645466963189474 and parameters: {'feature_set': 'sector', 'model_type': 'BiGRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.4, 'batch_size': 16, 'learning_rate': 0.008597847792150292, 'weight_decay': 5.277270829630958e-05, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 1.092249450551155, 'early_stopping_min_delta': 0.001708898066584954}. Best is trial 214 with value: 0.2991200218486954.

  Epoch 012 - train 0.55649 | val 0.89385
  Classification -> best τ=0.470 (val F1=0.3309)
  Directional -> Accuracy: 0.5167, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.26645466963189474
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.64239 | val 1.14270
  Epoch 012 - train 0.57748 | val 1.16400
  Classification -> best τ=0.670 (val F1=0.2510)
  Directional -> Accuracy: 0.5526, MCC: 0.0000, F1: 0.0000

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.54564 | val 1.28831
  Epoch 016 - train 0.45338 | val 0.94219
  Classification -> best τ=0.320 (val F1=0.2949)
  Directional -> Accuracy: 0.6444, MCC: 0.3126, F1: 0.7647

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.55632 | val 2.06910
  Epoch 012 - train 0.57356 | val 2.08141
  Classification -> best τ=0.730 (val F1=0.3237)
  Directional -> Accuracy: 0.4783, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.61562 | val 0.74332
  Epoch 020 - train 0.51638 | val 0.71152
  Epoch 022 - train 0.44420 | val 0.74330
  Classification -> best τ=0.475 (val F1=0.2204)
  Directional -> Accuracy: 0.4865, MCC: 0.1537, F1: 0.0952

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.61054 | val 1.54172
  Epoch 011 - train 0.49091 | val 1.73780
  Classification -> best τ=0.720 (val F1=0.4247)
  Directional -> Accuracy: 0.6000, MCC: 0.2802, F1: 0.4444

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.54259 | val 0.80435
  Epoch 018 - train 0.33214 | val 1.08122
  Classification -> best τ=0.610 (val F1=0.2912)
  Directional -> Accuracy: 0.5217, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.65219 | val 0.75360
  Epoch 016 - train 0.51554 | val 1.04901
  Classification -> best τ=0.380 (val F1=0.2473)
  Directional -> Accuracy: 0.5294, MCC: 0.1909, F1: 0.5897

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.53110 | val 1.19080
  Epoch 015 - train 0.38528 | val 1.41206
  Classification -> best τ=0.220 (val F1=0.3158)
  Directional -> Accuracy: 0.4524, MCC: 0.0212, F1: 0.5818

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.57416 | val 2.33640
  Epoch 011 - train 0.54976 | val 1.96403
  Classification -> best τ=0.600 (val F1=0.1837)
  Directional -> Accuracy: 0.5833, MCC: 0.1534, F1: 0.5238

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.56544 | val 1.05374
  Epoch 016 - train 0.47382 | val 0.92891
  Classification -> best τ=0.455 (val F1=0.2788)
  Directional -> Accuracy: 0.5072, MCC: 0.0170, F1: 0.4688

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.60125 | val 2.08876
  Epoch 011 - train 0.54106 | val 2.94176
  Classification -> best τ=0.535 (val F1=0.3007)
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.62444 | val 1.28493
  Epoch 012 - train 0.55876 | val 1.27951
  Classification -> best τ=0.420 (val F1=0.3170)
  Directional -> Accuracy: 0.5088, MCC: 0.0000, F1: 0.6744

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.53356 | val 1.25040
  Epoch 011 - train 0.44717 | val 1.20452
  Classification -> best τ=0.510 (val F1=0.1754)
  Directional -> Accuracy: 0.4048, MCC: -0.1758, F1: 0.5455

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.58430 | val 1.18221
  Epoch 013 - train 0.57562 | val 1.02216
  Classification -> best τ=0.450 (val F1=0.4193)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.1176

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.62021 | val 0.69319
  Epoch 020 - train 0.49523 | val 0.97667
  Epoch 022 - train 0.43664 | val 1.81952
  Classification -> best τ=0.505 (val F1=0.2667)
  Directional -> Accuracy: 0.5490, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.66844 | val 1.00486
  Epoch 012 - train 0.54383 | val 1.27746
  Classification -> best τ=0.285 (val F1=0.2341)
  Directional -> Accuracy: 0.5652, MCC: 0.1858, F1: 0.7115

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.55334 | val 0.85924
  Epoch 011 - train 0.51974 | val 1.02800
  Classification -> best τ=0.520 (val F1=0.1521)
  Directional -> Accuracy: 0.5000, MCC: 0.1969, F1: 0.3830

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.58493 | val 0.71787
  Epoch 013 - train 0.50687 | val 0.85590
  Classification -> best τ=0.580 (val F1=0.1909)
  Directional -> Accuracy: 0.4000, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.58935 | val 1.25772
  Epoch 013 - train 0.53785 | val 1.17499
  Classification -> best τ=0.315 (val F1=0.3624)
  Directional -> Accuracy: 0.5000, MCC: -0.0464, F1: 0.5897

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.53524 | val 0.96178
  Epoch 011 - train 0.47844 | val 1.31221
  Classification -> best τ=0.585 (val F1=0.2230)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.52517 | val 1.75310
  Epoch 011 - train 0.47630 | val 1.87835
  Classification -> best τ=0.715 (val F1=0.1033)
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.65845 | val 1.07310
  Epoch 012 - train 0.56373 | val 1.09698
  Classification -> best τ=0.525 (val F1=0.3148)
  Directional -> Accuracy: 0.4923, MCC: -0.0027, F1: 0.0571

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.63437 | val 0.68339
  Epoch 015 - train 0.54328 | val 0.68353
  Classification -> best τ=0.550 (val F1=0.4222)
  Directional -> Accuracy: 0.5789, MCC: 0.1528, F1: 0.6129

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.60260 | val 0.77822
  Epoch 018 - train 0.52468 | val 0.95925
  Classification -> best τ=0.480 (val F1=0.1874)
  Directional -> Accuracy: 0.5538, MCC: 0.1046, F1: 0.5246

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.60730 | val 1.03885
  Epoch 014 - train 0.44143 | val 1.05086
  Classification -> best τ=0.435 (val F1=0.4543)
  Directional -> Accuracy: 0.5455, MCC: 0.0864, F1: 0.5763

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.54506 | val 3.50193
  Epoch 011 - train 0.48279 | val 4.01273
  Classification -> best τ=0.615 (val F1=0.2035)
  Directional -> Accuracy: 0.4000, MCC: -0.1323, F1: 0.5574

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.58355 | val 0.86381
  Epoch 014 - train 0.53313 | val 0.93713
  Classification -> best τ=0.610 (val F1=0.2161)
  Directional -> Accuracy: 0.5238, MCC: 0.1217, F1: 0.4444

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.55035 | val 0.95567
  Epoch 011 - train 0.52351 | val 1.11085
  Classification -> best τ=0.455 (val F1=0.2327)
  Directional -> Accuracy: 0.4464, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.51894 | val 0.99184
  Epoch 012 - train 0.47377 | val 1.47128
  Classification -> best τ=0.580 (val F1=0.3518)
  Directional -> Accuracy: 0.6000, MCC: 0.2010, F1: 0.7241

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.53857 | val 1.93401
  Epoch 012 - train 0.50405 | val 2.16707
  Classification -> best τ=0.490 (val F1=0.3244)
  Directional -> Accuracy: 0.4524, MCC: -0.1003, F1: 0.4103

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.64503 | val 0.73089
  Epoch 020 - train 0.41937 | val 0.82906
  Epoch 021 - train 0.38318 | val 0.89293
  Classification -> best τ=0.415 (val F1=0.3385)
  Directional -> Accuracy: 0.5238, MCC: -0.0663, F1: 0.6774

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.49960 | val 0.88938
  Epoch 012 - train 0.45316 | val 1.19948
  Classification -> best τ=0.575 (val F1=0.3465)
  Directional -> Accuracy: 0.4286, MCC: -0.2193, F1: 0.0000

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.57177 | val 0.91365
  Epoch 013 - train 0.54984 | val 0.96689
  Classification -> best τ=0.790 (val F1=0.2637)
  Directional -> Accuracy: 0.4444, MCC: 0.0000, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.54768 | val 1.24088
  Epoch 013 - train 0.48307 | val 1.43148
  Classification -> best τ=0.475 (val F1=0.2804)
  Directional -> Accuracy: 0.5349, MCC: 0.1579, F1: 0.0909

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.57872 | val 1.39014
  Epoch 012 - train 0.52701 | val 2.15930
  Classification -> best τ=0.330 (val F1=0.2409)
  Directional -> Accuracy: 0.5758, MCC: 0.0000, F1: 0.7308

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.51479 | val 3.16739
  Epoch 012 - train 0.48429 | val 3.78774
  Classification -> best τ=0.485 (val F1=0.2409)
  Directional -> Accuracy: 0.5238, MCC: 0.0337, F1: 0.6000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.60653 | val 0.92404
  Epoch 012 - train 0.49962 | val 1.05629
  Classification -> best τ=0.600 (val F1=0.2382)
  Directional -> Accuracy: 0.5893, MCC: 0.1641, F1: 0.4651

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.52139 | val 0.94320
  Epoch 011 - train 0.47341 | val 0.83711
  Classification -> best τ=0.350 (val F1=0.3146)
  Directional -> Accuracy: 0.5870, MCC: 0.0062, F1: 0.7246

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.56400 | val 0.90444
  Epoch 018 - train 0.39325 | val 0.79969
  Classification -> best τ=0.220 (val F1=0.3469)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.55363 | val 1.39581
  Epoch 011 - train 0.50658 | val 1.53259
  Classification -> best τ=0.280 (val F1=0.2226)
  Directional -> Accuracy: 0.4865, MCC: -0.0199, F1: 0.5476

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.55635 | val 0.82132
  Epoch 020 - train 0.45115 | val 0.81647
  Epoch 023 - train 0.41145 | val 1.50158
  Classification -> best τ=0.520 (val F1=0.5493)
  Directional -> Accuracy: 0.5111, MCC: 0.0832, F1: 0.1538

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.35820 | val 2.73362
  Epoch 012 - train 0.38994 | val 2.22998
  Classification -> best τ=0.490 (val F1=0.5230)
  Directional -> Accuracy: 0.6190, MCC: 0.2107, F1: 0.7419

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.57262 | val 0.86225
  Epoch 014 - train 0.46641 | val 1.10141
  Classification -> best τ=0.445 (val F1=0.4682)
  Directional -> Accuracy: 0.6042, MCC: 0.3752, F1: 0.6415

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.65393 | val 1.33971
  Epoch 011 - train 0.63664 | val 1.22346
  Classification -> best τ=0.550 (val F1=0.2452)
  Directional -> Accuracy: 0.5091, MCC: 0.2193, F1: 0.1818

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.51660 | val 1.71495
  Epoch 011 - train 0.44545 | val 2.07990
  Classification -> best τ=0.335 (val F1=0.3111)
  Directional -> Accuracy: 0.5536, MCC: 0.1225, F1: 0.6032

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.63811 | val 0.74545
  Epoch 012 - train 0.56611 | val 0.78185
  Classification -> best τ=0.620 (val F1=0.1668)
  Directional -> Accuracy: 0.5472, MCC: 0.1599, F1: 0.2941

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.57017 | val 3.86805
  Epoch 011 - train 0.47186 | val 4.73237
  Classification -> best τ=0.685 (val F1=0.1166)
  Directional -> Accuracy: 0.4727, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.63515 | val 0.72960

[I 2026-02-22 14:36:52,017] Trial 220 finished with value: 0.288188018268012 and parameters: {'feature_set': 'sector', 'model_type': 'BiGRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.4, 'batch_size': 16, 'learning_rate': 0.008017961294160526, 'weight_decay': 6.458090918155813e-05, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 0.2319407392513353, 'early_stopping_min_delta': 0.001105222698708041}. Best is trial 214 with value: 0.2991200218486954.

  Epoch 013 - train 0.54505 | val 0.71855
  Classification -> best τ=0.370 (val F1=0.3363)
  Directional -> Accuracy: 0.5833, MCC: 0.1651, F1: 0.4898

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.288188018268012
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.61051 | val 1.25033
  Epoch 012 - train 0.62681 | val 1.33469
  Classification -> best τ=0.700 (val F1=0.2510)
  Directional -> Accuracy: 0.5921, MCC: 0.1542, F1: 0.4364

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.53031 | val 1.16652
  Epoch 011 - train 0.46161 | val 1.11668
  Classification -> best τ=0.445 (val F1=0.2798)
  Directional -> Accuracy: 0.5778, MCC: 0.0842, F1: 0.6885

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.61963 | val 2.15510
  Epoch 012 - train 0.50846 | val 3.08148
  Classification -> best τ=0.625 (val F1=0.2311)
  Directional -> Accuracy: 0.5870, MCC: 0.1921, F1: 0.5366

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.57240 | val 1.84437
  Epoch 011 - train 0.54455 | val 2.00870
  Classification -> best τ=0.540 (val F1=0.2309)
  Directional -> Accuracy: 0.4730, MCC: -0.0019, F1: 0.2642

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.51252 | val 1.20699
  Epoch 011 - train 0.45758 | val 1.28485
  Classification -> best τ=0.520 (val F1=0.4247)
  Directional -> Accuracy: 0.6200, MCC: 0.2795, F1: 0.5366

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.53596 | val 0.72272
  Epoch 019 - train 0.33118 | val 1.37226
  Classification -> best τ=0.615 (val F1=0.4957)
  Directional -> Accuracy: 0.5217, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.63757 | val 0.82190
  Epoch 017 - train 0.50378 | val 0.98141
  Classification -> best τ=0.435 (val F1=0.2179)
  Directional -> Accuracy: 0.5441, MCC: 0.0902, F1: 0.4918

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.54771 | val 0.84961
  Epoch 018 - train 0.31780 | val 1.14145
  Classification -> best τ=0.300 (val F1=0.2657)
  Directional -> Accuracy: 0.4762, MCC: 0.0152, F1: 0.5417

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.55035 | val 1.41114
  Epoch 012 - train 0.49162 | val 2.10341
  Classification -> best τ=0.460 (val F1=0.3047)
  Directional -> Accuracy: 0.6667, MCC: 0.3115, F1: 0.5556

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.60223 | val 0.99666
  Epoch 011 - train 0.59888 | val 0.92890
  Classification -> best τ=0.435 (val F1=0.1839)
  Directional -> Accuracy: 0.4348, MCC: -0.0749, F1: 0.4935

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.60517 | val 1.01256
  Epoch 016 - train 0.48212 | val 2.13641
  Classification -> best τ=0.505 (val F1=0.4191)
  Directional -> Accuracy: 0.5306, MCC: 0.0637, F1: 0.5106

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.57770 | val 1.83384
  Epoch 012 - train 0.57573 | val 1.46771
  Classification -> best τ=0.535 (val F1=0.2162)
  Directional -> Accuracy: 0.5088, MCC: 0.0000, F1: 0.6744

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.48029 | val 1.71443
  Epoch 011 - train 0.48525 | val 1.84974
  Classification -> best τ=0.450 (val F1=0.1801)
  Directional -> Accuracy: 0.5238, MCC: 0.0572, F1: 0.5238

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.62478 | val 0.83368
  Epoch 013 - train 0.55550 | val 0.79002
  Classification -> best τ=0.240 (val F1=0.4995)
  Directional -> Accuracy: 0.5333, MCC: 0.0668, F1: 0.5172

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.51882 | val 0.69950
  Epoch 011 - train 0.50592 | val 0.79050
  Classification -> best τ=0.515 (val F1=0.1556)
  Directional -> Accuracy: 0.5686, MCC: 0.1084, F1: 0.1538

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.58847 | val 1.56817
  Epoch 011 - train 0.53731 | val 1.23292
  Classification -> best τ=0.795 (val F1=0.1709)
  Directional -> Accuracy: 0.4638, MCC: 0.0000, F1: 0.0000

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.60503 | val 1.30120
  Epoch 012 - train 0.52378 | val 1.46845
  Classification -> best τ=0.625 (val F1=0.1878)
  Directional -> Accuracy: 0.6207, MCC: 0.0000, F1: 0.7660

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.64680 | val 0.88649
  Epoch 016 - train 0.47393 | val 1.01191
  Classification -> best τ=0.555 (val F1=0.2220)
  Directional -> Accuracy: 0.4000, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.57029 | val 0.89123
  Epoch 013 - train 0.51390 | val 1.25547
  Classification -> best τ=0.205 (val F1=0.3624)
  Directional -> Accuracy: 0.5156, MCC: -0.1062, F1: 0.6593

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.57303 | val 1.47440
  Epoch 011 - train 0.48263 | val 1.52838
  Classification -> best τ=0.410 (val F1=0.3151)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.56011 | val 0.76221
  Epoch 012 - train 0.45984 | val 0.89010
  Classification -> best τ=0.505 (val F1=0.1830)
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.58678 | val 1.87486
  Epoch 011 - train 0.55443 | val 2.13450
  Classification -> best τ=0.480 (val F1=0.0157)
  Directional -> Accuracy: 0.5692, MCC: 0.1431, F1: 0.5333

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.57300 | val 0.65651
  Epoch 011 - train 0.59124 | val 0.70411
  Classification -> best τ=0.690 (val F1=0.3550)
  Directional -> Accuracy: 0.5439, MCC: 0.0820, F1: 0.5806

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.61546 | val 0.70859
  Epoch 011 - train 0.55069 | val 0.85216
  Classification -> best τ=0.595 (val F1=0.1874)
  Directional -> Accuracy: 0.4615, MCC: -0.1510, F1: 0.1463

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.56229 | val 0.73322
  Epoch 020 - train 0.40722 | val 0.74008
  Epoch 028 - train 0.24835 | val 1.12955
  Classification -> best τ=0.505 (val F1=0.4914)
  Directional -> Accuracy: 0.5818, MCC: 0.1733, F1: 0.5818

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.59269 | val 2.17118
  Epoch 011 - train 0.48534 | val 2.58465
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.5938

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.60002 | val 0.73364
  Epoch 014 - train 0.55553 | val 0.90976
  Classification -> best τ=0.470 (val F1=0.1978)
  Directional -> Accuracy: 0.5714, MCC: 0.0807, F1: 0.6786

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.67149 | val 1.49509
  Epoch 012 - train 0.51463 | val 1.20538
  Classification -> best τ=0.520 (val F1=0.3280)
  Directional -> Accuracy: 0.4464, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.56049 | val 0.77871
  Epoch 020 - train 0.31935 | val 0.91552
  Epoch 023 - train 0.22809 | val 0.71402
  Classification -> best τ=0.570 (val F1=0.5105)
  Directional -> Accuracy: 0.5000, MCC: -0.0316, F1: 0.5833

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.61555 | val 1.56252
  Epoch 013 - train 0.55223 | val 0.92630
  Classification -> best τ=0.565 (val F1=0.2814)
  Directional -> Accuracy: 0.4762, MCC: -0.0608, F1: 0.3889

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.69137 | val 1.02557
  Epoch 011 - train 0.56447 | val 0.90130
  Classification -> best τ=0.395 (val F1=0.0409)
  Directional -> Accuracy: 0.7143, MCC: 0.4571, F1: 0.7000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.47242 | val 0.80799
  Epoch 011 - train 0.45724 | val 0.81616
  Classification -> best τ=0.595 (val F1=0.4451)
  Directional -> Accuracy: 0.4694, MCC: 0.0000, F1: 0.0000

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.65882 | val 0.83079
  Epoch 012 - train 0.52852 | val 0.97915
  Classification -> best τ=0.390 (val F1=0.3244)
  Directional -> Accuracy: 0.4722, MCC: 0.0949, F1: 0.1364

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.56417 | val 0.81564
  Epoch 011 - train 0.48547 | val 1.01165
  Classification -> best τ=0.365 (val F1=0.3652)
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.55275 | val 2.31698
  Epoch 011 - train 0.51955 | val 2.17027
  Classification -> best τ=0.585 (val F1=0.0929)
  Directional -> Accuracy: 0.4242, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.53418 | val 1.69200
  Epoch 011 - train 0.39801 | val 2.37577
  Classification -> best τ=0.635 (val F1=0.2618)
  Directional -> Accuracy: 0.6190, MCC: 0.3091, F1: 0.5000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.58588 | val 0.80970
  Epoch 012 - train 0.49014 | val 0.96022
  Classification -> best τ=0.505 (val F1=0.3181)
  Directional -> Accuracy: 0.5893, MCC: 0.1666, F1: 0.4103

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.54654 | val 1.08549
  Epoch 011 - train 0.42793 | val 1.09328
  Classification -> best τ=0.255 (val F1=0.1195)
  Directional -> Accuracy: 0.5000, MCC: -0.2157, F1: 0.6567

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.63845 | val 0.77082
  Epoch 015 - train 0.48335 | val 0.86943
  Classification -> best τ=0.525 (val F1=0.4688)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.54478 | val 2.67399
  Epoch 012 - train 0.48925 | val 2.61704
  Classification -> best τ=0.190 (val F1=0.3031)
  Directional -> Accuracy: 0.4595, MCC: -0.0804, F1: 0.4595

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.61020 | val 1.18097
  Epoch 014 - train 0.52854 | val 1.22269
  Classification -> best τ=0.535 (val F1=0.3953)
  Directional -> Accuracy: 0.5556, MCC: 0.1632, F1: 0.6875

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.44239 | val 3.24545
  Epoch 011 - train 0.39602 | val 3.05943
  Classification -> best τ=0.365 (val F1=0.1667)
  Directional -> Accuracy: 0.5476, MCC: -0.1353, F1: 0.7077

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.55402 | val 1.13170
  Epoch 011 - train 0.51594 | val 1.32418
  Classification -> best τ=0.555 (val F1=0.2689)
  Directional -> Accuracy: 0.5208, MCC: 0.2619, F1: 0.5965

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.65972 | val 1.00786
  Epoch 012 - train 0.61205 | val 1.59232
  Classification -> best τ=0.625 (val F1=0.2036)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.46120 | val 2.90806
  Epoch 011 - train 0.44591 | val 2.76992
  Classification -> best τ=0.630 (val F1=0.2143)
  Directional -> Accuracy: 0.5179, MCC: 0.0000, F1: 0.0000

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.64655 | val 0.90599
  Epoch 012 - train 0.57942 | val 0.90325
  Classification -> best τ=0.645 (val F1=0.1668)
  Directional -> Accuracy: 0.5094, MCC: 0.0484, F1: 0.2353

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.51312 | val 2.39352
  Epoch 011 - train 0.50263 | val 3.19325
  Classification -> best τ=0.820 (val F1=0.0322)
  Directional -> Accuracy: 0.4727, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.64627 | val 0.69208

[I 2026-02-22 14:39:33,862] Trial 221 finished with value: 0.2628232789286183 and parameters: {'feature_set': 'sector', 'model_type': 'BiGRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.4, 'batch_size': 16, 'learning_rate': 0.008541972334870276, 'weight_decay': 7.195121723171062e-05, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 0.29552354680987486, 'early_stopping_min_delta': 0.0012069260007881737}. Best is trial 214 with value: 0.2991200218486954.

  Epoch 013 - train 0.59729 | val 0.91763
  Classification -> best τ=0.320 (val F1=0.2637)
  Directional -> Accuracy: 0.5333, MCC: 0.0766, F1: 0.5758

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2628232789286183
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.62492 | val 1.03013
  Epoch 012 - train 0.59856 | val 1.25387
  Classification -> best τ=0.890 (val F1=0.2510)
  Directional -> Accuracy: 0.5658, MCC: 0.1283, F1: 0.0571

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.53411 | val 1.04636
  Epoch 011 - train 0.52872 | val 1.10156
  Classification -> best τ=0.530 (val F1=0.2523)
  Directional -> Accuracy: 0.6667, MCC: 0.2984, F1: 0.7458

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.54381 | val 1.69814
  Epoch 011 - train 0.45895 | val 2.21195
  Classification -> best τ=0.760 (val F1=0.3537)
  Directional -> Accuracy: 0.4783, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.62384 | val 1.34615
  Epoch 011 - train 0.57043 | val 0.84370
  Classification -> best τ=0.390 (val F1=0.2377)
  Directional -> Accuracy: 0.5270, MCC: 0.0375, F1: 0.5882

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.59873 | val 0.98890
  Epoch 012 - train 0.47507 | val 1.13211
  Classification -> best τ=0.600 (val F1=0.4602)
  Directional -> Accuracy: 0.5800, MCC: 0.1922, F1: 0.4878

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.53067 | val 1.17904
  Epoch 014 - train 0.44566 | val 0.78019
  Classification -> best τ=0.595 (val F1=0.3525)
  Directional -> Accuracy: 0.5217, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.58680 | val 0.92653
  Epoch 012 - train 0.52051 | val 1.47684
  Classification -> best τ=0.345 (val F1=0.3546)
  Directional -> Accuracy: 0.4412, MCC: 0.0509, F1: 0.5581

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.53572 | val 0.89760
  Epoch 015 - train 0.53618 | val 0.74215
  Classification -> best τ=0.355 (val F1=0.3689)
  Directional -> Accuracy: 0.4524, MCC: -0.1635, F1: 0.2581

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.53314 | val 2.38752
  Epoch 011 - train 0.54010 | val 2.53478
  Classification -> best τ=0.640 (val F1=0.1928)
  Directional -> Accuracy: 0.5833, MCC: 0.1240, F1: 0.4118

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.59299 | val 0.77648
  Epoch 020 - train 0.44563 | val 1.24689
  Epoch 021 - train 0.43094 | val 1.12463
  Classification -> best τ=0.865 (val F1=0.1983)
  Directional -> Accuracy: 0.5072, MCC: -0.0017, F1: 0.4333

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.66296 | val 0.64390
  Epoch 019 - train 0.42847 | val 0.78303
  Classification -> best τ=0.305 (val F1=0.3836)
  Directional -> Accuracy: 0.5714, MCC: 0.1005, F1: 0.2759

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.55129 | val 1.33521
  Epoch 011 - train 0.49750 | val 1.68649
  Classification -> best τ=0.445 (val F1=0.1576)
  Directional -> Accuracy: 0.5263, MCC: 0.0502, F1: 0.5714

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.50070 | val 2.01201
  Epoch 013 - train 0.42779 | val 2.91789
  Classification -> best τ=0.345 (val F1=0.1632)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.6230

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.59815 | val 0.74353
  Epoch 011 - train 0.57896 | val 0.74363
  Classification -> best τ=0.445 (val F1=0.3477)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.63213 | val 0.79598
  Epoch 019 - train 0.43256 | val 1.06756
  Classification -> best τ=0.475 (val F1=0.3140)
  Directional -> Accuracy: 0.4902, MCC: -0.0557, F1: 0.3500

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.56693 | val 1.63478
  Epoch 012 - train 0.53242 | val 1.20268
  Classification -> best τ=0.410 (val F1=0.1512)
  Directional -> Accuracy: 0.5217, MCC: -0.0558, F1: 0.6796

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.60277 | val 0.83094
  Epoch 011 - train 0.51626 | val 1.04036
  Classification -> best τ=0.495 (val F1=0.1931)
  Directional -> Accuracy: 0.6207, MCC: 0.0000, F1: 0.7660

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.58016 | val 0.88847
  Epoch 017 - train 0.54430 | val 0.81066
  Classification -> best τ=0.535 (val F1=0.2220)
  Directional -> Accuracy: 0.4000, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.59288 | val 1.56827
  Epoch 011 - train 0.54960 | val 1.56706
  Classification -> best τ=0.475 (val F1=0.3144)
  Directional -> Accuracy: 0.5156, MCC: 0.0853, F1: 0.4746

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.52716 | val 1.50243
  Epoch 011 - train 0.50196 | val 1.63399
  Classification -> best τ=0.245 (val F1=0.2457)
  Directional -> Accuracy: 0.4865, MCC: -0.1022, F1: 0.6122

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.51808 | val 0.86265
  Epoch 011 - train 0.48820 | val 0.94286
  Classification -> best τ=0.400 (val F1=0.2784)
  Directional -> Accuracy: 0.6170, MCC: 0.0000, F1: 0.7632

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.59551 | val 0.95421
  Epoch 012 - train 0.54361 | val 0.99259
  Classification -> best τ=0.610 (val F1=0.3190)
  Directional -> Accuracy: 0.5692, MCC: 0.1742, F1: 0.4167

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.61166 | val 0.70711
  Epoch 020 - train 0.53458 | val 0.59945
  Epoch 023 - train 0.40718 | val 0.95370
  Classification -> best τ=0.785 (val F1=0.4108)
  Directional -> Accuracy: 0.4912, MCC: 0.0465, F1: 0.3830

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.57402 | val 1.60712
  Epoch 011 - train 0.59564 | val 1.49281
  Classification -> best τ=0.515 (val F1=0.2366)
  Directional -> Accuracy: 0.5231, MCC: 0.1330, F1: 0.6517

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.53078 | val 1.45294
  Epoch 011 - train 0.47107 | val 1.53371
  Classification -> best τ=0.570 (val F1=0.2446)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.52645 | val 2.57437
  Epoch 011 - train 0.44221 | val 3.01639
  Classification -> best τ=0.530 (val F1=0.4947)
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.5938

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.57385 | val 0.68918
  Epoch 012 - train 0.51388 | val 0.71531
  Classification -> best τ=0.500 (val F1=0.2582)
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.7273

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.57533 | val 1.27306
  Epoch 011 - train 0.51636 | val 1.56426
  Classification -> best τ=0.330 (val F1=0.2149)
  Directional -> Accuracy: 0.4821, MCC: -0.0207, F1: 0.4727

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.51365 | val 0.75325
  Epoch 011 - train 0.46264 | val 0.76036
  Classification -> best τ=0.555 (val F1=0.1748)
  Directional -> Accuracy: 0.6000, MCC: 0.1741, F1: 0.6923

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.64005 | val 0.84252
  Epoch 019 - train 0.46506 | val 1.51823
  Classification -> best τ=0.600 (val F1=0.3501)
  Directional -> Accuracy: 0.4762, MCC: -0.0754, F1: 0.3125

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.53357 | val 1.37910
  Epoch 011 - train 0.54457 | val 1.57031
  Classification -> best τ=0.380 (val F1=0.2428)
  Directional -> Accuracy: 0.4048, MCC: -0.2071, F1: 0.4681

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.55473 | val 0.95891
  Epoch 011 - train 0.51509 | val 1.11373
  Classification -> best τ=0.470 (val F1=0.3461)
  Directional -> Accuracy: 0.5102, MCC: 0.0217, F1: 0.5200

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.60051 | val 0.98844
  Epoch 013 - train 0.51166 | val 0.83373
  Classification -> best τ=0.305 (val F1=0.3576)
  Directional -> Accuracy: 0.5139, MCC: 0.1147, F1: 0.3636

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.51432 | val 1.72284
  Epoch 012 - train 0.46672 | val 1.70930
  Classification -> best τ=0.780 (val F1=0.3385)
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.59870 | val 1.05997
  Epoch 013 - train 0.54156 | val 1.73046
  Classification -> best τ=0.230 (val F1=0.3525)
  Directional -> Accuracy: 0.6515, MCC: 0.2656, F1: 0.7356

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.50002 | val 1.84970
  Epoch 013 - train 0.53600 | val 2.06793
  Classification -> best τ=0.225 (val F1=0.3001)
  Directional -> Accuracy: 0.5714, MCC: 0.1455, F1: 0.5714

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.55794 | val 0.79579
  Epoch 012 - train 0.49815 | val 0.93741
  Classification -> best τ=0.675 (val F1=0.2277)
  Directional -> Accuracy: 0.6071, MCC: 0.2067, F1: 0.4500

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.50230 | val 1.30385
  Epoch 011 - train 0.42992 | val 1.34269
  Classification -> best τ=0.410 (val F1=0.3370)
  Directional -> Accuracy: 0.5652, MCC: 0.0691, F1: 0.6552

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.52134 | val 1.09406
  Epoch 011 - train 0.50821 | val 1.14450
  Classification -> best τ=0.630 (val F1=0.4011)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.54990 | val 1.49112
  Epoch 011 - train 0.47269 | val 1.85646
  Classification -> best τ=0.565 (val F1=0.2222)
  Directional -> Accuracy: 0.4459, MCC: -0.1388, F1: 0.2545

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.61135 | val 0.78007
  Epoch 018 - train 0.45363 | val 0.91839
  Classification -> best τ=0.570 (val F1=0.2874)
  Directional -> Accuracy: 0.4444, MCC: -0.1395, F1: 0.1379

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.39139 | val 2.04343
  Epoch 015 - train 0.25197 | val 2.50937
  Classification -> best τ=0.445 (val F1=0.5000)
  Directional -> Accuracy: 0.6667, MCC: 0.3043, F1: 0.7407

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.50454 | val 0.68861
  Epoch 018 - train 0.29624 | val 0.88372
  Classification -> best τ=0.560 (val F1=0.5249)
  Directional -> Accuracy: 0.4167, MCC: 0.1615, F1: 0.5625

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.66826 | val 1.04226
  Epoch 012 - train 0.60859 | val 1.71362
  Classification -> best τ=0.640 (val F1=0.1647)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.47532 | val 2.32363
  Epoch 011 - train 0.44660 | val 2.33762
  Classification -> best τ=0.700 (val F1=0.2696)
  Directional -> Accuracy: 0.5179, MCC: 0.0246, F1: 0.4000

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.61297 | val 0.76254
  Epoch 011 - train 0.60079 | val 0.73886
  Classification -> best τ=0.530 (val F1=0.2064)
  Directional -> Accuracy: 0.6038, MCC: 0.2082, F1: 0.6441

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.54839 | val 3.98991
  Epoch 012 - train 0.49089 | val 2.79052
  Classification -> best τ=0.525 (val F1=0.2945)
  Directional -> Accuracy: 0.4545, MCC: -0.0933, F1: 0.0625

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.61494 | val 0.77915

[I 2026-02-22 14:42:17,353] Trial 222 finished with value: 0.29557200369354864 and parameters: {'feature_set': 'sector', 'model_type': 'BiGRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.4, 'batch_size': 16, 'learning_rate': 0.00671018955264115, 'weight_decay': 6.313223069415127e-05, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 1.0107255246585416, 'early_stopping_min_delta': 0.0010199264773707965}. Best is trial 214 with value: 0.2991200218486954.

  Epoch 015 - train 0.53537 | val 0.70192
  Classification -> best τ=0.380 (val F1=0.3178)
  Directional -> Accuracy: 0.6667, MCC: 0.3601, F1: 0.7059

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.29557200369354864
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.61558 | val 0.96461
  Epoch 014 - train 0.59013 | val 1.37455
  Classification -> best τ=0.550 (val F1=0.2919)
  Directional -> Accuracy: 0.5395, MCC: -0.0465, F1: 0.0541

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.58542 | val 1.62467
  Epoch 012 - train 0.47388 | val 1.32709
  Classification -> best τ=0.450 (val F1=0.1764)
  Directional -> Accuracy: 0.6222, MCC: 0.2073, F1: 0.7463

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.56498 | val 1.52800
  Epoch 012 - train 0.47747 | val 1.58946
  Classification -> best τ=0.590 (val F1=0.2449)
  Directional -> Accuracy: 0.4783, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.59892 | val 1.06279
  Epoch 011 - train 0.52846 | val 1.25795
  Classification -> best τ=0.275 (val F1=0.1812)
  Directional -> Accuracy: 0.4595, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.51464 | val 0.84628
  Epoch 013 - train 0.47525 | val 1.96408
  Classification -> best τ=0.540 (val F1=0.4851)
  Directional -> Accuracy: 0.6000, MCC: 0.2202, F1: 0.5455

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.51304 | val 0.75467
  Epoch 017 - train 0.44199 | val 1.94255
  Classification -> best τ=0.545 (val F1=0.4957)
  Directional -> Accuracy: 0.5217, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.61016 | val 0.89820
  Epoch 011 - train 0.54512 | val 0.84112
  Classification -> best τ=0.610 (val F1=0.3514)
  Directional -> Accuracy: 0.4853, MCC: 0.0072, F1: 0.4776

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.57252 | val 0.67512
  Epoch 020 - train 0.43794 | val 1.05657
  Epoch 023 - train 0.38327 | val 1.11867
  Classification -> best τ=0.125 (val F1=0.3094)
  Directional -> Accuracy: 0.4524, MCC: 0.0212, F1: 0.5818

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.57526 | val 2.48513
  Epoch 013 - train 0.50281 | val 2.04103
  Classification -> best τ=0.695 (val F1=0.2764)
  Directional -> Accuracy: 0.6042, MCC: 0.2002, F1: 0.5581

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.59348 | val 0.77034
  Epoch 014 - train 0.50307 | val 0.89584
  Classification -> best τ=0.465 (val F1=0.2355)
  Directional -> Accuracy: 0.4783, MCC: -0.0511, F1: 0.4194

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.62926 | val 0.74485
  Epoch 011 - train 0.54966 | val 0.82273
  Classification -> best τ=0.380 (val F1=0.2867)
  Directional -> Accuracy: 0.4694, MCC: 0.0594, F1: 0.6176

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.57275 | val 1.37702
  Epoch 013 - train 0.52692 | val 1.27379
  Classification -> best τ=0.370 (val F1=0.2667)
  Directional -> Accuracy: 0.5088, MCC: 0.0000, F1: 0.6744

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.55506 | val 1.88452
  Epoch 011 - train 0.44776 | val 1.31899
  Classification -> best τ=0.485 (val F1=0.1754)
  Directional -> Accuracy: 0.4286, MCC: -0.1114, F1: 0.5200

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.61370 | val 0.65989
  Epoch 018 - train 0.44688 | val 1.05957
  Classification -> best τ=0.520 (val F1=0.4109)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.60538 | val 0.74851
  Epoch 011 - train 0.56919 | val 0.79041
  Classification -> best τ=0.495 (val F1=0.1556)
  Directional -> Accuracy: 0.5490, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.56289 | val 1.08042
  Epoch 011 - train 0.51997 | val 1.14103
  Classification -> best τ=0.895 (val F1=0.0972)
  Directional -> Accuracy: 0.4638, MCC: 0.0000, F1: 0.0000

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.59698 | val 1.15940
  Epoch 012 - train 0.53032 | val 1.19452
  Classification -> best τ=0.305 (val F1=0.2683)
  Directional -> Accuracy: 0.5172, MCC: -0.1687, F1: 0.6667

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.57069 | val 0.84835
  Epoch 012 - train 0.53054 | val 1.31164
  Classification -> best τ=0.505 (val F1=0.2220)
  Directional -> Accuracy: 0.4000, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.61219 | val 0.84701
  Epoch 012 - train 0.53741 | val 0.75516
  Classification -> best τ=0.320 (val F1=0.2616)
  Directional -> Accuracy: 0.5469, MCC: 0.0664, F1: 0.6133

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.55936 | val 1.60670
  Epoch 011 - train 0.54902 | val 1.47164
  Classification -> best τ=0.270 (val F1=0.2482)
  Directional -> Accuracy: 0.5541, MCC: 0.0000, F1: 0.7130

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.50791 | val 1.41476
  Epoch 011 - train 0.48417 | val 1.34085
  Classification -> best τ=0.545 (val F1=0.3237)
  Directional -> Accuracy: 0.4043, MCC: 0.1162, F1: 0.0667

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.58475 | val 1.32232
  Epoch 011 - train 0.52500 | val 1.58445
  Classification -> best τ=0.440 (val F1=0.2371)
  Directional -> Accuracy: 0.5077, MCC: 0.0000, F1: 0.6735

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.59610 | val 0.64039
  Epoch 019 - train 0.55189 | val 0.78198
  Classification -> best τ=0.445 (val F1=0.4055)
  Directional -> Accuracy: 0.4912, MCC: -0.2428, F1: 0.6588

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.56784 | val 0.81218
  Epoch 012 - train 0.57341 | val 0.99079
  Classification -> best τ=0.600 (val F1=0.1348)
  Directional -> Accuracy: 0.5538, MCC: 0.1111, F1: 0.2564

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.52504 | val 1.37845
  Epoch 012 - train 0.45753 | val 1.41076
  Classification -> best τ=0.480 (val F1=0.5294)
  Directional -> Accuracy: 0.4727, MCC: 0.1242, F1: 0.0645

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.50691 | val 2.42102
  Epoch 011 - train 0.45587 | val 2.76498
  Classification -> best τ=0.715 (val F1=0.1890)
  Directional -> Accuracy: 0.5778, MCC: 0.0000, F1: 0.0000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.61181 | val 0.91237
  Epoch 011 - train 0.56927 | val 0.99336
  Classification -> best τ=0.415 (val F1=0.1925)
  Directional -> Accuracy: 0.5952, MCC: 0.1291, F1: 0.7119

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.51237 | val 1.42398
  Epoch 011 - train 0.48847 | val 1.81220
  Classification -> best τ=0.280 (val F1=0.2543)
  Directional -> Accuracy: 0.4464, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.64185 | val 2.06056
  Epoch 015 - train 0.47329 | val 1.21818
  Classification -> best τ=0.480 (val F1=0.3518)
  Directional -> Accuracy: 0.5500, MCC: 0.0335, F1: 0.6897

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.57891 | val 1.20215
  Epoch 017 - train 0.46073 | val 0.87006
  Classification -> best τ=0.460 (val F1=0.3823)
  Directional -> Accuracy: 0.4762, MCC: -0.0455, F1: 0.4762

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.59339 | val 0.83495
  Epoch 019 - train 0.45907 | val 0.84687
  Classification -> best τ=0.670 (val F1=0.1286)
  Directional -> Accuracy: 0.4524, MCC: -0.0464, F1: 0.2581

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.53049 | val 0.90305
  Epoch 012 - train 0.42736 | val 0.97218
  Classification -> best τ=0.215 (val F1=0.3142)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.59530 | val 0.67726
  Epoch 019 - train 0.46723 | val 0.97817
  Classification -> best τ=0.375 (val F1=0.3610)
  Directional -> Accuracy: 0.5556, MCC: 0.1000, F1: 0.6000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.52498 | val 1.04273
  Epoch 011 - train 0.47903 | val 1.22355
  Classification -> best τ=0.430 (val F1=0.1874)
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.55525 | val 1.39390
  Epoch 011 - train 0.56725 | val 1.41974
  Classification -> best τ=0.385 (val F1=0.0486)
  Directional -> Accuracy: 0.5758, MCC: 0.0000, F1: 0.7308

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.48853 | val 2.49208
  Epoch 013 - train 0.39953 | val 3.11050
  Classification -> best τ=0.570 (val F1=0.3001)
  Directional -> Accuracy: 0.4762, MCC: -0.0107, F1: 0.0833

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.50580 | val 0.97137
  Epoch 011 - train 0.51926 | val 0.96246
  Classification -> best τ=0.720 (val F1=0.1238)
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.0000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.48548 | val 0.92971
  Epoch 011 - train 0.41129 | val 1.12665
  Classification -> best τ=0.400 (val F1=0.0318)
  Directional -> Accuracy: 0.5217, MCC: -0.0463, F1: 0.6333

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.55092 | val 0.92600
  Epoch 013 - train 0.48878 | val 0.80410
  Classification -> best τ=0.610 (val F1=0.4710)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.53676 | val 2.36015
  Epoch 011 - train 0.48440 | val 3.11249
  Classification -> best τ=0.610 (val F1=0.3057)
  Directional -> Accuracy: 0.5135, MCC: 0.0000, F1: 0.0000

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.58467 | val 0.73506
  Epoch 019 - train 0.40523 | val 1.69845
  Classification -> best τ=0.640 (val F1=0.4490)
  Directional -> Accuracy: 0.4667, MCC: -0.0629, F1: 0.3684

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.45767 | val 1.41553
  Epoch 011 - train 0.34759 | val 1.66224
  Classification -> best τ=0.620 (val F1=0.2010)
  Directional -> Accuracy: 0.4286, MCC: -0.0323, F1: 0.0769

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.64676 | val 1.38537
  Epoch 013 - train 0.43833 | val 1.34319
  Classification -> best τ=0.735 (val F1=0.2902)
  Directional -> Accuracy: 0.5833, MCC: 0.1721, F1: 0.5238

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.63393 | val 1.03288
  Epoch 013 - train 0.58333 | val 1.36480
  Classification -> best τ=0.495 (val F1=0.2132)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.49423 | val 1.84589
  Epoch 011 - train 0.44473 | val 1.87018
  Classification -> best τ=0.620 (val F1=0.3695)
  Directional -> Accuracy: 0.4821, MCC: -0.0206, F1: 0.5797

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.65234 | val 0.72946
  Epoch 013 - train 0.64480 | val 0.98794
  Classification -> best τ=0.575 (val F1=0.1801)
  Directional -> Accuracy: 0.6038, MCC: 0.2109, F1: 0.6557

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.54298 | val 3.81822
  Epoch 011 - train 0.48633 | val 3.78356
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5273, MCC: 0.0000, F1: 0.6905

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.59254 | val 1.01838

[I 2026-02-22 14:45:05,227] Trial 223 finished with value: 0.26488030612697067 and parameters: {'feature_set': 'sector', 'model_type': 'BiGRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.4, 'batch_size': 16, 'learning_rate': 0.006537422683306971, 'weight_decay': 6.161849145815774e-05, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 0.20747523357585923, 'early_stopping_min_delta': 0.0010024609467525639}. Best is trial 214 with value: 0.2991200218486954.

  Epoch 014 - train 0.56183 | val 1.27095
  Classification -> best τ=0.410 (val F1=0.2984)
  Directional -> Accuracy: 0.6000, MCC: 0.2313, F1: 0.4000

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.26488030612697067
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.64220 | val 0.93708
  Epoch 015 - train 0.59530 | val 1.14142
  Classification -> best τ=0.785 (val F1=0.2919)
  Directional -> Accuracy: 0.5395, MCC: -0.1039, F1: 0.0000

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.56321 | val 0.78317
  Epoch 012 - train 0.47282 | val 0.84789
  Classification -> best τ=0.580 (val F1=0.1941)
  Directional -> Accuracy: 0.6000, MCC: 0.1419, F1: 0.7000

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.55023 | val 1.50226
  Epoch 011 - train 0.54640 | val 1.66837
  Classification -> best τ=0.900 (val F1=0.3114)
  Directional -> Accuracy: 0.4565, MCC: -0.1557, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.60660 | val 1.22714
  Epoch 011 - train 0.57795 | val 1.10229
  Classification -> best τ=0.455 (val F1=0.1895)
  Directional -> Accuracy: 0.4459, MCC: -0.1269, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.56440 | val 1.37491
  Epoch 011 - train 0.53419 | val 1.36491
  Classification -> best τ=0.615 (val F1=0.4342)
  Directional -> Accuracy: 0.6400, MCC: 0.2942, F1: 0.6087

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.57482 | val 0.66329
  Epoch 020 - train 0.45898 | val 1.34115
  Classification -> best τ=0.570 (val F1=0.3525)
  Directional -> Accuracy: 0.5217, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.57640 | val 1.03812
  Epoch 011 - train 0.57173 | val 1.01123
  Classification -> best τ=0.315 (val F1=0.1453)
  Directional -> Accuracy: 0.4412, MCC: 0.1743, F1: 0.5870

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.53223 | val 0.59451
  Epoch 020 - train 0.35205 | val 1.25427
  Classification -> best τ=0.065 (val F1=0.2075)
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.57601 | val 0.77162
  Epoch 011 - train 0.47637 | val 1.08640
  Classification -> best τ=0.505 (val F1=0.2285)
  Directional -> Accuracy: 0.5625, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.53300 | val 0.87900
  Epoch 014 - train 0.51646 | val 1.00748
  Classification -> best τ=0.375 (val F1=0.2173)
  Directional -> Accuracy: 0.4493, MCC: -0.0291, F1: 0.5250

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.61759 | val 0.96455
  Epoch 011 - train 0.59847 | val 1.14515
  Classification -> best τ=0.465 (val F1=0.3146)
  Directional -> Accuracy: 0.6327, MCC: 0.2556, F1: 0.4375

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.61595 | val 0.97268
  Epoch 016 - train 0.49752 | val 1.27414
  Classification -> best τ=0.205 (val F1=0.2157)
  Directional -> Accuracy: 0.5263, MCC: 0.1360, F1: 0.6824

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.50398 | val 1.00341
  Epoch 017 - train 0.39521 | val 1.53751
  Classification -> best τ=0.535 (val F1=0.2205)
  Directional -> Accuracy: 0.5238, MCC: 0.0123, F1: 0.3750

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.59651 | val 1.34242
  Epoch 013 - train 0.54363 | val 1.10256
  Classification -> best τ=0.385 (val F1=0.4601)
  Directional -> Accuracy: 0.5167, MCC: 0.0431, F1: 0.2927

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.58826 | val 0.72648
  Epoch 011 - train 0.56730 | val 0.69891
  Classification -> best τ=0.525 (val F1=0.3390)
  Directional -> Accuracy: 0.6078, MCC: 0.2325, F1: 0.6154

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.55922 | val 1.50456
  Epoch 011 - train 0.55035 | val 1.55808
  Classification -> best τ=0.485 (val F1=0.2662)
  Directional -> Accuracy: 0.5217, MCC: -0.0022, F1: 0.6452

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.55464 | val 1.93479
  Epoch 011 - train 0.52680 | val 2.12137
  Classification -> best τ=0.360 (val F1=0.0057)
  Directional -> Accuracy: 0.6034, MCC: -0.0221, F1: 0.7473

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.61273 | val 0.89585
  Epoch 012 - train 0.54197 | val 0.93518
  Classification -> best τ=0.570 (val F1=0.1087)
  Directional -> Accuracy: 0.3733, MCC: -0.1601, F1: 0.1455

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.66948 | val 0.95312
  Epoch 012 - train 0.53608 | val 1.10949
  Classification -> best τ=0.280 (val F1=0.3099)
  Directional -> Accuracy: 0.5781, MCC: 0.0000, F1: 0.7327

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.56160 | val 1.25755
  Epoch 011 - train 0.49572 | val 1.24803
  Classification -> best τ=0.640 (val F1=0.3062)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.67545 | val 0.76956
  Epoch 014 - train 0.43698 | val 0.94197
  Classification -> best τ=0.445 (val F1=0.2784)
  Directional -> Accuracy: 0.6170, MCC: 0.0000, F1: 0.7632

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.60039 | val 1.02882
  Epoch 012 - train 0.53020 | val 0.98590
  Classification -> best τ=0.565 (val F1=0.2541)
  Directional -> Accuracy: 0.5692, MCC: 0.1742, F1: 0.4167

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.67313 | val 0.68078
  Epoch 018 - train 0.52127 | val 0.63294
  Classification -> best τ=0.445 (val F1=0.6521)
  Directional -> Accuracy: 0.5263, MCC: 0.0688, F1: 0.5263

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.57991 | val 0.91068
  Epoch 011 - train 0.57856 | val 0.90528
  Classification -> best τ=0.600 (val F1=0.1348)
  Directional -> Accuracy: 0.5077, MCC: 0.0251, F1: 0.5429

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.54661 | val 0.99275
  Epoch 011 - train 0.45098 | val 1.06838
  Classification -> best τ=0.430 (val F1=0.4910)
  Directional -> Accuracy: 0.5818, MCC: 0.1913, F1: 0.5490

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.47791 | val 3.59096
  Epoch 011 - train 0.45658 | val 3.53989
  Classification -> best τ=0.615 (val F1=0.3669)
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.5938

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.61699 | val 0.79898
  Epoch 014 - train 0.55139 | val 1.11372
  Classification -> best τ=0.605 (val F1=0.1353)
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.0000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.54747 | val 1.21126
  Epoch 011 - train 0.46308 | val 1.42403
  Classification -> best τ=0.400 (val F1=0.2892)
  Directional -> Accuracy: 0.5000, MCC: 0.2137, F1: 0.1765

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.56359 | val 0.80646
  Epoch 013 - train 0.53314 | val 1.03990
  Classification -> best τ=0.610 (val F1=0.2509)
  Directional -> Accuracy: 0.5250, MCC: 0.0356, F1: 0.5778

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.60948 | val 0.85309
  Epoch 012 - train 0.56946 | val 0.95377
  Classification -> best τ=0.675 (val F1=0.3501)
  Directional -> Accuracy: 0.5000, MCC: -0.0142, F1: 0.4000

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.59933 | val 1.58019
  Epoch 011 - train 0.48696 | val 0.97680
  Classification -> best τ=0.585 (val F1=0.1286)
  Directional -> Accuracy: 0.6429, MCC: 0.3383, F1: 0.5946

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.61932 | val 0.96756
  Epoch 012 - train 0.47463 | val 1.32689
  Classification -> best τ=0.495 (val F1=0.2399)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.59989 | val 0.82085
  Epoch 016 - train 0.48119 | val 0.93816
  Classification -> best τ=0.400 (val F1=0.4246)
  Directional -> Accuracy: 0.5833, MCC: 0.1562, F1: 0.6250

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.50666 | val 1.83691
  Epoch 011 - train 0.49790 | val 1.81879
  Classification -> best τ=0.255 (val F1=0.2324)
  Directional -> Accuracy: 0.5349, MCC: 0.2158, F1: 0.6774

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.58214 | val 1.12981
  Epoch 011 - train 0.56623 | val 1.12633
  Classification -> best τ=0.575 (val F1=0.2249)
  Directional -> Accuracy: 0.4242, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.44056 | val 0.86690
  Epoch 016 - train 0.34244 | val 2.27253
  Classification -> best τ=0.765 (val F1=0.3828)
  Directional -> Accuracy: 0.5476, MCC: 0.1706, F1: 0.3448

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.55520 | val 0.81465
  Epoch 011 - train 0.51221 | val 0.95968
  Classification -> best τ=0.665 (val F1=0.2478)
  Directional -> Accuracy: 0.5714, MCC: 0.1316, F1: 0.2941

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.49606 | val 0.87594
  Epoch 011 - train 0.44403 | val 0.97824
  Classification -> best τ=0.505 (val F1=0.4012)
  Directional -> Accuracy: 0.4783, MCC: -0.0349, F1: 0.5200

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.59184 | val 0.88788
  Epoch 011 - train 0.49093 | val 0.86295
  Classification -> best τ=0.540 (val F1=0.3800)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.55924 | val 1.31807
  Epoch 011 - train 0.49080 | val 1.93995
  Classification -> best τ=0.495 (val F1=0.2102)
  Directional -> Accuracy: 0.4459, MCC: -0.1047, F1: 0.5060

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.62017 | val 0.96821
  Epoch 017 - train 0.51935 | val 0.77219
  Classification -> best τ=0.400 (val F1=0.2668)
  Directional -> Accuracy: 0.5556, MCC: 0.1107, F1: 0.5652

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.34912 | val 2.42375
  Epoch 012 - train 0.35842 | val 2.41729
  Classification -> best τ=0.565 (val F1=0.4423)
  Directional -> Accuracy: 0.5952, MCC: 0.1578, F1: 0.6667

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.46267 | val 1.12631
  Epoch 012 - train 0.43721 | val 0.82484
  Classification -> best τ=0.650 (val F1=0.3752)
  Directional -> Accuracy: 0.5833, MCC: -0.0325, F1: 0.1667

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.65257 | val 0.89644
  Epoch 012 - train 0.60760 | val 1.27714
  Classification -> best τ=0.430 (val F1=0.2291)
  Directional -> Accuracy: 0.5455, MCC: 0.0000, F1: 0.7059

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.51594 | val 2.65712
  Epoch 011 - train 0.46520 | val 3.04405
  Classification -> best τ=0.645 (val F1=0.1502)
  Directional -> Accuracy: 0.5179, MCC: 0.0000, F1: 0.0000

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.64463 | val 0.72507
  Epoch 014 - train 0.55778 | val 0.78411
  Classification -> best τ=0.515 (val F1=0.2728)
  Directional -> Accuracy: 0.5849, MCC: 0.1729, F1: 0.6452

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.54708 | val 3.05293
  Epoch 011 - train 0.50344 | val 3.65960
  Classification -> best τ=0.920 (val F1=0.1605)
  Directional -> Accuracy: 0.4727, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.60409 | val 0.83742

[I 2026-02-22 14:47:45,176] Trial 224 finished with value: 0.27839654745152104 and parameters: {'feature_set': 'sector', 'model_type': 'BiGRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.4, 'batch_size': 16, 'learning_rate': 0.008033734763488953, 'weight_decay': 3.558777031470718e-05, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 1.0237038589936271, 'early_stopping_min_delta': 0.0015953742025585356}. Best is trial 214 with value: 0.2991200218486954.

  Epoch 018 - train 0.53570 | val 0.92209
  Classification -> best τ=0.375 (val F1=0.2723)
  Directional -> Accuracy: 0.5500, MCC: 0.1920, F1: 0.1290

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.27839654745152104
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.61327 | val 0.90920
  Epoch 011 - train 0.56616 | val 1.03848
  Classification -> best τ=0.645 (val F1=0.2919)
  Directional -> Accuracy: 0.5921, MCC: 0.1710, F1: 0.2439

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.51376 | val 1.04548
  Epoch 012 - train 0.46634 | val 1.07493
  Classification -> best τ=0.645 (val F1=0.1323)
  Directional -> Accuracy: 0.5556, MCC: 0.0891, F1: 0.6154

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.49842 | val 2.71262
  Epoch 011 - train 0.58567 | val 3.16683
  Classification -> best τ=0.660 (val F1=0.2311)
  Directional -> Accuracy: 0.4565, MCC: -0.0996, F1: 0.0741

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.60610 | val 1.18574
  Epoch 014 - train 0.51621 | val 0.93876
  Classification -> best τ=0.480 (val F1=0.2593)
  Directional -> Accuracy: 0.5405, MCC: 0.0000, F1: 0.7018

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.53881 | val 1.75117
  Epoch 013 - train 0.48754 | val 1.60249
  Classification -> best τ=0.690 (val F1=0.5415)
  Directional -> Accuracy: 0.6600, MCC: 0.3398, F1: 0.6222

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.53111 | val 0.78294
  Epoch 020 - train 0.38843 | val 0.75468
  Epoch 021 - train 0.33057 | val 0.71743
  Classification -> best τ=0.660 (val F1=0.4513)
  Directional -> Accuracy: 0.5217, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.62989 | val 1.08153
  Epoch 012 - train 0.56595 | val 1.13638
  Classification -> best τ=0.465 (val F1=0.2766)
  Directional -> Accuracy: 0.4559, MCC: 0.0250, F1: 0.5316

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.50221 | val 2.08869
  Epoch 015 - train 0.38382 | val 0.92492
  Classification -> best τ=0.435 (val F1=0.3524)
  Directional -> Accuracy: 0.4762, MCC: -0.1021, F1: 0.3125

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.51931 | val 1.11849
  Epoch 011 - train 0.53679 | val 1.65925
  Classification -> best τ=0.590 (val F1=0.2233)
  Directional -> Accuracy: 0.6042, MCC: 0.2494, F1: 0.6275

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.55962 | val 0.74594
  Epoch 012 - train 0.53597 | val 0.71048
  Classification -> best τ=0.360 (val F1=0.1858)
  Directional -> Accuracy: 0.4348, MCC: -0.0667, F1: 0.5063

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.59192 | val 1.11640
  Epoch 020 - train 0.46249 | val 0.92671
  Epoch 021 - train 0.42372 | val 1.03642
  Classification -> best τ=0.350 (val F1=0.3414)
  Directional -> Accuracy: 0.5714, MCC: 0.1457, F1: 0.5532

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.63590 | val 1.68468
  Epoch 012 - train 0.51880 | val 2.06104
  Classification -> best τ=0.430 (val F1=0.2779)
  Directional -> Accuracy: 0.5088, MCC: 0.0000, F1: 0.6744

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.49737 | val 2.48723
  Epoch 011 - train 0.45779 | val 2.88053
  Classification -> best τ=0.360 (val F1=0.1991)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.6230

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.61236 | val 0.95864
  Epoch 016 - train 0.50893 | val 0.86528
  Classification -> best τ=0.545 (val F1=0.3748)
  Directional -> Accuracy: 0.4667, MCC: -0.1336, F1: 0.0588

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.58369 | val 0.98380
  Epoch 011 - train 0.51884 | val 0.94123
  Classification -> best τ=0.495 (val F1=0.0634)
  Directional -> Accuracy: 0.4510, MCC: 0.0000, F1: 0.6216

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.59941 | val 1.36592
  Epoch 011 - train 0.56835 | val 1.16306
  Classification -> best τ=0.645 (val F1=0.2299)
  Directional -> Accuracy: 0.5217, MCC: 0.0490, F1: 0.5217

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.59277 | val 1.21077
  Epoch 012 - train 0.50697 | val 1.65080
  Classification -> best τ=0.555 (val F1=0.3261)
  Directional -> Accuracy: 0.4138, MCC: 0.1477, F1: 0.1053

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.58021 | val 0.99938
  Epoch 011 - train 0.55167 | val 0.91267
  Classification -> best τ=0.365 (val F1=0.2305)
  Directional -> Accuracy: 0.6000, MCC: 0.0000, F1: 0.7500

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.63852 | val 0.95745
  Epoch 012 - train 0.51562 | val 0.95654
  Classification -> best τ=0.635 (val F1=0.2234)
  Directional -> Accuracy: 0.4375, MCC: -0.1782, F1: 0.5385

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.50588 | val 1.85331
  Epoch 011 - train 0.48369 | val 1.94851
  Classification -> best τ=0.455 (val F1=0.2989)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.60552 | val 1.71635
  Epoch 011 - train 0.50186 | val 1.74492
  Classification -> best τ=0.740 (val F1=0.1383)
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.61179 | val 0.99531
  Epoch 014 - train 0.46388 | val 1.16806
  Classification -> best τ=0.310 (val F1=0.2952)
  Directional -> Accuracy: 0.4923, MCC: -0.0533, F1: 0.6452

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.55321 | val 0.83834
  Epoch 016 - train 0.47327 | val 1.01176
  Classification -> best τ=0.885 (val F1=0.4108)
  Directional -> Accuracy: 0.5263, MCC: 0.1434, F1: 0.4000

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.60196 | val 0.88439
  Epoch 014 - train 0.50065 | val 1.38269
  Classification -> best τ=0.515 (val F1=0.1702)
  Directional -> Accuracy: 0.4769, MCC: -0.0377, F1: 0.5143

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.57353 | val 1.28261
  Epoch 020 - train 0.51679 | val 0.95104
  Epoch 021 - train 0.41729 | val 1.09552
  Classification -> best τ=0.565 (val F1=0.5278)
  Directional -> Accuracy: 0.5636, MCC: 0.2170, F1: 0.4286

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.47463 | val 2.67245
  Epoch 011 - train 0.43632 | val 2.44074
  Classification -> best τ=0.630 (val F1=0.2726)
  Directional -> Accuracy: 0.4444, MCC: -0.0891, F1: 0.4444

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.49871 | val 1.10856
  Epoch 011 - train 0.53987 | val 1.01455
  Classification -> best τ=0.470 (val F1=0.1407)
  Directional -> Accuracy: 0.5476, MCC: 0.0313, F1: 0.6545

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.53436 | val 1.77493
  Epoch 011 - train 0.48875 | val 2.15038
  Classification -> best τ=0.445 (val F1=0.3147)
  Directional -> Accuracy: 0.4464, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.56562 | val 1.36034
  Epoch 016 - train 0.32653 | val 1.40361
  Classification -> best τ=0.560 (val F1=0.3427)
  Directional -> Accuracy: 0.5500, MCC: 0.0422, F1: 0.6786

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.64279 | val 3.20558
  Epoch 012 - train 0.59111 | val 3.12087
  Classification -> best τ=0.580 (val F1=0.3501)
  Directional -> Accuracy: 0.4762, MCC: -0.0754, F1: 0.3125

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.59637 | val 0.86603
  Epoch 011 - train 0.56730 | val 0.85275
  Classification -> best τ=0.480 (val F1=0.0716)
  Directional -> Accuracy: 0.6190, MCC: 0.4065, F1: 0.4667

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.50850 | val 1.09566
  Epoch 011 - train 0.47774 | val 0.90569
  Classification -> best τ=0.300 (val F1=0.2837)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.58884 | val 0.82007
  Epoch 015 - train 0.50628 | val 1.31487
  Classification -> best τ=0.475 (val F1=0.2975)
  Directional -> Accuracy: 0.5694, MCC: 0.1429, F1: 0.5867

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.54227 | val 1.19575
  Epoch 011 - train 0.50940 | val 1.38131
  Classification -> best τ=0.220 (val F1=0.1874)
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.62203 | val 1.44036
  Epoch 015 - train 0.50973 | val 1.92345
  Classification -> best τ=0.360 (val F1=0.3551)
  Directional -> Accuracy: 0.5606, MCC: 0.1048, F1: 0.6133

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.42805 | val 1.08795
  Epoch 012 - train 0.46660 | val 1.51759
  Classification -> best τ=0.435 (val F1=0.2839)
  Directional -> Accuracy: 0.5952, MCC: 0.1907, F1: 0.6047

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.53613 | val 0.94071
  Epoch 012 - train 0.54189 | val 1.07578
  Classification -> best τ=0.485 (val F1=0.2327)
  Directional -> Accuracy: 0.5536, MCC: 0.0862, F1: 0.4186

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.50155 | val 1.03983
  Epoch 011 - train 0.47163 | val 0.99645
  Classification -> best τ=0.490 (val F1=0.3225)
  Directional -> Accuracy: 0.5870, MCC: -0.1195, F1: 0.7397

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.57013 | val 0.85551
  Epoch 016 - train 0.43559 | val 1.58231
  Classification -> best τ=0.535 (val F1=0.4011)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.55045 | val 2.40356
  Epoch 011 - train 0.49264 | val 2.31642
  Classification -> best τ=0.060 (val F1=0.1260)
  Directional -> Accuracy: 0.4865, MCC: 0.0000, F1: 0.6545

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.57786 | val 0.83774
  Epoch 011 - train 0.56402 | val 0.84211
  Classification -> best τ=0.660 (val F1=0.2174)
  Directional -> Accuracy: 0.5111, MCC: 0.0518, F1: 0.2667

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.50400 | val 1.75724
  Epoch 011 - train 0.38858 | val 1.66553
  Classification -> best τ=0.525 (val F1=0.1667)
  Directional -> Accuracy: 0.4286, MCC: -0.2976, F1: 0.5862

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.50495 | val 0.61479
  Epoch 019 - train 0.39026 | val 0.89185
  Classification -> best τ=0.115 (val F1=0.4682)
  Directional -> Accuracy: 0.4583, MCC: 0.2335, F1: 0.5806

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.64396 | val 1.46195
  Epoch 012 - train 0.62130 | val 1.55431
  Classification -> best τ=0.590 (val F1=0.2036)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.48266 | val 2.00760
  Epoch 011 - train 0.44027 | val 1.65827
  Classification -> best τ=0.305 (val F1=0.1883)
  Directional -> Accuracy: 0.5179, MCC: 0.0124, F1: 0.1818

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.63580 | val 0.74078
  Epoch 015 - train 0.55174 | val 0.86100
  Classification -> best τ=0.740 (val F1=0.1668)
  Directional -> Accuracy: 0.6038, MCC: 0.2069, F1: 0.6316

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.51528 | val 2.91126
  Epoch 011 - train 0.48706 | val 3.45257
  Classification -> best τ=0.805 (val F1=0.0580)
  Directional -> Accuracy: 0.4727, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.60361 | val 0.72633
  Epoch 020 - train 0.55427 | val 0.67244

[I 2026-02-22 14:50:35,886] Trial 225 finished with value: 0.2659770050294088 and parameters: {'feature_set': 'sector', 'model_type': 'BiGRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.4, 'batch_size': 16, 'learning_rate': 0.006560819684218345, 'weight_decay': 9.232214925807075e-05, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 0.9961253744410881, 'early_stopping_min_delta': 0.0013716460447458405}. Best is trial 214 with value: 0.2991200218486954.

  Epoch 025 - train 0.41490 | val 0.77445
  Classification -> best τ=0.755 (val F1=0.2623)
  Directional -> Accuracy: 0.5167, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2659770050294088
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.65651 | val 1.17073
  Epoch 011 - train 0.64080 | val 1.16393
  Classification -> best τ=0.695 (val F1=0.2919)
  Directional -> Accuracy: 0.5658, MCC: 0.1283, F1: 0.0571

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.60075 | val 0.82695
  Epoch 020 - train 0.44409 | val 1.07167
  Epoch 026 - train 0.41435 | val 1.54643
  Classification -> best τ=0.285 (val F1=0.1289)
  Directional -> Accuracy: 0.6000, MCC: 0.1323, F1: 0.7353

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.56839 | val 0.95453
  Epoch 011 - train 0.54029 | val 0.96117
  Classification -> best τ=0.595 (val F1=0.2793)
  Directional -> Accuracy: 0.4783, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.59009 | val 0.74844
  Epoch 014 - train 0.54525 | val 0.75290
  Classification -> best τ=0.480 (val F1=0.1042)
  Directional -> Accuracy: 0.5135, MCC: 0.0206, F1: 0.5500

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.51879 | val 1.63508
  Epoch 011 - train 0.54293 | val 2.11523
  Classification -> best τ=0.765 (val F1=0.4851)
  Directional -> Accuracy: 0.6200, MCC: 0.2573, F1: 0.5778

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.58258 | val 0.73219
  Epoch 013 - train 0.51364 | val 0.98924
  Classification -> best τ=0.545 (val F1=0.4039)
  Directional -> Accuracy: 0.5217, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.58487 | val 1.09143
  Epoch 011 - train 0.57208 | val 0.96351
  Classification -> best τ=0.400 (val F1=0.1783)
  Directional -> Accuracy: 0.4412, MCC: 0.0509, F1: 0.5581

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.52946 | val 0.66696
  Epoch 017 - train 0.40362 | val 1.21614
  Classification -> best τ=0.190 (val F1=0.4215)
  Directional -> Accuracy: 0.5476, MCC: 0.1635, F1: 0.5957

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.55399 | val 1.02972
  Epoch 011 - train 0.51888 | val 1.38648
  Classification -> best τ=0.575 (val F1=0.3433)
  Directional -> Accuracy: 0.5833, MCC: 0.1302, F1: 0.4444

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.56033 | val 0.75991
  Epoch 012 - train 0.48531 | val 0.91628
  Classification -> best τ=0.610 (val F1=0.1967)
  Directional -> Accuracy: 0.5507, MCC: 0.1004, F1: 0.5079

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.59018 | val 0.85228
  Epoch 011 - train 0.53334 | val 1.20506
  Classification -> best τ=0.480 (val F1=0.2997)
  Directional -> Accuracy: 0.5918, MCC: 0.1804, F1: 0.2308

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.55497 | val 1.35020
  Epoch 012 - train 0.56773 | val 1.53594
  Classification -> best τ=0.485 (val F1=0.2258)
  Directional -> Accuracy: 0.5088, MCC: 0.0000, F1: 0.6744

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.47814 | val 2.08644
  Epoch 011 - train 0.48743 | val 2.38218
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.6230

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.61580 | val 0.89992
  Epoch 011 - train 0.57249 | val 1.21243
  Classification -> best τ=0.530 (val F1=0.3642)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.61516 | val 0.70918
  Epoch 013 - train 0.54830 | val 0.73249
  Classification -> best τ=0.530 (val F1=0.1843)
  Directional -> Accuracy: 0.5490, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.59969 | val 1.11087
  Epoch 011 - train 0.56673 | val 1.67612
  Classification -> best τ=0.735 (val F1=0.2474)
  Directional -> Accuracy: 0.5362, MCC: 0.2162, F1: 0.2727

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.62224 | val 0.99660
  Epoch 012 - train 0.53334 | val 1.04379
  Classification -> best τ=0.635 (val F1=0.2276)
  Directional -> Accuracy: 0.3966, MCC: 0.1035, F1: 0.0541

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.63667 | val 0.77809
  Epoch 012 - train 0.58684 | val 0.80252
  Classification -> best τ=0.600 (val F1=0.1909)
  Directional -> Accuracy: 0.4000, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.55876 | val 0.72738
  Epoch 013 - train 0.57254 | val 0.73764
  Classification -> best τ=0.300 (val F1=0.3385)
  Directional -> Accuracy: 0.5312, MCC: -0.0123, F1: 0.6429

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.56827 | val 1.16508
  Epoch 011 - train 0.50833 | val 1.14087
  Classification -> best τ=0.570 (val F1=0.1839)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.56618 | val 0.78492
  Epoch 012 - train 0.50787 | val 0.76561
  Classification -> best τ=0.665 (val F1=0.2449)
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.60889 | val 1.25838
  Epoch 012 - train 0.57924 | val 1.36243
  Classification -> best τ=0.720 (val F1=0.2830)
  Directional -> Accuracy: 0.4923, MCC: -0.0027, F1: 0.0571

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.62082 | val 0.72224
  Epoch 020 - train 0.58014 | val 1.19310
  Epoch 021 - train 0.54858 | val 1.17857
  Classification -> best τ=0.365 (val F1=0.5060)
  Directional -> Accuracy: 0.6140, MCC: 0.2162, F1: 0.6562

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.61725 | val 1.06045
  Epoch 014 - train 0.53877 | val 0.78726
  Classification -> best τ=0.500 (val F1=0.1778)
  Directional -> Accuracy: 0.4923, MCC: -0.0402, F1: 0.3265

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.59596 | val 0.91759
  Epoch 012 - train 0.58210 | val 1.08253
  Classification -> best τ=0.385 (val F1=0.4207)
  Directional -> Accuracy: 0.5636, MCC: 0.1587, F1: 0.5200

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.53170 | val 2.92351
  Epoch 011 - train 0.52837 | val 2.71375
  Classification -> best τ=0.845 (val F1=0.2726)
  Directional -> Accuracy: 0.3778, MCC: -0.3463, F1: 0.1250

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.61060 | val 0.72323
  Epoch 020 - train 0.54367 | val 0.69192
  Epoch 022 - train 0.47465 | val 1.11026
  Classification -> best τ=0.645 (val F1=0.3873)
  Directional -> Accuracy: 0.5952, MCC: 0.1340, F1: 0.7018

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.56303 | val 1.34741
  Epoch 012 - train 0.49088 | val 1.70936
  Classification -> best τ=0.645 (val F1=0.2742)
  Directional -> Accuracy: 0.4464, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.47332 | val 0.79563
  Epoch 016 - train 0.53102 | val 0.90554
  Classification -> best τ=0.670 (val F1=0.2774)
  Directional -> Accuracy: 0.5250, MCC: 0.0161, F1: 0.6122

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.61347 | val 1.12242
  Epoch 013 - train 0.49780 | val 1.00048
  Classification -> best τ=0.550 (val F1=0.3630)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.4878

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.56848 | val 1.26429
  Epoch 012 - train 0.48895 | val 1.63603
  Classification -> best τ=0.435 (val F1=0.3034)
  Directional -> Accuracy: 0.5476, MCC: 0.0000, F1: 0.7077

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.55036 | val 0.76269
  Epoch 018 - train 0.41089 | val 1.11801
  Classification -> best τ=0.360 (val F1=0.3802)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.60000 | val 0.73631
  Epoch 017 - train 0.50750 | val 1.23682
  Classification -> best τ=0.485 (val F1=0.3117)
  Directional -> Accuracy: 0.5278, MCC: 0.0905, F1: 0.4848

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.54025 | val 1.61313
  Epoch 011 - train 0.48163 | val 1.87989
  Classification -> best τ=0.395 (val F1=0.2845)
  Directional -> Accuracy: 0.4884, MCC: -0.0849, F1: 0.0833

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.58294 | val 1.09685
  Epoch 011 - train 0.57696 | val 1.25091
  Classification -> best τ=0.470 (val F1=0.2778)
  Directional -> Accuracy: 0.5758, MCC: 0.0000, F1: 0.7308

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.52154 | val 2.09632
  Epoch 011 - train 0.42090 | val 2.03741
  Classification -> best τ=0.555 (val F1=0.1970)
  Directional -> Accuracy: 0.6190, MCC: 0.2864, F1: 0.5294

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.52388 | val 1.12102
  Epoch 012 - train 0.50517 | val 0.80150
  Classification -> best τ=0.675 (val F1=0.2478)
  Directional -> Accuracy: 0.5536, MCC: 0.0812, F1: 0.2424

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.52600 | val 1.15396
  Epoch 011 - train 0.46418 | val 1.48824
  Classification -> best τ=0.510 (val F1=0.2659)
  Directional -> Accuracy: 0.3913, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.54899 | val 0.69625
  Epoch 012 - train 0.49662 | val 0.72063
  Classification -> best τ=0.370 (val F1=0.4625)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.61443 | val 0.87717
  Epoch 012 - train 0.53425 | val 1.66689
  Classification -> best τ=0.525 (val F1=0.3081)
  Directional -> Accuracy: 0.5541, MCC: 0.1052, F1: 0.5075

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.65915 | val 0.78530
  Epoch 017 - train 0.48940 | val 1.42162
  Classification -> best τ=0.440 (val F1=0.3371)
  Directional -> Accuracy: 0.4222, MCC: -0.1613, F1: 0.2778

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.43587 | val 1.05928
  Epoch 011 - train 0.42036 | val 1.46260
  Classification -> best τ=0.650 (val F1=0.4523)
  Directional -> Accuracy: 0.4524, MCC: -0.0574, F1: 0.4103

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.52337 | val 0.92519
  Epoch 015 - train 0.38313 | val 1.28974
  Classification -> best τ=0.640 (val F1=0.4795)
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.5455

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.66263 | val 1.87775
  Epoch 012 - train 0.62026 | val 1.36474
  Classification -> best τ=0.465 (val F1=0.2036)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.51546 | val 2.66459
  Epoch 011 - train 0.45061 | val 3.14834
  Classification -> best τ=0.665 (val F1=0.1502)
  Directional -> Accuracy: 0.5179, MCC: 0.0000, F1: 0.0000

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.65098 | val 1.15471
  Epoch 015 - train 0.61779 | val 0.86601
  Classification -> best τ=0.590 (val F1=0.0750)
  Directional -> Accuracy: 0.5849, MCC: 0.1695, F1: 0.5926

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.58311 | val 3.66196
  Epoch 012 - train 0.47810 | val 3.40470
  Classification -> best τ=0.420 (val F1=0.1647)
  Directional -> Accuracy: 0.5273, MCC: 0.0000, F1: 0.6905

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.60263 | val 0.66910
  Epoch 020 - train 0.57895 | val 0.77574

[I 2026-02-22 14:53:26,068] Trial 226 finished with value: 0.28169926733852746 and parameters: {'feature_set': 'sector', 'model_type': 'BiGRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.4, 'batch_size': 16, 'learning_rate': 0.009963138528216163, 'weight_decay': 0.00012925037740687398, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 0.9075037393134455, 'early_stopping_min_delta': 0.0010597906424790454}. Best is trial 214 with value: 0.2991200218486954.

  Epoch 030 - train 0.45798 | val 1.13163
  Classification -> best τ=0.380 (val F1=0.3177)
  Directional -> Accuracy: 0.5667, MCC: 0.1451, F1: 0.3500

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.28169926733852746
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down', 'finbert_neutral']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.63692 | val 0.74442
  Epoch 012 - train 0.60043 | val 0.77564
  Classification -> best τ=0.535 (val F1=0.2510)
  Directional -> Accuracy: 0.5263, MCC: -0.0499, F1: 0.1429

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.64683 | val 1.20831
  Epoch 012 - train 0.49549 | val 1.17223
  Classification -> best τ=0.295 (val F1=0.1273)
  Directional -> Accuracy: 0.5778, MCC: 0.0000, F1: 0.7324

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.52804 | val 0.96262
  Epoch 011 - train 0.47017 | val 0.89650
  Classification -> best τ=0.545 (val F1=0.3313)
  Directional -> Accuracy: 0.4783, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.64867 | val 1.22424
  Epoch 020 - train 0.53308 | val 0.69171
  Epoch 030 - train 0.34048 | val 0.79314
  Classification -> best τ=0.615 (val F1=0.1895)
  Directional -> Accuracy: 0.4595, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.45886 | val 0.99081
  Epoch 012 - train 0.40187 | val 1.12923
  Classification -> best τ=0.410 (val F1=0.3641)
  Directional -> Accuracy: 0.7000, MCC: 0.4120, F1: 0.6809

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.58247 | val 0.70622
  Epoch 016 - train 0.44057 | val 1.14032
  Classification -> best τ=0.410 (val F1=0.2593)
  Directional -> Accuracy: 0.6087, MCC: 0.2241, F1: 0.4706

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.62872 | val 0.90844
  Epoch 012 - train 0.54985 | val 0.95413
  Classification -> best τ=0.520 (val F1=0.2179)
  Directional -> Accuracy: 0.5294, MCC: 0.1521, F1: 0.5676

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.36572 | val 1.09027
  Epoch 014 - train 0.29693 | val 1.69595
  Classification -> best τ=0.535 (val F1=0.5247)
  Directional -> Accuracy: 0.5000, MCC: 0.1698, F1: 0.6182

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.51785 | val 2.03856
  Epoch 011 - train 0.45049 | val 2.53755
  Classification -> best τ=0.530 (val F1=0.3616)
  Directional -> Accuracy: 0.7292, MCC: 0.5071, F1: 0.5517

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.53518 | val 1.25456
  Epoch 011 - train 0.51932 | val 1.47570
  Classification -> best τ=0.455 (val F1=0.2083)
  Directional -> Accuracy: 0.5072, MCC: 0.0562, F1: 0.5278

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.66710 | val 0.74916
  Epoch 020 - train 0.53839 | val 0.67927
  Epoch 021 - train 0.43284 | val 0.68104
  Classification -> best τ=0.470 (val F1=0.3493)
  Directional -> Accuracy: 0.5510, MCC: 0.0212, F1: 0.0833

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.67089 | val 0.95801
  Epoch 013 - train 0.54211 | val 1.36788
  Classification -> best τ=0.655 (val F1=0.2428)
  Directional -> Accuracy: 0.5965, MCC: 0.1933, F1: 0.6349

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.45371 | val 1.42432
  Epoch 011 - train 0.38459 | val 1.43720
  Classification -> best τ=0.555 (val F1=0.1225)
  Directional -> Accuracy: 0.5238, MCC: -0.1419, F1: 0.0000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.66265 | val 2.32479
  Epoch 012 - train 0.60616 | val 1.53312
  Classification -> best τ=0.510 (val F1=0.3833)
  Directional -> Accuracy: 0.6000, MCC: 0.2075, F1: 0.5385

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.55772 | val 0.82346
  Epoch 011 - train 0.51683 | val 1.71599
  Classification -> best τ=0.585 (val F1=0.2141)
  Directional -> Accuracy: 0.5490, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.60020 | val 1.16484
  Epoch 011 - train 0.58168 | val 1.48877
  Classification -> best τ=0.375 (val F1=0.2604)
  Directional -> Accuracy: 0.5217, MCC: -0.0237, F1: 0.6667

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.60622 | val 3.36282
  Epoch 012 - train 0.53592 | val 2.88670
  Classification -> best τ=0.880 (val F1=0.1137)
  Directional -> Accuracy: 0.4310, MCC: 0.1826, F1: 0.1538

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.64109 | val 0.89225
  Epoch 011 - train 0.60060 | val 1.39593
  Classification -> best τ=0.310 (val F1=0.1243)
  Directional -> Accuracy: 0.6000, MCC: 0.0000, F1: 0.7500

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.62730 | val 0.79483
  Epoch 016 - train 0.53339 | val 0.82437
  Classification -> best τ=0.440 (val F1=0.3426)
  Directional -> Accuracy: 0.4688, MCC: -0.0785, F1: 0.5278

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.56935 | val 0.87674
  Epoch 011 - train 0.51989 | val 1.09651
  Classification -> best τ=0.540 (val F1=0.2639)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.65135 | val 1.38218
  Epoch 011 - train 0.57567 | val 1.83136
  Classification -> best τ=0.665 (val F1=0.2416)
  Directional -> Accuracy: 0.5745, MCC: -0.1661, F1: 0.7297

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.65193 | val 1.93842
  Epoch 013 - train 0.61752 | val 4.54041
  Classification -> best τ=0.205 (val F1=0.2673)
  Directional -> Accuracy: 0.5077, MCC: 0.0152, F1: 0.5152

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.67530 | val 1.76671
  Epoch 015 - train 0.49010 | val 1.86905
  Classification -> best τ=0.620 (val F1=0.3370)
  Directional -> Accuracy: 0.5439, MCC: 0.1093, F1: 0.5357

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.59753 | val 1.33284
  Epoch 012 - train 0.53284 | val 1.18451
  Classification -> best τ=0.415 (val F1=0.1878)
  Directional -> Accuracy: 0.5385, MCC: 0.1702, F1: 0.6591

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.55320 | val 1.20786
  Epoch 011 - train 0.50814 | val 1.55187
  Classification -> best τ=0.485 (val F1=0.1660)
  Directional -> Accuracy: 0.5455, MCC: 0.1491, F1: 0.4444

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.40836 | val 7.60290
  Epoch 011 - train 0.37144 | val 8.54240
  Classification -> best τ=0.775 (val F1=0.2935)
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.5938

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.55129 | val 0.76631
  Epoch 011 - train 0.54496 | val 0.73424
  Classification -> best τ=0.600 (val F1=0.2582)
  Directional -> Accuracy: 0.5952, MCC: 0.1291, F1: 0.7119

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.48429 | val 2.45125
  Epoch 011 - train 0.48886 | val 2.68661
  Classification -> best τ=0.560 (val F1=0.0344)
  Directional -> Accuracy: 0.4107, MCC: -0.1511, F1: 0.3265

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.54089 | val 0.97432
  Epoch 011 - train 0.43480 | val 1.28582
  Classification -> best τ=0.580 (val F1=0.2774)
  Directional -> Accuracy: 0.4500, MCC: -0.0909, F1: 0.4500

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.58225 | val 1.40644
  Epoch 020 - train 0.34117 | val 0.80326
  Epoch 025 - train 0.27135 | val 1.23180
  Classification -> best τ=0.400 (val F1=0.5331)
  Directional -> Accuracy: 0.4524, MCC: -0.0853, F1: 0.5818

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.63993 | val 1.35312
  Epoch 012 - train 0.54676 | val 1.24154
  Classification -> best τ=0.420 (val F1=0.3385)
  Directional -> Accuracy: 0.5476, MCC: 0.0310, F1: 0.6885

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.51321 | val 1.06420
  Epoch 012 - train 0.42807 | val 1.38498
  Classification -> best τ=0.395 (val F1=0.4467)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.61164 | val 0.99467
  Epoch 018 - train 0.52757 | val 1.07613
  Classification -> best τ=0.415 (val F1=0.3287)
  Directional -> Accuracy: 0.5278, MCC: 0.1291, F1: 0.4138

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.55197 | val 2.17933
  Epoch 011 - train 0.54582 | val 2.87800
  Classification -> best τ=0.795 (val F1=0.1818)
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.53336 | val 1.57840
  Epoch 011 - train 0.48260 | val 1.83627
  Classification -> best τ=0.520 (val F1=0.0860)
  Directional -> Accuracy: 0.5758, MCC: 0.0271, F1: 0.7255

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.55722 | val 2.09972
  Epoch 013 - train 0.44596 | val 1.72331
  Classification -> best τ=0.345 (val F1=0.4073)
  Directional -> Accuracy: 0.5714, MCC: 0.1357, F1: 0.6538

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.46683 | val 1.40661
  Epoch 011 - train 0.44753 | val 1.40144
  Classification -> best τ=0.360 (val F1=0.1951)
  Directional -> Accuracy: 0.4643, MCC: -0.0716, F1: 0.4444

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.67387 | val 0.86981
  Epoch 017 - train 0.37561 | val 1.22726
  Classification -> best τ=0.365 (val F1=0.5821)
  Directional -> Accuracy: 0.6087, MCC: 0.1323, F1: 0.7097

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.43678 | val 0.80834
  Epoch 011 - train 0.43141 | val 0.89590
  Classification -> best τ=0.495 (val F1=0.4242)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.60209 | val 1.09711
  Epoch 011 - train 0.54694 | val 1.12269
  Classification -> best τ=0.575 (val F1=0.3235)
  Directional -> Accuracy: 0.5676, MCC: 0.1327, F1: 0.5294

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.54894 | val 0.68859
  Epoch 019 - train 0.37917 | val 1.71921
  Classification -> best τ=0.725 (val F1=0.3953)
  Directional -> Accuracy: 0.5333, MCC: 0.0672, F1: 0.5333

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.42309 | val 2.08434
  Epoch 011 - train 0.41943 | val 2.40599
  Classification -> best τ=0.480 (val F1=0.2381)
  Directional -> Accuracy: 0.4286, MCC: -0.1376, F1: 0.4545

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.59183 | val 0.51463
  Epoch 020 - train 0.31900 | val 0.91660
  Epoch 023 - train 0.29260 | val 0.89751
  Classification -> best τ=0.205 (val F1=0.6080)
  Directional -> Accuracy: 0.3750, MCC: -0.0538, F1: 0.5312

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.59998 | val 1.86322
  Epoch 012 - train 0.56714 | val 1.86270
  Classification -> best τ=0.510 (val F1=0.1605)
  Directional -> Accuracy: 0.5455, MCC: 0.0177, F1: 0.6988

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.58553 | val 1.74681
  Epoch 011 - train 0.51845 | val 1.73557
  Classification -> best τ=0.455 (val F1=0.0985)
  Directional -> Accuracy: 0.4286, MCC: -0.1399, F1: 0.4483

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.61224 | val 1.22291
  Epoch 011 - train 0.52567 | val 1.61818
  Classification -> best τ=0.720 (val F1=0.2064)
  Directional -> Accuracy: 0.4906, MCC: 0.0000, F1: 0.0000

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.55156 | val 3.63152
  Epoch 011 - train 0.50279 | val 4.87550
  Classification -> best τ=0.795 (val F1=0.1154)
  Directional -> Accuracy: 0.5273, MCC: 0.0000, F1: 0.6905

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.59974 | val 1.04891

[I 2026-02-22 14:56:10,624] Trial 227 finished with value: 0.27698026889433197 and parameters: {'feature_set': 'finbert', 'model_type': 'BiGRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.4, 'batch_size': 16, 'learning_rate': 0.009981133249052882, 'weight_decay': 0.00013602826015752815, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 0.43624943920965775, 'early_stopping_min_delta': 0.0011006223142960125}. Best is trial 214 with value: 0.2991200218486954.

  Epoch 019 - train 0.49502 | val 0.70043
  Classification -> best τ=0.515 (val F1=0.3108)
  Directional -> Accuracy: 0.6000, MCC: 0.3117, F1: 0.2941

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.27698026889433197
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d', 'sentiment', 'emotion_anger', 'emotion_disgust', 'emotion_fear', 'emotion_joy', 'emotion_neutral', 'emotion_sadness', 'emotion_surprize', 'emotion_anger_pct', 'emotion_disgust_pct', 'emotion_fear_pct', 'emotion_joy_pct', 'emotion_neutral_pct', 'emotion_sadness_pct', 'emotion_surprize_pct', 'positive_emotion', 'negative_emotion', 'uncertainty_emotion', 'positive_emotion_pct', 'negative_emotion_pct', 'uncertainty_emotion_pct', 'stance_label', 'stance_score', 'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down', 'finbert_neutral']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.48535 | val 1.08323
  Epoch 012 - train 0.35104 | val 1.24442
  Classification -> best τ=0.885 (val F1=0.2510)
  Directional -> Accuracy: 0.5658, MCC: 0.1283, F1: 0.0571

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.43556 | val 0.86817
  Epoch 012 - train 0.20221 | val 1.45974
  Classification -> best τ=0.590 (val F1=0.1350)
  Directional -> Accuracy: 0.6667, MCC: 0.3123, F1: 0.7170

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.35067 | val 2.68945
  Epoch 011 - train 0.23924 | val 3.05260
  Classification -> best τ=0.625 (val F1=0.2559)
  Directional -> Accuracy: 0.4565, MCC: -0.0790, F1: 0.1935

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.45138 | val 2.79165
  Epoch 011 - train 0.31739 | val 3.70761
  Classification -> best τ=0.275 (val F1=0.1269)
  Directional -> Accuracy: 0.5405, MCC: 0.0000, F1: 0.7018

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.25003 | val 3.95662
  Epoch 011 - train 0.18002 | val 4.82200
  Classification -> best τ=0.410 (val F1=0.3307)
  Directional -> Accuracy: 0.7400, MCC: 0.4804, F1: 0.7451

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.24990 | val 1.72264
  Epoch 011 - train 0.13872 | val 2.00756
  Classification -> best τ=0.635 (val F1=0.2593)
  Directional -> Accuracy: 0.5217, MCC: 0.0382, F1: 0.4762

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.39487 | val 1.49074
  Epoch 011 - train 0.26400 | val 1.66210
  Classification -> best τ=0.295 (val F1=0.2462)
  Directional -> Accuracy: 0.5441, MCC: 0.1940, F1: 0.5867

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.34364 | val 1.69395
  Epoch 017 - train 0.14187 | val 1.25930
  Classification -> best τ=0.185 (val F1=0.5541)
  Directional -> Accuracy: 0.6190, MCC: 0.1936, F1: 0.4286

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.29927 | val 1.91241
  Epoch 011 - train 0.22368 | val 2.59769
  Classification -> best τ=0.740 (val F1=0.1928)
  Directional -> Accuracy: 0.5208, MCC: -0.1839, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.47577 | val 0.83161
  Epoch 011 - train 0.29610 | val 0.92207
  Classification -> best τ=0.735 (val F1=0.1983)
  Directional -> Accuracy: 0.5217, MCC: 0.0324, F1: 0.4590

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.26186 | val 2.66327
  Epoch 011 - train 0.21843 | val 3.25315
  Classification -> best τ=0.625 (val F1=0.2187)
  Directional -> Accuracy: 0.5714, MCC: 0.1376, F1: 0.5333

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.42602 | val 1.19129
  Epoch 012 - train 0.25311 | val 1.64875
  Classification -> best τ=0.625 (val F1=0.2230)
  Directional -> Accuracy: 0.5439, MCC: 0.0957, F1: 0.4800

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.24282 | val 1.82415
  Epoch 011 - train 0.19954 | val 2.18231
  Classification -> best τ=0.535 (val F1=0.0548)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.6230

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.39792 | val 1.08574
  Epoch 012 - train 0.24650 | val 0.87914
  Classification -> best τ=0.535 (val F1=0.3126)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.31248 | val 1.17416
  Epoch 011 - train 0.20081 | val 1.46550
  Classification -> best τ=0.565 (val F1=0.3219)
  Directional -> Accuracy: 0.4510, MCC: -0.1278, F1: 0.3333

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.37787 | val 3.29042
  Epoch 011 - train 0.36433 | val 2.90510
  Classification -> best τ=0.770 (val F1=0.1385)
  Directional -> Accuracy: 0.4638, MCC: 0.0000, F1: 0.0000

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.37792 | val 1.20623
  Epoch 012 - train 0.28377 | val 1.18334
  Classification -> best τ=0.220 (val F1=0.1336)
  Directional -> Accuracy: 0.6207, MCC: 0.0000, F1: 0.7660

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.45170 | val 1.11400
  Epoch 011 - train 0.37674 | val 1.24986
  Classification -> best τ=0.420 (val F1=0.2004)
  Directional -> Accuracy: 0.5200, MCC: 0.0219, F1: 0.5814

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.30193 | val 1.50357
  Epoch 011 - train 0.17753 | val 1.55559
  Classification -> best τ=0.600 (val F1=0.1910)
  Directional -> Accuracy: 0.5625, MCC: 0.1927, F1: 0.5172

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.33678 | val 1.22491
  Epoch 011 - train 0.25376 | val 1.66765
  Classification -> best τ=0.215 (val F1=0.1566)
  Directional -> Accuracy: 0.5541, MCC: 0.0000, F1: 0.7130

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.25103 | val 1.63540
  Epoch 011 - train 0.15216 | val 1.97603
  Classification -> best τ=0.515 (val F1=0.1455)
  Directional -> Accuracy: 0.4894, MCC: 0.1609, F1: 0.3684

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.35786 | val 1.12531
  Epoch 018 - train 0.11989 | val 1.11340
  Classification -> best τ=0.270 (val F1=0.3858)
  Directional -> Accuracy: 0.5077, MCC: 0.0443, F1: 0.2000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.40551 | val 0.88238
  Epoch 012 - train 0.27763 | val 1.21696
  Classification -> best τ=0.625 (val F1=0.4766)
  Directional -> Accuracy: 0.5088, MCC: 0.1095, F1: 0.3636

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.48106 | val 0.89199
  Epoch 014 - train 0.24441 | val 2.11855
  Classification -> best τ=0.490 (val F1=0.2111)
  Directional -> Accuracy: 0.5692, MCC: 0.1327, F1: 0.5172

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.41293 | val 1.04005
  Epoch 012 - train 0.24845 | val 1.60371
  Classification -> best τ=0.360 (val F1=0.3750)
  Directional -> Accuracy: 0.5455, MCC: 0.1365, F1: 0.4681

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.16499 | val 4.77029
  Epoch 011 - train 0.14060 | val 5.25034
  Classification -> best τ=0.555 (val F1=0.2035)
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.5938

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.21159 | val 1.21320
  Epoch 012 - train 0.15576 | val 1.52949
  Classification -> best τ=0.555 (val F1=0.3717)
  Directional -> Accuracy: 0.4286, MCC: -0.0468, F1: 0.1429

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.33100 | val 1.62824
  Epoch 011 - train 0.24232 | val 2.05846
  Classification -> best τ=0.510 (val F1=0.1778)
  Directional -> Accuracy: 0.4464, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.24107 | val 2.49700
  Epoch 013 - train 0.09505 | val 2.36378
  Classification -> best τ=0.565 (val F1=0.2403)
  Directional -> Accuracy: 0.5250, MCC: 0.0056, F1: 0.6275

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.18561 | val 1.22395
  Epoch 011 - train 0.13256 | val 1.45279
  Classification -> best τ=0.530 (val F1=0.2764)
  Directional -> Accuracy: 0.4524, MCC: -0.0853, F1: 0.5106

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.24579 | val 1.54168
  Epoch 011 - train 0.24755 | val 2.48905
  Classification -> best τ=0.705 (val F1=0.2298)
  Directional -> Accuracy: 0.4762, MCC: 0.0663, F1: 0.1538

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.37505 | val 1.99282
  Epoch 012 - train 0.18250 | val 2.37800
  Classification -> best τ=0.455 (val F1=0.2976)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.35484 | val 0.88570
  Epoch 013 - train 0.19953 | val 1.09222
  Classification -> best τ=0.325 (val F1=0.3816)
  Directional -> Accuracy: 0.5556, MCC: 0.0337, F1: 0.6981

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.24058 | val 2.82673
  Epoch 011 - train 0.16813 | val 2.97065
  Classification -> best τ=0.660 (val F1=0.1599)
  Directional -> Accuracy: 0.4651, MCC: -0.0664, F1: 0.5106

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.31920 | val 2.27009
  Epoch 011 - train 0.29034 | val 1.84157
  Classification -> best τ=0.465 (val F1=0.2410)
  Directional -> Accuracy: 0.5909, MCC: 0.2749, F1: 0.5263

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.22879 | val 2.04733
  Epoch 011 - train 0.10083 | val 2.01646
  Classification -> best τ=0.470 (val F1=0.3001)
  Directional -> Accuracy: 0.6905, MCC: 0.3786, F1: 0.7111

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.38668 | val 0.99990
  Epoch 012 - train 0.24026 | val 1.18715
  Classification -> best τ=0.435 (val F1=0.1802)
  Directional -> Accuracy: 0.4643, MCC: -0.1536, F1: 0.1667

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.29219 | val 1.72886
  Epoch 011 - train 0.20646 | val 1.26263
  Classification -> best τ=0.510 (val F1=0.3105)
  Directional -> Accuracy: 0.5217, MCC: -0.0244, F1: 0.6207

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.23588 | val 3.29937
  Epoch 011 - train 0.14493 | val 3.31950
  Classification -> best τ=0.730 (val F1=0.4710)
  Directional -> Accuracy: 0.4792, MCC: 0.1654, F1: 0.5455

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.38833 | val 2.64025
  Epoch 011 - train 0.27693 | val 3.34699
  Classification -> best τ=0.385 (val F1=0.3199)
  Directional -> Accuracy: 0.4595, MCC: -0.1053, F1: 0.2857

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.35507 | val 2.33920
  Epoch 012 - train 0.12002 | val 2.08487
  Classification -> best τ=0.390 (val F1=0.2697)
  Directional -> Accuracy: 0.4889, MCC: -0.0314, F1: 0.5660

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.18507 | val 2.27294
  Epoch 012 - train 0.11607 | val 2.99454
  Classification -> best τ=0.350 (val F1=0.2408)
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.7273

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.21296 | val 1.39111
  Epoch 011 - train 0.14821 | val 2.05631
  Classification -> best τ=0.455 (val F1=0.1371)
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.5455

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.39933 | val 0.82957
  Epoch 011 - train 0.27034 | val 1.19358
  Classification -> best τ=0.510 (val F1=0.1383)
  Directional -> Accuracy: 0.4909, MCC: 0.0659, F1: 0.2632

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.23723 | val 3.50626
  Epoch 011 - train 0.18184 | val 3.99362
  Classification -> best τ=0.470 (val F1=0.3236)
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.6506

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.38746 | val 1.33416
  Epoch 011 - train 0.28759 | val 1.46540
  Classification -> best τ=0.400 (val F1=0.0616)
  Directional -> Accuracy: 0.5849, MCC: 0.2188, F1: 0.6944

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.31297 | val 4.81354
  Epoch 013 - train 0.17657 | val 3.67977
  Classification -> best τ=0.670 (val F1=0.2283)
  Directional -> Accuracy: 0.5455, MCC: 0.0728, F1: 0.6575

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.48784 | val 0.83790

[I 2026-02-22 14:58:39,887] Trial 228 finished with value: 0.2494917318713332 and parameters: {'feature_set': 'sector_all_nlp', 'model_type': 'BiGRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.4, 'batch_size': 16, 'learning_rate': 0.00828835568302006, 'weight_decay': 4.336498994846773e-05, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 0.9332547522440034, 'early_stopping_min_delta': 0.0012287235987896781}. Best is trial 214 with value: 0.2991200218486954.

  Epoch 016 - train 0.30507 | val 1.45725
  Classification -> best τ=0.415 (val F1=0.3195)
  Directional -> Accuracy: 0.5667, MCC: 0.2372, F1: 0.1875

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2494917318713332
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.62662 | val 2.15100
  Epoch 011 - train 0.57094 | val 2.14744
  Classification -> best τ=0.370 (val F1=0.1794)
  Directional -> Accuracy: 0.5658, MCC: 0.1895, F1: 0.6207

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.54005 | val 0.72020
  Epoch 011 - train 0.51370 | val 0.70687
  Classification -> best τ=0.380 (val F1=0.3126)
  Directional -> Accuracy: 0.5556, MCC: -0.0159, F1: 0.6970

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.59748 | val 1.25865
  Epoch 013 - train 0.50013 | val 1.41693
  Classification -> best τ=0.730 (val F1=0.3237)
  Directional -> Accuracy: 0.4783, MCC: -0.0134, F1: 0.1429

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.61613 | val 0.94602
  Epoch 020 - train 0.43347 | val 1.30709
  Epoch 021 - train 0.42892 | val 1.63556
  Classification -> best τ=0.585 (val F1=0.2204)
  Directional -> Accuracy: 0.4595, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.54195 | val 2.40324
  Epoch 011 - train 0.50954 | val 2.58573
  Classification -> best τ=0.530 (val F1=0.4414)
  Directional -> Accuracy: 0.6200, MCC: 0.2378, F1: 0.6415

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.46625 | val 0.83894
  Epoch 020 - train 0.47796 | val 0.77947
  Epoch 023 - train 0.41712 | val 0.83329
  Classification -> best τ=0.470 (val F1=0.5108)
  Directional -> Accuracy: 0.5217, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.66243 | val 1.13846
  Epoch 012 - train 0.55256 | val 1.33332
  Classification -> best τ=0.570 (val F1=0.2236)
  Directional -> Accuracy: 0.5000, MCC: 0.0313, F1: 0.4848

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.49222 | val 1.01660
  Epoch 015 - train 0.37970 | val 1.35531
  Classification -> best τ=0.285 (val F1=0.3632)
  Directional -> Accuracy: 0.4524, MCC: -0.0446, F1: 0.5106

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.54783 | val 1.54737
  Epoch 011 - train 0.52933 | val 1.59500
  Classification -> best τ=0.505 (val F1=0.1928)
  Directional -> Accuracy: 0.5625, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.57418 | val 0.89080
  Epoch 011 - train 0.49631 | val 0.86879
  Classification -> best τ=0.425 (val F1=0.1967)
  Directional -> Accuracy: 0.4203, MCC: -0.0665, F1: 0.5455

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.57283 | val 0.81650
  Epoch 017 - train 0.44016 | val 1.94991
  Classification -> best τ=0.390 (val F1=0.0479)
  Directional -> Accuracy: 0.5714, MCC: 0.1126, F1: 0.4324

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.60544 | val 1.51063
  Epoch 011 - train 0.54432 | val 2.28027
  Classification -> best τ=0.655 (val F1=0.2012)
  Directional -> Accuracy: 0.5439, MCC: 0.1422, F1: 0.6829

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.49769 | val 1.04033
  Epoch 013 - train 0.44823 | val 1.51626
  Classification -> best τ=0.550 (val F1=0.3553)
  Directional -> Accuracy: 0.5952, MCC: 0.1758, F1: 0.3200

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.63479 | val 0.70465
  Epoch 015 - train 0.54808 | val 0.79519
  Classification -> best τ=0.320 (val F1=0.3706)
  Directional -> Accuracy: 0.4833, MCC: -0.0603, F1: 0.1143

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.58381 | val 0.82839
  Epoch 013 - train 0.49256 | val 1.76547
  Classification -> best τ=0.595 (val F1=0.2571)
  Directional -> Accuracy: 0.5490, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.55707 | val 1.53183
  Epoch 011 - train 0.54854 | val 2.11557
  Classification -> best τ=0.405 (val F1=0.2955)
  Directional -> Accuracy: 0.4783, MCC: 0.0150, F1: 0.2174

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.57241 | val 1.39894
  Epoch 012 - train 0.53200 | val 1.75748
  Classification -> best τ=0.310 (val F1=0.2581)
  Directional -> Accuracy: 0.3793, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.60277 | val 0.75710
  Epoch 014 - train 0.50216 | val 0.84025
  Classification -> best τ=0.535 (val F1=0.1909)
  Directional -> Accuracy: 0.4000, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.59800 | val 2.43829
  Epoch 012 - train 0.54747 | val 3.28348
  Classification -> best τ=0.225 (val F1=0.2522)
  Directional -> Accuracy: 0.5625, MCC: 0.1122, F1: 0.6111

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.58397 | val 1.19647
  Epoch 011 - train 0.55028 | val 0.99646
  Classification -> best τ=0.640 (val F1=0.3161)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.54832 | val 1.17018
  Epoch 011 - train 0.45620 | val 1.90141
  Classification -> best τ=0.545 (val F1=0.1413)
  Directional -> Accuracy: 0.5319, MCC: 0.1139, F1: 0.5417

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.60633 | val 3.31361
  Epoch 011 - train 0.54299 | val 4.93701
  Classification -> best τ=0.420 (val F1=0.1224)
  Directional -> Accuracy: 0.5385, MCC: 0.1275, F1: 0.2857

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.62928 | val 0.76055
  Epoch 019 - train 0.49239 | val 1.65207
  Classification -> best τ=0.430 (val F1=0.4177)
  Directional -> Accuracy: 0.5965, MCC: 0.1923, F1: 0.6230

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.61612 | val 0.73952
  Epoch 011 - train 0.57676 | val 0.76294
  Classification -> best τ=0.560 (val F1=0.2111)
  Directional -> Accuracy: 0.4769, MCC: -0.0515, F1: 0.4333

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.53218 | val 0.89062
  Epoch 011 - train 0.50071 | val 0.85307
  Classification -> best τ=0.320 (val F1=0.4607)
  Directional -> Accuracy: 0.5455, MCC: 0.0690, F1: 0.6154

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.42021 | val 3.91061
  Epoch 011 - train 0.41817 | val 4.18261
  Classification -> best τ=0.630 (val F1=0.0385)
  Directional -> Accuracy: 0.3556, MCC: -0.2466, F1: 0.4528

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.57970 | val 0.78307
  Epoch 013 - train 0.58006 | val 1.14472
  Classification -> best τ=0.530 (val F1=0.2402)
  Directional -> Accuracy: 0.4762, MCC: 0.1171, F1: 0.2143

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.53302 | val 1.60003
  Epoch 011 - train 0.47689 | val 1.80277
  Classification -> best τ=0.340 (val F1=0.3689)
  Directional -> Accuracy: 0.4464, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.59384 | val 0.72568
  Epoch 020 - train 0.36600 | val 0.71733
  Epoch 027 - train 0.26441 | val 0.99566
  Classification -> best τ=0.500 (val F1=0.3296)
  Directional -> Accuracy: 0.6000, MCC: 0.1919, F1: 0.6364

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.55192 | val 3.09664
  Epoch 012 - train 0.50408 | val 2.93344
  Classification -> best τ=0.575 (val F1=0.3501)
  Directional -> Accuracy: 0.5238, MCC: 0.0413, F1: 0.4737

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.59028 | val 1.54569
  Epoch 012 - train 0.47725 | val 1.85105
  Classification -> best τ=0.515 (val F1=0.3067)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.52782 | val 0.71826
  Epoch 012 - train 0.43411 | val 0.93220
  Classification -> best τ=0.385 (val F1=0.2488)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.64061 | val 0.86802
  Epoch 013 - train 0.53775 | val 0.74126
  Classification -> best τ=0.420 (val F1=0.4367)
  Directional -> Accuracy: 0.5694, MCC: 0.2524, F1: 0.4364

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.55269 | val 1.36255
  Epoch 011 - train 0.48215 | val 1.58694
  Classification -> best τ=0.665 (val F1=0.3227)
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.61731 | val 1.24807
  Epoch 011 - train 0.61844 | val 1.30632
  Classification -> best τ=0.375 (val F1=0.2464)
  Directional -> Accuracy: 0.5758, MCC: 0.0000, F1: 0.7308

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.40893 | val 2.39829
  Epoch 011 - train 0.38704 | val 2.12388
  Classification -> best τ=0.615 (val F1=0.2658)
  Directional -> Accuracy: 0.6429, MCC: 0.2897, F1: 0.7059

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.56111 | val 0.75626
  Epoch 012 - train 0.50302 | val 0.80221
  Classification -> best τ=0.465 (val F1=0.2203)
  Directional -> Accuracy: 0.5714, MCC: 0.1623, F1: 0.6000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.47748 | val 0.88139
  Epoch 012 - train 0.43264 | val 1.21439
  Classification -> best τ=0.625 (val F1=0.2254)
  Directional -> Accuracy: 0.6087, MCC: 0.0000, F1: 0.7568

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.60115 | val 0.72424
  Epoch 020 - train 0.48992 | val 0.80998
  Epoch 023 - train 0.36262 | val 0.89172
  Classification -> best τ=0.445 (val F1=0.4710)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.56845 | val 1.27362
  Epoch 011 - train 0.53269 | val 1.12785
  Classification -> best τ=0.450 (val F1=0.3081)
  Directional -> Accuracy: 0.4730, MCC: -0.0638, F1: 0.3810

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.58948 | val 0.79613
  Epoch 012 - train 0.52656 | val 0.76917
  Classification -> best τ=0.520 (val F1=0.4632)
  Directional -> Accuracy: 0.5333, MCC: 0.1059, F1: 0.3226

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.45118 | val 2.37714
  Epoch 011 - train 0.36664 | val 2.73199
  Classification -> best τ=0.790 (val F1=0.3612)
  Directional -> Accuracy: 0.4524, MCC: 0.1353, F1: 0.0800

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.44503 | val 0.67809
  Epoch 020 - train 0.46547 | val 0.76329
  Epoch 028 - train 0.21737 | val 1.33590
  Classification -> best τ=0.585 (val F1=0.5689)
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.5455

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.60754 | val 1.11665
  Epoch 011 - train 0.60175 | val 1.30868
  Classification -> best τ=0.545 (val F1=0.2291)
  Directional -> Accuracy: 0.4182, MCC: -0.3051, F1: 0.5789

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.49007 | val 2.13579
  Epoch 011 - train 0.47102 | val 2.38168
  Classification -> best τ=0.710 (val F1=0.3546)
  Directional -> Accuracy: 0.4821, MCC: -0.0146, F1: 0.6133

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.65644 | val 0.92216
  Epoch 012 - train 0.57467 | val 0.77047
  Classification -> best τ=0.450 (val F1=0.2369)
  Directional -> Accuracy: 0.5283, MCC: 0.0707, F1: 0.6667

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.53853 | val 2.03142
  Epoch 018 - train 0.41044 | val 3.84791
  Classification -> best τ=0.770 (val F1=0.2292)
  Directional -> Accuracy: 0.4545, MCC: -0.1437, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.62729 | val 2.09804

[I 2026-02-22 15:03:01,344] Trial 229 finished with value: 0.29057109847686813 and parameters: {'feature_set': 'sector', 'model_type': 'BiGRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.4, 'batch_size': 16, 'learning_rate': 0.009994737218369638, 'weight_decay': 0.00011415679175057767, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 0.9155821869090288, 'early_stopping_min_delta': 0.0009674482854067803}. Best is trial 214 with value: 0.2991200218486954.

  Epoch 011 - train 0.59936 | val 2.14944
  Classification -> best τ=0.580 (val F1=0.2623)
  Directional -> Accuracy: 0.5167, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.29057109847686813
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.59270 | val 1.10041
  Epoch 014 - train 0.61465 | val 0.87339
  Classification -> best τ=0.910 (val F1=0.2919)
  Directional -> Accuracy: 0.5526, MCC: 0.0174, F1: 0.0556

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.50179 | val 0.78463
  Epoch 011 - train 0.45120 | val 0.79630
  Classification -> best τ=0.640 (val F1=0.3126)
  Directional -> Accuracy: 0.6222, MCC: 0.2204, F1: 0.6792

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.54659 | val 1.92206
  Epoch 011 - train 0.56469 | val 2.09398
  Classification -> best τ=0.735 (val F1=0.3114)
  Directional -> Accuracy: 0.5217, MCC: 0.1124, F1: 0.2667

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.60814 | val 0.80355
  Epoch 012 - train 0.51691 | val 1.07159
  Classification -> best τ=0.525 (val F1=0.2482)
  Directional -> Accuracy: 0.5000, MCC: 0.1127, F1: 0.2128

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.54993 | val 1.90223
  Epoch 014 - train 0.39760 | val 2.49455
  Classification -> best τ=0.770 (val F1=0.3113)
  Directional -> Accuracy: 0.5400, MCC: 0.0738, F1: 0.6667

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.52005 | val 0.71197
  Epoch 020 - train 0.42077 | val 0.80263
  Epoch 025 - train 0.26576 | val 0.99707
  Classification -> best τ=0.560 (val F1=0.5089)
  Directional -> Accuracy: 0.5217, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.61175 | val 1.01643
  Epoch 012 - train 0.55186 | val 0.99526
  Classification -> best τ=0.350 (val F1=0.3312)
  Directional -> Accuracy: 0.3971, MCC: -0.1358, F1: 0.4533

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.47113 | val 0.89124
  Epoch 017 - train 0.40060 | val 0.85109
  Classification -> best τ=0.095 (val F1=0.3158)
  Directional -> Accuracy: 0.4524, MCC: 0.0534, F1: 0.5965

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.50467 | val 2.40917
  Epoch 011 - train 0.49281 | val 3.13722
  Classification -> best τ=0.505 (val F1=0.1928)
  Directional -> Accuracy: 0.6875, MCC: 0.3620, F1: 0.6341

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.65533 | val 1.90678
  Epoch 015 - train 0.49061 | val 1.37493
  Classification -> best τ=0.660 (val F1=0.2083)
  Directional -> Accuracy: 0.5362, MCC: 0.0664, F1: 0.4839

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.60912 | val 1.26169
  Epoch 011 - train 0.51332 | val 1.37406
  Classification -> best τ=0.595 (val F1=0.1316)
  Directional -> Accuracy: 0.5510, MCC: 0.0782, F1: 0.4500

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.65467 | val 1.10413
  Epoch 011 - train 0.51052 | val 1.20383
  Classification -> best τ=0.490 (val F1=0.2162)
  Directional -> Accuracy: 0.5088, MCC: 0.0000, F1: 0.6744

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.45262 | val 0.93670
  Epoch 016 - train 0.40554 | val 0.93295
  Classification -> best τ=0.705 (val F1=0.4097)
  Directional -> Accuracy: 0.5476, MCC: 0.0000, F1: 0.0000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.61999 | val 0.88741
  Epoch 012 - train 0.55651 | val 1.09327
  Classification -> best τ=0.285 (val F1=0.3843)
  Directional -> Accuracy: 0.4667, MCC: -0.1111, F1: 0.1111

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.57778 | val 0.99218
  Epoch 011 - train 0.54260 | val 1.33375
  Classification -> best τ=0.460 (val F1=0.3000)
  Directional -> Accuracy: 0.5490, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.54082 | val 2.98975
  Epoch 012 - train 0.52120 | val 1.90259
  Classification -> best τ=0.410 (val F1=0.2155)
  Directional -> Accuracy: 0.6087, MCC: 0.2144, F1: 0.7033

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.55807 | val 2.69999
  Epoch 011 - train 0.49551 | val 2.75964
  Classification -> best τ=0.165 (val F1=0.1905)
  Directional -> Accuracy: 0.6207, MCC: 0.0000, F1: 0.7660

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.55913 | val 1.05985
  Epoch 013 - train 0.49359 | val 1.26423
  Classification -> best τ=0.420 (val F1=0.2165)
  Directional -> Accuracy: 0.4267, MCC: 0.0727, F1: 0.1224

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.56012 | val 2.94478
  Epoch 011 - train 0.51375 | val 3.64720
  Classification -> best τ=0.695 (val F1=0.2000)
  Directional -> Accuracy: 0.5156, MCC: 0.1459, F1: 0.3922

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.55237 | val 1.31507
  Epoch 011 - train 0.47784 | val 1.89829
  Classification -> best τ=0.365 (val F1=0.2597)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.59882 | val 0.89880
  Epoch 013 - train 0.42980 | val 1.29951
  Classification -> best τ=0.540 (val F1=0.2281)
  Directional -> Accuracy: 0.4681, MCC: -0.0918, F1: 0.5455

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.60378 | val 1.51248
  Epoch 012 - train 0.53203 | val 1.96144
  Classification -> best τ=0.460 (val F1=0.2520)
  Directional -> Accuracy: 0.4923, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.57994 | val 0.81241
  Epoch 013 - train 0.53310 | val 0.73035
  Classification -> best τ=0.460 (val F1=0.4074)
  Directional -> Accuracy: 0.5614, MCC: 0.1750, F1: 0.5098

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.63331 | val 0.73122
  Epoch 018 - train 0.50235 | val 3.15045
  Classification -> best τ=0.515 (val F1=0.2430)
  Directional -> Accuracy: 0.4769, MCC: -0.0455, F1: 0.4688

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.53598 | val 1.26994
  Epoch 011 - train 0.50156 | val 1.60702
  Classification -> best τ=0.165 (val F1=0.4688)
  Directional -> Accuracy: 0.5636, MCC: 0.1047, F1: 0.6364

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.50211 | val 2.23851
  Epoch 013 - train 0.38395 | val 1.35616
  Classification -> best τ=0.535 (val F1=0.1890)
  Directional -> Accuracy: 0.5778, MCC: 0.0340, F1: 0.0952

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.52873 | val 0.71961
  Epoch 011 - train 0.52013 | val 0.72620
  Classification -> best τ=0.545 (val F1=0.2402)
  Directional -> Accuracy: 0.5238, MCC: 0.0413, F1: 0.5652

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.58379 | val 1.48807
  Epoch 012 - train 0.48046 | val 1.86800
  Classification -> best τ=0.295 (val F1=0.3751)
  Directional -> Accuracy: 0.4464, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.47608 | val 1.64075
  Epoch 011 - train 0.46745 | val 1.23083
  Classification -> best τ=0.565 (val F1=0.2618)
  Directional -> Accuracy: 0.6000, MCC: 0.2010, F1: 0.7241

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.57430 | val 0.71657
  Epoch 014 - train 0.48735 | val 1.66014
  Classification -> best τ=0.265 (val F1=0.3059)
  Directional -> Accuracy: 0.4524, MCC: -0.0953, F1: 0.4390

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.52225 | val 0.90576
  Epoch 020 - train 0.41387 | val 0.80738
  Epoch 026 - train 0.30292 | val 0.98113
  Classification -> best τ=0.620 (val F1=0.2646)
  Directional -> Accuracy: 0.4762, MCC: -0.0123, F1: 0.3889

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.48741 | val 0.89527
  Epoch 011 - train 0.49041 | val 0.91303
  Classification -> best τ=0.280 (val F1=0.4120)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.60296 | val 0.80979
  Epoch 016 - train 0.48187 | val 1.25756
  Classification -> best τ=0.815 (val F1=0.3278)
  Directional -> Accuracy: 0.4444, MCC: 0.0000, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.58220 | val 0.86468
  Epoch 011 - train 0.51543 | val 0.85888
  Classification -> best τ=0.470 (val F1=0.2603)
  Directional -> Accuracy: 0.6279, MCC: 0.3713, F1: 0.3846

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.60309 | val 1.05283
  Epoch 011 - train 0.55998 | val 1.29143
  Classification -> best τ=0.590 (val F1=0.1819)
  Directional -> Accuracy: 0.4242, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.36242 | val 1.49140
  Epoch 011 - train 0.42615 | val 1.78741
  Classification -> best τ=0.590 (val F1=0.3287)
  Directional -> Accuracy: 0.6190, MCC: 0.3091, F1: 0.5000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.58783 | val 0.76134
  Epoch 012 - train 0.46666 | val 0.89795
  Classification -> best τ=0.445 (val F1=0.2244)
  Directional -> Accuracy: 0.5000, MCC: 0.0601, F1: 0.6111

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.46751 | val 1.37447
  Epoch 011 - train 0.38843 | val 1.71616
  Classification -> best τ=0.465 (val F1=0.1362)
  Directional -> Accuracy: 0.5435, MCC: -0.0586, F1: 0.6769

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.51052 | val 0.69208
  Epoch 011 - train 0.50800 | val 0.83356
  Classification -> best τ=0.565 (val F1=0.4011)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.53566 | val 1.22846
  Epoch 011 - train 0.51488 | val 0.99684
  Classification -> best τ=0.620 (val F1=0.3549)
  Directional -> Accuracy: 0.4595, MCC: -0.1007, F1: 0.3103

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.54663 | val 0.87785
  Epoch 014 - train 0.47996 | val 1.94155
  Classification -> best τ=0.530 (val F1=0.4080)
  Directional -> Accuracy: 0.5778, MCC: 0.1692, F1: 0.5128

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.39512 | val 2.75373
  Epoch 011 - train 0.28064 | val 2.57046
  Classification -> best τ=0.300 (val F1=0.3015)
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.7273

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.46914 | val 1.21791
  Epoch 011 - train 0.38676 | val 1.10648
  Classification -> best τ=0.515 (val F1=0.2689)
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.5455

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.64665 | val 0.95802
  Epoch 015 - train 0.58131 | val 1.18087
  Classification -> best τ=0.605 (val F1=0.2036)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.48917 | val 3.21687
  Epoch 011 - train 0.42882 | val 4.24321
  Classification -> best τ=0.560 (val F1=0.3809)
  Directional -> Accuracy: 0.5357, MCC: 0.0680, F1: 0.5000

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.66605 | val 0.67679
  Epoch 011 - train 0.62470 | val 0.76873
  Classification -> best τ=0.515 (val F1=0.2351)
  Directional -> Accuracy: 0.4906, MCC: -0.0216, F1: 0.5263

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.54281 | val 1.27806
  Epoch 012 - train 0.43587 | val 3.26068
  Classification -> best τ=0.505 (val F1=0.3143)
  Directional -> Accuracy: 0.4545, MCC: -0.1437, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.60707 | val 0.73600

[I 2026-02-22 15:07:14,205] Trial 230 finished with value: 0.2877666152984898 and parameters: {'feature_set': 'sector', 'model_type': 'BiGRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.4, 'batch_size': 16, 'learning_rate': 0.00844614323844671, 'weight_decay': 0.00011800806021043806, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 0.8910466984884458, 'early_stopping_min_delta': 0.0015171844276695254}. Best is trial 214 with value: 0.2991200218486954.

  Epoch 011 - train 0.58593 | val 0.82278
  Classification -> best τ=0.490 (val F1=0.2810)
  Directional -> Accuracy: 0.5167, MCC: 0.0131, F1: 0.2162

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2877666152984898
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.60751 | val 1.18057
  Epoch 011 - train 0.60404 | val 1.40077
  Classification -> best τ=0.425 (val F1=0.1635)
  Directional -> Accuracy: 0.5395, MCC: 0.1006, F1: 0.5570

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.55632 | val 0.74407
  Epoch 012 - train 0.46648 | val 0.90849
  Classification -> best τ=0.680 (val F1=0.3126)
  Directional -> Accuracy: 0.6222, MCC: 0.2204, F1: 0.6792

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.59099 | val 1.32914
  Epoch 011 - train 0.51419 | val 1.67843
  Classification -> best τ=0.435 (val F1=0.3114)
  Directional -> Accuracy: 0.5652, MCC: 0.1510, F1: 0.5000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.60918 | val 1.28850
  Epoch 012 - train 0.51927 | val 1.04707
  Classification -> best τ=0.635 (val F1=0.0803)
  Directional -> Accuracy: 0.5270, MCC: -0.1079, F1: 0.6903

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.53756 | val 0.61303
  Epoch 020 - train 0.39658 | val 1.50946
  Classification -> best τ=0.560 (val F1=0.4602)
  Directional -> Accuracy: 0.6400, MCC: 0.3036, F1: 0.5909

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.48421 | val 0.64122
  Epoch 020 - train 0.36040 | val 1.08274
  Classification -> best τ=0.600 (val F1=0.3838)
  Directional -> Accuracy: 0.5217, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.60919 | val 1.20789
  Epoch 012 - train 0.54172 | val 1.21259
  Classification -> best τ=0.315 (val F1=0.2182)
  Directional -> Accuracy: 0.4853, MCC: -0.0053, F1: 0.4615

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.47614 | val 0.94998
  Epoch 013 - train 0.36240 | val 1.41649
  Classification -> best τ=0.255 (val F1=0.3632)
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.62650 | val 1.52074
  Epoch 012 - train 0.56441 | val 1.31728
  Classification -> best τ=0.475 (val F1=0.3433)
  Directional -> Accuracy: 0.5833, MCC: 0.1193, F1: 0.1667

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.61553 | val 1.02626
  Epoch 017 - train 0.47284 | val 1.28486
  Classification -> best τ=0.385 (val F1=0.2386)
  Directional -> Accuracy: 0.4638, MCC: -0.0208, F1: 0.5067

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.58707 | val 0.70746
  Epoch 015 - train 0.52477 | val 1.61343
  Classification -> best τ=0.490 (val F1=0.2484)
  Directional -> Accuracy: 0.5510, MCC: 0.0212, F1: 0.0833

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.59146 | val 0.93912
  Epoch 014 - train 0.49930 | val 0.96744
  Classification -> best τ=0.415 (val F1=0.2000)
  Directional -> Accuracy: 0.5088, MCC: 0.0033, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.44422 | val 0.70377
  Epoch 015 - train 0.38775 | val 0.83171
  Classification -> best τ=0.600 (val F1=0.3362)
  Directional -> Accuracy: 0.4048, MCC: -0.1658, F1: 0.5098

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.58054 | val 0.89837
  Epoch 016 - train 0.51852 | val 1.19689
  Classification -> best τ=0.385 (val F1=0.3141)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.58609 | val 0.78878
  Epoch 012 - train 0.53186 | val 1.26953
  Classification -> best τ=0.440 (val F1=0.2370)
  Directional -> Accuracy: 0.5098, MCC: -0.0277, F1: 0.3243

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.54580 | val 1.76486
  Epoch 011 - train 0.48788 | val 1.68212
  Classification -> best τ=0.810 (val F1=0.1709)
  Directional -> Accuracy: 0.4638, MCC: 0.0000, F1: 0.0000

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.58305 | val 1.41969
  Epoch 011 - train 0.55605 | val 1.33225
  Classification -> best τ=0.305 (val F1=0.1905)
  Directional -> Accuracy: 0.6207, MCC: 0.0000, F1: 0.7660

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.61276 | val 0.80792
  Epoch 011 - train 0.54255 | val 0.92371
  Classification -> best τ=0.385 (val F1=0.1605)
  Directional -> Accuracy: 0.4800, MCC: 0.1118, F1: 0.3390

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.61522 | val 2.10973
  Epoch 012 - train 0.56765 | val 1.86991
  Classification -> best τ=0.320 (val F1=0.2803)
  Directional -> Accuracy: 0.4844, MCC: -0.0416, F1: 0.5352

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.55489 | val 1.34085
  Epoch 011 - train 0.46083 | val 1.34310
  Classification -> best τ=0.620 (val F1=0.1808)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.58638 | val 1.96903
  Epoch 013 - train 0.41206 | val 1.62016
  Classification -> best τ=0.460 (val F1=0.2559)
  Directional -> Accuracy: 0.6170, MCC: 0.0000, F1: 0.7632

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.61701 | val 0.93991
  Epoch 014 - train 0.46588 | val 3.25120
  Classification -> best τ=0.455 (val F1=0.2437)
  Directional -> Accuracy: 0.5077, MCC: 0.0533, F1: 0.1579

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.63431 | val 0.79373
  Epoch 011 - train 0.63242 | val 1.20566
  Classification -> best τ=0.475 (val F1=0.3294)
  Directional -> Accuracy: 0.6316, MCC: 0.3108, F1: 0.7529

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.59231 | val 0.83411
  Epoch 011 - train 0.52369 | val 0.96434
  Classification -> best τ=0.530 (val F1=0.2397)
  Directional -> Accuracy: 0.5846, MCC: 0.1664, F1: 0.5574

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.64738 | val 1.30350
  Epoch 014 - train 0.46090 | val 1.53192
  Classification -> best τ=0.315 (val F1=0.4607)
  Directional -> Accuracy: 0.4545, MCC: -0.0930, F1: 0.4828

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.47503 | val 1.83727
  Epoch 013 - train 0.37163 | val 1.77884
  Classification -> best τ=0.710 (val F1=0.2726)
  Directional -> Accuracy: 0.5778, MCC: 0.0842, F1: 0.3448

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.58198 | val 0.84061
  Epoch 014 - train 0.50655 | val 0.92497
  Classification -> best τ=0.595 (val F1=0.2810)
  Directional -> Accuracy: 0.5476, MCC: 0.0829, F1: 0.5957

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.51370 | val 0.99499
  Epoch 011 - train 0.50292 | val 1.08995
  Classification -> best τ=0.205 (val F1=0.1986)
  Directional -> Accuracy: 0.6071, MCC: 0.2118, F1: 0.6333

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.52372 | val 1.28309
  Epoch 012 - train 0.43921 | val 1.47446
  Classification -> best τ=0.480 (val F1=0.2618)
  Directional -> Accuracy: 0.6000, MCC: 0.2536, F1: 0.7333

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.55438 | val 1.43963
  Epoch 015 - train 0.42033 | val 0.93502
  Classification -> best τ=0.780 (val F1=0.2814)
  Directional -> Accuracy: 0.5000, MCC: -0.0258, F1: 0.3226

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.56852 | val 0.64406
  Epoch 020 - train 0.42388 | val 0.95052
  Classification -> best τ=0.660 (val F1=0.3036)
  Directional -> Accuracy: 0.4524, MCC: -0.0214, F1: 0.0800

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.48366 | val 0.82478
  Epoch 011 - train 0.41441 | val 1.22654
  Classification -> best τ=0.600 (val F1=0.2566)
  Directional -> Accuracy: 0.5306, MCC: 0.0127, F1: 0.6849

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.64037 | val 0.84411
  Epoch 018 - train 0.51111 | val 0.74209
  Classification -> best τ=0.475 (val F1=0.2068)
  Directional -> Accuracy: 0.4861, MCC: 0.1865, F1: 0.1395

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.56966 | val 1.30132
  Epoch 013 - train 0.45844 | val 1.52643
  Classification -> best τ=0.280 (val F1=0.2717)
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.61011 | val 1.81376
  Epoch 014 - train 0.57143 | val 2.04768
  Classification -> best τ=0.150 (val F1=0.4024)
  Directional -> Accuracy: 0.5152, MCC: 0.1917, F1: 0.3333

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.39949 | val 0.98341
  Epoch 013 - train 0.33864 | val 1.01581
  Classification -> best τ=0.415 (val F1=0.3589)
  Directional -> Accuracy: 0.6905, MCC: 0.3814, F1: 0.6977

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.54343 | val 1.00231
  Epoch 012 - train 0.43787 | val 0.90747
  Classification -> best τ=0.615 (val F1=0.1832)
  Directional -> Accuracy: 0.5714, MCC: 0.1316, F1: 0.2941

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.39940 | val 0.99958
  Epoch 011 - train 0.36884 | val 1.07060
  Classification -> best τ=0.340 (val F1=0.1195)
  Directional -> Accuracy: 0.5435, MCC: -0.2118, F1: 0.7042

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.58597 | val 0.85265
  Epoch 011 - train 0.51815 | val 1.11597
  Classification -> best τ=0.570 (val F1=0.3800)
  Directional -> Accuracy: 0.4375, MCC: -0.0040, F1: 0.4706

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.61840 | val 0.65755
  Epoch 020 - train 0.44625 | val 2.16078
  Classification -> best τ=0.700 (val F1=0.4249)
  Directional -> Accuracy: 0.4324, MCC: -0.2266, F1: 0.0870

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.59779 | val 2.07350
  Epoch 012 - train 0.53963 | val 1.69017
  Classification -> best τ=0.520 (val F1=0.4080)
  Directional -> Accuracy: 0.5333, MCC: 0.1221, F1: 0.2759

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.41095 | val 3.38057
  Epoch 013 - train 0.31313 | val 2.03098
  Classification -> best τ=0.680 (val F1=0.4082)
  Directional -> Accuracy: 0.6667, MCC: 0.3339, F1: 0.7667

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.46251 | val 1.12457
  Epoch 011 - train 0.44210 | val 1.46026
  Classification -> best τ=0.635 (val F1=0.3672)
  Directional -> Accuracy: 0.5833, MCC: 0.1511, F1: 0.5000

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.61184 | val 2.05816
  Epoch 012 - train 0.57953 | val 1.86018
  Classification -> best τ=0.535 (val F1=0.1884)
  Directional -> Accuracy: 0.4182, MCC: -0.2739, F1: 0.5676

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.52730 | val 3.36593
  Epoch 011 - train 0.46898 | val 2.90959
  Classification -> best τ=0.615 (val F1=0.1502)
  Directional -> Accuracy: 0.5000, MCC: -0.0515, F1: 0.1250

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.66598 | val 0.67310
  Epoch 020 - train 0.43112 | val 1.04684
  Classification -> best τ=0.575 (val F1=0.2358)
  Directional -> Accuracy: 0.5472, MCC: 0.1005, F1: 0.5000

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.57256 | val 1.28219
  Epoch 011 - train 0.48747 | val 0.86359
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5273, MCC: 0.0000, F1: 0.6905

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.59059 | val 0.68387

[I 2026-02-22 15:11:42,537] Trial 231 finished with value: 0.2706158813620207 and parameters: {'feature_set': 'sector', 'model_type': 'BiGRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.4, 'batch_size': 16, 'learning_rate': 0.009791209007625668, 'weight_decay': 0.00013240474273489803, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 0.8979592017983867, 'early_stopping_min_delta': 0.0015359210752693307}. Best is trial 214 with value: 0.2991200218486954.

  Epoch 016 - train 0.52874 | val 1.10169
  Classification -> best τ=0.545 (val F1=0.3056)
  Directional -> Accuracy: 0.5167, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2706158813620207
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.65633 | val 0.87429
  Epoch 016 - train 0.57678 | val 1.02548
  Classification -> best τ=0.795 (val F1=0.2082)
  Directional -> Accuracy: 0.6316, MCC: 0.2636, F1: 0.3913

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.54780 | val 0.72133
  Epoch 011 - train 0.48217 | val 0.74303
  Classification -> best τ=0.520 (val F1=0.1764)
  Directional -> Accuracy: 0.6000, MCC: 0.1323, F1: 0.7353

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.54916 | val 1.19288
  Epoch 011 - train 0.55612 | val 1.11309
  Classification -> best τ=0.810 (val F1=0.3114)
  Directional -> Accuracy: 0.5000, MCC: 0.0547, F1: 0.2069

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.58682 | val 1.16034
  Epoch 011 - train 0.54223 | val 1.32059
  Classification -> best τ=0.630 (val F1=0.2118)
  Directional -> Accuracy: 0.5270, MCC: 0.1566, F1: 0.3137

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.47176 | val 0.99227
  Epoch 011 - train 0.51958 | val 0.83933
  Classification -> best τ=0.635 (val F1=0.5167)
  Directional -> Accuracy: 0.6200, MCC: 0.2670, F1: 0.5581

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.54680 | val 0.66951
  Epoch 014 - train 0.46694 | val 1.92025
  Classification -> best τ=0.565 (val F1=0.3624)
  Directional -> Accuracy: 0.5217, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.62921 | val 0.69822
  Epoch 015 - train 0.58502 | val 1.10713
  Classification -> best τ=0.540 (val F1=0.3208)
  Directional -> Accuracy: 0.5441, MCC: 0.2645, F1: 0.6173

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.50115 | val 2.75456
  Epoch 013 - train 0.41235 | val 2.24296
  Classification -> best τ=0.255 (val F1=0.3504)
  Directional -> Accuracy: 0.4286, MCC: -0.0323, F1: 0.5862

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.56543 | val 2.08636
  Epoch 012 - train 0.47410 | val 2.31556
  Classification -> best τ=0.645 (val F1=0.2285)
  Directional -> Accuracy: 0.6042, MCC: 0.1917, F1: 0.5366

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.54932 | val 1.20986
  Epoch 011 - train 0.55776 | val 1.19423
  Classification -> best τ=0.420 (val F1=0.2877)
  Directional -> Accuracy: 0.5072, MCC: 0.1376, F1: 0.5952

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.59911 | val 0.68297
  Epoch 020 - train 0.36683 | val 2.81058
  Classification -> best τ=0.665 (val F1=0.3231)
  Directional -> Accuracy: 0.5918, MCC: 0.1804, F1: 0.2308

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.62089 | val 1.25068
  Epoch 012 - train 0.51208 | val 1.23718
  Classification -> best τ=0.600 (val F1=0.1528)
  Directional -> Accuracy: 0.5439, MCC: 0.1422, F1: 0.6829

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.54479 | val 0.65287
  Epoch 016 - train 0.37970 | val 1.05191
  Classification -> best τ=0.510 (val F1=0.3362)
  Directional -> Accuracy: 0.4286, MCC: -0.3341, F1: 0.0000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.60329 | val 0.72122
  Epoch 012 - train 0.56947 | val 0.72286
  Classification -> best τ=0.565 (val F1=0.3642)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.60114 | val 1.05822
  Epoch 011 - train 0.56615 | val 1.06590
  Classification -> best τ=0.545 (val F1=0.1540)
  Directional -> Accuracy: 0.5882, MCC: 0.1475, F1: 0.4000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.58812 | val 3.32651
  Epoch 011 - train 0.53402 | val 2.65262
  Classification -> best τ=0.830 (val F1=0.0972)
  Directional -> Accuracy: 0.4638, MCC: 0.0000, F1: 0.0000

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.59073 | val 1.19582
  Epoch 013 - train 0.54649 | val 1.26663
  Classification -> best τ=0.435 (val F1=0.3476)
  Directional -> Accuracy: 0.4310, MCC: 0.1826, F1: 0.1538

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.61556 | val 0.81496
  Epoch 011 - train 0.57061 | val 0.98099
  Classification -> best τ=0.525 (val F1=0.2500)
  Directional -> Accuracy: 0.4000, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.61391 | val 1.44704
  Epoch 011 - train 0.52526 | val 1.40302
  Classification -> best τ=0.425 (val F1=0.3140)
  Directional -> Accuracy: 0.5781, MCC: 0.0000, F1: 0.7327

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.56274 | val 1.01093
  Epoch 011 - train 0.50068 | val 1.25024
  Classification -> best τ=0.630 (val F1=0.2902)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.57507 | val 0.74573
  Epoch 019 - train 0.37352 | val 1.32788
  Classification -> best τ=0.490 (val F1=0.3164)
  Directional -> Accuracy: 0.4894, MCC: 0.2066, F1: 0.3333

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.60490 | val 2.20554
  Epoch 011 - train 0.54115 | val 2.81647
  Classification -> best τ=0.355 (val F1=0.0689)
  Directional -> Accuracy: 0.5077, MCC: 0.0000, F1: 0.6735

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.60020 | val 0.78726
  Epoch 017 - train 0.55599 | val 0.69794
  Classification -> best τ=0.430 (val F1=0.4030)
  Directional -> Accuracy: 0.5088, MCC: -0.0919, F1: 0.6500

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.57263 | val 0.76397
  Epoch 011 - train 0.56201 | val 0.94598
  Classification -> best τ=0.620 (val F1=0.2055)
  Directional -> Accuracy: 0.5077, MCC: -0.0336, F1: 0.1579

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.56316 | val 0.93315
  Epoch 012 - train 0.47532 | val 1.19217
  Classification -> best τ=0.275 (val F1=0.4068)
  Directional -> Accuracy: 0.5636, MCC: 0.1047, F1: 0.6364

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.40919 | val 4.67607
  Epoch 012 - train 0.42504 | val 5.35090
  Classification -> best τ=0.655 (val F1=0.2035)
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.5938

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.54340 | val 1.09484
  Epoch 012 - train 0.50854 | val 1.00588
  Classification -> best τ=0.600 (val F1=0.1452)
  Directional -> Accuracy: 0.4524, MCC: -0.0574, F1: 0.4103

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.54119 | val 1.09027
  Epoch 012 - train 0.45923 | val 1.14688
  Classification -> best τ=0.560 (val F1=0.2816)
  Directional -> Accuracy: 0.4464, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.63887 | val 2.07621
  Epoch 012 - train 0.39218 | val 1.41658
  Classification -> best τ=0.540 (val F1=0.3518)
  Directional -> Accuracy: 0.6000, MCC: 0.2536, F1: 0.7333

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.62195 | val 0.91082
  Epoch 017 - train 0.49860 | val 0.85481
  Classification -> best τ=0.725 (val F1=0.2814)
  Directional -> Accuracy: 0.5000, MCC: -0.0196, F1: 0.3636

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.54756 | val 1.61711
  Epoch 011 - train 0.50123 | val 0.96445
  Classification -> best τ=0.690 (val F1=0.2273)
  Directional -> Accuracy: 0.4286, MCC: -0.1946, F1: 0.5385

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.55492 | val 1.13570
  Epoch 016 - train 0.38061 | val 1.62104
  Classification -> best τ=0.150 (val F1=0.3541)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.61011 | val 0.69548
  Epoch 013 - train 0.50457 | val 0.69861
  Classification -> best τ=0.415 (val F1=0.3838)
  Directional -> Accuracy: 0.5278, MCC: 0.1419, F1: 0.3929

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.57082 | val 1.68341
  Epoch 017 - train 0.39643 | val 1.25956
  Classification -> best τ=0.470 (val F1=0.1027)
  Directional -> Accuracy: 0.5349, MCC: 0.0664, F1: 0.4737

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.58679 | val 2.16700
  Epoch 012 - train 0.53500 | val 2.17405
  Classification -> best τ=0.205 (val F1=0.4160)
  Directional -> Accuracy: 0.5758, MCC: 0.0000, F1: 0.7308

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.45355 | val 1.00705
  Epoch 012 - train 0.32865 | val 1.36621
  Classification -> best τ=0.455 (val F1=0.2839)
  Directional -> Accuracy: 0.5952, MCC: 0.2427, F1: 0.4848

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.57321 | val 0.80250
  Epoch 012 - train 0.45453 | val 0.86563
  Classification -> best τ=0.430 (val F1=0.1986)
  Directional -> Accuracy: 0.5536, MCC: 0.1899, F1: 0.6479

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.56098 | val 1.06513
  Epoch 012 - train 0.43267 | val 0.93698
  Classification -> best τ=0.630 (val F1=0.2254)
  Directional -> Accuracy: 0.3913, MCC: -0.0475, F1: 0.0667

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.54970 | val 0.68702
  Epoch 014 - train 0.43596 | val 0.83566
  Classification -> best τ=0.510 (val F1=0.3161)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.56020 | val 1.09442
  Epoch 012 - train 0.48783 | val 1.03462
  Classification -> best τ=0.220 (val F1=0.3075)
  Directional -> Accuracy: 0.4865, MCC: 0.0000, F1: 0.6545

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.53073 | val 0.71477
  Epoch 020 - train 0.42444 | val 1.28608
  Epoch 021 - train 0.41426 | val 1.50325
  Classification -> best τ=0.525 (val F1=0.5000)
  Directional -> Accuracy: 0.4667, MCC: -0.1541, F1: 0.0000

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.36697 | val 1.33511
  Epoch 011 - train 0.33507 | val 1.28607
  Classification -> best τ=0.735 (val F1=0.3612)
  Directional -> Accuracy: 0.5238, MCC: 0.1021, F1: 0.4737

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.57797 | val 1.02158
  Epoch 012 - train 0.36953 | val 0.90573
  Classification -> best τ=0.530 (val F1=0.4542)
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.5455

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.62839 | val 1.79955
  Epoch 014 - train 0.57369 | val 1.52723
  Classification -> best τ=0.685 (val F1=0.2374)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.48444 | val 3.71712
  Epoch 011 - train 0.38057 | val 4.68312
  Classification -> best τ=0.410 (val F1=0.2632)
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.6506

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.60549 | val 1.44832
  Epoch 011 - train 0.56439 | val 1.68072
  Classification -> best τ=0.595 (val F1=0.2305)
  Directional -> Accuracy: 0.4717, MCC: -0.0800, F1: 0.5882

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.50504 | val 2.39582
  Epoch 011 - train 0.46422 | val 2.31929
  Classification -> best τ=0.575 (val F1=0.1605)
  Directional -> Accuracy: 0.4727, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.64444 | val 0.71791

[I 2026-02-22 15:16:09,025] Trial 232 finished with value: 0.2843221744012108 and parameters: {'feature_set': 'sector', 'model_type': 'BiGRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.4, 'batch_size': 16, 'learning_rate': 0.008332910575224124, 'weight_decay': 0.0001913699186567404, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 0.9151084576778482, 'early_stopping_min_delta': 0.0013269771459159267}. Best is trial 214 with value: 0.2991200218486954.

  Epoch 013 - train 0.60944 | val 0.73327
  Classification -> best τ=0.410 (val F1=0.3575)
  Directional -> Accuracy: 0.5333, MCC: 0.0637, F1: 0.5000

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2843221744012108
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.62921 | val 1.46067
  Epoch 012 - train 0.59373 | val 1.57475
  Classification -> best τ=0.735 (val F1=0.2919)
  Directional -> Accuracy: 0.5789, MCC: 0.1259, F1: 0.4286

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.54174 | val 0.76337
  Epoch 011 - train 0.49078 | val 0.77860
  Classification -> best τ=0.455 (val F1=0.1941)
  Directional -> Accuracy: 0.6222, MCC: 0.1941, F1: 0.7385

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.51813 | val 1.30749
  Epoch 011 - train 0.54173 | val 1.41105
  Classification -> best τ=0.775 (val F1=0.3114)
  Directional -> Accuracy: 0.4783, MCC: -0.0134, F1: 0.1429

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.61475 | val 0.83097
  Epoch 019 - train 0.51570 | val 0.94637
  Classification -> best τ=0.500 (val F1=0.2128)
  Directional -> Accuracy: 0.5405, MCC: 0.0427, F1: 0.6531

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.52266 | val 2.13614
  Epoch 017 - train 0.45349 | val 0.73977
  Classification -> best τ=0.565 (val F1=0.4947)
  Directional -> Accuracy: 0.6000, MCC: 0.2019, F1: 0.6000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.49140 | val 0.74012
  Epoch 012 - train 0.43370 | val 1.16264
  Classification -> best τ=0.605 (val F1=0.3525)
  Directional -> Accuracy: 0.5217, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.59879 | val 0.96999
  Epoch 014 - train 0.55164 | val 1.16686
  Classification -> best τ=0.120 (val F1=0.2101)
  Directional -> Accuracy: 0.4265, MCC: 0.0751, F1: 0.5714

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.42927 | val 1.13596
  Epoch 017 - train 0.38706 | val 0.94346
  Classification -> best τ=0.190 (val F1=0.4971)
  Directional -> Accuracy: 0.5000, MCC: 0.0138, F1: 0.4878

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.55349 | val 1.77431
  Epoch 012 - train 0.50234 | val 2.16154
  Classification -> best τ=0.545 (val F1=0.2838)
  Directional -> Accuracy: 0.5000, MCC: 0.1009, F1: 0.6000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.55010 | val 1.16690
  Epoch 011 - train 0.51040 | val 0.87901
  Classification -> best τ=0.540 (val F1=0.2098)
  Directional -> Accuracy: 0.5362, MCC: 0.1415, F1: 0.5789

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.59084 | val 0.66852
  Epoch 012 - train 0.55812 | val 0.99546
  Classification -> best τ=0.435 (val F1=0.4059)
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.56972 | val 0.88161
  Epoch 012 - train 0.51065 | val 1.01251
  Classification -> best τ=0.580 (val F1=0.1809)
  Directional -> Accuracy: 0.5263, MCC: 0.0675, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.44007 | val 0.73998
  Epoch 011 - train 0.43325 | val 0.95772
  Classification -> best τ=0.595 (val F1=0.1840)
  Directional -> Accuracy: 0.4524, MCC: -0.0214, F1: 0.6102

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.57973 | val 0.72417
  Epoch 012 - train 0.55947 | val 0.78063
  Classification -> best τ=0.545 (val F1=0.3126)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.63077 | val 0.76330
  Epoch 016 - train 0.51374 | val 0.88610
  Classification -> best τ=0.405 (val F1=0.3062)
  Directional -> Accuracy: 0.5490, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.59699 | val 1.32335
  Epoch 012 - train 0.51823 | val 1.05062
  Classification -> best τ=0.380 (val F1=0.3094)
  Directional -> Accuracy: 0.5362, MCC: 0.0000, F1: 0.6981

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.59816 | val 1.06731
  Epoch 011 - train 0.55238 | val 1.36224
  Classification -> best τ=0.425 (val F1=0.0811)
  Directional -> Accuracy: 0.6724, MCC: 0.3106, F1: 0.7324

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.61049 | val 0.73538
  Epoch 016 - train 0.54248 | val 1.10311
  Classification -> best τ=0.750 (val F1=0.1909)
  Directional -> Accuracy: 0.4000, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.60193 | val 1.38937
  Epoch 011 - train 0.52163 | val 1.84577
  Classification -> best τ=0.325 (val F1=0.2327)
  Directional -> Accuracy: 0.5469, MCC: 0.0757, F1: 0.6027

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.53436 | val 1.47450
  Epoch 011 - train 0.45957 | val 1.89949
  Classification -> best τ=0.515 (val F1=0.1808)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.56921 | val 1.50849
  Epoch 013 - train 0.45777 | val 1.35817
  Classification -> best τ=0.775 (val F1=0.1978)
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.55029 | val 2.02425
  Epoch 011 - train 0.54108 | val 2.90235
  Classification -> best τ=0.190 (val F1=0.1514)
  Directional -> Accuracy: 0.5077, MCC: 0.0000, F1: 0.6735

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.63450 | val 0.66235
  Epoch 019 - train 0.48360 | val 0.77058
  Classification -> best τ=0.470 (val F1=0.4010)
  Directional -> Accuracy: 0.5789, MCC: 0.1450, F1: 0.6250

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.61342 | val 0.98784
  Epoch 013 - train 0.54555 | val 0.89201
  Classification -> best τ=0.375 (val F1=0.2366)
  Directional -> Accuracy: 0.5385, MCC: 0.1368, F1: 0.6429

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.52352 | val 1.13842
  Epoch 011 - train 0.46562 | val 1.38497
  Classification -> best τ=0.500 (val F1=0.5197)
  Directional -> Accuracy: 0.5818, MCC: 0.2024, F1: 0.5306

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.47834 | val 2.79574
  Epoch 011 - train 0.41333 | val 3.08296
  Classification -> best τ=0.690 (val F1=0.2726)
  Directional -> Accuracy: 0.4667, MCC: -0.0503, F1: 0.4545

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.54922 | val 0.83195
  Epoch 012 - train 0.45021 | val 0.94048
  Classification -> best τ=0.605 (val F1=0.1936)
  Directional -> Accuracy: 0.5952, MCC: 0.1680, F1: 0.6531

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.55702 | val 0.82838
  Epoch 013 - train 0.48853 | val 1.23445
  Classification -> best τ=0.470 (val F1=0.5242)
  Directional -> Accuracy: 0.4464, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.48929 | val 1.63879
  Epoch 012 - train 0.36442 | val 1.86440
  Classification -> best τ=0.480 (val F1=0.2618)
  Directional -> Accuracy: 0.5750, MCC: 0.1240, F1: 0.7119

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.58244 | val 1.63132
  Epoch 013 - train 0.51712 | val 2.10378
  Classification -> best τ=0.535 (val F1=0.2764)
  Directional -> Accuracy: 0.5238, MCC: 0.0608, F1: 0.5652

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.62695 | val 1.64044
  Epoch 011 - train 0.53567 | val 1.43702
  Classification -> best τ=0.590 (val F1=0.1591)
  Directional -> Accuracy: 0.4524, MCC: -0.1972, F1: 0.5965

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.50705 | val 0.96707
  Epoch 012 - train 0.38648 | val 1.22563
  Classification -> best τ=0.340 (val F1=0.3850)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.60930 | val 0.88921
  Epoch 017 - train 0.51362 | val 0.75470
  Classification -> best τ=0.435 (val F1=0.3676)
  Directional -> Accuracy: 0.5139, MCC: 0.0733, F1: 0.4444

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.53914 | val 2.24028
  Epoch 011 - train 0.43470 | val 2.15031
  Classification -> best τ=0.255 (val F1=0.2422)
  Directional -> Accuracy: 0.6047, MCC: 0.3278, F1: 0.3200

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.61941 | val 1.42571
  Epoch 012 - train 0.52585 | val 1.68604
  Classification -> best τ=0.325 (val F1=0.3366)
  Directional -> Accuracy: 0.5152, MCC: 0.0168, F1: 0.5676

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.46329 | val 2.23852
  Epoch 011 - train 0.37227 | val 2.37220
  Classification -> best τ=0.590 (val F1=0.2858)
  Directional -> Accuracy: 0.5476, MCC: 0.1228, F1: 0.4571

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.54300 | val 1.39679
  Epoch 011 - train 0.49770 | val 1.58359
  Classification -> best τ=0.380 (val F1=0.2327)
  Directional -> Accuracy: 0.5357, MCC: 0.0827, F1: 0.5517

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.53788 | val 0.81216
  Epoch 011 - train 0.41811 | val 1.02569
  Classification -> best τ=0.515 (val F1=0.2441)
  Directional -> Accuracy: 0.4348, MCC: 0.1709, F1: 0.1333

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.51733 | val 0.64932
  Epoch 020 - train 0.41465 | val 0.63731
  Epoch 030 - train 0.36408 | val 0.81799
  Classification -> best τ=0.415 (val F1=0.4688)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.57595 | val 1.05307
  Epoch 013 - train 0.46957 | val 1.73142
  Classification -> best τ=0.395 (val F1=0.2968)
  Directional -> Accuracy: 0.5270, MCC: 0.0479, F1: 0.4262

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.58276 | val 0.67346
  Epoch 012 - train 0.52586 | val 0.77199
  Classification -> best τ=0.455 (val F1=0.3190)
  Directional -> Accuracy: 0.6222, MCC: 0.2890, F1: 0.7119

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.47148 | val 2.15486
  Epoch 018 - train 0.17479 | val 1.78002
  Classification -> best τ=0.865 (val F1=0.4971)
  Directional -> Accuracy: 0.5714, MCC: 0.1132, F1: 0.6400

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.48897 | val 0.65784
  Epoch 011 - train 0.47729 | val 0.75700
  Classification -> best τ=0.660 (val F1=0.3895)
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.0000

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.61504 | val 1.42333
  Epoch 011 - train 0.58398 | val 1.51928
  Classification -> best τ=0.630 (val F1=0.2036)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.51795 | val 2.22429
  Epoch 011 - train 0.46249 | val 2.70012
  Classification -> best τ=0.390 (val F1=0.4355)
  Directional -> Accuracy: 0.5000, MCC: 0.0515, F1: 0.6410

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.62371 | val 1.75794
  Epoch 014 - train 0.59406 | val 1.56030
  Classification -> best τ=0.520 (val F1=0.2351)
  Directional -> Accuracy: 0.5849, MCC: 0.1729, F1: 0.6452

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.51856 | val 3.76518
  Epoch 011 - train 0.42783 | val 5.69642
  Classification -> best τ=0.655 (val F1=0.1689)
  Directional -> Accuracy: 0.4727, MCC: -0.0153, F1: 0.1212

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.62927 | val 0.78713

[I 2026-02-22 15:20:38,262] Trial 233 finished with value: 0.29182259978776276 and parameters: {'feature_set': 'sector', 'model_type': 'BiGRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.4, 'batch_size': 16, 'learning_rate': 0.008362906702733904, 'weight_decay': 0.0001017503548854832, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 0.874113043722099, 'early_stopping_min_delta': 0.0013378316496968391}. Best is trial 214 with value: 0.2991200218486954.

  Epoch 014 - train 0.59325 | val 1.06562
  Classification -> best τ=0.510 (val F1=0.2623)
  Directional -> Accuracy: 0.5333, MCC: 0.1346, F1: 0.0667

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.29182259978776276
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.67683 | val 0.80649
  Epoch 013 - train 0.65762 | val 0.82194
  Classification -> best τ=0.410 (val F1=0.1718)
  Directional -> Accuracy: 0.5263, MCC: 0.0837, F1: 0.5610

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.69745 | val 1.13454
  Epoch 012 - train 0.63456 | val 0.75868
  Classification -> best τ=0.430 (val F1=0.1967)
  Directional -> Accuracy: 0.6222, MCC: 0.1967, F1: 0.7119

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.70774 | val 0.70565
  Epoch 011 - train 0.69596 | val 0.68860
  Classification -> best τ=0.530 (val F1=0.3135)
  Directional -> Accuracy: 0.5435, MCC: 0.0784, F1: 0.6038

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.69874 | val 0.68355
  Epoch 020 - train 0.65929 | val 0.72098
  Epoch 021 - train 0.60981 | val 0.80985
  Classification -> best τ=0.305 (val F1=0.2593)
  Directional -> Accuracy: 0.4865, MCC: -0.0293, F1: 0.5128

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.66751 | val 0.74395
  Epoch 012 - train 0.65014 | val 0.78043
  Classification -> best τ=0.565 (val F1=0.4611)
  Directional -> Accuracy: 0.6200, MCC: 0.2957, F1: 0.5128

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.69963 | val 0.69157
  Epoch 012 - train 0.66144 | val 0.68953
  Classification -> best τ=0.530 (val F1=0.1251)
  Directional -> Accuracy: 0.5217, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.69367 | val 0.71562
  Epoch 011 - train 0.68820 | val 0.71427
  Classification -> best τ=0.490 (val F1=0.2101)
  Directional -> Accuracy: 0.3971, MCC: 0.0000, F1: 0.5684

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.64649 | val 1.12100
  Epoch 017 - train 0.61562 | val 0.70684
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.69170 | val 0.76861
  Epoch 015 - train 0.68326 | val 1.02158
  Classification -> best τ=0.445 (val F1=0.2443)
  Directional -> Accuracy: 0.5833, MCC: 0.2140, F1: 0.6154

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.70285 | val 0.82356
  Epoch 020 - train 0.69952 | val 0.69775
  Epoch 022 - train 0.66877 | val 0.81061
  Classification -> best τ=0.545 (val F1=0.2880)
  Directional -> Accuracy: 0.4203, MCC: -0.1032, F1: 0.4872

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.68704 | val 0.72475
  Epoch 019 - train 0.65772 | val 0.93490
  Classification -> best τ=0.420 (val F1=0.3020)
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.69073 | val 0.69220
  Epoch 020 - train 0.64120 | val 0.99612
  Epoch 022 - train 0.61993 | val 1.02801
  Classification -> best τ=0.495 (val F1=0.2162)
  Directional -> Accuracy: 0.5088, MCC: 0.0000, F1: 0.6744

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.62826 | val 0.68373
  Epoch 012 - train 0.61214 | val 0.66290
  Classification -> best τ=0.545 (val F1=0.3922)
  Directional -> Accuracy: 0.5476, MCC: 0.0000, F1: 0.0000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.67312 | val 0.66073
  Epoch 020 - train 0.65706 | val 0.70869
  Epoch 023 - train 0.65294 | val 0.67877
  Classification -> best τ=0.455 (val F1=0.3833)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.67657 | val 0.81477
  Epoch 016 - train 0.63999 | val 0.86068
  Classification -> best τ=0.535 (val F1=0.2571)
  Directional -> Accuracy: 0.5490, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.67630 | val 0.67331
  Epoch 014 - train 0.67037 | val 0.73349
  Classification -> best τ=0.595 (val F1=0.3602)
  Directional -> Accuracy: 0.4203, MCC: -0.1476, F1: 0.3750

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.66334 | val 0.81123
  Epoch 011 - train 0.67750 | val 0.76363
  Classification -> best τ=0.515 (val F1=0.3310)
  Directional -> Accuracy: 0.5862, MCC: -0.0322, F1: 0.7273

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.68351 | val 0.69242
  Epoch 020 - train 0.68382 | val 0.67907
  Epoch 025 - train 0.62198 | val 0.73612
  Classification -> best τ=0.560 (val F1=0.1773)
  Directional -> Accuracy: 0.4400, MCC: 0.1091, F1: 0.1600

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.69206 | val 0.69417
  Epoch 013 - train 0.69126 | val 0.73538
  Classification -> best τ=0.540 (val F1=0.2234)
  Directional -> Accuracy: 0.4375, MCC: -0.0502, F1: 0.3077

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.67223 | val 0.67605
  Epoch 012 - train 0.65477 | val 0.71434
  Classification -> best τ=0.525 (val F1=0.2871)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.74893 | val 0.77012
  Epoch 011 - train 0.65465 | val 0.79285
  Classification -> best τ=0.495 (val F1=0.2416)
  Directional -> Accuracy: 0.5319, MCC: 0.1139, F1: 0.5417

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.69803 | val 0.69637
  Epoch 018 - train 0.68293 | val 0.73151
  Classification -> best τ=0.485 (val F1=0.2425)
  Directional -> Accuracy: 0.5846, MCC: 0.1730, F1: 0.5574

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.70152 | val 0.68372
  Epoch 020 - train 0.67763 | val 0.68818
  Epoch 022 - train 0.69965 | val 0.67419
  Classification -> best τ=0.540 (val F1=0.3294)
  Directional -> Accuracy: 0.4737, MCC: 0.0518, F1: 0.2500

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.68884 | val 0.68747
  Epoch 012 - train 0.69090 | val 0.68868
  Classification -> best τ=0.410 (val F1=0.1558)
  Directional -> Accuracy: 0.5077, MCC: 0.0320, F1: 0.5676

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.68509 | val 0.64362
  Epoch 016 - train 0.57548 | val 0.72762
  Classification -> best τ=0.395 (val F1=0.4723)
  Directional -> Accuracy: 0.5455, MCC: 0.0637, F1: 0.6269

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.65059 | val 2.52579
  Epoch 011 - train 0.55580 | val 2.57974
  Classification -> best τ=0.565 (val F1=0.1956)
  Directional -> Accuracy: 0.4000, MCC: -0.1500, F1: 0.4706

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.66879 | val 0.73207
  Epoch 016 - train 0.65626 | val 0.69276
  Classification -> best τ=0.565 (val F1=0.1936)
  Directional -> Accuracy: 0.4762, MCC: 0.0323, F1: 0.3529

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.67084 | val 0.66938
  Epoch 015 - train 0.64074 | val 0.66253
  Classification -> best τ=0.410 (val F1=0.2742)
  Directional -> Accuracy: 0.4464, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.61794 | val 2.28576
  Epoch 011 - train 0.53570 | val 2.50176
  Classification -> best τ=0.585 (val F1=0.0601)
  Directional -> Accuracy: 0.4750, MCC: -0.0912, F1: 0.5714

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.69222 | val 0.68188
  Epoch 018 - train 0.66617 | val 0.74882
  Classification -> best τ=0.485 (val F1=0.3501)
  Directional -> Accuracy: 0.4286, MCC: -0.1455, F1: 0.4000

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.69794 | val 0.73326
  Epoch 020 - train 0.67140 | val 0.68212
  Epoch 025 - train 0.64518 | val 0.68522
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5476, MCC: 0.0000, F1: 0.7077

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.65301 | val 0.64772
  Epoch 020 - train 0.63643 | val 0.79997
  Classification -> best τ=0.305 (val F1=0.3987)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.70737 | val 0.68913
  Epoch 020 - train 0.66244 | val 0.68741
  Epoch 026 - train 0.60935 | val 0.71824
  Classification -> best τ=0.700 (val F1=0.2957)
  Directional -> Accuracy: 0.4444, MCC: 0.0000, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.67432 | val 0.83151
  Epoch 015 - train 0.63799 | val 0.71213
  Classification -> best τ=0.510 (val F1=0.3668)
  Directional -> Accuracy: 0.6047, MCC: 0.2331, F1: 0.4516

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.66893 | val 0.72161
  Epoch 019 - train 0.64365 | val 0.90106
  Classification -> best τ=0.365 (val F1=0.2641)
  Directional -> Accuracy: 0.5758, MCC: 0.0000, F1: 0.7308

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.67531 | val 0.69401
  Epoch 016 - train 0.63191 | val 1.37556
  Classification -> best τ=0.575 (val F1=0.2618)
  Directional -> Accuracy: 0.6190, MCC: 0.3091, F1: 0.5000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.66165 | val 0.94776
  Epoch 017 - train 0.55633 | val 1.81004
  Classification -> best τ=0.560 (val F1=0.2026)
  Directional -> Accuracy: 0.5179, MCC: 0.0234, F1: 0.4490

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.68915 | val 1.32835
  Epoch 012 - train 0.64717 | val 0.71205
  Classification -> best τ=0.410 (val F1=0.2800)
  Directional -> Accuracy: 0.6304, MCC: 0.1564, F1: 0.7463

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.63747 | val 0.90518
  Epoch 011 - train 0.68873 | val 0.84234
  Classification -> best τ=0.600 (val F1=0.4011)
  Directional -> Accuracy: 0.5417, MCC: 0.2553, F1: 0.5769

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.66511 | val 0.72599
  Epoch 015 - train 0.59605 | val 1.03376
  Classification -> best τ=0.550 (val F1=0.3128)
  Directional -> Accuracy: 0.4865, MCC: -0.0615, F1: 0.2083

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.66740 | val 0.75925
  Epoch 012 - train 0.68123 | val 0.74865
  Classification -> best τ=0.390 (val F1=0.2174)
  Directional -> Accuracy: 0.6000, MCC: 0.3458, F1: 0.3571

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.59068 | val 1.53876
  Epoch 020 - train 0.53727 | val 0.96644
  Epoch 021 - train 0.46736 | val 1.22255
  Classification -> best τ=0.455 (val F1=0.5601)
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.7273

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.64495 | val 0.63573
  Epoch 019 - train 0.62203 | val 0.66512
  Classification -> best τ=0.670 (val F1=0.4795)
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.5455

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.69695 | val 0.68327
  Epoch 020 - train 0.67373 | val 0.71851
  Epoch 028 - train 0.67262 | val 1.57947
  Classification -> best τ=0.570 (val F1=0.2036)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.68115 | val 0.87727
  Epoch 011 - train 0.65513 | val 0.92346
  Classification -> best τ=0.400 (val F1=0.2952)
  Directional -> Accuracy: 0.4821, MCC: -0.0069, F1: 0.6420

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.71103 | val 0.99373
  Epoch 015 - train 0.70026 | val 0.86731
  Classification -> best τ=0.505 (val F1=0.2317)
  Directional -> Accuracy: 0.6038, MCC: 0.2423, F1: 0.6957

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.63878 | val 1.39047
  Epoch 011 - train 0.64999 | val 1.54792
  Classification -> best τ=0.530 (val F1=0.0379)
  Directional -> Accuracy: 0.4364, MCC: -0.1445, F1: 0.5079

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.68770 | val 0.68386

[I 2026-02-22 15:24:32,208] Trial 234 finished with value: 0.2661399540484818 and parameters: {'feature_set': 'sector', 'model_type': 'LSTM', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.4, 'batch_size': 16, 'learning_rate': 0.007856667682571728, 'weight_decay': 0.00011138807888306944, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 0.8525675416738763, 'early_stopping_min_delta': 0.0017130651497783687}. Best is trial 214 with value: 0.2991200218486954.

  Epoch 017 - train 0.67463 | val 0.68614
  Classification -> best τ=0.420 (val F1=0.2507)
  Directional -> Accuracy: 0.5167, MCC: 0.0089, F1: 0.1212

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2661399540484818
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.62965 | val 1.03988
  Epoch 011 - train 0.57026 | val 1.19705
  Classification -> best τ=0.485 (val F1=0.2919)
  Directional -> Accuracy: 0.5263, MCC: -0.1479, F1: 0.0000

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.52571 | val 0.74688
  Epoch 011 - train 0.45688 | val 0.76906
  Classification -> best τ=0.455 (val F1=0.1764)
  Directional -> Accuracy: 0.5556, MCC: 0.1469, F1: 0.5455

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.55865 | val 1.32767
  Epoch 012 - train 0.45288 | val 1.52890
  Classification -> best τ=0.565 (val F1=0.2861)
  Directional -> Accuracy: 0.4565, MCC: -0.1557, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.55926 | val 0.85719
  Epoch 011 - train 0.55842 | val 0.90282
  Classification -> best τ=0.460 (val F1=0.1269)
  Directional -> Accuracy: 0.5405, MCC: 0.0000, F1: 0.7018

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.50359 | val 1.55907
  Epoch 015 - train 0.46129 | val 1.94765
  Classification -> best τ=0.570 (val F1=0.5079)
  Directional -> Accuracy: 0.6800, MCC: 0.3759, F1: 0.6522

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.50644 | val 0.73805
  Epoch 014 - train 0.41375 | val 0.93070
  Classification -> best τ=0.445 (val F1=0.4513)
  Directional -> Accuracy: 0.5217, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.58108 | val 1.22276
  Epoch 013 - train 0.54297 | val 1.12623
  Classification -> best τ=0.655 (val F1=0.2361)
  Directional -> Accuracy: 0.5588, MCC: -0.0300, F1: 0.2105

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.40721 | val 0.66368
  Epoch 017 - train 0.30411 | val 1.03864
  Classification -> best τ=0.245 (val F1=0.2453)
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.59302 | val 3.41860
  Epoch 015 - train 0.47804 | val 4.36054
  Classification -> best τ=0.745 (val F1=0.3523)
  Directional -> Accuracy: 0.5833, MCC: 0.1372, F1: 0.4737

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.53741 | val 0.92433
  Epoch 018 - train 0.38387 | val 0.88478
  Classification -> best τ=0.680 (val F1=0.1983)
  Directional -> Accuracy: 0.4783, MCC: -0.0707, F1: 0.3793

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.59849 | val 0.74682
  Epoch 020 - train 0.47520 | val 1.41602
  Epoch 026 - train 0.36255 | val 0.85398
  Classification -> best τ=0.665 (val F1=0.2484)
  Directional -> Accuracy: 0.5714, MCC: 0.1024, F1: 0.2222

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.58795 | val 0.97381
  Epoch 012 - train 0.51118 | val 0.80833
  Classification -> best τ=0.495 (val F1=0.2112)
  Directional -> Accuracy: 0.5965, MCC: 0.2482, F1: 0.7013

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.56467 | val 1.21178
  Epoch 016 - train 0.39696 | val 1.70726
  Classification -> best τ=0.545 (val F1=0.2850)
  Directional -> Accuracy: 0.5000, MCC: -0.0138, F1: 0.4324

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.57657 | val 0.67166
  Epoch 019 - train 0.48352 | val 1.81524
  Classification -> best τ=0.460 (val F1=0.2531)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.57426 | val 0.76205
  Epoch 011 - train 0.56055 | val 0.79543
  Classification -> best τ=0.525 (val F1=0.2571)
  Directional -> Accuracy: 0.5490, MCC: 0.0546, F1: 0.3429

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.65437 | val 1.01205
  Epoch 012 - train 0.53430 | val 1.45405
  Classification -> best τ=0.345 (val F1=0.2341)
  Directional -> Accuracy: 0.5507, MCC: 0.0867, F1: 0.6990

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.52694 | val 2.35566
  Epoch 011 - train 0.47195 | val 2.28220
  Classification -> best τ=0.665 (val F1=0.2773)
  Directional -> Accuracy: 0.3793, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.59692 | val 0.86292
  Epoch 012 - train 0.49215 | val 0.98196
  Classification -> best τ=0.465 (val F1=0.1909)
  Directional -> Accuracy: 0.4000, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.56836 | val 1.32160
  Epoch 011 - train 0.50396 | val 1.50295
  Classification -> best τ=0.200 (val F1=0.2491)
  Directional -> Accuracy: 0.5781, MCC: 0.0000, F1: 0.7327

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.55948 | val 0.96061
  Epoch 012 - train 0.47510 | val 1.14447
  Classification -> best τ=0.555 (val F1=0.3161)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.51049 | val 0.76558
  Epoch 011 - train 0.47961 | val 0.83375
  Classification -> best τ=0.395 (val F1=0.2784)
  Directional -> Accuracy: 0.6170, MCC: 0.0000, F1: 0.7632

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.55219 | val 2.06403
  Epoch 011 - train 0.51078 | val 2.78457
  Classification -> best τ=0.475 (val F1=0.3475)
  Directional -> Accuracy: 0.5077, MCC: 0.1231, F1: 0.0588

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.63516 | val 0.72987
  Epoch 014 - train 0.58858 | val 0.76533
  Classification -> best τ=0.475 (val F1=0.4735)
  Directional -> Accuracy: 0.6667, MCC: 0.3133, F1: 0.7397

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.61270 | val 0.69256
  Epoch 012 - train 0.51830 | val 0.75399
  Classification -> best τ=0.395 (val F1=0.2245)
  Directional -> Accuracy: 0.4615, MCC: -0.0649, F1: 0.5333

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.53784 | val 1.16344
  Epoch 012 - train 0.46099 | val 0.98732
  Classification -> best τ=0.610 (val F1=0.5009)
  Directional -> Accuracy: 0.5818, MCC: 0.1817, F1: 0.5660

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.44774 | val 1.82093
  Epoch 011 - train 0.38622 | val 2.37317
  Classification -> best τ=0.695 (val F1=0.1956)
  Directional -> Accuracy: 0.5333, MCC: -0.0706, F1: 0.1600

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.60809 | val 0.69263
  Epoch 020 - train 0.44083 | val 0.80524
  Classification -> best τ=0.650 (val F1=0.1667)
  Directional -> Accuracy: 0.5714, MCC: 0.0913, F1: 0.6667

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.56449 | val 1.43925
  Epoch 011 - train 0.52052 | val 2.00344
  Classification -> best τ=0.365 (val F1=0.3563)
  Directional -> Accuracy: 0.4464, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.49834 | val 2.12055
  Epoch 012 - train 0.44597 | val 2.29535
  Classification -> best τ=0.530 (val F1=0.3278)
  Directional -> Accuracy: 0.6000, MCC: 0.2536, F1: 0.7333

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.54406 | val 2.63212
  Epoch 013 - train 0.50933 | val 2.03895
  Classification -> best τ=0.550 (val F1=0.3501)
  Directional -> Accuracy: 0.5476, MCC: 0.0912, F1: 0.5128

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.59565 | val 0.78391
  Epoch 013 - train 0.46780 | val 1.15264
  Classification -> best τ=0.615 (val F1=0.1329)
  Directional -> Accuracy: 0.5952, MCC: 0.2205, F1: 0.5641

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.48065 | val 1.18075
  Epoch 011 - train 0.45103 | val 1.17171
  Classification -> best τ=0.310 (val F1=0.3502)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.55747 | val 0.87723
  Epoch 015 - train 0.47646 | val 1.16983
  Classification -> best τ=0.410 (val F1=0.3548)
  Directional -> Accuracy: 0.4861, MCC: 0.1865, F1: 0.1395

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.50974 | val 1.18588
  Epoch 011 - train 0.45972 | val 1.36220
  Classification -> best τ=0.245 (val F1=0.2324)
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.58130 | val 1.21870
  Epoch 011 - train 0.56896 | val 1.49354
  Classification -> best τ=0.465 (val F1=0.3068)
  Directional -> Accuracy: 0.5758, MCC: 0.0000, F1: 0.7308

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.53020 | val 1.31554
  Epoch 012 - train 0.39789 | val 1.45516
  Classification -> best τ=0.535 (val F1=0.3260)
  Directional -> Accuracy: 0.4762, MCC: -0.0155, F1: 0.1538

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.59530 | val 0.91936
  Epoch 011 - train 0.51589 | val 0.95423
  Classification -> best τ=0.410 (val F1=0.2530)
  Directional -> Accuracy: 0.5536, MCC: 0.1474, F1: 0.6154

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.51185 | val 1.14810
  Epoch 012 - train 0.45190 | val 1.08993
  Classification -> best τ=0.225 (val F1=0.1328)
  Directional -> Accuracy: 0.6087, MCC: 0.0000, F1: 0.7568

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.57561 | val 1.58907
  Epoch 016 - train 0.43668 | val 0.85335
  Classification -> best τ=0.560 (val F1=0.4011)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.58370 | val 1.84520
  Epoch 012 - train 0.48343 | val 1.95576
  Classification -> best τ=0.245 (val F1=0.2982)
  Directional -> Accuracy: 0.5000, MCC: 0.1139, F1: 0.6606

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.57907 | val 0.80267
  Epoch 015 - train 0.42807 | val 0.78684
  Classification -> best τ=0.450 (val F1=0.4080)
  Directional -> Accuracy: 0.4889, MCC: 0.0000, F1: 0.0000

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.49335 | val 2.10263
  Epoch 017 - train 0.27581 | val 1.83590
  Classification -> best τ=0.515 (val F1=0.5593)
  Directional -> Accuracy: 0.6429, MCC: 0.2527, F1: 0.7170

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.51074 | val 0.80212
  Epoch 013 - train 0.39530 | val 0.84229
  Classification -> best τ=0.555 (val F1=0.2689)
  Directional -> Accuracy: 0.4375, MCC: 0.2000, F1: 0.5714

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.63556 | val 1.21961
  Epoch 012 - train 0.60522 | val 1.13790
  Classification -> best τ=0.425 (val F1=0.2291)
  Directional -> Accuracy: 0.5455, MCC: 0.0000, F1: 0.7059

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.52985 | val 2.93155
  Epoch 011 - train 0.45495 | val 3.03353
  Classification -> best τ=0.675 (val F1=0.2514)
  Directional -> Accuracy: 0.5357, MCC: 0.0830, F1: 0.5806

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.64868 | val 0.68771
  Epoch 015 - train 0.60243 | val 0.72929
  Classification -> best τ=0.560 (val F1=0.2788)
  Directional -> Accuracy: 0.6226, MCC: 0.2468, F1: 0.6154

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.55354 | val 2.11183
  Epoch 012 - train 0.48237 | val 3.65571
  Classification -> best τ=0.765 (val F1=0.1769)
  Directional -> Accuracy: 0.4182, MCC: -0.1547, F1: 0.3043

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.57730 | val 0.71926
  Epoch 020 - train 0.60380 | val 0.77944

[I 2026-02-22 15:29:10,679] Trial 235 finished with value: 0.2885609232970571 and parameters: {'feature_set': 'sector', 'model_type': 'BiGRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.4, 'batch_size': 16, 'learning_rate': 0.006363249637635399, 'weight_decay': 0.00020893183995303365, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 0.9384366268927936, 'early_stopping_min_delta': 0.001327642177648745}. Best is trial 214 with value: 0.2991200218486954.

  Epoch 023 - train 0.49783 | val 0.89058
  Classification -> best τ=0.420 (val F1=0.2744)
  Directional -> Accuracy: 0.5833, MCC: 0.1761, F1: 0.4186

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2885609232970571
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.60791 | val 1.55219
  Epoch 011 - train 0.57348 | val 2.11359
  Classification -> best τ=0.860 (val F1=0.2510)
  Directional -> Accuracy: 0.5395, MCC: -0.1039, F1: 0.0000

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.52972 | val 1.02651
  Epoch 013 - train 0.45026 | val 0.83258
  Classification -> best τ=0.580 (val F1=0.1941)
  Directional -> Accuracy: 0.6667, MCC: 0.2984, F1: 0.7458

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.53815 | val 0.98477
  Epoch 011 - train 0.52104 | val 1.11249
  Classification -> best τ=0.630 (val F1=0.3114)
  Directional -> Accuracy: 0.4565, MCC: -0.0996, F1: 0.0741

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.60241 | val 1.89394
  Epoch 011 - train 0.57924 | val 1.95668
  Classification -> best τ=0.255 (val F1=0.1778)
  Directional -> Accuracy: 0.5405, MCC: 0.0000, F1: 0.7018

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.56528 | val 0.70103
  Epoch 012 - train 0.51652 | val 0.67475
  Classification -> best τ=0.500 (val F1=0.5415)
  Directional -> Accuracy: 0.7000, MCC: 0.4120, F1: 0.6809

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.57849 | val 0.79386
  Epoch 015 - train 0.50803 | val 0.69457
  Classification -> best τ=0.425 (val F1=0.4039)
  Directional -> Accuracy: 0.5217, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.59626 | val 1.24494
  Epoch 011 - train 0.55470 | val 1.02607
  Classification -> best τ=0.670 (val F1=0.2827)
  Directional -> Accuracy: 0.5588, MCC: 0.1141, F1: 0.5000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.45930 | val 0.97220
  Epoch 014 - train 0.34843 | val 1.28037
  Classification -> best τ=0.240 (val F1=0.2753)
  Directional -> Accuracy: 0.4524, MCC: 0.1353, F1: 0.6102

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.58114 | val 1.33693
  Epoch 012 - train 0.51273 | val 2.17848
  Classification -> best τ=0.175 (val F1=0.2497)
  Directional -> Accuracy: 0.4375, MCC: 0.0000, F1: 0.6087

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.56054 | val 0.95054
  Epoch 011 - train 0.54589 | val 0.98602
  Classification -> best τ=0.380 (val F1=0.3141)
  Directional -> Accuracy: 0.5072, MCC: 0.0910, F1: 0.5641

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.58130 | val 1.14124
  Epoch 011 - train 0.53710 | val 1.07426
  Classification -> best τ=0.450 (val F1=0.3590)
  Directional -> Accuracy: 0.5918, MCC: 0.1804, F1: 0.2308

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.56402 | val 1.24944
  Epoch 012 - train 0.51693 | val 1.39033
  Classification -> best τ=0.465 (val F1=0.1923)
  Directional -> Accuracy: 0.5965, MCC: 0.3156, F1: 0.7160

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.50811 | val 0.90865
  Epoch 013 - train 0.41616 | val 0.76117
  Classification -> best τ=0.660 (val F1=0.2176)
  Directional -> Accuracy: 0.5476, MCC: 0.0000, F1: 0.0000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.58636 | val 1.78276
  Epoch 015 - train 0.49266 | val 1.07142
  Classification -> best τ=0.380 (val F1=0.2845)
  Directional -> Accuracy: 0.4833, MCC: -0.1302, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.55818 | val 0.93946
  Epoch 020 - train 0.43729 | val 0.79502
  Epoch 025 - train 0.40484 | val 1.51094
  Classification -> best τ=0.690 (val F1=0.3390)
  Directional -> Accuracy: 0.5294, MCC: -0.0591, F1: 0.0769

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.57051 | val 1.78731
  Epoch 013 - train 0.51297 | val 2.71007
  Classification -> best τ=0.735 (val F1=0.3151)
  Directional -> Accuracy: 0.4928, MCC: 0.0035, F1: 0.4444

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.56176 | val 1.57314
  Epoch 011 - train 0.53278 | val 1.79436
  Classification -> best τ=0.275 (val F1=0.1905)
  Directional -> Accuracy: 0.6207, MCC: 0.0000, F1: 0.7660

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.58515 | val 0.92385
  Epoch 020 - train 0.51449 | val 1.13498
  Epoch 023 - train 0.43775 | val 1.07048
  Classification -> best τ=0.560 (val F1=0.1310)
  Directional -> Accuracy: 0.5067, MCC: -0.2178, F1: 0.6667

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.59880 | val 1.45897
  Epoch 011 - train 0.54806 | val 1.70682
  Classification -> best τ=0.195 (val F1=0.2626)
  Directional -> Accuracy: 0.5781, MCC: 0.0000, F1: 0.7327

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.54230 | val 1.05477
  Epoch 011 - train 0.49580 | val 1.13311
  Classification -> best τ=0.600 (val F1=0.2881)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.54649 | val 1.84478
  Epoch 012 - train 0.50050 | val 2.23681
  Classification -> best τ=0.310 (val F1=0.2784)
  Directional -> Accuracy: 0.6170, MCC: 0.0000, F1: 0.7632

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.55939 | val 1.07498
  Epoch 011 - train 0.54271 | val 1.17001
  Classification -> best τ=0.425 (val F1=0.1482)
  Directional -> Accuracy: 0.5077, MCC: 0.0533, F1: 0.1579

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.64985 | val 0.63695
  Epoch 018 - train 0.50638 | val 0.68188
  Classification -> best τ=0.675 (val F1=0.4108)
  Directional -> Accuracy: 0.4211, MCC: -0.1009, F1: 0.1081

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.61026 | val 1.54522
  Epoch 011 - train 0.56541 | val 1.78504
  Classification -> best τ=0.630 (val F1=0.1565)
  Directional -> Accuracy: 0.5385, MCC: 0.0619, F1: 0.2857

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.60017 | val 1.18344
  Epoch 011 - train 0.53601 | val 0.97508
  Classification -> best τ=0.320 (val F1=0.4199)
  Directional -> Accuracy: 0.5455, MCC: 0.0690, F1: 0.6154

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.51489 | val 1.67974
  Epoch 012 - train 0.39894 | val 2.19166
  Classification -> best τ=0.630 (val F1=0.2035)
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.5938

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.58116 | val 0.72120
  Epoch 011 - train 0.55274 | val 0.70107
  Classification -> best τ=0.640 (val F1=0.0278)
  Directional -> Accuracy: 0.5952, MCC: 0.1680, F1: 0.6531

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.53707 | val 1.33121
  Epoch 011 - train 0.52879 | val 1.53913
  Classification -> best τ=0.420 (val F1=0.2976)
  Directional -> Accuracy: 0.4464, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.53106 | val 0.90770
  Epoch 012 - train 0.49468 | val 1.16143
  Classification -> best τ=0.565 (val F1=0.4109)
  Directional -> Accuracy: 0.6000, MCC: 0.2010, F1: 0.7241

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.61929 | val 0.65873
  Epoch 020 - train 0.40792 | val 1.33042
  Classification -> best τ=0.405 (val F1=0.3059)
  Directional -> Accuracy: 0.5238, MCC: 0.0500, F1: 0.5238

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.55016 | val 0.79528
  Epoch 014 - train 0.55055 | val 1.13620
  Classification -> best τ=0.550 (val F1=0.1846)
  Directional -> Accuracy: 0.4524, MCC: -0.0214, F1: 0.0800

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.55383 | val 0.97229
  Epoch 011 - train 0.46980 | val 1.14291
  Classification -> best τ=0.325 (val F1=0.3433)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.59721 | val 0.83000
  Epoch 014 - train 0.53428 | val 0.73438
  Classification -> best τ=0.455 (val F1=0.3450)
  Directional -> Accuracy: 0.5139, MCC: 0.1147, F1: 0.3636

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.49967 | val 1.51757
  Epoch 011 - train 0.45159 | val 1.85011
  Classification -> best τ=0.150 (val F1=0.1095)
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.59896 | val 1.24150
  Epoch 017 - train 0.52244 | val 1.06199
  Classification -> best τ=0.315 (val F1=0.3366)
  Directional -> Accuracy: 0.4697, MCC: 0.1873, F1: 0.1463

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.54721 | val 1.90800
  Epoch 012 - train 0.38699 | val 2.70219
  Classification -> best τ=0.555 (val F1=0.2618)
  Directional -> Accuracy: 0.6905, MCC: 0.4122, F1: 0.6486

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.56792 | val 0.88330
  Epoch 012 - train 0.48621 | val 0.79195
  Classification -> best τ=0.455 (val F1=0.2305)
  Directional -> Accuracy: 0.5893, MCC: 0.2556, F1: 0.2069

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.51064 | val 0.68974
  Epoch 020 - train 0.28167 | val 2.41683
  Classification -> best τ=0.110 (val F1=0.2118)
  Directional -> Accuracy: 0.6087, MCC: 0.0687, F1: 0.7429

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.53893 | val 0.78768
  Epoch 014 - train 0.53985 | val 0.74788
  Classification -> best τ=0.450 (val F1=0.4011)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.57877 | val 0.98920
  Epoch 011 - train 0.53148 | val 1.26362
  Classification -> best τ=0.370 (val F1=0.3263)
  Directional -> Accuracy: 0.5000, MCC: -0.0267, F1: 0.2128

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.59537 | val 0.67958
  Epoch 019 - train 0.51709 | val 0.77486
  Classification -> best τ=0.500 (val F1=0.4080)
  Directional -> Accuracy: 0.5333, MCC: 0.1059, F1: 0.3226

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.57382 | val 0.90575
  Epoch 011 - train 0.34488 | val 0.96974
  Classification -> best τ=0.450 (val F1=0.1667)
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.7273

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.58448 | val 0.72552
  Epoch 016 - train 0.41196 | val 1.03775
  Classification -> best τ=0.395 (val F1=0.2605)
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.5455

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.62054 | val 1.09659
  Epoch 011 - train 0.61428 | val 1.33676
  Classification -> best τ=0.455 (val F1=0.0279)
  Directional -> Accuracy: 0.3636, MCC: -0.2586, F1: 0.2553

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.52606 | val 2.75718
  Epoch 011 - train 0.47896 | val 2.92140
  Classification -> best τ=0.390 (val F1=0.2491)
  Directional -> Accuracy: 0.5000, MCC: 0.1301, F1: 0.6585

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.64575 | val 0.77855
  Epoch 011 - train 0.59155 | val 0.76208
  Classification -> best τ=0.495 (val F1=0.1901)
  Directional -> Accuracy: 0.6981, MCC: 0.3963, F1: 0.7143

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.57502 | val 3.21210
  Epoch 011 - train 0.52236 | val 2.86650
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5273, MCC: 0.0000, F1: 0.6905

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.61991 | val 0.94545

[I 2026-02-22 15:33:50,245] Trial 236 finished with value: 0.26219273864890497 and parameters: {'feature_set': 'sector', 'model_type': 'BiGRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.4, 'batch_size': 16, 'learning_rate': 0.0063108345767153365, 'weight_decay': 0.0002962122616478651, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 0.8610908088640465, 'early_stopping_min_delta': 0.0014020428385621503}. Best is trial 214 with value: 0.2991200218486954.

  Epoch 014 - train 0.52158 | val 1.09539
  Classification -> best τ=0.510 (val F1=0.2920)
  Directional -> Accuracy: 0.5000, MCC: -0.0689, F1: 0.0625

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.26219273864890497
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.65612 | val 1.04988
  Epoch 011 - train 0.58496 | val 1.16280
  Classification -> best τ=0.470 (val F1=0.2919)
  Directional -> Accuracy: 0.5263, MCC: -0.0499, F1: 0.1429

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.49514 | val 1.30273
  Epoch 011 - train 0.47432 | val 1.21614
  Classification -> best τ=0.525 (val F1=0.1764)
  Directional -> Accuracy: 0.6000, MCC: 0.2213, F1: 0.6087

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.56605 | val 1.30833
  Epoch 011 - train 0.54252 | val 1.45270
  Classification -> best τ=0.335 (val F1=0.3159)
  Directional -> Accuracy: 0.5652, MCC: 0.1679, F1: 0.6970

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.59170 | val 1.75726
  Epoch 012 - train 0.53256 | val 1.24650
  Classification -> best τ=0.400 (val F1=0.1269)
  Directional -> Accuracy: 0.5405, MCC: 0.0000, F1: 0.7018

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.48078 | val 1.44566
  Epoch 011 - train 0.46359 | val 1.98576
  Classification -> best τ=0.700 (val F1=0.4556)
  Directional -> Accuracy: 0.6200, MCC: 0.2957, F1: 0.5128

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.50053 | val 0.66941
  Epoch 018 - train 0.35872 | val 0.71981
  Classification -> best τ=0.565 (val F1=0.4885)
  Directional -> Accuracy: 0.5217, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.61804 | val 0.87804
  Epoch 013 - train 0.54071 | val 1.60455
  Classification -> best τ=0.415 (val F1=0.3336)
  Directional -> Accuracy: 0.5735, MCC: 0.1904, F1: 0.5672

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.57343 | val 0.66710
  Epoch 013 - train 0.41501 | val 0.94656
  Classification -> best τ=0.190 (val F1=0.1657)
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.60681 | val 1.75025
  Epoch 011 - train 0.50701 | val 2.18677
  Classification -> best τ=0.405 (val F1=0.2497)
  Directional -> Accuracy: 0.4375, MCC: 0.0000, F1: 0.6087

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.56821 | val 0.76344
  Epoch 019 - train 0.47218 | val 0.88456
  Classification -> best τ=0.910 (val F1=0.1607)
  Directional -> Accuracy: 0.5072, MCC: -0.0310, F1: 0.3704

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.60586 | val 0.77162
  Epoch 017 - train 0.44232 | val 0.75786
  Classification -> best τ=0.580 (val F1=0.2498)
  Directional -> Accuracy: 0.5714, MCC: 0.1118, F1: 0.1600

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.58631 | val 0.73594
  Epoch 014 - train 0.51543 | val 1.17313
  Classification -> best τ=0.740 (val F1=0.2083)
  Directional -> Accuracy: 0.4561, MCC: -0.0874, F1: 0.4561

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.49978 | val 0.83246
  Epoch 011 - train 0.39576 | val 0.73146
  Classification -> best τ=0.535 (val F1=0.2850)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.6230

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.61435 | val 0.64193
  Epoch 020 - train 0.52329 | val 0.72360
  Classification -> best τ=0.505 (val F1=0.3126)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.57574 | val 0.82868
  Epoch 012 - train 0.50713 | val 1.05558
  Classification -> best τ=0.485 (val F1=0.1455)
  Directional -> Accuracy: 0.5490, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.59276 | val 1.11340
  Epoch 012 - train 0.53818 | val 1.55955
  Classification -> best τ=0.245 (val F1=0.3949)
  Directional -> Accuracy: 0.6087, MCC: 0.2651, F1: 0.7273

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.59667 | val 1.30197
  Epoch 011 - train 0.51701 | val 1.19367
  Classification -> best τ=0.320 (val F1=0.1336)
  Directional -> Accuracy: 0.6207, MCC: 0.1270, F1: 0.7317

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.56399 | val 0.98906
  Epoch 011 - train 0.56474 | val 1.12483
  Classification -> best τ=0.570 (val F1=0.2220)
  Directional -> Accuracy: 0.4000, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.57022 | val 1.53207
  Epoch 012 - train 0.48238 | val 1.74264
  Classification -> best τ=0.335 (val F1=0.2433)
  Directional -> Accuracy: 0.5000, MCC: 0.1376, F1: 0.3333

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.55376 | val 1.03764
  Epoch 011 - train 0.51392 | val 1.14620
  Classification -> best τ=0.360 (val F1=0.2699)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.54824 | val 1.03157
  Epoch 013 - train 0.41624 | val 0.77754
  Classification -> best τ=0.535 (val F1=0.1979)
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.57595 | val 2.39619
  Epoch 011 - train 0.50562 | val 2.06220
  Classification -> best τ=0.515 (val F1=0.1925)
  Directional -> Accuracy: 0.4923, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.66445 | val 0.79785
  Epoch 020 - train 0.54828 | val 1.71603
  Classification -> best τ=0.570 (val F1=0.4074)
  Directional -> Accuracy: 0.6140, MCC: 0.2525, F1: 0.6071

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.59949 | val 0.76570
  Epoch 013 - train 0.52784 | val 0.75223
  Classification -> best τ=0.745 (val F1=0.1985)
  Directional -> Accuracy: 0.5231, MCC: 0.0000, F1: 0.0000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.52653 | val 1.02731
  Epoch 011 - train 0.48499 | val 0.94022
  Classification -> best τ=0.600 (val F1=0.3823)
  Directional -> Accuracy: 0.4364, MCC: -0.1491, F1: 0.0000

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.48813 | val 4.21840
  Epoch 011 - train 0.43403 | val 4.64885
  Classification -> best τ=0.675 (val F1=0.2241)
  Directional -> Accuracy: 0.5111, MCC: 0.2670, F1: 0.6333

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.56159 | val 0.77730
  Epoch 013 - train 0.46558 | val 0.76289
  Classification -> best τ=0.605 (val F1=0.2402)
  Directional -> Accuracy: 0.5000, MCC: 0.1698, F1: 0.2759

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.57771 | val 1.14968
  Epoch 012 - train 0.51967 | val 1.65130
  Classification -> best τ=0.315 (val F1=0.1860)
  Directional -> Accuracy: 0.4464, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.52952 | val 1.53288
  Epoch 011 - train 0.44192 | val 1.26878
  Classification -> best τ=0.685 (val F1=0.1748)
  Directional -> Accuracy: 0.6250, MCC: 0.2335, F1: 0.6809

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.59342 | val 1.15717
  Epoch 012 - train 0.56171 | val 1.16585
  Classification -> best τ=0.335 (val F1=0.4083)
  Directional -> Accuracy: 0.5000, MCC: 0.0196, F1: 0.5714

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.58418 | val 2.52434
  Epoch 013 - train 0.54885 | val 0.83053
  Classification -> best τ=0.590 (val F1=0.3419)
  Directional -> Accuracy: 0.4048, MCC: -0.1870, F1: 0.4186

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.55493 | val 1.19959
  Epoch 011 - train 0.46222 | val 1.16485
  Classification -> best τ=0.385 (val F1=0.4120)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.62841 | val 1.40756
  Epoch 015 - train 0.46364 | val 0.76958
  Classification -> best τ=0.595 (val F1=0.3129)
  Directional -> Accuracy: 0.4583, MCC: 0.1061, F1: 0.0488

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.57382 | val 0.96557
  Epoch 012 - train 0.45941 | val 1.03279
  Classification -> best τ=0.660 (val F1=0.2603)
  Directional -> Accuracy: 0.5349, MCC: 0.0691, F1: 0.3333

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.59011 | val 1.54908
  Epoch 011 - train 0.57896 | val 1.59216
  Classification -> best τ=0.550 (val F1=0.2329)
  Directional -> Accuracy: 0.5758, MCC: 0.0000, F1: 0.7308

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.44081 | val 0.77152
  Epoch 011 - train 0.40544 | val 0.86440
  Classification -> best τ=0.505 (val F1=0.2618)
  Directional -> Accuracy: 0.6667, MCC: 0.3920, F1: 0.5882

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.58897 | val 1.19648
  Epoch 017 - train 0.43241 | val 1.13065
  Classification -> best τ=0.445 (val F1=0.2417)
  Directional -> Accuracy: 0.6250, MCC: 0.2455, F1: 0.4878

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.46233 | val 0.94820
  Epoch 011 - train 0.44308 | val 0.89720
  Classification -> best τ=0.500 (val F1=0.2815)
  Directional -> Accuracy: 0.6087, MCC: 0.0000, F1: 0.7568

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.56812 | val 0.67987
  Epoch 018 - train 0.41195 | val 0.75109
  Classification -> best τ=0.265 (val F1=0.4855)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.58679 | val 2.18209
  Epoch 011 - train 0.48594 | val 2.36984
  Classification -> best τ=0.180 (val F1=0.2397)
  Directional -> Accuracy: 0.4865, MCC: 0.0000, F1: 0.6545

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.55330 | val 0.93221
  Epoch 017 - train 0.42261 | val 1.12140
  Classification -> best τ=0.555 (val F1=0.4632)
  Directional -> Accuracy: 0.5778, MCC: 0.1633, F1: 0.5366

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.42417 | val 1.97974
  Epoch 012 - train 0.42096 | val 1.87970
  Classification -> best τ=0.570 (val F1=0.4001)
  Directional -> Accuracy: 0.5952, MCC: 0.1925, F1: 0.6222

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.46290 | val 0.86975
  Epoch 020 - train 0.34420 | val 1.10947
  Classification -> best τ=0.225 (val F1=0.4682)
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.5455

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.68090 | val 2.31641
  Epoch 011 - train 0.63321 | val 1.94928
  Classification -> best τ=0.540 (val F1=0.2036)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.44984 | val 3.97562
  Epoch 011 - train 0.39503 | val 4.17566
  Classification -> best τ=0.550 (val F1=0.2649)
  Directional -> Accuracy: 0.5179, MCC: 0.0206, F1: 0.3415

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.64310 | val 0.83698
  Epoch 011 - train 0.59633 | val 0.85526
  Classification -> best τ=0.525 (val F1=0.1824)
  Directional -> Accuracy: 0.5283, MCC: 0.1413, F1: 0.6835

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.53163 | val 1.48331
  Epoch 015 - train 0.45900 | val 2.71342
  Classification -> best τ=0.785 (val F1=0.2786)
  Directional -> Accuracy: 0.4727, MCC: -0.0106, F1: 0.0645

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.64501 | val 0.68026

[I 2026-02-22 15:38:25,043] Trial 237 finished with value: 0.27990676787915064 and parameters: {'feature_set': 'sector', 'model_type': 'BiGRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.4, 'batch_size': 16, 'learning_rate': 0.00688574250216942, 'weight_decay': 0.00021769465290604023, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 20, 'huber_delta': 0.9344981058820571, 'early_stopping_min_delta': 0.001368475661800955}. Best is trial 214 with value: 0.2991200218486954.

  Epoch 016 - train 0.52667 | val 1.02036
  Classification -> best τ=0.580 (val F1=0.2623)
  Directional -> Accuracy: 0.5167, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.27990676787915064
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'positive_emotion', 'negative_emotion', 'uncertainty_emotion', 'positive_emotion_pct', 'negative_emotion_pct', 'uncertainty_emotion_pct']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.59957 | val 0.72310
  Epoch 014 - train 0.52133 | val 1.26015
  Classification -> best τ=0.630 (val F1=0.3286)
  Directional -> Accuracy: 0.5395, MCC: -0.0022, F1: 0.1860

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.44699 | val 1.67199
  Epoch 011 - train 0.52302 | val 1.38062
  Classification -> best τ=0.540 (val F1=0.0492)
  Directional -> Accuracy: 0.6222, MCC: 0.1967, F1: 0.7119

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.60764 | val 1.19594
  Epoch 017 - train 0.41864 | val 1.61598
  Classification -> best τ=0.585 (val F1=0.5000)
  Directional -> Accuracy: 0.5870, MCC: 0.1774, F1: 0.6780

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.61273 | val 3.10368
  Epoch 011 - train 0.61537 | val 1.50713
  Classification -> best τ=0.355 (val F1=0.0759)
  Directional -> Accuracy: 0.5405, MCC: 0.0000, F1: 0.7018

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.52851 | val 1.18602
  Epoch 012 - train 0.45472 | val 0.87008
  Classification -> best τ=0.395 (val F1=0.4602)
  Directional -> Accuracy: 0.5400, MCC: 0.1487, F1: 0.6933

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.54120 | val 0.73501
  Epoch 013 - train 0.42804 | val 0.98611
  Classification -> best τ=0.550 (val F1=0.3525)
  Directional -> Accuracy: 0.5217, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.62290 | val 0.95052
  Epoch 011 - train 0.61376 | val 0.92756
  Classification -> best τ=0.285 (val F1=0.2195)
  Directional -> Accuracy: 0.4412, MCC: 0.1135, F1: 0.5778

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.46041 | val 0.85834
  Epoch 013 - train 0.44896 | val 1.03459
  Classification -> best τ=0.490 (val F1=0.3632)
  Directional -> Accuracy: 0.5000, MCC: 0.0280, F1: 0.5116

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.51991 | val 1.59794
  Epoch 011 - train 0.43044 | val 1.78307
  Classification -> best τ=0.385 (val F1=0.1402)
  Directional -> Accuracy: 0.4375, MCC: 0.0000, F1: 0.6087

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.51176 | val 0.89573
  Epoch 011 - train 0.51310 | val 0.98271
  Classification -> best τ=0.530 (val F1=0.1607)
  Directional -> Accuracy: 0.4928, MCC: -0.0562, F1: 0.3636

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.53503 | val 2.49687
  Epoch 013 - train 0.49884 | val 1.41875
  Classification -> best τ=0.610 (val F1=0.2543)
  Directional -> Accuracy: 0.6327, MCC: 0.2887, F1: 0.3571

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.61079 | val 1.10780
  Epoch 012 - train 0.55570 | val 0.83830
  Classification -> best τ=0.675 (val F1=0.2875)
  Directional -> Accuracy: 0.5614, MCC: 0.1265, F1: 0.6377

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.58494 | val 0.74339
  Epoch 020 - train 0.57248 | val 1.12562
  Epoch 024 - train 0.40235 | val 1.24709
  Classification -> best τ=0.335 (val F1=0.2466)
  Directional -> Accuracy: 0.4286, MCC: -0.1194, F1: 0.5862

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.61095 | val 0.62541
  Epoch 020 - train 0.51990 | val 0.83638
  Epoch 022 - train 0.49561 | val 0.89571
  Classification -> best τ=0.360 (val F1=0.4133)
  Directional -> Accuracy: 0.4833, MCC: -0.0467, F1: 0.6173

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.54187 | val 0.75675
  Epoch 012 - train 0.46878 | val 0.84469
  Classification -> best τ=0.555 (val F1=0.2078)
  Directional -> Accuracy: 0.5490, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.66186 | val 0.80680
  Epoch 014 - train 0.53686 | val 1.39468
  Classification -> best τ=0.525 (val F1=0.3435)
  Directional -> Accuracy: 0.5942, MCC: 0.1755, F1: 0.6818

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.60944 | val 1.01536
  Epoch 015 - train 0.50185 | val 0.78728
  Classification -> best τ=0.570 (val F1=0.0290)
  Directional -> Accuracy: 0.3793, MCC: -0.0995, F1: 0.1818

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.65117 | val 0.74480
  Epoch 014 - train 0.59231 | val 0.91193
  Classification -> best τ=0.640 (val F1=0.2500)
  Directional -> Accuracy: 0.4000, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.57023 | val 0.82240
  Epoch 013 - train 0.53312 | val 0.82589
  Classification -> best τ=0.820 (val F1=0.2289)
  Directional -> Accuracy: 0.4375, MCC: 0.1076, F1: 0.0526

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.57448 | val 0.82668
  Epoch 011 - train 0.55348 | val 0.75144
  Classification -> best τ=0.280 (val F1=0.2333)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.51828 | val 1.80731
  Epoch 011 - train 0.51448 | val 2.11559
  Classification -> best τ=0.580 (val F1=0.2295)
  Directional -> Accuracy: 0.4894, MCC: -0.1303, F1: 0.6129

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.65150 | val 1.24149
  Epoch 011 - train 0.58942 | val 1.76210
  Classification -> best τ=0.350 (val F1=0.1999)
  Directional -> Accuracy: 0.4154, MCC: -0.1686, F1: 0.3871

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.59065 | val 0.68048
  Epoch 011 - train 0.58061 | val 0.70330
  Classification -> best τ=0.640 (val F1=0.4319)
  Directional -> Accuracy: 0.4386, MCC: -0.0639, F1: 0.2727

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.55694 | val 0.73368
  Epoch 011 - train 0.53765 | val 0.74790
  Classification -> best τ=0.495 (val F1=0.2552)
  Directional -> Accuracy: 0.5538, MCC: 0.1396, F1: 0.6234

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.58400 | val 1.76726
  Epoch 012 - train 0.48011 | val 1.73895
  Classification -> best τ=0.705 (val F1=0.4839)
  Directional -> Accuracy: 0.5273, MCC: 0.1143, F1: 0.4091

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.44091 | val 2.33891
  Epoch 011 - train 0.42860 | val 2.57428
  Classification -> best τ=0.775 (val F1=0.2318)
  Directional -> Accuracy: 0.5111, MCC: -0.0165, F1: 0.3889

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.49898 | val 0.91513
  Epoch 012 - train 0.49098 | val 0.86869
  Classification -> best τ=0.535 (val F1=0.2582)
  Directional -> Accuracy: 0.5238, MCC: 0.0694, F1: 0.5238

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.60743 | val 1.37033
  Epoch 011 - train 0.53031 | val 1.43640
  Classification -> best τ=0.435 (val F1=0.2114)
  Directional -> Accuracy: 0.4286, MCC: -0.1502, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.38648 | val 2.43265
  Epoch 011 - train 0.31922 | val 2.48853
  Classification -> best τ=0.505 (val F1=0.3278)
  Directional -> Accuracy: 0.5750, MCC: 0.1770, F1: 0.7213

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.57707 | val 0.90317
  Epoch 011 - train 0.48933 | val 0.85192
  Classification -> best τ=0.555 (val F1=0.0344)
  Directional -> Accuracy: 0.5238, MCC: 0.0754, F1: 0.6000

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.53878 | val 1.33283
  Epoch 015 - train 0.43383 | val 4.19030
  Classification -> best τ=0.480 (val F1=0.2544)
  Directional -> Accuracy: 0.4286, MCC: -0.1194, F1: 0.0769

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.55094 | val 1.03261
  Epoch 011 - train 0.52506 | val 1.17031
  Classification -> best τ=0.375 (val F1=0.3541)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.62073 | val 0.80332
  Epoch 011 - train 0.58055 | val 0.89721
  Classification -> best τ=0.295 (val F1=0.2513)
  Directional -> Accuracy: 0.5694, MCC: 0.1309, F1: 0.6076

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.60249 | val 1.07160
  Epoch 011 - train 0.55430 | val 1.34839
  Classification -> best τ=0.725 (val F1=0.2151)
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.58662 | val 0.81551
  Epoch 015 - train 0.49028 | val 1.25107
  Classification -> best τ=0.315 (val F1=0.2941)
  Directional -> Accuracy: 0.4848, MCC: 0.0116, F1: 0.4516

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.42982 | val 1.63824
  Epoch 012 - train 0.33346 | val 2.34018
  Classification -> best τ=0.575 (val F1=0.3589)
  Directional -> Accuracy: 0.6190, MCC: 0.3091, F1: 0.5000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.55468 | val 0.85918
  Epoch 011 - train 0.53835 | val 0.92819
  Classification -> best τ=0.415 (val F1=0.2804)
  Directional -> Accuracy: 0.4821, MCC: -0.0437, F1: 0.4314

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.46444 | val 1.12197
  Epoch 012 - train 0.30928 | val 1.28930
  Classification -> best τ=0.580 (val F1=0.3372)
  Directional -> Accuracy: 0.3696, MCC: -0.1493, F1: 0.1212

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.51111 | val 1.67069
  Epoch 011 - train 0.36350 | val 1.74802
  Classification -> best τ=0.720 (val F1=0.3800)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.59444 | val 0.97497
  Epoch 017 - train 0.49692 | val 1.48230
  Classification -> best τ=0.430 (val F1=0.2965)
  Directional -> Accuracy: 0.5000, MCC: 0.0466, F1: 0.6476

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.55260 | val 0.88778
  Epoch 011 - train 0.51506 | val 0.95138
  Classification -> best τ=0.470 (val F1=0.1890)
  Directional -> Accuracy: 0.5333, MCC: 0.2109, F1: 0.1600

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.48965 | val 1.03132
  Epoch 015 - train 0.21583 | val 2.43103
  Classification -> best τ=0.200 (val F1=0.3015)
  Directional -> Accuracy: 0.5952, MCC: 0.1334, F1: 0.7302

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.54811 | val 1.63026
  Epoch 011 - train 0.47712 | val 1.84732
  Classification -> best τ=0.490 (val F1=0.5421)
  Directional -> Accuracy: 0.3750, MCC: -0.0778, F1: 0.5161

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.59002 | val 0.84745
  Epoch 011 - train 0.58637 | val 0.88163
  Classification -> best τ=0.680 (val F1=0.1647)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.52884 | val 2.19528
  Epoch 011 - train 0.49009 | val 2.35948
  Classification -> best τ=0.615 (val F1=0.3729)
  Directional -> Accuracy: 0.5357, MCC: 0.0728, F1: 0.5357

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.62008 | val 0.79253
  Epoch 013 - train 0.52202 | val 1.01312
  Classification -> best τ=0.580 (val F1=0.2139)
  Directional -> Accuracy: 0.4528, MCC: -0.1483, F1: 0.0645

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.57026 | val 2.00316
  Epoch 011 - train 0.49161 | val 2.26390
  Classification -> best τ=0.800 (val F1=0.2967)
  Directional -> Accuracy: 0.5273, MCC: 0.0106, F1: 0.6829

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.63476 | val 0.72101
  Epoch 020 - train 0.55267 | val 1.33495

[I 2026-02-22 15:42:55,242] Trial 238 finished with value: 0.27775621963494374 and parameters: {'feature_set': 'unified_emotion', 'model_type': 'BiGRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.4, 'batch_size': 16, 'learning_rate': 0.005726858635347879, 'weight_decay': 0.00018939944634864493, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 0.9085529861479842, 'early_stopping_min_delta': 0.0021473744336007136}. Best is trial 214 with value: 0.2991200218486954.

  Epoch 025 - train 0.39821 | val 1.01845
  Classification -> best τ=0.510 (val F1=0.4212)
  Directional -> Accuracy: 0.6000, MCC: 0.2313, F1: 0.4000

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.27775621963494374
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.63109 | val 0.88512
  Epoch 011 - train 0.59420 | val 1.18720
  Classification -> best τ=0.775 (val F1=0.2510)
  Directional -> Accuracy: 0.5395, MCC: -0.1039, F1: 0.0000

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.59098 | val 0.81145
  Epoch 011 - train 0.50149 | val 0.83655
  Classification -> best τ=0.575 (val F1=0.2523)
  Directional -> Accuracy: 0.5333, MCC: 0.2025, F1: 0.4000

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.54651 | val 1.75797
  Epoch 011 - train 0.52249 | val 2.01943
  Classification -> best τ=0.845 (val F1=0.2727)
  Directional -> Accuracy: 0.5217, MCC: 0.1124, F1: 0.2667

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.61570 | val 1.08845
  Epoch 012 - train 0.54327 | val 1.19049
  Classification -> best τ=0.545 (val F1=0.1895)
  Directional -> Accuracy: 0.4595, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.57467 | val 1.30133
  Epoch 016 - train 0.41471 | val 2.24826
  Classification -> best τ=0.860 (val F1=0.5079)
  Directional -> Accuracy: 0.5800, MCC: 0.2044, F1: 0.4615

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.51597 | val 0.95820
  Epoch 015 - train 0.33759 | val 1.18123
  Classification -> best τ=0.610 (val F1=0.3210)
  Directional -> Accuracy: 0.5217, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.62007 | val 1.12822
  Epoch 012 - train 0.59059 | val 1.10740
  Classification -> best τ=0.440 (val F1=0.2389)
  Directional -> Accuracy: 0.4118, MCC: 0.0991, F1: 0.5745

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.46632 | val 1.01664
  Epoch 014 - train 0.39379 | val 2.29337
  Classification -> best τ=0.195 (val F1=0.3689)
  Directional -> Accuracy: 0.4286, MCC: -0.0589, F1: 0.5556

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.54962 | val 2.13776
  Epoch 011 - train 0.52434 | val 2.33136
  Classification -> best τ=0.515 (val F1=0.2285)
  Directional -> Accuracy: 0.5417, MCC: 0.1127, F1: 0.5600

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.57511 | val 0.92883
  Epoch 011 - train 0.55156 | val 1.07329
  Classification -> best τ=0.545 (val F1=0.2776)
  Directional -> Accuracy: 0.5507, MCC: 0.2601, F1: 0.6353

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.58821 | val 1.94482
  Epoch 012 - train 0.50270 | val 1.84410
  Classification -> best τ=0.520 (val F1=0.2995)
  Directional -> Accuracy: 0.5918, MCC: 0.1804, F1: 0.2308

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.52642 | val 0.83011
  Epoch 012 - train 0.48042 | val 1.11443
  Classification -> best τ=0.540 (val F1=0.3307)
  Directional -> Accuracy: 0.5439, MCC: 0.0874, F1: 0.5517

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.53095 | val 0.93112
  Epoch 016 - train 0.34192 | val 0.90281
  Classification -> best τ=0.650 (val F1=0.2884)
  Directional -> Accuracy: 0.5476, MCC: 0.0000, F1: 0.0000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.60422 | val 0.79540
  Epoch 012 - train 0.51993 | val 0.85789
  Classification -> best τ=0.575 (val F1=0.3642)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.55449 | val 0.74221
  Epoch 011 - train 0.51579 | val 0.72349
  Classification -> best τ=0.520 (val F1=0.2078)
  Directional -> Accuracy: 0.5490, MCC: 0.0199, F1: 0.0800

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.61363 | val 2.17389
  Epoch 014 - train 0.59669 | val 1.19439
  Classification -> best τ=0.890 (val F1=0.2457)
  Directional -> Accuracy: 0.4493, MCC: -0.0867, F1: 0.0500

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.57553 | val 1.42314
  Epoch 014 - train 0.53250 | val 1.19500
  Classification -> best τ=0.350 (val F1=0.2885)
  Directional -> Accuracy: 0.3793, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.57560 | val 0.80711
  Epoch 012 - train 0.51666 | val 0.86309
  Classification -> best τ=0.520 (val F1=0.2500)
  Directional -> Accuracy: 0.4267, MCC: 0.1351, F1: 0.0851

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.68657 | val 1.00346
  Epoch 012 - train 0.49688 | val 1.19945
  Classification -> best τ=0.320 (val F1=0.2493)
  Directional -> Accuracy: 0.5469, MCC: 0.0286, F1: 0.6506

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.51164 | val 0.95912
  Epoch 011 - train 0.47256 | val 1.16961
  Classification -> best τ=0.415 (val F1=0.2357)
  Directional -> Accuracy: 0.4730, MCC: 0.1495, F1: 0.0930

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.56647 | val 3.52790
  Epoch 011 - train 0.50806 | val 3.44871
  Classification -> best τ=0.375 (val F1=0.1723)
  Directional -> Accuracy: 0.5106, MCC: 0.1602, F1: 0.4390

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.55985 | val 2.30728
  Epoch 011 - train 0.52567 | val 3.14305
  Classification -> best τ=0.425 (val F1=0.1650)
  Directional -> Accuracy: 0.6000, MCC: 0.1998, F1: 0.6061

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.65646 | val 0.60933
  Epoch 019 - train 0.54262 | val 2.81688
  Classification -> best τ=0.605 (val F1=0.4597)
  Directional -> Accuracy: 0.6316, MCC: 0.2487, F1: 0.6769

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.59098 | val 1.04614
  Epoch 014 - train 0.55249 | val 0.76830
  Classification -> best τ=0.645 (val F1=0.1985)
  Directional -> Accuracy: 0.5231, MCC: 0.0118, F1: 0.1143

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.53091 | val 1.08563
  Epoch 011 - train 0.48185 | val 1.06143
  Classification -> best τ=0.340 (val F1=0.3851)
  Directional -> Accuracy: 0.6000, MCC: 0.1884, F1: 0.7105

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.47027 | val 1.72648
  Epoch 011 - train 0.41023 | val 2.17362
  Classification -> best τ=0.725 (val F1=0.1819)
  Directional -> Accuracy: 0.4667, MCC: 0.1844, F1: 0.6129

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.56824 | val 0.70697
  Epoch 020 - train 0.44252 | val 0.89866
  Epoch 021 - train 0.32223 | val 0.95881
  Classification -> best τ=0.620 (val F1=0.3184)
  Directional -> Accuracy: 0.4286, MCC: -0.0589, F1: 0.2000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.52212 | val 2.22138
  Epoch 012 - train 0.49010 | val 2.80678
  Classification -> best τ=0.435 (val F1=0.2742)
  Directional -> Accuracy: 0.4464, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.52275 | val 1.77042
  Epoch 011 - train 0.48164 | val 1.90063
  Classification -> best τ=0.510 (val F1=0.1748)
  Directional -> Accuracy: 0.6250, MCC: 0.2347, F1: 0.7170

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.55935 | val 1.06085
  Epoch 011 - train 0.52383 | val 1.50389
  Classification -> best τ=0.465 (val F1=0.3656)
  Directional -> Accuracy: 0.4524, MCC: -0.0853, F1: 0.5106

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.51444 | val 0.84815
  Epoch 011 - train 0.50741 | val 0.80474
  Classification -> best τ=0.390 (val F1=0.0806)
  Directional -> Accuracy: 0.4048, MCC: -0.2368, F1: 0.5098

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.53483 | val 0.90322
  Epoch 011 - train 0.46610 | val 1.26028
  Classification -> best τ=0.200 (val F1=0.3714)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.60754 | val 0.67533
  Epoch 016 - train 0.47369 | val 0.97614
  Classification -> best τ=0.600 (val F1=0.3654)
  Directional -> Accuracy: 0.5417, MCC: 0.2535, F1: 0.3265

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.53399 | val 1.93918
  Epoch 013 - train 0.41364 | val 1.91787
  Classification -> best τ=0.380 (val F1=0.1309)
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.56055 | val 1.66507
  Epoch 011 - train 0.54956 | val 1.76667
  Classification -> best τ=0.330 (val F1=0.2820)
  Directional -> Accuracy: 0.5758, MCC: 0.0000, F1: 0.7308

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.46960 | val 1.90596
  Epoch 011 - train 0.40296 | val 1.73244
  Classification -> best τ=0.550 (val F1=0.2228)
  Directional -> Accuracy: 0.6429, MCC: 0.3511, F1: 0.5455

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.54986 | val 1.30673
  Epoch 011 - train 0.48679 | val 1.24833
  Classification -> best τ=0.710 (val F1=0.2305)
  Directional -> Accuracy: 0.5714, MCC: 0.2067, F1: 0.1429

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.46203 | val 1.10246
  Epoch 011 - train 0.40918 | val 1.11826
  Classification -> best τ=0.560 (val F1=0.4547)
  Directional -> Accuracy: 0.4348, MCC: -0.1055, F1: 0.4583

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.51164 | val 0.62443
  Epoch 019 - train 0.46287 | val 1.20427
  Classification -> best τ=0.430 (val F1=0.4011)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.61190 | val 0.82713
  Epoch 012 - train 0.50762 | val 1.09788
  Classification -> best τ=0.380 (val F1=0.3880)
  Directional -> Accuracy: 0.4595, MCC: -0.0819, F1: 0.4444

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.56645 | val 0.94978
  Epoch 013 - train 0.48036 | val 1.14166
  Classification -> best τ=0.565 (val F1=0.2712)
  Directional -> Accuracy: 0.4667, MCC: -0.1541, F1: 0.0000

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.41680 | val 1.87634
  Epoch 013 - train 0.30448 | val 2.68615
  Classification -> best τ=0.650 (val F1=0.4082)
  Directional -> Accuracy: 0.5000, MCC: 0.0138, F1: 0.5116

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.51289 | val 1.12988
  Epoch 011 - train 0.46449 | val 0.68946
  Classification -> best τ=0.595 (val F1=0.6590)
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.0000

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.62899 | val 2.88158
  Epoch 011 - train 0.61861 | val 2.47991
  Classification -> best τ=0.690 (val F1=0.1647)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.49043 | val 2.55773
  Epoch 011 - train 0.43900 | val 3.70720
  Classification -> best τ=0.350 (val F1=0.2137)
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.6506

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.59542 | val 1.00203
  Epoch 015 - train 0.52805 | val 0.74977
  Classification -> best τ=0.500 (val F1=0.2317)
  Directional -> Accuracy: 0.6038, MCC: 0.2103, F1: 0.5882

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.47119 | val 3.35348
  Epoch 011 - train 0.48328 | val 3.72727
  Classification -> best τ=0.590 (val F1=0.0322)
  Directional -> Accuracy: 0.4364, MCC: -0.1359, F1: 0.1143

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.62347 | val 0.74441

[I 2026-02-22 15:47:17,614] Trial 239 finished with value: 0.2823015416747082 and parameters: {'feature_set': 'sector', 'model_type': 'BiGRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.4, 'batch_size': 16, 'learning_rate': 0.007480837770150452, 'weight_decay': 0.00010063224176966926, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 0.8859375133083845, 'early_stopping_min_delta': 0.0017330407488959792}. Best is trial 214 with value: 0.2991200218486954.

  Epoch 012 - train 0.56312 | val 0.74973
  Classification -> best τ=0.395 (val F1=0.2787)
  Directional -> Accuracy: 0.5500, MCC: 0.0965, F1: 0.5091

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2823015416747082
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sentiment', 'emotion_anger', 'emotion_disgust', 'emotion_fear', 'emotion_joy', 'emotion_neutral', 'emotion_sadness', 'emotion_surprize', 'emotion_anger_pct', 'emotion_disgust_pct', 'emotion_fear_pct', 'emotion_joy_pct', 'emotion_neutral_pct', 'emotion_sadness_pct', 'emotion_surprize_pct', 'positive_emotion', 'negative_emotion', 'uncertainty_emotion', 'positive_emotion_pct', 'negative_emotion_pct', 'uncertainty_emotion_pct', 'stance_label', 'stance_score', 'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down', 'finbert_neutral']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.58734 | val 0.98766
  Epoch 012 - train 0.33871 | val 1.28521
  Classification -> best τ=0.400 (val F1=0.2116)
  Directional -> Accuracy: 0.5526, MCC: 0.1468, F1: 0.5952

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.47161 | val 1.47817
  Epoch 012 - train 0.30335 | val 1.86248
  Classification -> best τ=0.460 (val F1=0.1941)
  Directional -> Accuracy: 0.5111, MCC: -0.0020, F1: 0.5769

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.39187 | val 1.60590
  Epoch 012 - train 0.19117 | val 1.29202
  Classification -> best τ=0.510 (val F1=0.4252)
  Directional -> Accuracy: 0.5652, MCC: 0.1510, F1: 0.5000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.56255 | val 0.92210
  Epoch 020 - train 0.38810 | val 1.86391
  Epoch 025 - train 0.18843 | val 4.09832
  Classification -> best τ=0.625 (val F1=0.2090)
  Directional -> Accuracy: 0.5135, MCC: 0.0076, F1: 0.5814

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.28477 | val 1.75788
  Epoch 011 - train 0.19272 | val 2.33109
  Classification -> best τ=0.525 (val F1=0.2934)
  Directional -> Accuracy: 0.5200, MCC: 0.1084, F1: 0.2500

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.27880 | val 1.11001
  Epoch 013 - train 0.08312 | val 2.45695
  Classification -> best τ=0.330 (val F1=0.2593)
  Directional -> Accuracy: 0.6087, MCC: 0.2241, F1: 0.4706

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.42945 | val 1.35165
  Epoch 013 - train 0.19070 | val 2.21336
  Classification -> best τ=0.635 (val F1=0.1923)
  Directional -> Accuracy: 0.5441, MCC: -0.0250, F1: 0.2791

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.18702 | val 0.77070
  Epoch 011 - train 0.10175 | val 0.99778
  Classification -> best τ=0.420 (val F1=0.3632)
  Directional -> Accuracy: 0.5000, MCC: -0.0280, F1: 0.4000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.34105 | val 2.96294
  Epoch 011 - train 0.20247 | val 3.14310
  Classification -> best τ=0.455 (val F1=0.2925)
  Directional -> Accuracy: 0.4375, MCC: 0.0000, F1: 0.6087

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.38623 | val 0.87616
  Epoch 011 - train 0.30697 | val 1.05113
  Classification -> best τ=0.460 (val F1=0.3560)
  Directional -> Accuracy: 0.4348, MCC: -0.0495, F1: 0.5301

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.33569 | val 3.47452
  Epoch 011 - train 0.23664 | val 3.63389
  Classification -> best τ=0.620 (val F1=0.0385)
  Directional -> Accuracy: 0.5714, MCC: 0.1016, F1: 0.3226

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.46280 | val 1.51174
  Epoch 012 - train 0.26537 | val 1.13404
  Classification -> best τ=0.630 (val F1=0.3426)
  Directional -> Accuracy: 0.5088, MCC: 0.0359, F1: 0.3000

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.43296 | val 1.15820
  Epoch 013 - train 0.16811 | val 1.78863
  Classification -> best τ=0.405 (val F1=0.1316)
  Directional -> Accuracy: 0.5476, MCC: 0.1220, F1: 0.5778

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.36620 | val 1.45902
  Epoch 012 - train 0.24682 | val 1.38390
  Classification -> best τ=0.410 (val F1=0.1668)
  Directional -> Accuracy: 0.4333, MCC: -0.1414, F1: 0.3200

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.41779 | val 0.74899
  Epoch 011 - train 0.28631 | val 1.22990
  Classification -> best τ=0.480 (val F1=0.2141)
  Directional -> Accuracy: 0.6275, MCC: 0.2806, F1: 0.3448

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.51803 | val 1.12193
  Epoch 016 - train 0.23006 | val 0.99979
  Classification -> best τ=0.330 (val F1=0.3339)
  Directional -> Accuracy: 0.5072, MCC: -0.0645, F1: 0.6531

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.50241 | val 1.98700
  Epoch 011 - train 0.35846 | val 3.11491
  Classification -> best τ=0.665 (val F1=0.2186)
  Directional -> Accuracy: 0.3621, MCC: -0.1467, F1: 0.1395

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.44576 | val 1.26967
  Epoch 011 - train 0.35392 | val 1.84828
  Classification -> best τ=0.380 (val F1=0.1769)
  Directional -> Accuracy: 0.6133, MCC: 0.1424, F1: 0.7563

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.38416 | val 1.90003
  Epoch 011 - train 0.34348 | val 1.42478
  Classification -> best τ=0.320 (val F1=0.1846)
  Directional -> Accuracy: 0.4219, MCC: -0.1309, F1: 0.4127

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.48458 | val 1.27132
  Epoch 011 - train 0.43633 | val 1.42059
  Classification -> best τ=0.215 (val F1=0.2601)
  Directional -> Accuracy: 0.4595, MCC: 0.0249, F1: 0.1304

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.29739 | val 2.21142
  Epoch 011 - train 0.17722 | val 2.11474
  Classification -> best τ=0.625 (val F1=0.2449)
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.43452 | val 2.10551
  Epoch 011 - train 0.31396 | val 1.90319
  Classification -> best τ=0.410 (val F1=0.1664)
  Directional -> Accuracy: 0.4462, MCC: -0.1231, F1: 0.2174

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.36387 | val 3.10271
  Epoch 012 - train 0.23517 | val 2.45312
  Classification -> best τ=0.330 (val F1=0.2485)
  Directional -> Accuracy: 0.5263, MCC: -0.0359, F1: 0.6582

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.46441 | val 1.99158
  Epoch 013 - train 0.32865 | val 1.91960
  Classification -> best τ=0.460 (val F1=0.1320)
  Directional -> Accuracy: 0.5385, MCC: 0.0619, F1: 0.2857

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.40703 | val 1.11196
  Epoch 011 - train 0.30701 | val 1.79956
  Classification -> best τ=0.475 (val F1=0.2887)
  Directional -> Accuracy: 0.5455, MCC: 0.1491, F1: 0.4444

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.14374 | val 3.46174
  Epoch 011 - train 0.06765 | val 3.95866
  Classification -> best τ=0.815 (val F1=0.4594)
  Directional -> Accuracy: 0.5778, MCC: 0.0000, F1: 0.0000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.28823 | val 0.73131
  Epoch 013 - train 0.15397 | val 1.59054
  Classification -> best τ=0.500 (val F1=0.3873)
  Directional -> Accuracy: 0.4286, MCC: -0.1021, F1: 0.3684

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.47017 | val 1.72634
  Epoch 011 - train 0.29258 | val 1.88827
  Classification -> best τ=0.425 (val F1=0.0063)
  Directional -> Accuracy: 0.4464, MCC: -0.0682, F1: 0.3404

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.24108 | val 3.25259
  Epoch 013 - train 0.09658 | val 2.56101
  Classification -> best τ=0.380 (val F1=0.3296)
  Directional -> Accuracy: 0.5750, MCC: 0.1140, F1: 0.7018

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.15844 | val 5.73783
  Epoch 011 - train 0.11143 | val 5.14310
  Classification -> best τ=0.870 (val F1=0.3001)
  Directional -> Accuracy: 0.5238, MCC: 0.0267, F1: 0.3333

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.32653 | val 1.53722
  Epoch 011 - train 0.22543 | val 3.08945
  Classification -> best τ=0.370 (val F1=0.2147)
  Directional -> Accuracy: 0.4762, MCC: -0.1498, F1: 0.6207

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.42446 | val 1.26749
  Epoch 011 - train 0.33924 | val 1.21397
  Classification -> best τ=0.485 (val F1=0.4194)
  Directional -> Accuracy: 0.5714, MCC: 0.1701, F1: 0.5116

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.50040 | val 1.46822
  Epoch 013 - train 0.34534 | val 0.93795
  Classification -> best τ=0.515 (val F1=0.2618)
  Directional -> Accuracy: 0.5000, MCC: 0.1167, F1: 0.2800

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.27837 | val 2.88718
  Epoch 011 - train 0.21136 | val 3.12814
  Classification -> best τ=0.360 (val F1=0.1309)
  Directional -> Accuracy: 0.5814, MCC: 0.2592, F1: 0.6897

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.46093 | val 1.22235
  Epoch 012 - train 0.24920 | val 1.23107
  Classification -> best τ=0.290 (val F1=0.3254)
  Directional -> Accuracy: 0.5455, MCC: 0.0344, F1: 0.6429

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.23890 | val 1.14871
  Epoch 011 - train 0.12224 | val 1.05794
  Classification -> best τ=0.575 (val F1=0.4356)
  Directional -> Accuracy: 0.5000, MCC: 0.0561, F1: 0.2222

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.47587 | val 2.12893
  Epoch 012 - train 0.32530 | val 2.37538
  Classification -> best τ=0.720 (val F1=0.1832)
  Directional -> Accuracy: 0.5714, MCC: 0.1309, F1: 0.5000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.33144 | val 1.32376
  Epoch 011 - train 0.17372 | val 1.50567
  Classification -> best τ=0.455 (val F1=0.4012)
  Directional -> Accuracy: 0.3913, MCC: -0.1174, F1: 0.2632

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.16178 | val 2.40620
  Epoch 011 - train 0.12368 | val 2.68885
  Classification -> best τ=0.605 (val F1=0.3378)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.43755 | val 1.76732
  Epoch 011 - train 0.37094 | val 2.19357
  Classification -> best τ=0.610 (val F1=0.1279)
  Directional -> Accuracy: 0.4865, MCC: -0.0065, F1: 0.6415

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.37886 | val 1.37559
  Epoch 012 - train 0.08694 | val 1.68545
  Classification -> best τ=0.710 (val F1=0.1890)
  Directional -> Accuracy: 0.5111, MCC: 0.0832, F1: 0.1538

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.20668 | val 1.64623
  Epoch 011 - train 0.07105 | val 1.61320
  Classification -> best τ=0.300 (val F1=0.2408)
  Directional -> Accuracy: 0.5952, MCC: 0.1803, F1: 0.7385

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.19488 | val 2.97666
  Epoch 011 - train 0.10472 | val 3.57370
  Classification -> best τ=0.565 (val F1=0.3752)
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.5455

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.41834 | val 0.82052
  Epoch 013 - train 0.21031 | val 1.11068
  Classification -> best τ=0.590 (val F1=0.2859)
  Directional -> Accuracy: 0.4182, MCC: -0.1817, F1: 0.4839

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.35595 | val 2.04894
  Epoch 011 - train 0.21779 | val 3.14912
  Classification -> best τ=0.820 (val F1=0.2143)
  Directional -> Accuracy: 0.4821, MCC: -0.0619, F1: 0.2927

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.55197 | val 1.03167
  Epoch 011 - train 0.26768 | val 1.19756
  Classification -> best τ=0.535 (val F1=0.0406)
  Directional -> Accuracy: 0.4906, MCC: -0.0113, F1: 0.3415

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.43682 | val 1.87678
  Epoch 011 - train 0.29517 | val 1.50570
  Classification -> best τ=0.815 (val F1=0.1407)
  Directional -> Accuracy: 0.5091, MCC: 0.0133, F1: 0.5424

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.49752 | val 0.73515

[I 2026-02-22 15:51:32,356] Trial 240 finished with value: 0.25287645099976747 and parameters: {'feature_set': 'all_nlp', 'model_type': 'BiGRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.4, 'batch_size': 16, 'learning_rate': 0.008141259307605874, 'weight_decay': 0.00022233410219193238, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 0.9366198962730377, 'early_stopping_min_delta': 0.0014696353601629693}. Best is trial 214 with value: 0.2991200218486954.

  Epoch 011 - train 0.42831 | val 0.71905
  Classification -> best τ=0.405 (val F1=0.3862)
  Directional -> Accuracy: 0.6500, MCC: 0.2986, F1: 0.6316

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.25287645099976747
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.60082 | val 0.79682
  Epoch 013 - train 0.56751 | val 0.90786
  Classification -> best τ=0.720 (val F1=0.2036)
  Directional -> Accuracy: 0.5395, MCC: -0.0465, F1: 0.0541

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.50738 | val 0.84841
  Epoch 011 - train 0.47057 | val 0.98372
  Classification -> best τ=0.740 (val F1=0.2523)
  Directional -> Accuracy: 0.5333, MCC: 0.2428, F1: 0.3636

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.63458 | val 1.41742
  Epoch 011 - train 0.55279 | val 1.74429
  Classification -> best τ=0.800 (val F1=0.3114)
  Directional -> Accuracy: 0.5217, MCC: 0.1124, F1: 0.2667

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.54317 | val 1.52863
  Epoch 013 - train 0.52256 | val 2.10362
  Classification -> best τ=0.340 (val F1=0.2593)
  Directional -> Accuracy: 0.5405, MCC: 0.0529, F1: 0.6304

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.55567 | val 2.42906
  Epoch 011 - train 0.47634 | val 2.21236
  Classification -> best τ=0.770 (val F1=0.4611)
  Directional -> Accuracy: 0.6600, MCC: 0.3398, F1: 0.6222

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.51195 | val 1.02667
  Epoch 014 - train 0.37815 | val 0.70844
  Classification -> best τ=0.690 (val F1=0.3210)
  Directional -> Accuracy: 0.5217, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.61604 | val 1.39888
  Epoch 013 - train 0.54550 | val 1.00451
  Classification -> best τ=0.520 (val F1=0.2009)
  Directional -> Accuracy: 0.5147, MCC: 0.0552, F1: 0.4923

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.40032 | val 0.65693
  Epoch 011 - train 0.44875 | val 1.22882
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.58414 | val 1.49911
  Epoch 019 - train 0.41956 | val 1.96534
  Classification -> best τ=0.695 (val F1=0.3962)
  Directional -> Accuracy: 0.4583, MCC: -0.1811, F1: 0.1875

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.58535 | val 1.86791
  Epoch 011 - train 0.49721 | val 1.32385
  Classification -> best τ=0.435 (val F1=0.3318)
  Directional -> Accuracy: 0.4493, MCC: 0.1471, F1: 0.6042

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.53158 | val 2.13516
  Epoch 011 - train 0.56434 | val 2.88538
  Classification -> best τ=0.660 (val F1=0.4037)
  Directional -> Accuracy: 0.6122, MCC: 0.2379, F1: 0.2963

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.59684 | val 1.04034
  Epoch 012 - train 0.50090 | val 1.29827
  Classification -> best τ=0.515 (val F1=0.1923)
  Directional -> Accuracy: 0.5789, MCC: 0.2796, F1: 0.7073

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.48750 | val 1.15655
  Epoch 012 - train 0.43982 | val 1.75748
  Classification -> best τ=0.490 (val F1=0.2205)
  Directional -> Accuracy: 0.5476, MCC: 0.0214, F1: 0.0952

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.57657 | val 1.19405
  Epoch 014 - train 0.51150 | val 1.70359
  Classification -> best τ=0.405 (val F1=0.3126)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.61644 | val 0.89894
  Epoch 011 - train 0.56939 | val 0.99845
  Classification -> best τ=0.545 (val F1=0.2971)
  Directional -> Accuracy: 0.5490, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.57211 | val 1.60204
  Epoch 011 - train 0.49437 | val 1.67732
  Classification -> best τ=0.730 (val F1=0.4260)
  Directional -> Accuracy: 0.5942, MCC: 0.1751, F1: 0.6585

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.54339 | val 0.92621
  Epoch 012 - train 0.48658 | val 1.03519
  Classification -> best τ=0.450 (val F1=0.3382)
  Directional -> Accuracy: 0.3793, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.57190 | val 1.05173
  Epoch 011 - train 0.57131 | val 0.99261
  Classification -> best τ=0.440 (val F1=0.2220)
  Directional -> Accuracy: 0.4000, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.57765 | val 2.17330
  Epoch 012 - train 0.51755 | val 2.70772
  Classification -> best τ=0.325 (val F1=0.2770)
  Directional -> Accuracy: 0.5781, MCC: 0.0000, F1: 0.7327

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.50402 | val 1.11294
  Epoch 011 - train 0.46455 | val 1.33273
  Classification -> best τ=0.650 (val F1=0.2588)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.50244 | val 0.86579
  Epoch 013 - train 0.43672 | val 1.25590
  Classification -> best τ=0.660 (val F1=0.2727)
  Directional -> Accuracy: 0.4255, MCC: 0.0391, F1: 0.2286

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.60506 | val 2.39225
  Epoch 011 - train 0.54395 | val 2.93761
  Classification -> best τ=0.175 (val F1=0.1514)
  Directional -> Accuracy: 0.5077, MCC: 0.0000, F1: 0.6735

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.64439 | val 0.67846
  Epoch 011 - train 0.57341 | val 0.76765
  Classification -> best τ=0.770 (val F1=0.3550)
  Directional -> Accuracy: 0.5439, MCC: 0.0737, F1: 0.5938

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.58287 | val 0.89236
  Epoch 014 - train 0.48178 | val 1.06795
  Classification -> best τ=0.735 (val F1=0.1985)
  Directional -> Accuracy: 0.5385, MCC: 0.1309, F1: 0.0625

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.51308 | val 0.89336
  Epoch 012 - train 0.46606 | val 0.92407
  Classification -> best τ=0.380 (val F1=0.4839)
  Directional -> Accuracy: 0.5455, MCC: 0.0745, F1: 0.6032

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.37747 | val 1.12653
  Epoch 011 - train 0.38351 | val 1.25327
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.5938

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.56863 | val 0.73452
  Epoch 011 - train 0.53224 | val 0.75438
  Classification -> best τ=0.525 (val F1=0.0525)
  Directional -> Accuracy: 0.5238, MCC: 0.0550, F1: 0.5455

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.52728 | val 1.32823
  Epoch 011 - train 0.47107 | val 1.72597
  Classification -> best τ=0.275 (val F1=0.2850)
  Directional -> Accuracy: 0.4464, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.48438 | val 1.58869
  Epoch 012 - train 0.44594 | val 1.30379
  Classification -> best τ=0.645 (val F1=0.2686)
  Directional -> Accuracy: 0.5750, MCC: 0.1124, F1: 0.6909

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.61295 | val 1.17619
  Epoch 013 - train 0.54125 | val 1.49432
  Classification -> best τ=0.535 (val F1=0.3501)
  Directional -> Accuracy: 0.5000, MCC: 0.0046, F1: 0.5116

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.56028 | val 0.94866
  Epoch 011 - train 0.55771 | val 1.06146
  Classification -> best τ=0.390 (val F1=0.3158)
  Directional -> Accuracy: 0.5714, MCC: 0.1194, F1: 0.7097

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.46712 | val 1.06904
  Epoch 011 - train 0.49949 | val 1.26760
  Classification -> best τ=0.350 (val F1=0.2837)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.55427 | val 1.04746
  Epoch 011 - train 0.50251 | val 0.93518
  Classification -> best τ=0.690 (val F1=0.3278)
  Directional -> Accuracy: 0.4444, MCC: 0.0000, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.48427 | val 1.24189
  Epoch 011 - train 0.47628 | val 1.33806
  Classification -> best τ=0.580 (val F1=0.0664)
  Directional -> Accuracy: 0.5581, MCC: 0.2261, F1: 0.1739

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.58485 | val 0.96249
  Epoch 011 - train 0.56708 | val 1.23076
  Classification -> best τ=0.720 (val F1=0.2501)
  Directional -> Accuracy: 0.4394, MCC: 0.1065, F1: 0.0513

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.42420 | val 2.59541
  Epoch 011 - train 0.33318 | val 3.58071
  Classification -> best τ=0.480 (val F1=0.2292)
  Directional -> Accuracy: 0.5952, MCC: 0.1870, F1: 0.6222

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.54645 | val 1.04940
  Epoch 012 - train 0.50541 | val 1.22664
  Classification -> best τ=0.655 (val F1=0.2305)
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.0000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.45277 | val 1.04973
  Epoch 011 - train 0.38961 | val 1.04869
  Classification -> best τ=0.240 (val F1=0.2118)
  Directional -> Accuracy: 0.6087, MCC: 0.0000, F1: 0.7568

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.50726 | val 0.74188
  Epoch 020 - train 0.39724 | val 0.99060
  Epoch 030 - train 0.41704 | val 0.84966
  Classification -> best τ=0.350 (val F1=0.4855)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.54224 | val 2.20952
  Epoch 011 - train 0.50268 | val 2.77128
  Classification -> best τ=0.365 (val F1=0.2547)
  Directional -> Accuracy: 0.5135, MCC: 0.0000, F1: 0.0000

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.54854 | val 1.22228
  Epoch 012 - train 0.46260 | val 1.82959
  Classification -> best τ=0.540 (val F1=0.2874)
  Directional -> Accuracy: 0.5778, MCC: 0.1613, F1: 0.6545

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.45924 | val 2.19571
  Epoch 012 - train 0.33971 | val 1.89317
  Classification -> best τ=0.540 (val F1=0.5092)
  Directional -> Accuracy: 0.6190, MCC: 0.1978, F1: 0.7037

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.50465 | val 1.13281
  Epoch 011 - train 0.41855 | val 1.23072
  Classification -> best τ=0.565 (val F1=0.3672)
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.0000

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.58263 | val 2.36242
  Epoch 013 - train 0.55434 | val 1.54353
  Classification -> best τ=0.695 (val F1=0.2036)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.42931 | val 2.58829
  Epoch 011 - train 0.37526 | val 2.99604
  Classification -> best τ=0.495 (val F1=0.2338)
  Directional -> Accuracy: 0.4643, MCC: -0.0625, F1: 0.5455

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.65876 | val 0.73195
  Epoch 011 - train 0.60676 | val 0.73832
  Classification -> best τ=0.695 (val F1=0.2442)
  Directional -> Accuracy: 0.6415, MCC: 0.2854, F1: 0.6780

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.56412 | val 3.26260
  Epoch 012 - train 0.49943 | val 3.09975
  Classification -> best τ=0.725 (val F1=0.2686)
  Directional -> Accuracy: 0.3818, MCC: -0.2940, F1: 0.0556

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.59923 | val 1.23166

[I 2026-02-22 15:55:45,683] Trial 241 finished with value: 0.273648695997962 and parameters: {'feature_set': 'sector', 'model_type': 'BiGRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.4, 'batch_size': 16, 'learning_rate': 0.0071571808390028194, 'weight_decay': 0.00010883095910310043, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 0.8995837711628777, 'early_stopping_min_delta': 0.0018616238907208714}. Best is trial 214 with value: 0.2991200218486954.

  Epoch 011 - train 0.58251 | val 1.14289
  Classification -> best τ=0.445 (val F1=0.2623)
  Directional -> Accuracy: 0.4667, MCC: -0.0704, F1: 0.4286

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.273648695997962
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.60553 | val 0.97546
  Epoch 011 - train 0.57359 | val 0.97760
  Classification -> best τ=0.670 (val F1=0.1635)
  Directional -> Accuracy: 0.6053, MCC: 0.1978, F1: 0.3182

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.49529 | val 0.99905
  Epoch 011 - train 0.49310 | val 1.11467
  Classification -> best τ=0.320 (val F1=0.1844)
  Directional -> Accuracy: 0.5778, MCC: 0.0340, F1: 0.7246

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.52569 | val 1.34802
  Epoch 011 - train 0.48433 | val 1.39123
  Classification -> best τ=0.645 (val F1=0.3482)
  Directional -> Accuracy: 0.5217, MCC: 0.0948, F1: 0.3125

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.57960 | val 1.13830
  Epoch 011 - train 0.55772 | val 0.96574
  Classification -> best τ=0.445 (val F1=0.2090)
  Directional -> Accuracy: 0.4595, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.53114 | val 2.55789
  Epoch 014 - train 0.50846 | val 1.06357
  Classification -> best τ=0.525 (val F1=0.5079)
  Directional -> Accuracy: 0.5800, MCC: 0.1572, F1: 0.6557

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.46509 | val 0.67679
  Epoch 020 - train 0.30212 | val 1.62254
  Classification -> best τ=0.615 (val F1=0.3838)
  Directional -> Accuracy: 0.5217, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.58325 | val 1.49994
  Epoch 013 - train 0.53406 | val 1.30418
  Classification -> best τ=0.635 (val F1=0.2163)
  Directional -> Accuracy: 0.6029, MCC: 0.0000, F1: 0.0000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.54972 | val 1.61175
  Epoch 012 - train 0.40721 | val 1.54385
  Classification -> best τ=0.270 (val F1=0.2168)
  Directional -> Accuracy: 0.4286, MCC: -0.0468, F1: 0.5714

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.59194 | val 1.23025
  Epoch 011 - train 0.51450 | val 1.46814
  Classification -> best τ=0.440 (val F1=0.2497)
  Directional -> Accuracy: 0.4375, MCC: 0.0000, F1: 0.6087

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.55105 | val 1.09602
  Epoch 016 - train 0.45394 | val 0.94724
  Classification -> best τ=0.630 (val F1=0.1668)
  Directional -> Accuracy: 0.5362, MCC: 0.0853, F1: 0.5152

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.61992 | val 0.73809
  Epoch 020 - train 0.37249 | val 0.84896
  Epoch 024 - train 0.30401 | val 0.76966
  Classification -> best τ=0.480 (val F1=0.3007)
  Directional -> Accuracy: 0.5510, MCC: 0.0212, F1: 0.0833

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.56399 | val 0.92065
  Epoch 011 - train 0.51280 | val 1.40004
  Classification -> best τ=0.570 (val F1=0.1771)
  Directional -> Accuracy: 0.5088, MCC: 0.0000, F1: 0.6744

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.47024 | val 0.90095
  Epoch 012 - train 0.41475 | val 0.85253
  Classification -> best τ=0.545 (val F1=0.2339)
  Directional -> Accuracy: 0.5476, MCC: 0.0391, F1: 0.2400

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.54826 | val 0.90473
  Epoch 011 - train 0.54511 | val 1.15001
  Classification -> best τ=0.305 (val F1=0.1018)
  Directional -> Accuracy: 0.5667, MCC: 0.1383, F1: 0.5000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.58528 | val 0.71700
  Epoch 012 - train 0.53262 | val 0.88371
  Classification -> best τ=0.580 (val F1=0.2571)
  Directional -> Accuracy: 0.5490, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.57445 | val 1.19592
  Epoch 012 - train 0.52711 | val 1.08185
  Classification -> best τ=0.365 (val F1=0.2341)
  Directional -> Accuracy: 0.4638, MCC: -0.1271, F1: 0.5843

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.58365 | val 1.30589
  Epoch 011 - train 0.56043 | val 1.53975
  Classification -> best τ=0.355 (val F1=0.0811)
  Directional -> Accuracy: 0.6207, MCC: 0.0000, F1: 0.7660

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.56417 | val 0.89789
  Epoch 020 - train 0.52834 | val 0.96912
  Epoch 023 - train 0.49645 | val 1.15108
  Classification -> best τ=0.635 (val F1=0.2367)
  Directional -> Accuracy: 0.4267, MCC: 0.1351, F1: 0.0851

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.58472 | val 1.21524
  Epoch 012 - train 0.51915 | val 1.36655
  Classification -> best τ=0.370 (val F1=0.3513)
  Directional -> Accuracy: 0.5156, MCC: -0.0082, F1: 0.5974

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.50289 | val 1.10095
  Epoch 011 - train 0.49685 | val 0.95508
  Classification -> best τ=0.705 (val F1=0.2701)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.51989 | val 1.85043
  Epoch 011 - train 0.49267 | val 2.64103
  Classification -> best τ=0.795 (val F1=0.1978)
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.57534 | val 1.15995
  Epoch 011 - train 0.53354 | val 1.12166
  Classification -> best τ=0.440 (val F1=0.2168)
  Directional -> Accuracy: 0.4769, MCC: -0.0879, F1: 0.6222

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.59117 | val 0.74413
  Epoch 011 - train 0.56612 | val 0.71162
  Classification -> best τ=0.595 (val F1=0.3175)
  Directional -> Accuracy: 0.5439, MCC: 0.1093, F1: 0.5357

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.57774 | val 0.76176
  Epoch 011 - train 0.54711 | val 0.72268
  Classification -> best τ=0.615 (val F1=0.1985)
  Directional -> Accuracy: 0.5231, MCC: 0.0000, F1: 0.0000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.60545 | val 0.74088
  Epoch 011 - train 0.55119 | val 0.92911
  Classification -> best τ=0.345 (val F1=0.3360)
  Directional -> Accuracy: 0.5818, MCC: 0.1660, F1: 0.5965

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.50842 | val 2.24246
  Epoch 012 - train 0.41176 | val 1.84071
  Classification -> best τ=0.775 (val F1=0.2241)
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.5938

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.56399 | val 1.34062
  Epoch 013 - train 0.47082 | val 1.02661
  Classification -> best τ=0.590 (val F1=0.1936)
  Directional -> Accuracy: 0.4286, MCC: -0.0323, F1: 0.0769

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.58387 | val 1.26788
  Epoch 012 - train 0.45618 | val 1.65065
  Classification -> best τ=0.620 (val F1=0.4095)
  Directional -> Accuracy: 0.4464, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.47618 | val 2.14601
  Epoch 011 - train 0.41737 | val 2.29279
  Classification -> best τ=0.530 (val F1=0.2618)
  Directional -> Accuracy: 0.6000, MCC: 0.2536, F1: 0.7333

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.57617 | val 1.23919
  Epoch 011 - train 0.55919 | val 1.00530
  Classification -> best τ=0.510 (val F1=0.1930)
  Directional -> Accuracy: 0.5238, MCC: 0.0674, F1: 0.5833

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.58245 | val 0.69865
  Epoch 020 - train 0.44811 | val 0.92371
  Classification -> best τ=0.495 (val F1=0.2147)
  Directional -> Accuracy: 0.5476, MCC: 0.0464, F1: 0.6667

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.53200 | val 0.73897
  Epoch 013 - train 0.45026 | val 1.02886
  Classification -> best τ=0.345 (val F1=0.3242)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.55174 | val 0.68855
  Epoch 015 - train 0.51443 | val 1.07467
  Classification -> best τ=0.380 (val F1=0.3830)
  Directional -> Accuracy: 0.5000, MCC: 0.1000, F1: 0.3077

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.49427 | val 1.17789
  Epoch 013 - train 0.43165 | val 1.87555
  Classification -> best τ=0.285 (val F1=0.1309)
  Directional -> Accuracy: 0.5116, MCC: 0.0452, F1: 0.6182

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.57066 | val 1.42631
  Epoch 011 - train 0.51804 | val 1.39577
  Classification -> best τ=0.600 (val F1=0.2329)
  Directional -> Accuracy: 0.4242, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.43086 | val 4.11829
  Epoch 012 - train 0.35790 | val 4.23739
  Classification -> best τ=0.605 (val F1=0.2665)
  Directional -> Accuracy: 0.6190, MCC: 0.3091, F1: 0.5000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.51594 | val 2.71399
  Epoch 011 - train 0.45783 | val 2.22877
  Classification -> best τ=0.590 (val F1=0.1832)
  Directional -> Accuracy: 0.5179, MCC: 0.0333, F1: 0.4906

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.45105 | val 1.03146
  Epoch 012 - train 0.37563 | val 1.15389
  Classification -> best τ=0.630 (val F1=0.2254)
  Directional -> Accuracy: 0.3913, MCC: -0.1627, F1: 0.3636

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.51905 | val 0.67834
  Epoch 020 - train 0.41246 | val 0.95967
  Classification -> best τ=0.485 (val F1=0.4011)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.62732 | val 0.93890
  Epoch 012 - train 0.53471 | val 1.36056
  Classification -> best τ=0.765 (val F1=0.2518)
  Directional -> Accuracy: 0.4459, MCC: -0.1545, F1: 0.1961

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.59054 | val 1.24161
  Epoch 013 - train 0.47164 | val 1.67245
  Classification -> best τ=0.560 (val F1=0.3371)
  Directional -> Accuracy: 0.4889, MCC: 0.0000, F1: 0.0000

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.40701 | val 2.61523
  Epoch 014 - train 0.40629 | val 1.81814
  Classification -> best τ=0.520 (val F1=0.3333)
  Directional -> Accuracy: 0.6190, MCC: 0.1964, F1: 0.7333

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.49870 | val 0.65005
  Epoch 020 - train 0.20480 | val 1.40731
  Epoch 023 - train 0.13748 | val 1.30662
  Classification -> best τ=0.735 (val F1=0.6590)
  Directional -> Accuracy: 0.5208, MCC: 0.2619, F1: 0.5965

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.63314 | val 1.10472
  Epoch 012 - train 0.62726 | val 1.06578
  Classification -> best τ=0.300 (val F1=0.2291)
  Directional -> Accuracy: 0.6000, MCC: 0.1992, F1: 0.7179

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.51058 | val 4.67247
  Epoch 011 - train 0.43211 | val 5.32675
  Classification -> best τ=0.195 (val F1=0.2998)
  Directional -> Accuracy: 0.5179, MCC: 0.0875, F1: 0.6400

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.69520 | val 0.83540
  Epoch 020 - train 0.53811 | val 0.97302
  Epoch 028 - train 0.31761 | val 1.15027
  Classification -> best τ=0.530 (val F1=0.2358)
  Directional -> Accuracy: 0.5660, MCC: 0.1345, F1: 0.5490

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.47639 | val 2.65041
  Epoch 011 - train 0.46334 | val 3.28669
  Classification -> best τ=0.605 (val F1=0.0042)
  Directional -> Accuracy: 0.5091, MCC: 0.0517, F1: 0.3721

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.60193 | val 0.78868

[I 2026-02-22 16:00:20,350] Trial 242 finished with value: 0.25756720411336637 and parameters: {'feature_set': 'sector', 'model_type': 'BiGRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.4, 'batch_size': 16, 'learning_rate': 0.008203389818563157, 'weight_decay': 9.697759428396575e-05, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 0.884867973914898, 'early_stopping_min_delta': 0.0017679115540957843}. Best is trial 214 with value: 0.2991200218486954.

  Epoch 011 - train 0.61135 | val 0.98565
  Classification -> best τ=0.440 (val F1=0.2124)
  Directional -> Accuracy: 0.4667, MCC: -0.0704, F1: 0.4286

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.25756720411336637
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.59261 | val 1.64546
  Epoch 011 - train 0.58457 | val 1.64542
  Classification -> best τ=0.655 (val F1=0.2510)
  Directional -> Accuracy: 0.5526, MCC: 0.0000, F1: 0.0000

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.55214 | val 0.74742
  Epoch 011 - train 0.48662 | val 0.83188
  Classification -> best τ=0.555 (val F1=0.3126)
  Directional -> Accuracy: 0.6444, MCC: 0.2713, F1: 0.6923

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.61593 | val 2.02640
  Epoch 011 - train 0.53162 | val 2.38003
  Classification -> best τ=0.940 (val F1=0.2727)
  Directional -> Accuracy: 0.5435, MCC: 0.1633, F1: 0.3226

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.60191 | val 0.87089
  Epoch 011 - train 0.55721 | val 1.09346
  Classification -> best τ=0.545 (val F1=0.2701)
  Directional -> Accuracy: 0.5946, MCC: 0.1805, F1: 0.6341

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.48455 | val 1.98729
  Epoch 011 - train 0.46243 | val 2.41218
  Classification -> best τ=0.650 (val F1=0.4745)
  Directional -> Accuracy: 0.6200, MCC: 0.2795, F1: 0.5366

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.56206 | val 0.74177
  Epoch 012 - train 0.46902 | val 0.84879
  Classification -> best τ=0.605 (val F1=0.3210)
  Directional -> Accuracy: 0.5217, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.58535 | val 0.80759
  Epoch 018 - train 0.48002 | val 1.37107
  Classification -> best τ=0.260 (val F1=0.2665)
  Directional -> Accuracy: 0.4412, MCC: -0.0669, F1: 0.4571

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.50439 | val 0.57366
  Epoch 018 - train 0.32692 | val 0.93989
  Classification -> best τ=0.185 (val F1=0.3094)
  Directional -> Accuracy: 0.5000, MCC: -0.0595, F1: 0.3226

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.57528 | val 2.15311
  Epoch 013 - train 0.51483 | val 1.94032
  Classification -> best τ=0.615 (val F1=0.2443)
  Directional -> Accuracy: 0.6250, MCC: 0.3228, F1: 0.6667

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.54229 | val 1.56367
  Epoch 012 - train 0.50133 | val 1.15455
  Classification -> best τ=0.515 (val F1=0.1508)
  Directional -> Accuracy: 0.5072, MCC: 0.0265, F1: 0.4848

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.52267 | val 1.72625
  Epoch 011 - train 0.49223 | val 2.09693
  Classification -> best τ=0.575 (val F1=0.2543)
  Directional -> Accuracy: 0.5510, MCC: 0.0453, F1: 0.2667

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.54196 | val 0.85031
  Epoch 011 - train 0.50422 | val 1.08829
  Classification -> best τ=0.640 (val F1=0.3160)
  Directional -> Accuracy: 0.5088, MCC: 0.0000, F1: 0.6744

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.58657 | val 0.99364
  Epoch 011 - train 0.46277 | val 1.32202
  Classification -> best τ=0.555 (val F1=0.1801)
  Directional -> Accuracy: 0.4524, MCC: -0.0464, F1: 0.5660

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.60871 | val 0.95340
  Epoch 012 - train 0.53845 | val 0.84640
  Classification -> best τ=0.540 (val F1=0.3126)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.54167 | val 0.75791
  Epoch 011 - train 0.51434 | val 0.76211
  Classification -> best τ=0.580 (val F1=0.2571)
  Directional -> Accuracy: 0.5098, MCC: -0.0659, F1: 0.1935

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.57736 | val 1.62560
  Epoch 012 - train 0.56536 | val 1.51295
  Classification -> best τ=0.340 (val F1=0.3067)
  Directional -> Accuracy: 0.5797, MCC: 0.1576, F1: 0.7010

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.60733 | val 1.24353
  Epoch 012 - train 0.52296 | val 1.49650
  Classification -> best τ=0.165 (val F1=0.3382)
  Directional -> Accuracy: 0.3621, MCC: -0.1557, F1: 0.1778

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.58124 | val 0.80365
  Epoch 019 - train 0.43464 | val 1.03248
  Classification -> best τ=0.200 (val F1=0.2182)
  Directional -> Accuracy: 0.6000, MCC: 0.0000, F1: 0.7500

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.55292 | val 1.83130
  Epoch 012 - train 0.48097 | val 2.22027
  Classification -> best τ=0.230 (val F1=0.3689)
  Directional -> Accuracy: 0.5312, MCC: -0.1308, F1: 0.6875

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.49463 | val 1.20018
  Epoch 011 - train 0.47131 | val 1.19570
  Classification -> best τ=0.325 (val F1=0.2593)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.46807 | val 1.14699
  Epoch 011 - train 0.47822 | val 1.42425
  Classification -> best τ=0.660 (val F1=0.1978)
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.55743 | val 2.39606
  Epoch 011 - train 0.51589 | val 2.90339
  Classification -> best τ=0.495 (val F1=0.2168)
  Directional -> Accuracy: 0.4923, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.62299 | val 0.94344
  Epoch 017 - train 0.52744 | val 1.08982
  Classification -> best τ=0.385 (val F1=0.4138)
  Directional -> Accuracy: 0.5965, MCC: 0.1707, F1: 0.6567

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.62663 | val 0.70323
  Epoch 018 - train 0.48714 | val 1.06544
  Classification -> best τ=0.475 (val F1=0.2055)
  Directional -> Accuracy: 0.4769, MCC: -0.2100, F1: 0.0000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.55103 | val 0.62813
  Epoch 020 - train 0.40332 | val 1.13406
  Classification -> best τ=0.675 (val F1=0.4907)
  Directional -> Accuracy: 0.5455, MCC: 0.1826, F1: 0.3902

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.47947 | val 3.36305
  Epoch 011 - train 0.40739 | val 3.96748
  Classification -> best τ=0.620 (val F1=0.2726)
  Directional -> Accuracy: 0.5333, MCC: 0.0230, F1: 0.4000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.59726 | val 0.87588
  Epoch 011 - train 0.57663 | val 0.76161
  Classification -> best τ=0.525 (val F1=0.0829)
  Directional -> Accuracy: 0.5238, MCC: 0.0550, F1: 0.5455

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.54206 | val 1.09709
  Epoch 011 - train 0.51317 | val 1.30971
  Classification -> best τ=0.225 (val F1=0.1126)
  Directional -> Accuracy: 0.5536, MCC: 0.0000, F1: 0.7126

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.49958 | val 1.35042
  Epoch 012 - train 0.48495 | val 1.40437
  Classification -> best τ=0.500 (val F1=0.3278)
  Directional -> Accuracy: 0.5750, MCC: 0.1770, F1: 0.7213

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.52934 | val 1.75430
  Epoch 013 - train 0.51983 | val 2.78514
  Classification -> best τ=0.640 (val F1=0.3501)
  Directional -> Accuracy: 0.5238, MCC: 0.0455, F1: 0.5000

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.57543 | val 0.86482
  Epoch 011 - train 0.54144 | val 0.95031
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5476, MCC: 0.0000, F1: 0.7077

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.51849 | val 1.04983
  Epoch 011 - train 0.45925 | val 0.99040
  Classification -> best τ=0.370 (val F1=0.4255)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.57549 | val 0.65657
  Epoch 016 - train 0.44254 | val 0.91013
  Classification -> best τ=0.305 (val F1=0.3610)
  Directional -> Accuracy: 0.5278, MCC: -0.0949, F1: 0.6852

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.47239 | val 1.04673
  Epoch 011 - train 0.46992 | val 1.20242
  Classification -> best τ=0.295 (val F1=0.2324)
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.62141 | val 1.76305
  Epoch 012 - train 0.54599 | val 1.91916
  Classification -> best τ=0.650 (val F1=0.2665)
  Directional -> Accuracy: 0.4242, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.47190 | val 1.36958
  Epoch 012 - train 0.40708 | val 1.48790
  Classification -> best τ=0.530 (val F1=0.2839)
  Directional -> Accuracy: 0.6667, MCC: 0.3708, F1: 0.6111

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.51565 | val 1.01146
  Epoch 013 - train 0.49143 | val 0.85412
  Classification -> best τ=0.440 (val F1=0.2417)
  Directional -> Accuracy: 0.5536, MCC: 0.0891, F1: 0.4444

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.51387 | val 0.86243
  Epoch 012 - train 0.42966 | val 0.94709
  Classification -> best τ=0.550 (val F1=0.2659)
  Directional -> Accuracy: 0.5217, MCC: -0.1783, F1: 0.6765

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.55000 | val 0.82200
  Epoch 013 - train 0.44750 | val 1.84812
  Classification -> best τ=0.285 (val F1=0.4011)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.53056 | val 1.69459
  Epoch 011 - train 0.51699 | val 1.64179
  Classification -> best τ=0.075 (val F1=0.2766)
  Directional -> Accuracy: 0.4865, MCC: 0.0000, F1: 0.6545

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.59680 | val 0.79565
  Epoch 013 - train 0.48501 | val 0.98303
  Classification -> best τ=0.530 (val F1=0.3190)
  Directional -> Accuracy: 0.5111, MCC: 0.0518, F1: 0.2667

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.41589 | val 2.86650
  Epoch 012 - train 0.33258 | val 2.83957
  Classification -> best τ=0.915 (val F1=0.3612)
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.0000

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.53671 | val 0.66788
  Epoch 020 - train 0.37969 | val 0.85214
  Epoch 026 - train 0.19044 | val 1.05841
  Classification -> best τ=0.575 (val F1=0.5421)
  Directional -> Accuracy: 0.4583, MCC: 0.2335, F1: 0.5806

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.69417 | val 0.94333
  Epoch 011 - train 0.60490 | val 1.28563
  Classification -> best τ=0.525 (val F1=0.2036)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.49317 | val 4.05846
  Epoch 011 - train 0.44901 | val 4.22778
  Classification -> best τ=0.665 (val F1=0.3111)
  Directional -> Accuracy: 0.4821, MCC: -0.0333, F1: 0.4912

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.61818 | val 0.73701
  Epoch 012 - train 0.55507 | val 0.81084
  Classification -> best τ=0.590 (val F1=0.1646)
  Directional -> Accuracy: 0.5472, MCC: 0.1005, F1: 0.5000

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.56357 | val 2.02480
  Epoch 012 - train 0.43599 | val 1.86595
  Classification -> best τ=0.790 (val F1=0.3225)
  Directional -> Accuracy: 0.4545, MCC: -0.1437, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.62225 | val 0.86888

[I 2026-02-22 16:04:44,352] Trial 243 finished with value: 0.2858247288090321 and parameters: {'feature_set': 'sector', 'model_type': 'BiGRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.4, 'batch_size': 16, 'learning_rate': 0.006209120702659206, 'weight_decay': 0.00016833555886233836, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 0.9743074702037632, 'early_stopping_min_delta': 0.0015766093575202739}. Best is trial 214 with value: 0.2991200218486954.

  Epoch 011 - train 0.59902 | val 0.84059
  Classification -> best τ=0.520 (val F1=0.3862)
  Directional -> Accuracy: 0.5333, MCC: 0.1346, F1: 0.0667

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2858247288090321
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.61636 | val 1.48604
  Epoch 011 - train 0.59865 | val 1.56204
  Classification -> best τ=0.460 (val F1=0.2919)
  Directional -> Accuracy: 0.5658, MCC: 0.1283, F1: 0.0571

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.55094 | val 1.00961
  Epoch 011 - train 0.50616 | val 1.04761
  Classification -> best τ=0.605 (val F1=0.1297)
  Directional -> Accuracy: 0.6222, MCC: 0.2030, F1: 0.7018

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.56027 | val 1.54198
  Epoch 012 - train 0.51803 | val 1.29350
  Classification -> best τ=0.840 (val F1=0.2861)
  Directional -> Accuracy: 0.4783, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.61162 | val 0.82689
  Epoch 019 - train 0.46525 | val 0.82124
  Classification -> best τ=0.350 (val F1=0.2593)
  Directional -> Accuracy: 0.5405, MCC: 0.0000, F1: 0.7018

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.51299 | val 1.18312
  Epoch 013 - train 0.42147 | val 2.24375
  Classification -> best τ=0.580 (val F1=0.4414)
  Directional -> Accuracy: 0.6200, MCC: 0.2795, F1: 0.5366

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.53424 | val 0.74301
  Epoch 020 - train 0.41448 | val 1.66817
  Epoch 023 - train 0.35269 | val 2.12434
  Classification -> best τ=0.550 (val F1=0.4810)
  Directional -> Accuracy: 0.5217, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.63543 | val 1.25656
  Epoch 012 - train 0.54599 | val 1.74720
  Classification -> best τ=0.210 (val F1=0.2445)
  Directional -> Accuracy: 0.4559, MCC: 0.1097, F1: 0.5747

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.52867 | val 1.35704
  Epoch 012 - train 0.50818 | val 1.38612
  Classification -> best τ=0.275 (val F1=0.1657)
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.59416 | val 1.42532
  Epoch 013 - train 0.51571 | val 1.55308
  Classification -> best τ=0.665 (val F1=0.2764)
  Directional -> Accuracy: 0.6667, MCC: 0.3185, F1: 0.5000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.57486 | val 0.85154
  Epoch 012 - train 0.49729 | val 1.23087
  Classification -> best τ=0.380 (val F1=0.2190)
  Directional -> Accuracy: 0.4493, MCC: -0.0737, F1: 0.4571

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.60667 | val 0.89491
  Epoch 011 - train 0.55670 | val 0.87233
  Classification -> best τ=0.405 (val F1=0.3590)
  Directional -> Accuracy: 0.5918, MCC: 0.1687, F1: 0.5238

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.63405 | val 1.42851
  Epoch 011 - train 0.57654 | val 1.33080
  Classification -> best τ=0.390 (val F1=0.2157)
  Directional -> Accuracy: 0.5088, MCC: 0.0000, F1: 0.6744

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.53230 | val 1.04237
  Epoch 011 - train 0.53808 | val 1.06290
  Classification -> best τ=0.560 (val F1=0.0272)
  Directional -> Accuracy: 0.3810, MCC: -0.2251, F1: 0.4091

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.58290 | val 0.97963
  Epoch 011 - train 0.57943 | val 0.85675
  Classification -> best τ=0.355 (val F1=0.2219)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.55307 | val 1.49803
  Epoch 011 - train 0.53493 | val 1.68429
  Classification -> best τ=0.550 (val F1=0.2571)
  Directional -> Accuracy: 0.5490, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.59376 | val 0.84157
  Epoch 013 - train 0.54987 | val 1.38888
  Classification -> best τ=0.235 (val F1=0.2795)
  Directional -> Accuracy: 0.5652, MCC: 0.1424, F1: 0.7059

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.57914 | val 1.28305
  Epoch 013 - train 0.53586 | val 1.26704
  Classification -> best τ=0.310 (val F1=0.3382)
  Directional -> Accuracy: 0.4483, MCC: 0.2128, F1: 0.2000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.62050 | val 1.03106
  Epoch 012 - train 0.54827 | val 1.30891
  Classification -> best τ=0.590 (val F1=0.1310)
  Directional -> Accuracy: 0.4000, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.58086 | val 1.60881
  Epoch 012 - train 0.48054 | val 1.94358
  Classification -> best τ=0.260 (val F1=0.3057)
  Directional -> Accuracy: 0.5781, MCC: 0.0000, F1: 0.7327

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.56109 | val 1.26618
  Epoch 011 - train 0.53520 | val 1.24117
  Classification -> best τ=0.440 (val F1=0.2881)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.57166 | val 1.47916
  Epoch 013 - train 0.47191 | val 1.87382
  Classification -> best τ=0.630 (val F1=0.2164)
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.55150 | val 1.31432
  Epoch 012 - train 0.55540 | val 1.66248
  Classification -> best τ=0.480 (val F1=0.2509)
  Directional -> Accuracy: 0.4923, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.64989 | val 0.67152
  Epoch 012 - train 0.59598 | val 0.70100
  Classification -> best τ=0.590 (val F1=0.3820)
  Directional -> Accuracy: 0.5088, MCC: 0.0471, F1: 0.4815

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.58725 | val 0.80787
  Epoch 011 - train 0.57161 | val 0.82119
  Classification -> best τ=0.485 (val F1=0.1778)
  Directional -> Accuracy: 0.4923, MCC: 0.0112, F1: 0.5926

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.50620 | val 0.96018
  Epoch 011 - train 0.53903 | val 1.07414
  Classification -> best τ=0.275 (val F1=0.4399)
  Directional -> Accuracy: 0.5636, MCC: 0.1200, F1: 0.6000

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.48228 | val 3.36640
  Epoch 012 - train 0.47186 | val 3.60566
  Classification -> best τ=0.615 (val F1=0.3669)
  Directional -> Accuracy: 0.6222, MCC: 0.4274, F1: 0.6909

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.54898 | val 0.67832
  Epoch 015 - train 0.52697 | val 1.14787
  Classification -> best τ=0.645 (val F1=0.3184)
  Directional -> Accuracy: 0.4524, MCC: 0.0212, F1: 0.2069

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.57975 | val 1.28460
  Epoch 012 - train 0.51537 | val 1.62339
  Classification -> best τ=0.130 (val F1=0.2892)
  Directional -> Accuracy: 0.4821, MCC: 0.1728, F1: 0.1212

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.55946 | val 0.77516
  Epoch 011 - train 0.52956 | val 0.87772
  Classification -> best τ=0.590 (val F1=0.0836)
  Directional -> Accuracy: 0.5500, MCC: 0.0503, F1: 0.6667

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.58260 | val 1.41911
  Epoch 012 - train 0.56361 | val 1.25358
  Classification -> best τ=0.375 (val F1=0.3689)
  Directional -> Accuracy: 0.4524, MCC: -0.0853, F1: 0.5106

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.63251 | val 0.89545
  Epoch 018 - train 0.49607 | val 1.23729
  Classification -> best τ=0.315 (val F1=0.2357)
  Directional -> Accuracy: 0.5000, MCC: -0.1319, F1: 0.6557

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.62207 | val 0.82195
  Epoch 012 - train 0.45997 | val 0.94267
  Classification -> best τ=0.360 (val F1=0.3196)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.57307 | val 0.92344
  Epoch 013 - train 0.51740 | val 0.72519
  Classification -> best τ=0.320 (val F1=0.2513)
  Directional -> Accuracy: 0.5556, MCC: 0.0000, F1: 0.7143

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.53037 | val 1.18118
  Epoch 011 - train 0.51076 | val 1.12683
  Classification -> best τ=0.490 (val F1=0.2643)
  Directional -> Accuracy: 0.6047, MCC: 0.3278, F1: 0.3200

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.59290 | val 1.23405
  Epoch 011 - train 0.56868 | val 1.10835
  Classification -> best τ=0.430 (val F1=0.1580)
  Directional -> Accuracy: 0.5000, MCC: 0.1624, F1: 0.2979

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.46574 | val 1.94764
  Epoch 013 - train 0.51833 | val 1.80950
  Classification -> best τ=0.620 (val F1=0.3589)
  Directional -> Accuracy: 0.7143, MCC: 0.4404, F1: 0.7000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.52001 | val 0.95337
  Epoch 012 - train 0.51880 | val 1.04097
  Classification -> best τ=0.380 (val F1=0.2450)
  Directional -> Accuracy: 0.5357, MCC: 0.0890, F1: 0.5667

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.51101 | val 2.22889
  Epoch 011 - train 0.43620 | val 1.82829
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.6087, MCC: 0.0000, F1: 0.7568

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.59754 | val 0.82809
  Epoch 011 - train 0.57778 | val 0.92352
  Classification -> best τ=0.585 (val F1=0.3656)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.59057 | val 1.09274
  Epoch 014 - train 0.47635 | val 1.10100
  Classification -> best τ=0.240 (val F1=0.3556)
  Directional -> Accuracy: 0.5135, MCC: 0.0910, F1: 0.6538

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.60033 | val 0.86674
  Epoch 017 - train 0.44958 | val 1.03514
  Classification -> best τ=0.620 (val F1=0.4080)
  Directional -> Accuracy: 0.5111, MCC: 0.0832, F1: 0.1538

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.43300 | val 1.83378
  Epoch 011 - train 0.40407 | val 2.07305
  Classification -> best τ=0.675 (val F1=0.4523)
  Directional -> Accuracy: 0.5000, MCC: 0.1698, F1: 0.2759

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.50811 | val 0.69354
  Epoch 020 - train 0.42787 | val 0.67367
  Epoch 025 - train 0.33630 | val 0.78539
  Classification -> best τ=0.555 (val F1=0.4795)
  Directional -> Accuracy: 0.5625, MCC: 0.2137, F1: 0.5714

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.65450 | val 1.26227
  Epoch 012 - train 0.63040 | val 1.16406
  Classification -> best τ=0.485 (val F1=0.2374)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.51881 | val 1.86588
  Epoch 011 - train 0.46121 | val 2.22771
  Classification -> best τ=0.565 (val F1=0.3233)
  Directional -> Accuracy: 0.5179, MCC: 0.0333, F1: 0.4906

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.65648 | val 0.83689
  Epoch 013 - train 0.62175 | val 0.73355
  Classification -> best τ=0.605 (val F1=0.1999)
  Directional -> Accuracy: 0.5094, MCC: 0.0484, F1: 0.2353

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.57038 | val 2.23951
  Epoch 011 - train 0.53662 | val 2.44969
  Classification -> best τ=0.790 (val F1=0.1647)
  Directional -> Accuracy: 0.5273, MCC: 0.0000, F1: 0.6905

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.62041 | val 0.71558

[I 2026-02-22 16:09:07,715] Trial 244 finished with value: 0.2749042723651692 and parameters: {'feature_set': 'sector', 'model_type': 'BiGRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.5, 'batch_size': 16, 'learning_rate': 0.005994095994604836, 'weight_decay': 0.0001479578471586173, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 0.9743604971182205, 'early_stopping_min_delta': 0.001291420029853006}. Best is trial 214 with value: 0.2991200218486954.

  Epoch 016 - train 0.57713 | val 0.91747
  Classification -> best τ=0.365 (val F1=0.2637)
  Directional -> Accuracy: 0.5167, MCC: 0.0334, F1: 0.5085

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2749042723651692
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.58984 | val 1.20213
  Epoch 011 - train 0.57778 | val 1.38582
  Classification -> best τ=0.730 (val F1=0.2510)
  Directional -> Accuracy: 0.5789, MCC: 0.1357, F1: 0.4839

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.54565 | val 1.14684
  Epoch 011 - train 0.50235 | val 1.17809
  Classification -> best τ=0.600 (val F1=0.1941)
  Directional -> Accuracy: 0.6444, MCC: 0.2619, F1: 0.7037

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.55880 | val 1.31303
  Epoch 011 - train 0.54475 | val 1.70110
  Classification -> best τ=0.820 (val F1=0.2793)
  Directional -> Accuracy: 0.5435, MCC: 0.1633, F1: 0.3226

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.58496 | val 0.80579
  Epoch 011 - train 0.53347 | val 0.86157
  Classification -> best τ=0.515 (val F1=0.2014)
  Directional -> Accuracy: 0.5270, MCC: -0.0112, F1: 0.6667

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.52926 | val 1.86475
  Epoch 011 - train 0.49050 | val 2.00452
  Classification -> best τ=0.565 (val F1=0.3933)
  Directional -> Accuracy: 0.6000, MCC: 0.2425, F1: 0.5000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.54061 | val 0.67973
  Epoch 019 - train 0.30144 | val 0.98232
  Classification -> best τ=0.495 (val F1=0.4575)
  Directional -> Accuracy: 0.5217, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.60808 | val 1.26413
  Epoch 011 - train 0.55917 | val 1.48384
  Classification -> best τ=0.380 (val F1=0.2648)
  Directional -> Accuracy: 0.3971, MCC: 0.0000, F1: 0.5684

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.47957 | val 1.64820
  Epoch 011 - train 0.43876 | val 1.57906
  Classification -> best τ=0.380 (val F1=0.0679)
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.56818 | val 2.09891
  Epoch 012 - train 0.48670 | val 1.82580
  Classification -> best τ=0.620 (val F1=0.3523)
  Directional -> Accuracy: 0.5833, MCC: 0.2322, F1: 0.6296

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.57925 | val 1.02991
  Epoch 011 - train 0.52408 | val 1.21200
  Classification -> best τ=0.255 (val F1=0.3262)
  Directional -> Accuracy: 0.4348, MCC: 0.1033, F1: 0.5979

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.60124 | val 0.69896
  Epoch 013 - train 0.52430 | val 0.74443
  Classification -> best τ=0.575 (val F1=0.4059)
  Directional -> Accuracy: 0.5918, MCC: 0.1804, F1: 0.2308

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.53646 | val 0.89337
  Epoch 012 - train 0.54742 | val 1.17939
  Classification -> best τ=0.310 (val F1=0.2391)
  Directional -> Accuracy: 0.5263, MCC: 0.1360, F1: 0.6824

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.58139 | val 1.00532
  Epoch 011 - train 0.50470 | val 0.97137
  Classification -> best τ=0.465 (val F1=0.1316)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.6230

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.59208 | val 0.70886
  Epoch 016 - train 0.52459 | val 0.75117
  Classification -> best τ=0.440 (val F1=0.3774)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.52123 | val 0.79016
  Epoch 014 - train 0.47403 | val 1.07201
  Classification -> best τ=0.465 (val F1=0.2008)
  Directional -> Accuracy: 0.6275, MCC: 0.2365, F1: 0.5128

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.61395 | val 1.69108
  Epoch 013 - train 0.50449 | val 1.18942
  Classification -> best τ=0.240 (val F1=0.2659)
  Directional -> Accuracy: 0.5507, MCC: 0.1304, F1: 0.7048

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.59322 | val 1.43999
  Epoch 011 - train 0.55774 | val 1.66554
  Classification -> best τ=0.490 (val F1=0.2298)
  Directional -> Accuracy: 0.3793, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.55991 | val 1.02068
  Epoch 011 - train 0.52165 | val 1.01540
  Classification -> best τ=0.565 (val F1=0.1909)
  Directional -> Accuracy: 0.4000, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.57217 | val 1.15953
  Epoch 012 - train 0.53394 | val 1.14744
  Classification -> best τ=0.615 (val F1=0.3823)
  Directional -> Accuracy: 0.4219, MCC: -0.0284, F1: 0.0513

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.52796 | val 1.08416
  Epoch 014 - train 0.45026 | val 1.32413
  Classification -> best τ=0.535 (val F1=0.2771)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.57956 | val 1.16030
  Epoch 012 - train 0.47926 | val 1.73458
  Classification -> best τ=0.390 (val F1=0.2416)
  Directional -> Accuracy: 0.4043, MCC: 0.0267, F1: 0.1250

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.52947 | val 2.14620
  Epoch 011 - train 0.53056 | val 2.83353
  Classification -> best τ=0.310 (val F1=0.1925)
  Directional -> Accuracy: 0.5077, MCC: 0.0000, F1: 0.6735

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.65297 | val 0.99589
  Epoch 015 - train 0.54887 | val 0.95273
  Classification -> best τ=0.405 (val F1=0.4748)
  Directional -> Accuracy: 0.5965, MCC: 0.2012, F1: 0.6102

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.55943 | val 0.76693
  Epoch 014 - train 0.52964 | val 0.99931
  Classification -> best τ=0.470 (val F1=0.1985)
  Directional -> Accuracy: 0.4923, MCC: -0.0917, F1: 0.1081

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.55923 | val 0.85159
  Epoch 011 - train 0.53683 | val 0.86648
  Classification -> best τ=0.250 (val F1=0.3751)
  Directional -> Accuracy: 0.5455, MCC: 0.0637, F1: 0.6269

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.45306 | val 2.38607
  Epoch 011 - train 0.47010 | val 2.52307
  Classification -> best τ=0.650 (val F1=0.0105)
  Directional -> Accuracy: 0.4444, MCC: -0.0225, F1: 0.5455

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.62791 | val 0.77200
  Epoch 014 - train 0.46667 | val 0.84593
  Classification -> best τ=0.600 (val F1=0.3712)
  Directional -> Accuracy: 0.6429, MCC: 0.2887, F1: 0.6667

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.55364 | val 1.41273
  Epoch 011 - train 0.50495 | val 1.37571
  Classification -> best τ=0.265 (val F1=0.3873)
  Directional -> Accuracy: 0.4643, MCC: 0.1211, F1: 0.0625

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.47009 | val 0.98389
  Epoch 013 - train 0.38582 | val 1.60269
  Classification -> best τ=0.495 (val F1=0.2618)
  Directional -> Accuracy: 0.6000, MCC: 0.2536, F1: 0.7333

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.59771 | val 1.98569
  Epoch 018 - train 0.42056 | val 2.35055
  Classification -> best τ=0.390 (val F1=0.3630)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.4878

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.53434 | val 1.02937
  Epoch 011 - train 0.50357 | val 1.01905
  Classification -> best τ=0.515 (val F1=0.1286)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.46530 | val 0.84892
  Epoch 011 - train 0.43866 | val 0.97375
  Classification -> best τ=0.680 (val F1=0.2399)
  Directional -> Accuracy: 0.3673, MCC: -0.3172, F1: 0.0606

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.61867 | val 1.04787
  Epoch 014 - train 0.53076 | val 0.94335
  Classification -> best τ=0.375 (val F1=0.2618)
  Directional -> Accuracy: 0.5694, MCC: 0.1203, F1: 0.6265

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.57734 | val 0.94069
  Epoch 011 - train 0.52693 | val 0.98865
  Classification -> best τ=0.510 (val F1=0.0427)
  Directional -> Accuracy: 0.6047, MCC: 0.3278, F1: 0.3200

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.57585 | val 1.25332
  Epoch 011 - train 0.50515 | val 1.44288
  Classification -> best τ=0.390 (val F1=0.2179)
  Directional -> Accuracy: 0.4545, MCC: 0.1517, F1: 0.1000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.49938 | val 2.86685
  Epoch 012 - train 0.44219 | val 2.73642
  Classification -> best τ=0.500 (val F1=0.2665)
  Directional -> Accuracy: 0.6667, MCC: 0.3708, F1: 0.6111

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.51035 | val 1.08457
  Epoch 014 - train 0.42537 | val 1.54987
  Classification -> best τ=0.535 (val F1=0.1832)
  Directional -> Accuracy: 0.5714, MCC: 0.1269, F1: 0.3333

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.51358 | val 0.77705
  Epoch 011 - train 0.42814 | val 0.94002
  Classification -> best τ=0.440 (val F1=0.2474)
  Directional -> Accuracy: 0.5000, MCC: -0.1362, F1: 0.6349

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.49553 | val 0.78716
  Epoch 011 - train 0.46033 | val 0.86604
  Classification -> best τ=0.555 (val F1=0.4011)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.51958 | val 1.20761
  Epoch 011 - train 0.48192 | val 1.40603
  Classification -> best τ=0.585 (val F1=0.2547)
  Directional -> Accuracy: 0.5000, MCC: -0.0230, F1: 0.2449

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.58657 | val 0.93400
  Epoch 015 - train 0.47035 | val 0.90263
  Classification -> best τ=0.425 (val F1=0.4080)
  Directional -> Accuracy: 0.5333, MCC: 0.1493, F1: 0.2222

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.44854 | val 1.16368
  Epoch 012 - train 0.31975 | val 1.23071
  Classification -> best τ=0.415 (val F1=0.5092)
  Directional -> Accuracy: 0.6905, MCC: 0.3596, F1: 0.7636

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.48205 | val 0.78439
  Epoch 011 - train 0.39087 | val 0.84679
  Classification -> best τ=0.535 (val F1=0.4622)
  Directional -> Accuracy: 0.5625, MCC: 0.3200, F1: 0.6182

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.61737 | val 1.46936
  Epoch 012 - train 0.61928 | val 1.51326
  Classification -> best τ=0.565 (val F1=0.0117)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.54585 | val 1.74113
  Epoch 011 - train 0.48679 | val 2.05058
  Classification -> best τ=0.505 (val F1=0.2998)
  Directional -> Accuracy: 0.5357, MCC: 0.0876, F1: 0.5938

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.65402 | val 0.73655
  Epoch 012 - train 0.59688 | val 0.71287
  Classification -> best τ=0.510 (val F1=0.2358)
  Directional -> Accuracy: 0.5660, MCC: 0.1343, F1: 0.6349

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.51882 | val 2.90512
  Epoch 011 - train 0.49975 | val 3.65216
  Classification -> best τ=0.725 (val F1=0.1605)
  Directional -> Accuracy: 0.4727, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.62351 | val 0.71215

[I 2026-02-22 16:13:17,100] Trial 245 finished with value: 0.2705842992954846 and parameters: {'feature_set': 'sector', 'model_type': 'BiGRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.4, 'batch_size': 16, 'learning_rate': 0.005281973889491239, 'weight_decay': 0.00017727898139972413, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 1.0154642983356397, 'early_stopping_min_delta': 0.001490247472250693}. Best is trial 214 with value: 0.2991200218486954.

  Epoch 014 - train 0.52681 | val 0.90540
  Classification -> best τ=0.515 (val F1=0.2920)
  Directional -> Accuracy: 0.5500, MCC: 0.1223, F1: 0.2286

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2705842992954846
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.61809 | val 1.08094
  Epoch 011 - train 0.60863 | val 1.03774
  Classification -> best τ=0.565 (val F1=0.2919)
  Directional -> Accuracy: 0.5526, MCC: 0.0000, F1: 0.0000

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.66216 | val 0.84475
  Epoch 011 - train 0.51540 | val 1.17857
  Classification -> best τ=0.440 (val F1=0.2285)
  Directional -> Accuracy: 0.5778, MCC: 0.0000, F1: 0.7324

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.56770 | val 1.32176
  Epoch 011 - train 0.53450 | val 1.31565
  Classification -> best τ=0.645 (val F1=0.3114)
  Directional -> Accuracy: 0.4783, MCC: -0.0134, F1: 0.1429

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.59817 | val 0.74714
  Epoch 019 - train 0.50575 | val 1.48207
  Classification -> best τ=0.410 (val F1=0.1808)
  Directional -> Accuracy: 0.5405, MCC: 0.0000, F1: 0.7018

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.53503 | val 2.42016
  Epoch 012 - train 0.51519 | val 2.83948
  Classification -> best τ=0.665 (val F1=0.4745)
  Directional -> Accuracy: 0.5400, MCC: 0.1375, F1: 0.3429

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.52604 | val 0.68733
  Epoch 018 - train 0.36421 | val 0.76322
  Classification -> best τ=0.470 (val F1=0.3855)
  Directional -> Accuracy: 0.5217, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.58143 | val 1.34030
  Epoch 018 - train 0.53688 | val 1.27024
  Classification -> best τ=0.435 (val F1=0.2750)
  Directional -> Accuracy: 0.5147, MCC: 0.1280, F1: 0.5600

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.57898 | val 0.55018
  Epoch 018 - train 0.35077 | val 1.87044
  Classification -> best τ=0.095 (val F1=0.3855)
  Directional -> Accuracy: 0.5000, MCC: 0.0782, F1: 0.5714

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.59941 | val 1.35172
  Epoch 014 - train 0.42759 | val 1.56672
  Classification -> best τ=0.515 (val F1=0.3433)
  Directional -> Accuracy: 0.7083, MCC: 0.4184, F1: 0.5625

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.55353 | val 1.07857
  Epoch 014 - train 0.45331 | val 1.14589
  Classification -> best τ=0.565 (val F1=0.3245)
  Directional -> Accuracy: 0.5362, MCC: 0.0758, F1: 0.5000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.57158 | val 2.33014
  Epoch 012 - train 0.55589 | val 2.07767
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4490, MCC: 0.0000, F1: 0.6197

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.60320 | val 0.89766
  Epoch 013 - train 0.52917 | val 1.19463
  Classification -> best τ=0.510 (val F1=0.2487)
  Directional -> Accuracy: 0.5088, MCC: 0.0000, F1: 0.6744

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.51375 | val 2.00254
  Epoch 011 - train 0.48457 | val 2.23223
  Classification -> best τ=0.360 (val F1=0.1991)
  Directional -> Accuracy: 0.4048, MCC: -0.2460, F1: 0.5763

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.61720 | val 0.65074
  Epoch 015 - train 0.53307 | val 0.73571
  Classification -> best τ=0.400 (val F1=0.3281)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.62090 | val 0.74361
  Epoch 013 - train 0.52286 | val 0.93641
  Classification -> best τ=0.430 (val F1=0.1616)
  Directional -> Accuracy: 0.5098, MCC: 0.0216, F1: 0.4898

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.60698 | val 1.54852
  Epoch 015 - train 0.47536 | val 1.46677
  Classification -> best τ=0.690 (val F1=0.2169)
  Directional -> Accuracy: 0.5507, MCC: 0.1801, F1: 0.3922

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.58675 | val 0.82204
  Epoch 012 - train 0.51871 | val 0.74453
  Classification -> best τ=0.245 (val F1=0.2824)
  Directional -> Accuracy: 0.3793, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.59768 | val 0.87317
  Epoch 019 - train 0.46615 | val 0.95289
  Classification -> best τ=0.555 (val F1=0.1909)
  Directional -> Accuracy: 0.4000, MCC: -0.0338, F1: 0.0426

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.57555 | val 2.65478
  Epoch 014 - train 0.53083 | val 1.97283
  Classification -> best τ=0.285 (val F1=0.3426)
  Directional -> Accuracy: 0.5781, MCC: 0.0000, F1: 0.7327

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.55029 | val 1.20435
  Epoch 011 - train 0.51418 | val 1.15456
  Classification -> best τ=0.750 (val F1=0.2651)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.53370 | val 0.81519
  Epoch 011 - train 0.53047 | val 1.01083
  Classification -> best τ=0.380 (val F1=0.2784)
  Directional -> Accuracy: 0.6809, MCC: 0.2851, F1: 0.7826

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.59266 | val 2.00578
  Epoch 011 - train 0.55415 | val 1.96799
  Classification -> best τ=0.640 (val F1=0.1350)
  Directional -> Accuracy: 0.4923, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.67430 | val 0.62436
  Epoch 013 - train 0.58647 | val 0.70028
  Classification -> best τ=0.525 (val F1=0.4008)
  Directional -> Accuracy: 0.5789, MCC: 0.1706, F1: 0.5862

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.66827 | val 0.74266
  Epoch 017 - train 0.56540 | val 0.81554
  Classification -> best τ=0.460 (val F1=0.1599)
  Directional -> Accuracy: 0.4923, MCC: -0.0077, F1: 0.5217

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.57592 | val 1.00079
  Epoch 011 - train 0.51203 | val 0.94048
  Classification -> best τ=0.395 (val F1=0.3901)
  Directional -> Accuracy: 0.4727, MCC: -0.0745, F1: 0.5397

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.47764 | val 2.10300
  Epoch 012 - train 0.37859 | val 2.45296
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.5938

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.56475 | val 0.72542
  Epoch 011 - train 0.52369 | val 0.73811
  Classification -> best τ=0.570 (val F1=0.0574)
  Directional -> Accuracy: 0.5000, MCC: -0.0138, F1: 0.5532

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.54321 | val 2.42923
  Epoch 013 - train 0.49523 | val 1.83222
  Classification -> best τ=0.160 (val F1=0.2354)
  Directional -> Accuracy: 0.4464, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.66704 | val 1.26118
  Epoch 011 - train 0.59240 | val 0.88396
  Classification -> best τ=0.545 (val F1=0.3278)
  Directional -> Accuracy: 0.5250, MCC: -0.1448, F1: 0.6885

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.64068 | val 1.49378
  Epoch 011 - train 0.59422 | val 1.50331
  Classification -> best τ=0.545 (val F1=0.4146)
  Directional -> Accuracy: 0.4762, MCC: -0.0337, F1: 0.5417

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.57163 | val 0.85726
  Epoch 012 - train 0.53007 | val 1.01857
  Classification -> best τ=0.475 (val F1=0.2357)
  Directional -> Accuracy: 0.5476, MCC: 0.0000, F1: 0.7077

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.49033 | val 1.03199
  Epoch 011 - train 0.46311 | val 1.15650
  Classification -> best τ=0.335 (val F1=0.3833)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.59113 | val 0.78855
  Epoch 012 - train 0.52814 | val 0.91833
  Classification -> best τ=0.290 (val F1=0.3593)
  Directional -> Accuracy: 0.4861, MCC: -0.0507, F1: 0.5542

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.49503 | val 1.06705
  Epoch 011 - train 0.46476 | val 1.19133
  Classification -> best τ=0.595 (val F1=0.2151)
  Directional -> Accuracy: 0.6047, MCC: 0.3278, F1: 0.3200

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.60851 | val 1.89438
  Epoch 012 - train 0.52049 | val 1.65327
  Classification -> best τ=0.460 (val F1=0.2179)
  Directional -> Accuracy: 0.4697, MCC: 0.1873, F1: 0.1463

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.43103 | val 1.28507
  Epoch 011 - train 0.43614 | val 1.20428
  Classification -> best τ=0.475 (val F1=0.2858)
  Directional -> Accuracy: 0.5952, MCC: 0.2259, F1: 0.5143

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.57329 | val 0.77780
  Epoch 011 - train 0.48450 | val 0.83722
  Classification -> best τ=0.625 (val F1=0.2327)
  Directional -> Accuracy: 0.5000, MCC: 0.0103, F1: 0.5172

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.47836 | val 0.74255
  Epoch 011 - train 0.45830 | val 0.74493
  Classification -> best τ=0.625 (val F1=0.2659)
  Directional -> Accuracy: 0.3913, MCC: -0.0475, F1: 0.0667

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.53091 | val 0.95314
  Epoch 013 - train 0.54878 | val 1.25010
  Classification -> best τ=0.210 (val F1=0.4201)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.60828 | val 1.52097
  Epoch 014 - train 0.50852 | val 1.81703
  Classification -> best τ=0.410 (val F1=0.2951)
  Directional -> Accuracy: 0.5000, MCC: -0.0060, F1: 0.4308

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.61117 | val 1.16556
  Epoch 014 - train 0.48797 | val 0.80899
  Classification -> best τ=0.430 (val F1=0.3287)
  Directional -> Accuracy: 0.4889, MCC: -0.0119, F1: 0.3030

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.36743 | val 1.22557
  Epoch 011 - train 0.37911 | val 0.93935
  Classification -> best τ=0.460 (val F1=0.2041)
  Directional -> Accuracy: 0.6429, MCC: 0.2527, F1: 0.7170

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.50425 | val 0.87419
  Epoch 012 - train 0.43638 | val 0.95110
  Classification -> best τ=0.580 (val F1=0.4216)
  Directional -> Accuracy: 0.5417, MCC: 0.3464, F1: 0.6207

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.65323 | val 0.72041
  Epoch 012 - train 0.57913 | val 0.96087
  Classification -> best τ=0.500 (val F1=0.2291)
  Directional -> Accuracy: 0.4000, MCC: -0.2820, F1: 0.5352

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.49116 | val 2.27460
  Epoch 011 - train 0.42429 | val 2.73997
  Classification -> best τ=0.670 (val F1=0.3006)
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.6506

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.60967 | val 0.72013
  Epoch 011 - train 0.58312 | val 0.80420
  Classification -> best τ=0.405 (val F1=0.2369)
  Directional -> Accuracy: 0.6038, MCC: 0.2598, F1: 0.7042

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.53928 | val 2.90671
  Epoch 011 - train 0.46358 | val 3.85158
  Classification -> best τ=0.790 (val F1=0.0094)
  Directional -> Accuracy: 0.4182, MCC: -0.1848, F1: 0.1111

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.62067 | val 0.67554

[I 2026-02-22 16:17:43,035] Trial 246 finished with value: 0.26602258148739194 and parameters: {'feature_set': 'sector', 'model_type': 'BiGRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.4, 'batch_size': 16, 'learning_rate': 0.00653954260135487, 'weight_decay': 0.00031387670235286585, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 0.48331877240267673, 'early_stopping_min_delta': 0.0008844124293584509}. Best is trial 214 with value: 0.2991200218486954.

  Epoch 017 - train 0.60049 | val 1.20490
  Classification -> best τ=0.465 (val F1=0.2920)
  Directional -> Accuracy: 0.5167, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.26602258148739194
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.63539 | val 1.75653
  Epoch 012 - train 0.62603 | val 1.16456
  Classification -> best τ=0.480 (val F1=0.1671)
  Directional -> Accuracy: 0.5789, MCC: 0.1588, F1: 0.5556

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.51218 | val 0.81314
  Epoch 011 - train 0.44741 | val 0.93163
  Classification -> best τ=0.580 (val F1=0.2523)
  Directional -> Accuracy: 0.5778, MCC: 0.0492, F1: 0.7164

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.56733 | val 1.20591
  Epoch 012 - train 0.48424 | val 1.28040
  Classification -> best τ=0.600 (val F1=0.0850)
  Directional -> Accuracy: 0.4783, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.58472 | val 0.83645
  Epoch 011 - train 0.52502 | val 0.86154
  Classification -> best τ=0.385 (val F1=0.0242)
  Directional -> Accuracy: 0.5405, MCC: 0.0000, F1: 0.7018

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.55395 | val 0.94553
  Epoch 020 - train 0.37455 | val 0.79412
  Epoch 023 - train 0.29150 | val 0.80590
  Classification -> best τ=0.515 (val F1=0.5570)
  Directional -> Accuracy: 0.6600, MCC: 0.3398, F1: 0.6222

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.51806 | val 0.70507
  Epoch 014 - train 0.48034 | val 0.72246
  Classification -> best τ=0.560 (val F1=0.3624)
  Directional -> Accuracy: 0.5217, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.60054 | val 1.39451
  Epoch 012 - train 0.57253 | val 1.17065
  Classification -> best τ=0.535 (val F1=0.2492)
  Directional -> Accuracy: 0.4265, MCC: 0.0165, F1: 0.5517

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.54095 | val 0.82755
  Epoch 016 - train 0.34812 | val 1.06847
  Classification -> best τ=0.350 (val F1=0.3632)
  Directional -> Accuracy: 0.5000, MCC: 0.0138, F1: 0.4878

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.59564 | val 1.08065
  Epoch 011 - train 0.47969 | val 1.22882
  Classification -> best τ=0.265 (val F1=0.2497)
  Directional -> Accuracy: 0.4375, MCC: 0.0000, F1: 0.6087

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.51443 | val 0.90154
  Epoch 011 - train 0.49418 | val 1.31630
  Classification -> best τ=0.385 (val F1=0.2971)
  Directional -> Accuracy: 0.4928, MCC: 0.0780, F1: 0.5679

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.62255 | val 1.31258
  Epoch 013 - train 0.51687 | val 0.77672
  Classification -> best τ=0.560 (val F1=0.4059)
  Directional -> Accuracy: 0.5714, MCC: 0.1118, F1: 0.1600

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.57566 | val 0.95813
  Epoch 012 - train 0.52244 | val 0.99314
  Classification -> best τ=0.660 (val F1=0.2320)
  Directional -> Accuracy: 0.4561, MCC: -0.1248, F1: 0.5867

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.51732 | val 1.43880
  Epoch 012 - train 0.38785 | val 1.78499
  Classification -> best τ=0.585 (val F1=0.3520)
  Directional -> Accuracy: 0.5476, MCC: 0.0000, F1: 0.0000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.57235 | val 0.70879
  Epoch 011 - train 0.56634 | val 0.75064
  Classification -> best τ=0.450 (val F1=0.2531)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.55828 | val 0.68909
  Epoch 020 - train 0.47801 | val 1.16765
  Epoch 022 - train 0.37137 | val 0.99876
  Classification -> best τ=0.480 (val F1=0.2000)
  Directional -> Accuracy: 0.5882, MCC: 0.1718, F1: 0.5532

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.60272 | val 0.82479
  Epoch 011 - train 0.56027 | val 0.79785
  Classification -> best τ=0.575 (val F1=0.2604)
  Directional -> Accuracy: 0.5217, MCC: -0.0237, F1: 0.6667

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.54615 | val 1.01413
  Epoch 011 - train 0.52975 | val 1.03988
  Classification -> best τ=0.530 (val F1=0.1930)
  Directional -> Accuracy: 0.3793, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.58811 | val 0.91542
  Epoch 011 - train 0.53456 | val 0.90853
  Classification -> best τ=0.370 (val F1=0.1605)
  Directional -> Accuracy: 0.5867, MCC: 0.1742, F1: 0.6265

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.61397 | val 1.64467
  Epoch 012 - train 0.54522 | val 1.56175
  Classification -> best τ=0.270 (val F1=0.3421)
  Directional -> Accuracy: 0.5000, MCC: -0.0149, F1: 0.5556

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.51785 | val 0.98493
  Epoch 011 - train 0.51916 | val 1.05309
  Classification -> best τ=0.440 (val F1=0.3471)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.54280 | val 0.89394
  Epoch 011 - train 0.50618 | val 1.08571
  Classification -> best τ=0.550 (val F1=0.0895)
  Directional -> Accuracy: 0.5745, MCC: -0.0074, F1: 0.7059

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.59416 | val 1.93402
  Epoch 011 - train 0.55604 | val 2.20033
  Classification -> best τ=0.515 (val F1=0.1157)
  Directional -> Accuracy: 0.5077, MCC: 0.0000, F1: 0.6735

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.67182 | val 0.75085
  Epoch 013 - train 0.55094 | val 0.67455
  Classification -> best τ=0.450 (val F1=0.3800)
  Directional -> Accuracy: 0.5789, MCC: 0.1021, F1: 0.7000

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.61328 | val 0.78707
  Epoch 011 - train 0.58928 | val 0.73371
  Classification -> best τ=0.600 (val F1=0.1393)
  Directional -> Accuracy: 0.5231, MCC: 0.0000, F1: 0.0000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.53172 | val 0.94229
  Epoch 011 - train 0.48458 | val 1.24504
  Classification -> best τ=0.390 (val F1=0.4380)
  Directional -> Accuracy: 0.4727, MCC: -0.0467, F1: 0.4727

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.46705 | val 2.49766
  Epoch 013 - train 0.42943 | val 2.73619
  Classification -> best τ=0.730 (val F1=0.2035)
  Directional -> Accuracy: 0.4667, MCC: 0.0240, F1: 0.5556

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.62787 | val 1.18621
  Epoch 012 - train 0.57958 | val 1.07556
  Classification -> best τ=0.635 (val F1=0.0278)
  Directional -> Accuracy: 0.5238, MCC: 0.0000, F1: 0.6154

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.57944 | val 2.01820
  Epoch 013 - train 0.47235 | val 1.53870
  Classification -> best τ=0.635 (val F1=0.3147)
  Directional -> Accuracy: 0.4464, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.44164 | val 2.55516
  Epoch 011 - train 0.44916 | val 2.61634
  Classification -> best τ=0.525 (val F1=0.3278)
  Directional -> Accuracy: 0.6000, MCC: 0.2536, F1: 0.7333

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.57994 | val 2.11369
  Epoch 013 - train 0.52540 | val 1.59716
  Classification -> best τ=0.775 (val F1=0.3501)
  Directional -> Accuracy: 0.4524, MCC: -0.1706, F1: 0.1481

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.61629 | val 1.57698
  Epoch 011 - train 0.55802 | val 1.46989
  Classification -> best τ=0.600 (val F1=0.1286)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.72531 | val 1.01746
  Epoch 011 - train 0.46963 | val 1.06066
  Classification -> best τ=0.515 (val F1=0.3541)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.60721 | val 0.79664
  Epoch 013 - train 0.53365 | val 0.94501
  Classification -> best τ=0.515 (val F1=0.3419)
  Directional -> Accuracy: 0.4444, MCC: 0.0000, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.51813 | val 1.62660
  Epoch 012 - train 0.44361 | val 1.64867
  Classification -> best τ=0.690 (val F1=0.2603)
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.62500 | val 1.01593
  Epoch 017 - train 0.56517 | val 1.24108
  Classification -> best τ=0.315 (val F1=0.2858)
  Directional -> Accuracy: 0.5000, MCC: 0.1624, F1: 0.2979

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.40216 | val 3.15894
  Epoch 011 - train 0.37501 | val 3.56952
  Classification -> best τ=0.560 (val F1=0.2750)
  Directional -> Accuracy: 0.6429, MCC: 0.3511, F1: 0.5455

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.52536 | val 1.47079
  Epoch 011 - train 0.49899 | val 1.34248
  Classification -> best τ=0.295 (val F1=0.1986)
  Directional -> Accuracy: 0.4643, MCC: -0.0493, F1: 0.5312

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.58408 | val 0.74137
  Epoch 012 - train 0.40880 | val 0.88312
  Classification -> best τ=0.505 (val F1=0.4666)
  Directional -> Accuracy: 0.6087, MCC: 0.0000, F1: 0.7568

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.54177 | val 0.90315
  Epoch 014 - train 0.46145 | val 1.12494
  Classification -> best τ=0.390 (val F1=0.4011)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.58129 | val 1.90098
  Epoch 013 - train 0.53508 | val 1.36665
  Classification -> best τ=0.300 (val F1=0.2319)
  Directional -> Accuracy: 0.4865, MCC: 0.0000, F1: 0.6545

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.58233 | val 1.72673
  Epoch 012 - train 0.48247 | val 1.91746
  Classification -> best τ=0.615 (val F1=0.0395)
  Directional -> Accuracy: 0.4889, MCC: 0.0000, F1: 0.0000

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.51379 | val 1.59048
  Epoch 012 - train 0.31051 | val 2.25022
  Classification -> best τ=0.905 (val F1=0.3612)
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.0000

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.47529 | val 0.75357
  Epoch 020 - train 0.35570 | val 1.21424
  Epoch 023 - train 0.21990 | val 1.28614
  Classification -> best τ=0.745 (val F1=0.5421)
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.5455

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.63482 | val 1.40242
  Epoch 014 - train 0.53480 | val 1.30022
  Classification -> best τ=0.345 (val F1=0.2833)
  Directional -> Accuracy: 0.4000, MCC: -0.2476, F1: 0.5075

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.49739 | val 2.97362
  Epoch 011 - train 0.42043 | val 3.13391
  Classification -> best τ=0.440 (val F1=0.3585)
  Directional -> Accuracy: 0.4821, MCC: -0.0069, F1: 0.6420

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.64998 | val 0.71203
  Epoch 015 - train 0.58385 | val 0.75767
  Classification -> best τ=0.490 (val F1=0.2351)
  Directional -> Accuracy: 0.6038, MCC: 0.2213, F1: 0.6769

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.55047 | val 3.24164
  Epoch 012 - train 0.45971 | val 2.94668
  Classification -> best τ=0.860 (val F1=0.3092)
  Directional -> Accuracy: 0.3636, MCC: -0.3324, F1: 0.0541

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.61626 | val 0.77400

[I 2026-02-22 16:21:58,684] Trial 247 finished with value: 0.27214239719047056 and parameters: {'feature_set': 'sector', 'model_type': 'BiGRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.4, 'batch_size': 16, 'learning_rate': 0.008063780219583278, 'weight_decay': 0.00021937395355171437, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 0.96911549352348, 'early_stopping_min_delta': 0.001588396732788023}. Best is trial 214 with value: 0.2991200218486954.

  Epoch 013 - train 0.56525 | val 0.71806
  Classification -> best τ=0.465 (val F1=0.2507)
  Directional -> Accuracy: 0.5500, MCC: 0.0973, F1: 0.3721

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.27214239719047056
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.60115 | val 1.74372
  Epoch 011 - train 0.59183 | val 2.27580
  Classification -> best τ=0.725 (val F1=0.2510)
  Directional -> Accuracy: 0.5395, MCC: -0.1039, F1: 0.0000

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.54294 | val 1.29490
  Epoch 011 - train 0.47304 | val 1.62505
  Classification -> best τ=0.530 (val F1=0.2073)
  Directional -> Accuracy: 0.4889, MCC: -0.0402, F1: 0.5490

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.54259 | val 1.86517
  Epoch 011 - train 0.47830 | val 2.40570
  Classification -> best τ=0.715 (val F1=0.3114)
  Directional -> Accuracy: 0.5870, MCC: 0.2143, F1: 0.4865

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.63761 | val 0.70541
  Epoch 012 - train 0.59034 | val 0.89799
  Classification -> best τ=0.480 (val F1=0.2920)
  Directional -> Accuracy: 0.5405, MCC: 0.0000, F1: 0.7018

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.60729 | val 1.32648
  Epoch 012 - train 0.48962 | val 1.53122
  Classification -> best τ=0.640 (val F1=0.5167)
  Directional -> Accuracy: 0.7200, MCC: 0.4423, F1: 0.7200

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.55517 | val 2.09100
  Epoch 012 - train 0.46719 | val 0.70194
  Classification -> best τ=0.610 (val F1=0.4070)
  Directional -> Accuracy: 0.5217, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.61831 | val 1.07932
  Epoch 011 - train 0.58313 | val 1.20333
  Classification -> best τ=0.180 (val F1=0.2944)
  Directional -> Accuracy: 0.3971, MCC: 0.0000, F1: 0.5684

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.45913 | val 0.81199
  Epoch 015 - train 0.40633 | val 2.36354
  Classification -> best τ=0.290 (val F1=0.4453)
  Directional -> Accuracy: 0.5714, MCC: 0.0913, F1: 0.4000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.54319 | val 2.63031
  Epoch 011 - train 0.48805 | val 2.93909
  Classification -> best τ=0.445 (val F1=0.2231)
  Directional -> Accuracy: 0.4375, MCC: 0.0000, F1: 0.6087

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.61934 | val 0.79641
  Epoch 020 - train 0.58495 | val 1.86355
  Epoch 022 - train 0.51869 | val 2.46843
  Classification -> best τ=0.650 (val F1=0.1607)
  Directional -> Accuracy: 0.5072, MCC: -0.0112, F1: 0.4138

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.62575 | val 1.59197
  Epoch 013 - train 0.50564 | val 1.62181
  Classification -> best τ=0.620 (val F1=0.0825)
  Directional -> Accuracy: 0.5714, MCC: 0.1118, F1: 0.1600

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.63191 | val 0.80023
  Epoch 013 - train 0.53525 | val 1.12120
  Classification -> best τ=0.630 (val F1=0.1620)
  Directional -> Accuracy: 0.6316, MCC: 0.3198, F1: 0.7200

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.47743 | val 0.96026
  Epoch 017 - train 0.40084 | val 0.82050
  Classification -> best τ=0.490 (val F1=0.4385)
  Directional -> Accuracy: 0.6190, MCC: 0.2567, F1: 0.3333

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.64455 | val 0.89541
  Epoch 012 - train 0.57716 | val 1.05869
  Classification -> best τ=0.410 (val F1=0.3268)
  Directional -> Accuracy: 0.5500, MCC: 0.1048, F1: 0.4706

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.61045 | val 0.93544
  Epoch 013 - train 0.52909 | val 1.61879
  Classification -> best τ=0.635 (val F1=0.2571)
  Directional -> Accuracy: 0.5490, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.53396 | val 1.44194
  Epoch 011 - train 0.52712 | val 1.61794
  Classification -> best τ=0.805 (val F1=0.0972)
  Directional -> Accuracy: 0.4638, MCC: 0.0000, F1: 0.0000

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.61218 | val 1.55269
  Epoch 014 - train 0.50411 | val 1.23864
  Classification -> best τ=0.600 (val F1=0.2942)
  Directional -> Accuracy: 0.4138, MCC: 0.1477, F1: 0.1053

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.61670 | val 1.12480
  Epoch 012 - train 0.55948 | val 1.15298
  Classification -> best τ=0.550 (val F1=0.1909)
  Directional -> Accuracy: 0.4267, MCC: 0.1351, F1: 0.0851

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.57546 | val 1.06240
  Epoch 011 - train 0.52963 | val 1.40169
  Classification -> best τ=0.455 (val F1=0.1898)
  Directional -> Accuracy: 0.5000, MCC: 0.1376, F1: 0.3333

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.59030 | val 1.21798
  Epoch 012 - train 0.48341 | val 1.08861
  Classification -> best τ=0.615 (val F1=0.2470)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.58912 | val 1.60529
  Epoch 012 - train 0.44228 | val 0.77790
  Classification -> best τ=0.530 (val F1=0.2779)
  Directional -> Accuracy: 0.5532, MCC: 0.1043, F1: 0.6038

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.65697 | val 2.46101
  Epoch 011 - train 0.58772 | val 2.49277
  Classification -> best τ=0.205 (val F1=0.2037)
  Directional -> Accuracy: 0.5077, MCC: 0.0000, F1: 0.6735

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.65235 | val 0.76488
  Epoch 019 - train 0.55987 | val 1.23937
  Classification -> best τ=0.395 (val F1=0.3906)
  Directional -> Accuracy: 0.5965, MCC: 0.1576, F1: 0.7229

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.63614 | val 0.68906
  Epoch 019 - train 0.51989 | val 0.80451
  Classification -> best τ=0.370 (val F1=0.1122)
  Directional -> Accuracy: 0.4769, MCC: -0.0242, F1: 0.5854

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.59840 | val 0.63129
  Epoch 020 - train 0.52868 | val 0.94769
  Classification -> best τ=0.315 (val F1=0.4068)
  Directional -> Accuracy: 0.5273, MCC: 0.1463, F1: 0.3500

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.47464 | val 1.41995
  Epoch 013 - train 0.32585 | val 1.78479
  Classification -> best τ=0.785 (val F1=0.2726)
  Directional -> Accuracy: 0.5111, MCC: -0.2285, F1: 0.0000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.57006 | val 0.74361
  Epoch 013 - train 0.45965 | val 0.72591
  Classification -> best τ=0.615 (val F1=0.2582)
  Directional -> Accuracy: 0.4048, MCC: -0.1803, F1: 0.0000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.61186 | val 0.95657
  Epoch 012 - train 0.48069 | val 1.52412
  Classification -> best τ=0.350 (val F1=0.2841)
  Directional -> Accuracy: 0.4464, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.44817 | val 2.31625
  Epoch 012 - train 0.53997 | val 1.71853
  Classification -> best τ=0.415 (val F1=0.3278)
  Directional -> Accuracy: 0.6000, MCC: 0.2536, F1: 0.7333

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.55542 | val 1.15117
  Epoch 013 - train 0.51370 | val 0.77634
  Classification -> best τ=0.560 (val F1=0.3501)
  Directional -> Accuracy: 0.5238, MCC: 0.0413, F1: 0.4737

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.53308 | val 0.87592
  Epoch 011 - train 0.50361 | val 0.99447
  Classification -> best τ=0.455 (val F1=0.3054)
  Directional -> Accuracy: 0.5238, MCC: 0.0214, F1: 0.6000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.53444 | val 1.07924
  Epoch 011 - train 0.51103 | val 0.83411
  Classification -> best τ=0.380 (val F1=0.3850)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.59658 | val 0.66200
  Epoch 018 - train 0.48175 | val 0.94711
  Classification -> best τ=0.545 (val F1=0.3278)
  Directional -> Accuracy: 0.4722, MCC: 0.0949, F1: 0.1364

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.55954 | val 0.88015
  Epoch 011 - train 0.48099 | val 0.91741
  Classification -> best τ=0.650 (val F1=0.2151)
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.64038 | val 1.26192
  Epoch 011 - train 0.56029 | val 1.44421
  Classification -> best τ=0.530 (val F1=0.1822)
  Directional -> Accuracy: 0.4242, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.39265 | val 1.17280
  Epoch 013 - train 0.37383 | val 1.08980
  Classification -> best τ=0.555 (val F1=0.3589)
  Directional -> Accuracy: 0.6190, MCC: 0.3091, F1: 0.5000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.59553 | val 0.89267
  Epoch 012 - train 0.54156 | val 1.45693
  Classification -> best τ=0.535 (val F1=0.1951)
  Directional -> Accuracy: 0.5893, MCC: 0.1690, F1: 0.5306

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.57020 | val 1.01175
  Epoch 011 - train 0.45345 | val 0.87274
  Classification -> best τ=0.375 (val F1=0.4377)
  Directional -> Accuracy: 0.3913, MCC: -0.0475, F1: 0.0667

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.56898 | val 0.95830
  Epoch 012 - train 0.54277 | val 0.91971
  Classification -> best τ=0.430 (val F1=0.4011)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.61082 | val 1.27722
  Epoch 013 - train 0.48660 | val 2.26153
  Classification -> best τ=0.360 (val F1=0.3548)
  Directional -> Accuracy: 0.4865, MCC: 0.0000, F1: 0.6545

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.65213 | val 1.30753
  Epoch 014 - train 0.51303 | val 2.17943
  Classification -> best τ=0.545 (val F1=0.3953)
  Directional -> Accuracy: 0.4889, MCC: -0.0048, F1: 0.0800

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.50077 | val 1.74377
  Epoch 012 - train 0.36846 | val 2.88647
  Classification -> best τ=0.300 (val F1=0.5092)
  Directional -> Accuracy: 0.6190, MCC: 0.2582, F1: 0.7500

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.42266 | val 0.71512
  Epoch 020 - train 0.22765 | val 0.58277
  Epoch 028 - train 0.13809 | val 1.08074
  Classification -> best τ=0.720 (val F1=0.6110)
  Directional -> Accuracy: 0.4167, MCC: 0.1615, F1: 0.5625

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.67261 | val 1.48749
  Epoch 012 - train 0.60790 | val 1.40408
  Classification -> best τ=0.620 (val F1=0.2036)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.51948 | val 4.34530
  Epoch 011 - train 0.51533 | val 4.43378
  Classification -> best τ=0.480 (val F1=0.2137)
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.6506

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.71424 | val 0.82992
  Epoch 013 - train 0.61782 | val 0.98496
  Classification -> best τ=0.550 (val F1=0.2908)
  Directional -> Accuracy: 0.5094, MCC: 0.0000, F1: 0.6750

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.51858 | val 2.89523
  Epoch 017 - train 0.49642 | val 4.68945
  Classification -> best τ=0.885 (val F1=0.2693)
  Directional -> Accuracy: 0.4727, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.66389 | val 0.93274

[I 2026-02-22 16:26:26,704] Trial 248 finished with value: 0.2957776189162271 and parameters: {'feature_set': 'sector', 'model_type': 'BiGRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.4, 'batch_size': 16, 'learning_rate': 0.009957759437181178, 'weight_decay': 0.0002678337787172486, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 0.9304847198253684, 'early_stopping_min_delta': 0.002378155358314797}. Best is trial 214 with value: 0.2991200218486954.

  Epoch 012 - train 0.58453 | val 0.95238
  Classification -> best τ=0.400 (val F1=0.2623)
  Directional -> Accuracy: 0.5167, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2957776189162271
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.64208 | val 1.26303
  Epoch 012 - train 0.60813 | val 0.90843
  Classification -> best τ=0.740 (val F1=0.2919)
  Directional -> Accuracy: 0.5526, MCC: 0.0000, F1: 0.0000

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.55329 | val 0.78858
  Epoch 013 - train 0.46664 | val 0.79224
  Classification -> best τ=0.600 (val F1=0.2523)
  Directional -> Accuracy: 0.6222, MCC: 0.2110, F1: 0.6909

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.57059 | val 0.92462
  Epoch 011 - train 0.58842 | val 0.89231
  Classification -> best τ=0.675 (val F1=0.2727)
  Directional -> Accuracy: 0.4565, MCC: -0.0996, F1: 0.0741

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.64473 | val 0.80247
  Epoch 016 - train 0.56749 | val 0.86986
  Classification -> best τ=0.445 (val F1=0.1079)
  Directional -> Accuracy: 0.5405, MCC: 0.0358, F1: 0.6667

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.60883 | val 0.68896
  Epoch 013 - train 0.49665 | val 0.78794
  Classification -> best τ=0.555 (val F1=0.5079)
  Directional -> Accuracy: 0.6800, MCC: 0.3677, F1: 0.6667

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.50817 | val 0.76006
  Epoch 015 - train 0.50391 | val 0.77344
  Classification -> best τ=0.575 (val F1=0.3377)
  Directional -> Accuracy: 0.5217, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.64400 | val 0.88708
  Epoch 017 - train 0.60508 | val 0.96040
  Classification -> best τ=0.410 (val F1=0.2810)
  Directional -> Accuracy: 0.5294, MCC: -0.0220, F1: 0.3333

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.45857 | val 1.95017
  Epoch 014 - train 0.49322 | val 2.05578
  Classification -> best τ=0.170 (val F1=0.3158)
  Directional -> Accuracy: 0.4762, MCC: 0.1936, F1: 0.6207

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.60062 | val 1.03941
  Epoch 012 - train 0.55916 | val 1.55904
  Classification -> best τ=0.615 (val F1=0.1928)
  Directional -> Accuracy: 0.5833, MCC: 0.1116, F1: 0.2857

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.60199 | val 0.84555
  Epoch 012 - train 0.55733 | val 0.83357
  Classification -> best τ=0.655 (val F1=0.1552)
  Directional -> Accuracy: 0.5652, MCC: 0.1442, F1: 0.5455

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.59535 | val 1.51282
  Epoch 014 - train 0.56031 | val 1.93127
  Classification -> best τ=0.685 (val F1=0.3075)
  Directional -> Accuracy: 0.5714, MCC: 0.1118, F1: 0.1600

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.62671 | val 0.82631
  Epoch 013 - train 0.55955 | val 1.39357
  Classification -> best τ=0.650 (val F1=0.2083)
  Directional -> Accuracy: 0.4737, MCC: -0.0518, F1: 0.4643

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.57053 | val 1.15570
  Epoch 012 - train 0.48026 | val 0.82115
  Classification -> best τ=0.345 (val F1=0.1991)
  Directional -> Accuracy: 0.4286, MCC: -0.1194, F1: 0.5862

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.66405 | val 0.84244
  Epoch 018 - train 0.59214 | val 0.90795
  Classification -> best τ=0.420 (val F1=0.3387)
  Directional -> Accuracy: 0.5833, MCC: 0.1849, F1: 0.4681

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.63513 | val 0.72268
  Epoch 019 - train 0.55550 | val 0.87739
  Classification -> best τ=0.450 (val F1=0.1925)
  Directional -> Accuracy: 0.5294, MCC: 0.1742, F1: 0.6364

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.64333 | val 0.88507
  Epoch 011 - train 0.58150 | val 0.91393
  Classification -> best τ=0.685 (val F1=0.2299)
  Directional -> Accuracy: 0.5072, MCC: 0.0135, F1: 0.5278

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.60491 | val 0.76243
  Epoch 011 - train 0.56551 | val 0.87846
  Classification -> best τ=0.530 (val F1=0.1973)
  Directional -> Accuracy: 0.5000, MCC: 0.2369, F1: 0.3556

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.66384 | val 0.70367
  Epoch 014 - train 0.53697 | val 0.78096
  Classification -> best τ=0.605 (val F1=0.2367)
  Directional -> Accuracy: 0.4267, MCC: 0.1351, F1: 0.0851

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.60613 | val 1.42892
  Epoch 012 - train 0.55504 | val 1.21626
  Classification -> best τ=0.495 (val F1=0.2770)
  Directional -> Accuracy: 0.5000, MCC: 0.1167, F1: 0.3600

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.57740 | val 1.15217
  Epoch 014 - train 0.53928 | val 1.12626
  Classification -> best τ=0.730 (val F1=0.3062)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.59516 | val 2.01490
  Epoch 016 - train 0.51337 | val 1.74734
  Classification -> best τ=0.740 (val F1=0.3237)
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.63213 | val 1.42066
  Epoch 011 - train 0.56781 | val 2.00563
  Classification -> best τ=0.490 (val F1=0.2865)
  Directional -> Accuracy: 0.4000, MCC: -0.2009, F1: 0.4179

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.66865 | val 0.67814
  Epoch 020 - train 0.59352 | val 0.78609
  Epoch 024 - train 0.56265 | val 0.71709
  Classification -> best τ=0.640 (val F1=0.4649)
  Directional -> Accuracy: 0.4561, MCC: -0.0338, F1: 0.3404

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.59534 | val 0.89652
  Epoch 020 - train 0.56526 | val 0.79113
  Epoch 025 - train 0.49424 | val 0.83330
  Classification -> best τ=0.485 (val F1=0.1702)
  Directional -> Accuracy: 0.4615, MCC: -0.0636, F1: 0.5455

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.61923 | val 1.07946
  Epoch 018 - train 0.50897 | val 0.89235
  Classification -> best τ=0.405 (val F1=0.4399)
  Directional -> Accuracy: 0.5636, MCC: 0.1144, F1: 0.6129

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.55133 | val 1.61355
  Epoch 011 - train 0.49900 | val 1.88537
  Classification -> best τ=0.585 (val F1=0.4328)
  Directional -> Accuracy: 0.6444, MCC: 0.4138, F1: 0.6923

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.62272 | val 0.71352
  Epoch 016 - train 0.50493 | val 0.78623
  Classification -> best τ=0.570 (val F1=0.0138)
  Directional -> Accuracy: 0.5952, MCC: 0.1925, F1: 0.6222

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.58960 | val 1.30484
  Epoch 014 - train 0.49888 | val 1.84416
  Classification -> best τ=0.435 (val F1=0.3147)
  Directional -> Accuracy: 0.4464, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.55758 | val 0.84554
  Epoch 012 - train 0.47656 | val 1.29536
  Classification -> best τ=0.445 (val F1=0.2618)
  Directional -> Accuracy: 0.6250, MCC: 0.3148, F1: 0.7458

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.58026 | val 0.96639
  Epoch 011 - train 0.57182 | val 1.12760
  Classification -> best τ=0.505 (val F1=0.2814)
  Directional -> Accuracy: 0.5714, MCC: 0.1685, F1: 0.6250

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.59377 | val 1.56870
  Epoch 012 - train 0.60168 | val 1.00345
  Classification -> best τ=0.520 (val F1=0.2042)
  Directional -> Accuracy: 0.6190, MCC: 0.2622, F1: 0.6000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.59239 | val 0.66188
  Epoch 020 - train 0.47153 | val 1.07237
  Classification -> best τ=0.330 (val F1=0.3541)
  Directional -> Accuracy: 0.5306, MCC: 0.0923, F1: 0.4390

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.62166 | val 0.73591
  Epoch 015 - train 0.57997 | val 0.72733
  Classification -> best τ=0.240 (val F1=0.3477)
  Directional -> Accuracy: 0.5556, MCC: 0.0000, F1: 0.7143

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.55832 | val 0.72959
  Epoch 011 - train 0.50799 | val 0.85836
  Classification -> best τ=0.380 (val F1=0.1874)
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.66223 | val 1.11861
  Epoch 017 - train 0.56541 | val 1.91927
  Classification -> best τ=0.320 (val F1=0.3373)
  Directional -> Accuracy: 0.4848, MCC: -0.0646, F1: 0.5641

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.50859 | val 2.61609
  Epoch 011 - train 0.53450 | val 2.07414
  Classification -> best τ=0.470 (val F1=0.2839)
  Directional -> Accuracy: 0.6429, MCC: 0.2919, F1: 0.6341

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.57476 | val 0.83679
  Epoch 011 - train 0.55653 | val 0.86383
  Classification -> best τ=0.440 (val F1=0.3145)
  Directional -> Accuracy: 0.5536, MCC: 0.0962, F1: 0.4898

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.53542 | val 1.50320
  Epoch 015 - train 0.40291 | val 2.13473
  Classification -> best τ=0.675 (val F1=0.2804)
  Directional -> Accuracy: 0.4130, MCC: 0.0314, F1: 0.1290

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.55116 | val 1.02563
  Epoch 011 - train 0.56111 | val 1.01810
  Classification -> best τ=0.555 (val F1=0.4306)
  Directional -> Accuracy: 0.3750, MCC: -0.0643, F1: 0.4828

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.58706 | val 1.53408
  Epoch 013 - train 0.57958 | val 1.15287
  Classification -> best τ=0.395 (val F1=0.3373)
  Directional -> Accuracy: 0.4730, MCC: -0.0638, F1: 0.3810

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.60491 | val 0.79680
  Epoch 017 - train 0.53825 | val 0.75496
  Classification -> best τ=0.435 (val F1=0.3953)
  Directional -> Accuracy: 0.5111, MCC: 0.0518, F1: 0.2667

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.45343 | val 2.12218
  Epoch 011 - train 0.38996 | val 2.78348
  Classification -> best τ=0.765 (val F1=0.3612)
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.0000

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.52378 | val 0.62230
  Epoch 015 - train 0.41995 | val 0.64858
  Classification -> best τ=0.585 (val F1=0.4795)
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.5455

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.64813 | val 1.01851
  Epoch 013 - train 0.62550 | val 1.35718
  Classification -> best τ=0.605 (val F1=0.2036)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.58147 | val 2.14884
  Epoch 011 - train 0.49962 | val 1.96509
  Classification -> best τ=0.765 (val F1=0.2793)
  Directional -> Accuracy: 0.5536, MCC: 0.1135, F1: 0.5763

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.66100 | val 0.72111
  Epoch 011 - train 0.64036 | val 0.72723
  Classification -> best τ=0.530 (val F1=0.2741)
  Directional -> Accuracy: 0.5849, MCC: 0.1704, F1: 0.6333

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.58207 | val 1.46165
  Epoch 017 - train 0.47169 | val 4.24525
  Classification -> best τ=0.830 (val F1=0.2368)
  Directional -> Accuracy: 0.4182, MCC: -0.2537, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.63306 | val 0.89821

[I 2026-02-22 16:30:38,734] Trial 249 finished with value: 0.2868202790403003 and parameters: {'feature_set': 'sector', 'model_type': 'BiGRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.4, 'batch_size': 16, 'learning_rate': 0.009993755517199516, 'weight_decay': 0.000284267503362372, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 1.0474733222392367, 'early_stopping_min_delta': 0.0012704472808615776}. Best is trial 214 with value: 0.2991200218486954.

  Epoch 011 - train 0.62533 | val 1.07375
  Classification -> best τ=0.560 (val F1=0.2623)
  Directional -> Accuracy: 0.5167, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2868202790403003
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.65402 | val 0.91905
  Epoch 011 - train 0.61197 | val 0.86613
  Classification -> best τ=0.820 (val F1=0.2510)
  Directional -> Accuracy: 0.5526, MCC: 0.0249, F1: 0.1053

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.54381 | val 0.73242
  Epoch 011 - train 0.56373 | val 0.74840
  Classification -> best τ=0.710 (val F1=0.2523)
  Directional -> Accuracy: 0.6222, MCC: 0.2030, F1: 0.7018

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.55548 | val 1.29753
  Epoch 011 - train 0.54764 | val 1.41516
  Classification -> best τ=0.610 (val F1=0.2311)
  Directional -> Accuracy: 0.5000, MCC: 0.0421, F1: 0.2581

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.61683 | val 0.79287
  Epoch 011 - train 0.56722 | val 0.97043
  Classification -> best τ=0.525 (val F1=0.2204)
  Directional -> Accuracy: 0.4595, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.55237 | val 1.31844
  Epoch 011 - train 0.53978 | val 2.17340
  Classification -> best τ=0.475 (val F1=0.3688)
  Directional -> Accuracy: 0.7000, MCC: 0.4120, F1: 0.6809

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.56810 | val 0.68225
  Epoch 020 - train 0.32592 | val 1.53511
  Epoch 021 - train 0.36320 | val 1.68484
  Classification -> best τ=0.540 (val F1=0.4957)
  Directional -> Accuracy: 0.5217, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.64239 | val 0.88629
  Epoch 019 - train 0.53986 | val 1.26363
  Classification -> best τ=0.445 (val F1=0.3911)
  Directional -> Accuracy: 0.5441, MCC: 0.0296, F1: 0.3922

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.52962 | val 0.85342
  Epoch 015 - train 0.41294 | val 1.77074
  Classification -> best τ=0.185 (val F1=0.1147)
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.63118 | val 1.01794
  Epoch 013 - train 0.58146 | val 1.03024
  Classification -> best τ=0.355 (val F1=0.1743)
  Directional -> Accuracy: 0.4375, MCC: 0.0000, F1: 0.6087

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.62213 | val 0.70008
  Epoch 020 - train 0.41681 | val 0.82457
  Classification -> best τ=0.520 (val F1=0.2524)
  Directional -> Accuracy: 0.5072, MCC: 0.0562, F1: 0.5278

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.60064 | val 1.01469
  Epoch 014 - train 0.64515 | val 0.82898
  Classification -> best τ=0.470 (val F1=0.1064)
  Directional -> Accuracy: 0.6122, MCC: 0.2178, F1: 0.3448

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.59619 | val 0.84809
  Epoch 011 - train 0.56584 | val 0.88660
  Classification -> best τ=0.605 (val F1=0.0423)
  Directional -> Accuracy: 0.5439, MCC: 0.0993, F1: 0.4583

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.53657 | val 1.08355
  Epoch 020 - train 0.42203 | val 0.79563
  Epoch 028 - train 0.21341 | val 0.72960
  Classification -> best τ=0.515 (val F1=0.3803)
  Directional -> Accuracy: 0.4762, MCC: -0.0389, F1: 0.4762

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.65498 | val 0.70617
  Epoch 012 - train 0.61670 | val 0.69096
  Classification -> best τ=0.425 (val F1=0.3916)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.60773 | val 0.95268
  Epoch 011 - train 0.57288 | val 0.89416
  Classification -> best τ=0.400 (val F1=0.3055)
  Directional -> Accuracy: 0.5294, MCC: 0.0203, F1: 0.3684

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.61319 | val 1.37208
  Epoch 013 - train 0.54021 | val 1.00345
  Classification -> best τ=0.285 (val F1=0.1741)
  Directional -> Accuracy: 0.4783, MCC: -0.1200, F1: 0.6170

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.57670 | val 1.20573
  Epoch 012 - train 0.60173 | val 1.42254
  Classification -> best τ=0.135 (val F1=0.3095)
  Directional -> Accuracy: 0.5000, MCC: 0.1131, F1: 0.4528

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.60791 | val 1.17378
  Epoch 011 - train 0.57026 | val 1.17551
  Classification -> best τ=0.460 (val F1=0.1909)
  Directional -> Accuracy: 0.4000, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.60303 | val 1.27647
  Epoch 012 - train 0.55021 | val 1.22830
  Classification -> best τ=0.480 (val F1=0.3241)
  Directional -> Accuracy: 0.5781, MCC: 0.0990, F1: 0.6747

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.61422 | val 1.18777
  Epoch 011 - train 0.54423 | val 1.08422
  Classification -> best τ=0.655 (val F1=0.2230)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.56869 | val 1.14779
  Epoch 012 - train 0.54145 | val 1.03927
  Classification -> best τ=0.475 (val F1=0.2247)
  Directional -> Accuracy: 0.4468, MCC: 0.0497, F1: 0.3158

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.62836 | val 1.78676
  Epoch 011 - train 0.57304 | val 1.76901
  Classification -> best τ=0.510 (val F1=0.3356)
  Directional -> Accuracy: 0.6462, MCC: 0.2919, F1: 0.6567

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.65630 | val 0.68415
  Epoch 012 - train 0.60904 | val 0.67758
  Classification -> best τ=0.595 (val F1=0.3833)
  Directional -> Accuracy: 0.5614, MCC: 0.0500, F1: 0.6914

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.65178 | val 0.69266
  Epoch 012 - train 0.59611 | val 0.82749
  Classification -> best τ=0.560 (val F1=0.1985)
  Directional -> Accuracy: 0.5231, MCC: 0.0000, F1: 0.0000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.56460 | val 1.38681
  Epoch 012 - train 0.54541 | val 1.25480
  Classification -> best τ=0.430 (val F1=0.4688)
  Directional -> Accuracy: 0.6000, MCC: 0.2476, F1: 0.5417

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.49708 | val 1.23040
  Epoch 011 - train 0.48648 | val 1.33652
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.5938

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.61973 | val 0.71165
  Epoch 013 - train 0.54006 | val 0.73830
  Classification -> best τ=0.510 (val F1=0.0700)
  Directional -> Accuracy: 0.4762, MCC: -0.1750, F1: 0.6207

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.61861 | val 1.42683
  Epoch 011 - train 0.49454 | val 1.78308
  Classification -> best τ=0.410 (val F1=0.1677)
  Directional -> Accuracy: 0.5179, MCC: 0.2491, F1: 0.2286

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.52522 | val 1.55265
  Epoch 011 - train 0.57717 | val 1.57903
  Classification -> best τ=0.495 (val F1=0.2774)
  Directional -> Accuracy: 0.4250, MCC: -0.1985, F1: 0.5306

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.58241 | val 0.76325
  Epoch 011 - train 0.57323 | val 0.86343
  Classification -> best τ=0.525 (val F1=0.2814)
  Directional -> Accuracy: 0.5714, MCC: 0.1409, F1: 0.5500

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.58977 | val 0.93743
  Epoch 012 - train 0.57096 | val 1.00921
  Classification -> best τ=0.545 (val F1=0.1425)
  Directional -> Accuracy: 0.5000, MCC: -0.0588, F1: 0.6182

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.56881 | val 0.79185
  Epoch 011 - train 0.52151 | val 0.86114
  Classification -> best τ=0.540 (val F1=0.2686)
  Directional -> Accuracy: 0.5510, MCC: 0.1535, F1: 0.7027

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.63336 | val 0.68251
  Epoch 012 - train 0.58134 | val 0.78370
  Classification -> best τ=0.415 (val F1=0.2950)
  Directional -> Accuracy: 0.4583, MCC: 0.1061, F1: 0.0488

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.56025 | val 1.44196
  Epoch 011 - train 0.55278 | val 1.39293
  Classification -> best τ=0.645 (val F1=0.2603)
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.62855 | val 1.00380
  Epoch 013 - train 0.59817 | val 1.17840
  Classification -> best τ=0.270 (val F1=0.2114)
  Directional -> Accuracy: 0.4242, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.54522 | val 1.10407
  Epoch 012 - train 0.53687 | val 0.80633
  Classification -> best τ=0.495 (val F1=0.3260)
  Directional -> Accuracy: 0.6429, MCC: 0.3511, F1: 0.5455

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.54575 | val 1.36925
  Epoch 012 - train 0.52191 | val 1.41811
  Classification -> best τ=0.450 (val F1=0.2450)
  Directional -> Accuracy: 0.4821, MCC: -0.0780, F1: 0.2927

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.52073 | val 0.84305
  Epoch 012 - train 0.39855 | val 1.08178
  Classification -> best τ=0.300 (val F1=0.2118)
  Directional -> Accuracy: 0.6087, MCC: 0.0000, F1: 0.7568

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.58338 | val 0.85903
  Epoch 012 - train 0.55668 | val 0.79716
  Classification -> best τ=0.715 (val F1=0.4710)
  Directional -> Accuracy: 0.3333, MCC: -0.1687, F1: 0.4839

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.58522 | val 1.22651
  Epoch 011 - train 0.59244 | val 1.47699
  Classification -> best τ=0.210 (val F1=0.2202)
  Directional -> Accuracy: 0.4865, MCC: 0.0000, F1: 0.6545

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.62502 | val 0.74324
  Epoch 012 - train 0.54841 | val 0.85596
  Classification -> best τ=0.430 (val F1=0.3750)
  Directional -> Accuracy: 0.5556, MCC: 0.2205, F1: 0.6970

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.49065 | val 1.48224
  Epoch 011 - train 0.46428 | val 1.57229
  Classification -> best τ=0.515 (val F1=0.2677)
  Directional -> Accuracy: 0.5952, MCC: 0.1334, F1: 0.7302

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.48672 | val 0.88676
  Epoch 011 - train 0.53758 | val 0.76420
  Classification -> best τ=0.415 (val F1=0.0889)
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.5455

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.63520 | val 1.15113
  Epoch 011 - train 0.61958 | val 0.92920
  Classification -> best τ=0.575 (val F1=0.2036)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.52507 | val 1.32698
  Epoch 011 - train 0.49392 | val 1.79873
  Classification -> best τ=0.640 (val F1=0.3455)
  Directional -> Accuracy: 0.5000, MCC: -0.0039, F1: 0.4615

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.65127 | val 0.85662
  Epoch 013 - train 0.59181 | val 0.75635
  Classification -> best τ=0.655 (val F1=0.2155)
  Directional -> Accuracy: 0.5849, MCC: 0.1976, F1: 0.4762

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.60722 | val 2.44967
  Epoch 011 - train 0.56096 | val 2.50306
  Classification -> best τ=0.430 (val F1=0.1154)
  Directional -> Accuracy: 0.5273, MCC: 0.0000, F1: 0.6905

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.62321 | val 0.70421

[I 2026-02-22 16:34:20,419] Trial 250 finished with value: 0.2539136910875762 and parameters: {'feature_set': 'sector', 'model_type': 'BiGRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.4, 'batch_size': 16, 'learning_rate': 0.008763397473114722, 'weight_decay': 0.0002290338364333177, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 1.0287779230609009, 'early_stopping_min_delta': 0.0023074437649637405}. Best is trial 214 with value: 0.2991200218486954.

  Epoch 016 - train 0.59731 | val 0.80253
  Classification -> best τ=0.360 (val F1=0.3178)
  Directional -> Accuracy: 0.5833, MCC: 0.1710, F1: 0.4444

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2539136910875762
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.63406 | val 1.28959
  Epoch 012 - train 0.61226 | val 1.17474
  Classification -> best τ=0.860 (val F1=0.2082)
  Directional -> Accuracy: 0.5921, MCC: 0.1586, F1: 0.4746

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.58100 | val 0.79375
  Epoch 020 - train 0.55105 | val 0.90621
  Epoch 021 - train 0.46909 | val 0.91061
  Classification -> best τ=0.740 (val F1=0.1764)
  Directional -> Accuracy: 0.6444, MCC: 0.2493, F1: 0.7241

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.60116 | val 0.99334
  Epoch 011 - train 0.59272 | val 0.95602
  Classification -> best τ=0.570 (val F1=0.4178)
  Directional -> Accuracy: 0.4565, MCC: -0.0807, F1: 0.4186

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.66050 | val 0.96765
  Epoch 011 - train 0.62266 | val 0.97602
  Classification -> best τ=0.600 (val F1=0.1849)
  Directional -> Accuracy: 0.4595, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.53078 | val 0.80428
  Epoch 012 - train 0.49995 | val 0.97657
  Classification -> best τ=0.475 (val F1=0.5079)
  Directional -> Accuracy: 0.6400, MCC: 0.3036, F1: 0.5909

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.62076 | val 0.88728
  Epoch 014 - train 0.48109 | val 1.15242
  Classification -> best τ=0.710 (val F1=0.3963)
  Directional -> Accuracy: 0.5217, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.65968 | val 0.90813
  Epoch 020 - train 0.65988 | val 1.20057
  Epoch 023 - train 0.59667 | val 1.26436
  Classification -> best τ=0.290 (val F1=0.2755)
  Directional -> Accuracy: 0.4265, MCC: -0.1503, F1: 0.3607

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.53071 | val 1.15407
  Epoch 017 - train 0.50652 | val 1.87985
  Classification -> best τ=0.215 (val F1=0.4971)
  Directional -> Accuracy: 0.5952, MCC: 0.1340, F1: 0.3704

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.60557 | val 1.83672
  Epoch 011 - train 0.59376 | val 1.83849
  Classification -> best τ=0.565 (val F1=0.2443)
  Directional -> Accuracy: 0.6042, MCC: 0.2343, F1: 0.6122

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.62605 | val 0.74310
  Epoch 020 - train 0.56684 | val 0.82735
  Epoch 022 - train 0.49123 | val 0.90039
  Classification -> best τ=0.605 (val F1=0.2821)
  Directional -> Accuracy: 0.5362, MCC: 0.1415, F1: 0.5789

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.66009 | val 1.00644
  Epoch 011 - train 0.61822 | val 0.89897
  Classification -> best τ=0.565 (val F1=0.3231)
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.62626 | val 0.94670
  Epoch 011 - train 0.57196 | val 0.79285
  Classification -> best τ=0.545 (val F1=0.1198)
  Directional -> Accuracy: 0.6316, MCC: 0.3198, F1: 0.7200

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.48679 | val 1.31973
  Epoch 011 - train 0.44318 | val 1.06385
  Classification -> best τ=0.555 (val F1=0.2902)
  Directional -> Accuracy: 0.4286, MCC: -0.1946, F1: 0.2500

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.63247 | val 0.71853
  Epoch 012 - train 0.61590 | val 0.76453
  Classification -> best τ=0.385 (val F1=0.4346)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.64982 | val 0.70645
  Epoch 014 - train 0.56365 | val 0.84416
  Classification -> best τ=0.585 (val F1=0.2720)
  Directional -> Accuracy: 0.5490, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.64078 | val 0.87092
  Epoch 011 - train 0.60042 | val 1.19836
  Classification -> best τ=0.350 (val F1=0.2795)
  Directional -> Accuracy: 0.5652, MCC: 0.1858, F1: 0.7115

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.61955 | val 1.10670
  Epoch 014 - train 0.59197 | val 1.41694
  Classification -> best τ=0.510 (val F1=0.3310)
  Directional -> Accuracy: 0.3793, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.62982 | val 0.73002
  Epoch 011 - train 0.62145 | val 0.73916
  Classification -> best τ=0.550 (val F1=0.1909)
  Directional -> Accuracy: 0.4133, MCC: 0.0949, F1: 0.0435

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.62143 | val 1.17550
  Epoch 011 - train 0.59577 | val 1.25723
  Classification -> best τ=0.395 (val F1=0.3140)
  Directional -> Accuracy: 0.5000, MCC: -0.0464, F1: 0.5897

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.60293 | val 0.89343
  Epoch 019 - train 0.51172 | val 0.95832
  Classification -> best τ=0.225 (val F1=0.3513)
  Directional -> Accuracy: 0.4865, MCC: 0.0843, F1: 0.2400

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.61429 | val 0.91195
  Epoch 014 - train 0.55450 | val 1.20158
  Classification -> best τ=0.515 (val F1=0.2309)
  Directional -> Accuracy: 0.4043, MCC: 0.1162, F1: 0.0667

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.65893 | val 1.30779
  Epoch 012 - train 0.64254 | val 0.84413
  Classification -> best τ=0.505 (val F1=0.2722)
  Directional -> Accuracy: 0.5385, MCC: 0.1077, F1: 0.3478

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.66738 | val 0.69284
  Epoch 020 - train 0.65478 | val 0.70566
  Epoch 022 - train 0.63155 | val 0.84380
  Classification -> best τ=0.590 (val F1=0.3781)
  Directional -> Accuracy: 0.5614, MCC: 0.0910, F1: 0.6377

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.67557 | val 0.73092
  Epoch 017 - train 0.60095 | val 0.83011
  Classification -> best τ=0.775 (val F1=0.1985)
  Directional -> Accuracy: 0.5231, MCC: 0.0000, F1: 0.0000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.62927 | val 0.76637
  Epoch 011 - train 0.57880 | val 0.76998
  Classification -> best τ=0.455 (val F1=0.4903)
  Directional -> Accuracy: 0.5636, MCC: 0.1047, F1: 0.6364

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.55409 | val 1.80369
  Epoch 011 - train 0.50019 | val 1.79841
  Classification -> best τ=0.640 (val F1=0.3764)
  Directional -> Accuracy: 0.5111, MCC: 0.2029, F1: 0.6207

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.64766 | val 0.94220
  Epoch 011 - train 0.61786 | val 0.90969
  Classification -> best τ=0.555 (val F1=0.1353)
  Directional -> Accuracy: 0.4048, MCC: -0.1273, F1: 0.1379

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.58735 | val 2.90358
  Epoch 012 - train 0.58737 | val 1.56797
  Classification -> best τ=0.515 (val F1=0.2816)
  Directional -> Accuracy: 0.4464, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.58605 | val 3.16056
  Epoch 012 - train 0.52176 | val 3.86931
  Classification -> best τ=0.615 (val F1=0.2414)
  Directional -> Accuracy: 0.5750, MCC: 0.1240, F1: 0.7119

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.62681 | val 0.82813
  Epoch 017 - train 0.51155 | val 0.93532
  Classification -> best τ=0.375 (val F1=0.3689)
  Directional -> Accuracy: 0.4762, MCC: -0.0455, F1: 0.4762

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.67119 | val 0.69102
  Epoch 019 - train 0.55447 | val 0.95784
  Classification -> best τ=0.630 (val F1=0.1324)
  Directional -> Accuracy: 0.4762, MCC: 0.0387, F1: 0.2143

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.49620 | val 1.88346
  Epoch 013 - train 0.45635 | val 1.44146
  Classification -> best τ=0.325 (val F1=0.3833)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.61020 | val 0.83750
  Epoch 013 - train 0.59722 | val 0.89530
  Classification -> best τ=0.260 (val F1=0.4460)
  Directional -> Accuracy: 0.5278, MCC: 0.1419, F1: 0.3929

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.61525 | val 0.91034
  Epoch 012 - train 0.56714 | val 1.13630
  Classification -> best τ=0.355 (val F1=0.1309)
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.62158 | val 0.97343
  Epoch 012 - train 0.59994 | val 1.68692
  Classification -> best τ=0.390 (val F1=0.3218)
  Directional -> Accuracy: 0.4697, MCC: 0.1873, F1: 0.1463

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.51420 | val 0.83770
  Epoch 014 - train 0.41668 | val 2.84340
  Classification -> best τ=0.530 (val F1=0.4356)
  Directional -> Accuracy: 0.6429, MCC: 0.3290, F1: 0.5714

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.58059 | val 1.26482
  Epoch 011 - train 0.56752 | val 1.29576
  Classification -> best τ=0.315 (val F1=0.2315)
  Directional -> Accuracy: 0.5357, MCC: 0.2067, F1: 0.6579

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.52339 | val 2.14444
  Epoch 012 - train 0.49911 | val 1.18073
  Classification -> best τ=0.315 (val F1=0.3105)
  Directional -> Accuracy: 0.6087, MCC: 0.0000, F1: 0.7568

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.60445 | val 1.21531
  Epoch 017 - train 0.46469 | val 1.07177
  Classification -> best τ=0.410 (val F1=0.4011)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.59991 | val 0.82458
  Epoch 011 - train 0.55314 | val 0.91657
  Classification -> best τ=0.340 (val F1=0.3776)
  Directional -> Accuracy: 0.4865, MCC: 0.0000, F1: 0.6545

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.61572 | val 1.04007
  Epoch 012 - train 0.59950 | val 1.07466
  Classification -> best τ=0.475 (val F1=0.4625)
  Directional -> Accuracy: 0.5111, MCC: 0.0000, F1: 0.6765

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.47695 | val 1.74878
  Epoch 011 - train 0.46957 | val 1.67933
  Classification -> best τ=0.520 (val F1=0.3563)
  Directional -> Accuracy: 0.6905, MCC: 0.3596, F1: 0.7636

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.49738 | val 0.84172
  Epoch 011 - train 0.52504 | val 0.95617
  Classification -> best τ=0.450 (val F1=0.2605)
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.5455

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.65665 | val 1.13435
  Epoch 012 - train 0.64000 | val 1.40126
  Classification -> best τ=0.525 (val F1=0.2085)
  Directional -> Accuracy: 0.4909, MCC: 0.1150, F1: 0.1765

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.57428 | val 2.23930
  Epoch 011 - train 0.52523 | val 2.76109
  Classification -> best τ=0.640 (val F1=0.4367)
  Directional -> Accuracy: 0.4821, MCC: -0.0146, F1: 0.6133

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.66582 | val 0.73456
  Epoch 013 - train 0.65169 | val 0.74264
  Classification -> best τ=0.555 (val F1=0.2570)
  Directional -> Accuracy: 0.5849, MCC: 0.1691, F1: 0.6207

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.53170 | val 1.86579
  Epoch 011 - train 0.52295 | val 1.97124
  Classification -> best τ=0.770 (val F1=0.2661)
  Directional -> Accuracy: 0.4727, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.67620 | val 0.89040

[I 2026-02-22 16:38:20,087] Trial 251 finished with value: 0.30686774032207087 and parameters: {'feature_set': 'sector', 'model_type': 'BiGRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.5, 'batch_size': 16, 'learning_rate': 0.009765106654291046, 'weight_decay': 0.00044124105881465647, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 0.9990471773036554, 'early_stopping_min_delta': 0.0012936020917655464}. Best is trial 251 with value: 0.30686774032207087.

  Epoch 016 - train 0.63352 | val 0.68551
  Classification -> best τ=0.445 (val F1=0.2407)
  Directional -> Accuracy: 0.5667, MCC: 0.2372, F1: 0.1875

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.30686774032207087
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.65931 | val 0.82466
  Epoch 016 - train 0.61671 | val 0.81730
  Classification -> best τ=0.905 (val F1=0.1713)
  Directional -> Accuracy: 0.5789, MCC: 0.1259, F1: 0.4286

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.56853 | val 0.77074
  Epoch 018 - train 0.53919 | val 0.84884
  Classification -> best τ=0.655 (val F1=0.2523)
  Directional -> Accuracy: 0.5556, MCC: 0.1857, F1: 0.5000

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.59875 | val 0.89498
  Epoch 011 - train 0.59253 | val 1.11181
  Classification -> best τ=0.585 (val F1=0.3114)
  Directional -> Accuracy: 0.4783, MCC: -0.0093, F1: 0.0769

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.64949 | val 0.74881
  Epoch 011 - train 0.63683 | val 0.77193
  Classification -> best τ=0.435 (val F1=0.2902)
  Directional -> Accuracy: 0.5000, MCC: 0.1895, F1: 0.1395

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.53539 | val 1.92273
  Epoch 015 - train 0.48597 | val 2.04091
  Classification -> best τ=0.495 (val F1=0.4782)
  Directional -> Accuracy: 0.6800, MCC: 0.3622, F1: 0.6800

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.55055 | val 0.73346
  Epoch 020 - train 0.52966 | val 1.40374
  Epoch 021 - train 0.42477 | val 1.65187
  Classification -> best τ=0.395 (val F1=0.3855)
  Directional -> Accuracy: 0.5217, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.65959 | val 0.82949
  Epoch 017 - train 0.62388 | val 0.90422
  Classification -> best τ=0.435 (val F1=0.3633)
  Directional -> Accuracy: 0.5147, MCC: 0.0425, F1: 0.4762

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.47643 | val 0.60263
  Epoch 019 - train 0.44224 | val 1.04397
  Classification -> best τ=0.145 (val F1=0.4453)
  Directional -> Accuracy: 0.4762, MCC: -0.0550, F1: 0.4211

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.58759 | val 1.21149
  Epoch 011 - train 0.58987 | val 1.58344
  Classification -> best τ=0.420 (val F1=0.2233)
  Directional -> Accuracy: 0.5833, MCC: 0.1143, F1: 0.3333

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.60667 | val 1.07608
  Epoch 011 - train 0.57733 | val 1.12274
  Classification -> best τ=0.440 (val F1=0.2951)
  Directional -> Accuracy: 0.4203, MCC: -0.0959, F1: 0.5000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.63142 | val 0.96751
  Epoch 020 - train 0.54080 | val 0.75518
  Epoch 024 - train 0.45107 | val 0.71766
  Classification -> best τ=0.565 (val F1=0.3075)
  Directional -> Accuracy: 0.5918, MCC: 0.2285, F1: 0.1667

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.64917 | val 0.77618
  Epoch 014 - train 0.62451 | val 1.37631
  Classification -> best τ=0.735 (val F1=0.2083)
  Directional -> Accuracy: 0.5439, MCC: 0.1159, F1: 0.3810

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.52668 | val 1.03745
  Epoch 014 - train 0.49614 | val 0.86853
  Classification -> best τ=0.535 (val F1=0.3942)
  Directional -> Accuracy: 0.3333, MCC: -0.3349, F1: 0.3000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.64696 | val 0.66614
  Epoch 015 - train 0.58857 | val 0.69259
  Classification -> best τ=0.355 (val F1=0.3774)
  Directional -> Accuracy: 0.4667, MCC: -0.0754, F1: 0.3043

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.60650 | val 0.72214
  Epoch 011 - train 0.60935 | val 0.90745
  Classification -> best τ=0.470 (val F1=0.0921)
  Directional -> Accuracy: 0.5490, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.65956 | val 0.85139
  Epoch 011 - train 0.62422 | val 1.16338
  Classification -> best τ=0.475 (val F1=0.2155)
  Directional -> Accuracy: 0.5942, MCC: 0.1812, F1: 0.6957

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.63602 | val 0.96340
  Epoch 012 - train 0.64402 | val 0.78364
  Classification -> best τ=0.625 (val F1=0.3148)
  Directional -> Accuracy: 0.3793, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.64389 | val 0.68176
  Epoch 020 - train 0.42344 | val 1.08342
  Classification -> best τ=0.630 (val F1=0.2220)
  Directional -> Accuracy: 0.4000, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.63222 | val 1.33880
  Epoch 011 - train 0.61098 | val 1.33259
  Classification -> best τ=0.380 (val F1=0.2803)
  Directional -> Accuracy: 0.6094, MCC: 0.1716, F1: 0.7423

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.58287 | val 1.09464
  Epoch 011 - train 0.55637 | val 1.18845
  Classification -> best τ=0.430 (val F1=0.2771)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.62902 | val 1.49421
  Epoch 014 - train 0.53940 | val 0.90194
  Classification -> best τ=0.505 (val F1=0.3458)
  Directional -> Accuracy: 0.4468, MCC: 0.0837, F1: 0.2778

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.64380 | val 0.87772
  Epoch 011 - train 0.61224 | val 0.88396
  Classification -> best τ=0.470 (val F1=0.2612)
  Directional -> Accuracy: 0.4923, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.66270 | val 0.84534
  Epoch 015 - train 0.62199 | val 0.84998
  Classification -> best τ=0.565 (val F1=0.4472)
  Directional -> Accuracy: 0.5789, MCC: 0.1528, F1: 0.6129

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.65248 | val 0.80643
  Epoch 013 - train 0.61321 | val 0.72904
  Classification -> best τ=0.435 (val F1=0.2177)
  Directional -> Accuracy: 0.5077, MCC: 0.0105, F1: 0.4667

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.56010 | val 0.86971
  Epoch 018 - train 0.55076 | val 1.47059
  Classification -> best τ=0.425 (val F1=0.4307)
  Directional -> Accuracy: 0.5818, MCC: 0.1913, F1: 0.5490

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.56405 | val 1.11459
  Epoch 011 - train 0.52081 | val 1.16982
  Classification -> best τ=0.630 (val F1=0.3669)
  Directional -> Accuracy: 0.4444, MCC: -0.0636, F1: 0.4898

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.65757 | val 0.71168
  Epoch 019 - train 0.57366 | val 0.86636
  Classification -> best τ=0.660 (val F1=0.4201)
  Directional -> Accuracy: 0.5952, MCC: 0.1925, F1: 0.6222

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.58852 | val 0.75427
  Epoch 011 - train 0.56242 | val 0.80003
  Classification -> best τ=0.325 (val F1=0.3563)
  Directional -> Accuracy: 0.4643, MCC: 0.1211, F1: 0.0625

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.47390 | val 0.86768
  Epoch 011 - train 0.51187 | val 0.83512
  Classification -> best τ=0.475 (val F1=0.1183)
  Directional -> Accuracy: 0.5500, MCC: 0.1005, F1: 0.5714

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.59832 | val 1.15311
  Epoch 017 - train 0.47042 | val 1.19551
  Classification -> best τ=0.470 (val F1=0.3501)
  Directional -> Accuracy: 0.5476, MCC: 0.1137, F1: 0.5957

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.63810 | val 1.14850
  Epoch 017 - train 0.54117 | val 0.88410
  Classification -> best τ=0.550 (val F1=0.1788)
  Directional -> Accuracy: 0.4524, MCC: -0.0829, F1: 0.4390

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.56943 | val 1.20891
  Epoch 011 - train 0.53910 | val 1.14289
  Classification -> best τ=0.660 (val F1=0.2969)
  Directional -> Accuracy: 0.5102, MCC: 0.0018, F1: 0.5862

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.60389 | val 0.75401
  Epoch 020 - train 0.52405 | val 0.77106
  Epoch 023 - train 0.46664 | val 0.78403
  Classification -> best τ=0.570 (val F1=0.3630)
  Directional -> Accuracy: 0.5000, MCC: 0.1000, F1: 0.3077

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.62151 | val 1.14685
  Epoch 012 - train 0.54668 | val 1.35870
  Classification -> best τ=0.405 (val F1=0.0696)
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.61363 | val 0.81319
  Epoch 013 - train 0.60634 | val 1.02342
  Classification -> best τ=0.265 (val F1=0.3280)
  Directional -> Accuracy: 0.5455, MCC: 0.2457, F1: 0.4000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.48544 | val 2.30995
  Epoch 011 - train 0.51808 | val 3.25527
  Classification -> best τ=0.460 (val F1=0.2439)
  Directional -> Accuracy: 0.6190, MCC: 0.2697, F1: 0.5556

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.57511 | val 0.77783
  Epoch 011 - train 0.56034 | val 0.76282
  Classification -> best τ=0.375 (val F1=0.2114)
  Directional -> Accuracy: 0.5893, MCC: 0.2034, F1: 0.6230

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.57421 | val 1.59860
  Epoch 014 - train 0.48525 | val 2.15154
  Classification -> best τ=0.400 (val F1=0.3677)
  Directional -> Accuracy: 0.6087, MCC: 0.0000, F1: 0.7568

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.58970 | val 0.76807
  Epoch 016 - train 0.59852 | val 1.00988
  Classification -> best τ=0.560 (val F1=0.3800)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.63186 | val 0.79842
  Epoch 011 - train 0.60585 | val 0.89685
  Classification -> best τ=0.250 (val F1=0.3533)
  Directional -> Accuracy: 0.4865, MCC: -0.0065, F1: 0.6415

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.66158 | val 0.95223
  Epoch 011 - train 0.60425 | val 0.94336
  Classification -> best τ=0.525 (val F1=0.4914)
  Directional -> Accuracy: 0.5111, MCC: 0.0000, F1: 0.6765

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.56560 | val 1.28508
  Epoch 012 - train 0.42352 | val 1.42301
  Classification -> best τ=0.595 (val F1=0.4082)
  Directional -> Accuracy: 0.5952, MCC: 0.1803, F1: 0.7385

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.56552 | val 0.61710
  Epoch 020 - train 0.60621 | val 0.81604
  Epoch 030 - train 0.44933 | val 0.67453
  Classification -> best τ=0.315 (val F1=0.5514)
  Directional -> Accuracy: 0.3958, MCC: 0.0222, F1: 0.5397

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.67546 | val 0.91939
  Epoch 012 - train 0.64812 | val 0.97420
  Classification -> best τ=0.430 (val F1=0.2833)
  Directional -> Accuracy: 0.4364, MCC: -0.1981, F1: 0.5634

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.59692 | val 1.73258
  Epoch 011 - train 0.54342 | val 1.97084
  Classification -> best τ=0.605 (val F1=0.4918)
  Directional -> Accuracy: 0.5714, MCC: 0.2072, F1: 0.6667

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.68805 | val 0.70800
  Epoch 012 - train 0.62957 | val 0.68855
  Classification -> best τ=0.645 (val F1=0.2423)
  Directional -> Accuracy: 0.5849, MCC: 0.1695, F1: 0.5926

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.55122 | val 2.30101
  Epoch 011 - train 0.54697 | val 2.88755
  Classification -> best τ=0.625 (val F1=0.1154)
  Directional -> Accuracy: 0.5273, MCC: 0.0000, F1: 0.6905

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.63369 | val 1.12012

[I 2026-02-22 16:42:27,412] Trial 252 finished with value: 0.3108162738957727 and parameters: {'feature_set': 'sector', 'model_type': 'BiGRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.5, 'batch_size': 16, 'learning_rate': 0.009998241846210619, 'weight_decay': 0.000404807118998449, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 1.0446688741401795, 'early_stopping_min_delta': 0.0013121186629166605}. Best is trial 252 with value: 0.3108162738957727.

  Epoch 011 - train 0.63383 | val 1.39707
  Classification -> best τ=0.405 (val F1=0.3234)
  Directional -> Accuracy: 0.5667, MCC: 0.1346, F1: 0.5667

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.3108162738957727
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.64453 | val 0.84880
  Epoch 012 - train 0.65206 | val 0.91193
  Classification -> best τ=0.840 (val F1=0.2510)
  Directional -> Accuracy: 0.5526, MCC: 0.0363, F1: 0.1905

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.52744 | val 0.85861
  Epoch 011 - train 0.52476 | val 0.90723
  Classification -> best τ=0.355 (val F1=0.1844)
  Directional -> Accuracy: 0.5778, MCC: 0.0000, F1: 0.7324

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.58401 | val 0.97521
  Epoch 011 - train 0.55517 | val 1.28173
  Classification -> best τ=0.475 (val F1=0.2275)
  Directional -> Accuracy: 0.6739, MCC: 0.3482, F1: 0.6809

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.60294 | val 0.93182
  Epoch 011 - train 0.60008 | val 0.95580
  Classification -> best τ=0.485 (val F1=0.1537)
  Directional -> Accuracy: 0.4865, MCC: 0.0016, F1: 0.4062

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.59654 | val 1.27939
  Epoch 011 - train 0.52041 | val 1.22238
  Classification -> best τ=0.645 (val F1=0.4259)
  Directional -> Accuracy: 0.6600, MCC: 0.3309, F1: 0.6383

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.56283 | val 0.72016
  Epoch 020 - train 0.41690 | val 1.23275
  Epoch 024 - train 0.35980 | val 0.71925
  Classification -> best τ=0.660 (val F1=0.4513)
  Directional -> Accuracy: 0.5217, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.63470 | val 0.78437
  Epoch 011 - train 0.58762 | val 0.86373
  Classification -> best τ=0.445 (val F1=0.2648)
  Directional -> Accuracy: 0.5441, MCC: 0.0659, F1: 0.4561

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.50664 | val 0.61343
  Epoch 018 - train 0.36625 | val 2.01963
  Classification -> best τ=0.335 (val F1=0.4215)
  Directional -> Accuracy: 0.5000, MCC: 0.0595, F1: 0.5532

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.59916 | val 1.01155
  Epoch 012 - train 0.54288 | val 1.26413
  Classification -> best τ=0.350 (val F1=0.2010)
  Directional -> Accuracy: 0.4375, MCC: 0.0000, F1: 0.6087

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.58951 | val 0.75907
  Epoch 018 - train 0.51618 | val 1.00218
  Classification -> best τ=0.525 (val F1=0.2964)
  Directional -> Accuracy: 0.5217, MCC: 0.2104, F1: 0.6207

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.64144 | val 0.67604
  Epoch 017 - train 0.53750 | val 0.90270
  Classification -> best τ=0.530 (val F1=0.3729)
  Directional -> Accuracy: 0.5918, MCC: 0.1804, F1: 0.2308

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.61256 | val 0.89578
  Epoch 011 - train 0.60735 | val 0.81687
  Classification -> best τ=0.625 (val F1=0.0500)
  Directional -> Accuracy: 0.5088, MCC: 0.0566, F1: 0.1765

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.52354 | val 1.86496
  Epoch 015 - train 0.43965 | val 1.40518
  Classification -> best τ=0.645 (val F1=0.1370)
  Directional -> Accuracy: 0.5238, MCC: -0.1419, F1: 0.0000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.63132 | val 0.84423
  Epoch 012 - train 0.60033 | val 0.71684
  Classification -> best τ=0.375 (val F1=0.4213)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.58024 | val 0.74939
  Epoch 014 - train 0.53235 | val 0.98140
  Classification -> best τ=0.490 (val F1=0.2571)
  Directional -> Accuracy: 0.5490, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.61184 | val 1.11523
  Epoch 012 - train 0.57286 | val 1.42288
  Classification -> best τ=0.770 (val F1=0.2904)
  Directional -> Accuracy: 0.4928, MCC: 0.0526, F1: 0.2553

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.58763 | val 0.71893
  Epoch 012 - train 0.55869 | val 0.81348
  Classification -> best τ=0.400 (val F1=0.2824)
  Directional -> Accuracy: 0.6552, MCC: 0.2079, F1: 0.7778

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.61743 | val 0.84361
  Epoch 011 - train 0.55253 | val 0.96436
  Classification -> best τ=0.690 (val F1=0.2220)
  Directional -> Accuracy: 0.4000, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.60910 | val 1.06461
  Epoch 011 - train 0.57599 | val 1.03226
  Classification -> best τ=0.675 (val F1=0.3238)
  Directional -> Accuracy: 0.4219, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.58276 | val 1.01218
  Epoch 011 - train 0.55426 | val 1.09123
  Classification -> best τ=0.320 (val F1=0.2881)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.57641 | val 1.22081
  Epoch 012 - train 0.50852 | val 1.27214
  Classification -> best τ=0.570 (val F1=0.1979)
  Directional -> Accuracy: 0.4681, MCC: 0.0346, F1: 0.4186

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.61549 | val 1.08258
  Epoch 011 - train 0.59086 | val 1.13641
  Classification -> best τ=0.610 (val F1=0.2520)
  Directional -> Accuracy: 0.4923, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.64676 | val 0.74004
  Epoch 011 - train 0.60537 | val 0.67000
  Classification -> best τ=0.565 (val F1=0.4032)
  Directional -> Accuracy: 0.6491, MCC: 0.2747, F1: 0.7297

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.59785 | val 0.85755
  Epoch 012 - train 0.52239 | val 1.44190
  Classification -> best τ=0.550 (val F1=0.1010)
  Directional -> Accuracy: 0.4462, MCC: -0.1101, F1: 0.4194

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.59344 | val 0.72587
  Epoch 019 - train 0.45491 | val 1.53337
  Classification -> best τ=0.540 (val F1=0.4199)
  Directional -> Accuracy: 0.4727, MCC: -0.0342, F1: 0.4314

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.49917 | val 2.03237
  Epoch 011 - train 0.48301 | val 2.27780
  Classification -> best τ=0.515 (val F1=0.3669)
  Directional -> Accuracy: 0.4667, MCC: 0.1844, F1: 0.6129

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.55227 | val 0.86120
  Epoch 012 - train 0.56931 | val 0.73935
  Classification -> best τ=0.565 (val F1=0.0829)
  Directional -> Accuracy: 0.5000, MCC: 0.0430, F1: 0.4615

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.59044 | val 0.87081
  Epoch 012 - train 0.58079 | val 0.94055
  Classification -> best τ=0.440 (val F1=0.3147)
  Directional -> Accuracy: 0.4464, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.49985 | val 1.97627
  Epoch 011 - train 0.49027 | val 2.08457
  Classification -> best τ=0.565 (val F1=0.1748)
  Directional -> Accuracy: 0.5750, MCC: 0.1124, F1: 0.6909

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.62665 | val 1.55361
  Epoch 014 - train 0.57555 | val 2.01056
  Classification -> best τ=0.495 (val F1=0.4067)
  Directional -> Accuracy: 0.5238, MCC: 0.1469, F1: 0.6552

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.59171 | val 0.96538
  Epoch 017 - train 0.46781 | val 0.91992
  Classification -> best τ=0.515 (val F1=0.2476)
  Directional -> Accuracy: 0.2857, MCC: -0.4262, F1: 0.1667

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.54023 | val 1.09798
  Epoch 011 - train 0.53821 | val 0.98648
  Classification -> best τ=0.360 (val F1=0.4255)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.59472 | val 1.10694
  Epoch 012 - train 0.56155 | val 0.81793
  Classification -> best τ=0.370 (val F1=0.3694)
  Directional -> Accuracy: 0.5000, MCC: 0.1685, F1: 0.2174

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.56938 | val 0.90394
  Epoch 011 - train 0.55117 | val 0.91102
  Classification -> best τ=0.665 (val F1=0.2603)
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.61017 | val 1.13023
  Epoch 012 - train 0.60117 | val 0.97192
  Classification -> best τ=0.715 (val F1=0.1279)
  Directional -> Accuracy: 0.4242, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.51680 | val 0.78969
  Epoch 012 - train 0.45977 | val 0.94095
  Classification -> best τ=0.550 (val F1=0.3260)
  Directional -> Accuracy: 0.5952, MCC: 0.2656, F1: 0.4516

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.55416 | val 0.98633
  Epoch 011 - train 0.51985 | val 1.05809
  Classification -> best τ=0.695 (val F1=0.2478)
  Directional -> Accuracy: 0.5893, MCC: 0.1641, F1: 0.4651

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.52050 | val 1.03717
  Epoch 011 - train 0.49803 | val 1.05903
  Classification -> best τ=0.540 (val F1=0.2185)
  Directional -> Accuracy: 0.3913, MCC: -0.0687, F1: 0.1250

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.55806 | val 0.84871
  Epoch 019 - train 0.54355 | val 1.06358
  Classification -> best τ=0.460 (val F1=0.3006)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.62272 | val 1.23021
  Epoch 011 - train 0.55051 | val 1.38901
  Classification -> best τ=0.250 (val F1=0.3548)
  Directional -> Accuracy: 0.5000, MCC: 0.1139, F1: 0.6606

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.61110 | val 0.71954
  Epoch 016 - train 0.51170 | val 0.72011
  Classification -> best τ=0.545 (val F1=0.4632)
  Directional -> Accuracy: 0.5556, MCC: 0.2043, F1: 0.2857

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.48986 | val 1.61420
  Epoch 011 - train 0.38111 | val 1.67873
  Classification -> best τ=0.690 (val F1=0.3612)
  Directional -> Accuracy: 0.4524, MCC: -0.0446, F1: 0.3784

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.57482 | val 0.64249
  Epoch 019 - train 0.35545 | val 0.87982
  Classification -> best τ=0.495 (val F1=0.5249)
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.5455

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.60859 | val 0.99578
  Epoch 011 - train 0.63987 | val 0.86617
  Classification -> best τ=0.735 (val F1=0.2036)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.54203 | val 1.92722
  Epoch 011 - train 0.52347 | val 1.86661
  Classification -> best τ=0.770 (val F1=0.4174)
  Directional -> Accuracy: 0.4464, MCC: -0.1167, F1: 0.5867

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.66229 | val 0.80107
  Epoch 014 - train 0.61064 | val 0.98232
  Classification -> best τ=0.795 (val F1=0.2064)
  Directional -> Accuracy: 0.6038, MCC: 0.2103, F1: 0.5882

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.56699 | val 2.14318
  Epoch 011 - train 0.54751 | val 2.27718
  Classification -> best τ=0.695 (val F1=0.0817)
  Directional -> Accuracy: 0.5273, MCC: 0.1430, F1: 0.2778

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.65375 | val 0.81083

[I 2026-02-22 16:46:11,366] Trial 253 finished with value: 0.2831648368925841 and parameters: {'feature_set': 'sector', 'model_type': 'BiGRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.4, 'batch_size': 16, 'learning_rate': 0.006251498631113059, 'weight_decay': 0.00046452525680241183, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 0.14074093750030137, 'early_stopping_min_delta': 0.0012553529781817521}. Best is trial 252 with value: 0.3108162738957727.

  Epoch 014 - train 0.59977 | val 0.69165
  Classification -> best τ=0.605 (val F1=0.2124)
  Directional -> Accuracy: 0.5167, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2831648368925841
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.63079 | val 0.92221
  Epoch 011 - train 0.63550 | val 0.94195
  Classification -> best τ=0.805 (val F1=0.2510)
  Directional -> Accuracy: 0.5921, MCC: 0.1615, F1: 0.4918

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.64444 | val 3.16452
  Epoch 015 - train 0.51104 | val 1.20118
  Classification -> best τ=0.820 (val F1=0.1764)
  Directional -> Accuracy: 0.5778, MCC: 0.3149, F1: 0.4571

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.57674 | val 1.15933
  Epoch 011 - train 0.53602 | val 1.21629
  Classification -> best τ=0.610 (val F1=0.3114)
  Directional -> Accuracy: 0.5435, MCC: 0.1633, F1: 0.3226

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.65002 | val 0.71149
  Epoch 011 - train 0.61482 | val 0.70811
  Classification -> best τ=0.395 (val F1=0.2470)
  Directional -> Accuracy: 0.5135, MCC: -0.0378, F1: 0.6471

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.61930 | val 0.62656
  Epoch 018 - train 0.53675 | val 1.00719
  Classification -> best τ=0.625 (val F1=0.4556)
  Directional -> Accuracy: 0.6000, MCC: 0.2587, F1: 0.4737

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.54402 | val 1.00912
  Epoch 020 - train 0.48679 | val 0.82092
  Epoch 022 - train 0.38898 | val 0.84387
  Classification -> best τ=0.360 (val F1=0.4379)
  Directional -> Accuracy: 0.5217, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.61714 | val 0.79749
  Epoch 014 - train 0.60930 | val 0.78080
  Classification -> best τ=0.490 (val F1=0.2870)
  Directional -> Accuracy: 0.5588, MCC: 0.1021, F1: 0.4828

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.53831 | val 0.55429
  Epoch 016 - train 0.47193 | val 0.60466
  Classification -> best τ=0.295 (val F1=0.3974)
  Directional -> Accuracy: 0.5000, MCC: -0.0280, F1: 0.4000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.60086 | val 1.17081
  Epoch 012 - train 0.61250 | val 1.15242
  Classification -> best τ=0.475 (val F1=0.2497)
  Directional -> Accuracy: 0.4375, MCC: 0.0000, F1: 0.6087

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.59733 | val 0.92481
  Epoch 011 - train 0.57396 | val 0.99913
  Classification -> best τ=0.470 (val F1=0.1424)
  Directional -> Accuracy: 0.5217, MCC: 0.1165, F1: 0.5714

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.61276 | val 0.66816
  Epoch 019 - train 0.49807 | val 0.97795
  Classification -> best τ=0.475 (val F1=0.3075)
  Directional -> Accuracy: 0.5714, MCC: 0.1599, F1: 0.0870

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.62151 | val 0.99046
  Epoch 011 - train 0.59530 | val 1.67521
  Classification -> best τ=0.525 (val F1=0.2157)
  Directional -> Accuracy: 0.5088, MCC: 0.0000, F1: 0.6744

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.54414 | val 0.80843
  Epoch 011 - train 0.56658 | val 0.82987
  Classification -> best τ=0.515 (val F1=0.2176)
  Directional -> Accuracy: 0.5000, MCC: 0.1319, F1: 0.6316

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.64628 | val 0.82536
  Epoch 013 - train 0.61423 | val 0.66149
  Classification -> best τ=0.460 (val F1=0.3126)
  Directional -> Accuracy: 0.5333, MCC: 0.1857, F1: 0.1250

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.63887 | val 0.69670
  Epoch 011 - train 0.56214 | val 0.70184
  Classification -> best τ=0.525 (val F1=0.2078)
  Directional -> Accuracy: 0.5490, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.62118 | val 1.47933
  Epoch 012 - train 0.60913 | val 1.29166
  Classification -> best τ=0.670 (val F1=0.2722)
  Directional -> Accuracy: 0.5797, MCC: 0.3003, F1: 0.3830

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.61460 | val 0.91943
  Epoch 012 - train 0.62728 | val 1.06351
  Classification -> best τ=0.620 (val F1=0.2097)
  Directional -> Accuracy: 0.5345, MCC: 0.1064, F1: 0.5574

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.61349 | val 0.72155
  Epoch 017 - train 0.59170 | val 0.72051
  Classification -> best τ=0.620 (val F1=0.1909)
  Directional -> Accuracy: 0.4000, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.61938 | val 1.17060
  Epoch 011 - train 0.57777 | val 1.28173
  Classification -> best τ=0.390 (val F1=0.2306)
  Directional -> Accuracy: 0.5312, MCC: -0.0725, F1: 0.6739

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.61331 | val 0.80762
  Epoch 012 - train 0.54462 | val 1.06728
  Classification -> best τ=0.335 (val F1=0.2962)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.59519 | val 0.69469
  Epoch 011 - train 0.58018 | val 0.79653
  Classification -> best τ=0.490 (val F1=0.2064)
  Directional -> Accuracy: 0.5106, MCC: -0.0958, F1: 0.6349

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.63019 | val 1.17897
  Epoch 012 - train 0.60434 | val 1.17879
  Classification -> best τ=0.525 (val F1=0.1994)
  Directional -> Accuracy: 0.4923, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.66292 | val 0.68817
  Epoch 014 - train 0.62081 | val 0.64852
  Classification -> best τ=0.535 (val F1=0.3656)
  Directional -> Accuracy: 0.5614, MCC: 0.0000, F1: 0.7191

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.64017 | val 0.71278
  Epoch 020 - train 0.62193 | val 0.74866
  Epoch 021 - train 0.59930 | val 0.73500
  Classification -> best τ=0.575 (val F1=0.1985)
  Directional -> Accuracy: 0.5231, MCC: 0.0000, F1: 0.0000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.61471 | val 1.08546
  Epoch 015 - train 0.52062 | val 1.45468
  Classification -> best τ=0.185 (val F1=0.5197)
  Directional -> Accuracy: 0.5818, MCC: 0.1733, F1: 0.5818

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.51916 | val 2.15095
  Epoch 011 - train 0.49317 | val 2.14520
  Classification -> best τ=0.715 (val F1=0.2241)
  Directional -> Accuracy: 0.3778, MCC: -0.2314, F1: 0.3636

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.56897 | val 0.75430
  Epoch 012 - train 0.60672 | val 0.73244
  Classification -> best τ=0.675 (val F1=0.2810)
  Directional -> Accuracy: 0.5000, MCC: 0.1005, F1: 0.3636

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.60729 | val 1.00325
  Epoch 012 - train 0.52220 | val 2.27186
  Classification -> best τ=0.600 (val F1=0.3322)
  Directional -> Accuracy: 0.4464, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.53273 | val 0.81031
  Epoch 013 - train 0.49920 | val 1.16605
  Classification -> best τ=0.460 (val F1=0.3518)
  Directional -> Accuracy: 0.5750, MCC: 0.1240, F1: 0.7119

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.64073 | val 1.31862
  Epoch 011 - train 0.62805 | val 1.02550
  Classification -> best τ=0.610 (val F1=0.3501)
  Directional -> Accuracy: 0.5476, MCC: 0.0826, F1: 0.3871

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.67656 | val 0.87191
  Epoch 020 - train 0.55106 | val 1.10458
  Epoch 025 - train 0.52678 | val 1.89431
  Classification -> best τ=0.285 (val F1=0.3385)
  Directional -> Accuracy: 0.5714, MCC: 0.1194, F1: 0.7097

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.58446 | val 0.84969
  Epoch 011 - train 0.52817 | val 0.95744
  Classification -> best τ=0.465 (val F1=0.2342)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.63949 | val 0.71098
  Epoch 012 - train 0.56126 | val 0.75853
  Classification -> best τ=0.335 (val F1=0.4014)
  Directional -> Accuracy: 0.5139, MCC: 0.0916, F1: 0.4068

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.59303 | val 0.79217
  Epoch 014 - train 0.58039 | val 0.82187
  Classification -> best τ=0.625 (val F1=0.2603)
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.64840 | val 1.05837
  Epoch 011 - train 0.60076 | val 1.05405
  Classification -> best τ=0.185 (val F1=0.3603)
  Directional -> Accuracy: 0.5758, MCC: 0.0000, F1: 0.7308

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.43665 | val 0.80475
  Epoch 019 - train 0.39853 | val 0.94073
  Classification -> best τ=0.555 (val F1=0.3287)
  Directional -> Accuracy: 0.6667, MCC: 0.3303, F1: 0.6957

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.56503 | val 0.66093
  Epoch 020 - train 0.39112 | val 1.13799
  Classification -> best τ=0.545 (val F1=0.2478)
  Directional -> Accuracy: 0.5357, MCC: 0.0453, F1: 0.3810

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.49583 | val 1.34677
  Epoch 011 - train 0.50019 | val 1.42541
  Classification -> best τ=0.450 (val F1=0.1369)
  Directional -> Accuracy: 0.5435, MCC: 0.0321, F1: 0.6316

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.60060 | val 0.73484
  Epoch 020 - train 0.46626 | val 0.76784
  Epoch 022 - train 0.46019 | val 0.76551
  Classification -> best τ=0.665 (val F1=0.4710)
  Directional -> Accuracy: 0.4167, MCC: 0.1099, F1: 0.5333

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.60474 | val 0.93609
  Epoch 011 - train 0.55152 | val 1.00963
  Classification -> best τ=0.370 (val F1=0.3691)
  Directional -> Accuracy: 0.5405, MCC: 0.1647, F1: 0.6667

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.60865 | val 0.82435
  Epoch 011 - train 0.59706 | val 0.78011
  Classification -> best τ=0.510 (val F1=0.4472)
  Directional -> Accuracy: 0.5111, MCC: 0.0000, F1: 0.6765

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.49786 | val 1.34199
  Epoch 012 - train 0.44214 | val 1.04720
  Classification -> best τ=0.765 (val F1=0.3612)
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.0000

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.59913 | val 0.82379
  Epoch 011 - train 0.54880 | val 0.91742
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.5455

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.67399 | val 0.88876
  Epoch 014 - train 0.60401 | val 0.96671
  Classification -> best τ=0.725 (val F1=0.2036)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.53032 | val 2.32661
  Epoch 011 - train 0.56573 | val 2.33266
  Classification -> best τ=0.640 (val F1=0.3294)
  Directional -> Accuracy: 0.5000, MCC: 0.0405, F1: 0.6316

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.66459 | val 0.71298
  Epoch 015 - train 0.64142 | val 0.96471
  Classification -> best τ=0.525 (val F1=0.2801)
  Directional -> Accuracy: 0.6038, MCC: 0.2213, F1: 0.6769

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.62216 | val 1.07696
  Epoch 012 - train 0.56770 | val 1.71730
  Classification -> best τ=0.770 (val F1=0.0770)
  Directional -> Accuracy: 0.5636, MCC: 0.2052, F1: 0.7073

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.65454 | val 0.74595

[I 2026-02-22 16:50:09,923] Trial 254 finished with value: 0.2823881937022268 and parameters: {'feature_set': 'sector', 'model_type': 'BiGRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.5, 'batch_size': 16, 'learning_rate': 0.009835484042705053, 'weight_decay': 0.0003930933424237542, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 1.0484510924623516, 'early_stopping_min_delta': 0.0009376849865877629}. Best is trial 252 with value: 0.3108162738957727.

  Epoch 016 - train 0.61720 | val 1.01914
  Classification -> best τ=0.645 (val F1=0.2623)
  Directional -> Accuracy: 0.5167, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2823881937022268
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.61168 | val 0.87690
  Epoch 014 - train 0.62603 | val 0.67583
  Classification -> best τ=0.850 (val F1=0.2919)
  Directional -> Accuracy: 0.5526, MCC: 0.0000, F1: 0.0000

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.56600 | val 0.72255
  Epoch 011 - train 0.54914 | val 0.69850
  Classification -> best τ=0.605 (val F1=0.2523)
  Directional -> Accuracy: 0.5556, MCC: 0.2798, F1: 0.4118

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.61185 | val 0.92841
  Epoch 011 - train 0.57544 | val 1.08535
  Classification -> best τ=0.655 (val F1=0.3114)
  Directional -> Accuracy: 0.5652, MCC: 0.1724, F1: 0.4444

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.64686 | val 0.79442
  Epoch 011 - train 0.64722 | val 1.12918
  Classification -> best τ=0.530 (val F1=0.1537)
  Directional -> Accuracy: 0.4730, MCC: 0.0520, F1: 0.0930

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.63344 | val 0.83777
  Epoch 012 - train 0.51824 | val 0.75599
  Classification -> best τ=0.565 (val F1=0.4247)
  Directional -> Accuracy: 0.5800, MCC: 0.2203, F1: 0.4324

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.56310 | val 0.76340
  Epoch 011 - train 0.57772 | val 0.93407
  Classification -> best τ=0.510 (val F1=0.1537)
  Directional -> Accuracy: 0.5217, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.65914 | val 0.84526
  Epoch 013 - train 0.61902 | val 0.81792
  Classification -> best τ=0.375 (val F1=0.2463)
  Directional -> Accuracy: 0.5294, MCC: -0.0084, F1: 0.3600

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.59886 | val 0.65818
  Epoch 020 - train 0.48679 | val 1.22936
  Epoch 021 - train 0.44055 | val 1.16933
  Classification -> best τ=0.155 (val F1=0.4215)
  Directional -> Accuracy: 0.4762, MCC: 0.0525, F1: 0.5769

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.64083 | val 1.16973
  Epoch 011 - train 0.60334 | val 1.53072
  Classification -> best τ=0.515 (val F1=0.3047)
  Directional -> Accuracy: 0.6250, MCC: 0.2574, F1: 0.6087

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.65897 | val 0.72909
  Epoch 011 - train 0.62889 | val 0.92777
  Classification -> best τ=0.525 (val F1=0.2460)
  Directional -> Accuracy: 0.4928, MCC: 0.1099, F1: 0.5882

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.65332 | val 0.79660
  Epoch 019 - train 0.58692 | val 0.73734
  Classification -> best τ=0.465 (val F1=0.3072)
  Directional -> Accuracy: 0.5918, MCC: 0.1804, F1: 0.2308

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.63319 | val 1.03623
  Epoch 015 - train 0.59529 | val 0.91849
  Classification -> best τ=0.460 (val F1=0.2739)
  Directional -> Accuracy: 0.5263, MCC: 0.1360, F1: 0.6824

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.59990 | val 0.68973
  Epoch 017 - train 0.51390 | val 0.83509
  Classification -> best τ=0.650 (val F1=0.2176)
  Directional -> Accuracy: 0.5476, MCC: 0.0000, F1: 0.0000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.65021 | val 0.72956
  Epoch 018 - train 0.62452 | val 0.64844
  Classification -> best τ=0.600 (val F1=0.4109)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.63731 | val 0.77348
  Epoch 011 - train 0.61045 | val 0.77085
  Classification -> best τ=0.515 (val F1=0.1702)
  Directional -> Accuracy: 0.5490, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.64770 | val 1.09213
  Epoch 011 - train 0.60615 | val 1.10025
  Classification -> best τ=0.495 (val F1=0.2341)
  Directional -> Accuracy: 0.5652, MCC: 0.1256, F1: 0.7000

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.64016 | val 0.97851
  Epoch 011 - train 0.60899 | val 0.93069
  Classification -> best τ=0.650 (val F1=0.3093)
  Directional -> Accuracy: 0.3793, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.64687 | val 0.68324
  Epoch 020 - train 0.65589 | val 0.71564
  Epoch 021 - train 0.60888 | val 0.72510
  Classification -> best τ=0.495 (val F1=0.2596)
  Directional -> Accuracy: 0.5467, MCC: -0.0801, F1: 0.6909

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.62280 | val 0.82225
  Epoch 011 - train 0.58940 | val 0.99420
  Classification -> best τ=0.295 (val F1=0.2522)
  Directional -> Accuracy: 0.5312, MCC: 0.0095, F1: 0.6250

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.63892 | val 0.81676
  Epoch 011 - train 0.55688 | val 0.90504
  Classification -> best τ=0.585 (val F1=0.2937)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.62723 | val 1.04642
  Epoch 012 - train 0.58806 | val 1.04176
  Classification -> best τ=0.625 (val F1=0.2861)
  Directional -> Accuracy: 0.3404, MCC: -0.2797, F1: 0.3404

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.64004 | val 1.04914
  Epoch 011 - train 0.64184 | val 1.01400
  Classification -> best τ=0.430 (val F1=0.1561)
  Directional -> Accuracy: 0.4923, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.63984 | val 0.72464
  Epoch 011 - train 0.66308 | val 0.69738
  Classification -> best τ=0.705 (val F1=0.3550)
  Directional -> Accuracy: 0.5263, MCC: 0.0784, F1: 0.5091

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.67089 | val 0.89696
  Epoch 011 - train 0.65465 | val 0.87022
  Classification -> best τ=0.450 (val F1=0.2631)
  Directional -> Accuracy: 0.5231, MCC: 0.0584, F1: 0.5634

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.64773 | val 0.89047
  Epoch 012 - train 0.54554 | val 0.85871
  Classification -> best τ=0.585 (val F1=0.5048)
  Directional -> Accuracy: 0.5636, MCC: 0.1144, F1: 0.6129

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.54281 | val 2.33252
  Epoch 011 - train 0.51244 | val 2.26583
  Classification -> best τ=0.640 (val F1=0.2726)
  Directional -> Accuracy: 0.5778, MCC: 0.0000, F1: 0.0000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.60399 | val 0.75508
  Epoch 011 - train 0.57732 | val 0.69592
  Classification -> best τ=0.585 (val F1=0.1680)
  Directional -> Accuracy: 0.5476, MCC: 0.0446, F1: 0.6415

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.60232 | val 1.21940
  Epoch 011 - train 0.57956 | val 1.11094
  Classification -> best τ=0.420 (val F1=0.3265)
  Directional -> Accuracy: 0.4464, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.53398 | val 0.76226
  Epoch 011 - train 0.56204 | val 0.74910
  Classification -> best τ=0.450 (val F1=0.2618)
  Directional -> Accuracy: 0.6250, MCC: 0.3148, F1: 0.7458

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.61989 | val 1.01220
  Epoch 013 - train 0.58970 | val 1.03381
  Classification -> best τ=0.560 (val F1=0.0344)
  Directional -> Accuracy: 0.5714, MCC: 0.1357, F1: 0.4375

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.63544 | val 0.84494
  Epoch 019 - train 0.55943 | val 1.16881
  Classification -> best τ=0.680 (val F1=0.1329)
  Directional -> Accuracy: 0.4524, MCC: -0.0214, F1: 0.0800

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.62079 | val 0.93480
  Epoch 012 - train 0.56224 | val 0.79998
  Classification -> best τ=0.390 (val F1=0.4120)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.66985 | val 0.68497
  Epoch 017 - train 0.57098 | val 0.68258
  Classification -> best τ=0.360 (val F1=0.3245)
  Directional -> Accuracy: 0.4583, MCC: 0.0105, F1: 0.1702

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.57483 | val 0.94645
  Epoch 012 - train 0.53799 | val 0.95412
  Classification -> best τ=0.600 (val F1=0.2603)
  Directional -> Accuracy: 0.6047, MCC: 0.3278, F1: 0.3200

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.63144 | val 0.94012
  Epoch 011 - train 0.65981 | val 0.98219
  Classification -> best τ=0.280 (val F1=0.2778)
  Directional -> Accuracy: 0.5758, MCC: 0.0000, F1: 0.7308

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.59630 | val 0.85041
  Epoch 012 - train 0.50951 | val 0.75006
  Classification -> best τ=0.470 (val F1=0.3218)
  Directional -> Accuracy: 0.6429, MCC: 0.2919, F1: 0.6341

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.59199 | val 0.75796
  Epoch 015 - train 0.57146 | val 0.76669
  Classification -> best τ=0.500 (val F1=0.2725)
  Directional -> Accuracy: 0.5000, MCC: 0.0051, F1: 0.5000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.59531 | val 0.79934
  Epoch 011 - train 0.56844 | val 0.88154
  Classification -> best τ=0.525 (val F1=0.3409)
  Directional -> Accuracy: 0.3913, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.62714 | val 0.74383
  Epoch 019 - train 0.55580 | val 0.74146
  Classification -> best τ=0.515 (val F1=0.2405)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.65259 | val 1.09593
  Epoch 011 - train 0.59924 | val 0.93423
  Classification -> best τ=0.550 (val F1=0.2271)
  Directional -> Accuracy: 0.5135, MCC: 0.0278, F1: 0.5135

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.62362 | val 0.86353
  Epoch 015 - train 0.59838 | val 0.93595
  Classification -> best τ=0.520 (val F1=0.4490)
  Directional -> Accuracy: 0.5556, MCC: 0.1089, F1: 0.6000

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.51907 | val 1.54080
  Epoch 016 - train 0.47602 | val 1.36777
  Classification -> best τ=0.500 (val F1=0.4082)
  Directional -> Accuracy: 0.5952, MCC: 0.1803, F1: 0.7385

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.55259 | val 0.81150
  Epoch 012 - train 0.48167 | val 0.72600
  Classification -> best τ=0.625 (val F1=0.1974)
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.5455

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.67785 | val 0.72983
  Epoch 011 - train 0.67682 | val 0.71831
  Classification -> best τ=0.550 (val F1=0.2833)
  Directional -> Accuracy: 0.4364, MCC: -0.2170, F1: 0.5753

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.55767 | val 1.55371
  Epoch 011 - train 0.56803 | val 1.30256
  Classification -> best τ=0.720 (val F1=0.4444)
  Directional -> Accuracy: 0.4821, MCC: -0.0099, F1: 0.6329

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.66668 | val 0.78697
  Epoch 020 - train 0.63272 | val 0.66534
  Epoch 021 - train 0.61660 | val 0.67509
  Classification -> best τ=0.575 (val F1=0.2482)
  Directional -> Accuracy: 0.5849, MCC: 0.1704, F1: 0.6333

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.58627 | val 3.04212
  Epoch 011 - train 0.56304 | val 3.48124
  Classification -> best τ=0.630 (val F1=0.1605)
  Directional -> Accuracy: 0.4364, MCC: -0.1555, F1: 0.0606

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.66157 | val 0.67454

[I 2026-02-22 16:53:59,994] Trial 255 finished with value: 0.27992425242785773 and parameters: {'feature_set': 'sector', 'model_type': 'BiGRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.5, 'batch_size': 16, 'learning_rate': 0.009919082060240569, 'weight_decay': 0.0007322300250758104, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 0.9988117684630704, 'early_stopping_min_delta': 0.0015921322460026035}. Best is trial 252 with value: 0.3108162738957727.

  Epoch 017 - train 0.62671 | val 1.22142
  Classification -> best τ=0.355 (val F1=0.2719)
  Directional -> Accuracy: 0.6000, MCC: 0.2019, F1: 0.5000

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.27992425242785773
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.63753 | val 0.67831
  Epoch 020 - train 0.61881 | val 1.06809
  Classification -> best τ=0.835 (val F1=0.2510)
  Directional -> Accuracy: 0.6053, MCC: 0.1845, F1: 0.4000

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.59114 | val 0.88901
  Epoch 014 - train 0.57570 | val 1.07304
  Classification -> best τ=0.675 (val F1=0.1941)
  Directional -> Accuracy: 0.5556, MCC: 0.0891, F1: 0.6154

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.63273 | val 0.90033
  Epoch 011 - train 0.61039 | val 0.91727
  Classification -> best τ=0.515 (val F1=0.1572)
  Directional -> Accuracy: 0.4783, MCC: -0.0826, F1: 0.6000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.63890 | val 1.08275
  Epoch 018 - train 0.55086 | val 0.94642
  Classification -> best τ=0.460 (val F1=0.2760)
  Directional -> Accuracy: 0.4595, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.58971 | val 0.85194
  Epoch 019 - train 0.49476 | val 1.18614
  Classification -> best τ=0.430 (val F1=0.4782)
  Directional -> Accuracy: 0.7000, MCC: 0.4120, F1: 0.6809

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.60353 | val 0.68668
  Epoch 020 - train 0.48479 | val 1.33971
  Epoch 027 - train 0.38354 | val 0.81626
  Classification -> best τ=0.375 (val F1=0.3439)
  Directional -> Accuracy: 0.5217, MCC: 0.0229, F1: 0.3125

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.65589 | val 0.88825
  Epoch 011 - train 0.61544 | val 0.98050
  Classification -> best τ=0.460 (val F1=0.2506)
  Directional -> Accuracy: 0.5441, MCC: 0.0902, F1: 0.4918

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.61690 | val 0.54665
  Epoch 020 - train 0.45922 | val 3.57279
  Epoch 022 - train 0.42935 | val 1.86165
  Classification -> best τ=0.330 (val F1=0.4453)
  Directional -> Accuracy: 0.4524, MCC: -0.1635, F1: 0.2581

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.62121 | val 0.78830
  Epoch 011 - train 0.59019 | val 1.00884
  Classification -> best τ=0.540 (val F1=0.1221)
  Directional -> Accuracy: 0.6042, MCC: 0.1917, F1: 0.5366

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.62961 | val 0.76754
  Epoch 011 - train 0.59023 | val 0.76393
  Classification -> best τ=0.475 (val F1=0.2150)
  Directional -> Accuracy: 0.4348, MCC: 0.1033, F1: 0.5979

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.65809 | val 0.89126
  Epoch 012 - train 0.63741 | val 0.77545
  Classification -> best τ=0.425 (val F1=0.3020)
  Directional -> Accuracy: 0.5918, MCC: 0.1804, F1: 0.2308

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.63655 | val 0.82247
  Epoch 011 - train 0.62201 | val 0.79165
  Classification -> best τ=0.510 (val F1=0.2157)
  Directional -> Accuracy: 0.5088, MCC: 0.0000, F1: 0.6744

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.52424 | val 0.67977
  Epoch 016 - train 0.41216 | val 0.82141
  Classification -> best τ=0.575 (val F1=0.4301)
  Directional -> Accuracy: 0.4762, MCC: -0.1249, F1: 0.2143

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.62287 | val 0.71483
  Epoch 020 - train 0.56375 | val 0.88248
  Epoch 022 - train 0.52903 | val 0.97681
  Classification -> best τ=0.570 (val F1=0.3126)
  Directional -> Accuracy: 0.4833, MCC: -0.0603, F1: 0.1143

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.63418 | val 0.70214
  Epoch 020 - train 0.56810 | val 0.74928
  Epoch 021 - train 0.53026 | val 0.72871
  Classification -> best τ=0.655 (val F1=0.2571)
  Directional -> Accuracy: 0.5490, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.62937 | val 0.84648
  Epoch 015 - train 0.59858 | val 1.08716
  Classification -> best τ=0.650 (val F1=0.2997)
  Directional -> Accuracy: 0.5507, MCC: 0.1234, F1: 0.5079

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.64804 | val 0.73203
  Epoch 019 - train 0.54860 | val 1.41665
  Classification -> best τ=0.615 (val F1=0.2512)
  Directional -> Accuracy: 0.3793, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.63081 | val 0.85560
  Epoch 019 - train 0.56437 | val 0.88826
  Classification -> best τ=0.435 (val F1=0.2473)
  Directional -> Accuracy: 0.5600, MCC: -0.0144, F1: 0.6916

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.59904 | val 1.00456
  Epoch 012 - train 0.56896 | val 1.09835
  Classification -> best τ=0.390 (val F1=0.3421)
  Directional -> Accuracy: 0.5000, MCC: -0.0149, F1: 0.5556

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.58774 | val 0.90400
  Epoch 011 - train 0.56307 | val 0.88381
  Classification -> best τ=0.590 (val F1=0.2470)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.61911 | val 0.74628
  Epoch 012 - train 0.54270 | val 0.76349
  Classification -> best τ=0.480 (val F1=0.2784)
  Directional -> Accuracy: 0.5532, MCC: 0.0645, F1: 0.6316

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.61342 | val 1.04921
  Epoch 011 - train 0.59523 | val 1.38346
  Classification -> best τ=0.520 (val F1=0.2520)
  Directional -> Accuracy: 0.5077, MCC: 0.1231, F1: 0.0588

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.67530 | val 0.69676
  Epoch 020 - train 0.65738 | val 0.61442
  Epoch 025 - train 0.52398 | val 0.64074
  Classification -> best τ=0.700 (val F1=0.4108)
  Directional -> Accuracy: 0.5614, MCC: 0.0910, F1: 0.6377

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.63824 | val 0.73154
  Epoch 012 - train 0.64733 | val 0.83691
  Classification -> best τ=0.380 (val F1=0.1122)
  Directional -> Accuracy: 0.4615, MCC: -0.0657, F1: 0.6067

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.59896 | val 0.81459
  Epoch 013 - train 0.55501 | val 0.95352
  Classification -> best τ=0.385 (val F1=0.4075)
  Directional -> Accuracy: 0.5091, MCC: 0.0133, F1: 0.5424

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.58899 | val 0.93626
  Epoch 012 - train 0.55932 | val 0.83960
  Classification -> best τ=0.540 (val F1=0.2726)
  Directional -> Accuracy: 0.6222, MCC: 0.1924, F1: 0.4138

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.60804 | val 0.83212
  Epoch 011 - train 0.61046 | val 0.80951
  Classification -> best τ=0.540 (val F1=0.1171)
  Directional -> Accuracy: 0.5238, MCC: 0.1217, F1: 0.4444

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.64034 | val 0.70097
  Epoch 013 - train 0.52142 | val 0.93960
  Classification -> best τ=0.445 (val F1=0.3961)
  Directional -> Accuracy: 0.4464, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.60772 | val 0.75617
  Epoch 011 - train 0.58095 | val 0.77134
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5500, MCC: 0.0000, F1: 0.7097

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.66149 | val 0.94778
  Epoch 011 - train 0.61208 | val 0.86204
  Classification -> best τ=0.520 (val F1=0.3501)
  Directional -> Accuracy: 0.5476, MCC: 0.1137, F1: 0.5957

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.60489 | val 0.98110
  Epoch 011 - train 0.59213 | val 0.91217
  Classification -> best τ=0.525 (val F1=0.2697)
  Directional -> Accuracy: 0.4762, MCC: 0.0387, F1: 0.2143

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.63460 | val 0.70649
  Epoch 018 - train 0.41556 | val 0.86561
  Classification -> best τ=0.510 (val F1=0.2521)
  Directional -> Accuracy: 0.5714, MCC: 0.1676, F1: 0.7042

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.63111 | val 0.73927
  Epoch 011 - train 0.57075 | val 0.73337
  Classification -> best τ=0.495 (val F1=0.3260)
  Directional -> Accuracy: 0.4861, MCC: 0.1344, F1: 0.1778

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.60609 | val 0.76692
  Epoch 018 - train 0.46366 | val 1.00569
  Classification -> best τ=0.725 (val F1=0.2151)
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.65631 | val 0.95334
  Epoch 012 - train 0.60433 | val 0.98103
  Classification -> best τ=0.320 (val F1=0.3525)
  Directional -> Accuracy: 0.6364, MCC: 0.2714, F1: 0.6667

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.57591 | val 0.87111
  Epoch 014 - train 0.45455 | val 1.14689
  Classification -> best τ=0.540 (val F1=0.3828)
  Directional -> Accuracy: 0.5952, MCC: 0.2656, F1: 0.4516

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.57309 | val 1.10044
  Epoch 011 - train 0.54472 | val 1.06101
  Classification -> best τ=0.605 (val F1=0.2203)
  Directional -> Accuracy: 0.4464, MCC: -0.0962, F1: 0.4746

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.54621 | val 0.71558
  Epoch 012 - train 0.53823 | val 0.80111
  Classification -> best τ=0.385 (val F1=0.2118)
  Directional -> Accuracy: 0.6087, MCC: 0.0000, F1: 0.7568

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.63076 | val 0.86048
  Epoch 014 - train 0.60111 | val 0.94764
  Classification -> best τ=0.520 (val F1=0.4242)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.57707 | val 0.78672
  Epoch 014 - train 0.52709 | val 1.28186
  Classification -> best τ=0.390 (val F1=0.3052)
  Directional -> Accuracy: 0.4865, MCC: 0.0000, F1: 0.6545

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.60228 | val 0.68639
  Epoch 020 - train 0.61317 | val 0.66497
  Epoch 027 - train 0.52370 | val 1.05477
  Classification -> best τ=0.570 (val F1=0.5164)
  Directional -> Accuracy: 0.4667, MCC: -0.0786, F1: 0.1429

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.45711 | val 1.50346
  Epoch 011 - train 0.36031 | val 1.51866
  Classification -> best τ=0.600 (val F1=0.4082)
  Directional -> Accuracy: 0.5714, MCC: 0.1132, F1: 0.6400

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.58042 | val 0.64551
  Epoch 020 - train 0.41871 | val 0.57887
  Epoch 028 - train 0.35522 | val 0.63112
  Classification -> best τ=0.705 (val F1=0.5261)
  Directional -> Accuracy: 0.3958, MCC: 0.1130, F1: 0.5538

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.67307 | val 0.67903
  Epoch 019 - train 0.64708 | val 0.89606
  Classification -> best τ=0.670 (val F1=0.2036)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.55771 | val 2.36679
  Epoch 011 - train 0.53606 | val 2.13263
  Classification -> best τ=0.600 (val F1=0.2499)
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.6506

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.68347 | val 0.67667
  Epoch 020 - train 0.64699 | val 0.78162
  Classification -> best τ=0.565 (val F1=0.1847)
  Directional -> Accuracy: 0.5283, MCC: 0.0546, F1: 0.6269

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.59813 | val 2.22561
  Epoch 011 - train 0.61224 | val 2.44210
  Classification -> best τ=0.530 (val F1=0.0782)
  Directional -> Accuracy: 0.5455, MCC: 0.0759, F1: 0.6269

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.65671 | val 0.66543

[I 2026-02-22 16:59:08,553] Trial 256 finished with value: 0.28530991909970294 and parameters: {'feature_set': 'sector', 'model_type': 'BiLSTM', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.5, 'batch_size': 16, 'learning_rate': 0.007104259319046133, 'weight_decay': 0.0002675522359424378, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 1.0603291740642264, 'early_stopping_min_delta': 0.0024324119073468493}. Best is trial 252 with value: 0.3108162738957727.

  Epoch 020 - train 0.64113 | val 0.70184
  Classification -> best τ=0.385 (val F1=0.3330)
  Directional -> Accuracy: 0.4667, MCC: -0.0580, F1: 0.5556

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.28530991909970294
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.60700 | val 0.85975
  Epoch 020 - train 0.57812 | val 1.09208
  Epoch 021 - train 0.59527 | val 1.11142
  Classification -> best τ=0.580 (val F1=0.2919)
  Directional -> Accuracy: 0.5658, MCC: 0.0797, F1: 0.2326

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.59538 | val 1.18153
  Epoch 013 - train 0.48543 | val 1.27844
  Classification -> best τ=0.525 (val F1=0.1941)
  Directional -> Accuracy: 0.5556, MCC: 0.0891, F1: 0.6154

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.61826 | val 1.16015
  Epoch 011 - train 0.58254 | val 1.32185
  Classification -> best τ=0.710 (val F1=0.1978)
  Directional -> Accuracy: 0.5217, MCC: 0.1124, F1: 0.2667

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.64603 | val 0.74958
  Epoch 020 - train 0.50732 | val 1.17419
  Epoch 021 - train 0.50257 | val 1.41393
  Classification -> best τ=0.515 (val F1=0.3495)
  Directional -> Accuracy: 0.5270, MCC: 0.0736, F1: 0.4928

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.53084 | val 1.81576
  Epoch 014 - train 0.51154 | val 1.43002
  Classification -> best τ=0.470 (val F1=0.4493)
  Directional -> Accuracy: 0.6600, MCC: 0.3320, F1: 0.7213

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.55037 | val 1.04238
  Epoch 020 - train 0.48118 | val 0.98662
  Epoch 026 - train 0.38066 | val 0.99561
  Classification -> best τ=0.430 (val F1=0.4957)
  Directional -> Accuracy: 0.5217, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.65405 | val 0.77426
  Epoch 016 - train 0.56388 | val 0.82143
  Classification -> best τ=0.445 (val F1=0.3485)
  Directional -> Accuracy: 0.6176, MCC: 0.1265, F1: 0.2778

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.49834 | val 0.59288
  Epoch 019 - train 0.42042 | val 0.96760
  Classification -> best τ=0.395 (val F1=0.3632)
  Directional -> Accuracy: 0.4762, MCC: -0.0694, F1: 0.3889

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.63782 | val 1.02994
  Epoch 013 - train 0.60604 | val 1.08007
  Classification -> best τ=0.680 (val F1=0.1928)
  Directional -> Accuracy: 0.5625, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.58557 | val 0.73712
  Epoch 011 - train 0.57935 | val 0.72421
  Classification -> best τ=0.485 (val F1=0.2396)
  Directional -> Accuracy: 0.4348, MCC: -0.1078, F1: 0.4348

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.61493 | val 0.66281
  Epoch 018 - train 0.56183 | val 1.07142
  Classification -> best τ=0.510 (val F1=0.3493)
  Directional -> Accuracy: 0.6531, MCC: 0.3136, F1: 0.4516

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.61465 | val 1.30819
  Epoch 012 - train 0.56544 | val 1.51693
  Classification -> best τ=0.470 (val F1=0.2434)
  Directional -> Accuracy: 0.5088, MCC: 0.0000, F1: 0.6744

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.56857 | val 1.09993
  Epoch 011 - train 0.52098 | val 1.15202
  Classification -> best τ=0.395 (val F1=0.0400)
  Directional -> Accuracy: 0.4048, MCC: -0.1758, F1: 0.5455

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.64847 | val 0.68230
  Epoch 011 - train 0.61723 | val 0.68365
  Classification -> best τ=0.390 (val F1=0.2750)
  Directional -> Accuracy: 0.5167, MCC: 0.0431, F1: 0.2927

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.59713 | val 0.75124
  Epoch 011 - train 0.63112 | val 0.71586
  Classification -> best τ=0.590 (val F1=0.3000)
  Directional -> Accuracy: 0.5490, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.61113 | val 1.59807
  Epoch 011 - train 0.57165 | val 1.98021
  Classification -> best τ=0.385 (val F1=0.2341)
  Directional -> Accuracy: 0.5362, MCC: 0.0126, F1: 0.6923

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.61487 | val 0.75821
  Epoch 013 - train 0.55228 | val 0.78282
  Classification -> best τ=0.615 (val F1=0.3060)
  Directional -> Accuracy: 0.3793, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.59497 | val 1.08784
  Epoch 011 - train 0.57261 | val 0.96221
  Classification -> best τ=0.480 (val F1=0.2537)
  Directional -> Accuracy: 0.4933, MCC: -0.0934, F1: 0.6042

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.63569 | val 0.79774
  Epoch 016 - train 0.58437 | val 0.83574
  Classification -> best τ=0.510 (val F1=0.3622)
  Directional -> Accuracy: 0.5000, MCC: -0.0049, F1: 0.5429

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.54054 | val 0.84812
  Epoch 011 - train 0.51308 | val 0.86818
  Classification -> best τ=0.385 (val F1=0.2597)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.60952 | val 0.75996
  Epoch 018 - train 0.45209 | val 0.88232
  Classification -> best τ=0.790 (val F1=0.3237)
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.60246 | val 1.20999
  Epoch 011 - train 0.56365 | val 1.34629
  Classification -> best τ=0.605 (val F1=0.2376)
  Directional -> Accuracy: 0.5077, MCC: 0.1231, F1: 0.0588

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.65854 | val 0.64681
  Epoch 020 - train 0.56409 | val 0.96260
  Classification -> best τ=0.725 (val F1=0.4319)
  Directional -> Accuracy: 0.5088, MCC: 0.0112, F1: 0.5484

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.64242 | val 0.71091
  Epoch 011 - train 0.61623 | val 0.70096
  Classification -> best τ=0.550 (val F1=0.2055)
  Directional -> Accuracy: 0.4923, MCC: -0.0285, F1: 0.4000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.56508 | val 0.85606
  Epoch 012 - train 0.52381 | val 0.79902
  Classification -> best τ=0.325 (val F1=0.4380)
  Directional -> Accuracy: 0.5455, MCC: 0.0690, F1: 0.6154

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.51569 | val 1.97586
  Epoch 011 - train 0.46150 | val 2.22665
  Classification -> best τ=0.595 (val F1=0.3006)
  Directional -> Accuracy: 0.5333, MCC: 0.0367, F1: 0.4324

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.60384 | val 0.83557
  Epoch 018 - train 0.53908 | val 0.74104
  Classification -> best τ=0.545 (val F1=0.2402)
  Directional -> Accuracy: 0.4524, MCC: -0.0313, F1: 0.3429

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.61065 | val 0.91125
  Epoch 011 - train 0.54763 | val 1.03160
  Classification -> best τ=0.400 (val F1=0.4007)
  Directional -> Accuracy: 0.4464, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.51788 | val 0.81861
  Epoch 011 - train 0.49426 | val 0.82857
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5500, MCC: 0.0000, F1: 0.7097

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.60545 | val 0.78207
  Epoch 011 - train 0.60900 | val 0.74722
  Classification -> best τ=0.485 (val F1=0.3501)
  Directional -> Accuracy: 0.5000, MCC: 0.0046, F1: 0.5116

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.57017 | val 1.48282
  Epoch 012 - train 0.55114 | val 1.48065
  Classification -> best τ=0.445 (val F1=0.2147)
  Directional -> Accuracy: 0.5476, MCC: 0.0391, F1: 0.6780

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.59602 | val 0.74733
  Epoch 016 - train 0.54279 | val 0.68489
  Classification -> best τ=0.325 (val F1=0.3242)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.60354 | val 0.69881
  Epoch 019 - train 0.50185 | val 1.08342
  Classification -> best τ=0.540 (val F1=0.3278)
  Directional -> Accuracy: 0.4444, MCC: 0.0000, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.57720 | val 0.99916
  Epoch 011 - train 0.54451 | val 0.95831
  Classification -> best τ=0.450 (val F1=0.2324)
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.60806 | val 1.32027
  Epoch 011 - train 0.58579 | val 1.12625
  Classification -> best τ=0.295 (val F1=0.3280)
  Directional -> Accuracy: 0.6667, MCC: 0.3045, F1: 0.7556

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.56132 | val 0.74970
  Epoch 012 - train 0.41633 | val 0.88992
  Classification -> best τ=0.600 (val F1=0.3001)
  Directional -> Accuracy: 0.5952, MCC: 0.2427, F1: 0.4848

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.55497 | val 0.87459
  Epoch 018 - train 0.43354 | val 1.72955
  Classification -> best τ=0.395 (val F1=0.2114)
  Directional -> Accuracy: 0.5714, MCC: 0.1925, F1: 0.6364

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.66638 | val 0.98048
  Epoch 014 - train 0.51040 | val 0.99144
  Classification -> best τ=0.655 (val F1=0.2783)
  Directional -> Accuracy: 0.3913, MCC: -0.0475, F1: 0.0667

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.51802 | val 0.92727
  Epoch 020 - train 0.50322 | val 0.93997
  Epoch 024 - train 0.44823 | val 1.19865
  Classification -> best τ=0.340 (val F1=0.3859)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.62164 | val 1.07988
  Epoch 012 - train 0.54217 | val 1.12896
  Classification -> best τ=0.370 (val F1=0.3053)
  Directional -> Accuracy: 0.4865, MCC: 0.0000, F1: 0.6545

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.70829 | val 0.85766
  Epoch 012 - train 0.55957 | val 0.82934
  Classification -> best τ=0.430 (val F1=0.3500)
  Directional -> Accuracy: 0.5778, MCC: 0.1877, F1: 0.4571

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.48364 | val 1.25103
  Epoch 011 - train 0.43772 | val 1.11110
  Classification -> best τ=0.600 (val F1=0.3015)
  Directional -> Accuracy: 0.5714, MCC: 0.0468, F1: 0.7097

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.53498 | val 0.99918
  Epoch 011 - train 0.51487 | val 0.87387
  Classification -> best τ=0.430 (val F1=0.0309)
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.5455

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.67661 | val 0.93501
  Epoch 012 - train 0.62391 | val 0.96898
  Classification -> best τ=0.560 (val F1=0.2291)
  Directional -> Accuracy: 0.5091, MCC: -0.0516, F1: 0.6400

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.55566 | val 3.66000
  Epoch 011 - train 0.54044 | val 4.27681
  Classification -> best τ=0.805 (val F1=0.3073)
  Directional -> Accuracy: 0.5357, MCC: 0.0702, F1: 0.5185

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.66281 | val 0.85594
  Epoch 016 - train 0.59702 | val 1.03851
  Classification -> best τ=0.545 (val F1=0.2358)
  Directional -> Accuracy: 0.5660, MCC: 0.1312, F1: 0.5818

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.58242 | val 2.58104
  Epoch 013 - train 0.50854 | val 2.85983
  Classification -> best τ=0.640 (val F1=0.3303)
  Directional -> Accuracy: 0.4727, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.65224 | val 0.71631
  Epoch 013 - train 0.59862 | val 0.82615

[I 2026-02-22 17:03:11,519] Trial 257 finished with value: 0.2857655672341784 and parameters: {'feature_set': 'sector', 'model_type': 'BiGRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.5, 'batch_size': 16, 'learning_rate': 0.0071768443578046496, 'weight_decay': 0.0002657717876975774, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 1.1065094811544132, 'early_stopping_min_delta': 0.0024996636131002633}. Best is trial 252 with value: 0.3108162738957727.

  Classification -> best τ=0.480 (val F1=0.3496)
  Directional -> Accuracy: 0.5333, MCC: 0.0594, F1: 0.4400

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2857655672341784
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sentiment']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.64154 | val 0.64801
  Epoch 020 - train 0.60669 | val 1.29318
  Epoch 021 - train 0.61096 | val 1.16917
  Classification -> best τ=0.670 (val F1=0.3286)
  Directional -> Accuracy: 0.5132, MCC: -0.0841, F1: 0.1395

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.61551 | val 0.77366
  Epoch 012 - train 0.62176 | val 0.83916
  Classification -> best τ=0.400 (val F1=0.2285)
  Directional -> Accuracy: 0.5778, MCC: 0.0000, F1: 0.7324

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.67646 | val 0.67603
  Epoch 011 - train 0.67977 | val 0.66369
  Classification -> best τ=0.520 (val F1=0.4828)
  Directional -> Accuracy: 0.5217, MCC: 0.0200, F1: 0.6452

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.68778 | val 0.69189
  Epoch 020 - train 0.65246 | val 1.19276
  Classification -> best τ=0.535 (val F1=0.0602)
  Directional -> Accuracy: 0.4595, MCC: -0.0194, F1: 0.0909

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.63744 | val 0.64640
  Epoch 015 - train 0.64563 | val 0.78255
  Classification -> best τ=0.620 (val F1=0.4611)
  Directional -> Accuracy: 0.7000, MCC: 0.4361, F1: 0.6512

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.63272 | val 0.69383
  Epoch 014 - train 0.61790 | val 0.89302
  Classification -> best τ=0.505 (val F1=0.3222)
  Directional -> Accuracy: 0.5435, MCC: 0.0763, F1: 0.3226

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.67231 | val 0.81708
  Epoch 012 - train 0.66309 | val 0.75417
  Classification -> best τ=0.280 (val F1=0.3042)
  Directional -> Accuracy: 0.3971, MCC: 0.0000, F1: 0.5684

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.65819 | val 1.90831
  Epoch 013 - train 0.65336 | val 1.54191
  Classification -> best τ=0.535 (val F1=0.2100)
  Directional -> Accuracy: 0.5714, MCC: 0.1514, F1: 0.5500

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.65123 | val 0.75275
  Epoch 011 - train 0.64786 | val 0.73297
  Classification -> best τ=0.505 (val F1=0.2443)
  Directional -> Accuracy: 0.5833, MCC: 0.1449, F1: 0.5000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.67468 | val 0.71560
  Epoch 013 - train 0.64169 | val 0.86329
  Classification -> best τ=0.550 (val F1=0.2293)
  Directional -> Accuracy: 0.3913, MCC: -0.1540, F1: 0.5435

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.66297 | val 0.88848
  Epoch 012 - train 0.66436 | val 0.92031
  Classification -> best τ=0.435 (val F1=0.4037)
  Directional -> Accuracy: 0.5918, MCC: 0.1557, F1: 0.4444

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.68554 | val 1.24541
  Epoch 011 - train 0.67185 | val 1.02807
  Classification -> best τ=0.515 (val F1=0.1771)
  Directional -> Accuracy: 0.6140, MCC: 0.2849, F1: 0.7105

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.60927 | val 0.88952
  Epoch 011 - train 0.58665 | val 0.90880
  Classification -> best τ=0.560 (val F1=0.1707)
  Directional -> Accuracy: 0.5714, MCC: 0.1276, F1: 0.5000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.70802 | val 0.66151
  Epoch 020 - train 0.69902 | val 0.67108
  Epoch 022 - train 0.67741 | val 0.64307
  Classification -> best τ=0.365 (val F1=0.3477)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6053

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.64928 | val 0.77228
  Epoch 011 - train 0.64752 | val 0.78824
  Classification -> best τ=0.500 (val F1=0.2141)
  Directional -> Accuracy: 0.5490, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.68976 | val 0.71883
  Epoch 013 - train 0.67836 | val 0.72778
  Classification -> best τ=0.470 (val F1=0.3150)
  Directional -> Accuracy: 0.5217, MCC: -0.0237, F1: 0.6667

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.67528 | val 0.96408
  Epoch 011 - train 0.68910 | val 0.90121
  Classification -> best τ=0.555 (val F1=0.2186)
  Directional -> Accuracy: 0.4310, MCC: 0.1826, F1: 0.1538

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.66937 | val 0.78954
  Epoch 011 - train 0.65722 | val 0.79746
  Classification -> best τ=0.570 (val F1=0.2220)
  Directional -> Accuracy: 0.4267, MCC: 0.1351, F1: 0.0851

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.64765 | val 0.74552
  Epoch 019 - train 0.60987 | val 0.79965
  Classification -> best τ=0.245 (val F1=0.3140)
  Directional -> Accuracy: 0.5469, MCC: 0.2224, F1: 0.4314

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.61267 | val 0.78765
  Epoch 011 - train 0.58815 | val 0.81496
  Classification -> best τ=0.530 (val F1=0.3161)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.66964 | val 0.67976
  Epoch 018 - train 0.65442 | val 0.67833
  Classification -> best τ=0.455 (val F1=0.3678)
  Directional -> Accuracy: 0.5745, MCC: -0.0074, F1: 0.7059

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.69309 | val 0.72699
  Epoch 011 - train 0.70929 | val 0.70796
  Classification -> best τ=0.575 (val F1=0.2168)
  Directional -> Accuracy: 0.5231, MCC: 0.1755, F1: 0.1143

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.66593 | val 0.68752
  Epoch 015 - train 0.69283 | val 0.73679
  Classification -> best τ=0.580 (val F1=0.3370)
  Directional -> Accuracy: 0.4912, MCC: 0.0465, F1: 0.3830

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.67788 | val 0.69895
  Epoch 015 - train 0.68267 | val 0.70528
  Classification -> best τ=0.455 (val F1=0.2400)
  Directional -> Accuracy: 0.4769, MCC: 0.0000, F1: 0.6458

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.64315 | val 0.73134
  Epoch 014 - train 0.62310 | val 0.66813
  Classification -> best τ=0.570 (val F1=0.4075)
  Directional -> Accuracy: 0.4909, MCC: 0.0516, F1: 0.3000

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.60321 | val 2.08545
  Epoch 011 - train 0.58093 | val 2.33230
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.5938

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.65440 | val 0.71674
  Epoch 013 - train 0.64314 | val 0.72047
  Classification -> best τ=0.560 (val F1=0.0700)
  Directional -> Accuracy: 0.5238, MCC: 0.0694, F1: 0.5238

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.64346 | val 0.77275
  Epoch 011 - train 0.67586 | val 0.74197
  Classification -> best τ=0.465 (val F1=0.2718)
  Directional -> Accuracy: 0.5357, MCC: 0.2812, F1: 0.2778

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.60737 | val 0.98192
  Epoch 011 - train 0.60685 | val 1.08099
  Classification -> best τ=0.510 (val F1=0.1457)
  Directional -> Accuracy: 0.7000, MCC: 0.4062, F1: 0.7692

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.67500 | val 1.04225
  Epoch 011 - train 0.68002 | val 1.04852
  Classification -> best τ=0.520 (val F1=0.3244)
  Directional -> Accuracy: 0.3810, MCC: -0.2412, F1: 0.4800

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.71300 | val 0.68644
  Epoch 020 - train 0.67723 | val 0.85305
  Classification -> best τ=0.485 (val F1=0.3385)
  Directional -> Accuracy: 0.5714, MCC: 0.1718, F1: 0.7188

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.65388 | val 0.70108
  Epoch 012 - train 0.61407 | val 0.70430
  Classification -> best τ=0.450 (val F1=0.2812)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.67584 | val 0.85573
  Epoch 011 - train 0.66247 | val 0.84047
  Classification -> best τ=0.565 (val F1=0.2267)
  Directional -> Accuracy: 0.4444, MCC: 0.0000, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.68499 | val 0.82367
  Epoch 011 - train 0.69200 | val 0.79584
  Classification -> best τ=0.570 (val F1=0.1818)
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.63172 | val 0.99672
  Epoch 011 - train 0.64427 | val 0.89965
  Classification -> best τ=0.420 (val F1=0.3068)
  Directional -> Accuracy: 0.6212, MCC: 0.2364, F1: 0.6575

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.64600 | val 0.76007
  Epoch 017 - train 0.56672 | val 0.78694
  Classification -> best τ=0.370 (val F1=0.3551)
  Directional -> Accuracy: 0.6667, MCC: 0.3318, F1: 0.6818

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.65548 | val 0.71036
  Epoch 012 - train 0.61230 | val 0.78826
  Classification -> best τ=0.540 (val F1=0.2976)
  Directional -> Accuracy: 0.5179, MCC: -0.0174, F1: 0.2286

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.64094 | val 0.83698
  Epoch 011 - train 0.60882 | val 0.84198
  Classification -> best τ=0.515 (val F1=0.3750)
  Directional -> Accuracy: 0.6087, MCC: 0.1473, F1: 0.7000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.65240 | val 0.77466
  Epoch 013 - train 0.61456 | val 0.80630
  Classification -> best τ=0.415 (val F1=0.4011)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.68085 | val 0.84226
  Epoch 013 - train 0.63176 | val 0.99076
  Classification -> best τ=0.175 (val F1=0.4325)
  Directional -> Accuracy: 0.4865, MCC: 0.0000, F1: 0.6545

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.62511 | val 0.69077
  Epoch 016 - train 0.62655 | val 0.74996
  Classification -> best τ=0.485 (val F1=0.3371)
  Directional -> Accuracy: 0.5333, MCC: 0.1493, F1: 0.2222

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.61127 | val 1.15485
  Epoch 011 - train 0.62148 | val 1.26739
  Classification -> best τ=0.505 (val F1=0.2408)
  Directional -> Accuracy: 0.6190, MCC: 0.1964, F1: 0.7333

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.66463 | val 0.83654
  Epoch 013 - train 0.62076 | val 0.98811
  Classification -> best τ=0.570 (val F1=0.1974)
  Directional -> Accuracy: 0.3750, MCC: -0.0976, F1: 0.5000

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.68340 | val 0.89962
  Epoch 013 - train 0.67636 | val 0.98083
  Classification -> best τ=0.570 (val F1=0.2224)
  Directional -> Accuracy: 0.5636, MCC: 0.1698, F1: 0.5000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.64394 | val 1.44093
  Epoch 011 - train 0.63792 | val 1.46809
  Classification -> best τ=0.715 (val F1=0.3497)
  Directional -> Accuracy: 0.5536, MCC: 0.1555, F1: 0.6479

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.68947 | val 0.68724
  Epoch 020 - train 0.68167 | val 0.69400
  Epoch 021 - train 0.67242 | val 0.72132
  Classification -> best τ=0.550 (val F1=0.2012)
  Directional -> Accuracy: 0.4528, MCC: -0.1599, F1: 0.6027

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.63264 | val 1.53229
  Epoch 011 - train 0.63924 | val 1.70077
  Classification -> best τ=0.550 (val F1=0.1062)
  Directional -> Accuracy: 0.5273, MCC: 0.0000, F1: 0.6905

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.66699 | val 0.68697

[I 2026-02-22 17:07:40,110] Trial 258 finished with value: 0.2717982276906467 and parameters: {'feature_set': 'sentinment', 'model_type': 'BiLSTM', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.5, 'batch_size': 16, 'learning_rate': 0.006969608400584622, 'weight_decay': 0.0002811201626245893, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 1.1003006608293293, 'early_stopping_min_delta': 0.002370488405224502}. Best is trial 252 with value: 0.3108162738957727.

  Epoch 012 - train 0.66645 | val 0.69085
  Classification -> best τ=0.440 (val F1=0.2441)
  Directional -> Accuracy: 0.5833, MCC: 0.1634, F1: 0.5283

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2717982276906467
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.65369 | val 0.79171
  Epoch 013 - train 0.62573 | val 0.95076
  Classification -> best τ=0.815 (val F1=0.2510)
  Directional -> Accuracy: 0.5526, MCC: 0.0000, F1: 0.0000

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.58912 | val 0.85690
  Epoch 011 - train 0.59122 | val 0.96214
  Classification -> best τ=0.500 (val F1=0.2523)
  Directional -> Accuracy: 0.6000, MCC: 0.1591, F1: 0.6786

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.65116 | val 0.74786
  Epoch 014 - train 0.60680 | val 0.96849
  Classification -> best τ=0.560 (val F1=0.3237)
  Directional -> Accuracy: 0.4783, MCC: -0.0093, F1: 0.0769

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.65236 | val 0.75076
  Epoch 018 - train 0.57039 | val 0.84651
  Classification -> best τ=0.510 (val F1=0.2482)
  Directional -> Accuracy: 0.4595, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.57380 | val 0.81400
  Epoch 016 - train 0.53652 | val 0.69595
  Classification -> best τ=0.505 (val F1=0.4753)
  Directional -> Accuracy: 0.7000, MCC: 0.4048, F1: 0.6939

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.57887 | val 0.88207
  Epoch 020 - train 0.48761 | val 0.82089
  Epoch 021 - train 0.44503 | val 0.84942
  Classification -> best τ=0.740 (val F1=0.3644)
  Directional -> Accuracy: 0.5217, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.59728 | val 0.96246
  Epoch 011 - train 0.60879 | val 0.94496
  Classification -> best τ=0.605 (val F1=0.2163)
  Directional -> Accuracy: 0.6029, MCC: 0.0000, F1: 0.0000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.58481 | val 0.63652
  Epoch 020 - train 0.42979 | val 0.65807
  Epoch 023 - train 0.41076 | val 0.69858
  Classification -> best τ=0.115 (val F1=0.3504)
  Directional -> Accuracy: 0.5000, MCC: 0.0782, F1: 0.5714

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.65298 | val 0.83670
  Epoch 013 - train 0.61062 | val 0.74851
  Classification -> best τ=0.535 (val F1=0.2584)
  Directional -> Accuracy: 0.5625, MCC: 0.1159, F1: 0.5116

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.59654 | val 0.82348
  Epoch 012 - train 0.59326 | val 0.84198
  Classification -> best τ=0.495 (val F1=0.2982)
  Directional -> Accuracy: 0.4058, MCC: -0.1153, F1: 0.5176

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.65275 | val 0.68233
  Epoch 019 - train 0.56440 | val 0.75025
  Classification -> best τ=0.560 (val F1=0.2687)
  Directional -> Accuracy: 0.6122, MCC: 0.2379, F1: 0.2963

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.66335 | val 0.84864
  Epoch 011 - train 0.65347 | val 0.87129
  Classification -> best τ=0.520 (val F1=0.1450)
  Directional -> Accuracy: 0.5614, MCC: 0.1915, F1: 0.6914

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.55335 | val 1.45101
  Epoch 012 - train 0.49596 | val 1.58292
  Classification -> best τ=0.475 (val F1=0.0731)
  Directional -> Accuracy: 0.4048, MCC: -0.2205, F1: 0.2857

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.64137 | val 0.69593
  Epoch 017 - train 0.55811 | val 0.92954
  Classification -> best τ=0.440 (val F1=0.3126)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.63871 | val 0.82290
  Epoch 011 - train 0.63391 | val 0.83058
  Classification -> best τ=0.495 (val F1=0.1925)
  Directional -> Accuracy: 0.5098, MCC: -0.0183, F1: 0.3590

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.62577 | val 0.86763
  Epoch 011 - train 0.61995 | val 0.91294
  Classification -> best τ=0.425 (val F1=0.2589)
  Directional -> Accuracy: 0.4493, MCC: -0.1458, F1: 0.5581

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.64135 | val 0.94325
  Epoch 011 - train 0.61738 | val 0.98914
  Classification -> best τ=0.495 (val F1=0.1770)
  Directional -> Accuracy: 0.4828, MCC: -0.0796, F1: 0.5714

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.63490 | val 0.94424
  Epoch 012 - train 0.57315 | val 1.01491
  Classification -> best τ=0.550 (val F1=0.2165)
  Directional -> Accuracy: 0.4533, MCC: 0.1405, F1: 0.1961

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.63036 | val 0.75611
  Epoch 011 - train 0.61695 | val 0.78433
  Classification -> best τ=0.430 (val F1=0.3484)
  Directional -> Accuracy: 0.5781, MCC: 0.0000, F1: 0.7327

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.58529 | val 0.95211
  Epoch 011 - train 0.54099 | val 1.08216
  Classification -> best τ=0.545 (val F1=0.2617)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.62750 | val 0.76648
  Epoch 017 - train 0.52350 | val 0.94283
  Classification -> best τ=0.805 (val F1=0.2449)
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.64064 | val 0.87524
  Epoch 012 - train 0.60707 | val 0.96407
  Classification -> best τ=0.480 (val F1=0.2327)
  Directional -> Accuracy: 0.5846, MCC: 0.2493, F1: 0.3721

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.63650 | val 0.67469
  Epoch 020 - train 0.60831 | val 0.74191
  Epoch 024 - train 0.55078 | val 1.30881
  Classification -> best τ=0.425 (val F1=0.3906)
  Directional -> Accuracy: 0.6491, MCC: 0.2779, F1: 0.7368

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.65685 | val 0.83207
  Epoch 012 - train 0.61683 | val 0.76873
  Classification -> best τ=0.435 (val F1=0.1122)
  Directional -> Accuracy: 0.4615, MCC: -0.1309, F1: 0.6316

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.58890 | val 0.62253
  Epoch 015 - train 0.55846 | val 0.93812
  Classification -> best τ=0.540 (val F1=0.4582)
  Directional -> Accuracy: 0.5636, MCC: 0.2170, F1: 0.4286

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.59293 | val 1.27811
  Epoch 011 - train 0.53556 | val 1.34390
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.5938

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.64981 | val 0.71563
  Epoch 013 - train 0.60933 | val 0.72705
  Classification -> best τ=0.560 (val F1=0.1407)
  Directional -> Accuracy: 0.5476, MCC: 0.0000, F1: 0.6780

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.54301 | val 0.96850
  Epoch 011 - train 0.52494 | val 1.01498
  Classification -> best τ=0.410 (val F1=0.3689)
  Directional -> Accuracy: 0.4464, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.57549 | val 1.68885
  Epoch 012 - train 0.53057 | val 1.40146
  Classification -> best τ=0.540 (val F1=0.3427)
  Directional -> Accuracy: 0.6000, MCC: 0.1830, F1: 0.7143

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.64290 | val 0.77911
  Epoch 013 - train 0.61312 | val 0.83523
  Classification -> best τ=0.540 (val F1=0.3501)
  Directional -> Accuracy: 0.5238, MCC: 0.0500, F1: 0.5238

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.62150 | val 1.00122
  Epoch 015 - train 0.60044 | val 0.87943
  Classification -> best τ=0.490 (val F1=0.1286)
  Directional -> Accuracy: 0.4762, MCC: 0.1419, F1: 0.0833

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.55773 | val 0.85584
  Epoch 013 - train 0.53638 | val 0.75432
  Classification -> best τ=0.310 (val F1=0.2932)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.67035 | val 0.69686
  Epoch 020 - train 0.49678 | val 1.07182
  Classification -> best τ=0.690 (val F1=0.2267)
  Directional -> Accuracy: 0.4444, MCC: 0.0000, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.61852 | val 0.99084
  Epoch 011 - train 0.53379 | val 1.00752
  Classification -> best τ=0.480 (val F1=0.2324)
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.63320 | val 0.92991
  Epoch 012 - train 0.59185 | val 1.03868
  Classification -> best τ=0.375 (val F1=0.3099)
  Directional -> Accuracy: 0.5455, MCC: 0.1165, F1: 0.5455

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.54910 | val 0.84097
  Epoch 014 - train 0.42329 | val 1.39204
  Classification -> best τ=0.490 (val F1=0.3420)
  Directional -> Accuracy: 0.6429, MCC: 0.3127, F1: 0.5946

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.54684 | val 0.85455
  Epoch 011 - train 0.55154 | val 0.89790
  Classification -> best τ=0.480 (val F1=0.2327)
  Directional -> Accuracy: 0.6250, MCC: 0.2774, F1: 0.6557

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.53574 | val 1.07187
  Epoch 011 - train 0.54412 | val 1.01748
  Classification -> best τ=0.460 (val F1=0.2118)
  Directional -> Accuracy: 0.5435, MCC: -0.2118, F1: 0.7042

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.54506 | val 0.99473
  Epoch 013 - train 0.54951 | val 0.96551
  Classification -> best τ=0.560 (val F1=0.4011)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.61002 | val 1.01637
  Epoch 012 - train 0.58925 | val 1.42607
  Classification -> best τ=0.340 (val F1=0.3209)
  Directional -> Accuracy: 0.4730, MCC: -0.1202, F1: 0.6422

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.67762 | val 0.69268
  Epoch 019 - train 0.57569 | val 0.87236
  Classification -> best τ=0.495 (val F1=0.3953)
  Directional -> Accuracy: 0.4667, MCC: -0.0786, F1: 0.1429

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.59534 | val 1.26178
  Epoch 011 - train 0.51280 | val 1.29049
  Classification -> best τ=0.510 (val F1=0.3563)
  Directional -> Accuracy: 0.5952, MCC: 0.1487, F1: 0.6792

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.53913 | val 0.84832
  Epoch 012 - train 0.51087 | val 0.86791
  Classification -> best τ=0.520 (val F1=0.3752)
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.5455

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.65708 | val 0.69787
  Epoch 018 - train 0.64480 | val 0.74757
  Classification -> best τ=0.545 (val F1=0.2036)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.56978 | val 1.98315
  Epoch 011 - train 0.53001 | val 2.28366
  Classification -> best τ=0.615 (val F1=0.3246)
  Directional -> Accuracy: 0.4643, MCC: -0.0675, F1: 0.6053

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.66861 | val 0.67456
  Epoch 020 - train 0.60447 | val 0.77105
  Epoch 021 - train 0.64207 | val 0.71914
  Classification -> best τ=0.565 (val F1=0.4058)
  Directional -> Accuracy: 0.4906, MCC: -0.0172, F1: 0.4706

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.64905 | val 3.24143
  Epoch 011 - train 0.60148 | val 2.72829
  Classification -> best τ=0.500 (val F1=0.0080)
  Directional -> Accuracy: 0.5091, MCC: -0.0251, F1: 0.6400

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.66438 | val 0.82197
  Epoch 020 - train 0.61779 | val 0.73135

[I 2026-02-22 17:12:33,937] Trial 259 finished with value: 0.2707037716750775 and parameters: {'feature_set': 'sector', 'model_type': 'BiLSTM', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.5, 'batch_size': 16, 'learning_rate': 0.005690490352915032, 'weight_decay': 0.0003732191964413375, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 1.1253187426447178, 'early_stopping_min_delta': 0.0020364416646523544}. Best is trial 252 with value: 0.3108162738957727.

  Epoch 022 - train 0.58519 | val 0.74937
  Classification -> best τ=0.410 (val F1=0.2920)
  Directional -> Accuracy: 0.5667, MCC: 0.1541, F1: 0.3158

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2707037716750775
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.63569 | val 0.97903
  Epoch 019 - train 0.64120 | val 1.22350
  Classification -> best τ=0.910 (val F1=0.2510)
  Directional -> Accuracy: 0.5526, MCC: 0.0000, F1: 0.0000

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.55657 | val 0.78485
  Epoch 012 - train 0.56660 | val 0.77022
  Classification -> best τ=0.560 (val F1=0.1297)
  Directional -> Accuracy: 0.6444, MCC: 0.2545, F1: 0.7143

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.65129 | val 1.08032
  Epoch 011 - train 0.62582 | val 1.06940
  Classification -> best τ=0.620 (val F1=0.3589)
  Directional -> Accuracy: 0.4565, MCC: -0.1557, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.65313 | val 0.85057
  Epoch 011 - train 0.64763 | val 1.00596
  Classification -> best τ=0.385 (val F1=0.2403)
  Directional -> Accuracy: 0.4595, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.62292 | val 0.68853
  Epoch 019 - train 0.53136 | val 1.08407
  Classification -> best τ=0.685 (val F1=0.5250)
  Directional -> Accuracy: 0.6000, MCC: 0.2587, F1: 0.4737

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.62816 | val 0.69646
  Epoch 013 - train 0.54999 | val 0.72287
  Classification -> best τ=0.450 (val F1=0.2937)
  Directional -> Accuracy: 0.5217, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.65367 | val 0.75981
  Epoch 014 - train 0.62726 | val 0.75975
  Classification -> best τ=0.470 (val F1=0.2753)
  Directional -> Accuracy: 0.5147, MCC: 0.0425, F1: 0.4762

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.55230 | val 0.56264
  Epoch 020 - train 0.48653 | val 0.52936
  Epoch 021 - train 0.43943 | val 0.57426
  Classification -> best τ=0.265 (val F1=0.5247)
  Directional -> Accuracy: 0.5238, MCC: 0.0694, F1: 0.5238

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.63905 | val 1.06550
  Epoch 012 - train 0.63131 | val 0.80965
  Classification -> best τ=0.465 (val F1=0.2443)
  Directional -> Accuracy: 0.5833, MCC: 0.1852, F1: 0.5833

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.63877 | val 0.81461
  Epoch 011 - train 0.61596 | val 0.83322
  Classification -> best τ=0.465 (val F1=0.1667)
  Directional -> Accuracy: 0.4638, MCC: -0.0301, F1: 0.4932

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.70973 | val 0.68889
  Epoch 013 - train 0.60747 | val 0.85710
  Classification -> best τ=0.445 (val F1=0.3005)
  Directional -> Accuracy: 0.6122, MCC: 0.2379, F1: 0.2963

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.66703 | val 0.77794
  Epoch 011 - train 0.64930 | val 0.79318
  Classification -> best τ=0.485 (val F1=0.1053)
  Directional -> Accuracy: 0.5614, MCC: 0.1669, F1: 0.6835

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.54427 | val 0.74152
  Epoch 013 - train 0.64740 | val 0.67717
  Classification -> best τ=0.585 (val F1=0.3125)
  Directional -> Accuracy: 0.5238, MCC: -0.0387, F1: 0.1667

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.67648 | val 0.72677
  Epoch 011 - train 0.64163 | val 0.69240
  Classification -> best τ=0.550 (val F1=0.3268)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.61139 | val 0.69717
  Epoch 012 - train 0.61345 | val 0.72041
  Classification -> best τ=0.585 (val F1=0.2549)
  Directional -> Accuracy: 0.5490, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.64836 | val 0.77070
  Epoch 016 - train 0.61678 | val 1.10324
  Classification -> best τ=0.385 (val F1=0.2795)
  Directional -> Accuracy: 0.5362, MCC: 0.0000, F1: 0.6981

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.67050 | val 0.68380
  Epoch 017 - train 0.63967 | val 0.69837
  Classification -> best τ=0.525 (val F1=0.2620)
  Directional -> Accuracy: 0.4655, MCC: -0.2183, F1: 0.6076

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.66580 | val 0.69016
  Epoch 012 - train 0.62590 | val 0.74660
  Classification -> best τ=0.430 (val F1=0.2305)
  Directional -> Accuracy: 0.5333, MCC: -0.0118, F1: 0.6392

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.63468 | val 0.76752
  Epoch 011 - train 0.60491 | val 0.87208
  Classification -> best τ=0.420 (val F1=0.2166)
  Directional -> Accuracy: 0.5469, MCC: 0.2224, F1: 0.4314

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.61457 | val 0.90068
  Epoch 011 - train 0.56167 | val 0.99985
  Classification -> best τ=0.660 (val F1=0.2701)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.62721 | val 0.79863
  Epoch 011 - train 0.61434 | val 0.99548
  Classification -> best τ=0.545 (val F1=0.1978)
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.67069 | val 0.80671
  Epoch 011 - train 0.64647 | val 0.89634
  Classification -> best τ=0.540 (val F1=0.3107)
  Directional -> Accuracy: 0.4923, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.63069 | val 0.87380
  Epoch 017 - train 0.63049 | val 0.67678
  Classification -> best τ=0.705 (val F1=0.3550)
  Directional -> Accuracy: 0.5263, MCC: 0.1125, F1: 0.4490

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.65583 | val 0.73019
  Epoch 020 - train 0.61640 | val 0.71892
  Epoch 022 - train 0.64428 | val 0.72366
  Classification -> best τ=0.370 (val F1=0.2111)
  Directional -> Accuracy: 0.4615, MCC: -0.0836, F1: 0.6237

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.60994 | val 0.67013
  Epoch 018 - train 0.55243 | val 0.70949
  Classification -> best τ=0.485 (val F1=0.5312)
  Directional -> Accuracy: 0.5818, MCC: 0.2155, F1: 0.5106

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.59346 | val 0.87080
  Epoch 011 - train 0.53854 | val 1.07323
  Classification -> best τ=0.540 (val F1=0.2726)
  Directional -> Accuracy: 0.5556, MCC: -0.0159, F1: 0.1667

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.69174 | val 0.70989
  Epoch 011 - train 0.66968 | val 0.69985
  Classification -> best τ=0.530 (val F1=0.1667)
  Directional -> Accuracy: 0.5476, MCC: -0.0534, F1: 0.6984

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.63980 | val 1.22277
  Epoch 012 - train 0.53400 | val 1.17257
  Classification -> best τ=0.390 (val F1=0.3192)
  Directional -> Accuracy: 0.4821, MCC: 0.1728, F1: 0.1212

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.57020 | val 1.00420
  Epoch 011 - train 0.55927 | val 0.94334
  Classification -> best τ=0.570 (val F1=0.2267)
  Directional -> Accuracy: 0.5750, MCC: 0.1770, F1: 0.7213

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.65046 | val 0.72693
  Epoch 011 - train 0.62078 | val 0.77810
  Classification -> best τ=0.505 (val F1=0.0296)
  Directional -> Accuracy: 0.5714, MCC: 0.1409, F1: 0.5500

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.71770 | val 0.67115
  Epoch 020 - train 0.56471 | val 0.90068
  Classification -> best τ=0.620 (val F1=0.2298)
  Directional -> Accuracy: 0.5000, MCC: 0.2032, F1: 0.1600

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.56807 | val 0.81983
  Epoch 012 - train 0.53061 | val 1.02860
  Classification -> best τ=0.405 (val F1=0.3502)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.63787 | val 0.95123
  Epoch 016 - train 0.59053 | val 0.75649
  Classification -> best τ=0.555 (val F1=0.3008)
  Directional -> Accuracy: 0.4722, MCC: 0.0949, F1: 0.1364

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.59466 | val 0.75439
  Epoch 012 - train 0.61657 | val 1.02305
  Classification -> best τ=0.520 (val F1=0.2151)
  Directional -> Accuracy: 0.6279, MCC: 0.3713, F1: 0.3846

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.64326 | val 0.85508
  Epoch 017 - train 0.59417 | val 1.01573
  Classification -> best τ=0.375 (val F1=0.3280)
  Directional -> Accuracy: 0.5000, MCC: 0.1961, F1: 0.2667

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.58802 | val 0.94441
  Epoch 016 - train 0.46152 | val 1.32414
  Classification -> best τ=0.485 (val F1=0.3420)
  Directional -> Accuracy: 0.6905, MCC: 0.3877, F1: 0.6829

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.64591 | val 1.08988
  Epoch 012 - train 0.56913 | val 0.78648
  Classification -> best τ=0.475 (val F1=0.2114)
  Directional -> Accuracy: 0.4821, MCC: -0.0185, F1: 0.5246

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.61725 | val 0.67468
  Epoch 020 - train 0.45375 | val 0.85693
  Classification -> best τ=0.595 (val F1=0.2924)
  Directional -> Accuracy: 0.5870, MCC: 0.0062, F1: 0.7246

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.66024 | val 0.98616
  Epoch 015 - train 0.56186 | val 0.90341
  Classification -> best τ=0.570 (val F1=0.4688)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.60154 | val 1.42550
  Epoch 011 - train 0.55208 | val 1.37282
  Classification -> best τ=0.435 (val F1=0.2795)
  Directional -> Accuracy: 0.5270, MCC: 0.0549, F1: 0.1860

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.65495 | val 0.69394
  Epoch 020 - train 0.57525 | val 0.68075
  Epoch 028 - train 0.51551 | val 0.68987
  Classification -> best τ=0.445 (val F1=0.3873)
  Directional -> Accuracy: 0.4667, MCC: -0.0667, F1: 0.2500

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.54233 | val 0.72680
  Epoch 019 - train 0.29192 | val 1.97973
  Classification -> best τ=0.410 (val F1=0.4001)
  Directional -> Accuracy: 0.5476, MCC: 0.0700, F1: 0.6122

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.62516 | val 0.66062
  Epoch 020 - train 0.46662 | val 0.57793
  Epoch 029 - train 0.35240 | val 0.63701
  Classification -> best τ=0.130 (val F1=0.3752)
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.5455

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.65306 | val 0.91682
  Epoch 011 - train 0.66064 | val 0.89558
  Classification -> best τ=0.440 (val F1=0.2448)
  Directional -> Accuracy: 0.5273, MCC: 0.0000, F1: 0.6486

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.61386 | val 1.56209
  Epoch 011 - train 0.57347 | val 1.73162
  Classification -> best τ=0.715 (val F1=0.3818)
  Directional -> Accuracy: 0.5179, MCC: 0.0333, F1: 0.4906

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.70036 | val 0.75559
  Epoch 020 - train 0.66925 | val 0.79335
  Epoch 023 - train 0.66717 | val 0.69683
  Classification -> best τ=0.515 (val F1=0.2762)
  Directional -> Accuracy: 0.5472, MCC: 0.1483, F1: 0.6842

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.61094 | val 2.24813
  Epoch 012 - train 0.58041 | val 1.37926
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5273, MCC: 0.0000, F1: 0.6905

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.68014 | val 0.67263
  Epoch 020 - train 0.64989 | val 0.66341

[I 2026-02-22 17:17:45,878] Trial 260 finished with value: 0.2819726946734776 and parameters: {'feature_set': 'sector', 'model_type': 'BiLSTM', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.5, 'batch_size': 16, 'learning_rate': 0.009974535338984644, 'weight_decay': 0.0005831902329792303, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 1.0186740725328818, 'early_stopping_min_delta': 0.00298829956704625}. Best is trial 252 with value: 0.3108162738957727.

  Epoch 030 - train 0.62614 | val 0.69518
  Classification -> best τ=0.690 (val F1=0.2623)
  Directional -> Accuracy: 0.5167, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2819726946734776
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.67086 | val 0.80698
  Epoch 014 - train 0.63712 | val 0.89495
  Classification -> best τ=0.630 (val F1=0.2919)
  Directional -> Accuracy: 0.5395, MCC: -0.0120, F1: 0.1463

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.67250 | val 0.70816
  Epoch 013 - train 0.66496 | val 0.75919
  Classification -> best τ=0.470 (val F1=0.1297)
  Directional -> Accuracy: 0.5778, MCC: 0.0340, F1: 0.7246

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.69608 | val 0.67842
  Epoch 019 - train 0.63584 | val 0.70496
  Classification -> best τ=0.515 (val F1=0.3212)
  Directional -> Accuracy: 0.5217, MCC: 0.1410, F1: 0.2143

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.69098 | val 0.88471
  Epoch 011 - train 0.66814 | val 0.98327
  Classification -> best τ=0.495 (val F1=0.0721)
  Directional -> Accuracy: 0.4865, MCC: 0.0752, F1: 0.1739

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.68126 | val 0.69076
  Epoch 017 - train 0.65051 | val 0.65380
  Classification -> best τ=0.640 (val F1=0.4291)
  Directional -> Accuracy: 0.6200, MCC: 0.3459, F1: 0.4571

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.64555 | val 0.72597
  Epoch 011 - train 0.61533 | val 0.76445
  Classification -> best τ=0.500 (val F1=0.0890)
  Directional -> Accuracy: 0.5217, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.67118 | val 0.85744
  Epoch 012 - train 0.66902 | val 1.03391
  Classification -> best τ=0.435 (val F1=0.2756)
  Directional -> Accuracy: 0.3971, MCC: -0.0526, F1: 0.5495

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.67794 | val 0.60807
  Epoch 020 - train 0.64600 | val 0.70107
  Epoch 023 - train 0.61229 | val 0.65799
  Classification -> best τ=0.215 (val F1=0.2810)
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.65125 | val 0.78535
  Epoch 011 - train 0.69241 | val 0.74847
  Classification -> best τ=0.540 (val F1=0.2927)
  Directional -> Accuracy: 0.6250, MCC: 0.2208, F1: 0.5000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.67199 | val 0.69072
  Epoch 019 - train 0.66090 | val 0.82231
  Classification -> best τ=0.500 (val F1=0.2362)
  Directional -> Accuracy: 0.4203, MCC: -0.0401, F1: 0.5745

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.65103 | val 0.94898
  Epoch 011 - train 0.65529 | val 0.93776
  Classification -> best τ=0.525 (val F1=0.2101)
  Directional -> Accuracy: 0.4694, MCC: -0.0317, F1: 0.5185

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.69411 | val 0.67847
  Epoch 013 - train 0.69954 | val 0.68784
  Classification -> best τ=0.650 (val F1=0.2083)
  Directional -> Accuracy: 0.5439, MCC: 0.1248, F1: 0.3500

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.62210 | val 0.69243
  Epoch 020 - train 0.57871 | val 0.69119
  Epoch 030 - train 0.56493 | val 0.65932
  Classification -> best τ=0.575 (val F1=0.3114)
  Directional -> Accuracy: 0.6190, MCC: 0.2781, F1: 0.6522

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.69344 | val 0.67990
  Epoch 019 - train 0.69709 | val 0.65645
  Classification -> best τ=0.440 (val F1=0.2687)
  Directional -> Accuracy: 0.5667, MCC: 0.1361, F1: 0.6061

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.64206 | val 1.10465
  Epoch 011 - train 0.68141 | val 0.96234
  Classification -> best τ=0.645 (val F1=0.1556)
  Directional -> Accuracy: 0.5490, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.67010 | val 0.66342
  Epoch 014 - train 0.65780 | val 0.73530
  Classification -> best τ=0.810 (val F1=0.3679)
  Directional -> Accuracy: 0.5217, MCC: 0.1200, F1: 0.3265

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.66946 | val 0.93444
  Epoch 011 - train 0.67084 | val 1.03717
  Classification -> best τ=0.505 (val F1=0.2207)
  Directional -> Accuracy: 0.6207, MCC: 0.1535, F1: 0.7179

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.68267 | val 0.77835
  Epoch 011 - train 0.64567 | val 0.72923
  Classification -> best τ=0.520 (val F1=0.2220)
  Directional -> Accuracy: 0.4000, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.66837 | val 0.73260
  Epoch 018 - train 0.61576 | val 0.73207
  Classification -> best τ=0.350 (val F1=0.2843)
  Directional -> Accuracy: 0.4844, MCC: 0.0299, F1: 0.4211

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.63244 | val 0.91152
  Epoch 011 - train 0.60414 | val 1.13665
  Classification -> best τ=0.520 (val F1=0.3161)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.69046 | val 0.69339
  Epoch 016 - train 0.65172 | val 0.68045
  Classification -> best τ=0.495 (val F1=0.3878)
  Directional -> Accuracy: 0.4894, MCC: 0.0465, F1: 0.4783

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.68442 | val 0.70850
  Epoch 016 - train 0.66983 | val 0.72192
  Classification -> best τ=0.405 (val F1=0.2281)
  Directional -> Accuracy: 0.4462, MCC: -0.1114, F1: 0.3077

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.66566 | val 0.74316
  Epoch 014 - train 0.68717 | val 0.70900
  Classification -> best τ=0.650 (val F1=0.4376)
  Directional -> Accuracy: 0.4737, MCC: 0.0518, F1: 0.2500

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.68849 | val 0.67741
  Epoch 020 - train 0.66714 | val 0.75131
  Classification -> best τ=0.640 (val F1=0.2055)
  Directional -> Accuracy: 0.5077, MCC: -0.0202, F1: 0.2381

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.66599 | val 0.87841
  Epoch 014 - train 0.66103 | val 0.75860
  Classification -> best τ=0.380 (val F1=0.4839)
  Directional -> Accuracy: 0.5091, MCC: 0.0267, F1: 0.5091

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.64342 | val 1.02003
  Epoch 011 - train 0.65277 | val 1.10068
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.5938

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.68865 | val 0.70327
  Epoch 017 - train 0.65775 | val 0.70781
  Classification -> best τ=0.540 (val F1=0.0700)
  Directional -> Accuracy: 0.5000, MCC: -0.1291, F1: 0.6441

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.68199 | val 0.84402
  Epoch 012 - train 0.67709 | val 0.82130
  Classification -> best τ=0.545 (val F1=0.2724)
  Directional -> Accuracy: 0.4464, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.66478 | val 0.72852
  Epoch 011 - train 0.65279 | val 0.78232
  Classification -> best τ=0.525 (val F1=0.2403)
  Directional -> Accuracy: 0.5500, MCC: 0.1111, F1: 0.5500

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.69122 | val 0.75660
  Epoch 019 - train 0.64776 | val 1.03596
  Classification -> best τ=0.565 (val F1=0.2814)
  Directional -> Accuracy: 0.4762, MCC: -0.0674, F1: 0.3529

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.67835 | val 0.80703
  Epoch 018 - train 0.66358 | val 0.70753
  Classification -> best τ=0.600 (val F1=0.2273)
  Directional -> Accuracy: 0.5714, MCC: 0.2150, F1: 0.4706

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.65813 | val 0.75948
  Epoch 012 - train 0.64578 | val 0.78510
  Classification -> best τ=0.475 (val F1=0.3196)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.69917 | val 0.66690
  Epoch 013 - train 0.68577 | val 0.69152
  Classification -> best τ=0.465 (val F1=0.3610)
  Directional -> Accuracy: 0.5417, MCC: 0.1155, F1: 0.5075

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.68309 | val 0.68929
  Epoch 020 - train 0.66640 | val 1.05970
  Epoch 021 - train 0.68819 | val 1.09917
  Classification -> best τ=0.445 (val F1=0.1027)
  Directional -> Accuracy: 0.5349, MCC: 0.2158, F1: 0.6774

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.65028 | val 0.78268
  Epoch 014 - train 0.62788 | val 0.77008
  Classification -> best τ=0.185 (val F1=0.3280)
  Directional -> Accuracy: 0.5303, MCC: 0.1729, F1: 0.4151

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.61129 | val 0.79277
  Epoch 017 - train 0.59829 | val 0.84499
  Classification -> best τ=0.540 (val F1=0.2618)
  Directional -> Accuracy: 0.6429, MCC: 0.3511, F1: 0.5455

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.66332 | val 0.71324
  Epoch 011 - train 0.60801 | val 0.74107
  Classification -> best τ=0.440 (val F1=0.1126)
  Directional -> Accuracy: 0.4464, MCC: -0.0801, F1: 0.5753

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.65534 | val 0.76070
  Epoch 019 - train 0.60694 | val 0.97978
  Classification -> best τ=0.590 (val F1=0.3372)
  Directional -> Accuracy: 0.4565, MCC: 0.0917, F1: 0.2857

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.63748 | val 0.67195
  Epoch 016 - train 0.60317 | val 0.70121
  Classification -> best τ=0.390 (val F1=0.4242)
  Directional -> Accuracy: 0.3750, MCC: 0.1080, F1: 0.5312

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.64788 | val 0.76081
  Epoch 011 - train 0.64837 | val 0.81711
  Classification -> best τ=0.420 (val F1=0.3031)
  Directional -> Accuracy: 0.4865, MCC: 0.0000, F1: 0.6545

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.67569 | val 0.71422
  Epoch 017 - train 0.64978 | val 0.70203
  Classification -> best τ=0.440 (val F1=0.2582)
  Directional -> Accuracy: 0.5333, MCC: 0.0653, F1: 0.5532

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.59929 | val 1.03460
  Epoch 013 - train 0.64084 | val 0.76248
  Classification -> best τ=0.495 (val F1=0.3015)
  Directional -> Accuracy: 0.6190, MCC: 0.1936, F1: 0.7143

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.67149 | val 0.75581
  Epoch 013 - train 0.60662 | val 0.78148
  Classification -> best τ=0.580 (val F1=0.1306)
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.5455

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.68739 | val 0.99847
  Epoch 015 - train 0.68139 | val 0.80851
  Classification -> best τ=0.500 (val F1=0.2661)
  Directional -> Accuracy: 0.5455, MCC: 0.1826, F1: 0.3902

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.64112 | val 1.09136
  Epoch 011 - train 0.62630 | val 1.22470
  Classification -> best τ=0.605 (val F1=0.2811)
  Directional -> Accuracy: 0.5179, MCC: 0.0413, F1: 0.5424

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.69490 | val 0.72620
  Epoch 015 - train 0.66831 | val 0.69891
  Classification -> best τ=0.685 (val F1=0.1893)
  Directional -> Accuracy: 0.4906, MCC: -0.0484, F1: 0.6301

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.63605 | val 2.22385
  Epoch 012 - train 0.62029 | val 2.15470
  Classification -> best τ=0.600 (val F1=0.0523)
  Directional -> Accuracy: 0.5273, MCC: 0.0000, F1: 0.6905

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.67720 | val 0.68244
  Epoch 020 - train 0.64659 | val 0.74159

[I 2026-02-22 17:22:56,784] Trial 261 finished with value: 0.2539954617783606 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.5, 'batch_size': 16, 'learning_rate': 0.0077067947517156605, 'weight_decay': 0.0002445527025432964, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 0.3473564158401234, 'early_stopping_min_delta': 0.002486882583209175}. Best is trial 252 with value: 0.3108162738957727.

  Epoch 021 - train 0.65111 | val 0.77501
  Classification -> best τ=0.510 (val F1=0.3448)
  Directional -> Accuracy: 0.5167, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2539954617783606
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'emotion_anger', 'emotion_disgust', 'emotion_fear', 'emotion_joy', 'emotion_neutral', 'emotion_sadness', 'emotion_surprize', 'emotion_anger_pct', 'emotion_disgust_pct', 'emotion_fear_pct', 'emotion_joy_pct', 'emotion_neutral_pct', 'emotion_sadness_pct', 'emotion_surprize_pct']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.60421 | val 0.71158
  Epoch 013 - train 0.53306 | val 0.75089
  Classification -> best τ=0.450 (val F1=0.2759)
  Directional -> Accuracy: 0.5132, MCC: -0.0104, F1: 0.3729

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.47104 | val 1.15463
  Epoch 011 - train 0.41181 | val 1.46594
  Classification -> best τ=0.540 (val F1=0.1273)
  Directional -> Accuracy: 0.6889, MCC: 0.3779, F1: 0.7812

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.61147 | val 0.75265
  Epoch 011 - train 0.60674 | val 0.77509
  Classification -> best τ=0.535 (val F1=0.2427)
  Directional -> Accuracy: 0.5000, MCC: 0.0421, F1: 0.2581

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.59954 | val 1.01060
  Epoch 011 - train 0.59454 | val 0.98490
  Classification -> best τ=0.430 (val F1=0.2195)
  Directional -> Accuracy: 0.5000, MCC: 0.1401, F1: 0.1778

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.48397 | val 0.84181
  Epoch 012 - train 0.40858 | val 0.95657
  Classification -> best τ=0.640 (val F1=0.3933)
  Directional -> Accuracy: 0.6000, MCC: 0.2587, F1: 0.4737

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.44930 | val 1.30212
  Epoch 011 - train 0.42532 | val 1.35800
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4783, MCC: 0.0000, F1: 0.6471

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.61721 | val 0.86031
  Epoch 011 - train 0.55454 | val 0.96682
  Classification -> best τ=0.510 (val F1=0.3208)
  Directional -> Accuracy: 0.4412, MCC: -0.0669, F1: 0.4571

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.47538 | val 1.09337
  Epoch 011 - train 0.45188 | val 1.76568
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.51022 | val 2.04001
  Epoch 011 - train 0.43337 | val 2.06909
  Classification -> best τ=0.550 (val F1=0.2764)
  Directional -> Accuracy: 0.5625, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.60564 | val 0.75188
  Epoch 011 - train 0.58133 | val 0.76975
  Classification -> best τ=0.430 (val F1=0.3302)
  Directional -> Accuracy: 0.3768, MCC: -0.2504, F1: 0.5474

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.56878 | val 1.26054
  Epoch 011 - train 0.53841 | val 1.48936
  Classification -> best τ=0.545 (val F1=0.1593)
  Directional -> Accuracy: 0.5510, MCC: 0.0584, F1: 0.3529

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.59244 | val 0.94617
  Epoch 015 - train 0.53546 | val 1.28412
  Classification -> best τ=0.670 (val F1=0.2083)
  Directional -> Accuracy: 0.5439, MCC: 0.1159, F1: 0.3810

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.48191 | val 1.00340
  Epoch 013 - train 0.38366 | val 1.24965
  Classification -> best τ=0.615 (val F1=0.1754)
  Directional -> Accuracy: 0.5476, MCC: 0.0535, F1: 0.3448

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.63143 | val 0.67800
  Epoch 020 - train 0.50326 | val 0.76777
  Epoch 022 - train 0.41302 | val 0.78809
  Classification -> best τ=0.285 (val F1=0.2054)
  Directional -> Accuracy: 0.4667, MCC: -0.0833, F1: 0.5897

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.56307 | val 0.92799
  Epoch 012 - train 0.54328 | val 0.83567
  Classification -> best τ=0.530 (val F1=0.3079)
  Directional -> Accuracy: 0.5098, MCC: -0.1178, F1: 0.0741

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.59887 | val 0.78974
  Epoch 014 - train 0.52479 | val 0.94577
  Classification -> best τ=0.645 (val F1=0.3063)
  Directional -> Accuracy: 0.5942, MCC: 0.1922, F1: 0.6000

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.59654 | val 1.05567
  Epoch 012 - train 0.57872 | val 1.44380
  Classification -> best τ=0.620 (val F1=0.0732)
  Directional -> Accuracy: 0.3793, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.58502 | val 0.91567
  Epoch 011 - train 0.57552 | val 0.94563
  Classification -> best τ=0.525 (val F1=0.1612)
  Directional -> Accuracy: 0.4133, MCC: 0.0949, F1: 0.0435

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.54245 | val 0.82726
  Epoch 011 - train 0.52112 | val 0.94608
  Classification -> best τ=0.625 (val F1=0.2234)
  Directional -> Accuracy: 0.4531, MCC: 0.0899, F1: 0.1463

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.60639 | val 0.97447
  Epoch 011 - train 0.57695 | val 0.87981
  Classification -> best τ=0.505 (val F1=0.3460)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.53141 | val 0.93135
  Epoch 011 - train 0.47936 | val 1.04829
  Classification -> best τ=0.545 (val F1=0.1572)
  Directional -> Accuracy: 0.6170, MCC: 0.0000, F1: 0.7632

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.62395 | val 0.83472
  Epoch 011 - train 0.60368 | val 0.80771
  Classification -> best τ=0.430 (val F1=0.1610)
  Directional -> Accuracy: 0.6154, MCC: 0.2656, F1: 0.5098

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.61071 | val 0.72539
  Epoch 019 - train 0.45290 | val 1.00322
  Classification -> best τ=0.505 (val F1=0.3382)
  Directional -> Accuracy: 0.5439, MCC: 0.0420, F1: 0.6389

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.59810 | val 1.35339
  Epoch 013 - train 0.52673 | val 0.82185
  Classification -> best τ=0.335 (val F1=0.1855)
  Directional -> Accuracy: 0.5231, MCC: 0.0719, F1: 0.5974

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.54988 | val 1.83864
  Epoch 014 - train 0.49281 | val 2.09963
  Classification -> best τ=0.475 (val F1=0.4207)
  Directional -> Accuracy: 0.4545, MCC: -0.0803, F1: 0.4444

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.41321 | val 2.33373
  Epoch 011 - train 0.34249 | val 2.64380
  Classification -> best τ=0.510 (val F1=0.3315)
  Directional -> Accuracy: 0.4889, MCC: -0.2029, F1: 0.0800

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.51846 | val 1.42036
  Epoch 015 - train 0.49155 | val 1.73306
  Classification -> best τ=0.510 (val F1=0.1578)
  Directional -> Accuracy: 0.5238, MCC: 0.0142, F1: 0.6000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.56111 | val 1.01882
  Epoch 011 - train 0.54764 | val 0.99151
  Classification -> best τ=0.450 (val F1=0.1815)
  Directional -> Accuracy: 0.4643, MCC: 0.1211, F1: 0.0625

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.53968 | val 1.09571
  Epoch 014 - train 0.46092 | val 0.98661
  Classification -> best τ=0.545 (val F1=0.2774)
  Directional -> Accuracy: 0.3500, MCC: -0.3237, F1: 0.0714

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.61691 | val 0.84559
  Epoch 011 - train 0.58628 | val 0.84107
  Classification -> best τ=0.595 (val F1=0.1959)
  Directional -> Accuracy: 0.5238, MCC: 0.0000, F1: 0.0000

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.52826 | val 2.54791
  Epoch 011 - train 0.54298 | val 2.27836
  Classification -> best τ=0.475 (val F1=0.3036)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.55260 | val 0.88363
  Epoch 011 - train 0.51444 | val 0.91572
  Classification -> best τ=0.510 (val F1=0.3987)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.67266 | val 0.67754
  Epoch 013 - train 0.63422 | val 0.69191
  Classification -> best τ=0.600 (val F1=0.2637)
  Directional -> Accuracy: 0.4306, MCC: -0.1327, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.53482 | val 1.70786
  Epoch 011 - train 0.51257 | val 1.91862
  Classification -> best τ=0.495 (val F1=0.1309)
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.57621 | val 1.28212
  Epoch 013 - train 0.45272 | val 1.13715
  Classification -> best τ=0.290 (val F1=0.4160)
  Directional -> Accuracy: 0.4545, MCC: -0.0784, F1: 0.4706

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.45692 | val 1.28843
  Epoch 012 - train 0.25001 | val 0.98253
  Classification -> best τ=0.540 (val F1=0.2618)
  Directional -> Accuracy: 0.5714, MCC: 0.2197, F1: 0.4000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.59055 | val 0.77941
  Epoch 012 - train 0.58758 | val 0.81662
  Classification -> best τ=0.480 (val F1=0.2530)
  Directional -> Accuracy: 0.5179, MCC: 0.0283, F1: 0.4706

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.54403 | val 1.20192
  Epoch 011 - train 0.39389 | val 1.14946
  Classification -> best τ=0.485 (val F1=0.3024)
  Directional -> Accuracy: 0.4348, MCC: -0.1055, F1: 0.4583

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.47146 | val 0.99585
  Epoch 012 - train 0.30932 | val 0.92532
  Classification -> best τ=0.625 (val F1=0.2392)
  Directional -> Accuracy: 0.6042, MCC: 0.1462, F1: 0.4571

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.56507 | val 1.45471
  Epoch 011 - train 0.57799 | val 1.25597
  Classification -> best τ=0.510 (val F1=0.1721)
  Directional -> Accuracy: 0.5811, MCC: 0.1754, F1: 0.4151

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.58235 | val 0.83898
  Epoch 012 - train 0.60835 | val 0.83603
  Classification -> best τ=0.415 (val F1=0.2697)
  Directional -> Accuracy: 0.5111, MCC: 0.0000, F1: 0.6765

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.40562 | val 0.84303
  Epoch 011 - train 0.34698 | val 0.87399
  Classification -> best τ=0.510 (val F1=0.1667)
  Directional -> Accuracy: 0.6429, MCC: 0.2582, F1: 0.7458

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.51834 | val 1.09844
  Epoch 014 - train 0.37820 | val 1.16286
  Classification -> best τ=0.570 (val F1=0.2605)
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.5455

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.59065 | val 1.08532
  Epoch 012 - train 0.56684 | val 1.09479
  Classification -> best τ=0.610 (val F1=0.2036)
  Directional -> Accuracy: 0.4545, MCC: -0.0256, F1: 0.1176

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.56535 | val 1.79029
  Epoch 012 - train 0.43189 | val 2.05368
  Classification -> best τ=0.530 (val F1=0.3236)
  Directional -> Accuracy: 0.5179, MCC: 0.1857, F1: 0.6667

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.65593 | val 0.97951
  Epoch 012 - train 0.60598 | val 1.10461
  Classification -> best τ=0.485 (val F1=0.0350)
  Directional -> Accuracy: 0.5094, MCC: 0.0185, F1: 0.5185

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.57832 | val 1.63054
  Epoch 011 - train 0.57160 | val 1.63586
  Classification -> best τ=0.550 (val F1=0.3238)
  Directional -> Accuracy: 0.5455, MCC: 0.0933, F1: 0.6914

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.63656 | val 0.72419

[I 2026-02-22 17:27:26,728] Trial 262 finished with value: 0.23517867197389095 and parameters: {'feature_set': 'emotion', 'model_type': 'BiLSTM', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.5, 'batch_size': 16, 'learning_rate': 0.006581571011196285, 'weight_decay': 0.0002660265449706565, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 0.9947134392772696, 'early_stopping_min_delta': 0.001976702586005342}. Best is trial 252 with value: 0.3108162738957727.

  Epoch 013 - train 0.56339 | val 0.68562
  Classification -> best τ=0.410 (val F1=0.2052)
  Directional -> Accuracy: 0.5833, MCC: 0.1638, F1: 0.5098

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.23517867197389095
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.65717 | val 1.32459
  Epoch 011 - train 0.61676 | val 1.36777
  Classification -> best τ=0.745 (val F1=0.2510)
  Directional -> Accuracy: 0.5789, MCC: 0.1259, F1: 0.4286

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.57562 | val 1.07247
  Epoch 016 - train 0.47961 | val 0.86050
  Classification -> best τ=0.880 (val F1=0.1323)
  Directional -> Accuracy: 0.6222, MCC: 0.2204, F1: 0.6792

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.59702 | val 0.76091
  Epoch 012 - train 0.60782 | val 0.80110
  Classification -> best τ=0.610 (val F1=0.1978)
  Directional -> Accuracy: 0.5217, MCC: 0.1124, F1: 0.2667

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.61607 | val 0.92345
  Epoch 013 - train 0.60702 | val 0.78656
  Classification -> best τ=0.475 (val F1=0.1426)
  Directional -> Accuracy: 0.5405, MCC: 0.0322, F1: 0.6731

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.60958 | val 0.70795
  Epoch 012 - train 0.53918 | val 0.65751
  Classification -> best τ=0.510 (val F1=0.4782)
  Directional -> Accuracy: 0.7200, MCC: 0.4423, F1: 0.7200

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.51089 | val 0.87328
  Epoch 017 - train 0.43845 | val 0.66715
  Classification -> best τ=0.545 (val F1=0.3525)
  Directional -> Accuracy: 0.5217, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.65766 | val 0.80808
  Epoch 011 - train 0.62628 | val 0.91147
  Classification -> best τ=0.580 (val F1=0.1923)
  Directional -> Accuracy: 0.5588, MCC: 0.0786, F1: 0.4444

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.55518 | val 0.57111
  Epoch 017 - train 0.37873 | val 0.84560
  Classification -> best τ=0.340 (val F1=0.6571)
  Directional -> Accuracy: 0.5238, MCC: 0.0849, F1: 0.5455

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.63153 | val 1.09928
  Epoch 011 - train 0.62824 | val 1.21375
  Classification -> best τ=0.560 (val F1=0.1928)
  Directional -> Accuracy: 0.7292, MCC: 0.4454, F1: 0.6486

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.60138 | val 0.77691
  Epoch 011 - train 0.58617 | val 0.87432
  Classification -> best τ=0.470 (val F1=0.2620)
  Directional -> Accuracy: 0.4928, MCC: 0.0017, F1: 0.4776

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.64754 | val 0.81646
  Epoch 019 - train 0.52384 | val 0.78890
  Classification -> best τ=0.415 (val F1=0.2593)
  Directional -> Accuracy: 0.5510, MCC: 0.0212, F1: 0.0833

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.62402 | val 0.91265
  Epoch 011 - train 0.61112 | val 0.99387
  Classification -> best τ=0.520 (val F1=0.2162)
  Directional -> Accuracy: 0.5088, MCC: 0.0000, F1: 0.6744

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.53092 | val 1.40479
  Epoch 015 - train 0.47885 | val 1.17544
  Classification -> best τ=0.695 (val F1=0.1754)
  Directional -> Accuracy: 0.4762, MCC: -0.1498, F1: 0.1538

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.61978 | val 0.72754
  Epoch 012 - train 0.58187 | val 0.79067
  Classification -> best τ=0.320 (val F1=0.3391)
  Directional -> Accuracy: 0.5833, MCC: 0.1675, F1: 0.5614

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.58548 | val 0.80790
  Epoch 011 - train 0.65222 | val 0.81499
  Classification -> best τ=0.545 (val F1=0.2571)
  Directional -> Accuracy: 0.5490, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.63925 | val 1.48281
  Epoch 012 - train 0.60683 | val 1.30620
  Classification -> best τ=0.250 (val F1=0.4156)
  Directional -> Accuracy: 0.5362, MCC: 0.0333, F1: 0.6596

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.61368 | val 0.99168
  Epoch 011 - train 0.55455 | val 1.01009
  Classification -> best τ=0.365 (val F1=0.2743)
  Directional -> Accuracy: 0.6379, MCC: 0.1557, F1: 0.7529

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.61972 | val 0.92443
  Epoch 020 - train 0.62012 | val 0.74559
  Epoch 022 - train 0.53907 | val 0.73655
  Classification -> best τ=0.485 (val F1=0.3546)
  Directional -> Accuracy: 0.6133, MCC: 0.1424, F1: 0.7563

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.61901 | val 0.94571
  Epoch 011 - train 0.59418 | val 1.00815
  Classification -> best τ=0.310 (val F1=0.2522)
  Directional -> Accuracy: 0.5781, MCC: 0.0000, F1: 0.7327

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.59900 | val 0.85713
  Epoch 011 - train 0.56916 | val 0.93797
  Classification -> best τ=0.520 (val F1=0.2327)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.52352 | val 0.82648
  Epoch 013 - train 0.59355 | val 0.74882
  Classification -> best τ=0.485 (val F1=0.3383)
  Directional -> Accuracy: 0.5532, MCC: -0.0497, F1: 0.6866

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.59183 | val 0.97700
  Epoch 011 - train 0.60945 | val 0.79201
  Classification -> best τ=0.550 (val F1=0.2899)
  Directional -> Accuracy: 0.5692, MCC: 0.1982, F1: 0.3636

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.65074 | val 0.63723
  Epoch 020 - train 0.53389 | val 0.61023
  Epoch 023 - train 0.54936 | val 0.61365
  Classification -> best τ=0.500 (val F1=0.5244)
  Directional -> Accuracy: 0.6316, MCC: 0.2391, F1: 0.6957

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.67065 | val 0.68633
  Epoch 015 - train 0.59386 | val 0.68185
  Classification -> best τ=0.665 (val F1=0.1985)
  Directional -> Accuracy: 0.5231, MCC: 0.0000, F1: 0.0000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.55878 | val 0.90939
  Epoch 011 - train 0.53529 | val 1.02724
  Classification -> best τ=0.405 (val F1=0.4629)
  Directional -> Accuracy: 0.5818, MCC: 0.1540, F1: 0.6230

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.59572 | val 1.47812
  Epoch 011 - train 0.54858 | val 1.80047
  Classification -> best τ=0.710 (val F1=0.1099)
  Directional -> Accuracy: 0.6000, MCC: 0.1323, F1: 0.1818

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.59120 | val 0.77280
  Epoch 016 - train 0.58498 | val 0.69653
  Classification -> best τ=0.645 (val F1=0.1353)
  Directional -> Accuracy: 0.5476, MCC: 0.1635, F1: 0.4865

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.60450 | val 0.69064
  Epoch 012 - train 0.56914 | val 0.76313
  Classification -> best τ=0.385 (val F1=0.3967)
  Directional -> Accuracy: 0.4464, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.61917 | val 0.76183
  Epoch 012 - train 0.52548 | val 0.76119
  Classification -> best τ=0.590 (val F1=0.1457)
  Directional -> Accuracy: 0.6000, MCC: 0.2010, F1: 0.7241

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.61149 | val 1.59840
  Epoch 011 - train 0.60583 | val 1.58639
  Classification -> best τ=0.520 (val F1=0.3501)
  Directional -> Accuracy: 0.4762, MCC: -0.0413, F1: 0.5000

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.56315 | val 0.65902
  Epoch 020 - train 0.48570 | val 1.18742
  Classification -> best τ=0.480 (val F1=0.2357)
  Directional -> Accuracy: 0.5476, MCC: 0.0214, F1: 0.6984

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.61420 | val 0.73001
  Epoch 019 - train 0.40921 | val 1.34235
  Classification -> best τ=0.750 (val F1=0.2969)
  Directional -> Accuracy: 0.4286, MCC: -0.1316, F1: 0.3636

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.61711 | val 0.66380
  Epoch 020 - train 0.57330 | val 1.04712
  Epoch 021 - train 0.51150 | val 1.10724
  Classification -> best τ=0.610 (val F1=0.4109)
  Directional -> Accuracy: 0.4722, MCC: 0.0949, F1: 0.1364

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.62143 | val 0.82647
  Epoch 012 - train 0.58257 | val 1.33130
  Classification -> best τ=0.330 (val F1=0.1874)
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.60016 | val 1.18870
  Epoch 011 - train 0.60952 | val 1.15861
  Classification -> best τ=0.265 (val F1=0.3855)
  Directional -> Accuracy: 0.6364, MCC: 0.2345, F1: 0.7143

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.57036 | val 0.81186
  Epoch 011 - train 0.52832 | val 0.72033
  Classification -> best τ=0.465 (val F1=0.2067)
  Directional -> Accuracy: 0.6190, MCC: 0.2864, F1: 0.5294

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.56072 | val 0.87229
  Epoch 011 - train 0.55567 | val 1.01635
  Classification -> best τ=0.525 (val F1=0.2327)
  Directional -> Accuracy: 0.5179, MCC: 0.0333, F1: 0.4906

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.51623 | val 0.80913
  Epoch 011 - train 0.48434 | val 0.86451
  Classification -> best τ=0.390 (val F1=0.1709)
  Directional -> Accuracy: 0.5870, MCC: -0.1195, F1: 0.7397

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.59298 | val 0.91119
  Epoch 012 - train 0.56310 | val 0.76703
  Classification -> best τ=0.585 (val F1=0.4011)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.62716 | val 1.07610
  Epoch 011 - train 0.57682 | val 1.16163
  Classification -> best τ=0.355 (val F1=0.2709)
  Directional -> Accuracy: 0.5135, MCC: 0.0263, F1: 0.5000

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.57320 | val 1.16003
  Epoch 011 - train 0.55450 | val 0.87068
  Classification -> best τ=0.530 (val F1=0.3233)
  Directional -> Accuracy: 0.3556, MCC: -0.3494, F1: 0.4912

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.50699 | val 0.92277
  Epoch 012 - train 0.40386 | val 0.85574
  Classification -> best τ=0.475 (val F1=0.4423)
  Directional -> Accuracy: 0.6429, MCC: 0.2527, F1: 0.7170

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.54332 | val 0.70975
  Epoch 020 - train 0.40672 | val 0.89682
  Epoch 021 - train 0.35047 | val 0.79109
  Classification -> best τ=0.485 (val F1=0.3458)
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.5455

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.66175 | val 0.93566
  Epoch 011 - train 0.63824 | val 0.99110
  Classification -> best τ=0.420 (val F1=0.1647)
  Directional -> Accuracy: 0.4182, MCC: -0.1372, F1: 0.2727

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.55777 | val 1.55333
  Epoch 011 - train 0.48694 | val 2.30157
  Classification -> best τ=0.780 (val F1=0.2696)
  Directional -> Accuracy: 0.5357, MCC: 0.0702, F1: 0.5185

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.66938 | val 0.75001
  Epoch 011 - train 0.62771 | val 0.81131
  Classification -> best τ=0.595 (val F1=0.2064)
  Directional -> Accuracy: 0.5849, MCC: 0.1695, F1: 0.5926

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.55176 | val 1.86087
  Epoch 011 - train 0.52231 | val 1.91951
  Classification -> best τ=0.655 (val F1=0.2448)
  Directional -> Accuracy: 0.4364, MCC: -0.2052, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.66766 | val 0.73513

[I 2026-02-22 17:31:35,882] Trial 263 finished with value: 0.28558784812245314 and parameters: {'feature_set': 'sector', 'model_type': 'BiGRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.5, 'batch_size': 16, 'learning_rate': 0.008090858419079817, 'weight_decay': 0.0004165027787606314, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 1.05570593537975, 'early_stopping_min_delta': 0.0026783930600900586}. Best is trial 252 with value: 0.3108162738957727.

  Epoch 011 - train 0.67916 | val 0.69537
  Classification -> best τ=0.465 (val F1=0.3259)
  Directional -> Accuracy: 0.5500, MCC: 0.0965, F1: 0.5091

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.28558784812245314
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.65029 | val 0.89797
  Epoch 016 - train 0.61842 | val 1.53588
  Classification -> best τ=0.875 (val F1=0.2919)
  Directional -> Accuracy: 0.5921, MCC: 0.1616, F1: 0.2791

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.65116 | val 2.08664
  Epoch 013 - train 0.52879 | val 0.87798
  Classification -> best τ=0.640 (val F1=0.2523)
  Directional -> Accuracy: 0.6444, MCC: 0.2545, F1: 0.7143

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.58653 | val 0.84585
  Epoch 011 - train 0.57540 | val 0.80876
  Classification -> best τ=0.515 (val F1=0.2449)
  Directional -> Accuracy: 0.4783, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.61344 | val 1.34667
  Epoch 011 - train 0.63122 | val 1.21522
  Classification -> best τ=0.430 (val F1=0.2067)
  Directional -> Accuracy: 0.4730, MCC: 0.1079, F1: 0.0488

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.55823 | val 0.88444
  Epoch 013 - train 0.54848 | val 1.04851
  Classification -> best τ=0.520 (val F1=0.5079)
  Directional -> Accuracy: 0.6600, MCC: 0.3200, F1: 0.7018

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.54231 | val 1.51571
  Epoch 019 - train 0.45438 | val 1.63658
  Classification -> best τ=0.575 (val F1=0.4513)
  Directional -> Accuracy: 0.5217, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.63312 | val 0.78280
  Epoch 011 - train 0.62323 | val 0.82303
  Classification -> best τ=0.710 (val F1=0.1753)
  Directional -> Accuracy: 0.5735, MCC: -0.0751, F1: 0.0645

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.55469 | val 0.64802
  Epoch 019 - train 0.42682 | val 0.57995
  Classification -> best τ=0.270 (val F1=0.3632)
  Directional -> Accuracy: 0.5238, MCC: 0.1021, F1: 0.5652

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.62232 | val 1.48365
  Epoch 013 - train 0.55812 | val 0.96878
  Classification -> best τ=0.385 (val F1=0.3385)
  Directional -> Accuracy: 0.6042, MCC: 0.2673, F1: 0.6415

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.62133 | val 1.05645
  Epoch 012 - train 0.61034 | val 0.87675
  Classification -> best τ=0.410 (val F1=0.2071)
  Directional -> Accuracy: 0.5507, MCC: 0.2143, F1: 0.6173

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.61528 | val 0.86680
  Epoch 012 - train 0.55376 | val 0.98042
  Classification -> best τ=0.395 (val F1=0.0722)
  Directional -> Accuracy: 0.4082, MCC: -0.1804, F1: 0.5672

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.60961 | val 1.19774
  Epoch 012 - train 0.60921 | val 1.07312
  Classification -> best τ=0.525 (val F1=0.1009)
  Directional -> Accuracy: 0.5088, MCC: 0.0000, F1: 0.6744

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.60027 | val 0.74687
  Epoch 016 - train 0.46856 | val 0.77319
  Classification -> best τ=0.790 (val F1=0.2083)
  Directional -> Accuracy: 0.5238, MCC: -0.0663, F1: 0.0909

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.63372 | val 0.66526
  Epoch 011 - train 0.61750 | val 0.70641
  Classification -> best τ=0.490 (val F1=0.3126)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.58704 | val 0.79300
  Epoch 011 - train 0.57746 | val 0.83006
  Classification -> best τ=0.550 (val F1=0.1843)
  Directional -> Accuracy: 0.5490, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.62135 | val 0.97657
  Epoch 011 - train 0.58141 | val 1.24269
  Classification -> best τ=0.480 (val F1=0.4077)
  Directional -> Accuracy: 0.6232, MCC: 0.2465, F1: 0.7111

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.58356 | val 0.92733
  Epoch 011 - train 0.56597 | val 0.89097
  Classification -> best τ=0.495 (val F1=0.3563)
  Directional -> Accuracy: 0.3793, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.65510 | val 0.70452
  Epoch 014 - train 0.59249 | val 0.86436
  Classification -> best τ=0.560 (val F1=0.1909)
  Directional -> Accuracy: 0.4000, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.64061 | val 1.60187
  Epoch 011 - train 0.58180 | val 1.57079
  Classification -> best τ=0.395 (val F1=0.2843)
  Directional -> Accuracy: 0.4844, MCC: 0.0861, F1: 0.3265

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.61699 | val 1.20638
  Epoch 011 - train 0.54608 | val 1.23490
  Classification -> best τ=0.145 (val F1=0.2482)
  Directional -> Accuracy: 0.5541, MCC: 0.0000, F1: 0.7130

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.58054 | val 0.83346
  Epoch 011 - train 0.56003 | val 0.87521
  Classification -> best τ=0.645 (val F1=0.2861)
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.65569 | val 0.75737
  Epoch 012 - train 0.60087 | val 1.14985
  Classification -> best τ=0.470 (val F1=0.2371)
  Directional -> Accuracy: 0.4308, MCC: -0.2166, F1: 0.5843

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.64763 | val 0.62681
  Epoch 020 - train 0.59516 | val 0.72670
  Epoch 021 - train 0.60076 | val 0.60130
  Classification -> best τ=0.445 (val F1=0.4409)
  Directional -> Accuracy: 0.5614, MCC: 0.0236, F1: 0.7126

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.66127 | val 0.75183
  Epoch 011 - train 0.61319 | val 0.81591
  Classification -> best τ=0.610 (val F1=0.2451)
  Directional -> Accuracy: 0.5538, MCC: 0.1400, F1: 0.1714

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.58357 | val 0.71910
  Epoch 014 - train 0.51974 | val 0.92522
  Classification -> best τ=0.275 (val F1=0.4903)
  Directional -> Accuracy: 0.5636, MCC: 0.1491, F1: 0.5385

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.53593 | val 1.53515
  Epoch 011 - train 0.49296 | val 1.73740
  Classification -> best τ=0.635 (val F1=0.1956)
  Directional -> Accuracy: 0.5778, MCC: 0.0340, F1: 0.0952

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.60408 | val 0.78739
  Epoch 011 - train 0.60373 | val 0.73937
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.7273

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.59671 | val 0.90604
  Epoch 011 - train 0.56022 | val 0.97611
  Classification -> best τ=0.330 (val F1=0.2530)
  Directional -> Accuracy: 0.4464, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.56484 | val 0.73456
  Epoch 011 - train 0.56803 | val 0.70717
  Classification -> best τ=0.525 (val F1=0.2509)
  Directional -> Accuracy: 0.5750, MCC: 0.1124, F1: 0.6909

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.62935 | val 1.36010
  Epoch 011 - train 0.62668 | val 1.36134
  Classification -> best τ=0.555 (val F1=0.2065)
  Directional -> Accuracy: 0.4286, MCC: -0.1356, F1: 0.4783

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.62612 | val 0.93127
  Epoch 013 - train 0.59628 | val 0.72242
  Classification -> best τ=0.625 (val F1=0.1641)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.54362 | val 0.83564
  Epoch 011 - train 0.53422 | val 0.84782
  Classification -> best τ=0.440 (val F1=0.3957)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.64356 | val 0.71729
  Epoch 013 - train 0.55796 | val 0.67225
  Classification -> best τ=0.480 (val F1=0.4058)
  Directional -> Accuracy: 0.5556, MCC: 0.1323, F1: 0.5429

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.62572 | val 0.79425
  Epoch 011 - train 0.54411 | val 0.89646
  Classification -> best τ=0.355 (val F1=0.1309)
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.62298 | val 1.20725
  Epoch 013 - train 0.55807 | val 1.05724
  Classification -> best τ=0.140 (val F1=0.3525)
  Directional -> Accuracy: 0.5606, MCC: 0.2710, F1: 0.4314

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.55903 | val 0.99202
  Epoch 014 - train 0.40086 | val 0.77816
  Classification -> best τ=0.405 (val F1=0.3218)
  Directional -> Accuracy: 0.6429, MCC: 0.3511, F1: 0.5455

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.61260 | val 0.78208
  Epoch 011 - train 0.50914 | val 0.78434
  Classification -> best τ=0.580 (val F1=0.2850)
  Directional -> Accuracy: 0.5536, MCC: 0.1448, F1: 0.0741

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.57038 | val 1.31367
  Epoch 011 - train 0.49996 | val 1.13832
  Classification -> best τ=0.390 (val F1=0.2118)
  Directional -> Accuracy: 0.6087, MCC: 0.0000, F1: 0.7568

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.58752 | val 1.04041
  Epoch 016 - train 0.53220 | val 1.33379
  Classification -> best τ=0.515 (val F1=0.4625)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.63086 | val 1.52701
  Epoch 013 - train 0.55537 | val 1.48206
  Classification -> best τ=0.510 (val F1=0.2951)
  Directional -> Accuracy: 0.5000, MCC: 0.0375, F1: 0.6408

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.59521 | val 0.90944
  Epoch 011 - train 0.55404 | val 0.88157
  Classification -> best τ=0.525 (val F1=0.1890)
  Directional -> Accuracy: 0.5778, MCC: 0.2222, F1: 0.3871

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.52523 | val 0.99809
  Epoch 016 - train 0.39321 | val 1.80747
  Classification -> best τ=0.865 (val F1=0.3612)
  Directional -> Accuracy: 0.4286, MCC: -0.1021, F1: 0.3684

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.54062 | val 1.24624
  Epoch 012 - train 0.44439 | val 1.43677
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.5455

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.64261 | val 0.92444
  Epoch 011 - train 0.66653 | val 0.92895
  Classification -> best τ=0.465 (val F1=0.2833)
  Directional -> Accuracy: 0.4545, MCC: -0.1641, F1: 0.5833

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.51646 | val 2.80655
  Epoch 011 - train 0.52660 | val 3.57538
  Classification -> best τ=0.690 (val F1=0.3422)
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.6506

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.66680 | val 0.78056
  Epoch 020 - train 0.62534 | val 0.66331
  Epoch 022 - train 0.59092 | val 0.73846
  Classification -> best τ=0.650 (val F1=0.2508)
  Directional -> Accuracy: 0.5660, MCC: 0.1325, F1: 0.5660

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.62703 | val 2.04356
  Epoch 011 - train 0.53091 | val 2.30795
  Classification -> best τ=0.670 (val F1=0.2693)
  Directional -> Accuracy: 0.4727, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.64437 | val 0.96443

[I 2026-02-22 17:35:36,580] Trial 264 finished with value: 0.2707020068857388 and parameters: {'feature_set': 'sector', 'model_type': 'BiGRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.5, 'batch_size': 16, 'learning_rate': 0.008368669188754943, 'weight_decay': 0.0004716651211422191, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 1.1080347644211332, 'early_stopping_min_delta': 0.0017657710022719582}. Best is trial 252 with value: 0.3108162738957727.

  Epoch 011 - train 0.64756 | val 0.74516
  Classification -> best τ=0.465 (val F1=0.2623)
  Directional -> Accuracy: 0.5000, MCC: -0.0689, F1: 0.0625

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2707020068857388
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.62575 | val 0.90432
  Epoch 018 - train 0.58737 | val 1.45889
  Classification -> best τ=0.785 (val F1=0.2200)
  Directional -> Accuracy: 0.6053, MCC: 0.1978, F1: 0.3182

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.55923 | val 0.72971
  Epoch 012 - train 0.57318 | val 0.78033
  Classification -> best τ=0.510 (val F1=0.1941)
  Directional -> Accuracy: 0.6444, MCC: 0.2493, F1: 0.7241

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.57812 | val 1.99440
  Epoch 013 - train 0.55829 | val 1.63027
  Classification -> best τ=0.815 (val F1=0.3237)
  Directional -> Accuracy: 0.4783, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.61958 | val 0.87110
  Epoch 011 - train 0.62685 | val 0.92253
  Classification -> best τ=0.335 (val F1=0.2230)
  Directional -> Accuracy: 0.4865, MCC: -0.0992, F1: 0.6200

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.59072 | val 0.78476
  Epoch 014 - train 0.51154 | val 1.04403
  Classification -> best τ=0.255 (val F1=0.5175)
  Directional -> Accuracy: 0.7200, MCC: 0.4387, F1: 0.7407

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.51459 | val 0.70974
  Epoch 019 - train 0.40882 | val 0.77007
  Classification -> best τ=0.485 (val F1=0.3433)
  Directional -> Accuracy: 0.5217, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.62936 | val 0.93897
  Epoch 014 - train 0.54789 | val 1.12225
  Classification -> best τ=0.575 (val F1=0.2506)
  Directional -> Accuracy: 0.5441, MCC: 0.0170, F1: 0.3673

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.57190 | val 0.60138
  Epoch 019 - train 0.40638 | val 0.87320
  Classification -> best τ=0.385 (val F1=0.3632)
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.60357 | val 2.13894
  Epoch 012 - train 0.54315 | val 1.99278
  Classification -> best τ=0.460 (val F1=0.3096)
  Directional -> Accuracy: 0.4375, MCC: 0.0000, F1: 0.6087

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.61910 | val 0.68994
  Epoch 018 - train 0.50909 | val 0.72744
  Classification -> best τ=0.645 (val F1=0.2462)
  Directional -> Accuracy: 0.4783, MCC: 0.0808, F1: 0.5814

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.65304 | val 0.94848
  Epoch 014 - train 0.55068 | val 0.70925
  Classification -> best τ=0.520 (val F1=0.2995)
  Directional -> Accuracy: 0.5918, MCC: 0.1804, F1: 0.2308

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.59314 | val 1.43351
  Epoch 011 - train 0.58013 | val 1.38511
  Classification -> best τ=0.520 (val F1=0.1771)
  Directional -> Accuracy: 0.5088, MCC: 0.0000, F1: 0.6744

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.53942 | val 1.79697
  Epoch 015 - train 0.43514 | val 0.85647
  Classification -> best τ=0.395 (val F1=0.2850)
  Directional -> Accuracy: 0.4762, MCC: -0.0478, F1: 0.4500

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.64859 | val 1.09348
  Epoch 013 - train 0.58613 | val 0.99150
  Classification -> best τ=0.505 (val F1=0.3126)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.60889 | val 0.72782
  Epoch 020 - train 0.44472 | val 0.97710
  Classification -> best τ=0.375 (val F1=0.2728)
  Directional -> Accuracy: 0.4314, MCC: -0.1068, F1: 0.5085

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.62973 | val 0.81590
  Epoch 018 - train 0.53935 | val 1.95364
  Classification -> best τ=0.745 (val F1=0.3151)
  Directional -> Accuracy: 0.5652, MCC: 0.1389, F1: 0.5588

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.59970 | val 1.33174
  Epoch 013 - train 0.56359 | val 1.34344
  Classification -> best τ=0.480 (val F1=0.3565)
  Directional -> Accuracy: 0.4310, MCC: 0.1826, F1: 0.1538

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.63986 | val 0.72767
  Epoch 015 - train 0.57028 | val 0.76454
  Classification -> best τ=0.625 (val F1=0.2220)
  Directional -> Accuracy: 0.4000, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.59660 | val 1.67802
  Epoch 011 - train 0.57862 | val 1.72032
  Classification -> best τ=0.420 (val F1=0.3140)
  Directional -> Accuracy: 0.5312, MCC: 0.0294, F1: 0.6053

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.56755 | val 1.06924
  Epoch 011 - train 0.52448 | val 1.06539
  Classification -> best τ=0.115 (val F1=0.2204)
  Directional -> Accuracy: 0.5541, MCC: 0.0000, F1: 0.7130

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.59074 | val 0.89937
  Epoch 011 - train 0.56032 | val 0.99083
  Classification -> best τ=0.400 (val F1=0.2247)
  Directional -> Accuracy: 0.6170, MCC: 0.0000, F1: 0.7632

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.61921 | val 1.63156
  Epoch 011 - train 0.59475 | val 1.76404
  Classification -> best τ=0.510 (val F1=0.2830)
  Directional -> Accuracy: 0.5692, MCC: 0.1393, F1: 0.5625

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.65681 | val 0.62868
  Epoch 020 - train 0.56824 | val 0.76430
  Classification -> best τ=0.760 (val F1=0.4037)
  Directional -> Accuracy: 0.5614, MCC: 0.1216, F1: 0.5902

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.62223 | val 0.70375
  Epoch 014 - train 0.62242 | val 0.76268
  Classification -> best τ=0.415 (val F1=0.1478)
  Directional -> Accuracy: 0.5077, MCC: 0.0402, F1: 0.5897

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.55695 | val 0.90543
  Epoch 013 - train 0.54451 | val 0.69396
  Classification -> best τ=0.640 (val F1=0.4183)
  Directional -> Accuracy: 0.4909, MCC: 0.0402, F1: 0.3333

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.48984 | val 3.02236
  Epoch 011 - train 0.47418 | val 3.22077
  Classification -> best τ=0.750 (val F1=0.5151)
  Directional -> Accuracy: 0.6222, MCC: 0.1909, F1: 0.3704

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.61213 | val 0.70145
  Epoch 011 - train 0.58002 | val 0.70543
  Classification -> best τ=0.540 (val F1=0.1353)
  Directional -> Accuracy: 0.5000, MCC: 0.1005, F1: 0.3636

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.58451 | val 1.51709
  Epoch 016 - train 0.52950 | val 1.41866
  Classification -> best τ=0.420 (val F1=0.3743)
  Directional -> Accuracy: 0.4464, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.57015 | val 0.91205
  Epoch 015 - train 0.51058 | val 1.06468
  Classification -> best τ=0.510 (val F1=0.2414)
  Directional -> Accuracy: 0.5750, MCC: 0.1240, F1: 0.7119

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.65011 | val 0.93176
  Epoch 012 - train 0.60532 | val 1.00869
  Classification -> best τ=0.540 (val F1=0.3450)
  Directional -> Accuracy: 0.5000, MCC: 0.0196, F1: 0.5714

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.62051 | val 1.12012
  Epoch 013 - train 0.49318 | val 0.95042
  Classification -> best τ=0.375 (val F1=0.0769)
  Directional -> Accuracy: 0.7143, MCC: 0.4416, F1: 0.7143

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.53231 | val 1.21850
  Epoch 011 - train 0.54875 | val 1.04602
  Classification -> best τ=0.455 (val F1=0.3541)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.60253 | val 0.69858
  Epoch 012 - train 0.54478 | val 0.78533
  Classification -> best τ=0.345 (val F1=0.3477)
  Directional -> Accuracy: 0.5278, MCC: 0.1179, F1: 0.4333

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.54561 | val 1.62522
  Epoch 011 - train 0.51552 | val 1.61966
  Classification -> best τ=0.420 (val F1=0.1874)
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.60136 | val 1.31222
  Epoch 011 - train 0.58696 | val 1.36632
  Classification -> best τ=0.320 (val F1=0.2674)
  Directional -> Accuracy: 0.6212, MCC: 0.2542, F1: 0.7525

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.51339 | val 1.75870
  Epoch 011 - train 0.44184 | val 1.29613
  Classification -> best τ=0.510 (val F1=0.2618)
  Directional -> Accuracy: 0.6667, MCC: 0.3920, F1: 0.5882

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.56179 | val 0.80819
  Epoch 011 - train 0.53719 | val 0.79058
  Classification -> best τ=0.290 (val F1=0.2315)
  Directional -> Accuracy: 0.5000, MCC: 0.0499, F1: 0.6000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.53801 | val 1.25647
  Epoch 011 - train 0.50423 | val 1.31851
  Classification -> best τ=0.290 (val F1=0.2118)
  Directional -> Accuracy: 0.6087, MCC: 0.0000, F1: 0.7568

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.58911 | val 1.33955
  Epoch 012 - train 0.59926 | val 1.64853
  Classification -> best τ=0.480 (val F1=0.4011)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.61325 | val 0.84692
  Epoch 013 - train 0.53756 | val 1.08188
  Classification -> best τ=0.380 (val F1=0.3556)
  Directional -> Accuracy: 0.4595, MCC: -0.1107, F1: 0.2593

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.57409 | val 0.77663
  Epoch 012 - train 0.53754 | val 0.94595
  Classification -> best τ=0.535 (val F1=0.4397)
  Directional -> Accuracy: 0.5111, MCC: 0.0000, F1: 0.6765

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.49585 | val 1.57015
  Epoch 015 - train 0.36862 | val 1.76683
  Classification -> best τ=0.865 (val F1=0.4082)
  Directional -> Accuracy: 0.5238, MCC: 0.0694, F1: 0.5238

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.54471 | val 0.91242
  Epoch 020 - train 0.39746 | val 0.74605
  Classification -> best τ=0.775 (val F1=0.5421)
  Directional -> Accuracy: 0.3958, MCC: 0.1130, F1: 0.5538

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.61497 | val 1.52460
  Epoch 013 - train 0.59793 | val 0.86895
  Classification -> best τ=0.625 (val F1=0.2036)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.54034 | val 2.17968
  Epoch 011 - train 0.52373 | val 2.75365
  Classification -> best τ=0.725 (val F1=0.4159)
  Directional -> Accuracy: 0.4643, MCC: -0.0643, F1: 0.5946

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.66536 | val 0.68334
  Epoch 013 - train 0.64633 | val 0.68216
  Classification -> best τ=0.650 (val F1=0.2064)
  Directional -> Accuracy: 0.5472, MCC: 0.0926, F1: 0.6000

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.51016 | val 0.77085
  Epoch 011 - train 0.56641 | val 1.13941
  Classification -> best τ=0.570 (val F1=0.3047)
  Directional -> Accuracy: 0.4182, MCC: -0.1590, F1: 0.2381

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.62227 | val 0.86373

[I 2026-02-22 17:39:47,526] Trial 265 finished with value: 0.29719150391631216 and parameters: {'feature_set': 'sector', 'model_type': 'BiGRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.4, 'batch_size': 16, 'learning_rate': 0.008381360058049485, 'weight_decay': 0.0003690705402100816, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 20, 'huber_delta': 0.9944381175494467, 'early_stopping_min_delta': 0.001315051400994958}. Best is trial 252 with value: 0.3108162738957727.

  Epoch 011 - train 0.59810 | val 0.94007
  Classification -> best τ=0.480 (val F1=0.1941)
  Directional -> Accuracy: 0.5833, MCC: 0.1761, F1: 0.4186

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.29719150391631216
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.65118 | val 1.00035
  Epoch 012 - train 0.60995 | val 0.79463
  Classification -> best τ=0.805 (val F1=0.2036)
  Directional -> Accuracy: 0.5526, MCC: 0.0000, F1: 0.0000

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.58762 | val 0.75180
  Epoch 011 - train 0.53776 | val 0.89916
  Classification -> best τ=0.505 (val F1=0.1941)
  Directional -> Accuracy: 0.6000, MCC: 0.1764, F1: 0.7429

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.59726 | val 1.45240
  Epoch 012 - train 0.54113 | val 1.50605
  Classification -> best τ=0.675 (val F1=0.3114)
  Directional -> Accuracy: 0.5000, MCC: 0.0547, F1: 0.2069

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.59922 | val 0.80422
  Epoch 016 - train 0.60218 | val 0.81200
  Classification -> best τ=0.370 (val F1=0.2712)
  Directional -> Accuracy: 0.5676, MCC: 0.1294, F1: 0.6000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.55336 | val 0.77995
  Epoch 011 - train 0.52629 | val 0.86103
  Classification -> best τ=0.625 (val F1=0.3946)
  Directional -> Accuracy: 0.6200, MCC: 0.2670, F1: 0.5581

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.54194 | val 0.67215
  Epoch 020 - train 0.50126 | val 1.08618
  Classification -> best τ=0.510 (val F1=0.4379)
  Directional -> Accuracy: 0.5217, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.61987 | val 0.91149
  Epoch 011 - train 0.60240 | val 1.12838
  Classification -> best τ=0.305 (val F1=0.2280)
  Directional -> Accuracy: 0.4118, MCC: -0.0378, F1: 0.5349

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.57687 | val 0.56501
  Epoch 020 - train 0.47933 | val 0.71148
  Classification -> best τ=0.285 (val F1=0.4176)
  Directional -> Accuracy: 0.5238, MCC: 0.0849, F1: 0.5455

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.61613 | val 1.11024
  Epoch 011 - train 0.55204 | val 1.06005
  Classification -> best τ=0.555 (val F1=0.2838)
  Directional -> Accuracy: 0.5625, MCC: 0.0263, F1: 0.0870

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.59305 | val 0.77378
  Epoch 011 - train 0.57993 | val 0.78856
  Classification -> best τ=0.455 (val F1=0.2504)
  Directional -> Accuracy: 0.4203, MCC: -0.0887, F1: 0.5122

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.60967 | val 0.93363
  Epoch 011 - train 0.60820 | val 0.87088
  Classification -> best τ=0.610 (val F1=0.4059)
  Directional -> Accuracy: 0.5918, MCC: 0.1804, F1: 0.2308

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.58775 | val 0.96864
  Epoch 011 - train 0.58762 | val 0.91627
  Classification -> best τ=0.480 (val F1=0.1843)
  Directional -> Accuracy: 0.5263, MCC: 0.1360, F1: 0.6824

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.53914 | val 1.18309
  Epoch 011 - train 0.48847 | val 1.43173
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.6230

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.62205 | val 0.66917
  Epoch 011 - train 0.60386 | val 0.63230
  Classification -> best τ=0.420 (val F1=0.3706)
  Directional -> Accuracy: 0.4667, MCC: -0.1857, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.58544 | val 0.84366
  Epoch 013 - train 0.54318 | val 0.80727
  Classification -> best τ=0.480 (val F1=0.2571)
  Directional -> Accuracy: 0.5490, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.65581 | val 0.69843
  Epoch 020 - train 0.58674 | val 1.02916
  Classification -> best τ=0.735 (val F1=0.4410)
  Directional -> Accuracy: 0.5362, MCC: 0.1027, F1: 0.4667

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.60734 | val 0.82772
  Epoch 011 - train 0.61685 | val 0.89803
  Classification -> best τ=0.505 (val F1=0.2234)
  Directional -> Accuracy: 0.3966, MCC: -0.1063, F1: 0.3137

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.60391 | val 0.87323
  Epoch 011 - train 0.56964 | val 0.86184
  Classification -> best τ=0.590 (val F1=0.2220)
  Directional -> Accuracy: 0.4000, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.58386 | val 0.94136
  Epoch 011 - train 0.57789 | val 0.91175
  Classification -> best τ=0.425 (val F1=0.2620)
  Directional -> Accuracy: 0.4844, MCC: 0.0694, F1: 0.3529

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.58766 | val 0.77155
  Epoch 014 - train 0.51337 | val 0.94241
  Classification -> best τ=0.415 (val F1=0.2617)
  Directional -> Accuracy: 0.3919, MCC: -0.2665, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.57987 | val 0.79555
  Epoch 016 - train 0.47998 | val 1.09897
  Classification -> best τ=0.585 (val F1=0.2259)
  Directional -> Accuracy: 0.3830, MCC: -0.1251, F1: 0.2564

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.62390 | val 0.99020
  Epoch 011 - train 0.61620 | val 1.55868
  Classification -> best τ=0.515 (val F1=0.2543)
  Directional -> Accuracy: 0.4923, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.63786 | val 0.68079
  Epoch 013 - train 0.61640 | val 0.68354
  Classification -> best τ=0.720 (val F1=0.3833)
  Directional -> Accuracy: 0.5789, MCC: 0.1706, F1: 0.5862

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.62977 | val 0.82612
  Epoch 013 - train 0.58438 | val 0.97702
  Classification -> best τ=0.440 (val F1=0.2737)
  Directional -> Accuracy: 0.4923, MCC: -0.0657, F1: 0.1951

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.58560 | val 0.88883
  Epoch 017 - train 0.44861 | val 0.88073
  Classification -> best τ=0.320 (val F1=0.4688)
  Directional -> Accuracy: 0.5273, MCC: 0.0467, F1: 0.5667

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.55297 | val 1.53156
  Epoch 011 - train 0.52779 | val 1.48286
  Classification -> best τ=0.590 (val F1=0.2035)
  Directional -> Accuracy: 0.6222, MCC: 0.3815, F1: 0.6792

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.58813 | val 1.02337
  Epoch 013 - train 0.52659 | val 1.11147
  Classification -> best τ=0.585 (val F1=0.0212)
  Directional -> Accuracy: 0.4762, MCC: 0.1936, F1: 0.1538

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.58859 | val 0.87294
  Epoch 011 - train 0.55943 | val 1.14631
  Classification -> best τ=0.535 (val F1=0.2850)
  Directional -> Accuracy: 0.4464, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.54362 | val 0.89550
  Epoch 012 - train 0.53709 | val 1.03082
  Classification -> best τ=0.480 (val F1=0.2618)
  Directional -> Accuracy: 0.5750, MCC: 0.1240, F1: 0.7119

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.61736 | val 0.91529
  Epoch 015 - train 0.54556 | val 1.03620
  Classification -> best τ=0.620 (val F1=0.3501)
  Directional -> Accuracy: 0.5238, MCC: 0.0500, F1: 0.5238

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.59067 | val 1.15248
  Epoch 011 - train 0.58580 | val 1.36840
  Classification -> best τ=0.525 (val F1=0.2011)
  Directional -> Accuracy: 0.5476, MCC: 0.0391, F1: 0.6780

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.60799 | val 0.80609
  Epoch 011 - train 0.52658 | val 0.77693
  Classification -> best τ=0.660 (val F1=0.2969)
  Directional -> Accuracy: 0.4898, MCC: -0.1940, F1: 0.6575

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.62246 | val 0.77113
  Epoch 014 - train 0.55991 | val 0.92730
  Classification -> best τ=0.445 (val F1=0.2765)
  Directional -> Accuracy: 0.5694, MCC: 0.2524, F1: 0.4364

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.55192 | val 1.23609
  Epoch 011 - train 0.52857 | val 1.29447
  Classification -> best τ=0.335 (val F1=0.2717)
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.66650 | val 0.68520
  Epoch 012 - train 0.61910 | val 0.88036
  Classification -> best τ=0.310 (val F1=0.3758)
  Directional -> Accuracy: 0.5152, MCC: 0.0646, F1: 0.5000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.55343 | val 0.91154
  Epoch 013 - train 0.46562 | val 1.34498
  Classification -> best τ=0.450 (val F1=0.2439)
  Directional -> Accuracy: 0.6190, MCC: 0.2409, F1: 0.6190

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.57741 | val 0.78292
  Epoch 012 - train 0.49334 | val 0.87748
  Classification -> best τ=0.420 (val F1=0.2114)
  Directional -> Accuracy: 0.4464, MCC: -0.1003, F1: 0.4561

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.60412 | val 1.13720
  Epoch 012 - train 0.50166 | val 1.00056
  Classification -> best τ=0.740 (val F1=0.2659)
  Directional -> Accuracy: 0.4565, MCC: 0.0318, F1: 0.3590

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.59636 | val 1.20694
  Epoch 014 - train 0.54921 | val 1.07409
  Classification -> best τ=0.540 (val F1=0.4011)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.57627 | val 1.71048
  Epoch 013 - train 0.51660 | val 1.63078
  Classification -> best τ=0.255 (val F1=0.2181)
  Directional -> Accuracy: 0.4865, MCC: 0.0000, F1: 0.6545

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.62567 | val 0.99963
  Epoch 012 - train 0.58082 | val 1.04785
  Classification -> best τ=0.515 (val F1=0.3873)
  Directional -> Accuracy: 0.5333, MCC: 0.0786, F1: 0.6667

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.45823 | val 1.85819
  Epoch 011 - train 0.42837 | val 1.81998
  Classification -> best τ=0.570 (val F1=0.4588)
  Directional -> Accuracy: 0.5714, MCC: 0.0589, F1: 0.7000

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.55471 | val 0.73569
  Epoch 020 - train 0.43884 | val 0.56808
  Classification -> best τ=0.760 (val F1=0.6290)
  Directional -> Accuracy: 0.4792, MCC: 0.2641, F1: 0.5902

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.65107 | val 0.98229
  Epoch 011 - train 0.60796 | val 1.09434
  Classification -> best τ=0.580 (val F1=0.1801)
  Directional -> Accuracy: 0.4545, MCC: -0.0177, F1: 0.0625

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.55522 | val 1.92984
  Epoch 011 - train 0.50359 | val 2.11283
  Classification -> best τ=0.720 (val F1=0.4282)
  Directional -> Accuracy: 0.5000, MCC: 0.0153, F1: 0.5758

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.65929 | val 0.68527
  Epoch 015 - train 0.59774 | val 0.90592
  Classification -> best τ=0.540 (val F1=0.2298)
  Directional -> Accuracy: 0.6604, MCC: 0.3709, F1: 0.7353

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.55248 | val 1.70415
  Epoch 011 - train 0.53685 | val 1.67669
  Classification -> best τ=0.640 (val F1=0.2557)
  Directional -> Accuracy: 0.5273, MCC: 0.0000, F1: 0.6905

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.63924 | val 0.68635

[I 2026-02-22 17:43:37,162] Trial 266 finished with value: 0.29173591560305673 and parameters: {'feature_set': 'sector', 'model_type': 'BiGRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.4, 'batch_size': 16, 'learning_rate': 0.005428257995748692, 'weight_decay': 0.0005887734324116315, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 20, 'huber_delta': 0.9491570573682167, 'early_stopping_min_delta': 0.001247968663091812}. Best is trial 252 with value: 0.3108162738957727.

  Epoch 018 - train 0.61681 | val 0.70812
  Classification -> best τ=0.345 (val F1=0.3234)
  Directional -> Accuracy: 0.6167, MCC: 0.2330, F1: 0.5490

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.29173591560305673
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d', 'sentiment', 'emotion_anger', 'emotion_disgust', 'emotion_fear', 'emotion_joy', 'emotion_neutral', 'emotion_sadness', 'emotion_surprize', 'emotion_anger_pct', 'emotion_disgust_pct', 'emotion_fear_pct', 'emotion_joy_pct', 'emotion_neutral_pct', 'emotion_sadness_pct', 'emotion_surprize_pct', 'positive_emotion', 'negative_emotion', 'uncertainty_emotion', 'positive_emotion_pct', 'negative_emotion_pct', 'uncertainty_emotion_pct', 'stance_label', 'stance_score', 'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down', 'finbert_neutral']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.57603 | val 0.78832
  Epoch 011 - train 0.57537 | val 0.79024
  Classification -> best τ=0.560 (val F1=0.1430)
  Directional -> Accuracy: 0.5395, MCC: -0.1039, F1: 0.0000

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.54552 | val 0.93407
  Epoch 011 - train 0.56182 | val 0.94024
  Classification -> best τ=0.435 (val F1=0.2025)
  Directional -> Accuracy: 0.5778, MCC: 0.0000, F1: 0.7324

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.62111 | val 0.71718
  Epoch 013 - train 0.59697 | val 0.72884
  Classification -> best τ=0.565 (val F1=0.2037)
  Directional -> Accuracy: 0.4130, MCC: -0.1860, F1: 0.1818

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.60241 | val 1.02180
  Epoch 011 - train 0.60340 | val 1.05241
  Classification -> best τ=0.445 (val F1=0.0803)
  Directional -> Accuracy: 0.4865, MCC: -0.0076, F1: 0.4412

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.55574 | val 0.59508
  Epoch 020 - train 0.46120 | val 0.63004
  Classification -> best τ=0.600 (val F1=0.4745)
  Directional -> Accuracy: 0.5800, MCC: 0.1922, F1: 0.4878

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.57359 | val 0.74321
  Epoch 011 - train 0.55237 | val 0.74630
  Classification -> best τ=0.505 (val F1=0.1716)
  Directional -> Accuracy: 0.5000, MCC: -0.0766, F1: 0.0800

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.59264 | val 0.74287
  Epoch 012 - train 0.59764 | val 0.73930
  Classification -> best τ=0.475 (val F1=0.3287)
  Directional -> Accuracy: 0.5882, MCC: 0.1866, F1: 0.5484

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.64331 | val 0.79563
  Epoch 011 - train 0.62640 | val 0.80101
  Classification -> best τ=0.430 (val F1=0.1657)
  Directional -> Accuracy: 0.4048, MCC: -0.1803, F1: 0.5763

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.60471 | val 0.90115
  Epoch 011 - train 0.60151 | val 0.90245
  Classification -> best τ=0.545 (val F1=0.1608)
  Directional -> Accuracy: 0.6042, MCC: 0.2002, F1: 0.5581

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.59579 | val 0.72751
  Epoch 011 - train 0.59282 | val 0.73405
  Classification -> best τ=0.450 (val F1=0.1576)
  Directional -> Accuracy: 0.3768, MCC: -0.2504, F1: 0.5474

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.59780 | val 0.81174
  Epoch 011 - train 0.58132 | val 0.82129
  Classification -> best τ=0.540 (val F1=0.3072)
  Directional -> Accuracy: 0.5306, MCC: -0.0594, F1: 0.0800

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.61987 | val 0.78134
  Epoch 011 - train 0.63222 | val 0.78462
  Classification -> best τ=0.450 (val F1=0.1083)
  Directional -> Accuracy: 0.5439, MCC: 0.1941, F1: 0.6905

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.58957 | val 0.82682
  Epoch 011 - train 0.56958 | val 0.83359
  Classification -> best τ=0.530 (val F1=0.1754)
  Directional -> Accuracy: 0.5476, MCC: 0.0000, F1: 0.0000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.61422 | val 0.66262
  Epoch 013 - train 0.60307 | val 0.66723
  Classification -> best τ=0.475 (val F1=0.4317)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.58784 | val 0.77353
  Epoch 011 - train 0.57369 | val 0.78514
  Classification -> best τ=0.500 (val F1=0.1556)
  Directional -> Accuracy: 0.5490, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.59503 | val 0.75002
  Epoch 013 - train 0.56824 | val 0.76853
  Classification -> best τ=0.220 (val F1=0.2341)
  Directional -> Accuracy: 0.5507, MCC: 0.1304, F1: 0.7048

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.59678 | val 0.75060
  Epoch 011 - train 0.59910 | val 0.74683
  Classification -> best τ=0.540 (val F1=0.2276)
  Directional -> Accuracy: 0.3793, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.59297 | val 0.87236
  Epoch 011 - train 0.57974 | val 0.87242
  Classification -> best τ=0.550 (val F1=0.0437)
  Directional -> Accuracy: 0.4933, MCC: 0.1582, F1: 0.3448

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.59090 | val 0.70853
  Epoch 011 - train 0.58233 | val 0.71044
  Classification -> best τ=0.430 (val F1=0.2428)
  Directional -> Accuracy: 0.5156, MCC: 0.1459, F1: 0.3922

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.56825 | val 0.87765
  Epoch 011 - train 0.56514 | val 0.89157
  Classification -> best τ=0.390 (val F1=0.2601)
  Directional -> Accuracy: 0.5405, MCC: 0.1426, F1: 0.4516

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.61942 | val 0.70977
  Epoch 011 - train 0.62267 | val 0.71090
  Classification -> best τ=0.560 (val F1=0.0850)
  Directional -> Accuracy: 0.5532, MCC: -0.0220, F1: 0.6769

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.57560 | val 0.72899
  Epoch 011 - train 0.61154 | val 0.73239
  Classification -> best τ=0.485 (val F1=0.1482)
  Directional -> Accuracy: 0.4923, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.61499 | val 0.68612
  Epoch 020 - train 0.50864 | val 0.72140
  Classification -> best τ=0.700 (val F1=0.2606)
  Directional -> Accuracy: 0.4737, MCC: 0.1685, F1: 0.1176

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.60836 | val 0.72817
  Epoch 011 - train 0.58887 | val 0.73034
  Classification -> best τ=0.525 (val F1=0.1727)
  Directional -> Accuracy: 0.5385, MCC: 0.0923, F1: 0.5833

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.61033 | val 0.65728
  Epoch 018 - train 0.53212 | val 0.71025
  Classification -> best τ=0.490 (val F1=0.3643)
  Directional -> Accuracy: 0.5636, MCC: 0.1698, F1: 0.5000

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.58833 | val 0.74494
  Epoch 011 - train 0.58364 | val 0.74684
  Classification -> best τ=0.485 (val F1=0.2035)
  Directional -> Accuracy: 0.4000, MCC: -0.1764, F1: 0.5714

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.59653 | val 0.69058
  Epoch 014 - train 0.57011 | val 0.71101
  Classification -> best τ=0.550 (val F1=0.1667)
  Directional -> Accuracy: 0.4762, MCC: 0.1171, F1: 0.2143

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.57643 | val 0.78119
  Epoch 011 - train 0.57388 | val 0.79103
  Classification -> best τ=0.555 (val F1=0.1615)
  Directional -> Accuracy: 0.4464, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.60549 | val 0.70862
  Epoch 011 - train 0.64301 | val 0.70869
  Classification -> best τ=0.490 (val F1=0.0948)
  Directional -> Accuracy: 0.4750, MCC: 0.0380, F1: 0.2222

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.61882 | val 0.71409
  Epoch 011 - train 0.61616 | val 0.71845
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4762, MCC: 0.0000, F1: 0.6452

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.63053 | val 0.77456
  Epoch 011 - train 0.62577 | val 0.77941
  Classification -> best τ=0.480 (val F1=0.3385)
  Directional -> Accuracy: 0.5238, MCC: -0.0663, F1: 0.6774

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.56899 | val 0.67907
  Epoch 015 - train 0.51586 | val 0.71709
  Classification -> best τ=0.355 (val F1=0.3714)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.59414 | val 0.72350
  Epoch 013 - train 0.55568 | val 0.75662
  Classification -> best τ=0.420 (val F1=0.3131)
  Directional -> Accuracy: 0.5833, MCC: 0.1285, F1: 0.7115

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.57794 | val 0.95687
  Epoch 011 - train 0.58798 | val 0.97388
  Classification -> best τ=0.510 (val F1=0.1607)
  Directional -> Accuracy: 0.6512, MCC: 0.3392, F1: 0.7059

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.60658 | val 0.75792
  Epoch 011 - train 0.59323 | val 0.76206
  Classification -> best τ=0.370 (val F1=0.2088)
  Directional -> Accuracy: 0.5909, MCC: 0.1056, F1: 0.7158

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.56760 | val 0.69143
  Epoch 016 - train 0.51080 | val 0.72159
  Classification -> best τ=0.540 (val F1=0.3828)
  Directional -> Accuracy: 0.5952, MCC: 0.2656, F1: 0.4516

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.55780 | val 0.80594
  Epoch 011 - train 0.55016 | val 0.81260
  Classification -> best τ=0.490 (val F1=0.1151)
  Directional -> Accuracy: 0.5536, MCC: 0.1588, F1: 0.6269

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.61201 | val 0.72475
  Epoch 011 - train 0.57306 | val 0.72713
  Classification -> best τ=0.495 (val F1=0.1022)
  Directional -> Accuracy: 0.3261, MCC: -0.2815, F1: 0.2051

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.60485 | val 0.68920
  Epoch 015 - train 0.56511 | val 0.70677
  Classification -> best τ=0.560 (val F1=0.4625)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.57095 | val 0.79611
  Epoch 012 - train 0.56755 | val 0.82970
  Classification -> best τ=0.545 (val F1=0.2271)
  Directional -> Accuracy: 0.5135, MCC: 0.0444, F1: 0.6000

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.62409 | val 0.69524
  Epoch 011 - train 0.63357 | val 0.69723
  Classification -> best τ=0.465 (val F1=0.0271)
  Directional -> Accuracy: 0.4667, MCC: -0.0709, F1: 0.2000

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.58555 | val 0.74404
  Epoch 011 - train 0.58601 | val 0.74787
  Classification -> best τ=0.505 (val F1=0.3273)
  Directional -> Accuracy: 0.4048, MCC: -0.1291, F1: 0.1935

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.59506 | val 0.78687
  Epoch 011 - train 0.59536 | val 0.79066
  Classification -> best τ=0.520 (val F1=0.1974)
  Directional -> Accuracy: 0.4792, MCC: 0.1152, F1: 0.5455

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.58954 | val 0.70400
  Epoch 011 - train 0.59324 | val 0.70375
  Classification -> best τ=0.505 (val F1=0.1884)
  Directional -> Accuracy: 0.5636, MCC: 0.1047, F1: 0.6364

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.58483 | val 1.03182
  Epoch 011 - train 0.58435 | val 1.03719
  Classification -> best τ=0.585 (val F1=0.2335)
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.6506

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.60017 | val 0.71945
  Epoch 012 - train 0.59847 | val 0.72161
  Classification -> best τ=0.535 (val F1=0.1243)
  Directional -> Accuracy: 0.6038, MCC: 0.2068, F1: 0.6182

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.59427 | val 1.34344
  Epoch 011 - train 0.58009 | val 1.36956
  Classification -> best τ=0.430 (val F1=0.3472)
  Directional -> Accuracy: 0.4909, MCC: 0.1289, F1: 0.0667

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.62152 | val 0.79825

[I 2026-02-22 17:47:09,221] Trial 267 finished with value: 0.21565202149826357 and parameters: {'feature_set': 'sector_all_nlp', 'model_type': 'BiGRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.4, 'batch_size': 16, 'learning_rate': 0.00021895846009803153, 'weight_decay': 0.0003268235329887544, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 20, 'huber_delta': 0.9612610478306816, 'early_stopping_min_delta': 0.001278783962774332}. Best is trial 252 with value: 0.3108162738957727.

  Epoch 011 - train 0.61866 | val 0.79717
  Classification -> best τ=0.545 (val F1=0.2915)
  Directional -> Accuracy: 0.6167, MCC: 0.2693, F1: 0.6761

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.21565202149826357
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.63701 | val 0.87398
  Epoch 011 - train 0.63853 | val 0.91905
  Classification -> best τ=0.460 (val F1=0.2919)
  Directional -> Accuracy: 0.6316, MCC: 0.2950, F1: 0.3333

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.56182 | val 0.95517
  Epoch 011 - train 0.50552 | val 0.94566
  Classification -> best τ=0.415 (val F1=0.2285)
  Directional -> Accuracy: 0.5778, MCC: 0.0000, F1: 0.7324

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.60864 | val 1.52987
  Epoch 011 - train 0.59036 | val 1.55682
  Classification -> best τ=0.625 (val F1=0.2311)
  Directional -> Accuracy: 0.5435, MCC: 0.1633, F1: 0.3226

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.63816 | val 1.21367
  Epoch 011 - train 0.57150 | val 1.41161
  Classification -> best τ=0.320 (val F1=0.1808)
  Directional -> Accuracy: 0.5405, MCC: 0.0000, F1: 0.7018

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.53176 | val 0.73595
  Epoch 011 - train 0.53929 | val 0.68501
  Classification -> best τ=0.575 (val F1=0.4611)
  Directional -> Accuracy: 0.6000, MCC: 0.2300, F1: 0.5238

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.54805 | val 0.95197
  Epoch 012 - train 0.47753 | val 0.90557
  Classification -> best τ=0.685 (val F1=0.2204)
  Directional -> Accuracy: 0.5217, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.61124 | val 0.90365
  Epoch 011 - train 0.60992 | val 0.97599
  Classification -> best τ=0.395 (val F1=0.3041)
  Directional -> Accuracy: 0.4853, MCC: 0.0781, F1: 0.5455

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.52443 | val 0.89114
  Epoch 018 - train 0.37663 | val 0.66303
  Classification -> best τ=0.365 (val F1=0.3632)
  Directional -> Accuracy: 0.4762, MCC: -0.1750, F1: 0.1538

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.62612 | val 1.40453
  Epoch 014 - train 0.58659 | val 1.51660
  Classification -> best τ=0.550 (val F1=0.2443)
  Directional -> Accuracy: 0.4375, MCC: -0.0263, F1: 0.5970

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.61343 | val 0.73229
  Epoch 020 - train 0.47581 | val 0.89738
  Classification -> best τ=0.445 (val F1=0.2620)
  Directional -> Accuracy: 0.5217, MCC: 0.0707, F1: 0.5217

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.62693 | val 0.81225
  Epoch 020 - train 0.53722 | val 1.12322
  Classification -> best τ=0.650 (val F1=0.3590)
  Directional -> Accuracy: 0.5918, MCC: 0.1804, F1: 0.2308

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.65134 | val 0.84561
  Epoch 013 - train 0.57423 | val 1.26297
  Classification -> best τ=0.520 (val F1=0.1528)
  Directional -> Accuracy: 0.5088, MCC: 0.0000, F1: 0.6744

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.53721 | val 0.74370
  Epoch 013 - train 0.47759 | val 1.08570
  Classification -> best τ=0.470 (val F1=0.1707)
  Directional -> Accuracy: 0.4762, MCC: -0.0389, F1: 0.4762

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.62936 | val 0.65658
  Epoch 013 - train 0.59798 | val 0.64975
  Classification -> best τ=0.425 (val F1=0.3748)
  Directional -> Accuracy: 0.5167, MCC: 0.0519, F1: 0.2162

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.61018 | val 0.75880
  Epoch 014 - train 0.55891 | val 0.69552
  Classification -> best τ=0.630 (val F1=0.2571)
  Directional -> Accuracy: 0.5490, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.63188 | val 1.39411
  Epoch 011 - train 0.58324 | val 1.47278
  Classification -> best τ=0.410 (val F1=0.1741)
  Directional -> Accuracy: 0.4783, MCC: -0.0978, F1: 0.6000

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.60659 | val 0.92900
  Epoch 011 - train 0.61491 | val 1.12795
  Classification -> best τ=0.445 (val F1=0.2429)
  Directional -> Accuracy: 0.6207, MCC: 0.0000, F1: 0.7660

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.62264 | val 1.24788
  Epoch 013 - train 0.57202 | val 1.08566
  Classification -> best τ=0.530 (val F1=0.2220)
  Directional -> Accuracy: 0.4000, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.57268 | val 0.86620
  Epoch 011 - train 0.54733 | val 0.84693
  Classification -> best τ=0.420 (val F1=0.3624)
  Directional -> Accuracy: 0.5312, MCC: 0.1253, F1: 0.4828

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.54575 | val 1.00734
  Epoch 011 - train 0.53165 | val 1.23938
  Classification -> best τ=0.390 (val F1=0.2881)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.58960 | val 0.71247
  Epoch 011 - train 0.55362 | val 0.75182
  Classification -> best τ=0.470 (val F1=0.0912)
  Directional -> Accuracy: 0.5745, MCC: -0.0834, F1: 0.7222

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.63392 | val 0.90739
  Epoch 012 - train 0.59155 | val 1.06951
  Classification -> best τ=0.570 (val F1=0.3164)
  Directional -> Accuracy: 0.4923, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.62839 | val 0.75325
  Epoch 020 - train 0.60596 | val 0.65936
  Classification -> best τ=0.470 (val F1=0.4532)
  Directional -> Accuracy: 0.5263, MCC: -0.0518, F1: 0.6667

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.62613 | val 1.07495
  Epoch 013 - train 0.59608 | val 0.77963
  Classification -> best τ=0.430 (val F1=0.2006)
  Directional -> Accuracy: 0.4923, MCC: 0.0010, F1: 0.5600

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.64640 | val 1.07368
  Epoch 017 - train 0.53129 | val 1.00322
  Classification -> best τ=0.320 (val F1=0.4839)
  Directional -> Accuracy: 0.5455, MCC: 0.0745, F1: 0.6032

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.48403 | val 2.67517
  Epoch 011 - train 0.51687 | val 2.83671
  Classification -> best τ=0.720 (val F1=0.3407)
  Directional -> Accuracy: 0.6000, MCC: 0.1350, F1: 0.3571

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.62081 | val 0.70092
  Epoch 011 - train 0.57551 | val 0.70093
  Classification -> best τ=0.575 (val F1=0.1487)
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.7273

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.55782 | val 1.30844
  Epoch 011 - train 0.57248 | val 1.50543
  Classification -> best τ=0.345 (val F1=0.2096)
  Directional -> Accuracy: 0.4821, MCC: 0.1728, F1: 0.1212

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.54298 | val 1.17813
  Epoch 011 - train 0.51178 | val 1.14856
  Classification -> best τ=0.520 (val F1=0.2414)
  Directional -> Accuracy: 0.6250, MCC: 0.3148, F1: 0.7458

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.62016 | val 0.74904
  Epoch 013 - train 0.59847 | val 0.85388
  Classification -> best τ=0.540 (val F1=0.3501)
  Directional -> Accuracy: 0.5000, MCC: 0.0092, F1: 0.5333

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.61458 | val 0.84742
  Epoch 011 - train 0.61718 | val 1.07857
  Classification -> best τ=0.550 (val F1=0.1286)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.57164 | val 0.79534
  Epoch 012 - train 0.47362 | val 0.93932
  Classification -> best τ=0.350 (val F1=0.3502)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.61246 | val 0.87906
  Epoch 013 - train 0.59578 | val 0.82832
  Classification -> best τ=0.300 (val F1=0.3366)
  Directional -> Accuracy: 0.5694, MCC: 0.1203, F1: 0.6265

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.49999 | val 1.15953
  Epoch 011 - train 0.52134 | val 1.36783
  Classification -> best τ=0.430 (val F1=0.2324)
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.60027 | val 1.52024
  Epoch 011 - train 0.59817 | val 1.51886
  Classification -> best τ=0.155 (val F1=0.2972)
  Directional -> Accuracy: 0.4848, MCC: 0.1062, F1: 0.2917

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.47898 | val 0.81605
  Epoch 011 - train 0.50283 | val 1.26557
  Classification -> best τ=0.450 (val F1=0.1715)
  Directional -> Accuracy: 0.6429, MCC: 0.2897, F1: 0.7059

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.55976 | val 0.95988
  Epoch 011 - train 0.50879 | val 0.86723
  Classification -> best τ=0.445 (val F1=0.2110)
  Directional -> Accuracy: 0.5000, MCC: 0.0103, F1: 0.5172

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.53874 | val 1.17409
  Epoch 013 - train 0.45341 | val 1.87987
  Classification -> best τ=0.605 (val F1=0.2804)
  Directional -> Accuracy: 0.3913, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.59682 | val 0.68162
  Epoch 014 - train 0.55062 | val 1.07755
  Classification -> best τ=0.565 (val F1=0.4011)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.58367 | val 1.12554
  Epoch 011 - train 0.56376 | val 1.04723
  Classification -> best τ=0.215 (val F1=0.2766)
  Directional -> Accuracy: 0.4865, MCC: 0.0000, F1: 0.6545

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.61443 | val 0.74920
  Epoch 011 - train 0.58156 | val 0.85543
  Classification -> best τ=0.585 (val F1=0.3500)
  Directional -> Accuracy: 0.6222, MCC: 0.2890, F1: 0.7119

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.47249 | val 2.22216
  Epoch 011 - train 0.46041 | val 2.28500
  Classification -> best τ=0.540 (val F1=0.3851)
  Directional -> Accuracy: 0.5714, MCC: 0.1132, F1: 0.6400

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.52947 | val 0.77783
  Epoch 011 - train 0.48324 | val 0.79379
  Classification -> best τ=0.410 (val F1=0.2605)
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.5455

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.64647 | val 1.16113
  Epoch 011 - train 0.62598 | val 1.14836
  Classification -> best τ=0.465 (val F1=0.2228)
  Directional -> Accuracy: 0.4182, MCC: -0.2155, F1: 0.5294

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.55748 | val 2.19462
  Epoch 011 - train 0.52603 | val 2.30456
  Classification -> best τ=0.680 (val F1=0.3294)
  Directional -> Accuracy: 0.5000, MCC: 0.1301, F1: 0.6585

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.64123 | val 0.75200
  Epoch 011 - train 0.61765 | val 0.72563
  Classification -> best τ=0.530 (val F1=0.2309)
  Directional -> Accuracy: 0.5849, MCC: 0.2450, F1: 0.7027

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.52492 | val 2.12794
  Epoch 011 - train 0.52153 | val 2.18370
  Classification -> best τ=0.605 (val F1=0.2306)
  Directional -> Accuracy: 0.4182, MCC: -0.1639, F1: 0.2000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.62361 | val 0.76604

[I 2026-02-22 17:50:50,572] Trial 268 finished with value: 0.27469726233096475 and parameters: {'feature_set': 'sector', 'model_type': 'BiGRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.4, 'batch_size': 16, 'learning_rate': 0.0051530333609967035, 'weight_decay': 0.0006113216958440812, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 20, 'huber_delta': 0.9318236523776403, 'early_stopping_min_delta': 0.0016285123712795762}. Best is trial 252 with value: 0.3108162738957727.

  Epoch 015 - train 0.60112 | val 0.83666
  Classification -> best τ=0.275 (val F1=0.2637)
  Directional -> Accuracy: 0.5667, MCC: 0.1346, F1: 0.5667

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.27469726233096475
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.66798 | val 0.74389
  Epoch 012 - train 0.66580 | val 0.93380
  Classification -> best τ=0.570 (val F1=0.2919)
  Directional -> Accuracy: 0.5789, MCC: 0.1225, F1: 0.2381

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.63518 | val 0.69513
  Epoch 013 - train 0.62620 | val 0.75869
  Classification -> best τ=0.445 (val F1=0.2523)
  Directional -> Accuracy: 0.6000, MCC: 0.3120, F1: 0.5263

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.69561 | val 0.67853
  Epoch 020 - train 0.69040 | val 0.70771
  Classification -> best τ=0.585 (val F1=0.2793)
  Directional -> Accuracy: 0.5217, MCC: 0.1124, F1: 0.2667

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.68944 | val 0.72161
  Epoch 017 - train 0.66907 | val 1.15915
  Classification -> best τ=0.580 (val F1=0.3069)
  Directional -> Accuracy: 0.4865, MCC: 0.1005, F1: 0.1364

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.65059 | val 0.70138
  Epoch 020 - train 0.61318 | val 0.66441
  Epoch 028 - train 0.61021 | val 0.68824
  Classification -> best τ=0.530 (val F1=0.5079)
  Directional -> Accuracy: 0.7000, MCC: 0.4048, F1: 0.6939

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.65085 | val 0.69868
  Epoch 020 - train 0.65237 | val 0.72696
  Epoch 021 - train 0.67843 | val 0.70486
  Classification -> best τ=0.555 (val F1=0.3838)
  Directional -> Accuracy: 0.5217, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.69213 | val 0.68403
  Epoch 020 - train 0.68652 | val 0.71783
  Epoch 026 - train 0.68413 | val 0.75254
  Classification -> best τ=0.575 (val F1=0.2195)
  Directional -> Accuracy: 0.5294, MCC: 0.0790, F1: 0.5000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.62078 | val 0.56612
  Epoch 020 - train 0.66688 | val 0.55318
  Epoch 022 - train 0.64304 | val 0.57757
  Classification -> best τ=0.230 (val F1=0.3158)
  Directional -> Accuracy: 0.4524, MCC: 0.1353, F1: 0.6102

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.68606 | val 0.74121
  Epoch 015 - train 0.66661 | val 0.93825
  Classification -> best τ=0.360 (val F1=0.2443)
  Directional -> Accuracy: 0.5833, MCC: 0.2322, F1: 0.6296

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.66496 | val 0.70534
  Epoch 011 - train 0.64996 | val 0.72191
  Classification -> best τ=0.495 (val F1=0.1834)
  Directional -> Accuracy: 0.4493, MCC: -0.0563, F1: 0.4865

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.70241 | val 0.67102
  Epoch 020 - train 0.67326 | val 0.69093
  Classification -> best τ=0.425 (val F1=0.4059)
  Directional -> Accuracy: 0.5918, MCC: 0.1804, F1: 0.2308

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.69163 | val 0.72875
  Epoch 020 - train 0.68438 | val 0.79614
  Epoch 024 - train 0.69130 | val 0.72564
  Classification -> best τ=0.580 (val F1=0.3307)
  Directional -> Accuracy: 0.5789, MCC: 0.1576, F1: 0.5862

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.70480 | val 0.65976
  Epoch 020 - train 0.53363 | val 0.69349
  Epoch 024 - train 0.49529 | val 0.72069
  Classification -> best τ=0.575 (val F1=0.4105)
  Directional -> Accuracy: 0.5476, MCC: 0.0000, F1: 0.0000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.67705 | val 0.89320
  Epoch 012 - train 0.64907 | val 0.99238
  Classification -> best τ=0.375 (val F1=0.0116)
  Directional -> Accuracy: 0.5500, MCC: 0.1558, F1: 0.2703

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.66019 | val 0.69904
  Epoch 011 - train 0.64578 | val 0.71673
  Classification -> best τ=0.445 (val F1=0.2381)
  Directional -> Accuracy: 0.5490, MCC: 0.1177, F1: 0.5660

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.68811 | val 0.72243
  Epoch 020 - train 0.69170 | val 0.63907
  Epoch 023 - train 0.67089 | val 0.74358
  Classification -> best τ=0.520 (val F1=0.5469)
  Directional -> Accuracy: 0.6522, MCC: 0.2992, F1: 0.7143

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.67773 | val 0.71350
  Epoch 018 - train 0.66227 | val 0.74929
  Classification -> best τ=0.505 (val F1=0.2569)
  Directional -> Accuracy: 0.3966, MCC: -0.1358, F1: 0.3636

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.69461 | val 0.69725
  Epoch 018 - train 0.67415 | val 0.69479
  Classification -> best τ=0.615 (val F1=0.2082)
  Directional -> Accuracy: 0.4000, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.67007 | val 0.72405
  Epoch 020 - train 0.68004 | val 0.71758
  Epoch 026 - train 0.66609 | val 0.84700
  Classification -> best τ=0.440 (val F1=0.3229)
  Directional -> Accuracy: 0.4844, MCC: 0.1062, F1: 0.2979

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.63930 | val 0.80190
  Epoch 011 - train 0.62314 | val 0.74031
  Classification -> best τ=0.480 (val F1=0.2617)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.66143 | val 0.69010
  Epoch 020 - train 0.66923 | val 0.68893
  Epoch 024 - train 0.64787 | val 0.75154
  Classification -> best τ=0.410 (val F1=0.3251)
  Directional -> Accuracy: 0.6383, MCC: 0.1848, F1: 0.7385

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.69675 | val 0.72984
  Epoch 016 - train 0.68951 | val 0.72192
  Classification -> best τ=0.420 (val F1=0.2019)
  Directional -> Accuracy: 0.5077, MCC: 0.0000, F1: 0.6735

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.68346 | val 0.68750
  Epoch 015 - train 0.67790 | val 0.67007
  Classification -> best τ=0.690 (val F1=0.3550)
  Directional -> Accuracy: 0.4912, MCC: 0.0250, F1: 0.4314

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.68607 | val 0.70148
  Epoch 014 - train 0.68837 | val 0.69638
  Classification -> best τ=0.550 (val F1=0.1393)
  Directional -> Accuracy: 0.5231, MCC: 0.0000, F1: 0.0000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.68578 | val 0.65878
  Epoch 018 - train 0.66102 | val 0.62892
  Classification -> best τ=0.315 (val F1=0.4607)
  Directional -> Accuracy: 0.5091, MCC: 0.0133, F1: 0.5424

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.65786 | val 1.32121
  Epoch 011 - train 0.67584 | val 1.41292
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.5938

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.67217 | val 0.70458
  Epoch 020 - train 0.67476 | val 0.71019
  Epoch 024 - train 0.67570 | val 0.80120
  Classification -> best τ=0.545 (val F1=0.2402)
  Directional -> Accuracy: 0.4762, MCC: 0.0000, F1: 0.4211

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.68427 | val 0.68274
  Epoch 018 - train 0.65597 | val 0.66659
  Classification -> best τ=0.500 (val F1=0.3430)
  Directional -> Accuracy: 0.4464, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.64408 | val 1.04980
  Epoch 011 - train 0.60834 | val 1.05519
  Classification -> best τ=0.555 (val F1=0.1608)
  Directional -> Accuracy: 0.6250, MCC: 0.2659, F1: 0.7368

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.67749 | val 0.66477
  Epoch 020 - train 0.66172 | val 0.68965
  Classification -> best τ=0.595 (val F1=0.3501)
  Directional -> Accuracy: 0.4524, MCC: -0.1064, F1: 0.3784

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.70513 | val 0.65782
  Epoch 020 - train 0.69211 | val 0.70425
  Epoch 021 - train 0.68357 | val 0.71266
  Classification -> best τ=0.670 (val F1=0.1470)
  Directional -> Accuracy: 0.5000, MCC: -0.0976, F1: 0.6441

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.68852 | val 0.74375
  Epoch 020 - train 0.66266 | val 0.71092
  Epoch 027 - train 0.61578 | val 0.75978
  Classification -> best τ=0.325 (val F1=0.3541)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.71040 | val 0.70348
  Epoch 012 - train 0.68886 | val 0.69263
  Classification -> best τ=0.410 (val F1=0.3145)
  Directional -> Accuracy: 0.4028, MCC: -0.2133, F1: 0.4691

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.65617 | val 0.86036
  Epoch 012 - train 0.63406 | val 0.99672
  Classification -> best τ=0.545 (val F1=0.2151)
  Directional -> Accuracy: 0.5814, MCC: 0.1993, F1: 0.3571

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.68514 | val 0.79437
  Epoch 013 - train 0.65547 | val 0.76057
  Classification -> best τ=0.460 (val F1=0.3899)
  Directional -> Accuracy: 0.5000, MCC: 0.1168, F1: 0.3529

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.68906 | val 0.69066
  Epoch 013 - train 0.69788 | val 0.73641
  Classification -> best τ=0.485 (val F1=0.2439)
  Directional -> Accuracy: 0.5238, MCC: 0.0337, F1: 0.6000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.66710 | val 0.76290
  Epoch 014 - train 0.61448 | val 0.89841
  Classification -> best τ=0.445 (val F1=0.2110)
  Directional -> Accuracy: 0.5536, MCC: 0.1377, F1: 0.6032

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.64140 | val 0.78428
  Epoch 014 - train 0.68657 | val 0.67980
  Classification -> best τ=0.345 (val F1=0.3906)
  Directional -> Accuracy: 0.6087, MCC: 0.0000, F1: 0.7568

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.66746 | val 0.68562
  Epoch 020 - train 0.67721 | val 0.64899
  Epoch 030 - train 0.63434 | val 0.68970
  Classification -> best τ=0.450 (val F1=0.4011)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.65866 | val 0.79379
  Epoch 011 - train 0.63732 | val 0.91229
  Classification -> best τ=0.540 (val F1=0.2547)
  Directional -> Accuracy: 0.5811, MCC: 0.1609, F1: 0.5079

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.71108 | val 0.68675
  Epoch 016 - train 0.66561 | val 0.68714
  Classification -> best τ=0.470 (val F1=0.3953)
  Directional -> Accuracy: 0.5556, MCC: 0.2205, F1: 0.6970

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.59915 | val 0.80677
  Epoch 020 - train 0.53134 | val 0.81031
  Epoch 022 - train 0.57948 | val 1.03149
  Classification -> best τ=0.410 (val F1=0.5092)
  Directional -> Accuracy: 0.6190, MCC: 0.2041, F1: 0.6923

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.67278 | val 0.69655
  Epoch 014 - train 0.58374 | val 0.67830
  Classification -> best τ=0.620 (val F1=0.4606)
  Directional -> Accuracy: 0.3958, MCC: -0.0457, F1: 0.5085

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.69444 | val 0.69728
  Epoch 014 - train 0.69405 | val 0.69249
  Classification -> best τ=0.530 (val F1=0.2291)
  Directional -> Accuracy: 0.5455, MCC: 0.0319, F1: 0.6835

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.67264 | val 0.82065
  Epoch 012 - train 0.63671 | val 0.82574
  Classification -> best τ=0.565 (val F1=0.4621)
  Directional -> Accuracy: 0.4643, MCC: -0.0620, F1: 0.5588

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.69963 | val 0.67527
  Epoch 016 - train 0.69955 | val 0.68830
  Classification -> best τ=0.545 (val F1=0.1847)
  Directional -> Accuracy: 0.5094, MCC: 0.0000, F1: 0.6750

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.67831 | val 1.03358
  Epoch 013 - train 0.62020 | val 0.85087
  Classification -> best τ=0.500 (val F1=0.1780)
  Directional -> Accuracy: 0.4545, MCC: -0.1475, F1: 0.5833

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.68962 | val 0.68081

[I 2026-02-22 17:53:56,998] Trial 269 finished with value: 0.29450262742943556 and parameters: {'feature_set': 'sector', 'model_type': 'LSTM', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.4, 'batch_size': 16, 'learning_rate': 0.009966175170973568, 'weight_decay': 0.0008022489542715065, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 0.98406082965756, 'early_stopping_min_delta': 0.0009680029844720023}. Best is trial 252 with value: 0.3108162738957727.

  Epoch 018 - train 0.67783 | val 0.67696
  Classification -> best τ=0.485 (val F1=0.2407)
  Directional -> Accuracy: 0.5167, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.29450262742943556
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down', 'finbert_neutral']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.65132 | val 0.65959
  Epoch 020 - train 0.63310 | val 0.97230
  Classification -> best τ=0.530 (val F1=0.2919)
  Directional -> Accuracy: 0.5132, MCC: -0.0841, F1: 0.1395

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.64116 | val 1.05128
  Epoch 014 - train 0.59943 | val 0.84507
  Classification -> best τ=0.495 (val F1=0.1764)
  Directional -> Accuracy: 0.5778, MCC: 0.0842, F1: 0.6885

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.61218 | val 0.86605
  Epoch 013 - train 0.56107 | val 0.79359
  Classification -> best τ=0.585 (val F1=0.4178)
  Directional -> Accuracy: 0.5870, MCC: 0.2307, F1: 0.4571

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.65702 | val 0.76118
  Epoch 020 - train 0.65205 | val 1.00433
  Classification -> best τ=0.570 (val F1=0.0839)
  Directional -> Accuracy: 0.5135, MCC: -0.1537, F1: 0.6786

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.64244 | val 0.65735
  Epoch 012 - train 0.57466 | val 0.68092
  Classification -> best τ=0.410 (val F1=0.4947)
  Directional -> Accuracy: 0.6400, MCC: 0.2871, F1: 0.6250

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.57161 | val 0.78207
  Epoch 016 - train 0.48971 | val 0.96984
  Classification -> best τ=0.555 (val F1=0.2739)
  Directional -> Accuracy: 0.5435, MCC: 0.0851, F1: 0.2222

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.65056 | val 1.04276
  Epoch 011 - train 0.61570 | val 1.30731
  Classification -> best τ=0.505 (val F1=0.2536)
  Directional -> Accuracy: 0.5147, MCC: 0.0819, F1: 0.5217

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.52579 | val 0.80232
  Epoch 016 - train 0.44988 | val 0.84832
  Classification -> best τ=0.535 (val F1=0.5247)
  Directional -> Accuracy: 0.5238, MCC: -0.1936, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.67062 | val 1.36343
  Epoch 011 - train 0.60541 | val 1.08343
  Classification -> best τ=0.610 (val F1=0.3380)
  Directional -> Accuracy: 0.5417, MCC: -0.1286, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.64516 | val 0.73486
  Epoch 016 - train 0.61554 | val 0.77869
  Classification -> best τ=0.560 (val F1=0.3131)
  Directional -> Accuracy: 0.4493, MCC: 0.0034, F1: 0.5581

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.60950 | val 0.81577
  Epoch 011 - train 0.60792 | val 0.91167
  Classification -> best τ=0.365 (val F1=0.1987)
  Directional -> Accuracy: 0.6531, MCC: 0.3350, F1: 0.4138

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.67564 | val 0.75528
  Epoch 014 - train 0.61329 | val 1.18020
  Classification -> best τ=0.620 (val F1=0.3827)
  Directional -> Accuracy: 0.6140, MCC: 0.2849, F1: 0.7105

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.65661 | val 0.89800
  Epoch 013 - train 0.57400 | val 1.00851
  Classification -> best τ=0.480 (val F1=0.1878)
  Directional -> Accuracy: 0.4286, MCC: -0.1194, F1: 0.5862

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.67106 | val 0.93697
  Epoch 020 - train 0.66381 | val 0.81477
  Classification -> best τ=0.590 (val F1=0.2845)
  Directional -> Accuracy: 0.4500, MCC: -0.1214, F1: 0.2326

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.61400 | val 0.72761
  Epoch 020 - train 0.44857 | val 0.96600
  Classification -> best τ=0.410 (val F1=0.3213)
  Directional -> Accuracy: 0.5294, MCC: -0.0591, F1: 0.0769

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.66852 | val 0.71484
  Epoch 020 - train 0.67017 | val 0.66554
  Classification -> best τ=0.340 (val F1=0.3849)
  Directional -> Accuracy: 0.5362, MCC: 0.0000, F1: 0.6981

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.67603 | val 0.89284
  Epoch 014 - train 0.66536 | val 0.91424
  Classification -> best τ=0.820 (val F1=0.1842)
  Directional -> Accuracy: 0.3793, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.64534 | val 0.84414
  Epoch 014 - train 0.63368 | val 1.25946
  Classification -> best τ=0.555 (val F1=0.2220)
  Directional -> Accuracy: 0.4000, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.67148 | val 0.73083
  Epoch 012 - train 0.67417 | val 0.72761
  Classification -> best τ=0.560 (val F1=0.1495)
  Directional -> Accuracy: 0.4375, MCC: 0.0398, F1: 0.1000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.64907 | val 1.02134
  Epoch 012 - train 0.59283 | val 0.91918
  Classification -> best τ=0.425 (val F1=0.2871)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.63983 | val 0.68797
  Epoch 016 - train 0.57691 | val 0.69159
  Classification -> best τ=0.495 (val F1=0.3678)
  Directional -> Accuracy: 0.5957, MCC: 0.0615, F1: 0.7164

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.66705 | val 0.84982
  Epoch 013 - train 0.67232 | val 0.76663
  Classification -> best τ=0.270 (val F1=0.2371)
  Directional -> Accuracy: 0.5231, MCC: 0.0767, F1: 0.6737

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.67634 | val 0.76471
  Epoch 012 - train 0.65122 | val 0.73428
  Classification -> best τ=0.590 (val F1=0.2478)
  Directional -> Accuracy: 0.5088, MCC: 0.1095, F1: 0.3636

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.66595 | val 0.75817
  Epoch 015 - train 0.67026 | val 0.72283
  Classification -> best τ=0.470 (val F1=0.2826)
  Directional -> Accuracy: 0.5692, MCC: 0.1622, F1: 0.6216

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.62346 | val 0.92560
  Epoch 011 - train 0.56764 | val 0.85171
  Classification -> best τ=0.495 (val F1=0.3436)
  Directional -> Accuracy: 0.4182, MCC: -0.1415, F1: 0.3333

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.48847 | val 2.91705
  Epoch 012 - train 0.38237 | val 3.59836
  Classification -> best τ=0.610 (val F1=0.2035)
  Directional -> Accuracy: 0.5778, MCC: 0.0732, F1: 0.2963

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.62403 | val 0.79186
  Epoch 020 - train 0.58209 | val 0.75787
  Classification -> best τ=0.635 (val F1=0.1171)
  Directional -> Accuracy: 0.4762, MCC: 0.1936, F1: 0.1538

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.64364 | val 0.94633
  Epoch 013 - train 0.55784 | val 1.08419
  Classification -> best τ=0.505 (val F1=0.2724)
  Directional -> Accuracy: 0.4464, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.55991 | val 0.91651
  Epoch 011 - train 0.56865 | val 0.94024
  Classification -> best τ=0.480 (val F1=0.2414)
  Directional -> Accuracy: 0.6500, MCC: 0.3685, F1: 0.7586

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.66824 | val 0.80346
  Epoch 016 - train 0.56799 | val 1.09618
  Classification -> best τ=0.615 (val F1=0.4594)
  Directional -> Accuracy: 0.4286, MCC: -0.1589, F1: 0.3333

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.61995 | val 0.67174
  Epoch 020 - train 0.64057 | val 1.11637
  Classification -> best τ=0.690 (val F1=0.4653)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.62290 | val 0.72115
  Epoch 011 - train 0.56195 | val 0.73005
  Classification -> best τ=0.375 (val F1=0.3541)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.69303 | val 0.74006
  Epoch 011 - train 0.67642 | val 0.72019
  Classification -> best τ=0.505 (val F1=0.2853)
  Directional -> Accuracy: 0.4306, MCC: -0.0839, F1: 0.1277

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.60417 | val 1.29267
  Epoch 011 - train 0.57740 | val 1.46726
  Classification -> best τ=0.335 (val F1=0.1874)
  Directional -> Accuracy: 0.5581, MCC: 0.2676, F1: 0.6885

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.65389 | val 0.74600
  Epoch 011 - train 0.57928 | val 0.96185
  Classification -> best τ=0.450 (val F1=0.3099)
  Directional -> Accuracy: 0.5152, MCC: 0.0353, F1: 0.5429

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.61520 | val 0.59401
  Epoch 020 - train 0.35417 | val 2.61986
  Classification -> best τ=0.435 (val F1=0.4647)
  Directional -> Accuracy: 0.6667, MCC: 0.3318, F1: 0.6818

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.60657 | val 0.88247
  Epoch 011 - train 0.58813 | val 0.95098
  Classification -> best τ=0.455 (val F1=0.2114)
  Directional -> Accuracy: 0.5179, MCC: 0.0283, F1: 0.4706

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.58333 | val 1.05841
  Epoch 011 - train 0.57869 | val 0.83108
  Classification -> best τ=0.450 (val F1=0.3050)
  Directional -> Accuracy: 0.4348, MCC: -0.0094, F1: 0.3158

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.65462 | val 1.14345
  Epoch 012 - train 0.50237 | val 0.84466
  Classification -> best τ=0.740 (val F1=0.4710)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.65994 | val 0.75010
  Epoch 011 - train 0.64975 | val 0.84537
  Classification -> best τ=0.425 (val F1=0.3597)
  Directional -> Accuracy: 0.4865, MCC: 0.0000, F1: 0.6545

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.64846 | val 0.68828
  Epoch 020 - train 0.57332 | val 0.70136
  Classification -> best τ=0.480 (val F1=0.4348)
  Directional -> Accuracy: 0.5778, MCC: 0.1613, F1: 0.6545

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.59329 | val 1.09732
  Epoch 011 - train 0.57683 | val 1.10932
  Classification -> best τ=0.505 (val F1=0.1307)
  Directional -> Accuracy: 0.5238, MCC: -0.0323, F1: 0.6429

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.60026 | val 0.77517
  Epoch 016 - train 0.52411 | val 1.22901
  Classification -> best τ=0.320 (val F1=0.2605)
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.5455

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.64782 | val 0.80884
  Epoch 011 - train 0.61232 | val 1.02365
  Classification -> best τ=0.545 (val F1=0.1474)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.60113 | val 1.90991
  Epoch 011 - train 0.61769 | val 1.84720
  Classification -> best τ=0.660 (val F1=0.2187)
  Directional -> Accuracy: 0.4821, MCC: -0.0099, F1: 0.6329

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.68860 | val 0.69743
  Epoch 012 - train 0.67033 | val 0.73048
  Classification -> best τ=0.545 (val F1=0.1668)
  Directional -> Accuracy: 0.5849, MCC: 0.1712, F1: 0.5769

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.60934 | val 1.85171
  Epoch 011 - train 0.59210 | val 1.76164
  Classification -> best τ=0.670 (val F1=0.2291)
  Directional -> Accuracy: 0.4727, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.66017 | val 0.68452

[I 2026-02-22 17:57:56,039] Trial 270 finished with value: 0.2886694577500188 and parameters: {'feature_set': 'finbert', 'model_type': 'BiGRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.4, 'batch_size': 16, 'learning_rate': 0.009941220291756312, 'weight_decay': 0.000890944914747773, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 20, 'huber_delta': 1.004884184309852, 'early_stopping_min_delta': 0.000927723408262927}. Best is trial 252 with value: 0.3108162738957727.

  Epoch 015 - train 0.63515 | val 0.68467
  Classification -> best τ=0.475 (val F1=0.3108)
  Directional -> Accuracy: 0.5167, MCC: 0.0089, F1: 0.1212

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2886694577500188
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down', 'finbert_neutral']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.65395 | val 0.98773
  Epoch 013 - train 0.57564 | val 0.88411
  Classification -> best τ=0.515 (val F1=0.2510)
  Directional -> Accuracy: 0.5263, MCC: -0.0671, F1: 0.1000

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.61700 | val 0.75233
  Epoch 013 - train 0.58866 | val 0.77675
  Classification -> best τ=0.340 (val F1=0.1844)
  Directional -> Accuracy: 0.5778, MCC: 0.0000, F1: 0.7324

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.59358 | val 0.72996
  Epoch 011 - train 0.55606 | val 0.90596
  Classification -> best τ=0.500 (val F1=0.2871)
  Directional -> Accuracy: 0.5435, MCC: 0.0756, F1: 0.6316

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.67130 | val 0.98081
  Epoch 011 - train 0.66045 | val 1.11383
  Classification -> best τ=0.465 (val F1=0.0855)
  Directional -> Accuracy: 0.5405, MCC: 0.0000, F1: 0.7018

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.67172 | val 1.03978
  Epoch 012 - train 0.64988 | val 0.74374
  Classification -> best τ=0.640 (val F1=0.5250)
  Directional -> Accuracy: 0.4800, MCC: -0.0082, F1: 0.0714

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.58774 | val 0.77823
  Epoch 013 - train 0.49292 | val 0.91969
  Classification -> best τ=0.490 (val F1=0.3222)
  Directional -> Accuracy: 0.5652, MCC: 0.1374, F1: 0.5833

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.67760 | val 0.77740
  Epoch 013 - train 0.61093 | val 0.80797
  Classification -> best τ=0.575 (val F1=0.1923)
  Directional -> Accuracy: 0.5735, MCC: 0.1150, F1: 0.4727

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.50321 | val 0.54416
  Epoch 020 - train 0.33414 | val 1.51153
  Classification -> best τ=0.225 (val F1=0.3855)
  Directional -> Accuracy: 0.6190, MCC: 0.2340, F1: 0.5789

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.55219 | val 2.18943
  Epoch 012 - train 0.45765 | val 1.52121
  Classification -> best τ=0.270 (val F1=0.2497)
  Directional -> Accuracy: 0.4375, MCC: 0.0000, F1: 0.6087

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.61847 | val 0.73650
  Epoch 017 - train 0.55763 | val 0.74126
  Classification -> best τ=0.540 (val F1=0.3268)
  Directional -> Accuracy: 0.5362, MCC: 0.1057, F1: 0.5429

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.64877 | val 0.98410
  Epoch 012 - train 0.58033 | val 1.50733
  Classification -> best τ=0.550 (val F1=0.2593)
  Directional -> Accuracy: 0.6122, MCC: 0.2076, F1: 0.3871

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.66455 | val 0.88763
  Epoch 018 - train 0.58756 | val 0.72636
  Classification -> best τ=0.665 (val F1=0.3307)
  Directional -> Accuracy: 0.6140, MCC: 0.2849, F1: 0.7105

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.54468 | val 0.77935
  Epoch 011 - train 0.48090 | val 0.73352
  Classification -> best τ=0.460 (val F1=0.2522)
  Directional -> Accuracy: 0.4286, MCC: -0.1083, F1: 0.5385

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.67542 | val 1.05538
  Epoch 012 - train 0.65848 | val 1.29314
  Classification -> best τ=0.315 (val F1=0.2574)
  Directional -> Accuracy: 0.5833, MCC: 0.1925, F1: 0.6667

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.64074 | val 0.69663
  Epoch 014 - train 0.53863 | val 0.81086
  Classification -> best τ=0.480 (val F1=0.2245)
  Directional -> Accuracy: 0.6275, MCC: 0.2806, F1: 0.3448

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.64636 | val 0.66235
  Epoch 012 - train 0.59295 | val 0.90236
  Classification -> best τ=0.345 (val F1=0.2998)
  Directional -> Accuracy: 0.5652, MCC: 0.1171, F1: 0.6939

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.68321 | val 0.85317
  Epoch 014 - train 0.64595 | val 0.81478
  Classification -> best τ=0.570 (val F1=0.2276)
  Directional -> Accuracy: 0.4138, MCC: 0.1477, F1: 0.1053

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.64588 | val 0.69011
  Epoch 015 - train 0.65750 | val 0.72634
  Classification -> best τ=0.430 (val F1=0.2182)
  Directional -> Accuracy: 0.6133, MCC: 0.1900, F1: 0.6813

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.63901 | val 0.73051
  Epoch 017 - train 0.64273 | val 0.74051
  Classification -> best τ=0.320 (val F1=0.2522)
  Directional -> Accuracy: 0.4688, MCC: 0.0725, F1: 0.2609

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.63937 | val 1.34968
  Epoch 012 - train 0.60849 | val 1.08807
  Classification -> best τ=0.545 (val F1=0.2937)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.62555 | val 0.72458
  Epoch 016 - train 0.57304 | val 0.81862
  Classification -> best τ=0.455 (val F1=0.2871)
  Directional -> Accuracy: 0.4468, MCC: -0.1250, F1: 0.5185

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.68735 | val 0.93087
  Epoch 011 - train 0.64774 | val 0.89754
  Classification -> best τ=0.350 (val F1=0.1225)
  Directional -> Accuracy: 0.4308, MCC: -0.1377, F1: 0.4127

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.64828 | val 0.77960
  Epoch 016 - train 0.61013 | val 1.20895
  Classification -> best τ=0.695 (val F1=0.2964)
  Directional -> Accuracy: 0.4561, MCC: 0.0076, F1: 0.2051

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.66483 | val 0.80225
  Epoch 016 - train 0.61185 | val 1.08591
  Classification -> best τ=0.455 (val F1=0.0268)
  Directional -> Accuracy: 0.4615, MCC: -0.0631, F1: 0.5977

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.58448 | val 0.84136
  Epoch 016 - train 0.63298 | val 1.10709
  Classification -> best τ=0.455 (val F1=0.3887)
  Directional -> Accuracy: 0.5091, MCC: 0.0575, F1: 0.4255

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.57353 | val 4.69401
  Epoch 011 - train 0.51637 | val 3.98976
  Classification -> best τ=0.695 (val F1=0.2097)
  Directional -> Accuracy: 0.5778, MCC: 0.0000, F1: 0.0000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.62484 | val 0.95661
  Epoch 015 - train 0.58524 | val 0.81508
  Classification -> best τ=0.565 (val F1=0.1803)
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.7273

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.60090 | val 1.15968
  Epoch 011 - train 0.57912 | val 1.33851
  Classification -> best τ=0.320 (val F1=0.2892)
  Directional -> Accuracy: 0.5536, MCC: 0.2311, F1: 0.3902

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.45128 | val 1.67263
  Epoch 011 - train 0.49271 | val 2.33935
  Classification -> best τ=0.540 (val F1=0.0836)
  Directional -> Accuracy: 0.6000, MCC: 0.2121, F1: 0.6000

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.57988 | val 0.63650
  Epoch 019 - train 0.47108 | val 0.87096
  Classification -> best τ=0.680 (val F1=0.4110)
  Directional -> Accuracy: 0.5000, MCC: 0.0258, F1: 0.5882

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.62258 | val 0.66338
  Epoch 020 - train 0.59794 | val 0.89762
  Classification -> best τ=0.535 (val F1=0.2544)
  Directional -> Accuracy: 0.5000, MCC: -0.0976, F1: 0.6441

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.56998 | val 0.87351
  Epoch 011 - train 0.53010 | val 0.80372
  Classification -> best τ=0.520 (val F1=0.2521)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.67207 | val 0.67628
  Epoch 020 - train 0.64108 | val 0.69026
  Classification -> best τ=0.285 (val F1=0.4032)
  Directional -> Accuracy: 0.5556, MCC: 0.1323, F1: 0.5429

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.58478 | val 1.39535
  Epoch 013 - train 0.45474 | val 1.28826
  Classification -> best τ=0.630 (val F1=0.2078)
  Directional -> Accuracy: 0.4419, MCC: -0.1366, F1: 0.2941

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.60403 | val 0.88277
  Epoch 011 - train 0.59921 | val 0.99216
  Classification -> best τ=0.500 (val F1=0.2228)
  Directional -> Accuracy: 0.4242, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.51705 | val 0.76182
  Epoch 019 - train 0.29561 | val 2.37056
  Classification -> best τ=0.415 (val F1=0.4647)
  Directional -> Accuracy: 0.6190, MCC: 0.2337, F1: 0.6667

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.56307 | val 1.06797
  Epoch 011 - train 0.55307 | val 0.83600
  Classification -> best τ=0.330 (val F1=0.2371)
  Directional -> Accuracy: 0.4464, MCC: -0.0925, F1: 0.4918

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.52358 | val 0.97609
  Epoch 011 - train 0.48295 | val 0.93748
  Classification -> best τ=0.490 (val F1=0.4012)
  Directional -> Accuracy: 0.5435, MCC: 0.0511, F1: 0.6182

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.54640 | val 0.91606
  Epoch 013 - train 0.43291 | val 0.90300
  Classification -> best τ=0.555 (val F1=0.4688)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.63226 | val 0.95767
  Epoch 013 - train 0.60407 | val 1.37718
  Classification -> best τ=0.570 (val F1=0.2626)
  Directional -> Accuracy: 0.5405, MCC: 0.0855, F1: 0.5641

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.56054 | val 1.01573
  Epoch 012 - train 0.57698 | val 0.69005
  Classification -> best τ=0.425 (val F1=0.3371)
  Directional -> Accuracy: 0.4667, MCC: -0.0667, F1: 0.2500

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.55796 | val 0.70380
  Epoch 019 - train 0.56724 | val 1.43329
  Classification -> best τ=0.575 (val F1=0.5819)
  Directional -> Accuracy: 0.5000, MCC: 0.0595, F1: 0.4324

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.56629 | val 0.76478
  Epoch 011 - train 0.52762 | val 0.79171
  Classification -> best τ=0.455 (val F1=0.3410)
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.5455

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.62722 | val 0.85745
  Epoch 019 - train 0.56737 | val 0.86415
  Classification -> best τ=0.530 (val F1=0.2036)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.62315 | val 1.12637
  Epoch 013 - train 0.51699 | val 1.76083
  Classification -> best τ=0.505 (val F1=0.3249)
  Directional -> Accuracy: 0.5536, MCC: 0.1072, F1: 0.5455

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.68234 | val 0.73862
  Epoch 020 - train 0.63447 | val 0.71008
  Classification -> best τ=0.600 (val F1=0.0381)
  Directional -> Accuracy: 0.5283, MCC: 0.0546, F1: 0.5614

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.60305 | val 1.61634
  Epoch 011 - train 0.58998 | val 2.18257
  Classification -> best τ=0.625 (val F1=0.1026)
  Directional -> Accuracy: 0.5273, MCC: 0.0289, F1: 0.6389

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.68242 | val 0.68883

[I 2026-02-22 18:01:56,641] Trial 271 finished with value: 0.27218722920438904 and parameters: {'feature_set': 'finbert', 'model_type': 'BiGRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.4, 'batch_size': 16, 'learning_rate': 0.009806529360848033, 'weight_decay': 0.0005802054855903234, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 20, 'huber_delta': 0.9308459479300895, 'early_stopping_min_delta': 0.0008940628492148757}. Best is trial 252 with value: 0.3108162738957727.

  Epoch 020 - train 0.62313 | val 0.68064
  Classification -> best τ=0.485 (val F1=0.2407)
  Directional -> Accuracy: 0.6833, MCC: 0.3714, F1: 0.6275

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.27218722920438904
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down', 'finbert_neutral']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.69349 | val 0.78788
  Epoch 011 - train 0.67916 | val 0.76212
  Classification -> best τ=0.545 (val F1=0.2036)
  Directional -> Accuracy: 0.5526, MCC: 0.0000, F1: 0.0000

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.67263 | val 0.71961
  Epoch 020 - train 0.62303 | val 0.83953
  Classification -> best τ=0.475 (val F1=0.1289)
  Directional -> Accuracy: 0.5778, MCC: 0.0000, F1: 0.7324

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.68355 | val 0.66622
  Epoch 020 - train 0.66319 | val 0.64195
  Classification -> best τ=0.535 (val F1=0.3894)
  Directional -> Accuracy: 0.4348, MCC: -0.1679, F1: 0.0714

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.68076 | val 1.05151
  Epoch 014 - train 0.66871 | val 0.80705
  Classification -> best τ=0.520 (val F1=0.1143)
  Directional -> Accuracy: 0.4730, MCC: -0.0542, F1: 0.4935

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.69196 | val 0.80748
  Epoch 013 - train 0.66449 | val 0.64118
  Classification -> best τ=0.625 (val F1=0.5298)
  Directional -> Accuracy: 0.7200, MCC: 0.4704, F1: 0.6818

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.67675 | val 0.87743
  Epoch 011 - train 0.67733 | val 0.75211
  Classification -> best τ=0.470 (val F1=0.2204)
  Directional -> Accuracy: 0.5217, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.68785 | val 0.70852
  Epoch 020 - train 0.67352 | val 0.95532
  Classification -> best τ=0.490 (val F1=0.2827)
  Directional -> Accuracy: 0.5147, MCC: 0.0301, F1: 0.4590

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.70374 | val 0.75553
  Epoch 015 - train 0.67143 | val 0.83636
  Classification -> best τ=0.390 (val F1=0.1147)
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.68872 | val 0.73034
  Epoch 013 - train 0.66269 | val 0.78208
  Classification -> best τ=0.395 (val F1=0.1975)
  Directional -> Accuracy: 0.4375, MCC: 0.0000, F1: 0.6087

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.65709 | val 0.71325
  Epoch 012 - train 0.66933 | val 0.69529
  Classification -> best τ=0.570 (val F1=0.3288)
  Directional -> Accuracy: 0.4783, MCC: -0.0232, F1: 0.4706

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.69567 | val 0.68393
  Epoch 019 - train 0.67915 | val 0.73655
  Classification -> best τ=0.390 (val F1=0.1965)
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.69253 | val 0.69181
  Epoch 020 - train 0.69075 | val 0.68666
  Classification -> best τ=0.560 (val F1=0.3307)
  Directional -> Accuracy: 0.5263, MCC: 0.0939, F1: 0.2703

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.60555 | val 1.00678
  Epoch 011 - train 0.62569 | val 1.02970
  Classification -> best τ=0.520 (val F1=0.3553)
  Directional -> Accuracy: 0.6190, MCC: 0.2981, F1: 0.6667

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.69013 | val 0.67515
  Epoch 020 - train 0.69316 | val 0.69115
  Classification -> best τ=0.415 (val F1=0.3477)
  Directional -> Accuracy: 0.5667, MCC: 0.1414, F1: 0.4800

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.67840 | val 0.72045
  Epoch 019 - train 0.66763 | val 0.69521
  Classification -> best τ=0.555 (val F1=0.2571)
  Directional -> Accuracy: 0.5490, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.70414 | val 0.68151
  Epoch 017 - train 0.66184 | val 0.70059
  Classification -> best τ=0.595 (val F1=0.2294)
  Directional -> Accuracy: 0.4928, MCC: 0.0526, F1: 0.2553

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.67501 | val 0.75842
  Epoch 015 - train 0.68929 | val 0.72917
  Classification -> best τ=0.600 (val F1=0.2651)
  Directional -> Accuracy: 0.3793, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.67520 | val 0.74476
  Epoch 014 - train 0.68136 | val 0.69222
  Classification -> best τ=0.495 (val F1=0.1893)
  Directional -> Accuracy: 0.6000, MCC: 0.0338, F1: 0.7458

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.67990 | val 0.69940
  Epoch 013 - train 0.68559 | val 0.70910
  Classification -> best τ=0.585 (val F1=0.2600)
  Directional -> Accuracy: 0.4219, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.65077 | val 0.85180
  Epoch 011 - train 0.65223 | val 0.77902
  Classification -> best τ=0.445 (val F1=0.1673)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.69574 | val 0.77419
  Epoch 011 - train 0.68011 | val 0.81887
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.6170, MCC: 0.0000, F1: 0.7632

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.68743 | val 0.69553
  Epoch 013 - train 0.69269 | val 0.70130
  Classification -> best τ=0.585 (val F1=0.2044)
  Directional -> Accuracy: 0.4769, MCC: -0.0550, F1: 0.1500

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.69837 | val 0.68686
  Epoch 020 - train 0.69795 | val 0.71072
  Classification -> best τ=0.540 (val F1=0.2644)
  Directional -> Accuracy: 0.4912, MCC: 0.0739, F1: 0.3256

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.68962 | val 0.77254
  Epoch 013 - train 0.68159 | val 1.16120
  Classification -> best τ=0.460 (val F1=0.2675)
  Directional -> Accuracy: 0.4769, MCC: 0.0000, F1: 0.6458

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.65512 | val 0.65478
  Epoch 019 - train 0.63364 | val 0.66639
  Classification -> best τ=0.700 (val F1=0.3889)
  Directional -> Accuracy: 0.4545, MCC: -0.0177, F1: 0.0625

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.65285 | val 1.37219
  Epoch 011 - train 0.60066 | val 1.39613
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.5938

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.69628 | val 0.69173
  Epoch 020 - train 0.67862 | val 0.72580
  Classification -> best τ=0.530 (val F1=0.0212)
  Directional -> Accuracy: 0.4048, MCC: -0.1680, F1: 0.3902

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.68672 | val 0.66507
  Epoch 020 - train 0.64687 | val 0.72944
  Classification -> best τ=0.415 (val F1=0.2829)
  Directional -> Accuracy: 0.5000, MCC: 0.2137, F1: 0.1765

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.63679 | val 0.71273
  Epoch 011 - train 0.64232 | val 0.74522
  Classification -> best τ=0.550 (val F1=0.1870)
  Directional -> Accuracy: 0.4750, MCC: -0.0259, F1: 0.4324

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.65397 | val 0.80255
  Epoch 020 - train 0.70629 | val 0.74759
  Classification -> best τ=0.645 (val F1=0.3501)
  Directional -> Accuracy: 0.5000, MCC: -0.0196, F1: 0.3636

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.70966 | val 0.72383
  Epoch 016 - train 0.70527 | val 0.75462
  Classification -> best τ=0.595 (val F1=0.0716)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.66179 | val 0.77390
  Epoch 017 - train 0.65775 | val 0.70614
  Classification -> best τ=0.415 (val F1=0.2812)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.67067 | val 0.74919
  Epoch 020 - train 0.67667 | val 0.74245
  Classification -> best τ=0.545 (val F1=0.4063)
  Directional -> Accuracy: 0.5417, MCC: 0.1682, F1: 0.4211

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.68912 | val 0.75445
  Epoch 019 - train 0.67596 | val 0.89481
  Classification -> best τ=0.405 (val F1=0.1309)
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.68940 | val 0.70356
  Epoch 013 - train 0.67101 | val 0.69645
  Classification -> best τ=0.390 (val F1=0.3787)
  Directional -> Accuracy: 0.5606, MCC: 0.2252, F1: 0.4727

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.71026 | val 0.66939
  Epoch 020 - train 0.70542 | val 0.70939
  Classification -> best τ=0.365 (val F1=0.3603)
  Directional -> Accuracy: 0.5714, MCC: 0.1386, F1: 0.6667

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.67021 | val 0.86851
  Epoch 013 - train 0.70668 | val 0.68945
  Classification -> best τ=0.395 (val F1=0.2622)
  Directional -> Accuracy: 0.4464, MCC: -0.0962, F1: 0.4746

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.66807 | val 0.72013
  Epoch 011 - train 0.69221 | val 0.76098
  Classification -> best τ=0.390 (val F1=0.2800)
  Directional -> Accuracy: 0.5217, MCC: -0.0040, F1: 0.6071

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.67797 | val 0.69163
  Epoch 020 - train 0.66814 | val 0.65467
  Classification -> best τ=0.305 (val F1=0.3859)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.69019 | val 0.68394
  Epoch 015 - train 0.67143 | val 0.75811
  Classification -> best τ=0.550 (val F1=0.2998)
  Directional -> Accuracy: 0.5405, MCC: 0.1647, F1: 0.6667

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.69511 | val 0.70319
  Epoch 019 - train 0.67647 | val 0.74248
  Classification -> best τ=0.485 (val F1=0.2562)
  Directional -> Accuracy: 0.6444, MCC: 0.2951, F1: 0.6923

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.63789 | val 0.86781
  Epoch 018 - train 0.64808 | val 0.68621
  Classification -> best τ=0.505 (val F1=0.3118)
  Directional -> Accuracy: 0.4762, MCC: -0.0278, F1: 0.4762

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.66359 | val 0.85226
  Epoch 020 - train 0.66225 | val 0.76057
  Classification -> best τ=0.715 (val F1=0.3458)
  Directional -> Accuracy: 0.3750, MCC: -0.0538, F1: 0.5312

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.69332 | val 0.67792
  Epoch 020 - train 0.68906 | val 0.71504
  Classification -> best τ=0.515 (val F1=0.1957)
  Directional -> Accuracy: 0.3636, MCC: -0.2609, F1: 0.2222

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.68785 | val 0.92361
  Epoch 011 - train 0.66269 | val 0.87851
  Classification -> best τ=0.670 (val F1=0.1939)
  Directional -> Accuracy: 0.5179, MCC: 0.0000, F1: 0.0000

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.69299 | val 0.76317
  Epoch 018 - train 0.68215 | val 0.73801
  Classification -> best τ=0.640 (val F1=0.1668)
  Directional -> Accuracy: 0.5094, MCC: 0.1361, F1: 0.0714

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.67445 | val 1.16110
  Epoch 011 - train 0.65274 | val 1.37603
  Classification -> best τ=0.590 (val F1=0.0251)
  Directional -> Accuracy: 0.5273, MCC: 0.0000, F1: 0.6905

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.67450 | val 0.67936

[I 2026-02-22 18:04:46,222] Trial 272 finished with value: 0.2436737209702947 and parameters: {'feature_set': 'finbert', 'model_type': 'LSTM', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.4, 'batch_size': 16, 'learning_rate': 0.009913084632904351, 'weight_decay': 0.0007903665149701039, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 20, 'huber_delta': 0.9795321101350537, 'early_stopping_min_delta': 0.0010461392511294865}. Best is trial 252 with value: 0.3108162738957727.

  Epoch 020 - train 0.68071 | val 0.68121
  Classification -> best τ=0.480 (val F1=0.2691)
  Directional -> Accuracy: 0.5000, MCC: -0.0689, F1: 0.0625

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2436737209702947
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down', 'finbert_neutral']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.69094 | val 0.74496
  Epoch 018 - train 0.64371 | val 0.70132
  Classification -> best τ=0.565 (val F1=0.2510)
  Directional -> Accuracy: 0.5263, MCC: -0.0671, F1: 0.1000

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.66612 | val 0.81987
  Epoch 016 - train 0.65910 | val 0.70320
  Classification -> best τ=0.535 (val F1=0.1323)
  Directional -> Accuracy: 0.6667, MCC: 0.3340, F1: 0.6939

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.68560 | val 0.69051
  Epoch 011 - train 0.68476 | val 0.68967
  Classification -> best τ=0.560 (val F1=0.2725)
  Directional -> Accuracy: 0.6087, MCC: 0.2496, F1: 0.7097

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.66657 | val 1.18471
  Epoch 011 - train 0.67965 | val 0.97095
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5405, MCC: 0.0000, F1: 0.7018

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.67649 | val 0.77023
  Epoch 013 - train 0.67643 | val 0.69574
  Classification -> best τ=0.610 (val F1=0.3688)
  Directional -> Accuracy: 0.6600, MCC: 0.3516, F1: 0.6047

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.67293 | val 0.70121
  Epoch 011 - train 0.65968 | val 0.70365
  Classification -> best τ=0.520 (val F1=0.3495)
  Directional -> Accuracy: 0.5217, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.69410 | val 0.68782
  Epoch 012 - train 0.67867 | val 0.69195
  Classification -> best τ=0.455 (val F1=0.3331)
  Directional -> Accuracy: 0.4265, MCC: -0.0025, F1: 0.5412

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.69959 | val 0.65028
  Epoch 020 - train 0.64612 | val 0.70702
  Classification -> best τ=0.440 (val F1=0.1147)
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.66458 | val 0.92433
  Epoch 011 - train 0.64965 | val 0.99773
  Classification -> best τ=0.490 (val F1=0.3047)
  Directional -> Accuracy: 0.4375, MCC: 0.0000, F1: 0.6087

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.66986 | val 0.76768
  Epoch 011 - train 0.65523 | val 0.77554
  Classification -> best τ=0.665 (val F1=0.2621)
  Directional -> Accuracy: 0.4348, MCC: -0.0749, F1: 0.4935

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.68203 | val 0.68238
  Epoch 019 - train 0.67596 | val 0.77011
  Classification -> best τ=0.440 (val F1=0.3729)
  Directional -> Accuracy: 0.6735, MCC: 0.3783, F1: 0.4667

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.69304 | val 0.69470
  Epoch 020 - train 0.69593 | val 0.68607
  Classification -> best τ=0.535 (val F1=0.2741)
  Directional -> Accuracy: 0.5439, MCC: 0.1368, F1: 0.3158

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.68660 | val 0.73507
  Epoch 013 - train 0.64889 | val 0.78170
  Classification -> best τ=0.590 (val F1=0.2172)
  Directional -> Accuracy: 0.5476, MCC: 0.2949, F1: 0.6667

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.70050 | val 0.69078
  Epoch 016 - train 0.66026 | val 0.83781
  Classification -> best τ=0.485 (val F1=0.3196)
  Directional -> Accuracy: 0.5167, MCC: 0.0370, F1: 0.3830

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.68215 | val 0.69878
  Epoch 020 - train 0.66413 | val 0.71718
  Classification -> best τ=0.525 (val F1=0.2444)
  Directional -> Accuracy: 0.5490, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.68815 | val 0.69512
  Epoch 020 - train 0.67587 | val 0.68830
  Classification -> best τ=0.330 (val F1=0.3809)
  Directional -> Accuracy: 0.5217, MCC: -0.0558, F1: 0.6796

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.68648 | val 0.73137
  Epoch 011 - train 0.68496 | val 0.71844
  Classification -> best τ=0.595 (val F1=0.2276)
  Directional -> Accuracy: 0.3793, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.68761 | val 0.71894
  Epoch 015 - train 0.66600 | val 0.74169
  Classification -> best τ=0.585 (val F1=0.1909)
  Directional -> Accuracy: 0.4000, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.68366 | val 0.71889
  Epoch 013 - train 0.67876 | val 0.71201
  Classification -> best τ=0.620 (val F1=0.2234)
  Directional -> Accuracy: 0.4219, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.65866 | val 0.76726
  Epoch 011 - train 0.66532 | val 0.76793
  Classification -> best τ=0.555 (val F1=0.2329)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.68687 | val 0.71220
  Epoch 014 - train 0.66298 | val 0.69213
  Classification -> best τ=0.555 (val F1=0.1383)
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.68421 | val 0.69502
  Epoch 012 - train 0.69807 | val 0.70282
  Classification -> best τ=0.395 (val F1=0.2019)
  Directional -> Accuracy: 0.5385, MCC: 0.0916, F1: 0.4231

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.69220 | val 0.69663
  Epoch 020 - train 0.69493 | val 0.67739
  Classification -> best τ=0.580 (val F1=0.3881)
  Directional -> Accuracy: 0.4737, MCC: 0.0518, F1: 0.2500

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.68499 | val 0.69808
  Epoch 012 - train 0.68882 | val 0.70828
  Classification -> best τ=0.515 (val F1=0.2056)
  Directional -> Accuracy: 0.5385, MCC: 0.1368, F1: 0.6429

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.69838 | val 0.67180
  Epoch 020 - train 0.66907 | val 0.64256
  Classification -> best τ=0.450 (val F1=0.5299)
  Directional -> Accuracy: 0.5273, MCC: 0.1143, F1: 0.4091

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.66632 | val 1.22871
  Epoch 011 - train 0.64212 | val 1.33727
  Classification -> best τ=0.540 (val F1=0.2035)
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.5938

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.66999 | val 0.72017
  Epoch 016 - train 0.63186 | val 0.70529
  Classification -> best τ=0.600 (val F1=0.0212)
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.0000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.66551 | val 0.66389
  Epoch 018 - train 0.60832 | val 0.75740
  Classification -> best τ=0.330 (val F1=0.2945)
  Directional -> Accuracy: 0.5536, MCC: 0.3111, F1: 0.3243

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.66062 | val 1.35999
  Epoch 011 - train 0.65873 | val 1.35921
  Classification -> best τ=0.585 (val F1=0.0601)
  Directional -> Accuracy: 0.5250, MCC: 0.0912, F1: 0.4571

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.66517 | val 0.67458
  Epoch 020 - train 0.66440 | val 0.70735
  Classification -> best τ=0.545 (val F1=0.3501)
  Directional -> Accuracy: 0.6429, MCC: 0.3511, F1: 0.7059

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.69918 | val 0.69552
  Epoch 020 - train 0.71553 | val 0.76691
  Classification -> best τ=0.535 (val F1=0.0256)
  Directional -> Accuracy: 0.4524, MCC: -0.1711, F1: 0.5818

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.67598 | val 0.80787
  Epoch 013 - train 0.64739 | val 0.75105
  Classification -> best τ=0.455 (val F1=0.2521)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.69364 | val 0.67258
  Epoch 012 - train 0.68012 | val 0.67812
  Classification -> best τ=0.340 (val F1=0.3593)
  Directional -> Accuracy: 0.5694, MCC: 0.1429, F1: 0.5867

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.66737 | val 0.69743
  Epoch 012 - train 0.66534 | val 0.80773
  Classification -> best τ=0.530 (val F1=0.4423)
  Directional -> Accuracy: 0.5814, MCC: 0.1615, F1: 0.5263

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.69392 | val 0.69086
  Epoch 011 - train 0.67036 | val 0.71732
  Classification -> best τ=0.480 (val F1=0.3814)
  Directional -> Accuracy: 0.6212, MCC: 0.2021, F1: 0.7423

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.59874 | val 0.67582
  Epoch 020 - train 0.53445 | val 0.86448
  Classification -> best τ=0.375 (val F1=0.3603)
  Directional -> Accuracy: 0.4524, MCC: -0.1706, F1: 0.5965

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.67930 | val 0.70463
  Epoch 016 - train 0.61275 | val 0.78943
  Classification -> best τ=0.590 (val F1=0.3322)
  Directional -> Accuracy: 0.5893, MCC: 0.1641, F1: 0.4651

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.66820 | val 0.72933
  Epoch 012 - train 0.66242 | val 0.76178
  Classification -> best τ=0.460 (val F1=0.2562)
  Directional -> Accuracy: 0.6087, MCC: 0.0000, F1: 0.7568

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.65498 | val 0.73006
  Epoch 020 - train 0.62842 | val 0.70854
  Classification -> best τ=0.365 (val F1=0.4556)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.64594 | val 0.77399
  Epoch 011 - train 0.67628 | val 0.75482
  Classification -> best τ=0.510 (val F1=0.2218)
  Directional -> Accuracy: 0.5135, MCC: 0.1131, F1: 0.6604

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.67682 | val 0.70547
  Epoch 011 - train 0.67280 | val 0.70582
  Classification -> best τ=0.510 (val F1=0.0271)
  Directional -> Accuracy: 0.4889, MCC: -0.0260, F1: 0.5306

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.62364 | val 0.60556
  Epoch 020 - train 0.62264 | val 0.88071
  Classification -> best τ=0.535 (val F1=0.5092)
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.7273

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.70493 | val 0.66894
  Epoch 016 - train 0.65641 | val 0.83375
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.5455

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.68398 | val 0.70114
  Epoch 020 - train 0.66880 | val 0.67571
  Classification -> best τ=0.580 (val F1=0.2694)
  Directional -> Accuracy: 0.5091, MCC: 0.2193, F1: 0.1818

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.66754 | val 1.01591
  Epoch 012 - train 0.64573 | val 1.06662
  Classification -> best τ=0.695 (val F1=0.2774)
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.6506

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.70341 | val 0.70720
  Epoch 012 - train 0.69128 | val 0.69916
  Classification -> best τ=0.485 (val F1=0.1942)
  Directional -> Accuracy: 0.4528, MCC: -0.1876, F1: 0.6133

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.64729 | val 1.46740
  Epoch 011 - train 0.66597 | val 1.25151
  Classification -> best τ=0.600 (val F1=0.2426)
  Directional -> Accuracy: 0.5273, MCC: 0.0000, F1: 0.6905

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.68650 | val 0.68971

[I 2026-02-22 18:07:21,812] Trial 273 finished with value: 0.2569734723673598 and parameters: {'feature_set': 'finbert', 'model_type': 'LSTM', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.4, 'batch_size': 16, 'learning_rate': 0.008187869305596285, 'weight_decay': 0.0004174344317710556, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 20, 'huber_delta': 0.5720730902244852, 'early_stopping_min_delta': 0.001266160430059434}. Best is trial 252 with value: 0.3108162738957727.

  Epoch 015 - train 0.65201 | val 0.68594
  Classification -> best τ=0.475 (val F1=0.2623)
  Directional -> Accuracy: 0.5000, MCC: -0.1259, F1: 0.0000

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2569734723673598
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down', 'finbert_neutral']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.68488 | val 0.71914
  Epoch 011 - train 0.67833 | val 0.73087
  Classification -> best τ=0.480 (val F1=0.1772)
  Directional -> Accuracy: 0.5921, MCC: 0.2255, F1: 0.6265

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.66505 | val 0.70260
  Epoch 020 - train 0.65494 | val 0.70476
  Classification -> best τ=0.445 (val F1=0.1844)
  Directional -> Accuracy: 0.6000, MCC: 0.1350, F1: 0.7097

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.69760 | val 0.67616
  Epoch 020 - train 0.68757 | val 0.68889
  Classification -> best τ=0.515 (val F1=0.3577)
  Directional -> Accuracy: 0.7174, MCC: 0.4331, F1: 0.7347

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.69041 | val 0.72943
  Epoch 019 - train 0.69175 | val 0.83630
  Classification -> best τ=0.555 (val F1=0.1627)
  Directional -> Accuracy: 0.4595, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.65514 | val 0.68118
  Epoch 018 - train 0.62465 | val 0.64645
  Classification -> best τ=0.475 (val F1=0.4851)
  Directional -> Accuracy: 0.6800, MCC: 0.3677, F1: 0.6667

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.66556 | val 0.75554
  Epoch 011 - train 0.67731 | val 0.77133
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4783, MCC: 0.0000, F1: 0.6471

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.68989 | val 0.68947
  Epoch 020 - train 0.65697 | val 0.78941
  Classification -> best τ=0.510 (val F1=0.2756)
  Directional -> Accuracy: 0.4559, MCC: 0.1465, F1: 0.5843

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.66640 | val 0.57827
  Epoch 020 - train 0.62460 | val 1.13011
  Classification -> best τ=0.205 (val F1=0.2075)
  Directional -> Accuracy: 0.4762, MCC: 0.1936, F1: 0.6207

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.66882 | val 0.71643
  Epoch 017 - train 0.67290 | val 0.92000
  Classification -> best τ=0.460 (val F1=0.1837)
  Directional -> Accuracy: 0.5833, MCC: 0.1986, F1: 0.6000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.68122 | val 0.73880
  Epoch 020 - train 0.66365 | val 0.87576
  Classification -> best τ=0.495 (val F1=0.2434)
  Directional -> Accuracy: 0.4783, MCC: 0.1003, F1: 0.5909

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.69705 | val 0.69356
  Epoch 020 - train 0.68037 | val 0.67319
  Classification -> best τ=0.445 (val F1=0.2285)
  Directional -> Accuracy: 0.4898, MCC: 0.0869, F1: 0.6154

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.70909 | val 0.68871
  Epoch 015 - train 0.69565 | val 0.69784
  Classification -> best τ=0.545 (val F1=0.1888)
  Directional -> Accuracy: 0.6140, MCC: 0.2481, F1: 0.5417

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.67068 | val 0.99669
  Epoch 020 - train 0.59091 | val 0.96475
  Classification -> best τ=0.630 (val F1=0.1370)
  Directional -> Accuracy: 0.4286, MCC: -0.1783, F1: 0.2941

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.68707 | val 0.67444
  Epoch 020 - train 0.68848 | val 0.65073
  Classification -> best τ=0.435 (val F1=0.3843)
  Directional -> Accuracy: 0.5167, MCC: 0.0603, F1: 0.1714

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.66763 | val 0.69507
  Epoch 020 - train 0.68134 | val 0.69474
  Classification -> best τ=0.485 (val F1=0.2245)
  Directional -> Accuracy: 0.6275, MCC: 0.2806, F1: 0.3448

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.69146 | val 0.72161
  Epoch 015 - train 0.69193 | val 0.68510
  Classification -> best τ=0.595 (val F1=0.3094)
  Directional -> Accuracy: 0.5362, MCC: 0.0000, F1: 0.6981

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.69328 | val 0.75533
  Epoch 015 - train 0.68612 | val 0.73742
  Classification -> best τ=0.550 (val F1=0.2276)
  Directional -> Accuracy: 0.5000, MCC: 0.1969, F1: 0.3830

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.68834 | val 0.69370
  Epoch 016 - train 0.67734 | val 0.73501
  Classification -> best τ=0.710 (val F1=0.1909)
  Directional -> Accuracy: 0.4000, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.66579 | val 0.71389
  Epoch 011 - train 0.64857 | val 0.73570
  Classification -> best τ=0.410 (val F1=0.3893)
  Directional -> Accuracy: 0.5781, MCC: 0.0000, F1: 0.7327

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.67566 | val 0.74994
  Epoch 020 - train 0.68175 | val 0.77315
  Classification -> best τ=0.415 (val F1=0.3557)
  Directional -> Accuracy: 0.4324, MCC: -0.1305, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.69419 | val 0.69584
  Epoch 017 - train 0.68276 | val 0.74648
  Classification -> best τ=0.535 (val F1=0.2247)
  Directional -> Accuracy: 0.5957, MCC: 0.0615, F1: 0.7164

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.69586 | val 0.71562
  Epoch 011 - train 0.69032 | val 0.70993
  Classification -> best τ=0.495 (val F1=0.1514)
  Directional -> Accuracy: 0.5385, MCC: 0.0994, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.70024 | val 0.69215
  Epoch 013 - train 0.67860 | val 0.68381
  Classification -> best τ=0.515 (val F1=0.2293)
  Directional -> Accuracy: 0.4912, MCC: 0.2083, F1: 0.1714

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.68157 | val 0.70066
  Epoch 012 - train 0.68805 | val 0.72268
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4769, MCC: 0.0000, F1: 0.6458

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.67646 | val 0.67717
  Epoch 020 - train 0.67482 | val 0.68124
  Classification -> best τ=0.430 (val F1=0.4380)
  Directional -> Accuracy: 0.5455, MCC: 0.1826, F1: 0.3902

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.65672 | val 1.22409
  Epoch 011 - train 0.68575 | val 1.21611
  Classification -> best τ=0.655 (val F1=0.2035)
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.5938

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.68571 | val 0.69349
  Epoch 011 - train 0.65768 | val 0.69485
  Classification -> best τ=0.580 (val F1=0.1021)
  Directional -> Accuracy: 0.5952, MCC: 0.1803, F1: 0.7385

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.68039 | val 0.67146
  Epoch 013 - train 0.67970 | val 0.67535
  Classification -> best τ=0.510 (val F1=0.3430)
  Directional -> Accuracy: 0.4464, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.69163 | val 0.69773
  Epoch 011 - train 0.67533 | val 0.71398
  Classification -> best τ=0.595 (val F1=0.1870)
  Directional -> Accuracy: 0.5000, MCC: 0.0439, F1: 0.4118

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.67662 | val 1.10430
  Epoch 016 - train 0.66287 | val 0.88703
  Classification -> best τ=0.550 (val F1=0.1649)
  Directional -> Accuracy: 0.5476, MCC: 0.1494, F1: 0.6415

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.69751 | val 0.69371
  Epoch 020 - train 0.70502 | val 0.71666
  Classification -> best τ=0.530 (val F1=0.1161)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.67547 | val 0.70271
  Epoch 014 - train 0.62663 | val 0.74049
  Classification -> best τ=0.535 (val F1=0.3917)
  Directional -> Accuracy: 0.5306, MCC: 0.0127, F1: 0.6849

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.69052 | val 0.65400
  Epoch 016 - train 0.68769 | val 0.67015
  Classification -> best τ=0.365 (val F1=0.3346)
  Directional -> Accuracy: 0.5556, MCC: 0.0000, F1: 0.7143

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.65663 | val 0.83133
  Epoch 011 - train 0.65676 | val 1.24485
  Classification -> best τ=0.500 (val F1=0.0112)
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.68156 | val 0.70669
  Epoch 011 - train 0.67488 | val 0.80374
  Classification -> best τ=0.475 (val F1=0.4271)
  Directional -> Accuracy: 0.5606, MCC: 0.2461, F1: 0.4528

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.69547 | val 0.74973
  Epoch 012 - train 0.68223 | val 0.81030
  Classification -> best τ=0.495 (val F1=0.2382)
  Directional -> Accuracy: 0.5238, MCC: 0.1469, F1: 0.2308

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.67090 | val 0.76370
  Epoch 013 - train 0.67362 | val 0.79707
  Classification -> best τ=0.420 (val F1=0.2203)
  Directional -> Accuracy: 0.4464, MCC: -0.0925, F1: 0.4918

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.66567 | val 0.77231
  Epoch 016 - train 0.61915 | val 0.71268
  Classification -> best τ=0.560 (val F1=0.2659)
  Directional -> Accuracy: 0.4348, MCC: -0.0309, F1: 0.3500

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.70099 | val 0.68876
  Epoch 020 - train 0.66707 | val 0.66214
  Classification -> best τ=0.310 (val F1=0.4242)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.68440 | val 0.68613
  Epoch 012 - train 0.68499 | val 0.71784
  Classification -> best τ=0.600 (val F1=0.2891)
  Directional -> Accuracy: 0.5135, MCC: 0.0263, F1: 0.5000

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.66903 | val 0.70642
  Epoch 018 - train 0.69444 | val 0.82646
  Classification -> best τ=0.515 (val F1=0.3371)
  Directional -> Accuracy: 0.4667, MCC: -0.0667, F1: 0.2500

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.68079 | val 0.70057
  Epoch 020 - train 0.64777 | val 1.01505
  Classification -> best τ=0.535 (val F1=0.5601)
  Directional -> Accuracy: 0.5000, MCC: -0.0595, F1: 0.6038

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.66409 | val 0.83419
  Epoch 017 - train 0.67644 | val 0.78949
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.5455

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.69529 | val 0.68652
  Epoch 015 - train 0.66799 | val 0.69196
  Classification -> best τ=0.560 (val F1=0.2452)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.68734 | val 0.73989
  Epoch 020 - train 0.69362 | val 0.67735
  Classification -> best τ=0.395 (val F1=0.2640)
  Directional -> Accuracy: 0.5179, MCC: 0.1289, F1: 0.6582

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.68630 | val 0.68535
  Epoch 018 - train 0.68893 | val 0.68526
  Classification -> best τ=0.555 (val F1=0.1057)
  Directional -> Accuracy: 0.4717, MCC: -0.0539, F1: 0.4167

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.66753 | val 1.39472
  Epoch 020 - train 0.68981 | val 0.68204
  Classification -> best τ=0.410 (val F1=0.0952)
  Directional -> Accuracy: 0.5273, MCC: 0.0000, F1: 0.6905

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.68752 | val 0.67613

[I 2026-02-22 18:10:17,166] Trial 274 finished with value: 0.2407857835580892 and parameters: {'feature_set': 'finbert', 'model_type': 'LSTM', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.4, 'batch_size': 16, 'learning_rate': 0.009991413757627935, 'weight_decay': 0.0006107628091059383, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 20, 'huber_delta': 1.008904807846777, 'early_stopping_min_delta': 0.0008732301167631275}. Best is trial 252 with value: 0.3108162738957727.

  Epoch 020 - train 0.68992 | val 0.67704
  Classification -> best τ=0.435 (val F1=0.2749)
  Directional -> Accuracy: 0.6167, MCC: 0.2550, F1: 0.4651

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2407857835580892
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.66149 | val 0.69053
  Epoch 016 - train 0.61828 | val 0.70754
  Classification -> best τ=0.875 (val F1=0.2919)
  Directional -> Accuracy: 0.5395, MCC: -0.1039, F1: 0.0000

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.54239 | val 1.06085
  Epoch 012 - train 0.56239 | val 1.24908
  Classification -> best τ=0.790 (val F1=0.1941)
  Directional -> Accuracy: 0.6000, MCC: 0.1591, F1: 0.6786

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.58027 | val 1.11753
  Epoch 012 - train 0.55259 | val 1.33075
  Classification -> best τ=0.545 (val F1=0.3762)
  Directional -> Accuracy: 0.5652, MCC: 0.1604, F1: 0.4737

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.62826 | val 1.13705
  Epoch 012 - train 0.59497 | val 0.86314
  Classification -> best τ=0.495 (val F1=0.2204)
  Directional -> Accuracy: 0.5000, MCC: -0.0453, F1: 0.6105

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.57265 | val 0.94956
  Epoch 012 - train 0.54528 | val 0.93616
  Classification -> best τ=0.520 (val F1=0.5298)
  Directional -> Accuracy: 0.7200, MCC: 0.4423, F1: 0.7200

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.55870 | val 1.60807
  Epoch 016 - train 0.48397 | val 0.83899
  Classification -> best τ=0.555 (val F1=0.3377)
  Directional -> Accuracy: 0.5217, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.65060 | val 0.70235
  Epoch 013 - train 0.59962 | val 0.98158
  Classification -> best τ=0.565 (val F1=0.2361)
  Directional -> Accuracy: 0.5735, MCC: 0.0925, F1: 0.4314

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.57155 | val 0.72702
  Epoch 020 - train 0.37249 | val 1.30120
  Classification -> best τ=0.135 (val F1=0.3974)
  Directional -> Accuracy: 0.5000, MCC: 0.1291, F1: 0.6038

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.57049 | val 1.12461
  Epoch 011 - train 0.54298 | val 1.13464
  Classification -> best τ=0.420 (val F1=0.3497)
  Directional -> Accuracy: 0.4375, MCC: 0.0000, F1: 0.6087

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.60418 | val 0.88254
  Epoch 020 - train 0.58434 | val 0.77272
  Classification -> best τ=0.500 (val F1=0.2460)
  Directional -> Accuracy: 0.4638, MCC: -0.0301, F1: 0.4932

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.66834 | val 1.14697
  Epoch 011 - train 0.60598 | val 1.09256
  Classification -> best τ=0.575 (val F1=0.3075)
  Directional -> Accuracy: 0.5510, MCC: 0.0212, F1: 0.0833

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.61700 | val 1.00875
  Epoch 019 - train 0.54726 | val 1.60272
  Classification -> best τ=0.745 (val F1=0.3032)
  Directional -> Accuracy: 0.5263, MCC: 0.0509, F1: 0.5574

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.56340 | val 0.65264
  Epoch 016 - train 0.44773 | val 0.64527
  Classification -> best τ=0.465 (val F1=0.3803)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.6230

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.63803 | val 0.63106
  Epoch 020 - train 0.62169 | val 0.66883
  Classification -> best τ=0.290 (val F1=0.3916)
  Directional -> Accuracy: 0.4833, MCC: -0.0467, F1: 0.2051

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.62596 | val 0.93218
  Epoch 014 - train 0.53776 | val 0.85746
  Classification -> best τ=0.605 (val F1=0.2078)
  Directional -> Accuracy: 0.5490, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.61517 | val 0.83473
  Epoch 011 - train 0.58966 | val 0.86040
  Classification -> best τ=0.295 (val F1=0.3094)
  Directional -> Accuracy: 0.5507, MCC: 0.1304, F1: 0.7048

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.64934 | val 0.93982
  Epoch 012 - train 0.60727 | val 0.69780
  Classification -> best τ=0.460 (val F1=0.3959)
  Directional -> Accuracy: 0.4138, MCC: 0.1477, F1: 0.1053

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.64540 | val 0.69307
  Epoch 020 - train 0.60364 | val 0.68741
  Classification -> best τ=0.635 (val F1=0.2220)
  Directional -> Accuracy: 0.4000, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.62297 | val 0.88512
  Epoch 011 - train 0.61099 | val 0.91755
  Classification -> best τ=0.325 (val F1=0.3421)
  Directional -> Accuracy: 0.5781, MCC: 0.1486, F1: 0.6197

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.60491 | val 0.73914
  Epoch 020 - train 0.52016 | val 1.00680
  Classification -> best τ=0.295 (val F1=0.2597)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.61560 | val 0.90245
  Epoch 018 - train 0.50419 | val 1.18498
  Classification -> best τ=0.280 (val F1=0.2784)
  Directional -> Accuracy: 0.5106, MCC: -0.0699, F1: 0.6230

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.65239 | val 1.38551
  Epoch 018 - train 0.58448 | val 1.23591
  Classification -> best τ=0.365 (val F1=0.2371)
  Directional -> Accuracy: 0.5077, MCC: 0.0000, F1: 0.6735

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.66160 | val 0.65881
  Epoch 020 - train 0.58582 | val 0.62556
  Classification -> best τ=0.430 (val F1=0.5161)
  Directional -> Accuracy: 0.5789, MCC: 0.1009, F1: 0.7143

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.63351 | val 0.74173
  Epoch 012 - train 0.60948 | val 0.72774
  Classification -> best τ=0.465 (val F1=0.1878)
  Directional -> Accuracy: 0.5231, MCC: 0.0776, F1: 0.6076

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.58005 | val 0.95372
  Epoch 011 - train 0.54166 | val 0.89970
  Classification -> best τ=0.450 (val F1=0.4199)
  Directional -> Accuracy: 0.5636, MCC: 0.0913, F1: 0.6757

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.58052 | val 1.46968
  Epoch 012 - train 0.47531 | val 1.70303
  Classification -> best τ=0.595 (val F1=0.2935)
  Directional -> Accuracy: 0.4667, MCC: 0.1844, F1: 0.6129

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.61413 | val 0.74413
  Epoch 011 - train 0.61526 | val 0.72236
  Classification -> best τ=0.525 (val F1=0.0413)
  Directional -> Accuracy: 0.5238, MCC: -0.0323, F1: 0.6429

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.56607 | val 1.37629
  Epoch 011 - train 0.53394 | val 1.24888
  Classification -> best τ=0.515 (val F1=0.1205)
  Directional -> Accuracy: 0.4464, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.57191 | val 1.77434
  Epoch 012 - train 0.50475 | val 1.56221
  Classification -> best τ=0.530 (val F1=0.1748)
  Directional -> Accuracy: 0.5750, MCC: 0.1124, F1: 0.6909

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.60682 | val 0.75551
  Epoch 015 - train 0.51927 | val 1.33290
  Classification -> best τ=0.560 (val F1=0.3501)
  Directional -> Accuracy: 0.4524, MCC: -0.1137, F1: 0.3429

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.61668 | val 1.40532
  Epoch 011 - train 0.59454 | val 1.42300
  Classification -> best τ=0.545 (val F1=0.1231)
  Directional -> Accuracy: 0.4762, MCC: -0.1249, F1: 0.6071

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.51968 | val 0.94136
  Epoch 011 - train 0.52665 | val 0.86555
  Classification -> best τ=0.575 (val F1=0.2969)
  Directional -> Accuracy: 0.3878, MCC: -0.2724, F1: 0.0625

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.62935 | val 0.74718
  Epoch 012 - train 0.56767 | val 0.69660
  Classification -> best τ=0.535 (val F1=0.2957)
  Directional -> Accuracy: 0.4444, MCC: 0.0000, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.54604 | val 1.10951
  Epoch 011 - train 0.53097 | val 1.36871
  Classification -> best τ=0.490 (val F1=0.1818)
  Directional -> Accuracy: 0.4186, MCC: -0.2592, F1: 0.0741

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.60481 | val 0.89394
  Epoch 011 - train 0.59170 | val 1.02463
  Classification -> best τ=0.685 (val F1=0.2249)
  Directional -> Accuracy: 0.4242, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.50320 | val 0.81069
  Epoch 011 - train 0.48019 | val 0.88328
  Classification -> best τ=0.475 (val F1=0.2464)
  Directional -> Accuracy: 0.5238, MCC: 0.0000, F1: 0.6875

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.55551 | val 0.80189
  Epoch 011 - train 0.56340 | val 0.78150
  Classification -> best τ=0.485 (val F1=0.2114)
  Directional -> Accuracy: 0.4821, MCC: -0.0283, F1: 0.4912

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.52297 | val 0.91329
  Epoch 011 - train 0.50754 | val 0.94579
  Classification -> best τ=0.375 (val F1=0.2118)
  Directional -> Accuracy: 0.5217, MCC: -0.0706, F1: 0.6452

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.60064 | val 0.82871
  Epoch 011 - train 0.53087 | val 0.84822
  Classification -> best τ=0.525 (val F1=0.3887)
  Directional -> Accuracy: 0.4583, MCC: 0.0019, F1: 0.4583

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.57294 | val 1.92927
  Epoch 011 - train 0.57606 | val 1.66211
  Classification -> best τ=0.385 (val F1=0.3523)
  Directional -> Accuracy: 0.4459, MCC: -0.1168, F1: 0.3692

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.63005 | val 0.89646
  Epoch 014 - train 0.58228 | val 0.83812
  Classification -> best τ=0.425 (val F1=0.3953)
  Directional -> Accuracy: 0.4889, MCC: -0.0048, F1: 0.0800

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.51164 | val 1.29490
  Epoch 013 - train 0.45720 | val 1.53853
  Classification -> best τ=0.470 (val F1=0.5000)
  Directional -> Accuracy: 0.5238, MCC: 0.0278, F1: 0.5833

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.50842 | val 1.34629
  Epoch 012 - train 0.51783 | val 1.72923
  Classification -> best τ=0.665 (val F1=0.1371)
  Directional -> Accuracy: 0.4167, MCC: 0.1615, F1: 0.5625

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.65049 | val 0.69960
  Epoch 020 - train 0.58039 | val 1.17169
  Classification -> best τ=0.605 (val F1=0.2374)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.56834 | val 2.46461
  Epoch 011 - train 0.53457 | val 2.56632
  Classification -> best τ=0.780 (val F1=0.3988)
  Directional -> Accuracy: 0.5536, MCC: 0.1897, F1: 0.6667

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.66864 | val 0.67927
  Epoch 016 - train 0.60856 | val 0.69398
  Classification -> best τ=0.585 (val F1=0.2853)
  Directional -> Accuracy: 0.5283, MCC: 0.0662, F1: 0.4444

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.59115 | val 1.47764
  Epoch 013 - train 0.53825 | val 1.64660
  Classification -> best τ=0.490 (val F1=0.3649)
  Directional -> Accuracy: 0.5091, MCC: 0.0517, F1: 0.3721

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.69139 | val 0.67131

[I 2026-02-22 18:14:22,934] Trial 275 finished with value: 0.29296056552981664 and parameters: {'feature_set': 'sector', 'model_type': 'BiGRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.4, 'batch_size': 16, 'learning_rate': 0.008420829910091708, 'weight_decay': 0.0008940815277350787, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 20, 'huber_delta': 0.9474692820415059, 'early_stopping_min_delta': 0.0011242887565770456}. Best is trial 252 with value: 0.3108162738957727.

  Epoch 020 - train 0.57593 | val 0.74497
  Classification -> best τ=0.510 (val F1=0.2920)
  Directional -> Accuracy: 0.5167, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.29296056552981664
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.63577 | val 0.70875
  Epoch 011 - train 0.59295 | val 0.75768
  Classification -> best τ=0.700 (val F1=0.2919)
  Directional -> Accuracy: 0.5921, MCC: 0.1615, F1: 0.4918

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.62782 | val 1.05638
  Epoch 015 - train 0.52798 | val 1.11614
  Classification -> best τ=0.485 (val F1=0.1924)
  Directional -> Accuracy: 0.6222, MCC: 0.2110, F1: 0.6909

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.64304 | val 1.45056
  Epoch 011 - train 0.59843 | val 1.33167
  Classification -> best τ=0.435 (val F1=0.3159)
  Directional -> Accuracy: 0.6739, MCC: 0.3656, F1: 0.7368

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.63471 | val 0.85768
  Epoch 011 - train 0.63817 | val 0.79772
  Classification -> best τ=0.460 (val F1=0.0855)
  Directional -> Accuracy: 0.5811, MCC: 0.2230, F1: 0.7207

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.57623 | val 1.29125
  Epoch 015 - train 0.51316 | val 1.15697
  Classification -> best τ=0.490 (val F1=0.4787)
  Directional -> Accuracy: 0.7200, MCC: 0.4484, F1: 0.7083

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.55566 | val 0.79152
  Epoch 016 - train 0.53494 | val 0.69915
  Classification -> best τ=0.595 (val F1=0.5108)
  Directional -> Accuracy: 0.5217, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.65302 | val 0.77344
  Epoch 012 - train 0.60796 | val 0.76086
  Classification -> best τ=0.245 (val F1=0.2668)
  Directional -> Accuracy: 0.5000, MCC: 0.1418, F1: 0.5750

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.51012 | val 0.55215
  Epoch 017 - train 0.44516 | val 0.66378
  Classification -> best τ=0.330 (val F1=0.3632)
  Directional -> Accuracy: 0.4286, MCC: -0.2976, F1: 0.0769

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.62795 | val 1.05829
  Epoch 011 - train 0.61313 | val 1.13699
  Classification -> best τ=0.545 (val F1=0.3198)
  Directional -> Accuracy: 0.5625, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.60340 | val 0.69317
  Epoch 020 - train 0.57594 | val 0.80574
  Classification -> best τ=0.490 (val F1=0.2982)
  Directional -> Accuracy: 0.5217, MCC: 0.0921, F1: 0.5479

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.61790 | val 0.68417
  Epoch 020 - train 0.54753 | val 1.10126
  Classification -> best τ=0.570 (val F1=0.3231)
  Directional -> Accuracy: 0.6122, MCC: 0.2379, F1: 0.2963

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.61054 | val 0.82625
  Epoch 012 - train 0.59613 | val 0.76619
  Classification -> best τ=0.515 (val F1=0.3160)
  Directional -> Accuracy: 0.5263, MCC: 0.1360, F1: 0.6824

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.56825 | val 0.77102
  Epoch 015 - train 0.49531 | val 1.53473
  Classification -> best τ=0.265 (val F1=0.1991)
  Directional -> Accuracy: 0.5000, MCC: -0.0138, F1: 0.4324

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.63891 | val 0.67977
  Epoch 019 - train 0.57864 | val 0.69309
  Classification -> best τ=0.535 (val F1=0.3126)
  Directional -> Accuracy: 0.4667, MCC: -0.1857, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.67178 | val 0.90079
  Epoch 011 - train 0.61646 | val 0.90260
  Classification -> best τ=0.570 (val F1=0.2571)
  Directional -> Accuracy: 0.5490, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.63145 | val 1.13948
  Epoch 011 - train 0.58161 | val 1.58079
  Classification -> best τ=0.640 (val F1=0.1382)
  Directional -> Accuracy: 0.4928, MCC: 0.0356, F1: 0.3137

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.63686 | val 0.92150
  Epoch 012 - train 0.57755 | val 0.85916
  Classification -> best τ=0.400 (val F1=0.4297)
  Directional -> Accuracy: 0.4655, MCC: -0.1453, F1: 0.5753

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.63217 | val 0.81571
  Epoch 011 - train 0.60192 | val 0.85740
  Classification -> best τ=0.695 (val F1=0.1909)
  Directional -> Accuracy: 0.4000, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.60405 | val 1.61685
  Epoch 012 - train 0.59821 | val 1.26501
  Classification -> best τ=0.355 (val F1=0.3140)
  Directional -> Accuracy: 0.5312, MCC: 0.1003, F1: 0.5161

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.60281 | val 1.00136
  Epoch 016 - train 0.55028 | val 0.90666
  Classification -> best τ=0.370 (val F1=0.3219)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.59128 | val 0.86442
  Epoch 015 - train 0.54809 | val 0.74984
  Classification -> best τ=0.705 (val F1=0.2861)
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.62256 | val 1.18540
  Epoch 011 - train 0.58783 | val 1.58290
  Classification -> best τ=0.555 (val F1=0.2192)
  Directional -> Accuracy: 0.4923, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.63787 | val 0.64961
  Epoch 020 - train 0.60101 | val 0.75753
  Classification -> best τ=0.555 (val F1=0.4472)
  Directional -> Accuracy: 0.4035, MCC: -0.1576, F1: 0.1053

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.64609 | val 0.73731
  Epoch 015 - train 0.58351 | val 0.94091
  Classification -> best τ=0.430 (val F1=0.2444)
  Directional -> Accuracy: 0.5231, MCC: 0.0669, F1: 0.5867

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.55709 | val 1.02524
  Epoch 015 - train 0.52749 | val 1.00745
  Classification -> best τ=0.365 (val F1=0.4907)
  Directional -> Accuracy: 0.5636, MCC: 0.2170, F1: 0.4286

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.47912 | val 1.50752
  Epoch 011 - train 0.44215 | val 1.41839
  Classification -> best τ=0.715 (val F1=0.1890)
  Directional -> Accuracy: 0.6000, MCC: 0.1802, F1: 0.5263

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.59259 | val 0.74386
  Epoch 020 - train 0.54573 | val 0.79267
  Classification -> best τ=0.560 (val F1=0.2402)
  Directional -> Accuracy: 0.5000, MCC: 0.1005, F1: 0.3636

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.56331 | val 1.02296
  Epoch 011 - train 0.59105 | val 1.02834
  Classification -> best τ=0.295 (val F1=0.3751)
  Directional -> Accuracy: 0.4464, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.49892 | val 1.43421
  Epoch 012 - train 0.57224 | val 1.18978
  Classification -> best τ=0.485 (val F1=0.2414)
  Directional -> Accuracy: 0.6000, MCC: 0.2010, F1: 0.7241

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.60305 | val 0.67249
  Epoch 014 - train 0.57111 | val 0.69098
  Classification -> best τ=0.515 (val F1=0.3501)
  Directional -> Accuracy: 0.5000, MCC: -0.0092, F1: 0.4324

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.61133 | val 0.88650
  Epoch 015 - train 0.52347 | val 0.83314
  Classification -> best τ=0.680 (val F1=0.1286)
  Directional -> Accuracy: 0.4524, MCC: -0.0214, F1: 0.0800

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.59749 | val 0.82896
  Epoch 013 - train 0.52585 | val 0.79809
  Classification -> best τ=0.505 (val F1=0.4397)
  Directional -> Accuracy: 0.4898, MCC: -0.1311, F1: 0.6479

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.63134 | val 0.82588
  Epoch 018 - train 0.54921 | val 1.07118
  Classification -> best τ=0.345 (val F1=0.3380)
  Directional -> Accuracy: 0.5417, MCC: -0.0244, F1: 0.6916

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.59125 | val 0.96120
  Epoch 011 - train 0.55718 | val 0.96771
  Classification -> best τ=0.270 (val F1=0.1874)
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.59195 | val 1.19030
  Epoch 012 - train 0.57265 | val 1.61592
  Classification -> best τ=0.325 (val F1=0.2712)
  Directional -> Accuracy: 0.5909, MCC: 0.1376, F1: 0.6747

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.48163 | val 2.60796
  Epoch 013 - train 0.48182 | val 2.81681
  Classification -> best τ=0.490 (val F1=0.3287)
  Directional -> Accuracy: 0.6190, MCC: 0.2697, F1: 0.5556

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.55037 | val 0.77311
  Epoch 019 - train 0.48665 | val 0.88516
  Classification -> best τ=0.640 (val F1=0.2850)
  Directional -> Accuracy: 0.6071, MCC: 0.2204, F1: 0.3889

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.58088 | val 0.75946
  Epoch 011 - train 0.54224 | val 0.69507
  Classification -> best τ=0.375 (val F1=0.3105)
  Directional -> Accuracy: 0.6087, MCC: 0.0000, F1: 0.7568

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.58875 | val 0.68860
  Epoch 011 - train 0.55620 | val 0.73972
  Classification -> best τ=0.450 (val F1=0.4201)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.62356 | val 0.96004
  Epoch 012 - train 0.57682 | val 1.06177
  Classification -> best τ=0.255 (val F1=0.3053)
  Directional -> Accuracy: 0.4865, MCC: 0.0000, F1: 0.6545

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.62178 | val 0.74836
  Epoch 013 - train 0.58199 | val 0.94601
  Classification -> best τ=0.530 (val F1=0.4080)
  Directional -> Accuracy: 0.4889, MCC: 0.0000, F1: 0.0000

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.47385 | val 1.86033
  Epoch 011 - train 0.45377 | val 2.34126
  Classification -> best τ=0.470 (val F1=0.5092)
  Directional -> Accuracy: 0.6667, MCC: 0.3043, F1: 0.7407

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.55385 | val 0.71367
  Epoch 020 - train 0.51053 | val 0.67224
  Classification -> best τ=0.670 (val F1=0.6110)
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.5455

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.65241 | val 0.67831
  Epoch 012 - train 0.64567 | val 0.68625
  Classification -> best τ=0.690 (val F1=0.2036)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.56761 | val 1.51664
  Epoch 011 - train 0.50769 | val 1.93200
  Classification -> best τ=0.630 (val F1=0.3585)
  Directional -> Accuracy: 0.5357, MCC: 0.1486, F1: 0.6579

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.66271 | val 0.73768
  Epoch 012 - train 0.65994 | val 0.68752
  Classification -> best τ=0.585 (val F1=0.2482)
  Directional -> Accuracy: 0.5849, MCC: 0.1691, F1: 0.6207

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.53670 | val 2.22508
  Epoch 011 - train 0.54927 | val 2.16012
  Classification -> best τ=0.665 (val F1=0.2292)
  Directional -> Accuracy: 0.4727, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.66317 | val 0.83161

[I 2026-02-22 18:18:20,992] Trial 276 finished with value: 0.31006393291237067 and parameters: {'feature_set': 'sector', 'model_type': 'BiGRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.4, 'batch_size': 16, 'learning_rate': 0.008253626252082005, 'weight_decay': 0.0009513002028454122, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 20, 'huber_delta': 0.945290224263529, 'early_stopping_min_delta': 0.0010798438951826195}. Best is trial 252 with value: 0.3108162738957727.

  Epoch 014 - train 0.61932 | val 0.96004
  Classification -> best τ=0.355 (val F1=0.2915)
  Directional -> Accuracy: 0.5833, MCC: 0.1823, F1: 0.6269

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.31006393291237067
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'positive_emotion', 'negative_emotion', 'uncertainty_emotion', 'positive_emotion_pct', 'negative_emotion_pct', 'uncertainty_emotion_pct']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.66701 | val 0.93166
  Epoch 020 - train 0.66801 | val 0.67716
  Classification -> best τ=0.460 (val F1=0.2082)
  Directional -> Accuracy: 0.5526, MCC: 0.0000, F1: 0.0000

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.66573 | val 0.70860
  Epoch 014 - train 0.68949 | val 0.72421
  Classification -> best τ=0.350 (val F1=0.2285)
  Directional -> Accuracy: 0.6222, MCC: 0.2073, F1: 0.7463

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.68236 | val 0.69075
  Epoch 020 - train 0.66839 | val 0.76167
  Classification -> best τ=0.525 (val F1=0.3212)
  Directional -> Accuracy: 0.5000, MCC: 0.0334, F1: 0.3030

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.68222 | val 0.76226
  Epoch 016 - train 0.67301 | val 0.80777
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5405, MCC: 0.0000, F1: 0.7018

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.65006 | val 0.64226
  Epoch 020 - train 0.59557 | val 0.75763
  Classification -> best τ=0.540 (val F1=0.4753)
  Directional -> Accuracy: 0.6200, MCC: 0.2670, F1: 0.5581

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.69844 | val 0.69267
  Epoch 019 - train 0.58143 | val 0.78766
  Classification -> best τ=0.380 (val F1=0.2593)
  Directional -> Accuracy: 0.5000, MCC: 0.0077, F1: 0.5306

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.68395 | val 0.66900
  Epoch 020 - train 0.67490 | val 0.70961
  Classification -> best τ=0.430 (val F1=0.3151)
  Directional -> Accuracy: 0.3971, MCC: -0.0654, F1: 0.5393

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.64949 | val 0.63557
  Epoch 020 - train 0.63316 | val 0.56438
  Classification -> best τ=0.255 (val F1=0.2453)
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.67337 | val 0.84442
  Epoch 016 - train 0.68528 | val 0.75173
  Classification -> best τ=0.475 (val F1=0.2927)
  Directional -> Accuracy: 0.6458, MCC: 0.2845, F1: 0.6047

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.67151 | val 0.77572
  Epoch 019 - train 0.66542 | val 0.77714
  Classification -> best τ=0.515 (val F1=0.3131)
  Directional -> Accuracy: 0.3913, MCC: -0.1499, F1: 0.5227

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.67723 | val 0.72109
  Epoch 015 - train 0.68889 | val 0.71281
  Classification -> best τ=0.375 (val F1=0.1199)
  Directional -> Accuracy: 0.4490, MCC: 0.0000, F1: 0.6197

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.69537 | val 0.68920
  Epoch 020 - train 0.69012 | val 0.70208
  Classification -> best τ=0.610 (val F1=0.2218)
  Directional -> Accuracy: 0.6316, MCC: 0.2901, F1: 0.5532

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.61920 | val 1.16109
  Epoch 013 - train 0.66576 | val 0.74146
  Classification -> best τ=0.435 (val F1=0.1991)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.6230

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.69816 | val 0.67343
  Epoch 020 - train 0.69910 | val 0.64091
  Classification -> best τ=0.380 (val F1=0.3493)
  Directional -> Accuracy: 0.5167, MCC: 0.0405, F1: 0.6234

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.66686 | val 0.72268
  Epoch 016 - train 0.64408 | val 0.73916
  Classification -> best τ=0.455 (val F1=0.2298)
  Directional -> Accuracy: 0.5490, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.67520 | val 0.75368
  Epoch 015 - train 0.65160 | val 0.83915
  Classification -> best τ=0.635 (val F1=0.2504)
  Directional -> Accuracy: 0.5362, MCC: 0.1668, F1: 0.3333

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.69448 | val 0.70234
  Epoch 019 - train 0.66777 | val 0.83871
  Classification -> best τ=0.450 (val F1=0.2743)
  Directional -> Accuracy: 0.6207, MCC: 0.0000, F1: 0.7660

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.69629 | val 0.69669
  Epoch 015 - train 0.65208 | val 0.73586
  Classification -> best τ=0.545 (val F1=0.2500)
  Directional -> Accuracy: 0.4000, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.66865 | val 0.70194
  Epoch 012 - train 0.66005 | val 0.68702
  Classification -> best τ=0.535 (val F1=0.2973)
  Directional -> Accuracy: 0.4375, MCC: 0.1076, F1: 0.0526

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.64745 | val 0.90941
  Epoch 013 - train 0.64003 | val 0.73150
  Classification -> best τ=0.630 (val F1=0.2617)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.66902 | val 0.68735
  Epoch 020 - train 0.55382 | val 0.74538
  Classification -> best τ=0.480 (val F1=0.2800)
  Directional -> Accuracy: 0.5319, MCC: -0.0887, F1: 0.6667

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.68816 | val 0.71750
  Epoch 013 - train 0.68643 | val 0.69862
  Classification -> best τ=0.475 (val F1=0.1492)
  Directional -> Accuracy: 0.5077, MCC: 0.0239, F1: 0.3846

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.68409 | val 0.70980
  Epoch 020 - train 0.65295 | val 0.66898
  Classification -> best τ=0.655 (val F1=0.4472)
  Directional -> Accuracy: 0.4211, MCC: -0.1083, F1: 0.0571

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.67594 | val 0.68765
  Epoch 017 - train 0.67944 | val 0.70436
  Classification -> best τ=0.455 (val F1=0.1568)
  Directional -> Accuracy: 0.4769, MCC: -0.0264, F1: 0.5750

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.68136 | val 0.69234
  Epoch 020 - train 0.67007 | val 0.66859
  Classification -> best τ=0.590 (val F1=0.3663)
  Directional -> Accuracy: 0.4545, MCC: -0.0319, F1: 0.1667

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.65774 | val 1.90573
  Epoch 012 - train 0.67893 | val 1.55863
  Classification -> best τ=0.560 (val F1=0.1890)
  Directional -> Accuracy: 0.6889, MCC: 0.4470, F1: 0.7083

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.66681 | val 0.68823
  Epoch 014 - train 0.69343 | val 0.70107
  Classification -> best τ=0.575 (val F1=0.2178)
  Directional -> Accuracy: 0.4762, MCC: -0.0142, F1: 0.4500

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.67724 | val 0.69541
  Epoch 019 - train 0.66187 | val 0.69006
  Classification -> best τ=0.340 (val F1=0.2315)
  Directional -> Accuracy: 0.5179, MCC: 0.1037, F1: 0.4000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.69719 | val 0.72937
  Epoch 012 - train 0.67167 | val 0.72294
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5500, MCC: 0.0000, F1: 0.7097

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.68517 | val 0.82664
  Epoch 011 - train 0.67435 | val 0.84642
  Classification -> best τ=0.550 (val F1=0.3501)
  Directional -> Accuracy: 0.5000, MCC: -0.0092, F1: 0.4324

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.68822 | val 0.71449
  Epoch 020 - train 0.70226 | val 0.64969
  Classification -> best τ=0.625 (val F1=0.1591)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.66271 | val 0.68307
  Epoch 012 - train 0.62439 | val 0.71053
  Classification -> best τ=0.360 (val F1=0.2509)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.69026 | val 0.68075
  Epoch 017 - train 0.66452 | val 0.68098
  Classification -> best τ=0.750 (val F1=0.3568)
  Directional -> Accuracy: 0.4444, MCC: -0.0271, F1: 0.0909

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.64674 | val 1.10415
  Epoch 011 - train 0.61413 | val 1.03913
  Classification -> best τ=0.530 (val F1=0.2603)
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.68967 | val 0.72234
  Epoch 014 - train 0.67690 | val 0.69886
  Classification -> best τ=0.400 (val F1=0.3342)
  Directional -> Accuracy: 0.5303, MCC: 0.1939, F1: 0.3922

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.69728 | val 0.78885
  Epoch 011 - train 0.68579 | val 0.84274
  Classification -> best τ=0.495 (val F1=0.1550)
  Directional -> Accuracy: 0.5952, MCC: 0.2132, F1: 0.5405

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.69376 | val 0.77593
  Epoch 012 - train 0.65693 | val 0.74016
  Classification -> best τ=0.485 (val F1=0.2478)
  Directional -> Accuracy: 0.5536, MCC: 0.1049, F1: 0.5283

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.68179 | val 0.76483
  Epoch 011 - train 0.63149 | val 0.85854
  Classification -> best τ=0.475 (val F1=0.3367)
  Directional -> Accuracy: 0.6087, MCC: 0.0000, F1: 0.7568

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.70823 | val 0.66171
  Epoch 020 - train 0.57972 | val 0.65871
  Classification -> best τ=0.465 (val F1=0.4011)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.66499 | val 0.71579
  Epoch 020 - train 0.68508 | val 0.68747
  Classification -> best τ=0.555 (val F1=0.3373)
  Directional -> Accuracy: 0.5135, MCC: 0.1131, F1: 0.6604

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.69146 | val 0.72526
  Epoch 013 - train 0.67271 | val 0.73741
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5111, MCC: 0.0000, F1: 0.6765

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.67343 | val 0.70327
  Epoch 020 - train 0.68852 | val 0.76526
  Classification -> best τ=0.590 (val F1=0.6124)
  Directional -> Accuracy: 0.5000, MCC: 0.2402, F1: 0.2222

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.73062 | val 0.60581
  Epoch 020 - train 0.63974 | val 0.81296
  Classification -> best τ=0.870 (val F1=0.6110)
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.0000

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.68328 | val 1.00116
  Epoch 020 - train 0.70746 | val 0.68823
  Classification -> best τ=0.555 (val F1=0.2257)
  Directional -> Accuracy: 0.3455, MCC: -0.3560, F1: 0.4545

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.66075 | val 0.97608
  Epoch 011 - train 0.64344 | val 0.98176
  Classification -> best τ=0.570 (val F1=0.3695)
  Directional -> Accuracy: 0.5000, MCC: 0.0121, F1: 0.5625

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.70205 | val 0.67838
  Epoch 020 - train 0.68187 | val 0.70491
  Classification -> best τ=0.600 (val F1=0.1168)
  Directional -> Accuracy: 0.4906, MCC: 0.0000, F1: 0.0000

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.71774 | val 0.83602
  Epoch 017 - train 0.63648 | val 1.44816
  Classification -> best τ=0.440 (val F1=0.3750)
  Directional -> Accuracy: 0.5273, MCC: 0.0000, F1: 0.6905

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.69134 | val 0.69650

[I 2026-02-22 18:21:21,096] Trial 277 finished with value: 0.2707391936039796 and parameters: {'feature_set': 'unified_emotion', 'model_type': 'LSTM', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.4, 'batch_size': 16, 'learning_rate': 0.008506978592541355, 'weight_decay': 0.0009619178172566356, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 20, 'huber_delta': 0.9294090758848134, 'early_stopping_min_delta': 0.0011259540428387722}. Best is trial 252 with value: 0.3108162738957727.

  Epoch 012 - train 0.67321 | val 0.69228
  Classification -> best τ=0.445 (val F1=0.3458)
  Directional -> Accuracy: 0.5167, MCC: 0.0062, F1: 0.0645

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2707391936039796
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.67799 | val 0.97217
  Epoch 014 - train 0.65936 | val 0.95050
  Classification -> best τ=0.645 (val F1=0.2510)
  Directional -> Accuracy: 0.5789, MCC: 0.1291, F1: 0.2000

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.65743 | val 0.77146
  Epoch 013 - train 0.64189 | val 0.72550
  Classification -> best τ=0.510 (val F1=0.2523)
  Directional -> Accuracy: 0.5333, MCC: 0.3022, F1: 0.3226

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.68452 | val 0.69971
  Epoch 012 - train 0.66469 | val 0.71566
  Classification -> best τ=0.605 (val F1=0.3114)
  Directional -> Accuracy: 0.5435, MCC: 0.1633, F1: 0.3226

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.68159 | val 0.77144
  Epoch 011 - train 0.66603 | val 0.78771
  Classification -> best τ=0.480 (val F1=0.1422)
  Directional -> Accuracy: 0.5135, MCC: -0.1005, F1: 0.6727

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.64321 | val 0.65448
  Epoch 020 - train 0.65383 | val 0.66560
  Classification -> best τ=0.500 (val F1=0.4259)
  Directional -> Accuracy: 0.6000, MCC: 0.2202, F1: 0.5455

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.67806 | val 0.69770
  Epoch 020 - train 0.66097 | val 0.76361
  Classification -> best τ=0.555 (val F1=0.3210)
  Directional -> Accuracy: 0.5217, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.68023 | val 0.72653
  Epoch 016 - train 0.68174 | val 0.67881
  Classification -> best τ=0.600 (val F1=0.2361)
  Directional -> Accuracy: 0.5294, MCC: 0.0790, F1: 0.5000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.62678 | val 0.57131
  Epoch 016 - train 0.57876 | val 0.59777
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.69942 | val 0.72537
  Epoch 011 - train 0.66070 | val 0.70459
  Classification -> best τ=0.410 (val F1=0.1402)
  Directional -> Accuracy: 0.4375, MCC: 0.0000, F1: 0.6087

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.68703 | val 0.68642
  Epoch 013 - train 0.65985 | val 0.72325
  Classification -> best τ=0.495 (val F1=0.2651)
  Directional -> Accuracy: 0.4203, MCC: 0.0000, F1: 0.5918

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.68853 | val 0.68999
  Epoch 015 - train 0.64621 | val 0.70086
  Classification -> best τ=0.470 (val F1=0.3231)
  Directional -> Accuracy: 0.5918, MCC: 0.1804, F1: 0.2308

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.69952 | val 0.71304
  Epoch 015 - train 0.67559 | val 0.77379
  Classification -> best τ=0.580 (val F1=0.1771)
  Directional -> Accuracy: 0.5965, MCC: 0.2739, F1: 0.7089

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.66281 | val 0.67220
  Epoch 017 - train 0.57523 | val 0.73718
  Classification -> best τ=0.530 (val F1=0.3172)
  Directional -> Accuracy: 0.5952, MCC: 0.1940, F1: 0.2609

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.67080 | val 0.72541
  Epoch 020 - train 0.67101 | val 0.76008
  Classification -> best τ=0.415 (val F1=0.3721)
  Directional -> Accuracy: 0.5333, MCC: 0.0981, F1: 0.2632

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.66241 | val 0.71250
  Epoch 011 - train 0.64709 | val 0.71136
  Classification -> best τ=0.465 (val F1=0.2667)
  Directional -> Accuracy: 0.4510, MCC: 0.0000, F1: 0.6216

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.68629 | val 0.68768
  Epoch 016 - train 0.64609 | val 0.75473
  Classification -> best τ=0.575 (val F1=0.4073)
  Directional -> Accuracy: 0.5797, MCC: 0.1428, F1: 0.6588

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.66159 | val 0.68276
  Epoch 020 - train 0.64019 | val 0.71370
  Classification -> best τ=0.560 (val F1=0.3460)
  Directional -> Accuracy: 0.3793, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.67309 | val 0.69919
  Epoch 018 - train 0.63985 | val 0.76771
  Classification -> best τ=0.520 (val F1=0.2220)
  Directional -> Accuracy: 0.4000, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.66246 | val 0.73948
  Epoch 011 - train 0.65130 | val 0.72126
  Classification -> best τ=0.395 (val F1=0.2752)
  Directional -> Accuracy: 0.5781, MCC: 0.0000, F1: 0.7327

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.62892 | val 0.90653
  Epoch 011 - train 0.62455 | val 0.98548
  Classification -> best τ=0.385 (val F1=0.2482)
  Directional -> Accuracy: 0.4730, MCC: -0.1077, F1: 0.5806

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.65698 | val 0.69058
  Epoch 020 - train 0.64752 | val 0.70600
  Classification -> best τ=0.590 (val F1=0.3924)
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.69155 | val 0.67597
  Epoch 017 - train 0.68570 | val 0.70891
  Classification -> best τ=0.465 (val F1=0.2874)
  Directional -> Accuracy: 0.6000, MCC: 0.2269, F1: 0.5000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.68864 | val 0.66538
  Epoch 016 - train 0.67683 | val 0.65888
  Classification -> best τ=0.760 (val F1=0.3550)
  Directional -> Accuracy: 0.4035, MCC: -0.1518, F1: 0.1500

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.69899 | val 0.68416
  Epoch 018 - train 0.65748 | val 0.68395
  Classification -> best τ=0.410 (val F1=0.2006)
  Directional -> Accuracy: 0.5385, MCC: 0.1702, F1: 0.6591

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.66390 | val 0.62502
  Epoch 017 - train 0.65394 | val 0.71433
  Classification -> best τ=0.260 (val F1=0.4001)
  Directional -> Accuracy: 0.5273, MCC: 0.0000, F1: 0.6486

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.63958 | val 1.50882
  Epoch 011 - train 0.60787 | val 1.64681
  Classification -> best τ=0.575 (val F1=0.2686)
  Directional -> Accuracy: 0.5778, MCC: 0.1683, F1: 0.5581

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.68317 | val 0.68874
  Epoch 011 - train 0.68258 | val 0.70826
  Classification -> best τ=0.560 (val F1=0.1334)
  Directional -> Accuracy: 0.5000, MCC: -0.0138, F1: 0.5532

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.66642 | val 0.66860
  Epoch 020 - train 0.66543 | val 0.72291
  Classification -> best τ=0.455 (val F1=0.2804)
  Directional -> Accuracy: 0.4464, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.64831 | val 0.91628
  Epoch 011 - train 0.60290 | val 1.19604
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5500, MCC: 0.0000, F1: 0.7097

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.69523 | val 0.68465
  Epoch 018 - train 0.57662 | val 0.86699
  Classification -> best τ=0.445 (val F1=0.3501)
  Directional -> Accuracy: 0.5000, MCC: 0.0046, F1: 0.5116

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.68124 | val 0.88061
  Epoch 012 - train 0.67214 | val 0.84192
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5476, MCC: 0.0000, F1: 0.7077

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.67981 | val 0.71140
  Epoch 020 - train 0.57879 | val 0.66285
  Classification -> best τ=0.350 (val F1=0.3541)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.66591 | val 0.76662
  Epoch 012 - train 0.67161 | val 0.71104
  Classification -> best τ=0.415 (val F1=0.3624)
  Directional -> Accuracy: 0.5139, MCC: 0.0311, F1: 0.5333

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.63752 | val 0.93511
  Epoch 011 - train 0.61745 | val 0.92373
  Classification -> best τ=0.410 (val F1=0.2324)
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.68639 | val 0.72474
  Epoch 016 - train 0.65284 | val 0.93103
  Classification -> best τ=0.415 (val F1=0.3855)
  Directional -> Accuracy: 0.5758, MCC: 0.0000, F1: 0.7308

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.66486 | val 0.74644
  Epoch 020 - train 0.63012 | val 0.73375
  Classification -> best τ=0.605 (val F1=0.2839)
  Directional -> Accuracy: 0.6190, MCC: 0.2697, F1: 0.5556

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.67947 | val 1.08120
  Epoch 011 - train 0.61776 | val 1.00131
  Classification -> best τ=0.470 (val F1=0.2755)
  Directional -> Accuracy: 0.5357, MCC: 0.1040, F1: 0.5938

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.65398 | val 0.90126
  Epoch 012 - train 0.64804 | val 0.90619
  Classification -> best τ=0.490 (val F1=0.2800)
  Directional -> Accuracy: 0.3696, MCC: -0.1490, F1: 0.0645

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.67239 | val 0.70375
  Epoch 020 - train 0.67839 | val 0.67790
  Classification -> best τ=0.380 (val F1=0.4011)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.65559 | val 1.04030
  Epoch 011 - train 0.63881 | val 0.88982
  Classification -> best τ=0.460 (val F1=0.3072)
  Directional -> Accuracy: 0.4865, MCC: -0.1622, F1: 0.0000

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.67973 | val 0.68750
  Epoch 019 - train 0.65478 | val 0.68536
  Classification -> best τ=0.415 (val F1=0.3287)
  Directional -> Accuracy: 0.5778, MCC: 0.1935, F1: 0.6885

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.59158 | val 1.12861
  Epoch 016 - train 0.55157 | val 1.57005
  Classification -> best τ=0.575 (val F1=0.3612)
  Directional -> Accuracy: 0.4762, MCC: -0.0142, F1: 0.4500

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.65337 | val 0.65498
  Epoch 020 - train 0.63887 | val 0.71045
  Classification -> best τ=0.680 (val F1=0.4216)
  Directional -> Accuracy: 0.3958, MCC: -0.0457, F1: 0.5085

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.67338 | val 0.67833
  Epoch 018 - train 0.66323 | val 0.72462
  Classification -> best τ=0.570 (val F1=0.1682)
  Directional -> Accuracy: 0.5818, MCC: 0.2739, F1: 0.4390

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.67967 | val 0.80759
  Epoch 011 - train 0.62926 | val 0.95166
  Classification -> best τ=0.560 (val F1=0.2064)
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.6506

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.67884 | val 0.70961
  Epoch 016 - train 0.69428 | val 0.67706
  Classification -> best τ=0.580 (val F1=0.2279)
  Directional -> Accuracy: 0.5849, MCC: 0.1688, F1: 0.6071

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.65219 | val 1.07287
  Epoch 011 - train 0.62028 | val 0.88427
  Classification -> best τ=0.425 (val F1=0.1154)
  Directional -> Accuracy: 0.5273, MCC: 0.0000, F1: 0.6905

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.68773 | val 0.69437

[I 2026-02-22 18:24:19,922] Trial 278 finished with value: 0.26961893152496613 and parameters: {'feature_set': 'sector', 'model_type': 'LSTM', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.4, 'batch_size': 16, 'learning_rate': 0.007524854381542461, 'weight_decay': 0.0009200503871599709, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 20, 'huber_delta': 0.8503787651394612, 'early_stopping_min_delta': 0.000868634934437787}. Best is trial 252 with value: 0.3108162738957727.

  Epoch 018 - train 0.67283 | val 0.68737
  Classification -> best τ=0.510 (val F1=0.2623)
  Directional -> Accuracy: 0.5167, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.26961893152496613
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.62114 | val 0.87768
  Epoch 011 - train 0.62096 | val 0.90191
  Classification -> best τ=0.560 (val F1=0.2510)
  Directional -> Accuracy: 0.5526, MCC: 0.0412, F1: 0.2273

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.58816 | val 0.71585
  Epoch 015 - train 0.52567 | val 0.92019
  Classification -> best τ=0.750 (val F1=0.2523)
  Directional -> Accuracy: 0.6222, MCC: 0.2204, F1: 0.6792

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.57215 | val 1.32679
  Epoch 011 - train 0.55266 | val 1.29678
  Classification -> best τ=0.520 (val F1=0.2727)
  Directional -> Accuracy: 0.5652, MCC: 0.1724, F1: 0.4444

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.61840 | val 0.78163
  Epoch 020 - train 0.59494 | val 1.41413
  Classification -> best τ=0.475 (val F1=0.2030)
  Directional -> Accuracy: 0.5000, MCC: -0.0044, F1: 0.5316

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.57268 | val 0.68833
  Epoch 014 - train 0.48704 | val 0.71115
  Classification -> best τ=0.620 (val F1=0.4414)
  Directional -> Accuracy: 0.5800, MCC: 0.2044, F1: 0.4615

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.53447 | val 0.74197
  Epoch 013 - train 0.56170 | val 1.21426
  Classification -> best τ=0.530 (val F1=0.3168)
  Directional -> Accuracy: 0.5217, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.64451 | val 0.67603
  Epoch 020 - train 0.55589 | val 1.20182
  Classification -> best τ=0.475 (val F1=0.3633)
  Directional -> Accuracy: 0.5735, MCC: 0.1381, F1: 0.5085

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.56473 | val 0.65200
  Epoch 020 - train 0.42856 | val 0.89721
  Classification -> best τ=0.175 (val F1=0.4453)
  Directional -> Accuracy: 0.5238, MCC: -0.0323, F1: 0.2857

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.62044 | val 0.78253
  Epoch 013 - train 0.59173 | val 1.05443
  Classification -> best τ=0.340 (val F1=0.2955)
  Directional -> Accuracy: 0.4375, MCC: 0.0000, F1: 0.6087

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.59081 | val 1.58165
  Epoch 011 - train 0.58663 | val 1.55450
  Classification -> best τ=0.445 (val F1=0.2691)
  Directional -> Accuracy: 0.4638, MCC: -0.0010, F1: 0.5316

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.58539 | val 0.91558
  Epoch 011 - train 0.58419 | val 0.93787
  Classification -> best τ=0.425 (val F1=0.2765)
  Directional -> Accuracy: 0.5714, MCC: 0.1005, F1: 0.2759

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.61785 | val 0.98183
  Epoch 011 - train 0.56881 | val 1.07770
  Classification -> best τ=0.595 (val F1=0.1924)
  Directional -> Accuracy: 0.5789, MCC: 0.1926, F1: 0.6842

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.51154 | val 0.96894
  Epoch 011 - train 0.48911 | val 0.95392
  Classification -> best τ=0.620 (val F1=0.1754)
  Directional -> Accuracy: 0.4762, MCC: -0.1864, F1: 0.0833

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.60817 | val 0.82162
  Epoch 018 - train 0.59696 | val 0.75350
  Classification -> best τ=0.645 (val F1=0.3126)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.67176 | val 0.69880
  Epoch 019 - train 0.58554 | val 0.70796
  Classification -> best τ=0.580 (val F1=0.3079)
  Directional -> Accuracy: 0.4510, MCC: 0.0000, F1: 0.6216

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.61589 | val 0.92233
  Epoch 011 - train 0.58905 | val 1.06218
  Classification -> best τ=0.745 (val F1=0.1058)
  Directional -> Accuracy: 0.4928, MCC: 0.0807, F1: 0.1860

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.59076 | val 0.94440
  Epoch 015 - train 0.57788 | val 0.86985
  Classification -> best τ=0.260 (val F1=0.2743)
  Directional -> Accuracy: 0.4138, MCC: -0.1528, F1: 0.4516

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.60754 | val 0.99690
  Epoch 011 - train 0.60541 | val 1.09531
  Classification -> best τ=0.590 (val F1=0.2220)
  Directional -> Accuracy: 0.4533, MCC: 0.1938, F1: 0.1633

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.61185 | val 0.74769
  Epoch 015 - train 0.58402 | val 1.24157
  Classification -> best τ=0.240 (val F1=0.3421)
  Directional -> Accuracy: 0.5938, MCC: 0.1850, F1: 0.6286

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.60107 | val 0.80328
  Epoch 020 - train 0.48261 | val 1.26166
  Classification -> best τ=0.385 (val F1=0.2597)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.61680 | val 0.75464
  Epoch 014 - train 0.53030 | val 0.76525
  Classification -> best τ=0.570 (val F1=0.3924)
  Directional -> Accuracy: 0.4894, MCC: -0.1602, F1: 0.6250

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.62104 | val 1.01473
  Epoch 011 - train 0.59249 | val 1.22778
  Classification -> best τ=0.725 (val F1=0.2656)
  Directional -> Accuracy: 0.4923, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.66186 | val 0.74189
  Epoch 018 - train 0.56939 | val 0.68749
  Classification -> best τ=0.635 (val F1=0.5217)
  Directional -> Accuracy: 0.5965, MCC: 0.1527, F1: 0.6933

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.62646 | val 0.82537
  Epoch 011 - train 0.58630 | val 0.73668
  Classification -> best τ=0.480 (val F1=0.1985)
  Directional -> Accuracy: 0.5385, MCC: 0.1309, F1: 0.0625

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.55577 | val 0.74916
  Epoch 014 - train 0.52997 | val 0.77957
  Classification -> best τ=0.430 (val F1=0.4839)
  Directional -> Accuracy: 0.5273, MCC: 0.1463, F1: 0.3500

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.56172 | val 2.26510
  Epoch 011 - train 0.51223 | val 2.59587
  Classification -> best τ=0.620 (val F1=0.3669)
  Directional -> Accuracy: 0.4889, MCC: 0.0900, F1: 0.5818

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.60629 | val 0.78912
  Epoch 020 - train 0.47827 | val 0.73837
  Classification -> best τ=0.485 (val F1=0.3184)
  Directional -> Accuracy: 0.4524, MCC: -0.0962, F1: 0.4889

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.56139 | val 0.82393
  Epoch 011 - train 0.57911 | val 0.80187
  Classification -> best τ=0.380 (val F1=0.1997)
  Directional -> Accuracy: 0.4464, MCC: -0.0299, F1: 0.1143

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.56204 | val 0.76867
  Epoch 011 - train 0.49409 | val 0.82613
  Classification -> best τ=0.510 (val F1=0.3278)
  Directional -> Accuracy: 0.5750, MCC: 0.1770, F1: 0.7213

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.60647 | val 1.07654
  Epoch 011 - train 0.56787 | val 1.00408
  Classification -> best τ=0.525 (val F1=0.3501)
  Directional -> Accuracy: 0.5238, MCC: 0.0413, F1: 0.4737

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.59507 | val 0.79816
  Epoch 011 - train 0.59824 | val 0.86506
  Classification -> best τ=0.420 (val F1=0.2042)
  Directional -> Accuracy: 0.5238, MCC: -0.0663, F1: 0.6774

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.56741 | val 1.00511
  Epoch 012 - train 0.52806 | val 1.04492
  Classification -> best τ=0.360 (val F1=0.3541)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.66755 | val 0.84442
  Epoch 014 - train 0.53776 | val 0.72419
  Classification -> best τ=0.410 (val F1=0.2697)
  Directional -> Accuracy: 0.4722, MCC: 0.1512, F1: 0.0952

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.55694 | val 1.39609
  Epoch 011 - train 0.51969 | val 1.50722
  Classification -> best τ=0.680 (val F1=0.1818)
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.60317 | val 1.85044
  Epoch 012 - train 0.59557 | val 1.20624
  Classification -> best τ=0.185 (val F1=0.2464)
  Directional -> Accuracy: 0.5758, MCC: 0.0000, F1: 0.7308

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.47604 | val 1.20160
  Epoch 013 - train 0.36625 | val 1.76852
  Classification -> best τ=0.495 (val F1=0.3001)
  Directional -> Accuracy: 0.5952, MCC: 0.2259, F1: 0.5143

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.57122 | val 0.78743
  Epoch 011 - train 0.56819 | val 0.71211
  Classification -> best τ=0.480 (val F1=0.2114)
  Directional -> Accuracy: 0.5536, MCC: 0.1726, F1: 0.6377

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.53252 | val 0.89656
  Epoch 011 - train 0.48441 | val 0.92537
  Classification -> best τ=0.485 (val F1=0.2698)
  Directional -> Accuracy: 0.6087, MCC: 0.0000, F1: 0.7568

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.58298 | val 0.75157
  Epoch 019 - train 0.53051 | val 0.85519
  Classification -> best τ=0.615 (val F1=0.4710)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.58173 | val 1.39197
  Epoch 011 - train 0.60266 | val 1.37687
  Classification -> best τ=0.640 (val F1=0.2890)
  Directional -> Accuracy: 0.4730, MCC: -0.0816, F1: 0.2642

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.56935 | val 0.97556
  Epoch 016 - train 0.53065 | val 0.99801
  Classification -> best τ=0.450 (val F1=0.4632)
  Directional -> Accuracy: 0.5778, MCC: 0.1633, F1: 0.5366

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.52106 | val 2.20566
  Epoch 011 - train 0.40065 | val 2.19294
  Classification -> best τ=0.700 (val F1=0.5000)
  Directional -> Accuracy: 0.6667, MCC: 0.3066, F1: 0.7500

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.56805 | val 0.77292
  Epoch 020 - train 0.47585 | val 0.92244
  Classification -> best τ=0.295 (val F1=0.4371)
  Directional -> Accuracy: 0.3958, MCC: 0.1130, F1: 0.5538

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.65132 | val 0.70952
  Epoch 013 - train 0.63441 | val 0.77251
  Classification -> best τ=0.480 (val F1=0.2228)
  Directional -> Accuracy: 0.4727, MCC: -0.0920, F1: 0.5672

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.53501 | val 1.56696
  Epoch 011 - train 0.47433 | val 1.70403
  Classification -> best τ=0.740 (val F1=0.4577)
  Directional -> Accuracy: 0.5000, MCC: 0.0092, F1: 0.5484

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.67483 | val 0.78178
  Epoch 014 - train 0.64976 | val 0.68383
  Classification -> best τ=0.560 (val F1=0.2337)
  Directional -> Accuracy: 0.5472, MCC: 0.1259, F1: 0.6757

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.56874 | val 1.96013
  Epoch 011 - train 0.52031 | val 2.21602
  Classification -> best τ=0.775 (val F1=0.1605)
  Directional -> Accuracy: 0.4727, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.65124 | val 0.78414

[I 2026-02-22 18:28:21,763] Trial 279 finished with value: 0.3029038386955046 and parameters: {'feature_set': 'sector', 'model_type': 'BiGRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.4, 'batch_size': 16, 'learning_rate': 0.008006838169406545, 'weight_decay': 0.0006958228627970035, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 20, 'huber_delta': 0.9472052934874378, 'early_stopping_min_delta': 0.0010685018798858709}. Best is trial 252 with value: 0.3108162738957727.

  Epoch 014 - train 0.58705 | val 1.15348
  Classification -> best τ=0.520 (val F1=0.2623)
  Directional -> Accuracy: 0.5167, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.3029038386955046
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.66842 | val 0.75906
  Epoch 014 - train 0.62949 | val 0.83869
  Classification -> best τ=0.775 (val F1=0.2919)
  Directional -> Accuracy: 0.5789, MCC: 0.1291, F1: 0.2000

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.61739 | val 1.11094
  Epoch 011 - train 0.51494 | val 1.00224
  Classification -> best τ=0.535 (val F1=0.1941)
  Directional -> Accuracy: 0.5778, MCC: 0.1170, F1: 0.6545

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.61808 | val 1.05253
  Epoch 011 - train 0.63100 | val 1.02242
  Classification -> best τ=0.545 (val F1=0.2700)
  Directional -> Accuracy: 0.6304, MCC: 0.2957, F1: 0.7213

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.64029 | val 1.41417
  Epoch 015 - train 0.59717 | val 1.09753
  Classification -> best τ=0.390 (val F1=0.3222)
  Directional -> Accuracy: 0.5405, MCC: 0.0000, F1: 0.7018

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.59687 | val 1.02605
  Epoch 015 - train 0.49187 | val 1.12287
  Classification -> best τ=0.580 (val F1=0.5169)
  Directional -> Accuracy: 0.6800, MCC: 0.3677, F1: 0.6667

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.56742 | val 0.65213
  Epoch 020 - train 0.40455 | val 1.37424
  Classification -> best τ=0.660 (val F1=0.4070)
  Directional -> Accuracy: 0.5217, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.64575 | val 0.88991
  Epoch 011 - train 0.62389 | val 0.87361
  Classification -> best τ=0.570 (val F1=0.2536)
  Directional -> Accuracy: 0.5147, MCC: 0.0301, F1: 0.4590

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.55735 | val 0.68034
  Epoch 015 - train 0.39289 | val 0.65459
  Classification -> best τ=0.215 (val F1=0.4588)
  Directional -> Accuracy: 0.4524, MCC: 0.0534, F1: 0.5965

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.61220 | val 1.68836
  Epoch 011 - train 0.57155 | val 2.00721
  Classification -> best τ=0.495 (val F1=0.1743)
  Directional -> Accuracy: 0.4375, MCC: 0.0000, F1: 0.6087

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.62732 | val 0.76788
  Epoch 014 - train 0.55715 | val 0.74001
  Classification -> best τ=0.310 (val F1=0.2465)
  Directional -> Accuracy: 0.5362, MCC: 0.1557, F1: 0.5897

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.60863 | val 1.14713
  Epoch 013 - train 0.54029 | val 1.10673
  Classification -> best τ=0.495 (val F1=0.3231)
  Directional -> Accuracy: 0.5306, MCC: -0.1303, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.58163 | val 1.51813
  Epoch 011 - train 0.57851 | val 1.01390
  Classification -> best τ=0.535 (val F1=0.1505)
  Directional -> Accuracy: 0.6316, MCC: 0.2894, F1: 0.7042

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.57355 | val 0.71827
  Epoch 014 - train 0.48460 | val 0.73348
  Classification -> best τ=0.710 (val F1=0.1801)
  Directional -> Accuracy: 0.5476, MCC: 0.0000, F1: 0.0000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.64956 | val 0.73666
  Epoch 014 - train 0.58601 | val 0.63259
  Classification -> best τ=0.275 (val F1=0.3196)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.2105

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.62579 | val 0.75045
  Epoch 018 - train 0.55524 | val 1.18137
  Classification -> best τ=0.695 (val F1=0.2571)
  Directional -> Accuracy: 0.5490, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.62461 | val 0.84919
  Epoch 014 - train 0.57575 | val 1.60233
  Classification -> best τ=0.690 (val F1=0.1850)
  Directional -> Accuracy: 0.5362, MCC: 0.1027, F1: 0.4667

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.63396 | val 0.76183
  Epoch 012 - train 0.60971 | val 0.77659
  Classification -> best τ=0.275 (val F1=0.2787)
  Directional -> Accuracy: 0.6207, MCC: 0.0000, F1: 0.7660

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.62421 | val 0.88653
  Epoch 013 - train 0.59793 | val 0.73036
  Classification -> best τ=0.495 (val F1=0.1773)
  Directional -> Accuracy: 0.4000, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.63632 | val 1.00276
  Epoch 011 - train 0.59380 | val 0.93050
  Classification -> best τ=0.370 (val F1=0.2843)
  Directional -> Accuracy: 0.5781, MCC: 0.1486, F1: 0.6197

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.61156 | val 1.04559
  Epoch 016 - train 0.49833 | val 1.10513
  Classification -> best τ=0.195 (val F1=0.3194)
  Directional -> Accuracy: 0.4595, MCC: 0.1050, F1: 0.0476

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.60025 | val 0.66853
  Epoch 016 - train 0.52805 | val 0.94664
  Classification -> best τ=0.510 (val F1=0.3383)
  Directional -> Accuracy: 0.4043, MCC: -0.0814, F1: 0.3000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.61989 | val 1.42759
  Epoch 011 - train 0.62100 | val 1.57933
  Classification -> best τ=0.525 (val F1=0.2701)
  Directional -> Accuracy: 0.5077, MCC: 0.0000, F1: 0.6735

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.65674 | val 0.62079
  Epoch 020 - train 0.62973 | val 0.70944
  Classification -> best τ=0.465 (val F1=0.5417)
  Directional -> Accuracy: 0.5614, MCC: 0.1620, F1: 0.5283

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.64527 | val 0.98076
  Epoch 013 - train 0.57902 | val 0.86036
  Classification -> best τ=0.560 (val F1=0.1985)
  Directional -> Accuracy: 0.5385, MCC: 0.1309, F1: 0.0625

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.56560 | val 1.10043
  Epoch 011 - train 0.53532 | val 0.96901
  Classification -> best τ=0.555 (val F1=0.4199)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.53174 | val 1.54339
  Epoch 011 - train 0.48773 | val 1.41707
  Classification -> best τ=0.655 (val F1=0.2097)
  Directional -> Accuracy: 0.5556, MCC: 0.1160, F1: 0.5238

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.62292 | val 0.71872
  Epoch 016 - train 0.56633 | val 0.70547
  Classification -> best τ=0.550 (val F1=0.0829)
  Directional -> Accuracy: 0.5476, MCC: 0.0446, F1: 0.6415

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.60714 | val 1.08123
  Epoch 012 - train 0.51623 | val 0.90835
  Classification -> best τ=0.490 (val F1=0.3853)
  Directional -> Accuracy: 0.4464, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.52371 | val 0.72330
  Epoch 013 - train 0.50237 | val 1.26637
  Classification -> best τ=0.515 (val F1=0.2618)
  Directional -> Accuracy: 0.6250, MCC: 0.2659, F1: 0.7368

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.62127 | val 0.81224
  Epoch 020 - train 0.54337 | val 0.83092
  Classification -> best τ=0.500 (val F1=0.3501)
  Directional -> Accuracy: 0.5000, MCC: 0.0046, F1: 0.5116

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.62048 | val 0.90298
  Epoch 012 - train 0.55885 | val 0.95568
  Classification -> best τ=0.550 (val F1=0.2042)
  Directional -> Accuracy: 0.5238, MCC: -0.0214, F1: 0.6552

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.52767 | val 0.74750
  Epoch 012 - train 0.52643 | val 0.70308
  Classification -> best τ=0.370 (val F1=0.3833)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.63182 | val 0.70666
  Epoch 020 - train 0.60481 | val 0.71604
  Classification -> best τ=0.435 (val F1=0.3907)
  Directional -> Accuracy: 0.4444, MCC: -0.0395, F1: 0.1667

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.52975 | val 1.01990
  Epoch 011 - train 0.51078 | val 1.08257
  Classification -> best τ=0.600 (val F1=0.2025)
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.64393 | val 0.95698
  Epoch 019 - train 0.58879 | val 1.44395
  Classification -> best τ=0.865 (val F1=0.2249)
  Directional -> Accuracy: 0.4242, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.50737 | val 1.19120
  Epoch 012 - train 0.43761 | val 2.30191
  Classification -> best τ=0.520 (val F1=0.3287)
  Directional -> Accuracy: 0.5952, MCC: 0.2656, F1: 0.4516

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.52526 | val 0.74688
  Epoch 011 - train 0.53414 | val 0.73229
  Classification -> best τ=0.675 (val F1=0.2305)
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.0000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.60277 | val 1.04286
  Epoch 013 - train 0.44888 | val 1.05224
  Classification -> best τ=0.735 (val F1=0.2659)
  Directional -> Accuracy: 0.4348, MCC: 0.0460, F1: 0.2353

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.59449 | val 0.76541
  Epoch 014 - train 0.48021 | val 0.87381
  Classification -> best τ=0.590 (val F1=0.4011)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.60541 | val 0.78675
  Epoch 011 - train 0.57854 | val 0.86408
  Classification -> best τ=0.380 (val F1=0.2674)
  Directional -> Accuracy: 0.4865, MCC: 0.0000, F1: 0.6545

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.61177 | val 0.82773
  Epoch 012 - train 0.56116 | val 0.78062
  Classification -> best τ=0.595 (val F1=0.3500)
  Directional -> Accuracy: 0.6667, MCC: 0.3340, F1: 0.6939

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.44822 | val 1.52545
  Epoch 011 - train 0.44853 | val 1.84407
  Classification -> best τ=0.565 (val F1=0.4588)
  Directional -> Accuracy: 0.6429, MCC: 0.2527, F1: 0.7170

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.52072 | val 1.06624
  Epoch 020 - train 0.45055 | val 1.05715
  Classification -> best τ=0.695 (val F1=0.6058)
  Directional -> Accuracy: 0.4583, MCC: 0.0497, F1: 0.5185

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.65293 | val 0.81225
  Epoch 011 - train 0.63510 | val 0.77099
  Classification -> best τ=0.515 (val F1=0.1881)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.56065 | val 2.22688
  Epoch 011 - train 0.51444 | val 2.65419
  Classification -> best τ=0.810 (val F1=0.2143)
  Directional -> Accuracy: 0.4821, MCC: -0.0444, F1: 0.4082

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.65441 | val 0.75042
  Epoch 015 - train 0.63510 | val 0.72113
  Classification -> best τ=0.635 (val F1=0.2407)
  Directional -> Accuracy: 0.5849, MCC: 0.1704, F1: 0.6333

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.56786 | val 2.09714
  Epoch 011 - train 0.55005 | val 1.74388
  Classification -> best τ=0.610 (val F1=0.2184)
  Directional -> Accuracy: 0.4727, MCC: -0.0644, F1: 0.5246

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.64335 | val 0.68479

[I 2026-02-22 18:32:20,471] Trial 280 finished with value: 0.293883853654258 and parameters: {'feature_set': 'sector', 'model_type': 'BiGRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.4, 'batch_size': 16, 'learning_rate': 0.00781963897294554, 'weight_decay': 0.0007574956594589041, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 20, 'huber_delta': 0.9431012077305094, 'early_stopping_min_delta': 0.0010392391619474433}. Best is trial 252 with value: 0.3108162738957727.

  Epoch 014 - train 0.60136 | val 0.74887
  Classification -> best τ=0.460 (val F1=0.2623)
  Directional -> Accuracy: 0.5167, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.293883853654258
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.65184 | val 0.93795
  Epoch 018 - train 0.65965 | val 0.70934
  Classification -> best τ=0.455 (val F1=0.2412)
  Directional -> Accuracy: 0.5658, MCC: 0.0886, F1: 0.3529

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.64692 | val 0.68969
  Epoch 015 - train 0.61809 | val 0.72617
  Classification -> best τ=0.510 (val F1=0.2523)
  Directional -> Accuracy: 0.5556, MCC: 0.0891, F1: 0.6154

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.70473 | val 0.70542
  Epoch 011 - train 0.66460 | val 0.69418
  Classification -> best τ=0.520 (val F1=0.3678)
  Directional -> Accuracy: 0.4783, MCC: -0.0948, F1: 0.6129

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.66741 | val 0.88191
  Epoch 011 - train 0.68407 | val 1.10755
  Classification -> best τ=0.490 (val F1=0.1725)
  Directional -> Accuracy: 0.5405, MCC: 0.0836, F1: 0.5526

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.64427 | val 0.66822
  Epoch 012 - train 0.61460 | val 0.69254
  Classification -> best τ=0.505 (val F1=0.3641)
  Directional -> Accuracy: 0.6600, MCC: 0.3398, F1: 0.6222

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.62458 | val 0.80120
  Epoch 020 - train 0.66350 | val 0.69876
  Classification -> best τ=0.550 (val F1=0.2699)
  Directional -> Accuracy: 0.5217, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.69491 | val 0.68354
  Epoch 016 - train 0.66889 | val 0.69077
  Classification -> best τ=0.525 (val F1=0.3659)
  Directional -> Accuracy: 0.5441, MCC: 0.1157, F1: 0.5231

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.64715 | val 0.55709
  Epoch 020 - train 0.65387 | val 0.56470
  Classification -> best τ=0.275 (val F1=0.0225)
  Directional -> Accuracy: 0.4048, MCC: -0.1803, F1: 0.5763

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.67642 | val 0.72266
  Epoch 016 - train 0.63095 | val 1.03073
  Classification -> best τ=0.470 (val F1=0.2443)
  Directional -> Accuracy: 0.5833, MCC: 0.2540, F1: 0.6429

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.66728 | val 0.72091
  Epoch 011 - train 0.65527 | val 0.74084
  Classification -> best τ=0.485 (val F1=0.3268)
  Directional -> Accuracy: 0.4203, MCC: -0.0585, F1: 0.5556

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.67469 | val 0.69819
  Epoch 011 - train 0.66723 | val 0.70771
  Classification -> best τ=0.475 (val F1=0.3175)
  Directional -> Accuracy: 0.5918, MCC: 0.1537, F1: 0.3750

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.70053 | val 0.72564
  Epoch 011 - train 0.68378 | val 0.75894
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5088, MCC: 0.0000, F1: 0.6744

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.63515 | val 0.68537
  Epoch 019 - train 0.55567 | val 0.68347
  Classification -> best τ=0.655 (val F1=0.4175)
  Directional -> Accuracy: 0.5000, MCC: -0.0976, F1: 0.1600

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.66832 | val 0.73784
  Epoch 018 - train 0.65647 | val 0.66048
  Classification -> best τ=0.500 (val F1=0.3864)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.66129 | val 0.71836
  Epoch 020 - train 0.67102 | val 0.70837
  Classification -> best τ=0.705 (val F1=0.3333)
  Directional -> Accuracy: 0.5294, MCC: 0.0733, F1: 0.5385

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.65794 | val 0.96207
  Epoch 011 - train 0.66246 | val 0.87845
  Classification -> best τ=0.510 (val F1=0.3094)
  Directional -> Accuracy: 0.5362, MCC: 0.0000, F1: 0.6981

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.67258 | val 0.71574
  Epoch 018 - train 0.67083 | val 0.75520
  Classification -> best τ=0.535 (val F1=0.2877)
  Directional -> Accuracy: 0.3966, MCC: 0.0221, F1: 0.1026

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.68178 | val 0.68539
  Epoch 012 - train 0.66806 | val 0.68791
  Classification -> best τ=0.560 (val F1=0.2500)
  Directional -> Accuracy: 0.4267, MCC: 0.0727, F1: 0.1224

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.65217 | val 0.77564
  Epoch 011 - train 0.61990 | val 0.74413
  Classification -> best τ=0.475 (val F1=0.3948)
  Directional -> Accuracy: 0.5625, MCC: 0.1316, F1: 0.5882

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.62194 | val 0.74285
  Epoch 013 - train 0.61921 | val 0.79685
  Classification -> best τ=0.380 (val F1=0.2882)
  Directional -> Accuracy: 0.4865, MCC: 0.0220, F1: 0.3871

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.68154 | val 0.98920
  Epoch 012 - train 0.65915 | val 0.90111
  Classification -> best τ=0.525 (val F1=0.3458)
  Directional -> Accuracy: 0.5106, MCC: 0.1602, F1: 0.4390

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.69094 | val 0.68967
  Epoch 012 - train 0.68797 | val 0.70447
  Classification -> best τ=0.480 (val F1=0.2952)
  Directional -> Accuracy: 0.5846, MCC: 0.1968, F1: 0.4706

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.67383 | val 0.64925
  Epoch 020 - train 0.67179 | val 0.64916
  Classification -> best τ=0.700 (val F1=0.3550)
  Directional -> Accuracy: 0.4035, MCC: -0.2157, F1: 0.0000

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.69780 | val 0.70019
  Epoch 020 - train 0.65849 | val 0.69298
  Classification -> best τ=0.475 (val F1=0.1702)
  Directional -> Accuracy: 0.4923, MCC: 0.0010, F1: 0.5600

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.65989 | val 0.88633
  Epoch 015 - train 0.66713 | val 0.69844
  Classification -> best τ=0.485 (val F1=0.4638)
  Directional -> Accuracy: 0.5818, MCC: 0.1913, F1: 0.5490

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.65486 | val 1.62723
  Epoch 011 - train 0.66025 | val 1.60505
  Classification -> best τ=0.550 (val F1=0.2035)
  Directional -> Accuracy: 0.4444, MCC: 0.0159, F1: 0.5763

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.69398 | val 0.74366
  Epoch 015 - train 0.67228 | val 0.69892
  Classification -> best τ=0.505 (val F1=0.0313)
  Directional -> Accuracy: 0.5714, MCC: 0.1021, F1: 0.6538

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.64864 | val 0.68040
  Epoch 017 - train 0.66159 | val 0.78724
  Classification -> best τ=0.175 (val F1=0.2892)
  Directional -> Accuracy: 0.4643, MCC: -0.2812, F1: 0.6341

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.67293 | val 1.22387
  Epoch 012 - train 0.65761 | val 1.07825
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5500, MCC: 0.0000, F1: 0.7097

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.69248 | val 0.68403
  Epoch 019 - train 0.65228 | val 0.82113
  Classification -> best τ=0.455 (val F1=0.3244)
  Directional -> Accuracy: 0.4524, MCC: -0.0835, F1: 0.5306

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.69678 | val 0.71057
  Epoch 013 - train 0.67089 | val 0.71584
  Classification -> best τ=0.550 (val F1=0.2357)
  Directional -> Accuracy: 0.5476, MCC: 0.0535, F1: 0.6545

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.62970 | val 0.81908
  Epoch 011 - train 0.62906 | val 0.80820
  Classification -> best τ=0.465 (val F1=0.2978)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.66764 | val 0.70800
  Epoch 017 - train 0.67191 | val 0.76064
  Classification -> best τ=0.425 (val F1=0.3534)
  Directional -> Accuracy: 0.4444, MCC: 0.0000, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.64524 | val 0.79561
  Epoch 020 - train 0.57663 | val 0.79372
  Classification -> best τ=0.690 (val F1=0.1818)
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.69226 | val 0.73968
  Epoch 014 - train 0.66557 | val 0.83575
  Classification -> best τ=0.360 (val F1=0.3254)
  Directional -> Accuracy: 0.5909, MCC: 0.1026, F1: 0.7216

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.65936 | val 0.72719
  Epoch 011 - train 0.63930 | val 0.73015
  Classification -> best τ=0.470 (val F1=0.2464)
  Directional -> Accuracy: 0.5952, MCC: 0.1850, F1: 0.6383

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.62114 | val 1.08294
  Epoch 011 - train 0.60256 | val 1.45369
  Classification -> best τ=0.525 (val F1=0.2110)
  Directional -> Accuracy: 0.5536, MCC: 0.1377, F1: 0.6032

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.67774 | val 0.80723
  Epoch 011 - train 0.68781 | val 0.84351
  Classification -> best τ=0.530 (val F1=0.2203)
  Directional -> Accuracy: 0.4783, MCC: 0.0706, F1: 0.4000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.64724 | val 0.66935
  Epoch 020 - train 0.65841 | val 0.79006
  Classification -> best τ=0.450 (val F1=0.4625)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.66009 | val 0.72914
  Epoch 016 - train 0.61936 | val 0.85491
  Classification -> best τ=0.530 (val F1=0.3446)
  Directional -> Accuracy: 0.4730, MCC: -0.2001, F1: 0.0000

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.66642 | val 0.76548
  Epoch 011 - train 0.65500 | val 0.76094
  Classification -> best τ=0.530 (val F1=0.2582)
  Directional -> Accuracy: 0.5556, MCC: 0.2205, F1: 0.6970

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.58610 | val 0.76451
  Epoch 015 - train 0.52212 | val 0.82236
  Classification -> best τ=0.430 (val F1=0.5601)
  Directional -> Accuracy: 0.6190, MCC: 0.2041, F1: 0.6923

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.62187 | val 0.70245
  Epoch 020 - train 0.53452 | val 1.09739
  Classification -> best τ=0.750 (val F1=0.1371)
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.5455

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.69058 | val 0.68117
  Epoch 017 - train 0.67987 | val 0.72807
  Classification -> best τ=0.455 (val F1=0.2833)
  Directional -> Accuracy: 0.5455, MCC: 0.0430, F1: 0.6667

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.62630 | val 0.84468
  Epoch 011 - train 0.61537 | val 0.91362
  Classification -> best τ=0.480 (val F1=0.1949)
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.6506

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.69530 | val 0.73083
  Epoch 014 - train 0.68525 | val 0.72199
  Classification -> best τ=0.575 (val F1=0.2369)
  Directional -> Accuracy: 0.5283, MCC: 0.0546, F1: 0.6269

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.63117 | val 1.46336
  Epoch 011 - train 0.61551 | val 1.65061
  Classification -> best τ=0.500 (val F1=0.0236)
  Directional -> Accuracy: 0.4545, MCC: -0.0933, F1: 0.0625

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.68790 | val 0.67581

[I 2026-02-22 18:35:04,891] Trial 281 finished with value: 0.2694294952843755 and parameters: {'feature_set': 'sector', 'model_type': 'LSTM', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.4, 'batch_size': 16, 'learning_rate': 0.006205654272512845, 'weight_decay': 0.0007757638832591045, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 20, 'huber_delta': 0.8877426020537987, 'early_stopping_min_delta': 0.0008188520493083091}. Best is trial 252 with value: 0.3108162738957727.

  Epoch 020 - train 0.64632 | val 0.74314
  Classification -> best τ=0.500 (val F1=0.2691)
  Directional -> Accuracy: 0.5167, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2694294952843755
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.64251 | val 0.89022
  Epoch 020 - train 0.59846 | val 0.82812
  Classification -> best τ=0.445 (val F1=0.1671)
  Directional -> Accuracy: 0.5921, MCC: 0.1728, F1: 0.5373

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.59973 | val 0.82341
  Epoch 017 - train 0.50255 | val 0.83981
  Classification -> best τ=0.585 (val F1=0.3126)
  Directional -> Accuracy: 0.6000, MCC: 0.1924, F1: 0.6400

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.60434 | val 0.85984
  Epoch 016 - train 0.52288 | val 1.21615
  Classification -> best τ=0.430 (val F1=0.2275)
  Directional -> Accuracy: 0.6739, MCC: 0.3815, F1: 0.7458

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.63804 | val 0.73027
  Epoch 020 - train 0.52036 | val 0.71323
  Classification -> best τ=0.480 (val F1=0.3506)
  Directional -> Accuracy: 0.5270, MCC: -0.1079, F1: 0.6903

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.51681 | val 2.30612
  Epoch 017 - train 0.45706 | val 2.50201
  Classification -> best τ=0.650 (val F1=0.4556)
  Directional -> Accuracy: 0.6200, MCC: 0.3170, F1: 0.4865

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.52988 | val 0.67262
  Epoch 020 - train 0.45035 | val 0.73324
  Classification -> best τ=0.490 (val F1=0.5089)
  Directional -> Accuracy: 0.5217, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.64503 | val 0.96040
  Epoch 016 - train 0.55912 | val 1.13873
  Classification -> best τ=0.580 (val F1=0.2536)
  Directional -> Accuracy: 0.4265, MCC: -0.1763, F1: 0.3158

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.52616 | val 0.57668
  Epoch 020 - train 0.41156 | val 0.79917
  Classification -> best τ=0.325 (val F1=0.3974)
  Directional -> Accuracy: 0.5238, MCC: 0.0694, F1: 0.5238

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.61909 | val 0.91057
  Epoch 020 - train 0.50338 | val 2.43978
  Classification -> best τ=0.400 (val F1=0.3199)
  Directional -> Accuracy: 0.4375, MCC: 0.0000, F1: 0.6087

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.60047 | val 0.89968
  Epoch 020 - train 0.47013 | val 0.93333
  Classification -> best τ=0.475 (val F1=0.3033)
  Directional -> Accuracy: 0.4928, MCC: 0.1099, F1: 0.5882

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.61403 | val 0.98380
  Epoch 016 - train 0.52920 | val 0.82186
  Classification -> best τ=0.530 (val F1=0.4037)
  Directional -> Accuracy: 0.5714, MCC: 0.1118, F1: 0.1600

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.58292 | val 1.34830
  Epoch 017 - train 0.56583 | val 1.16602
  Classification -> best τ=0.660 (val F1=0.1685)
  Directional -> Accuracy: 0.5439, MCC: 0.1248, F1: 0.3500

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.58197 | val 0.78815
  Epoch 020 - train 0.33080 | val 4.19585
  Classification -> best τ=0.525 (val F1=0.2438)
  Directional -> Accuracy: 0.5476, MCC: 0.0391, F1: 0.2400

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.64057 | val 0.71678
  Epoch 017 - train 0.56164 | val 0.70907
  Classification -> best τ=0.380 (val F1=0.3584)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.56246 | val 0.75077
  Epoch 016 - train 0.48858 | val 0.76445
  Classification -> best τ=0.550 (val F1=0.2571)
  Directional -> Accuracy: 0.5490, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.60448 | val 1.22479
  Epoch 016 - train 0.53093 | val 1.66212
  Classification -> best τ=0.370 (val F1=0.2795)
  Directional -> Accuracy: 0.5507, MCC: 0.0867, F1: 0.6990

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.60284 | val 1.22515
  Epoch 016 - train 0.52840 | val 1.68130
  Classification -> best τ=0.480 (val F1=0.2581)
  Directional -> Accuracy: 0.3793, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.63350 | val 0.71086
  Epoch 020 - train 0.61618 | val 0.69995
  Classification -> best τ=0.415 (val F1=0.2071)
  Directional -> Accuracy: 0.6000, MCC: 0.0000, F1: 0.7500

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.61456 | val 0.79969
  Epoch 017 - train 0.53635 | val 1.22714
  Classification -> best τ=0.275 (val F1=0.3624)
  Directional -> Accuracy: 0.5000, MCC: -0.0250, F1: 0.5676

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.58979 | val 0.97297
  Epoch 018 - train 0.48784 | val 1.09698
  Classification -> best τ=0.645 (val F1=0.2771)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.58870 | val 0.89425
  Epoch 020 - train 0.47075 | val 0.83568
  Classification -> best τ=0.430 (val F1=0.2784)
  Directional -> Accuracy: 0.4043, MCC: -0.0814, F1: 0.3000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.64827 | val 1.60726
  Epoch 017 - train 0.53506 | val 1.49077
  Classification -> best τ=0.430 (val F1=0.3468)
  Directional -> Accuracy: 0.4923, MCC: -0.0152, F1: 0.4923

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.66479 | val 0.65127
  Epoch 020 - train 0.60645 | val 1.09834
  Classification -> best τ=0.540 (val F1=0.4332)
  Directional -> Accuracy: 0.5614, MCC: 0.1133, F1: 0.6032

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.64013 | val 0.70540
  Epoch 016 - train 0.56838 | val 0.96421
  Classification -> best τ=0.420 (val F1=0.1964)
  Directional -> Accuracy: 0.5077, MCC: 0.0133, F1: 0.4839

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.61229 | val 0.64905
  Epoch 020 - train 0.41999 | val 0.97882
  Classification -> best τ=0.695 (val F1=0.4560)
  Directional -> Accuracy: 0.4909, MCC: 0.0305, F1: 0.3636

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.48134 | val 1.63362
  Epoch 016 - train 0.35521 | val 1.98921
  Classification -> best τ=0.595 (val F1=0.1099)
  Directional -> Accuracy: 0.3778, MCC: -0.2440, F1: 0.3333

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.60987 | val 0.82107
  Epoch 019 - train 0.52712 | val 0.78811
  Classification -> best τ=0.610 (val F1=0.1936)
  Directional -> Accuracy: 0.5476, MCC: 0.1635, F1: 0.4865

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.58790 | val 1.00607
  Epoch 017 - train 0.47300 | val 1.37399
  Classification -> best τ=0.320 (val F1=0.3697)
  Directional -> Accuracy: 0.4464, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.58503 | val 0.84129
  Epoch 018 - train 0.43396 | val 1.30928
  Classification -> best τ=0.545 (val F1=0.1459)
  Directional -> Accuracy: 0.6000, MCC: 0.2536, F1: 0.7333

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.62299 | val 0.77135
  Epoch 016 - train 0.53760 | val 2.30540
  Classification -> best τ=0.550 (val F1=0.3501)
  Directional -> Accuracy: 0.5476, MCC: 0.0912, F1: 0.5128

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.58044 | val 0.84743
  Epoch 020 - train 0.61361 | val 0.73320
  Classification -> best τ=0.765 (val F1=0.1286)
  Directional -> Accuracy: 0.4524, MCC: -0.0310, F1: 0.1481

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.55700 | val 0.96092
  Epoch 016 - train 0.47876 | val 0.90241
  Classification -> best τ=0.390 (val F1=0.3541)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.62284 | val 0.73413
  Epoch 019 - train 0.49656 | val 1.08416
  Classification -> best τ=0.405 (val F1=0.3676)
  Directional -> Accuracy: 0.5139, MCC: 0.2443, F1: 0.2222

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.55099 | val 1.09792
  Epoch 016 - train 0.43642 | val 1.66418
  Classification -> best τ=0.495 (val F1=0.2717)
  Directional -> Accuracy: 0.5581, MCC: 0.1140, F1: 0.5128

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.60489 | val 1.12349
  Epoch 016 - train 0.56648 | val 1.19564
  Classification -> best τ=0.340 (val F1=0.1213)
  Directional -> Accuracy: 0.5758, MCC: 0.0000, F1: 0.7308

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.51419 | val 0.69146
  Epoch 020 - train 0.30378 | val 1.07458
  Classification -> best τ=0.590 (val F1=0.2665)
  Directional -> Accuracy: 0.5476, MCC: 0.1228, F1: 0.4571

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.52187 | val 0.70274
  Epoch 017 - train 0.48179 | val 0.73347
  Classification -> best τ=0.520 (val F1=0.2110)
  Directional -> Accuracy: 0.5536, MCC: 0.1377, F1: 0.6032

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.49436 | val 1.10644
  Epoch 016 - train 0.43042 | val 1.04678
  Classification -> best τ=0.500 (val F1=0.2474)
  Directional -> Accuracy: 0.5217, MCC: 0.0156, F1: 0.5926

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.57950 | val 1.26137
  Epoch 018 - train 0.50395 | val 1.25623
  Classification -> best τ=0.585 (val F1=0.4011)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.57232 | val 1.23855
  Epoch 016 - train 0.49478 | val 1.98254
  Classification -> best τ=0.320 (val F1=0.2236)
  Directional -> Accuracy: 0.4865, MCC: 0.0000, F1: 0.6545

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.60552 | val 0.68690
  Epoch 019 - train 0.46002 | val 0.83141
  Classification -> best τ=0.495 (val F1=0.3873)
  Directional -> Accuracy: 0.5778, MCC: 0.1633, F1: 0.5366

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.45554 | val 1.98462
  Epoch 016 - train 0.31192 | val 2.78972
  Classification -> best τ=0.665 (val F1=0.3612)
  Directional -> Accuracy: 0.4286, MCC: -0.0468, F1: 0.1429

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.52728 | val 0.94482
  Epoch 017 - train 0.35809 | val 0.69362
  Classification -> best τ=0.490 (val F1=0.4542)
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.5455

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.65066 | val 0.80288
  Epoch 016 - train 0.58680 | val 0.84194
  Classification -> best τ=0.680 (val F1=0.2036)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.55064 | val 2.07575
  Epoch 016 - train 0.44257 | val 2.90330
  Classification -> best τ=0.670 (val F1=0.4642)
  Directional -> Accuracy: 0.5179, MCC: 0.0444, F1: 0.5574

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.65064 | val 0.68419
  Epoch 019 - train 0.58819 | val 0.80842
  Classification -> best τ=0.690 (val F1=0.2482)
  Directional -> Accuracy: 0.6226, MCC: 0.2500, F1: 0.6000

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.57501 | val 1.63584
  Epoch 018 - train 0.49113 | val 2.20243
  Classification -> best τ=0.540 (val F1=0.2859)
  Directional -> Accuracy: 0.5091, MCC: 0.0344, F1: 0.4490

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.67451 | val 0.66681

[I 2026-02-22 18:40:23,726] Trial 282 finished with value: 0.29692311226823925 and parameters: {'feature_set': 'sector', 'model_type': 'BiGRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.4, 'batch_size': 16, 'learning_rate': 0.007378630419837823, 'weight_decay': 0.0007500835204002735, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 15, 'max_epochs': 20, 'huber_delta': 0.9364753240262123, 'early_stopping_min_delta': 0.0011114595974336203}. Best is trial 252 with value: 0.3108162738957727.

  Epoch 020 - train 0.56328 | val 1.31869
  Classification -> best τ=0.555 (val F1=0.2623)
  Directional -> Accuracy: 0.5167, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.29692311226823925
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.63953 | val 0.86876
  Epoch 016 - train 0.59305 | val 1.02631
  Classification -> best τ=0.710 (val F1=0.2510)
  Directional -> Accuracy: 0.6053, MCC: 0.2273, F1: 0.2500

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.55858 | val 0.83014
  Epoch 020 - train 0.39949 | val 1.28094
  Classification -> best τ=0.295 (val F1=0.2670)
  Directional -> Accuracy: 0.5778, MCC: 0.0000, F1: 0.7324

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.58899 | val 0.92017
  Epoch 016 - train 0.48601 | val 1.60019
  Classification -> best τ=0.620 (val F1=0.3114)
  Directional -> Accuracy: 0.5435, MCC: 0.1633, F1: 0.3226

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.63249 | val 0.93572
  Epoch 020 - train 0.50411 | val 0.76826
  Classification -> best τ=0.495 (val F1=0.2333)
  Directional -> Accuracy: 0.4324, MCC: -0.1094, F1: 0.1923

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.63439 | val 0.65518
  Epoch 020 - train 0.45795 | val 0.69386
  Classification -> best τ=0.615 (val F1=0.5298)
  Directional -> Accuracy: 0.6600, MCC: 0.3245, F1: 0.6531

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.57289 | val 0.73907
  Epoch 020 - train 0.49417 | val 0.82469
  Classification -> best τ=0.650 (val F1=0.3210)
  Directional -> Accuracy: 0.5217, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.65595 | val 0.71977
  Epoch 016 - train 0.57790 | val 0.88023
  Classification -> best τ=0.530 (val F1=0.2220)
  Directional -> Accuracy: 0.5147, MCC: -0.0781, F1: 0.2667

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.54702 | val 0.70782
  Epoch 020 - train 0.36154 | val 0.98755
  Classification -> best τ=0.140 (val F1=0.4971)
  Directional -> Accuracy: 0.4524, MCC: -0.0168, F1: 0.5490

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.60808 | val 0.85823
  Epoch 016 - train 0.49833 | val 0.82496
  Classification -> best τ=0.530 (val F1=0.1928)
  Directional -> Accuracy: 0.5625, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.64097 | val 0.75417
  Epoch 020 - train 0.53545 | val 0.73644
  Classification -> best τ=0.710 (val F1=0.1607)
  Directional -> Accuracy: 0.4493, MCC: -0.1198, F1: 0.3667

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.60972 | val 0.75566
  Epoch 017 - train 0.55753 | val 0.75982
  Classification -> best τ=0.450 (val F1=0.3474)
  Directional -> Accuracy: 0.5714, MCC: 0.1118, F1: 0.1600

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.57007 | val 0.97340
  Epoch 016 - train 0.52077 | val 1.31015
  Classification -> best τ=0.585 (val F1=0.3512)
  Directional -> Accuracy: 0.5088, MCC: 0.0000, F1: 0.6744

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.60081 | val 1.19168
  Epoch 016 - train 0.43552 | val 1.63856
  Classification -> best τ=0.420 (val F1=0.0512)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.6230

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.59193 | val 0.68438
  Epoch 016 - train 0.54501 | val 0.65838
  Classification -> best τ=0.425 (val F1=0.3642)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.61779 | val 0.70161
  Epoch 020 - train 0.50455 | val 0.79227
  Classification -> best τ=0.730 (val F1=0.2571)
  Directional -> Accuracy: 0.5490, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.62895 | val 1.10454
  Epoch 017 - train 0.51210 | val 1.20764
  Classification -> best τ=0.355 (val F1=0.3589)
  Directional -> Accuracy: 0.5942, MCC: 0.2287, F1: 0.7200

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.62113 | val 1.02487
  Epoch 016 - train 0.54263 | val 1.39620
  Classification -> best τ=0.515 (val F1=0.0849)
  Directional -> Accuracy: 0.6034, MCC: 0.2499, F1: 0.6230

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.64340 | val 0.81306
  Epoch 017 - train 0.53488 | val 1.05627
  Classification -> best τ=0.420 (val F1=0.2828)
  Directional -> Accuracy: 0.5467, MCC: 0.0343, F1: 0.6383

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.61075 | val 1.28829
  Epoch 016 - train 0.50945 | val 1.65063
  Classification -> best τ=0.380 (val F1=0.4444)
  Directional -> Accuracy: 0.5781, MCC: 0.0000, F1: 0.7327

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.56825 | val 0.78421
  Epoch 016 - train 0.50099 | val 1.06008
  Classification -> best τ=0.415 (val F1=0.2902)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.62364 | val 1.03585
  Epoch 016 - train 0.48147 | val 1.41576
  Classification -> best τ=0.425 (val F1=0.1723)
  Directional -> Accuracy: 0.5106, MCC: 0.0584, F1: 0.5306

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.58941 | val 1.29809
  Epoch 016 - train 0.54953 | val 2.04517
  Classification -> best τ=0.415 (val F1=0.2709)
  Directional -> Accuracy: 0.5538, MCC: 0.1816, F1: 0.2927

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.62722 | val 0.67101
  Epoch 020 - train 0.51696 | val 0.68897
  Classification -> best τ=0.460 (val F1=0.3906)
  Directional -> Accuracy: 0.5965, MCC: 0.1576, F1: 0.7229

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.67299 | val 0.88039
  Epoch 016 - train 0.59289 | val 1.10702
  Classification -> best τ=0.565 (val F1=0.1985)
  Directional -> Accuracy: 0.5692, MCC: 0.1867, F1: 0.2222

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.56301 | val 0.76413
  Epoch 017 - train 0.48926 | val 1.11136
  Classification -> best τ=0.545 (val F1=0.4560)
  Directional -> Accuracy: 0.5455, MCC: 0.1257, F1: 0.4898

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.52859 | val 1.41495
  Epoch 016 - train 0.36671 | val 1.30125
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.5938

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.61948 | val 0.70033
  Epoch 018 - train 0.48451 | val 0.78418
  Classification -> best τ=0.550 (val F1=0.2810)
  Directional -> Accuracy: 0.4524, MCC: -0.0168, F1: 0.3030

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.59628 | val 1.00885
  Epoch 016 - train 0.48485 | val 1.04393
  Classification -> best τ=0.420 (val F1=0.2755)
  Directional -> Accuracy: 0.4464, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.48170 | val 0.74626
  Epoch 017 - train 0.42628 | val 0.90603
  Classification -> best τ=0.555 (val F1=0.3518)
  Directional -> Accuracy: 0.6000, MCC: 0.2010, F1: 0.7241

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.60287 | val 0.88834
  Epoch 020 - train 0.49974 | val 0.76083
  Classification -> best τ=0.480 (val F1=0.3532)
  Directional -> Accuracy: 0.5000, MCC: 0.0092, F1: 0.5333

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.60719 | val 1.34340
  Epoch 016 - train 0.53194 | val 0.93619
  Classification -> best τ=0.485 (val F1=0.1286)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.56551 | val 0.88341
  Epoch 018 - train 0.50181 | val 1.07973
  Classification -> best τ=0.335 (val F1=0.3196)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.60627 | val 0.67866
  Epoch 020 - train 0.48650 | val 1.10546
  Classification -> best τ=0.560 (val F1=0.3260)
  Directional -> Accuracy: 0.4861, MCC: 0.1344, F1: 0.1778

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.56817 | val 1.48818
  Epoch 016 - train 0.43455 | val 1.28780
  Classification -> best τ=0.450 (val F1=0.2717)
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.58306 | val 1.19726
  Epoch 016 - train 0.52996 | val 1.62379
  Classification -> best τ=0.195 (val F1=0.3342)
  Directional -> Accuracy: 0.5758, MCC: 0.0000, F1: 0.7308

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.49996 | val 0.88283
  Epoch 018 - train 0.42765 | val 1.21830
  Classification -> best τ=0.490 (val F1=0.2858)
  Directional -> Accuracy: 0.6905, MCC: 0.3877, F1: 0.6829

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.56561 | val 1.06100
  Epoch 016 - train 0.45614 | val 0.74185
  Classification -> best τ=0.490 (val F1=0.2327)
  Directional -> Accuracy: 0.4821, MCC: -0.0185, F1: 0.5246

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.52255 | val 1.06461
  Epoch 017 - train 0.37385 | val 1.04553
  Classification -> best τ=0.575 (val F1=0.3294)
  Directional -> Accuracy: 0.4130, MCC: -0.0062, F1: 0.1818

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.57116 | val 0.75956
  Epoch 019 - train 0.53142 | val 0.84955
  Classification -> best τ=0.570 (val F1=0.3800)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.59836 | val 1.01563
  Epoch 016 - train 0.48963 | val 1.22460
  Classification -> best τ=0.430 (val F1=0.1828)
  Directional -> Accuracy: 0.4730, MCC: -0.0638, F1: 0.3810

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.64809 | val 0.73689
  Epoch 020 - train 0.55727 | val 1.14465
  Classification -> best τ=0.550 (val F1=0.4490)
  Directional -> Accuracy: 0.4889, MCC: 0.0000, F1: 0.0000

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.47117 | val 1.42683
  Epoch 016 - train 0.28813 | val 2.65656
  Classification -> best τ=0.550 (val F1=0.2381)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.5333

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.52610 | val 0.67342
  Epoch 020 - train 0.32952 | val 1.30900
  Classification -> best τ=0.720 (val F1=0.4606)
  Directional -> Accuracy: 0.5625, MCC: 0.2784, F1: 0.6038

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.66720 | val 0.77094
  Epoch 016 - train 0.61785 | val 1.57370
  Classification -> best τ=0.630 (val F1=0.2374)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.58328 | val 2.30557
  Epoch 016 - train 0.43158 | val 2.69913
  Classification -> best τ=0.605 (val F1=0.2640)
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.6506

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.66869 | val 0.66960
  Epoch 020 - train 0.58125 | val 0.72022
  Classification -> best τ=0.615 (val F1=0.3207)
  Directional -> Accuracy: 0.6226, MCC: 0.2457, F1: 0.6552

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.58212 | val 1.94117
  Epoch 016 - train 0.48446 | val 2.21127
  Classification -> best τ=0.660 (val F1=0.1053)
  Directional -> Accuracy: 0.5455, MCC: 0.0804, F1: 0.6032

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.66283 | val 0.80035

[I 2026-02-22 18:45:23,940] Trial 283 finished with value: 0.2859643291559974 and parameters: {'feature_set': 'sector', 'model_type': 'BiGRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.4, 'batch_size': 16, 'learning_rate': 0.006985057839833229, 'weight_decay': 0.0007492694798687654, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 15, 'max_epochs': 20, 'huber_delta': 0.9439421594132332, 'early_stopping_min_delta': 0.0009630260415511261}. Best is trial 252 with value: 0.3108162738957727.

  Epoch 020 - train 0.54202 | val 0.73928
  Classification -> best τ=0.455 (val F1=0.2920)
  Directional -> Accuracy: 0.5833, MCC: 0.2335, F1: 0.2857

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2859643291559974
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sentiment', 'emotion_anger', 'emotion_disgust', 'emotion_fear', 'emotion_joy', 'emotion_neutral', 'emotion_sadness', 'emotion_surprize', 'emotion_anger_pct', 'emotion_disgust_pct', 'emotion_fear_pct', 'emotion_joy_pct', 'emotion_neutral_pct', 'emotion_sadness_pct', 'emotion_surprize_pct', 'positive_emotion', 'negative_emotion', 'uncertainty_emotion', 'positive_emotion_pct', 'negative_emotion_pct', 'uncertainty_emotion_pct', 'stance_label', 'stance_score', 'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down', 'finbert_neutral']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.71584 | val 0.67474
  Epoch 020 - train 0.70659 | val 0.67325
  Classification -> best τ=0.395 (val F1=0.1641)
  Directional -> Accuracy: 0.4211, MCC: -0.1195, F1: 0.5600

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.66569 | val 0.73343
  Epoch 016 - train 0.67233 | val 0.72837
  Classification -> best τ=0.560 (val F1=0.2493)
  Directional -> Accuracy: 0.4889, MCC: 0.0485, F1: 0.4103

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.68977 | val 0.73410
  Epoch 016 - train 0.69086 | val 0.73483
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5217, MCC: 0.0000, F1: 0.6857

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.69680 | val 0.72453
  Epoch 016 - train 0.69460 | val 0.72482
  Classification -> best τ=0.590 (val F1=0.1079)
  Directional -> Accuracy: 0.4595, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.69923 | val 0.67027
  Epoch 020 - train 0.68117 | val 0.66849
  Classification -> best τ=0.560 (val F1=0.3933)
  Directional -> Accuracy: 0.6200, MCC: 0.2442, F1: 0.6122

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.70303 | val 0.76456
  Epoch 016 - train 0.71548 | val 0.76480
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4783, MCC: 0.0000, F1: 0.6471

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.69745 | val 0.70566
  Epoch 016 - train 0.71250 | val 0.70597
  Classification -> best τ=0.495 (val F1=0.0519)
  Directional -> Accuracy: 0.3824, MCC: -0.1207, F1: 0.5227

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.70106 | val 0.87340
  Epoch 016 - train 0.70402 | val 0.87666
  Classification -> best τ=0.555 (val F1=0.0668)
  Directional -> Accuracy: 0.5952, MCC: 0.1340, F1: 0.3704

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.70525 | val 0.69671
  Epoch 019 - train 0.71127 | val 0.69768
  Classification -> best τ=0.535 (val F1=0.3385)
  Directional -> Accuracy: 0.4792, MCC: 0.0794, F1: 0.6032

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.70326 | val 0.68850
  Epoch 020 - train 0.68934 | val 0.69768
  Classification -> best τ=0.385 (val F1=0.2986)
  Directional -> Accuracy: 0.4203, MCC: -0.0279, F1: 0.5833

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.71806 | val 0.69101
  Epoch 016 - train 0.70336 | val 0.69428
  Classification -> best τ=0.390 (val F1=0.2564)
  Directional -> Accuracy: 0.4082, MCC: -0.1687, F1: 0.4314

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.71182 | val 0.70138
  Epoch 016 - train 0.71140 | val 0.70088
  Classification -> best τ=0.540 (val F1=0.2347)
  Directional -> Accuracy: 0.5439, MCC: 0.0874, F1: 0.6176

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.70537 | val 0.70240
  Epoch 016 - train 0.69139 | val 0.70877
  Classification -> best τ=0.480 (val F1=0.1991)
  Directional -> Accuracy: 0.5238, MCC: 0.1062, F1: 0.6000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.69782 | val 0.71006
  Epoch 018 - train 0.72186 | val 0.71284
  Classification -> best τ=0.655 (val F1=0.4109)
  Directional -> Accuracy: 0.4833, MCC: -0.1302, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.69334 | val 0.69338
  Epoch 016 - train 0.69309 | val 0.69579
  Classification -> best τ=0.475 (val F1=0.1455)
  Directional -> Accuracy: 0.5882, MCC: 0.2229, F1: 0.1600

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.71961 | val 0.77116
  Epoch 016 - train 0.70712 | val 0.76995
  Classification -> best τ=0.435 (val F1=0.0244)
  Directional -> Accuracy: 0.4928, MCC: -0.0359, F1: 0.5679

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.68704 | val 0.73979
  Epoch 016 - train 0.68955 | val 0.74335
  Classification -> best τ=0.580 (val F1=0.1303)
  Directional -> Accuracy: 0.3793, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.70216 | val 0.73381
  Epoch 016 - train 0.70572 | val 0.73323
  Classification -> best τ=0.445 (val F1=0.1182)
  Directional -> Accuracy: 0.5733, MCC: 0.1013, F1: 0.6522

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.69838 | val 0.69532
  Epoch 020 - train 0.70768 | val 0.69535
  Classification -> best τ=0.615 (val F1=0.1809)
  Directional -> Accuracy: 0.5000, MCC: 0.1635, F1: 0.3043

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.69369 | val 0.70152
  Epoch 016 - train 0.70236 | val 0.70225
  Classification -> best τ=0.410 (val F1=0.1549)
  Directional -> Accuracy: 0.5676, MCC: 0.1249, F1: 0.6098

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.70883 | val 0.70350
  Epoch 016 - train 0.71618 | val 0.70325
  Classification -> best τ=0.470 (val F1=0.1572)
  Directional -> Accuracy: 0.6170, MCC: 0.0000, F1: 0.7632

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.71628 | val 0.67172
  Epoch 018 - train 0.71014 | val 0.67131
  Classification -> best τ=0.385 (val F1=0.3356)
  Directional -> Accuracy: 0.5846, MCC: 0.2000, F1: 0.6824

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.70345 | val 0.69462
  Epoch 016 - train 0.71461 | val 0.69518
  Classification -> best τ=0.490 (val F1=0.2380)
  Directional -> Accuracy: 0.5965, MCC: 0.1707, F1: 0.6567

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.72204 | val 0.85171
  Epoch 016 - train 0.72680 | val 0.85306
  Classification -> best τ=0.655 (val F1=0.1393)
  Directional -> Accuracy: 0.5538, MCC: 0.1866, F1: 0.1212

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.71006 | val 0.71443
  Epoch 016 - train 0.70739 | val 0.71510
  Classification -> best τ=0.505 (val F1=0.1840)
  Directional -> Accuracy: 0.5636, MCC: 0.0896, F1: 0.6923

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.67334 | val 0.70039
  Epoch 016 - train 0.67133 | val 0.70188
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.5938

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.70074 | val 0.71026
  Epoch 020 - train 0.70417 | val 0.71071
  Classification -> best τ=0.415 (val F1=0.3151)
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.7273

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.68333 | val 0.70913
  Epoch 016 - train 0.69454 | val 0.70966
  Classification -> best τ=0.465 (val F1=0.0920)
  Directional -> Accuracy: 0.5179, MCC: -0.0114, F1: 0.6197

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.69360 | val 0.71892
  Epoch 016 - train 0.68950 | val 0.71754
  Classification -> best τ=0.565 (val F1=0.2774)
  Directional -> Accuracy: 0.5500, MCC: 0.1231, F1: 0.5263

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.68965 | val 0.77606
  Epoch 016 - train 0.68874 | val 0.77887
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4762, MCC: 0.0000, F1: 0.6452

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.71285 | val 0.67078
  Epoch 016 - train 0.70807 | val 0.66860
  Classification -> best τ=0.565 (val F1=0.2066)
  Directional -> Accuracy: 0.4762, MCC: 0.0083, F1: 0.3125

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.72780 | val 0.71761
  Epoch 016 - train 0.70025 | val 0.71727
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.69625 | val 0.68667
  Epoch 018 - train 0.69720 | val 0.68773
  Classification -> best τ=0.455 (val F1=0.2357)
  Directional -> Accuracy: 0.5694, MCC: 0.2050, F1: 0.4918

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.71315 | val 0.81454
  Epoch 016 - train 0.71973 | val 0.81849
  Classification -> best τ=0.535 (val F1=0.2057)
  Directional -> Accuracy: 0.4651, MCC: -0.1527, F1: 0.0800

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.68877 | val 0.68874
  Epoch 020 - train 0.68970 | val 0.68657
  Classification -> best τ=0.395 (val F1=0.2941)
  Directional -> Accuracy: 0.5152, MCC: 0.1279, F1: 0.4074

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.70552 | val 0.69042
  Epoch 020 - train 0.70683 | val 0.69002
  Classification -> best τ=0.545 (val F1=0.2618)
  Directional -> Accuracy: 0.4524, MCC: -0.0853, F1: 0.2069

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.67709 | val 0.78489
  Epoch 016 - train 0.69679 | val 0.78347
  Classification -> best τ=0.565 (val F1=0.2976)
  Directional -> Accuracy: 0.5000, MCC: -0.1792, F1: 0.0000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.69002 | val 0.71306
  Epoch 016 - train 0.69922 | val 0.71379
  Classification -> best τ=0.545 (val F1=0.0475)
  Directional -> Accuracy: 0.3913, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.70706 | val 0.69431
  Epoch 020 - train 0.69495 | val 0.69468
  Classification -> best τ=0.395 (val F1=0.2787)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.70860 | val 0.71496
  Epoch 016 - train 0.71516 | val 0.71334
  Classification -> best τ=0.480 (val F1=0.1901)
  Directional -> Accuracy: 0.5000, MCC: -0.0093, F1: 0.3934

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.70225 | val 0.71659
  Epoch 016 - train 0.70793 | val 0.71226
  Classification -> best τ=0.490 (val F1=0.2092)
  Directional -> Accuracy: 0.4667, MCC: -0.0811, F1: 0.5556

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.70805 | val 0.70878
  Epoch 016 - train 0.70017 | val 0.70783
  Classification -> best τ=0.495 (val F1=0.2677)
  Directional -> Accuracy: 0.6429, MCC: 0.2527, F1: 0.7170

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.70061 | val 0.72419
  Epoch 016 - train 0.71935 | val 0.72133
  Classification -> best τ=0.475 (val F1=0.2368)
  Directional -> Accuracy: 0.5833, MCC: 0.0497, F1: 0.3333

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.70065 | val 0.69024
  Epoch 020 - train 0.69493 | val 0.68860
  Classification -> best τ=0.480 (val F1=0.2945)
  Directional -> Accuracy: 0.6545, MCC: 0.3012, F1: 0.6885

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.72725 | val 0.73738
  Epoch 016 - train 0.71587 | val 0.73993
  Classification -> best τ=0.500 (val F1=0.1211)
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.6506

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.69263 | val 0.67548
  Epoch 020 - train 0.71432 | val 0.67477
  Classification -> best τ=0.545 (val F1=0.2741)
  Directional -> Accuracy: 0.4717, MCC: -0.0587, F1: 0.5000

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.69557 | val 0.68138
  Epoch 020 - train 0.70483 | val 0.67890
  Classification -> best τ=0.460 (val F1=0.2257)
  Directional -> Accuracy: 0.4727, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.71467 | val 0.76116

[I 2026-02-22 18:50:25,203] Trial 284 finished with value: 0.1893676682251679 and parameters: {'feature_set': 'all_nlp', 'model_type': 'BiGRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.4, 'batch_size': 16, 'learning_rate': 1.6330285750546422e-06, 'weight_decay': 0.0008973230494331056, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 15, 'max_epochs': 20, 'huber_delta': 0.9295833660862391, 'early_stopping_min_delta': 0.0011194054727976211}. Best is trial 252 with value: 0.3108162738957727.

  Epoch 016 - train 0.72393 | val 0.76069
  Classification -> best τ=0.570 (val F1=0.1790)
  Directional -> Accuracy: 0.4833, MCC: -0.0062, F1: 0.6437

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.1893676682251679
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.62995 | val 0.83899
  Epoch 016 - train 0.60871 | val 1.28247
  Classification -> best τ=0.845 (val F1=0.2510)
  Directional -> Accuracy: 0.5395, MCC: -0.1039, F1: 0.0000

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.56839 | val 0.80293
  Epoch 017 - train 0.49702 | val 0.79912
  Classification -> best τ=0.595 (val F1=0.2523)
  Directional -> Accuracy: 0.6222, MCC: 0.2314, F1: 0.6667

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.56458 | val 1.28798
  Epoch 016 - train 0.52384 | val 1.75916
  Classification -> best τ=0.600 (val F1=0.1978)
  Directional -> Accuracy: 0.4783, MCC: -0.0134, F1: 0.1429

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.62458 | val 0.87333
  Epoch 020 - train 0.54655 | val 0.75429
  Classification -> best τ=0.495 (val F1=0.2025)
  Directional -> Accuracy: 0.4595, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.55015 | val 0.90789
  Epoch 016 - train 0.43937 | val 2.28877
  Classification -> best τ=0.530 (val F1=0.4851)
  Directional -> Accuracy: 0.7200, MCC: 0.4484, F1: 0.7083

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.55233 | val 0.77087
  Epoch 020 - train 0.41196 | val 0.69408
  Classification -> best τ=0.570 (val F1=0.3194)
  Directional -> Accuracy: 0.5217, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.61327 | val 1.05567
  Epoch 016 - train 0.56879 | val 1.39607
  Classification -> best τ=0.275 (val F1=0.3042)
  Directional -> Accuracy: 0.5147, MCC: 0.1280, F1: 0.5600

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.49606 | val 0.77276
  Epoch 020 - train 0.38002 | val 1.42624
  Classification -> best τ=0.235 (val F1=0.2168)
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.59157 | val 1.21188
  Epoch 017 - train 0.50932 | val 2.84881
  Classification -> best τ=0.495 (val F1=0.4025)
  Directional -> Accuracy: 0.6875, MCC: 0.3944, F1: 0.4828

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.58124 | val 0.75896
  Epoch 017 - train 0.47710 | val 0.92687
  Classification -> best τ=0.415 (val F1=0.2732)
  Directional -> Accuracy: 0.5217, MCC: 0.1305, F1: 0.5823

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.61356 | val 1.47218
  Epoch 016 - train 0.52213 | val 1.70794
  Classification -> best τ=0.540 (val F1=0.4059)
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.58940 | val 0.84955
  Epoch 016 - train 0.55163 | val 1.12776
  Classification -> best τ=0.505 (val F1=0.3160)
  Directional -> Accuracy: 0.5263, MCC: 0.1360, F1: 0.6824

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.50724 | val 1.60030
  Epoch 017 - train 0.39073 | val 2.12393
  Classification -> best τ=0.550 (val F1=0.1801)
  Directional -> Accuracy: 0.5000, MCC: -0.0976, F1: 0.1600

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.60318 | val 0.65107
  Epoch 016 - train 0.53692 | val 0.69256
  Classification -> best τ=0.450 (val F1=0.4109)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.61229 | val 0.77283
  Epoch 016 - train 0.52862 | val 0.75526
  Classification -> best τ=0.570 (val F1=0.2078)
  Directional -> Accuracy: 0.5490, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.61830 | val 1.50800
  Epoch 019 - train 0.49467 | val 2.30363
  Classification -> best τ=0.520 (val F1=0.2466)
  Directional -> Accuracy: 0.5362, MCC: 0.0853, F1: 0.5152

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.59174 | val 0.87583
  Epoch 020 - train 0.48949 | val 2.53354
  Classification -> best τ=0.425 (val F1=0.3264)
  Directional -> Accuracy: 0.3793, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.61178 | val 0.85022
  Epoch 016 - train 0.55159 | val 1.10350
  Classification -> best τ=0.645 (val F1=0.1909)
  Directional -> Accuracy: 0.4000, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.57478 | val 0.80310
  Epoch 016 - train 0.51998 | val 0.92787
  Classification -> best τ=0.355 (val F1=0.2711)
  Directional -> Accuracy: 0.5312, MCC: 0.1253, F1: 0.4828

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.60199 | val 0.93205
  Epoch 016 - train 0.46527 | val 1.32078
  Classification -> best τ=0.585 (val F1=0.3183)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.55183 | val 0.92534
  Epoch 018 - train 0.43825 | val 1.10736
  Classification -> best τ=0.525 (val F1=0.2861)
  Directional -> Accuracy: 0.4043, MCC: -0.0814, F1: 0.3000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.62672 | val 0.94028
  Epoch 016 - train 0.57779 | val 0.88602
  Classification -> best τ=0.460 (val F1=0.4023)
  Directional -> Accuracy: 0.4000, MCC: -0.2056, F1: 0.4507

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.64042 | val 0.65677
  Epoch 020 - train 0.54330 | val 0.80583
  Classification -> best τ=0.685 (val F1=0.3749)
  Directional -> Accuracy: 0.5263, MCC: 0.1000, F1: 0.4706

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.60953 | val 0.81233
  Epoch 018 - train 0.51285 | val 0.91810
  Classification -> best τ=0.475 (val F1=0.1985)
  Directional -> Accuracy: 0.5231, MCC: 0.0000, F1: 0.0000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.58666 | val 0.83762
  Epoch 020 - train 0.42395 | val 1.11743
  Classification -> best τ=0.490 (val F1=0.4688)
  Directional -> Accuracy: 0.4545, MCC: -0.0637, F1: 0.3750

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.55332 | val 2.60483
  Epoch 016 - train 0.39307 | val 3.58603
  Classification -> best τ=0.700 (val F1=0.2570)
  Directional -> Accuracy: 0.5778, MCC: 0.1408, F1: 0.5128

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.62939 | val 0.80094
  Epoch 016 - train 0.56556 | val 0.95855
  Classification -> best τ=0.530 (val F1=0.0323)
  Directional -> Accuracy: 0.5714, MCC: 0.2282, F1: 0.5000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.54016 | val 0.84418
  Epoch 016 - train 0.50335 | val 1.92774
  Classification -> best τ=0.310 (val F1=0.2892)
  Directional -> Accuracy: 0.5357, MCC: 0.2308, F1: 0.3158

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.62218 | val 0.80430
  Epoch 017 - train 0.44917 | val 1.04737
  Classification -> best τ=0.530 (val F1=0.2618)
  Directional -> Accuracy: 0.5750, MCC: 0.1240, F1: 0.7119

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.59893 | val 0.80380
  Epoch 016 - train 0.51920 | val 1.03966
  Classification -> best τ=0.565 (val F1=0.2814)
  Directional -> Accuracy: 0.5476, MCC: 0.0835, F1: 0.4242

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.63475 | val 1.02877
  Epoch 016 - train 0.50127 | val 0.81200
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5476, MCC: 0.0000, F1: 0.7077

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.57913 | val 0.87009
  Epoch 017 - train 0.46932 | val 0.92351
  Classification -> best τ=0.420 (val F1=0.4397)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.63043 | val 0.69554
  Epoch 020 - train 0.51307 | val 0.98380
  Classification -> best τ=0.405 (val F1=0.3838)
  Directional -> Accuracy: 0.5278, MCC: -0.0359, F1: 0.6667

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.56137 | val 0.74805
  Epoch 018 - train 0.44024 | val 1.30060
  Classification -> best τ=0.255 (val F1=0.3078)
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.64936 | val 0.85585
  Epoch 019 - train 0.54077 | val 1.44677
  Classification -> best τ=0.290 (val F1=0.3001)
  Directional -> Accuracy: 0.4394, MCC: -0.1135, F1: 0.4638

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.52512 | val 1.19584
  Epoch 017 - train 0.41537 | val 1.94414
  Classification -> best τ=0.555 (val F1=0.3828)
  Directional -> Accuracy: 0.6429, MCC: 0.3290, F1: 0.5714

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.55183 | val 0.93306
  Epoch 016 - train 0.45652 | val 0.92631
  Classification -> best τ=0.595 (val F1=0.2478)
  Directional -> Accuracy: 0.5000, MCC: -0.0910, F1: 0.1250

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.57132 | val 1.00444
  Epoch 018 - train 0.44220 | val 0.97026
  Classification -> best τ=0.560 (val F1=0.3409)
  Directional -> Accuracy: 0.5652, MCC: 0.0094, F1: 0.6875

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.61319 | val 0.73543
  Epoch 019 - train 0.44547 | val 0.83713
  Classification -> best τ=0.435 (val F1=0.4011)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.57675 | val 1.74069
  Epoch 016 - train 0.48511 | val 2.71054
  Classification -> best τ=0.230 (val F1=0.2397)
  Directional -> Accuracy: 0.4865, MCC: 0.0000, F1: 0.6545

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.59393 | val 0.68988
  Epoch 020 - train 0.48191 | val 0.75316
  Classification -> best τ=0.490 (val F1=0.3500)
  Directional -> Accuracy: 0.4667, MCC: -0.0950, F1: 0.0769

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.42476 | val 1.83933
  Epoch 016 - train 0.28024 | val 2.45383
  Classification -> best τ=0.615 (val F1=0.4588)
  Directional -> Accuracy: 0.6429, MCC: 0.2513, F1: 0.7368

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.54396 | val 0.74004
  Epoch 020 - train 0.43671 | val 0.66962
  Classification -> best τ=0.530 (val F1=0.4385)
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.5455

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.63224 | val 1.15045
  Epoch 016 - train 0.58572 | val 0.94022
  Classification -> best τ=0.410 (val F1=0.2833)
  Directional -> Accuracy: 0.5636, MCC: 0.0924, F1: 0.7000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.52760 | val 2.01758
  Epoch 016 - train 0.47615 | val 2.26145
  Classification -> best τ=0.635 (val F1=0.4367)
  Directional -> Accuracy: 0.5357, MCC: 0.1768, F1: 0.6667

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.64352 | val 0.67838
  Epoch 020 - train 0.58499 | val 0.75410
  Classification -> best τ=0.710 (val F1=0.2719)
  Directional -> Accuracy: 0.6226, MCC: 0.2468, F1: 0.6154

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.54734 | val 2.07955
  Epoch 016 - train 0.48177 | val 2.37332
  Classification -> best τ=0.570 (val F1=0.1593)
  Directional -> Accuracy: 0.4727, MCC: -0.0350, F1: 0.3556

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.65979 | val 0.84269

[I 2026-02-22 18:55:23,795] Trial 285 finished with value: 0.3011423545131719 and parameters: {'feature_set': 'sector', 'model_type': 'BiGRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.4, 'batch_size': 16, 'learning_rate': 0.0059155571272197964, 'weight_decay': 0.0006727693560948995, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 15, 'max_epochs': 20, 'huber_delta': 0.9908363962172273, 'early_stopping_min_delta': 0.0011653895735246164}. Best is trial 252 with value: 0.3108162738957727.

  Epoch 020 - train 0.58778 | val 1.07498
  Classification -> best τ=0.455 (val F1=0.3815)
  Directional -> Accuracy: 0.6000, MCC: 0.2199, F1: 0.4286

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.3011423545131719
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.62308 | val 1.05368
  Epoch 016 - train 0.57496 | val 1.23497
  Classification -> best τ=0.660 (val F1=0.2510)
  Directional -> Accuracy: 0.5526, MCC: 0.0000, F1: 0.0000

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.55713 | val 0.83069
  Epoch 016 - train 0.46906 | val 0.83047
  Classification -> best τ=0.345 (val F1=0.2285)
  Directional -> Accuracy: 0.5778, MCC: 0.0000, F1: 0.7324

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.61001 | val 1.72816
  Epoch 016 - train 0.53769 | val 1.81887
  Classification -> best τ=0.710 (val F1=0.2559)
  Directional -> Accuracy: 0.4783, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.64393 | val 0.82448
  Epoch 016 - train 0.53750 | val 1.15118
  Classification -> best τ=0.435 (val F1=0.1566)
  Directional -> Accuracy: 0.4595, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.52552 | val 0.90118
  Epoch 020 - train 0.46097 | val 1.54456
  Classification -> best τ=0.725 (val F1=0.4745)
  Directional -> Accuracy: 0.6000, MCC: 0.2300, F1: 0.5238

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.55612 | val 0.74748
  Epoch 020 - train 0.39567 | val 0.69612
  Classification -> best τ=0.480 (val F1=0.4379)
  Directional -> Accuracy: 0.5217, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.66252 | val 0.82830
  Epoch 020 - train 0.54350 | val 1.09867
  Classification -> best τ=0.410 (val F1=0.3480)
  Directional -> Accuracy: 0.3971, MCC: 0.0000, F1: 0.5684

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.51101 | val 0.84064
  Epoch 020 - train 0.41622 | val 1.33580
  Classification -> best τ=0.180 (val F1=0.2100)
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.62832 | val 0.81489
  Epoch 016 - train 0.50775 | val 1.26068
  Classification -> best τ=0.610 (val F1=0.2443)
  Directional -> Accuracy: 0.5625, MCC: 0.0976, F1: 0.4615

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.60711 | val 0.77452
  Epoch 016 - train 0.52554 | val 0.83880
  Classification -> best τ=0.375 (val F1=0.2634)
  Directional -> Accuracy: 0.4203, MCC: -0.0401, F1: 0.5745

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.60666 | val 0.73571
  Epoch 020 - train 0.48551 | val 0.80810
  Classification -> best τ=0.475 (val F1=0.3241)
  Directional -> Accuracy: 0.5918, MCC: 0.1537, F1: 0.3750

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.60834 | val 1.38152
  Epoch 020 - train 0.49906 | val 1.74110
  Classification -> best τ=0.360 (val F1=0.3920)
  Directional -> Accuracy: 0.5088, MCC: 0.0048, F1: 0.6585

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.51767 | val 1.23284
  Epoch 017 - train 0.44200 | val 1.85013
  Classification -> best τ=0.400 (val F1=0.1550)
  Directional -> Accuracy: 0.4286, MCC: -0.1070, F1: 0.5556

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.66276 | val 0.64020
  Epoch 019 - train 0.52114 | val 0.71934
  Classification -> best τ=0.485 (val F1=0.3864)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.59844 | val 0.85522
  Epoch 016 - train 0.52218 | val 0.81704
  Classification -> best τ=0.675 (val F1=0.2078)
  Directional -> Accuracy: 0.5490, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.62788 | val 0.82076
  Epoch 020 - train 0.50135 | val 2.39344
  Classification -> best τ=0.240 (val F1=0.2795)
  Directional -> Accuracy: 0.5652, MCC: 0.1858, F1: 0.7115

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.60160 | val 0.84393
  Epoch 020 - train 0.52107 | val 1.29347
  Classification -> best τ=0.480 (val F1=0.2538)
  Directional -> Accuracy: 0.4138, MCC: 0.1477, F1: 0.1053

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.59709 | val 0.92514
  Epoch 016 - train 0.50689 | val 0.88685
  Classification -> best τ=0.495 (val F1=0.2220)
  Directional -> Accuracy: 0.4000, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.59735 | val 0.91607
  Epoch 016 - train 0.53159 | val 1.03541
  Classification -> best τ=0.295 (val F1=0.3421)
  Directional -> Accuracy: 0.5781, MCC: 0.0000, F1: 0.7327

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.57553 | val 0.77762
  Epoch 020 - train 0.45669 | val 1.00083
  Classification -> best τ=0.540 (val F1=0.2881)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.57783 | val 0.87720
  Epoch 018 - train 0.51250 | val 1.19098
  Classification -> best τ=0.635 (val F1=0.2398)
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.61560 | val 0.91209
  Epoch 016 - train 0.55861 | val 0.94243
  Classification -> best τ=0.465 (val F1=0.1709)
  Directional -> Accuracy: 0.4923, MCC: -0.0699, F1: 0.6526

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.65466 | val 0.66063
  Epoch 019 - train 0.56132 | val 0.89335
  Classification -> best τ=0.595 (val F1=0.4177)
  Directional -> Accuracy: 0.5439, MCC: 0.1758, F1: 0.4348

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.64592 | val 0.86470
  Epoch 020 - train 0.51265 | val 0.88725
  Classification -> best τ=0.725 (val F1=0.1985)
  Directional -> Accuracy: 0.5231, MCC: 0.0000, F1: 0.0000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.56061 | val 0.66892
  Epoch 017 - train 0.52385 | val 0.84320
  Classification -> best τ=0.380 (val F1=0.4688)
  Directional -> Accuracy: 0.5273, MCC: 0.0467, F1: 0.5667

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.54043 | val 0.88557
  Epoch 016 - train 0.46446 | val 1.17352
  Classification -> best τ=0.550 (val F1=0.2786)
  Directional -> Accuracy: 0.6222, MCC: 0.2440, F1: 0.5854

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.58559 | val 0.73887
  Epoch 020 - train 0.51018 | val 0.83456
  Classification -> best τ=0.565 (val F1=0.0138)
  Directional -> Accuracy: 0.5238, MCC: 0.0278, F1: 0.5833

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.55720 | val 1.10904
  Epoch 017 - train 0.46889 | val 1.24501
  Classification -> best τ=0.330 (val F1=0.3690)
  Directional -> Accuracy: 0.4464, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.58873 | val 0.76550
  Epoch 016 - train 0.46165 | val 0.84493
  Classification -> best τ=0.550 (val F1=0.1457)
  Directional -> Accuracy: 0.6000, MCC: 0.2536, F1: 0.7333

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.59981 | val 0.85658
  Epoch 016 - train 0.52887 | val 1.02958
  Classification -> best τ=0.520 (val F1=0.2814)
  Directional -> Accuracy: 0.5238, MCC: 0.0608, F1: 0.5652

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.56203 | val 0.81123
  Epoch 016 - train 0.46981 | val 1.03218
  Classification -> best τ=0.470 (val F1=0.0409)
  Directional -> Accuracy: 0.5476, MCC: 0.0214, F1: 0.6984

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.54435 | val 0.93824
  Epoch 016 - train 0.46207 | val 1.06028
  Classification -> best τ=0.380 (val F1=0.3987)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.62581 | val 0.75656
  Epoch 020 - train 0.54464 | val 0.90441
  Classification -> best τ=0.450 (val F1=0.3066)
  Directional -> Accuracy: 0.4444, MCC: 0.0000, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.56752 | val 1.21401
  Epoch 016 - train 0.42760 | val 1.33022
  Classification -> best τ=0.635 (val F1=0.2000)
  Directional -> Accuracy: 0.5814, MCC: 0.2261, F1: 0.3077

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.60985 | val 1.04935
  Epoch 016 - train 0.55733 | val 1.02458
  Classification -> best τ=0.275 (val F1=0.2778)
  Directional -> Accuracy: 0.5758, MCC: 0.0000, F1: 0.7308

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.50531 | val 1.07312
  Epoch 020 - train 0.34589 | val 1.37183
  Classification -> best τ=0.440 (val F1=0.2439)
  Directional -> Accuracy: 0.6429, MCC: 0.2843, F1: 0.6939

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.56624 | val 0.99239
  Epoch 016 - train 0.45796 | val 1.05257
  Classification -> best τ=0.430 (val F1=0.2530)
  Directional -> Accuracy: 0.4821, MCC: -0.0185, F1: 0.5246

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.64343 | val 0.73514
  Epoch 018 - train 0.45927 | val 0.90235
  Classification -> best τ=0.585 (val F1=0.2268)
  Directional -> Accuracy: 0.5217, MCC: -0.0040, F1: 0.6071

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.61868 | val 0.84997
  Epoch 016 - train 0.47199 | val 0.74798
  Classification -> best τ=0.520 (val F1=0.5119)
  Directional -> Accuracy: 0.3958, MCC: 0.1544, F1: 0.5397

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.55180 | val 1.40784
  Epoch 016 - train 0.48924 | val 1.66811
  Classification -> best τ=0.415 (val F1=0.2007)
  Directional -> Accuracy: 0.4865, MCC: -0.0153, F1: 0.5870

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.62035 | val 1.12197
  Epoch 020 - train 0.48216 | val 0.87753
  Classification -> best τ=0.700 (val F1=0.4080)
  Directional -> Accuracy: 0.6444, MCC: 0.2885, F1: 0.6522

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.46961 | val 1.70952
  Epoch 016 - train 0.37193 | val 2.13371
  Classification -> best τ=0.530 (val F1=0.4082)
  Directional -> Accuracy: 0.6667, MCC: 0.3066, F1: 0.7500

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.50981 | val 0.62521
  Epoch 020 - train 0.39393 | val 0.66488
  Classification -> best τ=0.355 (val F1=0.5514)
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.5455

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.64604 | val 1.18535
  Epoch 019 - train 0.60629 | val 1.09480
  Classification -> best τ=0.575 (val F1=0.2036)
  Directional -> Accuracy: 0.4727, MCC: 0.1242, F1: 0.0645

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.49653 | val 2.32665
  Epoch 016 - train 0.39901 | val 2.91992
  Classification -> best τ=0.715 (val F1=0.3846)
  Directional -> Accuracy: 0.4821, MCC: -0.0099, F1: 0.6329

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.63434 | val 0.95125
  Epoch 016 - train 0.56637 | val 1.19734
  Classification -> best τ=0.455 (val F1=0.2298)
  Directional -> Accuracy: 0.4906, MCC: -0.0369, F1: 0.6087

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.52515 | val 3.39440
  Epoch 016 - train 0.45082 | val 3.05164
  Classification -> best τ=0.745 (val F1=0.2291)
  Directional -> Accuracy: 0.4727, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.61579 | val 0.70013

[I 2026-02-22 19:00:34,079] Trial 286 finished with value: 0.2848400221119529 and parameters: {'feature_set': 'sector', 'model_type': 'BiGRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.4, 'batch_size': 16, 'learning_rate': 0.0053569304738640255, 'weight_decay': 0.0006767584079760557, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 15, 'max_epochs': 20, 'huber_delta': 0.994582532509814, 'early_stopping_min_delta': 0.0013768289031006826}. Best is trial 252 with value: 0.3108162738957727.

  Epoch 020 - train 0.55779 | val 0.84722
  Classification -> best τ=0.515 (val F1=0.2920)
  Directional -> Accuracy: 0.5333, MCC: 0.0580, F1: 0.3333

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2848400221119529
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.63352 | val 0.71066
  Epoch 020 - train 0.61659 | val 0.89977
  Classification -> best τ=0.495 (val F1=0.2919)
  Directional -> Accuracy: 0.5526, MCC: 0.0249, F1: 0.1053

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.55633 | val 0.91757
  Epoch 017 - train 0.48113 | val 1.20280
  Classification -> best τ=0.635 (val F1=0.2523)
  Directional -> Accuracy: 0.5778, MCC: 0.1170, F1: 0.6545

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.60793 | val 1.06549
  Epoch 017 - train 0.50689 | val 1.52945
  Classification -> best τ=0.610 (val F1=0.3114)
  Directional -> Accuracy: 0.5217, MCC: 0.0948, F1: 0.3125

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.61497 | val 0.83761
  Epoch 016 - train 0.54388 | val 1.20456
  Classification -> best τ=0.360 (val F1=0.2230)
  Directional -> Accuracy: 0.5405, MCC: 0.0000, F1: 0.7018

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.55700 | val 1.81395
  Epoch 016 - train 0.47660 | val 1.55186
  Classification -> best τ=0.675 (val F1=0.3541)
  Directional -> Accuracy: 0.5400, MCC: 0.1375, F1: 0.3429

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.57602 | val 0.73631
  Epoch 020 - train 0.43074 | val 0.98267
  Classification -> best τ=0.600 (val F1=0.3624)
  Directional -> Accuracy: 0.5217, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.63425 | val 0.93342
  Epoch 016 - train 0.55242 | val 1.23729
  Classification -> best τ=0.435 (val F1=0.3071)
  Directional -> Accuracy: 0.5441, MCC: 0.1157, F1: 0.5231

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.50849 | val 0.91589
  Epoch 020 - train 0.34828 | val 1.32615
  Classification -> best τ=0.425 (val F1=0.3632)
  Directional -> Accuracy: 0.4286, MCC: -0.2041, F1: 0.2500

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.60514 | val 1.28880
  Epoch 016 - train 0.49724 | val 1.54443
  Classification -> best τ=0.495 (val F1=0.0520)
  Directional -> Accuracy: 0.4375, MCC: 0.0000, F1: 0.6087

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.60103 | val 0.94835
  Epoch 016 - train 0.49933 | val 1.22072
  Classification -> best τ=0.390 (val F1=0.1554)
  Directional -> Accuracy: 0.4783, MCC: 0.0645, F1: 0.5714

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.61397 | val 0.87666
  Epoch 020 - train 0.40938 | val 2.49864
  Classification -> best τ=0.520 (val F1=0.2543)
  Directional -> Accuracy: 0.5918, MCC: 0.1804, F1: 0.2308

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.60247 | val 0.90265
  Epoch 018 - train 0.48958 | val 1.13032
  Classification -> best τ=0.530 (val F1=0.1450)
  Directional -> Accuracy: 0.5088, MCC: 0.0000, F1: 0.6744

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.55671 | val 0.90490
  Epoch 020 - train 0.34047 | val 1.67049
  Classification -> best τ=0.435 (val F1=0.2427)
  Directional -> Accuracy: 0.5238, MCC: 0.0123, F1: 0.3750

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.61438 | val 0.66645
  Epoch 017 - train 0.51671 | val 0.79453
  Classification -> best τ=0.420 (val F1=0.4160)
  Directional -> Accuracy: 0.5167, MCC: 0.0431, F1: 0.2927

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.65757 | val 0.71369
  Epoch 019 - train 0.50874 | val 0.86328
  Classification -> best τ=0.385 (val F1=0.1925)
  Directional -> Accuracy: 0.5098, MCC: 0.0921, F1: 0.6032

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.62178 | val 1.05048
  Epoch 016 - train 0.54954 | val 2.25342
  Classification -> best τ=0.585 (val F1=0.3151)
  Directional -> Accuracy: 0.5217, MCC: 0.0405, F1: 0.5479

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.59822 | val 0.75626
  Epoch 020 - train 0.48800 | val 1.20535
  Classification -> best τ=0.480 (val F1=0.3218)
  Directional -> Accuracy: 0.3793, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.58091 | val 0.90068
  Epoch 016 - train 0.56879 | val 0.98979
  Classification -> best τ=0.560 (val F1=0.1895)
  Directional -> Accuracy: 0.4000, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.57461 | val 0.88641
  Epoch 016 - train 0.50641 | val 0.81049
  Classification -> best τ=0.390 (val F1=0.3689)
  Directional -> Accuracy: 0.5469, MCC: 0.0949, F1: 0.5797

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.56523 | val 0.74098
  Epoch 020 - train 0.46167 | val 1.09007
  Classification -> best τ=0.500 (val F1=0.2614)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.57794 | val 0.76528
  Epoch 016 - train 0.51613 | val 0.75997
  Classification -> best τ=0.590 (val F1=0.1978)
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.62022 | val 1.08691
  Epoch 019 - train 0.45749 | val 1.77819
  Classification -> best τ=0.455 (val F1=0.2571)
  Directional -> Accuracy: 0.5385, MCC: 0.1688, F1: 0.2105

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.65311 | val 0.70282
  Epoch 020 - train 0.53907 | val 0.77131
  Classification -> best τ=0.725 (val F1=0.4845)
  Directional -> Accuracy: 0.5263, MCC: 0.0509, F1: 0.5574

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.62971 | val 0.82188
  Epoch 016 - train 0.51242 | val 0.85155
  Classification -> best τ=0.465 (val F1=0.1878)
  Directional -> Accuracy: 0.4923, MCC: 0.0632, F1: 0.6452

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.58523 | val 0.66186
  Epoch 020 - train 0.43842 | val 1.12589
  Classification -> best τ=0.210 (val F1=0.5197)
  Directional -> Accuracy: 0.4909, MCC: 0.0659, F1: 0.2632

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.53778 | val 2.41827
  Epoch 016 - train 0.47591 | val 3.41713
  Classification -> best τ=0.770 (val F1=0.2035)
  Directional -> Accuracy: 0.5333, MCC: -0.0068, F1: 0.3226

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.59315 | val 0.81293
  Epoch 018 - train 0.52000 | val 0.71824
  Classification -> best τ=0.590 (val F1=0.2071)
  Directional -> Accuracy: 0.5238, MCC: 0.0278, F1: 0.5833

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.57934 | val 0.80033
  Epoch 016 - train 0.51189 | val 0.99889
  Classification -> best τ=0.285 (val F1=0.2916)
  Directional -> Accuracy: 0.4464, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.58924 | val 0.94023
  Epoch 020 - train 0.40824 | val 1.06483
  Classification -> best τ=0.600 (val F1=0.3427)
  Directional -> Accuracy: 0.5000, MCC: -0.0754, F1: 0.6296

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.62062 | val 1.49238
  Epoch 016 - train 0.54534 | val 1.78167
  Classification -> best τ=0.490 (val F1=0.3244)
  Directional -> Accuracy: 0.5476, MCC: 0.0953, F1: 0.5366

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.58226 | val 0.75935
  Epoch 020 - train 0.43042 | val 1.24819
  Classification -> best τ=0.420 (val F1=0.2357)
  Directional -> Accuracy: 0.5476, MCC: 0.0000, F1: 0.7077

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.51692 | val 0.72005
  Epoch 020 - train 0.38549 | val 1.01300
  Classification -> best τ=0.335 (val F1=0.3541)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.59140 | val 0.74191
  Epoch 020 - train 0.50950 | val 1.02791
  Classification -> best τ=0.455 (val F1=0.3568)
  Directional -> Accuracy: 0.4583, MCC: 0.1061, F1: 0.0488

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.58103 | val 1.09379
  Epoch 016 - train 0.45124 | val 1.32377
  Classification -> best τ=0.550 (val F1=0.2245)
  Directional -> Accuracy: 0.4884, MCC: -0.0641, F1: 0.1538

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.59865 | val 0.82264
  Epoch 016 - train 0.52431 | val 1.23244
  Classification -> best τ=0.310 (val F1=0.2658)
  Directional -> Accuracy: 0.4394, MCC: 0.1065, F1: 0.0513

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.53914 | val 0.82256
  Epoch 018 - train 0.41918 | val 1.08607
  Classification -> best τ=0.505 (val F1=0.4416)
  Directional -> Accuracy: 0.5000, MCC: 0.0561, F1: 0.2222

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.54981 | val 0.96556
  Epoch 016 - train 0.46650 | val 0.98279
  Classification -> best τ=0.460 (val F1=0.2026)
  Directional -> Accuracy: 0.5179, MCC: 0.0283, F1: 0.4706

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.51741 | val 1.24361
  Epoch 020 - train 0.34802 | val 1.52119
  Classification -> best τ=0.265 (val F1=0.2118)
  Directional -> Accuracy: 0.5435, MCC: -0.1369, F1: 0.6957

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.54178 | val 0.91124
  Epoch 017 - train 0.48344 | val 1.39454
  Classification -> best τ=0.550 (val F1=0.3887)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.54820 | val 1.31221
  Epoch 017 - train 0.48805 | val 2.09553
  Classification -> best τ=0.275 (val F1=0.2892)
  Directional -> Accuracy: 0.4865, MCC: 0.0000, F1: 0.6545

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.57921 | val 0.76001
  Epoch 017 - train 0.53002 | val 0.98924
  Classification -> best τ=0.455 (val F1=0.3873)
  Directional -> Accuracy: 0.5556, MCC: 0.1632, F1: 0.6875

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.49001 | val 1.83870
  Epoch 019 - train 0.30115 | val 2.17912
  Classification -> best τ=0.450 (val F1=0.3851)
  Directional -> Accuracy: 0.6190, MCC: 0.2041, F1: 0.6923

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.57538 | val 0.75594
  Epoch 020 - train 0.40979 | val 1.01190
  Classification -> best τ=0.580 (val F1=0.4216)
  Directional -> Accuracy: 0.3958, MCC: 0.0222, F1: 0.5397

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.62315 | val 0.94490
  Epoch 016 - train 0.62350 | val 0.77746
  Classification -> best τ=0.430 (val F1=0.2291)
  Directional -> Accuracy: 0.4182, MCC: -0.2155, F1: 0.5294

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.55613 | val 3.67660
  Epoch 016 - train 0.42066 | val 5.18388
  Classification -> best τ=0.760 (val F1=0.3497)
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.6506

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.66000 | val 0.72613
  Epoch 020 - train 0.59919 | val 0.71512
  Classification -> best τ=0.645 (val F1=0.2728)
  Directional -> Accuracy: 0.5094, MCC: 0.0275, F1: 0.4091

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.57631 | val 2.05960
  Epoch 016 - train 0.46871 | val 2.77857
  Classification -> best τ=0.710 (val F1=0.3274)
  Directional -> Accuracy: 0.4364, MCC: -0.1202, F1: 0.2051

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.63760 | val 0.83928

[I 2026-02-22 19:05:44,159] Trial 287 finished with value: 0.2917154956373102 and parameters: {'feature_set': 'sector', 'model_type': 'BiGRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.4, 'batch_size': 16, 'learning_rate': 0.006090841860552479, 'weight_decay': 0.0005364074820221505, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 15, 'max_epochs': 20, 'huber_delta': 0.8599464000754184, 'early_stopping_min_delta': 0.000700620878712711}. Best is trial 252 with value: 0.3108162738957727.

  Epoch 020 - train 0.52945 | val 0.98191
  Classification -> best τ=0.500 (val F1=0.2623)
  Directional -> Accuracy: 0.5167, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2917154956373102
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down', 'finbert_neutral']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.62854 | val 0.74547
  Epoch 016 - train 0.59366 | val 1.12110
  Classification -> best τ=0.680 (val F1=0.2510)
  Directional -> Accuracy: 0.5263, MCC: -0.0936, F1: 0.0526

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.62960 | val 0.73621
  Epoch 018 - train 0.52789 | val 0.78068
  Classification -> best τ=0.500 (val F1=0.1941)
  Directional -> Accuracy: 0.5778, MCC: 0.0950, F1: 0.6780

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.59644 | val 0.66296
  Epoch 016 - train 0.53672 | val 0.98676
  Classification -> best τ=0.590 (val F1=0.3313)
  Directional -> Accuracy: 0.4565, MCC: -0.0996, F1: 0.0741

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.64520 | val 0.97329
  Epoch 016 - train 0.59343 | val 0.87278
  Classification -> best τ=0.375 (val F1=0.2016)
  Directional -> Accuracy: 0.5405, MCC: 0.0710, F1: 0.5854

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.57231 | val 0.73188
  Epoch 019 - train 0.44879 | val 0.97976
  Classification -> best τ=0.660 (val F1=0.4862)
  Directional -> Accuracy: 0.7000, MCC: 0.4223, F1: 0.6667

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.54394 | val 0.72151
  Epoch 017 - train 0.45111 | val 0.83704
  Classification -> best τ=0.630 (val F1=0.2204)
  Directional -> Accuracy: 0.5217, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.66690 | val 0.78335
  Epoch 020 - train 0.59336 | val 2.92185
  Classification -> best τ=0.395 (val F1=0.2665)
  Directional -> Accuracy: 0.4118, MCC: 0.0991, F1: 0.5745

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.57549 | val 0.67824
  Epoch 020 - train 0.34891 | val 1.81595
  Classification -> best τ=0.395 (val F1=0.0679)
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.56548 | val 1.11593
  Epoch 016 - train 0.54271 | val 1.57690
  Classification -> best τ=0.585 (val F1=0.2784)
  Directional -> Accuracy: 0.6875, MCC: 0.3749, F1: 0.5161

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.60573 | val 0.77590
  Epoch 020 - train 0.55940 | val 0.69319
  Classification -> best τ=0.705 (val F1=0.2251)
  Directional -> Accuracy: 0.4783, MCC: -0.0511, F1: 0.4194

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.64097 | val 0.72050
  Epoch 020 - train 0.63108 | val 0.69862
  Classification -> best τ=0.465 (val F1=0.3567)
  Directional -> Accuracy: 0.5918, MCC: 0.1804, F1: 0.2308

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.68019 | val 0.68631
  Epoch 020 - train 0.57210 | val 1.45300
  Classification -> best τ=0.580 (val F1=0.2225)
  Directional -> Accuracy: 0.5789, MCC: 0.2092, F1: 0.6923

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.51653 | val 1.02237
  Epoch 016 - train 0.42034 | val 1.11831
  Classification -> best τ=0.555 (val F1=0.2083)
  Directional -> Accuracy: 0.5714, MCC: 0.1158, F1: 0.4375

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.65401 | val 0.70916
  Epoch 020 - train 0.56999 | val 0.88913
  Classification -> best τ=0.400 (val F1=0.3320)
  Directional -> Accuracy: 0.5833, MCC: 0.3015, F1: 0.2857

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.59472 | val 0.74649
  Epoch 020 - train 0.47705 | val 0.86212
  Classification -> best τ=0.450 (val F1=0.2270)
  Directional -> Accuracy: 0.5882, MCC: 0.1793, F1: 0.5714

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.68629 | val 0.71113
  Epoch 020 - train 0.60687 | val 0.77453
  Classification -> best τ=0.340 (val F1=0.3339)
  Directional -> Accuracy: 0.5507, MCC: 0.1304, F1: 0.7048

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.65623 | val 1.11803
  Epoch 016 - train 0.59301 | val 1.76188
  Classification -> best τ=0.670 (val F1=0.1303)
  Directional -> Accuracy: 0.3793, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.64055 | val 0.79952
  Epoch 016 - train 0.60501 | val 1.09805
  Classification -> best τ=0.730 (val F1=0.1548)
  Directional -> Accuracy: 0.4000, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.68011 | val 0.68900
  Epoch 020 - train 0.61598 | val 0.68835
  Classification -> best τ=0.375 (val F1=0.2843)
  Directional -> Accuracy: 0.4688, MCC: 0.0725, F1: 0.2609

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.64146 | val 0.99233
  Epoch 017 - train 0.55826 | val 1.03066
  Classification -> best τ=0.735 (val F1=0.2902)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.68980 | val 0.83045
  Epoch 016 - train 0.62178 | val 0.75385
  Classification -> best τ=0.585 (val F1=0.3020)
  Directional -> Accuracy: 0.5319, MCC: -0.0118, F1: 0.6333

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.66402 | val 1.20661
  Epoch 017 - train 0.64586 | val 0.99111
  Classification -> best τ=0.600 (val F1=0.0246)
  Directional -> Accuracy: 0.4923, MCC: -0.0027, F1: 0.0571

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.67237 | val 0.76877
  Epoch 020 - train 0.65249 | val 0.66361
  Classification -> best τ=0.530 (val F1=0.4138)
  Directional -> Accuracy: 0.5789, MCC: 0.1924, F1: 0.5556

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.63204 | val 0.88658
  Epoch 017 - train 0.59831 | val 0.85335
  Classification -> best τ=0.565 (val F1=0.1415)
  Directional -> Accuracy: 0.4769, MCC: -0.0548, F1: 0.4138

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.65906 | val 0.78732
  Epoch 018 - train 0.45734 | val 1.11959
  Classification -> best τ=0.600 (val F1=0.4582)
  Directional -> Accuracy: 0.5636, MCC: 0.2170, F1: 0.4286

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.45593 | val 3.72551
  Epoch 016 - train 0.38414 | val 7.13652
  Classification -> best τ=0.610 (val F1=0.3039)
  Directional -> Accuracy: 0.5111, MCC: 0.1621, F1: 0.6071

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.61438 | val 0.82248
  Epoch 019 - train 0.55339 | val 1.05994
  Classification -> best τ=0.665 (val F1=0.1936)
  Directional -> Accuracy: 0.5000, MCC: 0.1291, F1: 0.3226

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.60947 | val 0.89054
  Epoch 018 - train 0.52153 | val 1.65077
  Classification -> best τ=0.615 (val F1=0.3322)
  Directional -> Accuracy: 0.4464, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.57057 | val 1.53289
  Epoch 016 - train 0.47154 | val 2.46878
  Classification -> best τ=0.565 (val F1=0.1918)
  Directional -> Accuracy: 0.4750, MCC: 0.1448, F1: 0.0870

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.64136 | val 1.28828
  Epoch 017 - train 0.49237 | val 1.66375
  Classification -> best τ=0.565 (val F1=0.3501)
  Directional -> Accuracy: 0.5238, MCC: 0.0500, F1: 0.5238

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.64905 | val 0.63522
  Epoch 020 - train 0.57497 | val 0.98743
  Classification -> best τ=0.635 (val F1=0.3825)
  Directional -> Accuracy: 0.4762, MCC: 0.0387, F1: 0.2143

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.50968 | val 0.85508
  Epoch 016 - train 0.37434 | val 1.09392
  Classification -> best τ=0.435 (val F1=0.2273)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.66797 | val 0.67732
  Epoch 020 - train 0.60479 | val 0.67772
  Classification -> best τ=0.455 (val F1=0.4023)
  Directional -> Accuracy: 0.5556, MCC: 0.1250, F1: 0.5556

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.54765 | val 1.15555
  Epoch 016 - train 0.38917 | val 1.92391
  Classification -> best τ=0.675 (val F1=0.2603)
  Directional -> Accuracy: 0.5814, MCC: 0.1635, F1: 0.5000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.61990 | val 0.98543
  Epoch 016 - train 0.51957 | val 1.03619
  Classification -> best τ=0.335 (val F1=0.3855)
  Directional -> Accuracy: 0.5606, MCC: 0.0030, F1: 0.7010

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.54636 | val 0.62504
  Epoch 020 - train 0.28373 | val 1.17633
  Classification -> best τ=0.660 (val F1=0.5477)
  Directional -> Accuracy: 0.6429, MCC: 0.3127, F1: 0.5946

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.58967 | val 1.17934
  Epoch 016 - train 0.49265 | val 1.16751
  Classification -> best τ=0.485 (val F1=0.2450)
  Directional -> Accuracy: 0.5000, MCC: 0.0051, F1: 0.5000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.55652 | val 1.20192
  Epoch 020 - train 0.41356 | val 0.68491
  Classification -> best τ=0.465 (val F1=0.3409)
  Directional -> Accuracy: 0.4130, MCC: 0.0314, F1: 0.1290

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.54567 | val 0.67536
  Epoch 017 - train 0.32673 | val 0.79796
  Classification -> best τ=0.405 (val F1=0.4242)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.66859 | val 0.82698
  Epoch 020 - train 0.54982 | val 1.37462
  Classification -> best τ=0.400 (val F1=0.3909)
  Directional -> Accuracy: 0.4865, MCC: 0.0000, F1: 0.6545

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.58475 | val 0.65969
  Epoch 020 - train 0.47652 | val 1.28603
  Classification -> best τ=0.525 (val F1=0.3953)
  Directional -> Accuracy: 0.4889, MCC: -0.0181, F1: 0.4390

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.55818 | val 1.30379
  Epoch 016 - train 0.36477 | val 1.61066
  Classification -> best τ=0.550 (val F1=0.3015)
  Directional -> Accuracy: 0.5476, MCC: 0.0574, F1: 0.6275

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.64762 | val 0.82944
  Epoch 020 - train 0.45645 | val 0.77727
  Classification -> best τ=0.505 (val F1=0.4542)
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.5455

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.62891 | val 0.80459
  Epoch 017 - train 0.60014 | val 0.74910
  Classification -> best τ=0.655 (val F1=0.2036)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.60970 | val 1.41452
  Epoch 016 - train 0.55749 | val 1.30103
  Classification -> best τ=0.665 (val F1=0.3695)
  Directional -> Accuracy: 0.5000, MCC: -0.0065, F1: 0.4400

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.70238 | val 0.71608
  Epoch 020 - train 0.61929 | val 1.18310
  Classification -> best τ=0.565 (val F1=0.1657)
  Directional -> Accuracy: 0.6038, MCC: 0.2082, F1: 0.6441

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.62750 | val 2.25632
  Epoch 017 - train 0.52436 | val 3.30962
  Classification -> best τ=0.735 (val F1=0.2224)
  Directional -> Accuracy: 0.4364, MCC: -0.1170, F1: 0.2439

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.66710 | val 0.68144

[I 2026-02-22 19:10:58,236] Trial 288 finished with value: 0.28611721800746365 and parameters: {'feature_set': 'finbert', 'model_type': 'BiGRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.4, 'batch_size': 16, 'learning_rate': 0.006390637107425816, 'weight_decay': 0.0009968062515270104, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 15, 'max_epochs': 20, 'huber_delta': 0.8750687020783254, 'early_stopping_min_delta': 0.0008741655615260575}. Best is trial 252 with value: 0.3108162738957727.

  Epoch 020 - train 0.58509 | val 1.10082
  Classification -> best τ=0.415 (val F1=0.2405)
  Directional -> Accuracy: 0.5500, MCC: 0.1025, F1: 0.5574

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.28611721800746365
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.61596 | val 1.19102
  Epoch 016 - train 0.60897 | val 1.42791
  Classification -> best τ=0.515 (val F1=0.1671)
  Directional -> Accuracy: 0.5921, MCC: 0.1686, F1: 0.5231

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.60976 | val 0.76859
  Epoch 020 - train 0.43341 | val 0.99349
  Classification -> best τ=0.560 (val F1=0.2523)
  Directional -> Accuracy: 0.6444, MCC: 0.2545, F1: 0.7143

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.59127 | val 0.95693
  Epoch 016 - train 0.49148 | val 1.23643
  Classification -> best τ=0.455 (val F1=0.2779)
  Directional -> Accuracy: 0.5217, MCC: 0.0000, F1: 0.6857

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.61120 | val 1.55848
  Epoch 016 - train 0.58882 | val 1.03473
  Classification -> best τ=0.430 (val F1=0.0752)
  Directional -> Accuracy: 0.4595, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.59578 | val 0.80226
  Epoch 016 - train 0.49282 | val 2.02219
  Classification -> best τ=0.625 (val F1=0.4414)
  Directional -> Accuracy: 0.5600, MCC: 0.1534, F1: 0.4500

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.59710 | val 0.69909
  Epoch 020 - train 0.46859 | val 0.76991
  Classification -> best τ=0.405 (val F1=0.4159)
  Directional -> Accuracy: 0.5652, MCC: 0.2227, F1: 0.1667

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.61940 | val 0.95426
  Epoch 016 - train 0.55474 | val 1.56116
  Classification -> best τ=0.500 (val F1=0.3010)
  Directional -> Accuracy: 0.5294, MCC: 0.1704, F1: 0.5789

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.54653 | val 0.59643
  Epoch 020 - train 0.41458 | val 0.97783
  Classification -> best τ=0.550 (val F1=0.3632)
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.56814 | val 0.88121
  Epoch 017 - train 0.54001 | val 0.94714
  Classification -> best τ=0.480 (val F1=0.4647)
  Directional -> Accuracy: 0.6042, MCC: 0.2212, F1: 0.5957

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.58531 | val 1.01001
  Epoch 016 - train 0.47288 | val 0.95513
  Classification -> best τ=0.425 (val F1=0.2097)
  Directional -> Accuracy: 0.4638, MCC: -0.0208, F1: 0.5067

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.61344 | val 0.87779
  Epoch 020 - train 0.54283 | val 1.21073
  Classification -> best τ=0.535 (val F1=0.3729)
  Directional -> Accuracy: 0.5714, MCC: 0.1599, F1: 0.0870

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.59532 | val 1.10847
  Epoch 016 - train 0.50519 | val 1.33449
  Classification -> best τ=0.475 (val F1=0.2747)
  Directional -> Accuracy: 0.5439, MCC: 0.1422, F1: 0.6829

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.55977 | val 0.92337
  Epoch 020 - train 0.36500 | val 2.52612
  Classification -> best τ=0.435 (val F1=0.2777)
  Directional -> Accuracy: 0.5476, MCC: 0.0000, F1: 0.0000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.63126 | val 0.65803
  Epoch 020 - train 0.56461 | val 0.63808
  Classification -> best τ=0.510 (val F1=0.3126)
  Directional -> Accuracy: 0.4667, MCC: -0.0894, F1: 0.2000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.66926 | val 0.72330
  Epoch 020 - train 0.55268 | val 0.81521
  Classification -> best τ=0.315 (val F1=0.3036)
  Directional -> Accuracy: 0.5098, MCC: 0.2266, F1: 0.6479

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.63088 | val 0.96356
  Epoch 020 - train 0.62169 | val 0.97097
  Classification -> best τ=0.785 (val F1=0.3367)
  Directional -> Accuracy: 0.5362, MCC: 0.1179, F1: 0.4286

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.62721 | val 0.87425
  Epoch 018 - train 0.47092 | val 1.98129
  Classification -> best τ=0.425 (val F1=0.4028)
  Directional -> Accuracy: 0.4310, MCC: 0.0715, F1: 0.2326

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.59971 | val 0.83925
  Epoch 016 - train 0.51602 | val 0.96252
  Classification -> best τ=0.575 (val F1=0.1938)
  Directional -> Accuracy: 0.5200, MCC: 0.2041, F1: 0.4000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.58117 | val 1.02790
  Epoch 016 - train 0.51220 | val 1.35989
  Classification -> best τ=0.335 (val F1=0.2843)
  Directional -> Accuracy: 0.6094, MCC: 0.1571, F1: 0.7191

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.55365 | val 0.96336
  Epoch 020 - train 0.45713 | val 1.34650
  Classification -> best τ=0.485 (val F1=0.3161)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.63009 | val 0.74101
  Epoch 020 - train 0.47794 | val 0.99877
  Classification -> best τ=0.770 (val F1=0.3835)
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.63032 | val 0.88044
  Epoch 016 - train 0.53853 | val 1.66017
  Classification -> best τ=0.520 (val F1=0.3468)
  Directional -> Accuracy: 0.4923, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.63888 | val 0.64689
  Epoch 020 - train 0.56874 | val 0.61013
  Classification -> best τ=0.470 (val F1=0.4008)
  Directional -> Accuracy: 0.6491, MCC: 0.2845, F1: 0.7436

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.66601 | val 0.68988
  Epoch 018 - train 0.56539 | val 1.93706
  Classification -> best τ=0.485 (val F1=0.1874)
  Directional -> Accuracy: 0.5077, MCC: 0.0049, F1: 0.4286

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.57869 | val 0.74955
  Epoch 019 - train 0.48801 | val 0.85208
  Classification -> best τ=0.385 (val F1=0.4524)
  Directional -> Accuracy: 0.5455, MCC: 0.0637, F1: 0.6269

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.52513 | val 1.05511
  Epoch 016 - train 0.45131 | val 1.29125
  Classification -> best τ=0.705 (val F1=0.2318)
  Directional -> Accuracy: 0.3778, MCC: -0.3181, F1: 0.1765

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.60675 | val 0.68975
  Epoch 016 - train 0.53230 | val 0.82831
  Classification -> best τ=0.560 (val F1=0.1936)
  Directional -> Accuracy: 0.5714, MCC: 0.2041, F1: 0.5263

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.56095 | val 0.90620
  Epoch 017 - train 0.47568 | val 1.88900
  Classification -> best τ=0.345 (val F1=0.3147)
  Directional -> Accuracy: 0.4464, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.53785 | val 1.03828
  Epoch 017 - train 0.47187 | val 0.70773
  Classification -> best τ=0.480 (val F1=0.1580)
  Directional -> Accuracy: 0.6000, MCC: 0.2536, F1: 0.7333

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.61426 | val 2.14735
  Epoch 020 - train 0.40308 | val 2.73560
  Classification -> best τ=0.690 (val F1=0.3501)
  Directional -> Accuracy: 0.4762, MCC: -0.0608, F1: 0.3889

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.61074 | val 1.06546
  Epoch 017 - train 0.47044 | val 1.78125
  Classification -> best τ=0.445 (val F1=0.1324)
  Directional -> Accuracy: 0.4048, MCC: -0.1870, F1: 0.4186

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.54281 | val 0.85158
  Epoch 016 - train 0.53749 | val 0.96850
  Classification -> best τ=0.305 (val F1=0.3196)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.59267 | val 0.75211
  Epoch 020 - train 0.59740 | val 0.67271
  Classification -> best τ=0.455 (val F1=0.3838)
  Directional -> Accuracy: 0.5278, MCC: 0.0622, F1: 0.5405

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.59931 | val 0.96734
  Epoch 016 - train 0.46822 | val 1.21341
  Classification -> best τ=0.435 (val F1=0.1874)
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.63464 | val 0.95842
  Epoch 016 - train 0.54936 | val 1.27486
  Classification -> best τ=0.310 (val F1=0.3634)
  Directional -> Accuracy: 0.4848, MCC: 0.0704, F1: 0.3462

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.47283 | val 0.77573
  Epoch 019 - train 0.31385 | val 1.89505
  Classification -> best τ=0.540 (val F1=0.3001)
  Directional -> Accuracy: 0.6190, MCC: 0.3091, F1: 0.5000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.54724 | val 0.94617
  Epoch 016 - train 0.47074 | val 0.92248
  Classification -> best τ=0.515 (val F1=0.1815)
  Directional -> Accuracy: 0.5000, MCC: 0.0103, F1: 0.5172

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.56513 | val 0.82038
  Epoch 016 - train 0.41078 | val 1.03798
  Classification -> best τ=0.460 (val F1=0.2698)
  Directional -> Accuracy: 0.5000, MCC: -0.0393, F1: 0.5818

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.58752 | val 1.10227
  Epoch 020 - train 0.45662 | val 1.15604
  Classification -> best τ=0.550 (val F1=0.4011)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.58780 | val 1.29034
  Epoch 017 - train 0.50475 | val 2.65636
  Classification -> best τ=0.420 (val F1=0.3835)
  Directional -> Accuracy: 0.5676, MCC: 0.1401, F1: 0.5897

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.56785 | val 0.83873
  Epoch 016 - train 0.49817 | val 1.40007
  Classification -> best τ=0.490 (val F1=0.3873)
  Directional -> Accuracy: 0.5111, MCC: 0.0000, F1: 0.6765

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.46128 | val 1.33998
  Epoch 016 - train 0.30644 | val 2.44831
  Classification -> best τ=0.570 (val F1=0.4576)
  Directional -> Accuracy: 0.5000, MCC: -0.0138, F1: 0.5532

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.50996 | val 0.79874
  Epoch 020 - train 0.35158 | val 0.59409
  Classification -> best τ=0.535 (val F1=0.5261)
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.5455

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.66352 | val 0.75827
  Epoch 016 - train 0.60745 | val 1.16533
  Classification -> best τ=0.560 (val F1=0.2036)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.53361 | val 2.50375
  Epoch 016 - train 0.43700 | val 3.67555
  Classification -> best τ=0.705 (val F1=0.4452)
  Directional -> Accuracy: 0.5179, MCC: 0.0357, F1: 0.5091

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.65782 | val 0.80325
  Epoch 017 - train 0.55038 | val 0.82668
  Classification -> best τ=0.560 (val F1=0.2351)
  Directional -> Accuracy: 0.5660, MCC: 0.1322, F1: 0.6230

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.57651 | val 0.81685
  Epoch 020 - train 0.46649 | val 2.72893
  Classification -> best τ=0.890 (val F1=0.3303)
  Directional -> Accuracy: 0.4364, MCC: -0.2052, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.62746 | val 0.84204

[I 2026-02-22 19:16:10,559] Trial 289 finished with value: 0.30902364496463747 and parameters: {'feature_set': 'sector', 'model_type': 'BiGRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.4, 'batch_size': 16, 'learning_rate': 0.0075255839115296996, 'weight_decay': 0.000684429279953106, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 15, 'max_epochs': 20, 'huber_delta': 0.8261586187125441, 'early_stopping_min_delta': 0.0007058603286082323}. Best is trial 252 with value: 0.3108162738957727.

  Epoch 020 - train 0.56051 | val 0.75969
  Classification -> best τ=0.580 (val F1=0.2623)
  Directional -> Accuracy: 0.5167, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.30902364496463747
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.62665 | val 0.86938
  Epoch 016 - train 0.58387 | val 1.36807
  Classification -> best τ=0.690 (val F1=0.2510)
  Directional -> Accuracy: 0.5526, MCC: 0.0000, F1: 0.0000

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.55003 | val 1.23202
  Epoch 016 - train 0.49334 | val 1.26391
  Classification -> best τ=0.525 (val F1=0.0732)
  Directional -> Accuracy: 0.6000, MCC: 0.1500, F1: 0.6897

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.58881 | val 1.08940
  Epoch 016 - train 0.55130 | val 1.62443
  Classification -> best τ=0.690 (val F1=0.2311)
  Directional -> Accuracy: 0.4565, MCC: -0.0996, F1: 0.0741

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.61968 | val 0.83809
  Epoch 020 - train 0.51937 | val 0.69731
  Classification -> best τ=0.500 (val F1=0.2030)
  Directional -> Accuracy: 0.5405, MCC: 0.0000, F1: 0.7018

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.54718 | val 1.17171
  Epoch 017 - train 0.45751 | val 0.81682
  Classification -> best τ=0.565 (val F1=0.5079)
  Directional -> Accuracy: 0.6800, MCC: 0.3677, F1: 0.6667

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.49573 | val 0.65379
  Epoch 020 - train 0.46442 | val 1.29778
  Classification -> best τ=0.530 (val F1=0.4379)
  Directional -> Accuracy: 0.5217, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.62017 | val 0.87478
  Epoch 017 - train 0.52912 | val 1.20226
  Classification -> best τ=0.510 (val F1=0.2536)
  Directional -> Accuracy: 0.5588, MCC: 0.0903, F1: 0.4643

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.58893 | val 0.58009
  Epoch 020 - train 0.38881 | val 2.04145
  Classification -> best τ=0.215 (val F1=0.3094)
  Directional -> Accuracy: 0.5238, MCC: 0.0000, F1: 0.3750

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.59843 | val 1.21240
  Epoch 016 - train 0.53692 | val 2.00088
  Classification -> best τ=0.525 (val F1=0.2927)
  Directional -> Accuracy: 0.5208, MCC: 0.0527, F1: 0.5106

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.60481 | val 0.92411
  Epoch 020 - train 0.57857 | val 0.95836
  Classification -> best τ=0.640 (val F1=0.2251)
  Directional -> Accuracy: 0.4638, MCC: -0.1168, F1: 0.3273

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.60840 | val 0.79569
  Epoch 020 - train 0.45443 | val 0.75836
  Classification -> best τ=0.675 (val F1=0.2484)
  Directional -> Accuracy: 0.5714, MCC: 0.1118, F1: 0.1600

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.62741 | val 0.94979
  Epoch 016 - train 0.54210 | val 1.41479
  Classification -> best τ=0.475 (val F1=0.0688)
  Directional -> Accuracy: 0.6667, MCC: 0.3408, F1: 0.7077

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.53839 | val 1.46730
  Epoch 016 - train 0.44700 | val 3.25633
  Classification -> best τ=0.415 (val F1=0.1923)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.6230

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.65182 | val 0.67019
  Epoch 020 - train 0.52311 | val 1.16405
  Classification -> best τ=0.500 (val F1=0.3118)
  Directional -> Accuracy: 0.5333, MCC: 0.1111, F1: 0.2222

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.62910 | val 0.75295
  Epoch 020 - train 0.49432 | val 1.04647
  Classification -> best τ=0.540 (val F1=0.2078)
  Directional -> Accuracy: 0.5490, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.60401 | val 0.80187
  Epoch 016 - train 0.55243 | val 0.96130
  Classification -> best τ=0.425 (val F1=0.2341)
  Directional -> Accuracy: 0.5362, MCC: 0.0000, F1: 0.6981

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.59563 | val 0.95288
  Epoch 017 - train 0.52274 | val 1.40639
  Classification -> best τ=0.895 (val F1=0.1842)
  Directional -> Accuracy: 0.3793, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.62183 | val 0.96645
  Epoch 016 - train 0.52892 | val 0.99521
  Classification -> best τ=0.565 (val F1=0.2220)
  Directional -> Accuracy: 0.4000, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.56904 | val 1.31688
  Epoch 016 - train 0.51954 | val 1.64326
  Classification -> best τ=0.410 (val F1=0.4199)
  Directional -> Accuracy: 0.5469, MCC: 0.0757, F1: 0.6027

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.58121 | val 0.94618
  Epoch 019 - train 0.45124 | val 1.32043
  Classification -> best τ=0.700 (val F1=0.2617)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.59265 | val 1.32467
  Epoch 018 - train 0.47888 | val 2.82335
  Classification -> best τ=0.425 (val F1=0.2800)
  Directional -> Accuracy: 0.4255, MCC: 0.0834, F1: 0.1818

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.62052 | val 0.97670
  Epoch 016 - train 0.54577 | val 1.25125
  Classification -> best τ=0.475 (val F1=0.3356)
  Directional -> Accuracy: 0.5846, MCC: 0.1910, F1: 0.6747

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.66321 | val 0.67741
  Epoch 020 - train 0.57725 | val 0.72404
  Classification -> best τ=0.365 (val F1=0.4778)
  Directional -> Accuracy: 0.6140, MCC: 0.2667, F1: 0.7442

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.62377 | val 0.75788
  Epoch 018 - train 0.48795 | val 1.14025
  Classification -> best τ=0.420 (val F1=0.1695)
  Directional -> Accuracy: 0.4154, MCC: -0.1664, F1: 0.4242

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.58969 | val 0.86223
  Epoch 016 - train 0.44851 | val 1.06611
  Classification -> best τ=0.440 (val F1=0.5489)
  Directional -> Accuracy: 0.5273, MCC: 0.0669, F1: 0.5185

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.53048 | val 1.90895
  Epoch 016 - train 0.38152 | val 2.94812
  Classification -> best τ=0.630 (val F1=0.1890)
  Directional -> Accuracy: 0.5778, MCC: 0.1058, F1: 0.4242

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.61609 | val 0.69906
  Epoch 020 - train 0.49696 | val 0.87037
  Classification -> best τ=0.585 (val F1=0.1105)
  Directional -> Accuracy: 0.5238, MCC: 0.1452, F1: 0.4118

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.55061 | val 1.03754
  Epoch 016 - train 0.48476 | val 1.62654
  Classification -> best τ=0.335 (val F1=0.3147)
  Directional -> Accuracy: 0.4464, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.54344 | val 0.71997
  Epoch 020 - train 0.35641 | val 0.79634
  Classification -> best τ=0.405 (val F1=0.2267)
  Directional -> Accuracy: 0.5500, MCC: 0.0335, F1: 0.6897

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.61194 | val 0.65018
  Epoch 020 - train 0.47904 | val 1.59971
  Classification -> best τ=0.505 (val F1=0.5410)
  Directional -> Accuracy: 0.4762, MCC: -0.0374, F1: 0.5217

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.59211 | val 0.69933
  Epoch 020 - train 0.49560 | val 0.90789
  Classification -> best τ=0.470 (val F1=0.2357)
  Directional -> Accuracy: 0.5714, MCC: 0.1718, F1: 0.7188

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.56037 | val 0.83350
  Epoch 016 - train 0.47363 | val 1.20560
  Classification -> best τ=0.405 (val F1=0.3850)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.59213 | val 1.10436
  Epoch 016 - train 0.51512 | val 1.13366
  Classification -> best τ=0.675 (val F1=0.2267)
  Directional -> Accuracy: 0.4444, MCC: 0.0000, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.51180 | val 1.48737
  Epoch 016 - train 0.49676 | val 1.20559
  Classification -> best τ=0.485 (val F1=0.2717)
  Directional -> Accuracy: 0.4651, MCC: -0.0670, F1: 0.5660

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.57171 | val 0.81180
  Epoch 019 - train 0.51323 | val 1.40247
  Classification -> best τ=0.275 (val F1=0.3490)
  Directional -> Accuracy: 0.5909, MCC: 0.2279, F1: 0.5714

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.49783 | val 0.68064
  Epoch 020 - train 0.36446 | val 1.00514
  Classification -> best τ=0.515 (val F1=0.3828)
  Directional -> Accuracy: 0.5714, MCC: 0.2197, F1: 0.4000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.54699 | val 0.95292
  Epoch 016 - train 0.45278 | val 1.17407
  Classification -> best τ=0.575 (val F1=0.2110)
  Directional -> Accuracy: 0.5357, MCC: 0.1132, F1: 0.6061

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.52827 | val 0.81521
  Epoch 016 - train 0.40447 | val 0.95457
  Classification -> best τ=0.390 (val F1=0.2118)
  Directional -> Accuracy: 0.3696, MCC: -0.1490, F1: 0.0645

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.59174 | val 0.93173
  Epoch 016 - train 0.48666 | val 1.10477
  Classification -> best τ=0.595 (val F1=0.4011)
  Directional -> Accuracy: 0.4375, MCC: 0.1482, F1: 0.5424

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.58296 | val 0.94686
  Epoch 016 - train 0.47913 | val 1.34978
  Classification -> best τ=0.470 (val F1=0.2271)
  Directional -> Accuracy: 0.5000, MCC: 0.0466, F1: 0.6476

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.61829 | val 0.77153
  Epoch 017 - train 0.55785 | val 0.69267
  Classification -> best τ=0.480 (val F1=0.2874)
  Directional -> Accuracy: 0.5333, MCC: 0.0672, F1: 0.5333

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.46721 | val 1.29213
  Epoch 016 - train 0.37082 | val 2.70319
  Classification -> best τ=0.555 (val F1=0.4588)
  Directional -> Accuracy: 0.6905, MCC: 0.3596, F1: 0.7636

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.56827 | val 0.92148
  Epoch 020 - train 0.37613 | val 0.68792
  Classification -> best τ=0.420 (val F1=0.6947)
  Directional -> Accuracy: 0.4167, MCC: 0.1615, F1: 0.5625

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.68050 | val 0.73032
  Epoch 018 - train 0.59815 | val 0.72529
  Classification -> best τ=0.580 (val F1=0.2132)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.54885 | val 1.75849
  Epoch 016 - train 0.44269 | val 1.58012
  Classification -> best τ=0.690 (val F1=0.3233)
  Directional -> Accuracy: 0.5179, MCC: 0.0333, F1: 0.4906

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.67115 | val 0.71322
  Epoch 016 - train 0.59596 | val 0.71186
  Classification -> best τ=0.545 (val F1=0.1847)
  Directional -> Accuracy: 0.5094, MCC: 0.0067, F1: 0.6486

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.55913 | val 2.75203
  Epoch 016 - train 0.47713 | val 2.53120
  Classification -> best τ=0.710 (val F1=0.0723)
  Directional -> Accuracy: 0.4909, MCC: -0.1839, F1: 0.6585

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.63602 | val 0.68646

[I 2026-02-22 19:21:19,127] Trial 290 finished with value: 0.28690517198933424 and parameters: {'feature_set': 'sector', 'model_type': 'BiGRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.4, 'batch_size': 16, 'learning_rate': 0.00534000700197162, 'weight_decay': 0.0005306316922798522, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 15, 'max_epochs': 20, 'huber_delta': 0.8280668645068163, 'early_stopping_min_delta': 0.0007084694873812332}. Best is trial 252 with value: 0.3108162738957727.

  Epoch 020 - train 0.51807 | val 1.94154
  Classification -> best τ=0.500 (val F1=0.3056)
  Directional -> Accuracy: 0.5167, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.28690517198933424
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.63688 | val 1.01050
  Epoch 016 - train 0.57548 | val 1.53621
  Classification -> best τ=0.520 (val F1=0.1635)
  Directional -> Accuracy: 0.5789, MCC: 0.1534, F1: 0.5429

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.52828 | val 0.91900
  Epoch 016 - train 0.47822 | val 0.89748
  Classification -> best τ=0.580 (val F1=0.2523)
  Directional -> Accuracy: 0.5556, MCC: 0.0891, F1: 0.6154

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.57484 | val 1.05793
  Epoch 016 - train 0.51336 | val 0.91015
  Classification -> best τ=0.685 (val F1=0.3114)
  Directional -> Accuracy: 0.4565, MCC: -0.0996, F1: 0.0741

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.64019 | val 0.87124
  Epoch 016 - train 0.59697 | val 0.87309
  Classification -> best τ=0.555 (val F1=0.1725)
  Directional -> Accuracy: 0.4595, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.57190 | val 0.70767
  Epoch 020 - train 0.44444 | val 0.95549
  Classification -> best τ=0.500 (val F1=0.4414)
  Directional -> Accuracy: 0.6600, MCC: 0.3203, F1: 0.6667

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.57341 | val 0.68635
  Epoch 019 - train 0.38379 | val 0.96340
  Classification -> best τ=0.620 (val F1=0.3525)
  Directional -> Accuracy: 0.5217, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.64993 | val 0.72835
  Epoch 017 - train 0.56273 | val 0.86920
  Classification -> best τ=0.570 (val F1=0.3110)
  Directional -> Accuracy: 0.5294, MCC: -0.0521, F1: 0.2727

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.50155 | val 0.96512
  Epoch 020 - train 0.37168 | val 1.47303
  Classification -> best τ=0.185 (val F1=0.3158)
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.59866 | val 1.86023
  Epoch 016 - train 0.54481 | val 3.09149
  Classification -> best τ=0.595 (val F1=0.3433)
  Directional -> Accuracy: 0.6250, MCC: 0.2698, F1: 0.6250

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.59294 | val 1.03456
  Epoch 016 - train 0.52499 | val 1.32905
  Classification -> best τ=0.460 (val F1=0.1910)
  Directional -> Accuracy: 0.4783, MCC: 0.0054, F1: 0.5135

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.60654 | val 0.93808
  Epoch 016 - train 0.54980 | val 1.67877
  Classification -> best τ=0.620 (val F1=0.3072)
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.62739 | val 0.92340
  Epoch 018 - train 0.47600 | val 1.47267
  Classification -> best τ=0.440 (val F1=0.2162)
  Directional -> Accuracy: 0.5088, MCC: 0.0000, F1: 0.6744

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.58595 | val 2.66350
  Epoch 017 - train 0.41658 | val 2.82341
  Classification -> best τ=0.590 (val F1=0.2193)
  Directional -> Accuracy: 0.5238, MCC: -0.1419, F1: 0.0000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.64238 | val 1.26026
  Epoch 020 - train 0.48232 | val 1.07912
  Classification -> best τ=0.380 (val F1=0.3378)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.63814 | val 1.03857
  Epoch 016 - train 0.56475 | val 1.49295
  Classification -> best τ=0.560 (val F1=0.1843)
  Directional -> Accuracy: 0.5490, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.66748 | val 0.70641
  Epoch 020 - train 0.55073 | val 1.45420
  Classification -> best τ=0.590 (val F1=0.2430)
  Directional -> Accuracy: 0.5072, MCC: 0.0220, F1: 0.5000

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.61924 | val 1.05570
  Epoch 020 - train 0.48481 | val 1.29534
  Classification -> best τ=0.285 (val F1=0.3128)
  Directional -> Accuracy: 0.4310, MCC: 0.1135, F1: 0.1951

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.62720 | val 0.68544
  Epoch 020 - train 0.55482 | val 0.82793
  Classification -> best τ=0.570 (val F1=0.2220)
  Directional -> Accuracy: 0.4000, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.61149 | val 0.90399
  Epoch 016 - train 0.55631 | val 1.09499
  Classification -> best τ=0.430 (val F1=0.2752)
  Directional -> Accuracy: 0.5312, MCC: 0.0683, F1: 0.5588

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.55849 | val 0.93678
  Epoch 016 - train 0.49209 | val 1.18594
  Classification -> best τ=0.590 (val F1=0.2937)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.62089 | val 0.73102
  Epoch 020 - train 0.44819 | val 0.71312
  Classification -> best τ=0.360 (val F1=0.3251)
  Directional -> Accuracy: 0.5532, MCC: 0.2260, F1: 0.5116

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.63107 | val 1.02501
  Epoch 016 - train 0.53312 | val 1.50191
  Classification -> best τ=0.510 (val F1=0.3437)
  Directional -> Accuracy: 0.4923, MCC: -0.0027, F1: 0.0571

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.64867 | val 0.63488
  Epoch 020 - train 0.58126 | val 0.72125
  Classification -> best τ=0.760 (val F1=0.4108)
  Directional -> Accuracy: 0.5789, MCC: 0.1613, F1: 0.6000

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.64572 | val 0.87164
  Epoch 016 - train 0.53996 | val 0.91915
  Classification -> best τ=0.480 (val F1=0.2111)
  Directional -> Accuracy: 0.4615, MCC: -0.0625, F1: 0.5570

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.58331 | val 1.06095
  Epoch 016 - train 0.51816 | val 1.18077
  Classification -> best τ=0.420 (val F1=0.4688)
  Directional -> Accuracy: 0.5455, MCC: 0.0930, F1: 0.5614

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.51162 | val 1.90742
  Epoch 016 - train 0.42337 | val 2.58742
  Classification -> best τ=0.595 (val F1=0.4193)
  Directional -> Accuracy: 0.4889, MCC: 0.1591, F1: 0.6102

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.61140 | val 0.70522
  Epoch 017 - train 0.52397 | val 0.92161
  Classification -> best τ=0.565 (val F1=0.1936)
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.0000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.57909 | val 0.95173
  Epoch 016 - train 0.43860 | val 1.73733
  Classification -> best τ=0.415 (val F1=0.2850)
  Directional -> Accuracy: 0.4464, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.52786 | val 1.62907
  Epoch 017 - train 0.42048 | val 1.57654
  Classification -> best τ=0.515 (val F1=0.3518)
  Directional -> Accuracy: 0.5750, MCC: 0.1240, F1: 0.7119

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.61524 | val 1.13172
  Epoch 016 - train 0.55551 | val 2.10021
  Classification -> best τ=0.455 (val F1=0.3630)
  Directional -> Accuracy: 0.5238, MCC: 0.0853, F1: 0.6154

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.59352 | val 0.84741
  Epoch 020 - train 0.50390 | val 0.73642
  Classification -> best τ=0.400 (val F1=0.2357)
  Directional -> Accuracy: 0.5714, MCC: 0.1718, F1: 0.7188

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.53096 | val 0.68743
  Epoch 016 - train 0.47644 | val 0.82968
  Classification -> best τ=0.480 (val F1=0.2488)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.62266 | val 0.68425
  Epoch 019 - train 0.53836 | val 0.73359
  Classification -> best τ=0.375 (val F1=0.4667)
  Directional -> Accuracy: 0.4583, MCC: -0.0935, F1: 0.5063

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.53557 | val 1.13965
  Epoch 016 - train 0.45491 | val 1.36855
  Classification -> best τ=0.390 (val F1=0.2717)
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.62266 | val 1.06029
  Epoch 017 - train 0.52247 | val 1.47113
  Classification -> best τ=0.455 (val F1=0.3430)
  Directional -> Accuracy: 0.5303, MCC: 0.0907, F1: 0.5231

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.55036 | val 0.92360
  Epoch 017 - train 0.38839 | val 2.04548
  Classification -> best τ=0.475 (val F1=0.3828)
  Directional -> Accuracy: 0.5952, MCC: 0.2656, F1: 0.4516

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.49135 | val 1.01639
  Epoch 016 - train 0.43034 | val 1.21480
  Classification -> best τ=0.565 (val F1=0.2332)
  Directional -> Accuracy: 0.5000, MCC: -0.0910, F1: 0.1250

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.53257 | val 1.71941
  Epoch 016 - train 0.40133 | val 1.45925
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.6087, MCC: 0.0000, F1: 0.7568

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.61293 | val 0.79009
  Epoch 019 - train 0.46265 | val 0.85652
  Classification -> best τ=0.450 (val F1=0.4011)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.58731 | val 1.06162
  Epoch 018 - train 0.48470 | val 1.33560
  Classification -> best τ=0.360 (val F1=0.3163)
  Directional -> Accuracy: 0.4865, MCC: 0.0000, F1: 0.6545

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.63990 | val 0.68863
  Epoch 020 - train 0.52520 | val 0.91532
  Classification -> best τ=0.500 (val F1=0.4632)
  Directional -> Accuracy: 0.6222, MCC: 0.2485, F1: 0.6047

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.52553 | val 1.40318
  Epoch 016 - train 0.34619 | val 2.54725
  Classification -> best τ=0.590 (val F1=0.4588)
  Directional -> Accuracy: 0.6667, MCC: 0.3043, F1: 0.7407

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.61228 | val 0.67635
  Epoch 020 - train 0.47953 | val 0.59896
  Classification -> best τ=0.565 (val F1=0.5249)
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.5455

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.66026 | val 0.68763
  Epoch 020 - train 0.57865 | val 1.16667
  Classification -> best τ=0.585 (val F1=0.2374)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.54689 | val 2.07232
  Epoch 016 - train 0.40180 | val 3.47423
  Classification -> best τ=0.615 (val F1=0.3104)
  Directional -> Accuracy: 0.4821, MCC: -0.0124, F1: 0.6234

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.68038 | val 0.68207
  Epoch 020 - train 0.56126 | val 0.85390
  Classification -> best τ=0.545 (val F1=0.2905)
  Directional -> Accuracy: 0.5283, MCC: 0.0546, F1: 0.6269

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.54947 | val 2.08287
  Epoch 016 - train 0.47163 | val 2.67862
  Classification -> best τ=0.750 (val F1=0.0602)
  Directional -> Accuracy: 0.4182, MCC: -0.2537, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.64703 | val 0.69931

[I 2026-02-22 19:26:23,804] Trial 291 finished with value: 0.2990936924446411 and parameters: {'feature_set': 'sector', 'model_type': 'BiGRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.4, 'batch_size': 16, 'learning_rate': 0.007289840277997267, 'weight_decay': 0.0006940051514968004, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 15, 'max_epochs': 20, 'huber_delta': 0.8071808696450138, 'early_stopping_min_delta': 0.0007521401056699011}. Best is trial 252 with value: 0.3108162738957727.

  Epoch 016 - train 0.53692 | val 0.67810
  Classification -> best τ=0.405 (val F1=0.2732)
  Directional -> Accuracy: 0.5333, MCC: 0.0578, F1: 0.3636

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2990936924446411
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean', 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector', 'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector', 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector', 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower', 'market_close', 'sector_rel_strength', 'sector_dispersion_1d']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.70115 | val 0.67626
  Epoch 020 - train 0.69425 | val 0.67394
  Classification -> best τ=0.465 (val F1=0.2158)
  Directional -> Accuracy: 0.5526, MCC: 0.1311, F1: 0.5750

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.74349 | val 0.67636
  Epoch 017 - train 0.73911 | val 0.67415
  Classification -> best τ=0.430 (val F1=0.3086)
  Directional -> Accuracy: 0.4222, MCC: -0.0618, F1: 0.1875

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.69966 | val 0.75757
  Epoch 016 - train 0.71212 | val 0.75683
  Classification -> best τ=0.520 (val F1=0.0440)
  Directional -> Accuracy: 0.3913, MCC: -0.2753, F1: 0.0667

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.70656 | val 0.68966
  Epoch 016 - train 0.71250 | val 0.68929
  Classification -> best τ=0.540 (val F1=0.2042)
  Directional -> Accuracy: 0.4459, MCC: -0.1085, F1: 0.4675

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.68278 | val 0.70425
  Epoch 016 - train 0.67945 | val 0.69986
  Classification -> best τ=0.545 (val F1=0.2332)
  Directional -> Accuracy: 0.4800, MCC: 0.0000, F1: 0.0000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.68137 | val 0.70125
  Epoch 016 - train 0.67232 | val 0.70159
  Classification -> best τ=0.505 (val F1=0.3210)
  Directional -> Accuracy: 0.5217, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.69595 | val 0.69912
  Epoch 016 - train 0.70759 | val 0.69887
  Classification -> best τ=0.450 (val F1=0.1703)
  Directional -> Accuracy: 0.3971, MCC: -0.0654, F1: 0.5393

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.69720 | val 0.64971
  Epoch 019 - train 0.71924 | val 0.64773
  Classification -> best τ=0.440 (val F1=0.0668)
  Directional -> Accuracy: 0.4524, MCC: -0.2178, F1: 0.1481

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.70634 | val 0.69153
  Epoch 020 - train 0.71829 | val 0.69560
  Classification -> best τ=0.525 (val F1=0.4022)
  Directional -> Accuracy: 0.5417, MCC: -0.1286, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.70111 | val 0.71111
  Epoch 016 - train 0.70931 | val 0.71180
  Classification -> best τ=0.485 (val F1=0.0367)
  Directional -> Accuracy: 0.4203, MCC: 0.0000, F1: 0.5918

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.71014 | val 0.88227
  Epoch 016 - train 0.70998 | val 0.89743
  Classification -> best τ=0.610 (val F1=0.0350)
  Directional -> Accuracy: 0.4490, MCC: -0.0306, F1: 0.5970

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.69148 | val 0.73127
  Epoch 016 - train 0.70209 | val 0.73005
  Classification -> best τ=0.395 (val F1=0.2157)
  Directional -> Accuracy: 0.5088, MCC: 0.0000, F1: 0.6744

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.69947 | val 0.77914
  Epoch 016 - train 0.67943 | val 0.78650
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.6230

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.69499 | val 0.65168
  Epoch 020 - train 0.69299 | val 0.64502
  Classification -> best τ=0.485 (val F1=0.4317)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.70079 | val 0.70195
  Epoch 018 - train 0.71366 | val 0.70615
  Classification -> best τ=0.585 (val F1=0.2571)
  Directional -> Accuracy: 0.5098, MCC: -0.0863, F1: 0.1379

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.70832 | val 0.75134
  Epoch 016 - train 0.70861 | val 0.75160
  Classification -> best τ=0.465 (val F1=0.1850)
  Directional -> Accuracy: 0.4493, MCC: -0.0753, F1: 0.2963

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.69878 | val 0.68892
  Epoch 016 - train 0.69208 | val 0.69342
  Classification -> best τ=0.465 (val F1=0.2882)
  Directional -> Accuracy: 0.6034, MCC: 0.3185, F1: 0.5818

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.68518 | val 0.72316
  Epoch 016 - train 0.68102 | val 0.73079
  Classification -> best τ=0.405 (val F1=0.2167)
  Directional -> Accuracy: 0.6000, MCC: 0.1147, F1: 0.7059

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.69813 | val 0.68001
  Epoch 020 - train 0.68785 | val 0.68016
  Classification -> best τ=0.450 (val F1=0.2620)
  Directional -> Accuracy: 0.5781, MCC: 0.0000, F1: 0.7327

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.68844 | val 0.68429
  Epoch 020 - train 0.68073 | val 0.68793
  Classification -> best τ=0.335 (val F1=0.2053)
  Directional -> Accuracy: 0.4595, MCC: 0.0249, F1: 0.1304

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.71056 | val 0.69467
  Epoch 018 - train 0.70920 | val 0.69597
  Classification -> best τ=0.455 (val F1=0.1825)
  Directional -> Accuracy: 0.6170, MCC: 0.0000, F1: 0.7632

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.71397 | val 0.73083
  Epoch 016 - train 0.70562 | val 0.72884
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5077, MCC: 0.0000, F1: 0.6735

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.70013 | val 0.71282
  Epoch 016 - train 0.70171 | val 0.71344
  Classification -> best τ=0.530 (val F1=0.1803)
  Directional -> Accuracy: 0.5789, MCC: 0.1706, F1: 0.5862

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.69501 | val 0.69895
  Epoch 020 - train 0.70661 | val 0.69564
  Classification -> best τ=0.540 (val F1=0.1393)
  Directional -> Accuracy: 0.4769, MCC: -0.0624, F1: 0.3704

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.69411 | val 0.69456
  Epoch 020 - train 0.70597 | val 0.68449
  Classification -> best τ=0.490 (val F1=0.4907)
  Directional -> Accuracy: 0.4545, MCC: -0.0319, F1: 0.1667

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.70051 | val 0.71580
  Epoch 016 - train 0.70442 | val 0.71729
  Classification -> best τ=0.435 (val F1=0.2035)
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.5938

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.73490 | val 0.72709
  Epoch 016 - train 0.72002 | val 0.73104
  Classification -> best τ=0.500 (val F1=0.1353)
  Directional -> Accuracy: 0.4286, MCC: -0.0468, F1: 0.1429

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.70889 | val 0.71332
  Epoch 016 - train 0.69339 | val 0.70847
  Classification -> best τ=0.490 (val F1=0.0068)
  Directional -> Accuracy: 0.5000, MCC: -0.0684, F1: 0.6216

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.70239 | val 0.81700
  Epoch 016 - train 0.67666 | val 0.81436
  Classification -> best τ=0.415 (val F1=0.4114)
  Directional -> Accuracy: 0.5750, MCC: 0.1459, F1: 0.6047

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.68346 | val 0.69430
  Epoch 020 - train 0.69833 | val 0.69154
  Classification -> best τ=0.505 (val F1=0.3450)
  Directional -> Accuracy: 0.4048, MCC: -0.1850, F1: 0.4444

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.70446 | val 0.72296
  Epoch 016 - train 0.71360 | val 0.72425
  Classification -> best τ=0.430 (val F1=0.3034)
  Directional -> Accuracy: 0.5476, MCC: 0.0310, F1: 0.6885

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.70097 | val 0.72509
  Epoch 016 - train 0.69552 | val 0.72587
  Classification -> best τ=0.515 (val F1=0.2150)
  Directional -> Accuracy: 0.5306, MCC: 0.0127, F1: 0.6849

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.68836 | val 0.72499
  Epoch 016 - train 0.69450 | val 0.72332
  Classification -> best τ=0.565 (val F1=0.1686)
  Directional -> Accuracy: 0.4861, MCC: 0.0845, F1: 0.2449

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.70042 | val 0.68192
  Epoch 017 - train 0.70484 | val 0.68191
  Classification -> best τ=0.415 (val F1=0.1874)
  Directional -> Accuracy: 0.4884, MCC: -0.0318, F1: 0.3889

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.67260 | val 0.69209
  Epoch 020 - train 0.70237 | val 0.69140
  Classification -> best τ=0.360 (val F1=0.3525)
  Directional -> Accuracy: 0.4848, MCC: 0.0323, F1: 0.4138

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.69963 | val 0.70035
  Epoch 016 - train 0.69505 | val 0.70197
  Classification -> best τ=0.530 (val F1=0.2409)
  Directional -> Accuracy: 0.5238, MCC: 0.0674, F1: 0.4444

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.70967 | val 0.76802
  Epoch 016 - train 0.68343 | val 0.76748
  Classification -> best τ=0.555 (val F1=0.1832)
  Directional -> Accuracy: 0.5536, MCC: 0.0965, F1: 0.1379

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.71707 | val 0.70730
  Epoch 020 - train 0.70057 | val 0.70970
  Classification -> best τ=0.550 (val F1=0.2783)
  Directional -> Accuracy: 0.4348, MCC: 0.0460, F1: 0.2353

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.72979 | val 0.67888
  Epoch 020 - train 0.71318 | val 0.67530
  Classification -> best τ=0.505 (val F1=0.2392)
  Directional -> Accuracy: 0.4167, MCC: -0.2751, F1: 0.1765

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.70684 | val 0.72419
  Epoch 016 - train 0.69551 | val 0.71669
  Classification -> best τ=0.605 (val F1=0.1345)
  Directional -> Accuracy: 0.6351, MCC: 0.2765, F1: 0.5574

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.69604 | val 0.83173
  Epoch 016 - train 0.69910 | val 0.83311
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5111, MCC: 0.0000, F1: 0.6765

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.70460 | val 0.68978
  Epoch 019 - train 0.69840 | val 0.68642
  Classification -> best τ=0.480 (val F1=0.3273)
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.7273

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.71212 | val 0.68025
  Epoch 020 - train 0.67668 | val 0.67656
  Classification -> best τ=0.495 (val F1=0.3458)
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.5455

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.70229 | val 0.69873
  Epoch 020 - train 0.70968 | val 0.69640
  Classification -> best τ=0.550 (val F1=0.1784)
  Directional -> Accuracy: 0.5455, MCC: 0.1826, F1: 0.3902

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.72322 | val 0.69267
  Epoch 020 - train 0.69805 | val 0.68895
  Classification -> best τ=0.500 (val F1=0.1883)
  Directional -> Accuracy: 0.5357, MCC: 0.0633, F1: 0.4348

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.71573 | val 0.71293
  Epoch 016 - train 0.72382 | val 0.71139
  Classification -> best τ=0.590 (val F1=0.1168)
  Directional -> Accuracy: 0.4906, MCC: 0.0000, F1: 0.0000

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.68221 | val 0.77576
  Epoch 016 - train 0.68617 | val 0.77711
  Classification -> best τ=0.510 (val F1=0.1209)
  Directional -> Accuracy: 0.5636, MCC: 0.1359, F1: 0.6923

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.69659 | val 0.68270

[I 2026-02-22 19:31:28,160] Trial 292 finished with value: 0.20972894853076393 and parameters: {'feature_set': 'sector', 'model_type': 'BiGRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.4, 'batch_size': 16, 'learning_rate': 7.184770372883886e-06, 'weight_decay': 0.0006690813590260184, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 15, 'max_epochs': 20, 'huber_delta': 0.7909262984689603, 'early_stopping_min_delta': 0.001139266704667616}. Best is trial 252 with value: 0.3108162738957727.

  Epoch 020 - train 0.68710 | val 0.68240
  Classification -> best τ=0.555 (val F1=0.2920)
  Directional -> Accuracy: 0.5167, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.20972894853076393
Saved Optuna results to ../results/benchmarking/classification/optuna_tuning_sector_1H.csv